### ISSUE TITLE
[Bug] Clarify media sync error message

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10000]
###### Reproduction Steps

1. Start a sync on a new device for a collection with a lot of media
2. Not sure. Probably do something such as remove internet access, move to a connection that requires condition (e.g. hotel, public transit)... Ensuring that media stop syncing, not requested by user
3. Look at error message

###### Expected Result
Let the user know what did occur and what can be done.

###### Actual Result
![Screenshot_20211217-065334](https://user-images.githubusercontent.com/357361/146888958-7118986c-a34d-47a0-937a-35cba6615948.png)

###### Debug info
You can for example let the user know the number of media that were downloaded and uploaded. You can also let them know that a new sync will sync more medias and they can do it until all media are synced.
If for some reason no media were synced at all but we were expecting to sync media, then let the user know that we tried to download or upload data but failed. They may try again or ask for help.

Good luck with making all of this small. But I believe more actionable advices and more explanation are needed

**Comment by david-allison-1** [comment]
This is a large cause of user support, and we can do much better with messaging here.

**Comment by puranjayK** [comment]
I would like to work on this issue
Can you assign it to me

**Comment by mikehardy** [comment]
Great! Go for it @puranjayK

**Comment by puranjayK** [comment]
@Arthur-Milchior @mikehardy @david-allison-1 could you help me out a bit with this error, since its my first issue in Anki Android.
What approach do I need to have here?

**Comment by Arthur-Milchior** [comment]
I can't answer for David and Mike, but personally, I'd find it hard to know how to help without a more specific question. I don't even know whether you know how to compile Ankidroid and run the compiled version on your phone/an emulator.

You may know that we usually discuss on discord. You may probably ask question there and find even more people who can answer a lot of beginner question.

**Comment by puranjayK** [comment]
I have run the compiled version on my emulator. 
Where can I get the link to the discord server? @Arthur-Milchior

**Comment by Arthur-Milchior** [comment]
https://discord.gg/qjzcRTx
Then you can search for the string in the screenshot, and search where it is used. 
Look at what number you can easily have access too in this part of the code.
Change the string to give the hint I mentioned and display those numbers

**Comment by puranjayK** [comment]
@Arthur-Milchior @david-allison-1 PTAL

**Comment by VaibhavAher219** [comment]
Has this issue been resolved because i am also interested in resolving it

**Comment by Arthur-Milchior** [comment]
Hi @VaibhavAher219. No, it has not been resolved. @puranjayK made a PR #10021 that still requires some work. @puranjayK, do you plan to still work on it ? I have not seen any news or feedback for two weeks. If you say you won't work on it or won't answer, then @VaibhavAher219, I'll be happy for you to work on it. You can take over the existing PR or work from scratch, as you prefer. 
I'd suggest waiting 48 hours so that we see if @puranjayK answer or not. But if you are confortable with the risk of having done duplicate work, you can start already

**Comment by VaibhavAher219** [comment]
actually I am a complete newbie to opensource I think I will wait and start from scratch can you please guide what is recommended?

**Comment by Arthur-Milchior** [comment]
@VaibhavAher219 Did you read the whole page? As @puranjayK did ask the same question, there is a chance the answer we already gave are still relevant. In particular about going on discord and discussing with people there to get interaction and help quicker

**Comment by puranjayK** [comment]
@Arthur-Milchior yes I still wanna work on the issue. Things were a bit difficult with the pandemic rising again in India. I'll get back to the issue

**Comment by Arthur-Milchior** [comment]
Thanks for the update @puranjayK. Thanks for your interest. I'm sorry to read that. Do you have any idea when you'll have time for it?
There is no emergency. I only want to get an idea of how much time we reserve the issue.

@VaibhavAher219 did you had the opportunity to start working on it?

**Comment by puranjayK** [comment]
> Thanks for the update @puranjayK. Thanks for your interest. I'm sorry to read that. Do you have any idea when you'll have time for it? There is no emergency. I only want to get an idea of how much time we reserve the issue.
> 
> @VaibhavAher219 did you had the opportunity to start working on it?

I'll try to finish it by the end of the week
