### ISSUE TITLE
Convert the string:export_email_text_new text into Hindi language

### ISSUE THREAD

**Issue by AayushSolanki** [ankidroid/Anki-Android#10001]
[Anki-Android/AnkiDroid/src/main/res/values-hi/02-strings.xml](url)

String text should be in Hindi
Lines 191 to 195
`   <string name="export_email_text_new"><![CDATA[        Hi!
        <br/><br/>
        This is an Anki flashcards deck sent from <a href="%1$s">AnkiDroid</a>.
        Try to open it using one of the available <a href="%2$s">Anki distributions</a> and enjoy easy and efficient learning!
        ]]></string>`

**Comment by david-allison-1** [comment]
Thanks for the report!

Please use [CrowdIn](https://crowdin.com/project/ankidroid) for string related issues and fixes. 

Feel free to make the change yourself on CrowdIn.
