### ISSUE TITLE
Misleading toast message on clicking "Send troubleshooting report"

### ISSUE THREAD

**Issue by ShridharGoel** [ankidroid/Anki-Android#10029]
A toast containing this message is displayed on clicking "Send troubleshooting report":
`AnkiDroid has encountered a problem; a report is being sent to the developers`

Can we use better terminology here? The above message makes it seem like that the app crashed or something went wrong even though the user themselves clicked the troubleshoot option to send a report. It is possible that AnkiDroid encountered no problem and the user wanted to report some other issue.

**Comment by AayushSolanki** [comment]
![Screenshot_20220102-221015 155](https://user-images.githubusercontent.com/75438613/148100039-2f9f6fa1-ede8-49fd-b23b-064cd933c65d.png)

@mikehardy @david-allison-1 i think we should remove the toast as it doesn't make any sense because we have the dailog box.
looking for your suggestions

**Comment by david-allison-1** [comment]
> ![Screenshot_20220102-221015 155](https://user-images.githubusercontent.com/75438613/148100039-2f9f6fa1-ede8-49fd-b23b-064cd933c65d.png)
> 
> @mikehardy @david-allison-1 i think we should remove the toast as it doesn't make any sense because we have the dailog box.
> looking for your suggestions
> 

If you can do so in this instance, without removing the toast in the general case, then that sounds like a good solution.

**Comment by AayushSolanki** [comment]
@david-allison-1  actually i was thinking to remove the toast _AnkiDroid has encountered a problem; a report is being generated..._  because it is of no use to the user so can i work upon these?

**Comment by david-allison-1** [comment]
> @david-allison-1  actually i was thinking to remove the toast _AnkiDroid has encountered a problem; a report is being generated..._  because it is of no use to the user so can i work upon these?

Personally: We should inform the user if we're sending their data to our crash reporting servers.

* We're informing them that a problem occurred with an operation
* It's a reminder that the automatic crash reporting is enabled
* It's a confirmation that the manual crash reporting succeeded

I'd be happy with a wording change for the manual dialog/report, but I don't feel it should be removed.

**Comment by mikehardy** [comment]
The toast must stay, if you choose "report every time without asking" you never get a dialog if I recall correctly, the toast is the only way we inform users their data was collected + sent

**Comment by ShridharGoel** [comment]
@mikehardy In the issue I wanted to mention about the message that shows when the users himself/herself clicks on the "Send troubleshooting report" option.

**Comment by david-allison-1** [comment]
The "manual" and "auto" strings are distinct. 

I feel this can be fixed with a bit of thought about the text. @ShridharGoel, would this be an acceptable fix, or would you prefer the toast was completely disabled in this case.

https://github.com/ankidroid/Anki-Android/blob/19641103a8eb9d6931c1495ad696ff610a2e0973/AnkiDroid/src/main/res/values/05-feedback.xml#L29-L30

Usage:

https://github.com/ankidroid/Anki-Android/blob/aedf30eb48a9a5578b89c08ea544661f82397bc8/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L590-L602

**Comment by ShridharGoel** [comment]
> I feel this can be fixed with a bit of thought about the manual text. @ShridharGoel, would this be an acceptable fix, or would you prefer the toast was completely disabled in this case.

Yeah, just a change in the text should be fine. Something like "A report is being generated for the reference of developers" would be good.

Also, the report is sent only after the user clicks "Report", right?

**Comment by david-allison-1** [comment]
> Also, the report is sent only after the user clicks "Report", right?

`Never || Ask`

`Always` sends without a dialog

https://github.com/ankidroid/Anki-Android/blob/494bbbd5c08cfd40c573ac3d74f3bb262e72eaf7/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.kt#L259-L271

**Comment by ShridharGoel** [comment]
Please note that changing the text is only suitable for the case when the
user manually selects the troubleshooting option in the help section,
because of the possibility that there might not be any problem which was
encountered which makes the toast message invalid.

**Comment by AayushSolanki** [comment]
@david-allison-1 can i now change the manual_toast_text? if yes , could you please assign it to me.

**Comment by david-allison-1** [comment]
Sure

**Comment by AayushSolanki** [comment]
@david-allison-1 do i need to change every string or is there any other way?

**Comment by david-allison-1** [comment]
> @david-allison-1 do i need to change every string or is there any other way?

> Developers should basically ignore all resource folders that have non-English locales. Edit the English strings only, and one of the project owners will handle the syncing of the translations. 

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations

In this case, we want to force a re-translation of the message, so change the message and the key in English
