### ISSUE TITLE
[Bug] Charts by hour are inconsistent before and after changing language

### ISSUE THREAD

**Issue by zkl-ai** [ankidroid/Anki-Android#10022]
###### Reproduction Steps

1. click Statistics button
2. change the chart to HOURLY BREAKDOWN
3. select All decks
4. change the language to simplified Chinese
5. back to the chart of HOURLY BREAKDOWN

###### Expected Result
The chart of HOURLY BREAKDOWN should be the same before and after the language change.

###### Actual Result
![~NLTQPWP9 @@DF1NOX5TI95](https://user-images.githubusercontent.com/72965042/147309864-a1ba460b-d902-44d6-9c5c-38afef8f1ce7.png)
![29{Y`4{@%DHJ1C67M9_(YQC](https://user-images.githubusercontent.com/72965042/147309874-9b428386-97b5-4776-8046-f6cac77ab3ca.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by zkl-ai** [comment]
And I have restarted the app, and the chart still different. When the language is English, it is empty. And when the language is simplified Chinese or Japanese which I have tried, it is not empty.

**Comment by BrayanDSO** [comment]
Couldn't reproduce. 
Tried with English, Portuguese, simplified chinese and Japanese, they all look the same here
