### ISSUE TITLE
Allocate larger memory buffers for sizy cards

### ISSUE THREAD

**Issue by camerooncameroon** [ankidroid/Anki-Android#10024]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a problem: when I use Image occlusion cards on Ankidroid, the images/masks are almost always redrawn (and zoom/position reset) when tapping on 'Answer' button (except ~10% cases when the red mask opens smoothly).
It is purely a cosmetic issue (because everything else is working fine), but it damages the testing experience, as the focus is lost and you need to find where you were looking at before (the mask in question position).
It's okay yet when the image is fully fit into the screen (mainly in portrait layout), but if you enlarge the image (which is often required with the IO cards on mobiles), after hitting the 'Answer' button the zoom and position is reset, so you have to search for where you've been before and what occlusion you've been answering.
At the same time, the 'Toggle masks' button works very smooth (the image remains steady, only the masks are toggled on/off, which is the ideal behavior in my opinion).

**Describe the solution you'd like**
I'd like that the reveal Answer behaviour is smooth like when you tap "Toggle masks' button, the background image isn't redrawn, the zoom and position is the same as before hitting the 'Answer' (i.e. not reset).
Perhaps it needs that Ankidroid allocates more memory for the cards (specific types of notes/cards like the IO ones) or doesn't make the cards' images reset (redraw) - like it is with the 'Toggle masks' button now.

**Describe alternatives you've considered**
I've considered such alternatives as changing background image format (tried png/jpg), lowering images' sizes (resolutions as well as sizes in MB/kB's). The result was better, but only a little (a bit faster loading), anyway the redrawing / position/zoom lost thing remained the same.

I've also used the IO addon by @infinyte7 but this addon produced cards' behaviour is mostly the same as @glutanimate's addon made cards.

I've also tried different models of Android phones (including new models with Android 11 onboard and capable RAM/video acceleration modules).

I've also tried the same IO cards on Anki Desktop, where the reveal Answer behaviour was always smooth.

**Additional context**
P.S. Of course that's the addon's issue (not Ankidroid's) but I'm putting it here as this addon is rather widely used and is pretty common, and it's not actually the addon's bug I guess but rather its specific needs which require a bit more resources allocation from Ankidroid?

**Comment by infinyte7** [comment]
I think it is related to this https://github.com/ankidroid/Anki-Android/issues/7825
