### ISSUE TITLE
[Bug] "is:due" not filtering properly with "is:learn"

### ISSUE THREAD

**Issue by szalejot** [ankidroid/Anki-Android#10072]
###### Reproduction Steps

1. Browse or create filtered deck with the following filter: "is:learn is:due"

###### Expected Result

Filter returns only learning and re-learning cards, that are already due.

###### Actual Result

Filter returns all learning and re-learning cards. Even ones that are not due (for example will be due in an hour).
Filter returns expected results in the desktop Anki, tested on version: 2.1.49.

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 8.0.0

Manufacturer = asus

Model = ASUS_Z01HD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; ASUS_Z01HD Build/OPR1.170623.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = ffc51eb1-d4d4-4314-a51d-a8de3cb61665

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Curious if this still happens with latest alpha and new backend / v3 scheduler turned on in settings advanced https://github.com/ankidroid/Anki-Android/releases

**Comment by szalejot** [comment]
@mikehardy I just checked on AnkiDroid 2.16alpha91 with V3 support enabled. Then it works as it should - not buggy anymore.

**Comment by mikehardy** [comment]
That's great to hear. Okay, this is a bit unsatisfying as it may still be a problem on v2 but given new-backend/v3 is the future and we have limited time I'm going to resolve this as it will be fixed by default for the future then (even if v2 is left with an issue while it still exists...)

I really appreciate the testing, thank you

**Comment by szalejot** [comment]
Just tested on learning cards having intervals of less than a day: also works as it should - not buggy anymore.
