### ISSUE TITLE
Answer buttons disappear

### ISSUE THREAD

**Issue by NicolasMICAUX** [ankidroid/Anki-Android#10098]
When reviewing a card, with "full screen" mode on (hides top and lower bars), sometimes the answer buttons (easy, ... hard) flash (appear, disappear, ...)

It happens on some cards only (not all), but I cannot figure out a pattern (not especially big cards, or a specific type of cards,...)

AnkiDroid Version = 2.15.6

Android Version = 8.0.0

Manufacturer = Sony

Model = F8331

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; F8331 Build/41.3.A.2.192; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = ea0f99ab-eab5-48c0-aec8-58293f5bacb5

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by david-allison-1** [comment]
> When reviewing a card, with "full screen" mode on (hides top and lower bars), sometimes the answer buttons (easy, ... hard) flash (appear, disappear, ...)
> 
> It happens on some cards only (not all), but I cannot figure out a pattern (not especially big cards, or a specific type of cards,...)

Hi, thanks for the report. Could you fill out the bug reporting template?

Especially adding the information from "about ankidroid". This is potentially due to an Android OS issue

**Comment by NicolasMICAUX** [comment]
Yes, I don't know why, the template choice does not seem to appear on github page for phones.

### Reproduction Steps
(1.  I think the bug is due to setting "Full screen Mode > Mask system bars" (approximate translation from french UI) )
2. Revise somes cards
3. Sometimes (not always, answer buttons flash appear-disappear)

### Expected Result
answer buttons stand still, always displayed

### Actual Result
answer buttons flash appear-disappear

### Debug info
AnkiDroid Version = 2.15.6
Android Version = 8.0.0
Manufacturer = Sony
Model = F8331
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; F8331 Build/41.3.A.2.192; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36
ACRA UUID = ea0f99ab-eab5-48c0-aec8-58293f5bacb5
Scheduler = std
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

## SOME INSIGHTS ABOUT THE ISSUE
It is not the first time I have the bug, probably have it for a few monthes, from time to tilme.
**Here is a screen record showing the bug :**
https://user-images.githubusercontent.com/72763959/148404909-410def03-de44-47ab-90b7-ded8b3bf846f.mp4

Some tests I made for diagnostic :
- Automatic rotation does not seem to change/trigger the bug.
- I thought maybe long URLs in the card may trigger the bug (because displayed out of the limits of the screen), but other cards have long urls without the bug.
- the bugg sometimes disappear when I switch off the screen then switch back on.

**Card template is "Cloze"**
RECTO
`{{cloze:Texte}}`
VERSO
`
{{cloze:Texte}}<br>
{{Verso Extra}}
`
STYLES/CSS
```
.card {
  font-family: Ubuntu;
  font-size: 20px;
  text-align: center;
  color: black;
  background-color: white;
  min-width: 15em;
  max-width: 33em;
  margin: 0 auto;
}

.cloze {
 font-weight: bold;
 color: red;
}
.cloze img {
 border: 5px solid red;
}

.nightMode .cloze {
 color: red;
}
```

FOR reproducing the bug, here is the card content 
```
besoin important d'estime de soi (besoin pr quoi ?) https://www.researchgate.net/publication/200008856_Leary_M_R_Sociometer_theory_and_the_pursuit_of_relational_value_Getting_to_the_root_of_self-esteem_European_Review_of_Social_Psychology_16_75-111

Plus sa motivation est {{c1::auto}}déterminée, plus l’élève développera et maintiendra les efforts indispensables aux franchissements des difficultés inhérentes à tout apprentissage

https://theconversation.com/estime-de-soi-et-difficultes-scolaires-un-cercle-vicieux-161384
```
or in HTML
```
besoin important d'estime de soi (besoin pr quoi ?)&nbsp;<a href="https://www.researchgate.net/publication/200008856_Leary_M_R_Sociometer_theory_and_the_pursuit_of_relational_value_Getting_to_the_root_of_self-esteem_European_Review_of_Social_Psychology_16_75-111">https://www.researchgate.net/publication/200008856_Leary_M_R_Sociometer_theory_and_the_pursuit_of_relational_value_Getting_to_the_root_of_self-esteem_European_Review_of_Social_Psychology_16_75-111</a><div>
</div><div>Plus sa motivation est {{c1::auto}}déterminée, plus l’élève développera et maintiendra les efforts indispensables aux franchissements des difficultés inhérentes à tout apprentissage
</div><div>
</div><div><a href="https://theconversation.com/estime-de-soi-et-difficultes-scolaires-un-cercle-vicieux-161384">https://theconversation.com/estime-de-soi-et-difficultes-scolaires-un-cercle-vicieux-161384</a>
</div>
```
(I'm using on my PC (synced collection) [this](https://ankiweb.net/shared/info/318752047) extension for adding/formatting hyperlinks.) maybe it does the bug.

**Comment by david-allison-1** [comment]
Android 8 has issues with hardware rendering. 

What's the value of `Settings - Advanced - Disable card hardware render`?

Ref: https://github.com/ankidroid/Anki-Android/commit/5386890a860d3473bad56f7344ea1211e44ad273

**Comment by NicolasMICAUX** [comment]
unchecked, I try to check it.

Ok, seems to solve the problem, thanks a lot !
