### ISSUE TITLE
Anki não funciona mais o TTS Definir idiomas para francês, Russo, Italiano, só funciona Ingles, portugues, Espanhol na lista dos Flashcards

### ISSUE THREAD

**Issue by fabiozonaleste** [ankidroid/Anki-Android#10099]
Ao entrar no card que criei do AnkiDroid, há anos deu tudo certo, mas ao instalar a versão nova no aparelho sansung x32, ao ir nos 3 pontos para "definir Idioma TTS" que antes era automático, só aparece opções "Selecionar Idiomas" = Não Fale, Ingles (EUA), Ingles (computador), Espanhol (méxico), Português (Brasil)

**Describe the solution you'd like**
Gostaria de que aparecesse na lista a opção dos outros idiomas como o Francês, Russo, e outros como na versão anterior. Detalhe, no aparelho anterior, com a versão anterior do anki, creio a versão 2.0, funciona ainda, amas só na versão atual com aparelho atual está apresentando problemas, mesmo seguindo as opções >configurações>avançado>adicionar texto para fala. Mesmo assim, no atual celular sansung x32 e atual Ankidroid, não resolve para outros idiomas como o Francês, Russo, e outros (eles não aparecem na lista)

**Describe alternatives you've considered**
Já instalei e reinstalei, tenho 13000 cartões frente que fiz com todo cuidado, pesquisas, cards de Francês desde o ano de 2019 e que agora não posso ouví-los, isso me frustra
Tenho cards Italianos de 1 ano de pesquisas e não consigo também colocar áudios em italiano.
Com o Russo tenho média de 400 cards que não consigo colocar áudios também

**Additional context**
Anexo, foto com a lista de idiomas que ficou limitado, pois mesmo correndo a tela do celular android, as opções Francês, Russo, Italiano não aparece

Contando com resposta favorável de vossa parte, desde já agradeço

Fabio Valente

![WhatsApp Image 2022-01-06 at 14 25 40](https://user-images.githubusercontent.com/97247422/148424840-ba737c5e-21a2-4277-81c1-ddb0d376ac63.jpeg)

**Comment by mikehardy** [comment]
Hi there! I believe this is under your control and you may install the voices that you like, including different languages if desired?

https://support.google.com/accessibility/android/answer/6006983?hl=en

**Comment by fabiozonaleste** [comment]
mikehardy Gotha !! I can this, now I'm go back for study, Thanks!!

> Hi there! I believe this is under your control and you may install the voices that you like, including different languages if desired?
> 
> https://support.google.com/accessibility/android/answer/6006983?hl=en

**Comment by mikehardy** [comment]
Great - I will close this since I think this will work for you, but if for some reason it does not work, please continue the conversation - we may reopen and work to fix it. 

Saludos desde su vecino en el ecuador ;-)
