### ISSUE TITLE
Marquee element for deck in custom study session.

### ISSUE THREAD

**Issue by Goudabroetchen** [ankidroid/Anki-Android#10094]
Sometimes I create a custom study session of combined decks.

Example:
Style of a random deck:
-Deckname
--Medicine
---Anatomy
--Languages
---German
---Dutch
---Spanish

Now I click on Languages for example - "Custom study" - "Review ahead" - "1 day" 

And I have to translate the word "Egg". Now I don't know in which language I have to translate. 
The header is just "Custom study session" 

My suggest would be to replace the headyer by a marquee element with the correct deck name, here: deckname:languages:german.

**Comment by david-allison-1** [comment]
You should be able to do this via adding `{{Deck}}` somewhere in the card template

**Comment by mikehardy** [comment]
How does anki desktop handle this (or AnkiMobile), just out of curiosity?

**Comment by david-allison-1** [comment]
Anki Desktop 2.1.49 doesn't display the deck name at all

**Comment by mikehardy** [comment]
okay, then it seems in the absence of upstream style to copy / stay consistent with, and knowing that deck names may get quite long so a general solution is somewhat complicated in addition to this not having come up before, I like the general direction of leaving it to users with a template change as that should really work...

**Comment by david-allison-1** [comment]
@Goudabroetchen - Our manual/communities (via the in-app "Help") should help with adding `{{Deck}}` to the appropriate card template(s) if you need assistance.

Thanks for reporting!
