### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Hisham7345** [ankidroid/Anki-Android#10100]
Hello,

I am a user from Yemen and I have been using Anki for a couple of years now and so far everything has been fine.
But suddenly, a problem has appeared with the synchronization. Each time I try to synchronize my ankidroid with the ankiweb version, I receive a message says : sync error, type: 400, message
 
![Screenshot_20220106-192521_AnkiDroid](https://user-images.githubusercontent.com/97251529/148448950-15a34743-3e98-4d16-bd66-8354658b1759.jpg)

The only one thing I did before the appearance of the problem is that I have left the reviewing of my decks for about a week. Then I came back to review and synchronize just like every time, but the problem showed up.

The debug info:
AnkiDroid Version = 2.10.3

Android Version = 10

ACRA UUID = a1be4257-12c8-430d-875a-182bb2b54250

I wish you could help me figure out how to solve this problem because I really feel desperate.

Sincerely yours,
Hisham Almarani

**Comment by mikehardy** [comment]
:thinking: 
This appears to be related to bad data in your collection somehow?
https://search.brave.com/search?q=ankiweb+syncing+error+400
check database and full sync is the answer most commonly referenced.

Possibly restore from a known good backup before it happened? But that implies you will lose review history from the time of the backup to the time it started happening, and may not fix it

**Comment by Hisham7345** [comment]
> Hello! 👋 Thanks for logging this issue. Please remember we are all volunteers here, so some patience may be required before we can get to the issue. Also remember that the fastest way to get resolution on an issue is to propose a change directly, https://github.com/ankidroid/Anki-Android/wiki/Contributing


> مرحبا! 👋شكرا لتسجيل هذه المشكلة. يرجى تذكر أننا جميعًا متطوعون هنا ، لذلك قد يتطلب الأمر بعض الصبر قبل أن نتمكن من حل المشكلة. تذكر أيضًا أن أسرع طريقة للحصول على حل لمشكلة ما هي اقتراح تغيير مباشرةً ، https://github.com/ankidroid/Anki-Android/wiki/Contributing

What do you mean by proposing a change directly? I mean a change of what?

**Comment by Hisham7345** [comment]
> Hello! 👋 Thanks for logging this issue. Please remember we are all volunteers here, so some patience may be required before we can get to the issue. Also remember that the fastest way to get resolution on an issue is to propose a change directly, https://github.com/ankidroid/Anki-Android/wiki/Contributing

Thank you so much. The problem has solved.
