### ISSUE TITLE
[Bug] Dark mode: icons in card editing window not (or barely) visible

### ISSUE THREAD

**Issue by choralbari** [ankidroid/Anki-Android#10118]
###### Reproduction Steps

1. Enter dark mode
2. Edit a card
3. Look for the icon to attach a file -- it's not visible.
4. Tap around about where the icon should be; the drop-down menu appears as it should.

###### Expected Result

The icons are clearly visible

###### Actual Result

The icons are not visible.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Xiaomi

Model = M2012K11AG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; M2012K11AG Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = a7de9d6d-3d8e-49a9-a72d-f2cdfd48285d

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by choralbari** [comment]
This is a new phone and I wasn't aware MIUI was "forcing" dark mode. I disabled the forced dark mode for AnkiDroid, turned on dark mode in AnkiDroid manually, and the icons display correctly now.

**Comment by david-allison-1** [comment]
Already fixed in 2.16. Thanks for the report!

https://github.com/ankidroid/Anki-Android/pull/9802
