### ISSUE TITLE
Dark mode: whiteboard pen not visible unless colour changed

### ISSUE THREAD

**Issue by choralbari** [ankidroid/Anki-Android#10117]
In dark mode, the whiteboard pen is not visible unless you change it's colour to something other than black.

I would expect the colour to automatically switch from black to white when entering dark mode and vice versa.

Debug info:

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Xiaomi

Model = M2012K11AG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; M2012K11AG Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = a7de9d6d-3d8e-49a9-a72d-f2cdfd48285d

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment]
Very interesting! We have a lot of issues with Xiaomi / MIUI devices, specifically around their "forced dark mode". Can you tell us whether you have forced dark mode *off* for AnkiDroid? There are a few things exactly like this that are problems for AnkiDroid when MIUI is trying to force a dark mode

**Comment by choralbari** [comment]
This is a new phone and I wasn't even aware MIUI was "forcing" dark mode. It's the sort of feature that sounds like a great idea until you take a moment to think about it ;-).  I disabled the forced dark mode in AnkiDroid, turned on dark mode in AnkiDroid manually, and the pen works as I would expect now.

**Comment by david-allison-1** [comment]
Fixed in #9802. Thanks for the report!
