### ISSUE TITLE
[Bug] Ankidroid messing with the <div>s

### ISSUE THREAD

**Issue by Raphael124** [ankidroid/Anki-Android#10122]
###### Reproduction Steps
Desktop Client : Windows 10 Version ⁨2.1.49 (dc80804a)⁩
Android client : Android 11 Version 2.1.49 downloaded from F-Droid. Same for others using it from Play Store

1. Create a card on Anki Desktop (The problem usually arises when copy pasting text from word or the web but it is somewhat random)
2. Sync
3. open the card in ankidroid : No change the card is as it should be
4. Click on Edit (JUST THAT, no modification)
5. Go back to the card (on ankidroid) it now has weird spaces handling and line breaks added to it
6. On desktop the card is changed too as the HTML code looks like it was changed upon opening the "edit" panel of ankidroid

###### Expected Result
Ankidroid should not modify the HTML code upon launching the edition windows

###### Actual Result
The code is indeed changed whenever the edit window is accessed

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Raphael124** [comment]
I did not want to pollute with a thousand screenshots so they are all in the google groups.
I've been working on it as much as my exams enable me to do so and it happens that this issue occurs when anki desktop inserts some line breaks due to formatting parsing (from Word or from a web page): 

Here is an example. This page was taken from a word doc and pasted:
```html
<div>Three components: User agents
(= the mail client),
  mail servers, protocol 
  SMTP (Simple Mail Transfer Protocol)</div>
<div>User Agent: the ‘‘mail
reader’’, software for writing, editing, and reading mails</div>
<div>Mail Servers: mailbox (contains incoming messages
  for user) + queue of outgoing mail messages
  (outgoing = to
be send)</div>
<div>SMTP: between mail
servers for sending mails</div>
<div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Client:
sending mail server
  (server d’émetteur de mail)</div>
<div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Server:
receiving mail server (server de réception de mail)</div>
```
After just clicking on "edit" and closing the windows it turns into this:
```html
<div>Three components: User agents<br>(= the mail client),<br>  mail servers, protocol <br>  SMTP (Simple Mail Transfer Protocol)</div><br><div>User Agent: the ‘‘mail<br>reader’’, software for writing, editing, and reading mails</div><br><div>Mail Servers: mailbox (contains incoming messages<br>  for user) + queue of outgoing mail messages<br>  (outgoing = to<br>be send)</div><br><div>SMTP: between mail<br>servers for sending mails</div><br><div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Client:<br>sending mail server<br>  (server d’émetteur de mail)</div><br><div>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Server:<br>receiving mail server (server de réception de mail)</div>
```
Key problems:
- The `<br>` added where there should be none
-  the fact that the 10 line code was squashed into one makes it harder to edit, especially when editing a space or a typo on the ankidroid app where it is tough understanding what is what.

**Comment by david-allison** [comment]
@Raphael124

* Preferences - Advanced - Replace Newlines with HTML

Sorry I missed this, "closed" doesn't mean "not open for comment", so if the above solution doesn't work, please let me know
