### ISSUE TITLE
"search_deck" may be ambiguous

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10178]
https://github.com/ankidroid/Anki-Android/blob/e0724fb8bf5bdac7e29f100938a791881d0bc5df/AnkiDroid/src/main/res/values/01-core.xml#L146

Can either mean:

Search for a deck to download:

https://github.com/ankidroid/Anki-Android/blob/ab4a40536ab066da2492d72cfca34b2c5f1875b0/AnkiDroid/src/main/res/menu/download_shared_decks_menu.xml#L13

OR: The title of a window allowing a user to search for an existing deck.

https://github.com/ankidroid/Anki-Android/blob/5714251163fc6b7de4139238f5b873d36a4058ca/AnkiDroid/src/main/java/com/ichi2/anki/DeckSpinnerSelection.kt#L232

I feel these may have separate translations, and would likely benefit from being split out.

This isn't yet a "Good First Issue" as I may be incorrect here

**Comment by SanjaySargam** [comment]
Hey @david-allison-1 we have to make two different strings right?

**Comment by SanjaySargam** [comment]
Can I contribute on this ?

**Comment by david-allison-1** [comment]
> This isn't yet a "Good First Issue" as I may be incorrect here

Let's wait for another maintainer to weigh in here.

**Comment by SanjaySargam** [comment]
> > This isn't yet a "Good First Issue" as I may be incorrect here
> 
> Let's wait for another maintainer to weigh in here.

Ok

**Comment by DeepanshuPratik** [comment]
Hey @david-allison can I contribute to this?

**Comment by david-allison** [comment]
Sure. Ensure that changes to strings are only performed in the `values` folder. We have a process to sync changes for other languages

**Comment by mikehardy** [comment]
:point_up:  https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

**Comment by DeepanshuPratik** [comment]
@david-allison  Just for clarity, I wanted to ask we have to separate out those two functionalities by introducing another string with the same value but a different meaningful ID? as in `DeckSpinnerSelection.kt` it is used for just selecting the existing deck but in `download_shared_decks_menu.xml` it is used for shared decks in Anki.

**Comment by david-allison** [comment]
> @david-allison Just for clarity, I wanted to ask we have to separate out those two functionalities by introducing another string with the same value but a different meaningful ID? as in `DeckSpinnerSelection.kt` it is used for just selecting the existing deck but in `download_shared_decks_menu.xml` it is used for shared decks in Anki.

Yes, different strings, and add a `comment="` attribute to fix the lint check which occurs.
