### ISSUE TITLE
New cards in reverse added order

### ISSUE THREAD

**Issue by balta2ar** [ankidroid/Anki-Android#10181]
**Is your feature request related to a problem? Please describe.**
Currently there are two options in AnkiDroid settings on the order of new cards: in random order, in order added:
![image](https://user-images.githubusercontent.com/340676/149302829-2f554e00-7353-47af-a033-46ae532ccbe1.png)

**Describe the solution you'd like**
I'd like the third option: In reverse added order. I wanna see recently added cards first.

**Comment by mikehardy** [comment]
Hi there! Does this option exist in Anki Desktop?

**Comment by balta2ar** [comment]
I've just checked Anki 2.1.49, and no -- there are only two options. Does that mean it should be added in desktop version first?

**Comment by mikehardy** [comment]
@balta2ar in general yes - we have a hard enough time keeping up with Anki Desktop just to maintain parity so there is little appetite for going ahead :sweat_smile: - they are receptive to feature requests though, and this seems reasonable, you may find success with your petition? https://forums.ankiweb.net I think

**Comment by david-allison-1** [comment]
Thanks for the report! This will need to be in Anki Desktop before we consider implementing it. 

Please let us know when this happens and we'll reopen the ticket.
