### ISSUE TITLE
Deprecation - handle new deprecation in localbroadcastmanager 1.1.0

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#10185]
Expected steps + outcome:

- update dependency locally in a new branch to localbroadcastmanager 1.1.0
- attempt build, note the new deprecation warnings that break the build
- read documentation around localbroadcastmanager deprecations added in 1.1.0, and what the documents say to shift to in order to not use deprecated items
- make the changes without adding annotations to ignore deprecation so it builds cleanly
- make a PR with the changes

```
> Task :AnkiDroid:compilePlayReleaseJavaWithJavac
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/widget/WidgetStatus.java:22: warning: [deprecation] LocalBroadcastManager in androidx.localbroadcastmanager.content has been deprecated
import androidx.localbroadcastmanager.content.LocalBroadcastManager;
                                             ^
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java:38: warning: [deprecation] LocalBroadcastManager in androidx.localbroadcastmanager.content has been deprecated
import androidx.localbroadcastmanager.content.LocalBroadcastManager;
                                             ^
error: warnings found and -Werror specified
1 error
2 warnings
```

Need to handle new deprecation

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/10183#issuecomment-1012140708_

**Comment by Supriyo9** [comment]
@mikehardy Just updating  dependency locally in a new branch to localbroadcastmanager 1.1.0 will not work , better if it is replaced with LiveData   https://developer.android.com/topic/libraries/architecture/livedata

**Comment by mikehardy** [comment]
Okay, that is essentially what the deprecation notice on the android developer site says.
How do you propose integrating LiveData into these two areas then? If you could lay out a rough design, or maybe put up a really rough pull request, that would help to reason about it

**Comment by Gravetide** [comment]
Noticed that nobody has updated on this issue, but how do we feel if we just replace localbroadcastmanager with [green robot's EventBus](https://github.com/greenrobot/EventBus)? Reason being is that the transition will be much smoother because a lot of the code can be simplified. I'll try getting a rough design or ideally a PR in the coming days but in theory it shouldn't be too complicated and it'll fix the depreciation issue.

**Comment by mikehardy** [comment]
I'm open to that. It's a well maintained project and I use it in some other repos.

**Comment by oyeraghib** [comment]
@mikehardy @david-allison I would like to work on this issue.

**Comment by david-allison** [comment]
Thanks!

**Comment by s-deepak-kumar** [comment]
Hello @oyeraghib, are you still working on it?

**Comment by oyeraghib** [comment]
@s-deepak-kumar yes I was on a break, but now I am on it!

**Comment by oyeraghib** [comment]
@s-deepak-kumar I am still working on it. Actually it's not a easy transition from localbroadcastmanager to LiveData and ViewModel. A proper way has to be constructed to make it work. If you have gone through the codebase for that and have information around LiveData and ViewModel I would love to hear your views about the same.
