### ISSUE TITLE
Parallel Builds are not identifiable at all after install

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#10188]
A couple days ago I personally noticed the same thing @Anthropos888 noticed:

----

2) the parallel A build also got installed as "AnkiDroid", not Ankidroid.A
There was just no way to find out which one is which one. Even the app info screen didn't tell. So I ended up uninstalling both apps.
That's confusing, I'd expect a parallel build A to have the letter .A in the app name (Android 11)

_Originally posted by @Anthropos888 in https://github.com/ankidroid/Anki-Android/issues/10175#issuecomment-1012557249_

**Comment by mikehardy** [comment]
I'll see if I can change this in the parallel release script, it was really difficult to deal with!

**Comment by mikehardy** [comment]
Hmm 🤔
![Screenshot_20220416-194313.jpg](https://user-images.githubusercontent.com/782704/163695624-840e7a6b-b7a9-4c13-b757-f0b457fbba1d.jpg)

**Comment by david-allison** [comment]
I think this is a different issue, the build is now identified for me, just not on that screen.

If you tap 'about', it returns the correct "AnkiDroid.A"

**Comment by mikehardy** [comment]
🤦 indeed, confusing version with name, I see what you see and I also see the .A in a couple other places. Definitely identifiable now!
