### ISSUE TITLE
Kotlin Migration: detect <br/> converted to <br></br>

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#10209]
A few Kotlin migrations have incorrectly changed `<br/>` tags to `<br></br>`. Instead they should be changed to a newline.

Add a lint check to detect these so they get flagged by CI, and fixed before they make it into the codebase

See: https://github.com/ankidroid/Anki-Android/commit/14898fa14f7a47e636e2f8f1af73a37771c20b13 for a sample implementation of a lint check, searching for the same issue in the copyright header.

This will require two commits:
1. One to fix all instances of `<br></br>`
2. One to implement the lint check, which will pass

We require two commits to ensure that each commit on `master` passes.

It is ideal to write the lint check before fixing all instances of the issue. BUT the commits should be ordered as above

**Comment by pree-T** [comment]
@david-allison-1 Sir I wanna work on this.

**Comment by david-allison-1** [comment]
> @david-allison-1 Sir I want to work on this.

You've already asked for an issue to work on today. It's best to focus on one at a time while you get used to the project.

**Comment by ramanjitsingh-hub** [comment]
Hi, I am new to the community and would love to work on this issue. I would need some help to get started

**Comment by david-allison-1** [comment]
Sounds good! First thing would be to get the project building and see the linked commit

**Comment by ramanjitsingh-hub** [comment]
can you please help me set up the enviournment?

**Comment by ramanjitsingh-hub** [comment]
Hey, Can someone mentor me on this issue?

**Comment by david-allison-1** [comment]
@ramanjitsingh-hub What have you tried? What's unclear?

**Comment by Gravetide** [comment]
Hey considering I don't see any progress on this I'll try starting on this. Ill either give a rough PR or a writeup in the coming days.

**Comment by david-allison-1** [comment]
Absolutely!
