### ISSUE TITLE
[Bug] "Collection not opened" after trying to edit note

### ISSUE THREAD

**Issue by mikemorr** [ankidroid/Anki-Android#10238]
Today, when attempting to edit a note, I get a "Collection not opened" dialog after attempting to save the note. Logcat is attached.

[log.txt](https://github.com/ankidroid/Anki-Android/files/7878045/log.txt)

AnkiDroid Version = 2.15.6

Android Version = 8.1.0

Manufacturer = LGE

Model = LM-X210APM

Hardware = cv1

Webview User Agent = Mozilla/5.0 (Linux; Android 8.1.0; LM-X210APM Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = 406cae4f-fc4b-461f-aad7-a1a87a6e1d6a

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by david-allison-1** [comment]
Hi @mikemorr 

Thanks for the report. Could you fill out the Bug Template (mostly the "Debug Info") and place it in the OP: https://raw.githubusercontent.com/ankidroid/Anki-Android/master/.github/ISSUE_TEMPLATE/issue_template.md

This issue looks similar to https://github.com/ankidroid/Anki-Android/issues/9616 and https://github.com/ankidroid/Anki-Android/issues/6378

<details><summary>Stack trace</summary>

```
01-16 16:52:31.929 12571 18546 E AnkiDroid: CollectionTask$UpdateNote/ doInBackgroundUpdateNote - RuntimeException on updating note
01-16 16:52:31.929 12571 18546 E AnkiDroid: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.utils.JSONObject.getLong(JSONObject.java:2)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Collection.genCards(Collection.java:55)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Collection.genCards(Collection.java:6)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Collection.genCards(Collection.java:5)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Note._postFlush(Note.java:2)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Note.flush(Note.java:18)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Note.flush(Note.java:2)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Note.flush(Note.java:1)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask$UpdateNote.lambda$task$0(CollectionTask.java:1)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask$UpdateNote.a(Unknown Source:0)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.e.run(Unknown Source:10)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.DB.executeInTransaction(DB.java:2)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask$UpdateNote.task(CollectionTask.java:5)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask$UpdateNote.task(CollectionTask.java:1)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:14)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at java.lang.Thread.run(Thread.java:764)
01-16 16:52:31.929 12571 18546 E AnkiDroid: Caused by: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at org.json.JSON.typeMismatch(JSON.java:100)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at org.json.JSONObject.getLong(JSONObject.java:520)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.utils.JSONObject.getLong(JSONObject.java:1)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	... 22 more
01-16 16:52:31.929 12571 18546 E AnkiDroid: 
01-16 16:52:31.929 12571 18546 E AnkiDroid: com.ichi2.utils.JSONException: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.utils.JSONObject.getLong(JSONObject.java:2)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Collection.genCards(Collection.java:55)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Collection.genCards(Collection.java:6)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Collection.genCards(Collection.java:5)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Note._postFlush(Note.java:2)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Note.flush(Note.java:18)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Note.flush(Note.java:2)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.Note.flush(Note.java:1)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask$UpdateNote.lambda$task$0(CollectionTask.java:1)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask$UpdateNote.a(Unknown Source:0)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.e.run(Unknown Source:10)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.libanki.DB.executeInTransaction(DB.java:2)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask$UpdateNote.task(CollectionTask.java:5)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask$UpdateNote.task(CollectionTask.java:1)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:14)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at android.os.AsyncTask$2.call(AsyncTask.java:333)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at java.lang.Thread.run(Thread.java:764)
01-16 16:52:31.929 12571 18546 E AnkiDroid: Caused by: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at org.json.JSON.typeMismatch(JSON.java:100)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at org.json.JSONObject.getLong(JSONObject.java:520)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	at com.ichi2.utils.JSONObject.getLong(JSONObject.java:1)
01-16 16:52:31.929 12571 18546 E AnkiDroid: 	... 22 more
```
</details>

If you're on AnkiDroid 2.15, could you try: 

> The error is in Settings - AnkiDroid - Deck for new cards. Setting this to "use current deck" will work around the issue for now

If this is the case, the issue is fixed for 2.16 (`v2.16alpha19`)

**Comment by mikemorr** [comment]
OK I added debug info. "Use current deck" is already selected.

**Comment by david-allison-1** [comment]
Could you try an alpha parallel release of 2.16 and tell me if this fixes the issue?

[Alphas](https://github.com/ankidroid/Anki-Android/releases/) - Select "Assets - Parallel.A/B"

Latest alpha as of now: https://github.com/ankidroid/Anki-Android/releases/download/v2.16alpha38/AnkiDroid-2.16alpha38.parallel.B.apk

**Comment by mikemorr** [comment]
@david-allison-1 Thanks for that link. Same thing happened and generated a crash report, which I just sent.

**Comment by david-allison-1** [comment]
Thanks, same stack trace as above: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/c9765a3b-ee11-4cc6-bf7e-9e688f119aad

I'm snowed under with another issue, but I've asked others to continue diagnosis here. 

If you don't get a response within a couple of days, please ping me.

**Comment by david-allison-1** [comment]
@prateek-singh-3212 Check with mike about getting access. Stack trace is in: https://github.com/ankidroid/Anki-Android/issues/10238#issuecomment-1013966384 which should be enough

@mikemorr Are you still experiencing this issue?

**Comment by mikemorr** [comment]
@david-allison-1 Yes, the issue still occurs.

**Comment by prateek-singh-3212** [comment]
@mikemorr could you share the collection.anki2 i.e your collection?

**Comment by mikemorr** [comment]
@prateek-singh-3212 Thanks, here it is: https://drive.google.com/file/d/1y4AXDANi99ZRwE7m7UQkLUfCV3bi8Hp6/view

**Comment by prateek-singh-3212** [comment]
@david-allison this occurred due to Rust transaction failure. Could you tell me that how to view rust logs?

**Comment by david-allison** [comment]
We don't currently take Rust logs - we return the errors as-is, and our Rust code is primarily a wrapper around Anki's.

If you check logcat, you get a list of all the API calls to the rust library, just without the internals.

The next step in diagnosis is to list the error and appropriate logcat lines in the issue while diagnosing

**Comment by s204451** [comment]
I am also experiencing this issue.

I have done some testing, here's what I found:

It only happens with a particular note type. [Example note type](https://drive.google.com/file/d/17UimTQrlaAzLt0A-oIcE5iQUS_P_Pc2e/view?usp=sharing). If I recreate the note's data with a different note type it doesn't crash in the same situation.

It only happens when I have at least two subdecks and there are cards in both of the subdecks. If I move all cards to the same deck/subdeck, it doesn't crash.

Hope someone will take a look at this.


### Debug info:
AnkiDroid Version = 2.15.6

Android Version = 12

Manufacturer = samsung

Model = SM-G985F

Hardware = exynos990

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G985F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.125 Mobile Safari/537.36

ACRA UUID = 441a6e8f-dd87-44fa-9efb-26f6cbd13617

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
