### ISSUE TITLE
[Bug] NoteEditor: can't paste recently copied images from clipboard

### ISSUE THREAD

**Issue by adammesa** [ankidroid/Anki-Android#10240]
###### Reproduction Steps

1. Take a screenshot desired content (e.g. from lecture slides - this is my desired workflow where I have slides + AnkiDroid open side-by-side on my phablet)
2. Open the note editor
3. Long press → paste; or Long press → clipboard and select image

###### Expected Result
The image will be pasted (in a similar fashion to that of inserting media via the attachment icon → from gallery). Seems to be relevant to https://github.com/ankidroid/Anki-Android/issues/7566 

###### Actual Result
The image is not pasted and a pop-up saying "something went wrong" appears. 
<details><summary>VIEW SCREENSHOT OF ERROR</summary>
<p>

![Screenshot_20220118-105601_AnkiDroid](https://user-images.githubusercontent.com/2158302/150001569-00f6bd6c-3720-43b9-a519-f73c52b0c579.png)

</p>
</details>

###### Debug info
<details><summary>VIEW DEBUG INFO</summary>
<p>

```
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-F926W

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-F926W Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.87 Safari/537.36

ACRA UUID = c1f19acf-8c86-45ea-b826-2045bdf5659c

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

</p>
</details> 

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum - there are a host of related closed topics from when this feature was first being implemented for Android's new clipboard management: https://github.com/ankidroid/Anki-Android/issues/7566 
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by murugu-21** [comment]
The pr will go through very soon and next release will fix this issue, in the mean time try to use gboard for pasting screenshots/clipboard images rather than default(samsung clipboard) implementation since gboard paste works with current version @adammesa
