### ISSUE TITLE
Hii i make some changes in readme file  but i can't able to push

### ISSUE THREAD

**Issue by Ra007hul** [ankidroid/Anki-Android#10254]
remote: Permission to ankidroid/Anki-Android.git denied to Ra007hul.
fatal: unable to access 'https://github.com/ankidroid/Anki-Android.git/': The requested URL returned error: 403

// Can someone help me how can i fix it

**Comment by prateek-singh-3212** [comment]
Hello @Ra007hul,
You are doing this in wrong way. Did you fork the Ankidroid Repo? if not then the first fork the ankidroid repo and push commit to forked repo then create the new pull request.

**Comment by Ra007hul** [comment]
Yes sir i forked this repo and then created a branch and then commited but
when i am pushing it to github it is showing error.Please help me

**Comment by david-allison-1** [comment]
You don't have permission to push to ankidroid. You need to clone from your fork.

If you're familiar with git, you can use the `git remote` to obtain and push contributions to your fork.

Otherwise, export your existing commits as a patch file, clone the correct respiratory and reapply them.

**Comment by Ra007hul** [comment]
Awesome, thanks!
