### ISSUE TITLE
E-mail message of exported deck does not parse html correctly

### ISSUE THREAD

**Issue by AayushSolanki** [ankidroid/Anki-Android#10256]
###### Reproduction Steps

1. Long press on any deck.
2. Click export deck.
3.  send via E-mail.

###### Expected Result
The E-mail body should contain 2 hyperlinks first one on "**AnkiDroid**" and another on "**Anki distributions**".

###### Actual Result
Both the anchor tags are not working as link.

<img width="700" alt="Screenshot 2022-01-21 103857" src="https://user-images.githubusercontent.com/75438613/150470508-99f7b12e-5aeb-49db-90ed-d21443e50ad7.png">

**Comment by AayushSolanki** [comment]
i would like to work on the issue!

**Comment by prateek-singh-3212** [comment]
@AayushSolanki are you working on this issue?

**Comment by viciousAegis** [comment]
I looked into this a little, and seems like Gmail app does not allow hyperlinking. The only way to send the links is to just send the link as it is separately in the email. 
example email body:

>Hi!
>
>This is an Anki flashcards deck sent from AnkiDroid. Try to open it using one of the available Anki distributions and enjoy easy and efficient learning!
>Anki Manual: https://docs.ankidroid.org/manual.html
>Distributions: https://apps.ankiweb.net/#download

This is the only way to send links in the mobile app.
If @AayushSolanki is not working on this currently, I can work on it, it's a simple fix.

**Comment by AayushSolanki** [comment]
@prateek-singh-3212 @viciousAegis I am still working on the and will make a PR soon

**Comment by david-allison** [comment]
After discussion, I proposed a style to fix it:

```
AnkiDroid[1]

[1] https://docs.ankidroid.org/manual.html
```
