### ISSUE TITLE
At the end of a timebox, don't play a video

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10262]
In AnkiDroid you can use timebox. AnkiDroid tell you that you reviewed 27 cards in the last 15 minutes, - for example - and whether you want to stop here.
However, a second after the question appears, ankidroid starts playing the media of the next card, in particular the video moves to full screen and hides the buttons. If you want to answer the question related to the video you can't because you need to answer whether you want to continue. This means that the user switch between "do you continue" and "actual card's question" thrice, which is slightly confusing and not a good experience.

Instead, media manager, or at least videos, should wait until the user has answered that they still want to review before playing the next media. 

I kind of hope that it's a good first issue, because it "only" touches two part of the code, media manager and timebox. It is not something that require to make change everywhere. However, it's not entirely trivial either since you'll need to ensure that the media manager take the state of the timebox into account (or that it is not triggered so soon)

**Comment by raddi1972** [comment]
Can I work on this?

**Comment by SanjaySargam** [comment]
Can I contribute this ?

**Comment by viciousAegis** [comment]
Hello! i'm new to the community and would love to contribute to this :)

**Comment by Arthur-Milchior** [comment]
Extremely sorry @raddi1972 , @SanjaySargam , @viciousAegis , I didn't check github as much as I should have.
The first one of you who confirm that they are not working on anything else for ankidroid can have it.
If you are not already on discord, please come if you have any question, usually people can answer here more quickly than on github, as there are more people looking at what you ask

**Comment by raddi1972** [comment]
I am not working on anything else in ankidroid, so I would like to work on this.

**Comment by Arthur-Milchior** [comment]
Then please go for it @raddi1972

**Comment by rishavchanda** [comment]
@Arthur-Milchior is this issue resolved? or @raddi1972 is still working on it?

**Comment by Arthur-Milchior** [comment]
Not resolved. Any news @raddi1972 ?

**Comment by raddi1972** [comment]
I was able to identify the problem and recreate it, I was also able to locate the code related to timebox. Could you point me, which part of the code should I look into for media manager or from where the videos are controlled?

**Comment by Arthur-Milchior** [comment]
I believe you may want com/ichi2/libanki/Sound.java which seems to have the method in charge of playing media. The name is admittedly confusing as it deals with video to

**Comment by raddi1972** [comment]
To fix this do we need to wait for the window to close and then play the video? I am thinking of somehow checking the state of the TimeBox window then calling the function that plays the media. Do we have a listener that can be called after the state of the TimeBox is finished? @Arthur-Milchior

**Comment by Arthur-Milchior** [comment]
That was indeed what seemed the most natural to me. If the user answer they want to still review, show the video, otherwise close

**Comment by ayushsoni916** [comment]
Is this issue fixed, @Arthur-Milchior ? or is it still being worked on by @raddi1972 ?

**Comment by raddi1972** [comment]
@ayushsoni916 The issue is not fixed. I am busy with university work so ig you can work on it. I will unassign myself.

**Comment by ayushsoni916** [comment]
@Arthur-Milchior could you assign me.

**Comment by Arthur-Milchior** [comment]
Done

**Comment by ayushsoni916** [comment]
@Arthur-Milchior could you provide some screenshot of this issue so I can understand it more better.

**Comment by Arthur-Milchior** [comment]
I'll try. I'll need a video however, because a screenshot will not show anything relevant

**Comment by ayushsoni916** [comment]
@Arthur-Milchior please send the video asap so I can work on this issue more efficiently.

**Comment by Arthur-Milchior** [comment]
https://user-images.githubusercontent.com/357361/160294311-4b93b70c-cf98-4618-80ce-cb4b2c3f377f.mp4

**Comment by s-deepak-kumar** [comment]
Hello @ayushsoni916, are you still working on it?

**Comment by Arthur-Milchior** [comment]
@s-deepak-kumar are you still interested? I believe we can assume @ayushsoni916 is not working on it anymore.

@s-deepak-kumar if you'rer interested, let me know if you understood the issue
