### ISSUE TITLE
Reorder menu items in Deck pop-up menu

### ISSUE THREAD

**Issue by peterj71** [ankidroid/Anki-Android#10283]
**Is your feature request related to a problem? Please describe.**

I have some filtered decks that I use daily and I fine-tune the Deck Options multiple times daily. The problem is that "Delete Deck" is right below "Deck Options" in the Deck pop-up menu, so it's very easy to accidentally delete a deck when simply trying to change options if you have fat fingers (see screenshot). 

**Describe the solution you'd like**

The easiest and fastest fix would be to re-order the menu items so that Delete Deck is at the bottom of the list. Adding a separator line above/below it would help as well.

A more elegant fix that would require a little coding would be to add a confirmation dialogue box to "Confirm Delete Deck? Yes/No".

Another fix would be to add an "Undo Delete Deck" feature so an accidental deletion could be restored immediately.
![21-12-26-07-46-33-977_deco](https://user-images.githubusercontent.com/15965443/151679281-bc412b1f-2b27-4d8a-b3f8-4064a98d21fd.jpg)

**Comment by david-allison-1** [comment]
> A more elegant fix that would require a little coding would be to add a confirmation dialogue box to "Confirm Delete Deck? Yes/No".

We already have a confirmation on deleting a deck if it contains cards. Does this not appear for you?

**Comment by peterj71** [comment]
Hi David, my filtered decks are always empty when I edit the deck options, so that dialog doesn't appear (in fact I've never seen it!).

I just made a temporary filtered deck with cards in it to test, and sure enough that dialog does appear when there are cards in the deck, but since my decks are empty it remains a nuisance to have them accidentally deleted.

So to amend my feature request, please extend this dialog to include empty decks, thanks!

BTW the reason it's a pain is that I have detailed search criteria in my filters so recreating them after they're gone is a pain.

Regards, Peter

**Comment by david-allison-1** [comment]
Hi @peterj71,

I've put in a Pull Request for this change (moving 'delete' to the bottom).

Assuming it passes review, it will be available in our 2.16 alphas (probably 2.16alpha42): https://github.com/ankidroid/Anki-Android/releases

Regards,
David

**Comment by david-allison-1** [comment]
I'll add a confirmation screen for filtered decks as well in a follow-up change.

**Comment by peterj71** [comment]
That's awesome, thanks David!
