### ISSUE TITLE
[Bug] Font sizes sometimes differ from front to back

### ISSUE THREAD

**Issue by Pound-Hash** [ankidroid/Anki-Android#10284]
###### Reproduction Steps

1. Set a `font-size` of `15px` under **styling** (applies to both front and back)
2. Use either a `.ttf`or `.otf` font file (Open Sans / Public Sans)

###### Expected Result
Display information on both sides of a card with equivalent font sizes.

###### Actual Result
Some cards display one side of a card with a smaller/larger font size than the other side.
This started happening after the last major AnkiDroid update (I'm not sure the version).

###### Debug info
```
AnkiDroid Version = 2.15.6

Android Version = 12

Manufacturer = samsung

Model = SM-G781V

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G781V Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/97.0.4692.98 Mobile Safari/537.36

ACRA UUID = 05496a74-dab1-47f8-bf2e-0f508c1d17e0

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, thanks for the report. This could be an issue with your card template. Could you confirm by editing the card and tapping "cards" to ensure that things look OK.

If they look fine, could you grab + upload:

* A sample deck, containing a card (with appropriate files to display the issue)
* Optional: the HTML generated for the front/back: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by Pound-Hash** [comment]
The front and back templates are fine. Attached is a deck titled **English**. Some cards have the problem, some don't. One card that has the problem is **abreaction**. One card without the problem is **fascia**.

https://drive.google.com/drive/mobile/folders/1hovufseJAHmyOxfa35fm7nA320tYsA9v?utm_source=en&pli=1&sort=13&direction=a

**Comment by Arthur-Milchior** [comment]
You didn't share access to this file. I just requested access. Unless it's private you may consider moving it to public

**Comment by Pound-Hash** [comment]
> You didn't share access to this file. I just requested access. Unless it's private you may consider moving it to public

My apologies. I uploaded it from my mobile and saw a message saying it was made publicly available. I don't know what that was about. I've now changed the permissions.

**Comment by Arthur-Milchior** [comment]
@Pound-Hash When I try to access it, I know read it has been moved to your trash, so I still can't take a look.

Sorry for the delay

**Comment by Pound-Hash** [comment]
I've resolved it. The back templates of some cards were changed from a simple `{{Back}}` to a line of html code. I'm not sure why this happened; I never did this on purpose or manually. Anyhow, it's fixed.
