### ISSUE TITLE
[Bug] Cannot add videos clips through "Add Audio Clips" option in note editor dropdown (unless "Allow all files in media import" setting is enabled)

### ISSUE THREAD

**Issue by viciousAegis** [ankidroid/Anki-Android#10315]
Important references:
#10212 
#9643

A few days ago, while on the Anki Play Store app (ver 2.15.6), I tried adding video clips through the `add audio clip` button in the note editor dropdown for issue #10212 and was successfully able to do it. Today, however, this same exact method was not accepting video files. After downloading the 2.16 alpha, and enabling the feature #9643 "Allow all files in media import", I was successfully able to add videos through the same method again. 

**The issue is that, I shouldn't have to enable the feature in order to add videos.**

###### Reproduction Steps

1. Add a new note
2. From the dropdown menu, select `add audio clip`, and then try to add the video. (didn't work for me)
3. If you are on the 2.16 alpha build, go to Settings -> Advanced -> Workarounds and scroll down to `Allow all files in media import` and enable it. 
4. Repeat step 2. Should work now.

###### Expected Result
Video should be added without needing to enable  `Allow all files in media import`   

###### Actual Result
Need to explicitly enable  `Allow all files in media import` to add video

###### Debug info
```
AnkiDroid Version = 2.16alpha41

Android Version = 9

Manufacturer = Xiaomi

Model = Redmi Note 8 Pro

Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 9; Redmi Note 8 Pro Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.85 Mobile Safari/537.36

ACRA UUID = 21d405cb-cda8-46ff-b6b4-38ac0fa5d51e

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
I'm unable to add an mp4 in in 2.15.6

Do you have a sample file which worked?

**Comment by david-allison-1** [comment]
Relevant code:

https://github.com/ankidroid/Anki-Android/blob/7eededc571df919795e73836326a52a69034f250/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.kt#L56-L62

**Comment by viciousAegis** [comment]
But, as you said:

> Note: Anki natively supports video via the [sound:] tag, which is why it was considered to be an audio clip

Shouldn't we be able to attach .mp4 because of the above reason regardless of anything?

**Comment by david-allison-1** [comment]
We should be able to attach MP4. I consider this to be a bug.

**Comment by david-allison-1** [comment]
During the implementation, I considered adding a new controller, but there were complexities in determining if a `[sound:` was a video or audio file.

Instead, I decided to add a button for video import to the controller
