### ISSUE TITLE
[Bug] Automatic answer display function does not work

### ISSUE THREAD

**Issue by socialpercon** [ankidroid/Anki-Android#10312]
###### Reproduction Steps

Automatic answer display function does not work

1. Automatic answer display check
2. 6seconds
3. study deck
[모질게토익테스트.zip](https://github.com/ankidroid/Anki-Android/files/8012134/default.zip)

###### Expected Result

automatic answer

###### Actual Result

does not work

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-G988N

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-G988N Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.87 Mobile Safari/537.36

ACRA UUID =

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, thanks for the report. Please fill in the "Debug Info" section so we can help you further

**Comment by socialpercon** [comment]
> Hi, thanks for the report. Please fill in the "Debug Info" section so we can help you further

Hi, updated debug info except uuid thanks for reply

**Comment by viciousAegis** [comment]
@david-allison @socialpercon I tried this out on the 2.16alpha42, and while the automatic answer function _is_ working, it is not working as intended. 
After setting the time limit 6 seconds, for the 3 cards in the deck, the times after which the cards were shown were 10,11,8 seconds respectively. 
Any idea what could be causing the time limit to malfunction?

**Comment by david-allison** [comment]
> @david-allison @socialpercon I tried this out on the 2.16alpha42, and while the automatic answer function _is_ working, it is not working as intended. After setting the time limit 6 seconds, for the 3 cards in the deck, the times after which the cards were shown were 10,11,8 seconds respectively. Any idea what could be causing the time limit to malfunction?

Do your cards have audio?

**Comment by viciousAegis** [comment]
> Do your cards have audio?

Yep,2 of the cards have audio

**Comment by david-allison** [comment]
Should be: audio duration + 6 then.

**Comment by viciousAegis** [comment]
> Should be: audio duration + 6 then.

Yep, works as intended then

**Comment by socialpercon** [comment]
> _**Edit by @david-allison: the durations/time limit were correct**_
> 
> @david-allison @socialpercon I tried this out on the 2.16alpha42, and while the automatic answer function _is_ working, it is not working as intended. After setting the time limit 6 seconds, for the 3 cards in the deck, the times after which the cards were shown were 10,11,8 seconds respectively. Any idea what could be causing the time limit to malfunction?

My guess is that the problem is with the TTS settings.

**Comment by MagTun** [comment]
In brief: I have a similar problem but for me "automatic answer" only works if the "Set TTS language" is not set to "Don't speak" (I have tried with latest alpha version cf. the debug below)

 
In details: I am using a JS script to set the field for the front/back. Sometimes the front field is in English and sometimes it is in Dutch. As the language changes, I can't use the "set TTS language" features and I have set it to "don't speak" for both front and back. For TTS, I use instead `AnkiDroidJS.ankiTtsSpeak()` (cf. below).  With these settings, the automatic answer doesn't work.  The TTS is short (max 4sec) and I have tried with automatic show answer after 9 seconds and automatic next question after 15 seconds. 

However, if I reactivate the "set TTS language" and set it to English and Dutch, then automatic answer works as expected (even with timeout set to 2 and 3 seconds)

```
AnkiDroidJS.ankiTtsSetLanguage(languageFront);
AnkiDroidJS.ankiTtsSpeak(textforTTS);
```


AnkiDroid Version = 2.16alpha55

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.79 Mobile Safari/537.36

ACRA UUID = 06e6dc69-fef2-4e49-a15a-2b41ca4d7007

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by david-allison** [comment]
> In brief: I have a similar problem but for me "automatic answer" only works if the "Set TTS language" is not set to "Don't speak" (I have tried with latest alpha version cf. the debug below)
> 
>  
> In details: I am using a JS script to set the field for the front/back. Sometimes the front field is in English and sometimes it is in Dutch. As the language changes, I can't use the "set TTS language" features and I have set it to "don't speak" for both front and back. For TTS, I use instead `AnkiDroidJS.ankiTtsSpeak()` (cf. below).  With these settings, the automatic answer doesn't work.  The TTS is short (max 4sec) and I have tried with automatic show answer after 9 seconds and automatic next question after 15 seconds. 
> 
> However, if I reactivate the "set TTS language" and set it to English and Dutch, then automatic answer works as expected (even with timeout set to 2 and 3 seconds)
> 
> ```
> AnkiDroidJS.ankiTtsSetLanguage(languageFront);
> AnkiDroidJS.ankiTtsSpeak(textforTTS);
> ```
> 
> 
> AnkiDroid Version = 2.16alpha55
> 
> Android Version = 10
> 
> Manufacturer = Xiaomi
> 
> Model = Redmi 7A
> 
> Hardware = qcom
> 
> Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.79 Mobile Safari/537.36
> 
> ACRA UUID = 06e6dc69-fef2-4e49-a15a-2b41ca4d7007
> 
> Scheduler = std2
> 
> Crash Reports Enabled = true
> 
> DatabaseV2 Enabled = true
> 

Could you re-report this as a separate issue? I did some work on automatic display answer, and this should be fixable and testable now

**Comment by MagTun** [comment]
@david-allison Thank you, it's done.

**Comment by mikehardy** [comment]
I think this still needs a good look
