### ISSUE TITLE
(Request) Delete button

### ISSUE THREAD

**Issue by javiercl2020** [ankidroid/Anki-Android#10321]
Can you please add the delete button during preview?
I have around 5000 cards and when I preview them in the browser its frustrating to go back and delete it.

**Comment by mikehardy** [comment]
Interesting - I see what you mean. Would it work for you if - when you tap the pencil icon to go to edit the note - there was a delete note option in the edit note menu? That might be possible without too much UI changing

**Comment by javiercl2020** [comment]
Yes that works

**Comment by mikehardy** [comment]
Hi there! Unfortunately we do not have a lot of time to offer guidance, so I just want to set the general explanation that you should picture yourself more as an explorer or an adventurer, not so much as a "tell me what to do" person. Get ready to explore :-)

In general you will want to use our Wiki, in particular the development guide.
You will want to find another area that has delete note functionality to see how it is done
You will want to understand exactly how the existing menu options in that menu work
You will want to explore how to add menu items to a layout file in android, find that layout file and try adding a new delete option
You will want to make a "dummy" implementation of the handler for your new menu option and make sure it is all hooked up

Now the hard part

You will want to actually delete the note if the user chooses that option, possibly with confirmation
After deleting the note you will need to go back to the previewer, but you will need to pass it a return code somehow indicating that the note was deleted, so that it may remove the note from it's selection of notes being previewed, and if you were only previewing one note and deleted it then the Previewer itself will need to return back to the deck list

I think the user interface part will be easy. I think managing the control flow back to previewer where it handles the deletion and maybe returns will be the hard part

Hope this helps

**Comment by Areeb-510** [comment]
Thanks for the guidance it helps a lot.

**Comment by rishavchanda** [comment]
@mikehardy Is this issue resolved? Or else can I work on it?

**Comment by mikehardy** [comment]
@rishavchanda it appears @Areeb-510 is working on this at the moment, so it might be best to find a different issue

**Comment by rishavchanda** [comment]
@mikehardy ok

**Comment by WPum** [comment]
@Areeb-510
Hi, are you still working on this issue? If not I can give it a try!

**Comment by parthn2** [comment]
HI @mikehardy., if no one is working on this issue now, Can i work on it ?

**Comment by viciousAegis** [comment]
@parthn2 The issue hasn't been worked on in a month, and hasn't had any responses. I started work on it because of that, but if you want to work on this specific issue, that's cool with me, otherwise you can also try another issue, all up to you :)

**Comment by mikehardy** [comment]
@viciousAegis please drop a note in the future but I'd say that means you have the issue for the moment

Sorry @parthn2 but hopefully there is another issue in the repo that looks interesting? I think the inventory might be pretty low at the moment unfortunately (a good thing normally? but a bad thing when we have people looking for stuff to do 😆 ). I think there is *always* kotlin migration to do and there is a document on the wiki about how to do that...

**Comment by viciousAegis** [comment]
Apologies, I started work and was just coming here to comment, and then I saw the other comment. 
Honest apologies @parthn2, I'll communicate better in the future.

**Comment by viciousAegis** [comment]
How does this look @mikehardy @javiercl2020?
https://user-images.githubusercontent.com/86671025/157905652-83c4660e-b456-4673-8144-a3d5399848e7.mov

The implementation is this:

> You will want to actually delete the note if the user chooses that option, possibly with confirmation
> After deleting the note you will need to go back to the previewer, but you will need to pass it a return code somehow indicating that the note was deleted, so that it may remove the note from it's selection of notes being previewed, and if you were only previewing one note and deleted it then the Previewer itself will need to return back to the deck list

Will send in a PR in the morning. Let me know if this looks okay.

**Comment by viciousAegis** [comment]
How does this look @mikehardy @javiercl2020?

The implementation is this:

> You will want to actually delete the note if the user chooses that option, possibly with confirmation
> After deleting the note you will need to go back to the previewer, but you will need to pass it a return code somehow indicating that the note was deleted, so that it may remove the note from it's selection of notes being previewed, and if you were only previewing one note and deleted it then the Previewer itself will need to return back to the deck list

Will send in a PR in the morning. Let me know if this looks okay.

https://user-images.githubusercontent.com/86671025/157906813-2abdce09-ccdb-4bd1-9fd8-722b83270b60.mov

**Comment by david-allison** [comment]
> How does this look @mikehardy @javiercl2020?
> 
> The implementation is this:
> 
> > You will want to actually delete the note if the user chooses that option, possibly with confirmation
> > After deleting the note you will need to go back to the previewer, but you will need to pass it a return code somehow indicating that the note was deleted, so that it may remove the note from it's selection of notes being previewed, and if you were only previewing one note and deleted it then the Previewer itself will need to return back to the deck list
> 
> Will send in a PR in the morning. Let me know if this looks okay.
> 
>  Screen.Recording.2022-03-11.at.9.15.36.PM.mov

My reading of this is that it should be from the `Preview` functionality, not the `Edit Note` functionality. 

It'd be worth keeping this in a branch. I wouldn't oppose this functionality in the note editor either

**Comment by viciousAegis** [comment]
@david-allison it works in the `Previewer` as well, since the pencil icon opens the `Edit Note` menu only, as Mike mentioned in https://github.com/ankidroid/Anki-Android/issues/10321#issuecomment-1034106789: 

> Would it work for you if - when you tap the pencil icon to go to edit the note - there was a delete note option in the edit note menu? That might be possible without too much UI changing

If there is something else to be done, let me know :)

**Comment by david-allison** [comment]
@viciousAegis This is the preview for the browser: 

Select cards -> Preview, 

This offers a "Card Viewer" approach to Previewing cards, and makes it much easier to transition between viewing cards than the Note Editor

**Comment by viciousAegis** [comment]
@david-allison Yep! Got it. Thanks for catching that one early 😅. I'll shelve this in a branch (can create a separate PR for it, if maintainers think it's a good addition), and work on the Previewer now.

**Comment by david-allison** [comment]
> @david-allison Yep! Got it. Thanks for catching that one early 😅. I'll shelve this in a branch (can create a separate PR for it, if maintainers think it's a good addition), and work on the Previewer now.

Would be worth creating a new issue to discuss

**Comment by viciousAegis** [comment]
Very very busy with school work right now, would happily let someone else try their hand at this!

**Comment by adizcode** [comment]
Hey, I'd like to work on this issue if it's available!

**Comment by adizcode** [comment]
I'm still working on this. Been busy with uni / internship work lately.
