### ISSUE TITLE
[Bug] Volume gestures not working on latest alpha

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10336]
###### Reproduction Steps

1. Go to settings
2. Open gestures preferences
3. Enable gestures
4. Select an action for `Volume up` and/or `Volume down`
5. Open a note
6. Press `Volume up` or `Volume down`

###### Expected Result

The selected action for gesture should work

###### Actual Result

Nothing happens

###### Debug info
```
Android Version = 11

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-N770F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.87 Mobile Safari/537.36

ACRA UUID = aac45246-7a76-48f0-a8fa-ab71f6855c22

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Tested with Android Studio Emulator (on API 30 and API 29) and with current master build as well, neither works.

It works at latest stable release (2.15.6).

**Comment by david-allison** [comment]
Good catch, thanks! These have been moved to "Settings - Controls"
