### ISSUE TITLE
Can't Add Media via Ankidroid Instant Add API [Bug]

### ISSUE THREAD

**Issue by KamWithK** [ankidroid/Anki-Android#10335]
Hello, I'm trying to use the Ankidroid instant add API to support Ankiconnect queries. I've managed to get most core queries apart from inserting media to work. Whenever I save a file and then try to use the `addMediaFromUri` function it returns null.

###### Reproduction Steps
Here's some source code for saving a file (I've tried saving in different locations with no changes):
```java
File file = new File(context.getExternalCacheDir(), filename);
file.setReadable(true, false);

try (FileOutputStream fileOutputStream = new FileOutputStream(file)) {
    fileOutputStream.write(data);
} catch (Exception e) {
    Log.w("Error", e);
    throw e;
}
```

Afterwards I extract the final file URI and then parse it all to Ankidroid API:
```java
Uri file_uri = Uri.fromFile(file);
context.grantUriPermission("com.ichi2.anki", file_uri, Intent.FLAG_GRANT_READ_URI_PERMISSION);
String result = api.addMediaFromUri(file_uri, filename, "audio");
```

###### Expected Result
If everything works results should contain the path to the media file (mp3 in this case)

###### Actual Result
`resolver.insert` returns null instead of the path (i.e. fails, I'm not sure why)
I thought this was due to permissions but after trying to change around `context.getExternalCacheDir()` to other get dir options I still haven't managed to have any luck (I can confirm that the audio file has been written to the write file and is 100% fine and not-corrupted).

The `contentValues` as expected contains "preferred_name=yomichan_audio_こうこう_高校_2022-01-13-06-01-48.mp3 file_uri=file:///storage/emulated/0/Android/data/com.example.ankiconnectandroid/cache/yomichan_audio_%E3%81%93%E3%81%86%E3%81%93%E3%81%86_%E9%AB%98%E6%A0%A1_2022-01-13-06-01-48.mp3" (to string-ed version).

Not sure what else I can try/where I've gone wrong (I've spent a long time trying to get this to work).
Any tips, advice, suggestions, code or examples would be greatly appreciated!

###### Debug Info
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Google

Model = sdk_gphone_x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 11; sdk_gphone_x86 Build/RSR1.201013.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36

ACRA UUID = 9df528d4-e8b5-4794-baed-53972e9cc702

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there!
It's supposed to work like this I think?
https://github.com/ankidroid/Anki-Android/blob/87ee885bab712290892934acb4a6aabeb3411ce3/api/src/main/java/com/ichi2/anki/FlashCardsContract.java#L1195-L1210

That looks very different from your code above, is our documentation that far off? :thinking: 

Second maybe useful / maybe not useful thought: I wonder if it has trouble with non-ASCII characters for some reason? It should be able to handle any character really, but I have seen errors where assumptions about character set were unexpectedly in the code. You might try a really simple filename to test that hypothesis

**Comment by KamWithK** [comment]
> Hi there! It's supposed to work like this I think?
> 
> https://github.com/ankidroid/Anki-Android/blob/87ee885bab712290892934acb4a6aabeb3411ce3/api/src/main/java/com/ichi2/anki/FlashCardsContract.java#L1195-L1210
> 
> That looks very different from your code above, is our documentation that far off? 🤔

So I think that's the lower level content values API right?
I was just trying to use the wrapper around it - https://github.com/ankidroid/Anki-Android/blob/master/api/src/main/java/com/ichi2/anki/api/AddContentApi.java#L200

I've also tried the ContentValues API directly but I have the exact same error where `Uri insertedFile = cr.insert(AnkiMedia.CONTENT_URI, cv);` would end up being null.

> Second maybe useful / maybe not useful thought: I wonder if it has trouble with non-ASCII characters for some reason? It should be able to handle any character really, but I have seen errors where assumptions about character set were unexpectedly in the code. You might try a really simple filename to test that hypothesis

Just tried out passing in "test.mp3" as the filename and I seem to get the same null value passed out of `addMediaFromUri`

**Comment by mikehardy** [comment]
Sorry - haven't had time to look at it and I'm focusing use of all the available time I have on PR review for scoped storage :weary: 
Not a great reply but I expect there must just be a bug in the implementation somehow and tracing it out will show the issue - stated slightly differently, I think at this moment you may already be the most knowledgeable person on this specific code path and you may actually stand the best chance of figuring out the what+why of the failure

**Comment by KamWithK** [comment]
> Sorry - haven't had time to look at it and I'm focusing use of all the available time I have on PR review for scoped storage 😩 Not a great reply but I expect there must just be a bug in the implementation somehow and tracing it out will show the issue - stated slightly differently, I think at this moment you may already be the most knowledgeable person on this specific code path and you may actually stand the best chance of figuring out the what+why of the failure

Ahh okay I understand
I'm actually not an Android developer so not sure whether I can help very much with finding/fixing the bug though (just trying to put together something useful for myself/others) :)

Is there a version of the api/ankidroid which will 100% work with this API?

**Comment by KamWithK** [comment]
I took some time once again today to look into this and looks like the problem here was (at least partially) due to Android's scoped storage. Whenever you try to open the file I put into the content values/content provider, you got a permission denied error (according to the debug logs). I've managed to get around this by creating a content provider and getting my file uri from it.


I no longer see any errors when debugging due to permissions but there still doesn't seem to be any audio added to anki :(

Here's the new code (I'm just using the api instead of content values, same thing happens with that though):
```java
Uri file_uri = FileProvider.getUriForFile(context, BuildConfig.APPLICATION_ID, file);
context.grantUriPermission("com.ichi2.anki", file_uri, Intent.FLAG_GRANT_READ_URI_PERMISSION);
result = api.addMediaFromUri(file_uri, Uri.parse(filename).getLastPathSegment().replaceAll("\\..*", ""), "audio");
```

I've got a new log here which shows what seems to be happening (I've just captured the part which seems to be issues after I try and add audio in):
```
2022-03-13 13:45:45.387 1355-1542/? I/MediaProvider: Observed non-standard /storage/emulated/0/AnkiDroid/.nomedia
2022-03-13 13:45:45.395 1355-1542/? I/MediaProvider: Deleted 1 items on external_primary due to com.ichi2.anki
2022-03-13 13:45:45.398 1355-1671/? I/MediaProvider: Observed non-standard /storage/emulated/0/AnkiDroid/.nomedia
2022-03-13 13:45:45.425 3946-4149/com.example.ankiconnectandroid W/Cache Path: content://com.example.ankiconnectandroid/cache/yomichan_audio_%E3%81%8B%E3%82%93%E3%81%98_%E6%BC%A2%E5%AD%97_2022-02-13-02-45-45.mp3
2022-03-13 13:45:45.425 3946-4149/com.example.ankiconnectandroid W/Result: [sound:yomichan_audio_かんじ_漢字_2022-02-13-02-45-45_5950640672617860740.mp3]
2022-03-13 13:45:45.489 13888-32716/? I/AnkiDroid: flush - Saving information to DB...
2022-03-13 13:45:45.489 13888-32716/? I/AnkiDroid: Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
2022-03-13 13:45:45.534 13888-32716/? I/AnkiDroid: flush - Saving information to DB...
2022-03-13 13:45:45.534 13888-32716/? I/AnkiDroid: Rust: executeGetRowsAffected UPDATE col SET ls=?,crt=?,dty=?,mod=?,scm=?,usn=?,conf=?
2022-03-13 13:45:45.581 315-8874/? D/goldfish-address-space: claimShared: Ask to claim region [0x3effb7000 0x3effe3000]
2022-03-13 13:45:45.584 315-352/? D/goldfish-address-space: claimShared: Ask to claim region [0x3ef48c000 0x3ef4b8000]
2022-03-13 13:45:45.586 315-352/? D/goldfish-address-space: claimShared: Ask to claim region [0x3ef4b8000 0x3ef4e4000]
2022-03-13 13:45:47.691 1158-1158/? D/BoundBrokerSvc: onUnbind: Intent { act=com.google.android.gms.scheduler.ACTION_PROXY_SCHEDULE cmp=com.google.android.gms/.chimera.PersistentInternalBoundBrokerService }
    
    --------- beginning of system
2022-03-13 13:45:49.073 528-1502/? W/NotificationService: Toast already killed. pkg=com.example.ankiconnectandroid token=android.os.BinderProxy@f840e59
2022-03-13 13:45:50.389 13888-13902/? W/System: A resource failed to call close. 
2022-03-13 13:45:50.417 3946-3963/com.example.ankiconnectandroid W/System: A resource failed to call end. 
```
It looks to me like the file is being deleted instead of added?

**Comment by KamWithK** [comment]
Hey good news, just managed to get all the code working
Turns out the remaining problems were due to yomichan not accepting the modified file paths which I was returning (which I found a small workaround for)
Can finally hear the audio!
Thanks for the help @mikehardy

**Comment by KamWithK** [comment]
Hey good news, just managed to get all the code working
Turns out the remaining problems were due to yomichan not accepting the modified file paths which I was returning (which I found a small workaround for)
Can finally hear the audio!
Thanks for the help @mikehardy

**Comment by mikehardy** [comment]
That is fantastic! Thanks so much for updating us here, and I'm really happy it was working. This stuff is now all very subtle yes, with all the permission being deny-by-default / no-actual-file-by-default and forcing use of content resolvers and URIs etc. It's the right way to go but definitely increases the difficulty... Good luck with your projecct!

**Comment by KamWithK** [comment]
Thanks @mikehardy 
Just in case anyone else gets stuck here's an example of the [media API working in a relatively simple application](https://github.com/KamWithK/AnkiconnectAndroid/blob/master/app/src/main/java/com/kamwithk/ankiconnectandroid/ankidroid_api/MediaAPI.java#L40)

**Comment by joepetrakovich** [comment]
I have what I think is a slightly simpler example in Kotlin for images that uses the `addMediaFromUri` method from the API rather than touching the content resolver.  Keep in mind you must register a file provider ([shown here](https://developer.android.com/reference/androidx/core/content/FileProvider) - you only need to add the `cache-path` to the xml since were only using the `cacheDir`).

```    
private fun addImageToAnkiMedia(image: Bitmap): String? {
        var fileUri: Uri? = null
        var imageTempFile: File? = null

        return try {
            imageTempFile = saveImageToTempFile(image)
            //FILE_PROVIDER_AUTHORITY is a const that is a string of the same string as you put in android:authorities in your manifest
            fileUri = FileProvider.getUriForFile(appContext, FILE_PROVIDER_AUTHORITY, imageTempFile)

            appContext.grantUriPermission("com.ichi2.anki", fileUri, Intent.FLAG_GRANT_READ_URI_PERMISSION)
            ankiDroidApi.addMediaFromUri(fileUri, "poe_image", "image")
        } catch (e: Exception) {
            Log.e(TAG, "Error adding file to ankidroid media", e)
            null
        } finally {
            fileUri?.let { appContext.revokeUriPermission(fileUri, Intent.FLAG_GRANT_READ_URI_PERMISSION) }
            imageTempFile?.let { if (it.exists()) imageTempFile.delete() }
        }
    }

    private fun saveImageToTempFile(bitmap: Bitmap): File {
        try {
            val file = File(appContext.cacheDir, "poe_tempfile_${System.currentTimeMillis()}.png")

            FileOutputStream(file).use { out ->
                bitmap.compress(Bitmap.CompressFormat.PNG, 100, out)
            }

            return file
        } catch (e: Exception) {
            Log.e(TAG, "Error saving bitmap to cache dir", e)
            throw e
        }
    }
```
