### ISSUE TITLE
Autoplay audio from URL (on card side changes, no other clicks)

### ISSUE THREAD

**Issue by patarapolw** [ankidroid/Anki-Android#10346]
**Is your feature request related to a problem? Please describe.**

It is possible to use TTS from JavaScript API, but the voice is not native. Also, sometimes `AnkiDroidJS.ankiTtsSpeak` is not defined for some reasons.

I can indeed use AwesomeTTS to generate audio files, but syncing large media folder is quite problematic, as well as **it is impossible to do in large batch with gTTS.** Instead, I chose to run gTTS on demand on an external server, but of course, it is not uploaded to AnkiDroid that way.

HTML5 Audio element can be created, but autoplay doesn't work. Clicking via JavaScript doesn't work either unless there is an actual click.

**Describe the solution you'd like**

`AnkiDroidJS.ankiPlayAudio` to play audio on Java/Kotlin side would pretty much be the surefire way.

**Describe alternatives you've considered**

I can also trap the first click, so this works.

```html
<script>
(function() {
  function doAutoplay() { document.querySelector('[autoplay]').click(); document.removeEventListener('click', doAutoplay) }
  document.addEventListener('click', doAutoplay)
})()
</script>
```

**Additional context**

TTS / audio files in Anki are a very big culprit of sync size, especially on the first sync. I think it is always better to allow online shared resources.

**Comment by krmanik** [comment]
The TTS JS API is implemented on top of java/kotlin. It uses the TTS engine on the device. 
View more about it in this PR https://github.com/ankidroid/Anki-Android/pull/8812

https://github.com/ankidroid/Anki-Android/blob/67d29b4dca04bdef238fdcbfbc0930e9d11c06f1/AnkiDroid/src/main/java/com/ichi2/anki/JavaScriptTTS.java#L31

**Comment by krmanik** [comment]
I tested above two code snippets. The autoplay works correctly.

Also I didn't get the following Exception
>Uncaught (in promise) DOMException: play() can only be initiated by a user gesture.

May be it is device specific issues. Can you add `Debug Info`?

>###### Debug info
>Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by patarapolw** [comment]
Debug Info

```
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-P610

Hardware = exynos9611

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-P610 Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.87 Safari/537.36

ACRA UUID = 276df1ab-2494-4fbb-9dca-05d55d3472f4

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```
