### ISSUE TITLE
Paste text without formatting as a default option

### ISSUE THREAD

**Issue by human912** [ankidroid/Anki-Android#10349]
**Is your feature request related to a problem? Please describe.**
When creating new notes and dealing with resources rich in formatting, I find it unpractical to manually choose the "paste without text" option every time I copy a text to my newly-created notes. It's not among the basic choices (paste, cut, copy) and it's easy to forget and just paste the usual way, with formatting, which then needs to be cleaned up afterwards. Is there a way to always strip formatting off a pasted text from outside and make it as a default option in Ankidroid?

**Describe the solution you'd like**
I'm looking for a solution that strips formatting off of the pasted text always, by default. One could choose this option in settings/preferences, which is currently possible on the desktop version of Anki. It's also a common feature in some text editors.

**Describe alternatives you've considered**
So far I haven't considered any alternatives, except creating such problematic notes (where there will be a lot of formatted text), exclusively on the desktop version of Anki.

**Additional context**
/

**Comment by Tinkidinki** [comment]
Hey, on my Ankidroid (version 2.15.6), paste without formatting seems to be the default while making notes. Just tried pasting text with varying fonts, bold, italics and underlined text. 

Are you referring to some specific type of formatting that gets copied over?

**Comment by human912** [comment]
> Hey, on my Ankidroid (version 2.15.6), paste without formatting seems to be the default while making notes. Just tried pasting text with varying fonts, bold, italics and underlined text.
> 
> Are you referring to some specific type of formatting that gets copied over?

Ok, I tested again. When I paste the text in the note not by choosing "paste", but by clicking on the clipboard above my onscreen keyboard of my android phone, it comes up stripped out of all formatting, just as I want.
![Screenshot_20220215-115452_AnkiDroid](https://user-images.githubusercontent.com/99691305/154048790-69e355a8-1b07-4a34-b1c5-dbdb8982b522.jpg)

But if I manually touch a field and choose "paste", it comes with formatting.
![Screenshot_20220215-115032_AnkiDroid](https://user-images.githubusercontent.com/99691305/154048816-149824bb-47bb-4337-97ec-ddd5c93f9515.jpg)

The problem is that the "clipboard paste" method is not always available. If you don't do it immediately and you go edit another note and then return to this note,  I can only do the regular paste method, which then gives me an unwanted formatted text. 
You can see in the pictures. I took a random article from The Guardian.
![Screenshot_20220215-114938_Samsung Internet](https://user-images.githubusercontent.com/99691305/154048951-070312ae-24b2-4554-a711-59381a00439a.jpg)

**Comment by GuidoFe** [comment]
In the same menu where the Paste option is, I see also the option "Paste as plain text". Do you see it? Maybe you have to expand the menu by clicking on the three vertical dots icon

**Comment by human912** [comment]
> In the same menu where the Paste option is, I see also the option "Paste as plain text". Do you see it? Maybe you have to expand the menu by clicking on the three vertical dots icon

Yes, I see it and I use it. I was wondering if there's a solution, where the main "paste" does exactly the same as the "paste as plan text" option by default. So, regardless which option i press, it's always zero formatting, even if I press just "paste" by mistake, which happens regularly and it's a time waster. On another phone I have to always manually expand the menu to get to the "paste as plain text", which is even worse. 

On the Anki desktop version, once you tick the box for zero formatting in preferences, you're set. No worries about missing using Ctrl+Shift+V instead of Ctrl+V. It's always without formatting, regardless.

**Comment by krmanik** [comment]
Sure!

**Comment by viciousAegis** [comment]
@human912 Can you try this once: 
1. Create a sample note, paste the formatted text in your note as is, and add the note in any test deck, Don't remove the formatting.
2. In the card browser, go back to the card and open it in the Note Editor.
3. For me, all the formatting is appearing stripped once I see the note again

Basically, the text only appears formatted the first time you paste it, and automatically becomes plain once you add the card, so you don't need to manually remove formatting.

Even when you open the card to study, the formatting should not appear. 

Please let me know if you can reproduce this and whether this is a viable solution to your problem. Thanks!

**Comment by human912** [comment]
@viciousAegis 
I'm not sure if I should reply here or on the linked pull request #10365 
I reproduced the method you mentioned and it works correctly, as you said. I can confirm that the formatting is appearing stripped once I see the note again. 
This is a viable solution, so mods can close this issue, as far as I'm concerned.
Thanks for the help!

**Comment by viciousAegis** [comment]
> @viciousAegis 
> 
> I'm not sure if I should reply here or on the linked pull request #10365 
> 
> I reproduced the method you mentioned and it works correctly, as you said. I can confirm that the formatting is appearing stripped once I see the note again. 
> 
> This is a viable solution, so mods can close this issue, as far as I'm concerned.
> 
> Thanks for the help!

Hey! Yep, what is happening is that, the formatting IS stripped, but it is not being displayed as stripped. This, it's false information. The linked PR will make the text stripped by default so that there is no inconsistency between what is saved and what is shown to the user!
