### ISSUE TITLE
Card answer has extra 'answer' class that is not in Anki for Windows

### ISSUE THREAD

**Issue by anewstheart** [ankidroid/Anki-Android#10356]
https://github.com/ankidroid/Anki-Android/blob/0f7b0bebed9539c6ee46608539be23c2e5db4780/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.kt#L84-L86

```
  <div class="answer" id="qa"><style>.card {
    font-family: Calibri, sans;
    font-size: 24px;
    text-align: center;
    color: #000000;
	background: #ddd;
}

</style>Ni Å¾vakaÄe iz trgovine nije ukrala.

<hr id=answer>
```

In Anki for Windows:

```

<div id="qa" style="opacity: 1;"><style>.card {
    font-family: Calibri, sans;
    font-size: 24px;
    text-align: center;
    color: white;
	background: #222;
}
.......
</style>Ustati i zasjati pospana glava!

<hr id="answer">
```

**Comment by david-allison** [comment]
@anewstheart Which version of Anki for Windows is this?

**Comment by BrayanDSO** [comment]
May I work on this?

**Comment by BrayanDSO** [comment]
Reproduced. Added the following css
```css
.answer {
background-color: yellow;
}
```
Results:
Desktop:
![2022_02_18-17_06_23](https://user-images.githubusercontent.com/69634269/154754221-2eb4643c-266f-4083-ba5c-96ffbc967bb2.png)

Ankidroid:
![Screenshot_20220218-170612_AnkiDroid](https://user-images.githubusercontent.com/69634269/154754300-4cbdd128-2899-45a8-8149-fef5cead7278.png)
![Screenshot_20220218-170617_AnkiDroid](https://user-images.githubusercontent.com/69634269/154754312-b92c887e-407a-4453-85b4-6cbb83aad1b6.png)

**Comment by BrayanDSO** [comment]
Another related extra class ankidroid adds is "question" to the front side
Reproduction:
```css
.question {
background-color: cyan;
}
```
Desktop:
![2022_02_18-17_13_40](https://user-images.githubusercontent.com/69634269/154755168-6f434985-4d26-4e39-9c2b-cc812c82d8b3.png)

Ankidroid:
![Screenshot_20220218-171556_AnkiDroid](https://user-images.githubusercontent.com/69634269/154755214-45a74157-15d3-457c-b8b8-8e4a60daf90f.png)

**Comment by david-allison** [comment]
Assigned, thanks!

**Comment by mikehardy** [comment]
A philosophical question - do we want to maybe break people's templates like this? If we remove these symbols it's a breaking change for people.

**Comment by david-allison** [comment]
We seem to be stuck between a rock and a hard place here. If Anki Desktop has made a breaking change, then we should (sadly) follow it to stay compatible.

If we were the ones that made the breaking change, then it's less vital, it would be ideal to be as compatible as possible - otherwise it becomes much harder to detect further breaking changes, but this seems to be much less set in stone.

I think the question to move this issue on would be: were we ever in alignment with Anki Desktop here?

**Comment by BrayanDSO** [comment]
In my experience, I haven't known until now there was classes only for styling front or back on Ankidroid. I can't find them on repo wiki or [user manual](https://docs.ankidroid.org/manual.html). 

Therefore I believe most people only discover them by chance when trying to use these specific classes names for another things. I think only a minority of people would discover this and find it useful to keep using it.

**Comment by anewstheart** [comment]
The Anki desktop documentation is referenced for styling so being
incompatible will create additional documentation burden.

**Comment by mikehardy** [comment]
I'm sympathetic to the argument of referencing upstream docs for styling means we should conform, so I'll go +1 on related PR, I will make a note in the release notes. I suppose if this becomes a big issue the proper resolution is to pursue adding the css selector upstream then we could revert this
