### ISSUE TITLE
Request: controller support hehe

### ISSUE THREAD

**Issue by ImanCraft** [ankidroid/Anki-Android#10351]
Problem: native controller support isn't enough please add input/button mapping options 

Option to map buttons from android controllers to specific functions like answer 1 - 4, menu, undo answer, play sound, etc.

I bought a gamsir x2 cause I'm a loser but I thought about using it w anki to study and again natively it's alright but could be super cool I think if I could just map functions to the buttons/joysticks

**Comment by mikehardy** [comment]
Hi there! Have you tried the latest alphas? They allow a flexible input mapping that may do what you want - https://github.com/ankidroid/Anki-Android/releases/

**Comment by ImanCraft** [comment]
Sorry! I didn't know about them 😅 but thank you so much i just updated anki and found the mapping settings. I can't wait to try

**Comment by mikehardy** [comment]
No worries @ImanCraft there's no real reason you should know about them, but the new controller mapping stuff is pretty excellent I think? You might be one of the first real testers on it so hopefully it works and if not, do post details of what you tried and what you want and what isn't working here and we can tune it as needed. Cheers

**Comment by billehunt** [comment]
So excited to discover this feature! I highly recommend the community makes people more aware of these alpha releases - I had no idea they were available, and spent a ton of non-joy trying to patch together this feature with external apps. This is so very cool - Thanks!
