### ISSUE TITLE
Improve restore backup dialog user friendliness

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10362]
**Is your feature request related to a problem? Please describe.**
When choosing a backup to restore, it shows a dialog like this:
![Screenshot_20220219-095745_AnkiDroid](https://user-images.githubusercontent.com/69634269/154801857-1c9b8611-d33a-47b3-ae67-00a66916469b.png)

Most people would find these options gibberish. It isn't natural to deduce that is a pattern of `collection-year-month-date-hour-minute.colpkg`, specially since this info isn't at the user manual and people of different languages/countries may even don't know how to read these letters.

**Describe the solution you'd like**
The files don't need to be renamed, only the strings shown on the dialog.
The ideal solution would be to follow a scheme according to user localization, without "collection-" prefix and ".colpkg" suffix:

Examples:
- English: `month-day-year hour:minute`, e.g. `02-19-2022 10:09`
- Portuguese: `day-month-year hour:minute`,  e.g. `19-02-2022 10:09`
- Japanese: `year年month月day日 hour:minute`, e.g. `2022年02月19日 10:09`

**Describe alternatives you've considered**
- Using an ISO pattern for all localizations like: `Year-month-date hour:minute`, without "collection-" prefix and ".colpkg" suffix (e.g. 2022-02-19 10:09)
- Putting this on the user manual

**Additional context**
Anki desktop doesn't do this. It just open a dialog to choose the collection file. Since I believe this isn't ideal either, I still think a more user friendly scheme should be approached
![2022_02_19-09_59_09](https://user-images.githubusercontent.com/69634269/154802090-6ae10d48-32c0-495b-9b6e-88a74f701ee6.png)

**Comment by mikehardy** [comment]
We are in control of the file naming format, so it seems okay to assume they are parse-able (with appropriate error handling just in case, of course).

If there were a PR where the directory of backups was listed, and any files that were parse-able were then formatted via substitution strings that were localizable, that would be great - then any non-parseable files that were still colpkgs could be tacked on the end (just in case? who knows)

A note in the area of backup generation should be left where the file name is constructed for the backup, mentioning that it must not be changed unless the corresponding parsing is changed

**Comment by BrayanDSO** [comment]
At the moment, Ankidroid doesn't show any file which doesn't follow the pattern `collection-year-month-date-hour-minute.colpkg`. This may be a problem if someone tries to restore a backup from Anki Desktop, because it follows a different name scheme. So, I think this should be updated too.

Removing the `.colpkg` to non-parseable files would be nicer or unnecessary since if someone put the file with a different name there, they must know what they are doing?

**Comment by BrayanDSO** [comment]
After thinking more about it, I've changed my opinion. To keep things simple, only the current name scheme (`collection-year-month-date-hour-minute.colpkg`) on backups folder should be shown on dialog. If someone wants to restore from another .colpkg, they should use the `Import` option.

Others' opinions are welcome as well.

**Comment by mikehardy** [comment]
That sounds reasonable, to me

**Comment by david-allison** [comment]
I think you raise a good point: A user wouldn't think to use "import" as "restore my backup".

I'd be open to UX to allow this functionality to be added to the "restore backup" screen, maybe turning it into a tabbed control, maybe a separate button somewhere on the dialog.

**Comment by BrayanDSO** [comment]
I think the most inclusive and least disruptive change would be:
- Parse Ankidroid filenames to localizable and human-readable strings
- Do the same thing with Anki Desktop filenames, since they are parseable too and most likely won't change (as they haven't for 5+ years)
- Add a `Choose another` button to choose another file the same way as `Import .colpkg` and Anki desktop

The result would look like this:
![Screenshot_20220221-064933_AnkiDroid](https://user-images.githubusercontent.com/69634269/154931336-b478501f-aaf7-43e5-9e98-c8b096b865f3.png)

`Choose another` file picking (the same as current `Import`)
![Screenshot_20220221-065006_Files](https://user-images.githubusercontent.com/69634269/154931722-e0c3a017-6b4a-42f6-9223-0e9a161791c8.png)

I'm still against putting non-parseable names on the first list because they can interfere with the UX there. 
Most people just want to restore the backups Ankidroid made. Seeing a tab or something like it would add confusion. 
If they copy their anki desktop folder or a backup from there, they can see their backups as well because desktop naming scheme is parseable too.

For the minority of people which have a backup with different name scheme, it means they changed it and put it deliberately on the backup folder, so they must know what they are doing and can still restore it with `Choose another` button

**Comment by BrayanDSO** [comment]
The work is done. #10388 needs to be fixed first so backups from Anki Desktop can be restored. I'll try to look into it later. When it is fixed, I'll submit the PR

**Comment by BrayanDSO** [comment]
Since #10388 doesn't seem to be fixable in the short-term, can I leave the parsing of Anki desktop backup names to the future and submit the PR?

It's still an advance:
- Adds localizable human-readable options
- Adds a choose another button, so the user isn't limited to that options
- It doesn't break any current functionality, since at the moment only the files with AnkiDroid name scheme show on the list and Anki desktop backups can't be restored
