### ISSUE TITLE
Copy/Paste/Select Action menu not visible in Night Mode

### ISSUE THREAD

**Issue by viciousAegis** [ankidroid/Anki-Android#10366]
###### Reproduction Steps
On my Xiaomi Redmi Note 8: 
1. While in light mode, in the Note Editor text fields, the `paste/copy/select` action popup works just fine.
2. switch to dark mode, long press to bring up the action popup

###### Expected Result
`paste/copy/select` action popup works normally

###### Actual Result
 The text in the popup is not present, i.e. the popup is blank. The actions still work

![image](https://user-images.githubusercontent.com/86671025/154821069-0cdf9689-dace-4737-bd2e-75151bce3079.png)

![image](https://user-images.githubusercontent.com/86671025/154821072-ec6d19ed-3225-45f8-a9ee-7c95db218dec.png)

### Possible Problem:

I am guessing that on switching to dark mode, the text is switched to white, while the action menu background stays white. Thus, the clash of the colors makes the text go invisible

###### Debug info
```
AnkiDroid Version = 2.15.6

Android Version = 9

Manufacturer = Xiaomi

Model = Redmi Note 8 Pro

Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 9; Redmi Note 8 Pro Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.85 Mobile Safari/537.36

ACRA UUID = 21d405cb-cda8-46ff-b6b4-38ac0fa5d51e

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Finally! We've been looking to replicate this one for ages

Thanks!

**Comment by viciousAegis** [comment]
You're welcome! 
If it's viable, I would like to work on this issue! (partly also because I believe I'm one of the few people with MIUI here)

**Comment by viciousAegis** [comment]
Found it: #6614

Has some work already been done on this?

**Comment by david-allison** [comment]
No, I'd love to, but I can't reproduce this (even on my Xiaomi). Help here would be massively appreciated

**Comment by viciousAegis** [comment]
Okay, I will see what I can do :)

**Comment by mikehardy** [comment]
Now if only one of the new contributors has a chromebook hahaha - maybe we can finally reproduce *all* our zombie bugs!

**Comment by viciousAegis** [comment]
@david-allison On enabling Night Mode **on the phone** and switching on Light Mode **in the AnkiDroid app**, the following happens. 
![image](https://user-images.githubusercontent.com/86671025/155007046-c4a3cbb9-c828-4784-8a51-0784691e1658.png)

So, because toggling the night mode on AnkiDroid somehow changes the action popup text colour, the text colour clashes with the background and the text becomes invisible. 

Either we stop changing the text colour on our end, or make an option for AnkiDroid to follow the system dark mode (I think this is a WIP?)

**Comment by david-allison** [comment]
@viciousAegis My best guess would be to add an AnkiDroid theme where all the colors are distinct, then use a color picker to determine which part of the theme the context menu is using.

A year in the future, I don't think my comment will work, but we can try

**Comment by Satya-Prakash0** [comment]
I would like to work on this issue can you assign me

**Comment by david-allison** [comment]
> I would like to work on this issue can you assign me

Can you reproduce the issue on your phone?

**Comment by david-allison** [comment]
@viciousAegis is this still an issue?

**Comment by viciousAegis** [comment]
No, works fine now. Not sure what fixed it
