### ISSUE TITLE
[Feature] Display Subdecks in "Deck Search" the same way they are displayed in the "Deck Browser"

### ISSUE THREAD

**Issue by viciousAegis** [ankidroid/Anki-Android#10378]
**Is your feature request related to a problem? Please describe.**

When selecting a deck in the note editor, on opening the deck search, subdecks are treated as decks with a separator ( :: ) to distinguish them. This makes them hard to read and distinguish, especially if two decks are very far down the hierarchy. 

I realise that Anki Desktop also follows the same convention to list their decks, so it may be hard to tinker with it, but this convention is much harder to read on a mobile than on a computer, so any improvement (if possible) will be welcome. 

### Current Deck Search screen
![image](https://user-images.githubusercontent.com/86671025/155142408-c00cf490-65f1-4bef-a128-3e7aa4b5fe9c.png)

**Describe the solution you'd like**
### Possible Improvement
Alternatively, if they were displayed as they are in the "Decks" menu, with proper indentation, it would be a lot cleaner and easier to select the deck you want.
![image](https://user-images.githubusercontent.com/86671025/155142619-5ca145a1-7a2e-432c-b521-6736ec71e89f.png)

**Describe alternatives you've considered**
Use the deck search to find the exact deck you want. Effective, but not the most convenient choice.

**Comment by Akshay0701** [comment]
Hello!
Thank you for the suggestion, We follow upstream Anki for making changes in AnkiDroid, 

> I realise that Anki Desktop also follows the same convention to list their decks, so it may be hard to tinker with it

and as you mentioned Anki Desktop also does the same as AnkiDroid, then I don't think so we should change the convention.

**Comment by david-allison** [comment]
For context: I'd be happy with this change. 

I made the "Deck Search" to for a rarely used subscreen and therefore didn't put in much effort with the UX. I feel it would be an improvement to use nested decks, and we're not introducing any concepts here that aren't already understood in Anki Desktop.

**Comment by viciousAegis** [comment]
@david-allison Great! Just to confirm, is this the file that shows "Deck Search" ? (I tried tinkering in `DeckSpinnerSelection.kt` yesterday, but that was not the right one. )
 
https://github.com/ankidroid/Anki-Android/blob/cab3c0d15d45f84d1ed1efba7ae74e5965e7e3bb/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt#L53-L62

**Comment by david-allison** [comment]
That's it!

**Comment by viciousAegis** [comment]
@david-allison How does this look?

![image](https://user-images.githubusercontent.com/86671025/155371342-02b5d3dc-1c59-4212-ab12-13cfd179fd5f.png)

**Comment by Akshay0701** [comment]
Fantastic 🌟

**Comment by david-allison** [comment]
Awesome!

**Comment by viciousAegis** [comment]
I've made it such that if you search for the parent deck, all the subdecks also show up, so the search functionality remains the same. 

I feel the code might be a little messy 😅 , so will appreciate refactoring and comments on the code once a PR is up.
