### ISSUE TITLE
[Bug] TTS disregards all text fields in a card if one of them includes an audio file

### ISSUE THREAD

**Issue by jparta** [ankidroid/Anki-Android#10379]
###### Reproduction Steps

1. Have two fields in a card, one with audio, one with text.
2. Enable TTS in Settings > Advanced > Plugins
3. View card in reviews

###### Expected Result

Audio is played and second field is read aloud

###### Actual Result

Audio is played, but the text in the other field is not read aloud by TTS.

###### Debug info

    AnkiDroid Version = 2.16alpha29

    Android Version = 11

    Manufacturer = OPPO

    Model = CPH1951

    Hardware = mt6779

    Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH1951 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36

    ACRA UUID = f939c8ba-2220-489e-abb1-d041f0afd05a

    Scheduler = std2

    Crash Reports Enabled = true

    DatabaseV2 Enabled = true`

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! We are on alpha44 now, do you think you could update and give it a try just in case we have fixed it already? https://github.com/ankidroid/Anki-Android/releases/

**Comment by jparta** [comment]
@mikehardy
I can reproduce the behaviour in alpha44.

**Comment by jparta** [comment]
The functionality I expect would be very useful when revealing additional information related to the FrontSide after the reveal.

**Comment by mikehardy** [comment]
The Preview mode is not really intended for full study - it is intended to verify that the card contents are generally correct and layout is generally correct, and not all features are enabled in it, it appears TTS is simply one of those things.

I assume the TTS is behaving as you expect during review?

**Comment by jparta** [comment]
TTS works for one field even in preview, but not the other. I assume this is because TTS is done after templating substitutions, and doesn't care about fields at all. The behavior is the same in preview and review. I edited the reproduction steps to reflect this.
