### ISSUE TITLE
Remove "paste as plain text"

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10377]
Thanks to @viciousAegis in #10365, "paste" work as "paste as plain text". Which mean we have two different context menu entries that have the same behavior I fear.

It would be nice to remove one of them. I'd suggest removing "paste as plain text". When there is a single feature, adding details is useless.

If eventually, "formatted text" can be transformed into an "paste as html", then it will be useful to have both of them. But since we are not even sure yet we want this feature, removing one of the two paste entry seems a no-brainer

_Originally posted by @Arthur-Milchior in https://github.com/ankidroid/Anki-Android/issues/10365#issuecomment-1047730112_

**Comment by viciousAegis** [comment]
I'd like to take this up as a continuation of the mentioned PR.

**Comment by Arthur-Milchior** [comment]
In case you don't know, you can try on emulator. But yeah, fine to wait for someone else. Especially with GSoC arriving soon and not a very hard project

**Comment by BrayanDSO** [comment]
To anyone who tries to fix this, "Paste as plain text" is a default item of the context menu of android O or newer, not exclusive to Ankidroid.
I don't know if this is feasible and appliable to all manufacters android flavors, but I'll hope it is.
If it isn't possible to remove it, maybe hiding it at the context menu "..." list would be useful IMO

**Comment by Arthur-Milchior** [comment]
Take a look at https://developer.android.com/reference/android/widget/TextView#setCustomInsertionActionModeCallback(android.view.ActionMode.Callback) and https://developer.android.com/reference/android/widget/TextView#setCustomSelectionActionModeCallback(android.view.ActionMode.Callback) I believe that what you would want

**Comment by david-allison** [comment]
Sounds good to me!

**Comment by Niraj81** [comment]
Can i give it a try?

**Comment by s-deepak-kumar** [comment]
@Tanish-5007, Are You Still Work On It?

**Comment by smish-hash** [comment]
Hi @Arthur-Milchior, I would like to work on this.

**Comment by Arthur-Milchior** [comment]
@smish-hash go for it

**Comment by shivam-2701** [comment]
Hey @Arthur-Milchior is this issue is up for taking. Like to contribute

**Comment by david-allison** [comment]
Thanks!

Related: https://github.com/ankidroid/Anki-Android/pull/11656

**Comment by shivam-2701** [comment]
Hey can someone point me to the directory in code where this "paste as plain text" context menu is written.
PS : new to open source apologize for inconvenience

**Comment by shivam-2701** [comment]
Can someone point me to the directory or activity from where we have to remove "paste as plain text".
PS: new to open source apologies for inconvenience.

**Comment by david-allison** [comment]
> Can someone point me to the directory or activity from where we have to remove "paste as plain text". PS: new to open source apologies for inconvenience.

`NoteEditor.kt`

**Comment by shivam-2701** [comment]
@BrayanDSO Can you point me some resource to implement this.
Thanks

**Comment by viciousAegis** [comment]
@shivam-2701 Take a look at this [link](https://developer.android.com/reference/android/widget/TextView#setCustomInsertionActionModeCallback(android.view.ActionMode.Callback)) mentioned in the comment [here](https://github.com/ankidroid/Anki-Android/issues/10377#issuecomment-1048568235), and I believe you will find the relevant code here:

https://github.com/ankidroid/Anki-Android/blob/69da0c89e8795427156bb98afac66414f618a763/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt#L2065-L2084

**Comment by shivam-2701** [comment]
@viciousAegis Thanks for the help.

**Comment by shivam-2701** [comment]
Getting an error in the android studio in the code from the pull request
https://github.com/ankidroid/Anki-Android/blob/69da0c89e8795427156bb98afac66414f618a763/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt#L1137-L1157

In line number 1139
Error :  Unresolved reference: defaultLegacySchema
![2022-06-30](https://user-images.githubusercontent.com/98466713/176730375-e9fea856-ec86-4cab-8c08-287dfce013b3.png)

**Comment by mikehardy** [comment]
@shivam-2701 you may need to rebase over main? Looks related to lack of this code integrated in whatever you are working on #11644

**Comment by shivam-2701** [comment]
@mikehardy I have rebased over main but the error still persists

**Comment by shivam-2701** [comment]
@mikehardy Error still persists even after rebasing over main

**Comment by viciousAegis** [comment]
> @mikehardy Error still persists even after rebasing over main

@shivam-2701 Try building the project again in a separate directory

**Comment by shivam-2701** [comment]
The projects builds and also works. But i can't commit as it shows error

**Comment by mikehardy** [comment]
"I can't commit as it shows error"

We are not mind readers, "it shows error", well, what error? Every report of an error needs details for others to help, or you can't expect help

https://stackoverflow.com/help/how-to-ask

**Comment by shivam-2701** [comment]
Sorry if you were not able to understand. when I am trying to commit changes android studio points out the above mentioned error which is :  "Unresolved reference: defaultLegacySchema" on line 1140 .
And stopping me from commiting my changes.
What I have tried:
I have rebased my code to main after updating my local repo from the remote upstream.

**Comment by shivam-2701** [comment]
Update: The previous error was fixed after a fresh clone of the project.
I was able to fix the "paste as plain text" issue , the project even builds and runs on my device.
But when I try to make a commit the following error crops:

ERROR: AnkiDroid builds with JVM version 11, 14, or 16.
  Incompatible major version detected: '17'

I am using Gradle JDK: version 11  11.0.12
but I also have version 17 installed from another project.

**Comment by shivam-2701** [comment]
Update: The previous error was fixed after a fresh clone of the project.
I was able to fix the "paste as plain text" issue , the project even builds and runs on my device.
But when I try to make a commit the following error crops:

ERROR: AnkiDroid builds with JVM version 11, 14, or 16.
  Incompatible major version detected: '17'

I am using Gradle JDK: version 11  11.0.12(Embedded JDK )
but I also have version 17 installed from another project.

I have also found the part of code which might have something to do with it
https://github.com/ankidroid/Anki-Android/blob/d6e9c0c33a4c0d6d7f929f719a6e4a424b885e99/build.gradle#L82-L121

**Comment by mikehardy** [comment]
> I am using Gradle JDK: version 11 11.0.12(Embedded JDK )

This assertion is false unfortunately - you *think* you are using JDK11, but actually when you are executing whatever command you are executing, JDK17 is in use. Or it wouldn't detect JVM version 17 and throw the error right?

Examine your PATH etc and make sure JDK11 is actually first and in use when you go to commit

**Comment by shivam-2701** [comment]
Thanks for the help. 

> > I am using Gradle JDK: version 11 11.0.12(Embedded JDK )
> 
> This assertion is false unfortunately - you _think_ you are using JDK11, but actually when you are executing whatever command you are executing, JDK17 is in use. Or it wouldn't detect JVM version 17 and throw the error right?
> 
> Examine your PATH etc and make sure JDK11 is actually first and in use when you go to commit

**Comment by snowtimeglass** [comment]
> If eventually, "formatted text" can be transformed into an "paste as html", then it will be useful to have both of them. But since we are not even sure yet we want this feature, 


_Originally posted by @Arthur-Milchior in https://github.com/ankidroid/Anki-Android/issues/10377#issue-1146831189_


> Probably worth exploring this an option for people caring about formatting (even if it will probably lead to ugly HTML)


_Originally posted by @Arthur-Milchior in https://github.com/ankidroid/Anki-Android/pull/10365#pullrequestreview-887974709_
            

I read an user's feedback with potential need for this feature ("paste as html" in the context menu). 

Is it unlikely that this feature will be implemented for the current editor (that is, before the WYSIWYG editor is introduced)?
