### ISSUE TITLE
Remove `is/equalTo(true/false)` in test

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10386]
Personally, I find `assertThat("explanation", property, is(true))` ugly, given that `foo is true` is equivalent to `foo`. Similarly, `assertThat("explanation", property, is(false))` would sounds better in English with `assertNot("explanation", property)`.

So, I believe our test would be improved if:
* we removed `is(true)`. Which require to add a method `assertThat(property: Boolean)`, since some assertion don't (yet) have an explanation.
* we removed `is(false)`. Which require to add methods `assertNot(property: Boolean)` and `assertNot(cause: String, property: Boolean)`

However, I don't suggest that `assertNot` should accept a matcher; if the assertion is more complex than a boolean property, then using the matcher `not` on an other `matcher` seems okay to me.

**Comment by deepanshu731** [comment]
@Arthur-Milchior I would like to work on this issue

**Comment by mikehardy** [comment]
writing new tests that expand coverage would be more valuable in my opinion as well. A bunch of test PRs that are just refactors is just time-consuming noise, to me
