### ISSUE TITLE
Add explanation to all tests

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10385]
Most of the tests have a message stating what was expected that did not occur. This ensure that a test failure is accompanied with at least a first hint of what is wrong.

Since most tests are not flaky, the absence of such message is not a big deal, but still, it would be nice for code beauty to ensure that most tests have a message explaining what was expected. I believe it is a good first issue because most assertions are straightforward when you read the class name, the test method name and even what is actually tested.

On a bonus, that will allow to remove a lot of `equalTo(true)` and `is(true)`, which I personally find ugly. Given that "I assert foo is true" is the same thing as "I assert foo" but more verbose. (Right now `assertThat("cause", property)` and `assertThat(value, matcher)` exists, but not `assertThat(property)`.)

Once it's done, it would be nice to add a linter that forbids to use `assertThat` without message.

**Comment by david-allison** [comment]
I'd really like to see more matchers. For example: "file exists" would be useful, so we can reduce the verbosity of the error .

And something along the lines of `hasSingleElementEqualTo`

**Comment by Arthur-Milchior** [comment]
@david-allison I strongly suggest creating your own issue and add more explanations. We'll, hopefully, soon have a lot of developers in need of a good first issue. Myself, I don't know exactly what you are talking about here (even if I suspect I could find by myself). Which mean, I fear, that this reply will be totally lost and unusable to every new contributors that will arrive. While a more detailled explanation in its own issue will allow for plenty of PR improving the code part by part.

**Comment by david-allison** [comment]
Sounds good to me. I'm on my phone right now, but will move this and delete/hide the comments later, if that's ok with you

**Comment by Arthur-Milchior** [comment]
Perfectly fine. No emergency

**Comment by puranjayK** [comment]
@Arthur-Milchior I would like to work on this issue, could you please assign it to me

**Comment by Arthur-Milchior** [comment]
Done @puranjayK. However, it can be possible for multiple people to work on it, given that there is a lot of work to do. 
So it would be nice also for you to update here on what you did, so that if someone else is interested, they know what is done and what remains

**Comment by Sustech-yx** [comment]
@Arthur-Milchior I'm interested in this and would like to work on this issue, could you please assign it to me?

**Comment by Arthur-Milchior** [comment]
@Sustech-yx I already assigned it to @puranjayK. 
@puranjayK did you start working on it? Can you state what you already did so that @Sustech-yx can work on other part

**Comment by puranjayK** [comment]
@Sustech-yx , I was reading upon tests currently.
As mentioned earlier, this issue requires a lot of work to be done, so we both can work on it. Just mention whatever part you are doing.

**Comment by Sustech-yx** [comment]
@puranjayK ,hello. I am trying to reading and understand such things. I will inform my origress under the issue

**Comment by puranjayK** [comment]
@Sustech-yx I have added explanations for AnswerTimerTest (package com.ichi2.anki.reviewer)
