### ISSUE TITLE
Rename "master" branch to "main"

### ISSUE THREAD

**Issue by nicolas-raoul** [ankidroid/Anki-Android#10399]
Context: https://www.zdnet.com/article/github-to-replace-master-with-alternative-term-to-avoid-slavery-references/

`main` actually is more understandable, so from my point of view, why not?

Apparently it is straightforward: https://github.com/github/renaming

**Comment by mikehardy** [comment]
I have done this in a lot of repos already, it is pretty straightforward. In fact, this may be the *last* repo where I have not done it!

These are the only friction points, and they are not blockers, they just generate a little noise as everyone settles in to the new branch:

```
Show a notice to repository contributors, maintainers, and admins on the repository homepage with instructions to update local copies of the repository
Show a notice to contributors who git push to the old branch
```

It really requires someone with admin rights and motivation to take it on and this is something I don't mind doing, I'll get it in a little bit

**Comment by mikehardy** [comment]
Done - got all the repositories in the org
