### ISSUE TITLE
Creating new deck with name same as any existing deck should give proper error message

### ISSUE THREAD

**Issue by AayushSolanki** [ankidroid/Anki-Android#10401]
###### Reproduction Steps

1. Create new deck.
2. Set name same as any existing deck.

###### Result
No error message displayed

###### Expected Result
Should give a message that deck with same name exists

https://user-images.githubusercontent.com/75438613/155757640-201b7a41-6bd9-4ac0-af2b-0f07e8dcf339.mp4

**Comment by AayushSolanki** [comment]
I would like to work on this issue

**Comment by Arthur-Milchior** [comment]
Just tested on desktop. There is no warning there in this case. but I admit that a toast may still be a better user experience in this case

**Comment by AayushSolanki** [comment]
i will be submitting a PR after my academic exams

**Comment by dae** [comment]
Counterargument: it makes the request idempotent. The user asks for a deck with name x, and when the command returns, they have a deck with name x (even if it already existed). Why make it an error?

One reason the backend doesn't make this an error is that the existence check requires unicode case folding, which the frontend may struggle with.

**Comment by mikehardy** [comment]
In the absence of progress + the presence of staleness indicating lack of interest + the presence of Anki Desktop maintainer having considered this before and showing a technical reason not to, going to close
