### ISSUE TITLE
[Bug]Some Incompatible API Usages in APP

### ISSUE THREAD

**Issue by Valentin-ys** [ankidroid/Anki-Android#10409]
For your app, we have found that this project has accessed the following APIs which are available only on an API level higher than the declared minSdkVersion and which are accessed without proper protection. In other words, if those APIs get called at runtime, it will trigger a NoSuchMethodError and thus result in a crash of the running application.

1. <android.webkit.WebView: android.webkit.WebViewClient getWebViewClient()>: [26,30]
``` java
Error path: <com.ichi2.anki.servicelayer.DebugInfoService: java.lang.String getDebugInfo(android.content.Context,com.ichi2.utils.FunctionalInterfaces$Supplier)>[[]]--><com.ichi2.anki.servicelayer.DebugInfoService: java.lang.String getWebviewUserAgent(android.content.Context)>[[]]--><android.webkit.WebView: void <init>(android.content.Context)>[]--><android.webkit.WebView: android.webkit.WebViewClient getWebViewClient()>

Error path: <com.ichi2.anki.AbstractFlashcardViewer$MyWebView: void <init>(com.ichi2.anki.AbstractFlashcardViewer,android.content.Context)>[[]]--><android.webkit.WebView: void <init>(android.content.Context)>[]--><android.webkit.WebView: android.webkit.WebViewClient getWebViewClient()>
```
You can add an if-then check like "If(Build.VERSION.SDK_INT >= 26)" when invoking this API to prevent compatibility issues.
 
2. <android.webkit.WebView: void setDataDirectorySuffix(java.lang.String)>：[28,30]
``` java
Error path: <com.ichi2.anki.servicelayer.DebugInfoService: java.lang.String getDebugInfo(android.content.Context,com.ichi2.utils.FunctionalInterfaces$Supplier)>[[]]--><com.ichi2.anki.servicelayer.DebugInfoService: java.lang.String getWebviewUserAgent(android.content.Context)>[[]]--><android.webkit.WebView: void <init>(android.content.Context)>[]--><android.webkit.WebView: void setDataDirectorySuffix(java.lang.String)>

Error path: <com.ichi2.anki.AbstractFlashcardViewer$MyWebView: void <init>(com.ichi2.anki.AbstractFlashcardViewer,android.content.Context)>[[]]--><android.webkit.WebView: void <init>(android.content.Context)>[]--><android.webkit.WebView: void setDataDirectorySuffix(java.lang.String)>
```
You can add an if-then check like "If(Build.VERSION.SDK_INT >= 28)" when invoking this API to prevent compatibility issues.

3.<android.content.Context: java.lang.Object getSystemService(java.lang.Class)>: [23,30]
``` java
Error path: <com.ichi2.compat.customtabs.KeepAliveService: void <init>()>[[]]--><android.content.Context: void <init>()>[]--><android.content.Context: java.lang.Object getSystemService(java.lang.Class)>

Error path: <com.ichi2.widget.AnkiDroidWidgetSmall$UpdateService: void <init>()>[[]]--><android.content.Context: void <init>()>[]--><android.content.Context: java.lang.Object getSystemService(java.lang.Class)>

Error path: <com.ichi2.anki.AnkiDroidApp: void <init>()>[[]]--><android.content.Context: void <init>()>[]--><android.content.Context: java.lang.Object getSystemService(java.lang.Class)>

```
You can add an if-then check like "If(Build.VERSION.SDK_INT >= 23)" when invoking this API to prevent compatibility issues.

4.<android.widget.TextView: void setImeHintLocales(android.os.LocaleList)>: [24,30]
``` java
Error path: <com.ichi2.preferences.IncrementerNumberRangePreference: void <init>(android.content.Context)>[[]]--><android.widget.TextView: void <init>(android.content.Context)>[]--><android.widget.TextView: void setImeHintLocales(android.os.LocaleList)>

Error path: <com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity: void recreateEditingUi(com.ichi2.anki.multimediacard.activity.MultimediaEditFieldActivity$ChangeUIRequest,android.os.Bundle)>[[]]--><com.ichi2.anki.multimediacard.fields.BasicControllerFactory: com.ichi2.anki.multimediacard.fields.IControllerFactory getInstance()>[[]]--><com.ichi2.anki.multimediacard.fields.BasicControllerFactory: void <init>()>[]--><com.ichi2.anki.multimediacard.fields.BasicControllerFactory: com.ichi2.anki.multimediacard.fields.IFieldController createControllerForField(com.ichi2.anki.multimediacard.fields.IField)>[[]]--><com.ichi2.anki.multimediacard.fields.BasicImageFieldController: void <init>()>[]--><com.ichi2.anki.multimediacard.fields.BasicImageFieldController: void createUI(android.content.Context,android.widget.LinearLayout)>[[]]--><android.widget.TextView: void <init>(android.content.Context)>[]--><android.widget.TextView: void setImeHintLocales(android.os.LocaleList)>

Error path: <com.ichi2.preferences.IncrementerNumberRangePreference: void <init>(android.content.Context,android.util.AttributeSet)>[[]]--><android.widget.TextView: void <init>(android.content.Context)>[]--><android.widget.TextView: void setImeHintLocales(android.os.LocaleList)>

Error path: <com.ichi2.anki.multimediacard.activity.LoadPronounciationActivity: void onCreate(android.os.Bundle)>[[]]--><android.widget.TextView: void <init>(android.content.Context)>[]--><android.widget.TextView: void setImeHintLocales(android.os.LocaleList)>

Error path: <com.ichi2.anki.multimediacard.activity.TranslationActivity: void onCreate(android.os.Bundle)>[[]]--><android.widget.TextView: void <init>(android.content.Context)>[]--><android.widget.TextView: void setImeHintLocales(android.os.LocaleList)>

```
You can add an if-then check like "If(Build.VERSION.SDK_INT >= 24)" when invoking this API to prevent compatibility issues.

**Comment by mikehardy** [comment]
@Valentin-ys please don't open issues based on automated analysis of source code, they are rarely correct. I've seen these sorts of issues opened before and they always appear to me to be the produce of academic toys and they don't survive a meeting with the real world.

I can tell you after checking the first thing you mentioned that we catch Throwable in that instance, so the usage is safe.

If you as a real person analyze these control flows and discover issues, open a new issue, but automated analysis issues in this repo or other repos just creates noise (and a bit of an unwanted adrenaline burst in the morning! I was afraid we had real problems).

**Comment by Valentin-ys** [comment]
We are extremely sorry to bother you in the morning, and we haven't analyzed the try-cath cases to prevent such compatibility issues in our 'academic toy' yet!  Thank you for pointing out the problem in a timely manner, and we will continue to improve our work to find real and reproducible bugs that really affect  the robustness of APPs, such as crashes or bad manner on some typical devices. Thanks a lot!

**Comment by mikehardy** [comment]
For the record, I am a huge fan of static analysis. But real humans have to drive things :-). Good luck.
