### ISSUE TITLE
[Bug] Apple Silicon test failures with x86_64 JDK on macOS

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#10403]
###### Reproduction Steps

1. clone Anki-Android repo
2. `./gradlew jacocoTestReport`

###### Expected Result

Clean run

###### Actual Result

```
com.ichi2.compat.DirectoryContentTest > ensure_absolute_path[21] FAILED
    java.lang.AssertionError: Paths should be canonical
    Expected: "/private/var/folders/tq/7kbhnvh9675drxzzyvpk0n840000gq/T/13587878100631967865/zero"
         but: was "/var/folders/tq/7kbhnvh9675drxzzyvpk0n840000gq/T/13587878100631967865/zero"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.ichi2.compat.DirectoryContentTest.ensure_absolute_path(DirectoryContentTest.kt:49)

com.ichi2.compat.DirectoryContentTest > ensure_absolute_path FAILED
    java.lang.AssertionError: Paths should be canonical
    Expected: "/private/var/folders/tq/7kbhnvh9675drxzzyvpk0n840000gq/T/8221483500880813673/zero"
         but: was "/var/folders/tq/7kbhnvh9675drxzzyvpk0n840000gq/T/8221483500880813673/zero"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at com.ichi2.compat.DirectoryContentTest.ensure_absolute_path(DirectoryContentTest.kt:49)
com.ichi2.async.CollectionTaskSearchCardsTest > searchCardsNumberOfResultCount FAILED
    Wanted but not invoked:
    taskListener.onProgressUpdate(
        <Capturing argument>
    );
    -> at com.ichi2.async.TaskListener.onProgressUpdate(TaskListener.kt:44)

    However, there was exactly 1 interaction with this mock:
    taskListener.onPreExecute();
    -> at com.ichi2.async.CollectionTask.onPreExecute(CollectionTask.java:208)
        at com.ichi2.async.TaskListener.onProgressUpdate(TaskListener.kt:44)
        at com.ichi2.async.CollectionTaskSearchCardsTest.searchCardsNumberOfResultCount(CollectionTaskSearchCardsTest.java:59)

```

Along with some other not-great-looking warnings that probably bear investigation but might be my local environment on my macOS M1 machine:
```

> Task :AnkiDroid:stripPlayDebugDebugSymbols
Unable to strip the following libraries, packaging them as they are: librsdroid.so.

> Task :AnkiDroid:dexBuilderPlayDebug
WARNING:/Users/mike/work/Ankidroid/Anki-Android/AnkiDroid/build/intermediates/jacoco_instrumented_classes/playDebug/out/com/ichi2/anki/DeckSpinnerSelection.class: D8: Invalid stack map table at 130: ifne L?, error: Source locals {0:Initialized(com.ichi2.anki.DeckSpinnerSelection),1:Initialized(long),3:Initialized(int),4:Initialized(boolean[]),5:Initialized(int),6:Initialized(int),7:Initialized(int),8:Initialized(int)} have different local indices than {0:Initialized(com.ichi2.anki.DeckSpinnerSelection),1:Initialized(long),3:Initialized(int),4:Initialized(boolean[]),5:Initialized(int),6:Initialized(int),7:Initialized(int),8:Initialized(int),9:top}.
```

@david-allison - worth noting that I was not able to reproduce the errors seen by @viciousAegis in https://github.com/ankidroid/Anki-Android/pull/10389#issuecomment-1051617588 though I did not try that specific command line yet, I just did a full run

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@Arthur-Milchior canonical path issues on an M1.

I've got an M1 on order, so I'll be able to debug this hopefully within the month.

I presume we have no Apple Silicon CI options?

**Comment by viciousAegis** [comment]
is the solution David suggested still relevant? https://github.com/ankidroid/Anki-Android/pull/10389#issuecomment-1052602567

I have my uni exams coming up, so I don't have a lot of time on hand :( . Regardless, If the above solution is still the way to go, I will start work on it ASAP, doing what David suggested in the comment.

**Comment by mikehardy** [comment]
There are no Apple Silicon CI options at present no. No reasonable ones at least, given our need for them is not really critical. Github Actions does not appear to have plans for M1 runners at present anyway.

@viciousAegis since I was not able to reproduce the issue, I would let it sit for now. I have low-priority plans to set up and start working on the Anki-Android-Backend and I have an M1 machine so if there's something to mop up there I can handle it

**Comment by Arthur-Milchior** [comment]
Nope. I don’t have m1

**Comment by david-allison** [comment]
@viciousAegis 

Uni takes priority. Always.

I'll be dealing with it this month. It's fine to run tests in CI on your GH repo for now.

**Comment by mikehardy** [comment]
I just tried this a moment ago in response to a comment on #10538 and I have the same results as above, some test failures but not total library load failures as @viciousAegis sees.

I think there is a problem here but I need to reproduce. I suspect my system is working because of something subtle to do with Rosetta2 or similar, perhaps I am using a JDK that is not arm64e so it's working?

```
[mike@yv ~]$ arch
arm64
[mike@yv ~]$ sysctl -in sysctl.proc_translated
0
[mike@yv ~]$ java -fullversion
openjdk full version "11.0.14.1+1"
[mike@yv ~]$ which java
/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java
```

I'm investigating the temurin JDK to see if that's it. @viciousAegis what JDK are you using?

**Comment by mikehardy** [comment]
That's it! temurin JDK is x86_64. So most tests work (well, except for the problems above) if you `brew tap homebrew/cask-versions` and `brew install --cask temurin11` then use that JDK.

Not ideal, we should run native and I will get to that, but a workaround is worth a lot.

**Comment by mikehardy** [comment]
Yeah, Temurin is definitely not arm64 native yet, so I'm "working" because of Rosetta2 translation, which is the workaround for the moment (Looks like Temurin11 will get arm64 around April according to Microsoft liasion with java community - https://github.com/adoptium/adoptium/issues/96#issuecomment-1055447874) - So we have 2 problems then:

1- M1 test runs fail for various reasons outlined above that look like trivial compatibility issues, this could be investigated by anyone and might be a good sub-issue ? (or just a PR)
2- M1 test runs *using arm64 JDKs* will fail until we have a cross-compile of the Anki-Backend, which is a slightly larger project - to test that someone will need to use temurin17 (we may not support JDK17 yet here?) or a native SDK of some other flavor (and Azul Zuzu appears to be the leader at the moment)

**Comment by mikehardy** [comment]
Okay I'm going to split this issue - I just reproduced my original failures here (pathing issues) in a regular x86_64 macOS environment.

The arm64 JDK thing I'm going to take over to Anki-Android-Backend as that's where it belongs.

**Comment by david-allison** [comment]
Backend issue: https://github.com/ankidroid/Anki-Android-Backend/issues/164
