### ISSUE TITLE
[Feature request] Filter valid import files

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10413]
**Is your feature request related to a problem? Please describe.**
When importing a file, all extensions seem like valid files

**Describe the solution you'd like**
The unvalid extensions to be greyed out/not selectable

**Additional context**
Probably feasible with [EXTRA_MIME_TYPES](https://developer.android.com/reference/android/content/Intent#EXTRA_MIME_TYPES) and [.colpkg and .apkg MIMES](https://github.com/ankidroid/Anki-Android/blob/05cdd6e6b3e539668a6950e36e8062208d8c1b55/AnkiDroid/src/main/AndroidManifest.xml#L152)

## Current
![Screenshot_20220301-104248_Files](https://user-images.githubusercontent.com/69634269/156179940-081e9c72-aa4f-4447-b318-859c2864d9e3.png)

## Expected
![Screenshot_20220301-104213_Files](https://user-images.githubusercontent.com/69634269/156179963-ee9c1f39-0f8b-41df-bbf9-ab3b6cccb20c.png)

**Comment by david-allison** [comment]
This is risky, but I'd like to see it if it's feasible.

**Comment by BrayanDSO** [comment]
> application/octet-stream is arbitrary binary data

When testing, this is the mime I got. Odd, but happened

**Comment by david-allison** [comment]
I'd expect `application/zip`, strange...

Just to elaborate: I'm happy for you to look into this, I'd like to get it resolved, but I can't guarantee I'd Approve the PR, it'd depend on how well documented the approach is.

The upside risk is a better file selection experience
The downside risk is that some users with unsupported phones may be unable to restore backups

**Comment by BrayanDSO** [comment]
Sure. The most important thing in this issue IMO is research about its behavior on different android versions/manufacters flavors. 

The implementation itself is quite simple and already works here.

I'll try to take a look into it later

**Comment by mikehardy** [comment]
I think it's too dangerous personally, we have unexpected file associations pop up here all the time, really device specific and version specific - I just think it's an intractable problem as you'll have to test every current and future device AnkiDroid runs on. Probably better to focus effort elsewhere

**Comment by BrayanDSO** [comment]
Maybe when Android gets some way to work with extensions instead of MIMEs this will be feasible
