### ISSUE TITLE
Uses constant in xml's key

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10423]
To be sure that we avoid typos (that would be hard to find during code review), ideally, xml keys should be a string constant and not directly a string literal. Currently it's only done in preferences_reviewing.xml with

```xml
     <ListPreference
            android:defaultValue="bottom"
            android:entries="@array/answer_buttons_position_labels"
            android:entryValues="@array/answer_buttons_position"
            android:key="@string/answer_buttons_position_preference"
            android:title="@string/answer_buttons_position" />
```
which uses the value from constant.xml
```xml
<string name="answer_buttons_position_preference" translatable="false">answerButtonPosition</string>
```

This allow in AbstractFlashCardViewer.java to uses `getString(R.string.answer_buttons_position_preference)`, hence using a constant instead of a literal.

I would love to get this same pattern everywhere.

Ideally, for ease of review, a commit should change a single literal to a constant. A PR can contain multiple commit or a single one.

You can search for keys that need to be changed with the regexp `android:key="[^@]`

**Comment by akarsh1263** [comment]
I'm on it

**Comment by Arthur-Milchior** [comment]
Thanks @akarsh1263 
You don't have to do all at once. Actually, it may be safer to do a single preference menu first, and ask for review, so that we can check whether what you do is the correct way before you spend time doing everything.

**Comment by david-allison** [comment]
> constant.xml

I'd prefer a `preferences.xml` here (same string values resource file, just with a different name)

**Comment by akarsh1263** [comment]
@david-allison 
I am facing some problem in creating a new preferences.xml under '10-preferences' folder. The new value resource file is created as a separate file directly under the 'values' folder instead of '10-preferences'. If there is some suggested advice, it would be very helpful, or I can simply use the 'constant.xml' file to use string constants

**Comment by david-allison** [comment]
> @david-allison 
> I am facing some problem in creating a new preferences.xml under '10-preferences' folder. The new value resource file is created as a separate file directly under the 'values' folder instead of '10-preferences'. If there is some suggested advice, it would be very helpful, or I can simply use the 'constant.xml' file to use string constants 

The keys are constants and aren't too be translated. A new "preferences.xml" file is perfect.

**Comment by Arthur-Milchior** [comment]
What is the issue you encouter? Do you get an error message, if so could you copy it?

**Comment by akarsh1263** [comment]
@david-allison 
@Arthur-Milchior 
I got it, thanks

**Comment by akarsh1263** [comment]
@Arthur-Milchior 
I have created a new preferences.xml and replaced the string literals with string constants in preferences_reviewing.xml, and comitted the changes. Is there anything else I have to do before you review it?

**Comment by Arthur-Milchior** [comment]
@akarsh1263 You don't have to worry about creating a PR. You can change PR if I ask for more work anyway. And it's easier for me to have an opinion if I see the actual result than if I have to guess whether we perfectly understood each other meaning.

So please, just go create the PR. In the worst case, I'll ask for changes.

**Comment by akarsh1263** [comment]
I'm getting some error while pushing (string_constants is my branch name):
 ! [remote rejected]     HEAD -> string_constants (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/lint.yml` without `workflow` scope)
error: failed to push some refs to 'https://github.com/akarsh1263/Anki-Android.git'

**Comment by david-allison** [comment]
> I'm getting some error while pushing (string_constants is my branch name): ! [remote rejected] HEAD -> string_constants (refusing to allow a Personal Access Token to create or update workflow `.github/workflows/lint.yml` without `workflow` scope) error: failed to push some refs to 'https://github.com/akarsh1263/Anki-Android.git'

You need more permissions on your PAT: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by oakkitten** [comment]
Why not use something along...

```kt
class PreferenceKeys(val resources: Resources) {
    val get(key: Int) = resources.getString(key)

    val answerButtonsPosition = getString(R.string.answer_buttons_position_preference)
}
```

Then instead of 

```kt
AnkiDroidApp.getSharedPrefs(this).getString(
    getString(R.string.answer_buttons_position_preference),
    "bottom"
)
```

You could say

```kt
AnkiDroidApp.getSharedPrefs(this).getString(
    preferenceKeys.answerButtonsPosition,
    "bottom"
)
```

I also have seen a few primitives that would allow doing something like:

```kt
class Reviewer {
    enum class AnswerButtonsPosition(override val res: Int) : EnumPreference.Values {
        Top(R.string.answer_buttons_position__top),
        Bottom(R.string.answer_buttons_position__bottom),
    }

    val answerButtonsPosition = EnumPreference(R.string.answer_buttons_position__key, 
            AnswerButtonsPosition.Bottom, AnswerButtonsPosition.values())
}

```

And then you can say simply 

```kt
if (prefs.reveiwer.answerButtonsPosition == AnswerButtonsPosition.Top) {...}
```
