### ISSUE TITLE
If I accidentally enter the wrong field in "Card Types", all cards will show up empty

### ISSUE THREAD

**Issue by sjl872964789** [ankidroid/Anki-Android#10431]
###### Reproduction Steps

1. Add some cards
2. Change their card types
3. An incorrect field is entered
4. When I studied the cards, I found the cards were empty

###### Expected Result

I should be prompted when I modify the field I entered

###### Actual Result

At the least, the cards should not appear empty

###### Video
![ezgif com-gif-maker](https://user-images.githubusercontent.com/15941953/156872532-75203bce-38eb-4c4f-8a6e-db46d45b2fa4.gif)

###### Debug info

AnkiDroid Version = 2.16alpha45
Android Version = 11
Manufacturer = OnePlus
Model = KB2000
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 11; KB2000 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Mobile Safari/537.36
ACRA UUID = fdd28bd9-b444-4d17-8736-d76574185b51
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi @sjl872964789, could you fill out the "debug info" section, especially the version number where this occurs?

**Comment by sjl872964789** [comment]
Sorry, I thought that only the crash error needed this information before, I have edited and added this information.

**Comment by BrayanDSO** [comment]
Funny behavior. The back side (default basic notetype) shows a better message when it have `{{FrontSide}}` on its template.

Although it shows the "empty cards" message, the cards aren't deleted when using the "empty cards" tool. 

Therefore it must be some lack of checking field names on template editing

![Screenshot_20220305-180036_AnkiDroid](https://user-images.githubusercontent.com/69634269/156899918-96bfeb41-4bf3-4312-bf8a-277707119c4f.png)

**Comment by WPum** [comment]
Currently, card empty checks are performed before the actual render process, which will fail because no field in the template matches the non-empty field in the card. ("Frot" does not match either "Front" or "Back")
I would like to fix this if possible, but I'm not sure what to do next.

**Comment by BrayanDSO** [comment]
The template editor is defined on `CardTemplateEditor.java`. The field names are listed at `mFieldNames`. When the user saves the edition, it should check if the front has no fields or one of the fields has a name not in `mFieldNames`. If it helps you, I guess upstream does it with `template.rs`

**Comment by WPum** [comment]
In the latest version of Anki desktop, it simply refuses to save problematic template.
May be a solution

**Comment by L-keeey** [comment]
Hi @david-allison , I would like to work on this issue.

**Comment by david-allison** [comment]
> Hi @david-allison , I would like to work on this issue.

Hi, it'd be good to engage in the discussion and come to a reasonable solution before coding.

After that, I'll happily assign it

**Comment by L-keeey** [comment]
In current version, when creating first card in a deck, the checking mechanism mentioned by @WPum would fail the generation if templates are wrong （like "frot" but not "front"). But when the card has been created, We could do the steps like @sjl872964789  did and the card type description could be saved with wrong template like "frot". And enter the deck would reproduce the bug. It seems like for a created card, the checker is not working on existed card or somehow blocked? May need to examine the checker.

**Comment by L-keeey** [comment]
Hi @david-allison , I have worked out by adding a regex check on modified fields and it seems work fine. But when running bundled test cases, they all failed due to "Can't find dependent libraries", which i literally don't know how to solve. Can i just commit my version? Or maybe you know how to fix this "library" problems? I'd appreciate your reply, thanks.

**Comment by L-keeey** [comment]
@david-allison Hi! Since I have already submitted a pull request for this issue, would you please assign this issue to me? Auto tests have passed but not merged yet.
