### ISSUE TITLE
[Feature request] Edit option on custom toolbar button dialog

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10436]
**Is your feature request related to a problem? Please describe.**
When long tapping a custom button added to the note editing toolbar, the only option shown is to delete the button. If someone wants to edit the letter or the html tags, their only option is to delete it and create another

**Describe the solution you'd like**
Add an option to edit the button on the dialog

**Additional context**
Current behavior

![Screenshot_20220305-173934_AnkiDroid](https://user-images.githubusercontent.com/69634269/156899416-a4d95bf5-932d-489a-af8c-d6389cc7c5fd.png)

**Comment by mikehardy** [comment]
sounds reasonable to me

**Comment by BishyanKar** [comment]
@mikehardy can I work on it?

**Comment by krmanik** [comment]
@BishyanKar 
Sure!
