### ISSUE TITLE
[Bug] "Search deck" button appears after synchronization

### ISSUE THREAD

**Issue by WPum** [ankidroid/Anki-Android#10445]
###### Reproduction Steps

1. Login to an AnkiWeb account
2. Do sync

###### Expected Result

"Search desk" button does not appear in the deck picker toolbar.

###### Actual Result

It appears.

### Before Sync

![before](https://user-images.githubusercontent.com/27683756/156931123-5b1e53ea-7c09-44bd-9f97-1fd36cefcd65.jpg)

### After Sync

![after](https://user-images.githubusercontent.com/27683756/156931127-aeb5f834-9645-4eeb-b53b-b75b965a2478.jpg)

###### Debug info
AnkiDroid Version = 2.16alpha48
Android Version = 9
Manufacturer = HUAWEI
Model = MHA-AL00
Hardware = hi3660
Webview User Agent = Mozilla/5.0 (Linux; Android 9; MHA-AL00 Build/HUAWEIMHA-AL00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.99 Mobile Safari/537.36
ACRA UUID = 59829251-4318-4acc-a9e2-a1824e9e735c
Scheduler = std
Crash Reports Enabled = false
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by sampath-houde** [comment]
Can I work on this issue?

**Comment by david-allison** [comment]
> Can I work on this issue?

Sure!

**Comment by SampathHoude** [comment]
Where can i get 2.16 alpha48 version apk @david-allison @WPum

**Comment by SampathHoude** [comment]
@david-allison can you explain it exaclty when the 'search desk' button should appear and when it shouldn't

**Comment by david-allison** [comment]
> Where can i get 2.16 alpha48 version apk @david-allison @WPum 

You'd be best to check out the git tag and build from source.

The alphas are also available on the releases page on GitHub

**Comment by david-allison** [comment]
> @david-allison can you explain it exaclty when the 'search desk' button should appear and when it shouldn't
> 

It should be shown if 10 or more decks are available:

https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L694-695

**Comment by sampath-houde** [comment]
to which branch I should raise a pr?

**Comment by david-allison** [comment]
> to which branch I should raise a pr? @david-allison 

Main

**Comment by sampath-houde** [comment]
Have created the PR
@david-allison

**Comment by mikehardy** [comment]
@sampath-houde if you include the issue number in the PR on the 'Fixes line' (like exactly this: `Fixes #10445`) then github will autolink them together and auto-close the issue when the PR is merged - it's a nice github feature

**Comment by winstoncooke** [comment]
I'm having the opposite problem where all items in the top right of the action bar (i.e. Search, Sync, and the 3 dot menu) disappear after a sync. Should that be a new issue?

**Comment by dorrin-sot** [comment]
Hi this was fixed in #11113 👀

**Comment by BrayanDSO** [comment]
I really appreciate your great fixes here, @dorrin-sot. As I am an avid AnkiDroid user, it's nice to get these things covered.
