### ISSUE TITLE
remove Compat.copyDirectory

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#10458]
I'd remove copy directory

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/10448#issuecomment-1062036211_

Also from @arthur-milchior
----
While you may be excused to assume that copyDirectory is some new code, it actually is code from Farjad and I don't expect we'll actually use it (@david-allison should we remove Compat.copyDirectory ?)

**Comment by inomag** [comment]
Hi @mikehardy, I would like to work on this issue.

**Comment by david-allison** [comment]
Sounds good to me!

**Comment by akarsh1263** [comment]
If no one is assigned currently, I can work on this. I just have to remove the copyDirectory function from the Compat interface right?

**Comment by david-allison** [comment]
yep

**Comment by akarsh1263** [comment]
The function is used in the moveDirectory function in CompatV21 class, so should I keep the function in CompatV21 without '@Override" sign and remove it just from the interface?

**Comment by david-allison** [comment]
remove all inheritors

**Comment by akarsh1263** [comment]
Ok, I'll remove moveDirectory function and any other inheritors

**Comment by david-allison** [comment]
It should only be used in tests. Remove those

**Comment by akarsh1263** [comment]
I have made the changes and committed. Should I push and make a PR?

**Comment by david-allison** [comment]
no need to ask! PRs welcome

**Comment by akarsh1263** [comment]
@david-allison 
I have made the PR. Please review it
