### ISSUE TITLE
Lag when reviewing cards on custom Android 12 ROM

### ISSUE THREAD

**Issue by grit780** [ankidroid/Anki-Android#10467]
###### Reproduction Steps

1. Hello 

I hope you are well.

I upgraded to a custom Android 12 ROM on my Samsung S10e. My phone is now much snappier and faster - however there is a huge lag when reviewing cards. When I click show answers, and then select again, hard, good or easy, there is no response for at least 5-10 seconds before going on to the next card. I tried disabling card hardware render in the settings, and that didn't fix the issue.

Really don't want to have to revert back to the stock ROM, as it's so much slower to use. Hoping there's something that can be done, or a fix I could implement?

Thanks for the great work,
Regards

I am currently using this ROM:

https://forum.xda-developers.com/t/rom-unofficial-12-galaxy-s10-e-5g-pixelextended-v4-2-aosp-encryption-lineageos-recovery-supported.4399589/

###### Debug info
AnkiDroid Version = 2.16alpha29

Android Version = 12

Manufacturer = Samsung

Model = Galaxy S10e

Hardware = exynos9820

Webview User Agent = Mozilla/5.0 (Linux; Android 12; Galaxy S10e Build/SQ1D.220205.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4758.101 Mobile Safari/537.36

ACRA UUID = 91bb39da-2e6f-4411-88b8-ab8aea9ab314

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Probably duplicate/related to #9941
