### ISSUE TITLE
Enable lint: `LogConditional`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10478]
We perform lint checking to ensure code correctness, but many of the system lint checks have not been enabled.

The goal of this issue is to enable the lint check: `LogConditional`

Line: https://github.com/ankidroid/Anki-Android/blob/6260cd6e25f67f331833bbd0981f2cda5a426dde/lint-release.xml#L224

To do this: 

* Change `ignore` to `fatal`
* Move the line in the XML to be somewhere near the top of the file (before the large block of `ignore` elements. 
  * The exact position is up to you, but if there's no comment associated with the check, a large nearly alphabetical block of `fatal` warnings seems sensible
* Run `gradlew lint` in the Android Studio terminal and fix the errors which occur.
  * `@Suppress(str)` (Kotlin) or `@SuppressWarnings(str)`  (Java) the warnings if they are valid.
    * Use your judgment, but aim to suppress as close to the error as possible (line/method) unless the class specifically has a reason why it will violate a lint check many times
  * If it was an error that we missed, fix it.
* Submit a Pull Request

**Comment by Prince-kushwaha** [comment]
@david-allison can i work on this issue

**Comment by david-allison** [comment]
Sure, thanks!

**Comment by Prince-kushwaha** [comment]
@david-allison can i do [Kotlin Conversion]  of IntentHandler.java or of some other java file

**Comment by david-allison** [comment]
Check to see what's not been done and feel free to do another one.

Check the `docs` folder for our process
