### ISSUE TITLE
open keyboard when rescheduling a card

### ISSUE THREAD

**Issue by tcaERROR-issues** [ankidroid/Anki-Android#10476]
**Is your feature request related to a problem? Please describe.**
Fairly clunkly since usually this action is hidden in hamburger menu, therefore you must, after showing answer, tap the open cards menu, hit reschedule, then make sure to hit in the gearbox to start typing . The default value isnt useful and there is no way of selecting any parameters without the keyboard. 

**Describe the solution you'd like**
Place cursor ready to go in prompt for how to long yo reschedule ,causing android to open the keyboars so you can quickly type a number of days and send that card away.

**Comment by david-allison** [comment]
Agreed. Relevant code: https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/RescheduleDialog.kt

**Comment by BrayanDSO** [comment]
Same behavior could be applied to some items in the deck options like `Steps`, `Ease`, etc

**Comment by oyeraghib** [comment]
Hey @david-allison can I work on this issue ?

**Comment by david-allison** [comment]
Sounds good to me

**Comment by oyeraghib** [comment]
@david-allison @tcaERROR-issues, guys isn't the keyboard already opening once we tap the reschedule option ? Is there any other issue here ?

Though I see keyboard not opening in deck options like **steps**, **ease** and I am working on it. But for the reschedule one please let me know!


https://user-images.githubusercontent.com/40427461/158472518-cdaad12e-9a72-4ed3-a46f-16d6459cdbba.mp4

**Comment by david-allison** [comment]
Doesn't happen for me. alpha50

**Comment by oyeraghib** [comment]
here working fine for me in alpha50

https://user-images.githubusercontent.com/40427461/158485889-e2e47a98-7baf-4fe0-ab57-a16c48ea27a7.mp4

**Comment by tcaERROR-issues** [comment]
Im on latest F-Droid version 2.15.6 - does that lag a lot?

On March 16, 2022 9:30:00 AM GMT+10:30, Mohd Raghib ***@***.***> wrote:
>here working fine for me in alpha50
>
>https://user-images.githubusercontent.com/40427461/158485889-e2e47a98-7baf-4fe0-ab57-a16c48ea27a7.mp4
>
>
>

-- 
I have deleted Facebook. Please remain in contact with me @JoshuM Wire and Telegram, 0 (0421373152 on Signal & Telegram — from greatest to least reliable — and mobile] ) or here, ***@***.***
Sent from my mobile device with K-9 Mail; please excuse my brevity.

**Comment by oyeraghib** [comment]
@BrayanDSO do you have any idea what dialog file is being used by deck options like `steps`, `ease` etc

**Comment by BrayanDSO** [comment]
#10593 was merged. This issue can be closed now

**Comment by mikehardy** [comment]
Hey @tcaERROR-issues for the moment all our public distribution channels are lagging a lot, yes, because we need to finish #5304 before we can start releasing publicly again. Until then you can get the latest 2.16alphas here https://github.com/ankidroid/Anki-Android/releases/ and you'll see this working when I do the next release (will be 2.16alpha54 and should be on Sunday or so)

**Comment by oyeraghib** [comment]
@mikehardy , @tcaERROR-issues we can close this issue as it have been resolved now.

**Comment by mikehardy** [comment]
Indeed, the issue was not cross-linked correctly per-template in related PR. Fixed PR description to cross-link, closing this. Thanks!
