### ISSUE TITLE
Add javascript formatting check via prettier to lint.yml 

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#10475]
For javascript (now that I'm much much better at it then when I started helping on AnkiDroid!), we should really have a .prettierrc and integrate a prettier check in our lint run, against our javascript.
Even if we don't require a full development toolchain for javascript for contributors (not something I recommend), it's easy to use the github setup-node action then do an `npx prettier` run on the files as part of the lint.yml workflow definition

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/10462#issuecomment-1065042582_

**Comment by mikehardy** [comment]
This would be a good issue for anyone that want's DevOps experience

In order for `npx` to appear as a command in your path you must have nodejs installed, it may be there already. setup-node is the action to use in the workflow. I use https://github.com/nvm-sh/nvm#installing-and-updating

Prettier requires a .prettierrc file like so https://github.com/invertase/notifee/blob/main/.prettierrc

`npx`, in order to run without prompt / non-interactive requires a special command line like `npm_config_yes=true npx <command to run> <arguments>`

**Comment by tharun634** [comment]
Hey, can I work on this?

**Comment by david-allison** [comment]
Sounds good to me
