### ISSUE TITLE
Add lint to ignore translation when all strings inside resources file set translatable to false

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#10483]
Should we consider following link for current xml file instead of repeated `translatable="false"`?
https://stackoverflow.com/a/53206467/13986833

_Originally posted by @krmanik in https://github.com/ankidroid/Anki-Android/pull/10450#discussion_r823389562_

**Comment by david-allison** [comment]
What's the problem currently? We only use `translatable="false"` 3 times

**Comment by krmanik** [comment]
I missed it. I haven't checked.
