### ISSUE TITLE
[Bug]Incomplete display of statistical charts

### ISSUE THREAD

**Issue by gugutu** [ankidroid/Anki-Android#10518]
###### Reproduction Steps
1. Turn on advanced statistics
2. Go to statistical chart
###### Expected Result
![1647172287780](https://user-images.githubusercontent.com/59798823/158058110-6e384fdc-f95d-40ee-ae80-bab4f06cdc85.jpg)
###### Actual Result
![1647172287795](https://user-images.githubusercontent.com/59798823/158058119-f52382dc-1b7e-4a25-af38-e26a4d2a27d0.jpg)
###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by gugutu** [comment]
This problem exists in versions above 2.16 alpha 36

**Comment by gugutu** [comment]
###### Debug info
AnkiDroid Version = 2.16alpha50

Android Version = 11

Manufacturer = Xiaomi

Model = M2006J10C

Hardware = mt6885

Webview User Agent = Mozilla/5.0 (Linux; Android 11; M2006J10C Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.85 Mobile Safari/537.36

ACRA UUID = 1381d01c-f576-4626-98b2-a5b32b428299

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by david-allison** [comment]
Thanks! Was reported in Discord a few days ago. Expected fallout from the Kotlin Migration

**Comment by Prince-kushwaha** [comment]
@david-allison can i work on this issue

**Comment by david-allison** [comment]
Sure

**Comment by Prince-kushwaha** [comment]
@david-allison yes your are right this issue is due to Kotlin Migration of `ChartBuilder.kt` when i replace code of  `ChartBuilder.kt` with 2.15 release -:`ChartBuilder.java` code  then this issue is fix

**Comment by Prince-kushwaha** [comment]
@david-allison can i replace code `ChartBuilder.kt` with 2.15 release -:`ChartBuilder.java` code ?

**Comment by david-allison** [comment]
We should fix the Kotlin instead.

**Comment by Prince-kushwaha** [comment]
@mikehardy  @david-allison when i commit my change i get below issue how i fix it?
<img width="536" alt="Screenshot 2022-03-16 114313" src="https://user-images.githubusercontent.com/65972015/158527900-8ca5122b-33c6-4e52-abb2-8657e5146033.png">

**Comment by mikehardy** [comment]
Hmmm the new JavaScript linter may not have been verified on a windows system, I'll check first thing this morning after some coffee. This looks unrelated to any changes you've made, it's from a different pr

**Comment by mikehardy** [comment]
@Prince-kushwaha - I cannot reproduce this. It works fine on my local windows test environment. So we'll need more info than just an error message and a question on how to fix. You'll have to get curious, and dig in. https://stackoverflow.com/help/how-to-ask

In particular, what is your local environment? We'll need instructions to reproduce in the form of an exact sequence of commands / UI actions to take, from a clean system, that results in this https://stackoverflow.com/help/minimal-reproducible-example

For example:
- I used the shell cmd.exe on a Windows 10 system (fully updated as of today)
- I used git 2.34.1.windows.1 in my cmd.exe path and did `git clone git@github.com:ankidroid/Anki-Android` into a temp directory
- I have npx version 8.1.2 on my path
- in the fresh Anki-Android directory I ran `npx --yes prettier --ignore-unknown --write AnkiDroid/**/*.js` (the same command as is in the pre-commit hook) and it ran
- I made a trivial change to a file and ran `git commit -a` and it succeeded

So I am not sure how to trigger this. With more details I might be able to fix it, or if you do some filesystem inspection and check the commands in "pre-commit" yourself manually it might turn up the problem then you could perhaps fix it

**Comment by mikehardy** [comment]
I peeled this off to a separate issue.
Prettier / windows errors should not clutter up an issue related to statistical charts.
I'm going to minimize all the related comments but please do expand them if you are curious
