### ISSUE TITLE
Kotlin Cleanup: integerListToArray

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10530]
This issue is open for contribution after https://github.com/ankidroid/Anki-Android/pull/10527 is merged.

Replace usages of `integerListToArray` with the Kotlin method: `.toIntArray()`. Remove the method when done.

**Comment by divyansh-dxn** [comment]
I can work on it.

**Comment by jals413** [comment]
I would like to work on it :)

**Comment by suman-somu** [comment]
@jals413 are you doing it ?

**Comment by david-allison** [comment]
#10527 isn't merged, so this isn't open to being worked on yet.

**Comment by jals413** [comment]
> @jals413 are you doing it ?

yes i will work on this issue

**Comment by sharmaaadish** [comment]
please assign this to me

**Comment by david-allison** [comment]
> please assign this to me

There's already a pull request in for this one, best to find an unassigned issue, or one that's been dormant for at least a month.

**Comment by jals413** [comment]
I am really sorry , I wont be able to work on this issue for as I am busy with my personal as well as college work so please unassign me and assign someone else to go on further
