### ISSUE TITLE
new prettier check in pre-commit may fail ?

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#10549]
@mikehardy  @david-allison when i commit my change i get below issue how i fix it?
<img width="536" alt="Screenshot 2022-03-16 114313" src="https://user-images.githubusercontent.com/65972015/158527900-8ca5122b-33c6-4e52-abb2-8657e5146033.png">

_Originally posted by @Prince-kushwaha in https://github.com/ankidroid/Anki-Android/issues/10518#issuecomment-1068776452_

If anyone is thinking of working on this, you must be developing on a windows machine, it's a windows-specific issue

**Comment by mikehardy** [comment]
I am unable to reproduce this on my windows test machine, asked @Prince-kushwaha for more information but I'd like to track it as a separate issue here.

**Comment by mikehardy** [comment]
My reproduction test (which succeeded):

- I used the shell cmd.exe on a Windows 10 system (fully updated as of today)
- I used git 2.34.1.windows.1 in my cmd.exe path and did git clone git@github.com:ankidroid/Anki-Android into a temp directory
- I have npx version 8.1.2 on my path
- in the fresh Anki-Android directory I ran npx --yes prettier --ignore-unknown --write AnkiDroid/**/*.js (the same command as is in the pre-commit hook) and it ran
- I made a trivial change to a file and ran git commit -a and it succeeded

**Comment by Prince-kushwaha** [comment]
i used window 11 system
i used git git version 2.35.1.windows.2
i have npx version 6.14.6 
when  I ran `npx --yes prettier --ignore-unknown --write AnkiDroid/**/*.js` i get below issue
<img width="728" alt="Screenshot 2022-03-16 221829" src="https://user-images.githubusercontent.com/65972015/158643731-d0f74617-3d32-4f25-9c64-1dc9b7a5613e.png">
And when i commit the change i get below issue 
<img width="632" alt="Screenshot 2022-03-16 221659" src="https://user-images.githubusercontent.com/65972015/158643892-2f559e5b-d438-4165-864e-df084cdf8115.png">



`

**Comment by david-allison** [comment]
What happens if you run under powershell?

**Comment by mikehardy** [comment]
You don't need prettier installed, "npx --yes" says "Hey npx, go download prettier from npmjs.com - and --yes I accept the risk of running code from the internet  - and run it". So we don't need prettier installed.

It would be easier if you pasted text instead of images, when the images are just of text.

So you have shown that error a few times. Is the directory actually there? What happens when you go `dir c:\users\PRINCE\AndroidStudioProjects\Anki-Android\AnkiDroid\` (which I could have just pasted from your error message but it was an image so hopefully I typed that out correctly...)

**Comment by mikehardy** [comment]
Second the thought that mingw is messing things up. Definitely try it in cmd.exe or powershell. If it continues to be a problem perhaps we can try to detect + warn people running unsupported shells, but I am going to guess that is the root cause

**Comment by Prince-kushwaha** [comment]
when i try to run it cmd or powershell i get same issue
Running Ktlint over these files:
AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
Completed ./gradlew ktlintFormat run.
ENOENT: no such file or directory, stat 'C:\Users\PRINCE\AndroidStudioProjects\Anki-Android\AnkiDroid\**\*.js'

**Comment by Prince-kushwaha** [comment]
> C:\Users\PRINCE\AndroidStudioProjects\Anki-Android>gradlew ktlintFormat run

FAILURE: Build failed with an exception.

* What went wrong:
Task 'run' is ambiguous in root project 'Anki-Android'. Candidates are: 'runKtlintCheckOverAmazonDebugSourceSet', 'runKtlintCheckOverAmazonReleaseSource
Set', 'runKtlintCheckOverAmazonSourceSet', 'runKtlintCheckOverAndroidTestAmazonDebugSourceSet', 'runKtlintCheckOverAndroidTestAmazonSourceSet', 'runKtli
ntCheckOverAndroidTestDebugSourceSet', 'runKtlintCheckOverAndroidTestPlayDebugSourceSet', 'runKtlintCheckOverAndroidTestPlaySourceSet', 'runKtlintCheckO
verAndroidTestReleaseSourceSet', 'runKtlintCheckOverAndroidTestSourceSet', 'runKtlintCheckOverDebugSourceSet', 'runKtlintCheckOverKotlinScripts', 'runKt
lintCheckOverMainSourceSet', 'runKtlintCheckOverPlayDebugSourceSet', 'runKtlintCheckOverPlayReleaseSourceSet', 'runKtlintCheckOverPlaySourceSet', 'runKt
lintCheckOverReleaseSourceSet', 'runKtlintCheckOverTestAmazonDebugSourceSet', 'runKtlintCheckOverTestAmazonReleaseSourceSet', 'runKtlintCheckOverTestAma
zonSourceSet', 'runKtlintCheckOverTestDebugSourceSet', 'runKtlintCheckOverTestFixturesAmazonSourceSet', 'runKtlintCheckOverTestFixturesDebugSourceSet',
'runKtlintCheckOverTestFixturesPlaySourceSet', 'runKtlintCheckOverTestFixturesReleaseSourceSet', 'runKtlintCheckOverTestFixturesSourceSet', 'runKtlintCh
eckOverTestPlayDebugSourceSet', 'runKtlintCheckOverTestPlayReleaseSourceSet', 'runKtlintCheckOverTestPlaySourceSet', 'runKtlintCheckOverTestReleaseSourc
eSet', 'runKtlintCheckOverTestSourceSet', 'runKtlintFormatOverAmazonDebugSourceSet', 'runKtlintFormatOverAmazonReleaseSourceSet', 'runKtlintFormatOverAm
azonSourceSet', 'runKtlintFormatOverAndroidTestAmazonDebugSourceSet', 'runKtlintFormatOverAndroidTestAmazonSourceSet', 'runKtlintFormatOverAndroidTestDe
bugSourceSet', 'runKtlintFormatOverAndroidTestPlayDebugSourceSet', 'runKtlintFormatOverAndroidTestPlaySourceSet', 'runKtlintFormatOverAndroidTestRelease
SourceSet', 'runKtlintFormatOverAndroidTestSourceSet', 'runKtlintFormatOverDebugSourceSet', 'runKtlintFormatOverKotlinScripts', 'runKtlintFormatOverMain
SourceSet', 'runKtlintFormatOverPlayDebugSourceSet', 'runKtlintFormatOverPlayReleaseSourceSet', 'runKtlintFormatOverPlaySourceSet', 'runKtlintFormatOver
ReleaseSourceSet', 'runKtlintFormatOverTestAmazonDebugSourceSet', 'runKtlintFormatOverTestAmazonReleaseSourceSet', 'runKtlintFormatOverTestAmazonSourceS
et', 'runKtlintFormatOverTestDebugSourceSet', 'runKtlintFormatOverTestFixturesAmazonSourceSet', 'runKtlintFormatOverTestFixturesDebugSourceSet', 'runKtl
intFormatOverTestFixturesPlaySourceSet', 'runKtlintFormatOverTestFixturesReleaseSourceSet', 'runKtlintFormatOverTestFixturesSourceSet', 'runKtlintFormat
OverTestPlayDebugSourceSet', 'runKtlintFormatOverTestPlayReleaseSourceSet', 'runKtlintFormatOverTestPlaySourceSet', 'runKtlintFormatOverTestReleaseSourc
eSet', 'runKtlintFormatOverTestSourceSet'.

**Comment by Prince-kushwaha** [comment]
@mikehardy how i update my pull request  or create pull request for issue without commit the change

**Comment by Prince-kushwaha** [comment]
->when i forked this project in different githhub account and clone it on my local system 
->then i commit some change it successfull commited

**Comment by Prince-kushwaha** [comment]
@mikehardy @david-allison i figure out how reproduce this issue 

-> create an branch which is fully update to upstream/main
->made some kotlin change then run it on the android emulator or any Device  
-> after runing on device commit the change then you get below  error
`	Running Ktlint over these files:
				AnkiDroid/src/main/java/com/ichi2/anki/stats/ChartBuilder.kt
				Completed ./gradlew ktlintFormat run.
				ENOENT: no such file or directory, stat 'C:\Users\PRINCE\AndroidStudioProjects\Anki-Android2\AnkiDroid\**\*.js'`

**Comment by Prince-kushwaha** [comment]
@ShridharGoel can help me to solve this issue

**Comment by krmanik** [comment]
I am getting same error in Powershell and Git Bash.
![image](https://user-images.githubusercontent.com/12841290/159114368-c4aa4428-484a-4134-abd0-da66d3a25a6f.png)

**Comment by krmanik** [comment]
Okay, I managed to get it works using WSL

![image](https://user-images.githubusercontent.com/12841290/159115997-983678e6-8faa-4a20-b681-4d8cdba02bce.png)

**Comment by oyeraghib** [comment]
getting the same error can't commit anything

**Comment by mikehardy** [comment]
Yep - that's a valid workaround until we get to the bottom of this. @oyeraghib you specify "I have the same error" but a "metoo" report like that is not that useful without knowing the details of your environment to see what's in common / what is not, what you tried https://stackoverflow.com/help/how-to-ask / https://stackoverflow.com/help/minimal-reproducible-example

**Comment by krmanik** [comment]
I think I have found the solution. The `--yes` in command causing the problem. But the `--yes` is documented on https://docs.npmjs.com/cli/v8/commands/npx#description

**PowerShell.**
Command with `--yes`
![image](https://user-images.githubusercontent.com/12841290/164362207-25f9821e-bd0a-4bdf-8f39-387fd778702e.png)

Command without `--yes`
![image](https://user-images.githubusercontent.com/12841290/164362239-689aa4b3-9290-4017-83ff-313ae442dc15.png)

**Git Bash.**
Command with `--yes`
![image](https://user-images.githubusercontent.com/12841290/164362274-f2dc1626-daa1-4aab-844e-29d08250e7a4.png)

Command without `--yes`
![image](https://user-images.githubusercontent.com/12841290/164362309-2e73729a-7162-485e-9b75-f171e5eef84b.png)

**Comment by david-allison** [comment]
@Prince-kushwaha @oyeraghib Does the above solve the issue for you?

**Comment by oyeraghib** [comment]
> @Prince-kushwaha @oyeraghib Does the above solve the issue for you?

Yes it worked 👍, thanks to @krmanik

**Comment by mikehardy** [comment]
That should do it and explains why some reproduced some did not. The npm install check command line argument is semi-recent, just a few months
