### ISSUE TITLE
Translated xml files: link documentation to reduce invalid edits

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10557]
* New users don't read the documentation on handling translations
  * Therefore they edit `values-NN` rather than `values`
* We should update the header of the files to:
  * link to the documentation, 
  * State that the file is auto-generated
  * State that only the "root" xml should be edited for the primary copy
  * That CrowdIn should be used to update translations

The header can be updated in: 

https://github.com/ankidroid/Anki-Android/blob/b02551b537c5d168380931a95ab99373a9755778/tools/update-localizations.py#L63

file: https://github.com/ankidroid/Anki-Android/blob/main/tools/update-localizations.py

**Comment by Tinkidinki** [comment]
@david-allison, I would like to take up this issue.

**Comment by david-allison** [comment]
Sure!

**Comment by david-allison** [comment]
Fixed in  #10566
