### ISSUE TITLE
Automate Kotlin Migration

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10573]
Kotlin migration has some repetitive part. Creating git commits, changing one line, changing it back, creating a second commit and so on. See https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md for details.

There is two ways - at least - to solve this issue. The best one and the easy one. I'll start with the easy one, which I believe to be a good first issue, but requires you to be able to write some shell script (which is relatively unusual here, but I suspect some contributors already did some). I'll then follow by a more complex task but that may be even easier to use. If we find someone who already know Intelli-J plug-in, or who want to learn how to create them, it will be wonderful. Otherwise, it may not be worth you time to do this second method, as it may cost you more time than it will save us (assuming the first method is implemented)

Since it's not production code, I'll be fine if you only do manual test and no automated test.

I don't know if windows developer can run shell script or if two versions are required. 

# Shell method

## First step: cleaning for a given file

Let's assume you have a file `f.java` you converted to `f.kotlin`. I want a script `convert_clean.sh` that, when you call `convert_clean.sh f` create a PR such as https://github.com/ankidroid/Anki-Android/pull/10611, as explained on  https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md . That is, it will do everything we asked contributors to do, but it will automate it instead of requiring to be done manually.

This mean that instead of doing all of those manual change, when a contributor is done with the conversion, they can run your script before pushing the PR.

## Second step: finding the file converted

Let's create a second script `converted.sh` that print the name of `f`. This means that it checks in your last commit/head and see what was modified and figure out the name of the converted file.

Then change `convert_clean.sh` so that, when it does not receive an argument, it calls `converted.sh` to obtain the name of the converted file. This way, the contributor won't even have to copy paste the file path.

## Third step: automate it in git hooks

Assuming that `converted.sh` is quick, then we can run it on git commit hook. If it finds a converted file, then it calls `convert_clean.sh`, otherwise it just process the commit as usual.  This ensure that this cleaning is done automatically when a conversion is done and there is no extra works for the contributors at all.

# Plug-in case

The best option, but it seems pretty hard, is to have the script also trigger the conversion. The issue is that, as far as I see when searching on the web, the conversion tool only run from intelli-J; there is no way to call it from command line directly. I expect that an android-studio plug-in maybe able to solve it; but it's not clear to me whether a plug-in can actually call existing IntelliJ's action.

## What if plug-in option is not possible?

If the other maintainers agree, I would consider this task to also be a success if you do the research, are convinced that the second task is impossible to do, and explain us what research you did and why you reached this conclusion. I.e. I'd be fine using Open Collective for the time you spent explaining why this idea can't succeed.
Plus, if there is some changes, or some idea that were not explored and other people have, then they can suggest new search area without having to waste time with search you already did

**Comment by justdvnsh** [comment]
Hi @Arthur-Milchior I am a new contributor to Anki. Though I am an experienced developer, I am still pretty new to this repo. 
From what I can understand, 

For the first point ->

1. Can We get access to the currently selected file ? 
    Ans. Yes. We can. Further details can be found at [https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010738880-How-to-get-the-selected-folder-or-file-path-in-project-view-from-a-tool-window-plugin-](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360010738880-How-to-get-the-selected-folder-or-file-path-in-project-view-from-a-tool-window-plugin-) 

2. Can Windows developers run shell script ?
    Ans. Yes, they can. But they would need to install WSL (Window Subsystem for Linux) on their machines.

4. Can we Call existing Intelli-J actions from plugin ? 
    Ans. Yes, we can. Infact there already exists such a plugin which can apply ```Convert Java to Kotlin``` action on multiple files. Further details can be found at [https://plugins.jetbrains.com/plugin/12183-multiple-file-kotlin-converter](https://plugins.jetbrains.com/plugin/12183-multiple-file-kotlin-converter)

__My Opinion__
Yes, I believe creating our own Android Studio plugin can solve the problem. 

I have mentioned everything I could, based on what I understood from the problem statement. Can you point out, if I missed something, or didn't get the problem correctly ? 😅

If everything seems to make sense, then I would love to work on this issue as well.

**Comment by Arthur-Milchior** [comment]
Welcome @justdvnsh.
Did you read our wiki pages I listed?
Because point 3 does not satisfy our need. Quite the contrary, we want each PR to convert a single file. Admittedly, sometime, converting a file will lead to change other files. For example a static method will become an object companion's method, and are not accessed the same way from Java if I recall correctly. But those are minimal changes that are also really easy to review.

What I want is to obtain a PR, similar to https://github.com/ankidroid/Anki-Android/pull/10611 , but with even less amount of manual work. And I don't feel like part 3 of the issue would allow to create such a PR.

Also, I was not able to find, after a quick search, how a plug-in can use already existing intelli-J action. I suppose they can, but that was one thing that made me wonder whether it was possible or not. If you state it's possible, wonderful. If it is not possible, it would still be possible to do the action manually and run a script that change split the commit (I'll edit my issue to describe my new idea)

Please don't hesitate to ping me on discord if you want us to discuss it quicker, or even plan a quick vocal chat. I really wish this PR to be done asap as it'll save a lot of time, so I'd be willing to take the time to discuss more.

By the way, are you here for GSoC?

**Comment by justdvnsh** [comment]
@Arthur-Milchior Yes I did read the wiki pages you listed. For the point 3, I know that, that plugin is not satisfactory for our need. I just mentioned it for reference,  that we can actually call IntelliJ's actions using a plugin. For our use case, we'll most probably need our very own plugin. 

yeah, sure I'll ping you on Discord for further discussions. 

Actually, I wasn't here for GSoC. I have been a past user of Anki and wanted to contribute to the code base. I was planning to participate in GSoC this year, but with some other organisation. Infact, I didn't even knew, that Anki is participating in GSoC. Nevertheless, I was browsing the organisations this on the GSoC website, and happened to find out Anki. 

But since, it is, I want to participate in GSoC with Anki itself, specifically for the Notification Subsytem and Converting Async task to Coroutines projects.

**Comment by Arthur-Milchior** [comment]
Wonderful, thanks for the clarification.
I feel the urge to clarify that AnkiDroid is participating to GSoC. Sadly, Anki declined our offer to participate. Paradoxically, there are less contributors to upstream than to AnkiDroid as far as I know.

I'm looking forward seeing your PR, or you clarification if any is needed, as you'll solve a developer's real painpoint if you succeed!

**Comment by Arthur-Milchior** [comment]
@justdvnsh are you still working on it?

**Comment by justdvnsh** [comment]
@Arthur-Milchior yes. Yes. I am. Actually, couldn't give this issue time due to the proposals. 

I'll complete it once i am done with my proposals are ready

**Comment by Arthur-Milchior** [comment]
I added a bash version on https://github.com/ankidroid/Anki-Android/pull/10779

So much time is spent manually repeating this word, while bash don't even take an hour to write, so I preferred to do it now. The intelliJ add-on would still be nice however
