### ISSUE TITLE
index.d.ts file for typescript type information of JS API

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#10585]
Create an `index.d.ts` file provide typescript type information about JS API implemented in `JavaScriptInterface` and `card.js`, and make a comment in card.js / correct area of Java implementation noting that developers should keep it up to date when they add/change things

**Comment by justdvnsh** [comment]
hi @krmanik I'd like to work on this. Can you please further elaborate on this ?

**Comment by krmanik** [comment]
HI @justdvnsh, 
It needs to create a `index.d.ts` file for the JS interface and functions implemented here.
https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/assets/scripts/card.js

The file mainly contains function name and parameters type but not body of the function. The process is automated in case of JS file when available. So for `card.js` file can be type information can be automated but for JS Interface I didn't find any automated solution. 
So may be the file manually created or a `index.js` with function definitions can be created then index.d.ts file generated.

To know more about how the JS API works inside, HTML debug can be used.
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection
https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

The implementation process may be different from my suggestion.

Resources
https://www.typescriptlang.org/docs/handbook/declaration-files/dts-from-js.html
https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html
https://stackoverflow.com/questions/51516394/what-is-the-main-usage-of-index-d-ts-in-typescript
