### ISSUE TITLE
[Bug] The language of the string of "Card info" screen top bar isn't changed by AnkiDroid settings

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10591]
Thank you always, developers. 
Let me inform you of a minor bug on `Card info` screen.
 
###### Reproduction Steps

1. `Settings`->`AnkiDroid: General settings`->`Language`
2. Select a language other than the system language on the device. 

      (For example, if the system language is `English`, you can select `Deutsch` on AnkiDroid settings.)

3. (Take a brief look and confirm that the selected language is applied as a whole.)
4. Show `Card info` of a card.

 

###### Expected Result
   The string on the top bar is written in the selected language (`Deutsch`, in the above example) as other strings on AnkiDroid are done so.

###### Actual Result
The string on the top bar is written in the system language  (`English`, in the above example) in contrast to other strings, which are written in the selected language  (`Deutsch`, in the above example).

![Screenshot_2022-03-20-18-32-23-14_a9eef3a2a561b80d5c76daebd0f9a14c](https://user-images.githubusercontent.com/10436072/159156508-b411d277-1e58-49a3-a2aa-e6dc25b3fcf7.png)

###### Video

https://user-images.githubusercontent.com/10436072/159156680-9d0eef88-ab68-4193-840b-949c11f19bae.mp4

###### Supplement
The result of the reverse case of the above sample is as follows. In this case, the system default is `Deutsch`, and the selected language on AnkiDroid settings is `English`.
![cardinfo title d](https://user-images.githubusercontent.com/10436072/159156174-082d8b37-b666-4d28-b6db-2911f1ab61ff.png)

###### Debug info
```
AnkiDroid Version = 2.16alpha52

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.58 Mobile Safari/537.36

ACRA UUID = 3b6235a2-041c-45f0-a6d1-782c54c43431

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Sorry for the delay - I swear I put in a PR

**Comment by snowtimeglass** [comment]
@david-allison, thank you for the fix! Take your time :-)
