### ISSUE TITLE
make "press back again to exit" optional

### ISSUE THREAD

**Issue by bstephen1** [ankidroid/Anki-Android#10618]
**Is your feature request related to a problem? Please describe.**
An update changed the behavior of the back button on the main screen so it now has to be pressed twice to exit the app instead of once. 

**Describe the solution you'd like**
Make this an optional toggle in the settings.

**Comment by mikehardy** [comment]
Hi there! I believe it is optional and is default to off? https://github.com/ankidroid/Anki-Android/pull/9216 - check advanced settings?

**Comment by bstephen1** [comment]
I checked through all the settings but didn't see any option to turn it off. It was introduced in v 2.15.0. I've been running an older version to avoid it but the older version is no longer able to sync to anki web. 

I found it listed in the [reddit changelog](https://www.reddit.com/r/Anki/comments/nkct2f/ankidroid_2150_changelog/) as "[General] Add confirmation when back button pressed from Deck Picker", but I can't find the related merge in the github changelog since there are hundreds and they have different titles.

**Comment by bstephen1** [comment]
Oh I see why I don't see that option -- it's in the alpha build for v2.16. I'll try signing up for the alpha testing.

**Comment by mikehardy** [comment]
Hey @bstephen1 - I linked the PR, it has a commit reference in it where the merge happened: https://github.com/ankidroid/Anki-Android/commit/897f932b6f673327497246894dd2362d1917d287 that commit ref indicates it was first available in 2.16alpha5

I suggest you try the new releases then - https://github.com/ankidroid/Anki-Android/releases/ - yes they are alphas so there *may* be something wrong with them but all the devs use them as daily use installations and we have pretty thorough automated testing on all changes too. So it is not risk-free but also not as dangerous as it sounds. I'm not aware of any issues currently, at least.

**Comment by mikehardy** [comment]
We're blocked by google currently on releasing through any official google channels because we need to finish our scoped storage migration (#5304 - it's an epic-sized job) so you won't get fresh alphas there and it also explains why we're on something like 2.16alpha56 instead of a steady public series of 2.17, 2.18 etc

**Comment by bstephen1** [comment]
Ah gotcha -- yup that fixes it. Thanks for the explanation! I'll close this.
