### ISSUE TITLE
[Bug] Model browser activity does not follow AnkiDroid language

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10623]
###### Reproduction Steps

1. Tap topbar three dots
2. Tap `Manage note types`

###### Expected Result

Top bar is on AnkiDroid language

###### Actual Result

Top bar is on system language

![Screenshot_20220325-102755_AnkiDroid](https://user-images.githubusercontent.com/69634269/160131343-a59c0f0c-061e-4bce-a4ad-0a0005f2f21e.png)

###### Debug info
```
AnkiDroid Version = 2.16alpha53

Android Version = 11

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-N770F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = 037bbc86-38a4-4ad7-9c42-05870e9b6086

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
These are actually data stored in the collection, and they are translated, but they are created on first app open and that's that, there is no way to translate them afterward

**Comment by BrayanDSO** [comment]
@mikehardy See `Gerenciar tipo de notas` at the top bar, not on the notetype names

**Comment by BrayanDSO** [comment]
![Screenshot_20220325-102755_AnkiDroid](https://user-images.githubusercontent.com/69634269/160132634-5a92d413-23ea-4dc3-b60d-81ad00a917a7.png)

**Comment by mikehardy** [comment]
Oh! Oops, I see what you mean.
