### ISSUE TITLE
[Feature request] Follow upstream filtered deck name pattern

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10622]
**Is your feature request related to a problem? Please describe.**
AnkiDroid filtered deck default name scheme does not follow upstream current behavior.

**Describe the solution you'd like**
Follow upstream

**Describe alternatives you've considered**
Keep the current behavior

**Additional context**
Upstream uses the current timestamp (HH:mm) after "Filtered deck" ([relevant code](https://github.com/ankitects/anki/blob/main/rslib/src/scheduler/filtered/mod.rs#L149-L154)) (Anki 2.1.49, Windows 10)

![2022_03_25-10_03_36](https://user-images.githubusercontent.com/69634269/160126260-fd9c3f73-00c5-41a3-b2b7-909698a1633d.png) 

AnkiDroid only adds a index number
![image](https://user-images.githubusercontent.com/69634269/160127124-e119ea9a-33db-4dee-b0b8-8da84f9c26d1.png)

**Comment by mikehardy** [comment]
Huh. Interesting. I wonder if we get this for "free" @david-allison as we ingest more current rust lib in future?

**Comment by david-allison** [comment]
Unsure - this one's worth keeping open. I don't believe we get it in 2.1.35

**Comment by BrayanDSO** [comment]
Oh, dear bot. I like how efficient you are on your job of notifying us. It's unfortunate that we have so many changes on Android and Anki to keep up. But we will do this when the time comes, thanks for the job.

**Comment by BrayanDSO** [comment]
Ohhhhh, dear bot, I like our conversations. Perhaps I should give you a name or nickname. We are getting really close to this with all the backend work that is being done. I am very excited with all the new things we will be able to do with it. Maybe as excited as you are with notifying people that their issues are stale

**Comment by BrayanDSO** [comment]
Should be feasible with the new backend. I think that the used method will be the same linked on the issue description

**Comment by dae** [comment]
backend.getOrCreateFilteredDeck()
