### ISSUE TITLE
[Bug] Press-back count isn't reset when returning to `Decks` screen

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10638]
Thanks to developers.

###### Reproduction Steps

1. `Settings` -> `Advanced` > Check `Press back twice to go back/exit`
  ![image](https://user-images.githubusercontent.com/10436072/160280330-e27c6696-3376-4685-bab4-1ce095a54729.png)

2. Return to `Decks` screen
3. Press (Tap) `Back` button
   (Then, `Press back again to exit` toast is shown)
   ![image](https://user-images.githubusercontent.com/10436072/160281309-1290a838-ad7c-484d-9341-66021343ef71.png)

5. Tap a deck
  (Then, `Study screen` is shown. After this step, it is OK to answer some cards, as a natural behavior for ordinary users)

6. Return to `Decks` screen
7.  Press (Tap) `Back` button

###### Expected Result
`Press back again to exit` toast is shown, as on step 3 above.

###### Actual Result
AnkiDroid is closed.

https://user-images.githubusercontent.com/10436072/160282297-2d7e66be-afb3-44bf-b5b1-b31821b489d2.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha53

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.58 Mobile Safari/537.36

ACRA UUID = 057cd16c-e7f1-4e0c-a259-8401e998e532

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by UvrajSB** [comment]
I want to work on this, can you please assign it to me!
Thank You

**Comment by snowtimeglass** [comment]
@UvrajSB, thank you for the fix!
