### ISSUE TITLE
[Bug] Ripple effect is accompanied by another ripple on Decks screen　

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10634]
Thanks to developers.

###### Reproduction Steps

1. Create a subdeck if there aren't any subdecks in `Decks` screen
2. Long tap (or just tap) a deck which doesn't have any subdecks
 (e.g. `Deck 1`, `Deck 3`, `Deck 4`, and `sub` in the following image)

###### Expected Result
A ripple is shown, as follows (on `2.15alpha17 parallel B`).
![image](https://user-images.githubusercontent.com/10436072/160266533-f4e2af76-5f53-4c8e-9a31-58803ef17eb6.png)

https://user-images.githubusercontent.com/10436072/160266823-abeefefb-2c2e-4fb7-b4de-6abe17de4f10.mp4

###### Actual Result
Two ripple are shown. The second ripple is always small and fixed on the left edge.
![image](https://user-images.githubusercontent.com/10436072/160266638-efbce344-e34e-423b-a532-b29ebcbf68f6.png)

https://user-images.githubusercontent.com/10436072/160266826-b82cc0c7-db7b-408a-a90b-c160bb1e0ef4.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha53 (This issue seems to have occurred since 2.15alpha18)

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.58 Mobile Safari/537.36

ACRA UUID = 057cd16c-e7f1-4e0c-a259-8401e998e532

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by shubham419** [comment]
Hi I will be more than happy to solve these issue. 
It will be my first contribution and I really want to contribute.
I have created app which makes process of talking attendance easy.
guide me, help me to grow.

**Comment by lukstbit** [comment]
Setting the listener for `deckExpander` to null in `DeckAdapter.onBindViewHolder()` seems to solve this issue:

```
// ...
if (node.hasChildren()) {
    holder.deckExpander.setTag(node.getDid());
    holder.deckExpander.setOnClickListener(mDeckExpanderClickListener);
} else {
    holder.deckExpander.setClickable(false);
    holder.deckExpander.setOnClickListener(null);
}
```

**Comment by shubham419** [comment]
I am really very happy that someone read my comment. Thank you so much.
Can you explain more, like in which activity or fragment I have to make change please.

**Comment by UvrajSB** [comment]
@shubham419 if you are not working on it then can I do it please?

**Comment by UvrajSB** [comment]
> holder.deckExpander.setOnClickListener(null);

Yeah this change actually removed the double ripple effect

**Comment by UvrajSB** [comment]
@shubham419 if You are not working on this issue then can I please take it?

**Comment by shubham419** [comment]
hi @UvrajSB, now I am working on it. 
if I can't solve it I will let you know.

**Comment by shubham419** [comment]
hi @UvrajSB  I have solved issue.
