### ISSUE TITLE
[Bug] After creating a subdeck, its parent deck's menu is displayed again

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10632]
Thank you always, developers.

###### Reproduction Steps

1. Long tap a deck in `Decks` screen 
(then, the selected deck's menu is displayed.)
3. `Create subdeck`
4. Input a sting (e.g. "sub") -> `OK`

###### Expected Result
`Decks` screen is displayed, as follows (on 2.15alpha18 parallel B).
![image](https://user-images.githubusercontent.com/10436072/160263812-ac5acae6-d53b-4981-8735-2ee16182aa73.png)

https://user-images.githubusercontent.com/10436072/160263703-7f03ac92-d557-4a9a-9d3d-0d43ecb42655.mp4

###### Actual Result
the selected deck's menu is displayed again.
![image](https://user-images.githubusercontent.com/10436072/160263892-7170229c-9099-47fc-afee-bde053385c69.png)

https://user-images.githubusercontent.com/10436072/160263686-8fc93e05-a5af-4eb2-945a-53e85f745b4e.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha53

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.58 Mobile Safari/537.36

ACRA UUID = 057cd16c-e7f1-4e0c-a259-8401e998e532

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
can i work on this issue

**Comment by snowtimeglass** [comment]
@Prince-kushwaha thank you for the fix!
