### ISSUE TITLE
[Bug] Build failed

### ISSUE THREAD

**Issue by Prince-kushwaha** [ankidroid/Anki-Android#10657]
###### Reproduction Steps

1. i update my main branch with upstream main branch 
2. Run the module on android Device Redmi y then after some time Build Failed

<img width="490" alt="Screenshot 2022-03-30 180806" src="https://user-images.githubusercontent.com/65972015/160836112-60a69731-2b83-4b33-bb74-1aa83c24c16d.png">

<img width="878" alt="Screenshot 2022-03-30 181058" src="https://user-images.githubusercontent.com/65972015/160836547-4d3f6c4e-518a-4ced-ace7-72ea834832d3.png">

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
i found this issue afer merge of this PR Enable ##10650

**Comment by david-allison** [comment]
What fixed it for me:

* Close Android Studio 
* Delete the folder: `AnkiDroid/build`
* run `gradlew assembleAmazonDebug`

**Comment by Prince-kushwaha** [comment]
<img width="928" alt="Screenshot 2022-03-30 183657" src="https://user-images.githubusercontent.com/65972015/160841488-39ce0b6d-5f6e-437e-81a1-997dbcfd5435.png">

**Comment by krmanik** [comment]
Deleting `.gradle` directory solved the issues. 

The path of the `.gradle` folder in widows is
```
C:\Users\<username>
```

**Comment by mikehardy** [comment]
I don't think there is anything we can do about this one. I'm going to close this as it is useful for reference only unfortunately, not actionable

And today I learned that moving XML files around *really* confuses gradle for some reason, who knew?
