### ISSUE TITLE
Subdeck limits ignored

### ISSUE THREAD

**Issue by sam-jaques** [ankidroid/Anki-Android#10670]
Version ⁨2.1.49 (dc80804a)⁩ (Ubuntu 18.04.6)
Version 2.0.83 (20083.1) (iOS 15.3)

I have nested subdecks: Deck 1 contains Deck 2 contains Deck 3. Both Deck 2 and Deck 3 belong to the same options group, with a review limit of 0 cards. Deck 1 belongs to a different options group, with a limit of 1000 cards. 

Clicking deck 2 or deck 3 shows no reviews. Clicking deck 1 shows several hundred reviews from deck 3. 

The expected behaviour is that deck 1 should not show any cards from deck 3 (this was the behaviour before I upgraded to the new scheduler today).

**Comment by mikehardy** [comment]
Hi there! No where in there do I see AnkiDroid? Is this reproducible on AnkiDroid?
For Desktop and iOS support you'll want https://forums.ankiweb.net
