### ISSUE TITLE
[Feature request] Add new deck option on move cards dialog

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10674]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to move cards to a new deck. In Anki desktop I only need to select them, press the move cards option and then the add deck button.
On AnkiDroid I don't have a `add` option, so I need to previously create a deck on the main screen then move the cards. This adds additional friction to the job and is a lacking upstream feature

**Describe the solution you'd like**
An option in the dialog to create a new deck to move my cards, like upstream

**Describe alternatives you've considered**
None

**Additional context**

## Anki desktop (2.1.49) change deck dialog

On Windows 10:
![2022_04_01-09_11_00](https://user-images.githubusercontent.com/69634269/161261755-d3bc52fc-0124-4e42-9da8-4638bdae333c.png)

![2022_04_01-09_22_47](https://user-images.githubusercontent.com/69634269/161262560-5784ee91-66fb-480a-a8c3-f6be64e829e7.png)

## Ankidroid (2.1.6alpha54) change deck dialog

On my phone (Samsung Galaxy Note 10 Lite SM-N770F/DS, API 30)

![Screenshot_20220401-091557_AnkiDroid](https://user-images.githubusercontent.com/69634269/161262342-541077d0-f5a3-41a0-8374-92f06d3af19e.png)

**Comment by david-allison** [comment]
👍

**Comment by BishyanKar** [comment]
@david-allison Can I work on it?

**Comment by david-allison** [comment]
Let's give @BrayanDSO 36 hours to see if they'd like to claim it, if not, it's yours

**Comment by BrayanDSO** [comment]
@BishyanKar, since I wanted this ASAP to my Anki daily studies I've already started to work on it.
But thanks for the desire to take this up 😄

**Comment by winstoncooke** [comment]
This is a really handy feature! It's something I'll use frequently.
I agree about reusing the search deck dialogue as mentioned in #10681. It's what I would expect and feels more consistent.

**Comment by BishyanKar** [comment]
> @BishyanKar, since I wanted this ASAP to my daily studies on AnkiDroid, I've already started to work on it. But thanks for the desire to take this up 😄

No issues. It's a great feature indeed.
