### ISSUE TITLE
[Bug] Edit note & Replay audio buttons inconsistently appear based on initial screen rotation

### ISSUE THREAD

**Issue by winstonrc** [ankidroid/Anki-Android#10683]
###### Reproduction Steps

1. Click on a deck to study the cards while the device is portrait
2. Note the `Edit note` and `Replay audio` buttons are not in the top right
3. Rotate the device horizontally and note that the `Edit note` and `Replay audio` buttons are still not there
4. Back out to Decks screen
5. Click on a deck to study the cards while the device is horizontal
6. Note the `Edit note` and `Replay audio` buttons are now in the top right (even for cards without audio)
7. Rotate the device to portrait and note that the `Edit note` and `Replay audio` buttons are still there (even for cards without audio)

###### Expected Result
1. The visibility of overflow buttons should be consistent regardless of initial device orientation when selecting a deck
2. Optionally, the replay audio button should not appear on cards with no audio (perhaps this should be a separate issue)
3. Optionally, the replay audio button appears to be redundant given there's already a play audio button next to the word itself. Although, this could be considered by design and falls under [removing the audio play button](https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#remove-the-audio-play-button-from-flashcards) in the FAQ.

###### Actual Result
Buttons tagged to show `ifRoom` show up when a deck has been clicked on while the device is horizontal and remain there until backed out. This means the user could be studying a card horizontally, but depending on their device orientation when they initially clicked on a card, the buttons may or may not be there.

###### Debug info
```
AnkiDroid Version = 2.15.6

Android Version = 12

Manufacturer = samsung

Model = SM-S901U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-S901U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 6513c4b2-d751-40e6-9fab-f42c1fc1e7f9

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Example video

https://user-images.githubusercontent.com/71997294/161393085-0b134f9b-059e-4264-8f1b-62c9572e7af3.mp4

**Comment by mikehardy** [comment]
Hey there! Definitely check the current alpha to see if it still happens: https://github.com/ankidroid/Anki-Android/releases but if it does, nice find!

**Comment by winstoncooke** [comment]
> Hey there! Definitely check the current alpha to see if it still happens: https://github.com/ankidroid/Anki-Android/releases but if it does, nice find!

I'll take a look tomorrow and then dive in if it's still an issue. I assume it has to do with how the process for calling status bar items if they fit might only be invoked when initially clicking onto the deck. May have to be changed so that it is called based on device rotation. But would love to hear your thoughts. It's definitely a minor inconsistency.

**Comment by winstoncooke** [comment]
> Hey there! Definitely check the current alpha to see if it still happens: https://github.com/ankidroid/Anki-Android/releases but if it does, nice find!

I'll take a look tomorrow and then dive in if it's still an issue. I assume it has to do with how the process for calling status bar items if they fit might only be invoked when initially clicking onto the deck. May have to be changed so that it is called based on device rotation. But would love to hear your thoughts. It's definitely a minor inconsistency.

**Comment by winstoncooke** [comment]
> Hey there! Definitely check the current alpha to see if it still happens: https://github.com/ankidroid/Anki-Android/releases but if it does, nice find!

I'll take a look tomorrow and then dive in if it's still an issue. I assume it has to do with how the process for calling status bar items if they fit might only be invoked when initially clicking onto the deck. May have to be changed so that it is called based on device rotation. But would love to hear your thoughts. It's definitely a minor inconsistency.

**Comment by winstoncooke** [comment]
Can confirm the issue still exists on [AnkiDroid 2.16alpha54](https://github.com/ankidroid/Anki-Android/releases/tag/v2.16alpha54).
I'll take a look into it, and see if I can figure out an elegant solution.

**Comment by winstoncooke** [comment]
@mikehardy I've run into a wall, so perhaps your familiarity with the codebase can help.

In the AbstractFlashcardViewer class, which is inherited by Reviewer.kt, the following methods are called:

```
@Override
    public void onConfigurationChanged(Configuration config) {
        // called when screen rotated, etc, since recreating the Webview is too expensive
        super.onConfigurationChanged(config);
        refreshActionBar();
    }

protected void refreshActionBar() {
        supportInvalidateOptionsMenu();
    }
```

Now I would assume that the supportInvalidateOptionsMenu() would be invoked each time the device rotates and then [refresh the menu bar](https://developer.android.com/guide/topics/ui/menus#ChangingTheMenu), which would then look for the `always` and `ifRoom` attributes for choosing whether or not to display the optional menu bar items. Obviously, that is not the case when the user is on the reviewer screen. Any thoughts as to why that's not occurring?

**Comment by mikehardy** [comment]
Hmm - in AndroidManifest you make an entry for each activity advising what config changes they respond to, perhaps it is missing (I'd be surprised, but that is the start of the call chain for rotation events)
After that...I'm not sure sorry :sweat_smile:

**Comment by winstoncooke** [comment]
All is well in the manifest. The menu bar noticeably shrinks and reduces the font size to fit all the extra items in there. However, I'm stumped, and this is such a minuscule issue. Gonna have to put it on hold. Hopefully it's a bug in Android itself!

I can close the issue if you'd like.

**Comment by mikehardy** [comment]
Nah, if it's really an issue good to stay open in case others want to take a crack at it, at least until the stale bot reaps it

**Comment by briancatraguna** [comment]
@winstoncooke Can I work on this issue?

**Comment by winstoncooke** [comment]
> @winstoncooke Can I work on this issue?

Please do! My last findings were perhaps it's because there is no onPrepareOptionsMenu() method for Reviewer.kt, which would be invoked on invalidateOptionsMenu(). Perhaps that helps.

**Comment by Amandeep404** [comment]
is this issue solved?

**Comment by winstoncooke** [comment]
Not as far as I'm aware

**Comment by oakkitten** [comment]
Still an issue. 

A proper fix would be stopping handling orientation changes, as well as other changes.

**Comment by alyoshenka** [comment]
I am currently looking into this and will ask to be assigned once I have an idea for a fix.

**Comment by oakkitten** [comment]
As long as I'm not mistaken, not handling orientation changes should fix this and other issues. There's a high chance that this will be done one day, since this is an all-around sensible change. So I'd suggest not implementing any temporary workarounds, at least not if it is not clearly marked as such, and easy to remove.

**Comment by alyoshenka** [comment]
Ah ok, and so not handling orientation is a different and bigger issue to fix. I'll look into something else, thanks!

**Comment by Akshatkamboj14** [comment]
Hey can i work on this issue?

**Comment by ShubhadeepKarmakar** [comment]
Is this issue still open @winstonrc?

**Comment by winstonrc** [comment]
As far as I’m aware it is still open.
