### ISSUE TITLE
Move Cards: Fix alignment of the list of decks

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10681]
Let's add a follow-up issue: I don't like the alignment of the items being to the left of the dialog - the margins seem off

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/10680#issuecomment-1086645836_

**Comment by BrayanDSO** [comment]
> Let's add a follow-up issue: I don't like the alignment of the items being to the left of the dialog - the margins seem off

100% agreed. This is currently a AlertDialog.

IMO the ideal solution is to reuse the search deck dialog so we can use the search deck button, but keep filtering the valid decks to move cards (i.e. non dynamic decks)

I only noticed it now, but the search deck dialog even has a new deck button, which makes it even better.

**Comment by david-allison** [comment]
Sounds good! If you'd like to do it in the linked PR then I'd more more than happy.

Do note that I wrote `SearchDeckDialog` quickly for a sub-sub screen and didn't intend for it to see mainstream use. Very happy to see architectural fixes if they're needed
