### ISSUE TITLE
[Bug] Flag display on reviewer minibar is inconsistent when changing flags

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10691]
###### Reproduction Steps

1. Have `Flag` app bar option to `Always`
2. Open a flagged card
3. Reflag it

https://user-images.githubusercontent.com/69634269/161430479-57b09dd5-dad4-46b5-a4a7-531e488d108a.mp4

###### Expected Result

Flag on minibar should not appear if app bar already has the `Flag` option. Neither the flag should vanish when changing if the former was the intended behavior

###### Actual Result

The minibar flag appear then vanishes when changed

###### Debug info
```
AnkiDroid Version = 2.16alpha54

Android Version = 11

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-N770F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 037bbc86-38a4-4ad7-9c42-05870e9b6086

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
The flag was intended to not appear in the mini-bar if it appears in the app bar.

**Comment by BrayanDSO** [comment]
> The flag was intended to not appear in the mini-bar if it appears in the app bar.

Is it intended to do this as well on full screen mode enabled (i.e. app bar hidden)? 

I personally would like not to have to hide the flag button on the `...` menu to see the flag on the mini-bar

**Comment by david-allison** [comment]
It was, but I'd be open to changing that in a new issue.

This is a bug that's introduced somewhere in 2.16

**Comment by david-allison** [comment]
Bug was introduced between a11896c20dcd8af20f31a203711d591e1f1129d4 and 411dd9c1ba8fbba6d7313dbf326033a524c851cd

(alpha 25 and 27)

**Comment by BrayanDSO** [comment]
I expect 66300a61a4c91227423308b6492964a7403dd7eb to be the first bad commit (gradle is taking ages to download/build, so I'll just guess)

Amusing facts:

1. It works at the first run after opening the app, but not after

https://user-images.githubusercontent.com/69634269/161443877-f230e948-b9b3-4c48-8229-f20f9cb91716.mp4

2. The bug appear to be on findMenuItem. Sometimes the mMenu is null

https://github.com/ankidroid/Anki-Android/blob/9f5888df5b2f1c6d8b433b7c4cdc2d04ebb14e20/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtons.kt#L49-L53

3. If I just attach a break point to any part of onCreateOptionsMenu (where the menu is defined), menu never comes null and it works fine, even without me changing anything

https://github.com/ankidroid/Anki-Android/blob/1bcdc6df02e8d224282a29b471a2421a301c0517/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt#L646-L651

**Comment by Kshitij09** [comment]
@BrayanDSO will you be fixing this one? I'm new to this repo and I feel this could be a good exercise for me to try solving the same. Let me know if you've already made some progress and is there any way we could collaborate.

**Comment by BrayanDSO** [comment]
I've only assessed it on the [above comment](https://github.com/ankidroid/Anki-Android/issues/10691#issuecomment-1086930855). I will not have the time for it right now.

So, you can go for it. I hope you will manage it and welcome to AnkiDroid!

**Comment by Kshitij09** [comment]
Sure @BrayanDSO, thanks! 

> It works at the first run after opening the app, but not after

Also, I can confirm this behavior as I was trying to reproduce the issue. I will look into it 🧐

**Comment by Kshitij09** [comment]
After a day, and going through all the [changes from alpha 25 to 27](https://github.com/ankidroid/Anki-Android/compare/v2.16alpha25..v2.16alpha27), I came down to the same conclusion,

> The bug appear to be on findMenuItem. Sometimes the mMenu is null

 I tried adding log statements in this function by checking out `release-2.15` as well as the `main` branch. `mMenu` was never `null` on branch `release-2.15` but it intermittently appears null on the current main. I suspect this has something to do with prior changes as well (pre-alpha25). We need to check all the places where we call `refreshActionBar` (which in turn calls `supportInvalidateOptionsMenu()`)

**Comment by BrayanDSO** [comment]
The approach I would try is:
1. Identify the first bad commit, either manually or with `git bisect` (as I said before, I expect it to be 66300a61a4c91227423308b6492964a7403dd7eb)
2. See what changed there and try to isolate the part which created the bug
3. Make a regression test

The fact that the first Reviewer opening always work may give a clue. I think your thought about `refreshActionBar` makes sense. Seeing its implementation may help

> If I just attach a break point to any part of onCreateOptionsMenu (mMenu is set on mActionButtons.setCustomButtonsStatus()), menu never comes null and it works fine, even without me changing anything

The part that bugs me the most is this. I don't know why this happened. Maybe is a problem with the compile I made back there, but I need someone else to confirm it.

So, here's my two cents. I hope it may be helpful

**Comment by Kshitij09** [comment]
@BrayanDSO Interesting! This was indeed useful. One more thing I find a bit challenging here is coming up with a Regression Test that fails on the `main` while succeeds on some previous commit, as I don't think manually running the app to test this scenario on every commit git bisect offers is a good idea.

Could you point me to a Regression Test that I could take inspiration from?

**Comment by mikehardy** [comment]
https://github.com/ankidroid/Anki-Android/issues/6176
https://github.com/ankidroid/Anki-Android/issues/6149

not sure if this will help or not, but all I could think of were the crashes that David bisected a while back, where he posted the bisect test case on the issue

**Comment by Kshitij09** [comment]
I found the cause! 🥳  
https://github.com/ankidroid/Anki-Android/blob/6b17f60821b580d5500a139cdecb70f9de407bd6/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt#L1001

We're calling `onFlagChanged()` and `onMarkChanged()` in `Reviewer::fillFlashCard`. While am not sure why we call these methods here, I am quite certain that commenting out these lines doesn't display the flag inconsistently.
