### ISSUE TITLE
[Bug] Filtered deck doesn't mix learning with reviews

### ISSUE THREAD

**Issue by szalejot** [ankidroid/Anki-Android#10694]
###### Reproduction Steps

1. Create a filtered deck
2. Use search criteria: deck:"MyDeck" is:due 
3. cards selected by: Random

###### Expected Result

When in the review of this filtered deck random mix of learning and review cards should appear.
Learning cards have intervals of 1 day.
This is how this deck behaves on the Anki desktop - V3 scheduler.

###### Actual Result

When in the review of this filtered deck first all learning cards are presented, only then reviews.

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 8.0.0

Manufacturer = asus

Model = ASUS_Z01HD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; ASUS_Z01HD Build/OPR1.170623.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = ffc51eb1-d4d4-4314-a51d-a8de3cb61665

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
We currently only support up to `V2` scheduler. It will be probably quite some time until we support V3.

**Comment by szalejot** [comment]
@BrayanDSO  But if there are learning with a 1 day steps, shouldn't this combination also work on V2?

**Comment by mikehardy** [comment]
This needs someone more familiar with the scheduler then me, suggest either @david-allison or @Arthur-Milchior otherwise I (or someone else) is going to need to do some scheduler research since I don't use filtered decks myself and am not sure what the behavior should be.
