### ISSUE TITLE
[Feature request] Option to disable auto sync with metered connections

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10706]
**Is your feature request related to a problem? Please describe.**
I have auto sync enabled, but I don't want to spend my mobile data with automatic syncs. Mobile data prices can be quite a concern in some countries

**Describe the solution you'd like**
An option to only do auto sync on not metered connections
Extra: a dialog asking if user want to proceed on manual syncs on metered connections

**Describe alternatives you've considered**
None

**Additional context**
JsApi has something similar already #6784

**Comment by mikehardy** [comment]
It's more than just wifi or not, it's "connection is metered" as in the JsAPI thing you link - I'd say just make that generic (put it in a util somewhere?), have the JsAPI reference the new util method (of course), then all the decisions are how to handle the UX

Thoughts:
- have a toggle in settings where ever the sync config is, to toggle *on* sync over metered connections and default it to off (this is a change from current behavior but is actually the kindest on data plans - I live in Ecuador and lean towards default off based on my experience here)
- check it before syncing any time - if it's a manual sync maybe pop a dialog saying "hey, it's a metered connection, are you sure?"
- if it's an auto-sync pop a toast that says "auto-sync disabled on metered connection" with maybe a "sync anyway" button?
- optionally have separate toggles for collection sync and media sync? Not sure if that's even possible

I am mostly just thinking out loud here. I like the root idea as it is in your title, obviously

**Comment by david-allison** [comment]
I like the idea (my data is $0.17/MB if the contract runs out) - we probably want more 'sub-preference' screens, and I'd like to see 'sync' or 'auto-sync' become one of them


> have a toggle in settings where ever the sync config is, to toggle on sync over metered connections and default it to off (this is a change from current behavior but is actually the kindest on data plans - I live in Ecuador and lean towards default off based on my experience here)

100%, off as a default

> if it's an auto-sync pop a toast that says "auto-sync disabled on metered connection" with maybe a "sync anyway" button? 

Snackbar, toasts can't have options - very similar to the 'you're offline'

> optionally have separate toggles for collection sync and media sync? Not sure if that's even possible

Could we shelve this for now? Once scoped storage is off the agenda, moving 'sync' to libAnki is going to be a project - a lot of the libAnki performance improvements have made the conversion very difficult, and I'd rather avoid large changes in the sync code for the same reasons.

**Comment by mikehardy** [comment]
agreed all points on that as refinements on my thinking-out-loud, except I do not agree for your sake with 17c/MB data ouch!!

**Comment by BrayanDSO** [comment]
2 months already? Oh time flies for sure. Later, dear bot
