### ISSUE TITLE
Widget with reviewer on home screen

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10708]
This is a feature I'd like very much. Having a widget that shows the reviewer directly in the main screen.
That means that, instead of having to open ankidroid and select a deck, when I open the phone, I'd see on my screen a question, and a button to show the answer. That would also means that reviewing requires less motivation, since you directly see a question.

If we are lucky, the reviewer can almost be used as is. If we are not, we'll discover plenty of issues during test. I can already imagine:
* for video and audio it can't be played by default anymore, so we should just show the icon to play the media
* for big image, I am not sure anything practical can be made
* it's not clear whether we should have a parameter that ensure that the widget always show the same deck or that it shows the last selected deck. 
* Gesture. Widgets are not able to capture left/right gesture. Only up/down gesture. This is because left/right gesture moves the android screen to the next/previous window. Personally, it would be an issue because I use those left/right gesture a lot. 

The good news is that for simple collections with one deck and simple cards such as "Word in a language -> word in another language", this widget will still be quite useful.

If other maintainers believes it may be interesting, I'd like it to be a GSoC project, if we can find a candidate interested in it.

# Consideration regarding the choice of deck

## From the user perspective

I believe it's far more intuitive to select the deck once and for all, and always have the same deck in the widget. Maybe even have multiple widgets, with multiple decks.

While changing the decks may seems a good idea, it requires an extra option menu, which goes against the purpose of the widget to be very simple.

## Implementation issue

One issue with Anki(Droid) is that the selected deck is a state of the current collection. The scheduler simply uses the selected deck from the collection preference. So we can't have two schedulers that just work in parallel, giving cards for different selected decks in different widgets. (Actually, limits by day would be a nightmare to define if we can simultaneously select multiple decks that descends from the same parent)

Worse, that mean that if you select a deck in ankidroid, that will be the deck shown in the widget. Unless you explicitly change the selected deck when the widget is shown, which means that when you open ankidroid, you'll always be back to this selected deck. (Unless you had yet another state, "backupSelectedDeck" where the widget store the deck selected previously, and which is restored as "SelectedDeck" when AnkiDroid is open)

**Comment by david-allison** [comment]
I don't believe WebViews are supported by Widgets

> You cannot use custom views or subclasses of the views that are supported by RemoteViews.

https://developer.android.com/guide/topics/appwidgets/index.html#layout



> RemoteViews is limited to support for the following layouts:
> 
> [AdapterViewFlipper](https://developer.android.com/reference/android/widget/AdapterViewFlipper)
> [FrameLayout](https://developer.android.com/reference/android/widget/FrameLayout)
> [GridLayout](https://developer.android.com/reference/android/widget/GridLayout)
> [GridView](https://developer.android.com/reference/android/widget/GridView)
> [LinearLayout](https://developer.android.com/reference/android/widget/LinearLayout)
> [ListView](https://developer.android.com/reference/android/widget/ListView)
> [RelativeLayout](https://developer.android.com/reference/android/widget/RelativeLayout)
> [StackView](https://developer.android.com/reference/android/widget/StackView)
> [ViewFlipper](https://developer.android.com/reference/android/widget/ViewFlipper)
> And the following widgets:
> 
> [AnalogClock](https://developer.android.com/reference/android/widget/AnalogClock)
> [Button](https://developer.android.com/reference/android/widget/Button)
> [Chronometer](https://developer.android.com/reference/android/widget/Chronometer)
> [ImageButton](https://developer.android.com/reference/android/widget/ImageButton)
> [ImageView](https://developer.android.com/reference/android/widget/ImageView)
> [ProgressBar](https://developer.android.com/reference/android/widget/ProgressBar)
> [TextClock](https://developer.android.com/reference/android/widget/TextClock)
> [TextView](https://developer.android.com/reference/android/widget/TextView)
> As of API 31, the following widgets and layouts may also be used:
> 
> [CheckBox](https://developer.android.com/reference/android/widget/CheckBox)
> [RadioButton](https://developer.android.com/reference/android/widget/RadioButton)
> [RadioGroup](https://developer.android.com/reference/android/widget/RadioGroup)
> [Switch](https://developer.android.com/reference/android/widget/Switch)
> Descendants of these classes are not supported.

https://developer.android.com/reference/android/widget/RemoteViews

**Comment by mikehardy** [comment]
Guess we'll just have to open the app ;-)
