### ISSUE TITLE
[Bug] The color of "Reschedule" icon on "︙" menu isn't same as one of other icons, but always white

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10703]
Thank you always, developers.

###### Reproduction Steps

1. `Settings` -> `Reviewing` -> `App bar buttons` -> `Reschedule` -> `Menu only` 
2. Open Study screen

3. Tap `︙` button on the upper right of the screen

###### Expected Result

- `Reschedule` icon is visible
- The color of `Reschedule` icon is same as one of the other icons

###### Actual Result

![image](https://user-images.githubusercontent.com/10436072/161527603-fd28f6f7-dc9f-4e3f-8d68-dd96b9a28bb5.png)
- `Reschedule` icon isn't visible when `Theme` is `Light` or `Plain`
-  The color of `Reschedule` icon isn't same as one of the other icons (as @BrayanDSO mentions in #10697), but always white.

###### Debug info
```
AnkiDroid Version = 2.16alpha55

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = eaa1e476-1b19-4d58-8d4e-5226e342002d

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Thanks for creating the issue 👍🏻

**Comment by snowtimeglass** [comment]
@BrayanDSO thanks, too. I always use AnkiDroid on `Light` theme, so I was about to write a bug report which claims "Reschedule icon doesn't exist". I was surprised when I see the icon on `Black` theme screenshot you posted in the third.

**Comment by snowtimeglass** [comment]
Ah, majority is not always right. Perhaps, on `Black` and `Dark` theme, the color of `Reschedule` icon is right because it is same as one of  App bar icons. On these themes, the color of other icons on `︙` menu might have to be corrected to white.

![image](https://user-images.githubusercontent.com/10436072/161539563-c083c874-9f9c-4eb6-b0bf-5646cea49b2e.png)

**Comment by Prince-kushwaha** [comment]
@krmanik can i work on this issue

**Comment by Ghanem21** [comment]
@ShridharGoel 
@krmanik 
Hi sir can I work on this issue,I will make it's color as the same of other

**Comment by krmanik** [comment]
@Ghanem21 You do not need to address anyone as sir here.

Sure! Go for it.

**Comment by Prince-kushwaha** [comment]
Ok

**Comment by Ghanem21** [comment]
@krmanik 
I'm new in open source and I'm here for Gsoc
Can you give me a Free issues to work on it please

**Comment by Prince-kushwaha** [comment]
@Ghanem21 good first issue  https://github.com/ankidroid/Anki-Android/labels/Good%20First%20Issue%21
and open issue https://github.com/ankidroid/Anki-Android/issues

**Comment by krmanik** [comment]
@Ghanem21 
The https://github.com/ankidroid/Anki-Android/labels/Good%20First%20Issue%21 is good for get started to contributing to AnkiDroid. Also you can check other [issues](https://github.com/ankidroid/Anki-Android/issues) if you feel confident to implement.

**Comment by krmanik** [comment]
Whiteboard icon also have this issue.

1. Enable whiteboard
2. Then click curve icon to disable white board. The whiteboard editor icon becomes white.
3. Sometimes it show sometimes not.

**Comment by Prince-kushwaha** [comment]
@krmanik i create separate issue for WhiteBoard icon issue or fix it in this current pull request ?

**Comment by s-deepak-kumar** [comment]
Can I Work On This Issue?

**Comment by mikehardy** [comment]
This one has  PR pending merge now, it's not open for contribution. Thanks @Prince-kushwaha for the fix!

**Comment by krmanik** [comment]
> @krmanik i create separate issue for WhiteBoard icon issue or fix it in this current pull request ?

You can create a PR for this if you verified the issue.

**Comment by snowtimeglass** [comment]
@Prince-kushwaha, thank you for the fix!
