### ISSUE TITLE
[Dev] Add IntelliJ dictionaries to reduce 'typo' warnings

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10713]
This is for discussion, not yet for implementation.

IntelliJ allows for project-level dictionaries, to remove the 'typo' warnings in code.

IntelliJ is apparently set up so each user has their own dictionary of 'valid' words. This individual dictionary exists to avoid merge conflicts, but the IDE uses all combined dictionaries when flagging typos.

https://stackoverflow.com/a/28151692

After a bit of deliberation: I'm in favour of this setup. My only concern is that it moves `git blame` to `git grep -> git blame` if you want to find out why a word was in a dictionary, and it makes listing the full dictionary slightly harder.

**Comment by mikehardy** [comment]
Seems fine, I dislike the little green squiggles myself, and it if is no good we can always take it out later.
Similar to the project settings being committed it was sort of experimental to start - "it seems like it could help, let's try it..." and in practice it works okay. This could be same
