### ISSUE TITLE
[Suggestion] Rename "Reviews" on App shortcuts menu more comprehensible name

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10728]
Thank you always, developers.

**Is your feature request related to a problem? Please describe.**

- The item named `Reviews` on App shortcuts menu reopens Study screen of the last opened deck. Its name seems ambiguous and confusing to understand its feature. For one thing, this word, "Review(s)", has multiple meanings on Anki.
![image](https://user-images.githubusercontent.com/10436072/161939169-35eb0ef6-8b45-4ae7-9d8e-20879a56db8f.png)
![image](https://user-images.githubusercontent.com/10436072/161967456-af784ef9-fb77-4c4b-b544-7b1166e1b4fa.png)

**Describe the solution you'd like**

- Rename the item's name more comprehensible one, for example, "Back to Study", "Restart Study", and so on.
![image](https://user-images.githubusercontent.com/10436072/161963729-2677c6ce-2d36-4e73-a8a8-9bbf1bf52387.png)

**Describe alternatives you've considered**

- Keep its name unchanged, but make an independent string for it on Crowdin to make room for adjustment on respective languages.  [The string for "Reviews" on Card info](https://crowdin.com/translate/ankidroid/all/en-en?filter=basic&value=0#6535194) seems to be reused for it currently.
![image](https://user-images.githubusercontent.com/10436072/161964173-3f5f87d5-5672-484d-9c2d-4f283914e4ef.png)

**Additional context**

- On current Japanese translation, the string for "Reviews" on Card info isn't suitable for the item named "Reviews" on App shortcuts menu. I would like to fix this mismatch.

**Comment by BrayanDSO** [comment]
> Rename the item's name more comprehensible one, for example, "Back to Study", "Restart Study", and so on.

I support this. Way more intuitive.

I know Anki uses `Review` because, after all, the main purpose of the app is to *review* flashcards. But, I don't have to spend any time to think what `Back to study` means, while `Reviews` needs some thought. So, I personally like this change

**Comment by mikehardy** [comment]
Is "Study" used anywhere? Would "Review cards" or "Open Reviewer" be less ambiguous? I'm not as familiar with the terminology Anki uses in the ecosystem but it would be good to use only words Anki uses normally on desktop

Note that if we change a string and we want fresh translations, there is no clean way to do it without removing the string and re-adding it and all languages lose their current translation. That is worthwhile in some cases but it is a translation cost to keep in mind - if we do this we should do it correctly in other words

**Comment by snowtimeglass** [comment]
>Is "Study" used anywhere?

>it would be good to use only words Anki uses normally on desktop

>I think it's important to use the exact words Anki Desktop uses as much as possible, for fidelity

The word, "Study", is used on the buttons on [Deck overview screen in Anki Desktop](https://docs.ankiweb.net/studying.html#study-overview), and [AnkiDroid](https://docs.ankidroid.org/#deckOverview) respectively. These buttons are used to start showing cards, as the item named "Reviews" on App shortcuts menu is done so.
 ![image](https://user-images.githubusercontent.com/10436072/162004065-538c8f8b-f85b-4450-bac3-29a1176151ad.png)

As a side note, "Review" is used on the left side of the button on Anki Desktop as a part of the name of three type cards to be shown. 
![image](https://user-images.githubusercontent.com/10436072/162015232-0badb4fd-de98-4062-99f8-ebfd6d9b3e45.png)




>Would "Review cards" or "Open Reviewer" be less ambiguous?

Considering cases of studying "new" cards (unseen cards), selecting an item named "Review cards" (or "Open Reviewer") seems a bit unnatural. I think that "Study" is an inclusive word to describe checking "new", "learning", and "review" cards. Anki Desktop and AnkiDroid use the word, "Study", to start the check indeed.
  
>Note that if we change a string and we want fresh translations, there is no clean way to do it without removing the string and re-adding it and all languages lose their current translation. That is worthwhile in some cases but it is a translation cost to keep in mind - if we do this we should do it correctly in other words

Yes, I'll keep it in mind, it's very important, but in this case, I think that their current translations aren't lost at least from Crowdin even if the strings are removed from the item, because they probably remain to be used for "Reviews" on Card info. They can be reused if the above alternative solution plan is done.

>IMO `Review cards` is fine

>I think we could go with that. Do you think it's worth it to push this slight tweak out to all languages and force them to re-translate or is this just an English-string problem? 

To be honest, I think it might be worth to push the change I have suggested above (i.e., "Back to Study", "Restart Study", etc.), not "Review cards", to all languages for the above reasons (For one thing, the word, "Review(s)", seems confusing and unnatural in this case; for another thing, Anki Desktop and AnkiDroid use the word, "Study", to start checking cards), but I'm not a rushing perfectionist who demand perfection in a hurry by using other people's effort and time. I agree that it might still be just a low-priority slight tweak. I would like to know what you developers think about this change. I mean no offense, of course :-)

**Comment by mikehardy** [comment]
nice screenshot, makes me think 'study now' is right on

**Comment by BrayanDSO** [comment]
Thanks for the research. Since Anki Desktop uses `Study now` and I agree it's more natural than `Review`, I think it's worth the change.

In brazillian portuguese, it's used a straight translations of `Reviews`, so it's still unnatural for this sample

**Comment by snowtimeglass** [comment]
Thanks for the feedbacks. If you two say so, it'll be good to adopt `Study now`. I'll vote for it, too :-)

**Comment by mikehardy** [comment]
Okay - action here is:
- check for usages of existing string resource key to see if it is used in multiple locations
- if used in only one location - this location - remove it, otherwise leave it
- make a new string with a more specific name, and english value "study now", make sure to add a context string to help translators, attach a screenshot showing it if possible

That will force new translation for this spot and get the new string in

**Comment by winstoncooke** [comment]
Is this available to work on?

**Comment by Niraj81** [comment]
Can I work on this?

**Comment by Arthur-Milchior** [comment]
While @winstoncooke asked first, I'd prefer to leave the issue to someone who has not already contributed. Since PR are mandatory to apply to GSoC, I prefer to leave the way to everybody to create one PR, which is hard given our small number of issue.

By the way, @snowtimeglass, I don't know if it's a coincidence that you send us so many issues during the start of GSoC application. But thank you very much, it's extremely appreciated. We are in this very strange situation where we have a lack of bugs, and every single improvement is appreciated in order to let our candidates have at least one contribution.

For the context, `studyoptions_start` is the button on bottom of "study option fragment", the fragment on the right of the deck picker on tablets. Since it's a button opening an action, I believe that it is probably also acceptable for a shortcut. At least until a translator tell us that they can't use the same word for both places

**Comment by mikehardy** [comment]
I thought the same thing about the issues @snowtimeglass logged - I thought "wow that's great timing!" - if you have any more send them in!

**Comment by winstoncooke** [comment]
> While @winstoncooke asked first, I'd prefer to leave the issue to someone who has not already contributed. Since PR are mandatory to apply to GSoC, I prefer to leave the way to everybody to create one PR, which is hard given our small number of issue.

My only PR so far is removing an erroneous </p> tag in the READEME, so it's not much! I just submitted a PR but saw @Abhiram-DLVSS has already linked one.

**Comment by snowtimeglass** [comment]
@Arthur-Milchior, @mikehardy,  thank you so much! I'm very pleased to hear that.

>I don't know if it's a coincidence that you send us so many issues during the start of GSoC application.

Ah, it's pure coincidence. At first, I was surprised at the recent situation and thought "what's on earth going on!?" And now, I think "what good timing!"

>We are in this very strange situation where we have a lack of bugs

Hahaha, wow!

>every single improvement is appreciated in order to let our candidates have at least one contribution.

>if you have any more send them in!

Sure, with pleasure. I do have them!

**Comment by snowtimeglass** [comment]
@winstoncooke, thank you for the fix!

**Comment by winstoncooke** [comment]
@snowtimeglass thank you for all your help pointing out issues!

**Comment by Abhiram-DLVSS** [comment]
I'm closing my pull request (https://github.com/ankidroid/Anki-Android/pull/10759 ) as the alternate pull request is merged.

**Comment by snowtimeglass** [comment]
@winstoncooke it's my pleasure!

@Abhiram-DLVSS thank you for the PR. I'm sorry about it. I will see you on other issues soon!
