### ISSUE TITLE
font not display normally on ankidroid

### ISSUE THREAD

**Issue by Stonehomecai** [ankidroid/Anki-Android#10725]
**Is your feature request related to a problem? Please describe.**
have a deck can display font normally on desktop and ankidroid but when I change to other content, desktop display normal but ankidroid not.

**Describe the solution you'd like**
Hope that both terminals can display normally.

**Describe alternatives you've considered**
Same as above

**Additional context**
this deck is the one display normally on both desktop and mobile terminal.
![image](https://user-images.githubusercontent.com/34940981/161911491-f703cc85-c727-445d-b720-3172554e1021.png)

this deck is changed content, display normally on desktop, not display same font effect on ankidroid.
![image](https://user-images.githubusercontent.com/34940981/161911690-eb8ce297-bf9e-4956-8703-a03cbc2f775a.png)

**Comment by mikehardy** [comment]
Perhaps you have correctly set up pinyin.tts and kt.ttf but not yiqipinyin.ttf? 
https://github.com/ankidroid/Anki-Android/wiki/FAQ#how-can-i-use-custom-fonts
