### ISSUE TITLE
[Suggestion] Add an icon to the item of "Deck options" on Actionbar of Study screen

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10731]
Thanks to developers.

**Is your feature request related to a problem? Please describe.**

- #9110 is unquestionably a wonderful work, but it seems to have not solved all of the tasks mentioned on  #8912 yet. One of the unsolved tasks is [to add an icon to "Deck options"](https://github.com/ankidroid/Anki-Android/issues/8912#issuecomment-850807096). 
![image](https://user-images.githubusercontent.com/10436072/161990085-bddb53db-d79b-43d4-b3fd-0f0ea1e7b519.png)

**Describe the solution you'd like**

- Add [the following icon](https://fonts.google.com/icons?selected=Material+Icons+Outlined:tune:) to "Deck options".
![image](https://user-images.githubusercontent.com/10436072/161993305-4f9e1794-d3d1-4969-9def-92b8fa9e2b8b.png)
![image](https://user-images.githubusercontent.com/10436072/161993133-d79eef75-7b76-4442-9775-d1aa819713f6.png)

**Describe alternatives you've considered**

- Add [the following icon](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Asettings_applications%3A) to "Deck options".
![image](https://user-images.githubusercontent.com/10436072/161994966-0a9a56a9-a8b8-4b78-8325-e343aaa9eb0c.png)
![image](https://user-images.githubusercontent.com/10436072/161994874-d5f956e8-535f-4333-a1a2-b845de3e3d7c.png)

**Additional context**

- N/A

**Comment by mikehardy** [comment]
I like Tune as well

**Comment by snowtimeglass** [comment]
Me too :-)

**Comment by s-deepak-kumar** [comment]
Can You Please Assign It To Me?

**Comment by mikehardy** [comment]
sure!

**Comment by s-deepak-kumar** [comment]
I completed the task, please check it once & let me know. Actually i'm new to open source community, but well aware of android development. Thanks!

**Comment by snowtimeglass** [comment]
@s-deepak-kumar thank you for the fix. It's looks nice!
