### ISSUE TITLE
[Bug] CardTemplateBrowserAppearanceEditor follows system language instead of app

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10737]
Just noticed this is another activity with title not being translated

![2022_04_06-20_45_28](https://user-images.githubusercontent.com/69634269/162092365-6787db9f-0596-42aa-9ea4-3511a0fe315f.png)

I'll make the issue

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/10736#issuecomment-1090932897_

**Comment by s-deepak-kumar** [comment]
Please Assign It To Me.
