### ISSUE TITLE
[Bug] Review activity Menu item icon get hidden after one or two time screen rotation 

### ISSUE THREAD

**Issue by Prince-kushwaha** [ankidroid/Anki-Android#10732]
###### Reproduction Steps

1. Open Review activity and open menu item 
2. Rotation the screen one or two time

###### Expected Result
Menu item icons not get hidden

###### Actual Result

https://user-images.githubusercontent.com/65972015/162023469-65c8eb2b-8473-41eb-b914-f54cba41a328.mp4

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
can i work on this issue

**Comment by s-deepak-kumar** [comment]
I Solved This Issue, But Wanna Discuss One Thing. So, Please Let Me Know Once You Free @ShridharGoel.

**Comment by Prince-kushwaha** [comment]
@s-deepak-kumar i already working on this issue before work on issue please ask to mentor

**Comment by Prince-kushwaha** [comment]
@s-deepak-kumar above i already mention that i like to work on this issues

**Comment by s-deepak-kumar** [comment]
Sorry Bro, Actually I Was Working On Other Bugs & I Got Solution For This Bugs Too. Thats Why I Solved. But Now I Saw You Already Comented. Sorry!
