### ISSUE TITLE
[Bug] If we are on Decks/ Card Browser / Statistics screens, selecting the same from Navigation drawer should close the Navigation drawer.

### ISSUE THREAD

**Issue by UvrajSB** [ankidroid/Anki-Android#10738]
###### Reproduction Steps

1. Open any of Decks/ Card Browser / Statistics screens
2. Open the Navigation drawer
3. Select the option of the screen you are currently on. (Decks/ Card Browser / Statistics)

###### Expected Result
Navigation Drawer should get closed

###### Actual Result
It stays open

###### Debug info
AnkiDroid Version = 2.16alpha55

Android Version = 11

Manufacturer = realme

Model = RMX3151

Hardware = mt6781

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX3151 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 51f26ca3-5637-427b-a948-7e7f792958f8

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by UvrajSB** [comment]
I want to work on this issue

**Comment by UvrajSB** [comment]
Lets just take the example of gmail app 
I was on "primary screen", I opened navigation drawer and clicked on "primary" where I was already.
So navigation drawer got simply closed.
Thats what I want to do for our app in case of Decks/ Card Browser / Statistics screens

https://user-images.githubusercontent.com/73571511/162405229-ff1ab9f5-e5ca-48b9-a153-f48824dbb10d.mp4

**Comment by Arthur-Milchior** [comment]
Thanks a lot for the example. Fine by me then

**Comment by snowtimeglass** [comment]
@UvrajSB it's comfortable. Thanks!
