### ISSUE TITLE
[Suggestion] Add an Icon for Save whiteBoard Menu  option

### ISSUE THREAD

**Issue by Prince-kushwaha** [ankidroid/Anki-Android#10744]
###### Reproduction Steps

Add an Icon for Save whiteBoard Menu option like others menu option icons
![Screenshot_2022-04-07-22-31-58-534_com ichi2 anki 1](https://user-images.githubusercontent.com/65972015/162258800-8773d7fd-f76f-480a-9284-014c9ac43589.jpg)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
@david-allison @mikehardy can i this suggestion

**Comment by mikehardy** [comment]
Sure, do you have a choice for the whiteboard icon? Do we already have one we use somewhere?
Here's a good search location https://fonts.google.com/icons

**Comment by Prince-kushwaha** [comment]
@mikehardy below icons  is best for ` Save whiteboard`  menuOption 
![save_black_24dp](https://user-images.githubusercontent.com/65972015/162355521-4c810858-b8e3-4d96-bd0f-d1a66d18f54a.svg)

**Comment by mikehardy** [comment]
That looks good to me
