### ISSUE TITLE
[Bug] Requiering "Check database" on every sync

### ISSUE THREAD

**Issue by Calle92** [ankidroid/Anki-Android#10755]
###### Reproduction Steps

When I try to sync on Ankidroid it requires me to first “Check database”. After it has checked database, it requires me to do a full sync. It does this everytime I try to sync. I have done several full syncs in both directions, I have tried to re-install the app, but nothing helps.

The issue suddenly appeared yesterday, on two different Android devices (Samsung 10 + Boox Nova 3 (e-book), both running the latest version of Ankidroid. I can’t remember having done anything different before the problem appeared. Syncing on PC works as normal. 

I was told to include this link: [Anki-Android/Syncer.java at 7082f6ee93ed165180b935dbca44598a6566b3cc · ankidroid/Anki-Android · GitHub 3](https://github.com/ankidroid/Anki-Android/blob/7082f6ee93ed165180b935dbca44598a6566b3cc/AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java#L397) 

Very grateful for any help on this!

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Full syncs can be quite a pain, especially with slow media syncing on the AnkiDroid side at the moment.
That is a fantastically specific deep link to one specific line of the code here :laughing: - may I ask who directed you to include it?
Also, I fully recognize that collections can contain sensitive information so you may be unable or unwilling to share it, but the fastest way to fix this will probably be to examine your collection's anki sql database if that is possible, to see exactly what is going on and why a "check database" was unable to fix it... Is that a possibility?

**Comment by Calle92** [comment]
It was "dae" from the Anki forum (https://forums.ankiweb.net/u/dae/summary). 

Sure, I don't mind sharing it, no secrets there! https://drive.google.com/file/d/1xnYC8Ql_8hI4c93cN8Y5UJohki0UiR51/view?usp=sharing

Also, seems like I'm not the only one having this issue: https://forums.ankiweb.net/t/cannot-sync-ankidroid/18881
It also appears that the issue began at the same time for both of us. 

Thank you so much for helping!

**Comment by Calle92** [comment]
Problem seems to have been solved after instructions from @dae ! To see the instructions, go to this thread at the Anki forum: https://forums.ankiweb.net/t/syncing-issue-with-ankidroid/18853

Again, thank you so much @dae and @mikehardy for helping me solve this issue!

**Comment by mikehardy** [comment]
Ah great! For devs here: check database does fix it but then forcing a full sync up from fixed location was important, and this step may not be clear in the documentation
