### ISSUE TITLE
[Bug] Opening the filtered deck options rebuild it

### ISSUE THREAD

**Issue by WiliTest** [ankidroid/Anki-Android#10767]
I signaled the bug in [this issue] (https://github.com/ankidroid/Anki-Android/issues/5091), [mikehardy](https://github.com/mikehardy) told me to open a new issue.

###### Reproduction Steps

1. on AnkiDroid-2.16alpha55 create a filter deck with these settings: _search_= `DECK:"NewCard" is:new` //  _limit to_=`15` // _Reschedule card based on my answer in this deck_=`✔`
2. then review the first card "XYZ", set it as "good"
3. close the deck and look at the number of cards in this deck (as expected it's 14+1 red= 15)
4. But now open the option of this deck, and then close it.
5. now look at the number of card of this deck 

###### Expected Result
The number should be 15 (the filtered deck should not be rebuilt until we click on "rebuild" (the card "XYZ" should remain in the NewCard deck)

###### Actual Result
The number is 14 

###### Debug info
AnkiDroid Version = 2.16alpha55

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.79 Mobile Safari/537.36

ACRA UUID = 06e6dc69-fef2-4e49-a15a-2b41ca4d7007

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum 
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Thanks @WiliTest

**Comment by yshubham8419** [comment]
Hello @mikehardy I would like to  work on this issue

**Comment by mikehardy** [comment]
@yshubham8419 sure!
