### ISSUE TITLE
[Suggestion] Replace all the checkboxes with the toggle switches in the Preferences section

### ISSUE THREAD

**Issue by UvrajSB** [ankidroid/Anki-Android#10776]
**Is your feature request related to a problem? Please describe.**
Material uses toggles instead of checkboxes for Preferences/Settings screens
https://material.io/archive/guidelines/patterns/settings.html#settings-labels-secondary-text

**Describe the solution you'd like**
I would like to replace all checkboxes with toggle switches

Toggle Switch

![image](https://user-images.githubusercontent.com/73571511/162645745-9b77ac2a-15d8-429a-bd9b-50bac55f71cc.png)

Checkboxes

![image](https://user-images.githubusercontent.com/73571511/162645775-623150f9-3aeb-4034-96ae-4c706613f1cb.png)

**Comment by david-allison** [comment]
I suggested this.

Before we start: Let's list the UX guidelines for a toggle, and when we make each change, we should ensure that we meet these criteria

**Comment by Abhiram-DLVSS** [comment]
These might help us to set the UX guidelines for a toggle switch

1. Best practices by UX Planet - https://uxplanet.org/toggle-switch-5-simple-design-tips-for-better-design-b4046eff4a2f
2. Switches by Material Design - https://material.io/components/selection-controls#switches

**Comment by UvrajSB** [comment]
I am planning to start the changes with the "General Settings" screen of preferences.
Let's take it as the experimental screen for now and let's see if there are any issues in code implementation or UX and if we all agree on it then we will make the same changes in all the screens of preferences.
