### ISSUE TITLE
[Suggestion] Replace the string, "Add note", of Decks-screen's-add-button-menu item with "Add"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10773]
**Is your suggestion related to a problem? Please describe.**

- The shape of the current `Add note` icon doesn't look like a note, but a card.
 ![image](https://user-images.githubusercontent.com/10436072/162625001-4c78c54d-ead1-4b46-a291-099d5832cd13.png)

**Describe the solution you'd like**

- Use a more note-like icon like [the following one](https://fonts.google.com/icons?selected=Material%20Icons%3Anote_add%3A).
![image](https://user-images.githubusercontent.com/10436072/162624874-86c21f17-f391-4703-b8b0-400d5d49b8be.png)

**Describe alternatives you've considered**

- n/a

**Additional context**

- n/a

**Comment by Abhiram-DLVSS** [comment]
Can I work on this, if this issue is approved by the moderators?

**Comment by BrayanDSO** [comment]
I think the current one is better than the proposed one.

 It looks more like a card to me, and is similar to the `Create deck` and `Card browser` dialog.

To me, the `Note add` icon looks more like a `Add file`

**Comment by BrayanDSO** [comment]
I know `Note` and `Card` distinction can be somewhat confusing on Anki, but I don't think it matters much in this case

**Comment by snowtimeglass** [comment]
@BrayanDSO thank you for the feedback.

>I think the current one is better than the proposed one.

On second thought, I admit that your opinion is probably reasonable.

After all, AnkiDroid is a flashcard app. It is natural and intuitive that an card-shaped icon exists on the position. Maybe neither a  file-like icon nor a note-like icon should do on it.

It is also good to use a card-shaped icon for "Create deck", since [a "deck" is a group of cards](https://docs.ankiweb.net/getting-started.html#decks).

To use a card-shaped icon for "Card browser" is appropriate, too.

The problem is that the name of the icon in which a card has a plus mark is `Add note`. Now, I suspect that the string should not exist on the position -- just like a note-like icon. Again, AnkiDroid is a flashcard app after all.

I would like to know what you think of the alternative plan as follows.
- Keep the icon unchanged
- Rename its name (that is to say, `Add note`) "Add **card**"
- Renate the title of the current `Add note` screen "Add note **for card**"

**Comment by BrayanDSO** [comment]
TBH, I think changing `Note` for `Card` won't make a big change. Both are fine to me. If someone would change it, I wouldn't care.

Anki Desktop uses only `Add` in the option and window, so it isn't useful to follow it.

Right now, I'd leave it as is to avoid discarding the current translations

I'd only change it if there were some people really complaining about confusing cards with notes, or if it caused translations problems (which I think the translators can workaround either way).

**Comment by snowtimeglass** [comment]
I see. I'll consider about this issue for a while. Let me keep this pending. For now, I have changed the title of this issue. Thanks always for your candid feedback :-)

**Comment by mikehardy** [comment]
If Anki Desktop just uses "Add" that might actually be most useful, 1) ecosystem compatibility, and 2) no confusion about note or card! It's just "Add".

This is one of the areas of serious user confusion - I answer a *lot* of reviews where people complain "they don't know how to add a card to an existing deck". Our new user introduction system (when it eventually launches) will help a lot I think. But eliminating card/note word confusion (by just deleting that word - following Anki Desktop) might be a plus too. I think it would be worth the string re-translation cost, it really is a lot of user confusion

**Comment by mikehardy** [comment]
If you proposed a PR that switched it to "Add" - assuming that is what Anki Desktop does, by removing-string/adding-new-string we could debate on the PR, sort of a call for votes. I think that's an easy enough PR it won't represent a huge loss of time if the vote is "no"

**Comment by Shane-Patrick-Roach** [comment]
Could I be assigned to issue?

**Comment by mikehardy** [comment]
Sure @Shane-Patrick-Roach - it's a really easy change but please note my warning that could be frustrating in a way. The PR itself will be a sort of "vote" to see what other maintainers think and it may very well result in my suggestion (switch to "Add") being rejected and the PR going nowhere. But it's quick at least! :-)

**Comment by Shane-Patrick-Roach** [comment]
This was the first time exploring such a complex codebase. Thank you for the opportunity to contribute.

**Comment by mikehardy** [comment]
@Shane-Patrick-Roach sure - and don't forget that it also uses this as it's foundation https://github.com/ankidroid/Anki-Android-Backend/ which uses this as a library https://github.com/ankitects/anki/tree/main/rslib

The complexity is ridiculous :sweat_smile:

**Comment by SamarthAsthan** [comment]
@david-allison @Arthur-Milchior @snowtimeglass hey can you assign it to me i want to work on it ?

**Comment by david-allison** [comment]
Done

**Comment by mikehardy** [comment]
I believe this *may* actually be done? #11876

**Comment by SamarthAsthan** [comment]
@david-allison @mikehardy 
You see if it looks good or not, may I push it?

<img width="1440" alt="Screenshot 2022-07-23 at 11 45 36 AM" src="https://user-images.githubusercontent.com/97031010/180593069-b3a330df-b096-4c8d-8cb3-e62414b9638a.png">

**Comment by mikehardy** [comment]
I think at the end this boiled down to just the icon left as an open question

I apologize this has sat as long as it has- unfortunately we (maintainers) let the issue of whether to change the icon or not sit without really being clear.

Thinking about it now, I must admit I also prefer the current icon that is the same general card shape as the deck one
