### ISSUE TITLE
[Bug] Splash Screen takes seconds to appear

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#10789]
###### Reproduction Steps

1. take a slow phone or an emulator, and a collection with lot of cards (not necessary, but it may help)
2. ensure that ankidroid is closed
3. click on ankidroid icon on android

###### Expected Result
you'll see our logo immediately, a splash screen. Then when the app is done loading, you'll see the app

###### Actual Result
You wait during a few second with nothing ocurring. Then you see the logo a fraction of second, then the app open

##### Discussion

The logo is here so little time that I can't even screenshot it on my phone.
Ideally, it would be great if we could ensure that the logo is shown immediately, to give feedback and indicate the app is opening.
One of the main issue I have is that the profiler do not register any data before the splash screen appear, so I've never been able to figure out what is slowing us down here

**Comment by s-deepak-kumar** [comment]
Assign It To Me, Please!

**Comment by Arthur-Milchior** [comment]
You already have three issues assigned according to https://github.com/ankidroid/Anki-Android/issues/assigned/s-deepak-kumar and I don't see progress on any of them. So if you please I'd first like that you update them or relinquish them.

**Comment by mikehardy** [comment]
@s-deepak-kumar no, Arthur's comment was complete and prescriptive. Finish or relinquish existing tasks.

**Comment by mikehardy** [comment]
Possibly fixed by moving to Android 12 splashscreen style - see #10791 - I would investigate that one first and only do this if it was still slow.
