### ISSUE TITLE
[Bug] The name of "≡" button isn't correct 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10786]
Thanks to developers.

###### Reproduction Steps
1. Open any of `Decks` / `Card browser` / `Statistics` / `Study` screens
2. Long press `≡` button
 

###### Expected Result
A string which expresses the button's feature, for example, "Open drawer", gets shown. 

###### Actual Result
The string, "Navigate up", gets shown. It doesn't express the button's feature.
![image](https://user-images.githubusercontent.com/10436072/162765578-906445ab-627f-4312-a65e-f70974ffb722.png)

###### Sidenote
- The string, "Navigate up", is originally used for the following button.
![image](https://user-images.githubusercontent.com/10436072/162766865-d00cf137-9736-415f-be01-2bb01c15aa4e.png)
- The string has probably been lost on Crowdin for some reason. 

###### Debug info
```
AnkiDroid Version = 2.16alpha56

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = 69410480-0b9c-401f-ae8d-94da0f29c9dc

Scheduler = std2

Crash Reports Enabled = true


DatabaseV2 Enabled = true
```
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Propo41** [comment]
@mikehardy I'd like to work on this issue.

**Comment by david-allison** [comment]
Sounds good to me

**Comment by snowtimeglass** [comment]
@Propo41 thank you for the fix!
