### ISSUE TITLE
Update to Android 12 splash screen API

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10791]
Android 12 changed its splash screen API (https://developer.android.com/guide/topics/ui/splash-screen)

Migrating guide: https://developer.android.com/guide/topics/ui/splash-screen/migrate

With it, AnkiDroid's previous splash screen doesn't appear anymore (at least on my phone, Samsung Galaxy Note 10 Lite SM-N770F/DS, API 31, One UI 4.0)

Debug info:
```
AnkiDroid Version = 2.16alpha56

Android Version = 12

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-N770F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.79 Mobile Safari/537.36

ACRA UUID = 037bbc86-38a4-4ad7-9c42-05870e9b6086

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

![2022_04_12-08_00_45](https://user-images.githubusercontent.com/69634269/162946304-c20ac229-5c6a-46d3-8c16-4c7eff65f4c2.png)

https://user-images.githubusercontent.com/69634269/162946320-e694f320-d574-4394-9c33-247384a18321.mp4

**Comment by UvrajSB** [comment]
I have actually implemented Android 12 splash in a few apps, I am confident that I can do it but I am unable to understand the current implementation of splash screen in the app. Can anyone please help me with that, just some brief explanation of the current implementation for the splash screen required

**Comment by mikehardy** [comment]
Hey @UvrajSB, I'll give it an attempt

Control for the app starts with a launch intent here:

https://github.com/ankidroid/Anki-Android/blob/5289e3b8afe43df00e05a1c8c0573c13727854d5/AnkiDroid/src/main/AndroidManifest.xml#L83-L94

So IntentHandler is our entry point

It seems to set it's content view to a progress bar immediately

https://github.com/ankidroid/Anki-Android/blob/5289e3b8afe43df00e05a1c8c0573c13727854d5/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt#L51

https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/res/layout/anki_progress.xml

...which is just a progress bar. So I infer something must be defining the root view prior to that launching

So, that seems like a dead-end, but you get my thought process too.

Okay, so browse resources to find something named like a home screen drawable, I find:

https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/res/drawable/launch_screen.xml


...and search for usage:

```
mike@bistromath:~/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src (fix/deck-picker-androidTest) % grep -r launch_screen
main/res/values/styles.xml:        <item name="android:windowBackground">@drawable/launch_screen</item>
```

https://github.com/ankidroid/Anki-Android/blob/5289e3b8afe43df00e05a1c8c0573c13727854d5/AnkiDroid/src/main/res/values/styles.xml#L14-L16

...okay, where is that used

```
mike@bistromath:~/work/AnkiDroid/Anki-Android-Upstream/AnkiDroid/src (fix/deck-picker-androidTest) % grep -r Theme_Dark_Compat.Launcher
main/AndroidManifest.xml:            android:theme="@style/Theme_Dark_Compat.Launcher"
main/res/values/styles.xml:    <style name="Theme_Dark_Compat.Launcher">
```

...ok

https://github.com/ankidroid/Anki-Android/blob/5289e3b8afe43df00e05a1c8c0573c13727854d5/AnkiDroid/src/main/AndroidManifest.xml#L171-L176

So, the logo is in our launcher theme style, which is used for DeckPicker Activity. And IntentHandler - *if* we are headed to DeckPicker (which is the default) - will "reload" it self via an Intent to that DeckPicker, which should load that style.

Is this how splash screens should be done? I think IntentHandler is actually the one that needs the splash screen in a traditional pre-Android 12 style - this doesn't seem to match the way I have seen splash screens done before and I have done a few too.

But I think Android 12 changed things completely (if I understand from my collaboration on https://github.com/zoontek/react-native-bootsplash correctly)

So this is interesting and should help piece the current situation together, may not matter for an Android 12 style boot screen

**Comment by UvrajSB** [comment]
Not going to lie, it was really fun to read this investigation. You described it extremely well.
Coming to the actual discussion, for pre-Android 12 style I used to use the handler for splash screen but I saw a similar implementation of the splash screen in blogs bragging make a splash screen without using extra activity but haven't used it personally.

**Comment by UvrajSB** [comment]
Working on android 12 splash screen implementation

**Comment by TacoTheDank** [comment]
Bumping thread for github-actions bot.

**Comment by mikehardy** [comment]
Yes - hoping to get to this soon, just did my first full queue PR scan today and got all the easy stuff through. Time to roll up sleeves and get to work on the bigger things like this one

**Comment by mikehardy** [comment]
Relevant, just hasn't been a priority
