### ISSUE TITLE
[Suggestion] Add an icon to "Set TTS language" item of the action menu of Study screen

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10796]
**Is your feature request related to a problem? Please describe.**

On action menu of Study screen, "Save note" is going to have an icon by #10769. The other items except "Set TTS language" have already had respective icons, but "Set TTS language" item doesn't have its icon yet.
 
![image](https://user-images.githubusercontent.com/10436072/162973561-f066dcf7-1ee5-4ee3-b054-b4fd0d1c69f2.png)

**Describe the solution you'd like**

Add the following icon to "Set TTS language" item.
![image](https://user-images.githubusercontent.com/10436072/162971946-475327fe-8fb3-4a13-9313-797f0dff4884.png)
https://fonts.google.com/icons?selected=Material%20Icons%3Alanguage%3A

**Describe alternatives you've considered**
n/a

**Additional context**
When "Save" and "Set TTS language" have respective icons, this ”Add an icon” work on the action menu of Study screen gets completed (at least on the main menu).

**Comment by snowtimeglass** [comment]
@Prince-kushwaha thanks for your prompt candidacy. That's very fine with me, of course :-)

**Comment by Prince-kushwaha** [comment]
@mikehardy can i work on this suggestion

**Comment by mikehardy** [comment]
Sure, the proposed icon seems fine to me as well

**Comment by adinayyu** [comment]
I am adithya from India and as part of gsoc 2022 i want to work on visual editor project. To contribute to ankidroid i want to work on this issue. How to work on this issue and this is my first issue

**Comment by mikehardy** [comment]
Hi @adinayyu! You can look at previous PRs doing similar things - there have been icon additions quite recently. Here is a search of PRs for "add icon" and in that list are some examples

https://github.com/ankidroid/Anki-Android/pulls?q=is%3Apr+add+icon

**Comment by snowtimeglass** [comment]
@Prince-kushwaha thank you for the fix. It looks nice!
