### ISSUE TITLE
[Bug] Immediately after tapping AnkiDroid-App-shortcut-menu items, unnecessary and insipid screens get shown   

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10792]
Thank you always, developers.

###### Reproduction Steps

1. Long tap AnkiDroid App icon
2. Tap any AnkiDroid shortcut items
![image](https://user-images.githubusercontent.com/10436072/162961314-088a896f-f0f4-41d8-9573-255b7a83ace1.png)

###### Expected Result
Before the intended screens get shown, nothing happens or AnkiDroid splash screen gets shown.
![image](https://user-images.githubusercontent.com/10436072/162959920-1631c5e8-bd26-4816-b9a5-7ec11b2b6bec.png)

###### Actual Result

The following unnecessary (for users) and insipid screens get shown respectively.
![image](https://user-images.githubusercontent.com/10436072/162960218-b2104f24-2666-4eb5-844a-32f14a5cee88.png)

![image](https://user-images.githubusercontent.com/10436072/162960249-b5b24444-df32-49f9-a1b1-ab2666a7a87e.png)

![image](https://user-images.githubusercontent.com/10436072/162960311-f19eb79d-9542-4557-926a-91dea136be4d.png)

https://user-images.githubusercontent.com/10436072/162960447-97792567-2b93-4855-ac72-d1d4255639d9.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha56

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = 69410480-0b9c-401f-ae8d-94da0f29c9dc

Scheduler = std2

Crash Reports Enabled = true


DatabaseV2 Enabled = true
```
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by n1snt** [comment]
Hey, can I try to solve this issue?

**Comment by snowtimeglass** [comment]
@n1snt thanks a lot! It's so cool!
