### ISSUE TITLE
[Bug] Card Browser - "All Decks" Appears twice

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#10800]
###### Reproduction Steps

1. Open Card Browser
2. Open Deck Selection

###### Expected Result

3. "All Decks" should appear once

###### Actual Result

3. "All Decks" appears twice

###### Debug info
```
AnkiDroid Version = 2.16alpha55

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.79 Mobile Safari/537.36

ACRA UUID = 3e7c4ead-530d-4748-9f4f-622f9f619871

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
I'd expect that this is caused by 750abd2c49a44f23295e3f50a50d631de822bb2d (my fault). Needs a unit test if so.

**Comment by david-allison** [comment]
Ignore me... had a deck at the top of the list named 'All Decks' :/

**Comment by mikehardy** [comment]
Was indeed your fault haha
Who makes a deck called All Decks !?

**Comment by oakkitten** [comment]
I also have a deck named “All Decks”. I think AnkiDroid added it somehow :s

**Comment by divyansh-dxn** [comment]
Happened with me as well. I was thinking it was due to my changes and I have done something wrong. I was quiet frustrating because I hadn't touched this part of code, so possibly it could happen.

**Comment by divyansh-dxn** [comment]
Trying to fix, is just a simple one.
