### ISSUE TITLE
[Suggestion] Add two more choices to the item of "Deck options" on the setting of "App bar buttons"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10815]
**Is your suggestion related to a problem? Please describe.**

Now, AnkiDroid has already had the icon for "Deck options" by #10735 (thanks @s-deepak-kumar); nevertheless, it is impossible to show it on App bar yet since the item of "Deck options" has been given only two choices as follows.
![image](https://user-images.githubusercontent.com/10436072/163191651-005f2fd6-ca99-40bf-840a-d9afd8a71725.png)

(`Settings` -> `Reviewing` -> `App bar buttons` -> `Deck options`)
 

**Describe the solution you'd like**

Add the following two choices to the item of "Deck options".
![image](https://user-images.githubusercontent.com/10436072/163191189-2e7c2a4b-7933-4ce0-bcc4-4d9f48fe272f.png)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mikehardy** [comment]
Good point / Good idea. As long as it defaults to it's current setting ("Menu only"?) it shouldn't be a change for existing users but will allow it as a new feature in the app bar

**Comment by SySagar** [comment]
I want to work on it

**Comment by david-allison** [comment]
> I want to work on it

There's already a PR in for the issue. Could you pick an issue which people aren't working on?

**Comment by SySagar** [comment]
> > I want to work on it
> 
> There's already a PR in for the issue. Could you pick an issue which people aren't working on?

There aren't many ui related issues so I thought since this is open so I  thought to give it try

**Comment by snowtimeglass** [comment]
@sauravrao637 thank you for the fix!
