### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by aliffhasf** [ankidroid/Anki-Android#10837]
When choosing a form to fill in the blank when I want to select the text which want to hide, it closes suddenly

**Comment by david-allison** [comment]
> When choosing a form to fill in the blank when I want to select the text which want to hide, it closes suddenly

You should fill out the 'bug' template. Especially 'Settings - Advanced - About AnkiDroid' - Copy Debug Info

If you're on a Xiaomi phone, the Android 12 update is broken. Either use [our alphas](https://github.com/ankidroid/Anki-Android/releases), roll forward, or roll back your OS update.

**Comment by aliffhasf** [comment]
Yes, my device is Xiaomi and now it is updated to version 13 ،Was it because of the new update?

**Comment by david-allison** [comment]
> Yes, my device is Xiaomi and now it is updated to version 13 ،Was it because of the new update?

Yes. Use our alphas (linked above) if you can't remove or go forward to a non-buggy version.

**Comment by aliffhasf** [comment]
Thank you very much, the problem was solved after installing the alpha version.

**Comment by aliffhasf** [comment]
Do I download new updates from this alpha or will I be satisfied with what I have now?

**Comment by david-allison** [comment]
> Do I download new updates from this alpha or will I be satisfied with what I have now?

Once a month, check back to see if we move on to AnkiDroid 2.17 alphas.

When this happens, 2.16 will have been released, and you can go back to the Play Store.

OR: You can download the Parallel.A alpha, and your regular non-alpha AnkiDroid will update once we release on the Play Store
