### ISSUE TITLE
[Feature Request] Custom Math Delimiters for Mathjax

### ISSUE THREAD

**Issue by oscarmohr** [ankidroid/Anki-Android#10846]
**The Problem**
The Mathematical community mostly uses `$ MATH HERE $` - math delimiters, both in TeX and in Markdown. The standard delimiters for Maths in Anki however use `\( MATH HERE \)`.

I have 1000s of pages of mathematical content in `$`-delimiters.

It is not feasable to process these to use `\( ... \)` delimiters.

**Workarounds don't work anymore**
A common workaround used to be to run a script in the card template that calls `MathJax.Hub.Config(.)` after loading the note. That worked on both Anki and on Ankidroid. It is documented by [Niklas Korz](https://niklaskorz.de/2017/06/studying-mathematics-with-anki-and-mathjax.html).

With the recent update of Mathjax in Ankidroid, this does not work anymore.

A new workaround on Desktop is changing the file

`/usr/share/anki/bin/aqt_data/web/js/mathjax.js`

in which we update `window.MathJax.tex.inlineMath`:

```
window.MathJax = {
    tex: {
        inlineMath: [["$", "$"], ["\\(", "\\)"]],
        // inlineMath: [["\\(", "\\)"]],
        displayMath: [["$$", "$$"], ["\\[", "\\]"]],
        // displayMath: [["\\[", "\\]"]],
        ...
```

**However** on Ankidroid, there is no such way to change the Math delimiters.

**Possible Solution**
Add advanced option in settings in which a custom value for `window.MathJax.tex.inlineMath` and `....displayMath` can be set.
These values can be set in the file [`AnkiDroid/src/main/assets/mathjax/conf.js`](https://github.com/ankidroid/Anki-Android/blob/7082f6ee93ed165180b935dbca44598a6566b3cc/AnkiDroid/src/main/assets/mathjax/conf.js)

Simply giving the user checkboxes to choose exactly one or both of the delimiter syntaxes and having the file be loaded according to these user settings would alleviate this issue.

[Relevant Mathjax Documentation](https://docs.mathjax.org/en/latest/web/configuration.html)

**Comment by mikehardy** [comment]
Hey @oscarmohr ! Can I ask why Anki Desktop does not just support this by default? Has it been requested + discussed as a feature / change at https://forums.ankiweb.net ? We'd like to stay as close as possible to desktop - maintaining differences is very difficult for us, and in fact our Mathjax implementation is ideally just a copy of the exact Desktop code/bundle

Incidentally, it seems like it would be possible to re-config mathjax in the card template - it's possible to execute arbitrary javascript in there, and there is a reasonable (in my experience? hopefully?) development experience like so:

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection
Examples of JS execution in card template: https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

**Comment by oscarmohr** [comment]
Thanks @mikehardy for your swift reply.

It is indeed better to stick with the official Anki provided MathJax assets.
Anki advises to avoid changing these delimiters because of Anki note text processing internals.


I have actually found that the API change of MathJax does in fact not prevent the MathJax configuration to be reconfigured in the card template after Anki has been loaded, as I initially misunderstood.


The problem was, that after MathJax was loaded by the local MathJax config files, neither changing `window.MathJax.tex.inlineMath` (as in the local config), nor `MathJax.tex.inlineMath` in a `<script>`-tag in a card template provided the wanted results.


The values to be modified from the card template are now `MathJax.config.tex.inlineMath`

Therefore changing the MathJax config with a `<script>`-tag in the card template now works again by inserting
```
<script>
MathJax.config.tex.inlineMath = [['$', '$'], ['\\(', '\\)']]
MathJax.config.tex.displayMath = [['$$', '$$'], ['\\[', '\\]']]
</script>
```

Herewith this issue is solved.

Thanks a lot!

**Comment by mikehardy** [comment]
Oh that's excellent, I'm glad you found a solution! We definitely want to stick with compatibility *by default* but as you can see the system is kind of wide open internally, and I'm happy it was open enough for you to use all your existing mathjax material. Cheers!
