### ISSUE TITLE
[Bug] Crash: Studying all "due" cards started from "Study" shortcut ends up closing AnkiDroid without returning to Decks screen with "Congraturations!" snackbar

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10841]
###### Reproduction Steps

1. On Decks screen, tap a deck which has one or more "due" cards
![image](https://user-images.githubusercontent.com/10436072/163351938-86812ee0-859a-4b64-80de-68df6c191bf0.png)
 (Then, Study screen gets shown)
![image](https://user-images.githubusercontent.com/10436072/163351672-fa9dbe7a-e4a4-4a15-8e0d-f660c60056fe.png)
2. Go back to Android Home screen
 (ex. press Back button twice [or more if necessary] )
3. Long tap (press) AnkiDroid app icon
4. Tap `Study` on the shortcut menu.
![image](https://user-images.githubusercontent.com/10436072/163318567-d8968c4b-cb99-4942-8931-e9abdde5cf1c.png)
 (Then, Study screen gets shown again)
![image](https://user-images.githubusercontent.com/10436072/163352221-5bf71642-42d0-416e-a3c0-c8cc697f2bc8.png)
5. Answer all "due" cards in the deck.
![image](https://user-images.githubusercontent.com/10436072/163356255-dfaa5a94-26b4-425e-b230-b20d80ee0531.png)

###### Expected Result
Decks screen with `Congratulation! You have finished for now.` snackbar gets shown.
![image](https://user-images.githubusercontent.com/10436072/163355790-61d53bff-3209-4fdd-805b-82206157496b.png)

###### Actual Result
AnkiDroid "crashes". I mean, it closes unexpectedly without any explanation.
![image](https://user-images.githubusercontent.com/10436072/163362161-6f0a661c-d884-4c66-b14f-1a4db4deed55.png)

https://user-images.githubusercontent.com/10436072/163378134-a9eb0498-900a-41a8-bbfc-e060ab6e18b7.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha56

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = 69410480-0b9c-401f-ae8d-94da0f29c9dc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release 
  (2.16alpha58)

**Comment by mikehardy** [comment]
Just as a guess - the fix for #10840 may fix this one at the same time, they *seem* like they have the same root cause

**Comment by raymondwzeng** [comment]
Currently looking into this + the linked issue.

**Comment by fred-sab** [comment]
Hi all, I had look at #10840 and #10841 and thought of another approach: displaying a Toast on exit (actually  [suggested in the original feature](https://github.com/ankidroid/Anki-Android/issues/8648#issuecomment-822581182)).
It would look like this: #11547. What do you think?
