### ISSUE TITLE
[Bug] On Deck overview screen, the name of the left arrow button on the left end of Actionbar can't be shown

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10895]
###### Reproduction Steps

1. On Decks screen, tap a counts area of a deck which has "due" cards at the moment  
   (Then, Deck overview screen gets shown)　
2. Long-tap the left arrow button on the left end of Actionbar
![image](https://user-images.githubusercontent.com/10436072/163677518-07dcd222-2996-491e-bbc2-dbe6b882484b.png)

###### Expected Result

The name of the button (action), that is, "Navigate up", gets shown.
![image](https://user-images.githubusercontent.com/10436072/163677223-fcd0a0d2-4619-492e-8e34-d0294ed16e7f.png)

###### Actual Result

The name of the button (action), that is, "Navigate up", doesn't get shown.
![image](https://user-images.githubusercontent.com/10436072/163677293-a9c6375f-eba6-4c26-a7c2-a3f3c7ef4792.png)
###### Debug info
```
AnkiDroid Version = 2.16alpha58

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Mobile Safari/537.36

ACRA UUID = eebcb40f-3377-438f-afa3-59d9cae062bc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by MrPenguins** [comment]
Hey, may I work on this issue?

**Comment by david-allison** [comment]
Sure!

**Comment by snowtimeglass** [comment]
@MrPenguins thank you for the fix and checking it thoroughly!
