### ISSUE TITLE
[Suggestion] Add two more choices to the item of "Set TTS language" on the setting of "App bar buttons"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#10917]
**Is your suggestion related to a problem? Please describe.**

Now, AnkiDroid has already had the icon for "Set TTS language" by #10796 (thanks @Prince-kushwaha); nevertheless, it is impossible to show it on App bar yet since the item of "Set TTS language" has been given only two choices as follows.
![image](https://user-images.githubusercontent.com/10436072/163721016-5d5c46f6-1366-4f9b-a326-42d293d6e966.png)
(v2.16alpha59 -> `Settings` -> `Reviewing` -> `App bar buttons` -> `Set TTS language`)
 

**Describe the solution you'd like**

Add the following two choices to the item of "Set TTS language".
![image](https://user-images.githubusercontent.com/10436072/163191189-2e7c2a4b-7933-4ce0-bcc4-4d9f48fe272f.png)

**Describe alternatives you've considered**
n/a

**Additional context**
This issue is identical to #10815 except for the item (icon) and the version of AnkiDroid.

**Comment by Prince-kushwaha** [comment]
@snowtimeglass if mentor accept this suggestion then i like to work on this issue

**Comment by snowtimeglass** [comment]
@Prince-kushwaha thank you always. That sounds good to me :-)

**Comment by adinayyu** [comment]
I am adithya from india and how can i work on this issue. Where is the source code available for this

**Comment by Elizalll** [comment]
Hello @snowtimeglass , could I work on this issue? 🌹Thank you, I will try my best.

**Comment by Prince-kushwaha** [comment]
@mikehardy can i work on this suggestion

**Comment by snowtimeglass** [comment]
@Elizalll thank you for fixing this issue so patiently. You've been very helpful!
