### ISSUE TITLE
App does not prevent creating same question multiple times

### ISSUE THREAD

**Issue by vinaydeepkaur** [ankidroid/Anki-Android#10932]
###### Reproduction Steps

1.  Launch AnkiDroid.
2.  Click on the "+" button on the bottom right corner.
3.  Select " Create Deck"
4. Enter the name of the Deck.
5. Long press the created Deck and select "Browse deck"
6. Click on "+" on the top bar to add questions and answers.
7. for "front" enter "sameText" and enter some answer for it.
8. click on "+" again and add another question and answer with the same text as in step 7.

Observation:
Multiple questions with same text get created.
The textbox color of front changes to red while creating a new question with the same text but does not prevent user from repeating the question or show an error message to indicate the exact problem. 

Expected: 
It will be helpful if the user cannot create same question twice and is show an error message instead.

**Comment by mikehardy** [comment]
Hi there!
We warn the user, but we do not stop them - it is the difference between being helpful and being paternalistic.
The user may have valid reasons for entering the text multiple times, for instance if they are studying multiple languages and need to enter the same English word for two notes, but one note has French back, and one note has German back.
