### ISSUE TITLE
[Bug] Crash: Help dialog - Don't keep activities

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10942]
###### Reproduction Steps

1. Have Don't keep activities enabled
2. Open help dialog (on the navigation drawer)
3. Minimize the app
4. Open it again

###### Expected Result

No crashes

###### Actual Result

Crash

###### Debug info
```
AnkiDroid Version = 2.16alpha60

Android Version = 12

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-N770F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.88 Mobile Safari/537.36

ACRA UUID = 037bbc86-38a4-4ad7-9c42-05870e9b6086

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
https://user-images.githubusercontent.com/69634269/163864071-96e23d16-c96a-496d-80be-2819fd9c8ca3.mp4

**Comment by Prince-kushwaha** [comment]
@david-allison can i work on this issue

**Comment by david-allison** [comment]
Sure
