### ISSUE TITLE
Remove the "Easy" and "Hard" buttons

### ISSUE THREAD

**Issue by nzarbayezid** [ankidroid/Anki-Android#10961]
as you may already know there are a lot of people using Anki for learning languages using the sentences mining with Anki.
most of us the method we are using a method that we don't use HARD and EASY at all, in fact using it will break the method we are using, on desktop we have an [addon ](https://ankiweb.net/shared/info/876946123 )that let us hide the HARD and EASY button,
you may look into it on google how many people using sentence mining for learning languages with Anki that we don't use the HARD and EASY buttons, so maybe you can add a feature that let us hide those two buttons in the settings, cuz we do not have to press these two bottom by miss clicking or otherwise, it will break our flashcard methood.
I hope you can hear us out, thanks 🙏

my PC Anki

![image](https://user-images.githubusercontent.com/101425664/163928870-d8650cb1-45b1-4428-bc28-96a7d9718b7e.png)

my mobile Anki

![Screenshot 2022-04-19 083732](https://user-images.githubusercontent.com/101425664/163930082-372d1c70-9d67-4436-901f-9171bf7f4fa0.png)

**Comment by krmanik** [comment]
Hi, using JS API. It is possible to remove `Easy` and `Hard` buttons. 
https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

Also JS Addons are in development so the addons to hide buttons will be available also.

**Comment by mikehardy** [comment]
You can use the JS addons if you like, but with apologies @nzarbayezid we support stock Anki features and will not deviate from that. This would specifically break anki functionality and thus will not be implemented

**Comment by nzarbayezid** [comment]
thanks, I found a way to implement that in the current version, I just turn off the screen button and use the gesture to choose only the buttons no1 and no3

**Comment by santiyounger** [comment]
> thanks, I found a way to implement that in the current version, I just turn off the screen button and use the gesture to choose only the buttons no1 and no3

that's a good idea! can you help me find where to turn off "screen button" in the ankidroid settings?

thanks

**Comment by nzarbayezid** [comment]
> > thanks, I found a way to implement that in the current version, I just turn off the screen button and use the gesture to choose only the buttons no1 and no3
> 
> that's a good idea! can you help me find where to turn off "screen button" in the ankidroid settings?
> 
> thanks

Anki>settings>reviewing>fullscreen mode>hide the system bar and bottoms

**Comment by santiyounger** [comment]
> > > thanks, I found a way to implement that in the current version, I just turn off the screen button and use the gesture to choose only the buttons no1 and no3
> > 
> > 
> > that's a good idea! can you help me find where to turn off "screen button" in the ankidroid settings?
> > thanks
> 
> Anki>settings>reviewing>fullscreen mode>hide the system bar and bottoms

great got it! thanks a lot!

**Comment by crackwei** [comment]
> Hi, using JS API, it is possible to remove `Easy` and `Hard` buttons. https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API
> 
> Also JS Addons are in development so the addons to hide buttons will be available also.

Hi, could you please teach how to hide special button real time. I want to set some options in front, and if choose the wrong, then hide "good" and "easy" button, only show "hard" and "again" button. but I read the document, it don't say how to do, only a paragraph say:
`Return time for next review. Time at answer buttons (Again/Hard/Good/Easy/). It can be used to hide button if returned string is empty.

console.log(AnkiDroidJS.ankiGetNextTime1());
console.log(AnkiDroidJS.ankiGetNextTime2());
console.log(AnkiDroidJS.ankiGetNextTime3());
console.log(AnkiDroidJS.ankiGetNextTime4());
`

it seems that this can't solve my problem

**Comment by 825i** [comment]
> > > thanks, I found a way to implement that in the current version, I just turn off the screen button and use the gesture to choose only the buttons no1 and no3
> > 
> > 
> > that's a good idea! can you help me find where to turn off "screen button" in the ankidroid settings?
> > thanks
> 
> Anki>settings>reviewing>fullscreen mode>hide the system bar and bottoms

This no longer exists and having the hard and easy buttons is absolutely horrible. Is there any clear way to do this on Ankidroid? It's absolutely maddening this isn't a feature.
