### ISSUE TITLE
[Feature request] `Add note` gesture

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#10976]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to add notes while I'm on the reviewer. There is a `Add note` app bar button, but there isn't an equivalent gesture

**Describe the solution you'd like**
Add a `Add note` gesture

**Describe alternatives you've considered**
None

**Comment by BrayanDSO** [comment]
And I'd like to do it if it is accepted

**Comment by david-allison** [comment]
🚀 🚀
