### ISSUE TITLE
[Bug] Multiple blank deck created on tapping `::Test` deck name

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#11026]
###### Reproduction Steps

1. Create deck with `::Test` deck name
2. Click on blank space row

https://user-images.githubusercontent.com/12841290/164760901-60f14e17-020a-4a15-964b-6b95e6757382.mp4

###### Expected Result
It should prompt for empty parent deck name error or should follow AnkiDesktop. It should add `blank` deck name then `Test` subdeck name.

###### Actual Result
1. Creates empty name deck
2. Click on it create decks with blank name
3. Reopen AnkiDroid, it adds multiple `blank+++` deck

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
```
AnkiDroid Version = 2.16alpha61

Android Version = 11

Manufacturer = samsung

Hardware = exynos9611

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-M307F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.88 Mobile Safari/537.36

ACRA UUID = 28d6a8ba-00ba-404c-ab99-9386ecacef65

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### AnkiDesktop Result 
![image](https://user-images.githubusercontent.com/12841290/164761578-03b1c326-f3ba-4074-b621-ff57af3711bb.png)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by krmanik** [comment]
May be this is the issues.
https://github.com/ankidroid/Anki-Android/blob/06e5b4210f6e3f53dd4252ab3faa6733f69ec968/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java#L1223-L1225

**Comment by Sustech-yx** [comment]
> May be this is the issues.
> 
> https://github.com/ankidroid/Anki-Android/blob/06e5b4210f6e3f53dd4252ab3faa6733f69ec968/AnkiDroid/src/main/java/com/ichi2/libanki/Decks.java#L1223-L1225
> 
> https://github.com/ankidroid/Anki-Android/blob/06e5b4210f6e3f53dd4252ab3faa6733f69ec968/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt#L78-L91

Yes... It seems that such bug appear when a parent with `""` as its name, and when click the deck bar, the deck named `"blank"` will be created. Could you assign this issue to me? @mikehardy

**Comment by Sustech-yx** [comment]
![report](https://user-images.githubusercontent.com/59305237/164879111-d6876084-dbee-4f30-8c78-1af90d3bfbb8.gif)
@mikehardy I fix this through adding a check when enseure the parents of deck. However, it seems that when try to adding another deck named `"::anotherTest"`, the new deck will be added into the folder named `"blank"` insteadof `"blank+"`. Is such approach ok? Thank you.

**Comment by Sustech-yx** [comment]
The pull request is added #11045
