### ISSUE TITLE
[Bug] New cards don't go to its set location

### ISSUE THREAD

**Issue by acmd7** [ankidroid/Anki-Android#11024]
Whenever I add a new card to a selected deck, it saves to a different deck. I already updated my ankidoid version. I still can't figure out what's wrong with my Anki. It used to work smoothly. Please help me..

https://user-images.githubusercontent.com/104205377/164715478-6b61b2f0-fd45-4bf8-95d5-d391ee696780.mp4

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.15.6

Android Version = 12

Manufacturer = samsung

Model = SM-T975

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-T975 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.127 Safari/537.36

ACRA UUID = f7147a16-eb75-45ca-bb9b-51ccc4a5fbef

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

https://user-images.githubusercontent.com/104205377/164713873-b98cbbe3-5d1d-4e50-ab14-a54ede5528ea.mp4

**Comment by mikehardy** [comment]
Thanks for posting this! Sorry it is still happening. The screen recording definitely shows it!

I see this:

> AnkiDroid Version = 2.15.6

Can I ask you to try with a parallel install of our newest alpha? Choose the `.A` version and it will install side-by-side with your current stable version, we can see if this is already fixed in current code

https://github.com/ankidroid/Anki-Android/releases

**Comment by acmd7** [comment]
I can't find the alpha version

**Comment by mikehardy** [comment]
Strange, it's at the top of that page? Anyway, here's the direct link https://github.com/ankidroid/Anki-Android/releases/download/v2.16alpha61/AnkiDroid-2.16alpha61.parallel.A.apk

**Comment by mikehardy** [comment]
Dang!! Well, I was hoping it was fixed, I can imagine this is really frustrating. I'll flag it up for triage

**Comment by acmd7** [comment]
It also happens with my Anki on windows. There must be something wrong with my settings? Idk. I can't remember changing anything there. Is there a reset for the settings?

**Comment by mikehardy** [comment]
Hmm - I don't think so, but that's a great clue - that it is happening in windows too. You might check with them at https://forums.ankiweb.net - it may be that someone else has experienced this and has a solution.

It may be that running database check from deck list could help, but that's kind of a "reboot" sort of vague solution.

I've never personally encountered this so I'm not sure exactly what is going on.

If no one knows anything on forums.ankiweb.net *and* your collection doesn't have personal / sensitive info, we may be able to figure out what's happening if you could upload your collection here (or on forums.ankiweb.net for triage (https://docs.ankiweb.net/exporting.html#collection-colpkg).

@dae have you ever seen new cards going to the wrong deck on Anki Desktop? Not sure what version @acmd7 is on but this is a first for me but is likely in the rust code somewhere if it's on both platforms, and perhaps you've already seen it + fixed it?

**Comment by krmanik** [comment]
Can you check the Deck Id for both and paste it here?
It may be related to id but not sure.

**Comment by krmanik** [comment]
It is not related. I have tested it. You can wait for other developer comments.

**Comment by david-allison** [comment]
@acmd7 What's the value of:

`Settings - General - Deck for new cards`

Do you have a deck override set for the card:

* `Add Note - Tap "cards" - click the "..." menu - Deck override`

**Comment by acmd7** [comment]
Q1- The Deck for new cards were set to "Decide by note type" because I can't change it to "Use currenr deck" for some reason it just goes back to the same setting.

Q2 - My Deck Override was ON! I turned it OFF and my problem was solved. 😭

FINALLY GOT THE SOLUTION!!
Thank you, @mikehardy and @david-allison for helping. 🙏🏻
