### ISSUE TITLE
[Feature] Lazy media sync

### ISSUE THREAD

**Issue by yoshi314** [ankidroid/Anki-Android#11042]
The initial media sync or sync when introducing a deck with a huge amount of media files is very annoying on mobile - especially if you  have a device with a bit slower storage/network connection.

A feature that would be nice to have would be "lazy media sync". That means, syncing media only for immediately due cards, up to user-defined limit. Or for cards that are due within the next N days. E.g. no more than 500 media files for due cards within the next week. 

This would slowly incrementally sync the media for the collection, possibly reducing load on Anki servers and reducing wait times for users when syncing (especially initially).

If user somehow shuffles their card review order, re-running sync will fetch the missing media for those cards. It seems like a practical solution to me - if technically feasible.

Alternatives i considered were importing deck initially on mobile and syncing media to the anki servers from there - afaik either AnkiDroid or Anki sync up to ~5000 media files per sync session, so a partially similar solution is in place in one of those apps.

**Comment by mikehardy** [comment]
I believe when we ratched forward to a new underlying rust lib, we will move synchronization from Java to Rust, and that will allow us to do background media sync - if I understand correctly this is already in the long-term roadmap, but we need to get through scoped storage migration (#5304) first as it's a hard blocker, while contending with Google Summer of Code new contributor influx.

That will at least do the sync in the background but I am not sure it will prioritize the sync queue based on media on notes with cards due soon - that would be a nice optimization but would then be handled in the Anki Desktop repo (where the core Rust code lives) and you could inquire on https://forums.ankiweb.net then if/when implemented we would get it "for free" (plus cost of integrating new version of Anki Desktop Rust lib)

All to say: have patience :pray: but we will get there

**Comment by david-allison** [comment]
Also to note: #5304 will significantly speed up sync times
