### ISSUE TITLE
Automatic open keyboard for DeckOptions items

### ISSUE THREAD

**Issue by oyeraghib** [ankidroid/Anki-Android#11053]
**Is your feature request related to a problem? Please describe.**
Keyboard doesn't automatically opens up when you open any listed options in DeckOptions. You have to tap on the empty edit text to bring the keyboard up.  

https://user-images.githubusercontent.com/40427461/164933747-493ad4ac-c3ee-4f2b-bd06-42a9da8b9316.mp4

**Describe the solution you'd like**
Not sure but extending DeckOptions to PreferenceFragmentCompat and then overriding onResume() method like mentioned here : https://stackoverflow.com/a/59677185/9062752

**Describe alternatives you've considered**
Instead of EditTextPreferences we can create Dialogs for different options and can call the displayKeyboard() function like here #10593

**Comment by dorrin-sot** [comment]
can i work on this?

**Comment by david-allison** [comment]
Sure!

**Comment by dorrin-sot** [comment]
@david-allison Thanks. BTW if a preference is non-empty beforehand, after it has been focused, which of these behaviors is preferred?

- put cursor at the end of text
- select the whole text

**Comment by david-allison** [comment]
> @david-allison Thanks. BTW if a preference is non-empty beforehand, after it has been focused, which of these behaviors is preferred?
> 
> - put cursor at the end of text
> - select the whole text

Do a little research online, but I'd prefer end of text - it's hard to undo on an Android and it's a destructive action. I do think it's context dependent (might actually warrant analytics in the future), but let's be safe for now
