### ISSUE TITLE
[Bug] Option icons color changes on screen rotation

### ISSUE THREAD

**Issue by oyeraghib** [ankidroid/Anki-Android#11060]
###### Reproduction Steps

1. Choose any deck
2. Click on the options menu on top right 
3. rotate your phone to landscape/portrait mode

https://user-images.githubusercontent.com/40427461/164959703-76e8e2e3-0bc0-4a90-8791-4ba246c4fd75.mp4

###### Expected Result
Color of the icons should not change

###### Actual Result
icons color changes

###### Debug info
AnkiDroid Version = 2.16alpha52

Android Version = 9

Manufacturer = asus

Model = ASUS_X01BDA

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; ASUS_X01BDA Build/PKQ1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.127 Mobile Safari/537.36

ACRA UUID = e8337654-a2bd-4df5-850a-c4fe10d24fb3

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dorrin-sot** [comment]
Hi I would like to work on this though I can't find how to activate icons in action menus :(
