### ISSUE TITLE
[Bug] <style> tags in fields are ignored, which anki desktop and web do not

### ISSUE THREAD

**Issue by SimonHeimberg** [ankidroid/Anki-Android#11073]
###### Reproduction Steps

1. create a new card
2. add this to a field shown on the front side (back side would also be fine):

```
<span class="bgRed">&nbsp;red&nbsp;</span>
<style>
  .nightMode .bgRed, .bgRed { background-color: red; }
</style>
```
3. preview the card

###### Expected Result

the text "red" has red background, as it has on anki desktop and anki web.

###### Actual Result

the text "red" has no special background

(Use case: Trying to set the background color independent of the night mode. The colour seems to be inverted in ankidroid only, the hint is in anki manual, so it might not work in many ways.)

###### Debug info

AnkDroid Version = 2.15.6

Android Version = 9

Webview User Agent = Mozilla/5.0 (Linux; Android 9; GT-I9595 ...

(More info on demand, since I report the error on a desktop device.)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Edit the card template and add `.night_mode {}`.

The HTML should work. Have you checked the [HTML inspector](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection)?

**Comment by SimonHeimberg** [comment]
By looking at "card.html" I have seen that all the newlines inside the style attribute are replaced by a `<br>` tag. A style tag with `<br>` inside is invalid of course. It works when I delete all newlines in `<style>`.
Is this an effect of the setting to replace newlines? I understood it only the other way around. :-/

Thank you for the hint with `.night_mode`. I will try it.

So thank you very much. It is not an issue.

**Comment by david-allison** [comment]
@SimonHeimberg 

To confirm: is there anything actionable here that I can help with?

We have plans to both swap out the editors for a visual editor, and before then, move the 'newline' setting inside the Note Editor.
