### ISSUE TITLE
[Enhancement] Detect '0 tests' when running emulator tests

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#11078]
We were testing the API21 emulator, and it didn't run any tests, but the action passed.

We should modify the github action to check the number of tests run for emulator tests and ensure that it's greater than zero.

If it's not, fail the action

**Comment by mikehardy** [comment]
Suggested implementation is after the emulator test run, inspect the actual test results report to make sure tests executed were > 0

probably determine filename --> `cat` file --> `grep` for the results line pattern --> `cut` out the number of tests executed, test for > 0 or similar
