### ISSUE TITLE
[Bug] Add Tag Dialog - tapping a 'suggestion' on the keyboard removes the EditText value

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#11089]
###### Reproduction Steps

1. Type 'helo'
2. Tap Gboard's 'hello' suggestion

###### Expected Result

'hello' is in the EditText

###### Actual Result

'' is in the EditText

###### Debug info
AnkiDroid 2.14.0 and latest alpha

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
https://user-images.githubusercontent.com/62114487/165107767-a3c0f517-354e-45c4-9371-9fde6c7ca00f.mp4

**Comment by david-allison** [comment]
Issue is in:

https://github.com/ankidroid/Anki-Android/blob/9b3d462246b699bf91f4fdf5b5baf0786106c28b/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/tags/TagsDialog.kt#L179-L188

Debugging: the string is `help `, as it contains a ` `, it gets ignored.

Now I know the cause, I think we should leave this and some unit tests. A comment I added on https://github.com/ankidroid/Anki-Android/pull/10966 should fix this

**Comment by dorrin-sot** [comment]
> Filtering whitespace is how I'd do it, BUT:
> 
> > Now I know the cause, I think we should just add some unit tests. A comment I added on #10966 should fix this

Oh Do I just add the tests or do I fix it too?😅
