### ISSUE TITLE
[Bug] tools/migrate.sh

### ISSUE THREAD

**Issue by codingtosh** [ankidroid/Anki-Android#11102]
## About: 
migrate.sh automates the repetitive steps of our custom [Kotlin migration process](https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md). 
This works great and eases the process a lot for the most part, but: 

### Steps: 
1. Convert the file to Kotlin
2. Fix Nullity and warnings
3. Build successfully
4. Run the script `./tools/migrate.sh`

### Actual Outcome: 
```
DELETED=''
NB_DELETED=
FILEPATH=''
Deleted file is not Java
```

## Issue: Renamed instead of Deleted
If there aren't major changes to the file after conversion to Kotlin, git automatically identifies it as a rename and not the deleted(.java)+created(.kt). The script currently relies on `git status` printing deleted: "exampleFile.java", this means that in the case where git's heuristics identify the diff as a rename directly and git status prints "renamed: ../exampleFile.java -> ../exampleFile.kt , the script won't recognize any converted files. 

Example1: 
```
$ git status
On branch BasicMediaClipFieldControllerTest
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	renamed:    AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldControllerTest.java -> AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldControllerTest.kt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   AnkiDroid/src/test/java/com/ichi2/anki/multimediacard/fields/BasicMediaClipFieldControllerTest.kt

$ ./tools/migrate.sh
DELETED=''
NB_DELETED=
FILEPATH=''
Deleted file is not Java
```
```
$ git status
On branch CardInfoModelTest
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	renamed:    AnkiDroid/src/test/java/com/ichi2/anki/CardInfoModelTest.java -> AnkiDroid/src/test/java/com/ichi2/anki/CardInfoModelTest.kt

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   AnkiDroid/src/test/java/com/ichi2/anki/CardInfoModelTest.kt

$ ./tools/migrate.sh
DELETED=''
NB_DELETED=
FILEPATH=''
Deleted file is not Java
```

**I would like to work on this.** 

## Proposed Solution
Ideally, we would also want to `grep` for "renamed:" in the "git status" text, and then store it, modify it similar to how we do for "deleted:". I would have to think of the edgecases and also if I could merge both the cases somehow. I'm new to bash scripting but this shouldn't be too difficult. 

Another lazy hack would be to just call `git stash + git stash pop` from the script `IF` git status prints "renamed". After using git stash + git stash pop, git status will show it as "deleted: " and "new file: " which our script handles already. Though there is no certainty that this will work in the future or works for older versions of git. 

If this is not blocking other devs + if it is not high priority, I prefer the former approach. If not, the second approach will unblock people(if any) much sooner.

**Comment by david-allison** [comment]
@Arthur-Milchior
