### ISSUE TITLE
[nits] ./tools/migrate.sh

### ISSUE THREAD

**Issue by codingtosh** [ankidroid/Anki-Android#11100]
## About: 
migrate.sh automates the repetitive steps of our custom [Kotlin migration process](https://github.com/ankidroid/Anki-Android/blob/main/docs/kotlin-migration.md), making 2 commits, one for the actual conversion and the other one for the rename(required to maintain the VCS history of the file). 

## Nit 1: 
The commit message of the conversion commit is as follows: 
```
    refactor: Convert CardInfoModelTest.kt to Kotlin

    com.ichi2.anki.CardInfoModelTest
```

It should be `    refactor: Convert CardInfoModelTest.java* to Kotlin` instead,
just like we have for the rename commit: 

```
    refactor: Rename CardInfoModelTest.java to .kt
    
    com.ichi2.anki.CardInfoModelTest
```
## Nit 2:
Rename migrate.sh to kotlinMigrate.sh 
## Nit 3:
Reformat the code with proper indentation(using shfmt) 
Remove warnings generated by shellcheck

## Nit 4: 
I think it would be cool if we can have arguments to run unittests, ktlintchecks, emulatortests etc. for this. Those users who prefer to run the tests and checks right after the commits locally before sending in the PR, can execute this script with the desired arguments and save time. 

Example: 
```
./tools/kotlinMigrate.sh runWithUnitTests
./tools/kotlinMigrate.sh runWithEmulatorTests
./tools/kotlinMigrate.sh runWithKtlintCheck
./tools/kotlinMigrate.sh runWithKtlintCheck runWithUnitTests runWithEmulatorTests
```

This can be done by looping over the input arguments and calling the respective test/check commands if we find any of these.

**Comment by david-allison** [comment]
I'd prefer

`refactor: Rename CardInfoModelTest to Kotlin`

as it's no longer a java file.

Only bikeshedding I'll do on this, happy to see a change.

**Comment by david-allison** [comment]
@Arthur-Milchior

**Comment by david-allison** [comment]
@codingtosh thoughts on https://github.com/ankidroid/Anki-Android/issues/11100#issuecomment-1109128596

**Comment by codingtosh** [comment]
> I'd prefer
> 
> `refactor: Rename CardInfoModelTest to Kotlin`
> 
> as it's no longer a java file.
> 
> Only bikeshedding I'll do on this, happy to see a change.

@david-allison Sorry for the late reply, got a little confused. I think it may just be semantics, but imo the file is the original java file before the rename happens. Rename is the first commit, so the original message is appropriate for it and should not  be changed , i.e.,
`refactor: Rename CardInfoModelTest.java to .kt 
`
I believe you probably meant it for the second commit?
`refactor: Convert* CardInfoModelTest to Kotlin` instead?
That would make more sense than my suggested changes as the file is already a .kt file due to the first commit, we're just converting the contents(java) to kotlin.

**Comment by david-allison** [comment]
🤦  you're absolutely correct. `refactor: Convert CardInfoModelTest to Kotlin`

**Comment by codingtosh** [comment]
@mikehardy Could you please reopen this? This one has multiple nits I edited in  later on, only one has been discussed and fixed by #11111 

@david-allison @Arthur-Milchior Could you please look at the remaining nits as well?

**Comment by mikehardy** [comment]
Sure!

**Comment by david-allison** [comment]
if you want to take on 2,3 and 4, I won't oppose.

2 may slightly change workflows, but it's probably not worth working around
