### ISSUE TITLE
[Bug]Category name not displayed on app bar 

### ISSUE THREAD

**Issue by UvrajSB** [ankidroid/Anki-Android#11119]
###### Reproduction Steps

1.  Go to Preferences
2.  Click on any category 
3.  When any category is opened, ideally on the next screen the app bar title should be "the name of category" not the "Preferences" again.

###### Expected Result

<img src = "https://user-images.githubusercontent.com/73571511/165473707-1d65cf41-1843-4d0f-9f84-54414a840cac.jpeg" width = "200" height = "450"/>

###### Actual Result

<img src = "https://user-images.githubusercontent.com/73571511/165472771-478d0597-4f77-4b14-b55b-bf2134ec1033.jpeg" width = "200" height = "450"/>

###### Debug info
AnkiDroid Version = 2.16alpha61

Android Version = 11

Manufacturer = realme

Model = RMX3151

Hardware = mt6781

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX3151 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.127 Mobile Safari/537.36

ACRA UUID = 4d030ff8-bba6-40fd-a41f-645d5cc51b30

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research

As you can see on the official guidelines for the preferences the app bar's heading always displays the category name not the Preference.

https://source.android.com/devices/tech/settings/settings-guidelines

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by UvrajSB** [comment]
I want to work on this issue, I observed this issue a long time ago and I finally want to address it now.

**Comment by mikehardy** [comment]
Sure @UvrajSB - thanks!
