### ISSUE TITLE
Update FAB UI for more intuitive double tapping

### ISSUE THREAD

**Issue by winstonrc** [ankidroid/Anki-Android#11121]
**Is your feature request related to a problem? Please describe.**
A natural extension of #11085.

**Describe the solution you'd like**
I think the FAB should be updated in the app to act similarly to Google Calendar. With Google Calendar, after tapping the FAB, the FAB itself turns into the primary action to create, which not only allows for a double tap but also informs the user why double tapping would perform the function it does.

This requires animating the existing FAB to rotate, turn into the `Add note` button and rotate back into the regular FAB if backed out.

The general steps to get started with this issue are to modify `DeckPickerFloatingActionMenu.kt` by adding `mFabMain.visibility = View.GONE` to the `showFloatingActionMenu` method and `mFabMain.visibility = View.VISIBLE` to the `closeFloatingActionMenu` method? Then adjust the `Add note` icon to retain the size and position of the FAB. With a properly timed animation, the FAB would rotate into the `Add note` icon and backing out would rotate the `Add note` icon back into the FAB.

**Describe alternatives you've considered**
n/a

**Additional context**
<img src="https://user-images.githubusercontent.com/71997294/165380594-845a2a7e-3c58-4bab-9c7b-c99d528decea.png" width="195"> <img src="https://user-images.githubusercontent.com/71997294/165380606-bbf0c51f-206e-4e1b-8001-4a0d90e7c747.png" width="195"> <img src="https://9to5google.com/wp-content/uploads/sites/4/2021/09/Google-Calendar-Material-You-2.png" width="195"> <img src="https://9to5google.com/wp-content/uploads/sites/4/2021/09/Google-Calendar-Material-You-3.png" width="195">

**Comment by BrayanDSO** [comment]
Loved this. Simple, intuitive and still fast to trigger.

**Comment by mikehardy** [comment]
I like this as a refinement of #11085  as well, for what it's worth

**Comment by david-allison** [comment]
Likewise

**Comment by winstoncooke** [comment]
I think this should be reopened if someone wants to take a look at it. I don't have the time at the moment unfortunately.

**Comment by oyeraghib** [comment]
Is anybody working on this issue? If not then I would like to pick it up.

**Comment by david-allison** [comment]
Sounds good to me

**Comment by winstoncooke** [comment]
Go for it! It would be a really convenient addition.

**Comment by oyeraghib** [comment]
PR awaiting review.

**Comment by oyeraghib** [comment]
PR awaiting review.
