### ISSUE TITLE
Cannot synchronize cards anymore

### ISSUE THREAD

**Issue by Watakun7** [ankidroid/Anki-Android#11143]
Hello,
every time I try to synchronize I receive this error: "AnkiWeb encountered an error. Please try again in a few minutes, and if the problem persists, please file a bug report".
I love this application, can you please help me to fix this issue?
This is the log, tia.

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = OnePlus

Model = ONEPLUS A6013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; ONEPLUS A6013 Build/RKQ1.201217.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.127 Mobile Safari/537.36

ACRA UUID = 5f46e273-7928-4ca7-a806-224da35c2a38

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by david-allison** [comment]
Data center issue, please see this link for updates:

https://forums.ankiweb.net/t/error-ankiweb-encountered-a-problem/19528
