### ISSUE TITLE
add card filter in custom study sessions

### ISSUE THREAD

**Issue by seekingmeanings** [ankidroid/Anki-Android#11195]
I'm learning languages most of the time and using different cards in decks for different aspects.
It would be genius to create study sessions with only selected cards appearing in it.

**Comment by mikehardy** [comment]
Hi there! I'm not sure how we can support this more generally then we already do - using search based filtering on flags or tags you can tag or flag your cards based on their "different aspects", then you can use a search query for that tag or flag to create the custom study session

So I think this is already handled here pretty well - however - and almost more importantly - any change to the way custom study sessions work would start with a request upstream on Anki Desktop then if implemented their we would follow here
