### ISSUE TITLE
Automate process of updating of jquery and mathjax library in assets folder

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#11211]
**Is your feature request related to a problem? Please describe.**
The jquery and mathjax library should be updated and similar to Anki.
|.|Anki|AnkiDroid|
|:-:|:-:|:-|
|jquery|3.6.0|3.5.1|
|mathjax|3.2.0|3.1.2|

**Describe the solution you'd like**
The library should match with Anki jquery and mathjax version. Automation should be used to update the files.

**Describe alternatives you've considered**
Manually it needs to copy/paste the updated files for each release.

**Additional context**
Currently it works without any issues but we should consider this for updating it.

**Comment by mikehardy** [comment]
Hmm - good idea. For something like this I like the idea of a shell script if possible, so that it may be run locally as a "local first" development experience"
Then we can wrap the shell script in a github action just to execute it, like I did with release.sh and the translations sync
