### ISSUE TITLE
"History" in the Add Note window

### ISSUE THREAD

**Issue by euu2021** [ankidroid/Anki-Android#11213]
**Is your feature request related to a problem? Please describe.**
I'm used to creating notes in Anki desktop, and there the Add Note window has a list of recently added notes. It's useful because it's not rare for me to notice that, as I follow in the content being studied, one card that I just added needs to be corrected or complemented.

As I started using Ankidroid to create some notes, I'm missing this feature, which is vanilla in Anki desktop. 

**Describe the solution you'd like**
Having a history list of recently added notes. As I click in one item of the list, it takes me to the browser, with the given note opened.

Thanks,

**Comment by BrayanDSO** [comment]
Can you please add a screenshot here of this feature on Anki Desktop?

**Comment by eu2021** [comment]
It's a button besides the Add button:
![a](https://user-images.githubusercontent.com/77707706/166303775-66ee2063-519f-4629-9202-144d3ed41ec8.png)

When you click it, a list of recent notes added opens up:

![b](https://user-images.githubusercontent.com/77707706/166303850-a9f2bfb8-83db-4446-8cc4-709a8836377a.png)

**Comment by BrayanDSO** [comment]
I'll join this with #1377, since they all should be fixed when we move to the desktop Note Editor
