### ISSUE TITLE
After learning the filtered deck, the "empty" button is replaced by the "undo" button, and this button does not respond when clicked

### ISSUE THREAD

**Issue by sjl872964789** [ankidroid/Anki-Android#11220]
###### Description

"Filtered Deck" originally contains a "rebuild" function and "empty" function, but when you finish a filtered deck the "empty" button disappears and is replaced by an invalid button "undo".

###### Reproduction Steps

1. click "more option"
2. click "create filtered deck"
3. enter a name "test"
4. click "ok"
5. back
6. click "Clear" to clear the words you need to learn
7. Click "rebuild"
8. Click on the "study"
9. Finish studying
10. Click on the "test"
11. Click "rebuild"
12. The "empty" button is replaced by the "undo" button, which does not respond when clicked

###### Expected Result

the invalid button should not be in place of the "empty" button

###### Actual Result

After learning the filtered deck, the "empty" button is replaced by the "undo" button, and this button does not respond when clicked

###### Debug info
AnkiDroid Version = 2.16alpha63
Android Version = 11
Manufacturer = OnePlus
Model = KB2000
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 11; KB2000 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36
ACRA UUID = 32ebdbb2-6391-4ee3-b87d-c933ecae7006
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Video
https://user-images.githubusercontent.com/15941953/166639178-d7dd1170-a57f-4333-b257-243b98b14f55.mp4

**Comment by Tinkidinki** [comment]
Hey, I faced the same issue in Android 12, although in my case rather than the rebuild option, I see the "Deck options" option as shown in the image. However, upon refreshing/synchronizing the issue doesn't persist. 

<img src="https://user-images.githubusercontent.com/26631482/167305286-00b721b0-164a-4a46-a68b-fc7d8dc97f08.png" width=30% height=30%>

One way I was able to remove the issue was by removing the undo element itself from the `menu/study_options_fragment.xml` file, and code related to the undo element from `StudyOptionsFragment.kt`. 

This seems a bit destructive, but I haven't seen the undo option ever be present in the StudyOptions fragment - is removing it an issue, or is it used for something else?

**Comment by BrayanDSO** [comment]
On my daily usage, I never go to those screens, so I don't know what is the supposed use of the `Undo` button there. 

It can undo a filtered or custom study deck creation? It seems like the `Undo` toast isn't shown there (it's part of AbstractFlashcardViewer), so I can't know what is undone (is there a log for this?). If not, I don't know why it should be there.

**Comment by david-allison** [comment]
Just to note: the screen is always in view if you use a tablet.

**Comment by snowtimeglass** [comment]
@bot Hello 👋, thanks for your daily superhuman work. Please don't close this issue yet.
