### ISSUE TITLE
[Bug] CSS written for Linux desktop also applies to Ankidroid (android).

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#11272]
![test1](https://user-images.githubusercontent.com/43168745/167289682-673b4177-587c-46a2-a46b-b0dceec6b960.jpg)
![test2](https://user-images.githubusercontent.com/43168745/167289700-5a8d2bd2-cb0d-40d7-ab36-55565b573fc0.jpg)

###### Reproduction Steps

1. [Write CSS for Linux desktop](https://docs.ankiweb.net/templates/styling.html#platform-specific-css)

###### Expected Result
Ankidroid ignores CSS for Linux

###### Actual Result
Ankidroid does not ignore CSS for Linux

(Strictly speaking, Android may be Linux, but this behavior eliminates the way to specify a CSS dedicated to Linux Desktop.)
###### Debug info
DatabaseV2 Enabled = true

Crash Reports Enabled = false

Scheduler = std2

ACRA UUID = f40502af-2f2d-46a1-89bc-6b86d7fa6380

Webview User Agent = Mozilla/5.0 (Linux; Android 12; ASUS_I004D Build/SKQ1.210821.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.127 Mobile Safari/537.36

Hardware = qcom

Model = ASUS_I004D

Manufacturer = asus

Android Version = 12

AnkiDroid Version = 2.16alpha64
I don't know how to get the current debug information because ankDroid.org is down
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Will `:not(.mobile)` work?

This class was introduced in 2013, and will be a breaking change to fix (e13a901c5840720a9d56967e21eee6b6cb5be7a5), I'd prefer documenting a workaround if at all possible for the meantime.

**Comment by mikehardy** [comment]
Also, as you mention, android *is* linux

**Comment by mikunimaru** [comment]
I agree that Android is Linux, but in the [Anki manual](https://docs.ankiweb.net/?search=Linux), the term "Linux" seems to refer only to "Linux desktop".



```CSS
/* CSS for Linux desktop (but also applies to android). */
.linux .test {
  font-family: "for Linux desktop";
}

/* Create an overwrite CSS for android. */
.android .test {
  font-family: "Other than Linux desktop";
}
```

This forced override is a workaround, but it would be difficult for a template author who created CSS for Linux desktop to guess the above behavior.

**Comment by mikehardy** [comment]
The anki manual should be updated I think, I'd consider that an oversight. Android is linux as an objective fact so that selector is not specific enough

**Comment by mikunimaru** [comment]
I will try to submit the issue that there is no CSS specifically for Linux desktop in anki desktop's issue.
It is necessary to confirm that this behavior is as intended for anki desktop.

**Comment by dae** [comment]
If AnkiDroid is already applying .linux, then we can't change it without breaking compatibility, and can only update the manual to document the behaviour.

**Comment by mikunimaru** [comment]
I will submit an issue to the anki desktop side with the understanding that the android side intends to continue this specification to maintain compatibility.
(Since the essence of the problem is that there is no CSS specifically for Linux desktop, the submission itself should be valid.)

**Comment by dae** [comment]
The desktop behaviour can't change either, as we need to maintain compatibility. The only thing we can do is change the documentation.

**Comment by mikunimaru** [comment]
I think the lack of CSS dedicated only to Linux desktop is enough to deserve the submission of an anki desktop issue.
There is an option to keep the .linux class specification and create a new class only for Linux desktop.

I'll submit the issue as a lack of CSS for Linux desktop rather than a .linux behavior issue.
The reason is that even with the web rewrite, the problem of lack of CSS for Linux desktop itself still exists.

**Comment by mikunimaru** [comment]
I submitted an issue to anki desktop and it was resolved by updating the anki manual.
Thanks for suggesting a solution.

**Comment by david-allison** [comment]
Thanks! Closing as completed
