### ISSUE TITLE
Ankidroid.org is down [server compromised; reinstall in progress]

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#11273]
![image](https://user-images.githubusercontent.com/43168745/167290210-1b24561f-99b7-4858-b926-fd096174d1f4.png)

It may just be maintenance, but it could be a problem, so I am reporting it just in case.

**Comment by mikehardy** [comment]
Yes, the server was compromised Friday morning, we were working with the hosting provider Friday and Saturday to re-image it and have them put it back on the network, and today I'm going to finish reinstalling services. On the other hand it's Mother's Day here and I'm a real person with a family (implying: a wife who is a mother, so we have activities planned for the day) so it will happen with time available and not before. Hopefully quickly though

**Comment by mikehardy** [comment]
had just enough time before heading out to get the automated publish working again with ssh keypairs and set up nginx + letsencrypt etc so the manual is back up again, correctly secured, from the app and on the web

**Comment by mikunimaru** [comment]
Thanks for the quick fix.

https://ankidroid.org/docs/help.html
https://ankidroid.org/docs/manual.html

The above two links in the issue template are still 404.

**Comment by mikehardy** [comment]
Thanks for noticing that - I am not aware of all the URLs out there but it seems through various 404s (including your report) that the full set was that the docs site was available at:

ankidroid.org
docs.ankdroid.org
www.ankidroid.org

as well as all three of those names but under the /docs sub-directory as well as the root site.

I've reimplemented this last one with some nginc magic

```
