### ISSUE TITLE
Like AnkiDesktop, do not reset the interval when rescheduling a card.

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#11275]
As suggested by @mikehardy's [comment](https://github.com/ankidroid/Anki-Android/issues/9727#issuecomment-1120274472), I am opening a new issue for this. 

The problem is that when rescheduling a card, this card interval is set to the delay set in the rescheduling. If my cards' intervals are 3 months, and I set a reschedule for these cards in 4 days, these cards' intervals are now 4 days. Anki desktop doesn't do that.: it keeps the original interval. 

So, it would be nice if either the interval is never reset when rescheduling or there was a feature to choose to reset the interval or not. 

@krmanik has already done a bit of debugging in this [comment](https://github.com/ankidroid/Anki-Android/issues/9727#issuecomment-1112583275)  

This is not a duplicate of #9740 as this issue concerns the ease, not the interval.

**Comment by MagTun** [comment]
Any news on this?

**Comment by mikehardy** [comment]
Hey @dae semi-random question but related to your work on getting V3 scheduler going and purging out most libanki stuff, is this the sort of thing that will be fixed simply  integrating your work, or will there be more to do in order to get reschedule-without-changing-interval ?

**Comment by mikehardy** [comment]
Excellent - thanks for that @dae - that'll give a blueprint to any future devs that take this up, noting of course that it's blocked until we (me, really :sweat_smile: ) get a big enough time slice to do the next batch of anki -> backend -> ankidroid PR assimilation. Hopefully soon but can't make promises as our travel itinerary is objectively ridiculous (though fun)

**Comment by MagTun** [comment]
Will this be implemented?

**Comment by mikehardy** [comment]
@MagTun yes actually - we are slowly working through using the desktop code for all scheduling
