### ISSUE TITLE
[Bug]crash and exit when save empty video or audio

### ISSUE THREAD

**Issue by jyjsunny** [ankidroid/Anki-Android#11280]
###### Reproduction Steps

1. click "card browser"
2. click and choose one card
3. click "add video clip"
4. click and choose to save
5. crash and exit

###### Expected Result

Save an empty video clip, or prompt for a video clip that does not need to be saved

###### Actual Result

https://user-images.githubusercontent.com/92309998/167401873-72abc378-b0b1-4e9a-8fc1-342890984be2.mov

**Comment by BrayanDSO** [comment]
https://github.com/ankidroid/Anki-Android/blob/d26ac786508ac324424830b75715fbeb3245fa68/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/AudioField.kt#L81

audioPath is null here, hence the crash. IIRC videos uses the same. I'd do the fix after NoteEditor conversion to Kotlin is merged though, so it can be fixed there too.

**Comment by david-allison** [comment]
NoteEditor is now merged
