### ISSUE TITLE
[Bug] Android Studio Chipmunk: Duplicate content roots detected

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#11291]
EDIT: https://issuetracker.google.com/issues/220326930

2022-05-10 Marked as priority 1: https://issuetracker.google.com/issues/232007221

Upgrading to Chipmunk removes multiple methods of running unit tests with the information:

> Duplicate content roots detected: Path [/Users/davidallison/StudioProjects/Anki-Android/AnkiDroid/src/test] of module [Anki-Android.AnkiDroid.main] was removed from modules [Anki-Android.AnkiDroid.unitTest]

![Screenshot 2022-05-10 at 14 29 11](https://user-images.githubusercontent.com/62114487/167640267-0afbefe3-53d5-447c-8df8-461fc85c4ef4.png)
![Screenshot 2022-05-10 at 14 31 22](https://user-images.githubusercontent.com/62114487/167640344-d44c5d10-871e-4b1e-b1f3-06e204206ef1.png)

**Comment by mikehardy** [comment]
Did that actually break them for you ? I updated as a test and I've been running my CI-merge-train all day *after* the original message :thinking:

**Comment by Mereo4** [comment]
I have the same issue, and on my side it's actually the update of the Android Gradle plugin to version 7.2.0 that causes it.

**Comment by david-allison** [comment]
I can't run tests from the context menu, or IDE sidebar any more.

Java files are showing a message at the top of the file: `This .java file is outside of Java Source roots and won't be added to the classpath`

But running all tests from 'configuration' runs 1529 tests (correct)

**Comment by david-allison** [comment]
Bumblebee is available from: https://developer.android.com/studio/archive with no issue, but this blocks the gradle update.

Will post on the issue tracker once I re-download Chipmunk: https://issuetracker.google.com/issues/220326930

Potentially related: 
* https://issuetracker.google.com/issues/219984431 (likely related, upgarding Above Bumblebee)
* https://issuetracker.google.com/issues/232007221 (AGP 7.2.0, rather than Chipmunk)

**Comment by mikehardy** [comment]
wait for AGP 7.2.1, this bug is marked as blocker for that release upstream

**Comment by mikehardy** [comment]
I posted our repo there as a comment (comment 10) during collaboration, it appears they have cloned it, reproduced and are actively triage-ing, in other words "Yes! should see a fix for this"

> Sorry, the duplicate path issue in the project from #10 seems to be different to the KAPT one. Will investigate and update once we know more.

**Comment by mikehardy** [comment]
Triage completed there, we have work to do here. We *are* messing with 'sourceSets' in a newly-unsupported here (but long-unsupported in IntelliJ) way and need to adapt:

https://issuetracker.google.com/issues/232007221#comment13

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/b1a42c781f5bd3420d6d561b63d8bc3a9b92d812/AnkiDroid/build.gradle#L199-L203

Added in ee463c2a3e20c0a8eea3c467a37b5f1b08f73f15 (https://github.com/ankidroid/Anki-Android/pull/5249)
