### ISSUE TITLE
[CI] Hang: Restore Gradle state from cache

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#11301]
https://github.com/ankidroid/Anki-Android/runs/6365082400?check_suite_focus=true

We can probably do with a timeout on this step which is less than 30 minutes
OR: A retry

**Comment by mikehardy** [comment]
I saw a couple sub-minute ones and on main it took 2'41", timeout for 5' should be adequate.
I don't believe it's possible to do a retry on this one, the retry action I'm familiar with doesn't wrap actions only commands, and to do a retry on an action requires multiple attempts with status setting/checking (a real workflow monster with regard to code).

So just setting a timeout and failing faster, given current incidence of this one, seems like a good solution
