### ISSUE TITLE
[Automation] Remove assignees on merged Pull Request

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#11321]
Noticed this on https://github.com/ankidroid/Anki-Android/pull/11319

Related: https://github.com/ankidroid/Anki-Android/issues/10410

**Comment by krmanik** [comment]
This can be good first issues because it easier to implement using github script (label and milestone)
https://octokit.github.io/rest.js/v18#issues-remove-assignees

```js
octokit.rest.issues.removeAssignees({
  owner,
  repo,
  issue_number,
});
```

**Comment by Elizalll** [comment]
👋 hello! May I work on this issue? Thanks!🌹
