### ISSUE TITLE
[Note Editor][Toolbar]: allow custom labels to user-defined buttons

### ISSUE THREAD

**Issue by PetbkA** [ankidroid/Anki-Android#11329]
**Is your feature request related to a problem? Please describe.**
I've added `<code>`, `<ol>` and `<li>` tags to Note Editor toolbar, but they all are displayed as "1", "2" and "3". So I have to remember what every number means.

It would be nice if I could change user-defined buttons labels.

**Describe the solution you'd like**
When adding user-defined button, third field (e.g. "label") will be displayed where I can set custom label.

The problem is that only 1 or 2 characters will fit to label, so there should be:
1. Unicode symbols support;
2. Limit to length of label (e.g. 2 characters)

**Comment by david-allison** [comment]
Thanks for the report!

Already exists in our alpha: https://github.com/ankidroid/Anki-Android/releases (pick Parallel.A)

Duplicates https://github.com/ankidroid/Anki-Android/issues/9077

![image](https://user-images.githubusercontent.com/62114487/168035238-035f5732-47a4-431b-a19a-694b83bee532.png)
