### ISSUE TITLE
[Add Note Screen]: Set Deck to the one that was used on the last added note

### ISSUE THREAD

**Issue by PetbkA** [ankidroid/Anki-Android#11330]
**Is your feature request related to a problem? Please describe.**
I have two decks:
1. _English_ to learn new words in english;
2. _English Pronunciation_ to learn pronunciation of words that I already know.

Usually I'm adding words when reading articles in english and mostly adding it to the first deck.

The problem is that the deck which I studied the last is usually the second, and it's being chosen by default when I'm adding notes.

So I have to:
1. Either change _Deck_ manually on every note adding;
2. Or "study" the first deck before adding notes.

**Describe the solution you'd like**
Set _Deck_ in _Add Note Screen_ to the one that was used on the last added note, not the last deck studied

**Comment by dorrin-sot** [comment]
Hi if this is accepted, can I work on it?
