### ISSUE TITLE
[Bug] v2.16alpha65 Can't use back or return button to save changes in deck options

### ISSUE THREAD

**Issue by ThoreBor** [ankidroid/Anki-Android#11332]
###### Reproduction Steps

1.  Open the deck options
2.  Go to new cards
3.  Go to New cards/day
4. Save changes with the return button on the keyboard or back button

This also doesn't work for the other options in new cards, as well as reviews and lapses

###### Expected Result

The settings are saved and the dialog closes

###### Actual Result

Dialog stays open

###### Debug info

AnkiDroid Version = 2.16alpha65
Android Version = 11
Manufacturer = Xiaomi
Model = Redmi Note 8 Pro
Hardware = mt6785
Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Pro Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.41 Mobile Safari/537.36
ACRA UUID = 0f3adff3-464a-472b-83d4-c20017c25211
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

https://user-images.githubusercontent.com/40232329/168053473-b7cb6e00-bd35-46ce-8f19-0f54f07eaf71.mp4

**Comment by david-allison** [comment]
Double tap to close for now. Problem with displaying the keyboard

**Comment by dorrin-sot** [comment]
> Cause: [4939304](https://github.com/ankidroid/Anki-Android/commit/493930435102e0532b6b6dfcc439d4061d71ae5c) (#11087) @dorrin-sot , do you have time to look into this?

ok 😁
