### ISSUE TITLE
[Bug] Reschedule for review in x days?

### ISSUE THREAD

**Issue by dictdl30** [ankidroid/Anki-Android#11353]
Hi,
Mike Hardy told me to put my questions here as a bugreport: https://groups.google.com/g/anki-android/c/uvjkCYVUGQA

How does this Reschedule-Option (Reschedule for review in x days) work?
(1) If I reschedule one card to “10 days”... What schedule will Anki use after these “10 days”? Will it impact on the spaced repetition algorithm for this card in general or not?
(2) If I reschedule a card to “10 days”, do I see the card again in exactly 10 days or in something between 8-12 days?

Reschedule => Reschedule for review in x days:
Every card has “More options” (“3 dots” in the right upper corner, s. screenshots). You can find Reschedule at the bottom.
S. the images here: https://groups.google.com/g/anki-android/c/uvjkCYVUGQA
Thanks in advance.

**Comment by dictdl30** [comment]
Yes, I am still searching for solutions.
But it is no bug. It is a question.
Mike Hardy told me to put my questions here as a bugreport: https://groups.google.com/g/anki-android/c/uvjkCYVUGQA

**Comment by dictdl30** [comment]
the same question was here:
https://groups.google.com/g/anki-android/c/cO7oEys9BwE/m/6cv57_wPBAAJ

**Comment by eginhard** [comment]
Based on https://github.com/ankidroid/Anki-Android/blob/988033ad4fca697d83d78eff1334da38edd66b7c/AnkiDroid/src/main/java/com/ichi2/libanki/sched/Scheduler.kt#L349 rescheduling a card for review in X days should be the same as entering "X!" in Anki Desktop's "Set due date" screen, i.e. it will reappear in exactly X days and the interval is reset.

**Comment by dictdl30** [comment]
Thank you very much for your answer, eginhard!
