### ISSUE TITLE
Plugin to force portrait or landscape mode

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1138]
Originally reported on Google Code with ID 235

```
Hello,

would it be possible to add an option to lock the screen in either portrait or landscape
mode?  Sometimes the screen rotates even when I move my arm just a little.  

Do you all like to frequently switch between the modes, or do you stick with one? 
My preference is to stay in portrait mode the whole time.

Thanks!
```

Reported by `ottenlips` on 2010-10-14 07:08:56

**Comment by rlpowell** [comment]
FWIW, despite my earlier comment to the contrary, the tasker solution doesn't actually work very reliably, and I'd really like this to be an option in Ankidroid specifically.  I typically have my phone locked to portrait for this program *only*; all the other programs where it matters have the option in their settings.

**Comment by mikehardy** [comment]
A PR for this would be nice
