### ISSUE TITLE
[Bug] The basic template does not display MathJax math formulas properly.

### ISSUE THREAD

**Issue by xllhxd** [ankidroid/Anki-Android#11412]
The basic (input answer) template does not display MathJax math formulas properly.

**Comment by n1snt** [comment]
Can you show some screenshots?

**Comment by xllhxd** [comment]
![892A44380444E9F52A8E7DD367FEBAF0](https://user-images.githubusercontent.com/93316999/170012280-26ab0191-5809-4142-ade0-b2fa3d40593c.jpg)
![F24DC972A2E1A0AE7B2535F9830C78EC](https://user-images.githubusercontent.com/93316999/170012344-f851acdd-9e20-453f-8377-228078caf384.jpg)
![0FF18A5EA09BEA2F8D5787C1E3738968](https://user-images.githubusercontent.com/93316999/170012380-6af9c538-5036-43cf-914d-5302112b1884.jpg)
![28EDB99650AC8E14368E69E04FAD1B19](https://user-images.githubusercontent.com/93316999/170012406-7843c457-3239-4227-add6-d8b2e8608aed.jpg)
![52D92CC6CB38CFDF0345E5D73E068475](https://user-images.githubusercontent.com/93316999/170012430-c8e33c18-2037-4728-af00-de1c35a80c4e.jpg)
![F33EC60ABF8439078EAA37633345F8AC](https://user-images.githubusercontent.com/93316999/170012445-e4eaa5e9-84b5-4464-8303-c16f38e885fd.jpg)
![2022-05-24_18-41-47](https://user-images.githubusercontent.com/93316999/170015711-1249a13d-efaf-4df4-b2fe-20f367ee4eb0.png)
![2022-05-24_18-42-07](https://user-images.githubusercontent.com/93316999/170015896-d7f0f33e-815e-4e00-80db-6cbc8e6a14ab.png)
The default basic (input answer) template is {{front}}<hr id=answer>{{type:back}}, and if I remove the "type" it displays the formulas normally. But on Windows, the template is the same, and the formula can be displayed without deleting type, as I did in the screenshot.

**Comment by xllhxd** [comment]
This caused me a lot of confusion, and it took me almost four or five hours to discover the problem, but it may have been intentional on your part. Thank you for always maintaining AnkiDroid.

**Comment by xllhxd** [comment]
I'm sorry to bother you. I just found out that the Window version does not do the same.

**Comment by dorrin-sot** [comment]
Hi @n1snt Are you working on this? if not, I would like to have a go at it 👀

**Comment by n1snt** [comment]
@dorrin-sot I'm currently a bit busy & I'm not working on it. You can go ahead & see if you can fix this. Best of luck 👍

**Comment by dorrin-sot** [comment]
Hi @xllhxd Could you please copy paste the texts here?
