### ISSUE TITLE
Avoid `CollectionHelper.getInstance().getCol()`, save the collection instead

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11417]
In object oriented programming, statics are genally a bad idea.
We use `CollectionHelper.getInstance().getCol()` 46 times. As far as I can tell, we really rarely need it. 
It is useful if we potentially need to reload the collection if it was closed, or when the app starts. 
So, a few improvements could be:
* AnkiActivity saves the collection when `onCollectionLoaded` returns the collection. (With special care for DeckPicker since with its Collection check and its full sync, it can invalidate the collection. Replacing `CollectionHelper.getInstance().getCol()` by `.col` each time we are sure the collection was loaded first.
* In other cases, such as Card.java, just use the `col` already saved. 

Each change can be it's own PR. I love simple to review PR, and that will allow each change to be justified.

**Comment by oyeraghib** [comment]
I would like to work with this issue.

**Comment by Arthur-Milchior** [comment]
I'd prefer @oyeraghib, if you could take a look and state one or a few part of it you intend to consider. This task seems big, and I believe you can have nice PR already by just looking at one or a few task
