### ISSUE TITLE
Giving more readable names to the functions - specially in Testing

### ISSUE THREAD

**Issue by oyeraghib** [ankidroid/Anki-Android#11414]
**Is your feature request related to a problem? Please describe.**
The name of the functions specially in testing are very long, though one can read them and understand what they do but sometimes it still look a little messy to read.

**Describe the solution you'd like**
In Kotlin we can use the backticks to write the names of function in a more readable way.
For example a function in the class **CollectionTaskCheckDatabaseTest** is named as fun `checkDatabaseWithLockedCollectionReturnsLocked()` which can be written as `Check database with locked collection returns locked ()` using backticks.

**Additional context**
Doing so will not have any impact on the performance of the app but it will be helpful for the developers as it will make the code more easy to read.

**Comment by RaidenCHEN** [comment]
Hi, so here I tried to apply your suggestions to kotlin test files under directory "lint-rules/src/test/java/com.ichi2.anki.lint.rules". In case of not doing the work you wish, i didn't modify test files in "Ankidroid/src/test/java".
So, I change all kotlin functions whose name are more than three words to the format you suggested. And also I kept all method with name no more than three words in lower camel case. I guess those names are not so hard to read that we need to use backticks.

**Comment by RaidenCHEN** [comment]
If you think it's ok, i could keep on working on the rest test files.

**Comment by lukstbit** [comment]
@RaidenCHEN I think you should wait a bit. There was no approving comment yet on this issue from maintainers of the project.

@oyeraghib Note that instrumented tests from `androidTest` will show a _Identifier not allowed in Android projects_ if using backticks in method names. Should still work, but this error being displayed or having to suppress it is not that great.

**Comment by oyeraghib** [comment]
@RaidenCHEN I really appreciate the work you did. But for future purpose just make sure before you start to work with any issues, ask the maintainers to assign it to you. As it will also help others to know that you are working on it. 
Also as suggested by @lukstbit it is important that we wait for the approval of maintainers before working on this issue.

**Comment by RaidenCHEN** [comment]
Yep, my fault, I was too impatient. Thanks for your suggestions, I would be calmer next time. Apologies if i made anything that causes problem.

**Comment by oyeraghib** [comment]
No it is really fine, it didn't cause any problems :).
As a matter of fact I have been at your place too when I started out and it is really okay, we all get better by doing.

**Comment by oakkitten** [comment]
I use test methods with spaces and so far I haven't had any issues with them. Much more readable. (I don't capitalize every word because my tests are not song titles.)

**Comment by BrayanDSO** [comment]
First, how do I run a test like this on a CLI?

Overall, I like the idea. e.g. `onlyDisableWhiteboardAppearsInAppBarIfAllAppBarButtonsAreDisabledWithWhiteboard()` on `ReviewerTest` would be a lot more readable with this.

But, yes, please don't capitalize every word. English capitalizing rules are enough.

I particularly wouldn't spend time/energy changing existing tests with small or readable enough names though, because it wouldn't make a relevant difference on readability, only creating noise.

**Comment by oyeraghib** [comment]
Yeah I agree, we can use English capitalizing rules rather than capitalizing every word.

**Comment by BrayanDSO** [comment]
> https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#run-single-unit-test

I believe I wasn't clear with my question. So, further elaborating on it:

How to run a single unit test (not every one on the class) on the CLI if it has backticks and spaces on it? Do I need to wrap it on quotes? Do I need to add the backticks?

**Comment by mikehardy** [comment]
- @BrayanDSO has a great point about making sure we can still run single tests, spaces in names are problematic for this reason in filesystems and there are always workarounds and solutions but it's more junk to know, is it worth it? I personally don't think so, but don't feel strongly as long as it is possible
- also the point about not changing any existing tests is something I agree with, given I don't really think it's important, I definitely am not interested in seeing diff noise for it

Always just opinions, in the end as long as it's not a "running a single unit test regression", if people feel strongly and are actually doing the work...PRs matter a lot and comments matter a little

**Comment by oakkitten** [comment]
> How to run a single unit test

There's nothing special about it, just [spell it out with spaces](https://stackoverflow.com/a/68558101).

**Comment by david-allison** [comment]
(pinged on Discord)

This seems like busywork. I'd much rather the effort was spent on the codebase (features/fixes), or increasing code coverage. 

I feel with the current state of the codebase, test failures aren't taking enough of our time to worry about this. This proposal optimizes for the very few developers who read/break tests, rather than user experience, or general developer experience.

**Comment by Arthur-Milchior** [comment]
@oyeraghib I'd like to let you know your idea still had some applications. As @david-allison's recent PR followed it, and for the first time, I got to review test with spaces in name. https://github.com/ankidroid/Anki-Android/pull/11513/commits/a4b9b7206bf7a46a7d51a4f26edd2b0b89bfef18#diff-b9280c48c13c02c10dd594626aaacc117144a8ce8412ae2185badf5a484a5721R42
