### ISSUE TITLE
[Bug]pureAnswer not correct

### ISSUE THREAD

**Issue by captain-miao** [ankidroid/Anki-Android#11442]
###### Reproduction Steps

1. val pureAnswer = mCurrentCard!!.pureAnswer

###### Expected Result
```
    val pureAnswer: String
        get() {
            val s = render_output(false).answer_text
            val target = "<hr id=answer>"
            val pos = s.indexOf(target)
            return if (pos == -1) {
                s
            } else s.substring(pos + target.length).trim { it <= ' ' }
        }
```

###### Actual Result
```
    val pureAnswer: String
        get() {
            val s = render_output(false).answer_text
            val target = "<hr id=\"answer\">"
            val pos = s.indexOf(target)
            return if (pos == -1) {
                s
            } else s.substring(pos + target.length).trim { it <= ' ' }
        }
```

###### Debug info
![image](https://user-images.githubusercontent.com/1283212/170852522-b68c77f4-3ce9-445e-a2df-0363e935e707.png)

sorry, I can't commit by PR.

**Comment by mikehardy** [comment]
Hi there! With apologies, I don't understand what the problem is.


https://github.com/ankidroid/Anki-Android/blob/e6a1698025e3ec13a68bcdb796b5f4af9830fa76/.github/ISSUE_TEMPLATE/issue_template.md?plain=1#L25-L26

Also, you deleted the debug info we request in our template. Please include it, you may want to make sure you are testing this on the latest release https://github.com/ankidroid/Anki-Android/releases

**Comment by captain-miao** [comment]
> Hi there! With apologies, I don't understand what the problem is.
> 
> https://github.com/ankidroid/Anki-Android/blob/e6a1698025e3ec13a68bcdb796b5f4af9830fa76/.github/ISSUE_TEMPLATE/issue_template.md?plain=1#L25-L26
> 
> Also, you deleted the debug info we request in our template. Please include it, you may want to make sure you are testing this on the latest release https://github.com/ankidroid/Anki-Android/releases

```
            val s = render_output(false).answer_text
            val target = "<hr id=answer>"
            val pos = s.indexOf(target) // always pos = -1
            ...
```

**Comment by david-allison** [comment]
I believe the problem is the HTML is sometimes changed to `"<hr id="answer">"` and we also need to handle this case when detecting the answer

fb6993c15973b9b92506f12e1eb20c55c97f4208
