### ISSUE TITLE
Use `"""` instead of `"` to avoid `\"`

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11451]
One usual issue in reading code inside of code (e.g. string containing html, css, or js) is that they contains quote, which you must escape. Worst is when you want to have actual quote in the inside language. 
Kotlin offers one solution, triple quote. Let's take an example: https://github.com/ankidroid/Anki-Android/blob/8d4083e1ddbad8f0633679997a4b5b44ee88dc72/api/src/main/java/com/ichi2/anki/api/BasicModel.kt
```Kotlin
val AFMT = arrayOf("{{FrontSide}}\n\n<hr id=\"answer\">\n\n{{Back}}")
```
It would be nice to look for all \" in the code base and remove then when possible.
Simultaneously, you can add `@Language("HTML")` or any other relevant language, to ensure proper syntax coloring

So that would become
```Kotlin
@Language("HTML")
val AFMT = arrayOf("""{{FrontSide}}\n\n<hr id="answer">\n\n{{Back}}""")
```

It's cleanup, it's a matter of taste and not of absolute rules. If in some case you believe the result would be worse than the original, feel free to not make a change. As an example, we have some part in the code `"\""`, the string containing a single double-quote. You should probably leave it alone, because `"""""""` (7 double-quote), which is a valid template for the string containing a single double-quote, is far far less readable.
Each change should take less than a minute to make. If you do a PR by change, they should be merged almost immediately, so the risk of conflict and wasted work is low. You can just look below to see if someone did what you are about to do. This mean that you don't have to ask permission to work on it.

Once it is done, an extra task would be to consider adding a lint issue for escaped quote.

**Comment by SaranshBaniyal** [comment]
Hey @Arthur-Milchior, greeting. Can you please assign this issue to me? I have just started with android development and would love to get my hands-on some beginner level issue like this, in order to improve my skills.

**Comment by david-allison** [comment]
> Hey @Arthur-Milchior, greeting. Can you please assign this issue to me? I have just started with android development and would love to get my hands-on some beginner level issue like this, in order to improve my skills.

Done! et us know if you need help

**Comment by Arthur-Milchior** [comment]
any news @SaranshBaniyal ? Are you still working on it?

**Comment by SaranshBaniyal** [comment]
I'm sorry guys for my inactivity, I have been off for some time and was totally unaware that I was allotted this issue. I would still like to contribute if you guys can allow me a little more time, or if you decide to allocate this issue to someone else, that would be fine. I again apologize for my inactivity and negligence.

**Comment by SaranshBaniyal** [comment]
@Arthur-Milchior sir, I sincerely apologize but I am having a tough time understanding how to proceed on this issue after cloning the repository. I am a beginner in android dev and lack experience in real-life working projects. I would be grateful if you can just brief me on the direction to proceed or maybe you can unassign this issue and reassign it to someone else

**Comment by Arthur-Milchior** [comment]
Can ou please come on the discord, where you may get real-time help?
I don't even know what is your issue. Whether you can or can't compile. Whether you can't find the place to improve. Whether you found them but fail to improve them. etc.

**Comment by sparkyniner** [comment]
What is your discord?

**Comment by Arthur-Milchior** [comment]
https://discord.gg/qjzcRTx
You can find it from the app too

**Comment by SaranshBaniyal** [comment]
@sparkyniner AstroITNinja#3803

**Comment by SaranshBaniyal** [comment]
@Arthur-Milchior I have cloned the files, so should I start looking for " in all the Kotlin files of the codebase from start till end?

**Comment by Arthur-Milchior** [comment]
@SaranshBaniyal the comment is valid for you too. If you have question about how to proceed, I strongly suggest you to come on our discord. Because this way you can find people to answer your question very quickly instead of having to wait half a day or more that someone looking at this particular PR see you.


And no, I would not ask anyone to look at codebase from start till end. That would be an impossible amount of work to do for almost anything. Instead, I was implicitly expecting that a dev that will attack this issue would:
1. have android studio installled and be able to compile,
2. probably have knowledge of at least basic tools such as "search in the repository" (ctrl-shift-f)
3. search for occurence of `\"` in the code and
4. see whether it makes sense to replace quotes by triple quote, (in some case, maybe it's less readable to do the change. If so, let's not make it)

**Comment by SaranshBaniyal** [comment]
@Arthur-Milchior thanks for all the help, I have joined the discord server. Looking forward to a great learning experience with you all.

**Comment by Aditya8840** [comment]
Hey @Arthur-Milchior, greeting. Can you please assign this issue to me?

**Comment by SaranshBaniyal** [comment]
@Arthur-Milchior I m still learning and am unable to resolve this issue yet, I don't mind if you assign this issue to @Aditya8840 . Thanks for all the help, I wish to catch up soon and contribute to ankidroid in any way possible

**Comment by Arthur-Milchior** [comment]
Greeting @Aditya8840 . Done

**Comment by SanjaySargam** [comment]
Is this issue still open?
I would love to contribute to getting my hands free on good first issue

**Comment by Arthur-Milchior** [comment]
@SanjaySargam Welcome,
It's still open.
As far as I know, @Aditya8840 has not contacted us since the issue was assigned to them, so you certainly can go work on it.

**Comment by SanjaySargam** [comment]
@Arthur-Milchior we have to do changes only in HTML,CSS ,JS files right?

**Comment by Arthur-Milchior** [comment]
Oh no. We have very very few HTML, CSS and JS pages actually. 
What I meant is that sometime, we write some HTML directly inside of Kotlin code. And this code, may be cleaned.
I just edited the first message in this issue to add an example. For example https://github.com/ankidroid/Anki-Android/blob/8d4083e1ddbad8f0633679997a4b5b44ee88dc72/api/src/main/java/com/ichi2/anki/api/BasicModel.kt is a line that should be corrected

**Comment by SanjaySargam** [comment]
> Oh no. We have very very few HTML, CSS and JS pages actually. 
> What I meant is that sometime, we write some HTML directly inside of Kotlin code. And this code, may be cleaned.
> I just edited the first message in this issue to add an example. For example https://github.com/ankidroid/Anki-Android/blob/8d4083e1ddbad8f0633679997a4b5b44ee88dc72/api/src/main/java/com/ichi2/anki/api/BasicModel.kt is a line that should be corrected

Thank You for ur explanation ☺️@Arthur-Milchior

**Comment by BrayanDSO** [comment]
If this is going to be done, I believe that a lint rule should be used, otherwise this will be a open-ended issue that may never be completed because people may not remember to use `"""` on new PRs. 

And, to be honest, I bet that the time cost on pushing/reviewing all usages of `\"` will be way bigger than the spared time spent on deciphering that `\"` = `"`. So, I don't suggest spending time on this

**Comment by Sagar0-0** [comment]
Please close this issue! Thanks
