### ISSUE TITLE
Cleanup: avoid var

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11450]
As a general rule, `val` is better than `var`. Because that means that you can read code without having to keep track of how a value change. Even when there is no "kotlinCleanup", if you see a var and can change it to a val, it would be appreciated. 

This change has very low importance. So no need to got searching for all vars. The goal of this issue is simply to let you know that if, when you are reading/touching some part of the code base, you find some `var`, you can potentially improve the code in the ways described below. This means that if part of the code is never touched, it'll keep those var; but that's not so bad, after all, if nobody touches some code, the fact that it is not as beautiful as possible do not hurt anybody.

You can do PRs with a single change; so they 'll be easy to review, and can be merged quickly. And if they is an error, the error won't block other changes to be accepted. This also ensure PR can be merged quickly, and so there is very little risk of conflict.
You don't need to ask permission to work on this issue

This is a question of taste, and if you see a change that would leave the code uglier, don't do it, none of those changes are mandatory, and if they don't improve readability, they are not worth it.

# Hints to change var to val.

## Iteration

If a var is used to count the number of time a loop was executed, e.g. 
```kotlin
var i = 0
for (elt in elts) {
  ...
  i++
}
```
you can instead use 
```
for elts.forEachIndexed {i, elt ->
  ...
}
```
For a lot of loops, you use elt/i a single time, and so don't actually need to introduce it into a value.

## Fixed number of assignment

Some time, you'll see
```kotlin
var title = sectionTitle()
...
title = buttonTitle()
...
title = footerTitle()
```
Usually, you can simply use three distinct values ` sectionTitle`, `buttonTitle` and `footerTitle` as all of those titles are actually entirely independent and there is no reason to use the same variable

## Early return
In some old code we have
```kotlin
var x = defaultValue()
try {
if (condition) x = otherValue()
} catch (Exception e) {...}
return x
```
You can return `otherValue()` directly, and in the last case, do `return defaultValue()`. This only works if none of the function have side effect

## Use if conditional
Sometime we have
```kotlin
var x = defaultValue()
if (condition) x = otherValue()
```
you can use instead 
```kotlin
val x = if (condition) otherValue else defaultValue()
```

there are too special cases.
```kotlin
var x = defaultValue()
if (condition(x)) x = otherValue()
```
you can use instead 
```kotlin
val x = defaultValue().let {if condition(it) otherValue() else it)
```

there are too special cases.
```kotlin
var x = defaultValue()
if (x == null) x = otherValue()
```
you can use instead 
```kotlin
val x = defaultValue() ?: otherValue()
```

## other case?
If you see pattern I forgot, please add them in answer. I'll copy here.

**Comment by lukstbit** [comment]
> can you please help me to start with?

Usually when you want to start contributing to a project you would first look through its source code to get familiar with its code. Then you would pick something easy to fix, like this issue. 

This issue asks to replace(where possible) unneeded usages of `var` with `val` like the examples above show you. Then go through the source code and try to find places where `var` are used like in the examples and replace them.

**Comment by Amandeep404** [comment]
can I work on this issue?

**Comment by lukstbit** [comment]
@Amandeep404 Sure, there's no need to ask for permission. If you see places in the code base where the var usages  can be improved as mentioned above you can make a(small) pull request.

**Comment by david-allison** [comment]
I don't feel that there is an acceptance criteria for this issue. 

@Arthur-Milchior When can this issue be closed, and when can we move towards this goal?

I could potentially see annotating every current `var` with a potential `KotlinCleanup`, and then evaluating them on a case-by-case basis, but I don't know if this provides value

**Comment by Arthur-Milchior** [comment]
I did not believe that an acceptance criteria was a requirement for an issue. I was hoping it would be a way for new contributors to find some simple task to onboard and test making changes to our codebase.
if it becomes an issue because it becomes hard to find `var` that actually have reasons to be variable, then it'll makes sens to close it or think about more systematic way to annotate them.

**Comment by SanjaySargam** [comment]
is issue this still open?

**Comment by Arthur-Milchior** [comment]
It still is. @SanjaySargam

**Comment by Sagar0-0** [comment]
Please close this issue, thanks!

**Comment by mikehardy** [comment]
Not sure exactly what the criteria to close here should be

**Comment by BrayanDSO** [comment]
I vote to close this because:
1. It is open-ended / doesn't have finishing criteria
2. It may be hard for a new developer to find a place where the `var -> val` replacement can be done, and it will become harder with each `var` that is removed
3. It drains reviewers' time that could be used somewhere else
4. The benefit is infimal
5. If you want small changes for new developers, we still have more than 100+ KotlinCleanups, which tend to be more useful and have a finishing criterium

**Comment by BrayanDSO** [comment]
It's been a week and nobody has opposed to close this, so I'm going to do it. This can be rediscussed and reopened if necessary

**Comment by mikehardy** [comment]
only commenting now to say I agree in general with the progression of "thoughtful comment with solid argument" --> "default close but hey we can reopen if anyone is angry" style. Not sure how to better manage qualitative things like this and still make progress, so +1
