### ISSUE TITLE
[Bug] Issue with Add note and Create deck Options in AnkiDroid 2.15.6

### ISSUE THREAD

**Issue by S-Downes** [ankidroid/Anki-Android#11510]
###### Reproduction Steps

1. Start AnkiDroid on mobile device 
2. Tap + icon to Create deck
3. Tap + icon to Add note

###### Expected Result

Created deck is saved upon closing the application, and upon returning to AnkiDroid. Add note feature does not cause the app to crash, or terminate. 

###### Actual Result

Creating a deck seems to work, but does not persist when exiting and returning to AnkiDroid. Instead the new deck is missing. Add note option always results in the application closing.

###### Debug info

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = OPPO

Model = CPH2127

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2127 Build/RKQ1.201217.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.61 Mobile Safari/537.36

ACRA UUID = b322145e-c3e0-4b9a-bf1d-d9eebd5cd3e4

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there!
Can you please try the most recent .A parallel release from https://github.com/ankidroid/Anki-Android/releases ?
We're getting quite a few crash reports on 2.15.x and most of them are reporting "hey, that fixed it" when they try the newer releases

**Comment by S-Downes** [comment]
Tried using .A and works fine now. Thanks for the help.

**Comment by mikehardy** [comment]
@S-Downes yes! really glad that worked. We're working hard to get 2.16 out (it's stable enough, really) we're just blocked until we handle a forward migration to requirements of new google play policy, can follow here if interested to track the blocking issue #5304
