### ISSUE TITLE
Prevent a certain tag from being reviewed

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1151]
Originally reported on Google Code with ID 248

```
Add the possibility to suspend/unsuspend all cards that have a certain tag.
```

Reported by `nicolas.raoul` on 2010-11-09 05:01:42

**Comment by dotancohen** [comment]
Now that users can review cards _on a watch_ this issue is more important than ever:
https://play.google.com/store/apps/details?id=com.yannik.wear.anki

Many cards are not suitable for display on a 300px * 300px screen. Users should be able to blacklist these cards from showing up on the watch based on tags.

**Comment by timrae** [comment]
How do you propose this feature would work exactly?

**Comment by dotancohen** [comment]
I actually don't have a watch yet so I'm currently unfamiliar with the available interface options. Perhaps a long tap then swipe down if the API  supports that.

**Comment by timrae** [comment]
Anki Wear is a completely separate app that just accesses the AnkiDroid database through the API, so obviously any feature related to skipping cards with a certain tag on a watch would be independent from us adding such a feature.

To be honest I find it hard to see such a feature as described above ever being included in AnkiDroid unless Anki Desktop adds such functionality. It would make a great plugin, however! @jvanprehn mentioned being interested in working on the plugin architecture in #2943 last month.

**Comment by p4nix** [comment]
Sorry for the duplicate, I'm just going to +1 here.
Some cards are not suitable for AnkiDroid and currently can only be excluded from the review queue via filtered decks. While this is better than nothing, a dedicated option to exclude cards with a certain tag to be reviewed would remove the need to rebuild a filtered deck each time you switched between AnkiDroid and Anki desktop and thus be quite convenient.

**Comment by dotancohen** [comment]
still searching for solutions

**Comment by dae** [comment]
I'm afraid this is unlikely to happen in the near future if at all. I'd recommend either moving the cards to a separate deck, using filtered decks, or if the cards are infrequent, burying them as they come up.
