### ISSUE TITLE
[Bug] Import does not show .apkg files 2.16alpha67

### ISSUE THREAD

**Issue by PanderMusubi** [ankidroid/Anki-Android#11525]
###### Reproduction Steps

1. Import
2. Navigate to directory with .apkg files

###### Expected Result

See the .apkg files to import.

###### Actual Result

Not seeing the .apkg files to import

###### Debug info

Version 2.16alpha67, import does work on thie same device for version 2.15

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report. Could you fill out the debug information: Preferences - Advanced - About AnkiDroid - copy ddebug info

**Comment by PanderMusubi** [comment]
AnkiDroid Version = 2.16alpha67

Android Version = 11

Manufacturer = OnePlus

Model = IN2023

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; IN2023 Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.61 Mobile Safari/537.36

ACRA UUID = 5e653a8a-d8ce-4bbc-bb9e-1c5d224ab537

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by PanderMusubi** [comment]
PS Preferences is name of the menu but it is listed as Settings. Also a bug?

**Comment by mikehardy** [comment]
Strange, I just tried this with 2.16alpha69 on my device and I was able to see .apkg files (and .colpkg files, incidentally) in my Downloads folder after navigating to it. So...i can't reproduce :thinking: - that was a OnePlus6T on Android 11 plus an Android API31 emulator
