### ISSUE TITLE
Decouple `Time` from the collection

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11541]
I admit with time passing that Time itself was not part of the collection but of the system. I don't like static value, but I guess it's the more logical way to go. I'll thus remove time from Col

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/11487#issuecomment-1146790616_

**Comment by mikehardy** [comment]
Not sure if this is completed or not?

**Comment by Arthur-Milchior** [comment]
@david-allison is it done? I don't understand what's up with Time to be honest. I believe right now it's okay

**Comment by david-allison** [comment]
This was completed in e4da0eb9da6c79a14f80bdc0afc28f6d9ad5294c (https://github.com/ankidroid/Anki-Android/pull/11563), @Arthur-Milchior you didn't seem happy with this as a resolution, but I consider this to be resolved.

**Comment by Arthur-Milchior** [comment]
If that's not blocking anything, I'm fine with it.
