### ISSUE TITLE
Crowd-in open source

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11568]
> Would probably need to check with CrowdIn support about getting the test project verified as open source, we're very close to the 60k strings limit which pushes you to paid territory if you're not an open source app

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/8274#issuecomment-1146037931_

I plan to take charge of it (I'll double check on discord you didn't do it)
Only issue is that they require to have updated news on our website. I'll try to argue that what is relevant here is our play store address, as it's where people get new version

**Comment by david-allison** [comment]
Is this still necessary?: https://github.com/ankidroid/Anki-Android/pull/11557

**Comment by Arthur-Milchior** [comment]
I don't see how this PR change the issue. If I understand https://crowdin.com/pricing#:~:text=If%20you%20have%20up%20to,of%20data%20transfer%2C%20it's%20free. the limit is on the number of words and it don't seem to change

**Comment by david-allison** [comment]
AnkiDroid is already an open source org.

Our 'test' org would need to go through the same process

**Comment by Arthur-Milchior** [comment]
Thanks a lot for clarifying. I misunderstood your original concern then, my bad.
I could honestly have imagined it was never declared as such before as we didn't have a need for it. But happy to know I got it wrong
