### ISSUE TITLE
Deprecate legacy preference upgrade mechanism

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#11560]
That should probably be added in a comment here in the code so future developers are not lured in, and/or could use a blurb in developer guide "how to do a preferences upgrade"...

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/11555#discussion_r890150791_

**Comment by BrayanDSO** [comment]
There is a comment there IIRC
