### ISSUE TITLE
[Bug] Previews sometimes take place out of normal order and never end

### ISSUE THREAD

**Issue by sjl872964789** [ankidroid/Anki-Android#11576]
###### Reproduction Steps

1. Click the menu
2. Click "Card Browser"
3. Search for any character
4. Click the three dots in the upper right corner
5. Click "Select All"
6. Deselect one of the check boxes
7. Select the check box again
8. Click the three dots in the upper right corner
9. Click on "preview"

###### Expected Result

Preview in the normal order, and the preview works normally

###### Actual Result

It starts with the second word in the list, and the preview never ends and the first word does not appear

###### Debug info
AnkiDroid Version = 2.16alpha67

Android Version = 11

Manufacturer = OnePlus

Model = KB2000

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; KB2000 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = aa4d19d2-311f-41e8-87a9-bc4ce5082d08

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Video

https://user-images.githubusercontent.com/15941953/172786219-ee03bfc1-1d52-4b7e-87ab-c814b7099f26.mp4

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by krmanik** [comment]
You have to click on arrow to view the next question.
