### ISSUE TITLE
[Regression] Samsung browser copy paste is broken

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#11574]
###### Reproduction Steps

1. Open a web Page and copy a text
2. Edit a card in Ankidroid
3. Paste to a blank field

###### Expected Result

The text is pasted to the field.

###### Actual Result

The text is not pasted. The field remains empty.
To open clipboard and paste works.

###### Debug info

AnkiDroid Version = 2.16alpha67

Android Version = 11

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-A225F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36

ACRA UUID = 279377fa-c607-444b-8d1e-0ac5b2f9a752

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dorrin-sot** [comment]
Hi I couldn't reproduce this. Could you please show a video of these steps?

**Comment by pavreh** [comment]
Well, this can be reproduced with Samsung Internet browser only. I tried to copy from Opera Mini now and copy/paste works. But copy/paste from Samsung Inernet to other apps works too.

**Comment by pavreh** [comment]
It definitely is a solution to start using a different web browser :-)
Copy/paste from Samsung Internet to AnkiDroid 2.15.6 works.  Only thing which do not work for me is: 1) long tap in Samsung Internet then tap copy. 2) long tap in AnkiDroid 2.16alpha67 note field then tap paste.
It is Samsung Internet version 17.0.6.9.

**Comment by pavreh** [comment]
I did a research. AnkiDroid 2.16alpha53 and lower works. AnkiDroid 2.16alpha54 and above does not work.
