### ISSUE TITLE
[Bug] Tapping on the ‘Card Browser’ Menu thing doesn't fill in the input field of Card browser with the search term

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#11587]
###### Reproduction Steps

1. Select some text
1. Tap on the ‘Card Browser’ Menu thing

###### Expected Result

Card browser search input is filled with the search term

###### Actual Result

Card browser search input is empty

###### Debug info

AnkiDroid Version = 2.16alpha65

Android Version = 11

Manufacturer = Xiaomi

Model = Mi A2

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Mi A2 Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = 265fa358-f0e1-4fd2-9858-aa352ae60d78

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dorrin-sot** [comment]
Hi sorry I couldn't understand what you mean by "select some text". could you please  provide a video or screenshot?

**Comment by oakkitten** [comment]
You literally select some text anywhere in the app, then tap on the triple dots in the popup menu (the one with Cut, Copy, Paste), and then tap on Card Browser.

**Comment by oakkitten** [comment]
By the way, we are these two menu items supposed to work in other apps? The setting summary says "Enables ... context menu globally", but it seems that it only enables the items inside AnkiDroid.

**Comment by oakkitten** [comment]
Still an issue

**Comment by snowtimeglass** [comment]
Ah, this actual result is certainly not good.

FWIW, the expected result seems to realize only after tapping ”SEARCH ALL DECKS" in the toast message.

>By the way, are these two menu items supposed to work in other apps? The setting summary says "Enables ... context menu globally", but it seems that it only enables the items inside AnkiDroid.

The setting enables these two items in context menu of Chrome on my device. I use 'Card Browser' often in my daily life. It’ so useful.
