### ISSUE TITLE
[Bug] [Feature Missing] Filtered Decks missing multi-steps

### ISSUE THREAD

**Issue by ANKIFETISH** [ankidroid/Anki-Android#11609]
###### Reproduction Steps

1. AnkiDroid 2.15.2 (The official Google Playstore version)
2. AnkiDroid 2.16alpha67 (GitHub)
3. Anki Mobile (iOS version)
4. Anki Desktop (latest)

###### Expected Result

Filtered Decks should show multiple steps upon review (Again, Hard, Good, Easy[End]), just like regular unfiltered decks would show. 

###### Actual Result

Filtered Decks on AnkiDroid on official and beta version fail to show the multiple steps. The pictures have iOS version (Dark theme) and Android version(Light theme). As you can see this is soley a missing feature of AnkiDroid.

[Samsung Tab S6 Lite Info.txt](https://github.com/ankidroid/Anki-Android/files/8887076/Samsung.Tab.S6.Lite.Info.txt)

![Anki iOS Mobile version](https://user-images.githubusercontent.com/106856406/173259907-67eccf8b-1933-4ab9-92f5-0f216f5eec9e.PNG)
![AnkiDroid Filtered Steps](https://user-images.githubusercontent.com/106856406/173259910-71a9fe04-c382-44f1-8067-e0512d3992df.JPG)
![AnkiDroid Unfiltered Deck Steps](https://user-images.githubusercontent.com/106856406/173259911-218e2835-c43e-4f46-9fab-42b1f78ca7e8.JPG)
![AnkiDroid Version](https://user-images.githubusercontent.com/106856406/173259912-f4bf0a8d-1378-4650-af96-f2ef31a563d0.JPG)
![iOS Anki Mobile Filtered Steps](https://user-images.githubusercontent.com/106856406/173259913-973a6bd8-47e1-4e2c-9d41-4232a307f25e.JPG)

###### Debug info
AnkiDroid Version = 2.16alpha67

Android Version = 12

Manufacturer = samsung

Model = SM-P610

Hardware = exynos9611

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-P610 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.73 Safari/537.36

ACRA UUID = 4a9bbfc2-76ec-414d-8c93-dd2a6cd0ea09

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
Filtered decks with rescheduling off have 2 buttons in v2, and 4 buttons in v3

**Comment by ANKIFETISH** [comment]
Thank you both for quick response! Now I can be at peace [believe me, i thought i was doing something wrong]. I will follow those issues. Thank you once again!

**Comment by mikehardy** [comment]
I honestly didn't know about it myself and was also suffering, came in handy just this evening for me personally :-)
