### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by Rahey94** [ankidroid/Anki-Android#11620]
Hi all,

I recently started experiencing a problem with Ankidroid:

When I do reviews over a long period of time, the cards get slower and slower to load, until eventually the app crashes. Upon crashing, a message appears saying that Webview failed due to lack of memory.

Upon restarting the app, the process repeats: At the beginning the cards all load instantaneously, but the more reviews I do the longer it takes for the cards to load (both the front and back) until it crashes again. 

Force quitting the app also "resets" the process.

All of my cards have audio on them, and I'm using Ankidroid version 2.15.6.

Debug information:

AnkiDroid Version = 2.15.6

Android Version = 12

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 12; Pixel 3a Build/SP2A.220505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36

ACRA UUID = 22093a8d-3099-421d-b128-30c8204cad98

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

Thanks!

**Comment by mikehardy** [comment]
Hi there! This is most likely related to fonts, as a guess. Do you have custom fonts installed?
Those are the things that cause WebView to leak memory. In general if it is a memory leak inside the WebView we can only mitigate it, we cannot fix it, until/unless Google issues an update to the underlying Chrome library / WebView system component.

If it's just default fonts + audio, that's a new one!

**Comment by Rahey94** [comment]
Hi, thanks for your reply!

I do have custom fonts installed, and use them on all of my cards. If custom fonts cause WebView to leak memory, that must be the underlying problem.

It's a bummer there's no way to fix it - I guess I'll either have to switch to default fonts or just hope Google does something on their end.

Thanks again!

**Comment by Rahey94** [comment]
This issue is likely caused by custom fonts, and is not an Ankidroid problem.

**Comment by mikehardy** [comment]
Please do report back if switching to default fonts as a test relieves the memory leak - if it doesn't then we may have something new in the leak department and there is always the chance we can do something to mitigate it

**Comment by Rahey94** [comment]
Will do. I'll test it out over the next couple days and reply back here. Thanks!

**Comment by Rahey94** [comment]
Hi,

I tried changing to a default font yesterday from a custom font and the app still crashed after around 100 cards worth of reviews, which is unchanged from before. The crash happened twice. The error message was a little different today, however: Instead of saying that WebView failed due to a lack of memory, it said that WebView failed due to an unknown error.


In regards to fonts, a couple notes:

1)	I’m studying Japanese so switched over to a font called ＭＳ ゴシック. Since this is a Microsoft font maybe it’s not present on Android and would cause the same problem as custom fonts? 

2)	There are three cards for each note in the deck I’m using. I changed card type 1 and card type 2 to the ＭＳ ゴシック font, but card type 3 remains with a custom font. However, only card types 1 and 2 appear in the deck I have been using – card type 3 is not used at all.
I’m not sure if cards of the same note, even if they don’t appear in the deck, would cause problems but I thought it would be worth bringing up.

My apologies this got so long. Hopefully this is at least a little helpful!

**Comment by mikehardy** [comment]
Custom fonts are still custom fonts, and any custom font that's not built in to the webview may be "heavy" with regard to memory usage. So I'm not sure this is really an advance in "what we know" vs "what we think we know". 

I don't see anything for Pixel 3as in our crash database or on google's play store crash database:

ACRA UUID = 22093a8d-3099-421d-b128-30c8204cad98

So I don't have a lot of info. Perhaps if you could create a deck you could export (no personal information etc) that triggered it and you could attach the .apkg here?

**Comment by vincrichard** [comment]
Hello,
I am having the same issue and it only started a couples of weeks ago (thought the issue was from my phone Redmi Note 7 which is getting old) but Anki droid was the only application with sure issues.
I have been using this deck for a good 2 months without any issues. and issues started around 2 weeks ago.
Usually when I start reviews everything is fine, after ~20 reviews the app slow down so bad I need to restart it to continue my reviews.

As for my deck type I am using a template taken from: https://ankiweb.net/shared/info/1557722832
With another premade deck.

Hope this helps.

**Comment by mikehardy** [comment]
The thing with issues that start without AnkIDroid being updated (note: AnkiDroid has not been updated in months and months, unless you installed an alpha manually) is that it is usually related to a Chrome WebView update which is out of our control.

For that reason our issue template requests the debug information from the app which contains the webview version information. It would be useful to have that, for example:

> Webview User Agent = Mozilla/5.0 (Linux; Android 12; Pixel 3a Build/SP2A.220505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36

You might try uninstalling webview updates to see if that helps as a test. They usually contain security fixes so it is not a long-term solution and I don't recommend uninstalling them permanently but it is useful as a test and you may reinstall them after the test

**Comment by vincrichard** [comment]
Thanks for explaining where the issue came from. 
I will look into it.
There as indeed been a update of the Android System Webview 2 weeks ago, so like you said it is probably link.
My version of Android System Webview is 102.0.5005.125.

**Comment by Rahey94** [comment]
Thanks for commenting that you have the same issue! It's nice to know I'm not alone.

I also never noticed this problem until recently, so the Webview update breaking something theory makes sense.

Please let me know if you're able to find a solution!

**Comment by Rahey94** [comment]
Hi,

As requested, here's the .apkg of the deck I've been using. I had to delete all the media, otherwise it was too big to upload.

Thanks!
[Japanese - Core10000.zip](https://github.com/ankidroid/Anki-Android/files/8973202/Japanese.-.Core10000.zip)

**Comment by homocomputeris** [comment]
I have the same issue with enforced default fonts
```
AnkiDroid Version = 2.16alpha68

Android Version = 12

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; ONEPLUS A6003 Build/SQ3A.220605.009.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36

ACRA UUID = 79dddeac-0bae-4534-bd39-9621f65c69bc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by mikehardy** [comment]
Oh no @homocomputeris - have you tried uninstalling webview updates to see if we can locate this in the webview? Only temporarily for a test of course as the updates contain security fixes and I don't want to expose anyone to security attacks

**Comment by homocomputeris** [comment]
It seems I have no WebView updates installed (at least I cannot uninstall anything). My current version is 102.0.5005.78

**Comment by vincrichard** [comment]
Hello, to update on the matter, I have downgrade the Android System WebView to 83.0.4103.101 and Ankidroid work without an issue.
I guess for now I will uninstall / reinstall every day

**Comment by mikehardy** [comment]
@vincrichard I guess that at least isolates the problem into the WebView. I think chrome webview 103 just came out, hopefully they will fix it soon, or 103 already fixes it?

**Comment by tme78** [comment]
I've been having the same issue. My very simple workaround is: when it starts to get slow, I go back to Ankidroid home screen and hit synch. Then it's back to a fresh start right away. Maybe this helps! 😃
