### ISSUE TITLE
Error syncing media data

### ISSUE THREAD

**Issue by fastcat001** [ankidroid/Anki-Android#11621]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/73415472/173502684-200ed274-7de5-448f-b566-b1640bbbba39.png">

This error happens on Ankidroid, Android 11.

Wastes 1 hour to finish synchronizing from the desktop app and ends up with this error.

**Comment by mikehardy** [comment]
Hi there! You assert "wastes", please be aware that sync is a "convergent" process. That means, every time you sync, it gets closer to being in sync. No time is wasted, whatever progress was made is real progress and your device is that much closer to in sync.

How did it go when you re-started syncronization? Does it begin syncrhonizing media again and start making more progress?

If so, then after a few attempts (depending on how much media you  have) it will be in sync and the current low-performance media sync process will no longer repeat itself, it will just be the typical fast sync of only the database contents

See #8925 (media sync performance, with not-great-but-works workaround if really needed) & #5304 (underlying issue)
