### ISSUE TITLE
An error occurs when you change an ordinary word into a cloze

### ISSUE THREAD

**Issue by LL12138LL** [ankidroid/Anki-Android#11626]
###### Reproduction Steps

1. Add a new word
2. Edit the word
3. Change the type to cloze
4. Fields cannot be edited
5. Previewing the word at this time will show an error

###### Expected Result

Fields can be edited normally

###### Actual Result

Fields cannot be edited, and previewing will fail

###### Debug info
AnkiDroid Version = 2.16alpha67

Android Version = 11

Manufacturer = OnePlus

Model = KB2000

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; KB2000 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 5f8bfad0-e4da-46e7-a01a-753e09ec39d4

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Video

https://user-images.githubusercontent.com/101189845/173603520-dc9525c9-8ff7-4245-aea7-40212d3fa0ea.mp4

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
There was a proposed PR for this one but it's a lot more complicated than I thought at first glance. Related commentary:

https://github.com/ankidroid/Anki-Android/pull/11627#pullrequestreview-1007284754

> This removes the ability to map the fields when changing the note type.
> 
> I feel it'd be best to move the discussion back to the issue.
> 
> We have a lot of UX tech debt around editing note types, and it'd be best to resolve this properly rather than adding more complexity.


https://github.com/ankidroid/Anki-Android/pull/11627#discussion_r897827680

> Users currently aren't able to edit a card until it's been saved (if we are changing the note type, this lets users fix the field mapping).
> 
> This PR lets users edit the fields, but it disallows a user from setting the mapping if moving from a note type with 3 fields to a note type with 2 fields.
