### ISSUE TITLE
[Bug] Can't quick open deck stats when no cards scheduled

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#11638]
###### Reproduction Steps

1.  From the deck list, tapping on the numbers will bring up a screen showing some deck statistics. If no cards are scheduled in that deck, instead of showing the stats there's a banner at the bottom saying "No cards scheduled to study". Since the deck stats are helpful, it would be nice to always show the stats page and, if there are no cards scheduled to study, just grey out the "Study" button.  

![Screenshot_20220615-160610_AnkiDroid A](https://user-images.githubusercontent.com/409080/173934575-a74cc3b6-2b72-47eb-bf02-6c3794b8641a.png)

###### Expected Result

![Screenshot_20220615-125336_AnkiDroid A](https://user-images.githubusercontent.com/409080/173934622-5c7176fa-6461-4db2-b4a9-daa08c0b894f.png)

###### Actual Result

![Screenshot_20220615-125244_AnkiDroid A](https://user-images.githubusercontent.com/409080/173934628-8ba46a45-1c1b-4d19-b59d-aea01dac3a7c.png)

###### Research

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, could you fill out the 'debug info' section of the template (Settings - Advanced - About AnkiDroid - Debug Info). Thanks!

**Comment by doozan** [comment]
I'm seeing this on both the stable 2.15.6 and the latest alpha 2.16 alpha 68

#### debug info ####
AnkiDroid Version = 2.16alpha68

Android Version = 11

Manufacturer = Motorola

Model = Moto X4

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Moto X4 Build/RD2A.211001.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.120 Mobile Safari/537.36

ACRA UUID = b663b463-70e7-440b-9d25-3f43e59b6c01

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by doozan** [comment]
Can confirm this is still an issue with 2.16alpha78. I posted the debug info earlier so I think someone with permissions can remove the waiting for feedback label unless there's any more info I should provide.
