### ISSUE TITLE
Deck deletion not followed by the option to undo

### ISSUE THREAD

**Issue by bnknndy** [ankidroid/Anki-Android#11669]
After deleting a deck, users do not receive a prompt to undo their action.

Specifically, decks have no easy recovery method, unlike AnkiDroid's option to undo card deletion immediately after the action. While users can restore decks from a backup, that functionality isn't accessible.

![image](https://user-images.githubusercontent.com/7875524/175699340-f3eda804-d6cd-4be0-b086-2e9215faa98a.png)

## Relevant heuristic

 [User control and freedom](https://www.nngroup.com/articles/user-control-and-freedom)

"Users often choose system functions by mistake and will need a clearly marked 'emergency exit' to leave the unwanted state without having to go through an extended dialogue. Support undo and redo."

## Student's severity classification (minor, major, critical)

*Critical*, due to:

1. **Frequency**: "The frequency of this will be low/moderate because the deletion of a deck isn’t something that a user will commonly do unlike the deletion of a card."

2. **Impact**: "The impact of this issue is very high because when a user wants to undo the deletion of a deck there is no easy way of completing this. A user may be able to restore a previous backup with the deck but there is no guarantee that the deck will be there, and the user will lose any changes made that weren’t backed up. Since the implications of this issue can be significant the impact is high."

3. **Persistence**: "This issue’s persistence is high since this is not an issue that can be overcome even if the user is aware of it. Users will be repeatedly bothered by this issue since there is no easy solution for recovering when they accidentally delete a deck, delete the wrong deck by mistake, or delete a deck and then realize they wanted it after."

4. **Weighting**: "Although the frequency of this issue is lower since the deletion of a deck is not something that is commonly done, if the issue is encountered the impact of it is high and can result in the user losing their entire deck. The persistence of this issue is also high because the issue is not avoidable even if the user is aware of it. Due to this, a rating of 4 is given since the implications are significant when the issue arises."

This issues comes from [Source file](https://1sfu-my.sharepoint.com/personal/paulh_sfu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team%2Fheuristic%2Deval%2Dexemplary%2D3%2Epdf&parent=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team&ga=1) as discussed in #11664. *Text not wrapped in quotation marks is rewritten for brevity.*

**Comment by snowtimeglass** [comment]
I agree. Incidentally, Anki Desktop can undo deck deletion immediately after the action. 

![image](https://user-images.githubusercontent.com/10436072/186810354-dc168f8b-1a46-489c-b443-19f8197493ce.png)
