### ISSUE TITLE
Minor dev suggestion: don't turn Kotlin warnings into errors except in CI

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#11660]
Making things like unused variables hard errors makes it more cumbersome to comment out a section of code while testing.

**Comment by mikehardy** [comment]
I see what you're saying, but in our experience twice now with the GSoC avalanche, getting errors prior to CI is a big win for us, we push hard for detection of all things that would fail CI to fail immediately on a dev workstation and only through the accumulation of a lot of marginal gains like that are we able to survive March/April/May as maintainers

Is there some more trivial local hack you can do to swap out the rules list?

**Comment by dae** [comment]
Gotcha, I'll do that then.

**Comment by dae** [comment]
Implemented in https://github.com/ankidroid/Anki-Android/pull/11644/commits/ecdf4adf4a3622ba7bc10df78ed21deb5c4930ea in #11644

**Comment by mikehardy** [comment]
That's a good tradeoff - I like that, local failures pre-CI has been a big help but an override for those that can handle a foot-gun works for me
