### ISSUE TITLE
No feedback provided when creating or deleting decks

### ISSUE THREAD

**Issue by bnknndy** [ankidroid/Anki-Android#11668]
Users receive no explicit feedback when creating or deleting decks.

Specifically, users must confirm whether their action succeeded by checking the deck list. In cases where actions fail, such as when a user attempts to create a new deck with the same name as an extant deck, the user receives no explanation.

![image](https://user-images.githubusercontent.com/7875524/175663594-1bb97602-40a1-4c0f-8160-bea354602346.png)

![image](https://user-images.githubusercontent.com/7875524/175663742-796654dd-8ebc-4020-948b-dddec7f75a6b.png)

## Relevant heuristic

 [Visibility of system status](https://www.nngroup.com/articles/visibility-system-status/)

"The visibility of system status refers to how well the state of the system is conveyed to its users. **Ideally, systems should always keep users informed about what is going on, through appropriate feedback within reasonable time.**"

## Student's severity classification (minor, major, critical)

*Critical*, due to:

1. **Frequency**: "This issue is common since users will encounter this every time they create and delete a deck which is a frequently completed action. Therefore, the issue is frequent."

2. **Impact**: "The impact of this is moderate because when a user creates or deletes a deck and isn’t sure the action was completed it will require extra steps for the user to overcome the issue. If the issue arises, the user can search for the deck name into the search bar and will be able to deduce whether the deck was created, deleted, or not created. Since the issue is no difficult to overcome but requires action from the user that shouldn’t be required the impact is moderate."

3. **Persistence**: "This is a persistent problem because even if a user is aware of the issue when they are creating a deck, deleting a deck, or creating a duplicate deck there won’t be any feedback to inform the user of this. Additionally, if a user accidentally clicks cancel or the wrong button without knowing they will not be certain if the intended action was completed."

4. **Weighting**: "This issue has a high degree of frequency and persistence since there is no way to avoid it. The impact of the issue is moderate because users will be able to be easily overcome the issue by searching within the list of decks once they are aware of it. Although the impact of the issue is low/moderate since the issue will be consistently faced by the user a severity rating of 4 is given."

This issues comes from [Source file](https://1sfu-my.sharepoint.com/personal/paulh_sfu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team%2Fheuristic%2Deval%2Dexemplary%2D3%2Epdf&parent=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team&ga=1) as discussed in #11664. *Text not wrapped in quotation marks is rewritten for brevity.*

**Comment by BrayanDSO** [comment]
Part on #10401. About deleting feedback, I think that a snackbar with something like `Deck "foo" deleted` should be good

**Comment by bnknndy** [comment]
Oh, thanks for tagging that one. Is it feasible to stick an undo button on the snackbar for each of those?

**Comment by BrayanDSO** [comment]
@bnknndy As for adding the button, yes, it's simple to add one.

As for the button action, I know Anki desktop is able to undo deck creations and deletions, so our code may be able to do it as well (i.e. I haven't checked it up)

**Comment by BrayanDSO** [comment]
> Part on #10401. About creating/deleting feedback, I think that a snackbar with something like `Deck "foo" deleted`/`Deck "foo" created` should be good

Maybe just `Deck deleted` or `Deck created` would be better because deck names can be really long, which wouldn't show well on a snackbar

**Comment by bnknndy** [comment]
> > Part on #10401. About creating/deleting feedback, I think that a snackbar with something like `Deck "foo" deleted`/`Deck "foo" created` should be good
> 
> Maybe just `Deck deleted` or `Deck created` would be better because deck names can be really long, which wouldn't show well on a snackbar

@BrayanDSO that makes sense. I think the likelihood of people creating and deleting decks without knowing what they're manipulating is probably pretty low. A generic confirmation should be fine since they'll have the visual feedback of the deck list and the snackbar, possibly with the undo option (I forgot it was a separate issue #11669) but definitely with the ability to manually recover a backup in case of a grievous error.
