### ISSUE TITLE
Setting is difficult to understand - Learn ahead limit

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#11677]
**Is your feature request related to a problem? Please describe.**
For new users, it is not possible to understand what “Learn ahead limit” setting means. There is just a title “Learn ahead limit” and a value “0 min” (see the picture below).

“Double tap time interval” setting is developed better. There is a title and a hint. A value is visible after tapping on the setting (see the picture below). 

![Screenshot_20220621-174447_AnkiDroidA-learn_ahead](https://user-images.githubusercontent.com/10192661/175015514-f8179315-ff4f-4c2b-bf2a-6a44e9edc398.png)

**Describe the solution you'd like**
My suggestion is to follow a “title, hint, value” rule like for “Double tap time interval” setting.
It this case, the “Learn ahead limit” setting could look like this:
“Learn ahead limit
Cards will be shown early if they are due to be shown in less than X minutes and there’s nothing else to do” 
See the picture below.

![Screenshot_20220621-174447_AnkiDroidA-learn_ahead_ok](https://user-images.githubusercontent.com/10192661/175015894-cd88590d-0147-46b1-8ea6-3e1cb7b9fd7f.png)

After the user tap on the setting, the value and units will be visible (see the picture below).

![Screenshot_20220622-123815_AnkiDroidA-learn_ahead_value_ok](https://user-images.githubusercontent.com/10192661/175016230-c20d992b-4a0b-41c0-bc5f-7893da0bbd11.png)

**Additional context**
In Anki, there are no hints too but the user can click on a help button directly in the setting screen (see the picture below).

![anki_help](https://user-images.githubusercontent.com/10192661/175016794-ef823d27-f32f-4f24-91ed-c87635bcf05b.jpg)

If you like this idea and the issue will be resolved, I will prepare more settings improvements. Mainly for Timebox time limit and New timezone handling.

**Comment by snowtimeglass** [comment]
@pavreh I agree with this idea, at least as a solution for the time being. `Timebox time limit` and `New timezone handling` also seem to be too difficult for new users to understand.

As @dorrin-sot (#11674) and @bnknndy (#11724) suggested in their respective contexts, it may be desirable to add a small "?" or "i" button which pops up a short summary explanation next to the title in the future.

![image](https://user-images.githubusercontent.com/10436072/185940012-0d3531c1-041d-45fe-baab-9fd71d940fc8.png)
(an example of "i" icon and its pop-up help on Anki Desktop)

**Comment by snowtimeglass** [comment]
The solution of "i" button looks promising in futere.

https://user-images.githubusercontent.com/69634269/184986361-bc4c8dae-1352-448b-85e3-edc4215115ec.mp4


_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/12039#issuecomment-1217178460_
