### ISSUE TITLE
Answer button intervals may confuse new users

### ISSUE THREAD

**Issue by bnknndy** [ankidroid/Anki-Android#11675]
Some new users may not immediately grasp the use of or logic behind \[Again...Good] in the study interface.

Specifically, the student found it confusing for the time labels on the buttons to increase with perceived prompt ease, since they associated a shorter interval with "better" and a longer interval with "worse."

![image](https://user-images.githubusercontent.com/7875524/175699976-bd213741-0080-4c47-adff-411000c78eec.png)

## Relevant heuristic

[Match between system and real world](https://www.nngroup.com/articles/match-system-real-world/)

"Systems should speak the users' language with familiar words, phrases, and concepts rather than system-oriented terms. Interfaces that follow real-world conventions and make information appear in a natural and logical order demonstrate empathy and acknowledgement for users."

## Student's severity classification (minor, major, critical)

Major, due to:

1. **Frequency**: "This issue appears with high frequency as it happens every time the user studies a card, after clicking 'show answer'."

2. **Impact**: "This issue has medium impact since it is possible to overcome the initial confusion once the user becomes more familiar with the system. However, since the time and colour combination is not intuitive, it requires the user to spend time understanding the function, which distracts from the main task of studying the cards."

3. **Persistence**: "This feature becomes less of an issue over time as the user becomes familiar with the system, though it is significant at the beginning and will take the user some time to learn, which means the issue does not disappear after the first time."

4. **Weighting**: "This issue occurs with high frequency but its impact and persistence will decrease as the user learns its purpose. The initial mismatch creates a clash between user assumptions about the rating bar and its actual purpose, meaning the user must readjust their mental model. Since users must use the rating bar before moving on to the next card, it is a major issue."

This issues comes from [Source file](https://1sfu-my.sharepoint.com/personal/paulh_sfu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team%2Fheuristic%2Deval%2Dexemplary%2D4%2Epdf&parent=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team&ga=1) as discussed in #11664. *Text not wrapped in quotation marks is rewritten for brevity.*

**Comment by BrayanDSO** [comment]
As said in the "Impact" and "Persistence" topics, the user will get how it works with time (or will have already got the idea since this is a flashcard app)

To aid them on this matter, I think this should be a part somewhere on Onboarding "Hey, now this card will show only after 4 days!"

**Comment by snowtimeglass** [comment]
Or/And showing tutorial alert dialogs after tapping the buttons as follows...?

```
You are rating this card as "Easy", 
so AnkiDroid will show you it next time 
after a longer interval than standard one 
to study it less frequently, more efficiently.
All right?

□ Never ask again                  [Cancel] [OK]
```
