### ISSUE TITLE
Insufficient error notification in card template editor

### ISSUE THREAD

**Issue by bnknndy** [ankidroid/Anki-Android#11672]
The card template editor doesn't validate field names.

Specifically, when a user inputs a {{field name}} into a card template which doesn't exist in the card's note type, the user won't discover this until effected cards appear in review or in the card browser, at which point AnkiDroid provides a link to the manual to find out how they can fix the error.

![image](https://user-images.githubusercontent.com/7875524/174868240-e750137b-36d5-4f7b-acce-8b71bbdb1e1c.png)

## Relevant heuristic

 [Error prevention](https://www.nngroup.com/articles/slips/)

"Prevent unconscious errors by offering suggestions, utilizing constraints, and being flexible."

## Student's severity classification (minor, major, critical)

*Major*, due to:

1. **Frequency**: "The frequency of this issue is very rare because this is not something a user would commonly use or accidentally change."

2. **Impact**: "This has high impact because once this issue is encountered the user will not be able to use their cards until it is solved. The issue forces the user to read documentation on what the fields are used for and find out what the original value in these fields used to be. Since this issue breaks the user’s flow and stops the user from using the app the impact is high."

3. **Persistence**: "Once the user is able to understand and know what the field value should be, the user will be able to overcome this issue. The user can overcome this issue when they are aware of it making the persistence of this issue is low."

4. **Weighting**: "The frequency and persistence of this issue is low meaning that this is not a common thing for users to encounter and if they do, they will be able to mitigate this from occurring again. The impact is high for the user when they do encounter the issue is high however, increasing the score to a 3."

This issues comes from [Source file](https://1sfu-my.sharepoint.com/personal/paulh_sfu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team%2Fheuristic%2Deval%2Dexemplary%2D3%2Epdf&parent=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team&ga=1) as discussed in #11664. *Text not wrapped in quotation marks is rewritten for brevity.*

**Comment by dorrin-sot** [comment]
Can I work on this?

**Comment by mikehardy** [comment]
@dorrin-sot sure!
