### ISSUE TITLE
Users may find card type names unfamiliar

### ISSUE THREAD

**Issue by bnknndy** [ankidroid/Anki-Android#11674]
Users may have trouble choosing a card type in the note editor due to unfamiliar terminology.

Specifically, the student felt that terms like "cloze" or "reversed card" weren't familiar enough to new users.

![image](https://user-images.githubusercontent.com/7875524/175699504-e7666eb8-3534-4ebd-9c5f-9e74ff95c20f.png)

## Relevant heuristic

[Match between system and real world](https://www.nngroup.com/articles/match-system-real-world/)

"Systems should speak the users' language with familiar words, phrases, and concepts rather than system-oriented terms. Interfaces that follow real-world conventions and make information appear in a natural and logical order demonstrate empathy and acknowledgement for users."

## Student's severity classification (minor, major, critical)

*Major*, due to:

1. **Frequency**: "The frequency of users encountering this issue is common because users are highly likely to investigate different card types."

2. **Impact**: "The impact of this issue is moderate because users can ignore this issue and continue using the app as they had before. Although they can avoid the card types this discourages the user from being able to learn and utilize types that they can get value from."

3. **Persistence**: "The persistence of this issue is low because once the user becomes familiar with each card type, they will no longer encounter the issue."

4. **Weighting**: "The frequency of this issue is common because the majority of users will utilize the different card types offered by the app. The impact of this issue is moderate because it steers users away from being able to utilize different card types. The persistence of this issue is low making it a one-time issue that is easy for the user to overcome. Although the issue is common, the moderate impact and the problem only being encountered once results in a rating of 3."

This issues comes from [Source file](https://1sfu-my.sharepoint.com/personal/paulh_sfu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team%2Fheuristic%2Deval%2Dexemplary%2D3%2Epdf&parent=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team&ga=1) as discussed in #11664. *Text not wrapped in quotation marks is rewritten for brevity.*

**Comment by dorrin-sot** [comment]
Oh my god I also still don't know how some of the card types work 😅
I suggest adding a small button next to the type-selector spinner(like below) which would display a tabbed dialog that explains the basics of each type, how they are created, reviewed, and deleted. 

![image](https://user-images.githubusercontent.com/59933477/175532120-1b59ff44-e70a-416e-a4f5-bf9140c6c60e.png)

**Comment by bnknndy** [comment]
> tabbed dialog that explains the basics of each type, how they are created, reviewed, and deleted.

@dorrin-sot I agree with the idea of a dialog. Regarding creating, reviewing, and deleting, I would push back and ask: 

* How much of that do they need to know in that particular stage of creating or editing?

  Info on reviewing and deleting might work better in the particular contexts of reviewing and deleting (in the reviewer and in the card browser, respectively).

* Do users even need to know the details of creating cards in a type selector help dialog? 

  We can try to break down this information even more, and closely tie each discrete piece to its place in the creation flow.

Maybe we have a general dialog introducing the concept of card types and encouraging users to choose one to learn more information about it. That dialog can include a "learn more" link to the [Anki manual](https://docs.ankiweb.net/templates/intro.html), although it's unapproachable.

Then, for the specifics of how to interact with each type in AnkiDroid, we add some flags into [Onboarding.kt](https://github.com/ankidroid/Anki-Android/blob/7082f6ee93ed165180b935dbca44598a6566b3cc/AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt) and use the tap-target system to quickly introduce people to the particularities of a card type.

A couple examples:

| Condition | Effect |
| --- | --- |
| Hasn't created Basic + reversed in AnkiDroid yet | Tap-target the "Cards:" selector button/field and let them know briefly that they're now creating 2 cards for the effort of 1 |
| Hasn't created a Cloze in AnkiDroid yet | Tap-target a text field and tell them that selecting text in the field will give them the contextual option to quickly create occluded text without having to type any markup |

There would have to be more basic conditions, but that gets the idea across. The conditions could also get much deeper, like introducing the concept of cloze to people who have no cloze cards in their decks at all vs. telling people who have created cloze cards how to do so in AnkiDroid, if we felt adventurous.

What do you think?

**Comment by BrayanDSO** [comment]
I'd only add the icon to the manual.

This probably isn't something everybody will get after only reading some dialog messages.

For this, the manual must be well organized (i.e. at least a section and subsections for each type) with examples and screenshots. 

(thinking out loud) maybe add a custom link scheme on the manual, so the user may tap an example and the app would open on the Add Note screen with that text

**Comment by bnknndy** [comment]
> This probably isn't something everybody will get after only reading some dialog messages.

I agree, but having people get it isn't necessarily a useful goal. People just need enough information to feel confident taking action and seeing what happens, with the knowledge that they can get deeper information if they need to at any point in time. We don't need them to learn any more than needed to be able to accomplish their goals with AnkiDroid.

> (thinking out loud) maybe add a custom link scheme on the manual, so the user may tap an example and the app would open on the Add Note screen with that text

The AnkiDroid manual depends heavily on the Anki manual for core concepts, default note types included. We would have to add that link to the Anki manual, or start re-writing it for ourselves.

Even if this was desirable, wouldn't it end up being a version of what Dorrin proposed but with more steps? At that point, I think we could consider just using a more elaborate dialog. From a standpoint of conforming to Material best practices, there's precedent for them throughout Google apps, Maps being one example:

![image](https://user-images.githubusercontent.com/7875524/175698943-25aea6d4-80d2-442c-8e20-96bd9f22057d.png)

---

We should also consider whether this needs intervention at all -- I'm entering these as issues for discussion, but it doesn't mean they require action! Different note types are nice to have, but we don't know that they're crucial to helping users develop a productive relationship with Anki/Droid. This might be better tabled as part of the larger discussion about onboarding priorities, with effort directed at more meaningfully progressive changes.

**Comment by dorrin-sot** [comment]
> Then, for the specifics of how to interact with each type in AnkiDroid, we add some flags into [Onboarding.kt](https://github.com/ankidroid/Anki-Android/blob/7082f6ee93ed165180b935dbca44598a6566b3cc/AnkiDroid/src/main/java/com/ichi2/anki/Onboarding.kt) and use the tap-target system to quickly introduce people to the particularities of a card type.

Ooh the Onboarding class is interesting. Since we already have that, we can use it for the very basics of each card type (like how we already have for the "Basic" card type note creation). Then the "i" button would have abit more info and inside that dialog we would also include a like to the card types section of anki manual

Though I think if we use the Onboarding, it should be after the user created their first note and also should be skippable to prevent overwhelming them🤔

**Comment by dorrin-sot** [comment]
> I'd only add the icon to the manual.

But that has the issue of overwhelming them with too much info

> This probably isn't something everybody will get after only reading some dialog messages. IMO, more complex matters need a bigger explanation which fits better on the manual and the user may use Google translator or anything similar if that section isn't translated already, which isn't possible on the app.

Not sure if this is the best approach but maybe we can add a "copy to clipboard" or a "google translate" IconButton that opens google translate directly (with the text) in it?
Also I'm pretty sure it's possible to make TextView's text selectable

**Comment by bnknndy** [comment]
> Though I think if we use the Onboarding, it should be after the user created their first note and also should be skippable to prevent overwhelming them🤔

I agree @dorrin-sot. But we can't guarantee someone won't explore card types before they finish creating their first card. (Well, we can, if AD forces people through a process where they create a basic card first. But if a user doesn't *want* to create a basic card first, we risk turning them away.)

Material Tap Target Prompt allows creating robust trigger conditions (really cool). That was what I was referencing when I mentioned we could think about different prompts for those who have cloze cards in their decks already vs those who have no cloze cards at all.

That lets us think about onboarding not as a long process at first run, but instead as a series of self-contained conditional triggers that only activate when users satisfy certain criteria throughout their personal journeys with the app.

Part of that should include never showing more than one prompt per trigger/between user input actions to avoid that overwhelmed sensation and hopefully to reduce the desire to skip. Though a lot of people will always skip because other apps have terrible onboarding...
