### ISSUE TITLE
Error message for missing clozes doesn't provide guidance

### ISSUE THREAD

**Issue by bnknndy** [ankidroid/Anki-Android#11673]
When users attempt to save a new cloze card without clozes in any fields, the error they receive provides no guidance regarding how to create that cloze.

Additionally, the user feels that the cloze icon doesn't provide any help regarding the actual creation of clozes.

![image](https://user-images.githubusercontent.com/7875524/175699433-d189d07d-5822-4dd0-adb1-090e7ba5b685.png)

## Relevant heuristic

 [Help users recognize, diagnose, and recover from errors](https://www.nngroup.com/videos/usability-heuristic-recognize-errors) (*Video only. For a relevant article, consider supplementing with [Error Message Guidelines](https://www.nngroup.com/articles/error-message-guidelines/)*.)

"Clearly inform users when an error occurs, tell users what went wrong (if necessary), and offer a solution."

## Student's severity classification (minor, major, critical)

*Major*, due to:

1. **Frequency**: "This is a common issue for users to encounter because the majority of users will explore various card types and not know how to create a Cloze card type."

2. **Impact**: "The impact is high because it forces users to have to search for a solution and break their user flow when a solution could’ve been given to the user. This is amplified because the icons are not labelled making this necessary for an insert icon that users are not familiar with to have highlighted for the user."

3. **Persistence**: "This issue has low persistence because once the user understands how to create a cloze deletion, they will not encounter this issue."

4. **Weighting**: "The frequency of this issue is common since users will likely explore different card types. The impact is high because the user will have to go outside of the app to search and learn what a cloze deletion is. The persistence is low however, meaning that the user will only have to encounter this issue once to be able to avoid it, making the rating a 3."

This issues comes from [Source file](https://1sfu-my.sharepoint.com/personal/paulh_sfu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team%2Fheuristic%2Deval%2Dexemplary%2D3%2Epdf&parent=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team&ga=1) as discussed in #11664. *Text not wrapped in quotation marks is rewritten for brevity.*

**Comment by BrayanDSO** [comment]
Maybe a snackbar with a button "Show me how" or simply "Help" which will trigger a Onboarding tutorial.

I like it because it isn't intrusive (i.e. won't show if the person already knows how clozes work) and it's easily repeatable, so the user may see the tutorial how many times they want

**Comment by bnknndy** [comment]
> Maybe a snackbar with the same message and a button "Show me how" or simply "Help" which will trigger a Onboarding tutorial.
> 
> I like it because it isn't intrusive (i.e. won't show a tutorial if the person already knows how clozes work) and it's easily repeatable, so the user may see the tutorial how many times they want

That makes sense. I don't think it even needs the description of the error or the link to a "show me how," it can just say "Long-press words in your Text field to create a cloze deletion."

Unless you think the snackbar should pop up a dialog with a little animated GIF, which I could see being useful if people don't understand how to select text (a very real possibility!)
