### ISSUE TITLE
[Bug] Error while importing decks 

### ISSUE THREAD

**Issue by shahrd97** [ankidroid/Anki-Android#11680]
###### Reproduction Steps

1. Click Three dots -> Import -> Deck package 

Or 
Directly open with ankidroid from file manager 

###### Expected Result
The deck should be imported 

###### Actual Result
I get the error "The system does not have an app installed that can perform this action."
![edited](https://user-images.githubusercontent.com/72303955/175208544-5290f269-2e6a-4133-ac67-607a2ffe7903.jpg)

If I open directly open from the file manager, Ankidroid opens and closes and a dialog pops up to report an error. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by prateek-singh-3212** [comment]
Thanks @shahrd97 for reporting this issue. Please share the debug info you can find it in Settings -> Advanced -> About Ankidroid -> Copy Debug info. It will be easier for us to analyse the issue.

**Comment by shahrd97** [comment]
> Thanks @shahrd97 for reporting this issue. Please share the debug info you can find it in Settings -> Advanced -> About Ankidroid -> Copy Debug info. It will be easier for us to analyse the issue.

AnkiDroid Version = 2.16alpha68

Android Version = 10

Manufacturer = realme

Model = RMX2001

Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 10; RMX2001 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.99 Mobile Safari/537.36

ACRA UUID = 0347584a-dbe5-4662-9e7a-a82fd9e02b2a

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by shahrd97** [comment]
Solved it there was an error in my android filepicker app _com.google.android.documentsui_, I reinstalled the app with adb and restarted my phone and importing decks works now.

**Comment by mikehardy** [comment]
Happy to hear you got it working! That is such a strange error - hopefully that doesn't happen to too many people
