### ISSUE TITLE
[Bug] "All decks" doesn't work anymore (in "card browser" and "statistics")

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#11696]
###### Reproduction Steps

1. open the left menu and select "card browser" (or statistics)
2. in the top menu, select "All decks'

###### Expected Result
I should see all the notes from all of my decks (or all the statistics)

###### Actual Result
No cards are displayed and not stats are displayed even though I have done several reviews today (cf the third printscreen)

![1656165980907](https://user-images.githubusercontent.com/15843700/175777159-27c8aad1-6626-406e-ac9d-bdcdf41b25df.jpg)

![1656165980903](https://user-images.githubusercontent.com/15843700/175777166-c8423ba8-21b0-441e-9f4f-d30068367d89.jpg)

![1656165980894](https://user-images.githubusercontent.com/15843700/175777168-4a7e75a2-013e-4605-a500-69c644a90306.jpg)

###### What I tried + possible explanation
I have use "check the database" both in Ankidroid and in Anki desktop several times: it didn't fix this bug

This bug happened after I had a bug for another thing which could be (or not) the cause: when reviewing the last card of a deck, I edited this card and changed its deck. When I saved, I had the bug popup (I don't remember if the app crashed or not). 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) **I installed the latest alpha release (69) and I still have the same problem with "all decks" (the other issue I opened today, concerning the latest releases only concerns opening the deck. I can still see the stats and use the card browser)**

**Comment by mikehardy** [comment]
Hmm - I cannot reproduce this one either, with 2.16alpha69

I don't doubt you are having problems - I'm trying to reproduce and I see your stack trace from the crash you mention here in optional information (pasted into #11695 ) so something is going wrong but I just don't know what :thinking:

**Comment by mikehardy** [comment]
Not sure if it is okay for you or not, I totally understand some collections have private information and are not share-able, however it may help to have your colpkg here for inspection if it is safe to do so

**Comment by MagTun** [comment]
Thanks a lot for your help!

My friend (who has the model of phone than me) was able to update to 69 without any problem, so yes, the problem probably comes from my database and from this bug.

I can share with you my colpkg. But I didn't find how to do it with ankidroid (it exports an apk). I can do it with anki desktop, but it exports all the media from all my decks even though the 2 decks I want to share with you (the one from where the card was from and the one where I sent it) dont' have any media. I don't know how to share with you the information you need.

**Comment by MagTun** [comment]
Thanks a lot for your help!

My friend (who has the model of phone than me) was able to update to 69 without any problem, so yes, the problem probably comes from my database and from this bug.

I can share with you my colpkg. But I didn't find how to do it with ankidroid (it exports an apk). I can do it with anki desktop, but it exports all the media from all my decks (it takes ages and will be heavy!) even though the 2 decks I want to share with you (the one from where the card was from and the one where I sent it) dont' have any media. I don't know how I can share with you the information you need.

**Comment by MagTun** [comment]
Thanks to the log you shared in my other issue, I was able to find the card that caused the very first bug (when I edited the last card of a deck and changed its deck). I deleted this card, check the db, but it didn't solve the bug with "all decks": the card browser and the stats are still empty.

**Comment by MagTun** [comment]
I just found a way to use the "carb browser" on "all decks". I don't know if this could help to find the origin of this bug but here it is:

1. open card browser. If I choose "all decks", the list is empty and "0 card" is still written just beneath the menu.
2. choose another deck (any one)
3. do a search for any word
4. click on "search all decks" at the bottom of the screen
5. tada! all matching cards, from all decks are shown. I can even press the back arrow and see "all decks ... 60938 cards"! I can even do another search on "all decks"! 

But: 
- if I reselect "all decks" again from the menu, I get the empty screen again.
- the statistics page never works on "all decks", even if I switch directly to "statistics"
- I am still unable to update to the latest alpha

So it doesn't fix anything but the difference in the way the search is done when performs via the menu compared to via the "search all decks" at the bottom, could give a clue.

**Comment by MagTun** [comment]
I was trying to reinstall the backup saved just before the [crash](https://github.com/ankidroid/Anki-Android/issues/11695#issuecomment-1166308780) to see if it may debug something but it didn't. 

But I discover that what you meant by sending you the "colpkg" may not be the files I send you. I send you the 2 buggy decks (as a deck can be exported as colpgk I thought that's what you meant). But I just saw that the backups are saved as "colpkg", which I guess is what you really meant. Just in case this is the case, I am sending you 2 backup (on your email written on your github profile): 
- the first one (saved just before the crash)
- the second one (saved a couple of hours after it) 

I have reinstalled both of them and I confirm that I don't have the bug with 'all decks" with the first backup, but I do have the bug with the second one.

**Comment by mikehardy** [comment]
What luck, I had need to test import and export of colpkg files for #11644 :-), so I tested yours.

The problem with your later colpkg is that for some reason you actually have a deck that is really named "All Decks". Why? I don't know, but if you long-press and delete that deck, then when I go to the card browser and choose all decks I actually get "All Decks" as in all of your decks vs "All Decks" the named deck with no cards.

Maybe that helps?

**Comment by MagTun** [comment]
Thanks a lot your help and yes it's working!  feel really embarrassed to have bother for a problem with such a simple solution. I am sorry for that, I should have check my decks more carefully.

One thing that is strange is that I really don't remember having created it. Could it have been created automatically by the bug that happened when changing the deck of the last card of a review?

So this bug is fixed (I will close this issue), but I am still [unable to update to alpha 66 and above](https://github.com/ankidroid/Anki-Android/issues/11695). I have created a new bug report and sent you a new colpkg (more details on the other issue).

Again sorry for that and thanks so much for your time!

**Comment by mikehardy** [comment]
No worries - I appreciate the bug reports and for this one in particular I was testing something else and literally had a moment where I thought "If only I had a collection package at hand since I really need to test collection package import" and...there it was :-). Sometimes things are easier than they seem. Sometimes harder :-). This was easier. Cheers
