### ISSUE TITLE
[Bug] alpha 69 does not sync

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#11692]
###### Reproduction Steps

1. Use alpha 68, 69 parallel A
2. Try sync
3. Get error

###### Expected Result
The version from Play Store (installed in parallel) syncs successfully 

###### Actual Result
Error
![Screenshot_20220625-130857_AnkiDroid A](https://user-images.githubusercontent.com/7422433/175769038-42f954cb-3781-47a1-96a8-b9bd8f311262.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha69

Android Version = 12

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; ONEPLUS A6003 Build/SQ3A.220605.009.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36

ACRA UUID = 79dddeac-0bae-4534-bd39-9621f65c69bc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I think you have an actual network error *or* ankiweb was perhaps down for a while
I just tried 2.16alpha69.A and 2.16alpha69 and both sync fine for me

Additionally sync13.ankiweb.net does respond to ping :shrug:  --> can't reproduce right now - we can reopen if still happening, ideally with corroboration from someone else

**Comment by homocomputeris** [comment]
Thanks for checking it.
Probably something strangely specific for my case. Although strage taking into account the fact everything syncs on the same device in the release version
