### ISSUE TITLE
[Bug] swipe back in card browser doesn't apply the change we made (by editing a card or deleting it)

### ISSUE THREAD

**Issue by WiliTest** [ankidroid/Anki-Android#11698]
###### Reproduction Steps

1. Click on a deck to review your card 
2. Select some words on your card, 
3. On the menu chose "Card Browser"  
4. Then click on the card to edit it (or delete it)  ★
5. apply the change
6. then swipe left to exit the search.
7. then swipe left again to go back on the reviewing panel.

★: (I often use this trick to correct or merge several notes from the same deck that contains the same word as they will be all opened in the card browser) 

###### Expected Result

When coming back on the reviewing, we should see
- (if I edited the card) the change I made
- (if I deleted the card) the next card

###### Actual Result

- (if I edited the card) the change doesn't show (to see it, we need to pass it, then to undo)
- (if I deleted the card) I'm reviewing the card I just deleted

ps: it's not a new bug, I struggled with it for a long time but did not take the time to report it. I just notice an improvement when I used the version Alpha62 (which could have been solved before as I do not try each version): the app ceased to crashed after 1) I deleted a note (step 4 above) and then came back on the deck, and 2) I pressed "again" to get rid of the deleted note showing again (it crashed when the note came back in the review which is logical). Now it's not crashing anymore, but the deleted note in the browser should not appear in the reviewing.

###### Debug info
AnkiDroid Version = 2.16alpha69

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.125 Mobile Safari/537.36

ACRA UUID = 06e6dc69-fef2-4e49-a15a-2b41ca4d7007

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
It's somewhat related to #11046 on the topic of "Reviewer not reloading after changes"

In the case of this issue since this was triggered by the context menu (i.e. not from a `startActivityForResult()` launched from the Reviewer), the reviewer doesn't get the result that the card browser changed the collection and that it should reload.
