### ISSUE TITLE
Small tap targets for single-line cards

### ISSUE THREAD

**Issue by bnknndy** [ankidroid/Anki-Android#11690]
Single-line cards offer much smaller tap targets than multiline cards.

Specifically, the student feels the tap targets are too small to reliably prevent user error when selecting single-line cards.

![image](https://user-images.githubusercontent.com/7875524/175721130-5a5b7a3d-997b-4a3f-960d-cf2f3bcd34fe.png)

## Relevant heuristic

 [Error prevention](https://www.nngroup.com/articles/slips)

"Prevent unconscious errors by offering suggestions, utilizing constraints, and being flexible."

## Student's severity classification (minor, major, critical)

Minor, due to:

1. **Frequency**: "The frequency of this issue depends on the type of content the user is studying. If the user studies predominantly cards with large amounts of information, then it will rarely occur, but if they are studying cards that tend to only be one line of content, then it can happen quite frequently."

2. **Impact**: "This issue is moderately easy to overcome since the user can simply go back to tap the correct card, but it takes a few extra seconds each time they make an error (or if they are trying to be extra careful to tap the correct card), which can add up in terms of frustration."

3. **Persistence**: "This problem can be more permanently overcome if the user changes the font size in the setting, but since the default font size is so small and the user may not be aware that changing font size is an option, this can be a persisting issue."

4. **Weighting**: "Though this is an issue that can be overcome by changing the settings or mitigated by going back after tapping the wrong card, the fact that the problem arises due to default settings means that the user may not know about the alternate options. Therefore, it is frustrating enough that it is deserving of a severity of two."

This issues comes from [Source file](https://1sfu-my.sharepoint.com/personal/paulh_sfu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team%2Fheuristic%2Deval%2Dexemplary%2D4%2Epdf&parent=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team&ga=1) as discussed in #11664. *Text not wrapped in quotation marks is rewritten for brevity.*

**Comment by bnknndy** [comment]
[Material guidelines](https://material.io/design/usability/accessibility.html#layout-and-typography) suggest a touch target minimum of 48x48

> For most platforms, consider making touch targets at least 48 x 48 dp. A touch target of this size results in a physical size of about 9mm, regardless of screen size. The recommended target size for touchscreen elements is 7-10mm. It may be appropriate to use larger touch targets to accommodate a larger spectrum of users.

If the current one-line card has a touch target smaller than that, that might be an issue, but if it's larger, does it really matter? Tagging you @viciousAegis since this concerns the browser ux

**Comment by viciousAegis** [comment]
@bnknndy I mentioned this in my proposal as well, that the minimum number of lines shown should at least be 2/3. That's a simple change and should not take me long 👍

**Comment by Arthur-Milchior** [comment]
> @bnknndy I mentioned this in my proposal as well, that the minimum number of lines shown should at least be 2/3. That's a simple change and should not take me long +1

Thanks. I was pretty sure I saw it somewhere.
I fear that I did read far too many proposal to have those in memory. Even while I did re-read the four selected ones.
