### ISSUE TITLE
[Bug] Unlike Anki Desktop, trying to delete Default deck doesn't delete its notes

### ISSUE THREAD

**Issue by dorrin-sot** [ankidroid/Anki-Android#11703]
###### Reproduction Steps

0. If Default deck is empty, create some notes in it
1. Tap and hold Default deck
2. Choose "Delete deck"

###### Expected Result
All notes inside it would be deleted and then the error "The default deck can't be deleted" is shown

###### Actual Result
Only the error "The default deck can't be deleted" is shown

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
@mikehardy can i work on this issue

**Comment by mikehardy** [comment]
@Prince-kushwaha sure! Can you please do me a favor and double-check that anki desktop does actually do exactly what is described? Just to make sure - I don't use it personally and this involves destruction of user data (with the delete) so making sure is worth it. Then absolutely
