### ISSUE TITLE
If Rust lib fails to load, show user an appropriate error message

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#11700]
Context: We are about to drop the legacy Java anki lib, and rely completely on the Rust lib. So if the Rust lib fails to load there will be no collection access, but it is not because of corruption

Related #11644 / #11581

----

Architecturally, I don't mind as long as there's a cleanup attribute.

When this causes a crash, the user won't have migrated to the new storage mechanism, and their collection will be safe, allowing them to downgrade.

But, we shouldn't show the regular 'collection open failed' message here, as that provides incorrect solutions to this issue.

![image](https://user-images.githubusercontent.com/62114487/173700475-abddd89f-ab9f-48fe-b6c0-4eb58e82eb39.png)
![image](https://user-images.githubusercontent.com/62114487/173700484-24430e7c-c88f-479f-9aca-39333937a7c9.png)

I'd accept either:
1. throw an `Error` if `NativeMethods.ensureSetup()` fails (to hard crash the app)
2. Expose the exception from `NativeMethods` and check in `DatabaseErrorDialog`

I'd prefer `1` for now, with a cleanup attribute to move to `2`, to retain velocity

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/11581#pullrequestreview-1006653389_

**Comment by mikehardy** [comment]
Sure! That would be nice

**Comment by parthn2** [comment]
@mikehardy, Can you help me with recreating this? I am not able to do it myself and I believe It would help me understand how is the whole thing working.

**Comment by mikehardy** [comment]
The best way is probably to go right in to the code that can throw, and for development purposes, manually add code that throws the exception. Directly mess the code up in other words so it never loads the library correctly

**Comment by mikehardy** [comment]
Definitely rebase over main / make sure you have the most up to date code before starting on this, as I just merged the PR where the issue came up (#11644) and it changed everything in the area related to rust library loading
