### ISSUE TITLE
"Anking Overhaul Note Type Hint Buttons" are not compatible with the Ankidroid "Show Hint" controller command

### ISSUE THREAD

**Issue by SoftSalem** [ankidroid/Anki-Android#11709]
###### Reproduction Steps

1. Review an Anking flashcard in Ankidroid (Or any flashcard that uses buttons in the note type to show and hide hints)
2. Press the button of your bluetooth controller, cellphone, etc that is linked to the Ankidroid controller settings "show hint" cmd. (cmd = command)

###### Expected Result
Pressing the button that activates the"show hint" cmd of my ankidroid app should reveal the flashcard hint AND scroll the flashcard down because the note type has this code:
   `var ScrollToButton = true;`

So what it is expected is that when the button of the note type is activated by the "show hint"cmd, the flashcard not only reveal the hint, but scroll the screen where the hint is supposed to be.

###### Actual Result
Instead of showing the hint AND scroll down, the "show hint" cmd does reveal the hint, but it also makes the flashard jump back up to the top every single time is pressed. The only way to get the correct scroll function is by touching the note type buttons in the screen, directly with the fingers.

Even if you manually scrolled down, activating the "show hint"cmd will only  jump back up to the top again and again.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ X] I have searched for similar existing issues here and on the user forum
- [X ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SoftSalem** [comment]
This is what is going on

![2022-06-27_1656314974318 (1)](https://user-images.githubusercontent.com/104769180/175963899-8ddff1c1-4cff-4b6a-8699-99f3216310ec.gif)

**Comment by SoftSalem** [comment]
Got this[visual example ](https://ibb.co/hd1mcK0)  

I opened the First Aid field using my Bluetooth controller and it did open, but it also jumps automatically at the top of the flashcard. (I did this with all the fields but the video was too heavy to upload here).

**Comment by BrayanDSO** [comment]
It scrolls on my PS4 controller and with `Tap` gestures, but not with swipe gestures.

IMO, the tweaking should be probably better done on Anking's notetype rather than AnkiDroid. Have you tried contacting the AnkiPalace?

**Comment by SoftSalem** [comment]
I will contact him, probably the notetype should be modified, but I find it really strange that it works on other devices like yours.

So you have an specific button on your PS4 controller that is synchronized to the "show hint" option on your phone, and it does automatically scroll?

**Comment by SoftSalem** [comment]
I will contact him, buy your right, probably the notetype should be modified, but I find it really strange that it works on other devices like yours.

So you have an specific button on your PS4 controller that is synchronized to the "show hint" option on your phone, and it does automatically scroll?

**Comment by BrayanDSO** [comment]
> So you have an specific button on your PS4 controller that is synchronized to the "show hint" option on your phone, and it does automatically scroll?

Exactly

When you contact Anking, you can send this link (https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/assets/scripts/card.js#L264-L278) as it is the current implementation of the show hints. Quite similar to the `Hint reveal hotkeys` addon. It should help
