### ISSUE TITLE
[Bug]Kotlin conversion tools uses backtick instead of []

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11705]
###### Reproduction Steps

1. Search for a file with `{@code foo}`
2. automatically convert it to kotlin

###### Expected Result

`[foo]`

###### Actual Result

```
`foo`
```

###### Debug info

Since we won't fix the correction tool, if someone is good with script, it may be helpful to adapt the ./tools/convert.sh script so that:
* for each `{@code foo}` it finds in deleted java
* it replaces backquoted `foo` by square-bracketed `foo`
* it amend previous commit

I suspect that the risk of wrong change from backquote from square bracket is low enough that it's worth checking it during code review only

Relatedly, I guess a general tool to transform backquote to square bracket may be nice too; to eventually clean everything that needs cleaning. But I suspect a general sed regexp may get this almost right

**Comment by david-allison** [comment]
That's a correct conversion. we should be using `{@link }` in the Java.

**Comment by Arthur-Milchior** [comment]
Oh, makes total sense. 
Yeah, then I guess the correct task would have been to transform `@code` into `@link`

**Comment by Arthur-Milchior** [comment]
Except that if I try to do so, android-studio don't accept it, because it doesn't know link to local argument :(
