### ISSUE TITLE
Side-nav hides core functionality

### ISSUE THREAD

**Issue by bnknndy** [ankidroid/Anki-Android#11723]
A hamburger menu hides the card browser.

Specifically, the student identifies 3 critical functions of AnkiDroid: creating, studying, and editing cards. However, to edit cards, users need to access the browser through a hamburger menu, which may be too far removed from the main screen for a core use.

![image](https://user-images.githubusercontent.com/7875524/176256761-39ac0888-22a9-4ffe-8cec-d5be453f6ca6.png)

## Relevant heuristic

 [Aesthetic and minimalist design](https://www.nngroup.com/videos/aesthetic-and-minimalist-design) (*Video only. For a relevant article, consider supplementing with [Signal-to-Noise Ratio](https://www.nngroup.com/articles/signal-noise-ratio/).*)

"Ensure that the visual elements of the interface support the user's primary goals."

## Student's severity classification (minor, major, critical)

Minor, due to:

1. **Frequency**: "This is a common problem, as a core functionality of the application is for users to edit the cards in a deck, or check which cards are in the decks. As a result, accessing the card browser page is an action users will want to perform often, and should not be hidden in the default loadout of the application."

2. **Impact**: "This issue is moderately easy to overcome since the problem diminishes as users become more familiar with the interface. However, **it presents a steeper learning curve at the beginning, when users have to learn that there is a menu item for navigating to the deck, and pressing the decks themselves launches into a study session immediately**" [*Ben's note: I emphasized this part because it appears the student initially thought they could access a given deck's cards by tapping said deck, which seems important.*]

3. **Persistence**: "This is a highly persistent issue as users must open the menu every time to remember the path to navigate to the card browser tab. However, the persistence decreases over time as users become familiar with tapping the hamburger menu for this particular action."

4. **Weighting**: "This issue has high frequency and persistence that decreases over time as users become more familiar with the system. However, the initial learning curve it presents hinders new users from effectively accessing a core functionality of this application, which is why it is still significant enough to warrant a severity of two."

This issues comes from [Source file](https://1sfu-my.sharepoint.com/personal/paulh_sfu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team%2Fheuristic%2Deval%2Dexemplary%2D4%2Epdf&parent=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team&ga=1) as discussed in #11664. *Text not wrapped in quotation marks is rewritten for brevity.*

**Comment by BrayanDSO** [comment]
I hava a concept in mind for a bottom bar navigation for AnkiDroid which should deprecate the navigation drawer and solve this one. I should do a mock design of it eventually.

Unfortunately, I won't have time for it until GSoC it's done

**Comment by viciousAegis** [comment]
Here's a concept of a bottom nav I created, not sure if I will implement it during GSoC though
![image](https://user-images.githubusercontent.com/86671025/176442052-e574a452-4879-49ca-8d44-c68f3deabe7a.png)

**Comment by snowtimeglass** [comment]
Thanks for the analysis and the concept. As one of the users who use the card browser frequently, I am interested in this topic.
