### ISSUE TITLE
Users may struggle to find functions hidden in menus

### ISSUE THREAD

**Issue by bnknndy** [ankidroid/Anki-Android#11722]
Users may have trouble remembering where things are.

Specifically, the student highlighted two issues:

* Three-dot menus could confound users by representing different functions in every screen, making it difficult to develop consistent expectations for use.

* Functions such as "delete note" will be difficult to access easily, because rather than recognizing a common icon, users will have to remember where to find the control for it every time.
![image](https://user-images.githubusercontent.com/7875524/176254583-cafcc7d2-ccfb-4179-a23f-e6a278ad3afe.png)

## Relevant heuristic

 [Recognition rather than recall](https://www.nngroup.com/articles/recognition-and-recall/)

"Showing users things they can recognize improves usability over needing to recall items from scratch because the extra context helps users retrieve information from memory."

## Student's severity classification (minor, major, critical)

Critical, due to:

1. **Frequency**: "This is a common issue since it occurs every time the user switches screens in the application and is looking for functionality beyond creating a new card or deck, or studying from an existing deck. Since editing and deleting cards are quite important secondary features of this application, users will be performing these actions quite frequently."

2. **Impact**: "This issue is moderately difficult to overcome given the number of functions that are hidden in the three-dot menu. In order to eliminate this problem, users have to remember both the functions important to them and which page each function belongs to, which can take some getting used to due to the number of options available."

3. **Persistence**: "This is a recurring issue as users will continue having the problem of needing to remember which functions are available to them on what page until they become more accustomed to the application, which can be a timely process."

4. **Weighting**: "The three-dot menu hides a multitude of options, so it’s difficult for the user to remember them. Moreover, even if the user only wants to use a few functions, they can still easily forget where they are because the options are different for each screen. Therefore, this problem scores high across all three factors, and is deserving of a four."

This issues comes from [Source file](https://1sfu-my.sharepoint.com/personal/paulh_sfu_ca/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team%2Fheuristic%2Deval%2Dexemplary%2D4%2Epdf&parent=%2Fpersonal%2Fpaulh%5Fsfu%5Fca%2FDocuments%2FCMPT%2D363%2D222%2Fassignments%2Fassignment%2D1%2Fankidroid%20flashcards%20team&ga=1) as discussed in #11664. *Text not wrapped in quotation marks is rewritten for brevity.*

**Comment by BrayanDSO** [comment]
> I don't know of any best practices that state you should maintain continuity across every three-dot in an experience.

Neither do I   ¯\_╏ ՞ ︿ ՞ ╏_/¯
