### ISSUE TITLE
[Bug] Reviewing with Fullscreen mode set to Hide system bars leaves the status bar (notification bar) empty

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#11747]
###### Reproduction Steps

1. in Settings → Appearance, set Fullscreen mode to Hide system bars
2. Review a card

###### Expected Result

Either:
 * the reviewer extends to the very top of the screen, or,
 * if “system bars” means only the toolbar, system bar icons are visible.

###### Actual Result

There's empty space where the status bar is normally located:

<img src=https://user-images.githubusercontent.com/1710718/176735817-1f21fefe-a12a-4edd-915d-87f1406bca03.png width=300>

###### Debug info

AnkiDroid Version = 2.16alpha70

Android Version = 11

Manufacturer = Xiaomi

Model = Mi A2

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Mi A2 Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36

ACRA UUID = 265fa358-f0e1-4fd2-9858-aa352ae60d78

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dorrin-sot** [comment]
@mikehardy Can I work on this?

**Comment by mikehardy** [comment]
Have a blast 😂

**Comment by oakkitten** [comment]
I didn't mean to hijack this but I looked into this while I was offline and had everything ready. Hope you didn't waste time working on this! A rather straightforward fix, anyway.
