### ISSUE TITLE
navigation/status bar color

### ISSUE THREAD

**Issue by andsofine** [ankidroid/Anki-Android#11754]
change navigation bar color to background color in light/dark themes
change status bar color to toolbar color
![AFFIX_20220702_043848.png](https://user-images.githubusercontent.com/99369164/176981955-2d4c857a-73d6-4210-a84a-4213f75a8ae7.png)

**Comment by BrayanDSO** [comment]
There is a active pull request implementing this (#11236), so it may be merged soon
