### ISSUE TITLE
The long press menu of decks is broken

### ISSUE THREAD

**Issue by Throlo** [ankidroid/Anki-Android#11786]
When you long press a deck and touch a option anki does another. 
Examples: 

- Long press (LP) > Browse cards > go to rename deck

- LP > Rename deck > open deck options
- LP > Create subdeck > go to custom study options
- **LP > Deck options > Deletes the deck**
- LP > Custom study > go to export deck
- LP > Export deck > apparently nothing happens
- LP > Create shortcut >  a brief loading screen, and apparently nothing happens
- LP > Delete deck > same as above

Anki version: Alpha 71 (It does not occurs in previus alphas)

**Comment by mikehardy** [comment]
Oh noooo - that's terrible, the delete deck risk is of course the worst but all of it is pretty serious, thank you for reporting this so quickly

**Comment by mikehardy** [comment]
Thanks again for reporting this and @lukstbit for a quick PR aimed at fixing it - alpha72 is processing right now and hopefully lines the actions up with the menu items again

**Comment by Throlo** [comment]
You fixed it very quickly, thanks!
