### ISSUE TITLE
deprecation: Material Dialog neutral button

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#11780]
Please log an issue to track this

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/11646#discussion_r913977376_

**Comment by dorrin-sot** [comment]
Can I work on this?

**Comment by mikehardy** [comment]
I always felt like "email" was a bit strange as a fixed choice, I would favor at least just opening it to a normal share picker. Share usually lets you save as an option too doesn't it?

**Comment by dorrin-sot** [comment]
> I always felt like "email" was a bit strange as a fixed choice, I would favor at least just opening it to a normal share picker. Share usually lets you save as an option too doesn't it? 

I think it does in some phones but it didn't in mine

**Comment by dorrin-sot** [comment]
I actually just committed a "save to file" button in the share bottomsheet

**Comment by mikehardy** [comment]
if it has save file, I'm okay with 2 buttons, and I agree widening the share possibility is actually a big plus, so for this case, this could work for me

The general idea of case-by-case thought is something I agree with to though
