### ISSUE TITLE
Add regression test for long press menu of DeckPicker

### ISSUE THREAD

**Issue by ShridharGoel** [ankidroid/Anki-Android#11790]
Material dialogs library update resulted in a bug where the option name and functionality were not aligned. This was fixed in https://github.com/ankidroid/Anki-Android/pull/11788.

**Comment by dorrin-sot** [comment]
Is there a way to programmatically click on an item in DeckPickerContextMenu?

**Comment by dorrin-sot** [comment]
Can I work on this?
