### ISSUE TITLE
[Bug] cannot remove user-defined toolbar button

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#11806]
A user-defined toolbar button **cannot** be removed by long pressing the button and selecting "Delete".

![Screenshot_20220708-234546_AnkiDroidA](https://user-images.githubusercontent.com/10192661/178093969-a824d828-e157-4743-a969-23f8e778e53f.png)

###### Reproduction Steps

1. Edit a note
2. Create a toolbar button (press "+" and follow instructions)
3. Long press the button

###### Expected Result
It is possible to delete the button (as mentioned in the user manual)

###### Actual Result
The option "delete" is not there

###### Debug info
AnkiDroid Version = 2.16alpha72

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 49704c83-4498-4347-84c4-2988936a699f

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
@lukstbit not tagging you because you are obligated to do any thing at all, but you seem to be squashing all these dialog mis-mapping issues and this smells like another one from the material dialog conversion. The button/action mappings appear to have taken quite the load of issues from that one :weary:

**Comment by lukstbit** [comment]
@mikehardy I've made a PR.
Also I'm looking at all these issues related to material dialogs library, if you see one feel free to assign me for a ping.

**Comment by mikehardy** [comment]
I just triggered the publish process for the fixes by @lukstbit of this one and the other one you logged @pavreh - thanks so much for testing our alpha builds and taking the time to log issues, we really appreciate it
