### ISSUE TITLE
[Bug] The setting Full screen navigation drawer is not immediately applied to activities lower in the stack

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#11813]
###### Reproduction Steps

1. Have the setting Full screen navigation drawer off;
1. Open Decks;
1. Open Card browser;
1. Open settings, change Full screen navigation drawer to on;
1. Press back. Observe that the setting works in Card browser;
1. Press back. Observe that the setting does not work in Decks.

###### Expected Result

Setting works immediately.

###### Actual Result

Setting doesn't immediately work, works after restart.

###### Debug info

AnkiDroid Version = 2.16alpha70

Android Version = 11

Manufacturer = Xiaomi

Model = Mi A2

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Mi A2 Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/102.0.5005.78 Mobile Safari/537.36

ACRA UUID = 265fa358-f0e1-4fd2-9858-aa352ae60d78

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Actually, any setting isn't updated to activities lower in the stack

See #11046 and #11698

**Comment by oakkitten** [comment]
Ah! Missed those. Closing as a duplicate.
