### ISSUE TITLE
Check database is inaccessible when collection error

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#11819]
When an error of the database occurres, there is an advice to run check database in a dialog (see picture 1). But check database is not present in the options so it is not possible to run check database (see picture 2)
![Screenshot_20220709-192636_AnkiDroidA](https://user-images.githubusercontent.com/10192661/178134063-a6a02cbb-9d44-494c-a387-38ebd0245c66.png)
_Picture 1_
![Screenshot_20220709-192650_AnkiDroidA](https://user-images.githubusercontent.com/10192661/178133779-c691454d-cb8e-4ae5-a637-070cb42c5443.png)
_Picture 2_

###### Debug info
AnkiDroid Version = 2.16alpha73

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 49704c83-4498-4347-84c4-2988936a699f

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
This is a string issue. We can't perform 'check database' as in this case the collection was not open:

https://github.com/ankidroid/Anki-Android/blob/8aa0570ae1d28678558cfce01c6fdb20dfeeacbc/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.kt#L112-L120
