### ISSUE TITLE
[Bug] Incompatible database version dialog - Restore from backup doesn't work

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#11811]
###### Reproduction Steps

1. Change the database version by a db editor
2. Start Ankidroid
3. Press "Restore from backup"
![Screenshot_20220709-160247_AnkiDroidA](https://user-images.githubusercontent.com/10192661/178110457-c4a4b013-e2a6-4055-9d5f-c7ba3c331ed4.png)

###### Expected Result
A backup is restored

###### Actual Result
Nothing happened

###### Debug info
AnkiDroid Version = 2.16alpha73

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 49704c83-4498-4347-84c4-2988936a699f

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
If you are running a development version and open the developers options menu you can tap the button to use V16+ database and this should work. We are almost up to current database schemas (using desktop as reference for 'current' but these are serious changes so we've hidden them behind development flags at the moment.

I *think* you are testing release versions (not locally built versions, is that correct? If so you won't have the developers menu so you won't be able to check but that's okay. I appreciate all your testing!

**Comment by pavreh** [comment]
Yes, I am testing the release versions. I thought it could be another dialog mis-mapping issue as recently. If this is not the case we can close this issue.

**Comment by mikehardy** [comment]
Oh I see what you mean, I think.
Do you mean that when you press that dialog choice for restore from backup, nothing happens at all? If so that does sound like an issue related to dialog options that may be related to material dialog update

**Comment by mikehardy** [comment]
maybe @lukstbit wants to have a look at yet another dialog issue 😅

**Comment by lukstbit** [comment]
Yes, the dialog option wasn't triggered. Made a PR for this in #11839
