### ISSUE TITLE
java.util.zip.ZipException. error in opening zip file. on Galaxy S4 minis[Bug]

### ISSUE THREAD

**Issue by misanthropos** [ankidroid/Anki-Android#11856]
Years ago I created a stack with pictures of corals and their corresponding names. Because of the included images that card deck is bigger in size than the usual stacks. Synchronizing from a Galaxy S6 Edge forward does not pose any problems. However syncing always fails with mentioned error window popping up.

Is the Zip library using a CPU instruction unknown to the S4 Mini??

I have tried lineage in different versions, even other custom ROMs. All show the same behaviour. I tried a different S4 mini. Same result.

The cardstack which I think does problems is added as attachment.

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = GT-I9195I

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; GT-I9195I Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.50 Mobile Safari/537.36

ACRA UUID = b4009b2a-562b-4b3b-8f17-51b436580901

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true
###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

[corales-20220715112517.apkg.zip](https://github.com/ankidroid/Anki-Android/files/9119621/corales-20220715112517.apkg.zip)

**Comment by misanthropos** [comment]
Annotation: Removing the corales deck does not solve the problem. So the  problem arises after loading up about 10k of data.

**Comment by slavistan** [comment]
I'm having the same problem on a Galaxy Note 4 (SM-910F) using LineageOS. The error started to occur a few weeks ago, seemingly out of nowhere.

![image](https://user-images.githubusercontent.com/35600954/180395927-838ed92a-114b-4511-a2ee-153122a5204c.png)

Despite the error, the sync seems to work. Any learned and new cards are synchronized to my desktop app, but the synchronization always shows the error in the end when done on my phone.

**Comment by slavistan** [comment]
@misanthropos After removing the deck did you delete the trash prior to syncing? I don't know whether deleted items are synchronized or not. Might be worth a try.

**Comment by misanthropos** [comment]
AFAIK there is no trash. At least I could not find any on Lineage 18.1.
A full sync from AnkiWeb will show the error popup window.

**Comment by slavistan** [comment]
![image](https://user-images.githubusercontent.com/35600954/180606455-b7a4a999-7293-4608-9179-d2d2e645328a.png)

If you delete a card with media, then open the `check media` dialogue, there'll be a button to delete unused media. After deletion, the media will have landed in the trash. Afterwards, you'll have the option to empty the trash.
