### ISSUE TITLE
Replace "Add note" by "Add"

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11861]
So, here are the places where `Add Note` is used:

- One of the 3 app shortcuts
- NoteEditor
- FAB
- Gestures selection
- Reviewer menu

Following @brayanDSO analysis, we want to keep the string in Gesture and reviewer menu, and change the other ones. 

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/10853#issuecomment-1112735559_ 

After two months, I assume original author @Shane-Patrick-Roach won't finish it. I don't think it's worth to use the original PR, given that it's a single line and we won't keep it. However, it may still be polite to credit it, as this author bringed the original idea to us.

**Comment by shaiguelman** [comment]
Could I take over this?

**Comment by Arthur-Milchior** [comment]
I'm quite sorry @shaiguelman because someone already sent a PR before you asked.
FYI, in general you can just put a note stating you'll start working on it. The only time we really require someone to ask us first is during Google Summer of Code selection due to the number of participant. So feel free tof ind another task that seems relevant to your interest

**Comment by shaiguelman** [comment]
Ah no worries thanks for the explanation.
