### ISSUE TITLE
[Bug] Flag icon doesn't use the correct color on the app bar on day themes

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#11868]
On main c0a9657

They should be white
![image](https://user-images.githubusercontent.com/69634269/179354448-f501cfad-363e-4f4f-b91c-fed91d89ad3b.png)

![image](https://user-images.githubusercontent.com/69634269/179354454-339f5c37-de75-48e0-8bd7-d7dcea8b955f.png)

###### Debug info
```
AnkiDroid Version = 2.16alpha73

Android Version = 7.1.1

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 7.1.1; Android SDK built for x86 Build/NYC; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = 65fcb988-cf49-45da-9532-79e558f9b514

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
[cause](https://github.com/ankidroid/Anki-Android/commit/f0e4ceb6237002ed3c9ab21b99081fc744b930fd#diff-f8131e95f2af6b71f6d8736672745f572e4a8c292888458c78cc76da99a35bd2R4). Pinging @viciousAegis

**Comment by viciousAegis** [comment]
On it 👍🏼
