### ISSUE TITLE
[Bug] card editor - context menu does not work

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#11865]
###### Reproduction Steps

1. Edit a note
2. Long press in a field
3. Press one of the following: cut, copy, select all, undo, clipboard, paste as plain text

###### Expected Result
Selected option is performed

###### Actual Result
Selected option is not performed. E.g. the text is not cut, copied and so on.
Paste works.

###### Debug info
AnkiDroid Version = 2.16alpha73

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 49704c83-4498-4347-84c4-2988936a699f

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
This was introduced in 0527ea0f84 .
@dorrin-sot Could you please have a look at this as it was your PR?

**Comment by dorrin-sot** [comment]
@lukstbit Sure!
