### ISSUE TITLE
Add comment to xml layouts

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11878]
We have 81 layouts defined in XML (only counting the ones in https://github.com/ankidroid/Anki-Android/tree/main/AnkiDroid/src/main/res/layout ). I find it hard sometime to know what they represents and the goal of this issue is to improve it.

If other maintainers approve, one way to do it would be, for each layout `la.xml`:
* create a root folder "screenshot" and add a low quality (to save space) screenshot "la.png", potentially "la_big.png" if it differs considerably on tablet, or "la2.png" if the same layout differs considerably in multiple places 
* add a comment `<!--- --->` indicating how to open this layout (some layouts can be accessed in multiple way, but I can trust contributors to be reasonable in their description and not do an exhaustive list the 15 places that use the Toolbar layout). When the layout does not appear in full screen, a red rectangle should indicates the part of the screenshot that contains the layout
* also put the url on github of la.png so that the person looking can directly copy past the link, or see the name of the file and open it on their folder. (I would consider using relative path, but I don't see how to tell android studio to recognize a relative path in a comment in xml, especially since the goal is that those screenshots are not considered part of the source resources)

As an example, I lost some time on https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/res/layout/deck_picker_dialog_list_item.xml . I didn't understand at first that it was NOT in the Deck Picker window, but in the "add card" window, when you select a deck. A picture, or even just a text stating it, would help a lot. 

As a last request, it may be nice to have a linter that check whether there is at least a comment.

**Comment by david-allison** [comment]
This doesn't seem worth the effort currently. There's much more high priority work to do

**Comment by Arthur-Milchior** [comment]
I am confused. I agree it would not be worth the effort for more experienced contributor. But some people are willing to help and not yet knowledgeable enough to be given high priority work to do.
As far as I'm concerned, having those comments would have saved me quite some time this after-noon, when I was reviewing some other PR and I had trouble understanding what a layout did. And I hope most layouts can be done without too much difficulty by people wanting to discover the codebase

**Comment by david-allison** [comment]
This makes it harder for **everyone** to modify layouts, as they have to update the screenshots. It's a large amount of work now, and it makes everyone's workflow more unpleasant when dealing with layouts. This makes the developer experience worse.

From a technical argument: It bloats the repository, and it needlessly replaces the in-built IDE tools to determine where a layout file is used.

It feels like we want:

* a targeted change to rename files with `deck_picker_dialog...` to `deck_selection_dialog...`
* a better understanding of how to use the IDE preview for layouts, and using `Find Usages` on the ID of a layout from the XML to see where it's used.

**Comment by Arthur-Milchior** [comment]
For new layouts, we'll want a screenshot anyway to upload for context for translators. (Unless there is no text in the layout, which does not seem to occur that often). Also, hopefully, someone creating or changing a layout will test their code and open the layout on a device to ensure it gets the right result, and probably will need a screenshot to illustrate their PR. I am thus far from convinced that it adds that much pain to creating the change. Plus, code being read far more often that written, I am still in favor of optimizing to help reading. Unless there is some reason to believe that the complexity of creating PR has actually impeded or development, which I have no reason to believe up to know, given that the time taken for review has often be the blocking part.

But even comment without screenshot would help.
My point was not about the name of deck_picker_dialog... there are other that I find complex. But to keep this example, it's easy to see it's used only in `adjustToolbar` in `DeckSelectionDialog`, which itself is documented. So, it's indeed already possible to find this kind of informations with tools. 

I prefer to have a self-contained git repo, with most useful information. But since we already trust github, we could also just add screenshots in the PR (which we often do) and add a link to the image's URL on github. This way, no extra download for the developers, and still a screenshot accessible

**Comment by david-allison** [comment]
Screenshots don't need to be updated if a layout changes. They typically need to be updated if the string changes, and even then, only if we're causing problems for the translators.

The point of the screenshots for translators is to provide context for where the string is used. As long as we're providing this context, translators can do their job, and we don't need to expend additional time.

An effective translation workflow means translators do not leave CrowdIn, as long as we enable this, there's no concern that a screenshot may be out of date (with respect to the UI).

----

> Plus, code being read far more often that written

* I don't think this applies to layouts. It's XML (declarative, with a mostly standardised and fixed schema)
* Our UI/UX is not good; we want as little barrier to modification of this as possible. We want to incentivise changes here, and adding (unnecessary) roadblocks is going against this goal

----

> Unless there is some reason to believe that the complexity of creating PR has actually impeded or development, which I have no reason to believe up to know, given that the time taken for review has often be the blocking part.

* The issue template means that less people post issues.
* The PR template means that less people post PRs. 
* Our review process means that less people post PRs.

Adding additional screenshots when necessary to a PR is a good thing, our contributors do this, and I trust their judgment.

Enforcing this on every PR is a hassle for what I see to be no benefit.

----

> I prefer to have a self-contained git repo, with most useful information. But since we already trust github, we could also just add screenshots in the PR (which we often do) and add a link to the image's URL on github. This way, no extra download for the developers, and still a screenshot accessible

This seems like the worst of both worlds. I still don't understand why we're not using the IDE preview for the layout.

**Comment by david-allison** [comment]
Let's go for a sample workflow.

`deck_picker_dialog_list_item `

I find an instance of the ID (Ctrl+Shift+F + `deck_picker_dialog_list_item `:

https://github.com/ankidroid/Anki-Android/blob/4c20bb65678a76cdd10efc0724286b588e25dce0/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt#L260-L262

It's used inside `DeckSelection`, which is commented as:

https://github.com/ankidroid/Anki-Android/blob/4c20bb65678a76cdd10efc0724286b588e25dce0/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt#L58

----

Is this workflow too complicated, where could it be improved, and is the cost of improving it (making all changes to all layouts harder) worthwhile?

**Comment by david-allison** [comment]
An alternate proposal

Our XML layout previews haven't been well maintained. We should get them working again. I've pinged @BrayanDSO to see if this is a quick fix (it feels theme related)

In addition, we can fix most of our layouts to show a 'good' preview, which should fix this.

An example of a preview:

![Screenshot 2022-07-17 at 16 18 49](https://user-images.githubusercontent.com/62114487/179404991-27d95f29-c71d-495b-bfac-29e0c6b1d787.png)

**Comment by BrayanDSO** [comment]
> it feels theme related

Change the preview theme to one of AnkiDroid's

![image](https://user-images.githubusercontent.com/69634269/179416211-6732cbbc-5a2e-4959-a9f1-752e1aa69d84.png)

To have it by default on the previews, add it on the manifest `<application>` tag (https://stackoverflow.com/questions/50923968/android-studio-layout-preview-default-theme)

I suggest having `Theme_Light` as the default.

---
On some layouts I still expect manual changes, e.g. the posted one `deck_picker_dialog_list_item` as it is a part of another layout

**Comment by david-allison** [comment]
One useful step in this would be to star: https://issuetracker.google.com/issues/151244078

We're unable to add previews for `TabLayout`, which has usages

**Comment by mikehardy** [comment]
Feels like busywork to me adding a barrier also. I also just grep for the key and dereference the layout. I also just use the layout editor sometimes. I starred the issue on googles tracker. I don't want to add process or repo inertia here

**Comment by david-allison** [comment]
@Arthur-Milchior now https://github.com/ankidroid/Anki-Android/pull/11879 has gone in, are there any additional layouts to flag as needing work?
