### ISSUE TITLE
[Bug] Edge pro shortcut gestures don't work anymore with last alpha version

### ISSUE THREAD

**Issue by Yoannjap** [ankidroid/Anki-Android#11887]
Hey,

Using last alpha version of Ankidroid, I figured out that [Xposed Edge Pro](https://play.google.com/store/apps/details?id=com.jozein.xedgepro)  gesture shortcuts with it I made to edit text (select all / cut / copy / paste) work on any app but not with Ankidroid anymore when I edit a card...

Debug information:

With Anki 2.15.X until Anki 2.16alpha53, Xposed Edge Pro clipboard edit gestures work with card editions.

With Anki 2.16alpha73, I tested that those shortcuts don't work anymore.

**Comment by david-allison** [comment]
Hi @Yoannjap, could you post the debug information (as listed in the bug template)?

It would also be useful if you could bisect to find the version which broke the Xposed plugin. 

Due to the dependency on Xposed, it's very likely we'll need some investigative work to get this resolved. I personally don't use it.

**Comment by pavreh** [comment]
Select all / cut / copy etc. in the card editor is broken in the latest alpha (#11865). @Yoannjap, can you please test 2.16alpha53? Xposed Edge Pro could work there.

**Comment by Yoannjap** [comment]
@pavreh 
Thanks for your reply.
Indeed, I downloaded the 2.16alpha53, and Xposed Edge Pro clipboard edit gestures work with this version!

**Comment by david-allison** [comment]
I'd like to close this as a duplicate of https://github.com/ankidroid/Anki-Android/issues/11865.

Good news is that this is much easier to fix.

@Yoannjap Would this work for you? (following the linked issue for updates)
