### ISSUE TITLE
[Bug] Api Unit test do not compile

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#11917]
The main problem is that API's unit test seems not to be tested by our CI. 
No idea how to fix that. But it probably should have been detected sooner.

The more local problem is that the test `splitFieldsShouldReturnNullWhenStringIsNull` was broken in 9024e6629b3f3a02e33c94c95c2f0e9e7d819322 . It's not clear how to repair it. The function `splitFields` do not accept null anymore. The question is whether the good correction is:
* we should accept null again
* we should remove the test

I don't understand why we actually tested that. 
By any luck, @rodrigobressan, you would not recall why you added it in [e2d4f48cae6dd6aa8898d771d7d2e0e94737d865](https://github.com/ankidroid/Anki-Android/commit/e2d4f48cae6dd6aa8898d771d7d2e0e94737d865#diff-ce3b16e3604d300428b5879f2a3ada0a6fc7eaa7f436fbd31a494766929ce765R98-R103) , five years ago? (By the way, nice to meet you, I don't think we ever interacted. )
Was it just for the sake of completeness because you did not used `@NonNull` annotation at the time, or was there a reason to really expect a null input?

Personally, I'm not confident enough with API to know whether we can expect some null values from cursor. I believe that this can't occur because fields are never passed as argument from the API call, but always as result. But I may be wrong here.
I believe that anyway, we should not accept "null" fields as input, but I even less want to break our APIs without good reason

I also ping @n1snt because this is blocking your PR #11416, and also because the nullability issue should have been noted when merging your commit 9024e6629b3f3a02e33c94c95c2f0e9e7d819322, so I assume you want to be involved.
(And for the sake of clarity, this is absolutely not to blame you in any way whatshowever. This passed CI test and code review, so even if this commit broke some build, I consider it to be a good as all the other conversion commit)

**Comment by n1snt** [comment]
I had a look at this and I think this is caused due to the [kotlin migration of Utils](https://github.com/ankidroid/Anki-Android/pull/11372).
The kotlin migration changed the Utils `class` to an `internal object` which makes it not accessible outside the package.
If I change it from `internal object` to `object` it is compiling tests.

**Comment by Arthur-Milchior** [comment]
Can you please add more details? Where does it appear? In a specific class? how did you get them?
Because I just tried to run the 8 API tests (clearly not enough admittedly) and they compiled and run succesfully

**Comment by n1snt** [comment]
The tests seem to be running fine for me too but the IDE is showing them as errors:
![image](https://user-images.githubusercontent.com/46300244/185807464-e98a8faf-4a11-4f33-a100-f3c01ebde426.png)

**Comment by n1snt** [comment]
It is due to the Utils object being internal.
It would be more appropriate to change Utils object to private.
_Source: https://kotlinlang.org/docs/visibility-modifiers.html#modules_

**Comment by Arthur-Milchior** [comment]
I believe this issue should have been closed. My bad, I didn't note my PR fixes it. 
Would you accept to put it in a separate issue? You're issue is relevant but it will be ignored if it remains here.

I don't think it should be private. If it were, nobody would be able to use it I think. Instead we need to figure out what to do here. I don't even understand why those Utils methods are in the API subfolder, it seems redundant with the methods of `com.ichi2.libanki`. So I suspect what would makes more sense is to delete the Utils file and replace any of their use with the standard method we have there

**Comment by n1snt** [comment]
Yeah right removing Utils & replacing any of their use makes sense.
Would create a different issue for this 👍.
