### ISSUE TITLE
Keep the settings when downgrading (= when uninstalling the app)

### ISSUE THREAD

**Issue by WiliTest** [ankidroid/Anki-Android#11939]
**Is your feature request related to a problem? Please describe.**
Trying a new beta version is always costly because, when we encounter a bug, and have to downgrade to come back to the previous version that worked fine, we have to uninstall the app, we lose all our settings (like gestures, themes) 

**Describe the solution you'd like**
saving settings into the DB would solve this issue

**Additional context**
Another user told me that sometimes, between some versions the settings are preserved after downgrading. I did not had this chance, I lost them every time I downgraded (my last try was to go from beta69 to 75 then 76 (*) then back to 69)

 (The cut/copy past was not working when editing a card: it worked fines few time, but then not anymore after few minutes: clicking the button "cut" did not do anything. It still works in other apps).

**Comment by BrayanDSO** [comment]
Overall I agree. This is related to #9762, as it proposes saving the settings on the collection too.

As I'm already refactoring the settings code on my GSoC project, and this is actually part of the project "If I have time" section, I may do it on the end of August, or soon after GSoC, depending on my availability and the PR reviews pace.

**Comment by escape0707** [comment]
Try `adb install -r -d /path/to/the-version-you-want-to-install.apk`. If it doesn't work, maybe add `-t`, too.
See https://developer.android.com/studio/command-line/adb#-t-option

**Comment by WiliTest** [comment]
still searching for solutions
