### ISSUE TITLE
[Bug] The play audio button is still not the same as the Anki Desktop play audio button

### ISSUE THREAD

**Issue by bernardosulzbach** [ankidroid/Anki-Android#11940]
###### Reproduction Steps
1. Use AnkiDroid with a [sound:...] tag whose output you tried to modify by using CSS targetting `replay-button`.

###### Expected Result
A similar (ideally identical) element to the one I get on Anki Desktop.

###### Actual Result
![image](https://user-images.githubusercontent.com/8271090/181919337-3d9570cb-8e70-4ba5-97e2-0dcbe0ab7ad4.png)

###### More info
See [Audio Replay Buttons](https://docs.ankiweb.net/templates/styling.html#audio-replay-buttons) and #10350 (for #10343), which I think should have fixed this.

###### Debug info
```
AnkiDroid Version = 2.15.6
Android Version = 9
Manufacturer = samsung
Model = SM-J730G
Hardware = samsungexynos7870
Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-J730G Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36
ACRA UUID = 5e28aaed-23ce-46e0-9a3e-08deb500f948
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true
```

###### Research
- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pavreh** [comment]
#10350 was merged 6 months ago but AnkiDroid 2.15.6 is one year old. Please try the latest alpha. 
[https://github.com/ankidroid/Anki-Android/releases](https://github.com/ankidroid/Anki-Android/releases)

**Comment by bernardosulzbach** [comment]
Ah, that's the issue. I read 2.15.6 as being released July 14 but didn't see it was... last year.

Do you know why there has been no public release of AnkiDroid since then?

**Comment by mikehardy** [comment]
@bernardosulzbach we are very carefully working through the required changes for "scoped storage" which requires us to move the database of all the installed users to a new location on their phone - #5304 - and in the meantime we're doing other large-scale projects like Google Summer of Code (2021 and 2022), migrating from Java to Kotlin and a few other things so it is all just taking time. We'll get there though - we still have a fast release cadence and a great change velocity, we just can't publish them publicly on Google Play until #5304 is done
