### ISSUE TITLE
Use a project-wide license instead of adding a license to every file

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#11969]
Never understood the point of the copyright statement when you have many people who edit the same file. Doesn't everyone get a copyright? If so, then this statement is wrong for the vast majority of files, since not many people update it. Besides, don't I get the copyright regardless of the statement?

Also, what's the point of having a license header in every file? Having a project-wide license should cover every file that doesn't have a different explicit license and is not in the NOTES(?) file. (There are some files without the license header. What's up with that?)

_Originally posted by @oakkitten in https://github.com/ankidroid/Anki-Android/pull/11836#discussion_r922688469_

---

Particularly, I don't know if legal-wise it's imperative to have a copyright header on every file or not, but I like the idea of not having the burden of adding a copyright header to every file + would avoid issues with new contributors forgetting to add it + would close #8659.

If it's imperative to have a copyright header on every file, maybe adding "AnkiDroid Open Source Team/Organization/Project/Whatever" as author + a contributors file somewhere would help

**Comment by BrayanDSO** [comment]
> Could you peel this via context menu action to a new issue 🙏? I'm leaning your way these days on copyright. I'd rat have a license bot set up for PRs to sign a contributor license agreement (like invertase org, used in react-native-firebase), remove per file license lint check, and have a project wide license, with only the couple exceptions as needed. But it's a real, separate change assuming others agree, so needs debate / separate PR

Commented by @mikehardy [on the same discussion](https://github.com/ankidroid/Anki-Android/pull/11836#discussion_r922887142)

**Comment by david-allison** [comment]
For reference

> ### Why should I put a license notice in each source file?
> You should put a notice at the start of each source file, stating what license it carries, in order to avoid risk of the code's getting disconnected from its license. If your repository's README says that source file is under the GNU GPL, what happens if someone copies that file to another program? That other context may not show what the file's license is. It may appear to have some other license, or [no license at all](https://www.gnu.org/licenses/license-list.html#NoLicense) (which would make the code nonfree).
> 
> Adding a copyright notice and a license notice at the start of each source file is easy and makes such confusion unlikely.
> 
> This has nothing to do with the specifics of the GNU GPL. It is true for any free license.

https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile

**Comment by dae** [comment]
The approach the desktop uses is to include a license statement in every file, but to use a generic copyright line. Even a one-line patch holds its own copyright, but it's not practical to update the copyright statement every time, and users who contribute larger patches may feel aggrieved if they're not listed with other contributors. IMHO it's better to use a generic copyright line, and let the git blame reflect the actual contributions.
