### ISSUE TITLE
[Bug] Field in my card goes blank if I edit it

### ISSUE THREAD

**Issue by inexplicabro** [ankidroid/Anki-Android#11966]
If I tap on the edit button (even without making any changes) on any one of my cards, one of my fields (which is a field which contains a graph) turns into an invisible square when I preview the card. If I then tap on the edit button again to see what happened to that field, it seems that the code hasn't changed a bit, it still has the same code that it had before I tapped on the edit button, and if I then preview that card on my PC, it still looks fine and normal. It seems this only applies to Ankidroid.

###### Reproduction Steps

1. Import my Anki deck into Ankidroid (I have filtered it so there's only a couple of cards in the deck for brevity's sake)
2. Go to the browser and view any card under the "Mining" note type (for example, the card 停める) 
3. Tap on the edit button (you might need to make a change to the card, so just edit a letter in the Glossary field)
4. Tap save and preview the card
5. There should be a transparent rectangle that takes up a lot of space where there used to be a small graph

###### Expected Result
The graph should not be replaced with a big blank rectangle.

###### Debug info
```
AnkiDroid Version = 2.15.6

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 8

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 8 Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36

ACRA UUID = 56a74bc4-f4a6-421d-ae95-d04d8ce884a1

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Expected Result
![expected-result](https://user-images.githubusercontent.com/42508471/182325980-fdd04ecc-eabf-4343-b288-8e22a6213be1.png)

###### Actual Result
https://user-images.githubusercontent.com/42508471/182326006-093a00d5-d611-495e-8772-652d065d2a60.mp4

###### Exported Deck
[Test.zip](https://github.com/ankidroid/Anki-Android/files/9240302/Test.zip)

**Comment by mikehardy** [comment]
Hey there! Sorry this is happening - I think this is an area of code that has changed a lot though, since 2.15.6 - can you try a test / .A release of the 2.16alpha series and see if it works for you? https://github.com/ankidroid/Anki-Android/releases

**Comment by inexplicabro** [comment]
It still seems to happen on the latest 2.16alpha76 :(

**Comment by inexplicabro** [comment]
Update: Now it affects my PC cards as well.

https://user-images.githubusercontent.com/42508471/183271430-601021f3-1bf5-4d5c-9bd3-e18bd6f53809.mp4
