### ISSUE TITLE
Version mismatch not checked in loading the backend library.

### ISSUE THREAD

**Issue by divyanshdxn** [ankidroid/Anki-Android#11963]
###### Reproduction Steps
1. Set ANKIDROID_BACKEND_VERSION=0.1.1`5`-anki2.1.54
2. Download the dylib file for 0.1.1`4`-anki2.1.54
3. Set the env var for path
4. Run unit tests 

###### Expected Result
Tests should fail to load producing a version mismatch error

###### Actual Result
Tests get instantiated and run.

https://user-images.githubusercontent.com/69595691/182091154-a1ecbfa9-ad1d-489a-bdea-7b5e2f69ded9.mp4

**Comment by mikehardy** [comment]
Thanks for filing this! Other maintainers this was filed on request. It may end belonging in Anki-Android-Backend, it may not be worth fixing even, I'm not sure but I wanted to track it in case it was easy at least

**Comment by divyansh-dxn** [comment]
keep open

**Comment by dae** [comment]
Should be obsoleted by https://github.com/ankidroid/Anki-Android/pull/12897
