### ISSUE TITLE
Do not silently commit hunks that weren't staged

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#11973]
In git, you can commit parts of changes, or hunks, instead of entire files. AnkiDroid's git commit hooks somehow undo the partial selection, committing the whole file instead. This is something that you may not notice, as you often commit partial changes only to put the rest of the changes into another commit.

**Describe the solution you'd like**
Do not silently commit hunks that weren't staged, only commit what's been staged.

**Describe alternatives you've considered**
One alternative would be to simply abort the commit, since the result is never what the committer wants.

**Additional context**
I would also love to be asked to review any changes that the linter may introduce before committing. Silent changes are just not cool.

**Comment by BrayanDSO** [comment]
Probably the same as #9390.

+1 for the issue. It's annoying to have to workaround it and definitely not a good experience for new contributors

**Comment by oakkitten** [comment]
I swear I searched for the word "hunk"! Oh well. Closing as duplicate

**Comment by mikehardy** [comment]
agreed  on all counts, regardless - I'm just processing notifications mobile so don't have time to click through but silent changes are evil and I frequently do hunk-wise commits
