### ISSUE TITLE
Enlarge buttons on bottom of review mode

### ISSUE THREAD

**Issue by avisgut** [ankidroid/Anki-Android#11989]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I accidentally hit one of the navigation tabs on my old tablet which are right next to the answer buttons. 

**Describe the solution you'd like**
I would like bigger buttons to give me some distance from the navigation buttons. 

**Describe alternatives you've considered**
Using a bluetooth keyboard works great on a table, but no so much an easy chair. 

**Additional context**
The tablet has a ridiculous amount of real estate.

**Comment by BrayanDSO** [comment]
If you are on 2.15.6, go to `Settings > Reviewing > Answer button size` and set to the size you want

If you are on one of the latest alphas, you can find it on  `Settings > Accessibility > Answer button size`
