### ISSUE TITLE
[Bug] Follow system dark mode may not update the theme if the AnkiDroid widget is being used

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#11982]
###### Reproduction Steps

Quite specific to get it
1. Have "Follow system" as theme
2. Have AnkiDroid widget on your home screen (bug only happens with it)
3. Enable "Change automatically based on time" on the system's dark mode
4. Have AnkiDroid closed
5. Wait until system automatically changes the dark mode

###### Expected Result

App uses the new dark mode status (either light or dark)

###### Actual Result

App uses the old dark mode status

###### Debug info
On latest main

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

---

I didn't expect the widget to interfere with this. I know how to fix it, so I should push it soon

**Comment by pavreh** [comment]
The bug is caused not only by the widget but by the back button too. Please try these steps without the widget.

1 have day mode in the mobile
2 in Ankidroid, settings - appearance - theme - follow system 
3 tap back to close Ankidroid
4 switch night mode on in the mobile
5 open Ankidroid

Night mode is not switched. When I use the home button instead of the back button, night mode works.

AnkiDroid Version = 2.16alpha80
Scheduler = std3

**Comment by pavreh** [comment]
Night mode do not work at all in AnkiDroid 2.16alpha84.

**Comment by marcodallagatta** [comment]
I was going to open a request to implement a "follow system" setting but it appears I'm the only one not having it... All I see in appearance regarding the theme are "Day Theme" and "Night Theme", but the only place where I can switch between themes is in the pullable hamburger menu, where there's a night mode toggle.

**Comment by BrayanDSO** [comment]
@marcodallagatta Try using one of the latest alpha versions https://github.com/ankidroid/Anki-Android/releases

**Comment by marcodallagatta** [comment]
> @marcodallagatta Try using one of the latest alpha versions https://github.com/ankidroid/Anki-Android/releases

Thank you, works with this alpha! Although I can attest the bug reported in this issue is happening on my device, too.

**Comment by mikehardy** [comment]
...and of course you still need the widget to get notifications, so a bit of a conundrum on that one. I swear we'll have great notifications at some point in the future...
