### ISSUE TITLE
[Bug] Subdecks are not collapsed after tapping the arrow with V16 schema

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#11999]
###### Reproduction Steps

1. use V16 backend
2. have a parental deck and two subdecks
3. tap the arrow next to the parental deck.
![Screenshot_20220809-035755_AnkiDroidA](https://user-images.githubusercontent.com/10192661/183961059-b8fe8903-7424-417f-bfd2-360aa9277f7c.png)

###### Expected Result

Subdecks are collapsed

###### Actual Result

Subdecks are not collapsed. Open a deck and tap back then subdecks are collapsed.

###### Debug info
AnkiDroid Version = 2.16alpha76

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36

ACRA UUID = 8811dfdf-46ff-4a51-bbea-195fe8c86a5f

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Thanks you very much for all the testing with the new backend. Out of curiosity, have you enabled it by unlocking developer options by using the "About" screen secret?

**Comment by dae** [comment]
Agreed, the testing is much appreciated :-)

**Comment by pavreh** [comment]
@BrayanDSO yes, I read a comment recently where you uncovered the about screen secret :)

**Comment by BrayanDSO** [comment]
FYI, a new alpha was just launched with an option to enable it persistently. You can find it on the "Advanced" settings. Thanks again for all the jobing testing it, really appreciated.

**Comment by mikehardy** [comment]
@pavreh just a note that 2.16alpha78 is building now and should be available soon (30 minutes or so?) if you'd like to re-check all the things you noticed with the new schema over the last couple weeks. Hopefully they are all actually fixed and no new crashes are noticed, but you never know and the testing is really appreciated. Thanks!
