### ISSUE TITLE
[Bug] App bar flickers after opening the navigation drawer

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#11993]
###### Reproduction Steps

1. Open the navigation drawer
2. See the flickering
(tapping an option inside the navigation drawer do the same thing)

###### Expected Result

Icons are pretty and healthy

###### Actual Result

Icons flicker like a ghost

###### Debug info

```
AnkiDroid Version = 2.16alpha76

Android Version = 7.1.1

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 7.1.1; Android SDK built for x86 Build/NYC; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36

ACRA UUID = 8d08c311-c5ba-4cd3-aca6-9ba229e5345a

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```
Same happens on my phone

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
https://user-images.githubusercontent.com/69634269/183650318-fd8600de-ddd6-47f6-a4d3-388394df6dd7.mp4

**Comment by BrayanDSO** [comment]
Based on my local branches, it's something after afbbfd23574abdd3d3d5d4089b3c5f74fbe66d6d. 

My shot is that the first bad commit is 1fa8cde1087b6f42b1f08ba68646267d1ff4cb5d

**Comment by lukstbit** [comment]
I didn't manage to replicate the flickering while using API 21 and 31 emulators. 
Are you using the latest code or just the latest release? 

I'm asking this because two days ago I merged https://github.com/ankidroid/Anki-Android/commit/dde749b70c84a4eba066faf627a8fd86c84217f4 while the _2.16alpha76_  version it's like from 13 days ago.

Also the code in that linked commit is not responsible because it's not used at all and should have been deleted instead of being refactored :laughing:

**Comment by BrayanDSO** [comment]
Latest code

**Comment by lukstbit** [comment]
> About https://github.com/ankidroid/Anki-Android/commit/dde749b70c84a4eba066faf627a8fd86c84217f4, I've cherry-picked to my personal build for ~3 weeks and haven't found a problem with it. Unless it got a side efect of one of the latest changes

I wasn't saying it had problems I was hoping it would solve the issue.
I tested this on a Nougat emulator and I didn't saw the flickering. It would be helpful if others check this out and confirm it happening.

**Comment by BrayanDSO** [comment]
Odd. I'm not seeing the flicker anymore. Closing this.
