### ISSUE TITLE
"Check pronunciation" feature: Audio recorded so small, how can i volume up this?

### ISSUE THREAD

**Issue by pqnhan** [ankidroid/Anki-Android#12029]
My audio recorded file so smaller than sound file of cards.
I can't listen my voice clearly even turn max volume in my phone or using  earphone.

Is there any way (or option) that allows to triple or quadruple the play volume of an recorded file?

**Comment by sparkyniner** [comment]
Can I add a feature that boosts volume @david-allison ?

**Comment by mikehardy** [comment]
I am just now seeing this - I have to admit I do not want to add this feature. We need to be careful not to become a full-fledged audio player app (in the same way we are not a full-fledged image editor, though we do allow crop that's it, and it's from an underlying library)

In this case if the source audio has volume that's too low, that indicates the sound recording setup is not adequate and the mic wasn't getting signal. Amplifying the sound is the wrong fix, fixing the mic and the audio is the fix.

So this would not be a merge-able feature
