### ISSUE TITLE
Adding Fuzz Factor to Ankidroid

### ISSUE THREAD

**Issue by louwheesy** [ankidroid/Anki-Android#12023]
**Is your feature request related to a problem? Please describe.**
Cards learned on the same day that you constantly tap "good" on will have the same intervals and due dates. This can lead to an association between the cards, which can be problematic.

**Describe the solution you'd like**
Anki has a feature called a Fuzz Factor that adds a bit of noise to the following review times. It does not affect the ease, so it won't create cards with relatively large or small intervals. 

**Additional context**
Description of the feature from the Anki manual:
[Fuzz Factor](https://docs.ankiweb.net/studying.html#fuzz-factor)
When you select an ease button on a review card, Anki also applies a small amount of random “fuzz” to prevent cards that were introduced at the same time and given the same ratings from sticking together and always coming up for review on the same day. This fuzz will appear on the answer buttons when the [v3 scheduler](https://faqs.ankiweb.net/the-2021-scheduler.html) is enabled, so if you are using a previous version and you’re noticing a slight discrepancy between what you select and the intervals your cards actually get, this is probably the cause.

Learning cards are also given up to 5 minutes of extra delay so that they don’t always appear in the same order, but answer buttons won't reflect that. It is not possible to turn this feature off.

**Comment by david-allison** [comment]
This is already implemented.

Ctrl+F for fuzz: https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java

**Comment by louwheesy** [comment]
I'm not sure that it's a functional feature. I've added 5 test cards to a deck and marked each one as "good" each time to see what would happen. They each have 1 week intervals at this point and still all show up together.

**Comment by humhue** [comment]
Thanks for the swift reply, I can confirm that this works as intended. Anki desktop shows the new interval (default + fuzz) on top of the buttons while Ankidroid doesn't seem to and I think that was the source of my confusion. Maybe this could be changed? Is there a particular reason not to show the real interval?
