### ISSUE TITLE
Using the new backend add `.0` to some numbers of deck options

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12039]
I've noticed that after using the new backend, a `.0` on the numbers of some options of Deck options (e.g. Steps), which may be odd

![Screenshot_20220816-133002_AnkiDroid](https://user-images.githubusercontent.com/69634269/184934072-2fa2e714-efa9-4d02-82e8-3cce239f2018.png)

Not a big problem, but is something to note.

**Comment by BrayanDSO** [comment]
Probably it would be best to migrate these preferences to the new Anki Desktop notation, e.g. 2d = 2 days (2880 minutes)

**Comment by mikehardy** [comment]
This may be a good time to test using the backend's 'TR' method and use the backend translations

**Comment by dae** [comment]
The deck options screen is a HTML/TS page that can be included verbatim in AnkiDroid like the CSV importer. The current AnkiDroid deck options have some AnkiDroid-specific options in them however (automatic display answer, notifications). These could either be moved to a different screen, or AnkiDroid could inject extra settings into the page in the same way desktop add-ons do, though it may take some work and would ideally require a node toolchain for building/testing. AnkiMobile avoids having to do this by having automatic answering and notifications as collection-level properties in the preferences screen instead of binding them to each deck.

The deck description is also not shown on that page; the desktop uses a different screen to edit it now.

**Comment by BrayanDSO** [comment]
I guess I'll test it just for fun on my CSV importer local build after I get some time to discover what javascript methods this screen needs to evaluate

**Comment by mikehardy** [comment]
I would try to use upstream HTML/TS verbatim instead of fooling with it, and have separate screen(s) for non-Anki-generic stuff, for what it's worth. Injection/modification seems like a fragile thing just waiting to break

**Comment by dae** [comment]
@BrayanDSO the relevant line in the desktop code is

```
        self.web.eval(
            f"""const $deckOptions = anki.setupDeckOptions({self._deck["id"]});"""
        )
```

And I think there are two endpoints: getDeckConfigsForUpdate, and updateDeckConfigs

**Comment by BrayanDSO** [comment]
Oh boy, I love getting things from free. My head hurts every time I have to open `DeckOptions.kt`, so getting this no-charge will have an extra flavor. If/when filtered deck options gets a HTML screen too, the world will become a more beautiful place.

https://user-images.githubusercontent.com/69634269/184986361-bc4c8dae-1352-448b-85e3-edc4215115ec.mp4

It doesn't seem very optimized for mobile though (my phone's webView is updated, so that's not it). Maybe I messed up something? Or it may be a WIP? Since the screen is new and I don't know if AnkiMobile has got it already

**Comment by dae** [comment]
> It doesn't seem very optimized for mobile though

What specifically are you referring to? The thing in the far right of the center of the screen looks odd and doesn't appear on other platforms, and the dropdown boxes are showing up with very large text on Android. The screen also usually has a grey background, but I guess you've overriden the styling?

**Comment by BrayanDSO** [comment]
> What specifically are you referring to? The thing in the far right of the center of the screen looks odd and doesn't appear on other platform

exactly this. Good to know that it's a Android/my implementation issue

> I guess you've overriden the styling?

yes, but just colors

---

The odd right margin apparently is because of the undo icon which I haven't seen before 

![image](https://user-images.githubusercontent.com/69634269/184992559-098b1ebd-982d-4056-8ae6-b393e78fe6e7.png)

I can tell that the big text on the dropdowns are an Android thing because it follows the theme colors even without injecting any CSS

![image](https://user-images.githubusercontent.com/69634269/184992769-47706c78-f0fc-4b53-bc86-9211685f00b6.png)

And I probably should add some margins to this screen
