### ISSUE TITLE
[Bug] Change note type crash with v16 schema

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12049]
###### Reproduction Steps
1. Use v16 backend, v3 scheduler
2. Add a note (e.g. basic type)
3. Card browser
4. Edit the note 
5. Change the note type, e.g. Basic and reversed card

###### Expected Result
The note type is changed

###### Actual Result
Crash. A crash report sent

###### Debug info
AnkiDroid Version = 2.16alpha78

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36

ACRA UUID = 5166056d-62ff-4898-beed-7183997fc68e

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
Just pushed a fix for this :-)
