### ISSUE TITLE
[Bug] Wrong review count for decks with subdecks queried through API

### ISSUE THREAD

**Issue by wlky** [ankidroid/Anki-Android#12052]
###### Reproduction Steps

1. Have decks with subdecks in AnkiDroid (subdecks must have cards to be reviewed, green numbers)
2. Query decks through API from another app
3. Output deck counts

###### Expected Result

Decks should show only their own card numbers and not include subdeck card numbers for all counts. So when querying the expected result would be:
```
deck counts of the Deck. [learn, review, new]
deckName = Math
deckCounts = [0,0,0]
deckName = Math::Integration
deckCounts = [0,0,0]
deckName = Math::Integration::StandartIntegration
deckCounts = [6,6,2]
deckName = Math::Integration::Trig-1
deckCounts = [2,4,3]
deckName = Math::Integration::Trig-2
deckCounts = [0,0,10]
```

###### Actual Result

The deck review counts include subdeck **review** counts (but not new and learn counts). I'm using https://ankiweb.net/shared/info/1874527669 for testing. When I query it this is the result:
```
deck counts of the Deck. [learn, review, new]
deckName = Math
deckCounts = [0,10,0]
deckName = Math::Integration
deckCounts = [0,10,0]
deckName = Math::Integration::StandartIntegration
deckCounts = [6,6,2]
deckName = Math::Integration::Trig-1
deckCounts = [2,4,3]
deckName = Math::Integration::Trig-2
deckCounts = [0,0,10]
```
AnkiDroid at the same time shows this:
![SmartSelect_20220817-091524_AnkiDroid](https://user-images.githubusercontent.com/10642029/185057840-3cf26730-16ee-475f-8a4d-51710e65104e.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
What version are you testing with? If this only started on recent alphas, I suspect I caused this. The backend code no longer provides a routine to get the counts for individual decks, so the old approach will not work for users who switch to the v3 scheduler. What's your use case? Are you tallying the counts yourself?

**Comment by dae** [comment]
Ok, pretty sure this behavior changed before I touched the code :-) If you want a total count, you should be able to just tally the top-level decks instead.

**Comment by wlky** [comment]
Maybe it has always been this way, I don't think I've tested it with subdecks when I first programmed it in 2017.
Right now I'm tallying the deck and all of its subdecks to get the top-level deck stats. That works fine for learn and new card counts, but as you can see the review card counts are duplicated because the parent deck also reports the sum of the child decks as its own review card count.
It would also be fine with me if that would be normal behavior for new and learn cards, but right now, as you can see those are 0 in the parent decks.

**Comment by dae** [comment]
Pretty sure things are consistent in https://faqs.ankiweb.net/the-2021-scheduler.html, which AnkiDroid currently only supports behind a feature flag.
