### ISSUE TITLE
[Bug] Save search crash

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12057]
###### Reproduction Steps
1. Open Card browser
2. Search something
3. Tap the three dots - tap Save search

###### Expected Result
The search can be saved

###### Actual Result
Crash

###### Debug info
AnkiDroid Version = 2.16alpha78

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36

ACRA UUID = b0d00727-21ff-4c1f-a51b-97a0cbf9e738

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
Thank you for all the reported bugs!
