### ISSUE TITLE
[Bug] Undo Delete crash with v16 schema

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12054]
###### Reproduction Steps
1. Use v3 scheduler
2. Bury a note
3. Delete a note
4. Back to Deck picker
5. Tap the three dots menu - Undo Delete note
![Screenshot_20220819-140341_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/185614740-983e94e7-1138-4c9d-a19c-a775964c2a06.png)
###### Expected Result
1. The note deletion is undone and a toast/snackbar appears.
2. Undo Bury is possible.

###### Actual Result
1. The note deletion is undone but no feedback.
2. Undo Delete note is offered again. The app crashes If Undo Delete note is used for the second time.

###### Debug info
AnkiDroid Version = 2.16alpha78

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36

ACRA UUID = 5166056d-62ff-4898-beed-7183997fc68e

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by escape0707** [comment]
I'm having a similar crashing bug on 2.16a9.

When reviewing, I sometimes want to edit a note. After editing, when I choose to answer "good" for this card, it sometimes crashes. I don't know if it crashes only on the second time seeing this card, tho.

**Comment by pavreh** [comment]
@escape0707 I can confirm your crash and I sent a crash report too. The app crases when a back field is edited but not every time. Please create a new issue.

**Comment by dae** [comment]
Split into #12155
