### ISSUE TITLE
[Bug] Card modified date with v16 schema

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12051]
###### Reproduction Steps
1. Use v16 backend, v3 scheduler
2. Have a note with basic and reversed cards
3. Review one of the cards

###### Expected Result
Card modified date is updated for the reviewed card only

###### Actual Result
Card modified date is updated for all cards of the note
![Screenshot_20220817-053849_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/185037533-2a2de029-c53e-4c2e-95d4-1ef3bfad4d96.png)

###### Debug info
AnkiDroid Version = 2.16alpha78

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36

ACRA UUID = 5166056d-62ff-4898-beed-7183997fc68e

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
Do you have burying enabled? If the sibling was buried, that will mark it modified.

**Comment by pavreh** [comment]
Oh I see. Yes, I have burying enabled. When I switch burying off reviewed card only is modified. The sibling stay unmodified. I am sorry.

**Comment by dae** [comment]
No problem! Thanks again for all the reports.
