### ISSUE TITLE
Pop-up menu is skipped after clicking back on the confrimation dialog

### ISSUE THREAD

**Issue by PinkRay7** [ankidroid/Anki-Android#12053]
###### Reproduction Steps

1. Click the menu on the home page.
2. Click "Manage note types".
3. Choose one note type.
4. Click "front" and see a menu pops up.
5. Click "Delete field".
6. Go back.

###### Expected Result
After step 5, a confirmation dialog will pop up. After clicking back on the dialog, the app should go back to the menu showed up in step 4.

###### Actual Result
After clicking back on the dialog, the menu in step 4 won't show up. The app will directly go back to the state after step 3.

However, this behaves normally on 2.16alpha65 and earlier versions.

###### Debug info
AnkiDroid Version = 2.16alpha78
Android Version = 8
Model = Google Pixel 2

###### Additional info
Regression bug, the first version with this bug is 2.16alpha66.

Bug on 2.16alpha78

https://user-images.githubusercontent.com/53887881/185071011-39d591c8-e9d4-4b7e-a04b-3d1fd901580c.mp4

Normal behavior on 2.16 alpha65

https://user-images.githubusercontent.com/53887881/185070884-1608cffa-8afe-4820-b4c2-a1bdd56b3e8d.mp4

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by ShridharGoel** [comment]
Seems to be happening due to the changes in #11347.
