### ISSUE TITLE
Remove method name from translatable string

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12080]
Currently, there is a translatable string with a method name on it which should be removed
https://github.com/ankidroid/Anki-Android/blob/8aa45daf163e37b4cd0325a65dcc7cb676e011e1/AnkiDroid/src/main/res/values/02-strings.xml#L170

**Comment by pratyaksh1610** [comment]
@BrayanDSO Please assign this issue to me.
Thanks.
