### ISSUE TITLE
[Bug] play media gesture doesn't work after showing the cards

### ISSUE THREAD

**Issue by aghanki** [ankidroid/Anki-Android#12084]
### Reproduction Steps

1. I add a gesture to use "play media".
2.I go to my decks with media in front of the cards. I use the button for showing the answers.
 3. After showing answers, When I use the gesture to play media , nothing happens. 

 ( The media i am trying to play is on the front of the card when I am on the back of the card)

###### Expected Result

I expect that when I use the defined gesture in back of my card , it play my media (the media is on front of the card ), but nothing happens.

###### Actual Result

Nothing happens when I use the defined gesture after showing the answers.
(The media is on front of the card)

###### Debug info

AnkiDroid Version = 2.15.6

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi Note 8 Pro
] play media gesture doesn't work after 
Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi Note 8 Pro Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36

ACRA UUID = d68cc2a6-b89c-4642-9e83-310426112137

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual]([manual](https://ankidroid.org/docs/manual.html) and the [FAQ]([FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

tps://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi @aghanki :wave: - thanks for logging this, I was the person responding to your review on the Play Store, and I appreciate that you took the time to write this up, also (note for maintainers!) that you took the time to try 2.16alpha78 (I think? could have been 79, regardless, it's current code) so we know this issue still exists

Hopefully we can figure it out, either way, we're tracking it now

**Comment by aghanki** [comment]
Thanks! I have already checked the issue with 2.16alpha79 version . 
Thank you!

**Comment by criticalAY** [comment]
is this issue fixed?
I tried to reproduce the issue but it was working i guess.

**Comment by aghanki** [comment]
The issue is ongoing.
It is reported a few days ago.

**Comment by snowtimeglass** [comment]
Hi @aghanki I have also read your review on Play Store. 

> I downloaded AnkiDroid 2.16alpha79, I add a gesture to play media. It doesn't work again after showing answers. However, it works before showing answers.

I suspect that `Replay audio` feature itself doesn't play media on front of the card after answers are shown on the decks which you are using.

If `Deck options` on the review screen of the card -> `General` -> `Replay question` has been unchecked, `Replay audio` just plays media on back of the cards after answers are shown, and consequently the gesture of `Play media` (there seems to be terminological inconsistency. Its feature is identical with `Replay audio`'s one) doesn't play media on front of the card after answers are shown, as you have been experiencing.

Could you please confirm whether the `Replay question` item has been checked or not?

![image](https://user-images.githubusercontent.com/10436072/186201888-11677ac3-cf9e-4f90-9f73-663e6bb9ead0.png)

**Comment by aghanki** [comment]
Hello! That's great! I confirm that it worked.
Awesome!
I guess it wasn't a bug at all at first.
Thanks!

**Comment by snowtimeglass** [comment]
That's good to hear! My pleasure!

**Comment by mikehardy** [comment]
Great collaboration figuring that out, thanks all!
