### ISSUE TITLE
AnkiActivity.finishActivityWithFade: change transition from UP -> FADE

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#12123]
_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/12115#discussion_r950783644_

**Comment by criticalAY** [comment]
hey, I have committed the transition change from UP to FADE in the AnkiActivity  in  #12129

**Comment by david-allison** [comment]
Fixed by https://github.com/ankidroid/Anki-Android/pull/12129
