### ISSUE TITLE
backendUndoAndShowPopup() snackbar should not show on top of answer buttons

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#12138]
When using new schema, backendUndoAndShowPopup() snackbar needs to be changed so it does not show on top of the answer buttons

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/12093#discussion_r950641591_

**Comment by sparkyniner** [comment]
Hello, can I work on this?

**Comment by mikehardy** [comment]
Sure! This may be a little involved on the setup since you will be on the leading edge of our conversion to the new backend. In order to see it I think you'll have to toggle on the new backend in settings -> advanced then try some undos in the reviewer, and then it should be visible?

**Comment by sparkyniner** [comment]
On it!

**Comment by sparkyniner** [comment]
Which option do I click in Advanced to toggle the new backend and what exactly do you mean by reviewer.

**Comment by mikehardy** [comment]
My comment indicates the setting to toggle ("new backend", in settings -> advanced) and "reviewer" is the name for the Activity where you review cards and test your memory

In Android terms, you may discover these things yourself by looking in the manifest for something that has the same name

https://github.com/ankidroid/Anki-Android/blob/26ae93b87b90b0f9d4bfdf492d8481941de5e329/AnkiDroid/src/main/AndroidManifest.xml#L239-L240

Alternatively, you can just look in the filesystem (on unix, like `find . |grep Reviewer`) and you'll see hits, then you may explore

**Comment by sparkyniner** [comment]
Ahh okk, so as I understand it, the undo and show popup is showing over the answer button and we would like to change the position of the snackbar. So to solve this issue, I need to edit the file Reviewer.kt?

**Comment by sparkyniner** [comment]
And if the popup should not show on top of the answer button, should I make it show somewhere else or remove it completely?

**Comment by BrayanDSO** [comment]
> And if the popup should not show on top of the answer button, should I make it show somewhere else or remove it completely?

Show it above the answer buttons, like showSnackbarAboveAnswerButtons() does (here's a [link](https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L1798) for it)

**Comment by sparkyniner** [comment]
But for me the undone snackbar already shows above the answer button https://imgur.com/a/SN6Iuwj

**Comment by BrayanDSO** [comment]
You have to enable the new backend for this to happen. It's on "Settings > Advanced > Experimental > Use the new backend"

**Comment by sparkyniner** [comment]
I've enabled it, still the same

**Comment by BrayanDSO** [comment]
The new backend message is different, it should show `X undone` instead of `Undone "X"`. Can you confirm which one you get? In some cases, even with the new backend, it relies on the legacy undo

**Comment by sparkyniner** [comment]
I'm getting Undone "X" even with the new backend

**Comment by sparkyniner** [comment]
Also which file do I need to edit to solve this problem?

**Comment by BrayanDSO** [comment]
Try undoing a Bury or Suspend and you will get the message

**Comment by sparkyniner** [comment]
Sorry, what exactly is a bury or a suspend?

**Comment by sparkyniner** [comment]
nvm, got it

**Comment by sparkyniner** [comment]
Yup now it's showing the snackbar right on top of the answer button

**Comment by sparkyniner** [comment]
Which file do I need to edit to solve this?

**Comment by mikehardy** [comment]
>  Which file do I need to edit to solve this?

I think a lot of the point of a first issue is to discover these answers yourself by following the debugging lines that are out in the code, searching the codebase etc. There's no other way to really get familiar with a codebase then to start exploring and learning where things are on your own

**Comment by sparkyniner** [comment]
You're right, I'll explore and figure it out

**Comment by sparkyniner** [comment]
I edited backendUndo.kt and made these modifications:

`suspend fun FragmentActivity.backendUndoAndShowPopup(): Boolean {

    return try {
        val changes = withProgress() {
            undoableOp {
                undoNew()
            }
        }
         fun showSnackbarAboveAnswerButtons(


            duration: Int = Snackbar.LENGTH_LONG,
            snackbarBuilder: SnackbarBuilder? = null
        )
         {
            // BUG: Moving from full screen to non-full screen obscures the buttons
            showSnackbar(TR.undoActionUndone(changes.operation),duration) {
                snackbarBuilder?.let { it() }

                if (mAnswerButtonsPosition == "bottom") {
                    val easeButtons = findViewById<View>(R.id.answer_options_layout)
                    val previewButtons = findViewById<View>(R.id.preview_buttons_layout)
                    anchorView = if (previewButtons.isVisible) previewButtons else easeButtons
                }
            }
        }

` But for some reason, now the undo snackbar for bury and suspend does not show at all

**Comment by sparkyniner** [comment]
Found the file, fixing the issue

**Comment by sparkyniner** [comment]
i've solved the issue and issued a PR, please have a look.
