### ISSUE TITLE
Night mode should follow device's status

### ISSUE THREAD

**Issue by feuGeneA** [ankidroid/Anki-Android#12131]
My Android natively supports night mode via a top-level button, along side wifi, flashlight, location, etc. I've noticed that other apps have an option to "automatically enable/disable night mode according to the device setting". AnkiDroid should do the same.

I'm often enabling it disabling night mode on my device, and then using Anki Droid, and needing to manually enable or disable night mode specifically within the app in order to maintain a consistent experience.

(Thank you for AnkiDroid!i absolutely love it!!)

**Comment by pavreh** [comment]
Hi, AnkiDroid 2.16alpha switches night mode automatically according to the device setting. You can try the latest alpha here [https://github.com/ankidroid/Anki-Android/releases](https://github.com/ankidroid/Anki-Android/releases)

**Comment by mikehardy** [comment]
Yep - we've implemented this, it was a highly requested feature
