### ISSUE TITLE
[Bug] Open Card browser crash

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12143]
###### Reproduction Steps
1. Open Card browser

###### Expected Result
Card browser is opened

###### Actual Result
Crash

###### Debug info
AnkiDroid Version = 2.16alpha80 

Android Version = 12 

Manufacturer = samsung 

Model = SM-A225F 

Hardware = mt6769t 

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36 

ACRA UUID = 06c5c865-3ffa-4b5a-b91e-878fa8709710 

Scheduler = std3 

Crash Reports Enabled = true 

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
New ACRA is problematic to say the least. I can't find the report. Could be one of:

* Edit note when reviewing - https://ankidroid.org/acra/app/1/bug/11499/report/55115210-9e36-431f-9e42-7a9a78b79235
* open deck reviewer - https://ankidroid.org/acra/app/1/bug/11498/report/bcf2b032-708c-4275-ac42-3cd8cd4d414c
* Edit note, answer - https://ankidroid.org/acra/app/1/bug/11496/report/0e027968-32e8-4252-86c5-9ee7770cc559

Is it possible for you to provide your `collection.anki2` file so we can take a look?

If you don't want to share it publicly, could you link it via a 'permission required' google drive link? I could also accept it via email

**Comment by pavreh** [comment]
I sent a new crash report called "Open Card browser crash"

Then I backed up the collection.anki2 file and deleted app data and AnkiDroid folder. 
Now, I am not able to crash the AnkiDroid again even I use the affected collection.anki2 file...

**Comment by dae** [comment]
Report at https://ankidroid.org/acra/app/1/bug/11543/report/6327fbb0-d3aa-4c46-8384-f4739dfdbe1f

```
Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=10
	at com.ichi2.anki.CardBrowser.onCollectionLoaded(CardBrowser.kt:29)
	at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.kt:4)
	at com.ichi2.anki.CardBrowser.onCreate(CardBrowser.kt:13)
```

Could it be connected to https://github.com/ankidroid/Anki-Android/commit/c762f1af254e4f1bea1c207a157d5a24c62170ac?

**Comment by pavreh** [comment]
Somehow connected with upgrade. I upgraded my second instalation AnkiDroid.B and I cannot open the card browser again.

**Comment by mikehardy** [comment]
New acrarium was irritating @david-allison but now is great, after acrarium maintainer graciously implemented my request for a installation UUID filter

1. Open ACRA https://ankidroid.org/acra
2. Login
3. Tap ankidroid to open the app
4. Tap "installations" so you can filter by ACRA UUID
5. Tap filter icon over on right
6. paste in UUID
7. View report

**Comment by mikehardy** [comment]
@Arthur-Milchior this is likely from your PR #11956 ?
I cannot reproduce it though, I just attempted to open current main on an emulator with my normal test collection and it worked

What columns are you displaying in the card browser? I'm using boring Question / Answer 2-column layout. All the other values for the second column seem to work as well.

I think we're going to need a collection that shows the problem

**Comment by pavreh** [comment]
What columns are you displaying... It was the right question. Question/Answer works.  Question/Deck does not work. Switch to Question/Deck, tap back to go to Deck picker, open Card browser = crash. Display order is "By sort field".

These columns does not work:
Question/Deck
Question/Note
Question/Question
Question/Tags
Question/Lapses
Question/Reviews
...
Qustion/Note modified

**Comment by mikehardy** [comment]
Got it! @pavreh --> :trophy: 

 Reproduction:
1- go to card browser
2- change second column to deck (others may do it), it will appear to work
3- go to deck list
4- go back to card browser
:boom: 

```
08-24 13:01:32.470 11989 11989 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.CardBrowser}: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3635)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3792)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2210)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7839)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=2; index=2
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at com.ichi2.anki.CardBrowser.onCollectionLoaded(CardBrowser.kt:616)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at com.ichi2.anki.AnkiActivity.startLoadingCollection(AnkiActivity.kt:373)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at com.ichi2.anki.CardBrowser.onCreate(CardBrowser.kt:495)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8051)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:8031)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3608)
08-24 13:01:32.470 11989 11989 E AndroidRuntime: 	... 12 more

```

I tested a revert of just that commit and it worked, I was no longer able to reproduce

#12162 is the PR for the revert then, and I'll release a new alpha as soon as it passes CI and gets a review
