### ISSUE TITLE
v3 scheduler sometimes crashes after editing

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#12155]
I'm having a similar crashing bug on 2.16a80 with V3 scheduler.

When reviewing, I sometimes want to edit a note. After an edition triggered from reviewing the back card (start editing from the front card doesn't seem to trigger this problem), if I choose to answer "good" for this card, it seems to crashes. I don't know how to extract and review the crash log but they got uploaded.

AnkiDroid Version = 2.16alpha80

Android Version = 13

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6a Build/TP1A.220624.021.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 9c32ddea-ccc7-42cb-9016-62a03202d3d3

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

_Originally posted by @escape0707 in https://github.com/ankidroid/Anki-Android/issues/12054#issuecomment-1225104401_

**Comment by escape0707** [comment]
This seems to be fixed in latest alpha build. But I sometimes still got crashes after flagging / unflagging and answering.

**Comment by mikehardy** [comment]
Hey @escape0707 :wave: - thank you for testing this! If you could open a new issue + make sure you are reporting crashes + and include your ACRA UUID in the debug info (there are some instructions on the new issue template to get it) we can probably dig up the crash stacktrace and analyze what's happening

**Comment by escape0707** [comment]
> Hey @escape0707 :wave: - thank you for testing this! If you could open a new issue + make sure you are reporting crashes + and include your ACRA UUID in the debug info (there are some instructions on the new issue template to get it) we can probably dig up the crash stacktrace and analyze what's happening

Okay, will do that after getting my hands on a PC.
