### ISSUE TITLE
[Bug] Card info - Manual type is not defined

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12167]
###### Reproduction Steps
There are at least four types in Card info. Learn, Review, Filterd and Manual. Manual type is not defined.

###### Expected Result
![Snímek obrazovky 2022-08-25 135259.png](https://user-images.githubusercontent.com/10192661/186658588-c871366f-d887-4064-b41b-9c25615b1c50.png)

###### Actual Result
![Screenshot_20220825-135026_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/186658679-e064d56b-c88f-4175-a364-ef4147181411.png)

###### Debug info
AnkiDroid Version = 2.16alpha80

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 5df52f79-f5cd-436f-8b15-11830f324973

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
I think we will get this one with the new backend's Card info screen. It hasn't been implemented yet though. 

I should push it soon after #12105 is merged, as I've already implemented it locally.

**Comment by mikehardy** [comment]
Agreed - this is a change from v3 scheduler I'm sure, and we could update our code here or just use new backend + get the fancy new backend screen in. Going with "the future" is the right state. @BrayanDSO I'm dying to hit the merge button on that PR, I think it's ready to go, but since it is a huge GSoC one it seems like a person actually doing the mentor work should do it, that's the only hold up I think. Cheers

**Comment by david-allison** [comment]
My intention is for this screen to be removed. We should get it for free with the new backend

**Comment by mikehardy** [comment]
It'll launch in the next alpha :-), glorious
