### ISSUE TITLE
Cannot open Ankidroid

### ISSUE THREAD

**Issue by javiercl2020** [ankidroid/Anki-Android#12182]
Whenever I open it I get this message
![Screenshot_20220825-235204](https://user-images.githubusercontent.com/73913963/186825103-6afc415b-1986-4602-b36f-8d026cb46a95.png)

**Comment by mikehardy** [comment]
Hi there! Really sorry this is happening.
Have you verified that AnkiDroid has storage access permissions (in System preferences list of apps, permissions are of the AnkiDroid app from it's info screen)
How did it go when you tried database check or backup?

**Comment by javiercl2020** [comment]
I solved it already so I deleted my collection and restored it with my ankiweb account
