### ISSUE TITLE
[Bug] Cannot convert `ApiUtilsTest` to Kotlin: There are no configurators available

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#12209]
Likely an upstream bug, posting here for research purposes

* This only fails for the `/test`, not for the `/src` elements in the /api project
* not fixed with `testImplementation "org.jetbrains.kotlin:kotlin-test:$kotlin_version"` 

File: https://github.com/ankidroid/Anki-Android/blob/main/api/src/test/java/com/ichi2/anki/api/ApiUtilsTest.java
Commit: 9797b7b29d281904bcdb4857f134824e6592fcd3

Using the IDE's `Convert Java File to Kotlin File` feature

----

Messages:

```
Kotlin is not configured in the project
You will have to configure Kotlin in project before performing a conversion.

[ No, cancel conversion ]
[ OK, configure Kotlin in the project ]
```

<details>

![Screenshot 2022-08-28 at 10 26 22](https://user-images.githubusercontent.com/62114487/187067229-5b51f6be-00fe-4a1c-91ca-1fdfd33e0afa.png)

</details>

```
Kotlin is not configured in the project
There are no configurators available

[ OK ]
```
<details>

![Screenshot 2022-08-28 at 10 26 35](https://user-images.githubusercontent.com/62114487/187067234-8f31beae-ab20-4833-ab5d-9832f7458807.png)

</details>

**Comment by david-allison** [comment]
Fix:

* Create an unused Kotlin class in the test project `A.kt`
* The conversion now works on `ApiUtilsTest.java`
* Delete `A.kt`

**Comment by david-allison** [comment]
Reopening this. Acceptance criteria or closing: 

- This issue has been posted to the Android Studio bug tracker with the above commit reference so the issue can be reproduced and fixed.
- This issue contains a link to the bug report

**Comment by mikehardy** [comment]
Make sure to try their latest test version first (Dolphin since it's close to release, Electric Eel as a last resort) to see if it's already fixed - https://developer.android.com/studio/preview

**Comment by david-allison** [comment]
Closing as stale - we won't get to this any time soon
