### ISSUE TITLE
Assuming first deck instead of current when adding card from edit card menu

### ISSUE THREAD

**Issue by dansynek** [ankidroid/Anki-Android#12205]
This is only a bug when adding a card from within the edit card menu! It seems to assume the first deck in alphabetic order instead of the current deck to which the card you edit belongs. It's not obvious that this is a bug, perhaps this is behavior that is intended, but I think most people would expect the card to be added to the deck you are using at the moment as the default(it can of course be changed in the menu)

Edit: actually it does add the card to the current deck. It's only the label in the menu that is wrong!

**Comment by david-allison** [comment]
Hi, could you please fill out the provided [issue template](https://raw.githubusercontent.com/ankidroid/Anki-Android/main/.github/ISSUE_TEMPLATE/issue_template.md) when filing a report, paying attention to the `Debug Info` section so we can determine if you're using an old version of AnkiDroid

Thanks!!
