### ISSUE TITLE
Use issue forms for logging issues

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#12214]
**Is your feature request related to a problem? Please describe.**
Use forms when users log issues here. 

**Describe the solution you'd like**
The forms should be integrated into the issues template.

**Describe alternatives you've considered**
Currently issue are logged in markdown.

**Additional context**
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms
https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository

**Comment by omsurase** [comment]
i would like to work on this

**Comment by omsurase** [comment]
could you give me some idea of what all information should be collected in the form?

**Comment by krmanik** [comment]
The forms should be similar to issue template and feature request template.
https://github.com/ankidroid/Anki-Android/blob/main/.github/ISSUE_TEMPLATE/issue_template.md
https://github.com/ankidroid/Anki-Android/blob/main/.github/ISSUE_TEMPLATE/feature_request.md

**Comment by mikehardy** [comment]
Hey @omsurase :wave: - welcome

I think the issue logging is the big one, not so much the feature request

I would start with:

- checkboxes for the things we have as checkboxes
- Debug Info text box, with the instructions on how to get that from the phone as the description
- Short description of the steps to reproduce
- open text entry box to describe any extra information
