### ISSUE TITLE
Make code coverage reporting stable

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#12227]
`codecov` often reports random fluctuations in the coverage. This is likely because tests are nondeterministic, but may be a bug in codecov.

* Determine why this occurs (typically by finding the classes which fluctuate)
  * Maybe this is just due to flaky tests, should we upload codecov reports if there are test failures? 
* Fix this, so we no longer get `codecov`-based CI failures on changes which should be no-ops

Maybe useful: https://docs.codecov.com/docs/unexpected-coverage-changes

**Comment by mikehardy** [comment]
It does seem coverage should not be uploaded if there are failures, in that case it should be a fail on codecov if possible though (to warn us of total codecov breaks at integration level by maintaining that it's a fail if there is no coverage?)

My hypothesis is some test-specific non-determinism, that's the high-probability cause of this in general
