### ISSUE TITLE
There is an error when crop image on the mobile side, it prompts "something went wrong"[Bug]

### ISSUE THREAD

**Issue by ccvbc** [ankidroid/Anki-Android#12230]
###### Reproduction Steps
1. I tried restarting, no effect
2. Version: The latest version of the Google Play Store
3. Error screenshot

![Screenshot_20220829_221014](https://user-images.githubusercontent.com/103726582/187226132-bf5aa86c-c76c-47e4-9068-3cde76a8f2a6.jpg)

###### Expected Result

normal operation

**Comment by david-allison** [comment]
Hi, thanks for the report. Please edit your post to include the [issue template](https://raw.githubusercontent.com/ankidroid/Anki-Android/main/.github/ISSUE_TEMPLATE/issue_template.md)

You may want to try our alphas (listed) to see if this issue is resolved.

Thanks!

**Comment by ccvbc** [comment]
> 你好！ 👋 感谢您记录此问题。 请记住，我们都是这里的志愿者，所以在我们解决这个问题之前可能需要一些耐心。 另请记住，解决问题的最快方法是直接提出更改， [https://github.com/ankidroid/Anki-Android/wiki/Contributing ](https://github.com/ankidroid/Anki-Android/wiki/Contributing)

Thanks for reminding.I understand, next time there is a problem, I will report it on the forum.

**Comment by ccvbc** [comment]
> 您好，感谢您的报告。 请编辑您的帖子以包含 [问题模板 ](https://raw.githubusercontent.com/ankidroid/Anki-Android/main/.github/ISSUE_TEMPLATE/issue_template.md)
> 
> 您可能想尝试 [我们的 Alpha ](https://github.com/ankidroid/Anki-Android/releases)版，看看这个问题是否已解决。
> 
> 谢谢！

Question has been modified
Is the "Alpha" version "parallel" and which one is more stable, parallel A?
Forgive me for asking you such a simple basic question.
![图片](https://user-images.githubusercontent.com/103726582/187231986-70b41440-2f08-4838-9918-1f3ade5a8148.png)

**Comment by ccvbc** [comment]
> “并行”表示您可以并排安装多个不同版本的 AnkiDroid。 并行构建在其名称中添加了指示的字母，因此它们看起来像 Android 系统的独立应用程序（AnkiDroid.A、AnkiDroid.B 等）
> 
> “Alpha”是指我们 2.16 系列的测试版本之一。 [https://github.com/ankidroid/Anki-Android/releases/tag/v2.16alpha82 ](https://github.com/ankidroid/Anki-Android/releases/tag/v2.16alpha82)是我输入的最新版本
> 
> 在这一点上，我认为 2.16alphas 实际上更稳定。 当人们尝试 alpha 时，2.15 中有几个崩溃已解决
> 
> 一个具体的例子：如果您下载并安装 2.16alpha82.parallel.A - 为了在保持 2.15.6 安装完好无损的情况下并排测试它，您可能会注意到在 alpha 版本中，这里失败的事情对您有用.

Thank you for your answer,I got it.

**Comment by ccvbc** [comment]
> 您好，感谢您的报告。 请编辑您的帖子以包含 [问题模板 ](https://raw.githubusercontent.com/ankidroid/Anki-Android/main/.github/ISSUE_TEMPLATE/issue_template.md)
> 
> 您可能想尝试 [我们的 Alpha ](https://github.com/ankidroid/Anki-Android/releases)版，看看这个问题是否已解决。
> 
> 谢谢！

I have tried the "alpha" version, it works fine, it seems he has been resolved.

I'm glad to find that there are more features in this version, I once missed a "treasure".

**Comment by mikehardy** [comment]
There are a huge amount of new features in the 2.16 series :-), and more coming.

Glad it fixed your crash!

If you feel a little adventurous, you may go to the "settings" --> "advanced" tab and turn on "new backend" and "v3 scheduler" to get the statistics heatmap, the v3 scheduler, a more efficient sync and a new card info page.

If you try that and notice anything wrong, please come log an issue here and we will investigate

Cheers!
