### ISSUE TITLE
how to edit the text in akpg files?

### ISSUE THREAD

**Issue by king129954** [ankidroid/Anki-Android#12239]
Hello reading https://github.com/ankidroid/Anki-Android/wiki/Database-Structure I cannot find the exact field that contains the front of the card. Unless it is in 'flds'. But even then I don't know how to open apkg files outside of anki to edit them either manually or with a script. Should I convert them to csv files first and then import? How do I convert apkg to cvs and keep the scheduling info if that's how to do it?

**Comment by david-allison** [comment]
Hi, GitHub issues are for issues with AnkIDroid. 

Question would be better solved on the [Anki forums](https://forums.ankiweb.net/), [reddit](https://www.reddit.com/r/Anki) or [Discord](https://discord.com/invite/qjzcRTx)
