### ISSUE TITLE
Improve/document debugging Coroutine errors

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#12238]
I had an issue where the following line call was throwing due to the exception below:

https://github.com/ankidroid/Anki-Android/blob/9f050a6041d53cfb200fab39deee4e457f35a631/AnkiDroid/src/main/java/com/ichi2/anki/preferences/AdvancedSettingsFragment.kt#L135

```
com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory /storage/emulated/0/AnkiDroid
        at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:255)
```

This raised an `AlertDialog`, but nowhere in the stack trace was there a reference to the method/lambda/class which caused the exception. It was frustrating to track down the responsible call.

https://github.com/ankidroid/Anki-Android/blob/c69218e6ad452f859eb72e8a9a1806104bda5650/AnkiDroid/src/main/java/com/ichi2/anki/CoroutineHelpers.kt#L109-L116

I would ideally like to see: `AdvancedSettingsFragment.kt:135` somewhere in the AlertDialog, OR the stack trace of the calling code somewhere in Android Studio

**Comment by divyansh-dxn** [comment]
I guess, printing the stack-trace logcat is enough. No need to show a lot of text in AlertDialog.
