### ISSUE TITLE
Same/multiple gesture for function.

### ISSUE THREAD

**Issue by gustavosmendes** [ankidroid/Anki-Android#12245]
In older ankidroid version - google play version - I could use the same gesture for "show answer" and "Answer button 3". In newer beta versions, i can't do this. 

Also, i could add multiple gestures to the same function. I.e. touch right AND swipe right for answer button 3. 

Is there any way issue related to this feature?

**Comment by david-allison** [comment]
> In older ankidroid version - google play version - I could use the same gesture for "show answer" and "Answer button 3". In newer beta versions, i can't do this.

'Answer Button 3' now performs 'Show Answer' on the front of the card

> Also, i could add multiple gestures to the same function. I.e. touch right AND swipe right for answer button 3.

This is still possible. yo can 'add gesture' multiple times

![Screenshot 2022-08-30 at 14 29 10](https://user-images.githubusercontent.com/62114487/187449770-bc217e3f-c263-4492-963e-ae9e6b35963d.png)

**Comment by gustavosmendes** [comment]
My apologies. I tested it multiple times before creating this issue. Thanks for the answer.

**Comment by david-allison** [comment]
No worries, thanks for alpha testing!
