### ISSUE TITLE
Add Anki Forum URL in Readme file in `Join Us On` section

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#12244]
[Anki Forums](https://forums.ankiweb.net/) is place for getting help / discussions related to Anki Ecosystem so it will be helpful for new users.

Add Anki Forums icon in `https://github.com/ankidroid/Anki-Android/tree/main/docs/graphics/logos` dir and link it to `https://forums.ankiweb.net/`

**Comment by pratyaksh1610** [comment]
It will be this, right ?
![ankiforum](https://user-images.githubusercontent.com/76740999/187474519-26e3600b-c6db-47bd-a32a-9aea1f188aeb.png)

**Comment by krmanik** [comment]
It is right.

**Comment by pratyaksh1610** [comment]
@krmanik Okay, cool.
Thanks !
