### ISSUE TITLE
[Bug] LaTeX in SchedV3

### ISSUE THREAD

**Issue by lervag** [ankidroid/Anki-Android#12249]
After changing to the new backend and the v3 scheduler, LaTeX now mostly does _not_ render the images. An example may be more illuminating: The image on the left is what I see during review, whereas the image on the right shows how I would expect the markdown to display.

![out1](https://user-images.githubusercontent.com/998898/187606763-bd68f848-5a77-44ac-8a3f-08dea926bf7c.jpg) ![out2](https://user-images.githubusercontent.com/998898/187606768-952c4157-ed6e-4ccf-9097-cce0e5918542.jpg)

Notice, though, that the expected result is still achieved if I inspect it through the card browser's preview mode (this is what we see to the right above).

Also, for reference, the actual html content of the card displayed in the screenshots are listed below. The `data-original-markdown` attribute is used to store a Markdown version of the card, which is a well-known technique for using markdown as the "source" for Anki cards.

```html
<p data-original-markdown="WyQkXSAobisxKVBfe24rMX0oeCkgPSAoMm4rMSl4UF9uKHgpIC0gblBfe24tMX0oeCkgWy8kJF0=">[$$] (n+1)P_{n+1}(x) = (2n+1)xP_n(x) - nP_{n-1}(x) [/$$]</p>
```

###### Reproduction Steps

I am not 100% sure it is reproducible. However, if it is, I would suspect this should be how:

1. Ensure AnkiDroid is set to the new backend and the v3 scheduler (not sure if the latter is relevant).
2. Create a card on PC with LaTeX, e.g. something like this:
    ```
    [$$] f(x) = 1 [/$$]
    ```
3. Verify that this displays correctly on the PC. Then synchronize with AnkiWeb.
4. Synchronize to AnkiDroid.
5. Do review until a card with LaTeX (as above) appears.

###### Expected Result

The card displays the compiled LaTeX image.

###### Actual Result

The card displays the _markup_.

###### Debug info

```
AnkiDroid Version = 2.16alpha82
Android Version = 12
Manufacturer = samsung
Model = SM-G986B
Hardware = exynos990
Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G986B Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36
ACRA UUID = 21db2d73-841c-4d39-9ed5-be24f8bac647
Scheduler = std3
Crash Reports Enabled = true
DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lervag** [comment]
I've disabled the new backend for now. Not having LaTeX content renderred properly is a serious issue for me.

**Comment by mikehardy** [comment]
@lervag totally understandable, thanks for the testing effort (and logging this issue) - it is appreciated

**Comment by lervag** [comment]
I will be glad to continue testing when this issue is solved and will of course follow the issue. If I can be of help with e.g. testing a PR or something, let me know.
