### ISSUE TITLE
Make back button in popup toolbar smaller 

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#12242]
The size of back button should be smaller, similar to activity toolbar.

<img src="https://user-images.githubusercontent.com/12841290/187354677-d1b1a5c7-edaa-4047-a06f-b9573dd1b49d.jpg" height=450px></img>

**Comment by pratyaksh1610** [comment]
Similar to #11916

**Comment by krmanik** [comment]
Thanks, It should be closed.
