### ISSUE TITLE
Add new schema to emulator test in CI

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12246]
> it can't be tested until the new schema becomes the default in CI

I'll add new schema (probably via writing a local.properties if the matrix variable for new schema is set?) to our matrix in CI to start the process of exercising it regularly

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/12226#issuecomment-1231788968_

**Comment by mikehardy** [comment]
This one is pretty important - I'll get to it if no one else does, all things in due time...

**Comment by mikehardy** [comment]
Unit tests are doing this now, just need to do emulator as well

**Comment by dae** [comment]
New schema is the default now.
