### ISSUE TITLE
Keyboard not shown when focusing HTML input/contenteditable elements

### ISSUE THREAD

**Issue by abdnh** [ankidroid/Anki-Android#12251]
###### Reproduction Steps

1. Create a basic note with `<input type="text">` in the front.
2. Review the card and tap on the input box to focus it.

###### Expected Result

The keyboard should pop up.

###### Actual Result

The keyboard is not showing up, though the input seemingly has focus as it appears from the orange outline around it. Typing using a physical keyboard doesn't work either.
On the emulator, pressing tab to focus the input instead does cause the keyboard to show up.

###### Debug info

Tested on 2.16alpha39 using Android Studio Emulator:

```
AnkiDroid Version = 2.16alpha39

Android Version = 11

Manufacturer = Google

Model = sdk_gphone_x86_arm

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 11; sdk_gphone_x86_arm Build/RSR1.201013.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36

ACRA UUID = 8efa639d-c6d2-4a45-ae75-7220a7835b01

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Demo
[untitled.webm](https://user-images.githubusercontent.com/41397710/187616672-ce01750f-bab0-4953-966a-8aa654133324.webm)

The deck shown in the video: https://drive.google.com/file/d/1DfCCC6s8UjdMrx4H1e22qOVUAESq4cLW/view?usp=sharing

###### Related

I've also reported a similar issue in AnkiMobile here: https://forums.ankiweb.net/t/keyboard-not-always-shown-when-focusing-html-input-contenteditable-elements-on-ankimobile/22711
In the AnkiMobile case, dae has suggested a solution that worked for me. If the cause of the issue here is the same or similar, maybe a similar solution can be implemented in AnkiDroid?

**Comment by mikehardy** [comment]
> AnkiDroid Version = 2.16alpha39

Can you try with the most up to date release? That one is pretty old... https://github.com/ankidroid/Anki-Android/releases

**Comment by abdnh** [comment]
Tested with the latest main ([c9deb5f](https://github.com/ankidroid/Anki-Android/commit/c9deb5fdfa11e4049e369e04194ffefa271ef346)). The issue is still reproducible.

**Comment by mikehardy** [comment]
Ah, well that's unfortunate. Thanks a bunch for testing that @abdnh - especially taking the time to test the latest code and report it. Need investigation...

**Comment by abdnh** [comment]
Update on this: It turned out that enabling the "Type answer into the card" option fixes the issue, probably as a side effect of this line: https://github.com/ankidroid/Anki-Android/blob/43fffa5f52221069ef9707b27d1082de31caad0b/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L1072

How about setting isFocusableInTouchMode to true in all cases? I guess in this case, the webview can steal focus from the normal type box that's separate from the card? But maybe there is another workaround for this...

**Comment by MohitGupta121** [comment]
Is this issue is still open @abdnh ?

**Comment by abdnh** [comment]
Yes.

**Comment by MohitGupta121** [comment]
I want to work on this, can you please assign me?

**Comment by abdnh** [comment]
You should ask @mikehardy about this (I'm not a maintainer). But looks like no one is working on this yet, so I would say go ahead!

**Comment by MohitGupta121** [comment]
Okay sure, @mikehardy can you assign me this issue if no one is working on this.

**Comment by mikehardy** [comment]
Sure! If no one else is working on something and you drop a comment saying you're working on it that's good enough I think.

If you see an issue that you want to work on and someone mentioned they already are but it has been a couple weeks, you can just ask if they are still working on it and go from there depending on response ( ...or if no response in a couple days)

**Comment by MohitGupta121** [comment]
Okay sure, @mikehardy I'll take care of that next time.

**Comment by MohitGupta121** [comment]
> Sure! If no one else is working on something and you drop a comment saying you're working on it that's good enough I think.
> 
> If you see an issue that you want to work on and someone mentioned they already are but it has been a couple weeks, you can just ask if they are still working on it and go from there depending on response ( ...or if no response in a couple days)

Is there no need to assign issues? I continue my work and raise PR?

**Comment by mikehardy** [comment]
We have enough people working on the repository that as maintainers we just can't keep up with issue assignments etc - we need people to self-organize a bit more, even in the absence of official assignments. So a polite system of dropping a comment / checking on status of previous commenters if needed, then going ahead can work well I think. I happen to be here right now so I can assign it but I think as long as people are collaborating (that is critical!) it can work regardless

**Comment by mikehardy** [comment]
Should be said: thanks for the interest in working on it either way :-), very appreciated

**Comment by MohitGupta121** [comment]
Yep great. Thank you for clearing my doubts. I'll start working on this issue. 
Okay I take care for that next time and see previous comments to get the issue stage.

**Comment by MohitGupta121** [comment]
> 

So I have to fix it with other way? Right?

**Comment by krmanik** [comment]
Wait for AnkiDroid maintainers to have a look on the issues.

**Comment by MohitGupta121** [comment]
Yes sure, I'll wait for their response.

**Comment by mikehardy** [comment]
I don't have time to thoroughly review the related PR because it is more subtle than it seems.

Here is a related change: https://github.com/ankidroid/Anki-Android/commit/805b923be6e141e15e83b3e5e87abad819ea2aff

What's happening?
- USE_INPUT_TAG and a javascript implementation in card.js + AbstractFlashcardViewer was created for API >= 15
  - note: we are minSdkVersion 21 now, so we may be able to remove any SDK conditionals related to it if they still exist...
- it *may* be valid to make the change you made in the PR, @MohitGupta121 but it may not. It will need testing with a card that has a type answer field in it to make sure a regular input in the card template works, *and* type answer still works
  - if the change is valid, you should remove the related comment as well

So in your PR test section please expand to include a case where the card template also has a type answer field and we'll see if it still works

**Comment by MohitGupta121** [comment]
Okay I'll check that and follow that.

**Comment by SanjaySargam** [comment]
Can I work on this issue if no one is working?

**Comment by MohitGupta121** [comment]
> 

Actually I raised PR for this and figuring out.

**Comment by SanjaySargam** [comment]
> > 
> 
> Actually I raised PR for this and figuring out.

Ok No problem
