### ISSUE TITLE
Passcode and biometric lock

### ISSUE THREAD

**Issue by z99h** [ankidroid/Anki-Android#12254]
**Is your feature request related to a problem? Please describe.**
I would like to keep my A AnkiDroid private when I pass my phone to a friend for activities such as watching videos.

**Describe the solution you'd like**
Add a passcode / biometric lock option to AnkiDroid, once enabled the actual AnkiDroid interface is hidden in "switch between recent apps" and the user needs to type in a passcode (or uses biometric such as fingerprint) to unlock when switch back to AnkiDroid - similar to what the Telegram app or Element Matrix app has.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by BrayanDSO** [comment]
Have you tried an external app to add password/biometric lock to access some apps (in the case, AnkiDroid)? May actually be easier so suit your use case and could solve your issue immediately.

**Comment by david-allison** [comment]
I'd rather this were done in the Android OS or as a fork. 

Adding in biometric security would add complexity (for example: how would our API work?), and would imply to users that we've secure (potentially encouraging them to store confidential data), whereas the feature does little to deter a motivated attacker.

**Comment by mikehardy** [comment]
Yeah - this is not something we should do I think. But there are lots of "app lockers" I think ?
Like https://www.androidauthority.com/best-applocks-privacy-lock-apps-android-750699/

I think some vendors integrate one even

I think that's sufficient for a "light security" case like you describe
