### ISSUE TITLE
Differentiate the before and after merge Strings label message

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12267]
> Message to maintainers, this PR contains strings changes.
> 
> 1. Before merging this PR, it is best to run the "Sync Translations" GitHub action, then make and merge a PR from the i18n_sync branch to get translations cleaned out.
> 2. Then merge this PR, and immediately do another translation PR so the huge change made by this PR's key changes are all by themselves.
> 
> Read more about updating strings on the wiki,
> 
> * [localization-administration](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#localization-administration)
> * [download-localized-strings](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#download-localized-strings)

so this should be the "after merge" message. Perhaps making the "before" and "after" messages different would be more helpful

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/12264#issuecomment-1233587218_

**Comment by krmanik** [comment]
The check should be implemented. I will update it.

**Comment by krmanik** [comment]
@david-allison @mikehardy 
What will be post merge commit message? Should only one comment suffice or post merge comments needed?

**Comment by david-allison** [comment]
Maintainers: please [Sync Translations](https://github.com/ankidroid/Anki-Android/actions/workflows/sync_translations.yml) to produce a sync with only the automated changes from this PR
