### ISSUE TITLE
[Question]Sync hostkey Url change 

### ISSUE THREAD

**Issue by dobefore** [ankidroid/Anki-Android#12269]
**Is your feature request related to a problem? Please describe.**
It seems the request url about user authentication has changed from `/sync/hostKey` to `/hostKey ` in 2.16 alpha82.

I would like to know whether  this change will be remain the same in stable release 2.16.

Thanks in advance.  

Add:use case I use it under self-hosted server in semi-WIFi

**Comment by david-allison** [comment]
@oakkitten

**Comment by dobefore** [comment]
Sorry for this. the error is on my side.

**Comment by dobefore** [comment]
Here,I have experienced some slight change when I set up self-hosted server address.
Take an example, my address is 192.168.x.196.
In version 2.15.6 ,I set sync address with `http://192.168.x.196:27701/` and output in server log is ok with `POST /sync/hostKey HTTP/1.1" `

However,the situation changed with version 2.16 alpha78 or above. I set sync address with `http://192.168.x.196:27701/`  as usual and sync. The output in server log is `"POST /hostKey HTTP/1.1"` (in version like alpha78 or 80 It will automatically add suffix /sync) .In this case ,I have to complete the address with `http://192.168.x.196:27701/sync`

So I assume this is a break change ?

**Comment by dobefore** [comment]
Here,I have experienced some slight change when I set up self-hosted server address.
Take an example, my address is 192.168.x.196.
In version 2.15.6 ,I set sync address with `http://192.168.x.196:27701/` and output in server log is ok with `POST /sync/hostKey HTTP/1.1" `

However,the situation changed with version 2.16 alpha78 or above. I set sync address with `http://192.168.x.196:27701/`  as usual and sync. The output in server log is `"POST /hostKey HTTP/1.1"` (in versions like alpha78 or 80 It will automatically add suffix /sync) .In this case ,I have to complete the address with `http://192.168.x.196:27701/sync`

So I assume this is a break change ?

**Comment by oakkitten** [comment]
There was a change, yes, you have to enter `http://192.168.x.196:27701/sync/` now (if you are using the new backend, the final slash must be present for the time being). If you had `http://192.168.x.196:27701/` before, after updating to a new app version (including alpha versions) you should see that the setting has been set to `http://192.168.x.196:27701/sync/`.

See #12112 for rationale

**Comment by dobefore** [comment]
I appreciate it that your contributions make the component of setting up custom server and even the ankidroid better. I just look through the conversations maked in PR #12112 to try to grasp the main idea.

Some improvements are great! such as the separation of collection sync and media sync and UI notification advance. It's no accident that the PR has been accepted and approved and the experts who had been reviewing it have said yes to it.

However,I have something to say.

> The custom sync URL preferences must have / at the end of the URLs.

Although this is technically correct,this will put burden on our users(including me). What will I write about sync address if I write articles introducing the server to people? I may write separate addr in order to adapt to such changes.

As far as I know,Anki has undergone approximate change at version 2.1.28 ,yet we can use add-on to wrap two differences and won't cause trouble to people.And further,Why not web browser opt for such forced change like `https://github.com/` ?

Why not allow the two ways to co-exist ?

>  This can lead to some quite obscure errors, e.g. inputting http://192.168.1.90:8080

I wonder if the error will happen again if I compelte the addr with `http://192.168.1.90:8080/sync/,even if the port is not what we defined in the server.

**Comment by oakkitten** [comment]
> > The custom sync URL preferences must have / at the end of the URLs.  

> Although this is technically correct,this will put burden on our users(including me). What will I write about sync address if I write articles introducing the server to people? I may write separate addr in order to adapt to such changes.

Hopefully this is fixed in the backend for the next stable release; when it is fixed, entering both `http://192.168.x.196:27701/sync` and `http://192.168.x.196:27701/sync/` will be valid.
> Why not allow the two ways to co-exist ?

Technically `http://192.168.x.196:27701` can be a valid sync endpoint.

> This can lead to some quite obscure errors, e.g. inputting http://192.168.1.90:8080/

>> I wonder if the error will happen again if I compelte the addr with http://192.168.1.90:8080/sync/ ,even if the port is not what we defined in the server.

The problem is that the backend doesn't append `/` when appending path segments, so instead of `http://192.168.1.90:8080/meta` you get `http://192.168.1.90:8080meta`, and `8080meta` is not a valid number. Again, this is hopefully fixed for the next release, and is only a problem if you are using backend.

> after updating to a new app version (including alpha versions) you should see that the setting has been set to http://192.168.x.196:27701/sync/

> > This seems a great idae,but what if I am not updating from an older version and straightfowardly install the lastest?

 I understand that after it is released there will be a bit of confusion as different versions will be expecting different values (with `/sync/` or without it). However in the long run having two consistent settings while also following Anki's expectations is beneficial.

In #12112 I am also talking about introducing new preference UI elements to make things simpler, and adding some help text. I suppose this help text might include a note about how the setting now expects `/sync/`.

**Comment by dobefore** [comment]
Thanks for the kind and detailed reply
