### ISSUE TITLE
[Bug] an invalid "Undo" button appears on Deck Overview screen

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#12277]
###### Reproduction Steps

0. (Close AnkiDroid, and restart it)
1. Tap any of the decks on "Decks" screen
2. Tap "SHOW ANSWER"
3. Tap any of the answer buttons
4. Go back to "Decks" screen
5. Tap the deck counts area of the deck (the right side area of the deck's row)
![image](https://user-images.githubusercontent.com/10436072/187925111-afe2eca5-9e3f-4338-a3cd-d55efcd63538.png)
6. Tap "Undo" button
![image](https://user-images.githubusercontent.com/10436072/187923767-14fe6902-db2c-49d8-9323-3c96102498ba.png)
  _Note: If you tap the deck counts area of the deck before the step 1 above, you can confirm that the "undo" button doesn't exist._
![image](https://user-images.githubusercontent.com/10436072/187931557-a269e063-3f25-4cd5-9a23-01687d61baee.png)

###### Expected Result
The review above gets undone.
![image](https://user-images.githubusercontent.com/10436072/187925718-c31cca99-0dbe-46fb-a394-8545b7fed36b.png)

###### Actual Result
Nothing happens.  The button doesn't respond when tapped (except for its ripple effect).
![image](https://user-images.githubusercontent.com/10436072/187926783-c34eb79a-f873-403d-ae72-a58c7e34201b.png)

###### Video
https://user-images.githubusercontent.com/10436072/187922084-a1c27361-300a-4f25-ab71-c65bea67959d.mp4

###### Debug info
```
AnkiDroid Version = 2.16alpha82

Android Version = 10

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; CPH2013 Build/QKQ1.200209.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.99 Mobile Safari/537.36

ACRA UUID = 69410480-0b9c-401f-ae8d-94da0f29c9dc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
#11220 seems to be a part of this issue.
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
I went through the code and the item click listener is set in there but the button is not getting clicked

**Comment by pavreh** [comment]
It is similar to #9490

**Comment by criticalAY** [comment]
I have removed the undo button from the main screen page as it was not necessary I guess but I am unable to commit my code due to JAVA_HOME error which I did not encounter when I contributed earlier.

**Comment by mikehardy** [comment]
If you are getting an error that you need help with, please actually post the full details of the error message, ideally enclosed in triple-backticks so the markdown format is easy to read here, like

```
error JAVA_HOME not set
please determine why your shell environment is not setting JAVA_HOME and set it correctly
```

You don't specify what operating system you are running on, how your environment is initialized, how you reproduce the error, or what troubleshooting steps you've taken already to determine + resolve your problem (https://stackoverflow.com/help/how-to-ask). If you open a command prompt / terminal and type `which java` or `java -fullversion` or `echo $JAVA_HOME` etc, what does it tell you?

Those are steps to take, and the results should help determine root cause

**Comment by criticalAY** [comment]
> If you are getting an error that you need help with, please actually post the full details of the error message, ideally enclosed in triple-backticks so the markdown format is easy to read here, like
> 
> ```
> error JAVA_HOME not set
> please determine why your shell environment is not setting JAVA_HOME and set it correctly
> ```
> 
> You don't specify what operating system you are running on, how your environment is initialized, how you reproduce the error, or what troubleshooting steps you've taken already to determine + resolve your problem (https://stackoverflow.com/help/how-to-ask). If you open a command prompt / terminal and type `which java` or `java -fullversion` or `echo $JAVA_HOME` etc, what does it tell you?
> 
> Those are steps to take, and the results should help determine root cause

Thankyou Mike I figured it out by defining the system variable that went missing idk how but yes also there is some issue with gitHub desktop version as I was not able to commit my code through it but cmd line.

**Comment by criticalAY** [comment]
ok so i guess i have figured it out today when i was free i will test it out and push the code.

**Comment by alyoshenka** [comment]
I've reproduced the error as well, and this video might expand on where exactly things work and don't work.

### Debug Info
```AnkiDroid Version = 2.16alpha82

Android Version = 10

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; CPH2013 Build/QKQ1.200209.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.99 Mobile Safari/537.36

ACRA UUID = 69410480-0b9c-401f-ae8d-94da0f29c9dc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```
### Steps where Undo works as expected
1. Open a deck
2. Select "Show Answer", select an answer
3. Select "Undo" button
    - Undo works as expected
4. Select "Show Answer", select an answer
5. Navigate back to DeckPicker
6. Tap Study Options (numbers on right side of deck name)
7. Tap "Study"
8. Select "Undo" button
    - Undo works as expected
9. Select "Show Answer", select an answer
10. Navigate back to Deck Picker
11. Select option menu at top right
12. Select "Undo last review"
    - Undo works as expected

So in these 3 different cases, undoing works as expected. The only place it **doesn't** work is as described in the original issue. Just wanted to help out by showing that it *does* work as expected
 in every other flow.

Selecting "Use the new backend" does not solve the issue, nor does "Use the v3 scheduler"

![undo_button_discrepancy](https://user-images.githubusercontent.com/38815390/198346884-245471a5-c779-49ff-93f8-e25241ee803e.gif)

**Comment by alyoshenka** [comment]
[Here](https://github.com/ankidroid/Anki-Android/blob/eede7eb5e09833f83ed8cef1d068c339d56362ec/AnkiDroid/src/main/res/menu/study_options_fragment.xml#L8) is the problematic line. Removing it makes the Undo button work as expected.

[Here](https://github.com/ankidroid/Anki-Android/commit/7351e8481615bb2edd181153a6d9db8c429cf776) is the commit where this line was added. This issue has to do with making the Undo button RTL Compliant. 

Currently looking into better fixes, but this seems to be the reason it doesn't work.

**Comment by criticalAY** [comment]
> [Here](https://github.com/ankidroid/Anki-Android/blob/eede7eb5e09833f83ed8cef1d068c339d56362ec/AnkiDroid/src/main/res/menu/study_options_fragment.xml#L8) is the problematic line. Removing it makes the Undo button work as expected.
> 
> [Here](https://github.com/ankidroid/Anki-Android/commit/7351e8481615bb2edd181153a6d9db8c429cf776) is the commit where this line was added. This issue has to do with making the Undo button RTL Compliant.
> 
> Currently looking into better fixes, but this is the reason it doesn't work.

I did figure out that and removed the line : ) and got a nice lecture from David later which helped to understand why was it placed there. We need to fix the RTL file ig

**Comment by alyoshenka** [comment]
`RtlCompliantActionProvider` is populated with an Activity. When an options item is selected, it runs `onOptionsItemSelected(itemID)`. This is why all other instances of Undo work: they're all Activities. BUT since `StudyOptionsFragment` is a Fragment, it doesn't work as expected. Also, `StudyOptionsFragment` uses `onMenuItemClick` to handle menu item clicks. When the undo button is pressed, `StudyOptionsActivity.onOptionsItemSelected(undoID)` is called. In theory you could just handle Undo in this parent Activity, but that seems improper. I am currently looking into making `RtlCompliantActionProvider` work with Fragments, or how to pass the `onOptionsItemSelected` function down from `StudyOptionsActivity` to `StudyOptionsFragment`.

**Comment by alyoshenka** [comment]
Looked into `MeuHost/MenuProvider` to handle menu interactions, but could not find many references for getting it to work, since it's a relatively new feature. The particular difficulty with this issue is that a Toolbar is used. I could not get `MH/MP` to get initialized as the documentation demonstrates.
