### ISSUE TITLE
Rename `Try anyway` to `Retry`

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12273]
>Instead, it should show the "You are offline - Try anyway" snackbar

I feel that "Try anyway" is a bit odd, unnatural as a response to "You are offline". In this context, "Retry" seems more appropriate.

"Try anyway" seems to mean "try syncing even if I am offline", so it may sounds nonsense, whereas "Retry" seems to imply "try syncing again after any actions (e.g. enabling Mobile data/Wi-Fi, waiting some time, etc.), which makes sense.

_a sample of probably appropriate usage of "do anyway"_
![image](https://user-images.githubusercontent.com/10436072/187882480-d69b2932-bcf2-4f60-912b-ab4353256269.png)

How about using "Retry" instead of "Try anyway"?

_Originally posted by @snowtimeglass in https://github.com/ankidroid/Anki-Android/issues/12261#issuecomment-1234045382_

**Comment by pratyaksh1610** [comment]
I am working on this

**Comment by david-allison** [comment]
That's exactly what it means. `isOnline` was not fully reliable: https://github.com/ankidroid/Anki-Android/issues/5381 https://github.com/ankidroid/Anki-Android/issues/6396 https://github.com/ankidroid/Anki-Android/pull/6397

This may no longer be the case

**Comment by BrayanDSO** [comment]
> This may no longer be the case

Perhaps. Idk if the lack of reliability is restricted to `activeNetworkInfo`, which are only used on API 21 and 22. Will need investigation

**Comment by david-allison** [comment]
Report was on Android 6.0 (API 23): https://github.com/ankidroid/Anki-Android/issues/5381

**Comment by mikehardy** [comment]
Hi there! :wave: your friendly maintainer of react-native-device-info here. Online detection is a disaster. It's not reliable.

Ask me how I know! https://github.com/react-native-netinfo/react-native-netinfo/issues?q=is%3Aissue+sort%3Acomments-desc+is%3Aopen

:laughing: 

"Try Anyway" is absolutely correct in this sense. It's the user saying "Shut up computer, I know I have internet, just do it"

**Comment by BrayanDSO** [comment]
Not ideal for the user, but this is what we have and seems good enough to me

**Comment by snowtimeglass** [comment]
I understand that the online detection isn't reliable, and that the string, "Try anyway", is the result of taking it into consideration, but then, I am concerned about appropriateness of the message of the snackbar, "You are offline".

Taking the unreliable online-detection-judgement at face value and telling users it as it is doesn't seem to be user-friendly. "Hey, wait, you are offline""Shut up computer, I know I have internet, just do it" -- it may be acceptable as relationship between computer and programmers at back-end, but it doesn't seem to be desirable relationship between AnkiDroid and its end-users. 

How about using a bit more moderate and modest message, for example, "You may be offline", "No internet connection found"?

**Comment by mikehardy** [comment]
Well, I suppose if we expect well-mannered users who do not hurl abuse at their devices, your suggestion of softening the "You are offline" language is pretty good. "You seem to be offline" maybe?
