### ISSUE TITLE
Search function - highlight searched word

### ISSUE THREAD

**Issue by heilil** [ankidroid/Anki-Android#12276]
If I search for a specific word in my learning cards, it shows me the cards containing this word. But unfortunately it does not highlight the word inside the text. As sometimes my learning cards contain a bigger text, it would be useful, if the specific word I am searching for, would be somehow highlighted or similar inside the text.

See picture attached, which shows bigger paragraphs, where I have to look for the searched word.

Would be great for a future update, otherwise I love working with your great app :)

Best regards
![Screenshot_2022-08-08-18-07-33-551_com ichi2 anki](https://user-images.githubusercontent.com/111989552/187919226-e2665196-e29e-4796-94ee-65b91b283dd3.jpg)

**Comment by MohitGupta121** [comment]
@heilil I want to work on this issue can someone assign me this.
