### ISSUE TITLE
[Bug] java.io.IOException: ‘No space left on device’ thrown syncing media collection when there is plenty of room on the device.

### ISSUE THREAD

**Issue by Greenactivist** [ankidroid/Anki-Android#12285]
###### Reproduction Steps

1. Press sync button
2. 
3. 

###### Expected Result
Collection and media synced

Note that the AnkiDroid directory is set to: /storage/2962-1FC/Android/data/com.ichi2.anki/Ankidroid
Which is on an external 512 GB SanDisk SD card and only 121 GB has been used so far.  the file that AnkiDroid is trying to download is only 32K so there should be no problem.

###### Actual Result
![image](https://user-images.githubusercontent.com/92814600/188165431-1b57a123-857a-44f7-b9de-2bb2da314656.png)

###### Debug info

AnkiDroid Version = 2.15.6

Android Version = 9

Manufacturer =Fairphone

Model = FP3

Hardware = qcom

Webview  User Agent = Mozilla/5.0 (Linux; Android 9; SAMSUNG SM-G960U Build/PQ3A.190801.002; wv) AppleWebKit/537.36 (KHTML, like Gecko)Version/4.0 Chrome/96.0.464.54 Mobile Safari/537.36

ACRA UUID = 82018eb2-dacb-4c43-b104723f08036eae

Scheduler = std2

Crash Reports Enabled = true

DatabseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Fairphone! Neat.

To your issue:

Can I ask you to try our latest release https://github.com/ankidroid/Anki-Android/releases and in particular these things:
1- make absolutely sure you really do have space on the device - then try sync again. Does it reproduce?
2- go to advanced settings and turn on "new backend" if 1 above did not work. Does it still reproduce?

If it does, then...something is messed up perhaps with handling UTF-16 file characters or similar :thinking:

**Comment by dobefore** [comment]
> Which is on an external 512 GB SanDisk SD card 

Does it mean that you are using external storage instead of local storage? I assume that the Ankidroid probably still use local storage as its prefered storage or It write some data which larger than the local can hold. From the picture
I find your cards are large.

**Comment by Greenactivist** [comment]
Thanks for you quick reply.   I’m beginning to think that this is an Android problem.

First there is plenty of room on the SD card.  I can use adb to push giggabytes of data into other directories on the same SD card.  I can even push files into AnkiDroid directory, /storage/2962-19FC/Android/data/com.ichi2.anki/Ankidroid <http://com.ichi2.anki/Ankidroid>,  with no problems, the but I can’t push anything into the collection.media subdirectory and Ghost Commander won’t copy anything into it either.  I always get the same exception.

It looks like there is a limit to the number of files a directory can contain - I have a lot of small files - although I haven’t seen that documented anywhere.

If I am right about this then the solution would seem to split the collection into separate directories of collection.media.  Looking around, someone claims this works for the desktop version of Anki.  Do you know if it will work for AnkiDroid?  

I think I will experiment with this and see what happens.

-- 
Sent with Tutanota, enjoy secure & ad-free emails. 



2 Sept 2022, 3:30 pm by ***@***.***:

**Comment by dae** [comment]
What filesystem is it formatted as? Fat32 has a limit on the number of files.

**Comment by Greenactivist** [comment]
Yes, that is correct.  In preferences have set AnkiDroid directory to point to a directory on the external SD card so the Anki database etc and all my media collection is there.  The App itself uses about 82MB if internal storage.

I have used a setup like this for years and using several operating systems - I now use /e/os a de-Googled version of Android and my phone is rooted using Magisk.  This set up has worked perfectly for about 3 years.

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



3 Sept 2022, 12:17 am by ***@***.***:

**Comment by Greenactivist** [comment]
It looks like I will have to find out how to format my card as ex-Fat.

Thanks all for your help!
-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



3 Sept 2022, 12:26 am by ***@***.***:

**Comment by mikehardy** [comment]
That will be the solution (or ext2 or similar) - sorry for this, haven't seen a FAT fs for years! :-). Used to be a big problem for us but has thankfully faded.

**Comment by Greenactivist** [comment]
Thanks for your reply.

I was beginning to think it must be something like that.  I can’t remember what file system is on the card.  I am so used to using Linux file systems that problems like that don’t occur to me.  

If I can’t find some sort of work around then maybe I’ll have back up the card and re-format it.

-- 
 Sent with Tutanota, enjoy secure & ad-free emails. 



3 Sept 2022, 12:26 am by ***@***.***:
