### ISSUE TITLE
Don't show "Created deck" toast after tapping OK on filtered deck dialog

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12284]
A whole activity is being shown so you can configure your filtered deck, which IMO is enough feedback + the toast is shown above the filtered deck settings, which pollutes the view a bit

![image](https://user-images.githubusercontent.com/69634269/188123168-050097e2-4255-4fea-960d-ffb8673197c5.png)

**Comment by snowtimeglass** [comment]
The toast isn't shown on 2.16alpha82 in my device, strangely.

https://user-images.githubusercontent.com/10436072/188178408-c37964e1-8221-4e08-9627-1fa81f7866e0.mp4





###### Debug info
```
AnkiDroid Version = 2.16alpha82

Android Version = 10

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; CPH2013 Build/QKQ1.200209.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.99 Mobile Safari/537.36

ACRA UUID = eebcb40f-3377-438f-afa3-59d9cae062bc

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by BrayanDSO** [comment]
The toast was introduced after alpha82

**Comment by snowtimeglass** [comment]
Ah, I see. Thanks.
