### ISSUE TITLE
Hide/Disable "New cards after reviews" if v3 Scheduler is enabled

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12319]
###### Reproduction Steps

1. Settings > Reviewing > New card position > **New cards after reviews**
2. Enable v3 Scheduler on advanced
3. Start reviewing cards

###### Expected Result

The new cards are shown after reviews

###### Actual Result

The new cards are mixed with reviews

###### Debug info
I've got a media sync crash recently after tapping `Background`, but not related to the issue
```
AnkiDroid Version = 2.16alpha82

Android Version = 12

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-N770F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 28fc9ae4-faa1-462f-9711-2249aec8346e

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
 ```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
In the v2 scheduler, the setting is collection-wide. In the v3 scheduler, the setting depends on which deck you click on, and the new deck options screen will show that deck-specific option. Does that explain things @BrayanDSO?

**Comment by BrayanDSO** [comment]
So, this should be solved when the new deck options is merged? Should the global setting be removed in the future?

**Comment by dae** [comment]
When the v2 scheduler is removed in the future, the global option should be removed too
