### ISSUE TITLE
Recall what gesture the window is for

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12326]
When assigning gesture, there is nothing that recall on which action a gesture is currently being assigned. Can someone please add a title, so that it's certain that I didn't misclick and that I have no doubt whether I'm at button 2 or 3 already.

Ping @BrayanDSO since you worked on it

**Comment by BrayanDSO** [comment]
+1 for the issue

For whoever wants to implement this, think on a string (Maybe `Add key for "%s"` and `Add gesture for "%s"`) and change it here:

https://github.com/ankidroid/Anki-Android/blob/ab5bfc3ef44d0db8e913590b92176166be43d835/AnkiDroid/src/main/java/com/ichi2/preferences/ControlPreference.kt

**Comment by pratyaksh1610** [comment]
I have raised a PR. 
PTAL. 
Thanks.
