### ISSUE TITLE
"show the answer" gesture should indicate it's not necessary

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12327]
Currently "Show the answer" is only useful if you have no gesture/action to select one of the four answers.
Indeed, if you have one gesture to select an answer and you're on question side, it'll show the answer.

So it'd be nice to indicate:
* on button 1 to 4 that they also show the answer
* on "show the answer", if at least one button has a gesture, that the user can also use the gesture(s) _gesture description_ associated with _button i_

Or maybe rename to "show answer/answer _n_"

Another option would be to ensure that it's okay to have the same gesture for "answer _n_" and "show answer", and ensure that by default the "answer _n_" don't show answer too.

This is not trivial to discover, and the trouble is that if you decide to use the same gesture on both side of the card, and it's not easy to discover on the new gestures.

Ping @BrayanDSO since you worked on gesture

**Comment by SanjaySargam** [comment]
@Arthur-Milchior Can you explain a little bit more about issue?

**Comment by SanjaySargam** [comment]
@BrayanDSO Can you explain a little bit more about the issue?

**Comment by BrayanDSO** [comment]
It's always to ask the original poster about the issue (@Arthur-Milchior). 

I personally haven't found this an issue nor had got confused by this, so I can't relate much.

**Comment by SanjaySargam** [comment]
> It's always to ask the original poster about the issue (@Arthur-Milchior). 
> 
> I personally haven't found this an issue nor had got confused by this, so I can't relate much.

Ok Fine
