### ISSUE TITLE
[Bug] Deck picker app bar items vanish after timed out sync

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12320]
###### Reproduction Steps

1. Use the old backend
2. Disable your internet
3. Tap sync
4. Tap try anyway
5. Wait until timeout error dialog appears
6. Tap outside the dialog (not on OK)

###### Expected Result

Everything is normal

###### Actual Result

Search, Sync and three dot icons vanish

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha82

Android Version = 12

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-N770F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 28fc9ae4-faa1-462f-9711-2249aec8346e

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment]
I think this one is a real thing...
