### ISSUE TITLE
[Bug] The same colour of a cursor and the background 

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12337]
###### Reproduction Steps
1. Have Light Day theme
2. Open Card browser
3. Tap Search
4. Type some text
5. Tap inside the text

###### Expected Result
The cursor is visible

###### Actual Result
The cursor has the same colour as the background
![Screenshot_20220907-144943_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/188940440-34c0cf2e-705d-4ca8-b6d9-d0415ecad6ca.png)

###### Debug info
AnkiDroid Version = 2.16alpha83

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 5df52f79-f5cd-436f-8b15-11830f324973

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by omsurase** [comment]
any suggestions as to where should I start looking in the codebase?

**Comment by Arthur-Milchior** [comment]
same issue occurs in search in deck picker. 
Please, whatever the fix is, only do the change for this particular color.
