### ISSUE TITLE
[Bug] TTS languages in the dropdown menu aren't sorted alphabetically 

### ISSUE THREAD

**Issue by WiliTest** [ankidroid/Anki-Android#12345]
###### Reproduction Steps

1. open a deck
2. click on the 3 vertical dots to open the menu
3. chose "Set TTS languages"
4. look at the order of the items

###### Expected Result

the language should be sorted alphabetically

###### Actual Result
Eg. "Spanish" is between "English" and "Estonian".

###### Research
*Enter an [x] character to confirm the points below: *

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Off-topic: congrats on issue 12345! 🚀🚀
