### ISSUE TITLE
[Bug] Valid add-on names depends on the locale

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12357]
Addon names should be lower case.
However, add-on names are tested using the device's default locale. 
Which means that an add-on name may be considered to be lower case or not depending on the device. So a package can be valid or invalid depending on the device's locale.

I assume it's mostly theoretical, but probably not ideal. 

Ping @krmanik

**Comment by Arthur-Milchior** [comment]
I should have put a link to the line of code in question.
I was referring to `https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/anki/jsaddons/NpmUtils.kt#L56` 
Which is used to validate the name and not to display it.

**Comment by krmanik** [comment]
I think this can be removed and only check on lowercase. 
` if (name.lowercase(Locale.getDefault()) != name) {`

**Comment by Arthur-Milchior** [comment]
Anything that uses `Locale.getDefault()` will depends on the default locale of the machine. So may succeed or fail depending on the machine. It's described on android documentation by

> Gets the current value of the default locale for this instance of the Java Virtual Machine.
>
> The Java Virtual Machine sets the default locale during startup based on the host environment. It is used by many locale-sensitive methods if no locale is explicitly specified. It can be changed using the [setDefault](https://developer.android.com/reference/java/util/Locale#setDefault(java.util.Locale)) method.

I believe that since your name should either always be valid or always invalid, we should not use getDefault in its validation system.
If this is a restriction from npm, I guess we should just check how NPM deals with it. Which definition of "lower case" do they use. And otherwise using some fixed language
