### ISSUE TITLE
[Bug] AddonData bugs if name is null

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12356]
In AddonData's `getAddonModelFromAddonData` if your addon's name is null, we create an error string, but we don't already return. Which means that below, we use `name!!` which would crash the app.
So, either we should return immediately or check non nullability below.

I prefer the second case, because, if we must send error message, I want to be as specific as possible, and just stating that some fields are null is not very helpful (actually, the message is not even accurate since it seems to implies all fields are null)

Ping @krmanik

**Comment by krmanik** [comment]
The PR is improvement on existing implementation. The second case should be considered. I have updated the PR to pass the test cases.
