### ISSUE TITLE
Card Browser Search bar

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12363]
when we search for something in the card browser then it shows the relevant search result but when we remove all the keywords the search result stays the same even after pressing search. Should not it be going back to its original state?

possible solution (my guess)
we can define a condition where an empty search returns all the cards or we can clear the search result when the search string is empty.

![Screenshot_20220910_001520](https://user-images.githubusercontent.com/48384865/189422146-cfdeae47-bdec-47da-a83c-8aa80d901a94.png)
![Screenshot_20220910_001548](https://user-images.githubusercontent.com/48384865/189422152-b6c5a937-ebf7-445f-8713-bced0baefe35.png)

**Comment by viciousAegis** [comment]
@david-allison IIRC this is expected behavior?

**Comment by viciousAegis** [comment]
On entering an empty search, it defaults to `deck:*` and searches for all cards

**Comment by david-allison** [comment]
Since we have the deck picker spinner, I don't think we'll want to follow that behaviour exactly. It does imply support that our 'do nothing' is incorrect

**Comment by viciousAegis** [comment]
I think we can search for `""`. Doing that on the `Clear` functionality for filter sheet shows all cards

**Comment by SySagar** [comment]
Hello , @david-allison , I would like to work on it.

**Comment by mikehardy** [comment]
Hey @SySagar go right ahead, good luck!

**Comment by Arthur-Milchior** [comment]
Agreed with David. Searching for the empty string should be equivalent to "deck:SelectedDeck" with the SelectedDeck from the spinner

**Comment by oakkitten** [comment]
Whenever I try searching for an empty string by pressing the magnifying glass icon in the keyboard, the keyboard stays, indicating that no search is performed. This seems to be [deliberate behavior](https://stackoverflow.com/questions/13576283) of `SearchView`. So I am not exactly sure how to reproduce this issue?

**Comment by oakkitten** [comment]
...Following the discussion on discord, given that you can't perform a search with an empty string, I would suggest closing this. It is possible to allow searches with an empty string using one of the workarounds in the linked SO question, but I don't think that the extra complexity is worth it.

**Comment by criticalAY** [comment]
I am closing this issue as it seems things are good to go. Thanks!
