### ISSUE TITLE
[Bug] Instant API AddContentApi.getAnkiDroidPackageName returns null

### ISSUE THREAD

**Issue by mvysny** [ankidroid/Anki-Android#12369]
Hi guys, for some reason on my Android 12 phone the `AddContentApi.getAnkiDroidPackageName(Context)` returns null, causing Aedict to errorneously report that AnkiDroid is not available.

###### Reproduction Steps

1. Install Aedict
2. Search for `haha` and open the entry details
3. In the upper-right overflow menu there should be a menu item "Export to `AnkiDroid"`

The menu item is hidden since `AddContentApi.getAnkiDroidPackageName(activity);` returns null. Full code of the Anki presence check function:

```java
    private boolean isAnkiDroidInstantAPIAvailable() {
        PackageManager manager = activity.getApplicationContext().getPackageManager();
        try {
            final String ankiDroidPackageName = AddContentApi.getAnkiDroidPackageName(activity);
            if (ankiDroidPackageName == null) {
                return false;
            }
            final ApplicationInfo appInfo = manager.getApplicationInfo(ankiDroidPackageName, 0);
            return true;
        } catch (PackageManager.NameNotFoundException e) {
            return false;
        }
    }
```

###### Expected Result

The `AddContentApi.getAnkiDroidPackageName(activity);` function should not return null

###### Actual Result

`AddContentApi.getAnkiDroidPackageName(activity);` returns null.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

* Aedict 3.50.24
* AnkiDroid 2.15.6
* Instant API version: `com.ichi2.anki:api:1.1.0alpha5`

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

I'll attach the debug info from AnkiDroid immediately.

The users reported that the same issue persists on Android 11 and 13, and that the ability to export to AnkiDroid was lost a couple of days ago.

Could it be that Google hardened Android and now some additional permissions are required to expose/access Content Providers? I have recently bumped target SDK API to 30 in Aedict, but the page at https://developer.android.com/about/versions/11/behavior-changes-11 says nothing about content providers :thinking: 

Aedict's AndroidManifest.xml lists `<uses-permission android:name="com.ichi2.anki.permission.READ_WRITE_DATABASE"/>` so the access should be granted. Or was it perhaps changed in newer AnkiDroids please?

**Comment by mvysny** [comment]
AnkiDroid Version = 2.15.6

Android Version = 12

Manufacturer = OnePlus

Model = IN2023

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; IN2023 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = cb794f2c-c872-4c02-a7d6-cec31fb39d8c

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment]
Interesting...sorry this is happening

Have you just recently moved to Android 12 from another version? Point of the question: this may be an Android12-specific thing

Only other thing I can think of is maybe the new alphas from https://github.com/ankidroid/Anki-Android/releases fixes it, but that is vague and low-probability-of-fix with a small risk of messes-up-other-things...still if you are adventurous and it isn't working anyway, might be a good test

**Comment by lukstbit** [comment]
@mvysny Android 11 introduced some changes that might be the reason for the issue, that's the [changes to package visiblity](https://developer.android.com/training/package-visibility). Looking at which packages are [visible by default](https://developer.android.com/training/package-visibility/automatic), ContentProviders are mentioned only if you have the uri permissions. 

So you could try to see if adding a [queries element](https://developer.android.com/guide/topics/manifest/queries-element) to the manifest for AnkiDroid's ContentProvider fixes this.

**Comment by mvysny** [comment]
@lukstbit thank you, excellent find! I'll try to add the queries element to AnkiDroid on my phone, let's see if it helps.

**Comment by mvysny** [comment]
@lukstbit thanks a ton, adding
```xml
    <queries>
        <package android:name="com.ichi2.anki" />
    </queries>
```
to Aedict's `AndroidManifest.xml` fixed the issue.
