### ISSUE TITLE
[Bug] Follow OS theme

### ISSUE THREAD

**Issue by xmha97** [ankidroid/Anki-Android#12377]
Please follow the OS theme to enable the dark theme automatically on Android.

**Comment by mikehardy** [comment]
Hi there! This is already implemented in the 2.16alpha series thanks to the excellent work of contributor BrayanDSO - please search the issues list prior to posting an issue, that is part of the new issue template that you removed

duplicate #12131
PR #10520

https://github.com/ankidroid/Anki-Android/releases
