### ISSUE TITLE
[Bug] Change a card type leads to an error

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12379]
###### Reproduction Steps
1. Add a basic and reversed note
2. Go to Card Browser, Edit the note, change Card Type to Basic
3. Save
4. OK

###### Expected Result
Card type is changed.

###### Actual Result
Card type is changed but an error appears. The error appears everytime I try to open Card Browser. Card Browser seems empty. Check database resolves the issue but there is no advice to run Check database.  
![Screenshot_20220912-101042_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/189613054-c5b5bc86-a231-4afe-917e-561a72b20e7c.png)

###### Possible solution
1. Check database could be run automatically after a note type is changed.
2. There could be an advice to run Check database in the error message.
![Screenshot_20220912-101042_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/189613406-6fdc546f-4aa1-4725-95ea-734d471def51.png)

###### Debug info
AnkiDroid Version = 2.16alpha83

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = d4a82cc8-397d-4a8f-81c8-87106ce0ba00

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
@mikehardy I've added a new tag for issues specific to the new schema; could you start tagging such issues in the future? I can't promise I'll address them, but it would be helpful to keep track of the issues that need addressing

**Comment by dae** [comment]
(I've now noticed you have an existing Rust label, but that implies the issue is in the Rust code - could we either rename it or re-purpose it?)

**Comment by mikehardy** [comment]
donel https://github.com/ankidroid/Anki-Android/labels?q=rust
