### ISSUE TITLE
[Bug] Crash when selecting text on the Note editor

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12381]
###### Reproduction Steps

1. Add or edit a note
2. Select text

###### Expected Result

Text is selected 

###### Actual Result

Crash OR the context menu doesn't appear

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha83

Android Version = 12

Manufacturer = samsung

Model = SM-N770F

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-N770F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.79 Mobile Safari/537.36

ACRA UUID = 02e6a05c-0a8a-4db5-bbd1-e9239428793b

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mahmood199** [comment]
By context do you mean the options which user gets whether to select/cut/copy the text 
Correct?

**Comment by BrayanDSO** [comment]
> By context menu do you mean the options which user gets whether to select/cut/copy the text
Correct?

Yes.

**Comment by BrayanDSO** [comment]
this was already fixed by 4b7c104c4e3f05bd58440d450ecf835d5dc8a74e. Closing
