### ISSUE TITLE
Display name of currently studied parent deck in review

### ISSUE THREAD

**Issue by Lilalas** [ankidroid/Anki-Android#12385]
**Problem**

When studying a parent deck with several subdecks, the top bar will always display the name of the subdeck the current card is from. This could be an unwanted cue in some situations (a.k.a. ‘cheating’).

**Reasoning**

Suppose I am studying `Language`, for which I have created a large deck with thousands of cards. To make it easier to maintain (export decks, manage unseen cards etc.), my deck is divided into several subdecks corresponding to the semester I learned the vocabulary:

```
Language
    Semester 1
    Semester 2
    Semester 3
    Semester 4
```

This structure also allows me to quickly select a specific semester to study (e.g. study `Language::Semester 4` when preparing for the exam in the fourth semester), but usually I would study the parent deck so that I get cards from all semesters intermixed.

Now suppose I selected the parent deck `Language` to study and I am shown a card whose answer I cannot quite recall. My eyes wander to the top of the screen and I see that the headline is saying `Semester 1`. Now I know, it must be one of these ‘beginner words’ I learned in the first semester, and I can suddenly remember the answer (because of this information).

**Solution**

The solution is simple and should also be easy to implement. Just display the name of the parent deck that was selected for studying, instead of the subdeck the current card is from.

Alternatively there could also be an option to completely disable showing the deck name in the top bar. In my opinion, it does not really add anything useful to the review.

My current hacky workaround is a simple hardware mod that covers the top bar. (This actually serves as a conversation starter when I study around people.) <details><summary>Show photo</summary><img src="https://user-images.githubusercontent.com/10713547/189761170-7c605e2a-1424-494c-a29d-d3e971b7e7ac.JPG" width="600" /></details>

**Comment by mikehardy** [comment]
Hi there - you might like the combination of gestures and immersive mode in settings - to hide the top bar stuff

**Comment by Lilalas** [comment]
Appreciate your suggestion, that is certainly more practical than my current workaround.

Although ideally I would like to keep the system status bar and also the top navigation buttons.

**Comment by Mehar18** [comment]
searching for solution..

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by BrayanDSO** [comment]
Nor Anki or AnkiMobile shows the deck name on the top of the screen, only AnkiDroid.

Particularly I feel that removing the title (which serves as a cue and cues are bad for active recall, as OP said) and the number of cards remaining (we have them in the minibar anyway) would be good. This would leave more space to the action buttons as well (suspend, bury, flag, reschedule, etc)

**Comment by user1823** [comment]
I support the idea of removing the title. This way, we will solve the current issue (the title serving as a cue and hurting active recall) and make AnkiDroid more consistent with Anki.

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by BrayanDSO** [comment]
Closing it since the original issue won't be created and I'll remove the deck title (or at least be able to hide it) in #14302

**Comment by Johnny-saints** [comment]
There is an option to hide system bar

**Comment by leyvReyn** [comment]
> Hi there - you might like the combination of gestures and immersive mode in settings - to hide the top bar stuff

thank you very much, this helped a lot!
