### ISSUE TITLE
[Bug] Whiteboard editor toolbar overlaps top toolbar when buttons set to appear at top or to not appear

### ISSUE THREAD

**Issue by lukstbit** [ankidroid/Anki-Android#12388]
###### Reproduction Steps

1. Go to Settings / Appearance / "Answer buttons position"
2. Select top or none(both have the bug)
3. Go to the decks screen and select one deck as you would do when reviewing
4. When a card appears then go in the top toolbar menu and select  "Whiteboard Editor"(you may have to enable whiteboard first here if it isn't already enabled)

###### Expected Result

The "Whiteboard Editor" toolbar doesn't overlap the top toolbar.

###### Actual Result

The "Whiteboard Editor" toolbar overlaps the top toolbar and makes it hard to see info there or access its menu. See images below:

When answer buttons are set to appear at the top:

![Screenshot from 2022-09-13 10-45-20](https://user-images.githubusercontent.com/52494258/189844486-50ed3d2d-d2d0-48fb-a518-9545f0598edc.png)

When answer buttons are set to not appear(when using gestures):

![Screenshot from 2022-09-13 10-45-50](https://user-images.githubusercontent.com/52494258/189844637-e79a2bb8-b780-4130-807a-2107f1238a77.png)

Present in the latest alpha([2.16alpha83](https://github.com/ankidroid/Anki-Android/releases/tag/v2.16alpha83)) but this issue was present way before(just got to post the bug report now).

For maintainers: do we have analytics data about this feature(the answer buttons positioning)? Maybe we could remove the positioning options and let the whiteboard editor toolbar sit at the bottom where it works ok? 

*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
- No, we don't have analytics for this pref
- I'm not in favor of removing it. Particularly, I use the setting with "None" and interact with the reviewer with only gestures/controls. I've heard before that some people do the same.

**Comment by Marius1501** [comment]
@lukstbit I would work on this issue. Do you know how you can check wether the "Answer buttons position"-option is set to Top or None?

**Comment by lukstbit** [comment]
@Marius1501 Sorry for taking so long to answer.

> Do you know how you can check wether the "Answer buttons position"-option is set to Top or None?

You can always get a reference to the application SharedPreferences and then look at the value for the corresponding key. The key of the preference you're looking for is `answerButtonPosition` in the constants.xml file.
