### ISSUE TITLE
[Bug] Syncing Issues

### ISSUE THREAD

**Issue by kami-leo** [ankidroid/Anki-Android#12395]
1. Hello i am facing syncing problem and i am unable to login in ankidroid
2. ankidroid reports "you are currently offline" even though mkbile is connected to the mobile data is turned on.

**Comment by mikehardy** [comment]
Hi there! Are you sure you can log in directly to ankiweb using your mobile browser? That is worth checking:
https://github.com/ankidroid/Anki-Android/wiki/FAQ#sync-is-not-working

If that is working, you might try our latest alpha - if the app somehow detects you are offline but you *know* you are offline, it lets you just force it to try anyway. This can happen if you are on VPNs or other networks that behave in unexpected ways

https://github.com/ankidroid/Anki-Android/releases

**Comment by kami-leo** [comment]
Actually only the version of anki present in Play store can be installed. And all the versions are not being installed, and a message"app is not installed appears" in my Android phone having android version 11.
Plz help me fixing this problem. My whole week has been wasted away in fixing this problem.

**Comment by david-allison** [comment]
What happens when you install this: https://github.com/ankidroid/Anki-Android/releases/download/v2.16alpha84/AnkiDroid-2.16alpha84.parallel.A.apk

**Comment by escape0707** [comment]
> Actually only the version of anki present in Play store can be installed. And all the versions are not being installed, and a message"app is not installed appears" in my Android phone having android version 11.
> Plz help me fixing this problem. My whole week has been wasted away in fixing this problem. 

Anyway if you want help you will have to tell devs more info about which APK you can't install and exactly what store you see. Better with a screen shot of the exact version of APK and error message.
