### ISSUE TITLE
Option for the front of the card to be displayed on screen even after pressing "show answer"

### ISSUE THREAD

**Issue by jjijen** [ankidroid/Anki-Android#12424]
My japanese cards are built in such a way that the front has Audio only, and after pressing show answer the front will then reveal the japanese notation with kanji,  and the back\answer will display the english translation etc.  
On ankidroid, pressing show answer automatically fils my screen only with the back of the card, but the first thing I want to see is the notation that is written in the front.   To avoid scrolling up to see the front, and then back down to see the translation: 

I'd suggest an option that would keep ankidroid displaying a fixed position even after pressing "show answer"  , be that the top position of a card\front. 

I concidered there is probably a solution to this if I'l do a mass edit to the deck ,  making  the change to front side which occurs after pressing show answer ,  be part of the back side.  I do not know how to do such mass editing,  and the current layout works really good on my pc. 

example from my pc but I'l describe how it is on ankidroid: 

Card front before pressing show answer: 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/82251301/190853600-a531cc99-0682-4c80-9bd4-d29f83e82913.png">  

Card front and back after pressing show answer (above the line break is the front, below is the back) : 
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/82251301/190853675-2a8d7a7a-a11c-4674-ba75-eff48248f565.png">

Anki droid would automatically scroll down and display the back portion after pressing show answer:
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/82251301/190853711-00dc1c9a-6700-409c-a97d-5d5221c64d6f.png">

**Comment by BrayanDSO** [comment]
Both Anki and AnkiDroid automatically scrolls to a HTML element with the id of `answer`. As your desktop screen is bigger, you may have not noticed it, as it may show all the content at once

Could you check if there is something like it on the back of your note type? Searching for `id="answer"` then removing it should fix this.
