### ISSUE TITLE
Browser's filter sheet's `clear` string is hardcoded

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12426]
Noticed this while reviewing #12409

https://github.com/ankidroid/Anki-Android/blob/46f31e8af6cd0edff70b607221998fc4413758a5/AnkiDroid/src/main/res/layout/filter_bottom_sheet.xml#L34-L35

Haven't found a justification on the original PR, and we have a `Clear` string anyway, so it's best to use it

Pinging @viciousAegis

**Comment by yashjani01** [comment]
@BrayanDSO analyzing it..

**Comment by viciousAegis** [comment]
Oops. @yashjani01 would you like to work on fixing this? should be simple

**Comment by ShridharGoel** [comment]
@yashjani01 Are you working on it? Asking since @pratyaksh1610 has raised a PR but you had already commented here.

**Comment by viciousAegis** [comment]
@pratyaksh1610 Please comment on the issue that you'll be working on it so other people don't have to spend their time doing something that's already in progress :3

**Comment by yashjani01** [comment]
😪 I was working on it. But the problem has been solved.
@pratyaksh1610 👍
