### ISSUE TITLE
Hierarchical deck chooser when adding new note.

### ISSUE THREAD

**Issue by vi** [ankidroid/Anki-Android#12442]
**Is your feature request related to a problem? Please describe.**

When I use Share menu to add new card to AnkiDroid, it [rarely defaults to the deck i want][1], so I need to choose it from "Deck:" combobox.
But with many mini-decks it is cumbersome to scroll though `s::a::OneMinideck`,`s::a::AnotherMinidesk`, `s::b::YetAnother12CardsDeck` to get to the e.g. `words` deck at the end of the list. This contracts with the deck chooser from home screen, where you can expand and collapse deck folders.

[1]:https://github.com/ankidroid/Anki-Android/issues/12443

**Describe the solution you'd like**

For new note adder, use hierarchical/tree chooser for deck instead of a plain list.
Ideally such chooser be used everywhere, e.g. for statistics viewer as well.

**Workaround**

Abort adding new note, go do main screen, activate the deck you want from there (e.g. enter learning, then immediately exist), then share to AnkiDroid again. Now the deck you have entered before will be the default deck.

**Alternative**

~~Allow typing deck name from keyboard, showing filtered subset of matching decks in combobox to choose from.~~ Just noticed that there is already search function in that popup window (somehow I assumed it was a plain combobox before, not a separate view).

**Version**

2.15.6 from F-Droid.

**Comment by david-allison** [comment]
I feel this is fixed in 2.16, can you check it works as expected https://github.com/ankidroid/Anki-Android/releases/download/v2.16alpha85/AnkiDroid-2.16alpha85.parallel.A.apk

**Comment by BrayanDSO** [comment]
Currently, tags are hierarchical and decks are "semi" hierarchical. When I say "semi" is because the dialog isn't a collapsible tree view, but it has hierarchical indentation at least.

I haven't looked at the tag dialog code, but I suppose it shouldn't be hard to abstract part of it and reuse it on the deck dialog, especially because both decks and tags use a similar (perhaps equal) name/hierarchy pattern

**Comment by vi** [comment]
Just indentation alone won't save one from using multiple gestures to scroll though 70+ decks to reach the last one.

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by vi** [comment]
> Stale

Shall low-priority feature requests be tracked in Github or elsewhere?
2 months may be too short for a feature request to be considered stale.

**Comment by BrayanDSO** [comment]
Agreed

**Comment by salmanuc** [comment]
Hierarchical support still not available in statistics section

**Comment by salmanuc** [comment]
Also Hierarchical support still not available in deck selection in card browser
