### ISSUE TITLE
[Bug] Ankidroid widget bug

### ISSUE THREAD

**Issue by Zec69** [ankidroid/Anki-Android#12441]
Ankidroid widget doesn't show anymore the badge for cards due and i can't get it back.
![IMG_20220918_224129](https://user-images.githubusercontent.com/90362342/190927362-4bacee0e-70ef-4718-b64f-95060f631e66.jpg)

**Comment by mikehardy** [comment]
Hi there! It appears you have opened a new issue and specifically selected all of the template and deleted it.
That's a shame, it makes it hard to help.
Could you open a new issue and follow the instructions in the template? Most importantly, the debug information, as requested with a helpful link on how to get it
