### ISSUE TITLE
When adding new note, default to the deck chosen for adding before, not the deck last learned.

### ISSUE THREAD

**Issue by vi** [ankidroid/Anki-Android#12443]
**Is your feature request related to a problem? Please describe.**

When I add a note to AnkiDroid using "+" button or using "Share" action from other app, the default deck for a note to be added to seems to be the last deck I studied.
It means when I adding multiple notes using multiple "Share -> Anki card" actions, I need to choose the deck each time.

**Describe the solution you'd like**

I'd like AnkiDroid to default to the last deck a note was added to in this case, not the last deck studied / opened.

**Version**

2.15.6 from F-Droid.

**Comment by BrayanDSO** [comment]
Have you tried the `Deck for new cards` setting? I think it's under `Reviewing` on AnkiDroid 2.15.6 (version you are using)

**Comment by vi** [comment]
I see "Deck for new cards" setting in "AnkiDroid. General settings" group instead of "Reviewing. Non-deck-specific reviewer settings".
The setting has only two options: "Use current deck" and "Decide by note type". I don't understand what does "note type" mean when creating new note, especially when sharing text fragment from a browser.

**Comment by vi** [comment]
.
