### ISSUE TITLE
Add Pontoon as a place for translators to help (contributing/support messaging)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12452]
We need to start messaging the changes for translators in AnkiDroid (contributing, support etc) that Pontoon is a place to help with translations as well as Crowdin,

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/12448#issuecomment-1251267309_

**Comment by mikehardy** [comment]
If you are wondering what Pontoon is, check ankitects / ankiweb.net for documentation on how to contribute to upstream AnkiDesktop, it is their translation platform and we are starting to access some of their translations now, so Pontoon is something people using AnkiDroid may want to use in order to fix/add translations that will then show up in AnkiDroid

**Comment by lonewolf2208** [comment]
Hey @mikehardy , greeting. I am eager to work on this issue . Can you please assign this issue to me?

**Comment by mikehardy** [comment]
Sure - cheers!

**Comment by homocomputeris** [comment]
As a proofreader of both projects, I'd like to note that Pontoon is, unfortunately, far inferior to Crowdin.

**Comment by lonewolf2208** [comment]
Hey @mikehardy, I am new to this repo, so could you please guide me a bit more and elaborate on the issue. Also, how should I proceed to fix the issue?

**Comment by mikehardy** [comment]
First thing is to discover all the places that may be affected. When you are in a new codebase you've never seen, try

- Search the code base case-insensitive for the string in question, in this case "crowdin"
- For each location that is affected (discovered because it is related to "crowdin") add information in that place that "Pontoon" is also a place to do translations
- What is Pontoon? Go over to ankiweb.net and read up on how they handle translations https://docs.ankiweb.net/contrib.html#translating-anki --> https://translating.ankiweb.net/

Note that this affects documentation as well, so you'll want to update the wiki. It's a pain to search a wiki on the web but github wikis are actually repositories, you can clone it via git and search it via recursive grep as well https://search.brave.com/search?q=how+to+clone+github+wiki&source=desktop

**Comment by wonhyeongseo** [comment]
pontoon seems to be adding in features such as built-in MT and custom translation engines via Google AutoML translate. Have you made a decision regarding which l10n service to use during the past few months?
