### ISSUE TITLE
Media sync screen in new schema needs improving

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#12468]
There are a few issues with the current implementation:

- When the user taps on "background", there's no way to see that the sync is continuing, or to bring it back to the foreground. If the sync button checked if media was currently syncing, then it could bring the screen back. Maybe the icon could be animated, or have some other badge shown when syncing?
- "background" is hard-coded in English currently

**Comment by BrayanDSO** [comment]
I believe that a progress notification would be good here

**Comment by mikehardy** [comment]
Yeah I think it *has* to be a foreground-service connected to a progress notification or Android reserves the right to kill it at all times

**Comment by mikehardy** [comment]
Yes. This is a known issue, and it's fine to log it here, but it is not news exactly.
This will be one of the most involved parts of the migration to the new schema and will likely stay like this for a while, though it is not optimal, no.

I see the exact same behavior. It's the main sync happening (great), then the media sync starts (great), but the media sync has no progress (not great), if you background it there is no way to re-foreground it (not great), and that's that

**Comment by JalinWang** [comment]
Hi~ Any suggestions on how I could open the `Media sync screen` or enable `new schema`? I looked around for a couple of minutes and had no idea. 
Does `new schema` always refer to `new backend`?
![image](https://user-images.githubusercontent.com/20621784/193226247-bce4a8c3-7d30-4be1-8f9c-c0a93cc399df.png)

**Comment by BrayanDSO** [comment]
> Does new schema always refer to new backend?

Indirectly, yes. The new backend enables the new Anki SQL schema, although it may not be appropriate to interchange the terms sometimes

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by mikehardy** [comment]
Yeah this one is not going to go away without work and we cannot ignore it forever. Maybe not going to make it before 2.16 (likely not) but needs a pin

**Comment by BrayanDSO** [comment]
Noting: I'd started working on this and actually have it working with a foreground service with notification. There were some TODOs and I can't work on this for the time being. 

If anyone wants the code I did to get some jumpstart, ping me

**Comment by dae** [comment]
Media syncing is going to receive some refactoring in the not-too-distant future, so it might be worth holding off on any changes here until that's done.

**Comment by ChuckieChen945** [comment]
A minor suggestion:

The processes for both main sync and media sync are prone to interruption.

During the main sync process, any click outside the sync dialog will interrupt the sync process, as illustrated in the figure below:

![Screenshot_20240222_061506_com.ichi2.anki.jpg](https://github.com/ankidroid/Anki-Android/assets/29732324/a657e539-ba8c-4023-8936-17f5846eb97a)

![Screenshot_20240222_061510_com.ichi2.anki_edit_690738836641093.jpg](https://github.com/ankidroid/Anki-Android/assets/29732324/6a70bcd1-0561-4f84-8f71-0092de975b7a)

In the media sync process, clicking outside the sync dialog will close the dialog. There is no indication whether the sync has been moved to the background or has been interrupted. Based on the sync log, it appears to have been interrupted.

When initiating a sync, most users would prefer the program to run uninterrupted until the sync is complete. However, the current gestures are too sensitive and can easily lead to accidental interruptions, requiring the process to restart from the beginning.

As part of refining the media sync screen, it might be beneficial to introduce a confirmation step prior to an interruption, or perhaps consider a different gesture for interruption to minimize accidental triggers.
