### ISSUE TITLE
[Crash] Selecting filter by tag option in card browser results in a crash

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#12472]
###### Reproduction Steps

1. Open the card browser.
2. Select the "filter by tag" option.

###### Expected Result
The user is shown a list of existing tags to choose from.

###### Actual Result
The AnkiDroid app crashes.

###### Debug info
AnkiDroid Version = 2.16alpha85

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Thanks for logging this one too! I think I found it. I also think this is a more generic problem, not necessary v3/new-schema-related

Here's the installation:

https://ankidroid.org/acra/app/1/installation/c6a580cb-02cc-4970-b7a5-24615e6542e1/report

I think it's this crash:
https://ankidroid.org/acra/app/1/bug/15206/report/a7f86eac-1fac-4a7d-8bde-590a211475cb

```
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setTitle(java.lang.CharSequence)' on a null object reference
	at com.ichi2.anki.CardBrowser$CheckSelectedCardsHandler.setMenuIcons(CardBrowser.kt:30)
	at com.ichi2.anki.CardBrowser$CheckSelectedCardsHandler.actualOnPostExecute(CardBrowser.kt:6)
	at com.ichi2.anki.CardBrowser$CheckSelectedCardsHandler.actualOnPostExecute(CardBrowser.kt:1)
	at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.kt:9)
	at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.kt:8)
	at android.os.AsyncTask.finish(AsyncTask.java:660)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

logcat:

```
--------- beginning of main
09-20 12:23:56.151 E/AnkiDroid(23332): CollectionManager/ blocked main thread for 175ms:
09-20 12:23:56.151 E/AnkiDroid(23332): com.ichi2.anki.Reviewer.onStop(Reviewer.kt:30)
09-20 12:24:03.831 E/AnkiDroid(23332): CollectionManager/ blocked main thread for 3620ms:
09-20 12:24:03.831 E/AnkiDroid(23332): com.ichi2.anki.DeckPicker.onDeckClick(DeckPicker.kt:33)
09-20 12:58:18.838 E/AnkiDroid(23332): CollectionManager/ blocked main thread for 2008ms:
09-20 12:58:18.838 E/AnkiDroid(23332): com.ichi2.anki.CardBrowser.onCreate(CardBrowser.kt:101)
09-20 13:13:35.591 E/AnkiDroid(23332): CollectionManager/ blocked main thread for 114ms:
09-20 13:13:35.591 E/AnkiDroid(23332): com.ichi2.anki.CardBrowser$ChangeDeckHandler.actualOnValidPostExecute(CardBrowser.kt:51)
09-20 13:17:43.985 E/AnkiDroid(23332): CollectionTask/ CollectionTask CollectionTask class com.ichi2.async.CollectionTask$UpdateValuesFromDeck as Collection could not be opened
09-20 13:17:44.939 E/AnkiDroid(23332): CollectionManager/ blocked main thread for 393ms:
09-20 13:17:44.939 E/AnkiDroid(23332): com.ichi2.anki.StudyOptionsActivity.onStop(StudyOptionsActivity.kt:4)
09-20 13:30:18.255 E/AnkiDroid(23332): CollectionManager/ blocked main thread for 1429ms:
09-20 13:30:18.255 E/AnkiDroid(23332): com.ichi2.anki.CardBrowser.onCreate(CardBrowser.kt:101)
09-20 13:30:52.401 E/AnkiDroid(23332): CollectionManager/ blocked main thread for 175ms:
09-20 13:30:52.401 E/AnkiDroid(23332): com.ichi2.anki.CardBrowser$ChangeDeckHandler.actualOnValidPostExecute(CardBrowser.kt:51)
```

**Comment by TomerPacific** [comment]
@mikehardy , I'd like to help out with this.
Anything I should know before getting started?

**Comment by TomerPacific** [comment]
@mikehardy, 
I've tried reproducing the crash with the steps mentioned, but am not seeing it.
I also tried adding a deck with cards and a tag and seeing if that causes the crash as well.

Is there something I am missing?

Also, it seems like the line numbers from the stack trace don't actually correspond to the lines in the class itself.

**Comment by mikehardy** [comment]
in release mode the line numbers are sadly obliterated, so no - those are not meaningful and you're not just imagining it

bummer that you are not able to reproduce - I just tried it myself from current main branch and I am also not able to reproduce this.

Perhaps it is related to the collection in use and the tags in that collection :thinking: ? Perhaps it only happens on an android API24 device? I tried it in an API24 emulator and it still works on my test collection.

So the only thing I can think of is that it is collection dependent or perhaps already fixed on main and the next alpha will have a fix

**Comment by user1823** [comment]
I have tried the latest alpha release (86), but the issue persists.

For reproducing the issue, have you tried hierarchical tags (i.e. tags of the type A::B::C)?

**Comment by pavreh** [comment]
I tried the hierarchical tags and I found a different issue. No crash but the newly added tag is not in the list when Filter by tag. It is related to the new backend only. Check database repairs this. 

@user1823 Please run Check database and try reproduce again.

**Comment by user1823** [comment]
I ran Check Database, but the issue still persists.

**Comment by TomerPacific** [comment]
@user1823 , can you provide a bit more detail on how you reproduce the crash? What tags/decks do you have already on the application?
Can you share a screen recording?

@mikehardy  - Let me know how you would like me to proceed with this issue.

**Comment by mikehardy** [comment]
Without a reproduction there will be no progress, so I would move on.

**Comment by user1823** [comment]
My collection has sensitive data. So, I can't share it publicly. However, I installed a parallel build and tried to reproduce the issue.

I couldn't reproduce the exact same issue because the collection didn't have any tags.

However, when I tried to add a hierarchical tag (A::B) to a note, the app crashed. This didn't occur when I added a non-hierarchical tag (A).

Also, the crash occurred **with** and **without** the new schema enabled.

### Screen Recording

https://user-images.githubusercontent.com/92206575/194762732-2fb375fb-81c7-4c8c-aaac-d00a938e738c.mp4

### Debug Info
AnkiDroid Version = 2.16alpha86

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = 082087c3-5c47-456d-a85b-d03620ffa392

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by user1823** [comment]
I have tried the latest alpha release (alpha 86), but the issue persists.

For reproducing the issue, did you try out hierarchical tags (i.e. tags of
the type A::B::C)?

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by user1823** [comment]
I have upgraded my phone to one with Android 12 and I no longer see this happening. This makes me think that this issue is related to earlier Android versions (such as Android 7).
