### ISSUE TITLE
Text in the syncing screen seems to be too small

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#12474]
The text in the popup window that shows the sync status doesn't seem to be in proportion with the size of the popup.
Though this is a minor issue, it does deserve attention because it just doesn't look correct.
![Screenshot_20220921-183743](https://user-images.githubusercontent.com/92206575/191514015-17945598-c882-4703-95d1-1f515aa5e63d.jpg)

**Comment by user1823** [comment]
Similar issues are there with the sort options in the Note Browser:
![Screenshot_20220928-205012](https://user-images.githubusercontent.com/92206575/192819344-8c58fec9-c08a-499f-8a52-2c174d8e5a90.jpg)
![Screenshot_20220928-205007](https://user-images.githubusercontent.com/92206575/192819347-8c7e10f3-b14f-482d-af30-4e097aa9e7a1.jpg)

**Comment by Vedant755** [comment]
Can I work on the issue? I am a newbie and this seems to be good to test my skills as much I have learned so far in Android!

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by user1823** [comment]
I created this issue when I was on Android 7.

I am now using an Android 12 device and I don't feel that the text is too small on my device. However, it may have something to do with the fact that I have "Display Size" and "Font Size" set to Large in my Android settings.

I am not sure how the text looks currently on an Android 7 device.
