### ISSUE TITLE
[Bug] Special characters shown in dark grey in Dark theme

### ISSUE THREAD

**Issue by luizfepe** [ankidroid/Anki-Android#12479]
###### Reproduction Steps

1. Create a deck for Japanguage study  .
![Screenshot_20220922-084124](https://user-images.githubusercontent.com/5821104/191629454-338a83a0-60c8-41ab-bcf9-41d0ba7f3942.png)

2. Create a card containing special character from Portuguese language.

###### Expected Result
Show all words in white color.

###### Actual Result
The words with special character such as çàã are shown in dark grey or black color, being difficult to visualize over the dark theme background.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Could you please send your debug info here? Here's the [instructions](https://ankidroid.org/docs/help.html) (if you are on one of the latest alphas, the "About" screen is not on the "advanced" category anymore)

If possible, sharing the deck, or at least one card of it, would help a lot.

I am Brazilian, study Japanese on AnkiDroid daily and sometimes I add some comments in Portuguese. I have seen this on my daily usage, so I suppose this may be a problem with your deck, but I'd need the debug info and a sample of the deck to tell

**Comment by luizfepe** [comment]
Dear Brayan Oliveira,

Thank you for your quick reply.
Before I'm checking with the professor that makes his decks, to ensure this
is not a formatting issue.
I first create the issue ticket, but I know recognize it can be from his
source, and not actually a bug.
Therefore I asked him some tests and will report here as soon as I receive
the results.

Thank you again and have a nice day!
