### ISSUE TITLE
Higher contrast in the Tags and Cards options in the Note Editor (in dark mode)

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#12476]
###### Reproduction Steps
1. Install an alpha release newer than 2.16alpha85. (I have not tested the alpha releases prior to this release.)
2. Set the app theme to Black. (Settings -> Appearance -> Theme)
3. Go to Note Editor or Add Note window.

###### Expected Result
The tags and cards options at the bottom of the window should have a good contrast.

###### Actual Result
The Tags and Cards options in the Note Editor have white text on a (whitish) gray background. This is not a good design and certainly not good for accessibility.

Note: I don't know why but the background in the tags and cards options in the below screenshot looks slightly darker as compared to what I actually see in the app on my phone.

![Screenshot_20230120-091454](https://user-images.githubusercontent.com/92206575/213613346-b95c742a-b4ba-46a6-b65a-1d6dca23c473.png)

###### Possible Solution
The colour of the background in the tags and cards options should be made darker so as to increase the contrast.

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by user1823** [comment]
@BrayanDSO
Please add a "Good First Issue" label to this issue.

**Comment by BrayanDSO** [comment]
Could you describe the issue a little bit more? Like telling which theme(s) is generating the problem. New contributors may not understand what the task is.

**Comment by user1823** [comment]
I have edited my post to include more details.

Note that I can read the text in the tags and cards options well but the same may not be the case for everyone (especially the ones who are visually challenged).

This issue was one of my first impressions when I jumped from 2.15.6 to 2.16alpha85.

**Comment by karthik-anand** [comment]
Hi, I have made changes to the issue. 

![WhatsApp Image 2023-01-22 at 10 46 50(1)](https://user-images.githubusercontent.com/68493176/213901789-6e20a60e-9358-4f1f-b1fa-aa634d56547c.jpg)
![WhatsApp Image 2023-01-22 at 10 46 50](https://user-images.githubusercontent.com/68493176/213901790-9268350a-0bb8-4935-a85f-71c50887c12f.jpg)

Inserted images showing the new contrast setting in light and dark mode. Can I raise a PR?

**Comment by user1823** [comment]
These look good. But, I have two opinions:
1. The box around the tags and cards options should have rounded borders (as before).
2. You have not shared the screenshot of the screen in the "Black" theme.

**Comment by karthik-anand** [comment]
Incorporated your suggestions. What do you think about these?
![WhatsApp Image 2023-01-22 at 19 44 57](https://user-images.githubusercontent.com/68493176/213920417-677db00e-8c8d-49f8-9401-2585bca10c0a.jpg)
![WhatsApp Image 2023-01-22 at 19 44 571](https://user-images.githubusercontent.com/68493176/213920419-faa7488d-cbb1-494c-a51c-d1e52aec6f44.jpg)

**Comment by user1823** [comment]
They look better. But I suggest the following colors:
- In "Black" Theme: #303030 | rgb(48,48,48)
- In "Dark" Theme: #909090 | rgb(144,144,144)
- In "Light" and "Plain" Themes: #D3D3D3 | rgb(211,211,211)

After making the above changes, open a PR.

**Comment by prabs3257** [comment]
Is this issue still open to work ?

**Comment by karthik-anand** [comment]
I have made a [Pull request](https://github.com/ankidroid/Anki-Android/pull/13142)

**Comment by adityabarodiya** [comment]
I might be able to fix this issue. It could be my first contribution, please assign this issue to me.
