### ISSUE TITLE
FR: 1st variation of random card display will not be the same after a progress reset

### ISSUE THREAD

**Issue by anatoliibakhtin** [ankidroid/Anki-Android#12488]
**Is your feature request related to a problem? Please describe.**
Hi ! I always get frustrated when I use cards in random display mode, I choose to 'forget the cards (windows), reset progress (android)', time is reset, BUT its display mode is also reset, from 'random', to 'in order of addition'. If you go into deck settings - new cards - under 'order' is specified as 'random', but the cards are displayed 'in order of addition'.

**Describe the solution you'd like**
I want the 'forget-reset progress' button The time of its subsequent display was reset, but its display mode was not.

**Describe alternatives you've considered**
 I wrote on the [android](https://forums.ankiweb.net/t/bug-reset-the-card-progress-changes-the-order-in-which-it-is-displayed/22360/3) and computer forum about the situation (as there were problems there and there). [Abdo from computer version replied to me](https://forums.ankiweb.net/t/copy-reset-the-card-progress-changes-the-order-in-which-it-is-displayed/23174) that there are flags in the new PC version 'Restore original position where possible', 'Reset repetition and lapse counts' checkboxes that allow to keep previous card display mode after reset (it is so I checked). Please add this feature also in android version.

**Additional context**
demonstration of the problem:

![569e2170770efabbcd2815436a06f5ff398e73e7](https://user-images.githubusercontent.com/71871141/191804721-fd123a38-125a-4385-8ce8-07c0253f4610.gif)

![Obsidian_rifSG8Iz2L](https://user-images.githubusercontent.com/71871141/191810084-94fbc0b1-351b-402c-9135-9098c3d2251c.jpg)

Thank you for your attention !🎉

**Comment by anatoliibakhtin** [comment]
I'm still waiting... [AnkiDroid-2.16alpha84-arm64-v8a.apk](https://github.com/ankidroid/Anki-Android/releases/download/v2.16alpha84/AnkiDroid-2.16alpha84-arm64-v8a.apk)  has the same situation: The deck is set to random, but after resetting the cards (time), the deck is also reset to display in order, not in random, as I originally set it to do.

**Comment by mikehardy** [comment]
For what it's worth we're on 2.16alpha90 now with maybe 100 PRs merged since 84...
https://github.com/ankidroid/Anki-Android/releases

**Comment by anatoliibakhtin** [comment]
@mikehardy thank you! I checked, it's the same situation.

**Comment by anatoliibakhtin** [comment]
It would be cool if a much respected developer who took on this problem would commit here. Thank you for your attention.

**Comment by anatoliibakhtin** [comment]
Hi, I don't know why no one pays any attention to this bug. It's important to me, because when I'm learning English words, I create decks and portion them out to high potential, and then merge those decks afterwards. I have to do unnecessary things while I don't have this feature.
