### ISSUE TITLE
Make the "Card marked as leech" a snackbar instead of a toast

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12487]
**Is your feature request related to a problem? Please describe.**
I was doing my cards and got one wrong, so I had to tap again. Unfortunately it became a leech 😭. then I noticed that the "Card marked as leech"  message used a toast. As snackbars are preferred, we should replace it

**Describe the solution you'd like**
Use a snack bar instead of a toast for the "Card marked as leech" message

**Describe alternatives you've considered**
Keep seeing toasts every time I fail miserably to remember a card multiple times

**Comment by criticalAY** [comment]
Card browser -> select few cards -> reset progress. Also shows a toast.

**Comment by criticalAY** [comment]
Could you please help me a bit to reproduce this issue? I would like to work on it and fix it.

**Comment by pratyaksh1610** [comment]
@criticalAY  This could be a good starting point.
https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt

**Comment by criticalAY** [comment]
> @criticalAY This could be a good starting point. https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt

Thankyou!

**Comment by criticalAY** [comment]
@BrayanDSO I have fixed this. How to test it? Practical conditions so that I can test and make a PR.
