### ISSUE TITLE
Creating a filtered deck shows the study options fragment with no reason

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12480]
###### Reproduction Steps

1. Go to the deck picker
2. Tap the three dot menu > Create filtered deck
3. Tap ok on the dialog (the filtered Deck options activity will be shown)
4. Tap back

###### Expected Result

After tapping back, you should be back to the deck picker

###### Actual Result

You are on the study options screen and have to tap back again

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Hey! There is a whole function created for this in Deck Picker if I am not wrong. 
```
  private fun openStudyOptions(withDeckOptions: Boolean) {
        if (fragmented) {
            // The fragment will show the study options screen instead of launching a new activity.
            loadStudyOptionsFragment(withDeckOptions)
        } else {
            val intent = Intent()
            intent.putExtra("withDeckOptions", withDeckOptions)
            intent.setClass(this, StudyOptionsActivity::class.java)
            startActivityForResultWithAnimation(intent, SHOW_STUDYOPTIONS, START)
        }
    }

```
So is it ok to fix it and go to the main Anki Screen once the deck is created?

**Comment by criticalAY** [comment]
Hey! I am working on it and exploring the FilteredDeckOptions

**Comment by criticalAY** [comment]
@BrayanDSO But if we set up home as default display on back pressed then if we open the deck/ filtered deck again won't we be redirected to home itself from there rather the fragment (which I think is required).

**Comment by BrayanDSO** [comment]
I am sorry, but I can't get what you are trying to say.

**Comment by criticalAY** [comment]
I am saying that step 4 is necessary because when we access the filtered deck from the deck list then the back button should take us to the study option fragment which it does. We can not say it is there for no reason?

**Comment by BrayanDSO** [comment]
The issue is about when you create a filtered Deck. Not when you open an existing filtered deck in the deck picker

**Comment by criticalAY** [comment]
> The issue is about when you create a filtered Deck. Not when you open an existing filtered deck in the deck picker

Ok got it

**Comment by snowtimeglass** [comment]
>You are on the study options screen and have to tap back again

Just to confirm, does "the study options screen" mean the following deck overview screen?
![image](https://user-images.githubusercontent.com/10436072/192133605-7981c508-7f89-4cc2-83fa-630ccb5d638c.png)

**Comment by BrayanDSO** [comment]
Yep. Exactly that one
