### ISSUE TITLE
[Bug] Export saves a 0 bytes file 

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12490]
###### Reproduction Steps

1. Does not matter if the legacy schema or the new schema
2. Export a collection or export a deck

###### Expected Result

Functional .colpkg or .apkg is saved

###### Actual Result

The file is saved but it has 0 bytes and it cannot be imported.
The bug does not exist in 2.16alpha84.

###### Debug info
AnkiDroid Version = 2.16alpha85

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = bd3df842-8d38-48ea-8cb8-9ef2d08fbca2

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
The file appears to be non-zero before it's passed to the intent, so I suspect it's some sort of issue with the intent system such as inadequate permissions, or the file being located in an inaccessible place.

**Comment by divyansh-dxn** [comment]
Happened with me as well.

**Comment by divyansh-dxn** [comment]
https://user-images.githubusercontent.com/69595691/192163839-9b4d1709-716e-48df-8423-b5bc7487bbde.mp4

For me it happens only when I export using Android's system file manager, with other app (CX File Explorer) it was exported correctly. @pavreh Can you try using other explorer or save with any other method (emai, drive...etc) and let us know?

**Comment by pavreh** [comment]
When I tap Export - Send, it offeres two methods only, Bluetooth and Files. I am not able to send it by email or save it to G. drive. I use Samsung My Files as a file manager.
