### ISSUE TITLE
[Bug] Blanc empty cards (detailed)

### ISSUE THREAD

**Issue by ahmedbenarab** [ankidroid/Anki-Android#12526]
###### Reproduction Steps

1. opening a deck that contain some cards
2. nothing show on front nor back
3. i tried to change some settings like : toggling the hardware render , the safe display mode , allow files in media imports ... but non seems to fix the prob  
4. it seems like this issue appears just with the Basic note type
5. the cloze version is working well
6. i revised my basic note type on Anki desktop found that it contain some codes from the "closet" add on (idk if it is the issue or no 
7. the cloze note type cards don't contains such codes 

###### Actual Result

![image](https://user-images.githubusercontent.com/21174375/192890881-f1afd7b3-c041-4efc-8eb9-b66d50417398.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
> Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

This part is really important

**Comment by ahmedbenarab** [comment]
as i mentioned before, the problem was in the add on called "clozet for Anki" , just open the basic note type and remove all the js and css injected by this addon (after removing it ofc) then sync --> everythig is working well now
