### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by andrevaz1** [ankidroid/Anki-Android#12528]
###### Reproduction Steps

1. Good evening everyone, there is an error with the statistics, it does not appear in the entire deck, and in the deck all decks are duplicated

**Comment by andrevaz1** [comment]
Good evening everyone, there is an error with the statistics, it does not appear in the entire deck, and in the deck all decks are duplicated

**Comment by mikehardy** [comment]
Hi there!

The current implementation of statistics in the released version will see no further development.

In the 2.16 series (which I encourage you to try, you may get it here: https://github.com/ankidroid/Anki-Android/releases) has the Anki Desktop statistics package built in to it, and you may access that by going to settings -> advanced and turning on "new schema support"

At that point you'll have the same stats that you have on desktop (including the heatmap!), so things should work as expected
