### ISSUE TITLE
Check Media in ManageSpace

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12539]
In the Manage Space part of the application, as described in https://github.com/ankidroid/Anki-Android/issues/12366, we should allows the user to do "check media", and, if any unused media is found, delete them.
We can reuse code that already exists and implements this task in the settings. This option should also states how much storage the medias take.

If there is no collection (e.g. it was deleted before, or the app was never opened) this option should be disabled.

In case of issue with the collection, we should let the user know, but don't try anything to correct it. Instead, tell the user to use the regular app to try to fix it or do a full download.

This issue is NOT yet ready to be implemented. It is up to discussion. This message will be changed once we can implement it.

**Comment by mahmood199** [comment]
Would like to work on it.
Researching and Looking at the code that does this right now.

**Comment by Arthur-Milchior** [comment]
In case it was not clear by looking at the issue linked above; the managed space is already started in https://github.com/ankidroid/Anki-Android/pull/12371
It won't be merged as-is, but it's a good-start. You can pull this branch, and work yourself on adding this extra feature.

**Comment by mahmood199** [comment]
`We can reuse code that already exists and implements this task in the settings.`

By this do you mean to resuse the functions from abstract SettingsFragment? Please clarify

**Comment by Arthur-Milchior** [comment]
We already have a "check media" that can be accessed from the DeckPicker. You can reuse the same function. Actually, you should reuse the same function, and not implement a new "check media" yourself.
However, I do not know exactly where it is implemented. Finding it is part of the task, I guess

**Comment by mikehardy** [comment]
Stale bot you will *not* close this before the actual PR.
