### ISSUE TITLE
Use Markdown to highlight text

### ISSUE THREAD

**Issue by Avinash071** [ankidroid/Anki-Android#12537]
Markdown support would be great to highlight important parts of the text in between lines.

**Comment by Arthur-Milchior** [comment]
Hi @Avinash071.
AnkiDroid follows Anki behavior. So you'll need to ask it on https://forums.ankiweb.net/
If anki accepts it, personally, I'd be delighted; I entirely agree with you, in a lot of case, markdown would be far better than what we currently have. 
Once you have created a post there, please let me know, I'll be interested to follow the discussion

**Comment by sangorys** [comment]
+1

This should be the last killing feature I need  :)

**Comment by Arthur-Milchior** [comment]
Sadly, @sangorys , I can only repeat what I answered @Avinash071. 
I totally see your point, it would be a great feature. But this is not to us that it should be asked
