### ISSUE TITLE
Change the number of back-up in ManageSpace

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12538]
In the Manage Space part of the application, as described in #12366, we should add an option to let the user chose the number of back-ups. We can reuse code that already exists and implements this task in the settings. This option should also states how many back-ups they are currently and the size of the biggest one (Normally, most back-up should have approximately the same size)

This issue is NOT yet ready to be implemented. It is up to discussion. This message will be changed once we can implement it.

**Comment by SanjaySargam** [comment]
@Arthur-Milchior @oakkitten is this issue ready to implement?

**Comment by SanjaySargam** [comment]
> This has been implemented in #12765 along with the new backend settings support and other changes

Ok
Are there any other issues that are open related to manage space?

**Comment by oakkitten** [comment]
If you are looking to fix a thing with manage space activity, one major issue is in the TODO on a method that deletes the collection:

    // TODO: Finish other AnkiDroid activities when the collection is deleted.
    //   Note that this might be not quite trivial, as the activities might be visible to user.
    //   One way would be to have the activities register broadcast receivers that perform finish;
    //   Another would be maintaining weak references to them. Would be nice to find a better way.

This might be trivial or might be hard.

Also it would help a lot if you tested #12765 as described in https://github.com/ankidroid/Anki-Android/pull/12765#issuecomment-1320489763
