### ISSUE TITLE
[Crash] Moving a card to another deck results in crash

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#12542]
###### Reproduction Steps
I am not able to reliably reproduce this but following the below steps causes a crash on many occasions.

1. Open the card browser.
2. Search for a card (using the search bar) and select a card.
3. Choose Change Deck option and select the desired deck.

###### Expected Result
The card moves to the chosen deck and no crash occurs.

###### Actual Result
The card moves to the chosen deck but the app crashes.

###### Debug info
AnkiDroid Version = 2.16alpha85

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hey there 👋 - sorry that's happening, thanks a bunch for taking the time to log a report with the crash report / ACRA UUID

Your install is here https://ankidroid.org/acra/app/1/installation/c6a580cb-02cc-4970-b7a5-24615e6542e1/report

I see a couple different types of crash 

I think this is the one you log here: https://ankidroid.org/acra/app/1/bug/15206/report/6a6b4485-b245-486e-9213-ec99a14d626b

logcat

```
--------- beginning of main
10-01 07:59:21.623 E/AnkiDroid(24862): CollectionManager/ blocked main thread for 3229ms:
10-01 07:59:21.623 E/AnkiDroid(24862): com.ichi2.anki.DeckPicker.onDeckClick(DeckPicker.kt:33)
10-01 08:11:24.625 E/AnkiDroid(24862): CollectionManager/ blocked main thread for 108ms:
10-01 08:11:24.625 E/AnkiDroid(24862): com.ichi2.anki.CardBrowser.onCreateOptionsMenu(CardBrowser.kt:60)
10-01 08:18:09.758 E/AnkiDroid(24862): CollectionManager/ blocked main thread for 203ms:
10-01 08:18:09.758 E/AnkiDroid(24862): com.ichi2.anki.Reviewer.onStop(Reviewer.kt:30)
10-01 08:29:27.756 E/AnkiDroid(24862): CollectionManager/ blocked main thread for 627ms:
10-01 08:29:27.756 E/AnkiDroid(24862): com.ichi2.anki.DeckPicker.onDeckClick(DeckPicker.kt:33)
10-01 08:55:55.447 E/AnkiDroid(24862): CollectionManager/ blocked main thread for 266ms:
10-01 08:55:55.447 E/AnkiDroid(24862): com.ichi2.anki.Reviewer.onStop(Reviewer.kt:30)
10-01 09:00:49.056 E/AnkiDroid(24862): CollectionManager/ blocked main thread for 1365ms:
10-01 09:00:49.056 E/AnkiDroid(24862): com.ichi2.anki.DeckPicker.onDeckClick(DeckPicker.kt:33)
10-01 09:15:02.185 E/AnkiDroid(24862): CollectionManager/ blocked main thread for 264ms:
10-01 09:15:02.185 E/AnkiDroid(24862): com.ichi2.anki.CardBrowser$ChangeDeckHandler.actualOnValidPostExecute(CardBrowser.kt:51)
```

stack trace

```
java.lang.NullPointerException: Attempt to invoke interface method 'android.view.MenuItem android.view.MenuItem.setTitle(java.lang.CharSequence)' on a null object reference
	at com.ichi2.anki.CardBrowser$CheckSelectedCardsHandler.setMenuIcons(CardBrowser.kt:30)
	at com.ichi2.anki.CardBrowser$CheckSelectedCardsHandler.actualOnPostExecute(CardBrowser.kt:6)
	at com.ichi2.anki.CardBrowser$CheckSelectedCardsHandler.actualOnPostExecute(CardBrowser.kt:1)
	at com.ichi2.async.TaskListenerWithContext.onPostExecute(TaskListenerWithContext.kt:9)
	at com.ichi2.async.CollectionTask.onPostExecute(CollectionTask.kt:8)
	at android.os.AsyncTask.finish(AsyncTask.java:660)
	at android.os.AsyncTask.-wrap1(AsyncTask.java)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loop(Looper.java:203)
	at android.app.ActivityThread.main(ActivityThread.java:6251)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1075)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
```

Looks like there must be a race condition on menu item setting somehow

**Comment by pratyaksh1610** [comment]
I'll take this.

**Comment by lonewolf2208** [comment]
Hey @pratyaksh1610 if you are not working on this issue . I would like to take on this

**Comment by pratyaksh1610** [comment]
@lonewolf2208 Since it is good for first, you can work on this if you want to. 
Thanks.

**Comment by lonewolf2208** [comment]
Thanks @pratyaksh1610  , I am eager to work on this issue . Hey @mikehardy can you assign this to me ?

**Comment by pratyaksh1610** [comment]
@lonewolf2208 I think you can leave a comment saying that you are working on this , and raise a PR for the same 👍

**Comment by lukstbit** [comment]
@user1823 Thank you for the bug report. The code were the error happens was changed in the latest alpha(86). If you use this new alpha it would be helpful to mention if you still see the error happening.

I tried to reproduce it(with previous and newer alphas) but didn't manage to see it.

**Comment by user1823** [comment]
As I mentioned earlier, I am not sure on the exact conditions that lead to the crash. So, it is difficult for me to say that the issue has resolved.

I have installed the latest alpha and I haven't seen the crash yet. I will update here if I see the crash occurring.

**Comment by raehat** [comment]
@lonewolf2208 are you still working on this?
