### ISSUE TITLE
Delete everything in manage space 

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12540]
In the Manage Space part of the application, as described in https://github.com/ankidroid/Anki-Android/issues/12366, we should allows the user to delete everything.

The work is already being done on #12371 , so this issue is here only so that we can track this menu option separately from the general ManageSpaceActivity issue.

**Comment by mikehardy** [comment]
The work is not quite done - there's quite a bit of change that needs to happen in the *actual* implementation of deletion there per review - https://github.com/ankidroid/Anki-Android/pull/12371#discussion_r984227859

**Comment by Arthur-Milchior** [comment]
I beg your pardon. I rephrased.
My point was actually that we are not looking right now for someone to start this project, as it's started
