### ISSUE TITLE
Help: Back on dialog

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12559]
Shouldn't be be getting back to the main screen if we press somewhere else other than the dialog. Like as of now we get to the previous dialogue if we click outside the dialog box. https://user-images.githubusercontent.com/48384865/193473133-bf5aecaa-f15d-4680-9593-dedc4f940925.mp4

**Comment by lukstbit** [comment]
> Shouldn't be be getting back to the main screen if we press somewhere else other than the dialog

Normally yes, but there we have a hierarchy of dialogs and I think it makes sense to go back the the previous dialog even on tap outside. Ideally this part should be refactored to avoid the double dialog situation but there are more important things to tackle right now.

**Comment by mikehardy** [comment]
I disagree on a tap outside only going back, as an android user, if I tap outside a dialog I expect it to dismiss the dialog in almost all cases, and I don't see why the dialogs here would be an exception? I think this is a valid issue

**Comment by oyeraghib** [comment]
I would like to work on this, if no one has started yet.

**Comment by lukstbit** [comment]
@oyeraghib I think @criticalAY intended to work on this as he opened the issue, so lets wait a bit.

**Comment by oyeraghib** [comment]
sure!

**Comment by criticalAY** [comment]
Yes! I am on it but if I am running out of time or something I will let you know and you can overtake it @oyeraghib

**Comment by oyeraghib** [comment]
Sure, there is no rush. Take your time :)

**Comment by oakkitten** [comment]
Istead of trying to fix it, I would suggest replacing the recursive help dialog with a single bottom sheet dialog with a directory tree structure. This doesn't have too many items, so it will make things easier to find, and we (may soon) have the infrastructure to do this with minimal code.

Alternatively, put all the help of information in a HTML page and display that.

**Comment by criticalAY** [comment]
> Istead of trying to fix it, I would suggest replacing the recursive help dialog with a single bottom sheet dialog with a directory tree structure. This doesn't have too many items, so it will make things easier to find, and we (may soon) have the infrastructure to do this with minimal code.
> 
> Alternatively, put all the help of information in a HTML page and display that.

Okay let's see

**Comment by SySagar** [comment]
hello @criticalAY if you are not working on this , I will like to take it up.

**Comment by criticalAY** [comment]
> hello @criticalAY if you are not working on this , I will like to take it up.

Ahh I am on it.

**Comment by raehat** [comment]
@criticalAY hey are you still working on it?

**Comment by criticalAY** [comment]
I am not pushing any PRs for this rn because it needs time and there are other important things to handle right now as everyone is busy

**Comment by Sagar0-0** [comment]
> am not pushing any PRs for this rn because it needs time and there are other important things to handle right now as everyone is busy. We plan to replace the dialog fragment with bottom sheet dialog here

Should I do it?

**Comment by criticalAY** [comment]
> > am not pushing any PRs for this rn because it needs time and there are other important things to handle right now as everyone is busy. We plan to replace the dialog fragment with bottom sheet dialog here
> 
> Should I do it?

Ummm it's not that easy as it seems as I would not say it's a good first issue now, more like new feature implementation. Bottom sheet with tree structure. But if you wanna try it then sure give it a try. But you are taking it because of good first issue I would suggest this one in that case.

**Comment by mikehardy** [comment]
agreed I think this was a bit more complicated then it first appeared, removed good first issue tag for now, better to get a truly simple PR done as a first PR, to learn all the other stuff related to getting PRs merged on this project while the actual code change isn't so difficult

**Comment by criticalAY** [comment]
@mikehardy could you please mark it 'keep open' as it is a new feature that would be implemented afterward most probably after scoped storage migration.

**Comment by criticalAY** [comment]
The bottom sheet can be an improvement but as of now @lukstbit already have fixed the issue

**Comment by david-allison** [comment]
@criticalAY can this be closed? If not, what changes are still needed?

**Comment by criticalAY** [comment]
Yes we can I was talking about the bottom sheet but that's not coming anytime soon so closing it
