### ISSUE TITLE
[Bug] New cards indication bug

### ISSUE THREAD

**Issue by reyaz006** [ankidroid/Anki-Android#12553]
###### Reproduction Steps

1. Import a deck. It shows "20 0 0".
2. Do a full session.
3. The deck still shows "20 0 0".
4. Try to do a session again right away. It does not allow that and says "Congratulations! You have finished for now."
5. Check AnkiWeb. It shows "0 20" and allows to do a session.
6. If stopped before finishing a session, saved and synced, AnkiDroid will allow to proceed with this second session.
7. The deck will show "0 0 0" if finished a session through AnkiWeb and synced.

Checking database/media did not solve this issue.

###### Expected Result
The deck should show "0 0 0" after one session in AnkiDroid.

###### Actual Result
AnkiDroid does not drop "new cards" stat to zero after a session, and allows to do additional session if it's started from AnkiWeb.

###### Debug info
AnkiDroid Version = 2.16alpha85
Android Version = 12
Manufacturer = samsung
Model = SM-M315F
Hardware = exynos9611
Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-M315F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36
ACRA UUID = addfc480-9cb5-4465-8132-f2e29142ce3d
New schema = true
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Well...that's concerning.
Can I ask a favor? Can you try to reproduce this, after going in to settings -> advanced and enabling the v3 scheduler?
That will mean we're definitely all working on the newest scheduler code (shared with Anki Desktop! So I'll be very surprised if this still happens, but we really want to know if so...)

Great problem report by the way - with the description and the debug info I was able to quickly determine what the next step for reproduction is...

**Comment by reyaz006** [comment]
v3 scheduler was enabled before the first step. I assumed it was included in the debug info.

**Comment by mikehardy** [comment]
Yep - we log it in debug info :-)

> Scheduler = std2

**Comment by reyaz006** [comment]
It seems that solves the problem. Also noticed that skipping a day does not increase the number of new words for next session, which might have been the major point in most complains.

Thanks!
