### ISSUE TITLE
Show a snackbar instead of a toast

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12552]
There is a list of actoins which show a toast but a snackbar should be shown 

Card browser -> select a card ->
- Reposition card
- Reschedule card
- Reset progress
- Change deck -> Create a new deck -> Created deck

Deck picker -> long tap on a deck ->
- Rename deck
- Create subdeck

Settings 
- Sync -> Force full sync -> OK
- About -> Copy debug info

_Originally posted by @criticalAY in https://github.com/ankidroid/Anki-Android/issues/12487#issuecomment-1255396087_

-----
AnkiDroid Version = 2.16alpha85
New schema = true
Scheduler = std3
DatabaseV2 Enabled = true

**Comment by pratyaksh1610** [comment]
I'll take this .

**Comment by jellybeansenjoyer** [comment]
I ll also like to take this

**Comment by pratyaksh1610** [comment]
@jellybeansenjoyer Currently I am addressing the first four, you can take the others if you want to.
Thanks.
