### ISSUE TITLE
[Bug] Incorrect statistics report for complete collection

### ISSUE THREAD

**Issue by heitorPB** [ankidroid/Anki-Android#12578]
###### Reproduction Steps

1. go to statistics
2. select "All Decks" and "deck life" for time
3. Check the average cards added by day and manually do the math with your total cards and days studied. They don't match.

###### Expected Result

In my case: ~4 new cards added per day

###### Actual Result

I have ~4k cards and I've being studying for ~1k days, this gives an average of ~4 new cards/day. AnkiDroid reports 93.7 new cards / day:

![photo_2022-10-04_11-34-46](https://user-images.githubusercontent.com/13461702/193852724-5be5c6b2-5c4c-4d46-859d-3b172248e9f8.jpg)

###### Debug info
```
AnkiDroid Version = 2.15.6

Android Version = 9

Manufacturer = motorola

Model = moto e6s

Hardware = mt6765

Webview User Agent = Mozilla/5.0 (Linux; Android 9; moto e6s Build/POBS29.288-60-6-1-29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/85.0.4183.101 Mobile Safari/537.36

ACRA UUID = 6f60bdf2-e931-491d-b04a-0d7f0fb8d277

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hey there - this statistics page is going to be removed completely within short order - the new way to do statistics will be to use the AnkiDesktop code directly, and we have done so already -

1- grab the latest release: https://github.com/ankidroid/Anki-Android/releases
2- go to settings -> advanced and turn on the "new schema support"
3- examine the new statistics, they should look the same as Anki Desktop now, including with the much-requested-here heatmap!
