### ISSUE TITLE
[Bug] Anki app (newly installed) keeps crashing at login attempt

### ISSUE THREAD

**Issue by 7avocado** [ankidroid/Anki-Android#12583]
###### Reproduction Steps

1. Clicking on AnkiApp and entering AnkiApp login credentials
2. Hit Login
3. Get message 'loading data'. and crash.

###### Expected Result
login successful, using the app

###### Actual Result

 AnkiApp doesn't get past login screen and crashes instead. Next a pop-up display comes up that say "AnkiApp keeps stopping'. It gives options to get app info/close app/send feedback

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
I re-installed the app, same issue continues 

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
"AnkiApp" is not AnkiDroid

This: https://play.google.com/store/apps/details?id=com.ankiapp.client&hl=en_US&gl=US - is a poorly implemented clone made only to get money

you want AnkiDroid https://play.google.com/store/apps/details?id=com.ichi2.anki&hl=en&gl=US free forever and always has been, and *should not* crash, although the version in the play store has problems for some people. No worries though, you can grab the latest releases here where known crashes are fixed: https://github.com/ankidroid/Anki-Android/releases
