### ISSUE TITLE
Implement in AnkiDroid Card editor a search-bar with autocomplete

### ISSUE THREAD

**Issue by Yoannjap** [ankidroid/Anki-Android#12597]
I use AnkiDroid 90% of times (Anki desktop 10%) to edit or create my shared decks cards.
However, for very advanced decks, there are at least 50 different fields. I renamed each one well and with coherence in order to find them out more easily.
However scrolling over and over is a bit straining!

Indeed, implement in a next AnkiDroid version a search-bar letting search field names, and focusing the screen on results matching with what you typed, would be great!
With autocompletion would be best.

Yoannjap

**Comment by raehat** [comment]
There is already a search bar which does the job, I think what you want here is, that it should dynamically search field names while the user types, right?
Please someone correct me if I am wrong

**Comment by oakkitten** [comment]
The *editor* doesn't have a search bar.

I am a little curious about what a note with 50 field can look like. I can't imagine a scenario where it would be useful. Best I can do is fields with various dictionary indexes and other metadata, for searching, but this would be generated and not something one would want to edit. Might be a very edgy edge case?

**Comment by raehat** [comment]
Okay he was talking about the editor
well, a search bar can be implemented for sure
but again as @oakkitten said, quite an edgy edge case!

**Comment by raehat** [comment]
Please assign me this issue if it has to be done though!

**Comment by Yoannjap** [comment]
Thanks a lot raehat and oakkitten for your answers.

Indeed, a field search bar that filter fields displayed as you type text in it, doesn't exist in the editor and and would be extremely useful.

Creating and update a deck on Ankidroid, day after day, is not an edge case ;)
If you spend enough time voluntarily to create decks that you share with a lot of users, you theoretically have to respect things like adding licence sourcing for media used, for example. You can also create very good-looking and ergonomic cards tweaking CSS style, involving to separate infos into many fields.

As an example, I've created and enrich every day a French speaking—French Sign language deck.
Front gather several written words synonyms, example sentences, potentially a picture to illustrate the sense.
Back gather one or 2 French Sign Language very short video(s) of the matching sign, then the license and author sources.

Another example is [my French-English thematic deck](https://ankiweb.net/shared/info/2428949188) with words, example sentences, audio pronunciations, eventually pictures, etc. for each media with author and licence sources.

[Here is a short video](https://kdrive.infomaniak.com/app/drive/401725/redirect/122397) to figure out why an editor search-bar to filter fields titles would be so useful and time saving for big day-to-day editor like me.

Thanks if it can't be implemented easily :)

**Comment by raehat** [comment]
I am working on it

**Comment by Yoannjap** [comment]
> I am working on it
Thanks a lot for your help!

Available to test it when needed.

**Comment by raehat** [comment]
I have created a PR
@Yoannjap I can share apk with you if you want to test it

**Comment by oakkitten** [comment]
I can't open the infomaniak links, asks me to login.

Looking at Anglais — Français thématique, well, at least at from what I see on AnkiWeb, I'm not convinced. I would just use fewer fields. There are some fields that deserve being fields, such as pronunciation, but as for example sentences, images, etc, these things IMO are much more suitable for just being HTML.

Also, Anki doesn't support this.

Also, if there is a search functionality in the editor, I'd expect it to (primarily) search for field contents, not field labels. And, it would not filter, but highlight fields, and words and would allow jumping between them.

**Comment by raehat** [comment]
![image](https://user-images.githubusercontent.com/77321971/198675896-a88518b2-222b-4770-8b18-1e1a790bd887.png)
for now, I have added a simple searchview
it just iterates through field labels and filters them

**Comment by oakkitten** [comment]
That's not card editor though?

**Comment by raehat** [comment]
![WhatsApp Image 2022-10-28 at 9 13 54 PM](https://user-images.githubusercontent.com/77321971/198678573-dcc89bdd-586c-4d6d-9d9f-2443c827227b.jpeg)
this screen?

**Comment by Yoannjap** [comment]
> I have created a PR @Yoannjap I can share apk with you if you want to test it

Yes, I want to test it. Can you share it to me through Github or d'you need my email address?

**Comment by Yoannjap** [comment]
> I can't open the infomaniak links, asks me to login.
> 
> Looking at Anglais — Français thématique, well, at least at from what I see on AnkiWeb, I'm not convinced. I would just use fewer fields. There are some fields that deserve being fields, such as pronunciation, but as for example sentences, images, etc, these things IMO are much more suitable for just being HTML.
> 
> Also, Anki doesn't support this.
> 
> Also, if there is a search functionality in the editor, I'd expect it to (primarily) search for field contents, not field labels. And, it would not filter, but highlight fields, and words and would allow jumping between them.
> 
> P.S. I like the idea of keeping image copyrights along with the images, very cool! It don't see how it could be implemented given the current infrastructure though, if the images don't get their own fields.

Well, there could be 2 options box to check next to search bar:
• first box: search field label
• second box: search box content.

But whatever you say, managing a rich deck I'have been doing since 2010 requires at a moment multiple and multiple fields, to sort, edit, CSS-style, search, batch edit/replace fields content separately. I began with a few field, but as I enriched decks and made them a bit more 'pro', I needed 1 content = 1 field. At least that's my Anki deck création experience.

And for the Infomaniak share URL, try these new ones:
- [the screencast](https://kdrive.infomaniak.com/app/share/401725/47333d54-6cd0-414f-83e2-0922a3f7b039) 
- [the other one](https://kdrive.infomaniak.com/app/drive/401725/redirect/122397)

**Comment by raehat** [comment]
![image](https://user-images.githubusercontent.com/77321971/198708580-1ce615db-a5b2-4450-800f-c262ad47f4d7.png)
@Yoannjap you're asking changes in this screen, right?

**Comment by mikehardy** [comment]
Just post the PR, then who ever wants to test it pulls the PR (`gh pr checkout 12597` with https://github.com/cli/cli) and install it on your phone (`./gradlew installDebug` with your phone plugged in and developer mode enabled, or just an emulator running, perhaps)

**Comment by Yoannjap** [comment]
> ![image](https://user-images.githubusercontent.com/77321971/198708580-1ce615db-a5b2-4450-800f-c262ad47f4d7.png) @Yoannjap you're asking changes in this screen, right?

Yes, on this very screen.

**Comment by Yoannjap** [comment]
> ![image](https://user-images.githubusercontent.com/77321971/198708580-1ce615db-a5b2-4450-800f-c262ad47f4d7.png) @Yoannjap you're asking changes in this screen, right?

Yes, on this very screen.

**Comment by Yoannjap** [comment]
@mikehardy thanks for your answer,
But, well, I have never tested a PR before.
And not having any PC for my 2 weeks trip, but only Android (rooted) is there a way to test it directly from my Phone not using any PC?

**Comment by mikehardy** [comment]
> And not having any PC for my 2 weeks-trip, but only a smartphone with rooted Stock Android 12, is there a way to test it directly from my Phone not using any PC?

No, in that case, not without an APK

**Comment by raehat** [comment]
I will work on all the points mentioned and create a new PR in the next few days
@Yoannjap when I am done with it, I will share apk with you then you can test it

**Comment by Yoannjap** [comment]
> I will work on all the points mentioned and create a new PR in the next few days @Yoannjap when I am done with it, I will share apk with you then you can test it

Great, thanks a million for your help. I'll be there when needed for testing.

**Comment by raehat** [comment]
https://user-images.githubusercontent.com/77321971/199165462-b3710079-231e-4b43-b4e5-fa7f8e09d403.mp4

I have implemented this so far
I can share you the apk through email or medium of your choice for you to test it
Test it and let me know the changes

**Comment by Yoannjap** [comment]
Hey raehat,

I am so orry to answer only now to what seems, seeing your gif, to be a brilliant work you did to add the search bar!
But I had a huge week of work in my company :(

Well, if you have time, could you send me the apk at my email yoannjap at yahoo dot fr ?

I can test it this week, having myself more time to do.

Thanks again 👍

**Comment by Yoannjap** [comment]
> WhatsApp.Video.2022-11-01.at.10.57.44.AM.mp4
> 
> @Yoannjap I have implemented this so far I can share you the apk through email or medium of your choice for you to test it Test it and let me know the changes

Hi back raehat,

May I see and test your great work with an apk ?

My email address is on my reply above.

**Comment by Yoannjap** [comment]
Yes, of course, I am still searching someone who could help !

**Comment by raehat** [comment]
I have been working on this issue for a while
https://github.com/ankidroid/Anki-Android/pull/12773
look into this

**Comment by raehat** [comment]
Tell me how can we work together on this

**Comment by Yoannjap** [comment]
Hey raehat !

Great to read you again.
Yes, you did proposed a gif of your development.m that fitted exactly with a field search bar with aurocomplete in the card editor.

How we can work together on that? Well, as you proposed me before, if you still have the test-apk you've created, can you send it to me, then I can test it?

**Comment by raehat** [comment]
@Yoannjap The problem is what I showed in that old video was doable, but @oakkitten preferred a different approach with searching fields with highlights and option to iterate through fields using arrow buttons. I don't think I can implement that without recycler view, which is not used currently.
I don't know how to proceed without some input from others contributors on this.

**Comment by Yoannjap** [comment]
@raehat Ok, that would be a great news if someone can help to achieve it.
I don't know myself coding, but I can test it heavy if ever it can be done.

Anyone can help please?

PS: what's a recycler view?

**Comment by raehat** [comment]
Well, it's alright you don't have to understand the technicalities. What I'm trying to say is to implement it in the way @oakkitten mentioned, I need to implement recycler view I think, and it can be a big task so I don't want to proceed without any input from old contributors.

**Comment by raehat** [comment]
@Yoannjap you should ask for some old contributors so that they can help me here. I mean what you're saying can be done but again, need someone to mentor me here.
