### ISSUE TITLE
[Bug] "Card marked as leech" snackbar shows on top of answer buttons

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12606]
###### Reproduction Steps
1. Tap again during review so the card is marked as leech

###### Expected Result
The snackbar appears above answer buttons like other snackbars

###### Actual Result
The snackbar covers answer buttons

###### Debug info
AnkiDroid Version = 2.16alpha86

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = 6cf7bbad-e282-47db-ad26-f6170967fa55

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I wonder - since you're testing the new schema / v3 scheduler, if this is the new snackbar code from @oakkitten not hooked up with the new schema scheduler stuff. That is a poorly researched hunch, I don't have a solid backing but that's where I'd look first - new schema leech pathway, and how it does the snackbar vs places where snackbars correctly avoid UI items.

Can you specify a use case @pavreh where you generate a snackbar in the reviewer and it does avoid the buttons? Could be useful for comparison

**Comment by oakkitten** [comment]
You need to set an `anchorView` to make the snackbar appear above it, this is how reviewer does it:

https://github.com/ankidroid/Anki-Android/blob/0dd61d1e76ae7edf6766209d9415f27fe6703276/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L1795-L1811

`leech()` (awful name) doesn't do it

https://github.com/ankidroid/Anki-Android/blob/c1dfa70659385502e8b7e4bbdf14eeeb3e260b47/AnkiDroid/src/main/java/com/ichi2/libanki/sched/AbstractSched.kt#L204

Relevant commit: 03f98567

**Comment by pavreh** [comment]
Sure, e.g. Bury card, Suspend card, Delete note and Undo in the reviewer show snackbar above the button.
![Screenshot_20221009-195416_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/194772343-214f5fb2-b233-473d-b25f-d8e7e0a8f023.png)
There is a picture for leech below
![Screenshot_20221009-195616_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/194772408-8958af31-27a8-4d16-8c0d-60d455f30b94.png)

**Comment by yellowjello** [comment]
Can this issue be reopened? I would like to work on it.

**Comment by david-allison** [comment]
Thanks!!!
