### ISSUE TITLE
[Bug] day/night mode is not switched when AnkiDroid closed by the back button

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12617]
_Originally posted by @pavreh in https://github.com/ankidroid/Anki-Android/issues/11982#issuecomment-1228052632_

###### Reproduction Steps
Does not matter if the new schema or legacy schema.
1. have day mode in the mobile
2. in Ankidroid, settings - appearance - theme - follow system 
3. tap back to close Ankidroid
4. switch night mode on in the mobile
5. open Ankidroid

###### Expected Result
AnkiDroid is in night mode

###### Actual Result
Night mode is not switched. When I use the home button instead of the back button, night mode works.

###### Debug info
AnkiDroid Version = 2.16alpha86

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = 6cf7bbad-e282-47db-ad26-f6170967fa55

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by jeremyxarcher** [comment]
Hi, I've created a PR here :) https://github.com/ankidroid/Anki-Android/pull/12697
