### ISSUE TITLE
[Bug] Can't change deck "Options group"

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#12622]
###### Reproduction Steps

1. Using beta86 with new backend
2. Long press on deck and select 'Deck Options'
3. Click 'Options Group'
4. Select new group

###### Expected Result

Window closes, deck is changed to selected group.

###### Actual Result

Window closes, there's a brief flicker of what might be another window briefly appearing and closing, and deck is not changed.

###### Debug info
```
AnkiDroid Version = 2.16alpha86

Android Version = 12

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = f9d003f3-ae34-4529-8cd5-ed8aff42fa30

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by rawrins** [comment]
It happens on the old backend as well
