### ISSUE TITLE
[Feature request] Add support for the custom study feature recently implemented into Anki (2.1.55)

### ISSUE THREAD

**Issue by Vitorvlv** [ankidroid/Anki-Android#12620]
Hi! I'm wondering if the latest alphas support the CustomData feature recently implemented in Anki.

It's needed to experiment with a new custom scheduler going around lately.

https://github.com/ankitects/anki/issues/2039
https://github.com/ankitects/anki/pull/2040
https://forums.ankiweb.net/t/some-problems-in-implementing-a-state-of-the-art-srs-scheduler-on-anki/22705/5
https://www.reddit.com/r/Anki/comments/x9jjcx/implement_a_new_spaced_repetition_algorithm_based/inpm44b/

**Comment by dae** [comment]
The whole custom study feature is not supported yet.

**Comment by Vitorvlv** [comment]
I see, I guess I'll leave this open as a feature request then, thank you!!

**Comment by dae** [comment]
It will require:

- loading review_extras.js from the desktop code into the webview
- switching from the 'card' property in AbstractSched to instead storing the current card state and next states inside the reviewer
- evaluating the provided javascript after the question is shown
- displaying the answer buttons based on the stored/mutated state, instead of via the method in AbstractSched

See V3CardInfo in reviewer.py and the code in mediasrv.py for more

**Comment by Vitorvlv** [comment]
go away bot

**Comment by L-M-Sherlock** [comment]
Two months on, Anki for PC 2.1.55 stable has been released and I wonder if this feature will be supported in AnkiDroid 2.16?

**Comment by galantra** [comment]
https://github.com/open-spaced-repetition/fsrs4anki/issues/107#issue-1508088316

> So, I can tell you. customData is a field specific to scheduler v3. We don’t support it. And sadly, we don’t even have an idea of when we’ll actually support it, because Android Play store does not allow us to update the app until we make some complex changes.

Upon reading this, I was not sure whether

1. there is a technical obstacle in Play Store that prevents the use of customData, or
2. there are more pressing issues than customData (, which are related to the Play Store).

If the technical obstacle is the case, perhaps customData could already be included in Github and/or F-Droid (pre-)releases.

I have searched through the issues. Probably this is meant? https://github.com/ankidroid/Anki-Android/issues/9259

**Comment by BrayanDSO** [comment]
In a nutshell,
- AnkiDroid can't be updated because of #5304
- The v3 scheduler implementation is a WIP, so customData is too

**Comment by Arthur-Milchior** [comment]
@L-M-Sherlock I don’t know how much you can infer from Brayan’s statement regarding your specific question.
No, it quite probably won’t be available in 2.16. That is not a priority. The only thing that is needed for 2.16 is the storage permission. Once we have it and are confident in it, we release it.
All contributors are volunteers, and one can decide that it is their priority. But as far as I know, nobody decided to start working on it. But I’d be surprised if it is deemed stable enough that we are confident to release it outside of the advanced settings.

**Comment by mikehardy** [comment]
Not disagreeing with anything from Brayan or Arthur - on the contrary their statements are all correct - just chiming in to say I would welcome this as a contribution and all of our infrastructure work to support 2.1.55 desktop release + to support javascript programming APIs etc etc is all aimed at making things like this *possible*. But it will need someone with motivation to adopt it as a feature they will work on (as Arthur mentioned - likely behind an advanced toggle at first, or something similar that makes sure it won't destabilize the non-custom-scheduling code paths)

**Comment by doctorman** [comment]
> Not disagreeing with anything from Brayan or Arthur - on the contrary their statements are all correct - just chiming in to say I would welcome this as a contribution and all of our infrastructure work to support 2.1.55 desktop release + to support javascript programming APIs etc etc is all aimed at making things like this _possible_. But it will need someone with motivation to adopt it as a feature they will work on (as Arthur mentioned - likely behind an advanced toggle at first, or something similar that makes sure it won't destabilize the non-custom-scheduling code paths)

Do you recomend enabling the v3 scheduling on desktop or does it cause issue with the current play store version or even with the alpha builds?  as a beta option which alpha is the most stable? the latest one?

**Comment by Ceynou** [comment]
Not sure if I understood correctly but if customData is ever supported it would be nice to have it start running before rendering the card so the template can depend on customData value, I have this variable and the card display one thing or the other depending on its value
```js
globalThis.intervalTest = states.current.normal.review.elapsedDays || 0;
```
It might already be working correctly but the template is displaying both f1 and f2
```html
<script>
  qFade = 0; //make it so the card appears immediately instead of fading in
	f1 = document.getElementById("field1");
	f2 = document.getElementById("field2");
	if (globalThis.intervalTest < 10){
		f1.style.display = "None";
	} else {
		f2.style.display = "None";
	}
</script>

<div id="field1">
thing one
</div>

<div id="field2">
thing two
</div>

```

**Comment by L-M-Sherlock** [comment]
Congratulations for the release of 2.16! I notice that the change log said that "We include anki 2.1.61 now, we’re fully up to date!" Does it mean CustomData feature has been implemented in 2.16?

**Comment by user1823** [comment]
> Does it mean CustomData feature has been implemented in 2.16?

No. The custom scheduling feature is not implemented yet. I think that they plan to release it with 2.17.

> "We include anki 2.1.61 now, we’re fully up to date!"

In my opinion, this part of the changelog is misleading. There are several features where AnkiDroid lags behind Anki.

**Comment by xificurC** [comment]
The commit closing this says "enables FSRS". I'm lost in the details here.

- this issue is about a customdata feature, which IIUC allows using custom SRS schedulers in anki
- FSRS is a new open source SRS algorithm
- there are [FSRS anki addons](https://github.com/open-spaced-repetition/fsrs4anki) one can use on desktop

If one wants to test the FSRS algorithm in AnkiDroid, where do we stand on this? Or is FSRS included in the latest release?

**Comment by Arbitrate3280** [comment]
It has been introduced in this commit: https://github.com/ankidroid/Anki-Android/pull/14171

No new release has been made yet that contains this change. The next time a release is made, it will have it.
