### ISSUE TITLE
Change ACRA toastText init to a ToastType enum style

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12631]
> future cleanup (for a follow-up): can toastText be moved to ToastType enum (containing the R.string), and actually get the string here to ensure we handle translations in the same way?

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/10627#discussion_r861050941_

**Comment by indyfromoz** [comment]
Hi @mikehardy 

I would love to work on this, could you please assign this issue to me?

**Comment by david-allison** [comment]
Sounds good to me, thanks!

**Comment by indyfromoz** [comment]
Hi @david-allison, I have finished working on the issue and have a branch ready for a PR. Will you please consider adding a `hacktoberfest` label to the issue? This will help with my Hacktoberfest 2022 submissions.
