### ISSUE TITLE
Enhance ACRA string handling to switch languages when user switches

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12632]
Currently ACRA initializes with user language correctly on startup, but if the user switches language you have to restart the app before ACRA's toast and dialog switch languages

Here is the FIXME I left:

```
        // FIXME ACRA needs to reinitialize after language is changed, but with the new language
        //   this is difficult because the Application (AnkiDroidApp) does not change it's baseContext
        //   perhaps a solution could be to change AnkiDroidApp to have a context wrapper that it sets
        //   as baseContext, and that wrapper allows a resources/configuration update, then
        //   in GeneralSettingsFragment for the language dialog change listener, the context wrapper
        //   could be updated directly with the new locale code so that calling getString on would fetch
        //   the new language string ?
```

Here is the related comment:

> I was unable to quickly fix this, the Application context is never updated with the system language, the only way Activities update is that they recreate themselves. I left a big comment instead that we should peel to another issue, with a maybe-useful solution sketch of having the base contexts be wrappers that allow resources/configuration updates post-hoc on language change events vs having them be frozen post-attachBaseContext

I'll have to peel it to another issue in order to get this update in so the PR doesn't decay any more

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/10627#discussion_r991688317_

**Comment by mikehardy** [comment]
Not sure this is a good issue or not, the handling of contexts and the resource configurations etc seemed pretty subtle to me, but perhaps I was missing an easy solution.

**Comment by oakkitten** [comment]
I mean, this affects the entire app, to make it reflect language changes you have to restart it. (Did I mention manual dealing with configuration changes? 😛)
