### ISSUE TITLE
Implement an android sync provider

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1267]
Originally reported on Google Code with ID 364

```
It would be nice to use Android's native sync provider framework, which would give us
automatic background syncing / scheduling for free, among other things.


```

Reported by `jan.berkel` on 2011-01-29 11:55:46

**Comment by mikehardy** [comment]
https://developer.android.com/training/sync-adapters/

Could be interesting in the context of #2982 where if AnkiDroid was mostly just the "system of record" / database for the facts and reviews but actual review and note edit was done elsewhere, we still kept things in sync well for users by allowing them to schedule it, or use the sync adapter hook for content providers to request a sync on some content provider condition

**Comment by david-allison-1** [comment]
Anki Desktop now uses background sync for media, and we're worrying people with really heavy decks due to long media syncs

**Comment by adamwolf** [comment]
I have a fair amount of experience with Android's native sync framework.  I do not recommend it in 2020, and am working on migrating a few apps away from it.

For instance, if you have under 10% of free space, it silently refuses to sync.  This means some phones need 5 or 10 gigs free to sync, even if the app only needs a few kilobytes.

**Comment by mikehardy** [comment]
that sounds....terrible. Thank you for sharing!
Not to say we can't do a persistent notification and "background download" but "silent refusal" to do anything is going to be a support disaster

**Comment by adamwolf** [comment]
It is a support disaster in the other app I maintain.

I actually see Google has a big thing aiming you away from Sync Adapters in
their docs now :)

https://developer.android.com/training/sync-adapters

**Comment by dae** [comment]
Impractical with the new backend in any case - closing.
