### ISSUE TITLE
changelog for betas

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#12688]
Would it be possible to have small changelog between betas?

Thanks!

**Comment by voidplayer** [comment]
Yes, i meant alphas :laughing: 

I was asking for small changelogs for alphas

Reading pull request is too much since you guys merge nonstop (what does NF mean?)

Maybe a few lines with the important changes so we know what are we upgrading when we installa a new alpha? :angel:

**Comment by mikehardy** [comment]
NF means non-functional, there will be no available time to produce an alpha changelog, apologies - the "merging non-stop" is the priority and it takes all available time, non to spare for changelogs at the moment

Ideally we'd use conventional commits and generate them automagically but that is a bigger change and not contemplated at the moment

Sorry :sweat_smile: - as always though I definitely appreciate the testing

**Comment by voidplayer** [comment]
Yeah, understandable

I hope that focusing on finishing the work ahead is worth not focusing on bringing people along with you even if it takes a little longer to finish

[Quoting a recent post of google engineers](https://cloud.google.com/blog/topics/developers-practitioners/how-google-got-to-rolling-linux-releases-for-desktops)
> "Our journey has ultimately reinforced our belief that incremental changes are better manageable than big bang releases."

I will keep myself for updating any further too tho :sweat_smile:

As always thanks for the work! (and i really mean it! I use it daily!)

Ill probably start testing again when i have more time

**Comment by mikehardy** [comment]
Prior to being blocked by scoped storage migration I was averaging one new public release every 6 weeks. I believe strongly in incremental change

Scoped storage, from the perspective of release management, has basically been a disaster. Big bang releases are terrible, and we're about to have one.
