### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by foldfield** [ankidroid/Anki-Android#12699]
###### Reproduction Steps

1. \(\underline{V}\\)
2. \(\underline{v}\\)

###### Expected Result
for both of the lines to be able to display an underlined V and an underlined v

###### Actual Result
the capital V doesn't render as underlined but the lowercase does. In fact, any capital letter isn't underlined, but lowercase is

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 13

Manufacturer = Google

Model = Pixel 5

Hardware = redfin

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 5 Build/TP1A.221005.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = 8aded4e7-7dbe-4542-97cc-bbcdc5d894ae

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hey there! Can you try this with the latest alphas, there has been quite a bit of work on mathjax if I recall - https://github.com/ankidroid/Anki-Android/releases

**Comment by foldfield** [comment]
Yes the issue is sorted on the alpha! Many thanks :)

**Comment by mikehardy** [comment]
Glad to hear it - thanks for reporting back
