### ISSUE TITLE
paste images by sharing to ankidroid

### ISSUE THREAD

**Issue by NameLessGO** [ankidroid/Anki-Android#12692]
**Is your feature request related to a problem? Please describe.**
Trying to make cards on PDF, but cant seem to paste images in ankidroid, using samsung notes since it was the only pdf viewer that was able to copy and share images, but there isn’t an option to paste nor share on ankidroid

**Describe the solution you'd like**
I cant tell which format samsung notes uses so that ankidroid can recognizes the pasted images, so was thinking in creating a field that lets u share images to anki, lets say you are interested in adding an image to a field called “images”, you find an image on PDF or in a Google search, then you share to anki, in which will open a “add card” tab and post the image in the field “images"

**Describe alternatives you've considered**
currently trying alternatives to samsung notes to copy and paste images in a way ankidroid understand, or any alternatives that improves workflow

**Comment by BrayanDSO** [comment]
I like the idea

**Comment by liutng** [comment]
I'd like to work on this. Can I have this?

**Comment by david-allison** [comment]
@NameLessGO this should be fixed in https://github.com/ankidroid/Anki-Android/pull/15264 (both image occlusion and creating a note from an image)

If not, please let me know

* https://github.com/ankidroid/Anki-Android/pull/15264
