### ISSUE TITLE
How do I add the "needs review" label to a PR?

### ISSUE THREAD

**Issue by jeremyxarcher** [ankidroid/Anki-Android#12716]

**Comment by criticalAY** [comment]
This is not an issue I guess but okay you can't unless you have access?

**Comment by jeremyxarcher** [comment]
Yeah I didn't know where else to ask to be honest. Seems like other contributors add it to their PRs, didn't know if I needed to do so to get mine looked at!

**Comment by criticalAY** [comment]
Contributors can't really put that on there like on their own PRs. and we have a discord channel I hope you know.

**Comment by jeremyxarcher** [comment]
Oh, no I didn't know about the discord! Thanks for letting me know, this is the first time I'm trying to contribute to something so I'm a little new at this. Thanks for your help, see you in the discord!

**Comment by criticalAY** [comment]
Plus there are other priorities right now so we got to be a little more patient thanks!

**Comment by jeremyxarcher** [comment]
Of course. I'm not trying to rush anyone, I just want to make sure I'm doing things right. Where is the link to the discord btw?

**Comment by criticalAY** [comment]
> Of course. I'm not trying to rush anyone, I just want to make sure I'm doing things right. Where is the link to the discord btw?

you can find it on the main page but okay https://discord.gg/emtzJAZn there you go

**Comment by jeremyxarcher** [comment]
Thanks a lot man. I'm an idiot I cmd+f for discord and of course it's an icon :|
