### ISSUE TITLE
[Bug] After just exporting a single note, "Collection exported" message gets shown

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#12713]
###### Reproduction Steps

1. "Settings"->"Advanced" -> Enable "Use the new backend"
2. Tap "Card browser"
3. Long press a row  of the list of cards/notes (then, the row gets selected)
4. Tap the three dot icon --> Tap "Export cards" / "Export notes" --> Tap "OK"

###### Expected Result
Some message like "_Card_ exported" / "_Note_ exported" gets shown as on Anki Desktop ("n cards exported." / "1 card exported.")

![image](https://user-images.githubusercontent.com/10436072/197097291-8f28efb5-52e3-4634-8271-194d0f173a98.png)

###### Actual Result
The dialog box titled "_Collection_ exported successfully" gets shown.
![image](https://user-images.githubusercontent.com/10436072/197098234-390b6e32-4fb4-4fc2-9575-1f9bf454d98a.png)
'[Collection](https://docs.ankiweb.net/getting-started.html?highlight=collection#collection)' is all the material stored in Anki – your cards, notes, decks, note types, deck options, and so on, so the word doesn't seem to fit this situation.
###### Debug info
```
AnkiDroid Version = 2.16alpha88

Android Version = 11

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/105.0.5195.136 Mobile Safari/537.36

ACRA UUID = 8d368aeb-897f-40c1-bd7c-b18afe12a517

New schema = true

Scheduler = std3

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```
###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)), so it doesn't seem to fit this situation.

**Comment by arjundevasi** [comment]
Hi, I would like to contribute on the issue.

**Comment by snowtimeglass** [comment]
@arjundevasi thanks!

**Comment by arjundevasi** [comment]
I can't find the export button

![Screenshot_20221022-082408.png](https://user-images.githubusercontent.com/27912546/197316023-674f1e74-e913-4cb2-82c8-8fdabdb67e32.png)

**Comment by snowtimeglass** [comment]
Ah, sorry. The feature was probably added after 2.16alpha88 was released. I found this issue on a debug.apk which I build after the feature was added.

**Comment by snowtimeglass** [comment]
> I can't find the export button

@arjundevasi If you can't find the export button on 2.16alpha92, either, "Settings"->"Advanced" -> Enable "Use the new backend" and check again please. I've updated the reproduction steps above.

**Comment by david-allison** [comment]
A number of refactorings in the following make this change easier:

- https://github.com/ankidroid/Anki-Android/pull/13316

**Comment by snowtimeglass** [comment]
Thank you for the work and the notification!

**Comment by david-allison** [comment]
Very welcome! Ping me after the change is merged and I'll get this one done

**Comment by BrayanDSO** [comment]
> Ping me after the change is merged and I'll get this one done

@david-allison

**Comment by snowtimeglass** [comment]
>Ping me after the change is merged and I'll get this one done

Apologies for the lack of response. To be honest, I didn't (and still don't) get what "the change" means in this case and thought about it for a while, but eventually I missed to ask a question. I should have done it.

I am now considering an approach of changing the title itself to a completely different one, rather than creating several similar patterns based on the current title. So, I may possibly submit another issue or PR related to this issue.

**Comment by snowtimeglass** [comment]
Fixed in https://github.com/ankidroid/Anki-Android/pull/14059
