### ISSUE TITLE
Image occlusion enhanced images cant be opened on ankidroid

### ISSUE THREAD

**Issue by sugar42** [ankidroid/Anki-Android#12721]
Hi, 
i have a problem with opening images on my ankidroid. 
I can access and open the images on Ankiweb but on my phone it isnt possible. 
![14wdbfk3xqu91](https://user-images.githubusercontent.com/56407539/197482512-ff43a733-4604-412a-a2a1-6893b664fa31.jpg)

I found out, that the images are saved as JPEG files on my machine but saved as svg files in the ankidroid app. 

Please can someone help me? :)

**Comment by criticalAY** [comment]
are the images 1MB> ?

**Comment by criticalAY** [comment]
I am not able to reproduce this issue. Works fine on my end

**Comment by justdvnsh** [comment]
Cannot reproduce as well. Works fine. 

![Screenshot 2022-11-24 at 1 16 24 AM](https://user-images.githubusercontent.com/29144058/203633866-12a99ced-b933-404f-a14e-f7b509d8c014.png)
