### ISSUE TITLE
[Bug] Changelog style applies to Open Collective if opened via link click

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#12720]
###### Reproduction Steps

1. About -> Changelog -> Stable Changelog -> "Thank you" link to Open Collective
2. OC opens in the WebView

###### Expected Result

Either:

* Open Collective opens in a 'Chrome' browser window
* Styles are unchanged

###### Actual Result

* Open Collective appears with colored links from the CSS
<img width="401" alt="Screenshot 2022-10-23 at 13 28 23" src="https://user-images.githubusercontent.com/62114487/197392122-d66e09ab-c3a9-47c3-b2b7-90ae6674d076.png">

###### Debug info

AnkiDroid Version = 2.16alpha88

Android Version = 12

Manufacturer = unknown

Model = Android SDK built for arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; Android SDK built for arm64 Build/SE1A.220621.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = 319004e4-1ceb-4aa1-867a-afe72be08340

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Hey! So we want this to be opening in chrome ?

**Comment by ShridharGoel** [comment]
@criticalAY Either of the two things mentioned by @david-allison would work. Are you picking this task?

**Comment by criticalAY** [comment]
> @criticalAY Either of the two things mentioned by @david-allison would work. Are you picking this task?

yeah sure I'll work on it it just happened to slip out of my mind because of the festive break

**Comment by ShridharGoel** [comment]
> yeah sure I'll work on it it just happened to slip out of my mind because of the festive break

There's no hurry, I was just asking for info. Assigning the issue to you.

**Comment by criticalAY** [comment]
Have done few changes so the OC link opens up in the browser rather than the webview

**Comment by criticalAY** [comment]
Should we do the same for the development link also I have put a condition so that the development link opens in Webview itself ?

**Comment by criticalAY** [comment]
Hey!

**Comment by criticalAY** [comment]
@david-allison reopen this one please
