### ISSUE TITLE
[Bug] can't send report 

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12733]
###### Reproduction Steps

open Help -> Get Help -> Send Troubleshooting report 

###### Expected Result
Sending a report dialog box show

###### Actual Result
nothing is happening

###### Debug info
AnkiDroid Version = 2.16alpha88

Android Version = 12

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.220630.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = 246da304-f39d-4cd2-9fc7-d1bc0bd83ad0

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
> Crash Reports Enabled = false

You'll have to follow the guide to test things well, in debug builds they are disabled by default:

https://github.com/ankidroid/Anki-Android/wiki/Crash-Reports#steps-to-test

**Comment by criticalAY** [comment]
oops! sorry

**Comment by criticalAY** [comment]
but can't we display some toast/snackback ? like it's disabled ?
