### ISSUE TITLE
[Bug] By sort field order does not work when browser notes

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12742]
###### Reproduction Steps
1. Create a few basic cards but not alphabetically, e.g. 2, 4, 6, 1, 3, 5
2. Card browser, change display order, by sort field and set browser options to "cards". You can see the cards in alphabetical order (1, 2, 3, 4, 5, 6).
3. Change browser options to "notes".

###### Expected Result
Cards are in alphabetical order

###### Actual Result
Cards are in order as added
![Screenshot_20221029-104749_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/198822685-c15d06b9-e07d-4130-bebd-1c4750bbf44f.png)

###### Debug info
AnkiDroid Version = 2.16alpha88

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 6e947d7c-0fbc-4a5c-805f-d612c7208dc1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pavreh** [comment]
Other types of sorting does not work too when browser options are set to "notes".

**Comment by Jack8861** [comment]
Is this by any chance a good first issue? 
If no one is interested i would love to look into it.

**Comment by constructor-s** [comment]
I have a similar issue. 

I have three cards, `A01, A02, A10`, it would sort it as `A01, A10, A02`, as if just ignoring the leading zeros. I specifically put in the leading zero to make sure it sorts correctly (which it does on desktop).

**Comment by pavreh** [comment]
@constructor-s Sorting works for me in 2.17alpha9. A01, A02, A10 as expected. Display order is set to "by sort field".

**Comment by david-allison** [comment]
* Fixed in https://github.com/ankidroid/Anki-Android/pull/14859
