### ISSUE TITLE
[Bug] Run out of space not using SD card

### ISSUE THREAD

**Issue by KeithSware** [ankidroid/Anki-Android#12752]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
We do not officially support sdcards, and cannot for many reasons. There is a FAQ with more information on the same: https://github.com/ankidroid/Anki-Android/wiki/FAQ#my-ankidroid-files-are-stored-on-a-sd-card-how-can-i-point-ankidroid-to-them

**Comment by KeithSware** [comment]
New install to Android. I went into ANDROID settings and changed the storage to use the SD card because there is limited space available on the main phone card. 1st time user and 1st time I used the Anki phone app. The first thing I wanted to do was run sync because there were several decks installed on the windows10 Anki program. While the android app was running sync, it ran out of space, popped up an error message, I selected continue and the Anki phone app then popped out of existence (i.e. it died). on windows, I looked at the phone storage and I noticed that the SD card was not not not being used, all storage was on the main phone card. This is the problem because I had set the android settings to use the SD card and the Anki program was failing to use any part of the SD card. I will log on from the PC and provide some screen shots later when I've had some food.

**Comment by KeithSware** [comment]
Question Why is some fool closing this issue before I have even started it?

**Comment by mikehardy** [comment]
I explained our position and linked the documentation.
I'm the primary maintainer here and have been for years.
I will say this one time and one time only: if you continue being rude I will delete this and report you for disruptive content.

**Comment by KeithSware** [comment]
If you want to delete the issue, then go right ahead.

 

If you want someone to invest 2/3 hours of their own valuable time documenting an issue and providing technical evidence and screen shots in order to assist you in improving your project outputs…

 

Then those words that you write in that previous email are the wrong approach.

 

I get that you are a little upset, and that open source projects are a gift to the community.

 

None the less, when someone embarks on documenting a bug in a program; this is their time and their gift to the community.

 

However that gift is apparently packaged, that comes your way, nice or horrible, fare or bad, …  it matters not, if it gets the job done and an improvement gets out the door that benefits the community.

 

On the other side of the table

 

If the bug report is closed down, before they have had a chance to create the documentation describing the bug, then they are going to be upset.

 

The speed at which the bug was closed was unusual.

 

It is still, none the less, their effort and mental creativity, that they are also giving up for the community in order to highlight a problem that appeared unexpectedly.

 

The point is, that good will has to go in both directions, otherwise the result will always be human nature.

 

One other point

In a previous email, you state [[[We do not officially support sdcards]]]. If this is the case, then your phone app is incorrectly configured because its configurations (see screen shot) does allow the user to change the storage setting.

What I see is that the program is failing to use storage on the SD card. This is in spite of the fact that I went into settings and changed the storage to use the SD card.

If a program is put out into the public arena, then it should operate without trauma to the user. I don’t see, that it is beyond the wit of a programmer, to ensure that any path settings, in any software variables, do allow for access to an SD card. But perhaps that is too much of a technical challenge, who knows.

 

See pics, I’ve attached the log file to this email.

 

I’m in the middle of a 10 hour work day, so I’ll leave this with you to choose, if you want this to be the end of the road.

  

 

Contact details   |   Creativity seeds Inspiration
========================
Keith Leggett ( KeithSware )  LinkedIn

Security Clearance: ISC cleared Jul-2008, SC cleared on May-2004 & Sep-2003
Email : ***@***.***
Mobile: +44 (0)7913 797 971

LinkedIn: https://uk.linkedin.com/in/keithsware 

Ww: https://keithsware.wordpress.com <https://keithsware.wordpress.com/>  

Cars Exposed: https://www.youtube.com/channel/UCRfF_E-wrIEzIxJNQL1SMcQ 

 

Past locations: Britain, Amsterdam, Jersey, London, Frankfurt, Edinburgh, Fiji, New Zealand

Flexible within the European Union
Please note: I only take on work that is non weapons related roles.
[30 plus projects completed in different software languages and technologies]
==================

Please consider the environment before printing this e-mail

Special Note:
=============
To decompress ZIP files go to www.winzip.com <http://www.winzip.com/> 
where it's possible to download the free evaluation copy of winzip.exe
 <http://grants.nih.gov/grants/edocs.htm> http://grants.nih.gov/grants/edocs.htm
 <http://www.dummies.com/how-to/content/compressing-files-to-ease-emailing.html> http://www.dummies.com/how-to/content/compressing-files-to-ease-emailing.html
 <http://www.computerhope.com/jargon/c/compfile.htm> http://www.computerhope.com/jargon/c/compfile.htm
