### ISSUE TITLE
[Bug] Old deck options in the new backend

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12761]
###### Reproduction Steps
1. Long tap to a deck
2. Deck options (there are the new deck options from the new backend)
3. Tap back and tap the numbers next to a deck title to enter the deck overview
4. Deck options

###### Expected Result
The new backend deck options are shown

###### Actual Result
The old backend deck options are shown

###### Debug info
AnkiDroid Version = 2.16alpha89

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 6e947d7c-0fbc-4a5c-805f-d612c7208dc1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Huh, it was working on my branch before the merge. 

Gonna need a bisect of these commits: https://github.com/BrayanDSO/Anki-Android/compare/main...ankidroid:Anki-Android:main

**Comment by BrayanDSO** [comment]
Bad cache messed up my builds. 

Now that I've fixed it, can't reproduce on cb3cfcead55fd86ee5a5944c19fdbb63618bb18b

**Comment by pavreh** [comment]
AnkiDroid 2.16alpha90. I deleted data of the app and reinstalled the app. I still can reproduce. See the video below. 
https://user-images.githubusercontent.com/10192661/202835701-ccd85bfe-b2b2-42c5-b954-9b18c79c8e29.mp4

**Comment by BrayanDSO** [comment]
The video helped a lot. Now I can reproduce. It's actually simple to fix this
