### ISSUE TITLE
[Bug] Second field cannot be added

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12760]
###### Reproduction Steps
1. Three dots in Deck picker
2. Manage note types
3. Select a note type
4. Add field - Enter a name - OK (the field is added)
5. Add field - Enter a name - OK

###### Expected Result
The second field is added

###### Actual Result
The second field is not added

###### Debug info
AnkiDroid Version = 2.16alpha89 

Android Version = 12 

Manufacturer = samsung 

Model = SM-A225F 

Hardware = mt6769t 

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36 

ACRA UUID = 6e947d7c-0fbc-4a5c-805f-d612c7208dc1 

New schema = true 

Scheduler = std3 

Crash Reports Enabled = true 

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
Interesting, I didn't manage to replicate the issue.
I have another PR to also use the backend for the note type fields but that is going to be available in the next alpha. I think that should fix issues like this.

**Comment by snowtimeglass** [comment]
pavreh or lukstbit or someone else, is this issue reproduced in version 2.17.6 or above in your device?
 
I have tried the steps, but still can't reproduce the issue in 2.17.6 in my device. After the steps, the second field is shown (added) in the field list properly, as well as the first field.

**Comment by pavreh** [comment]
Agree, I cannot reproduce in 2.18alpha6.
