### ISSUE TITLE
[Bug] "AnkiDroid isn't responding" error after media sync popup in v2.16alpha88

### ISSUE THREAD

**Issue by beirne** [ankidroid/Anki-Android#12769]
###### Reproduction Steps

1. In desktop Anki create some new notes with media. Mine have sound and images. My desktop is Anki for the Mac 2.1.54.
2. In AnkiDroid Settings->Sync enable "Fetch media on sync"
3. Do a sync in AnkiDroid

###### Expected Result
AnkiDroid will do the sync, with a popup from the app about syncing media. After that goes away the app should be usable without any interruptions.

###### Actual Result
The popup about syncing media came up and went away. The sound and image files came down, at least on the two cards I reviewed. The problem is that the system keeps producing a popup saying "AnkiDroid isn't responding" and giving me the choices to Close app or Wait. I kept selecting Wait and after 15-20 minutes it stopped appearing. The system popup appeared no matter which app I was in.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha88

Android Version = 13

Manufacturer = Google

Model = Pixel 6 Pro

Hardware = raven

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6 Pro Build/TP1A.221005.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 5f4f6209-d536-499c-ace9-fd2afc6febbb

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Thanks for logging this @beirne !
So it appears media sync *is* working, but the "ANR" (android term "App Not Responding") warning dialog is concerning.
To use v3 scheduler you must have new schema enabled so this is the new media sync dialog + code pathway

To confirm: you did not select "background" on the media sync dialog? Or did you? Curious how it "went away" - if it was really going away on it's own or if you tapped outside of it or backgrounded it directly

**Comment by beirne** [comment]
I didn't hit background on the media sync dialog. On the ANR, I might have tapped outside but don't think that made the difference.

This actually also happened the first time I installed it last week. In that case I did hit Close app in the ANR hoping it was a fluke or known. I didn't add new cards to the desktop until last night, so this hadn't come up again. I'lll be a proper alpha tester now.

I just did another sync without having added more media. The media sync popup quickly came and went and no ANRs. This is not a surprise but I figured I'd see. I'll try adding some cards after work and do the sync again and track things more carefully.

**Comment by beirne** [comment]
I just created a note on the desktop with an image and sound and it came down fine with out the ANR message. I'll add a bigger set of notes later on when I have more time.

**Comment by beirne** [comment]
I just created some more notes this evening and they synced fine. I'm not sure what was different last night.

**Comment by homocomputeris** [comment]
I also notice AnkiDroid freezing since alpha88, and Android suggests to kill it. It seems like stopping it and cleaning cache helps.

**Comment by mikehardy** [comment]
If you have any sort of exact steps to reproduce for this @homocomputeris that would be great

**Comment by homocomputeris** [comment]
Steps to reproduce:

1. Open AnkiDroid
2. Start sync
3. It shows the 'Syncing # changes, syncing # files' pop-up
4. The number of kB, files increases, and then stops
5. AnkiDroid freezes
6. Android's 'Kill app now? Or wait?' pop-up appears
7. If 'Wait', the screen goes fully black
8. Go to recent apps, kill Anki

```
AnkiDroid Version = 2.16alpha89

Android Version = 12

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; ONEPLUS A6003 Build/SQ3A.220705.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 6fbaaf7d-f70a-4c72-b1f3-87d4cdfc1ed5

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by homocomputeris** [comment]
It seems to have improved significantly in alpha 90

**Comment by beirne** [comment]
I've synced a number of times since opening the ticket and just did again after adding some cards with media. I haven't been able to reproduce the problem, either on alpha 88 or 90.

**Comment by kenrick95** [comment]
Hmm I start seeing this issue again. Seems like happening if there are significant amount of cards that need to be synced with remote. But if I managed to keep waiting till it finished, the next times won't trigger that Application isn't responding popup anymore...


AnkiDroid Version = 2.19alpha4 (a2a109caa87ccfd84d9f49ae3294749712961ac2)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G991B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-G991B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = 5c82c1cf-0d8d-496c-8024-778f46ed45fb

FSRS Enabled = true

Crash Reports Enabled = true

**Comment by kenrick95** [comment]
More info on this issue. Seems like the popup happened when my Internet connection (mobile data) is poor, leading to like connection time out. However before the connection time out error pop up appeared, this "AnkiDroid isn't responding" system popup will appear. When I turned off my mobile data and then turned on again, seems like the Internet connection got "reset" and the sync seems gone fine without the system popup anymore...

**Comment by kenrick95** [comment]
I didn't encounter this issue anymore in the past few months I guess we can close the issue?

**Comment by beirne** [comment]
> I didn't encounter this issue anymore in the past few months I guess we can close the issue?

Yes, I'll close it now. I haven't seen this happen in a long time.

**Comment by ZornHadNoChoice** [comment]
Hi. This bug has been bothering me for months now. I guess I have a really bad internet connection but Ankidroid should tell the system "please wait, I'm working here" or something like it.

```
AnkiDroid Version = 2.20.1 (e32a82c33646807ea19623c9c88be38965bc07e6)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = Xiaomi

Model = 23013PC75G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 23013PC75G Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/136.0.7103.60 Mobile Safari/537.36

ACRA UUID = 3792582f-98ac-430e-ae42-4ace0156bf29

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true```
