### ISSUE TITLE
[Bug] Migrate to scoped storage button appears but does nothing

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#12764]
I don't know if this is supposed to be hooked up yet or not, but I'm reporting it just in case it's supposed to be working now.

I upgraded from alpha88 to alpha89 and I didn't receive any messages asking me to migrate, but I do have a yellow "Migrate to scoped storage" button that does nothing when clicked. Logcat reports "AnkiDroid: DeckPicker:: migrate button pressed" but nothing else.

FWIW, my data was already manually configured to use scoped storage at:
"storage/emulated/0/Android/data/com.ichi2.anki.b/col"

###### Reproduction Steps

1. click Migrate to scoped storage

###### Expected Result

Data migrates to scoped storage.

###### Actual Result

Nothing.

###### Debug info
```
AnkiDroid Version = 2.16alpha89

Android Version = 12

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = f9d003f3-ae34-4529-8cd5-ed8aff42fa30

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Interesting! If you were already configured to use scoped storage, I'm not sure that icon should appear.
It is definitely true that we (I, really) merged it as a "building block" so that it was available but most of the scoped storage migration building blocks exist like this: they exist but are not quite connected yet. That should come soon.

So this may or may not be a bug or just a partial feature at the moment. Fine leaving it open until clicking on the button actually kicks off the migration, it will serve as a nice thing to watch for when that happens.

**Comment by criticalAY** [comment]
I noticed too but left that because of the ongoing changes and also was working on a crash fix but he is right it is like that

**Comment by oakkitten** [comment]
Might be related to the fact that `/storage/emulated/0/Android/data/com.ichi2.anki.b/` is not something that you can directly get via API, and probably not a place you should put files in. [This method](https://github.com/ankidroid/Anki-Android/blob/046efd115e0a61c96c7bd405f043cfc69006e44f/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/ScopedStorageService.kt#L234-L259), which is like super hard to read, seems to be only examining data directory and external files directories, the latter usually being `/storage/emulated/0/Android/data/com.ichi2.anki.b/files`.

I needed something like that for my manage space activity PR and I came up [with this](https://github.com/ankidroid/Anki-Android/blob/3fe4a39e180832a5745f8c7ff0467cf9d73cec7b/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/managespace/FileUtils.kt#L57-L102). It would handle `/storage/emulated/0/Android/data/com.ichi2.anki.b/col` correctly

**Comment by Arthur-Milchior** [comment]
For the record, it is normal that the button does nothing right now. As far as I know, the migration service is still not implemented. 
On the other hand, it's clearly not normal that you see it if you're under scoped storage, so thank you very much for letting us know.

**Comment by Arthur-Milchior** [comment]
Also @doozan, since you already know how to use logcat. You should have a line starting with "isLegacyStorage(): current dir:", followed by two list of directories. It should appear when you open the deck picker. Can you please copy paste them here. (If you are not sure where to stop copying, just stop a few lines after "scoped internal dir:" and it should be fine.

**Comment by doozan** [comment]
Here are the related logcat entries:
```
AnkiDroid: isLegacyStorage(): current dir: storage/emulated/0/Android/data/com.ichi2.anki.b/col
AnkiDroid: scoped external dirs: /storage/emulated/0/Android/data/com.ichi2.anki.b/files, /storage/8152-1618/Android/data/com.ichi2.anki.b/files
AnkiDroid: scoped internal dir: /data/user/0/com.ichi2.anki.b/files
```
I moved the directory manually, following the directions in https://github.com/ankidroid/Anki-Android/issues/8925#issuecomment-976337268

Many thanks to everybody involved for making such a great app and for all the work related to the scoped storage migration.

**Comment by oakkitten** [comment]
> If you were already configured to use scoped storage, I'm not sure that icon should appear.

If this hasn't been fixed, it should be
