### ISSUE TITLE
[Bug] Report generated when cropping image and pressed back

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12768]
###### Reproduction Steps

1.  open a collection
2. edit note
3.  add a image
4. select image from gallery
5. press crop(do nothing after that)
6. press back

###### Expected Result
should get back to edit image section

###### Actual Result
crash report is generated

###### Debug info
AnkiDroid Version = 2.16alpha89

Android Version = 12

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.220630.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = 246da304-f39d-4cd2-9fc7-d1bc0bd83ad0

New schema = true

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
https://user-images.githubusercontent.com/48384865/199340409-a9377944-1227-48df-a37d-8eab89e67984.mp4

**Comment by pratyaksh1610** [comment]
It works fine on my end.

**Comment by mikehardy** [comment]
@pratyaksh1610 test results should include version or commit hash you are claiming results for, as well as execution environment (model of phone, version of Android)

**Comment by BrayanDSO** [comment]
Can't reproduce at cb3cfcead55fd86ee5a5944c19fdbb63618bb18b on my Android 12 Samsung Note10 Lite

**Comment by criticalAY** [comment]
I have reproduced this issue after your comment on OnePlus Nord CE again

**Comment by criticalAY** [comment]
Unable to share the clip because it's too large but here are the screenshots
![Screenshot_2022-11-03-07-44-01-33_a9eef3a2a561b80d5c76daebd0f9a14c.jpg](https://user-images.githubusercontent.com/48384865/199635829-67005da3-63d0-4ea6-8c83-f4612ca09eb0.jpg)![Screenshot_2022-11-03-07-44-04-11_a9eef3a2a561b80d5c76daebd0f9a14c.jpg](https://user-images.githubusercontent.com/48384865/199635836-4522112d-ced3-46d6-ab7a-be9d1d05c431.jpg)

**Comment by criticalAY** [comment]
@mikehardy Can we consider updating the library here to the latest version to fix this issue (probably it will be fixed as Canhub has fixed many exceptions in their latest version)

**Comment by mikehardy** [comment]
I don't see why there is a crash report but no stack trace? Crash reports have nearly zero value without the crash trace - they are only useful as a reminder to go get the crash trace as job 1

That said, I've updated the image cropper library in the latest dependency updates #12783

**Comment by criticalAY** [comment]
There is actually, I have marked them one with my username itself, Thanks though

**Comment by mikehardy** [comment]
I see no crash trace in this issue here

**Comment by criticalAY** [comment]
> I see no crash trace in this issue here

Yes, no crash just the report is getting generated
