### ISSUE TITLE
[Bug] Add note window doesn't indicate which fields are pinned when it 'remembers' the pinned fields from Desktop Anki

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#12770]
###### Reproduction Steps
1. Select add note option on Desktop Anki.
2. Pin one or more fields and create some notes.
3. Sync collection with AnkiDroid.
4. Open Add note window on AnkiDroid.

###### Expected Result
1. AnkiDroid (and Desktop Anki) remembers which fields were pinned.
2. The add note window indicates which fields are pinned (as it does when you click on the pin option).

###### Actual Result
Desktop Anki remembers as well as indicates the pinned fields.
However, AnkiDroid just remembers but does not indicate the pinned fields.

###### Debug info
AnkiDroid Version = 2.16alpha89

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.91 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there @user1823 ! You have not pasted the debug info from your install (I believe that was requested in the template, but it seems you have removed that part? :thinking: ) - that would be very helpful to know

Also, if you are not using the latest alphas when testing, you *may* want to try a parallel / test install to see if the issue still happens, there have been a lot of changes in the last year or so since we released 2.15 - https://github.com/ankidroid/Anki-Android/releases

**Comment by user1823** [comment]
Updated with debug info.

**Comment by oyeraghib** [comment]
I am gonna look into it, if no one has started yet!

**Comment by oyeraghib** [comment]
@user1823 Can you describe me the steps in Anki(Desktop) to see what fields are pinned when you add a note.

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by error96num** [comment]
I'm going to look into this issue🙋

**Comment by error96num** [comment]
I made a pull request for this issue.
https://github.com/ankidroid/Anki-Android/pull/13228
