### ISSUE TITLE
"SD card" used to mean "storage"

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#12777]
Let's not use `SD Card`, I don't believe this is accurate

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/12683#discussion_r1002538445_
      

Actually, there are other strings that seems problematic too. 
```xml
    <string name="backup_deck_no_space_left">Backup not saved. Not enough space left on SD card. Lower the backup depth or remove some other files.</string>
    <string name="sd_space_warning">Less than %d MB space on your SD card left.\nFree some space to avoid data loss.</string>
    <string name="sync_write_access_error">The downloaded file couldn’t be saved to the SD card. Either the card is mounted read-only or there isn’t enough space.</string>
    <string name="sd_card_full_title">SD card full</string>
    <string name="sd_card_almost_full_title">SD card almost full</string>
```

This issue is resolved when those five strings are rephrased in a way that does not refer to SD card. Ideally, we should just remain vague and and mention space without even trying to indicate to the user which storage we are referring to exactly.
Since those will be new string, they require new translation, so we should also change the key of all of those strings.

For the record, original issue considered three options:
* we create a new string key, to get them retranslated
* we correct in English but know it won't be corrected in other locales
* We don't do anything because it's really no big deal

And option 1 was selected, as seen below

**Comment by Subhadiptech** [comment]
Hey @Arthur-Milchior Can I work on this issue. I think I can solve this with some little guidance.

**Comment by Arthur-Milchior** [comment]
Hi @Subhadiptech,

I beg your pardon, but I don't understand your question. What work do you intent to do? or what guidance do you expect?
Because, right now, the main issue is not code. The main issue is deciding what we want to do. I made three suggestions, we need to decide between them
Personally, I don't have a strong preference any way. So the first thing is really to decide which solution we choose (or if we chose another one), and if we get a consensus on it

**Comment by Subhadiptech** [comment]
Ohh ya, My bad.

**Comment by mikehardy** [comment]
I think it is worth fixing it, I think it requires a new key, that is - option 1 is my preference

**Comment by Arthur-Milchior** [comment]
So, to be explicit, @Subhadiptech, I believe that now you can work on it. I edited the first message of the issue to indicate as clearly as possible what is expected. Don't hesitate to ask question on our discord if you need more guidance

**Comment by Subhadiptech** [comment]
Sure. Thanks. Will work on it.

**Comment by Subhadiptech** [comment]
@mikehardy  @Arthur-Milchior The issue is resolved and the link to the [https://github.com/ankidroid/Anki-Android/pull/12786](PR)

**Comment by Arthur-Milchior** [comment]
No need to ping us, well see it when we have time to review.

**Comment by lukstbit** [comment]
Done in #12786
