### ISSUE TITLE
[Bug] AnkiDroidJS.ankiGetCardFactor() and other functions always return 0

### ISSUE THREAD

**Issue by fylux** [ankidroid/Anki-Android#12814]
In the latest alpha I was trying to use:
 * AnkiDroidJS.ankiGetCardFactor()
 * AnkiDroidJS.ankiGetCardReps()
 * AnkiDroidJS.ankiGetCardLapses()

For some reason they all return 0. It does not happen with every API function, e.g. AnkiDroidJS.ankiGetCardDue() works well.

![a](https://i.imgur.com/gBl8ujA.png)

###### Reproduction Steps

1a. Add to a note type `AnkiDroidJS.ankiGetCardFactor()`
1b. Or simply use debug mode an in the console call `AnkiDroidJS.ankiGetCardFactor()`
2. Visualize a card of this type in preview mode

###### Expected Result
Something >0

###### Actual Result
0

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Huh :thinking: thanks for reporting this. May be possible to reproduce this one with a unit test - I'm not sure there is much if any coverage of the JS API, and if some of the APIs are reproducibly returning 0 it should show up immediately under a unit test

**Comment by fylux** [comment]
Thank you for the quick reply. Fyi today I have tried it in study mode and it does work well, so probably the issue is only when visualizing in the browser.

**Comment by notpx** [comment]
Hey im new to this, i know about java and i would likr to help

**Comment by SySagar** [comment]
I would like to work on this.

**Comment by SySagar** [comment]
I have an addition doubt. What is the expected return values of this function if not zero.
AnkiDroidJS.ankiGetCardFactor()
AnkiDroidJS.ankiGetCardReps()
AnkiDroidJS.ankiGetCardLapses()

**Comment by fylux** [comment]
Can anyone try to reproduce it in the latest version?

**Comment by david-allison** [comment]
Let's give this one another cycle

**Comment by ryg-git** [comment]
I would like to work on this issue

**Comment by adityakrchy** [comment]
I would like to work on the same. If possible, please assign me.
