### ISSUE TITLE
The application crashes when adding a new entry

### ISSUE THREAD

**Issue by xallllien** [ankidroid/Anki-Android#12819]
Hello!
After a break of several months, I opened the application, synchronized the decks, created a new deck. When trying to add a new entry, the application crashes. Rebooting the phone and reinstalling the app didn't help.
I will be grateful for your help.

--------------------

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Xiaomi

Model = Redmi Note 9 Pro

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi Note 9 Pro Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.91 Mobile Safari/537.36

ACRA UUID = ba60e95a-facf-4929-a50d-b62b00f67a4d

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment]
Hi there! You should definitely try the latest release from our releases page: https://github.com/ankidroid/Anki-Android/releases

There is something that causes lots of 2.15 users to crash when adding notes and I've heard almost completely "that fixed it" responses when using the current 2.16 alphas
