### ISSUE TITLE
[Bug] Error: Invalid input: card was modified after unsuspending a card while studying

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#12837]
While studying I used cardbrowser to find and unsuspend a card that I hadn't used in two years which would surely be due by now had it not been suspended. Then I returned to studying, answered the displayed card and received the error. Clicking OK dismissed the error and popped up a snackbar saying it was sending an error report and then returned me to the card I had just tried to answer. Answering again produced the same error but without notification that it had sent an error report. I exited back to the list of decks, synced, and then returned to studying and had no further errors.

###### Reproduction Steps

1. Study all decks
2. Click menu | card browser
3. Search for a card
4. Decide there are too many cards, click back then select a specific deck in the deck browser (probably not needed, just being complete)
5. Search again
6. Highlight the card
7. From the three dots menu, select Unsuspend card
8. Use 'back' gesture to go back to studying
9. Answer the card

###### Expected Result

Card is answered, continues to the next card (possibly even the one that was just unsuspended, who knows!)

###### Actual Result

![Screenshot_20221116-193851_AnkiDroidB](https://user-images.githubusercontent.com/409080/202336118-65b75e5c-cd08-4185-abe7-9cc76f20ddfe.png)

###### Debug info
```
AnkiDroid Version = 2.16alpha89

Android Version = 12

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = f9d003f3-ae34-4529-8cd5-ed8aff42fa30

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by justdvnsh** [comment]
@doozan I tried but I was not able to reproduce it. Maybe if you could give me some more info, I might be able to look into this.

**Comment by daddydave** [comment]
I got a similar error yesterday, but I also have no idea how to reproduce it. If it happens again, I'll try to pay more attention to what card I'm on. Maybe a one off for me. Attaching screenshot.
![Uploading Screenshot_20230128-230314.png…]()
