### ISSUE TITLE
Sync Error - Your Anko Client is not compatible with the V2 Server

### ISSUE THREAD

**Issue by Michaelar1** [ankidroid/Anki-Android#12842]
![Screenshot_20221117-130143_AnkiDroid](https://user-images.githubusercontent.com/112276652/202523913-89d5aac5-1541-43e3-9324-f42154cf7f12.jpg)
AnkiDroid Version = 2.8.4

Android Version = 12

ACRA UUID = 82692438-fc2f-4738-ab8f-dfcb2f11889b

**Comment by mikehardy** [comment]
Hi there! The error is as the error message says. You should get a new version, not sure why you are on v2.8.4 when the latest in the play store (and on f-droid) is 2.15.6 but you may easily access those and turn on v2 scheduler in advanced settings

Or you may grab the latest alphas and it is compatible out of the box https://github.com/ankidroid/Anki-Android/releases

That will fix you up
