### ISSUE TITLE
[Request] HTML support for decks list (decks name in the main page)

### ISSUE THREAD

**Issue by fehC** [ankidroid/Anki-Android#12851]
Title says it all.
On Windows and MacOS, Anki supports HTML/CSS format for decks names on the main page. Any plans to support that anytime soon in AnkiDroid? We need it for school. We now have decks that are color-coded and look appealing to young learners.

Would a generous donation motivate you to consider it?

Cheers

**Comment by BrayanDSO** [comment]
Didn't know that this can be done on Anki. Looks cool.

Although this still needs some polishing there (the HTML isn't stripped or parsed on other windows)

![image](https://user-images.githubusercontent.com/69634269/202865054-60d7fde4-4523-4e59-bdcd-2ba828afa520.png)
![image](https://user-images.githubusercontent.com/69634269/202864990-03de8978-3cde-4d8b-bc63-d207417d31ad.png)
![image](https://user-images.githubusercontent.com/69634269/202865030-59284289-cfb6-481d-88ad-46477c92d084.png)

**Comment by mikehardy** [comment]
I think this is a something that worked by accident and may be going away? I believe it came up before, am I misremembering this @dae ?

**Comment by dae** [comment]
You're correct, it's unsupported and will stop working in the future.

**Comment by fehC** [comment]
We have invested a lot of time and money in creating user-friendly lessons titles for our young learners on Anki main page. We're talking about kids as young as 5 years old.

Removing such a (hack) feature would certainly mean that we won't be updating our apps or apps on students' devices.

Why not leave such a minor feature as optional? Even better, why not implement it in AnkiDroid?

![anki](https://user-images.githubusercontent.com/1677377/202881516-6894eae7-9fb5-4c5d-8888-63ebb1c207cd.png)

**Comment by mikehardy** [comment]
AnkiDroid is not anti-any-feature-specifically but we are always resource-constrained.

As such we implement - in general - what is (or will be) supported in the general Anki system and as a priority, and what is required to track new Android releases, and that is struggle enough for us, we barely keep up and are a bit behind as it is.

So in this case if the Anki ecosystem is not going support this feature then it is a mis-prioritization of scarce resources to support it.

Unless Damien reconsiders this, it's a closed issue for us. Reopening is just a single button click here but unless reconsidered, it's not actionable here, with apologies
