### ISSUE TITLE
[Bug] Syncing with AnkiDroid breaks Custom Scheduler on Desktop

### ISSUE THREAD

**Issue by Blauelf** [ankidroid/Anki-Android#12866]
###### Reproduction Steps
Might require custom scheduler code that's already synced between desktop and AnkiDroid, as at one point, changes did work.

1.  On desktop, change something in the Custom Scheduler part.
2.  Sync on desktop
3.  Sync on Android
4.  Sync on desktop

###### Expected Result
The change is still there

###### Actual Result
The change got reverted by the last sync

###### Debug info

AnkiDroid Version = 2.16alpha90

Android Version = 11

Manufacturer = Xiaomi

Model = Mi 9T Pro

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Mi 9T Pro Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.105 Mobile Safari/537.36

ACRA UUID = 94aa4f3e-2914-4a88-88b4-37180006b849

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
> Scheduler = std2
/
can you retry w/new schema support and v3 enabled in advanced settings?

**Comment by Blauelf** [comment]
Same result with new backend and V3 enabled. Syncing on desktop *after* syncing on AnkiDroid reverts changes.

(Independently, with V3 enabled, AnkiDroid freezes on sync showing a window "Media Sync Log" "Background", no buttons or anything else, just my system asking me whether I want to wait or terminate the app. Is it doing some one-time thing without any progress bar, or is it actually stuck?)

**Comment by mikehardy** [comment]
the media sync log thing is a known "no user progress indicator" thing that we need to work on for the new schema - it probably won't be ready for 2.16 but it *is* actually doing something (or I think it is?) just no progress. It should be a sticky notification / foreground-service type deal where you can continue using the app while it works through whatever media sync stuff needs to happen

**Comment by matejdro** [comment]
This seems to be resolved with 2.16alpha92

**Comment by Blauelf** [comment]
Not resolved for me. It still reverts to one of the first versions I had in that field.

**Comment by Blauelf** [comment]
So I checked again.
After syncing on desktop, android, desktop again, the custom scheduler code is still overwritten by an old version.

**Comment by david-allison** [comment]
On my list for 2.17, thanks for the bump

**Comment by L-M-Sherlock** [comment]
@david-allison, has this issue been solved?

**Comment by BenjaminBrandtner** [comment]
Seems to be fixed in the new backend, (Settings -> Advanced) but not in the current one.

**Comment by wang1zhen** [comment]
@david-allison @BenjaminBrandtner is it safe to enable the new anki backend and v3 scheduler now (2.16.5 AnkiDroid)? It still remains "Experimental" on Ankidroid.
