### ISSUE TITLE
[Bug]Alpha2.16-90: Red dot on synch icon remains after synching. 

### ISSUE THREAD

**Issue by LBX1002** [ankidroid/Anki-Android#12873]
###### Reproduction Steps

1.  Hit synch icon
2. Red dot remains
3. Hit synch again - red now disappears

###### Expected Result
Expect red synch dot to disappear after synching.

###### Actual Result
Required 2 back to back attempts before red synch dot disappears.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ]x (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Can you share the debug info

**Comment by LBX1002** [comment]
> Can you share the debug info

I don't get any bug info. I just notice it when I am synching. I have to synch twice if I want the red dot to vanish.

**Comment by criticalAY** [comment]
I am not able to reproduce the issue like I am not facing this issue doing so

**Comment by criticalAY** [comment]
> > Can you share the debug info
> 
> I don't get any bug info. I just notice it when I am synching. I have to synch twice if I want the red dot to vanish.

This in the setting section -> about -> debug info

**Comment by criticalAY** [comment]
Did you check your data connection though?

**Comment by LBX1002** [comment]
AnkiDroid Version = 2.16alpha90

Android Version = 12

Manufacturer = samsung

Model = SM-F926U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-F926U1 Build/SP2A.220305.013; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.105 Safari/537.36

ACRA UUID = 4215bb3b-efed-4490-89c1-855fa20a8a44

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by LBX1002** [comment]
> Did you check your data connection though?

Yeah. Connection seems to be fine. The red dot also disappeared when I pulled down the menu to go to send the bug report.

**Comment by criticalAY** [comment]
You can try the new backend though. Thanks! for logging this one

**Comment by LBX1002** [comment]
> You can try the new backend though. Thanks! for logging this one

Sorry I am not that technical. How do I get the new blackened?

**Comment by LBX1002** [comment]
> > You can try the new backend though. Thanks! for logging this one
> 
> Sorry I am not that technical. How do I get the new blackened?

*backend

**Comment by criticalAY** [comment]
Go to setting -> advance -> turn on "use new database"

**Comment by criticalAY** [comment]
My findings are that this issue is due to the page not being refreshed after sync we don't need to hit the sync button again but just need to go to some other activity so  that the page is refreshed.

**Comment by criticalAY** [comment]
Yep! And it is only with the legacy backend not with the new backend, works fine there.

**Comment by LBX1002** [comment]
> Go to setting -> advance -> turn on "use new backend"

Fantastic! All works fine now. My thanks to the team.
