### ISSUE TITLE
Suggestion to push HTML tags to internal app working in place of showing it to the user.

### ISSUE THREAD

**Issue by Subhadiptech** [ankidroid/Anki-Android#12885]
**Is your feature request related to a problem? Please describe.**
For a user on clicking **B** or Underline, etc, the user is shown their respective HTML tags. In place this should be pushed into internal working as in my opinion.

**Describe the solution you'd like**
We can concat the tags but only show the resultant text to the user.

**Additional context**
I have shared a Screenshot which can describe it better.

Note: This is what I think, If maintainers/contributors think its good to go, then I can work on this issue.
<img width="301" alt="Screenshot 2022-11-27 at 4 28 10 AM" src="https://user-images.githubusercontent.com/89024718/204111928-5058159d-3cf7-4e5f-b79d-461b1b772612.png">

**Comment by mikehardy** [comment]
Duplicate #1377
