### ISSUE TITLE
Wrong Snackbar appears when changing deck

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12880]
###### Reproduction Steps

1. search a card in card browser
2. select that card
3. select change deck

###### Expected Result
Snackbars showing card moved to that particular deck

###### Actual Result
The snackbar says no card found in the present deck(the search function is performed for some reason though it works fine when not searching the changing the deck)

###### Debug info
AnkiDroid Version = 2.16alpha88

Android Version = 9

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 9; AOSP on IA Emulator Build/PSR1.180720.122; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = eca47b9a-8805-41f1-b44c-cf84187addf3

New schema = true

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by abhi-kr-2100** [comment]
I tried it and had a different result. This is all I did:
1. Create "Test Deck 1".
2. Create "Test Deck 2".
3. Add a basic card to "Test Deck 1".
4. Go to Card Browser.
5. Enter something in the search bar so that the only card results.
6. Select it.
7. Choose "Change Deck" from the options.
8. Select "Test Deck 2" as the destination.

The snackbar says, "1 card shown" instead of "Changed deck" or "No card found."

**Comment by criticalAY** [comment]
Yes because there might be something common in those cards so when you searched the card there must have been 2 results try when there is only one card as a search result. Even so the snackbar is still wrong

**Comment by criticalAY** [comment]
Debugger goes to the snackbar but the search snackbar overrides this one

**Comment by BrayanDSO** [comment]
Could you please send a video showing this?

**Comment by criticalAY** [comment]
> Could you please send a video showing this?

Will do once home

**Comment by criticalAY** [comment]
https://user-images.githubusercontent.com/48384865/203818495-e1b29c4c-caa8-4470-8f14-94d051af6796.mp4

@BrayanDSO here it is

**Comment by PratyushSingh07** [comment]
@BrayanDSO I am facing a different issue , I have moved a card from T2 to T1 but after this operation , the snackbar stays constant. It doesn't disappear as it should
![WhatsApp Image 2023-01-25 at 19 55 10](https://user-images.githubusercontent.com/90026952/214588993-b2a16d21-bc09-4614-86d7-01c0673b2ee2.jpeg)

**Comment by criticalAY** [comment]
@BrayanDSO Could you please remove the stale tag and add keep open

**Comment by Aditya-gupta99** [comment]
@criticalAY assign this to me I can fix this

> @BrayanDSO I am facing a different issue , I have moved a card from T2 to T1 but after this operation , the snackbar stays constant. It doesn't disappear as it should ![WhatsApp Image 2023-01-25 at 19 55 10](https://user-images.githubusercontent.com/90026952/214588993-b2a16d21-bc09-4614-86d7-01c0673b2ee2.jpeg)

**Comment by criticalAY** [comment]
You can start working on it as no one is working on it right now and you already dropped a text stating that you are interested. Go ahead. Happy coding!

**Comment by SanjaySargam** [comment]
I am working on it
