### ISSUE TITLE
Add alpha releases to F-Droid

### ISSUE THREAD

**Issue by xmha97** [ankidroid/Anki-Android#12908]
Hi @mikehardy
Please add the Anki alpha releases to F-Droid.
By default F-Droid install stable version, unless the following option is activated:
![IMG_20221201_012702_890.jpg](https://user-images.githubusercontent.com/23485114/204916766-d098acd1-2b78-41fc-97ce-0368a76deb4b.jpg)
Thanks

**Comment by xmha97** [comment]
Also you can upload the Anki alpha releases to Google play store for beta testers:
![IMG_20221201_013436_832.jpg](https://user-images.githubusercontent.com/23485114/204918028-f6281fe2-4263-436a-b156-0f5f7cb62eee.jpg)

**Comment by mikehardy** [comment]
Did you search the issues list prior to posting? I think this is duplicate

**Comment by BrayanDSO** [comment]
Relevant issue https://github.com/ankidroid/Anki-Android/issues/7159

**Comment by xmha97** [comment]
> Relevant issue https://github.com/ankidroid/Anki-Android/issues/7159

All similar issues are closed without being implemented.

**Comment by mikehardy** [comment]
@xmha97 did you take the time to read why?

Relevant comment https://github.com/ankidroid/Anki-Android/issues/7159#issuecomment-1145634222

> Who will maintain that? As alphas/betas should not be the "suggested version", they must be added manually every time, via merge request, which someone must open and someone must process.

**Comment by oakkitten** [comment]
Is that right, though? CMIIW, F-Droid builds are not pushed by AnkiDroid but instead pulled by F-Droid, which builds, signs and publishes APKs all by itself without human intervention. Given that alphas/betas do contain tags, I imagine you'd only have to add a few rules for this to work.

But perhaps it would be better to request this from F-Droid team.
