### ISSUE TITLE
maybe extracting everything to a recreateIfThemeHasChanged method as an Activity's extension method could work

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12906]
The same needs to be done on `DeckOptions.kt` and `FilteredDeckOptions.kt` as well (they are not `AnkiActivity`s and at the time I just duplicated the code as I expected to deal with it soon, but life took over my time). 

For reusability purposes, maybe extracting everything to a `recreateIfThemeHasChanged` method as an Activity's extension method could work

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/pull/12765#discussion_r1012245142_

**Comment by BrayanDSO** [comment]
#13076 should close this
