### ISSUE TITLE
Untangle android fragment testing dependencies w/Fragment 1.6 release

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12904]
From [upstream](https://issuetracker.google.com/issues/128612536#comment22) where they resolved the underlying issue:

> In Fragment 1.6.0-alpha04, we've added a new fragment-testing-manifest artifact. This means that instead of adding fragment-testing as a debugImplementation, you can now instead add fragment-testing-manifest as a debugImplementation and keep fragment-testing as androidTestImplementation.
> 
> debugImplementation "androidx.fragment:fragment-testing-manifest:$fragment_version"
> androidTestImplementation "androidx.fragment:fragment-testing:$fragment_version"

So we may undo [this commit](https://github.com/ankidroid/Anki-Android/pull/12817/commits/77bc2216f3b821562c8e6ed0814ab5817e1ef96a) from #12817 then get the fragment-testing stuff out of our implementation paths (a long-standing issue)

This will be blocked until 1.6 is released, check status here: https://developer.android.com/jetpack/androidx/releases/fragment

**Comment by lukstbit** [comment]
Nice, just saw the notification from their issue tracker.

**Comment by mikehardy** [comment]
This one should be available now, all the issue traffic (except one...where one person continued to have a problem?) indicates that this is fixed. Worth a try now for anyone interested

**Comment by david-allison** [comment]
In beta now, still not workable
