### ISSUE TITLE
Add progress indication to delete collection dialog in manage space activity

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12907]
- delete collection took a really long time for me - fairly sizable collection with regard to count of media files, on legacy or new backend / not scoped storage so it's just really slow IO. Maybe a follow-on PR to expand the modal to have number remaining vs number total to delete?

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/12765#issuecomment-1331541979_

**Comment by SanjaySargam** [comment]
I want to work on this issue.
Please assign me

**Comment by mikehardy** [comment]
@SanjaySargam I was going to give a warning for having too many PRs open and not getting them merged because I remembered a couple outstanding, but on a quick check I see you've gotten quite a few through! https://github.com/ankidroid/Anki-Android/pulls?q=+is%3Apr+author%3Asanjaysargam

Nicely done!

Go for it on this one, we don't assign generally - just coordinate with people in comments please - but also do please make sure to continue getting existing PRs that need replies through to merge before taking on too  many more. I think you have a reasonable amount now - just wanted to mention it. Cheers

**Comment by SanjaySargam** [comment]
Yes, I am in the process of resolving previous pull requests concurrently.

**Comment by soCallmeAdityaKumar** [comment]
@SanjaySargam are you working on it ?

**Comment by SanjaySargam** [comment]
> @SanjaySargam are you working on it ?

You can go ahead

**Comment by soCallmeAdityaKumar** [comment]
@mikehardy i need to know , ho to reach the manage space activity

**Comment by SanjaySargam** [comment]
> @mikehardy i need to know , ho to reach the manage space activity in app

App Info -> Storage Usage -> Manage Space
