### ISSUE TITLE
De-duplicate manage space activity checkMedia() for new schema by using backend method

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12905]
checkMedia() in the backend performs the same task, but @oakkitten felt that the fact that it renames invalidly-named files at the same time was worth writing his own implementation.

_Originally posted by @dae in https://github.com/ankidroid/Anki-Android/pull/12765#discussion_r1027031813_

----

May be that backend method can be made to not have a side-effect, may be that the side effect is judged not important.

Legacy schema will need the existing implementation for a while anyway I think, but would be nice to purge it with new schema + backend method call in future

**Comment by BrayanDSO** [comment]
FWIW, the new backend's Check media is a LOT faster than the manage activity one

**Comment by mikehardy** [comment]
My basic stance is: Rust is not going away, and Rust provides a check media method which is coded and maintained by others, which is like the best kind of "free stuff". So I lean strongly towards consolidating on that implementation. I'm not concerned by a normalizing name side effect as we are just one platform and if it's okay for the other 2 platforms (apple, desktop) it is a) observably acceptable *or* b) needs to be fixed for all of them. Either of those takes still results in using the rust backend implementation (just fixing it, if need be)
