### ISSUE TITLE
Test whether manage space activity calculates app data in FAT-format external storage

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#12916]
For the purpose of the method we'd need to have some data in a folder that's deleted with the app. I don't know if the system creates such folders on FAT partitions at all. But you can check that maybe `getExternalFilesDirs()` gives you several results? If so, then maybe you can test by placing stuff inside both of the folders, and verifying that that the FAT codepath gives you correct numbers. If not, mhm, perhaps call `android.app.usage.StorageStatsManager#getTotalBytes(java.util.UUID)` on the resulting UUID to see if it's valid.

Also, I guess this needs to be tested on a device with storage volumes that produce non-FAT volume identifiers...

_Originally posted by @oakkitten in https://github.com/ankidroid/Anki-Android/issues/12765#issuecomment-1332680745_

**Comment by mikehardy** [comment]
This may stale close, not sure anyone will have enough interest, but if someone wants to check this, you could probably write an integration test that checks the method.

My emulator with an sdcard was the reproduction case originally that showed the problem with FAT-formatted external cards but I did not go as far as correctly determining if space usage was calculated correctly after fixing a related crash

**Comment by oakkitten** [comment]
To explain what's going on here,

App (theoretically) can have its (semi-)private data on multiple volumes. It is not clear whether this is a realistic scenario. So just to be safe, when we want to calculate the size of data that will be deleted when the app is removed, we try account for all possible data.

We do that by looping through volumes and doing API requests using volume UUIDs. Sometimes the string UUID that `volume.uuid` gives us is incorrect. After some digging, I found that this might be a FAT volume identifier, and wrote code to convert it to a valid UUID. However, I can't run an emulator so I can't test whether the code actually works the way it is supposed to.

What needs to be done:
* Verify that private app data on FAT volumes is accounted for. To do this:
  * Have a FAT volume. Maybe it only exists on emulators, maybe not?
  * (Probably) call `getExternalFilesDirs()` and make sure you have at least 2 results, note both
  * Place files in both locations
  * In manage space activity, verify that the app size correctly reflects the two files
  * Verify, e.g. by placing a breakpoint, that we get a non-zero result from a volume that has a FAT identifier

  IF `getExternalFilesDirs()` doesn't return 2 volumes, but only one, you can't verify that placing data on a FAT volume will produce correct app data size. But you can verify that the UUID itself is correct. To do this:
  * Have a FAT volume
  * In manage space activity, put a break point somewhere around the code that touches UUID and note the resulting UUID of the FAT partition
  * Call `android.app.usage.StorageStatsManager#getTotalBytes(java.util.UUID)` or a similar method to see if the data returned for the volume is correct.
* Verify that private app data on non-FAT volumes is accounted for. Like above, but check with non-FAT volumes
* Try to determine whether [the alternative approach mentioned here](https://github.com/ankidroid/Anki-Android/pull/12765#issuecomment-1331190809) is sufficient. If so, we could simplify the code.
