### ISSUE TITLE
[Bug]application crashes due to invalid shortcut

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12910]
###### Reproduction Steps

1. Create a deck shortcut
2. delete the deck
3. click the shortcut

###### Expected Result
The shortcut is removed as soon as the deck is removed from the collection

###### Actual Result
Shortcut is not removed and results in a crash

###### Debug info
AnkiDroid Version = 2.16alpha90

Android Version = 12

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_x86_64 Build/SE1A.220630.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = 788ac1c2-9dfe-4386-a6c5-ca62fa05ac23

New schema = true

Scheduler = std3

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
@mikehardy should I raise the Todo or leave them because I will be working on it now

**Comment by mikehardy** [comment]
As long as there is something connected here (that is: raise a PR that has a `See #<issue number / comment>` so it's visible for coordination or something, that works for me. It (an issue, or a PR and the cross-linking in github) is more just to help with visibility which helps with work coordination. Two goals being: not to lose track of things and not to have two people accidentally working same thing
