### ISSUE TITLE
[Bug]In recent Alphas - Cannot paste a cropped image directly into a field anymore.

### ISSUE THREAD

**Issue by LBX1002** [ankidroid/Anki-Android#12926]
###### Reproduction Steps

1.  Open Edit Card
2.  (a) Go to.document to be cropped; (b) screenshot; ⒞ select area and crop an image (d) save
3. Go to Anki field and paste.
4. Nothing happens

###### Expected Result
I expect to see the image code (as was the case in version 2.15.6 in the Playstore)

###### Actual Result
Nothing happens.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha91

Android Version = 12

Manufacturer = samsung

Model = SM-F926U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-F926U1 Build/SP2A.220305.013; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Safari/537.36

ACRA UUID = 366705ad-10a3-45fd-86a5-c237e77a8071

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by LBX1002** [comment]
My apologies - it was working with version 2.16alpha29. I was able to reinstall it on my other phone and I will post a screenshot of what I am talking about shortly.

**Comment by LBX1002** [comment]
https://user-images.githubusercontent.com/61126947/205616502-5efe2277-31a3-4937-8821-515cda95d4e5.mp4

**Comment by LBX1002** [comment]
> Screen_Recording_20221205-102540_AnkiDroid.mp4

This ability to post cropped images directly into saves about 7 steps compared to using the "Add image" function in Anki, and avoids having to search through my gallery. 

Since 2.16Alph29 can no longer use the new database structure, I cannot run it along side an A or B version of the latest alpha.

For folks like me that post tons of cropped images, the direct past of cropped images was a life saver.  I really hope the function can be restored.
Thank!

**Comment by LBX1002** [comment]
https://user-images.githubusercontent.com/61126947/205621855-980efe9e-0417-4e00-b529-fa5144c5bee1.mp4

2.16Alpha91

**Comment by LBX1002** [comment]
https://user-images.githubusercontent.com/61126947/205621855-980efe9e-0417-4e00-b529-fa5144c5bee1.mp4

**Comment by mikehardy** [comment]
It is supposed to be working, strange that it stopped working, the library we use is being maintained even so the library itself should be working...

**Comment by tehami94** [comment]
Hello, I am new to open source but I know many relevant technologies like JAVA KOTLIN. Can u guide me how should I contribute.
For example- You raised this issue but how will I know which part of code should I change to make Changes in the app?

**Comment by tehami94** [comment]
According to me you can attach images rather than pasting them directly.

**Comment by xidsyed** [comment]
@LBX1002 are you sure this isnt an issue with your keyboard. The keyboard is responsible for the clipboard. 
I CAN reproduce the error with my Microsoft swift key keyboard, since its clipboard does not support copied images on my device i think.

can you open your clipboard and try to paste from there?

**Comment by xidsyed** [comment]
Also what are the A and B versions of the latest alpha, it says nothing on the about page, and there is no second main branch. where do i get the other versions of the alpha

**Comment by mikehardy** [comment]
> @mikehardy i am a relative beginner at android. made a few projects. I'm looking for an issue to solve that isnt being handled already. Please let me know if you have any mind 😅.

Hey there 👋  - search for issues labeled "good first issue" in our list, and check the wiki for development guides and google summer of code guides, they'll help get oriented here

> 
> Also what are the A and B versions of the latest alpha, it says nothing on the about page, and there is no second main branch. where do i get the other versions of the alpha

From the [releases page](https://github.com/ankidroid/Anki-Android/releases)

> The builds with letter codes below (A, B, etc) are universal parallel builds. They will install side-by-side with the main APK for testing, or to connect to a different AnkiWeb account in combination with changing the storage directory in preferences

They are useful for testing or multiple profiles as indicated here https://github.com/ankidroid/Anki-Android/wiki/FAQ#how-to-use-different-anki-profiles

**Comment by LBX1002** [comment]
> @LBX1002 are you sure this isnt an issue with your keyboard. The keyboard is responsible for the clipboard. I CAN reproduce the error with my Microsoft swift key keyboard, since its clipboard does not support copied images on my device i think.
> 
> can you open your clipboard and try to paste from there?
> 
>  2022_12_07_01_42_17_trim.mp4 
> kinda like this

Thanks for the reply.

I have a custom keyboard so I have to go back and figure out how to access its clipboard however:

With same the keyboard:
I can paste a clipped image to 2.16alpha29 but not to 2.16alpha91
I can also paste a clipped image to my Gmail.
So the image must be in the clipboard.

I did try my Samsung keyboard and I can paste the clipped image into 2.16alpha91.

So maybe it has something to do with my custom keyboard but it is strange that the same keyboard will work on  2.16alpha29 (and Gmail) but not 2.16alpha91.

**Comment by xidsyed** [comment]
![Screenshot_20221207-055451_NewPipe SponsorBlock.jpg](https://user-images.githubusercontent.com/26184016/206056467-5c06cea9-c333-492b-8f94-4f3fd7ae514e.jpg)

If I had to guess it is at the keyboards discretion whether or not it allows pasting an image into a test field. Even the Samsung keyboard will not allow you to paste an image into a search box edittext for example.

**Comment by LBX1002** [comment]
> ![Screenshot_20221207-055451_NewPipe SponsorBlock.jpg](https://user-images.githubusercontent.com/26184016/206056467-5c06cea9-c333-492b-8f94-4f3fd7ae514e.jpg)
> 
> If I had to guess it is at the keyboards discretion whether or not it allows pasting an image into a text field. Even the Samsung keyboard will not allow you to paste an image into a search box edittext for example.

I think it's more that the recent updates to Android OS are starting to block 3rd party keyboards access to post cropped images.  I just updated to Android 13 on one of my phones that the function was working and now I can no longer crop and paste using my 3rd party kb but I can still do so with my samsung kb.

**Comment by tanmaySinha16** [comment]
Hello , I am new to open source and interested in this project .Can anyone  please  guide me how to start contributing to this project. I am a beginner in Kotlin and android architecture components , please let me know if any issues are there?

**Comment by rohan3050** [comment]
I want to work on this issue please assign me this issu.
