### ISSUE TITLE
Add a sub-option to avoid syncing media on metered connections

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12932]
**Is your feature request related to a problem? Please describe.**
Frequently, I'm not at a place with Wi-Fi but I want to sync my cards with my cellphone connection, but would like to avoid syncing media so I don't spend much data

**Describe the solution you'd like**
Make `Fetch media on sync` a ListPreference with the options of `Always`, `Only on Wi-Fi` and `Never`.

**Comment by criticalAY** [comment]
thoughtful and makes more sense. Would give it a try
