### ISSUE TITLE
[Bug] crash or the application is closing

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12937]
###### Reproduction Steps

1. downloaded the shared deck having a lot of media
2. imported the collection
3. press sync again or interrupt the sync

###### Expected Result
normal sync is carried out

###### Actual Result
the application crashes

https://user-images.githubusercontent.com/48384865/206483035-ddfff8d3-350f-4e26-9e3b-b91b21c6bde1.mp4

###### Debug info
AnkiDroid Version = 2.16alpha91

Android Version = 12

Manufacturer = OnePlus

Model = EB2101

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; EB2101 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36

ACRA UUID = d962898b-b4fe-4630-8198-c116e81c81e7

New schema = true

Scheduler = std3

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
In my case, it's sync done successfully. I can't reproduce the issue.

**Comment by criticalAY** [comment]
Check the debug info ?

**Comment by dae** [comment]
For some reason the last bug report for your ACRA ID is 2 weeks ago on beta90.

**Comment by criticalAY** [comment]
> For some reason the last bug report for your ACRA ID is 2 weeks ago on beta90.

There was no report generated for this one I saw the logcat and this was caused due to some main thread action

**Comment by dae** [comment]
If it happens again, please provide the exact log.

**Comment by criticalAY** [comment]
oki sure
