### ISSUE TITLE
[Bug] Mathjax flalign function not working

### ISSUE THREAD

**Issue by Relevartt** [ankidroid/Anki-Android#12941]
Edit: Solution found — use the "aligned" function instead of the "flalign" function.

###### Reproduction Steps

1. Produce a Mathjax that begins with \begin{flalign} *a bunch of mathjax here* \end{flalign} on desktop
2. 
3. 

###### Expected Result
It will display a math expression on the left with a couple of equal expressions on the right aligned by their = sign.

###### Actual Result
It will display unformatted red text on a yellow background in the Android app.
![Screenshot_20221209-092918](https://user-images.githubusercontent.com/97558206/206659232-c75fc13c-96c3-47e0-a2e5-60d9a8ea6edb.jpg)

###### Debug info
AnkiDroid Version = 2.15.6 

Android Version = 11

Manufacturer = OnePlus

Model = GM1913

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; GM1913 Build/RKQ1.201022.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36

ACRA UUID = 4dfad7f4-9d3a-44f2-b2c2-29a43469eea6

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/doc
![Screenshot_20221209-092918] and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I may be wrong but I think v2.15.6 is on mathjax 2 and v2.16alpha series is on mathjax3 built right from the anki desktop code.

So you should see if you can reproduce it with the latest alphas and *hopefully* you can't. Could you try it and let us know?

Grab them here: https://github.com/ankidroid/Anki-Android/releases

**Comment by Relevartt** [comment]
> I may be wrong but I think v2.15.6 is on mathjax 2 and v2.16alpha series is on mathjax3 built right from the anki desktop code.
> 
> So you should see if you can reproduce it with the latest alphas and _hopefully_ you can't. Could you try it and let us know?
> 
> Grab them here: https://github.com/ankidroid/Anki-Android/releases

Hey thanks for the reply, could you tell me how long it will probably take for this update to roll out on the app store because that's where I downloaded Anki from, and I prefer not to tinker too much with stuff as long as it works fine, I've had some negative experiences with that...

**Comment by mikehardy** [comment]
Of course, I don't like to mess with things that are working either :-). On the other hand, the play store *should* update the app later once it officially releases. I cannot make a prediction on when it will release though, it may be some months yet.

Know that you may always install the parallel A version of the app for testing and the main one will maintain its connection to the play store and update itself once we release it as stable finally

**Comment by Relevartt** [comment]
> Of course, I don't like to mess with things that are working either :-). On the other hand, the play store _should_ update the app later once it officially releases. I cannot make a prediction on when it will release though, it may be some months yet.
> 
> Know that you may always install the parallel A version of the app for testing and the main one will maintain its connection to the play store and update itself once we release it as stable finally

Hey I found a solution. The "aligned" function does pretty much the same thing and it does show properly in the android app :) Thanks again for your responses!
