### ISSUE TITLE
Add an `Enable` button to the `You must enable gestures to hide the answer buttons` snackbar

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12940]
**Is your feature request related to a problem? Please describe.**
I'd like to ease the user life by not making them search the gestures preference with a simple `Enable` button

**Describe the solution you'd like**
1. Add an `Enable` button to the `You must enable gestures to hide the answer buttons` snackbar
2. If the user taps the button:
    - Open the controls fragment
    - Scroll/Highlight the `Enable gestures` preference
    - Turn on the `Enable gestures` preference

**Additional context**
IIRC, Android has a method to scroll to a preference on a PreferenceScreen.

And the SearchPreference library that we use has a highlight method that can serve as inspiration

**Comment by jeremyxarcher** [comment]
@BrayanDSO 

Just did a quick look at the codebase. I think you might be referring to this message instead: "You must enable gestures to hide the answer buttons." I didn't see any reference to the message you referred to, but I could be missing it!

**Comment by criticalAY** [comment]
I am working on it.

**Comment by BrayanDSO** [comment]
> Just did a quick look at the codebase. I think you might be referring to this message instead: "You must enable gestures to hide the answer buttons." I didn't see any reference to the message you referred to, but I could be missing it!

Yep. Changed the PR title. Thanks!

**Comment by SanjaySargam** [comment]
@criticalAY I have done half of the implementation. If you don't mind Can I take this issue?

**Comment by SanjaySargam** [comment]
@BrayanDSO Can you explain how exactly we can highlight preference when the user navigates to the ControlsSettingsFragment screen
