### ISSUE TITLE
[Bug] After saving new edits on the back template (while reviewing), the front template is replaced by the back template  

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#12949]
###### Reproduction Steps
I am not sure how to reproduce this issue as it isn't a consistent bug but I had this bug with several versions of Anki (currently with AnkiDroid 2.16alpha91 but was on AnkiDroid 2.16alpha70 before that). For a long time, I thought that I was the one doing the error (ex: with a select all, paste error) but twice since yesterday I have just me small edit and I had this bug, so I am sure the bug isn't from and error select-all/paste. 

1. do a deck review
2. click on the pen to edit and scroll down to edit the note template
3. select the back template and modify it
4. I am not sure about what is really triggering the bug here: but yesterday afternoon I switched to the front template, scrolled a bit and then saved the edits. Today I switched to the front template then to another app (ex: browse 2-3 page in my Android browser) and came back on Anki, finished editing the back and saved. 

The strange thing is that when I try to reproduce exactly what I have just done, then I don't never get the bug. Most of the time I get the bug when I edit the template for the first time in several hours, not the many times I save after my first edit. 

###### Expected Result
When coming back on the note template (or the deck review), the front template should remain unchanged and the back one should have its edits saved

###### Actual Result
The front template is replaced by the back one. 

###### possible solution
I haven't found anyone complaining about this so it may be difficult to debug, but a possible solution would be to check for major change ad confirm them or someting like that (because of this bug, I have added a comment for each template on the very first line that state `<!-- front-->` and   `<!-- back -->` so that could be another way to add a warning.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha91

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36

ACRA UUID = 558d8332-b5e1-48c7-b893-93de78759e5e

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Aayush2111** [comment]
Hi, I'm new to this organization and I'm excited to be a part of the project. I'm looking forward to learning from everyone and contributing what I can to the project.
