### ISSUE TITLE
Replace the parallel build scripts with gradle configs

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12955]
**Is your feature request related to a problem? Please describe.**
Creating parallel builds with a script isn't a safe thing to do and have got some bugs with the time and probably will get some more with the new Android/Gradle configs that may come

**Describe the solution you'd like**
Setup app id suffix with `applicationSuffixId` and try setting up in gradle the parallel builds

> A flavor or a build variant, not sure about the difference. Or perhaps just fetch the suffix and name from properties, then you'll be able to set that via local properties file or command-line arguments
There's string app_name, make that generated by gradle

oakkitten on [Discord](https://discord.com/channels/368267295601983490/847123004059549718/1051251770132803666)

**Comment by BrayanDSO** [comment]
I had made https://github.com/ankidroid/Anki-Android/commit/6f59e0c8f643cc7d72b95200ae0d094e9ff2a65d while trying to fix #12953, but got the idea to get rid of the whole script instead

**Comment by mikehardy** [comment]
We need to change the default storage location as well I think? Not sure all of the items changed by the parallel build script can be done with application suffixes

That said, I definitely made the parallel build script before I knew about gradle application suffixes (which I use myself, in a work app - they are great...). Might be able to handle all of it

**Comment by mikehardy** [comment]
I think this may be required in order to have a complete fix for #12953 - as the temporary fix proposed by #12954 hard wires even parallel builds to use the main install's manage space activity if I understand correctly. That "works" but only for a small definition of word works as it access unexpected code (main install) from the parallel app

**Comment by david-allison** [comment]
I was gone for this discussion. I believe it's at least partially resolved in https://github.com/ankidroid/Anki-Android/pull/13089
