### ISSUE TITLE
[Bug]The count textviews are not visible in dark mode.

### ISSUE THREAD

**Issue by Subhadiptech** [ankidroid/Anki-Android#12952]
###### Reproduction Steps

1. Run the app in dark mode.
2. Create a card.
3. Observe the count text color of the card at the right 

###### Expected Result
The color should be visible to the user without any effort.

###### Actual Result
The color is mixing with the background of the card and making hard for the user to read.

For more clarification, I am sharing the screenshot of my physical emulator.

Device - Xiaomi Redmi Note 8

Android Version - 11
![Screenshot_2022-12-11-01-06-08-251_com ichi2 anki](https://user-images.githubusercontent.com/89024718/206873252-8553852b-ba3d-40dc-bca0-a06cb2747926.jpg)

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Marius1501** [comment]
I would work on this issue. 😄

**Comment by Subhadiptech** [comment]
Thanks @Marius1501 . Let the reviewer check your PR
