### ISSUE TITLE
[Bug] Screen may get dark while importing a huge deck

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12950]
###### Reproduction Steps

1. Deck picker > Three dot menu > Import deck
2. Select a huge deck file (GBs of size)

###### Expected Result

A nice and beautiful user interface is shown while importing the deck

###### Actual Result

Everything goes dark for a while

###### Debug info

app built with 6ea36860a8e9fddadff0bf484746248fd843eb53

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Most likely because decks/collection files/CSVs are copied to cache before being imported

**Comment by oakkitten** [comment]
I think I've seen the black screen a few times and LeakCanary was to blame, so try disabling it (you can do so via its notification). Also FWIW you can try attaching a debugger in AS and pressing the camera button, that should dump threads and you'll see where the main thread or some other threads are stuck

**Comment by BrayanDSO** [comment]
Originally noted on a release version. And my debug builds always have leak canary disabled anyway, so I'm pretty sure it isn't the problem.

**Comment by david-allison** [comment]
Longstanding issue. Not LeakCanary related. 

Needs to handle the following async: https://github.com/ankidroid/Anki-Android/blob/bdb279a7f4024415fdd6f76fd6ecf89b354a17b5/AnkiDroid/src/main/java/com/ichi2/anki/IntentHandler.kt#L65 as it copies a file to the app cache. 

This file may be GBs large.
