### ISSUE TITLE
Add a preference on developer options to disable leakCanary 

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12957]
**Is your feature request related to a problem? Please describe.**
Kind of follow up of #12956 

**Describe the solution you'd like**
- Add a SwitchPreference at the "Developer options" screen to enable/disable LeakCanary at will

**Comment by pratyaksh1610** [comment]
I am working on it.

**Comment by Aayush2111** [comment]
@pratyaksh1610 Are you already working on this issue? If not, I'd be happy to take a look and see if I can help!

**Comment by pratyaksh1610** [comment]
@Aayush2111 I think I have resolved the issue, I think you can help in reviewing the PR and suggest improvements. Thanks

**Comment by Aayush2111** [comment]
@pratyaksh1610 Sure!

**Comment by BrayanDSO** [comment]
Closed this in favor of native approach described [here](https://github.com/ankidroid/Anki-Android/pull/12956#issuecomment-1345401002)
