### ISSUE TITLE
Add a cancel confirmation to the import dialog

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#12951]
**Is your feature request related to a problem? Please describe.**
I happened to tap outside the import dialog just to keep my phone awake and got my import cancelled, so lost some minutes

**Describe the solution you'd like**
A cancel confirmation dialog if the user taps outside the import dialog

**Comment by Subhadiptech** [comment]
Ya, in my suggestion, we should get a alert before closing. Can I work on this issue?

**Comment by BrayanDSO** [comment]
Sure. 

FYI, this happened with the new backend enabled (`Settings > Advanced > Use the new backend`). Haven't tested if this happens with the legacy backend as well.

**Comment by Subhadiptech** [comment]
Okey will try to check all possibilities.

**Comment by Subhadiptech** [comment]
Another query, @BrayanDSO  how should the alert dialog look?

**Comment by Subhadiptech** [comment]
Okay, thanks a lot.

**Comment by Subhadiptech** [comment]
Hey @BrayanDSO, according to the code, On selecting CSV file for importing, it opens a webView
`else if (requestCode == PICK_CSV_FILE && resultCode == RESULT_OK) {
            val path = ImportUtils.getFileCachedCopy(this, data!!) ?: return
            startActivity(CsvImporter.getIntent(this, path))
        }`
        
        So, do you think there is a dialog for import button where we can add a cancellable listener?

**Comment by n1snt** [comment]
Hey, is anyone working on this?

**Comment by BrayanDSO** [comment]
Nope. Go for it

**Comment by n1snt** [comment]
This dialog right? 
![image](https://github.com/ankidroid/Anki-Android/assets/46300244/2fdd4f52-6175-4cb5-a305-f35ccf755658)

**Comment by BrayanDSO** [comment]
No, it would be the progress dialog when a file is being imported
