### ISSUE TITLE
[Bug] Night mode is not set for the whole app

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#12958]
###### Reproduction Steps
1. Have day mode switched on
2. Force quit AnkiDroid in the app info
3. Start AnkiDroid
4. Study cards
5. Switch night mode on
6. Back to the deck picker

###### Expected Result
Deck picker is in night mode

###### Actual Result
The app is in day mode

###### Debug info
AnkiDroid Version = 2.16alpha91

Android Version = 12

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A225F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36

ACRA UUID = 26e4486a-d86f-4fe9-84d4-2bf87a7c4d03

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
I would like to add something, even if we don't force stop the app and just open it up in day mode and then turn on the night mode the main screen will go to dark mode but if you click on any deck and start reviewing it then it would still be in the light/day mode

**Comment by BrayanDSO** [comment]
I believe that I've fixed the night mode problems once and for all, although I need to fix some bugs and merge #12991 first in order to do it
