### ISSUE TITLE
Just copy an image / picture to the clipboard

### ISSUE THREAD

**Issue by sangorys** [ankidroid/Anki-Android#12969]
**Is your feature request related to a problem? Please describe.**
Sometimes, I want to copy a picture from an Anki card to the clipboard and I'm always frustrated.

**Describe the solution you'd like**
1. Long push / touch an image
2. A menu appears with the item : "copy"

**Describe alternatives you've considered**
I am doing screenshot, so the size of the picture is huge and it takes more time

**Additional context**
NA. Everything else is excellent !!!

**Comment by criticalAY** [comment]
Could you please share the debug info?

**Comment by mikehardy** [comment]
A cursory glance at this indicates that context menu or long press functionality needs to be implemented in WebViewClient and for images (if context menu or long press is invoked on an image) the handler would then need to copy to clipboard.

Does seem potentially useful.

**Comment by dhruvpatidar359** [comment]
Hello @mikehardy. Please provide a detailed explanation of which file has to be changed, as there are many of them in webViewClient, making it difficult for me to work on it.

Many thanks

**Comment by dhruvpatidar359** [comment]
![Screenshot (285)](https://user-images.githubusercontent.com/103873587/210411496-776b352a-c449-4189-9c85-cfc31501e1cf.png)
 which files out of these ?

**Comment by mikehardy** [comment]
Sorry, I don't have time to provide guidance at this level. You'll have to experiment and determine the location of the change - that experimentation/determination is part of the necessary work in other words

**Comment by dhruvpatidar359** [comment]
> Sorry, I don't have time to provide guidance at this level. You'll have to experiment and determine the location of the change - that experimentation/determination is part of the necessary work in other words

Ok , will try my best
