### ISSUE TITLE
Adding a card by long pressing the deck

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12962]
**Is your feature request related to a problem? Please describe.**
I was going through a deck which I have created to learn Japanese and when I exhausted all the card I long pressed the deck thinking there would be an option to directly add a card to the deck/sub deck but there isn't any. It's a lil convenient  I find it creates much more ease for the user.
I would love to hear it from other developers.

**Describe the solution you'd like**
We can give the free hand to directly add card/s to the deck/sub deck by long pressing it

**Describe alternatives you've considered**

**Additional context**

**Comment by Marius1501** [comment]
I would like to work on this issue. 😃

**Comment by mikehardy** [comment]
Sure, sounds great, and thank you

**Comment by criticalAY** [comment]
Keep open please
