### ISSUE TITLE
[Bug] Wrong Deck exported when exporting from the context menu

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#12966]
###### Reproduction Steps

1. Long press hold a deck
2. Select export deck

###### Expected Result
If we are exporting some other deck than the default deck then that deck should be exported

###### Actual Result
The default deck is exported 

###### Debug info
AnkiDroid Version = 2.16alpha91

Android Version = 12

Manufacturer = OnePlus

Model = EB2101

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; EB2101 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36

ACRA UUID = d962898b-b4fe-4630-8198-c116e81c81e7

New schema = true

Scheduler = std3

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Should the last word in this sentence from the description be "exported"?

> If we are exporting some other deck than the default deck then that deck should be imported
