### ISSUE TITLE
Better button placement for handwriting feature 

### ISSUE THREAD

**Issue by KanjiWanji** [ankidroid/Anki-Android#12979]
**Is your feature request related to a problem? Please describe.**

When writing kanji characters, there is no button to wipe the board clean. You must go back stroke by stroke to the beginning to rewrite your character from scratch. There should be a reset/wipe board feature. 

Additionally, when hitting the arrow button to go back a stroke, it is very easy to turn off the writing pad altogether or toggle the flag menu. If you want to go back several strokes and hit the back button several times consecutively, you risk turning the writing pad off by accident then hitting the back button. This makes you go back to the previous card and not back a stroke. I've had it happen where I'm trying to get to the beginning of my stroke order So I'm hitting the back arrow a few times consecutively, and instead I accidentally turn off the writing pad and send myself back two or three cards.

**Describe the solution you'd like**
I would like to see a small dedicated handwriting menu open with a back button for stroke order, an erase button to clear the board completely, and an on and off toggle switch. This small handwritten menu should be away from all the other review function buttons such as the flag button or go back button.

**Describe alternatives you've considered**

None 

**Additional context**

This would be useful not just for Japanese but also Chinese, Korean - any language where there are complex ideographic characters with a stroke order. It would also permit me to practice writing the kanji several times by writing it then completely erasing it rather than write it once then have to go back stroke by stroke.

**Comment by BrayanDSO** [comment]
Really liked the ideas. Other Android apps have a dedicated floating or fixed bar at the bottom or the side of the screen with the pen actions.

Dividing this issue, I suggest

- [ ] Adding a redo button
- [ ] Changing the eraser icon of the undo button to the undo icon
- [ ] Adding a proper eraser tool
    - it should either erase a stroke completely after touching it or just erasing the selected area, whatever is easier to implement
- [ ] Move the whiteboard controls to a floating bottom or sidebar
    - Probably a sidebar would be better, since the answer buttons are most commonly at the bottom
    - Include:
        - Pen stroke width
        - Pen color
        - Undo
        - Redo
        - Eraser

**Comment by snowtimeglass** [comment]
Hi, a dedicated handwriting menu is interesting for me, too.

>When writing kanji characters, there is no button to wipe the board clean. You must go back stroke by stroke to the beginning to rewrite your character from scratch. There should be a reset/wipe board feature.

IIUC you may want to try and use "Clear whiteboard" action as a current usable measure, right...? I think it is the feature to wipe the board clean.
![image](https://user-images.githubusercontent.com/10436072/207871930-0105160a-2a89-4516-b3f1-2e546434af7a.png)

 Redo feature, which exists in Anki Desktop, may be in high demand.

**Comment by Aayush2111** [comment]
I absolutely love these ideas!
Can I start to work on this? I'm eager to contribute to the project and I'd love to implement these ideas!
My prior knowledge includes working with android studio and java/kotlin.

**Comment by BrayanDSO** [comment]
> Can I start to work on this?

Sure. Go for it 👍

**Comment by pratyaksh1610** [comment]
@Aayush2111 Can you please tell on which parts are you currently working on the above mentioned issue ?

**Comment by Aayush2111** [comment]
> @Aayush2111 Can you please tell on which part are you currently working on the above mentioned issue ?

I am currently working on implementing clear button, undo button and redo button

**Comment by KanjiWanji** [comment]
Thanks for your hard work on the improvements folks, really looking forward to seeing the end result! Never knew this was how feature requests got implemented. 

So I didn't know if this was a "feature request" .. more of an associated or secondary complaint - in the next version is it possible to also reduce the drawing area by 1 or 2 mm along the bottom margin and create some dead space above the "Show Answer" button? 

With writing/drawing board enabled sometimes I go to hit the Show Answer button, nothing happens, I hit it a few more times, then realize I'm missing the button by a fraction and instead I've just been creating a bunch of dots above it.

Thanks again for all your hard work!

**Comment by soCallmeAdityaKumar** [comment]
Can I work on the moving Whiteboard control.
If yes please assign it to me

**Comment by SanjaySargam** [comment]
> Changing the eraser icon of the undo button to the undo icon
I am working on it

**Comment by SanjaySargam** [comment]
>  Changing the eraser icon of the undo button to the undo icon

I am working on it

**Comment by KanjiWanji** [comment]
Hi, just replying to keep this alive. Still hoping some big brained people who can code can make this magically happen. Every time I want to erase a kanji it has to be stroke by stroke, There's NO way to just wipe the slate clean you have to erase each kanji stroke by stroke. So if you want to write a 15 stroke kanji over again and practice, first you have to hit the erase button 15 times. I almost never succeed without accidentally hitting the previous card arrow instead, sometimes a few times, and I erase about 1.5 minutes of progress.
