### ISSUE TITLE
[Bug] Find empty cards window doesn't have a cancel option 

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#12973]
###### Reproduction Steps

1. Open three dot menu.
2. Click "Empty cards" option.

###### Expected Result
The finding empty cards window should have an option to cancel.

###### Actual Result
There is no cancel option.

![IMG_20221214_081456](https://user-images.githubusercontent.com/92206575/207495021-fb00a275-29ff-42f1-ab21-2758d5e7b98e.jpg)

Note that the cancel option appears upon pressing the back button, but this may not be intuitive to the user.

###### Debug info
AnkiDroid Version = 2.16alpha91

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.79 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pratyaksh1610** [comment]
I working on it .

**Comment by dae** [comment]
I don't think the backend method supports cancellation at the moment, so fixing this will require a PR to the desktop code.

**Comment by lonewolf2208** [comment]
Hey @pratyaksh1610 are you still working on it ?

**Comment by user1823** [comment]
> I don't think the backend method supports cancellation at the moment, so fixing this will require a PR to the desktop code.

But, the cancel option that appears upon pressing the back button does cancel the operation. This means that cancellation is possible. So, the resolution of this issue just requires the addition of a cancel option in the "Finding empty cards" window.

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by user1823** [comment]
The real reason for which I opened this issue was that the operation took too long to complete. But, now the operation completes within seconds. It might be a result of optimization of the code or might be caused by the fact that I am using a newer (and faster) device now. So, this issue is no longer important for me.

Current debug info:
```
AnkiDroid Version = 2.16.2
Android Version = 12
ProductFlavor = full
Manufacturer = motorola
Model = moto g62 5G
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g62 5G Build/S2SSIS32.18-12-4-11; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36
ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50
New schema = true
Scheduler = std3
Crash Reports Enabled = true
DatabaseV2 Enabled = true

```

**Comment by dae** [comment]
The Rust backend is considerably faster at this. It doesn't currently support cancelling the operation mid-way, but I'm going to close this until that proves necessary.
