### ISSUE TITLE
[Bug] Error after sync & check media

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#12974]
After I sync AnkiDroid with AnkiWeb, it sometimes get the following error.

![IMG_20221214_083907](https://user-images.githubusercontent.com/92206575/207495957-56130e42-8589-48d7-8007-9ae6c0518155.jpg)

Note that each time I have received the error, I was syncing changes made on Anki Desktop to AnkiDroid and not vice-versa.

When this error occurs, I usually perform another sync, thinking that a part of the collection may not have been synced.

Yesterday, after this error occurred, I happened to open the collection media folder in the file explorer. The folder didn't contain the media files I added to Anki Desktop before the sync.

By performing another sync, the media files were synced.

Yesterday, I also saw the same error while using the Check Media feature.
Steps:
1. I clicked on check media option. It showed me 2 unused files.
2. I clicked on delete option.
3. The error was shown.
4. I clicked check media again. It showed me 1 unused file.
5. I clicked on delete. The error was shown again.
6. I clicked on check media again. It showed no unused file.

Combining the above two observations, it appears to me that this issue is related to accessing the collection media folder.

###### Debug info
AnkiDroid Version = 2.16alpha91

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.79 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
The permission is granted.

**Comment by user1823** [comment]
This issue occurs every time there are unused media files that have to be deleted.

Please fix this soon, otherwise, I have to delete media files one by one following the steps below:

1. Click on check media option. It shows x unused files.
2. Click on delete option.
3. The error is shown.
4. Click check media again. It shows x - 1 unused files.
5. Click on delete. The error is shown again.

This cycle continues till there are no unused files left.

**Comment by dae** [comment]
Looks like the same root cause as #12827
