### ISSUE TITLE
[Bug] Custom Study deck doesn't appear until switching away from AnkiDroid and back

### ISSUE THREAD

**Issue by daddydave** [ankidroid/Anki-Android#12975]
###### Reproduction Steps

1. On the Decks screen, long press a deck and choose Custom study
2. Choose Review ahead
3. Choose 1 day

###### Expected Result
Custom Study deck should appear

###### Actual Result
Progress roundabout keeps spinning and Custom Study deck does not appear. I have waited up to 5 minutes with no change, but actually it is fixed as soon as I switch to home screen and back to AnkiDroid

###### Debug Info
AnkiDroid Version = 2.16alpha91

Android Version = 10

Manufacturer = motorola

Model = moto g(7) power

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; moto g(7) power Build/QPOS30.85-23-7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.79 Mobile Safari/537.36

ACRA UUID = 99a1caac-47da-4d5e-9f15-93d81de2b763

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pratyaksh1610** [comment]
I am able to reproduce it, will fix it soon.

**Comment by pratyaksh1610** [comment]
It happens with other options too.

**Comment by lukstbit** [comment]
@daddydave Thanks for the bug report and for testing the new backend. A fix for this will be available with the next alpha.

**Comment by daddydave** [comment]
Awesome, thanks!
