### ISSUE TITLE
[Bug] unable to hear audio for ankidroid app first timer user

### ISSUE THREAD

**Issue by Ashdream07** [ankidroid/Anki-Android#12989]
###### Reproduction Steps

1. What does this mean?
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pratyaksh1610** [comment]
Hi @Ashdream07 .Please follow the template as it will give complete information about the issue. `Reproduction Steps` include the steps that are required to reach that issue that you are facing in an app, and can you please share the debug info. Thanks.

**Comment by mikehardy** [comment]
Closing, this does not include anything required to help. Just open a new issue if you need to, but please provide information required to help (here's a handy guide: https://stackoverflow.com/help/how-to-ask) plus our template
