### ISSUE TITLE
[Bug] Audio not working after first sync in android app

### ISSUE THREAD

**Issue by ashlyn-tan** [ankidroid/Anki-Android#12992]
###### Reproduction Steps

1. Open Ankidroid
2. Play cards but no audio coming out
3. 

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 12

Manufacturer = samsung

Model = SM-P613

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-P613 Build/SP2A.220305.013; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.79 Safari/537.36

ACRA UUID = 1f1b7c86-ea74-4dc2-b5e4-82c162880a1b

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there - have you tried all the items here? https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

**Comment by ashlyn-tan** [comment]
Hi, yes. The media files are in the directory in my anki android and the coding is [sound:Tatoeba arh sentence EngID 37000 SpaID 922562.mp3]
file type is mp3 that is correct too

**Comment by ashlyn-tan** [comment]
> Hi there - have you tried all the items here? https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

Hi, yes. The media files are in the directory in my anki android and the coding is [sound:Tatoeba arh sentence EngID 37000 SpaID 922562.mp3]
file type is mp3 that is correct too

**Comment by Bholanath8436** [comment]
Hi,
I want to work on this issue please assign me this issue.
