### ISSUE TITLE
[Bug] The full width of the card cannot be displayed

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#12998]
###### Reproduction Steps

Card browser→Preview

###### Expected Result

![aa11](https://user-images.githubusercontent.com/10048069/208256621-fae964fd-87f8-4378-b70d-e5b5b3a68c78.jpg)

###### Actual Result (After I pinch the screen with two fingers)

![aa22](https://user-images.githubusercontent.com/10048069/208256632-5125ebc4-3192-4cfa-9cc8-b75e528c5cf1.jpg)

###### Research

My anki version is 2.16alpha91. I bought a new folding screen phone (honor Magics Vs), and since the outer screen has a 21:9 ratio (not the regular 18:9), it's causing this problem. I now need to pinch the screen with two fingers every time I PREVIEW a card for its content to display properly. Hope to fix this problem

**Comment by pratyaksh1610** [comment]
@Juddd Can you please share debug info ?

**Comment by Juddd** [comment]
> @Juddd Can you please share debug info ?
> 
> Settings -> About -> Copy debug info

AnkiDroid Version = 2.16alpha91

Android Version = 12

Manufacturer = HONOR

Model = FRI-AN10

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; FRI-AN10 Build/HONORFRI-AN10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.105 Mobile Safari/537.36

ACRA UUID = d86e7160-cca6-40f1-a2ee-db0a99bb36a1

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by Juddd** [comment]
> @Juddd Can you please share debug info ?
> 
> Settings -> About -> Copy debug info

Hi, could I expect this problem to be fixed as soon as possible? This greatly affected the review experience. If you still want to know how the problem is reproduced, I would like to cooperate with your debugging work very actively.

**Comment by Juddd** [comment]
This is a problem about my .css:

```
body { 
tab-size: 2; 
min-width:384px;
}
```

It's normal after remove it
