### ISSUE TITLE
The FullscreenMode must be on default value if gesture is disabled

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#12995]
###### Reproduction Steps

1. Enable Gestures
2. Select `Hide the system bars and answer buttons` (in FullscreenMode)
3. Disable Gestures 

###### Expected Result

The FullScreenMode  should be on `Off`

###### Actual Result

Here the FullScreenMode is still selected on `Hide the system bars and answer buttons`

###### Debug info

AnkiDroid Version = 2.16alpha91

Android Version = 10

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/QSR1.210802.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.185 Mobile Safari/537.36

ACRA UUID = ba1aa3b4-a9fe-4414-8ce5-fbb9b01159e1

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

**For Better Understanding**

https://user-images.githubusercontent.com/65113071/208245765-6ba9ddbf-3334-444a-80f0-a0a0004494b3.mp4

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Not that I'm thinking about it, even without the answer buttons and gestures, the user can still review their cards with a controller/keyboard/external device, so the snackbar isn't that useful and may not be even correct in its use.

**Comment by criticalAY** [comment]
@BrayanDSO Are you referring to the TODO that was placed to enable the gesture?

**Comment by SanjaySargam** [comment]
> Not that I'm thinking about it, even without the answer buttons and gestures, the user can still review their cards with a controller/keyboard/external device, so the snackbar isn't that useful and may not be even correct in its use.

This is different issue

**Comment by BrayanDSO** [comment]
> Are you referring to the TODO that was placed to enable the gesture?

I am referring to if goal of the snackbar is still valid

**Comment by SanjaySargam** [comment]
> Not that I'm thinking about it, even without the answer buttons and gestures, the user can still review their cards with a controller/keyboard/external device, so the snackbar isn't that useful and may not be even correct in its use.

Yes, showing the snackbar isn't helpful

**Comment by ishantok** [comment]
i want to try this issue plz assign me this issue

**Comment by SanjaySargam** [comment]
> i want to try this issue plz assign me this issue
I think this is not a valid issue
Let the @BrayanDSO confirm it

**Comment by SanjaySargam** [comment]
> i want to try this issue plz assign me this issue

I think this is not a valid issue
Let the @BrayanDSO confirm it
