### ISSUE TITLE
Adding multiple buttons affects the efficiency of the operation

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#13000]
I added some common buttons through the "plus" sign at the far right of the toolbar:

![crossbutton](https://user-images.githubusercontent.com/10048069/208257250-c0d5c404-84b1-474f-aa39-fec6abe952c4.jpg)

These buttons are very common to me, but due to the limited width of the screen, I now have to swipe right every time to reach them. Can you arrange the new BUTTONS down IN a ROW instead OF to the right? This saves the user from having to swipe the tiny toolbar to the right countless times.

**Comment by BrayanDSO** [comment]
Tap the three dot menu at the top right of that screen then disable "Scroll toolbar"

**Comment by Juddd** [comment]
> Tap the three dot menu at the top right of that screen then disable "Scroll toolbar"
> 
> If that solves the issue, let us know

thanks, It solves my problem indeed
