### ISSUE TITLE
If background image applied, then it should be set with all the layouts inside the app.

### ISSUE THREAD

**Issue by SB2318** [ankidroid/Anki-Android#13005]
**Is your feature request related to a problem? Please describe.**

When we apply a background image for the app, it is only displayed for one fragment. Rests are the same as it is.
I don't think it's the expected behavior.

![withBG](https://user-images.githubusercontent.com/87614560/208307696-7cf6174a-41e9-4080-8422-a573751a6d62.png)|![without_bg2](https://user-images.githubusercontent.com/87614560/208307726-a32dc760-29a6-4600-9a87-f2db47eae7c5.png)

**Describe the solution you'd like**

The rest of the features are okay. I want the background of all fragments to be affected by this change. I would like to try if it is possible.

**Describe alternatives you've considered**

Although I don't know if it will go with your design or not,
But since this particular fragment is only effecting.

We can add it (Change Background) to this pop up.

![InkedwithBG](https://user-images.githubusercontent.com/87614560/208308041-ad6f2139-09b3-405d-b2e0-55afd5ca50f7.jpg)

**Additional context**

**Comment by kimo-supremo** [comment]
yes please I've needed this for quite a while as some font is unreadable on the android app while very easily readable on the computer

**Comment by SanjaySargam** [comment]
> yes please I've needed this for quite a while as some font is unreadable on the android app while very easily readable on the computer

what's the font name?

**Comment by kimo-supremo** [comment]
> > yes please I've needed this for quite a while as some font is unreadable on the android app while very easily readable on the computer
> 
> what's the font name?

sorry i meant font color. dark blue

**Comment by SanjaySargam** [comment]
ok

**Comment by SB2318** [comment]
@kimo-supremo Thanks for your response. Please assign me on this issue. And give me some time. Because next week I will busy with my semester exam 😅. But I will try to solve it.

**Comment by kimo-supremo** [comment]
> @kimo-supremo Thanks for your response. Please assign me on this issue. And give me some time. Because next week I will busy with my semester exam 😅. But I will try to solve it.

no worries good luck!
