### ISSUE TITLE
Discuss if the "You must enable gestures first" snackbar should be shown if the answer buttons are hidden

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13002]
Not that I'm thinking about it, even without the answer buttons and gestures, the user can still review their cards with a controller/keyboard/external device, so the snackbar isn't that useful and may not be even correct in its use.

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/12995#issuecomment-1356331577_

**Comment by SanjaySargam** [comment]
This snackbar must be shown if the user tries to off gestures even when answer buttons are hidden

**Comment by SanjaySargam** [comment]
@BrayanDSO So what we have to do?
Remove the snackbar?

**Comment by BrayanDSO** [comment]
> @BrayanDSO So what we have to do?
Remove the snackbar?

IMO, yes

**Comment by SanjaySargam** [comment]
> > @BrayanDSO So what we have to do?
> Remove the snackbar?
> 
> IMO, yes

Okk
I will work on this.
