### ISSUE TITLE
Feature request: retrieving the last selected answer (again, hard...) via the js API.

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#13018]
I search in the ["AnkiDroid Javascript API" wiki](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API), if it was possible to retrieve the last chosen answer for a card but I didn't find it.

This info is already in the info from the card but it would be nice to have access to it via the API.

This would be really useful for example to display specific warnings or tips when the last answer was "Again" and the interval was more than a specific number of days (ex: 30).

**Comment by mikehardy** [comment]
Seems like many of the Card Info related APIs that are currently exposed could be removed and replaced with a single info-returning getCardInfo API that returns a JSON with all the info

**Comment by MagTun** [comment]
Yes that would be a really good idea!
