### ISSUE TITLE
[Bug] 2.16 alpha92 - card info no displaying

### ISSUE THREAD

**Issue by szalejot** [ankidroid/Anki-Android#13027]
###### Reproduction Steps

3 dots menu in right corner -> Card info

The result is the same while during a review or in the card browser with the card selected.

###### Expected Result

Card info displayed. Worked in 2.16 alpha91.

###### Actual Result

Empty window with "(No card to display.)" message.

![Screenshot_2022-12-23-14-56-37-780_com ichi2 anki](https://user-images.githubusercontent.com/3840404/209365690-9b32b528-fc68-4d16-9042-f1190fb02eb1.jpg)

###### Debug info
AnkiDroid Version = 2.16alpha92
Android Version = 12
Manufacturer = Xiaomi
Model = 21081111RG
Hardware = mt6893
Webview User Agent = Mozilla/5.0 (Linux; Android 12; 21081111RG Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36
ACRA UUID = 76363c13-0769-4137-8c86-83fac13b0de0
New schema = true
Scheduler = std3
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Hey! Thanks for logging this issue seems like there is some issue with the new backend. For time being please disable the new backend. as it works fine it being off and will try to get it fixed asap.

**Comment by mikehardy** [comment]
@dae does this look like something that may have changed in all the Anki-Android-Backend work? There was a lot of work prior to get + render the backend typescript pages, maybe some of that was undone? 

@szalejot I wonder if (with new backend enabled...) you also have a problem seeing statistics or not? It also uses the backend's typescript pages system to show information and would help indicate if this was a "complete backend typescript page problem" or just a "cardinfo has some problem" type of thing. Thanks for testing!

**Comment by szalejot** [comment]
@mikehardy Statistics are showing perfectly fine.

**Comment by mikehardy** [comment]
Interesting! If I had placed a bet, it would have been on total typescript failure, so I would have lost that bet. Something card info specific then. Thanks for reporting back

**Comment by LBX1002** [comment]
Have same issue. No card info displays with new backend on 2.16 alpha 92 but works when new backend is unchecked.

**Comment by mikehardy** [comment]
Okay - I understand it is not convenient for regular folks to update to current unreleased code but if you did a local build now it would be fixed for you. It will be fixed in the next alpha - until then as mentioned above, disable new backend if card info is important for you. Sorry for the trouble but thanks a ton for the quick fix @dae !
