### ISSUE TITLE
[Bug] Alpha 92 not showing cards due for the new day

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#13022]
The day changed. So, the app should show cards due for the next day. However, the alpha 92 version doesn't.
Also, the main screen shows "Studied _ cards in _ minutes today" while I studied those cards yesterday not today.

I installed alpha 91 in parallel. It showed the due cards as it should.

Note the "Start of next day" is set to be 4 hours past midnight and I checked for the new cards at 6:50 AM.

###### Debug info
AnkiDroid Version = 2.16alpha92

Android Version = 7.0

Manufacturer = motorola

Model = Moto C Plus

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Moto C Plus Build/NRD90M.03.045; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by in-out** [comment]
same here

**Comment by mikehardy** [comment]
Thanks for reporting this you two - you can see we've got a PR linked that will close this (where "we" is "Damien found and fixed the issue" 😆 ) and I'm driving the release process for it right now in our backend module. We will hopefully have an alpha93 out with it fixed before too long. Sorry for the hassle!
