### ISSUE TITLE
[Bug] Not adding suggestion in TAGS

### ISSUE THREAD

**Issue by Sagar0-0** [ankidroid/Anki-Android#13021]
###### Reproduction Steps

1. Click on "Add a note"
2. Click on "Tags"
3. Type something 
4. Click on the keyboard suggested word

###### Expected Result
It should fill the TextField with the clicked word, but it just clears the TextField.

###### Actual Result
It clears the whole word that we were trying to add.

https://user-images.githubusercontent.com/85388413/208943729-287b0aaf-57f4-4e90-b7e5-b15c1bb0ae84.mp4

###### Debug info

AnkiDroid Version = 2.15.6

Android Version = 9

Manufacturer = Realme

Model = RMX1831

Hardware = mt6771

Webview User Agent = Mozilla/5.0 (Linux; Android 9; RMX1831 Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = f75dd278-c2c9-4a0c-be58-d4be749f2a73

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Please do not skip the debug info. Without some reference to what version of the code you are running, any bug report has little value

**Comment by Sagar0-0** [comment]
Done

**Comment by user1823** [comment]
According to my experience, it occurs because the keyboard inserts a space in addition to the suggested word.

When a space is added, AnkiDroid rejects the whole text because spaces are not permitted in the tags.

I think a better behaviour would be to just remove the space (and probably also show a popup saying spaces are not permitted, which would be helpful for the cases when the user is manually trying to add a space.)

**Comment by Sagar0-0** [comment]
Having the same issue while adding a new TAG, I don't think this is an expected behavior.

**Comment by Sagar0-0** [comment]
> According to my experience, it occurs because the keyboard inserts a space in addition to the suggested word.
> 
> When a space is added, AnkiDroid rejects the whole text because spaces are not permitted in the tags.
> 
> I think a better behaviour would be to just remove the space (and probably also show a popup saying spaces are not permitted, which would be helpful for the cases when the user is manually trying to add a space.)

Should I work on this solution?

**Comment by BrayanDSO** [comment]
Yeah. I like the idea:
- Remove spaces if they are at the beginning or at the end of the string
- Don't allow the input of tags with space within them by disabling the plus button (I haven't checked, but I supposed that the plus button action is to add notes

If you want to, go for it @Sagar0-0. I hope you have a good time implementing this

**Comment by Sagar0-0** [comment]
Sure, I'm going for it. I have some questions here, everyone the user inputs a space we have to show a Toast message or a Snackbar? and suppose when the user input a sentence from the clipboard which contains spaces in between the words, then we should just remove the spaces or disable the add button and let the user remove them manually?

**Comment by BrayanDSO** [comment]
I think that showing a message every time a space is added would be annoying, as some keyboards add spaces after selecting a word. And removing the spaces automatically isn't something the user would expect normally. So probably just showing a snackbar saying that spaces aren't allowed after tapping the add button would be fine

**Comment by Sagar0-0** [comment]
Ok doing it now

**Comment by Sagar0-0** [comment]
Well, The app is working differently for my device and the emulator. What is the reason? Using the emulator, when I add a space, it treats it as `::` and do not allow 2 consecutive space. But on my device, it is working as mentioned in the issue.

**Comment by Sagar0-0** [comment]
Is this(or any related) issue previously reported and resolved? or what is the reason for this behavior? Does anyone know?

**Comment by user1823** [comment]
This is likely due to the support for hierarchical tags which was added by https://github.com/ankidroid/Anki-Android/pull/10966.

Since this PR was merged, the tags feature is not at all working for me, which I reported in https://github.com/ankidroid/Anki-Android/issues/12471 and https://github.com/ankidroid/Anki-Android/issues/12472.

**Comment by Sagar0-0** [comment]
So, in the newly added feature, if the spaces are used for creating the hierarchy(as spaces get converted to '::'), then this issue doesn't exist anymore. Need the author's reply to close this here.

**Comment by user1823** [comment]
Now, it must be checked whether addition of keyboard suggestions in the latest alpha works as it should or not.

If it does work correctly, I think that this issue can be closed.

**Comment by Sagar0-0** [comment]
Yes, it works but I think creating a Nested tag by adding a space in between words is not the expected behavior and a normal user can't just understand why this is happening, so IMO we should add a little note at the bottom of Tags Dialog that this this is a feature to be used. What do you guys think?

**Comment by Sagar0-0** [comment]
It will be something like this:
![Add a space to create nested Tags](https://user-images.githubusercontent.com/85388413/210128161-4b4b614a-2325-48d8-8614-e07edc5c3b82.png)

Authors let me know if it looks good to you, then I will add this.

**Comment by user1823** [comment]
The idea is good.
However, I think that
- The text should read something like "Tip: Add a space to create nested tags."
- The message should have more contrast (so that it can be seen easily).

Also, can we detect when a space is added by the keyboard automatically and when it is added manually by the user? If so, we can remove that space in order to prevent creation of unwanted nested tags.

Otherwise, can we instruct the keyboard to not automatically insert spaces with the suggested words?

**Comment by Sagar0-0** [comment]
Nice tip! 
For removing unwanted spaces added by the keyboard we can just use the trim method, so either the space at the end is added by the user or by the keyboard that will(and should) be removed.

**Comment by Sagar0-0** [comment]
Any update on this Suggestion?

**Comment by Sagar0-0** [comment]
Adding nested tag can be done intentionally, we should not remove all the spaces. We just have to  make the user aware about the new feature of creating nested tag with a space. IMO, this is the simplest way todo.

> It will be something like this: ![Add a space to create nested Tags](https://user-images.githubusercontent.com/85388413/210128161-4b4b614a-2325-48d8-8614-e07edc5c3b82.png)
> 
> Authors let me know if it looks good to you, then I will add this.

**Comment by user1823** [comment]
What about the unwanted spaces added by the keyboard? That is the main point.

**Comment by Sagar0-0** [comment]
We can just trim the extra space at the end when user is creating the tag. Not every time when user clicks on suggestions.

**Comment by user1823** [comment]
In many cases, tags consist of multiple words. Several examples are there in the following image shared by you:
https://user-images.githubusercontent.com/85388413/210128161-4b4b614a-2325-48d8-8614-e07edc5c3b82.png

So, if we don't automatically remove the spaces, :: would be added every time the user clicks on a keyboard suggestion. So, taking an example from above image, BasicSyntax would become Basic::Syntax

This is what I am concerned about.
