### ISSUE TITLE
cleanup: Replace most usages of `TextUtils` with Kotlin methods

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13036]
We have a lot of usages of `TextUtils.isEmpty` and `TextUtils.join` that could be replaced with Kotlin methods, which are more idiomatic and have better contracts. Another reason to do it is to *perhaps* improve some tests performance, as said by `@mikehardy` [here](https://github.com/ankidroid/Anki-Android/pull/11684#discussion_r906317512).

These are quite simple to do, so it's fine to have many of these on a single PR.

As these are going to be pure simple non-functional changes, I'd rather keep this as a good first issue for ***only new contributors***.

So, if you are not a new contributor, your help would be welcome on any one of the other issues we have

**Comment by soCallmeAdityaKumar** [comment]
Please assign it to me. 
I want to work on it.

**Comment by Aayush2111** [comment]
> Please assign it to me. I want to work on it.

Hey, you can go ahead and start to work on it, we are all volunteers here :)
just keep this thread updated so others can know if someone's already working on it or not

**Comment by soCallmeAdityaKumar** [comment]
Can Any one please review my PR.

**Comment by criticalAY** [comment]
> Can Any one please review my PR.

Hey! Everyone here is a volunteer so they are working here in their free time or whatever time they can make for it, please be patient with the PRs you are making as it has hardly been 24 hours which isn't a lot of time. Someone will take a look they come across it.

**Comment by rishujam** [comment]
Is this issue handled?

**Comment by soCallmeAdityaKumar** [comment]
> Is this issue handled?

I am doing it

**Comment by rishujam** [comment]
Okay, why no one is assigned

**Comment by ParthTagalpallewar** [comment]
Hello there, I am a beginner to Anki android, may I start my contribution by beginning work on this issue?

**Comment by Mehar18** [comment]
can i work on this?

**Comment by criticalAY** [comment]
@Mehar18 @ParthTagalpallewar There is an existing PR on this issue. I suggest picking another issue(good first).

**Comment by ParthTagalpallewar** [comment]
> @Mehar18 @ParthTagalpallewar There is an existing PR on this issue. I suggest picking another issue(well first).

Please can you help me by suggesting a comparatively easier one at first?
