### ISSUE TITLE
Show timeline while recording audio

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13043]
**Is your feature request related to a problem? Please describe.**
When the recording starts there is no timeline shown(00:00:00). IMO it makes more sense to have the time there as it helps keep a record for the user.

**Describe the solution you'd like**
Adding a timeline which can be displayed while recording and playing the saved audio file

**Describe alternatives you've considered**

**Additional context**
![Screenshot_38](https://user-images.githubusercontent.com/48384865/209850442-e9190ff9-e426-4cb6-9a78-fdd53022b187.png)

**Comment by Sagar0-0** [comment]
This whole thing contains a lot of bugs. Should I report all of them one by one or... IMO, we need to improve the whole recording system.

**Comment by criticalAY** [comment]
> This whole thing contains a lot of bugs. Should I report all of them one by one or... IMO, we need to improve the whole recording system.

Sure go ahead

**Comment by Sagar0-0** [comment]
I think, for changing the working mechanism of the audio player, we have to make changes in multiple places like `AudioPlayer, AudioRecorder, AudioView, and MediaPlayer` and also the tests related to them..., that's gonna be a huge task and also error-prone. I think I can't handle the whole task independently, so need some assistance with the steps and precautions for getting started.

**Comment by BrayanDSO** [comment]
`NF`, on our context, normally stands for `Non-functional`, but this is a functional change, so I renamed the PR

**Comment by criticalAY** [comment]
> I think, for changing the working mechanism of the audio player, we have to make changes in multiple places like `AudioPlayer, AudioRecorder, AudioView, and MediaPlayer` and also the tests related to them..., that's gonna be a huge task and also error-prone. I think I can't handle the whole task independently, so need some assistance with the steps and precautions for getting started.

I'll work with you but it's just that I am busy with assignments and stuff.

**Comment by criticalAY** [comment]
> `NF`, on our context, normally stands for `Non-functional`, but this is a functional change, so I renamed the PR

Interesting NF was new feature for me :)

**Comment by Sagar0-0** [comment]
> > I think, for changing the working mechanism of the audio player, we have to make changes in multiple places like `AudioPlayer, AudioRecorder, AudioView, and MediaPlayer` and also the tests related to them..., that's gonna be a huge task and also error-prone. I think I can't handle the whole task independently, so need some assistance with the steps and precautions for getting started.
> 
> I'll work with you but it's just that I am busy with assignments and stuff.

I can understand!! My exams are also going on. I am starting with understanding the current mechanism, then let you know about the changes we have to do

**Comment by adiityack** [comment]
![WhatsApp Image 2022-12-30 at 8 02 05 PM](https://user-images.githubusercontent.com/118683224/210081480-fc87b160-91e0-4bdb-8b66-e87d298b13fa.jpeg)

I am beginner at github and Anki,I want to contribute in resolving this issue,need help!! I am not able to find XML file of the activity(screen shot is attached in the comment)

**Comment by Sagar0-0** [comment]
> ![WhatsApp Image 2022-12-30 at 8 02 05 PM](https://user-images.githubusercontent.com/118683224/210081480-fc87b160-91e0-4bdb-8b66-e87d298b13fa.jpeg)
> 
> I am beginner at github and Anki,I want to contribute in resolving this issue,need help!! I am not able to find XML file of the activity(screen shot is attached in the comment)

Double tap the shift key in windows to activate search in android studio and type some generic keywords that can be related to some activity or layouts you want to search.

**Comment by adiityack** [comment]
> 

Thankyou,but I have already tryed that,but couldn't find that particular XML file.

**Comment by Sagar0-0** [comment]
That's most probably `multimedia_edit_field_activity`

**Comment by Sagar0-0** [comment]
And the class related to the work is `BasicAudioRecordingFieldController`

**Comment by Sagar0-0** [comment]
Well, there are lot of abstraction layers! To refactor the player's mechanism we need to manipulate a lot of things than expected.

**Comment by criticalAY** [comment]
Yes, I know that it is not as easy as seems to be so It can't be done in one go. We will have to take down in steps.

**Comment by criticalAY** [comment]
@adiityack Thanks for your efforts as a beginner I would suggest you to pick a 'Good First Issue' so you are bit familiar with the codebase

**Comment by adiityack** [comment]
> @adiityack Thanks for your efforts as a beginner I would suggest you to pick a 'Good First Issue' so you are bit familiar with the codebase

Ok  I will go for "Good First Issue" first

**Comment by Sagar0-0** [comment]
> Yes, I know that it is not as easy as seems to be so It can't be done in one go. We will have to take down in steps.

So are you going to implement this particular feature?

**Comment by criticalAY** [comment]
I'll look into it and will let you know : )

**Comment by criticalAY** [comment]
I would like this to be kept open
