### ISSUE TITLE
Language setting "Not set" to "System Language"

### ISSUE THREAD

**Issue by Subhadiptech** [ankidroid/Anki-Android#13046]
The below screenshot shows that the language is shown to user as not set but in place, it should by default show System language text in the menu.

<img width="340" alt="Screenshot 2022-12-30 at 9 31 29 PM" src="https://user-images.githubusercontent.com/89024718/210089636-5f7316e5-fc53-46dd-992b-4ae7ce1eab78.png">

**Comment by Subhadiptech** [comment]
If the issue is valid, then I would love to work on this

**Comment by Aayush2111** [comment]
It shows "System language" to me though.

**Comment by Subhadiptech** [comment]
Hey @Aayush2111 can you specify thr device in which you are running the app

**Comment by Aayush2111** [comment]
Physical device: Redmi note 9 pro
android version: 11
ankiDroid 2.16alpha92

**Comment by BrayanDSO** [comment]
#12991 will fix it after it is reviewed/merged

**Comment by Subhadiptech** [comment]
Cool.
