### ISSUE TITLE
Case insensitive search

### ISSUE THREAD

**Issue by ghost** [ankidroid/Anki-Android#13057]
Hello,

When searching for cards in the Card Browser, some characters are case sensitive. More specifically, letters such as þ/Þ or ð/Ð as well as (some?) letters with diacritics like í/Í.
Is there a reason for this? If so, would it be possible to have true case-insensitive search as an option?

Thank you

**Comment by Subhadiptech** [comment]
Hey @January3rd , Can you please attach some video ref to show the same

**Comment by January3rd** [comment]
Hello,
I don't understand your request. My description is quite clear I believe, and you can test it on your phone in about 5 seconds. Why is a video needed?
(to be clear, I am not being hostile here, just genuinely puzzled)

**Comment by Subhadiptech** [comment]
@January3rd Reason being, I have searched with some decks and it worked fine for me. The reason of video demand was to know for which collection of deck and search string seq, its showing problem

**Comment by dae** [comment]
The OP provided some examples of letters they were having trouble with. Did you try those? A video does not seem necessary here. 

@January3rd, can you reproduce the issues with the new schema enabled in the preferences screen of the latest alpha build?

**Comment by elliotcathcart** [comment]
> can you reproduce the issues with the new schema enabled in the preferences screen of the latest alpha build?

@dae what's the exact name for the setting to enable the new schema? Is it just the new backend setting? If so the issue still persists for me.

Is regex supported by ankidroid? The same issue exists on the on desktop app but it can be circumvented by searching "re:Ö" instead of just "Ö". Could be a temp workaround for OP at least

**Comment by dae** [comment]
New backend sounds like it. With the new backend, the regex search should work - it won't with the old backend. A simple search only does simple ascii case folding. We should probably document this on https://docs.ankiweb.net/searching.html#ignoring-accentscombining-characters and note the option in the preferences to make it the default.

**Comment by January3rd** [comment]
Hello,
@dae I'm not sure how to do that. I only have the default Android app, is that a desktop-only setting?

**Comment by dae** [comment]
If you're not using an alpha, I'm afraid you'll need to wait for now.

**Comment by mikehardy** [comment]
You may try the new alphas directly from our release page: https://github.com/ankidroid/Anki-Android/releases
You may turn on the "new backend" in advanced preferences, then ... it may work?
