### ISSUE TITLE
Note Editor: Wrong field editing screen opened

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13064]
###### Reproduction Steps

1. Edit note
2. click attach
3. open menu/three dots
4. Audio Clip

###### Expected Result
The audio option is opened

###### Actual Result
Video and Audio options are shown

###### Debug info
AnkiDroid Version = 2.16alpha91

Android Version = 12

Manufacturer = OnePlus

Model = EB2101

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; EB2101 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/107.0.5304.141 Mobile Safari/537.36

ACRA UUID = d962898b-b4fe-4630-8198-c116e81c81e7

New schema = true

Scheduler = std3

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
I am self assigning this issue

**Comment by pavreh** [comment]
Imagine you want to add a video clip. You must tap three dots - Audio clip - Video.

**Comment by criticalAY** [comment]
> Imagine you want to add a video clip. You must tap three dots - Audio clip - Video.

Yes, there is a bit of correction needed there for each case

**Comment by SanjaySargam** [comment]
It should be better if menu/three dots itself has video clip option

**Comment by PratyushSingh07** [comment]
@criticalAY can you assign this issue to me

**Comment by PratyushSingh07** [comment]
@criticalAY @SanjaySargam @vvs  this is the current progress , I am almost there so kindly assign this to me and let me know if this is what you would like
https://user-images.githubusercontent.com/90026952/214680654-88cb057d-ac1f-44d1-94f0-02e595af2499.mp4

**Comment by criticalAY** [comment]
Hey @PratyushSingh07 ! we are all volunteers here so please be patient with the response time and avoid too much direct pings. You can start working on it as you need to drop a message to see if someone else is working or not. In this case it was me but I am short of time right now. So you are free to work on it.

**Comment by PratyushSingh07** [comment]
> Hey @PratyushSingh07 ! we are all volunteers here so please be patient with the response time and avoid too much direct pings. You can start working on it as you need to drop a message to see if someone else is working or not. In this case it was me but I am short of time right now. So you are free to work on it.

Thanks man , will keep it in mind henceforth

**Comment by criticalAY** [comment]
And IMO we can skip that unnecessary screen and directly select the media/audio just by clicking the options there, that was my proposal

**Comment by prabs3257** [comment]
can i work on this issue ?

**Comment by criticalAY** [comment]
> can i work on this issue ?

@PratyushSingh07  is working on it ig?

**Comment by criticalAY** [comment]
@david-allison could you mark this "keep open"

**Comment by criticalAY** [comment]
Closing it since the code is revamped during my GSoC project
