### ISSUE TITLE
[Bug]Multibyte characters causes crash

### ISSUE THREAD

**Issue by tea-create** [ankidroid/Anki-Android#13065]
###### Reproduction Steps
add notes (not when importing) on devices with imported notes containing Japanese characters.

> 

##### Expected Result
open the editing window and select deck which you want add to

###### Actual Result
app crashes

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
Can you please share debug info

**Comment by tea-create** [comment]
AnkiDroid Version = 2.15.6

Android Version = 10

Manufacturer = samsung

Model = SM-A750C

Hardware = exynos7885

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-A750C Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = d983f6c8-fea4-46e6-9f88-17ced86b9138

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by criticalAY** [comment]
@tea-create try out the latest alpha release I am certain that it was fixed

**Comment by tea-create** [comment]
Thanks, the app have runned correctly
