### ISSUE TITLE
Work out a concrete plan to finish up scoped storage and release a new version

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#13072]
Google Play is now [delisting apps that do not target an API level within two years of the latest major Android release](https://support.google.com/googleplay/android-developer/answer/9876714#:~:text=To%20provide%20users,needed.%20Learn%20more). We are currently falling behind, as we require arbitrary storage access, which prevents us from targetting later Android. We are still up, but the deadline is (as I undestand) the 1st of May, after which AnkiDroid will vanish from Play Store.

It looks like we have enough time, but work on migrating to scoped storage is progressing a bit slower than you might expect. It was commenced many months ago and is still incomplete, although it's close. If we are going to meet the deadline, I think we ought to create a concrete and detailed plan on how to do this work.

I'm not exactly sure what would be a good way to work out such a plan. I'm not exactly a fan of Google docs and flowchart websites but maybe these will do good. Meanwhile, I suggest that we simply write our versions of the a plan in the comments below, and see where it leads us. I'll start.

**Comment by oakkitten** [comment]
As I see it, codewise, speaking broadly, we need to do these things:

* Finish up scoped storage
* Identify and tie up the loose ends that arose during the alpha development
* Thoroughly test the release candidates, looking for edge cases

Here's what I think needs to be done to tackle these:

* Stop merging PRs unrelated to this plan, unless simple enough so we can be sure that it will not introduce new issues. Pin an issue explaining this. Maybe stop reviewing them as well, or even ask everyone to stop submitting them.

* Identify what work needs to be done to finish up scoped storage. As I understand, there's some UI code and some backend code that is mostly done and what's needed is tying it all together. I'd like to ask Arthur and Dave to weigh in here as they did most of the work here. Create issues for according tasks, and tag them with `Scoped storage` or something. Perhaps we could ask David to write up a bird's-eye view of how the migration works, and how it is tested, in simple terms.

* Identify the loose ends that arose during the alpha development. These might be stale bugs that no-one got around to fix up, or partially merged PRs. Tag these with `Loose ends` or something. I suggest creating and pinning an issue inviting everyone to suggest these loose ends.

* After we have a list of issues, assign them to more experienced developers who can come up with ETAs. I enjoy reviewing PRs of developers of all levels of experience, but often reviewing takes more time than actually doing things myself, and here time is of essence. 

  Here we need a bit of bossing people around. Having a bullet point with no-one assigned to it is a great way of not getting things done. We need a way to deal out tasks, inquire about availability, work out if the deadlines can be met. In other words, we need an HR department. Perhaps someone can assume the role of it, or maybe we can successfully organize ourselves without it, not sure.

* After the issues have been resolved, identify what needs to be tested manually by people, and recruit a team of testers to go through it. Storage migration is something that can lead to data loss, and combinations of different devices and API versions can have underwater stones that automated tests currently can not pick up. It'd be best to have a way to communicate with the testers to notify them of changes and to ask them to test additional stuff.

  Also, investigate whether it'd be feasible to run our automated tests on a matrix of different devices with different Android versions. Perhaps there are some third-party services that offer this kind of testing?

**Comment by BrayanDSO** [comment]
> Stop merging PRs unrelated to this plan, unless simple enough so we can be sure that it will not introduce new issues. Pin an issue explaining this. Maybe stop reviewing them as well, or even ask everyone to stop submitting them.

Agreed with all but the part of "or even ask everyone to stop submitting them", as I don't think everybody is going to be interested on scoped storage, and their PRs can be reviewed later.

> Identify what work needs to be done to finish up scoped storage. As I understand, there's some UI code and some backend code that is mostly done and what's needed is tying it all together. I'd like to ask Arthur and Dave to weigh in here as they did most of the work here. Create issues for according tasks, and tag them with Scoped storage or something. Perhaps we could ask David to write up a bird's-eye view of how the migration works, and how it is tested, in simple terms.

Most important part IMO. The lack of a list of tasks in such a big project done by multiple people is the main reason I, particularly, haven't tried to work on it.

> Identify the loose ends that arose during the alpha development. These might be stale bugs that no-one got around to fix up, or partially merged PRs. Tag these with Loose ends or something. I suggest creating and pinning an issue inviting everyone to suggest these loose ends.

Do you mean things we've got to fix before releasing? Since I've started contributing, I've always been on the 2.16 scoped storage limbo, so I'm not sure about the default releasing procedures, better to consult with Mike, but I guess that the [2.16 milestone ](https://github.com/ankidroid/Anki-Android/milestone/42) would be fit the goal of the `Loose ends` label

> After we have a list of issues, assign them to more experienced developers who can come up with ETAs. I enjoy reviewing PRs of developers of all levels of experience, but often reviewing takes more time than actually doing things myself, and here time is of essence.

Agreed

> Here we need a bit of bossing people around. Having a bullet point with no-one assigned to it is a great way of not getting things done. We need a way to deal out tasks, inquire about availability, work out if the deadlines can be met. In other words, we need an HR department. Perhaps someone can assume the role of it, or maybe we can successfully organize ourselves without it, not sure.

Idk how feasible this is on a volunteers' project, but I agree with the overall lines of trying to organize who does what and keep track if they are going to be able to do it or not in the expected time, so other people can take over if necessary

> After the issues have been resolved, identify what needs to be tested manually by people, and recruit a team of testers to go through it. Storage migration is something that can lead to data loss, and combinations of different devices and API versions can have underwater stones that automated tests currently can not pick up. It'd be best to have a way to communicate with the testers to notify them of changes and to ask them to test additional stuff.

IIRC, David knew some people he trusted to test it

**Comment by BrayanDSO** [comment]
And I like Google Docs and Figma flowcharts. They are a good way for people adding their current statuses and TODOs

**Comment by oakkitten** [comment]
> Do you mean things we've got to fix before releasing? Since I've started contributing, I've always been on the 2.16 scoped storage limbo, so I'm not sure about the default releasing procedures, better to consult with Mike, but I guess that the [2.16 milestone ](https://github.com/ankidroid/Anki-Android/milestone/42)would be fit the goal of the `Loose ends` label

Oh, wasn't aware of that milestone. Well, yes, that's what I was thinking of, but this list is probably not quite... up-to-date at the time. For instance, it includes a WYSIWYG editor which is something we probably don't want to deal right now, and doesn't include stuff like the FAB in Card browser that was supposed to be removed. So much work was done in various parts of the project, and some of it is incomplete or otherwise problematic. It's so easy to miss an important issue when there's just so much going on, so we should start compiling a list of issues and ranking them by urgency as early as possible.

**Comment by BrayanDSO** [comment]
> Oh, wasn't aware of that milestone. Well, yes, that's what I was thinking of, but this list is probably not quite... up-to-date at the time. For instance, it includes a WYSIWYG editor which is something we probably don't want to deal right now, and doesn't include stuff like the FAB in Card browser that was supposed to be removed. So much work was done in various parts of the project, and some of it is incomplete or otherwise problematic. It's so easy to miss an important issue when there's just so much going on, so we should start compiling a list of issues and ranking them by urgency as early as possible.

I've removed anything that wasn't a crash or relevant bug (here were the removed issues: #9518, #9002, #9355, #8925, #8307, #7279, #6677, #6562, #6422, #5919, #4944, #6556). And created #13075 for anyone else that wants to add something important to the list, as the FAB removal
