### ISSUE TITLE
Scoped storage: Display number of files on the dialog that warns that sync isn't possible during the migration

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13080]
There is a dialog that warns the user that it isn't possible to sync during the scoped storage migration. Part of it should show the number of files remaining, but it is currently hardcoded to 5 

https://github.com/ankidroid/Anki-Android/blob/0458ee60d6e533d475970bf2e2baefa2bc044a9f/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L2787-L2799

The task is to solve the TODO is display the actual number of remaining files.

**Comment by BrayanDSO** [comment]
As this isn't essential to the actual migration and the string could be modified if we don't have time for this, I'm labeling it as Medium priority

**Comment by lonewolf2208** [comment]
Hey @BrayanDSO I would like to work on this .

**Comment by david-allison** [comment]
@lonewolf2208 Had a discussion on Discord before I saw this and I've assigned this elsewhere, apologies!

Come to our [Discord](https://discord.gg/qjzcRTx) and say 'hi' - I'm back from a break, and I'm looking to strongly push a small number of issues over the finish line so we can release 2.16. Any help would be most appreciated 🙏🙏

**Comment by criticalAY** [comment]
As discussed on discord gist to what to be done : 
1. Make a/Update the current one  material dialog with the string "Sync is disabled until migration is done" alongside with a progress bar
2. The progress bar is updated as the number of files ascend by a random number with `value = min(value, 99%)`

This would be done as the user won't be opening the sync dialog very often during migration and showing the number of files considering the speed to transfer makes no sense as they would be flaky ones as David and Brayan suggested.

We are planning to finish this issue in 4 days.

**Comment by lonewolf2208** [comment]
> @lonewolf2208 Had a discussion on Discord before I saw this and I've assigned this elsewhere, apologies!
> 
> Come to our [Discord](https://discord.gg/qjzcRTx) and say 'hi' - I'm back from a break, and I'm looking to strongly push a small number of issues over the finish line so we can release 2.16. Any help would be most appreciated 🙏🙏

Okay, no issue @david-allison , thanks for letting me know. I would love to contribute in the meanwhile to other issues.

**Comment by oakkitten** [comment]
I suggest removing numbers, or any other progress indicators, from this dialog, for simplicity. It's too much work for little gain. While this should be easy if done right, but still, you'd have to subscribe to & unsubscribe from progress updates. And you'd have to deal with the progress reaching 100% in some way. (IMO, making a non-sticky dialog with buttons silently disappear is not very good UX).

**Comment by david-allison** [comment]
I'm ambivalent, depending on the amount of effort needed.

I've implemented the below in a branch I'll be posting this weekend:
* The Deck Picker needs to subscribe to the service (in order to update the sync icon when the migration is complete
* Getting the progress data in the DeckPicker

We still require here:
* Updating progress (rather than a fixed number)
* Deciding what to do on 'completion'

I mildly like the dialog because it encourages people to leave the app open on the screen. If that happens, the service is less likely to be killed by 'power saving' features that manufacturers put on devices.

**Comment by oakkitten** [comment]
Btw, we can have the progress displayed inside the deck picker migrate toolbar button. Since it's round, you know. Make its background transparent and show the usual circular progress indicator around the edge

**Comment by criticalAY** [comment]
You mean replace the sync icon or display it along with it?

**Comment by oakkitten** [comment]
Along with it. Something like this, although I'd probably just disable the sync icon
![image](https://user-images.githubusercontent.com/1710718/213868675-4937d823-e41f-4977-a331-43b86c1b91aa.png)
