### ISSUE TITLE
Scoped Storage: Update Alpha Build workflow

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13092]
We want to discourage alpha testers from using `com.ichi2.anki` for alpha builds. Alpha testers are the most likely to experience volatility with builds (uninstalls due to crashes etc..), and we should encourage them to have `com.ichi2.anki` as a 'stable' Anki profile, and `com.ichi2.anki.A` (for example) as their alpha build. Alpha users should be more technical and happy with 'don't delete my data on uninstall'. But we want to minimise disruption. Users will make mistakes and we want these to have as little impact as possible
  * Outcome (alpha builds only): Do not supply com.ichi2.anki
     * Use .A for the current build splits (x86/arm/x86_64 etc...)
     * For later: reconsider whether we want to have the 'non-universal' builds as first-class citizens - I intuit this produces more confusion than benefit - maybe move them into a zip, or move to the bottom of the list (if feasible)?
  * This will not affect release or beta builds

**Comment by BrayanDSO** [comment]
I’ll do this together with #12955

**Comment by david-allison** [comment]
I'm happy to move the 'for later' into a non-blocking issue to be resolved after 2.16 if this is a long process (& if you feel appropriate)

The ideal is to move back to Play Store distribution ASAP - which means fewer users are relying on GitHub + the confusion caused by architectures.

**Comment by BrayanDSO** [comment]
I’ve reconsidered this to the point that I don’t think this is a good idea

My main concern is about the possibility wanting to migrate from an alpha to a newer stable release, either from GitHub or Play store. Using `com.ichi2.anki.a` forces the user to install from GitHub and forces us to keeping releasing parallel builds, and I expect that some day when Profiles are implemented parallel builds should be removed.

Right now I think that if the user wants to uninstall the app while keeping their data, they can simply tap the “Keep data” box when uninstalling. This would allow them to downgrade or upgrade the app in a much more free way and stop being hostage of parallel builds.

**Comment by david-allison** [comment]
I'm happy to close this as completed.

I suspect we'll reduce, but won't remove parallel builds once profiles are implemented. 

But if we choose 'remove', this choice would block it.

I would like to more strongly encourage alpha users to keep a separate collection. I'd be happy to do this via text, or order of build artifacts.
