### ISSUE TITLE
Storage Migration: Improve Deck Picker icon

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13095]
Context: Once we move to 2.16 we need to move the user profile folder. 

This is a complex operation:
* a user may have ~20+GB of nested data
* Copying is slow
* Android background processes have problems
* Android doesn't provide helpful APIs 

We define:
* **safe storage/legacy storage**: A folder on the Android device which previously would not be deleted after uninstall (safe). Due to Android changes, this folder is now slow. And after AnkiDroid 2.16:
   * new users will be unable to use this folder
   * old users will be able to use this folder until they uninstall the app, after which the folder will be inaccessible from. AnkiDroid
* **unsafe storage**: The folder that we will use with AnkiDroid 2.16. Android will offer to delete this folder on uninstall, wiping both user data and backups
* **storage migration**: the process of copying data from a 'safe storage' location to 'unsafe storage'
* **Deck Picker**: Main screen of AnkiDroid
* **safe folder** a folder which is not deleted on uninstall

----

1. When an existing user starts the app, we want to inform them that they have 'legacy storage' and they need to upgrade.
2. If a user declines, we want an icon for them to press to continue the process
3. We can backup to a **safe folder**, but we cannot run AnkiDroid from a **safe folder**
4. If we annoy the user enough that they uninstall the app, we've lost our chance to migrate and need to handle this via complex user support (or losing users). We don't want this. Users don't want this.

**Use cases of the icon**
* If a user is neither backing up, nor syncing, we want to warn them that uninstalling will make data inaccessible, and pressing an icon to press to offer suggestions to fix it.
* If a user is eligible for a storage migration (user has backups/is syncing), a user may 'postpone' a storage migration, in which the icon reminds them that this has been postponed.

In 55275ef89daf539592bb3d78321b55fc00c98979 / https://github.com/ankidroid/Anki-Android/pull/12648 we introduce `ic_migrate`.

But in my mind, this icon does not indicate the use cases. In addition, white on yellow is not a good color scheme.

A proposed flow for this process has been added: https://www.figma.com/file/nkm1EXmPUUALwXLAzyWQJd/Scoped-Storage-Migration?node-id=0%3A10#281762514

I have also added some thoughts on the [previous pull request](https://github.com/ankidroid/Anki-Android/pull/12648)

We need someone to take ownership of a good icon to display to the user, and to think hard about the use cases and flow which are proposed to see how they can be improved from a UX perspective

![Screenshot 2023-01-10 at 20 59 23](https://user-images.githubusercontent.com/62114487/211661385-2f7dc5be-6aef-4655-8657-e4a0d7bc3611.png)

**Comment by lonewolf2208** [comment]
Good day, @david-allison  Could you please elaborate how the icon needs to be updated. I want to work on this.

**Comment by david-allison** [comment]
@lonewolf2208 I've expanded on the issue. I've tagged a couple of maintainers on Discord to ensure that my explanation is correct. Expect an 'accepted' tag on the issue within 24 hours, in which case it'll be open for work

**Comment by BrayanDSO** [comment]
IMO, keep using a similar icon with an arrow inside a circle, but use a nice and slightly dark shade of red instead of yellow so we have a good contrast and call the user attention

**Comment by lonewolf2208** [comment]
Hey @BrayanDSO , I experimented with it with a little brighter and more light red colour. Does this seem nice?
![image](https://user-images.githubusercontent.com/72886809/212488699-fa11a629-fa6f-4370-ba8a-60a4ac8c1e1f.png)

**Comment by BrayanDSO** [comment]
I'd make it globally bigger, and would replace the arrow with one with a longer/wider tail

**Comment by lonewolf2208** [comment]
> I'd make it globally bigger, and would replace the arrow with one with a longer/wider tail

Thanks for looking into it @BrayanDSO . But given that it is red. It would be preferable, in my opinion, if it were smaller since otherwise, the user would find it annoying to look at.

**Comment by BrayanDSO** [comment]
I think that it being a little annoying is good. We actually want the user to tap the button and do the migration ASAP

**Comment by lonewolf2208** [comment]
> I think that it being a little annoying is good. We actually want the user to tap the button and do the migration ASAP

Sure . I'll implement the adjustments. Thanks for investigating it
