### ISSUE TITLE
Determine functionality to be disabled when storage migration is in progress

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13094]

**Comment by criticalAY** [comment]
IMO if the migration doesn't take more than just few minutes (2-3mins at maximum) we can disable it and warn the user not to exit the application while the process is ongoing

**Comment by BrayanDSO** [comment]
> IMO if the migration doesn't take more than just few minutes (2-3mins at maximum) we can disable it and warn the user not to exit the application while the process is ongoing

I don't think there is an accurate and precise enough way to calculate the time, and someone will exit the app anyway even if warned

**Comment by david-allison** [comment]
When a user opens AnkiDroid, they want to review. We shouldn't get in the way of this unless we 'have' to. All the technical concerns should be as simple as possible to acknowledge, and understand, so a user can return to reviewing. We should not block reviewing and block the minimum amount of functionality possible while migrating storage.

In terms of speed:

* Some users have multi-gigabytes of data in individual files (sound & images).
* There are significant reported slowdowns on some phones. We should assume 'hours' at the worst case.

(30-78x reduction in speed - this will likely still be current on some phones): https://github.com/tliebeck/saftest & https://github.com/JustinTipton/SAFTraversal

**Comment by Arthur-Milchior** [comment]
I suspect "media check" is also a bad idea. API calls should be disabled at least during the migration of essential files. Notifications too, since it can open the reviewer directly. Right now, I can't think of anything more, and don't see how to be exhaustive in my search of features to disable

**Comment by BrayanDSO** [comment]
1. The AnkiDroid directory preference
2. Perhaps the new backend preference

**Comment by david-allison** [comment]
**Advanced Settings**
* AnkiDroid Directory
* BackendV3

**DeckPicker**
* Sync
* Automated Sync (disable)
* Check Database (various)
* Check Media
* Export Collection
* import
* maybe: restore from backup
* maybe: empty cards

**ManageSpace**
* Delete Unused Media Files

**API**
* TBC
