### ISSUE TITLE
[Bug] JS API: AnkiDroidJS.ankiTtsSpeak(text) should strip/ignore html

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#13107]
I'm attempting to make a replay tts button on a template:

###### Reproduction Steps

1. Create a Basic note type with a template as so:
``` 
<!-- initial tts when the card is rendered on AnkiDroid -->
<tts service="android" voice="en_US">{{Front}}</tts>

<!-- initial tts when the card is rendered on Anki desktop -->
<span class="ankitts">{{tts en_US:Front}}</span>

<!-- TTS replay button on AnkiDroid -->
<button class="ankidroidTtsButton" onclick="
AnkiDroidJS.ankiTtsSpeak('{{Front}}');">Play TTS</button>
```

2. Create a note of this note type with a Front field containing:
```
Test front 1 <b>2</b> 3
```

3. Review the resulting card. When initially rendering the card, the tts service will correctly read `Test front 1 2 3` and ignore the b html tags. The replay button using the JS API will incorrectly read out the element: `Test front 1 less than sign b greater than sign 2 less than sign slash b greater than sign 3`

###### Expected Result
The same behavior as when using the tts HTML tags: embedded HTML elements shouldn't be read by `ankiTtsSpeak()`.

###### Actual Result
embedded HTML elements are read

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha92

Android Version = 11

Manufacturer = Google

Model = Pixel 2

Hardware = walleye

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 2 Build/RP1A.201005.004.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = edb11ce0-7c90-482d-9915-9e02591297f0

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by sudomain** [comment]
Related: the ankiTtsSpeak() will continue reading text it was given when going back to the deck list, unlike the html <tts> tags which will stop reading of going back to the deck list

**Comment by dae** [comment]
With 2.17 standard Anki TTS tags will be supported, which should handle this correctly. I'm not sure what the AD devs want to do with the AnkiDroid-specific TTS tags.

**Comment by david-allison** [comment]
@krmanik 

Just so you're aware of a user request, I expect this is blocked on TTS

We're going to be deprecating `ReadText` reading the entirety of the card in a few versions maximum (ideally starting to warn users in 2.17, probably removing in 2.19)

We're still going to support TTS via `{{tts}}` and there's nothing stopping us from sending arbitrary input into the TTS Engine

This seems like a reasonable request: a user wants an API for TTS to read out field contents in the same way that `{{tts <options>: Front}}` would

**Comment by krmanik** [comment]
Then JS API for TTS also needs to be upgraded.

**Comment by sudomain** [comment]
Please tag "keep open"

**Comment by krmanik** [comment]
I will create PR to fix this issue later which update JS API.
