### ISSUE TITLE
add pause option for audio while playing

### ISSUE THREAD

**Issue by JaziTricks** [ankidroid/Anki-Android#13125]
when the audio is long, it's sometime useful to be able to pause (I'm using a deck with semi long audios)

adding a pause button in first shown card if audio can be very helpful. 

thanks all contributors!

**Comment by SanjaySargam** [comment]
I think we can pause the audio in Reviewing cards.

**Comment by JaziTricks** [comment]
> I think we can pause the audio in Reviewing cards.

not in my android phone. checked 3 different decks, none has a pause showing
unless it differs by deck settings and what not....


thanks :)

**Comment by SanjaySargam** [comment]
![WhatsApp Image 2023-01-18 at 9 37 14 AM](https://user-images.githubusercontent.com/65113071/213081404-1a9554ca-2079-4fa0-b057-72c7f8370be4.jpeg)
We can pause audio by clicking again on the play button

**Comment by JaziTricks** [comment]
not on my phone. clicking in play mid audio, restarts the audio rather than pausing it.

I notice the layout is different too

![Screenshot_2023-01-18-10-52-05-590_com ichi2 anki](https://user-images.githubusercontent.com/108614606/213140017-a490e78f-2a3d-498b-af5b-98bcd06d9457.jpg)

**Comment by SanjaySargam** [comment]
No, the layout is same. 
And it's work for me

**Comment by khawaja0** [comment]
@JaziTricks What version are you using? The latest version of AnkiDroid from the Play Store (2.15.6)?

When I use AnkiDroid 2.15.6 (on a Pixel 6a with Android 13), I have the same problem. If I click on the play button while audio is playing, it does not pause. It restarts. But I know that pausing audio was implemented for the as-yet unreleased 2.16. Look here: [https://github.com/ankidroid/Anki-Android/pull/8781] #8781
If you're not running the 2.16 code, then hopefully when 2.16 is released and you update from the Play Store we'll all have access to this feature.

**Comment by JaziTricks** [comment]
@khawaja0 I'm using the playstore latest. 2.15.6

thanks! 

I suppose this thread should be closed as it's too be implemented in the next release already

**Comment by Wizek** [comment]
This still seems to be an issue (again?) 2.16.4. Is this expected?

**Comment by snowtimeglass** [comment]
This is expected behavior in 2.16.4. 
https://github.com/ankidroid/Anki-Android/issues/14221
https://github.com/ankidroid/Anki-Android/pull/14296

It is also consistent behavior with Anki Desktop and AnkiMobile.

I think that the idea itself of adding pause option for audio is appropriate. Both Anki Desktop and AnkiMobile have the option.

**Comment by Wizek** [comment]
@snowtimeglass Ah I see. Would downgrading to 2.15.x or 2.14.x in the meantime just via the APK be safe if the pausing is important?

**Comment by snowtimeglass** [comment]
@Wizek  I don't think it will be effective. I suppose that in the versions the button works the same as it does now. 

Perhaps in 2.16.3 the button works as you expect.
