### ISSUE TITLE
STOR-04: Design an icon for 'sync is disabled'

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13129]
https://github.com/ankidroid/Anki-Android/blob/0458ee60d6e533d475970bf2e2baefa2bc044a9f/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L715-L717

If sync is disabled due to a storage migration, we want to inform the user that this is occurring.

It is planned to display the progress of the storage migration if the icon is pressed when in this state

**Comment by criticalAY** [comment]
Heyoo!
