### ISSUE TITLE
START OF NEXT DAY ISSUES

### ISSUE THREAD

**Issue by GeoMD** [ankidroid/Anki-Android#13120]
In Ankidroid v2.16alpha92, When start of new day reaches, the cards don't change to another day, it continues from previous day and i don't get new cards unless i sometimes synchronise with desktop anki, but either way number of reviews does not change.

How can i fix this, kindly help

**Comment by pilgrimlyieu** [comment]
I meet it too.

**Comment by dae** [comment]
This will hopefully be resolved in the next alpha once the backend gets updated.
