### ISSUE TITLE
[Bug] Two settings of backup

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#13121]
###### Reproduction Steps

There are two settings of backups.
1. Settings - Advanced - Max number of backups
![Screenshot_20230114_092846_AnkiDroid.png](https://user-images.githubusercontent.com/10192661/212463811-42995945-bf1a-4257-93fb-e5786a9d3a4d.png)
2. Manage space
![Screenshot_20230114_092927_AnkiDroid.png](https://user-images.githubusercontent.com/10192661/212463821-7004fc14-8988-4200-8501-2fe53c5fa7fd.png)

It seems the second one is functional.

###### Expected Result
1. One setting only.
2. The setting of backup is accessible from the settings in the app. 

###### Actual Result
1. Two different settings.
2. Users will not find the setting of backup in the Manage space screen (separated from the other settings).

###### Debug info
AnkiDroid Version = 2.16alpha92

Android Version = 13

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = 139fc465-1882-4a0c-9b4d-43bfab0f2701

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Task here is to create a new preferences top category called “Backups” if the new backend is enabled showing those options

**Comment by Fazil29** [comment]
@BrayanDSO can we elaborate what needs to be done here?

**Comment by BrayanDSO** [comment]
AnkiDroid has a setting called "Use the new backend". By enabling it, we get access to Anki's newer features such as more backup settings. So we need to implement the "frontend" for those settings if the new backend is enabled. This has been done on the manage space activity (the one you can get access on the Storage section on the system settings of the app), but not on the in-app settings (the one you access by tapping "Settings" on AnkiDroid navigation drawer).

So the task is:
1. Create a new top category on the settings screen (like General, Sync, Appearance, Controls, etc)
2. Only show it if the new backend setting is enabled
3. Reuse those settings from the manage space activity and show them on the new category

**Comment by SanjaySargam** [comment]
@BrayanDSO Is this necessary that we must have Android version 13 to access Manage Space option ?
