### ISSUE TITLE
Don't re-render full document when showing back

### ISSUE THREAD

**Issue by fylux** [ankidroid/Anki-Android#13128]
AnkiDesktop only re-renders the #qa element when showing the back according to https://forums.ankiweb.net/t/avoid-rendering-webview-twice-front-and-back/24937/2. This allows to inject content outside of #qa for it to persist in the back, allowing to do some optimizations. For example, if I have a progress bar, I don't need to render the progress bar twice what often will not look smooth since it will disappear for a few ms. It would be great if AnkiDroid would follow the same approach as AnkiDesktop in this regard.

**Comment by BrayanDSO** [comment]
I've tried to inject HTML before and I confirm this

**Comment by BrayanDSO** [comment]
Will be solved with #14302

**Comment by fylux** [comment]
Just to confirm, does this mean that then the behavior of the HTML will be the same as in Anki Desktop? At least regarding the HTML elements that get rewritten?

**Comment by BrayanDSO** [comment]
That's the goal
