### ISSUE TITLE
STOR-05 Simple UI element for when the migration is completed

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13131]
* This may occur when the user has the app closed 

Accepted Proposal: Toast + Notification

**Comment by lonewolf2208** [comment]
Hey @david-allison , I would like to work on this issue .

**Comment by criticalAY** [comment]
> Hey @david-allison , I would like to work on this issue .

Though I mentioned David on Discord to assign it to me but are you aware of the Discord discussion we had? like the toast and notification use case?

**Comment by lonewolf2208** [comment]
I'm not very active on Discord, @criticalAY , So if you aren't working on it, I may listen to your Discord conversation and implement as necessary.

**Comment by criticalAY** [comment]
If you want to work on it I have no issue but would like you to go through the discord conversation about STOR-05

**Comment by lonewolf2208** [comment]
Sure , Thanks for informing @criticalAY .

**Comment by david-allison** [comment]
I can't assign an issue unless it's been commented on - let me know who'd like it and I'll assign

**Comment by criticalAY** [comment]
> I can't assign an issue unless it's been commented on - let me know who'd like it and I'll assign

@lonewolf2208 are you aware of what is needed to be done here now ? Otherwise I'll take it up

**Comment by lonewolf2208** [comment]
You can go ahead with it @criticalAY .

**Comment by criticalAY** [comment]
Ok thanks! @david-allison Please assign it to me

**Comment by oakkitten** [comment]
I would suggest all of the following:
* If the app has any started activities, show a success dialog;
* If app is not visible, show a success dialog when user gets back to it, even if it stopped;
* If migration progress was shown as a notification, do not dismiss that notification on completion and instead make it show success, and make it dismissible. Also, probably change the icon to indicate that migration has finished. (Or failed!)

**Comment by criticalAY** [comment]
>If the app has any started activities, show a success dialog

I can agree with toast or the success dialog

>If app is not visible, show a success dialog when user gets back to it, even if it stopped;

Not in favour of this one as showing the notification once the migration is complete makes more sense and clicking the success notification should take us to the app itself dismissing it or user can dismiss it after reading it without clicking it to redirect to app

**Comment by oakkitten** [comment]
Toasts are very easy to miss. Notifications are harder to miss, but it's still easy to inadvertently dismiss a notification. I think it's important to have a very clear and unmissable confirmation that migration has completed.
