### ISSUE TITLE
[Bug]2.16alpha92: lag when scrolling a note and gradual performance degradation when reviewing

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#13132]
###### Reproduction Steps

1. install  2.16alpha92
2. review a deck with 20+ cards and at least one card with a lot of text that requires scrolling

###### Expected Result
No lag when scrolling and no gradual performance degradation 

###### Actual Result

 Lag when scrolling a note and gradual performance degradation when reviewing (with each review, Anki becomes slower until it's really annoying, > 3-5secondes delay).

###### Additional information

Based on these [two](https://github.com/ankidroid/Anki-Android/issues/12980) [issues](https://github.com/ankidroid/Anki-Android/issues/12034), I have removed all my "font-family" CSSrules (but kept the "font-size" ones) and I have updated to the [latest beta web-view](https://play.google.com/store/apps/details?id=com.google.android.webview.beta). But I still experience a lag on scrolling and a gradual performance degradation. Exiting the review and reopening reset the performance lag. 

Without modifying anything else, I have downgraded to 2.16alpha91 and I don't have any lag or decreasing performance. I have then reinstalled 2.16alpha92 and the bugs are back. 

I am opening a new issue as this problem is really specific to 2.16alpha92 and not solved by the solution mentioned in the two other issues.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

This is the debug when I was on 2.16alpha92:

AnkiDroid Version = 2.16alpha92

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.29 Mobile Safari/537.36

ACRA UUID = 558d8332-b5e1-48c7-b893-93de78759e5e

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by daddydave** [comment]
I've noticed this as well. As a workaround, I will go to the home screen and hit the Sync button and then review card speed seems to go back to normal. Maybe this would happen if I didn't hit the Sync button too, I just usually hit it out of habit.

**Comment by dae** [comment]
If one of you is able to build AnkiDroid from source, it would be helpful to know which of the changes in .92 is responsible:

https://github.com/ankidroid/Anki-Android/compare/v2.16alpha91...v2.16alpha92

You could find that out by bisecting (trying a change around the middle, seeing if it's broken, and then trying other changes to narrow it down): https://git-scm.com/docs/git-bisect

If you don't feel comfortable doing that, please try to boil the issue down into minimum steps/time to reproduce, provide an .apkg to test with, and then we can label this as a good first issue for volunteers to try to isolate the cause.

**Comment by daddydave** [comment]
Thanks, I will give the first suggestion a shot, as time permits. The second suggestion I can definitely do, I will work on getting minimum steps and attach a version of my deck here after trying to correlate number of reviews with degree of performance degradation. By the way, speaking for myself, I am running a little low on internal space on my phone, so now I am curious if I can reproduce this slowness on an emulator. Also, I realized my cards don't have enough information to scroll, so I wouldn't see any scrolling issue. I do use custom fonts in my style css, too, not sure if that is a factor as well. I'll see if I can screen capture the performance degradation as well.

**Comment by MagTun** [comment]
Sorry, I am not able to build AnkiDroid from source. 
I forgot to add that I tried on a brand-new deck, using the basic note type, without any css or custom HMTL/JS (just a front and a back) and I still got the lag. So, it doesn't depend on a specific deck.  (The scrolling isn't as important and could probably be fixed with fixing the lag between review).

**Comment by daddydave** [comment]
I will try to do the git bisect thing, next week I will have some time and a junk device for testing (I had forgotten how slow the Android Studio emulator was).

In the meantime, I did a couple of videos showing the gradual performance degradation, with my notes and key moments in the description. For me, I think I start seeing it around card 43-54 or so. I don't really have any cards that scroll, hopefully it is the same or similar issue.

Fake Deck (just clicking through like crazy until the problem appears)
https://youtu.be/fuypsn87YwU

Real Deck (me actually studying)
https://youtu.be/ClXMAACcj-c

**Comment by MagTun** [comment]
Yes, I confirm that the lag is when scrolling on a note during a review (the browser also lags but it was always like that so it's not the problem). But I don't have the same problem as you. Your lag seems to be inexistant until suddenly it comes and lasts right away several seconds. My lag starts after a couple of reviews (sometime after only 3-5), and after it's barely noticeable and it increases progressively with each review. 

To really isolate the problem down to the alpha version, I created a new deck with the basic note type and about 20 dummy cards with only simple English text, that I uploaded from a TSV file I created from scratch (I don't remember if I tested the scrolling on this dummy deck). It was enough to notice the lag (maybe because I don't have a powerful smartphone) 

I am sorry I can't investigate this problem at the moment nor can I provide a video of my lag.

**Comment by daddydave** [comment]
Debug info (parallel build I am using for the fake deck)
AnkiDroid Version = 2.16alpha92

Android Version = 10

Manufacturer = motorola

Model = moto g(7) power

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; moto g(7) power Build/QPOS30.85-23-7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.85 Mobile Safari/537.36

ACRA UUID = c3db1482-834a-45a7-ac4b-ca4f56533c1d

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true


~~~
Main install debug info, looks the same except

ACRA UUID = 99a1caac-47da-4d5e-9f15-93d81de2b763

New schema = true

Scheduler = std3

**Comment by daddydave** [comment]
@MagTun  I tried reproducing your scrolling issue using 30 cards for review and about 8 pages of lorem ipsum text and a little formatting, but I had no luck, it all scrolled very smoothly. I might try to add another 30 later and see if I can reproduce my own issue.

**Comment by daddydave** [comment]
Here is my .apkg file. I will try this on my junk phone for testing that is arriving this week as well.
[Fake Urdu Everything Bagel.zip](https://github.com/ankidroid/Anki-Android/files/10531415/Fake.Urdu.Everything.Bagel.zip)

**Comment by daddydave** [comment]
My particular issue seems to be something very specific to my device somehow. I have a Moto G7 Power (2 GB internal space free, I mention this because earlier it was running low on space, but not anymore. My damaged device arrived today, the older Moto G5 Plus, and I was not able to reproduce the issue with 2.1.6alpha92-debug and the apkg above, even with 226 reviews.

**Comment by dae** [comment]
It could possibly be something hardware related like amount of memory or slow flash drive, or possibly Android-OS related. If the bad device performs fine on alpha 91 but not 92, that implies AD's made a change which triggers this behaviour, and knowing which commit caused it may give us a hint.

**Comment by daddydave** [comment]
I did a simple uninstall and reinstall of 92 on my main device, and I am no longer able to reproduce the issue, so it's no longer an issue for me.

**Comment by MagTun** [comment]
Following @daddydave's comment, I also uninstalled Ankidroid and reinstalled 92 and I don't have any lags (I did a 200+ review and not a single lag; also, no lag when scrolling on a long note during a review).
To test if the bug was caused by the update from 91 to 92, I uninstalled 92, reinstalled 91 and then updated to 92, but again I don't have any lags.
@daddydave, thanks for the time you spent on this and for your last comment, otherwise I wouldn't have tried it again!

@dae, I don't know if I should close this issue or not: the bug is real, but a simple solution exists.

**Comment by dae** [comment]
Well, that's a weird one. This issue should automatically expire if people stop commenting on it, so we could leave this open to see if anyone else hits the same issue.

**Comment by FredericOdermatt** [comment]
I've encountered the same behavior after using ankidroid for many years. It seems this issue appeared with an update in the last few months. The reinstall option worked for me too, but I only found this thread because I know a bit how to search through github issues. Might be hard to resolve for people who don't know how to do that

**Comment by MagTun** [comment]
@FredericOdermatt , thanks for your comment. Can you share your AnkiDroid version and the model of your phone?

> it might be hard to resolve for people who don’t know how to do that.

At the same time, people who struggle using GitHub search won’t be installing alpha versions of Ankidroid. But if you have better wording for the issue title, I will be happy to improve it.

In the last few weeks, I tried to update my AnkiDroid from 2.16alpha92 to 2.16alpha98, but I had this lag again. That time, the solution to uninstall and reinstall didn’t work (I tried at least three times), so I went back to AnkiDroid 2.16alpha92. When I wanted to retry before posting a new comment here, I saw that AnkiDroid 2.16.0beta1 came out. So, I installed it and since then, I don’t have any lag anymore (I didn’t have to uninstall Anki for this beta update)

**Comment by FredericOdermatt** [comment]
> At the same time, people who struggle using GitHub search won’t be installing alpha versions of Ankidroid

Hey, that's a really good point: the issue was appearing for me starting from this spring in a _beta_ version downloaded from the google play store. Unfortunately I'm not using auto-update, so I can't pinpoint the exact beta version change that made this issue start for me as I also updated in early spring for the first time in maybe 6 months and that is when I first started to notice the lag. The problem has not resurfaced after the reinstall even with heavy usage over the past week.

**Comment by MagTun** [comment]
I didn't know this bug where also in a beta version. I have been using alpha version for a while now and I don't see any new beta versions in the last months (https://github.com/ankidroid/Anki-Android/tags) except the one that came out 2 weeks ago. I am not using google play updates for Ankidroid, so I don't know how it works there.
