### ISSUE TITLE
[Bug] Low performance when scrolling notes in Card browser 

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#13133]
###### Reproduction Steps

1. Have approximately 7000 notes
2. Open Card browser 
3. Options - Notes - OK
3. Scroll down quickly 

###### Expected Result

The performance is the same as when scrolling cards

###### Actual Result

The performance is worse. Scrolling cards in Card browser is OK.

###### Debug info
AnkiDroid Version = 2.16alpha92

Android Version = 13

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = 139fc465-1882-4a0c-9b4d-43bfab0f2701

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by JagrutThakare** [comment]
I want to work on this issue can you plz assign this to me.

**Comment by satvik2131** [comment]
I understood the issue , it can be optimized by realtime loading the flash cards or by loading the flash cards in chunks according to the screen
