### ISSUE TITLE
Developer option to fill the database

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13141]
To solve this issue we need:
* in the developer options, a setting "fill the collection"
* when the user tap on it, it creates a series of card, let's say, card `n` contains as question the number `n` and as answer a link to a svg containing only the `<text>n</text>`,
* (and so we need to create medias entries for all of those [svg](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text))

The goal will be to manually create collection so that it's simple to see whether our migration tools worked as expected.

**Comment by Shaky-Sahil** [comment]
Hi Arthur, I am excited about the opportunity to work on resolving this issue as Anki is an app that I frequently use. Although my expertise lies primarily in web development, I do have some experience with Java which could come in handy. Based on my skillset and experience, do you believe that I would be able to solve this issue? I am eager to take on this challenge and try my hand at android development.

**Comment by oyeraghib** [comment]
@Shaky-Sahil you should definitely go for this issue. You can even ask questions on our [Discord](https://discord.gg/N2N5vcwv) if you get stuck anywhere. Thanks!!

**Comment by Shaky-Sahil** [comment]
> @Shaky-Sahil you should definitely go for this issue. You can even ask questions on our [Discord](https://discord.gg/N2N5vcwv) if you get stuck anywhere. Thanks!!

Thank you! 
I have a couple of questions :
Should I only start once the issue is assigned to me or can I go ahead and begin? 
Since this is a high-priority issue is there some deadline that I'm expected to meet? Thanks in advance.

**Comment by criticalAY** [comment]
> > @Shaky-Sahil you should definitely go for this issue. You can even ask questions on our [Discord](https://discord.gg/N2N5vcwv) if you get stuck anywhere. Thanks!!
> 
> Thank you! I have a couple of questions : Should I only start once the issue is assigned to me or can I go ahead and begin? Since this is a high-priority issue is there some deadline that I'm expected to meet? Thanks in advance.

You can start working on it :) There is no deadline as such

**Comment by Arthur-Milchior** [comment]
Hey, thanks everyone for answering questions while I was away.
@Shaky-Sahil You can start working on it. 
You may want to know it's some Kotlin. Even if it should not be too hard for a java dev to discover it.

While I can't give a specific deadline, it must be done some time in February, as I expect we'll need it to test scoped storage migration, and this one, for sure, we'll need it in March

**Comment by MudssirAhmed** [comment]
Hey @Arthur-Milchior, I'm starting to work on this issue, Can you guide me a little bit, What I need to remember and what not.
Thank you!

**Comment by criticalAY** [comment]
@MudssirAhmed Please note this issue is already assigned.

**Comment by MudssirAhmed** [comment]
@criticalAY sorry I missed it, Thank you for correcting me.

**Comment by iamryuga** [comment]
is somebody working on this ?

**Comment by Shaky-Sahil** [comment]
Hi @Arthur-Milchior I cannot follow through on completing this issue can you please reassign this issue to @iamryuga.

**Comment by Shaky-Sahil** [comment]
> is somebody working on this ?

You can start working on the issue if you'd like to.

**Comment by iamryuga** [comment]
okay i'll like onto it .

**Comment by iamryuga** [comment]
assign it to me please

**Comment by iamryuga** [comment]
(and so we need to create medias entries for all of those [svg](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text)) 
what is the meaning of this line ? can somebody please explain

**Comment by iamryuga** [comment]
if i am understanding this correctly then when tapping the button "fill the collection a menu pops up that asks  the user to enter numbers and we need to create a link to svg containing  <text>n</text>

**Comment by dipankarupd** [comment]
Hey! It seems like nobody is working on this issue. Can I try to solve it?
Thank you

**Comment by iamryuga** [comment]
Hi @dipankarupd  currenly I'm working on it .if i am not able to , I'll tell you .

**Comment by dipankarupd** [comment]
Oh didn't know about it. It's okay sir. Please continue :)

**Comment by RahulTulsani** [comment]
i want to work on this issue please assign me this issue

**Comment by doozan** [comment]
> (and so we need to create medias entries for all of those [svg](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/text)) what is the meaning of this line ? can somebody please explain

You need to create individual .svg files as the media for each card. svg files are just xml files with a .svg extension so they're pretty easy to create, just putting ```<text>n</text>``` as Arthur suggested should work. When viewing the card you should see an image with the card number.

**Comment by Arthur-Milchior** [comment]
Thanks @doozan , it seems you perfectly understood the requirement.

@RahulTulsani you can potentially just open a svg editor such as inkscape (it's free), and create a small image 4.svg with the number 4 in it only. Then open this with a text editor such as emacs, gedit, android-studio should work to. You'll see how it done. Replacing `4` by another number in the text will directly create another image.

Please note it may not be merged. It'll be used for manual testing, but we may not want it in the main branch of the app. So I suppose it is possible it'll just remain an extra branch that can be used when needing to test a real database

**Comment by IamAbhinavSINGH** [comment]
Hi there,

I hope you're doing well. I noticed that this issue is currently assigned to @thisisme-shivam . I'm interested in contributing to this project and was wondering if you're still working on this issue.

If you're not actively working on it, I would be happy to take on the task. I have experience in Java and a basic understanding of Kotlin, which I believe will be helpful in addressing this issue.
