### ISSUE TITLE
`ACTION_OPEN_DOCUMENT_TREE` in developer options

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13147]
This issue is solved when:
* in the settings, in developer options, there is a new entry called "Give folder permission" (the string should be hard coded right now, as it's only a test, and it's not clear we'll want to release it)
* when the user tap this setting entry, AnkiDroid uses `ACTION_OPEN_DOCUMENT_TREE`.
* the app retains permission to read and write in the returned folder, as explained [here](https://developer.android.com/training/data-storage/shared/documents-files#persist-permissions)

The part above tell us what you need to do. Below, I explain the reason why I want this feature, but you don't need to understand everything below to start implementing this.

The goal is to test an idea from @oakkitten in #13134. If you install a new version of ankidroid targeting SDK 30, as in c1497bd57e338f2a6e029d259e210d962f60b389, you won't be able to access the collection that is saved on ~/AnkiDroid.
To solve this issue, we want to check whether just giving permission through  `ACTION_OPEN_DOCUMENT_TREE` would be enough. It would be wonderful, as it would allow us to keep using `File` instead of being forced to relying on `DocumentFiles` (as those can't be used to open the database)

In practice, it would mean that if the user change the folder to `/storage/emulated/0/AnkiDroid`, we finally can open this collection. If it works, we could automate this in a future issue.

**Comment by ParthTagalpallewar** [comment]
Hello @Arthur-Milchior, I am a beginner to community and am interested in working on this issue, can you please assign this work to me so that I can start working on it?

**Comment by Arthur-Milchior** [comment]
@ParthTagalpallewar nice to meet you. Done. Do you believe you understand what you have to do? Ideally, it'd be nice if it work next week-end so we can do test with it quickly.

**Comment by ParthTagalpallewar** [comment]
@Arthur-Milchior  Please Correct me if I am wrong.
1. I need to create  "Give folder permission", and Hardcoded Entry in DeveloperOption Tab in Settings.
2. Then Handling Click of that String and send Intent like
   Intent(ACTION_OPEN_DOCUMENT_TREE).apply {
            startActivityForResult(this, 1)
   }
To get permission to read and write to the folder chosen by the user.

Please add things that if i missed any.

**Comment by narendraanjana09** [comment]
Hello @Arthur-Milchior ,
I have completed the work on the "Give folder permission" feature as requested. I have added a new option in the developer options that allows the user to select a folder and grant the app permission to read and write to that folder. I have raised a pull request for it where I have also described all the things that I have taken care of while resolving the issue, please take a look and let me know if you need any further changes or if it is ready to be merged.
Thank you

**Comment by ParthTagalpallewar** [comment]
Thank you @Arthur-Milchior for assigning me this issue. I added 'Give Folder Permission' in Developers Options under settings, after clicking on this, allows the app to grant to read and write to the folder chosen by the user, please take a look and let me know if there are any further changes needed, or if it is ready to merge.
Thank you

**Comment by Arthur-Milchior** [comment]
Thank you both of you. Sorry that this was duplicated work. Given that I indicated it was a high priority, I appreciate that you were quick to do it.

At best will merge a single one of them. In future case, @narendraanjana09 , it'd be nice to ask to be assigned work, to ensure you don't duplicate work with someone else. I hope you didn't lose to much time on it :(

**Comment by narendraanjana09** [comment]
Hey, @Arthur-Milchior 
I Apologize for the confusion on the assigned issue. My mistake as a beginner, I assure you that I will be more careful in the future and will make sure to communicate first to avoid any confusion.
Thank you for your understanding.

**Comment by Arthur-Milchior** [comment]
No issue on my side, really. I'm just sorry for both of you because that's duplicated work that could have been avoided.
On the other hand, given that I had hope it may help with important feature we need quickly, I really appreciate the quick PR.
