### ISSUE TITLE
Set back collection folder to default value


### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13150]
In the advanced settings, below the text field for ankidroid folder, please add a button that sets the folder back to it's default value.

# Bug report

Here is the bug report causing this need:

1. open the advanced settings
2. Tap on the Folder. You should see something such as `/storage/emulated/0/Android/data/com.ichi2.anki/files`
3. change the last words. E.g. replaces `files` by `f`

Now you get a whole new profile. You currently have no way to find back all of your data, unless you recall that the original value was `files` and you manually enter it back. Or unless you enter a value that is so wrong that a folder can't be created, leading to the offer to reinitialize this value.

Even reinstalling the app, the wrong preference is recalled.

**Comment by BrayanDSO** [comment]
After scoped storage, will we be able to change the AnkiDroid directory? Because AFAIU, the legacy storage approach isn't feasible, according to David's and oakkitten's investigation (#13134)

**Comment by Arthur-Milchior** [comment]
To be honest, it's not a scoped-storage issue. It's an issue with current version. I changed the folder. The new folder was recorded, but can't actually be opened. And now my ankidroid installation is broken until I put back the right folder information. I admit I don't know the right folder information by heart to be in scoped storage. So being able to put back the default value is useful.

Also, even if we remain in scoped storage, until the day where we actually have multiple user profile, moving to a different folder inside scoped storage may still be useful for advanced users.

**Comment by ParthTagalpallewar** [comment]
Hello, @Arthur-Milchior I read this carefully and am interested in working on this issue. Please Assign me this task so that I can start working on it. Thank you

**Comment by Arthur-Milchior** [comment]
Assigned

**Comment by david-allison** [comment]
> The new folder was recorded, but can't actually be opened.

What do you mean by this? What's the path and what's the issue?

**Comment by Arthur-Milchior** [comment]
I added a bug report with a list of steps to create the issue and why it was hard to fix manually. Hoping it makes it clearer.

**Comment by ParthTagalpallewar** [comment]
Thank you @Arthur-Milchior for assigning me this issue. I added 'Reset Directory Path' in Advanced Settings under settings, after clicking on this, the path of the directory gets changed to default, please take a look and let me know if there are any further changes needed, or if it is ready to merge.
Thank you

**Comment by thakuratul2** [comment]
I want to work on this issue please assign me.

**Comment by thakuratul2** [comment]
oky close it
