### ISSUE TITLE
Revamping the UI of decks shown on home screen

### ISSUE THREAD

**Issue by prabs3257** [ankidroid/Anki-Android#13164]
Currently the decks on the homepage are shown as just textual list with few numbers. This downgrades the user experience of the whole app and is not very intuitive in itself.

My solution would be to replace the textual list with a more graphic list where an image of notes placed in a deck would represent each deck. this would provide the users a more intuitive experience

**Additional context**

![Screenshot_2023-01-29-14-28-24-054_com ichi2 anki](https://user-images.githubusercontent.com/73053857/215316120-3cc5a610-7fff-453a-86a9-cbc45d566167.jpg)

**Comment by prabs3257** [comment]
i am new to anki-android community and i would like to start my journey with contributing to this issue, can i work on this issue ?

**Comment by prabs3257** [comment]
@Arthur-Milchior

**Comment by lukstbit** [comment]
Thanks for creating the issue. 
In the near future we have other development priorities regarding app functionality and not UI changes.
In order for your proposal to even be considered you need to provide more details about the UI revamp(it's not clear for me what would actually go inside that new image of a deck). The current screenshot is not very helpful to understand the proposal, you need to provide images for before and after the change, screen shots for different types of cards, opinions about the difference in performance between text and images etc.

> This downgrades the user experience of the whole app and is not very intuitive in itself.

Why do you feel the current UI downgrades the experience in the whole app when we are similar to the desktop app to which a lot of the users are already familiar with?

**Comment by david-allison** [comment]
Thanks! Please see: https://github.com/ankidroid/Anki-Android/wiki/User-Interface-contribution#what-about-big-changes-

This isn't on our roadmap currently. I'd be open to a plan/discussion/implementation once you've contributed to the repo for a while and have a planned UI which doesn't impact current users of the app (for example: how do you select subdecks in a card-based UI).

I suspect this discussion will take significant time away from other planned priorities of the project, so I'm closing it as WONTFIX (for now). We have a large number of open issues, and I'd strongly welcome contributions to these.

Thanks again for taking an interest!
