### ISSUE TITLE
Add a monospaced Font

### ISSUE THREAD

**Issue by samtrot** [ankidroid/Anki-Android#13165]
Please add a monospaced dont, so that  for example I and l are distinguishable.

**Comment by daddydave** [comment]
You can use whatever font you want. Easiest way is to do from desktop Anki and sync so that it will be picked up by AnkiDroid.

https://docs.ankiweb.net/templates/styling.html?highlight=Font#installing-fonts

**Comment by david-allison** [comment]
Closing as answered (thanks!). We already support arbitrary fonts in the reviewer, and for the UI.
