### ISSUE TITLE
[Bug] `deckPath` location should be in a subfolder of `files`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13169]
It is the root of `/files`, should be `/files/AnkiDroid`.

The latter location allows for multiple profiles in an obvious manner

**Comment by BrayanDSO** [comment]
Unless you just want to solve it yourself, a little more context would be nice.

**Comment by david-allison** [comment]
The default path is `/storage/emulated/0/Android/data/com.ichi2.anki.debug/files`

It should be `/storage/emulated/0/Android/data/com.ichi2.anki.debug/files/AnkiDroid`

This allows multiple folders in the `files` directory, which will be useful for when we implement profiles.
