### ISSUE TITLE
Reset to Default button in App bar button doesn't show warning..

### ISSUE THREAD

**Issue by LCB2021029-Badri** [ankidroid/Anki-Android#13174]
**Is your feature request related to a problem? Please describe. **
App bar buttons doesn't show warning when "Reset to default" is clicked.

**Describe the solution you'd like**
Dialog showing "Do you want to proceed. Yes/No"

**Describe alternatives you've considered**
enabling undo button to restore previous settings.

**Additional context**
i would like to get permission to work on this issue.

https://user-images.githubusercontent.com/96579549/215783706-70ee8129-abff-47ec-af80-101b958d6b7b.mp4

**Comment by BrayanDSO** [comment]
Go for it 👍

**Comment by LCB2021029-Badri** [comment]
Sure, thanks for the permission

**Comment by LCB2021029-Badri** [comment]
I am new to open source, so sir, can you please confirm if the pr has been made?
![Screenshot (27)](https://user-images.githubusercontent.com/96579549/216097450-b92712eb-9af5-49b5-b9de-91906e828762.png)

**Comment by criticalAY** [comment]
Yes, It was made, I review it but you deleted the repo so it's closed now #13179

**Comment by LCB2021029-Badri** [comment]
@BrayanDSO @criticalAY
i've created new strings for the alert dialog, do i need any special permissions to make this PR?

**Comment by criticalAY** [comment]
Nope

**Comment by SanjaySargam** [comment]
@LCB2021029-Badri Are you working on it?
If No, I would love to work on this
