### ISSUE TITLE
Ankidroid Bug

### ISSUE THREAD

**Issue by anaisbuser** [ankidroid/Anki-Android#13192]
AnkiDroid Version = 2.16alpha92

Android Version = 12

Manufacturer = samsung

Model = SM-T733

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-T733 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.85 Safari/537.36

ACRA UUID = fe9e9af5-693a-42f2-8316-54a59d34f161

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

https://drive.google.com/file/d/1aH_H1dTah07A-JPWn8mu3sKyAsiSmRYC/view?usp=sharing

**Comment by lukstbit** [comment]
Please fill all the sections of the bug report template. Without clearly describing the bug and reproduction steps we can't really help.

**Comment by anaisbuser** [comment]
Hey, thanks for the response. I'm not sure what informations you need.. I apologize, I am not very familiar with all of this.. I simply copy pasted the bug report from my AnkiDroid App, is there something else I should do?

**Comment by lukstbit** [comment]
> I'm not sure what informations you need

We need you to tell us what is the faulty behavior, right now you just mentioned "Android Bug" and added a debug info + a file link?! and we can't really do anything with this. 

So you need to tell us what's happening(ex app crashing when I do x, app has unexpected behavior when doing y etc) and also how we can reproduce the failure(for example, if the app is crashing mentions the step to see the failure: like you open the menu on screen A, select option Z and then the app crashes).

**Comment by anaisbuser** [comment]
Thank you for answering. 
My AnkiDroid was showing an error everytime I opened it, but it seems to be working again after I cleaned the cache and cleaned the app. I'm really sorry for taking up some of your valuable time. Thank you!
