### ISSUE TITLE
IMAGE ERROR

### ISSUE THREAD

**Issue by reached01** [ankidroid/Anki-Android#13194]
###### Reproduction Steps

1. I have faced a lot of times with this image error.
2. I am using anki doodle, anki image occlusion and directly adding images.
3. I have checked date base, synced media with one way and checked media.
4. I can not find any solution from internet.
5. I am only using ankidroid. Not web or pc format.

![Screenshot_2023-02-05-12-08-52-329_com ichi2 anki](https://user-images.githubusercontent.com/124494876/216811576-a59cc075-115f-4252-8774-60cd733e9275.jpg)

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 12

Manufacturer = Xiaomi

Model = Redmi Note 9 Pro

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; Redmi Note 9 Pro Build/SKQ1.211019.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.129 Mobile Safari/537.36

ACRA UUID = 15ea2a4b-d531-461b-bcf6-c9b903047b5b

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

That FAQ has all the causes of the problem, I would look there. The code isn't the problem - there will be some problem with either your card template, the card contents, or missing media for some reason
