### ISSUE TITLE
Add the Karakalpak language

### ISSUE THREAD

**Issue by ghost** [ankidroid/Anki-Android#13200]
Hi, I'm from the Republic of Karakalpakstan. We are using Karakalpak language. Could you add our language to your product please?
We are a team of Karakalpak language translators ready to quickly and efficiently translate your product into our language.

You can add it as a custom language on crowdin. Here is the information about the language:

Language name: Karakalpak
The dialect of: Not chosen
Crowdin code: kaa
Three letters code: kaa
Locale code: kaa
Text direction: left to right
Plural form: one, other

Thanks!

**Comment by mikehardy** [comment]
Thanks for logging this! I was the one that requested it be logged here from your crowdin request. Please have some patience with us as we are working on getting 2.16 out but now it will be tracked and not forgotten

**Comment by alizhumagaliev** [comment]
Ok) Thanks!

**Comment by mikehardy** [comment]
the kaa code has been added in crowdin, once the two core files are translated they'll need to be added to our infrastructure here

**Comment by mikehardy** [comment]
@alizhumagaliev thank you for pointing that out! I added the custom language based on your settings but there was one step after saving the new custom language where you have to scroll alllllll the way to the bottom of the language list to the set of custom languages and enable it.

That was missing. I believe it is done now? The link you posted was 404 before I did this step and now it resolves correctly

**Comment by mikehardy** [comment]
Hey @alizhumagaliev sure thing! Should be done now

**Comment by dae** [comment]
@mikehardy ok to close?

**Comment by mikehardy** [comment]
I don't believe that it's added to the language lists yet in code

**Comment by david-allison** [comment]
24%, core is at 62%:

https://crowdin.com/project/ankidroid/kaa

I believe we used to require core being at 100%. If this is still the case, the issue should be closed.
