### ISSUE TITLE
[Bug] Blank cards when requiring mathjax-mathtools

### ISSUE THREAD

**Issue by mzietlow** [ankidroid/Anki-Android#13214]
###### Reproduction Steps

1. Open AnkiDroid.
2. Create a new card of arbitrary type.
3. Insert `\(\require{mathtools}\)`
4. Insert arbitrary text to make the card valid.
5. Open the card in preview mode.

###### Expected Result

The arbitrary text that was added to the card should be shown.

###### Actual Result

No text is shown at all.

###### Debug info

AnkiDroid Version = 2.15.6

Android Version = 10

Manufacturer = HUAWEI

Model = EML-L29

Hardware = kirin970

Webview User Agent = Mozilla/5.0 (Linux; Android 10; EML-L29 Build/HUAWEIEML-L29; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.117 Mobile Safari/537.36

ACRA UUID = 6922810f-e26c-4601-9bbb-28ca06b32027

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mzietlow** [comment]
Additionally, I was suprised that mathtools-commands like `\(\Coloneq\)` did not work out of the box, because `mathtools` appears to be required in the [config](https://github.com/ankidroid/Anki-Android/blob/6d4551f981091150d38c2721334c460e52bd555b/AnkiDroid/src/main/assets/mathjax/conf.js).

**Comment by mzietlow** [comment]
Okay, I further investigated the config-topic.

I explicitly embeded the config using `<script src="file:///android_asset/mathjax/conf.js"></script>`. This lead to the same result I described above: No text is shown at all.

**Comment by mikehardy** [comment]
Can you try with the 2.16 alpha series? Mathjax has changed quite a bit and most issues registered by folks against 2.15 related to mathjax are resolved https://github.com/ankidroid/Anki-Android/releases

**Comment by mzietlow** [comment]
@mikehardy thank you for the suggestion. I can confirm that the issue is resolved in 2.16alpha93.

**Comment by mikehardy** [comment]
Excellent! Thanks for giving it a shot @mzietlow - I'll close this then and hopefully we get 2.16 out for real shortly :-)
