### ISSUE TITLE
[Bug] using a hardware keyboard to search for a deck in the deck list also triggers keyboard shortcuts

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#13210]
###### Reproduction Steps

1. Begin searching for decks from the deck list activity using a connected hardware keyboard (bluetooth or usb). software keyboards aren't affected
2. Begin to type "default" to find the default deck
3. After only "defa" is typed, the add card screen pops up. This is because "a" is the shortcut for add card. Similarly, Y (sync) and B (card browser) can also be incorrectly triggered.

###### Expected Result
Keyboard shortcuts shouldn't trigger when searching for a deck

###### Actual Result
They do

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16alpha92

Android Version = 11

Manufacturer = Google

Model = Pixel 2

Hardware = walleye

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 2 Build/RP1A.201005.004.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = edb11ce0-7c90-482d-9915-9e02591297f0

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by n1snt** [comment]
Hey, can I try to solve this issue?

**Comment by david-allison** [comment]
Sure!

**Comment by n1snt** [comment]
@sudomain can you please explain how did you search for the decks? I am unable to replicate this issue.

**Comment by david-allison** [comment]
Once you have 10+ decks, a search icon appears

**Comment by n1snt** [comment]
Thanks, I tried replicating this issue & it worked.
Will try fixing this now. 🙌
