### ISSUE TITLE
[Bug] New install alpha93 syncing a large collection with subdecks all cards in "Default" deck

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#13221]
This might be a fluke but I wanted to report it anyways since it was very unexpected. I'll try to reproduce it again later but my collection takes about 40 minutes to sync 12k multimedia files even with scoped storage and I have to study it now :)

Possibly related: I think Android killed my sync half way through because I switched to another app. When the migration notification finally exists, could it also be used to for the multimedia sync just to keep the app alive?

###### Reproduction Steps

1. New install of alpha93.parallel.A
2. On the welcome screen, choose the option to sync from ankiweb
3. Sync

###### Expected Result

All cards in their proper decks

###### Actual Result

All cards are in the "Default" deck (which does not exist in my collection). The expected decks have been created but are empty. Forcing a one-way sync from AnkiWeb returns the everything to the expected state.

![Screenshot_20230207-163233_AnkiDroidA](https://user-images.githubusercontent.com/409080/217385077-8a78b79a-66e2-4f93-88aa-5902a191a4d5.jpg)

###### Debug info
```

AnkiDroid Version = 2.16alpha93

Android Version = 12

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 0819f67d-4836-45b6-90c6-ecc700511215

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pavreh** [comment]
Reproduced.
It happend after I switched to an other app and back. Default deck appeared during sync. Notes remained in Default deck when sync has been finished.
![Screenshot_20230208_063111_AnkiDroidA.png](https://user-images.githubusercontent.com/10192661/217444192-c9198c29-ffcd-45a2-a8b2-8f6c6b087882.png)

AnkiDroid Version = 2.16alpha93

Android Version = 13

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.117 Mobile Safari/537.36

ACRA UUID = 3d354162-d703-4fa4-97df-39f154eab5ff

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by user1823** [comment]
I also faced this issue when I changed my phone and downloaded my collection to it.

(Android 12, AnkiDroid 2.16alpha91)

**Comment by dae** [comment]
@BrayanDSO I've bisected this to 3cc351c545e0881f9c350c625d005d669e8c08ce. Steps I used to reproduce in the emulator:

- Uninstall AnkiDroid
- Run the app and tap on "Sync with AnkiWeb" in the startup screen
- Wait until it reaches the media part of the sync, and return to the Android homescreen
- Return to the app
- Stop the app running (so you don't need to wait for all media to finish syncing)
- Reopen the app and observe cards are in the default deck

A few things to note:
- The issue doesn't seem to exist when using the new schema pathway (but there is a separate issue where the user needs to tap on 'sync with AnkiWeb' twice)
- If you kill the app before returning to it, the issue doesn't happen, so it seems to be some code that is run when AnkiDroid returns to the foreground.

**Comment by dae** [comment]
I'm not sure why that commit causes this problem to occur, but the root issue is that the decks cache in Decks.kt is not being reloaded after the full sync, so when the deck list is re-rendered, _recoverOrphans() moves all the cards into the default deck. I'll push a fix shortly.

**Comment by johtso** [comment]
I also had this happen, let me know if there's any info I can provide (seems like you're on top of it though).
