### ISSUE TITLE
[Bug] Unable to change deck name color in AnkiDroid

### ISSUE THREAD

**Issue by AndreHero007** [ankidroid/Anki-Android#13231]
I tried putting HTML codes, like <span style="color:blue;">Deck name</span>.

However, the color change only works on AnkiPC, on AnkiDroid the HTML codes around the deck name are visible and there is no color change.

Perhaps in AnkiDroid the HTML code is trapped in a string that makes Anki recognize it as text and not as code

AnkiDroid:
![7abb2598-a980-4bb5-8c67-b95f35b70528](https://user-images.githubusercontent.com/38014871/218142715-99c967a7-fac7-43ee-94f1-b7cd29c5120f.jpg)

AnkiWeb:
![image](https://user-images.githubusercontent.com/38014871/218142910-4c7d2ae1-178b-4859-bc5c-4e3976af7510.png)

**Comment by BrayanDSO** [comment]
The behavior on the desktop version is actually unintended and should be fixed there. As we try to keep compatible with the desktop features, we shouldn't implement this here

**Comment by AndreHero007** [comment]
> The behavior on the desktop version is actually unintended and should be fixed there. As we try to keep compatible with the desktop features, we shouldn't implement this here

I was on an old version, the most current desktop version also doesn't allow changing the color of the deck name.
