### ISSUE TITLE
QA refreshes in the preview webview

### ISSUE THREAD

**Issue by mmc20520** [ankidroid/Anki-Android#13230]
###### Reproduction Steps

1. In preview
2. Click show answer
3. Rotate screen

###### Expected Result

The content does not change

###### Actual Result

QA refreshes

Before rotation:
<img width="312" alt="Screen Shot 2023-02-10 at 2 16 17 PM" src="https://user-images.githubusercontent.com/100833575/218017015-e8176c3a-9219-474a-9ae2-299a1b70a5b9.png">

After rotation:
<img width="600" alt="Screen Shot 2023-02-10 at 2 16 28 PM" src="https://user-images.githubusercontent.com/100833575/218017058-3954c5a3-8f94-4cfe-83bc-e87ef9e6ebd2.png">

**Comment by Ohior** [comment]
your view is not being saved when re-created. So, you can use MVVM to save view
