### ISSUE TITLE
logcat monitored that a problem occurred when touch eye button

### ISSUE THREAD

**Issue by RiShinku** [ankidroid/Anki-Android#13238]
###### Reproduction Steps

1. Open card explorer
2. Click add button
3. Click eye button

###### Actual Result
logcat log printed 'Attempt to invoke virtual method 'void com.ichi2.libanki.Card.setDid(long)' on a null object reference'

**Comment by ShubhadeepKarmakar** [comment]
Yeah, I saw that too.

**Comment by criticalAY** [comment]
Yes, as the model was null but the error is already being handled already

**Comment by mikehardy** [comment]
So, @RiShinku what's the log level this is logged at? Is it debug? info? warning? error? You have not included enough information to know.

If it is debug or info, then ignoring it (as a developer: this message and in future) is fine. If it is warning or error, then a PR to tune it down to debug seems justified.

Either way, doesn't appear to be an issue
