### ISSUE TITLE
[Bug] Empty cards being saved

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13240]
###### Reproduction Steps

1. Click add card
2. try adding a empty card

###### Expected Result
If the first field is empty then the card is not saved 

###### Actual Result
Empty cards are getting saved which is not the right flow

###### Debug info
AnkiDroid Version = 2.16alpha93-debug

Android Version = 12

Manufacturer = OnePlus

Model = EB2101

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; EB2101 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.118 Mobile Safari/537.36

ACRA UUID = 4ffa3fea-6003-44a0-b914-0919027ac81d

New schema = true

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
@david-allison This bug is quite interesting as it is not reproduced in legacy backend but the new backend `v3`

**Comment by dae** [comment]
In the new schema path, the adding screen should be calling noteFieldsCheck() and aborting if the returned value is Empty. That backend method is not currently exposed, so it first needs to be added to CollectionV16. https://github.com/ankidroid/Anki-Android/issues/11882

**Comment by criticalAY** [comment]
> In the new schema path, the adding screen should be calling noteFieldsCheck() and aborting if the returned value is Empty. That backend method is not currently exposed, so it first needs to be added to CollectionV16. #11882

So this should be fixed at the NoteEditor end ?

**Comment by dae** [comment]
The desktop enforces this in the adding screen, not in the backend add method, so handling it in NoteEditor would make AnkiDroid consistent.

**Comment by criticalAY** [comment]
ok
