### ISSUE TITLE
Use manually translated language names instead of getting them from java libraries

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13259]
Currently we build the languages list dinamically by retrieving the language names from their locales. The java locales library is well known for being problematic and has created some issues.

Below is the demo of the issue of languages having their names changed (here depicted by changing from english to japanese)
https://user-images.githubusercontent.com/69634269/218898599-d0fbf6e9-7406-4040-a6ad-a166f867584f.mp4

Here's another example. `Gothic` isn't how the gothic language is called in gothic
![image](https://user-images.githubusercontent.com/69634269/218899021-406921b7-3119-4faf-92d0-6d4797b060dd.png)

And here is a language that hasn't got its name built correctly, so it used its language code (tl is the code of Tagalog)
![image](https://user-images.githubusercontent.com/69634269/218899180-026d5336-f8d4-493b-a5b1-ca37e65fcd8f.png)

---

My suggestion is to add a string to `01-core.xml` to represent each language name on their respective languages

**Comment by BrayanDSO** [comment]
I'd be willing to manually add the language names for the current languages on Crowdin, by getting them initially from the same methods we currently use, so the result is equivalent until actual speakers make a proper translation if necessary

**Comment by david-allison** [comment]
We should be doing two things:

1) When displaying a language, it should be displayed in the L2. This makes it easy for anyone to be certain about their language if they accidentally change the AnkiDroid language
    * `français` is always shown

This can likely be a single string for each language on CrowdIn, and we obtain this from each of the language files.

2) When displaying a language, it should be displayed in the current language if available
  * `French (français)`

I believe that 1) is more important than 2). I wouldn't oppose either, but I feel both are separate issues

**Comment by david-allison** [comment]
I support this, but would like to see a new `.xml` for this. 

`French` isn't an `01-core` string
