### ISSUE TITLE
Publish Alpha releases on the F-Droid store

### ISSUE THREAD

**Issue by galantra** [ankidroid/Anki-Android#13256]
**Is your feature request related to a problem? Please describe.**
As I understand it, https://github.com/ankidroid/Anki-Android/issues/5304 prevents the Play Store release from being updated. This does not affect F-Droid. Nevertheless, the F-Droid release has not been updated since Version 2.15.6 (21506300), added on 2021-07-20.

**Describe the solution you'd like**
Either
- publish another package that contains the alpha channel (or beta, if there is a 2.16 beta already)
- or update the existing package with the current 2.16 alpha releases.

**Describe alternatives you've considered**
If a solution for the Play Store issue is imminent, it might not be worth the effort; since I assume that F-Droid will be updated once the Play Store issue is solved.

**Comment by david-allison** [comment]
Solution for the Play Store is imminent, BUT: this has been asked for previously: 

https://github.com/ankidroid/Anki-Android/issues/7159

I'd want to merge this if someone wanted to take this on (and the F-Droid UX acceptably marks it as 'unstable' - we don't want alphas distributed to end users unless they know what they're doing).

Given after 2.16, F-Droid alphas will have more storage options than Google Play releases. 

The additional benefits of this change would be:
* F-Droid would provides automated alpha updates for users who want these additional storage options

Would you be interested in implementing this? I've had extremely limited experience with F-Droid

**Comment by BrayanDSO** [comment]
[Last time someone asked (December 2022)](https://github.com/ankidroid/Anki-Android/issues/12908#issuecomment-1334044153), the alpha/beta releases on Fdroid had to be manual.

Unless this has changed, I don’t find it feasible

**Comment by david-allison** [comment]
Missed that one. Closing as WONTFIX until it's workable via an API

**Comment by galantra** [comment]
I am sorry that I opened a duplicate!

**Comment by david-allison** [comment]
No worries!
