### ISSUE TITLE
[Bug] Crash when downloading a new collection completes

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13255]
###### Reproduction Steps

1. Change Profile Folder
2. Log In
3. Sync (Download)

###### Expected Result

No error

###### Actual Result

Crashes (logcat): [AnkiDroid-2023-02-14-Logcat.txt](https://github.com/ankidroid/Anki-Android/files/10727880/AnkiDroid-2023-02-14-Logcat.txt)

###### Debug info
Commit a71b31d3ccc331326cf48297d3351b72469af5ee + a few changes related to progress dialogs

NOTE: this is after potential fixes have gone in:

* e5f0cef773d3dcdf27cb588aa6d5277f2045c029 
* 59d59787eeae51e713d50b4514226980ebf05cba

```
AnkiDroid Version = 2.16alpha93-debug

Android Version = 12

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_arm64 Build/S2B2.211203.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.114 Mobile Safari/537.36

ACRA UUID = 1a9e35fb-1344-427c-9d78-e4a677862bab

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
May be my fault, will look into it.
