### ISSUE TITLE
[Bug] Migration not finishing, can't sync

### ISSUE THREAD

**Issue by Wyzmic** [ankidroid/Anki-Android#13263]
![Screenshot_20230215_114416_AnkiDroid](https://user-images.githubusercontent.com/72083780/218993070-3d28c172-381c-49b6-94a6-24dcb6074a7d.png)
It's stuck showing this for a few hours, what can I do?

**Comment by david-allison** [comment]
Hi, is there a notification on your phone which provides more information on the migration status?

**Comment by criticalAY** [comment]
@david-allison the migration PR was merged after `alpha93` so it won't go away until we are done with the migration PRs. Like the one that is open from my end too.

**Comment by Wyzmic** [comment]
I see, for sure:

AnkiDroid Version = 2.16alpha93

Android Version = 13

Manufacturer = samsung

Model = SM-S908B

Hardware = s5e9925

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-S908B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.117 Mobile Safari/537.36

ACRA UUID = a9d099e4-b961-4151-9e48-5f175321e22f

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by criticalAY** [comment]
So that's a temporary issue and will be fixed with the upcoming version @Wyzmic don't worry you haven't migrated till

**Comment by Wyzmic** [comment]
> So that's a temporary issue and will be fixed with the upcoming version @Wyzmic don't worry you haven't migrated till now

Oh alright, I did uninstall it and went back to the stable version and everything was still there. Thanks!

**Comment by doozan** [comment]
Dup of #13212?

**Comment by criticalAY** [comment]
Yes

**Comment by david-allison** [comment]
Closing as duplicate
