### ISSUE TITLE
Linebreaks (<br>) not to be replaced with \n

### ISSUE THREAD

**Issue by cd-FileX** [ankidroid/Anki-Android#13279]
**Is your feature request related to a problem? Please describe.**
The HTML Linebreaks are being replaced with `\n`, so actual linebreaks. This causes my notes to have, when edited on mobile, 2 Line breaks as I format the code as `1: Meaning 1<br>\n2: Meaning 2` which in the end should look like 
```
1: Meaning 1
2: Meaning 2
```

**Describe the solution you'd like**
Split up notes and code and also displaying the formatting, so things like `<b>Text</b>`. This would be identical to desktop and probably the hardest but best solution

**Describe alternatives you've considered**
1) Keeping the HTML Linebreaks in the note. This is the easiest but worst looking solution
2) Note in background which was an actual linebreak (in code) and which one a `<br>` (Probably harder and more useless than the next one or the top solution)
3) Split up notes and code and display it like on Desktop (without the formatting).
  This would look like

**Additional context**
Alternative 1:
```
This <b>Text</b><br>got a <em>Linebreak</em>
```
Alternative 2 & 3:
```
This <b>Text</b>
got a <em>Linebreak</em>
```

**Comment by atakanserifoglu** [comment]
I can be assigned for this issue.

**Comment by doozan** [comment]
Settings -> Advanced -> Replace newlines with HTML

**Comment by cd-FileX** [comment]
Ah thank you, this worked. I didn't know there was such a setting
