### ISSUE TITLE
Add "stop or pause audio button" when I review the cards

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1328]
Originally reported on Google Code with ID 425

```
I use the text to speech or I would put some audio into my card.
sometimes I wish I could the pause the audio or stop the audio when I review the cards.
Would you please add stop or pause audio button when I review the cards?

Le

```

Reported by `lo.catdog` on 2011-02-16 15:36:30

**Comment by mnhende2** [comment]
Hello hssm, greetings.  Recently Damien added this feature to the Apple mobile version.  See the thread here:  https://anki.tenderapp.com/discussions/ankimobile/5682-playpause
Any chance this might get added into the Android version?

**Comment by mikehardy** [comment]
This would dovetail with #996 and/or #4601 - if there were a graphical audio control on the note viewer to handle play/pause here, then for an implementation of #996 it could just load paused

**Comment by ajkfrye** [comment]
Want this. If a native option could be added that would be great. Is there a possible workaround to get this functionality using javascript in the meantime?

**Comment by mikehardy** [comment]
Just to be clear on the Anki Desktop / iOS implementation based on discussion linked above, it's a control for audio files (not TTS) that allows for -5s / play+pause / +5s

**Comment by ajkfrye** [comment]
And for those of us who do all our studying in Ankidroid? . . . and isn't that what this GitHub thread is for . . . or am I in the wrong place?

**Comment by mikehardy** [comment]
You are in the right place, this is an enhancement request to add the functionality to AnkiDroid. In general however we just maintain feature compatibility with AnkiDesktop or iOS, so I was just documenting what I learned about how the feature is implemented there, for anyone that is thinking of coding it up to have a rough idea of what's being contemplated

**Comment by ajkfrye** [comment]
Ah ok. For sure. It feels like this shouldn't be hard, but I'm not a real coder. Everything I know about code is a result of tinkering with Anki. I just want a pause button. Like for the play button to change to pause during playback. If there was so forward and back so much the better! But again I wouldn't know what it would take to have this

**Comment by mikehardy** [comment]
Fresh idea that can work now here: https://github.com/ankidroid/Anki-Android/issues/996#issuecomment-548060297
