### ISSUE TITLE
A `ClassCircularityError` should break unit test run

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13298]
The following code causes a `ClassCircularityError` which did not break the test run, but it killed a test executor

https://github.com/ankidroid/Anki-Android/blob/06c2e548da32d1cf80f63572d16683bcd20d4db0/AnkiDroid/src/test/java/com/ichi2/utils/UniqueArrayListTest.kt#L86-L92

Make sure that if you mock Collection and break the unit test in the way https://github.com/ankidroid/Anki-Android/pull/13353 will mark flaky to skip, the test harness actually fails

---

<details><summary><b>old issue text</b></summary>

Likely by: 2c76360f889838f66130b47061c14af774588da4

> Exception in thread "Test worker" 
> Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Test worker"

- [x] refresh cache + test: https://github.com/ankidroid/Anki-Android/actions/runs/4213615072: failed
- [x] revert
- [ ] 
</details>

**Comment by mikehardy** [comment]
I'm typing this right now from a macOS I just cracked the lid on for first time in a while, investigating locally....

**Comment by mikehardy** [comment]
Well in a stroke of "luck" it reproduces locally on my machine on current main. 

A revert of your suspect commit does indeed pass locally

 I'm just about out of time for the evening though, so anything past the revert test (running now) will have to sit for 12hrs or so but rolling it forward seems like it should be easy enough since it's only one platform and it reproduces, I can pick that up tomorrow

Revert in the meantime (and just merge it and go, I've tested it...) if unblocking is worth it

**Comment by mikehardy** [comment]
I'm re-opening this while I work on fixing it for real

Also it appears that macOS legacy_schema=false is not run in CI 🤔  (needs verification)

I want to examine / fix both if possible while I'm in here on a mac working through things

**Comment by david-allison** [comment]
The issue was a circular dependency (`ClassCircularityError`) caused by mocking `Collections`

https://github.com/ankidroid/Anki-Android/blob/06c2e548da32d1cf80f63572d16683bcd20d4db0/AnkiDroid/src/test/java/com/ichi2/utils/UniqueArrayListTest.kt#L86-L92

I've got a fix ready to go. I'm timeboxing investigating why it started failing.

This error does **not** break the test run, and it should.

**Comment by mikehardy** [comment]
Okay - so new goalpost here: make sure that if you mock Collection and break the unit test in the way #13353 will mark flaky to skip, the test harness *actually* fails
