### ISSUE TITLE
[Bug]Every Deck Got Duplicated

### ISSUE THREAD

**Issue by Prosphel5** [ankidroid/Anki-Android#13304]
###### Reproduction Steps
![27a4dfe997147ac5ab8175621a13e48](https://user-images.githubusercontent.com/124118365/219948432-011295dc-3416-41f9-95af-4f78450c9de3.jpg)
Some user reflects that after his AnkiDroid updated this happened. Every deck got duplicated with a plus sign added to each duplicate. Why did this happen?

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! I'm not sure why this happened.
You've ignored our issue template though, meaning support is not really possible.

**Comment by mikehardy** [comment]
I repeat:


Hi there! I'm not sure why this happened.
You've ignored our issue template though, meaning support is not really possible.

**Comment by SanjaySargam** [comment]
Hey Hi @Prosphel5, can you please give us 
1. Reproduction Steps
3. Debug info
 
So that we can figure out why it is happening and how it can resolve

**Comment by david-allison** [comment]
Author didn't reply, closing as 'can't reproduce'
