### ISSUE TITLE
Implement matrix / API split for emulator tests `>= R`

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#13312]
@mikehardy This brings in an API split for emulator tests `>= R`. https://github.com/ankidroid/Anki-Android/pull/13291 was required for `amazon`. `play` works with no changes.

Proposal: move this to a separate issue

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/13261#issuecomment-1436005851_

**Comment by mikehardy** [comment]
@david-allison can you elaborate on what the emulator tests should split on exactly? I can probably take it up

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/blob/625e6c71cb9b1bc7f39c4b4391c478bee59b6a4b/AnkiDroid/build.gradle#L145-L153

In `targetSdkVersion 30`, all non-Play variants will have `MANAGE_EXTERNAL_STORAGE` permissions.

We're not allowed this on the Play Store, and it will be removed from the manifest.
This will be done in the same manner that we remove `camera ` permissions for Amazon:

https://github.com/ankidroid/Anki-Android/blob/60a823d9c2f7364958b5eaa5a5faee13159b172d/AnkiDroid/src/amazon/AndroidManifest.xml#L5-L8

When implementing `targetSdkVersion 30`, emulator tests passed on `playDebug`, but not `amazonDebug`.

For reference: I typically run Android Studio against `amazonDebug`. Arbitrary selection of the default
