### ISSUE TITLE
Every Deck Got Duplicated

### ISSUE THREAD

**Issue by Prosphel5** [ankidroid/Anki-Android#13320]
![image](https://user-images.githubusercontent.com/124118365/220342531-1025b359-0339-4859-9f1f-c8143730bc54.png)
Some user reflects that after his AnkiDroid updated this happened. Every deck got duplicated with a plus sign added to each duplicate. Why did this happen?

**Comment by criticalAY** [comment]
Duplicate of #13304

**Comment by mikehardy** [comment]
Please do not open duplicate issues.
