### ISSUE TITLE
[BUG]: Night Mode color inversion

### ISSUE THREAD

**Issue by 2pascal** [ankidroid/Anki-Android#13325]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Trying to have AnkiDroid use dark mode for the application's toolbars and menu without changing the card theme which is working properly on PC for both light/dark mode, and on AnkiDroid only when light mode is selected. Found a Reddit post suggesting 
.night_mode {
.nightMode {
.mobile {

placing my intended formatting code within these, or just closing the bracket with nothing between

but no changes happened with the appearance on AnkiDroid when in Dark mode

### Expected behaviour

see my custom colors on the card while in dark mode

### Actual behaviour

my custom theme appears to be more or less inverted while in dark mode

### Debug info

on both latest release and alpha

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Please edit your post to include your AnkiDroid debug information: https://ankidroid.org/help.html

**Comment by Flibbo** [comment]
Had the same issue and solved it with kinda the described hack. Maybe you misunderstood. From your description it sounds like you put it in your cards?
You have to change your card presets - that you do just with anki on your computer.
_To be specific:_
**Open Anki -> Browse**
In that Window you look for the menu bar at the top
**Notes -> Manage Notes**
In the Note Types Window you choose the card type (yes, you may have to do it for more than one)
**Cards -> Styling**
And there you finally are to add
`.mobile .night_mode { }`
to your css. Works like a charm. Black fonts should still be bright, but all the colors i set on the cards eg for colored backgrounds are actually that color now and not just half of the times.

Have fun

**Comment by TrustKibou** [comment]
Any update on this problem?

I've noticed this only happens to colors set using CSS in the cards editor, not colors that are manually applied using the color-picker. For instance, I have a T/F note type that uses in-line CSS (via card template) to change the color of the first field to orange. In AnkiDroid, this color gets changed to blue. However, if I use the color picker to change the color of some text in a different field, that color is retained in AnkiDroid. I've tried using !important but it doesn't work. This also applies to note CSS (via card template).

I looked at the HTML breakdown using AnkiWeb and couldn't see any selectors that might separate the two. They're both just spans with in-line.

**Comment by david-allison** [comment]
@TrustKibou What version are you using? This was removed in 2.17:

https://ankidroid.org/removed-features.html#_automatic_night_mode_color_inversion

**Comment by david-allison** [comment]
* Duplicate of https://github.com/ankidroid/Anki-Android/issues/14893

**Comment by TrustKibou** [comment]
just upgraded, works perfect, thank you!
