### ISSUE TITLE
[BUG]: Missing Spanish Translation

### ISSUE THREAD

**Issue by gncs** [ankidroid/Anki-Android#13331]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

![Screenshot_20230219-125522](https://user-images.githubusercontent.com/1926852/220851234-03336f98-3eb6-4273-92bb-5b551019b0b1.jpg)

It says "Hola" (Hello in Spanish) in the menu shown above (second item from the top). I don't think this is the correct translation. 

### Expected behaviour

I expect the correct translation of this menu item. 

### Actual behaviour

Possibly missing translation. 

### Debug info

AnkiDroid (latest) 

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
Thank you, the string will be changed.

**Comment by mikehardy** [comment]
Wow! That one has been in there since #9000 about 2 years ago :facepalm:

**Comment by david-allison** [comment]
Thanks! In future, feel free to make an account on: https://crowdin.com/project/ankidroid and **be bold** in fixing issues
