### ISSUE TITLE
[BUG]: Search filter `introduced:N` doesn't work

### ISSUE THREAD

**Issue by michalrus** [ankidroid/Anki-Android#13339]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Browse cards, input `introduced:5` to filter down to cards that have been introduced (first answered) in the last 5 days.

Cf. https://docs.ankiweb.net/searching.html#first-answered

### Expected behaviour

Those cards are shown

### Actual behaviour

No cards are shown

### Debug info

AnkiDroid Version = 2.15.6

Android Version = 7.1.2

Manufacturer = LGE

Model = Nexus 5X

Hardware = bullhead

Webview User Agent = Mozilla/5.0 (Linux; Android 7.1.2; Nexus 5X Build/NJH47F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/64.0.3282.137 Mobile Safari/537.36

ACRA UUID = cedc4894-4d9e-46f2-a6da-6081705c1718

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Fixed in the new backend in the 2.16 alpha.

**Comment by michalrus** [comment]
Hey, thank you for quick answer!

I installed [v2.16alpha92](https://github.com/ankidroid/Anki-Android/releases/tag/v2.16alpha92) – because alpha93 had a warning about breaking ease, and I tried both creating a filtered deck, and searching in the browser for "introduced:5", but no cards are added, while in Anki Desktop, I see 100 cards for this query

**Comment by michalrus** [comment]
Should I try 93? 🥹

**Comment by david-allison** [comment]
would recommend 92

**Comment by michalrus** [comment]
Great! Now it works, thank you 🙇

**Comment by michalrus** [comment]
Though I noticed, doing today's reviews, that `alpha92` claims I have 20 new cards to learn, but when I click the deck, it says I'm all done for today :thinking: Switching back to the previous backed solved the issue, but now I still don't have `introduced:5`

Do you maybe know a solution?

**Comment by david-allison** [comment]
> Though I noticed, doing today's reviews, that `alpha92` claims I have 20 new cards to learn, but when I click the deck, it says I'm all done for today 🤔 Switching back to the previous backed solved the issue, but now I still don't have `introduced:5`
> 
> Do you maybe know a solution?

Worthwhile opening a new bug for that one

**Comment by michalrus** [comment]
I decided to—instead of `introduced:5`—do `rated:5:1 OR rated:5:2`. It does mostly the same and even better, including past reviews

**Comment by mikehardy** [comment]
I think the due date stuff was exactly what was targeted as a fix in alpha93 but there was (as noted, as you saw...) an unrelated issue which means we unfortunately cannot recommend alpha93. All should be working much more nicely in alpha94 but that's blocked on some storage migration stuff. We'll get there in the end. Glad you found something that works for you though :-)

**Comment by michalrus** [comment]
Keeping 🤞 for `alpha94` then, good luck! Thank you
