### ISSUE TITLE
[Bug] No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13340]
Reported by @criticalAY 

```
* What went wrong:
Could not determine the dependencies of task ':lint-rules:ktlintKotlinScriptFormat'.
> Could not resolve all dependencies for configuration ':lint-rules:ktlint'.
> Failed to calculate the value of task ':lint-rules:compileJava' property 'javaCompiler'.
> No matching toolchains found for requested specification: {languageVersion=11, vendor=any, implementation=vendor-specific}.
> No locally installed toolchains match (see https://docs.gradle.org/8.0.1/userguide/toolchains.html#sec:auto_detection) and toolchain download repositories have not been configured (see https://docs.gradle.org/8.0.1/userguide/toolchains.html#sub:download_repositories). Does anyone have idea about this error I am not able to commit my changes
```

Probable cause: 625e6c71cb9b1bc7f39c4b4391c478bee59b6a4b

Creating issue for documentation/tracking

Additional bug when moved to JDK11

```
* What went wrong:
Execution failed for task ':AnkiDroid:runKtlintFormatOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
> java.lang.ExceptionInInitializerError (no error message)
```

**Comment by mikehardy** [comment]
Very strange as I run it under JDK11 (and JDK18, but with JDK11 installed on system) and both have worked for me.

That said the first error is what I suspected *could* happen with this directive specifically: https://github.com/ankidroid/Anki-Android/commit/625e6c71cb9b1bc7f39c4b4391c478bee59b6a4b#diff-63b4e1c61db7eeab4f6a80d1ed5a06a35a354c7119d40dda1b493bb8e9d63fb7

The alternative is not to use toolchain and instead specify source/target I think

I believe the successful test for this one would be to have a system with (for example) only JDK17 (since it is an LTS, it is a good candidate) and make sure that AnkiDroid can build and run correctly including `./gradlew ktlintFormat` with only JDK17 installed

**Comment by criticalAY** [comment]
The second error was
```
* What went wrong:
Execution failed for task ':AnkiDroid:runKtlintFormatOverMainSourceSet'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction
   > java.lang.ExceptionInInitializerError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s
```
There was no java error in this one but the ktlint command fails for some reason though when I ran ktlint over main branch it was successful

**Comment by criticalAY** [comment]
I also update the branch from mainstream but was not useful at all

**Comment by mikehardy** [comment]
You might be able to fix it by altering `lint-rules/build.gradle` to contain something more like:

```groovy
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
        coreLibraryDesugaringEnabled true
    }
    kotlinOptions {
        jvmTarget = JavaVersion.VERSION_1_8
    }
```

Note that I think the `compileOptions` and `kotlinOptions` specifically are not in scope there, it might be a little different - I won't have time to check this for a bit unfortunately, in the meantime you can skip checks on commit I think so I do not think you are blocked? Just want to make sure

**Comment by criticalAY** [comment]
Nope I simply skipped the hook

**Comment by david-allison** [comment]
What's the output of `java -version`?

**Comment by criticalAY** [comment]
`java version "19.0.1" 2022-10-18` from power shell

**Comment by criticalAY** [comment]
I have set different version as JAVA_HOME variable

**Comment by david-allison** [comment]
Android Studio: What does `Build, Execution, Deployment -> Build Tools -> Gradle` say?

**Comment by criticalAY** [comment]
umm sure
![Screenshot_59](https://user-images.githubusercontent.com/48384865/221300621-df8536ef-eac3-4c5a-9132-cf80716c6a7d.png)

**Comment by oakkitten** [comment]
I see the same error while trying to commit on top of #13219 (e57be85)

**Comment by criticalAY** [comment]
It was fixed for after somehow after I installed JDK11 and cleared caches and restarted my system though I am not sure what fixed it but I am glad it is fixed

**Comment by mikehardy** [comment]
Clearly the `jvmToolchain` thing is problematic, really sorry this has hung folks up and that I haven't had a chance to clear it yet

Using JDK11 (that is: having it installed, making sure it is configured in PATH and as JAVA_HOME and in Android Studio) appears to be a valid workaround for now if affected.
