### ISSUE TITLE
Hide Card Browser Filter Sheet

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13341]
(mentioned in Discord)

This isn't not going to be done before 2.16. We shouldn't display this to users.

* Determine what (if any) functionality is unavailable without using the sheet
* Check `git` history and re-enable any missing functionality
* Hide the Floating Action Button displaying the filter sheet
  * ~~Use the following syntax to define a `BuildConfig` variable to hide it: https://github.com/ankidroid/Anki-Android/blob/e9120d8a20fefa10a0461f5ffe82e66279a9a443/AnkiDroid/build.gradle#L99-L101 ~~
  * ~~Access the constant via `BuildConfig.constant`~~
* If any functionality is removed, re-enable it from the CardBrowser Menu

**Comment by Aditya13s** [comment]
@david-allison can you explain to me what is going on in this code?

**Comment by david-allison** [comment]
> @david-allison can you explain to me what is going on in this code?

Which code?

**Comment by Aditya13s** [comment]
> > @david-allison can you explain to me what is going on in this code?
> 
> Which code? The gradle snippet expects a value in `local.properties`and sets a constant in `BuildConfig.java` if it's found

Please provide more information about the issue

**Comment by david-allison** [comment]
Specifically, what part of the issue don't you understand?

We have a floating action button which we wish to hide. It was started but unfinished

We want to ensure that when we hide it, none of the functionality which it provides has been removed from the app.

**Comment by Aditya13s** [comment]
> Specifically, what part of the issue don't you understand?
> 
> We have a floating action button which we wish to hide. It was started but unfinished
> 
> We want to ensure that when we hide it, none of the functionality which it provides has been removed from the app.

Can you be able to assign me the issue so that I can start working on it

**Comment by BrayanDSO** [comment]
I don’t think that there is anyone willing to proceed with the filters bottom sheet, while we have #12554 that looks more promising. So I wouldn’t bother adding a build config that almost no one will ever use, and would just hide the filter sheet FAB (I don’t recall if there is another way to trigger it

**Comment by Aditya13s** [comment]
This is the code in the CardBrowser.kt file for the Floating Action Button and I set the visibility to gone from the layout
        val filterButton = findViewById<FloatingActionButton>(R.id.filter_sheet_fab)

        filterButton.setOnClickListener {
            modalBottomSheet.show(supportFragmentManager, FilterSheetBottomFragment.TAG)
        }

**Comment by david-allison** [comment]
If any functionality only exists in the CardBrowser bottom sheet, re-enable it in the menu

**Comment by Aditya13s** [comment]
The functionality of the Floating Action Button is added in the menu Named Filter by tag and I hide the Floating Action Button

**Comment by Aditya13s** [comment]
@david-allison

**Comment by david-allison** [comment]
If it's done, send in a Pull Request. It's harder for me to act on a description of the code
