### ISSUE TITLE
[BUG]:  service doesn't get properly set up as a foreground service

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13348]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Reported by @oakkitten 
> service stopping -> stops due to the fact that a) the activity unbinds from the service on stop, and b) the service doesn't get properly set up as a foreground service in the first place, which makes it stop when the last client unbinds. This, in turns, seems to be happening because the first notification is not posted until the size of transfer is calculated, which can take more than 5 seconds:

### Expected behaviour

Service is unaffected by theme change or device rotation

### Actual behaviour

Stops on theme change

### Debug info

alpha93-debug

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by oakkitten** [comment]
Duplicate of #13299

**Comment by criticalAY** [comment]
Cool
