### ISSUE TITLE
[BUG]: Subdecks not displaying as such

### ISSUE THREAD

**Issue by szalejot** [ankidroid/Anki-Android#13377]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Open the main AnkiDroid window

### Expected behaviour

Subdecks will display their relation to the parent deck.

### Actual behaviour

All decks are shown as main decks.

### Debug info

```text
AnkiDroid Version = 2.16alpha94

Android Version = 12

Manufacturer = Xiaomi

Model = 21081111RG

Hardware = mt6893

Webview User Agent = Mozilla/5.0 (Linux; Android 12; 21081111RG Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.65 Mobile Safari/537.36

ACRA UUID = 76363c13-0769-4137-8c86-83fac13b0de0

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

How it looks on AnkiDroid:
![image](https://user-images.githubusercontent.com/3840404/222219292-3f881966-06ed-4711-867f-5cfa0da22626.png)

The same collection on desktop:
![image](https://user-images.githubusercontent.com/3840404/222219345-f4ad8f50-1dd0-4c87-b199-fb5373da9a36.png)

Issue started after upgrade to 2.16alpha94, on 2.16alpha93 it was working properly.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
This is not reproducible in latest release.

@david-allison You can feel free to close this issue.
