### ISSUE TITLE
[Bug] "Backup Your Collection" appears frequently if logged in

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13370]
###### Reproduction Steps

1. Install the new alpha 
2. Logged in 
3. Synced only my collection minutes ago, then canceled while downloading media 
4. Reopen the app

###### Expected Result

No Dialog

###### Actual Result

![image](https://user-images.githubusercontent.com/62114487/222015947-f81e599f-3a40-485e-8cc0-0d394bb11793.png)

###### Debug info
2.16alpha94

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
PR ref: https://github.com/ankidroid/Anki-Android/pull/13316

**Comment by BrayanDSO** [comment]
And the icon isn't shown (at least on Dark theme)
![image](https://user-images.githubusercontent.com/69634269/222018846-d963309b-1b9f-4501-926b-b2b3ed5b7313.png)
