### ISSUE TITLE
[BUG]: No way to access "three dots" menu during review using Fullscreen mode/Hide the system bars

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#13375]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

* Using android configured with gesture navigation
* Anki configured to use "Fullscreen mode" / "Hide the system bars"
* Begin reviewing cards
* Slide from right side of screen towards the center until the android "arrow" hint appears, then slide back to right side.

### Expected behaviour

Anki should display the toolbar with the three dots menu and other controls

![reviewing - hide all - back](https://user-images.githubusercontent.com/409080/222183076-a9ae88c0-3abe-4058-a0d1-52586be07e33.jpg)

### Actual behaviour

Anki does not show the toolbar

![reviewing - hide system bars - back](https://user-images.githubusercontent.com/409080/222183150-be54e961-92bd-4429-952f-8eac72551e3d.jpg)

### Debug info

```
AnkiDroid Version = 2.16alpha94

Android Version = 12

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 0819f67d-4836-45b6-90c6-ecc700511215

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

This is a regression that first appeared in alpha93. In alpha92 and 2.15.6, the header bar appears as expected. When using "Fullscreen mode - Hide the system bars and answer buttons" the header bar still appears as expected.

My use case here is that I don't want to see the deck name when I'm reviewing, but I do want to see the number of cards left to review and I occasionally need to undo a response or edit a card while reviewing.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
I would love to work on this issue
