### ISSUE TITLE
[Bug] Backup prompt dialog icon isn't shown with the dark theme

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13372]
And the icon isn't shown (at least on Dark theme)
![image](https://user-images.githubusercontent.com/69634269/222018846-d963309b-1b9f-4501-926b-b2b3ed5b7313.png)

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/issues/13370#issuecomment-1449163027_

**Comment by david-allison** [comment]
Gah, tested it on `black`, but not `dark`

**Comment by david-allison** [comment]
- PR ref: https://github.com/ankidroid/Anki-Android/pull/13316
