### ISSUE TITLE
[BUG]: Open the "create a new subdeck" dialog in card browser on the "All Decks" item creates a new deck named "All Decks"

### ISSUE THREAD

**Issue by jgscherber** [ankidroid/Anki-Android#13387]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

See attached screen recording

**STR**

- Open card browser
- Open deck select dialog
- Long-press on "All Decks"

Create subdeck dialog opens

- Cancel dialog
- Select "All Decks" option (IDK if this is required)
- Go back to home

https://user-images.githubusercontent.com/6207661/222477168-3a059df1-52d6-4748-b9fd-a5ce665ea8b1.mp4

### Expected behaviour

No new deck created

### Actual behaviour

New deck created named "All Decks"

### Debug info

```text
AnkiDroid Version = 2.15.6

Android Version = 13

Manufacturer = samsung

Model = SM-G981U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G981U1 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.154 Mobile Safari/537.36

ACRA UUID = 03434583-cd6c-4869-8ed2-d8e7712382df

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Fixed by https://github.com/ankidroid/Anki-Android/pull/11907
