### ISSUE TITLE
[Bug] Copy debug info shows a snackbar and a toast together

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#13384]
###### Reproduction Steps

1. Settings - About - Copy debug info

###### Expected Result

A snackbar appears

###### Actual Result

A snackbar and a toast appear together.

![Screenshot_20230302_061154_AnkiDroid.png](https://user-images.githubusercontent.com/10192661/222338738-ac1b6a16-4fa8-460a-9d0c-b9aab59523b8.png)

###### Debug info
AnkiDroid Version = 2.16alpha94

Android Version = 13

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36

ACRA UUID = c7d3c7d7-9663-4e37-9340-b9e8e137ac85

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

test alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
The toast is from you system. Not sure if all manufacturers do the same in all sdk versions, but I bet not
