### ISSUE TITLE
Improve `Cancel download of shared decks` dialog

### ISSUE THREAD

**Issue by pratyaksh1610** [ankidroid/Anki-Android#13386]
**Is your feature request related to a problem? Please describe.**

I was downloading a shared deck and after clicking Cancel download, a dialog appears saying `Cancel download?` with buttons `Continue` and `Cancel`. I think these buttons can be sometimes misleading as `Cancel` can refer to cancelling the dialog instead of cancelling the shared deck download. (I also meant the same the first time, Lol 😆). Looks like this dialog can be improved further. 

![ss](https://user-images.githubusercontent.com/76740999/222467006-b4049dad-87c2-4378-a964-43e94d35d7d0.png)

**Describe the solution you'd like**

![sss](https://user-images.githubusercontent.com/76740999/222469664-7dd36e90-ae39-45e3-af44-e9a4eb0e15ea.png)

**Comment by n1snt** [comment]
Some text can be added to the popup in addition to the title.
Something like "Canceling the download will delete any downloaded files. Do you want to proceed?"
Also if this gets approved as a valid issue & you are not working on this I would love to have a try at this.

**Comment by pratyaksh1610** [comment]
Yes , feel free to work on this.

**Comment by SanjaySargam** [comment]
@n1snt Are you working on it?
