### ISSUE TITLE
[BUG]: new cards appear at wrong time

### ISSUE THREAD

**Issue by abrasive** [ankidroid/Anki-Android#13388]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Set "start of next day" to 0 hours past midnight

### Expected behaviour

New cards appear at 00:00 local time

### Actual behaviour

New cards don't appear until 11:00 local time.

With the same setting on Anki desktop, the same cards appear at 00:00 local time.

### Debug info

```text
AnkiDroid Version = 2.16alpha92

Android Version = 12

Manufacturer = samsung

Model = SM-G970F

Hardware = exynos9820

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36

ACRA UUID = 08944ea3-e8f2-4d2c-a37d-4580aa3409cc

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Same issue occurred with the default setting of day start at midnight+4h but I wasn't able to determine exactly when the new cards popped - it was certainly in the afternoon.

The time zone on my device is UTC+11.
The Android clock shows the correct local time.
Seems almost as if the UTC-to-local correction is being applied twice?

Both Anki desktop and AnkiDroid are set to use V3 scheduler.
Legacy timezone handling is disabled on Anki.
New timezone handling is enabled on AnkiDroid.

The only potentially related issue I can find is #5637.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
Can you reproduce it with the latest alpha?

**Comment by mikehardy** [comment]
This should be fixed with alpha94 - 93 specifically fixed it (but had a different issue...) 94 should be good on all counts here.
Going to close this pre-emptively, but if course can reopen if alpha94 doesn't work in this case

**Comment by abrasive** [comment]
Confirming this was fixed in alpha94. Sorry it took a few days to test. Many thanks to all involved 🙏🏻
