### ISSUE TITLE
[BUG]: Cannot quote/escape search queries

### ISSUE THREAD

**Issue by Aquafina-water-bottle** [ankidroid/Anki-Android#13399]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Create any card with a field containing `a"bc`. For example, create a Basic card with `Front` -> `a"bc`, and `Back` -> `abc back`.
1. Attempt to search for `"Front:a\"bc"`

### Expected behaviour

The card should show in the results screen.

### Actual behaviour

The card is not shown in the results screen.

### Debug info

```text
AnkiDroid Version = 2.16alpha94

Android Version = 11

Manufacturer = samsung

Model = SM-A705W

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-A705W Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36

ACRA UUID = 92deb424-7585-4976-afd5-787232deaf81

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

- It is true that the search `Front:a"bc` would work. However, if the field contains a space, i.e. `<span class="a">abc</span>`, it becomes impossible to search for the exact string with say, `"Front:<span class=\"a\">abc</span>"`.
- The query works on Anki Desktop, so I believe it is expected to work on AnkiDroid as well.
- I didn't test it on the latest stable release, only on the latest alpha release.
- As random workarounds, I tried queries such as `"Front:a\\"bc"`, `"Front:a\\\"bc"`, and <code>\`Front:a\"bc\`</code>. Unfortuately, none of them worked.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Aquafina-water-bottle** [comment]
Looking into the issue, I believe [this function](https://github.com/ankidroid/Anki-Android/blob/7e9769ddca89df4349753b229b8b59f42e638f3a/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt#L534-L538) has to be reworked to be more similar to [Anki's search parser.rs](https://github.com/ankitects/anki/blob/e5d5d1d4bdecfac326353d154c933e477c4e3eb8/rslib/src/search/parser.rs#L285-L305) in order to support the functionality. (I believe that's the correct file/function, but I can't really read Rust code unfortunately)

**Comment by david-allison** [comment]
> New schema = false

Have you tried using the Rust backend in the advanced settings?

**Comment by Aquafina-water-bottle** [comment]
> > New schema = false
> 
> Have you tried using the Rust backend in the advanced settings?

It was as simple as that, thank you so much!
