### ISSUE TITLE
[BUG] Crash: Can't open "AnkiWeb account" page on parallel version

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#13398]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Open 2.16alpha93(parallel A) or 2.16alpha94(parallel A)
   <img src="https://user-images.githubusercontent.com/10436072/222881633-521a69ed-15d8-4c6e-8b45-4690b95d8243.png" width="320px">

2. "Settings" -> "Sync" -> "AnkiWeb account"
   <img src="https://user-images.githubusercontent.com/10436072/222881829-4c2af689-cd7e-4819-a5f9-7c1545f63d47.png" width="320px">

### Expected behaviour

"AnkiWeb account" page gets shown, as on 2.16alpha92 parallel A.
<img src="https://user-images.githubusercontent.com/10436072/222882100-056d0795-213e-4359-845d-7b5895c772ed.png" width="320px">

### Actual behaviour

Crash
<img src="https://user-images.githubusercontent.com/10436072/222881937-85d47e04-1c5a-41e3-9b37-fb42769aed56.png" width="320px">

### Debug info

```text
AnkiDroid Version = 2.16alpha94

Android Version = 11

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.117 Mobile Safari/537.36

ACRA UUID = b0f6e323-bfa7-49c8-8026-f40b71a679f2

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

- AnkiDroid directory is default, `/storage/emulated/0/AnkiDroid`.
  <img src="https://user-images.githubusercontent.com/10436072/222882757-b333d792-55a2-4ea3-a01b-ecfddeff3b19.png" width="320px">

- This bug wasn't reproduced on either the main (not-parallel) 2.16alpha93 or the main (not-parallel) 2.16alpha94.
- After uninstalling the main (not-parallel) 2.16alpha94 and performing the reproduction steps above on 2.16alpha94 parallel A, the following message appeared (no crash occurred): 
`The system does not have an app installed that can perform this action.`
  <img src="https://user-images.githubusercontent.com/10436072/222884994-ee02f150-36e8-4e1e-9b03-a4b354d53a6b.png" width="320px">

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Relevant code:

https://github.com/ankidroid/Anki-Android/blob/44ff8c7e98d7c37a30b71674c022e21ef4d24395/AnkiDroid/src/main/res/xml/preferences_sync.xml#L28-L30
