### ISSUE TITLE
Automatic theme switching

### ISSUE THREAD

**Issue by serpenteagle** [ankidroid/Anki-Android#13393]
**Is your feature request related to a problem? Please describe.**
I expect all my apps to synchronize their themes with the system theme. It's problematic to have to do so manually with the current implementation.

**Describe the solution you'd like**
Add a checkbox in Preferences > Appearance > Themes which toggles dark/light system theme synchronization.

When enabled, the user can still change the theme manually via the toggle switch in the hamburger menu. However, the theme should still automatically synchronize upon system theme change.

**Describe alternatives you've considered**
None, this seems like the easiest solution. Ideally Material You would be implemented, however this would be a much bigger change.

**Comment by BrayanDSO** [comment]
Already implemented on 2.16. You can try it out on one of the newest alphas
