### ISSUE TITLE
Show a snackbar instead of a toast II

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#13411]
# PRs will only be accepted with a video showing the exchange

**Is your feature request related to a problem? Please describe.**
Some actions show a toast but a snackbar should be shown

**Describe the solution you'd like**
Relace these toasts by snackbars

 #12552 continues

Note: **Don't** replace the toasts below:
- [x] in MultimediaEditFieldActivity.onRequestPermissionsResult() method
- [x] in DecksArrayAdapter.init {}
- [x] all toasts in CardTemplatePreviewer

Toasts that should be replaced:

Reviewer 
- [x] Reschedule - Reschedule for reviews
- [x] Reschedule - Reset progress

Text of a toast
- [x] Initializing tts
-  <s>Could not obtain microphone permission</s>
- <s>Could not obtain camera permission. Functionality has been disabled.</s>

Card browser -> select a card ->
- [x] Change deck -> Create a new deck -> Created deck

Deck picker -> long tap on a deck ->
- [x] Rename deck
- [x] Create subdeck

**Comment by savitore** [comment]
Please assign it to me

**Comment by savitore** [comment]
@snowtimeglass please assign

**Comment by mikehardy** [comment]
@savitore great! We will not assign this issue though

Anyone that wants to work on this issue should simply leave a comment indicating which specific one they are currently working on, then propose one PR at a time fixing them

**Comment by SanjaySargam** [comment]
> Reviewer
> [ ] Reschedule - Reschedule for reviews
> [ ] Reschedule - Reset progress

I am working on Reviewer.kt

**Comment by Arthur-Milchior** [comment]
Edited the initial post with `- [ ]` to ensure we have actual checkbox

**Comment by rohit9625** [comment]
Well, it didn't close till now. I just want to ask how can I test the toast and at which activity it's showing the toast that is to be replaced by snackbar.

**Comment by pavreh** [comment]
There are more toasts which need to be replaced. You can see a list in the issue description. E.g. "Initializing tts" you can test so you switch on Text to speech in advanced settings. Then start to study.

**Comment by rohit9625** [comment]
Hello @pavreh, I am facing an issue in that I am unable to find that XML file where I can get the view to set snackbar. Can you please help me to find out?

**Comment by rohit9625** [comment]
@pavreh I have added snackbar for deck creation. This is the before and after - 
**Before**
![Before](https://github.com/ankidroid/Anki-Android/assets/101377978/b0f4f7ee-3535-4de9-a8d2-976e7feedd7c)

**After**

![After](https://github.com/ankidroid/Anki-Android/assets/101377978/c85920cf-b001-47cc-8bd3-27416330ef73)


Please ensure this change so that I can proceed further.

**Comment by pavreh** [comment]
@rohit9625 Thank you for the contribution. But the snackbar should appear above FAB. See #14403 for more info.

Is this affected too by the change? Card browser -> select a card -> Change deck -> Create a new deck -> Created deck

**Comment by Maan-Sharma** [comment]
hey ,can I work on it

**Comment by ABHAYISm** [comment]
I would be working on text of a toast.

**Comment by nfragiskatos** [comment]
@pavreh 

The following tasks can be checked as 'complete'. They were addressed by #14565 

Card browser -> select a card ->

    Change deck -> Create a new deck -> Created deck

Deck picker -> long tap on a deck ->

Rename deck
Create subdeck
