### ISSUE TITLE
Build failed while fixing warnings

### ISSUE THREAD

**Issue by Prachi-Jamdade** [ankidroid/Anki-Android#13414]
I was trying to fix some of the warnings. But then I'm facing the build issue while pushing my code. I haven't made any production code changes.

Here is the screenshot of what went wrong -

![image](https://user-images.githubusercontent.com/94190717/223354336-2fcc74b5-f583-4139-a068-7f5e60ad1126.png)

**Comment by david-allison** [comment]
Could you paste the text of the error so people can search for this?

**Comment by criticalAY** [comment]
For a faster response and better help you can also get into our [discord](https://discord.gg/StM3Fh7w) server. And you don't have to alter the gradle files as they won't cause any issues while building the project
