### ISSUE TITLE
Rename performPermissionRequest

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13413]
It should indicates that it returns whether the permission was performed or not. Intuitively, I'd guess it indicates whether we have permission or not, or something similar.

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/13261#discussion_r1111391658_

**Comment by pratyaksh1610** [comment]
It can be like `onRequestMultimediaPermissionsResult` since it deals with permissions of audio and camera.
