### ISSUE TITLE
Add a "full" build

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13431]
Currently we have two pairs of build. Amazon and Play.
Amazon does not allow to take picture. Play, soon, won't allow to throw to access all media. So we need a third build that has no artificial limitation. I'd suggest a name such as "full", given it's not related to a specific store, but just to have the full features.

This probably require to change ./tools/release.sh, so that this build is published on github.

Note: handle the backup prompt for full build as mentioned here: https://github.com/ankidroid/Anki-Android/pull/13424/commits/88cde70490430a7ba3c5843b15deb1108d2db029#r1147041922

**Comment by mikehardy** [comment]
We have a "full" build dimension now, remaining work is to alter release script / parallel release script to use it, along with the f-droid release

**Comment by BrayanDSO** [comment]
I haven't found anything to be changed on the release script, as we are going to keep releasing `play` versions to the play store, so nothing has changed.

I haven't found a F-droid script either, so I only fixed the parallel builds script

**Comment by david-allison** [comment]
F-Droid: 

Our metadata is: https://gitlab.com/fdroid/fdroiddata/-/commits/master/metadata/com.ichi2.anki.yml

I believe this uses the 'default' build script

https://f-droid.org/en/docs/Build_Metadata_Reference/ . maybe we need `gradle: ` here.
