### ISSUE TITLE
Scheduling settings per deck

### ISSUE THREAD

**Issue by rayzchen** [ankidroid/Anki-Android#13438]
**Is your feature request related to a problem? Please describe.**
See https://docs.ankiweb.net/deck-options.html#per-deck-daily-limits (feature added in v2.1.55)

**Describe the solution you'd like**
Some implementation of this, preferrably using the settings from my anki on PC.

**Describe alternatives you've considered**
Presets, but they are fiddly and not easy to bulk change. The only thing i want to change between decks is the new card limit, I want to use the same learning steps etc.

**Additional context**

**Comment by mikehardy** [comment]
This should be possible now, we are on 2.1.60 backend at the moment #13366 so the feature will "exist"
Not sure exactly what's required to do expose the feature but you *might* try the latest alpha, turn on v3 scheduler in advanced settings, and see if the deck options page already has it - I *think* we are simply exposing the upstream deck options page at this point.

Could be wrong though..

**Comment by rayzchen** [comment]
I don't see the options, nor do the decks have the correct number of new cards even with the v3 scheduler enabled.
