### ISSUE TITLE
Clarification for the "Deck" option in the "Edit Note" screen

### ISSUE THREAD

**Issue by euu2021** [ankidroid/Anki-Android#13439]
I was looking for a "Move Card" option in Ankidroid. At first, I thought it did not exist, because I could only find the "Deck" inside the "Edit Note" screen, and, as an experienced Anki user, I know that editing a Note is not the same as editing a Card. So, if I'm inside a "Edit Note" screen, changing the deck there will change the deck for the whole Note, right? No. To my surprise (a good surprise, because that was the feature that I was looking for), changing the deck there actually moves only the Card at hand, as explained in the manual:

> Changing the deck operates on the selected card (which is underlined in the "Cards" box). If a note type is chosen which has more than one card, only the currently selected card will be moved to the new deck.

So, for the sake of clarification, I suggest that the label "Deck" could be changed to something that clearly implies that what is actually moved is the card. For example: "Deck of the currently selected card", or something shorter, like "Card Deck", "Deck(Card)".

**Comment by SanjaySargam** [comment]
@pratyaksh1610 What are your views on this?
I think there is not need to change name of the label

**Comment by oakkitten** [comment]
This is pretty awful and needs fixing

**Comment by snowtimeglass** [comment]
>I suggest that the label "Deck" could be changed to something that clearly implies that what is actually moved is the card. For example: "Deck of the currently selected card", or something shorter, like "Card Deck", "Deck(Card)". 

If I'm not mistaken, the label "Deck" has already been changed to "Card deck" if the selected note has more than one card, on both the officially-released version and the latest beta. 
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/189585c5-d7b6-476a-affa-7ff7fbbf86ac" width="320px">

Whether there is no need for further improvement is another point, though.
