### ISSUE TITLE
[BUG]: Error when answering card after looking at another deck in Card Browser

### ISSUE THREAD

**Issue by yellowjello** [ankidroid/Anki-Android#13442]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Start reviewing cards in Deck A
2. Open up Card Browser and look at Deck B
3. Go back to reviewer and answer card

### Expected behaviour

- There should be no error
- The next card should be from Deck A

### Actual behaviour

The error differs between V2 scheduler and V3 scheduler

#### V2 Scheduler:
The next card is from Deck B instead of Deck A.

https://user-images.githubusercontent.com/5134058/225444060-b2748a2b-f954-41cb-9f6a-36641bccc336.mov

#### V3 Scheduler:
It gives a "not at top of queue" error

https://user-images.githubusercontent.com/5134058/225444192-41f953b5-1462-462c-a70a-f99ef643c2f4.mov

### Debug info

```text
AnkiDroid Version = 2.16alpha94

Android Version = 13

Manufacturer = Google

Model = Pixel 6

Hardware = oriole

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ1A.230205.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.154 Mobile Safari/537.36

ACRA UUID = 8cfb65c4-55b1-4985-b063-9d97def1ffa8

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

The bug is reproducible on both the old and new backends.

I do not believe this bug is present on the latest stable version on the Play Store

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
I am working on it

**Comment by SanjaySargam** [comment]
This bug is not reproducible when we use old backend

**Comment by SanjaySargam** [comment]
The Bug is reproducible only for deck (first deck)  having almost 2 cards in old backend

**Comment by SanjaySargam** [comment]
Using V3 scheduler
It's showing like this in my case
![Screenshot 2023-05-16 151703](https://github.com/ankidroid/Anki-Android/assets/65113071/1978e0b7-7b92-4e00-b1e2-fd73622a2fe7)
It is still there in latest release

**Comment by SanjaySargam** [comment]
Using V2 scheduler

It is also reproducible in latest release

**Comment by SanjaySargam** [comment]
This issue was introduced due to #9235

**Comment by yellowjello** [comment]
Yeah I believe what's happening is that the PR made it so that the current deck is set whenever the deck is changed in the Card Browser. And whenever the current deck is changed, the scheduler (or something related) will regenerate the review queue for the newly selected deck.

So when we go back to the reviewer, we are in an inconsistent state where the card we are reviewing is from a deck that is different from both the current deck and the deck for the regenerated review queue.

Potentially what we can do is keep track of the current deck when we leave the Reviewer and then when we go back, we can restore the previous deck by reselecting it as the current deck.

**Comment by SanjaySargam** [comment]
> Yeah I believe what's happening is that the PR made it so that the current deck is set whenever the deck is changed in the Card Browser. And whenever the current deck is changed, the scheduler (or something related) will regenerate the review queue for the newly selected deck.
> 
> So when we go back to the reviewer, we are in an inconsistent state where the card we are reviewing is from a deck that is different from both the current deck and the deck for the regenerated review queue.
> 
> Potentially what we can do is keep track of the current deck when we leave the Reviewer and then when we go back, we can restore the previous deck by reselecting it as the current deck.

Yes. This is what we supposed to do.
I will make a PR soon for this bug

**Comment by SanjaySargam** [comment]
I agree with @yellowjello 

> Going from Reviewer to Card Browser/Stats via back button

This is not a possible situation

@Arthur-Milchior, is it ok to implement the things, the way @yellowjello said

**Comment by yellowjello** [comment]
So what is the status of this right now?

We have already identified a potential solution that works with the user flows that currently exist in the app.
We also have people who are willing to work on this (@SanjaySargam if you are still available, otherwise I can work on this).

Is there anything still blocking this? Any edge cases that still need to be considered?

**Comment by SanjaySargam** [comment]
> I agree with @yellowjello 
> 
> > Going from Reviewer to Card Browser/Stats via back button
> 
> This is not a possible situation
> 
> @Arthur-Milchior, is it ok to implement the things, the way @yellowjello said

@yellowjello Yes, I am ready , just waiting for @Arthur-Milchior 's reply

**Comment by dae** [comment]
It would be great if you could let us know if this still an issue with the latest code (either by building from source, or waiting for a 2.17 alpha)

**Comment by yellowjello** [comment]
Yup. I was able to reproduce the issue with the latest code today.
