### ISSUE TITLE
[BUG]: System WebView Rendering Failure

### ISSUE THREAD

**Issue by gaul** [ankidroid/Anki-Android#13440]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Study JLPT Tango N4 Omega or JLPT Tango N5 MIA Japanese decks.  Note that these include sounds but I have muted the device.

### Expected behaviour

AnkiDroid should display all the cards without background interference or crash dialogs.

### Actual behaviour

Android kills background tasks and eventually shows an out of memory error message:
![2023-03-09 11 37 01](https://user-images.githubusercontent.com/848247/225230862-48989967-aa2e-4381-b766-c9bbe7e58487.png)

### Debug info

```text
AnkiDroid Version = 2.15.6

Android Version = 13

Manufacturer = samsung

Model = SM-T570

Hardware = exynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-T570 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.58 Safari/537.36

ACRA UUID = 9e1fa5cb-fd02-4cab-b6c4-37dcd1c7f642

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Sorry for the trouble - can you try the latest alpha from the releases page here? https://github.com/ankidroid/Anki-Android/releases - I *think* most crash issues are solved now
