### ISSUE TITLE
[Bug] Two identical questions and two identical answers per card despite not setting it that way.

### ISSUE THREAD

**Issue by AshiqIbrahim** [ankidroid/Anki-Android#13444]
###### Reproduction Steps

1. Startup ankidroid
2. Click on any deck to review (or study new cards)

###### Expected Result
One question per card- just the way the user put it.
For instance, 
![image](https://user-images.githubusercontent.com/128031783/225560751-3ef07430-21bc-4491-8e68-5f17c5e62d3e.png)
which is in anki desktop.

###### Actual Result
Two identical questions per card- not the way the user had set it up.
![image](https://user-images.githubusercontent.com/128031783/225561583-830ff43d-54d0-4cb6-b90d-086c947d54b6.png)
which is in ankidroid.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.15.6
Android Version = 13
Manufacturer = samsung
Model = SM-A515F
Hardware = exynos9611
Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A515F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36
ACRA UUID = 353c5cce-9928-4546-8ab3-f448aa0919d4
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by snowtimeglass** [comment]
Hi, could you please show me a screenshot of Anki Desktop, which shows the card identical to the "actual result"?

**Comment by AshiqIbrahim** [comment]
> Hi, could you please show me a screenshot of Anki Desktop, which shows the card identical to the "actual result"?
Here is an example of the front of a card.
![image](https://user-images.githubusercontent.com/128031783/225605761-85c1af13-5d5e-439f-8609-8d4ae61f2fa4.png)
Here is an example of the back of a card.
Both of which are in anki desktop, and the issue outlined doesn't occur there although it does happen in my ankidroid (as I showed in the screenshot in my message above)
