### ISSUE TITLE
[BUG]: Unintentional return to logged in state after logout and reinstallation

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#13447]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Log out from AnkiWeb, on AnkiDroid
 ([Settings] -> [Sync] -> [AnkiWeb account] -> [Log out])
1. Uninstall AnkiDroid
1. (Optional)
  Delete AnkiDroid directory, that is, `/storage/emulated/0/AnkiDroid` (with the intension of eliminating information of the uninstalled AnkiDroid above as much as possible)

    Note: the storage migration hasn't been done on the AnkiDroid above yet.
1. Install AnkiDroid again
1. Check AnkiWeb account on AnkiDroid
   ([Settings] -> [Sync] -> [AnkiWeb account])

### Expected behaviour

The screen for logging in gets shown.

### Actual behaviour

Your AnkiWeb account has already logged in.

### Debug info

```text
AnkiDroid Version = 2.16alpha94

Android Version = 9

Manufacturer = OPPO

Model = CPH1983

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; CPH1983 Build/PKQ1.190519.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36

ACRA UUID = cc3e7cfb-1d54-44d6-9dfa-6fee671e9eef

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

No other debug build or parallel build is on this device.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by ParthTagalpallewar** [comment]
Hello @snowtimeglass, I tried all the above steps that you mentioned above. I tested reproduction above mention bug by following 2 ways:
1. Logging out from AnkiDroid using (setting->sync->AnkiWeb account->logout) and deleting folder AnkiDroid in file manager of Physical Device.
2. Logging out from AnkiDroid using (setting->sync->AnkiWeb account->logout) and not deleting folder AnkiDroid in file manager of Physical Device. 

In both the above cases, ankidroid shows me option to log in to AnkiWeb account after navigating to (setting->sync->AnkiWeb account)

**Comment by snowtimeglass** [comment]
Hello @ParthTagalpallewar Thank you for taking the time to verify the steps. I’ll look into conditions some more.

**Comment by snowtimeglass** [comment]
- On another physical device (Android 11), I have not been able to reproduce this issue so far.

- After restarting the issue-produced device (Android 9), this issue was reproduced.

- On the issue-produced device, AnkiDroid directory is `/storage/emulated/0/AnkiDroid` **even after** uninstalling and reinstalling alpha94.
  (Uninstall alpha94 -> Reinstall alpha94 -> Open the app -> [Settings] -> [Advanced] -> [AnkiDroid directory])

**Comment by mikehardy** [comment]
I am guessing - I could be wrong - but I wonder if you have it set up such that you are backing up your account / app information to Google on the Android 9 where it reproduces, and on the Android 11 device you are not?

My hypothesis is that the prefs XML (where the login information and collection path information is stored) is being backed up + restored.

**Comment by snowtimeglass** [comment]
@mikehardy I've confirmed that your hypothesis is right. Disabling "Automatic restore" in settings of the Android device stops this "issue" from occurring.
<img src="https://user-images.githubusercontent.com/10436072/226244633-03f10d8f-249a-45aa-a6bb-64d8dc0db25f.png" width="320px">

Thank you for your pertinent advice!
