### ISSUE TITLE
[BUG]: A toast for Scoped Migration is shown in the system language instead of the configured language

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#13458]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. [Settings] -> [Language] -> Select any language other than the system language
   - In the following example, the system language is Spanish, and the language configured on AnkiDroid is German.
2. (Optional) Sync to check if the issue of #13369 is reproduced
   - The issue (13369) wasn't reproduced on my environment, so I suppose that the issue and the following issue are separate ones.

3. Tap [Migrate to scoped storage] icon -> [Migrate]
4. Wait for the migration to complete successfully

### Expected behaviour

The toast of "Migration successful" is shown in German (the language configured on AnkiDroid) as `Migration erfolgreich`

### Actual behaviour

The toast of "Migration successful" is shown in Spanish (the system language) as `Migración exitosa`
<img src="https://user-images.githubusercontent.com/10436072/226325560-4821628a-ceeb-4eab-b318-3da8ee196db6.png" width="320px">

https://user-images.githubusercontent.com/10436072/226326117-562b481b-1ad2-4cee-b98d-90e36a159ae1.mp4

### Debug info

```text
AnkiDroid Version = 2.16alpha94

Android Version = 11

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36

ACRA UUID = 5030dae3-a0ba-453f-9da2-89735c9f64f0

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

N/A

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
My hypothesis is that the `Context` that `Service` uses wasn't updated with the new language. My current guess is that this is a framework issue, which can be better tested on a dummy app, but I don't think it is worth it

> The issue (13369) wasn't reproduced on my environment, so I suppose that the issue and the following issue are separate ones.

This specifically only happens if you were using an alpha version with the new backend enabled then upgraded to a newer alpha with the new language configuration code. As this would only affect a very few number of people and it has a workaround, I considered that is wasn't worth to fix it.

**Comment by snowtimeglass** [comment]
Thank you for the detailed explanation. I understand :-)
