### ISSUE TITLE
[BUG]: pop-up text not visible in tablet mode

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#13452]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Open a pop-up

![Screenshot_20230318-193436_AnkiDroid](https://user-images.githubusercontent.com/7422433/226129479-e9aa24f2-9eb2-4ab7-9c5f-9d5b5cbcbc47.png)
![Screenshot_20230318-193420_AnkiDroid](https://user-images.githubusercontent.com/7422433/226129487-78801bb0-66f5-4743-b08c-87d5e33f7e31.png)

### Expected behaviour

Visible text

### Actual behaviour

Text not visible

### Debug info

```text
AnkiDroid Version = 2.16alpha94

Android Version = 9

Manufacturer = samsung

Model = SM-T713

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-T713 Build/PQ3A.190801.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.58 Safari/537.36

ACRA UUID = 29702457-3edd-4c96-a52e-3c9397467f17

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Maybe related to https://github.com/ankidroid/Anki-Android/pull/9285

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
What in the ___ ?! Thanks for reporting this

**Comment by homocomputeris** [comment]
Unfortunately, still present in

AnkiDroid Version = 2.16.0beta1

Android Version = 9

ProductFlavor = full

Manufacturer = samsung

Model = SM-T713

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-T713 Build/PQ3A.190801.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/100.0.4896.58 Safari/537.36

ACRA UUID = 29702457-3edd-4c96-a52e-3c9397467f17

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by homocomputeris** [comment]
Maybe related https://github.com/ankidroid/Anki-Android/issues/13831

**Comment by homocomputeris** [comment]
Still in issue in the latest release.

**Comment by BrayanDSO** [comment]
Can you still reproduce it on the latest release?

**Comment by homocomputeris** [comment]
It seems to be fixed.
