### ISSUE TITLE
Fix a few visual issues with the ongoing-migration button

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#13453]
As a part of the storage migration effort, #13335 introduced a button with a migration progress indicator. I did not consider this change in #13368 and should rebase that on `main` and update it to work with with this new button. As a part of that, or maybe separately, I also want to change a few things about the button itself, namely:

* Make the semi-circle thinner, to be in line with the usual thickness of wireframe icon stroke width;
* Make it rotate to indicate action—if not rotating, the icon appears stuck when the number of files is large;
* Make it start not at 0% but at some non-zero value so that the user sees _something_ at the very beginning, _or_
* Make its ends rounded, protruding from the edges, so that at 0% it's a tiny circle—if this is easy.

I create this issue for the sake of discussing these changes.

Also, note that while migrating essential files, the user is still seeing the red arrow button. I suppose it would be nice if the button changed on the very beginning of the migration. However, I suppose this would be best tackled by slightly reworking everything so that the service is started right away, and not only while migrating media files.

**Comment by criticalAY** [comment]
>Make the semi-circle thinner, to be in line with the usual thickness of wireframe icon stroke width;
I can agree with this one

>Make it rotate to indicate action—if not rotating, the icon appears stuck when the number of files is large;
We have the progress dialog that indicates the progress just in case the user feels so and it is better off this way as it would be irritating to have a rotating progress bar that is what I feel .

>Make it start not at 0% but at some non-zero value so that the user sees something at the very beginning, or 
Nice one!

>Also, note that while migrating essential files, the user is still seeing the red arrow button. I suppose it would be nice if the button changed on the very beginning of the migration.
I fixed it in one of my PRs but I don't know how it came back so I will look into it and fix it

**Comment by oakkitten** [comment]
> as it would be irritating to have a rotating progress bar that is what I feel

I understand, and mostly agree, and I also think that it's easier to see the actual progress when the circle is not rotating. For this reason, I kept the circle still in my own app for a similar button that serves to upload files to a web server. However, in my case this is used primarily for photos and short videos, so you can expect the file to be uploaded in seconds, and you can clearly observe the progress at any moment.

However, with us it can be different. I tried migrating my entire collection, which has a few thousand of tiny images. The migration is so slow, and the progress just appears stuck. It's a big problem in the very beginning, when it is not clear that the button has a progress indicator. Slow rotation will clearly indicate that what the user is seeing is a progress indicator. And, it's very common for progress indicators to rotate on Android, I think it's more common than not. Finally, while the animation might be slightly irritating, it's not like the user is going to stare at the deck picker for a long time. In the reviewer they won't be seeing any annoying animations and that's where I assume users spend most of their time. So I don't think this is of much concern.

**Comment by criticalAY** [comment]
or maybe move the arrow-like animation or it make it blob up and down (but it would be a little more complex) so we either do this or make the rotation speed slow so it is not too catchy

**Comment by mikehardy** [comment]
Isn't there some android supplied thing that does a "shimmer" - something like that isn't too distracting but lets you know the thing is alive. Just a thought, I suck at UI, ignore it at will

**Comment by oakkitten** [comment]
Hm, shimmer?

Actually, I realized that we want to show something while calculating transfer size. So I suppose we could show counter-clockwise rotation while doing so, and then switch to a static progress indicator.
