### ISSUE TITLE
"restore to backup" on the first screen

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13464]
When you open AnkiDroid for the first time, a view offers to create an Ankiweb account.
It should also has a small link "restore from back-up", that would invite previous users who already have a backup to use it. It can essentially reuse the code from the deckpicker's menu "restore from backup"

**Comment by pratyaksh1610** [comment]
@Arthur-Milchior 

On this screen we require a `restore from back-up` link ? on clicking on `Sync from AnkiWeb` on startup . Am I on the right track ?


![ed](https://user-images.githubusercontent.com/76740999/226543342-03da9977-9572-4442-a789-5cf92d36fd10.png)

**Comment by pratyaksh1610** [comment]
@Arthur-Milchior Waiting for the reply.

**Comment by Arthur-Milchior** [comment]
Oops, sorry I missed it.
I don't understand your question @pratyaksh1610. 
We are not requiring anything. This extra link will add an option. But users can simply ignore it. 
Also, it should be on this screen:
![2023-04-15-163610_327x560_scrot](https://user-images.githubusercontent.com/357361/232230874-fdf0045d-ca53-46ed-b281-df380c42d208.png)
, as this option would be related to start-up and not to syncing with ankiweb.
