### ISSUE TITLE
Postpone requesting notification permission

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13465]
On the first install of AnkiDroid, it requires to authorize notification.
This should be postponed until this is actually required. And before the request is sent, a message should state why we need this permission. (Yeah, even if it's "obvious", if the user is changing notification settings)

The only exception may be if the preference already request notification. In this case, we could request permission when ankidroid start. Still, we should at least explain why we'll request it before showing the request.

We should also give an option for the user to just cancel/dismiss, in which case we'd turn notification off

**Comment by criticalAY** [comment]
But we use notification in other cases too like if a download fails or in scope storage if the user is not asked for the permission at start then how will those notifications be shown?

**Comment by BrayanDSO** [comment]
I'd do like many other apps do, and have a screen/dialog/menu/whatever on the app intro to request the notification.
