### ISSUE TITLE
Don't close the app before opening the `All files access` screen

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#13463]
So the user can return to the app after giving the permission, which is a better UX.

[This comment](https://github.com/ankidroid/Anki-Android/blob/56a195bf466c57e5a848e6ba8796a529816d5cab/AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt#L169) says that finishing the app is necessary, but I've seen it working other apps

Here's a demo of [logseq](https://github.com/logseq/logseq) (open source)

https://user-images.githubusercontent.com/69634269/226469079-2600f585-652c-4ea8-9a89-f1b76a05dc5a.mp4

**Comment by lonewolf2208** [comment]
I will be working on this issue
