### ISSUE TITLE
Alter PermissionManager Activity WeakReference to not be weak

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#13460]
So, as explained elsewhere, I was clearly wrong here. The callback is not kept in memory during permission request. This is why it's important to immediately register the callback, because the newly registered callback will be call.
Anyway, since this callback capture the activity, the activity lives as long as the callback. So the activity can't become null. So this weakRef is useless here

_Originally posted by @Arthur-Milchior in https://github.com/ankidroid/Anki-Android/pull/13261#discussion_r1133165467_

**Comment by david-allison** [comment]
This was already handled. Nothing to do
