### ISSUE TITLE
Integration con Word Reference

### ISSUE THREAD

**Issue by Cesuuur** [ankidroid/Anki-Android#13470]
First of all, thank you for such a useful tool. 

For those of us who study English, an integration with the Word Reference API would be fantastic, or with DeepL... Here's an idea.

**Comment by mikehardy** [comment]
Hi there - what you propose seems interesting,  but is not really a defect / is not actionable here.
Note that in our experience most of the APIs that would be interesting are paid services and we are a free app unable to obtain API keys, so they are not possible

However, you can add context-menu integrations for AnkiDroid such that once you use one of those other tools, if you long-press on a word, you can use it to quickly create a new AnkiDroid card.
