### ISSUE TITLE
Add a way to simulate/test storage migration on device

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#13480]
**Is your feature request related to a problem? Please describe.**

To test storage migration, I have to:
* Go to Settings > Advanced > AnkiDroid directory, and set it to a public folder
* Copy some files into `collection.media` of that folder

This is annoying and takes time and requires a computer (or a lot of tapping)

**Describe the solution you'd like**

A menu option to create a dummy collection + media in a public folder, perhaps with options to specify file number and sizes

**Comment by Arthur-Milchior** [comment]
I'll add to this issue related request from @oakkitten 

              I think this needs to be a more easily accessible action, e.g. a *main menu* option to “Create a fake deck” or something with the options to set:

* Collection location
* Number and sizes of media files to generate (e.g. 10-20 files of 1-10MB each)
* Whether or not some media files are referenced to by cards or not
* Maybe something else?

Also I'd love to have the option to crash during migration

Also I'd love to have the option to reset migration state

_Originally posted by @oakkitten in https://github.com/ankidroid/Anki-Android/issues/13854#issuecomment-1547777281_

**Comment by Arthur-Milchior** [comment]
I admit that I don't understand what it mean to reset migration state. Unless it means undoing the migration. Or do you mean to delete the scoped storage folder and restart from a new collection? Not entirely trivial with our current library, but can be done.

Crash is probably simpler. Do you have any preference when it should occur? Media migration? When moving the collection.anki2?

**Comment by oakkitten** [comment]
`MediaMigrationState.Ongoing` is determined in part by several variables such as `PREF_MIGRATION_DESTINATION` or `PREF_MIGRATION_ERROR_TEXT`, simply removing all them and restarting deck picker should work. Maybe stop the service if it's running. (Note that this should raise `CancellationException` in `MigrationService` which is **not** dealt with in any specific way. Not sure if makes dealing with it in a specific way. Also note that the service will not stop until after all binders will unbind, which should happen on activity restart. And in current implementation `PREF_MIGRATION_ERROR_TEXT` will be set.)
