### ISSUE TITLE
[Bug] Don't allow search collection/s when there isn't any

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13489]
###### Reproduction Steps

1. Make a fresh install
2. Go to card browser
3. Search any cards let say "xyz" in search tab

###### Actual Result
Shows a result that no such card found in the default deck but there are no decks created by now

###### Expected Result
The search should be allowed or hidden until there are any cards or decks
OR
Create a UI background like the one we have in DeckPicker when there are no Decks/Cards and show it till the collection exists and don't allow search

###### Debug info
AnkiDroid Version = 2.16alpha94-debug

Android Version = 12

Manufacturer = OnePlus

Model = EB2101

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; EB2101 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.118 Mobile Safari/537.36

ACRA UUID = 4ffa3fea-6003-44a0-b914-0919027ac81d

New schema = true

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
> The search should be allowed or hidden until there are any cards or decks
> OR
> Create a UI background like the one we have in DeckPicker when there are no Decks/Cards and show it still the collection exists and don't allow search

Nice Idea!!

**Comment by pratyaksh1610** [comment]
I would like to work on this.

**Comment by dae** [comment]
I'm afraid I don't think this is worth implementing, but please feel free to reply if you disagree.

**Comment by criticalAY** [comment]
This would make the UI better that if there isn't any collection it still allows us to search where as there is a similar case when the deck count is more than 20 then only the search bar appears so would like this to be kept open
