### ISSUE TITLE
[BUG]: "Metered_sync_warning" shown twice on full sync

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13504]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

* Get a fresh ankidroid install (probably work with any install as long as a full sync is required)
* sync with an already existing ankiweb account with data
* press the sync button
* use a metered connection

### Expected behaviour

Be asked once to confirm you want to sync

### Actual behaviour

Get asked twice.

### Debug info

```text
current main: f83f19004d.
```

### (Optional) Anything else you want to share?

First time comes from `R.id.action_sync` in DeckPicker.
Second time from `Connection.onPostExecute`, which call `Sync.onPostExecute`

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pratyaksh1610** [comment]
I am working on it.

**Comment by Arthur-Milchior** [comment]
Any news @pratyaksh1610 ?
