### ISSUE TITLE
F-Droid: use 'full' build

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13516]
Our metadata is: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.ichi2.anki.yml

I believe this uses the default build script

https://f-droid.org/en/docs/Build_Metadata_Reference/ . maybe we need `gradle: ` here.

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/13431#issuecomment-1485845231_

**Comment by david-allison** [comment]
Similar issues (no actual fix provided)

https://gitlab.com/fdroid/fdroiddata/-/issues/2588

https://gitlab.com/fdroid/fdroiddata/-/issues/2883

**Comment by david-allison** [comment]
Likely best to ping a maintainer.

I suspect from a quick glance:

* Disable AutoUpdateMode in the metadata
* Manually perform an update with the new script
* Turn on AutoUpdateMode

**Comment by shuvashish76** [comment]
But https://github.com/ankidroid/Anki-Android/issues/9259#issuecomment-1315279057 issue still open.
Do you want universal or split apks for F-Droid?

> Likely best to ping a maintainer.

https://gitlab.com/fdroid/fdroiddata/-/issues/3047

**Comment by mikehardy** [comment]
I believe this is as easy as just switching this from `play` to `full`:
https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.ichi2.anki.yml?ref_type=heads#L772

https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13629 I think is correct?

**Comment by mikehardy** [comment]
I believe this is done, based on an examination of our f-droid page: https://f-droid.org/en/packages/com.ichi2.anki/
It is reporting all the arches and a roughly 71MB file which corresponds to a "full" universal build so it should work for everyone

**Comment by david-allison** [comment]
* Download 2.16.5: https://f-droid.org/repo/com.ichi2.anki_21605300.apk
* Test on API 33
* ✅ Asks for 'Manage All Files'

Definitely resolved
