### ISSUE TITLE
Please update ankiToggleFlag() in Javascript API

### ISSUE THREAD

**Issue by TygerKu** [ankidroid/Anki-Android#13526]
Could you please update ankiToggleFlag() to support Pink Turquoise and Purple? Thanks for your work.

**Comment by mikehardy** [comment]
Have you tried the latest alphas? I believe the support all the colors - https://github.com/ankidroid/Anki-Android/releases

**Comment by TygerKu** [comment]
Yes, I have tested it on 2.16alpha95 before open this issue, and it still only supports 4 colors. If it exceeds 5, it will prompt "No Flag Found" in the console.

**Comment by lukstbit** [comment]
Thanks for reporting this, I've made a PR which should fix this from my limited testing(as I haven't used the js API myself). Merging that PR would close this issue, so I'm asking you to also verify this is fixed when the new alpha drops.
