### ISSUE TITLE
App Permissions Screen: Don't show on unsupported devices

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13520]
At an unknown API level, "Allow management of all files" is no longer available in the app permissions screen. 

Determine the API level which disables the functionality and fix the calling code to perform an alternate action:

https://github.com/ankidroid/Anki-Android/blob/09b3f0a2f54ab2d3ab19c2b30442d807d1b860c8/AnkiDroid/src/main/java/com/ichi2/anki/permissions/PermissionManager.kt#L180-L185

----

> No longer exists on API 33 (!). 
> Here's a screenshot of API 30
>
> <img width="371" alt="Screenshot 2023-03-28 at 01 28 01" src="https://user-images.githubusercontent.com/62114487/228096026-3c15dda7-c089-4054-afd6-ada5679a518f.png">
>

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/13519#discussion_r1149907837_

**Comment by david-allison** [comment]
This is non-blocking as:

* It's not on a widely distributed APK
* It's on a path which is unlikely to be hit (Android missing a permissions screen: "all files access"). Technically this is optional, but unlikely to be missing

**Comment by BrayanDSO** [comment]
this is on the `onPermissionPermanentlyDenied()` path

**Comment by lonewolf2208** [comment]
I would like to work on this issue

**Comment by mikehardy** [comment]
I guess ?

- check for API33+ in onPermissionPermanentlyDenied,
- display a dialog that explains to the user why full access is needed (I think we already have a string explaining our need for storage access, and we should reuse it)
- on positive action on that dialog open the generic settings page for the app

**Comment by oakkitten** [comment]
I'm sorry I don't understand this conversation. As I understand, what @david-allison is implying is that they want something like this (added comments):

```kt
if (intent.resolveActivity(packageManager) != null) {
    // This opens “Allow access to manage all files” screen.
    // (See screenshot below.)
    startActivityWithoutAnimation(intent) 
} else if (/* TODO */) { 
    // This opens AnkiDroid's “App permissions” screen.
    // You can use that to open “File and media permission” screen 
    // that allows choosing “Allow management of all files”.
    // (See screenshot in the 1st comment.)
    // However, on some API level this action has been removed,
    // So we need to do something else!
    showAppPermissionManagementScreen()
} else {
    // ?? Something else ??
}
```

Also it seems that we are yet to determine on which API level “Allow management of all files” has disappeared from the “App permissions” screen. Or are we sure it's 33+?

<img src=https://user-images.githubusercontent.com/1710718/229323162-ce35354c-3359-418e-9eca-d178126b39ac.png width=300>

**Comment by BrayanDSO** [comment]
My question is if we are really sure that there is a scenario where the “All files access” screen can not be opened or the `if-else` block is there just as a possibly unnecessary safety measure. 
If there are not a way to give the permission, simply use the app private directory as collection path as Play store builds do

**Comment by BrayanDSO** [comment]
Better alternative: tell the user to go to System settings > Apps > Special app access > All files access > Grant AnkiDroid the permission (tested on SDK 33 emulator and my Samsung Android 13 phone)

**Comment by MudssirAhmed** [comment]
I checked in API 34, The All-File-Access page is showing and working. Can someone mention the API at which this permission is not working?

**Comment by david-allison** [comment]
It works in all API levels on standard devices. 

The documentation states that it's not guaranteed to work.

The fallback screen is the App permissions screen, and at some API level a user is no longer allowed to grant 'all files' access there.
