### ISSUE TITLE
[Bug] Videos are not displayed in full screen

### ISSUE THREAD

**Issue by rgrunbla** [ankidroid/Anki-Android#13546]
###### Reproduction Steps

1. Use the deck attached to this bug report and import it in ankidroid
2. Open a card

The deck was generated using genanki. The video has a avc1 codec (H.264), and I also tested with a hev1 (H.265) codec. Both are listed on https://developer.android.com/guide/topics/media/media-formats#core

###### Expected Result

The video is displayed with most of the screen.

###### Actual Result

The video is shown very small.

###### Debug info

```
AnkiDroid Version = 2.15.6

Android Version = 13

Manufacturer = Google

Model = Pixel 7

Hardware = panther

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 7 Build/TQ2A.230305.008; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36

ACRA UUID = 77467b5e-1568-4be5-8a17-1a498b9a34c0

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

# Example of video deck

[deck.apkg.zip](https://github.com/ankidroid/Anki-Android/files/11146062/deck.apkg.zip)

# Illustration of the problem

[ankidroid.webm](https://user-images.githubusercontent.com/42433779/229726276-4810cb94-26cd-4b53-bff2-b14b58a57daf.webm)

**Comment by hai265** [comment]
I'm on 2.16alpha94 and the video looks fine, maybe try updating to latest version and see if it works.

**Comment by rgrunbla** [comment]
> I'm on 2.16alpha94 and the video looks fine, maybe try updating to latest version and see if it works.

I just tried this 2.16alpha94 version, and, indeed, it works. I'll wait for the next stable and check whether it works or not.

**Comment by SanjaySargam** [comment]
Tested in latest release and works fine for me
@mikehardy You can close this issue....

**Comment by BrayanDSO** [comment]
OP says it was solved
