### ISSUE TITLE
Japanese fonts load slow and are fonts are being reloaded on every card front and back [BUG]: 

### ISSUE THREAD

**Issue by basvdelsen** [ankidroid/Anki-Android#13543]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Download Japanese font, use in card, enjoy the lag.  I use Noto Sans JP and TakaoPMincho.

### Expected behaviour

Fonts loads on first card, then no longer need to load up the font on subsequent cards.

### Actual behaviour

Fonts are being reloaded on every card front and back, And with Japanese fonts being quite big this causes fonts to show up with a delay.

### Debug info

```text
AnkiDroid Version = 2.15.6

Android Version = 9

Manufacturer = samsung

Model = SM-G950F

Hardware = samsungexynos8895

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-G950F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36

ACRA UUID = e2eb26a6-3827-4714-9df2-8f00ce681482

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

I've seen this issue raised in 2018, not sure why this is still an issue?

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
This is a duplicate, you literally commented on the duplicate issue, I just replied to it as I was processing notifications.

**Comment by ElnuDev** [comment]
Should be marked duplicate of #4856, if anyone stumbles across this thread and is looking for that issue.

**Comment by david-allison** [comment]
Thanks @ElnuDev. Duplicates are a new (ish) feature of GitHub, which I don't believe was available at the time
