### ISSUE TITLE
Google Translation while using Advanced Editor in Application

### ISSUE THREAD

**Issue by Abhishekverma2002** [ankidroid/Anki-Android#13547]
I have been using your application and is always frustrated by that translation option in your Advanced Editor Section while making a card.
Because I have not downloaded the dictionaries offered by the application and so not able to use that option well. 
I would highly appreciate you guys to include the feature of google translation in the application so it become easier for all the users to  use this feature well. 
Would be keen to know your views on this as well.

**Comment by mikehardy** [comment]
Hi there!

Google requires you to use an API to use their translation in an app, and they charge for it. We have no ability in an open source app to obtain an API key and pay for its use in translation, so this is not technically feasible.
