### ISSUE TITLE
AlertDialogBox while exiting the Application

### ISSUE THREAD

**Issue by Abhishekverma2002** [ankidroid/Anki-Android#13551]
An alertDialog box is a good option to have while on an application. So that you cannot accidentally close the application.

**Comment by criticalAY** [comment]
There is an option that you can enable and you will have to tap back twice to exit the application so it already exists thanks though !!

**Comment by Abhishekverma2002** [comment]
@mikehardy @criticalAY Can you suggest me some issues for this repo. I am currently learning Android Development in java.

**Comment by SanjaySargam** [comment]
> @mikehardy @criticalAY Can you suggest me some issues for this repo. I am currently learning Android Development in java.

This repo is in Kotlin
You can start with good first issues
