### ISSUE TITLE
[BUG]: Anki does not detect browser

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#13567]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Open advanced settings
- Tap Third-party apps

### Expected behaviour

Open web page

### Actual behaviour

![Screenshot_20230407-221639_AnkiDroid](https://user-images.githubusercontent.com/7422433/230673485-3aabf497-fb75-40d9-8e7c-de0d2ebbda59.png)

### Debug info

```text
AnkiDroid Version = 2.16alpha97

Android Version = 13

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; ONEPLUS A6003 Build/TQ1A.230205.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/109.0.5414.118 Mobile Safari/537.36

ACRA UUID = d955bcd1-fd00-4663-a668-76961b1f8863

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by oakkitten** [comment]
Can reproduce on my device and I'm pretty sure I have a browser (actually, more than one)

**Comment by david-allison** [comment]
https://developer.android.com/about/versions/11/privacy/package-visibility
