### ISSUE TITLE
Feature request: Create a keyboard shortcut to search in the card browser.

### ISSUE THREAD

**Issue by davide-casiraghi** [ankidroid/Anki-Android#13566]
When using an external keyboard on a tablet it's not possible to access the search field using a shortcut. I have to tap on the screen the lens icon.

I would love to have a keyboard shortcut like CTRL+F to access the search field, so I can type from the keyboard without touching the tablet screen. Then to get all the results when I press ENTER.

**Comment by Chandra-Mauli-Sharma** [comment]
I would like to work on this issue. If we are planning to include it in prod.
