### ISSUE TITLE
Support nested cloze notes

### ISSUE THREAD

**Issue by RasmusRendal** [ankidroid/Anki-Android#13570]
**Is your feature request related to a problem? Please describe.**
The main Anki application supports [nested cloze deletions](https://docs.ankiweb.net/editing.html#cloze-deletion):
 > From version 2.1.56, nested cloze deletions are supported. For example, the following is valid:
> ```
> {{c1::Canberra was {{c2::founded}}}} in 1913
 >```
> The inner cloze is entirely nested within the outer. 

However, when I create this card it does not work in Ankidroid, at least not as of version 2.15.6:
![Screenshot_20230408-091950](https://user-images.githubusercontent.com/19538856/230708977-acb5cde1-3b53-44c5-a509-bce29ae9ff0e.png)

**Describe the solution you'd like**
I would like nested cloze notes to work exactly as in the desktop application:
![Untitled](https://user-images.githubusercontent.com/19538856/230709143-d9bf7475-8d76-4696-965a-1cb34484e7ed.png)

**Describe alternatives you've considered**
Currently, I'm just tagging the notes where I use nested cloze, and using a filtered deck to avoid reviewing them on my phone.

**Comment by mikehardy** [comment]
Hi there - please try the latest releases as they have been improve substantially https://github.com/ankidroid/Anki-Android/releases

**Comment by RasmusRendal** [comment]
Just tried it, the behaviour is identical.

**Comment by BrayanDSO** [comment]
Try enabling the new backend setting at Settings > Advanced > Use the new backend.

It worked well here after enabling it

**Comment by RasmusRendal** [comment]
That worked, thank you!

**Comment by x51mon** [comment]
> Try enabling the new backend setting at Settings > Advanced > Use the new backend.

Is this supposed  to work in AnkiDroid 2.16.5?

My cards with a nested cloze are empty and just showing the hint "This card is empty. Use the “Empty cards” option from the menu on the deck list screen.", on the desktop version they work just fine. I have the new backend enabled.

**Comment by mikehardy** [comment]
We've moved on. The new backend is now the only backend with the upcoming 2.17 release and it's in beta now.

Current recommendation is to join the beta program and you should get 2.17beta2 (at least, we release pretty quickly) and nested close should work https://ankidroid.org/#betaTesting
