### ISSUE TITLE
Discuss : Yellow tint when using autofill to log in 

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13572]
There is a yellow tint when we click autofill from the keyboard on the login screen which most apps don't use and in my opinion, is not good UI as there are security layers in the keyboard itself plus our application doesn't use something strange it is just being used to login to the ankiweb i.e. not any banking site
So, I would like the tint to be removed from the UI/ or disable the autofill
Related #13532

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Expected behavior per google. It is not going to change.

**Comment by criticalAY** [comment]
Okayo no issue then we are good to go, Thankyou
