### ISSUE TITLE
[BUG]: Difference in speed of rebuilding filtered decks through two different options 

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#13580]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Create a filtered deck.
- Empty it.
- Rebuild it by following these steps:
  - Click on the filtered deck name in the Decks screen
  - Click on the three-dot-menu on the upper right corner
  - Click rebuild.
- Empty the filtered deck again.
- Rebuild it again by following these steps:
  - Long press the filtered deck name in the Decks screen
  - Click rebuild.

### Expected behaviour

Both the approaches should be equally fast in rebuilding the filtered deck.

### Actual behaviour

The first approach (through the three-dot-menu) is faster.

### Debug info

```text
AnkiDroid Version = 2.16alpha97

Android Version = 12

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g62 5G Build/S2SSIS32.18-12-4-6; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by RobozinhoD** [comment]
working on this

**Comment by RobozinhoD** [comment]
> Rebuild it by following these steps:
Click on the filtered deck name in the Decks screen
Click on the three-dot-menu on the upper right corner
Click rebuild.

@user1823 I can't reproduce this, can you share a screenshot?. I found a scenario where I click on the numbers in the right of the filtered deck name then click the rebuild (🔁 icon) button at the top, is that it?

**Comment by mikehardy** [comment]
I see @user1823 is using "std3" which may imply "new backend", I wonder if the two different methods may access new backend vs legacy backend and @RobozinhoD you don't reproduce because you are either on std2 scheduler or have not turned on the new backend? Just a hypothesis, but I advance it because it's so easy to check

**Comment by user1823** [comment]
> I can't reproduce this, can you share a screenshot?

Here are the screenshot:
<img width="30%" src="https://user-images.githubusercontent.com/92206575/230805537-701b7ce7-b826-4ded-b359-8c3deea40203.png"><img width="30%" src="https://user-images.githubusercontent.com/92206575/230805749-8981a0a5-d3cc-43b9-8a85-24b990f60a70.png">


> I see @user1823 is using "std3" which may imply "new backend"

Yes, I am using the new backend and the v3 scheduler.

**Comment by RobozinhoD** [comment]
@user1823, how many decks do you have? And how much different is the speed between the options? This may happen because rebuilding the deck list UI is a more expensive task

**Comment by user1823** [comment]
> how many decks do you have?

I have 2 large decks and 2 smaller ones (with 2-3 cards each).
In addition, I have 7 filtered decks, 6 of which are not in use and are empty currently. I use the remaining one. This filtered deck filters the due cards from one of my larger decks (with 98k total cards and 8k cards in use).

> how much different is the speed between the options?

With the first option (through the three-dot-menu), rebuilding the filtered deck takes less than a second.

With the second option (by long-pressing the filtered deck name), rebuilding the filtered deck takes about 20-30 seconds.

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by dae** [comment]
If it's still an issue when building from source or with a future 2.17 alpha, please let us know.
