### ISSUE TITLE
Can’t access existing collection after upgrading from GitHub versions after alpha95 to a play version

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#13588]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Upgrade from 2.16alpha95-universal to 2.16alpha97-play-universal
2. Open App

### Expected behaviour

The existing collection used in alpha95 is accessible (after one or some dialog messages)

### Actual behaviour

The existing collection used in alpha95 is inaccessible as the dialog message of "Inaccessible collection" is shown.
<img src="https://user-images.githubusercontent.com/10436072/230844124-93bf0f66-352a-4a09-aebe-6bc1ce8e7544.png" width="320px">

https://user-images.githubusercontent.com/10436072/230843770-e1c1017c-0fa4-431a-9040-2aeae9da3a66.mp4

### Debug info

```text
AnkiDroid Version = 2.16alpha97

Android Version = 11

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/110.0.5481.153 Mobile Safari/537.36

ACRA UUID = 88707bf0-b55e-4e77-a11a-552bfe63f79e

New schema = false

Scheduler = Not found

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

- Reproduced consistently on my Android 11 device above.
- Not reproduced if upgrading to alpha97-_full_-universal instead of alpha97-_play_-universal
- Not reproduced on my Android 9 device.
- On App info screen of alpha97, AnkiDroid icon isn't shown. 
  <img src="https://user-images.githubusercontent.com/10436072/230845830-7edceb52-db60-4e3f-884d-106b7c1f5efd.png" width="320px">

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Smaller issue than I thought. This is specific from migrating from a version with the `All files access` permission to a `play` version. As this currently only impacts GitHub users and they can revert this with a `full` build, this isn't a high priority issue

**Comment by BrayanDSO** [comment]
> On App info screen of alpha97, AnkiDroid icon isn't shown.

It shows up on both my phone (Samsung Android 13) and emulator (android 13 also)

**Comment by BrayanDSO** [comment]
Too much work, too small reward fixing this. Closing it
