### ISSUE TITLE
[BUG]: `DirectoryNotEmptyException` when re-running the app that has an ongoing migration

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#13609]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

* Start migration
* Kill app
* Re-run app

### Expected behaviour

Migration resumes

### Actual behaviour

“Migration failed” in the notification, and this in logcat

```
W  Failed while executing com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$SingleRetryDecorator@a94d0d4
   java.nio.file.DirectoryNotEmptyException: /storage/emulated/0/AnkiDroid/collection.media
       at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
       at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
       at java.nio.file.Files.delete(Files.java:1126)
       at com.ichi2.compat.CompatV26.deleteFile(CompatV26.kt:76)
       at com.ichi2.anki.servicelayer.scopedstorage.DeleteEmptyDirectory.execute(DeleteEmptyDirectory.kt:41)
       at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$SingleRetryDecorator.execute(MigrateUserData.kt:313)
       at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor.executeOperationInternal$AnkiDroid_playDebug(MigrateUserData.kt:361)
       at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor$execute$1.invoke(MigrateUserData.kt:351)
       at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor$execute$1.invoke(MigrateUserData.kt:350)
       at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$MigrationContext.execSafe(MigrateUserData.kt:191)
       at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData$Executor.execute(MigrateUserData.kt:350)
       at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData.migrateFiles$moveRemainingFiles(MigrateUserData.kt:516)
       at com.ichi2.anki.servicelayer.scopedstorage.migrateuserdata.MigrateUserData.migrateFiles(MigrateUserData.kt:525)
       at com.ichi2.anki.services.MigrationService$onStartCommand$1.invoke(MigrationService.kt:226)
       at com.ichi2.anki.services.MigrationService$onStartCommand$1.invoke(MigrationService.kt:221)
       at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)
```

### Debug info

```text
AnkiDroid Version = 2.16alpha97-debug

Android Version = 11

Manufacturer = Xiaomi

Model = Mi A2

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Mi A2 Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 3121aa6c-3e3d-4250-8dd4-66ccd7be24b0

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

On ad538ed9efb2e8185032b8f55206654e465271b3

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by oakkitten** [comment]
Strange, `contentOfDirectory` (API 26) says that there's 0 files in `/storage/emulated/0/A/collection.media` and 2 files in `/storage/emulated/0/A` (`collection.anki2-journal` and `collection.media`), but both folders have more files

**Comment by oakkitten** [comment]
Also the dialog says 

> Migrated 0 MB of -62 MB

**Comment by oakkitten** [comment]
Note: I'm running current-ish main with playDebug/debug variant. To test the migration I ran adb commands from [here](https://github.com/ankidroid/Anki-Android/commit/56a195bf466c57e5a848e6ba8796a529816d5cab) and also had to enable “Allow access to media only” in permissions (the only option I have)

**Comment by oakkitten** [comment]
I ran into the issue again on a branch stemming from current main. For the record:
* I verified that we have the read/write permissions and the folder's `canWrite()` is `true`;
* `adb shell dumpsys package` also lists the same permissions;
* If I create a new folder it is appears in `listFiles`, but not any new files;
* Restarting the device doesn't help;
* Re-running `adb shell` commands from 56a195bf466c57e5a848e6ba8796a529816d5cab *does* help;
* After re-rerunning the above commands and successfully finished migration, `adb shell dumpsys package` output is unchanged.

Might be a glitch in the system, perhaps only appearing on my particular Android flavor.

**Comment by mikehardy** [comment]
**2.16.0beta2 is currently  blocked on this**

it appears to be difficult to hit, and some low-level thing according to all the chatter on the issue. I want a cheap effective solution to unblock the thing.

Here's my thought: We cannot easily reproduce this, and if we can it may just lead to a rabbit-hole of vendor-/API-specific low-level issues we don't control anyway. So I want to make the app resilient to it vs fixing it.

The problem as I see it is that the migration is effectively over but the final deletion of media directory fails? How about:

- If there are no more files left to migrate in a directory *and*
- directory delete fails,
- we simply ignore that error and move on, from perspective of the migration?

Then the app is usable again and this problem is de-prioritized so we can release and move on

Open to any other ideas, anything that solves this any way from app usability perspective.

**Comment by oakkitten** [comment]
I do not understand why this is blocking. Suggest ignoring.

I can currently reproduce the issue so if anyone has any ideas about the things I can try please tell.

> If there are no more files left to migrate in a directory

No more files as reported by the `File` API or actually?

**Comment by david-allison** [comment]
Potential Diagnostics (as requested in Discord)

> Re-running adb shell commands from https://github.com/ankidroid/Anki-Android/commit/56a195bf466c57e5a848e6ba8796a529816d5cab does help;

1. Which one fixes it? 
2. If we re-request permissions (as done before `checkMedia`), does this resolve the issue? [can we replicate the `adb` commands inside the app]
    a. Has this issue been seen after https://github.com/ankidroid/Anki-Android/pull/13630 was merged?  
3. If a file is accessed by path `File(string)`:
   a. What does `.exists()` return
   b. can it be read, and therefore moved 
   c. can it be deleted?

**Comment by david-allison** [comment]
As I understand it, the issue is:

* There is a bug, causing `listFiles` etc... to only list a subset of media files
* Once there are no 'visible' files, the migration attempts to delete the 'empty' folder
* Deletion of the folder fails, as it's actually non-empty

----


> The problem as I see it is that the migration is effectively over but the final deletion of media directory fails? How about:
> 
> * If there are no more files left to migrate in a directory _and_
> * directory delete fails,
> * we simply ignore that error and move on, from perspective of the migration?

If we complete the migration at this point, then AIUI the media is partially migrated but we can't see the rest.

1. Most importantly, these missing files may appear as a 'delete' when syncing media
2. We don't know if the files are accessible in the `Reviewer`
    a. If they are, then the files are migrated when they're viewed, even though they're not listed in `listFiles` 
       i. As soon as we stop the migration, these files are no longer migrated when they're viewed
       ii. We could fix /most/ of these, but I don't feel this is feasible with the time that we have.


I'd like to understand more, as there may be easier workarounds.

If we can't reproduce this, I feel a specific error dialog + selection of options will suffice. 

* A user can manually move the files, which completes the migration
* A user can wipe + re-sync

**Comment by oakkitten** [comment]
> If a file is accessed by path File(string):
> a. What does .exists() return

Somehow it returns `true`

> b. can it be read, and therefore moved

`inputStream()` throws `java.io.FileNotFoundException` with the cause `android.system.ErrnoException`: open failed: EACCES (Permission denied) & errno 13

> c. can it be deleted?

No and `delete()` returns `false`

> If we re-request permissions (as done before checkMedia), does this resolve the issue?

Running `checkMediaStoragePermissionCheck.checkPermissions()` gives:

```
result = {PermissionsCheckResult@19679} com.ichi2.anki.permissions.PermissionsCheckResult@d1b7bcc
 allGranted = true
 permissions = {LinkedHashMap@19723}  size = 2
  "android.permission.READ_EXTERNAL_STORAGE" -> {Boolean@19730} true
  "android.permission.WRITE_EXTERNAL_STORAGE" -> {Boolean@19730} true
```

Running `checkMediaStoragePermissionCheck.launchPermissionDialog()` gives:

```
results = {LinkedHashMap@19946}  size = 2  @ com/ichi2/anki/permissions/PermissionManager.kt:57
 "android.permission.READ_EXTERNAL_STORAGE" -> {Boolean@19730} true
 "android.permission.WRITE_EXTERNAL_STORAGE" -> {Boolean@19730} true
```

With no effect on migration

> Which one fixes it?

This time none of the commands fixed it. But what did, is going to permission setting, and changing this setting from “Allow access to media only” to “Deny” and _back_ to “Allow”. ¯\\\_(ツ)_/¯

<img src=https://user-images.githubusercontent.com/1710718/236622373-f56cdb9a-1eca-4042-b82d-3f95569b8e50.png width=300>

**Comment by david-allison** [comment]
So this can be resolved with an error stating that the user should deny and re-approve permissions?

**Comment by oakkitten** [comment]
This definitely feels like a bug in the system. Denying and allowing again a permission should have no effect. I still see reasons to believe that this bug is very local. Until there's a second report about this issue, I'd not go beyond adding a note about this in the documentation.
