### ISSUE TITLE
[BUG]: Curly brackets from mathjax and cloze mismatch

### ISSUE THREAD

**Issue by mis-match** [ankidroid/Anki-Android#13606]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Code from Anki PC: `{{c1::<anki-mathjax>\sqrt{\frac{GM}{r}}</anki-mathjax>}}`
sync to AnkiDroid: `{{c1::\(\sqrt{\frac{GM}{r}}\)}}`

### Expected behaviour

expect:
![image](https://user-images.githubusercontent.com/96474692/232184058-be5d71cb-1d5b-4bee-af78-23e33af940f0.png)

### Actual behaviour

On AnkiDroid:
![image](https://user-images.githubusercontent.com/96474692/232184293-6ef1bbb8-9f3f-4cbe-b264-f67897a57bf6.png)
![image](https://user-images.githubusercontent.com/96474692/232184305-d418aaad-0b5c-4385-a418-fc5a9fc3065a.png)

I manually replace " `\(`" and "`\)`" into "`<anki-mathjax>`" and "`</anki-mathjax>`", but the cloze still match the brackets after the "r".

### Debug info

```text
AnkiDroid version: 2.16alpha97 and before
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
`{{c1::<anki-mathjax>\(\sqrt{\frac{GM}{r}}\)</anki-mathjax>}}`

I used this, it gives the output as expected
![Screenshot 2023-04-21 231908](https://user-images.githubusercontent.com/65113071/233702149-1e0733c5-e673-486a-8e5d-e0c6272233b6.png)

**Comment by mis-match** [comment]
> `{{c1::<anki-mathjax>\(\sqrt{\frac{GM}{r}}\)</anki-mathjax>}}`
> 
> I used this, it gives the output as expected
> ![Screenshot 2023-04-21 231908](https://user-images.githubusercontent.com/65113071/233702149-1e0733c5-e673-486a-8e5d-e0c6272233b6.png)
> 

i couldn't recur your output on 2.16alpha97. which version do you use?

![Screenshot_20230422_045859_com.ichi2.anki.jpg](https://user-images.githubusercontent.com/96474692/233734820-fa7f05a3-c17d-40c9-a705-5404bc3e852a.jpg)
![Screenshot_20230422_045905_com.ichi2.anki.jpg](https://user-images.githubusercontent.com/96474692/233734823-fb510734-6f56-4167-8a52-be909a937eea.jpg)

**Comment by SanjaySargam** [comment]
Debug info :-
AnkiDroid Version = 2.16alpha97-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = c070f6dc-866e-4fcf-8bc1-2aa53bcca93d

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
