### ISSUE TITLE
Deactivate advanced storage's collection path during migration

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13608]
During a migration, we should not change the collection path manually using advanced storage (I assume). So it should be deactivated.

@BrayanDSO ; I believe I recall you were the one deactivating things during migration. Would you mind taking charge of it.

**Comment by BrayanDSO** [comment]
There was a merged PR for this. Isn't it working?

**Comment by david-allison** [comment]
adbba18dea136cb926586005841ab000d179eebf ([#13329](https://github.com/ankidroid/Anki-Android/pull/13329))

**Comment by Arthur-Milchior** [comment]
Thanks. i was not able to find it in the code, I didn't look at the right place. Thanks
