### ISSUE TITLE
The new card is not displayed correctly

### ISSUE THREAD

**Issue by Benjamin-Watson0** [ankidroid/Anki-Android#13615]
I need to have 385 cards to review today, and my daily plan is to learn 30 new cards and review 300 due cards. But when I opened ANKI today, I found that there were only 300 expired cards, and there were no new cards to learn (there were enough new cards). When I tried to adjust the daily review amount to 400, the new card count was adjusted to 40, and the new card count showed 15 (I thought it would show 40). When I try to set the daily review amount to 500, the number of new cards shows 50.
What happened and is it reasonable? I used the time V3 way.

I wonder if this is anki's V3 card placement feature, or something else.

**Comment by david-allison** [comment]
Hi, 

GitHub is for bugs and developer support, you'd be best to read the manual, then check [Reddit/Discord/our Forums](https://github.com/ankidroid/Anki-Android#join-us-on) for user support on this one
