### ISSUE TITLE
[BUG]: `allow_unsafe_migration` doesn't work as expected

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13612]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Allow unsafe migration does not work as it should in all APIs reported by @Arthur-Milchior on Discord
```
## This file must *NOT* be checked into Version Control Systems,
# as it contains information specific to your local configuration.
#
# Location of the SDK. This is only used by Gradle.
# For customization when using a Version Control System, please read the
# header note.
#Sat Jul 30 19:00:38 CEST 2022
sdk.dir=/home/milchior/Android/Sdk
allow_unsafe_migration=true
```

Works for me on API27 but not on API30 or 32 and 33 for Arthur

### Expected behaviour

Migration button should be available 

### Actual behaviour

No migration button is shown even if its set to `true`

### Debug info

```text
alpha97-debug
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
What's your Build Variant? If you're on `amazon`, then a migration will not be offered

![Screenshot 2023-04-15 at 18 48 57](https://user-images.githubusercontent.com/62114487/232245224-1325f807-11bd-4f18-9ea8-43368780ff82.png)

**Comment by criticalAY** [comment]
it was amazon but it is offered on the API27
