### ISSUE TITLE
[Bug]None of the images in the card are displayed( AnkiDroid-2.16alpha97-arm64-v8a.apk )

### ISSUE THREAD

**Issue by ghost** [ankidroid/Anki-Android#13618]
###### Reproduction Steps

1. Click on the deck to start learning the cards
2. The picture in the card is not displayed
3. Everything is fine after switching to alpha95（AnkiDroid-2.16alpha95-arm64-v8a.apk）

###### Expected Result

The picture in the card is displayed normally

###### Actual Result

Images in cards are not displayed

###### Debug info
AnkiDroid Version = 2.16alpha97Android Version = 12Manufacturer = HUAWEIModel = DBY-W09Hardware = qcomWebview User Agent = Mozilla/5.0 (Linux; Android 12; DBY-W09 Build/HUAWEIDBY-W09; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.105 Safari/537.36ACRA UUID = c5e87d72-a977-410c-aa34-22153f8f41b7New schema = falseScheduler = std2Crash Reports Enabled = trueDatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
It is not reproducible in my case

My debug info - 
AnkiDroid Version = 2.16alpha97-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36

ACRA UUID = c070f6dc-866e-4fcf-8bc1-2aa53bcca93d

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
