### ISSUE TITLE
Status Bar Color Doesn't Match Card Background Color

### ISSUE THREAD

**Issue by MarvNC** [ankidroid/Anki-Android#13617]
**Is your feature request related to a problem? Please describe.**
When I review cards in light mode the card backgrounds are usually just white. However in fullscreen mode on my Pixel 6, the status bar behind the camera cutout is black, even though in the non fullscreen mode interface the status bar matches the top of the screen (blue). 

**Describe the solution you'd like**
I would like if the status bar was the same color as the card background when reviewing in fullscreen mode.

**Describe alternatives you've considered**
- The user could set the color they want the status bar to be, though IMO this isn't needed.
- Assuming the user is using an OLED device, the black bar could incorporate the rounded edges of the original top corners somehow as to not look out of place. But not everyone uses OLED.

**Additional context**

<details>
<summary> Image </summary>

![Screenshot_20230415-204757](https://user-images.githubusercontent.com/17340496/232265410-6d53ca32-7ce4-4ae8-b975-7791e2e06b2c.png)
</details>

**Comment by SanjaySargam** [comment]
I would like to work on this

**Comment by MarvNC** [comment]
Still unresolved.
