### ISSUE TITLE
[BUG]: Schedule seems to work wrong between Desktop and AnkiDroid

### ISSUE THREAD

**Issue by MWesleyy** [ankidroid/Anki-Android#13629]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

I use Anki (and AnkiDroid) every day for some months now, and I noticed that the scheduling works differently between the two apps. 

for example, If I studied a card yesterday, anki can suggest it'll appear 1d later. On the windows app, it will appear in the next day no matter the hour. On AnkiDroid, however, it will only appear after completing exactly 24 hours. I like the way it works on windows because some days I want to study my cards sooner and they didn't appear yet on my phone. Is there a way to solve this?

### Expected behaviour

Is expected that I have the same cards available to study as I have on my PC

### Actual behaviour

Until the end of the day, I will have all the same cards available to study on my PC, but I need to wait some hours more (that is not convenient sometimes)

### Debug info

```text
AnkiDroid Version = 2.15.6

Android Version = 13

Manufacturer = samsung

Model = SM-M236B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-M236B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.100 Mobile Safari/537.36

ACRA UUID = a6c2baf2-49e5-4a2e-8848-9a97e39b3cbc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pavreh** [comment]
You can try AnkiDroid 2.16alpha (available here on GitHub), go to Settings - advanced - use the new backend. Then, AnkiDroid will use the same backend (e.g. scheduler) as Anki and the behaviour should be the same.
