### ISSUE TITLE
Investigate `DeckPicker` toolbar not showing migration progress on some API

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#13633]
We need to make sure this isn't some sort of unknown issue that can pop up even on API that matter. As I understand, there are two separate but probably related issues of:

* the toolbar [failing to start progress](https://github.com/ankidroid/Anki-Android/pull/13368#pullrequestreview-1386952010), and
* the toolbar [failing to update after success](https://github.com/ankidroid/Anki-Android/pull/13368#discussion_r1167723170).

Brayan [noted](https://github.com/ankidroid/Anki-Android/pull/13368#pullrequestreview-1391126321),

> The circle bar not appearing issue didn't happen on an API 33 emulator. As the issue showed up on a version that doesn't need the migration (29), it won't matter.

It makes me think that this not a coincidence and there's some path in the code that checks whether or not we need migration, and if not, causes the issue. But then why migration is offered in the first place?

**Comment by BrayanDSO** [comment]
> But then why migration is offered in the first place?

I don't see why as well. IMO, `shouldOfferToUpgrade()` should take in consideration the device Android version

**Comment by david-allison** [comment]
> > But then why migration is offered in the first place?
> 
> I don't see why as well. IMO, `shouldOfferToUpgrade()` should take in consideration the device Android version

This aspect should be fixed in https://github.com/ankidroid/Anki-Android/pull/13614/
