### ISSUE TITLE
No cancel button in Add note type Dialog

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#13647]
**Is your feature request related to a problem? Please describe.**
It's good to have `cancel` button in dialog so that user can close dialog

**Describe the solution you'd like**
Add cancel button in Dialog

**Additional context**
![Screenshot_20230421_232539](https://user-images.githubusercontent.com/65113071/233703814-b3879f69-d8c0-4ef5-a4fc-f7bfbc602740.png)

**Comment by Arthur-Milchior** [comment]
First, thanks, that's a nice improvement

FYI, there are 141 positiveButton and only 102 negativeButton in our codebase. If one day you're bored and don't know what to do, it would be nice to check whether it was intended that the 39 other one don't have negativeButton.

For example, any code that display an error message, indeed, has no need to have two buttons, as there is no real selection.

**Comment by SanjaySargam** [comment]
> First, thanks, that's a nice improvement
> 
> FYI, there are 141 positiveButton and only 102 negativeButton in our codebase. If one day you're bored and don't know what to do, it would be nice to check whether it was intended that the 39 other one don't have negativeButton.
> 
> For example, any code that display an error message, indeed, has no need to have two buttons, as there is no real selection.

Sure I'll do
