### ISSUE TITLE
JSON data from CDN/localhost not loaded in latest version but it loads in previous version

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#13656]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Install AnkiDroid.A 2.16alpha92 and latest alpha
2. Download and unzipping following then import this deck in both version
[Test.zip](https://github.com/ankidroid/Anki-Android/files/11300290/Test.zip)
3. Open deck in both version of AnkiDroid
4. In first version the JSON data loaded and svg generated
5. But in latest alpha, it does not load

### Expected behaviour

The JSON should load from CDN as it loaded in previous version.

### Actual behaviour

```
Acess to XMLHttpRequest at 'https://cdn.jsdelivr.net/npm/hanzi-writer-data@latest/%E4%B8%80.json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.jsdelivr.net/npm/hanzi-writer-data@latest/%E4%B8%80.json:1     Failed to load resource: net::ERR_FAILED
__viewer__.html:1169 Uncaught (in promise) Error: Failed to load char data for 一
    at __viewer__.html:1169:45189
__viewer__.html:1 Access to XMLHttpRequest at 'https://cdn.jsdelivr.net/npm/hanzi-writer-data@latest/%E4%B8%80.json' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
cdn.jsdelivr.net/npm/hanzi-writer-data@latest/%E4%B8%80.json:1     Failed to load resource: net::ERR_FAILED
```

### Debug info

```text
AnkiDroid Version = 2.16alpha97

Android Version = 11

Manufacturer = samsung

Model = SM-M307F

Hardware = exynos9611

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-M307F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = 95fd7760-93ab-4a7d-9271-b54e9a0da086

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```
```


### (Optional) Anything else you want to share?

_No response_

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
I strongly suspect this is related to our `targetSdkVersion` increase. 

Was this broken between alpha 94 and 95?

**Comment by krmanik** [comment]
I have tested with 94 and 95. The issues happens after in and after 95. It is working fine in 94.

**Comment by david-allison** [comment]
Can't reproduce on `main` (`amazonDebug`), the only thing that I feel could have affected this is the move from `targetSdkVersion 30 -> 31`

I can reproduce this from alpha 92 -> 97

![Screenshot 2023-04-22 at 17 28 46](https://user-images.githubusercontent.com/62114487/233795934-79614c22-fd50-492c-9552-9a13eba640ee.png)

**Comment by krmanik** [comment]
The issue is resolved in latest alpha also built from source, the data is loaded now.

**Comment by david-allison** [comment]
Great! It's a shame we didn't discover /what/ resolved it, but I'm glad it's resolved.
