### ISSUE TITLE
Emulator tests failing: NullPointerException

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13677]
Something's failing on an emulator I'm running locally. Should be pulled out into an issue to investigate

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/13661#issuecomment-1519048012_
            
```
java.lang.NullPointerException
at com.ichi2.anki.TestUtils.isScreenSw600dp(TestUtils.kt:78)
at com.ichi2.anki.DeckPickerTest.checkIfStudyOptionsIsDisplayedOnTablet(DeckPickerTest.kt:91)
```

**Comment by mikehardy** [comment]
any details on emulator API / flavor / config and SHA that was failing, for repro help?

**Comment by david-allison** [comment]
Tested by rebasing onto https://github.com/ankidroid/Anki-Android/commit/d88ad6251c7358359e0dcca36c10f08ff543c4db and running tests on playDebug (API 32 emulator)

I suspect this is due to the emulator lacking permissions to access storage, therefore the activity is destroyed
