### ISSUE TITLE
Change type for existing cards

### ISSUE THREAD

**Issue by jordandsullivan** [ankidroid/Anki-Android#13675]
**Is your feature request related to a problem? Please describe.**
My main issue is that I can't convert basic cards into cloze cards, which throws off my workflow.
To reproduce the issue:
Create a basic card with content on both sides, save it, and then go back to edit it and change the card type to, for instance cloze (but any type other than the original will cause this). The content will suddenly become uneditable, making the change in card type change meaningless. 

**Describe the solution you'd like**

**Describe alternatives you've considered**
I want to be able to edit the original content as I see fit. E.g. if the original card type has two different boxes and the new card type has only one, just add all the content from the second box into the first. As for cloze deletions, if changing from cloze to another type of card, I would argue that you can just show an error that won't let you save if there are still cloze deletions present. Or better yet even allow cloze deletions in the other types of cards.

**Additional context**

**Comment by dtolia** [comment]
Still searching for solutions...
@jordandsullivan didn't provide a clear description. So, I'll reiterate it below.

**Comment by dtolia** [comment]
### Is your feature request related to a problem? Please describe.
I can't convert Basic cards to Cloze cards.

### To reproduce the issue

- Create a Basic card with content on both sides and save it.
- Go back to edit it and change the card type to Cloze. (Any card type other than the original will also produce similar results)
- The text section will suddenly become unmodifiable. Thus making the change in card type meaningless.

### Describe the solution you'd like
Please allow change in card type after saving the card. The text section shouldn't become unmodifiable.

### Describe alternatives you've considered
None

### Additional context
None

**Comment by jordandsullivan** [comment]
To clarify, do you need more information from me?

**Comment by dtolia** [comment]
No. Your initial message seemed a bit unclear to me. So, I thought I would
rewrite it again for the developers.
