### ISSUE TITLE
Optimize release builds / release process

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#13682]
This is a bit of an umbrella, I want to capture at least one thing (there may be others...) that I see with the release process:

- [ ] `Unable to strip the following libraries, packaging them as they are: librsdroid.so.` from https://github.com/ankidroid/Anki-Android/actions/runs/4779228629/jobs/8496177233#step:10:60
- [x] `package="com.ichi2.anki" found in source AndroidManifest.xml: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/intermediates/merged_manifest/playRelease/AndroidManifest.xml.
Setting the namespace via a source AndroidManifest.xml's package attribute is deprecated` from https://github.com/ankidroid/Anki-Android/actions/runs/4779228629/jobs/8496177233#step:10:98
- [ ] `Note: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/generated/aidl_source_output_dir/playRelease/out/android/content/pm/IPackageStatsObserver.java uses or overrides a deprecated API.` from https://github.com/ankidroid/Anki-Android/actions/runs/4779228629/jobs/8496177233#step:10:130
- [ ] the release script normally tells you what it is going to do before it executes a gradle thing, which is nice if you read it and follow along as it works. It does not do that for parallel releases
- [ ] for parallel releases, on alphas only 2 are uploaded to github but all 5 are built every time. Could speed alpha build/release by only building the alpha set of parallels vs the full set

**Comment by BrayanDSO** [comment]
>  Note: /home/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/generated/aidl_source_output_dir/playRelease/out/android/content/pm/IPackageStatsObserver.java uses or overrides a deprecated API. 

Introduced at https://github.com/ankidroid/Anki-Android/commit/f0a912da64c2f8fc059b11c9e69e272fc2152d4c#diff-140f07a144337564d5e4e8f17e28efc94c3587a78bbfa6539d2017e6784c5e98. @oakkitten do you have any ideas if this is fixable or if it should be suppressed?

**Comment by oakkitten** [comment]
I mention the warning [in the PR](https://github.com/ankidroid/Anki-Android/pull/12765#issuecomment-1315996344), from what I wrote it seems that I hadn't found a way to suppress it, but by now I don't remember what exactly or how hard I tried
