### ISSUE TITLE
[BUG]:  Shared deck download aborts due to lack of permission(read and write)

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13699]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. alpha98 debug build(amazon)
2. fresh install
3. proceed to the deck picker and try to download any shared deck
4. wait for the download to complete

### Expected behaviour

If there is no read-write permission then the user is asked for the permission and the downloaded deck is imported/ or asked to download again whatever suits

### Actual behaviour

Toast is shown and the import is aborted

### Debug info

```text
Alpha98- debug
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@criticalAY I believe this is fixed in #13703

**Comment by criticalAY** [comment]
> @criticalAY I believe this is fixed in #13703

I will check it now

**Comment by criticalAY** [comment]
@david-allison It is fixed Thanks! I am closing it
