### ISSUE TITLE
[BUG]: Can't open decks after storage migration.

### ISSUE THREAD

**Issue by eginhard** [ankidroid/Anki-Android#13692]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- synced my collection
- updated to the 2.16alpha98 through the Play store from the last released one (alpha21 I think?)
- started the migration when prompted after opening the app and let it complete without using the app
- tried to open a deck after I was notified about successful completion of the migration

### Expected behaviour

Deck opens normally for review

### Actual behaviour

- a toast like "A problem occurred. A report was sent to the developers." was shown once
- further clicking on any decks shows a toast "Failed to load deck 1234567"

### Debug info

```text
AnkiDroid Version = 2.16alpha98
Android Version = 11
ProductFlavor = play
Manufacturer = HMD Global
Model = Nokia 8.1
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 11; Nokia 8.1 Build/RKQ1.200906.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36
ACRA UUID = 59d02946-b534-4858-a266-438ebc92d44b
New schema = false
Scheduler = std
Crash Reports Enabled = true
DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@eginhard Unusual question: were you on Sched V1?

The 'upgrade path' from V1 to V2 was broken, causing this bug. (`schedVer` didn't exist on SchedV1, but the code expected it to)

I'm concerned that another bug was lurking which caused `schedVer` to be wiped. The rest of the config you provided seemed reasonable.

**Comment by eginhard** [comment]
@david-allison Yes, I rarely do reviews anymore and only on Ankidroid, so never got any nudge to upgrade. The fix looks good, thanks a lot! I'll try the next release.

**Comment by eginhard** [comment]
Quick follow-up: in the new beta I was correctly prompted to upgrade the scheduler as shown in #13702 and after doing so everything worked fine again. No issues with the migration otherwise. Thanks a lot!
