### ISSUE TITLE
[Bug] Bad visuals when tapping a `.anki2` file in 'Files' app [IntentHandler]

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13704]
###### Reproduction Steps

1. Open the 'Files' app
1. Tap a `.anki2` file
    * **Not** from DeckPicker -> Import

###### Expected Result

A normal dialog

###### Actual Result

This overlay. Needs two 'back' taps to return
![Screenshot 2023-04-24 at 23 57 11](https://user-images.githubusercontent.com/62114487/234133643-6986d213-cda7-4f58-ad37-370727474c4e.png)

###### Debug info
* Private build, alpha98 -> alpha99: fc008f06208e92bf3fc6164c80d82a826772537e + changes in https://github.com/ankidroid/Anki-Android/pull/13703

```
AnkiDroid Version = 2.16alpha98-debug

Android Version = 12

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 12; sdk_gphone64_arm64 Build/SE1B.220616.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36

ACRA UUID = ba0c0656-6559-45e4-b7a8-688f2fd3931a

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
This is what I see on main:
![image](https://user-images.githubusercontent.com/69634269/234147550-549a3f38-b041-47df-9cdc-2e75d7005436.png)

**Comment by david-allison** [comment]
Did you select the `anki2` inside the 'Files' app, not from DeckPicker -> Import -> Files

**Comment by lukstbit** [comment]
See #13689 on how to reproduce this.
Ideally we would fix the AppCompat issue for IntentHandler which would allow us to use AlertBuilder as a dialog(MaterialDialog also doesn't like the current translucent theme).

**Comment by BrayanDSO** [comment]
> See https://github.com/ankidroid/Anki-Android/issues/13689 on how to reproduce this.

Helped a lot. Already fixed it. Thanks!
