### ISSUE TITLE
Storage Migration halts during Screen Off [Wake Lock]

### ISSUE THREAD

**Issue by Consonata** [ankidroid/Anki-Android#13728]
Hello All!

Just updated to 2.16, and having issues with the storage migration. Any time the screen is off, the migration halts. It's not a huge issue probably for most users, however with larger collections (5.3gb for my own) it can be slightly annoying.

Not sure if there is any way around this though.
Thanks all! Apart from that I love the new update <3

**Comment by BrayanDSO** [comment]
Hi there! Thanks for the feedback.

Some questions:
1. Which Android version do you have?
2. Which phone/device do you have? (at least the manufacturer, Samsung, Xiaomi, Google, etc)
3. Does the migration stops immediately after the screen goes out or you block your device?

**Comment by criticalAY** [comment]
So here we are with the worst case :)

**Comment by david-allison** [comment]
Proposal: move this to a dialog shown during the start of migration. I don't think we'll be able to get a good UX using the notification

**Comment by criticalAY** [comment]
That the user want to turn on the wake lock or not before starting the migration?

**Comment by oakkitten** [comment]
Heh, that was my initial concern; as a user I would also be expecting that the migration is performed continuously and without pauses, similar to what you'd expect of any similar action like copying or downloading a file.

I don't like the idea of a dialog with a choice, it feels too complicated. How about unconditionally using a wakelock and:
1. Determine if the number of the media files is large, say, over 1000. In my experience the slowdown depends on the *number* not the size of the files.
1. If more than the threshold, either:
1.1. add a warning to the initial dialog that migration can take considerable time and that they want to have a full battery yadayada, or
1.2. add another dialog with the same warning and the same options.

**Comment by BrayanDSO** [comment]
IMO, either use it or don't. No preferences or conditionals based on files number or whatever else. 

If it is used, warn the user to take care of their battery status, as many other places do when backuping or upgrading an app, which would avoid the problem of running out of battery even without the wake lock

**Comment by oakkitten** [comment]
Why not skip the warning if we can be sure that migration is going to be done in a few minutes?

**Comment by criticalAY** [comment]
do you plan to show that warning if the files are more than a certain number and skip it if we are aware that it is less than that. Like we skip a snackbar if the migration is completed before a certain time. But I'm still in favour of not forcing the user for wake lock. Though a warning is fine and let them decide if they want to keep their device on or not

**Comment by Consonata** [comment]
Just on this, from a users perspective, I totally understand the risks to battery particularly for folx who are reliant on their devices for work and health needs.

My collection is probably unusually large as well (5.3gb), for myself it is just a mild annoyance to the type of workflow I use with Anki (use Anki on my computer in the morning and Ankidroid commuting). I think it would be nice for an option tucked in advanced preferences to allow it transfer in the background. However if this isn't ideal I also can totally see that.

Thanks so much for all the work you all do!

**Comment by BrayanDSO** [comment]
> Why not skip the warning if we can be sure that migration is going to be done in a few minutes?

I can never be sure that someone will do a migration in just a few minutes. Some random person will have a slow phone, a lot of background apps running and/or low battery. 

It doesn’t hurt to warn

**Comment by oakkitten** [comment]
I'd say that by choosing a rather low threshold of 1000 files or so we _can_ be sure, and it would cover a large number of users. But maybe it doesn't matter. I'm okay with an unconditional wakelock + a warning as well. Still not a fan of giving the user a choice to use a wakelock via a dialog.

P.S. Absolutely _not_ a fan of a setting hidden in advanced preferences, no-one is going to find that.
