### ISSUE TITLE
[BUG]:  API24 Shared deck download import causes a crash

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13729]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Try to download a shared deck 
2. let it complete a
3. press import

### Expected behaviour

The deck is imported

### Actual behaviour

App crashes

### Debug info

```text
AnkiDroid Version = 2.16alpha98-debug

Android Version = 7.0

ProductFlavor = amazon

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Android SDK built for x86 Build/NYC; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/51.0.2704.90 Mobile Safari/537.36

ACRA UUID = 997f409e-a647-4092-baf1-3da5eaf50f3f

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
What's the stack trace?

**Comment by david-allison** [comment]
https://github.com/FasterXML/jackson-databind#compatibility


>## Compatibility
>
>### JDK
>
>Jackson-databind package baseline JDK requirements are as follows:
>
>* Versions 2.0 - 2.7 require JDK 6
>* Versions 2.8 - 2.12 require JDK 7 to run (but 2.11 - 2.12 require JDK 8 to build)
>* Versions 2.13 and above require JDK 8
>
>### Android
>
>List is incomplete due to recent addition of compatibility checker.
>
>* 2.13: Android SDK 24+
>* 2.14: Android SDK 26+
>
>for information on Android SDK versions to Android Release names see https://en.wikipedia.org/wiki/Android_version_history

-----

**Comment by criticalAY** [comment]
Umm the version is incompatible
