### ISSUE TITLE
Include greek translation in app

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#13720]
From crowdin https://crowdin.com/messages/638803

----

[codeenthusiast7](https://crowdin.com/profile/codeenthusiast7)
codeenthusiast7 codeenthusiast702:37
01-core for Greek is 100% so I'm asking for inclusion

----

Seems we could enable it by adding it to the various languages arrays etc

**Comment by david-allison** [comment]
Already enabled and working. Listed lower in the list as 'Ελληνικά' starts with Epsilon

![AnkiDroidGreek](https://user-images.githubusercontent.com/62114487/234445258-8843304c-1593-43bb-899e-a987b025164a.png)
