### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by pputnik** [ankidroid/Anki-Android#13739]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

in Anki (desktop version) create a note which references a file in a subfolder, like this:

`[sound:subdir/myNote.mp3]`

save the note then sync. 
Sync the database in AnkiDroid.

### Expected behaviour

The file will be downloaded to the phone, the card plays sound when needed.

### Actual behaviour

The card/note appears on the phone with proper field value but the file is missing. If create the subdir manually and put the file there - everything works.

### Debug info

```text
AnkiDroid Version 2.15.6
Android Version = 11
Manufacturer = motorola
Model = moto g(8)
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 11; moto g(8) Build/RPJS31.Q4U-47-35-17; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36
ACRA UUID = 14a28e43-e427-4606-86df-57992f1d0f90
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Thank you for the app! :)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, we're about to release 2.16, could you let us know whether this is fixed (especially if using the new backend in the advanced settings), or if we'll need to fix it for 2.17
