### ISSUE TITLE
[Bug] Bottom button clipped on the left and right corners (Phone Model - Samsung S20+)

### ISSUE THREAD

**Issue by Consonata** [ankidroid/Anki-Android#13748]
This report relates to the latest Alpha edition (2.16alpha98)

###### Reproduction Steps

1. Open Ankidroid and open a deck
2. Bottom "Show Answer" button is clipped on the left and right corners as can be seen below
3. Similarly for "Again","Good", "Easy", this is a Samsung S20+ and using Gesture Controls

###### Expected Result
Box fully delineated at the bottom

###### Actual Result
![image](https://user-images.githubusercontent.com/119627691/234972300-690c0df8-b6fe-4825-ba2c-8933e9fa0c9b.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Replicated on my S21. Thanks!

We're very likely going to want to redesign the bottom/right/left of the buttons to avoid a border. I've done a quick check on the apps on my phone and haven't seen any others with this border.

**Comment by BrayanDSO** [comment]
Can replicate as well. Although I got used to it, but always found it ugly

**Comment by criticalAY** [comment]
I have
Option 1 - Add padding to the main layout which would fix it but on devices that don't use the full screen and use soft buttons to navigate it would be ugly
Option 2 - Remove the vertical border keeping only the horizontal ones making it consistent

**Comment by snowtimeglass** [comment]
> Option 2 - Remove the vertical border keeping only the horizontal ones making it consistent

The loss of both ends of the bottom horizontal border is fairly conspicuous on my device.
![image](https://user-images.githubusercontent.com/10436072/236682405-9abfe518-9ee1-4b12-9198-87aa622632f1.png)

**Comment by criticalAY** [comment]
![Screenshot_71](https://user-images.githubusercontent.com/48384865/236695069-9a564da9-ff29-4a2a-ade8-70b34fff9869.jpg)
Can we redesign it to something like this? @david-allison @BrayanDSO

**Comment by david-allison** [comment]
I'd prefer not to round the corners, but let's shelve this until 2.16 is out

**Comment by oakkitten** [comment]
I propose to have rounded corner buttons (with a very dim background color for night mode) **_with some non-clickable space between them_** (to remove the possibility of mistapping). If we have the API to determine the radius of the screen corners, we could try fitting the buttons nicely within the area that we know we have. (Math time 🤓) 

**Note that** one some (many?) devices you can hide the bottom navigation hint (the bar at the bottom of the screen) so that the app spans to the very bottom of the display. (**No insets!** Buttons will be located in the **very bottom* of the screen, within the gesture zone, but that doesn't cause issues—presses and system gestures do not normally conflict)

**Comment by BrayanDSO** [comment]
Joining with #14759
