### ISSUE TITLE
[BUG]: The 'is:learn' filter does not work for filtered decks!

### ISSUE THREAD

**Issue by MohamedAmineSafi** [ankidroid/Anki-Android#13749]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Create a filtered deck using the filter 'is:learn', but not all the cards in the learning stage got added to the filtered deck. Rebuilding the same deck on the desktop version of anki successfully added the cards to the filtered deck.

### Expected behaviour

All the cards in the learning stage should have been added to the filtered deck.

### Actual behaviour

Only the the the cards I was relearning were added without a problem, but the cards I was learning for the first time weren't added. Rebuilding the same deck on the PC version solved the issue (adding all the cards in the learning and relearning stages). So, the PC and Android versions are behaving differently.

### Debug info

```text
AnkiDroid Version = 2.15.6

Android Version = 9

Manufacturer = android-uct

Model = LP_Pro1

Hardware = s9863a1h10

Webview User Agent = Mozilla/5.0 (Linux; Android 9; LP_Pro1 Build/P00610; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = 0943ffc0-54ff-45f7-804d-9575287115eb

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
I tried filtering cards using Ankidroid and Anki Desktop, it gives the same result.

WIll you provide some more info regarding this ?
