### ISSUE TITLE
[Bug] Changing the setting “AnkiDroid directory” can show misleading error dialog “The path specified wasn’t a valid directory”

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#13756]
The string itself was introduced in 173afebf530bf0762c7ab36c5ce41d9a56801516 and it was a valid message back then

###### Reproduction Steps

1. Don't have full disk access permission
2. Try changing “AnkiDroid directory” to a valid but inaccessible directory

###### Expected Result

A permission prompt if applicable or an error detailing the lack of permissions

###### Actual Result

<img width=300 src=https://user-images.githubusercontent.com/1710718/235186767-63950359-cc45-4d60-9e62-e52ae791d80f.png>

###### Debug info

AnkiDroid Version = 2.16alpha98-debug

Android Version = 11

ProductFlavor = play

Manufacturer = Xiaomi

Model = Mi A2

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Mi A2 Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 54b7f367-a65e-4309-af70-5bacd77d1172

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by tjbrn** [comment]
How to set the directory to the previous one? ("/storage/emulated/0/AnkiDroid")

I use ssh/rsync to sync my media, and neither ssh can't access "storage/emulated/10/Android/data/com.ichi2.anki/files/AnkiDroid" nor can I change AnkiDroid directory in Advanced options (invalid directory error)
