### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by fredjoe7** [ankidroid/Anki-Android#13758]
###### Reproduction Steps

1. ANKING NOTE TYPE
2. TURN ON TEXT TO SPEECH IN ANKING NOTE TYPE ON WINDOWS AND SYNC 
3. NOW OPEN IN ANKI DROID

###### Expected Result
work normally 

###### Actual Result
the front  side of card appears twice  and persists and persists after turning the card.

![image](https://user-images.githubusercontent.com/107930196/235297248-d437d594-c0bd-4645-ad7a-9dec982b9329.png)

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-M307F

Hardware = exynos9611

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-M307F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = a6347ba8-a048-476c-b872-02bd6d72bf9b

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions]()

**Comment by david-allison** [comment]
Hi, could you provide an export containing the note type?

**Comment by fredjoe7** [comment]
front template


<div id="text">{{cloze:Text}}</div>

<br>



{{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=2.0:cloze:Text}}


<script>
// ############## USER CONFIGURATION START ##############
// Auto flip to back when One by one mode.
var autoflip = true 

// Timer config (timer length, timer finished message)
var minutes = 0
var seconds = 7
var timeOverMsg = "<span style='color:#CC5B5B'>!<br/>!<br/>!<br/>!<br/>!<br/>!</span>"

// ##############  TAG SHORTCUT  ##############
var toggleTagsShortcut = "C";

// ENTER THE TAG TERM WHICH, WHEN PRESENT, WILL TRIGGER A RED BACKGROUND
var tagID = "XXXYYYZZZ"

// WHETHER THE WHOLE TAG OR ONLY THE LAST PART SHOULD BE SHOWN

var numTagLevelsToShow = 0;

// ############## USER CONFIGURATION END ##############
</script>



<div id="one-by-one" style="display: none;">{{One by one}}</div>

<script>
  var clozeOneByOneEnabled = true;
    clozeOneByOneEnabled = document.getElementById("one-by-one").textContent !== "";
  
  window.clozeHints = [];
  if (clozeOneByOneEnabled) {
    // Save cloze hints to display in the back
    let clozes = document.getElementsByClassName("cloze")
    for(var i = 0; i < clozes.length; i++) {
      if (clozes[i].innerHTML === "[...]") {
        window.clozeHints.push("")
      } else {
        window.clozeHints.push(clozes[i].innerHTML)
      }
    }

    if (autoflip) {
    // avoid flickering. Must unset this in the back.
    document.getElementById("qa").style.display = "none";

    if (window.pycmd) {
        pycmd("ans")
    } else if (window.showAnswer) {
        showAnswer()
    }
}
// AnkiMobile JS API doesn't have one for show answer.
// Best alternative is to use Taps/Swipes to show answer.
  }
</script>


<script>
  if (window.ankingEventListeners) {
    for (const listener of ankingEventListeners) {
      const type = listener[0]
      const handler = listener[1]
      document.removeEventListener(type, handler)
    }
  }
  window.ankingEventListeners = []
  
  window.ankingAddEventListener = function(type, handler) {
    document.addEventListener(type, handler)
    window.ankingEventListeners.push([type, handler])
  }
</script>


<script>
  var specialCharCodes = {
    "-": "minus",
    "=": "equal",
    "[": "bracketleft",
    "]": "bracketright",
    ";": "semicolon",
    "'": "quote",
    "`": "backquote",
    "\\": "backslash",
    ",": "comma",
    ".": "period",
    "/": "slash",
  };
  // Returns function that match keyboard event to see if it matches given shortcut.
  function shortcutMatcher(shortcut) {
    let shortcutKeys = shortcut.toLowerCase().split(/[+]/).map(key => key.trim())
    let mainKey = shortcutKeys[shortcutKeys.length - 1]
    if (mainKey.length === 1) {
      if (/\d/.test(mainKey)) {
        mainKey = "digit" + mainKey
      } else if (/[a-zA-Z]/.test(mainKey)) {
        mainKey = "key" + mainKey
      } else {
        let code = specialCharCodes[mainKey];
        if (code) {
          mainKey = code
        }
      }
    }
    let ctrl = shortcutKeys.includes("ctrl")
    let shift = shortcutKeys.includes("shift")
    let alt = shortcutKeys.includes("alt")

    let matchShortcut = function (ctrl, shift, alt, mainKey, event) {
      if (mainKey !== event.code.toLowerCase()) return false
      if (ctrl !== (event.ctrlKey || event.metaKey)) return false
      if (shift !== event.shiftKey) return false
      if (alt !== event.altKey) return false
      return true
    }.bind(window, ctrl, shift, alt, mainKey)
    
    return matchShortcut
  }
</script>


<div class="timer" id="s2"></div>
<script>
  function countdown(elementName, minutes, seconds) {
    var element, endTime, mins, msLeft, time;
    function twoDigits( n ) {
      return (n <= 9 ? "0" + n : n); 
    }
    function updateTimer() {
      msLeft = endTime - (+new Date);
      
      if ( msLeft < 1000 ) {
        element.innerHTML = timeOverMsg;
      } else {
        time = new Date( msLeft );
        mins = time.getUTCMinutes();
        element.innerHTML = mins + ':' + twoDigits(time.getUTCSeconds());
        setTimeout( updateTimer, time.getUTCMilliseconds() + 500 );
      }
    }
    element = document.getElementById(elementName);
    endTime = (+new Date) + 1000 * (60*minutes + seconds) + 500;
    updateTimer();
  }
  countdown("s2", minutes, seconds ); //2nd value is the minute, 3rd is the seconds
</script>


<a href="https://www.ankingmed.com"><img src="_AnKingRound.png" alt="The AnKing" id="pic"></a>
    

{{#Tags}}
<div id="tags-container">{{clickable::Tags}}</div>
<script>
  var tagContainer = document.getElementById("tags-container")
  var tagList;
  if (tagContainer.childElementCount == 0) {
    tagList = tagContainer.innerHTML.split(" ");
    var kbdList = [];
    var newTagContent = document.createElement("div");

    for (var i = 0; i < tagList.length; i++) {
      var newTag = document.createElement("kbd");
      var tag = tagList[i];
      // numTagLevelsToShow == 0 means the whole tag should be shown
      if(numTagLevelsToShow != 0){
        tag = tag.split('::').slice(-numTagLevelsToShow).join("::");
      }
      newTag.innerHTML = tag;
      newTagContent.append(newTag)
    }
    tagContainer.innerHTML = newTagContent.innerHTML;
    tagContainer.style.cursor = "default";
  }
  else {
    tagList = Array.from(tagContainer.children).map(e => e.innerText);
  }
  globalThis.tagList = tagList.map(t => t.trim().toLowerCase());
  if (tagContainer.innerHTML.indexOf(tagID) != -1) {
    tagContainer.style.backgroundColor = "rgba(251,11,11,.15)";
  }

  function showtags() {
    var tagContainerShortcut = document.getElementById("tags-container");

    if (tagContainerShortcut.style.display
      === "none") {
      tagContainerShortcut.style.display = "block";
    } else {
      tagContainerShortcut.style.display =
        "none";
    }
  }
  
  var isShortcut = shortcutMatcher(toggleTagsShortcut)
  ankingAddEventListener('keyup', function (e) {
      if (isShortcut(e)) {
          showtags();
      }
  });

</script>
{{/Tags}}

**Comment by fredjoe7** [comment]
{{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=2.0:cloze:Text}}

if i disable the above string (text to speech in anking notetype, then everything works normally in ankidroid.

**Comment by fredjoe7** [comment]
i tried installing the 2.16 alpha98 build and it has replaced the second copy with a play button. 
but clicking the play button does not seem to play anything.

![image](https://user-images.githubusercontent.com/107930196/235298813-b75b70ab-75ad-4f0d-a956-f4ca172c3492.png)

**Comment by Spyhund** [comment]
> {{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=2.0:cloze:Text}}
> 
> if i disable the above string (text to speech in anking notetype, then everything works normally in ankidroid.

I had this issue aswell but fixed it by putting the tts-part (if i remember correctly) inside <script>, like this;  <script> {{tts en_US ... }} </script>. The tts works as usual on PC and no duplicate text on Ankidroid.
