### ISSUE TITLE
The upper margin of the title of some dialogs looks a bit too narrow

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#13763]
###### Reproduction Steps

1. Long press a deck (which has any new or review cards)
2. "Custom study"
3. "Modify today's new card limit" (or "Modify today's review card limit")

###### Relatively Acceptable Result & Actual Result
![image](https://user-images.githubusercontent.com/10436072/235331207-cbde6101-55ab-4140-b228-46ca208a29f3.png)

###### Debug info
```
AnkiDroid Version = 2.16alpha98

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36

ACRA UUID = 5ba46727-9ddb-47f3-a810-53f66d97a89e

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
I am working on it
