### ISSUE TITLE
[BUG]: Some dialogs of "Custom study" are shown in the system language instead of the configured language

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#13766]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. [Settings] -> [Language] -> Select any language other than the system language
2. Long press any normal decks -> [Custom study] -> Select one of the following options

   - Modify today's new card limit
   - Modify today's review card limit
   - Review forgotten cards
   - Review ahead
   - Study a random selection of cards

### Expected behaviour

Dialog is shown in the configured language on Anki

### Actual behaviour

Dialog is shown in the system language

### Debug info

```text
AnkiDroid Version = 2.16alpha98

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36

ACRA UUID = 5ba46727-9ddb-47f3-a810-53f66d97a89e

New schema = true

Scheduler = std3

Crash Reports Enabled = true


DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

- Disabling the new backend doesn't change the actual behaviour.
- Restarting AnkiDroid doesn't change it, either.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pratyaksh1610** [comment]
I am working on it.

**Comment by snowtimeglass** [comment]
Thank you for the fix!
