### ISSUE TITLE
[BUG]: App becomes unresponsive after sync

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#13764]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Start sync
- Press the home button to move to the home screen of the device while the sync continues in the background
- Return to the app after a delay of at least 10 minutes.

### Expected behaviour

The app is responsive.

### Actual behaviour

The app becomes unresponsive. It even doesn't indicate a change in the number of due cards (e.g. if a learning card became due in the meantime).

The app becomes responsive only after pressing the back button to exit the app and then reopening the app.

### Debug info

```text
AnkiDroid Version = 2.16alpha98

Android Version = 12

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g62 5G Build/S2SSIS32.18-12-4-6; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

This issue is not specific to the latest alpha. I have been experiencing it since long but I didn't report it earlier.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
Still searching for solutions...

**Comment by woj-tek** [comment]
I think I have the same issue but even without wait. Simply open the app, start synchronisation and while the synchronisation dialog is still on, hit home button. After re-opening Anki (even after a couple of seconds), synchronisation dialog is stuck.

(Version 2.16.2 from f-droid)

**Comment by dae** [comment]
Please do this when you don't have much to sync (so you have an idea of how quickly the sync will finish), and then wait until the sync has likely finished - does the UI become responsive again after that? If so, it's likely some legacy code that is trying to access the collection on the main thread which runs on resume, which would cause the UI to hang until the sync operation completes.

**Comment by woj-tek** [comment]
I usually don't have much to sync (~100 reviews), which usually finishes in about 5-10 seconds. I just started sync (no changes) and immediately went to the home screen. I waited a couple of minutes and opened AnkiDroid and it was still hanged.

**Comment by dae** [comment]
To confirm, do you have the new schema/backend enabled? I tested with the new backend enabled on a device here, but can't seem to reproduce it - if I return to the home screen while it's syncing, the deck list is visible and usable when I return.

**Comment by woj-tek** [comment]
Hmm... there was data migration when I opened the app - it took a couple of minutes to finish so I guess this is new schema. Regarding backend - in Options -> Advanced I see "use new backend" but it says: "Unstable: DO NOT USE for important collections" and it's OFF, and considering the warning I didn't enabled it :-)

**Comment by woj-tek** [comment]
Hm... should I create new bug report then? What additional data should I provide? Or just try to switch to new backend?

**Comment by user1823** [comment]
I am not sure if it is related but I have noticed some unexpected behaviour about the media sync.
- If I sync on mobile data, the sync completes in less than 3 seconds. (I have disabled media sync on metered connections.)
- If I sync on WiFi, the sync takes much longer (more than 20 seconds) to complete. Note that I am talking about the sync of the collection (and not the media sync, which begins later).

This happens even if there are no changes to sync.

**Comment by user1823** [comment]
> Please do this when you don't have much to sync (so you have an idea of how quickly the sync will finish), and then wait until the sync has likely finished - does the UI become responsive again after that?

When I reopen the app, the sync has already finished. I can say that because I get a notification saying "Collection synchronized" in the notifications section of my phone.

However, I can't say the same about media sync because the media sync starts after the corresponding toast/snackbar appears in the app.
![Screenshot](https://github.com/ankidroid/Anki-Android/assets/92206575/4bc08dc0-d818-4070-ac1d-66d1a32b7900)

Nevertheless, most of the time, I don't have any media to sync.

Also, in my case, the delay before reopening the app seems to be important. I can't reproduce the bug if I reopen the app immediately after I get the "collection synchronized" notification.

**Comment by woj-tek** [comment]
Still happening in 2.16.3

**Comment by dae** [comment]
I suspect this may be related to view lifecycles, where a view is destroyed, but the backend syncing code will continue to run to completion. If my assumption is correct, it may require running the sync using a globalScope instead of using .launchCatchingTask on the current view.

**Comment by oakkitten** [comment]
> I think I have the same issue but even without wait

> The original reporter had the new backend on, so I'm not sure if these are the same issue or not.

Just here to note that I can repro the issue on the old backend and can't on the new one

**Comment by mikehardy** [comment]
I am not able to reproduce this on 2.17alpha9 and we have another new backend success report from oakkitten as well (thank you!)

So, this *may* still be happening and if so we can always reopen (let us know @user1823 , but I think with the new 2.17alphas using the new backend, this is fixed

**Comment by mikehardy** [comment]
Those are both large-ish projects and I'll defer until needed, we've got enough going on at the moment 😆 
We'll know when it's needed if we get a lot of error reports related to syncing - but right now there aren't many (and I've been working to track them all down and help fix them, over the last few days)
