### ISSUE TITLE
[BUG]: "Gray screen" to import file to Anki

### ISSUE THREAD

**Issue by juliocspeitzer** [ankidroid/Anki-Android#13760]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

When I import files (txt) to my deck (new and old decks) it shows a empty screen...I already used old versions and I uninstalled and install again, not working.

![erro](https://user-images.githubusercontent.com/26841231/235307754-66a90ee6-5063-4f15-89d6-538b1cb9db5a.jpg)

### Expected behaviour

I don't know, it was working perfectly... 

### Actual behaviour

I don't get to import files to any deck 

### Debug info

```text
Versão ⁨2.1.62 (fd509efc)⁩
Python 3.9.15 Qt 6.4.3 PyQt 6.4.0
```

### (Optional) Anything else you want to share?

I'm using on Windows 11 updated and yesteday it was working perfectly

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
Hey, sorry but this is the code repository for `AnkiDroid` an android mobile app. Try the [Anki desktop application code repository](https://github.com/ankitects/anki/issues) or the [Anki Forums](https://forums.ankiweb.net/).
