### ISSUE TITLE
Create more Promotion-worthy images for Play Store listing

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#13778]
Apparently the images we currently have in our Play Store listing are not "Promotion worthy", I believe (based on their note) because they are not 1080px+?

Here are their content guidelines: https://support.google.com/googleplay/android-developer/answer/9866151#screenshots&zippy=%2Cscreenshots

The content is, I think, fine on the current screenshots so I would not over-think re-doing them.

However here are the "Highly Recommended" guidelines for non-game apps, with a max dimension of 3840px as the upper limit to keep in mind:

> Highly recommended
>
> Some sections of Google Play show groups of recommended apps and games in a large format using screenshots. To be eligible for recommendations in formats that use screenshots, the following guidelines are a requirement:
For apps, you must provide at least four screenshots with minimum 1080px resolution. These should be 16:9 for landscape (minimum 1920x1080px) screenshots and 9:16 for portrait screenshots (minimum 1080x1920px).

**Comment by SanchitGeez** [comment]
I would like to work on this issue. Is anyone working on it?

**Comment by Viraj76** [comment]
I want to work on this issue

**Comment by david-allison** [comment]
Thanks!

**Comment by Viraj76** [comment]
Dear sir, I have one query should I recreate the available images in the play store with better resolution OR I could add some modifications also. Thanks.

**Comment by david-allison** [comment]
Just improving the resolution

**Comment by Viraj76** [comment]
I greatly appreciate being assigned this issue . I've successfully enhanced the resolution of all images available at  the Ankidroid App in play store. I achieved this by meticulously adhering to your guidance and thoroughly studying the provided guidelines:

1. Adhering to the content guidelines, I enlarged the dimensions of all images from their previous 810x1440px to the recommended 1080x1920px. 

2. I boosted the DPI (dots per inch) to 96dpi, a noticeable improvement from the previous 72dpi. Consequently, each image now boasts a heightened resolution.

3. Ensuring compliance with the guideline, I substantially reduced the text coverage in the images. Previously, images 1, 4, and 5 had text coverage percentages of 20%, 30%, and 30% respectively. Now, all images adhere to the guideline's requirement of 10% text coverage.

4. To align with the guidelines, I rectified image 5 by removing notifications and icons related to WiFi or other services when a status bar is present. This adjustment was facilitated by maintaining a higher resolution and appropriate dimensions.

Drive links for all the images -:
Image 1 -https://drive.google.com/file/d/1_cXFKlBJnnXO68u1jI-V3YTjCSAcYMSo/view?usp=sharing, 
Image 2 -https://drive.google.com/file/d/1jW9wtkOQk8DfWOiXgZqMBQpb_07OCEll/view?usp=sharing, 
Image 3 - https://drive.google.com/file/d/11qFO2RuTn-VZv9qDygPPUFln9SwfoZ4C/view?usp=sharing, 
Image 4 -https://drive.google.com/file/d/1kr_3R4Kgkij1Ds24ri0bV5UzzAqMlmNX/view?usp=sharing),
Image 5 -https://drive.google.com/file/d/1V5fkLR-2cY7pigURKgvmPgbvZmG0qdL0/view?usp=sharing, 

Thank You.

**Comment by david-allison** [comment]
Thanks!! On first glance, this looks good. Could you put in a PR to allow us to compare the changes more easily?

**Comment by Viraj76** [comment]
Sorry to ask you sir , but as these are images and I have not used Android SDK to solve this issue how I can commit and generate a PR , please help me .

**Comment by Viraj76** [comment]
Dear sir, I have made the PR 
enhanced images #14271

**Comment by Viraj76** [comment]
Dear @david-allison I have made a PR regarding this issue , please review it once. #14271

**Comment by david-allison** [comment]
I'm traveling today, but I see it breaks CI and it seems there's no change in files?

**Comment by Viraj76** [comment]
Dear @david-allison , as it issue was for enhancement of resolutions of the images that are listed in the Ankidroid in the play store. i.e. I have made changes in the images by following the guideline ( https://support.google.com/googleplay/android-developer/answer/9866151#screenshots&zippy=%2Cscreenshots). For generating the PR , am not finding those images in the App repo. i.e. it is not showing any changes . I just uploaded the better images in the drawable and made a PR. 

Please give me some guidance if am going wrong. 
Thankyou

**Comment by Viraj76** [comment]
Dear @david-allison sir , finally I have made changes and done in a proper way ,#14280 .

In last 24 hours I have learned a lot with your guidance. Thankyou so much for for kind guidance.
Please let me know if anywhere am lagging.

**Comment by rohit9625** [comment]
@Viraj76  Images are great and I appreciate your efforts. I strongly recommend you use AI for upscaling images these days. Anyways nice work.

**Comment by AffanShaikhsurab** [comment]
Is this issue still open ?

**Comment by david-allison** [comment]
Closed in #13778
