### ISSUE TITLE
Nested clozes not handled correctly

### ISSUE THREAD

**Issue by TRIAEIOU** [ankidroid/Anki-Android#13770]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

From fresh install of AnkiDroid 2.16alpha98:
1. Create new `Cloze` type note with the following content `one: {{c1::two: {{c2::three}}}}`
2. Review

### Expected behaviour

1. Review card `c1` as `one: [...]` → `one: two: three`
2. Review card `c2` as `one: two: [...]` → `one: two: three`

### Actual behaviour

1. Review of card `c1` functions as expected
2. Review card `c2`  gives the `empty_card_warning` string ('This card is empty. Use the "Empty cards"...') on the front/question side, the back/answer side shows correctly.

### Debug info

```text
AnkiDroid Version = 2.16alpha98
 
Android Version = 8.0.0
 
ProductFlavor = full
 
Manufacturer = Sony
 
Model = H8324
 
Hardware = qcom
 
Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; H8324 Build/51.1.A.11.51; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36
 
ACRA UUID = c1f2c4a1-961f-4b08-8fc4-ebd3ffbe236e
 
New schema = true
 
Scheduler = std3
 
Crash Reports Enabled = true
 
DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

I don't have a functioning dev environment for AnkiDroid but looking at the code one guess would be that [Models.emptyCard](https://github.com/ankidroid/Anki-Android/blob/7e376dbb52183e2758d17cf61a876c526c1fd9ed/AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt#L933) may be the culprit, as far as I can tell it ends up using [fClozeOrdPattern](https://github.com/ankidroid/Anki-Android/blob/7e376dbb52183e2758d17cf61a876c526c1fd9ed/AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt#LL846C21-L846C21): `private val fClozeOrdPattern = Pattern.compile("(?si)\\{\\{c(\\d+)::.*?\\}\\}")` which seems to not take nested clozes into account.

The "new" backend has the corresponding functionality that do take nested clozes into account, however as I understand it AnkiDroid does not by default use the "new" backend?

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, thanks for the report!

Is this a regression from 2.15.6?

**Comment by BrayanDSO** [comment]
> Is this a regression from 2.15.6?

Nested clozes are a new feature from one of the desktop versions that came after 2.15.6.

**Comment by TRIAEIOU** [comment]
> Nested clozes are a new feature from one of the desktop versions that came after 2.15.6.

Yes, nested clozes were only introduced a few months ago (with the backend version which is included from alpha 93 and forward I believe). I don't know what your plans are for moving to the "new" backend by default, if that is not on the immediate horizon then one (untested) way would possibly be to drop the closing `}}` from `fClozeOrdPattern`. That would however make the regex return a false positive for `c2` in something like `this {{c1::shouldn't {{c2::be a nested cloze}}`, although it is questionable how common that type on note writing is or if it would actually be a problem if the backend never presents a card for `c2` in this case?

**Comment by BrayanDSO** [comment]
Does it work fine wth the new backend?

**Comment by david-allison** [comment]
To be fixed in 2.17

**Comment by TRIAEIOU** [comment]
> Does it work fine with the new backend?

Yes, it has [`cloze_numbers_in_string()`](https://github.com/ankitects/anki/blob/ac7b63e81bb619483f89d70cedd09d94bb0eb489/rslib/src/cloze.rs#L379) which does the equivalent of what [`Models._availClozeOrds`](https://github.com/ankidroid/Anki-Android/blob/7e376dbb52183e2758d17cf61a876c526c1fd9ed/AnkiDroid/src/main/java/com/ichi2/libanki/Models.kt#LL1064C13-L1064C28) does (which `Models.emptyCards` uses):

```rust
pub fn cloze_numbers_in_string(html: &str) -> HashSet<u16> {
    let mut set = HashSet::with_capacity(4);
    add_cloze_numbers_in_string(html, &mut set);
    set
}

fn add_cloze_numbers_in_text_with_clozes(nodes: &[TextOrCloze], set: &mut HashSet<u16>) {
    for node in nodes {
        if let TextOrCloze::Cloze(cloze) = node {
            set.insert(cloze.ordinal);
            add_cloze_numbers_in_text_with_clozes(&cloze.nodes, set);
        }
    }
}
```

**Comment by TRIAEIOU** [comment]
As a another side note for anyone wanting the functionality in the mean time the following seems to be a hacky temporary measure that does the trick assuming that:

1. You are using the new backend
2. You are not using mathjax (it might work with mathjax but I haven't tested it)
3. You are not using AnkiDroid to generate your notes because this version bypasses an empty card check - the consequences of this bypass are not immediately clear to me
4. You understand that I have not tested this extensively

Credit to [jaytea](https://stackoverflow.com/users/410484/jaytea) for [non-recursive bracket balancing regex](https://stackoverflow.com/a/47162099) and [Bart Kiers](https://stackoverflow.com/users/50476/bart-kiers) for [matching string without `{{`](https://stackoverflow.com/a/406408):

diff vs 2.16.0beta1
```diff
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
index eb4461bb8..48db134d6 100644
--- a/AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt
@@ -308,7 +308,7 @@ open class Card : Cloneable {

     open val isEmpty: Boolean
         get() = try {
-            Models.emptyCard(model(), ord, note().fields)
+            false // Models.emptyCard(model(), ord, note().fields)
         } catch (er: TemplateError) {
             Timber.w("Card is empty because the card's template has an error: %s.", er.message(col.context))
             true
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt
index 0a2e999d8..4cc7b88c1 100644
--- a/AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.kt
@@ -36,7 +36,8 @@ import java.util.regex.Pattern
 object TemplateFilters {
     const val CLOZE_DELETION_REPLACEMENT = "[...]"
     private val fHookFieldMod = Pattern.compile("^(.*?)(?:\\((.*)\\))?$")
-    const val CLOZE_REG = "(?si)\\{\\{(c)%s::(.*?)(::(.*?))?\\}\\}"
+    // const val CLOZE_REG = "(?si)\\{\\{(c)%s::(.*?)(::(.*?))?\\}\\}"
+    const val CLOZE_REG = "(?si)\\{\\{(c)1::((?:(?=.*?\\{\\{(?!.*?\\3)(.*\\}\\}(?!.*\\4).*))(?=.*?\\}\\}(?!.*?\\4)(.*)).)+?.*?(?=\\3)(?!.*?\\{\\{).*(?=\\4(?:\\n|\$))|.*?)(?:::(.*?))?\\}\\}"

     /**
      * @param txtInput The content of the field field_name
@@ -136,8 +137,8 @@ object TemplateFilters {
             @KotlinCleanup("maybe make non-null")
             var buf: String?
             buf = if (type == 'q') {
-                if (!m.group(4).isNullOrEmpty()) {
-                    "[" + m.group(4) + "]"
+                if (!m.group(5 /*4*/).isNullOrEmpty()) {
+                    "[" + m.group(5 /*4*/) + "]"
                 } else {
                     CLOZE_DELETION_REPLACEMENT
                 }
```

**Comment by teacupdave** [comment]
Hi.  Still searching for solutions.

Not sure if this helps, but here is an example of a card I have which is exhibiting this issue, but not with any pattern I can find.  I just went through all cards of the note on my AnkiDroid and marked all cards that were showing as empty with a flag.  Oddly, the only 2 that aren't showing are Cloze 4 & 14.  I can't identify any significant difference between Cloze 4 and 5, yet 5 works and 4 doesn't.

My ANKIdroid is 2.16.5.  For reference I am not a programmer, but I have self-taught limited HTML & CSS skills to program Anki cards.

`Hormones are released in response to neural innervation or in response to triggers associated with ingested food
<br><br>Gut functions influenced include: {{c1::secretion, digestion, motility, &amp; absorption::LIST}}


<h1>Phases of Digestion</h1>
The phases of digestion are: {{c13::Cephalic phase, Gastric phase, &amp; Intestinal phases::LIST the phases of digestion}}


<h1>Hormonal Response</h1>Hormones released by the GIT in response to a meal include:<br><br><table border="1" style="border-collapse: collapse;">
  <tbody style="vertical-align: top;">
    <tr style="background-color: rgb(53, 152, 219);">
      <td>Early response to a meal</td>
      <td>During digestion of meal</td></tr>
    <tr>
      <td>{{c2::<ol>
        <li>ACh</li>
        <li>Gastrin</li></ol>
        ::LIST}}</td>
      <td>{{c3::Mnemonic: GMC SINS<ol>
        <li>Glucose Insulinotropic Peptide (GIP)</li>
        <li>Motilin</li>
        <li>Cholecystokinin</li>
        <li>Somatostatin</li>
        <li>Insulin</li>
        <li>Neurotensin</li>
        <li>Secretin</li></ol>
        ::LIST}}</td></tr></tbody></table>

<span class="ignore">{{c2::{{c3::</span>

<h2>Hormones released early in response to a meal</h2>
<h3>Acetylcholine</h3>
{{c4::<ul>
  <li>Released from: <b>postganglionic vagal fibres</b></li>
  <li>In response to: the <b>cephalic</b> &amp; <b>gastric phases</b> of digestion</li>
  <li>Triggering: <b>gastrin</b> secretion from gastric G cells</li>
</ul>::OUTLINE the hormone in the context of a meal}}

<h3>Gastrin</h3>
{{c5::<ul>
  <li>Secreted by: <b>antral G-cells</b></li>
  <li>In response to: <i>luminal </i><b>food</b> &amp; <b>vagal stimulation</b></li>
  <li>Triggering: <b>gastric acid</b> &amp; <b>pepsinogen</b> secretion, and <b>reduced gastric emptying</b> via <i>CCK receptors</i></li>
</ul>::OUTLINE the hormone in the context of a meal}}

<h2>Hormones released during digestion of meal</h2>
<h3>Glucose Insulinotropic Peptide (GIP)</h3>
{{c6::<ul>
  <li>Secreted by: <b>jejunal K-cells</b></li><li>In response to: <i>luminal </i><b>glucose</b>, <b>fatty acids</b>, &amp; <b>amino acids</b></li><li>Triggering: <b>increased glucose-insulin response</b>, and <b>decreased gastric motility</b> &amp; <b>acid secretion</b><br></li>
</ul>::OUTLINE the hormone in the context of a meal}}

<h3>Motilin</h3>
{{c7::<ul>
  <li>Secreted by: <b>upper gut M-cells</b></li><li>In response to: <i>luminal </i><b>alkalinity</b> of the intestinal chyme.</li>
  <li>Triggering: <b>increased gut motility</b>, likely initiation of the {{c14::<b>migrating motor complex</b> (MMC)::physiological process}}.</li>
</ul>::OUTLINE the hormone in the context of a meal}}

<h3>Cholecystokinin</h3>
{{c8::<ul>
  <li>Secreted by: <b>duodenal &amp; jejunal I-cells</b></li><li>In response to: <i>luminal </i><b>fatty acids</b> &amp; <b>amino acids</b></li>
  <li>Triggering: <b>GB contraction</b>, <b>pancreatic enzyme secretion</b>, <b>reduced gastric emptying</b>, &amp; <b>satiety</b></li>
</ul>::OUTLINE the hormone in the context of a meal}}

<h3>Somatostatin</h3>
{{c9::<ul>
  <li>Secreted by: <b>pyloric gland D-cells</b></li><li>In response to: <b>increasing<i> luminal </i>acid levels</b> (i.e. <i>as a meal progresses</i>)</li>
  <li>Triggering: <b>reduced gastrin &amp; gastric acid secretion</b></li>
</ul>::OUTLINE the hormone in the context of a meal}}
  
<h3>Insulin</h3>
{{c10::<ul>
  <li>Secreted by: <b>pancreatic β-cells</b> in <i>Islet of Langerhans</i></li><li>In response to: <i>plasma </i><b>glucose &gt; 5 mmol/L</b></li>
  <li>Triggering: multiple actions including: <b>cellular carbohydrate uptake</b>, and <b>altered protein &amp; lipids metabolism</b></li>
</ul>::OUTLINE the hormone in the context of a meal}}

<h3>Neurotensin</h3>
{{c11::<ul>
  <li>Secreted by: <b>ileum &amp; rectal N-cells</b> (i.e. found in the end of the small &amp; large guts)</li><li>In response to: <i>luminal </i><b>fatty acids</b></li>
  <li>Triggering: <b>decreased GIT motility</b></li>
</ul>::OUTLINE the hormone in the context of a meal}}
  
<h3>Secretin</h3>
{{c12::<ul>
  <li>Secreted by: <b>duodenal S-cells</b></li><li>In response to: <i>luminal </i><b>acidity</b></li>
  <li>Triggering: <b>biliary &amp; pancreatic bicarbonate secretion</b>, and <b>inhibition of gastrin &amp; gastric acid secretion</b></li>
</ul>::OUTLINE the hormone in the context of a meal}}<br>::ignore}}<br>::ignore}}`

**Comment by mikehardy** [comment]
2.17 is now in beta! so it is a bit easier to get: https://ankidroid.org/#betaTesting
