### ISSUE TITLE
Lint didn't pick up MissingCopyrightHeader

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13786]
FYI: This one got past the lint check

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/13780#discussion_r1183135212_

**Comment by lukstbit** [comment]
The lint rule check works locally, I managed to replicate this by using _amend_:

- commit code with the lint failure suppressed
- use git commit --amend and remove the previous method of suppression

**Comment by david-allison** [comment]
The lint check works for me in the IDE, but not via gradle: `gradlew lint` / `gradlew lintFullRelease` didn't pick up the issue when I checked out the PR

**Comment by lukstbit** [comment]
It seems our custom rules aren't applied if ran through gradlew lint.

**Comment by criticalAY** [comment]
it is not just ignoring this issue but the others too like the direct toast usage
