### ISSUE TITLE
Increase Crash Database Performance

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#13781]
**Is your feature request related to a problem? Please describe.**

Acrarium, our crash-reporting front-end working as a Java<->MySQL app on https://ankidroid.org/acra is pretty slow, we would like to increase the performance.

Currently it is on the basic droplet at digitalocean with 1GB RAM + 1 "regular" vCPU @ $7/month (details: https://www.digitalocean.com/pricing/droplets)

**Describe the solution you'd like**

The app is definitely RAM-bound and appears to be CPU-bound (this could be the JDK garbage collection working over time in low RAM)

Fitting the crash reporting front-end into 1GB was quite difficult.

I would like 2GB RAM and 1 "premium" vCPU for performance reasons, at a cost of $14/month as a first attempt at "throwing hardware at the problem".

If that works, we are done. If not then perhaps we need more CPU

**Describe alternatives you've considered**

I definitely am not able to fit the app in to less RAM, I had to write a special set of instructions that was merged upstream for it to even work with this tiny amount of RAM.

It is not possible to go lower than one CPU so I cannot consider that.

I have considered more CPUs but want to try a premium CPU first as those monthly price jumps are large.

I have considered reducing the dataset in the front-end but testing it by purging out almost all reports did not result in adequate performance.

Other crash reporting systems do not meet the project's requirements, so ACRA is best, and this is the only supported front-end for those reports.

**Additional context**

Here is where @dae comes in - Damien - you are currently paying for this. I suppose I should switch billing information to me, then I can submit for reimbursement to OpenCollective so that AnkiDroid takes on the expense in general, and shoulders the price increase?

**Comment by Arthur-Milchior** [comment]
You may want to note whether it’s premium intel or amd. And I assume it remains in the basic droplet category

**Comment by mikehardy** [comment]
No price difference between the two cpu vendors and they only guarantee "from latest 2 generations" so can't compare them directly meaning I'm indifferent to the CPU vendor but premium should be faster than generic based on their docs. A nice middle step before going to 2 CPUs


Still the basic droplet yes, having a dedicated vCPU is overkill I think

**Comment by dae** [comment]
Sorry, I saw this yesterday but forgot to reply. Happy to assign the account over to you if that's more convenient and the OC income is stable. Before doing that, I'd suggest you also consider Hetzner - you could get 8GB RAM for less money, or 4 vCPU for about $1 more. https://www.hetzner.com/cloud

**Comment by mikehardy** [comment]
oh nice @dae - that does look attractive, hadn't scanned this market in quite a while, thanks.

I will keep that on the radar but right now just for expediency it would be nice to see if throwing hardware at it even works (it might not!), before going through any re-hosting hassle.

OpenCollective income is definitely stable enough to support a monthly charge like what I'm considering while still at digital ocean

If more hardware has little/no effect then I'll have to look at something else, if it does work then I'll queue up re-hosting as a future cost optimization

**Comment by dae** [comment]
From what I can tell from [their docs](https://docs.digitalocean.com/products/images/snapshots/how-to/change-owners/#:~:text=To%20transfer%20a%20Droplet%20to,menu%20and%20select%20Change%20Owner.), the way to transfer ownership is to take a snapshot of the server, then import the snapshot into a new account that you control. It will be given a new IP address, so we then just need to point ankidroid.org at the new IP. I think you may have permission to create a snapshot already, but I'll need to update the DNS entry when you're ready.

Alternatively I can just resize the droplet for now, but it needs to be shut down to do that. Is it safe to shut it down via DigitalOcean and have it come back automatically, or do you want to ssh in and do a clean shutdown/ensure services restart afterwards? If so it'll need to be at a time we're both around; it's evening here, so I'll next be back in around 12 hours

**Comment by dae** [comment]
(can transfer DNS ownership too if you'd prefer, but I presume that'll take a few days)

**Comment by mikehardy** [comment]
Hmm 🤔 to be honest this all sounds like a hassle though the full hassle (take DNS ownership, install somehow - via snapshot transfer or on another host - under a controlled account) is the objectively correct course.

What I'm looking for *right* now that would help direct any future effort is to answer the question "will more hardware resource actually improve performance" though.

The fastest way to answer that question and direct effort is I think to just resize CPU/RAM right now under your control still as a test. If we could do that it would be really fast.

As long as you don't resize disk as well, it is reversible in case it has no effect and we want to maintain status quo while looking for other solutions

Seems like you'll be around in about 6 more hours (that's...5pm or so my time) - can you @ me when you're back around and I can do a clean shut down + you can just try a resize to 1 premium intel CPU + 2GB RAM ?

If that fails it might be worth subsequently trying (after some config work on my part...) a 2 vCPU + 2GB+ RAM setup

The results of those tests will be important for any future decisions I think

**Comment by dae** [comment]
@mikehardy have sent you a message via Google Chat

**Comment by mikehardy** [comment]
Okay! With the "1 premium vCPU / 2GB RAM" droplet size we have what *appears* to be adequate performance, though I'm waiting on confirmation (or disagreement) from other users

Assuming it is good, next steps here are to:

- transfer ankidroid.org DNS to an ankidroid account
- either create a new server somewhere else ready to take the traffic, *or* create a new digitalocean account that ankidroid controls and transfer a snapshot to it to start the server up under ankidroid account
- re-point the DNS to the new IP of the new server

At that point we should have sufficient performance *and* ankidroid will assume the cost + have control

Damien is okay with this being tabled until after scoped storage is released, so I'm going to mark this infrastructure and blocked by dependency...
