### ISSUE TITLE
[Bug] Error: App not installed as package appears to be invalid.

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#13798]
I tried to install the play version of the latest beta (2.16.0beta1).

The installation failed with the error: App not installed as package appears to be invalid.

###### Debug info
This debug info is from the full version that is currently installed on my device.

AnkiDroid Version = 2.16.0beta1

Android Version = 12

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g62 5G Build/S2SSIS32.18-12-4-6; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = c6a580cb-02cc-4970-b7a5-24615e6542e1

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
Uninstall existing previous version of app.
And install latest version
