### ISSUE TITLE
AnkiDroid not available in Play Store for new Android versions [WORKAROUND INCLUDED]

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#13797]
Hi guys,

Just in case you weren't already aware of this, it looks like Google may have selectively blocked you after that May 1 deadline:

https://www.reddit.com/r/Anki/comments/137cgk4/ankidroid_doesnt_work_on_android_13/

----

AnkiDroid is not available in the Play Store for new Android versions until we release version 2.16 that migrates to the new scoped storage regime that Google requires.

**WORKAROUND**

If you must have AnkiDroid on a newer Android version now, and the Play Store says it is not available, you have a few ways to get it:

- **Beta channel**: 
  - join the Beta channel in the Play Store https://ankidroid.org/#betaTesting
  - we are rolling out 2.16.0 betas right now (currently at 40% rollout) to beta testers and you may receive 2.16.0beta versions after a day or so, then you are set
- **Alpha channel**:
  - If you still have not received the betas you may not be in the target population (#13801) at which point you may join the alpha channel https://ankidroid.org/#alphaTesting
  - *all* our builds are promoted through alpha first, so even though we are at the "beta" release phase at the moment, they go through the alpha channel. All builds are rolled out to 100% of alpha testers though so you are guaranteed to receive v2.16
- **Direct install**:
  - grab the release directly from our releases page
  - you will likely want the "arm64-v8a" apk https://github.com/ankidroid/Anki-Android/releases

**Comment by SanjaySargam** [comment]
My Android Version is 13.
But not able to reproduce in my case

**Comment by dae** [comment]
Maybe they make an exception for people who previously downloaded the app? Had another report on the forums about an hour ago: https://forums.ankiweb.net/t/downloading-error-from-play-store/30015

**Comment by BrayanDSO** [comment]
> My Android Version is 13.
But not able to reproduce in my case

Same. But the reports are real. We gotta run before losing more users

**Comment by mikehardy** [comment]
We'll be back before too long, order of days I think. I'm surprised it is only a partial outage in fact (that is: still seems to be available for lower APIs?)

Anyway, plan is to release absolutely as soon as responsibly possible. Waiting on one blocker at the moment before we release 2.16.0beta2 and otherwise have not seen too many other issues so things are looking good for a release shortly

**Comment by 4523polu** [comment]
Hi! New here but concerned about this, because I need to download it. How long do you think is gonna take to release it newly in Play store? I want to use it but it is not possible

**Comment by uqs** [comment]
Can confirm, I was able to install it on a Pixel 6 about 3 weeks ago, then my wife wanted to install it on her Pixel 6 yesterday and Play Store claims the app is now too old. So all new installs are blocked on up-to-date Android versions.

**Comment by BrayanDSO** [comment]
Now available 
![StandingOvationGIF](https://github.com/ankidroid/Anki-Android/assets/69634269/5931a88f-d877-47a8-9124-6e56c1cce7eb)
