### ISSUE TITLE
[Bug] "Card browser" item gets in bold after users going back from "Statistics" screen to "Decks" 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#13818]
###### Reproduction Steps

1. Start the app
2. Open the navigation drawer

5. Choose "Statistics"
6. Go back to the deck picker screen
7. Open the navigation drawer

###### Expected Result
"Card browser" is not in bold. Same status as the step 2 above.
   <img src="https://user-images.githubusercontent.com/10436072/236759033-55f31488-2adc-447f-b24b-4cf1121024fb.png" width="320px">
###### Actual Result
"Card browser" is in bold as well as the actually selected "Decks"
<img src="https://user-images.githubusercontent.com/10436072/236759669-dbda216b-257f-4d78-b272-c59cad3dbbc9.png" width="320px">

###### Debug info
```
AnkiDroid Version = 2.16.0beta1

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36

ACRA UUID = 5ba46727-9ddb-47f3-a810-53f66d97a89e

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
working on it

**Comment by SanjaySargam** [comment]
This bug was introduced between alpha92 and alpha93
