### ISSUE TITLE
Warmup latency for audio is very long when using Bluetooth earphones

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#13810]
Reproduction steps:

1. Connect Bluetooth earphones.
2. Play audio(or TTS) by flipping a card. (Allow at least 4 seconds between audio)
3. Play audio(or TTS) by flipping a card while playing music in the background.
4. There is a significant additional delay in sound playback only in step 2 (probably several hundred milliseconds).

It is suspected that the issue is related to warmup latency, as the playback delay is significantly reduced when playing silent music in the background. As more Android smartphones are being released without headphone jacks and the app is designed to flip through many cards, this is not considered a minor issue and is being posted as an issue on GitHub.

If long warmup latency occurs again at intervals of around 4 seconds, it's possible that some users may experience additional latency on all cards.

Device used: Zenfone 8 flip (android 13), EarFun Air Pro 3 (Game mode)
Ankidroid version: 2.16.0beta1

Related article:
https://developer.android.com/ndk/guides/audio/audio-latency#warmup-latency
While the article above suggests playing continuous silence as a hack, it is unclear whether this is appropriate for Ankidroid.

**Comment by david-allison** [comment]
This should be improved, agreed.

For now, make a `silence.mp3` of an appropriate length and add it to the card template you use for reviewing

**Comment by mikunimaru** [comment]
> This should be improved, agreed. It'll be difficult as different bluetooth devices have different latencies (and Android's Bluetooth implementation isn't fun)

Since this issue is related to the warmup delay, I think there is a mitigation strategy for that specific aspect of the problem.

> For now, make a `silence.mp3` of an appropriate length and add it to the card template you use for reviewing

Personally, I think it would be ideal if there was no long warmup delay again when playing the audio of the next card until the "Maximal answer time" in the deck options has elapsed.

However, simply adding a silent MP4 to the template may not avoid the issue, as there is a possibility that another audio may start playing when the card's play button is clicked, causing the silent audio to stop. To work around this issue with the current functionality, it may be necessary to insert relatively advanced JavaScript code into the template
