### ISSUE TITLE
[Bug]: MathJax is not defined

### ISSUE THREAD

**Issue by nihil-admirari** [ankidroid/Anki-Android#13819]
###### Reproduction Steps

1. Clone Cloze template.
2. Add the following to the template
    ```html
    {{cloze:Text}}

    <div id="rendered-cloze"></div>

    <script type="module">
      const rendered = document.getElementById('rendered-cloze');

      function msg(m) {
          rendered.textContent += m + '\n';
      }

      try {
          MathJax.startup.promise.then(() => msg('MathJax loaded')).catch(msg);
      } catch (e) {
          msg(e);
      }
    </script>
    ```
3. Create a cloze card and open it.

###### Expected Result

`MathJax loaded` appears on card's front (like in desktop's Anki).

###### Actual Result

`ReferenceError: MathJax is not defined`.

###### Debug info

```
AnkiDroid Version = 2.16.0beta1

Android Version = 13

ProductFlavor = full

Manufacturer = Google

Model = sdk_gphone_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone_x86_64 Build/TE1A.220922.025; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 9934c73d-f97a-4faa-bc39-03ea4ebd8aea

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report. Did this work on AnkiDroid 2.15.6?

**Comment by nihil-admirari** [comment]
> Did this work on AnkiDroid 2.15.6?

No.

> Does it work in Anki Desktop?

Yes.

**Comment by nihil-admirari** [comment]
> However I seem to recall that for performance reasons we only load mathjax conditionally?

True. [A simple test for `undefined`](https://github.com/nihil-admirari/modern-cloze-overlapper/commit/4634108bc7f769aa6875a0ea5d05f099b7fd2e91#diff-230e14ca431559afda426713646cafcab628abad91a2f0445035b0d4c35565e6R285) avoids the error, while still allowing MathJax to be used, when it's actually needed.

Closing as non-issue.
