### ISSUE TITLE
[Bug] The new backend strings are shown in the system language instead of Ankidroid configured language

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#13813]
###### Reproduction Steps

1. "Settings" -> "Language" -> Select any language other than the system language
2. (Re)start AnkiDroid
3. Enable the new backend
4. Show "Statistics" or "Deck options"

    (Doing 3 before 1 is also okey.)

###### Expected Result
The strings are shown in the configured language on AnkiDroid

###### Actual Result
The strings other than the title are shown in the system language
<img src="https://user-images.githubusercontent.com/10436072/236679230-0836cf1d-3f2b-4b99-969d-3319a9ef9b84.png" width="320px">

######  Anything else you want to share?
The new backend strings (Anki Desktop strings) in the menu and the toasts are also shown in the system language.
<img src="https://user-images.githubusercontent.com/10436072/236678988-7f908e5c-7d6b-48fc-89e0-0caba2429138.png" width="320px">

###### Debug info

```
AnkiDroid Version = 2.16.0beta1

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/111.0.5563.116 Mobile Safari/537.36

ACRA UUID = 5ba46727-9ddb-47f3-a810-53f66d97a89e

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
I can’t reproduce (including in japanese)

**Comment by snowtimeglass** [comment]
Added more details to the reproduction steps above.

**Comment by BrayanDSO** [comment]
The issue I got is the opposite: being on the previous language after changing to the System language. I'll do a PR for that

**Comment by snowtimeglass** [comment]
When I perform the following steps that you mention, your issue is reproduced on my device as well.

1. Enable the new backend
2. Change language to any other than the system language
3. Check if the statistics screen uses the new language
4. Change app language to "System language"
5. Check if the statistics screen uses the system language
   -> It doesn't use the system language (until you restart the app) [**Problematic**]

I suppose that changing the above 4 and 5 of your steps to the following 4' and 5' will reproduce the issue I'm concerned about on your device as well.

4': Restart AnkiDroid
5': Check again if the statistics screen uses the system language new language
       -> It doesn't use the new language. It uses the system language. [**Problematic**]

**Comment by BrayanDSO** [comment]
I still can't reproduce your issue

**Comment by snowtimeglass** [comment]
It’s unexpected for me. Some unnoticed requirements or the difference of the versions of Android might be the cause...?

The actual steps (1>2>3>4'>5') are as follows:

https://github.com/ankidroid/Anki-Android/assets/10436072/5cf97093-14b8-4aed-9d42-bcfd7df68dae

- The issue is also reproduced on the main (not parallel) version, though this video shows parallel.B
- It is also reproduced on another device (Android 9)

**Comment by BrayanDSO** [comment]
I think that I did the same steps (2.16beta01 from the releases page)

https://github.com/ankidroid/Anki-Android/assets/69634269/a4366c9e-3a87-4bd7-9e4e-b3903e68c20e
