### ISSUE TITLE
Training mode

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1381]
Originally reported on Google Code with ID 478
```
Hi,

Nicolas Raoul asked me to create an issue for what i wrote here: http://groups.google.com/group/anki-android/browse_frm/thread/36060f0a3204fad6

I'd be great to have a pure training mode in which i can browse through my cards back
and forth (by button and/or gesture) in the same way as in review mode. But with these
differences:

- question and answer are visible at once (because it's training/learning) mode
- the review buttons are not shown, only prev/next button for browsing through the
cards

I'm currently missing such a learning/training mode because in review mode i always
feel like in a test situation and that prevents me from learning in a relaxed way.



Thx for Ankidroid and keep up the good work.

Stefan
```

Reported by `stefan.schelling` on 2011-02-28 09:54:22

**Comment by stepelu** [comment]
By any chance, has any progress been made regarding this enhancement?

I too would really welcome a proper training mode: right now I just "study" the cards but what happens in practice (as I have a learning rate on the deck of 10 cards/day) is that I have to go through all 10 cards before starting to review the first one, by which time I have already forgotten it. Same for the second card...

If I properly memorise the 10 cards beforehand this does not happen, but it means having to take with me a heavy book every day (and reading it while commuting on cramped transports is not fun :D).

I am actually happy to sponsor this if it helps moving this issue forward.
