### ISSUE TITLE
Crash on edit Android 13

### ISSUE THREAD

**Issue by brownbat** [ankidroid/Anki-Android#13829]
When tagging a card as leech during review, app suddenly crashes with "Sending a message to the developers..."

When editing a note, the error is "Collection not opened: An error occurred while accessing your collection..." Then it prompts for a resynch. Editing a note from within review produces the same error.

(Will export notes below.)

**Comment by david-allison** [comment]
Thanks, could you provide debug info?

**Comment by brownbat** [comment]
[exported-notes.zip](https://github.com/ankidroid/Anki-Android/files/11436738/exported-notes.zip)

No problem, will attach debug info separately. Thanks for taking a look.

**Comment by brownbat** [comment]
AnkiDroid Version = 2.15.6

Android Version = 13

Manufacturer = samsung

Model = SM-G9980

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G9980 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = 05ffb7c4-99ce-4bb3-b0f1-2ae0abe39f95

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by n1snt** [comment]
I tried replicating this issues but it seems to be working fine here.
I tried editing a note & tagging card as leech as well.
![image](https://github.com/ankidroid/Anki-Android/assets/46300244/a532d704-0512-428d-93f8-b2e25dd76396)

**Comment by brownbat** [comment]
Still an issue that replicates for me as of 19 May.

I thought it might be scoped storage issues but: 
AnkiDroid directory:
/storage/emulated/0/AnkiDroid

So couldn't figure out why writing logs would be fine but writing card content would break. Suspecting some unique permission. Digging into app permissions shows that AnkiDroid does have one special custom permission "Read and write to the AnkiDroid database." This gets automatically removed if the app is unused for a while, explaining why the app was working fine, then when I went back to it after reviewing on PC a while, it broke.

Does Android let you catch explicitly a permissions error during write attempts and prompt the user to restore that permission before crashing?

**Comment by brownbat** [comment]
Ugh, had a crash again today on a leech and that custom permission, and all permissions, were enabled. Back to square one on diagnosing this.

**Comment by dae** [comment]
Tentatively assuming the new backend has fixed it. Please post back if a 2.17 (alpha) still exhibits this problem.
