### ISSUE TITLE
[BUG]: "lose current input" even when there is no input

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13821]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

* Open ankidroid
* tap "add card"
* tap return on the device

### Expected behaviour

Closing the note editor

### Actual behaviour

Being asked whether I want to close and lose current input. While there is NO input

### Debug info

```text
Running on 8a93414e89
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
I can reproduce the bug with the given reproduction steps.

**Comment by asirrosa** [comment]
Hello there could i take this issue?

**Comment by asirrosa** [comment]
Hello, i finished this issue but i just realized that there could be another bug related with this:

If the user tries to clicks in the add button, changes the type and afterwards tries to go back to the homepage, in the case of some types the alert dialog is shown and in other cases it is not shown. It seems pretty strange, and I discovered it making tests for the other issue.
