### ISSUE TITLE
[BUG] Toast text not visible on android 13 dark theme

### ISSUE THREAD

**Issue by pochopsp** [ankidroid/Anki-Android#13831]
The toast appearing when you press back button to exit with the text "Press back again to exit" has text not visible on android 13 with dark theme enabled.

Here's the screenshot from android 7 (in which text is visible):
![7](https://github.com/ankidroid/Anki-Android/assets/50794441/b3b35a3e-87ef-4f40-a93d-252b5809b8af)

Here's the screenshot from android 13 (in which text is NOT visible):
![13](https://github.com/ankidroid/Anki-Android/assets/50794441/b348bcd1-8908-45a6-ab16-16e19bda00e2)

I think this bug has been already reported on material components repository: https://github.com/material-components/material-components-android/issues/3003 and there's a solution in the second to last message.

Best regards

**Comment by pochopsp** [comment]
Sure, here it is:

```
AnkiDroid Version = 2.15.6

Android Version = 13

Manufacturer = Google

Model = Pixel 4a

Hardware = sunfish

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 4a Build/TQ2A.230505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = 3bfd860a-321d-46a9-9a80-ad60a3cf23c8

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by pochopsp** [comment]
@SanjaySargam do you use dark theme?
I also know that Realme / Xiaomi and other manufacturers use a heavy customized version of android, so that could explain why it's fine to you.

I have a google Pixel and it uses the stock android configuration

**Comment by SanjaySargam** [comment]
> @SanjaySargam do you use dark theme?
> I also know that Realme / Xiaomi and other manufacturers use a heavy customized version of android, so that could explain why it's fine to you.
> 
> I have a google Pixel and it uses the stock android configuration

Yes, I used a dark theme

**Comment by pochopsp** [comment]
@criticalAY could you please tell me where I can find the newest beta? I'm sorry but I am a bit unexperienced with this stuff

**Comment by criticalAY** [comment]
@pochopsp if the bug is fixed you can't access the fixed code unless the next beta is released or you have the debug version running which is updated from the mainstream branch so please wait for the next beta which is released I guess or for the stable release (on Playstore soon)

**Comment by pochopsp** [comment]
thanks @SanjaySargam 
I installed AnkiDroid-2.16.0beta2-arm64-v8a.apk and the toast is not present at all, neither a snackbar.

When i press back button to exit, it just exit, it doesn't show any toast/snackbar for confirmation

**Comment by criticalAY** [comment]
Check if it is enabled from the settings

**Comment by SanjaySargam** [comment]
@david-allison 
We are no more using toast in latest build 
You can close this as completed
