### ISSUE TITLE
[BUG]: Wrong icon tint

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#13838]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

There are icons that don't show the icon tint colour they are supposed to show 
-> drawing layout has a pen icon that is shown in black color rather than white in the toolbar though it is set to white but for some reason, it does not work 

### Expected behaviour

In light mode the pen color is white

### Actual behaviour

Black

### Debug info

```text
AnkiDroid Version = 2.16.0beta1-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = OnePlus

Model = EB2101

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; EB2101 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = 30fe5941-45f0-4cae-b24f-4345edd9b3a5

New schema = true

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
could you please provide screenshot? I admit it's not clear to me. Maybe I don't have enough contrast, or whatever, but I can't figure out what you're speaking about

**Comment by criticalAY** [comment]
![Screenshot_2023-05-12-08-24-26-03_7b5228b5a93c00ecba98ecb0735c59e2.jpg](https://github.com/ankidroid/Anki-Android/assets/48384865/9d2d8e4e-0c62-44cf-83f5-7d706fd268e7)

**Comment by Mamun-Yusef** [comment]
- I have the same issue. It happened after the [2.16alpha95] update and the migration of media files. 

- All other media files (jpg, PNG, mp3) display properly except Mp4 files. Only The audio of the Mp4 is played.

- The video files are synced (They play in the file explorer of the tablet) but only audio is played in Ankidroid.

- There is also no problem in Anki for Windows.

**Comment by Mamun-Yusef** [comment]
> > * All other media files (jpg, PNG, mp3) display properly except Mp4 files. Only The audio of the Mp4 is played.
> 
> Hey @Mamun-Yusef This issue has been solved

I am on 2.16.0beta1 and still have the issue on two different devices.

**Comment by SanjaySargam** [comment]
> > > * All other media files (jpg, PNG, mp3) display properly except Mp4 files. Only The audio of the Mp4 is played.
> > 
> > 
> > Hey @Mamun-Yusef This issue has been solved
> 
> I am on 2.16.0beta1 and still have the issue on two different devices.

Did you updated your repo ?
The PR just merged 3 hours ago

**Comment by Mamun-Yusef** [comment]
> > > > * All other media files (jpg, PNG, mp3) display properly except Mp4 files. Only The audio of the Mp4 is played.
> > > 
> > > 
> > > Hey @Mamun-Yusef This issue has been solved
> > 
> > 
> > I am on 2.16.0beta1 and still have the issue on two different devices.
> 
> Did you updated your repo ? The PR just merged 3 hours ago

Thank you, very much @SanjaySargam! 

Will check that out.
