### ISSUE TITLE
[Bug] 2.16.0beta1 - API 21: "Close and lose current input" appears again when cancelled

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#13834]
###### Reproduction Steps

1. Add Note
2. Type in first field
3. Add a tag: `aa::bb`
4. Press the back icon in the menu bar
5. "Close and lose current input" appears
6. Press "cancel"

###### Expected Result

Note Editor is uable

###### Actual Result

Another dialog showing "Close and lose current input" appears

###### Debug info
```
AnkiDroid Version = 2.16.0beta1-debug

Android Version = 5.0.2

ProductFlavor = amazon

Manufacturer = unknown

Model = Android SDK built for arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 5.0.2; Android SDK built for arm64 Build/LSY66K) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/37.0.0.0 Mobile Safari/537.36

ACRA UUID = 8f217ac1-e3d4-4e94-83d0-064a50054588

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
Working on it
