### ISSUE TITLE
[BUG]: Move cursor to end in TagsDialog

### ISSUE THREAD

**Issue by gayatriii0803** [ankidroid/Anki-Android#13841]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to NoteEditor
2. Click on Tag
3. Rename the Tag

### Expected behaviour

The cursor must at the end of EditText

### Actual behaviour

The cursor is at start
![tag](https://github.com/ankidroid/Anki-Android/assets/119813120/7bce10a1-515b-4a2d-ab04-6d2fcd1eaa22)

### Debug info

```text
AnkiDroid Version = 2.16.0beta1-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_x86_64 Build/TE1A.220922.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 31240e53-bc26-41a8-b8d0-c4c90159c405

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by sargamgayatri** [comment]
I am working on this issue
