### ISSUE TITLE
Is it possible to disable ankidroid gestures only on certain elements like scrollable elements?

### ISSUE THREAD

**Issue by basvdelsen** [ankidroid/Anki-Android#13857]
**Is your feature request related to a problem? Please describe.**
I have a horizontally scrollable element in my anki cards, I like having swipe gestures on, however this creates the issue that when I try swiping through the scrollable content it triggers the gesture and swipes to the next card.

**Describe the solution you'd like**
I'd like to be able to exclude scrollable elements from swipe gestures.

**Describe alternatives you've considered**
I've tried methods with javascript like event.preventDefault(); or event.stopPropagation(); but these either don't do anything or disable the scrolling.

**Comment by huandney** [comment]
I was also wondering how I could do this, since `Event.preventDefault();` and `Event.stopPropagation();` seems not to work. :/

**Comment by BrayanDSO** [comment]
Will be solved with #14303
