### ISSUE TITLE
[BUG]: Adding a large card deck slows down to the point of effectively freezing

### ISSUE THREAD

**Issue by tomaszgarbus** [ankidroid/Anki-Android#13855]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Buy a OnePlus 6 with Android 11.
2. Install AnkiDroid.
3. Download either of these 2 decks: https://ankiweb.net/shared/info/257529691, https://ankiweb.net/shared/info/893324022.
4. Open it with the AnkiDroid app and confirm that you want to add it.
5. Observe the progress.

### Expected behaviour

Importing of the deck will take a long time, but the progress will be uniform and the importing will eventually complete.

### Actual behaviour

Importing gradually slows down. It takes a few seconds to go from 1% to 2%, tens of seconds to go from 10% to 11%, many minutes to go from 40% to 41% and then forever from 60% to 61%. I left the phone for the entire night to complete the import and by morning the app had crashed or restarted and the deck was not imported.

### Debug info

```text
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; ONEPLUS A6003 Build/RKQ1.201217.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.135 Mobile Safari/537.36

ACRA UUID = 9e00fbc0-6be3-40a3-ba1a-f471492694ec

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by tomaszgarbus** [comment]
Hi Mike, thanks for the quick reply!

I have updated the debug info.

> This should be fixed in 2.16 releases

Ah, that's great to hear! Closing the bug then.

**Comment by tomaszgarbus** [comment]
Out of curiosity: would you mind sharing how it was resolved? (a link to a bug/commit etc.) I'm trying to get into AnkiDroid's codebase and I'd love to read up more on this.

**Comment by mikehardy** [comment]
Sorry for the ridiculously long delay - essentially it is solved by using native code (written in rust) to do the import vs the older Java code which used memory quite poorly. It *would* be possible to get a Java implementation working well but we are migrating more and more to using shared rust code that underpins the Anki Desktop application at the same time, so we benefit from more shared work

So, if you use the new 2.16 versions and enable the "new backend" you get access to lots of new rust implementations for the same old features, and many of them are more performant

The code calling organization diagram for this would be something like "the java implementation of screens and stuff here" --> "an adapter layer to the Rust backend built from the Anki-Android-Backend repo sister project" --> "the rust Anki library built from ankitects/anki repo"

Hope this helps :-)
