### ISSUE TITLE
Button disappear on deck picker

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13866]
Running on 3fe7c1a2b3c7ed88747f82d2eac425fe252b5198

Arthur, [16.05.23 14:30]
AnkiDroid Version = 2.16.0beta2-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = samsung

Model = SM-A226B

Hardware = mt6833

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A226B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.76 Mobile Safari/537.36

ACRA UUID = cb4eb2c2-a66e-42bd-8cf1-90bcf6866f06

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

![Screenshot_20230516_043313_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/357361/5ec9eb90-1b46-40be-bb74-9d51d8109192)

No idea how it occurred. I just opened the app, and then it was

**Comment by SanjaySargam** [comment]
Is it still happening ?
Can you share debug info
