### ISSUE TITLE
Add feedback on tap on about button

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13873]
How to reproduce:
* Open the settings
* open About
* Tap "Copy debug info"

Expected result:
* the link text reacts. Either change of stroke color or background color; as any button on the web 

Actual result:
* no feedback that the UI registered the press of the button

Same problem with the other buttons of this page by the way. But this one is particularly important because it takes more than a second before the snackbar confirms the info are copied.

**Comment by RobozinhoD** [comment]
Working on it
