### ISSUE TITLE
Add IPA "keyboard language" as an option when setting keyboard language hints on fields in note types

### ISSUE THREAD

**Issue by EddieAS07** [ankidroid/Anki-Android#13883]
**Is your feature request related to a problem? Please describe.**
I use the IPA (International Phonetic Alphabet) keyboard from GBoard (Google Keyboard) to answer Type In fields for my custom "IPA Sounds" note type. With AnkiDroid 2.16's keyboard language hints applying to reviewing cards and not just editing them, I hoped to be able to set  IPA as a keyboard language hint for the "Sound" field of my note type; however, it does not show up as a possible keyboard language type (probably because it was not considered a language).

**Describe the solution you'd like**
I would like IPA included in the list of languages which you can set a language hint for when accessing the options of a field in a note type and selecting "Set keyboard language hint."

**Describe alternatives you've considered**
Changing manually to the IPA keyboard on GBoard makes reviewing flashcards take longer because I have to switch between IPA and English (U. S.) for filling in the "Sound" field (e. g. pʰ) and "Features" field (e. g. voiceless aspirated bilabial plosive) of my note type, respectively. Alternatively (although not immediately relevant to my issue), being able to set custom keyboard language hint text in case AnkiDroid does not have a particular keyboard language type works better as a long-term solution to this issue, rather than adding new keyboard languages manually.

**Additional context**
I don't see any particular reason for IPA to be excluded from the list of languages to choose from despite not being a language; adding it won't ruin the purpose of the feature and it does more harm to exclude it than include it. Also, I don't think the alternative feature I suggested would take long, although I don't know much about how dialog boxes are created in the code and any issues or bugs this would create. I also don't know if selecting IPA for a keyboard provider that doesn't support it would be problematic and cause errors or bugs.

Here is an example of the IPA keyboard and it not being included on the list of languages:
![Screenshot_20230517-073419_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/66839475/31a5aafb-80b6-4156-9ec7-ad075ddfdcb2)

**Comment by david-allison** [comment]
Thanks for the report! Oversight on my behalf

**Comment by lukstbit** [comment]
@EddieAS07 I've manually added IPA in the list of languages for hints(look for IPA Phonetics). It will be available in the next beta, give it a go and see if it works.
