### ISSUE TITLE
App hangs up when importing

### ISSUE THREAD

**Issue by E0697** [ankidroid/Anki-Android#13880]
###### Reproduction Steps

1. Import a deck.
2. Change focus from app (turn off screen or switch to another app)
3. App hangs up

###### Expected Result

Importing should continue normally

###### Actual Result

App hangs up, importing prpgress will be lost as you have to kill the app

###### Debug info

AnkiDroid Version = 2.16.0beta2

Android Version = 12

ProductFlavor = full

Manufacturer = realme

Model = RMX2170

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; RMX2170 Build/SKQ1.210216.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.76 Mobile Safari/537.36

ACRA UUID = 2faedfa9-8c35-433f-be34-c02a5473aea9

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by E0697** [comment]
I've noticed it happens in other cases too. I just tried checking the media and it happened. I waited for some time and got a nptification that it finished, but the app crashed (reported) when I returned.

**Comment by lukstbit** [comment]
During the import, after sending the app to the background and then back to foreground, `DeckPicker` seems to hang at `InitialActivity.getStartupFailureType()` -> `CollectionHelper.instance.getColSafe()` and further down the line at `CollectionManager.blockForQueue()`.

**Comment by E0697** [comment]
I've just tried to import a small deck, it seems to get stuck (app not responding message), unlike the scan media and database options; which continue to run but fail to update the progress.

**Comment by dae** [comment]
If it still happens when a 2.17 (alpha) release happens, please let us know.

**Comment by E0697** [comment]
I just tried importing a collection in 2.17alpha01 and it still hangs up.

**Comment by lukstbit** [comment]
@E0697 This doesn't seem to happen with the latest changes we have. Once 2.17.alpha2 is released please see if the app still hangs.

**Comment by E0697** [comment]
Everything seems good so far with 2.17alpha2. Thank you!
