### ISSUE TITLE
Deck duplicating with a + sign

### ISSUE THREAD

**Issue by aguadamuz1982** [ankidroid/Anki-Android#13909]
I recently downloaded a new deck for study. Two days ago I finished one deck and noticed that it said congratulations...etc. and the deck was 0/0. Underneath that deck a new one appeared with same title with a + and the number of questions unanswered. The rest of the whole section of decks duplicated just the same but I didn't start the other ones. The only thing I did is that I edited some cards... Like spaces between answers or spelling, nothing else. I didn't add notes or anything. My version on iPad, iPhone and Mac is 2.0.92. 
I erased all the deck of that section and started again. By the way the other deck from the same source, downloaded previously didn't have this problem.

**Comment by lukstbit** [comment]
Hey, judging by your mention of iphone/mac version this sounds like an issue with AnkiMobile for which you can see how to get support [at this link](https://docs.ankimobile.net/support.html).

This is the code repository for AnkiDroid the mobile app for Android. If this is an AnkiDroid issue then leave a comment to reopen this and please provide the debug information.
