### ISSUE TITLE
Request for MCQ Feature: Adding Multiple-Choice Question Options

### ISSUE THREAD

**Issue by AnantMishra01** [ankidroid/Anki-Android#13904]
**Is your feature request related to a problem? Please describe.**
I often create flashcards using Ankidroid for studying various subjects, but I find it limiting when it comes to creating questions with multiple-choice options. Currently, Ankidroid only supports basic text-based question and answer pairs. This limitation hinders my ability to create comprehensive and interactive flashcards for effective learning.

**Describe the solution you'd like**
I would like to request the addition of a feature that allows the inclusion of multiple-choice question (MCQ) options in Ankidroid. The proposed solution entails modifying the flashcard creation interface to accommodate the question prompt, answer options, and the ability to mark one option as the correct answer. Additionally, the reviewing interface should display the MCQ options, allowing users to select the correct answer during the review process.

**Describe alternatives you've considered**
As an alternative, I have tried creating separate flashcards for each possible answer choice, but this approach quickly becomes cumbersome and inefficient, especially for complex topics with multiple options. Incorporating an MCQ feature would streamline the flashcard creation process and provide a more intuitive and efficient way to study with multiple-choice questions.

**Additional context**
I would like to emphasize my willingness to contribute to the development of this feature if needed. I have experience in software development and would be happy to assist with testing, providing feedback, or even contributing code if given the opportunity. I believe this feature would greatly benefit Ankidroid users and enhance the overall learning experience.

Please note that I am open to any suggestions or modifications to the proposed solution. Thank you for considering my feature request, and I look forward to contributing to the development of Ankidroid's MCQ feature if given the chance.

**Comment by user1823** [comment]
It is not recommended to use MCQs for studying. Read here: https://faqs.ankiweb.net/multiple-choice-questions.html

Having said that, if you really want to create MCQs, you can write the question and the options in the Front field and the correct answer in the Back field.

Obviously, this is not interactive but it serves the purpose. Also, I think that it is possible to create interactive MCQs by using some JavaScript.

**Comment by BrayanDSO** [comment]
user1823 is correct, MCQ aren't good for active recall and spaced repetition. And if you really want those you can always create a note type that supports it (or search the internet. Someone probably already built one)
