### ISSUE TITLE
Feature request: Add cropping mode to background image

### ISSUE THREAD

**Issue by Stillmatic27** [ankidroid/Anki-Android#13907]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Go to settings > appearance > Background - select image > select any image. Go to decks, rotate the phone, image will appear distorted.

### Expected behaviour

Image should be cropped according to screen size and orientation 

### Actual behaviour

Image appears distorted

### Debug info

```text
AnkiDroid Version = 2.16.0beta2

Android Version = 13

ProductFlavor = full

Manufacturer = samsung

Model = SM-G781B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G781B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.131 Mobile Safari/537.36

ACRA UUID = 3117771b-4f06-4ab6-9bcf-2bdaa342ff77

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
It is a crop X distort issue. I think that both behaviors are reasonable and would be nice to have the option to select which one to use. Up to someone that wants to implement the cropping feature
