### ISSUE TITLE
Feature request : Upon selecting the note type, initiate immediate dialog

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#13914]
**Is your feature request related to a problem? Please describe.**
While adding note type `from manage note types`, I am supposed to choose the `note type`, and after choosing I again needs to press the `Ok` button and then it opens new dialog for naming the note type
It is obvious that if I chose `note type` I meant to add note type. 

**Describe the solution you'd like**
1.After choosing `note type` ,  immediately open new dialog for naming the note type instead of after pressing `Ok` button
2.Remove positive button from dialog

**Describe alternatives you've considered**

**Additional context**

https://github.com/ankidroid/Anki-Android/assets/65113071/84cb6ab8-682f-4b42-a154-dbb52ba4b6f0

**Comment by SanjaySargam** [comment]
If it is accepted then I'd like to implement

**Comment by BrayanDSO** [comment]
Good idea IMO
