### ISSUE TITLE
The title of ”Collection exported successfully” in the middle of exporting process is misleading

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#13920]
**Is your feature request related to a problem? Please describe.**
After selecting "OK" to the confirmation dialogs about whether to export or not, the dialog with its title,`Collection exported successfully`, is shown. 
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/e2ae9dd6-3c9e-443e-8d92-40d7bd53ba1d" width="480px">

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/56ac6f5b-e195-4f69-938a-1040374689b6" width="320px">

The title may possibly give end-users a false impression _that_ the exported file has already be saved somewhere like `AnkiDroid/Backup` directory _and that_ the choices in the dialog are mere additional options (because, at least for common end-users,  an export process is _not_ up to the phase of outputting a temporary file _but_ up to the phase of saving (or sharing) an exported file somewhere, I think.)

However, if users get the impression above and cancel the dialog, they actually lose the "successfully exported" file.

So, the title seems to be a bit misleading, and the combination of the title and the message seems to be a bit confusing to end-users, in my opinion. (Personally, I was puzzled for a long time.) 

**Describe the solution you'd like**
Replace the title, that is, `Collection exported successfully`, with another one, for example, `Where to export?`, which implies that the exporting is not yet complete.  
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/ab7c7318-4a88-4761-91e4-0f47c4624a0e" width="320px">

**Describe alternatives you've considered**
Replace the title with another one, for example, `Now ready to export`, or just `Export` again.

**Additional context**
- The solution above will resolve #12713
- The counterpart dialogs of Anki Desktop are as follows.
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/c4bb81c3-964a-458f-8e62-940d9f1dfe28" width="600px">
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/8f0f0d33-5746-43ca-8b0d-b208d011d286" width="600px">

**Comment by snowtimeglass** [comment]
If the solution is accepted, I'd like to work on it.

**Comment by oakkitten** [comment]
I like “Ready to export” or maybe “Export ready”. Also I'd ditch the text, leaving only the buttons like this:

    Export ready
      Save to disk
      Share
      Cancel

But yeah “Collection exported successfully” is not acceptable

**Comment by BrayanDSO** [comment]
> Also I'd ditch the text, leaving only the buttons like this:

Nice idea

**Comment by snowtimeglass** [comment]
Thank you for the feedbacks and the idea.

The `Export ready` looks good to me, too. (That said, this preference of mine is not based on knowledge of English grammar and usage, so I would like to know opinions of native speakers, though.)

Also, ditching the text may be good idea in terms of simplification.


On the other hand, I don't think the `Save to disk` (or `Save to device`) is a very good label for that button, since selecting the button even allows users to save the exported file to Google Drive cloud storage (perhaps it may be a more popular destination than an internal directory of user's devices). 
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/9a79925f-0041-480f-a2e0-14b780a5e208" width="320px"><img src="https://github.com/ankidroid/Anki-Android/assets/10436072/6201a90f-a1af-436d-916b-f15dba02b75c" width="200px">


So, either `Save to directory` or `Save to folder` or just `Save` may be better?

**Comment by lukstbit** [comment]
@snowtimeglass I assigned you to this issue.

I'm indifferent to the name of the dialog, in favor of removing the extra dialog message but I would say that the current strings for the two options should remain.

**Comment by oakkitten** [comment]
> So, either Save to directory or Save to folder or just Save may be better?

“Save” is also fine but usually it means overwriting the already existing copy. In Windows the idiom would be “Save as...”, “...” indicating that the action will be not immediate complete. It seems that this convention does not exist on Android, I looked around and Simple mobile tools Gallery says “Save as” and Files says “Move to” and “Copy to”. So maybe “Save as” or “Save to” would be better.

> I would say that the current strings for the two options should remain.

Why?

**Comment by lukstbit** [comment]
> Why?

Because it reads quite well with the new title:

_Export ready, select where to save file
Export ready, select application for sharing_

_Save to disk_ is not precise as the user can save the file outside the phone(in fact many would do this as a backup), _Save_, I think, introduces a small ambiguity for the user: does it save directly and I have to look for the saved file or does it allow me to choose _where to save_.
I would also want to avoid having to force two new translations.

**Comment by snowtimeglass** [comment]
Thank you for the assignment and the opinions.

"Save to" looks good to me as a possible new label. I appreciate the apps research.

Weighing "merit (simplification)" against "demerit (new string's cost and a bit ambiguity)", …umm, I'm at a loss.

**Comment by oakkitten** [comment]
> Because it reads quite well with the new title

I'd say “select” is a bit weird here (why not “choose”), and “select application for sharing” could be a little misleading because it could be opening the application selector instead of the share dialog (and you can share to a contact or whatever). This is really nitpicking because even if confusing, it should be clear for the user what they want to tap—the options are so limited. But I'd still go for the conventional way because an interface that makes users use their brain even a little is usually worse than one that doesn't

**Comment by snowtimeglass** [comment]
>But I'd still go for the conventional way

Sorry, let me confirm your conclusion just to be sure. The "conventional way" means `select where to save file` and `select application for sharing`, and you are in favor of keeping these labels for now, ―right? (or not right at all?)

**Comment by oakkitten** [comment]
By conventional I mean what other apps commonly use, which would be simply “Share” and “Save to”/“Save as”

**Comment by snowtimeglass** [comment]
Ah, sorry for my misreading. I reread and understand it correctly as you explain. Thank you. 

I agree to your opinion. Plus, their translation cost (translators' burden) would be relatively less heavy in my opinion, because the strings are commonly used in apps, as you say.

**Comment by snowtimeglass** [comment]
@lukstbit Simplification and standardization of these strings of the choices looks not-bad idea for me. Do you mind if I incorporate these changes into my PR for this issue?

**Comment by lukstbit** [comment]
@snowtimeglass Go ahead.

**Comment by snowtimeglass** [comment]
@lukstbit Thank you!

**Comment by snowtimeglass** [comment]
The second style below would be better?
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/e2a518b2-f7b5-49f0-b544-ac65deed748e)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/8cd0ea69-7d2e-4200-894d-1d494a26841b)
The second is in the same style as the "Help", "Support", and "Import" dialogs.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/1d4c7a53-959c-46eb-bffe-93a2eddc0190" width="320px">

(The second dialog image above is a mere mock-up. It actually is the "Import" dialog in which its strings and icons are replaced with those for "Export ready". I have not yet succeeded in showing the menu with icons in the actual "Export ready" dialog.)

**Comment by oakkitten** [comment]
Can we simply use an `AlertDialog` with regular buttons?

**Comment by lukstbit** [comment]
No icons.
The import dialog uses the dialog related code for Help/Support dialogs and it's force to have icons, but it should be simplified and the icons  be removed.

**Comment by snowtimeglass** [comment]
Thank you for the feedbacks. 

>Can we simply use an AlertDialog with regular buttons?

>No icons.

Then, I'll try in that direction.

Do you mean this kind of layout (without description text)? Or the buttons are lined up vertically as in the previous comment?
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/5ee1eca4-a5dd-424a-9d22-c6e700f2ee51)

**Comment by oakkitten** [comment]
The buttons will align themselves vertically automatically if they require more space. Not sure if you can force the alignment.

P.S. I hope that in near future we move to [bottom sheet dialogs](https://m2.material.io/develop/android/components/bottom-sheet-dialog-fragment) where we can have more flexibility

**Comment by snowtimeglass** [comment]
I understand. Thank you.

Bottom sheet dialogs looks attractive. I look forward to the move to them.

**Comment by snowtimeglass** [comment]
The second style below would be better?
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/d544a6a0-15e8-4941-b9b1-c30362e06a1f)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/1aa08933-e7e6-4575-babf-0985143f3283)

The cancel button might be less necessary in this situation. I think so because of the following reasons.

- The will to export has already been confirmed once on the previous dialog.
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/086e9c30-4bfd-4c42-a63f-7fb3b2c02c31" width="320px">
- This "Export ready" dialog is _in effect_ not so much "_alert_ dialog" as "simple dialog" compared to the dialogs for deleting or overwriting data. This "Export ready" dialog just leads to one of the almost risk-free operations, like the simple dialog below.
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/f2397ba6-8960-49e0-8a44-5304a6833d96" width="320px">
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/7c1a112f-909f-4e2d-8d11-955a25fe2dbd)
     https://m2.material.io/components/dialogs#simple-dialog

- Users can cancel easily by their back operation or tapping anywhere outside the dialog.
- This "Export ready" dialog is not for the final decision. Users can cancel on the next screen (for selecting a location to save or an application to share).
- Two actions on a dialog is simpler than (deprecated) three actions.

So, there is less need to show the "Cancel" button on this dialog?

**Comment by oakkitten** [comment]
Ditching Cancel sounds good to me.

Also we can switch to alert dialog while we are at it maybe?

**Comment by snowtimeglass** [comment]
>Ditching Cancel sounds good to me.

Thank you.

>Also we can switch to alert dialog while we are at it maybe?

Sorry, I still can't get what you mean. Could you please rephrase that? (You are suggesting using `AlertDialog` instead of `MaterialDialg`?)

**Comment by oakkitten** [comment]
Yes, see #13315 for reasoning

**Comment by snowtimeglass** [comment]
Thank you for the guidance. I understand the direction.
