### ISSUE TITLE
[BUG]: Add item tint getting black 

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#13921]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to Reviewer
2. Set a card to any flag color
3. And then Go to CardBrowser

### Expected behaviour

Add `+` item tint color is in white

**Without Flag**

https://github.com/ankidroid/Anki-Android/assets/65113071/8e691493-92b6-43c5-a41d-808ccc28eb42

### Actual behaviour

Add `+` item tint color is in black

**With Flag**

https://github.com/ankidroid/Anki-Android/assets/65113071/2826e380-cf3c-4042-978f-a1768de677da

### Debug info

```text
AnkiDroid Version = 2.16.0beta2-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.131 Mobile Safari/537.36

ACRA UUID = d71c7dc4-d57e-410d-bf00-d42e216a26d6

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

It's not always reproducible 
Sometimes it's occurs or maybe not

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
> It's not always reproducible
> Sometimes it's occurs or maybe not

Finally found actual reproduction steps 

1.  Go to Reviewer
2. Set a card to any flag color
3. Go to CardBrowser

**Comment by Arthur-Milchior** [comment]
the bug only appear in "add card" is not an option in the reviewer.
If you put it as an option, either in the top menu, or in the overflow (hamburger) menu, the plus symbol remains white when you open the card browser. Which makes little sens to me, because the plus sign in is block in the overflow menu, and should not have tint when it's not available.
