### ISSUE TITLE
[BUG]: (add-note-widget) "Deck for new cards" does not select last used deck

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#13931]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Set to "Decide by note type"
2. Press Add note widget
3. Select note type (say, English)
4. Select deck (say, English, too)
5. Add note
6. Close AnkiDroid and swipe it away from the recent app list
7. Press Add note widget

### Expected behaviour

On adding new notes of type English, the deck English should be remembered:

> The other option, "Decide by note type," saves the last-used deck for each note type

### Actual behaviour

Another deck is chosen. In my case, it's always Default.
For a different note type (say, A), it always chooses deck B, although all the cards of type A are in deck called A.

### Debug info

```text
AnkiDroid Version = 2.16.0beta2

Android Version = 13

ProductFlavor = full

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; ONEPLUS A6003 Build/TQ2A.230305.008.C1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/112.0.5615.48 Mobile Safari/537.36

ACRA UUID = d955bcd1-fd00-4663-a668-76961b1f8863

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Related to https://github.com/ankidroid/Anki-Android/pull/9617?

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
working on it

**Comment by homocomputeris** [comment]
https://github.com/ankidroid/Anki-Android/assets/7422433/57be5a6b-2445-4069-b8b5-f5fb24855af0

**Comment by SanjaySargam** [comment]
https://github.com/ankidroid/Anki-Android/assets/65113071/c2ea9f1e-8cf1-43a3-ad83-7baf99b76305
Not reproducible!!

**Comment by homocomputeris** [comment]
[Srpski.apkg.zip](https://github.com/ankidroid/Anki-Android/files/11692711/Srpski.apkg.zip)

Here is the deck. Every time I try to add a note to this deck, Default deck is chosen instead.

**Comment by SanjaySargam** [comment]
https://github.com/ankidroid/Anki-Android/assets/65113071/d2275408-10e0-4197-9266-18581b3237c5

**Comment by homocomputeris** [comment]
The issue persists even after creating a new deck (to check whether the `did` issue affecs anything) and moving cards there

AnkiDroid Version = 2.16.0beta4

Android Version = 13

ProductFlavor = play

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; ONEPLUS A6003 Build/TQ2A.230505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.58 Mobile Safari/537.36

ACRA UUID = d955bcd1-fd00-4663-a668-76961b1f8863

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by dae** [comment]
Please let us know if the issue still exists after a 2.17 alpha is released.

**Comment by homocomputeris** [comment]
Still an issue

AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A346B

Hardware = mt6877

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-A346B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.105 Mobile Safari/537.36

ACRA UUID = d1aff59f-1f26-411d-b2e3-c282a25cadf2

Crash Reports Enabled = true

**Comment by homocomputeris** [comment]
Moveover, in 2.17.6, AnkiDroid sometimes does _show_ the latest deck used, but it _adds_ cards to the default deck.

**Comment by david-allison** [comment]
> Moveover, in 2.17.6, AnkiDroid sometimes does _show_ the latest deck used, but it _adds_ cards to the default deck.

To confirm, this isn't due to the 'Deck override' setting on the card template?

**Comment by homocomputeris** [comment]
> To confirm, this isn't due to the 'Deck override' setting on the card template?

I've never used this feature. It took me a while to find it, and these fields are in all templates are empty.

**Comment by homocomputeris** [comment]
Also, I've never seen this bug in Anki Desktop, so if there is any shared code, the bug is probably not there.

**Comment by homocomputeris** [comment]
Still an issue in 2.18.

**Comment by david-allison** [comment]
Thanks for the bump, I'll add this to my 2.18.X collection.

I'm not going to be very active this week, please ping this weekend if this still isn't resolved

**Comment by homocomputeris** [comment]
Thanks! Please tell me if you need any specific test, screenshots or whatever.
