### ISSUE TITLE
The update localization script doesn't properly handle empty strings

### ISSUE THREAD

**Issue by lukstbit** [ankidroid/Anki-Android#13946]
The script(update-localizations.py) we use seems to not take in consideration an empty string and results in a `<string></string>` entry in `values-xx` folders and a warning in the IDE.

_Originally posted by @lukstbit in https://github.com/ankidroid/Anki-Android/pull/13943#pullrequestreview-1460965355_

**Comment by dae** [comment]
@lukstbit do you have the bandwidth to fix this?

**Comment by lukstbit** [comment]
Not really. We should keep this open and wait first for #8274 and see if that also fixes this issues. 
It's very very low priority.

**Comment by lukstbit** [comment]
We have a new implementation for syncing translations which hopefully handles this.
