### ISSUE TITLE
_writeDstMedia should let caller know write fails

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13949]
_writeDstMedia silently capture IOExceptions that are not "no space left".

https://github.com/ankidroid/Anki-Android/blob/043ded78761fea83a0614206eb987eb891799b9d/AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.kt#L724-L741

This is clearly not acceptable, it means media may fail to be imported, and the user is not even warned.
It is absolutely not clear to me what is the behavior we want. Personally, I believe that the exception should be rethrown, and the callers should catch it, create the list of files that were not copied, and in the end, let the user know the list of files that failed (if any). But that's up to discussion.

**Comment by BrayanDSO** [comment]
Do you know if this will be kept after the new backend is the default?

**Comment by Arthur-Milchior** [comment]
As you can see in https://github.com/ankitects/anki/blob/1aaf6dbf18ba444996dc2ff81f4371ec0c3efe39/pylib/anki/importing/anki2.py#L430 it's still in Python upstream. So I highly doubt it'll be quickly available in rust. I suspect one day it will be,

**Comment by dae** [comment]
Actually, apkg importing has already been ported to Rust, and is already used by AnkiDroid when the new backend is enabled. The legacy Python importing code still exists in the computer version because some add-ons depend on it, and it requires the add-on force the old import path, or the user enable the legacy setting in the preferences.

**Comment by BrayanDSO** [comment]
Okay, so we will eventually be able to ditch the method, so I vote to not spend time with it. 

Up to you @Arthur-Milchior if the issue should be closed or not

**Comment by Arthur-Milchior** [comment]
ok, my bad. Then yeah, let's close it
