### ISSUE TITLE
Create lint error if a class has a member of type Collection

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13942]
In order to ensure that we don't leak the collection object inadvertently, and reduce the number of crash related to closed collection, I suggest we had a linter to help us. 

What I would like as a first step is to have an error if a class has a member that is either  Collection, a Deck manager, a Model Manager or a Base Scheduler or a descendant of any of those. The exception being those very classes, that are allowed to keep references to each other. This linter should not apply in test, in test it's okay to have reference to those classes.

The rationale here is that, in order to ensure that a Collection is only used inside a `withCol`, we need to be certain to never keep a reference to a collection object. For the sake of practicality, we prefer to keep the collection as a state of the Deck manager, model manager and scheduler. To be safe, we thus require that no other class keep a reference to a deck manager, model manager or scheduler.

In practice, if you implement it sucessfuly, current code would fail the linter. However, PRs such as #13941 are trying to improve the state of the code. The idea is to ensure that we never write similar code again.

Ideally, the code should also detect any parametric type that has an argument which is Collection Related. Such as List<Collection> or Pair<Long, BaseManager>. In practice, it's not a huge deal if it is not the case, as I can't imagine we'll want a list of Collection object. And it may be hard, because I still want to allow function of the type `(Collection, T) -> U`. 

In a second time, it'd be nice to figure out how to forbid function to return a Collection Related object, and to assign it to variables that are outside the scope of `withCol`; but I can't even imagine how to do it properly, except with Code Colouring, which seems overkill.

**Comment by dae** [comment]
@Arthur-Milchior not against this, but might be easier to audit the existing code instead?

**Comment by david-allison** [comment]
I'd prefer to audit the code: `getColUnsafe` + warnings on using `col` in the main thread are slowly moving us to a better situation. 

We don't have enough dev capacity for this, and this would take time away from code which is moving the architecture/app forward
