### ISSUE TITLE
Add reset to default in AccessibilitySetting Screen

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#13957]
**Is your feature request related to a problem? Please describe.**
It's better to add `reset to default` button as we have in `App bar buttons` so that we can set values to default

**Describe the solution you'd like**
Add reset to default button

**Describe alternatives you've considered**
Nothing

**Additional context**
![WhatsApp Image 2023-06-06 at 9 11 19 AM](https://github.com/ankidroid/Anki-Android/assets/65113071/ccab388a-bb01-4d41-93f8-6d96976f33eb)

**Comment by BrayanDSO** [comment]
I’d rather not. This screen is quite simple and having a “Reset to default” button on every settings screen isn’t common on Android apps. Particularly, I think that we should strive for having less settings so things are simpler, not more. Besides, I haven’t seen people complaining about that.

**Comment by lukstbit** [comment]
@BrayanDSO Fair points and I agree. Looking at it again, I'm realizing that the users that would use/change those preferences are the users which unfortunately will probably not reset them to defaults anyway.

I'm closing this and the associated PR as _not planned_.

@SanjaySargam If you create an issue wait for some feedback, but feel free to add a comment that you plan to work on it if accepted. Then you'll be the one assigned to/considered for the issue.
