### ISSUE TITLE
Disabling "automatic display answer" should disable "keep screen on"

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#13951]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to Settings
2. Go to ReviewingSettings
3. Enable `automatic display answer`
4.  And then disable `automatic display answer`

### Expected behaviour

`keep screen on` must be disable while disabling `automatic show answer`

### Actual behaviour

`keep screen on` is not disabled while disabling `automatic show answer`

### Debug info

```text
AnkiDroid Version = 2.16.0beta2-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_x86_64 Build/TE1A.220922.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = cabb428e-f642-40b5-8cc5-4ec1b52f6ea9

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
The user may want to keep `Keep screen on` enabled and disable `Automatic display answer` only. So the "Expected behavior" you described isn't expected at all.

**Comment by SanjaySargam** [comment]
> The user may want to keep `Keep screen on` enabled and disable `Automatic display answer` only. So the "Expected behavior" you described may not be expected at all

The user still can enable `keep screen on` by clicking on it.

The reason why I expect this behavior is 

If user enabled `automatic display answer` then it enables `keep screen on`. It means that user didn't manually enable `keep screen on` . And when user disables `automatic display answer` the `keep screen on` still enabled but the user does not want at all coz the user didn't enabled manually.

**Comment by BrayanDSO** [comment]
Maybe those two settings should be isolated from each other. So, if `Automatic display answer` is enabled, the screen should be kept on independently of the `Keep screen on` preference value, and the `Keep screen on` preference value should not be changeable (i.e. isEnabled = false) while `Automatic display answer` is enabled

**Comment by SanjaySargam** [comment]
> Maybe those two settings should be isolated from each other. So, if `Automatic display answer` is enabled, the screen should be kept on independently of the `Keep screen on` preference value, and the `Keep screen on` preference value should not be changeable (i.e. isEnabled = false) while `Automatic display answer` is enabled

Made changes in PR
