### ISSUE TITLE
Add Forgetting curve

### ISSUE THREAD

**Issue by Pantyhose-X** [ankidroid/Anki-Android#13962]
**Is your feature request related to a problem? Please describe.**
Review what you've learned, and review it in a scientific way to deepen your memory

**Describe the solution you'd like**
Learned content, add forgetting curve statistics, remind users to review when time is up
**Additional context**
https://en.wikipedia.org/wiki/Forgetting_curve

**Comment by BrayanDSO** [comment]
Hi there. Could you be more descriptive about what you want to be implemented?

**Comment by Pantyhose-X** [comment]
> Hi there. Could you be more descriptive about what you want to be implemented?

(learned flashcard group, increase time memory) the alarm clock will remind users to review according to the [forgetting curve](https://en.wikipedia.org/wiki/Forgetting_curve)
