### ISSUE TITLE
Permit direct sync to local server/desktop

### ISSUE THREAD

**Issue by Mr-Dave** [ankidroid/Anki-Android#13978]
**Is your feature request related to a problem? Please describe.**
The current sync option requires https but that is only possible if the server is available via the internet has all the certificates, set up and infra-structure.  

**Describe the solution you'd like**
The current Anki desktop app (in Linux) includes the feature to run a sync server via the command line.  It would be good to allow users to work on the cards via the desktop app, save the deck, then start the sync server for a moment to sync with the android device and then stop the sync server.

This would improve the privacy of the users (not sharing data with Ankiweb or others), as well as improving the security of the desktop/server i.e. Do not have to expose the desktop/server to the internet in order to obtain a certificate for https and does not require the user to have a static IP.  

**Describe alternatives you've considered**
Reverse proxies and self signed certificates fail to function.  

**Additional context**
This is related to the requirement for https on the custom sync server.  The requirement makes sense for those using a server on the internet.  However the easiest and most straight forward use case of the custom sync server (sync directly to my desktop) is no longer functional.

**Comment by dae** [comment]
I believe this already works if you enable the new backend in the beta version.

**Comment by Mr-Dave** [comment]
Oh awesome!...tell me more...point me to instructions/documentation.  I spent days on trying to get this to work.

**Comment by dae** [comment]
https://github.com/ankidroid/Anki-Android/issues/13797

**Comment by Mr-Dave** [comment]
Thank you.  The feature is there and allows for the local server so I'll close this enhancement request.  

It may however have a bug somewhere in the process that I'll try to track down and if I can reproduce it, submit separately.  i.e.  Using 2.16beta2 after connecting and showing all the syncing progress there were not any decks and then it crashed with the submission of an automatic bug report.
