### ISSUE TITLE
[BUG]: note editor loses editing state in multi-window mode (Samsung Galaxy Fold 4)

### ISSUE THREAD

**Issue by richardjharris** [ankidroid/Anki-Android#13988]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Create a new note using the Share function of android (I used Aedict). This opens the note editor 

Make some changes 

Drag a new app onto the screen e.g. from the taskbar, or if already in multiwindow mode, remove an app.

Edited changes will be lost.

### Expected behaviour

Editing state should be retained, just like when rotating the screen

### Actual behaviour

Editing state is lost - card data resets to the initially shared data.

### Debug info

```text
AnkiDroid Version = 2.16.0beta2

Android Version = 13

ProductFlavor = full

Manufacturer = samsung

Model = SM-F936B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-F936B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.61 Safari/537.36

ACRA UUID = 0f05d6f1-bf8f-4fb5-a93f-46f9cec6573e

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Issue also present on the latest Play Store release.

Does not occur if "add new note" button is clicked directly from Android.

May be that Samsung is doing something unusual/stupid in its multi window implementation (I apologise if so). Happy to debug it.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Have you found this behavior or something similar on other screens (e.g. Card browser, Template editor) or without the share function usage? It should help delimiting and finding where the issue is.

**Comment by BrayanDSO** [comment]
Part of #12832. This is an issue in our part. With good activity/fragment state handling this should bs solved
