### ISSUE TITLE
`@UiThread` should not apply to whole AnkiActivity

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#13990]
This annotation indicates that everything in AnkiAcitivity and it's descendants should be on the UI Thread.
That means not only that all methods should be on the UI Thread, but that all members should only be accessed and set from the UI Thread.
Admittedly, setting members from two threads may theoretically be risky, but "race condition" is not the problem this annotation were trying to solve. And in any case, restricting access to a single thread is clearly a bad idea.

I want to note that "Wrong Thread" inspection already detect that `onCreate` should not have `col.save()`. But for som reason, not onStart, onStop, onPause, onResume, onDestroy. So I guess we should annotate them explicitelly.

The other solution would be to explicitly annotate each members and methods that are in Activities classes but can be used in WorikngThread or in both thread, I fear that it would add a lot of noises in the classes that contains the business logic

**Comment by dae** [comment]
> restricting access to a single thread is clearly a bad idea

I'm not sure I agree :-) UI code starts in the main thread, so withContext(Dispatchers.main) calls should rarely be required, and ergonomics don't suffer much. Something like the following:

```
fun someUiMethod() {
  val someId = this.id // fetch UI state; for collection objects that may be mutated by the UI, it would be safest to clone them first.
  this.someState = withCol { doSomeWork(someId) } // update UI state from background result
}
```

ensures that any parallel UI code that reads from someState is going to get a valid state object and not something that has been half-modified by a background thread. It doesn't solve all data races - the UI code may change this.id before this.someState is updated for example. But if the code is written in a way that a change to .id triggers a change to someState, then it shouldn't matter - someState will temporarily be stale, but it will still be internally consistent.

Can you offer some examples of where restricting to a single thread is a bad idea?

> But for som reason, not onStart, onStop, onPause, onResume, onDestroy. 

I tried adding col.db.execute("test") to DeckPicker's onStop, and it showed a warning for me. Can you provide a specific example?

**Comment by BrayanDSO** [comment]
Ideally activities should only display the views, not do any kind of background work, so yes, they should be in the UI thread
