### ISSUE TITLE
[BUG]: Automatically added long breaks in tables while there are no HTML breaks

### ISSUE THREAD

**Issue by Stillmatic27** [ankidroid/Anki-Android#13991]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Make a new card

Add this HTML table in extra section

`<div>Attitude has 3&nbsp;components: <i>Affective</i>, <i>behavioral</i>, and <i>cognitive</i></div>

  <title>Attitude Components</title>

  <table>
    <thead>
      <tr>
        <th>Component</th>
        <th>Description</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Affective</td>
        <td>Emotional aspect of attitude</td>
      </tr>
      <tr>
        <td>Behavioral</td>
        <td>Observable actions associated with attitude</td>
      </tr>
      <tr>
        <td>Cognitive</td>
        <td>Beliefs and thoughts linked to attitude</td>
      </tr>
    </tbody>
  </table>

<div>
</div><div><i></i></div><div>
</div><div><a href="https://www.khanacademy.org/test-prep/mcat/behavior/physiological-and-sociocultural-concepts-of-motivation-and-attitudes/v/components-of-attitude">Khan Academy Link</a></div>`

### Expected behaviour

While reviewing, table should come right below the text field

### Actual behaviour

Table is shown way below the text field
![Screenshot_20230612_034506_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/134497169/3c7d726b-ebb8-4e79-b942-09a4f1175873)

### Debug info

```text
AnkiDroid Version = 2.16.0beta2

Android Version = 13

ProductFlavor = full

Manufacturer = samsung

Model = SM-G781B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G781B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.60 Mobile Safari/537.36

ACRA UUID = 3117771b-4f06-4ab6-9bcf-2bdaa342ff77

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

This table displays normally on anki PC and ankimobile

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Go to settings > Advanced > Replace newlines with HTML and disable it, so the line breaks in your HTML snippet aren't replaced by HTML line breaks, i.e. `<br>` tags

**Comment by Stillmatic27** [comment]
Thank you! That fixed it! I don't remember turning it on, I guess it should be off by default?

**Comment by BrayanDSO** [comment]
> I guess it should be off by default?

Most people don't want to see HTML in their notes, so not having to use `<br>` to do a line break helps a lot

**Comment by Stillmatic27** [comment]
Ah makes sense.
I guess a new feature of seperate field for text and seperate field for HTML like that on the PC can help, should I ask for a feature request? Or is it not that important? I know you guys are giving your best, can't thank you enough!

**Comment by BrayanDSO** [comment]
It is important yes, we have the goal of implementing an editor like Anki's (#1377), but this is going to be a LOT of work and we are all volunteers and a bit short-handed, so it definetely it is going to take time

**Comment by Stillmatic27** [comment]
I wish I could help. I've always been and always will be a fan of you guys and open-source community in general. Thank you all for the amazing work you do!
