### ISSUE TITLE
[BUG]: AddNote button overrides on floatingAction button

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#14000]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to DeckPicker
2. Click FloatingAction Button

### Expected behaviour

AddNote doesn't overrides on floating action button

### Actual behaviour

AddNote button overrides on floatingAction button
![float](https://github.com/ankidroid/Anki-Android/assets/65113071/b705fb0d-83a1-4ec6-a89f-fbbf966aca78)

### Debug info

```text
AnkiDroid Version = 2.16.0beta2-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_x86_64 Build/TE1A.220922.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = b61a4a65-7010-4808-9429-e8052e131562

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
What do you mean by "overrides"? The FAB was changed in #12280

**Comment by SanjaySargam** [comment]
Ohh Sorry I don't know
Can I close this issue?

**Comment by SanjaySargam** [comment]
I mean `cancel` button is not visible as we have in previous version
![Screenshot_2023-06-14-12-49-58-78_a9eef3a2a561b80d5c76daebd0f9a14c.jpg](https://github.com/ankidroid/Anki-Android/assets/65113071/04f8315a-90c3-4c11-a95e-14dfd55bd33a)

**Comment by lukstbit** [comment]
Check the PR I linked to above, it was changed.

**Comment by nishadphule** [comment]
@SanjaySargam is this issue resolved??

**Comment by SanjaySargam** [comment]
@nishadphule Actually this is not a bug, it's a feature 
sorry

**Comment by SanjaySargam** [comment]
@lukstbit but there is some color difference between create deck, get shared decks vs add note icons
![IMG_20230615_092907.jpg](https://github.com/ankidroid/Anki-Android/assets/65113071/759a11c4-bf1f-4214-a220-9c12229e0763)

**Comment by lukstbit** [comment]
@SanjaySargam It's fine, the material design specifications seem to allow this.

**Comment by SanjaySargam** [comment]
Ok I am closing this issue
