### ISSUE TITLE
[BUG]: Discrepancies in classes applied to DOM elements between desktop and Ankidroid

### ISSUE THREAD

**Issue by tomelliot** [ankidroid/Anki-Android#14038]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Create a card on Anki Desktop.
Add a large image.
Add a style 
`img { 
max-width: 10vw;
max-height: 10vh;
}`
Sync to AnkiDroid.
View card.

### Expected behaviour

Image is max 10% of the view width and view height.

### Actual behaviour

Image is up to 100% of view width and 90% of view height.

### Debug info

```text
AnkiDroid Version = 2.15.6
Android = 13
```

### (Optional) Anything else you want to share?

Hi there,

I was struggling to get things matching between Ankidroid and Desktop. I had a look at both with the inspector and found that there were some differences in the classes that got applied.

The three examples I've found:
1. On Ankidroid, the id `content` wraps everything beneath the <body> tag and gets a 0.5em margin applied (#content is not present on desktop, and there's no additional 0.5em margin).
2. On Ankidroid, images get a `.chrome img` class with max-width and max-height. This selector is more specific than an `img` selector, so this overrides max-height and max-width set using the `img` selector in the user's css.
3. On Ankidroid, an `answer` class gets added beneath the div with id `content`. This is not present on Desktop (and if a user creates a class `answer`, this will be applied here).

<img width="359" alt="image" src="https://github.com/ankidroid/Anki-Android/assets/3267684/06d074d8-05df-4828-bff4-5b9172219b12">

<img width="358" alt="image" src="https://github.com/ankidroid/Anki-Android/assets/3267684/dea75f31-a58d-408a-9fa4-09bcdbbafdff">

Now I know where to look I can update these if I run into them again, but I thought I'd point it out as it's not the behaviour I expected. 

Is there somewhere users can go to see what differences to expect between desktop and mobile?

Thanks.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Hi there. Thanks for the report. Could you try seeing if this was solved in our latest beta (https://github.com/ankidroid/Anki-Android/releases)? Try it with the setting `Use the new backend` enabled (Settings > Advanced > Use the new backend (or search it))

**Comment by tomelliot** [comment]
I just tried with the beta and "Use the new backend" and it seemed to have the same issue. The margin was still present, and the images also had their sizing overrided.
![Screenshot_20230628-200240](https://github.com/ankidroid/Anki-Android/assets/3267684/676877de-d45c-4a73-a784-39ccdd633111)
![Screenshot_20230628-200253](https://github.com/ankidroid/Anki-Android/assets/3267684/70f994d3-ebf1-4b9f-b786-ebcb88410b3b)
![Screenshot_20230628-200300](https://github.com/ankidroid/Anki-Android/assets/3267684/575e2105-fb84-4751-897e-7e9e23f98468)
