### ISSUE TITLE
Add option to Redo Answer Card

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14030]
**Is your feature request related to a problem? Please describe.**
Sometimes, I accidentally click on the Undo button in the reviewer, which undoes the rating of the last card I reviewed.
This happens especially when I am editing a particular card during review because the location of the ✓ button of the edit note window coincides with the location of the undo button.

Because AnkiDroid doesn't have the Redo button, I have to rethink which answer button should be used for rating that card.

**Describe the solution you'd like**
This problem can be solved by adding a Redo option, just like Desktop Anki has.

**Describe alternatives you've considered**

**Additional context**

**Comment by SanjaySargam** [comment]
Really liked the feature request. I'd like to try to implement it

**Comment by NathanYearout** [comment]
I've been working a bit on implementing this feature and had some questions for other contributers. Would a redo button like this also stay active while the whiteboard is up to redo strokes? I believe that would make the most sense, but I want to see if anyone has any objections.

**Comment by dae** [comment]
So, as of #14171, general redo suport should be practical to implement. The whiteboard is another matter, and may need its own undo/redo buttons.

**Comment by RobozinhoD** [comment]
Im gonna do it
