### ISSUE TITLE
[BUG][Crash][2.16.0beta3]: Can't open "Deck options" in the default backend

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#14035]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Disable the new backend
2. Long press a deck on the deck picker screen
3. Tap "Deck options"

### Expected behaviour

The deck option screen get shown.

### Actual behaviour

Crash

### Debug info

```text
AnkiDroid Version = 2.16.0beta3

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.162 Mobile Safari/537.36

ACRA UUID = 5ba46727-9ddb-47f3-a810-53f66d97a89e

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

- Two users have reported the crash. Their Android versions are 10 and 12.
- This bug isn't reproduced in beta2.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
This was fixed in #14023.

**Comment by snowtimeglass** [comment]
Oops, I'm sorry. I couldn't search for it with the keyword of "deck options", and missed it. I should have checked more carefully. Thanks for letting me know.

**Comment by lukstbit** [comment]
There's no need to be sorry, I just didn't created an issue as I provided a fix immediately. Probably should have done it to not waste people's time.

**Comment by snowtimeglass** [comment]
Thank you for your kind words!
