### ISSUE TITLE
[BUG]: Translate icon tint is not in blue color

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#14040]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to NavigationDrawer
2. Click on Support AnkiDroid

### Expected behaviour

Translate icon tint is in blue color

### Actual behaviour

Translate icon tint is not in blue color
![WhatsApp Image 2023-06-27 at 2 45 24 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/95ff1af9-6e21-4b3b-9e00-bd79f9740293)

### Debug info

```text
AnkiDroid Version = 2.16.0beta4-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.130 Mobile Safari/537.36

ACRA UUID = 20b2dc80-f22d-4759-9817-396d281f95b3

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by adityabarodiya** [comment]
i want to work on this issue. please assign me.

**Comment by SanjaySargam** [comment]
> i want to work on this issue. please assign me.

Already made PR #14041
