### ISSUE TITLE
Themed Icon Support

### ISSUE THREAD

**Issue by JayXT** [ankidroid/Anki-Android#14049]
It would be great if Anki has received a support for Android 13 themed icons (on a home screen).
The details of this feature are described in Android documentation:
https://developer.android.com/about/versions/13/features#themed-app-icons

**Comment by JayXT** [comment]
Oh... I see. Currently, I'm on v2.15.6 from Google Play. The feature isn't critical, so I'll wait for the final release. BTW, when approximately it's going to be rolled out?

**Comment by mikehardy** [comment]
@JayXT in the workaround section are the various ways to access the beta until it releases 100%

https://github.com/ankidroid/Anki-Android/issues/13797
