### ISSUE TITLE
Images and audio don't sync on new phone

### ISSUE THREAD

**Issue by Faced69** [ankidroid/Anki-Android#14050]
I got a new phone and wanted to use anki on it but I can't because I always get an error (screenshot) and images and audio won't get played. My pc and my old phone syn perfectly well and I have no issues there. The images that are not getting displayed on my new phone are getting displayed on ankiweb so it has to have smth to do with my new phone but I don't know what. Could you guys please help me?
![Screenshot_20230628_201932_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/98234810/00232620-0dfb-4107-a305-c88b3750a476)

**Comment by mikehardy** [comment]
Hi there! You have not posted in the debug info, so I'm not sure exactly how to offer advice.
You may need to run check database.
You may need to uninstall / reinstall (if you are on 2.15 AnkiDroid, but not 2.16 AnkiDroid)

**Comment by Faced69** [comment]
I am sorry but I am not sure if I exactly know what you mean by 'not posted in the debug info'. I have the 2.15.6 version, isn't that the newest one you can get in the playstore? Also I tried running check database but it sadly changed nothing :(

**Comment by mikehardy** [comment]
Our issue template should have some instructions on how to get the debug info and post it in, however knowing the version helps.

2.15.6 is the current production version but it is quite old at this point, you might try getting the 2.16.0beta version which we're in the process of releasing now - it's just a couple of fixes away from being released to the general public. The workaround information here details a number of ways to get it: https://github.com/ankidroid/Anki-Android/issues/13797

**Comment by Faced69** [comment]
I have download the newest beta on my new phone but still no changes. Maybe it does have something to do with that I used Smart Switch to get the old things from my old phone to the new one? But I also did delete that version that got "copied' with Smart Switch and the decks in attempt to let it sync cleanly but that did also not work.

**Comment by Faced69** [comment]
Solved! Wiped anki from my phone completly and redownloaded the 2.16beta again, before starting anki gave it almost all permisions execpt: Camera, Microphone and read and write to the AnkiDroid database (I do not know if this one is needed bc it sounds important). After this it worked perfect.

**Comment by Faced69** [comment]
Closed.
