### ISSUE TITLE
[Bug] CrOS And11 arcvm cant type to login

### ISSUE THREAD

**Issue by ccchan234** [ankidroid/Anki-Android#14053]
###### Reproduction Steps

1. launch ankidroid in lenovo 2020 duet with android 11 arcvm
2. cant type, cant login
3. 

###### Expected Result

can type

###### Actual Result

type but nothing change

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by ccchan234** [comment]
hi, the play store’s 2.15.6 not working as said.
yeah the .apk from anki droid’s github seems working.
at least i can type account now.
solved i think, reported also on ankiweb forum

**Comment by mikehardy** [comment]
Thank you for trying the new beta version! I was just going to reply saying that should work for chromebooks.
We'll be in full / general release shortly
