### ISSUE TITLE
lint: Check formatters like `%1$D`

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14079]
Recently there was a crash at a translated string because of a uppercase `D` instead of `d` in the string format (I've already fixed the string in Crowdin)

```
java.util.UnknownFormatConversionException: Conversion = 'D'
	at java.util.Formatter$FormatSpecifier.conversion(Formatter.java:2787)
	at java.util.Formatter$FormatSpecifier.<init>(Formatter.java:2817)
	at java.util.Formatter$FormatSpecifierParser.<init>(Formatter.java:2630)
	at java.util.Formatter.parse(Formatter.java:2563)
	at java.util.Formatter.format(Formatter.java:2510)
	at java.util.Formatter.format(Formatter.java:2464)
	at java.lang.String.format(String.java:3603)
	at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.confirmAddCards(CardTemplateEditor.kt:38)
	at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment.access$confirmAddCards(CardTemplateEditor.kt:1)
	at com.ichi2.anki.CardTemplateEditor$CardTemplateFragment$setupMenu$1.onMenuItemSelected(CardTemplateEditor.kt:390)
```

The task here is to change [InvalidStringFormatDetector](https://github.com/ankidroid/Anki-Android/blob/a06e727f6094541b763e2dc18a300edb3e17fd26/lint-rules/src/main/java/com/ichi2/anki/lint/rules/InvalidStringFormatDetector.kt) to detect those cases

**Comment by dae** [comment]
One nice thing about the backend's translation system is that invalid replacements in translations will show an error for that string, but not cause a crash. AnkiDroid can potentially make use of this system in the future, though I'm not sure how practical it would be unless the backend compilation were made part Anki-Android,  as otherwise users would need to contribute the strings to the AnkiDroid-Backend first and then wait for a backend update.

**Comment by BrayanDSO** [comment]
I have no idea how much complex would be compiling only the strings, but I like the idea. Exporting them as Android string resources (in XMLs, as the app's strings) would be even better so we can preview them in layouts, other languages, etc.

---
As a note for anyone that wants to do this issue, this discussion is just a brainstorm about ideas for the future. The task of this issue remains the same

**Comment by dae** [comment]
Exporting the strings to a different format would mean you wouldn't benefit from the replacement handling Fluent has. But I'm not sure how practical using them would be - as mentioned above it would mean the Rust build would need to become part of AnkiDroid, and the translations wouldn't be accessible in XMLs/UI previews.

**Comment by ryank2001** [comment]
Hi, i would like to pick up this issue if that's still possible. It will be my first time working on any open source project.

**Comment by BrayanDSO** [comment]
Go for it, @ryank2001

**Comment by TusharBhatia34** [comment]
can i work on this issue as well?

**Comment by BrayanDSO** [comment]
Go for it, @TusharBhatia34

**Comment by realSharkbird** [comment]
Hello, I recently made a change for this issue. It is my first time contributing so I'm not sure if I did it correctly.
If anyone can take a look it would be much appreciated, thanks.
