### ISSUE TITLE
Add icons to the AnkiDroid shortcuts

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14081]
Currently we have 3 shortcuts:
1. Study
2. Add
3. Card browser

None of them have icons and it would be nice to have some. 

I suggest that the card browser shortcut icon be the same that is used for the card browser button at the navigation drawer. 

A `+` icon would be nice in the `Add` shortcut

**Comment by BrayanDSO** [comment]
Sure

**Comment by KUSHAL-RAJ-PAREEK** [comment]
may i work on this issue

**Comment by hemant838** [comment]
could you please assign me this issue

**Comment by BrayanDSO** [comment]
@madhuri701, are you still working on this? I'm gonna give you a 48h time períod to reply. If you don't, I'm going to assign to the next person

**Comment by relentless-pursuit** [comment]
> Currently we have 3 shortcuts:
> 
> 1. Study
> 2. Add
> 3. Card browser
> 
> None of them have icons and it would be nice to have some.
> 
> I suggest that the card browser shortcut icon be the same that is used for the card browser button at the navigation drawer.
> 
> A `+` icon would be nice in the `Add` shortcut

I have figured out where the code changes be done. Also, I have found out the matching card_broswer icon in navigation drawer for the shortcut. The pending task is finding a suitable icon for review. And, i think a suitable icon can be used from google fonts. So, can you assign me this to start making those changes?

**Comment by BrayanDSO** [comment]
Go for it, @relentless-pursuit

**Comment by relentless-pursuit** [comment]
> Go for it, @relentless-pursuit
I am new to mobile development. Infact, this is the first time i am working on android studio. hence, i might miss out on aesthetics or different use cases. I am attaching a screen-shot of the emulator. I tested in nexus S API 34. Your feedback would be valuable. 

<img width="705" alt="image" src="https://github.com/ankidroid/Anki-Android/assets/95259545/14b6fe30-d5d5-46f8-b7d2-0af77cc2dccf">

**Comment by relentless-pursuit** [comment]
@BrayanDSO Can I proceed with a PR or draft PR based on the screenshot I have attached?

**Comment by snowtimeglass** [comment]
@relentless-pursuit Thank you for the contribution, but I'm afraid to say that I don't like the icon for "Study" very much.

What can I say, it evokes a bit of instinctive unease in me, and perhaps in some of the users (not neurosurgeons or medical students), I guess. The symbol of brain is not as abstracted as that of heart (♡). Also, the brain symbol is generally not as familiar as the heart one. So, it still impresses with the rawness of an internal organ. It would make me hesitate to open the shortcut icon menu unfortunately.

I would appreciate it if the possibility of using another icon could be considered, for example, simply using the star icon like the notification. 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/770e2f53-b44c-40c4-85d7-d637d371315d)

https://github.com/ankidroid/Anki-Android/blob/b44dcf49d5a410751ead0d29b7b3c90ccbfed965/AnkiDroid/src/main/res/drawable/ic_star_notify.xml

https://github.com/ankidroid/Anki-Android/blob/b44dcf49d5a410751ead0d29b7b3c90ccbfed965/docs/graphics/src/ic_star_notify.svg

The "Study" is for the core feature of the app. The star is the core of the symbol of the app. So, the star would work well as the "Study" icon, I think.

**Comment by relentless-pursuit** [comment]
> @relentless-pursuit Thank you for the contribution, but I'm afraid to say that I don't like the icon for "Study" very much.
> 
> What can I say, it evokes a bit of instinctive unease in me, and perhaps in some of the users (not neurosurgeons or medical students), I guess. The symbol of brain is not as abstracted as that of heart (♡). Also, the brain symbol is generally not as familiar as the heart one. So, it still impresses with the rawness of an internal organ. It would make me hesitate to open the shortcut icon menu unfortunately.
> 
> I would appreciate it if the possibility of using another icon could be considered, for example, simply using the star icon like the notification. ![image](https://user-images.githubusercontent.com/10436072/253461604-770e2f53-b44c-40c4-85d7-d637d371315d.png)
> 
> https://github.com/ankidroid/Anki-Android/blob/b44dcf49d5a410751ead0d29b7b3c90ccbfed965/AnkiDroid/src/main/res/drawable/ic_star_notify.xml
> 
> https://github.com/ankidroid/Anki-Android/blob/b44dcf49d5a410751ead0d29b7b3c90ccbfed965/docs/graphics/src/ic_star_notify.svg
> 
> The "Study" is for the core feature of the app. The star is the core of the symbol of the app. So, the star would work well as the "Study" icon, I think.

Makes sense. Thank you for the feedback. Meanwhile, I will try to incorporate the feedback. And, send a sample of how it looks like again.

**Comment by praveen7512** [comment]
May i work on this issue?

**Comment by relentless-pursuit** [comment]
@snowtimeglass , @BrayanDSO Can this be considered? And, if there are any other changes/feedback, please let me know. Otherwise, Can i proceed with a PR?
<img width="352" alt="Screenshot 2023-07-15 at 10 54 12 AM" src="https://github.com/ankidroid/Anki-Android/assets/95259545/9ca3465e-5d94-4bc6-9522-fe4627e71803">

**Comment by BrayanDSO** [comment]
LGTM. Send a PR, please @relentless-pursuit

**Comment by snowtimeglass** [comment]
@relentless-pursuit Thank you for the replacement. The star looks good to me. The other icons also look nice. 

I suppose that adjusting the color might make them more attractive, especially when they are placed on the home screen.
![youtube shortcut android 2](https://github.com/ankidroid/Anki-Android/assets/10436072/ecf63275-35b7-493c-86f1-cf6a00380af3)

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/3b7123cf-93ca-4afc-b23e-9ebada76d93c" width="320px">

I'm not familiar with that, but it might be good to utilize the pre-made color, `"@android:color/holo_blue_dark"`, as follows (if you would try to incorporate this change).
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/a5992f7f-1c40-43c5-bcf7-38018cfb913a" width="320px">
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/3461ec8e-d971-4923-8c6d-cc4b44821f52" width="320px">

(Your PR at this moment will be helpful for me, too.)

**Comment by relentless-pursuit** [comment]
@BrayanDSO done. @snowtimeglass, thank you for the feedback. As far as i understood, using a predefined Android color like '@android:color/holo_blue_dark' can make icons more visually appealing, especially when placed on the home screen. Please correct me if i am wrong. I have done those changes in the PR raised and attaching a sample of the same. Please have a look and let me know your feedback. 

link to PR: https://github.com/ankidroid/Anki-Android/pull/14136

<img width="333" alt="Screenshot 2023-07-15 at 7 16 47 PM" src="https://github.com/ankidroid/Anki-Android/assets/95259545/9fac0dff-2b82-4cae-a54b-b5d42370b7da">

**Comment by snowtimeglass** [comment]
LGTM. Thank you for the color change. I appreciate your perfect understanding of my opinion. 

Although the simplicity of the black (or dark grey) icons in the previous sample is fairly appealing to me, considering the case when the icons are placed alongside other app icons on the home screen, I think it would be appropriate to color them like this, unlike this app's internal (monochrome) icon style.

**Comment by relentless-pursuit** [comment]
Thank you for the response. Since, it was my first contribution in mobile development area, I just was focused on changing icons. But, then you made me realise what goes into chosing the right icon, or the right color. And, that makes me realise that a lot goes into aesthetics. What might seem trivial for an user, can actually be pretty logical and emotional to a developer and designer. Thankyou again for being detailed comments and helping me understand the process. I have atttached a link to the PR. If you get time, please give your valuable feedback.  

link to PR: https://github.com/ankidroid/Anki-Android/pull/14136

**Comment by snowtimeglass** [comment]
I'm glad to hear that. Thank you for letting me help your contribution :-)
