### ISSUE TITLE
[BUG]: Color Inversions in Night Mode

### ISSUE THREAD

**Issue by sorata225** [ankidroid/Anki-Android#14089]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

I am no programmer. So I may not be able to properly explain things using my 8th grade html knowledge. But here's an attempt. I have modified one of my note types to include this
<code>#word {
  font-size: 30px;
  margin-bottom: 16px;
  color: chocolate;
  text-align: center;
  border-radius: 12px;
  box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
  padding: 24px;
  margin: 12px;
  border: 1px solid #D9D9D9;
}</code>

### Expected behaviour

In a normal world the chocolate colour is the colour of chocolates.

### Actual behaviour

In anki, chocolate is the colour of the sky.

![Screenshot_2023-07-04-15-46-48-09_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/5f88cd55-de8c-4e8c-a78d-c2e6ccacc675)

The 凛 here should have been a different color.

### Debug info

```text
AnkiDroid Version = 2.16.0beta5

Android Version = 11

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.147 Mobile Safari/537.36

ACRA UUID = dce906d5-19f7-4514-a0e4-0071f4f7b489

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Similar problems arise with colours in anki when I'm in dark mode(and I'm always in dark mode). See these two screen shots of a note/card from a different deck. 
![Screenshot_2023-07-04-16-17-02-40_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/9143f776-2882-4934-b3f3-2240e76790a0)
![Screenshot_2023-07-04-16-16-53-10_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/19ac87c0-178e-42ba-bfd5-5d6d01bc5cdd)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Colors are inverted in night mode if the CSS doesn't specify a `.night_mode` or `.nightMode` selector somewhere. Adding one (maybe even empty) should avoid this

**Comment by BorisNA** [comment]
@sorata225 - as for readability, dark colored font is good for the light background, but is unreadable on the dark one. And vice versa. 

See my example with magenta/darkmagenta and blue/deepskyblue.  It was done on purpose, since I use the card both on a desktop (with the light scheme) and on a phone (with the dark oled theme). If I use just one color it won't be readable in both cases.

And yes, you can turn this off with `.night_mode {}`
