### ISSUE TITLE
Crash when deleting unused media while syncing 

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#14083]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

I had a lot of unused media files. During syncing I pressed the button to sync media in the background, checked media and started to delete unused media

Steps to reproduce
1. Create 1,000 media files
2. Sync, press background 
3. Check media
4. Delete unused

### Expected behaviour

No crash, maybe an error message.

### Actual behaviour

An "unusual" error message appears (more details: [https://forums.ankiweb.net/t/untranslatable-string/31774](https://forums.ankiweb.net/t/untranslatable-string/31774)), AnkiDroid crashes (I have sent a crash report).

### Debug info

```text
AnkiDroid Version = 2.16.0beta5

Android Version = 13

ProductFlavor = full

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.147 Mobile Safari/537.36

ACRA UUID = 3092f152-c3c7-4ade-942a-3bcacb208dbd

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Do you know if this happens without the new backend?

**Comment by pavreh** [comment]
This didn't happen without the new backend because it is not possible to check media (or perform any other actions) while sincing. Sync cannot be done on the background.
