### ISSUE TITLE
[BUG]: Notetype Back content is copied to Front after an activity recreation

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14086]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Note editor > Edit template
2. Select "Back" in the bottombar
3. Change system night mode (assuming your AnkiDroid theme is `Follow system`

### Expected behaviour

Front content stay as is

### Actual behaviour

Back content is copied to front

### Debug info

```text
2.16.0beta5

Legacy backend/v2 scheduler
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Aditya13s** [comment]
Please explain this bug in detail so that I can work on it.

**Comment by parthn2** [comment]
Hey @BrayanDSO! I was trying to reproduce the issue but was not able to! Please tell if this is the page which is having issue and the issue is that instead of {{Back}} it is coming out to be {{FrontSide}}! 
<img width="180" alt="Screenshot 2023-09-09 at 11 04 49 AM" src="https://github.com/ankidroid/Anki-Android/assets/74675085/19334380-c1f3-4d47-8a61-9b63dad23d31">

**Comment by BrayanDSO** [comment]
Steps:

https://github.com/ankidroid/Anki-Android/assets/69634269/c18d7423-6f52-43c2-a66f-aa0cbfe22066

**Comment by parthn2** [comment]
> Steps:
> 
>  Screen_Recording_20230909_051322_AnkiDroid.mp4

Got it now! I will explore and reach back if I think I can solve the issue!

**Comment by Aditya13s** [comment]
@david-allison can i work on this issue?

**Comment by david-allison** [comment]
@Aditya13s Sure, thanks!!

**Comment by Aditya13s** [comment]
@david-allison i think this bug is no more. I am not able to find this bug in the app.

**Comment by BrayanDSO** [comment]
Reproduced with the exact same steps in main

**Comment by Aditya13s** [comment]
@BrayanDSO can you send me a video on how to reproduce this bug.

**Comment by david-allison** [comment]
Reproduction instructions: https://github.com/ankidroid/Anki-Android/issues/16467

**Comment by deysak** [comment]
Working on it 🐞🔍
