### ISSUE TITLE
[BUG]: AnkiDroid not updating css file

### ISSUE THREAD

**Issue by wagewarsgetrichdiegoncharov** [ankidroid/Anki-Android#14080]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Update css file in desktop media collection. 
2. Sync desktop Anki.
3. Sync AnkiDroid.

### Expected behaviour

For the css file in AnkiDroid to update to the desktop version of the file. 

### Actual behaviour

The file does not update. In fact, the only way I've been able to force it to update it delete it from the desktop media folder, sync both collections, replace it, and sync both again. 

### Debug info

```text
AnkiDroid Version = 2.16.0beta3

Android Version = 10

ProductFlavor = full

Manufacturer = samsung

Model = SM-G960U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-G960U Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.131 Mobile Safari/537.36

ACRA UUID = dccfd3bc-6176-4719-8542-05af6fba61df

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

If there's any other debugging info I should provide, just let me know! 

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
What do you mean here by `Update css file in desktop media collection`? Were you editing an actual CSS file, or it was an Anki notetype CSS?

**Comment by wagewarsgetrichdiegoncharov** [comment]
I have an actual CSS file in my media folder, with `@import url("_file.css")` in the Styling tab of the note template.

**Comment by BrayanDSO** [comment]
Have you tried using `Media check` on Anki desktop or AnkiDroid?

**Comment by dae** [comment]
https://docs.ankiweb.net/syncing.html#media

**Comment by BrayanDSO** [comment]
Since this is not exactly a bug. I'm going to close this.

**Comment by wagewarsgetrichdiegoncharov** [comment]
I see, thank you! What made me think it was a bug was that it seemed like the behavior changed, like my AnkiDroid was recognizing that a media file was updated and updating accordingly and then stopped doing that with an update. But, I guess not updating is the default, and the expected behavior.
