### ISSUE TITLE
LaunchCatchingTask should be adapted for write

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14085]
`launchCatchingTask`'s task does not start if the job is destoyed. That's perfectly acceptable if the task is here to get data to display. But there is nothing that ensure that the last review before reviewed is close, or the edition of a note, will actually be saved.
So, I guess that the tasks that write may need to be done on `GlobalScope` instead.
We should still keep the current activity, so that we can show error message on it, but only as a weak pointer, so as not to leak it. (Ideally, if there were a way to know current top level activty, so that it can be used in case of error, it would be great actually. Or to show an error message that does not require an activy that is displayed)

Thanks for @lukstbit review, that told me that we should not use `launchCatchingTask` in `onDestroy`, as I had not realized this pitfall

**Comment by dae** [comment]
Related discussion: https://github.com/ankidroid/Anki-Android/issues/13970

**Comment by oakkitten** [comment]
> in the note editor, saveCard use a progress dialog, so we block until it's saved, so no risk of it getting closed.

Some actions such changing the device theme will trigger activity recreation, which cancels the job. And the progress dialog will get lost, of course.

**Comment by BrayanDSO** [comment]
This will have a lot of per-case fixes, so I'm closing this in favor of more objective and specific issues

**Comment by BrayanDSO** [comment]
This will have a lot of per-case fixes, so I'm closing this in favor of more objective and specific issues
