### ISSUE TITLE
Simplify "Don't ask again string" in the metered connection dialog

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14091]
![Screenshot_20230704_124408_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/69634269/0cfd8656-b4c3-4313-bc3b-3b21ad779175)

My proposal is to reduce the checkbox to only ~~Don't warn again~~ `Don't show again`, because

1. The text isn't "asking" anything, but warning
2. Too much text to convey an action. The focus should be on the checkbox action, not on something else
3. The setting to re-enable the dialog isn't hard to find

**Comment by BrayanDSO** [comment]
This is a personal opinion. Not open to PRs until this is discuted

**Comment by lukstbit** [comment]
I'm indifferent to this, so consider my approval for any option.

**Comment by snowtimeglass** [comment]
I agree with simplification and the reasons above. I think that "Don't show again" might be enough, though. It is a common phrase that accompanies alerts, so it is easy to understand with minimal attention. Also, it is one of the existing source strings.

**Comment by BrayanDSO** [comment]
I like `Don't show again`, and recycling strings is always great.

issue opened for PRs

**Comment by pratyaksh1610** [comment]
Working on it .
