### ISSUE TITLE
[BUG]: Issues with "start of next day"/rollover handling

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#14090]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

"start of next day" is set to 4 hours past midnight (I don't know if it needs to be set this way a day before the cards become available to study, but in my case it had been set as "4 hours past midnight" for several days)
study all cards scheduled before midnight
after midnight, but before 4am, adjust "start of next day" to 0 hours before midnight

### Expected behaviour

after decreasing "start of next day", new cards should become available to study and studying should behave normally

### Actual behaviour

after decreasing "start of next day", new cards become available to study but the "undo" button is greyed out while studying

### Debug info

```text
AnkiDroid Version = 2.16.0beta4

Android Version = 12

ProductFlavor = full

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 0819f67d-4836-45b6-90c6-ecc700511215

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Do you know if this happens without the new backend enabled?

**Comment by doozan** [comment]
I was unable to reproduce the error with the new backend disabled.

Attempt to reproduce:
- Disable new backend
- Set start of next day to 4 hours after midnight
- Wait a day to make sure the scheduler is using the old backend
- Before midnight, study all cards
- After midnight and before 4am, adjust "start of next day" to 0

Expected:
- New cards become available to study, and undo button works

Actual:
- New cards do not become available to study, Anki still reports all cards have been studied
- However, after a force-close and restart, Anki does show new cards to study and the undo button does work

Note: I did not try force closing the app while using the new backend. It could be that the force-close fixes the undo button regardless of whether or not the new backend is enabled.

**Comment by doozan** [comment]
Just for the sake of completeness, I reproduced this again with the new backend enabled. Force-closing and re-opening anki does fix the undo button when the new backend is enabled. So it's impossible to get into the "no undo button" state with the old backend since the old backend doesn't seem to rebuild the list of cards to be studied when changing the "start of next day" value, but it's not clear whether or not this bug is part of the new backend.

**Comment by doozan** [comment]
Still an issue as of 2.16.5

**Comment by david-allison** [comment]
* Related: https://github.com/ankidroid/Anki-Android/issues/12946

**Comment by BrayanDSO** [comment]
Maybe `SharedPreferences.OnSharedPreferenceChangeListener` can solve this specific issue. #11046 as well

**Comment by david-allison** [comment]
Specifically: 

1. We need functionality to handle rollover once the day passes the threshold
2. We need functionality to handle the change in settings

The Anki Desktop solution for rollover is:

https://github.com/ankitects/anki/blob/edd38ca06730d7fc16804f52ce10f6bc54c3d145/qt/aqt/main.py#L508-L528

Briefly discussed on Discord: https://discord.com/channels/368267295601983490/701922522836369498/1184649125443149864

Since this is blocking, I'll propose a quick hack:

* run a handler every minute checking for rollover
  * If rollover is 'soon', change this to every second 
* If the user unpauses the app, check for rollover

I don't know how much we can trust a handler to be accurate, and we likely can't get an accurate notification due to Android system, so I don't want a 'large' scheduled delay. Once per minute seems reasonable

**Comment by BrayanDSO** [comment]
For a hack, putting it in `onResume` of `DeckPicker` and `Reviewer` seems good enough to me, and it should be less battery demanding. 

Generally when an issue is relevant, more than one person comes to complain here even if someone already posted it, so I wouldn't sweat about getting it super accurate or block 2.17 because of it

**Comment by david-allison** [comment]
If it's not accurate, the end user will receive an 'Invalid Input' message

**Comment by david-allison** [comment]
The Anki code:

* Checks every second
* Is based off a change in 'day cutoff' rather than the delta from the current time to the 

Performance:

`withCol { sched.dayCutoff }` takes 0-5ms on a background thread, I'm not worried about a hit to battery life from this

**Comment by BrayanDSO** [comment]
Reasonable. Handler seems fine then

**Comment by dae** [comment]
> The Anki code: Checks every second

Not sure if that's what you meant - the code schedules a timer that runs at rollover time, so it "checks" only once (at least if ignore the internal implementation to Qt timers)

**Comment by david-allison** [comment]
> > The Anki code: Checks every second
> 
> Not sure if that's what you meant - the code schedules a timer that runs at rollover time, so it "checks" only once (at least if weignore the internal implementation to Qt timers)

Misread the code, thanks for the comment, will rewrite.

**Comment by dae** [comment]
And I'll rewrite that mess of a sentence ^_^;
