### ISSUE TITLE
Remove "Chess notation support" 

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14092]
The "Chess notation support" setting is supposed to enable parsing a Forsyth-Edwards notation to a chessboard design.

Since:
1. this isn't a general use case
2. It can be done in a note type
3. It doesn't exist in other Anki versions (Anki desktop and AnkiMobile)
4. It is best to keep only essential settings, since there are some people that have a hard time understanding them

I suggest to remove it.

Currently this issue isn't open to PRs, since this is based on my opinion and needs more discussion

**Comment by pavreh** [comment]
Moreover, the chess notation does not work with the new backend. You can test it by creating a card with this content: 

[fen]​rnbqkbnr/pp1ppppp/8/2p5/4P3/8/PPPP1PPP/RNBQKBNR w KQkq c6 0 2[/fen]

While you can see a chessboard in the old backend, you will see the string above in the new backend.

And because it is not an upstream function, I vote to remove it, too.

**Comment by lukstbit** [comment]
I'm also for this removal.

We might want to look at other settings as well, just two examples:

- Appearance -> Background image(I haven't found this option in Anki desktop?) . What's the point of this(this seems like having a setting just for the sake of it)?
- General -> Press BACK twice to exit the app , this shouldn't be implemented in an Android app that integrates correctly with the system. An app should easily go and come up to the foreground if the user chooses, there's also the new [predictive back](https://developer.android.com/design/ui/mobile/guides/patterns/predictive-back) to consider.

Ideally we would be making this changes using analytics data to see how many users actually use this settings.

**Comment by BrayanDSO** [comment]
> Ideally we would be making this changes using analytics data to see how many users actually use this settings.

I intend to implement preferences analytics after 2.16.

**Comment by BrayanDSO** [comment]
Besides the lack of statistics, since this is a setting that shouldn't exist and that people agree with removing it, I'm gonna do it.

**Comment by BrayanDSO** [comment]
> I intend to implement preferences analytics after 2.16.

Implemented it at #14114 since it should be useful getting analytics earlier in 2.16

**Comment by szukiadam** [comment]
I had quite a few decks utilizing this functionality, is there anything we can use now after the removal to display FEN positions?

**Comment by szukiadam** [comment]
> Did you find a way? I got back to some old decks and realized they are useless now 😞

@menisadi I looked up the last working version and manually installed it on my phone. You have to be mindful not to update your version by accident and you'll miss out on some new features, but so far it has been working well.

**Comment by mikehardy** [comment]
You might notice there are "parallel" builds of the last release that had it (the 2.15.x series I believe), you may install those side-by-side with a current version and not worry about upgrading

https://github.com/ankidroid/Anki-Android/releases/tag/v2.15.6

However, synchronization will likely not work as that version does not "speak" the collection version that ankiweb uses as a minimum now

For desktop https://github.com/lwerdna/anki-fen-vis

I assume if someone was interested they could bundle `chessboard.js` library, put it in their media collection, and use javascript in a custom card template here to locate FEN in the card front or back and set it as the position via the chessboard API https://chessboardjs.com/examples.html#2044
