### ISSUE TITLE
[BUG]: "New cards in random order" is actually reverse order added

### ISSUE THREAD

**Issue by BlueRaja** [ankidroid/Anki-Android#14107]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Use the v2 scheduler
2. Set "New cards --> Order" to "New cards in random order"
3. Set "New cards/day" = 7
4. Add more than 7 cards to the deck each day

### Expected behaviour

New cards are chosen randomly from all available cards

### Actual behaviour

All 7 cards each day are picked from the > 7 cards that were added yesterday.  This has happened every single day for the past month, which is too often to be explainable by coincidence.

### Debug info

```text
AnkiDroid Version = 2.15.6

Android Version = 9

Manufacturer = LGE

Model = VS988

Hardware = lucye

Webview User Agent = Mozilla/5.0 (Linux; Android 9; VS988 Build/PKQ1.190522.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.57 Mobile Safari/537.36

ACRA UUID = 8076c55d-caac-4a69-80d3-6a87194a098a

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
@BlueRaja Use latest beta version https://github.com/ankidroid/Anki-Android/releases/tag/v2.16.0beta5

Not reproducible in latest version

**Comment by BlueRaja** [comment]
I will give it a shot, but I thought the ordering came from the server. `sortDeck` is implemented in Rust.

**Comment by dae** [comment]
Please see the caveat on https://docs.ankiweb.net/deck-options.html#insertion-order. If you enable the v3 scheduler in the beta version, you can avoid the issue.

**Comment by BlueRaja** [comment]
Weird that such horrendously broken behavior would be documented and not fixed, but I can confirm it doesn't happen in the v3 scheduler.
