### ISSUE TITLE
[BUG]: Isuue with Advanced Statistics 

### ISSUE THREAD

**Issue by sorata225** [ankidroid/Anki-Android#14119]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

The advanced statistics on one of my decks does not look right. I've checked changing the time frames but it stays the same. This is the SS of the settings I'm using. 

![Screenshot_2023-07-08-02-37-27-02_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/eb3f2db7-4cfa-4882-9ad3-046ee283e24a)

### Expected behaviour

The advanced statistics to my knowledge takes account of the number of new cards I am doing per day. And then shows a graph of future reviews on the basis of that. So in one of my decks the daily new cards is set to zero. As I'm immersing more in my target language, I've stopped using that deck except the reviews. That means the number of daily reviews should be decreasing.

### Actual behaviour

In my case, this has been increasing actually(I mean, in the statistics, in reality it's decreasing). The reason I suspect is, Anki is assuming the number of daily new cards to be one(it's zero).

![Screenshot_2023-07-08-02-36-39-01_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/17500695-fdb0-44ff-9e22-835cc3eb2a47)

I've confirmed it from another deck where anki's doing the same thing.

![Screenshot_2023-07-08-02-36-19-89_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/c80fef9d-7b8f-4e58-820c-d93b50e9cfe4)

### Debug info

```text
AnkiDroid Version = 2.16.0beta5

Android Version = 11

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36

ACRA UUID = dce906d5-19f7-4514-a0e4-0071f4f7b489

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Is this some sort of feature I'm unaware of?

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
I’m sorry, but advanced statistics will be gone when we start using the same statistics screen as Anki Desktop, so this is not going to be worked on

**Comment by sorata225** [comment]
@BrayanDSO That's nice to hear. Is there a timeline for when we will be getting the same statistics screen as anki desktop?

**Comment by BrayanDSO** [comment]
We can't give a timeline because we are all volunteers here. 

You can already use it by enabling the new backend (Settings > Advanced > Use the new backend), which is experimental.

The 2.17 goal currently is to make the new backend the default
