### ISSUE TITLE
Due Order Field

### ISSUE THREAD

**Issue by sorata225** [ankidroid/Anki-Android#14127]
**Is your feature request related to a problem? Please describe.**

There are times when I want to change the order of the new cards in accordance to a particular field. For instance, when learning vocabulary cards with a frequency field you may want the cards to show up according to that particular field. This can happen with Japanese kanji decks with multiple ordering possible. You may want kanji to show up according to the frequency when it is actually ordered according to jouyou grade.

**Describe the solution you'd like**
 
I suggest something similar to the sort field that would basically identify the field used for ordering all the new cards.

**Comment by BrayanDSO** [comment]
Already possible. Order your cards by the field you want and then reschedule then.

**Comment by sorata225** [comment]
@BrayanDSO By reschedule you actually mean reposition. Well I know about reposition, but if you have something like a mining deck, that would require you to do it multiple times a day. Especially because I do a lot of new cards at various times of the day combined with mining.

**Comment by BrayanDSO** [comment]
Oh, I see. I thought this was a once in a time operation. Is that possible in the desktop version? If not, you should ask there, since here we use the same scheduler

**Comment by dae** [comment]
Sorry, this is unlikely to happen, as the queue building code needs to avoid accessing note data in order to perform well.
