### ISSUE TITLE
The automatic linkage from enabling "Use the new backend" to enabling "Use the v3 scheduler" is not clear visually on the spot.

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#14123]
**Is your feature request related to a problem? Please describe.**
When "Use the new backend" is enabled, "Use the v3 scheduler" is also enabled automatically. However, this linkage isn't shown on the spot. 

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/2d2c0839-164c-4cdd-a7d7-ce899e669203)

https://github.com/ankidroid/Anki-Android/assets/10436072/2277f4be-f0f1-4836-82d8-c2ffea3c38a8

**Describe the solution you'd like**
Visualize the linkage on the spot, that is, show that when the "Use the new backend" switch is turned on, the "Use the v3 scheduler" switch is also turned on.

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/621209c0-39b5-40d4-9c08-831db11eefae)
(2.16.0beta4-debug)

https://github.com/ankidroid/Anki-Android/assets/10436072/b0560f44-b93b-4be0-9f26-81c95509a9c2

(2.16.0beta4-debug)

**Describe alternatives you've considered**
N/A

**Additional context**
The linkage from disabling the new backend to disabling the v3 scheduler is visualized on the spot.

https://github.com/ankidroid/Anki-Android/assets/10436072/7f931f47-7457-4492-ae96-61d231500586

**Comment by BrayanDSO** [comment]
Will be solved when the new backend is the default, so I don't suggest spending time on it. 

It is a "Experimental" setting, so not having the best UX is expected
