### ISSUE TITLE
FR: Ankidroid plugin inside Koreader for android e-ink devices

### ISSUE THREAD

**Issue by unacceptablet** [ankidroid/Anki-Android#14128]
Greetings & salutations.

Is it possible to create a [plugin](https://github.com/koreader/contrib) for Koreader which adds looked-up words to a anki.

Like this but for android e-ink devices:  https://github.com/Ajatt-Tools/anki.koplugin

I guess it doesnt have to be for "AnkiDROID" just Anki. Synchs to anki server. 

Deivce: Onyx Boox leaf 2 (android  11).

**Comment by BrayanDSO** [comment]
Hi there. We already have an API that should makes this possible, but this feature requires work in KOReader's end, not ours. So try asking there if they can implement this
