### ISSUE TITLE
[Bug] Keyboard input not visible on SearchIcon click in LocaleSelectionDialog

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#14121]
###### Reproduction Steps

1. Go to Manage Note Types
2. Click on any note type
3. Click on Fields
4. Select `Set keyboard language hint`

###### Expected Result
Keyboard input is visible on SearchIcon click in LocaleSelectionDialog

###### Actual Result
Keyboard input not visible on SearchIcon click in LocaleSelectionDialog

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.16.0beta5-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36

ACRA UUID = 20b2dc80-f22d-4759-9817-396d281f95b3

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
This issue introduced due to #14061

**Comment by BrayanDSO** [comment]
Reverts are accepted as well
