### ISSUE TITLE
[BUG]:  Syncing gets stuck on "Finding changed media"

### ISSUE THREAD

**Issue by Pineapplenuts** [ankidroid/Anki-Android#14131]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

The option to migrate to scoped storage comes up then, the sync starts and gets stuck on finding changed media despite no media changes for months. Following this train of thought, I changed a note type on the desktop anki to force a one way sync so anki-droid gets the option to replace the collection with ankiweb's collection only to get stuck on finding changed media again. 

### Expected behaviour

The collection gets replaced with the collection from ankiweb and then the migration to scoped storage gets successfully completed. 

### Actual behaviour

The sync gets stuck on finding changed media and nothing else happens 

### Debug info

```text
AnkiDroid Version = 2.16.0beta5

Android Version = 11

ProductFlavor = full

Manufacturer = Xiaomi

Model = Redmi Note 8

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi Note 8 Build/RKQ1.201004.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36

ACRA UUID = a4c4b778-3a4f-4a87-a042-156141bd3978

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Should be solved in 2.17
