### ISSUE TITLE
FR: Make dictionary entries pretty using .lua script just like Koreader

### ISSUE THREAD

**Issue by unacceptablet** [ankidroid/Anki-Android#14141]
I have used [FastWordQuery](https://github.com/sth2018/FastWordQuery) to import definitions from local stardict dictionaries to Anki. But the same dictionary looks pretty on Koreader (right) & but not so pretty on Ankidroid (left):

![image](https://github.com/ankidroid/Anki-Android/assets/127971612/cb18eafb-86a1-46b1-bcd3-013560989bd1)

The .lua script inside the dictionary folder contains the following code:

```css
return function(html)

    html = html:gsub('<rref[^>]*>[^<]*%.wav</rref>', '🔊')
    html = html:gsub('<rref[^>]*>[^<]*%.jpg</rref>', '⛶')
    html = html:gsub('<k[^>]*>[^<]*</k>', '')
    html = html:gsub('<c>', '<span>')
    html = html:gsub('</c>', '</span>')
    html = html:gsub('<c c="', '<span style="color:')
    html = html:gsub('"color:indigo"', '"color:#4B0082"')
    html = html:gsub('"color:darkgray"', '"color:#A9A9A9"')
    html = html:gsub('"color:lightcoral"', '"color:#F08080"')
    html = html:gsub('"color:lightseagreen"', '"color:#20B2AA"')
    html = html:gsub('"color:darkgoldenrod"', '"color:#B8860B"')   
    html = html:gsub('"color:orangered"', '"color:#B8860B"')   
    html = html:gsub('"color:sienna"', '"color:#B8860B"')   
    html = html:gsub('"color:darkred"', '"color:#B8860B"')   
    html = html:gsub('"color:navy"', '"color:#B8860B"')   
    html = html:gsub('"color:red"', '"color:#B8860B"')   

    return html
end
```
This code changes the .wav / .jpg text to icons, changes the color of some annoying words to grey etc. But this does not work on Ankidroid.

How can I use the same .lua script to make it look as good as Koreader?

**Comment by BrayanDSO** [comment]
The feature itself won't be implemented because only a very few users would use it and it can be made with Javascript
