### ISSUE TITLE
Disable keyboard suggestions in "type in the answer" box

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14148]
**Is your feature request related to a problem? Please describe.**
When a user is typing in the answer, the keyboard suggestions interfere with the recall. This can also be appropriately called as "cheating".

**Describe the solution you'd like**
Disable the keyboard suggestions when the focus is on the type box.

**Describe alternatives you've considered**

**Additional context**

**Comment by n1snt** [comment]
If this gets approved, I would love to work on this.

**Comment by BrayanDSO** [comment]
Duplicate of #10352. I'll reopen it so you can discuss it there
