### ISSUE TITLE
Reset progress inconsistent with desktop Anki

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14155]
### Checked for duplicates?

- [X] This issue is not a duplicate

AnkiDroid uses the terms "Reset progress" and "Reschedule" while Anki Desktop uses the terms "Forget" and "Set Due Date" for the same options respectively.

Also, the "Reset progress" option in AnkiDroid works like how older versions of Anki did.

* [x] Set Due Date
* [ ] Reset

#### Debug info

```text
AnkiDroid Version = 2.16.0beta5
```

As a side note, I feel that "Reset progress" is a better term as compared to "Forget". The term "Forget" is somewhat confusing. A user might think that it is used to tell Anki that you have forgotten a card (when the card is not due yet). Even the heading of [the related page in Anki FAQs](https://faqs.ankiweb.net/resetting-progress-in-a-deck.html) uses the term "reset progress" rather than "forget". @dae, what do you think about this?

**Comment by user1823** [comment]
Another inconsistency: While the option is called "Reschedule", the undo option that comes after using it says "Undo Set Due Date".

**Comment by user1823** [comment]
> I feel that "Reset progress" is a better term as compared to "Forget". The term "Forget" is somewhat confusing.

@dae, if you think that it would be better to change this terminology in Desktop Anki, I think that now is the correct time to do so (with so many other changes that have happened in 23.10).

**Comment by user1823** [comment]
Given that https://github.com/ankidroid/Anki-Android/pull/15699 has been merged, we now just need to
- implement the new Reset dialog
 
   <img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/3e3e89c5-4fbc-4346-8124-2f404ec840f7">
- (optional) switch to the Anki Desktop string for the name of the option (https://github.com/ankitects/anki/commit/eee02d5e8c2054a691b5271a14efedbf27c05296)

**Comment by david-allison** [comment]
Reset/Forget are both incorrect. The dialog works for 1 card or many cards

But the title is always in the singular
