### ISSUE TITLE
Italics: AnkiDroid wraps in em tags, Anki Desktop in i tags

### ISSUE THREAD

**Issue by twwn** [ankidroid/Anki-Android#14150]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

AnkiDroid wraps text in _em_ tags when selecting the _I_ button in the note editor.

Anki Desktop, however, has always used _i_ tags.

Though both render the same in the default case (semantically, the _em_ tag is also to mean actual emphasis), it's better to unify this to the desktop's older/widespread use of _i_, esp. since some decks use CSS rules for one tag but not the other.

### Expected behaviour

Pressing _I_ in the note editor wraps selection in _i_ tags.

### Actual behaviour

Text is wrapped in _em_ tags.

### Debug info

```text
AD 2.16.0b5
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by chickendude** [comment]
Recording got cut off, but i can confirm that it uses <i> tags on the Linux desktop version.
[recording.webm](https://github.com/ankidroid/Anki-Android/assets/2564517/d42502a3-2d5b-4d65-959c-18f8be491ab9)

**Comment by pilgrimlyieu** [comment]
Confirmed in 2.16.2. I also think that `<i> ... </i>` is better, considering to be consistent with Anki Desktop.
