### ISSUE TITLE
[BUG]: AnkiDroid crashes when importing a specific deck

### ISSUE THREAD

**Issue by paternal** [ankidroid/Anki-Android#14154]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Import [this deck](https://github.com/AnonymerNiklasistanonym/Md2Anki/files/12160093/deck.zip) (.apkg file renamed as .zip because github does not seem to like .apkg files).

To see how this deck was created, go to: https://github.com/AnonymerNiklasistanonym/Md2Anki/issues/21

### Expected behaviour

I expected the deck to be properly imported.

### Actual behaviour

1. A loading screen appears (so far so good).
   ![loading](https://user-images.githubusercontent.com/6587757/255874808-5dfbae9e-7753-488c-9c9b-f248e15c6439.png)
2. AnkiDroid crashes
   ![crash](https://user-images.githubusercontent.com/6587757/255875047-e64e5d66-5c10-45e1-b0fe-1378121d60b7.png)

### Debug info

```text
AnkiDroid Version = 2.15.6

Android Version = 6.0

Manufacturer = Orange

Model = Orange-Rise51

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0; Orange-Rise51 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = acf21fa1-41dd-4aad-950f-e5b27da3ca9f

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

- This bug only happens when using several subdecks of the same level.
- Since it involves subdecks, this bug might be related to #9518

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by paternal** [comment]
Note: Since I do not know if this is a md2anki bug (the software used to generate the deck) or an AnkiDroid bug, I also opened an issue with md2anki: https://github.com/AnonymerNiklasistanonym/Md2Anki/issues/21

**Comment by criticalAY** [comment]
Please update the to the latest `beta`

**Comment by paternal** [comment]
Indeed, it works with 2.16.1. Sorry for the noise.
Thanks!
