### ISSUE TITLE
[Bug] Some titles in settings overflow since beta4

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#14160]
Since beta4, the maximum number of lines for the titles in settings with toggle switches seem to be limited to one. The overflow ranges due to the limitation are possibly large in some languages.

Expected Result (beta3) | Actual Result (beta4, beta5)| Language |
-- | -- | -- 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/0514d162-a6cd-45f3-a61b-1c58b3777ce4)|![image](https://github.com/ankidroid/Anki-Android/assets/10436072/fc811172-538c-4353-8c21-1e6ee16149dd)| English |
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/a51052c6-3360-4e8b-81d1-640334549a30)|![image](https://github.com/ankidroid/Anki-Android/assets/10436072/4bea6900-2869-435a-a66f-a88ea786a9ee)| German |
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/9ca14911-c381-4399-ab59-a5c8c1b005ab)|![image](https://github.com/ankidroid/Anki-Android/assets/10436072/445282a0-6b68-4661-a6c3-e7314ed74bb1)| French |

###### Debug info
```
AnkiDroid Version = 2.16.0beta5

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36

ACRA UUID = 5ba46727-9ddb-47f3-a810-53f66d97a89e

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by n1snt** [comment]
Hey if no one is working on this I would love to have a try at it.

**Comment by snowtimeglass** [comment]
In all or most of the cases, its meaning seems to be understandable by the explanatory texts under the titles.

**Comment by snowtimeglass** [comment]
@RobozinhoD thank you for the fix!
