### ISSUE TITLE
Remove Beolingus pronounce feature

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14165]
Mostly to know if it is worth maintaining

see: LoadPronunciationActivity

**Comment by lukstbit** [comment]
We should remove it directly as we shouldn't be scraping a website.

**Comment by BrayanDSO** [comment]
> We should remove it directly as we shouldn't be scraping a website.

That's my preference as well. Current UI/UX is bad, it can break at any time, and we should focus in TTS instead of it.

**Comment by pratyaksh1610** [comment]
working on it

**Comment by pratyaksh1610** [comment]
We need to remove the `pronunciation` button and its functionality and the above mentioned activity .
Am I on the right path ?

**Comment by BrayanDSO** [comment]
Yep
