### ISSUE TITLE
Add option to bury/unbury cards in browser

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14163]
Please add the ability to bury/unbury cards in the card browser.

The desktop version of Anki added a similar feature some time back: https://github.com/ankitects/anki/issues/2295

**Comment by chickendude** [comment]
I spent some time looking into this today and think i should be able to get a PR up for it if it's something the main devs would like to add.

**Comment by chickendude** [comment]
Just an update, i got the bury/unbury feature working from the card browser (in my [fork](https://github.com/chickendude/Anki-Android/tree/issue-14163/bulk-bury)), though i've noticed the undo functionality isn't exactly what you'd expect, "undo" basically re-buries or unburies the cards. If you bury and unbury a suspended card, for example, it will no longer be suspended. I think this is the same behavior as the existing suspend function, though.

**Comment by user1823** [comment]
The backend update PR has been merged (2 months ago). I think that the requested feature should be easier to implement now.

**Comment by user1823** [comment]
Still waiting for implementation.

**Comment by david-allison** [comment]
Relevant:

https://github.com/ankitects/anki/blob/074becc0cee1e9ae59be701ad6c26787f74b4594/qt/aqt/browser/browser.py#L896-L902
