### ISSUE TITLE
Migrate UI's to compose

### ISSUE THREAD

**Issue by utkarsh006** [ankidroid/Anki-Android#14178]
**Is your feature request related to a problem? Please describe.**
- I have just thought to turn this project's UI layouts into compose which are currently in xml.
- I have explored Android Jetpack for 1yr and can say it's a boon for Android apps. It improves performance and allows us to write reusable code. The new Threads app by Meta is a prime example of it.

**Describe the solution you'd like**
- Current plan is to refactor 3 or 4 existing layouts in XML to compose.

**Describe alternatives you've considered**

**Additional context**

**Comment by utkarsh006** [comment]
@BrayanDSO Kindly Review

**Comment by BrayanDSO** [comment]
IMHO, the work is not worth it currently. We have almost 400 issues here and a very limited workforce, so we have to be selective with what kind of path we want to follow. Changing how our entire UI is built would be a LOT (!!!) of work with an uncertain reward. Having both technologies at the same time (XMLs and Compose) isn't a good idea either from a performance or maintenance perspective.

If we were creating a new app, or were from a big company (exactly like your example of Threads by Meta), Compose would be a good option, but migrating all of the UI to Compose is the exception. Most apps, at least from what I've seen in the open source world, just keep using their reliable XMLs and so should we

**Comment by utkarsh006** [comment]
@BrayanDSO Thanks for reverting me back. I would like to correct you, migrating all UI's to compose is not an exception, may companies or organizations are migrating to compose. Morever, it reduces a lot of boilerplate XML code and UI is easily manageable. [This article](https://medium.com/okcredit/comparing-jetpack-compose-performance-with-xml-9462a1282c6b) gives you an analysis how compose is good in performance. At the end of the day, the repo belongs to Ankidroid and depends on you guys, how you want to take it forward.

Have a nice day !
