### ISSUE TITLE
     Request to make "Reschedule" as one of the command mapping controller button options

### ISSUE THREAD

**Issue by tndk323** [ankidroid/Anki-Android#14179]
Is it possible to make "Reschedule" as one of the command mapping controller button options? I would like to be able to reschedule a card to a different date as needed with a touch of a gesture or button on a game controller without having to tap multiple times to reach the "Reschedule for review in x days"  option for a specific card. 
     Simply put, I would like to be able to do a certain gesture or click a single button to reach the "Reschedule" option like we can do for "Bury card", "Undo", etc. Please let me know if there's already a way to do this! Thank you all so much!!

**Comment by BrayanDSO** [comment]
Yes, it is possible. Pretty valid feature request

**Comment by tndk323** [comment]
Oh, that's awesome! Thank you so much!

**Comment by parthn2** [comment]
Hi, I would like to work on this feature request!

**Comment by parthn2** [comment]
> Hello @parthn2. We appreciate the work.
> 
> For now, there is no need to do a command for `Reset progress`. Just the `Reschedule` command asked by the OP is enough

Okay!! But wouldn't it just make it useless to go 2 clicks for 'Reset' because no one will be using 2 clicks for 'Reschedule' because it is just one click away. So why not break that into 2 if it is the correct thing?

**Comment by BrayanDSO** [comment]
> because no one will be using 2 clicks for 'Reschedule' because it is just one click away.

Not everybody is going to add a gesture for Reschedule, so it may be still be a 2 taps action.
