### ISSUE TITLE
[Question] Compatibility of v2.16.2 with Desktop v2.1.49?

### ISSUE THREAD

**Issue by opusforlife2** [ankidroid/Anki-Android#14172]
I got an upgrade notification for the app, but the changelog mentions a Scheduler V3 and some other changes. I'm stuck on Desktop v2.1.49 due to Windows 7. So I would like to know if this version is still compatible, and if that is intended to change in a future version.

**Comment by BrayanDSO** [comment]
Yes, it is. v3 scheduler is optional and experimental.]

But we are going to have the same code of the desktop version in 2.17, so we can't guarantee the compatibility in the future
