### ISSUE TITLE
[BUG]: The front card's toggle will turn on automatically after adding notes

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#14187]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Add a Card in NoteEditor

### Expected behaviour

The front card's toggle does not  turn on automatically after adding notes

### Actual behaviour

The front card's toggle will turn on automatically after adding notes

### Debug info

```text
AnkiDroid Version = 2.16.2-debug

Android Version = 13

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone_x86_64 Build/TE1A.220922.031; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 7c8b0c2b-d647-4efa-bddd-d1a6b7106de8

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

https://github.com/ankidroid/Anki-Android/assets/65113071/c32fdac5-0bc2-4710-8747-4206f8bb6c4b

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
Don't know the exact reproduction steps. Sometimes, it works or may not. I'll figure it out

**Comment by pratyaksh1610** [comment]
I don't think it's a bug. The `pin` option is `toggled::on` that's why it stays right after that.

**Comment by SanjaySargam** [comment]
> I don't think it's a bug. The `pin` option is `toggled::on` that's why it stays right after that.
@pratyaksh1610 
Ohhhh. I didn't see. Got it Thank You.
And one more thing, the toggle will turn on automatically after adding notes. Is this expected behaviour? I don't think so.
Will you please try to reproduce and let me know

**Comment by SanjaySargam** [comment]
https://github.com/ankidroid/Anki-Android/assets/65113071/56fc35bd-bfb3-492a-876a-91eea11eb159

**Comment by pratyaksh1610** [comment]
> Untitled.mp4

Not able to reproduce this behaviour.
