### ISSUE TITLE
[Bug] AnkiDroid does not sync media with a local anki server

### ISSUE THREAD

**Issue by mauriciosantosds** [ankidroid/Anki-Android#14188]
###### Reproduction Steps

1. Setup a local ankiweb server using nginx or apache as a reverse proxy for https
2. Try to sync with the app.

###### Expected Result

Correctly sync cards and card media

###### Actual Result
The app sync only card's and is not syncing the media 
![Screenshot_20230804_155919_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/4843775/1af06f64-a9f7-4b1f-8903-d12eb8c3fbbc)

###### Debug info

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

Anki desktop built-in web server log:

2023-08-04T19:00:38.884888Z  INFO request{uri="/sync/sanityCheck2" ip="127.0.0.1" uid="mauricio" client="" session="c1f566c3"}: finished elap_ms=1 httpstatus=200
2023-08-04T19:00:38.901762Z  INFO request{uri="/sync/finish" ip="127.0.0.1" uid="mauricio" client="" session="c1f566c3"}: finished elap_ms=3 httpstatus=200
2023-08-04T19:00:38.988825Z  INFO request{uri="/begin"}: finished elap_ms=0 httpstatus=404

Android debug info:

AnkiDroid Version = 2.15.6

Android Version = 13

Manufacturer = samsung

Model = SM-A546E

Hardware = s5e8835

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A546E Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/114.0.5735.196 Mobile Safari/537.36

ACRA UUID = e076c056-f148-4b17-81db-d58bda9cabbb

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

##### Warning
This feature works correctly in the desktop version, it must be some business rules divergence in the android version that is causing the problem

**Comment by BrayanDSO** [comment]
Olá, tudo bem? Sempre ótimo ver um brasileiro por aqui.

Houve umas correções e melhorias no servidor privado na última versão do AnkiDroid. Como ela ainda não está disponível para todos os usuários da Play store ainda, você pode tentar entrar no programa Beta lá na play store para conseguir a atualização agora, ou esperar algum tempo até que fique disponível para todo mundo.

**Comment by mauriciosantosds** [comment]
Olá. Tudo certo e com você?
Também fico feliz de saber que tem mais brasileiros por aqui. 
Já me inscrevi no programa beta, mas por enquanto só aparece para mim a versão 2.16.2 que é a que já estava instalada. 
Vou tentar compilar uma versão mais recente do app.

**Comment by mauriciosantosds** [comment]
![image](https://github.com/ankidroid/Anki-Android/assets/4843775/e80faf41-6fbe-4aa9-8066-d073e7c7090a)

![image](https://github.com/ankidroid/Anki-Android/assets/4843775/268e525e-3481-400a-bcfb-a9232357ca6a)

Está funcionando muito obrigado! Que maravilha! 
Consegui fazer o download do código e compilar o código da branch main.
