### ISSUE TITLE
[Bug] JS / CSS applied to "type in the answer" box doesn't work

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14183]
###### Reproduction Steps

1. Use JS and CSS in the notetype to modify the "type in the answer" box, as in https://forums.ankiweb.net/t/how-to-have-instant-type-answer-feedback/21259/14
2. Review a card and start typing the answer.

###### Expected Result
The background color of the box changes just like in Anki Desktop.

###### Actual Result
The background color of the box doesn't change.

###### Additional information
Even adding "hidden" to the HTML element (like the following) doesn't hide the type box in AnkiDroid, though it does hide the box in Anki Desktop.
```html
<div id='type' hidden>{{type:Back}}</div>
```

###### Debug info
AnkiDroid Version = 2.16.2

Android Version = 12

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g62 5G Build/S2SSIS32.18-12-4-11; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.138 Mobile Safari/537.36

ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
It may be worth checking if this is still an issue after #14171 merges, as that PR switches the comparison to the backend.

**Comment by user1823** [comment]
Just to ensure that the issue is being interpreted correctly, I wanted to say that I am talking about the following box:

<img width=290 src="https://github.com/ankidroid/Anki-Android/assets/92206575/a6c8adaa-25a8-4979-a0cb-12b1e69628e7">

**Comment by BrayanDSO** [comment]
Probably won't by fixed in that PR. That is an Android layout, not a HTML one. 

I'll take a look it when I eventually try to use the upstream code for the reviewer

**Comment by user1823** [comment]
Still waiting for a solution.

**Comment by user1823** [comment]
Still waiting for a solution.

If this is not likely to be fixed soon, I recommend adding a `Keep Open` label.

**Comment by david-allison** [comment]
This probably isn't going to be fixed due to the `EditText` being an Android control. 

Does `Advanced - Type Answer Into Card` cause problems?

**Comment by user1823** [comment]
> Does Advanced - Type Answer Into Card cause problems?

It works. Thanks!

I wonder why it is not the default.

**Comment by david-allison** [comment]
Before my time, but: the default input field is ugly, and HTML doesn't support keyboard language selection

I also believe there were also bugs with ,`<input>` in older versions of Android

**Comment by david-allison** [comment]
Anyway, glad this helped, closing as completed!

**Comment by user1823** [comment]
> the default input field is ugly

I don't think so. I applied some basic css, though:

```css
input#typeans {
 border: 2px solid white;
 border-radius: 5px;
 width: 98%;
}
```

<image width="200px" src="https://github.com/ankidroid/Anki-Android/assets/92206575/a19e1728-1d44-41a4-8802-3a4397349c86">


> HTML doesn't support keyboard language selection

It does, if the following is what you mean.

<image width="200px" src="https://github.com/ankidroid/Anki-Android/assets/92206575/392ef210-b6c8-4a56-80fc-7c3b8068b884"><image width="200px" src="https://github.com/ankidroid/Anki-Android/assets/92206575/5e873fbe-d757-4ced-8440-30bda39d39fa">

**Comment by BrayanDSO** [comment]
> It does, if the following is what you mean.

It means automatically changing the language when the input box is selected
