### ISSUE TITLE
[BUG]: Ankidroid sync wipes saved search changes

### ISSUE THREAD

**Issue by amliddy** [ankidroid/Anki-Android#14186]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Synchronise ankidroid with web. 

### Expected behaviour

Ankidroid should check saved searches synced to web and if web versions are newer download/sync to ankidroid.

### Actual behaviour

When the latest ankidroid syncs to the cloud it always overwrites the saved searches with those stored in ankidroid regardless of the modification date/time.

So if you make changes to saved searches on the desktop and sync the changes are wiped out by ankidroid when it syncs next.

Bug only present in the new heavily revised Ankidroid, worked perfectly in earlier versions.

### Debug info

```text
Ankidroid 2.16.2
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
I've tested it and can't see this bug with the latest alpha.
If you still see this when 2.19(might worth checking 2.18 as well) is released please leave a comment to reopen.
