### ISSUE TITLE
Crash when whiteboard is on (on a GalaxyTab S 8.4.)

### ISSUE THREAD

**Issue by Negirno** [ankidroid/Anki-Android#14199]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Tapping on a deck having whiteboard enabled or enabling whiteboard while in a deck.

### Expected behaviour

The whiteboard to be working on this tablet.

### Actual behaviour

Tap "learn on a deck", if whiteboard mode is on, it crashes immediately, if not then enabling the feature crashes the app.
Since the whiteboard mode can't be turned off elsewhere in the app, the only way to make the deck(s) work again is to delete the app's configuration settings in the Android application manager.

### Debug info

```text
AnkiDroid Version = 2.16.2

Android Version = 6.0.1

ProductFlavor = play

Manufacturer = samsung

Model = SM-T700

Hardware = universal5420

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0.1; SM-T700 Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Safari/537.36

ACRA UUID = edbfba6c-8337-4e09-98dd-58f5feb48d2f

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
Thanks for the bug report, I created a fix which will be available in the next release.
