### ISSUE TITLE
Deck Options: White screen flicker in night mode

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#14194]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Turn on the night mode on your phone
2. Turn on the new backend
3. Open a deck options.

### Expected behaviour

The deck picker or the deck overview is replaced by the deck option screen or a dark screen appears before the deck option loads.

### Actual behaviour

A white screen appears before the deck option loads.

![Screenshot_20230806_053632_AnkiDroidA](https://github.com/ankidroid/Anki-Android/assets/10192661/cf45ac80-e92a-46a4-9d76-fbf407ade1c7)

### Debug info

```text
AnkiDroid Version = 2.16.2

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.138 Mobile Safari/537.36

ACRA UUID = 7ed5121d-d5f6-484c-a729-72c1f012dc72

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
Reproduced

**Comment by BrayanDSO** [comment]
I'll try to fix it in 2.17 together with matching the page colors with the current theme

**Comment by dae** [comment]
You can solve this by hiding the webview until the page has fully loaded, and then revealing it.

**Comment by jeremyxarcher** [comment]
@dae 

I took a look at doing this, I can't say I'm an expert, but it seems the white screen appears after the webview is fully loaded. I tried using onLoadResource to control the behavior to no avail.

**Comment by dae** [comment]
It should be the correct color after anki.setupDeckOptions() has been called and has returned

**Comment by jeremyxarcher** [comment]
Yeah I'm not sure what's going on there to be honest. I don't know how to debug through to the js script execution, but it seems like something in there is setting the background color to white just before the deckoptions are loaded.

**Comment by dae** [comment]
Before? I'm suggesting the webview is only revealed after they're loaded.

**Comment by jeremyxarcher** [comment]
When I tried to implement onResourceLoaded to control this behavior the webview was considered fully loaded, but the white screen still appeared before deckoptions.

Maybe it has to do with something in the anki.setupDeckOptions()?

**Comment by dae** [comment]
You should be able to accomplish it by using the callback from evaluateJavascript()

**Comment by jeremyxarcher** [comment]
I'll take a stab at it later today.

**Comment by jeremyxarcher** [comment]
I tried loading various URLs directly with the web view and got mixed results on whether the screen flashed white before loading the site. When loading on the Desktop app, the screen flashes black before loading the deckoptions.

**Comment by BrayanDSO** [comment]
> You can solve this by hiding the webview until the page has fully loaded, and then revealing it

AFAIU, that's what the current code does (or what it should do)
