### ISSUE TITLE
[BUG]: Time axis in statistics shows non-integers

### ISSUE THREAD

**Issue by peterj71** [ankidroid/Anki-Android#14193]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Open statistics view

### Expected behaviour

Time axis markers should show days as integers

### Actual behaviour

Time axis markers used to be integral, in month view view they are now non-integral divisions of 31 days. Would be better if imtegral divisions of 30 days, with day 31 a hangover after day 30 as before. Screenshots below show issue more clearly...

### Debug info

```text
2.16.2
```

### (Optional) Anything else you want to share?

![23-08-06-10-27-38-237_deco](https://github.com/ankidroid/Anki-Android/assets/15965443/1e72f253-80ad-42ca-b46a-3b58b8ed9e3d)
![23-08-06-10-26-46-784_deco](https://github.com/ankidroid/Anki-Android/assets/15965443/79f91dc1-6206-4f4c-834a-5e8ce15a9c97)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
This statistics screen will be replaced by the same of Anki desktop in 2.17, so I'll close this issue. Thanks for the report anyway though
