### ISSUE TITLE
Is v3 stable enough to be used as of Ankidroid 2.16.2? 

### ISSUE THREAD

**Issue by salmanuc** [ankidroid/Anki-Android#14192]
Is v3 stable enough to be used as of Ankidroid 2.16.2? What kind of corruption can it cause?

**Comment by doozan** [comment]
See [V3 Scheduler FAQ](https://faqs.ankiweb.net/the-2021-scheduler.html). I don't think anyone has reported issues here stemming from the new backend or scheduler. I've been using it since it was introduced in the early alphas without any problem.

**Comment by david-allison** [comment]
I wrote that message [a couple of years ago](https://github.com/ankidroid/Anki-Android/commit/f1ff0e68). Things are a lot more stable now.

Worst case: Expect a couple of non-fatal error messages when editing a card while reviewing, and a few badly formed error messages when syncing. I don't feel corruption is even slightly likely

**Comment by pkubowicz** [comment]
Despite FAQ saying V2 and V3 can be both used without scheduling issues, I met an issue.

On desktop V3 I fully reviewed deck1. On AnkiDroid V2 I fully reviewed deck2. This caused a new review appearing for deck1 (but deck1 was not touched in AnkiDroid). Syncing caused the extra review to appear on desktop as well. It was card I already answered that day on desktop.

So now I am using V3 in both places.
