### ISSUE TITLE
Change the color of the Android bottom navigation bar to match the Ankidroid answer bar

### ISSUE THREAD

**Issue by Rahey94** [ankidroid/Anki-Android#14209]
I've noticed that in Ankidroid, the color of the bottom navigation bar doesn't match the color of the "show answer" bar, as shown below (it's a bit hard to see here, because it's white):

![image](https://github.com/ankidroid/Anki-Android/assets/54212141/05aa9f1f-426c-428b-b574-5f9b4aa692ed)

This obviously isn't a huge problem, but it would be nice if the color matched, as it tends to on other apps.

Thanks all,

Rahey94

**Comment by SaketKaswa20** [comment]
I would like to work on this.

**Comment by SaketKaswa20** [comment]
Thank you so much!

**Comment by SaketKaswa20** [comment]
Need Some Guidance!
Went through the code base and found out that the customization of 'Show answer' is linked to flashcard_potrait.xml but I am unable to find it. Went through an issue which has solved one issue which included some changes in flashcard_potrait.xml, I went through the same path mentioned in that but still couldn't find it.

**Comment by david-allison** [comment]
I'd look to the button and see that it's using `hardButtonRef` as the background: 

https://github.com/ankidroid/Anki-Android/blob/bb94700f7ca9a64347f590fd96d3fce86f4a3703/AnkiDroid/src/main/res/layout/reviewer_answer_buttons.xml#L198-L207

I then test by changing it on `theme_light.xml`

<img width="758" alt="Screenshot 2023-08-30 at 00 55 46" src="https://github.com/ankidroid/Anki-Android/assets/62114487/01b76579-0d22-4bc5-9d73-0164a6bf20ea">

and that seems to be the reference to the color that you need

**Comment by SaketKaswa20** [comment]
Thanks!
Will go through it.

**Comment by SaketKaswa20** [comment]
Can you guide me more, the reference colour thing I got but confused how to actually apply it. It would be great if someone can guide me. I am really interested to solve this issue.

**Comment by neeldoshii** [comment]
Can I work on this issue? @david-allison

**Comment by david-allison** [comment]
@neeldoshii sure!
