### ISSUE TITLE
Return of night mode checkbox in main menu

### ISSUE THREAD

**Issue by JhonnySalles** [ankidroid/Anki-Android#14200]
**Is your feature request related to a problem? Please describe.**
In this new version, the night mode checkbox was removed from the main screen, this field was very helpful for studying during the day and night, where you could easily change the appearance and avoid straining your eyes in the study.
Apparently the button was removed and now it is necessary to go to the settings.

**Describe the solution you'd like**
I need the checkbox in the menu be returned to be added to the menu, as it was more practical previously.

**Describe alternatives you've considered**
Go to the menu and make the change, but every time you need to enter 3 menus until you reach the theme field.

Another possibility was to go back to the version, but I will not do that because the media were migrated and it would be necessary to download them again.

**Additional context**
New updated version on google play
![image](https://github.com/ankidroid/Anki-Android/assets/43912638/6d9fdd21-1c37-43e0-b5f5-9f5ac0ef3251)

Old version with night mode button.
![image](https://github.com/ankidroid/Anki-Android/assets/43912638/e3c5ccf8-400c-48a8-ad92-90dc08e49aa8)

**Comment by BrayanDSO** [comment]
The initial option would be choosing `Follow system` if your Android version supports it.

Otherwise, I'm sorry but as a design decision, having a setting in two places can be confusing, and most people don't go switching themes back and forth. In your case, since this is an once in a day change, two extra taps aren't that bad.

**Comment by JhonnySalles** [comment]
No problem, I'll be looking for another way to keep the themes switching, perhaps a suggestion that was raised earlier of having Android change the theme at a certain time of day.

This is the only app I use every day, I really appreciate all the work done on it.
