### ISSUE TITLE
How to get rid of all the <> codes in the Edit note section?

### ISSUE THREAD

**Issue by tndk323** [ankidroid/Anki-Android#14210]
When I go to the Edit note for a card, I've noticed that there are always things like <>, <>, etc. I know that they're their when I bold words, go to the next line, and so on, but is there a way to see just the texts and images itself without all these codes when editing? I know nothing about coding, unfortunately, and I don’t know if this is something that can be resolved. 🥲 Thank you all!!

**Comment by lukstbit** [comment]
> but is there a way to see just the texts and images itself without all these codes when editing?

Unfortunately, no.
What you're asking is a WYSIWYG (what you see is what you get) editor and AnkiDroid doesn't have one implemented(but is available on the desktop app(editing/creating cards is easier on desktop in general)). I was planing to maybe trying to implement this but it's not going to happen in the immediate future(meaning the next major 1-2 releases of the app).

**Comment by BrayanDSO** [comment]
Apparently, the desktop's editor may be ported to mobile clients, so things should be easier when it happens. ref: https://forums.ankiweb.net/t/move-cursor-to-end-of-field-when-focusing-with-tab-button-in-external-keyboard/32641/2

**Comment by tndk323** [comment]
Oh, I see! Thank you all for responding!
