### ISSUE TITLE
[BUG]: Since the 2.16.2 update I can't export any deck anymore

### ISSUE THREAD

**Issue by DonutsFactor-e** [ankidroid/Anki-Android#14217]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

I try to export a deck from AnkiDroid as I always did but it doesn't work.
![Screenshot_2023-08-10-16-46-38-859_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/141972834/7d00533e-8639-4436-9d55-2b8d9b1ec159)

### Expected behaviour

A .apkg file should have been created in my files.

### Actual behaviour

An error message.

### Debug info

```text
AnkiDroid 2.16.2
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, thanks for the report. 

I suspect that this is due to the deck name. Could you go to "rename deck", copy the full deck name, and provide it as a comment on this issue.

Thanks!

**Comment by david-allison** [comment]
Fixed in https://github.com/ankidroid/Anki-Android/pull/14195
