### ISSUE TITLE
[Regression] Inability to Save with First Field Empty

### ISSUE THREAD

**Issue by MarkusJLechner** [ankidroid/Anki-Android#14211]
**Background:**
I use the Akebi Android app to generate notes directly to Anki and have added around 5k notes this way. The important details are pre-filled, and I occasionally add extra context. Not all cards need this additional context.

**Problem:**
Since the latest update, if the first field is empty, saving is blocked. I've resorted to entering a blank space as a workaround.

**Suggestion:**
Allow users to define "required" fields for each deck. Mandating the first field be filled doesn't always provide added value.

---

###### Reproduction Steps

1. Edit note
2. Ensure you have multiple fields
3. Leave the first field empty
4. Confirm

###### Expected Result
Like before, it was possible to confirm with empty fields.

Maybe a validation that at least 1 field MUST be filled, as empty notes would make trouble

###### Actual Result
<img width="230px" src="https://github.com/ankidroid/Anki-Android/assets/48199873/170a0e26-fe88-49e3-80b6-9e5aedb3d883"/>

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
> Maybe a validation that at least 1 field MUST be filled, as empty notes would make trouble

👍

**Comment by pratyaksh1610** [comment]
working on it.

**Comment by BrayanDSO** [comment]
Good point

**Comment by lukstbit** [comment]
> In AnkiDroid, was this change made because of the uniqueness check?

I'm not the person that implemented it but I can say that we strive to replicate the behavior of the desktop app.

> Entering empty spaces should also be considered an Empty Field, as uniqueness is not guaranteed.

Yes, that's a bug.
