### ISSUE TITLE
JS API should probably be asynchronous

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#14226]
The JS API is currently synchronous, and I think it might be a good idea to rethink this before people start using it in earnest. There may be a non-trivial delay between the time a request is made and it can be fulfilled, as another operation may already be running on the collection, and I/O may be slow. While the handler on the Kotlin side is called in a background thread, the JS side will block during that time, so the web interface will appear stuck until the request completes.

One way to resolve this would be to switch from using addJavascriptInterface() to instead defining a promise-based API. The API would internally send a message to the Kotlin side, and then resolve once a reply had been received. https://github.com/ankidroid/Anki-Android/pull/14171 has introduced AnkiServer into the reviewer page to support custom scheduling, and it would probably be simplest to pass the messages back and forth using a post request to the server.

@krmanik thoughts? No rush; I know you're busy at the moment.

**Comment by krmanik** [comment]
I am thinking about moving JS API to backend so that all three clients Anki, AnkiDesktop, AnkiDroid should have access to same API. The promise-based API will solve the issues I will pull the server implementation and try to implement asynchronous implementation.

**Comment by dae** [comment]
I'd actually prefer not to integrate this in the backend/across the clients just yet I'm afraid. Before committing to a shared API, I'd like the proposal to receive careful thought and discussion, such as the security implications of shared decks being able to access these API routines, and exactly how the API should look. Currently there are a few other large projects that I would like to see tackled first, eg AnkiDroid's 2.17 release, more AnkiWeb infrastructure updates, getting the desktop editor working in the mobile clients, rewriting the desktop's deck/study/browse views in Svelte so that we can share more code there too, and maybe integration of FSRS into Anki's core.

**Comment by dae** [comment]
To confirm, did you build the backend from this branch https://github.com/ankidroid/Anki-Android-Backend/pull/294? And then build AnkiDroid from this branch https://github.com/ankidroid/Anki-Android/pull/14171?

**Comment by krmanik** [comment]
I have built successfully using updated branch.

**Comment by krmanik** [comment]
The library is not loaded? I have built it in WSL2 and added path to this. 
```
implementation files("\\\\wsl.localhost\\Ubuntu-20.04\\home\\mani\\Anki-Android-Backend\\rsdroid\\build\\outputs\\aar\\rsdroid-release.aar")
testImplementation files("\\\\wsl.localhost\\Ubuntu-20.04\\home\\mani\\Anki-Android-Backend\\rsdroid-testing\\build\\libs\\rsdroid-testing.jar")
```

```
> Task :AnkiDroid:packageAmazonDebug
There are no .so files available to package in the APK for x86.
```

**Comment by dae** [comment]
I'm confused - why are you using WSL? If you're wanting to test on Windows, you should either build the library on Windows + use it on the Windows Android studio, or build the library inside WSL and use it inside AndroidStudio on WSL. A further complicating factor is it looks like you're using a network path - I don't know if Gradle supports those or not.

**Comment by krmanik** [comment]
Building Anki on Windows quite troublesome, first the storage issues to install Visual Studio and setting up development environment in WSL is easier than windows.

But I will setup environment on windows now.

**Comment by krmanik** [comment]
I have setup environment in windows and the rdroid.dll file built successfully. But still getting this in Anki-Android, is there any additional command needs to run?

```
java.lang.UnsatisfiedLinkError: dlopen failed: library "librsdroid.so" not found
```

**Comment by krmanik** [comment]
No, no trouble, the library loaded now.
