### ISSUE TITLE
Minimal Click Speed - accessibility option for users

### ISSUE THREAD

**Issue by crackychans** [ankidroid/Anki-Android#14229]
Good day everyone,

Requesting a **minimal click speed accessibility option** for users.  
A setting where the user can define the minimal amount of time needed for a screen touch to reveal a card and choose answer options.

**Issue:**
I review Anki while commuting, but bumps on the road and shakiness with my hands causes my finger to hyperclick cards sometimes.  This prematurely shows the answer, or in some cases, spamclicks through the following card... which I don't even get to see!

If there was a way I could define 0.3seconds or 0.5seconds, this would stop the issue.  Being able to choose between a drop down or input one's own desired speed would be really useful!  If the user knows they're going offroad or getting shoved around in a busy transit area (haha), they could increase the time setting.

**Comment by pavreh** [comment]
Some devices, e.g. Samsung or LG, has this function implemented. It is called Ignore repeated touches or Ignore repeated taps. Check the accessibility settings of your device.

**Comment by criticalAY** [comment]
I would look into it

**Comment by criticalAY** [comment]
This would allow the user to define the touch time (screen hold time) before the answer is shown

**Comment by snowtimeglass** [comment]
@crackychans Please let me make sure one thing.
Can't the following feature on the latest version (2.16.2) resolve your issue?

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/3d8209a4-0be5-4272-99fb-effcb959df85" width="500px">

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/b8624098-6703-4977-a29a-efa753c28466" width="320px">

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/305590d2-b451-487c-9e6e-89a35e6f093f" width="320px">

**Comment by criticalAY** [comment]
This enables the answer button after the time period what I did was that the user needs to hold the press the button to show the answer

**Comment by snowtimeglass** [comment]
Ah, thank you. It is a feature in order to prevent not only accidental double (multiple) taps but also an accidental single tap, by requiring somewhat long press. I think I understand now.
