### ISSUE TITLE
[Bug] Bluetooth keyboard or Controller highlights the screen

### ISSUE THREAD

**Issue by MarkusJLechner** [ankidroid/Anki-Android#14224]
###### Reproduction Steps

You can reproduce the problem with the following steps:

**Option 1: Using a Bluetooth Keyboard**
1. Connect a Bluetooth keyboard.
2. Go to the deck.
3. Press space, then 4.

**Option 2: Using an (Xbox) Bluetooth Controller**
1. Connect an (Xbox) Bluetooth controller.
2. Assign a key to a joystick or trigger (seem to always trigger the problem).
3. Go to the deck.
4. Press one of the assigned keys.

###### Expected Result
The screen's brightness/contrast should not change.

###### Actual Result
Instead, the screen appears as though it has been selected or highlighted. This state persists through the cards, and the only ways to fix it are to either exit to the deck overview or close the app altogether. This issue makes using Bluetooth devices unfeasible.

The problem has been around for a while and is a regression issue. Although I can't pinpoint the exact update that caused it, it appeared around the 2.15 life cycle. The temporary solution was to simply avoid using Bluetooth devices.

---

Normal:
![Screenshot_2023-08-14-05-52-30-16_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/48199873/25a41db7-1930-44b8-854a-dc71b2721a0a)

Highlighted
![Screenshot_2023-08-14-05-57-19-65_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/48199873/427720f1-d2d7-4526-ab40-5b21099c9286)
<img src="https://github.com/ankidroid/Anki-Android/assets/48199873/846f8a22-f810-4ab7-811d-4f9947de0c91" width="180">

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by MarkusJLechner** [comment]
Just found the same issue 😅

**Comment by david-allison** [comment]
For posterity:

Duplicate of #14142
