### ISSUE TITLE
[BUG]: {{Tags}} does not render on preview mode from note editing screen

### ISSUE THREAD

**Issue by rudnam** [ankidroid/Anki-Android#14239]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Add {{Tags}} to a note template
2. Tap a note to go to the note editing screen
3. Tap the preview button (eye) at the top right.
4. See that {{Tags}} does not render
5. Exit preview mode and scroll to the bottom and select the card type to go to the card types screen
6. Tap the preview button (eye) at the top right
7. {{Tags}} actually renders as expected

### Expected behaviour

{{Tags}} should render normally on preview mode from the note editing screen

### Actual behaviour

{{Tags}} is missing/not rendering anything on preview mode from the note editing screen

### Debug info

```text
AnkiDroid Version = 2.16.2

Android Version = 12

ProductFlavor = play

Manufacturer = Xiaomi

Model = M2007J20CG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; M2007J20CG Build/SKQ1.211019.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

ACRA UUID = 4769c9c7-5884-45f5-98e3-6de1d52368a8

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
If I don't do it, somebody please remember me to close this when the new template previewer is the default since it fixes that

**Comment by Xenonicus** [comment]
Special field {{Deck}} has the same problem
still searching for solutions
![Screenshot_2024-02-21-09-12-55-323](https://github.com/ankidroid/Anki-Android/assets/160725180/65cc53a9-9fa9-465a-be0a-d1b5fbe10c74)
![Screenshot_2024-02-21-09-10-31-179](https://github.com/ankidroid/Anki-Android/assets/160725180/a1ea6198-2aae-445c-bec9-21ee0f908fc1)

**Comment by david-allison** [comment]
@Xenonicus also on 2.17?

**Comment by Xenonicus** [comment]
Also on v. 2.17 beta 5

**Comment by BrayanDSO** [comment]
also fixed by the new template previewer
