### ISSUE TITLE
[BUG]: Image does not appear completely in Image Occlusion cards

### ISSUE THREAD

**Issue by CamilaCSBomfim** [ankidroid/Anki-Android#14238]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Open an image on max width and max height on Image Occlusion Enhanced card as below:

/* GENERAL CARD STYLE */
body {
margin: 0;
}
.card {
position: absolute;
width: 99%;
height: 99%;
display: -webkit-box;
-webkit-box-align: center;
-webkit-box-pack: center;
-webkit-box-orient: vertical;
}
img {
max-width: 100%;
max-height: 100%;
}
io-footer {
max-width: 100%;
margin-top: 0em;
margin: auto 0.5%;
}
.mobile .card img {
max-width: auto;
max-height: none;
}
.mobile .card {
width: 100%;
height: 100%;
margin: 0 auto;
}
.mobile #content {
margin: 0 auto;
}

/* OCCLUSION CSS START - don't edit this */
#io-overlay {
position:absolute;
top:0;
width:100%;
z-index:3
}

#io-original {
position:relative;
top:0;
width:100%;
z-index:2
}

#io-wrapper {
position:relative;
width: 100%;
}
/* OCCLUSION CSS END */

/* OTHER STYLES */
#io-header{
font-size: 1.1em;
margin-bottom: 0.2em;
}

#io-footer{
max-width: 80%;
margin-left: auto;
margin-right: auto;
margin-top: 0.8em;
font-style: italic;
}

#io-extra-wrapper{
/* the wrapper is needed to center the
left-aligned blocks below it */
width: 80%;
margin-left: auto;
margin-right: auto;
margin-top: 0.5em;
}

#io-extra{
text-align:center;
display: inline-block;
}

.io-extra-entry{
margin-top: 0.8em;
font-size: 0.9em;
text-align:left;
}

.io-field-descr{
margin-bottom: 0.2em;
font-weight: bold;
font-size: 1em;
}

#io-revl-btn {
font-size: 0.5em;
}

/* ADJUSTMENTS FOR MOBILE DEVICES */

.mobile .card, .mobile #content {
font-size: 120%;
margin: 0;
}

.mobile #io-extra-wrapper {
width: 95%;
}

.mobile #io-revl-btn {
font-size: 0.8em;
}

[Anki](https://github.com/ankidroid/Anki-Android/assets/142409890/a8507414-86b7-4d35-9bd5-149f96aeb39e)

### Expected behaviour

In the previous version on Anki, I could see those images completely by scrolling to the side.

### Actual behaviour

The image appears cropped and I can't scroll.

### Debug info

```text
AnkiDroid Version = 2.16.2

Android Version = 8.1.0

ProductFlavor = play

Manufacturer = samsung

Model = SM-G610M

Hardware = samsungexynos7870

Webview User Agent = Mozilla/5.0 (Linux; Android 8.1.0; SM-G610M Build/M1AJQ; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

ACRA UUID = 0bf0bbba-62d9-40eb-be21-99e455cfd3fa

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by CamilaCSBomfim** [comment]
still searching for solutions

**Comment by david-allison** [comment]
Image occlusion should be fixed in the 2.17 alpha series, could you test this when you have a second?

Thanks!

**Comment by CamilaCSBomfim** [comment]
It's not working.

**Comment by david-allison** [comment]
@CamilaCSBomfim Could you provide an export of a sample card and the steps you used to produce it?

**Comment by david-allison** [comment]
No author reply - moving to 2.18

**Comment by CamilaCSBomfim** [comment]
Sorry, I am with a health issue, I will share now.

**Comment by CamilaCSBomfim** [comment]
https://1drv.ms/u/s!AiNICt6wDmpIhtUJvyKpxBOAiEzS5g?e=jgHMVL

It's a normal IO card, I only did the configurations reported on the issue description.

**Comment by david-allison** [comment]
Alpha 12, looks fine to me. Image is scrollable:



![Screenshot 2023-12-19 at 01 49 35](https://github.com/ankidroid/Anki-Android/assets/62114487/46c08158-0a19-405d-87f4-5d0bf4d6aeb0)
![Screenshot 2023-12-19 at 01 49 30](https://github.com/ankidroid/Anki-Android/assets/62114487/4655cf6f-0e0a-45f7-a3dc-23b0f5968401)
