### ISSUE TITLE
Add `Drawing` attachment option and use Android solution to get image from camera or gallery

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14244]
My goal here is to actually remove the screen for choosing from `Camera`, `Gallery` or `Drawing`, which can be done with two tasks:

# 1. Add an attachment menu option for drawing

Which will lead directly to the drawing screen

# 2. Use Android's solution to get image from camera or gallery

This is something done by other apps like Notion, showing a system dialog like this:

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/487d540a-4777-4c10-89cb-312bb56cef5c)

A quick google should lead to how it can be done. Something to test is if this works in the older Android versions we support

**Comment by lukstbit** [comment]
That whole field multimedia attachment(audio/video/image)  needs to be changed. I would say to wait until Damien's PR is merged.

**Comment by david-allison** [comment]
It's been in need of significant work for a long while, agreed on blocking until we're using the new backend + note editor
