### ISSUE TITLE
Group commands by categories

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14242]
Currently we have 39 possible commands in the control preferences (if I counted them right), which is a big number. 

Besides searching, to find a command more easily, I suggest grouping them in some categories, like:

- Answer buttons
    - Show answer
    - Answer button 1
    - Answer button 2
    - ...
- Flags
    - red
    - blue
    - orange
    - ...
- Whiteboard
    - ...
- Current card/note
    - suspend
    - delete
    - bury
    - ...
- Navigation
    - Page up
    - Page down
    - Abort
    - ...
- Misc
    - whatever couldn't be put in any other categories

**Comment by BrayanDSO** [comment]
Implementation-wise, this probably means that the commands shouldn't be created programatically, so it would be nice to add a test to check if all commands were added to the XML

**Comment by RobozinhoD** [comment]
i think im understanding how commands work so i would like to do it
