### ISSUE TITLE
[BUG]: Synchronization problem (media)

### ISSUE THREAD

**Issue by hamedsamie** [ankidroid/Anki-Android#14247]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Hello, 

I have an account of Anki with a couple of the decks and a couple of thousands cards. 

I use Ankidtoid on my Android phone. I use the media fetch at each synchronization. Unfortunately, each time that I use the synchronization, instead of modifying only the modified/added/removed media, it downloads (overwrite) all the media which is very time and data consuming and it is now impossible to work with it. Normally this procedure should be happened only at the first synchronization time.

I have no problems whatsoever with Anki desktop (windows) and Anki Web. 

BTW, I didn't not modified any of the ankidtoid default settings.

I would appreciate if anyone can help me with this issue.

Thanks.

### Expected behaviour

It should synchronized only modified/added/removed media

### Actual behaviour

It overwrites (downloads) all the media from the Anki web

### Debug info

```text
2.16.2
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi thanks for the report! Could you confirm that all the media has been downloaded (& that the media sync completes successfully)?

Could you also fill out the full 'debug info' template from `Settings -> About -> Copy Debug Info`

**Comment by Yoannjap** [comment]
Same issue with my 2.16.3 Ankidroid.

**Comment by david-allison** [comment]
Thanks! Do you have an answer to my question above, @Yoannjap?
