### ISSUE TITLE
Remove `Advanced editor` option from the note editor

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14245]
## **Not accepted yet, up to discussion

After #14181 is merged, its only used will be to have a `Clone from` button, which copies the text from another field to the current one. The reasons I think it should be removed are:

1. Doesn't exist in Anki Desktop and eventually we will start getting the code from there
2. It doesn't fit in an option menu for attachments
3. I believe that most people would try to "clone" a field by copying and pasting, which is a more intuitive action
4. Would remove the awkward behavior of opening the advanced editor when tapping the attachment menu if there is text in the field

**Comment by pratyaksh1610** [comment]
Happy to work on this , if it gets accepted.
