### ISSUE TITLE
Some media files display as blank spaces

### ISSUE THREAD

**Issue by Wyzmic** [ankidroid/Anki-Android#14248]
The first two svg images loaded on the desktop anki properly but they don't seem to want to load on anki mobile, they're just blank spaces and an error appears too. The red media file seems to work just fine, please fix the issue. 
![image](https://github.com/MarvNC/yomichan-dictionaries/assets/72083780/adaa9154-f0da-44c2-9cdb-06a847c69ab6)
![Screenshot 2023-08-17 172452](https://github.com/MarvNC/yomichan-dictionaries/assets/72083780/86de29f5-ae22-4c9b-83a2-1621ea3e5280)
![Screenshot 2023-08-17 171153](https://github.com/MarvNC/yomichan-dictionaries/assets/72083780/a34a9d42-cbd3-464a-9e3f-0c9c178f263f)

**Comment by david-allison** [comment]
It failed to load an image. Could you see if the image is available in your `collection.media` folder?

**Comment by Wyzmic** [comment]
Yes they are in my collection.media folder, if I actually tap the blank spaces, the formatted japanese characters are there, opening in a separate page. If I hold down on them they do appear but they're the same color as the bg, maybe ankidroid doesn't handle these pictures' formats as it does on desktop.
![image](https://github.com/ankidroid/Anki-Android/assets/72083780/da8b3173-56c4-4a92-9f99-a6be34846a64)
![image](https://github.com/ankidroid/Anki-Android/assets/72083780/f3a2e938-9165-40d4-8b97-707f5482fd06)
