### ISSUE TITLE
[Bug]After new Ankidroid update ,The anki doodle cards are not working anymore .The app is showing error .

### ISSUE THREAD

**Issue by mainaloohun** [ankidroid/Anki-Android#14240]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report! 

Could you provide an image of the error, and an export of a sample card so we can reproduce this.

**Comment by Shivendra711** [comment]
Same issue with me as well

**Comment by mainaloohun** [comment]
Well i have move on from there .i am currently using old anki.
So right now i cannot provide
But the error is "media not found"

**Comment by Shivendra711** [comment]
![Screenshot_2023-08-18-12-24-12-294_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/142571642/b961147b-f978-479c-accf-5a46461459f7)
Here is the screenshot

**Comment by david-allison** [comment]
* AnkiDoodle uses the AnkiDroid API to add a note type
* AnkiDoodle manually saves files in `/AnkiDroid/collection.media`
* AnkiDoodle uses the AnkiDroid API to add new notes referencing the saved image
* AnkiDroid no longer stores files in `/AnkiDroid/collection.media`
  * To fix: AnkiDoodle needs to use AnkiDroid's API to add media 

AnkiDoodle needs an update, as we can no longer use the `/AnkiDroid` folder in the `apk` released on the Play Store.

Closing as 'WONTFIX' (we can't perform this change, it must be done via AnkiDoodle)

**Workaround**

For now, downloading the `-full` or `.Parallel.A` apk should restore functionality: https://github.com/ankidroid/Anki-Android/releases/latest
