### ISSUE TITLE
Shortcuts are not standardized according to the Google guidelines

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#14251]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Long tap the app icon > Long tap each shortcut > Drop each shortcut on the home screen

### Expected behaviour

The appearance (e.g. size, background) of shortcuts is harmonize (consistent) with other apps shortcuts.

### Actual behaviour

The appearance of shortcuts isn't harmonize (consistent) with other apps shortcuts.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/97e607c0-f722-4fd6-896f-f40e5e4ae5f6)
`AnkiDroid Version = 2.16.2 / Android Version = 11 / Oppo phone `

The background may be adjusted automatically in newer versions of Android, but the inconsistency of proportion still seems to remain (The inner shapes look a bit too big).
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/6c64c75a-10b1-42db-b59f-0499a19bf211)
`2.16.2 full release from GH. Android 13 Samsung phone`
https://github.com/ankidroid/Anki-Android/issues/14246

### Debug info

```text
AnkiDroid Version = 2.16.2

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

ACRA UUID = 5ba46727-9ddb-47f3-a810-53f66d97a89e

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

There seem to be some guidelines for app shortcuts.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/90388ccb-b0e4-47c1-8951-e2f50ff77232)
https://developer.android.com/develop/ui/views/launch/shortcuts/best-practices
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/c6fe269d-a404-43fb-ad43-1f2f6857a264)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/00bbb9dd-dbfb-4e0a-baab-e951f1cd3351)

I have been trying that for a while.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/63ebebb2-6927-48ea-a13d-aec1c84f9a0d)
sample (system icon is full size in 24x24dp)

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/8132d0ec-e626-4dd8-a01c-d0b6dd6a4fc5)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
I have photoshopped the icons
