### ISSUE TITLE
[feature request] multiple flag colours for one card

### ISSUE THREAD

**Issue by AdiWeit** [ankidroid/Anki-Android#14256]
I use the coloured flags to be able to find card with specific criteria. Sadly, the old flag colour is overwritten by the new one, so I cannot have multiple. For example, I want to mark that I don't understand the solution of the card, but it should also be marked in another colour so I can find it easily to be able to write the note on a piece of paper I am allowed to use in the exam. 

So it would be great to be able to select multiple flags. Clicking the flag could bring up all the flags like it is already, but then you could click on the flags you want to add or remove them by clicking if they are added currently and confirm  your choice with a button. 

I could alternatively use keywords, but adding or deleting them takes more time than just clicking the flag symbole and the flags you want.

**Comment by lukstbit** [comment]
> So it would be great to be able to select multiple flags

I just verified and this isn't possible on Anki desktop either and as we strive to replicate the features available on desktop this will not be implemented in AnkiDroid.

If you think this is a feature worthwhile to add please open a feature request on the [anki repository](https://github.com/ankitects/anki). If it's accepted and implemented we'll eventually implement it. The menu around flagging a card on desktop could be improved as it uses checkboxes to select the flag although it only permits one flag.
