### ISSUE TITLE
Deprecation: compileSdkVersion

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#14258]
https://stackoverflow.com/a/67251145/

> With the new Android Gradle Plugin 7.0.0 (currently 7.0.0-alpha14) you can use:
> 
> * [minSdk](https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/BaseFlavor#minSdk:kotlin.Int) instead of minSdkVersion
> * [targetSdk](https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/ApplicationBaseFlavor#targetsdk) instead of targetSdkVersion
> * [compileSdk](https://developer.android.com/reference/tools/gradle-api/7.0/com/android/build/api/dsl/CommonExtension#compilesdk) instead of compileSdkVersion

`compileSdkVersion` is showing as deprecated. We should fix all at once to be consistent

Blocking this until the following is completed (due to conflicts):

* #14129

**Comment by mikehardy** [comment]
Saw this too :-), happy to see it as a commit on some other PR, it's trivial enough and worked locally (though I haven't PRd it)

**Comment by criticalAY** [comment]
Can we simply update the attributes? I would be happy to update these

**Comment by Aditya13s** [comment]
@david-allison please assign me this issue I want to work on it.

**Comment by david-allison** [comment]
@Aditya13s this is blocked for the next few days, but ok!

**Comment by Aditya13s** [comment]
@david-allison please check this commit.
