### ISSUE TITLE
Remove `Answer recommended (green)` and `Answer better than recomended` commands

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14265]
I asked myself what those did, so I peeked at the code to discover that they are the exact same thing of calling `Answer button 3` and `Answer button 4`, respectively. So they are actually useless.

For reference, AnkiMobile doesn't have those options and instead of `Answer button [x]`, it is phrased as `Answer [again/easy/good/hard]` which IMO is clearer

---
so the task here is:
1. Remove the `Answer recommended (green)` and `Answer better than recomended` commands
2. Move their default commands to `Answer button 3` and `Answer button 4` respectively
3. Upgrade their preference assigned commands to `Answer button 3` and `Answer button 4` respectively

**Comment by david-allison** [comment]
I believe these made sense in SchedV1. Can be removed now.

**Comment by RobozinhoD** [comment]
ill do it
