### ISSUE TITLE
[Bug] Screen Highlights/Darkens with Bluetooth Keyboard or Controller (Regression)

### ISSUE THREAD

**Issue by MarkusJLechner** [ankidroid/Anki-Android#14262]
In update 2.16.3, fix #14231 for issue #14142 was published, altering the behavior of a specific bug. While the highlight color changed from bright to dark, the root problem still persists. Reverting the Pull Request would not be beneficial, as it would not resolve the underlying issue.

###### Reproduction Steps

**Option 1: Using a Bluetooth Keyboard**
1. Connect a Bluetooth keyboard.
2. Go to the deck.
3. Press space, then 4.

**Option 2: Using an (Xbox) Bluetooth Controller**
1. Connect an (Xbox) Bluetooth controller.
2. Assign a key to a joystick or trigger (seem to always trigger the problem).
3. Go to the deck.
4. Press one of the assigned keys.

###### Expected Result
The screen's brightness/contrast should not change.

###### Actual Result
Instead, the screen appears as though it has been selected or highlighted (dark). This state persists through the cards, and the only ways to fix it are to either exit to the deck overview or close the app altogether.

---

Normal:
![Screenshot_2023-08-19-06-56-33-91_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/48199873/2a2d3956-6e0c-493b-b6d8-17432db237d9)

Highlighted
![Screenshot_2023-08-19-06-57-15-07_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/48199873/bd67620b-3842-4c71-9cb5-1b10f945b8ed)

<img src="https://github.com/ankidroid/Anki-Android/assets/48199873/d2c5a90d-1cce-45cd-9679-9275d21cecef" width="180">

---

I have no experience with Android, so I consulted GPT-4 about this issue. My insights may not be of much help, as I'm unfamiliar with the underlying setup, such as the use of WebView or the specific layout causing the problem. Additionally, I am not aware of any potential side effects that may arise from this:
```java
WebView webView = findViewById(R.id.webView);
webView.setFocusable(false);
webView.setFocusableInTouchMode(false);
```
Or
```xml
<resources>
    <style name="ThemeOverlay.DisableKeyboardHighlight" parent="">
        <item name="android:focusable">false</item>
        <item name="android:focusableInTouchMode">false</item>
    </style>
</resources>
```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by AtilioA** [comment]
Same behavior as #14142, but this is much less intrusive. The major problem is risk of regressions

**Comment by sudomain** [comment]
I don't have a solution for this, but I'm commenting to follow the issue. I sporadically experience this screen hightlight when using a keyboard with other apps such as Fennec and NewPipe

**Comment by inherithandle** [comment]
it has been almost a year since this issue was created, but it seems that none of 2.18 beta branches don't contain fix of this issue. and any patch note about 2.18 branches doesn't mention this issue. so i just wanted ask.. by any chance does 2.18 beta branches contain fix of this issue..?

**Comment by david-allison** [comment]
It doesn't
