### ISSUE TITLE
[BUG]: SqliteFailureError when marking cards

### ISSUE THREAD

**Issue by chem-william** [ankidroid/Anki-Android#14269]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

The first card scheduled in the following .apkg should make the app crash (I've zipped the .apkg to be able to upload here on Github):
[adj.zip](https://github.com/ankidroid/Anki-Android/files/12387991/adj.zip)

### Expected behaviour

I expected the cards to be marked without any issue and that they won't make the app crash

### Actual behaviour

Sometimes when marking cards as correct, wrong, etc, I get the following error message:
android.database.sqlite.SQLiteDatabase.CorruptException: error while compiling: "UPDATE cards SET queue = -1, mod = ?, usn = ? WHERE id IN (1688800897180)": DbError { info: "SqliteFailure(Error { code: DatabaseCorrupt, extended_code: 779 }, Some(\"database disk image is malformed\"))", kind: Other }.

When clicking OK and marking the card again, I can see from the counter that it skips it. If a corrupted card is the first in the collection, the app crashes.

### Debug info

```text
AnkiDroid Version = 2.16.2

Android Version = 12

ProductFlavor = play

Manufacturer = Fairphone

Model = FP4

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Pixel 4a Build/QD4A.200805.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.156 Mobile Safari/537.36

ACRA UUID = 5118965c-a011-43a9-a596-0d66cc7584d8

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

I've tried downloading the `collection.anki2´ and running the following commands:
1. `pragma quick_check;` -> returns `ok`
2. `pragma integrity_check;` -> returns `ok`
3. `REINDEX;` -> doesn't change anything when looking at the `diff` before and after
4. `UPDATE cards SET queue = -1, mod = 0, usn = 0 WHERE id IN (1688800897180);` -> returns `Error: stepping, NOT NULL constraint failed: cards.mod (19)`

I've also tried to figure out which cards it is specifically, but as I'm never shown the cards that makes the app crash/give the error, it's very difficult

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Imported the `apkg`, can't reproduce this.

I went through the entire deck selecting 'easy' and nothing occurred.

1. Do you get the same error importing the `apkg` into `Parallel.A`: https://github.com/ankidroid/Anki-Android/releases/latest
2. Is it feasible to share the `collection.anki2` file (your collection data, excluding media).
   3. Make a note of the folder in `Settings -> Advanced -> AnkiDroid Directory`
   4. Inside this folder there should be a `collection.anki2` file
