### ISSUE TITLE
Addition of shake phone gesture for some actions.

### ISSUE THREAD

**Issue by vartult** [ankidroid/Anki-Android#14270]
**Is your feature request related to a problem? Please describe.**
While using the app, I can't skip a question, If I'm so sure about the answer. So we can split this as two problems-

1. Do we really want to make a card skippable.
2. On shaking the phone we can navigate to the next card. (Even if we don't want the card to be skipped I think we should have this feature.)

**Describe the solution you'd like**
So as part of solution we can based on the sensitivity of device's gyroscope as part of gesture settings can give an option to complete this action.

**Describe alternatives you've considered**
None in my mind as of now as not sure if we would really want to make the card skippable.

**Additional context**
NA

**Comment by david-allison** [comment]
I like this, but won't be able to get around to it any time soon

**Comment by mikehardy** [comment]
If someone wanted to take this on, I'd accept a PR that added the Seismic library as a dependency (https://github.com/square/seismic) so that we didn't have to invent a bunch of shake detection code.

Then use it to detect shakes and map that to a gesture

**Comment by neeldoshii** [comment]
Is this issue fixed as the PR is merged? @mikehardy

**Comment by david-allison** [comment]
The PR description states that this is a work in progress, but it looks fairly complete to me

The selection code looks good, needs a test of the detection code in the card viewer
