### ISSUE TITLE
[BUG]: Reviewer activity no longer triggers from external apps

### ISSUE THREAD

**Issue by Wolfbeta** [ankidroid/Anki-Android#14275]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Open Termux
`am start com.ichi2.anki/.Reviewer`

I had a Tasker profile setup that would run this shell command to load the reviewer activity upon disabling my Sleep As Android alarm.

This worked in 2.15.4, but no longer works in 2.16.*. I've downgraded to confirm that it still works there.

### Expected behaviour

Open Review activity directly

### Actual behaviour

Nothing

### Debug info

```text
Ankidroid Version: 2.16.3
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
API 33 changes. 😅

Do either of these work:

* `am start -n com.ichi2.anki/.Reviewer`
* `am start -a android.intent.action.MAIN -n com.ichi2.anki/.Reviewer`

**Comment by Wolfbeta** [comment]
Weirdest thing.

To test your solution, I uninstalled 2.15.4, installed 2.16.3 and ran both of your commands with success. Then tried my original one, also with success.

I checked my other phone which was still on 2.16.3 and the original command still wasn't working. I downgraded, and then upgraded again. And without running your commands it began to work.

**Comment by david-allison** [comment]
Thanks! We're probably not going to be unable to resolve this if reproduction steps aren't provided.

Glad you got the problem resolved! Up to you if you want to close the issue at this point.
