### ISSUE TITLE
Reduce snackbar time in the reviewer

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14278]
**Is your feature request related to a problem? Please describe.**
The snackbar time in the reviewer takes relatively much time when doing actions like undoing, which may be annoying when trying to answer cards

**Describe the solution you'd like**
Reducing the time from the 1500ms (IIRC) of Snackbar.LENGTH_SHORT to something like 600ms

**Comment by soCallmeAdityaKumar** [comment]
@BrayanDSO  I want to work on this
