### ISSUE TITLE
[Bug] Magnifying glass icon for lookup disappeared after 2.16.2

### ISSUE THREAD

**Issue by viivgit** [ankidroid/Anki-Android#14273]
###### Reproduction Steps

1. Have a card open for review
2. Select any item (e.g. a character, a word) by long pressing, and then on the pop up menu selecting 'Copy'
3. Tap anywhere on the card

###### Expected Result
The magnifying glass icon for lookup appears at the top right of the card. (If you press it launches a search for instance in another app of what you selected)

###### Actual Result
The magnifying glass icon does not appear at the top right of the card.

###### Debug info
AnkiDroid Version = 2.16.2

Android Version = 13

ProductFlavor = play

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6a Build/TQ3A.230705.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

ACRA UUID = 4d0e3b24-530f-4fe3-b539-1f87022286e1

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue: **I have found in the manual that this feature might be removed soon in favor of a plugin but I didn't see anything related to that in the recent developments**. I also didn't know you could do plugins yet on Ankidroid.
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
As per discussion on https://github.com/ankidroid/Anki-Android/issues/3896 and linked issues, the feature was removed

The feature saw very little use, its implementation was brittle (and had been for nearly a decade) and Android has moved on with better ways to implement it

I feel it would be much better implemented as a third party app which extends the Android system context menu. This would extend any app/WebView with dictionary lookup, instead of only working with AnkiDroid

Alternately, it'll be a candidate for JS Add-ons, when we get the implementation over the finish line

**Comment by viivgit** [comment]
Ah ok I see, that is disappointing since I was heavily using it (probably 10 times /day) but I guess it was somehow hard to maintain so it had to go.

I have a follow-up question then, to see if there could be a workaround in the meantime:
In Settings->Advanced->Plugins subsection there is 'Third-party API apps', which redirects to a GitHub page where you can see apps that make use of AnkiDroid's API.
The one I was using as a lookup dictionary is _Aedict3 Japanese Dictionary_ (second on that long list), which is actually the first dictionary mentioned in that PR that deleted this function (#8263).
The thing I don't understand then is why when I select a character/word/sentence/whatever, then the ... menu does not show me _Aedict3_ (but does show me other apps that I can export the selected data too, even some unlisted ones like _Yomiwa_, another Japanese dictionary I use). Is it because these other apps expose themselves to the system context menu (and thus that has nothing to do with AnkiDroid)? And the fact that _Aedict3_ is still listed is then because it can _export_ data to AnkiDroid's API still, which has nothing to do with the problem here ?

I am just trying to understand how this lookup feature was working before. Was it hardcoded in AnkiDroid for selected few chosen apps (_Aedict_, leo.org, etc.), or did AnkiDroid expose some feature (now removed) that other apps available on an Android device could tap into, and if yes, how was this different from the regular API access ?

Again, I am just trying to understand to see how I still could get access to that lookup search more easily, or what would be necessary to the _Aedict3_ developer to make this happen (maybe having a system context menu for _Aedict3_ is not hard, I have no idea).
