### ISSUE TITLE
[BUG]: `\texit` and `\emph` not working within `\text` in Mathjax

### ISSUE THREAD

**Issue by MonsterDruide1** [ankidroid/Anki-Android#14287]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Create a card with an inline mathjax block containing some nested `\textit{italic}` or `\emph{other italic}` within `\text{}`
2. View it in AnkiDroid

### Expected behaviour

The text should be displayed in italics, as displayed by LaTeX/Anki on PC

![](https://user-images.githubusercontent.com/26349348/263201148-9936e20b-1456-492d-8a92-b505251d64ca.png)
![](https://user-images.githubusercontent.com/26349348/263202925-3c2d0ce4-9482-47ab-85c4-5e86c55eb359.png)

### Actual behaviour

The tags `\textit{}` and `\emph{}` are displayed without changing how the text inside renders

![](https://user-images.githubusercontent.com/26349348/263202977-5967b32f-e850-4997-ae0a-8f67a33fcbd8.png)

### Debug info

```text
AnkiDroid Version = 2.16.3

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-T870

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-T870 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Safari/537.36

ACRA UUID = 99befa59-db58-4f4e-87e5-dd6edc2b780b

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pavreh** [comment]
I cannot reproduce.

**Comment by david-allison** [comment]
This is what Anki Desktop 2.1.65 shows:

<img width="711" alt="Screenshot 2023-08-24 at 18 39 43" src="https://github.com/ankidroid/Anki-Android/assets/62114487/a4e63cf4-c8d6-41c8-810b-d1a2a7001c8d">

Can't reproduce

**Comment by MonsterDruide1** [comment]
Here's one:
Anki Desktop:
![image](https://github.com/ankidroid/Anki-Android/assets/26349348/3c2d0ce4-9482-47ab-85c4-5e86c55eb359)

Ankidroid:
![image](https://github.com/ankidroid/Anki-Android/assets/26349348/5967b32f-e850-4997-ae0a-8f67a33fcbd8)

So, I'd actually correct my report to "Ankidroid doesn't recognize LaTeX-Tags within `\text{}`-blocks", or something like that.

**Comment by david-allison** [comment]
Thanks, could you edit the main post with updated information?

**Comment by MonsterDruide1** [comment]
Found a bug report in MathJax for this specific scenario:
https://github.com/mathjax/MathJax/issues/2846

**Comment by MonsterDruide1** [comment]
*still searching for solutions*

**Comment by david-allison** [comment]
@MonsterDruide1 Still a problem in 2.17?
