### ISSUE TITLE
Feature Request: Add the "Modify today's review card limit" option in the "Custom study" section.

### ISSUE THREAD

**Issue by laraws** [ankidroid/Anki-Android#14288]
**Is your feature request related to a problem? Please describe.**
Modifying today's review card limit has become overly complicated in the current version. After completing the review cards for the day, I am required to click on 'Study more' to reveal the 'Custom study' option. Additionally, I have to click on 'More' to access the 'Modify today's review card limit' feature. This added complexity contrasts unfavorably with the previous version.

![image](https://github.com/ankidroid/Anki-Android/assets/40230381/4a6f3227-b73b-4e11-9fa0-8ef2104c3b28)

**Describe the solution you'd like**
Add the "Modify today's review card limit" option in the "Custom study" section.

**Describe alternatives you've considered**
Add the "Modify today's review card limit" option in the "Custom study" section.

**Comment by BrayanDSO** [comment]
That option already exists. Probably is about your device screen size, or an old ankidroid version

**Comment by BrayanDSO** [comment]
That option already exists. Probably is about your device screen size, or an old ankidroid version

**Comment by laraws** [comment]
> ankidroid

I have a phone with a screen size of 5.5 inches, and I am using the latest version of AnkiDroid. Could you provide a picture showing the 'Custom study' section with the 'Modify today's review card limit' option?

**Comment by BrayanDSO** [comment]
![Screenshot_20230831_075214_AnkiDSO](https://github.com/ankidroid/Anki-Android/assets/69634269/0f74652f-5833-47d9-8007-af08a93247c3)

**Comment by laraws** [comment]
> ![Screenshot_20230831_075214_AnkiDSO](https://user-images.githubusercontent.com/69634269/264622608-0f74652f-5833-47d9-8007-af08a93247c3.jpg)

Thank you for your reply and the picture.  Why doesn't your 'Custom study' section have a 'More' option? Could it be because my phone screen size is too small?

**Comment by BrayanDSO** [comment]
Gonna reopen this for investigation. My phone screen is 6.1"

**Comment by laraws** [comment]
> Gonna reopen this for investigation. My phone screen is 6.1"

Thank you for promptly reopening the issue. I hope it gets resolved soon.

**Comment by pavreh** [comment]
![Screenshot_20230831-181306_AnkiDroid.jpg](https://github.com/ankidroid/Anki-Android/assets/10192661/53718196-7672-4f5e-bf15-cfa92cbe6f31)

This is 4.7" screen so it is not about the screen size...

**Comment by jazzeps** [comment]
I'm experiencing this issue too but it only happens for me if there are new cards remaining in the deck. If no new cards, then Modify Today's Review Card limit appears. But if there are new cards remaining, then Modify Today's New Card Limit appears and the Review Card Limit option is buried in the More submenu

**Comment by jazzeps** [comment]
This is issue still hasn't been resolved. Per my last comment, when there are still new cards, the review card limit option is buried in the More menu. It should be in the first menu as that is the most used option once finishing a deck. 
![Screenshot_20231207_233713_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/8616458/40a5ab7e-81ae-40e2-8ced-16d560d1603e)
![Screenshot_20231207_233720_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/8616458/7523d151-a0d6-4c75-b006-cd2e1a359fa4)

**Comment by snowtimeglass** [comment]
@laraws  @jazzeps 

>and I am using the latest version of AnkiDroid. 

_Originally posted by @laraws in https://github.com/ankidroid/Anki-Android/issues/14288#issuecomment-1700810212_

Could you confirm and provide the specific version of AnkiDroid which you are using?

**Comment by jazzeps** [comment]
Thank you for the prompt reply. I am using Ankidroid 2.16.5

![Screenshot_20231208_070909_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/8616458/de19e0bd-6cb9-47fb-a4b2-cdc7b1c485e2)

**Comment by mikehardy** [comment]
Can you try a parallel release of our 2.17alpha series? I believe this is one of the screens that has changed quite a bit between 2.16 and 2.17 as we look to expose more of the Desktop UI screens directly https://github.com/ankidroid/Anki-Android/releases
