### ISSUE TITLE
[Bug] CSS template not syncing

### ISSUE THREAD

**Issue by Raptime** [ankidroid/Anki-Android#14289]
###### Reproduction Steps

1. update card templates in Anki desktop (front, back and styling)
2. Sync anki desktop then sync ankidroid
3. open the templates on Ankidroid

###### Expected Result
All templates are synced

###### Actual Result
Only front and back are synced, CSS is not.
Other synced anki desktop correctly sync the CSS
Interestingly, modifying the CSS template in Ankidroid and syncing makes it properly update on Anki desktop. Issue is only from desktop to Ankidroid.

###### Debug info
AnkiDroid Version = 2.16.3
Android Version = 13
ProductFlavor = play
Manufacturer = Google
Model = Pixel 6a
Hardware = bluejay
Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6a Build/TQ3A.230805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36
ACRA UUID = e3b2a415-fc31-4ff9-bfa4-17b20da9f589
New schema = true
Scheduler = std3
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, thanks for the report (and filling out the debug info 💜).

Could you check to see if the CSS is synced to AnkiWeb or not (from a change done using Anki Desktop).

If the CSS changes aren't uploaded, this would be an Anki Desktop issue

**Comment by Raptime** [comment]
Hello,
thanks for your reply!
The CSS is synced to ankiweb and to other anki desktops.
Here I just made a test adding a background color and hiding a div, both web and desktop look alike while ankidroid is missing the last few modifications.
![ankidroid](https://github.com/ankidroid/Anki-Android/assets/4553932/bac42010-5681-412b-9a17-86213ec1824b)
![ankiweb](https://github.com/ankidroid/Anki-Android/assets/4553932/19c8430c-27f4-45eb-be33-077ae1bb2f25)
![ankidesktop](https://github.com/ankidroid/Anki-Android/assets/4553932/bcfb6468-c968-4e46-b02a-4ccbfffd2603)

**Comment by david-allison** [comment]
Note: `New schema = true`. This likely means we'll get it in a patch release to 2.16

**Comment by Raptime** [comment]
Will do, in the meantime I'll just update the css manually on ankidroid, no big deal since I'm not making major changes.
I'm pretty sure I didn't have that issue with 2.16.2 but I cannot say if the issue started right after I got 2.16.3 or not (not really helpful sorry 😅).

**Comment by david-allison** [comment]
Almost certainly introduced somewhere in 2.15 -> 2.16, you've been MORE than helpful, thank you!

**Comment by Raptime** [comment]
looks like it's fixed, I do not have the issue on 2.16.5. 🎉

**Comment by extr15** [comment]
I encountered this problem today on AnkiDroid 2.16.5, and the modified 'Styling' tab's content in the card template from Anki Desktop didn't synchronize to AnkiDroid.
Just pressing 'sync' button from AnkiDroid didn't get the newest modification, but I found that after I killed the AnkiDroid app and opened it again, the modification will be synchroized.

**Comment by E5DR** [comment]
> I encountered this problem today on AnkiDroid 2.16.5, and the modified 'Styling' tab's content in the card template from Anki Desktop didn't synchronize to AnkiDroid. Just pressing 'sync' button from AnkiDroid didn't get the newest modification, but I found that after I killed the AnkiDroid app and opened it again, the modification will be synchroized.

Today I notice this exact behavior, also on AnkiDroid 2.16.5 (Anki version 23.10.1). I added a field did some changes to the backside and CSS which were synchronized as expected. At some point further CSS changes failed to synchronize, even with a forced complete sync (though I cannot say for sure if *only* the CSS stopped synchronizing, since I did not really further modify the html). Restarting the app solved it and all modifications got synchronized with a normal sync.
