### ISSUE TITLE
Align forecast screen vertical lines with count bars

### ISSUE THREAD

**Issue by eaubin** [ankidroid/Anki-Android#14283]
**Is your feature request related to a problem? Please describe.**

The forecast screen changed a while ago so that the vertical lines do not perfectly align with the day bar count. I use the Forecast page to figure out the search filter for custom study sessions (e.g. prop:due=12) and it's a little more difficult to use.

**Describe the solution you'd like**
Align the vertical lines at whole number multiples. For days, vertical lines at 0, 10, 20, 30 instead of 0, 5.x, 10.3, 20.7, 31.

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot_20230822-120730](https://github.com/ankidroid/Anki-Android/assets/450244/0f390e85-0479-4721-af4b-a5cd09146379)

**Comment by david-allison** [comment]
Thanks for the report!

We're going to be deprecating this screen in 2.17 in favour of the unified statistics screen.

This is currently visible if you enable the new backend in the advanced settings.

Closing this as WONTFIX as effort would be better spend ensuring the new backend is stable so the new screen will b available for general release
