### ISSUE TITLE
[Notification button badge not going away]
When syncing the Android app, one needs to do it twice for the badge on the sync button to go away, even though the first sync success is confirmed by a snackbar.

### ISSUE THREAD

**Issue by shining-cat** [ankidroid/Anki-Android#14281]
###### Reproduction Steps

1. Launch Anki droid
2. Do stuff to cause a need for sync (go through some cards for example)
3. Come back to main screen listing decks
4. Sync button would show the red badge
5. Click on sync button to launch a sync
6. Sync success is confirmed by snackbar, but badge on sync button is still here
7. Click again to launch a second sync
8. One sees the same messages and the success snackbar
9. Now the badge is gone on the sync button 

###### Expected Result

The badge should be gone on the first successful attempt. It still being here is confusing and makes one wonder which is right: the "need sync" badge, or the "sync succeeded" snackbar?

###### Actual Result

The badge on the sync button only goes away after the second sync.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, thanks for the report. Please fill in the Debug Information section.

This should be fixed in 2.16.3

**Comment by shining-cat** [comment]
Just noticed this was fixed in the release notes this morning.
Awesome job, cheers!!

**Comment by david-allison** [comment]
Cheers!

Closing as duplicate of #14225
