### ISSUE TITLE
Feature Request: Implement 'User Action' Functionality Similar to AnkiMobile

### ISSUE THREAD

**Issue by huandney** [ankidroid/Anki-Android#14286]
In AnkiMobile (starting from version 2.0.88+), there is a feature that allows users to trigger JavaScript in the review screen. This advanced functionality is especially beneficial for those using shared decks that provide keyboard shortcuts to perform actions, such as revealing a hint or the next cloze deletion. By defining a user action, it's possible to trigger these actions with external devices, like a gamepad, or even by using gestures on the screen.

For instance, in AnkiMobile, if a card template provides a revealNext() function, users can instruct AnkiMobile to call it with the following code:

```
var userJs1 = revealNext;
```

This feature is especially handy for those who have written their own actions or are using certain shared decks/templates that provide these actions.

For more details, please refer to the [AnkiMobile documentation](https://docs.ankimobile.net/study-tools.html). Once on the page, scroll down to the "User Action 1-8" section for specifics.

**Comment by BrayanDSO** [comment]
Implementation should be similar to #10462

**Comment by salmanuc** [comment]
Any idea when this feature will be incorporated? Will it make to 2.17?

**Comment by david-allison** [comment]
Depends on whether anyone submits a PR. Fancy giving it a shot?

Personally: working on getting 2.17 stable, won't have much capacity for enhancements until 2.18

**Comment by salmanuc** [comment]
I don't know anything about coding. If i did, i would have had loved to work on ankidroid.

**Comment by mikehardy** [comment]
@salmanuc then you will just have to wait patiently, accept that there is no progress unless someone comments that they are working on it (so asking will not be helpful, sorry) and also accept that it may simply close out unimplemented. That's the way open source / volunteer projects work

**Comment by AnKingMed** [comment]
I'd be happy to fund this if there's someone interested in doing it

**Comment by BrayanDSO** [comment]
I can do that by the mid of the month

**Comment by beejumm** [comment]
Hey everyone, wanted to ask if there was an update to this?
for AnkiDroid

**Comment by BrayanDSO** [comment]
I forgot this issue. I'll take a look into it in the next couple of weeks

**Comment by beejumm** [comment]
> I forgot this issue. I'll take a look into it in the next couple of weeks

Thanks alright, would be a timesaver 😄

**Comment by beejumm** [comment]
Hey @BrayanDSO
Wanted to ask if there was an update to this?
Specifically related to AnkiDroid

Thank you so much!

**Comment by BrayanDSO** [comment]
Had some personal issues, but I'll start this weekend

**Comment by beejumm** [comment]
Hope you're doing well, and sorry for being annoying 
Thanks so much again

**Comment by BrayanDSO** [comment]
Do you, or anyone else, have a sample deck that uses it to share?

If it has any sensitive content and you don't want to share it publicly, you can send it to my email brayandso.dev@gmail.com

**Comment by salmanuc** [comment]
@BrayanDSO are you asking about anki deck with this reveal all and reveal next feature? If so, would the deck without media suffice?

**Comment by beejumm** [comment]
I've created a sample deck that has a few cards that use the one-by-one cloze reveal

Hope this works; if it doesn't, I'll be happy to help out in any way I can 

Here's the deck:
https://drive.google.com/file/d/1RqYEjuDi6WK2A0GKMHbzT8_TwaEDKYxm/view?usp=drivesdk

**Comment by beejumm** [comment]
Hey @BrayanDSO thanks!

Just something I don't know how to do:
I've downloaded the 2.17.1 update that's been rolled out
But I can't seem to be able to attach a user action to a joystick to be able to use it for the one-by-one type cards

Any idea on how to enable this?

**Comment by david-allison** [comment]
@beejumm could you send a screen recording of what your'e trying?

**Comment by beejumm** [comment]
Sure
https://github.com/ankidroid/Anki-Android/assets/146592804/8939312c-ee8a-436f-8ab3-0a5925bf03de

I've added text in the video to show what I'm trying to do

**Comment by salmanuc** [comment]
@beejumm download "anking notes types easy customization" from anki on addons on pc or mac and then set user action to toggle next cloze
![IMG_20240227_125038.jpg](https://github.com/ankidroid/Anki-Android/assets/138794113/a073552b-6603-4287-ad76-9f75d0533770)

**Comment by beejumm** [comment]
@salmanuc Thanks so much, it's working now
