### ISSUE TITLE
dev: bump Robolectric to sdk=33

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#14297]
> the underlying upstream thing is fixed but I'm fine using API32 for robolectric until upstream fix is released in non-SNAPSHOT form. So the issue is just to remove the robolectric.properties sdk=32 clamp once robolectric releases version n+1

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/14259#issuecomment-1693388242_

**Comment by mikehardy** [comment]
Any robolectric version greater than 4.10.3 (current release) should have the fix.

**Comment by mikehardy** [comment]
Fixed this with #14617
