### ISSUE TITLE
[Bug] java.net.UnknownHostException: Unable to resolve host "sync4.ankiweb.net": No address associated with hostname

### ISSUE THREAD

**Issue by OlegGorod** [ankidroid/Anki-Android#14292]
I open anki on my android and want to sync changes related to ma cards, but getting isue.
`java.net.UnknownHostException: Unable to resolve host "sync4.ankiweb.net": No address associated with hostname `

How I can solve it?

AniDroid 2.15.6
Redmi 3
Android version 5.1.1 LMY47V

**Comment by lukstbit** [comment]
Please try the latest version `2.16.3` and check if you see the same issue.

**Comment by david-allison** [comment]
This is typically a temporary network issue, you should be able to retry to fix it

Closing this preemptively, but feel free to comment if this is a permanent issue rather than a temporary network issue
