### ISSUE TITLE
[BUG]: Reminder notification does not appear for a deck

### ISSUE THREAD

**Issue by DecemberGiraffe** [ankidroid/Anki-Android#14319]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Select a deck and go to 'Deck options'
2. Go to 'Reminders' and set a time and enable notifications
3. No notification appears at the time reminder was set for

### Expected behaviour

A notification to remind user to study deck

### Actual behaviour

No notification appears at the set time. However, when opening the app (e.g. 11pm) past the reminder time (e.g. 9pm), the reminder notification appears.

### Debug info

```text
AnkiDroid Version = 2.16.3

Android Version = 13

ProductFlavor = full

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6a Build/TQ3A.230805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36

ACRA UUID = fa313df2-5057-4aa5-a1c2-181733af0413

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Thanks to all volunteers!

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Reminders are currently broken: https://github.com/ankidroid/Anki-Android/labels/Advanced%20Reminders

Closing as duplicate, please let me know if this is a further regression in 2.16
