### ISSUE TITLE
[Bug] Deleting a deck only deleted the cards

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#14312]
###### Reproduction Steps
⚠️ Unsure if this is reproducible

1. Select a large deck (Arthur's 'theory' deck)
2. Delete
3. Close the app after deletion completes

###### Expected Result

The decks are deleted

###### Actual Result
<img width="382" src="https://github.com/ankidroid/Anki-Android/assets/62114487/caf6314d-3f59-4390-819b-32c6a0f69ffb">

The decks are still there, only with no cards 

###### Debug info

AnkiDroid Version = 2.16.3-debug

Android Version = 13

ProductFlavor = full

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_arm64 Build/TE1A.220922.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 33caaff8-36bc-4ee2-8a0f-413cdbb2b9a1

New schema = false

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by parvinder8** [comment]
can you assign it to me?

**Comment by david-allison** [comment]
Sure, would be great to confirm that you can reproduce this

**Comment by parvinder8** [comment]
yes, I can reproduce this issue. 
for reproducing :
App version - AnkiDroid-2.16.3-full-universal.apk

1 - add large deck 
2 - click delete and close app instantly

**Comment by dae** [comment]
We should get this fixed for free when switching to the new schema. Given that it's relatively harmless, perhaps it's best just to wait?

**Comment by parvinder8** [comment]
yes

> We should get this fixed for free when switching to the new schema. Given that it's relatively harmless, perhaps it's best just to wait?

**Comment by parvinder8** [comment]
actually found new issue, don't know if its known or not 

1 - when you log in on app and go to get shared deck
2 - search deck then it gives log in first error 

expected behaviour - download without login on web if you are logged in on app

actual behaviour - it asks user to log in on web also

**Comment by dae** [comment]
The login inside the app is separate from the website login. To prevent abuse, users need to log in after downloading more than 3 decks in a day. Sync login is not stored very securely, so it would be a security issue if users could login to the website based on their sync credentials.

**Comment by david-allison** [comment]
Deferring this one to 2.17

**Comment by dae** [comment]
Closed by #14171
