### ISSUE TITLE
Anki takes 30+ minutes to synchronize EVERYTIME I open it[Bug]

### ISSUE THREAD

**Issue by samxyx** [ankidroid/Anki-Android#14316]
Needles to say this makes this app unusable.

**Comment by david-allison** [comment]
Hi, could you go through user support on [Reddit](https://www.reddit.com/r/anki)/[Discord](https://discord.gg/qjzcRTx). 

You didn't fill out any of our bug info template, and there's not enough information in this post to help us diagnose this issue
