### ISSUE TITLE
Feature Request: Whiteboard in the preview screen of Card browser

### ISSUE THREAD

**Issue by naong** [ankidroid/Anki-Android#14322]
In general, writing is an effective way to enhance learning.

I'm not using word-based language learning, but rather multi-page study materials. One card contains multiple pages of content, and I'm learning hundreds of cards.

When I study, I write down what I've learned to make it more effective.

I also use Card Browser to find some of the things I've learned in the vast amount of material, but I often find myself studying on the preview screen of Card Browser in addition to just browsing.

This creates a need for Whiteboard on the Card Browser preview screen. However, it's not supported on the Card Browser's Preview screen, so I wrote some code to make it happen.

Pull request: [#14318](https://github.com/ankidroid/Anki-Android/pull/14318)

![whiteboard01](https://github.com/ankidroid/Anki-Android/assets/7389524/550dd568-ba0e-403e-9762-31966423767b)

**Comment by BrayanDSO** [comment]
This begins the discussion of how powerful we want the Previewer to be. If it should just preview cards, or have most of the reviewer functions like burying, deleting, etc. We already allow editing the note, and overall the only downside of adding the other features would be the implementation/maintaining burden.

As of now, adding just the whiteboard is fine IMO

**Comment by naong** [comment]
> This begins the discussion of how powerful we want the Previewer to be. If it should just preview cards, or have most of the reviewer functions like burying, deleting, etc. We already allow editing the note, and overall the only downside of adding the other features would be the implementation/maintaining burden.
> 
> As of now, adding just the whiteboard is fine IMO

I think it's fine that the previewer isn't very powerful, but it needs to be a step up, like a whiteboard.

**Comment by lukstbit** [comment]
I'm against this.

While I understand this feature might be useful for the author it's also a feature for an unusual workflow(learning in the card browser/card browser previewer - I'm not sure we should encourage this) and which is not going to be used by many. So few will use it but the rest of the users will have a slightly more complex/verbose screen(also we'll have more code to maintain). Our users have complained in the reviews about the complexity of the screens and the to many options available and I agree with them.

In the end, it's a previewer with a link to edit the card and I think we should keep this way(simple).

**Comment by BrayanDSO** [comment]
Making the previewer only preview and trying to persist as a "flashcards" app, i.e. most of the learning should be through the reviewer, is pretty valid as well. An alternative is to create a filtered Deck and use the whiteboard there

I'll go with simplicity here and not support it as well.

**Comment by david-allison** [comment]
As above, I'd like to keep the previewer as simple and intuitive as possible. 

In addition: Having cards that big goes against the minimum information principle: https://www.supermemo.com/en/blog/twenty-rules-of-formulating-knowledge

**Comment by naong** [comment]
I currently use Ankidroid very frequently and well.

However, I have been studying it in a form that does not meet `the minimum information principle` that david-allison has provided.

I'm doing memorization, of course, but I'm aiming for a deeper understanding of the material through understanding and repetition, not just memorization.

While `the minimum information principle` can be an effective reference point for learning for the purpose of memorization, the amount of material that goes into meeting this principle - breaking down the material into simple cards - can be overwhelming for someone like me.

And if you want to find out which cards in that material you've studied, and relearn some of it, a filtered Deck isn't enough, because a filtered Deck can be organized by a card's status or tags, but not by its content.

Add to this the advantage of the Card Browser, where you can see all the related cards based on content. Cards searched for a particular content are likely to have connections, and you can learn those connections by lightly studying them in Prewveiw.

Nevertheless, if this is a feature I need just for me, I agree with not including it in the distribution. This is because the feature is already implemented, and I can build it separately for me whenever a new version of Ankidroid is released.

Thank you for your consideration of the feature and for helpful comments.

**Comment by BrayanDSO** [comment]
> because a filtered Deck can be organized by a card's status or tags, but not by its content.

You can create filtered decks based in the same search queries that can be made in the browser. The result should be the same

---

About the minimum information principle, I've used some decks before that have a comprehensive extra field to better explain things and get the big picture and I liked it. I understand the reasonality about making bigger cards with bigger questions and answers as well in order to memorize by having a bigger understanding
