### ISSUE TITLE
request to enhace the ui of the appliation. since the current ui looks so pro\imitive

### ISSUE THREAD

**Issue by CodeXstalker** [ankidroid/Anki-Android#14324]
**Is your feature request related to a problem? Please describe.**
no]

**Describe the solution you'd like**
I will use the material design to enhnace the ui.

**Comment by BrayanDSO** [comment]
Not a new issue. Duplicate of #13878 and similars. Feel free to improve it yourself so it is less "primitive" or otherwise just be patient. We are all volunteers here
