### ISSUE TITLE
Examine codebase for any API <23 comparisons that may be eliminated

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#14338]
A general search for the strings 20, 21, 22, 23, 24 (so any of the variety of arithmetic comparison operators likely operands will show up)
A general search for VERSION_CODES.M LOLLIPOP and N to do the same for the symbol-based API designations

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/14171#discussion_r1307480636_

**Comment by cemsity** [comment]
I will work on this over the weekend.

**Comment by SteelColossus** [comment]
Hi there, can I volunteer to work on this as a first issue?

**Comment by cemsity** [comment]
Made some minor changes in regards to [https://github.com/cemsity/Anki-Android/commit/a7fd837490c153b68b9726bd997989a6a69c8894](Marshmallow).

**Comment by soCallmeAdityaKumar** [comment]
Can i work on this issue
