### ISSUE TITLE
Request to make "Sync" as one of the command mapping controller button options

### ISSUE THREAD

**Issue by tndk323** [ankidroid/Anki-Android#14339]
**Is your feature request related to a problem? Please describe.**
It's not a problem but was wondering if there can be a separate control button for "Sync" instead of just the "Abort Learning and Sync" option we currently have. I like to Sync my cards when I'm in the middle of reviewing a deck just to make sure and I would like to be able to do a gesture or press a button on my game controller without it causing me to go back to the main page each time.

**Describe the solution you'd like**
Ability to make "Sync" as a separate option from "Abort Learning and Sync" and be able to assign a gesture and game controller button for it. Thank you so much!!

**Comment by BrayanDSO** [comment]
Have you enabling auto sync? That would fit your use case and it is automatic.

If you find the sync dialog annoying, ideally we could make it autosync in the background after exiting the app, #12468 (including syncing collection)

If you suddenly need to sync then switch context to another device, `Abort learning and sync` covers it as well.

Given the above and that syncing while reviewing could have a lot of problems, I'm against the feature

**Comment by tndk323** [comment]
Ok I can try that. Thank you!
