### ISSUE TITLE
[Bug]error "sync_write_access_error_on_storage" occurs after sync.

### ISSUE THREAD

**Issue by Admmmmmmin** [ankidroid/Anki-Android#14342]
###### Reproduction Steps

1. sync
2. and then "无法将下载的文件保存到您的存储。要么是存储空间是只读的，要么空间不足。" pop out.

###### Expected Result

Successfully done the sync.

###### Actual Result

Error message.

###### Debug info
Debug info was sent from the app with the message `` error "sync_write_access_error_on_storage" occurs ``

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum 
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by nonenty** [comment]
I encountered the same issue. I found it on 2.13.5, 2.15.4, 2.16.4 and 2.17alpha1. My device is Oneplus 11, running ColorOS 13.0 (based on Android 13). In 2.16.4 and 2.17alpha the app requested the MANAGE_EXTERNAL_STORAGE privilege and I've granted it as mentioned [here](https://developer.android.com/training/data-storage/manage-all-files#all-files-access) but found no luck. The AnkiDroid directory is set as /storage/emulated/0/AnkiDroid.

**Comment by nonenty** [comment]
I've found out what the problem is. I use Nginx as a reverse proxy server to the [sync server](https://docs.ankiweb.net/sync-server.html#with-pip)
The fix is turning off the proxy_redirect and proxy_buffering.
```
  location /sync/ {
    rewrite ^/sync/(.*) /$1 break;
    proxy_pass http://127.0.0.1:18080;
    proxy_redirect off; #ADD
    proxy_buffering off; #ADD
  }
```
When writing downloaded files, ```okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR``` is thrown out here. It has nothing to do with the privilege but with server-side configuration.
https://github.com/ankidroid/Anki-Android/blob/67fd45a351c44c46c844aa35a402b98a2a487f68/AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.kt#L266-L284

**Comment by david-allison** [comment]
The listed code was removed in https://github.com/ankidroid/Anki-Android/pull/14171

Please let us know if this is still a problem
