### ISSUE TITLE
Regression: play tags are now being shown in the browser

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#14353]
Regression: play tags are now being shown in the browser if there is audio in the note:

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/3645bad7-ee9f-4cc1-80ae-88787b6d8483)

This is best solved by integrating #11889

**Comment by mikehardy** [comment]
@david-allison how does #14911 relate to this one? May be a matter of calling the same method you implemented there on q and a prior to sending up to browser layer? Given you're refactoring in there you may be all over this already

**Comment by david-allison** [comment]
I'd prefer to get #11889 in, but the methods on the class that I added are a patch which will work

* #11889

**Comment by mikehardy** [comment]
ok, I posted over there on #11889 looking for status+plans

**Comment by mikehardy** [comment]
Wow. Definitely in progress... 
![image](https://github.com/ankidroid/Anki-Android/assets/782704/1e5c5e52-3ca2-4bdd-af9e-ea362c0196be)

**Comment by david-allison** [comment]
When we need to (when card browser issues are the only blockers) we can fix this without the refactor
