### ISSUE TITLE
Determine which robolectric versions are necessary for AnkiDroid tests

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#14350]
the file `AnkiDroid/roblectricDownloader.gradle` needs an update now that minSdkVersion is 23, but it is unclear which versions are actually used

the way to determine what is in use is to delete the `.m2` directory in your home directory then (warning! will transfer a lot of data...) run `./gradlew jacocoUnitTestReport`, then run `find ~/.m2 | grep robolectric` to determine which of the android API levels were downloaded

This task should be done after #14171 is merged, this description of how to determine what is needed should be added to robolectricDownloader.gradle, and the file itself should be updated with the necessary files

Thanks!

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/14171#discussion_r1309486144_

**Comment by SteelColossus** [comment]
I am planning to work on this as a first time contributor.
