### ISSUE TITLE
Undone "last review" toast message blocks some contents of a card and distracts attention

### ISSUE THREAD

**Issue by yoshiotobe** [ankidroid/Anki-Android#14359]
When I use an undo action, Undone "last review" toast message shows up.
It blocks some contents of a card and distracts my attention.
Before I upgraded to the version 2.16.4, it was not shown and fine without it.
Is there any way to disable the toast message or could you add option to disable it?

**Comment by voidplayer** [comment]
Sync toast also blocks the numbers on bottom. i use those number to check i didnt forget to sync on the other devices and dont remember to check until is blocked by toast

Not too bad, but I agree is quite annoying toast

**Comment by BrayanDSO** [comment]
I believe that making the time shorter, like 500ms (currently is 1500, IIRC) would balance the desire of adding feedback to the action while interfering less with reviewing. Would that be okay with you?

**Comment by BrayanDSO** [comment]
> Sync toast also blocks the numbers on bottom

Here they are shown above it. Can't reproduce it

**Comment by voidplayer** [comment]
It my case is just a middle annoyance. Probably less time will be less annoying

> Here they are shown above it. Can't reproduce it

I guess it depends on the size of the screen, because it only blocks it partially. Numbers font being that small i can see not being blocked in a bigger screen

**Comment by BrayanDSO** [comment]
The thing is that it shouldn't block the numbers at all. Needs investigation

**Comment by voidplayer** [comment]
![image](https://github.com/ankidroid/Anki-Android/assets/4019910/54feb882-23c2-4321-8de5-c9d3512ef897)

**Comment by BrayanDSO** [comment]
It may not be clear what exactly is being undone. Undoing things like answers are clear because the whole screen reloads, but tags, reschedules or flags may be undone without any visual changes. Also, in slower phones and with huge collections, it may take some time to undo, so the user can't be sure if they action was undone without feedback. So I do think that the feedback is necessary.

I was annoyed the same way as you were by the snackbar showing up, but after making the time shorter (I changed the code to do it), it doesn't annoy me at all anymore.

**Comment by voidplayer** [comment]
Lets see if the experience improves with less time

I agree the feedback is needed but tbh i was annoyed by this toast since it was first introduced

It looks very slick and modern compared with the old one but being floaty makes it to always be in the way of something

**Comment by yoshiotobe** [comment]
Thank you for the explanation and the quick fix.
I understood why it's necessary.
Maybe a lighter color and stronger opacity like the one used for "initializing tts..." would be less annoying?
I will wait for the fixed version.
