### ISSUE TITLE
[Bug] 2.16.3 Rebuild after empty doesn't refresh the deck list view

### ISSUE THREAD

**Issue by david-resnick** [ankidroid/Anki-Android#14352]
###### Reproduction Steps

1. Rebuild filtered deck (deck list view is refreshed)
2. Study new cards not in filtered deck (probably unrelated)
3. Empty filtered deck (list view is refreshed)
4. Rebuild filtered deck -- deck list view shows the filtered deck as still empty

This is a recent regression. A similar refresh bug was fixed since this broke in the recent big release.

###### Expected Result
In deck list view, the correct number of new cards for the filtered deck.

###### Actual Result
The filtered deck is shown as having 0 due or new cards. 

###### Debug info
AnkiDroid Version = 2.16.3

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-G996B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G996B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.168 Mobile Safari/537.36

ACRA UUID = e6ad4c07-d626-477e-9f99-805c3e063440

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-resnick** [comment]
If someone could point out where to look in the code for this problem, I might be able to take a look myself.

**Comment by lukstbit** [comment]
@david-resnick Duplicate with #14285(which was fixed for 2.16.4)?

**Comment by david-resnick** [comment]
It looks like it might be. I'll wait to check after 2.16.4 is released.

**Comment by lukstbit** [comment]
2.16.4 is already released and should be available as an update.
