### ISSUE TITLE
[BUG]: Loading the deck count and toolbar takes more time if internet is enabled with the new backend

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14355]
Haven't tested with the legacy backend, since it will be removed very soon

My guess is that the sync status fetching is happening before the UI update and since `withCol` works with a queue, the UI update will always have to wait for it

2.16.4, new backend enabled, Android 13

**Comment by dae** [comment]
This could be solved by updating SyncStatus.kt to call CollectionManager.getBackend().syncStatus() instead of withCol { syncStatus() }, but the try {} block should handle any error, as it will fail if the user does something like a .colpkg import just before the status is refreshed.
