### ISSUE TITLE
Backup options need updating

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#14366]
Currently when visiting the preferences>advanced screen, you can only choose a single number for backups, which is not how the backend code works. There are separate settings for weeks/months, which appear to have already been implemented in BackupsLimitPresenter(), and need to be hooked up.

**Comment by pratyaksh1610** [comment]
Can i work on it ?

**Comment by dae** [comment]
As a general rule, you can work on anything without permission if someone else has not already said they're working on it.

**Comment by pratyaksh1610** [comment]
In this we need to remove max backups and add the weekly/monthly/daily backups .

**Comment by pavreh** [comment]
Duplicate of #13121

**Comment by lukstbit** [comment]
@pratyaksh1610 Are you still working on this?
