### ISSUE TITLE
Controlls - Allowing same button/gesture for "show answer" and other answer buttons

### ISSUE THREAD

**Issue by RoseWebb** [ankidroid/Anki-Android#14367]
Currently, AnkiDroid allows only to use each button / gesture to do one action. However, since show answer and answer buttons are in deferment pages, it seems to be doable and will not cause conflict.

Example: 
using the right swap to "show answer" and then again to click on "good". So the when the user uses the right swap gesture in the first time, it will show the answer. Then again when the user uses the same gesture (right swap) it will click on the good answer button.

**Comment by BrayanDSO** [comment]
I'm going to join this with #13816
