### ISSUE TITLE
[BUG]: Sync does not complete if I do anything while syncing 

### ISSUE THREAD

**Issue by dylley** [ankidroid/Anki-Android#14375]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Ever since the update to 2.16, the sync gets stuck or the sync window disappears without completing the sync if I do anything but let my phone sit undisturbed until completion. Hitting the home button or switching to another app usually makes the window disappear and the sync does not complete. Rotating my screen makes the sync get stuck and I have to cancel the sync and resync.

### Expected behaviour

The sync should continue without issue in the background or despite a screen rotation.

### Actual behaviour

The sync stops, either with a dozen sync window or the window disappears.

### Debug info

```text
AnkiDroid Version = 2.16.4 (67fd45a351c44c46c844aa35a402b98a2a487f68)

Android Version = 11

ProductFlavor = play

Manufacturer = motorola

Model = moto g power

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; moto g power Build/RPMS31.Q1-54-13.3-10; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36

ACRA UUID = 2a91b6d4-bf73-45bb-ab4a-27d5a83e5d84

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by jazzeps** [comment]
+1
I can confirm that I am experiencing this bug too

**Comment by mikehardy** [comment]
I can no longer reproduce this on the all-new sync code in 2.17 with the new backend - built from commit e04d9be7cdab47044057ddd9f07ef634bb99e382 (current as of this typing)

Previously I know this (and a few things like this were happening) but with the swap to the anki desktop sync code I think it is working well now - you can try the alphas from https://github.com/ankidroid/Anki-Android/releases if this is bothersome before we release 2.17
