### ISSUE TITLE
Option to view Card Info from the Reviewer 

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14397]
**Is your feature request related to a problem? Please describe.**
Multiple times, while reviewing, I want to see the review history of a card before deciding what to do with it. This is particularly important when I encounter cards that are poorly formulated. But, the reviewer in AnkiDroid doesn't provide the option to see the card info (unlike Anki Desktop). So, I have to copy the question, open the browser, search for the question and then see the card info.

**Describe the solution you'd like**
All this hassle of searching for the card in the browser could be avoided if the menu of the reviewer had an option to view the card info (just like Anki Desktop).

**Describe alternatives you've considered**

**Additional context**

**Comment by BrayanDSO** [comment]
There is one. Settings > Appearance > App bar buttons > Card info

**Comment by BrayanDSO** [comment]
![Screenshot_20230905_155057_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/69634269/c8a0f497-ab1e-40f3-abc8-3eacaecb10b4)

**Comment by Pr0pHesyer** [comment]
Please set it to enable in menu by default

**Comment by david-allison** [comment]
We've already got too many options on that menu, it's likely best left as an advanced feature, especially as it's available in the Browser
