### ISSUE TITLE
[BUG]: no option for Remote Debugging via USB

### ISSUE THREAD

**Issue by shnurks** [ankidroid/Anki-Android#14395]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Trying to inspect the page as per the [Development Guide](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection) is not possible. However, I can inspect other apps such as chrome on my device.
### Expected behaviour

remote debugging possible

### Actual behaviour

does not appear in the devtools

### Debug info

```text
AnkiDroid Version = 2.16.4 (67fd45a351c44c46c844aa35a402b98a2a487f68)

Android Version = 10

ProductFlavor = play

Manufacturer = Xiaomi

Model = MI 8

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; MI 8 Build/QKQ1.190828.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36

ACRA UUID = 5ce14bf4-93a5-4688-b6ec-72f8847281f3

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Used to work fine a while ago when the option to enable remote debugging was still in the settings.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
It works here

**Comment by david-allison** [comment]
Also works here.

I would note that the documentation is out of date:

* About AnkiDroid
* Tap on the AnkiDroid logo 6 times
* You'll find the setting in the Developer Options

**Comment by BrayanDSO** [comment]
> I would note that the [documentation](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection) is out of date:

Where exactly?

**Comment by david-allison** [comment]
Documentation was listing the 'legacy' location first, I've updated it
