### ISSUE TITLE
[BUG]: problem displaying an answer with a shared deck and ankidroid

### ISSUE THREAD

**Issue by jpggithub** [ankidroid/Anki-Android#14391]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Download https://ankiweb.net/shared/info/1491161675

Use it.

The displayed answer are incomplete and inconsistent:

1. The type of the chord is not displayed as attended.
2. The name of the deck appears on all the answers.

### Expected behaviour

The displayed answer should be root note + type of the chord as configured in the format of the cards in the deck.

The name of the deck should not appear in the answers.

### Actual behaviour

The displayed answers on ankidroid didn't correspond to the template of the cards.
The format of the answer is designed to display the root note and the type of the chord. It works well  on ankiweb.net. But the displayed answer on ankidroid shows the root note and... the name of the deck! So the type of the chords are not displayed and the name of the deck is useless at this place.

### Debug info

```text
Ankidroid 2.16.4 (f-droid)

I use ankidroid with several shared decks for a long time. I never had this problem with another deck.

I tried to reinstall ankidroid and completly download again the deck. The bug is still there.

I don't know how to solve this problem.
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pavreh** [comment]
Use the new backend in advanced settings.  It works for me.

**Comment by jpggithub** [comment]
Thank you, it works!
But Ankidroid indicates that this choice could corrupt the database. Not very cool! 😬

**Comment by pavreh** [comment]
Don't worry, the new backend is the same backend which Anki uses. It will be default in Ankidroid 2.17.

**Comment by jpggithub** [comment]
Thank you!
