### ISSUE TITLE
Cannot display back[Bug]

### ISSUE THREAD

**Issue by plusjhjhjh** [ankidroid/Anki-Android#14400]
###### Reproduction Steps

1. use this card
2. answer
3. click back card

###### Expected Result
![Screenshot_20230906_091226](https://github.com/ankidroid/Anki-Android/assets/72897552/23210ef3-f6f7-4a30-af27-487023fdbc6c)

![Screenshot_20230906_091247](https://github.com/ankidroid/Anki-Android/assets/72897552/c0b0da8e-f803-4e4e-834d-4668a4fbf7a7)

###### Actual Result
![Screenshot_20230906_090044](https://github.com/ankidroid/Anki-Android/assets/72897552/59d23df9-cdc6-45a8-8f42-a4cc862f5529)

![Screenshot_20230906_090049](https://github.com/ankidroid/Anki-Android/assets/72897552/b97cc248-60ae-4b17-81f6-3126c8e7ccba)
/

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
I guess that this is a duplicate of #4828
