### ISSUE TITLE
Show snackbar above FAB in the deck picker instead of below

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14403]
Material guidelines are against animating the FAB together with the snackbar:

https://m3.material.io/components/snackbar/guidelines#84cd5bb6-354f-4fd0-bdd9-daf9684ba4bf

And actually suggest showing it on top of the snackbar:

https://m3.material.io/components/snackbar/guidelines#f762d356-69a1-402c-ab69-3621c23f91d2

---
This mainly avoids misclicking the FAB when a snackbar is shown

**Comment by DevP-ai** [comment]
Can you please assign me this task?? I want to work on it

**Comment by BrayanDSO** [comment]
Go for it
