### ISSUE TITLE
[BUG]: first time entering a deck  "focus type in answer" is not honored

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#14404]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

uncheck `settings> advanced> workarounds > focus type in answer`

go to a deck with a type in field, first time keyboard shows. After you dismiss it, it wont show again

### Expected behaviour

I would expect to never show the keyboard unless i press on the field

### Actual behaviour

keyboard shows

### Debug info

```text
AnkiDroid Version = 2.16.4
Android Version = 12
ProductFlavor = full
Hardware = qcom
New schema = false
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
We've got a lot of external pressure to get [2.17 out without regressions](https://github.com/ankidroid/Anki-Android/milestone/51).

If someone submits a PR, it'll almost certainly be accepted, otherwise this will be prioritised lower than the tasks in the 2.17 milestone

Thanks for bumping!

**Comment by parthn2** [comment]
I will try to look into this issue!

**Comment by SanjaySargam** [comment]
Actual Behaviour: - 
keyboard does not show but when I press on the field for the first time then it remains showing everytime
