### ISSUE TITLE
[Bug] Sort of. Make One-Way Sync Prompt consistent with Anki Desktop and AnkiMobile

### ISSUE THREAD

**Issue by daddydave** [ankidroid/Anki-Android#14402]
###### Reproduction Steps

1.  Force a one-way sync on AnkiDroid, or perform an action that requires one
2.  Do a manual sync and observe the one-way sync prompt

###### Expected Result
A one-way sync prompt with buttons similar to what appears on Anki Desktop:
Upload to AnkiWeb
Download to AnkiWeb

This would allow Anki and AnkiDroid newcomers to quickly conceptualize uploading to AnkiWeb on one side and downloading from AnkiWeb on the other side. It also would make it consistent with AnkiMobile as per my understanding, not owning an Apple device. Even the Anki Desktop documentation says things such as "Next, if one of your devices is a mobile device, synchronize it first. If there’s a conflict, choose "upload" to overwrite any existing data on AnkiWeb with the data from your mobile device." So it is expected the mobile device, be it iOS or Android will have an Upload and Download buttons when they get this prompt.

###### Actual Result
A one-way sync prompt with these buttons:
AnkiWeb
Android

See Anki Desktop and AnkiDroid prompts together for comparison:

![Anki_Desktop_prompt](https://github.com/ankidroid/Anki-Android/assets/9300442/a78b4f6b-03ac-44a3-8c33-af6a002e8731)

![Ankidroid_prompt](https://github.com/ankidroid/Anki-Android/assets/9300442/513f30ed-3b2c-40b4-b1f4-e735d83a5d1f)

This did not used to bother me, and seemed straightforward enough as it is, but once I noticed it, I could not unsee it. I think it would be nice to see Upload and Download on both sides. (Not sure what the wording above the buttons should be, but maybe similar to whatever AnkiMobile uses.)

###### Debug info
N/A

###### Research

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
I prefer `Download` and `Upload` as well. Or even `Local`/`Remote`. 

I don't know exactly how this plays off with a custom sync server or which messages shows if one is being used, since I never used it

**Comment by dae** [comment]
For what it's worth, I think the AnkiDroid prompt is actually probably better for the typical layperson - it's more concise, and some users struggle with the distinction between uploading and downloading. I would be open to changing the desktop/AnkiMobile message to be closer to this one instead in the future (but perhaps with the buttons being "Keep AnkiWeb" instead of "AnkiWeb").

One problem though is that all the existing documentation and the intro videos talk about uploading and downloading, so it could potentially cause more confusion if those are not updated as well, and the videos were quite time consuming to make.

**Comment by BrayanDSO** [comment]
> Edit: maybe "Upload (Keep local)" and "Download (Keep AnkiWeb)"?

I think that only `Keep local` and `Keep AnkiWeb` is better

**Comment by daddydave** [comment]
> some users struggle with the distinction between uploading and downloading
They should probably put that on an Anki Note if that is the case, @dae 

Anyway, I am rather backslidden these days on my flashcard habits these days, and I see there is a lot going on in AnkiWorld with the FSRS and IO integrations, so feel free to park this somewhere until there is a good time for it. It sounds like this can't be resolved by changing the wording on a single platform, and the exact wording is your call.

**Comment by RedRubble** [comment]
>  maybe "Upload (Keep local)" and "Download (Keep AnkiWeb)"?
Support!
