### ISSUE TITLE
Feed back with sound

### ISSUE THREAD

**Issue by alvarouchija** [ankidroid/Anki-Android#14416]
I think it would be incredible if anki is able to make a good sound when you are right, a bad sound when you are wrong :)

**Comment by lukstbit** [comment]
To my knowledge this isn't an option available in the standard Anki desktop app. 
We strive to replicate the features of the desktop app so this isn't going to be implemented here. If you feel that this would be a nice feature I recommend that you propose it on the [desktop app repository](https://github.com/ankitects/anki) and if it is accepted and implemented there we will eventually implement it as well.
