### ISSUE TITLE
[BUG]: audio plays randomly with Ankidroid in the background if the app is not closed normally

### ISSUE THREAD

**Issue by traycerb** [ankidroid/Anki-Android#14414]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

After switching away from the app (without "properly" exiting via Back Key, or swiping the app away from Overview/Recents button), after a random period of time, Ankidroid will play the card's audio even with the app in the background.  It also seems to play multiple times, cutting off to repeat itself.

### Expected behaviour

no audio playing when not in foreground.

### Actual behaviour

audio plays with app in the background

### Debug info

```text
AnkiDroid Version = 2.16.4 (67fd45a351c44c46c844aa35a402b98a2a487f68)
Android Version = 11
ProductFlavor = full
Manufacturer = Google
Model = Pixel 4a (5G)
Hardware = bramble
Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 4a (5G) Build/RD1A.200810.022.A4; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.106 Mobile Safari/537.36
ACRA UUID = edc1cf0a-73f9-4d8a-b7c2-9808416b612f
New schema = false
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
This is almost certainly a background WebView crash causing the audio to be played:

https://github.com/david-allison/Anki-Android/blob/cca7bfac9534791eaba7d79fcffdc7db59d06b11/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/OnRenderProcessGoneDelegate.kt#L89-L95

This will be fixed in the next alpha, thanks for your patience

**Comment by fatbringer** [comment]
Thanks guys!
