### ISSUE TITLE
[BUG]: App crashes when downloading decks.

### ISSUE THREAD

**Issue by omer-ash33** [ankidroid/Anki-Android#14429]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Get shared decks > French > Any deck > Download > app crashes

### Expected behaviour

AnkiDroid should've downloaded the deck.

### Actual behaviour

Either the app crashes and takes me back to my phone's homescreen or the download gets stuck at 0%.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 11

ProductFlavor = full

Manufacturer = Xiaomi

Model = Mi 9T Pro

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Mi 9T Pro Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36

ACRA UUID = 2b155303-ca24-482e-861d-cf2b01103cb3

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

I've tried downloading AnkiDroid from the Play Store as well as Droid-ify, same crash still happens.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by rohit9625** [comment]
Hi there @omer-ash33 , I just followed your steps to test the bug, and I am not facing any issues like that. The deck is downloading without crashing or stuck at 0%. So maybe it was just an OS-specific issue. Please tell me you are still facing that problem.

**Comment by omer-ash33** [comment]
Hello. Yes, I'm still facing the same issue. I tried uninstalling and
reinstalling but it still didn't work. I have a Xiaomi phone so maybe that
has something to do with it?

**Comment by rohit9625** [comment]
Okay @omer-ash33 , I'll try to repeat the process from another phone, I have a Xiaomi phone which has the same Android version.

**Comment by rohit9625** [comment]
@omer-ash33, I tried testing this on a Xiaomi phone with Android 11 but still no issue in downloading decks, I only faced one issue that too for one deck as shown in the image.
![Deck](https://github.com/ankidroid/Anki-Android/assets/101377978/c1ed6dc0-a4eb-47b7-af0b-47c83608fb5d)

The issue was the server issue and later on, it was working fine. So, can you please tell me for which specific deck you are facing issues?

**Comment by omer-ash33** [comment]
The deck was 5000 french words or something similar to that.

**Comment by omer-ash33** [comment]
Hey, just wanted to let you know that I found a workaround this issue. I
downloaded the decks on my PC then synced it with my phone. The decks
downloaded automatically.

**Comment by david-allison** [comment]
https://ankidroid.org/acra/app/1/bug/75328/report/153963dd-8139-4add-8de8-eb5ce5a443e6

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.getLastPathSegment()' on a null object reference
	at android.app.DownloadManager.enqueue(DownloadManager.java:1643)
	at com.ichi2.anki.SharedDecksDownloadFragment.downloadFile(SourceFile:107)
	at com.ichi2.anki.SharedDecksDownloadFragment.onViewCreated(SourceFile:134)
	at androidx.fragment.app.Fragment.performViewCreated(SourceFile:15)
	at androidx.fragment.app.FragmentStateManager.createView(SourceFile:314)
	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(SourceFile:125)
	at androidx.fragment.app.FragmentManager.executeOpsTogether(SourceFile:348)
	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(SourceFile:82)
	at androidx.fragment.app.FragmentManager.execPendingActions(SourceFile:22)
	at androidx.fragment.app.FragmentManager$5.run(Unknown Source:3)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:236)
	at android.app.ActivityThread.main(ActivityThread.java:8061)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
```

**Comment by david-allison** [comment]
@omer-ash33 

Thanks for the report. Could you test again on the 2.17 alpha, this may have been fixed in: 
* https://github.com/ankidroid/Anki-Android/pull/14198 (9e7809ac02bbc94b697a3de87fa451ba737f4aa1)

**Comment by omer-ash33** [comment]
Hello again. Can you please send the download link? I couldn't find it in
Github. Sorry, I'm not very familiar with that website.

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/releases/download/v2.17alpha9/AnkiDroid-2.17alpha9.parallel.A.apk

Thanks for replying!

For future reference, it can be found here: https://github.com/ankidroid/Anki-Android/releases/

**Comment by omer-ash33** [comment]
Thank you so much. I'll let you know if this update fixes the issue or not.

**Comment by omer-ash33** [comment]
Hello David. I just downloaded the alpha version of AnkiDroid and I
couldn't log in. Here's a screenshot of the error message.

**Comment by david-allison** [comment]
hi @omer-ash33 

There's a known bug in non-Play Store releases where 'sync from AnkiWeb' won't work, if you get started, THEN log in, it should work

**Comment by david-allison** [comment]
Regardless, you shouldn't need to log in to download a deck

**Comment by omer-ash33** [comment]
I was able to log in now. Turns out I didn't give the app access to my
files, which I thought I did. Downloading shared decks is working too.
Thanks for your help.

**Comment by david-allison** [comment]
Perfect, thanks. Closing as completed
