### ISSUE TITLE
Keep the screen dark when opening the deck option

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14439]
In dark mode, you get a white full screen when opening the deck options, before the page content load. Rendering it unusable if you want to keep a dark screen

**Comment by jeremyxarcher** [comment]
Did some debugging on this. Go to line 47 in DeckOptions.kt. It seems to stem from loading the WebView here. I tried using onLoadResource to edit the theme until the WebView is fully loaded, but it appears that the white screen is displayed after that point. Not super clear on WebViews, but I'm guessing it has something to do with the js, not the android part.

**Comment by pavreh** [comment]
Duplicity of #14194
