### ISSUE TITLE
Unable to click italics button with Bluetooth mouse

### ISSUE THREAD

**Issue by jgscherber** [ankidroid/Anki-Android#14435]
###### Reproduction Steps

1. Connect Bluetooth mouse to phone
2. Edit a card and select text
3. Attempt to click the italics button

###### Expected Result
Italics button is clicked

###### Actual Result
Nothing happens

###### Debug info
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-G981U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G981U1 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36

ACRA UUID = 03434583-cd6c-4869-8ed2-d8e7712382df

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
Is that the only button which shows this problem?

**Comment by jgscherber** [comment]
I tested this again and the format buttons are working now.

**Comment by david-allison** [comment]
Thanks! Closing as completed
