### ISSUE TITLE
UI, small: Let the user mark notes in edit mode

### ISSUE THREAD

**Issue by silidev** [ankidroid/Anki-Android#14431]
UI: Show a star icon in edit mode and let the user toggle it on or off. This will apply or remove the tag “marked” to the note.

Alternatively, add a menu option “Mark note” in edit mode.

This feature would be useful for many users. It should be easy to implement. Maybe it was just overlooked.

**Comment by BrayanDSO** [comment]
Hello there. This isn't available at the desktop version and since we still lack some features of it, this isn't a priority. Try suggesting to add this feature in the desktop version, if it gets implemented, we'll add it here too

**Comment by silidev** [comment]
Hi Brayan,

Firstly, I'd like to express my gratitude for your response and your
contributions to AnkiDroid!

I understand. I'd just like to note that since you have a keyboard on the
desktop, it somewhat already possesses this feature. Although it doesn't
use a star, it's incredibly quick to manually add the tag keyword. This is
also possible on mobile, but it is cumbersome.

Am Fr., 15. Sept. 2023 um 14:20 Uhr schrieb Brayan Oliveira <
***@***.***>:
