### ISSUE TITLE
[ERROR] Please grant ankidroid the Storage permission to continue

### ISSUE THREAD

**Issue by Ezkielnet** [ankidroid/Anki-Android#14443]
I have installed AnkiDroid for the first time and I get the following error: please grant ankidroid the Storage permission to continue. When I go to the permissions section of the app they are only available: Microphone, notifications and Read and write to the AnkiDroid Database.

Does anyone know how to fix it?

I have a One Plus Nord 2 (European Version) with Android 13.

**Comment by BrayanDSO** [comment]
Duplicate of #14423
