### ISSUE TITLE
Undo should be disabled when changing deck 

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14442]
I’m running HEAD. I discovered that I can undo when I change deck. In the deck statq page o’ the the right of the tablet, and in the reviewer. If I do it, I get cards from the previous deck, which is an unexpected change in behaviour

**Comment by mikehardy** [comment]
Sorry, I don't understand the issue

Can you list the exact steps you take, starting with opening the app?
Can you explain exactly why the actual behavior is not expected?

Here's what I did:
- opened app
- selected a deck which started review
- used top right menu in phone form factor to edit note
- selected a different deck for the note and hit save
- now I am in the reviewer again, same note, but in a different deck
- I hit the undo button and it said "Change deck undone" and I am in reviewer, same note, in the original deck

That seems like it is working as expected, to me ?

**Comment by eginhard** [comment]
I had assumed @Arthur-Milchior referred to changing the current deck, not changing a note's deck. E.g. like this in 2.17alpha8:
- open deck A and review one card
- return to the deck picker
- open deck B
- clicking the undo button now shows "Change deck undone" and I'm back in the reviewer in deck A (only changing the deck was undone, not the last review)

I agree that this could be unexpected, but I just checked and it's consistent with Anki Desktop.

**Comment by mikehardy** [comment]
ah ha! I misunderstood, thank you @eginhard - changing the deck is itself an undoable op, and if it's consistent with anki desktop then we have "met our contract" so to speak ;-). Going to close

Thanks
