### ISSUE TITLE
[BUG]: Wrong "New #" position for new cards

### ISSUE THREAD

**Issue by DerDemystifier** [ankidroid/Anki-Android#14449]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1- Check the database on AnkiDesktop to make sure everything is good.
2- Add a new card on AnkiDesktop. Card is correctly assigned New # (last one +1)
3- Sync from AnkiDesktop.
4- Sync from AnkiDroid.
5- Sync again from AnkiDesktop.
6- Add new card on AnkiDesktop. The card is assigned a wrong New #. It's given a number that already exists, so now I have several cards with the same New #.
![image](https://github.com/ankidroid/Anki-Android/assets/124774256/c3c58a77-68ec-4328-a781-5ddf58b3f0cb)

### Expected behaviour

AnkiDroid should adopt the same # position for new cards when I sync from AnkiDesktop.

### Actual behaviour

I think AnkiDroid has its own position numbering which is not overridden when I sync from AnkiDesktop to AnkiDroid. But AnkiDesktop overrides its position numbering when I sync from AnkiDroid. That's why in my case the position always starts at "New #13568".

### Debug info

```text
AnkiDesktop:
V3 Scheduler
Version 2.1.63 (f356f177)
Python 3.9.15 Qt 6.4.3 PyQt 6.4.0

AnkiDroid:
V2 scheduler (V3 is still experimental)
Version 2.16.5
```

### (Optional) Anything else you want to share?

The only workaround right now is to "Check Database" every time I want to add new cards on AnkiDesktop,

I've also added a new post in [AnkiDesktop forum](https://forums.ankiweb.net/t/wrong-new-position-for-new-cards/34526) for this  issue.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Would be useful to know if this is fixed in the V2.17 alpha

**Comment by DerDemystifier** [comment]
Can no longer reproduce. Seems to be fixed 👍🏻

Using :
    
    Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
    Platform: Windows-10-10.0.19045
    Flags: frz=True ao=True sv=3

and `AnkiDroid 2.17alpha8`

**Comment by david-allison** [comment]
One step closer to a stable 2.17, thanks for your help! 🙏
