### ISSUE TITLE
Change the green color of the green flag with day mode

### ISSUE THREAD

**Issue by sangorys** [ankidroid/Anki-Android#14445]
**Is your feature request related to a problem? Please describe.**
I use the green flag. It is very difficult to see the green flag with the day mode theme (I thought my card had no flag because I did not succeed in seeing it !!!)

See the picture below

**Describe the solution you'd like**
On day mode theme, change the color to a dark green instead of light green.
On night mode theme, keep the color

**Describe alternatives you've considered**
No alternative solution except stop using the day mode theme

**Additional context**
![image](https://github.com/ankidroid/Anki-Android/assets/544194/4a1b17ab-6708-49e0-b9e3-4a36b5785134)
(on my computer, I can see it but on my phone, I cannot see it easily)

**Comment by the-mr17** [comment]
@sangorys Please provide some information about your device.
