### ISSUE TITLE
[Bug] An irreproducible crash. (with logs)

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#14447]
###### Reproduction Steps
I don't know how to reproduce it reliably.

###### Actual Result
The app suddenly crashes.
![Screenshot_20230919-100348483 (1).jpg](https://github.com/ankidroid/Anki-Android/assets/43168745/c5645109-681f-4f24-ad9d-ce1727c68792)
![Screenshot_20230919-100303912 (1).jpg](https://github.com/ankidroid/Anki-Android/assets/43168745/6d4acf00-b3b5-4a41-ac8c-d6235026d304)

###### Debug info
AnkiDroid Version = 2.17alpha1-debug (032959c6edf8ee5e8d5ee07afcc51e04bb444e2e)

Android Version = 13

ProductFlavor = play

Manufacturer = asus

Model = ASUS_I004D

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; ASUS_I004D Build/TKQ1.220807.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36

ACRA UUID = a88a5b74-c352-4c72-99da-a3d54075d9dc

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
We can't do much with this, so I'm going to close it.
