### ISSUE TITLE
Paragraph symbol in text

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14453]
That seems new appear in many text. Probably worth an investigation,  as I doubt translators are the cause 

Running on HEAD from a few day ago![Screenshot_20230919-195259_AnkiDroid.jpg](https://github.com/ankidroid/Anki-Android/assets/357361/c2fba99d-8631-4e98-a624-dc0aebbcb194)

**Comment by pavreh** [comment]
Unfortunately, the translation is the cause. You can see two paragraph symbols in the French translation. The first is a symbol, and the second is the end of line. Second, the symbol is not present in my language.
![Screenshot_20230919_230924_Samsung Internet.png](https://github.com/ankidroid/Anki-Android/assets/10192661/13c9689d-cd5c-4845-a5d2-c8195dbb4d65)

![Screenshot_20230919_231312_AnkiDroidA.png](https://github.com/ankidroid/Anki-Android/assets/10192661/ecfe9303-bd0a-4f24-b2c5-8c0b95e5c884)

**Comment by dae** [comment]
Thanks @pavreh, I've fixed these in bulk.
