### ISSUE TITLE
Return 3 answer buttons like before

### ISSUE THREAD

**Issue by huuson889** [ankidroid/Anki-Android#14451]
I don't know why you changed to 4 answer buttons. It's very very super inconvenient because every time a user wants to answer, they have to spend a long time choosing buttons. Three choices are more natural for humans. Please change it back, or at least provide a 3-button option. We really need it. 😞😞😞😞😞

**Comment by mikehardy** [comment]
We follow desktop here.
Sometimes there are only 2 choices. Sometimes 4. Sometimes 3.
It has always been that way.

**Comment by dae** [comment]
To clarify, in the v1 scheduler there were 3 buttons in learning and then 4 during review. With v2, the button count does not differ between learning and review. If you want to retain the old behavior, you can just ignore the Hard button.

**Comment by huuson889** [comment]
@mikehardy @dae 
I don't know, but having four buttons is super inconvenient. I might accidentally press the wrong one. Additionally, with four buttons, each one becomes smaller and more difficult to press. Also, Anki will repeat any words I forget, so 3 buttons are enough.

I just want to choose the answers as quickly as possible without thinking. On the phone, it's 1 left, 1 right and 1 middle button. On the computer, it's 1, 2, 3 - that's enough. Simple and fast.

I simply wish for an option to default to turning off 1 button and having only 3 buttons, as it was in the previous version, please!!!

**Comment by dae** [comment]
It's been this way since the introduction of the v2 scheduler in 2018, so I'm afraid that ship has sailed. If you find the buttons hard to hit, I suggest you use gestures to trigger Again and Good, and only use the buttons when you want to hit Easy or Hard.

**Comment by huuson889** [comment]
From this morning until now (Vietnam time), I have searched for each version of Ankidroid, compared to find the 3-button version but still haven't found it. Thank you, you said it was from the 2018 version so I found it again, but surprisingly the 2021 windows version still has 3 buttons.
Anyway, I still hope the future version has a 3-button option, just 1 option to turn off 1 button is fine, please.
