### ISSUE TITLE
Can’t suspend note anymore

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14455]
Running on 2 days old HEAD. On notes with multiple cards, the suspend note action lead to a toast stating 0 cards are suspended. The card do not change and still appear if I close and open the deck

**Comment by snowtimeglass** [comment]
Reproduced on a4cbca0 (3 weeks old). 

<details>
<summary>Debug info</summary>


AnkiDroid Version = 2.17alpha1-debug (a4cbca046935907cae816576c05f6ab438126acf)

Android Version = 11

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36

ACRA UUID = f74d8c3b-b173-4337-ae0c-819d3934bd5e

Crash Reports Enabled = false


DatabaseV2 Enabled = true
</details>

---
- Same with "Bury note". "0 cards buried" is shown, and the cards are not buried.
- Not reproduced on 2.16.5.

**Comment by dae** [comment]
Should be an easy fix - buryNotes() is passed in the card id instead of the note id

**Comment by Arthur-Milchior** [comment]
Thanks. You surely know it, but it's repaired
