### ISSUE TITLE
[BUG]: Deleted decks still count in the size of collections

### ISSUE THREAD

**Issue by PhunkyBob** [ankidroid/Anki-Android#14454]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Create a new account. 
- Go to ankiweb.net and check "collection size" --> few bytes.
- In AnkiDroid, download an existing deck with 10k cards in it. 
- Sync the application.
- Go to ankiweb.net and check "collection size" --> 3 MB.
- In AnkiDroid, delete the deck. Now there is no more deck except for "Default" with no card in it.
- Sync the application.
- Go to ankiweb.net and check "collection size".

### Expected behaviour

I excpect my collection size to be few bytes, because there a no more any cards in the collection.

### Actual behaviour

The size is still 3 MB, like if the deck hasn't been deleted.

### Debug info

```text
...
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
https://forums.ankiweb.net/t/size-of-my-collections/34188

**Comment by PhunkyBob** [comment]
Hello, @dae 

Your solution works fine, but it's only a workaround. 
If your Android application needs a task that can be done only by the Destop application, there is a problem. 

EDIT: OK, my apologies. I didn't see that this option was also available in the Android application.

Thank you!
