### ISSUE TITLE
Refactor / remove DeckRenameException

### ISSUE THREAD

**Issue by lukstbit** [ankidroid/Anki-Android#14458]
Re DeckRenameException, the "already exists" case could be removed, as the backend will return successfully if the user attempts to add a deck that already exists. If you wanted to go a step further, you could consider dropping the custom exception entirely, and just relying on BackendDeckIsFilteredException instead. AnkiDroid doesn't need to actually handle this error; it can just print the localized message when the exception is caught by launchCatchingTask.

_Originally posted by @dae in https://github.com/ankidroid/Anki-Android/pull/14446#pullrequestreview-1634324112_

**Comment by david-allison** [comment]
Sounds good to me!
