### ISSUE TITLE
Deck options for New cards, steps should be possible in days

### ISSUE THREAD

**Issue by jonathan-s** [ankidroid/Anki-Android#14465]
**Is your feature request related to a problem? Please describe.**
When setting up deck options it is different from the desktop version. 

<img width="582" alt="Screen Shot 2023-09-22 at 11 26 24" src="https://github.com/ankidroid/Anki-Android/assets/2124818/177f13f7-5989-4a7f-83c5-532c77608c3c">

The number of steps needs to be in minutes. If you want to have something longer than minutes like days or hours it becomes difficult to manage. 

**Describe the solution you'd like**
Be able to use the same format as the desktop version, much like the attached image.

**Comment by lukstbit** [comment]
This should be fixed starting with version 2.17alpha2 as from that version the new backend is enabled.
