### ISSUE TITLE
wrong card count in the deck picker

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#14469]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Switch burying on in a deck options
2. Create a new and reverse card

### Expected behaviour

The deck picker shows one new card as the sibling card is delayed to the next day.

### Actual behaviour

The deck picker shows two new cards. After you study one new card, the study season is ended.
![Screenshot_20230923_153613_AnkiDroidA](https://github.com/ankidroid/Anki-Android/assets/10192661/af8d8345-dcc4-4236-bffd-c432b887d290)

### Debug info

```text
AnkiDroid Version = 2.17alpha1 (e817d891c70a05b86aa10690f5a5d5e2b1c7ad2d)

Android Version = 13

ProductFlavor = full

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = c8d2feb8-9e68-4178-9295-bbc690cfef0c

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Card count in the deck info is all right.
![Screenshot_20230923_153617_AnkiDroidA](https://github.com/ankidroid/Anki-Android/assets/10192661/5b11e859-44c9-4577-b347-b6864dcb5c34)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by jeremyxarcher** [comment]
I've reproduced the issue and am looking in to it.

**Comment by jeremyxarcher** [comment]
This issue exists on Anki Desktop as well. It could be a problem with the data coming from the backend. I did notice that the issue does not exist when you get to the Reviewer. I couldn't trace it fully how the queuestate gets set, but it's set differently that the counts in the DeckAdapter.

**Comment by pavreh** [comment]
Thank you for the investigation. I can confirm that the deck picker in Anki shows two cards also. The situation is different in the deck overview. Anki shows 1+1 while AnkiDroid shows 1.

**Comment by BrayanDSO** [comment]
@dae, do you have any thoughts on this?

**Comment by dae** [comment]
Which cards get buried depends on which deck is selected, so it's not possible to show bury counts on the deck list.

**Comment by BrayanDSO** [comment]
> The situation is different in the deck overview. Anki shows 1+1 while AnkiDroid shows 1.

joining this with https://github.com/ankidroid/Anki-Android/issues/15186
