### ISSUE TITLE
Default to left-aligned instead of centered

### ISSUE THREAD

**Issue by jfowl** [ankidroid/Anki-Android#14473]
Relaying a frustration from a friend here:

Unordered lists appear as left-centered on desktop while creating them, but are centered on android while learning.

Would it be feasible to make android and desktop more consistent? Accidentially centered bullet points are a bit confusing looking.

**Comment by david-allison** [comment]
Fixed in https://github.com/ankidroid/Anki-Android/pull/16239

* https://github.com/ankidroid/Anki-Android/pull/16239

**Comment by jfowl** [comment]
@david-allison thank you very much, this is greatly appreciated <3

**Comment by Hedaja** [comment]
Hello

I'm facing the issue of text being  eft-aligned by default on Anki desktop but it's centered when I change to Android.
I'm using the latest preview Version (22.2alpha1) from the Google Playstore (updated 27.06.25)

**Comment by david-allison** [comment]
@Hedaja Edit a note and tap `Cards` to set the CSS

**Comment by Hedaja** [comment]
@david-allison thank you for the tip 

Yes, card still had text aligned set to center. I guess it's a Anki desktop issue then, if that gets ignored there.

**Comment by david-allison** [comment]
Use this: https://ankiweb.net/shared/info/31746032

Or: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide/#html-javascript-inspection for AnkiDroid
