### ISSUE TITLE
[BUG]: Chromebook - AnkiDroid crashes when I try to edit a card

### ISSUE THREAD

**Issue by mathias11234** [ankidroid/Anki-Android#14472]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Be on a Chromebook 514. Press "start studying". Press "E" or "edit" while on a card. Ankidroid will stop working and crash.
It also crashes sometimes when im in Settings.

### Expected behaviour

It should allowed me to Edit the card

### Actual behaviour

The Ankidroid app crashes.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 11

ProductFlavor = full

Manufacturer = Google

Model = asurada

Hardware = bertha

Webview User Agent = Mozilla/5.0 (Linux; Android 11; asurada Build/R116-15509.72.0; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.131 Safari/537.36

ACRA UUID = d0099dcf-47d6-456b-b1a7-c775936c0edd

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Im a newbie who just wants to study my flashcards

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mathias11234** [comment]
ive tried installing Ankidroid from the playstore, then the latest 2.16.5 full-universal.apk in developer mode several times, then 2.16.5-arm64-v8a.apk which should be fitting for my specifics if I understood the guide correctly (200 dpi, R (11), arm 64)

**Comment by dae** [comment]
Maybe related? https://www.reddit.com/r/androiddev/comments/146cd1y/comment/jnt3jmn/

**Comment by mathias11234** [comment]
https://www.youtube.com/watch?v=kPZRb4_G7sc

**Comment by mathias11234** [comment]
[https://www.youtube.com/watch?v=kPZRb4_G7sc](url)

**Comment by david-allison** [comment]
No crashes in ACRA for `d0099dcf-47d6-456b-b1a7-c775936c0edd`

@mathias11234 are you still around to provide debug info?

**Comment by mikehardy** [comment]
Just a note there are a couple play store chromebook crash things as well - I still don't have a chromebook as I deferred that purchase thinking 2.16 would fix most of them and that the Desktop AVD (a relatively new thing https://chromeos.dev/en/posts/desktop-avd-in-android-studio) or something like it would exist. Looks like it exists now

So if someone wants to triage this, setting up the Desktop AVD would be a good start

**Comment by mikehardy** [comment]
Sadly, tried the Desktop AVD (using the 12L image out of the "13 or 12L" choice of two available images...) and I could not replicate any crashes in either card review/edit or settings despite trying my best to hammer it with keyboard shortcuts or mouse clicks and lots and lots of repetitions.
We'll need to see the actual crash trace of this if it is possible --> make sure crash reports are enabled in settings if at all possible

**Comment by mikehardy** [comment]
With more interaction on the support mailing list, this appears to be an ANR (hang, "Application Not Responding") not a crash. I am unable to get a stack trace related to this, so far.

The play dashboard ANR report shows a few chromebook ANRs related to a GPU thread hanging, which is quite odd. And not much else...

**Comment by ccchan234** [comment]
i got a lenovo duet 2020 /w latest chrome OS on android using virtual mchine, not the container method before.

currently, no matter what version of ankidroid i install, when i simply press into the "setting", it even cant scroll down to the bottom and halt.

i gave up. my chromebook wont be able to run ankidroid for sometime i think.

**Comment by ccchan234** [comment]
hi,
i wanna report here that with my lenovo duet chromebook 2020 (arm cpu).
2.17.5 from play store worked fine.
i tried to use 2.16.5 (to sync with older desktops) but 2.16.5 simply always hangs. i cant even type in my email and password.

but the CB works OK /w 2.17.5.

thank you.

**Comment by david-allison** [comment]
Thanks! I don't think the dev team has a Chromebook for testing, so it's difficult to diagnose & fix bugs.

But we're MORE than happy to merge bugfixes
