### ISSUE TITLE
[BUG]: Snackbar shows in front of the FAB secondary options

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14470]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Do an action that shows a snackbar in the deck picker, such as undoing or syncing
2. Tap the FAB

### Expected behaviour

The snackbar is dismissed

### Actual behaviour

The snackbar is in front of the FAB secondary options (Get shared decks and Create deck)

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/4ed0097e-7b3c-4475-8f51-eb7967aa01f1)

### Debug info

```text
3e520ad2c64a0f5a6c7b65160825b4fd5c6d258f
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by soCallmeAdityaKumar** [comment]
I am working on it

**Comment by soCallmeAdityaKumar** [comment]
fixed for deckpicker will be fixing for rest of snackbar in further commits

**Comment by BrayanDSO** [comment]
Adding this to the 2.17 milestone
