### ISSUE TITLE
Advanced forecast broke between 2.15 vs 2.16

### ISSUE THREAD

**Issue by infinity0** [ankidroid/Anki-Android#14487]
###### Reproduction Steps

1. Fully learn a deck so there are no more new cards.
2. Set the "maximum reviews/day" to the maximum allowed, 9999.
3. Check the advanced forecast

###### Expected Result

Forecast is a gradually reducing number of young/mature cards to learn, eventually going to 0. This is what happened in 2.15.

This is what you'd intuitively expect, that it's possible to actually learn.

###### Actual Result

Forecast is a gradually **increasing** number of young/mature cards to learn, eventually going up to the total number of cards in the deck or to whatever maximum you set in (2). This is what happens in 2.16.

This is off-putting as it suggests learning is pointless, you will never learn the actual deck.

Possibly related to #8857.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Advanced statistics was removed in 2.17 in favor of using the desktop statistics screen and won't be added back. But thanks for the report
