### ISSUE TITLE
[BUG]: long user startup time perceived

### ISSUE THREAD

**Issue by mainrs** [ankidroid/Anki-Android#14486]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Install the 2.16.5 version.
- Start the app

### Expected behaviour

The splash screen shows instantly and waits until the app is ready. Once ready, the app shows the deck browser.

### Actual behaviour

There is a rather large delay between clicking the app in the app launcher and having a startup splash screen shown. 

I think the app does some checks on startup before showing the activity content (if someone would point me out to what the app does before showing the deck browser I'd be thankful).

Potential fix is to move to androids startup api that allows for asynchronous workers in the background before showing app content.

I'd be happy to work on this. 

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = full

Manufacturer = Google

Model = Pixel 6

Hardware = oriole

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ3A.230901.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = 86ad8b62-73bb-4ce4-a638-ee1896487ab5

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@mainrs Was on holiday when this was submitted. Sorry I missed it.

If you're still interested, please let me know

`AnkiDroidApp` is the entry point to the app, I've recently added `measureTime` (below), which as a first step can be used to log potential issues with startup time.

The likelihood is that loading the bridge to the Anki Backend, and then loading the user collection is taking up the majority of time, but I suspect we have a fair amount of low-hanging fruit here.

As a first step, determine where the slowdown occurs, then we have more insight into fixing it.

With 2.17, we use a new backend, which will have faster performance characteristics for the most part. Ensuring testing occurs on `main` is vital
