### ISSUE TITLE
[Bug] - Import apkg error

### ISSUE THREAD

**Issue by filipenanclarez** [ankidroid/Anki-Android#14484]
###### Reproduction Steps

1. Install Ankidroid
2. Import the first file (rename to .apkg): [HSK3.0v20230902.zip](https://github.com/ankidroid/Anki-Android/files/12744772/HSK3.0v20230902.zip)
4. Import the second file (rename to .apkg): [HSK3.0v20230903.zip](https://github.com/ankidroid/Anki-Android/files/12744773/HSK3.0v20230903.zip)

Please see this vídeo with more details:

https://github.com/ankidroid/Anki-Android/assets/27212546/0efd369c-3c9f-4b10-b08a-425db55d0b89

###### Expected Result
Import new cards like AnkiMobile and Anki Desktop

###### Actual Result
Error, and no notes imported

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

```
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-T220

Hardware = mt6765

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-T220 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/[116.0.0.0](http://116.0.0.0/) Safari/537.36

ACRA UUID = 20ff51cf-a3df-4585-b5cd-98e7a902f3fd

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

@dae

**Comment by dae** [comment]
I recommend closing this, as 2.17 will use the same importer as the desktop version.

**Comment by filipenanclarez** [comment]
@BrayanDSO and @dae 

How can i test the  beta version of AnkiDroid to check if this problem is fixed? 

Many users is reporting this problem, and waiting for the new version
