### ISSUE TITLE
[Bug] new backend: "undo" doesn't work

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#14482]
###### Reproduction Steps

1. Review a few cards
2. Tap undo 

###### Expected Result

3. Review is undone 

###### Actual Result

"Bury undone" is shown instead

###### Debug info
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-G991B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G991B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = 1574cc4c-69c4-40de-b502-2f753d67b31c

New schema = true

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
Probably already fixed in 2.17?

**Comment by BrayanDSO** [comment]
I have been using 2.17 for some weeks now and haven't seen this happening

**Comment by criticalAY** [comment]
It works fine
