### ISSUE TITLE
Optimized Deck Management with Expiry Dates

### ISSUE THREAD

**Issue by programadory** [ankidroid/Anki-Android#14495]
Absolutely, let's structure your idea following those guidelines:

**Is your feature request related to a problem? Please describe.**

I often find myself overwhelmed with the sheer number of flashcards I accumulate while using AnkiDroid to study languages. Managing these decks and their cards becomes a significant challenge. It's frustrating to have no built-in way to set limits or deadlines for my decks, leading to a cluttered and inefficient study experience.

**Describe the solution you'd like**

I propose the introduction of an "Expiry Date" feature in AnkiDroid. This feature would allow users to set expiration dates for their study decks. Here's how it would work:

- When creating or editing a deck in AnkiDroid, users should have the option to specify an expiration date for that deck by selecting a specific date in the future.

- Starting from the defined expiry date, AnkiDroid would gradually limit the number of reviews available for that deck. Users would only be able to review cards in that deck up until the expiry date.

- When the expiry date approaches, users should be presented with several management options:
   - They can choose to "Keep the Deck" if they want to continue studying it, and extend the expiry date or remove it to resume regular reviews.
   - Alternatively, they can "Delete the Deck" if they feel they no longer need to study that deck or wish to free up space on their device.

This solution would provide a structured approach to deck management, allowing users to set study goals and deadlines, which is currently lacking in AnkiDroid.

**Describe alternatives you've considered**

I've considered manually managing each deck's cards and reviews, but this is time-consuming and prone to oversight. Another alternative is using external tools, but having this functionality directly within AnkiDroid would streamline the process.

**Additional context**

This feature addition would not only improve the user experience but also contribute to efficient storage space management on the servers, benefiting both users and AnkiDroid's infrastructure.

**Comment by BrayanDSO** [comment]
This kind of feature should only be added if the desktop version has it as well, so I suggest you request this feature there first. If it gets implemented, we will add it here too.
