### ISSUE TITLE
[BUG]: Card audio plays unexpectedly when changing deck options

### ISSUE THREAD

**Issue by doozan** [ankidroid/Anki-Android#14496]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

* Enable new backend
* Have cards with audio on the front that need to be studied today
* Long press on deck
* Select deck options
* Make any adjustment
* Save

### Expected behaviour

Options are saved

### Actual behaviour

Options are saved, and the audio is played from the next card needing to be studied, even though that card is not displayed (still in deck viewer)

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 12

ProductFlavor = full

Manufacturer = samsung

Model = SM-G970U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 9e04916e-4ad1-45aa-b58c-9624d0eb41b6

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

It's not just the deck options that causes this, I think I remember it happening when toggling the new backend, too.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
opExecuted() will need to be updated to set a flag that a refresh is required, and defer refreshing if not currently shown.

https://github.com/ankitects/anki/blob/0ef28853fd96c2ec516339c9f6c147003556edac/qt/aqt/reviewer.py#L202
