### ISSUE TITLE
[BUG]: line breaks insterted when note edited

### ISSUE THREAD

**Issue by AXiSource** [ankidroid/Anki-Android#14504]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

https://github.com/ankidroid/Anki-Android/assets/32098707/8eac51e8-61a2-4f05-82b4-f318a60fe588

### Expected behaviour

No new line break added after simply opening and closing "Edit note" panel.

### Actual behaviour

Line breaks added after simply opening and closing "Edit note" panel.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-M135F

Hardware = exynos850

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-M135F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = 7ab61a33-0623-4db8-9604-6b458ef84023

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Field with html :
```
 	se plaindre
\<br>porter plainte
\<br>dire
\<br> 	raconter
\<br>accuser
\<br>recourir
\<br>
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Should be handled by `Settings -> Advanced -> Replace newlines with HTML`

We'll have a better UX once we replace the note editor
