### ISSUE TITLE
[Bug] Snackbar shows in front of Note editor toolbar

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14506]
###### Reproduction Steps

1. Tap the FAB to add a card to open the note editor
2. Add a card

###### Expected Result

The snackbar doesn't hide any UI content

###### Actual Result

The snackbar shows in front of the note editor toolbar

https://github.com/ankidroid/Anki-Android/assets/69634269/54cd3020-270c-4cb5-bb67-2333a9a475db

###### Debug info

2.17alpha1, Android 13

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Abdullahkhanspn** [comment]
where the Snackbar shows in how to resolve that .Should I make the Snackbar toast up the note editor?
I want to work with the issue. Please assign me .

**Comment by githubashutoshsoni** [comment]
we can hide the keyboard and show the snackbar at the bottom? if this is what you want let me know.

**Comment by Abdullahkhanspn** [comment]
yes i think that work in this.

**Comment by soCallmeAdityaKumar** [comment]
Please assign this to me , i want to work on this

**Comment by Giyutomioka-SS** [comment]
li have already fixed it,  just making PR

**Comment by soCallmeAdityaKumar** [comment]
> l have already fixed it, just making PR

Oh i haven't seen you'r comment and just opened the pull request , closing it.
