### ISSUE TITLE
[BUG]: pasting image results in `<src` code

### ISSUE THREAD

**Issue by Frankkkkk** [ankidroid/Anki-Android#14501]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Copy an image in Firefox and paste it back into ankidroid.

The paste inserts an `img` tag and not the image per se.

The clipboard shows the correct image.

![Screenshot_2023-10-01-13-44-34-455_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/17879459/84ce549e-b70a-404e-ad68-e5c2fbde12f6)

### Expected behaviour

The image should be pasted into the textbox

### Actual behaviour

The `img` tag is inserted instead 

### Debug info

```text
Android 14
MIUI 14
Gboard
AnkiDroid 2.16.5
Firefox 117
```

### (Optional) Anything else you want to share?

Don't hesitate if you need more information on my part ! Thanks !

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
Hello thanks for the report.
This is not a bug, the same html tag is introduced on anki desktop as well it's just that the desktop app has a [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG) editor(which "translates" the html code) while AnkiDroid doesn't have one so you just see the underlying html. You can still see how the card will look in AnkiDroid by using the top bar preview feature(the eye icon).

There's some work to implement a WYSIWYG editor on AnkiDroid but it's going to take a while.

**Comment by Frankkkkk** [comment]
Hi @lukstbit 
Thanks for your reply.
The problem is that the image doesn't show on the final card (with preview for example)
Many thanks

**Comment by lukstbit** [comment]
I've reopened this issue.

> the image doesn't show on the final card (with preview for example)

It doesn't show anything or it shows a broken link image?

**Comment by david-allison** [comment]
> It doesn't show anything or it shows a broken link image?

@Frankkkkk

**Comment by david-allison** [comment]
Just tested (Samsung S21 + Firefox + Wikipedia)

Can't reproduce:

* `<img>` is inserted
* Preview shows the image
