### ISSUE TITLE
[BUG][2.17alpha][HEAD]: Can't disable "Show remaining" and "Show button time"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#14502]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Use the HEAD ([0767aef](https://github.com/ankidroid/Anki-Android/commit/0767aef449e4dc7e0f83254a2f35b53f9929de15)) or recent one
2. "Settings">"Appearance"
3. (Confirm "Show top bar" is enabled. If it isn't, enable it.)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/820dae27-7eea-465e-a278-e2ae4daf386d)

4. Tap "Show remaining"

### Expected behaviour

The "Show remaining" feature is switched to be disabled.

### Actual behaviour

The error message is shown. 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/fb574db5-459a-44b3-baa5-5e766d90c64a)

The "Show remaining" switch is visually toggled to be disabled, 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/3ecb24df-2a01-4232-b3c1-1ed99c503f1c)
but the feature isn't actually disabled. 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/fc0e5a4e-6a6b-483d-85ac-b5de2b6a2fa9)
On showing the "Appearance" screen again, you can see that the switch is toggled to be enabled.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/820dae27-7eea-465e-a278-e2ae4daf386d)

https://github.com/ankidroid/Anki-Android/assets/10436072/5ae5c299-1e35-4846-b3a3-af08478f3560

### Debug info

```text
AnkiDroid Version = 2.17alpha1-debug (0767aef449e4dc7e0f83254a2f35b53f9929de15)

Android Version = 11

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/116.0.0.0 Mobile Safari/537.36

ACRA UUID = f74d8c3b-b173-4337-ae0c-819d3934bd5e

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Not reproduced on both 2.16.5 and 2.17alpha1

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
Just requires casting newDueCountsValue into a bool before passing it to config.set()

**Comment by snowtimeglass** [comment]
>It would also be good to check the other preferences to make sure they don't suffer from the same issue.

@dae thank you. Seemingly the "Show button time" option has the same issue.

**Comment by asirrosa** [comment]
Hello there could i work on this issue?

**Comment by vyom198** [comment]
Hello , can you assign me this issue?

**Comment by criticalAY** [comment]
If no one is assigned on a issue you can just comment that you are working on it and start working : )
