### ISSUE TITLE
[BUG]: Doesn't do all available cards when deck over Maximum Reviews

### ISSUE THREAD

**Issue by phannan** [ankidroid/Anki-Android#14519]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Set the maximum review limit below the number of cards that will be due in the next session.  I set new maximums yesterday.  Turn on "Use the new backend"

### Expected behaviour

AnkiDroid allows me to review cards until the maximum review is reached.  

### Actual behaviour

All of my decks were over the maximum review limits.  I had a variety of responses, all of whom boiled down to not being able to do all the cards that were due in the deck.

In one deck it did one card and then it bopped out.   On another of the decks that was over the maximum review it told me I was finished for the day even though I had several cards to review that were under the maximum.    I was able to review cards as expected on the desktop version.   When I increased the maximum deck size, I was able to review the cards.

AnkiDroid properly showed the card stats on the deck screen.  IOW, if the deck limit was 25, ankidroid showed 25 due. 

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 11

ProductFlavor = play

Manufacturer = samsung

Model = SM-T510

Hardware = exynos7904

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-T510 Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Safari/537.36

ACRA UUID = 2236c1c8-8bfd-4b03-8564-9deef9c78291

New schema = true

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

When I turned "Use the new backend" off it worked as expected. 

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Sorry this was happening for you!
I no longer reproduce this, it was likely fixed in all the backend work done as we switched the upstream anki scheduler
You might try the new 2.17 alphas if this is troublesome for you, until we release 2.17 for real: https://github.com/ankidroid/Anki-Android/releases
