### ISSUE TITLE
[BUG]: Frozen/pinned fields are reset after adding a note 

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14511]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Pin/unpin a field in the note editor
2. Add a note

https://github.com/ankidroid/Anki-Android/assets/69634269/1cf903e5-99c7-44bb-8679-26733d8251ed

### Expected behaviour

Pinned fields are kept

### Actual behaviour

Pinned fields are reset

### Debug info

```text
2.17alpha1 HEAD, Android 13
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pratyaksh1610** [comment]
Can't reproduce



https://github.com/ankidroid/Anki-Android/assets/76740999/e531f4c1-56aa-4798-afc8-975444f0f905


```

AnkiDroid Version = 2.17alpha1-debug (10af5423467466144ed17c5a11249fdf943299f6)

Android Version = 13

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_x86_64 Build/TPB4.220624.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.74 Mobile Safari/537.36

ACRA UUID = dcdf83a6-79da-4690-9b4a-5968da3f1114

Crash Reports Enabled = false

DatabaseV2 Enabled = true

```

**Comment by mikehardy** [comment]
I do not reproduce this either
