### ISSUE TITLE
Quick-win! Turn on hyphenation by CSS/HTML by default

### ISSUE THREAD

**Issue by silidev** [ankidroid/Anki-Android#14525]
Turn on hypenation by default. I did it for my card template, work greats, but I think all users should have that.

I use this, it works, probably not all needed:
CSS:
```
 -webkit-hyphens: auto;
 -ms-hyphens: auto;
 hyphens: auto;
```

HTML (e. g.):
`<div lang="en-US">`

**Comment by silidev** [comment]
I still recommend this.

**Comment by BrayanDSO** [comment]
We try to be consistent to Anki desktop style, so try suggesting it there, and if it gets accepted we will ingest the change
