### ISSUE TITLE
[BUG]: Importing a deck that wasn't exported with the "Support older Anki versions" fails to import and gives misleading message

### ISSUE THREAD

**Issue by soliviantar** [ankidroid/Anki-Android#14522]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Import a deck that had the "Support older Anki versions (slower/larger files)" disabled when exporting in Anki Desktop. (Example deck [here](https://drive.google.com/file/d/1JH4QecUv91Z44QYKA9Vu-fgGvicm09t4/view?usp=sharing))

### Expected behaviour

The deck is correctly imported (if using latest Ankidroid, I guess), or the error message should indicate the correct way to export the file in Desktop.

### Actual behaviour

A "Default" deck with one card is created. Both the front and back of the card say:

`Please update to the latest Anki version, then import the .colpkg/.apkg file again.`

(This is not useful, since both the Desktop and Android apps are on their latest version. It should probably direct the user to export with the "Support older Anki versions" enabled.)

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2102J20SG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; M2102J20SG Build/TQ2B.230505.005.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = 133f00ff-3288-4734-9330-044c0da702c7

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Try enabling the `Use the new backend` setting in `Settings - Advanced`. If it works, this is already solved since the new backend is the default in 2.17

**Comment by soliviantar** [comment]
> Try enabling the `Use the new backend` setting in `Settings - Advanced`. If it works, this is already solved since the new backend is the default in 2.17

Yes, this worked, thanks! The decks are now being imported correctly. 

However it seems their settings are lost. Deck presets are imported and appear in the preset list, but they're not being applied to the decks on import.
