### ISSUE TITLE
[BUG]: JS API features flags are turned off

### ISSUE THREAD

**Issue by silidev** [ankidroid/Anki-Android#14520]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

From the code of 2.17 alpha and 2.16: ([source](https://github.com/ankidroid/Anki-Android/blob/953b9bd879269910ee962b520da9705336d8bc2d/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPIConstants.kt#L55)): 
```
        jsApiListMap[MARK_CARD] = false
        jsApiListMap[TOGGLE_FLAG] = false
        jsApiListMap[BURY_CARD] = false
        jsApiListMap[BURY_NOTE] = false
        jsApiListMap[SUSPEND_CARD] = false
        jsApiListMap[SUSPEND_NOTE] = false
        jsApiListMap[SET_CARD_DUE] = false
        jsApiListMap[RESET_PROGRESS] = false
```

These flags turn off the corresponding API functions. As far as I can see, this is wrong, e. g. SET_CARD_DUE was implemented in this issue: github.com/ankidroid/Anki-Android/pull/11071

### Expected behaviour

It should be possible to use these API methods.

### Actual behaviour

showDeveloperContact(ankiJsErrorCodeDefault)

and the methods are not executed.

### Debug info

```text
n/a
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Probably need to handle this after #14564

**Comment by mikehardy** [comment]
I'm closing this while reviewing #14564 - I believe this is a misread of the source, and I believe the sample deck on that PR (plus the PR itself) work fine.

If you initialize the JS API correctly the JS API enables the various functions, altering the default `false` values you have cited such that they are true.

If you do not initialize the JS API, then they remain false

**Comment by silidev** [comment]
Okay Mike, thank you for that information. I will check what might be wrong
with my init code.

Am Sa., 2. Dez. 2023 um 14:25 Uhr schrieb Mike Hardy <
***@***.***>:
