### ISSUE TITLE
[Bug] An error of "java.util.zip.ZipException" error opening zip file, after syncing and exporting from AnkiWeb

### ISSUE THREAD

**Issue by Fastball2880** [ankidroid/Anki-Android#14527]
###### Reproduction Steps

1. After researching the issue, proceeded to install the alpha version of AnkiDroid on my tablet. I even installed the official version in my other phone to ensure that it works.
2. Checked the decks/cards in AnkiWeb and Anki Desktop to ensure that it shows all the pictures, etc. (Which it is for a long time) 
3. Proceeded to sync all the media's to AnkiDroid.

###### Expected Result
All my decks should be working by now as in my other phone, according to my Samsung on the official image with Knox un-tripped.

###### Actual Result
All the media is not showing, despite AndroidWebView supporting these files, as written in the AnkiAndroid Manual. I checked the collection.media but its empty.

Is it because of the unofficial build of LineageOS that I am using or am I too broke to buy an iPad?

https://github.com/ankidroid/Anki-Android/assets/147415340/95f2d44b-2165-4d9d-8a90-abcc02e8553a

![Screenshot_20231009-084028_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/147415340/6bce1bec-ee79-49af-8319-17689b193af8)

###### Debug info
AnkiDroid Version = 2.17alpha1 (e817d891c70a05b86aa10690f5a5d5e2b1c7ad2d)

Android Version = 11

ProductFlavor = full

Manufacturer = samsung

Model = SM-T350

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-T350 Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Safari/537.36

ACRA UUID = f83505f8-8ece-406b-b4ee-4f9171a610b9

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Fastball2880** [comment]
Yes, by the way, this also happened at another issue at https://github.com/ankidroid/Anki-Android/issues/11856, but it seems like it got ignored. Same custom ROM (LineageOS). Is this still fixable or I actually need to buy an iPad? I have AnkiMobile but still, too broke at the moment.

**Comment by mikehardy** [comment]
Are you able to see what the exact ZipException is, like via `adb logcat` and hopefully grabbing a stack trace? Not sure how we can move this forward otherwise

**Comment by Fastball2880** [comment]
Sure! Also, I do not know Java with the ZipException since I only deal with bash and Phyton.

I will follow-up with the adb logcat, but would you reproduce how to logcat when finding error as it was not described on manual?

**Comment by dae** [comment]
Can you reproduce the error on alpha2+?

**Comment by Fastball2880** [comment]
> Can you reproduce the error on alpha2+?

https://github.com/ankidroid/Anki-Android/assets/147415340/01caae0e-66a7-4fc6-97a0-e91f6b395892

The files successfully transferred to AnkiDroid! No error occured while syncing.

The second deck is gone because I failed a course and haven't done my review for days, so ignore my overdues with the first deck

**Comment by Fastball2880** [comment]
I will do the logcat in the stable build; probably this issue is with the conflict with the custom ROM.

**Comment by dae** [comment]
I'd wait until you hear from another AnkiDroid dev advising you to do so, as it may not be worth trying to chase down this bug in code that has already been removed from the current development branch.

**Comment by mikehardy** [comment]
If this is code is gone in the current development version and the alpha is working, I would use the alpha and we should close the issue as it will never be actionable - we've already fixed it :-)

The alpha is in general stable yes. We have a pretty large automated test suite that runs against all changes prior to inclusion, and it exercises all the basic functionality of the app. So the alpha should work well for you - I use it daily for instance, as do nearly a thousand other people (our alpha testing group) as near as I can tell.

There may sometimes be *surprises*, like visual changes that are half done (#14642 is an example, as we refresh the UI) or functionality moving around to different menus but the app will work and we don't alter things that quickly so the rate of surprise should be pretty low

**Comment by Fastball2880** [comment]
> If this is code is gone in the current development version and the alpha is working, I would use the alpha and we should close the issue as it will never be actionable - we've already fixed it :-)
> 
> The alpha is in general stable yes. We have a pretty large automated test suite that runs against all changes prior to inclusion, and it exercises all the basic functionality of the app. So the alpha should work well for you - I use it daily for instance, as do nearly a thousand other people (our alpha testing group) as near as I can tell.
> 
> There may sometimes be _surprises_, like visual changes that are half done (#14642 is an example, as we refresh the UI) or functionality moving around to different menus but the app will work and we don't alter things that quickly so the rate of surprise should be pretty low

Thank you for making me learn more on things with AnkiDroid, keep up the good work for this development.
