### ISSUE TITLE
[BUG]: AnkiDroid 2.16.5 CSS font-color issue with theme "follow-system"/rgb(0, 0, 0) shown as white

### ISSUE THREAD

**Issue by kuramaa** [ankidroid/Anki-Android#14526]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

0. switch your android-settings appearance to darkmode
1. create a new card for your deck in Anki (not ankidroid) for macOS or windows.
2. write a sentence with a few words
3. mark one word in the sentence
4. change the background-color to "yellow" (of the marked word)
5. change the font-color to "black" (of the marked word)

### Expected behaviour

AnkiDroid 2.16.5 shows a black [rgb(0 , 0, 0)] font-color instead of white!

### Actual behaviour

AnkiDroid 2.16.5 shows a white font-color instead of black!

![Screenshot_20231008-103229_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/25812370/f5b6fff8-17cc-4907-b501-10ca53775aa2)

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 11

ProductFlavor = play

Manufacturer = samsung

Model = SM-A705FN

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-A705FN Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.131 Mobile Safari/537.36

ACRA UUID = 19d4aab3-eafe-4248-8e3f-784e25b6c48e

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BorisNA** [comment]
I believe this is a night-mode color inversion. Like https://docs.ankimobile.net/night-mode.html or https://github.com/ankidroid/Anki-Android/issues/13325 or ..

You can add the following to your stylesheet to disable this inversion globally
```
.mobile .night_mode { }
```
or define color like
```
.tone3 {color: blue;}
.night_mode .tone3 {color: deepskyblue;}
```
