### ISSUE TITLE
[BUG]: incorrect colors for difference in typed answer and correct answer

### ISSUE THREAD

**Issue by lrvideckis** [ankidroid/Anki-Android#14530]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

![Screenshot_20231010-153231](https://github.com/ankidroid/Anki-Android/assets/33103480/a88d26e4-46a6-46d0-b5e2-baf4871d4d65)

card type: "Basic (type in the answer)"
front: proud
back: गर्व

then I typed in गर्ब and (as seen in the screenshot) it correctly says the spelling is wrong(via the arrow) but it shouldn't be all green

### Expected behaviour

![Screenshot_20231010-155307](https://github.com/ankidroid/Anki-Android/assets/33103480/02937ba3-22e9-4e45-8ff0-b251d65d31e1)
correct behavior: something like this where the top(incorrect) text has the wrong letter in red; bottom(correct) text in grey

### Actual behaviour

see above

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = full

Manufacturer = Google

Model = Pixel 6

Hardware = oriole

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6 Build/TQ3A.230901.001.C1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = 2636c47b-6cbe-4412-aea2-b3ade4269288

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

the script is called devanagari https://en.m.wikipedia.org/wiki/Devanagari

unicode block: https://en.m.wikipedia.org/wiki/Devanagari_(Unicode_block)

the bug may have to do with the virama character https://en.m.wikipedia.org/wiki/Virama which "combines" 2 characters

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Can't reproduce this on 2.17, please let me know if it's still an issue
