### ISSUE TITLE
[BUG]: Hard option on Learning Cards uses wrong time

### ISSUE THREAD

**Issue by muffin4** [ankidroid/Anki-Android#14532]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- set Learning Steps to "1 10 60" on a deck
- create a new card
- select "Good" on its first appearance
- wait 10 minutes
- get the card again

### Expected behaviour

- the Again button should show 1 minute (returning the card to the first step)
- the Hard button should show 10 minutes (repeating the previous delay)
- the Good button should show 60 minutes (the next delay)

### Actual behaviour

- the Hard button shows 35 minutes

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = Google

Model = Pixel 4a

Hardware = sunfish

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 4a Build/TQ3A.230805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = af054d65-0fa8-491f-b1e6-41ea00a01c24

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

https://docs.ankiweb.net/studying.html#learningrelearning-cards

> If the card is on any subsequent step, Hard repeats the previous delay.

https://faqs.ankiweb.net/the-anki-2.1-scheduler.html

> Learning cards have 4 buttons instead of 3 - Hard repeats the current step after the first step, and is the average of Again and Good on the first step.

In the linux Anki desktop application the scheduling works as expected:

![android](https://github.com/ankidroid/Anki-Android/assets/71238026/3f7dbc4a-a21a-4181-a91d-54ac189eca45)
![linux](https://github.com/ankidroid/Anki-Android/assets/71238026/cbd16b47-163f-4ad2-9ae2-2ee3afb4930e)
![actually-35-minutes](https://github.com/ankidroid/Anki-Android/assets/71238026/88c48014-f3c6-4d85-83d0-bc54b0a3850c)

[Besto.apkg.zip](https://github.com/ankidroid/Anki-Android/files/12874703/Besto.apkg.zip)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by am009** [comment]
I discovered the same issue today. It is also mentioned here:
https://faqs.ankiweb.net/hard-good-interval-longer-than-good-easy.html

> Hard will repeat the current learning step (except on the first step, where it is the average of first and second steps)
