### ISSUE TITLE
[Bug] Study options activity incorrectly behaves as deck is empty in certain cases

### ISSUE THREAD

**Issue by lukstbit** [ankidroid/Anki-Android#14538]
###### Reproduction Steps

1. Have the **Default** deck empty 
2. In DeckPicker click on the counts of any deck that isn't empty
3. Study option activity opens and appears as empty with no option to study

###### Expected Result

The study option activity allows the user to start studying if the deck is not empty.

###### Actual Result

The study options activity behaves as it's empty:

![image](https://github.com/ankidroid/Anki-Android/assets/52494258/c3ee2ea2-2849-4355-9dd0-d0d28de37500)

###### Debug info

Latest HEAD

###### Research

The code calls through `Scheduler.cardCount()`-> `Scheduler._deckLimit()` where a call to `col.decks.active()` is made. This method always return 1, the id of the Default deck. If the Default deck is empty then you get this bug, otherwise the app behaves normally(although just be coincidence).

**Comment by lukstbit** [comment]
@dae The `Decks.active()` method reads the `ACTIVE_DECKS` config field(which I assume is initialized with 1, the Default deck) but this field is never updated. Any thoughts on this?

**Comment by dae** [comment]
This is an implementation detail, but reading the values from the active_decks table should be valid after the user has selected a deck.
