### ISSUE TITLE
[BUG]: No system keyboard when focusing on <input> text box in card view

### ISSUE THREAD

**Issue by infinity0** [ankidroid/Anki-Android#14546]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Add `<input type="text" />` to a card.
2. Preview it and focus in the input box. Try to type something.

### Expected behaviour

3. I should be able to type input into the input box in the card.

### Actual behaviour

3. No keyboard is available to type input, although you can long-press for a context menu that allows you to cut/copy/paste/etc.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = full

Manufacturer = samsung

Model = SM-T970

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-T970 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Safari/537.36

ACRA UUID = 95943709-6d61-46e3-b45d-a521971ddff8

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pratyaksh1610** [comment]
Working on it.
