### ISSUE TITLE
[Bug] Importing a .csv file shows error although data is imported

### ISSUE THREAD

**Issue by lukstbit** [ankidroid/Anki-Android#14573]
###### Reproduction Steps

1. Import a csv file(I built a simple 2 column/4 rows one, see image below)
2. See error dialog: _Error 500: unhandled request importDone_

###### Expected Result

The csv data is imported with no errors.

###### Actual Result

The csv data is imported but the UI shows an error:
<img src="https://github.com/ankidroid/Anki-Android/assets/52494258/7f0f0de0-ff47-4688-a479-98ac01b02017" width="320px" height="720px" /><img src="https://github.com/ankidroid/Anki-Android/assets/52494258/f564d1cc-1009-4e74-93cc-6aabac26b133" width="320px" height="720px" />

###### Debug info

Latest HEAD

###### Research

Tried to add _"importDone" -> withCol { backend.importDoneRaw(bytes) }_ in _AnkiServer.handlePostRequest()_, this gets rid of the error above(about importDone) but shows another error(csv data still imported correctly):

<img src="https://github.com/ankidroid/Anki-Android/assets/52494258/55a4edc0-98a8-47f4-89d2-1c9bca0458a1" width="320px" height="720px" />

- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
importDone is used by anki desktop to change the modality of the front window, and the backend doesn't know about it. In AnkiDroid you can probably just make it a no-op.

**Comment by lukstbit** [comment]
Thanks, this is going to help with #14540 as well.

> importDone is used by anki desktop to change the modality of the front window, and the backend doesn't know about it

I'm assuming this is also the case for `searchInBrowser` in the last screen of the import. 

And one more issue(with my limited knowledge) would be the `window.bridgeCommand` when closing the end screen.
