### ISSUE TITLE
[BUG]: Clicking on empty deck shows daily Study  limit reached snackbar

### ISSUE THREAD

**Issue by rishab247** [ankidroid/Anki-Android#14580]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Open the app
2. Tap on the menu button top-right of the screen
3. Tap on import
4. Select any  .csv or .apkg file
5. Tap on + button bottom-right of the screen
6. Tap on Create Deck
7. Enter the deck name 
8. Tap on the newly added deck

[Screen_recording_20231024_051629.webm](https://github.com/ankidroid/Anki-Android/assets/47221639/25df5211-38aa-46b9-8d5f-a52e7e582e7d)

### Expected behaviour

Display a snackbar showing"This deck is empty"

### Actual behaviour

Display a snackbar should show "Daily Study limit is reached"

### Debug info

```text
AnkiDroid Version = 2.17alpha1-debug (b65f426f1182ea410539e30c0e1c888faf21d206)

Android Version = 13

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone_x86_64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone_x86_64 Build/TE1A.220922.034; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = d9e65ac1-2bf2-449d-b277-6dec2901688d

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
I just checked and this bug doesn't seem to be present with the latest changes we've done(since alpha1).
When the new alpha is released please ping this issue if you still see the issue.
