### ISSUE TITLE
 Feature request: Macking add card flow consistent

### ISSUE THREAD

**Issue by rishab247** [ankidroid/Anki-Android#14582]
**Is your feature request related to a problem? Please describe.**
While adding cards user can leave Back Fields empty and make a card with incomplete data. which can cause confusion while memorizing. Users can also add duplicate data while in a hurry to create multiple cards.
![image](https://github.com/ankidroid/Anki-Android/assets/47221639/2624fb2c-a0cd-4e41-8f48-153575681e60)

**Describe the solution you'd like**
Make Back Fields mandatory and prevent users from creating cards without it.
Also, don't let them create cards with duplicate data.

**Comment by david-allison** [comment]
Thanks for the feature request! 

We aim to be consistent with Anki Desktop, so this feature will need to be in Anki Desktop before we consider it.
