### ISSUE TITLE
Second confirmation on delete.

### ISSUE THREAD

**Issue by StyraxBenzoin** [ankidroid/Anki-Android#14585]
**Is your feature request related to a problem? Please describe.**
I sometimes like to check the card info from the card browser 'three dots' menu, but the option is dangerously close the the 'delete notes' option. More than several times I've accidentally finger jabbed the 'delete notes' and lost a card. If I'm quick enough a little toast notification pops up at the bottom to say the card was deleted, and offers an undo option, but it's very quick and I sometimes miss it.

**Describe the solution you'd like**
A secondary confirmation button. E.g. 'n cards will be deleted. Are you sure?'

**Describe alternatives you've considered**
Currently the only alternative I have found to restore the card is to force a full one way sync from AnkiWeb. However, if there wasn't a sync recently, there's risk of losing reviews. I think prevention is better than cure?

**Additional context**

![Screenshot_20231020_215500_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/66492803/fa67faf8-59ba-4a5b-be16-a02cf99420ad)

**Comment by david-allison** [comment]
"Undo last review" should change to 'undo delete notes' once you click it

**Comment by StyraxBenzoin** [comment]
Thank you for pointing that out, I didn't know that. I tested it with a dummy card and it worked, however, it's not clear that that will be the behaviour of the undo button, not just 'undo last review'. It has no description. 

Also this only works if you go into review mode for that specific deck the card was deleted from. If you happen to go into another deck and then back again, the undo button is greyed out. 

Also if there are no reviews left today for that deck, you can't get to the review mode to even access the back button.

**Comment by david-allison** [comment]
The undo menu should also be available on the Card Browser, as seen in your screenshot above

**Comment by pavreh** [comment]
With the legacy backend, if you switch between decks, the undo button is really lost. The undo works properly with the new backend. You can enable the new backend in advanced settings.

**Comment by StyraxBenzoin** [comment]
> The undo menu item should also be available on the Card Browser, as seen in your screenshot above

Thank you, I didn't see that before. Tested it a it works even after navigating away from the browser screen and back again.

**Comment by StyraxBenzoin** [comment]
> With the legacy backend, if you switch between decks, the undo button is really lost. The undo works properly with the new backend. You can enable the new backend in advanced settings.

Thanks for the suggestion. However, since the new backend is under 'Experimental' and says;

"UNSTABLE. Do not use on a collection you care about. NOT reverted on app close"

I'm hesitant to use the feature, as my collection is something I very much do care about.

**Comment by pavreh** [comment]
The new backend will be default in AnkiDroid 2.17 so this issue will be resolved there.
