### ISSUE TITLE
[BUG]: With FSRS enabled, Card Info doesn't show Stability, Difficulty, Retrievability

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14599]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

After updating to alpha2 and syncing, the card info still does not show DSR even though I have FSRS enabled in the Desktop since about 2 weeks and now in AnkiDroid too.

Edit: The DSR appears after I review the card. But, since the memory states have already been calculated on Desktop, they should appear on AnkiDroid even before reviewing the card on AnkiDroid.

### Expected behaviour

The card info shows DSR just like Desktop.

### Actual behaviour

The card info doesn't show DSR.

### Debug info

```text
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 13

ProductFlavor = full

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
I can't reproduce this. It sounds like you may have had a sync conflict. You could try forcing a one-way sync from the desktop.

**Comment by user1823** [comment]
I think the reason is that the cards were already synced to AnkiDroid before updating AnkiDroid.

Possibly, AnkiDroid v2.16 didn't save the memory states and then after updating to v2.17, AnkiDroid didn't have any memory states to show. Possibly, sync didn't resolve this because there weren't any "new" changes to sync.

A one-way sync resolved this issue. But isn't there any better way to handle this automatically?

**Comment by dae** [comment]
I guess that's possible. Anki 23.10 recommends people not enable FSRS until all their clients support it, so they shouldn't hit this.
