### ISSUE TITLE
[BUG]: FSRS settings don't sync reliably

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14598]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

After updating to 2.17 alpha2, the deck options didn't contain the FSRS weights and retention that I had configured on the Desktop.

After opening the Desktop Anki, I changed the SM2 retention (it was reset, not sure why) and pressed sync on Desktop and then on AnkiDroid. Then, AnkiDroid showed the correct FSRS settings except the SM2 retention.

### Expected behaviour

After sync, the FSRS settings in AnkiDroid should be exactly the same as that on Desktop.

### Actual behaviour

Settings don't sync properly.

### Debug info

```text
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 13

ProductFlavor = full

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
The first issue sounds like a conflict I mentioned on #14599. sm2_retention getting reset to 0.9 is a bug in the desktop code, and I'll fix it before the stable release. AD should automatically get it in alpha3.

**Comment by mikehardy** [comment]
Just a note that we may get alpha3 here prior to getting new anki / anki-backend build here - but we *will* get the fix whenever it's fixed in desktop and we pull it htrough, can follow https://github.com/ankidroid/Anki-Android-Backend/pull/314 as merging that then pulling it through here is when we'll have it

**Comment by user1823** [comment]
> whenever it's fixed in desktop

Well, it has already been fixed in the desktop and rc3 includes the fix.

> we may get alpha3 here prior to getting new anki / anki-backend build here

No worries, but thanks for informing.
