### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Firewater21** [ankidroid/Anki-Android#14605]
So I've been trying to the new 2.17 aplha 2 of ankidroid for the FSRS4 but there's this glitch in the card where the color of the text is written on the card itself. 
![Screenshot_2023-10-28-22-10-59-640_com ichi2 anki-edit](https://github.com/ankidroid/Anki-Android/assets/149249012/76122121-6f0e-488b-a565-620830600011)
![Screenshot_2023-10-28-22-11-20-950_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/149249012/26e06713-3aad-41d5-9793-6304b5d616c9)

###### Reproduction Steps

1. Unknown 

###### Expected Result
White text 

###### Actual Result
Black text

###### Debug info
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 13

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2102J20SG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; M2102J20SG Build/TKQ1.221013.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = 59dab852-30af-4114-8e82-bb304c5ede34

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
This isn't a bug. That's because you copied/pasted something that had a color. Similar to what other softwares like Microsoft Word do. 

Delete the `<div>...` part and that's solved.
