### ISSUE TITLE
[BUG]: Snackbar shown on top of FAB

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#14609]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. The snackbar is shown on top of the FAB
2. When creating a new Deck(empty) and clicking it shows a wrong snackbar 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/074f59fe-7c3f-4d7b-8ecc-90cb9e22ba07)

### Expected behaviour

1. FAB is on top
2. Correct snackbar

### Debug info

```text
AnkiDroid Version = 2.17alpha1-debug (f5f1493ace379b94e036a9aeb61da11f5dd7ae18)

Android Version = 13

ProductFlavor = amazon

Manufacturer = OnePlus

Model = EB2101

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; EB2101 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = 28d860a4-c0eb-46b0-8d66-a3965d0d52b8

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
https://m3.material.io/components/snackbar/guidelines#f762d356-69a1-402c-ab69-3621c23f91d2

And I agree with material. UI elements shouldn't be moving around and causing misclicks.
