### ISSUE TITLE
Remove estimated time required to complete the reviews

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14602]
AnkiDroid still shows the estimated times, though Anki removed them years ago.

![Screenshot_20231028-163352~2](https://github.com/ankidroid/Anki-Android/assets/92206575/74cf53f3-3c18-43a3-8918-6b8cff819358)
![80176a7ab119b01bc1f033ebfe579e3b760a8543_2_510x1000](https://github.com/ankidroid/Anki-Android/assets/92206575/3c4057b7-3b64-4276-a17b-8f38b4419883)

Also see: https://forums.ankiweb.net/t/show-more-info-about-deck-when-deck-is-clicked/31693/2

**Comment by RobozinhoD** [comment]
Doing it
