### ISSUE TITLE
[Bug] AnkiDroid.A and AnkiDroid.B use the same folder/data

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#14601]
###### Reproduction Steps

1. Install AnkDroid.A and AnkiDroid.B 2.17alpha2

###### Expected Result
Each installation uses its own folder

###### Actual Result
AnkiDroid.A and AnkiDroid.B use the same folder/data so it is not possible use different databases.

###### Debug info
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 13

ProductFlavor = full

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = fc1a40d6-0d5b-4359-b9e5-298870da56f1

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Oh no! 👀

**Comment by mikehardy** [comment]
I assigned this to myself just so I don't forget about it - but if anyone else has time before me to look at + fix it, that would be incredible

My assumption was that with scoped storage it would be in app-specific storage so setting separate directories wouldn't even be necessary...

**Comment by BrayanDSO** [comment]
This isn't new. They used the same `AnkiDroid` public folder before scoped storage and just kept using it because they are `full` builds. 
Never there was a specific public folder for parallel builds

If you try to build a `play` parallel version, they will work accordingly in their app-specific directories, since the app id is different.

**Comment by BrayanDSO** [comment]
>  so it is not possible use different databases.

And the directory can be changed at Settings > Advanced, so it is possible to use different collections

**Comment by mikehardy** [comment]
Ah! That is documented, I thought that was clear. I forgot that this would still happen for full builds.

Here is the documentation:

> installing several parallel versions of AnkiDroid besides the normal AnkiDroid and setting a unique collection path in each one

https://github.com/ankidroid/Anki-Android/wiki/FAQ#how-to-use-different-anki-profiles

I don't think there is more to do here
