### ISSUE TITLE
ankidroid export multiple decks as apkg

### ISSUE THREAD

**Issue by Benjamin-Watson0** [ankidroid/Anki-Android#14604]
**Is your feature request related to a problem? Please describe.**
Ankidroid can only export one deck as apkg.

**Describe the solution you'd like**
I hope that ankidroid export all Decks as apkg.Just like anki on PC.

**Describe alternatives you've considered**
no

**Additional context**
Guys, thank you so much for reading my request.❤️
I've recently had a slow connection to ankiweb in my area and my deck contains a lot of media files.
Therefore, I finally used file export to achieve multi-platform synchronization.
After investigation, the format of apkg is the most consistent with my philosophy, because it does not cover all decks when exporting, but looks for changes, just like ankiweb.
Unfortunately, ankidroid can only export a single deck as an apkg file. I don't always remember which decks made changes. So I prefer to export the entire deck as apkg.
Thanks for your help, hope this feature can be implemented. In this way, synchronization can be achieved even without going through ankiweb.😊

**Comment by mikehardy** [comment]
Hi there!
I'm not sure I understand.
It appears to be possible from the deck list three-dot menu at top right to export all decks as a .colpkg (collection package, that is, more than one deck - one deck is an apkg).
You may choose to do it with or without scheduling and with or without media
It seems like this is what you are asking for ?

**Comment by mikehardy** [comment]
Okay....that is quite different than the title you gave the issue ("ankidroid export all decks as apkg")
I'm not sure I understand the feature request really.

Is this something that Anki Desktop does?

If Anki Desktop does not include this functionality, this will be closed as something we cannot support unless they add it first.

If Anki Desktop does include this functionality, we can leave this open and see about exposing the functionality here

**Comment by david-allison** [comment]
Potential alternative if your regular changes aren't media heavy:

Even on a slow connection, an AnkiWeb sync (excluding media) should be a few KB

* Settings - Sync - Disable 'Fetch Media on Sync'

====

When you do have internet capacity for a media sync, only the initial download of media is truly heavy, afterwards it only syncs changes

**Comment by mikehardy** [comment]
Apologies - your comments still do not seem consistent to me.
Your final comment, you say "Android *has* the ability to export all decks as apkg files".
But you are discussing this as if it does not.

The title of the issue does not seem to relate to the feature you want.

I asked you directly to confirm your actual feature request as I understand it:

> exporting multiple cards as apkg files

So, to be as clear as possible, please confirm if this understanding is correct:

- Anki Desktop allows you to select multiple cards (not a deck, not the whole collection, just a group of cards) and export them as an apkg
- AnkiDroid does *not* allow you to select multiple cards and export them as an apkg
- You want AnkiDroid to be able to export multiple cards as an apkg

Is that correct?

**Comment by david-allison** [comment]
AnkiDroid supports exporting multiple cards as an apkg if running with the new backend: 

* #8045
* https://github.com/ankidroid/Anki-Android/pull/12524

**Comment by mikehardy** [comment]
I wonder if you are on an old version of Anki Desktop? If you are trying to export all decks now, it *should* be in a "colpkg" ("Collection Package") file, and Anki Desktop should also be operating with the same format (.colpkg vs .apkg).

".apkg" files are now only used for single decks

https://docs.ankiweb.net/exporting.html?highlight=colpkg#collection-colpkg

Can you verify you are using up to date Anki Desktop? It looks like it should be version 23.10 https://apps.ankiweb.net/#download

**Comment by dae** [comment]
When .colpkg is selected, it forces all decks and scheduling to be included. .apkg is more flexible - you can have multiple decks if you select 'all decks', or when you export notes from the browser screen.

**Comment by mikehardy** [comment]
So, it seems that for AnkiDroid to behave like Anki Desktop for export, we need to examine the dialog choices desktop presents to the user, but there is apparently a functionality gap where it is either "all" (as colpkg) or "one deck" (apkg) on AnkiDroid, and we're missing the middle state of "one or more, possibly all" (as apkg) in ankidroid

Assuming I got that correct, then that's the issue to solve here and someone will need to take it up, I'll tag it to match my understanding
