### ISSUE TITLE
[Bug] Re-rendering positioning error

### ISSUE THREAD

**Issue by Pr0pHesyer** [ankidroid/Anki-Android#14610]
###### Reproduction Steps

1. Open a deck,shows the front of a card
2. Switch to other apps,capture more memory for making sure it will re-rende when get back to Ankidroid
3. Get back to Ankidroid,card will be re-render in worry position

NOT ALWAYS CAN BE REPRODUCT
I think the reason is that the top was set to the top of the whole screen instead of the top title bar when re-rendering. 

###### Expected Result
![Screenshot_20231029-150710](https://github.com/ankidroid/Anki-Android/assets/74277431/7d8cf732-3d84-43e7-8cf6-dd087b52e84c)

###### Actual Result
![Screenshot_20231029-144735](https://github.com/ankidroid/Anki-Android/assets/74277431/6db92511-8ee9-4725-8ab3-7645eb2cd06f)

The word "afftection" is cover by title bar

###### Debug info
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 12

ProductFlavor = play

Manufacturer = LGE

Model = LM-G820N

Hardware = alphaplus

Webview User Agent = Mozilla/5.0 (Linux; Android 12; LM-G820N Build/SKQ1.211103.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = 10ee99ce-643f-44ad-b2f4-53df9a6e2b36

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Closing as "can't reproduce".

We need concrete steps to determine if this is a problem so we can resolve it
