### ISSUE TITLE
[BUG]: Timebox time limit is counting time spend outside of reviewing.

### ISSUE THREAD

**Issue by szalejot** [ankidroid/Anki-Android#14614]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Set "Timebox time limit" to non-zero value. Do some reviews, exit to main screen (all decks view), do more reviews.

### Expected behaviour

"Timebox time limit" should reset each time the user leaves reviews and goes to the main screen.

### Actual behaviour

I have "Timebox time limit" set to 5.
Some failure scenarios:

1. Do reviews for 1 minute.
2. Exit to the main screen, wait 10 minutes.
3. Start reviewing of a deck.
4. "Timebox reached" info shows immediately.

Another scenario:
1. Do reviews for 1 minute.
2. Exit to the main screen, wait 1 minute.
3. Do reviews for 3 minutes.
4. "Timebox reached" info shows.

Additionally, these "failed" info can show 0 or even negative number of cards done. See screenshots below.
![Screenshot_2023-10-29-11-35-28-163_com ichi2 anki-edit](https://github.com/ankidroid/Anki-Android/assets/3840404/1039be9a-7add-4d6e-9eef-eb51a55e8a45)
![IMG_20231029_105128](https://github.com/ankidroid/Anki-Android/assets/3840404/9f07887c-c64e-4f37-b0db-0ce27d3808e3)

### Debug info

```text
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 13

ProductFlavor = full

Manufacturer = Xiaomi

Model = 21081111RG

Hardware = mt6893

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 21081111RG Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = 32cd7308-64af-439f-aa74-37ffb8dd0ae1

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [x] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by matejdro** [comment]
First failure scenario appears to also across longer timespans (hours). Last night this happened:

1. I have installed the alpha and completed the deck in the evening
2. In the morning (10+ hours after deck was completed), I started the review again and immediately got the Timebox popup.

**Comment by david-allison** [comment]
I believe this will be fixed in #14614, once this is merged & released, please ping the issue if this continues to be a problem

**Comment by david-allison** [comment]
Needs confirmation if this is fixed in the next alpha

**Comment by mikehardy** [comment]
@szalejot is this still happening? We've got fixes released that were in this area - https://github.com/ankidroid/Anki-Android/releases

**Comment by szalejot** [comment]
With the current alpha, it works correctly.

**Comment by mikehardy** [comment]
Yes!! Thanks for re-testing and reporting back
