### ISSUE TITLE
[BUG]: 2.17alpha (1 or 2) Exception browsing deck- Wrongid: No card with id

### ISSUE THREAD

**Issue by BorisNA** [ankidroid/Anki-Android#14623]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Use 2.17.alpha1 or alpha2, sync collection or import it
2. Open card browser, set it to _display notes_
3. Open one of the decks

### Expected behaviour

Deck notes (cards) are shown (as on the desktop Anki 2.1.66 or AnkiDroid 2.16.5)

### Actual behaviour

Message: com.ichi2.libanki.exception.Wrongid: No card with id 1516347476210 is shown. No cards in the deck

### Debug info

```text
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 11

ProductFlavor = full

Manufacturer = Google

Model = Pixel 4a

Hardware = sunfish

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 4a Build/RQ3A.211001.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = a1db5b2e-3d3a-4b46-9345-cab15df6c1e1

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Collection and all decks work Ok on on the desktop 2.1.66
V3 scheduler with FSRS js-code is used (old copy-paste one)
In 2.17.alpha1/2 some decks (sub-decks) could be viewed in the browser correctly, some - give this error. Cards appear to be Ok though.

I've tried to clear the app's db (db files in Android/com.ichi2.anki/files/.... ) and get the collection from AnkiWeb - the error is still shown.

![image](https://github.com/ankidroid/Anki-Android/assets/7961527/f324124d-e186-42d9-9ec4-86adc9a5ff4b)

UPD. Note with such id indeed exists in the database. It looks to be Ok, it could be correctly viewed through the card browser or on the desktop.

UPD2. Small apkg export is attached (3 cards). It gives this error if imported with 2.17alpha on mobile, and works Ok with 2.16.5. 

[deutsch_deck.zip](https://github.com/ankidroid/Anki-Android/files/13227988/deutsch_deck.zip)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BorisNA** [comment]
I've opened the collection db directly.

Table 'notes'
- A note with such id (1516347476210) does exist. This is a first note of one of the decks. This note is Ok and suspended. Opens Ok in 2.17alpha1 (table "notes")

Table 'cards'
- Of course, there are no cards in the DB with such id
- There are two cards (as it should be) with such nid (suspended, never seen, usn=0 - doesn't know what it is)

Table 'revlogs'
- No revlogs with such id or cid 



I wonder if the message _really mentions a card_ (then something is definitely completely wrong), or if the message meant "a note" (bad wordings).

**Comment by dae** [comment]
Perhaps it relates to whether the browser is set to show cards or notes?

**Comment by BorisNA** [comment]
Update. I've made an apkg-export with only 3 notes that reproduces this error if imported in AnkiDroid 2.17alpha
