### ISSUE TITLE
[BUG]: JsonError when syncing with custom sync server on v2.17alpha2

### ISSUE THREAD

**Issue by AdmerStroh** [ankidroid/Anki-Android#14635]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Enable option "own sync server" and specify an instance
2. Login to the instance
3. hit the sync button

### Expected behaviour

It should sync without problems, as it does for me with v2.16.5

### Actual behaviour

I get the following error:

`JsonError { info: "missing field 'media_usn' at line 1 column 115" }`

### Debug info

```text
AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 14

ProductFlavor = full

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 6a Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.53 Mobile Safari/537.36

ACRA UUID = 2ec026a1-ab05-41e7-a6d8-695c304b8dd5

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Thank you for testing the alpha versions, that is a huge help to us.
I think 2.17alpha2 will likely only work with Anki Desktop 23.10 in it's pre-release versions or - just today! - in it's final released version. We were incorporating 23.10 Anki Desktop pre-release code (which includes sync code....) in order to get FSRS out and in testing, and I think for local sync servers that implies you also need to be running the same code from desktop as the local server

Can you install 23.10 on the desktop and let us know if you sync correctly again?

**Comment by choralbari** [comment]
In my case, I had an old version of the sync server running. I had to exit it and start the new version from Anki 23.11. However, in order to do that, I needed the work around from https://github.com/ankitects/anki/issues/2794.

**Comment by akharrou** [comment]
I just had the same issue today! 

```
JsonErro {info: "missing field media_usn at line 1 column 114"}
```

**Comment by dae** [comment]
Please read 'things to be aware of': https://docs.ankiweb.net/sync-server.html

Please also note this is the issue tracker for AnkiDroid - questions about AnkiMobile should be posted here: https://docs.ankimobile.net/support.html

**Comment by akharrou** [comment]
> Please read 'things to be aware of' in the top section: https://docs.ankiweb.net/sync-server.html
> 
> Please also note this is the issue tracker for AnkiDroid - questions about AnkiMobile should be posted here: https://docs.ankimobile.net/support.html

Hey thanks @dae for that. I wasn't aware. Also, this bit of the doc helped "Newer clients may depend on changes to the sync protocol, so syncing may stop working if you update your Anki clients without also updating the server.", i updated anki (`pip install --upgrade anki`), and that fixed it. thanks

**Comment by mikehardy** [comment]
Glad that resolved it! Sounds like it's not actionable here, other than addition to the FAQ, which I've done here

https://github.com/ankidroid/Anki-Android/wiki/FAQ/_compare/b357a6314789c139b2fb3cbe588aa4fdeda6cb35...0123679a5bac01c0433fd8d727f658508b1b57a7

**Comment by ccchan234** [comment]
> > Please read 'things to be aware of' in the top section: https://docs.ankiweb.net/sync-server.html
> > Please also note this is the issue tracker for AnkiDroid - questions about AnkiMobile should be posted here: https://docs.ankimobile.net/support.html
> 
> Hey thanks @dae for that. I wasn't aware. Also, this bit of the doc helped "Newer clients may depend on changes to the sync protocol, so syncing may stop working if you update your Anki clients without also updating the server.", i updated anki (`pip install --upgrade anki`), and that fixed it. thanks

also for this line: Newer clients may depend on changes to the sync protocol, so syncing may stop working if you update your Anki clients without also updating the server..

I am on a Chromebook. ankidroid6 2.16.x wont work.
ankidroid6 2.17.x do work, but if I need to use the self sync server,
it now forces my other 4PCs to upgrade from a stable 2.1.54 to not even 2.1.60 but 23.10+ and esp should be 23.12.x which is the same code base.

I appreciate the author dae grant us such a great tool, and in many platforms it's free of charge.
but I would appreciate if there is not forcing of us to upgrade... instead, as what microsoft did, I am willing to pay to keep on old versions.

I am tired to do arm race /w google on android's file system (document provider) and I am tired of these. thanks
