### ISSUE TITLE
[BUG]: Ugly blue top bar in Black theme in Deck info page

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14642]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Use 2.17 alpha 3
- Enable Black theme.
- Click the due counts of any deck to open the deck info page.

### Expected behaviour

The Deck info page doesn't look ugly.

Screenshot from an earlier version (same up to 2.17 alpha 2):
![278809505-3c4057b7-3b64-4276-a17b-8f38b4419883](https://github.com/ankidroid/Anki-Android/assets/92206575/84c25960-fad5-445e-b01d-4a5b06095c41)

### Actual behaviour

The page has a blue top bar that looks ugly.

![Screenshot_20231102-074921~2](https://github.com/ankidroid/Anki-Android/assets/92206575/73543ec4-5074-4c6e-a3ab-d34577f0b7c3)

### Debug info

```text
AnkiDroid Version = 2.17alpha3 (42a8c8c55c200f372b0bd0b462e4b58554b72fe5)

Android Version = 13

ProductFlavor = full

ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
😆  - well, we (where we is the illustrious @BrayanDSO ) are in the process of implementing Material3 and it's a big UI / layout / theming change. I expect this won't be the only UI item that has a visual regression but the overall change is necessary and good.

Anything else you see definitely point it out, it is appreciated

**Comment by user1823** [comment]
A similar blue bar now appears on the deck chooser that is used to change the deck of a card from the note editor.

**Comment by mikehardy** [comment]
We just built an alpha (2.17alpha3) yesterday, so it's still rolling out (although you clearly got in on that early!) but this will be in the next alpha or any install you build from source starting now. Thanks again for the report
