### ISSUE TITLE
Add `Show play buttons on cards with audio` preference as in Anki Desktop

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14649]
**Is your feature request related to a problem? Please describe.**
Anki Desktop has a feature called  `Show play buttons on cards with audio`, but AnkiDroid doesn't have it

**Describe the solution you'd like**
Add the pref to AnkiDroid

**Additional context**
![image](https://github.com/ankidroid/Anki-Android/assets/69634269/37388d7f-7313-4ce6-86f9-9f04d228dddf)

**Comment by david-allison** [comment]
https://github.com/search?q=repo%3Aankitects%2Fanki%20hide_audio_play_buttons&type=code

https://github.com/ankitects/anki/blob/e327195470824074465657f98bb0282c7c93a56e/qt/aqt/main.py#L587-L592
