### ISSUE TITLE
[full build] - Sync From AnkiWeb -> Can't create AnkiDroid folder

### ISSUE THREAD

**Issue by BEST8OY** [ankidroid/Anki-Android#14650]
###### Reproduction Steps

1. Clean Install AnkiDroid Alpha 3 
2. Open the app
3. Choose Sync from AnkiWeb
4. Enter your mail and it says it can't create AnkiDroid folder  

###### Expected Result
Before entering login credentials, it should ask for All files access which is the way it is when you choose Get Started

###### Actual Result
Error not being able to create AnkiDroid folder
`com.ichi2.anki.exception.StorageAccessException: Failed to create AnkiDroid directory / storage/emulated/0/AnkiDroid
`
###### Research
- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by magicgoose** [comment]
How do you work around this?  
I get various sorts of this error even after manually granting storage access permission to the app.  
Even if I manually create that folder via adb shell.

**Comment by magicgoose** [comment]
Found it, need to proceed without an account first

**Comment by david-allison** [comment]
Hi @BEST8OY could you enter the debug into from `Settings - About`. Thanks!

**Comment by BEST8OY** [comment]
> Hi @BEST8OY could you enter the debug into from `Settings - About`. Thanks!

AnkiDroid Version = 2.17alpha5 (4fc8af92973d8d502e0139d0dd5372415444ca1f)

Android Version = 13

ProductFlavor = full

Manufacturer = Xiaomi

Model = Mi 9 Lite

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Mi 9 Lite Build/TQ3A.230901.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = 2d4473c6-c308-41cf-a884-64d4323e9ba6

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by BEST8OY** [comment]
@david-allison 
Is it not reproduced?

**Comment by david-allison** [comment]
Still unresolved, would you like to submit a PR?

**Comment by BEST8OY** [comment]
> Still unresolved, would you like to submit a PR?

I'm not knowledgeable enough to do so.

**Comment by david-allison** [comment]
For reference

https://github.com/ankidroid/Anki-Android/blob/f94a0cba75dd61e1bb806ed40adf9ca8c2d4bd54/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L537-L542
