### ISSUE TITLE
First syncing error: "missing original size"

### ISSUE THREAD

**Issue by BEST8OY** [ankidroid/Anki-Android#14651]
###### Reproduction Steps

1. Clean install Alpha 3
2. Open app and choose Get Started and allow file access.
3. Tap on sync icon
4. Enter your credentials.
5. It should produce an error with number 500 in it (sorry I didn't note the error🥲)
6. Close Ankidroid and Reopen it and it'll sync fine.

###### Expected Result
It should sync normally on first run.

###### Actual Result
It didn't

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
was this the error ?
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/d30e966b-4f58-4b07-9e40-29c5c8470734)

**Comment by BEST8OY** [comment]
> was this the error ? ![image](https://user-images.githubusercontent.com/48384865/280492118-d30e966b-4f58-4b07-9e40-29c5c8470734.png)

Yes
I even forgot the correct number in the error which was "400" 😅

**Comment by criticalAY** [comment]
Reproduced! 
 @david-allison could you please add the 2.17 label here

**Comment by Aditya13s** [comment]
@david-allison please assign me i want to work on this issue

**Comment by david-allison** [comment]
Also mentioned with proposed solution:

* Ref: https://github.com/ankidroid/Anki-Android/issues/14219#issuecomment-1834380925
