### ISSUE TITLE
[UI] Permissions: Insufficient Padding

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#14653]
The permissions dialog needs more left padding on the switch control

<details>

<summary>Screenshot: Permission Screen</summary>

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/939edbaa-5eaa-48f2-8610-291445b1cef6)

</details>

Ideally we should match how Preferences looks

<details>
<summary>Screenshot: Preferences</summary>

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/d89144ce-34b2-481b-8016-5dfa625dbb31)

</details>

[Relevant code](https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/main/res/layout/permission_item.xml) ([permalink](https://github.com/ankidroid/Anki-Android/blob/93f4312a0f5918f892a26b8e88537e47ef003ea9/AnkiDroid/src/main/res/layout/permission_item.xml))

**Comment by RobozinhoD** [comment]
Ill do it

**Comment by criticalAY** [comment]
umm it's marked good first you sure you want to take it?

**Comment by Aditya13s** [comment]
@david-allison please assign me i want to work on this issue.

**Comment by criticalAY** [comment]
> @david-allison please assign me i want to work on this issue.

Heyo! I hope you please go through the issue once  :) before making a comment there is an open PR for this issue so it's already being worked on
