### ISSUE TITLE
Can't edit a note with empty first field

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14664]
Anki does not allow to create note with empty first field (except with an add-on), but it allows to edit a note and empty the first field. I've a ton of note with empty first field. I can't edit them anymore with ankidroid. 
Could you please differentiate the add mode and the edit mode, and still allow empty first field during edition

**Comment by criticalAY** [comment]
I remember that I worked on this code but I made it necessary for the Add card only not edit note, upon inspecting I found Brayan placed the condition there

**Comment by criticalAY** [comment]
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/f4e3b505-f9b3-4085-a458-e36ed14b6bc5)

![image](https://github.com/ankidroid/Anki-Android/assets/48384865/3197b7fe-5c66-42d1-b235-129ca9c7a057)

**Comment by criticalAY** [comment]
Not sure if this is helpful but It would make AnkiDroid consistent with Anki so I am taking off this condition
