### ISSUE TITLE
[UI] Deck Options : Insufficient Margin

### ISSUE THREAD

**Issue by Prince-kushwaha** [ankidroid/Anki-Android#14661]
###### Reproduction Steps
There is needs more left Margin and right Margin to save button 

![Deck Picker](https://github.com/ankidroid/Anki-Android/assets/65972015/da8668d4-6386-466d-b6b2-219176331c1e)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
i like to work on this issue

**Comment by Prince-kushwaha** [comment]
@BrayanDSO can i work on this issue

**Comment by Prince-kushwaha** [comment]
@david-allison can i work on this issue

**Comment by david-allison** [comment]
@Prince-kushwaha Sure!

**Comment by SanjaySargam** [comment]
@Prince-kushwaha Do you still want to work on this?
If not, I'm happy to take this

**Comment by Prince-kushwaha** [comment]
@SanjaySargam u can work on this issue

**Comment by SanjaySargam** [comment]
@david-allison 
The fragment is a WebView. I want to know how can I modify WebView.
Is it possible?

**Comment by david-allison** [comment]
@SanjaySargam Possible, but we haven't discussed the most effective way to do it yet. Best to start a conversation in Discord

**Comment by SanjaySargam** [comment]
> @SanjaySargam Possible, but we haven't discussed the most effective way to do it yet. Best to start a conversation in Discord

Ok

**Comment by neeldoshii** [comment]
> Possible, but we haven't discussed the most effective way to do it yet. Best to start a conversation in Discord

@david-allison Not sure, about will this be an optimal approach to solve it but if we could try to inject JavaScript into the WebView to manipulate the website DOM after the page has finished loading we can add suitable  margin between them. 

If you want I can release a draft PR over it.

**Comment by david-allison** [comment]
Let's not. It's much more ideal to work out the process to discuss + contribute changes upstream
