### ISSUE TITLE
Shift v3 scheduler from Experimental to Any Normal section

### ISSUE THREAD

**Issue by shundred** [ankidroid/Anki-Android#14671]
Anki desktop has dropped support for v2 scheduler and made v3 default. In my case (qt6 on windows 10) I could not even find v2 switch.
I have just started to use v3 on Ankidroid also. But due to its location in experimental section it makes one hesitant to turn on v3.
So for consistency between Anki and Ankidroid (given the developers believe v3 is stable enough on Ankidroid) shift v3 switch to any normal section and also turn it in by default.

**Comment by BrayanDSO** [comment]
Already done in 2.17. But thanks for the report
