### ISSUE TITLE
App becoming unresponsive after full sync on "Custom Sync Server"

### ISSUE THREAD

**Issue by shundred** [ankidroid/Anki-Android#14683]
###### Reproduction Steps

1. Set Custom sync server on anki 23.10 qt6 Windows and Ankidroid 2.16.5 with v3 scheduler active on both
2. Do Full sync from to Anki to custom server
3. Then also do Full sync (using settings) from custom server to Ankidroid
4. Disconnect Mobile from network between PC and Mobile. (keep mobile internet on)
5. Close Ankidroid
6. Launch Ankidroid

###### Expected Result

Ankidroid working without any error

###### Actual Result

1. At first I saw all the parent decks expanded with Blue, Green and Red number all zero.
2. After that an error message everything appears and app becomes responsive
3. I close the app and relaunch it, this time decks shows as expected, but if you click on any deck expansion arrow the app becomes unresponsive. At this moment if you close the app and relaunch it, this step "3" will repeat.
4. If you Launch and click on any deck expansion arrow and wait for some seconds an error message will be shown and app will start to work fine.

![Screenshot_20231108-083252_AnkiDroid.png](https://github.com/ankidroid/Anki-Android/assets/95898042/92455e59-2b70-4467-8dd1-50374594e135)

Although I have Automatic Synchronisation in Ankidroid turned off, looks like the app is not respecting it at first.

Earlier I was using Anki 2.1.65 qt5 with v2 and Ankidroid 2.16.5 with Experimental (v3) turned off. And that setup used to work fine.

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! If you are using 23.10 on the desktop and using it's built in sync server, I think you may want to use the 2.17alpha series here https://github.com/ankidroid/Anki-Android/releases as it includes the 23.10 anki library that should provide best compatibility

**Comment by shundred** [comment]
Thanks for quick reply.
I am waiting for stable release, just wanted to bring into developers notice this behaviour. So they can take action for next release if required.

**Comment by mikehardy** [comment]
The developers are all working + using the up to date (that is: "alpha") releases so we likely won't notice. Unless we hear a report by someone that tries the latest release and reproduces it there won't be any action. We can reopen if someone tries 2.17 and reproduces
