### ISSUE TITLE
[Bug] In some languages, reviews graphic label shows overflow.

### ISSUE THREAD

**Issue by gugutu** [ankidroid/Anki-Android#14688]
###### Reproduction Steps

1. Enter the statistical interface.
2. Check the reviews graph ->Time.

###### Expected Result

![Screenshot_2023-11-09-00-58-33-783_com.ichi2.anki.jpg](https://github.com/ankidroid/Anki-Android/assets/59798823/8bed4579-80c5-4a9b-95b5-1e7a0343c065)

###### Actual Result

![IMG_20231109_005756.jpg](https://github.com/ankidroid/Anki-Android/assets/59798823/ec350792-8c8d-4476-a789-d0b8c0a7043a)

###### Debug info

AnkiDroid Version = 2.17alpha3 (42a8c8c55c200f372b0bd0b462e4b58554b72fe5)

Android Version = 11

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2006J10C

Hardware = mt6885

Webview User Agent = Mozilla/5.0 (Linux; Android 11; M2006J10C Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/117.0.0.0 Mobile Safari/537.36

ACRA UUID = 3c64139d-2b12-4753-b518-62a8dad67316

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by gugutu** [comment]
Anki desktop does not have this issue.

![IMG_20231109_011229.jpg](https://github.com/ankidroid/Anki-Android/assets/59798823/7e5d85ef-11d6-4731-a4a8-56e06122fd33)

**Comment by BrayanDSO** [comment]
Closing as upstream issue. Please report it at the anki forums
