### ISSUE TITLE
[BUG]: Auto advance not working as expected on cards with TTS.

### ISSUE THREAD

**Issue by thyarles** [ankidroid/Anki-Android#14681]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Create a card with some text enclosed on the TTS service on the answer side.
2. Configure auto advance to show answer in 1 second and advance in 3 seconds.
3. After the TTS stops, the card only auto advance after 60 seconds (the max configuration).

### Expected behaviour

`auto-advance time = time to play TTS + auto-advance time`

### Actual behaviour

`auto-advance time = time to play TTS + 60 seconds`

### Debug info

```text
AnkiDroid version = 2.16.5
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
I suspect: the deck-specific option has only been set for 1 of 2 of the settings, therefore the incorrect default is used

https://github.com/ankidroid/Anki-Android/blob/dbf355e5a3425614f49f514df72607cc6bb77122/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/AutomaticAnswer.kt#L262-L289
