### ISSUE TITLE
 icons are not displayed in the taskbar.

### ISSUE THREAD

**Issue by BCFCODE** [ankidroid/Anki-Android#14682]
In the latest original release of Windows 11, it was tested and found that the icons are not displayed in the taskbar.

###### Actual Result

![image](https://github.com/ankidroid/Anki-Android/assets/78473407/7470493f-1596-4c95-991e-3d82f9ebe2b1)

**Comment by mikehardy** [comment]
Hi there! This repository is for bug reports related to AnkiDroid - the Anki program for Android mobile devices.
Your issue seems to be about Anki Desktop, I believe you'll want to head over here ---> https://faqs.ankiweb.net/

**Comment by BCFCODE** [comment]
oh! I see, thanks to metion it
