### ISSUE TITLE
[BUG]: 2.17: videos no longer autoplay

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14693]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Have a card with video. Open reviewer to review it

### Expected behaviour

Relatively similar to the one we had before. Autoplay it (unless it's answer side and it was on question side), as soon as the card appear on screen.

### Actual behaviour

Just after tapping to reveal the card, I need to tap a second time on the video to play it.  And I see the animation showing the video loading (it's short, so I don't know whether it's actually slower than the previous video player or whether it's just a feeling caused by seing this extra animation.

### Debug info

```text
2.17.alpha3
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Adding an `autoplay` here would solve it https://github.com/ankidroid/Anki-Android/blob/0834991ac817bfcb6760537664400380a5d5ab82/AnkiDroid/src/main/java/com/ichi2/libanki/TemplateManager.kt#L196

Although, I don't know which is the preferred behavior, autoplay or not. And I can think of use cases about the both of them. Some simple JS can solve that while this isn't discussed.

---
> And I see the animation showing the video loading

Discussed that a little here https://github.com/ankidroid/Anki-Android/issues/14490

**Comment by Arthur-Milchior** [comment]
There are many use case for a lot of different implementation. I’d still prefer we remain as consistent as possible with Anki, which autoplay one video after the other. 
May be really worth it to have a discussion with anki to add extra settings for the user when they want more fine grained control.

I am not certain your implementation would not cause otheri ssues. Indeed, if there are multiple video, it would play them all at once. If there is sound in the video, that would make all of them interact in a bad way. For image only video, I guess it could be acceptable.
My use-case is French sign language. Sometime there are up to three synonyms for a word, so I get three video. Now I also have to scroll on phone to see the third one.
Also, I may not want to autoplay on the answer side when it was played on question side.

**Comment by david-allison** [comment]
Blocked on:

* https://github.com/ankidroid/Anki-Android/pull/15000

After this is merged, we can handle video

**Comment by rcoh** [comment]
Is there anything still blocking this from being fixed? I'm also using an ASL deck and without autoplay it's much harder to use.

**Comment by david-allison** [comment]
Nothing blocking this.

Needs a discussion on how this interacts with `Automatic Display Answer` if a user pauses the video

**Comment by rcoh** [comment]
I think it shouldn't personally. You can't take back showing the answer and if you pause the video you have already engaged with the app with a click.

If you were going to click, you could have picked an answer already.

**Comment by rcoh** [comment]
:-D thanks!!!
