### ISSUE TITLE
[BUG]: Edit Note Preview does not show the expected card

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14694]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

open the browser
Select a card which is not card 1 of the note
long press
in the menu, tap "edit note"
Tap preview

### Expected behaviour

You should see the selected card in the preview mode (or at least, the card should be consistent with the card underlined at the bottom of the editor)

### Actual behaviour

First card of the note is shown (At least I assume. In the case I was interested in, I saw the "this card is empty" warning)

### Debug info

```text
2.17 alpha 3
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
This will be slightly easier to fix once https://github.com/ankidroid/Anki-Android/pull/14719 goes in:

* `ordinal` is provided to the editor: 
* `ordinal` is `ord`, NOT the index into the array
  * `{{c1::AA}} {{c3::BB}}` returns the second ordinal as 2

https://github.com/ankidroid/Anki-Android/blob/170c2d1ee5a354b42395e8c0de4363a1e1fc367b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt#L84

`mOrdinal` is not used to set `templateIndex` in this branch:

https://github.com/ankidroid/Anki-Android/blob/170c2d1ee5a354b42395e8c0de4363a1e1fc367b/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.kt#L233-L241

`setCurrentCardFromNoteEditorBundle` uses `templateIndex = 0` and displays the wrong card

**Comment by david-allison** [comment]
I've added two regression tests to help guide a fix

One undefined question: what should the note editor previewer show if one of the cards is empty? Should it be skipped, or displayed

Should this be different between:
* Card Template Preview
* Note Editor Preview
* Card Browser Preview (less likely to want to see empty cards)

**Comment by david-allison** [comment]
For when a few dependencies have been merged:

```kotlin
    private fun indexFromOrdinal(col: Collection, ordinal: Int): Int {
        return when (mEditedNotetype?.isCloze) {
            true -> col.clozeNumbersInNote(col.newNote(mEditedNotetype!!)).indexOf(mOrdinal)
            else -> ordinal
        }
    }
```

**Comment by dae** [comment]
Is that correct? with c1 and c3, that will return [1,3], and ord 3 will be an index out of bounds, won't it?
