### ISSUE TITLE
Alert in app startup if an old Webview (< v77) is being used

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14702]
Oh I always forget that. This is an easy trap to fall in to, I believe others have as well (recently)

I think a nice ergonomic improvement would be a startup alert for people like me that forget this that checks for a minimum webview version and alerts people if it is too old

I'll re-test this on a modern emulator. I was trying to avoid the higher API emu I've got because it crashes so frequently at the moment (upstream google emulator issue, not related to any work here...)

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/14622#issuecomment-1806841201_

---

The concern of the issue is that Anki HTML pages (`com.ichi2.anki.pages`: Card info, statistics, deck options, import CSV, etc) needs a not too old webview version. The task is to:

1.  Find out the approximate minimum version of WebView required for the pages to work correctly
2. If the user's WebView is old, show a dialog or snackbar at the app startup (in the deck picker to be more precise) telling the user to update their webview with a link explaining how

**Comment by BrayanDSO** [comment]
Complementing the Webview version discussion, here are some previous tests I did for the CSV import screen: https://github.com/ankidroid/Anki-Android/issues/6772#issuecomment-1209212058, which may help.

**Comment by mikehardy** [comment]
May be worthwhile to just do this as an app startup check... I'd rather not waste any time testing something that relies on up to date WebView if it's out of date...

**Comment by mikehardy** [comment]
Looks like we have another webview item that can cause the app to not work if webview is not up to date: https://caniuse.com/?search=globalthis (from #14737 )

It appears WebView 119+ at least can work, but perhaps there is some lower version that can work.

Once we determine the minimum webview version we can implement this I suppose

**Comment by BrayanDSO** [comment]
[Maybe 77](https://github.com/ankidroid/Anki-Android/issues/6772#issuecomment-1209221166) (up to testing and deciding if we are going to just follow AnkiMobile/Desktop, which is easier)

**Comment by mikehardy** [comment]
That looks perfect, thank you for finding that @BrayanDSO. Updating title and text above to match

**Comment by elli-hae** [comment]
I'd like to try to do this :)

**Comment by mikehardy** [comment]
@elli-hae be my guest! This one has caught me a couple times 😆

**Comment by Aditya8840** [comment]
Could you please assign me?

**Comment by mikehardy** [comment]
@Aditya8840 hi there 👋 we do not assign issues normally, a comment saying you are going to work on it is sufficient.

@elli-hae has already made a comment saying basically this, which means this issue is *likely* not available at the moment since someone is already working on it, unless elli-hae either comes back and says they are no longer working on it, or doesn't answer a request for status for more than a few days

That keeps the process pretty easy with fewer steps normally. It also means that the hunt for an actual good first issue has to go elsewhere and I think they may be a bit scarce in the repo at the moment...

**Comment by elli-hae** [comment]
Hi, I've been working on this and I'm having some trouble with upgrading the WebView version. I can't update it from the Google Play Store, so I found [this guide](https://gist.github.com/ppoffice/9ce9790708eeabbec1281467e25139e4#file-readme-md) but it's not really working either (or it might, but I'm just not getting far). Btw I'm using the Nexus 5 API 24 AVD and the WebView version is around 51. Is there an easy way/another tutorial on how to upgrade the WebView?

**Comment by mikehardy** [comment]
Hey @elli-hae - as far as I know on the emulators there is no easy way to update the webview unless you use a "Google Play Store" version of the emulator. But then you won't trigger the error as it will have an updated webview 😆 

I think the success criteria for this feature is simply that you detect the version as being too low and throw an error. There is no need to update it or anything - it is just a big obvious notice to developers that "hey, this probably isn't going to work out for you"

Users should never see this in reality

So as long as you are detecting the old version you have, and you throw an alert, awesome. That's it

**Comment by elli-hae** [comment]
Oh okay, that makes it a lottt easier, thanks @mikehardy !
