### ISSUE TITLE
[Bug] Time limit reached is shown when starting reviews

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#14709]
###### Reproduction Steps

1. Open Ankidroid App
2. Start reviewing a deck
3. A message pops up: "Time limit reached. Studies 0 cards in 30 minutes

###### Expected Result

No time limit message

###### Actual Result

Time limit message is shown.
That wasn't the case in the previous stable version.

###### Debug info
AnkiDroid Version = 2.17alpha3 (42a8c8c55c200f372b0bd0b462e4b58554b72fe5)

Android Version = 12

ProductFlavor = play

Manufacturer = motorola

Model = moto g(60)s

Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g(60)s Build/S3RLS32.114-25-13; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.66 Mobile Safari/537.36

ACRA UUID = 751875a7-f00b-41fe-90b1-2bcc6af0617f

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pippep** [comment]
Same Bug in 2.17alpha4

**Comment by david-allison** [comment]
We are missing calls to `col.startTimebox()`: 

https://github.com/search?q=repo%3Aankitects/anki%20startTimebox&type=code

We need to define when a timebox starts, and how this is handled in the activity lifecycle

**Comment by david-allison** [comment]
Change occurred in 67bb409f7a4c8f82d6d4bd745b507ac41c89c3fe. Timebox previously stared on `onCollectionLoaded`.

I do feel this is subject to change, as it doesn't take the Android activity lifecycle into account but this will close out the regression

**Comment by mikehardy** [comment]
I think this just popped up for someone in a Play Store review too actually - I asked them to check new-backend/v3 scheduler on 2.16.5 or the alphas to see if that affects it. Seems like it won't fix it for them - but I see a PR so perhaps with 2.17alpha6
