### ISSUE TITLE
[BUG]: Changing language for the first time causes Ankidroid to freeze

### ISSUE THREAD

**Issue by NameLessGO** [ankidroid/Anki-Android#14726]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Clear Ankidroid cache
2. Settings
3. Language
4. choose any option.

### Expected behaviour

To just change with little to no delay/freeze

### Actual behaviour

It can result in 3 behaviors,

- Freeze and crash
- Freeze and change
- Change with no issues

### Debug info

```
AnkiDroid Version = 2.17alpha5 (4fc8af92973d8d502e0139d0dd5372415444ca1f)

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-G991B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G991B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.66 Mobile Safari/537.36

ACRA UUID = e05e35be-f57b-4474-a73a-ecded42040f8

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```

### (Optional) Anything else you want to share?

While this problem won't be an issue after the second time, we will probably receive issues about it
### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by NameLessGO** [comment]
Great, now that I test for the third time following the same steps, it works without issue 🤡

**Comment by david-allison** [comment]
Is changing the app language something which you do often?

**Comment by david-allison** [comment]
I can't produce this on `main`, could you provide the AnkiDroid version in the Debug Info (first line)?

**Comment by david-allison** [comment]
No crash reports under the ACRA ID

**Comment by NameLessGO** [comment]
I like to use english but had to help someone in PT-BR so encountered the problem, which tried finding ways to trigger, which worked in the 2rd time, but not 3rd

Not sure why it was hidden, but was on latest alpha
`AnkiDroid Version = 2.17alpha5 (4fc8af92973d8d502e0139d0dd5372415444ca1f)
`

**Comment by mikehardy** [comment]
Sounds like a race condition. I've noticed a few ANR-usually/sometime-crash items like that as well (while testing the new import screen in #14622 - I am not saying it's related - just saying there is at least one thing I've also personally seen that is hard to reproduce and feels timing related like a race condition between AnkiDroid and Anki-Android-Backend and this one sounds so similar...
