### ISSUE TITLE
Implement `Set Due Date` dialog

### ISSUE THREAD

**Issue by 1343467272** [ankidroid/Anki-Android#14729]
Implement the "set expiration time" feature on both desktop and iOS, allowing users to set an expiration time within a specified range.

**Comment by BrayanDSO** [comment]
Hi there. Could you give more context?

Also, here is the place for reporting AnkiDroid (Android version of Anki) issues. For iOS and the desktop version. you should go to the anki forums https://forums.ankiweb.net/

**Comment by 1343467272** [comment]
iOS and computer end can set an interval for the expiration date, while Android cannot.

**Comment by 1343467272** [comment]
> Hi there. Could you give more context?
> 
> Also, here is the place for reporting AnkiDroid (Android version of Anki) issues. For iOS and the desktop version. you should go to the anki forums https://forums.ankiweb.net/



> Hi there. Could you give more context?
> 
> Also, here is the place for reporting AnkiDroid (Android version of Anki) issues. For iOS and the desktop version. you should go to the anki forums https://forums.ankiweb.net/

iOS and computer end can set an interval for the expiration date, while Android cannot.

**Comment by 1343467272** [comment]
iOS and computer end can set an interval for the expiration date, while Android cannot.

**Comment by mikehardy** [comment]
I'm not personally familiar with this - sorry, could you walk us through how exactly you reach that setting in Anki Desktop? All the clicks required starting from opening it? That would help us locate where this setting is and what it's supposed to do

Thanks!

**Comment by 1343467272** [comment]
![tmpD53F](https://github.com/ankidroid/Anki-Android/assets/98404006/a96aa9c2-7450-486b-8ee2-02d2b96065ad)

In Anki desktop, pressing 'Ctrl+Shift+D' in the card browsing interface or browser interface brings up the deck options. However, in AnkiDroid, you can only set the due date for a card to a specific day and not to a range.
