### ISSUE TITLE
Frequent "AnkiDroid is not responding" messages

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14723]
I am seeing frequent "AnkiDroid is not responding" messages while using the latest alphas.

These messages mostly appear on the main decks page and the browser. In most cases, they appear within a minute of launching the app. But, the messages don't appear on every launch. So, I am not sure what's the actual trigger.

###### Debug info
AnkiDroid Version = 2.17alpha5 (4fc8af92973d8d502e0139d0dd5372415444ca1f)

Android Version = 13

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.66 Mobile Safari/537.36

ACRA UUID = d808c2e4-92ce-40db-9491-1fdcb75b1f50

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
On which screens, after performing which actions?

**Comment by user1823** [comment]
It is actually quite random, though it mostly appears on the main decks page and the browser.

**Comment by dae** [comment]
If you can use adb to check your device logs, have a look to see if you can see "blocked main thread" messages around the time it occurs.

**Comment by user1823** [comment]
I am not that technical, sorry.

**Comment by user1823** [comment]
> after performing which actions?

In most cases, within a minute of launching the app. But, the messages don't appear on every launch. So, I am not sure what's the actual trigger.

**Comment by user1823** [comment]
I have not seen the message for quite some time. So, I think that the issue was fixed in some earlier alphas. I will reopen the issue if I see those messages again.
