### ISSUE TITLE
[BUG]: Do not show again does not work for backup reminder

### ISSUE THREAD

**Issue by matejdro** [ankidroid/Anki-Android#14732]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Wait for backup popup to show up
2. Select no
3. Select do not show again
4. Select later
5. Wait for next backup popup to show up

(something like that, I'm not 100% sure about the flow)

### Expected behaviour

Backup popup should never show up again since you selected "do not show again"

### Actual behaviour

Backup popup will show again eventually

### Debug info

```text
AnkiDroid Version = 2.17alpha5 (4fc8af92973d8d502e0139d0dd5372415444ca1f)

Android Version = 13

ProductFlavor = play

Manufacturer = Google

Model = Pixel 7 Pro

Hardware = cheetah

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 7 Pro Build/TQ3A.230901.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.66 Mobile Safari/537.36

ACRA UUID = 85314e7b-0d43-4b96-a861-e60e9dd7f848

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Note that even though I'm reporting this from alpha version, this has been happening for some time (including latest stable version), so it's not limited to alpha.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by soCallmeAdityaKumar** [comment]
I am working on it
