### ISSUE TITLE
[BUG][Crash]: Play button of audio recorder/player can't work

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#14730]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Record and save an audio file

    (Open "Add" screen > Tap the clip icon of a field >"Record audio" > Start & Stop recording > Tap the check button next to the record button)
   <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/bfbe1418-276d-43c5-be02-18a6a2716f5e" width="320px">

2. Tap the play button
   <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/9b3c9dc5-41e5-4824-84e8-1e158c706ee9" width="320px">

### Expected behaviour

The recorded audio get played.

### Actual behaviour

Crash

### Debug info

```text
AnkiDroid Version = 2.17alpha5 (4fc8af92973d8d502e0139d0dd5372415444ca1f)

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

The crash report has been sent.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
@criticalAY

**Comment by criticalAY** [comment]
Yes, I recently noticed it, its due to the async state and the state was not managed properly, I already fixed it in my draft but that might take time so I will fix it up separately.
