### ISSUE TITLE
dev: logcat warning `"Uncaught ReferenceError: globalThis is not defined", source: http://127.0.0.1:37995/assets/reviewer_extras_bundle.js (437)`

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#14737]
Reproduction steps:
1. Open the reviewer
2. See logcat

"Uncaught ReferenceError: globalThis is not defined", source: http://127.0.0.1:42665/assets/reviewer_extras_bundle.js (437)"

Built with f131181a6b43506ccb95fdb73fd7b55d993ce5b9

**Comment by BrayanDSO** [comment]
Asking @dae what `globalThis` is supposed to do

**Comment by dae** [comment]
Are you testing in an emulator? The error implies the webview is not up to date.

https://caniuse.com/?search=globalthis

**Comment by BrayanDSO** [comment]
Yep. And my Javascript knowledge is limited so I didn't know about this. Thanks

**Comment by mikehardy** [comment]
Hey @BrayanDSO what's the webview version on whatever emulator this failed for you? Trying to find the minimum version of webview for #14702

**Comment by BrayanDSO** [comment]
Couldn't reproduce it again in the emulators I have installed

**Comment by mikehardy** [comment]
Must have updated the webview in the background 😆 - got it though, webview minversion 71 for globalThis ✅
