### ISSUE TITLE
[BUG]: Reviewed card don't show up in due date

### ISSUE THREAD

**Issue by PanicoAlessandro** [ankidroid/Anki-Android#14742]
### Checked for duplicates?

- [x] This issue is not a duplicate

### What are the steps to reproduce this bug?

Create any number of cards in whichever deck, one or more, you prefer (in my case, I only checked with basic cards). The bug begins when cards in learning phase graduate into reviewed cards

### Expected behaviour

When the due date comes, reviewed cards for the day should appear as green numbers in their correspondent deck.
The same logic applies to when you make a custom study to review ahead cards in a deck.

### Actual behaviour

Reviewed cards don't show up as expected, since the reviewed date increase.
Let's say, for example, today (day 0) I have a reviewed card scheduled for tomorrow. When tomorrow comes (day 1), the card doesn't show up, and it is scheduled instead for the day tomorrow (day 2). And this goes on and on. So, no reviewed card actually show up again.
Even when making a custom study to review ahead, cards don't show up.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-A336B

Hardware = s5e8825

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A336B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = a0d4a676-d498-48ad-9ed8-eeab6b0f1663

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

```

### (Optional) Anything else you want to share?

I tried installing previous versions of the app (in particular version 2.13.4 and 2.14.5 and, though the bug seemed not to be there, it actually popped up later at random).
p.s. (17th November 2023) I also tried installing the alpha version (2.17alpha), but the bug still occurs

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by snowtimeglass** [comment]
Hi, thank you for the report. 

Could you fill in the debug info section by [the steps](https://ankidroid.org/docs/help.html#_ankidroid_2_16)?

**Comment by david-allison** [comment]
Potentially: https://docs.ankiweb.net/studying.html#fuzz-factor

**Comment by PanicoAlessandro** [comment]
> Potentially: https://docs.ankiweb.net/studying.html#fuzz-factor

I considered it too. The problems are 2, though:
1) The addition of one day to the time due of the card happens exactly the moment the card should show up.
Imagine it's 23:59, and "next day" is set at midnight. Right not the card has a clear indication that it should come tomorrow but, as soon as one minute passes, it's time due grows by one.
2) When a card, or more, due for the next day get involved in this event, even all the other cards in all deck have their time due increased by one day, while fuzz factor should consider each card RESPECTIVELY with a RANDOM time added (whereas this bug involves ALL CARDS with SPECIFIC time added).


Hope this clarifies more the situation

**Comment by snowtimeglass** [comment]
>p.s. (17th November 2023) I also tried installing the alpha version, but the bug still occurs

Which alpha version specifically?

**Comment by PanicoAlessandro** [comment]
2.17alpha

**Comment by snowtimeglass** [comment]
You can know the specific version on the page which you copy the debug info.
