### ISSUE TITLE
[BUG]: Plural words used in browser menu even when single card is selected

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14752]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Select a single card in the Browser and open the menu.

### Expected behaviour

The menu options use singular words.

### Actual behaviour

Some menu options use plural words.

<img width=100 src="https://github.com/ankidroid/Anki-Android/assets/92206575/9a7866a9-3598-421a-8150-cafdec193c18">

### Debug info

```text
AnkiDroid Version = 2.17alpha5 (4fc8af92973d8d502e0139d0dd5372415444ca1f)
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
'delete notes' absolutely

I would like to change 'Suspend cards' to `Toggle suspend` and `Mark Notes` to Toggle Mark as Anki does it.

<img width="181" alt="Screenshot 2023-11-16 at 14 14 09" src="https://github.com/ankidroid/Anki-Android/assets/62114487/ecf5312b-32c0-4cf6-8c11-616f3c11a73c">

This functionality in AnkiDroid depends on the tag/queue of every card in the selection, and the calculation process is complex
