### ISSUE TITLE
Allow for interactive javascript that can permanently modify what is displayed on a card's backside

### ISSUE THREAD

**Issue by 1a2a34v** [ankidroid/Anki-Android#14766]
For my deck, I often first blindly download a lot of information from various sources. Sometimes I have 10+ example sentences for a vocabulary I am trying to learn, and right now if I want to remember the word by a particular sentence or image I always have to search for it every time I look at the backside

It would be perfect if I could then, from all this content, have some way to select the backside content that is the most interesting for me while using anki or ankidroid and not while I am constructing the deck, and have it displayed at the top every time I open the card from then on. This would require some way to permanently modify the html or some other datastructure related to the card based on the javascript buttons we press in the anki or ankidroid frontend when looking at the card backside.

I am a big fan of anki and would love for a feature like this to be implemented, as I believe it has a lot of potential to make this app even greater and improve the usability for many users.

**Comment by BrayanDSO** [comment]
For now, using https://developer.mozilla.org/en-US/docs/Web/API/Window/sessionStorage or https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage should make this possible (I don't remember which)

After #14302 is solved, it should be possible to do more easily it without local/sessionStorage.

**Comment by 1a2a34v** [comment]
I tried something like this

```
<div id="selected-items">Selected Items:</div>
<hr>
<div id="content">
    <div id="selections">
        <div onclick="toggleSelection(this)">Sentence 1</div>
        <div onclick="toggleSelection(this)">Sentence 2</div>
        <div onclick="toggleSelection(this)">Sentence 3</div>
    </div>
</div>

<script>
function toggleSelection(element) {
    element.classList.toggle('selected');
    updateSelectedItems();
}

function updateSelectedItems() {
    var selectedItems = document.querySelectorAll('#selections .selected');
    var displayText = Array.from(selectedItems).map(item => item.innerText).join(', ');
    document.getElementById('selected-items').innerText = 'Selected Items: ' + displayText;
}
</script>

<style>
#selections div {
    cursor: pointer;
    margin-bottom: 5px;
    padding: 5px;
    border: 1px solid #ddd;
}

#selections div.selected {
    background-color: #e0e0e0;
}
</style>
```

But when I press the buttons nothing happens, I assume this is because of the restricted environment in anki. For me it is not as straightforward to make this work, if you don't see an easy way either I think I have no choice but to wait for your MR.
