### ISSUE TITLE
CSV import capability

### ISSUE THREAD

**Issue by awes12** [ankidroid/Anki-Android#14778]
AnkiWeb has a functionality where you can import a CSV file, and those items will be added to a deck (after choosing note types, breakpoints, etc). This isn't possible in AnkiDroid as far as I know (you currently have to do it on AnkiWeb then sync to AnkiDroid), but would be a very welcome feature. The implementation would ideally be as similar to AnkiWeb's for parity reasons (although functionality for importing multiple files at once would be nice).

**Comment by lukstbit** [comment]
This functionality is available:
- in latest 2.16.4-5 stable version if you enable the new backend in Settings -> Advanced
- in latest 2.17 alphas without changing any settings
