### ISSUE TITLE
[BUG]: User settings are reset on sync with AnkiDroid

### ISSUE THREAD

**Issue by kanjieater** [ankidroid/Anki-Android#14800]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

![image](https://github.com/ankidroid/Anki-Android/assets/32607317/10f77ebd-7d47-4e47-b80c-5d7aed6695ee)
Inside of settings
![image](https://github.com/ankidroid/Anki-Android/assets/32607317/eaa8e145-2363-4629-b6a2-fc75733942f1)
This is the option to stop playing audio when you answer a card.

If I set it on the latest version of anki desktop, it gets removed as soon as I sync with the latest version of ankidroid.

### Expected behaviour

User settings should never be reset on sync if they weren't modified

### Actual behaviour

User settings are removed without users control

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 9

ProductFlavor = play

Manufacturer = samsung

Model = SM-N950U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-N950U1 Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.163 Mobile Safari/537.36

ACRA UUID = 85c60929-c55d-4046-ae16-545886ccf69b

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi @kanjieater - if you are using latest desktop as you say:

> If I set it on the latest version of anki desktop,

You will likely want to use the latest code here (our latest alpha build) as well, to match desktop+ankiweb: https://github.com/ankidroid/Anki-Android/releases

The issue you describe may already be fixed there. Could you try one of the 2.17alphas and report whether it is already working there or not?

Thank you

**Comment by kanjieater** [comment]
> Hi @kanjieater - if you are using latest desktop as you say:
> 
> > If I set it on the latest version of anki desktop,
> 
> You will likely want to use the latest code here (our latest alpha build) as well, to match desktop+ankiweb: [ankidroid/Anki-Android/releases](https://github.com/ankidroid/Anki-Android/releases)
> 
> The issue you describe may already be fixed there. Could you try one of the 2.17alphas and report whether it is already working there or not?
> 
> Thank you

Thanks Mike, I can confirm that does fix it. I was just surprised that the latest stable ankidroid and stable anki desktop would change settings. 

Is there anyway way to know what version of ankidesktop is compatible with any version of ankidroid?

**Comment by mikehardy** [comment]
Unfortunately it is not so easy at the moment to determine cross-compatibility, and this is something we'll need to explore between upstream anki (@dae 👀 ) and this repo.

There are a *lot* of changes right now with v3+ scheduling and FSRS etc that have gone out with anki upstream 23.10+ and we have ingested them here in the 2.17 series (still in alpha as you know, so not generally available yet...) and I'm not even sure if the incompatibilities are expected or unexpected so I'm not sure how problems like what you see inform future release decisions

An area to pay attention to though.

Seems like the non-controversial action item we need to pursue here in AnkiDroid with full speed is to get our 2.17 release out with as little delay as possible to minimize the time where observable problems are actually happening

That's something we're already doing so I'm going to close this as not separately actionable but I'm happy to know about it so I appreciate your logging the issue and verifying 2.17 fixes
