### ISSUE TITLE
[BUG]: The Color button in the whiteboard editor has no color.

### ISSUE THREAD

**Issue by xjqm-tao** [ankidroid/Anki-Android#14802]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

You can see it by opening the whiteboard editor.

![IMG_20231124_154505](https://github.com/ankidroid/Anki-Android/assets/126331411/6afd8607-978e-4849-9ef5-07d2e03d4215)

### Expected behaviour

Buttons are colored.

### Actual behaviour

The buttons are the same color.

### Debug info

```text
AnkiDroid Version = 2.17alpha6 (393f61b229a26ec97eb13c83f0d1f09652f776c2)

Android Version = 13

ProductFlavor = full

Manufacturer = Xiaomi

Model = 22041216C

Hardware = mt6895

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 22041216C Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 13b991d9-a0fd-4ffc-8f8b-0b5c080f71cf

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [x] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by peyman79** [comment]
Hi
Can I work on this issue?
