### ISSUE TITLE
keyboard (or controller) shortcuts for one-by-one type cards

### ISSUE THREAD

**Issue by salmanuc** [ankidroid/Anki-Android#14819]
**Is your feature request related to a problem? Please describe.**
The Anking deck has one by one type cards for which you can set shortcut on pc but not ankidroid. 

**Describe the solution you'd like**
keyboard (or controller) shortcut for one-by-one type cards

**Describe alternatives you've considered**
Rn only option is to manually touch the button to reveal answer as opposed to a shortcut from controller or keyboard which is frustrating when you are laying back using a controller. 

**Additional context**

**Comment by salmanuc** [comment]
It would need two separate shortcuts for the two separate butons. One is "reveal next" and the other is "toggle all"

![Screenshot_2023-11-26-15-30-03-19_a9eef3a2a561b80d5c76daebd0f9a14c.jpg](https://github.com/ankidroid/Anki-Android/assets/138794113/5582fda9-c34a-4ef1-b656-cfcce5366e42)

**Comment by david-allison** [comment]
Thanks for the report!

I believe this should be handled in #14286, I believe this is a subset of that feature, therefore I'm closing it as such

If this isn't possible after #14286 is resolved, please give us a ping and we'll reopen this

* #14286

**Comment by beejumm** [comment]
Hey everyone, wanted to ask if there was an update to this?
