### ISSUE TITLE
[Bug] Invisible characters displayed as question mark

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14817]
When I copy text from the Web into my cards, my cards sometimes get invisible formatting characters such as the [left-to-right mark](https://en.wikipedia.org/wiki/Left-to-right_mark) character. 

###### Expected Result

Anki doesn't display this character, which is expected because it is an invisible formatting character.

###### Actual Result

AnkiDroid displays this character as a question mark.

###### Debug info
2.17 alpha 6

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
> When I copy text from the Web into my cards, my cards sometimes

"sometimes"

If you have some URL and a description of some specific text you can copy and paste (or perhaps you could put a specific text chunk here that is copy-pastable ? 🙏 ) I think that would help with reproduction

**Comment by user1823** [comment]
> "different" +‎ -topic

**Comment by mikehardy** [comment]
Fascinating. Honestly I just learned this character existed from your opening this issue. And when I click "edit" on your comment in a desktop browser to see if I can see the character I cannot. I have a lot to learn in this area

**Comment by user1823** [comment]
<img width=200 src="https://github.com/ankidroid/Anki-Android/assets/92206575/daabd964-e60b-4def-8875-1efe459a6713">

As I am putting more attention to it now, it seems that it has something to do with the font too. I will confirm that and report here.

**Comment by user1823** [comment]
I confirmed that the bug can be reproduced using the default font-family (arial) in the default Basic notetype.

**Comment by user1823** [comment]
Also reproduced by the character `u+02069`

Copy-pastable text:

> }⁩{

The character is in between the two brackets.

**Comment by danielmehring** [comment]
I'll give it a go

**Comment by user1823** [comment]
I don't know how but this issue seems to be resolved now. Probably, it has something to do with WebView updates?
