### ISSUE TITLE
[BUG]: AnkiDroid 2.17alpha6 AnkiDroid Crashes when accessed from background processes 

### ISSUE THREAD

**Issue by kanjieater** [ankidroid/Anki-Android#14829]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

There are multiple apps that can export Anki cards to AnkiDroid.
- Jidoujisho (https://github.com/lrorpilla/jidoujisho)
- Yomichan w/ Kiwi browser + AnkiConnect Android ( https://learnjapanese.moe/yomichan/ + https://github.com/KamWithK/AnkiconnectAndroid)

Doing any Anki related features shows that AnkiDroid has stopped working

### Expected behaviour

Same as the working 2.16.5, it should not crash and allow for cards to be added.		

### Actual behaviour

"AnkiDroid has stopped working" popup occurs

### Debug info

```text
AnkiDroid Version = 2.17alpha6 (393f61b229a26ec97eb13c83f0d1f09652f776c2)

Android Version = 9

ProductFlavor = full

Manufacturer = samsung

Model = SM-N950U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-N950U1 Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.163 Mobile Safari/537.36

ACRA UUID = 85c60929-c55d-4046-ae16-545886ccf69b

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, could you ensure that crash reports are enabled? I can only see two reports from 2.16.5


```
Caused by: org.json.JSONException: No value for new
	at org.json.JSONObject.get(JSONObject.java:392)
	at org.json.JSONObject.getJSONObject(JSONObject.java:612)
	at com.ichi2.libanki.sched.SchedV2._newConf(SourceFile:18)
```

**Comment by kanjieater** [comment]
> Hi, could you ensure that crash reports are enabled? I can only see two reports from 2.16.5
> 
> ```
> Caused by: org.json.JSONException: No value for new
> 	at org.json.JSONObject.get(JSONObject.java:392)
> 	at org.json.JSONObject.getJSONObject(JSONObject.java:612)
> 	at com.ichi2.libanki.sched.SchedV2._newConf(SourceFile:18)
> ```

Sorry, It's not crashing on 2.16.5 like i mentioned in the original post, but when it crashes in the background on the alpha versions theres no crash report popup unfortunately

**Comment by david-allison** [comment]
I've tried to reproduce this briefly and it worked fine on alpha6

It would be extremely helpful for you to get your computer connected to your phone and post a [logcat](https://developer.android.com/tools/logcat) so we can see what's going on with the crash.

Are you technical?

**Comment by david-allison** [comment]
Should be fixed in alpha 8, thanks for your patience
