### ISSUE TITLE
[BUG]: Update of styling section of card types on Anki Desktop is not reflected on AnkiDroid

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#14827]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Prepare a card which already exists both on the desktop version and on AnkiDroid
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/ffdde12a-2491-4b88-bbd1-7572ee82c8fe" width="200px"><img src="https://github.com/ankidroid/Anki-Android/assets/10436072/f36f39cb-8384-4815-8b67-492573926e43" height="339px">

2. Update the content of the front template of the card type on the desktop version

    **Before**
  ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/7004cbb5-0051-46a9-bb78-cc7b787fd729)
↓
**After**
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/8bb595d4-c8a7-4ac8-a65e-db9cbf6c0224)

3. Update the content of the styling section of the card type as well
  
    **Before**
  ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/0369c66c-61d5-48f2-97e2-320f8d4732e7)
↓
**After**
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/a435cd47-7136-46f1-8b0d-30f9d653b253)

5. "Sync" on the desktop version 
  ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/5b9fcf66-4bd3-44aa-9f7e-13a86a2cacce)

6. "Sync" on AnkiDroid
7. Show the card on AnkiDroid

### Expected behaviour

Both updates of the front template and the styling are reflected on the card
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/ddfc3987-d5c7-49b8-be62-7ed94f89fbf2" width="320px">

### Actual behaviour

Although the update of the front template is reflected on the card, the update of the styling is not reflected.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/817d43d7-12e3-464e-9c99-402b49b2ef73" width="320px">

### Debug info

```text
AnkiDroid Version = 2.17alpha6 (393f61b229a26ec97eb13c83f0d1f09652f776c2)

Android Version = 11

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

Neither the front template nor the styling section is updated on AnkiDroid
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/6349d5aa-cdfd-48e3-ba79-54586ca89cde" width="320px">
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/3bc9e3ce-8c24-447d-8c51-b8ce3cd8f74b" width="320px">

After a one-way sync from AnkiWeb or completely-closing and restarting the app, the updates are reflected.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/5bc1adb5-6bf1-4506-9504-02b483ee3a29" width="320px">
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/844f854d-82e7-4ebf-991d-df258cdca3bf" width="320px">
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/4b1ffd73-94ed-4f16-a7fc-74f0d53750ff" width="320px">

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
A method to clear the cache in Notetypes.kt should be implemented, and it should be called at the start or end of a sync.
