### ISSUE TITLE
[BUG]: Error after editing a note

### ISSUE THREAD

**Issue by sommerluk** [ankidroid/Anki-Android#14857]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Create a deck "mydeck".
2. Create two sub-decks "A" and "B".
3. Create some notes for each sub-deck, but not for "mydeck" itself.
5. Go into learning mode for "mydeck", so that you are shown both, cards of deck "A" and of deck "B".
6. While reviewing a card from deck "A", choose "Edit note"
7. Change the deck from "A" to "B".
8. Confirm
9. When going back to learning mode, depending on the schedule, the very same card might or might not show up again. If a different card shows up, everything is fine. However, if the same card shows up again, the error will finally occur. Go on…
10. Show the answer.
11. Assess the card as "Good".

### Expected behaviour

No error message.

### Actual behaviour

The following error message appears:
![Screenshot_20231201-065208_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/6830724/94c1712c-5857-4551-85fe-7ac6ef1fa9d4)

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 11

ProductFlavor = play

Manufacturer = samsung

Model = SM-A305F

Hardware = exynos7904

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-A305F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.163 Mobile Safari/537.36

ACRA UUID = d63a9090-38e0-44c4-b448-94b71664eef4

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by sommerluk** [comment]
Sorry, I forgot to mention this only occurs when moving notes from one subdeck to another subdeck within the same parent subdeck, when learning the parent deck. I've edited the original bug report accordingly now.

**Comment by david-allison** [comment]
Can you reproduce this in the 2.17 alpha? (try Parallel.A). I've had a try and can't reproduce

https://github.com/ankidroid/Anki-Android/releases
