### ISSUE TITLE
Deck option add misleading highlights

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14851]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Open the deck options. 
Select the deck type. Long press one entry and scroll a bit (while pressing)

### Expected behaviour

The highlight disappear once it's no longer considered to be the selection.
Highlight is nice to give feedback on where we tap, but should not stay once the finger is up

### Actual behaviour

The touched line remain blue. I thought it mean it was selected. And when I tapped "Save" I discovered it was ignored.

### Debug info

```text
AnkiDroid Version = 2.17alpha6 (393f61b229a26ec97eb13c83f0d1f09652f776c2)

Android Version = 14

ProductFlavor = play

Manufacturer = Google

Model = Pixel 8 Pro

Hardware = husky

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro Build/UD1A.231105.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.67 Mobile Safari/537.36

ACRA UUID = 47035a3d-ff8b-4423-8485-1d6d82d48957

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Aditya13s** [comment]
May I begin working on it? @david-allison

**Comment by Aditya13s** [comment]
Is Deck Options page a web view?

<img src="https://github.com/ankidroid/Anki-Android/assets/77337791/0600e685-829e-4dfa-990f-20c58baa6710)" width="350">

**Comment by Aditya13s** [comment]
@david-allison can you explain me how the web pages are loading , i am not able to understand how the html of the pages coming from can you explain me so that i can work on the issue

**Comment by mikehardy** [comment]
We may need a section of the development guide in the wiki added to explain the new "page from Anki Desktop displayed in AnkiDroid" data / control flow - @BrayanDSO apologies for pinging you but even if it is just a 60 second effort involving a short list of items, would you mind giving that a try? I'll even deep-link it for maximum efficiency 😆 https://github.com/ankidroid/Anki-Android/wiki/Development-Guide/_edit

**Comment by BrayanDSO** [comment]
Okay, I tried to explain the important Anki details that people need to know. The rest of things are implementation details which ideally should be understable by reading the code (and refactoring/documenting it more if it isn't clear)

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#anki-desktop-pages

**Comment by mikehardy** [comment]
@BrayanDSO that's fantastic, thank you!

**Comment by Aditya13s** [comment]
@david-allison i tried understanding how anki web pages are working but i am unable to understand so i think i am not able to work on this issue with my less knowledge but i if i get some help i can easily able to fix this issue

**Comment by BrayanDSO** [comment]
Closing as upstream issue

**Comment by Arthur-Milchior** [comment]
@BrayanDSO do you know whether it was opened as a bug upstream ? If so, would you mind giving the link it please ?
