### ISSUE TITLE
[Bug]The AnkiDroid API incorrectly handles the `[sound:XXXX]` tag

### ISSUE THREAD

**Issue by ChuckieChen945** [ankidroid/Anki-Android#14866]
###### Reproduction Steps

When querying card content with the AnkiDroid API, the handling of the `[sound:XXXX]` tag in 2.17alpha2 and subsequent versions is inconsistent with previous versions. For example, when querying the QUESTION column of a Card (the QUESTION column contains the `[sound:XXXX]` tag) with the following code:

```java
long noteId = 123456789L;
int cardOrd = 0;

Uri noteUri = Uri.withAppendedPath(FlashCardsContract.Note.CONTENT_URI, Long.toString(noteId));
Uri cardsUri = Uri.withAppendedPath(noteUri, "cards");
Uri specificCardUri = Uri.withAppendedPath(cardsUri, Integer.toString(cardOrd));
final Cursor cardCursor = contentResolver.query(specificCardUri,
        new String[]{FlashCardsContract.Card.QUESTION, FlashCardsContract.Card.ANSWER},  // projection
        null,  // selection is ignored for this URI
        null,  // selectionArgs is ignored for this URI
        null   // sortOrder is ignored for this URI
);
if(cardCursor.moveToFirst()) {
    question = cardCursor.getString(cardCursor.getColumnIndex(FlashCardsContract.Card.QUESTION));
    answer = cardCursor.getString(cardCursor.getColumnIndex(FlashCardsContract.Card.ANSWER));
}
```

###### Expected Result

In 2.16.5 and earlier versions, the value of `question` is:

```html
<style>.card {
    font-family: arial;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}
</style>[sound:my_sound.mp3]
```

###### Actual Result

In 2.17alpha2 and subsequent versions, it would return:

```html
<style>.card {
    font-family: arial;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}
</style>[anki:play:q:0]
```

2.17alpha2 and subsequent versions incorrectly replaced `[sound:my_sound.mp3]` with `[anki:play:q:0]`.

###### Debug info

AnkiDroid Version = 2.17alpha2 (19ad510c0a44c4fa140394363a0df3bd8ab177d8)

Android Version = 10

ProductFlavor = full

Manufacturer = HUAWEI

Model = MXW-AN00

Hardware = mt6873

Webview User Agent = Mozilla/5.0 (Linux; Android 10; MXW-AN00 Build/HONORMXW-AN00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.105 Mobile Safari/537.36

ACRA UUID = 9f6f5513-56ac-4600-be92-00b8a321ada0

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
* Related: https://github.com/ankidroid/Anki-Android/issues/14353

**Comment by ChuckieChen945** [comment]
Yes, I just started developing an app using the AnkiDroid API, and I need to find specific audio tags in the cards. If there is a direct API, it would be of great help to me. Thank you very much!
