### ISSUE TITLE
[Bug] Bluestacks: NoClassDefFoundError: Failed resolution of: Landroid/media/AudioFocusRequest

### ISSUE THREAD

**Issue by thamerla** [ankidroid/Anki-Android#14867]
###### Reproduction Steps

1. Install Anki Droid 2.17alpha8 onto Bluestacks 5
2. Import 300 notes / 600 cards deck via apkg (containing text, some css styling, audio, no images)
3. Try studying

###### Expected Result

The window goes into learning mode

###### Actual Result

The app crashes

###### Debug info
AnkiDroid Version = 2.17alpha8 (945014383cba6e47dc41ef244f3e929ac548246c)

Android Version = 7.1.2

ProductFlavor = full

Manufacturer = samsung

Model = SM-A805N

Hardware = SDM730

Webview User Agent = Mozilla/5.0 (Linux; Android 7.1.2; SM-A805N Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.108 Mobile Safari/537.36

ACRA UUID = 24ced073-7f6f-4f1c-897b-a30387e5d82c

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Note: We did have compat here, need to confirm the current status once I'm at a PC

We may be better served with  `AudioFocusRequestCompat.Builder`

This could also be an emulator-only issue.

Next step would be to get a caller/compat code reference

**Comment by david-allison** [comment]
Needs a follow-up that this is fixed in alpha9

**Comment by david-allison** [comment]
@thamerla following up
