### ISSUE TITLE
[BUG]: "New cards in random order" is not semantically consistent with what it says

### ISSUE THREAD

**Issue by Nefcanto** [ankidroid/Anki-Android#14863]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

I know other issues exist, like https://github.com/ankidroid/Anki-Android/issues/14107. But this issue is related to the semantics.

Based on the [docs](https://docs.ankiweb.net/deck-options.html#insertion-order), when we choose **New cards in random order**, Anki randomly sorts **the existing** cards.

This needs to be semantically corrected. The thing that Anki does is called **shuffling**. You have to add a shuffle option for what it does now.

What I understood and asked many of my friends to see what they have understood shows me that all of us thought that choosing **New cards in random order** means that *hey Anki, whatever I add, when I want to memorize new cards, select one from the unseen cards one by random. Don't follow any pattern for that*.

This is very different from what it does.

### Expected behaviour

The **New cards in random order** should be semantically consistent with what it does. It should do what it says. When selecting this option, it should choose one from the unseen cards at random, not randomly sort the existing cards.

### Actual behaviour

It says one thing; it does another thing.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = Xiaomi

Model = 2201116PG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 2201116PG Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.163 Mobile Safari/537.36

ACRA UUID = aab36e08-79bc-43c3-bc87-1b50b478d918

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Nefcanto** [comment]
But I'm using the latest update.

**Comment by BrayanDSO** [comment]
The fix will be shipped in the next stable update. You can use an alpha version if you want which will already have the fix

**Comment by mikehardy** [comment]
> AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

The latest update is always the latest on https://github.com/ankidroid/Anki-Android/releases which is actually 2.17alpha8, not 2.16.5 - and the 2.17alphas do in fact use the v3 scheduler by default so it is already solved in the latest

For people still on 2.16.5 to access the v3 scheduler you'll need to go into settings -> advanced and turn on the new backend + v3 scheduler

**Comment by mikehardy** [comment]
It was a little ambiguous - adding to the ambiguity is that if you are enrolled in the "beta" program on Google Play and are a member of the alpha-testing googlegroup, Google Play will actually deliver the alphas to you! https://ankidroid.org/#alphaTesting

So, the "latest" (non-ambiguously: the 2.17alph8 release) build is actually deployed to Google Play, but only a subset of all Play installs get it

Anyway, hopefully you've got things randomizing well now!
