### ISSUE TITLE
[Bug] 2.17alpha8 "Stop timer on answer" timer is started again when exiting app

### ISSUE THREAD

**Issue by Bjoe60** [ankidroid/Anki-Android#14874]
###### Reproduction Steps

1. Start reviewing a card with timer shown and "stop timer on answer" enabled
2. Go to the answer side of the card so timer is being frozen
3. Close AnkiDroid by going to home screen of phone
4. Reopen AnkiDroid

###### Expected Result
The timer should stay frozen

###### Actual Result
The timer is counting again.
This happens also e.g. when pressing a url from the answer screen and reopening the app.

###### Debug info
AnkiDroid Version = 2.17alpha8 (945014383cba6e47dc41ef244f3e929ac548246c)

Android Version = 13

ProductFlavor = full

Manufacturer = samsung

Model = SM-G985F

Hardware = exynos990

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G985F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.193 Mobile Safari/537.36

ACRA UUID = 0c7d27a4-431f-4fa4-ab8f-5b25c70651f3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by soCallmeAdityaKumar** [comment]
i am working on it
