### ISSUE TITLE
[Suggestion] Add information to document, about current situation and workarounds about Image Occlusion

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#14925]
I think that a guide to the following recent situation about image occlusion would be helpful for users who are interested in or already using the feature.
- The built-in Image Occlusion feature has been introduced from Anki Desktop 23.10. 
Users can review the I/O cards on the recent alpha series of AnkiDroid (from 2.17alph3).
  - https://forums.ankiweb.net/t/new-image-occlusion-dosent-work-on-latest-vesion-of-android/36252/13

- [Anki Doodle](https://github.com/mmjang/Ankillusion#anki-doodle), a third-party image occlusion app, is (at least as it is) no longer compatible with AnkiDroid with new storage location, 
but users can review the I/O cards again by using the old location (`/AnkiDroid/collection.media`) on `full` or `parallel` apk.
  - https://github.com/ankidroid/Anki-Android/issues/14240#issuecomment-1685136343
  - https://forums.ankiweb.net/t/help-the-card-i-made-from-ankilussion-failed-after-deleting-all-the-pictures-from-the-album/38180/2

**Comment by mikehardy** [comment]
Agreed - this should be a FAQ (altering current Image Occlusion information in the FAQ) - no need to wait on that you can just edit the FAQ now

**Comment by snowtimeglass** [comment]
Then, I'll try it.

**Comment by snowtimeglass** [comment]
I have tried editing the information in the FAQ. 
https://github.com/ankidroid/Anki-Android/wiki/FAQ#image-occlusion-cards-cant-work-on-ankidroid

**Comparison before and after the change**
https://github.com/ankidroid/Anki-Android/wiki/FAQ/_compare/ee35a603cf97c1c0549b313ff97d2ad2598517dc...f3804269900baf3a47fd5cf9f8e26b33803e520a

**Comment by mikehardy** [comment]
That looks great @snowtimeglass - thank you!

**Comment by snowtimeglass** [comment]
I'm relieved by the feedback. Thank you both!
