### ISSUE TITLE
Zoom option in decks overview

### ISSUE THREAD

**Issue by NameLessGO** [ankidroid/Anki-Android#14927]
**Is your feature request related to a problem? Please describe.**
Got a report over telegram asking an option to zoom out the characters in the deck tab, alongside changing the fonts and removing the bold effect

**Describe the solution you'd like**
- option to decrease zoom in deck tab (important)
- ability to change fonts
- a way to change font colors, adding/removing effects (misc/optional)

**Describe alternatives you've considered**
There isn't any way to decrease zoom in the deck tab, nor change fonts already checked the accessibility and advanced configuration 

**Additional context**
![IMG_20231209_234131_743.jpg](https://github.com/ankidroid/Anki-Android/assets/66227691/5c246180-a31e-477e-833a-85771bd31bcd)
The reported' deck 

![Screenshot_20231209_233737_AnkiDroid.jpg](https://github.com/ankidroid/Anki-Android/assets/66227691/ec20e52e-20b1-4e4e-a961-78c396ed54ef)

Currently in 2.17 alpha8

**Comment by criticalAY** [comment]
seems nice, I would implement the suggested feature

**Comment by NameLessGO** [comment]
![RDT_20240316_1556204935514632406668699.jpg](https://github.com/ankidroid/Anki-Android/assets/66227691/aa685712-47e8-4f48-b6c3-a1cb1d548054)

Languages shared decks users would have the same issue

+1 for accessibility category > zoom levels

**Comment by NameLessGO** [comment]
Bump: I would like to increase the font size in the card overview. Does anyone know how to do this?

https://forums.ankiweb.net/t/changing-font-size-in-card-overview-schriftgrosse-in-der-kartenubersicht-andern/43817?u=namelessgo

**Comment by david-allison** [comment]
![Screenshot_20240419_205054_AnkiDroid.jpg](https://github.com/ankidroid/Anki-Android/assets/62114487/5114889c-500d-422c-b276-ceb7db65b185)

For the card browser - see above

**Comment by NameLessGO** [comment]
I'm sorry, read card overview and thought of deck overview, will discuss in forums
