### ISSUE TITLE
[Bug] Card preview crash

### ISSUE THREAD

**Issue by gugutu** [ankidroid/Anki-Android#14928]
###### Reproduction Steps

1. Enter `Card browser`
2. Click the icon in the upper right corner
3. Click `Preview`

###### Expected Result

Normal display

###### Actual Result

![Screenshot_2023-12-10-13-35-45-597_com.ichi2.anki.jpg](https://github.com/ankidroid/Anki-Android/assets/59798823/2683601a-bc30-440f-91dc-a5560db955bd)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.17alpha9 (ee2a3ba67baeb24f8c5e42c55fadd7d980ba3fe4)

Android Version = 12 (SDK 31)

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2006J10C

Hardware = mt6889

Webview User Agent = Mozilla/5.0 (Linux; Android 12; M2006J10C Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 756393f7-4e9a-4237-bf56-cce7e9108797

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by snowtimeglass** [comment]
Reproduced.

<details>
<summary>Debug info</summary>

AnkiDroid Version = 2.17alpha9 (ee2a3ba67baeb24f8c5e42c55fadd7d980ba3fe4)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom


Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

</details>

**Comment by BrayanDSO** [comment]
I guess it was the Javascript API PR

**Comment by mikehardy** [comment]
Yeah, that was a chunk of code I wasn't sure about - it's going to be here:

https://github.com/ankidroid/Anki-Android/blob/3cde2aa5fdd1eafe1c5e9e91a3a88c8b78ba0a48/AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt#L32

and 

https://github.com/ankidroid/Anki-Android/blob/3cde2aa5fdd1eafe1c5e9e91a3a88c8b78ba0a48/AnkiDroid/src/main/java/com/ichi2/anki/ReviewerServer.kt#L105-L107

There are more than just those two cases, seems like should convert maybe to "default enable" for the API and only disable for a specific subset or similar

Follow-on question: Why did CI not register this as a crash? When we convert to AnkiPages does that mean the use cases are no longer included in our Activity startup test that was built to detect "does not even successfully do the thing without crashing" crashes? 

I think that is here for layout https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/LayoutValidationTest.kt

And here for activities https://github.com/ankidroid/Anki-Android/blob/main/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupMetaTest.kt

We may need a new strategy for AnkiPages tests or similar - this is a kind of crash that seems like we *must* be able to automatically verify

**Comment by BrayanDSO** [comment]
The Previewer gets calls from the server, but isn't an Anki page. 

Also, as far as I know, there isn't a test to check if the activities are created without issues. Only the `StartupUnderBackup` one.
