### ISSUE TITLE
Update night mode card color inversion documents to mention 2.17 will not invert

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#14921]
If we do this, it will need a big callout in the release notes and a documentation update that inverts the explanations on how to *remove* the night mode colorization with an explanation on how to re-do it with CSS (for people that do not want change)

https://github.com/ankidroid/Anki-Android/wiki/FAQ#advanced-formatting-tips
https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#customize-night-mode-colors

Basically, this feature is relatively polarizing as an idea (most don't care, some hate it, some probably like it) and everyone seems to have in general learned to live with it. Changing it requires some care for that reason as it is likely to be disruptive for a lot of people

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/14894#issuecomment-1845494840_

**Comment by david-allison** [comment]
https://ankidroid.org/removed-features.html#_automatic_night_mode_color_inversion

I'm going to remove the linked wiki sections as they're no longer relevant

**Comment by david-allison** [comment]
Removed:

> ### Invert color of images in night-mode
> The default color inversion algorithm does not affect images, with the consequence that images which have a transparent background and black lines will end up appearing invisible when night-mode is enabled. If you would like the color of images to be inverted when using night mode, you can set the following CSS selectors in addition to the `.card.night_mode` styling mentioned above. Note that these filters will generally only work on Android 4.4+.
> 
> ```css
> .night_mode img {
>  filter: invert(1); -webkit-filter:invert(1);
> }
> ```
> 
> Alternatively, if you only want images with a certain class to be inverted (for instance LaTeX images), then you can specify that class name instead of `img`:
> 
> ```css
> .night_mode .latex {
>  filter: invert(1); -webkit-filter:invert(1);
> }
> ```

Kept the usage of `night_mode` as that's still useful

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#to-access-color-in-frontback-side-of-card doesn't make sense to me, consider removing
