### ISSUE TITLE
Better UI suggestions

### ISSUE THREAD

**Issue by Sepamwa** [ankidroid/Anki-Android#14937]
Hi, I do not know much about coding but I am a regular user of the app and wanted to contribute by proposing a better UI for it.

Here is what I came up with : 

![image](https://github.com/ankidroid/Anki-Android/assets/62790741/d8f52031-b546-41cb-89e5-49908d773e80)

![image](https://github.com/ankidroid/Anki-Android/assets/62790741/64e5268f-52cb-4965-97e8-94fdac704d2a)

![image](https://github.com/ankidroid/Anki-Android/assets/62790741/1c7583b5-bd4a-409f-9942-4d398f11cef8)

And here are the details of the changes I made : 

![image](https://github.com/ankidroid/Anki-Android/assets/62790741/3a14ff6b-e3c7-451d-b7de-7ecfdb0e7862)

![image](https://github.com/ankidroid/Anki-Android/assets/62790741/10d0308a-c0f7-4f1f-8e35-af94e36db59f)

![image](https://github.com/ankidroid/Anki-Android/assets/62790741/72b74273-9450-4c63-8c01-04e3247a3276)

What do you think about it ?

I also think the Logo could use a little refresh, is it possible to make a proposition for a new one ?

**Comment by Sepamwa** [comment]
You just taught me about the existence of sub-decks lol, seems really useful.

Here is what I came up with for it : 

![image](https://github.com/ankidroid/Anki-Android/assets/62790741/c3d564fa-82b9-4920-b5a8-0071baa8423b)

When clicking on the little arrow, other decks disappear and the back gets a 20% opacity black layer for better readability. Also with the addition of the + icon, people are now more likely to know about the existence of sub-decks and not completely miss the feature like I did.

**Comment by Sepamwa** [comment]
Also I think the reduced space on the review screen is not an inconvenience for most users. I've seen Ankidroid being used mostly for learning vocabulary, names of chemicals, history dates etc. So mostly short things that do not require much space. 

However to accommodate the users that use bigger flashcards, we could make the inside of the card scrollable this way we have even more space than before.

**Comment by david-allison** [comment]
Closing as-per: https://github.com/ankidroid/Anki-Android/wiki/User-Interface-contribution

This is very broad, and unlikely to be worked on while we have so many issues under: https://github.com/ankidroid/Anki-Android/labels/Bug and https://github.com/ankidroid/Anki-Android/labels/Anki%20Ecosystem%20Compatibility
