### ISSUE TITLE
[BUG]: Card remains selected even after unselecting it

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14952]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- In the Card Browser, select a card.
- Then, select another card and unselect the previous one.

### Expected behaviour

The previous card gets unselected.

### Actual behaviour

The previous card remains selected (as indicated by the selected card count at the top). If you scroll down and then up again, both cards would even show the checkmarks.

### Debug info

```text
2.17 alpha 10
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
* ref: https://github.com/ankidroid/Anki-Android/pull/14900

**Comment by david-allison** [comment]
I'm aiming to get this done within 24 hours

**Comment by david-allison** [comment]
This can be worked around by tapping the checkbox, not the row

Will be fixed shortly, sorry for the inconvenience
