### ISSUE TITLE
Game idea

### ISSUE THREAD

**Issue by Craigdreams** [ankidroid/Anki-Android#14985]
**Is your feature request related to a problem? Please describe.**
Including anki in Android games

**Describe the solution you'd like**
Since many Android games tend to have ads in  just the right spot in order to continue playing, this would be an excellent time to display a anki card to continue playing. Combining gaming with anki card learning. I was trying to play around with tasker and automate apps to see if I could trigger anki when an ad is displayed in a gaming app. I couldn't figure it out.

**Comment by david-allison** [comment]
Thanks for the request!

I don't think this will be feasible without rooting/hacking APKs, and it's out-of-scope for our app to be modifying the functionalities of other apps in this manner, so I'm closing this as https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix

If you do get this working with the games you use, feel free to use our [API](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API) for any additional functionality which we don't provide natively, and let us know so we can add this to the Third Party Apps list

I believe the API should cover your use case of displaying + allowing you to answer cards, but if we're not providing the functionality you need, do let us know

Good luck!
