### ISSUE TITLE
[Bug] Deck Title & Time Left for Review Not Showing When Reviewing Each Deck (2.17alpha10)

### ISSUE THREAD

**Issue by tndk323** [ankidroid/Anki-Android#14986]
###### Reproduction Steps

1. Click on any deck to review (using the most recent 2.17alpha10 release)

###### Expected Result
Title & Time Left should show up in the top left corner when reviewing cards.

###### Actual Result
Blank, blue space

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Ironically, you have noticed two changes that are separate and done on purpose

- the title during reviewing was serving as a bit of a cue for some (as it provides context for a card) and thus defeating a little bit of the "active recall" effect. It was decided to remove the title while reviewing so a card is fully stand alone and you either know it or you don't
- If I understand correctly, Anki desktop removed the ETA / times thus we removed them as an ecosystem compatibility item. We attempt to behave as desktop does so we follow their changes / attempt to follow their UI

So, this is kind of a "won't fix" issue that I think we should close 🤔

**Comment by tndk323** [comment]
Oh, I see! Thank you so much for explaining!

**Comment by mikehardy** [comment]
Well it is easy for me to explain things 😆 however I recognize that the changes may be uncomfortable, especially for an app like AnkiDroid where people spend a lot of time in it and get used to things. But we have gotten a little pushback on the deck title removal thing so I think I will close this but we are listening. Perhaps this is a change that everyone hates...

Mostly replying to say that I appreciate your testing the most current alphas, the testing on our new releases and reporting issues really helps us.

**Comment by tndk323** [comment]
Yes, I think I just got so used to having the title and time there (especially the time left). Your reasoning for the Title being removed totally makes sense. As for the ETA, it was just really helpful for simply getting an idea of how much time I have left to do, even if it may not be completely accurate, and the fact that AnkiDesktop removed this feature recently as well also makes it difficult to get a time estimate. I think that's the only inconvenience.

I always look forward to the new AnkiDroid updates! Thank you all for your hard work! Reporting is the least I can do.
