### ISSUE TITLE
[BUG]: Continued performance issues with androidTest UI tests

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#14994]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Run CI emulator tests a lot
Read the logcat + watch the video
There will likely be a failure on the custom study test around 10-20% of the time (mostly because it is the most demanding)

### Expected behaviour

Successful runs every time

### Actual behaviour

Fails 10-20% of the time

### Debug info

```text
I see this in the logcat:

> 12-15 04:58:43.176   522   634 I WindowManager: Input event dispatching timed out sending to com.ichi2.anki.debug/com.ichi2.anki.DeckPicker.  Reason: 9871e8e com.ichi2.anki.debug/com.ichi2.anki.DeckPicker (server) is not responding. Waited 5002ms for FocusEvent(hasFocus=false)

But I also see that AnkiDroid *is* doing stuff well into that 5s timeout window, so it appears that it is just going slowly.

Thoughts:
- perhaps we need to bump the emulator up to a more recent version and work on stabilizing it so any efforts are spent on current emulators
- perhaps it is possible to extend that "kill activity after 5000ms" timeout to a longer timeout?
- perhaps the "emulator warming" workflow step when an emulator is cold should be run on a schedule once a week, and it should run for longer than 10 minutes (perhaps until a success criteria of CPU utilization or something vs just a time...), *and* it should clear out the system UI / pixel launcher not responding dialogs
- perhaps dedicating more cores to the emulator would help ?
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
this is a bit more important now with the merge queue in use, as emulator tests will eject a PR in queue from the queue, and it has a cascading effect of re-queueing all in-process queued PRs as they have to remove those commits from their merge queue CI run

**Comment by mikehardy** [comment]
Here is probably the second-most frequent android emulator flake (was most frequent until the custom study scheduler test stressed it...) - it's a total failure of the emulator to install packages:

```

> Task :AnkiDroid:connectedPlayDebugAndroidTest
Exception thrown during onBeforeAll invocation of plugin com.android.tools.utp.plugins.host.apkinstaller.AndroidTestApkInstallerPlugin.
Failed to install APK(s): /Users/runner/work/Anki-Android/Anki-Android/AnkiDroid/build/outputs/apk/play/debug/AnkiDroid-play-x86_64-debug.apk
Unknown failure: Exception occurred while executing 'install':
java.lang.NullPointerException: Attempt to invoke virtual method 'void android.content.pm.PackageManagerInternal.freeStorage(java.lang.String, long, int)' on a null object reference
at com.android.server.StorageManagerService.allocateBytes(StorageManagerService.java:3901)
at android.os.storage.StorageManager.allocateBytes(StorageManager.java:2278)
```

It feels like this is something that could perhaps be a re-tryable failure

As a possible success criteria gate on whether the emulator is ready, this stack is only thrown if PackageManagerInternal is null in StorageManagerService, and it will only be null if onBootPhase hasn't run:

https://android.googlesource.com/platform/frameworks/base/+/master/services/core/java/com/android/server/StorageManagerService.java#241

...so perhaps there is information in the log as to the current status of the boot phase of the device

Or, we could have a completely separate "just install the package" workflow step that was not the test step, as part of emulator startup, and if it did not work we could retry startup?

In fact, as a general idea, it may be okay to attempt to run the tests some number of times as a brute force workaround, with an emulator teardown / restart in between ?

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/actions/runs/7234648258

```
com.ichi2.anki.ReviewerTest > testCustomSchedulerWithCustomData[test(AVD) - 11] FAILED 
	androidx.test.espresso.NoMatchingViewException: No views in hierarchy found matching: view.getId() is <2131296732/com.ichi2.anki.debug:id/flashcard_layout_flip>
	If the target view is not part of the view hierarchy, you may need to use Espresso.onData to load it from one of the following AdapterViews:androidx.appcompat.widget.AppCompatSpinner{5d0581f G.ED..CL. ......I. 0,0-0,0 #7f09040d app:id/toolbar_spinner}
```

[30-x86_64-google_apis-600-0-adb_logs (2).zip](https://github.com/ankidroid/Anki-Android/files/13694199/30-x86_64-google_apis-600-0-adb_logs.2.zip)

[30-x86_64-google_apis-600-0-adb_video (2).zip](https://github.com/ankidroid/Anki-Android/files/13694200/30-x86_64-google_apis-600-0-adb_video.2.zip)

**Comment by david-allison** [comment]
```
com.ichi2.anki.ReviewerTest > testCustomSchedulerWithCustomData[test(AVD) - 11] FAILED 
	java.lang.AssertionError: View assertion was not true within 30000 milliseconds
	at org.junit.Assert.fail(Assert.java:89)
```

[30-x86_64-google_apis-600-0-adb_video (3).zip](https://github.com/ankidroid/Anki-Android/files/13694930/30-x86_64-google_apis-600-0-adb_video.3.zip)
[30-x86_64-google_apis-600-0-adb_logs (3).zip](https://github.com/ankidroid/Anki-Android/files/13694931/30-x86_64-google_apis-600-0-adb_logs.3.zip)
