### ISSUE TITLE
Can ankidroid 2.16.x + android 13 use SD card as storage as before? i deadly want this, thx.

### ISSUE THREAD

**Issue by ccchan234** [ankidroid/Anki-Android#14996]
hi,

i looked up that officially not supported.

but some old post claim success in older versions. i think what changed is android 13. 

i got the latest ankidroid, with data migrated.

i tried to do the same trick as the link at bottom, but permission problem.

if someone success pls see if you can share.

thanks

ps saw someone claim only move the collection.media to SD, is that ok too?

ref:

[ref](https://www.reddit.com/r/Anki/comments/hnem0y/how_to_completely_migrate_anki_to_sd/?onetap_auto=true)

**Comment by david-allison** [comment]
Use the 'full' version and it should work. Google Play won't let us distribute it:

 https://f-droid.org/en/packages/com.ichi2.anki/

**Comment by ccchan234** [comment]
hi,
thank you for the replyS.
may i ask should i better use ntfs or exfat? thank you

**Comment by david-allison** [comment]
I don't think Android supports NTFS. 

I don't use an SD card, so can't help further. There's likely some forum threads about this

**Comment by ccchan234** [comment]
ok, i'll try exfat.
ps,
just FYI, some android variants i used before support NTFS.
but i didn't remember it's original AOSP, or xiaomi MIUI, or custom rom like cyangenmod/lineageos.
anyway, thankyou.

**Comment by david-allison** [comment]
Thanks! Let us know what works

**Comment by ccchan234** [comment]
hi, very very much appreciate your help.

i just found indeep the google play version worked!
i.e. should be the latest 2.16.x

1. i prepared an empty tf card, formated as exfat
failed here:
2. i use on redmi note 9 pro, android 12. 
with the f-droid ankidroid.
then no matter how, the ankidroid cant change to folder  on tf. (but it can export to the tf)

success using samsung a33 5g
since i deadly need this feature, i tried to do so on a samsung.
(xiaomi/redmi's MIUI s file system/structure is differ from AOSP, that's why i turn to samsung)
1. just format the tf again if you are obcessive like me
2. make a folder say ankidroid4 on the tf card
3. just go into the ankidroid, simply in the settings change into that path (i get thru es file manager, the one blamed to be spyware)
4. then it worked.

thanks.

ps i have setup my sync server too so now i am completely free from the size limits on anki/ankidroid.

thank you

**Comment by ccchan234** [comment]
currently it's still syncing, but from es file manager, i saw my 1GB files are downloading inside. so should be ok.

**Comment by ccchan234** [comment]
FYI,
after 1st download, ankidroid ask for migration.
migration did finished and is thus ok.
works. thanks

**Comment by david-allison** [comment]
That's unexpected

Especially as the full version shouldn't # need a migration

Where is the AnkiDroid folder in the advanced preferences? Has the data been moved from the SD Card?

**Comment by ccchan234** [comment]
hi,

the f-droid full version dont work on my redmi note9 pro, running MIUI (android 12), this could be because the MIUI s file system structure is differ from AOSP.

then i turn to my current samsung a33 5g android 13, running google play version,
i simply insert the tf card, format it, and add a folder say ankidroid4 to the tf card.
then inside the app's setting, choose that folder.

later it forced migration and moved to
/storage/xxxx-xxxx/Android/data/com.ich2.anki/files/AnkiDroid1

i verified that seems no more files are left in internal storage, or tf-card/ankidroid4.
everything is migrated to there.

thus seems this worked.

**Comment by ccchan234** [comment]
hi,
i strongly agree and suggest to use the f-droid version too.

today i removed the account, / uninstalled the play store version.
and re-install.

however, seems once migrated, the location would be there and cannot change.

using f-droid version is more free and easy to change the location,
and it didn't ask for migration.

thanks
