### ISSUE TITLE
Enable "trailing-commas" rules in ktlint / ktlint-gradle

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#14995]
the idea of a lint setting where "trailing commas" are allowed (assuming the language doesn't care) allows changes like this to create one `+1` in the diff instead of a `-1 +2`

Kotlin supports it since 1.4 apparently and ktlint does now as well, with ktlint-gradle finally adopting current versions this may be possible:

https://pinterest.github.io/ktlint/latest/rules/standard/#trailing-comma-on-call-site (two rules, the second is right after this one)

What do you all think? I'm +1 on trailing commas, I enable it in all my javascript/typescript stuff

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/14981#discussion_r1427527776_
            

David also agreed (visible on the discussion)

So the task here is:

- enable those two rules in `.editorconfig` (I think that's the spot...)
- verify that we fail the ktlintFormatCheck test
- run ktlintFormat to auto-format everything with new trailing commas
- visually inspect the diff to see if our parameter lists and such all have trialing commas now
- do one commit where you change the setting, with a nice commit message
- do one commit with all the formatting together
- hopefully it passes CI and we squash merge them into main

**Comment by relentless-pursuit** [comment]
I am on it.

**Comment by david-allison** [comment]
Closing as-per https://github.com/ankidroid/Anki-Android/pull/14997#issuecomment-1946306075. 

Might eventually get around to it with extensions to the underlying library or our processes, but it's not worth keeping around if it's barely actionable & for little reward

* https://github.com/ankidroid/Anki-Android/pull/14997#issuecomment-1946306075
