### ISSUE TITLE
"Exam Notifier" feature similar to AnkiDesktop add-on

### ISSUE THREAD

**Issue by tndk323** [ankidroid/Anki-Android#14999]
**Describe the solution you'd like**
It would be amazing if we had the option of being notified with a pop-up when a certain card review will be past an exam date, similar to the Exam Notifier add-on that's currently available for AnkiDesktop. Thank you!

**Comment by mikehardy** [comment]
Hi there! With apologies, if it is not in the main Anki Desktop implementation, we will not add it here. We aim to have fidelity with the features in Anki Desktop - no more + no less, we do not consider adding add-on features to our feature set
