### ISSUE TITLE
Hide the statistics toolbar on scroll

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#14991]
Currently, the graphs don't fit in the screen when in the landscape mode.

https://forums.ankiweb.net/t/suggestion-to-redesign-the-statistics-tab/37129/6

Dae said:
> It fits on an iPhone. You could ask the AnkiDroid devs to decrease the height of the top area and/or hide the status bar.

**Comment by BrayanDSO** [comment]
Hiding the toolbar on scroll is on my plans

**Comment by neeldoshii** [comment]
@BrayanDSO Can I work on this?

**Comment by BrayanDSO** [comment]
Originally I would only tackle this in 2.18, so go for it, @neeldoshii
