### ISSUE TITLE
Can't go back to deck picker by using "Abort learning" or "Abort Learning and Sync" in the congratulations screen

### ISSUE THREAD

**Issue by btsworld613** [ankidroid/Anki-Android#14998]
###### Reproduction Steps

After I finish reviewing a deck, "Congratulations! You have finished this deck for now." appears, and when I try to go back to the main deck screen by pressing on my game controller buttons that I set up for each "Abort learning" and "Abort Learning and sync", I can no longer go back. I have to physically touch the back arrow on the Anki screen. 

I have no problem with these functions when in the middle of reviewing the cards. It only happens when I finish. This was not an issue before from what I remember. Thank you!

###### Expected Result
Going back to home screen when using either the "Abort learning" or "Abort Learning and Sync" options.

###### Actual Result
Nothing happens. Stays on the "Congratulations!..." screen.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
I'm removing the `bug` header because this isn't a bug. 

What happened is that the congratulations message was upgraded from a popup to a whole screen. And your issue is actually that your controller don't have a default way to do back navigation (an equivalent to the `Esc` key of a keyboard)
