### ISSUE TITLE
[Bug] bottom of settings is truncated on some phones (many Google Pixel models)

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#14993]
###### Reproduction Steps

![Screenshot_20231215-153824.png](https://github.com/ankidroid/Anki-Android/assets/357361/258d3ddf-16fb-448b-9abe-ff9d7ba074f9)

Open this screen. Bottom is hidden but the android bar. Scrolling does not help

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.17alpha10 (50fa39cd561d83662cd5ef1f708b14a9a15c74ac)

Backend Version = 0.1.31-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 8 Pro

Hardware = husky

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro Build/UD1A.231105.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = 47035a3d-ff8b-4423-8485-1d6d82d48957

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
![Screenshot_2023-12-15-23-34-26-09_7b5228b5a93c00ecba98ecb0735c59e2.jpg](https://github.com/ankidroid/Anki-Android/assets/65113071/753fc280-90d8-4b77-9b1b-8e46cce5015a)

Showing in my case.
It is mobile specific. I think by putting `marginBottom` the issue may be solve

**Comment by BrayanDSO** [comment]
Can't reproduce Arthur's issue. And I don't see what is the problem in Sanjay's screenshot

**Comment by david-allison** [comment]
Likewise

**Comment by BorisNA** [comment]
It is the same to me. Google pixel 4a, android 11

The bottom part of the settings screen is cut. It just can't be scrolled up anymore
![Screenshot_20231216-111029](https://github.com/ankidroid/Anki-Android/assets/7961527/8ce1fb04-f64e-4a14-8df8-acfad04a3159)
![Screenshot_20231216-111010](https://github.com/ankidroid/Anki-Android/assets/7961527/d31dc405-7bb0-4d29-8d39-dd0cae59793b)

**Comment by BorisNA** [comment]
P.S. I can experiment with a custom build if you show me what to try

**Comment by BrayanDSO** [comment]
Apparently the toolbar isn't being collapsed on Pixels. Why? I don't know. We need a dev with a pixel to fix it

**Comment by BorisNA** [comment]
It was Ok in Alpha 3. Have there been any significant changes to this code since then?

**Comment by david-allison** [comment]
No issues on my pixel3a (HEAD & Android 11). Upgrading to Android 12 to see

**Comment by BorisNA** [comment]
Ok, I've tested - it is exactly https://github.com/ankidroid/Anki-Android/commit/94ec0c26d29a1b025c2ccfc4cd040791df83f676

* I have Android 11, never updated to 12. So I don't think that it has something to do with A12
* I have a tablet with a PixelExperience GSI 12.1 ROM - it works Ok there

**Comment by BorisNA** [comment]
Very weir behavior:

If I go to any settings subpage and then return back with the gesture approx 1/3 from the top of the screen, ~ 75% prob. that it will return to the correctly displayed main settings page with the collapsed top bar and the visible "about" (it is completely hidden now due to the bug).

**Comment by BrayanDSO** [comment]
Maybe moving the `android:fitsSystemWindows="true"` from the CoordinatorLayout to the AppBarLayout will solve that.

Or maybe we need to deal with insets. But I can't help without being able to reproduce it

**Comment by BorisNA** [comment]
But it is already there in the AppBarLayout (if I understand correctly). https://github.com/ankidroid/Anki-Android/blob/94ec0c26d29a1b025c2ccfc4cd040791df83f676/AnkiDroid/src/main/res/layout/preferences.xml

I've built this 94ec0c2 already, and the bug was there.

I can try something or build, but unfortunately, I know next to nothing in Android development.

**Comment by BorisNA** [comment]
Well, I really don't know what I'm doing, but after I removed `android:fitsSystemWindows="true"`  altogether it more or less works. Is this behavior correct?

https://github.com/ankidroid/Anki-Android/assets/7961527/b809a658-daf0-4105-8f49-be29836189d1

Resulting file is attached

[preferences.xml.zip](https://github.com/ankidroid/Anki-Android/files/13695496/preferences.xml.zip)

**Comment by BrayanDSO** [comment]
The status bar color stops being updated that way when the toolbar is collapsed

**Comment by BorisNA** [comment]
But it does change. I don't see it on the phone (scheme is dark), but here it is in the video

![Screenshot from 2023-12-17 14 37 20](https://github.com/ankidroid/Anki-Android/assets/7961527/f5a6c0a0-f651-4a8c-8c3b-1e571815ec43)

P.S. I opened Chrome - color doesn't change there, and it looks a little bit cleaner for me. But tastes differ ofcourse.

**Comment by BorisNA** [comment]
Ok. In Alpha11, this change seems to fix a problem: adding `android:fitsSystemWindows="true"` to the AppBar without removing from Coordinator

``` XML
<androidx.coordinatorlayout.widget.CoordinatorLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/root_layout"
    android:fitsSystemWindows="true"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    tools:context=".preferences.Preferences">

    <com.google.android.material.appbar.AppBarLayout
        android:id="@+id/appbar"
        android:fitsSystemWindows="true"
        android:layout_width="match_parent"
        android:layout_height="wrap_content">
```

It looks like this now


https://github.com/ankidroid/Anki-Android/assets/7961527/7b0012a1-eccd-437a-a709-a42a43f79816

And the file is below

[preferences.xml.zip](https://github.com/ankidroid/Anki-Android/files/13696707/preferences.xml.zip)

**Comment by BorisNA** [comment]
@BrayanDSO could you please verify that this works correctly for your devices and commit to the repository if it is Ok?

**Comment by BrayanDSO** [comment]
Works fine. If it has resolved the issue on Pixels, you can send a PR (I can't commit directly to main and we normally avoid that).

Thanks a lot for the work, @BorisNA
