### ISSUE TITLE
[BUG]: Bottom of search results is truncated

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#15008]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Open Settings
2. Search  (e.g. search 't')
3. Scroll to bottom 

### Expected behaviour

The bottom of search results should be properly visible

### Actual behaviour

The bottom of search results is not visible properly

https://github.com/ankidroid/Anki-Android/assets/65113071/bf3c9864-df30-4bf4-9b4c-cdf722999600

### Debug info

```text
AnkiDroid Version = 2.17alpha10-debug (50fa39cd561d83662cd5ef1f708b14a9a15c74ac)

Backend Version = 0.1.31-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.193 Mobile Safari/537.36

ACRA UUID = 75cf281b-7921-408d-a660-d55f11d401fe

Crash Reports Enabled = false
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BorisNA** [comment]
Oh, it's definitely https://github.com/ankidroid/Anki-Android/issues/14993

So, it's not Pixel-specific.
