### ISSUE TITLE
[Bug]Simplified Chinese language character error

### ISSUE THREAD

**Issue by xjqm-tao** [ankidroid/Anki-Android#15019]
###### Expected Result
Syntax error of statistical string at the bottom of deck.
![IMG_20231218_122002](https://github.com/ankidroid/Anki-Android/assets/126331411/f0c26492-2544-48e6-8cd1-f5064e97c5f9)

Change "今天在 ⁨⁨0⁩ 秒内⁩ 内学习了 ⁨0⁩ 张卡片（平均每张卡片 ⁨0⁩ 秒）" to "今天在 ⁨⁨0⁩ 秒内⁩学习了 ⁨0⁩ 张卡片（平均每张卡片 ⁨0⁩ 秒）"
###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, is this for AnkiDroid 2.16 or 2.17?

**Comment by david-allison** [comment]
Pontoon ref: backend.studiedToday() -> `statistics_studied_today`

**Comment by xjqm-tao** [comment]
> Hi, is this for AnkiDroid 2.16 or 2.17?
2.17alpha12，Previous versions also had this problem.

**Comment by xjqm-tao** [comment]
> Pontoon ref: backend.studiedToday() -> `statistics_studied_today` -> https://i18n.ankiweb.net/zh-CN/core/core/templates/statistics.ftl/?string=22382

I don't know how to operate it. It may be this character：https://i18n.ankiweb.net/zh-CN/core/core/templates/statistics.ftl/?search=%E7%A7%92%E5%86%85&string=22387

**Comment by xjqm-tao** [comment]
> Hi, is this for AnkiDroid 2.16 or 2.17?



> Pontoon ref: backend.studiedToday() -> `statistics_studied_today` -> https://i18n.ankiweb.net/zh-CN/core/core/templates/statistics.ftl/?string=22382

It should be this one, just delete a "内"。😅However, I can't operate it. Can you modify it?

**Comment by snowtimeglass** [comment]
Hi @pilgrimlyieu, would you mind changing the translation as suggested above?

**Comment by pilgrimlyieu** [comment]
> Hi @pilgrimlyieu, would you mind changing the translation as suggested above?

> It should be this one, just delete a "内"。😅However, I can't operate it. Can you modify it?

抱歉，是我的失误，已经修正了。

I'm sorry. It was my mistake. It's been corrected now.

**Comment by xjqm-tao** [comment]
> > Hi @pilgrimlyieu, would you mind changing the translation as suggested above?
> 
> > It should be this one, just delete a "内"。😅However, I can't operate it. Can you modify it?
> 
> 抱歉，是我的失误，已经修正了。
> 
> I'm sorry. It was my mistake. It's been corrected now.

原来是你手抖😂。那个翻译平台怎么登录的？

**Comment by pilgrimlyieu** [comment]
> 那个翻译平台怎么登录的？

如果想要贡献翻译的话，可以参阅 [Anki Translation Guide](https://translating.ankiweb.net)。

**Comment by david-allison** [comment]
This needs a backend update to fix

**Comment by xjqm-tao** [comment]
> This needs a backend update to fix

oh，thank you

**Comment by david-allison** [comment]
No point in keeping this around if it'll be pulled in in the next backend release
