### ISSUE TITLE
Add Camera option to Image Occlusion

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15017]
**Is your feature request related to a problem? Please describe.**
Image Occlusion works more wonderful in 2.17alpha11, but for now it can't open camera mode to take a photo image.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/f89908b9-c44a-4dec-b13d-ea45c7709d5e" width="320px">

**Describe the solution you'd like**
It would be great to add an option for camera, as on AnkiMobile.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/07c25621-5adb-4592-b5fe-911d262e8ffb" width="320px">

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by criticalAY** [comment]
Taking it up
