### ISSUE TITLE
[BUG]: Siblings are not always buried

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15011]
I am not sure of the exact trigger, but sometimes AnkiDroid doesn't bury the siblings of the reviewed cards.

In the Deck Options, I have enabled all of the following three options:

- Bury new siblings
- Bury review siblings
- Bury interday learning siblings

I don't know if this is an issue in the Desktop version or not because I rarely do my reviews on the Desktop.

###### Debug info

I remember first seeing this happen in 2.16.5 with New Backend (the issue may exist in earlier versions too).

The issue still persists in 2.17 alpha 10.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks!!
