### ISSUE TITLE
[BUG]: Links in cards no longer work

### ISSUE THREAD

**Issue by xiety** [ankidroid/Anki-Android#15015]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Enter a `<a href="https://google.com">test</a>` in a field's html.
Open card, click on this link.

### Expected behaviour

Link opens

### Actual behaviour

Nothing happens

### Debug info

```text
AnkiDroid Version = 2.17alpha11 (69910abf418fbaa6004736127516180bff5edb3b)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 10 (SDK 29)

ProductFlavor = full

Manufacturer = HUAWEI

Model = STK-LX1

Hardware = kirin710

Webview User Agent = Mozilla/5.0 (Linux; Android 10; STK-LX1 Build/HUAWEISTK-LX1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = c615841e-0e0d-4e08-893d-6bf7124be077

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

This stopped working in 2.17alpha11, it worked in 2.17alpha10

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by tkozybski** [comment]
For me, nothing in the review window seems to respond. Scrolling nor clicking. Only gestures and clicking the bottom bar.

**Comment by BorisNA** [comment]
Selecting and copying text (or calling dictionary) either. It breaks everything for me.
Morning build with 9eb0e82 commit was good, but it is not possible to downgrade.

**Comment by mikehardy** [comment]
@david-allison has posted a PR already with a revert, looks clean and is working through CI tests now, once all the automated tests are through and it's landed I'll kick out alpha12 - thanks for testing the alphas and reporting the issue it really helps! Sorry alpha11 wasn't a winner

**Comment by david-allison** [comment]
Echoing Mike: Thanks for your patience and thanks for testing!

**Comment by saifkaral** [comment]
Also found out java script doesn't work anymore

**Comment by david-allison** [comment]
@saifkaral Could you open a new issue with more details? Thanks

**Comment by mikehardy** [comment]
In about 40 minutes (building all the different .apks takes a while...) 2.17alpha12 will be out, may be best to wait and check that one to see if it was all one problem or if we have multiple problems and need more info on the second one

**Comment by saifkaral** [comment]
> @saifkaral Could you open a new issue with more details? Thanks

Any <script></script> in my cards does not work at all ,it doesn't respond at all

**Comment by david-allison** [comment]
@saifkaral Thanks! Could you please open a new issue here: https://github.com/ankidroid/Anki-Android/issues/new/choose so we csn track it
