### ISSUE TITLE
[BUG]: "Save" makes an error on Add screen when the note type is Image Occlusion

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15025]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Open the app
2. "+" -> "Add"
3. Select "Image Occlusion" in "Type:"
4. "Save"
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/16044d33-91ce-4dda-882b-b62c47b6e789" width="320px">

### Expected behaviour

No error.

### Actual behaviour

Error
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/5ee5d437-f94d-43f4-b407-472462986cd9" width="320px">

### Debug info

```text
AnkiDroid Version = 2.17alpha12 (3c81b124d2ca555d48e82e0f2d31d8ed13d3b662)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/118.0.0.0 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

It might be good to disable (gray) or hide the "Save" button in this case from the start.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
I did notice it when I was working with the enhancement for camera, can we consider hiding the save button in case of image occlusion type?

**Comment by david-allison** [comment]
The user is informed that a card is saved when image occlusion exits, so it's fine

**Comment by snowtimeglass** [comment]
Just to make sure: the save button needs to be kept on "_Edit note_" screen even if the note type is Image Occlusion.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/ef267d7a-6297-4fda-ac77-f97579ab76c9)
