### ISSUE TITLE
[BUG]: Search in card browser isn't case-insensitive for special letters like Ä, Ö, Ü.

### ISSUE THREAD

**Issue by lievenvanderheide** [ankidroid/Anki-Android#15027]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Add a card with "Über".
- open the card browser.
- Type "über" in the search bar.

### Expected behaviour

The entry for the card with Über is visible.

### Actual behaviour

The entre for the card is not visible.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = samsung

Model = SM-A515F

Hardware = exynos9611

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A515F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = 9299daa3-5604-4b0a-90b8-0e3ec8b8b91a

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, could you try this on the 2.17 alpha, as we've made large changes to how searching works internally:

https://github.com/ankidroid/Anki-Android/releases/download/v2.17alpha12/AnkiDroid-2.17alpha12.parallel.A.apk

**Comment by SanjaySargam** [comment]
Reproduced in latest version

**Comment by david-allison** [comment]
Even: https://docs.ankiweb.net/searching.html#ignoring-accentscombining-characters

?

**Comment by SanjaySargam** [comment]
`nc:uber` using this getting result as expected.

**Comment by david-allison** [comment]
Same behaviour as 

Anki ⁨23.10 (51a10f09)⁩

Closing as https://github.com/ankidroid/Anki-Android/labels/upstream-issue. If this is changed in Anki Desktop, do let us know.
