### ISSUE TITLE
[Bug] Missing scrolling bar

### ISSUE THREAD

**Issue by Benjamin007** [ankidroid/Anki-Android#15022]
###### Reproduction Steps

1. For the anki deck Kanji damage, 
https://ankiweb.net/shared/info/748570187

For any cards whose answer is too big to fit in one screen:
Like the card number 40 (see screenshot in the actual result section).

I cannot see the bottom lf the card.

It used to work, so I do not think there is a problem with the deck.

###### Expected Result
I want a side bar to scroll down and see the bottom of the cards.

###### Actual Result

No side bar on the right to scroll, so part of the answer is not accessible. I have to click on "edit card" to see it.

It used to work, so I do not think there is a problem with the deck.
![Screenshot_20231218-143623](https://github.com/ankidroid/Anki-Android/assets/5960294/a6d8faf9-c0bc-4da2-a08a-483576d6cfb6)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.17alpha11 (69910abf418fbaa6004736127516180bff5edb3b)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Fairphone

Model = FP4

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; FP4 Build/TKQ1.230127.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/119.0.6045.193 Mobile Safari/537.36

ACRA UUID = c470112d-347a-45b8-908f-9407699ba184

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Fixed in alpha 12
