### ISSUE TITLE
[Bug] customSchedulingJs issue: Cannot study Filtered Decks

### ISSUE THREAD

**Issue by jcznk** [ankidroid/Anki-Android#15035]
###### Reproduction Steps

1. Create a Filtered Deck with rescheduling enabled
2. Open it to study it
3. Click on "Show Answer" 

###### Expected Result

The card is flipped to the back side.

###### Actual Result

The card is not flipped and the front continues being shown.

###### Debug info
Tested on 2.17alpha12 (anki 23.10.1 / fac9e0ee), arm64-v8a version.
Did not occur on alpha8.
It started occuring at least since alpha10. Did not test on alpha9.

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report. Looking into it!

**Comment by david-allison** [comment]
I can't reproduce this in **2.17alpha12-debug** (e892afadd1180e24a6ec46aeb9b4f117ec646f68), are you willing to export your collection and upload it here as a `zip`?

If not, would you be willing to produce a minimum reproducible example, or send your collection to me privately?

**Comment by david-allison** [comment]
Hmm... I have a different issue: the card is not rescheduled

**Comment by david-allison** [comment]
I can't reproduce this in **2.17alpha12-debug** (e892afadd1180e24a6ec46aeb9b4f117ec646f68), are you willing to export your collection and upload it here as a `zip`?

If not, would you be willing to produce a minimum reproducible example, or send your collection to me privately?

**Comment by david-allison** [comment]
@jcznk Are any settings such as 'automatic display answer' being used?

**Comment by david-allison** [comment]
Could be a WebView render issue. Have you seen `WebView renderer crashed.` appear?

**Comment by jcznk** [comment]
Hi. Thanks for the prompt answer!

I do not have 'automatic display answer' enabled. I tried activating it, and it does not work on Filtered decks with 'Reschedule' enabled. However, it works as expected on normal decks.

I'm not sure what 'JS API' is. I do use 'Enable AnkiDroid API' to allow Pleco to interact with my AnkiDroid. I tried disabling it, but it did not solve the problem.

I do not remember seeing `WebView renderer crashed.` appear.

Here is a sample deck to try to reproduce the issue: [Sample Deck](https://gofile.io/d/4XDpgb) (I exported it as an .apkg file. Please let me know if you need it in another format!)

**Comment by david-allison** [comment]
Can't reproduce yet. Getting the full database `collection.anki2` would be ideal

Do you have a PC to connect to your phone?

The `collection.anki2` should be in `Android/data/com.ichi2.anki/files/AnkiDroid`

❗️ **This file contains all your Anki Decks (except media), answer history + settings**, you may not want to share this publicly

If you don't mind sharing publicly, could you zip it up and upload it here

Otherwise, could you email it to me at my gmail: `davidallisongithub`

**Comment by david-allison** [comment]
`customSchedulingJs` is

```js
if ( 
  states.good.normal && 
  states.good.normal.review && 
  states.current.normal.review 
) { 
  let oldEase = states.good.normal.review.easeFactor; 
  let diff = 2.2 - oldEase; 
  states.good.normal.review.easeFactor += 
    Math.sign(diff) * Math.min(0.05, Math.abs(diff)); 
}
```

Then this code goes into an infinite loop:

https://github.com/ankidroid/Anki-Android/blob/041f9d113ecf5046b2575ca6e72498c497a8422e/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.kt#L1076-L1082
