### ISSUE TITLE
[BUG]: The audio play button is stretched to the full screen

### ISSUE THREAD

**Issue by NDancer** [ankidroid/Anki-Android#15040]
###### Description
If the "sound" field in the card type settings is at the end of "back" side, the audio play button stretches across the screen. This does not happen if the "sounds" field is at the end of the face card.

###### Reproduction Steps

1. Go to "manage type notes"
2. Select type active card type
3. On the "back" side, specify the "sound" field at the end
4. Save changes

###### Expected Result
Button to play audio of similar size to text

###### Actual Result
The audio play button is stretched to the full screen

###### Debug info
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 9

ProductFlavor = play

Manufacturer = samsung

Model = SM-A530F

Hardware = samsungexynos7885

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-A530F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.115 Mobile Safari/537.36

ACRA UUID = 1de8a556-717a-4770-9930-8a4d6d40bf79

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Attachments
if "sound" at the end
![Screenshot_20231221-105156_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/80644965/c8ebce4c-ec2f-46ec-aa0d-c1fd1a5383a2)
![Screenshot_20231221-010018_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/80644965/79c06730-260c-489b-9189-50a654a3246e)

if the "sound" aren't at the end
![Screenshot_20231221-105222_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/80644965/3a8182de-28c7-443b-9500-844c320d7260)
![Screenshot_20231221-105237_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/80644965/511087ae-710d-4c24-a19f-33fe96a1618a)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
Not Reproduced in latest alpha

**Comment by david-allison** [comment]
@NDancer , could you try this in our beta and see if it's still a problem?

**Comment by NDancer** [comment]
@david-allison, I'll try, but no promises)

**Comment by NDancer** [comment]
@david-allison , hi. I checked the bug on the beta version AnkiDroid-2.17beta2.parallel.A.apk. The defect is reproducible. The screenshots are attached.

![Screenshot_20240210-225334_AnkiDroidA](https://github.com/ankidroid/Anki-Android/assets/80644965/89e406e7-2736-4c3a-8223-9e2229badf9a)
![Screenshot_20240210-225444_AnkiDroidA](https://github.com/ankidroid/Anki-Android/assets/80644965/05f65584-f177-4ddd-96c7-dd7a1da679f1)
![Screenshot_20240210-225403_AnkiDroidA](https://github.com/ankidroid/Anki-Android/assets/80644965/059ee27f-c5ad-4f9e-b991-4e8a4a3130a5)
![Screenshot_20240210-225334_AnkiDroidA](https://github.com/ankidroid/Anki-Android/assets/80644965/33a91094-658a-480f-82fc-8cdf14527bb0)
![Screenshot_20240210-225218_AnkiDroidA](https://github.com/ankidroid/Anki-Android/assets/80644965/9a1606e7-1960-4841-b8e9-4197ae7e4cd2)

**Comment by david-allison** [comment]
Thanks, could you provide those as text?

**Comment by NDancer** [comment]
what do you mean by "those"? Settings note types?

**Comment by david-allison** [comment]
* The screenshots: Front, back & CSS

**Comment by NDancer** [comment]
Front:
<div class=transl>{{translation}}</div> 

Back:
{{FrontSide}}

<hr id=answer>
<br>
<br>
<div class=word>{{word}}</div>
<div class=transc>[{{transcription}}]</div>
{{sound}} 
<div class=cont>{{context}}</div

Styling:
.card { 
 font-family: Arial,sans-serif;  
  text-align: center; 
 background-color: #F5F2E7; 
} 

.word { 
 font-size: 28px;  
  color: #000000; 
} 

.nightMode .word {
 color: white
}

.transc {  
 font-size: 16px;  
 color: #317FC0;  
 font-family: Arial Unicode MS; 
} 

.transl {  
 font-size: 22px; 
 color: #995B36; 
 margin: 0 0 10px; 
} 

.cont {  
 font-size: 15px;  
 font-style: italic; 
 color: #666666;  
 margin: 10px 0 0; 
}

.cont b {  
color: green !important; 
}

**Comment by david-allison** [comment]
> `<div class=cont>{{context}}</div`

What if this is changed to `</div>`

**Comment by NDancer** [comment]
ahaha, it works! such a stupid mistake

**Comment by david-allison** [comment]
Great to hear, thanks!
