### ISSUE TITLE
Cannot view cards offline

### ISSUE THREAD

**Issue by kimo-supremo** [ankidroid/Anki-Android#15045]
###### Reproduction Steps

1. turn off wifi
2. open a deck
3. card doesn't show

###### Expected Result
card shows

###### Actual Result
![Screenshot_2023-12-21-20-57-38-876_com.ichi2.anki-edit.jpg](https://github.com/ankidroid/Anki-Android/assets/70135155/1642ae1b-c510-462f-96c5-df863e5ac9de)

###### Debug info
AnkiDroid Version = 2.17alpha12 (3c81b124d2ca555d48e82e0f2d31d8ed13d3b662)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = 2107113SG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 2107113SG Build/TKQ1.220829.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = 3e5011c5-b2d5-4709-b894-ec73704affd8

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
What's the content of the card?
Could be it is referencing some thing that is not local in collection? https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

Normally I'd be pretty certain of that but anyone using the alpha series probably already knows their way around card templates etc - but I still have to ask

**Comment by kimo-supremo** [comment]
this happens to all cards. this wasn't an issue before the latest alpha although the previous alpha would just not let me scroll down. this is the content of the this particular card
![Screenshot_2023-12-21-21-04-41-674_com.ichi2.anki-edit.jpg](https://github.com/ankidroid/Anki-Android/assets/70135155/75692c59-eec8-48c5-8c60-9e919cd3d072)

**Comment by david-allison** [comment]
@kimo-supremo could you export a sample card? Can't reproduce this yet

**Comment by kimo-supremo** [comment]
@david-allison it's not just this card it's any and every card even the most basic ones

**Comment by david-allison** [comment]
@kimo-supremo I can't reproduce this with airplane mode on

Could you send a sample card which isn't working?

**Comment by kimo-supremo** [comment]
@david-allison https://github.com/ankidroid/Anki-Android/assets/70135155/94757d99-b1a9-44d8-82ff-d3bc6ce8940a

**Comment by david-allison** [comment]
Can you export the card in the card browser, or the deck in the deck picker? I can't import a screenshot

**Comment by kimo-supremo** [comment]
@david-allison
https://we.tl/t-M19YT96MDO

**Comment by david-allison** [comment]
Still can't reproduce, sorry!

![Screenshot_20231222_100112_AnkiDroid.jpg](https://github.com/ankidroid/Anki-Android/assets/62114487/90f75961-7858-45bd-807c-bcfa4081ded8)

**Comment by kimo-supremo** [comment]
idk what to do

**Comment by david-allison** [comment]
What were the steps you took to use Firefox as the system WebView?

**Comment by david-allison** [comment]
Come to Discord and ask for help with setting up HTML/JavaScript debugging

You'll need a computer

https://discord.gg/qjzcRTx

**Comment by david-allison** [comment]
> this wasn't an issue before the latest alpha although the previous alpha would just not let me scroll down. this is the content of the this particular card

For posterity, what was the version number of the alpha which this wasn't a problem for? I presume alpha10

Could you try alpha 11 to help us narrow down the possible issuex

**Comment by kimo-supremo** [comment]
@mikehardy @david-allison nevermind i tested on my tablet and also couldn't reproduce. i deleted the app on my phone and reinstalled it and now working fine. maybe it got corrupted in the installation process idk. thanks for your help
