### ISSUE TITLE
Add letter indicators to app icons and app names of the parallel builds

### ISSUE THREAD

**Issue by sepsol** [ankidroid/Anki-Android#15048]
**Is your feature request related to a problem? Please describe.**
When installing the parallel builds, it is impossible to distinguish between them and the main installation.

**Describe the solution you'd like**
It would be great if the parallel installations appended the letter to their name like `AnkiDroid (A)` and also to their icon like the screenshot below:

![zqnjx535ogg61 (1)](https://github.com/ankidroid/Anki-Android/assets/47871887/47b46516-6493-4fb5-8803-ae55c5f49b39)

Each letter could also have different colors.

**Describe alternatives you've considered**
I myself use launchers but my parents and my girlfriend either don't like or don't use launchers.

**Additional context**
N/A

**Comment by mikehardy** [comment]
This is something I suffer with actually 😆 - I would love it

**Comment by david-allison** [comment]
Getting close to adding profile support, but this would be a useful stopgap
