### ISSUE TITLE
[BUG]: Remaining time during review Not showing in the top bar

### ISSUE THREAD

**Issue by mazencamper** [ankidroid/Anki-Android#15047]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

enter review for any deck

### Expected behaviour

 display the expected Remaining time for set of cards to be done in the top bar

### Actual behaviour

 Remaining time during review Not showing in the top bar
![Screenshot_20231222-005729_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/64913600/038257c4-05ad-4d17-99b7-6960c14217fd)

### Debug info

```text
Ankidroid 2.17alpha12 arm v7a

Android 10 
Samsung j600f
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
ETA was removed on purpose - it is not present / no longer present in Anki Desktop and we aim to be consistent in feature addition and removal.

I understand people have grown used to it, but it was removed on purpose

#14930

**Comment by Alphyn-gunner** [comment]
Bad decision. I used this.

**Comment by mazencamper** [comment]
can you at least keep the deck name of the card above while review  ?

and ps: anki on windows i think readded the remining time
