### ISSUE TITLE
[BUG]: Unbury is not available when enabling v3 scheduler 

### ISSUE THREAD

**Issue by upsuper** [ankidroid/Anki-Android#15050]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Enable new backend and v3 scheduler in settings
2. Start reviewing and bury a card or two
3. Go back to the deck list view
4. Long press the deck with buried cards

### Expected behaviour

There is Unbury item available to unbury the buried cards.

### Actual behaviour

There is no Unbury button in the menu.

### Debug info

```text
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = Sony

Model = XQ-CT72

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; XQ-CT72 Build/64.1.A.0.996; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = a43fd0a2-35f4-42e9-a9b1-fca3f77f8102

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### (Optional) Anything else you want to share?

If I switch off v3 scheduler, the Unbury button shows again.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Confirmed - in 2.16.x with old scheduler I see unbury added to the deck long-press menu if a card is buried in a deck, in 2.17alphaX I do not see it.

**Comment by david-allison** [comment]
Triage:

* We use `haveBuriedInCurrentDeck`

https://github.com/ankidroid/Anki-Android/blob/041f9d113ecf5046b2575ca6e72498c497a8422e/AnkiDroid/src/main/java/com/ichi2/anki/StudyOptionsFragment.kt#L340

But the selected deck is not changed when long pressing a deck

**Comment by david-allison** [comment]
@upsuper Thank you so much for the report. Submitted a fix, and this should be resolved in the next alpha
