### ISSUE TITLE
[Bug] Switching themes while syncing

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#15069]
###### Reproduction Steps

1. Start a full sync
2. Switch to dark mode or light mode

###### Actual Result

![Screenshot_20231224-080612.png](https://github.com/ankidroid/Anki-Android/assets/357361/00dd133d-3ae8-47ba-8ba6-609d3255fb11)

###### Expected result

In an ideal world, we would want the UI to become dark/light while the full sync still goes on.
I don't think that's possible. Instead of recreating the UI, it would mean updating all components. The amount of work would not be reasonable for this kind of task.

Full sync is potentially a very expensive operation. It requires to sync a lot of data, so can cost a lot of money, can drain the battery. So we should avoid cancelling it. So the priority is to avoid interrupting the sync. If it means that we don't change the UI and stay in light/dark mode, so be it. At least until the sync is done. Once the sync is done, please be sure to refresh the UI.

I don't actually know if it's possible to catch the refresh of the UI and cancel it. If it's not possible, then we need to at least ensure that when the UI is recreated, a new sync is started instead of showing this error. Please try to ensure that sync is really restarted, don't silently cancel it. The user should know that, unless there is an error message, they can assume the sync was done correctly. So just removing this error message without showing anything instead would be worse than the current situation.

If for some reason you can't even restart the sync (I doubt that's realistically a concern), at least show a message that can be understood by users.

Now, what does it means to "restart the sync". In an ideal world, you would remember whether it was a normal sync, a full upload or a full download, and directly restart this particular kind of sync. If it's too hard, and a full sync is needed, don't hesitate to ask the user whether they want to upload or download. That is, you can juste reuse the method that the automated sync use. This bug is probably rare enough that having the user repeat their choice is an acceptable cost.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.17alpha13 (51186fdee0409d4605145fff77bfd284af0a7d36)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 8 Pro

Hardware = husky

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro Build/UD1A.231105.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = 47035a3d-ff8b-4423-8485-1d6d82d48957

Crash Reports Enabled = true

**Comment by Siddheshjondhale** [comment]
I understood the issue.

Can I try to fix it if no one else is currently working on it?

**Comment by Arthur-Milchior** [comment]
Hi @Siddheshjondhale,

Nice to meet you. I don't think we met before.
Yes, you can.
Generally speaking, you don't need to ask for permission. Just put a word to let us know, and update us if you found something, if you abandon, or if you have any question. 

I should just warn you, that does not seems trivial. I currently have NO idea how I'd solve it myself.
I'm not even sure what's possible.

I'm updating the bug description to add a few notes

**Comment by david-allison** [comment]
@Arthur-Milchior I believe this would be resoled by using a ViewModel, as this persists across configuration changes

**Comment by Siddheshjondhale** [comment]
Hi @Arthur-Milchior Nice to meet you as well. Yes, I’m new here.

I tried to reproduce the issue on the main branch, but I was unable to reproduce it with the given steps. Could you provide more details on how to reproduce the issue?

**Comment by Arthur-Milchior** [comment]
Would you mind recording your screen and sharing it please?

**Comment by Arthur-Milchior** [comment]
I can't reproduce either. It seems someone already fixed it. Thank you a lot for looking into it and to whoever fixed it!
