### ISSUE TITLE
Split immersive mode from hiding the reviewer's toolbar

### ISSUE THREAD

**Issue by vgf89** [ankidroid/Anki-Android#15070]
**Is your feature request related to a problem? Please describe.**

Making more complex card templates which include the answer buttons (as described here: https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#againhardgoodeasy) makes the built-in answer buttons redundant. However, the only way to hide the buttons is to go into fullscreen mode. The current fullscreen mode options are "Off", "Hide system bars", and "Hide system bars and answer buttons". Both of the on options also hide the ankidroid app bar. Needing to hide the system bars and app bar just to hide the native answer buttons is inconvenient as I would prefer the system bars and app bar to still be visible while studying.

**Describe the solution you'd like**

The Fullscreen mode options should be separated from the hide answer buttons option, and the app bar (the one with back, undo, overflow, etc) should probably also have its own visibility option. Ideally, Fullscreen should be a toggle, hide answer buttons should be a toggle, and possibly hide app bar should be a toggle in the ankidroid settings.

Additionally, this would allow gesture or external button users to hide the redundant answer buttons that they don't need without making them go into fullscreen mode.

**Describe alternatives you've considered**

I could implement a custom top bar in my card template which includes an undo button and other features I need (as shown in an example at the bottom of the javascript api page), but my system bars would still be hidden which is undesirable. For now, I've settled on decreasing the native answer button size to the minimum option (10%) using the accessibility settings, and the answer buttons from my card template get rendered just above them, without using fullscreen mode at all. This is an ok workaround, but it feels janky imo.

**Additional context**

Ultimately, my goal is to replace the four answer buttons with just two (Again and Good) since FSRS tends to perform slightly better with just those two buttons (according to the FSRS Tutorial FAQ and the "ask me about fsrs" guy on reddit), plus the extra mental load of rating card difficulty and potentially cheating based on intervals wastes time for me. I first modified the app to add an option to hide the hard and easy buttons, whick worked, but was informed on Discord that this wouldn't be accepted as a PR due to the divergence from Anki Desktop. I was told to use the ankidroid javascript API in a card template to render my own buttons (which I have now done) and use fullscreen mode to hide the native buttons. That gets me very close to what I want, but the side effects of the current fullscreen mode options are bothersome, and shrinking the native buttons as a workaround feels silly.

**Comment by BrayanDSO** [comment]
FWIW, you can hide the answer buttons with `Answer buttons position > None`

**Comment by vgf89** [comment]
I suppose that actually fixes my use case. Don't know how I missed it!

**Comment by david-allison** [comment]
Doesn't seem needed any more, let me know if I'm mistaken
