### ISSUE TITLE
[BUG]: Browser shows cards from all decks, not only those from selected deck

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15072]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- On the decks page, select a deck.
- Open the Card Browser.
- Press the back button to return to the Decks page.
- Reopen the Card Browser.

### Expected behaviour

The browser shows the cards only from the selected deck.

### Actual behaviour

The browser shows cards from all decks. However, it still shows the name of the selected deck at the top.

Note that the behaviour is correct when first opening the browser after selecting the deck, but not in the subsequent attempts.

### Debug info

```text
2.17 alpha 13

Issue persists in alpha 14
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report!

Doing a lot of work behind the scenes for the CardBrowser so we can improve the UI/UX, I'm trying for this to have as minimal negative impact as possible, but this one slipped through the net. Truly appreciate the time!

**Comment by user1823** [comment]
Not fixed in alpha 15

**Comment by user1823** [comment]
Two new findings:
- When the browser is incorrectly showing cards from all decks and I minimize and then reopen the app, the Browser refreshes and shows the cards from the selected deck only.
- The browser doesn't follow the Sort order when the deck is selected on the Decks page but it follows the Sort order when the deck is selected from the Browser itself. The Sort order is also correct when the app is reopened (while reproducing the previous finding).

**Comment by user1823** [comment]
@david-allison, I realise that this is volunteer work. But, this issue is quite annoying and causes loss of productivity. So, I hope that this is fixed soon.

**Comment by user1823** [comment]
Almost fixed in alpha 16, thanks!.

The only remaining issue:
When opening the browser, the cards from all decks flash on the screen for a fraction of a second before the cards of the selected deck are shown.

**Comment by user1823** [comment]
@david-allison, please reopen this because it is not completely fixed.

However, the remaining issue is not much of a problem. So, you can work on it later when you are not so busy.

Thanks for the time and effort you devote to AnkiDroid!

**Comment by david-allison** [comment]
Thanks for the ping, missed your previous message

**Comment by user1823** [comment]
Completely fixed in alpha 17. Thanks!
