### ISSUE TITLE
Update to Anki 23.12 backend

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15083]
The Anki update includes some significant changes to the FSRS algorithm. So, for best results, all reviews should be done on apps with the same codebase.

(There are no "breaking" changes, but still ...)

Now that the 23.12 release is public, the backend code of AnkiDroid should be updated as soon as possible.

**Comment by mikehardy** [comment]
I/we get notifications for anki releases, we are aware of them for what it's worth

**Comment by user1823** [comment]
I was almost certain that you guys get notifications for the releases, but I still created this issue because the 23.12 update changes the scheduler code, which means that doing reviews on apps with different backend versions can lead to some unwanted behaviour. So, quickly updating to this version is somewhat more important.

After this release, for several months, there are no expected changes to the FSRS scheduler code. So, I would not urge for a very rapid update to the new backend version for those releases.

**Comment by szalejot** [comment]
Also, 23.12 introduced some important fixes. From release notes:

- When cards are rescheduled multiple times without reviews, extra entries will not be added to the review log.
- Fix some bugs in sorting by FSRS retrievability.
- Recompute FSRS memory state when cards moved into different deck.
- Added a new v3 option to limit child decks by their parent, when clicking on the child.
- Fix filtered deck ordering of intraday learning cards and reviews
- Fix relative overdueness order error in filtered deck.

**Comment by dae** [comment]
The new backend can't be simply dropped in. Some changes will need to be made to AnkiDroid:

- The filtered deck screen will need to support customizing the separate preview delays for again/hard & good buttons
- The auto advance feature will need to switch to using the settings in the current card's deck options

**Comment by user1823** [comment]
> The new backend can't be simply dropped in.

Yes, I agree. All that I have to say is this update should take a slightly higher priority than normal.

**Comment by dae** [comment]
Another issue I didn't mention above: Anki displays various options when importing an .apkg file, which AnkiDroid is currently not doing. As a temporary workaround to get things to compile when switching to the 23.12 backend, you can hard-code the argument change:

```diff
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
index 07ec516536..bb272bd17b 100644
--- a/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
+++ b/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
@@ -17,6 +17,7 @@
 package com.ichi2.libanki

 import anki.import_export.ExportLimit
+import anki.import_export.exportAnkiPackageOptions
 import anki.search.SearchNode
 import net.ankiweb.rsdroid.Backend

@@ -107,7 +108,13 @@ fun Collection.exportAnkiPackage(
     limit: ExportLimit,
     legacy: Boolean = true
 ) {
-    backend.exportAnkiPackage(outPath, withScheduling, withMedia, legacy, limit)
+    val options = exportAnkiPackageOptions {
+        this.withScheduling = withScheduling
+        this.withMedia = withMedia
+        this.legacy = legacy
+        this.withDeckConfigs = true
+    }
+    backend.exportAnkiPackage(outPath, options, limit)
 }

 fun Collection.getCsvMetadataRaw(input: ByteArray): ByteArray {
diff --git a/build.gradle b/build.gradle
index aeafc762f8..2057d8a32f 100644
--- a/build.gradle
+++ b/build.gradle
@@ -9,7 +9,7 @@ buildscript {
     ext.kotlin_version = '1.9.21'
     ext.lint_version = '31.1.1'
     ext.acra_version = '5.11.3'
-    ext.ankidroid_backend_version = '0.1.32-anki23.10.1'
+    ext.ankidroid_backend_version = '0.1.34-anki23.12'
     ext.hamcrest_version = '2.2'
     ext.junit_version = '5.10.1'
     ext.coroutines_version = '1.7.3'
```

A proper fix will mean using the import-anki-package.html page. Currently, for some unknown reason, it is not being included in the backend builds, and it could use the help of someone knowledgeable in Gradle to debug.

https://github.com/ankidroid/Anki-Android-Backend/pull/339

**Comment by mikehardy** [comment]
Needs the "load pages from `assets`" patch here: https://github.com/ankidroid/Anki-Android-Backend/pull/339#issuecomment-1873922668

...with the small tweak that the pages are in `assets/backend` (i.e., that `backend` subdirectory...) in the final version
