### ISSUE TITLE
Show a Preview in CardBrowser if Card contains Image, Video, Audio

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#15096]
**Is your feature request related to a problem? Please describe.**
If card contains Image or Video then in CardBrowser, it shows empty
But if card contains audio file then it shows something like this `[anki:play:a:0]`

**Describe the solution you'd like**
Show a preview to let the user know what actually a card contains. 

**Describe alternatives you've considered**

**Additional context**
![WhatsApp Image 2023-12-28 at 1 21 43 PM](https://github.com/ankidroid/Anki-Android/assets/65113071/cd2e8c26-15f6-476b-b70a-ca6415d3de61)

**Comment by gourabsingha1** [comment]
I wanna work on this

**Comment by david-allison** [comment]
@gourabsingha1 There's a lot of work going on in this area, and it's likely to be a difficult one to resolve quickly
