### ISSUE TITLE
New card settings [Bug]

### ISSUE THREAD

**Issue by 999Addy999** [ankidroid/Anki-Android#15092]
###### Reproduction Steps

1. Unable to set new card limits for individual Decks
2. 
3. 

###### Expected Result

New card settings for individual decks 

###### Actual Result

Card limits finishing after 1 use

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, thanks for the report. Please post your debug information
