### ISSUE TITLE
[Bug] Initial file access Screen Don't allow to Toggle Off

### ISSUE THREAD

**Issue by Sagar0-0** [ankidroid/Anki-Android#15090]
###### Reproduction Steps

1. Go to Initial File access Screen which contains A switch 
2. Allow the permission and the switch will be on.
3. Try to turn it off, it won't.

###### Expected Result
It should turn off or navigate to the same system settings page.

###### Actual Result
It is not doing anything

https://github.com/ankidroid/Anki-Android/assets/85388413/24911c39-654a-4410-a9a4-6c91e689f50a

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.17alpha14-debug (f034ae348e0f993392e91875d4ad094341f570ea)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3371

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3371 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = cddde5e0-617c-4fbe-8864-951ba7e89322

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pratyaksh1610** [comment]
Working on it.

**Comment by Sagar0-0** [comment]
Let the maintainers reproduce it first, then assign it. I want to work on this, btw thanks for your interest.

**Comment by BrayanDSO** [comment]
This behavior is intended. The permission is mandatory to using the app, so it doesn't make sense to allow removing it

**Comment by Sagar0-0** [comment]
I know this permission is mandatory, but showing a toggle button which do not allow us to toggle, doesn't make sense. Either it should be something else button or we should show a message when user try to switch it off. That's the user expected behaviour to improve this functionality.
