### ISSUE TITLE
[BUG]: Unnecessary "next" card option in CardTemplatePreviewer

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15093]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Open a note created using the `Basic (optional reversed card)` notetype in the Note Editor. The note should not have a reversed card.
- Open the preview of the card.

### Expected behaviour

The forward card is seen in the preview and there are no `>` (next) or `<` (previous) options associated with the `Show/Hide answer` button.

<img width=400 src="https://github.com/ankidroid/Anki-Android/assets/92206575/c2e34f2e-a537-4754-911b-ae57dc82217b">

(Screenshot from the preview of a card created using the `Basic` notetype)

### Actual behaviour

The `Show/Hide answer` button shows `>` (next) or `<` (previous) options.

<img width=400 src="https://github.com/ankidroid/Anki-Android/assets/92206575/507c407c-5272-43a5-a32d-91cb7f41450e">

On clicking the `>` button, it shows:

<img width=400 src="https://github.com/ankidroid/Anki-Android/assets/92206575/9ca43dc0-f6d5-41c9-8652-5ac3435c9b56">

On the Desktop version, clicking the next button shows the next card (from the next note). It makes sense because the note editor and the browser are inseparable there.

However, in AnkiDroid, I think that it makes more sense to hide the button when there is no reverse card associated with the note.

### Debug info

```text
2.17 alpha 14
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
When the note actually has a reverse card and the user is previewing the reverse card (by first selecting the reverse card in the browser), then clicking the next button doesn't do anything.

In this case, either
- the next button should be disabled and the previous button be enabled instead; or
- clicking the next button should display the forward card.

**Comment by soCallmeAdityaKumar** [comment]
I am working on it!!

**Comment by BrayanDSO** [comment]
I thought about this for a while, and I believe that this can't be applied to the general scenario. There are people that will want to explicitly see that a card couldn't be generated, specially when there are many templates in the same notetype.

**Comment by user1823** [comment]
> There are people that will want to explicitly see that a card couldn't be generated

This makes sense. But, [my second observation](https://github.com/ankidroid/Anki-Android/issues/15093#issuecomment-1870827701) is definitely unexpected and should be resolved.

**Comment by BrayanDSO** [comment]
#15554 solves that

**Comment by user1823** [comment]
In that case, I would be happy to get this issue closed when the new previewer is made the default one or there is atleast an option to enable the new previewer.

**Comment by david-allison** [comment]
@user1823 Tap on the AnkiDroid logo in the settings a few times and you can access the dev options in a 'production' build
