### ISSUE TITLE
在browser中添加快捷按键, 迅速进行卡片的切换. 

### ISSUE THREAD

**Issue by kcrimson1** [ankidroid/Anki-Android#15108]
您好: 
我设置了一些快捷键(音量键 切换卡片), 但这个仅在学习中有效. 

希望可以添加进browser的预览中, 

这可能是一个好的建议, 我没有在其他issue里找到它.

**Comment by david-allison** [comment]
Hi, thanks for the report. This is a duplicate of: https://github.com/ankidroid/Anki-Android/issues/12390

I started work on the linked pull request recently, it's on my long list of things to get around to
