### ISSUE TITLE
[Proposal] Remove `card.html`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15109]
> To look at the HTML as a file, open the card you want to inspect in the reviewer, and at the same time browse to /sdcard/AnkiDroid - you should see card.html. The file will be overwritten fresh every time a question or answer is displayed in the reviewer.
> 
> card.html can be copied to your PC for inspection. You should also consider copying the collection.media folder to help diagnose missing media errors

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#via-html-file

----

I don't use this feature, and don't believe any maintainers do (given that the WebView inspector is better, and Scoped Storage has made it much harder to access `card.html`).

I propose that we remove this feature. I'm adding this issue to see if I'm mistaken

**Comment by lukstbit** [comment]
Remove it, I didn't use it.

**Comment by BrayanDSO** [comment]
Remove it. I never used it
