### ISSUE TITLE
[Bug] Login Screen Password field UI issue

### ISSUE THREAD

**Issue by Sagar0-0** [ankidroid/Anki-Android#15118]
###### Reproduction Steps

1. Go to the Login Screen
2. Try to Login Without any password
3. We will see two overlapping icons at the end of password textfield.

###### Expected Result
They should not overlap or only one icon while showing an error.

###### Actual Result
Overlapping icons 
![Screenshot_2023_12_27_09_08_08_30_7b5228b5a93c00ecba98ecb0735c59e2](https://github.com/ankidroid/Anki-Android/assets/85388413/55f7fb4c-f3f5-4617-ab97-8d7edd0757a5)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.17alpha14-debug (f034ae348e0f993392e91875d4ad094341f570ea)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3371

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3371 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = cddde5e0-617c-4fbe-8864-951ba7e89322

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by neeldoshii** [comment]
@david-allison seems an easy fix can I work on this issue?

**Comment by Sagar0-0** [comment]
> @david-allison seems an easy fix can I work on this issue?

I'm working on it

**Comment by david-allison** [comment]
Let's give @Sagar0-0 the chance to work on it since they submitted it. Thanks for the enthusiasm!

**Comment by criticalAY** [comment]
I already took care of it in #15067 using the M3 methods sorry :)

**Comment by Sagar0-0** [comment]
> @david-allison @Sagar0-0 I already took care of it in #15067 using the M3 methods sorry :) I also made some logical changes there so took care of this too

I hate you😭

**Comment by Sagar0-0** [comment]
I'll wait for #15067 and then see if any fixes are required.

**Comment by mikehardy** [comment]
Believed closed with #15067
