### ISSUE TITLE
TTS: `speed=3` isn't working [Samsung TTS]

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15126]
Will there support for non-default speeds in the future? For example, I have `{{tts en_US speed=3:Front}}` but the AnkiDroid TTS is operating at normal speed. (This behavior is not due to my Android TTS settings, as that is sped up as well.) I'm using 2.17alpha14.

_Originally posted by @lindayqlin in https://github.com/ankidroid/Anki-Android/issues/14358#issuecomment-1873593977_

**Comment by david-allison** [comment]
* Can't reproduce on an API 33 emulator
* Testing on my S21 (Android 14)

**Comment by lindayqlin** [comment]
Thanks for looking into this David! I'm using Samsung TTS v3.3.04.15 (on Galaxy S10e / Android 12). Here's the debug info:

AnkiDroid Version = 2.17alpha14 (0717daab11cd9669997aea6a421ec94689120cb6)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 12 (SDK 31)

ProductFlavor = full

Manufacturer = samsung

Model = SM-G970U1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970U1 Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Mobile Safari/537.36

ACRA UUID = 00f4b43f-add9-4bcb-8492-ec54715db8ed

Crash Reports Enabled = false

Thanks in advance for your help!

**Comment by david-allison** [comment]
@lindayqlin If you could provide a sample export of a failing card/deck, it would be ideal.

With apologies, I'm going to mark this one as https://github.com/ankidroid/Anki-Android/labels/Can%27t%20reproduce and see if another developer/maintainer can reproduce this.

In addition to the above, I've downloaded an API 31 emulator and this is working as expected. Relevant code below is simple and /should/ work.

https://github.com/ankidroid/Anki-Android/blob/13b9f9c80c5d10c73af83bbe62f2534c14a057b6/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt#L114-L121

**Comment by lindayqlin** [comment]
Thanks for the suggestions! This is strange, as upgrading Samsung TTS to v3.5.00.67 didn't work either, but switching to Google TTS did. Apologies that I didn't think to try that earlier before commenting here. I'm not sure why there'd be a difference between the two, but I suppose for my purposes this issue is resolved. Thank you so much for your help!

**Comment by david-allison** [comment]
That's frustrating - works fine on my S21, so I can't reproduce it.

Regardless, glad this is resolved for you! 

I'll leave this open for a while, I don't know if this is an issue on the Samsung side [you said the preview in the TTS settings worked fine], but if it is a Samsung problem, we likely can't resolve it on our side.

**Comment by david-allison** [comment]
Closing as "can't reproduce", this feels like an external provider issue, given other providers work correctly
