### ISSUE TITLE
[Bug] Login Screen persistance issue

### ISSUE THREAD

**Issue by Sagar0-0** [ankidroid/Anki-Android#15125]
###### Reproduction Steps

1. GO to the app home screen without login
2. Navigate to login screen
3. Click phone home button
4. Open the app again
5. We are at the home now not at login

###### Expected Result
We should be at login screen

###### Actual Result
Login screen is not persisting in app start

https://github.com/ankidroid/Anki-Android/assets/85388413/71b37043-70c1-444e-96d3-d9b61043ed56

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.17alpha14-debug (f034ae348e0f993392e91875d4ad094341f570ea)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3371

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3371 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = cddde5e0-617c-4fbe-8864-951ba7e89322

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Sagar0-0** [comment]
I'll work on it

**Comment by Sagar0-0** [comment]
Is it reproduced by anyone else?

**Comment by Sagar0-0** [comment]
I have already gone through the code, it normally starts the activity and idk why I am not able to reproduce it now.

**Comment by david-allison** [comment]
Let's reopen this if it happens again

**Comment by Sagar0-0** [comment]
I have not tested it after new implementation there

**Comment by david-allison** [comment]
No, that's why I closed it. Let's reopen it if it's reproduced
