### ISSUE TITLE
Allow zooming in Anki pages

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15127]
In 2.17, zooming is currently not possible in the Stats page.

However, some elements are small and might only be clearly visible after zooming in. Also, the bars in the charts are so thin that it is very difficult to select the correct bar without zooming in.

So, I think that Stats page should have the ability to zoom.

**Comment by RobozinhoD** [comment]
I want to do this

**Comment by BrayanDSO** [comment]
I'm extending the issue to all the Anki pages (Card info, stats, deck options, etc). The difficulty should be the same

**Comment by neeldoshii** [comment]
Can I collaborate in this @RobozinhoD @BrayanDSO 

Can we do it like this

webview zoom and this will be called with two buttons (+/-)

**+** ---> indicates zoom in button
**-** --> indicates zoom out button

**Comment by user1823** [comment]
> webview zoom and this will be called with two buttons (+/-)

I don't think that buttons should be added. Zoom should work with the pinch gesture.

**Comment by david-allison** [comment]
I'd rather focus on making the screens more mobile-friendly. After this, we should ask if we need a zoom gesture.

There's hundreds of accessibility issues in the accessibility scanner currently, and we should be tackling the root causes rather than papering over the issues.

**Comment by user1823** [comment]
> I'd rather focus on making the screens more mobile-friendly.

I agree that the screen needs to be made more mobile-friendly. However, I think that adding the ability to zoom is a much easier thing to do, which would make the situation better, at least in the short-term.
