### ISSUE TITLE
[BUG]: TTS doesn't stop when next card is shown 

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#15133]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1) review a card where the anser is read out with TTS
2) Anser card to load the next card

### Expected behaviour

TTS stops, like in all Ankidroid versions before.

### Actual behaviour

TTS remains to read out the previous answer, even though the next question is shown. That's confusing.

### Debug info

```text
AnkiDroid Version = 2.17alpha14 (0717daab11cd9669997aea6a421ec94689120cb6)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = motorola

Model = moto g(60)s

Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g(60)s Build/S3RLS32.114-25-13; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Mobile Safari/537.36

ACRA UUID = 751875a7-f00b-41fe-90b1-2bcc6af0617f

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
* Fixed in  https://github.com/ankidroid/Anki-Android/pull/15110
