### ISSUE TITLE
[BUG]: ajouter une photo

### ISSUE THREAD

**Issue by 4malia4** [ankidroid/Anki-Android#15134]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

La fonctionnalité pour ajouter une photo n'apparait pas. Lorsque l'on crée une carte et qu'on ajoute une photo avec le trombone, celle ci n'apparait pas, il reste un écran noir. J'ai pourtant permis à Android l'accès aux photos. Mais lorsque je l'ajoute ca semble marcher et pourtant quand on va dans "aperçu" avant de créer la carte on se rend compte que la photo n'apparait pas.  Mon amie qui utilise l'application a le même problème. 

### Expected behaviour

On devrait avoir une image qui apparait lorsque l'on retourne la carte

### Actual behaviour

Ecran noir

### Debug info

```text
Version Ankidroid 2.16.5
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by gourabsingha1** [comment]
Hi @david-allison, I'd like to work on this. Assign this to me please.

**Comment by david-allison** [comment]
@gourabsingha1 It's best to ask @4malia4 to upgrade to 2.17.5 & get debug info before working on this

**Comment by gourabsingha1** [comment]
Okay

**Comment by gourabsingha1** [comment]
Salut @4malia4. Veuillez passer à la version 2.17.5 et me fournir les informations de débogage.
