### ISSUE TITLE
[BUG]: Setting Daily limit in deck options has no effect

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#15132]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1) long press a deck in the list
2) Deck options
3) Daily limits -> set Maximum reviews/day to 1000

### Expected behaviour

I can review up to 1000 cards

### Actual behaviour

The review limit is always 30 cards for my deck.

After finishing the 30 cards the following message is shown:

"Today's review limit has been reached, but there are still cards waiting to be reviewed. For optimum memory, consider increasing the daily limit in the options."

1) increasing the daily limit in deck options has no effect

2) the meaning of the sentence is unclear. Which "options" do you mean? The "deck options" or the "app settings"? In the German Ankidroid version both are called "Einstellungen", so it's not clear what you mean. App settings also has an option "learn ahead limit", but I think you mean "deck options -> Daily limits -> Maximum reviews/day

### Debug info

```text
AnkiDroid Version = 2.17alpha14 (0717daab11cd9669997aea6a421ec94689120cb6)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = motorola

Model = moto g(60)s

Hardware = mt6785

Webview User Agent = Mozilla/5.0 (Linux; Android 12; moto g(60)s Build/S3RLS32.114-25-13; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Mobile Safari/537.36

ACRA UUID = 751875a7-f00b-41fe-90b1-2bcc6af0617f

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Anthropos888** [comment]
![Screenshot_20240102-205612](https://github.com/ankidroid/Anki-Android/assets/45192213/b66b3230-b098-4257-b186-d89dbc26512d)

@david-allison here you are

**Comment by BrayanDSO** [comment]
odd. Things work alright here

**Comment by yayachiken** [comment]
Not the author, but I have the same issue and it seems to be related to the custom setting preset, which you can also see in the screenshot posted by the author.

I don't know how to craft a reproducer without risking to lose my decks, but essentially I did the following:

* Import multiple decks (in my case one for conjugations, one for vocabulary), all of them getting the global `Default` preset first. The global preset has a limit of 20 cards set in my case.
* Create a new preset for each deck, in my case named `Konjugationen` and `Vokabeln`.
* In preset `Konjugationen` set the new card limit to 0, this is used to implement a manual card release workflow.
* Do a manual study session in the deck using the "Konjugationen" preset to change the card limit for one day.
* No matter what you enter, you will have a hard limit of 20 cards. This means, for any number lower or equal 20, you get that number, but for example if you say `30` you will just receive 20 cards.

Now I set the preset back temporarily to the `Default` one, and changed the global `Default` preset to `9999` new cards and save.
Then change back to the individual `Konjugationen` preset and save again.
Now you can enter e.g. a limit of `30` and will receive 30 new cards as expected.

Not sure if it is relevant, but I found another issue where presets identification does not seem to work.
When optimizing FSRS values, while using a custom preset and the default filter (in my case `preset:"Vokabeln" -is:suspended`, the app does not seem to find any repetitions. It always shows "Error 500 Insufficient review history" even though my reviews are probably over 10000 already. When you use `deck:current`, it works fine.

**Comment by BrayanDSO** [comment]
Since that screen comes directly from Anki's code, I'll ask to request any enhancements in the Anki forums. If it's changed there, the change will be automatically consumed here
