### ISSUE TITLE
[BUG]: Note Editor/Android keyboard shortcuts: Shift+TAB cycles only until paperclip icon

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#15135]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

This requires a hardware or software keyboard (such as the "Hacker's Keyboard" app) with the TAB and Shift keys. Pressing TAB in the note editor will correctly cycle the keyboard's focus through:
1. Field content
2. Paperclip icon/menu
3. Collapse field button
After 3, TAB will bring the focus to the next field's content.

Shift + TAB is meant to cycle through items but in the opposite direction of TAB. In this case, it should bring focus to these items but in the order of 3, 2, 1. The problem is that the focus will get stuck on 2- the paperclip icon when cycling backwards with Shift + TAB. The regular TAB cycling is not affected by this.

### Expected behaviour

Pressing Shift + TAB when the paperclip icon is highlighted should bring the keyboard focus to the field before the paperclip menu.

### Actual behaviour

The focus gets stuck on the paperclip menu

### Debug info

```text
AnkiDroid Version = 2.17alpha14 (0717daab11cd9669997aea6a421ec94689120cb6)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = Google

Model = Pixel 2

Hardware = walleye

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 2 Build/RP1A.201005.004.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 8c1582d1-72a4-4960-9f06-b83c67f6c621

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by RobozinhoD** [comment]
I have a keyboard and can do this

**Comment by sudomain** [comment]
That was fast! Thanks
