### ISSUE TITLE
Get MathJax and jquery directly from the backend instead of copying it with a GitHub workflow

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15138]
In the pre backend era, Mani built a [GH workflow](https://github.com/ankidroid/Anki-Android/blob/f3ebb8c0c729c8c7242d09ae47192d75085b8a8a/.github/workflows/update_js_libs.yml) to get jQuery and Mathjax libraries from Anki's repository

Since we now can ship anything from there with the new backend, that seems like an easier approach and more future proof.

~~It's a very low priority issue since both MathJax and jQuery rarely updates and this is mostly a non functional change~~

**Comment by mikehardy** [comment]
Indeed I'm not sure that workflow will even work anymore and I fear those libs are pretty out of date
Script under the workflow is still using the old bazelisk build system from anki https://github.com/ankidroid/Anki-Android/blob/main/tools/update-js-libs.sh

> Since we now can ship anything from there with the new backend

@BrayanDSO what's the rough process to "ship" something ("expose", perhaps the correct verb?) from the backend to the front-end ?

Looks like it might be in the anki build web artifacts area, with a copy --> https://github.com/BrayanDSO/Anki-Android-Backend/blob/ea684c64e7e00b271af718376e983ce7d88814f3/build_rust/src/main.rs#L52

...then on the Anki-Android side, reference jquery and mathjax bundles from the copied location?

**Comment by BrayanDSO** [comment]
Yes, basically all of that. Check the directory that Anki stores those files, copy them with main.rs, then reference them in AnkiDroid.

If the file doesn't get embedded in the `aar` file, check if its name or the name of its parent directory is allowed as an Android asset (e.g. directories starting with `_` aren't embedded)

**Comment by mikehardy** [comment]
Perfect, thanks.  Alright, reasonable path forward here then, doesn't look *too* bad

**Comment by mikehardy** [comment]
Fixing this will hopefully resolve #17226

**Comment by MorenoTropical** [comment]
Leave it to me
