### ISSUE TITLE
Reinstate deck title as a preference

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15147]
Because of the reasons in #14918, the deck title were removed from the reviewer in #14931.

Since [Hyrum's law](https://www.hyrumslaw.com/) (mandatory [xkcd](https://xkcd.com/1172/)) is more certain than Newton's laws, some people are fairly resistant to the change.

While JS addons aren't implemented, so it's possible to implement something like that outside the app, it was discussed in Discord to get the feature back in order to avoid backslash so focus can be given to more important matters

Given the fact that we still want to remove the feature, in order to make people depend less on it, its default should be set to "false" in new installations, and to "true" in existing ones to avoid backslash

**Comment by BrayanDSO** [comment]
@RobozinhoD, since you were the author of #14931 and have been around recently, I wanted to run the issue through you to see if you are okay with that, since I don't like reverting people's work, and maybe see if you want to do this since you know the code

**Comment by david-allison** [comment]
Discussed on Discord. I'm strongly onboard with this

I feel we'll gradually want to move this to the JS API as an optional feature, rather than as a setting, but that will take time

**Comment by RobozinhoD** [comment]
I'm fine and I'll do it
