### ISSUE TITLE
[Dev]: Make formatter automatically break big lines to match the IDE behavior

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15143]
These were automated changes when I used the inline function in the IDE. 

I was going to revert the changes, but since this is a recurring problem, I wanted to raise an issue to make the formatter automatically do these changes, or use some kind of project shared setting

I can still revert them if asked

_Originally posted by @BrayanDSO in https://github.com/ankidroid/Anki-Android/pull/15140#discussion_r1440000819_

**Comment by david-allison** [comment]
I've been burned by this in the CardBrowser refactor, strong support

**Comment by RobozinhoD** [comment]
Hi, I want to fix this. My question is if the line limit should follow Android Studio default of 100 characters or ktlint default of 140 characters https://pinterest.github.io/ktlint/latest/rules/standard/#max-line-length

**Comment by BrayanDSO** [comment]
Overall I prefer `100` as well, but that will be a conflict hell, so it needs a quick merge

**Comment by mikehardy** [comment]
There are going to be so many PRs in flight here through the whole GSoC process and we're still stabilizing 2.17
This sounds like something to do after GSoC, personally. It feels like we're trying to make our lives difficult - even if this were fast it'll be a few days of extra effort when effort is already the limiter

**Comment by BrayanDSO** [comment]
So, make `140` the default for Android Studio so there aren't any changes to review, so the original issue is fixed.

After GSOC, change it to 100

**Comment by RobozinhoD** [comment]
Okay, I'll set the default to 140
