### ISSUE TITLE
Add In-App review API for flexible rating support

### ISSUE THREAD

**Issue by Sagar0-0** [ankidroid/Anki-Android#15153]
**Is your feature request related to a problem? Please describe.**
In some low-memory devices, it is harder to keep multiple apps running and active in the background and the rate functionality in our app navigates us to the Play Store app which may not be a good idea considering the above condition which can also kill our app in the worst case. 

**Describe the solution you'd like**
Google provides a clear and flexible solution for this, which is [Google Play In-App Reviews API](https://developer.android.com/guide/playcore/in-app-review), using which we can show a dialog to directly rate us in Play store.

**Describe alternatives you've considered**
This Google Play In-App Reviews API supports android API level 21 or more, it is the official and IMO best solution for this.

**Additional context**
Leaving to the playstore is also not a consistent flow idea and by using In-App review API we can give the user a connected experience with more control over the flow.

**Comment by david-allison** [comment]
Initial impression: I don't want this as a dependency

**Comment by BrayanDSO** [comment]
> Initial impression: I don't want this as a dependency

me neither. I'd like to stay as google-free as possible and this doesn't seem vital to have

**Comment by Sagar0-0** [comment]
Imo Native android isn't possible to be google-free.🥲 
Somehow Google will be always there.

**Comment by lukstbit** [comment]
> Somehow Google will be always there.

Google will always be there but there's no reason to directly invite it :)
I'm also against this, the functionality doesn't justify the added dependency(especially without analytics data).
