### ISSUE TITLE
[Bug] Alignment issue in Statistics UI

### ISSUE THREAD

**Issue by Sagar0-0** [ankidroid/Anki-Android#15152]
###### Reproduction Steps

1. Open drawer
2. GO to Stats UI
3. See unaligned UI

###### Expected Result
Items should be aligned

###### Actual Result
![photo_6078100583744649684_y (1)](https://github.com/ankidroid/Anki-Android/assets/85388413/62dbf602-f3a6-4172-9377-f4888c9335a4)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.17alpha14-debug (f034ae348e0f993392e91875d4ad094341f570ea)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3371

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3371 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = cddde5e0-617c-4fbe-8864-951ba7e89322

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
I'd wait to see if there are improvements coming in from https://github.com/ankidroid/Anki-Android/pull/15141 before taking this on

**Comment by Sagar0-0** [comment]
With what condition or criteria can I work on the core features and integration of features like this?

**Comment by david-allison** [comment]
Test after https://github.com/ankidroid/Anki-Android/pull/15141 is merged. If it's still an issue, fix it [upstream](https://github.com/ankitects/anki?search=1) and bring it in via the next Anki Desktop release

**Comment by BrayanDSO** [comment]
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#anki-desktop-pages may help

**Comment by BorisNA** [comment]
And could it be made back zoomable, please? It was in 2.16 and earlier 2.17 betas. 

That is, you could zoom statistics on phones to see all these small numbers (like review numbers in graphs etc). But no more now :(

**Comment by BrayanDSO** [comment]
Closing as upstream issue (should be fixed there)
