### ISSUE TITLE
[Bug] Buttons in Card template editor are not visible

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#15163]
###### Reproduction Steps

1. Edit a card template in a day theme.

###### Expected Result

All buttons are visible.

###### Actual Result

![Screenshot_20240105_105414_AnkiDroidA.png](https://github.com/ankidroid/Anki-Android/assets/10192661/a9bc37bf-6aca-40cc-bf76-3e7329ffbca7)

![Screenshot_20240105_110002_AnkiDroidB.png](https://github.com/ankidroid/Anki-Android/assets/10192661/ed350c8c-f8f3-4f0f-8b3e-23602cf46e92)

###### Debug info
AnkiDroid Version = 2.17alpha14 (0717daab11cd9669997aea6a421ec94689120cb6)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Mobile Safari/537.36

ACRA UUID = 292934a2-f5a2-4c26-bb9a-aad37fa84073

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
already fixed
