### ISSUE TITLE
AnkiDroid registers itself to open multiple "extra" file types

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15175]
If I click `Open With` in the File Manager after selecting a file, I often see AnkiDroid listed as one of the options.

For example, I can see it as an option to open `.zip` and `.log` files.

But, shouldn't AnkiDroid's "supported" file types be restricted to `.apkg`, `.colpkg`, `.csv`, `.tsv` and some others which I may not be remembering?

Also, interestingly, AnkiDroid is not shown as an option when opening `.csv` and `.tsv` files, but it should be there in order to easily import these files.

###### Debug info
```
2.17 alpha 15
Android 13
```

**Comment by david-allison** [comment]
* Related to https://github.com/ankidroid/Anki-Android/issues/8073

This was a work around for Gmail which hid the file extension, and an apkg was `application/zip`. I don't know whether this is still the case.

https://github.com/ankidroid/Anki-Android/blob/0ebccb5fbcd467cd80ecb8e7a29e6c68dbe5a1f8/AnkiDroid/src/main/AndroidManifest.xml#L176-L187

**Comment by david-allison** [comment]
* Closing in favour of: https://github.com/ankidroid/Anki-Android/issues/8073
