### ISSUE TITLE
[Bug]Whiteboard can't draw lines

### ISSUE THREAD

**Issue by xjqm-tao** [ankidroid/Anki-Android#15176]
###### Reproduction Steps

1. Open the whiteboard and draw lines.

###### Expected Result
There are lines

###### Actual Result
Only dots appear, no lines.

###### Debug info
AnkiDroid Version = 2.17alpha15 (e5b25f3fef737140ae396d1b212a8d638551500f)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = 22041216C

Hardware = mt6895

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 22041216C Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/104.0.5112.97 Mobile Safari/537.36

ACRA UUID = 13b991d9-a0fd-4ffc-8f8b-0b5c080f71cf

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Dr-Konda** [comment]
Even I'm facing same problem

**Comment by meliache** [comment]
I´m having the same issue with
```
AnkiDroid Version = 2.17alpha15 (e5b25f3fef737140ae396d1b212a8d638551500f)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = Google

Model = Pixel 7a

Hardware = lynx

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 7a Build/UQ1A.231205.015; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.145 Mobile Safari/537.36

ACRA UUID = daa8887c-3fb3-448c-921a-aab7d181bd8c

Crash Reports Enabled = true
```

**Comment by david-allison** [comment]
Cause: 1bb9883e54c132cd1dc3235f8932bbab56590236
