### ISSUE TITLE
[BUG]:  Image Occlusion not compatible between current desktop and mobile app

### ISSUE THREAD

**Issue by Hedaja** [ankidroid/Anki-Android#15171]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

It seems like the might be a compatibility issue with the newer desktop Version (23.12.1) and the current Android version (2.16.5)
When I create an image occlusion card on the desktop version and sync it to the Android version, I get the the message to ' check your Anki version' and 'ReferenceError: ank not defined' when I view the card. And the image is not occluded.

### Expected behaviour

Image occlusion works between desktop and mobile app.

### Actual behaviour

Android app throws a ReferenceError

### Debug info

```text
AnkiDroid version 2.16.5
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Image occlusion support was added in the 2.17 alphas. But thanks for the report
