### ISSUE TITLE
An option to fill both Front and Back of a card from the shared text (clipboard)

### ISSUE THREAD

**Issue by dvdvdmt** [ankidroid/Anki-Android#15189]
Hi, Anki Droid team! I love your app, use it every day and donate to its development.

I'm searching for a way to speed up cards creation from the shared text. I want to share a text from
another app and create a card with the Front and Back fields filled. This would speed up the process
of creating cards for the words I want to learn.

I want to create a small application that helps me to learn new words. I want to share a text from
it and create a card with the Front and Back fields filled. Here is an illustration of the process
that I would like to automate:

1. I select a specially formatted text or populate the System clipboard with it.
   <img src="https://github.com/ankidroid/Anki-Android/assets/8076700/47281ee6-7605-4022-bec4-e202a199d031" width="300">
2. I tap on the "Share" button or trigger this action programmatically.
   <img src="https://github.com/ankidroid/Anki-Android/assets/8076700/a3ce1ebc-38f9-4aac-ae3b-feeeabb51099" width="300">
3. (desired) I see the Anki Droid card creation dialog with the Front and Back fields filled.
   <img src="https://github.com/ankidroid/Anki-Android/assets/8076700/d4c5809f-89fa-4fd5-a6fa-771dbffe6c05" width="300">

However, now any copied text ends up in the Front field only.
<img src="https://github.com/ankidroid/Anki-Android/assets/8076700/ad257735-8d13-40b2-8c0f-509beff38e4d" width="300">

Here are my questions:

- Is it possible to create a card with the Front and Back fields filled from the shared text?
- If there is none such thing, can I participate in the development of this feature?

**Comment by criticalAY** [comment]
Sounds like a nice idea to me

**Comment by BrayanDSO** [comment]
If you are creating an application, you can use [AnkiDroid API](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API) for creating cards which should lead to better results.

As a feature itself, people will want a lot of different separators or conditions to share their texts, which is quite complex to implement from an UX and code perspective, and would increase the complaints about the app being hard to understand. 

Also, the maintainance burdance would be quite big, and this is a feature with a very small demand, so I'm not in favor to add this to the main app. If you really feel that everyone should benefit from this, you can always build a generic app with the AnkiDroid API that allows to create cards sharing text

**Comment by dvdvdmt** [comment]
Hi @BrayanDSO,

Thank you for your feedback and for pointing out the AnkiDroid API as a potential solution. While the API is indeed a powerful tool, the proposed feature aims to provide a simpler and more streamlined user experience, particularly for users who may not have the technical expertise to utilize the API or in cases where the API is not available like in Web applications.

The proposed feature can utilize the JSON embedded in plain text, a format that is widely used and supported in many programming languages. This format is simple, flexible, and easy to understand, even for users with minimal technical knowledge. It starts with a unique identifier, followed by a JSON object that contains the data for the card. For example:

```plaintext
anki-droid-card-v1@{"subject":"front text","text":"back text"}
```

When shared text is received by AnkiDroid, the app checks that it starts from the unique identifier. If the identifier `anki-droid-card-v1@` is found, the following text is parsed as a JSON object. The `subject` and `text` fields are then extracted from the JSON object and used to prefill the Front and Back fields of a new card.

In terms of maintenance, the proposed feature is relatively straightforward and should not impose a significant burden. The unique identifier can be used to distinguish this format from other potential formats, reducing the risk of conflicts or misunderstandings. Additionally, as the feature is based on standard JSON parsing, it should not require frequent updates or modifications.

While it's true that not all users may need or use this feature, for those who do, it could significantly speed up the process of creating cards from shared text, improving their overall user experience. As a developer, I am willing and able to contribute to the development of this feature, and I believe that it would be a valuable addition to AnkiDroid.

Thank you for considering this proposal.

**Comment by david-allison** [comment]
With apologies, this would be better suited with a small app which adds a system context/share menu and integrates with the AnkiDroid API. 

Making the feature discoverable would be difficult, and even with it, it targets a niche audience.

After we get addon support, we can revisit this and see if we can add an 'on share text' hook for the note editor, feel free to ping/reopen at this point
