### ISSUE TITLE
Small discrepancy in "cards due" between the main screen and study

### ISSUE THREAD

**Issue by zxcvxzcv-johndoe** [ankidroid/Anki-Android#15186]
Hello,

I am not sure if this a bug or just my misunderstanding on something, but I have noticed that Ankidroid shows a bit different amounts for "cards due" in the main screen and the study. This happens in the latest alpha builds 2.17alpha14  and 2.17alpha15.

For example here it shows 145 cards due, 20 of them are new.
![anki_1](https://github.com/ankidroid/Anki-Android/assets/124170934/effe6bc3-062e-4c89-b0dd-751e84713e75)

When I click to study the total amount drops to 141.
![anki_2](https://github.com/ankidroid/Anki-Android/assets/124170934/36df481c-49b1-4ceb-acde-f4de10cc2a7a)

I have 20 new cards limit and 200 review cards limit, and after completing today's cards it only says that I have more new cards I could study but it will take longer time etc. but there's nothing about the review cards (? green ones)

Here's my settings, I started thinking would it be possible that those 3x sibling settings could cause the difference?

![anki_settings](https://github.com/ankidroid/Anki-Android/assets/124170934/db293975-a130-4ecd-befa-45cc41114991)

I am using the alpha14, here's the debug info:

AnkiDroid Version = 2.17alpha14 (0717daab11cd9669997aea6a421ec94689120cb6)
Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)
Android Version = 13 (SDK 33)
ProductFlavor = full
Manufacturer = OnePlus
Model = KB2003
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 13; KB2003 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Mobile Safari/537.36
ACRA UUID = 66ee9faa-7f83-4666-b9ae-121482db2d6a
Crash Reports Enabled = true

EDIT: This also happens in alpha15, here are the details:

AnkiDroid Version = 2.17alpha15 (e5b25f3fef737140ae396d1b212a8d638551500f)
Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)
Android Version = 13 (SDK 33)
ProductFlavor = full
Manufacturer = OnePlus
Model = KB2003
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 13; KB2003 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.144 Mobile Safari/537.36
ACRA UUID = 66ee9faa-7f83-4666-b9ae-121482db2d6a
Crash Reports Enabled = true

**Comment by david-allison** [comment]
Hi @zxcvxzcv-johndoe, thanks for the report.

Could you edit your main post to include Debug Information and ensure you're on the latest alpha

* Settings - About - Copy Debug Info

Thanks again!

**Comment by zxcvxzcv-johndoe** [comment]
> Hi @zxcvxzcv-johndoe, thanks for the report.
> 
> Could you edit your main post to include Debug Information and ensure you're on the latest alpha
> 
>     * Settings - About - Copy Debug Info
> 
> 
> Thanks again!

Sorry :D I do IT for living, I have no idea how I failed adding that to the post. I have edited the post and it contains the debug details now.

**Comment by zxcvxzcv-johndoe** [comment]
> Hi @zxcvxzcv-johndoe, thanks for the report.
> 
> Could you edit your main post to include Debug Information and ensure you're on the latest alpha
> 
>     * Settings - About - Copy Debug Info
> 
> 
> Thanks again!

Hello, edited the main post to include the debug details and that happens in both 2.17alpha14 and  2.17alpha15

**Comment by eginhard** [comment]
Yes, the difference is due to sibling burying and Anki Desktop shows the same difference, so this is expected.

Anki Desktop further shows the number of buried cards in the study overview screen (https://docs.ankiweb.net/studying.html?highlight=sibling#study-overview). This could also be done in AnkiDroid to make this clearer.

**Comment by lukstbit** [comment]
This should be fixed by #16947 for 2.19. If it's still an issue on 2.19 please ping to reopen this.
