### ISSUE TITLE
[Bug] ReferenceError appears on Image occlusion cards on ankidroid 

### ISSUE THREAD

**Issue by 4amtrain** [ankidroid/Anki-Android#15188]
###### Reproduction Steps

1. image occlusion card made on desktop anki version 23.10.1 and sync'd to ankiweb
2. sync'd on ankidroid and review deck selected
3. When image occlusion card appears, nothing is hidden in the image and on top, it asks if the anki version is up to date and Reference error: anki is not defined 

###### Expected Result
card image should appear with the answer hidden

###### Actual Result

answer in image not hidden

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x![] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Screenshot_20240108_184935_AnkiDroid (1)](https://github.com/ankidroid/Anki-Android/assets/156033387/e73fddc7-c360-47be-a76d-bd0440d9350d)
 
![Screenshot_20240108_184935_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/156033387/c0352188-d9bc-4cea-ae1e-3a88849fc9fe)

**Comment by david-allison** [comment]
Hi, this should be fixed in 2.17, what version are you using?

**Comment by BrayanDSO** [comment]
ETA in the deck picker was removed in the 2.17 alphas, so this is a 2.16.5 app.

@4amtrain, this should be fixed in the latest alpha version, which you can download [here](https://github.com/ankidroid/Anki-Android/releases).

Please comment again if that wasn't able to fix your isse
