### ISSUE TITLE
allow setting a maximum number of unrecognized cards that can be in the pool of cards to show.

### ISSUE THREAD

**Issue by lolbinarycat** [ankidroid/Anki-Android#15194]
**Is your feature request related to a problem? Please describe.**
i often struggled using anki, as i would get questions wrong (either from brand new cards or from cards i had forgotten), but then the app kept showing me even more new cards, and would only repeat cards once i had forgotten their answer.

**Describe the solution you'd like**
within a study session, there would be a counter.

this counter is incremented every time the user is shown a card they have not yet seen today.

whenever a card is "completed" (when it will only be shown again tomorrow or later), the counter is decremented.

when the counter is at the user-defined max, only cards that the user has previously seen today will be shown. 

**Describe alternatives you've considered**
one workaround is to split the study session into smaller units, but this creates a weird jagged difficulty cuvre.

**Comment by BrayanDSO** [comment]
Hello there. This looks like something that should be consistent among Anki desktop and AnkiDroid, so the flow is to ask there first and if it is implemented there, we will do it here as well.

But thanks for the report
