### ISSUE TITLE
[Bug] Inconsistent Color for Selected Tags

### ISSUE THREAD

**Issue by Sagar0-0** [ankidroid/Anki-Android#15196]
###### Reproduction Steps

1. Create a card
2. Select some tags
3. Try selecting and unselecting multiple times and Opening and closing the other cards hierarchy.

###### Expected Result
Should have the same selected tag button color

###### Actual Result
Sometimes, the gray color for the selected card
![photo_6123000524044350846_y](https://github.com/ankidroid/Anki-Android/assets/85388413/0d3cb228-8fc3-4273-b511-86a31c06fa0c)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.17alpha14-debug (f034ae348e0f993392e91875d4ad094341f570ea)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3371

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3371 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = cddde5e0-617c-4fbe-8864-951ba7e89322

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Sagar0-0** [comment]
Let me work on this for god's sake

**Comment by Sagar0-0** [comment]
Let me learn something 😭

**Comment by BrayanDSO** [comment]
Go for it

**Comment by Sagar0-0** [comment]
@user1823 If possible, can you also share the log messages?

**Comment by user1823** [comment]
Can you tell me how to do it? Also, I am not a dev. So, I would be able to do it only if it doesn't involve going to the command-line, etc.

**Comment by Sagar0-0** [comment]
If you're not a dev, then you don't need to share it.
Thank you for reporting the issue.

**Comment by Sagar0-0** [comment]
I have gone through all the related files, Adapter, and XML, but couldn't find the logic that leads to this inconsistency. Any ideas of what might be happening with the Checkbox state change cycle and color-related issue?

**Comment by Sagar0-0** [comment]
I might need some help in analysing what exactly is causing the issue

**Comment by neeldoshii** [comment]
@Sagar0-0 

Can you tell me how to reproduce this? I want to test it?

I am converting the tagDialog to alertDialog in #15398 this will probably fix this as the theming of alert dialog has been fixed recently.

**Comment by david-allison** [comment]
Reproduction Steps:

* Edit a note with a selected tag in the Browser
* Tap the checkbox to remove the tag
* Tap outside the checkbox to add the tag

**Comment by leobugeja** [comment]
Hello could I get assigned to this?

**Comment by david-allison** [comment]
Done, cheers!
