### ISSUE TITLE
[Bug] Ripple Alignment Issue in Tags Window

### ISSUE THREAD

**Issue by Sagar0-0** [ankidroid/Anki-Android#15205]
###### Reproduction Steps

1. Create a new card
2. Open tags window
3. Select or unselect a tag
4. See the alignment issue in the Tag checkbox

###### Expected Result
The ripple should cover the complete checkbox

###### Actual Result
It ripples outside of checkbox
![photo_6125112514082617193_y](https://github.com/ankidroid/Anki-Android/assets/85388413/60f3f0b8-a44a-4876-9cdd-128af70e1feb)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.17alpha14-debug (f034ae348e0f993392e91875d4ad094341f570ea)

Backend Version = 0.1.32-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3371

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3371 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = cddde5e0-617c-4fbe-8864-951ba7e89322

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Sagar0-0** [comment]
I will check to see if it can be resolved or not, and can/should I push it along with #15196, as they are related to the same functionality?

**Comment by BrayanDSO** [comment]
> can/should I push it along with https://github.com/ankidroid/Anki-Android/issues/15196, as they are related to the same functionality?

yeah, that's fine

**Comment by Sagar0-0** [comment]
I went through the code but can't find the actual gap, let me know if this is fixed.

**Comment by SanjaySargam** [comment]
Still reproducible. Not fixed.
![Screenshot_2024-04-11-10-17-22-63_7b5228b5a93c00ecba98ecb0735c59e2.jpg](https://github.com/ankidroid/Anki-Android/assets/65113071/93ffea29-90eb-476d-b8ed-83390e844acf)

**Comment by david-allison** [comment]
Cause: 

https://github.com/ankidroid/Anki-Android/blob/0c7a40021f5a02678760343ef5531c3c5e54f0c8/AnkiDroid/src/main/res/drawable/ic_baseline_check_box_outline_blank_24_inset.xml#L1-L4

The insets don't play well with the background

**Comment by david-allison** [comment]
In our fix, the OK button is no longer aligned with the checkboxes
