### ISSUE TITLE
Media sync does not check for pre-existing media

### ISSUE THREAD

**Issue by LgBattery** [ankidroid/Anki-Android#15216]
###### Reproduction Steps

1.  Make a large deck on PC Anki (few thousand cards with audio media files)
2. Upload to Ankindroid via USB through .apkg format because syncing anything over 1gb~ through internet is a 24 hour+ process on Ankidroid.
3. Add a few KB worth of audio media files to the PC Anki deck
4. Sync in Ankidroid

###### Expected Result

Ankdroid downloads a few KB worth of audio files

###### Actual Result

Ankidroid attempts to re-download all media for the entire deck, it never finishes (even if I let it sync overnight) and will get up to ~200mb downloaded before crashing.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 14

ProductFlavor = play

Manufacturer = Google

Model = Pixel 5a

Hardware = barbet

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 5a Build/UQ1A.231205.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.210 Mobile Safari/537.36

ACRA UUID = f29afc44-a7ec-4802-8fb3-0ed0bc03778a

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, media sync has been completely rewritten for 2.17, could you check the alpha when you have a chance?

**Comment by LgBattery** [comment]
Alright just tried it, the checking took a minute or two but it worked great after that, only took around 3m in total, thank you so much this issue can be closed now.
