### ISSUE TITLE
[BUG]: Failed to create AnkiDroid directory

### ISSUE THREAD

**Issue by Volmarx** [ankidroid/Anki-Android#15220]
![Screenshot_2024-01-12-12-36-53-602](https://github.com/ankidroid/Anki-Android/assets/156474085/c042685e-8e5d-41e2-ad5a-86be9e4b6c54)
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Android 12
Lenovo Lenovo Tab M10 (3rd Gen), model TB328FU
MicroSD card formatted as internal storage
AnkiDroid v. 2.16.5 automatically installed on SD card

After installation of AnkiDroid with following attempt to open the app have got error message “Failed to create AnkiDroid directory” (see attached picture).
Apps automatically installed to SD card can't be moved to main storage (maybe Android issue

### Expected behaviour

Start the app

### Actual behaviour

After installation of AnkiDroid with following attempt to open the app have got error message “Failed to create AnkiDroid directory” (see attached picture).
Apps automatically installed to SD card can't be moved to main storage (maybe Android issue).

### Debug info

```text
AnkiDroid v. 2.16.5
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Volmarx** [comment]
![Screenshot_2024-01-12-12-36-53-602](https://github.com/ankidroid/Anki-Android/assets/156474085/7d6df060-dcfa-473d-ae59-d3432370df15)

**Comment by david-allison** [comment]
Strongly suspect that this is an Android issue, `/storage/emulated/0/Android/data/com.ichi2.anki` should be `getExternalFilesDir` which should be writable

https://developer.android.com/reference/android/content/Context#getExternalFilesDir(java.lang.String)

Let's see about diagnostics, but this probably isn't fixable without the hardware:

We can use ACRA to list storage directories on the phone, I had a search for apps for an end user which could do this, but came up blank

**Steps**
1. Provide your full debug info, Settings -> About -> Copy Debug Info
2. Help -> Get Help -> Send Troubleshooting Report

**Comment by Volmarx** [comment]
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 12

ProductFlavor = full

Manufacturer = Lenovo

Model = TB328FU

Hardware = ums512_1h10

Webview User Agent = Mozilla/5.0 (Linux; Android 12; TB328FU Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Safari/537.36

ACRA UUID = 6b94c518-6447-4564-be3e-d9966dead680

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment]
🤔 - thanks for supplying that information. A further question - we have 2.17 in beta now - you can ask the play store to deliver the beta builds to you like so: https://ankidroid.org/#betaTesting

We have done a lot of work in the 2.17 series in this area, perhaps 2.17beta will work for you ?

**Comment by david-allison** [comment]
@Volmarx did you submit a troubleshooting report? 

Can't see anything in ACRA for `6b94c518-6447-4564-be3e-d9966dead680`
