### ISSUE TITLE
Do not update notification if count has not changed

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1523]
Originally reported on Google Code with ID 620

```
Currently, the notification of due cards is updated even if the number of cards has
not changed.
We should store the last shown count and update it only if it has changed.
```

Reported by `flerda` on 2011-05-05 06:23:46

**Comment by wchristian** [comment]
Yes please, this is needed, since otherwise notifications relentlessly buzz again and again on every notification update, even when the app itself is open.

**Comment by mikehardy** [comment]
#4944 - related to notifications work I'm doing now - notifications should go away while the app is open, and when it closes they should maybe go back once but without vibration if the user didn't clear the counts.
