### ISSUE TITLE
Allow the DeckSpinnerSelection to be used in Stats Fragment

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#15247]
The deck spinner requires collection load function override for col  and AnkiActivity as parameter.
We only need the deck names for the stats fragment to allow the hack to allow the user to change the deck from the stats fragments itself so we need refactoring in DeckSpinnerSelection

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Blocked on #15248

**Comment by BrayanDSO** [comment]
I'm going to close this as part of #15197

**Comment by david-allison** [comment]
Sorry! I asked for this issue and missed the linked PR
