### ISSUE TITLE
large webm file 

### ISSUE THREAD

**Issue by eerenyuan** [ankidroid/Anki-Android#15243]
###### Reproduction Steps

1. have a webm file which is larger than 100Mb
2. use it in card like this:
```
"<video id="videoblock" controls width=640b> 
    <source id="video1" src="{{video}}.webm" name="name{{video}}"
            type="video/webm">								
</video>"
```

###### Expected Result

visible

###### Actual Result

error message. 
100Mb seems to be the magic number here. I have mutlipe webm files that are generated using the same ffmpeg command. 
`ffmpeg -f concat -safe 0 -i XXXfilelist.txt -c:v libvpx-vp9 -b:v 1M -c:a libopus XXX.webm`
The smaller files work ok (even with longer duration), but the larger ones don't. 

all files work ok in desktop version, so I guess the problem is ankidroid specific. 

###### Debug info
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 13

ProductFlavor = play

Manufacturer = Xiaomi

Model = 2211133C

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 2211133C Build/TKQ1.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.210 Mobile Safari/537.36

ACRA UUID = 3a6902bf-74e2-47b2-829d-d71e5a56efc1

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Have you checked if this applies to 100mb files with other extensions?

**Comment by eerenyuan** [comment]
good question, I tested this using both [sound] and <video> tag 

in ankidroid:
small.mp4 works in both case ----but [sound] doesn't provide a player control, is there a plan to add that?
large.mp4 doesn't work in either case.

in anki windows
both file show up in [sound], but not in <video>


```
<video id="videoblock" controls width=640b> 
    <source src="{{large.mp4}}" 
            type="video/mp4">								

</video>

<video id="videoblock" controls width=640b> 
    <source src="{{small.mp4}}" 
            type="video/mp4">								

</video>

[sound:{{large.mp4}}]
[sound:{{small.mp4}}]
```

**Comment by BrayanDSO** [comment]
> is there a plan to add that?

For audios, if Anki desktop adds it, we will add it as well. But for now the  goal is to keep things consistent

For videos, in 2.17, [sound] tags are now played as <video> tags (although fullscreen feature hasn't been implemented yet). You can try a parallel version at the releases page here in GitHub to check if it solves your problem without messing with your current installation

**Comment by eerenyuan** [comment]
tried "[AnkiDroid-2.17alpha15.parallel.A.apk]". 
[sound:xxx.webm] just gives me a play icon, even if I click the btn, there is no video shown. Is this a bug?

**Comment by BrayanDSO** [comment]
I just checked and webm is not among the video extensions we added to be migrated to `<video>`, but that should be simple to fix

**Comment by eerenyuan** [comment]
I used webm for testing only because I have more webm files. Actuall, mp4 is my preferred format. I converted all files to webm only because anki desktop's video tag doesn't handle mp4 correctly and ankidroid's [sound] doesn't show control---and I don't know how to create platform conditional card template. 

if ankiroid automatically converts [sound] to video tag, then I can use [sound.xxx.mp4] in the future and there should be no need to convert the files.

**Comment by eerenyuan** [comment]
by the way, do you have any idea why 100m files don't work in ankidroid? is that related to phone level settings.

**Comment by BrayanDSO** [comment]
my guess is something about file buffering in Android webviews. Currently the file is loaded directly. Maybe if the file is streamed progressively, like an internet video, it will work, which is something to do in our end

If that is really the casue, it likely will take time to fix this since it is relatively complicated to do that, and >100mb videos aren't common in Anki flashcards, so it's mostly up to anyone motivated enough to fix this.

**Comment by eerenyuan** [comment]
all my files are in the media folder, do you think this is also affected by the webview buffer? 
100mb is definitely on the large end for flashcard, if it's too much trouble to fix, I will try to make the files smaller or split into multiple pieces.

**Comment by eerenyuan** [comment]
I notice in ankidestop check media there is a message says file larger than 100mb cannot be synced to ankiweb. Probably that's the problem---I'm using self hosted server, but I guess it's also considered as ankiweb.

**Comment by eerenyuan** [comment]
confimed it's a sync issue---if I directly copy the files to media folder in phone, they work fine.
