### ISSUE TITLE
Different button icons for "Enable/Disable whiteboard" and "Show/Hide whiteboard"

### ISSUE THREAD

**Issue by mikemorr** [ankidroid/Anki-Android#15253]
Currently the buttons for "Enable/Disable whiteboard" and "Show/Hide whiteboard" use the same squiggle icon (see screenshot). It would be nice if their icons were distinct from each other.

![Screenshot_20240117-142507~2](https://github.com/ankidroid/Anki-Android/assets/2184268/d4ea4634-4f2e-4276-a24b-38f38dbf869b)

**Comment by Subhadiptech** [comment]
@david-allison Have attached a PR for the same. KIndly have a look.
