### ISSUE TITLE
Share image to add a new note with Image Occlusion

### ISSUE THREAD

**Issue by Frostedfox** [ankidroid/Anki-Android#15257]
**Is your feature request related to a problem? Please describe.**
Finding the image you want to add in a mountain of screenshots from the imagepicker is way too cumbersome

**Describe the solution you'd like**
An option to directly share images to ankidroid image occlusion activity
it saves a lot of time 
and you can start occluding right from the moment you captured it

**Comment by criticalAY** [comment]
Taking it up
