### ISSUE TITLE
[BUG]: in filtered deck, sale card is shown again and again

### ISSUE THREAD

**Issue by mtthth** [ankidroid/Anki-Android#15267]
### Checked for duplicates?

- [x] This issue is not a duplicate

### What are the steps to reproduce this bug?

Create a filtered deck.
Build it. (In French, "Reconstruire")
Review (grad fail, hard or good) the first card.

### Expected behaviour

Cards should go to their orignal deck if they are graded easy or good during reviews.

### Actual behaviour

The card goes in review (red number), and keeps being shown again and again, except if you rate it "easy".

Strangely, each grad buttons is labelled by "(end)" (in French "(fin)").

In the Deck options, you cannot choose the time effect if each grad (as in Anki desktop)

### Debug info

```text
AnkiDroid Version = 2.17alpha10 (50fa39cd561d83662cd5ef1f708b14a9a15c74ac)

Backend Version = 0.1.31-anki23.10.1 (23.10.1 fac9e0ee1436ba5ac3366c72dd9394a6e692b1cf)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = Google

Model = Pixel 7a

Hardware = lynx

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 7a Build/UQ1A.240105.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.210 Mobile Safari/537.36

ACRA UUID = 55666457-4a12-494e-8e02-e69a31e90b88

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report!

You likely have a minor bug in your `customSchedulingJs` code. Anki Desktop ignores it, AnkiDroid didn't

* Duplicate of https://github.com/ankidroid/Anki-Android/issues/15035
* Fixed in https://github.com/ankidroid/Anki-Android/pull/15061

Fixed in alpha14, closing as duplicate

**Comment by mtthth** [comment]
Thanks for your answer.

I've just upgraded to 2.17alpha14. i have exactly thé same issue.

**Comment by david-allison** [comment]
Thanks for the swift reply

Could we have a copy of your collection to diagnose further. See: https://github.com/ankidroid/Anki-Android/issues/15035#issuecomment-1865945250

----

What version of Anki Desktop are you comparing this functionality to?

**Comment by mtthth** [comment]
My bad.

Their is actually no bug. The trouble comes from the fact I've chosen (I don(t know why/how) **0 min** in the field "Repeat unknown card after..." (approx English traduction) in the _Filtered deck options_ on Anki desktop.

Sorry for the inconvenience.

**Comment by david-allison** [comment]
No worries! Thanks for testing!
