### ISSUE TITLE
[Bug] Audio recording not working

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15300]
###### Reproduction Steps

1. Open Audio Recording
2. Press Record

###### Expected Result

3. Recording starts

###### Actual Result

Either a stop & start, or the audio recording starts, but 'save' is always greyed out

###### Debug info
da41ac1cb1db39847fe2dc3b870143192873af65

on my S21

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/8167f55c-b602-4fbb-b988-0e6eaa2240eb)
Can't reproduce tested on both emulator and physical device

**Comment by criticalAY** [comment]
tested on both main and `da41ac1`  greyed out only when stopped
https://github.com/ankidroid/Anki-Android/commit/da41ac1cb1db39847fe2dc3b870143192873af65

**Comment by criticalAY** [comment]
From discord 
> Got it, its a bug that I missed in previous PRs this happens when we start recording and press back without saving or clearing the recording, and when we try to record again it doesn't work i.e. acts as the reocrding was not clreared but I have already fixed
