### ISSUE TITLE
Feature request: Previewer keyboard shortcuts ("r" and arrow key changes)

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#15305]
**Is your feature request related to a problem? Please describe.**

Followup from #15217 (thanks again). I'd like to request a couple changes in the browser - previewer so it matches behavior in desktop:
1. The `r` key should replay audio/TTS 
2. The arrow keys in AnkiDroid 2.17alpha16 currently will go through cards and skip the answer side like this:
`Question 1 -> Question 2 -> Question 3 -> ... `

Desktop behavior is to show the answer side:
`Question 1 -> Answer 1 -> Question 2 -> Answer 2 -> ... `

**Describe the solution you'd like**
See above

**Describe alternatives you've considered**
N/A

**Additional context**

AnkiDroid Version = 2.17alpha16 (37daacf8e6a9642b85135ce3c00fa44cb58ea061)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = Google

Model = Pixel 2

Hardware = walleye

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 2 Build/RP1A.201005.004.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 8c1582d1-72a4-4960-9f06-b83c67f6c621

Crash Reports Enabled = true

**Comment by BrayanDSO** [comment]
The previewer rewrite is mostly finished and includes the arrows behavior and implementing the shortcut is trivial, so I don't recommend spending time adding the feature to the legacy previewer
