### ISSUE TITLE
TTS volume adjusting

### ISSUE THREAD

**Issue by John4650-hub** [ankidroid/Anki-Android#15302]
## INTRO
I don't know whether this has already been added but it hasn't then i wish you add it.
### REASON
In my cards i usually add recorded audios explaining some concepts and the tone at which they are recorded is always low so i when am reviewing, i always adjust the volume to be able to listen clearly  **but**  a **problem** comes when the next card comes up, the volume used by the TTS engine is always very loud and kinda makes reviewing painful because now i have to re-adjust the volume. 
Thanks for the work you are doing.

**Comment by elli-hae** [comment]
How should this be implemented? E.g. with a volume slider in the settings, where you toggle TTS on and off? I might work on this.

**Comment by John4650-hub** [comment]
@elli-hae ,thanks for replying. I think their should be a slider to somewhere in the settings , which can be used to set the TTS volume  which should then be applied to all cards in a deck when TTS is enabled during.  That way the general device volume remains unchanged. For audio recordings they can remain dependant on the system volume.

**Comment by david-allison** [comment]
Would adding an `AnkiDroid Volume` to the TTS tag resolve this issue?

`{{tts en_GB ad_volume=20:Front}}`

```patch
Index: AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt	(revision 906dd02571179f3096af4cdf32a924385c2af4b2)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt	(date 1708285715215)
@@ -20,7 +20,9 @@
 import android.os.Bundle
 import android.speech.tts.TextToSpeech
 import android.speech.tts.TextToSpeech.ERROR
+import android.speech.tts.TextToSpeech.Engine.KEY_PARAM_VOLUME
 import androidx.annotation.CheckResult
+import androidx.core.os.bundleOf
 import com.ichi2.anki.AndroidTtsError.TtsErrorCode
 import com.ichi2.compat.UtteranceProgressListenerCompat
 import com.ichi2.libanki.TTSTag
@@ -117,7 +119,10 @@
                 currentUtterance = this
                 cancelledUtterances.remove(this)
             }
-            tts.speak(tag.fieldText, TextToSpeech.QUEUE_FLUSH, bundleFlyweight, utteranceId)
+            val bundle = tag.volume?.let {
+                Bundle().apply { putFloat(KEY_PARAM_VOLUME, it / 100) }
+            } ?: bundleFlyweight
+            tts.speak(tag.fieldText, TextToSpeech.QUEUE_FLUSH, bundle, utteranceId)
 
             continuation.invokeOnCancellation {
                 Timber.d("stopping tts due to cancellation")
@@ -223,3 +228,14 @@
     } else {
         this.toString()
     }
+
+/**
+ * Returns the custom `volume=` parameter, from 0 to 100
+ */
+val TTSTag.volume: Float?
+    get() {
+        val volumeParam = this.otherArgs.firstOrNull { it.lowercase().startsWith("ad_volume=")} ?: return null
+        val volume = volumeParam.substring("ad_volume=".length).toFloatOrNull() ?: return null
+        if (volume < 0 || volume > 100) return null
+        return volume
+    }
\ No newline at end of file
```

**Comment by BrayanDSO** [comment]
I think that's reasonable trying to get this in upstream first, so the TTS format is as much cross-platform as possible

**Comment by david-allison** [comment]
We don't want volume to be consistent across the platforms: each platform uses a different voice with different volume characteristics

**Comment by BrayanDSO** [comment]
Very reasonable

**Comment by elli-hae** [comment]
That approach makes a lot more sense! @John4650-hub are you satisfied with this fix then?

**Comment by John4650-hub** [comment]
> Would adding an `AnkiDroid Volume` to the TTS tag resolve this issue?
> 
> `{{tts en_GB ad_volume=20:Front}}`
> 
> patch
> ```diff
> Index: AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt
> --- a/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt	(revision 906dd02571179f3096af4cdf32a924385c2af4b2)
> +++ b/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt	(date 1708285933163)
> @@ -20,7 +20,9 @@
>  import android.os.Bundle
>  import android.speech.tts.TextToSpeech
>  import android.speech.tts.TextToSpeech.ERROR
> +import android.speech.tts.TextToSpeech.Engine.KEY_PARAM_VOLUME
>  import androidx.annotation.CheckResult
> +import androidx.core.os.bundleOf
>  import com.ichi2.anki.AndroidTtsError.TtsErrorCode
>  import com.ichi2.compat.UtteranceProgressListenerCompat
>  import com.ichi2.libanki.TTSTag
> @@ -117,7 +119,10 @@
>                  currentUtterance = this
>                  cancelledUtterances.remove(this)
>              }
> -            tts.speak(tag.fieldText, TextToSpeech.QUEUE_FLUSH, bundleFlyweight, utteranceId)
> +            val bundle = tag.volume?.let {
> +                bundleOf(KEY_PARAM_VOLUME to it / 100)
> +            } ?: bundleFlyweight
> +            tts.speak(tag.fieldText, TextToSpeech.QUEUE_FLUSH, bundle, utteranceId)
>  
>              continuation.invokeOnCancellation {
>                  Timber.d("stopping tts due to cancellation")
> @@ -223,3 +228,16 @@
>      } else {
>          this.toString()
>      }
> +
> +/**
> + * Returns the custom `ad_volume=` parameter, from 0 to 100
> + *
> + * `{{tts en_GB ad_volume=30:Front}}`
> + */
> +val TTSTag.volume: Float?
> +    get() {
> +        val volumeParam = this.otherArgs.firstOrNull { it.lowercase().startsWith("ad_volume=")} ?: return null
> +        val volume = volumeParam.substring("ad_volume=".length).toFloatOrNull() ?: return null
> +        if (volume < 0 || volume > 100) return null
> +        return volume
> +    }
> \ No newline at end of file
> ```

Yes.
