### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by sebastianrueckerai** [ankidroid/Anki-Android#15313]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Not sure if this happens for everyone. For me:
1. Making a simple occlusion card on anki desktop
2. Trying to use the card on Anki Android 

### Expected behaviour

Occlusion should be occluded. :)

### Actual behaviour

The German text is saying: "Problem when loading occlusion. Do you have the latest Anki version?"

![Screenshot_20240122-232420](https://github.com/ankidroid/Anki-Android/assets/83586913/4fb83be1-6cc9-4403-affb-c6b6b59a98d5)

### Debug info

```text
2.16.5
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Fixed in the 2.17alpha
