### ISSUE TITLE
Legacy TTS: "Type for self" is spoken on "Type in the Answer" Cards

### ISSUE THREAD

**Issue by Goovac27** [ankidroid/Anki-Android#15316]
On the card to type the answer, the TTS voice repeats two annoying words at the end of each sentence. I see no benefit in keeping these two words mandatory in the TTS voice, it’s driving me crazy.

**Comment by david-allison** [comment]
@Goovac27 Could you provide a sample card?

Are you using our legacy TTS, or Anki's `{{tts}}` tag?

https://docs.ankiweb.net/templates/fields.html#text-to-speech-for-individual-fields

**Comment by Goovac27** [comment]
> @Goovac27Você poderia fornecer um cartão de amostra?
> 
> Você está usando nosso TTS legado ou `{{tts}}`a tag de Anki?
> 
> https://docs.ankiweb.net/templates/fields.html#text-to-speech-for-individual-fields

I don’t understand these things very well… but I’ll try to clarify what I’m finding inconvenient:

After creating a deck in Ankidroid, when we want to add a card, we choose its type.

The type of card I chose was: Basic (type the answer).
Now, I’m about to put a sentence on the front of the card and another on the back of the card.
Done! I just saved the card.

When reviewing the card, I realize that using TTS is more efficient for me. Because I will have to add hundreds of sentences, thousands, since this is my goal.
However, there is a small problem that I find annoying, sir.

Every time the TTS reads the sentence, always after the TTS voice finishes reading the sentence that I had put on the front, the TTS voice ends with the following robotic text: ‘type for self’.

Once it’s bearable… but after hearing ‘type for self’ hundreds of times at the end of each sentence, it’s driving me crazy.

Sir, would there be any solution? :("

**Comment by david-allison** [comment]
Come to [Discord](https://discord.gg/qjzcRTx) (`#help`) and ask them to walk you through setting up `{{tts}}`

We plan to be remove the old text to speech in the advanced settings after a few more AnkiDroid releases, and I suspect we're not going to fix bugs before removal

**Comment by david-allison** [comment]
Closing this as https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix, fixed by `{{tts}}` and we're removing our legacy TTS:

* https://github.com/ankidroid/Anki-Android/issues/15475
