### ISSUE TITLE
Clarification on Licensing for use of AnkiDroid API in Non-GPL-3 Projects

### ISSUE THREAD

**Issue by IstoraMandiri** [ankidroid/Anki-Android#15337]
Hello AnkiDroid Team,

I am in the process of developing an Android application and am considering the integration of the AnkiDroid API.

I noticed that https://github.com/ankidroid/Anki-Android/blob/main/api/src/main/java/com/ichi2/anki/FlashCardsContract.kt. includes the following licensing preamble:

```
//noinspection MissingCopyrightHeader - explicitly not GPL

/*
 * Copying and distribution of this file, with or without modification, 
 * are permitted in any medium without royalty. 
 * This file is offered as-is, without any warranty.
 */
```

IANAL, and I am confused as I had assumed that AnkiDroid itself being licensed under GPL-3 would mean that this file would also need to be GPL-3, but it implies that the authors of AnkiDroid have decided to license this particular file under different terms..

I'm trying to figure out whether or not I can use the AnkiDroid API, utilizing the mentioned file, in a proprietary, non-GPL-3.0 licensed Android application without the need to open-source my entire application under GPL-3 (or at least without having to do some plugin/dynamic loading).

My app isn't intending to be a derivative work of AnkiDroid and I simply want to allow users to add cards via this API. Is it possible to do so without inheriting the GPL-3 license?

If you are able help clear up this confusion it would be much appreciated.. Finally, are are there any guidelines for deploying proprietary android apps that utilize the AnkiDroid API?

Thank you.

**Comment by david-allison** [comment]
The API is under LGPL specifically for this reason: https://github.com/ankidroid/Anki-Android/blob/main/api/COPYING.LESSER

**Comment by david-allison** [comment]
Unless I'm missing something, the file that you linked in LGPL (GNU Lesser General Public License):

https://github.com/ankidroid/Anki-Android/blob/866369337a2ee1838b2075a401029c11b0fc33e9/api/src/main/java/com/ichi2/anki/api/AddContentApi.kt#L1-L17
