### ISSUE TITLE
Confusion in regard to Android permissions "all file access"

### ISSUE THREAD

**Issue by zxcvxzcv-johndoe** [ankidroid/Anki-Android#15330]
Hello,

First of all, I have read this https://github.com/ankidroid/Anki-Android/wiki/Permissions#permissions and https://play.google.com/store/apps/details?id=com.ichi2.anki

And I am running the latest alpha version:
AnkiDroid Version = 2.17alpha16 (37daacf8e6a9642b85135ce3c00fa44cb58ea061)
Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)
Android Version = 13 (SDK 33)
ProductFlavor = full
Manufacturer = OnePlus
Model = KB2003
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 13; KB2003 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Mobile Safari/537.36
ACRA UUID = 66ee9faa-7f83-4666-b9ae-121482db2d6a
Crash Reports Enabled = true

I am not able to continue without giving AnkiDroid "all files access" which sounds dangerous. Like that continue button is greyed out without that permission.

I dont want to give any Android app any unnecessary permissions. I do understand that for some people those backups might be only ones but personally I do sync my deck to AnkiWeb and I also backup my deck with my PC so I don't want AnkiDroid to do anything "extra" just in case.

Why cannot we have an option to bypass that?

![image](https://github.com/ankidroid/Anki-Android/assets/124170934/b42a602e-1f3f-4a62-82d4-07235c428e7f)

And what confuses me greatly is that "Read and Write to the Ankidroid database" permissions and how is that even related to "all files access" permission? Like I am not even sure if in my Android AnkiDroid has the "all files access" unless I totally misunderstand what that means? 

![image](https://github.com/ankidroid/Anki-Android/assets/124170934/626c0544-12d6-4cc6-b6ba-18b1ef659ff1)

![image](https://github.com/ankidroid/Anki-Android/assets/124170934/8730908e-4295-4913-b307-9d47e8e03690)

**Comment by david-allison** [comment]
Download the "play" variant, that doesn't require "All Files"
