### ISSUE TITLE
[BUG]: In full sync dialog, the button disappeared

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#15346]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

I don't know. Appart from needing a full sync

### Expected behaviour

All buttons present

### Actual behaviour

![image](https://github.com/ankidroid/Anki-Android/assets/357361/b9d427c0-7a7f-4a60-87e6-db3761b16803)

### Debug info

```text
AnkiDroid Version = 2.17alpha17 (866369337a2ee1838b2075a401029c11b0fc33e9)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 8 Pro

Hardware = husky

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Pro Build/UQ1A.240105.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Mobile Safari/537.36

ACRA UUID = 47035a3d-ff8b-4423-8485-1d6d82d48957

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

The button still exists. I was able to use them as usual. But if I didn't know where they were, I would never have found them.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Fixing it!

**Comment by user1823** [comment]
Not directly related but the sync popup has a somewhat awkward padding now.

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/bad56856-2b70-4715-ace5-80c70dfd5ff2">

I think that both of these issues are caused by https://github.com/ankidroid/Anki-Android/pull/15310.

**Comment by criticalAY** [comment]
> Not directly related but the sync popup has a somewhat awkward padding now.

This is the default padding and is fine but #[15333](https://github.com/ankidroid/Anki-Android/pull/15333) caused other issues

**Comment by user1823** [comment]
> This is the default padding and is fine

The top has less padding than the bottom, which makes it look awkward.

**Comment by oakkitten** [comment]
The button is probably there, just the text color is wrong

**Comment by criticalAY** [comment]
It's a theme issue I have the solution ready but couldn't push it, I will do it after gym
