### ISSUE TITLE
Replace check to checks

### ISSUE THREAD

**Issue by neeldoshii** [ankidroid/Anki-Android#15348]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Step to Reproduce : 
* Click on More Option from top right
* Click on Check
* Inside Submenu of Check you will see Check again which doesn't do anything.

### Video Preview for more clarification

https://github.com/ankidroid/Anki-Android/assets/60827173/ce79d77c-cd9b-44f7-9965-50680e83a2fb

### Expected behaviour

Remove the Check in sub-menu.

### Actual behaviour

-

### Debug info

```text
AnkiDroid Version = 2.17alpha16-debug (c6e5dc905953831a818753b107bb9f2ffc487bc7)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 11; sdk_gphone_arm64 Build/RSR1.210722.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.193 Mobile Safari/537.36

ACRA UUID = af136e21-9780-4507-b754-8c6edb93dfd8

Crash Reports Enabled = false
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by neeldoshii** [comment]
I am taking up on this issue please assign me Maintainers.
Thanks

**Comment by BrayanDSO** [comment]
That's the title of the menu, and how every menu works by default. Not an issue

**Comment by david-allison** [comment]
Is it feasible to rename the title to 'Checks', I feel the title is confusing currently

**Comment by neeldoshii** [comment]
> Is it feasible to rename the title to 'Checks', I feel the title is confusing currently

Done

**Comment by david-allison** [comment]
I was referring to the menu title
