### ISSUE TITLE
[BUG]: Time to show answer - 0s is not working as expected

### ISSUE THREAD

**Issue by ruzx** [ankidroid/Anki-Android#15342]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Open AnkiDroid.
Navigate to Settings.
Go to Reviewing settings.
Set the time to show the answer (or question) to 0s.

### Expected behaviour

When attempting to set the time to show the answer (or question) to 0s (zero seconds, implying no pauses) in AnkiDroid, the expected behavior is for the cards to continuously flip or change rapidly, especially in cramming mode where this feature is extensively used. However, this is not happening as anticipated.

In previous versions of AnkiDroid, specifically version 2.9 or older, setting the answer (or question) display time to 0s during cramming mode would result in the audio/cards changing repeatedly without any pause, creating a seamless and continuous learning experience when cramming before test.

### Actual behaviour

Currently, when the time is set to 0s, the first card front is displayed, audio is played, but the answer is not shown, and there's no auto-advance to the next card. This behavior is different from the expected behavior observed in older versions and is quite misleading. Interestingly, setting the time to 1s works, albeit with a pause, but 0s does not, which is unintuitive.

This regression in behavior is affecting the efficiency of cramming sessions, as the continuous and rapid card changes in cramming mode are not functioning as expected when the time to show the answer is set to 0s. 

### Debug info

```text
AnkiDroid Version = 2.17alpha8 (945014383cba6e47dc41ef244f3e929ac548246c)

Android Version = 10

ProductFlavor = play

Manufacturer = Xiaomi

Model = Redmi Note 7

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi Note 7 Build/QKQ1.190910.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.26 Mobile Safari/537.36

ACRA UUID = c220e1e8-0386-4f79-8d0d-ae897975a216

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, thanks for the report! Please update to alpha17. Should be fixed there.

Please let me know if you're still having issues after this

**Comment by ruzx** [comment]
> Hi, thanks for the report! Please update to alpha17. Should be fixed there.
> Please let me know if you're still having issues after this

Hi, thank you for your prompt response. I've upgraded to alpha17 as suggested and tested the issue again. Unfortunately, the behavior still persists.

Setting the time to 1s works as expected, but any decimal smaller than 1s (e.g., 0.0 or 0.5s) is not functioning as previously described.

**Comment by pavreh** [comment]
Actually, 0s means Auto Advance is stopped. See the documentation [https://docs.ankiweb.net/deck-options.html?auto-advance#auto-advance](https://docs.ankiweb.net/deck-options.html?auto-advance#auto-advance)

**Comment by ruzx** [comment]
@pavreh 

Thanks for explaining; it clicks now that AnkiDroid is aligning with the global Anki behavior. Maybe in previous AnkiDroid versions, the 0s with its own audio approach was better. Hmm, actually, it was better back then.
