### ISSUE TITLE
Full-screen Mode: System bars reappear after navigating menu

### ISSUE THREAD

**Issue by kirbysama** [ankidroid/Anki-Android#15356]
**Issue**
After entering full-screen mode, in certain instances the top/bottom bars will reappear, covering the card text (i.e. the bars are present but the card is aligned as though the bars are hidden). By switching apps (most reliable method) or dragging a finger up/down across the card ("wiggling the card"), the menu bars can hidden again.

**Expected Behavior**
System bars should remain hidden when returning to review mode from the AnkiDroid menu while full screen mode is active.

**Reproducibility Steps**
1. Enter fullscreen mode through Menu>Appearance>Fullscreen Mode>Hide the system bar and answer buttons.
2. Return to Decks.
3. Begin review.
4. Open side panel by swiping in from the left.
5. Tap Settings.
6. Use the left arrow or back button to return to card review.
7. System bar and answer buttons have reappeared, despite still being in Fullscreen mode.
8. Return to Appearance menu, notice that Fullscreen mode is still enabled.

**Comments**
This may be related to whichever function temporarily un-hides the system bars when the user interacts with the card in a way that suggests they may want to see the system bats.

Notice as well, that at the bottom of the screenshot, the answer bar is visible, but appears to be floating since the system controls (Back/Home/App Switcher) are hidden, leaving empty space where they would be located.

![Screenshot_20240128_022650_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/7307574/0ee420a2-5198-462e-b9f6-8c1399641803)

**Device info**
AnkiDroid version: 2.17alpha15
Samsung Galaxy S20 FE 5G
Model #: SM-G781U
Phone software details:
![Screenshot_20240128_024151_Settings](https://github.com/ankidroid/Anki-Android/assets/7307574/ab70c21c-203f-4dae-b448-abfe99098021)

**Comment by Bobalogic** [comment]
I would like to work on this!

**Comment by brishtibheja** [comment]
Related Issue: <https://github.com/ankidroid/Anki-Android/issues/16883>

In this one, system bars are visible while using **Set due date** or **Edit tags**.

**Comment by BrayanDSO** [comment]
I'll close this issue to concentrate efforts in the new reviewer (#14302)
