### ISSUE TITLE
[Bug] IO cards can't be previewed from note editor

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15359]
###### Reproduction Steps

1. Open an IO card from the browser
2. In the note editor, click on the Preview button.

###### Expected Result
The preview is displayed.

###### Actual Result
An error "A card could not be generated" appears.

###### Debug info
2.17 alpha 17

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
Unrelated, but I am not sure if I should create a separate issue for this:

If an IO note is open in the Editor and you click `Edit Occlusions → Note`, a rudimentary version of the Desktop Note Editor opens. The user can use Bold, Italics and Underline. Adding Tags works too.

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/5841c666-8461-4f1c-95d0-faef91b77078">

So, AnkiDroid could probably use the Desktop Note Editor after some more development (maybe in 2.18)?

**Comment by BrayanDSO** [comment]
Should have been fixed in #15030 (pinging @criticalAY)

> (maybe in 2.18)

The IO editor was thought to be reusable in mobile devices, while the default one wasn't, so that will likely take way more time

**Comment by mikehardy** [comment]
#15359 merged, this should be fixed in next release (2.17.2...)
