### ISSUE TITLE
[BUG]: Add button disappear after perform a search and go back

### ISSUE THREAD

**Issue by krantos** [ankidroid/Anki-Android#15352]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Having at least one Deck
2. From the Decks view tap on Search btn (zoom icon)
3. Write a word that matches any Deck
4. Tap on any resulting deck to enter into a card
5. Tap the android system back btn
6. Add button (plus icon) isn't visible on the decks view

### Expected behaviour

1. After tap on the Android back -> go back to the deck search results
2. Add button is still present on the decks view 

### Actual behaviour

Add button (plus icon) isn't visible on the decks view

![WhatsApp Image 2024-01-27 at 19 41 50](https://github.com/ankidroid/Anki-Android/assets/14831392/9e0d747b-a79a-4313-8495-44e83569182e)

### Debug info

```text
AnkiDroid Version = 2.17alpha17 (866369337a2ee1838b2075a401029c11b0fc33e9)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = samsung

Model = SM-A546E

Hardware = s5e8835

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-A546E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Mobile Safari/537.36

ACRA UUID = 9e2c8b06-d3c6-4569-abe3-385111f2bc9e

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by CyberButton** [comment]
I would like to work on this one

**Comment by SanjaySargam** [comment]
@CyberButton Are you still working on it ?
If not, I'd like to work on this

**Comment by CyberButton** [comment]
> @CyberButton Are you still working on it ? If not, I'd like to work on this

yes, almost done)

**Comment by BrayanDSO** [comment]
Not worth blocking the 2.17 release IMO

**Comment by CyberButton** [comment]
I think this issue can be closed https://github.com/ankidroid/Anki-Android/pull/15379
