### ISSUE TITLE
[Docs] Document additional removed features [Stats/Custom Fonts]

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15355]
* Statistics
    * Advanced Statistics
* ~~Custom Fonts~~

**Comment by brishtibheja** [comment]
In case you guys missed it I'll just add that (don't know what you call it) the text under Appearances still includes fonts even though it was removed.
![Screenshot_2024-02-05-07-51-21-40_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/a3aa4eaf-533d-4227-bc08-b09b3f847738)
