### ISSUE TITLE
[Bug] [2.17beta1] long-click "browse cards" feature remains stuck on first deck you selected

### ISSUE THREAD

**Issue by diceoh** [ankidroid/Anki-Android#15386]
###### Reproduction Steps

AnkiDroid 2.17beta1 on Pixel 8

1. Long-press, "browse cards" on one deck in your collection
2. Back out of the menu
3. Long-press, "browse cards" on another deck.

###### Expected Result

See the deck that you just selected.

###### Actual Result

See the browse cards menu for the first deck you selected. This behavior does not change no matter which cards you select.

###### Debug info

AnkiDroid Version = 2.17beta1 (ce6fef6f743f8b68c40608d85dd3fbc6b882d856)
Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)
Android Version = 14 (SDK 34)
ProductFlavor = full
Manufacturer = Google
Model = Pixel 8
Hardware = shiba
Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Build/UQ1A.240105.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.232 Mobile Safari/537.36
ACRA UUID = 5d76ee4b-a153-4e62-836b-92b6e9f8bf8d
Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
I'd love to work on this

**Comment by SanjaySargam** [comment]
Bug found between 2.17alpha14 and 2.17alpha15

**Comment by lukstbit** [comment]
Thanks for the bug report, the fix should be available in the next beta.

@SanjaySargam I added a fix for this as I saw what is the issue when I replicated the bug.
