### ISSUE TITLE
TTS language selecting popup appears repeatedly on every card

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1539]
Originally reported on Google Code with ID 636

```
What steps will reproduce the problem?
1. Text speech selecting is not saved.
2. repeat the selecting popup on every cards
3.

What is the expected output? What do you see instead?


What version of AnkiDroid are you using? On what version of Android?
New version only
alpha3 ,4

alpha2 is ok

Please provide any additional information below.

```

Reported by `weepis` on 2011-05-23 15:05:34

**Comment by sjleejf** [comment]
Hi hssm,

I'm using the latest 2.8.3 version of AnkiDroid.

And I'm experiencing the exact same bug that you wrote (TTS language selecting popup appears repeatedly on every card #1539).

Are you aware of this problem? How can I fix this?

Thanks.
