### ISSUE TITLE
[BUG]: Can't play sound files whose names include '#'

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15399]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

0. (Optional) Do "Check media" and/or use a file-manager App to confirm there is no trouble regarding the sound file itself described below
1. Tap a sound play button whose sound file name includes '#' (hash character)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/97c1522b-4ab1-49f9-8840-5382f5b67ef2)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/7796b83f-4b44-4035-9e22-a479b89a5d9f)

### Expected behaviour

The sound gets played, as on Anki DeskTop.

### Actual behaviour

The sound doesn't get played. 

The screen shows no response or the following error message. 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/a8b79f9f-2227-452a-a73e-557fa1aeff1b)
The filename displayed in the error message doesn't include the string after '#' (that is, `#1.mp3` of `test132#1.mp3` in the example above). 

### Debug info

```text
AnkiDroid Version = 2.17beta1 (ce6fef6f743f8b68c40608d85dd3fbc6b882d856)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Sample apkg file
[test_filename 2.zip](https://github.com/ankidroid/Anki-Android/files/14155284/test_filename.2.zip)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Funny that #15353 doesn't happen here.

Since now we need to have a server to intercept POST requests and because of it files are now requested as an HTTP URL (e.g. `http://127.0.0.1:40001/test#123.mp3`), my bet is the `#` is being treated as the fragment marker of an URL

**Comment by criticalAY** [comment]
> Since now we need to have a server to intercept POST requests and because of it files are now requested as an HTTP URL (e.g. http://127.0.0.1:40001/test#123.mp3), my bet is the # is being treated as the fragment marker of an URL

Ig no, it's due to the media player not being able to escape the special chars from the file name and directly setting it to dataSource

**Comment by criticalAY** [comment]
> Leave it to me!!!

Sorry! I have already fixed it on my end :)

**Comment by snowtimeglass** [comment]
Thanks for the fix!
