### ISSUE TITLE
Request: Restore ETA / Estimated Time Remaining (Beta 2.17 Feedback)

### ISSUE THREAD

**Issue by briankrznarich** [ankidroid/Anki-Android#15405]
... at least as an option, even if disabled by default.

Description: while reviewing cards, prior to 2.17 an ETA was shown at the top of the screen.  This has been deliberately removed to harmonize with the desktop app.   

I understand this was done intentionally, and is not a bug.  But as the beta has just dropped, I'd suggest that you might want an "open" ticket for consolidated feedback to see how big of an issue this is (or is not).   Previous feedback has all been closed as "feature-not-a-bug".

Ankidroid differs from Anki Desktop (I use both) in two critical ways:
1. Ankidroid is more likely to be used as a "review-only" tool, which makes time estimates significantly more reliable. (Average Time/review * cards remaining = pretty-good-estimate). I do 99% of my card editing in the desktop app, and 100% of my reviews in Ankidroid.  A common complaint seems to have been that ETA had poor handling of card-creation and editing time.  That doesn't apply if you only use the app for reviews.
2. Ankidroid doesn't have plugins

ETA was removed from the desktop app because it was inaccurate. But this was okay, because the desktop application supports plugins for those who rely on the feature, and people quickly went and put it back. See for example:
Study Time Stats (adds an ETA)
https://ankiweb.net/shared/info/1247171202
More Decks Stats and Time Left
https://ankiweb.net/shared/info/1556734708
Remaining time (for Anki 2.1)
https://ankiweb.net/shared/info/1508357010
https://github.com/trgkanki/remaining_time/issues/78  Fix for newer Anki
Progress Bar, cards done, cards left, seconds/card, time spent/left, and ETA
https://ankiweb.net/shared/info/1097423555

Ankidroid users don't have this luxury.  The feature is available, or it isn't. 

As a regular Ankidroid user for the last 5+ years, this really is a critical part of my routine as I chop down the "remaining time" throughout the day, and make sure I allot enough time to finish cards before the new day rolls around.   Some people may find a large ETA demotivating.  I personally find reducing the ETA to be very motivating("only 20 minutes to go!").

The moment I got the beta update, I first dug through the settings to find an option to turn ETA back on. When it wasn't there, I searched github. When I realized what had happened,  I was ready to roll-back immediately to 2.16.  But then I wouldn't be able to beta test the rest of the app, so I will stick it out for now.   If this is a permanent change, I may freeze myself at 2.16 and do my best to ride it till the wheels fall off.

Others may be similarly distraught.

I'm quite a bit late to "giving back", but I've just registered as a contributor on OpenCollective.  If this change would take a significant amount of work (and I'm not the only one who misses it), I'd be happy to help contribute towards development.  I appreciate all the effort that goes into making Ankidroid all that it is, and I appreciate your consideration.   

For reference, related closed items on this issue:

* #15047
* #15244

**Comment by briankrznarich** [comment]
Just noticed... It looks like Ankidroid it still computing a "time remaining", as it is displayed in the widget.  Unfortunately it's the rollup for all decks, which isn't great if you've orphaned some decks for a while...  

Surely it's inconsistent to display remaining-time in the widget if it's not displayed anywhere else in the app.  If it was added to the widget in the first place, surely someone else found it useful...

![image](https://github.com/ankidroid/Anki-Android/assets/11246418/b3121027-9b78-4776-a834-88ef20f73d60)

**Comment by brishtibheja** [comment]
ETA used to scared me when I would have too many reviews and it would show me like 2 or 3 hours. Quite demotivating for me. Well anyway I don't think it's coming back. You should try the anki forums and see if they add it to desktop. I've grown attached to it certainly but I think this is better.

**Comment by david-allison** [comment]
Proposal:

If someone can write a decent spec for: "what happens to the title when a user changes to a card which doesn't use the API"

Then we can add `setSubtitle` to the API:

```patch
Subject: [PATCH] bb
---
Index: AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt b/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt	(revision e3520ebe1462bb2ac6d2683454a3f4126d8d5353)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/NavigationDrawerActivity.kt	(date 1707103427678)
@@ -28,6 +28,7 @@
 import androidx.annotation.LayoutRes
 import androidx.annotation.VisibleForTesting
 import androidx.appcompat.app.ActionBarDrawerToggle
+import androidx.appcompat.app.ActionBar
 import androidx.appcompat.widget.Toolbar
 import androidx.coordinatorlayout.widget.CoordinatorLayout
 import androidx.core.app.ActivityCompat
@@ -197,6 +198,7 @@
         }
     }
 
+    /** @see ActionBar.setTitle */
     override fun setTitle(title: CharSequence) {
         if (supportActionBar != null) {
             supportActionBar!!.title = title
@@ -204,6 +206,11 @@
         super.setTitle(title)
     }
 
+    /** @see ActionBar.setSubtitle */
+    var subtitle: CharSequence?
+        get() = supportActionBar?.subtitle
+        set(value) {  supportActionBar?.subtitle = value }
+
     /**
      * When using the ActionBarDrawerToggle, you must call it during
      * onPostCreate() and onConfigurationChanged()...
Index: AnkiDroid/src/main/assets/scripts/js-api.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/assets/scripts/js-api.js b/AnkiDroid/src/main/assets/scripts/js-api.js
--- a/AnkiDroid/src/main/assets/scripts/js-api.js	(revision e3520ebe1462bb2ac6d2683454a3f4126d8d5353)
+++ b/AnkiDroid/src/main/assets/scripts/js-api.js	(date 1707102572347)
@@ -71,6 +71,8 @@
     ankiSttSetLanguage: "sttSetLanguage",
     ankiSttStart: "sttStart",
     ankiSttStop: "sttStop",
+    ankiSetTitle: "setTitle",
+    ankiSetSubtitle: "setSubtitle",
 };
 
 class AnkiDroidJS {
Index: AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt	(revision e3520ebe1462bb2ac6d2683454a3f4126d8d5353)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidJsAPI.kt	(date 1707103427676)
@@ -355,6 +355,16 @@
                 convertToByteArray(apiContract, mSpeechRecognizer.start())
             }
             "sttStop" -> convertToByteArray(apiContract, mSpeechRecognizer.stop())
+            "setTitle" -> {
+                activity.supportActionBar?.setDisplayShowTitleEnabled(true)
+                activity.title = apiParams
+                convertToByteArray(apiContract, true)
+            }
+            "setSubtitle" -> {
+                activity.supportActionBar?.setDisplayShowTitleEnabled(true)
+                activity.subtitle = apiParams
+                convertToByteArray(apiContract, true)
+            }
             else -> {
                 showDeveloperContact(ankiJsErrorCodeError, apiContract.cardSuppliedDeveloperContact)
                 throw Exception("unhandled request: $methodName")
```

```js
<script>
    var jsApi = { "version": "0.0.2", "developer": your email here };
    var api = AnkiDroidJS.init(jsApi);
    var response = api.ankiSetSubtitle("Hello world").then(() => {});
</script>
```

**Comment by briankrznarich** [comment]
wow @david-allison , thanks for taking a look at this 

@brishtibheja The issue is that Anki Desktop has no need to add this feature.  It already has it via the plugin system.  So the only justification for forcing it into Anki Desktop would be to get it into Ankidroid. I don't know that the Anki Desktop maintainer would (or should be expected to) entertain that kind of request.

**Comment by mikehardy** [comment]
What David's code above does is make it so that AnkiDroid can *also* have it via our plugin system.
Our plugin system will be / is based on javascript implementations people can add to cards, that then get info / display info in various parts of the app

So if adding the ability to make a subtitle is useful, then we can expose that as an API that plugins can use, and then people can add a little javascript to their card template that uses it to set the subtitle with the ETA info

In the future we'll have the ability to not just hand-hack Javascript into the card template but to actually package it as AnkiDroid JS Add-ons that you can share, download, install, enable/disable, delete etc (like you'd expect with a download system)

But first step is figuring out what parts of the AnkiDroid app people would like to be able to tweak (like, maybe, adding a subtitle?) and then making sure we have a javascript binding for that...

**Comment by david-allison** [comment]
Custom fonts are supported in the reviewer without addons

We recently removed them from being used as an interface font

**Comment by brishtibheja** [comment]
Yeah but it's still sad that it doesn't work on card browser and my deck looks like this.
![Screenshot_2024-02-06-02-11-03-66_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/7870d4b4-a34f-4383-b12c-a5a521f3f7ec)

**Comment by david-allison** [comment]
@brishtibheja It'd be worthwhile to submit an issue

**Comment by brishtibheja** [comment]
@david-allison okay I can but this is a issue with my phone that it doesn't support the chu nom script. Are you saying interface fonts are coming back?

**Comment by david-allison** [comment]
> If someone can write a decent spec for: "what happens to the title when a user changes to a card which doesn't use the API"
> 
> Then we can add `setSubtitle` to the API

See above for the problem:

* If the ETA is set on one card, and the next 10 cards don't have the code to show the ETA, what should happen?

---

I'd say:

* If the subtitle hasn't been set on a card within 200ms, remove it

**Comment by BorisNA** [comment]
P.S. My bad, I missed the discussion main point. My point was that adding some info via the card template will not work and/or will not be used by many people. 

I thought about some JS-code (hooks?) that is called before/after card render and can modify some 'system' parts outside of the card itself (don't know - buttons? title or how-is-it-called where three red numbers are displayed? patch card's DOM? may be even bury a card according to its own logic?)

**Comment by david-allison** [comment]
That's not going to get done before the next public release

We have the opportunity to fix this now if we can spec it. We can then move it to an addon (which can run hooks) later this year

**Comment by BorisNA** [comment]
Thanks for clarification. I totally agree with priorities, to make a public release with FSRS and other upstream compatibility changes is the most important now.  I never thought about pausing it for addons or statistics.

As for

> I'd say:
>
I> f the subtitle hasn't been set on a card within 200ms, remove it

Maybe an easier solution, without timers, will do?

1. Clear the subtitle on a card change (there is a redraw, so the flicker will not be so noticeable)
2. If the next card wants, it sets its own subtitle.

**Comment by david-allison** [comment]
I suspect there will be a flicker: the JS API is async

I'll ping Discord for additional discussion here, then let's do something after a solid proposal

**Comment by david-allison** [comment]
After [a discussion](https://discord.com/channels/368267295601983490/701922522836369498/1205329268662341693), reverting.

I would like to get the `setSubtitle` code into the API, so it can be used by addons, but this isn't a priority while a general 2.17 release is close

This issue should be closed when the strings from https://github.com/ankidroid/Anki-Android/pull/14939 are restored on CrowdIn (likely manually)

**Comment by david-allison** [comment]
just to note:

> This issue should be closed when the strings from https://github.com/ankidroid/Anki-Android/pull/14939 are restored on CrowdIn (likely manually)

only as a nice-to-have: we've had these translations for years, and it'd be a shame to see them go to waste
