### ISSUE TITLE
[BUG]: At end-of-day, deck summary shows 'again' cards remaining, but opening goes to "You have finished the deck for now"

### ISSUE THREAD

**Issue by briankrznarich** [ankidroid/Anki-Android#15408]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Only produced once so-far(first day using app).  Review cards right up until the end of the "day" rollover. (3am for me).   Finish all cards on time, but mark some cards as "again" while reviewing.  The cards marked "again" actually disappear from the queue (because they are scheduled for "tomorrow" at this point).  Finish all reviews ~1 minute before the rollover. (It might not need to get this close, but this is what I did).   Get the "Congratulations, you have finished this deck for now" screen.  Hit back button to return to deck list.

### Expected behaviour

The completed deck displays no cards due in any category.

### Actual behaviour

The completed deck has 1 red "again" card remaining.  Attempting to open the deck, I was returned to the "You have finished the deck for now" screen.  Impossible to "complete" that one card. 
![1000005810](https://github.com/ankidroid/Anki-Android/assets/11246418/424a2367-a4d3-402c-b824-f4e9da9e3132)
![1000005809](https://github.com/ankidroid/Anki-Android/assets/11246418/290d39b2-5793-4974-a041-22629901a842)

### Debug info

```text
AnkiDroid Version = 2.17beta1 (ce6fef6f743f8b68c40608d85dd3fbc6b882d856)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 7a

Hardware = lynx

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 7a Build/UP1A.231105.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Mobile Safari/537.36

ACRA UUID = c6a34d86-e649-446f-9365-99a7dc473cb5

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

This might be among the top of the "most inconsequential" bugs list, but anyway...

I am currently only studying the first deck in the screenshots, but I've included others so you have a complete picture.  Once the day rolled over, I had not 1, but 17 "again" cards (in red) due at the beginning of the next "day". (30 new, 17 again, 586 review).  

It is possible that I ended up with exactly 1 card schedule exactly somewhere between 2:59 and 3:01, and that differences in time rounding calculations between deck-list home screen, and the calculations for selecting cards to actually review are inconsistent.

I run down to the wire *a lot*, and have never seen this in earlier versions of AnkiDroid.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by briankrznarich** [comment]
If you read the text of the "you have finished this deck for now screen", you can even see it say "There is one remaining learning card due today".  But since there is less than 60 seconds left of "today", there will never be a moment where I could actually access that card...   

In previous versions of Anki, once I was "done" for the day, that was it.  If I was done at 3pm, the deck would never "re-open" at 8pm because a card was scheduled for later in the same day.  I don't know if this is related to completely new scheduling behavior, but it did seem to me that Ankidroid was dismissing "again" cards much more quickly as I approached the cutoff (3am), where previous versions of Anki would have continued showing me the failed cards over-and-over, even if the intervals were pointlessly short.  (Such as constantly showing me the same card repeatedly till I marked it "Ok").

**Comment by BrayanDSO** [comment]
> "There is one remaining learning card due today". But since there is less than 60 seconds left of "today", there will never be a moment where I could actually access that card...

Have you assessed if this is the same behavior of Anki Desktop? Now that we can use part of the desktop code, this and a lot of other stuff come from there now, which includes its bugs

**Comment by david-allison** [comment]
* Related: https://github.com/ankidroid/Anki-Android/issues/14090

**Comment by briankrznarich** [comment]
I don't generally use Anki desktop for reviews, but since it sounds like it would be helpful, I'll make an effort to see if I can reproduce there.   Could take a bit to get the right timing window, but I will follow up if I can figure anything out. 

I mentioned that I noticed some near-the-cutoff scheduling changes with "again" cards.  I guess that is also down to the shared desktop code, and isn't the end of the world either way.  Since I never do reviews with the desktop app, I can't say off the top of my head if any of this matches the desktop behavior.   But I'll see what I can see...

**Comment by BrayanDSO** [comment]
> I'll make an effort to see if I can reproduce there.

I already reproduced by changing my rollover time to 40 minutes from now. So it is an upstream issue and should also be reported there

**Comment by david-allison** [comment]
I believe this should be closed, we'll ingest it when fixed upstream. Let me know if mistaken
