### ISSUE TITLE
confused bc am a biology stud

### ISSUE THREAD

**Issue by ronved** [ankidroid/Anki-Android#15428]
After years of idle, opened ankidroid to start reviewing but was prompted to update.
I reinstalled the latest version but my decks did not show up.
So, i clicked a backup from last year, but images did not show up despite collection media file intatct.
i did not sign in or sync bc mine has a large media collection.
what should i do?

**Comment by mikehardy** [comment]
If there is no backup and you have lost data then the lesson is to have a backup unfortunately: https://github.com/ankidroid/Anki-Android/wiki/FAQ#lost-my-cards

Without more details on what version you were on, what version you are on now, and how you reinstalled (did you opt to preserve data?) I can't say

If images aren't showing up, there are ways to try to figure out why - that may be possible to fix: https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

In general, even with a large media collection, I would make sure I had a backup off of my phone. Regardless of app updates you can always just have your phone stolen or drop it in water. AnkiWeb is the easiest way but you can also use Anki Desktop and it's built in local sync server to just keep a copy on your computer with sync on your local network.
