### ISSUE TITLE
Add Option to Display Custom Fonts

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#15425]
**Is your feature request related to a problem? Please describe.**

As it currently stands, you can not use custom fonts with anki with an exception of the reviewer. The device that I currently use do not support [Chữ Nốm script](https://en.m.wikipedia.org/wiki/Ch%E1%BB%AF_N%C3%B4m) (script using Chinese characters to write Vietnamese words). I can certainly use Chữ Nôm fonts for the reviewer; but in it's current state card browser etc. in Anki show rectangular boxes instead of the Chữ Nôm.
![Screenshot_2024-02-06-02-11-03-66_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/07f60b9c-8144-4929-b48e-1721ccc80836)

**Describe the solution you'd like**

Add the option to use custom fonts for Anki interface.

p.s. Funnily enough the device is chinese and they don't support Chữ Nôm lol

**Comment by briankrznarich** [comment]
Just a note, here's a ticket where dropping custom-font support was discussed:
Remove Custom Fonts setting #14343
and here's it is being removed:
Remove custom font feature #14476

As discussed on the other thread, I think this use case was just not known about when the decision was made to drop support.

**Comment by BroMandarin** [comment]
Just to add to this, I am similarly affected by this update as I used app-wide custom fonts for Japanese. So, +1 request to re-add the feature.

**Comment by brishtibheja** [comment]
This might solve the issue at #15938 as I never encountered rendering issues with app-wide custom fonts. It might also solve Japanese font rendering issues at #15775 without slowing down the study session.

**Comment by BrayanDSO** [comment]
As this is a feature request, please do it in the forums.
