### ISSUE TITLE
[BUG]: Xiaomi Force Dark Mode causing issues again

### ISSUE THREAD

**Issue by Kitsuta-le** [ankidroid/Anki-Android#15421]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

when I use AnkiDroid at night

### Expected behaviour

the card should be in the light theme

### Actual behaviour

the cards become black, but AnkiDroid is still in the light theme
![微信图片_20240206004308](https://github.com/ankidroid/Anki-Android/assets/88605687/07d4918a-c833-4031-972e-66ac2a62cb53)
![微信图片_20240206004338](https://github.com/ankidroid/Anki-Android/assets/88605687/a2ee7c86-cab2-4057-8eb3-38ab6ede0f99)
![微信图片_20240206004306](https://github.com/ankidroid/Anki-Android/assets/88605687/8be16543-c1a1-4f54-946a-3f2a5d3f15d5)
[cards.zip](https://github.com/ankidroid/Anki-Android/files/14168697/cards.zip)

### Debug info

```text
AnkiDroid Version = 2.17beta1 (ce6fef6f743f8b68c40608d85dd3fbc6b882d856)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = Xiaomi

Model = Redmi K20 Pro Premium Edition

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi K20 Pro Premium Edition Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/101.0.4951.61 Mobile Safari/537.36

ACRA UUID = 686abd27-3be0-4577-a979-827fe8ab0610

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Probably Xiaomi's "force dark" mode playing up again

**Comment by Kitsuta-le** [comment]
> Probably Xiaomi's "force dark" mode playing up again
That's it! I fixed it by canceling my phone's "force dark" mode on anki. But it is confusing why only these two templates will be affected.

**Comment by david-allison** [comment]
@Kitsuta-le, which screens are affected? Has this always occurred, or is it new?

Relevant code:

https://github.com/ankidroid/Anki-Android/blob/785711c918324982f72e0e9691671c431a6ae707/AnkiDroid/src/main/java/com/ichi2/anki/AnkiActivity.kt#L83-L85
