### ISSUE TITLE
[BUG]: TTS [ReadText] doesn't stop playing from previous card on new card

### ISSUE THREAD

**Issue by glokplopit** [ankidroid/Anki-Android#15423]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

When reviewing in the new version I noticed that on longer cards TTS does not automatically stop after you have reviewed unless the new card also has TTS on it. For example, I have a paragraph close on one and then an image on the next card. The card keeps reading the cloze text even tho I already answered that card and don't need it to finish reading the whole thing.

### Expected behaviour

The TTS audio should stop when the card it was generated from is no longer being reviewed/visible

### Actual behaviour

The TTS overlaps and plays on the new card rather than stopping

### Debug info

```text
AnkiDroid Version = 2.17beta1 (ce6fef6f743f8b68c40608d85dd3fbc6b882d856)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-S908U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S908U Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.230 Mobile Safari/537.36

ACRA UUID = c726ecdd-b2c4-4157-8b79-3fa5bf6a38a4

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@glokplopit Has this always been an issue in the 2.17 series (after TTS was implemented), or was it introduced recently?

**Comment by glokplopit** [comment]
@david-allison I believe it's new to the latest version, I can't say for certain what version I was using before but I believe it updated yesterday so I first noticed it doing reviews today

**Comment by glokplopit** [comment]
@BrayanDSO I found some more information about the ones that do the TTS overlapping that may be helpful. On the template of the card before I had manually specified the TTS like this:<tts service="android" voice= "en_GB">{{Answer}}</tts> then on the next deck it the template had no <tts> tag and it also had specified "don't speak" in the menu where you normally select the language to speak

**Comment by BrayanDSO** [comment]
In 2.17, we have added the same TTS scheme of Anki desktop ([docs](https://docs.ankiweb.net/templates/fields.html?highlight=tts#text-to-speech-for-individual-fields)).

Since my test used the new scheme, I believe that migrating to it should solve your problem. There are plans to deprecate the legacy TTS scheme, but it will be done gradually

**Comment by BrayanDSO** [comment]
Also, #15362 was shipped in beta2. This report is from beta1

**Comment by glokplopit** [comment]
@BrayanDSO Yes, changing to the new scheme worked. Thank you so much!

**Comment by david-allison** [comment]
Thanks! 

Closing as https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix as we'll be removing the old code, rather than fixing the issue.

**Comment by Anthropos888** [comment]
Can anyone explain how to fix this behavior?
I am using the old way to implement TTS:

<tts service="google" voice="en" class="none">
	<tts service="android" voice="en_GB">
	</tts>
</tts>

It worked great for the past 7 years, now no more :-(

What exactly do I need to use instead?

Thank you!

**Comment by david-allison** [comment]
More pervasive than thought. Let's block 2.17 on this.

`{{tts}}`: https://docs.ankiweb.net/templates/fields.html?highlight=tts#text-to-speech-for-individual-fields

**Comment by Anthropos888** [comment]
@david-allison 
Thanks. The TTS will correctly stop playing when using this code:
```
<tts service="google" voice="en" class="none">
	<tts service="android" voice="en_GB">
		{{tts en_GB:Englisch}}
	</tts>
</tts>
```

But it doesn't use the Android TTS voice that I setup in the Android Text-to-Speech menu.

The following will use the correct Android TTS voice but the TTS will not stop playing.

```
<tts service="google" voice="en" class="none">
	<tts service="android" voice="en_GB">
		{{Englisch}}
	</tts>
</tts>
```

So what's the trick to get the correct TTS voice AND stop TTS when showing the next card?

**Comment by david-allison** [comment]
```diff
- <tts service="google" voice="en" class="none">
-	<tts service="android" voice="en_GB">
		{{tts en_GB:Englisch}}
-	</tts>
- </tts>
```

Use `{{tts-voices:}}` to open a dialog to find the correct voice

**Comment by Anthropos888** [comment]
Ok, in my case, this fixes the issue:

```
<tts service="google" voice="en" class="none">
	<tts service="android" voice="en_GB">
		{{tts en_GB voices=com.google.android.tts-en-GB-language:Englisch}}
	</tts>
</tts>

```
1) it uses the correct Android voice
2) and TTS stops when showing the next card

**Comment by david-allison** [comment]
You don't need the `<tts>` any more, just the line which uses `{{tts}}` will do

**Comment by david-allison** [comment]
@glokplopit Could you export a deck which has this problem?

**Comment by david-allison** [comment]
Cause: mis-abstraction, and didn't stop the legacy TTS in the new TTS Player

https://github.com/ankidroid/Anki-Android/commit/ee5e26702ff55cd83a8dad5bbdab3550c27b26de#diff-7cd4e14b716b1bcd35f3cb3318da36eb706289a8e79658266d1f37d4ff8df796L178
