### ISSUE TITLE
[Bug] Deleting a note with a "type field" or a sound shows an incorrect preview 

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15443]
###### Reproduction Steps

1. Make a "type the answer" note 
2. Review it and Delete Note

###### Expected Result

The preview should contain a newline between the message and preview note data

`type` should be rendered

###### Actual Result

`[[type:Back]]`
![Screenshot_20240207_152705_AnkiDroid.jpg](https://github.com/ankidroid/Anki-Android/assets/62114487/2c953c48-1099-477f-9375-89e980f3d77c)

###### Debug info
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G991B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-G991B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.143 Mobile Safari/537.36

ACRA UUID = c6e5536e-6891-4fcb-876f-f4ab9c707ff9

Crash Reports Enabled = true

**Comment by BrayanDSO** [comment]
![image](https://github.com/ankidroid/Anki-Android/assets/69634269/bc309939-de57-4f49-a615-36a44de6ff4b)

**Comment by SanjaySargam** [comment]
Preview shows which is there on the front card.
If the front card contains an image/video/audio then in the preview what we have to show?
Just a text as Image/Video?Audio or something else?

**Comment by BrayanDSO** [comment]
Just remove special fields like `[[type:]]` and `[anki:play]` from the text (and html, if it isn't removed already)

**Comment by SanjaySargam** [comment]
Ok

**Comment by WPum** [comment]
Hi, is someone still working on this issue? If not I would like to give it a try.

**Comment by david-allison** [comment]
@SanjaySargam

**Comment by david-allison** [comment]
@SanjaySargam ; 

@WPum, Sanjay's typically active, but assume you can work on this 48 hours from this message if there's no reply

**Comment by SanjaySargam** [comment]
@WPum You can work on this.. I love to encourage new contributors

**Comment by WPum** [comment]
See #15956.
