### ISSUE TITLE
[Bug] CardBrowser: selecting the selected deck shows 'all decks' 

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15448]
Needs triage - had 'all decks' incorrectly selected

* Select a deck
* Select the deck again
* 'All decks' is shown in the title, even though the deck is still selected

**Comment by rohit9625** [comment]
How can I reproduce the issue?

**Comment by david-allison** [comment]
I'll take this one on. I introduced the bug and want to up the test coverage
