### ISSUE TITLE
Add scheduler/version status to debug info

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15447]
We want to know if the user is using FSRS when we get a debug report

https://github.com/ankidroid/Anki-Android/blob/5c75c820d6c2f262f104aad6ac088fc982ba9897/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/DebugInfoService.kt#L29-L52

**Comment by BrayanDSO** [comment]
Aren't people forced to use v3? And are there any FSRS-specific bugs?

**Comment by mikehardy** [comment]
Sounds like we need our personal superhero-without-a-cape --> @dae 😆

**Comment by david-allison** [comment]
We're only on V3 OR FSRS, FSRS has an additional version number

Knowing whether FSRS is enabled is useful for debugging scheduling issues.

Knowing the FSRS version is additional useful information

**Comment by BrayanDSO** [comment]
Until now, I haven't asked myself if any of our reported bugs were because of FSRS, hence my question. But if you feel that's useful, I'm okay.

**Comment by Giyutomioka-SS** [comment]
I would like to work on this !

**Comment by HarshalBhangale** [comment]
fun getDebugInfo(info: Context): String { 
    val webviewUserAgent = getWebviewUserAgent(info)
    val fsrsUsage = isUsingFsrs() // This is a hypothetical method you would need to implement
    return """ 
           AnkiDroid Version = $pkgVersionName (${BuildConfig.GIT_COMMIT_HASH}) 
            
           Backend Version = ${BuildConfig.BACKEND_VERSION} (${BackendBuildConfig.ANKI_DESKTOP_VERSION} ${BackendBuildConfig.ANKI_COMMIT_HASH}) 
           
           Android Version = ${Build.VERSION.RELEASE} (SDK ${Build.VERSION.SDK_INT}) 
            
           ProductFlavor = ${BuildConfig.FLAVOR} 
            
           Manufacturer = ${Build.MANUFACTURER} 
            
           Model = ${Build.MODEL} 
            
           Hardware = ${Build.HARDWARE} 
            
           Webview User Agent = $webviewUserAgent 
            
           ACRA UUID = ${Installation.id(info)} 
            
           Crash Reports Enabled = ${isSendingCrashReports(info)}

           FSRS Usage = $fsrsUsage
    """.trimIndent() 
}

To integrate an FSRS check, you would need to add a method or a check that can identify whether FSRS is active or being used in the user's current session. This might involve checking a configuration setting, a runtime condition, or a feature flag that indicates FSRS usage.

**Comment by mikehardy** [comment]
@HarshalBhangale that comment appears to be pretty low quality. Is that just the output a large language model pasted in to the comment box without a lot of editing?

**Comment by Haz3-jolt** [comment]
I'd like to work on this!
