### ISSUE TITLE
[Bug] "Search..." and "Clear history" in Settings cannot be translated

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#15453]
###### Reproduction Steps

1. Open settings
There is a search field and three dots where Clear history is placed

###### Expected Result

The strings can be translated

###### Actual Result

The strings cannot be translated to different languages

###### Debug info
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = samsung

Model = SM-A225F

Hardware = mt6769t

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A225F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.143 Mobile Safari/537.36

ACRA UUID = fc1a40d6-0d5b-4359-b9e5-298870da56f1

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
These are not provided by us

https://github.com/ByteHamster/SearchPreference

https://github.com/ByteHamster/SearchPreference?tab=readme-ov-file#translations

> This library currently contains only a limited number of translations. If you want to translate the texts shown by the library together with your app's other strings, you can just override the strings defined in lib/src/main/res/values/strings.xml in your own application by copying those lines to your app's strings.xml.

**Comment by david-allison** [comment]
I've submitted a patch to add these files.

Note: `clear history` will not be translated until an upstream bug in the library is resolved
