### ISSUE TITLE
[Bug] The color of 'Hide whiteboard' icon in App bar is not white

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15457]
###### Reproduction Steps

1. `Settings - Appearance - App bar buttons - Hide whiteboard - Always show` (default)
2. Open a deck
3. `Three dot icon - Enable whiteboard`
4. See `Hide whiteboard` icon in App bar

###### Expected Result
Its color is white, as the other icons.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/303b890e-078e-4163-84d8-aadba7efe84d)
(2.16.5)

###### Actual Result
Its color is not white.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/68e467dc-7a60-4641-8ea7-7af133187df8)

###### (Optional) Anything else you want to share?
The issue is observed in 2.17alpha2, too.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/0253fb68-2252-4eba-81f6-fb451cf1577f)
(2.17alpha2)

###### Debug info
```
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.143 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by shlok-2003** [comment]
Hey @snowtimeglass, I would like to work on this issue

**Comment by snowtimeglass** [comment]
You are welcome!

**Comment by neeldoshii** [comment]
Are you still working? @shlok-2003

**Comment by shlok-2003** [comment]
Hey @neeldoshii, Sorry for delay, I had my exams going on, I'll work on it asap and will submit it with 2 days

**Comment by neeldoshii** [comment]
> Hey @neeldoshii, Sorry for delay, I had my exams going on, I'll work on it asap and will submit it with 2 days

cool !! take your time no hurry.
