### ISSUE TITLE
[Bug][HEAD] After restarting App, Error reporting mode is automatically set to 'Never report'

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15468]
###### Reproduction Steps

1. `Settings` - `General` - `Error reporting mode` - select `Always report` 
   　<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/bc3ab426-aa6f-4792-b7d7-84da98e9b91d" width="300px">

    -  (_Optional_) Go back to the main screen if you want to do so
    　<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/cb3be228-d97c-42c9-ae92-469797446275" width="100px">

    -  (_Optional_) Again, `Settings` - `General` - see `Error reporting mode` if you want to make sure that the selected item has not been changed at this point
    　<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/bc3ab426-aa6f-4792-b7d7-84da98e9b91d" width="300px">
5. Close App
7. Start App
8. Again, `Settings` - `General` - see `Error reporting mode`

###### Expected Result
The selected item has not been changed from `Always report`. 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/bc3ab426-aa6f-4792-b7d7-84da98e9b91d)

###### Actual Result
The selected item has been changed to `Never report`.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/48858a55-010d-49a6-a729-08fd1dbb2a0d)

###### Video

https://github.com/ankidroid/Anki-Android/assets/10436072/2f59be3f-2c16-4606-8557-432355b55d2e

###### Debug info
AnkiDroid Version = 2.17beta2-debug (dff34ec905ca3755f85668aefd48e2a7dc31046d)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.143 Mobile Safari/537.36

ACRA UUID = f74d8c3b-b173-4337-ae0c-819d3934bd5e

Crash Reports Enabled = false

###### Anything else you want to share?
- This issue is _not_ occurred in 2.17beta2
- This issue is observed as of the commit of https://github.com/ankidroid/Anki-Android/commit/78ad3d6f85d878bec3839b750ccbd064f7abb16e

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) (**The issue is not yet occurred in the version**)

**Comment by david-allison** [comment]
This is a difference between `DEBUG` and `!DEBUG`: 

https://github.com/ankidroid/Anki-Android/blob/b44dcf49d5a410751ead0d29b7b3c90ccbfed965/AnkiDroid/src/main/java/com/ichi2/anki/CrashReportService.kt#L210-L224

**Comment by snowtimeglass** [comment]
Oh, so it is an intentional design for debug versions. Thank you for letting me know.
