### ISSUE TITLE
'Congratulations' screen with the message about 'the next learning card' won't switch back to Reviewer screen automatically

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15470]
###### Reproduction Steps

1. Open a deck
2. Answer "Again (x min)" to a card 
3. Answer to all the other cards in the deck
   (Then, "Congratulations!" screen with the message about learning card, for example, `The next learning card will be ready in 4 minute.`, gets shown.)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/de9db8e0-44ef-41e7-b9cd-49da4d44f0f5)
5. Wait the time indicated on the screen (or plus 1 minute at most).

###### Expected Result
Reviewer screen gets shown automatically, as it does so on Anki Desktop and AnkiMobile.

###### Actual Result
The "Congratulations!" screen with `The next learning card will be ready in 1 minute.` remains. The screen won't switched after that, too.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/ace47d29-47d6-4b92-8c70-16942217ceb1)

###### Debug info
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.143 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Related:

* https://github.com/ankidroid/Anki-Android/issues/14090
* #15412

We can use a similar technique to check on this screen

**Comment by BrayanDSO** [comment]
The whole screen will be reworked someday, and the effort/benefit ratio of this feature is relatively high, so I'll close this one.
