### ISSUE TITLE
[Bug] Image Occlusion seems to fail (Error: version mismatch)

### ISSUE THREAD

**Issue by daald** [ankidroid/Anki-Android#15478]
###### Reproduction Steps

1. Create an Image Occlusion card in Anki Desktop ⁨23.12.1 for Linux (just use the newest version, I think the windows version will do similar
2. Sync the card to anki server version 23.12.1 (using pip install anki)
3. Sync the card to ankidroid version 2.16.5 (installed from f-droid)

###### Expected Result
Card is shown in Android and looks similar as in the Desktop version

###### Actual Result
Ankidroid shows 
![Error in Ankidroid](https://github.com/ankidroid/Anki-Android/assets/2741537/a83dbc76-caf1-4690-957c-a6d6b3d374b4)

(the image is shown, but the occlusions are not shown. instead, there is the error message above)

> Fehler beim Laden der Bildverdeckung. Ist Ihre Anki-Version aktuell?

Translation (might have a different wording)
> Error while loading Image Occlusion. Is your Anki version up-to-date?

I think the error message is kind of wrong. I'm using the most up-to-date versions everywhere (Desktop, Server, Android). And I saw from a screenshot in #15235 that it worked in the past or under different conditions. Maybe the format changed in the Desktop version and is not supported yet in Ankidroid?

###### Debug info
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 12

ProductFlavor = full

Manufacturer = samsung

Model = SM-G970F

Hardware = exynos9820

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-G970F Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36

ACRA UUID = 6303914b-d808-4487-b461-a2284e932eb2

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
> I'm using the most up-to-date versions everywhere (Desktop, Server, Android).

The most up-to-date version currently is 2.17beta2, which has Image Occlusion and you can get it from the [github releases page](https://github.com/ankidroid/Anki-Android/releases) or by signing up to the beta rollout in the play store.
