### ISSUE TITLE
[BUG]: Apply a white fill color to the star icon when it is marked

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#15483]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to CardBrowser
2. Select cards
3. Click on the toggle mark

### Expected behaviour

star icon should fill with white color when it is marked

### Actual behaviour

star icon remains in the same color when either marked or unmarked

### Debug info

```text
AnkiDroid Version = 2.17beta2-debug (0ae68d23e062373c2168822f6d575c8506d682f6)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.143 Mobile Safari/537.36

ACRA UUID = 976ce503-d5bc-4973-a7a9-e295046b6cbf

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

https://github.com/ankidroid/Anki-Android/assets/65113071/fcc1ba63-6713-4dad-9da4-94a794c6a61b

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
Working on it

**Comment by david-allison** [comment]
We don't do this currently due to performance - it can be a slow query, as the user can select an infinite amount of cards/notes

I don't feel it's worthwhile to put the effort into making this fast while we're working on rewriting the browser, and there's already a large amount of issues to work on

**Comment by SanjaySargam** [comment]
Ok I'm closing this issue
