### ISSUE TITLE
[BUG]: Show Answer button is hidden when Type Answer box is selected

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15487]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Enable "Type Answer into the Card" in the Advanced Options.
- Review a card that requires typing the answer and select the typing box

### Expected behaviour

The `Show Answer` is always shown, even when the typing box is selected.

This is the case when the "Type Answer into the Card" option is disabled.
<img width="280" src="https://github.com/ankidroid/Anki-Android/assets/92206575/baeee405-1776-49aa-97f4-334ca5be2fe6">

The previewer behaves as expected even when the option is enabled.
<img width="280" src="https://github.com/ankidroid/Anki-Android/assets/92206575/5899931c-cd3c-433e-b2ef-5378640778c1">

### Actual behaviour

The "Show Answer" button is not seen when the typing box is selected.

<img width="280" src="https://github.com/ankidroid/Anki-Android/assets/92206575/c2565bd6-3ed9-41b3-8aa0-870f6b8ac9d7">
<img width="280" src="https://github.com/ankidroid/Anki-Android/assets/92206575/7852e4e8-ed53-46ef-8fde-ceac1666caf2">

### Debug info

```text
2.17 beta 2
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
Reproduced in 2.16.5

**Comment by CyberButton** [comment]
I would like to work on this one

**Comment by SanjaySargam** [comment]
@CyberButton Did you start working on it?
I know how to resolve this 
If you need any help ping me, I'm happy to help

**Comment by CyberButton** [comment]
@SanjaySargam Thanks for offering to help! I think I've found a solution, but I'd love your input on it. Please feel free to check it out and share any thoughts! https://github.com/ankidroid/Anki-Android/pull/15513
