### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by cameronj86** [ankidroid/Anki-Android#15494]
###### Reproduction Steps

1. Use full screen mode with app bar hidden.
2. Either navigate away from the app temporarily or interact with something outside of the app such as the settings of your device

###### Expected Result
The app bar should still automatically collapse after 1 to 2 seconds

###### Actual Result
The app bar becomes sticky and draws on top of the Anki results. The issue has occurred for a few months but I'm just getting around to loading a ticket after I realized that the beta version still does the same thing.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = Xiaomi

Model = 23043RP34C

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; 23043RP34C Build/UKQ1.230917.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Safari/537.36

ACRA UUID = 8711eb9c-f966-4714-bfcd-e6d8f3e84b82

Crash Reports Enabled = true
###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by cameronj86** [comment]
Here is a video example:
https://photos.app.goo.gl/aH6zwYwYmDdChEQW8

**Comment by criticalAY** [comment]
This looks like Anki-mobile not AnkiDroid

**Comment by BrayanDSO** [comment]
> This looks like Anki-mobile

It doesn't look like it at all. It is AnkiDroid

**Comment by BrayanDSO** [comment]
I'm joining this with #14152, since it is has the same root problem and will have the same solution
