### ISSUE TITLE
[Bug] Can't launch if Android is rooted 

### ISSUE THREAD

**Issue by Pigeonwang08** [ankidroid/Anki-Android#15506]
###### Reproduction Steps

1. Open my Anki on rooted Pixel AOSP(Android 13)
2. Wait a few seconds
3. The application can't run any more and it seems frozen. You can only shut down and then reopen it.But this problem will reproduct again.

###### Expected Result
Simply run

###### Actual Result
FROZEN APP

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

What's more
The solution is that as I add Ankidroid to Magisk's Configure Denylist, the problem will disappear and the program will run nicely.
I just want to know why it can't run with rooted Android,thx.

**Comment by david-allison** [comment]
Hi, could you post a logcat?

What version of AnkiDroid are you trying to run?

**Comment by david-allison** [comment]
Thanks, and a logcat?

https://developer.android.com/tools/logcat
