### ISSUE TITLE
[BUG]: the application does not detect new photos/screenshots from the gallery without restarting 

### ISSUE THREAD

**Issue by MeinongsJungle** [ankidroid/Anki-Android#15501]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Took a screenshotwhile I had another windows pulled up and then tried to add  a screenshot to the card, but it would not show up 

### Expected behaviour

This is an issue that slows down my workflow when I mine for words or create cards from presentsrions or screenshots. The newly created pictures that are downloaded or created when anki is open in the background are not getting included in the set of pictures to chose from when adding an image to a new card I'm tyring to create 

### Actual behaviour

Described above 

### Debug info

```text
N/A
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Works for me. Could you fill in the Debug Info and send a video?

Which Gallery app are you using?

**Comment by BrayanDSO** [comment]
Kinda of reproduced it by accident in the emulator:

[what.webm](https://github.com/ankidroid/Anki-Android/assets/69634269/691c6bee-80a0-45ae-bd96-c136aa48a0f6)

**Comment by BrayanDSO** [comment]
The images only showed up when I cold booted the emulator. Had tried to force-stop the app, but it didn't work
