### ISSUE TITLE
[Bug] CongratsPage not attached

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15515]
###### Reproduction Steps

1. Be in the congrats page
2. (Not sure) Leave the phone for a few minutes and come back
3. 

###### Expected Result

Everything stays normal

###### Actual Result

![Screenshot_20240215_071527_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/69634269/6219c646-c5e5-4e1b-9c3c-4011feca520f)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid version: 2.17beta2 

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = samsung

Model = SM-S911B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S911B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36

ACRA UUID = 16a4b4e6-91b3-4e44-b598-415c7b48a88d

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
I believe that this is some kind of process killing problem, and from the fact that a dialog was shown, I deduce that it is because of something inside a `launchCatching`

**Comment by david-allison** [comment]
Possibly `opChanges` related
