### ISSUE TITLE
[Bug]牌组选项---自动展示---两个等待时间参数的设置与调用混淆了

### ISSUE THREAD

**Issue by snnhqm** [ankidroid/Anki-Android#15517]
###### Reproduction Steps

1. 在AnkiDroid（版本2.17beta2）中打开任一牌组
2. 进入牌组选项设置
3. 检查自动展示项下的两个时间参数：自动答案前等待秒数、显示答案后自动执行操作前等待秒数
4. 运行Anki的自动展示动能

###### Expected Result
Anki在运行自动展示功能时，运行时间与牌组选项中设置的时间相一致

###### Actual Result
1、Anki在运行自动展示功能时，自动答案前等待的时间，实际是调用了牌组选项设置的显示答案后自动执行操作前等待秒数。
2、Anki在运行自动展示功能时，显示答案后自动执行操作前等待的时间，实际是调用了牌组选项设置的自动答案前等待秒数。

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/releases/tag/v2.17beta3
