### ISSUE TITLE
Add `Toggle auto advance` control/shortcut

### ISSUE THREAD

**Issue by justarmadillo** [ankidroid/Anki-Android#15519]
**Is your feature request related to a problem? Please describe.**

Sometimes during review you need to pause Auto Advance, unlike Anki desktop which I only click on shift+A to pause/resume the feature, on Ankidroid you need to exit the review session and toggle it, which is not practical at all.

**Describe the solution you'd like**
A button to switch Auto Advance like the Enable/Disable whiteboard feature during review.

**Describe alternatives you've considered**
x
**Additional context**
x

**Comment by david-allison** [comment]
It should be under `Settings - Reviewing`

**Comment by SanjaySargam** [comment]
I'd like to work on it
