### ISSUE TITLE
[BUG]: Auto Advance options are inverted

### ISSUE THREAD

**Issue by justarmadillo** [ankidroid/Anki-Android#15514]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

In deck options, when I set  Auto Advance settings for example to:
Seconds to show question for : 6.0 seconds
Seconds to show  answer for : 0.0 seconds

here, when I'm on the front side, it must flip to the backside after 6 seconds, but It is working in a reverse way, in this situation it don't do anything on the front side, but on the back side it performs the "Answer Action" after 6 seconds, and when I reverse them (question → 0.0 and answer → 6.0 seconds) it works on the front side (when I'm on front side it flips to the back side after 6 seconds)
on anki desktop everything is working perfectly, In Ankidroid those 2 options are flipped (inverted)

### Expected behaviour

Normally:
Seconds to show question for option → flips to the back side after time set
Seconds to show question for option performs the answer action

### Actual behaviour

Seconds to show question for option → runs on back side
Seconds to show question for option → runs on front side

they must be the reverse

### Debug info

```text
AnkiDroid Version = 2.17beta2 (2412d48c21a51aa13774618c051adbffec5f3d66)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = M2101K6G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; M2101K6G Build/TKQ1.221013.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36

ACRA UUID = 8e5bb1b6-7bcd-4797-83ce-37f048cfa3da

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
lol
