### ISSUE TITLE
[BUG]: Editing the tags from the Reviewer causes the app to hang

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15528]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Add a tag (or remove a tag) to a card from the Reviewer 

### Expected behaviour

No hang

### Actual behaviour

The app hangs

### Debug info

```text
2.17 beta 3
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
@david-allison, this may be related to https://github.com/ankidroid/Anki-Android/issues/15526

**Comment by david-allison** [comment]
Likely: da62d3036f2033c70c42407dfd29a9f3e2c9a4b3
* https://github.com/ankidroid/Anki-Android/pull/15477
* https://github.com/ankidroid/Anki-Android/pull/15477/commits/ef36c8dfc231c6ae7b92329e164c54f02d51bec4
