### ISSUE TITLE
[BUG]: Unable to edit note from the reviewer

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15526]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Start reviewing
- Open the menu and click `Edit note`
- Edit the note and press the `✓` button.

### Expected behaviour

The note is edited.

### Actual behaviour

The edits are discarded.

### Debug info

```text
2.17 beta 3
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
Probably a regression from #14949 (_feat: add "Edit" option to the new previewer_) @BrayanDSO 

https://github.com/ankidroid/Anki-Android/blob/bfbd1606c96ec92b2b5f8faaea16e46c7e1fca08/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.kt#L1009-L1012

**Comment by user1823** [comment]
I doubt such an old commit could be responsible. This issue was not present in beta 2.

**Comment by david-allison** [comment]
Almost certainly:

* https://github.com/ankidroid/Anki-Android/pull/15496

**Comment by user1823** [comment]
What is the best way to roll back to beta 2? Unlike Anki Desktop, trying to reinstall the older APK doesn't work if you have a later version already installed.

**Comment by user1823** [comment]
> Parallel.A/B for now.

The parallel version can't find my collection.

On the normal version, it is stored in the following directory.

/storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid

When I put this in the parallel build, I get a message saying "The path specified wasn't a valid directory."

The last time I rolled back to an earlier version, I did it by uninstalling the latest version and reinstalling the older APK (but I don't remember whether I had to download my collection from AnkiWeb or not).

> We'll get beta4 out later today. 

Thanks for the quick fix. I think that I will wait for the next beta in that case.

**Comment by david-allison** [comment]
`/storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid`

This is an app-private directory 

* (I believe): it won't allow downgrades without deleting data [this might just be an F-Droid issue]
* won't allow other apps (`Parallel.A`) to access the collection

So you'd need to redownload, sorry. Google's tied our hands here.

**Comment by mikehardy** [comment]
Yep, the general assumption for all future android data interaction is app-private data / other apps can't see it
Our parallel versions are fully separate apps from a system perspective
Which all implies - for a parallel version, you'll need a fully parallel collection downloaded from ankiweb or via export/import from some other main or parallel version (and yes, taking up twice the space...)

Google tied our hands but at the same time, privacy is a thing 🤷  app-private data is the future
