### ISSUE TITLE
Deck options asks 'Close and lose current input?' even if nothing is changed

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15548]
###### Reproduction Steps

1. Open Deck options
2. Tap Back button

###### Expected Result
The previous screen (Deck picker or Reviewer) is shown, as on 2.16.5

###### Actual Result
Dialog box is shown:
`Close and lose current input?`

It might be nice if it would not ask for it when nothing has been changed in the screen. (Note editor has the feature.) 

###### Debug info
2.17beta4

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Known issue, https://github.com/ankidroid/Anki-Android/issues/14438#issuecomment-1947399818
