### ISSUE TITLE
[BUG]: Answer comparison not shown when type answer into the card is enabled

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15552]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

- Enable `Advanced → Type answer into the card`
- Review a card that requires typing the answer.

### Expected behaviour

After clicking "Show Answer", the comparision of the typed and actual answers should be shown.

It is the case when the above-mentioned Advanced option is disabled.

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/e6837f86-7bb1-446c-b145-e71cf077eb1f"><img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/10a25106-0aa7-4007-b332-24c4c2eae521">

### Actual behaviour

Only the correct answer is shown.

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/9d65601e-42e3-4303-bd43-860cd05243bc">

### Debug info

```text
2.17 beta 4
```

### (Optional) Anything else you want to share?

This might be a long-standing bug.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
Introduced due to #15531

**Comment by david-allison** [comment]
The `EditText` is not styleable with css

**Comment by david-allison** [comment]
This is currently fixed either by:

* tapping outside the box before submitting
* submitting using 'enter'
