### ISSUE TITLE
White board compatibility with e-ink devices (Boox Brand)

### ISSUE THREAD

**Issue by A-misterious-tapir** [ankidroid/Anki-Android#15551]
AnkiDroid is really wonderful to work with, especially with E-ink devices. However due to their latency the white board is barely usable.

However, Onyx Boox released a SDK to allow third party apps to write smoothly : https://github.com/stevezuo/booxsdk (not sure if it is the official link tho)
Some apps like Onenote or Evernote already used it to enhance the compatibility with E-ink.

Therefore, I think that it would be amazing if you could also implement the compatibility with the whiteboard functionnality to enhance the learning experience.
I admit that it is a bit of a niche categorie of users, but if you have some extra time, it would be fantastic (and I would be really grateful).

**Comment by A-misterious-tapir** [comment]
Alright, alright I understand. At least I gave a shot.
I'll ask them for the license, in case someone want to work on this.
Thanks for your quick reply

**Comment by david-allison** [comment]
Thanks! I'm closing this as we can't work on it right now

Please feel free to update if you get a response! Closed doesn't mean locked
