### ISSUE TITLE
Remove `noCodeFormatting` preference

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15556]
the reason for this feature was:

* #7896

fixed by

* https://github.com/ankidroid/Anki-Android/pull/15540

**Comment by BrayanDSO** [comment]
![JustDoItShiaLaBeoufGIF](https://github.com/ankidroid/Anki-Android/assets/69634269/9208e4c1-bc3d-4d30-818a-bc4ff6d55824)

**Comment by david-allison** [comment]
Let's test against the polytonic greek in the example:

<img width="150" alt="Screenshot 2024-02-17 at 22 57 08" src="https://github.com/ankidroid/Anki-Android/assets/62114487/8b99dcf0-ff8d-4b41-ad85-363926155b3c">

Good to be removed

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/d9c891c0-46ce-4c80-b173-359f30e695ee)

**Comment by RobozinhoD** [comment]
I can do it!
