### ISSUE TITLE
Automatically highlight typing box in the reviewer

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15569]
If I enable `Advanced → Type answer into the card`, the typing box is not automatically highlighted when reviewing cards. So, I have to first click the box and then type the answer.

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/16f8c818-7ffb-471d-b8d5-2132517af0b3">

It makes sense to automatically highlight the box because the user is expected to type the answer. When the advanced option is disabled, AnkiDroid does highlight the box automatically.

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/ad9d84ec-f57c-40b1-9b3e-cec54fc6a32b">

~~I have not checked whether Anki automatically highlights the box or not.~~ Anki Desktop highlights the typing box automatically.

Additionally, adding a grey text that says "Type answer" in the box would make it look better.

**Comment by SanjaySargam** [comment]
What is the id of typing box ?

I'm just trying to use below code in onPageFinished to see whether it's works or not 
```javascript
            view.loadUrl("javascript:document.getElementsByName('')[0].focus();");
            view.requestFocus()
```

**Comment by user1823** [comment]
The auto-focus should respect the following advanced setting.

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/d755b504-8e5f-4e80-bd85-94f88fe105c3">

Also, this setting should not be hidden when "Type answer into the card" is enabled.

**Comment by SanjaySargam** [comment]
I agree

**Comment by david-allison** [comment]
If the functionality has been implemented, it shouldn't be disabled in the settings

**Comment by teobrigljevic** [comment]
Regarding @user1823's final suggestion 

> Additionally, adding a grey text that says "Type answer" in the box would make it look better.

I myself put custom placeholder text depending on the deck/type of card:

```
<script>
   (...)
   var answerInput = document.getElementById("typeans");
   if (answerInput !== null) { answerInput.setAttribute("placeholder", "{{Instructions}}"); }
   (...)
</script>
```

Example on desktop:
![anki-desktop](https://github.com/ankidroid/Anki-Android/assets/36804360/2fa38583-9b89-49b5-908e-6ea098da0808)

Example on Ankidroid:
![anki-ankidroid](https://github.com/ankidroid/Anki-Android/assets/36804360/ecf664fb-d20c-45c6-afda-459ac028dbad)


Any chance that this change keeps allowing me to set custom placeholders? I am no Android app programming expert, but I've deduced that there's a localized string that is used for the text box that pops up when enabling `Settings > Advanced > Workarounds > Focus 'type in answer'`, the `android:hint="@string/type_answer_hint"` in [reviewer_answer_buttons.xml](https://github.com/ankidroid/Anki-Android/blob/6739dbe8cb7475af8e1c34a5b0a076674e7d8c13/AnkiDroid/src/main/res/layout/reviewer_answer_buttons.xml).

Ideally the `typeans` field could take this localized string by default as wished by @user1823, but still allow custom placeholder replacement ?
