### ISSUE TITLE
There is no proper margin at the bottom of the privacy item list.

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15568]
###### Reproduction Steps

1. [General] - [Language] - [Deutsch]
3. [Help] - [Privacy]

###### Expected Result
There is a proper margin under the last item.

###### Actual Result
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/9c70b86e-4e54-4881-8b01-115551fea665)

The height of the box seems to be locked.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/bb647979-de8f-4330-9243-da5f041583c5)

###### Debug info
```
AnkiDroid Version = 2.17beta5 (a06d445bfcea3139accc30faa1b24c0fe214d2b0)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.165 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@lukstbit FYI
