### ISSUE TITLE
[Bug] Setting AnkiDroid directory: Keyboard did not appear

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15573]
Keyboard didn't appear when tapping  the EditText

AnkiDroid Version = 2.17beta4-debug (6d2f895133b8b7aab4e5dad1f335e07e778db5e5)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = amazon

Manufacturer = samsung

Model = SM-G991B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-G991B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36

ACRA UUID = 2a654e26-d91a-44e5-8362-cd37abcc042c

Crash Reports Enabled = false

**Comment by david-allison** [comment]
After reporting, the keyboard opened as expected

**Comment by BrayanDSO** [comment]
Close this?

**Comment by david-allison** [comment]
Created to log the issue. I'll close as it's not currently actionable
