### ISSUE TITLE
Ability to go directly to duplicate card

### ISSUE THREAD

**Issue by davegutteridge** [ankidroid/Anki-Android#15585]
When adding a new card to a deck, sometimes it will be for an entry that already exists. When this happens, the duplicate field is colored in pink. However, there is no way that I can see to then go directly to the note that already exists. One has to exit the "add card" interface, and go the "Card browser" interface and do a search. This involves even more steps when importing directly from other apps, such as "Jsho."

In the Anki desktop application for Windows, when adding a new note when a duplicate exists, the duplicate field is bordered in red, and a link appears above the field that says "Show Duplicates."

This ability to "Show Duplicates" via a direct link on the "Add" interface should also exist in Ankidroid. 

I am using Ankidroid to study Japanese, and I have thousands of words in my deck. I sometimes add a word I've already added, and when I do, I would like to find the existing card and add new context, such as an updated definition, or additional information.

Having a direct link to find duplicates in Ankidroid would greatly speed up this process.

**Comment by criticalAY** [comment]
I am taking it up

**Comment by david-allison** [comment]
Worth discussing this one, we want to replace the current Note Editor

**Comment by criticalAY** [comment]
Then, I think it would be best to wait. Even if introduce it now, will have to change the code later

**Comment by criticalAY** [comment]
Whatever fits the best I am okay with it

**Comment by david-allison** [comment]
Check in Discord, I'm not certain here, depending on how much time it takes

**Comment by BrayanDSO** [comment]
Closing in favor of #1377
