### ISSUE TITLE
Improve "discard changes" dialog options 

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15594]
If you click Add note and type something and then close the window without saving the changes, the following message pops up.

<img width=280 src="https://github.com/ankidroid/Anki-Android/assets/92206575/a329d0c1-776c-45c1-9de9-c52f012314fa">

This pop up also appears at other places (for e.g. when leaving the Deck Options page without clicking Save).

The issue with this pop up is that "OK" and "Cancel" don't seem to be the correct responses to a message that says "Close and lose current input".

What about using the following instead?

- Anki Desktop:
<img width=280 src="https://github.com/ankidroid/Anki-Android/assets/92206575/fd00012c-d7d6-4415-bde1-2c1655d6288c">

- Google Photos:
<img width=280 src="https://github.com/ankidroid/Anki-Android/assets/92206575/a753f8dd-3a37-4b47-8e1b-b0a958546faf">

**Comment by criticalAY** [comment]
Will use `TR` from backend

**Comment by criticalAY** [comment]
Good first issue, I have fixed it if anyone wants to drop a PR here's the patch
[string_from_backend.patch](https://github.com/ankidroid/Anki-Android/files/14331068/string_from_backend.patch)

**Comment by Giyutomioka-SS** [comment]
working on it
