### ISSUE TITLE
Anki-Android and Ankiweb session sharing for accessing shared decks 

### ISSUE THREAD

**Issue by kryptokazz** [ankidroid/Anki-Android#15593]
**Is your feature request related to a problem? Please describe.**
The Get shared decks links to the Anki webpage which allows you to download new APKG files directly to the Anki-Android I think this is a great feature however due to the way the Ankiweb restricts downloads unless you're signed in has become a problem as downloads are limited. 

**Describe the solution you'd like**
I'm wondering if there's a way to share session from Anki-Android to the Ankiweb so when you access the shared deck page you're automatically logged in and can download APKG files freely. 

Anki-Android could potentially integrate with AnkiWeb to allow users to log in directly from the app and access shared decks without restrictions. However, I'm guessing this would require coordination with the AnkiWeb team and might not be possible. 

**Describe alternatives you've considered**
Another way That might be possible is to download the webpage decks and maybe have them stored as a repository natively to Anki-Android I think this isn't ideal as you'd have to maintain a mirror of the AnkiWeb site which seems like a lot of work but at least would have a better user experience then not being able to download APKGs from the phone app without restrictions. 

**Additional context**
![image](https://github.com/ankidroid/Anki-Android/assets/92654627/58fa7bbd-cdad-40d4-8da9-2b84930f8aab)

**Comment by david-allison** [comment]
Improved in https://github.com/ankidroid/Anki-Android/pull/15023, this is in the 2.17 beta

* https://github.com/ankidroid/Anki-Android/pull/15023
