### ISSUE TITLE
TTS: Can we default to Android's default TTS speed

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15598]
(Also, does the new text to speech ignore the speed setting of Android’s text to speech feature? I had to add the speed modifier to the template.)

_Originally posted by @mfmeulenbelt in https://github.com/ankidroid/Anki-Android/issues/15475#issuecomment-1952206539_

**Comment by david-allison** [comment]
Related code

https://github.com/ankidroid/Anki-Android/blob/d8dcf7e983cf0aaca232d687da6ff8ca024a0eeb/AnkiDroid/src/main/java/com/ichi2/anki/AndroidTtsPlayer.kt#L107-L109

Removing this code 

The Anki backend sends `speed` as a `Float` with a value of `1` as a default, it doesn't seem feasible to differentiate between a missing `speed` and a `speed` of 1.

As a current workaround, we can treat a `speed` of 1 as "use system"

----

@dae [low priority] is it feasible to make `TTSTag.speed` optional:

https://github.com/ankitects/anki/blob/9642a69b88a4cf631af23d49e08df9b918deee8b/proto/anki/card_rendering.proto#L60-L66

**Comment by dae** [comment]
It's possible, but easiest if use use 1=auto. Users who want 1 and not auto, if they exist, could use something like 1.01 instead.
