### ISSUE TITLE
Language voices get installed unintentionally from 'TTS voices settings'

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15596]
###### Reproduction Steps

1. Tap `Open TTS voices settings`

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/c6f1105f-201f-4ebd-ab26-144286c61fcf" width="320px">

3. Tap `Install`
4. Tap a language item
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/01adc867-0971-4607-b266-61f0174a2c84" width="320px">

###### Expected Result
I expect this operation doesn't cause installing the language voice.

###### Actual Result
The selected language voices are erased from the list. 
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/b1927653-1832-479c-a44c-c2ab279ffe80" width="320px">

(Tap `Install` again to go back to the installed language screen.)
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/e9e515aa-d7a3-4818-b357-bfd86cae4d95" width="320px">
They seem to get downloaded and installed.

https://github.com/ankidroid/Anki-Android/assets/10436072/25f3a7c7-d66a-4c39-b79c-3131a43af4cc

I'm not sure, but I'm wondering if this result is as intended. 

Sorry if I have misunderstood.

###### Debug info
AnkiDroid Version = 2.17beta5 (a06d445bfcea3139accc30faa1b24c0fe214d2b0)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.165 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Auto downloading the voices /should/ be the default behaviour, but Android's TTS is buggy and often doesn't download the voices

If it's a bad user experience, we can look into changing this

**Comment by david-allison** [comment]
Thanks!

I suspect we'll want to introduce a wizard for TTS. Matching Anki desktop is fine as a first pass

**Comment by BrayanDSO** [comment]
Hi there. We are migrating enhancements and feature requests into Anki forums in order to have a better experience for the reporters, and get a more focused and triaged space in Github for the devs.

I hereby ask to post the request on the [forums](https://forums.ankiweb.net/c/suggestions/17) so more people can give opinions there. Sorry for the extra wor
