### ISSUE TITLE
[Bug] Can't update Image Occlusion content from Card browser (by normal steps)

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15609]
###### Reproduction Steps

1. Edit an Image Occlusion content in a note from Card browser (_not_ from Reviewer screen -> `Edit note`)

    [Before]
    <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/a12b5eeb-e835-44e7-afb0-53548e17824c" width="320px">

    [After]
    <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/a2ccf026-ec6f-4d9b-b574-60ce6d446ab3" width="320px">
2. Tap `Update`
    <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/ecf70977-636f-407a-b8db-4350044ed8c5" width="320px">
    (Then, Card browser list screen gets shown)
2. See the Image Occlusion content again
   - You can do this step from Reviewer screen as well.

###### Expected Result
The content has been updated.
    <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/c2152d81-c5c7-46e7-991d-6c9e929e5ff2" width="320px">

###### Actual Result
The content is not updated.
    <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/53fbd098-c38a-468d-9adc-f1d261dbf7ce" width="320px">

###### Note
After that, users can "restore" the [After] content by `Undo Update Note` action, this is an unexpected operation in this situation though.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/e40be304-e686-4297-9e4f-56a3d23158a4" width="320px">
###### Video
https://github.com/ankidroid/Anki-Android/assets/10436072/1917289e-290d-43ca-a904-47ec31e0ec96

###### Debug info
AnkiDroid Version = 2.17beta6 (c17fed63b97a464484f7ee465057ff251f54007f)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.165 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by CyberButton** [comment]
I would like to work on this one

**Comment by mikehardy** [comment]
Possibly related / duplicate #15542

**Comment by david-allison** [comment]
Cause: https://github.com/ankidroid/Anki-Android/blob/5659b80603aec7a16d212a9a12611479614db16c/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt#L175

Removing the line fixes the issue, but care would need to be made to ensure that the Note Editor continues to save a normal note

**Comment by CyberButton** [comment]
> I would like to work on this one

sorry, I got sick(
