### ISSUE TITLE
[Bug] Can't save audio by "Record audio" feature once "Check pronunciation" feature is used

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15601]
###### Reproduction Steps

1. Open a card
2. Do `Check pronunciation` action 
3. (After that, it doesn't matter if you have it on, off, or move to another card.)
4. `Edit note`
5. Clip icon > `Record audio` (or Clip icon > three dots icon > `Audio recording`)

###### Expected Result
The right side blue icon is for "Save"
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/ed63b3cd-66a3-4e12-a7c8-6ec70c1c4cff" width="320px">

###### Actual Result
The right side blue icon is for "Check", and works so.

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/ac34210c-6b48-4d3c-86e8-b33cc02a7cff" width="320px">

###### Debug info
AnkiDroid Version = 2.17beta5 (a06d445bfcea3139accc30faa1b24c0fe214d2b0)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.165 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@criticalAY

**Comment by david-allison** [comment]
I'll propose moving this to 2.17.1

**Comment by criticalAY** [comment]
I'll fix it asap
