### ISSUE TITLE
Can't see nor edit `Comments` field in Image Occlusion note

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15610]
In Image Occlusion editor ('Note' mode) on AnkiDroid, `Comments` field isn't shown. 

- Anki Desktop
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/a91d8694-ddcd-4863-8174-19f4a5d5da1c)

- AnkiDroid
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/56e71825-fc00-4efc-9871-cf3caab17957)

###### Debug info
AnkiDroid Version = 2.17beta6 (c17fed63b97a464484f7ee465057ff251f54007f)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.165 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by krmanik** [comment]
It is not available in AnkiMobile also, the note editor is minimal version of Anki note editor. In future desktop note editor will included in all Anki client.

**Comment by snowtimeglass** [comment]
@krmanik 

> It is not available in AnkiMobile also

Sorry, I may still not understand correctly what you are referring to.

The `Comments` field seems to be available in AnkiMobile...
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/38fd15ef-d951-4f31-98e6-68448370ccd8)

**Comment by krmanik** [comment]
In earlier screenshot the comments fields are not available in mobile client but in latter screenshot Comments are available. The fields need to be shown instead of hidden in case of AnkiDroid.

**Comment by snowtimeglass** [comment]
@krmanik 
Ah, thank you. I understand what you mean and you're right. (Thank you, too @abdnh) 


AnkiDroid

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/7f596443-1949-4859-90f5-564ce3941639" width="300px">
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/d4fd9174-d3c8-4f83-b850-b15b33401146" width="300px">

********


AnkiMobile

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/db5d76e3-1727-4847-a308-c5b5ae0d3376" width="300px">
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/54f9e83c-7dd3-4b4d-8998-9fba99490b96" width="300px">

********

>The fields need to be shown instead of hidden in case of AnkiDroid.

I agree. Aside from how important or not the Comments field is, I think it would be desirable to show the non-Occlusion fields (Header, Back Extra, Comments) on the screen before the IO editor, as the layout would be consistent with the "Edit Occlusions" button.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/c02d180e-3355-411a-81ed-646fd1b970b8)
