### ISSUE TITLE
[BUG]: Card Browser Deck Search - Keyboard does not appear

### ISSUE THREAD

**Issue by Nerdywriter09** [ankidroid/Anki-Android#15613]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

When card browser is opened --dropdown arrow to shift among decks-- deck search --🔍 icon is pressed--Keyboard does not popup

https://github.com/ankidroid/Anki-Android/assets/160796992/1943ebd0-9703-426c-8204-e21f31131926

### Expected behaviour

The keyboard should popup so that one can type and search a particular deck

### Actual behaviour

So once i opened the Card browser and then went on to search among decks and by clicking on the dropdown arrow and then went on to hit the 🔍 icon no keyboard popped up
![IMG_20240222_045506](https://github.com/ankidroid/Anki-Android/assets/160796992/8db2b9a4-365a-449d-80fb-08ff1206d56a)

### Debug info

```text
AnkiDroid Version = 2.17beta6 (c17fed63b97a464484f7ee465057ff251f54007f)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = vivo

Model = I2217

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; I2217 Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.164 Mobile Safari/537.36

ACRA UUID = 482093c6-382c-4f1e-85e5-3c76bc4506e4

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Bisecting:

```
ccd62472708b33d626b64af675a92ac9e04994b2 is the first bad commit
commit ccd62472708b33d626b64af675a92ac9e04994b2
Author: Neel Doshi <60827173+neeldoshii@users.noreply.github.com>
Date:   Thu Feb 8 20:40:26 2024 +0530

    Deck SelectionDialog now uses Alert Dialog (#15431)

 .../com/ichi2/anki/dialogs/DeckSelectionDialog.kt  | 28 ++++++++++++----------
 1 file changed, 15 insertions(+), 13 deletions(-)
➜
```
