### ISSUE TITLE
Don't block user from leaving the app if `Automatic sync` is enabled

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15624]
If the user has `Automatic sync` enabled and tries to leave the app after some time, they will need to wait the collection to synchronize before leaving, which IMHO is annoying.

The option that I suggest is to start the sync on the background (with a notification) so the user can leave the app immediately, and show a ProgressDialog/block the app like before if they open the app before the collection sync is complete

**Comment by mikehardy** [comment]
agreed on this one
