### ISSUE TITLE
[BUG]: The currentTime method can set the start position of an audio

### ISSUE THREAD

**Issue by luohuichang** [ankidroid/Anki-Android#15631]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

The currentTime method can set the start position of an audio, which does not work in the current version (2.17.0) anymore. 

```
<audio id="audio" src={{mp3}} controls controlsList="nodownload"  preload="auto">

<script>
document.getElementById("audio").currentTime=300
document.getElementById("audio").play();
</script>
```

### Expected behaviour

Play from 300 seconds

### Actual behaviour

Play from 0 seconds（the beginning）

### Debug info

```text
AnkiDroid Version = 2.17.0 (af526585a5270c75db3f6b892d00035ad1ab17e0)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 12 (SDK 31)

ProductFlavor = full

Manufacturer = HUAWEI

Model = NOH-AN00

Hardware = kirin9000

Webview User Agent = Mozilla/5.0 (Linux; Android 12; NOH-AN00 Build/HUAWEINOH-AN00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = 08e625d4-35b6-480e-a91c-992f66f55712

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

In the previous version (2.16.0) worke well.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Could you please share a sample deck with this problem that would help us reproduce the issue?

You can sent it here as a zipped file. Or in my e-mail if you don't want to share it publicly: brayandso.dev@gmail.com

**Comment by BrayanDSO** [comment]
> personal bet: issue is caused because the base url of the reviewer isn't the media directory anymore

bingo, that's it.

While we solve this, which may take some time, if you only use AnkiDroid to review cards, what you can do to solve your issue is:

1. Copy your AnkiDroid directory at `Settings - Advanced - AnkiDroid directory`
2. Before in your template `{{mp3}}` add `file://` + `the AnkiDroid directory you copied` + `collection.media/`

Here's an example

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/55eca33e-4d19-4ddf-9ecf-7fe437e18665)

**Comment by BrayanDSO** [comment]
The possible solutions I see are:

1. Send partial content in shouldInterceptRequest, like #15037, which I tried and works
2. Change the `src=""` requests to use direct `file:///` protocol, which is wayyy more performant. The way I thought was via javascript
3. Both to cover possible corner cases of the second approach
