### ISSUE TITLE
Hierarchical menu in browser for selecting deck

### ISSUE THREAD

**Issue by salmanuc** [ankidroid/Anki-Android#15646]
**Is your feature request related to a problem? Please describe.**
No hierarchical menu in browser for selecting deck
![Screenshot_2024-02-24-23-34-00-37_a9eef3a2a561b80d5c76daebd0f9a14c.jpg](https://github.com/ankidroid/Anki-Android/assets/138794113/99e47b91-3ffb-410b-96dc-4847ea981cfc)

**Describe the solution you'd like**
Hierarchical menu in browser for selecting deck as it has been implemented for tags
![Screenshot_2024-02-24-23-37-02-83_a9eef3a2a561b80d5c76daebd0f9a14c.jpg](https://github.com/ankidroid/Anki-Android/assets/138794113/eb9cfc8c-d9fd-4709-b13e-fcc446755504)

**Describe alternatives you've considered**
Manually scroll down or search

**Additional context**
Also add feature so that the last opened or the way tags in hierarchy have been opened remain so and do not collapse everytime the filter by tag option is selected.

**Comment by josephShokry** [comment]
@david-allison kindly assign this issue to me.
