### ISSUE TITLE
Improve Amazon Listing Description

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15654]
> as an aside the Amazon store still lists:
>  spaced repetition (supermemo 2 algorithm)

- comment on reddit

**Comment by pradyuman04** [comment]
can you please tell me in detail what to improve?

**Comment by david-allison** [comment]
The description hasn't been updated in a long time. 

We should update the description and https://github.com/ankidroid/Anki-Android/blob/main/docs/marketing/localized_description/marketdescription.txt to include FSRS, as well as any new features which have been added to AnkiDroid in the past decade
