### ISSUE TITLE
Copy all in Note type

### ISSUE THREAD

**Issue by NameLessGO** [ankidroid/Anki-Android#15669]
**Is your feature request related to a problem? Please describe.**
I want users to debug note types by copying the info in Front, Back and Style more easily

**Describe the solution you'd like**
`Edit Note > Cards:Note type name > Note type`

Want a button next to the note type name called: Copy all

**Describe alternatives you've considered**
The current alternative is selecting the initial and dragging until the end then copying, this can be troublesome for note type with a lot of functions, Enhance cloze 2.1 alone takes 25s to reach the bottom

If possible: add '''copied content''' to automatically display in preformatted text

**Additional context**
![image](https://github.com/ankidroid/Anki-Android/assets/66227691/d104e353-5f00-4779-bbfd-66230160e398)

https://forums.ankiweb.net/t/lingq-cards-not-displaying-the-question-term-the-question/41626/5

**Comment by BrayanDSO** [comment]
Have you tried the `Select all` option in the context menu? Works wonders here

**Comment by NameLessGO** [comment]
Forgot about it 🤡
