### ISSUE TITLE
The following code for determining and "clicking" the button "good" stopped working in 2.17.0

### ISSUE THREAD

**Issue by Andrej-Adamenko** [ankidroid/Anki-Android#15660]
May be better implementation for this. Check for all available buttons, if all available then call third button, else call second button.
```html
<script>
    function goodButton() {
        if (AnkiDroidJS.ankiGetNextTime1() && AnkiDroidJS.ankiGetNextTime2() && AnkiDroidJS.ankiGetNextTime3() && AnkiDroidJS.ankiGetNextTime4()) {
            // Again / Hard / Good / Easy

            buttonAnswerEase3();

        } else if (AnkiDroidJS.ankiGetNextTime1() && AnkiDroidJS.ankiGetNextTime2() && AnkiDroidJS.ankiGetNextTime3() && !AnkiDroidJS.ankiGetNextTime4()) {
            // Again / Good / Easy                                                                                       ^^^^ Note: not

            buttonAnswerEase2();

        } else if (AnkiDroidJS.ankiGetNextTime1() && AnkiDroidJS.ankiGetNextTime2() && !AnkiDroidJS.ankiGetNextTime3() && !AnkiDroidJS.ankiGetNextTime4()) {
            // Again / Hard                                                           ^^^^^                               ^^^^ Note: not

            buttonAnswerEase2();

        }
    }
</script>
```
Check it may be helpful. I have use this to hide custom designed button to show and hide.
https://github.com/infinyte7/Anki-Custom-Card-Layout/blob/master/Example%204/front.html#L223-L247

_Originally posted by @krmanik in https://github.com/ankidroid/Anki-Android/issues/7307#issuecomment-700962144_

**Comment by david-allison** [comment]
The API went through breaking changes. See https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#responses for how to set this up

Closing as answered, but please follow up if necessary

**Comment by Andrej-Adamenko** [comment]
> The API went through breaking changes. See https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#responses for how to set this up
> 
> Closing as answered, but please follow up if necessary

Sorry, but I still do not understand how to write a code to click the "Good" button. The code above worked in the previous version. Can I update the code, so it works in both the previous and the new version? How?

**Comment by david-allison** [comment]
The API has completely changed, therefore I don't believe it's possible to run code for either 2.16.5 or 2.17.0

You posted on the previous issue asking about updated code, that's likely the best way if you're not a developer

**Comment by krmanik** [comment]
> Sorry, but I still do not understand how to write a code to click the "Good" button. 

Following will work on 2.17.

```js
    var jsApiContract = { version: "0.0.2", developer: /* your email here */ };
    var api = new AnkiDroidJS(jsApiContract);

    function goodButton() {
        if (api.ankiGetNextTime1() && api.ankiGetNextTime2() && api.ankiGetNextTime3() && api.ankiGetNextTime4()) {
            // Again / Hard / Good / Easy

            buttonAnswerEase3();

        } else if (api.ankiGetNextTime1() && api.ankiGetNextTime2() && api.ankiGetNextTime3() && !api.ankiGetNextTime4()) {
            // Again / Good / Easy                                                                                       ^^^^ Note: not

            buttonAnswerEase2();

        } else if (api.ankiGetNextTime1() && api.ankiGetNextTime2() && !api.ankiGetNextTime3() && !api.ankiGetNextTime4()) {
            // Again / Hard                                                           ^^^^^                               ^^^^ Note: not

            buttonAnswerEase2();

        }
    }
```
