### ISSUE TITLE
[Question]: How to deal with difference between globalThis behaviour in card templates on AnkiDroid vs desktop

### ISSUE THREAD

**Issue by jhhr** [ankidroid/Anki-Android#15665]
I've been banging my head on trying to implement some complex js file importing in my card template and it works on desktop but not on AnkiDroid.

I'm using the code suggested here: https://github.com/ankidroid/Anki-Android/issues/9098#issuecomment-872090066

It does work in AnkiDroid, if I run the import on both the front and back of the card.

It appears to me that `globalThis` behaves differently on AnkiDroid compared to desktop:
- Setting values like `globalThis.myCustomValue` on desktop works to transport values from the card front to the back and also to the next review.
- However, on AnkiDroid it appears that such values are lost on moving to the card back.

For example this code will work to increment a value on desktop between reviews but it only show `1` each time on AnkiDroid:
 ```
 globalThis.increment = globalThis.increment || 0;
  globalThis.increment++;
  // Create element to display globalThis content
  var globalThisContent = document.getElementById('globalThis-content');
  if (!globalThisContent) {
    globalThisContent = document.createElement('div');
    globalThisContent.id = 'globalThis-content';
    globalThisContent.style.cssText = 'position: fixed; top: 20; left: 0; max-height: 500px; overflow-y: auto; padding: 10px; background-color: #333; color: #fff; border: 1px solid #ccc; z-index: 1002;';
    document.body.insertBefore(globalThisContent, document.body.firstChild);
  }
  globalThisContent.innerHTML = 'globalThis.increment: ' + globalThis.increment;
```

**Question**
Is there some other persistent way to store variables on AnkiDroid or do I just have to live with having to import files on every review in AnkiDroid instead being able to import once and store them in a variable for the whole review session?

And perhaps... could this behaviour be made consistent with the desktop one?

**Comment by BrayanDSO** [comment]
Probably relevant to you: #4828

Solving that is on the works, but will take time

**Comment by jhhr** [comment]
> Probably relevant to you: #4828
> 
> Solving that is on the works, but will take time

Thanks, that thread pretty much answers my question about there being another way as "no" and that I'll need to live with having to make more code to manage the difference in behaviour for the time being.

**Comment by BrayanDSO** [comment]
I use `sessionStorage` for a notetype that I have, and it works well for my use case (storing a variable from question to answer of the same card)

There is a JavaScript snippet called Anki persistence IIRC, which you probably can find with a quick google (also IIRC, it is used in the Anking notetypes Addon)

**Comment by david-allison** [comment]
https://github.com/SimonLammer/anki-persistence?tab=readme-ov-file#anki-persistence

**Comment by jhhr** [comment]
Thanks for the link to anki-persistence. It hadn't occurred to me to try sessionStorage. Though this might not be the solution to my problem which was to store large javascript functions loaded from files in the collection media folder. 

Because the value needs to be stored as a string and then parsed back as an object on each load of the card front/back, any performance improvements on loading cards may be moot. I didn't test it yet, but I imagine parsing several hundred lines worth of javascript as a string in `sessionStorage` might be only slightly faster (or maybe slower?) as just having that javascript inline in the card template.

**Comment by BrayanDSO** [comment]
Closing this in favor of #4828
