### ISSUE TITLE
Permissions Screen: Toggle does not work

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15661]
This appears to be a separate issue with 2.17: nothing happens when the toggle button is pressed.

----

Same issue @ Pixel 4a, Android 13, app wouldn't boot. When installing latest 2.17alpha14, I then get this screen when booting : 

<img width="353" alt="image" src="https://github.com/ankidroid/Anki-Android/assets/2840135/e8c252aa-2aab-41be-9027-35eaa7a56bab">

What is weird : 
1- I don't recall ever having that specific permission screen before on my phone.
2- Whenever the toggle is used, dragging or clicking, it directly get back to "off". It cannot be activated.
3- All permissions [when going to "App permissions" in my app settings] I can give on my phone to AnkiDroid are given. The closest seems to be it is "Read and write to the AnkiDroid database". Others are Microphone and notifications...

Thanks !

_Originally posted by @TheMadSword in https://github.com/ankidroid/Anki-Android/issues/14423#issuecomment-1879953515_

**Comment by joschsch** [comment]
Same issue with Pixel 6 Pro, Android Version 14. Happy to help with logs, though I would need to get a pointer what to do. I understand i would need to do it like this: https://www.airdroid.com/mdm/view-android-logs/ If there are other ways (or only these described in the article), let me know how and what you need and I will try to do it.

**Comment by david-allison** [comment]
The section marked "How to use Android Debug Bridge (ADB) to view android logs" is excellent.

I believe you're just going to need to provide the logs for `com.ichi2.anki`

**Comment by david-allison** [comment]
Relevant

https://github.com/ankidroid/Anki-Android/blob/60e7308c1763b0365f4f21a57d659855c892e3b7/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/Full30and31PermissionsFragment.kt#L44-L46

https://github.com/ankidroid/Anki-Android/blob/223f61b9aaabfd6c055d4b8c41f74410a2d7947f/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsFragment.kt#L69-L84

**Comment by joschsch** [comment]
> The section marked "How to use Android Debug Bridge (ADB) to view android logs" is excellent on the link above.
> 
> Please let me know if you encounter any issues with the instructions.
> 
> When you have logcat running, I believe you're just going to need to provide the logs for `com.ichi2.anki`

`02-25 15:17:53.488  2066  2090 V WindowManagerShell: Transition requested: android.os.BinderProxy@3350d26 TransitionRequestInfo { type = 1, triggerTask = TaskInfo{userId=0 taskId=87327 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.ichi2.anki/.IntentHandler } baseActivity=ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker} topActivity=ComponentInfo{com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity} origActivity=null realActivity=ComponentInfo{com.ichi2.anki/com.ichi2.anki.IntentHandler} numActivities=3 lastActiveTime=3297543 supportsMultiWindow=true resizeMode=2 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@8fc5d67} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 145 - 0, 0) topActivityInfo=ActivityInfo{c935714 com.android.permissioncontroller.permission.ui.GrantPermissionsActivity} launchCookies=[android.os.BinderProxy@20b0343] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false isTopActivityTransparent=true locusId=null displayAreaFeatureId=1 cameraCompatControlState=hidden}, remoteTransition = null, displayChange = null, flags = 0 }
02-25 15:17:53.538  1652  1754 V WindowManager: Sent Transition #150 createdAt=02-25 15:17:53.483 via request=TransitionRequestInfo { type = 1, triggerTask = TaskInfo{userId=0 taskId=87327 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.ichi2.anki/.IntentHandler } baseActivity=ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker} topActivity=ComponentInfo{com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity} origActivity=null realActivity=ComponentInfo{com.ichi2.anki/com.ichi2.anki.IntentHandler} numActivities=3 lastActiveTime=3297543 supportsMultiWindow=true resizeMode=2 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{RemoteToken{eea9252 Task{fa8762e #87327 type=standard A=10296:com.ichi2.anki}}} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 145 - 0, 0) topActivityInfo=ActivityInfo{d0af7a9 com.android.permissioncontroller.permission.ui.GrantPermissionsActivity} launchCookies=[android.os.BinderProxy@9fb6e20] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false isTopActivityTransparent=true locusId=null displayAreaFeatureId=1 cameraCompatControlState=hidden}, remoteTransition = null, displayChange = null, flags = 0 }
02-25 15:17:53.568  1652  3941 I ImeTracker: com.ichi2.anki:8154567f: onRequestHide at ORIGIN_SERVER_HIDE_INPUT reason HIDE_UNSPECIFIED_WINDOW
02-25 15:17:53.568  1652  3941 I ImeTracker: com.ichi2.anki:8154567f: onCancelled at PHASE_SERVER_SHOULD_HIDE
02-25 15:17:57.589 26764 26772 I com.ichi2.anki: Background concurrent mark compact GC freed 194446(10MB) AllocSpace objects, 40(2060KB) LOS objects, 81% free, 5641KB/29MB, paused 468us,2.681ms total 125.530ms
02-25 15:17:57.591 26764 26774 W com.ichi2.anki: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~ZPnDBwFlrJ1RHbnJTYcpAg==/com.google.android.webview-pMNXZgaPsiAC0l4tUb-G1A==/base.apk' with 1 weak references
02-25 15:17:57.592 26764 26774 W com.ichi2.anki: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~ZPnDBwFlrJ1RHbnJTYcpAg==/com.google.android.webview-pMNXZgaPsiAC0l4tUb-G1A==/split_config.de.apk' with 1 weak references
02-25 15:17:57.592 26764 26774 W com.ichi2.anki: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~ZPnDBwFlrJ1RHbnJTYcpAg==/com.google.android.webview-pMNXZgaPsiAC0l4tUb-G1A==/split_config.en.apk' with 1 weak references
02-25 15:17:57.592 26764 26774 W com.ichi2.anki: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~T5RMlANJOFPZqOdyFJDjSQ==/com.google.android.trichromelibrary_616717833-SKNlpsyB3cHnBJP3LNzo1g==/base.apk' with 1 weak references
02-25 15:17:57.592 26764 26774 W com.ichi2.anki: ApkAssets: Deleting an ApkAssets object '<empty> and /data/app/~~X5Nzwmy_5ANrJ2Vi-dgtEw==/com.google.android.tts-gZuzL3stNuvuBA4sJZeS2Q==/base.apk' with 1 weak references`


This is what gets logged when I open the app, the screen with the prompt opens, I try to turn the switch once and nothing else happens.

Let me know if you need more

**Comment by david-allison** [comment]
Is anything more logged after the switch is pressed?

**Comment by david-allison** [comment]
Relevant logs.

No clue why this is happening, but we can detect it by a very quick `onPause` -> `onResume` cycle

```
02-25 16:13:46.794  1652  1765 I ActivityTaskManager: START u0 {act=android.content.pm.action.REQUEST_PERMISSIONS pkg=com.google.android.permissioncontroller cmp=com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity (has extras)} with LAUNCH_MULTIPLE from uid 10296 (BAL_ALLOW_VISIBLE_WINDOW) result code=0
02-25 16:13:46.795  2066  2090 V WindowManagerShell: Transition requested: android.os.BinderProxy@155f103 TransitionRequestInfo { type = 1, triggerTask = TaskInfo{userId=0 taskId=87338 displayId=0 isRunning=true baseIntent=Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.ichi2.anki/.IntentHandler } baseActivity=ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker} topActivity=ComponentInfo{com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity} origActivity=null realActivity=ComponentInfo{com.ichi2.anki/com.ichi2.anki.IntentHandler} numActivities=3 lastActiveTime=6650849 supportsMultiWindow=true resizeMode=2 isResizeable=true minWidth=-1 minHeight=-1 defaultMinSize=220 token=WCT{android.window.IWindowContainerToken$Stub$Proxy@c58b880} topActivityType=1 pictureInPictureParams=null shouldDockBigOverlays=false launchIntoPipHostTaskId=-1 lastParentTaskIdBeforePip=-1 displayCutoutSafeInsets=Rect(0, 145 - 0, 0) topActivityInfo=ActivityInfo{cfdbeb9 com.android.permissioncontroller.permission.ui.GrantPermissionsActivity} launchCookies=[android.os.BinderProxy@58799fa] positionInParent=Point(0, 0) parentTaskId=-1 isFocused=true isVisible=true isVisibleRequested=true isSleeping=false topActivityInSizeCompat=false topActivityEligibleForLetterboxEducation= false isLetterboxDoubleTapEnabled= false topActivityEligibleForUserAspectRatioButton= false topActivityBoundsLetterboxed= false isFromLetterboxDoubleTap= false topActivityLetterboxVerticalPosition= -1 topActivityLetterboxHorizontalPosition= -1 topActivityLetterboxWidth=-1 topActivityLetterboxHeight=-1 isUserFullscreenOverrideEnabled=false isTopActivityTransparent=true locusId=null displayAreaFeatureId=1 cameraCompatControlState=hidden}, remoteTransition = null, displayChange = null, flags = 0 }
02-25 16:13:46.796  6889  6889 I AnkiDroid: PermissionsActivity::onPause
02-25 16:13:46.796  6889  6889 I AnkiDroid: PermissionsActivity::PermissionsUntil29Fragment::onPause
02-25 16:13:46.798  1652  1765 D ActivityManager: quick sync unfreeze 2257 for 1
02-25 16:13:46.798   603   603 I BpBinder: onLastStrongRef automatically unlinking death recipients:
02-25 16:13:46.799  1652  1757 D ActivityManager: sync unfroze 2257 com.google.android.permissioncontroller for 1
02-25 16:13:46.865  1652  3969 D CoreBackPreview: Window{817bf6c u0 com.google.android.permissioncontroller/com.android.permissioncontroller.permission.ui.GrantPermissionsActivity}: Setting back callback OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@81dcf3b, mPriority=0, mIsAnimationCallback=false}
02-25 16:13:46.871  6889  6889 I AnkiDroid: PermissionsActivity::onResume
```

**Comment by david-allison** [comment]
@BrayanDSO do you have capacity to take this on?

**Comment by david-allison** [comment]
> I found the Option [All Files Access], but Anki doesn't show up in the list and I somehow can't assign it to random apps. Also can't assign this permission to anki somehow. It's weird, in the settings it looks like anki doesn't want this access, just when I start it. 

A similar issue can be reproduced by the following change:

```diff
-    Uri.fromParts("package", requireActivity().packageName, null) 
+    Uri.fromParts("package", requireActivity().packageName + "a", null) 
```

https://github.com/ankidroid/Anki-Android/blob/223f61b9aaabfd6c055d4b8c41f74410a2d7947f/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/PermissionsFragment.kt#L72-L75

**Comment by BrayanDSO** [comment]
This is the PermissuonsUntil29 screen.

Full30And31 uses `All files access` as the permission title.

It likely is some issue of the logic of checking the app permissions/version which is the should be the cause of #14423

Given the fact that I can't reproduce this and have other stuff in my pipeline, I can't take it at the moment

**Comment by david-allison** [comment]
Closing as duplicate of #14423 - same issue presented differently in 2.17

**Comment by BrayanDSO** [comment]
> currentFolderIsAccessibleAndLegacy is true
> - Environment.isExternalStorageLegacy() is true
> - isLegacyStorage(context, setCollectionPath = false) is true
>     - CollectionHelper.PREF_COLLECTION_PATH exists as a setting ⁉️

Logging them all, and probably more stuff, would help since we have some people that reproduce the issue and can share their logcat
