### ISSUE TITLE
Syncing issues

### ISSUE THREAD

**Issue by markcj62** [ankidroid/Anki-Android#15675]
Hello - I am not a developer, so apologies if this is not appropriately submitted.

I am having some issues with syncing on AnkiDroid. Here is a description of the problems.

1. Sometimes I need to do a full download, and sometimes this takes longer than my phone stays awake. If my phone's screen goes dark, the backup is interrupted. If I touch the screen to keep it alive, the backup is interrupted. Yes, I can set my phone to stay awake, but ... you understand the hassle.

2. When I sync, sometimes there are missing media files (more on this below). Yet, I see no way to access a list of the files that are missing.

3. I see no way to access the media sync log.

4. I am currently having problems where my AnkiDroid devices are not syncing all the media file from AnkiWeb. I have tried doing full downloads, checking media on all devices, checking the database on all devices. Rinse and repeat. I have even tried deleting the media on AnkiWeb and pasting in a new file. Somehow, AnkiDroid seems to know that it doesn't want to download the media on that particular card.

5. If there were a way to do some kind of "super media sync" where AnkiDroid takes a second look at AnkiWeb for missing media files, that would be quite helpful.

If is matters, I am using Anki on an Ubuntu Dell XPS 13 and AnkiDroid on an Android Pixel 6a.

Thank you for all your good work! - mj

**Comment by markcj62** [comment]
My AnkiDroid is 2.16.5

I believe my Anki Ubuntu is also the latest version:
Version ⁨23.12.1 (1a1d4d54)⁩
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1

And my Ubuntu is a fully updated Ubuntu 23.10

**Comment by david-allison** [comment]
2.18alpha has improved media syncing via a service/notification. Could you try it  and confirm that all your points still stand?

https://youtu.be/pQZT9jNF6MU

**Comment by markcj62** [comment]
Thank you for working on this with me.

I have installed the alpha, synced, checked media, forced full download,
checked, synced. Still, there are 82 files missing on AnkiDroid while I
have a clean check on Anki Desktop.


:-)      - mj

--------------------------

"That's the chief lesson I have learned.  The texture of our universe is
one where there is no question at all but that good and laughter and
justice will prevail."

- Archbishop Desmond Tutu

**Comment by david-allison** [comment]
Thanks, it'd be useful if you came to Discord: https://discord.gg/qjzcRTx `#help` to see if anyone can diagnose which media files are missing

We're not using the Anki Desktop backend for syncing, so everything should be the same, unless the files are strangely named

**Comment by BrayanDSO** [comment]
The forums may hep you https://forums.ankiweb.net/
