### ISSUE TITLE
[Bug] Momentary screen blackout occurs when moving from the "Get Started" phase to granting storage permission in order to proceed to the Deck Picker.

### ISSUE THREAD

**Issue by DevP-ai** [ankidroid/Anki-Android#15677]
###### Reproduction Steps

https://github.com/ankidroid/Anki-Android/assets/107491760/a4ed61dd-151a-41e6-9937-1c88876da3a4

###### Expected Result
There should be no momentary screen blackout or flickering.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Hi there. Can you still reproduce it?
