### ISSUE TITLE
[Bug] Can't create first deck if named 'Default'

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#15678]
###### Reproduction Steps

1. Delete Collection from Manage Space
2. Create a Deck with the name `Default`

###### Expected Result
The Default deck is created

###### Actual Result
The Default deck is not created but snackbar shows deck created

https://github.com/ankidroid/Anki-Android/assets/65113071/78a2f49a-4ec7-4308-bb98-1f42f8cb31ab

###### Debug info
AnkiDroid Version = 2.18alpha2-debug (0ab90ba8c1def105b512b507800c823d85bc9af4)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 9 (SDK 28)

ProductFlavor = amazon

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 9; AOSP on IA Emulator Build/PSR1.180720.122; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Safari/537.36

ACRA UUID = 63de06e9-9a3d-4ee5-8c5a-ce71ab411306

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by CyberButton** [comment]
I'll work on it

**Comment by SanjaySargam** [comment]
@CyberButton Yeah sure go ahead. If any help needed feel free to ask

**Comment by CyberButton** [comment]
> @CyberButton Yeah sure go ahead. If any help needed feel free to ask

I've noticed within the app that the default deck, which consistently has an ID of 1, is not displayed when it contains no cards. My goal is to adjust the functionality so that if a user creates a new deck named "default", it will be visible even when empty(if user deletes it then do the opposite), aligning with the behavior observed for other decks. However, I'm currently facing problems with database inspection. The Android Studio App Inspection tool doesn't reveal the database contents; it only shows the file ankidroid.db along with a few other unrelated tables. Could you provide some guidance on how I might access and inspect the database tables, specifically for the decks, to facilitate this change?
*or any other suggestions you may have

**Comment by SanjaySargam** [comment]
I am not understanding why you need to access database tables. Would you mind providing more context or explaining the specific need for inspecting the database tables?

**Comment by CyberButton** [comment]
> I am not understanding why you need to access database tables. Would you mind providing more context or explaining the specific need for inspecting the database tables?

Yeah, I was just unable to find the exact behaviour of the default deck which is clealry unique, so I was planning to look at the db to see how exactly it is behaving, to get more clue about it. Is it not where I should be looking for?

**Comment by CyberButton** [comment]
Oh, I found it, sorry yes there was no need to look at the db), will send PR soon.

**Comment by SanjaySargam** [comment]
> Oh, I found it, sorry yes there was no need to look at the db), will send PR soon.

Good to hear.

**Comment by CyberButton** [comment]
Upon further examination, it became clear that adjusting the functionality isn't as straightforward as I initially believed. My original idea involved modifying a specific line of code 

https://github.com/ankidroid/Anki-Android/blob/ea9e966ee6d260c9afbd2458569ca9a2d00856be/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L1978C1-L1979C97

 by incorporating an additional flag. This flag would be toggled on or off when the user explicitly decides to create or remove the default deck. However, this approach seems viable only when the default deck is the solitary deck present. Additionally, I've encountered an odd behavior where requesting the current deck invariably returns a single default deck if the collection is empty. Yet, the moment another deck is introduced, even if it's empty, the default deck vanishes from the listing. I've been unable to devise a method to consistently retrieve the default deck from the database in the presence of other decks.

Another issue arises when the default deck is deleted (or rather, hidden from view); it remains accessible during card addition, allowing users to add cards to it despite its supposed absence. In light of these observations, I propose reverting to a behavior observed in a previous version of Anki. There, attempting to create a deck with a name that already exists would result in an error message informing the user of the duplication. While attempting to implement this solution, I stumbled upon a bug. When creating a new deck with a name identical to an existing one, the system indicates that the deck has been created, even though no changes occur. I will provide a video to demonstrate this issue.

**Comment by CyberButton** [comment]
https://github.com/ankidroid/Anki-Android/assets/67738637/5c66e62f-2c14-459e-b0ad-c28d24882780

**Comment by CyberButton** [comment]
should I start a new issue for it?

**Comment by gourabsingha1** [comment]
Hi @david-allison can you please assign me this issue?
I've fixed it and want to make a pull request.

https://github.com/ankidroid/Anki-Android/assets/110812339/f97c25da-1b5d-40b6-9b5c-02f46efa90c0
