### ISSUE TITLE
Add "copy to clipboard" action for Snackbar shown in AnkiActivity when there's no app to show a url

### ISSUE THREAD

**Issue by lukstbit** [ankidroid/Anki-Android#15671]
Nit: add a to-do to use "copy to clipboard" functionality

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/15649#discussion_r1501721835_

**Comment by javaman97** [comment]
@david-allison I would like to work on this issue, would you please assign it to me ?

**Comment by ro4i7** [comment]
Can I work on this?

**Comment by david-allison** [comment]
@ro4i7 it's already been assigned, best to pick an issue which isn't being worked on

**Comment by ro4i7** [comment]
> @ro4i7 it's already been assigned, best to pick an issue which isn't being worked on

Ok @david-allison

**Comment by ro4i7** [comment]
Is it still open?

**Comment by david-allison** [comment]
@javaman97

**Comment by javaman97** [comment]
> @javaman97

Yes, I have made a PR regarding this, and it is closed successfully.

**Comment by lukstbit** [comment]
@javaman97 I think the question was if you are still working on this, as you opened two PRs for this issue and then closed them.

**Comment by david-allison** [comment]
For reference:

* https://github.com/ankidroid/Anki-Android/pull/15691 - closed without merging
* https://github.com/ankidroid/Anki-Android/pull/15693 - closed without merging

**Comment by ro4i7** [comment]
i want to work on this

**Comment by javaman97** [comment]
> For reference, both are closed without merging:
> 
> * https://github.com/ankidroid/Anki-Android/pull/15691 
> * https://github.com/ankidroid/Anki-Android/pull/15693 

Actually, this is done by my mistake as I didn't update the Rebase and updated the main branch , that's why existing issues have arrived with PR.
I will fix it by today, @david-allison what I need to improve ?

**Comment by david-allison** [comment]
We need an open PR to review

**Comment by awanishyadav967** [comment]
Hi @javaman97 are you still working on this?

**Comment by Haz3-jolt** [comment]
Hi @javaman97 wondering the same as well.

**Comment by david-allison** [comment]
I'll give this 24 hours, then reassign it to the next person who comments
