### ISSUE TITLE
Bring back ETA in main menu

### ISSUE THREAD

**Issue by sibilk99** [ankidroid/Anki-Android#15688]
In the previous version of AnkiDroid, the top left of the main menu would list the cumulative number of cards due across all decks and give an ETA, e.g. "877 cards due (122 min)". In the new release it only lists the number of cards due, without the estimated time.

The ETA was a useful feature for me, and evidently for others; it was [restored](https://github.com/ankidroid/Anki-Android/pull/15472) when reviewing individual decks, but not in the main screen. I propose returning this feature to the main menu, or at least making it an option that could be enabled in Settings.

**Comment by briankrznarich** [comment]
Possibly useful in the mean time: the all-decks ETA still seems to still be available in the custom widget. (tap-and-hold the Anki icon in the app list, select the 1x1 widget, add to home screen.  You'll get a global "remaining cards" and "eta" on the widget itself).

See also:
Request: Restore ETA / Estimated Time Remaining (Beta 2.17 Feedback) #15405

I guess I didn't notice this myself, as I have several out-of-date decks that make the main-screen ETA useless for me specifically.  But the arguments for restoring it are probably all the same.  Could maybe be tied to the same toggle that does deck ETA?

This may point to a potential issue with solving deck-ETA long-term via the new plugin system.  I'm not sure if plugins will be able to manipulate the deck list page or menus(discussed in the ticket above).

**Comment by richardjharris** [comment]
This seems to have been done (thanks!!) Just not merged yet

https://github.com/ankidroid/Anki-Android/pull/15472

**Comment by brishtibheja** [comment]
If this is done I would like the word AnkiDroid to be removed from here.

![Screenshot_2024-03-23-21-52-08-69_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/83163255-f7da-4bf4-a65e-79d1f0544345)

**Comment by richardjharris** [comment]
I would also like this feature, is it complicated? I could probably implement it

**Comment by BrayanDSO** [comment]
Feature requests were moved to the forums, so please ask it there
