### ISSUE TITLE
NoteEditorIntentTest flaky test after the intent handling changes

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#15707]
We have a new flaky test after the intent handling changes, this popped up on another PR recently as well and caused merge queue ejection

```

com.ichi2.anki.NoteEditorIntentTest > launchActivityWithIntent[emulator-5554 - 11] FAILED 
	java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
	at com.ichi2.anki.NoteEditorIntentTest.launchActivityWithIntent$lambda$0(NoteEditorIntentTest.kt:54)
```

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/15692#issuecomment-1969384047_

- step 1 mark flaky but not as resolving this issue
- step 2 determine why this is flaking on emulator tests, may require instrumentation (that is, logging and such) in the test so it can run on the CI runners to get their timing (they are slower than your local machine) and then download the logcat to see what your logs say about why it failed

**Comment by david-allison** [comment]
@criticalAY was this one which you added?

**Comment by criticalAY** [comment]
Yes, but it worked fine, would look into it

**Comment by criticalAY** [comment]
I suspect the field is accessed before the editor is properly set i.e. the progress bar is still there and field is tried to set text on
