### ISSUE TITLE
[BUG]: too small text in IO Card 

### ISSUE THREAD

**Issue by Devaprasad-reddy** [ankidroid/Anki-Android#15701]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

![Screenshot_2024-02-28-17-30-55-89_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/c8d01f64-62f3-46c9-87b6-c6c216b3d0da)
Add text in an IO Card and preview it
![Screenshot_2024-02-28-17-31-08-53_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/1f6ccbce-5c50-4772-8fed-d15eb79397df)

### Expected behaviour

The text size should have been same while reviewing the card

### Actual behaviour

The text size shrunk in the preview

### Debug info

```text
AnkiDroid Version = 2.17.1 (dd2f3762fb214f9dd51162b215974b23cc809713)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = OnePlus

Model = OPD2203

Hardware = mt8798

Webview User Agent = Mozilla/5.0 (Linux; Android 14; OPD2203 Build/UKQ1.230924.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.178 Safari/537.36

ACRA UUID = 3213579c-ae2d-4097-a4d5-6497675d3034

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by krmanik** [comment]
This is active issues currently in progress.
https://github.com/ankitects/anki/pull/2986

**Comment by Devaprasad-reddy** [comment]
Okay, couldn't find it when I searched
