### ISSUE TITLE
Anki Jukebox

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1570]
Originally reported on Google Code with ID 667

```
a kind of music player that selects tracks from an Anki deck's media folder, and shows
them based on their difficulty (more difficult=more often). It would open the .anki
database read-only.

Idea by Rachels:
Recently I've made a new deck for some of my mp3 listening material.  The question
is a track name and the answer contains a longish -  audio track.  I've been using
it  for the audio from 'Ultimate Japanese Phrasebook' plus a few other audioblog or
dialogues type tracks. Each track is them marked again, hard, easy or very easy depending
on how soon or how often I think I need to review it.  I wouldn't do this in desktop
anki, as i don't want to spend too much time sitting in front of a computer, but with
ankidroid being mobile, combining an mp3 player with some filtering of tracks so that
the easiest ones go away and the newest or hardest ones are repeated seems to make
sense. I've been happy with this so far.
The is already a feature request for track pausing and rewind. These are the basics
features that need to be added for it to be really practical.
But if it were to be popular, there could be more complex features added to make it
perfect for language study.
1. Looping track without having to reach into the pocket and press replay
2. Press a button to loop over the last eg 10 sec for bits that are not understood
well.
3. Playback at 70%, 80% and 90% normal speed, ideally without affecting pitch. (There
are players that can do this on android).
```

Reported by `nicolas.raoul` on 2011-07-02 12:45:32

**Comment by januario-hh** [comment]
I am also making a point of having this feature implemented in Ankidroid. I am using audio files which are at times long and I need a feature to stop the replay at times as well as a feature to loop back. The "smart audioplayer" (ak.alizandro.smartaudiobookplayer) has these features. And I enhance notes whith audios which are also used by other persons, who, like my wife, are of a completely different kind of learners' type and cannot stand listening to audios replayed slower and definitely prefer listening to audios replayed at normal speed.

**Comment by mikehardy** [comment]
Hmm - these are some advanced audio features and that's pretty far from our core abilities - maintaining the database (with media) and the scheduler and deck organization. This might be a good use of the API. If you tagged cards with the media you were interested in playing then you could pull those cards in scheduler order by the API I think, and (if we got the permissions right? unsure) you could send that to an audio player. I don't have the time to implement a player app or the glue between a player and AnkiDroid but this sort of thing should be possible programmatically if anyone wants to try
