### ISSUE TITLE
Add a "Pass/Fail Mode"

### ISSUE THREAD

**Issue by soliviantar** [ankidroid/Anki-Android#15700]
Abusing "Easy" and "Hard" buttons creates the problem of ease hell with SM-2. But even with FSRS where that problem disappeared, still having to decide between 3 levels of achievement can be mentally exhausting and discourage doing reviews. Some solutions exist, but for new users it can get overwhelming. (I create decks for my students and many of them are not savvy enought with technology to do the necessary tweaks without extensive supervision which I cannot provide.)

Could you implement a "Pass/Fail Mode" in the settings, so that when it'd be enabled the user would only get two buttons: Fail (or just a red X intead of a word, which would stand for "Again") and Pass (or a green tick, which would be "Good"). Getting rid of the time for next review in this mode would be sensible as well.

I personally have configured my Ankidroid to use gestures and hide the buttons, so I can just swipe left or right and works great (this could also be implemented in said Pass/Fail Mode, maybe). But as mentioned, my students would not be able to set this up so easily, and they find it hard to understand why they should not tap Hard or Easy, or they spend too much time deciding what to tap or considering the time for review shown in the buttons.

Thanks for your time and effort!

**Comment by david-allison** [comment]
Hi, 👋 thanks for the suggestion

This can be done by hiding the answer buttons and assigning gestures for "swipe left" or "swipe right" or using our JS API

We're slowly moving to a point where addons will allow this, but it's not functionality we'll natively support unless Anki Desktop does so

**Comment by brishtibheja** [comment]
You should try making a post in https://forums.ankiweb.net
