### ISSUE TITLE
Better way to attach images to the back/explanation part of the IO cards

### ISSUE THREAD

**Issue by Devaprasad-reddy** [ankidroid/Anki-Android#15702]
**Aattach images to the back of IO Card.**
I want to add images to the back of any IO Card while creating it in anki droid.
![Screenshot_2024-02-28-17-51-42-61_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/40095e0f-d143-49f8-bf39-c9390faf68c3)

**A button to add images just like in normal card mode**
A button to attach images in the back section of image occlusion card would solve my issue.
![Screenshot_2024-02-28-17-45-26-96_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/18b46f5b-dc27-45fd-94b0-a5b9fdff3363)

**Upload the image to database and paste the source name**
I've uploaded the image to my anki database and pasted the image source into the back but they are not showing as images.
![Screenshot_2024-02-28-17-51-53-60_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/cc175f1c-ce5e-4b3f-a8b2-46ad7726541e)

**that would be cool to use more clearer explanations for everyone who uses a lot of IO cards**
Thankyou

**Comment by david-allison** [comment]
How does this work on Anki Desktop?

**Comment by Devaprasad-reddy** [comment]
I'm not sure,
I've never used anki desktop..!

**Comment by krmanik** [comment]
Currently only one image supported in Anki native IO, if you want to use more images then you may create more notes.

**Comment by Devaprasad-reddy** [comment]
It worked with anki doodle app.

**Comment by krmanik** [comment]
The above pasted text `<img src="...` will work if click on `<>` icon to enter in html mode in note tab, then update.

**Comment by Devaprasad-reddy** [comment]
Sure will try that..
Then it might be possible to make an attachment button right?

**Comment by Devaprasad-reddy** [comment]
It would be nice to have an **attach button** to add extra reference images to show in the explanation part

**Comment by krmanik** [comment]
The current IO implementation hide the fields the only way to add content to fields to open IO editor. But this can be enhanced by  showing the fields before opening IO editor.

**Comment by Aditya13s** [comment]
@david-allison can you assign me this?

**Comment by Aditya13s** [comment]
@Devaprasad-reddy can you explain me what should i have to implement in it?

**Comment by Devaprasad-reddy** [comment]
The current IO creation looks like this
![Screenshot_2024-02-29-01-06-09-17_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/f5174668-727d-457d-88eb-316638364550)
After creating the card the masked image looks like this
![Screenshot_2024-02-29-01-04-58-46_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/667f268e-bb56-465f-a237-a609bfc197ca)
Further more, i want to add more reference images to the masked card in the note section. 
for example some relevant images from my gallery related to the above topic in the actual masked card
![Screenshot_2024-02-29-01-05-03-46_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/0b467fbf-0441-45ef-b500-122d430a9c41)
In the note screen, If I press the <> button above, I'm able to insert an image source code from a previously uploaded image. But i need an attach button in the back/note side of the IO creation interface so that i can directly attach images
Somewhat like this as mentioned above 
![308568976-02642747-657b-4561-8b6c-d6b93856362e](https://github.com/ankidroid/Anki-Android/assets/36725943/249673b2-6c6b-484c-b4d8-a8dbc15d6e9e)

If possible there should also be a crop tool in the mask screen to crop image before masking, that's an other issue.

**Comment by Devaprasad-reddy** [comment]
We have to press on the Note button on the top left to be able to see the notes part of the IO card
It would be nice to have it in the front itself but it would make the image masking screen too contested imo.

**Comment by Aditya13s** [comment]
@Devaprasad-reddy there is no Note button on the top left, can you send me tutorial for this?

**Comment by Devaprasad-reddy** [comment]
The <> button allows me to paste a pre existing source for an image which is a work around to get images in the back section.
If possible you can enhance it by directly allowing image attachment/upload button

**Comment by Aditya13s** [comment]
@Devaprasad-reddy Do i have to upload it and then put the url in img tag or i can take the reference of the image and use that?

**Comment by Devaprasad-reddy** [comment]
Doesn't matter, you can use any image that's available in your anki database.

**Comment by Aditya13s** [comment]
i tried taking the image path from my device and then paste it in the image url but image is not able to load

**Comment by Devaprasad-reddy** [comment]
First add a card in basic type card and attach any reference image
You will get a code - Copy that 
and now create a new IO card with main image and add a mask using the rectangle tool
No press **note** on top left and go to the back section and select the back extra text input section and press **<>** button.
Now paste the code and click Add in the bottom right.
Now you should be able to preview the card from the card browser and after clicking the show answer in preview, this should be able to see both main image at the top and the reference image at the bottom

**Comment by Aditya13s** [comment]
@Devaprasad-reddy I fully understand what i have to implement. Thanks!

**Comment by Devaprasad-reddy** [comment]
Instead of all this cumbersome process, we can have a button to attach images directly to the back of image occlusion card creation interface
I made a screen recording of the workaround mentioned by @krmanik in the above message
https://youtu.be/MA5Iz-UZ8_w

**Comment by krmanik** [comment]
@Devaprasad-reddy 
> I need an attach image option here

That does not require because it is come from Anki desktop. 

@Aditya13s 
>  I am not able to see the textboxes(Header, Back Extra, Comments), do i have to add these textboxes on the Add Screen

When you select note types other than IO, you will see fields related to those note types, but in case of IO the fields are hidden, so you have to just implement to show the fields before opening the IO editor.
