### ISSUE TITLE
[Bug] Context menu in 'Rename deck' dialog hides cursor handles and bottom of text

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15716]
###### Reproduction Steps

1. Use Day themes
    -  This issue occurs in the Night themes as well, but currently it is difficult to understand visually what happens on the screen, due to another issue #15717)
1. Long press a deck in Deck picker screen
3. [Rename deck] 
4. Long press an range of the text (deck name)

###### Expected Result
You can adjust the selected range by the handles of the cursors
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/60f59f43-950e-4a25-9499-c00b9b0e04f4)
###### Actual Result
You can't, because immediately after the long-pressed area is highlighted, the handles of the cursors (and the bottom area of the selected text) are covered by the context menu.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/65b7707e-6500-4937-b3c6-eca0727e8fa6)

https://github.com/ankidroid/Anki-Android/assets/10436072/386f6def-7341-48d5-b00a-8bc7260dbdad

###### Anything else you want to share?
- This happens even when the text in the input box is a single line.

- In "Edit note" screen, this issue doesn't seem to occur.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/e0a45477-0f42-47b4-8c25-36fef15e86e4)

###### Debug info
```
AnkiDroid Version = 2.17.1 (dd2f3762fb214f9dd51162b215974b23cc809713)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.178 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) 2.18alpha2

**Comment by david-allison** [comment]
Are you able to you press + drag the context menu? I can't reproduce this on an emulator

**Comment by snowtimeglass** [comment]
I think I can't drag the context menu. I mean, I think I can't move the position of the menu in the screen.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/3cceae88-3c0d-4b1b-a184-837c8bb9b03f)

**Comment by criticalAY** [comment]
Can't reproduce Remote emulator API34 Pixel 8 
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/cc46ace9-1ebb-4d29-a642-1dfcd97e5f4a)

**Comment by criticalAY** [comment]
My own device : (OnePlus API33)
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/39d6142b-4a29-451e-9eb6-0c99537bc8ff)

**Comment by david-allison** [comment]
@snowtimeglass is this still an issue in the latest alpha?

**Comment by BrayanDSO** [comment]
This is on the system side. Not something we can act on
