### ISSUE TITLE
Docs: document that `android.permission.INTERNET` is necessary for people with other OS

### ISSUE THREAD

**Issue by ghtesting2020** [ankidroid/Anki-Android#15718]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

launch ankidroid
tap on either
any deck and it will crash
on statistics and it will crash

### Expected behaviour

not crash

### Actual behaviour

crashing

### Debug info

```text
fdroid 2.17.0


java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.Reviewer}: java.net.SocketException: socket failed: EACCES (Permission denied)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3740)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3974)
    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2475)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loopOnce(Looper.java:205)
    at android.os.Looper.loop(Looper.java:294)
    at android.app.ActivityThread.main(ActivityThread.java:8279)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
    at com.android.internal.os.ExecInit.main(ExecInit.java:49)
    at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
    at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: java.net.SocketException: socket failed: EACCES (Permission denied)
    at java.net.ServerSocket.createImpl(ServerSocket.java:331)
    at java.net.ServerSocket.getImpl(ServerSocket.java:281)
    at java.net.ServerSocket.setReuseAddress(ServerSocket.java:740)
    at fi.iki.elonen.NanoHTTPD.start(SourceFile:4)
    at fi.iki.elonen.NanoHTTPD.start(SourceFile:2)
    at fi.iki.elonen.NanoHTTPD.start(SourceFile:1)
    at com.ichi2.anki.AbstractFlashcardViewer.<init>(SourceFile:51)
    at com.ichi2.anki.Reviewer.<init>(SourceFile:1)
    at java.lang.Class.newInstance(Native Method)
    at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
    at androidx.core.app.CoreComponentFactory.instantiateActivity(SourceFile:1)
    at android.app.Instrumentation.newActivity(Instrumentation.java:1383)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3727)
    ... 14 more
```
```


### (Optional) Anything else you want to share?

fdroid only has 2.17.0 for now. I haven't tried 2.17.1 but searching here does not return any results for my errors.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Sounds like somehow either your device or the F-Droid build does not allow AnkiDroid to create it's own network socket?

```
Caused by: java.net.SocketException: socket failed: EACCES (Permission denied)
    at java.net.ServerSocket.createImpl(ServerSocket.java:331)
```

The way that AnkiDroid works now is that for a lot of items (including the reviewer) it runs it's own tiny HTTP server and a couple of it's internal components communicate with each other over HTTP. This may sound odd but it's a way for us to "host" the desktop parts of the code (behind an HTTP server)  in a way that the AnkiDroid native Java "client" can communicate with it, in order to have access to + reuse those desktop parts.

What could be preventing AnkiDroid from starting a server and opening a socket on your device?

**Comment by mikehardy** [comment]
https://github.com/ankidroid/Anki-Android/blob/debb686b6dfb303504562e5eb9380110007b0ee9/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L230

https://github.com/ankidroid/Anki-Android/blob/1c01e4cb6f06a464f31fcc80a1907d58d1952c63/AnkiDroid/src/main/java/com/ichi2/anki/pages/AnkiServer.kt#L26-L38

I'm not sure exactly what port it is trying to open but it looks like 0, at the same time the comments are saying 40001

The [docs on the upstream site](https://github.com/NanoHttpd/nanohttpd) indicate 8080

They both seem to be explicitly configuring it though and I'm not sure what happens when you explicitly configure port `0`

Perhaps that port is already used?

@BrayanDSO can you think of any reason why AnkiServer couldn't open a socket / bind to some port on localhost? Do you know what using a port of `0` implies for NanoHTTPd ?

**Comment by david-allison** [comment]
https://docs.oracle.com/javase/8/docs/api/java/net/InetSocketAddress.html#InetSocketAddress-java.lang.String-int-

> A valid port value is between 0 and 65535. A port number of zero will let the system pick up an ephemeral port in a bind operation.

**Comment by david-allison** [comment]
@ghtesting2020 which permission did you apply? We'll want to update the issue with this information so we can better replicate it

**Comment by BrayanDSO** [comment]
> at the same time the comments are saying 40001

Damien added that to ease testing if you want a fixed port

**Comment by mikehardy** [comment]
Interesting. Okay, not sure what I can say except that AnkiDroid communicates internally with itself using HTTP over TCP/IP via an internal server it binds to localhost and an ephemeral port.

It's an important part of the current design and I don't see that changing any time soon, sorry.

I suppose this will just have to be documented. In the meantime, at least we're open source so you can audit to hearts delight and you can potentially also run little snitch or similar (is it available on grapheneos ?) to monitor network traffic, AnkiDroid should emit nothing except to localhost both from and to it's own PID

**Comment by mikehardy** [comment]
Possibly of interest, from grapheneos fora https://github.com/celzero/rethink-app

**Comment by mikehardy** [comment]
It is odd and hacked together, and it works as an architecture to bring desktop code here.
We welcome PRs that implement something different.

I'm aware of security 101 and a few higher courses

I'm not sure I can help further, the current design is what it is and I consider this a documentation issue now

**Comment by mikehardy** [comment]
I believe I understand.

AnkiDroid 2.17 has a new attack surface area that exposes your phone to the risk of unauthenticated requests being run in an AnkiDroid process context, if the originator of those requests can access localhost and discover the ephemeral port to make the requests. Those requests if crafted carefully in the presence of unknown issues in the Android System WebView or NanoHTTPd or AnkiDroid may take advantage of those issues and do something malicious in the context of the AnkiDroid process.

Perhaps you are interested in proposing a PR where the method of communication is altered to something with a smaller surface area but still works to keep the Desktop code running behind an interface it currently supports (like HTTP over TCP/IP) ?

Note that as an open source app, our old releases are available forever. Feel free to use 2.16.5

**Comment by BrayanDSO** [comment]
https://github.com/ankidroid/Anki-Android/wiki/Permissions/5f6f0d353a0ecdc8d8cc976eadf9eb2ca3ddbf9a

**Comment by BrayanDSO** [comment]
Check https://github.com/krmanik/Anki-Android/pull/23 if you want more context about the server implementation.

> I didn't encounter anything breaking when using various kind of decks (sound, images, texts). Could you share with me which steps you did, or which specific deck(s) you used? I know something about i18nResources breaking was mentioned previously.

Use an IO card with more than one occlusion and use a language that isn't english. The `Toggle masks` won't get translated. Also, the `Custom scheduling` deck option won't work without POST resquests.

> Should I wait for this to be ready before I try working on it (not promising anything)? I don't want to give you additional work if the code I add must then be rebased with the future changes.

Please add a check for the `INTERNET` permission when initializing the app, and show the message stating that it is a mandatory permission in `PermissionsActivity` if the user removed it. It is the most appropriate place for stuff related to permissions, and it is also the simplest way to implement it.

I, particularly, won't accept any changes in `ReviewerFragment` or any of the `PageFragment`s for that. I don't want to add complexity and maintance burden for those screens just for that. The `PermissionsActivity` approach also solves the issue of someone forgetting to handle the permission absence in new/changed screens.

**Comment by papjul** [comment]
> I, particularly, won't accept any changes in `ReviewerFragment` or any of the `PageFragment`s for that. I don't want to add complexity and maintance burden for those screens just for that.

"Complexity and maintenance burden" seems exaggerated for [1 added try/catch and 2 added if/else](https://github.com/papjul/Anki-Android/commits/fix_flashcard_socket_crash), given the added value of now being able to use the most basic features of the app.

Not being able to access (at least for now) what I would call "extra features" (Image Occlusion decks, deck options and statistics) is an acceptable compromise for the added security in my case. I would suggest putting only the extra features behind a permission request screen.

But I understand you want to either block access to the whole app, or have all server uses replaced at once:
> Please add a check for the `INTERNET` permission when initializing the app, and show the message stating that it is a mandatory permission in `PermissionsActivity` if the user removed it.

So as I understand it, I need to maintain a fork if I want to access the basic features of AnkiDroid without compromising on security.

**Comment by BrayanDSO** [comment]
> So as I understand it, I need to maintain a fork if I want to access the basic features of AnkiDroid without compromising on security.

Unless someone manages to intercept POST requests without a server, yes. 

I know it is a trade-off, but having a server is by far the best option we currently have.
