### ISSUE TITLE
[BUG]: In IO deck is not changed

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#15721]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

From discord:
Select IO -> Change deck(have a empty deck selected) -> add card via select image option

The deck you selected after opening Note editor is not having the added card

### Expected behaviour

The deck is changed and the card is added to the changed deck

### Actual behaviour

Deck is not changed and card is added to prev deck

### Debug info

```text
AnkiDroid Version = 2.18alpha2-debug (f025de5c034150e0c18d1ae27f8884538de3f94d)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = OnePlus

Model = EB2101

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; EB2101 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.178 Mobile Safari/537.36

ACRA UUID = f235f25a-b2fa-42ef-bd5e-c885be80ba41

Crash Reports Enabled = false
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by soCallmeAdityaKumar** [comment]
I am working on it
