### ISSUE TITLE
Show "X command is already used" inside the control dialog instead of by using a toast

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15724]
Toasts messages propagates to all the device, take time to disappear and may accumulate, so I propose replacing it.

Normally, snackbars would be the default solution, but since this is a dialog, snackbars would be hidden, so I propose doing it inside the dialog

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/cc4e94d9-a9dd-4cc8-99cc-85807f8b139b)

**Comment by RobozinhoD** [comment]
I can do that
