### ISSUE TITLE
Make `Show answer long-press time` a SliderPreference

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#15725]
personal opinion: I think that it's gonna be easier to setup it that way.

Also, why does it only apply to the `Show answer` button, but not for the answer buttons?

**Comment by criticalAY** [comment]
I am the one who implemented it, the reason for not having it in the answer button was that the request was to avoid accidental taps which revealed the answers while commuting, it ensured that these didn't happen and having it on answer button makes no sense to me, it would in fact irritate as user IMO, we already have the safety here
Question (Long press) -> Answer Button -> Question (long press)

**Comment by BrayanDSO** [comment]
if accidental taps occur for showing the answer, they can occur in the exact same way while selecting the answer. I'd say that it is even more likely to happen, since the answer buttons are smaller

**Comment by criticalAY** [comment]
But is it worth it? I mean do a lot of users rely on it? If we want we can have it no problem,

**Comment by BrayanDSO** [comment]
> Still, I'm not proposing to add it given the fact that nobody asked for it, but that makes me question the use-case of the preference itself
.

**Comment by criticalAY** [comment]
Yes just saw that, you edited that at the same time i posted

**Comment by RobozinhoD** [comment]
Doing it
