### ISSUE TITLE
Feature: "Copy card template to clipboard" using Markdown

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15748]
**Is your feature request related to a problem? Please describe.**
I see a lot of card templates posted to Anki Forums/GitHub/Discord/Reddit in a badly formatted manner

This is difficult both for the submitters and helpers

**Describe the solution you'd like**
I would like a user to be able to press a button and export the current template as Markdown

**Describe alternatives you've considered**
A non-Markdown format may be slightly easier for other platforms which aren't listed above

It doesn't seem worthwhile to do both. Understanding markdown as normal text is easy, the inverse is difficult (as some HTML is stripped)

~~I will use 4 spaces as a prefix, rather than backticks to support old reddit. This means we may lose out on CSS formatting~~

**Additional context**

I have implemented this, and want to be sure there's been adequate discussion before I submit the PR

## Example

**Front template**

```html
    {{Front}}
    
    <div id="result"></div>
    
    <div class="result">
    </div>
    
    <script>
        var jsApi = { "version": "0.0.2", "developer":  "" };
    
       var api = AnkiDroidJS.init(jsApi)
       api.ankiGetETA().then(response => console.log(response));
    
        (async function() {
           let eta = await api.ankiGetETA();
           console.log("2aa" + eta.value);
    })();
        
            
    </script>
```

**Back template**

```html
    {{FrontSide}}
    
    <hr id=answer>
    
    {{Back}}
```

**Styling**

```css
    .card {
        font-family: arial;
        font-size: 20px;
        text-align: center;
        color: black;
        background-color: white;
    }
```

**Comment by BrayanDSO** [comment]
A share button with a `Copy as markdown` option seems natural enough to me.

About the formatting style, I prefer backticks since it can add code highlighting in github and discord, which feels more worthwhile to me than preferring to support an `old` platform that deliberately don't support new stuff

**Comment by mikehardy** [comment]
great idea
