### ISSUE TITLE
[BUG]: 2.17.3 [<= Android 10] Widget is permanently removed

### ISSUE THREAD

**Issue by xiety** [ankidroid/Anki-Android#15745]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Try adding a widget to your screen or look at a previously added widget.

### Expected behaviour

You see the widget

### Actual behaviour

There is no widget

### Debug info

```text
AnkiDroid Version = 2.17.3 (ca4cb3c2802bcb17e73b051e7e42308993513717)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 10 (SDK 29)

ProductFlavor = full

Manufacturer = HUAWEI

Model = STK-LX1

Hardware = kirin710

Webview User Agent = Mozilla/5.0 (Linux; Android 10; STK-LX1 Build/HUAWEISTK-LX1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.180 Mobile Safari/537.36

ACRA UUID = c615841e-0e0d-4e08-893d-6bf7124be077

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@criticalAY

**Comment by criticalAY** [comment]
On it

**Comment by david-allison** [comment]
@xiety do the widgets reappear after you've opened AnkiDroid?

**Comment by criticalAY** [comment]
The bug is each time the app is updated the widget would be removed and the user will have to add it. The widget is available to be added again from widget in android

**Comment by david-allison** [comment]
Is this every update, or only the first update which adds 

`enabled="false"`
https://github.com/ankidroid/Anki-Android/blob/03f9e7b3a91ab4f2a75e8fabdf1159cbf334e925/AnkiDroid/src/main/AndroidManifest.xml#L499-L514

**Comment by criticalAY** [comment]
@david-allison It's one time pain, I updated my app (debug) the added widget was not removed

**Comment by xiety** [comment]
To @david-allison
> do the widgets reappear/become available after you've opened AnkiDroid?

No

To @criticalAY
> The bug is each time the app is updated

For me only the last update (2.17.3) removed widget and no longer allows me to add it. This didn't happen with previous updates.

> could you confirm if you can add the widgets from the Android widget option? If you can then we should wait for 1 more alpha as it would be one time issue(one update only) after that you would have stable things in hand,

I can not add it, AnkiDroid is not on the list of widgets

**Comment by david-allison** [comment]
Underlying cause is https://issuetracker.google.com/issues/36914010 (`enabled="false"` for a widget on Android <= 10)

@xiety Thanks for the report! This will be fixed ASAP
