### ISSUE TITLE
Remove new timezone handling setting

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#15746]
Latest versions of Anki don't include this setting (i.e. new timezone handling is always enabled). I think that there is no need for AnkiDroid to keep this setting.

The setting is located in Reviewing → Advanced.

**Comment by BrayanDSO** [comment]
The last discussion about it: https://github.com/ankidroid/Anki-Android/pull/11991

@dae, is that removable now?

**Comment by dae** [comment]
_load_scheduler() in the Python code automatically enables the new timezone when loading a v3 collection. Removing the setting is fine, but you'll need to make sure it's automatically enabled too, as we don't want users stuck on the old setting.

**Comment by yhua537** [comment]
Hi 

Legacy version user here, can we still keep this menu setting visible? Not everyone is using latest versions in all of their devices. I have 2 device and one is stuck in 2.14 because it is not supported to be updated to later version by the android version anymore.

**Comment by BrayanDSO** [comment]
Hello there. Unfortunately, not. But you can download any of the previous versions on the [releases page](https://github.com/ankidroid/Anki-Android/releases) and keep using it.

**Comment by Sanjai-Shaarugesh** [comment]
## ✨ Fix: Timestamp Handling in AnkiDroid Backend Functions (#369)

This PR improves the timestamp handling logic in the AnkiDroid backend functions to ensure consistent and accurate parsing across operations.

### 🔧 What’s Fixed
- Resolved inconsistencies in timestamp parsing logic.
- Improved compatibility with AnkiDroid’s expected formats.

### 🔗 Related Work
This fix builds on the foundation laid in [PR #3899](https://github.com/ankitects/anki/pull/3899), refining and adapting it specifically for the AnkiDroid backend.
