### ISSUE TITLE
[BUG]: Mobile app is not rendering empty lines that were introduced in Anki desktop with HTML editor

### ISSUE THREAD

**Issue by athkalia** [ankidroid/Anki-Android#15758]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Go to the Windows version of the app, and enable the HTML editor.
2. Create a card that has some empty lines in it, without an HTML <br> tag. So it could be:
===START
This is a test

lalala
===END
3. Save this note and try to open it from the Android mobile app.

### Expected behaviour

What is described above should render in multiple lines

### Actual behaviour

Instead, it is rendered in a single line.

Interestingly, if you edit the card from the mobile phone and save it without introducing any changes, the issue is resolved.

### Debug info

```text
AnkiDroid Version = 2.17.1 (dd2f3762fb214f9dd51162b215974b23cc809713)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G991B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-G991B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = 82aaedcd-7d2d-4947-a5e6-bfad233b9564

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
This seems to work correctly. Could you please create a topic in the [forums](https://forums.ankiweb.net/) asking for help on that?
