### ISSUE TITLE
[BUG]: Creating a new deck with duplicate name (Bad UX)

### ISSUE THREAD

**Issue by CyberButton** [ankidroid/Anki-Android#15759]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. crate a new deck with any name, say "myDeck1"
2. attempt to create a new deck with the same name, say "myDeck1" again

https://github.com/ankidroid/Anki-Android/assets/67738637/bb6678a7-0419-4b50-a255-4b270d0923e0

### Expected behaviour

User is notified that such deck already exists.

### Actual behaviour

Toast indiacting that deck was succesfully created, while nothing actually happenned 

### Debug info

```text
AnkiDroid Version = 2.18alpha3-debug (69b9741636dc26c67e1a6db5c1b42239d8836319)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = Xiaomi

Model = M2102J20SG

Hardware = qcom

Webview User Agent = null

ACRA UUID = 1ed63705-68b2-42de-be09-f7f6076ab243

FSRS Enabled = false

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

My version of the app is: **2.18alpha3-debug**

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
I believe this originally existed and was reverted in https://github.com/ankidroid/Anki-Android/pull/14171

It'll be worth doing some `git log/blame` to get context, but it should be added in again

**Comment by CyberButton** [comment]
I think this would also fix the https://github.com/ankidroid/Anki-Android/issues/15678 , since default deck is always there.

**Comment by david-allison** [comment]
>> A duplicate deck is no longer caught in the 'create deck' page

> This matches desktop behavior - if the user creates a deck that matches an existing name, it's considered a no-op, like mkdir -p

Ref: https://github.com/ankidroid/Anki-Android/pull/14171#issuecomment-1699900692

**Comment by CyberButton** [comment]
then, is there any way to know that operation was ignored?, if I understood correctly, 
creating new deck only returns deck id. (maybe search decks in current tree for matching deck id?)
https://github.com/ankidroid/Anki-Android/blob/bde10b0f527811455f66318a92423869ed8051fd/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/CreateDeckDialog.kt#L149C1-L150C71 


> > > A duplicate deck is no longer caught in the 'create deck' page
> > 
> > 
> > This matches desktop behavior - if the user creates a deck that matches an existing name, it's considered a no-op, like mkdir -p
> 
> * [Drop legacy schema, and update to 2.1.66 backend #14171 (comment)](https://github.com/ankidroid/Anki-Android/pull/14171#issuecomment-1699900692)

**Comment by david-allison** [comment]
I'd guess `decks.idForName` would be usable here

**Comment by gourabsingha1** [comment]
Hi again @david-allison. Since this issue is similar to https://github.com/ankidroid/Anki-Android/issues/15678, please assign this to me as well.
I've fixed it and want to make a pull request.

https://github.com/ankidroid/Anki-Android/assets/110812339/d30c6e76-d57f-4804-b130-e5897bb0f48d
