### ISSUE TITLE
[Bug] Syncing error, type: -1, message: arbitraryString

### ISSUE THREAD

**Issue by zapdos6244** [ankidroid/Anki-Android#15752]
![Screenshot_20240303-081928](https://github.com/ankidroid/Anki-Android/assets/161986057/90193c07-fce7-49e1-a2d0-5426a4fbaa4b)
###### Reproduction Steps

1. Tried syncing
2. Error message pops up
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, thanks for the report. Please fill in the debug info

**Comment by zapdos6244** [comment]
AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 9

ProductFlavor = play

Manufacturer = asus

Model = ASUS_X00TDB

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; ASUS_X00TDB Build/PKQ1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.210 Mobile Safari/537.36

ACRA UUID = 1f7364b2-d373-4aea-b31f-1a8b40efca1b

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by zapdos6244** [comment]
Is this it?

**Comment by david-allison** [comment]
2.17 is being rolled out now and should fix this

Please let me know if this continues afterwards

**Comment by zapdos6244** [comment]
Thanks, I appreciate the fast response!!
