### ISSUE TITLE
Confirm before closing IO editor

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#15753]
**Is your feature request related to a problem? Please describe.**

In IO editor click on back button should confirm before closing IO editor.

**Describe the solution you'd like**

A popup with Cancel/Ok.

**Comment by MonuGit9** [comment]
I want to work on this issue
Plz, Assign me !

**Comment by david-allison** [comment]
@MonuGit9 did we talk about this on Discord? If so, it's yours

**Comment by david-allison** [comment]
@ro4i7 Assigned, given you were second in line and there was no reply to my message on Discord from `orvenom `. Thanks!

**Comment by Aditya13s** [comment]
@david-allison Please check the pull request

**Comment by david-allison** [comment]
> @david-allison Please check the pull request

This was assigned to someone else, what happened?

**Comment by Aditya13s** [comment]
> > @david-allison Please check the pull request
> 
> This was assigned to someone else, what happened?

I completed this task when no one was assigned, but I got busy with other work. So today, I submitted the pull request for it.

**Comment by Aditya13s** [comment]
@david-allison Have you stopped paying contributors, or is there a problem that I'm unaware of?

**Comment by david-allison** [comment]
@Aditya13s message Mike on Discord as he's dealing with it

I believe it's just a big backlog

**Comment by Aditya13s** [comment]
@david-allison okay
