### ISSUE TITLE
String Suggestion for: "AnkiDroid is not initialized yet. Please open AnkiDroid once, then try again"

### ISSUE THREAD

**Issue by NameLessGO** [ankidroid/Anki-Android#15761]
Context: https://github.com/ankidroid/Anki-Android/pull/15692

Suggestion for better translations

- AnkiDroid is not initialized yet. Please open AnkiDroid, then try again (_once_ is removed)
- AnkiDroid is not initialized yet. Please open AnkiDroid and try again (_once_ and _then_ are removed, preferred)
- Try again after opening AnkiDroid

Once is redundant and harder to translate, in pt-BR had removed in favor of the second suggestion

**Comment by BrayanDSO** [comment]
I'm Brazillian and understand the issue. FWIW, I like the third phrase

**Comment by david-allison** [comment]
I still mildly prefer 3, but see discussion here:

* https://github.com/ankidroid/Anki-Android/pull/15692

@mikehardy @lukstbit

**Comment by mikehardy** [comment]
we already have some translations just go for the minor optimization and item 2

As this is a one-time only thing (after people have done first-run it never happens again) and is just a string I understand all the points of view but it's kind of a bike shed at the moment 😆

**Comment by mikehardy** [comment]
#15764 is up for review, if we're going to do it let's do it and move on 🙏

**Comment by david-allison** [comment]
* Fixed in https://github.com/ankidroid/Anki-Android/pull/15770
