### ISSUE TITLE
Add Search Bar in Manage Note Types

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#15763]
As it currently stands, a search bar would be useful in Manage Note Types. We already have one for the decks page even though around 15 decks can easily fit the screen. With the recent 2.17 changes I need to do a lot of scrolling as I've around 35 different note types. I believe it would make sense to have a search bar here.

**Comment by lukstbit** [comment]
I think this would be a helpful feature.

**Comment by AffanShaikhsurab** [comment]
Working on it
