### ISSUE TITLE
Statistics: "deck:current": Show name of deck

### ISSUE THREAD

**Issue by mikemorr** [ankidroid/Anki-Android#15768]
The new Statistics screen defaults to "deck:current", which is great, but I'd like the *name* of the current deck to also be visible on this screen, as it was in the old statistics screens.

**Comment by david-allison** [comment]
Hi @mikemorr, this should be fixed soon under the following issue. Thanks for the report, and hope this solution works for you.

* https://github.com/ankidroid/Anki-Android/issues/15197
