### ISSUE TITLE
[BUG]: Font override no longer available

### ISSUE THREAD

**Issue by xDoge26** [ankidroid/Anki-Android#15775]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Install ankidroid 2.17.3

### Expected behaviour

Allow font override to show japanese's kanji

### Actual behaviour

This option no longer available

### Debug info

```text
AnkiDroid Version = 2.17.3 (ca4cb3c2802bcb17e73b051e7e42308993513717)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = Xiaomi

Model = 2201117TG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; 2201117TG Build/SKQ1.211103.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = 636e8109-e8a9-49f7-912d-3da47899eb0d

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Without font override, anki is showing chinese kanji instead of japanese kanji

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lotard** [comment]
Which deck are you using? I'm using KanjiDamage and JLab and they don't seem to have changed in terms of kanji since the update (other than font color styling issues).

**Comment by david-allison** [comment]
This feature was replaced with fonts in the media folder

https://ankidroid.org/removed-features.html#_custom_fonts_in_fonts

Please use one of our support sites if you're having problems with the instructions to resolve this
