### ISSUE TITLE
Restore pre-2.17 night mode text color inversion as an optional Appearance/Accessibility setting

### ISSUE THREAD

**Issue by archaicbulba** [ankidroid/Anki-Android#15779]
**Is your feature request related to a problem? Please describe.**
On updating AnkiDroid to 2.17, I was dismayed to see that many of my decks now had black text in the night mode, and were totally unusable, thanks to the removal of the previous color inversion feature.

**Describe the solution you'd like**
Make the inversion feature as an option of "Appearance" or "Accessibility" in the settings.

**Describe alternatives you've considered**
Restore the comprehensive night mode text color inversion feature as a default feature of AnkiDroid, make the Desktop Version consistent colors currently in 2.17 an option under Appearance for power users.

**Additional context**
Telling users to simply edit their decks CSS is not a reasonable alternative, for two reasons.

Firstly, many Anki users are not especially technically proficient, often preferring pre-built decks to creating their own. These users will struggle at altering card template CSS to make their decks work in night mode without the color inversion feature, especially when these decks may use CSS that doesn't conform to the example given.

Secondly, many decks that users may download from Ankiweb will not function "out of the box" in dark mode because of the removal of the color inversion feature, simply due to how their card template CSS was coded. This would include decks that, while coming highly recommended to users for their topics, have not seen any updates for years, and would likely never get an update from their authors to work properly here. With users able to import decks downloaded from AnkiWeb directly into AnkiDroid, this means that the first experience of the Ankidroid app for many users may be a deck that isn't working properly for them.

**Comment by brishtibheja** [comment]
I was one of the people who requested this feature to be removed last year. My issue was that I know enough to edit my own cards but often did not know putting which color would get me which color in inversion. I tried but failed at disabling this feature in the CSS. The tags I tried just didn't work for some reason. Anyways, having it as an optional feature may be useful to some people and also solves my issue.

**Comment by BrayanDSO** [comment]
> many decks that users may download from Ankiweb will not function "out of the box"

Unfortunately, this isn't a problem that can be solved completely.

Night mode works by default in all notetypes, unless the template author has broken it. There are infinite ways of breaking the style of a card, and trying to give a workaround to all of them simply isn't sane.

The template author can break the fonts size, style, button height, images size, doesn't work on mobile or whatever. I've even seen breakage of the color inversion, when it was the default. Sometimes, some breakages are even intentional. Covering all of the possibilities is impossible.

So, from me, it's a no.

---
A more sane alternative, IMO, would be to 1. ask the deck author to fix the issue, and 2. someone build a tutorial of how to add the css line for inversion (adding a line isn't that hard, even for non-technicals)

**Comment by jeejee0** [comment]
> Night mode works by default in all notetypes, unless the template author has broken it. There are infinite ways of breaking the style of a card, and trying to give a workaround to all of them simply isn't sane.

I don't understand this.  Night mode *did* work before, but now the functionality that had been working no longer does.  I had to go to the Discord to find out why I could no longer read the text on my cards.  I'm grateful that a solution was provided, however it required me to manually edit the code for multiple decks.  For many people, both of these steps (going to the Discord, and editing decks) will be too much.

Even though I am capable of editing my own decks, it may not be feasible to do so quickly as I may be away from my computer while traveling etc - and with Anki, even a few days of not being able to review can be quite devastating let alone potentially longer.

So at least having a setting to maintain the existing functionality would be really helpful.
