### ISSUE TITLE
[BUG]: Widgets are gone

### ISSUE THREAD

**Issue by fvieira** [ankidroid/Anki-Android#15776]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

My app updated during the night to version 2.17.3, and now my widgets are gone and I can't see them in the list to add back. 

### Expected behaviour

Widgets are available 

### Actual behaviour

They're not

### Debug info

```text
AnkiDroid Version = 2.17.3 (ca4cb3c2802bcb17e73b051e7e42308993513717)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = motorola

Model = moto g(8) power

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; moto g(8) power Build/RPES31.Q4U-47-35-12; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = 9741f02f-e800-4f66-aad9-baeb3ff520e4

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

At least with this version I can now sync my cards again and it seems notifications are working too. Thanks for the continued work! 😁

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by fvieira** [comment]
@david-allison My bad, forgot to look for duplicates in the closed issues :sweat_smile:

**Comment by david-allison** [comment]
@fvieira No worries, thanks for reminding me that I forgot to close this! 😅

Truly, thanks for the reports. It's vital for us to know as soon as possible when things go wrong
