### ISSUE TITLE
.Avi files not playing

### ISSUE THREAD

**Issue by NameLessGO** [ankidroid/Anki-Android#15772]
###### Reproduction Steps

1. Insert .avi  (file used: [sample avi files](https://filesamples.com/formats/avi))
2. Preview Card

###### Expected Result
Load the video

###### Actual Result
![image](https://github.com/ankidroid/Anki-Android/assets/66227691/4a74268f-8234-47bb-90f4-e701c4423dab)
First field: .avi
Second field: .mp4

###### Debug info
2.18alpha2 Samsung S21

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Additional
This was reported in [Forum](https://forums.ankiweb.net/t/android/41960)

> The card on android has never been able to play avi videos (it won't sync over, I imported the avi video into the "collection.media" folder on android, and it won't play it either).

> Today I inserted an occasional mp4 video on my computer, and suddenly found that it could be synchronized to android and played without any problem. I would like to ask, does android have any special rules for synchronizing audio and video?

> The formats I've encountered are wav, mp3, mp4, avi. I found that mp4, wav can sync itself to the phone, while avi can't, and mp3 seems to be able to sync as well.

###### Context Code
``` @Test
    fun `parseSourcesToFileScheme - object`() {
        val mediaDir = "storage/emulated/0/AnkiDroid/collection.media"
        val result = parseSourcesToFileScheme("<object data=\"ben.avi\"></object>", mediaDir)
        assertEquals("""<object data="file:///$mediaDir/ben.avi"></object>""", result)```


// not in libAnki
object Sound {
    val VIDEO_EXTENSIONS = setOf("mp4", "mov", "mpg", "mpeg", "mkv", "avi")
```

**Comment by david-allison** [comment]
* We need a sample AVI to test
* How large is the AVI file? There's an AnkiWeb-based limit to media

**Comment by david-allison** [comment]
@NameLessGO is it feasible for you to attach a sample `apkg`?

**Comment by NameLessGO** [comment]
It is not possible in GitHub, sent via Discord

> Try again with GIF, JPEG, JPG, MOV, MP4, PNG, SVG, WEBM, CPUPROFILE, CSV, DMP, DOCX, FODG, FODP, FODS, FODT, GZ, JSON, JSONC, LOG, MD, ODF, ODG, ODP, ODS, ODT, PATCH, PDF, PPTX, TGZ, TXT, XLS, XLSX or ZIP.

The media file was picked from [Files Samples](https://filesamples.com/formats/avi)
