### ISSUE TITLE
[BUG]: [Imgur] Images fail to load with 403 due to referrer being 127.0.0.1

### ISSUE THREAD

**Issue by drquochoai** [ankidroid/Anki-Android#15777]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Just add img tags with source from (imgur.com) link in your cards.
`<img src='https://i.imgur.com/bGJffg6.png'/> <img src='https://i.imgur.com/Ng07jkz.png'/>`
This issues occurred since:
- Ankidroid 2.17. Before is 2.16.5, the images is shown normal.
- Anki for window 2.49.1 and before is shown normal.

### Expected behaviour

Images should show as normal, because some decks is so big for media. I always use images link to show images, and my decks is just in **kb** by size.

### Actual behaviour

Images have sourced from internet is not shown 

### Debug info

```text
AnkiDroid Version = 2.17.3 (ca4cb3c2802bcb17e73b051e7e42308993513717)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = samsung

Model = SM-N986B

Hardware = exynos990

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-N986B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/121.0.6167.180 Mobile Safari/537.36

ACRA UUID = 69cba529-7fe4-437b-95a4-a0f83bf896f5

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Issue: https://stackoverflow.com/questions/43895390/imgur-images-returning-403

**Comment by david-allison** [comment]
Hmm... Anki Desktop also has this issue

**Comment by david-allison** [comment]
@dae was there ever a discussion on Anki's [referrer policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy)?

* https://github.com/ankitects/anki/issues/2234

discusses this, but I believe from a lens of hosting on `localhost` vs `127.0.0.1`, rather than not sending `referrer: http://127.0.0.1` to external servers

**Comment by david-allison** [comment]
@drquochoai 

While we look into this, 

* Edit a broken card
* Tap `Cards...`
* add `  <meta name="referrer" content="no-referrer">` to your `Front` template

**Comment by drquochoai** [comment]
Thank you, tha

> @drquochoai
> 
> While we look into this,
> 
> * Edit a broken card
> * Tap `Cards`
> * add `<meta name="referrer" content="no-referrer">` to your `Front` template

Thank you, that's work for me.

**Comment by dae** [comment]
It's not something I've dug into before, as I'd prefer people use local media instead of remote links that require internet access and may break in the future.

**Comment by david-allison** [comment]
Okay, won't fix for now. 
Might come back to this in the future
