### ISSUE TITLE
Need for right to left languages support

### ISSUE THREAD

**Issue by Adinaat** [ankidroid/Anki-Android#15783]
There is no support for right to left languages in ankidroid. Words get mixed up when using two diffrent languages specially when one start from left to right and the other one starts from right to left. I have a photo that proves this that I just uploaded.

![Screenshot_20230811_144608_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/162358265/d790c529-a83b-4f91-a402-fb5b6d9d97a3)

![Screenshot_20230811_144617_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/162358265/9e0c5b8e-b68b-43d7-ba37-9f122ead04f4)

**Comment by Mohamed-Hamza** [comment]
I will work on this one!

**Comment by david-allison** [comment]
I don't feel this one is worthwhile, we're looking at replacing the note editor, and it'll likely end up being wasted effort.

**Comment by eginhard** [comment]
"No support" is also not quite true, see the manual for RTL use in AnkiDroid: https://ankidroid.org/docs/manual.html#RTL

**Comment by Mohamed-Hamza** [comment]
> I don't feel this one is worthwhile, we're looking at replacing the note editor, and it'll likely end up being wasted effort.

Ok great!
