### ISSUE TITLE
[BUG]: Very often AnkiDroid freezes with blank screen during repetitions (app restart needed)

### ISSUE THREAD

**Issue by mzacki** [ankidroid/Anki-Android#15792]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Open any deck and start learning. After a few repetitions, only blank screen is displayed. I can also see and use answer buttons, but no question card and no answer card is shown, even when any answer button is pressed. The screen reloads, the learning process goes on, but still, no question card, no answer card is visible, only buttons.

### Expected behaviour

I can see what I am learning.

### Actual behaviour

To restore normal learning flow, I need to shut up the AnkiDroid and launch it again. Sometimes multiple times per session.

### Debug info

```text
AnkiDroid Version = 2.17.1 (dd2f3762fb214f9dd51162b215974b23cc809713)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 6.0 (SDK 23)

ProductFlavor = play

Manufacturer = HUAWEI

Model = ALE-L21

Hardware = hi6210sft

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0; ALE-L21 Build/HuaweiALE-L21; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 8962faad-c74a-4c1c-86bb-67131cf5f770

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

This behaviour is independent from the content of notes, card types and the like. No matter if a deck is containing audio or not, jpeg files nor which character coding is used. It happens also in simple front - back decks containing English words without special characters etc.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by xenonnn4w** [comment]
i'm unable to reproduce the same , can you please attach a recording or img related to bug ?

**Comment by mzacki** [comment]
https://github.com/ankidroid/Anki-Android/assets/38253922/3e1d7fc3-3797-4da5-b103-55de0fdbba5c

**Comment by geektan123** [comment]
Hi @david-allison can you please assign the issue

**Comment by grbrown** [comment]
I am having the same issue on v 2.17.3

**Comment by mikehardy** [comment]
Interesting - have you tried altering the hardwa render setting in advanced settings? May have an effect

**Comment by snowtimeglass** [comment]
> I had the same issue, restarting the device appears to have fixed it.

_Originally posted by @AdrianSva in https://github.com/ankidroid/Anki-Android/issues/14517#issuecomment-1764075784_ ([[BUG]: All cards appear blank](https://github.com/ankidroid/Anki-Android/issues/14517#top))

Restarting the device doesn't work in your case?

**Comment by mzacki** [comment]
Unfortunately not, even after every restart of the app AND the device, the bug is getting back again after some time. Usually after a dozen repetitions.
Also enabling GPU rendering does not seem to have any impact.

**Comment by snowtimeglass** [comment]
Just to make sure: uninstall & reinstall the app doesn't work either?

**Comment by geektan123** [comment]
Hi  @mzacki , the app works fine on my device .....have you faced similar issue in other devices.

**Comment by JhonnySalles** [comment]
I believe the error is related, after the correction of the tag break in version 2.17.5, a problem is sometimes occurring in image rendering, as can be seen below, sometimes the image duplicates meaninglessly and other times it appears normally.

In tests, every 3 times the response card is viewed, the image becomes distorted, as shown in the image below.

My card does not have an image adjustment, just the with to display on the screen, it does not have another image besides it on the response side, but when adjusting the view, the break occurs.

Maybe the reported error is helping to freeze the card.

![Screenshot_20240308_103924_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/43912638/11724b8c-210a-4b50-b3e0-0b793ae34d6a)


![Screenshot_20240308_103942_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/43912638/30f58105-6e6d-45da-b3fd-fea13fdb5588)

**Comment by mzacki** [comment]
> Just to make sure: uninstall & reinstall the app doesn't work either?

@snowtimeglass No. Hard reboot also does not work. Tried also Android System WebView uninstall, reinstall & update, in the same way as for this issue https://github.com/ankidroid/Anki-Android/issues/15790
AnkiDroid had been working well through years on my device. Both bugs appeared after the update to current version, some 10 days ago.

**Comment by johncaiwa** [comment]
When you have that blank screen, can you try pinching to zoom in? Then, scroll up after pinching to zoom in and try to see. This looks like the problem I had that got rejected to fix
