### ISSUE TITLE
sync error: invalid peer certificte: unknownissuer[Bug]

### ISSUE THREAD

**Issue by hafatsat-anki** [ankidroid/Anki-Android#15797]
###### Reproduction Steps

1. Connecting to a home network (with monitoring that requires a security certificate)
2. Installing a self-signed security certificate (at the system or user level - the problem occurs in both types)
3. Synchronization attempt

The certificate is installed correctly - when it is at the system level, I have no problem with any application (except for Chrome, which is a known problem and not specifically related to me)
The problem occurred starting with the switch to the new backend
Also in version .16

###### Expected Result
sync

###### Actual Result
error alert

###### Debug info
AnkiDroid Version = 2.17.4 (103ccb54f833e7a78df8e0c4098a63e8daeacd51)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = DuoQin

Model = F21 Pro

Hardware = mt6761

Webview User Agent = Mozilla/5.0 (Linux; Android 11; F21 Pro Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/83.0.4103.120 Mobile Safari/537.36

ACRA UUID = 634b33da-a9f3-4933-a79c-eb1889835cfe

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X ] I have searched for similar existing issues here and on the user forum
- [X ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Duplicate of #14686
