### ISSUE TITLE
[BUG]: Deck options shows blank screen - impossible to edit deck options, AnkiDroid ignores deck options synchronized through AnkiWeb.

### ISSUE THREAD

**Issue by mzacki** [ankidroid/Anki-Android#15790]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Run AnkiDroid, enter any deck, open top right menu, select Deck Options.

### Expected behaviour

I can edit options.

### Actual behaviour

Screen is blank.

### Debug info

```text
AnkiDroid Version = 2.17.1 (dd2f3762fb214f9dd51162b215974b23cc809713)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 6.0 (SDK 23)

ProductFlavor = play

Manufacturer = HUAWEI

Model = ALE-L21

Hardware = hi6210sft

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0; ALE-L21 Build/HuaweiALE-L21; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = 8962faad-c74a-4c1c-86bb-67131cf5f770

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

AnkiDroid ignores deck options synchronized through AnkiWeb. 
I created a deck locally (AnkiDesktop) synchronized with AnkiDroid with own set of options, eg. 5 new cards per day. AnkiDroid ignores these settings, e.g. does not show any of new cards to be learned at all. They must be selected trough "custom study" feature everytime. I am unable to check what options this deck is using due to the blank screen.
In other decks (created before update to current AnkiDroid version), AnkiDroid started to show new cards dispersed among reviews, although in AnkiDroid / AnkiWeb they've always been set to be shown after repetitions. I am unable to check the options due to the blank screen.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Is it feasible for you to update Android System WebView? You're using a version from 2022

**Comment by mzacki** [comment]
It's Android 6. The version of Webview from September 2022 (105.xxxxx) is the highest possible.

**Comment by mzacki** [comment]
To sum up, in current state, from this version on, AnkiDroid seems to be unusable for this device & OS combination. It simply ignores deck options synchronized through AnkiWeb and overrides options set up on AnkiDroid earlier. And even after learning with custom study option, it will never show learned cards as repetitions, no matter how many days passed.

I am wondering why recent AnkiDroid update impacted the way how it works on mobile device. Earlier it was simply keeping the options as-is, without overriding them. All new cards appeared after repetitions, and the next day the new cards became the new repetitions. Now it is not working properly at all.

Not to mention that because of this graphical issue, there is no way to correct the AnkiDroid options for any deck.
I tried all actions described here https://github.com/ankidroid/Anki-Android/issues/15792
Both problems started along with the recent AnkiDroid update, that had been installed behind the scenes, without any action / approval from user side.

No other update took place on the device at the same time: Android version, System WebView and phone software have been remaining the same since very long time. Until this version of AnkiDroid, everything worked fine.

**Comment by david-allison** [comment]
I've ordered a P8 Lite to reproduce this. Should be delivered before the 19th March.

For now, you can use 2.16.5 in parallel: https://github.com/ankidroid/Anki-Android/releases/tag/v2.16.5#:~:text=AnkiDroid%2D2.16.5.parallel.A.apk

**Comment by mzacki** [comment]
Thank you for your prompt reaction. I downgraded to 2.16.5, tested it, and it works perfectly fine.
By the way, is there a way to disable automatic updates? Is it system-dependent (e.g. related to Google Store options) or handled differently?

**Comment by david-allison** [comment]
You can ask Google Play to stop automatic updates, but that's out of our control.

The `Parallel.A` version which I sent won't auto-update.

**Comment by david-allison** [comment]
```
18:17:45.595 chromium                com.ichi2.anki.debug                 I  [INFO:CONSOLE(1)] "page-fully-loaded:", source:  (1)
18:17:45.674 chromium                com.ichi2.anki.debug                 E  [ERROR:tile_manager.cc(830)] WARNING: tile memory limits exceeded, some content may not draw
18:17:45.675 chromium                com.ichi2.anki.debug                 E  [ERROR:tile_manager.cc(830)] WARNING: tile memory limits exceeded, some content may not draw
18:17:45.731 chromium                com.ichi2.anki.debug                 I  [INFO:CONSOLE(1)] "Uncaught ReferenceError: anki is not defined", source: chrome-error://chromewebdata/ (1)
18:17:45.741 chromium                com.ichi2.anki.debug                 I  [INFO:CONSOLE(3)] "Background color set", source:  (3)
18:17:45.744 chromium                com.ichi2.anki.debug                 I  [INFO:CONSOLE(1)] "Uncaught ReferenceError: $deckOptions is not defined", source: chrome-error://chromewebdata/ (1)
18:17:45.750 chromium                com.ichi2.anki.debug                 E  [ERROR:tile_manager.cc(830)] WARNING: tile memory limits exceeded, some content may not draw
18:17:45.751 chromium                com.ichi2.anki.debug                 E  [ERROR:tile_manager.cc(830)] WARNING: tile memory limits exceeded, some content may not draw
18:18:13.455 AnkiDroidApp$onCreate   com.ichi2.anki.debug                 I  SingleFragmentActivity::onPause
18:18:13.457 FragmentLifecycleLogger com.ichi2.anki.debug                 I  SingleFragmentActivity::DeckOptions::onPause
18:18:13.494 AnkiDroidApp$onCreate   com.ichi2.anki.debug                 I  SingleFragmentActivity::onSaveInstanceState
18:18:13.498 FragmentLifecycleLogger com.ichi2.anki.debug                 I  SingleFragmentActivity::DeckOptions::onSaveInstanceState
18:18:13.500 AnkiDroidApp$onCreate   com.ichi2.anki.debug                 I  SingleFragmentActivity::onStop
18:18:13.501 FragmentLifecycleLogger com.ichi2.anki.debug                 I  SingleFragmentActivity::DeckOptions::onStop
```
