### ISSUE TITLE
[BUG]: First click on Card Added bar graph does not work

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#15805]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Open statistics
2. Go to the bottom at Added graph.
3. Here, click on a bar on the right side.

### Expected behaviour

The bar is selected and it shows the number of cards added along with the day.

### Actual behaviour

page scrolls to the graph above it i.e., Answer Buttons' graph. If you scroll back to bottom and click it again, it works this time.

### Debug info

```text
AnkiDroid Version = 2.18alpha5 (d27c999e562fae2b648b0f45e21d4282466096bf)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Xiaomi

Model = 23076RN4BI

Hardware = qcom

Webview User Agent = null

ACRA UUID = dce906d5-19f7-4514-a0e4-0071f4f7b489

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
Reproduced!

**Comment by in5omnia** [comment]
Hello, I would love to work on this! I'm going to start working on a fix if that's okay!

**Comment by david-allison** [comment]
@in5omnia Sounds good, thanks!

**Comment by in5omnia** [comment]
Hello, I was about to start fixing this bug and noticed that it's already been fixed by the commit 7a4dfd0 . 
This issue should probably be closed.

**Comment by brishtibheja** [comment]
Yes I noticed I can't reproduced this in the latest alpha.

**Comment by david-allison** [comment]
Thanks! 

* Closed in https://github.com/ankidroid/Anki-Android/pull/16027

**Comment by david-allison** [comment]
Thanks! 

* Closed in https://github.com/ankidroid/Anki-Android/pull/16027
