### ISSUE TITLE
How to find the card, whose media files are not in media folder

### ISSUE THREAD

**Issue by Devaprasad-reddy** [ankidroid/Anki-Android#15809]
I'm always frustrated when I check media, and I get this 
![Screenshot_2024-03-08-11-25-13-43_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/e9a31cf6-88bc-4d8a-bbc6-0b699e79bdef)

I want to know which card is that

I tried searching my card browser but it's vast and didn't find it

Need a way to directly open that card from this popup, so I can re add that card/delete that card.

**Comment by david-allison** [comment]
@CODE-RED-101 Thanks! Please propose a sample design before sending off a pull request

This is to save work on implementing something which may not be desired

**Comment by david-allison** [comment]
@CODE-RED-101 What do you mean by the repository?

**Comment by Devaprasad-reddy** [comment]
![Screenshot_2024-04-18-09-07-05-06_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/da923558-f602-4790-87cb-1638186b64a5)

This happened again, the missing media is increasing day by day I don't know what is missing and I don't know how to find them??? Please help

**Comment by david-allison** [comment]
@CODE-RED-101 is looking into this, little can be done until someone submits some code, and we're all volunteers
