### ISSUE TITLE
[BUG]: New previewer does not show the front and back card contents ( Tablet )

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#15819]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. Enable new previewer from developer options
2. Go to NoteEditor
3. Click on Previewer

### Expected behaviour

New previewer shows contents of front and back card as expected

### Actual behaviour

New previewer does not show the front and back card contents
![newpreviewer](https://github.com/ankidroid/Anki-Android/assets/65113071/5c6e5de0-b733-48af-bb2a-23927cc5561d)

### Debug info

```text
AnkiDroid Version = 2.18alpha3-debug (11d1c414cec871f02645c9ebb5dba3b9c6a84468)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 9 (SDK 28)

ProductFlavor = amazon

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 9; AOSP on IA Emulator Build/PSR1.180720.122; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Safari/537.36

ACRA UUID = f2bd5b67-70e1-4373-b5a1-4cb0a19b67e4

Crash Reports Enabled = false
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
Working on it

**Comment by BrayanDSO** [comment]
Couldn't reproduce

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/a3b55d44-1846-4d94-b603-73980ab9470a)

**Comment by BrayanDSO** [comment]
> Webview User Agent = Mozilla/5.0 (Linux; Android 9; AOSP on IA Emulator Build/PSR1.180720.122; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Safari/537.36

cause: outdated webview

and you are in a debug build, so the warning at the startup should have been enough
