### ISSUE TITLE
[BUG]: New/review card count wrong

### ISSUE THREAD

**Issue by Mornon** [ankidroid/Anki-Android#15810]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Just open Anki, I didn't need to do anything else.

### Expected behaviour

New and review counts should be according to what was created and chosen in the settings.

### Actual behaviour

I have 100 reviews/day as review limit and new cards limit; yesterday I created 12 new cards, today I have zero new cards (despite the one I created being in the deck, I can see them as new in the browser) and 73 new cards (despite having 155 in the deck). This is a behavior I noticed before in Anki Desktop, so I guess it depends on that code being used in AnkiDroid too.

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = Xiaomi

Model = M2101K9AG

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; M2101K9AG Build/TKQ1.221013.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = a847dd05-7838-4957-9776-526227578aba

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Mornon** [comment]
I noticed some of the red cards were card I already had reviewed, and when I reset some cards' progress they were added to the green/review cards instead that in the blue/new cards, as with the previous version; another deck seems to work fine, though, and I have no idea of what's different.

**Comment by david-allison** [comment]
Hi, thanks for the report

If it's an Anki Desktop issue, could you report it here: https://forums.ankiweb.net/

I'll add a new issue template to avoid this in future

**Comment by Mornon** [comment]
It's not an Anki Desktop issue, I'm having it on AnkiDroid: it's _also_ on Anki Desktop, but now it's also on AnkiDroid, I'm having it right now on my phone.

Update: custom study > increase daily review made all the new cards appear.

**Comment by david-allison** [comment]
As of 2.17, we're using Anki Desktop code for almost all of our scheduling.

We aim to be consistent with Anki Desktop, even if there are perceived problems with the approach

**Comment by Mornon** [comment]
I understand that, but "There are 12 new cards with a daily limit of 100, and 155 new cards with a daily limit of 100; I see 0 new cards and 73 reviews" doesn't seem to me a perceived problem: if the limit is 100, shouldn't I see up to 100 cards?

With 100 new cards/day and 12 new cards in the deck, I would expect to see 12 new cards; I see 0.

With 100 reviews/day and 155 reviews in the deck, I would expect to see 100 new cards; I see 73.

Is this the expected behavior?

**Comment by david-allison** [comment]
Is it occurring on Anki Desktop? 

If so, it's a question to raise on the forums. There's no AnkiDroid related changes to be made

If not, it's appropriate for GitHub

**Comment by Mornon** [comment]
Yes, it's occouring also on Anki Desktop; I'll report it on their forum, thanks.

**Comment by Mornon** [comment]
It doesn't seem to be a bug, it can be solved by turning on "New cards ignore review limit" in deck options; it seems with the new code new and interday cards are counted in the review limit.
