### ISSUE TITLE
[BUG]: Statistics and Congratulations screen require an internet connection (TypeError: Failed to fetch)

### ISSUE THREAD

**Issue by Sayrus** [ankidroid/Anki-Android#15828]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Disable internet access for the app (or disable internet globally)

Either:
- Open Statistics
- Review a deck
- Open a reviewed deck

### Expected behaviour

For reviewed deck and when ending session, congratulations message should appear without requiring internet:
![Screenshot_2024-03-10-01-00-47-191_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/22404472/9aa8db0f-19e0-4939-80cd-2e29050bdf90)

For statistics, it should probably work without internet but maybe an external library is required there.

### Actual behaviour

When finishing a review, an error will occur.
When clicking on an already reviewed deck, an error will occur.
When clicking statistics on the left menu, an error will occur.

![Screenshot_2024-03-10-01-00-29-839_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/22404472/9e8b64b8-fb1c-4b46-93b4-5a55c3637011)

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 10 (SDK 29)

ProductFlavor = play

Manufacturer = Xiaomi

Model = Mi MIX 3

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Mi MIX 3 Build/QKQ1.190828.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.66 Mobile Safari/537.36

ACRA UUID = 27f3eea7-a8dd-423e-8f54-e7bbb5987934

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

I don't remember this being an issue until a march update.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
I believe this is fixed upstream in https://github.com/ankitects/anki/commit/db1aecd3d8d3dba40973ac842dd40aeab6f9fd2e

This will be completed once we upgrade to use Anki 24.04. No action for us to take currently

Thanks for the report!
