### ISSUE TITLE
Auto-postpone Leeches

### ISSUE THREAD

**Issue by johncaiwa** [ankidroid/Anki-Android#15823]
**Is your feature request related to a problem? Please describe.**
Waiting is often the best way to deal with leeches. However, there is no way to auto-postpone leeches like in SuperMemo.

**Describe the solution you'd like**
See: https://www.help.supermemo.org/wiki/Leeches#Leech_Hunting_Options
An option to auto-postpone leeches. Preferably with some sort of randomization.

**Describe alternatives you've considered**
All the leeches I have ever gotten just remain suspended. Ideally, I would like to pull from the leech pile little by little randomly, automatically.

**Additional context**
Again, see: https://www.help.supermemo.org/wiki/Leeches#Leech_Hunting_Options

**Comment by david-allison** [comment]
Hi @johncaiwa, thanks for using AnkiDroid & your feature request. 

Could you submit this to https://forums.ankiweb.net/c/suggestions/17, we're aiming to maintain strong consistency with Anki Desktop's feature set, so we're unlikely to implement a feature unless it's first implemented by Anki Desktop.

Best wishes,
David
