### ISSUE TITLE
Sort decks in Deckpicker to the bottom of the screen

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#15824]
**Is your feature request related to a problem? Please describe.**
Mobile phones are too big in these days and it is impossible to reach top of the screen by one hand. Decks in Deckpicker are sorted from top of the screen therefore it is impossible to choose the first deck by one hand.

**Describe the solution you'd like**
Deck list should start in the middle of the screen so the first deck can be opened by one hand. If there is a lot of decks, the user could scroll the list down so whole screen would be used. If the user scroll up, the scrolling would stop in the initial position - the first deck in the middle of the screen. You can see and try this concept e.g. in Samsung app Contacts (Android 13, One UI 5.1). 
The same concept could also be used in Card Browser and Settings but the Deckpicker is the most critical as users use it daily.

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20240309_164306_AnkiDroidB](https://github.com/ankidroid/Anki-Android/assets/10192661/fff3814a-7f16-4dee-a386-56906b88486f)
![Screenshot_20240309_164313_AnkiDroidB](https://github.com/ankidroid/Anki-Android/assets/10192661/c5f9f1d7-474d-4ebe-8a66-0645018fa033)

**Comment by xenonnn4w** [comment]
it's too vague to say impossible , and on the other hand the empty space left above does'nt look much nice to eyes !

**Comment by pavreh** [comment]
"Impossible" means "I don't have so long thumb to open the first deck." 
The empty space is exactly the same as now if you have few decks only. It is just above decks and not below them.

**Comment by BrayanDSO** [comment]
IMHO, it doesn't look good and seems quite unnatural to me.

**Comment by david-allison** [comment]
Agreed, it's an unusual design

I've said a couple of times that we'll eventually want to tackle a new home screen. 

We also have Google Summer of Code, where one of the projects may be tablet mode improvements

It would be useful to document the default thumb positions on a tablet so we can better design for the two above scenarios

**Comment by jainishrpandya** [comment]
We can design something like shown in the screenshot, in which it shows decks in the lower half and shows other information in the upper half. but when the deck list is scrolled. the upper half get shrunk and the list covers the majority area of the screen.

in the upperhalf we can also put spinner that gives option to the user to filter like show all the decks and their subdecks or show subdecks of a particular deck. and we can also shift the "Studied 87 cards in 23 minutes today (3.7sec / card) line to the upperhalf.

 

 
Note : This Screenshot is just for the layout reference.
<img src="https://github.com/ankidroid/Anki-Android/assets/69842037/cff83875-a619-4e04-aa5f-3afb888b296e" alt="image" width="200px"  />

**Comment by BrayanDSO** [comment]
Still wouldn't look good IMO.

**Comment by pavreh** [comment]
This design is used in a lot of mainy Samsung apps and it is practical as you can reach buttons by one hand.
