### ISSUE TITLE
[BUG]: Code formatting lost when editing card

### ISSUE THREAD

**Issue by gowerc** [ankidroid/Anki-Android#15820]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

On a PC (I used a Mac) create a code block including newlines. On mobile try to edit the code. When next viewing the card it all collapses onto a single line. (Note that code renders perfectly fine before attempting to edit the card on mobile).

## What I see in the editor:
<img src="https://github.com/ankidroid/Anki-Android/assets/8447209/15a50f22-4127-4f18-bf3d-9754e6cd3954"  height="280px">

## How it gets rendered:
<img src="https://github.com/ankidroid/Anki-Android/assets/8447209/7cbe0135-2070-4736-9577-bd2dca80c89f"  height="280px">

### Expected behaviour

Code formatting is maintained when opening the card for editing on mobile

### Actual behaviour

Code newlines are replaced with something and no longer get rendered properly.

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 8

Hardware = shiba

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Build/UQ1A.240205.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = 82ca0447-81c1-4d26-87f9-85fe648f01c0

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by shameertaggar** [comment]
I have some experience with these kind of bugs, can you assign this to me ?

**Comment by david-allison** [comment]
This is probably a case of `Settings -> Advanced -> Replace newlines with HTML`.

@gowerc have you tried this option?

**Comment by david-allison** [comment]
For most of AnkiDroid's history. Any instances of `<br>` in the fields of a note are converted to `\n` when viewed in the card editor.

On save, this converts from `\n` to `<br>` when saving the card. Leading to a lossy conversion.

Disabling the preference disables this behavior.

This stems from the fact that the note editor currently represents the HTML, but regular users would neither know nor care how to make a HTML newline.

The longer-term fix will be to replace the Note Editor with a visual editor. For now this preference exists for advanced users to stop the `<br>` -> `\n` -> `<br>` roundtrip
