### ISSUE TITLE
Pause Timer When Using Floating Windows

### ISSUE THREAD

**Issue by fjgcfxgvjn** [ankidroid/Anki-Android#15839]
While studying vocabulary with Anki, I sometimes use a floating dictionary window to look up words. However, I've noticed that the timer pauses whenever I use these floating windows. This significantly affects the accuracy of the estimated completion time

**Comment by BrayanDSO** [comment]
I'm sorry, but we are with the hands tied on that due to Android limitations. Floating windows like that are considered separated app/processes by Android and we can't differentiate when they are used or not.
