### ISSUE TITLE
Move `Add` button to tool bar in IO editor

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#15838]
**Is your feature request related to a problem? Please describe.**

The tool bar is shown in at bottom of IO editor. The `Add` call JS method, so it should be better to move it to android toolbar.

**Describe the solution you'd like**

It will be removed later (ongoing refactoring), so for now hide it by injecting CSS and add `Add` button to toolbar which calls JS method attached to the button.

**Additional context**

<img height=450px src="https://github.com/ankidroid/Anki-Android/assets/12841290/27c8a802-50f8-4a77-98ff-02c6e6515b49"></img>

**Comment by krmanik** [comment]
Wait for it, the issue may solved after refactoring of IO done on upstream.

**Comment by criticalAY** [comment]
Not sure if it would be a good first issue or not considering the work around it *may need*

**Comment by krmanik** [comment]
It will be easy after this

https://github.com/krmanik/anki/commit/c42de3505bede223bb05ec5e812c21cc1efed262

**Comment by xenonnn4w** [comment]
I'm interested in taking on this task; could I be assigned to it?

**Comment by xenonnn4w** [comment]
@krmanik does it get fixed upstream?

**Comment by criticalAY** [comment]
Nope not yet

**Comment by krmanik** [comment]
The issues will be fixed the Anki-Backed 24.04 available in AnkiDroid, till then wait.

**Comment by GajananPalepwad** [comment]
can i solve it @david-allison

**Comment by BrayanDSO** [comment]
Sorry, but given that we are a bit late with 2.18 release, I ended up implementing it
