### ISSUE TITLE
Unifying the expression of "Full Sync" on various platforms

### ISSUE THREAD

**Issue by NameLessGO** [ankidroid/Anki-Android#15831]
> As shown in the picture below, “Full Sync” has been inconsistently expressed on various platforms for a long time, so the translations are also inconsistent.

> For example, different translations in Chinese often cause confusion for new users. Especially users who are not familiar with computer operation and software operation.

> They are already unfamiliar with this concept. Coupled with the inconsistency in translation, users often encounter problems and do not know where to set up.

> I hope this expression can be unified and they will appreciate your work.
https://forums.ankiweb.net/t/unifying-the-expression-of-full-sync-on-various-platforms/42214/1

![image](https://github.com/ankidroid/Anki-Android/assets/66227691/09548619-6a06-4aed-9b69-a18b41dd210c)

**Comment by NameLessGO** [comment]
> I’ve changed the iOS label to “One-Way Sync”. I didn’t want to break the existing translations, so it won’t show up as a change on Pontoon.

**Comment by david-allison** [comment]
What should we set "Forced full sync" to? [appears after someone confirms a one-way sync]

**Comment by david-allison** [comment]
Partially complete here: https://github.com/ankidroid/Anki-Android/compare/main...david-allison:full-sync?expand=1

We also need to rename `Sync (full)` -> `Sync (one-way)`

**Comment by NameLessGO** [comment]
Pontoon Strings for reference

[Please use the Check Database function, then sync again. If problems persist, please force a full sync in the preferences screen.](https://i18n.ankiweb.net/en-GB/core/core/templates/sync.ftl/?search=force&string=23524)

[On next sync, force changes in one direction](https://i18n.ankiweb.net/en-GB/core/core/templates/preferences.ftl/?search=sync&string=23889)

**Comment by NameLessGO** [comment]
`Confirm One-way sync` since it is a confirmation prompt
