### ISSUE TITLE
[BUG]: card info no longer displayed 

### ISSUE THREAD

**Issue by AlexeyMalafeev** [ankidroid/Anki-Android#15835]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

When reviewing, try to access card info for any card (either from the menu or with a gesture). 

### Expected behaviour

Card info should be shown. 

### Actual behaviour

Leads to a blank screen. No card info is shown. 

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-S918B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S918B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.105 Mobile Safari/537.36

ACRA UUID = c9becef3-d562-44d4-886d-d84836fcf93d

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Card info used to work normally in 2.17.4. I noticed this new incorrect behavior only after upgrading to 2.17.5

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi @AlexeyMalafeev I can't reproduce this. 

Could you send a video reproducing the issue?

**Comment by AlexeyMalafeev** [comment]
> Hi @AlexeyMalafeev I can't reproduce this.
> 
> Could you send a video reproducing the issue?

Sorry, the bug no longer reproduces for me either after the app restart. I should have recorded the video when I came across it the first time. Let's close the issue and reopen it if I encounter the bug again or someone else does. I apologize for taking your time.
