### ISSUE TITLE
[BUG]: ease not reset to 250

### ISSUE THREAD

**Issue by Pierre-The-Rock-Bernier** [ankidroid/Anki-Android#15836]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

When reviewing a card:
- click reschedule
- then click reschedule for review in x days

### Expected behaviour

As the dialog says, I'm expecting that "ease will be reset to 250%)

### Actual behaviour

It doesn't reset the ease to 250%.

Note that this issue started with the new version from a few days ago. Before that, it used to work fine. Meaning it used to reset the ease to 250%.

Thanks in advance for addressing this issue,

### Debug info

```text
AnkiDroid version 2.17.5
Mar 7, 2024
anki 23.12.1 1a1d4d54
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report. Introduced in 2.17. This will be fixed in:

* https://github.com/ankidroid/Anki-Android/pull/15699

**Comment by brishtibheja** [comment]
Why there was a need for resetting Ease to 250 in the first place? I assume this will not affect me now that I use FSRS but in SM2 like some others my default ease was 130/135 for every deck. This was to avoid ease hell. But it also meant I couldn't reschedule my cards otherwise the scheduling gets messed up.

**Comment by phannan** [comment]
I reschedule to avoid ease hell.  If I have a card that I am not getting, I first do something to address the fact that I am not getting it, then I flag it as needing its ease fixed.  When I am next presented the card (and correctly answer it), I "reschedule" it to match the ok time frame.   I would happily switch to another method of getting out of ease hell if it existed.

**Comment by brishtibheja** [comment]
FSRS is the best method right now. Earlier everyone just set their ease to 130 (I usually set it a little bit higher back then).
