### ISSUE TITLE
[BUG]: Discrepancy in deck counts between home screen and deck

### ISSUE THREAD

**Issue by SchiffBased** [ankidroid/Anki-Android#15833]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Opened app after recent update to v. 2.17.5 and found a large discrepancy between the number of review cards on the home screen and the number while studying for one of the decks (my most-used, pictured).

![Screenshot_20240309_221847_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/162874475/3c01309d-d877-43d6-b003-e42c3b1fd6d6)
![Screenshot_20240309_221839_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/162874475/8f1649c1-04d0-4698-9a15-3b627ae95c19)

### Expected behaviour

Number of reviews while studying broadly comparable to number of reviews displayed on home screen.

### Actual behaviour

Number of reviews while studying hundreds of cards lower than number of reviews displayed on home screen.

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A546B

Hardware = s5e8835

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-A546B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = ea26c967-3d2c-4b39-a1d8-5515ef438977

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

The discrepancy is much larger than that due to sibling burying. The issue does not seem to be present for other decks. Reinstalling app & redownloading app data did not fix the issue. The maximum reviews/day is set to 9999 and there are no subdecks. Hope someone can help – thanks!

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, thanks for the report, could you:

* Confirm this doesn't occur on Anki Desktop
* If it doesn't, export the deck, zip it & upload it here

Thanks

**Comment by SchiffBased** [comment]
Hi, thanks for your response. I can confirm that this does not occur on desktop, before or after update (debug info attached). Unfortunately, even the zipped deck exceeds the 25 MB size limit for comments and repositories.

[Desktop debug info.txt](https://github.com/ankidroid/Anki-Android/files/14557451/Desktop.debug.info.txt)

**Comment by BrayanDSO** [comment]
I really expect the same behavior there, since that's how the v3 scheduler works when estimating which cards are going to be buried

**Comment by david-allison** [comment]
Thanks @SchiffBased 

Is it feasible for you to export your collection (without media), zip it and upload it here?

**Comment by SchiffBased** [comment]
Thanks all for your patience. Attached is the zipped collection without media. I re-synchronized the desktop version and now the numbers match the mobile version, so it does just seem to be caused by the v3 scheduler, as suggested by @BrayanDSO. Sorry for the confusion!

![Desktop after sync](https://github.com/ankidroid/Anki-Android/assets/162874475/4a673bee-d11e-4780-a61d-b220e97895da)


[collection-2024-03-11@14-35-19.zip](https://github.com/ankidroid/Anki-Android/files/14559365/collection-2024-03-11%4014-35-19.zip)
