### ISSUE TITLE
The feedback animation for the rating buttons is too fast on a device with higher specifications

### ISSUE THREAD

**Issue by yoshiotobe** [ankidroid/Anki-Android#15849]
**Is your feature request related to a problem? Please describe.**

The feedback animation for the rating buttons is too fast on a device with higher specifications.
The feedback is the white flicker in the yellow area of the attached photo.

![Screenshot3](https://github.com/ankidroid/Anki-Android/assets/38850403/d919a808-f394-4526-bc5b-651a7a12ba8e)

I have just changed my phone from one with 4GB RAM to 8GB RAM (Pixel 7a).
It was visible on the 4GB phone, but it's barely noticeable on the 8GB phone.
Without the visual feedback, it's difficult to know which button I've pressed.
Animations in other apps are fine. I guess they adjust the animation time based on device specifications.

・My old phone: Aquos Sense3 lite
    Android: 11  Ankidroid: 2.16.5  RAM: 4GB  CPU: 2.2GHz (x4) + 1.8GHz (x4)

・My new phone: Google Pixel 7a
    Android: 14  Ankidroid: 2.17.3  RAM: 8GB  CPU: 2.85GHz (x2) + 2.35GHz (x2) + 1.8GHz (x4)

**Describe the solution you'd like**

Would it be possible to make the duration of the feedback animation longer on devices with higher specifications such as more RAM?

**Comment by david-allison** [comment]
Thanks for the suggestion! The dots at the top of the reviewer display the answer which was pressed:

<img width="403" alt="Screenshot 2024-03-11 at 10 56 59" src="https://github.com/ankidroid/Anki-Android/assets/62114487/f7d10c05-c02d-430f-bf63-03c409a3f492">

I believe that we use your system animation settings for the ripple effect:

`<ripple>`

https://github.com/ankidroid/Anki-Android/blob/2e8380a8deb59cb7b323872a8de651f991865606/AnkiDroid/src/main/res/drawable/footer_button_hard_dark_ripple.xml#L2-L12

We wouldn't want to slow down moving to the next card, as that leads to people spending an unnecessary amount of time in the app
