### ISSUE TITLE
Image with `%20` in name can't be rendered

### ISSUE THREAD

**Issue by Nima38** [ankidroid/Anki-Android#15844]
Version: 2.17.5
Galaxy tab s6 t865
Android 12
![Screenshot_20240310_231106_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/133772585/fcd5f711-5222-49b6-af38-21d8c93efaa7)
![Screenshot_20240310_231121_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/133772585/8ca0a17e-bb19-4dd8-be58-349627171e17)

**Comment by david-allison** [comment]
Hi, could you export a bad card, zip it up and upload it here?

Thanks

**Comment by Nima38** [comment]
[anki-image-occlusion.zip](https://github.com/ankidroid/Anki-Android/files/14551675/anki-image-occlusion.zip)

**Comment by david-allison** [comment]
The file is named `Screenshot_20240310_222934_Samsung%20Notes.jpg`

This fails in both Anki Desktop and AnkiDroid

This is presumably due to the literal `%20` in the filename

**Comment by david-allison** [comment]
@Nima38 you should be able to use a different image to continue

**Comment by david-allison** [comment]
@dae FYI

I haven't worked through the internals of IRIs vs URIs, but I believe:

`encode_iri_paths("<img src="Screenshot_20240310_222934_Samsung%20Notes.jpg">")` should return `<img src="Screenshot_20240310_222934_Samsung%2520Notes.jpg`

as the following mapping is required: `%` -> `%25`

**Comment by Nima38** [comment]
Appreciated, that was indeed the case! 

However, I'd like to mention that there was a space in the screenshot name, which caused the problem:

"Screenshot_20240310_222934_Samsung Notes.jpg"

**Comment by dae** [comment]
@david-allison if the filename on disk has an actual space character, then Anki expects the field to also use a space character, which gets converted at display time to %20. If the field has %20 instead, it will get double-encoded.

**Comment by david-allison** [comment]
The filename on disk contains `%20`

Still unknown if this is our issue (I suspect it is). The image was added via the image occlusion screen

We should be using `<img src="Screenshot_20240310_222934_Samsung%2520Notes.jpg">` in the field of the note

<details>

<summary>Screenshot_20240310_222934_Samsung%20Notes.jpg</summary>

![Screenshot_20240310_222934_Samsung%20Notes](https://github.com/ankidroid/Anki-Android/assets/62114487/0b819087-1375-461e-9b2e-72941fc0ae95)

</details>

**Comment by Sahil06012002** [comment]
> [@david-allison](https://github.com/david-allison) if the filename on disk has an actual space character, then Anki expects the field to also use a space character, which gets converted at display time to %20. If the field has %20 instead, it will get double-encoded.

@dae , I was debugging the issue and noticed that if a file name contains encoded characters like %20 (or %25), it doesn’t get double-encoded when displayed. Specifically, the code from https://github.com/ankitects/anki/blob/9b5da546be49f37c8d6c286e09c86074b2f0c278/rslib/src/text.rs#L564 returns the same value for file names with encoded characters. For example, if the file name is test%20.png, it remains as test%20.png when encoding, and the resulting `<img src='test%20.png'/>` tries to find a file named test .png (without the %20), which doesn’t exist. The actual file is named test%20.png, and this mismatch causes rendering issues for media files on both the desktop and Android versions.
Double encoding these media files upstream should resolve the issue. For example, if test%20.png is encoded to test&2520.png, the resulting <img src='test&2520.png'/> will correctly attempt to find a file named test%20.png, which matches the actual file name.
