### ISSUE TITLE
[BUG]: Blank screen shown after finishing a deck on Android 7.1.2

### ISSUE THREAD

**Issue by he29-net** [ankidroid/Anki-Android#15847]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Finish reviewing a deck on an old Android phone (in my case version 7.1.2) in Anki 2.17.5.

### Expected behaviour

The new "Congratulations!" screen is shown.

### Actual behaviour

A blank screen is shown instead: no content and white background (despite dark theme in use). The buttons to go back or to the deck settings are present and work fine.

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 7.1.2 (SDK 25)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G800F

Hardware = universal3470

Webview User Agent = Mozilla/5.0 (Linux; Android 7.1.2; SM-G800F Build/NJH47F; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/60.0.3112.78 Mobile Safari/537.36

ACRA UUID = 4347e38c-8988-4cc2-8df3-bd58f9c72447

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Supporting older Android versions forever may not be suitable, so if the proposal to add an option to disable the "Congratulations!" screen is accepted, one possible solution may be to simply disable it by default on older devices.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Try updating your WebView. Some screens are now web-based and require at least WebView 77, while you are using 60.

Reply again if that didn't work

**Comment by he29-net** [comment]
Hi, thanks for the pointer, it now works correctly. :+1: 

The issue was that Google renamed Web View from `com.android.webview` to `com.google.android.webview`, so it apparently stopped updating years ago.

To fix the Anki issue, it is necessary to:
 1) install the new version (search for `com.google.android.webview` – I could not find it in Play store directly on the phone), and 
 2) disable the pre-installed `com.android.webview` (you may need to enable "Show system" to access it).

Without step 2, the old version takes precedence and the issue persists.

**Comment by david-allison** [comment]
It'd be worth having the dev-only check introduced in https://github.com/ankidroid/Anki-Android/issues/1470 also explain to regular users how to upgrade.

Android 6 supports > WebView 77, so a user should be able to upgrade

* https://github.com/ankidroid/Anki-Android/issues/14702
