### ISSUE TITLE
[BUG]: DARK MODE Bug in the latest update. 

### ISSUE THREAD

**Issue by hu-mann** [ankidroid/Anki-Android#15848]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Dark mode issues in the latest update. Can't see dark characters I'm dark mode at all. Characters were shown in white for dark mode and vice versa before but it is being shown dark in dark mode so it is not visible. 
![Screenshot_2024-03-11-11-30-08-40_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/162940174/d0913903-5828-4ce3-ae2d-4998ffba7850)

### Expected behaviour

Characters should have appeared white in dark mode and dark in light mode. 

### Actual behaviour

Light mode is working fine but characters are shown dark in dark mode so they aren't visible at all 

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = realme

Model = RMX3785

Hardware = mt6835

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3785 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.105 Mobile Safari/537.36

ACRA UUID = 45372720-4860-445e-acc2-78f117a0793a

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, thanks for the report. Please see: https://ankidroid.org/removed-features.html#_automatic_night_mode_color_inversion

Our other support channels should be able to guide you through a fix if you obtained the CSS from a shared deck
