### ISSUE TITLE
[Bug] Card not rendered with Cloze deletion with different types of media

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#15851]
###### Reproduction Steps

Steps to reproduce:
1. Create a cloze card with 2 cloze deletion having 3 of type cloze 1 and 1 cloze 2
2. follow this card format i.e. text(c1) -> img(c1) -> img(c2) -> sound(c1)

Apkg: 
[cloze error-20240311153403.zip](https://github.com/ankidroid/Anki-Android/files/14556792/cloze.error-20240311153403.zip)

###### Expected Result
No error

###### Actual Result
Card not rendered properly 

###### Debug info

```
AnkiDroid Version = 2.18alpha5-debug (8783ae55f0efef0bd4bfad12f51c3c020b94efbd)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = null

ACRA UUID = ee4f42d4-7130-4435-a0d1-67dea2d51513

FSRS Enabled = false

Crash Reports Enabled = false
```

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Possibly solved by #15837 

If not, I don't consider this one high priority because hiding a sound in a cloze doesn't make sense. But it's still an issue

**Comment by BrayanDSO** [comment]
It is fixed

**Comment by criticalAY** [comment]
It's fixed
