### ISSUE TITLE
Option to disable 'temporary system audio volume decrease' when anki audio is being played

### ISSUE THREAD

**Issue by 23894jfdk** [ankidroid/Anki-Android#15850]
This feature would be good because sometimes the system sound (mostly music) isn't that loud. A slider to adjust anki volume compared to system volume would be nice as well.

**Comment by BrayanDSO** [comment]
IIRC, that's not exactly feasible. Try using some kind of per-app sound manager, like Samsung's Sound Assistant or the one of Xiaomi (I don't record its name). Other manufacturers probably have a similar solution

**Comment by david-allison** [comment]
To note. Relevant code:

https://github.com/ankidroid/Anki-Android/blob/125a958b80fe5dc4bb442d4730dbc0db092277e9/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/SoundTagPlayer.kt#L50
