### ISSUE TITLE
[Bug] graduating interval set to 3 but sometimes it changes to 2 when reviewing. Started after update.

### ISSUE THREAD

**Issue by TakedownRex** [ankidroid/Anki-Android#15857]
###### Reproduction Steps

1.  Learning steps are 1m 1h 1d
2. Graduating interval is 3
3. Review cards like normal

###### Expected Result
The next day after reviewing the learning cards, the should say 3 days for the green button because the graduating interval is set to 3.

###### Actual Result
The green button say 2 half the time and 3 the other half. I have been told this is because of the fuzz factor. However this must be a bug because why would we have the option to set the interval if the fuzz factor can override it anyway. This will cause me to have to review more often due to the shorter interval.

###### Debug info
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A426B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; SM-A426B Build/SP1A.210812.016; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.64 Mobile Safari/537.36

ACRA UUID = f1821668-85d3-4808-a28d-b3468f819c0f

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
This is intentional: https://faqs.ankiweb.net/the-2021-scheduler.html#fuzz
