### ISSUE TITLE
Productionise WebView >= 77 check 

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15855]
It'd be worth having the dev-only check introduced in https://github.com/ankidroid/Anki-Android/issues/14702 also explain to regular users how to upgrade.

Android 6 supports >= WebView 77, so a user should be able to upgrade

* https://github.com/ankidroid/Anki-Android/issues/14702

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/15847#issuecomment-1988370221_

----

EDIT: Please also include a guide to fix the WebView if the package is incorrect: https://github.com/ankidroid/Anki-Android/issues/15847#issuecomment-1988304056

**Comment by aayush-tripathi** [comment]
Hello again. I have been working on this issue and have come up with the following Dialog Box containing a link to the Google Play Store. 
<img width="316" alt="Screenshot 2024-03-13 024444" src="https://github.com/ankidroid/Anki-Android/assets/112811133/fc8ba1ad-8087-4906-ab49-3c1b257c77e6">
I want to confirm if I have approached this correctly. Thanks!

**Comment by david-allison** [comment]
Looks like a good UI! We'll need to work on the strings, but that can be done in the PR

* Link to a wiki page which we can update later
* See if you can detect if the old package is installed, as this warrants different instructions: 

https://github.com/ankidroid/Anki-Android/blob/818a8134d16d6455993bbf80bd66900db445cd89/AnkiDroid/src/main/java/com/ichi2/utils/WebViewUtils.kt#L40

**Comment by neeldoshii** [comment]
Can i get assigned to this as the above PR is saying `Needs a new dev`?

**Comment by david-allison** [comment]
@neeldoshii done, please use the PR as it's REALLY close + please be sure you're using git cherry pick to give them credit
