### ISSUE TITLE
TypeCloze displays only the typing box but not the information on the cardon Android Anki (AnkiDroid) [BUG]:

### ISSUE THREAD

**Issue by lh9696** [ankidroid/Anki-Android#15853]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. During the review of cards of Type "Type Cloze", Ankidroid only displays the box to type in text but not the text of the card itself. (see attachment "FrontOfCard")
2. Clicking on "Show answer" shows the back of the card with all the text. (See attachment "BackOfCard"
![BackOfCard](https://github.com/ankidroid/Anki-Android/assets/162983602/c87fb38a-213c-4100-b21e-0254c2c8261f)
![FrontOfCard](https://github.com/ankidroid/Anki-Android/assets/162983602/e1f3bec0-6aaa-4c4a-a8c9-3eb643633079)

### Expected behaviour

The front of the card should display all text and boxes for the clozed information where I can type in the answer. 

### Actual behaviour

see What are the steps to reproduce this bug?

### Debug info

```text
no debug info
```

### (Optional) Anything else you want to share?

Below the card settings:
![image](https://github.com/ankidroid/Anki-Android/assets/162983602/c4e7fb53-b2ad-4b60-8914-29e4bc5d0dff)
![image](https://github.com/ankidroid/Anki-Android/assets/162983602/74a6e92d-87f1-42d1-97ce-4e73e5011d11)
![image](https://github.com/ankidroid/Anki-Android/assets/162983602/72f147b3-412d-484d-b6b9-a57de3310911)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lh9696** [comment]
I hope this is what you need:

*Front template*

html
{{type:cloze:Text}}


<link rel="stylesheet" href="_ch-pygments-solarized.css" class="anki-code-highlighter">
<link rel="stylesheet" href="_ch-hljs-solarized.css" class="anki-code-highlighter">
<script src="_ch-highlight.js" class="anki-code-highlighter"></script>
<script src="_ch-my-highlight.js" class="anki-code-highlighter"></script>


</br></br>

{{clickable:Tags}}



*Back template*

html
{{cloze:Text}}<br>
{{Back Extra}}<br>
{{clickable:Tags}}


<link rel="stylesheet" href="_ch-pygments-solarized.css" class="anki-code-highlighter">
<link rel="stylesheet" href="_ch-hljs-solarized.css" class="anki-code-highlighter">
<script src="_ch-highlight.js" class="anki-code-highlighter"></script>
<script src="_ch-my-highlight.js" class="anki-code-highlighter"></script>






*Styling*

css
.card {
    font-family: arial;
    font-size: 20px;
    text-align: left;
    color: black;
    background-color: white;
}
.cloze {
    font-weight: bold;
    color: blue;
}
.nightMode .cloze {
    color: lightblue;
}

.win {
max-width: 60%;
margin: auto; }

**Comment by david-allison** [comment]
The following doesn't work in either Anki Desktop or AnkiDroid

[15853.apkg.zip](https://github.com/ankidroid/Anki-Android/files/14559031/15853.apkg.zip)

----

What does this look like on Anki Desktop without addons enabled (hold shift while starting)?

If this does work in Anki Desktop, could you export a card/deck, zip it up and attach it here
