### ISSUE TITLE
Too much precision regarding time (in 11.2 minutes...)

### ISSUE THREAD

**Issue by tbm** [ankidroid/Anki-Android#15862]
**Is your feature request related to a problem? Please describe.**

After the recent upgrade, I get very detailed information, such as `186 cards in 11.2 minutes today` and `8.4h good`.  I'm pretty sure this level of precision wasn't there before and I don't find this useful at all.  11 minutes and 8h would be much clearer.

**Describe the solution you'd like**
Please revert the added precision that adds no value and is distracting.

**Comment by david-allison** [comment]
Hi, thanks for the report. We use Anki Desktop's string here, which uses the same amount of precision.

Could you add this as an issue on the forums: https://forums.ankiweb.net/c/suggestions/17

![Screenshot 2024-03-12 at 12 26 02](https://github.com/ankidroid/Anki-Android/assets/62114487/79b439aa-026b-4bb5-8b5c-bbfa74097f4e)

**Comment by tbm** [comment]
Someone reported it already: https://forums.ankiweb.net/t/reduce-precision-of-time-studied-today/42309

I'll add a comment there.
