### ISSUE TITLE
[Enhancement] Crop tool for image occlusion

### ISSUE THREAD

**Issue by Devaprasad-reddy** [ankidroid/Anki-Android#15864]
**Is your feature request related to a problem? Please describe.**
I want to crop out giveaways in an IO card but to do it I had to delete the card and crop it in my phone and upload as a new card, which also makes me loose the progress of that card

**Describe the solution you'd like**
A crop tool in the IO editing interface would be nice to have

**Describe alternatives you've considered**
Creating a New card again.

**Additional context**
Also two finger pan would be nice instead of 4 buttons to zoom in and out.

**Comment by awanishyadav967** [comment]
I would like to work on this @david-allison

**Comment by david-allison** [comment]
Thanks! See the following for how we currently open a crop tool:

https://github.com/ankidroid/Anki-Android/blob/a2c16051a4891292e6c571d5f1fac7910311997b/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.kt#L98

**Comment by criticalAY** [comment]
Just in case #15029 get merged before this then we just need to call the method

**Comment by awanishyadav967** [comment]
Hi @david-allison I created the new PR ,Please Review it.

**Comment by david-allison** [comment]
@awanishyadav967 In future, no need to ping me on GitHub, I already get notifications for new Pull Requests, and Discord can be used for 'you should look at this' pings if it's not reviewed in a sufficient amount of time

**Comment by Devaprasad-reddy** [comment]
Is this out..?
