### ISSUE TITLE
DialogFragment: catch `button { }` launching a job

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15898]
`positiveButton() { }` launches a job, which is scoped to the dialog

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/15699#issuecomment-1997853288_
            
----

This cancels the job when the dialog is closed by the positive button press

**Comment by Giyutomioka-SS** [comment]
@david-allison What needs to be done here?

**Comment by david-allison** [comment]
This feels too low priority to work on, compared to features and bug fixes
