### ISSUE TITLE
[BUG]: Syncing no longer works with 2.17.5

### ISSUE THREAD

**Issue by deejayem** [ankidroid/Anki-Android#15896]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

Since upgrading to 2.17.5, syncing is no longer working, but I do not get an error. When I press the sync button, something pops up, and then immediately disappears (before I can see it, but presumably it's the usual synchronisation modal), and then I see "Collection synchronized".

However, in AnkiWeb, the counts are not updated to match what's in the app. (I only noticed this because I was shown a message in the app about not having synced for a while, but I sync daily). I tried forcing a full sync, but that also finished almost immediately, and didn't make any difference.

### Expected behaviour

Sync works correctly, and the number of due cards in AnkiWeb matches AnkiDroid

### Actual behaviour

The number of due cards in AnkiWeb is different to AnkiDroid

### Debug info

```text
AnkiDroid Version = 2.17.5 (1c1aa94ec466f37d33fd2f75020d9f9021ac811e)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 8

Hardware = shiba

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 8 Build/UQ1A.240205.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.66 Mobile Safari/537.36

ACRA UUID = a187afa0-398a-4caa-8d6f-eaa3b57e0d05

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

I have been happily using AnkiDroid for well over 10 years - thank you!

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@deejayem Could you record a video so we could diagnose what's going on?

**Comment by criticalAY** [comment]
Can't reproduce

**Comment by deejayem** [comment]
@david-allison here is a video of AnkiDroid, and a screenshot of what I see in AnkiWeb after. Thank you for the APK link.

https://github.com/ankidroid/Anki-Android/assets/2564003/6a6214f9-38a9-4dbd-bcbb-44fa6c9e5898

![Screenshot_20240314-180021](https://github.com/ankidroid/Anki-Android/assets/2564003/76463c29-4af3-42d1-87fd-88d5478f370e)

**Comment by deejayem** [comment]
Strange, in the parallel version, I also saw 0 cards due, as soon as it had downloaded everything from AnkiWeb. But even after syncing again with the parallel version, I still see cards due to review in AnkiWeb.

**Comment by david-allison** [comment]
Your 'flashing screen' is normal.

![Screenshot 2024-03-14 at 18 45 05](https://github.com/ankidroid/Anki-Android/assets/62114487/754d2d8c-88b5-4568-8512-3a7309a513c4)

**Comment by david-allison** [comment]
Any possibility you could share your collection?

If you'd be fine to share it publicly, you can upload a `.zip` here, if not, you can send it to my gmail: davidallisongithub

We'd want an export of your collection with scheduling, without media, zipped

**Comment by deejayem** [comment]
[djm_anki_collection.zip](https://github.com/ankidroid/Anki-Android/files/14606912/djm_anki_collection.zip)

Is this what you want? I did an export in AnkiDroid (colpkg), and compressed it.

**Comment by david-allison** [comment]
That's showing 0 cards on Anki Desktop and AnkiDroid... unusual.

To confirm: you've refreshed AnkiWeb after syncing?

Are you running under any proxies?

----

The next step would be to get a `logcat` trace of what AnkiDroid 2.17 is doing

**Comment by deejayem** [comment]
Apologies, I think there is no actual issue here, apart from the message I received about not having synced for a while.

It turns out that the numbers I see in AnkiWeb are actually cards to learn, not to review. I was confused by 1) the initial (incorrect) message, 2) those numbers showing in AnkiWeb, but being hidden in AnkiDroid, as they are for sub-decks (or whatever the correct terminology is), that are collapsed by default, and 3) the new version seeming to sync much more quickly.

So thank you for looking into this, but since I can't reproduce the actual issue with the first message, I'll close this and raise a new issue if I see it again.

**Comment by david-allison** [comment]
@deejayem Thank you SO MUCH for the update, this one was worrying, and I'm glad it was just subdecks not appearing

To another decade of Anki usage!

![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExOW90NTh4dHVrNTBzemZreG01d3EwbTY1cG0zY3c0OXZ3cWx1cGoyZyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/BPJmthQ3YRwD6QqcVD/giphy.gif)

Please do log any other issues if you find any, user feedback is vital for us
