### ISSUE TITLE
JS API feature request: edit field during review

### ISSUE THREAD

**Issue by hxse** [ankidroid/Anki-Android#15904]
**Is your feature request related to a problem? Please describe.**
edit field and save field with js api, just like addon [Edit Field During Review](https://ankiweb.net/shared/info/385888438)

**Comment by krmanik** [comment]
I don't think it can be implemented because the addon directly modifying the notes during review which we should avoid in mobile clients.

**Comment by hxse** [comment]
@krmanik https://github.com/krmanik/ankidroid-js-addon
Can we expect this project coming for edit and save field?

**Comment by krmanik** [comment]
May be, I am not sure, because it is purely experimental, we may implement some API depending upon user request and demand which lets addon developer to implement feature they need. The JS Addon Support is in idealist of GSoC 2024, maybe we get addon support soon.
