### ISSUE TITLE
JS API feature request: send Android intent

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#15903]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to send an intent to another application via the JS API. Specifically, I want to run a Termux script when TTS stops speaking, and I'm halfway there with `api.ankiTtsIsSpeaking()` and a loop.

**Describe the solution you'd like**

A method, `sendIntent()` ?, to send an intent to another app. I'm familiar with the format of various intents I'd be sending and can already send them from automation based apps

**Describe alternatives you've considered**
N/A

**Additional context**

For my specific purpose, I may eventually need AnkiDroid to request Termux's [RUN_COMMAND] permission, though I guess it would be safer for me to send an intent from AnkiDroid to another app which already has that permission :)

**Comment by BrayanDSO** [comment]
Seems quite dangerous to me, and the use case is very niche. So from me, it's a no.

**Comment by BrayanDSO** [comment]
If you are in that deepness of hacking stuff, building your own version of AnkiDroid with this patch, would be the way IMO, but that's not safe for most users, even advanced ones

**Comment by sudomain** [comment]
No worries, thanks.
