### ISSUE TITLE
Need colour to know clicked button in IO interface 

### ISSUE THREAD

**Issue by Devaprasad-reddy** [ankidroid/Anki-Android#15907]
**Is your feature request related to a problem? Please describe.**
I'm always double checking to know whether the merge tool is clicked or not because of very poor colour changes in the top bar in black theme

**Describe the solution you'd like**
A blue colour blink will give a better feedback 

**Describe alternatives you've considered**
I check in my card to see changes

**Additional context**
![Screenshot_2024-03-15-15-55-51-40_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/cd456407-8fdd-46dc-931b-7764ff80da1f)
![Screenshot_2024-03-15-15-55-26-36_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/36725943/82c29c22-2a11-4cf7-8640-0bade5b4b175)

**Comment by krmanik** [comment]
It will be done in next PR.

**Comment by krmanik** [comment]
Fixed in 24.04.
