### ISSUE TITLE
Save image with space instead of `%20` when adding before IO setup

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#15908]
I found that in case of Anki Desktop the files are saved with space but in case of AnkiDroid the files are saved with `%20` instead of space. If I manually edit file name in `AnkiDroid/collection.media` and remove `%20` the files are loaded in reviewer also, so issues in adding image to collection also before setup IO editor.

_Originally posted by @krmanik in https://github.com/ankidroid/Anki-Android/issues/15890#issuecomment-1999487468_

**Comment by criticalAY** [comment]
Taking it up, will push the changes soon
