### ISSUE TITLE
Feature request: Previewer responds to mark/flag keyboard shortcuts.

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#15905]
**Is your feature request related to a problem? Please describe.**
These are 2 requests for the new previewer. I can create a separate issue if needed. With the new previewer, could it please:
* [x] Go back to the card browser when the back button (next to the home button) is pressed
* [ ] Keyboard shortcuts for the flag card and mark note, since the buttons are there

**Describe the solution you'd like**
Back button response and keyboard shortcuts

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by david-allison** [comment]
1. Duplicates 

* https://github.com/ankidroid/Anki-Android/issues/15884
