### ISSUE TITLE
Feature request: Browser keyboard shortcuts

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#15900]
**Is your feature request related to a problem? Please describe.**
Would it be possible to have the following desktop keyboard shortcuts on AnkiDroid's card browser?:
Ctrl + F - begin the card/note search
Ctrl + E - add notes

These are not the only missing browser keyboard shortcuts, but they are the main ones I would use. Please :)

**Describe the solution you'd like**
Keyboard shortcuts in the browser

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by david-allison** [comment]
`Ctrl + E` is already add notes

https://github.com/ankidroid/Anki-Android/blob/78582511a4cbe6309be0b30447167a05eddc6e10/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt#L585-L592

**Comment by sudomain** [comment]
Ah so it is! And Ctrl + F works as well!! Must be a hardware problem with the keyboard I was using earlier. Sorry about that
