### ISSUE TITLE
Synchronize the intervals for the pairs of primary and reversed cards.

### ISSUE THREAD

**Issue by Lucius-Will** [ankidroid/Anki-Android#15917]
I am learning English vocabulary from Oxford CEFR using Anki/AnkiDroid. It's a cool app. It is probably the only one of the interval repetition applications that allows me to adjust the growth rate of the interval for myself.

It often happens that I easily remember a direct translation. But it's hard to remember the reverse translation, or I don't remember the reverse translation at all. Or the opposite happens.

When I learning English words, the "reversed cards" function is very useful. But the problem is that one note gets 2 cards. Direct and reverse. And each of these two cards has its own separate progress. The intervals of two cards from a pair are messy and chaotic.

As a result, two cards get different intervals, where one card can go far ahead and the second one lags behind. This results in a loss of synchronization and more disorder. It's bad.

It would be great if user could choose different models for working with intervals of such card pairs.

1 - Calculation of the average interval for such a pair. And assigning this interval to both cards with a small difference. So that they are shown not on the same day, but with a small interval between them.

2 - The application can also calculate only the interval of the main card. And the interval for the inverted card is calculated so that it is shown only between the displays of the main card.

3 - Or, even better, align the progress according to the card that received the smallest interval. The second card (which has a longer interval) should just be shown next to it for several days.

I like the 3rd option the most right now. But the other 2 can also be useful to many users. The application could offer users to choose one of the models for working with reversed cards in deck preferences.

**Comment by BrayanDSO** [comment]
We use the same scheduler of Anki, so any changes related to that must be accepted and implemented there. So please ask it in Anki Forums.
