### ISSUE TITLE
The answer button with the same color navigation buttons (thick type navigation bar) looks distended

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15912]
Some users using in-screen navigation buttons (thick type navigation bar) seem to feel the current design of the "Show answer" button does not look good nor is it easy to use. I wonder if the design is an unexpected design caused by #15238 or an expected one.

2.16.5 | 2.17.6
---|---
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/d5417b08-ebc8-40a2-818f-317fab387dc9)|![image](https://github.com/ankidroid/Anki-Android/assets/10436072/cf1fa40e-e6b6-43e0-bd6f-274143ac9461)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/12e1a285-97c4-4df1-8005-b200a3b72176)|![image](https://github.com/ankidroid/Anki-Android/assets/10436072/ac566cdb-676f-4f10-a83a-ce647e177b3e)

Making app button and system navigation buttons (thick type navigation bar) a same color is not necessarily bad;
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/079ca127-5c66-42e8-bab4-d68394516162)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/c19b24eb-46b4-47de-9659-6bd3f0597143)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/ce5ae115-f2d4-4920-94de-f7acaeac1dee)

However, in this case, the text only button seems loose and ambiguous by losing the bottom outline. 
Also because its color is the app's button color, not the system button's neutral color, the answer button seems to look as if it is distended.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/05643b69-9f01-4d2d-a7dc-ba1211f1f25f)

###### Debug info
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

Crash Reports Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) (2.18alpha6)

**Comment by david-allison** [comment]
First step would be to see if there's a method to set a divider between the app content and the nav if a user is using this theme

**Comment by snowtimeglass** [comment]
How about the following approach: using an approximate-but-distinguishable color for the navigation bar, for example, reducing the brightness of the bar.

In the samples below, each RGB value was reduced by 4.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/cffec332-3fed-4066-b9d2-9fd8118a2496)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/0d49b5fc-b161-4147-a903-dea08ac5f59e)
This approach may rather improve the appearance of the thin type navigation bar as well. 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/7c0d2b23-8141-412a-b046-ee69257d7b9d)

---

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/fa5e639a-994c-4742-bf05-7132a62cc057" width="200px"><img src="https://github.com/ankidroid/Anki-Android/assets/10436072/6158e288-036f-47d8-8c13-d90e8c32c700" width="200px"><img src="https://github.com/ankidroid/Anki-Android/assets/10436072/0c906fad-af4d-4cae-a70f-756a4dce68e2" width="200px">

**Comment by david-allison** [comment]
@snowtimeglass This is one of those cases where I have to say 'I don't like it'. I can't justify it well, but it feels like one of those things that's ever so slightly annoying when you notice it, then you'll never stop noticing it

**Comment by snowtimeglass** [comment]
I've removed the screen images with relatively clunky-look mock buttons.

Does the feeling still remain?  

And the impression isn't likely to change even if the color difference is made more distinctive?

**Comment by BrayanDSO** [comment]
I also think that the undertone doesn't look good.

IMO, use the default semitransparent black-ish color of Android if the nav bar needs a scrim (i.e. the buttons option) like 2.15 did, and the show answer color if it doesn't (i.e. the gestures navigation option)

**Comment by david-allison** [comment]
I'm happy with that.

My preference: See if we can add a divider if the nav buttons are visible [I suspect this is possible]

If not, revert to 2.15 for when we're using nav buttons

**Comment by snowtimeglass** [comment]
No worries. Thank you two for the feedbacks.

**Comment by BrayanDSO** [comment]
At least in my imagination, a divider won't look good. Using the same color with 70/80/90 of alpha would be another option (different enough to have a reasonable contrast).

**Comment by david-allison** [comment]
I'm not here to block this, let's go with (my) option 2!

**Comment by snowtimeglass** [comment]
> I'm not here to block this, let's go with (my) option 2!

You mean this approach is better?
> If not, revert to 2.15 for when we're using nav buttons

**Comment by david-allison** [comment]
> IMO, use the default semitransparent black-ish color of Android if the nav bar needs a scrim (i.e. the buttons option) like 2.15 did, and the show answer color if it doesn't (i.e. the gestures navigation option)
