### ISSUE TITLE
[Bug] Deleting Deck doesn't update the StudyOptionsFragment in Tablet mode

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#15921]
###### Reproduction Steps

1. Delete Deck

###### Expected Result
StudyOptionsFragment should show another deck details (other than deleted)

###### Actual Result
StudyOptionsFragment still shows deleted deck details

###### Debug info
AnkiDroid Version = 2.18alpha6-debug (14173d3aab96a63611bbf630ba859bc0ad620e1b)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 9 (SDK 28)

ProductFlavor = amazon

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = null

ACRA UUID = 0e18e70d-4cdd-4099-ba65-85d82d40cb91

FSRS Enabled = false

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
I'll work on this issue

**Comment by david-allison** [comment]
Thanks! Please add a test while you're here

**Comment by SanjaySargam** [comment]
Ok

**Comment by SanjaySargam** [comment]
@david-allison This fragment is going to be removed in the future. Should I close this issue?

**Comment by david-allison** [comment]
I don't think we've finalised what we want to do wit thefragment, keep it open for a while, or link to the discussion and decision

**Comment by SanjaySargam** [comment]
Ok
