### ISSUE TITLE
[Feature] Audio can be paused and resumed when play button is clicked

### ISSUE THREAD

**Issue by ellethykhaled** [ankidroid/Anki-Android#15923]
**Is your feature request related to a problem? Please describe.**
When pressing on the play button for an audio within the Flashcard, the audio restarts from the beginning.

**Describe the solution you'd like**
Pressing the play button should pause/resume the audio, and not restart it.

**Additional context**
![image](https://github.com/ankidroid/Anki-Android/assets/62517775/fb349983-c049-432f-93fc-853dd4501642)

**Comment by snowtimeglass** [comment]
The current behavior (replay) is consistent with Anki Desktop and AnkiMobile.

- https://github.com/ankidroid/Anki-Android/pull/8781 
was merged once; 
but it has been changed by
- https://github.com/ankidroid/Anki-Android/pull/14296 
after discussion in
- https://github.com/ankidroid/Anki-Android/issues/14221 
 
(I think that the "adding pause option for audio" idea itself is appropriate. The current problem is that AnkiDroid doesn't have the "Pause audio" option, unlike Anki Desktop and AnkiMobile.)

Related issue:
- https://github.com/ankidroid/Anki-Android/issues/6774
- https://github.com/ankidroid/Anki-Android/issues/13125

**Comment by snowtimeglass** [comment]
The feature of pausing an audio has been implemented in both Anki Desktop and AnkiMobile, while AnkiDroid has yet to have the feature.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/a7576966-d928-40ed-b16a-22f172659f80)
(Anki Desktop)

**Comment by david-allison** [comment]
Closing as https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix as per https://github.com/ankidroid/Anki-Android/issues/14221

* https://github.com/ankidroid/Anki-Android/issues/14221
