### ISSUE TITLE
2.17+ Crashes Samsung Galaxy tab s3[Bug]

### ISSUE THREAD

**Issue by mmartin046** [ankidroid/Anki-Android#15939]
###### Reproduction Steps

1. Begin reviewing cards
2. Tablet eventually freezes and auto reboots. Time from start to crash varies 

###### Expected Result
Unimpaired card reviewing

###### Actual Result
Crashing

###### Debug info
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 9 (SDK 28)

ProductFlavor = play

Manufacturer = samsung

Model = SM-T820

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-T820 Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.168 Safari/537.36

ACRA UUID = 1e9cb9ae-e1d0-4192-a798-6531bd1e0926

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, could you fill out the debug information section please

Thanks!

**Comment by BrayanDSO** [comment]
Hello there. Couldn't find any error traces in our reports database.

Since we can't reproduce this, nor do we have an error trace of it, there's nothing actionable for us to do here.

If it happens again, the report will probably get delivered and we'll know about it.
