### ISSUE TITLE
A hide all guess all mode needed for IO

### ISSUE THREAD

**Issue by Devaprasad-reddy** [ankidroid/Anki-Android#15937]
**Is your feature request related to a problem? Please describe.**
A third button to hide all and guess all would be nice to have

**Describe the solution you'd like**
A button to combine all the masks in a card whenever needed.

**Describe alternatives you've considered**
I'm currently selecting all the masks in the card and pressing the combine button.

**Additional context**
🥲.

**Comment by devharsh2k4** [comment]
can i work on this?

**Comment by krmanik** [comment]
The page comes from Anki, the changes need to be done on upstream, so I don't think it should be done here.
Also, the changes need discussion before implementation. So, @Devaprasad-reddy I suggest creating a new thread here https://forums.ankiweb.net/ for this feature.

**Comment by Devaprasad-reddy** [comment]
Done
