### ISSUE TITLE
[Bug] IO- Adding header in Add note doesn't work

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#15940]
###### Reproduction Steps

1. Add header or comment to IO via `Add`
2. Save it

###### Expected Result
The comment or header should be added

###### Actual Result
Not added

###### Debug info
```
AnkiDroid Version = 2.18alpha6-debug (f9536fcfdf2dd33c8f3937fb2a6adef7a144c32c)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = null

ACRA UUID = 3bb814e8-c56f-47b7-88d7-224c4f4739a2

FSRS Enabled = false

Crash Reports Enabled = false
```

###### Research
The header not added to the note when we add a note but works fine when editing it

originally pointed out by @neeldoshii 

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
specifically, it doesn't if you do it in the `Note editor` fields, but it works if you do it in the IO screen fields editor.

Probably can be workarounded, but I wouldn't bother doing it since the definitive fix should be to use the desktop note editor.

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix Time here would be better spent replacing the Note Editor
