### ISSUE TITLE
Remove or disable congratulations screen

### ISSUE THREAD

**Issue by LouBtl** [ankidroid/Anki-Android#15945]
In the preview ankidroid versions, when I finished my deck, I would automatically go back to my home screen (with an informative snack-bar). This is very convenient for studying multiple decks in a row without any friction.
With the newest versions (which the community truly appreciates), I automatically get a congratulations screen. It requires one more click to go back to the home screen, every time I finish a deck. 
This can add a lot of friction when I have lots of decks to review.

**Describe the solution you'd like**
For my use, simply removing this screen would be a solution. It doesn't bring value to my use.

**Describe alternatives you've considered**
If this positive reinforcement is useful for some users, an option in the settings to switch it off would be ideal.

**Additional context**
![Screenshot_20240229_215746](https://github.com/ankidroid/Anki-Android/assets/44314766/31b3536b-8aef-4ba3-bdff-cf3eac582b76)

**Comment by david-allison** [comment]
Already done in 2.17.6

* https://github.com/ankidroid/Anki-Android/pull/15818
