### ISSUE TITLE
[Bug] Rename deck: do not show an error initially

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15944]
###### Reproduction Steps

1. Long press a deck
2. Select 'rename deck'

###### Expected Result

<img width="585" alt="Screenshot 2024-03-20 at 10 44 04" src="https://github.com/ankidroid/Anki-Android/assets/62114487/a8b439a5-4191-408b-9118-88c1123bb147">

###### Actual Result

No Error

----

If the user has not typed in the box, a 'deck exists' error should not be visible

* A unit test should be added to verify this functionality

**Comment by david-allison** [comment]
References 

* cebb4574df41f662364328549dc091416d5abe9b
* https://github.com/ankidroid/Anki-Android/pull/15808
* https://github.com/ankidroid/Anki-Android/issues/15759

**Comment by parthn2** [comment]
I will like to take up this issue

**Comment by BrayanDSO** [comment]
Or don't show the error message at all in the `Rename deck` dialog

**Comment by Aditya13s** [comment]
@david-allison Please check if this is the final output we need?

https://github.com/ankidroid/Anki-Android/assets/77337791/e69b7cde-b41e-4745-b251-bf7778acbc78

**Comment by david-allison** [comment]
@Aditya13s It would be fair to give @parthn2 an opportunity to solve this, given that they're assigned and it's a https://github.com/ankidroid/Anki-Android/labels/Good%20First%20Issue%21 for them to get started with

**Comment by Aditya13s** [comment]
Sure, let @parthn2 handle it

**Comment by BrayanDSO** [comment]
I particularly don't care much about who does what, I just don't want duplicated work, and @parthn2 already has 3 merged PRs, so they don't need that much the `Good first issue`.

IMO, I say to push it and be more aware if other people already asked to work on the issue.

**Comment by parthn2** [comment]
Yes, sure, @Aditya13s, you can push your work if you have already done it. I was just coming back to the codebase after so long so was looking for a good first issue!
