### ISSUE TITLE
Different Theme/Theming Colors

### ISSUE THREAD

**Issue by knakamura8** [ankidroid/Anki-Android#15942]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Android, as well as many android apps, has different theme/accent color schemes such as purple, orange, etc.  Considering how much time some users such as myself spend within the app, I think it would be pleasant to have at least a few more options aside from light, dark, and black modes.  Seeing as it is just a color setting, and that theming is already enabled within the app, I think there could be a lot of UI/UX gain for what I do not think should amount to much programming effort (though perhaps I am incorrect here).  Perhaps as a stretch goal, the user could type in and/or use a color-picker for a custom hex for the background color, and a custom hex for the foreground color.

**Describe alternatives you've considered**
I have not looked at the codebase myself.

**Additional context**
Love AnkiDroid, thank you, devs!!

**Comment by BrayanDSO** [comment]
I'll join this issue with #13878, but thanks for reporting
