### ISSUE TITLE
[Bug] UI of delete dialog in case of IO is not right

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#15941]
###### Reproduction Steps

1. Add a IO card
2. Open reviewer
3.  Press delete

###### Expected Result
The dialog with the correct UI opens up

###### Actual Result
The UI of the dialog box if messed up
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/0715c985-defa-4846-9810-836b5a0bb205)

###### Debug info
```
AnkiDroid Version = 2.18alpha6-debug (f9536fcfdf2dd33c8f3937fb2a6adef7a144c32c)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_x86_64

Hardware = ranchu

Webview User Agent = null

ACRA UUID = 3bb814e8-c56f-47b7-88d7-224c4f4739a2

FSRS Enabled = false

Crash Reports Enabled = false
```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by neeldoshii** [comment]
I guess issue lies here, commenting this line fixed the weird size of the dialog, investigating for fix.

 https://github.com/ankidroid/Anki-Android/blob/f9536fcfdf2dd33c8f3937fb2a6adef7a144c32c/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.kt#L795

**Comment by brishtibheja** [comment]
Good to see fellow bharatiyas here. There are more of us recently it seems.
