### ISSUE TITLE
[Bug] TTS verbally exposes clozed text on Front of card when the clozed text includes HTML text formatting. (Specifically, ">" character)

### ISSUE THREAD

**Issue by kirbysama** [ankidroid/Anki-Android#15958]
###### Reproduction Steps

1. Create an note with a cloze deletion. 
2. Within the cloze, insert HTML text formatting using the Bold, Italic, or Underline button.
3. Example front card text: This is a {{c1::<u>cloze</u> deletion}} card
4. Enable text-to-speech using the tts tag in the front and rear card templates. 
Example of tts tag used:
{{tts en_US voices=Apple_Samantha,Microsoft_Zira speed=1.5:cloze:Text}}
5. Enter card review and observe the TTS output.

###### Expected Result
TTS reads the card text, and upon reaching a cloze deletion, says "Blank", then continues through any remaining text that is not clozed.

###### Actual Result
Upon reaching a cloze deletion containing HTML, the entire instance of clozed text is spoken, along with some unusual bug text. For example: TTS will say "This is a cloze **data ordinal equals one inches** blank deletion card"

Bolded text is the "unusual bug text". When there is a Cloze 2 or a Cloze 3 that contains HTML formatting, TTS will change the bug text to say **data ordinal equals two inches** or **data ordinal equals three inches**, respectively. If there are multiple  clozes on the same card (i.e. two instances of Cloze 1) but only one contains HTML formatting, only that cloze will be revealed, while the other cloze will be correctly pronounced as "Blank".

More specifically, the offending character seems to be ">". The presence of any number of ">" will result in the entire cloze being revealed.

This effectively breaks the TTS function, as the card review is ruined when the content  is unexpectedly reviewed. Although it may not affect every card in the deck due to lack of formatting in some cards, any cards affected will no longer have an accurate review history in the FSRS algorithm.

This appears to be an issue exclusive to AnkiDroid, it does not seem to affect Anki Desktop, and furthermore, AnkiDroid's legacy TTS engine does not suffer the same issue. The issue is present on both the stable Google Play version and ~~current version~~ 2.18alpha5.

###### Debug info
AnkiDroid Version = 2.18alpha5 (d27c999e562fae2b648b0f45e21d4282466096bf)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = samsung

Model = SM-G781U

Hardware = qcom

Webview User Agent = null

ACRA UUID = cb850a16-7979-44a0-b453-7a8ad418812a

FSRS Enabled = true

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@kirbysama Thanks for the report! Could you try alpha 6?

**Comment by kirbysama** [comment]
@david-allison Ah, my bad, I guess I missed the latest alpha release. It appears to have been resolved in 2.18alpha6.

Sorry, and thanks for your time! Do I need to close the issue?

**Comment by david-allison** [comment]
That's a relief! You can close, or I can close

Thanks so much for both testing and reporting issues!
