### ISSUE TITLE
[Bug] SharedDecks's SearchView cancel icon is misaligned in landscape mode

### ISSUE THREAD

**Issue by SanjaySargam** [ankidroid/Anki-Android#15950]
###### Reproduction Steps

1. Go to SharedDecksActivity
2. Rotate horizontal
3. Search anything

###### Expected Result
Close icon must be align to right side

###### Actual Result
Close icon is somewhere in the middle
![WhatsApp Image 2024-03-21 at 2 12 15 AM](https://github.com/ankidroid/Anki-Android/assets/65113071/7ae12504-5008-42b0-9938-58f944ee1a7c)

###### Debug info
AnkiDroid Version = 2.17beta6-debug (ddc41f4a41dfc603ced2b8c2542f8ea249ca642a)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = 692fd70b-2e8e-4445-a5a8-4facd08d8904

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
This issue can be label as Good First Issue!

**Comment by criticalAY** [comment]
IMO in a bigger screen it would look weird at the end, it would look fine the way it is on tablets, but can hear from others and then decide

**Comment by SanjaySargam** [comment]
![shared](https://github.com/ankidroid/Anki-Android/assets/65113071/e9e154b2-f147-4384-808c-e7e395538524)
This is how it looks on the tablet. 

> it would look weird at the end

I don't think so. This is what we expected

**Comment by david-allison** [comment]
How do other apps do this?

**Comment by neeldoshii** [comment]
> IMO in a bigger screen it would look weird at the end, it would look fine the way it is on tablets, but can hear from others and then decide

I disagree too, the user will need to take a huge hand movement just to clear the text from the search.

> How do other apps do this?

![screenshot](https://github.com/ankidroid/Anki-Android/assets/60827173/09c66090-f50f-44cf-8904-7f3f7d20b66b)
Youtube

![screenshot1](https://github.com/ankidroid/Anki-Android/assets/60827173/a600dcf8-6802-45c1-8ed6-cd4835f4616f)

System Setting

![screenshot2](https://github.com/ankidroid/Anki-Android/assets/60827173/354b672c-b31b-49bd-b4cc-3e0907d10ac3)

Google Photos

**Comment by SanjaySargam** [comment]
Almost all the apps have a close button at the end.

**Comment by BrayanDSO** [comment]
At the end.

**Comment by SanjaySargam** [comment]
Similarly in CardBrowser

**Comment by david-allison** [comment]
Agreed. This is open to work

**Comment by SanjaySargam** [comment]
Working on it
