### ISSUE TITLE
[Bug] New Previewer: Fails to update if any card calls `document.write()`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#15959]
###### Reproduction Steps

1. Have a card with `document.write()`
2. Preview Card
3. Select a new card

###### Expected Result

New card is shown

###### Actual Result

Nothing happens

###### Debug info
AnkiDroid Version = 2.18alpha6-debug (b47b50888cfdaa4f5d7f5e8e1db691b49b4dc9a3)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = null

ACRA UUID = 492e61ec-8cbb-434d-ab67-af62ff9fd9e6

FSRS Enabled = false

Crash Reports Enabled = false

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

## Additional Info

Possibly relevant:

`[INFO:CONSOLE(442)] "Uncaught (in promise) TypeError: Cannot read properties of null (reading 'style')", source: file:///android_asset/backend/web/reviewer.js (442)`

**Front template**

```html
{{Front}}

<script>
const STORAGE_KEY = "example-storage-location";

let existing_storage = localStorage.getItem(STORAGE_KEY);
if (existing_storage === null) {
    existing_storage = 0;
} else {
    existing_storage = parseInt(existing_storage);
}

console.log("This template has been accessed " + existing_storage + " times.");
document.write(existing_storage);

existing_storage = existing_storage + 1;

localStorage.setItem(STORAGE_KEY, existing_storage);
console.log(STORAGE_KEY + " set to " + existing_storage);
</script>
```

**Back template**

```html
{{FrontSide}}

<hr id=answer>

{{Back}}
```

**Styling**

```css
.card {
    font-family: arial;
    font-size: 20px;
    text-align: center;
    color: black;
    background-color: white;
}

```

**Comment by david-allison** [comment]
@BrayanDSO FYI

**Comment by BrayanDSO** [comment]
Most likely a same origin policy issue. Solutions are in https://github.com/ankidroid/Anki-Android/issues/15863#issuecomment-1992190692 (the second one is the ideal)

It will take weeks until I can look at it myself

**Comment by BrayanDSO** [comment]
Actually, for this specific case of the previewers, it can fixed quickly. I'll send the patch

**Comment by BrayanDSO** [comment]
Now that I finally ran this locally, I noticed that it works when initially loading the answer, so it isn't a same origin policy issue.

It also doesn't works in Anki Desktop (23.12.1), so it's an upstream issue:

![image](https://github.com/ankidroid/Anki-Android/assets/69634269/a6537743-80d6-40bc-a080-6c08c032da95)

**Comment by BrayanDSO** [comment]
Closing as upstream issue.
