### ISSUE TITLE
[Feature request] - Add the option "prohibit changing the ease card level" in the "Browse cards" section.

### ISSUE THREAD

**Issue by Lucius-Will** [ankidroid/Anki-Android#15967]
The "ease" level of the cards affects the strength of the "good" and "easy" response buttons. If the card has automatically received a high "ease" level" (130%-150%-...), then the "good" and "easy" buttons increase the intervals too much than set in the deck settings.

If the developers make the "freeze ease card level" function in the "Browse cards" section, then this will easily solve this problem.

Then it will be possible to "freeze the ease level" for certain cards. And then the "good" and "easy" buttons will change the intervals of these cards strictly in accordance with the deck settings, without the influence of any additional coefficients from the "ease" level of the card.

And the user will be able to decide for himself which cards to freeze the "ease" level, and which cards to allow to change the "ease" level.

**Comment by david-allison** [comment]
Hi, does this exist in Anki Desktop?

If not, it'll need to be implemented there before we implement it, please add it as a suggestion on the Anki Forums

Ecosystem compatibility is vital to us, and we don't want to lead in adding core functionality

**Comment by Lucius-Will** [comment]
> If not, it'll need to be implemented there before we implement it, please add it as a suggestion on the Anki Forums

Well, I hope they won't refuse (most likely they will).

A rather strange policy. As far as I know, AnkiDroid does not support extensions. If something is missing in Anki Desktop, then it is easily solved by extensions. Therefore, developers of the desktop version can safely refuse many offers, adding only the most important ones and leaving their version minimalistic.

In light of all of the above, you have a sooooooo strange policy. If they refuse to accept this offer, I can implement this feature as an addon for Anki Desktop, but it won't be possible for Anki Droid.

Do you want to continue not to add features that are not available in the stock version of Anki Desktop, because they are easily added by addons there?

It's a very strange policy.

> Ecosystem compatibility is vital to us, and we don't want to lead in adding core functionality

And in theory, this proposal should not violate backward compatibility.

**Comment by Lucius-Will** [comment]
> Hi, does this exist in Anki Desktop?

I couldn't find this feature in stock Anki Desktop. But there is an addon for it.

https://ankiweb.net/shared/info/1387847178

What does it mean? Will you not implement it? Or if it is available as an addon, is it considered a compatible feature with the Anki Desktop ecosystem?

**Comment by Lucius-Will** [comment]
> Also, most of the features recently implemented in the desktop version can be ported to AnkiDroid with almost no effort with Anki's backend. And `scheduler` features like this one are expected to work the same way in all clients to avoid issues and confusion with different intervals between them.

It's clear. It is a pity that such things happening. Maybe someday everything will be fine. Good luck developing the app. There are few such powerful and functional applications.

In the meantime, we'll have to use this feature via AnkiWeb sync and an addon in Anki Desktop. Maybe I can make a fork of the addon, sharpening it for automatic working in Anki Desktop. So that the addon automatically forces the cards in AnkiWeb to have strictly defined "ease" level values.

**Comment by david-allison** [comment]
Just to clarify: I barely have the time to triage issues currently

We'll keep making progress, but things will take time

**Comment by Lucius-Will** [comment]
> Just to clarify: I barely have the time to triage issues currently
> 
> We'll keep making progress, but things will take time

Yes. The progress is very encouraging. In any case, alternative applications provide incomparably fewer functions.

**Comment by Lucius-Will** [comment]
I just want to leave information about what I found on the topic. For those who will be looking for a solution to a similar problem.

I will probably update the information.

For Anki Desktop:

- Set Card Ease
https://ankiweb.net/shared/info/1387847178
Allows you to manually change the "ease" level of each card. You can select several cards and make them the same "ease" level. These changes can be synchronized with AnkiDroid via AnkiWeb.

- Straight Reward
https://ankiweb.net/shared/info/957961234
Allows to change Base ease reward, Step ease reward, Start at ease, Stop at ease. But this only changes the behavior in Anki Desktop. AnkiDroid's behavior remains standard.

For Desktop and Android:

- Theoretically, we can make an addon for Anki Desktop that will automatically connect to AnkiWeb and change the "ease" level as you want. And these changes will be displayed in AnkiDroid as well.

- Perhaps we can make your own script in "Custom scheduling", which redefines the order of changing the "ease" level of cards, or even make the "ease" level immutable. But I do not yet know exactly how to do this.
