### ISSUE TITLE
[BUG]: Review count different on deck list vs review screen

### ISSUE THREAD

**Issue by cyberfox1** [ankidroid/Anki-Android#15962]
### Checked for duplicates?

- [X] This issue is not a duplicate

### What are the steps to reproduce this bug?

1. view deck list, says 5 new, 152 to review
2. click on deckname to see first card
3. at top says 5 new, 148 to review

### Expected behaviour

Numbers should match

### Actual behaviour

Review numbers are different

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 5

Hardware = redfin

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 5 Build/UP1A.231105.001.B2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = 7b8e7836-559c-48a2-9c46-1caa24251824

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Smeagol2069** [comment]
I am unable to reproduce this issue.
![Screenshot_20240322_123307_AnkiDroid.jpg](https://github.com/ankidroid/Anki-Android/assets/78649849/2bf60549-87aa-4cf9-843d-ab2e0141499e)

![Screenshot_20240322_123301_AnkiDroid.jpg](https://github.com/ankidroid/Anki-Android/assets/78649849/74001a7c-5de9-41a6-84a7-2920040b093b)



```
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-S901U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S901U Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = ed6255eb-d61b-4e53-b405-7e3048693f3b

Crash Reports Enabled = true
```

**Comment by BrayanDSO** [comment]
If you have defined to bury siblings/etc in deck options, the cards that are going to be buried are removed from the count after opening the reviewer. It cant be done before opening it because the deck you chose may influence in the scheduler ordering. 

The same happens in Anki Desktop

**Comment by BrayanDSO** [comment]
If you want that behavior changed, please report it at the Anki Forums and we will consume the change automatically if it happens

**Comment by cyberfox1** [comment]
> If you have defined to bury siblings/etc in deck options, the cards that are going to be buried are removed from the count after opening the reviewer.

I do bury siblings, so maybe that's why. If it's the expected behavior then OK I guess but it does seem  bit strange.

> It cant be done before opening it because the deck you chose may influence in the scheduler ordering.

I find this a bit strange. I thought decks were independent (i.e. a card can only be in one), so how does opening a deck get more information than the summary screen?

> 
> The same happens in Anki Desktop

Interesting I looked in desktop and its a bit different. On the deck screen it says "119 + 2" whereas the summary says "121".

![image](https://github.com/ankidroid/Anki-Android/assets/39321046/ba8f8c35-b153-4f45-b81d-04b0b83cf57a)

![image](https://github.com/ankidroid/Anki-Android/assets/39321046/27f7fe8c-3081-44e8-9f4d-5616dc4cd796)

**Comment by BrayanDSO** [comment]
> Interesting I looked in desktop and its a bit different. On the deck screen it says "119 + 2" whereas the summary says "121".

there’s already an issue for doing that here

> I find this a bit strange. I thought decks were independent (i.e. a card can only be in one), so how does opening a deck get more information than the summary screen?

I also found that strange, but it’s something about decks’ order and how the scheduled cards are organized, according to Damien (Anki’s main dev) IIRC.

**Comment by cyberfox1** [comment]
> there’s already an issue for doing that here

In that case close this ticket
