### ISSUE TITLE
[Feature request] - Add the ability to manually change the "ease" card level in the "Browse cards" section.

### ISSUE THREAD

**Issue by Lucius-Will** [ankidroid/Anki-Android#15965]
Actually, in the "Browse cards" section, you can reset the cards intervals. But for some reason it is impossible to change the "ease" level.

It turns out that if the card had a high "ease" level, and if you reset the card intervals, the "ease" level remains the same as it was, and it cannot simply be reset to basic 100%.

This is especially a problem if you had to discard a lot of cards and all of them had the "ease" level not reset to basic.

That's why I suggest adding a function to change the level of "ease" cards in the "Browse cards" section. We can change the intervals of the cards. So why don't we have the ability to manually specify the "ease" level of the same cards?

**Comment by brishtibheja** [comment]
I downloaded 2.16 alpha last year and it changed my ease to 250 from 130 for no reason. Would've loved this feature then but now thankfully I have FSRS.

**Comment by david-allison** [comment]
Will need to be implemented in Anki Desktop before we implement this
