### ISSUE TITLE
An option for a more minimal loading indicator

### ISSUE THREAD

**Issue by avshyz** [ankidroid/Anki-Android#15974]
**Is your feature request related to a problem? Please describe.**

Hello, as a long-time user, I've always appreciated this app. Initially, the syncing process was quite slow, sometimes taking up to ten seconds, so the "popup" loading indicator wasn't much of an issue for me. However, following one of the recent updates, the synchronization speed has improved significantly (kudos on that!), but now the loading popup seems out of place. It appears abruptly, without any text, and vanishes just as quickly.

https://github.com/ankidroid/Anki-Android/assets/3249081/8b494be1-5652-4fe1-917e-4edae20f8b69

**Describe the solution you'd like**

Considering the update now takes less time, the UI should be updated accordingly. A loading bar similar to the one shown at the provided link could be less distracting (for example, something like this https://klendi.github.io/react-top-loading-bar/). Additionally, the popup's cancel button could be relocated to the actions menu, alongside options like "undo last review" or "export."

**Describe alternatives you've considered**
An icon to sync progress is located at the top right corner of the screen (the 🔄 symbol in my recording). As an alternative, I've considered having it spin to signify that the progress is loading.

**Additional context**

**Comment by BrayanDSO** [comment]
That dialog that you are seeing is the media sync dialog. It already was replaced by a notification and it runs in the background:

https://github.com/ankidroid/Anki-Android/assets/69634269/fe3b9cfd-7abf-456d-82e1-352eb1f37688

The `Syncing collection` dialog will likely have to stay. While syncing the collection, most of the actions can’t be done to avoid any kind of corruption or a bad synchronization, and using a modal dialog is probably the best way of doing that, while other alternatives are much, much more complex.

It also doesn’t show up if the operation is very fast, like in the video you sent.

Given that both of your use cases are likely solved, I believe that this could be closed.

**Comment by avshyz** [comment]
I didn't understand the last part, because for me it does show up.

Could this be a bug?

**Comment by BrayanDSO** [comment]
The `Media Sync Log` dialog was replaced in 2.18.

The `↑ Added ↓ Removed`, which syncs the collection, dialog needs to stay. It only doesn't show up if the operation is really quick (<600ms), and it doesn't show up in the video you sent.

**Comment by avshyz** [comment]
Ok, sorry, now I understand!

I've tried installing the prerelease version (alpha6) and.. it still has the old media sync dialog.
Should I do something to enable the new media sync notification?

**Comment by BrayanDSO** [comment]
It will be shipped in 2.18alpha7. Sorry for the lack of information

**Comment by avshyz** [comment]
No need to apologize! Thanks for your help and patience :)
