### ISSUE TITLE
Ankidroid filtered deck, automatic display answer

### ISSUE THREAD

**Issue by stasimon1** [ankidroid/Anki-Android#15986]
It would be great if "the automatic display answer" worked with "the filtered deck"

version: 2.17.6

![image](https://github.com/ankidroid/Anki-Android/assets/148726259/3e6dea5b-007a-4880-997e-3eaac9a30fb6)

**Comment by SanjaySargam** [comment]
@stasimon1 It's already there

**Comment by david-allison** [comment]
@stasimon1 How does Anki Desktop differ to AnkiDroid?

**Comment by stasimon1** [comment]
Hi David
Desktop version has a lot of more tools and add-ons. 
Regards.

**Comment by stasimon1** [comment]
> @stasimon1 How does Anki Desktop differ to AnkiDroid?

Hi
Adjustable "playback speed" for audio cards (separately for each fields) also would be a great tool."
Thanks you and regards.

**Comment by david-allison** [comment]
> Hi David
> Desktop version has a lot of more tools and add-ons. 
> Regards.

Within the context of your feature request, how does Anki Desktop without addons differ from AnkiDroid

**Comment by stasimon1** [comment]
Sorry David I misunderstood you. 

"Auto Advance (Auto display answer)" on Anki Desktop with a filter deck works correc, but on Ankidroid "Automatic display answer" does not work.

https://github.com/ankidroid/Anki-Android/assets/148726259/147b64b8-a1af-45f2-a852-ca2e9a3e7456


https://github.com/ankidroid/Anki-Android/assets/148726259/2f6299ce-52b2-42cb-9956-72e6abc61585

**Comment by david-allison** [comment]
I believe this has been fixed with the 'automatic answer' changes.
