### ISSUE TITLE
[BUG]: Toast after completing a deck hides last deck in deck list.

### ISSUE THREAD

**Issue by kekoa** [ankidroid/Anki-Android#15989]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Scroll to bottom of a deck list at least as tall as the screen.  Finish studying a deck.  After returning to main screen, observe that there's a toast hiding the last deck in the deck list.

### Expected behaviour

Toast does not hide a deck.

### Actual behaviour

![congrats-toast](https://github.com/ankidroid/Anki-Android/assets/1727380/39c15284-03f0-450c-99c4-20ace13d7e56)

The last deck is hidden under the "Congratulations! You have finished for now." toast.  It's easy to miss that deck and forget to study it.

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 5a

Hardware = barbet

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 5a Build/AP1A.240305.019.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = 4ff114d2-0a21-4737-92f5-b0b7a81d77de

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
You can swipe the snackbar away to remove it

**Comment by BrayanDSO** [comment]
Also, the snackbar disappears automatically
