### ISSUE TITLE
Improve ETA calculation

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#15980]
I have decks for writing Kanji and it takes quite some time to do those cards. The way ETA is calculated currently doesn't seem to use the average time spent on a card. In my case I saw today I had 36 cards left and ETA was 6 mins. I am sure I would take at least 10-15 mins for all those cards everytime. If ETA was done using the average time spent per cards which were calculated differently for each decks this would improve greatly. I set up relatively low retention rates which equals higher amount of lapsed cards and that can also explain how ETA is so off in these decks. I would appreciate if this was done someday.

**Comment by BrayanDSO** [comment]
The setting was removed of Anki Desktop because of the lack of accuracy, and it's probably impossible to be accurate enough. Also it will likely be replaced with a JS addon in the future here in AnkiDroid, so it shouldn't have any enhacements in the app. I'm sorry for that.
