### ISSUE TITLE
enhancement: Inform `Restore from AnkiWeb (recommended)` solution in the help dialog for permission-removed users

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#15999]
`Restore from AnkiWeb` item was ruled out from the option list in the help dialog for permission-removed users, due to the following reason: 
https://github.com/ankidroid/Anki-Android/blob/03d18807aee9c8a3530c9549071b480735a3ba68/AnkiDroid/src/main/java/com/ichi2/anki/ui/windows/permissions/AndroidPermanentlyRevokedPermissionsDialog.kt#L75-L79

<img src="https://github.com/david-allison/Anki-Android/assets/10436072/f630c4c2-b585-4184-b0cc-2df5e5e2a128" width="320px">

However, even if it is impossible to do the solution directly from the dialog, it still seems to be helpful to inform (in this dialog in the app) users that there is a recommended solution using AnkiWeb. 

(Though the link in `Restore folder access` item notes that, the untranslated note may be not very impressive for upset readers.)
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/09cade14-13c3-4c92-92a7-ee94bb8a2533" width="500px">

Also, a subsequent dialog box for brief guidance including the information above (in the app, with translation) would be of help.

######  Anything else you want to share?
I read some v2.17.6 users' comments expressing their anxiety and complaint about installing file from external source. 

At first, I wondered why they talk as if restoring from AnkiWeb is not an solution, but seemingly, the dialog above makes it look as if the way is not an solution. 

From the viewpoint of some users, it seems to be fairly difficult, both emotionally and technically, to install an unknown file from unknown site, reading untranslated guide.

I regret their mistrust, but their security policy, "avoid as much as possible what I don't know well", is not necessarily wrong.

**Comment by BrayanDSO** [comment]
Creating a new collection then syncing solves that. It just needs a single line stating that in the same dialog, or better docs.

**Comment by snowtimeglass** [comment]
I've changed the title.
