### ISSUE TITLE
[BUG]: After reposition a card, "Undo Reschedule" is shown instead of "Undo Reposition"

### ISSUE THREAD

**Issue by XYIheng** [ankidroid/Anki-Android#15995]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. enter card browser
2. long click a card
3. click option
4. click reposition to reposit the card
5. click more option 
6. see error

https://github.com/ankidroid/Anki-Android/assets/31406320/1ee93896-6eff-46e1-a0e2-c98beb554ceb

### Expected behaviour

"Undo Reposition" button should display

### Actual behaviour

"Undo Reschedule" button display

### Debug info

```text
APP Version: 2.18alpha6
Android Version: Android10.0
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by brishtibheja** [comment]
The template should have included the word desktop because many people refer to AnkiWeb/AnkiDroid/Anki Mobile as also Anki. Quite possible someone would mistake "latest of version of Anki" as latest ankidroid ver.

**Comment by BrayanDSO** [comment]
If you mistook it with AnkiDroid, marking that it doesn't occur in AnkiDroid doesn't make sense.

But maybe the message could be shorter and harder to get wrong

**Comment by XYIheng** [comment]
@BrayanDSO I tested the desktop version of Anki and did not find "undo" action with reposition or reschedule.
I also browse the history bug in Ankidroid and find a related one: https://github.com/ankidroid/Anki-Android/issues/7674
It seems that "Undo Reposition" should display after click reposition

**Comment by BrayanDSO** [comment]
There is a feedback popup after undoing things in the desktop version. I suspect that it will have a message mentioning `Reschedule` instead of `Reposition` as well

**Comment by user1823** [comment]
Brayan is correct. Anki Desktop also says `Undo Reschedule`, not `Undo Reposition`.

**Comment by BrayanDSO** [comment]
Closing as upstream issue. Please report it there so it can get fixed
