### ISSUE TITLE
[Bug]: Cursor moves out of the input box in Deck options when swiping left and right

### ISSUE THREAD

**Issue by ChuckieChen945** [ankidroid/Anki-Android#15992]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Enable a keyboard on the phone that supports left and right swipe to move the cursor, and enable the function to move the cursor by swiping left and right
2. Open Deck options
3. Position the cursor in a text input box
4. Use the aforementioned keyboard to move the cursor left and right

### Expected behaviour

The cursor moves left and right, and is restricted within the text input box.

### Actual behaviour

The cursor jumps out of the text input box, and the input box loses focus. As shown in the following video:

https://github.com/ankidroid/Anki-Android/assets/29732324/6c2799db-fcbb-4b93-824e-e49704fe43b7

### Debug info

```text
AnkiDroid Version = 2.18alpha6 (d80b76744dcceab3d82fb30e028e76229c7fe03f)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 10 (SDK 29)

ProductFlavor = full

Manufacturer = HUAWEI

Model = MXW-AN00

Hardware = mt6873

Webview User Agent = null

ACRA UUID = ac8cd859-a1ab-4b8c-bf6d-33391493b3f2

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

The priority of this bug is relatively low.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Closing as upstream issue. Please report it there so it can get fixed
