### ISSUE TITLE
After completing a deck, show "Next learning card will be ready in ⁨⁨..."

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16000]
After completing a deck, AnkiDroid currently shows a snackbar saying "Congratulations! You have finished for now."

It would be great if AnkiDroid also shows "The next learning card will be ready in ..." after completing the deck (without needing to click the deck again).

However, I am not sure about the UI. Adding this string to the snackbar would probably not look good (because it is 2-3 lines long). Suggestions are welcome.

**Comment by david-allison** [comment]
We'll want to do this on the congrats screen

**Comment by user1823** [comment]
If this is done in the congrats screen, I am concerned that people will complain about something like this:

> However, the new Congratulations screen keeps bugging me, because there is no gesture to wave it away. If you have gestures turned on and are swiping left or right, it breaks your rhythm to have to look for a tiny arrow at the edge of the screen each time you finish a deck.

_Originally posted in https://github.com/ankidroid/Anki-Android/issues/15349#issue-2103571376_
