### ISSUE TITLE
[BUG]: custom study -> modify today's new card limit does not work consistently

### ISSUE THREAD

**Issue by Niemaa** [ankidroid/Anki-Android#16017]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- finishing learning a staple
- click on custom study and modify today's new card limit 
- enter "1"

### Expected behaviour

"1" appears as new learning card

### Actual behaviour

nothing happens.
I tried adding 2 cards following the same steps to the same staple, that worked, a "2" appeared as the number of new cards to learn. If I then try to add 1 card again to the staple it works.

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A515F

Hardware = exynos9611

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-A515F Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = 2f52687a-bc80-449a-ba8b-eaba7ab9b09b

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

The staple does contain new learning cards, but the daily limit for new cards is set to 0. 
Thank you so much for your support :)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Niemaa** [comment]
@snowtimeglass 
Thanks you for reply!
No, I can't reproduce it, the bug fortunately never occured again after that day. I have no Idea what went wrong, but now it works consistently :)

**Comment by snowtimeglass** [comment]
Good to hear that. 

(I'm not sure, but the limit had possibly been set to "achieved number of the cards minus 1" in advance by your several adjustments of the number. In this condition, I can reproduce it by the steps above. Anyway, it is nice that it doesn't occur to you anymore.)
