### ISSUE TITLE
Make Changes in ETA String 

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16011]
For some languages, unlike in the English, time of ETA appears at the end, for example in Japanese time is preceded by 残り約 which means 'left approximately'

![Screenshot_2024-03-28-15-43-16-18_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/d83387a7-4194-403d-abc4-3ef65944def3)

If you thus have around four buttons up there it hides the time. That doesn't happen with all languages.
I was thinking of changing the code so as to wrap the text but a simpler solution is to just remove the word 'left' from the English.

I recognise this is a bit unaesthetic and may confuse the new users a bit but will be able to prevent this situation for other languages.

**Comment by brishtibheja** [comment]
For Japanese though an alternative translation is possible we will just have to put the verb at the end. 〇〇時間が残っています。

**Comment by BrayanDSO** [comment]
ETA is going to be replaced by a JS addon in the future, so enhancements shouldn't be done.

And for this case, even wrapping won't fix it. Try using gestures to replace some of these buttons.

**Comment by brishtibheja** [comment]
You told me this before but I thought the same problem would persist there.
