### ISSUE TITLE
Need preview for IO cards while creating them.

### ISSUE THREAD

**Issue by Devaprasad-reddy** [ankidroid/Anki-Android#16025]
**Is your feature request related to a problem? Please describe.**
Could not preview cards after making masks 

**Describe the solution you'd like**
A preview button just before adding the card

**Describe alternatives you've considered**
Go to the card browser and preview created cards

**Additional context**
Also the confirmation dialogue before adding the card is much needed as I lost my work 2-3 times after making all the masks and accidentally pressing back button

**Comment by krmanik** [comment]
The (ported) upstream note editor will be used which solve this issue.

**Comment by BrayanDSO** [comment]
This needs to be done in Anki's repository, since we get that screen from there, so please post the request in Anki forums
