### ISSUE TITLE
Match the color of status bar with Statistic toolbar

### ISSUE THREAD

**Issue by neeldoshii** [ankidroid/Anki-Android#16034]
* Refer Comment https://github.com/ankidroid/Anki-Android/pull/16027#discussion_r1545590869 by Brayan. 

> Adding the fitsSystemWindows=true into the CoordinatorLayout fixes the problem but the workaround is to fix the scroll  issue.

**Comment by Aditya13s** [comment]
Please assign me. I am working on it.

**Comment by neeldoshii** [comment]
feel free to take it, you will get assigned ;)

**Comment by Aditya13s** [comment]
@david-allison i am working on it. Please assign it to me.

**Comment by neeldoshii** [comment]
No need to ping. If you have commented that means you are free to take it.

**Comment by Aditya13s** [comment]
https://github.com/ankidroid/Anki-Android/assets/77337791/26370561-8f5e-4fe6-b643-b3e0b8e98662

Is this the result we want @neeldoshii

**Comment by Aditya13s** [comment]
@neeldoshii you can check the PR
