### ISSUE TITLE
[BUG]: Add Audio Clip - Filename gets shortened and no file ending

### ISSUE THREAD

**Issue by FubayashiKazue** [ankidroid/Anki-Android#16045]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Hi!

I ran into the following bug today while trying to add a local sound file to a card:

- in the card browser, open a card
- click on the left icon of a field, choose "add audio clip"
- in the next screen, choose the grey "audio" "area" (sorry, don't know the right words)
- choose the audio file "Fairy_Tail_086_0.12.03.539-0.12.06.125.mp3"
- ankidroid adds it, but shortens the file name and drops the file ending, in my case the field now has [sound:Fairy_Tale_086_0.12]

### Expected behaviour

Anki should add the audio file using the full name including the ending

### Actual behaviour

Anki ahortens the filename

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = Fairphone

Model = FP3

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; FP3 Build/6.A.025.0; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = d3745061-9919-4114-b2b6-b2885b3ed8c1

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by FubayashiKazue** [comment]
Just tested it with other files and Ankidroid always cuts off the file name at the second dot when I try to add it through "add audio clip":
-> SwordArtOnlineS01E_07_0.07.49.385-0.07.50.887.mp3 turns into SwordArtOnlineS01E_07_0.07 
-> a.b.c.mp3 turns into a.b

**Comment by lukstbit** [comment]
Thanks for the bug report. I've created a fix and it will be available in the next alpha.
