### ISSUE TITLE
[BUG]: Deleting Custom Study Session Deck crashes app

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16042]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Custom Study
2. Preview new cards
3. Now delete the custom study session's deck

### Expected behaviour

Nothing happens 

### Actual behaviour

App crashes

### Debug info

```text
AnkiDroid Version = 2.18alpha7 (1c5a6b3c220d67a75dd4b4d78e1fc8a6cc4b4789)

Backend Version = provider(?) (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = null

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lukstbit** [comment]
Thanks for the bug report. I've created a fix which should be available in the next alpha.

**Comment by brishtibheja** [comment]
@lukstbit I just realized I forgot to add that this also happened with "review ahead".

**Comment by lukstbit** [comment]
I've just tested with my fix and _Review ahead_ doesn't crash.
If you see this with the new alpha(containing the fix) please open a new bug report so I can take a look.
