### ISSUE TITLE
[BUG]: Can't play web sound by `[sound:` `]`tags

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16041]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Paste the following text in a field of a card, or open the following attached sample card:
```
<audio src="http://dict.youdao.com/dictvoice?audio=forest&amp;type=2" controls="controls"></audio>

[sound:http://dict.youdao.com/dictvoice?audio=forest&amp;type=2]
```

   <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/a54e7022-0b44-405d-b8e6-cab6be3f20ee" width="200px">

Note:
- both web addresses are identical.
- The first part is just for comparison. This issue occurs even without it.

Sample:
 - [test web sound.zip](https://github.com/ankidroid/Anki-Android/files/14818045/test.web.sound.zip)

---
2. Tap the first play button in the card, and then tap the second
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/14a4f16f-b72d-4bc4-873a-c261eedf8624" width="200px">

### Expected behaviour

Both of the sounds are played, as in version 2.16.5, and as in Anki Desktop (version ⁨24.04).

### Actual behaviour

- Tapping the first plays button play its sound.
- Tapping the second play button shows the following error message. The button's sound is not played.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/b87b49d6-54db-40f9-bf3f-a67129be01ec" width="320px">

 

### Debug info

```text
AnkiDroid Version = 2.18alpha7 (1c5a6b3c220d67a75dd4b4d78e1fc8a6cc4b4789)

Backend Version = provider(?) (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = null

ACRA UUID = beb70800-6cd9-4528-80fc-c89c7e878144

FSRS Enabled = false

Crash Reports Enabled = true

```

Anki Desktop
```
Anki 24.04 (429bc9e1)  (ao)
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
Platform: Windows-10-10.0.19045
```

### (Optional) Anything else you want to share?

This issue occurs in 2.17.6, too.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
This works in Anki Desktop? Could you provide an apkg, as the `[sound:` isn't working on

Anki Desktop ⁨23.12.1 (1a1d4d54)⁩

@BrayanDSO FYI

**Comment by snowtimeglass** [comment]
> This works in Anki Desktop?

The second button works in Anki Desktop 24.04 (429bc9e1), as noted above. You mean you want to know about 23.12.1, not 24.04?

> Could you provide an apkg

I think the attached zip file above is it. It doesn't work?

**Comment by david-allison** [comment]
> The second button works in Anki Desktop 24.04 (429bc9e1), as noted above.
> I think it is in the attached zip file above.

Sorry! missed that. The second button doesn't work in Anki Desktop [23.12.1 (1a1d4d54)⁩] on my mac
