### ISSUE TITLE
Show Names on Long Press in IO Toolbar

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16043]
I get confused with the different tools in Image Occlusion. It would be nice if on long press the names of different tools appear. This already happens elsewhere.

**Comment by BrayanDSO** [comment]
That screen comes from https://github.com/ankitects/anki, so please report it there.

Tested in AnkiMobile 24.04 and also doesn't works there.

**Comment by krmanik** [comment]
I have logged the issue here, will be fixed in next update. https://github.com/ankitects/anki/issues/2774

**Comment by BrayanDSO** [comment]
Closing as upstream issue
