### ISSUE TITLE
I don't like the naming: `ankiBackend` vs `ankidroidBackend`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16067]
I don't like the naming: `ankiBackend` vs `ankidroidBackend`

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/16066#discussion_r1547085816_

**Comment by lukstbit** [comment]
The dependency and version declarations should use the same name, I'm fine with any of the names.

**Comment by mikehardy** [comment]
agreed with lukstbit, I'm just a sous chef in this part of the kitchen, David - name it exactly as you like and it works for me

**Comment by david-allison** [comment]
I was waiting for someone with a strong opinion. `ankiBackend` it is!

**Comment by Aditya13s** [comment]
I think ankiBackend is good. It's short and simple, also the backend is not just for android and ankidroidBackend looks like it's only for android so it's good to use ankiBackend.

> I was waiting for someone with a strong opinion. `ankiBackend` it is!

**Comment by ndkshr** [comment]
Hello everyone, I have created a PR for this issue. This is my first contribution here, so please let me know if these changes look good. Thank you!
