### ISSUE TITLE
[BUG]: `Upgraded version to %s` snackbar is misaligned

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#16061]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Upgrade to an alpha version newer than the installed one
2. Open the app

### Expected behaviour

The `Upgraded version to ...` snackbar should be shown above the FAB

### Actual behaviour

It is shown in front of the FAB

### Debug info

```text
2.18alpha7 (e434419c31f9d27a85bce64fd362a40b1cb44181)

Emulator with API 34
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Some context for whoever want to fix this:

By defaullt, `showSnackbar` checks if it's caller is a `BaseSnackbarBuilderProvider` so it can use a default Builder for that fragment/activity.

The one of DeckPicker is this one:

https://github.com/ankidroid/Anki-Android/blob/0ef9363cc92a29edbd4b0763873626cf92bc3928/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.kt#L227-L230

As you can see, the snackbar anchorView should be set, but in this case that doesn't happen (probably because findViewById is returning null). The task is to fix that.

**Comment by 410063005** [comment]
It's a little weired.  This bug reproduced on my Emulator with API 31. 

1. I'm sure findViewById always returns non-null.
2. If I open DeckPicker directly,  this snackbar shows in front of the FAB
3. If I go back to DeckPicker from Settings (Preferences.kt), the snackbar shows above the FAB

**Comment by devsarahgeo** [comment]
Can you assign this to me?

**Comment by david-allison** [comment]
Thanks!! Do ask on Discord if you need anything

**Comment by 410063005** [comment]
I did some changes in this PR in my own repo  https://github.com/410063005/Anki-Android/pull/1

Maybe these chages seem nonsense but the snackbar is aligned now.  I don't know if calling `showSnackbar` from `onCreate` is a BAD practice.

**Comment by devsarahgeo** [comment]
@david-allison I did not realize I was assigned as github sent no notification, just saw this today. But I think [410063005] has fixed this one.
