### ISSUE TITLE
Update backend to anki24.04

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16064]
Making this issue to link PRs

* [x] Fix backend publishing
  * https://github.com/ankidroid/Anki-Android-Backend/issues/347
  * https://github.com/ankidroid/Anki-Android-Backend/pull/361
  * https://github.com/ankidroid/Anki-Android-Backend/commit/70674f6a2a455886af2ec04f327387e5ad3088b0
* [x] Update from `io.github.david-allison-1` to `io.github.david-allison`
  * #16066  
* [x] Update from `anki23.12.1` to `anki24.04`
  * https://github.com/ankidroid/Anki-Android-Backend/pull/358
  * small preening PR in backend before backend publish: https://github.com/ankidroid/Anki-Android-Backend/pull/365
  * #16071
* [x] 24.04 changes to commit after backend update:
  * [x] https://github.com/ankidroid/Anki-Android/issues/15838
    * [x] https://github.com/ankidroid/Anki-Android/pull/16055

**Comment by mikehardy** [comment]
item 2 is brewing in #16065 and #16066 we think alike :-) - it already works locally
item 3 is apparently (I believe Brayan checked it?) just a commit hash bump and It Just Works(tm)

maybe it's easy !

**Comment by david-allison** [comment]
Ahaaa! Great minds think alike

* https://github.com/ankidroid/Anki-Android/pull/16065 
* https://github.com/ankidroid/Anki-Android/pull/16066

<center>
![](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExcDlncXNvZ3lud2VzdzVvOXJjcGJicjBsb255YWp6ZTVxb2x2OHBldiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/cRjmeUyMQ30MNGKXAr/giphy.gif)
</center>

**Comment by mikehardy** [comment]
description above updated, all the work appears to be done + queued now, just pending second eyes and working through various processes 🚂

**Comment by mikehardy** [comment]
Launching now. Awesome work back to front

**Comment by david-allison** [comment]
Great job, all!
