### ISSUE TITLE
Moving the other options from floating add button to topbar beside the sync option. and keeping the floating add button only to create Cards.

### ISSUE THREAD

**Issue by jainishrpandya** [ankidroid/Anki-Android#16082]
**Is your feature request related to a problem? Please describe.**
I have been using Ankidroid for quite a long time. and one thing that always got my attention is when I press the floating add button it shows me 4 options.
* get shared decks
* Create a filtered deck
* Create deck
* Add card

in which 90% of the time I press the add card button. and very rarely I use the other three options. and I think the majority of users have the same case.

**Describe the solution you'd like**
My solution is to keep the floating add button only to create a card. and the other three options can be moved to the top bar with a spinner menu for easy access.

Friction Count
To create card it will reduce the click friction from two taps to one tap.
and to for the other three options, it will remain two clicks.

**Additional context**
![image](https://github.com/ankidroid/Anki-Android/assets/69842037/1497ef5b-4e95-4e5a-acba-694b46155a44)

**Comment by jainishrpandya** [comment]
as a part of the community. if you approve I will solve the problem and create the PR.

**Comment by BrayanDSO** [comment]
A quick double tap opens it and the friction is practically null.

Also this avoids mistaps

And your use case isn't universal

Additionally, the toolbar has already too much stuff.

So, I'm sorry, but won't be implemented.
