### ISSUE TITLE
[BUG]: Ankidroid automatically opens CSV files on MIUI 12

### ISSUE THREAD

**Issue by William-N-Havard** [ankidroid/Anki-Android#16089]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Use an app that generates a CSV (in my case Revolut). Instead of being opened in a standard CSV reader, it opens in AnkiDroid (despite having set sharing option to another app previously)

### Expected behaviour

Do not automatically open CSVs.

### Actual behaviour

I have another app that generates CSV files and for some reason, AnkiDroid automatically opens those files instead of the standard CSV reader. I've tried everything to prevent this behaviour (disabled open supported links, etc.). But I can't get it to work properly.

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 10 (SDK 29)

ProductFlavor = play

Manufacturer = Xiaomi

Model = Redmi Note 7

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi Note 7 Build/QKQ1.190910.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/122.0.6261.119 Mobile Safari/537.36

ACRA UUID = 008862ab-8e10-444e-ac32-379bc000fa7a

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
You should be able to set the default app for opening a specific extension somehow (that varies between brands and Android versions).

AFAIK, no app can set themselves as the default app for something.

If what you actually want to request is for AnkiDroid to not be able to open a CSV file directly, please say so.

**Comment by William-N-Havard** [comment]
Well AnkiDroid set itself as the default CSV opener. As you, I though this would not be possible without any user interaction, but it is. 

I uninstalled AnkiDroid and was able to open my CSV file properly. And as soon as I reinstalled AnkiDroid, it became the default CSV app again.

I tried everything to prevent AnkiDroid to open CSVs by default, but nothing works.

**Comment by david-allison** [comment]
It sounds like your app hasn't registered itself for opening CSVs, AnkiDroid is the only app available, so it's chosen.

**What you can ask**
1. Request that the app you're using supports CSVs


**What you can do**
1. Make an app which accepts CSV, redirect to your desired app and set it as default
1. Fork AnkiDroid and apply the following patch

Index: AnkiDroid/src/main/AndroidManifest.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/AndroidManifest.xml b/AnkiDroid/src/main/AndroidManifest.xml
--- a/AnkiDroid/src/main/AndroidManifest.xml	(revision 0ea6a709eff04b2cae33985a7720914daf03e9ec)
+++ b/AnkiDroid/src/main/AndroidManifest.xml	(date 1712187900765)
@@ -200,31 +200,31 @@
                     android:pathPattern=".*\\.tsv"
                     android:scheme="file"
                     />
-                
-                <data
-                    android:host="*"
-                    android:mimeType="*/*"
-                    android:pathPattern=".*\\.csv"
-                    android:scheme="http"
-                    />
-                <data
-                    android:host="*"
-                    android:mimeType="*/*"
-                    android:pathPattern=".*\\.csv"
-                    android:scheme="https"
-                    />
-                <data
-                    android:host="*"
-                    android:mimeType="*/*"
-                    android:pathPattern=".*\\.csv"
-                    android:scheme="content"
-                    />
-                <data
-                    android:host="*"
-                    android:mimeType="*/*"
-                    android:pathPattern=".*\\.csv"
-                    android:scheme="file"
-                    />
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
             </intent-filter>
             
             <intent-filter>
@@ -238,7 +238,7 @@
                 <data android:mimeType="application/x-colpkg"/>
                 <data android:mimeType="application/octet-stream"/>
                 <data android:mimeType="text/tab-separated-values"/>
-                <data android:mimeType="text/comma-separated-values"/>
+
             </intent-filter>
