### ISSUE TITLE
Add a github bot that add a tag for candidates for GSoC or other event with deadline

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#16096]
During GSoC selection, and potentially some other events such as hacktober, some PRs must be reviewed quickly as there are external deadlines.
It would be helpful that mentors/reviewer can prioritize their PRs, hence can find them easily. The canonical way to do so would be to use a tag.
Most users can't add tag themselves. So we need a simple way that new contributors can add tag.

There may be many methods to do so. I don't know github bots, so I don't know what would be the most easy thing to do. Any person that is proficient with the bot can choose the methods they prefer. Here I give a few idea, maybe not the best.
* Add an extra tag that the user can fill in the PR template that indicates whether something is GSoC related
* search for "summer of code" or "gsoc" in the PR and, if present, add the tag
* create a discord bot that takes the link and add the tag to it on github

**Comment by david-allison** [comment]
It's very little time to triage issues as they're coming in

May not be worth the time: 
![image](https://github.com/ankidroid/Anki-Android/assets/62114487/be2f5c1f-1fce-49e1-9ea7-f0f8f7edbf5b)

**Comment by BrayanDSO** [comment]
For GSoC selecteds, just filter by the author name.

For GSoC candidates, I don't think that the tag matters enough in the end.

For hacktober, IMO this is just more work.

**Comment by david-allison** [comment]
@BrayanDSO Is that a proposal to remove the GSoC label altogether, or does it provide value?

**Comment by BrayanDSO** [comment]
If it is just an automated tag based in the PR text, like the issue proposes, the label doesn't matter, since you can filter it out in Github's search query without a sofisticated bot
