### ISSUE TITLE
[BUG]: There's no direct button to remove the background image for deck screen

### ISSUE THREAD

**Issue by oyeraghib** [ankidroid/Anki-Android#16090]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Go to Settings -> Appearance -> Select Image
2. Now select an image for the deck screen background.
3.Now to remove the background image you have to choose the "Select image" option again and close the selector in order to get the option to remove the background image.

### Expected behaviour

Ideally there should be a button to remove the background image without actually selecting the "Select image" option

<img width="424" alt="Screenshot 2024-04-04 at 6 44 19 AM" src="https://github.com/ankidroid/Anki-Android/assets/40427461/01b0a56b-1c14-46e9-843a-0d4b8d44fd28">

### Actual behaviour

User have to tap on "Select Image" to remove the image (which sounds a bit off)

<img width="276" alt="Screenshot 2024-04-04 at 6 45 34 AM" src="https://github.com/ankidroid/Anki-Android/assets/40427461/f90cf3ae-4b60-4723-b8f6-95bf40f95906">

<img width="277" alt="Screenshot 2024-04-04 at 6 47 11 AM" src="https://github.com/ankidroid/Anki-Android/assets/40427461/cb11dc39-0360-418e-8974-2a2f6796d451">

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 13; Pixel 6a Build/TQ2A.230405.003.E1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.40 Mobile Safari/537.36

ACRA UUID = 2563bf4e-52ff-49bb-883c-7538962634e9

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by snowtimeglass** [comment]
>User have to tap on "Select Image" to remove the image (which sounds a bit off)

I agree. The steps seem to be unnatural.

**Comment by jainishrpandya** [comment]
I'll look into it. and get back to you.

**Comment by jainishrpandya** [comment]
Yes! It feels strange.we can add button button just below the select image to remove background.

**Comment by jainishrpandya** [comment]
Please assign me this issue.

**Comment by oyeraghib** [comment]
Hi @jainishrpandya I am currently working on this myself.

**Comment by jainishrpandya** [comment]
@oyeraghib ohh! That's great. Ping me here if you need any help.

**Comment by oyeraghib** [comment]
Sure. Thanks

**Comment by snowtimeglass** [comment]
While I agree that the current steps are unnatural, I don't necessarily agree with the suggested solution (#16091). The remove button being there also looks somewhat unnatural, in my opinion. 

Moreover, the option title itself seems also unnatural, and dissimilar to the other option titles. 

I mean, "Select image" is just an step in the middle of the change of this setting. It is not a final result of a change (e.g., "Show top bar", "Show deck title") nor an object of a change (e.g., "Night theme", "App bar buttons"). So, it actually looks odd as an option title.

How about using "Apply image" (or "Show image") and toggle button.

**Comment by jainishrpandya** [comment]
Yes! Toggle button with title like "Apply Image background" and when toggle is on it expands the select image option. Otherwise it will be hidden.

**Comment by oyeraghib** [comment]
Interesting point. So what you are suggesting is:

1. The text should be "Apply image as background" with a toggle button.
2. Initially the toggle button is off
3. If user tries to turn on the toggle and select the image for background, the toggle button turns "ON" setting bg image for deck picker.
4. Now clicking the option to choose image (or trying to turn "OFF" the toggle ) would remove the image.

It is fine but the issue here would be if user wants to replace the image, they would have to first "OFF" the current toggle and then select a new image (turning it back ON), which could again become a bit unnatural from user's perspective.

But I would still keep the suggestion in mind and would wait for any reviewers to comment on the PR and know what do they think.

**Comment by snowtimeglass** [comment]
Thank you for the consideration.

These parts below seem to be somewhat different from what I have imagined. 

> 4. Now clicking the option to choose image (or trying to turn "OFF" the toggle ) would remove the image.

>if user wants to replace the image, they would have to first "OFF" the current toggle and then select a new image (turning it back ON), which could again become a bit unnatural from user's perspective.

My thoughts are as follows:

4'. Now tapping the option title (tentatively named `Apply image as background`) would open the image picker screen again.

5 . Instead, tapping the toggle button would remove the image (after a confirmation dialog for the removal), and turn it "OFF".

I mean, when the toggle button is already turned "ON", the reactions of (A) tapping the title and (B) tapping the toggle button would be different from each other, as in the case of "Custom sync server" option (Settings > Sync > Custom sync server):

https://github.com/ankidroid/Anki-Android/assets/10436072/d715ecb0-f0b1-4a22-9a1c-15c7054b024f

**Comment by brishtibheja** [comment]
@david-allison Do we want this closed?

**Comment by david-allison** [comment]
We've spent too much time on a minor feature and the UX still isn't good. 

Let's focus on things which have more impact
