### ISSUE TITLE
[BUG]: Limits for New Cards/Day cannot be changed simultaneously

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16098]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Open Deck Options
2. Change the New Cards/Day in "Preset"
3. Change to "Deck"
4. Save the settings

### Expected behaviour

New Cards/Day is changed for the deck

### Actual behaviour

It isn't

### Debug info

```text
AnkiDroid Version = 2.18alpha8 (6fc26947fd31743bc83e68f17ae7fec64bfa8e62)

Backend Version = provider(?) (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = null

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Also tried changing Deck limit first and then the limit for Preset. Doesn't work. 

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
We get the screen from the desktop version, so please report that in the [forums](https://forums.ankiweb.net/)
