### ISSUE TITLE
"UNDO" and "BACK" (undo the last note's review) should be separate… they're different concepts

### ISSUE THREAD

**Issue by boolbag** [ankidroid/Anki-Android#16119]
Not sure if this is a feature request or a bug as I only started noticing this problem. Did something change?

**Is your feature request related to a problem? Please describe.**
I often use the Back button to undo a review and change an answer. Sometimes I might go back three notes because I decide that I should have selected "Forgot".

The problem is that if I've edited any notes between the current one and the one where I need to change the answer, all the edits are lost! Any pictures added, any text... Just by going back a few cards to change an answer, all of that is completely lost.

Maybe I'm wrong, but I don't recall this ever happening before three months ago.
It's like a whole lot of UNDO features have been rolled into the BACK buton.

**Describe the solution you'd like**
A BACK button that doesn't UNDO.
Or an option so that pressing UNDO only goes BACK without altering cards.

**Describe alternatives you've considered**
Not using the BACK button. Not a happy option.

**Additional context**

**Comment by BrayanDSO** [comment]
> Maybe I'm wrong, but I don't recall this ever happening before three months ago.

It did.

> A BACK button that doesn't UNDO.

I don't understand the request. Do you mean the `Undo` toolbar button or the device's navigation back button (which implies that you mapped undo into it)? There isn't a "BACK" button in AnkiDroid

Either way, "undo" does what the name says, it undoes the last thing you did. Undoing a review or two is natural. Three? Something is wrong.

Also, it's not technically possible to add a "only undo reviews" option.

**Comment by boolbag** [comment]
1. I'm talking about the Undo toolbar button
2. I've always thought of it as a BACK button, to the user the icon could mean BACK just as well as UNDO
3. What is natural or not is subjective and personal. 
4. Anyway, just by going back two cards, the edits on the previous card are erased.
