### ISSUE TITLE
[BUG] JS API: `ankiGetCardMod` if card was not modified

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16113]
> If a card was never modified, this does NOT give the time when it was added, but some other unknown value, which does not seem to be in relation to to the added time. Maybe it is like the return value of the "cardDue" API method which returns "note id or random int" for new cards.

https://github.com/ankidroid/Anki-Android/wiki/_compare/d649c395e22654a5143927de969e5370e159796c...6b8b2b263effe41684b68be994ea0a835304384a

**Comment by david-allison** [comment]
@krmanik FYI

**Comment by krmanik** [comment]
I will look into this.
