### ISSUE TITLE
[BUG]: Browsing cards not possible

### ISSUE THREAD

**Issue by alproo** [ankidroid/Anki-Android#16126]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Try to browse the card within the collection

### Expected behaviour

Show list of available cards

### Actual behaviour

Error message is displayed

https://github.com/ankidroid/Anki-Android/assets/69971052/62e7cb9a-8bab-4501-91a8-f1741f42137d

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G998B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-G998B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.40 Mobile Safari/537.36

ACRA UUID = b22a72bf-404e-40e1-85dd-fa10c54accf4

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
From the video: ![Screenshot 2024-04-08 at 03 27 36](https://github.com/ankidroid/Anki-Android/assets/62114487/ce98c87b-f81d-49e6-bcb4-90d7c7741c03)
