### ISSUE TITLE
Use sentence casing in some settings

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16120]
If you go to Settings>>Controls then a few inconsistencies appear in capitalisation. The ones that I could spot are:

1. F in Flag is capitalised when it should be not.
2. W in Toggle Whiteboard is capitalised but other instances of whiteboard in the same screen are not.
3. L is not capitalised in Abort learning when it is in Abort Learning and Sync.

**Comment by david-allison** [comment]
Good first issue, I won't take it on

For implementers: look to the PRs introducing 

https://github.com/ankidroid/Anki-Android/blob/97b299ef3737c36c044147d849ab0171e9371307/AnkiDroid/src/test/java/com/ichi2/anki/ui/internationalization/SentenceCaseTest.kt

**Comment by Aditya13s** [comment]
Please Assign me @david-allison

**Comment by BrayanDSO** [comment]
This is currently the 4th issue assigned to you @Aditya13s. Try to finish one of other ones that you are assigned to before asking to do more stuff.

**Comment by MartiPresa** [comment]
Hi!
Is this issue still availble? Thanks!

**Comment by david-allison** [comment]
It is, thanks!

**Comment by jainishrpandya** [comment]
hey is anyone working on it? or please assign me this issue.

**Comment by Akshaykomar890** [comment]
Hey Akshaykomar890 just a heads up - I submitted the pull request for the issue #16160, but forgot to assign it to myself. I'll take care of that now. Let me know if you have any feedback or need anything else."

**Comment by Akshaykomar890** [comment]
Hi @MartiPresa 

I hope you're doing well. I wanted to check in regarding the #16120 that you're assigned to. Could you please provide an update on the progress of this issue?

Your response will help us determine the next steps regarding the related PR.

Thanks,

**Comment by gayatriii0803** [comment]
Is there anyone working on it? if not I would like to work on it.

**Comment by david-allison** [comment]
Assigned, thanks

**Comment by brishtibheja** [comment]
Finally this closes 😅

**Comment by jainv4156** [comment]
Hey ,can i work on this issue if no one is working on it

**Comment by david-allison** [comment]
Sure

**Comment by jainv4156** [comment]
hey @david-allison i think i got the solution but i have a question . There is no function for desired string in Generated Translaion That i can use with "TA" can i directly use  String Resourse xml in place of translation

**Comment by jainv4156** [comment]
https://github.com/ankidroid/Anki-Android/blob/94de856406ea3627302c82c28a7c261a824fcae4/AnkiDroid/src/main/java/com/ichi2/anki/preferences/ControlsSettingsFragment.kt#L45-L49

**Comment by david-allison** [comment]
@jainv4156 sorry, I don't understand what you're asking. Can you post a patch here with your proposal

**Comment by jainv4156** [comment]
i have made the changes should i directly raise a pr

**Comment by david-allison** [comment]
Push the branch and link it for now. I don't understand what you proposed

**Comment by jainv4156** [comment]
ok ,sure
