### ISSUE TITLE
[BUG]: Keyboard shows weird behaviour for while after Repositioning cards

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16136]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Search is:new
2. Select All
3. Reposition cards

### Expected behaviour

after reposition keyboard is shown normally in card browser screen

### Actual behaviour

keyboard shows a "jumping" motion. It shows up then it hides repeatedly for a few times.

### Debug info

```text
AnkiDroid Version = 2.18alpha8 (6fc26947fd31743bc83e68f17ae7fec64bfa8e62)

Backend Version = provider(?) (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = null

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by SanjaySargam** [comment]
Not reproduced in my case

**Comment by brishtibheja** [comment]
accha the sort field was the trigger. I tried just now, you have to have sort field shown on first column. Tell me if you still can't reproduce it.

**Comment by brishtibheja** [comment]
Probably not stale

**Comment by SanjaySargam** [comment]
> trigger

@brishtibheja Still not reproduce. Please attach a video

**Comment by brishtibheja** [comment]
https://github.com/user-attachments/assets/ff438743-40db-426e-b2b3-757aa378c430

**Comment by SanjaySargam** [comment]
Here is what I found. There is nothing in showing processing dialog
![image](https://github.com/user-attachments/assets/8b376bad-46d8-4b1d-8fb0-bf351b1aa92d)

**Comment by brishtibheja** [comment]
FYI the screen freezing for a moment happens a lot in this.

**Comment by BrayanDSO** [comment]
Most likely related to your device. Nothing we can do here
