### ISSUE TITLE
Make Text Editable in Note Editor

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16137]
Currently If you try to change the note type of a note it doesn't allow you to edit that note in the same screen. The text is greyed out. This may have been done without considering that it would mean changing a note to a cloze type would require you to edit it twice. I have to edit it first to change the note type and then edit again to add the cloze.

I suggest making the text editable and not grayed out.

**Comment by david-allison** [comment]
I agree, BUT:

The only way that I could see this happening is pulling out the 'Change Note Type' screen from the Note Editor and turning it into a dialog

We want to replace the Note Editor, and additional forward-moving effort on this would be waste.

**Comment by david-allison** [comment]
![Screenshot 2024-04-27 at 13 34 39](https://github.com/ankidroid/Anki-Android/assets/62114487/61a8048c-9ccb-4c1c-a26a-1d4c89aa3424)

**Comment by BrayanDSO** [comment]
We eventually will use the desktop note editor, so its not worth spending time on this
