### ISSUE TITLE
[Enhancement] Add "Check" actions to error messages

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16138]
The following errors could do with a 'check media' or 'check database' button to improve the UX:

* [ ] `errors-please-check-database`: Please use the Check Database action, then try again.
* [ ] `errors-please-check-media`: Please use the Check Media action, then try again.
* [ ] `errors-inconsistent-db-state`: Your database appears to be in an inconsistent state. Please use the Check Database action.

https://github.com/ankitects/anki-core-i18n/blob/main/core/templates/errors.ftl

Prompted by:

<details>

<summary>image</summary>

![image](https://github.com/ankidroid/Anki-Android/assets/62114487/8d94a5b8-c61e-4888-bd5e-dbd769f3119f)

</details>

https://www.reddit.com/r/Anki/comments/1byyaa2/comment/kymhygg/?context=3

**Comment by Aditya13s** [comment]
Is this completed? I can see the checks are present in the given link.
@david-allison

**Comment by prathvihan1008** [comment]
@david-allison  what  exactly should be done in this issue. Did u mean: to show up "check database" and "check media" buttons on encountering the above errors so that the user can navigate easily.

**Comment by david-allison** [comment]
Yes

**Comment by Aditya13s** [comment]
@david-allison I started working on it.

**Comment by david-allison** [comment]
To move this forward, the first stage is to list the exceptions with the exception type & stack trace, or follow them through to the Anki Desktop code

The aim is to know how to detect if an exception is one of the above (whether we need to compare strings, or whether we can already know by the exception class)
