### ISSUE TITLE
Renaming Hierarchical Tag

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16154]
If you rename a tag let's say, N1 to JLPT::N1 this creates a completly new tag instead of updating the hierarchy. I suggest that it change the hierarchy and bring N1 under JLPT instead of creating a completly new N1 tag.

(also someone suggested desktop behaves like that but I can not know that)

**Comment by david-allison** [comment]
Thanks for the report! It'll need to be changed upstream if we're going to implement it

**Comment by brishtibheja** [comment]
As Danika Dakika said, apparently this is how desktop behaves. Should this be reopened? @david-allison

**Comment by david-allison** [comment]
Sure! Could you post a screenshot to better explain the issue?

**Comment by brishtibheja** [comment]
https://github.com/ankidroid/Anki-Android/assets/136738526/43902f53-5328-4e1c-a70a-bb1eed7f7af9

Here I update N2 to JLPT::N2 which creates a completly new N2 tag. After rename, the (existing) N2 tag should've gone under newly created JLPT tag and shouldn't have been duplicated.

**Comment by david-allison** [comment]
That's "create (sub)tag", not rename. Working as intended

**Comment by brishtibheja** [comment]
It's not? This is what Danika Dakika said so I assumed I am simply renaming them.

> Renaming them should work (as long as you use the exact same text). What you did should move the N1 tag under the JLPT tag, and will create a JLPT parent-tag if it doesn’t already exist.

Can I use renaming in AnkiDroid?
