### ISSUE TITLE
the Statistics Text is not Readable

### ISSUE THREAD

**Issue by jainishrpandya** [ankidroid/Anki-Android#16153]
**Is your feature request related to a problem? Please describe.**
The text on the Statistics page is very small compared to the headings. and graphs are visible normally but the text is a little bit small to read. 

**Describe the solution you'd like**
We can make the text more readable and add more visualization to make it more easier to understand the data. Ex. Chart for Learn, Review, Relearn and Filtered data.

**Additional context**

https://github.com/ankidroid/Anki-Android/assets/69842037/01b15294-6895-48cd-9949-6292181402b7

**Comment by brishtibheja** [comment]
+make the pie chart interactable just like the bar graphs but that will have to be done in Desktop iirc

**Comment by BrayanDSO** [comment]
> +make the pie chart interactable just like the bar graphs but that will have to be done in Desktop iirc

Yes, it has to be done in Anki, since the screen comes from there.

**Comment by brishtibheja** [comment]
@jainishrpandya You can start a thread in the anki forums.
