### ISSUE TITLE
[BUG]: Newlines do not Appear on Review Screen

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16152]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Go to Settings >> Advanced.
2. Make sure "Replace newlines with HTML" is turned off.
3. Create a card with newlines (I did at least two)
4. Save that card and make sure it is not in the learning queue.
5. Go back to settings and turn on the option mentioned in 2.
6. Change daily limits and now see that card in review screen.

### Expected behaviour

newlines appear wherever they are

### Actual behaviour

newlines do not appear on review screen. go to the note editor and click save. this fixes the issue.

### Debug info

```text
AnkiDroid Version = 2.18alpha8 (6fc26947fd31743bc83e68f17ae7fec64bfa8e62)

Backend Version = provider(?) (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = null

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by brishtibheja** [comment]
@david-allison I randomly came across this yesterday. Whatever is causing this may have messed up my exported cards. FYI, I always keep "Replace newlines with HTML" turned on. If my issue persists even after this gets fixed I'll report it here then, if that's okay.

Also that naming is confusing because replace newlines with HTML sounds the opposite of "convert `<br>` to newlines".

**Comment by brishtibheja** [comment]
So I am actually "supposed" to open the note editor and press save? This didn't worked like that before I think. My cards came exported from another app with newlines and I didn't need to save them again.

> This isn't in AnkiDroid's manual. If you want to contribute making that less confusing, be welcome.

Sorry I can't. Working on GitHub goes over my head.

**Comment by BrayanDSO** [comment]
> This didn't worked like that before I think.

It did. The behavior hasn't changed.

> Sorry I can't

Since there is nothing concrete to do here, I'll close the issue.
