### ISSUE TITLE
Ci Failure (Windows-unit tests): Could not read workspace metadata from `C:\Users\runneradmin\.gradle\caches\transforms-4\0e69aaacf4af78f6c6c3f80936fa8b36\metadata.bin`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16161]
https://github.com/ankidroid/Anki-Android/actions/workflows/tests_unit.yml

First failure: https://github.com/ankidroid/Anki-Android/actions/runs/8645719390

Possible cause: cancelled build: https://github.com/ankidroid/Anki-Android/actions/runs/8645703463

```
3 warnings

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':AnkiDroid:checkPlayDebugAarMetadata'.
> A build operation failed.
      Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\0e69aaacf4af78f6c6c3f80936fa8b36\metadata.bin
   > Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\0e69aaacf4af78f6c6c3f80936fa8b36\metadata.bin

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org./

Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.

BUILD FAILED in 20s
25 actionable tasks: 8 executed, 17 from cache
Error: Gradle build failed: see console output for details
```

**Comment by david-allison** [comment]
Performing Rerun + clear caches : https://github.com/ankidroid/Anki-Android/actions/runs/8654514685

**Comment by david-allison** [comment]
The rerun on `main` was a success

A number of PRs have failing checks which continue to fail after a rerun

**Comment by bogdanzurac** [comment]
@david-allison We've been experiencing this issue on some of our internal projects as well. While searching for this issue online, this is the only other reference I could find. 

From what I can see, you're using Windows CI + updated recently to Gradle 8.7. Our CI runs Linux and Gradle 8.6/8.7 and we're also encountering the same problem. When have you first started seeing this? Does it only happen on CI or locally as well? Does it only happen when running unit tests?

**Comment by david-allison** [comment]
@bogdanzurac 

* Please see:  https://github.com/gradle/actions/issues/167
* Our temporary fix: https://github.com/ankidroid/Anki-Android/pull/16162

Your comments on the linked issue would be greatly appreciated. Specifically if you're running `gradle-home-cache-cleanup: true`

----

> When have you first started seeing this? 

* https://github.com/ankidroid/Anki-Android/commits/main/.github/workflows/tests_unit.yml
  * Workflow history:  https://github.com/ankidroid/Anki-Android/actions/workflows/tests_unit.yml
    * [Last success](https://github.com/ankidroid/Anki-Android/actions/runs/8644871195)
    * [Cancelled workflow](https://github.com/ankidroid/Anki-Android/actions/runs/8645703463)
    * [First failure](https://github.com/ankidroid/Anki-Android/actions/runs/8645719390)

We were previously having issues with the transform cache on our runners and re-enabled the cache on April 1: e7b894a5e04dd640c7bb8d5422d9a820353141e6

https://redirect.github.com/gradle/actions/issues/47

> Does it only happen on CI or locally as well? 

Only seen on CI

> Does it only happen when running unit tests?

Unknown. I haven't delved into `check${}AarMetadata`'s dependency graph

**Comment by mikehardy** [comment]
similar recurred - discord discussion https://discord.com/channels/368267295601983490/701922522836369498/1244755057342283816

I cleared related caches and CI went green

https://github.com/ankidroid/Anki-Android/actions/runs/9258853942/job/25469709342#step:8:91

```
Execution failed for task ':AnkiDroid:processPlayDebugResources'.
> Multiple build operations failed.
      Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\d959b569a6b68c46b9f909a1f83aa808\metadata.bin
      Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\d959b569a6b68c46b9f909a1f83aa808\metadata.bin
   > Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\d959b569a6b68c46b9f909a1f83aa808\metadata.bin
   > Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\d[95](https://github.com/ankidroid/Anki-Android/actions/runs/9258853942/job/25469709342#step:8:96)9b569a6b68c46b9f909a1f83aa808\metadata.bin
```

and

https://github.com/ankidroid/Anki-Android/actions/runs/9257726217/job/25466472650#step:8:86

```

> Multiple build operations failed.
      Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\d959b569a6b68c46b9f909a1f83aa808\metadata.bin
      Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\d959b569a6b68c46b9f909a1f83aa808\metadata.bin
   > Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\d959b569a6b68c46b9f909a1f83aa808\metadata.bin
   > Could not read workspace metadata from C:\Users\runneradmin\.gradle\caches\transforms-4\d959b569a6b68c46b9f909a1f83aa808\metadata.bin

```

**Comment by david-allison** [comment]
Haven't seen this in a long time, closing as completed

**Comment by LYFFYSAN** [comment]
just delete transforms-4 in the path C:\Users\runneradmin\.gradle\caches and reopen your project 
it worked for me

**Comment by Erosaddy** [comment]
> just delete transforms-4 in the path C:\Users\runneradmin.gradle\caches and reopen your project it worked for me

This one worked for me.
