### ISSUE TITLE
Gesture Compatible Whiteboard

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16164]
Gestures cannot be used when you have whiteboard enabled. That restriction can be removed if users are allowed to either—

1. Map actions to 2 finger gestures.

 2. Any gesture's two-finger version can be used just like the original gesture when wb enabled.

So instead of touching with one finger you touch with two finger to trigger the gesture action.

**Comment by BrayanDSO** [comment]
Too complicated, unintuitive and unergonomic IMO.

And disabling the whiteboard only requires a tap.

**Comment by brishtibheja** [comment]
> Too complicated, unintuitive and unergonomic IMO.

I don't think it's unergonomic but the former two, yes. But I figured it would help in my workflow as I use gestures to answer my cards. It ensures I'm always pressing Good/Again even when on bus. +This is also something that people who use Talkback are familiar with and it works fine. I mean it's not that hard to swipe with two fingers to answer or to tap with it.
