### ISSUE TITLE
CI: Deprecation: gradle/gradle-build-action

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16179]
Warning: This job uses deprecated functionality from the 'gradle/gradle-build-action' action. Consult the Job Summary for more details.

* [ ] DEPRECATION: The action `gradle/gradle-build-action` has been replaced by `gradle/actions/setup-gradle`. See https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#the-action-gradlegradle-build-action-has-been-replaced-by-gradleactionssetup-gradle
* [ ] DEPRECATION: Using the action to execute Gradle via the `arguments` parameter is deprecated. See https://github.com/gradle/actions/blob/main/docs/deprecation-upgrade-guide.md#using-the-action-to-execute-gradle-via-the-arguments-parameter-is-deprecated

https://github.com/ankidroid/Anki-Android/actions/runs/8681908926/job/23805375629?pr=16128

**Comment by mikehardy** [comment]
Fixed by #16192
