### ISSUE TITLE
"playback speed" for audio cards 

### ISSUE THREAD

**Issue by stasimon1** [ankidroid/Anki-Android#16175]
Hi

Adjustable "playback speed" for audio cards (separately for each fields in card) also would be a great tool."

Thanks and regards.

**Comment by david-allison** [comment]
Thanks for the suggestion! 

It'll need to be implemented in Anki Desktop before we get around to it here

Could you add a post here: https://forums.ankiweb.net/c/suggestions/17

Thanks!!
