### ISSUE TITLE
[Proposal] CI: upload test-results (stdout from tests) on failure

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16174]
Proposed in: https://redirect.github.com/gradle/actions/issues/76#issuecomment-2007584323

```diff
      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
-            **/build/reports/
            **/build/test-results/
```

I don't feel we need `reports`.

I feel the YAML should be modified so it does not execute if secrets are defined, to remove the possibility of data leakage in log files

**Comment by mikehardy** [comment]
copied from Discord for completeness - I'm okay with this based on my analysis at the moment:

---

> Due to the dangers inherent to automatic processing of PRs, GitHub’s standard pull_request workflow trigger by default prevents write permissions and secrets access to the target repository. However, in some scenarios such access is needed to properly process the PR. To this end the pull_request_target workflow trigger was introduced.

https://securitylab.github.com/research/github-actions-preventing-pwn-requests/

So, if we rely on `pull_request` trigger for the items that are untrusted, it should be okay from external forks - that is, there should be no possibility of secret leakage from unknown actors

Later they describe that the `pull_request` trigger *will* have access to secrets and write access to repo *from branches in the same repo*.  So *if* there was a YAML change from a known actor *then* we could leak secrets. I believe this is the same risk that already exists, in that anyone that has write access to the repo currently, could make a branch and could alter a workflow and could log secrets out (and/or upload them)

That is, I think our security surface area is actually the same with or without uploading here

**Comment by david-allison** [comment]
Ah, worked through things, thanks! Seems like we're good to go

The issue isn't YAML changes, we're 'safe' here
`pull_request_target` should not be checking out code, it's inherently dangerous and definitely out of scope
`pull_request`: no access to tokens unless merged (or added by a maintainer)

----

I felt the issue was secret leakage in artifacts:

* GitHub's secret scanning is good (tokens in logs are replaced with `*`), I've been able to bypass it when testing on a private repo, but it's a good guardrail
* It may not work as well in artifacts - documentation is unclear
* e.g. Someone adds Timber.w(ENV.list()) somewhere in either code or tests, and we get owned 
    * BUT this requires `env: {{ secrets.GITHUB_TOKEN }}`, which we don't do, so we're fine

**Comment by david-allison** [comment]
Tested in https://github.com/ankidroid/Anki-Android/pull/16128

* 70.9 MB folder
* One XML file per test
* `binary` folder is 36MB

In the XML, the `  <system-err>` element seems like noise, with a massive number of JaCoCo related errors:

I suspect these errors are impacting test execution time

```
<![CDATA[java.lang.instrument.IllegalClassFormatException: Error while instrumenting com/ichi2/libanki/exception/ConfirmModSchemaException with JaCoCo 0.8.11.202310140853/f33756c.
	at org.jacoco.agent.rt.internal_4742761.CoverageTransformer.transform(CoverageTransformer.java:94)
```
