### ISSUE TITLE
Move feature requests (& possibly non replicated bugs) to the Anki forums

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16189]
We had a discussion on Discord: https://discord.com/channels/368267295601983490/701922522836369498/1228668442794528778

General feeling was that we're getting too many "not planned" issues and should work towards removing the sources, so GitHub only contains actionable requests and we're not doing user support here

* Document the Discord discussion here 
* Ensure consensus on how much is redirected
* Figure out the forum to use & permissions
* Change the GitHub template to point there

**Comment by BrayanDSO** [comment]
My main goals with the move are:

1. Easily move general Anki issues to an appropriate section
    - As we now use the backend for a lot of features, any bugs or requested enhancements related to them should be done in Anki first
2. Move support to the forums
    - We frequently get reports asking for help understanding the scheduler, troubleshooting a template, etc.
    - So moving the support to the forums would:
        - focus the devs on dev tasks
        - direct the user to the helpers in the forums
3. Simplify the reporting process
    - For the user, it's easier to point to just one place to report issues
    - That way, it reduces the support burden of the people saying that "AnkiDroid reports are done in another place"
    - And reduces the amount of lost issues because people didn't come to GitHub or didn't want to create another account

---
I'd keep in GitHub only triaged issues and accepted feature requests that are specific to AnkiDroid, so all of the issues are actionable

**Comment by BrayanDSO** [comment]
> Figure out the forum to use & permissions

@dae

**Comment by david-allison** [comment]
To get the ball rolling, we can change the "enhancements" issue type to point to the Anki forums, and discuss/clean up our current list of enhancements

**Comment by dae** [comment]
I think the move to the Anki forums makes sense. If you need something from me, please be specific.

**Comment by dae** [comment]
Guys, one thing I forgot to mention is that all categories on the forums except the Suggestions and Add-ons categories will auto-close topics after 30 days of inactivity. That's not ideal for feature requests, so please make sure you direct people to the suggestions category. Alternatively, I can turn off the auto-closing for the AnkiDroid group, but that means ephemeral support requests will stick around and can be necroed.

**Comment by BrayanDSO** [comment]
@dae, could you please create a subcategory for AnkiDroid `Bug reports` as well?

**Comment by dae** [comment]
Happy to, but are you sure it's worth it? The desktop version uses a single Help category. The rationale is that users often think they've found a bug when they've in fact misunderstood something. So the help forum becomes a triage area, and when legitimate bugs have been reported, I use a [browser extension](https://github.com/abdnh/create-github-issue-from-anki-forum-post) to quickly create a GitHub issue for the report.

**Comment by BrayanDSO** [comment]
Okay, so let's test it with just `Help` and `Suggestions` for now

**Comment by BrayanDSO** [comment]
Up to discussion if we should leave a bug template here or not. The goal is to just post confirmed bugs, so most of them are actionable. So, only devs or informed enough people should post bugs in GitHub, and they don't need a template.

By not having a template, people are discouraged from creating bug reports here and should go to the forums instead, as they probably won't see or try using the `Open a blank issue` option.

The other option is having a template like Anki, which reinforces that only confirmed bugs should be reported:

https://github.com/ankitects/anki/blob/c4cd8808f3fc0ab583ccea8f0773fefbfe4b1d66/.github/ISSUE_TEMPLATE/bug-report.md

I'm open to both options, but at the moment I prefer the former.
