### ISSUE TITLE
[BUG]: Chinese (Taiwan) UI displays a mix of simplified and traditional characters

### ISSUE THREAD

**Issue by jiru** [ankidroid/Anki-Android#16183]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Using Android 11, AnkiDroid 2.17.6.

Android system language is set to "Traditional Chinese (Taiwan)" (displayed value is `繁體中文（台灣）`).

AnkiDroid language setting is set to "System language" (displayed value is `系統語言`).

Close AnkiDroid from the list of opened apps and open it again.

Go to Menu > Statistics.

### Expected behaviour

Statistics should be displayed using traditional characters only, like this (using workaround mentioned below):

![stats-ok](https://github.com/ankidroid/Anki-Android/assets/5107734/b7f9ed50-7b42-4ea1-8561-10b4a71f3fdc)

### Actual behaviour

Statistics are displayed using a mix of traditional and simplified characters. I am showing the example of the statistics screen here, but it happens in other places as well, such as the label of answer buttons (time interval) on card review screen, or the "Studied x cards in y minutes" text on the bottom of the main screen.

![bug-annotated](https://github.com/ankidroid/Anki-Android/assets/5107734/d0543fe3-20c3-4b82-b69d-02b5d7021106)

It’s important to understand that not all Chinese characters have a traditional and simplified variant, only some of them do. The characters I highlighted in the screenshot are the ones that have variants.

### Debug info

```text
I can send this upon request.
```

### (Optional) Anything else you want to share?

This issue is different from #7173 as there is a mix of simplified and traditional characters rather than the UI language wrongly selected.

This could be a regression because I think I realized it at some point after updating the app, somewhere between now and 6 months ago.

Interestingly, I can work around this issue by selecting "Chinese (Taiwan)" (displayed value `中文（台灣）`) in AnkiDroid language option.

After changing the language, remember to close AnkiDroid from the list of opened apps and open it again.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@jiru 

Thanks for the report! You can likely fix this by setting the in-app language to Chinese (Taiwan) in the settings

https://github.com/ankidroid/Anki-Android/blob/e38bfe4a977965e47f41cd321baf3774ccacd8dc/AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.kt#L221

**Comment by snowtimeglass** [comment]
@jiru FYI The title uses a string made for AnkiDroid specifically while the other strings in the screen is reused from the desktop version of Anki. 

So, considering without the title, I guess no mixing has occurred in the strings. In other words, Simplified Chinese seems to be used for the statistic screen (inappropriately) when the system language is Traditional Chinese.

**Comment by david-allison** [comment]
@snowtimeglass I've narrowed it down to using `zh`, rather than `zh-TW` for the Anki Backend language

**Comment by snowtimeglass** [comment]
I'm not familiar with it, but you mean that it has been done so intentionally for some reason and that this issue needs to be fixed by another approach other than changing that part?

**Comment by david-allison** [comment]
It's a bug, we'll get it fixed
