### ISSUE TITLE
"Set due date" should hint that "0 days" means today

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16199]
[Edit] "0 days" seems to be less intuitive in this case. It would be helpful if "Set due date" had hint text that "0 days" means today, as in the desktop version.

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/ff5bece2-30d0-4d10-bc41-8a3db77ca2a8" width="320px">

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/d11b8b76-1e4a-4c03-b6c4-84664d2ed0e4)

<details><summary>Before Edit</summary>

### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

0. Use a recent repository (after 8b3f2b07d082b5a25f776559d49f836fcc9d2642)
2. Open "Card browser"
3. Long press a card 
4. Three-dots menu > "Set due date"
   <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/ff5bece2-30d0-4d10-bc41-8a3db77ca2a8" width="320px">
5. Input "0"
   - Note: "0" means "today"
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/95099591-804c-4ed4-bc81-b3113643c440)

### Expected behaviour

`0 day` is shown

(as in the case of `1 day`)
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/c3a6d015-1746-42ee-bc10-e71c9f4f3342" width="320px">

### Actual behaviour

`0 days` is shown
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/1afd9b9b-14f0-4dc5-8bfa-9ce72a640ee0" width="320px">

### Debug info

```text
AnkiDroid Version = 2.18alpha8-debug (910795a5cb1caa26b121b3d85cab32d4cc2e1b76)

Backend Version = 0.1.36-anki24.04 (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

ACRA UUID = f74d8c3b-b173-4337-ae0c-819d3934bd5e

FSRS Enabled = false

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

It might be more helpful to change it to `0 days (today)` (even only in the left tab) or to show guide information under the input boxes when users input "0", as in the solution of https://github.com/ankidroid/Anki-Android/pull/16037: 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/4b2fe56a-641f-4a9a-87a0-be86ecf14d17)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) (not yet occurred in it)

</details>

**Comment by david-allison** [comment]
0 days is correct

> | Type     | Examples | Minimal Pairs                                                                                               | Rules           |
> |----------|----------|-------------------------------------------------------------------------------------------------------------|-----------------|
> | Cardinal |   other  | 0, 2\~16, 100, 1000, 10000, 100000, 1000000, … 0.0\~1.5, 10.0, 100.0, 1000.0, 10000.0, 100000.0, 1000000.0, … | 2 days 1.5 days |

https://www.unicode.org/cldr/charts/44/supplemental/language_plural_rules.html#en

**Comment by snowtimeglass** [comment]
> 0 days is correct

Thank you for pointing it out. I didn't have the knowledge. I should have researched beforehand. 

That said, I guess that "0 days" is less intuitive in this case. It seems to be room for improvement as you commented:
> we could add a hint of 'card(s) will be shown today'.

What would you think of renaming the title and reopening this topic?

**Before (Current):**
[BUG]: "Set due date" dialog box shows "0 days" instead of "0 day"

**After:**
enhancement: Add hint about "0 days" in "Set due date" dialog

**Comment by stranger-scripts-06** [comment]
Can I fix this please?

**Comment by Giyutomioka-SS** [comment]
Working on this !

**Comment by snowtimeglass** [comment]
> That works! Could you update the main post with the changes?

Thank you! I updated the main post just now.

**Comment by Giyutomioka-SS** [comment]
@snowtimeglass  Could you please review my PR and suggest changes regarding design?
