### ISSUE TITLE
Night Mode Quick Button (resuscitation)

### ISSUE THREAD

**Issue by promike-github** [ankidroid/Anki-Android#16190]
Hey there!

**Is your feature request related to a problem? Please describe.**
In older versions of Anki (2.14.6), there was a convenient Night mode quick button in the menu that I found really handy. I often (_every day_) switch between light and dark modes based on my environment, and having a quick toggle was super convenient. (_In bright light, I use light, in dark/evening I use dark._)

**Describe the solution you'd like**
If there has been no particular reason to remove the button, I would love to see the Night mode quick button restored in Anki. It would be great to have a small moon button next to the magnifying glass in the main menu for easy toggling between light and dark modes.

**Describe alternatives you've considered**
Alternatively, an option in the menu to automatically switch between light and dark modes based on the time of day could also be a helpful feature. However, my preference would be for a simple button in a more accessible location.

**Additional context**
I understand that this is a minor request, but I believe it would improve the user experience for those who frequently switch between light and dark modes.

**Comment by promike-github** [comment]
![Screenshot_2024-04-15-16-16-19](https://github.com/ankidroid/Anki-Android/assets/167091461/3af51cbf-4e54-49c7-858e-6acdac10f389)

**Comment by BrayanDSO** [comment]
Already rejected in #14204

**Comment by david-allison** [comment]
For context: we're moving to a bottom nav and we won't have room in the new future

**Comment by promike-github** [comment]
I appreciate your explanation.
While I understand and respect the team's decision, changing the settings at least twice a day is not the most user-friendly experience. It feels like I'm not doing something right.
It does not seem comparable to the settings around it. (_For example, no one adjusts the Max number of backups daily._)
I believe that having a convenient toggle option could improve the user experience without cluttering the interface.
Once again, thank you for your response

**Comment by david-allison** [comment]
Night mode should be in the Android system quick-settings menu (a swipe and a tap for me)

**Comment by promike-github** [comment]
I understand your suggestion about using the Android system's quick-settings menu for night mode. However, that dark mode is always on for me (_+Eye shield_), and I find it unnecessary to change the entire operating system's settings to accommodate a specific program.
I appreciate your insights and the considerations behind the decisions made by the team. Thank you.

**Comment by david-allison** [comment]
As always @promike-github, thanks for your politeness, positivity and patience. This is the primary reason I'm continuing here with this amount of effort, and it's down to you ☺️. A good attitude should be rewarded

Suggestions: 

**Gesture**
* We could add a gesture to toggle theme, but that would be messy: we have 4 themes and you likely wouldn't want to cycle through them. 
* Toggle day/night is feasible

I think the best option would be for us to support "switch theme" or "toggle night mode" in our JavaScript API. This can then be handled with the "user action" functionality which we provide. It's not as user-visible, but this solves it for advanced users. 

In a future extension, we can tie in "user action" and "JS API"

**Comment by BrayanDSO** [comment]
So, you always use dark mode for the entire system, but want to be toggling light/dark in only AnkiDroid?

Why do you want the system to be always dark, and not AnkiDroid to be always dark as well?

Most apps don't have a light/dark easy toggle. What do you do with them?
 
Is changing a setting in the settings page really that unconvenient? How many times (quantifiable) do you really need to change it?

**Comment by promike-github** [comment]
@david-allison 
Thank you for your kindness!
I'm fine with using gestures, even if it means cycling through all the themes.
It's way less hassle than going through the whole rigamarole of the
**Hamburger menu **->** Settings **->** Appearance **->** Theme **->** Pick theme **->** Back **->** Back **->** Back.**

Gestures would be handy for me, especially in bright sunlight when I can't always see the settings clearly and worry about messing things up.

@BrayanDSO 
I adjust the settings at least twice a day if I'm only dealing with natural light.
There are many times when I step in or out of a building, and the lighting changes.

I'm a fan of the dark theme, whether it's on my computer or phone. I stick with it all the time. The only exception might be the map, but I don't use that daily. When necessary, I also switch to the other mode manually.

On my computer, I can flip the colors with a hotkey, so Anki (desktop) supporting it or not doesn't bother me much. The light background in the dark strains my eyes, but I like the dark theme. However, I struggle to read text in dark mode when it's bright outside.


I'm all for gestures, although I have encountered some issues with them but I may go into details in a dedicated separate thread once I've gone through all the manuals.

**Comment by BrayanDSO** [comment]
I still don't think that the feature need is justified, either as a toggle or as a gesture. 

So, from my part it's a no. Up to the other maintainers if they want that.

**Comment by david-allison** [comment]
I don't have many qualms about adding useful functionality to the JS API, as long as we get the API right so we're not making breaking changes

I don't see the themes/night mode going away, so it'll be a positive addition

**Comment by brishtibheja** [comment]
Having the gesture would be useful actually! The toggle button, I never liked it. I sometimes would accidently press it (at night!) and oh my eyes... Gesture doesn't add such problems while providing an easy way to change the theme when you're suddenly out in daylight.

**Comment by david-allison** [comment]
I'd still be happy to add it as a gesture

**Comment by WallyWilly** [comment]
I would really love to have the quick day/night theme switching feature back. But it seems to be difficult, apparently all you regular developers are convinced that it is a useless feature. But as a regular user, I hate having to use the system theme switch for this, I really preferred the specific switch for Anki, it gave me much more usability control, since my cards are designed to behave according to the theme applied through the night css tag. And not always for a night style in all cases, in some it was for an easy style change without having to change the card template. It was just a swipe... Personally, I believe that many users also had frustrations with this, and the thing is that most of them don't have much knowledge about how things are done, I even had to search the entire changelog to find out that this wasn't even listed there as a change. I know this change isn't new, it happened a long time ago, but it's never left my mind.  And now that I have found this space, I leave my report here in favor of a night quick button.

**Comment by BrayanDSO** [comment]
As this is a feature request, please make it at the forums.
