### ISSUE TITLE
Support renaming flags

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16205]
* See https://github.com/ankidroid/Anki-Android/issues/16204

**Comment by criticalAY** [comment]
Taking it up next

**Comment by david-allison** [comment]
@criticalAY What's the rough plan for where this functionality exists?

**Comment by criticalAY** [comment]
I am thinking to put the rename setting in browser menu as Anki does here
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/0bd8fe03-ee91-41bc-81bc-64e5fd9e911d)

So, it would be somewhat consistent, we can give an option - `Rename flags` and click the submenu item i.e. flags should show a rename dialog where user can rename the flag or cancel it.

**Comment by david-allison** [comment]
Possibly long-press a flag name for now?

**Comment by criticalAY** [comment]
Thought of it, it would be less complex and clean then will go with this only

**Comment by lukstbit** [comment]
The vast majority of users will not use this feature so I don't think there should be an entry for this in the CardBrowser menu. As an alternative maybe we could add it in the CardBrowser's _Options_ menu dialog.

@criticalAY Before taking on other issues please also consider working on the issues you already have open and where there are changes requests.

**Comment by criticalAY** [comment]
I don't have a pending queue ig ? I'm mostly caught up which issue are you talking about though?

**Comment by david-allison** [comment]
You have a few open PRs: https://github.com/ankidroid/Anki-Android/pulls/criticalAY

**Comment by criticalAY** [comment]
I just resolved conflicts, and saw the comments left by luksbit on IO related PR which I missed the notification of, thanks!
