### ISSUE TITLE
In "Set due date" dialog, label and border line of input boxes can overlap

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16200]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

0. Use a recent repository
1. Open "Card browser"
2. Long press a card
3. Three-dots menu > "Set due date"
4. Tap the left tab

### Expected behaviour

The center `–` has sufficient padding:
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/fa2a327f-0039-4b3a-9655-f9a3fe82fe63" width="320px">
https://github.com/ankidroid/Anki-Android/pull/15699

### Actual behaviour

In my device, the center `–` doesn't have sufficient padding:
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/3c975137-80ab-4fb6-a573-efe244ca3af4" width="320px">

### Debug info

```text
AnkiDroid Version = 2.18alpha8-debug (910795a5cb1caa26b121b3d85cab32d4cc2e1b76)

Backend Version = 0.1.36-anki24.04 (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

ACRA UUID = f74d8c3b-b173-4337-ae0c-819d3934bd5e

FSRS Enabled = false

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

N/A

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks! I supplied `minEms` to ensure that the boxes do not increase/decrease in size, given the `days` suffix

https://github.com/ankidroid/Anki-Android/blob/8b3f2b07d082b5a25f776559d49f836fcc9d2642/AnkiDroid/src/main/res/layout/set_due_date_range.xml#L42

We can define a different layout based on screen width (`[xxx days] is the textbox`)

**vertical**
```
from: [xxx days]
to:      [xxx days]
```

**remove the days suffix**
```
[xxx] - [xxx]
```

Do you have any other proposed designs, or a preference?

**Comment by snowtimeglass** [comment]
Thank you, too.

Another quick thought:
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/176a7224-9307-4a15-a0de-67d88e7419be)


---
- model: _Toggle Track_ app
   <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/eba50c25-98fb-4a94-8ae0-3c6303496154" width="320px">
<details><summary>Screenshot of whole screen</summary>
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/31b16c33-6d4e-4e31-b9b9-cee92fa43f2d" width="320px">

</details>

---

Though the layout may be blamed from users who want to review the card next after more than 5 digits days (more than 27 years; conversely, I guess it would be fine for commonly expected number of days.

**Comment by snowtimeglass** [comment]
Ah, is that so. Then... I'd prefer "1. vertical" above without `:` after `from` and `to`, as follows
```
Show card(s) in range:
from    [xxx days]
to      [xxx days]
```

**Comment by snowtimeglass** [comment]
Thanks for the PR, but this issue still seems to be unresolved on 2.18beta2 in my device.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/cecdc7d4-f088-4982-8747-e80cce74eb1f" width="320px">

```
AnkiDroid Version = 2.18beta2 (dc5348852b15e0f27521acd3c5457595f4676f54)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

FSRS Enabled = false


Crash Reports Enabled = true

```
