### ISSUE TITLE
[BUG]: Set Due Date Dialog: "Help" should not close the dialog

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16206]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

* Create a card
* Select it in the card browser
* Open "Set Due Date"
* Press "Help"
* Close Chrome

### Expected behaviour

Dialog should still be there

### Actual behaviour

Dialog is closed

### Debug info

```text
AnkiDroid Version = 2.18alpha8-debug (a75ef34cf93c809931752f986f7b7ef95d51480b)

Backend Version = 0.1.36-anki24.04 (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 13; sdk_gphone64_arm64 Build/TE1A.220922.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.99 Mobile Safari/537.36

ACRA UUID = 762d4864-e56a-4027-8315-7a3fc9f8b4a9

FSRS Enabled = false

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

* https://github.com/ankidroid/Anki-Android/issues/14729
* https://stackoverflow.com/questions/2620444/how-to-prevent-a-dialog-from-closing-when-a-button-is-clicked

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@Aditya13s I'd want to get the `/releases/` improvements to a reviewable state (or unassigned) before assigning more issues here

**Comment by criticalAY** [comment]
@Aditya13s you already have got few issues assigned make sure you catch them before getting new one

**Comment by Aditya13s** [comment]
@david-allison This is the final result.


https://github.com/ankidroid/Anki-Android/assets/77337791/0ab7d348-21fb-4d53-898f-d47c9e0a8d3a

**Comment by david-allison** [comment]
@Aditya13s Just to note, you had two comments suggesting you finish some of your other issues

* https://github.com/ankidroid/Anki-Android/issues/assigned/Aditya13s

**Comment by Aditya13s** [comment]
> @Aditya13s Just to note, you had two comments suggesting you finish some of your other issues first. Good first issues are great for onboarding new contributors, and it's not fair to take them all.
> 
> * https://github.com/ankidroid/Anki-Android/issues/assigned/Aditya13s

I am encountering some difficulties with those issues, so I paused working on them and now work on them .
 I will remember to prioritize completing the assigned issues before tackling others.

**Comment by david-allison** [comment]
If you're not going to work on them, unassign yourself to give others the chance
