### ISSUE TITLE
Optimization: we should remove 'comment' from translated files to save space

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16208]
Optimization: we should remove 'comment' from translated files to save space

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/issues/16207#issuecomment-2064296781_
            

See: https://github.com/ankidroid/Anki-Android/blob/731203600791d01e7dfe1bdfb372679e66accb90/AnkiDroid/src/main/res/values-af/03-dialogs.xml#L240-L253

**Comment by BrayanDSO** [comment]
> to save space

If you mean disk space, it is only some kb. If you mean line space, I don't think that it matters. The comment may actually help a dev when debugging a string problem in another language

**Comment by david-allison** [comment]
If you find it useful, that's an obvious reason to keep it.

It's only noise to me when debugging

**Comment by BrayanDSO** [comment]
I don't care much if it stays or if it goes.

**Comment by harshit4311** [comment]
Yeah, I agree. We should remove it from translated files to save space.
I'd love working on this issue! Could you please assign it to me?

**Comment by david-allison** [comment]
@harshit4311 You've already got [a few issues assigned](https://github.com/ankidroid/Anki-Android/issues/assigned/harshit4311), could you complete these before asking for more
