### ISSUE TITLE
[DEV]: AnkiDroid API Documentation got lost

### ISSUE THREAD

**Issue by bnpd** [ankidroid/Anki-Android#16214]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Go to https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API  
All content is gone and Github prompts you to create a new page.

### Expected behaviour

The API reference should be available and liks in the Wiki & User Manual should not be broken.

### Actual behaviour

API reference cannot be found through search/links/wiki.

### Debug info

```text
Please restore from a backup, integration with AnkiDroid API is fun if well documented :)
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Note, this is about the java/kotlin API, not JS.

**Comment by david-allison** [comment]
Cheers!

Issue:

https://github.com/ankidroid/Anki-Android/wiki/_compare/ab6b0768e808118f49033a808a7d0e893b1b4333...9f17cb20178a27e640d018bbfe0484f2f2bcd7f7

Fixed:

https://github.com/ankidroid/Anki-Android/wiki/_compare/9f17cb20178a27e640d018bbfe0484f2f2bcd7f7...f737d8dcb4b8f1c56fe2e88799d72c03105c842e

Ref: https://github.com/ankidroid/Anki-Android/wiki/_history
