### ISSUE TITLE
FR: JS API function to add a specific tag

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ankidroid/Anki-Android#16210]
**Is your feature request related to a problem? Please describe.**
I saw that the JS API only supports opening the tag dialog but not directly adding a tag, but that's what I need.

**Describe the solution you'd like**
API function so that 1 click in the GUI adds a specific tag instantly to my note.

**Describe alternatives you've considered**
I often have many notes to tag, so I just end up flagging them or marking them and then going to my computer to see which one I would like to tag how.

**Additional context**
I have python scripts that run on my computer and do stuff to my cards depending on some tags. So quickly adding tags is vital for me.

I am willing to donate $15 instantly to the project if someone accepts to take a look at it. This feature would really be a life saver!

Thank you very much.

Also pinging @krmanik because he [implemented the function to open the tag dialog](https://github.com/ankidroid/Anki-Android/pull/9245)

**Comment by krmanik** [comment]
This can be implemented.

**Comment by thiswillbeyourgithub** [comment]
Great thank you

**Comment by david-allison** [comment]
Much appreciated!

I'll leave a good first issue tag here, as it shouldn't be a difficult change, please re-ping if things haven't moved to your liking

**Comment by Haz3-jolt** [comment]
@thiswillbeyourgithub this feature has been created, and will be shipped out with ver 2.19.

**Comment by silidev** [comment]
>  this feature has been created, and will be shipped out with ver 2.19.

@Haz3-jolt Thank you very much for this!
Removing a tag from a note should also be just as easy for you, am I correct? That would also be very handy!

**Comment by Haz3-jolt** [comment]
> >  this feature has been created, and will be shipped out with ver 2.19.
> 
> @Haz3-jolt Thank you very much for this!
> Removing a tag from a note should also be just as easy for you, am I correct? That would also be very handy!
> 
> 

Your welcome! Was fun working with js for the first time on a actual project. 😁

**Comment by Haz3-jolt** [comment]
> >  this feature has been created, and will be shipped out with ver 2.19.
> 
> @Haz3-jolt Thank you very much for this!
> Removing a tag from a note should also be just as easy for you, am I correct? That would also be very handy!
> 
>

Do you want a API method to remove a tag? Uhh, it should be pretty easy. Can you create a issue for with in the issues page, with the enhancement label? I'll get to it by tommorow at the latest.

**Comment by silidev** [comment]
Yes sure, thank you very much! ☺️

--
Viele Grüße - Helge

Hari Srinivasan ***@***.***> schrieb am Sa., 4. Jan. 2025,
12:24:
