### ISSUE TITLE
[BUG]: crash on clicking "Edit tags"

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16226]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Card Browser
2. Select all
3. Edit tags from menu

### Expected behaviour

some pop up opens up

### Actual behaviour

app crashes

### Debug info

```text
AnkiDroid Version = 2.18alpha9 (7da94c1238199a166310b7db63d53d5dbb40f054)

Backend Version = 0.1.36-anki24.04 (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.99 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Not seeing this one in ACRA

**Comment by brishtibheja** [comment]
When I said crash, I meant the app freezes and returns to deck page. Not sure if that's the proper term.

**Comment by criticalAY** [comment]
Not able to reproduce it

**Comment by brishtibheja** [comment]
Here's a recording.

https://github.com/ankidroid/Anki-Android/assets/136738526/f681d694-c46d-4cc2-8c6e-d777769a2e34

**Comment by david-allison** [comment]
I strongly suspect this is a `TranscactionTooLargeException` stemming from

https://github.com/ankidroid/Anki-Android/blob/2ac729cd8424cfd6363f27870bdfdda24d0ef00b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.kt#L1272-L1277

**Comment by neeldoshii** [comment]
For me:
In my case when i performed for a specific deck --> Select All --> Edit Tags --> Works fine

But 
when i performed for a all decks --> Select All --> Edit Tags --> Results in delay or sometimes Android Isn't responding 
Ref : Screenshots
<image src = "https://github.com/ankidroid/Anki-Android/assets/60827173/6261fb89-df42-4ce7-9c29-a5c3aa2c78f1" width=50% height=50%>
