### ISSUE TITLE
[BUG]: Flag in App bar not replacing default flag with colored flags

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16249]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Use current HEAD ([ffec26c](https://github.com/ankidroid/Anki-Android/tree/ffec26cba66afdf4fc94cbcfa12c2247fa5c0039))
2. Settings > Appearance >App bar buttons > Flag > Always show
2. Open Reviewer
3. Tap "Flag card" button
4. Tap "Red flag"

### Expected behaviour

the default ("transparent") flag is replaced with the red flag in App bar, as in 2.18alpha9
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/3d68e9ee-9ce3-4e6b-b8e2-41d36b0a4d17" width="320px">

### Actual behaviour

The default ("transparent") flag remains in App bar
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/dafe3ce9-ce6a-4456-b6da-940de23e6c78" width="320px">

### Debug info

```text
AnkiDroid Version = 2.18alpha9-debug (ffec26cba66afdf4fc94cbcfa12c2247fa5c0039)

Backend Version = 0.1.37-anki24.04 (24.04 429bc9e14cefb597646a0e1beac6ef140f226b6f)

Android Version = 11 (SDK 30)

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

ACRA UUID = f74d8c3b-b173-4337-ae0c-819d3934bd5e

FSRS Enabled = false

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

Color changes in Reviewer can be confirmed in Card browser.

https://github.com/ankidroid/Anki-Android/assets/10436072/5a323207-be74-4312-a291-6c0f92977cdb

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) (the issue does not occur yet)

**Comment by david-allison** [comment]
@criticalAY FYI
