### ISSUE TITLE
Undo stroke in drawing editor

### ISSUE THREAD

**Issue by kmicklas** [ankidroid/Anki-Android#16241]
**Is your feature request related to a problem? Please describe.**
When using the drawing feature added in https://github.com/ankidroid/Anki-Android/pull/9394, it seems like I need to complete the drawing in one shot with no mistakes.

**Describe the solution you'd like**
It would be nice to have a simple undo button.

**Describe alternatives you've considered**
Discard and redo until satisfaction. Works, but annoying.

**Additional context**
I guess a redo button would be nice too.

**Comment by leobugeja** [comment]
Hello, could I be assigned this issue? 🙂
