### ISSUE TITLE
[Emulator-only?] Record Audio Waveform not visible

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16258]
![image](https://github.com/ankidroid/Anki-Android/assets/48384865/d7934fe4-2341-4451-b250-eb3b8943ae9b)

It works fine in reviewer but in multimedia it has this issue now, Potrait -> Landscape -> Potrait, result in wave form to be invisible

_Originally posted by @criticalAY in https://github.com/ankidroid/Anki-Android/pull/16248#pullrequestreview-2016886844_

**Comment by shalenMathew** [comment]
in landscape mode the waveform becomes invisible can i try to fix it ?

**Comment by david-allison** [comment]
Thanks!
