### ISSUE TITLE
Lint unicode horizonal ellipsis "…" translated to three periods

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16269]
Should be using the Unicode. Optional lint improvement

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android/pull/16267#discussion_r1578311441_

**Comment by david-allison** [comment]
This is a good first issue. Please leave a comment if you'd like to work on this, and we'll improve the description to provide concrete steps for implementation

**Comment by Aditya13s** [comment]
I want to work on this.

**Comment by david-allison** [comment]
Sounds good! Do you need instructions, or do you feel it's easy enough to work out?

**Comment by Aditya13s** [comment]
Yes! Need Some Instructions.

**Comment by david-allison** [comment]
Here is a lint rule which involves CrowdIn strings

https://github.com/ankidroid/Anki-Android/blob/main/lint-rules%2Fsrc%2Fmain%2Fjava%2Fcom%2Fichi2%2Fanki%2Flint%2Frules%2FDuplicateCrowdInStrings.kt

Make a copy of the class, add it to IssueRegistry

Modify the functionality to: 

* Search through all languages rather than just `/values`

Check for `...` and return a lint error if this is found in any string value

If that works, rebase in a commit beforehand which fixes all the errors which are raised

We'll then go through to fix the issues on CrowdIn in the first commit, you can then drop the first commit, rebase the branch onto `main`, and we can merge the lint check

**Comment by lukstbit** [comment]
I think it would be simpler to use one of our current checks, in _TranslationTypo.visitElement()_:

```
// use the unicode character instead of three dots for ellipsis
if (element.textContent.contains("...")) {
    context.report(ISSUE, context.getElementLocation(element), "should use unicode '&#8230;' instead of three dots for ellipsis")
}
```

Fixing this issues will require manual changes on crowdin.
