### ISSUE TITLE
Request: apply "keep screen on" setting to previewer 

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#16274]
**Is your feature request related to a problem? Please describe.**

Can the "keep screen on" setting under advanced also be applied when using the previewer please?

**Describe the solution you'd like**

Keep screen on to prevent screen timeout when using the previewer.

**Describe alternatives you've considered**

N/A

**Additional context**
N/A

**Comment by david-allison** [comment]
I'd support if @BrayanDSO is happy, and you provide a quick use case for why you'd want this

**Comment by sudomain** [comment]
If there was an opensource app that could keep the screen on, I would use that, but not Tasker 😄 . Nonetheless, I found a setting under developer options that keeps the screen on while charging, which is good enough for my purposes. Sorry for the trouble

**Comment by sudomain** [comment]
Sorry again for not thinking to research separate apps. In fact, there are a couple apps currently on FDroid that are dedicate to keeping the screen on:
1. [Always On Display Toggle](https://github.com/Alberto97/AlwaysOnDisplayToggle)
2. [Coffee](https://github.com/mueller-ma/Coffee)

I just thought I'd comment with these in case other users request changes like I did or you guys end up discussing scrapping the setting 😁
