### ISSUE TITLE
Check Pronunciation: Additional Enhancements [persistence/bottom of screen]

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16288]
> Moving the recorder to the bottom of the screen is such a great idea. It could make things easier for people who prefer using the main buttons (Show Answer and friends) over gestures, especially on larger screens.
> 
> Speaking of the recorder button (check pronunciation), it's like a hidden treasure in the app, isn't it?
I've recommended AnkiDroid to a bunch of people over the years, but many of them miss out on the voice recorder feature because it's not immediately visible and needs to be enabled separately in the card menu (you may refer to it differently). And those "dangerous" buttons like "Delete note" can be a bit scary for some users, especially for the older ones.
> 
> I've noticed that "Check Pronunciation" is enabled, it disappears when they leave the deck, which means they end up not using it much. (It's interesting how the whiteboard function stays on while the pronunciation check doesn't.) Maybe if the feature could stick around until it's turned off (especially if it does not take up much space) or remember the decks it was used on, it could make things more user-friendly, especially for those who aren't as tech-savvy.

From @promike-github

----

- [ ] Move 'Check Pronunciation' to the bottom of the screen https://github.com/ankidroid/Anki-Android/labels/Blocked%20by%20dependency : new reviewer design
- [ ] Make 'Check Pronunciation: enabled' persist between review sessions

**Comment by leobugeja** [comment]
Hi I'm happy to work on persisting 'Check Pronunciation` state between review sessions.

To clarify, should this persistence be deck specific (similar to 'Enable whiteboard')?

**Comment by david-allison** [comment]
Bring the conversation to `#ankidroid-design` in Discord for consensus

I suspect per-deck is the best default

**Comment by leobugeja** [comment]
After discussion on [#ankidroid-design](https://discord.com/channels/368267295601983490/882228005504696350/1244643040044257340) the opinion is:

- Persist the feature state at the deck level.
- The `Check pronunciation` menu item should be renamed to reflect the visible state of the feature, similar to the whiteboard menu item. The text that made sense was "Enable voice playback" (in the case that it's currently disabled) and "Disable voice playback" (in the case that it's enabled).

**Comment by leobugeja** [comment]
@david-allison Could I get assigned to this please?

**Comment by david-allison** [comment]
Thanks!
