### ISSUE TITLE
Workaround for Syncthing

### ISSUE THREAD

**Issue by shuvashish76** [ankidroid/Anki-Android#16299]
To synchronize Android with Linux I need to sync the `AnkiDroid` folder of Android & the `Anki2` folder of Linux. Basically sync two folders
- Backups folder
- Collections folder

`collection.media` folder is same on both Android & Linux but here the problem is for backup folder Android use `backup` where as for Linux it's `backups`. I could sync both the folders separately but that's not the point here, I wanna sync whole  `AnkiDroid` folder with  `Anki2`.

Then after the sync I'd simply use "Restore from backup" option from 3dot menu to complete the process.

So my request is to rename the `backup` folder to `backups` to match with desktop to make things easier for users.

---

Is there any issue if android `collection.anki2`, `collection.anki2-wal`, `collection.log` files get synchronized with desktop? What's the use of such files?

**Comment by david-allison** [comment]
* `collection.anki2` - SQLite database 
* `collection.anki2-wal` SQLite write-ahead log
* `collection.log` is removed in 2.18, don't worry about it

You're at risk of corrupting your database if you're transferring hot journals: [How To Corrupt An SQLite Database File - 1.4 Mispairing database files and hot journals](https://www.sqlite.org/howtocorrupt.html#_mispairing_database_files_and_hot_journals_)

I'd strongly recommend using AnkiWeb or the sync server instead: https://github.com/ankitects/anki/tree/main/docs/syncserver

I'll propose closing this as https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix. I don't want to make it look like this style of syncing is encouraged

**Comment by shuvashish76** [comment]
Thanks for the infos.
