### ISSUE TITLE
Add Padding in Image Editor

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16290]
If you trying adding an image to a field from the note editor, you can also crop the image there. Trying to crop from the bottom sometimes (actually most of the times) trigger the gestures. I think the image should've been in the center of the screen ideally. There should've been some padding below it.

![Screenshot_2024-04-28-11-18-58-48_a9eef3a2a561b80d5c76daebd0f9a14c](https://github.com/ankidroid/Anki-Android/assets/136738526/5a975fde-0e30-4cb0-a93a-c09aa9c61e7b)

As you can see the image is covering up everything.

**Comment by david-allison** [comment]
This appears to be an issue in https://github.com/CanHub/Android-Image-Cropper

Will reopen if you confirm this is not an upstream issue
