### ISSUE TITLE
[suggestion] Add AnkiWeb logo to 'AnkiWeb account' screen

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16300]
As a desirable approach on the client (AnkiDroid) side, I suppose that it would be better to use AnkiWeb logo for the "AnkiWeb account" screen rather than AnkiDroid logo (only), to be less misleading. 
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/88d05c9e-d0d1-40d5-8ab3-3aed71289155)
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/69f9c2dc-1d6b-485a-84cd-9d18c6ece09d" width="320px">

In case that an app has a screen for connecting to Twitter/X, it is natural to use Twitter/X logo in the screen, rather than the logo of the app itself (only). 
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/905e78e3-42e9-4244-9cba-2b8053be3734" width="100px">

I would think the same is true for the screen for connecting to AnkiWeb.

_Originally posted in https://github.com/ankidroid/Anki-Android/issues/16260#issuecomment-2084674323_

**Comment by snowtimeglass** [comment]
> it would be better to use AnkiWeb logo for the "AnkiWeb account" screen rather than AnkiDroid logo (only), to be less misleading.

That is,
- Simply replacing the logo 
or 
- Displaying the two logos to visualize the independence of the app (AnkiDroid) and the external service (AnkiWeb) from each other.

  [Reference]
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/17b0ea3b-104c-4d9e-b428-9de8c9933b7d" width="320px">

  [image]
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/2ca19cd2-21d5-43a0-8328-d8a0dea08790" width="320px">

  (Anyway, the current logo on the screen may be a bit too big.)
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/1d452115-3764-45ee-b9d2-b22e75def73a" width="100px">

**Comment by david-allison** [comment]
I've labeled this as https://github.com/ankidroid/Anki-Android/labels/Good%20First%20Issue%21

The first step would be to propose a vector icon which:

- Fits the requirements above
  - `#ankidroid-design` on [Discord](https://discord.gg/qjzcRTx) if you need more real-time feedback
  - Bring the results of these discussions back to the issue
- Can be modified to work in Night Mode
- Will work Landscape + Portrait
- Works on both the 'MyAccount' and `LoginActivity` screens 
  - Log In + Logged In: we don't handle sign up
  - Do not make the image larger vertically. We can probably handle smaller
- Have a brief think about tablets 

You'll likely want to work with a placeholder for the AnkiWeb logo, then once the design seems reasonable, confirm with `@dae` that we're OK to use the logo in the design, and an appropriate license for it.

**Comment by tamojitdas** [comment]
Hi, can I work on this issue. New to open source contribution, hence would like to pitch in.

**Comment by david-allison** [comment]
That's great! Thanks

**Comment by tamojitdas** [comment]
Currently coming up with the logo design and placement along with caption, will get it verified tommorow on discord by @david-allison and @dae

**Comment by david-allison** [comment]
Great! No need to ping unless there's something for me to do

**Comment by devharsh2k4** [comment]
any updates on this i wanna try

**Comment by tamojitdas** [comment]
sure @devharsh2k4 will let u know

**Comment by tamojitdas** [comment]
HI @dae @david-allison @snowtimeglass require necessary feeds and confirmation for the following updated layout 
The Changes are done ..can raise a PR post confirmation
Login Page + loggedIn Page:
![logInPage](https://github.com/ankidroid/Anki-Android/assets/43579583/69f83644-ca2a-48cc-b74e-b8740f366d75)
![loggedInPage](https://github.com/ankidroid/Anki-Android/assets/43579583/b2d398f4-e6b9-46e7-a7a5-e66441e4c5fe)

**Comment by tamojitdas** [comment]
Also, just in case, if  you require to see landscape:
![loggInPageLandscape](https://github.com/ankidroid/Anki-Android/assets/43579583/76c669b5-42d9-4a5d-9cd7-2a06cc981e33)

**Comment by snowtimeglass** [comment]
Thank you for the work and the draft. 

Some concerns and expectation:

- I'm not sure that using "Authorize" here is appropriate. "Connect to AnkiWeb" might be better.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/d762196c-3457-4bd7-a510-274072848b77)
- 
  - Accordingly, the checkmark icon may also need to be reconsidered.
  ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/ad68997a-30e4-482c-a1bf-a2ac7c67b11f)


- The design of "connecting" seems to have room for improvement (in the future). The current black dots don't look very good to me.
  ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/4da28e24-099c-4dd3-8832-9512fc2ba93a)

  ---
   ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/883ce072-1151-4c39-9d2b-f6e30ad59dfc)
   ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/6cdf4a5d-c1d6-4faf-8e5b-8a45319600ea)
   ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/ce00d2d8-69a6-4217-aca4-afef0ae001e5)


  - Using AnkiWeb image only is also alternative.
     <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/38fea50a-4a2a-4873-a3de-210df0eb55a2" width="120px">


- The outline rectangle (shade) of the image looks unnecessary to me.
  ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/9ec91df4-94ae-458a-969d-f6ce913851b5)



- Spacing between images and the label and the input box looks narrow.
   ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/22d5b8be-e699-488b-999c-3bbe8e0a4172)

- The AnkiDroid image needs to be revised to more "official" one.
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/be6d71b5-3e08-4c9d-bcb3-04e012a06d7c" width="80px">![image](https://github.com/ankidroid/Anki-Android/assets/10436072/ece38a0a-5e47-4201-9a54-decd4c952526)![image](https://github.com/ankidroid/Anki-Android/assets/10436072/6d4319ca-33b9-4f94-8f57-5ebadaa37824)

- "AnkiWeb" text in the logged-in screen appears to be compressed vertically. It may be not desirable.
  
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/fb805044-af4c-43a0-870a-b640dfcddc80" width="220px">

  ---
  ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/17fda0da-56a9-4c8a-9df1-6be5992599e6)

**Comment by tamojitdas** [comment]
alright will work on this

**Comment by david-allison** [comment]
@tamojitdas you should come to the design channel on our Discord to get more instant feedback

And no need to ping `dae`, all that's needed is a final sign-off that he's ok with the AnkiWeb logo use, and an appropriate licence for us to use

**Comment by snowtimeglass** [comment]
Thank you, it generally looks better to me.

I too think posting it on Discord may be a good idea. 
You may want to take and use high-resolution screenshots for that.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/b1bf0847-a605-4d13-b311-f5b1bbffdf01)





I feel it might be even better if the vertical margins around the image area were a little wider.


![image](https://github.com/ankidroid/Anki-Android/assets/10436072/d64963bf-b919-4528-beca-ecbe0f35e04f)


![image](https://github.com/ankidroid/Anki-Android/assets/10436072/0101ccd1-f03c-4307-a77c-b51ad5c8274b)


"Connect To": "Connect to" (sentence case style) would be desirable as it is consistent with the notation of the other labels in this app.
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/c31df0e0-5a9e-407a-8dab-979786be7a7f)

Thanks again.
