### ISSUE TITLE
[BUG]: answer buttons swapped time periods

### ISSUE THREAD

**Issue by duckindisguise** [ankidroid/Anki-Android#16311]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

During learing

### Expected behaviour

Easy button displaying longer future period than the good button

### Actual behaviour

Good button shows a longer peruod than the easy button

### Debug info

```text
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A202F

Hardware = exynos7884B

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-A202F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.54 Mobile Safari/537.36

ACRA UUID = eeb53a64-eca5-4449-9d41-729eaaab7077

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Reporting this mini bug took me almost an hour. If I didnt see a dublicate Im sorry  I tried my best and either way will probably never report any bug ever anywhere again. (But still use this app, thank you)
![Screenshot_20240501-094009_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/168627645/dd9ca6b4-ec64-43d8-901d-db4532a6e499)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, this is almost certainly an issue with changes to your new card deck options:

https://docs.ankiweb.net/deck-options.html#new-cards

The good folks over at the [Anki Forums](https://forums.ankiweb.net/) should be able to help with this: https://forums.ankiweb.net/
