### ISSUE TITLE
[BUG]: Gestures for selecting answer buttons on back also reveal card answer from front

### ISSUE THREAD

**Issue by tomashaddad** [ankidroid/Anki-Android#16310]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Assign different gestures for revealing the back of and answering cards (e.g., double tap to reveal, swipe up/down/left/right to select answer buttons). Start reviewing. From the front of the card, use any of the gestures you assigned to selecting answer buttons.

### Expected behaviour

Using the gestures you assigned to selecting answer buttons while on the front of the card should not flip it. Only the reveal answer gesture should flip the card and reveal the back.

### Actual behaviour

Using the gestures you assigned to selecting answer buttons while on the front of the card flips the card and reveals the answer on the back.

### Debug info

```text
AnkiDroid Version = 2.18beta1 (c12b398c216dc2a2c2e2c98709c92132d19d105c)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G781B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-G781B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

ACRA UUID = 51cd624f-50d5-44f5-ba03-df2e45b897e6

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@BrayanDSO this one feels like a UX decision, it's been "flip & answer" for a long while

**Comment by BrayanDSO** [comment]
It has been that way for some years now, and I haven't seen any complain, so the best that I can give is a low priority.

Even with all the previous improvements, I still think that the controls selection UX is cumbetsome

**Comment by RobozinhoD** [comment]
I want to do those

**Comment by brishtibheja** [comment]
I use swipe right/left gestures for answering my cards. It enables me to swipe twice in the same direction to answer any card. With this implemented, will I have to have another gesture to flip the card and then use the other ones?

**Comment by BrayanDSO** [comment]
No

**Comment by david-allison** [comment]
We don't have capacity for this currently
