### ISSUE TITLE
[BUG]: After starting importing collection or restoring, the deck list does not refresh to the imported one

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16325]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Import a collection file
    - Three-dots menu on the main screen > "Import" > "Collection package (.colpkg)" > select a collection file * > "Replace"
       \* sample file: [collection-20240501195238 [colpkg].zip](https://github.com/ankidroid/Anki-Android/files/15186291/collection-20240501195238.colpkg.zip) (including a single deck with a single simple card)

   ---
   <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/e2d62bf1-2cda-48c3-9c83-504d7f76a817" width="220px">

### Expected behaviour

- The deck list refreshes to the new one (imported collection), as in 2.17.6.

### Actual behaviour

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/d0df3a7e-bc58-4612-b7ea-7cc4926e2571" width="220px">

- The deck list doesn't refresh to the new one (imported collection). 
- The buttons in the app bar disappears.

- (The deck list refreshes after restarting the app.)

### Debug info

```text
AnkiDroid Version = 2.18beta1 (c12b398c216dc2a2c2e2c98709c92132d19d105c)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

ACRA UUID = 5e59349c-ede4-4942-91b7-199dcf1342c0

FSRS Enabled = null

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

The same is true in the case of "Restore from backup".

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@snowtimeglass could you check to see if this is an issue in 2.17?

**Comment by snowtimeglass** [comment]
This isn't an issue in 2.17.6. As noted in the "Expected behaviour" above, the expected behavior occurs in 2.17.6. 

If I understand correctly, the 2.17.6 is the final version of 2.17 series.

<details><summary>Debug info (This issue has not been reproduced in this condition.)</summary>
AnkiDroid Version = 2.17.6 (568538896be943818ca793dd2635822265712def)

Backend Version = 0.1.34-anki23.12.1 (23.12.1 1a1d4d5419c6b57ef3baf99c9d2d9cf85d36ae0a)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

ACRA UUID = 719dac58-aa3d-49b5-b5e6-12a35df55d00

Crash Reports Enabled = true
</details>
