### ISSUE TITLE
Card Template Editor: ViewPager loses front/back toggle after 'don't keep activities'

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16337]
* Open the Card Template Previewer on "Basic (and reversed)
* Turn on "Don't Keep Activities"
* Pause + resume activity
* The Front/Back toggle fails

**Comment by BrayanDSO** [comment]
Perhaps duplicate/related to #14086 (I had broken a notetype and had to restore a backup because of it)

**Comment by david-allison** [comment]
I strongly suspect so, want to close as a duplicate?
