### ISSUE TITLE
[BUG]: When long pressing "Sync" button, its tooltip isn't shown; and after the long press, synchronization starts 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16343]
A minor bug

### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Long press "Sync" button in the deck picker screen.

### Expected behaviour

  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/e968a838-f6a8-4dd2-bf65-113ab7a07972" width="150px">

(2.17.6)

- The button's tooltip is shown.
- After the long press, synchronization doesn't start

https://github.com/ankidroid/Anki-Android/assets/10436072/a20bb604-6394-47db-b00f-5beb251b0fca

(2.17.6)

### Actual behaviour

- The button's tooltip isn't shown.
- After the long press, synchronization occurs.

https://github.com/ankidroid/Anki-Android/assets/10436072/dfaa75aa-23e0-404f-9812-d69fe1707aeb

### Debug info

```text
AnkiDroid Version = 2.18beta2 (dc5348852b15e0f27521acd3c5457595f4676f54)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.118 Mobile Safari/537.36

ACRA UUID = df169a4d-29ec-46b6-b114-141ca7e01ba3

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

N/A

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by RobozinhoD** [comment]
I can't reproduce the long touch issue
