### ISSUE TITLE
Expose all UI functions through the JS API

### ISSUE THREAD

**Issue by silidev** [ankidroid/Anki-Android#16359]
It would be amazing if all UI functions can be accessable through the JS API. By exposing all, a complete **UI overhaul** e. g. for better **accessability** (bigger) would be possible. Many UI functions are exposed, e. g. starting the tag chooser, burying, setting due date et al.; others are not, e.g. entering Edit-Mode.

**I would work on this issue if someone helps** me a little. I am able to modify the code of the JS API, but AnkiDroid's other code is just too complex for me / my available time. E. g.: 

1. How can I programmatically "press" the **Edit button**?
2. How do I programmatically **add a tag** to the current card?
3. It would be amazing to be able to **change a field** of the current card.
5. I am also very interested in programmatically "**answering**" (like tapping 1h, 1d, etc.) a card **and at the same time setting the due date to a different date** than the answer button has. The current API functions cannot be called after one another because the first one will continue to the next card. Also **changing the deck** at the same time would be very helpful.
6. Setting that a card should be displayed again in **one hour** or two hours, even if these times are not present on the displayed answer buttons.

Sorry for using funny terms, I am not versed in Anki's terminology.

**Comment by BrayanDSO** [comment]
Hi there. We are migrating feature requests into Anki forums in order to have a better experience for the reporters, and get a more focused and triaged space in Github for the devs.

I hereby ask to post the request on the [forums](https://forums.ankiweb.net/c/suggestions/17) so more people can give opinions there. Sorry for the extra work
