### ISSUE TITLE
Notify users when a due learning card is ready

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16358]
I have to switch between decks while there are still (re)learning cards due for later.

What ends up happening is I completly forget about them; by the time I get to those cards I've ofc already forgotten them.

Currently you can't set notifications for such situations. It would be helpful if this was allowed. Potentially something like "Notify when 10 learning cards are due" or something similar.

Alternatively, show a red dot in the deck and a red dot in the app bar while you are in review screen.

**Comment by shalenMathew** [comment]
can i contribute to this issue ?

**Comment by shalenMathew** [comment]
can i contribute to this issue ?

**Comment by BrayanDSO** [comment]
how is this different from what the `Notifications` settings try to do?

**Comment by BrayanDSO** [comment]
We are migrating feature requests into Anki forums in order to have a better experience for the reporters, and get a more focused and triaged space in Github for the devs.

I hereby ask to post the request on the [forums](https://forums.ankiweb.net/c/suggestions/17) so more people can give opinions there. Sorry for the extra work

**Comment by brishtibheja** [comment]
You guys could've kept these and move new feature requests to the forums. Anyways, I can do the hard work. Will start a new post there 👍

**Comment by brishtibheja** [comment]
@shalenMathew Hey posted it on the forums. Check it out if you will, https://forums.ankiweb.net/t/notify-users-when-a-due-learning-card-is-ready/44657/2

**Comment by shalenMathew** [comment]
> @shalenMathew Hey I posted it on the forums. Check it out if you will, https://forums.ankiweb.net/t/notify-users-when-a-due-learning-card-is-ready/44657/2

Ok 👌
