### ISSUE TITLE
[BUG]: Externally loaded JavaScript doesn't seem to work anymore in 2.18

### ISSUE THREAD

**Issue by Azzert** [ankidroid/Anki-Android#16352]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Using `import '<path to file in collection.media>';` in a card's script tag doesn't seem to work anymore, either through a relative path or by using the 'https://appassets.androidplatform.net' prefix.

### Expected behaviour

The file is imported correctly as in the desktop version or at least can be imported through the prefix mentioned above.

### Actual behaviour

The file fails to be imported. Looking through the debugger, it complains that `file://` is not a valid protocol in CORS when using a relative path and it says the file wasn't found when using the appassets URL.

### Debug info

```text
AnkiDroid Version = 2.18beta2 (dc5348852b15e0f27521acd3c5457595f4676f54)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = play

Manufacturer = motorola

Model = moto g(10)

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; moto g(10) Build/RRBS31.Q1-3-48-22; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.26 Mobile Safari/537.36

ACRA UUID = 259a6cb7-7280-4007-8d07-39acff87e836

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

This used to work in the previous version (2.17). I might be wrong, but I think it may have been inadvertently added in [this](https://github.com/ankidroid/Anki-Android/commit/e55cae28afc9ffcd9583a93e0f890ecb3351eca4) commit.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@BrayanDSO FYI

**Comment by BrayanDSO** [comment]
Hello there. Could you please share an `apkg` file with the related notetype so I can reproduce it here?

**Comment by Azzert** [comment]
Of course, here you have a small test one I created: [test-deck.zip](https://github.com/ankidroid/Anki-Android/files/15210083/test-deck.zip). I've put the JS file that should be in `collection.media` next to the `.apkg` since it wasn't being included when I exported the deck.
