### ISSUE TITLE
[BUG]: 2.18beta2 can no longer use paths like /storage/emulated/0/AnkiDroid

### ISSUE THREAD

**Issue by uqs** [ankidroid/Anki-Android#16365]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- install 2.17
- use /storage/emulated/0/sync/AnkiDroid as storage path (because SyncThing is shipping that off device)
- works fine
- upgrade to 2.18beta2
- ankidroid complains on startup, can't open database cannot restore from backup

Same problem happens on a fresh install. It opens fine, try changing the database path from the default /storage/emulated/0/Android/data/com.ichi2.anki/files/AnkiDroid to say /storage/emulated/0/AnkiDroid
It will say that it wasn't a valid directory.

### Expected behaviour

This is a regression and was working up till the last update (maybe I was on beta1, dunno)

### Actual behaviour

Android permissions are to allow "read and write to database", but I think it would need full filesystem access, no?

### Debug info

```text
AnkiDroid Version = 2.18beta2 (dc5348852b15e0f27521acd3c5457595f4676f54)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 6

Hardware = oriole

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 6 Build/AP1A.240505.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36

ACRA UUID = 53985122-f60a-4b54-89d4-ea6a2de1afcd

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by kot0dama** [comment]
Hi!

I'm having the same issue with latest AnkiDroid from F-Droid version 2.17.6 on one of my two devices (but not the other one). Both are using latest GrapheneOS.

I believe the permissions might have been automatically removed from one device, and the latest F-Droid 2.17.6 does not ask for Full storage access `MANAGE_EXTERNAL_STORAGE` as described on https://github.com/ankidroid/Anki-Android/wiki/Full-Storage-Access. Indeed, when I tried manually providing the permissions with adb, it yielded something along the lines of `com.ichi2.anki did not ask for XXXX permission`.

Installing the `Parallel.A` version (see link above) is a workaround as it asks the permission and can access storage.
@uqs ^

**Comment by giletvin** [comment]
Hi ! Same problem with Ankidroid 2.17.6 on Google Pixel 5, Android 14. 
 /storage/emulated/0/AnkiDroid was working fine yesterday, and is invalid this morning. 
Checking Android permissions, I saw that "read and write to database" was unauthorized, but restore permission didn't solve the problem.
Thank you for your help !

**Comment by BrayanDSO** [comment]
Versions from the play store can't access public directories like that one anymore because of Google policies. See this page for more explanation and a [workaround](https://github.com/ankidroid/Anki-Android/wiki/Full-Storage-Access).

**Comment by kot0dama** [comment]
Could you please reopen this bug?

I am not using the Play Store but the F-Droid version. I tried uninstalling and reinstalling, to no avail, the app does not ask for the permission to `MANAGE_EXTERNAL_STORAGE`.

Thank you

**Comment by BrayanDSO** [comment]
> I am not using the Play Store but the F-Droid version. 

Since that is specific to F-Droid, please create another issue for that

**Comment by uqs** [comment]
Thanks for the wiki page pointer. The workaround with giving it more permissions didn't work for me (Play Store), but when side-loading the full-universal apk it asked for full storage access and everything is back to working.

Can you clarify what changed recently for this to become an issue? Did the Play store policy change recently? Did this come about via a Play Services update? (Can't see the edit history on that wiki page ...)

**Comment by BrayanDSO** [comment]
https://developer.android.com/about/versions/11/privacy/storage

**Comment by uqs** [comment]
That doesn't answer my question though. I'm on Android 14 and the Play Store Ankidroid (beta channel) was working fine for at least half a year.

Was the target API level bumped? If so, why was that done in a point release? Seems odd ...

**Comment by uqs** [comment]
Well, spoken too soon. Turns out even the full-universal apk doesn't work. Today after opening AnkiDroid, it shows: Operation not permitted (os error 1)

It looks like it can't write back the database.
