### ISSUE TITLE
[BUG]: Optimiser Stops Working

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16367]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

I tried optimising my parameters for one of my decks which works fine. I don't save the settings, go back, do a review card, and try optimising once again.

### Expected behaviour

I should be able to optimise my parameters.

### Actual behaviour

The optimiser shows FSRS parameters are already optimal. 

### Debug info

```text
AnkiDroid Version = 2.18beta1 (c12b398c216dc2a2c2e2c98709c92132d19d105c)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/123.0.6312.121 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by brishtibheja** [comment]
Here's the recording of what I was doing: [Youtube](https://youtu.be/7QGGrfMDd8s?si=7R21kmWAiPP-O4IR)

**Comment by BrayanDSO** [comment]
We don't do anything different from Anki desktop on that screen, so I believe that's an upstream issue.

**Comment by BrayanDSO** [comment]
To ease the reproduction, exporting the deck with the scheduling information and deck presets would help

**Comment by brishtibheja** [comment]
> We don't do anything different from Anki desktop on that screen, so I believe that's an upstream issue.

Yes that is what I believe. I only opened this because Sherlock asked me to do so.

> To ease the reproduction, exporting the deck with the scheduling information and deck presets would help

Can you check [here](https://github.com/open-spaced-repetition/fsrs4anki/issues/644)? You need to change the date which I mentioned there.

**Comment by brishtibheja** [comment]
This was (most probably) an issue with FSRS Optimiser. I'm closing this thus.
