### ISSUE TITLE
[BUG]: Cards appear on wrong dates after burring then suspending it then unsuspending it after last update

### ISSUE THREAD

**Issue by Yahya-Mously** [ankidroid/Anki-Android#16375]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

buried a card then suspended it then unsuspended it

### Expected behaviour

apperring on the assigned date

### Actual behaviour

not appearing on the assigned date, and just getting repeated every day and due time not getting further
![b9145328b44593fd8f4db1c7e1e359f1581a204b_2_646x750](https://github.com/ankidroid/Anki-Android/assets/169539521/9e4ae7c3-5731-443f-ac79-a7a29eaa6499)
 

### Debug info

```text
Anki 23.12.1 (1a1d4d54)  (ao)
Python 3.9.15 Qt 6.6.1 PyQt 6.6.1
Platform: Windows-10-10.0.22631

===Add-ons (active)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
AwesomeTTS - Add speech to your flashcards ['1436550454', 2024-04-15T17:06, 'None', '']
Bar Chase ['1370131826', 2023-10-29T01:16, 'None', '']
Custom Background Image and Gear Icon ['1210908941', 2023-04-19T04:19, 'None', mod]
Image Occlusion Enhanced ['1374772155', 2022-04-09T10:15, 'None', '']
Review Heatmap ['1771074083', 2022-06-30T04:43, 'None', '']
True Retention ['613684242', 2017-11-19T22:43, 'None', '']

===IDs of active AnkiWeb add-ons===
1210908941 1370131826 1374772155 1436550454 1771074083 613684242

===Add-ons (inactive)===
(add-on provided name [Add-on folder, installed at, version, is config changed])
```

### (Optional) Anything else you want to share?

this issue happened 2- 3 months ago, i stopped it by schedule the cards that had it manually to today and then the Interval got back to a normal. back then I didn't have all of the add-ons that are in the debug report, maybe i updated anki since then, I tried to recreate the bug today, but it didn't happen.
also I submitted it back then to anki forums and i was suggested to to go to GitHub 
[https://forums.ankiweb.net/t/cards-appear-on-wrong-dates-after-last-update/40815](url)
i came here because it was cross-platforms bug

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Cross platform issues like that should stay in the forums. Here is the place of bugs specific to AnkiDroid
