### ISSUE TITLE
Jump to duplicate card ( Feature request )

### ISSUE THREAD

**Issue by learner0004** [ankidroid/Anki-Android#16385]
Please add button to go directly to duplicate card to edit it like in anki pc version. Thank you for this wonderful app.

![image](https://github.com/ankidroid/Anki-Android/assets/138207767/449470f8-75f7-450b-958d-05e4e615032e)

**Comment by BrayanDSO** [comment]
Hello there. Feature requests are currently done in the forums. Please send the request there: https://forums.ankiweb.net/c/suggestions/17
