### ISSUE TITLE
[BUG]: image occlusion type reappears when a card is added

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#16389]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Remove image occlusion note type
2. Add a card of any other type
3. Image occlusion note type appears

### Expected behaviour

Deleted note types should not reappear

### Actual behaviour

Image occlusion note type appears after being deleted

### Debug info

```text
AnkiDroid Version = 2.18.0 (464cf290cc77c3f2c562cb03b408b78a13be261b)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A346B

Hardware = mt6877

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-A346B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.123 Mobile Safari/537.36

ACRA UUID = d1aff59f-1f26-411d-b2e3-c282a25cadf2

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Also had a reddit post about this: https://www.reddit.com/r/Anki/comments/1clgluy/bug_image_occlusion_keeps_coming_back_every_time/

It's intentional, I'd typically say 'wait a little while longer'.

* https://github.com/ankidroid/Anki-Android/pull/14884#discussion_r1420413957

But given there's been two reports, I now (mildly) feel: "let's remove this for 2.19"

**Comment by mikehardy** [comment]
At current release cadence, 2.19 will likely be ~5-6mos after initial inclusion of this "add it every time to make sure everyone has it" thing.

That seems long enough.

Removing it for 2.19 seems fine, and for people really annoyed with it, if the removal happens fast and we release 2.19alpha they can get their hands on it quickly
