### ISSUE TITLE
Option to show top bar only in fullscreen

### ISSUE THREAD

**Issue by salmanuc** [ankidroid/Anki-Android#16399]
Kindly add the option to show top bar in fullscreen but system bars and answer buttons are hidden. The top bar shows timer as well as the option choosen as answer through the dots.  This makes especially useful when using a controller.

The top bar I am referring to I have circled in the picture below. 
![Screenshot_20240515_024046_AnkiDroid.jpg](https://github.com/ankidroid/Anki-Android/assets/138794113/7b4c261d-5bf8-4f71-815f-2b81b652591f)

**Comment by BrayanDSO** [comment]
Feature requests are done in the forums. Please create a post there https://forums.ankiweb.net/c/suggestions/17
