### ISSUE TITLE
[BUG]: Front card template android-app:// links not working in Preview screen since 2.18.0

### ISSUE THREAD

**Issue by hanpingchinese** [ankidroid/Anki-Android#16405]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Install [Hanping Chinese Dictionary Pro](https://play.google.com/store/apps/details?id=com.embermitre.hanping.app.pro) (I can send you a promo code, since it's a paid app).
2. Add Chinese Shared Deck "Hanping Chinese HSK (1-6)" to AnkiDroid 2.18.0
3. Tap on the "Hanping Chinese HSK" deck and tap play button - should hear the Chinese voice audio.
4. Tap "Show Answer" and tap on the pinyin ("wei2 bei4") - should hear the Chinese voice audio.
5. Tap Edit Note (overflow menu)
6. Tap Preview icon
7. Tap play button - should hear the Chinese voice audio but instead taken to Play Store app (to install Hanping Pro)
8. Go back to Anki and tap "show answer" - should hear the Chinese voice audio

### Expected behaviour

See above.

### Actual behaviour

See above.

### Debug info

```text
AnkiDroid Version = 2.18.0 (464cf290cc77c3f2c562cb03b408b78a13be261b)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 7a

Hardware = lynx

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 7a Build/AP1A.240405.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36

ACRA UUID = 32257909-1377-4d9a-9bbc-37d02f46eef1

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

So there is something broken about question template in preview mode only.

Example link href:

android-app://com.embermitre.hanping.app.pro#Intent;action=com.hanpingchinese.cmn.intent.action.PLAY;S.p={{text:Pinyin}};S.s={{text:Simplified}};S.t={{text:Traditional}};S.LANG=cmn;S._SOURCE=anki;end

Note: you can actually test this with the free app Hanping Lite (instead of Hanping Pro). Just need to change the template links from `.pro` to `.lite` (i.e. `android-app://com.embermitre.hanping.app.lite`)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by hanpingchinese** [comment]
https://github.com/ankidroid/Anki-Android/assets/19867743/62fae884-ee52-4423-92a9-2a9624f59c09

**Comment by BrayanDSO** [comment]
Why not using standard Android [deep links](https://developer.android.com/training/app-links/deep-linking)? We are not in 2016 anymore

**Comment by hanpingchinese** [comment]
There are still legacy APKs out there that rely on `android-app://` so regardless of how things should be done now, it's still worth supporting IMO.

Also it's worth noting that the [android-app](https://developer.android.com/reference/android/content/Intent#URI_ANDROID_APP_SCHEME) scheme has not been deprecated.

**Comment by BrayanDSO** [comment]
> that it has done so historically and AnkiDroid has always been strong at supporting legacy decks.

I don't think that sticking to the past per se is a reason for keeping features. Otherwise, `Chess notation` should be restored and the legacy TTS should be undeprecated, since they break a lot of decks and the workarounds are way harder than adding a simple deeplink, and need to be done by the users, not us.

But, `the feature is nice because of X and Y, so it should be kept` is a valid reason and I'm fine with it.

I still recommend deeplinks as a failproof measure instead of depending on AnkiDroid to avoid situations like this one.

**Comment by MorenoTropical** [comment]
Leave it to me
