### ISSUE TITLE
[BUG]: After upgrading to 2.18.0, my custom JavaScript is not working, but it works on AnkiMobile (iOS) and Anki on Windows 11

### ISSUE THREAD

**Issue by inherithandle** [ankidroid/Anki-Android#16403]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Upgrade AnkiDroid to version 2.18.0.
2. Create or open an Anki card that uses custom JavaScript, specifically wavesurfer.js for audio navigation and waveform display.
3. Attempt to use the audio navigation and waveform display functionality.

### Expected behaviour

expected to show me waveform, but waveform is missing.

### Actual behaviour

The custom JavaScript does not work, and the audio navigation and waveform display functionality is not operational on AnkiDroid version 2.18.0. This issue does not occur on AnkiMobile on iOS or Anki on Windows 11.

### Debug info

```text
Ankidroid 2.18.0
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Hello there. Could you send a zipped .apkg file with a card and the corresponding js file affected by it

**Comment by inherithandle** [comment]
here is apkg file and js file. please refer to the card that says "In middle school, 74% of the girls express science, technology as part of their interests," on the back.

apkg:
https://drive.google.com/file/d/1Y2MokGoR6WdOxX0l6LyyaOm2ZMM-1_4v/view?usp=drive_link

wavesurfer.js
https://drive.google.com/file/d/1-AL8oBPURpO3Eybs5vKz6ImxVB9X9U-1/view?usp=drive_link

**Comment by BrayanDSO** [comment]
2.17 used a different way to load files, but after noticing that it was considerably slower, we reverted back to the approach of 2.16.

That approach isn't compatible with Javascript's `fetch` API, and it's either that or loading media several times slower. It can be easily replaced with `XMLHttpRequest`, so that's what I suggest

Here's a modified version of your js file.

[js.zip](https://github.com/ankidroid/Anki-Android/files/15324054/js.zip)

If it doesn't work, ask for help on Discord or the forums

**Comment by inherithandle** [comment]
your javascript file does not work for both ankimobile (ios) and anki on ubuntu linux. are you sure about this? can you please check it again?

**Comment by inherithandle** [comment]
@BrayanDSO 
your javascript file does not work for both ankimobile (ios) and anki on ubuntu linux. are you sure about this? can you please check it again?
