### ISSUE TITLE
Add 20 second Timeout to `RobolectricTest`/`JvmTest`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16435]
This is what I wanted when I was diagnosing issues yesterday in

* https://github.com/ankidroid/Anki-Android/issues/16404

https://redirect.github.com/robolectric/robolectric/commit/5554acdd9c35f15381b0289e0c94f1a08aa39826

_Originally posted by @david-allison in https://github.com/ankidroid/Anki-Android-Backend/issues/377#issuecomment-2121030013_

**Comment by Aditya13s** [comment]
I will be working on it when the dependency get merged.

**Comment by david-allison** [comment]
Unblocked: 

* https://github.com/ankidroid/Anki-Android/pull/16433

**Comment by david-allison** [comment]
Add the rule (defined in the linked commit) to the classes (listed in the title of the issue)

Set a short timeout to ensure the rule stops the tests

Set the timeout to a correct value, and ensure tests still pass

Submit the PR

**Comment by Aditya13s** [comment]
> Unblocked:
> 
> * [build(deps): bump org.robolectric:robolectric from 4.12.1 to 4.12.2 #16433](https://github.com/ankidroid/Anki-Android/pull/16433)

In main branch, robolectric version is 4.12.1 in `libs.versions.toml`

**Comment by david-allison** [comment]
Unblocked now
