### ISSUE TITLE
Google TV support

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1643]
Originally reported on Google Code with ID 740

```
We should make sure AnkiDroid is usable on Google TV:
- Availability on Market
- Navigation without a touchscreen

Here are interesting tips:
http://android-developers.blogspot.com/2011/08/preview-of-google-tv-add-on-for-android.html
```

Reported by `nicolas.raoul` on 2011-08-23 01:10:44

**Comment by Magneticdud** [comment]
I just tried it on my android TV, and with the remote is possible to access everything except select a deck to study

**Comment by Magneticdud** [comment]
Good news! The deck can now be selected using the androidtv remote! (Tested on ankidroid 2.10.4).

I tried to add a card with the remote and it worked

But once a card is shown, the remote does not do anything, no part can be selected at all (hamburger menu, show answer, edit, more options,  play audio)

**Comment by david-allison-1** [comment]
@Magneticdud Can you access the settings? I'll be adding keybinding support for the reviewer in 2.12

**Comment by Magneticdud** [comment]
Yes, settings can be accessed from main menu (not when reviewing)

**Comment by Magneticdud** [comment]
hi bot, _still searching for solutions_

**Comment by david-allison-1** [comment]
I'll get automated keymappings for reviewing done in 2.14

**Comment by david-allison-1** [comment]
Hi @Magneticdud,

I'd like to take this on for AnkiDroid 2.14, but I don't have an Android TV to test this on.

What controls/buttons do you normally use with your Android TV?

How would you recommend we map buttons on your input device to AnkiDroid so you can review cards.

Thanks,
David

**Comment by mikehardy** [comment]
One of the available emulators is an Android TV emulator - https://developer.android.com/studio/run/emulator#avd - I've tested what apps look like on Android TV this way before, and the arrow keys work like the D-pad I think

**Comment by Magneticdud** [comment]
My remote has only dpad, back and click

Usually when i sideload regular android apps, the dpad is mapped like arrows, and when i click, it taps on the selected item

**Comment by david-allison-1** [comment]
@Magneticdud I've added reviewer TV support in the latest alpha, could you try it out and tell me what needs changing?

**Comment by david-allison-1** [comment]
Thanks!

> * is not clear what is highlighted. The color difference is very subtle. Especially if there's only two option, going right moves the highlight to left (flow back)

Would you recommend I took away the wrap-around behavior?

> * after answering the card, the hamburger menu is highlighted, so pressing OK will open the menu, instead of answering

That wasn't intended, and I don't think it happened on my emulator, I'll look into it.

**Comment by Magneticdud** [comment]
In my opinion, wrap-around is confusing when there's only two review buttons, because you don't know which is actually selected. It might be useful for the classic 4 review buttons if someone is using a gamepad, but i noticed that the 4 gamepad buttons are already mapped to each review score. Also, it defaults to "good", so if want to go "bad", two taps left, "perfect" one tap right, maybe could confuse people doing accidentally 3 taps and let a "bad" become "perfect"

**Comment by david-allison-1** [comment]
@Magneticdud 

In the next alpha: 

* I've removed the wraparound
* Can you please test the center button, it didn't work at all on my Android 29 TV emulator (I recall it working in the past on a different emulator).

**Comment by Magneticdud** [comment]
the center button, you mean the remote one? That's the OK i was referring, it works

I made a video of the remote + the app recording => https://imgur.com/a/fsTIjNN

**Comment by david-allison-1** [comment]
Hmm... looks like we'll need to see if my code improves things once the alpha's in, it might take a bit more calibration on our end

**Comment by david-allison-1** [comment]
@Magneticdud Any improvements?

**Comment by Magneticdud** [comment]
Tried alpha12.

Wraparound is removed. Hamburger menu is still selected after answering a card.

Noticed a minor issue: in settings, when choosing how many backups to store, it's not possible to submit the number. Can change the number, but when press OK, it won't save it or close the dialog. Need to connect a bluetooth mouse to tap on the slider to let it save it and close the dialog

Just noticed there's a new alpha. I'll connect the tv again to see whats' goin on

**Comment by david-allison-1** [comment]
@Magneticdud New alpha won't have solved the hamburger menu. What Android API are you running the TV on?

**Comment by mikehardy** [comment]
To be more specific: I don't think there were any changes for TV at all this alpha. We issue them pretty quickly to keep the changelist for each small and I don't recall TV-anything this time

**Comment by Magneticdud** [comment]
just tried alpha13, no difference as expected.

I'm on Android 8.0. They decided that for marketing reasons, my device is obsolete. They released a totally identical device, same SOC, same flash, same ram, different case. They consider it "new", so they do updates only for the new one.

another note: it doesn't appear on the launcher, in the beginning i thought this was normal (generic android apps won't appear), but then i saw some progress about androidtv icons and description?
