### ISSUE TITLE
Possibility of hiding the "easy" and "hard" buttons.

### ISSUE THREAD

**Issue by COLAB2709** [ankidroid/Anki-Android#16436]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Ever since I've been using AnkiDroid, in the communities I've been in, it's always been said that it's problematic to click on the "easy" and "hard" buttons. Whether this is the case or not, a culture has been created of AnkiDroid users who prefer to click only on the "again" and "good" buttons. Even if the problem was never really real or has been solved, people continue to click only on "again" and "good".

### Expected behaviour

It would therefore be refreshing to be able to hide buttons, especially the "easy" and "hard" buttons. Since not everyone finds these buttons useful, it would be nice to have only the two buttons that will decide the spacing trajectory on screen during the review: "again" and "good". There will be less visual pollution, more pragmatic minimalism.

### Actual behaviour

Nowadays, even though many people don't use the "easy" and "hard" buttons, they take up space on the screen so people don't focus as much as they should on the buttons that are actually used: "again" and "good". They may even accidentally confuse themselves when clicking.

### Debug info

```text
Alpha
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, we've moved feature requests to the forums, please send the request there: https://forums.ankiweb.net/c/ankidroid/suggestions/23 

Thanks!
