### ISSUE TITLE
[suggestion] Integrate Google Play In-App Review Api

### ISSUE THREAD

**Issue by Aditya13s** [ankidroid/Anki-Android#16430]
When we click on the Rate option it opens the play store.

https://github.com/ankidroid/Anki-Android/assets/77337791/d4e90c68-3165-485d-80cd-0457913303e5

We can integrate the Google Play In-App Review Api like this which is an enhancement for the app.

[![iar-flow](https://github.com/ankidroid/Anki-Android/assets/77337791/ee97e10e-2a5e-4b77-bf1d-6776deae7b74)](https://developer.android.com/static/images/google/play/in-app-review/iar-flow.jpg)

**Comment by david-allison** [comment]
Hi, we've moved feature requests to the forums, please send the request there: https://forums.ankiweb.net/c/ankidroid/suggestions/23
