### ISSUE TITLE
[Suggestion] Reverse Clozes

### ISSUE THREAD

**Issue by uyyrhf** [ankidroid/Anki-Android#16444]
A type of card that works like a regular cloze, except only one answer is shown by default, because I'm tired of nesting tons of clozes.

**Comment by david-allison** [comment]
Hi, we've moved proposed features to the forums so we can reduce the number of GitHub notifications. This allows us to focus our GitHub time on active issues and accepted enhancements

Feature requests can be posted: [Anki Forums - AnkiDroid - Suggestions](https://forums.ankiweb.net/c/ankidroid/suggestions/23)

Thanks for your understanding,
David
