### ISSUE TITLE
Replace remaining references to "Reschedule"

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16458]
In https://github.com/ankidroid/Anki-Android/pull/15699, `Reschedule` was replaced by `Set Due Date`.

However, `Settings → Controls` still uses the word "Reschedule".

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/953efbb2-095e-4b7f-88a4-62dff3303537">

Also, searching for "reschedule" in the repo gives many hits. So, many more references may need to be replaced.

**Comment by brishtibheja** [comment]
You are right. BUT it seems reschedule still has a different meaning. So all instances of this word might not need to get removed. For instance if you click reschedule in menu (in review screen) you get two options. One is set due date and another is reset progress.

**Comment by brishtibheja** [comment]
Well I said "You are right" because I use that setting and yes, it triggers only set due date so we're good here. Let's proceed with the changes 🚀
