### ISSUE TITLE
[BUG]: After upgrading to 2.18.0, my custom JavaScript is not working, but it works on AnkiMobile (iOS) and Anki on Windows 11

### ISSUE THREAD

**Issue by inherithandle** [ankidroid/Anki-Android#16469]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Upgrade AnkiDroid to version 2.18.0.
2. Create or open an Anki card that uses custom JavaScript, specifically wavesurfer.js for audio navigation and waveform display.
3. Attempt to use the audio navigation and waveform display functionality.

### Expected behaviour

expected to show me waveform on the front on the card, but waveform is missing.

### Actual behaviour

The custom JavaScript does not work, and the audio navigation and waveform display functionality is not operational on AnkiDroid version 2.18.0. This issue does not occur on AnkiMobile on iOS or Anki on Windows 11.

### Debug info

```text
Ankidroid 2.18.0
```

### (Optional) Anything else you want to share?

I wanted to reopen this issue #16403, but I can't. that is why I create this issue.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Fixed in #16457. Will be available in 2.18.1
