### ISSUE TITLE
[BUG]: Cards of type Basic (type in the answer) do not display answers

### ISSUE THREAD

**Issue by Mo-1996** [ankidroid/Anki-Android#16460]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- Go to Card browser
- Add a card of type "Basic (type in the answer)"
- The question and answer displayed on the added card are the same

**Record**
[re.webm](https://github.com/ankidroid/Anki-Android/assets/46777154/c8631fd5-bce2-4b40-9292-21b17effad78)

![image](https://github.com/ankidroid/Anki-Android/assets/46777154/c66f43f7-eb5d-4753-88e6-343286491376)
![image](https://github.com/ankidroid/Anki-Android/assets/46777154/8974d8b7-9de0-4b12-925d-cb0d5761d35b)

### Expected behaviour

When browsing, the card will display the corresponding answer, similar to the Basic type.

For example, the answer to the added card in the recording should be 16.

### Actual behaviour

The displayed answer is the same as the question.

### Debug info

```text
AnkiDroid Version = 2.18.0 (464cf290cc77c3f2c562cb03b408b78a13be261b)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 8.1.0 (SDK 27)

ProductFlavor = full

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 8.1.0; Android SDK built for x86 Build/OSM1.180201.037; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = aca1a327-477a-43a2-9e70-18a001fd3e0b

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, can be fixed with: 

https://youtube.com/shorts/JbxNP4pSIBA
