### ISSUE TITLE
[BUG]: BottomNavigation is not visible when keyboard is open ( CardTemplateEditor )

### ISSUE THREAD

**Issue by gayatriii0803** [ankidroid/Anki-Android#16477]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Go to CardTemplateEditor
2. Edit Card

### Expected behaviour

BottomNavigation is visible when keyboard is open

### Actual behaviour

BottomNavigation is not visible when keyboard is open

https://github.com/ankidroid/Anki-Android/assets/119813120/4d7fc3fe-c9ba-42d7-8a4b-35ff0f9dcc3a

### Debug info

```text
AnkiDroid Version = 2.19alpha0-debug (aa849fa3f42ed338a583cc30169ed5011df1cce3)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = amazon

Manufacturer = realme

Model = RMX3521

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; RMX3521 Build/RKQ1.211119.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36

ACRA UUID = 50dd5363-667e-4ec2-b25e-bf889d9292b3

FSRS Enabled = false

Crash Reports Enabled = false
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by gayatriii0803** [comment]
If it is valid issue, then I'd love to work on it

**Comment by user1823** [comment]
> Expected behaviour
> BottomNavigation is visible when keyboard is open

I don't think that this is the desired behaviour. If the bottom navigation is visible, the editing area would become very small.

**Comment by neeldoshii** [comment]
Will take it up.

**Comment by BrayanDSO** [comment]
Not a bug. If you want that changed, suggest it at the forums.
