### ISSUE TITLE
[BUG]: When editing a note from review, the reviewer screen jumps to the next card after note is saved

### ISSUE THREAD

**Issue by daddydave** [ankidroid/Anki-Android#16483]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

While reviewing a card in AnkiDroid, choose Edit Note from the menu.
Make the edit and save.

### Expected behaviour

The same card whose note was edited appears on the Reviewer screen.

### Actual behaviour

The Reviewer screen skips to the next card. This seems to be new behavior.

### Debug info

```text
AnkiDroid Version = 2.18.1 (5d13819ba811c6baea34dc747fce0568c755f31a)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 4a (5G)

Hardware = bramble

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 4a (5G) Build/UP1A.231105.001.B2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.180 Mobile Safari/537.36

ACRA UUID = 840c7342-1b95-4720-8c8e-5f24419cb68f

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by daddydave** [comment]
Not seeing this happen anymore with 2.18.2. 😀

**Comment by david-allison** [comment]
Still broken for some people.

2.18.2 was an emergency fix, and a full solution will be followed up in 2.18.3

* #16490
