### ISSUE TITLE
[BUG]: Can't Open Keyboard after Opening Tags Dialog

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16488]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Card browser
2. Menu
3. Filter by tag
4. Search Icon

### Expected behaviour

Keyboard opens up.

### Actual behaviour

Can't open keyboard. Tried clicking on the cursor.

### Debug info

```text
AnkiDroid Version = 2.19alpha2 (6bcf93dca00f36771212eaa2eeed489a37f85eb4)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.180 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

weird that I feel like somebody already reported it but found nothing in the issues

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Duplicate
