### ISSUE TITLE
[BUG]: Camera images maybe large message

### ISSUE THREAD

**Issue by John4650-hub** [ankidroid/Anki-Android#16492]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

I was trying to add an image to a flash card using the camera

### Expected behaviour

After taking the image i would expect to take me to the crop screen to resize the image.
Previously i would just take the image using my phone camera and then i would be taken to crop it.

### Actual behaviour

This is a screenshot of what happened
![Screenshot_20240527-211427](https://github.com/ankidroid/Anki-Android/assets/84484398/18e4ea76-e467-49c1-882a-6e4d630832bf)

### Debug info

```text
AnkiDroid Version = 2.18.0 (464cf290cc77c3f2c562cb03b408b78a13be261b)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 6.0.1 (SDK 23)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G532F

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0.1; SM-G532F Build/MMB29T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36

ACRA UUID = ebc1a772-0b02-42ba-9de7-8184c4986c89

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

I encountered this behaviour in version 2.18.0 of ankidroid 

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
I will be working on this area soon, so it will be fixed worry not

**Comment by John4650-hub** [comment]
@criticalAY  Thank you

**Comment by david-allison** [comment]
@criticalAY Still an issue?

**Comment by criticalAY** [comment]
No, it's fixed in the latest code
