### ISSUE TITLE
[BUG]: I can't use the app

### ISSUE THREAD

**Issue by Parhamsheikhi** [ankidroid/Anki-Android#16500]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

I didn't do anything, the program didn't open by itself yesterday

### Expected behaviour

I expected Anki to open for me every day, but suddenly this page appeared

### Actual behaviour

![Screenshot_2024-05-29-19-51-02-271_com ichi2 anki](https://github.com/ankidroid/Anki-Android/assets/171181776/ddb0a736-615b-4856-800e-090f28990374)

### Debug info

```text
.
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by criticalAY** [comment]
https://github.com/ankidroid/Anki-Android/wiki/Full%20Storage%20Access should give you the information you need
