### ISSUE TITLE
[BUG]:  Black theme, Cant read text. Android

### ISSUE THREAD

**Issue by Keffman** [ankidroid/Anki-Android#16503]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Just turn black or dark theme

### Expected behaviour

White text

### Actual behaviour

Dunno

### Debug info

```text
Don't
```

### (Optional) Anything else you want to share?

![Screenshot_20240530_135430_AnkiDroid](https://github.com/ankidroid/Anki-Android/assets/123264710/dc657bbb-a4e6-4a92-901e-4eb4aec53213)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
This is an issue with your card or its template. Try asking for help in the forums or Discord
