### ISSUE TITLE
 [BUG]: Make PermissionItem fully touchable

### ISSUE THREAD

**Issue by gayatriii0803** [ankidroid/Anki-Android#16506]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1.Go to PermissionActivity
2.Click on PermissionItem.

### Expected behaviour

PermissionItem fully touchable.

### Actual behaviour

PermissionItem is not fully touchable.

### Debug info

```text
AnkiDroid Version = 2.19alpha3-debug (1928dd00adf3514ddf0268ce4b9bcb032d972c23)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 6.0.1 (SDK 23)

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH1701

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0.1; CPH1701 Build/MMB29M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = bb61575f-ed56-4d3b-9dfb-f8ca8bc1021b

FSRS Enabled = false

Crash Reports Enabled = false
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by gayatriii0803** [comment]
I am working on it.

**Comment by BrayanDSO** [comment]
Not a bug. If you that changed, suggest it at the forums
