### ISSUE TITLE
[Code] Extract "text/plain" as constant

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#16508]
Maybe we can add `text/plain` in constants file?

_Originally posted by @ShridharGoel in https://github.com/ankidroid/Anki-Android/pull/16393#discussion_r1606052038_

### Checked for duplicates?

- [X] This issue is not a duplicate

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by shrutigitte** [comment]
I want to work on this

**Comment by Rutikgahukar** [comment]
I can solve this problem , i want to work on this project

**Comment by criticalAY** [comment]
@Rutikgahukar Already assigned as of now
