### ISSUE TITLE
[Enhancement] Extract magic build numbers to Version Catalog

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16517]
idle thought - is there a way to use the gradle version catalog to contain these magic numbers? (compileSdk / minSdk / targetSdk / compileOptions compatibility / kotlinOptions jvmTarget)

They are repeated a bunch

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/16498#discussion_r1621067466_

**Comment by AbdelrahmanEsam** [comment]
yes we can 
I will do it next after the build-logic pr
