### ISSUE TITLE
[BUG]: Edited Cards Not Retained in Filtered Decks

### ISSUE THREAD

**Issue by Gustav2024** [ankidroid/Anki-Android#16522]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- AnkiDroid Version: 2.18.2 (20240527)
- Issue since Version: 2.18.1 (20240523)
  - Suspected Cause: Possibly introduced by the fix "Fix deck handling note editor" as it seems related to the issue, though it could also be another fix.

**Brief problem Description**: 
Cards from Filtered Decks that are edited with the note editor are moved back to their original deck after the change, instead of staying in the Filtered Deck. Additionally, the edited card is not shown after the change; instead, the next card in the Filtered Deck is displayed.

**Steps to Reproduce the Issue**:

- Create a Filtered Deck:
  -  Create a Filtered Deck for cards in the "Due" state (green).
  -  Add all cards with this state to the deck. 

- Select and Edit Cards:
  - Select the Filtered Deck and start reviewing the cards one by one.
  - Enter edit mode for a card to correct a typo, for example.
  - Confirm the change by clicking the checkmark in the editor.

- Observed Behavior:
   - After confirming the change, the next card is displayed instead of the previously edited card.  
    - The edited card is removed from the Filtered Deck and moved back to its original deck, instead of remaining in the Filtered Deck.

### Expected behaviour

After editing a card in a filtered deck, the card should remain in the filtered deck and be displayed.

### Actual behaviour

A card in the filtered deck that is edited and confirmed with a click on the checkmark is not displayed; instead, the next card in the filtered deck is shown. Additionally, the card is moved back to its original deck.

### Debug info

```text
-
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by voczi** [comment]
Noticed the same, although I'm on 2.18.0. Similar thing happens to cards in normal decks when they're edited before showing the answer, next card depends on the gather method.

**Comment by david-allison** [comment]
* Likely related: https://github.com/ankidroid/Anki-Android/pull/16437

**Comment by david-allison** [comment]
Reproduced. Good in 2.18.0, bad in 2.18.1 

Apologies

**Comment by david-allison** [comment]
It was I

```
Author: David Allison <62114487+david-allison@users.noreply.github.com>
Date:   Tue May 21 04:01:36 2024 +0100

    fix(note-editor): display 'home' deck if filtered
    
    If a note is edited from the Reviewer
    And the note is in a filtered deck
    
    The 'current deck' should show the home deck
    Before this change it showed the first deck
    
    Fixes 15919

 .../src/main/java/com/ichi2/anki/NoteEditor.kt     |  7 +++--
 .../src/test/java/com/ichi2/anki/NoteEditorTest.kt | 36 ++++++++++++++++++++--
 2 files changed, 38 insertions(+), 5 deletions(-)
bisect found first bad commit
```
