### ISSUE TITLE
[BUG]: tags editor is showing diacritics as �

### ISSUE THREAD

**Issue by euu2021** [ankidroid/Anki-Android#16525]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- In Anki desktop, create a note with a tag that contains diacritics, like âáèõ
- In Ankidroid, open "edit note" window, in any note, and click to edit the tags
- the tag selector will have the tags with diacritics as �
- save this tag, and it will also appear in Anki desktop as �, as a duplicate of the original tag

### Expected behaviour

Diacritics showing up normally.

### Actual behaviour

diacritics as �

### Debug info

```text
AnkiDroid Version = 2.18.2 (f624ca684f2bee10203c67ed4f801aa4c5423b95)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = Xiaomi

Model = 21061110AG

Hardware = mt6893

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 21061110AG Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/124.0.6367.179 Mobile Safari/537.36

ACRA UUID = 7868d464-e23f-4df8-bc3c-262f71320c26

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report. 

* Fixed in https://github.com/ankidroid/Anki-Android/pull/16482
