### ISSUE TITLE
[BUG]: Image occulsion doesn't accept tags

### ISSUE THREAD

**Issue by Solutionful** [ankidroid/Anki-Android#16537]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Create an image occulsion card
2. Tag the card appropriately
3. See the card browser and notice that your card has not been tagged

### Expected behaviour

The created card should be tagged

### Actual behaviour

The card isn't tagged

### Debug info

```text
AnkiDroid Version = 2.18.2 (f624ca684f2bee10203c67ed4f801aa4c5423b95)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = Xiaomi

Model = 21051182G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; 21051182G Build/TQ3A.230901.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.26 Safari/537.36

ACRA UUID = bc188d8a-3f06-4e92-a2ec-e0e367166809

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

When creating an image occulsion tag with many areas (like four), it will create four cards. Tagging one of the four cards manually using the card browser will also tag the remaining cards.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
I'll join this with #16083. 

The root cause is the same: the NoteEditor contents aren't passed to the Image Occlusion screen, so they are ignored when adding a note.
