### ISSUE TITLE
[BUG]: Local Storage will be automatically cleared from v2.18.1

### ISSUE THREAD

**Issue by MoYiha** [ankidroid/Anki-Android#16563]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Local Storage will be automatically cleared when re-entering the deck. 

test code:
console.log(localStorage.getItem('testKey'))
localStorage.setItem('testKey', 'testValue')
console.log(localStorage.getItem('testKey'))

output:
null
testValue

Back to home screen and re-entering the deck will get same output.

v2.18.0(no issue)

I tried  v2.18.1, v2.18.2, v2.18.3, v2.19alpha4 release and build the latest commit [20add73](https://github.com/ankidroid/Anki-Android/commit/20add73857261a1562b5ce793d9ec0b86b2d92d2), have the same issue.

### Expected behaviour

Local Storage content is saved

### Actual behaviour

Local Storage content is cleared

### Debug info

```text
AnkiDroid Version = 2.19alpha4 (a2a109caa87ccfd84d9f49ae3294749712961ac2)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = Google

Model = Pixel 3 XL

Hardware = crosshatch

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3 XL Build/RQ3A.210605.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.148 Mobile Safari/537.36

ACRA UUID = d61e403a-4e8a-4238-b5e3-ee7011dd1658

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
We had to do a trade-off and this was reverted.. I'll reopen the original issue and close this one.
