### ISSUE TITLE
[BUG]: Copying a note and then saving it now results in a NullPointerException

### ISSUE THREAD

**Issue by benjmarks22** [ankidroid/Anki-Android#16569]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Pre-requisites: 2 decks, the first of which has at least one note (the second can as well but does not have to)

1. Open the card browser
2. Click on a note
3. Change the value of a field
4. Click the 3 dot menu in the upper right
5. Click copy note
6. Change the deck
7. Click the checkbox to save the copy to the second deck
8. Click the checkbox again to save the change to the original note to the first deck

### Expected behaviour

- The modified note should exist in the first deck
- A copy of the modified note should exist in the second deck

### Actual behaviour

- A copy of the modified note exists in the second deck
- Step 8 (saving the change to the original note to the first deck) shows a popup with the following text

**Error**
java.lang.NullPointerException

OK [right aligned]

Pressing OK and clicking the checkbox again results in the same error.

### Debug info

```text
AnkiDroid Version = 2.18.3 (e74513bdd21d521a7939a8b1f781123fb3ee2025)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 6a Build/AP1A.240505.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = dcd2b7f9-83a3-4437-a9ee-ced7c357e85b

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

This has been happening since at least version 2.18.1 (possibly 2.18.0 - I don't remember). I submitted a crash report in-app earlier today for this issue.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by shrutigitte** [comment]
i am working on this
