### ISSUE TITLE
Fix navbar color in note editor

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16573]
I think that a similar change should be made for the note editor too.

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/6001b6c0-f7dd-4879-8952-d722c82805a7">

<img width=300 src="https://github.com/ankidroid/Anki-Android/assets/92206575/bb789d2c-d287-480e-8111-94fccc8709ac">

_Originally posted by @user1823 in https://github.com/ankidroid/Anki-Android/issues/16568#issuecomment-2156605361_

**Comment by Giyutomioka-SS** [comment]
@user1823, as discussed in #16583, implementing the suggested changes in the note editor makes the navbar color look out of place and unappealing. However, you can create a suggestion in the forums if you want.

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix : we tried and it didn't look good

* https://github.com/ankidroid/Anki-Android/pull/16583
