### ISSUE TITLE
[BUG]: Review ahead but secondary day again 

### ISSUE THREAD

**Issue by Pr0pHesyer** [ankidroid/Anki-Android#16588]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. FSRS ON
2. Review a fraction of a deck ahead in on first day , don't review all of the custom deck. Don't delete the custom deck,leave some cards in it.
3. Secondary day, delete the custom deck. All cards will get back to the original deck , including the cards have been reviewed on the first day.

### Expected behaviour

The reviewed cards shouldn't due to be reviewed on second day.

### Actual behaviour

The reviewed cards is due to be reviewed on second day.
Even the interval of the button  becomes shorter when review on the second day than first day.

Focus the interval and the Date. It's 2024-6-12 when screenshot.
![Screenshot_20240612-142446](https://github.com/ankidroid/Anki-Android/assets/74277431/44928816-5c7f-4597-9cc1-5addf5086a60)

### Debug info

```text
AnkiDroid Version = 2.18.3 (e74513bdd21d521a7939a8b1f781123fb3ee2025)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 12 (SDK 31)

ProductFlavor = play

Manufacturer = LGE

Model = LM-G820N

Hardware = alphaplus

Webview User Agent = Mozilla/5.0 (Linux; Android 12; LM-G820N Build/SKQ1.211103.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = 10ee99ce-643f-44ad-b2f4-53df9a6e2b36

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

The cards I reviewed on first day due to be reviewed on second day with a longer interval.
I will test whether occur on Anki desktop tonight.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Pr0pHesyer** [comment]
Yes.
U can see the review log,date 2024-6-11 interval 18days.It's 12th now.
By the way,I couldn't confirm what time I review it exactly,it's the edge of the next day.BUT it's still a bug.
Sorry for my bad English.

**Comment by brishtibheja** [comment]
As for time of review change screen orientation to view `card info` screen in landscape mode. The time of review will show up then. On a different note, `custom study` itself has become really buggy after 2.16 I think.

**Comment by Pr0pHesyer** [comment]
Oh,recorded time is 2024-6-11@14:26.It really confuses me.

**Comment by BrayanDSO** [comment]
Scheduling is handled by the code that we get from the desktop version, so please send a report in the forums so the related people can take a look at it.
