### ISSUE TITLE
[BUG]: Issue with File Synchronization Between Anki Desktop and Ankidroid

### ISSUE THREAD

**Issue by MoYiha** [ankidroid/Anki-Android#16596]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Add new files to the `collection.media` folder in the Anki desktop version.
2. Perform a sync operation from the desktop version. The files appear as uploaded in the Anki desktop version.
3. Open Ankidroid and perform a sync operation.
4. Check the `collection.media` folder in Ankidroid for the new files.

### Expected behaviour

After adding new files to the `collection.media` folder on the Anki desktop version and syncing, these files should also be synced and appear in the Ankidroid `collection.media` folder. Similarly, files added in Ankidroid should sync back to the Anki desktop version.

### Actual behaviour

Files added to the `collection.media` folder on the Anki desktop version and synced do not appear in Ankidroid after a sync operation, even though they show as uploaded on the desktop version. Likewise, files added in Ankidroid do not sync to the desktop version. The files are only correctly synced when performing a one-way sync from Ankidroid. This issue persists even though the "Fetch media on sync" option in Ankidroid is set to "Always".

### Debug info

```text
AnkiDroid Version = 2.19alpha4 (a2a109caa87ccfd84d9f49ae3294749712961ac2)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 9 (SDK 28)

ProductFlavor = full

Manufacturer = Google

Model = Pixel

Hardware = sailfish

Webview User Agent = Mozilla/5.0 (Linux; Android 9; Pixel Build/PQ3A.190801.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = 680f17da-f7bc-4894-99ef-73f70513d9ba

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
AFAIK, you need to use `Check media` after manually adding or removing files in the collection.media folder.

**Comment by MoYiha** [comment]
> AFAIK, you need to use `Check media` after manually adding or removing files in the collection.media folder.

Thank you, I just tried using Check Media, and indeed, after adding files from Ankidroid, using Check Media can correct synchronization. However, if files are added on Anki, they still cannot be synchronized to Ankidroid.

**Comment by brishtibheja** [comment]
> However, if files are added on Anki, they still cannot be synchronized to Ankidroid.

For the benefit of humanity, you can report it here: https://forums.ankiweb.net
