### ISSUE TITLE
[BUG]: "Set due date" setting in App bar buttons also controls the display of "Reset progress"

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16598]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- In `Settings → Appearance → App bar buttons`, choose "Disabled" for "Set due date".
- Go to the reviewer and open the menu.
- See that it doesn't show the "Reschedule" option and, thus, the "Set due date" and "Reset progress" options.
- In the settings, now choose "Menu only".
- Return to the reviewer and see that the "Reschedule" option appears.

### Expected behaviour

The "Set due date" setting should only control the display of the "Set due date" option.

If it controls the display of both, the setting should be named as "Reschedule".

### Actual behaviour

Described along with the reproduction steps.

### Debug info

```text
2.19 alpha4
```

### (Optional) Anything else you want to share?

As a side note, I feel that if sufficient space is available in the menu, it doesn't make sense to have a separate menu for "Set due date" and "Reset progress".

<img width=170 src="https://github.com/ankidroid/Anki-Android/assets/92206575/126375b5-d2e1-43bd-92db-575d72c507a0">

Shifting those options to the main menu will save the users one tap whenever they want to use "Set due date" or "Reset progress".

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by brishtibheja** [comment]
`set due date` itself was called `reschedule` some time before and they do sound the equivalent of each other. If Anki Desktop doesn't use that term this is a mere relic from the past. I think it's confusing for new users, requires extra click and effort from users to access the features, bundles two unrelated features together when one may not need both of them.

**Comment by user1823** [comment]
Still looking for a solution...

**Comment by david-allison** [comment]
Broken in: b0de535d4c760072807120f1b99662c0f71ff3cf

* https://github.com/ankidroid/Anki-Android/pull/16461 `Reschedule` -> `Set due date`

But the menu is still named 'Reschedule'
