### ISSUE TITLE
[BUG]: "Set due date" setting in App bar buttons cannot be searched along with "Reset progress"

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16603]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

hamburger menu —> settings —> search icon —> put text `Set due date` and `Reset progress`

### Expected behaviour

search works

### Actual behaviour

search doesn't work

### Debug info

```text
latest alpha
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by brishtibheja** [comment]
tested again on 2.19beta1 but both searches do not work

**Comment by Prince-kushwaha** [comment]
working on this issue

**Comment by david-allison** [comment]
@brishtibheja was this fixed in: 

* https://github.com/ankidroid/Anki-Android/issues/17124

**Comment by brishtibheja** [comment]
Not sure. I can't build the app myself or check it in any other way.

**Comment by david-allison** [comment]
Should be in the latest beta

**Comment by Prince-kushwaha** [comment]
issue is present in latest beta. Able to reproduce it.
