### ISSUE TITLE
[BUG]: Can't see "No Flag" icon in light mode

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16622]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Tap "Flag card" option in the light mode or plain mode
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/b422ddfd-f039-4e8a-9da7-577efd30de12" width="320px">

### Expected behaviour

Can see "No Flag" icon, as in the dark or black mode, or like "Flag card" icon in the main menu:
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/c6f63944-2bcb-4b52-9d41-8d31becef84b" width="320px"> <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/ea98b546-c427-406d-b109-a078b89cb00a" width="320px">

### Actual behaviour

Can't see "No Flag" icon.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/2f7c6712-a43f-4a04-9976-d184994eb026" width="320px">

(Can see it when the item is being selected)
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/d64a8022-484b-4e1e-971e-94b722bb767d" width="320px">

### Debug info

```text
AnkiDroid Version = 2.19alpha4-debug (03dff23f9bbaca852a933c5a95dce70b257354e1)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 11 (SDK 30)

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = f74d8c3b-b173-4337-ae0c-819d3934bd5e

FSRS Enabled = true

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

N/A

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have confirmed the issue has not yet occurred in the latest alpha release

**Comment by shrutigitte** [comment]
I am working on this

**Comment by prathvihan108** [comment]
why does the app UI differ in my device ,it's up to date. There is no "flag card" option.
![Untitled2](https://github.com/ankidroid/Anki-Android/assets/150275112/ac5169cb-0bf9-47a3-9823-aa49419b6626)
![Untitled](https://github.com/ankidroid/Anki-Android/assets/150275112/32dced70-d379-46dd-8db1-4b0cd644e999)

**Comment by snowtimeglass** [comment]
In your case, you can find the "Flag card" option on the app bar. 

(That said, "No flag" icon itself has not introduced in the latest released version yet, so you can't find the "No Flag" icon.)

![image](https://github.com/ankidroid/Anki-Android/assets/10436072/09dd3ef7-51ba-465b-9098-6518b7020f63)

**Comment by prathvihan108** [comment]
> In your case, you can find the "Flag card" option on the app bar.
> 
> (That said, "No flag" icon itself has not introduced in the latest released version yet, so you can't find the "No Flag" icon.)

can you please brief , how can i get "2.19alpha4-debug" version on my local git, I am currently in the main branch.

**Comment by david-allison** [comment]
https://docs.ankidroid.org/#alphaTesting

**Comment by snowtimeglass** [comment]
The "2.19alpha4-debug" version was build by Android Studio in my device. I guess you can get it by Android Studio.

Now you may rather want to get the just-released 2.19alpha6 from the link above or here:
https://github.com/ankidroid/Anki-Android/releases/tag/v2.19alpha6

**Comment by SK3180** [comment]
i have started working on this..

**Comment by SK3180** [comment]
I have Fixed The Issue.
