### ISSUE TITLE
[BUG]: Quotation marks can not be added to deck names

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16628]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Use the Ditto mark (") in a deck name.
2. Save the deck.

### Expected behaviour

Deck appears with correct name.

### Actual behaviour

Quotation marks are removed from deck name upon save.

### Debug info

```text
2.19alpha4
```

### (Optional) Anything else you want to share?

1. This behaviour isn't relroducible for other quotation marks (`“”`, `«»`). 

2. I tried adding `"` while renaming the deck and it shows the "deck already exists" warning.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
> This bug does not occur in the latest version of Anki

Same behavior of Anki Desktop. Report it there, etc, etc, you know the drill
