### ISSUE TITLE
[BUG]: added links are not clickable

### ISSUE THREAD

**Issue by ruilya** [ankidroid/Anki-Android#16633]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Add a card with a URL in text

e.g.

```
Q: how foal is pronounced?

A: /fəʊl/

ref: https://en.wiktionary.org/wiki/foal
```

### Expected behaviour

When reviewing a card the link is clickable

### Actual behaviour

Link is not clickable

### Debug info

```text
AnkiDroid Version = 2.18.3 (e74513bdd21d521a7939a8b1f781123fb3ee2025)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G990E

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-G990E Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = 53292f5f-c004-44d5-ada3-706760b9232e

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

On desktop Anki, links are clickable by default when added to cards. I personally use this functionality to give references to source of the information for the given card. Unfortunately those cards that I've added with AnkiDroid do not have clickable links

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Probably an issue with your card template. Try asking for help in the forums https://forums.ankiweb.net/c/ankidroid/help/16
