### ISSUE TITLE
After canceling media sync, "Media sync complete." is often shown instead of "Media sync aborted" 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16631]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Tap "Cancel" in "Media Sync Log" dialog box

<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/3c1ef7a8-2455-4c90-9bd6-97a8a7bd688d" width="320px">

### Expected behaviour
"Media sync aborted." snackbar is always shown.
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/5dda8eb4-92fc-4af1-936e-4d223029ec7e" width="320px">

(as it is always so in Anki Desktop)
![image](https://github.com/ankidroid/Anki-Android/assets/10436072/a9fee2a2-7c75-43ec-80c6-107d180f005c)

### Actual behaviour
"Media sync aborted." snackbar is not always shown.
Instead, "Media sync complete." snackbar is often shown. 
<img src="https://github.com/ankidroid/Anki-Android/assets/10436072/9ccb9532-0ca6-4576-9f81-3ee0f5fac6db" width="320px">

https://github.com/ankidroid/Anki-Android/assets/10436072/afe2c3b4-8d7c-4a02-8712-a1c8b5cfa0e0

### Debug info

```
AnkiDroid Version = 2.19alpha6 (d2ddaaf122f6d03501bfec0adb88f510d93499f0)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = 5e59349c-ede4-4942-91b7-199dcf1342c0

FSRS Enabled = true


Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?
- "Check database" and "Check media" were done beforehand.

- It may be better to replace "Cancel" in "Media Sync Log" with "Abort", which is used in Anki Desktop.
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/00d26e8f-997e-486a-8cb2-aae16f397eb1" width="320px"> 
  ![image](https://github.com/ankidroid/Anki-Android/assets/10436072/c1e0c839-e9bd-404b-804a-058f6df74555)

- Sometimes the "Media Sync Log" doesn't seem to be shown properly:
  <img src="https://github.com/ankidroid/Anki-Android/assets/10436072/6b602fc7-0436-4a13-80a2-918cf0163c78" width="320px">
  (From 00:20 in the video above)
### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by vyom198** [comment]
I am working on this issue

**Comment by asp616848** [comment]
May I work on this issue ?

**Comment by david-allison** [comment]
Give @vyom198 some time, it's been two days

**Comment by vyom198** [comment]
> May I work on this issue ?

hey i have tried , you can work on this now

**Comment by david-allison** [comment]
@asp616848 all yours!

**Comment by david-allison** [comment]
@vyom198 feel free to come to [Discord](https://discord.gg/qjzcRTx) and ask next time! It's not in our best interests if you're stuck on something
