### ISSUE TITLE
[BUG]: Renaming Note Type Doesn't Take Effect

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16630]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

`manage note types` —> select a note type and `rename` —> `edit cards` and make some changes in template —> save and close the app —> open the app and look at the note type

### Expected behaviour

the note type has the new name

### Actual behaviour

previous name is retained

### Debug info

```text
2.19alpha4
```

### (Optional) Anything else you want to share?

even just after renaming the note type, previous name is shown in the template editor or whatever you call that

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by abhinavs1920** [comment]
Can you please assign this issue to me?

**Comment by Arthur-Milchior** [comment]
Sorry @abhinavs1920 , it seems nobody looked at it in some time.
Are you still interested by working on it ? If so, I can assign it to you.
By the way, don't hesitate to ask on discord if we don't answer. Or just to start the work when you see that nobody else seems interested.

**Comment by SanjaySargam** [comment]
This issue is sometimes reproducible and sometimes not.

**Comment by Arthur-Milchior** [comment]
@SanjaySargam can you clarify what you observed? you tried multiple time and it only sometime suceeded, is that it?

**Comment by SanjaySargam** [comment]
Yes
