### ISSUE TITLE
[BUG]: Learn ahead limit does not work

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16645]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Create a new card.
2. Press good (default learning steps).
3. Change `learn ahead limit` to >10mins.

### Expected behaviour

card shows up immediately

### Actual behaviour

card is shown as red in the deck picker screen but clicking on the deck shows that you need to wait a minute.

### Debug info

```text
AnkiDroid Version = 2.19alpha6 (d2ddaaf122f6d03501bfec0adb88f510d93499f0)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by soCallmeAdityaKumar** [comment]
Reproduced!!

**Comment by david-allison** [comment]
@brishtibheja was this an issue in 2.18?

**Comment by brishtibheja** [comment]
Just tried with 2.18.4 in a fresh install. No, it's not an issue there. But one thing I noticed is if you change `learn ahead limit` while in review mode, the change doesn't take effect until you leave the review screen.

**Comment by soCallmeAdityaKumar** [comment]
Working on this!!

**Comment by david-allison** [comment]
Just to note: this is a blocker for 2.19, so multiple people may be working on this at once
