### ISSUE TITLE
[BUG]: In 2.18.4, when the Reviewer screen gains focus, the user actions become invalid

### ISSUE THREAD

**Issue by ChuckieChen945** [ankidroid/Anki-Android#16681]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Add the following code to the front template of the card

    ```html
    <button class="button">Example Button 1</button>
    <button class="button">Example Button 2</button>
    <script>

    const jsApiContract = { "version": "0.0.3", "developer": "example@example.com" };
    const api=  new AnkiDroidJS(jsApiContract);

    var userJs1 = () => api.ankiShowToast('Run user action 1 by pressing a game controller button');

    </script>
     ```

2. Assign a key to user action 1
3. Start studying the card, and during the study process, press the key assigned to user action 1. At this point, the code executes normally
4. Click the screen to give it focus
5. Press the key assigned to user action 1 again. This time, the code bound to user action 1 cannot be executed; instead, the function of the game controller button itself is executed

I've recored a video:

https://github.com/ankidroid/Anki-Android/assets/29732324/3efb331b-29ef-4532-ae94-3540c1d0e29f

### Expected behaviour

When the Reviewer screen gains focus, the user action does not become invalid.

### Actual behaviour

When the Reviewer screen gains focus, the user actions become invalid

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 10 (SDK 29)

ProductFlavor = full

Manufacturer = HUAWEI

Model = MXW-AN00

Hardware = mt6873

Webview User Agent = Mozilla/5.0 (Linux; Android 10; MXW-AN00 Build/HONORMXW-AN00; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/99.0.4844.88 Mobile Safari/537.36

ACRA UUID = af76a139-3461-48a5-a908-b63a2cb7ad54

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
This isn't a bug per se. The shortcuts work differently in different contexts, like when something is focused or not. Some people expect that the Dpad should move around elements when focused, some others like you don't expect it.

Which is better? It's hard to argue, but I personally tend to prefer using the "default" behavior, which tends to be the most expected.

If you want that changed, please create a feature request in the forums.
