### ISSUE TITLE
[BUG]: New revlog doesn't appear

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16688]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Make sure `FSRS` is turned on
2. Optimise the parameters and save after `reschedule cards on change`

(a new revlog (rating=0) appears in card info of cards)

3. Optimise the parameters once again with `reschedule cards on change` (or manually change the parameters)
4. View card info of a card

### Expected behaviour

A new revlog appears once again with rating=0 which modifies the memory state and interval of cards

### Actual behaviour

1. The intervals of cards get modified but no new revlog appears if last rating was 0 (haven't tested this for `set due date` where rating=0)
2. Latest review date in card info also does not change

### Debug info

```text
2.19alpha7
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
All of that is done by desktop code. Please report it there
