### ISSUE TITLE
[BUG]:  Syncing problem

### ISSUE THREAD

**Issue by John4650-hub** [ankidroid/Anki-Android#16687]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Just  tried updating ankidroid to the latest version then my cards couldn't display images any more and even audio couldn't  play

### Expected behaviour

Card displayed correctly with all it's component

### Actual behaviour

This is a screenshot of what actually happened
![Screenshot_20240705-184957](https://github.com/ankidroid/Anki-Android/assets/84484398/e0f933f5-fb35-4119-9b59-5de5bd38225f)

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 6.0.1 (SDK 23)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G532F

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0.1; SM-G532F Build/MMB29T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36

ACRA UUID = 210f9dc9-6fa1-4edf-827c-b2f0a7586d2e

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by John4650-hub** [comment]
I have checked ankiweb and all my cards are actually displaying  correctly. 
![Screenshot_20240705-191830](https://github.com/ankidroid/Anki-Android/assets/84484398/29423eb6-e102-408c-bbae-e4554bc4fd53)

Is there a way to download the cards manually and then just import them into anki.

**Comment by david-allison** [comment]
You need to wait for your media to complete syncing

Please use https://forums.ankiweb.net/c/ankidroid/help/16 for further support
