### ISSUE TITLE
Create deck dialog "enter" should not enter a new line but similar to okay

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#16690]
If you open "create deck" or "rename deck", and tap the "enter" symbol of a keyboard, it enters a newline.
Instead, it should be similar to "ok". We are not expected to have lines in deck name. Actually, in Anki desktop, if you paste a new line caracter, it appears as a regular space and is stripped in the deck list.

**Comment by MinusMallard** [comment]
can i work on it

**Comment by MinusMallard** [comment]
I have fixed it so please assign me so that i can PR

**Comment by MinusMallard** [comment]
hey this is solved in #16704 so please close this one
