### ISSUE TITLE
[BUG]: Java null pointer exception saving a note after copying it

### ISSUE THREAD

**Issue by chreekat** [ankidroid/Anki-Android#16702]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Edit a note
2. Within the edit view, copy the note from the 3-dot menu
3. Save the new note with or without modifications
4. (After saving, you are back in the edit view for the first note.) Save the original note, with or without modifications

### Expected behaviour

Upon saving the original note, Ankidroid should save it successfully and return to the previous location

### Actual behaviour

Upon saving the original note, Ankidroid shows an error popup. The message is `java.lang.NullPointerException`.

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 6a Build/AP2A.240605.024; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36

ACRA UUID = 4d37c930-c6f2-4005-9bdb-2d19a16b291f

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

This bug is relatively new. A few months ago, I did not experience it.

I've sent a few crash reports through the app, but now I've figured out a more specific reproducer.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by soCallmeAdityaKumar** [comment]
Working on it!!
