### ISSUE TITLE
Improve typing of `findViewById`

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#16708]
This change is very low priority. (And wait until a maintainer confirm they agree with this proposition. Right now, it's not certain this is what we want to do)

`findViewById`, defined for Activity and View, is neither Nullable nor NotNull. This means the typer can't help us decide whether the returned value should be treated as nullable or not, making code harder to reason about.

Api 28 introduce `requireViewById`, that throws if the view is not found and returns a non null value. I suggest we use similar code to improve our typing. Given that we can't reuse the function name, I suggest using `requireViewByID` until the day min sdk is 28.

The process for `AnkiActivity.findViewByID` would use the following steps:

# Definition

First we must introduce those methods. I do it in PR #16709.

# Using them
This method is used in 516 places in our codebase. Do the change slowly. Each PR should be relatively small. Maybe it should contains one big class, or many small ones.

PR #16709 shows an example of such usage.

You can do it as follow.

Replace `findViewById` by `findViewByID` everywhere in one file. The typer will complain every place we actually use the result as a non-null value. In those place, use `requireViewByID`. 

Or you could replace `findViewById` by `requireViewByID`. The type will complain when we check whether the result is nullable. In those places, use `findViewByID`.

In any case: ensure the change you makes make sense. That you are certain the result can be null/can never be null. And run the code you change to ensure it works as expected.

# Forbidding the use of `findViewById`

With the linter, we can ensure we don't use it anymore.

This is only when this linter exists that we can close the bug as fixed.

**Comment by david-allison** [comment]
Disapprove: 

* Inconsistent naming 
* Name clash with an unusable API (easy to get incorrect)
* Little benefit to readability
* Huge code change 
* It's VERY rare that we won't have a view

ViewBinding would be a better use of time, and would deprecate this suggestion
