### ISSUE TITLE
[BUG]: After using Set Due Date, snackbar says card "rescheduled"

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16732]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

In the reviewer or browser, set the due date of a card.

### Expected behaviour

The snackbar says "Set due date of 1 card."

Anki string: https://github.com/ankitects/anki/blob/9d8782c31ca87b1de1a3d7e60d5bc4c2590479a1/ftl/core/scheduling.ftl#L170

### Actual behaviour

The snackbar says "1 card rescheduled."

This probably comes from https://github.com/ankidroid/Anki-Android/blob/703e6487ae39147ac5db8d6abb5bdc9b731d574b/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/SchedulerService.kt#L35
OR
https://github.com/ankidroid/Anki-Android/blob/703e6487ae39147ac5db8d6abb5bdc9b731d574b/AnkiDroid/src/main/java/com/ichi2/anki/scheduling/SetDueDateDialog.kt#L293

### Debug info

```text
2.19 alpha8
```

### (Optional) Anything else you want to share?

This is an issue not because AnkiDroid is inconsistent with Anki but because AnkiDroid is inconsistent with itself. Also, the word "Reschedule" has a more specific meaning in FSRS. So, it is better to avoid using it in other contexts.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Giyutomioka-SS** [comment]
looking into this.
