### ISSUE TITLE
Add 'wildcard import' to `.git-blame-ignore-revs`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16747]
* Obtain hash from https://github.com/ankidroid/Anki-Android/pull/16742
* Add it to the file, along with a one-line comment

**Comment by david-allison** [comment]
@andriusezerskis

One for you (optionally), but we can throw a Good First Issue tag, or get it done in a couple of minutes if you don't have time

**Comment by andriusezerskis** [comment]
@david-allison I'll gladly do it later today. Thanks !
