### ISSUE TITLE
[BUG]: Set due date does not work

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16744]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Add a card.
2. Select it, and tap on 'Set due date' in the menu.
3. Clear the checkbox for 'Set interval to same value'.
4. Enter '5' and tap on OK.

 (Cards get rescheduled to appear 5 days later)

5. Use 'Set due date' again but with a number greater than 6 (for example, 10).

### Expected behaviour

The due date is set to 10 days after today (or whichever number you use at the end).

### Actual behaviour

The due date changes by 1 day. For example, if it was 15th of August, it becomes 16th of August after the next 'Set due date'.

If I try another 'Set due date', the feature works normally.

### Debug info

```text
AnkiDroid Version = 2.19alpha7 (4aecb2a246a36d2efea0fdb555a2c484d2a884c1)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by MinusMallard** [comment]
I don't think this bug is in 2.19alpha9 version

**Comment by brishtibheja** [comment]
For some reason, that version is not available in the releases page in the repo. I think it was only released through play store?

Just to be sure, you used 'Set due date' twice on a fresh card with no revlogs? ('Set interval to same value' checkbox was also cleared?)

**Comment by david-allison** [comment]
Could you post a video? Can't reproduce this on `AnkiDroid Version = 2.19alpha10-debug (17343adc28e2b3ae6909e66f46c206c4efd32f57)`

**Comment by brishtibheja** [comment]
Hmm... working fine on alpha10.

**Comment by david-allison** [comment]
Thanks for confirming
