### ISSUE TITLE
[BUG]: Orange arrow flashes in menu on launching the app 

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16768]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

- Launch the app

### Expected behaviour

No orange arrow in the menu (as in 2.19 alpha 7)

### Actual behaviour

An orange arrow flashes in the top menu.

IIRC, this arrow button is used for storage migration. But, I am already using the scoped storage directory location.

### Debug info

```text
AnkiDroid Version = 2.19alpha10 (4afa7ec41ecc3efe7dd719db46c51cb09560292f)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 13 (SDK 33)

ProductFlavor = full

Manufacturer = motorola

Model = moto g62 5G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; moto g62 5G Build/T1SSIS33.1-75-7-6; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36

ACRA UUID = 38b5ca07-ddb1-4b0e-9d8c-30e3ac117703

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by shrutigitte** [comment]
ill do this

**Comment by user1823** [comment]
Still an issue in alpha 11
