### ISSUE TITLE
[BUG]: Instant editor's tapping makes cloze which ignores adjacent characters after symbol in middle of word

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16784]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1. Share the following text with Instant card:
`student's note(s)`
    <img src="https://github.com/user-attachments/assets/4ab67cba-e6a8-4b31-83e1-6474742d0527" width="320px">

2. Tap the words
     <img src="https://github.com/user-attachments/assets/d8d91beb-9ec7-46c2-845c-6f2e5dffe99f" width="320px">

3. Tap the pencil icon button
 

### Expected behaviour

Text in Text field is
`{{c1:student's}} {{c2::note(s)}}`

### Actual behaviour

Text in Text field is
`{{c1:student}}' {{c2::note}}(`

<img src="https://github.com/user-attachments/assets/1b479c94-652a-484b-8ab4-51c9c6911ed7" width="320px">

Screen after tapping the finger icon button:
<img src="https://github.com/user-attachments/assets/f00fffeb-c912-46d8-887e-faaa8dd90c0e" width="320px">

### Debug info

```text
AnkiDroid Version = 2.19alpha10-debug (73dde8aef587460c059e0de622e90eb6742fc1af)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 11 (SDK 30)

ProductFlavor = amazon

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/126.0.6478.134 Mobile Safari/537.36

ACRA UUID = 40e25c84-aa13-4b5b-be29-684c2e325a9d

FSRS Enabled = true

Crash Reports Enabled = false
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by peyman79** [comment]
I'd like to work on this issue

**Comment by peyman79** [comment]
I fixed the issue for these 3 characters, But in addition to the characters mentioned in the example `student's note(s)`, there are still other characters that may cause issues. How should the system be expected to handle these characters? The characters include `! " # $ % & * + , - . / : ; < = > ? @ [ \ ] ^ _ { | } ~`.

For example, given the input:
`20% of people are "rich"`

What should the output be? Currently, the output will be:
`{{c1::20}}% {{c2::of}} {{c3::people}} {{c4::are}} {{c5::rich}}"`

---

**Comment by snowtimeglass** [comment]
I'd say the following output would be desirable, as supposedly you think:
`{{c1::20%}} {{c2::of}} {{c3::people}} {{c4::are}} "{{c5::rich}}"`

**Comment by brishtibheja** [comment]
"rich" turning into rich" happens with almost every punctuation mark when wrapped around a word. @criticalAY this is similar to the bracket isuue; I also bought this up before.

@snowtimeglass I disagree with your evaluation of % sign. The sign is a replacement for the word percent, let's think about it that way for a moment. In a cloze it might not be clear that the question is asking percentage if the sign is inside the cloze.

**Comment by criticalAY** [comment]
* #16785
Will hopefully fix this one

**Comment by criticalAY** [comment]
@peyman79 @snowtimeglass @brishtibheja The percent sign after the word i.e. at the end of the word or any other punctuation mark will stay outside the close this is intended and I don't intend to change it, most user shouldn't have issue with this 
i.e. this is correct
> What should the output be? Currently, the output will be:
{{c1::20}}% {{c2::of}} {{c3::people}} {{c4::are}} {{c5::rich}}"

**Comment by snowtimeglass** [comment]
@criticalAY By the way, just to confirm for now, the percent sign after a word will stay inside a same chip, and you don't intend to change it?

**Comment by criticalAY** [comment]
Yes, it will be part of the same chip but it won't cloze. Also once this goes into the stable and too many users complain about it then 100% this will have to be changed, I am not fully rigid here :)
