### ISSUE TITLE
Tell the users why card type deletion fails when this would orphan note

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#16789]
An orphan note is a note that has no card. For example if you have a basic and reverse card, with only the front filled, and you delete the first card type, then the note has no card left.
In AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.kt, when the user tries to delete a card type, if that would cause orphan, we stop the user from doing it, thanks to `deletionWouldOrphanNote`
Except that the user does not know why it failed.
We should add a simple message dialog explaining that some note would not have any card anymore.

You can imitate the lines above, where the user gets a message stating that there is a single card type and so it can't be deleted

(I should note that, in anki, we can create orphan. There is no warning. The orphan first disappear from the browser if it's opened, and then reappear if you close and reopen it.
Honestly, I prefer the way ankidroid handle it, but if a maintainer prefer to imitate anki, fine)

**Comment by HUN-sp** [comment]
@Arthur-Milchior  Would love to work on this  issue .

**Comment by Arthur-Milchior** [comment]
Go for it. Sorry, it seems I can't assign from GitHub Android app

**Comment by HUN-sp** [comment]
Like? I am on it sir @Arthur-Milchior

**Comment by Sahil-Mandal15** [comment]
@Arthur-Milchior is this issue still open can I push my fix?

**Comment by Arthur-Milchior** [comment]
@HUN-sp Can you please give us an update ? David asked you to close one of the PR and rebase and force push the other. 
If you've not done in in 48 hours, then I'll assign it to @Sahil-Mandal15. It's supposed to be a short task, if it's not updated in a week already, I think it's okay to close this PR

**Comment by Sahil-Mandal15** [comment]
@Arthur-Milchior I have my initial fix ready for the issue, I will create a PR when this is assigned to me.

**Comment by HUN-sp** [comment]
Hey @Arthur-Milchior assign it to sahil

**Comment by Sahil-Mandal15** [comment]
@Arthur-Milchior  I am waiting for the issue to assigned to me to create the PR or should I proceed with it?

**Comment by Arthur-Milchior** [comment]
@Sahil-Mandal15 you could have proceeded. Of course, you're now assigned anyway.
Our goal here is just to ensure that we don't waste work, not to follow strict procedural rules. Given that HUN-sp mentioned they would let you work on it, and nobody else wanted it, it was perfectly to start

**Comment by devharsh2k4** [comment]
Is it still open?
