### ISSUE TITLE
Rename 'Modify today's review card limit'

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16806]
In the options for Custom Study, 'review card limit' needs to be renamed to 'maximum limit'.

The English name was changed upstream [in this PR](https://github.com/ankitects/anki/pull/3320).

This still needs to wait until Anki Desktop releases it's next version.

**Comment by david-allison** [comment]
For context, @brishtibheja contacted me on Discord about this

I'm closing this as it will come through in the next update to the backend: https://github.com/ankidroid/Anki-Android-Backend

No work needs to take place

Thanks so much for the link to the PR, it saves a ton of time
