### ISSUE TITLE
[BUG]: header and footer html tags not rendering correctly

### ISSUE THREAD

**Issue by nico-lechatnoir** [ankidroid/Anki-Android#16819]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

External CSS file is used to style cards but does not render any `header` or `footer` declarations. All other styling rules render correctly from the external file. 

### Expected behaviour

The `header` and `footer` should render as styled with matching margins to the rest of the card and a fainter text color. 

### Actual behaviour

![Screenshot_20240804_090035_AnkiDroid](https://github.com/user-attachments/assets/de4f4e12-573e-455f-b478-070120fbe321)
The pleco and Tabenta text should have larger margins with the bottom of the cards. 

Test hanzi and continent should show as a flexbox as a single line with larger margins from the edge of the card. Test hanzi should be right aligned and smaller grey text. Continent should be right aligned. 

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-S911W

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S911W Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.64 Mobile Safari/537.36

ACRA UUID = f85fc69e-888b-4391-b92d-cd15f1283311

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

This bug also occurs on the iOS app on ipad

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Could you provide a sample exported note which works in Anki Desktop and fails in AnkiDroid?

**Comment by BrayanDSO** [comment]
I also ask to test how it looks like in the previewer (Card browser > select a card > three dot menu > Previewl

**Comment by nico-lechatnoir** [comment]
Here is the html for the back side of the card:
```html
<div class="prettify-flashcard">
	<header>
		<span class="card-type">{{Card}}</span>
		{{#Tags}}<span class="prettify-tags">{{Tags}}</span>{{/Tags}}
	</header>
	<div class="prettify-field prettify-field--front">
		<div class="hanzi" id="conditionalContent"><span lang="zh-CN">{{Color Hanzi}}</span></div>
		<div id="pinyin" class="pinyin">{{Pinyin}}</div>
		<div class="sound">{{^Sound (Male)}}{{^Sound (Female)}}{{tts zh_CN speed=1:Simplified}}{{/Sound (Female)}}{{/Sound (Male)}} {{Sound (Male)}}{{Sound (Female)}}</div>
	</div>

	<hr class="prettify-divider answer" id="answer" />

	<div class="prettify-field prettify-field--back">
		<div id="example0" class="english">{{English}}</div>
		<section id="moreInfo" lang="zh-CN">
			{{#Also Written}}
			<div class="also">{{Also Written}}</div>
			{{/Also Written}} {{#Classifier}}
			<div class="classifier">{{Classifier}}</div>
			{{/Classifier}} {{Frequency}} {{#Notes}}
			<div class="notes">{{Notes}}</div>
			{{/Notes}}
		</section>
	</div>
	<footer>
		<div class="link">
			<a class="desktop-only" id="MDBG" href="https://www.mdbg.net/chinese/dictionary?page=worddict&wdrst=0&wdqb={{text:Simplified}}">MDBG</a>
			<a class="mobile-only" id="plecoMobile" href="plecoapi://x-callback-url/df?hw={{text:Simplified}}">Pleco</a>
			<a id="Tatoeba" href="https://tatoeba.org/en/sentences/search?from=cmn&query={{text:Simplified}}&to=">Tatoeba</a>
		</div>
	</footer>
</div>
```

and CSS:
```css
header, footer {margin: 2rem;}
.mobile:not(.ipad) :is(header, footer) {margin: 1rem;}
```
The previewer and actual card on ankidroid both look the same. 

This is how the header and footer should render and does on Mac:
<img width="533" alt="Screenshot 2024-08-05 at 12 11 59 AM" src="https://github.com/user-attachments/assets/40e33b48-af99-4ef1-b3cf-2374cd73cd2e">

**Comment by BrayanDSO** [comment]
> This bug also occurs on the iOS app on ipad

Given this fact and that the previewer renders the card the same way that the desktop version, I strongly believe that it is an issue with your card template.

The forums are a better place for that kind of issue, so I ask you to report it there.
