### ISSUE TITLE
Warn the user that media are resized.

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#16813]
I'd be happy to have opinion of other people.
Currently, when you paste an image, it get resized and converted to jpg.
It'd be nice to have a small snackbar telling the user the image was compressed to save space on the device.
Clearly, that was not my expectation. Especially since, I just tested, this is not the case (anymore) in anki.
In particular, during copy paste, I expect it be more useful than the snackbar telling us that the content of the pasteboard was used (which is the expectation given the paste action)

**Comment by BrayanDSO** [comment]
The warning would be useless after seeing it just once, and I believe that most people don't care about what is done when something is attached. I believe that most people don't even know the difference about a JPG and a PNG. 

Explaining the inner work of the app tends to make the app more complex, and the whole Anki ecosystem is already known for not being user-friendly, so I don't want to make it worse.

For the rare people that want to know that kind of detail, the manual would be a better place for that.

**Comment by Aditya13s** [comment]
@Arthur-Milchior I have a suggestion that we can show the size of the attached files.

**Comment by david-allison** [comment]
As-per Brayan, this doesn't feel like a good user experience, or something which we want to expose

The only time a user should care is if we've made a mistake, and the image on their card is not what they pasted.

We haven't had a complaint about this in maybe 3 years, so it doesn't seem necessary
