### ISSUE TITLE
En-EN a.k.a. en-gb is missing

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#16820]
Anki has an English (GB) translation. on crowdin, we have an en translation. Which I guess mean "England english"

It would be nice to offer this translation to the users.

I don't actually know how much difference there is. I find no way to do such a check in crowdin.
Once downloaded, a simple diff would show whether it's actually relevant to use it.

My problem is that:
* en crowdin it's "en"
* in ankidroid, "en" corresponds to the content on values/ and not to the content of value-en
* in anki, it's en-GB

And honestly, I'm not sure how to make all of this work together.

Once it's done, it'd be nice to update the wiki, so that we have a note that explain how to add a language, and how to ensure that we get both anki and ankidroid part of the translation, even when the abbreviation is not the same

**Comment by BrayanDSO** [comment]
IIRC, new languages are added when 01-core is fully translated. Idk where that it documented. If it isn't documented, the task would be to do it.

Besides that, I don't see why this issue should be kept opened. There are a lot of languages and variants that we don't offer support and having an issue for any of them isn't useful.

If someone wants en-GB, or any other localization, to be added, doing the standard procedure is enough

**Comment by Arthur-Milchior** [comment]
In the case of English(gb) specifically, I'm not sure that it makes sense to request 100% translation. When the string does not have to be changed, it's useless work to require it.

I realize I forgot to push https://github.com/ankidroid/Anki-Android/pull/16827 , where I tried to start this work.

I can't find the "standard procedure". And while I can figure out how to add most language by just looking as how any non English language is dealt with, I'm not sure it's exactly as trivial with en-gb. Because it's only "en" on crowdin, not "en-gb". That means that, not only does the abbreviation differs between ankidroid and anki, but also we must ensure that users that usually want "English" does not get the GB version.

So, for this one specifically, I thought an issue might make sense

**Comment by david-allison** [comment]
Why is it `en` on CrowdIn? That seems like an issue

English (UK) is available, but not selected

<img width="458" alt="Screenshot 2024-08-07 at 14 21 27" src="https://github.com/user-attachments/assets/b47a7771-8ffe-4495-815e-56b4669782d9">

**Comment by Arthur-Milchior** [comment]
I can't find an easy way to find history about why it was . And it's not even clear that all translators that actually spent time to do translation had the same goal in mind.

As far as I can tell, `en` is not the same as what we have in the `values` repo. People actually did translate it.

If we don't want to support en-gb, then we should at least close this, so translators don't spend more time on it. I'd be in favor of doing that unless, given that it's not even clear that the translation is consistent, unless we find someone who really want a UK version.

**Comment by david-allison** [comment]
I like the concept of `en`, from our activity log, it looks like it acts as a lightning rod for malicious contributions.

Would like to hear from @snowtimeglass about whether my hunch is correct

**Comment by snowtimeglass** [comment]
> it looks like it acts as a lightning rod for malicious contributions.

Maybe so, to some extent. Superficially, `en` doesn't seem to be conspicuously tampered with more than the other frequently tampered languages, but the acts could be dispersed into less-or-no tampered languages if `en` doesn't exist. 

That said, honestly I'm not sure. These results of the numbers may be interpreted either way.

**Comment by david-allison** [comment]
As stated: 

* https://github.com/ankidroid/Anki-Android/pull/16827

> ... if someone is willing to handle the code/CI side, I can spend half an hour verifying en-GB's 01-core

But otherwise, I'd vote to close, limited capacity on the dev side
