### ISSUE TITLE
[BUG]: Khmer language font displays bold on cards

### ISSUE THREAD

**Issue by jaredratcliff** [ankidroid/Anki-Android#16832]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

All Khmer characters on cards, regardless of card type, show bold characters. This **only happens on cards;** in the editor, or elsewhere in the app, Khmer characters appear normally. This issue appeared recently. 

![Screenshot_20240805-221619](https://github.com/user-attachments/assets/720ad22f-1927-4e53-bfd8-6012d89749a9)
![Screenshot_20240805-221614](https://github.com/user-attachments/assets/5e879531-ff80-42c3-816d-667e1aa06aa4)

### Expected behaviour

Khmer characters should appear normally on cards, like they do elsewhere in the app.

### Actual behaviour

Khmer characters appear bold on cards, almost artificially in a way that makes them difficult to read.

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 7

Hardware = panther

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 7 Build/AP2A.240705.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.64 Mobile Safari/537.36

ACRA UUID = 83341ee9-7e76-4a75-adf0-23dc725e39a6

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Likely related:

* https://github.com/ankidroid/Anki-Android/issues/15535
* https://github.com/ankidroid/Anki-Android/pull/15540
* https://github.com/ankidroid/Anki-Android/issues/15684

**Comment by david-allison** [comment]
Is this just with the Previewer, or also in the Reviewer?

**Comment by jaredratcliff** [comment]
> Is this just with the Previewer, or also in the Reviewer?

Also the reviewer. 
![Screenshot_20240807-052205](https://github.com/user-attachments/assets/c900e659-8e57-4300-848e-384b7e8c9a8c)

**Comment by david-allison** [comment]
Looks like a phone/card template problem. Screenshot: `ទឹកដោះគោ` on API 30

<img width="389" alt="Screenshot 2024-08-07 at 13 52 24" src="https://github.com/user-attachments/assets/c9796be7-8b58-4698-9352-d24b4f43029e">


Are you able to get the card working in `chrome://inspect`: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by brishtibheja** [comment]
Relevant: [forums.ankiweb.net](https://forums.ankiweb.net/t/khmer-text-is-bold/46422?u=sorata)

**Comment by david-allison** [comment]
Thanks!

Moved & resolved on Anki Forums

https://forums.ankiweb.net/t/khmer-text-is-bold/46422
