### ISSUE TITLE
[DEPRECATION]: Handle Kotlin context receivers 

### ISSUE THREAD

**Issue by criticalAY** [ankidroid/Anki-Android#16863]
Need to handle/ or remove the experimental API:
> Phased removal of context receivers feature﻿
In Kotlin 1.6.20, we introduced context receivers as an Experimental feature. After listening to community feedback, we've decided not to continue with it. Instead, we plan to introduce a replacement in future Kotlin releases: context parameters. You can find the proposal for context parameters in the KEEP.

### (Optional) Anything else you want to share?

https://kotlinlang.org/docs/whatsnew-eap.html#phased-removal-of-context-receivers-feature

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks!!

As stated when I proposed using Context receivers, I take full responsibility from removing them from the codebase if they don't pan out into stable

The replacement (Context Parameters) are very similar, but there won't be an overlap period. So we'll need to remove `context()` from our codebase, then add back in at a later time

> * **2.0.20**: A warning is introduced for declarations that use
> context receivers.
> The warning should mention that the design of context receivers
> is about to change, according to the new design (add a link to the KEEP/YT).
> The safest workaround is to migrate your code to extensions.
>  * **2.1.20**: The implementation of context receivers is removed from the compiler.
> Effectively, this warning is turned into an error.
> Note that this part is most likely inevitable as the implementation
> of context parameters requires  quite extensive refactoring in the compiler,
> and there are significant chances that we won't have either
> context receivers or context parameters at that time.
>  [There is a slight chance that we'll have an early prototype of context parameters,
> but we are not counting on that.]
> * **2.2.0**: Context parameters are introduced under a new compiler flag.

https://youtrack.jetbrains.com/issue/KT-67119/Migration-warning-from-context-receivers-to-context-parameters

----

I do feel that Context Parameters are a better solution, and it's not fair for JetBrains to handle a complex migration path for an experimental feature. 

I made the call to be on the bleeding edge of the language. This decision should have been deferred and would have resulted in less wasted effort
