### ISSUE TITLE
[BUG]: Voice Playback's Gesture Crashes App

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16873]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

* Enable voice playback's gesture. I set it to "Touch bottom right".
* Go to reviewer. Click on bottom right.
* Use the gesture once again.

### Expected behaviour

I thought this was a toggle option so it should toggle off. If not, nothing should happen.

### Actual behaviour

App crashes. It also happens with replay voice's gesture if no voice is recorded. App can also crash if you use the menu item and the gesture back to back (happened once).

### Debug info

```text
AnkiDroid Version = 2.19alpha10 (4afa7ec41ecc3efe7dd719db46c51cb09560292f)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.64 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@criticalAY FYI

**Comment by brishtibheja** [comment]
Also, why are we calling this Record and not Playback. It's confusing IMHO.
