### ISSUE TITLE
[BUG]: AnkiDroid 2.15, the latest Java version with dictionary support, is no longer built from source - Could not resolve all artifacts kotlinx-serialization-runtime-0.11.0.pom

### ISSUE THREAD

**Issue by mmmx123456777** [ankidroid/Anki-Android#16878]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Buid

### Expected behaviour

Buid successful

### Actual behaviour

Buid fail

### Debug info

```text
-
```

### (Optional) Anything else you want to share?

Hello, since version 2.16, rewritten in Kotlin, the developers have removed the ability to search dictionaries.
Previously, there was a choice of dictionary to use in the settings.
By copying a word and clicking anywhere on the card, a magnifying glass appeared in the upper right corner, clicking on which opened the dictionary.

Now only through Share, and selecting the app, which is not as convenient.

Questions:
1. Does anyone know why the developers removed this, and if they are going to bring this feature back?
2. Maybe they just didn't have time to move this feature?
3. Or maybe they implemented something else for dictionary searches?
So I use AnkiDroid version 2.15, the latest one with dictionary search capability.

In 2024, when building AnkiDroid 2.15, it started giving an error that it can't download:
kotlinx-serialization-runtime-0.11.0

When building gradle it gives the error:
A problem occurred configuring root project 'Anki-Android-2.15-current-1'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.11.0.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/org/jetbrains/kotlinx/kotlinx-serialization-runtime/0.11.0/kotlinx-serialization-runtime-0.11.0.pom
       - https://plugins.gradle.org/m2/org/jetbrains/kotlinx/kotlinx-serialization-runtime/0.11.0/kotlinx-serialization-runtime-0.11.0.pom
     Required by:
         project : > app.brant:amazonappstorepublisher:0.1.0
         project : > app.brant:amazonappstorepublisher:0.1.0 > com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter:0.4.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

You can read more about kotlinx serialization here:
https://github.com/Kotlin/kotlinx.serialization

There is no version for 0.11.0 in the repository:
https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-runtime/
[0.14.0/](https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-runtime/0.14.0/)                                           2019-11-26 11:02         -      
[0.20.0/](https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-runtime/0.20.0/)                                           2020-03-04 16:12         -      
[1.0-M1-1.4.0-rc/](https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-runtime/1.0-M1-1.4.0-rc/)                                  2020-07-30 18:05         -      

Library: org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.11.0, is a dependency for the plugin:
app.brant:amazonappstorepublisher:0.1.0

Judging from this link, this is his latest version:
https://plugins.gradle.org/plugin/app.brant.amazonappstorepublisher

I.e. these versions were somehow removed from the repository in 2004, although in 2023, gradle was building everything fine.
I tried to add a dependency to the build.gradle file: 
maven { url “https://kotlin.bintray.com/kotlinx” }
as follows:
buildscript {
    repositories {
        google()
        maven {
            url "https://plugins.gradle.org/m2/"
        }
        maven { url "https://kotlin.bintray.com/kotlinx" }
    }
But this repository task didn't help either, it gave a certificate error:
Certificate for <kotlin.bintray.com> doesn't match any of the subject alternative names: [*.jfrog.io, *.int.jfrog.io, jfrog.io, *.pe.jfrog.io]

I tried taking the library from the gradle cache on another computer: c:\Users\user1\.gradle\caches, where everything was built in 2023.
After that, I was able to build AnkiDroid 2.15

Question:
5. Is there any way to modify the dependencies so that I can build AnkiDroid 2.15?

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mmmx123456777** [comment]
On the forums they say that if you have problems with the latest version of AnkiDroid, you can always build the version you need from source.
Now this is not true, AnkiDroid 2.15, the latest Java version, is no longer buildable!

**Comment by voczi** [comment]
You can adopt these changes and it should build fine. https://github.com/ankidroid/Anki-Android/commit/8c352ec3de068ef8c42dfd343408afae234b9812

**Comment by BrayanDSO** [comment]
IIRC, the feature had a very very very small number of users and it had some kind of problem, so the team decided to remove it.

You can always download 2.15.6, or the latest alpha version that includes it.

About the building problems, the patch that voczi provided should work. If you got any other ones, try asking for help in the forums or in Discord.

I'm going to close the issue, since this isn't a problem that impact the current development of the app.
