### ISSUE TITLE
Regression in UI of Note Editor Previewer

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#16889]
Old UI (as in 2.19 alpha 10):
<img width=280 src="https://github.com/ankidroid/Anki-Android/assets/92206575/562548e0-7a69-43d4-ac4c-dd3447a7c74e">

New UI (as in 2.19 alpha 11):
<img width=280 src="https://github.com/user-attachments/assets/5e57a1e9-c912-4124-9820-083f4cf6b333">

In alpha 11, the `Card 1 Card 2` part is in its own line and is not colored.

(Disregard the padding changes within the card webview. They are due to changes in my card template.)

**Comment by david-allison** [comment]
@SanjaySargam FYI

**Comment by SanjaySargam** [comment]
That's because of https://github.com/ankidroid/Anki-Android/pull/16529/files#diff-759ea8a21a3cbadcd4b96369e8f90252e16765795d85a84ca5082261081ea035

**Comment by RobozinhoD** [comment]
I will send the fix
