### ISSUE TITLE
[BUG]: Set Due Date Unhides App Bars/Answer Buttons

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16883]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

* Go to **Settings > Controls** and set a gesture for **Set due date**. I used "Touch top right".
* Go to **Settings > Appearance > Fullscreen mode** and select "Hide system bars and answer buttons".
* Go to review screen.
* Use the set gesture.

### Expected behaviour

System bars and answer buttons are still hidden.

### Actual behaviour

They become partially visible.

### Debug info

```text
latest alpha
```

### (Optional) Anything else you want to share?

This is also true for the add tag control option. As a new window appears, fullscreen mode gets partially overriden.

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
I'll close this one to concentrate efforts in the new reviewer

**Comment by brishtibheja** [comment]
I hope new reviewer will solve this.
