### ISSUE TITLE
[BUG]: "Deck options > Don't play audio automatically" is not respected

### ISSUE THREAD

**Issue by horseDeveloper** [ankidroid/Anki-Android#16890]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

I have a card with multiple TTS buttons. On Anki desktop the setting behaves normally, but on AnkiDroid every single TTS instance is read.

### Expected behaviour

I only want to hear the TTS if I press a button.

### Actual behaviour

I have a card with multiple TTS buttons. On Anki desktop the setting behaves normally, but on AnkiDroid every single TTS instance is read.

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A146P

Hardware = mt6833

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-A146P Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = 1a9c86e9-dab0-43c2-8a79-37548458f924

FSRS Enabled = false

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by soCallmeAdityaKumar** [comment]
working on it!!

**Comment by BrayanDSO** [comment]
Do you have some kind of sample/deck to share so we can reproduce this?

**Comment by soCallmeAdityaKumar** [comment]
> Do you have some kind of sample/deck to share so we can reproduce this?

i reproduced using this
https://ankiweb.net/shared/info/1878034191
