### ISSUE TITLE
[Enhancement] Custom study: support both intersection and union of tags

### ISSUE THREAD

**Issue by emesterhazy** [ankidroid/Anki-Android#16908]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Custom study > Limit to particular tags

Select several tags. The custom study will include all of the cards which have any of the tags, but there is no way to limit it to cards which have all of the selected tags.

### Expected behaviour

There should be a way to limit the session to cards which have all of the selected tags (set intersection / AND condition).

### Actual behaviour

The session will contain cards which have any of the selected tags (set union / OR condition).

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 6 Pro

Hardware = raven

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 6 Pro Build/AP2A.240905.002.F1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.40 Mobile Safari/537.36

ACRA UUID = 802bc67a-9efc-4be5-b885-a9242333d069

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks! Feature requests have now been moved to the Anki Forums, please post there https://forums.ankiweb.net/c/ankidroid/suggestions/23

**Comment by emesterhazy** [comment]
Moved to https://forums.ankiweb.net/t/ankidroid-custom-study-support-both-intersection-and-union-of-tags/48466
