### ISSUE TITLE
[BUG]: Checkmark Icon Disappears After Selecting IO Notetype

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16903]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

* Select a deck.
* Click `＋` to go to the add screen.
* Change to IO notetype.
* Back and go to add screen again.

### Expected behaviour

Save/checkmark icon appears.

### Actual behaviour

Save has disappeared.

### Debug info

```text
AnkiDroid Version = 2.19alpha10 (4afa7ec41ecc3efe7dd719db46c51cb09560292f)

Backend Version = 0.1.39-anki24.06.2 (24.06.2 9b4dd54312de8798a3f2bee07892bb3a488d1f9b)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hey @brishtibheja 👋 
Looks like @MorenoTropical has just hit the "that was easy" button and has a PR for this that appears good to me. If a second reviewer agrees, it'll be in whatever the next alpha is after that (or beta as we're about to start 2.19beta)
Cheers

![image](https://github.com/user-attachments/assets/7fb263f2-3329-4936-8503-3b5404c9b5b6)
