### ISSUE TITLE
[BUG]: Can't use deck

### ISSUE THREAD

**Issue by Forseta** [ankidroid/Anki-Android#16924]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

I downloaded Ankidroid and synced it with my AnkiWeb account which has only one deck, the  Core 2k/6k Optimized Japanese deck.

### Expected behaviour

I expected that when I opened the deck, it would carry me to the screen where I could choose  to begin studying the flashcards

### Actual behaviour

Instead, the screen was just blank, nothing appeared 
![Screenshot_20240821-142141](https://github.com/user-attachments/assets/31401613-0df1-4385-98fc-9218b0c9fa40)

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 6.0.1 (SDK 23)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G532M

Hardware = mt6735

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0.1; SM-G532M Build/MMB29T; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/55.0.2883.91 Mobile Safari/537.36

ACRA UUID = 601d1b0c-3eff-47ea-bc1d-91fb7934dea8

FSRS Enabled = false

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

I have only used the deck twice, on the laptop Anki app, if that matters. I've search everywhere for a solution to the issue but nothing seems to work. Also, the cards appear blank when I preview them in the "Browse Cards" option, the deck options also appear blank.
![Screenshot_20240821-142129](https://github.com/user-attachments/assets/a316a6e9-720a-4ce7-9d73-da6356b79439)

![Screenshot_20240821-142100](https://github.com/user-attachments/assets/819a8970-5c9e-407a-b7e7-553302d401d4)

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
The webview on your system is too old. Here's a [guide](https://github.com/ankidroid/Anki-Android/wiki/WebView-Detection-and-Package-Updates) for how to update it.

Try asking for help in Discord or in the forums if necessary
