### ISSUE TITLE
[BUG] Key Labels Not Displaying in Landscape Mode

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16935]
* Go to **Settings > Controls**.
* Assign a key to any action (in landscape mode).

The key shows up when you press one in portrait mode, but not when in landscape mode.

I'm using latest alpha on a normal sized device (not large screen).

**Comment by Prince-kushwaha** [comment]
hi @mikehardy , i able to reproduce this issue , can i work on this issue

**Comment by Arthur-Milchior** [comment]
@Prince-kushwaha You don't need to ask. Just let us know when you start to work on something, so that nobody else starts to work at the same time on it
