### ISSUE TITLE
Remove "discard current input" when no change is made since last added card

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#16949]
How to reproduce:
* have a note type with a pinned field
* enter text in the field
* create the note
* try to leave the note editor

Expected:
* closing the note editor

Actual:
* A prompt "Discard current input"

I think that if the user made no change, we should just allow them to close the editor. Same as on anki desktop.
We could either listen to any change in text and record there was a change. Or record the state of the fields when the new "add note" was offered to the user and check whether we still have the same content. This way, if the user type by accident in the first field and then delete it, we know that it's okay for the user to save actually.

This is not the same bug as #15788, given that, in the current case, no prompt at all should appear

**Comment by BrayanDSO** [comment]
Although I agree with the request, I'm adding `Priority-Low` because the note editor will eventually be replaced with a Svelte screen
