### ISSUE TITLE
[BUG]: syncing problem on Android 

### ISSUE THREAD

**Issue by Lima-ctrl** [ankidroid/Anki-Android#16957]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

When i press to sync, it just doesn't. 
I already tried to change my Wifi network and even tried to sync with 5G, but it doesn't solve the problem.

The message in the picture is in portuguese, but translating it to English means: " **Error**  The network is expired. Try again with another network".

![Screenshot_20240825_172008_AnkiDroid](https://github.com/user-attachments/assets/ecb420df-4d1d-4483-9c6b-a04ff434cc46)

### Expected behaviour

It should've synced.

### Actual behaviour

It doesn't sync.

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-S926B

Hardware = s5e9945

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-S926B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = 1814a1ce-9402-4700-a4be-c65a0c9ed571

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [x] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by brishtibheja** [comment]
There have been [recent reports from Brazil](https://forums.ankiweb.net/t/syncing-not-working-since-08-19-24/48478/7?u=sorata) about sync issues. If you're from Brazil, try using a proxy or a VPN. This should solve your issue. If it persists, please report it on the forums: [forums.ankiweb.net](https://forums.ankiweb.net/)
