### ISSUE TITLE
[BUG]: Cannot Return to Edit/Add Screen from Template Editor

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16955]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

* Go to Edit screen/Add screen.
* Click **Cards** to open Card Template Editor.
* Try to go back to the previous screen.

### Expected behaviour

Edit/Add screen reopens.

### Actual behaviour

Cannot return to the previous screen. I'm able to use the **← Navigate up** button. Gestures and keyboard presses are not working.

### Debug info

```text
AnkiDroid Version = 2.19alpha12 (f720ae030b8920c73f957d64d7044e95242f7719)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
Can reproduce in beta 1 too.

The Android back button doesn't work, though the ← button at the top left works.

**Comment by david-allison** [comment]
@SanjaySargam FYI

**Comment by SanjaySargam** [comment]
working on it

**Comment by SanjaySargam** [comment]
introduced this bug due to https://github.com/ankidroid/Anki-Android/commit/87e2a79b676c6309496317141340d6db52e82fa5
