### ISSUE TITLE
[BUG]: Long Press Menu Doesn't Open

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16962]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

* Go to **Manage note types**.
* Click on a note.
* Long press on any field.

### Expected behaviour

The menu opens up on it's own.

### Actual behaviour

The ripple is freezed and the menu won't open until I release my finger.

### Debug info

```text
2.19alpha12
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Not a bug, just a mismatch of expecatives. That UI is designed for single taps, while you apparently expected them to work with long taps.

If you want some kind of different behavior like a tooltip or opening the buttons, please make a feature request in the forums.
