### ISSUE TITLE
[BUG]: Type-in fields don't work with the new reviewer

### ISSUE THREAD

**Issue by Expertium** [ankidroid/Anki-Android#16973]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

1) Download AnkiDroid 2.19 alpha 11 (arm64 v8a)
2) Enable New reviewer in Settings -> Developer options

### Expected behaviour

It works fine with New reviewer disabled.

### Actual behaviour

![Screenshot_20240827-161629_AnkiDroid](https://github.com/user-attachments/assets/ec4c35f9-8dc0-4681-a7ce-44c3b995e674)
![Screenshot_20240827-161230_AnkiDroid](https://github.com/user-attachments/assets/10e8a219-4f87-4c42-a4bb-7cda643c74b8)

### Debug info

```text
AnkiDroid Version = 2.19beta1 (6630ff411d643bf03206e106c4d940dc7076e738)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 10 (SDK 29)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G965F

Hardware = samsungexynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-G965F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = e07c5f58-e252-4d14-9a9c-c440ec0e1358

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by brishtibheja** [comment]
I mean it's developer option for a reason.

**Comment by BrayanDSO** [comment]
> I mean it's developer option for a reason.

I couldn't say it better. It's a WIP feature, not intended for general use.
