### ISSUE TITLE
Proposal: improve the 'Translation Sync' message

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#16980]
**Before**

Message to maintainers, this PR contains strings changes. 
1. Before merging this PR, it is best to run the "Sync Translations" GitHub action, then make and merge a PR from the i18n_sync branch to get translations cleaned out.
2. Then merge this PR, and immediately do another translation PR so the huge change made by this PR's key changes are all by themselves.
    
Read more about updating strings on the wiki,
- [localization-administration](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#localization-administration)
- [download-localized-strings](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#download-localized-strings)

----

**After**

> [!IMPORTANT]
> **Maintainers**: This PR contains https://github.com/ankidroid/Anki-Android/labels/Strings changes

1. [Sync Translations](https://github.com/ankidroid/Anki-Android/actions/workflows/sync_translations.yml) before merging this PR and wait for the action to complete
2. Find the [auto-generated PR](https://github.com/ankidroid/Anki-Android/pulls/app%2Fgithub-actions) and open and close the PR to perform a lint check. Review and merge the PR to sync all user-submitted translations
3. Merge this PR
4. [Sync Translations again](https://github.com/ankidroid/Anki-Android/actions/workflows/sync_translations.yml) and merge the [PR](https://github.com/ankidroid/Anki-Android/pulls/app%2Fgithub-actions) so the huge automated string changes caused by merging this PR are by themselves and easy to review

**Comment by david-allison** [comment]
I'm proposing this as:

* The previous message was missed, therefore probably isn't prominent enough
* The process has been updated and the message is no longer up to date

----

Location: 

https://github.com/ankidroid/Anki-Android/blob/701b5582de43fa0742ddf8964034ed5bce82c274/.github/workflows/label.yml#L128-L140

**Comment by BrayanDSO** [comment]
> Read more about updating strings on the wiki,
>
>    [localization-administration](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#localization-administration)
 >   [download-localized-strings](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#download-localized-strings)

Can this part be condensed into a single line?

I like the changes, but now the whole message takes a considerable amount of vertical space

**Comment by lukstbit** [comment]
Looks fine, but I don't see the purpose of the last line:

_Read more about updating strings on the [wiki](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#localization-administration)_

if the message targets us maintainers.
