### ISSUE TITLE
"Save your collection" warning can be displayed during first sync

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#16989]
![Screenshot 2024-08-28 17 12 18](https://github.com/user-attachments/assets/1e783362-e9fe-4681-b17b-cee56103f50d)
This should not occur. When the sync is going on, you should not be invited to sync.

I think this occured because I installed and opened AnkiDroid, but I had not selected whether to sync from ankiweb or do a fresh start. When I re-opened ankidroid to actually start using it and sync from ankiweb, ankidroid thought that it has been some time since last sync and I should get warned.

I'm not sure what the best correction is.
I think we should not invite to save our collection as long as the collection is empty. This is useless and potentially confusing.

Also, we should ensure that any sync would make this view disappear.

**Comment by BrayanDSO** [comment]
this is probably an extension of #16989, and any fix will involve both issues, so I'll join them

**Comment by Arthur-Milchior** [comment]
Sorry @BrayanDSO , but I think you used a wrong issue number. Because you're linking to the current issue.
