### ISSUE TITLE
Holding Down a Key Should be Considered a Single-click

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#16988]
* Go to **Settings > Controls** and assign <kbd>Space</kbd> to "Answer good".
* Go to reviewer and hold down <kbd>Space</kbd>.

As you can accidentally long press, this is considered a single click in desktop. In AnkiDroid, you'll end up answering multiple cards if you hold a key longer than an instant.

**Comment by BrayanDSO** [comment]
Not a bug. Since this is a feature request, please do it in the forums.

**Comment by brishtibheja** [comment]
@BrayanDSO The behaviour is inconsistent. For example, the DPad buttons work differently and a press and hold is only considered single click.

**Comment by brishtibheja** [comment]
Another example, press and hold <kbd>Ctrl</kbd>+any other key and it's considered a single click. Doesn't happen when <kbd>Shift</kbd> is used with any other key.
