### ISSUE TITLE
Card template editor has no menu on tablet

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#16992]
On the top right of  
![image](https://github.com/user-attachments/assets/52dae2a8-3991-44b0-98a5-8a93908864d1) there should be a menu.

According to @SanjaySargam , it was introduced in #16891, do you think you could fix it please @RobozinhoD ?
It does not seems to be merged in 2.18 so there is no emergency as far as I can tell

**Comment by BrayanDSO** [comment]
I'm sorry, but having two menus doesn't make sense to me.

If you are editing `Card 2`, you want to preview the changes in `Card 2`. Even previously to that PR, if I edit `Card 1` while `Card 2` is being previewed, it is automatically switched to `Card 1. And if someone wants to preview another template, they can select it in the first menu. Given that, the second menu doesn't have any actual purpose.

**Comment by Arthur-Milchior** [comment]
I'm very sorry @BrayanDSO , but I don't understand what you mean by "having two menus". 
My issue is that right now there are zero menus

**Comment by BrayanDSO** [comment]
I'm sorry, I misinterpreted you and thought that were talking about the missing tab layouts.

**Comment by RobozinhoD** [comment]
I can do that

**Comment by SanjaySargam** [comment]
@RobozinhoD Sure, go ahead!
