### ISSUE TITLE
[BUG]: The layout of the Axis Picker screen is not displaying correctly in landscape mode

### ISSUE THREAD

**Issue by Prince-kushwaha** [ankidroid/Anki-Android#17026]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Settings->control->user action 1-> Add joystick/motion controller

On Portrait mode
![WhatsApp Image 2024-09-05 at 8 19 27 PM](https://github.com/user-attachments/assets/33e73389-d93f-42a4-baae-99909d87c280)

On Landscape
![WhatsApp Image 2024-09-05 at 8 19 09 PM](https://github.com/user-attachments/assets/0611b048-2a72-4a5a-a5b6-913a451dd661)

### Expected behaviour

The layout of the Axis Picker screen displaying correctly in landscape mode

### Debug info

```text
android version 10
```

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
can i work on this issue

**Comment by BrayanDSO** [comment]
> can i work on this issue

Try finishing your open PRs first before asking to be assigned to more of them.

**Comment by gautamsingh2** [comment]
@BrayanDSO  I would like to work on this issue. Could you please assign it to me?
