### ISSUE TITLE
Hiding system bar bug

### ISSUE THREAD

**Issue by Licorioo** [ankidroid/Anki-Android#17034]
What about this bug?

              Maintainers Note : **Reproduced**

This does needs to be addressed. In both screenshot there seems to be some kind of hiding system bar bug here as system bar should have been in blue color for light mode but its showing in black in image below.

| Image 1 | Image 2 |
|--------|--------|
| ![screenshot](https://github.com/ankidroid/Anki-Android/assets/60827173/425efed2-7560-4652-a2ba-910458a23b9a) | ![screenshot](https://github.com/ankidroid/Anki-Android/assets/60827173/7147eca4-252c-4ba9-85a2-2976eabd48cc) |

Also do you @CyberButton wish to take on this issue?

_Originally posted by @neeldoshii in https://github.com/ankidroid/Anki-Android/issues/15762#issuecomment-2039351650_

**Comment by BrayanDSO** [comment]
Reopened the original issue. Please ping a maintainer if something like that happens again
