### ISSUE TITLE
Remove image import arbitrary limit of 1MB

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#17030]
- Anki doesn't have it.
- AnkiMobile doesn't have it.
- Cropping or compressing an image loses the image format, transparency and animation, and JPEG isn't the best lossy format out there
- The dialog is annoying to anyone that want to keep their files as is
- If you want a feature with the goal of reducing the media space, it should be applied to all files, not only the ones over 1MB, so the current approach doesn't make much sense
- It isn't user-friendly. A lot of people, specially non-technical people, won't get the dialog and enter the rant of "why anki is so complex??", "I can't even add an image without a techy dialog". Some may actually be compelled to crop/compress just because it says `The Default is X`

**Comment by lukstbit** [comment]
Yes, a limit of 1MB is silly. As you can only pass about 1 MB of data through a Bundle, I'm wondering if this isn't the reason why this value was used?(Not that images should be passed around through bundles anyway)

**Comment by criticalAY** [comment]
I had removed it originally in the new code but when I was removing the old code saw the limit so placed it, can remove it if there is no solid reason behind it

**Comment by mikehardy** [comment]
@lukstbit hello from 2019 and 2020 😆 

The PR that implemented "over 1 megabyte, you want to crop the thing?" #6543
The issue requesting the feature #562 

Somehow that morphed over time in to a hard limit, but it was just a feature for people that wanted it
