### ISSUE TITLE
[BUG]: Need to improve the  options  of statistics layout

### ISSUE THREAD

**Issue by Prince-kushwaha** [ankidroid/Anki-Android#17037]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Options text is overlapping
2. need to improve the options alignments

![WhatsApp Image 2024-09-08 at 9 21 58 AM](https://github.com/user-attachments/assets/4a0c0b8e-09d6-4a3b-be30-292bccabb237)

### Expected behaviour

improve options alignment

### Debug info

```text
android version 11
```

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by user1823** [comment]
You can suggest this in the Forums as this page comes from Anki backend.

A similar old post:
https://forums.ankiweb.net/t/duplicate-last-12-months-and-all-history-options-in-stats/33425

**Comment by Prince-kushwaha** [comment]
@user1823 , thanks i give that suggestion on anki backend
