### ISSUE TITLE
Deck picker "enter" key should not create the deck when the "ok" button is disabled

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#17044]
This is a follow-up to #16690 fixed by #16704 by @MinusMallard .

How to reproduce:
* open the deck picker
* create a deck A
* open "add deck"
* type name "A"
* press enter

Actual result:
* the view close, the snackbar tells the deck is created. No deck is created.

Expected result:
* A snackbar telling that the name already exists
* the dialog remain open

**Comment by MinusMallard** [comment]
@Arthur-Milchior  I will look into this but I cannot say for sure my top priority is my university exams 😢

**Comment by Arthur-Milchior** [comment]
Thank you very much @MinusMallard.
And take your time. This is a relatively small bug. When "ok" is disabled, it means either the text is empty or a deck with this name already exists. (Or that it ends with "::" maybe. I'm not sure) In both case, the back-end can handle it.

**Comment by lukstbit** [comment]
@MinusMallard Please make a PR to see the code.

**Comment by MinusMallard** [comment]
@Giyutomioka-SS  hey thanks your implementation looks better to me however if you can make Toast appear at the bottom of screen it would be better because it's currently blocking the cancel button. Thanks again!!

**Comment by Giyutomioka-SS** [comment]
@MinusMallard, firstly, sorry I didn’t see your messages from yesterday before making a PR. & Regarding the Snackbar, if you check the attached recording, it is shown when the keyboard is on, so the Snackbar should be displayed above the keyboard. However, when I try to do that, it goes under the dialog and is not visible.

**Comment by MinusMallard** [comment]
@Giyutomioka-SS I see, but even though showing a Snackbar is most logical thing to do I think since text dialog is itself showing the message in red so snackbar is king of redundant and just disbaling the imeKeyboard "done" and physical "enter" is sufficient.

**Comment by Giyutomioka-SS** [comment]
@MinusMallard, yeah, I thought about it too, but then I just followed what was stated as the expected result in the issue description. @Arthur-Milchior @lukstbit, your views on this?

**Comment by Arthur-Milchior** [comment]
Personally, I prefer the snackbar. When the user does an action, it seems nice to acknowledge in the UI that they did something, or at least tried to do it. 

Users may have missed the error message. And not know why their "enter" key press is ignored.

Admittedly, they should be able to see the message quickly, there is not a lot of content on the screen.
Still, I expect it's a nice touch. I appreciate it.


Also, it does not require a new string, so it's not like we have to ask 90 people to translate something!
