### ISSUE TITLE
É difícil apagar uma Tag pelo celular. 

### ISSUE THREAD

**Issue by Roger1410** [ankidroid/Anki-Android#17065]
Eu mesmo não consegui encontrar a opção, nem sei se tem ela. Se dá para remover a Tag eu não consegui, ainda e poderia ser mais simples de remover.

**Comment by brishtibheja** [comment]
If you're wanting to remove tags from notes you can already do that from the browser/edit screen.

**Comment by david-allison** [comment]
You can delete unused tags with "Check Database"
