### ISSUE TITLE
[solved]: parallel installation sync error "Anki already open"

### ISSUE THREAD

**Issue by honis56** [ankidroid/Anki-Android#17067]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Three parallel installations of AnkiDroid, AnkiDroid.A and AnkiDroid.B were running fine on Android 10 smartphone.Then I moved to a newer Android 14 smartphone (New installations from github).
Two installations (AnkiDroid and AnkiDroid.A) are running fine, but AnkiDroid.B generates an error "Anki already open or media currently syncing", which is not true.
I opened a new account in Ankiweb. After syncing the  data from old account to new account via Anki-Computer, shut of all connections and tried to sync a freshly installed AnkiDroid.C. Result: Same error.

### Expected behaviour

Syncing AnkiDroid.C (on Android 14 smartphone) with the brandnew account should run properly.

### Debug info

```text
AnkiDroid 2.16alpha98
```

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there!

> AnkiDroid 2.16alpha98

Strange choice of version - we don't typically spend much time on old versions as it is inefficient vs focusing on current+future versions - can you try installing the latest release? https://github.com/ankidroid/Anki-Android/releases/tag/v2.18.4

**Comment by honis56** [comment]
Hi Mike!

Thank you for answering!

You are right. I am sorry. After several attempts of deleting and reinstalling the newest version, it finally works. Problem solved.

Best regards

**Comment by mikehardy** [comment]
Really happy to hear that :-)
