### ISSUE TITLE
Alter statistics deck switcher search form programmatic usage to match "statisticsSearchText" element id vs "first text box"

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#17075]
Examine how the statistics deck switcher uses the upstream Svelte form to programmatically switch decks
Note that if upstream moves the element around, it will break since we match "first text box" instead of something unambiguous

Previously the text box had no id so there was no unambiguous way to match it, but a change was recently merged that gives it the id "statisticsSearchText" and we should alter code here to use that id

This will remain "blocked by dependency" until Anki-Android-Backend is updated with whatever the first release of anki upstream is that contains this commit:

https://github.com/ankitects/anki/commit/1b7123aa9456b877a87b0b051ed7306bb0400c87

...once we have the backend updated to use a version of anki with the text box id and we have adopted it here, this is good to go.

It is marked as a "good first issue" because it really should be - **however** it will be blocked for a while and you'll need to check if it is unblocked before even attempting to work on it. So be careful with that check before spending any time, thanks

**Comment by Aditya13s** [comment]
I will work on it when it gets unblocked.
