### ISSUE TITLE
compare_apk_size.yml is broken

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#17109]
The size check failed on https://github.com/ankidroid/Anki-Android/actions/runs/10981548896/job/30488712178 (ankidroid's main) and on a branch of mine https://github.com/Arthur-Milchior/Anki-Android/actions/runs/10981505951

Seems the error are different some how. In ankidroid's main it's
> bash: line 1: ./gradlew: No such file or directory
> Error: Final attempt failed. Child_process exited with error code 127

In my branch it's

> 
> > startup failed:
>   General error during semantic analysis: Unsupported class file major version 65
>   
>   java.lang.IllegalArgumentException: Unsupported class file major version 65
>   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:196)
>   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:177)
>   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:163)
>   	at groovyjarjarasm.asm.ClassReader.<init>(ClassReader.java:284)

I need to run this to satisfy @david-allison request in #17107 (I expect there would not be any change in apk size, but David is right it's better to check)

**Comment by mikehardy** [comment]
I believe this is user error, to run the action correctly:

1- just hit "Actions" at the top of the ankidroid repo
2- select the APK size comparison
3- choose to manually run it
4- specify your PR number in the input box
5- hit go and wait, a comment will pop out on the PR with the old vs new size

Of course this could be better, I have an issue open where I described the design and some technical detail that is feasible to meet the design where this could run every time a PR is built as part of the emulator workflow *without really increasing build times anywhere*

But I haven't had time to do that yet, I will some day, Open Collective is nearly caught up...
