### ISSUE TITLE
 [BUG]: The "Set Due Date" dialog box is missing its title

### ISSUE THREAD

**Issue by gautamsingh2** [ankidroid/Anki-Android#17124]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

settings-> controls->set due date 

![screenshot2](https://github.com/user-attachments/assets/98d19709-4803-4e17-9193-d587894928a7)

settings-> appearance->app bar button-> set due date
![WhatsApp Image 2024-09-26 at 4 40 43 PM](https://github.com/user-attachments/assets/d0c41621-2221-4abd-8214-e731d816040b)

### Expected behaviour

add missing  title

### Debug info

```text
debug
```

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by gautamsingh2** [comment]
looking into it

**Comment by brishtibheja** [comment]
Also applies to **Settings > App bar buttons > Set due date**.

Might be related: https://github.com/ankidroid/Anki-Android/issues/16603
