### ISSUE TITLE
Little need to keep `empty_card_warning` string?

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#17132]
The following string of `empty_card_warning` has already been replaced (with another string reused from the desktop version) at least in some situation in the app as the following images.

`This card is empty. Use the “Empty cards” option from the menu on the deck list screen.`

![image](https://github.com/user-attachments/assets/ef2017e6-3ac5-474a-a888-f7e6a64d35c4)

https://crowdin.com/editor/ankidroid/7291/en-eo?view=comfortable&filter=basic&value=0#6534296

![image](https://github.com/user-attachments/assets/1dab2760-7bad-4778-b588-22904e10e13e)

However, the string still exists in the current code:

https://github.com/search?q=repo%3Aankidroid%2FAnki-Android%20empty_card_warning&type=code

https://github.com/ankidroid/Anki-Android/blob/b1f6583cb306201d4cc18c5902545f9d8ec7464b/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/TypeAnswer.kt#L62-L132

I'm wondering about whether or not there still are situations where the message actually appears in the app. Additionally, even if it still is used, I suspect it would be better to replace it with the string reused from the desktop version, as in the case in the images above.

### (Optional) Anything else you want to share?
For context: https://discord.com/channels/368267295601983490/701922522836369498/1288172228369973358

**Comment by Giyutomioka-SS** [comment]
Looking into this.

**Comment by snowtimeglass** [comment]
After considering whether there is a need to keep that string or not, the string could possibly be removed (replaced with the desktop string above).

**Comment by david-allison** [comment]
It doesn't need to be used. Issue accepted and can be worked on
