### ISSUE TITLE
[BUG]: The layout of the Gesture Picker screen is not rendering properly when viewed in landscape mode.

### ISSUE THREAD

**Issue by Prince-kushwaha** [ankidroid/Anki-Android#17158]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

settings-> controls-> User Actions 1-> Add Gesture
![WhatsApp Image 2024-09-29 at 9 40 20 AM](https://github.com/user-attachments/assets/b0d469ed-f690-4023-bd38-7558adab336b)

### Expected behaviour

layout  rendered correctly in landscope mode

### Debug info

```text
Android version Sdk(30)
```

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
working on the issue

**Comment by Prince-kushwaha** [comment]
@RobozinhoD, I find your behavior concerning. I was already working on this issue, as mentioned in the comments, yet you started working on it without consulting me and created a pull request. I have noticed similar actions from you on other issues as well.  respect others' efforts and communicate before taking over tasks

**Comment by Prince-kushwaha** [comment]
I have worked on this issue and fixed it. Now how I can create a pull request now?

**Comment by Prince-kushwaha** [comment]
@mikehardy @Arthur-Milchior @david-allison @lukstbit, what should be the next step here? I suggest we consider marking @RobozinhoD's pull request as invalid

**Comment by mikehardy** [comment]
Discussing it on discord to see what others think, but this does seem to be a somewhat-rare-for-us case where you had clearly communicated your intention to work on it, and there was no further communication, so the PR from @RobozinhoD is a bit unexpected

@Prince-kushwaha - based on the PR contents (+2 lines / -3 lines - it is *tiny*, nearly trivial) it may seem that creating an issue and waiting 4 days is a bit silly and you could just post a PR immediately after discovering it, and I would be sympathetic to that. It's a lot of noise for not a lot of functionality here.

But in the absence of communication @RobozinhoD this does seem a bit un-collaborative. @Prince-kushwaha, post what your code change.

**Comment by RobozinhoD** [comment]
I'm sorry, I just wanted to help. I was the author of #15729, so this bug is my fault so I tried to fix it.

I can close this if you want.

**Comment by mikehardy** [comment]
I can understand that @RobozinhoD - I do feel a sense of duty when I know something's my original error. Just drop a note first in the future :-)

@Prince-kushwaha - as mentioned, post what you have or please explicitly tell us to let this one go and we'll merge the one already posted. The PR is apparently quite small so I don't expect a lot more back and forth on this, I want to merge one or the other and move on

Thanks

**Comment by Arthur-Milchior** [comment]
Please @Prince-kushwaha don't ping so many people. There is probably no need for that many reviewers to look at the issue and to be notified. Hopefully, you know by now that reviewers eventually goes over all open message. And if you want quick answer, the best solution is to just post a message on discord so anyone online can answer.
I admit I prefer my notifications to be on something I must look at, in particular issues I already spent time on and where I've got context.
