### ISSUE TITLE
[BUG]: Endless Processing popup when wi-fi is lost

### ISSUE THREAD

**Issue by Fabiensk** [ankidroid/Anki-Android#17162]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

* Connect to Internet with Wi-Fi (ex: from home) with your phone
* Synchronize the deck in Ankidroid
* Leave to a place where the Wi-Fi hotspot is not reachable
* Let the Wi-Fi enabled on the phone
* Start reviewing
* An endless and unclosable "Processing…" ("Traitement…" in French) popup is displayed
* Even after stopping/killing Ankidroid, disabling Wi-Fi and re-opening Ankidroid, it is not possible to review because of this popup

NB: automatic sync is disabled

Only solution:
* Get Internet access from the phone.
* The popup automatically closes.
* Review one card.
* Disable Wi-Fi
* Continue the review
*

### Expected behaviour

* The review should not be blocked forever if Internet access is not available
* If Ankidroid is restarted and Wi-Fi / mobile connection is disabled, there should be no "Processing" popup related to Internet access.

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 6.0.1 (SDK 23)

ProductFlavor = full

Manufacturer = samsung

Model = SM-G800F

Hardware = universal3470

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0.1; SM-G800F Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36

ACRA UUID = fdc3f1d6-99ed-497b-8fc9-085f6e22442f

FSRS Enabled = true

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

It happens frequently when I use Ankidroid on an old phone that do not have any SIM card when I go running. I synchronize before leaving home, then if I forget to disable the Wi-Fi before leaving, then when I'm outside the only way to review is to:
* use my main (larger) phone as a Wi-Fi hotspot
* connect my old phone to it.
* review a card
* disable the Wi-Fi

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
That sounds serious! Could I ask you to try our latest beta to see if that's still happening? You can use a parallel build to keep things separate: https://github.com/ankidroid/Anki-Android/releases

**Comment by Fabiensk** [comment]
Thank you to both of you.
I did not test it yet. I'll do it in the next days.

**Comment by BrayanDSO** [comment]
I feel that's an issue of how your phone detects that you have an internet connection or not. We don't do anything fancy there. We just start the sync and if there isn't internet connection, it will fail.

Also, your device is a bit old and a lot of things have improved in that matter in newer Android versions, I'm afraid there's nothing that we can do to help you.

**Comment by Fabiensk** [comment]
Thank you for your answer. I tried 2 betas:
* 2.19beta3 : I did not have this issue (I could start reviewing), but some very strange behaviour: cards behind reviewed without me touching anything (several times, while the latest stable release worked as usual in the same condition once I used the shared wi-fi trick)
* 2.19beta5 : this one just stops just after being started.

That's a bit sad. My phone is old, but it has an useful use as a small ankidroid machine. I guess I'll have to live with it, and that spending time investigating for such a infrequent case.

**Comment by david-allison** [comment]
@Fabiensk what model is your phone? 

Are you technical (could you connect your phone via USB/WiFi and run logcat on a PC)

We'll block the release if it no longer works for you

**Comment by mikehardy** [comment]
Getting a copy/paste of the debug info would be useful if possible (it contains not more hardware/software version information and is all at once -> start at opening the side menu from top left button -> settings -> scroll down to "about" -> "copy debug info", then you can paste that in here perhaps?)

**Comment by Fabiensk** [comment]
> [@Fabiensk](https://github.com/Fabiensk) what model is your phone?

It's a Samsung Galaxy S5 mini (from 2014), running 6.0.1.
 
> Are you technical (could you connect your phone via USB/WiFi and run logcat on a PC)

I can, but I don't have the time for the moment.

> We'll block the release if it no longer works for you

Thanks, but I think I can live with the current version (I probably won't have the time before next weekend) and not block all the other users.

> Getting a copy/paste of the debug info would be useful if possible (it contains not more hardware/software version information and is all at once -> start at opening the side menu from top left button -> settings -> scroll down to "about" -> "copy debug info", then you can paste that in here perhaps?)

```
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)
Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)
Android Version = 6.0.1 (SDK 23)
ProductFlavor = full
Manufacturer = samsung
Model = SM-G800F
Hardware = universal3470
Webview User Agent = Mozilla/5.0 (Linux; Android 6.0.1; SM-G800F Build/MMB29K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/106.0.5249.126 Mobile Safari/537.36
ACRA UUID = fdc3f1d6-99ed-497b-8fc9-085f6e22442f
FSRS Enabled = true
Crash Reports Enabled = true
```

**Comment by david-allison** [comment]
Very likely the following bug, which we'll get fixed in the next beta

* https://github.com/ankidroid/Anki-Android/issues/17256

**Comment by Fabiensk** [comment]
I tried 2.19beta6 twice, and the bug was not present (though I have issues with gestures, but I need more time to search for an existing ticket or test more).

**Comment by david-allison** [comment]
Great, thanks! 

We're pretty close to 2.19 going out, so the bug report would be much appreciated!!

**Comment by Fabiensk** [comment]
In fact I don’t have any issue any more. Regarding the gestures, I configured them for taping instead of sliding in a given direction (which I wanted). Now that I got that, everything seems to work like before.

**Comment by mikehardy** [comment]
Fantastic news! Thank you so much for testing + reporting, glad it looks like everything is working for you
