### ISSUE TITLE
[BUG]:  "User Action 1" event is not functioning as expected

### ISSUE THREAD

**Issue by gautamsingh2** [ankidroid/Anki-Android#17171]
### Checked for duplicates?

- [X] This issue is not a duplicate

### Does it also happen in the desktop version?

- [X] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Settings-> controls->User action 1-> Add key ->Android phone volume down -> in select card side(Answer)
![Image](https://github.com/user-attachments/assets/5c0d9fec-907e-49fa-a3b7-01b53e924837)

2. Settings-> Appearance -> App bar buttons ->User acttion 1 -> menu only

![Image](https://github.com/user-attachments/assets/d951f160-ddfd-4eb8-a7e8-3eb1a253a92b)

3. Open any deck for review -> go to menu -> click on User action 1.

![Image](https://github.com/user-attachments/assets/2ad367e4-2c53-4ebc-9f9a-0f97ac0da61c)

7. ### Expected behaviour
User action 1 action need to perform

### Debug info

```text
AnkiDroid Version = 2.19beta4-debug (f6338a306d9498c62c27960d2e7e030fffde34c2)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 14 (SDK 34)

ProductFlavor = amazon

Manufacturer = samsung

Model = SM-X115
Hardware = MT8781

Webview User Agent = Mozilla/5.0 (Linux; Android 34; samsung Build/QKQ1.191008.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/128.0.6613.146 Mobile Safari/537.36

ACRA UUID = f10080eb-ce62-4f79-b5e6-2f5ccdd7cd5a

FSRS Enabled = false

Crash Reports Enabled = false

```

### Research

- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report. Please fill out the debug info

**Comment by RobozinhoD** [comment]
I can't reproduce

**Comment by gautamsingh2** [comment]
Hi @RobozinhoD,

I have successfully reproduced the issue. I have also added a screenshot in the reproduction steps for your reference. Please take a look at it

**Comment by oyeraghib** [comment]
@gautamsingh2 in your "Expected behaviour" you mentioned "User action 1 action need to perform" what does that actually mean specifically in the case you mentioned? Should clicking on "User Action 1" from the 3 dot menu should show "Answer"...?

**Comment by david-allison** [comment]
What did you set user action 1 to do in the JavaScript? 

Is this user error, in that action 1 should give the user a message if it's not mapped?

**Comment by gautamsingh2** [comment]
> [@gautamsingh2](https://github.com/gautamsingh2) in your "Expected behaviour" you mentioned "User action 1 action need to perform" what does that actually mean specifically in the case you mentioned? Should clicking on "User Action 1" from the 3 dot menu should show "Answer"...?

yes,to show Answer

**Comment by gautamsingh2** [comment]
> What did you set user action 1 to do in the JavaScript?

to show answer 

Is this user error, in that action 1 should give the user a message if it's not mapped?

No

**Comment by david-allison** [comment]
What's the JavaScript you're using?
