### ISSUE TITLE
[BUG]: Card is flickering while using white board

### ISSUE THREAD

**Issue by Dr-Konda** [ankidroid/Anki-Android#17190]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

This issue is happening while using all notetypes and cards.
Version: 2.19beta3

![Image](https://github.com/user-attachments/assets/91b99874-bfb6-4564-b73c-010ac4a61bd4)
https://github.com/user-attachments/assets/68b7d03c-7b3e-44fc-858d-8d85f6d89b6f

### Expected behaviour

Previously the whiteboard was fine

### Debug info

AnkiDroid Version = 2.19beta3 (408718b5bd3e314ea9e70854abd326162596eb5d)

Backend Version = 0.1.40-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = samsung

Model = SM-T975

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-T975 Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.17 Safari/537.36

ACRA UUID = c05fad33-753f-4171-a30c-6274b2bd3fcf

FSRS Enabled = true

Crash Reports Enabled = true

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Thanks for the report! Is this a regression in the beta?

**Comment by lukstbit** [comment]
I'm not seeing this in the latest 2.19beta4.

**Comment by david-allison** [comment]
@Dr-Konda 

I also can't reproduce this on a tablet.

Could you:

* Go to our [releases](https://github.com/ankidroid/Anki-Android/releases)
* Download Parallel.A
* Determine the release which introduced this bug

Please try 2.18.4 first, to confirm that this was added in the 2.19 series of releases

**Comment by Dr-Konda** [comment]
Thank you so much for responding,

The issue stopped after updating to version 2.19
