### ISSUE TITLE
[BUG]: In the AnkiWeb account screen, when the device orientation is switched to landscape mode, the AnkiDroid logo disappears.

### ISSUE THREAD

**Issue by xenonnn4w** [ankidroid/Anki-Android#17203]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

To Reproduce, follow the sequence-
Settings > Sync > AnkiWeb account > Logged In Screen > Switched to landscape mode

https://github.com/user-attachments/assets/8ac3bfda-b19c-414a-b434-86772e755429

### Expected behaviour

The AnkiDroid logo should be visible. 

### Debug info

2.19beta4

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
That's intentional due to saving screen space and ensuring the login form will be visible

**Comment by xenonnn4w** [comment]
oh, that's not the case with "Log in" screen; so i thought of it as issue.
