### ISSUE TITLE
[BUG]: Storage migration issue after changing AnkiDroid directory

### ISSUE THREAD

**Issue by virginviolet** [ankidroid/Anki-Android#17205]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

I changed the AnkiDroid directory in settings to `/storage/emulated/0/AnkiDroid1`, so that I will have read and write access to it.
I'm pretty sure this didn't happen on an earlier version when I tried this in January, but... now, after changing directory, it wants to migrate storage. I tap "Migrate" and it says "Collection synchronized". But the migration button at the top won't disappear, and every time I restart the app, the migration dialogue appears.

### Expected behaviour

Either that the migration dialogue didn't appear, or that tapping "Migrate" would make it disappear.

### Debug info

AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

FSRS Enabled = true

Crash Reports Enabled = true

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
The storage migration has been removed in 2.19, so this wont happen anymore

**Comment by virginviolet** [comment]
> The storage migration has been removed in 2.19, so this wont happen anymore

Oh. I'll get the latest beta then.
