### ISSUE TITLE
[BUG]: Can't Attach Audio Files in Non-Empty Fields

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#17201]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Double-click **＋**.
2. Add some text in a field.
3. Try to record audio using the native functionality and attach the file.

### Expected behaviour

The saved audio file isn't added to the field when the field is non-empty.

If a user is trying to replace one file with another this will cause issues for them.

### Debug info

2.19beta2

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@criticalAY FYI

**Comment by criticalAY** [comment]
Will go through it

**Comment by david-allison** [comment]
@brishtibheja Could you provide a video? Can't reproduce on `2.19beta4-debug` (433a4c887b96c04308ada10348546cd685bcbe25)

**Comment by brishtibheja** [comment]
It seems I can't reproduce it all the times. When I can reproduce the issue, after clicking Save I'm returned with the same audio recording screen. I recorded a video.

___

https://github.com/user-attachments/assets/65e15f86-c24d-4ced-8b80-75f9d8033105

**Comment by david-allison** [comment]
@criticalAY FYI - this is one of our blockers for 2.19, so any thoughts/help would be much appreciated (obviously no stress, just nothing this is a priority)

**Comment by criticalAY** [comment]
@brishtibheja I have fixed it and I will drop Gdrive link for apk in the PR, could you test it out? /I have tested it multiples times though but still to be sure/

**Comment by brishtibheja** [comment]
@criticalAY I tried but couldn't install the full universal build. I'll test it again when the new beta drops. Thanks!
