### ISSUE TITLE
[BUG]: When enabling "Type answer into the card", changes made to the value in JavaScript are ignored

### ISSUE THREAD

**Issue by SlugFiller** [ankidroid/Anki-Android#17229]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Create a type card with a script that modifies the value:
```
{{type:Answer}}
<a id="change_answer" href="#">Click here to change the answer</a>
<script type="text/javascript">
document.getElementById('change_answer').addEventListener('click', (e) => {
  e.preventDefault();
  document.getElementById('typeans').value = 'Changed value';
});
</script>
```

In settings, go to "Advanced" and enable "Type answer into the card"

Study the card. Type the text, `Typed value` into the filed. Click the link `Click here to change the answer`, then click `Show answer`.

### Expected behaviour

The answer card should show a comparison between the string `Changed value` and the correct answer

Instead it shows a comparison between `Typed value` and the correct answer

### Debug info

AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 4a (5G)

Hardware = bramble

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 4a (5G) Build/UP1A.231105.001.B2; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/129.0.6668.100 Mobile Safari/537.36

ACRA UUID = b012b035-7f38-423e-a9e9-009512401156

FSRS Enabled = false

Crash Reports Enabled = true

### (Optional) Anything else you want to share?

It would be nice if methods were added to the JavaScript API, to allow reading and writing the input text even when "Type answer into the card" is disabled

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@SlugFiller Thanks for the report. Is this a duplicate of:

* https://github.com/ankidroid/Anki-Android/issues/16213

**Comment by SlugFiller** [comment]
Ah, you're right, it is. I'll continue commenting there.
