### ISSUE TITLE
Development requests for Android widgets.

### ISSUE THREAD

**Issue by goodbird2** [ankidroid/Anki-Android#17240]
Do you have any intention of developing an Android stats widget, if I can see simple auto-synced stats on my desktop, it might make me more motivated.I also want to help, but I have no experience in development.

![Image](https://github.com/user-attachments/assets/baf88c2e-27f4-484e-acea-b2606009866f)

**Comment by BrayanDSO** [comment]
As stated in the `New issue` options, please send requests in the forums

![Image](https://github.com/user-attachments/assets/6ca78d99-d174-4045-90e8-ebefdd83ce75)
