### ISSUE TITLE
Audio stops prematurely when "Automatically play audio" option enabled

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1729]
Originally reported on Google Code with ID 827

```
What steps will reproduce the problem?
1.
2.
3.

What is the expected output? What do you see instead?


What version of AnkiDroid are you using? On what version of Android?


Please provide any additional information below.

```

Reported by `Broken.zhou` on 2011-10-12 10:33:45

**Comment by nick926** [comment]
I'm having this exact same problem on my Galaxy Tab A6. Strangely, though, it only happens when I have bluetooth headphones on, and even then only for some cards. Any ideas?

**Comment by pechyonkin** [comment]
I also noticed the problem persists if I use my wireless headphones (AirPods). When I switch to MacBook Pro's internal speakers, it disappears.

**Comment by mikehardy** [comment]
Hmm. Bluetooth but not internal sounds like buffer issues to me. They're more popular now as well . If you could provide anki and android versions it could help. I have Bluetooth headphones I should be able to reproduce

**Comment by mikehardy** [comment]
Wait, Mac is anki desktop separate team. Is this reproducible on Android with ankidroid?

**Comment by timrae** [comment]
This issue is 7 years old, there's no way it's the same bug, and the user is clearly talking about Anki desktop 😅

**Comment by mikehardy** [comment]
pre-coffee
