### ISSUE TITLE
Ankitags

### ISSUE THREAD

**Issue by mohannadhosamhamada** [ankidroid/Anki-Android#17322]
I hope ankidroid team to add more ability to edit and move tags on ankidroid like the pc version.
And the ability to remove tags, its very basic and important.

**Comment by david-allison** [comment]
We'll get the below merged some time; closing this as suggestions should go in the forums, and this isn't actionable. Thanks!

![Image](https://github.com/user-attachments/assets/74759bf9-9b78-411c-9033-4a8f7b7a9e6e)
