### ISSUE TITLE
Deprecation build warning: Should bump API source/target up from 8

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#17332]
Deprecation build warning: Should bump API source/target up from 8

```

> Task :api:compileDebugJavaWithJavac
Java compiler version 21 has deprecated support for compiling with source/target version 8.
Try one of the following options:
    1. [Recommended] Use Java toolchain with a lower language version
    2. Set a higher source/target version
    3. Use a lower version of the JDK running the build (if you're not using Java toolchain)
For more details on how to configure these settings, see https://developer.android.com/build/jdks.
To suppress this warning, set android.javaCompile.suppressSourceTargetDeprecationWarning=true in gradle.properties.
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
```

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/17329#issuecomment-2449990290_

**Comment by david-allison** [comment]
The lines are in the API, which targeted `minSdk 16` until https://github.com/ankidroid/Anki-Android/commit/dcb10769b16c72f52c4191d35f36a494be46fc3a

https://github.com/ankidroid/Anki-Android/blob/dcb10769b16c72f52c4191d35f36a494be46fc3a/api/build.gradle.kts#L48-L57

I feel this API bump was a mistake, discussing it now. If it wasn't, then we can bump the JavaVersion to 11 without issue:

----

* AGP 7.0 supports Java 11
  * https://developer.android.com/build/releases/past-releases/agp-7-0-0-release-notes#java-11
* AGP 8.0 supports Java 17
* our minimum JVM is 17
  * https://github.com/ankidroid/Anki-Android/blob/06e8ac2ef3e0d35fb3efc59aabb38c796b276b04/build.gradle.kts#L96-L111
* But we still target SDK 23
  * Which should have desugaring for Java 11 features
  * But building for Java 17 features is less supported
  * API 34 targets Java 17

See also: https://developer.android.com/build/jdks

```
> Task :api:compileDebugJavaWithJavac
Java compiler version 21 has deprecated support for compiling with source/target version 8.
Try one of the following options:
    1. [Recommended] Use Java toolchain with a lower language version
    2. Set a higher source/target version
    3. Use a lower version of the JDK running the build (if you're not using Java toolchain)
For more details on how to configure these settings, see https://developer.android.com/build/jdks.
To suppress this warning, set android.javaCompile.suppressSourceTargetDeprecationWarning=true in gradle.properties.
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
```

----

Note that we should probably move to `jvmToolchain` and remove `sourceCompatibility/targetCompatibility/jvmTarget`:

```kotlin
/**
 * Locate (and possibly download) a JDK used to build your kotlin
 * source code. This also acts as a default for sourceCompatibility,
 * targetCompatibility and jvmTarget. Note that this does not affect which JDK
 * is used to run the Gradle build itself, and does not need to take into
 * account the JDK version required by Gradle plugins (such as the
 * Android Gradle Plugin)
 */
kotlin {
    jvmToolchain(11)
}
```

https://developer.android.com/build

**Comment by david-allison** [comment]
On `jvmToolchain` from Mike (Discord message):

> I do not like the toolchains stuff though, I do not want to use that stuff
> It will dynamically download install and use new JDKs on your machines in a .gradle folder using matching rules that don't match well (IMNSHO) so you could end up with all sorts of random JDKs in there taking up space but only for a single module of some single project
> I'd prefer to never use them and just use our current method of testing for JDK major version that we can work with and erroring otherwise
> I might be a luddite but I believe the JDK choice should be between system and developer and provided to software, vs defined in software and auto-fetched somehow. Just doesn't seem like the right place to put that responsibility IMHO, it's too big a chunk for that
