### ISSUE TITLE
Acrarium migration

### ISSUE THREAD

**Issue by voczi** [ankidroid/Anki-Android#17343]
There's going to be some work we need to do for Acrarium:
- Use Ankidroid's own DO account for hosting the droplet.
  - Who pays for this? @mikehardy willing to use personal billing info, but AnkiDroid pays via reimbursement from OpenCollective
  - Consider upgrading to a droplet with better specs (more cores&RAM) so that it's actually usable.
  - Who should we have maintaining the droplet? Do we need more than one person?
- Upgrade to Acrarium 2.
  - Not even released yet? About 300 commits since the latest stable release: https://github.com/F43nd1r/Acrarium/compare/v1.8.1...v2.0.0-beta09
  - I found several dependencies in the beta with fairly high CVE scores and pinned the patched versions to fix this. Not sure how bad stable looks. Should consider submitting a PR with my changes.
  - Purge old reports in a cron job or something. Problem: Acrarium's API endpoint for reports does not support delete operations. Maybe we can just.. drop records from the database directly?
  - Problem: I tried upgrading to the latest beta with the current database as-is, but Acrarium got stuck during the database migration saying something like "duplicate column name". I tried tinkering with the MySQL dialect variable as mentioned [here](https://github.com/F43nd1r/Acrarium/issues/448) to no avail. Idea: Dump a (very) small proportion of our DB and try migrating it, instead of doing the whole DB at once, so that it becomes faster to debug any migration issues by changing settings around and so on.
  - Try adding Proguard mappings, again? Didn't work for me on the droplet (Acrarium v1.8.1). Trying to open any report results in an "Error 500" page. Good to know: After a few "Error 500" messages, you can get back into the admin panel and upload an empty mappings file for the app version that's now bugged out. That has always un-bugged it for me, so that I can check reports for that version.
  - Check to see if filtering has changed in Acrarium (maybe it has improved?). I have personally felt that it is a bit lacking, like when trying to filter after a specific field in the reports.
  - Check if ingress stack matching is possible with the newer version, without degradation of performance on the droplet (or total meltdown, apparently?) Mike has way better knowledge about this.

**Comment by mikehardy** [comment]
Hetzner is more cost-efficient then Digital Ocean, I've got a new server up on [Hetzner cloud](https://console.hetzner.cloud/):
- IP address 37.27.88.220 / 2a01:4f9:c012:e3bc::/64
- shared cx32 server type (4 vCPU / 8GB RAM / 80GiB disk)

Should be more than powerful enough to hold ankidroid.org in the future, appears like it will cost somewhere between $8-15/month, which is pretty good for a server that size.

Next steps I think:
-install webserver stuff on it and get our ankidroiddocs build workflow to publish to it
-work to get unreleased acarium 2 stuff releasable upstream and install it (note: I don't think a data migration is important, we can just let the old data stay in the old server and evaporate when we turn it off)
-point ankidroid.org to the new server

**Comment by voczi** [comment]
For certain off-site reasons that the core maintainers are aware of, there is no interest for me to engage in this issue any further. Feel free to re-create this in a new issue.

**Comment by mikehardy** [comment]
This issue is a reasonable place to track the work, just because you logged the issue doesn't mean it is"yours", it's just a gathering place for information, and it has all the information already so it should stay put - there's an "unsubscribe" button over on the right side of the github web UI so you won't have to pay attention to it though as I imagine you won't want to see notifications

**Comment by voczi** [comment]
This still puts the issue on my "Recent activity" list whenever someone posts something here. So, let's be reasonable, unless you are looking to escalate this further?
