### ISSUE TITLE
[Question] why we need to do format for localization ?

### ISSUE THREAD

**Issue by MahmoudMabrok** [ankidroid/Anki-Android#17350]
[here](https://github.com/ankidroid/Anki-Android/blob/main/.github/workflows/lint.yml#L83) we are doing a format, is formate different than lint?

**Comment by mikehardy** [comment]
The code is all open, please read it for understanding 

        run: cd tools/localization && yarn checkformat

https://github.com/ankidroid/Anki-Android/blob/dea6d6d12c6c415641b2df54f61c1897186d51a9/tools/localization/package.json#L11

So we are running:

> npx prettier --check .

Prettier is our auto-formatter for javascript / typescript code, so we run that in case people have made changes to that code to make sure that all of the changes match our formatting standards

All of the code here is auto-formatted using project-wide formatting definitions so we don't waste any time having pointless discussions on how to correctly format code
