### ISSUE TITLE
[BUG]: Parameters must be either left blank to use the defaults, or must be 17 comma-separated numbers

### ISSUE THREAD

**Issue by chrislongros** [ankidroid/Anki-Android#17359]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Current AnkiDroid version: 2.19.1 arm64 v8
Current Anki Desktop version: 24.10 (8b845834)⁩

### Expected behaviour

Do reviews with no problem.

### Debug info

AnkiDroid Version = 2.19.1 (6953d60532ee2762d29b06fd1d76e69203ad8455)
Backend Version = 0.1.43-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)
Android Version = 13 (SDK 33)
ProductFlavor = full
Manufacturer = Xiaomi
Model = 2201117TY
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 13; 2201117TY Build/TKQ1.221114.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.58 Mobile Safari/537.36
ACRA UUID = 551fcc24-f6d1-4cd4-bbe0-bbeed1f939b5
FSRS = 0.6.4 (Enabled: true)
Crash Reports Enabled = true

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Issue is resolved in Anki Desktop beta 4 (I believe). Optimize with Anki Desktop

If this fails. Optimize with AnkiDroid 

If this fails. Seek help or restore from backup 

Closing as this is an issue introduced by the Anki beta which will not occur during production

**Comment by chrislongros** [comment]
I tried to optimize in Anki Desktop and AnkiDroid: both methods failed

**Comment by david-allison** [comment]
Time to check on the beta thread in the forums
