### ISSUE TITLE
Card HTML includes ancient zoom/scroll hack - needs test, docs update, possible modernization

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#17358]
As the title says, card.html includes some dubious javascript that attempts to work around ancient webview limitations.

I attempted to remove that with:
- #17281 

...but it turns out that the old workaround is not just for image zooming (which appears to work now) but also for page scroll placement when cards are flipped - causing a serious regression:
- #17318 

...so I reverted that immediately with:
- #17336 

I do still think this area needs attention though, as the docs in the code are at minimum out of date, and a critical feature of the app (that the card flip scrolls things to the correct spot) has no test coverage.

So, to close this issue, two things should happen:

- We need an androidTest that verifies the location of the WebView page content on question side and answer side somehow. How? I don't know, perhaps a card with some javascript that creates some sort of rectangular space-occupying graphical feature that takes up exactly one screen for the question, and has an identifiable element at the bottom? And same for the answer side? And then you attempt to detect that the question one is there but answer one is not, for the question side, and the answer one is there but question one is not on the answer side? But really any way that works and is easy to understand
- We need to document that the javascript hack is more than just a zoomable workaround but also affects card scroll position so is at least currently needed

We *may* then try to move forward by perhaps using modern WebView programmability to zoom without using javascript page loaded hooks? For example one way is mentioned here 

https://github.com/ankidroid/Anki-Android/pull/17317#discussion_r1820315737

> The delay is likely there to wait for the WebView to complete rendering, which ensures it’s ready to scroll back to the saved position. However, a fixed delay might not be enough if rendering takes longer.
Instead of a hardcoded delay, we can check if the WebView is ready by using a ViewTreeObserver.OnGlobalLayoutListener. This listener triggers when the layout changes, which ensures the WebView is rendered before restoring the scroll position

**Comment by BrayanDSO** [comment]
We eventually will use the desktop reviewer, so I don't think that it's worth working on this

**Comment by mikehardy** [comment]
Oh that's a good point! No idea why I keep forgetting that.
Closing.
