### ISSUE TITLE
[BUG]: IO Cards Go to the Wrong Deck

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#17393]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Go to **Settings > General**.
2. Click **Deck for new cards** and select `use current deck`.
3. Go back to deck picker and select a deck.
4. Now, double-click **＋** to open the Add screen.
5. Select the IO note type.
6. Change deck. Now you've selected a different deck and cards should go here.
7. Create a IO card from here.

### Expected behaviour

The deck where the IO cards created go should be the one we selected at #6 but the cards go to the previously selected deck.

### Debug info

```
AnkiDroid Version = 2.20alpha1 (edd1c61e6445ccac2ddf3cabe0d63c6a303f27b7)

Backend Version = 0.1.43-anki24.10rc2 (24.10rc2 898c91284bc97c928adbf1bcc8ca885b068dac5f)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.106 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hey there - for purposes of localizing this bug, does this happen on 2.19.x, or only on 2.20alpha?

**Comment by brishtibheja** [comment]
Can't reproduce on 2.19.1 ver.

**Comment by lukstbit** [comment]
I've closed a previous duplicate in favor of this report as it's more recent:
* #15721
