### ISSUE TITLE
Add a metronome option

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#17412]
When I review music card, I'd like to be able to have a metronome. In anki I can easily have it in another window or use a addon.
In AnkiDroid I'm unable to create a js script that has a regular beat, and opening a second app is not practical.

Ideally I'd like to be able to configure it with a note's field. 

I can implement it of course but won't try without permission

**Comment by mikehardy** [comment]
that seems like a pretty special purpose thing, I would not want this in AnkiDroid.

However! I understand javascript timing can be difficult to work with while a metronome has ONE JOB, that being perfect timing.

What if... there was a javascript API to create and send an Intent? That is, allow javascript to do Android inter-app RPCs...

...and there was a metronome app that responded to Intents to "start metronome at NNN bpm" and "stop metronome"

There are a number of metronome apps on github and responding to an Intent to start/stop seems pretty easy?
Adding a javascript API to send an Intent seems pretty easy?

Now we've got two excellent features where they belong (IMHO) and we do not have a metronome feature mushrooming within AnkiDroid

?

**Comment by mikehardy** [comment]
https://github.com/patzly/tack-android/blob/763be954c9d29da1e20151f4ff6b07edbe511ccb/app/src/main/java/xyz/zedler/patrick/tack/service/MetronomeService.java#L67-L78

**Comment by david-allison** [comment]
Agreed: out of scope for now

Would be a great addon, external app, or JS functionality (once we get the new reviewer)
