### ISSUE TITLE
[BUG]: Tablet: Settings highlight does not follow 'back button'

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17414]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

* Open Settings
* Tap 'Sync'
* Tap 'General'
* Press 'Back'

'General' is highlighted, with 'Sync' settings

![Image](https://github.com/user-attachments/assets/d06887f1-618d-4cfc-8432-e490abb6a456)

### Expected behaviour

'Sync' is highlighted

### Debug info

```text
AnkiDroid Version = 2.20alpha1-debug (b02115ed02ec8f3eec8706d0dcdc81642be4b6a7)

Backend Version = 0.1.47-anki24.11rc1 (24.11rc1 97e6b3d35b9ef541865a127fc094f521e43480d9)

Android Version = 14 (SDK 34)

ProductFlavor = amazon

Manufacturer = Google

Model = sdk_gphone64_arm64

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 14; sdk_gphone64_arm64 Build/UE1A.230829.036.A4; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.136 Safari/537.36

ACRA UUID = c682c90c-b65b-46d6-a858-ead1c92717f3

FSRS = 1.4.3 (Enabled: false)

Crash Reports Enabled = false
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
See:

* https://github.com/ankidroid/Anki-Android/pull/16368
* e605223cf0f22cf9eb0ee48b6d4e68f47205cc41

**Comment by jainv4156** [comment]
Hi @david-allison , I was able to successfully reproduce this bug. Can I work on this issue?

**Comment by david-allison** [comment]
Sure
