### ISSUE TITLE
[BUG]: <svg> not displayed nor accepted as valid input

### ISSUE THREAD

**Issue by natema** [ankidroid/Anki-Android#17440]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Create a new card with front
```html
<svg width="200" height="100">
  <rect width="200" height="100" fill="blue" />
</svg>
```

### Expected behaviour

- A blue rectangle is shown in the preview of the card.
- The user can create such a card. Currently, AnkiDroid says that the input is empty. 

### Debug info

```text
AnkiDroid Version = 2.19.1 (6953d60532ee2762d29b06fd1d76e69203ad8455)

Backend Version = 0.1.43-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = samsung

Model = SM-T976B

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; SM-T976B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.107 Safari/537.36

ACRA UUID = d3f4901a-c6f6-453e-9e92-03961a0d8f39

FSRS = 0.6.4 (Enabled: false)

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

I wasn't able to determine if this issue is related to #17029 or https://github.com/ankidroid/Anki-Android/issues/3250. 

In Anki Desktop, the svg is correctly previewed, but it seems that Anki is still ignoring the svg, since if the front only contains the svg element Anki says that the card is empty when the user tried to create it. Moreover, **the two following cards are considered the same**: 
- Front of card 1
```html
What color is this?
<svg width="200" height="100">
  <rect width="200" height="100" fill="blue" />
</svg>
```
- Front of card 2
```html
What color is this?
<svg width="200" height="100">
  <rect width="200" height="100" fill="red" />
</svg>
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Reproduced... cool!

Thanks so much for this one!

**Comment by natema** [comment]
I just noticed that, while the preview works in Anki Desktop, the svg element still appears to be entirely ignored. I edited the "Anything else you want to share?" section in the issue description. At this point it's borderline to say that it's not an Anki Desktop bug. I will create an issue there as well and link it here.

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/labels/upstream-issue. Please report it on [the forums](https://forums.ankiweb.net/)

`col.backend.noteFieldsCheck(this.toBackendNote()).state == NoteFieldsCheckResponse.State.EMPTY`

Screenshot from Anki Desktop Version ⁨24.06.3 (d678e393)⁩

![Image](https://github.com/user-attachments/assets/4e9b52fa-bc11-464c-987d-7f63cf0b365b)


Additional info: executed `noteFieldsCheck` with data

```
# anki.notes.Note@21a7e6b7
fields: "<svg width=\"200\" height=\"100\"><br>  <rect width=\"200\" height=\"100\" fill=\"blue\" /><br></svg>"
fields: ""
fields: ""
guid: "o#L2Vu%%uy"
id: 0
notetype_id: 1731502348910
```

----

I'm closing this as it's an issue with Anki Desktop (as per the screenshot), but please feel free to respond if I'm mistaken

**Comment by david-allison** [comment]
Thanks so much for the detailed report! Made this one really easy to diagnose

**Comment by natema** [comment]
It seems to me that there still is an issue with AnkiDroid per se: the Desktop version ignore the svgs to determine if the card is empty or unique, but correctly displays them. For example, I can create such a card: 
Front
```html
What color is this?
<svg width="200" height="100">
  <rect width="200" height="100" fill="blue" />
</svg>
```
Back
```
Blue
```

The svg element is correctly shown on Anki Desktop, while **on AnkiDroid, the svg square is not shown**.

**Comment by david-allison** [comment]
Can be fixed with:
* Settings - Advanced - Replace newlines with HTML

----

* https://github.com/ankidroid/Anki-Android/issues/3304 - will be resolved when we make a visual Note Editor

**Comment by natema** [comment]
Thanks a lot!
Here's the issue in the forum https://forums.ankiweb.net/t/content-of-svg-elements-is-ignored-in-determining-if-the-card-is-unique/51915
