### ISSUE TITLE
[BUG]: App crashes when network permission is disabled

### ISSUE THREAD

**Issue by antgig** [ankidroid/Anki-Android#17454]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Disabled network permission for Ankidroid
2. Open app
3. Click on a deck to study
4. "An error report is being prepared for the developers..." popup appears 
5. Ankidroid Feedback prompt appears 
6. Click cancel
7. Step 5-6 occurs repeatedly 
8. Disable Error reporting mode in settings by selecting 'Never report'
9. Click on a deck to study. App crashes instead of the Ankidroid Feedback prompt appearing

### Expected behaviour

Expected to continue to study decks with network permission disabled. The issue does not appear when it is enabled. 

### Debug info

```text
AnkiDroid Version = 2.19.1 (6953d60532ee2762d29b06fd1d76e69203ad8455)

Backend Version = 0.1.43-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 15 (SDK 35)

ProductFlavor = full

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel 6a Build/AP3A.241105.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.39 Mobile Safari/537.36

ACRA UUID = 54d8e8c7-0098-4472-93e7-5b18f2552770

FSRS = 0.6.4 (Enabled: false)

Crash Reports Enabled = false
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Is removing the network permission of apps part of the default functionality of your phone? 

If so, could you provide reproduction steps?

**Comment by mikehardy** [comment]
We have seen this before, duplicate #5718

It is s a documented requirement that INTERNET permissions is allowed as we have an internal client/server architecture that is fundamental to the app --> https://github.com/ankidroid/Anki-Android/wiki/Permissions/5f6f0d353a0ecdc8d8cc976eadf9eb2ca3ddbf9a#network-communication

I understand this may be unusual for an app, and I understand allowing that permission may be bothersome for some. Nevertheless, the requirement will not go away
