### ISSUE TITLE
BUG: Multimedia Option Open Twice When Bottom Sheet is Opened Twice

### ISSUE THREAD

**Issue by brishtibheja** [ankidroid/Anki-Android#17453]
I reported this before in https://github.com/ankidroid/Anki-Android/issues/17201 and @criticalAY tried to fix it in https://github.com/ankidroid/Anki-Android/pull/17239

I think I have identified how to properly reproduce this so I'm opening this new issue.
___

## Steps

1. Open the Add screen.
2. For any field, open the multimedia bottom sheet.
3. Now, close it.
4. Now open it again and select an option.

## Behaviour

When you've selected a file and clicked OK, the files app open again. Similar behaviour with other options too. With record audio, I'm prompted to record audio once again.

## Debug Info

```
AnkiDroid Version = 2.20alpha1 (edd1c61e6445ccac2ddf3cabe0d63c6a303f27b7)

Backend Version = 0.1.43-anki24.10rc2 (24.10rc2 898c91284bc97c928adbf1bcc8ca885b068dac5f)

Android Version = 11 (SDK 30)

ProductFlavor = full

Manufacturer = realme

Model = RMX2193

Hardware = mt6768

Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2193 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.106 Mobile Safari/537.36

ACRA UUID = cf265e01-9693-407f-984d-61ddf9698fac

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true

```

**Comment by brishtibheja** [comment]
The recording I posted in the old issue also had the same steps.

___

https://github.com/user-attachments/assets/65e15f86-c24d-4ced-8b80-75f9d8033105

**Comment by brishtibheja** [comment]
I can reproduce this on latest alpha, so it appears not fixed.

**Comment by criticalAY** [comment]
This recording issue?

**Comment by brishtibheja** [comment]
Yes. It appears to also happen with other multimedia options. Now that I go back to old recordings of that, it seems the problem might not have anything to do with empty/non-empty fields but with opening the bottom sheet twice.
