### ISSUE TITLE
[BUG]: a record that has a duplication could not be edited

### ISSUE THREAD

**Issue by Petriusam** [ankidroid/Anki-Android#17478]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Open any existing record.
2. Press to duplicate the record → a new record editor opens→ .... → save the record
3. We returned to the previous record
4. Any changes here, trying to save cause the Error window "java.lang.NullPointerException". The record isn't saved.
If not to save at point 2 the exception won't emerge.

### Expected behaviour

The record at step 3 should be saved.

### Debug info

```text
AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

Backend Version = 0.1.38-anki24.04.1 (24.04.1 ccd9ca1a8309b80bcb50ddc5d99c7ce63440bce9)

Android Version = 13 (SDK 33)

ProductFlavor = play

Manufacturer = Lenovo

Model = TB138FC

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 13; TB138FC Build/TKQ1.221013.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.107 Safari/537.36

ACRA UUID = 7c7d7985-616b-426c-b576-07ffdc85526c

FSRS Enabled = true

Crash Reports Enabled = true
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there 👋 

> AnkiDroid Version = 2.18.4 (f867da96b8304edaebd0361326316bc7514f8cde)

We've been working on the new 2.19.x series for a while and with the release of 2.19.2 I've finally dialed the production track rollout to 100% so everyone can see it.

That means that if you update your apps, you *should* see an AnkiDroid update, and it *should* be 2.19.2, and...maybe this is already fixed? Can you test it and see if this is still happening for you and report back?

Thank you!
