### ISSUE TITLE
[Proposal] StudyOptionsFragment: re-include 'total cards'

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17489]
> [!NOTE]
> This is not open for implementation until a consensus has been reached

07768585818965b7502bc6577179b35c5e2bd710 performs the following change:

> - removes information that isn't shown in the desktop app like the total cards count and total new cards

* https://github.com/ankidroid/Anki-Android/pull/16947

> * the previous code showed the total cards count in the deck. As the desktop screen didn't show this I removed it. Can be brought back with ease if requested using the cardCount() method which was just added to out codebase.
> * the previous code showed the total new cards count in the deck. As the desktop screen didn't show this I removed it. This can also be brought back for normal decks, however the related backend method doesn't work for filtered decks so we would need to either don't show this count for filtered decks or use the old code(which I'm actively trying to purge).

4 users have requested that this is reinstated:

* https://github.com/ankidroid/Anki-Android/pull/16947#issuecomment-2308430776
    > I use this screen regularly as a fast way to see how many new cards remain in a desk to estimate when I will finally complete the deck. For me, it's motivational to watch the numbers go down and I would be sad to lose that unless there's another easy way to see new/total count without having to mess with the deck browser. 
* https://discord.com/channels/368267295601983490/701939078786187315/1309788428593795114
  > How come the app no longer shows me how many new cards and total cards i have left in a deck when I click on the deck. Now it just shows me the new, learn and due
  > ... 
  > Yes, it used to be better than desktop, much better imo cause I liked insta seeing how many new cards I had total left and calculating in my head how many days that would take me
* https://www.reddit.com/r/Anki/comments/1gdw6mc/comment/lyjwsuu/?context=3
   >  2.19.2 seems to have eliminated the "Total" section of cards on the deck screen. Is there a way to re-enable it or do I just need to go to GitHub and get 19.1?
* https://www.reddit.com/r/Anki/comments/1gdw6mc/comment/lykeib6/?context=3
   > It used to be when you clicked the numbers next to a deck it used to show. New, learning, to review, and total cards. Now it's just new, learning, and to review. We used to be able to see how many cards are left that are new

I'd support reinstating it, but would like consensus before doing so.

**Comment by Danika-Dakika** [comment]
Another from a Reddit user: https://www.reddit.com/r/Anki/comments/1gxtr2k/change_in_card_count_display/

**Comment by BrayanDSO** [comment]
It seems more like a familiarity issue than a design one. Checking that in statistics is pretty quick, and has even a graph. So staying as is isn't bad.

On the other hand, that whole screen is poorly designed anyway, so adding a thing or two won't spoil something that is already rotten.

Following Newton's first law, I personally prefer to keep things as is. But if people wants to do all the implementation, reviewing and maintenance work, I won't object.

**Comment by david-allison** [comment]
My finger's no longer on the pulse with Reddit, and this feels like a very common complaint:

https://www.reddit.com/r/Anki/comments/1gyq37r/ankidroid_how_can_i_see_how_many_new_cards_are/

**Comment by lukstbit** [comment]
I guess restoring this is slightly more convenient for the user as it takes two extra "clicks"(on the hamburger button and scroll the stats page a bit) to see the info vs. the desktop app. I a and dded a PR  as it isn't that much code anyway.
