### ISSUE TITLE
[2.19.2] Android 8 WebView detection issue

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17498]
User appears to be on WebView 130.X, but we are detecting it as 70.

https://www.reddit.com/r/Anki/comments/1gy8viw/cant_update_webview_android_8_whats_my_best_option/

**Comment by mikehardy** [comment]
Something appears to have gone wrong here:
- #17441

I'll ask for debug info

**Comment by david-allison** [comment]
I don't know whether the user **can** provide debug info outside logcat if this screen appears

**Comment by mikehardy** [comment]
I believe you can - when I tested that PR 17441 I was able to tap outside the webview prompt and continue using the app. I considered that a key part of the warning - advise the user but don't *block* the user, just try to continue and most things work

**Comment by rlpowell** [comment]
Oh, this got lost: I can totally use the app.  I just click outside the box, and everything works normally.  I've seen no problems at all.

**Comment by rlpowell** [comment]
Debug info:

```
AnkiDroid Version = 2.19.2 (b073f52783583fd4fd1436d986090ced9006a66b)

Backend Version = 0.1.43-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 8.1.0 (SDK 27)

ProductFlavor = play

Manufacturer = BlackBerry

Model = BBF100-2

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 8.1.0; BBF100-2 Build/OPM1.171019.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.81 Mobile Safari/537.36

ACRA UUID = 8655e1d3-8a4d-4234-9d0d-406022cfc42f

FSRS = 0.6.4 (Enabled: false)

Crash Reports Enabled = true
```

**Comment by rlpowell** [comment]
Also I'm quite technical, lemme know if you need anything else.

**Comment by Yuri-K7** [comment]
Same issue with android 9, sees webview 74 and wants 77.

```
AnkiDroid Version = 2.19.2 (b073f52783583fd4fd1436d986090ced9006a66b)

Backend Version = 0.1.43-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 9 (SDK 28)

ProductFlavor = play

Manufacturer = samsung

Model = SM-A730F

Hardware = samsungexynos7885

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-A730F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.102 Mobile Safari/537.36

ACRA UUID = 0af32b0f-8aed-4887-a2ed-942be1d0b77c

FSRS = 0.6.4 (Enabled: false)

Crash Reports Enabled = true
```

**Comment by david-allison** [comment]
Thanks both! 

Could you screenshot the message?

**Comment by rlpowell** [comment]
![Image](https://github.com/user-attachments/assets/4eacd732-584b-44d4-8527-2f1c96d0a904)

**Comment by Yuri-K7** [comment]
![Image](https://github.com/user-attachments/assets/00b284fb-45de-4490-8976-72d3afe19151)

**Comment by Mar2ck** [comment]
Try this: Enable developer options in your phone's settings, look for "WebView Implementation" and make sure it's set to the play store version.

I had a problem on an old phone where this was set to a built-in version that was very old so even though I had the playstore webview installed it wasn't actually getting used.

**Comment by mikehardy** [comment]
Fascinating - the thing is, we're parsing the WebView version from the one that's loaded and should be visible in the debug info
We just changed the version parsing style between v2.19.1 and v2.19.2 for "reasons" (the best intentions, always! 😆 ) and clearly we're missing something important about it.

Having these version strings should help us out with test cases to fix up the new version parsing style
Or inform us that we need to revert, I suppose. Either way, the extra information is really useful thanks

**Comment by rlpowell** [comment]
Looks good thank you!

**Comment by mikehardy** [comment]
Happy to hear it seems to be working! Was a big refactor to fix this one 😅 
Can't imagine how irritating it was to get that popup every time though, go away already right?
