### ISSUE TITLE
User report: `Anki-Android-main.zip` repo flagged by MS Defender as `TrojanScript/Wacatac.B!ml`

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17502]
```
file: C:\Users\Khalil\Downloads\Anki-Android-main.zip
file: C:\Users\Khalil\Downloads\Anki-Android-main.zip
webfile: C:\Users\Khalil\Downloads\Anki-Android-main.zip|https://codeload.github.com/ankidroid/Anki-Android/zip/refs/heads/main|pid:9968,ProcessStart:133771064628792785
```

![Image](https://github.com/user-attachments/assets/39bae253-7147-492a-a00c-b5d6533d3321)

**Comment by mikehardy** [comment]
Going to guess user has some sort of "man in the middle" attack wherein malicious things are injected into things they download somehow

**Comment by david-allison** [comment]
Reproduced if downloaded by MS Edge (likely an [ADS](https://en.wikipedia.org/wiki/NTFS#Alternate_data_stream_(ADS)) issue)

Fix for now: 

* Download`Anki-Android-main.zip` using Firefox
* Or clone the repo with `git clone`
