### ISSUE TITLE
[BUG]: Note Editor: Resizing Ankidroid in split screen resets new card content

### ISSUE THREAD

**Issue by Philedor** [ankidroid/Anki-Android#17521]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Open Ankidroid and another application in split screen.
2. Create a new card and add some content.
3. Resize the split between the two applications (this can be done manually or automatically when the second application changes).
4. The new card's content is reset. 
5. https://github.com/user-attachments/assets/70f39ba4-f2c1-40a8-9203-9d12668d3e39
 

### Expected behaviour

The new card's content does not reset. 

### Debug info

```text
AnkiDroid Version = 2.19.2 (b073f52783583fd4fd1436d986090ced9006a66b)

Backend Version = 0.1.43-anki24.06.3 (24.06.3 d678e39350a2d243242a69f4e22f5192b04398f2)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = Xiaomi

Model = 23043RP34G

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 14; 23043RP34G Build/UKQ1.230917.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.39 Safari/537.36

ACRA UUID = 7adb37c6-c047-4ffb-b558-244d2e2c1a2c

FSRS = 0.6.4 (Enabled: false)

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Thank you guys for doing this! :)

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Thanks for reporting this - probably an activity/fragment lifecycle issue
Anyone looking to triage this: examine Activity methods that deal with the saved instance state Bundle, and same for Fragments involved in this screen

**Comment by Prince-kushwaha** [comment]
Hi @mikehardy,i like to work on this issue

**Comment by Prince-kushwaha** [comment]
i like to work on this issue

**Comment by BrayanDSO** [comment]
In the long term, the Note Editor will be migrated into a WebView page, and the content of one isn't recoverable after a activity is recreated, so using `android:configurationChanges="screenSize"` is acceptable here IMO.

Saving the state would be the ideal fix, but the work would be temporary.

**Comment by mikehardy** [comment]
good point re: moving to webview etc. agree just ignore config change then to see if it works

**Comment by david-allison** [comment]
This worked before, I'd like to treat it as a regression and fix it properly

**Comment by mikehardy** [comment]
we could but we *do* only have limited attention - perhaps best served exposing note editor from upstream
but it's open source, anyone can work on anything in reality
