### ISSUE TITLE
[BUG]:  The "Answer" input box briefly appears for a few seconds in the Review Activity when reviewing a card, even though the answer button position is set to "None."

### ISSUE THREAD

**Issue by Prince-kushwaha** [ankidroid/Anki-Android#17525]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

The "Answer" input box briefly appears for a few seconds in the Review Activity when reviewing a card, even though the answer button position is set to "None."

Steps to reproduce this bug
1.Go to Settings and click on  Appearance
2.In Appearance, Go "Answer button position" setting , set it "None" 
3.Open any deck for review

https://github.com/user-attachments/assets/53c234c0-5a0b-48b2-949c-8dd6dcf9b95b

### Expected behaviour

 "Answer" input box not soon

### Debug info

```text
AnkiDroid Version = 2.20alpha2-debug (4f4cd0030737f8314473a1a05d0097b1aa130b84)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 10 (SDK 29)

ProductFlavor = amazon

Manufacturer = Xiaomi

Model = Redmi Y3

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi Y3 Build/QKQ1.191008.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/130.0.6723.108 Mobile Safari/537.36

ACRA UUID = a3a67a4f-8502-4c6f-a227-4410ea48a6f6

FSRS = 1.4.3 (Enabled: false)

Crash Reports Enabled = fals
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
Very small issue and only applies to slower devices. As we are moving to a new reviewer (#14302), I'll close this.
