### ISSUE TITLE
CI: ensure `testlib` is built

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17520]
See 

* https://github.com/ankidroid/Anki-Android/issues/17517

We want to ensure that GitHub Actions runs `./gradlew :testlib:assemblePlayDebugAndroidTest` at some point to ensure that `testlib` compiles

This could likely either be done directly in CI (`/.github`), or by adding a dependency on this task from AnkiDroid's `androidTest` in `build.gradle`. The latter being preferred

**Comment by MritunjayTiwari14** [comment]
Can i work on this?

**Comment by KushagraPatni** [comment]
Can I work on this ? because @tanishy7777 is not replying.

**Comment by david-allison** [comment]
Sure
