### ISSUE TITLE
Handle 'Support older Anki Versions' when exporting

### ISSUE THREAD

**Issue by NameLessGO** [ankidroid/Anki-Android#17536]
This bug report is crossposted from Anking repo to Ankidroid

* https://github.com/AnKing-VIP/AnKing-Note-Types/issues/205

**Comment by louzhuqaq** [comment]
Misconfiguration.
Make sure that the S3 stored phase is correctly set in Loki's configuration file.
Close parameters, including endp oint, access keyid,.
secretAcce ssKey away.For example, in the use of the Helm department. When signing Loki, it needs to be in the file v alues-loki.yam B. Correctly modify loki.storage related field 4.
2.Permissions issues.
Ensure that the access keys used to access the S3 store have the correct weight limits, including ListBuc ket, PutObject, and.
GetObject,D eleteObject等.The authorization policies of different cloud platforms may be
different. If you encounter insufficient permissions, you can try to give the whole bucket a complete read-write limit of 4.

**Comment by david-allison** [comment]
> The difference is due to this option being enabled in AnkiDroid by default. ![image](https://private-user-images.githubusercontent.com/41397710/392279064-e054e79c-1c8b-4bba-875c-20017860d693.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzNDYyOTksIm5iZiI6MTczMzM0NTk5OSwicGF0aCI6Ii80MTM5NzcxMC8zOTIyNzkwNjQtZTA1NGU3OWMtMWM4Yi00YmJhLTg3NWMtMjAwMTc4NjBkNjkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDIwNTk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2YWY1MDBjOGVkODFlZGMwZjkwMDMyNjlhYjViNjAwMTA5YzljMzYzYzQzMGY2MjE1ZWM0NmU2M2IxNmVkZmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9z_RGSucQMfPRBMtgMkhs-9_y87W_2cIHIrEfHA2nPk)
> 
> To confirm, enable the option, export on desktop and compare the size with the AnkiDroid export.

- abdo

**Comment by david-allison** [comment]
This can be implemented in the following file

https://github.com/ankidroid/Anki-Android/blob/09a45359ec70fd76c76d7115b14a4127aea6cc13/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt

## Steps
### 1

* remove `= true` defaults:

https://github.com/ankidroid/Anki-Android/blob/14813c15532eda25d5fdcc8dd03e2e957caf689b/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt#L114-L120

https://github.com/ankidroid/Anki-Android/blob/14813c15532eda25d5fdcc8dd03e2e957caf689b/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt#L83-L87

And show the checkbox ONLY when either collection/deck exports are selected

### 2) Add a Checkbox to obtain the user-selected value in the Fragment

Use `TR.` to obtain the translated string which Anki Desktop uses

### 3) Ensure the default user-selected value is `false` for both `apkg` and `colpkg`

4) Add appropriate unit tests. Suggestions:

* Checkbox is only available on two selections
* Checkbox defaults to false
* Checkbox value is provided to the correct export functions (true/false)

----

* Reference: https://github.com/ankidroid/Anki-Android/pull/11644 => b5829f682514f10323201531a50a49a639c4eff9

**Comment by MorenoTropical** [comment]
I can do this

**Comment by david-allison** [comment]
I think we should give @agnibhananda a little time with this as their first issue

**Comment by Haz3-jolt** [comment]
Hi I'd like to work on this

**Comment by Haz3-jolt** [comment]
> This can be implemented in the following file
> 
> https://github.com/ankidroid/Anki-Android/blob/09a45359ec70fd76c76d7115b14a4127aea6cc13/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
> ## Steps
> ### 1) remove `= true` defaults on `legacy` in the underlying functions
> 
> [Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt](https://github.com/ankidroid/Anki-Android/blob/14813c15532eda25d5fdcc8dd03e2e957caf689b/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt#L114-L120)
> 
> Lines 114 to 120 in [14813c1](/ankidroid/Anki-Android/commit/14813c15532eda25d5fdcc8dd03e2e957caf689b)
>  fun Collection.exportAnkiPackage( 
>      outPath: String, 
>      withScheduling: Boolean, 
>      withDeckConfigs: Boolean, 
>      withMedia: Boolean, 
>      limit: ExportLimit, 
>      legacy: Boolean = true 
> 
> [Anki-Android/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt](https://github.com/ankidroid/Anki-Android/blob/14813c15532eda25d5fdcc8dd03e2e957caf689b/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt#L83-L87)
> 
> Lines 83 to 87 in [14813c1](/ankidroid/Anki-Android/commit/14813c15532eda25d5fdcc8dd03e2e957caf689b)
>  fun Collection.exportCollectionPackage( 
>      outPath: String, 
>      includeMedia: Boolean, 
>      legacy: Boolean = true 
>  ) { 
> 
> ### 2) Add a Checkbox to obtain the user-selected value in the Fragment
> 
> Use `TR.` to obtain the translated string which Anki Desktop uses
> 
> Only show the checkbox when either collection/deck exports are selected
> ### 3) Ensure the default user-selected value is `false` for both `apkg` and `colpkg`
> ### 4) Add appropriate unit tests
> 
> Suggestions:
> 
>     * Checkbox is only available on two selections
> 
>     * Checkbox defaults to false
> 
>     * Checkbox value is provided to the correct export functions (true/false)
> 
> 
>     * Reference: [Update to work with desktop 2.1.54 code #11644](https://github.com/ankidroid/Anki-Android/pull/11644) => [b5829f6](https://github.com/ankidroid/Anki-Android/commit/b5829f682514f10323201531a50a49a639c4eff9)


Ok some help with this if possible,

1) What is the user-selected value we are looking for? is it the value for legacy being true or false?
2) For the string, I can't find the relevant string for this? Does it already exist or are we supposed to create it?

**Comment by david-allison** [comment]
<img width="662" alt="Image" src="https://github.com/user-attachments/assets/6d7bcbca-2e5d-41e5-a60c-67134a4b86af" />

Anki Desktop default.

The string is: `TR.exportingSupportOlderAnkiVersions()`

**Comment by Haz3-jolt** [comment]
Cool got it.

**Comment by Haz3-jolt** [comment]
So got a semi decent draft goin but facing a few issues, probabyly with the XML:
![Image](https://github.com/user-attachments/assets/ca6584a7-5426-444f-82ba-b8628f98d9e4)
![Image](https://github.com/user-attachments/assets/0f8311b5-7ff0-466c-b3d2-24b6a7dcb78e)

Will get the tests done after fixing these, they should be easy enough.


`Index: AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt b/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt
--- a/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt	(revision fab4ed0a8652390db0d41b8555ebdceb03b0b7c0)
+++ b/AnkiDroid/src/main/java/com/ichi2/libanki/BackendImportExport.kt	(date 1734530088315)
@@ -82,7 +82,7 @@
 fun Collection.exportCollectionPackage(
     outPath: String,
     includeMedia: Boolean,
-    legacy: Boolean = true,
+    legacy: Boolean,
 ) {
     close(forFullSync = true)
     backend.exportCollectionPackage(
@@ -113,7 +113,7 @@
     withDeckConfigs: Boolean,
     withMedia: Boolean,
     limit: ExportLimit,
-    legacy: Boolean = true,
+    legacy: Boolean,
 ) {
     val options =
         exportAnkiPackageOptions {
Index: AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt b/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt	(revision fab4ed0a8652390db0d41b8555ebdceb03b0b7c0)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/export/ExportDialogFragment.kt	(date 1734531790934)
@@ -77,6 +77,7 @@
     private lateinit var notesIncludeNotetypeName: CheckBox
     private lateinit var notesIncludeUniqueIdentifier: CheckBox
     private lateinit var cardsIncludeHtml: CheckBox
+    private lateinit var exportLegacyCheckbox: CheckBox
 
     override fun onCreateDialog(savedInstanceState: Bundle?): Dialog {
         val dialogView =
@@ -209,6 +210,10 @@
                 findViewById<CheckBox>(R.id.export_extras_collection_media).apply {
                     text = exportingIncludeMedia()
                 }
+            exportLegacyCheckbox =
+                findViewById<CheckBox>(R.id.export_legacy_checkbox).apply {
+                    text = exportingSupportOlderAnkiVersions()
+            }
         }
 
     /**
@@ -228,6 +233,9 @@
                 findViewById<CheckBox>(R.id.export_apkg_schedule).apply {
                     text = exportingIncludeSchedulingInformation()
                 }
+            exportLegacyCheckbox = findViewById<CheckBox>(R.id.export_legacy_checkbox).apply {
+                text = exportingSupportOlderAnkiVersions()
+            }
         }
 
     /**
@@ -274,6 +282,11 @@
         targetConfig: ExportConfiguration,
     ) {
         // if we export as collection there's no deck/selected items to choose from
+        if (targetConfig.layoutId == R.id.export_extras_collection || targetConfig.layoutId == R.id.export_extras_apkg) {
+            exportLegacyCheckbox.visibility = View.VISIBLE
+        } else {
+            exportLegacyCheckbox.visibility = View.GONE
+        }
         if (targetConfig.layoutId == R.id.export_extras_collection) {
             decksSelectorContainer.visibility = View.GONE
             selectedLabel.visibility = View.GONE
@@ -295,18 +308,20 @@
 
     private fun handleCollectionExport() {
         val includeMedia = collectionIncludeMedia.isChecked
+        val legacy = exportLegacyCheckbox.isChecked
         val exportPath =
             File(
                 getExportRootFile(),
                 "${CollectionManager.TR.exportingCollection()}-${getTimestamp(TimeManager.time)}.colpkg",
             ).path
-        (requireActivity() as AnkiActivity).exportCollectionPackage(exportPath, includeMedia)
+        (requireActivity() as AnkiActivity).exportCollectionPackage(exportPath, includeMedia, legacy)
     }
 
     private fun handleAnkiPackageExport() {
         val includeSchedule = apkgIncludeSchedule.isChecked
         val includeDeckConfigs = apkgIncludeDeckConfigs.isChecked
         val includeMedia = apkgIncludeMedia.isChecked
+        val legacy = exportLegacyCheckbox.isChecked
         val limits = buildExportLimit()
         var packagePrefix = getNonCollectionNamePrefix()
         // files can't have `/` in their names
@@ -322,6 +337,7 @@
             withDeckConfigs = includeDeckConfigs,
             withMedia = includeMedia,
             limit = limits,
+            legacy = legacy
         )
     }
 
Index: AnkiDroid/src/main/java/com/ichi2/anki/BackendExporting.kt
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/java/com/ichi2/anki/BackendExporting.kt b/AnkiDroid/src/main/java/com/ichi2/anki/BackendExporting.kt
--- a/AnkiDroid/src/main/java/com/ichi2/anki/BackendExporting.kt	(revision fab4ed0a8652390db0d41b8555ebdceb03b0b7c0)
+++ b/AnkiDroid/src/main/java/com/ichi2/anki/BackendExporting.kt	(date 1734530197865)
@@ -27,6 +27,7 @@
     withDeckConfigs: Boolean,
     withMedia: Boolean,
     limit: ExportLimit,
+    legacy: Boolean,
 ) {
     launchCatchingTask {
         val onProgress: ProgressContext.() -> Unit = {
@@ -35,7 +36,7 @@
             }
         }
         withProgress(extractProgress = onProgress) {
-            withCol { exportAnkiPackage(exportPath, withScheduling, withDeckConfigs, withMedia, limit) }
+            withCol { exportAnkiPackage(exportPath, withScheduling, withDeckConfigs, withMedia, limit, legacy) }
         }
         val factory =
             (this@exportApkgPackage as ExportDialogsFactoryProvider).exportDialogsFactory()
@@ -47,6 +48,7 @@
 suspend fun AnkiActivity.exportColpkg(
     colpkgPath: String,
     withMedia: Boolean,
+    legacy: Boolean,
 ) {
     val onProgress: ProgressContext.() -> Unit = {
         if (progress.hasExporting()) {
@@ -54,16 +56,17 @@
         }
     }
     withProgress(extractProgress = onProgress) {
-        withCol { exportCollectionPackage(colpkgPath, withMedia, true) }
+        withCol { exportCollectionPackage(colpkgPath, withMedia, legacy) }
     }
 }
 
 fun AnkiActivity.exportCollectionPackage(
     exportPath: String,
     withMedia: Boolean,
+    legacy: Boolean,
 ) {
     launchCatchingTask {
-        exportColpkg(exportPath, withMedia)
+        exportColpkg(exportPath, withMedia, legacy)
         val factory =
             (this@exportCollectionPackage as ExportDialogsFactoryProvider).exportDialogsFactory()
         val dialog = factory.newExportReadyDialog().withArguments(exportPath)
Index: AnkiDroid/src/main/res/layout/dialog_export_options.xml
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/AnkiDroid/src/main/res/layout/dialog_export_options.xml b/AnkiDroid/src/main/res/layout/dialog_export_options.xml
--- a/AnkiDroid/src/main/res/layout/dialog_export_options.xml	(revision fab4ed0a8652390db0d41b8555ebdceb03b0b7c0)
+++ b/AnkiDroid/src/main/res/layout/dialog_export_options.xml	(date 1734534160885)
@@ -32,6 +32,12 @@
             android:layout_height="wrap_content"
             android:checked="true"
             tools:text="Include media" />
+
+        <CheckBox
+            android:id="@+id/export_legacy_checkbox"
+            android:layout_width="match_parent"
+            android:layout_height="wrap_content"
+            android:checked="false" />
     </LinearLayout>
 
 
@@ -63,6 +69,12 @@
                 android:layout_width="match_parent"
                 android:layout_height="wrap_content"
                 android:checked="true" />
+
+            <CheckBox
+                android:id="@+id/export_legacy_checkbox"
+                android:layout_width="match_parent"
+                android:layout_height="wrap_content"
+                android:checked="false" />
         </LinearLayout>
 
 
`

**Comment by david-allison** [comment]
Sure!

**Comment by Haz3-jolt** [comment]
Sure! Got some other work for tomorrow, so might not be able to get to it immediately, but wanted something out so I can get feedback.

**Comment by david-allison** [comment]
No rush! Your time is greatly appreciated
