### ISSUE TITLE
Add 'Help' to "Reset Card Progress"

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17530]
We should link the manual

User was confused:

> What are meant by "original position," "repetition," and "lapse count?"
> <img src="https://github.com/user-attachments/assets/85caf593-8222-4c48-a3eb-85f05d59de76" height="400" />

https://www.reddit.com/r/Anki/comments/1h46igo/what_does_each_of_the_options_do_exactly/

**Comment by MorenoTropical** [comment]
Leave it to me!
