### ISSUE TITLE
Speech recognition to recognize answer

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1754]
Originally reported on Google Code with ID 852

```
By Max:
I wanted to share with you a quick spark of imagination. The last days i
stumbled over Android's SpeechToText-API and thought that this could be
basis for neat feature of Anki on Android. So instead of simply getting
shown the answer-side of a flash-card one may unlock it by saying the
answer. Anki could then check correctness of the answer etc.
Theres and API overview [1] and a demo [2], Japanese is supported as far as
i'm concerned. The regarding post on the developers blog [3]. I know that a
lot of design decision would have to be considered and that this would most
likely cluster Anki with respect to platforms -- quite undesirable.
```

Reported by `nicolas.raoul` on 2011-10-30 04:11:29

**Comment by kfowlks** [comment]
Has this feature been accepted? I'd like to up vote this one.

**Comment by JonathanLehner** [comment]
has someone implemented this?

**Comment by david-allison-1** [comment]
Enough +1s to show community interest

**Comment by krmanik** [comment]
This is simple implemention of speech recognition using Google Keyboard
1. Toggle `Type answer into card` in AnkiDroid advanced settings
2. Add `input` tag in front/back side of card template with following JS code
```html
<input id='stt_input' oninput="checkAnswer();"></input>

<script>
function checkAnswer() {
    let text =  document.getElementById("stt_input").value;
    if (text == "{{Back}}") {            // <--- change this for other fields in card template
        if (document.documentElement.classList.contains("android")) {
            ankiShowToast("Correct Answer");
        }
    }
}
</script>
```
3. During reviewing click mic button on GBoard and speak the answer
4. The GBoard will provide the text for the speech and JS code will show toast for correct answer.
5. Change language in GBoard for other language

Note: 
a) The words can be converted to lowercase for matching the answer. 
b) After ankiShowToast, other JS API can be used to show answer or set flag.
