### ISSUE TITLE
How can I have TTS read out dynamically generated text?

### ISSUE THREAD

**Issue by 102757017** [ankidroid/Anki-Android#17549]
My card will use queries to ChatGPT. How can I set up the Anki card template so that it can read out the text returned by GPT?

**Comment by BrayanDSO** [comment]
It can't.

I can't find the manual link right now, but Anki processes the TTS text before the card is shown, so anything after that (like dynamically generated content) will be ignored.

Please ask the feature first in the forums for the desktop version. If that's implemented there, we will also implement it here.

**Comment by DomoMKT** [comment]
"try converting your text into high-quality speech with extremely low latency at [www.nemesyslabs.com](https://www.nemesyslabs.com)!"
