### ISSUE TITLE
[BUG]: Cloze deletion cards completely messed up?

### ISSUE THREAD

**Issue by starcraft66** [ankidroid/Anki-Android#17542]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

I made a deck of cloze cards on Anki for Mac that has french verb conjucations on the front and multiple clozes on the back that reveal the translations of the conjugations in russian, one cloze per pronoun.

On Anki Desktop the cards work exactly as you'd expect but on Ankidroid, the front of the card is completely blank and the back just shows the markup without formatring it.![Image](https://github.com/user-attachments/assets/5012cadf-3031-44a7-88c3-36fbf076677b)
![Image](https://github.com/user-attachments/assets/7e526a4b-37b4-4317-ab08-0c5bb07409dd)
![Image](https://github.com/user-attachments/assets/537f86aa-0681-4e03-b6e0-2648876f3335)

### Expected behaviour

I expect the front to show my french conjugations and the back to show the russian ones with multiple clozes that can be revealed

### Debug info

```text
AnkiDroid 2.19.3
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
Hi, you'd get a faster response if you use our [Forums](https://forums.ankiweb.net/c/ankidroid/help/16) or [Discord](https://discord.gg/qjzcRTx) for user support [and supplied the card template data](https://www.youtube.com/shorts/KahBXFKUBKE)

If there is a bug/regression, we'll get to it ASAP

Thanks!

**Comment by starcraft66** [comment]
My bad, I misunderstood how cloze works, I got it all fixed thanks.
