### ISSUE TITLE
Whiteboard - drawing on the screen - card text flickering

### ISSUE THREAD

**Issue by pishutin84** [ankidroid/Anki-Android#17559]
When studying cards I just draw to check spelling. All last versions have this issue.
When I start drawing lines (curves actually), card text (no matter it's card side A or both sides A and B) keeps to dissappear and appear again depending on drawed line length. If the line short enough it just dissapears. If the line longer it appears again. When I draw something with several lines card text behaving like a lamp with loose wire - it flickering with every new screen touch.
I can see the issue for a while - maybe months. Don't remember exactly when it started.
Last version updated December still has the issue. AnkiDroid Flashcards 2.20.0.
Phone Xiaomi 13 Pro. HyperOS 1.0.10.0 (Android 14).

![Image](https://github.com/user-attachments/assets/96ca9084-6b7a-44a2-8ad6-24890dc92c72) ![Image](https://github.com/user-attachments/assets/1c883c2f-b9e3-4144-b61e-9d9b32007b13)

**Comment by mikehardy** [comment]
🤔 it would be helpful to know when it started - for original poster or anyone doing triage
You may install parallel builds of old versions from our releases page for testing

the general format of the page URL for a specific release is to just put the version number you want in there, for example, this is probably a v2.19 problem and maybe v2.18 works if it has been broken "many month" (but not "more than a year)

and last v2.18 release was https://github.com/ankidroid/Anki-Android/releases/tag/v2.18.4

but maybe https://github.com/ankidroid/Anki-Android/releases/tag/v2.17.6 from March?

**Comment by pishutin84** [comment]
Thank you.
So.
I uninstalled Play Store version and installed AnkiDroid-2.18.4-arm64-v8a.apk from the link provided.
The issue has gone.
But.
I installed Play Store version back and it is still gone.
Case can be closed :))

**Comment by mikehardy** [comment]
what !?!? 😆 that makes almost no sense but...if it's working on the current version then okay! Glad it's working :-)

**Comment by pishutin84** [comment]
no sense for me either. so I didn't even think to reinstall it. Just reported.
anyways. I reinstalled it 2 more times. Clear installation, default settings. Synchronization with my account.
Gone.
