### ISSUE TITLE
[BUG]: Android 15: Can't download shared decks [This isn't a valid Anki package file / 'deckname.bin']

### ISSUE THREAD

**Issue by thedroiddiv** [ankidroid/Anki-Android#17573]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Click on "Get shared decks"
2. Download any deck and try to import

https://github.com/user-attachments/assets/7950abce-c333-4cfd-9b48-52f542b72d2d

### Expected behaviour

Deck gets downloaded and imported successfully

### Debug info

```text
AnkiDroid Version = 2.21alpha1-debug (c7b499e62159391f549f73be9a24b2f8c41b4a3f)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 15 (SDK 35)

ProductFlavor = amazon

Manufacturer = Google

Model = Pixel 6a

Hardware = bluejay

Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel 6a Build/AP4A.241205.013; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.104 Mobile Safari/537.36

ACRA UUID = a432af50-f92f-44f9-979d-b10acb7ea920

FSRS = 1.4.3 (Enabled: false)

Crash Reports Enabled = false
```

### (Optional) Anything else you want to share?

```
10:04:11.845  D  Registering broadcast receiver for download completion
10:04:11.878  D  Download ID -> 982
10:04:11.879  D  File name -> Goethe_Institute_A1_Wordlist.bin
....
10:04:14.889  D  Stopping download progress checker
10:04:14.890  I  File does not have 'apkg' or 'colpkg' extension, abort the deck opening task
10:04:14.890  I  File is not a valid deck, hence return from the download screen
...
10:04:23.998  D  Registering broadcast receiver for download completion
10:04:24.024  D  Download ID -> 983
10:04:24.024  D  File name -> German_Federal_States__Deutsche_Bundeslnder.bin
10:04:24.025  D  Starting download progress checker
...
10:04:27.101  D  Stopping download progress checker
10:04:27.101  I  File does not have 'apkg' or 'colpkg' extension, abort the deck opening task
10:04:27.101  I  File is not a valid deck, hence return from the download screen
10:04:27.106  I  Back pressed when download is in progress, show cancellation confirmation dialog
```

When I downloaded the file from web using a browser, the downloaded filename had extension `.apkg` but when the file was downloaded from app, it had extension `.bin`

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
I had this reported today. Can't reproduce on my S21.

Is it feasible to get a copy of the `.bin` (if it doesn't contain anything sensitive such as AnkiWeb keys)?

**Comment by thedroiddiv** [comment]
@david-allison Here you go!

https://drive.google.com/drive/folders/1H_knlzV4zPki1liz6jJ9kIm6K-EeTHiq?usp=sharing

**Comment by david-allison** [comment]
@thedroiddiv Fantastic! That's an `apkg`

Is it feasible for you to test this line, to see the inputs and outputs:

https://github.com/ankidroid/Anki-Android/blob/e9fe00726a48f7d347081379de8cb2334fbd80a6/AnkiDroid/src/main/java/com/ichi2/anki/SharedDecksDownloadFragment.kt#L166-L170

**Comment by thedroiddiv** [comment]
```
12:21:02.332  D  URL: https://ankiweb.net/svc/shared/download-deck/293204297?t=<****>
                 MimeType: application/octet-stream 
                 ContentDisposition: attachment; filename=Goethe_Institute_A1_Wordlist.apkg
12:21:02.431  D  Download ID -> 989
12:21:02.431  D  File name -> Goethe_Institute_A1_Wordlist.bin
```

So, I believe this has to do something with `UrlUtils::guessFileName`

I'll try on an Emulator with API 35 and check if I'm able to reproduce.

**Comment by thedroiddiv** [comment]
I can confirm that the issue is only reproducible on Android API 35.

Works as expected on Android API 34 and 33.
Tested on Pixel 6a Emulators, API 33,34,35 and Pixel 6a Physical Device API 35

**Comment by david-allison** [comment]
Reported as https://issuetracker.google.com/issues/382864232

**Comment by criticalAY** [comment]
Again its Google🤷🤷

**Comment by thedroiddiv** [comment]
@david-allison Do you suggest we implement a work-around/hack, because currently import is broken for all devices running Android 15.

**Comment by david-allison** [comment]
@thedroiddiv already on it
