### ISSUE TITLE
git commit presubmit may lose data

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#17593]
How to reproduce:
* In a file A, change a local variable in all upper case
* in a file b, rename a variable, but keep the name valid for our linter
* `git add A; git commit -m test`

Actual result:
* Warning that the commit can't be done, and to read AnkiDroid/build/reports/ktlint/ktlintMainSourceSetFormat/ktlintMainSourceSetFormat.txt to find why
* B was reverted!!!!!!!!!!!

Expected result:
* A warning that commit failed
* A still committed, B uncomitted.

I wanted to add a first part of the work first, and then the big part of the work. I lost more than two hours of work. I was not expecting "git commit" to delete anything.

**Comment by Arthur-Milchior** [comment]
While trying to reproduce I read in more details the hook, and realized the change is saed in .git/unstaged-ktlint-git-hook.diff, and just discover that, by reproducing, I erased the backup that actually existed :'(

So I think that, if possible, we should apply the patch back. If not possible we should at least tell where the patch is, and maybe do a backup of it!

**Comment by david-allison** [comment]
Haven't been impacted by this due to my workflow 

Android Studio also has a "Local Changes" feature which preserves a second backup which you might want to try

**Comment by lukstbit** [comment]
Is this still an issue after #17595?

**Comment by Haz3-jolt** [comment]
> Is this still an issue after [#17595](https://github.com/ankidroid/Anki-Android/pull/17595)?
> 
> Edit: Hook failed when I tried to add the changes from a xml layout(no other kotlin file was modified):
> 
> _No Kotlin staged files. .git/hooks/pre-commit: 89: Syntax error: "fi" unexpected (expecting "then")_
> 
> Also happens when there are kotlin files involved:
> 
> _Completed ktlint run. Completed ktlint hook. .git/hooks/pre-commit: 89: Syntax error: "fi" unexpected (expecting "then")_


Hey I was actually facing this issue when cahnging the XML files in #17626 and when dealing wit shell scripts in #17629 , idk if what i did was correct, but i just rm the pre-commit files and it let it work.

**Comment by david-allison** [comment]
Should be closed

* https://github.com/ankidroid/Anki-Android/pull/17595

* https://github.com/ankidroid/Anki-Android/pull/17631
