### ISSUE TITLE
[BUG]: Reset progress don’t retain previous selection

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#17596]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Open ankidroid, open the reviewer
2. Review a card that is not new.
3. Tap the menu, select Reschedule > Reset progress 
4. Change the settings before tapping "ok"
5. Repeat 2 and 3

### Expected behaviour

The previous setting is saved. I know that I always want to reset reps and lapse counts, I don’t want to have to select it every single time.

### Debug info

```text
2.20.0
```

### (Optional) Anything else you want to share?

Contributors: please wait until another reviewer confirmed we’d accept such a change before working on it.
The bug can be easily resolved by solving the selected value in a preference.
Just, please, save it only when the user tap "ok". If the user decide to cancel, we don’t want to save it

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Aditya13s** [comment]
I started working on it.
