### ISSUE TITLE
[BUG]: Note editor shows Default deck for all cards

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#17604]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Open any note in the note editor.

### Expected behaviour

The note editor should show the deck in which the card is located. Instead, it shows the "Default" deck.

### Debug info

```text
2.21 alpha 2
```

### (Optional) Anything else you want to share?

Might be related to https://github.com/ankidroid/Anki-Android/issues/17603

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison** [comment]
@Arthur-Milchior 

* https://github.com/ankidroid/Anki-Android/pull/17591 => https://github.com/ankidroid/Anki-Android/commit/a58b4c10ed2f1db7dab9a3b7244cbf957b6915c7

```
a58b4c10ed2f1db7dab9a3b7244cbf957b6915c7 is the first bad commit
commit a58b4c10ed2f1db7dab9a3b7244cbf957b6915c7
Date:   Thu Dec 12 01:50:27 2024 +0100

    NF: uses protobuf simplified constructors
    
    While looking at the `Card` code, I decided to go over all
    `newBuilder`, and slightly improve the code everywhere.

 AnkiDroid/src/main/java/com/ichi2/anki/BackupManager.kt                  | 12 ++++++------
 AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DeckSelectionDialog.kt    | 11 +++++------
 AnkiDroid/src/main/java/com/ichi2/libanki/Card.kt                        | 55 +++++++++++++++++++++++++------------------------------
 AnkiDroid/src/main/java/com/ichi2/libanki/backend/model/SortOrderUtil.kt | 40 +++++++++++++++++++++-------------------
 AnkiDroid/src/test/java/com/ichi2/anki/BackupManagerSimpleTest.kt        | 12 ++++++------
 AnkiDroid/src/test/java/com/ichi2/anki/ThrowableFilterServiceTest.kt     | 10 +++++-----
 6 files changed, 68 insertions(+), 72 deletions(-)
```

**Comment by david-allison** [comment]
The bug is in:

```kotlin
+ fun currentDeckId() = deckId { did = oDid.ifZero { did } }
-  fun currentDeckId(): anki.decks.DeckId =
-        anki.decks.DeckId
-           .newBuilder()
-           .setDid(oDid.ifZero { did })
-           .build()
```

`did` uses the wrong value

**Comment by Arthur-Milchior** [comment]
My excuses
