### ISSUE TITLE
[BUG]: The "Hard" button sometimes reschedules the card too far into the future

### ISSUE THREAD

**Issue by blazern** [ankidroid/Anki-Android#17600]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [ ] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

I don't know exact steps - they seem to depend on how the scheduler (FSRS) is optimized (it's parameters).

But for me it reproduces when:
- I have a card added in the end of 2023
- The card is scheduled for today and is displayed to me
- I want to press "Hard" because I can barely remember the correct answer
- The "Hard" button reschedules for the moment 7 years in the future

Here's what it looks like:
<img src="https://github.com/user-attachments/assets/3a2bfa32-88e3-42c5-aa66-8a4e511b0b18" width="300" />

Here's card's info:
<img src="https://github.com/user-attachments/assets/0a5e14dd-0c5d-4d0f-8364-0d9bce1989ba" width="300" />

### Expected behaviour

I expected the card to be rescheduled for a few months in the future instead of 7 years, because if I can barely remember the card now, in 7 years I 100% won't be able to remember it.

### Debug info

```text
AnkiDroid Version = 2.20.0 (d41d16a45c00b0bdbd3b13ac988143db5ef8ae90)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 15 (SDK 35)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 8a

Hardware = akita

Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel 8a Build/AP3A.241105.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.135 Mobile Safari/537.36

ACRA UUID = 9866d38f-9a4c-4cd0-ad37-d1145e62668b

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true
```

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
If you have any problems with how FSRS works, please post it at the forums https://forums.ankiweb.net/c/anki/fsrs/19

**Comment by blazern** [comment]
Seems to be https://github.com/ankitects/anki/issues/3634

**Comment by brishtibheja** [comment]
@blazern It's probably not related to that issue. If you can come to https://discord.com/channels/368267295601983490/1282005522513530952 or https://forums.ankiweb.net someone can help.
