### ISSUE TITLE
[BUG]: Audio doesn't play automatically in 2.21alpha2

### ISSUE THREAD

**Issue by xiety** [ankidroid/Anki-Android#17617]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

Start studying the deck with "Don't play audio automatically" = **OFF** and front side with some audio: `[sound:1.mp3]`

No audio is played

(If you press the play button, the audio will play normally)

### Expected behaviour

Audio is played automatically

### Debug info

```text
AnkiDroid Version = 2.21alpha2 (0ea255d726ffc42d2b90f9eb9e7429cecf6b02c5)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 14 (SDK 34)

ProductFlavor = full

Manufacturer = samsung

Model = SM-A256B

Hardware = s5e8825

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-A256B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.135 Mobile Safari/537.36

ACRA UUID = 59d8b857-b962-4525-b5da-a6b983d15387

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

Works in 2.21alpha1

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by beirne** [comment]
I have the opposite problem. I have "Don't play audio automatically" turned on yet the audio plays automatically anyhow

**Comment by soCallmeAdityaKumar** [comment]
looking into this

**Comment by soCallmeAdityaKumar** [comment]
> Which version was this working on?

Found this on 2.21alpha2-debug

**Comment by david-allison** [comment]
@soCallmeAdityaKumar Please `git bisect` to find where this was introduced

**Comment by soCallmeAdityaKumar** [comment]
> > Which version was this working on?
> 
> reproduced this on 2.21alpha2-debug
can not reproduce this version

**Comment by david-allison** [comment]
@soCallmeAdityaKumar Are you using `git bisect`? https://stackoverflow.com/a/4714297/

**Comment by soCallmeAdityaKumar** [comment]
@david-allison yeah , i checked  between the commit 0ea255d7 and 253cb71e everything looks good

**Comment by beirne** [comment]
Here you go:

AnkiDroid Version = 2.21alpha2 (0ea255d726ffc42d2b90f9eb9e7429cecf6b02c5)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 15 (SDK 35)

ProductFlavor = play

Manufacturer = Google

Model = Pixel 8 Pro

Hardware = husky

Webview User Agent = Mozilla/5.0 (Linux; Android 15; Pixel 8 Pro Build/AP3A.241105.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.135 Mobile Safari/537.36

ACRA UUID = cb3248dc-7857-48dc-ad3a-62043849f6b2

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true

Wysłano z aplikacji Proton Mail

-------- Oryginalna wiadomość --------
18.12.2024 10:10 AM, Aditya kumar  napisał(a):

**Comment by david-allison** [comment]
Please post the output of `git bisect`, as was done: https://github.com/ankidroid/Anki-Android/issues/17604#issuecomment-2543812044.

Exclude the user email from the output

**Comment by xiety** [comment]
2.21alpha3 fixed this issue for me. Audio is played automatically now.
