### ISSUE TITLE
SQL Styleguide?

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#17659]
> I would have gone even further to improve the formatting for some of the sql strings(upper casing keywords, extra indentation).

_Originally posted by @lukstbit in https://github.com/ankidroid/Anki-Android/pull/17592#pullrequestreview-2503879858_

I agree with @lukstbit that the sql we have after my PR is still not great.

So my question is:
1. should we decide to introduce a styleguide for SQL?
2. if so which one?
3. How should we implement it?

I think it'd be nice to have an agreement. In case we ever add more SQL, or we touch the existing one, we'd know what to expect. 

For example
```sql
                    select 1 from cards where
                        (ord < 0 or ord >= ?)
                        and
                        nid in (select id from notes where mid = ?)
                      limit 1
```
is not really readable. 

But without a specific styleguide to follow, it's not clear to me what would have been a great way to reformat it. (Appart from using UPPER case for keywords)

Given that we have little SQL and probably will have less in the future, I don't think we should spend any time trying to add any tooling to enforce the styleguide. Unless someone knows how to do it very quickly implement this check.
I think it's a low priority, if someone has some time to spend doing a relatively simple task that does not require too much brain power. Or could be some cleaning done while we touch the code in this area.

If we decide that having a styleguide here makes sense, I guess we should follow upstream. It uses https://www.npmjs.com/package/@sqltools/formatter for formatting. Sadly, this tools does not state what styleguide it uses exactly.

Still, looking at examples of code in anki, it seems clear that  It seems to look like https://kvz.io/blog/sql-formatting.html without the 0 and 1.
This may not be very well specified, but honestly, I don't expect we'd ever have queries that are so complex that we can't guess what's this styleguide would imply

**Comment by david-allison** [comment]
Doesn't seem like a productive use of time when we have so many more pressing issues: 

* We run a risk of introducing bugs
* Most SQL should be moved to backend method calls, the longer we leave this, the less we have to do

In addition: JetBrains SQL highlighting is correctly broken in Android Studio, so we're also going to contend with IDE issues. 

A quick +1 on the following will probably be a valuable exercise

[KTIJ-24766 False positive "id, name or spec expected, got" in javascript language injection in IntelliJ Idea Community](https://youtrack.jetbrains.com/issue/KTIJ-24766)

**Comment by BrayanDSO** [comment]
The tendency is to use less and less SQL inside AnkiDroid and move to always using the backend. 

Personally, I never had to change any SQL string in AnkiDroid until now.

**Comment by david-allison** [comment]
Proposing closing this based on the above
