### ISSUE TITLE
Privacy Policy: Explain API access

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#17658]
https://github.com/ankidroid/Anki-Android/wiki/Privacy-Policy

**Comment by mikehardy** [comment]
should just be something short and simple like "AnkiDroid uses a specific AnkiDroid API permission to allow or disallow other apps to access the collection stored on your device via the AnkiDroid API. By default this permission is disabled. This permission may be changed in the system permissions settings for AnkiDroid."

**Comment by anandkaranubc** [comment]
@mikehardy Can you please confirm if it looks ok? Thanks!

**Comment by mikehardy** [comment]
@anandkaranubc 

> @mikehardy Can you please confirm if it looks ok? Thanks!

Confirm if what looks okay? There is no link to anything so I'm not sure what to confirm

**Comment by anandkaranubc** [comment]
> [@anandkaranubc](https://github.com/anandkaranubc)
> 
> > [@mikehardy](https://github.com/mikehardy) Can you please confirm if it looks ok? Thanks!
> 
> Confirm if what looks okay? There is no link to anything so I'm not sure what to confirm

Sorry, I just updated the `https://github.com/ankidroid/Anki-Android/wiki/Privacy-Policy` page which was mentioned above. Thanks for your time!

**Comment by mikehardy** [comment]
Looks good to me? But I suggested the original text so of course I would say that ;-)

I organized the page a little now that we have 4 different things there - I added headings and I altered wording a bit here and there

If anyone else wants to edit it please feel free - here's the section about API access: https://github.com/ankidroid/Anki-Android/wiki/Privacy-Policy#optional-on-device-api-access-in-ankidroid

And you can see my whole edit here if anyone is curious - https://github.com/ankidroid/Anki-Android/wiki/Privacy-Policy/_compare/26cf74c89c27d7e1e4082f2baa9cf8a1a98fd1de...acd9ca30689e97ffef8c3260de9b55038d6b8fb6

I'm going to close this as I personally think it is handled now (thank you @anandkaranubc !) but it's a wiki, anyone may go in there and improve it. Do your best if you are motivated, cheers

**Comment by david-allison** [comment]
>> should just be something short and simple like "AnkiDroid uses a specific AnkiDroid API permission to allow or disallow other apps to access the collection stored on your device via the AnkiDroid API. By default this permission is disabled. This permission may be changed in the system permissions settings for AnkiDroid."

> By default this permission is disabled. 

Is this true? 

https://github.com/ankidroid/Anki-Android/blob/3ea27c9fe4d7378d11943fc96d0a318b4ae9d0b6/AnkiDroid/src/main/AndroidManifest.xml#L655-L663

**Comment by mikehardy** [comment]
@david-allison yes it is true, the provider is always available but it requires the permission and that permission has to be granted for each app, in *that* app's settings.
