### ISSUE TITLE
Inconsistent Widget Styling

### ISSUE THREAD

**Issue by Aditya13s** [ankidroid/Anki-Android#17656]
<p height="200">
  <img src="https://github.com/user-attachments/assets/ef10cf4a-4090-475e-816e-d22bb2cb1c2b" height="420px" />
  <img src="https://github.com/user-attachments/assets/8d865475-5da9-4170-88cf-17a535206ccd" height="420px" />
</p>

Currently, the first widget uses dynamic system colors and lacks corner rounding. The second widget has corner rounding, adapts to light/dark mode, and has a more polished design.

## Expected Behavior:
The first widget should be updated to match the second widget's design:
- Add corner rounding to the first widget.
- Ensure the first widget adapts to light/dark mode, just like the second widget.

This will ensure consistency in design across both widgets.

**Comment by MinusMallard** [comment]
Actually, not only this, but the widget size has also been bothering me for quite some time. If you have a phone that has more than 4 columns on the home screen, the deck widget cannot be expanded to the full width of the display. Also, the height of the widget is inconsistent; it supports more than 2 height rows in portrait mode, which is fine, but as we can only select five, extra space goes to waste; either you miss some text or you have to leave some extra space. But these problems can only be specific to me, as I use custom scaling on my home screen to accommodate more apps; only if someone could verify that; also, in landscape mode, if I increase the width of the widget, the padding between numbers also increases, which starts to look very ugly. But again, this could only be because of my phone.

**Comment by Aditya13s** [comment]
@MinusMallard can you share an image or a video of the issue.

**Comment by xenonnn4w** [comment]
> Add corner rounding to the first widget.

Did a investigation and observed the following:

- On Samsung devices and the Pixel 5 emulator, both widgets display rounded corners.
- On Motorola devices, both widgets have square corners.
- On OnePlus devices, the Deck Picker widget is rounded, while the Card Analysis widget is square.
The likely reason for these discrepancies is that third-party launchers and device manufacturers can override the `system_app_widget_background_radius` parameter, which controls the corner radius. 

Solution : 
Tried this `system_app_widget_background_radius `attribute but it's not resolving, so i gave a quick try to custom drawable resources with rounded corners (rounded_background.xml ) for the widget's background. That worked :D , but below API<31 it behaved not the exact same way ( haha two corners were rounded while the others were not ) ; need more investigation here.

| Device/Scenario        | Image                                                                 |
|-------------------------|----------------------------------------------------------------------|
| Samsung | <img src="https://github.com/user-attachments/assets/0f5813a9-acc8-4472-8873-1b323323fa42" alt="Samsung or Pixel 5 Emulator" width="150"/> |
| Motorola Device         | <img src="https://github.com/user-attachments/assets/6aa48504-ff38-48ed-877d-601d3c6b079d" alt="Motorola Device" width="150"/> |
| Emulator        | <img src="https://github.com/user-attachments/assets/1d91a7ef-794b-4b23-865b-9a6bd5edfe97" alt="OnePlus Device" width="150"/> |

**Comment by xenonnn4w** [comment]
> Ensure the first widget adapts to light/dark mode, just like the second widget.

Apologies, I didn’t fully understand your point about 'dark mode.' From the perspective of dynamic colors, both widget already incorporates darker shades.

**Comment by xenonnn4w** [comment]
> Actually, not only this, but the widget size has also been bothering me for quite some time. If you have a phone that has more than 4 columns on the home screen, the deck widget cannot be expanded to the full width of the display. Also, the height of the widget is inconsistent; it supports more than 2 height rows in portrait mode, which is fine, but as we can only select five, extra space goes to waste; either you miss some text or you have to leave some extra space. But these problems can only be specific to me, as I use custom scaling on my home screen to accommodate more apps; only if someone could verify that; also, in landscape mode, if I increase the width of the widget, the padding between numbers also increases, which starts to look very ugly. But again, this could only be because of my phone. I just checked on widgets, and the issues you have mentioned aren't there in my version of app, corners are nice and round.

Hey, Thanks for using the widget and the feedback :>. Exactly, the extra padding or missing text is primarily due to scaling. It looks perfect on some phones but shows minor issues on others. It definitely needs further refinement.
