### ISSUE TITLE
[BUG]: Input box not working in 'type answer' cards

### ISSUE THREAD

**Issue by arebla** [ankidroid/Anki-Android#17671]
### Checked for duplicates?

- [x] This issue is not a duplicate

### Does it also happen in the desktop version?

- [x] This bug does not occur in the latest version of Anki Desktop

### What are the steps to reproduce this bug?

1. Create a _Basic (type in the answer)_ card.
2. Review the card.

### Expected behaviour

What happened:

- When reviewing the card, I encountered a [[Type:Pinyin]] string instead of the input prompt:
![Image](https://github.com/user-attachments/assets/88763e50-774a-4428-bc37-0e085cc96fee)

What should have happened:

- A  “…​…​” prompt appears in place of `{{Type:Pinyin}}`, and a text input box is shown at the bottom.

### Debug info

```text
AnkiDroid Version = 2.20.1 (e32a82c33646807ea19623c9c88be38965bc07e6)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 10 (SDK 29)

ProductFlavor = play

Manufacturer = Xiaomi

Model = Redmi Note 7

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi Note 7 Build/QKQ1.190910.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/131.0.6778.135 Mobile Safari/537.36

ACRA UUID = 7404fdcd-8fae-450c-87e0-0a2c7b7302fa

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true
```

### (Optional) Anything else you want to share?

- This bug only occurs in the reviewer, the previewer displays the card correctly:
 ![Image](https://github.com/user-attachments/assets/9c1530b4-14d3-45a6-868a-5c0df65168ab)
- I have another device running Android 9 (SDK 28) with the same AnkiDroid build, but I cannot reproduce this bug on it.

### Research

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by BrayanDSO** [comment]
You are using the new reviewer, and the message above it is pretty clear:

![Image](https://github.com/user-attachments/assets/9c53f645-62eb-40bd-a83a-acfa284d5d3a)

And I really mean the part of `Don't create reports about them`. There are stuff that simply weren't implemented yet, hence why the warning. I'm here spending time closing this issue instead of developing.

And FWIW, type in the answer cards are already implemented in the latest alpha. Download it from the GitHub releases page if you want to use it.
