### ISSUE TITLE
Arabic reshaper is missing a letter

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1785]
Originally reported on Google Code with ID 883
```
Hey,

referring to this issue: http://code.google.com/p/ankidroid/issues/detail?id=477 we
were asked to post some recognized problems.

First of all, I like your work and the possibility to have Arabic flash-cards, but
I still found some small issues. One letter, the 'hamza', is missing. For example the
word "water" should look like this: ماء but instead you sea: ما

There is no reshaping/concatenation for hyphens. There are used to show some more space
between letters without loosing concatenation of the whole word.

Have a nice day
```

Reported by `scheunem` on 2011-12-01 00:37:44

**Comment by edebeat** [comment]
I suggest that this bug gets closed. In the beginning Android didn't support the Arabic language very well. I guess the mentioned problem had to to with that. With today's Android versions this problem should be gone. I can't reproduce this bug on my phone (using Android 4.4.2).

**Comment by hssm** [comment]
The reshaper only takes effect on Android 2.2, and you need to enable it in the settings. We can close it once we drop support for Android 2.2 or someone fixes this problem upstream (we are using https://github.com/agawish/Better-Arabic-Reshaper/ for this).

**Comment by hssm** [comment]
We stopped supporting this in 2.5.
