### ISSUE TITLE
Convert Kanjis to furigana automatically

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1857]
Originally reported on Google Code with ID 955

```
Like Kakasi does for Anki Desktop.

We need to find/test a kanji to kana converter, either library or online API.
http://stackoverflow.com/questions/8904249/kanji-to-romaji-converter-java-open-source
```

Reported by `nicolas.raoul` on 2012-01-18 02:14:24

**Comment by luane91** [comment]
Hi, any update on this issue?

**Comment by mikehardy** [comment]
no one has actually done anything, so, no. If anyone wants to propose a solution, we can consider it, until then, this won't go anywhere
