### ISSUE TITLE
Hide decks with no due cards (deck picker)

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1902]
Originally reported on Google Code with ID 1000

```
By konnmatt:
I use more than 80 decks. I BEG YOU to add the feature of hiding decks with no-repetitions
(0 rep to do) for actual day!
```

Reported by `nicolas.raoul` on 2012-02-07 10:11:16

**Comment by mikehardy** [comment]
There is only one way to get to the options for a deck, and it is through the deck picker, so this would make it impossible to configure the hidden decks. I could see maybe sorting the decks but that'd be a different request.
