### ISSUE TITLE
Export facts to CSV

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1913]
Originally reported on Google Code with ID 1011

```
Export facts to CSV, so that they can easily be used in other software.
```

Reported by `nicolas.raoul` on 2012-02-14 06:48:36

**Comment by TarekkMA** [comment]
I will be working on this after #8196 and #8159 get merged

**Comment by n1snt** [comment]
I guess this can be closed now. @david-allison

**Comment by david-allison** [comment]
Thanks!
