### ISSUE TITLE
Lint: solve detected problems

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1937]
Originally reported on Google Code with ID 1035

```
Android Lint is a new tool introduced in ADT 16 (and Tools 16) which scans Android project
sources for potential bugs.

I attach the output for AnkiDroid.

The "errors" are actually not real problems, in my opinion (Ex: Error: Locale fi is
missing translations for: ankionline_sign_up_url, ...)

Let's try to solve what can be solved.
In a wonderful world, we might even be able to integrate Lint in the release script.
```

Reported by `nicolas.raoul` on 2012-03-05 11:00:03

**Comment by mikehardy** [comment]
My thinking on this is similar to #1266 - you can integrate anything with a build system, and static analyzers are a favorite, but without a concrete idea of how to make it a sustainable process, working through lint issues one time is clearly uninteresting for more than 3  years ;-)
