### ISSUE TITLE
Automatic or semi-automatic sync

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1964]
Originally reported on Google Code with ID 1062
```
I would propose a function to automatically pop up a message box to automatically sync
with OK button, NO button, LATER button.

OK means sync right away
NO means no
LATER will make the function run again after x minutes

thank you.  perhaps a voting system can be implemented so we can vote which is important
to be implemented
```

Reported by `peter733` on 2012-03-15 09:28:00

**Comment by timrae** [comment]
Fixed in #900

**Comment by dburt** [comment]
:+1: well done @hssm 

I was just coming to suggest this feature this morning.

A thought I had that might be an improvement is that by default on startup only Anki could check if sync data is available from upstream based purely on timestamps (this should be quick and low bandwidth and low on server resource demand) and could use a notification to unobtrusively warn the user.

What do you think, who have done so well on this issue in the last week?

**Comment by hssm** [comment]
For the record I had nothing to do with this. My name is just plastered over everything since we used my account to migrate the issue tracker yesterday. You can thank @x-ji for implementing this.

**Comment by dburt** [comment]
@hssm thanks for that migration, then!

And thanks @x-ji and @timrae for the help and merge.

What about my idea of checking for available updates by default: is it even possible with the sync server?

**Comment by timrae** [comment]
AFAIK that's already part of the sync protocol.

**Comment by x-ji** [comment]
I think currently if there's no change it won't initiate the sync process, and will instead just say "no changes found"?

**Comment by dburt** [comment]
@x-ji that's right, that's how `sync()` currently works, but if there are changes, `mSyncListener` will either show a dialog of some kind (depending on various factors) or start syncing straight away. We don't want that in auto mode because of data usage and maybe other reasons. Automatic check for updates only would need an alternative sync mode which only checks. Ideally, the user would only be notified if there were changes, whether by notification or just by dialog.

**Comment by timrae** [comment]
> We don't want that in auto mode because of data usage and maybe other reasons.

It sounds like you're describing a separate feature... "Notify when there is unsynced data" (i.e. without actually syncing)? So far we just focused on automatic syncing on app start/close.

I like your idea a lot actually! We could check for changes in a background thread and show a Snackbar with sync button which can be swiped off screen when there are changes.

**Comment by timrae** [comment]
I released a new alpha version anyway with the automatic sync

**Comment by dburt** [comment]
Yes, it is different enough to be considered a separate feature, and you've implemented something discrete and useful enough to make it less urgent.

I'm glad you like the idea. The key advantage I see in it is that you can turn it on by default and it will help users and not annoy them. You could even say,

"There is unsynced data at the server. Would you like to sync now?
Yes | No | Always | Never"

with the latter two options changing the relevant options, never = never check; always = auto-sync.
