### ISSUE TITLE
Use Forvo native pronunciation instead of TTS when possible

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#1994]
Originally reported on Google Code with ID 1092

```
Forvo is a collaborative effort to record native people speaking all words.

It could be used for a given card, if this card's word (or sequence of words) is present
in the Forvo database.
They don't have only words, but expressions and small sentences too. See for instance:
http://www.forvo.com/search/de%20rien/

At first use, the user would be prompted for her own API key (free to get on Forvo
website).

User could choose to either:
- always use the highest rated recording
- use a random recording, to train at recognizing the word rather than train at recognizing
the sound

The entire feature would be an opt-in option, as some people could object to the high
bandwidth usage.
```

Reported by `nicolas.raoul` on 2012-04-05 13:49:07

**Comment by Troyciv** [comment]
there is a pull request in the awesomeTTS repository that claims to use the API key from the forvo app to make it work. [link](https://github.com/AwesomeTTS/awesometts-anki-addon/pull/10)

**Comment by mikehardy** [comment]
> there is a pull request in the awesomeTTS repository that claims to use the API key from the forvo app to make it work. link

The problem with that approach is pointed out in the issue you linked - notably, ethics: https://github.com/AwesomeTTS/awesometts-anki-addon/pull/10#issuecomment-344121923

If there was a pull request for AnkiAndroid which let you specify the user key, this could be possible but it isn't okay to use forvo without paying for it according to their available plans: https://api.forvo.com/
