### ISSUE TITLE
Support for fora dictionary

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2143]
Originally reported on Google Code with ID 1241

```
The dictionary has a Send.. function that AnkiDroid already accepts.
A bit more formatting on the received information is needed.
```

Reported by `inigo.aldana` on 2012-07-20 22:35:50

**Comment by mikehardy** [comment]
@timrae I don't think there's much we can do here. Fora is a separate dictionary app, and if they use the send Intent to send to Anki we can only do so much with the formatting, and there are no specific formatting requests here (to see if they are sensible for everyone). And there's an API integration if Fora wants to implement it, so...
