### ISSUE TITLE
Selective sync of decks.

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2168]
Originally reported on Google Code with ID 1266

```
Please explain your idea here.

When I sync in akidroid 2.0beta9, it downloads all the decks to my phone. And I don't
want them to be all on the phone. Some have a lot of media and takes space on my phone,
and I feel guilty for the extra, useless bandwith taken from the ankiweb servers.


This feature is available on the 1.x series of ankidroid (I think).
```

Reported by `abijr.mtz` on 2012-07-29 08:02:11

**Comment by palashman** [comment]
Hello! Let me rearise this issue.
As you can see below, peoples are under **tortures** without this feature
 _https://www.reddit.com/r/Anki/comments/5o3vch/for_the_love_of_god_allow_users_to_choose_which/
https://www.reddit.com/r/Anki/comments/41sqye/downloadingsyncing_only_certain_decks_to_my_phone/
https://groups.google.com/forum/#!topic/anki-android/-IIMJEQcq_I_
and etc ...

Maybe one day it will be possible to implement asked feature.
Thank you in advance!

**Comment by mikehardy** [comment]
There is basic support for multiple profiles here (I use it, it works) https://github.com/ankidroid/Anki-Android/issues/2545

If anki desktop doesn't do it (selective sync) it won't be implemented here. profiles is the ticket
