### ISSUE TITLE
Unmounting extsd brings AnkiDroid to error screen

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2244]
Originally reported on Google Code with ID 1342

```
What steps will reproduce the problem?
1. Have the collection in the standard place, /mnt/sdcard/AnkiDroid
2. Have a memory card mounted at /mnt/extsd
3. Review in AnkiDroid
4. In the Android settings, unmount the extsd
5. Go back to AnkiDroid

What is the expected output? What do you see instead?
AnkiDroid should not care about the disappeared extsd.
Instead, you get the blue error screen with "SD-Karte ist nicht eingebunden." (in German).
Something like "SD card not mounted."


Does it happen again every time you repeat the steps above? Or did it
happen only one time?
Every time.

What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title)
On what version of Android? (Home screen > menu > About phone > Android
version)

AnkiDroid 2.0.beta16
Android 4.0.3

(...)


Please provide any additional information below.

From the error screen, when you click on the "back" button in the bottom left, AnkiDroid
recovers. Still, i guess there is no need for this screen at all.
```

Reported by `ospalh` on 2012-08-25 17:15:52

<hr>
- _Attachment: [bildschirmfoto(1).jpg](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-1342/comment-0/bildschirmfoto%281%29.jpg)_

**Comment by mikehardy** [comment]
I still see sdcard unmount/remount stack traces show up in ACRA

**Comment by mikehardy** [comment]
I just proposed #5049 which contains protection for this - when we receive the "unmount sdcard" intent, we then attempt to ...access the sdcard and crash if there are problems (even though we may be too late). Now we just log if there is a problem.

**Comment by mikehardy** [comment]
After #5049 was merged I'm going to mark this closed. If this shows up for anyone using a version later than 2.9alpha46 please send crash feedback and reopen with debug info
