### ISSUE TITLE
Select multiple cards in the card browser

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2339]
Originally reported on Google Code with ID 1437

```
It would be useful I think if you were able to select multiple cards in the card browser
so that you could (un)suspend, or delete, or whatever, 100 cards at once, instead of
having to long click on each one which takes a while :)
Maybe when in the card browser, you press the meny key, and in the list that shows
up (Undo, Add note, Change CardBrowser field (-should that have a space in or not??)..
and so on), there could be an item that is multi select, and then you can tap multiple
cards and they stay selected. Maybe long pressing or one of them will trigger the properties
for all of them, or maybe once multiselecting, you would have to press menu again and
select the action from there.

I tried to search if this idea was said before, but I could not find it. Thanks!
!
```

Reported by `woof.addict` on 2012-10-20 13:12:08

**Comment by dotancohen** [comment]
An Ankidroid user in my office today expressed interest in this feature.

**Comment by chickendude** [comment]
I've been looking into this today but the little progress bar that pops up when loading the cards in the card browser keeps restarting unless i scroll to the bottom, in which case it keeps throwing a "java.util.concurrent.CancellationException" exception. It works fine on my actual phone though, is it just an issue with the emulator (API 24)? The latest version in master also does this.

This is my fork:
https://github.com/chickendude/Anki-Android

Long-clicking an item brings up the check boxes, suspending, marking a note, and previewing (a single note) appear to work fine, deleting a note seems to still have some issues that i'm trying to iron out. Also, suspending notes was a bit more complicated than i thought (`case R.id.action_suspend_card` in onOptionsItemSelected) and is pretty slow. There are also a few strings which should probably be added with plural forms like "Suspend card**(s)**", "Mark card**(s)**", etc. and maybe having a preview icon rather than having to access the menu.

I'd be happy to continue working on it if you think it's usable, it's my first time contributing to another project, so not sure what to expect.

**Comment by timrae** [comment]
Hi sorry for the slow response. Thanks a lot for working on this.

How about just calling [`setChoiceMode(ListView.CHOICE_MODE_MULTIPLE_MODAL)`](https://developer.android.com/reference/android/widget/AbsListView.html#setChoiceMode(int))? This will highlight the item in the ListView, and bring up a special contextual action bar for handling the selected items. You can see an example [here](https://github.com/ankidroid/apisample/blob/master/app/src/main/java/com/ichi2/apisample/MainActivity.java)

The advantage of such an approach is that we don't need to add our own checkboxes to the layout, or manage when they are / aren't shown, etc.

**Comment by timrae** [comment]
Launching a new `DeckTask` for each card / note that you want to suspend/delete is always going to be very slow as each task will make its own database update. You'll want to instead pass in a list of ids that you want to apply the action to.

Libanki already has the functions [suspendCards()](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/Sched.java#L2066) function,  and [remNotes()](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L532) which are optimized for bulk actions, so you'll probably need to change the arguments you pass into the task to use arrays (or alternatively make new tasks to handle these bulk actions).

**Comment by timrae** [comment]
So [here](https://github.com/chickendude/Anki-Android/commit/c456a81d59f15fdd6cd8501341da04462731e90f#diff-880c932c6244230c1c7d8034d6525cadR746) you'd want to change this

```java
for (int cardPosition : mCheckedCardPositions) {
    final Card card = getCol().getCard(Long.parseLong(getCards().get(cardPosition).get("id")));
    deleteNote(card);
    DeckTask.launchDeckTask(DeckTask.TASK_TYPE_DISMISS, mDeleteNoteHandler,
            new DeckTask.TaskData(new Object[]{card, Collection.DismissType.DELETE_NOTE}));
}
```

to move the `DeckTask.launchDeckTask()` outside the loop

**Comment by timrae** [comment]
What editor are you using for working on this? It's kinda screwing up all the indentation, shifting things around and mixing spaces with tabs which makes it harder to review. This shouldn't happen if you import the project directly into Android Studio, which I highly recommend.

**Comment by timrae** [comment]
By the way, I noticed that you're committing directly to the master branch which is generally a bad idea as you'll start getting merge conflicts all over the place. Please have a quick read of the [git workflow section](https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#git-workflow) of the wiki. Let me know if you have any questions about the code or git!

**Comment by chickendude** [comment]
No worries, and thanks for all the help! I didn't know about that ListView mode, that'd be helpful indeed! I'm working in Android Studio but i generally work with tabs, so that's probably where the issues came up. I'll switch it over to spaces for this project and see if that helps. I'll also switch into a branch, should i delete the fork and restart it all in a new branch?

**Comment by timrae** [comment]
Deleting isn't necessary, just do
`git checkout -b browser-multiselect`

and then reset your master to upstream/HEAD

**Comment by chickendude** [comment]
Great, thanks! I think i've got everything back to normal in my master branch and the changes pushed over into the browser-multiselect branch. I'll work on implementing your suggested changes and then i'll get back to you here.

**Comment by tobia** [comment]
Any news on this? Is anybody still working on this feature?

**Comment by chickendude** [comment]
Hey @timrae, I've been looking at this again, it seems the `ListView.CHOICE_MODE_MULTIPLE_MODAL` setting as well as `ListView.setMultiChoiceModeListener` were added in API 11, and the current minimum is 10, which i believe is why i opted for manually setting it up to begin with. Alternatively we could only support multi-selection for API >=11 (probably close to 100% of the userbase anyway). I'm currently taking another look at the DeskTask to move the DeskTask call outside of the loop and only have one single call.

**Comment by chickendude** [comment]
So what would you say is the best way to pass in an array to the DeckTask? The current DeckTask code just accepts a single card, so i thought perhaps of adding a new task type, such as `TASK_TYPE_DISMISS_MULTI` which would call a new method "doInBackgroundDismissNotes(params)" to pass in an array of ids to the remNotes method, but there doesn't appear to be a method to handle bulk-updating the undo, but that is just an ArrayList, right? I've pushed a [first commit](https://github.com/chickendude/Anki-Android/commit/c341332a6db74125bc1fa6dc43d1a57843b9e3fb) to handle deleting multiple notes at once. I haven't updated marking/suspending yet.

**Comment by timrae** [comment]
> the current minimum is 10

The [current minimum is 14](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/build.gradle#L10)... Maybe you need to rebase?

**Comment by timrae** [comment]
> The current DeckTask code just accepts a single card, so i thought perhaps of adding a new task type

If you need to add a new task type feel free... Don't worry too much about implementation details for now, we can go through that during code review.

**Comment by vrublack** [comment]
Any progress on this? I'd look into this if nobody's currently working on it, maybe by working on @chickendude 's fork. I think it would be a really useful feature.

**Comment by mikehardy** [comment]
> Any progress on this? I'd look into this if nobody's currently working on it, maybe by working on @chickendude 's fork. I think it would be a really useful feature.

I haven't seen anything on this since Tim's comments on Feb 23 but I'd like this too - it is a feature the desktop has that I do use

**Comment by vrublack** [comment]
Okay I made [some fixes](https://github.com/vrublack/Anki-Android/commits/browser-multiselect) and will work on it more during the next days hopefully.

**Comment by vrublack** [comment]
I've implemented everything and will make a pull request. Now, mark, suspend, delete and change deck work for multiple selected items (as far as I've tested).

**Comment by chickendude** [comment]
@vrublack Nice work! I got a bit side-tracked and seems i missed Tim's comment, thanks for finishing this up! I saw your message last week, just had time now to stop by and see you've already finished! I'll take a look at it this weekend (or earlier if i can find the time) to double-check things are working as planned.

**Comment by timrae** [comment]
Out now in 2.9alpha24! Thanks so much to @vrublack for his dedication to getting this across the finish line and to @chickendude for getting it started!

**Comment by BrucePlumb** [comment]
Any progress on selecting multiple non-contiguous cards or notes in the browser? My current work around is to use the marked tag exclusively for this. Using the toggle-marked menu item is only slightly slower than simply clicking on a card. After marking all the desired card, choose the marked tag, then select all the cards. Works quite well.

**Comment by david-allison-1** [comment]
What UX would you expect here for selecting non-contiguous cards?

**Comment by BrucePlumb** [comment]
(Sorry, I don't know the meaning of "UX") The TagSelectorV2 add-on would be useful for this except it doesn't work inside the browser. What is the most efficient way of selecting several separate cards?
