### ISSUE TITLE
Opus audio support

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2387]
Originally reported on Google Code with ID 1485

```
It would be nice to have Opus audio (http://www.opus-codec.org/) support as it performs
very good, especially at low rates.
```

Reported by `wojtek.kapcia` on 2012-11-19 10:09:00

**Comment by aphirst** [comment]
It's currently not possible to open Issues on the Anki Desktop github page. Where should we report this, or conversely, check whether this is on the development cards there?

**Comment by timrae** [comment]
https://anki.tenderapp.com
