### ISSUE TITLE
Implement undo in card browser

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2463]
Originally reported on Google Code with ID 1561

```
The undo menu item is currently either disabled or does not do anything.
It is commented out in the code. It should be properly implemented.
```

Reported by `flerda` on 2013-01-05 23:40:18

**Comment by timrae** [comment]
When this is implemented, we can also remove the delete confirmation #3928

**Comment by timrae** [comment]
We removed the ability to undo note edits in https://github.com/hssm/Anki-Android/commit/564a8535801ba7c2306c2c1f658a93cbc242fabb, but if this PR is implemented we should consider whether or not to add it back in.
