### ISSUE TITLE
Crop/edit image before adding to a note

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2554]
Originally reported on Google Code with ID 1652

```
Let the user select a part of an image, instead of using the whole image.
```

Reported by `nicolas.raoul` on 2013-01-30 03:54:16

**Comment by tinyhappysteps** [comment]
Added a bounty: 
https://www.bountysource.com/issues/29271594-crop-edit-image-before-adding-to-a-note

Request:
1/ when take photo or select from gallery, allow crop
2/ also resize function (in settings or elsewhere) so huge photos aren't uploaded

Thanks

**Comment by mikehardy** [comment]
Looks like it would be a second pass after the image capture intent where we send the image back through a "Action.EDIT" intent attempt

If such a feature were implemented:

-  should it just become part of the default image capture flow? Just push all image capture through this phase?
-  I could see it starting as an advanced / incubating feature with a pref for "yes I want to edit images post capture"

I can see the need for this as sensors generate multi-megabyte files these days which makes camera capture pretty useless without the ability to shrink them.

- I could see an optional second "auto scale" type function where you set a maximum X and Y size and it scales the image down to the largest of the two maximum dimensions

**Comment by dezorianguy** [comment]
Can somebody implement that ? Any way to crop and resize any picture that is added to a card ?

**Comment by mikehardy** [comment]
"somebody" in an open source project could be "you" :-). 

https://github.com/ankidroid/Anki-Android/wiki/Contributing

**Comment by dezorianguy** [comment]
Thanks. How did my plea go?

**Comment by mikehardy** [comment]
core developers busy on other things at the moment and no one else indicated interest as of yet. Best workaround is to capture with camera and edit outside ankidroid, the pick the image from the gallery in anki. More taps, but does work

**Comment by mikehardy** [comment]
This may be a source of WebView crashes as well - rendering huge images resized into small WebViews. Unsure if that's true or not but it's one of our top crashes at the moment and this information is from a Chromium developer, so this may have more urgency https://bugs.chromium.org/p/chromium/issues/detail?id=916779#c15

**Comment by mikehardy** [comment]
Adding my current thinking on this, as used in a reply to a possible developer:

This is a common feature request, and image capture is definitely an area that needs improvement as cameras on phones generate such large images now that storing them directly is impractical and leads to other problems.

I see two needs - 

1- warn a user when they are about to save an image that is over a certain size
2- allow the user to edit an image with an easy flow from AnkiDroid


We also have a problem though - we have very limited development resources to maintain AnkiDroid, much less create new features, so every new feature needs to be as simple to maintain as possible or we can't accept it as we won't be able to maintain it in the future

When I combine the needs and the problem to think about a solution, I think something that relies most heavily on external applications is the way forward as image processing is not something core to the app and it is implemented well in free applications. Even using image codecs to try to determine image sizes can be problematic if our experience with audio codecs and files is any indication!

So I think a solution that could be merged would be something like:

1- a dialog box after image capture that asks the user if they want to edit the image or use it as is. If they want to edit it, we should send a standard system intent for image editing, and we should use whatever result comes back. This will avoid having image-processing code in AnkiDroid but should still provide a smooth user experience

2- a preference (with a sensible default) that simply checks the file size of any captured image and pops up a dialog that displays the file size and asks the user if they want to edit the image before saving or not, to shrink it. This could be combined with #1 above maybe, or maybe they could go one after the other so if the result of #1 is still very large the user is aware of it before saving and gets a chance to resize or crop

**Comment by NightXlt** [comment]
First of all, I am so sorry for this delayed task that should have been finished in Mar 2019, because I am a senior student hunting for jobs. Now I am free to finish this promised development.

**Several development detail questions**:
In #2 :
a preference (with a sensible default) that simply checks the file size of any captured image and **pops up a dialog that displays the file size and asks the user if they want to edit the image before saving or not,** to shrink it. **This could be combined with #1 above maybe, or maybe they could go one after the other so if the result of #1 is still very large the user is aware of it before saving and gets a chance to resize or crop**

My plan is to develop a simple, maintainable crop function, so all the crop/ resize operation will be implemented by  standard system intent. 

However, I am not so sure whether resize is means send a standard system intent for image editing? In addition, a sensible default is similar to 500KB that also is displayed in popup window as a Image limit? 

My flow chart as follows : 
![Crop_process](https://user-images.githubusercontent.com/16274345/55694145-40bcab00-59e5-11e9-8e53-96c2f6e99ac1.png)

Thanks.

**Comment by mikehardy** [comment]
Hi there! No need to apologize, we're all volunteering :-). I'm happy to see you back. 

This flow chart looks great. 

The only change I can think of is that I'm not sure how the state in the top right is accessed (and in my description of a possible solution I'm not sure I described things well, maybe leading to it). Could maybe just get rid of it. 

And near the end of the flow I think we show the user the size of the file they are about to save, with a suggestion they resize if it is over a certain size but allow them to go ahead if they want. I don't think we should prevent the user from saving unless they synchronizing is enabled and it is over the single-file limit ankiweb limit of 100MB (unlikely limit to hit, but it exists - https://github.com/ankidroid/Anki-Android/issues/4992 )

**Comment by NightXlt** [comment]
Concrete use situation : 
1. The new resize button would appear after capturing and cropping photo. Users could click it for cropping photo. 

  The reason why I wanna add a button is because of users' desire. If they don't crop photo very well after capturing and cropping photo, they will have another entrance to crop. 

   Actually, this isn't completely necessary to add a button. User also could enter into crop window after clicking save button, but this is only valid when the photo size is larger than default size.

2. I get your point about setting the size of the file they are about to save， but I always confuse How large the default size is. Our smartphone's resolution is increasing rapidly. For instance, The largest photo's size is more than 5MB.  So What do you think of the default size?

**Comment by mikehardy** [comment]
I see what you mean about a button for cropping, that could be useful yes.

My phone can generate 18MB images, it's crazy to think of for a flashcard! I think this is the sort of thing we can change later when we know more, if we need to, but it seems like 1MB or so is a reasonable time to suggest they shrink the thing - that's pretty low but these are network-synchronized cloud-saved resources taking up space on phones and just used for flashcards. That's expensive storage. And if we're not preventing them from saving it doesn't seem like it would hurt anything to have the limit be low

**Comment by NightXlt** [comment]
I have some problems about the localization. I read the docs. Is developer only responsible for coding? The string in coding I wanna use English replaced. You will proceed localization by crowdin?

**Comment by timrae** [comment]
Yes, you just put the English version of the string into the main XML file in res/values. The other localised version will then be handled by crowdin.

**Comment by NightXlt** [comment]
ah, I have finished this crop function, but I confront some adapt  problems. The common standard  system crop intent doesn't work on XiaoMi and HuaWei. I will spend more time on completing this function.

**Comment by mikehardy** [comment]
That's great news on the progress, and I have to admit I'm not surprised on the XiaoMi and HuaWei devices - I've started running into problems on other projects specific to XiaoMi at least where it seems they are doing things differently enough it is starting to really fragment the android ecosystem. Hope that doesn't just get worse as supporting "two androids" (or three or four) is not really possible with the amount of time we have as developers

**Comment by NightXlt** [comment]
Fortunately， I finish most of all phone crop adapt, but I wanna do an relative performance optimization. 

Q : We get the return resource after multi-media edit, but if we don't want to save this note and then quit this Activity. The return sources are't deleted. I wanna delete that. These resources  take up a lot of space. In addition, resources should be deleted would be uploaded to service.
H : How could I get all fields in editing note. I try my best to get fields.  Regrettably, I don't get that, so could you tell how could I get fields in current note. Thank you so much for your help.

**Comment by mikehardy** [comment]
Hi there - sorry for the delay - I'm not sure exactly how to get all the fields on a note but if you follow the code for card display (I think the implementation behind the q() and a() methods in AbstractFlashcardViewer, implemented in Note and Card) you should see some code that accesses fields

**Comment by NightXlt** [comment]
Hi, I still can't find the code, but I find a brute solution. I try to put all field path into an array list. When I quit and not save, I will delete all file based on this list.  What do you think of this solution?

**Comment by mikehardy** [comment]
If you make a PR for it (just start the pull request title with [WIP] for now to signal it's in progress) I can see the code and comment more about the solution. I'd be happy to look at it and try it locally to see how it works

**Comment by NightXlt** [comment]
Is it okay?

**Comment by mikehardy** [comment]
Sorry I was traveling early this week and I still have not read all the mail backlog, much less done PR reviews but I will get to it! Flagged this notification as important in my inbox so it filters up higher. I really appreciate the work!

**Comment by NightXlt** [comment]
No need to apologize, and I also delayed my push for my two weeks traveling. As soon as you have some problems, you could contact with me directly.

**Comment by NightXlt** [comment]
Does it work?

**Comment by mikehardy** [comment]
@NightXlt you are commenting on the issue, while on the PR I have left comments - I was waiting for feedback

**Comment by mikehardy** [comment]
Use the PR now for collaboration, as that is where we are shaping the code...

**Comment by NightXlt** [comment]
Sorry for ignoring PR comment, I have left my comment in here.

**Comment by mikehardy** [comment]
Has related PR that just needs final guidance from us as reviewers

**Comment by mikehardy** [comment]
@simonnewstead posted a bounty for this and @NightXlt did the original work that should merit the bounty though it was eventually carried into the codebase on a PR of mine - commenting here because I think that's how bountysource will pick it up? unsure but I'm on record at least :)
