### ISSUE TITLE
Copy database documentation to wiki

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2618]
Originally reported on Google Code with ID 1716

```
By Bibek:
https://github.com/bibstha/Anki-Android/wiki/Anki2-database-documentation
```

Reported by `nicolas.raoul` on 2013-03-21 08:40:56

**Comment by mikehardy** [comment]
The database structure was already largely documented. I only found a little information on the linked page that was not already in the wiki, and I added it:

https://github.com/ankidroid/Anki-Android/wiki/Database-Structure/_compare/8f269d044e294556381028ea39d6076458ea8097...1db43d8e1b31e85dcccbe870dd884a58b8a83781

@timrae  I think this may be closed
