### ISSUE TITLE
Refactor DeckOptions.java

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2632]
Originally reported on Google Code with ID 1730

```
Refactor class DeckOptions, especially 
- extract inner classes into an own file
- Add method comments
- Use constant variables (public static final) for option constants

```

Reported by `dominic.lerbs` on 2013-04-05 20:11:13

**Comment by david-allison-1** [comment]
Won't fix for now - there's a lot of code quality issues, but it'll be best to take a targeted approach to get the most value out of them, given our limited resources. 

Priorities will likely change between then and now, and there's little point in keeping this around.
