### ISSUE TITLE
Card created on Ankiweb shows &nbsp;

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2660]
Originally reported on Google Code with ID 1758

```
What steps will reproduce the problem?
1. Create a card on Anki server.
2. Use Ankidroid to sync with Anki server.
3. Open the deck on Ankidroid to find it's not usable and full of &nbsp; everywhere.

What is the expected output? What do you see instead?

One should see the exact card made on Anki server.  

Does it happen again every time you repeat the steps above? Or did it
happen only one time?

It happens all the time making Ankidroid itself obsolete and useless if syncing does
not render usable cards.

What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title)
On what version of Android? (Home screen > menu > About phone > Android
version)

V.2.0.1

If it is a crash or "Force close" and you can reproduce it, the following
would help immensely: 1) Install the "SendLog" app, 2) Reproduce the crash,
3) Immediately after, launch SendLog, 4) Attach the resulting file to this
report. That will make the bug much easier to fix.


Please provide any additional information below.

I've looked all over the internet for a fix and it seems like the only thing people
are saying is that Ankidroid needs a major update.  

```

Reported by `brandn14` on 2013-05-15 03:06:46

**Comment by mado0705** [comment]
I have the same problem too. 
I add cards on my desktop client, and  it happens often on android.
I know how reproduce the problem. and can modify it on android.

But it is really frustrating.

**Comment by timrae** [comment]
What are the steps to reproduce?

**Comment by mado0705** [comment]
1. create a card on Anki (windows10 version:2.0.44 )
2. I press "Enter" button when I want to change lines.
( or press "space" button twice )
3. Output the card into Ankidroid (V: 2.8.2)
4. When edit the card on Ankidroid, "&nbsp;" will appear at the position where I press "Enter" button。

The "&nbsp;" will disappear if I press "Shift+Enter" button not just "Enter" button.
The "&nbsp;" sometimes would appear and I don't know why.

I will revise a mistake on Ankidroid when I find the mistake.
but the "&nbsp;" make revise a mistake difficult.

**Comment by snoyes** [comment]
This non-breaking space entity is supposed to be there and is present in the desktop version too - you'll see it if you open the HTML editor. This is simply another version of "we want a WYSIWYG editor" - duplicate #1377
