### ISSUE TITLE
Add tactile output

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2772]
Originally reported on Google Code with ID 1870
```
Right now you can build cards that you can see and hear (text, graphics, animations,
videos, sounds).

I'd also like to build cards that you can feel, with an entry like [vibrate:(duration)(intensity)]
or some such. It would need to allow a sequence of vibrations, since my only interest
in this is one more way to present morse code.
```

Reported by `snoyes` on 2013-10-24 21:26:54

**Comment by hssm** [comment]
Anyone with a legitimate use case for this can use HTML5 in their card templates to trigger vibration.

**Comment by lucwastiaux** [comment]
What about haptic feedback when scoring a card ? it would interrupt the monotony of reviewing cards.
