### ISSUE TITLE
Custom Study Inconsistent with Desktop Version

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#2940]
Originally reported on Google Code with ID 2043

```
The default options for filtered decks created using custom study are different from
on the desktop:

e.g. AnkiDroid defaults to cards added in random order (Desktop is order added)
AnkiDroid disables "reschedule my answers" whereas Desktop enables it.

Let's try to be consistent with Desktop as much as possible.
```

Reported by `perceptualchaos2` on 2014-03-27 22:31:40

**Comment by reinert** [comment]
I use Custom Study every day and I always fall into this problem. When creating a CS session from AnkiDroid, after finishing it, then I realize my cards are not rescheduled. It's so frustrating! Please prioritize this issue! It doesn't cost too much to let this option selected by default. Thanks!

**Comment by mikehardy** [comment]
@timrae I just looked, and the desktop and AnkiDroid look exactly the same for creating filtered decks at this point - all the things above seem to be addressed
