### ISSUE TITLE
Add custom fonts from the media folder to lists given in default fonts etc

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3027]
Originally reported on Google Code with ID 2130

```
As per title, this will e.g. allow users to set a custom font for the browser after
importing using the new @font-face method.
```

Reported by `perceptualchaos2` on 2014-05-29 13:23:53

**Comment by Arthur-Milchior** [comment]
Probably not relevant as we don’t eve have an option to select a font in the note editor
