### ISSUE TITLE
Adding app to Nokia Store and Yandex Store

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3068]
Originally reported on Google Code with ID 2171

```
... then app will be available for phones like Nokia X.
```

Reported by `leafinbox` on 2014-06-26 07:16:38

**Comment by mikehardy** [comment]
Nokia Store is dead, changed to Opera Store, and now it's "bemobi". We're not in there:
http://android.oms.apps.bemobi.com/en_ec/catalog.php?search=ankidroid

Yandex looks like a pretty closed ecosystem - you can't even check if we're there unless you register (I did not register)

Not sure how much either of these are used anymore, they were from the older days when everyone wanted their own store and this was what Nokia did...
