### ISSUE TITLE
Anki on the unlockscreen (Android app)

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3111]
Originally reported on Google Code with ID 2214

```
It could be interesting if we must have to answer at one card to unlock our phone.

This feature could be seen in UnlockYourBrain app available in android store.
```

Reported by `Groultok` on 2014-07-29 10:38:20

**Comment by dancinglightning** [comment]
Hi,
i see this is old, but can i just ask why ?
We've used Semper for a long time before it went paid, and exactly this feature was the "killer feature" (imho)

**Comment by timrae** [comment]
For the reasons that were already mentioned... I agree that this would be a useful feature, but it's not something that we really want to maintain in the main code base, as we are struggling just with the maintenance of the core features. The philosophy is generally that if it can be added as an add-on then it should be. 

In saying that, if someone were to make an addon of sufficiently high quality, and they kept it maintained, and they then asked us to merge it into the main project we might consider that.
