### ISSUE TITLE
java.lang.RuntimeException: java.lang.NullPointerException at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:180

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3124]
Originally reported on Google Code with ID 2227

```
Media syncing bug in 2.2.3.

Triage link:
http://ankidroid-triage.appspot.com/view_bug?bug_id=6107982546862080
```

Reported by `Houssam.Salem.Au` on 2014-08-07 14:59:38

**Comment by mikehardy** [comment]
Not sure if we still get error reports about this but the line mentioned for possible null check has moved, it's here now:
https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/sync/RemoteMediaServer.java#L79

It's definitely possible for the super-class (HttpSyncer) to throw all sorts of RuntimeExceptions for various reasons, and those will bubble up write through the RemoteMediaServer syncing code

Not sure if it is an active source of errors but it looks like plausible it could still generate them in flaky network conditions

**Comment by mikehardy** [comment]
I see no errors on this currently
