### ISSUE TITLE
java.lang.RuntimeException: android.database.sqlite.SQLiteException: no such table: meta (code 1): , while compiling: select dirMod from meta

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3125]
Originally reported on Google Code with ID 2228

```
Media syncing bug in 2.2.3

Triage link:
http://ankidroid-triage.appspot.com/view_crash?crash_id=5901354891476992

Seems like the media database becomes corrupted somehow.
```

Reported by `Houssam.Salem.Au` on 2014-08-07 15:01:55

**Comment by guyemerson** [comment]
This happened to me when trying to save to an SD card that had too little free space, so the files could not be written correctly.  Freeing up more space, deleting collection.media.ad.db2 and collection.media.ad.db2-journal, and forcing a full sync fixed the problem.
