### ISSUE TITLE
cards display backwards- answers on front and questions on back

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3164]
Originally reported on Google Code with ID 2267

```
What steps will reproduce the problem?
1.download a set of cards(on android)
2.study
3.answer displays. Click show answer, and question displays.

What is the expected output? What do you see instead?
I want to see the question first, and then the answer.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?
Every time

What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title)
On what version of Android? (Home screen > menu > About phone > Android 
version)


If it is a crash or "Force close" and you can reproduce it, the following
would help immensely: 1) Install the "SendLog" app, 2) Reproduce the crash,
3) Immediately after, launch SendLog, 4) Attach the resulting file to this
report. That will make the bug much easier to fix.


Please provide any additional information below.

```

Reported by `heliumspark` on 2014-09-04 04:06:44

**Comment by raphaelLacerda** [comment]
i'm having the same problem

1 - Create a deck
2 - add some card
3 - create a custom study
4 - Some cards will show the back part first, instead of the front

It's happening in AnkiDRoid and Anki for MAC too.

**Comment by fditraglia** [comment]
I'm having this problem as well, both on the linux version and the Android version.

**Comment by mikehardy** [comment]
This is closed because it is not a bug. The manual section on card templates will show you how to fix your templates to show what you want

**Comment by lifanchu** [comment]
I am suddenly having this problem as well. No problems for years then, suddenly, all my basic cards are shown reversed.

**Comment by mikehardy** [comment]
This is closed because it is not a bug. The manual section on card templates will show you how to fix your templates to show what you want -> google ankidroid faq reverse cards

**Comment by lifanchu** [comment]
Changing the templates fixed the problem, thanks.  However, I do not see how this is not a bug. The contents of the 'Front Template' and 'Back Template' for a particular note type switched without notice. Maybe this is due to user error, but I cannot think of what series of mistakes I could have made to achieve this unconsciously.

**Comment by mikehardy** [comment]
It must be user error somehow, there is no way that these would change randomly that I can think of. I recognize that it is highly unlikely, yet some set of user error is the most likely explanation, however unlikely

**Comment by faith-ly6** [comment]
For future users with problem and are complete noobs like me lol
Go into browse then chose any card with type 'basic' then click 'Cards..." (Customize Card Template [ctrl+L]) 
If {{Back}} then change to {{Front}}
Click "Back Template" and change {{Front}} to {{Back}} 
- fixes problem for all basic cards so no need to repeat over and over again
- I don't know how it works on phones
