### ISSUE TITLE
Statistics graphs units inconsistent with Anki desktop

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3217]
Originally reported on Google Code with ID 2321
```
The units currently used in the statistics graphs are inconsistent with Anki desktop
and IMO inappropriate, can we stick to units of 10, 50, 100 or 1000 as in Anki.

At the moment, it's all over the place, with 4, 10, 20, 40, 80, 100, 400 units etc.
```

Reported by `financialwarfare` on 2014-10-16 09:16:03

**Comment by jvanprehn** [comment]
Anki Desktop uses Flot for JQuery (see ank/js.py). Flot for JQuery uses the following algorithm (see jquery.flot.js:setupTickGeneration):

            // estimate number of ticks
            var noTicks;
            if (typeof opts.ticks == "number" && opts.ticks > 0)
                noTicks = opts.ticks;
            else
                // heuristic based on the model a*sqrt(x) fitted to
                // some data points that seemed reasonable
                noTicks = 0.3 * Math.sqrt(axis.direction == "x" ? surface.width : surface.height);

            var delta = (axis.max - axis.min) / noTicks,
                dec = -Math.floor(Math.log(delta) / Math.LN10),
                maxDec = opts.tickDecimals;

            if (maxDec != null && dec > maxDec) {
                dec = maxDec;
            }

            var magn = Math.pow(10, -dec),
                norm = delta / magn, // norm is between 1.0 and 10.0
                size;

            if (norm < 1.5) {
                size = 1;
            } else if (norm < 3) {
                size = 2;
                // special case for 2.5, requires an extra decimal
                if (norm > 2.25 && (maxDec == null || dec + 1 <= maxDec)) {
                    size = 2.5;
                    ++dec;
                }
            } else if (norm < 7.5) {
                size = 5;
            } else {
                size = 10;
            }

            size *= magn;

If we set opts.ticks = field.height / pixelDistance and opts.tickDecimals= null we get in Java:

        double noTicks = field.height / pixelDistance;

        double delta = (deltaRange) / noTicks,
                dec = Math.floor(Math.log(delta) / Math.log(10));

        double magn = Math.pow(10, dec),
                norm = delta / magn; // norm is between 1.0 and 10.0

        double size;

        if (norm < 1.5) {
            size = 1;
        } else if (norm < 3) {
            size = 2;
            // special case for 2.5, requires an extra decimal
            if (norm > 2.25) {
                size = 2.5;
            }
        } else if (norm < 7.5) {
            size = 5;
        } else {
            size = 10;
        }

        size *= magn;

We could put this in ChartBuilder.java:ticsCalc and call it from ChartBuilder.java:ticksCalcY.

**Comment by jvanprehn** [comment]
Solved by https://github.com/ankidroid/Anki-Android/pull/4282

**Comment by timrae** [comment]
Thanks for the nice work on this @jvanprehn
