### ISSUE TITLE
"Cloze Deletion" botton in Ankidroid

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3252]
Originally reported on Google Code with ID 2356

```
I use a lot "Cloze Deletion" for creating my flashcards with Anki and the last months
i' ve started using "Cloze Deletion" on Ankidroid, but this prozess is very slow because
i've to type {{c1::...}} everytime manually and it's very uncomfortable when i add
a lot of sentences: is it not possible to add a simple Cloze botton in Ankidroid? So
it could possible to select something (1 o more words) and then just clicking that
botton. 


```

Reported by `fabio.iannone` on 2014-10-28 20:08:43

**Comment by zxcpoiu** [comment]
issue #1618 is different with the origin issue id on GoogleCode and totally not related.
**This issue should merge to** #2520

**Comment by eginhard** [comment]
They were still merged on Google Code and you'll see that the old id of #2520 was indeed 1618. Same for the other issue you posted in.

**Comment by zxcpoiu** [comment]
oh, ok, thanks for pointed it out. that's why I felt strange.

just wanted to make this issue more clear on Github issue tracker.
not familiar with Google Code though.
