### ISSUE TITLE
Changelog on F-Droid

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3256]
Originally reported on Google Code with ID 2360
```
Are you doing the F-Droid releases by yourselves? It would be very useful to have the
same changelog available there as in the Google Play Store.

```

Reported by `robert.pollak@mykolab.com` on 2014-10-29 07:05:21

**Comment by Minoru** [comment]
Changelog is accessible from the "Links" list that's right under the description, so I think that issue can be closed now.
