### ISSUE TITLE
turn deck or cards from "question - answer" to "answer->quastion"  

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3341]
Originally reported on Google Code with ID 2445

```
Hello. I like your app / Anki / 

We can learn the card according to the principle "question - the answer" (or front
-> back) Please add the possibility also to turn the card so that we can learn them
like: "back-> front". 

Or simply possibility to turn deck entirely

thx for app.

```

Reported by `ya.okkonstantin@yandex.ru` on 2014-12-18 17:57:17

**Comment by alireza001** [comment]
please add this feature for cards that Have already made.

**Comment by eginhard** [comment]
Please read the above. You can use the "Basic (and reversed card)" note type to create cards in both directions for simple question/answer notes, see also this helpful video on reversing cards: https://www.youtube.com/watch?v=DnbKwHEQ1mA
