### ISSUE TITLE
The order of the pie graph's pieces of "Cards Types" is not consistent with that of Anki Desktop.

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3349]
Originally reported on Google Code with ID 2453
```
As the attached file below,
the order of the pieces of the graph differ from that of Anki.
((a)&(b),(c)&(d))

Moreover,the order of the legend's elements is not stationary
((e)&(g)) , 
though that of Anki Desktop is stationary
((f)&(h)).

I think those of AnkiDroid are incomprehensible.
```

Reported by `windowopen00` on 2014-12-27 05:11:28

<hr>
 * *Attachment: Screenshot_2014-12-27-13-26-10 edit.png<br>![Screenshot_2014-12-27-13-26-10 edit.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2453/comment-0/Screenshot_2014-12-27-13-26-10 edit.png)*

**Comment by jvanprehn** [comment]
We could change 2 things in PieChart.java:paint:
- Introduce an angleOffSet of -90 degrees
- Change the sign of all angles passed to g.fillArc and Math.cos and Math.sin

Then the paint method would look like this:

		RectangleWrap field = g.getClipBounds();
        float maxSideBorders = Math.max(mPlotSheet.getFrameThickness()[PlotSheet.LEFT_FRAME_THICKNESS_INDEX],
                mPlotSheet.getFrameThickness()[PlotSheet.RIGHT_FRAME_THICKNESS_INDEX]);
        float maxUpperBottomBorders = Math.max(mPlotSheet.getFrameThickness()[PlotSheet.UPPER_FRAME_THICKNESS_INDEX],
                mPlotSheet.getFrameThickness()[PlotSheet.BOTTOM_FRAME_THICKNESS_INDEX]);

        float realBorder= Math.max(maxSideBorders, maxUpperBottomBorders) + 3;
        float diameter=Math.min(field.width, field.height)-2*realBorder;

        float xCenter = (float)(field.width/2.0);
        float yCenter = (float)(field.height/2.0);
		ColorWrap oldColor = g.getColor();

        float xMiddle = xCenter - (float)(diameter/2.0);
        float yMiddle = yCenter - (float)(diameter/2.0);

        float angleOffSet = -90;
        float currentAngle = angleOffSet;
        float nextAngle = currentAngle + (float)(360.0* mPercent[0]);
        int tmp = 0;
		for(int i = 0; i< mPercent.length-1; i++) {
			g.setColor(mColors[i% mColorHelper]);
            g.fillArc(xMiddle, yMiddle, (int)diameter, (int)(diameter), -1*currentAngle, -1*(nextAngle - currentAngle));
			currentAngle = nextAngle;
			nextAngle = (int)(angleOffSet + 360.0* mPercent[i+1]);
			tmp = i;
		}
        tmp++;
		//last one does need some corrections to fill a full circle:
		g.setColor(mColors[tmp% mColorHelper]);
        g.fillArc(xMiddle, yMiddle, diameter, diameter, -1*currentAngle, -1*(360 + angleOffSet - currentAngle));
		g.setColor(ColorWrap.black);
		g.drawArc(xMiddle, yMiddle, diameter, diameter, 0, 360);
		
		//Beschriftung
		g.setColor(ColorWrap.white);
		//g.drawString("" + Math.round(((mPercent[0]) * 100) * 100) / 100.0 + "%", (float) (xCenter + Math.cos(mPercent[0] * Math.PI) * 0.375 * diameter) - 20, (float) (yCenter - Math.sin(mPercent[0] * Math.PI) * 0.375 * diameter));
		for(int j=0;j< mPercent.length;j++)
		{
            double oldPercent = 0;
            if(j  != 0)
                oldPercent = mPercent[j-1];
            String text = ""+Math.round((((mPercent[j]- oldPercent))*100)*100)/100.0+"%";
            float x = (float)(xCenter+Math.cos(-1*((oldPercent+(mPercent[j]- oldPercent)*0.5)*360+angleOffSet)*Math.PI/180.0)*0.375*diameter)-20;
            float y = (float)(yCenter-Math.sin(-1*((oldPercent+(mPercent[j]- oldPercent)*0.5)*360+angleOffSet)*Math.PI/180.0)*0.375*diameter);
            FontMetricsWrap fm = g.getFontMetrics();
            float width = fm.stringWidth(text);
            float height = fm.getHeight();
            ColorWrap color = g.getColor();
            g.setColor(new ColorWrap(0,0,0,0.5f));
            g.fillRect(x-1,y-height+3,width+2,height);
            g.setColor(color);
			g.drawString(text,x ,y );
		}
		
		g.setColor(oldColor);

**Comment by jvanprehn** [comment]
To make the order of the legend's elements deterministic we could change mLegendMap to a LinkedHashMap instead of a HashMap.

**Comment by jvanprehn** [comment]
Just for completeness: R.string.statistics_suspended and R.attr.stats_suspended are used in stats.java:calculateCardTypes

**Comment by timrae** [comment]
Thanks for looking into it, would you be able to submit a PR? We don't
really have any preference about how it's implemented as none of us are
currently maintaining the stats code
