### ISSUE TITLE
Bring undo behavior inline with Anki Desktop

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3374]
Originally reported on Google Code with ID 2478

```
What steps will reproduce the problem?
1. edit a card
2. begin studying
3. use the back button to navigate backwards and changes to the card edited will be
undone

What is the expected output? using the back button should just step you backwards through
the card study order. What do you see instead? Changes made to cars are undone even
though you are not in the card editing mode


Does it happen again every time you repeat the steps above? Or did it
happen only one time? it happens everytime


What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title) 2.3.2
On what version of Android? (Home screen > menu > About phone > Android
version) 4.4.4


If it is a crash or "Force close" and you can reproduce it, the following
would help immensely: 1) Install the "SendLog" app, 2) Reproduce the crash,
3) Immediately after, launch SendLog, 4) Attach the resulting file to this
report. That will make the bug much easier to fix.


Please provide any additional information below.

```

Reported by `greg@ihnen.me` on 2015-01-20 14:54:53

**Comment by timrae** [comment]
We should check how Anki desktop does it, but clearing the "edit" event from the undo stack when the card is answered would fix this problem

**Comment by timrae** [comment]
I took a peek, and it seems that our implementation of undo is quite different from Anki Desktop. In solving the issue in the OP I think we'll need to bring the code inline with the desktop client. In particular we need the [`_undoReview()` method](https://github.com/dae/anki/blob/master/anki/collection.py#L613).

@hssm are you interested in looking into this for 2.5.1?

**Comment by hssm** [comment]
I looked at doing this some time ago but put it aside since it was a bit too involved.

At the time, I didn't really understand the database aspects and what we would need to change to make the roll-backs work (I think I have a better understanding of it now but haven't really looked at it since).

Anyway, it seemed like a big change and I want to work on other things in the mean time, so I probably won't be looking at this any time soon.

**Comment by mikehardy** [comment]
This code lives here now: 
https://github.com/dae/anki/blob/master/anki/collection.py#L645

Basic difference is we just have a list (treated as a stack) of undo items, whereas Anki Desktop differentiates between "checkpoints" and "reviews" for the purposes of undo. Anki Desktop saves one checkpoint at a time for undo, and multiple reviews.

I don't see a point in removing the ability to undo multiple things Anki Desktop thinks of as "checkpoints", but splitting between the types and having the button in the Reviewer only undo reviews seems sensible.

Not that I'm going to do this now, but I thought it's worth writing out what I just saw while investigating
