### ISSUE TITLE
pie chart turns black where it should be green

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3384]
Originally reported on Google Code with ID 2488

```
What steps will reproduce the problem?

go to statistics, CARDS TYPES[sic!]

in the following: 
s:=Suspended
u:=Unseen
m:=mature
y:=Young+Learn

observe that every slice not yellow i.e u, m and y is black instead of light green,
green.

Happens for: 
s:66 u:0    m:87 y:18
u:0  m:1989 y:25 s:42
s:1  u:0    y:23 m:207

Does not happen for:
y:260 m:4273 u:14   s:3581
u:0   s:1435 y:58   m:707
u:14  y:112  m:1245 s:2036
s:1   u:0    y:14   m:38
s:0   u:0    m:0    y:0    (all yellow)

I'm reporting the types(m,u,s,y) in their order of appearance in the legend at the
top left.
This is confusing when you want to compare the numbers, but I find it remarkable that
there is no fixed order.
Maybe their order in the legend corresponds to their order in the pie chart?

What I see is that when it happens, u(meant to be black) is 0, but u=0 does not imply
this behaviour.


Version of AnkiDroid: 2.3.2
Version of Android: 5.0
```

Reported by `peer.valhoegen` on 2015-01-24 21:58:17

**Comment by jvanprehn** [comment]
I can't reproduce this one.

I tried:
1. The minimal example (u=m=0, y=1, s=4)
Replace query in Stats.java:calculateCardTypes by:

                String query = "select " +
                "sum(0), -- mtr\n" +
                "sum(1)/sum(1), -- yng/lrn\n" +
                "sum(0), -- new\n" +
                "sum(4)/sum(1) -- susp\n" +
                "from cards where did in " + _limit();

It gives:
![anki-pie-wrong-color-0-minimal](https://cloud.githubusercontent.com/assets/16454627/15273201/8e3bb4ca-1a91-11e6-93c5-b805720c16a3.png)

2. One of the other examples (s:66 u:0    m:87 y:18):

                
                String query = "select " +
                "sum(87)/sum(1), -- mtr\n" +
                "sum(18)/sum(1), -- yng/lrn\n" +
                "sum(0)/sum(1), -- new\n" +
                "sum(66)/sum(1) -- susp\n" +
                "from cards where did in " + _limit();

It gives:
![anki-pie-wrong-color-1](https://cloud.githubusercontent.com/assets/16454627/15273420/7ede8e96-1a99-11e6-98d9-2b3e778a21ac.png)
