### ISSUE TITLE
Flashcard in Notification

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3397]
Originally reported on Google Code with ID 2501

```
I would love if AnkiDroid allowed to have random flashcards that are due to review show
up in the notification bar periodically.

There's an Android app that seems to be doing this (although I have not tested it since
it says is incompatible with all my devices):
https://play.google.com/store/apps/details?id=com.g2.quizification.lite


The idea would be to have the notification bar itself "test" me. It would be additionally
awesome if we could choose which sets to pull the cards from, set how often cards would
show up (i.e. "every x minutes"), and other options people might find useful.

I think this would be helpful for people like me who tend to "forget" to review their
cards or tend to "ignore" the notification for how many cards there are to review,
since there would be a question right there waiting to be answered, lowering the chance
for rationalizations like "I'll review later in the day" (it's these little things
that make a difference for chronic procrastinators like myself :P)
```

Reported by `cocax88` on 2015-01-29 18:02:43

**Comment by rpgrca** [comment]
I was going to suggest something similar to this. Maybe not necessarily answer from the notification screen. For example, I had a desktop application called Kanji Gold which had a "Kanji popup" feature, that would ask me about a kanji randomly while using other programs, with a timer to answer.

So, maybe you could make it so that if the screen is off, a notification appears, and when you turn the screen on it will ask you to answer a card. The idea wouldn't be to "learn" something new, which requires repetition and to pay attention, but to "refresh" something you already know, so it could be set that only cards that are already learned appear, cards that are most likely to take you less than 5-10 seconds to answer. And if it could go "above" lock screens so that you could answer without having to unlock it, it would be a hit.

**Comment by catalinapre2** [comment]
I want this feature too. I was on here to see if it's already been suggested and I'm happy to see that it has. However I would not put at certain intervals, but randomly throughout the day (say between 8am and 10pm). A super bonus feature would be to have it check my calendar and only serve me a flashcard if I'm available.

@hssm yes, they are easy to dismiss but people that want to keep learning and just never get around to doing it (like myself and other is this thread) won't do that; especially if we keep the interaction really short. Case: "What's apple in German?" -> [give yourself 1 sec to think of answer] -> press "See answer" -> mark yourself. Seriously, if users have to spend time thinking about the answer they should just move on and mark themselves accordingly instead. 

I'll try do implement this - depending on my spare time ;)

**Comment by hryanjones** [comment]
+1 This would be awesome.

It'd also allow for other uses of Anki, such as popping up quotes or other pieces of wisdom that you want to be reminded of on something like a daily timeframe, but wouldn't necessarily remember to open the app.

I also like that it would essentially remind you to study if you hadn't for some time, for example, if you could set to only show a notification if I haven't opened up AnkiDroid in 2 days.

@catalinapre2 I highly support you trying to implement. If there's anything I can do via beta testing or anything else, please let me know.

**Comment by timrae** [comment]
I think this would probably be more suitable for a 3rd party app that makes use of the API rather than merging into the main code base, but I'll keep this open as it's a relatively common feature request.

**Comment by madhead** [comment]
Is it a good idea to start implementing this in Ankidroid codebase?

**Comment by Arthur-Milchior** [comment]
@ericli3690 FYI, this 10 YO bug was related to your GSoC idea

**Comment by ericli3690** [comment]
Oh interesting! It's cool to see that this idea has been proposed before, I didn't find this issue when I was creating my GSoC proposal. I'll keep it in mind, thanks!
