### ISSUE TITLE
Use the locale’s first day of the week in statistics

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3400]
Originally reported on Google Code with ID 2504

```
What steps will reproduce the problem?
1. Use e.g. German UI
2. Go to »Statistik«, that is “Statistics”
3. And »Gedächnisleistung nach Wochentag«, “Weekly Breakdown”

What is the expected output? What do you see instead?
The graph should start with the first day of the week, which, in Germany, is Monday.
Instead it starts with Sunday, which, in Germany is the last day of the week.

(This happens every time since the stats rework, i tried it with 2.4, but will skip
pasting version info.)

Please provide any additional information below.

Week starts on Monday in Germany, see e.g. https://ssl.icu-project.org/icu-bin/locexp?d_=en&_=de_DE

Looks like we should look at what the Calendar class thinks is the first day of the
week: https://developer.android.com/reference/java/util/Calendar.html#getFirstDayOfWeek%28%29

P.S.:
Why does the week-*end* contain the *start* day of the week in, say, the USA‽
```

Reported by `ospalh` on 2015-02-02 11:05:57

**Comment by madhead** [comment]
I know many people who uses English locale on their phones in my country: many apps just lack of Russian translation, some are translated using Google Translate and so on. Implementing this feature via [`Calendar#getFirstDayOfWeek`](https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#getFirstDayOfWeek()) will not work for them, as it returns [`SUNDAY (1)`](https://docs.oracle.com/javase/7/docs/api/java/util/Calendar.html#SUNDAY) in this case. Tested on my phone.

So, maybe it's better to have a setting under `Reviewing` / `Start of next day` to denote first week day?

**Comment by david-allison-1** [comment]
On further inspection, this won't be a great first issue - date is currently provided to us by SQL:

https://github.com/ankidroid/Anki-Android/blob/c27f3907a6da9f6bf3dbe545a91a732ed5215352/AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java#L1016-L1024

Will close unless there's community interest.

**Comment by david-allison-1** [comment]
It's not as simple as a single rotation - the case where there are < 7 datapoints has to be considered. I'll get to this in a couple of months.
