### ISSUE TITLE
Can't switch language when entering text in ChromeOS

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3417]
Originally reported on Google Code with ID 2521

```
What steps will reproduce the problem?
1. Open AnkiDroid in your chromebook
2. Click "Add Note" menu item
3. Enter Front text in default keyboard layout
4. Tab 2 times to switch to the Back text entry
5. Press alt-shift to change the layout, observe in the bottom right corner that the
language is changed to the secondary one (Russian)
6. Try typing text

What is the expected output? What do you see instead?
observe that it is still typed with default keyboard layout

Does it happen again every time you repeat the steps above? Or did it
happen only one time?
happens all the time

Paste the "debug info" from the AnkiDroid "About" dialog below (see the
above help webpage for detailed instructions).


Please provide any additional information below.

```

Reported by `pyatasya` on 2015-02-13 21:59:00

**Comment by tek68213** [comment]
I'm suddenly unable to change the input language in AnkiDroid recently. The keyboard shortcut to switch to Japanese on my Chromebook changed to ctrl-shift-space a while back. That shortcut has never worked in AnkiDroid so I kept using shift-alt and it worked for a while but now it doesn't and I can't enter Japanese text without clicking out of Anki and switching the language. If I try the above steps, I see no change in the language in the lower right corner while in Anki. I have no issues switching the language outside of Anki. 

AnkiDroid Version = 2.6.1 Android Version = 5.0 ACRA UUID = c9290587-ad03-479c-9381-4fe2e72adf47

**Comment by mikehardy** [comment]
@tek68213 locale changing in general is broken in ankidroid for newer android versions #4729 - but this seems different. If it is chromebook specific then it will probably be closed eventually because it's not worth the time as chrome moves to supporting android apps out of the box, but if it affects all ankidroid users, it deserves a close look.
