### ISSUE TITLE
Import/Export doesn't work in ChromeOS

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3420]
Originally reported on Google Code with ID 2524

```
It tries to save to sdcard, which is not present in chromebook. Also it opens gmail,
but can't add the attachement.
```

Reported by `pyatasya` on 2015-02-13 22:02:22

**Comment by eginhard** [comment]
Not sure, possibly this would make it work?
https://www.reddit.com/r/chromeapks/comments/2np4z1/guide_instagram/

**Comment by mikehardy** [comment]
I'll look into this, from what I can tell chromebooks have the ability to read/write to /sdcard now and it shows up in a user-visible area outside of the ARC stuff.

**Comment by mikehardy** [comment]
This is actually still open until #5054 or something similar is merged - Chromebooks still can't export, though import is great now.

**Comment by mikehardy** [comment]
After all this time! And just as Chrome OS gets native Android apps too so its even more useful. Excellent!
