### ISSUE TITLE
Use Android backup service

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3427]
Originally reported on Google Code with ID 2531

```
http://developer.android.com/guide/topics/data/backup.html
http://developer.android.com/google/backup/index.html
```

Reported by `perceptualchaos2` on 2015-02-17 05:17:12

**Comment by mikehardy** [comment]
As of API23 this is enabled by default with no implementation required. To support it in API<23 we'd have to implement a BackupManager etc. We're covering 84% of the userbase at API23+ based on play console installs on active device stats, projected to rise to around 94% covered by auto-backup within the year. I think this is a wont-fix as the platform has filled the need
