### ISSUE TITLE
Add some Galaxy Note S-Pen features (e.g. Send screen capture to Anki) 

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3432]
Originally reported on Google Code with ID 2536

```
Hello and bonjour, 

I just bought a Galaxy Note 4 yesterday and the multitasking features on Anki are great!
However I was disappointed to see that Anki wasn't on the list of apps when I cropped
out a Tweet and wanted to make an Anki card about. Currently I'm getting by by adding
to Evernote and making Anki cards when I get on a computer, it would be nice to cut
out the middle man though ^^ 

I've attached pictures to explain what I'm talking about. The SPen has three relevant
features to Anki. One is Smart Select, which is basically cropping out a part of the
screen (what I used in the screenshot) and turning it into an image. The second is
Image Clip, which is similar to Smart Select, but lets you crop your image in irregular
shapes (e.g clouds or ovals), more useful for cropping images or comic books. The third
is not as important, Screen Write. It takes a snapshot of your entire screen and lets
you doodle on it, possibly useful for adding notes. 

I hope this isn't too much to ask for, I'm not sure how much effort this requires.
But if you guys can do it then I'd be very grateful! 

Thank you and merci beaucoup.
```

Reported by `Spookane112` on 2015-02-20 21:01:27

<hr>
- _Attachment: Screenshot_2015-02-20-15-44-16.png<br>![Screenshot_2015-02-20-15-44-16.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2536/comment-0/Screenshot_2015-02-20-15-44-16.png)_
- _Attachment: Screenshot_2015-02-20-15-44-28.png<br>![Screenshot_2015-02-20-15-44-28.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2536/comment-0/Screenshot_2015-02-20-15-44-28.png)_
- _Attachment: Screenshot_2015-02-20-15-47-24.png<br>![Screenshot_2015-02-20-15-47-24.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2536/comment-0/Screenshot_2015-02-20-15-47-24.png)_
- _Attachment: Screenshot_2015-02-20-15-47-33.png<br>![Screenshot_2015-02-20-15-47-33.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2536/comment-0/Screenshot_2015-02-20-15-47-33.png)_

**Comment by mikehardy** [comment]
This is related to #5023 - if the clipboard changes can handle images this is done
