### ISSUE TITLE
Add ability to edit card template / css styling

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3462]
Originally reported on Google Code with ID 2566
```
What steps will reproduce the problem?
1. when on a card, go to Edit->Cards
2.
3.

What is the expected output? What do you see instead?
I'd expect to be able to change+save the templates and styling. Instead, the only thing
I can do is copy.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?


Paste the "debug info" from the AnkiDroid "About" dialog below (see the
above help webpage for detailed instructions).


Please provide any additional information below.

I don't understand what the function is of the rather new Card Types section, when
I can only look at the code, not modify it. Is this on purpose? Or an unfinished feature?
```

Reported by `sarefo` on 2015-03-27 07:10:06

**Comment by Hans-N** [comment]
I really wish this would be added. In the end everything is there except enabling keyboard input into the text boxes. Sure ideally preview and nice editing features should be available. But I believe in incremental improvements, sometimes things are postponed too long waiting for a big comprehensive solution to be put in place.

For instance I have to delete 7 characters to fix an issue with a missing field in a card. Now I have to sync with the computer to be able to do that. Or sometimes I just want to change the font size, literally a 1 character fix.
