### ISSUE TITLE
Add pressure sensitivity to the whiteboard for styluses.

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3471]
Originally reported on Google Code with ID 2575

```
Please explain your idea here.

It would be beneficial to add pressure sensitive pen support to the whiteboard on those
tablets and phones which can support it. In addition to this, an undo button which
does not wipe the entire screen would be useful, as well as palm or touch rejection
when the user is using a stylus.

I feel this would significantly improve the viability of Anki as a tool for studying
any subject matter which requires drawing diagrams as well as writing out complex equations.

Is this feature available on similar apps (Anki Desktop, AnkiMobile,
AnyMemo, etc) ? If yes, it could help to include a screenshot or link to a
page explaining the feature.

This feature is available on OneNote, Samsung's S Note, and LectureNote, a popular
android note taking application.
```

Reported by `AseemSharma38` on 2015-04-06 15:27:07

**Comment by Xyde** [comment]
How much bounty would be enough to rekindle interest in this?

**Comment by mikehardy** [comment]
Always helps when there is working code, I found this: https://github.com/dsandler/markers/wiki (from here: https://play.google.com/store/apps/details?id=org.dsandler.apps.markers&hl=en )

I have no idea how much bounty would be sufficient for someone to give it a shot - I don't do any drawing with Anki do I'm not a great candidate, but the link above may be interesting for people to look at it if they're considering it
