### ISSUE TITLE
SSLException while building HttpClient

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3476]
Originally reported on Google Code with ID 2580

```
hi i run it in samsung sm-g30h rooted
android 4.4.4
kernalversion
3.10.28-356303
dpi@swdd5620 #1
wed jan 14 16:07:52 kst 2015
built number
ktu84p.g530hxcu1aoa2


What steps will reproduce the problem?
1.try to syncing
2.it synced but nut complete
3.some card isn't complete(no photo and no sound)
4. each time i try to sync it begin download the card at first
5.and show this errore
java.lang.RuntimeException:
java.lang.RuntimeException:
SSLException while building HttpClient

What is the expected output? What do you see instead?


Does it happen again every time you repeat the steps above? Or did it
happen only one time?
it happen every time.

Paste the "debug info" from the AnkiDroid "About" dialog below (see the
above help webpage for detailed instructions).

AnkiDroid Version = 2.4.2 Android Version=4.4.4
ACRA UUID =
20f9650a-0a58-4959-931f-712c1b3b9225
Please provide any additional information below.

```

Reported by `VOAM1993` on 2015-04-13 14:46:59

**Comment by bianwenbo** [comment]
I encountered the same problem because the custom server was used, see [https://github.com/kuklinistvan/docker-anki-sync-server](https://github.com/kuklinistvan/docker-anki-sync-server)
In order to solve this problem, we need to use the specified version of the application. The currently tested version is 2.9.1. Ankidroid higher than this version may have this problem.

**Comment by mikehardy** [comment]
@bianwenbo no, that is going the wrong direction. Make an SSL certificate for your sync server so you can take advantage of encrypted communications. Self-signed certs can work, we specifically made it so AnkiDroid can work with self-signed certificates.

**Comment by bianwenbo** [comment]
> @bianwenbo no, that is going the wrong direction. Make an SSL certificate for your sync server so you can take advantage of encrypted communications. Self-signed certs can work, we specifically made it so AnkiDroid can work with self-signed certificates.

Thank you for your reply.
I proxy [docker-anki-sync-server through](https://github.com/kuklinistvan/docker-anki-sync-server) and configure a self-signed certificate on the server through [Caddy](https://github.com/caddyserver/caddy).

- I tested the 2.10.x version on Google play (and the beta version included), as well as the pre-release version of 2.11.x downloaded on the Github relaease page. All of the above versions will have "SSLException while building HttpClient" issues.
- After changing to version 2.9.1, this problem disappeared.

During all the above tests, the server configuration has not changed.
Therefore, at least in my case, it seems not a problem with SSL certificates.

**Comment by bianwenbo** [comment]
@mikehardy To be precise, it should be related to [docker-anki-sync-server](https://github.com/kuklinistvan/docker-anki-sync-server). Perhaps the api has changed from 2.9.x to 2.10.x?

**Comment by mikehardy** [comment]
@bianwenbo you did not mention the part where you added your self-signed certificate CA to your Android trust store? We will trust self-signed certs but only in the sense that we allow user-installed CAs. I should have been more clear. Additionally, if/when you do so, the exact steps to do so could help other people. We know this works, we have user reports of success: #5435

**Comment by bianwenbo** [comment]
Sorry, there is a mistake in my content that needs to be corrected: the certificate deployed on the server side is a CA certificate issued by [let's-encrypt](https://letsencrypt.org), not a self-signed certificate. This is my fault, as I should have noticed the difference between them.
And I just checked the content of the link you mentioned, it seems that the certificate needs to be installed on the Android device. Do I need to do this for CA-certified certificates?

**Comment by mikehardy** [comment]
> And I just checked the content of the link you mentioned, it seems that the certificate needs to be installed on the Android device. Do I need to do this for CA-certified certificates?

Unknown - I would think not as Let's Encrypt is a pretty official project but it is possible that in older devices that CA is not trusted somehow? (I would be surprised, but I'm always surprised at the ways software can fail)

As you can see in the link above though we have focused on this area and received user acceptance / successful tests. It should work. Why is it not working I don't know but it works for everyone else that went through it ?

**Comment by adamwolf** [comment]
I am using Ankidroid 2.10 with a custom Anki sync server and Letsencrypt
SSL and I have not seen any issues.
