### ISSUE TITLE
Automatically change a keyboard layout on focus

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3496]
Originally reported on Google Code with ID 2600

```
It would be awesome to make the app remember the last keyboard layout for each field
when you create new cards. E.g. you have Russian and English translation fields. So,
the layout (in the apps SwiftKey and Swype as most popular, for example) switches to
Russian in the first field and bakc to English in the second automatically when the
fields get focus.
```

Reported by `pyastolov` on 2015-05-08 08:04:17

**Comment by vintotal** [comment]
In Duolingo, when I study Russian with Español, the Gboard keyboard language changes automatically according to the language that needs to be written.

**Comment by Minoru** [comment]
This feature is not implemented as of 2.9.7. Please don't close the issue.

**Comment by david-allison-1** [comment]
@Minoru Just to note: we're up to 2.11.0 if you'd like to upgrade. The feature hasn't been implemented yet

**Comment by Minoru** [comment]
@david-allison-1 Thanks! Apparently 2.11 hasn't made it to F-Droid yet, but I just upgraded to 2.10.4. I'm in no hurry either way, AnkiDroid works just fine — the little improvement proposed here will just make it even better.

Thanks for making and maintaining such an excellent application! :heart:

**Comment by david-allison-1** [comment]
Can't seem to get the last layout, but switching works: https://drive.google.com/file/d/19NNIilMRJbNmduQCjAYy1Lk7wZtCRbt0/view

**Comment by david-allison-1** [comment]
Nope - awaiting review
