### ISSUE TITLE
"Answer Buttons" stats graph should not show cumulative lines

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3506]
Originally reported on Google Code with ID 2610
```
The cumulative line should start on the "Fail" button, but if its value is 0, it starts
in "Hard" or in the last group, see attached picture. If it starts on "Hard", not this
case, the cumulative total shown is wrong, not considering the "hard" answers.

Ankidroid 2.5 alpha 32
Android 4.1.2
```

Reported by `renato.g.amici` on 2015-05-16 14:24:38

<hr>
 * *Attachment: Screenshot_2015-05-16-20-14-53.png<br>![Screenshot_2015-05-16-20-14-53.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2610/comment-0/Screenshot_2015-05-16-20-14-53.png)*

**Comment by jvanprehn** [comment]
Should it have a cumulative line at all? Anki Desktop doesn't...

**Comment by hssm** [comment]
No, actually, it shouldn't.

**Comment by gajewsk2** [comment]
This was a useful feature to gauge your average correctness rate. Its a shame to just remove it without something to tell what your % average for mature/young cards are.

**Comment by gajewsk2** [comment]
While the lines were not included on anki desktop the stats were included at the bottom of the graph, eg: 
Correct: 70.55%
(2254 of 3195)

On ankidroid now, this graph is far less useful without this information
