### ISSUE TITLE
Night mode does not change enough

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3513]
Originally reported on Google Code with ID 2625

```
What steps will reproduce the problem?
1. Use the attached deck or just use a color gradient as background
2. Review in night mode

What is the expected output? What do you see instead?
When the text color is inverted automatically, the background colors should, too.
They are not.


Does it happen again every time you repeat the steps above? Or did it
happen only one time?
Every time.

Paste the "debug info" from the AnkiDroid "About" dialog below (see the
above help webpage for detailed instructions).
AnkiDroid Version = 2.5alpha32

Android Version = 4.4.2

ACRA UUID = 43b14d00-fe66-46e2-a51e-2a69b75cd0a7

Please provide any additional information below.

The invertColors code,
https://github.com/ankidroid/Anki-Android/blob/develop/AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.java#L37-L82

just isn’t up to the task. I am for getting rid of this color inversion entirely.

See also issue “Night mode changes too much”

```

Reported by `ospalh` on 2015-05-27 12:00:38

<hr>
- _Attachment: [night mode too few.apkg](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2625/comment-0/night mode too few.apkg)_
- _Attachment: night_mode_read_this.png<br>![night_mode_read_this.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2625/comment-0/night_mode_read_this.png)_
- _Attachment: night_mode_no.png<br>![night_mode_no.png](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2625/comment-0/night_mode_no.png)_

**Comment by timrae** [comment]
@ospalh do you have any idea how I could get my LaTeX images to be inverted when using custom night mode styling?

I tried the following but it had no effect:

```css
.latex.night_mode {
 filter: invert(1); -webkit-filter:invert(1);
}
```

**Comment by hssm** [comment]
Try `.night_mode.latex {}`

**Comment by timrae** [comment]
Nope... already tried that. Rename this to apkg to see
[test.zip](https://github.com/ankidroid/Anki-Android/files/53617/test.zip)

**Comment by hssm** [comment]
Ah, right, you don't want to chain the selectors because [that means something different](https://css-tricks.com/multiple-class-id-selectors/). You need to use `.night_mode .latex {}`.

**Comment by timrae** [comment]
Nice, thanks, that works!

**Comment by timrae** [comment]
By the way, is there a way to get it to work for images in general? Why doesn't `.night_mode .img` work?

**Comment by hssm** [comment]
`.img` is not a class. You need `img` to select all image tags.

**Comment by hssm** [comment]
I mean to say `.img` *is* a class, just that you don't have anything with that name.

**Comment by timrae** [comment]
Understood, thanks a lot. I've [added this to the wiki](https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#invert-color-of-images-in-night-mode)
