### ISSUE TITLE
Import from all formats supported by Anki Desktop

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3517]
Originally reported on Google Code with ID 2631

```
Currently Anki Desktop supports importing directly from the following formats:

Text separated by tabs or semicolons
Mnemosyne 2.0 deck (*.db)
Supermemo XML export (*.xml)
Pauker 1.8 Lesson (*.pau.gz)

These files (and therefore any format which can be first exported to plain text) can
therefore be imported indirectly by AnkiDroid using the sync feature (https://ankidroid.org/docs/manual.html#AnkiDesktop),
however some people without a computer may find it useful to be able to import these
directly into AnkiDroid.
```

Reported by `perceptualchaos2` on 2015-06-02 06:15:19

----

- [ ] Text separated by tabs or semicolons
- [ ] Mnemosyne 2.0 deck (*.db)
- [ ] Supermemo XML export (*.xml)
- [ ] Pauker 1.8 Lesson (*.pau.gz)

**Comment by vi** [comment]
Implemented impor from simple text files as a separate app: https://github.com/vi/AnkiImporter

Not everything from the respective Anki Desktop's feature is implemented although.

**Comment by hssm** [comment]
I'm doing a bit of a rework of our import code at the moment. While I had no intention of porting the CSV importer any time soon, since you've started working on it, I decided to port over the tests from the desktop client and made some stubs out of the required classes.

Hopefully this will make it easier to integrate your work later on once we merge those changes in.

**Comment by jagdishrajan** [comment]
Please add an option to import a csv file without having to install the desktop app.  Ideally the phone app should be able to import a local csv file.  Alternatively we should be able to upload a csv to the site and have it show up on the phone app.

**Comment by mikehardy** [comment]
I would love to have this feature but have not had the time to implement. The code for the importer is pretty generic and I think there is some support for it already, it just is not finished. PRs welcome!

**Comment by vi** [comment]
I just keep on using my mini-program that reads semicolon-separated lines and imports them to decks based on filenames.

**Comment by mikehardy** [comment]
Very interesting! I had missed that earlier comment - thanks for sharing this @vi

**Comment by mikehardy** [comment]
Importing CSV in particular is super popular. Not easy perhaps, but super popular. There was some code (if you browse the repository on the release-2.10 branch it will still be there) commented out in the importer that seemed like it might have been close to working even.

**Comment by david-allison-1** [comment]
@mikehardy Could you point me to where this was. Unit tests were commented out between 2.8 and 2.9, but I don't see anything for the importers

https://github.com/ankidroid/Anki-Android/blob/60d6e07ee61305ab5fbd26036bb8f78fd843faa2/AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/libanki/ImportTest.java#L224-L230

**Comment by mikehardy** [comment]
The importer thing was actually an instrumented test, it's been commented since first commit and was prior to the era when I spliced robolectric into the project so all tests were instrumented

https://github.com/ankidroid/Anki-Android/blob/4b6d202ebeff322e4eaae0bc365dd88317dfe572/AnkiDroid/src/androidTest/java/com/ichi2/anki/tests/libanki/ImportTest.java#L232

**Comment by david-allison-1** [comment]
Darn... I was hoping for a silver bullet. The code is still there, and compiles when commented out.

I've had a shot at the conversion (`libAnki` is ported with a few TODOs, but the python modules for CSV reading and dealing with files with BOMs are a little more tricky). 

My main roadblock: It uses `csv.sniffer` to detect the type of CSV. The quote detection of this library uses the regex `groupindex` which Java regexes seem to be missing.

https://github.com/python/cpython/blob/a74eea238f5baba15797e2e8b570d153bc8690a7/Lib/csv.py#L217-L250

**Comment by dae** [comment]
CSV is already implemented now, and the others are niche. Closing.
