### ISSUE TITLE
Notification is unable to be observed

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3527]
Originally reported on Google Code with ID 2641
```
Note: If this is your first time submitting an issue, please read the
following webpage:

https://ankidroid.org/docs/help.html


What steps will reproduce the problem?
1. Have the phone set not to show sensitive notifications on the lock screen.
2. Start a sync.
3. Leave AnkiDroid as the forefront app.
4. Lock the phone.

What is the expected output? What do you see instead?

I suppose the "expected" behavior would be to somehow observe the notification.

When the sync finishes a notification is generated, but it can't be read because the
phone is hiding "sensitive" notifications. The notification can only be seen after
the phone is unlocked. However, when unlocking the phone the notification is already
cleared because AnkiDroid is the forefront app. The notification is never seen.

Not being able to see the notification means you don't know if the sync finished successfully
or not.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?

It happens every time.

Paste the "debug info" from the AnkiDroid "About" dialog below (see the
above help webpage for detailed instructions).

I'm using v 2.4.3

Please provide any additional information below.

```

Reported by `greg@ihnen.me` on 2015-06-14 19:18:32

**Comment by ospalh** [comment]
Actually i can reproduce this.
I see a notification with »Inhalte ausgeblendet« (Content hidden). 
![cont_hidden](https://cloud.githubusercontent.com/assets/1690429/8934181/aa975bb4-3546-11e5-8c67-8e1c1f65403e.png)
So i know that the sync worked or did not work. Not very helpful.
(I have my system set to German and don’t really want to change it.)

My notification settings:
![ad-notif](https://cloud.githubusercontent.com/assets/1690429/8934200/c731c480-3546-11e5-8318-e51a43d90e35.png)
![hide_sensitive](https://cloud.githubusercontent.com/assets/1690429/8934201/c735c26a-3546-11e5-877f-bc2f38efb3f1.png)

(The screen shots *were* done with my patched version, but it is the same with AnkiDroid built off `develop`.)

The screen shots were done with Android 5.0.2.

Btw. on 4.4.4 (i guess pre-Lolipop in general) it works slightly differently, but the effect is the same: On the lock screen you see the “AnkiDroid sync worked or failed” star, but until you unlock you can’t read the text, and when you have unlocked the notification is gone. (I am not sure if i had reported this, maybe it is on queue to be added at github, or i didn’t get around to it.)

**Comment by ospalh** [comment]
How about 
* getting rid of the Sync OK dialog in general
* showing some message when the sync failed that is not replaced by the notification

Personally i don’t like the dialog much for sync. I would be happy with just a spinning waiting indicator over the deck list that just goes away when the sync worked OK and some form of error message when there was a problem. 
Maybe something snackbar-like. Can they be permanent until acknowledged and are they restricted to one app?

**Comment by ospalh** [comment]
If i read the [docs](https://developer.android.com/reference/android/app/Notification.Builder.html#setVisibility%28int%29) correctly, sensitive is the default on API ≥ 21.
Maybe we should set this to public if possible.

Doesn’t really fix the problem with ≤ KitKat.

**Comment by wujek-srujek** [comment]
Neither do I like the Sync Ok dialog, like @ospalh. I would prefer it to just disappear once sync is successfull.

**Comment by ospalh** [comment]
>  The Sync (OK) dialog

That is gone in the 2.5 alpha. Thanks, @timrae, for those changes.

**Comment by timrae** [comment]
Please comment back if it's still not fixed in the next beta version
