### ISSUE TITLE
Search and share icons black on dark gray

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3549]
Originally reported on Google Code with ID 2677

```
Note: If this is your first time submitting an issue, please read the
following webpage:

https://ankidroid.org/docs/help.html


What steps will reproduce the problem?
1. Review
2. Select a word to do a web search


What is the expected output? What do you see instead?

The icons in the action bar should have a reasonable amount of contrast.
Instead, while the icons for “SELECT ALL” “COPY” look nice, white on dark gray, the
“SHARE” and “WEB SEARCH” icons are black on dark gray.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?

every time
Paste the "debug info" from the AnkiDroid "About" dialog below (see the
above help webpage for detailed instructions).

AnkiDroid Version = 2.5alpha45

Android Version = 4.4.2

ACRA UUID = e73611b6-1f73-45c3-a008-b6cab11758b0

Please provide any additional information below.

```

Reported by `ospalh` on 2015-07-06 10:46:55

**Comment by timrae** [comment]
@ospalh I don't suppose this was automatically fixed when I updated the support library?

**Comment by ospalh** [comment]
Unfortunately not.
It looks like the images have not survived the transfer here, so sa a reminder a screenshot done with 2.5alpha48, Android 4.4.4:
![polynesie](https://cloud.githubusercontent.com/assets/1690429/8931262/279be3f8-3535-11e5-8aea-e6390df11694.png)

**Comment by timrae** [comment]
Damn OK. This is almost certainly an Android Support Library bug though, so probably worth reporting it [over there](https://plus.google.com/u/0/+ChrisBanes/posts/A83SVXzi24f)
