### ISSUE TITLE
Port for Windows 10

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3564]
Originally reported on Google Code with ID 2692
```
With Windows 10 Microsoft add an Option to use Android Apps on Windows.

They Say only "small" changes need to be made. Because the Google Services are not
available as example. I guess that in short future the Windows Store becomes more important
and these services are not used in this great app. I would also pay for such a version.
```

Reported by `ChqrC1` on 2015-07-14 10:15:07

**Comment by petkahl** [comment]
I'm a Microsoft employee, and while I'm speaking for myself and not for the company, and I don't work on the team that supports this, I did get access to the tools and put AnkiDroid on my Windows phone with 0 changes, and it seems to work without issue (but see below). I haven't used it a ton, but it was pretty straightforward.

Two things to note. This is ONLY for Windows Mobile 10 (which isn't released yet, but available in beta), not Windows desktop, and the one change that would need to be made, that I haven't investigated at all yet, is that the directory for loading from SD would have to be tweaked. All I can say for sure is that the default didn't work.

**Comment by ray-pixar** [comment]
It seems that the bridge project is dead.
[http://www.theverge.com/2016/2/25/11117430/microsoft-android-apps-windows-10-port-dead](url)

what should we do now ?

**Comment by hssm** [comment]
There isn't really anything for us to do. It could have been useful if they followed through with it.

**Comment by petkahl** [comment]
Yes, I agree. If that project ever comes alive again. I'll bring it back up. And if I ever end up with copious free time (unlikely) I'll do a C# port.

**Comment by ray-pixar** [comment]
@petkahl 
> Yes, I agree. If that project ever comes alive again. I'll bring it back up. And if I ever end up with copious free time (unlikely) I'll do a C# port.

I'm a C# developer since 2002 and I firmly believe that's the best language ever. Also I'm a big fan of Anki. I was really looking forward to see the C# port. I know you love Anki too. I would appreciate if you consider the possibility of a joint work. Could you submit the base C# port to github and I'll continue it?

**Comment by SRGOM** [comment]
@ray-pixar  don't think pet-kahl has any c# cursed at this point- he is running unmodified ankidroid. Having said that- is anyone working on a c# client?

**Comment by petkahl** [comment]
Correct, I have no code 

That said, Anki Universal, now available on the Windows store, is perfect for me, as it's using existing files, and was able to import my status and stuff, and working across my phone and desktop, so it works for me. Wouldn't work if you needed to sync between android or iPhone and Win phone or Windows PC, as it doesn't use AnkiWeb for it's sync.

**Comment by timrae** [comment]
I just checked the source code for anki universal and it does actually
appear to be using anki web. The sync server url can be customized on
AnkiDroid, and there's a todo in the csharp about adding this feature as
well:

https://github.com/AnkiUniversal/Anki-Universal/blob/master/AnkiU/AnkiCore/Sync/HttpSyncer.cs

https://github.com/AnkiUniversal/Anki-Universal/blob/master/AnkiU/AnkiCore/Consts.cs

**Comment by srvds** [comment]
Maybe its time for windows store to get an Anki app that actually syncs with ankiweb....
The so called project centennial that bridges desktop app to be useed in the Universal Windows Platform that means xbox,windows phone,and hololens can have a ported desktop app...
https://developer.microsoft.com/en-us/windows/bridges/desktop
