### ISSUE TITLE
MediaSyncer/ Error downloading media files java.lang.RuntimeException: java.io.IOException: open failed: EINVAL (Invalid argument)

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3567]
Originally reported on Google Code with ID 2695

```
Note: If this is your first time submitting an issue, please read the
following webpage:

https://ankidroid.org/docs/help.html


What steps will reproduce the problem?
1. Click sync on android application
2.
3.

What is the expected output? What do you see instead?
I expect the collection to sync. instead I see Ankidroid has encountered a problem
and the syncing hangs at updating database.


Does it happen again every time you repeat the steps above? Or did it
happen only one time?
All the time

Paste the "debug info" from the AnkiDroid "About" dialog below (see the
above help webpage for detailed instructions).

AnkiDroid Version = 2.4.3

Android Version = 4.1.1

ACRA UUID = 4e50dbe2-86c1-4a36-8d9f-04a8a8c6dd53

logcat attached


Please provide any additional information below.

```

Reported by `samantha.lane1` on 2015-07-17 05:11:13

<hr>
- _Attachment: [logcat.txt](https://storage.googleapis.com/google-code-attachments/ankidroid/issue-2695/comment-0/logcat.txt)_

**Comment by tsudoko** [comment]
I'm able to reproduce this issue on ce0404d757f6edbf67abe4a13d9351c4252b0f78 (Android 5.0.1) with a media file containing a character from the Supplementary Multilingual Plane (🦊). The failing call appears to be here:
https://github.com/ankidroid/Anki-Android/blob/ce0404d757f6edbf67abe4a13d9351c4252b0f78/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java#L702

If `destination` contains 🦊, the call throws EINVAL. If it doesn't, everything works fine.

This doesn't seem to be a filesystem issue, I'm able to create files named 🦊 using the shell.

**Comment by timrae** [comment]
It looks like your character has been turned into a fox emoji lol, can you please escape it with backticks?

**Comment by timrae** [comment]
Are we currently showing the name of the offending file to users in the error message? The list of valid characters is probably manufacturer dependent, I can't find an official list of characters that is guaranteed to work.

**Comment by tsudoko** [comment]
> It looks like your character has been turned into a fox emoji lol, can you please escape it with backticks?

It is a fox emoji, emoji are Unicode characters.

> Are we currently showing the name of the offending file to users in the error message?

Didn't show up for me, had to look at the logs.

**Comment by timrae** [comment]
Ah ok that's pretty weird that some random emoji Unicode character doesn't work... What does the filename look like in your file explorer after you added it via the shell? Does it get rendered or does it just show the hex?

It sounds like adding the filename to the error message could help a lot of users to figure out how to fix the issue. Would you be interested in making a pull request for this?

**Comment by tsudoko** [comment]
> What does the filename look like in your file explorer after you added it via the shell? Does it get rendered or does it just show the hex?

`ߦʀ`. Seems like an OS issue, tried 4 different file managers and it's like that in all of them.

> It sounds like adding the filename to the error message could help a lot of users to figure out how to fix the issue. Would you be interested in making a pull request for this?

I'll try.

**Comment by mikehardy** [comment]
Unrelated, just as a possible root cause I learned in #5795 that older android has worse and worse emoji support until you get to android 4 where it doesn't have any really. The system just can't handle them.

A general solution might be to have media check warn on filenames that aren't valid in a given API, or just wait for this to get even more stale until everyone is using Android 7 or higher where unicode is well supported (probably 3 years from now)
