### ISSUE TITLE
AnkiDroid not reporting errors

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3569]
Originally reported on Google Code with ID 2697
```
Note: If this is your first time submitting an issue, please read the
following webpage:

https://ankidroid.org/docs/help.html


What steps will reproduce the problem?
1. Install AnkiDroid (2.5beta only?)
2. Look at Settings/General settings/Error reporting mode
3. See that the setting says “Ask me”
4. Crash AnkiDroid

What is the expected output? What do you see instead?

An error report should be send.
Instead, logcat produces lines like
"E/ACRA    (21299): ACRA is disabled for com.ichi2.anki - forwarding uncaught Exception
on to default ExceptionHandler"
and you get the standard Android app crash dialog.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?

Every time.

Paste the "debug info" from the AnkiDroid "About" dialog below (see the
above help webpage for detailed instructions).


AnkiDroid Version = 2.5alpha47

Android Version = 4.4.4

ACRA UUID = fa28bbf1-3e5e-4093-85da-8409da7acd68

Please provide any additional information below.

This seems to be a problem with the prefs value.
When you switch it to "never report" and back to "ask me" and *then* crash AnkiDroid,
the ACRA crash reporter comes up. But somehow only once. When you uncheck the "Send
error reports automatically" in the "⚠ Feedback" dialog, send one report and crash
again you seem to be back on square 1. ???

```

Reported by `ospalh` on 2015-07-22 09:08:18

**Comment by timrae** [comment]
@ospalh The behavior you're describing sounds like what I'd expect if you were using a version that you compiled yourself (i.e. crash reporting is intentionally disabled for debug versions). Can you please confirm whether or not you experienced this with the official apk? We are still receiving crash reports as expected up to an including alpha47

**Comment by ospalh** [comment]
Hmm. I was using my own build (but standard develop, not with my patches).
Switching off error reporting, at least at first, for non-official builds sounds like a good idea.
But my complaint is the discrepancy between what the app does and what the prefs show you the app will do.
When the error reporting is switched off, it should say so in the settings.

**Comment by timrae** [comment]
Yeah that will be enough to trigger a false value for `BuildConfig.DEBUG`
I see your point though
