### ISSUE TITLE
Descriptions of the answer buttons aren't translated into Japanese.

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3578]
"AGAIN","HARD","GOOD","EASY" aren't translated into Japanese.

AnkiDroid Version = 2.5alpha49

**Comment by hssm** [comment]
Hmm yeah I just noticed this in the build output:
```
warning: string 'contextmenu_deckpicker_inflate_deck' has no default translation.
warning: string 'ease1_successive' has no default translation.
warning: string 'ease2_successive' has no default translation.
warning: string 'ease3_learning' has no default translation.
warning: string 'ease3_successive' has no default translation.```

**Comment by hssm** [comment]
Yeah we [renamed those values recently](https://github.com/ankidroid/Anki-Android/commit/f28832c0837c913a3462b7d0b1a69c91fba7b95e#diff-20f7f7e5daf9215fe7464a7b993aab4dL214). It'll be fixed when we pull in the latest translations from Crowdin.

**Comment by timrae** [comment]
I have pulled the new translations since that commit. Renaming the strings
both locally and remotely (via the web interface) is supposed to allow
renaming strings without re-translation, but unfortunately the translations
are being pulled in with their old names. I'll contact crowdin support.

**Comment by timrae** [comment]
Apparently you can't rename the strings via the web interface (though I'm sure I read an article saying that you could, and which even let me do that). To rename strings and keep the old translations we should instead rename them in the translated xml files and then upload the translations to crowdin. I've done that now, and the translations for these buttons will be available in the next alpha.
