### ISSUE TITLE
Move a string to 01-core?

### ISSUE THREAD

**Issue by ospalh** [ankidroid/Anki-Android#3580]
The pluralized string `stats_today_cards_not_bold` in `values_NN/06-statistics.xml` is highly visible. That is the “Studied x card(s) in y minute(s)” at the bottom of the deck picker.
I think it should be moved to `01-core.xml`.

I could just move that, as i am working on code related to that string, but am wary to do that.
When a string is moved from one file to the other, does it keep its translation at crowdin?

Similarly, i think the naming should be the other way around. The `stats_today_cards_not_bold` should be something like `cards_studied_today` and `stats_today_cards` something like `cards_studied_today_bold`. I guess that one should stay in 06-satistics, as it is used only in the stats activity.

I guess renaming these strings, if done, should wait until i am through with my time formatting changes (soon) to avoid merge conflicts.

**Comment by timrae** [comment]
> I could just move that, as i am working on code related to that string, but am wary to do that.
When a string is moved from one file to the other, does it keep its translation at crowdin?

I don't think so. I can manually move it though if necessary. Please remind me after your time formatting changes.

**Comment by ospalh** [comment]
Letting `stats_today_cards` keep its name that i find aesthetically not perfect outweighs the trouble of changing the trouble of dealing with a changed string name, so that should stay. The other one is done in #3583.
