### ISSUE TITLE
Aligning the beginning of deck titles

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3585]
On AnkiDroid,
a deck which has an arrow icon looks as if it is a subdeck of the deck above.

![anki indent](https://cloud.githubusercontent.com/assets/10436072/9025883/3c6a4cb2-3953-11e5-9d7f-a6d9399ebdf0.png)
 
Ankidroid Version: 2.5alpha49

**Comment by hssm** [comment]
This was bothering me too actually. When I redid the expander I tried to make it as close as possible to the original instead of making it better. I've pushed a fix for it.

**Comment by snowtimeglass** [comment]
Thank you for the fix!
