### ISSUE TITLE
Adding summaries (supplementary explanations) to some more items of settings

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3595]
How about adding summaries (supplementary explanations) to some more items? 

For example,

"Graduating interval"
"Easy interval"
"Starting ease"
"Easy bonus"
"Interval modifier"
"Maximum interval"
"New interval"
"Leech threshold"

![image](https://cloud.githubusercontent.com/assets/10436072/9060710/4908a154-3af1-11e5-90fc-d8c35bac7aaa.png)

Especially for beginners,
The items seem to be too difficult to understand without reading Anki manual carefully.
For the moment, it seems to be troublesome for them.

**Comment by timrae** [comment]
From the [Android guidelines](https://www.google.com/design/spec/patterns/settings.html#settings-labels-secondary-text):
> For non-switch settings, secondary text should show the current status of a setting only.
