### ISSUE TITLE
UU language cannot be changed

### ISSUE THREAD

**Issue by pizzamx** [ankidroid/Anki-Android#3599]
v 2.4.3
android rom 5.1.1
reproduce:
1. change LANGUAGE in GENERAL to whatever
2. the UI language stays unchanged, which is the phone's local language setting.

**Comment by pizzamx** [comment]
Sirry for title typo. UU should be UI.

**Comment by pizzamx** [comment]
OMG...typing over cell is killing me

**Comment by timrae** [comment]
You have to restart the app for it to take effect, and choose a language
that has been translated like Japanese

OMG...typing over cell is killing me

—
Reply to this email directly or view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/3599#issuecomment-128471095>
.

**Comment by pizzamx** [comment]
I just want English.
And I've restarted it hundreds of times...

It just happened with this latest version upgrade and I am not sure if it
has anything to do with my android system.
2015年8月7日 上午1:46于 "Tim Rae" <notifications@github.com>写道：

**Comment by timrae** [comment]
Have you tried uninstalling and reinstalling AnkiDroid?

**Comment by pizzamx** [comment]
No. Just tried, doesn't work
2015年8月7日 上午7:54于 "Tim Rae" <notifications@github.com>写道：

> Have you tried uninstalling and reinstalling AnkiDroid?

**Comment by timrae** [comment]
Hmm are you using a stock ROM? It seems unlikely to be a problem with AnkiDroid.

**Comment by pizzamx** [comment]
No it is not stock...I'd better figure another way
2015年8月9日 上午11:49于 "Tim Rae" <notifications@github.com>写道：
