### ISSUE TITLE
Scheduling of cards review doen't wofk correctly

### ISSUE THREAD

**Issue by aktok-com** [ankidroid/Anki-Android#3601]
AnkiDroid Version = 2.4.3

Android Version = 5.0.2

ACRA UUID = d0812ad7-f07a-4955-8daa-3dac28b75de8

Some times, quite often, I schedule to show a card after 10 days, but it may be shown after few days as new card. 

Also may be shown some cards from another deck, not too often .

**Comment by hssm** [comment]
Are you able to use the Desktop client to verify that they were not rescheduled correctly? It sounds like your notes are generating multiple (similar or identical) cards, and you are confusing the two.

**Comment by aktok-com** [comment]
Yes, you are right, I found that I have 2 cards for "basic" type, where should be only one card. 
I've cleaned my deck, and I'll test it for several days.

Thank you.
