### ISSUE TITLE
Allow to un-do “force full sync”

### ISSUE THREAD

**Issue by ospalh** [ankidroid/Anki-Android#3604]
When you accidentally touch the option “Force full sync” there is no way to undo this.
When you have changes on both sides, you’re out of luck and those on one side will be lost.
(This came up in Google groups, but i’ve thought this was as problem, too.)

Maybe make this a check box instead, that can be unchecked before the next sync is triggered, and then gets unchecked when a full sync is done?

**Comment by timrae** [comment]
Should be relatively simple if you delay the setting of mod schema until the sync button is actually pressed.

**Comment by ospalh** [comment]
I don’t like the current way this is done, both in Anki desktop and AnkiDroid, doing the full sync in two steps, with maybe hours between them.
See https://anki.tenderapp.com/discussions/ankidesktop/14688-one-step-voluntary-full-sync

**Comment by RawToast** [comment]
Full Sync has always been a bit of a pain.

@ospalh I guess you mean "checked before the next sync"? So after one full sync, the client reverts back to the standard sync to avoid running two full syncs?

**Comment by mikehardy** [comment]
It is allowed, it's called "restore from backup"
