### ISSUE TITLE
Document "question" and "answer" CSS Classes in Manual

### ISSUE THREAD

**Issue by eliptus** [ankidroid/Anki-Android#3606]
I was having trouble getting my CSS styling that worked on Windows and Mac Anki to work in AnkiDroid.  It turned out that the problem was my use of custom CSS classes "question" and "answer", which apparently have special meaning to AnkiDroid, but are not documented in the manual.  The link to the discussion that led to this realization is below.

https://groups.google.com/d/topic/anki-android/8F283rkTZVU/discussion

**Comment by timrae** [comment]
Thanks, I moved it to the ankidroiddocs repository

**Comment by timrae** [comment]
I've made a new wiki page here:

https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting

The `question` and `answer` css classes aren't described though; @ospalh would you be able to add to the documentation?
