### ISSUE TITLE
Is the "real full screen" available for Ankidroid?

### ISSUE THREAD

**Issue by ivanhg** [ankidroid/Anki-Android#3608]
Since when I select full screen mode for reviewing, only the top status bar is hidden but the bottom buttons remain. This produces an issue for me. Since these buttons are right under the Ankidroid buttons it's easy to tap on the wrong button when I'm focusing or getting slightly quicker on learning. So I wonder if the real completely full screen available yet?
![a](https://cloud.githubusercontent.com/assets/9710620/9214150/a43eef2a-40cc-11e5-8c62-6d6006f8a1ad.JPG)

**Comment by timrae** [comment]
Hi, yes immersive mode is used in the latest alpha version:
https://github.com/ankidroid/Anki-Android/releases

**Comment by ivanhg** [comment]
Thanks!
