### ISSUE TITLE
hello everyone,  i am new member!

### ISSUE THREAD

**Issue by John0079** [ankidroid/Anki-Android#3610]
hello, everyone, i come from china, I have used Ankidroid for about two years, 
i think it is a great learning software. before, i am just a user of the software, but now i want to become its developer and to expand its function, so i come here. i hope i can become your friend, thanks!

**Comment by timrae** [comment]
Hi John,

Welcome aboard!
We normally use the [forum](https://groups.google.com/forum/#!forum/anki-android) for discussions that aren't directly related to a specific bug or enhancement in AnkiDroid, but if I remember correctly you can't access the forum from China?

**Comment by John0079** [comment]
Hi Tim,
Thank you for you recognized me.
yes, you are right, i can't access the forum. it is a great pity, maybe  i can find another way to access it . let me try...
