### ISSUE TITLE
How is the method "loadInBackground() " called in Class "CollectionLoader.class"

### ISSUE THREAD

**Issue by John0079** [ankidroid/Anki-Android#3611]
in the CollectionLoader.class, there is a method named "loadInBackground()", i want to know how is the method is called, i have debug about two days, i haven't find where it is called, 
by debug and logcat, i found it is called after "onStart()" methed of "DeckPicker.class", but i cann't comfirm which methed call it.
wait help.....

**Comment by timrae** [comment]
Hi John,

Loading the `Collection` can take quite a long time, so we start that in a background thread in the `onCreate()` method of most of the Activities via the method `startLoadingCollection()`. When the background thread is finished, the method `onCollectionLoaded()` will be automatically triggered.

It's not really necessary to understand the internal workings of the `CollectionLoader` class, but the `loadInBackground()` is a method of the parent class [`AsyncTaskLoader`](http://developer.android.com/reference/android/content/AsyncTaskLoader.html). It is called automatically by the Android framework, and runs in a background thread.

**Comment by timrae** [comment]
You can read more about loaders here if you are interested:
http://www.androiddesignpatterns.com/2012/07/loaders-and-loadermanager-background.html

**Comment by John0079** [comment]
Tim,
Thank you very much, 
under your guidance, i have found this method is called via "doInBackGround()" in "AsycTaskLoader.class". it's great. meanwhile, i learned a new Asnc method to load data!
Thank you very much again.
