### ISSUE TITLE
Is it necessary to "setBackgroundResource()" in the Item of "mDeckListView" ?---DeckPicker.class

### ISSUE THREAD

**Issue by John0079** [ankidroid/Anki-Android#3613]
Hello everyone,
  today, i study the DeckPicker.class, i don't understand why call the method: line432:
view.setBackgroundResource(R.drawable.white_deckpicker_top);
is it  necessary to ajust the arg "text", then to set the item's background color?
i have never seen it‘s screen effects?
![viewbinder0](https://cloud.githubusercontent.com/assets/7960973/9303938/813ac998-4515-11e5-8ec8-e67eff4812d7.png)

**Comment by timrae** [comment]
Hi John,

Probably you are looking at an old version of the code, as that line doesn't exist in the current version of the `develop` branch. Please do a `git pull upstream develop` to get the latest code.

**Comment by John0079** [comment]
Hi Tim,

yes, i am looking at V2.3.2 , because, when i try to import the new version into the Eclipse, it always meet some error, so i still use the old version.

**Comment by timrae** [comment]
Eclipse is no longer supported, please use Android Studio.
A lot has changed since 2.3.2 so it will be difficult to contribute

There are instructions on the wiki here:
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide

(I encourage you to add documentation about the DB structure etc to the development wiki!)

**Comment by John0079** [comment]
ok, but i don't know how to use Studio, next step, i will take some time to learn how to use it.

**Comment by timrae** [comment]
:+1: 
Good luck. Eclipse is now considered obsolete by Google, so now is a good time to learn Android Studio.

**Comment by John0079** [comment]
it is not a good luck, bucause, i just learned how to use Eclipse! i don't have any friend who know how to use android studio. it is so bad !

**Comment by John0079** [comment]
ok , i have to switch android studio.

**Comment by timrae** [comment]
From the [official Android documentation](https://developer.android.com/sdk/index.html):

> If you have been using Eclipse with ADT, be aware that Android Studio is now the official IDE for Android, so you should migrate to Android Studio to receive all the latest IDE updates.

Android studio is much nicer to use than Eclipse, I would recommend telling your friends about it.

**Comment by John0079** [comment]
ok ,thank you very much, but the first step, i have to download Android studio,  and  install it 
do you have some good advice to install it, i don't have a little experience about it

**Comment by timrae** [comment]
I don't really understand your question sorry... just download from [here](https://developer.android.com/sdk/index.html) and run the installer

**Comment by John0079** [comment]
it is very bad, i can't open the website, so i can't get andrioid studio installing file.  can you shared your installing file to me by email? thanks!

**Comment by timrae** [comment]
Hi John, that's very sad that your government is blocking crucial development tools.
I have uploaded Android Studio and the Android SDK for Windows to the cloud, you can download from [here](https://mega.nz/#F!p0dT1Coa!sAelVwRXG3DChFSe5cYUZg)

**Comment by timrae** [comment]
I'm a bit worried that you won't be able to get the necessary SDK components though... You may need to use a VPN

**Comment by John0079** [comment]
yes, i am trying to get  a VPN account.

**Comment by timrae** [comment]
I put a new folder inside the mega.nz link, maybe it will be useful for you

**Comment by John0079** [comment]
I just bought a Vpn account , now, i have accessed  the website and begin to download Android studio.
which new folder? where is the mega.nz link? I did't find it, is it at https://github.com/ankidroid/Anki-Android  ?

**Comment by timrae** [comment]
https://mega.nz/#F!p0dT1Coa!sAelVwRXG3DChFSe5cYUZg

**Comment by timrae** [comment]
You don't need a VPN to access that link though...

**Comment by John0079** [comment]
Tim,
Thanks you very much, you are so kind! , i have open the website.

**Comment by John0079** [comment]
Hi Tim, 
can you tell me how to access the welcome screen, at the first time, i can open the welcome screen, when i open android stutio again, this screen will be skiped, how can i open it again?
![qq 20150818161709](https://cloud.githubusercontent.com/assets/7960973/9325401/9b3fc30c-45c4-11e5-9a51-7931741bd4ee.jpg)

**Comment by timrae** [comment]
File -> Close project

**Comment by John0079** [comment]
ok, yes , thank you!

**Comment by John0079** [comment]
Tim,
I can't get Android studio code example, how to get Android studio's official help, maybe some forum or website, maybe some email, i can submit my question,  can you give me some advice?
![qq 20150818173245](https://cloud.githubusercontent.com/assets/7960973/9326817/33ca9f48-45cf-11e5-8047-7d0876a96c66.png)
![qq 20150818172844](https://cloud.githubusercontent.com/assets/7960973/9326821/3dcabb90-45cf-11e5-9e35-058929e89d01.png)

**Comment by timrae** [comment]
Did you set up your VPN correctly?

**Comment by John0079** [comment]
my VPN is an add-on in Chrome browser, now, i can access google website by the chrome browser, but i don't know Android studio is how to access some website.

**Comment by John0079** [comment]
i have found how to change Android studio's default browser, but i need add the target website address into the chrome browser's address list, i don't know the address to get "android studio example code" . so it don't work still.

**Comment by flerda** [comment]
You do not need the samples to work with AnkiDroid code.
But the samples are also available on GitHub, so that you can get them from there instead:
  https://github.com/googlesamples

**Comment by John0079** [comment]
i found them on Github, Thank you very much.

**Comment by timrae** [comment]
In the mega.nz link, I gave you instructions for how to use Psiphon3.
I have never tried to use it myself, but it sounds like it should work.
A VPN which only works for chrome will not allow you to update the Android
SDK, which is required by AnkiDroid.

**Comment by John0079** [comment]
ok, it is good, last night i buy some introduce vedios about how to use Android studio, now, i am watch them. so, i meet so many question. thank you very much again, and flerda, you helps let me know this is a good team. i'am very luck to join it.

**Comment by John0079** [comment]
Hi Tim,
 everything is ok, thank you very much,
before I just open Psiphon, but didn't  open the vpn model, so ..... ,
now, i can begin new work.
