### ISSUE TITLE
i can't download requested components, how to continue?

### ISSUE THREAD

**Issue by John0079** [ankidroid/Anki-Android#3614]
i can't download requested components, how to continue?
when i import the project "Anki-Ankidroid-2.4.3" , studio report error, it says "failed to find Build tools reversion 19.1.0", 
when i try to click link the "install Build tools 19.1.0 and sync project" below to the report, it always is that "connection time out", so i can't download requested component. what should i do?

**Comment by John0079** [comment]
why i can't submit picture,when i summit a question, and attach images, the website always tell me "something went really wrong, we can't process the file", but i try the same picture as the one i submitted yesterday, it still give this message. do you have ever meet this question?
![Uploading QQ图片20150818173245.png…]()

**Comment by timrae** [comment]
As I told you repeatedly, you will need a VPN to update the SDK (a proper VPN not just a chrome plugin). I even gave you instructions on how to use one (psiphon3). If that doesn't work you can try [this](http://stackoverflow.com/a/19944570/2125915)... 

Anyway, if you have VPN working please post to the [forum](https://groups.google.com/forum/#!forum/anki-android) for help, not github issues.

**Comment by John0079** [comment]
Hi Tim,
when i try to open one of layout file, the system reminds me 
"Unable to find the layout for Action Bar. Consider updating to a more recent version of appcompat, or switch the rendering library in the IDE down to API 21"

can you tell me how to updating a more recent version of appcompat, or how to switch the rendering library in the IDE , or you have other way to resolve the problem.

**Comment by timrae** [comment]
I don't know sorry. You should be able fyi edit the xml and compile despite
the error though

**Comment by John0079** [comment]
Tim, 
as you said, i can edit the xml and compile.
about that question, i think maybe i can find answer from android forum.let me try.
thank you very much.
