### ISSUE TITLE
Sync Error 2131624605

### ISSUE THREAD

**Issue by jadios101** [ankidroid/Anki-Android#3615]
"Your database is corrupt. Please fix it before tryinh again to sync.
See 2131624605 for information about repairing your database."

Could anyone help me? I don't know what to do.

**Comment by hssm** [comment]
We've had a report of this error before but never learned anything about it. That number doesn't appear anywhere else apart from AnkiDroid issues, and the database that we use (SQLite) doesn't have this number anywhere in its source code, so I'm really puzzled about what it could mean.

Are you able to use AnkiDroid normally? Does it only fail on sync? Is it a full or partial sync? Did it used to work normally before and fail later on?

**Comment by timrae** [comment]
I know what's happened here lol. 2131624605 is not an error code, it's supposed to be a [link to the Anki documentation on corrupt databases](http://ankisrs.net/docs/manual.html#corrupt-collections). I fixed the string issue in #3620.

As for the database corruption, you can try running "check database" from the deck picker menu. If that doesn't work, you'll need to restore from a previous backup, or manually repair the collection as per the link that was supposed to appear in that dialog: http://ankisrs.net/docs/manual.html#corrupt-collections

See also #3576
