### ISSUE TITLE
Answer buttons size not always respected

### ISSUE THREAD

**Issue by nicolas-raoul** [ankidroid/Anki-Android#3621]
My `Answer button size` is set to 170%

Despite that, the buttons sometimes (rarely) appear at just 100%.
Especially when I start reviewing.

**Comment by cameel** [comment]
It happens for me too (with scaling set to 150%). It only happens just after i enter the deck. When I click `show answer`, the rating buttons appear and they have the correct sizes. `show answer` on the next card is also scaled properly.

I see that I'm not the only one using this option. Maybe it makes sense to make the answer buttons a bit larger by default on bigger screens? On a tablet the current default makes it way too easy to hit the system buttons by accident.
