### ISSUE TITLE
Unclear what the graph in the tablet deck option is about

### ISSUE THREAD

**Issue by ospalh** [ankidroid/Anki-Android#3624]
On a tablet (xlarge layout) with the two-in-one deck picker deck options layout, there is a graph shown.

There is [no information what the graph is about](https://xkcd.com/833/).

I think the x-axis is days, but is the wrong way around, with the present as “0” and the *past* to the right.

**Comment by hssm** [comment]
I think this graph was only ever added as filler. There was too much blank space on a large tablet which looked ugly, so we filled it in with something. I never thought it was very useful myself (then again I don't review on a tablet).

We could just drop it. Or, better, replace it with something more meaningful (if anybody has any ideas).

**Comment by timrae** [comment]
I've dropped it in the latest version. I think it would be nice to replace it with the pie graph of the "cards types", but it's not something that I'm planning on working on
