### ISSUE TITLE
Remove dependence on deprecated Apache HTTP client

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#3626]
[Android Marshmallow has removed the Apache HTTP client](https://developer.android.com/preview/behavior-changes.html#behavior-apache-http-client). 
Consequently, AnkiDroid doesn't compile with SDK 23.

The `useLibrary` workaround given by them did not appear to fix the broken import of `org.apache.http.HttpResponse`. 

I have no idea why that didn't work, but it's probably not a good idea to keep using it anyway. According to [this stackoverflow](http://stackoverflow.com/questions/30556605/org-apache-http-httpentity-is-deprecated-how-to-solve-this-error-in-android-s):

> If you need to continue using the HttpClient API, consider switching to [OkHttp](http://square.github.io/okhttp/) and their HttpClient compatibility layer, or consider switching to [Apache’s separate Android edition of HttpClient](https://hc.apache.org/httpcomponents-client-4.3.x/android-port.html). Otherwise, switch to HttpURLConnection or OkHttp’s native API.

**Comment by hssm** [comment]
The `useLibrary` workaround *did* work for me. The compilation still fails further on over the Notification changes (also mentioned on the changes page) which I tried commenting out and it compiles and runs successfully.

**Comment by timrae** [comment]
Hmmm OK I'm not sure why that happened for me. That API is deprecated though, so we should consider switching to `OkHttp`, as the old API is supposed to be quite inefficient in terms of battery usage.

**Comment by timrae** [comment]
> Google Android 1.0 was released with a pre-BETA snapshot of Apache HttpClient. To coincide with the first Android release Apache HttpClient 4.0 APIs had to be frozen prematurely, while many of interfaces and internal structures were still not fully worked out. As Apache HttpClient 4.0 was maturing the project was expecting Google to incorporate the latest code improvements into their code tree. Unfortunately it did not happen. Version of Apache HttpClient shipped with Android has effectively become a fork. Eventually Google decided to discontinue further development of their fork while refusing to upgrade to the stock version of Apache HttpClient citing compatibility concerns as a reason for such decision. As a result those Android developers who would like to continue using Apache HttpClient APIs on Android cannot take advantage of newer features, performance improvements and bug fixes.

**Comment by hssm** [comment]
There are definitely good reasons to replace it then. I'd like to see if there's any appreciable speed improvements since our sync is kinda slow compared to the desktop client.

For our use case I think the built-in `HttpURLConnection` should be enough. I might try doing this some time soon.

**Comment by timrae** [comment]
I'm keen to go forward with the beta release ASAP, so for now let's just update to the official Apache HttpClient 4.4 via [this package](https://github.com/smarek/httpclient-android/wiki/Project-Introduction)

I definitely think it would be a good idea to update to `HttpURLConnection` in a future release if that's possible (or maybe OkHttp if it's not), as an Android specific library should be quite a lot more battery efficient, and the code should be much more readable / maintainable with a simpler API.

I'll close this issue now as #3674 accomplishes the original goal of the issue. Feel free to make a new issue if you're still interested in switching over to a different HTTP API.

**Comment by timrae** [comment]
It looks like updating the HttpClient broke our `EasySSLSocketFactory` class (see #3787). I didn't notice at the time, but all our http code is full of deprecated class warnings after the update, so I don't think it's worth trying to fix.

@hssm 
Did you end up look at switching over to `HttpUrlConnection`? If that looks too hard, it might actually be easier to use the lower level OkHttp, which is what HttpUrlConnection uses internally.

Depending on how much work is involved in upgrading I guess we should either switch back to the old apache client with the `useLibrary` workaround, or switch to an OkHttp based implementation (either directly or via HttpUrlConnection).

What do you think?

**Comment by timrae** [comment]
It seems OkHttp have a compatibility layer where they implement the Apache API:

> You can try out OkHttp without rewriting your network code. The okhttp-urlconnection module implements the familiar java.net.HttpURLConnection API and the okhttp-apache module implements the Apache HttpClient API.

That might involve less work and risk than a full rewrite

**Comment by hssm** [comment]
I think we should stick to the `useLibrary` approach to avoid any more surprises for this release. It's been working fine up to this point, and we can't really tell if any of the updates to the underlying libraries have any effect for us.

> it might actually be easier to use the lower level OkHttp, which is what HttpUrlConnection uses internally

You mean that the other way around, right?

When I first looked into using HttpUrlConnection I realised it'll be a pretty big job and left it for the next release (or the one after if we have to). I don't think we're in a hurry to replace it. The advantage of HttpUrlConnection is that we don't drag in a whole new dependency with a whole lot of stuff we don't use along with it.

The only reason to use OkHttp is that we don't have to rewrite stuff to end up with non-deprecated libraries. I.e., OkHttp is the easy way but HttpUrlConnection is the preferable way. It really comes down to someone putting in the work for it when the time comes. For now, I think it's best to stick to the existing library with `useLibrary`.

Those are my thoughts, at least.

**Comment by hssm** [comment]
>You mean that the other way around, right?

Okay I guess not. I'll read up on this later. It's a bit confusing.

**Comment by timrae** [comment]
> I think we should stick to the useLibrary approach to avoid any more surprises for this release. It's been working fine up to this point, and we can't really tell if any of the updates to the underlying libraries have any effect for us.

Agreed. I'll probably push a PR through tomorrow.

>> You mean that the other way around, right?

> Okay I guess not. I'll read up on this later. It's a bit confusing.

Yeah it's not really obvious from the AOSP code that it's using OkHttp, but [it is](https://twitter.com/jakewharton/status/482563299511250944). I saw it boil up on a stacktrace in the Acra library once. I was thinking it could be less effort if the OkHttp API is more similar to the Apache one than it is to the Android one, but the native Android API is the least likely to change, so should be the "best" assuming it does everything that we need it to.

**Comment by mikehardy** [comment]
The API change documentation has moved:
https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-apache-http-client

And the HttpURLConnection should be sufficient I think, it's here:
https://developer.android.com/reference/java/net/HttpURLConnection

**Comment by mikehardy** [comment]
Closer to contemplating doing this - just leaving a breadcrumb from an associated issue - a PR using OkHttp is potentially acceptable (depending on how it looks and performs of course) as it seems a 3rd party library - especially the one made by the developers the platform keeps adopting - ApacheHttp then OkHttp - may be slightly more reliable than the platform in this case http://square.github.io/okhttp/3.x/okhttp-urlconnection/deprecated-list.html

**Comment by mikehardy** [comment]
I already have this removed while still syncing in draft form and it *must* go away to solve #5623 (which will be the next phase of this PR: https://github.com/ankidroid/Anki-Android/pull/5658

Since it is inevitable and will have a separate issue tracking it, I'm going to close this one
