### ISSUE TITLE
Reverse text direction (RTL) field option not respected

### ISSUE THREAD

**Issue by mx3214** [ankidroid/Anki-Android#3628]
What steps will reproduce the problem?
1.Input arabic text on computer and load deck on ankidroid 2.4.3 or view on anki pc program.

What is the expected output? What do you see instead?
Desired output is arabic text RTL.  Text that it output is normal.  

Updated: 18:30 31.08.15
I realised the problem is with the reviewer. The cards don't show properly in it. Please see screenshot below. However in the editor (what I use to make the cards) the format is perfect.

**Comment by hssm** [comment]
- Which part of the application has the problem (reviewer or editor)?
- Have you toggled the RTL setting for the field on desktop client (Tools -> Manage Note Types... -> Fields) 
![rtl](https://cloud.githubusercontent.com/assets/789082/9577803/f238ad50-5027-11e5-8da2-c1757ba9af19.png)
- Do you combine RTL and LTR text in the same field?

**Comment by hssm** [comment]
A screenshot would be helpful as well.

**Comment by mx3214** [comment]
Thanks for the reply.

1) The problem only exists in the ankidroid app. In the anki pc program it works completely fine both in reviewer and editor.

2) I have selected the RTL setting for the field on desktop client - and that is why on the desktop client it works perfectly I believe.

3) I don't combine RTL & LTR. Even the brackets that are in the attached images are in the same direction as the text - either RTL (if front card), and LTR (if back card)

Thank you for your help. I really appreciate it.
![screenshot_2015-08-31-12-56-44](https://cloud.githubusercontent.com/assets/14053275/9578300/84bc282a-4fe0-11e5-8325-b2a39ba98984.png)
![pc anki working fine](https://cloud.githubusercontent.com/assets/14053275/9578308/94345b2e-4fe0-11e5-9695-6a610a0fffa3.JPG)

**Comment by ospalh** [comment]
>  I don't combine RTL & LTR

Hmm. The number “1” looks European. And Unicode [notes]( http://www.fileformat.info/info/unicode/char/0031/index.htm) a “directionality” different from that for, say, “[١](http://www.fileformat.info/info/unicode/char/0661/index.htm)” or [Arabic letters](http://www.fileformat.info/info/unicode/char/search.htm?preview=entity&q=arabic%20letter).

(The parentheses are directionally neutral, and probably not causing this.)

(I am not saying that this makes AnkiDroid’s current behavior OK. It may just be a hint to what went wrong.)

**Comment by mx3214** [comment]
I'm not sure about the number, to my knowledge its in the same language as the arabic text (I didn't switch languages on my keyboard when I was typing it).

Also my mistake about it being a problem in only ankidroid. The problem occurs in both the PC and android version, however only in REVIEWER. Very sorry about not realising this earlier.

Thank you for all your help.

**Comment by mx3214** [comment]
Here is a screen shot describing my problem;
![problemo](https://cloud.githubusercontent.com/assets/14053275/9585635/1bd7e42c-5010-11e5-8064-26e684f2b55c.jpg)

**Comment by hssm** [comment]
I think the issue is clear then. The checkbox marking a field as RTL is actually not used anywhere in AnkiDroid, and evidently not in the desktop previewer either. Shouldn't be a difficult fix I think. It would save me a lot of time if you could export that deck and send me a copy.

**Comment by mx3214** [comment]
Okay great! I have sent you the deck.

**Comment by hssm** [comment]
Okay I misread reviewer as previewer (looking at your screenshot) and jumped to conclusions. What I said before was wrong. The RTL checkbox only applies to the note editor and has no effect in the reviewer. It's not meant to.

Luckily, what you are seeing is [documented behaviour](http://ankisrs.net/docs/manual.html#rtl-(right-to-left)-text) and you can easily fix it by modifying your template. In your case, change the front template to ```<div dir=rtl>{{Front}}</div>```.

**Comment by mx3214** [comment]
Problem solved. Thank you for so much for patiently helping me with my problem.

**Comment by TimucinPusat** [comment]
I have the same problem in my back template but I don't know where to put this code which hssm mentioned  <div dir=rtl>{{Front}}</div>

Is there anyone who can help me please? I can share needed info.
