### ISSUE TITLE
"Can't add 0 byte file"

### ISSUE THREAD

**Issue by Snillsparv** [ankidroid/Anki-Android#3629]
For the last months I have had problems every time I try to sync my cards from AnkiDroid, Usually it starts syncing and loads up quite a lot of information but than this error message appears:

java.lang.RuntimeException:
SyncError: Can't add 0 byte file.

Anyone got any idea about how to fix this?

**Comment by timrae** [comment]
Try running check collection and check media

**Comment by Snillsparv** [comment]
Wow, it worked! Thank you so much!! :D

**Comment by timrae** [comment]
:+1:
