### ISSUE TITLE
Floating action button adrift

### ISSUE THREAD

**Issue by ospalh** [ankidroid/Anki-Android#3633]
With
* the newest alpha, 2.5alpha53,  f52c40c, 
* Android 5.1.1 (Cyanogen Mod)
* on a tablet (xlarge layout)

The floating action button is now covering parts of the deck list:

![screenshot_2015-09-04-13-10-02](https://cloud.githubusercontent.com/assets/1690429/9682564/145517b0-5308-11e5-9b33-a386e8d6f944.png)

In Portrait mode it covers some of the due counts, and you can’t scroll the deck list to get a good view

AnkiDroid Version = 2.5alpha53

Android Version = 5.1.1

ACRA UUID = 1de7e18b-4656-47bb-aaa6-8e42f2d59b74

**Comment by timrae** [comment]
Ah yeah thanks I forgot to update the tablet layout in the last PR
On 4/09/2015 8:25 pm, "ospalh" <notifications@github.com> wrote:

With

   - the newest alpha, 2.5alpha53, f52c40c
   <https://github.com/ankidroid/Anki-Android/commit/f52c40c4e1c3177b6a2d855d9711c21737bb4ed4>,

   - Android 5.1.1 (Cyanogen Mod)
   - on a tablet (xlarge layout)

The floating action button is now covering parts of the deck list:

[image: screenshot_2015-09-04-13-10-02]
<https://cloud.githubusercontent.com/assets/1690429/9682564/145517b0-5308-11e5-9b33-a386e8d6f944.png>

In Portrait mode it covers some of the due counts, and you can’t scroll the
deck list to get a good view

AnkiDroid Version = 2.5alpha53

Android Version = 5.1.1

ACRA UUID = 1de7e18b-4656-47bb-aaa6-8e42f2d59b74

—
Reply to this email directly or view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/3633>.

**Comment by ospalh** [comment]
Thanks.
