### ISSUE TITLE
About the "Tab"

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#3635]
(sorry for my poor English.)In the computer the effect like the picture I upload,It's normally,but in the android device the Tab hold eight characters,which waste the precious space in the widthness.How can I adjust the setting?

**Comment by timrae** [comment]
Can you post a screenshot please?

**Comment by Juddd** [comment]
![dis](https://cloud.githubusercontent.com/assets/10048069/9699191/0762211a-540c-11e5-86fe-baa6dc658ca9.jpg)
![dock](https://cloud.githubusercontent.com/assets/10048069/9699192/07650088-540c-11e5-8f24-7fd22277e813.png)

**Comment by Juddd** [comment]
![22](https://cloud.githubusercontent.com/assets/10048069/9699197/331804d2-540c-11e5-96e9-0c9efb7c8bbe.png)

**Comment by hssm** [comment]
If you are using Android 4.4.4 or newer you can specify the tab size in your styling section. E.g.,

``` body { tab-size: 2; } ```

If you are using an older device then you probably can't do much besides removing the tabs and replacing them with spaces. There is a regular expression search and replace feature on the desktop client that could make this quick.

**Comment by Juddd** [comment]
@hssm my device is android 4.2.2,I use your "body { tab-size: 2; }",It's don't work,Do you mean that I can use css to repleacing the "tab" with "two spaces" via regular expression?

**Comment by hssm** [comment]
I mean there is a [find and replace](http://ankisrs.net/docs/manual.html#find-and-replace) feature that you can use to replace the tabs with spaces in the fields themselves. If you are okay with replacing the tabs with spaces **permanently**, then you can go into the browser, select every card, and do this:

![fnr](https://cloud.githubusercontent.com/assets/789082/9702488/e60a857e-54a2-11e5-96ac-35e0bab0d923.png)

**Comment by Juddd** [comment]
Thanks a lot for your enthusiasic help.Eventually,I have solved the problem to transform my font from "Courier New" to "Arial".Now the Tab hold 4-spaces,which  is better than before.

**Comment by Juddd** [comment]
Thanks a lot for your enthusiasic help.Eventually,I have solved the problem to transform my font from "Courier New" to "Arial".Now the Tab hold 4-spaces,which  is better than before.@hssm

**Comment by flerda** [comment]
The general recommendation would be not to use the "tab" character in your card templates and fields.

For the most part, HTML considers all space-characters to be the same, so a tab character will be displayed as a single space on most devices. The only exceptions are tab characters within ```<textarea>``` and ```<pre>``` tags. Some devices (including recent versions of Android, 4.4.4 and above) will allow you to set the size of a "tab" character as a number of spaces using css with:
```css
body {
  tab-size: 8;
}
```
but that's not portable, and might cause issues on some devices.
http://www.w3schools.com/cssref/css3_pr_tab-size.asp
http://caniuse.com/#feat=css3-tabsize
