### ISSUE TITLE
about the background

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#3638]
(sorry my poor English.)
I use the css to set the background,the effect like the screenshot.There are two block still is white.How do I let it same to the background?

**Comment by Juddd** [comment]
![background](https://cloud.githubusercontent.com/assets/10048069/9704532/7fbbf876-54dd-11e5-99ab-53b0a424a18d.jpg)

**Comment by flerda** [comment]
The status bar at the top and the buttons at the bottom are not part of the card template and therefore their background cannot be customized at the moment.
