### ISSUE TITLE
Ankidroid tells me I don't have any card to review when I still do

### ISSUE THREAD

**Issue by daikazoku** [ankidroid/Anki-Android#3640]
Pretty often, but not always it seems, when I try to do my last reviews for the day on ankidroid and I still have tens of learning cards (not new cards) to do, each time I press the study button, a single card is presented, and after I answer ankidroid goes back to the deck screen, even though there are still many cards to do.
If I get that card wrong, the same card is presented over and over, until I answer correctly, and then I am brought back to the deck screen.
If the problem is appearing, it seems to persist until the next day.

I have custom learning steps of 1 10 120. I also enabled notifications on ankidroid.

AnkiDroid Version = 2.4.3

Android Version = 4.3

ACRA UUID = 51cd9153-5165-4dbc-b38a-cc4b674af8d2

**Comment by hssm** [comment]
How does the desktop client behave when the deck has entered this state? Would you be able to send me a deck that exhibits this issue?

**Comment by daikazoku** [comment]
Unfortunately (or fortunately?) I have been able to "fix" the problem by changing the directory and deleting all application data, then resyncing. I could have sent you the smaller deck if I didn't reset everything :(

It happened on both my decks (on the same options group).
Anki for desktop worked without any issue or warning message.

I have a small idea about what could have caused the issue. I think that in the same period that the problem began appearing, I had just reduced my last learning step from 180 minutes to 120 minutes from the desktop client. Maybe this could be triggering the problem?

**Comment by daikazoku** [comment]
It may also help to know that deleting the application data was not enough, I also had to move the collection directory.

**Comment by hssm** [comment]
It does sound like a stepping issue. I'm not sure how moving the collection could impact something like this though. Did you try it on a different day to wiping the data? If I had to guess, the problem went away by moving into the next day and/or syncing. It's just a guess though.

If you encounter it again try to remember the steps you took and export a copy of the deck so we can try to reproduce it ourselves. If possible, export a copy of the entire collection as well, since it *might* be related to the creation time of the collection (which all other scheduling parameters rely on).

This is a similar (or the same) issue: https://github.com/ankidroid/Anki-Android/issues/3474

**Comment by daikazoku** [comment]
No, I I wiped the data and it didn't fix it, so I chose another folder for the collection and it went away. I should clarify that when changing the folder, the collection was not actually moved, instead I had an empty collection and I had to do a full sync.

Reading the first comment in #3474, it appear the issue is identical, and it seems that the same steps I took fixed it for the people in that issue too.

I will actually try to make the problem appear again and I will write here if I'm successful.

**Comment by Hvalfisk** [comment]
I experience this bug too. Removing the widget from the home screen fixes it. I am using 2.5alpha58 though. But I got the bug on 2.4.3 too, that was why I upgraded to the alpha.

**Comment by hssm** [comment]
That could be a separate issue (probably another manifestation of https://github.com/ankidroid/Anki-Android/issues/3430). @daikazoku, are you using the widget?

**Comment by daikazoku** [comment]
Since I don't know what the widget is, I am assuming I'm not using it.

**Comment by dpmm99** [comment]
I also use the widget and occasionally have Anki tell me no cards are due when there are indeed some due, but it allows me to study one or more of the remaining due cards if I simply click the "Study Now" button again from the deck page. Sometimes it kicks me out several times in a row after studying just one card, but there are more due ones, but I can always just hit "Study Now" again.

**Comment by hssm** [comment]
Somehow I missed the line in the opening post where you mentioned
>I also enabled notifications on ankidroid.

Notifications trigger the same problematic behaviour as the widget, so really this is the same issue as #3745 which has been fixed.
