### ISSUE TITLE
ShowCase or tool tips Error 

### ISSUE THREAD

**Issue by KKS161994** [ankidroid/Anki-Android#3642]
SIr when the app is first installed it shows tooltips thats great but if onPause and then onResume is called it again shows the tool tips ... Please if possible Can i solve the bug if you allow me???

**Comment by timrae** [comment]
Add a new deck or some cards and it won't show up anymore

**Comment by KKS161994** [comment]
Okkk sir but dont you think every time it shows up the apps on Resume is
called it makes it somewhat irritating.

**Comment by timrae** [comment]
Yeah it could be annoying for some people, but we've removed ShowcaseView altogether from the development version anyway  :) Thanks for the feedback!

**Comment by KKS161994** [comment]
No problem sir...

**Comment by KKS161994** [comment]
Sir please let me know if i could be of any help to you...

**Comment by timrae** [comment]
Hi @KKS161994, there are definitely issues that you could help us with!
For example [there are a bunch of issues with the statistics](https://github.com/ankidroid/Anki-Android/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3AStatistics+) that it would be good to fix.

There are many other issues in the tracker that you could help with, so if you find something that you are interested in working on, please let us know!
