### ISSUE TITLE
Choice to concentrate on recently learned cards

### ISSUE THREAD

**Issue by jondo** [ankidroid/Anki-Android#3649]
My daughter is a quite regular user of Ankidroid - thank you for this great software!
However, during the summer holidays she nevertheless has built up quite a backlog of old cards to repeat.

During the school year, she should concentrate on learning and repeating the newly added cards, while not totally ignoring the older cards. How can I configure this?

My idea: In the "repetitions" section of the stack options, I'd like to see some way to shift the weight towards recently learned cards.

**Comment by jondo** [comment]
[On the mailing list](https://groups.google.com/forum/#!topic/anki-android/LhWQju5Kpd0), Nicolas Raoul proposed to work around my problem via a separate deck per school year or suspending 80 % of the older cards.

Separate decks are useless because this would make it too easy to totally ignore the old deck.
Is there a way to randomly suspend 80 % of 1200 cards?

**Comment by flerda** [comment]
This is not actually a bug in AnkiDroid, but it seems it is more of a discussion about finding advice about how to make better use of Anki.

As such, http://anki.tenderapp.com might be a more appropriate forum for this, maybe within the "Effective learning" topic (http://anki.tenderapp.com/discussions/effective-learning).

**Comment by jondo** [comment]
@flerda, thank you for this hint. I found [this relevant post](https://anki.tenderapp.com/discussions/effective-learning/688-manually-moving-cards-from-new-to-review#comment_37952146).

So, for the record, I think the solution is to use 'reschedule' to place last schoolyear's cards in the review queue with e.g. an interval between 0 and 365 days. By this, they will gradually pop up within the next year.
