### ISSUE TITLE
strings don't match when referenced

### ISSUE THREAD

**Issue by peervalhoegen** [ankidroid/Anki-Android#3650]
reproduce:
1. make a buried card situation & finish deck for the day
2. note the Text "Some related or buried cards were delayed until tomorrow. To see them now, touch the *"unbury"* button.
3. change language to swedish

The text now references a "visa dolda kort" button, but the referenced button says "Sluta dölja".

I suggest changing the string to "... touch the "{X}" button" and do a `getString(R.id.description).replaceFirst("{X}",getstring(R.id.Button_name))`
This solves the problem in all languages and for the future but requires an all language update.

**Comment by timrae** [comment]
In this case I think it's easier to just change the Swedish string, and it's feasible that a direct substitution of the button name will not make grammatical sense in every language.

Could you please take care of that? We use Crowdin for translations, that particular string can be found [here](https://crowdin.com/translate/ankidroid/7291/en-sv#q=unbury).

**Comment by peervalhoegen** [comment]
done. If anyone sees this, please upvote the new version with "Sluta dölja"

**Comment by ospalh** [comment]
Apparently, as i (have told crowdin that i ) don’t speak Swedish, i am not allowed to vote for translations, but as a reviewer i am allowed to delete them (?), which is what i did with the inconsistent “visa dolda kort” text.
This should be fixed after the next pull of the translations.
