### ISSUE TITLE
Long titles of decks cover the "remaining card count"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3656]
version: 2.5alpha57

![anki deck title](https://cloud.githubusercontent.com/assets/10436072/9873658/39ab0b82-5bdc-11e5-8d33-e43648b79ce2.png)

**Comment by timrae** [comment]
what version of Android?

**Comment by snowtimeglass** [comment]
The version is 4.3.

**Comment by snowtimeglass** [comment]
There wasn't the problem on alpha56.
