### ISSUE TITLE
Make undo on  'Congratulations! ...' screen show the reviewer again

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#3658]
When a study session is done, the 'Congratulations! You have finished for now.' screen is shown. In this screen, the 'undo' button to undo the last operation is shown (but why would it be there?) and clicking it changes the state of the deck (I guess it really undoes the operations) - this can be seen as the screen changes to the one with the 'Due today' information, and clicking the button more times changes the state each time (the numbers change). Seems like a bug.

**Comment by ospalh** [comment]
When you have reviewed cards until the number of cards due for the day is 0, you are shown the congratulations screen.
When you touch the undo button on that screen, the last review is undone. That means 1 card is due, and it is too early to show the congratulations screen. When you touch undo more than once, more and more cards are to be reviewed for the day.
Seems perfectly fine form me.
I guess touching undo could move you back to the reviewer. Is that what you mean by “Seems like a bug.”?

**Comment by wujek-srujek** [comment]
I thought the answer will be like this - it is a feature, and I'm fine with this.
My opinion is just that this feature has very little to offer and is confusing, which made me think 'whoa?' the first time I discovered it. I can press the button multiple times, but I don't even see which point in the study session I move to, which pretty much requires me to blindly try (and then go back to the reviewer at some point and go further from there), not use it at all, or press the button once, then press the study button and get to the reviewer, and then use the back button. Which resolves to this - sooner or later it is necessary to see the tasks by going back to the reviewer (unless, of course, one's memory is so trained that he can see the whole deck in his mind ;d).
So, as you say, I guess I would expect the 'undo' button in the 'congrats' screen move me to the reviewer again, and from then on, the usual 'undo' behavior is perfect.

**Comment by timrae** [comment]
> as you say, I guess I would expect the 'undo' button in the 'congrats' screen move me to the reviewer again, and from then on, the usual 'undo' behavior is perfect.

sounds reasonable

**Comment by ospalh** [comment]
With the newest 2.5alphas you get something like this. But at the moment with two caveats:

1. Only on tablets, or for a few seconds (while the snackbar is shown) on phones.
2. On tablets, when you select another deck and then touch “Undo”, the review gets undone, and you are shown a card *from the selected deck*. Not  really the Right Thing.
