### ISSUE TITLE
Protrusion of titles of decks

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3664]
It seems that the last selected deck protrudes.

![image](https://cloud.githubusercontent.com/assets/10436072/10009256/ec2b901e-6114-11e5-9670-dc6334923957.png)
Tap "deck 1" and back to this screen again.
(Nothing has been changed.)
![image](https://cloud.githubusercontent.com/assets/10436072/10009256/ec2b901e-6114-11e5-9670-dc6334923957.png)
Tap "deck 2" and back to this screen again.

![image](https://cloud.githubusercontent.com/assets/10436072/10009272/2007f742-6115-11e5-85d8-e00c6041ceb4.png)

Tap "deck 3" and back to this screen again.
![image](https://cloud.githubusercontent.com/assets/10436072/10009296/8045551e-6115-11e5-890f-4b69c86f6f34.png)

Tap "deck 1" and back to this screen again.
![image](https://cloud.githubusercontent.com/assets/10436072/10009318/ba195a92-6115-11e5-8ffc-d91f5df5e124.png)

**Comment by timrae** [comment]
Has anyone been able to reproduce this? I can't reproduce it.
What version of Android are you using? Any special ROM or anything?

**Comment by snowtimeglass** [comment]
Thank you for the reply.
Oh, can't it be reproduced?

>What version of Android are you using?

Android version is 4.3.
AnkiDroid version is 2.5alpha58 and alpha59.

>Any special ROM or anything?

Probably, not.
(Sorry, to tell the truth, 
I can't even understand the technical meaning of the question.)
This problem has been found on my smart phone (Galaxy Note II), 
which hasn't been remodeled specially.

By the way,
I made these decks in "/sdcard/AnkiDroid**/test**".

Before making them,
I found that the titles on my usual deck-list don't align.
The indents of the titles change bustlingly according to which title I tap.
However, I haven't understood the pattern yet.

(These decks are in  decks in "/sdcard/AnkiDroid".)
![image](https://cloud.githubusercontent.com/assets/10436072/10116860/a01ab134-647d-11e5-9a24-32d0294059a9.png)

**Comment by timrae** [comment]
First of all can you please try uninstall > reboot > reinstall?

**Comment by snowtimeglass** [comment]
Certainly. I'll try it.

**Comment by snowtimeglass** [comment]
Though I have tried the process,
Both these problems are reproduced.

**Comment by timrae** [comment]
Does this happen only on your Android 4.3 device?

**Comment by snowtimeglass** [comment]
No, it happen on my Android 4.1.2 device (tablet), too.

On the other hand, 
it doesn't happen on my Android 4.4.2 device (tablet).

[Each AnkiDroid version is 2.5alpha66]

**Comment by timrae** [comment]
> it doesn't happen on my Android 4.4.2 device (tablet)

Thanks I've reproduced it

**Comment by snowtimeglass** [comment]
Thank you.
Now, the decks look well-ordered. It delights me.
