### ISSUE TITLE
learn only cards that are result from search query

### ISSUE THREAD

**Issue by SprickW** [ankidroid/Anki-Android#3665]
my decks often contain 100+ cards, sometimes it makes sense to concentrate on cards related to some common theme

**Comment by flerda** [comment]
What you want to do is already possible using filtered decks.
https://ankidroid.org/docs/manual.html#filtered
http://ankisrs.net/docs/manual.html#filtered-decks-&-cramming

**Comment by SprickW** [comment]
Hi Flavio,

as I understand the description and how I tried it seems that filtering is based on tags only. I would like to filter by a search based on content of the cards.

Wolfgang

+++++++++++++++++++++++++++++++++

What you want to do is already possible using filtered decks.
https://ankidroid.org/docs/manual.html#filtered
http://ankisrs.net/docs/manual.html#filtered-decks-&-cramming

**Comment by flerda** [comment]
Filtered decks can be created using tags, that is true, but that's not the only option and it is possible to use arbitrary searches.

From http://ankisrs.net/docs/manual.html#creating-manually:
> Advanced users can create filtered decks with arbitrary search strings, instead of relying on set presets.

and later on in the same section:

> All of the searches possible in the browser are also possible for filtered decks, such as limiting to tags, finding cards forgotten a certain number of times, and so on.
