### ISSUE TITLE
disturbance in pronunciation

### ISSUE THREAD

**Issue by lahootian313** [ankidroid/Anki-Android#3670]
Hi
There are many sources that can present pronunciation of words in two accents British and American

But when I use anki to download word's pronunciation sometimes there is no result

So please add some other sources for downloading pronunciation of words
If we can choose those sources it will be better

thanks in advance

**Comment by ospalh** [comment]
There are already more than enough sources for English.
Are you sure that you 
a) spelled your words correctly and
b) used only single words?

Anyway, “some other sources” is more than vague.

**Comment by lahootian313** [comment]
Hi
I didn't understand what you mean


U can write word memento 


Does it have any result???????

**Comment by ospalh** [comment]
* I said you have to use correct spelling. Correct spelling includes writing the pronoun as “you’, and using exactly one punctuation mark at the end of sentences.
* I get audio for “memento” from Wiktionary, Leo, MW, Macmillan, OALD, Howjay and Google TTS. As i said, for English there are more than enough sources.
