### ISSUE TITLE
ogg audio format does not seem to be supported

### ISSUE THREAD

**Issue by EmilRehnberg** [ankidroid/Anki-Android#3673]
I am experiencing problems with playback of ogg files. 
It works on desktop-Anki but not on AnkiDroid.

Please let me know if I can provide an ogg file for debugging purposes.

**Comment by timrae** [comment]
AnkiDroid doesn't have anything to do with the actual playing of media; that's handled by your device itself, so all we can really do is point you here:

https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid
