### ISSUE TITLE
Decks that only contain subdecks are considered empty

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3675]
On 2.5alpha61. Steps to reproduce:

Have a deck (Parent) that contains no cards, but does contain subdecks (Child1, Child2, etc) that DO contain cards. 
Try to tap Parent. 
Receive error message at the bottom of the screen that the deck is empty. 

My workaround is to add a note to that parent deck to get AnkiDroid to recognize that it's not empty. Having done so, if I tap Parent, it displays the cards from Child1 and Child2 as I'd expect.

**Comment by timrae** [comment]
Ah thanks, I'll fix that soon
