### ISSUE TITLE
Some drop down menus are blank in Night Mode on 2.5alpha61

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3676]
![screenshot_2015-09-27-09-23-21](https://cloud.githubusercontent.com/assets/13272950/10123003/a620777c-64f9-11e5-9153-0e2e2ef99066.png)

**Comment by timrae** [comment]
yup I noticed this today, it will be fixed in the next alpha

**Comment by lizzgilmore** [comment]
Thanks! I just updated to 2.5alpha62 and the problem has actually gotten
worse: Now the options buttons (three vertical dots in upper right corner)
also open as a blank white rectangle.

**Comment by timrae** [comment]
by "also" you mean the deck selector is working now but the options menu is broken now, right?

**Comment by timrae** [comment]
oh sorry, I see, you're talking about the note editor

**Comment by lizzgilmore** [comment]
Ah, no, sorry, I mean when I'm studying a card and I want to tap the options menu to select, for instance, Reply Audio or Hide/Delete. 
![screenshot_2015-09-27-10-38-31](https://cloud.githubusercontent.com/assets/13272950/10123287/f1d7294a-6503-11e5-877e-ee73679d75cc.png)
