### ISSUE TITLE
"Decks" menu item is preselected and cannot be tapped on 2.5alpha62

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3680]
When I'm studying a deck and I tap the menu button, I can't tap Decks as it's already selected. Instead, I have to call up the navigation buttons (which I normally hide) and tap the back arrow to get back to the Deck list. 

![screenshot_2015-09-27-10-28-26](https://cloud.githubusercontent.com/assets/13272950/10123243/d548253c-6502-11e5-938c-d1b4594e976b.png)

**Comment by timrae** [comment]
you can just tap outside the drawer, I guess we could automatically close the drawer when an item which is already selected is tapped though

**Comment by lizzgilmore** [comment]
Sorry, I wasn't clear about what I was trying to do. 

While *already studying a card*, I want to open the menu drawer and tap Decks to be taken back to the main screen that lists all the decks. That's how I change from one deck to another. 

Instead, I tap Decks and nothing happens. 

Therefore, to get back to the main screen with the deck lists, I pull up the navigation buttons that I normally have hidden and tap the back arrow.

Does that give you a better idea of what I'm trying to accomplish when I tap Decks?

**Comment by timrae** [comment]
Thanks for the fast feedback!
