### ISSUE TITLE
Even in Full Screen Mode, the space where the status bar would be is still visible

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3681]
![screenshot_2015-09-27-10-49-00](https://cloud.githubusercontent.com/assets/13272950/10123341/809e4ee6-6505-11e5-9f88-82753d96a8c3.png)
![screenshot_2015-09-27-10-48-55](https://cloud.githubusercontent.com/assets/13272950/10123355/c68fe81a-6505-11e5-8070-6e0edd6ff185.png)

In the second screenshot, you can see that the window height is no greater than the window height in the first. Instead, there's a blank black bar above the deck title that simply takes up space. 

Full screen mode is supposed to hide the status bar and reclaim that space for the study window, right? That was the behavior I was used to seeing until I updated to the latest alpha (though I sadly couldn't tell you the version number under which this was most recently working).

**Comment by timrae** [comment]
could you please go back and find which version breaks it? it could possibly be from when we updated the appcompat update

**Comment by lizzgilmore** [comment]
I'm trying, but without success. When I download alpha60 and try to install
it, it lets me select install but then says App not installed. Do I have to
uninstall my existing AnkiDroid version to downgrade? If so, will
uninstalling wipe away my data (i.e. will I have to export my decks
beforehand and reimport after?)? The reason I'm concerned is that exporting
media hasn't worked in a while and I can't afford to lose everything.

**Comment by timrae** [comment]
> Do I have to uninstall my existing AnkiDroid version to downgrade

yes

> will uninstalling wipe away my data

no

**Comment by lizzgilmore** [comment]
Great, thank you!

Works fine in 2.5alpha60 and alpha61, broken for the first time in alpha62, still broken in alpha63. 

FYI: Uninstalling did not delete my decks or notes, but did reset all the Settings. Not complaining at all - you've been super helpful - just letting you know about it.

**Comment by WiliTest** [comment]
@timrae 
> > Do I have to uninstall my existing AnkiDroid version to downgrade?
> 
> yes
> 
> > will uninstalling wipe away my data?
> 
> no

** will uninstalling wipe away my settings?**

**Comment by mikehardy** [comment]
Tim's not going to answer I don't think
Settings that are not in the collection will be lost if you uninstall, as preferences are "app data" and thus are deleted with the app
There is discussion in some other places about using the deck config to store some AnkiDroid-specific settings, or to store settings for javascript add-ons, but no one is working on it at the moment
