### ISSUE TITLE
Image doesn't span the full width of the screen, even with image zoom set to a high value

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3685]
In the screenshot below, there's some wasted space to the right of both images. This is despite my having changed the image zoom setting to a high value. 

If the images were to be stretched to occupy the full width of the screen, images that contain text would be more readable, and I wouldn't need to rely on pinch to zoom. 

I know CSS is outside the scope of this project, but I'll ask in case anyone has advice: Is there a CSS value I should add to the note to force the image to scale to the full width of the screen? I don't want it to just be stretched disproportionately - I want it to scale the height and width properly. 

![screenshot_2015-09-27-12-14-05](https://cloud.githubusercontent.com/assets/13272950/10123828/98f11454-6511-11e5-9395-666ad9ac91b7.png)

**Comment by ospalh** [comment]
I think this is more a usage case than a bug in AnkiDroid, and have responded in the [Google group](https://groups.google.com/d/topic/anki-android/TjakbVGJLmk/discussion)
