### ISSUE TITLE
Can't rebuild filtered deck if the deck is empty - Receive "This deck is empty" notification

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3688]
On 2.5alpha64:

Steps to reproduce:
- Have a filtered deck with some cards in it.
- Open the filtered deck.
- Empty the filtered deck (either by hitting Empty or by completing all the cards, which sends them back to their home deck).
- Go back to the deck list.
- Try to tap on the filtered deck to open it (which is the only way you can access the Rebuild button that repopulates the deck with the cards)
- Get error bar at the bottom of the screen saying this deck is empty. This error message prevents you from opening the deck and getting to the Rebuild button.

Workaround:
- Manually create a new filtered deck using the same parameters... which is tedious to do, since it requires naming it, entering all the search terms, adjusting the card limits and other settings, etc.

**Comment by kazuoteramoto** [comment]
I can reproduce it.

Works with 2.5alpha59 and don't work with 2.5alpha60.

(For some reason I can upgrade but not downgrade on my Android device, I got 'App not installed' when trying to downgrade, this made searching for the broken version a PITA).

**Comment by timrae** [comment]
You have to uninstall to downgrade... I'm going to release a new version
soon though if you can be patient for a few hours

**Comment by timrae** [comment]
Fixed in latest alpha
