### ISSUE TITLE
"Unbury" is too pale, and doesn't work when tapped

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3692]
![image](https://cloud.githubusercontent.com/assets/10436072/10261324/28174e86-69cd-11e5-871b-ba9301a4fd32.png)

![image](https://cloud.githubusercontent.com/assets/10436072/10261326/3d4ffd0c-69cd-11e5-8649-7a5c16027675.png)

**Comment by timrae** [comment]
Thanks I'll fix it today

**Comment by snowtimeglass** [comment]
Thank you for your energetic works!

**Comment by timrae** [comment]
Actually it still wasn't completely fixed in alpha67, but it will be fixed in alpha68
