### ISSUE TITLE
v2.5alpha51 or above can't be opened on my tablets

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3693]
v2.5alpha50 can be opened on my three tablets.
However, on none of the tablets can v2.5alpha51 and v2.5alpha65 be opened.

(The message, 
"AnkiDroid has encountered a problem; a report is being generated…",
is displayed.)

Android version:
 4.1.2 and 4.4.2

**Comment by timrae** [comment]
In the case of a crash, please ALWAYS provide your "debug info"

**Comment by snowtimeglass** [comment]
I can't open AnkiDroid v2.5alpha51.
Am I supposed to uninstall it, install alpha50, get "debug info" in it , and paste it here?

**Comment by timrae** [comment]
Oh of course, sorry!

**Comment by snowtimeglass** [comment]
Certainly.
Just a moment.

**Comment by timrae** [comment]
No I mean you don't need to do anything

**Comment by timrae** [comment]
Thanks

**Comment by snowtimeglass** [comment]
Oh, I see. Thank you.
I sent some error reports in the last hour.
I hope they would be of some help.

**Comment by snowtimeglass** [comment]
Thank you.
v2.5alpha66 can be opened properly on my tablets.
