### ISSUE TITLE
Mini drawer interferes with whiteboard

### ISSUE THREAD

**Issue by ospalh** [ankidroid/Anki-Android#3702]
I find the mini-drawer #3690, distracting on the reviewer screen.
But it becomes a real problem when you want to use the whiteboard:
Try this:
* On a tablet
* With 2.5alpha67
* Review
* Switch on the whiteboard
* Try to write an F
![screenshot_2015-10-05-10-09-09](https://cloud.githubusercontent.com/assets/1690429/10275842/072af720-6b4b-11e5-89d2-3d976569dd34.png)

Instead of drawing the vertical stroke, a bit of the stroke is shown, and the drawer opens. That bit of the stroke is replaced by the start bit of the next stroke when you close the drawer, a game you can play again and again, open, close, open, close.

**Comment by timrae** [comment]
Ah yeah we should at least disable swipe to expand the minidrawer with whiteboard enabled
