### ISSUE TITLE
Position of "Unbury" 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3705]
Thank you for the fix about #3692

However, now, 
I think that it is more natural to put the menu item, "unbury", on the menu of currently selected deck (which opens when the title of the deck is long-tapped),
rather than on the menu which opens when the upper-right icon of the screen is tapped,
since the latter menu is for the function about the entire collection.

**Comment by timrae** [comment]
For some reason I was under the impression that unbury operated on all decks, but I just confirmed that you are right by looking at the source code. I agree the long-tap menu makes more sense

**Comment by snowtimeglass** [comment]
Thank you.
I felt relieved to hear that.

**Comment by timrae** [comment]
Fixed in alpha69
