### ISSUE TITLE
Study option area of tablet mode displays "backstage" for an instant

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3706]
When AnkiDroid is opened or when a deck title is tapped,
Study option area displays the following strings for an instant

![image](https://cloud.githubusercontent.com/assets/10436072/10281978/1c226efc-6bb3-11e5-8998-505547e7e207.png)

------------------------------------------------------
AnkiDroid Version = 2.5alpha67

Android Version = 4.1.2

ACRA UUID = bbb5f89b-6952-4da2-8281-a06dfe190c6c

**Comment by timrae** [comment]
haha thanks for noticing this. I added the strings while debugging the layout file
