### ISSUE TITLE
Option to hide action bar in fullscreen mode

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#3708]
There is a problem to coder when they review in the AnkiDroid like this:
![1t](https://cloud.githubusercontent.com/assets/10048069/10302010/beeeb988-6c3a-11e5-8278-4a7bf035c500.png)

You can see the red frame that I marked.The &lt;table&gt;&lt;/table&gt; is disorder complelely.So the only workaround I think is take the landscape-mode to review it like this:

![222](https://cloud.githubusercontent.com/assets/10048069/10302002/ae814336-6c3a-11e5-9b6c-05232edbffe9.png)

But the UE of landscape-mode is a little bad because of the narrow reading area.So my suggestion is add a option in setting to hidden the system notification bar,the top-bar and the button-bar(we can manipulate with custom gestures or return to portrait-mode) in landscape-mode.

**Comment by timrae** [comment]
@Juddd, thanks for the suggestion. 

Hiding the status bar can already be achieved by enabling fullscreen mode under reviewer preferences. AnkiDroid v2.5 (alpha69+) will also hide the action bar when fullscreen mode is enabled. 

We don't currently support hiding the answer buttons at this point, but we probably will at some point in the future. This will likely not be part of "fullscreen mode" though, instead I imagine you will able to set the preference for reviewer button size to 0.

**Comment by Juddd** [comment]
@timrae Thanks for your response.But what is my suggettion is just in the landscape-mode that I need your "fullscreen mode".Can we do this?And I am very much looking forward to your 0 of the button bar in bottom, or it just can be even smaller.

**Comment by timrae** [comment]
@Juddd 

There's not currently any way to only enable fullscreen mode when in landscape unfortunately. You are welcome to submit a pull request if you are motivated to develop this feature yourself!

**Comment by hssm** [comment]
Actually, in the latest alpha you can choose to hide the answer buttons if you have gestures enabled. It's under the gesture settings. The action bar is what remains visible. If we get enough user feedback wanting an option to remove the action bar as well we could always add it in later.

I don't know how useful a landscape-only full-screen mode is. I think if you are satisfied with operating AnkiDroid with gestures in one orientation you will also manage the other one just fine and use it in both cases. I don't think it warrants a new feature, personally.

**Comment by timrae** [comment]
> Actually, in the latest alpha you can choose to hide the answer buttons if you have gestures enabled

Ah, that's right, I thought we had that feature but had forgotten where it was

> If we get enough user feedback wanting an option to remove the action bar as well we could always add it in later.

I've already removed it (see #3709), it will be in the next alpha

> I don't think it warrants a new feature, personally.

neither do I, but I wouldn't try to block it if someone submitted a PR

**Comment by Juddd** [comment]
Oh,the reading area is enogh in the portrait-mode,isn't it?So I think it'll be ok just hidden the system notification bar,the action bar and the answer bar in landscape.And it is my personal thinking maybe.And I wanna to it but my poor ability of programing.@timrae

**Comment by timrae** [comment]
> the reading area is enogh in the portrait-mode

Some people have very large content, others have very small screens, and many just want to enable fullscreen for aesthetic purposes. The easiest way to cater for everyone's taste is to just have one setting that enables or disables fullscreen.

**Comment by timrae** [comment]
Sorry the code that I wrote to hide the action bar isn't working properly so I've removed it. You can still hide the answer button in v2.5

**Comment by Juddd** [comment]
@timrae I'm sorry to hear that.In addition, the expression of my yesterday seems to have some mistakes, my phone is currently the mode of automatic horizontal screen, I usually use a vertical screen, I mean that when I review the &lt;table&gt;&lt;/table&gt; like the pictrue I uploading,the portrait screen's reading area is not wide enough, then I use a landscape-screen, and then I hope to enable full screen mode in this landscape-screen.

**Comment by timrae** [comment]
I finally got it working

**Comment by Juddd** [comment]
@timrae Yeah.I have tried it some times.Thanks a lot for your working.
