### ISSUE TITLE
Feature request: postpone a card

### ISSUE THREAD

**Issue by peervalhoegen** [ankidroid/Anki-Android#3719]
scenario: you sit on a train with no head phones and a listening card¹ comes up. You can not move on with the deck unless you've answered this card which you can't.

Solution: an option to postpone a card to the end of the deck.

¹question is only audio

**Comment by timrae** [comment]
We already have that feature, it's called "bury card". When the card comes up, open the menu in the top right-hand corner, choose "Hide / delete" and then bury card.
