### ISSUE TITLE
Remove "Smart Typing" and "Predictive text" for {{type::NN}} field

### ISSUE THREAD

**Issue by madnik7** [ankidroid/Anki-Android#3727]
I use AnkiDroid for learning English, and use the "Type in the answer feature", but the "Smart Typing" feature of mobile keyboard is a real nuisance because it always displays the right spelling in front of my eyes, so I am wondering is it possible to disable the "Smart Typing" of mobile keyboard for {{type::NN}} field as I see on some other apps.

**Comment by hssm** [comment]
We have two approaches to the typing field and I've tested both to make sure they don't display predictions. If predictions still appear it's most likely the fault of the keyboard not obeying the hints from the OS and we can't do anything about that.
