### ISSUE TITLE
Deck was too large to sync, made it smaller, but now will not sync no matter what I do

### ISSUE THREAD

**Issue by maggiev123** [ankidroid/Anki-Android#3728]
I’ve been using Anki via the desktop version and my phone for many months (probably years) without any issues. However, I recently downloaded a shared deck that included a lot of mp3 music clips. On my laptop it was no problem, but when I synced to my phone, the sync failed because it ran out of room on my phone.

I am not very experienced at dealing with the Android OS (this is my first issue with storage). To try to solve the problem, I:
-	Completely removed the new deck from my Anki collection via my laptop. I’ve been in and out of my collection via the desktop version numerous times since then, including activities like changing a card type which resulted in a full sync with Ankiweb.
-	I then tried to sync again on my phone but it still gave me error msgs related to storage
-	I uninstalled Anki from my phone and reinstalled – still errors
-	I uninstalled Anki again, and also deleted a folder that I found under  System Settings --> Storage --> Misc --> AnkiDroid  (333 MB) – still errors

I tried again just now to uninstall, delete folder, reinstall and again I got an error msg. I'm sorry I don't have better info on the error msgs, but they seem to vary, and just now when I tried it again, it gave me no info except that it is going to send a report to the developers (which it often says), no other info about what the error itself was, though in the past they usually mention storage.  I never got them before this mess with the huge shared deck I downloaded, and since I deleted the shared deck, I’d think the size of my collection would be back to the size it was before when I didn’t get errors.

By the way, after the error msg, Anki sometimes appears open and acts like I can review, but within a few cards it gives me an error and will not let me review anymore or sync what I’ve done so far. Other times Anki won't open, or immediately gives me an error (no info) and may or may not open.

Any ideas?

**Comment by hssm** [comment]
Have you tried restarting the device itself? There may be unreleased resources that are in conflict.

Besides that, make sure there actually is enough space on the device and that you aren't still trying to sync those large media files. You said you deleted the large deck already, but to be completely sure the media is also gone, on the desktop client, go to `Tools -> Check media...`, and sync again after it's done.

**Comment by maggiev123** [comment]
Ah HA! Deleting the unused media was exactly what I needed to do! Didn't know about that step before, but it worked like a charm. Thank you SO MUCH!!!
(My 9yr old son thanks you, too, since he likes to climb up in his favorite tree to do his Anki reviews, and he was sad I wouldn't let him drag our whole laptop up there with him, LOL)
