### ISSUE TITLE
Another set of colors for dark mode

### ISSUE THREAD

**Issue by mzasuwik** [ankidroid/Anki-Android#3729]
Hey

Lately I find out that current dark mode is too intensive and all along my eyes are painful.

I also browse one website which has the finest dark mode I have ever seen. Its colors have more toned-down tinge. Could you replace this set of colors or let users choose it on their own?

Sample of colors:
http://i.imgur.com/cPHODU5.png

**Comment by hssm** [comment]
Additional themes is a possibility in the long-term but there are currently no plans for it.

**Comment by jshevek** [comment]
>  or let users choose it on their own?

You are definitely not alone in wanting this.

**Comment by timrae** [comment]
see #3757
