### ISSUE TITLE
Can't open "Settings"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3739]
Whenever "Settings" is tapped,
The message, "AnkiDroid has encountered a problem; a report is being generated…", 
is displayed, and AnkiDroid crashes.

----------------------------
AnkiDroid Version = 2.5alpha73

Android Version = 4.3

ACRA UUID = ? (I can't open "Settings")

**Comment by timrae** [comment]
While looking for your report I found out that our crash reporting system has been broken since alpha 68! Could you please try to reproduce the issue in alpha75? It should be available in a few minutes

**Comment by snowtimeglass** [comment]
I've installed alpha75 and reproduced the issue in it, 
and sent an error report.

(By the way, in cases like this,
is it meaningful to write "ACRA UUID" in "Debug info" on an older version of AnkiDroid?)

**Comment by timrae** [comment]
Thanks, it looks like this is a bug in the new version of the Android support library:
https://code.google.com/p/android/issues/detail?id=190459

I had a go at fixing it properly it but it's a lot of work so I think I'll just drop down the version of the library.

**Comment by snowtimeglass** [comment]
Thank you.
I can open "Settings" on alpha76.

In cases like this,
I'll be ready to write "ACRA UUID" in "Debug info" on an older version of AnkiDroid,
if it is useful for you.

Is the "ACRA UUID" unchangeable strings of a device?

**Comment by timrae** [comment]
Thanks, it's probably not necessary as the UUID is reset everytime the app is uninstalled

**Comment by snowtimeglass** [comment]
I see. Thank you.
