### ISSUE TITLE
In Japanese language mode, the button of "RATE ANKIDROID" is unnatural

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3741]
Though the transcription, "RATE ANKIDROID", is acceptable,
"ANKIDROIDを評価"  is less acceptable.

Is it possible to replace it with "AnkiDroidを評価"?

![image](https://cloud.githubusercontent.com/assets/10436072/10556876/8bd1255e-74cd-11e5-9318-ae5360b058d4.png)

**Comment by ospalh** [comment]
I guess your complaint is about the SHOUTING? The use of capital letters? That is the standard style now. Goggle, in their infinite wisdom, have decreed that [“(b)utton text should be capitalized”](http://www.google.com/design/spec/components/buttons.html#buttons-flat-raised-buttons). It is looking just as annoying to me in German as well. (So annoying in fact that i patched my version to get rid of this in a few spots: 76105a1ab5bf7  0febd6146d)

If you think that 「RATE ANKIDROID」 really is a better translation than 「ANKIDROIDを評価」, you can delete your old one at Crowdin and add the new one. If others disagree, they can re-add「AnkiDroidを評価」, which will be automatically converted to  「ANKIDROIDを評価」 again. That would then be the point to discuss this in more detail.

**Comment by snowtimeglass** [comment]
>I guess your complaint is about the SHOUTING? The use of capital letters?

It is about the use of capital letters. 
(though it is not about "SHOUTING"). 

When all letters are written with alphabet,
users can regard the transcription with capital letters as a style, design
(though they may feel as if it shouted).

However, "ANKIDROIDを評価" can't be regarded so.
They will regard it a mere typographical error.

It seems to be nonsense to apply the rule of capital letters to Japanese version.

Is it unavoidable that "AnkiDroidを評価" at Crowdin will be automatically converted to "ANKIDROIDを評価"?

**Comment by snowtimeglass** [comment]
For the time being,
I add "このアプリを評価" ("RATE THIS APP") at Crowdin.
