### ISSUE TITLE
Languages setting not used (CM 5.1.1)

### ISSUE THREAD

**Issue by ospalh** [ankidroid/Anki-Android#3751]
How to reproduce

* Use CyanogenMod 5.1.1
* Use for example German as system language
* Set the language to English in the AnkiDroid settings
* See the App stay in German

AnkiDroid Version = 2.5beta2

Android Version = 5.1.1

ACRA UUID = fa28bbf1-3e5e-4093-85da-8409da7acd68

The “5.1.1” is CyanogenMod. Language switching seems to work OK on an emulator with vanilla  Android 4.4.

**Comment by timrae** [comment]
what makes you think it's an AnkiDroid issue?

**Comment by ospalh** [comment]
… that i don’t have that many other apps where i can change the language

**Comment by ospalh** [comment]
That’s odd. 
I changed the tablet system language once and now changing the language inside of AnkiDroid works.
