### ISSUE TITLE
Fullscreen is not *really* fullscreen in the menu

### ISSUE THREAD

**Issue by bogdanteleaga** [ankidroid/Anki-Android#3753]
So I'm using a custom rom that has the expanded desktop option(which exists as an app as well right now). Basically it hides the status bar at all times unless you swipe from the top.

The problem is that in the main menu I get a white empty panel where the status bar is supposed to be. Settings looks fine and when doing the actual reviews it looks fine, it's just the main menu that has this problem. I'm running 2.5-beta2.

**Comment by timrae** [comment]
By "main menu" I guess you mean the navigation drawer that you swipe open from the left? It sounds like a problem with your custom ROM tbh and we can't help you with that. The next beta version should have enhanced fullscreen reviewing capabilities though, and that might fix your issue.

**Comment by bogdanteleaga** [comment]
I meant the main activity. It looks to me like everything besides reviews themselves are not fullscreen even though fullscreen is chosen as an option, so I guess this is a decision on your part. 

However, with an app such as https://play.google.com/store/apps/details?id=com.gmd.immersive, one should be able to make anything fullscreen. I think this is mostly what my custom rom has been doing(I have since changed to something else), and this can probably be achieved through xposed as well.

The main thing here is that it does not go fullscreen even with something like this. Now I have some other apps that exhibit behavior like this (type mail for example), but most of them seem to work.

Hope that makes sense, if not I can try to explain better.

**Comment by timrae** [comment]
Yeah fullscreen is only a reviewing option. Post some screenshots once you try beta17 (it should be out in the next few days)
