### ISSUE TITLE
Caps lock on by default while asking input

### ISSUE THREAD

**Issue by sollunaastro** [ankidroid/Anki-Android#3754]
Before I opted for the beta when a card asked for input the keyboard automatically was on lowercase 

Now it starts with mayus on, troublesome with the recognition.

**Comment by ospalh** [comment]
Hmm. I actually can reproduce this.
But then again:
* This is the standard behavior for input boxes inside a document. I get the keyboards set to type one majuscule and switch to minuscules afterwards for input boxes like this in Chrome and Browser. Changing this will be tricky.
* I am not sure that the new behavior is wrong. While my geography deck is in German, even with an English version you’d be *expected* to type “Egypt” rather than “egypt” in the example in #3730.

**Comment by ospalh** [comment]
Is it really caps *lock*? For me it is caps for the first letter, and lower case from then on.

**Comment by timrae** [comment]
yeah not really caps lock, but it's a bit more intelligible than the spanish word "mayus"

**Comment by sollunaastro** [comment]
Yeah, sorry about the misuse of caps lock, I meant shift/mayus
I understand it's the standard behavior, I just found the change strange and didn't know if it was intended. When practicing language particles and/or ideograms the lowercase fitted my needs, but I guess proper names get the benefit now.
Thanks for addressing this.

**Comment by ospalh** [comment]
It wasn’t so much intended as just the way some software keyboards apparently work.
Anyway, at least for the original Android keyboard, there is a setting to switch off automatic capitalization. 
For me it worked like this, translated from German to English:
* From the home screen
* Android settings
* Languages & Input (Sprache & Eingabe)
* Android keyboard (Android Tastatur)
* Settings (Einstellungen)
* Un-check “Automatic capitalization” (Autom. Groß-/Kleinschreibung)

Other keyboards may have similar settings.

**Comment by hssm** [comment]
Just like we did with `autocomplete="off"`, there is also a parameter for turning off auto-capitlization. Try [this test](http://jsfiddle.net/n17pqro2/) in your Chrome browser on an Android device. The second input box shouldn't allow capitalization (provided your keyboard takes the hint, of course).

I'm not suggesting adding this to AnkiDroid, but a motivated user can use JavaScript to add this tag to the typing element in their template.

**Comment by ospalh** [comment]
I don’t really know what the Right Thing to do is in this case. I am not *against* setting `autocapitalize="off"`,  just unsure what would be better.

**Comment by hssm** [comment]
Yeah I don't know either. I don't use this feature so I can't speak from experience. I would *guess* that most users would be targeting a single-word field where capitalization would be preferred, but then there are sentence clozes where the word is in the middle of the sentence...

I don't think there is a need to keep this issue open. It's not really a bug but maybe something we can adjust in the future.
