### ISSUE TITLE
No color red when reviewing

### ISSUE THREAD

**Issue by kwokhin** [ankidroid/Anki-Android#3756]
I think the picture below pretty much sum up what happened after upgrading to 2.5. I don't know which one to answer because no red specific label is specified. It doesn't occur when cards are made with default red. But when cards are made in different color, this problem occurs. Thanks!
This problem occurs no matter in beta version 2.5 or the normal 2.5
![screenshot_2015-10-23-18-24-13](https://cloud.githubusercontent.com/assets/11689867/10690319/79cd16fc-79b3-11e5-82fd-59dc8900b22d.jpg)

**Comment by ospalh** [comment]
1. What should have been red and isn’t?
1. The image upload didn’t work. Maybe you have JavaScript off/blocked?

**Comment by kwokhin** [comment]
I'm sorry I was posting this on my phone and all is fine now. Thank you:)

**Comment by timrae** [comment]
@kwokhin 
I just wanted to check that you meant all is fine now in the sense that you solved the problem by yourself, right?

**Comment by kwokhin** [comment]
@timrae No, sorry for my bad English. I meant that I successfully uploaded the picture from my phone

**Comment by kwokhin** [comment]
I downgraded to version 2.4.4, 2.4.3 and 2.4.2 but it didn't work( I uninstall the app, deleted the folder Ankidroid then restarted the phone). There aren't any red label to indicate which card is being asked for answer. It used to be like the picture below. Any help is appreciated!
![pc anki](https://cloud.githubusercontent.com/assets/11689867/10692603/43e7d038-79c5-11e5-8976-88e96bd076d3.png)

**Comment by timrae** [comment]
Yes that's what I suspected. You're using the image occlusion plugin right?
There are some threads on the forum if you search about it.

**Comment by kwokhin** [comment]
@timrae thank you so much for the insight! My bad. I should have searched for similar thread for similar problem before posting. It was android lollipop's problem. I downgraded the android system webview and the problem is immediately solved! Thank you so much!:) I really appreciate your help!
