### ISSUE TITLE
Add ability to customize colors

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#3757]
(Sorry if the process for remarks to the new material design is supposed to be different than using the issues.)

I have just downloaded the 2.5beta2 version to try out the night mode, something I've been longing for for a while. In general, I really, really like the new material design and especially the night mode applying to the whole application - I see myself using it a lot. I also like the fact that it is so easy to switch between day and night modes. In general - thumbs up!

Now my remarks - the buttons' colors seem to be too vivid. For example, the 'plus' floating action button in the decks screen is blue, but the blue is too bright (for me). I would like the blue to be like the 'new' cards number or 'virtual' decks blue - more pastel. Similarly, I find the answer buttons too bright, especially the red 'again' button. The red and green used for the counters in top-left corner are softer and better fit the overall dark theme.

In the day mode, I think the status bar's blue is too bright as well, seems too distracting. I know I can use the night mode all the time, but I kind of prefer the day mode during the day, due to less contrast. In the same vein, I think the answer buttons are too distracting as well. I think the 'old' design had them white and only the texts were colored; the new design has the buttons colored, and somehow it doesn't fit it well.

**Comment by Erraclau** [comment]
While I can see that the blue accent seems to be based on that used in the star of the logo, its brightness is a bit distracting when reviewing cards. Perhaps making the accent colour of the action bar and '+' button the same colour as the show answer button (#608392) would be a more neutral colour choice?

**Comment by timrae** [comment]
> I would like the blue to be like the 'new' cards number or 'virtual' decks blue - more pastel. Similarly, I find the answer buttons too bright, especially the red 'again' button. The red and green used for the counters in top-left corner are softer and better fit the overall dark theme.

I tried this out once in [the material design thread](https://groups.google.com/d/topic/anki-android/bZ6PP5Fc2kY/discussion) (page 7) and it [looked pretty stupid](https://lh3.googleusercontent.com/-lmv6pM-w2tg/VZZvfbAUEwI/AAAAAAAAATI/Nv2_6n_Pg-o/s1600/untitled.png).

Unless there is a huge backlash against the current color scheme, we probably won't be changing them as the defaults. In saying that, adding alternative "themes", or the ability to customize the answer button colors via css is definitely something that we'd consider merging if somebody were to submit a pull request.

**Comment by timrae** [comment]
Of course in the meantime you are welcome / encouraged to fork AnkiDroid and use your own custom color scheme. There are quite a few users that already do this, and there are some tips in the wiki to get you started with compiling the source code:

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide

**Comment by timrae** [comment]
v2.6 has the ability to customize which day mode / night mode theme is used, so I'm going to close this issue. The current theme architecture is pretty flexible so it should be relatively easy for any aspiring designers to submit additional themes if the current ones are not to their taste.
