### ISSUE TITLE
Card browser font scaling does not work with imported stylesheet files

### ISSUE THREAD

**Issue by Erraclau** [ankidroid/Anki-Android#3760]
I use a shared css stylesheet for a number of decks so that they can easily be made consistent. As such, the css of my decks just lists the following:

> `@import url("_StyleSheet.css");`

This stylesheet specifies font-sizes etc.

However, when the "Card browser font scaling" option is changed from 100% to another value, this has no effect on font sizes specified in the imported stylesheet (i.e., AnkiDroid continues to use the font-sizes specified in the imported stylesheet without applying any font scaling). Changing the "Card browser font scaling" value only seems to work when the css that specifies font-sizes is included in the styling section of the card itself.

**Comment by hssm** [comment]
"Card browser font scaling" only has an effect in the card browser. Perhaps you meant the reviewer font scaling?

In any case, I am quite certain this behaviour will work as you expect in the most recent builds. Please try grabbing the latest beta, either from here on github or the [Play Store](https://play.google.com/apps/testing/com.ichi2.anki) page, and see how that goes. The setting is renamed to "Card zoom" and moved to the Reviewing section.

**Comment by Erraclau** [comment]
Yes, sorry, I meant the reviewer font scaling, or card zoom in the 2.5 beta. It looks like the problem is fixed in 2.5, because card zoom has the expected function, whereas the reviewer font scaling in 2.4 did not.
