### ISSUE TITLE
A translation on GitHub hasn't been reflected in App

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3761]
The message, "Are you sure you want to cancel?", hasn't been translated in AnkiDroid
though I translated it on GitHub a month ago.

![image](https://cloud.githubusercontent.com/assets/10436072/10714145/ce826606-7b21-11e5-9009-de2c5f44ea0a.png)

**Comment by eginhard** [comment]
As long as it is translated on Crowdin, it will eventually appear in AnkiDroid, however, translations are usually pulled before releases (when there are a number of new translations), so it can sometimes take a while until they're visible in the app.

**Comment by snowtimeglass** [comment]
Hi eginhard,

Thank you for the response.
Generally speaking, what you say is, of course, true.
However, I suspect that this case is an exception. 

[The translation](https://crowdin.com/translate/ankidroid/all/en-ja#q=%E3%82%AD%E3%83%A3%E3%83%B3%E3%82%BB%E3%83%AB%E3%81%97%E3%81%BE%E3%81%99%E3%81%8B) was made on Sep 11.

From Sep 11 to Oct 20, there were [11 update of strings from Crowdin](https://github.com/ankidroid/Anki-Android/compare/v2.5alpha57...develop)("Updated strings from Crowdin") and 20 releases.

Moreover, other translations which was made on the same day (Sep 11) or after the day have already reflected on the app normally .

(I should have specified these situations.)

I suspect that the association between the translation on Crowdin and the app was broken for some reason.

**Comment by eginhard** [comment]
Thanks snowtimeglass. I should have looked at the specific string as well, turns out it just wasn't used in the app at all. This PR resolves that and some other ambiguity with this dialog.

**Comment by snowtimeglass** [comment]
eginhard, thank you for the fix.
I'd like to also thank you for the fix about the ambiguity.
I've felt the ambiguity as well.
