### ISSUE TITLE
"Daily study limit reached / Study more" snackbar after "No cards are due yet." seems odd

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3762]
After a deck which displayed " No cards are due yet. " snackbar once is tapped,
" Daily study limit reached / Study more " snackbar is displayed.

I feel it is odd.

Isn't it more appropriate to display " No cards are due yet. / Study more " snackbar first and repeatedly
as the older versions instructed users?

an older version (2.5alpha40)
![image](https://cloud.githubusercontent.com/assets/10436072/10714196/c7330744-7b25-11e5-83aa-a97b390343e1.png)

**Comment by timrae** [comment]
After reviewing the code I believe the "No cards are due yet." message is unnecessary now, since (unlike the old StudyOptions screen), the deck picker shows (0, 0, 0) counts due.

**Comment by snowtimeglass** [comment]
>I believe the "No cards are due yet." message is unnecessary now, since (unlike the old StudyOptions screen), the deck picker shows (0, 0, 0) counts due.

I think the "No cards are due yet." message is necessary, since it tells users not only that there are no cards to study for the moment, but also that there still are learn cards which are scheduled to be studied in the day. On Anki Desktop and the older versions of AnkiDroid, the message works so.
 
Now, on AnkiDroid 2.5beta11, the message of 'Congratulations!' is displayed even if there still are the learn cards which are scheduled to be studied in the day.
It has lost consistency with Anki Desktop.

I hope the "No cards are due yet." message will be restored.

**Comment by timrae** [comment]
I'm not going to change the message, but I could make it so that if the learn ahead limit is zero then we use the same behavior as v2.4.4 (i.e. don't bypass the deck overview screen, similar to what we do for filtered deck on v2.5). Would that be OK?

**Comment by snowtimeglass** [comment]
Would that keep the inconsistency in the pattern of appearance of the 'Congratulations!' message with Anki Desktop? In other word, when you finish studying for the moment (0 0 0), but there still are learn cards which are scheduled to be studied in the day, would the 'Congratulations!' message be displayed?

**Comment by timrae** [comment]
As I said, it would be the same as v2.4

**Comment by snowtimeglass** [comment]
Deck overview screen and the message of 'No card are due yet' would be displayed as follows, right?

v2.4.4
![image](https://cloud.githubusercontent.com/assets/10436072/11018436/6a2d6124-860c-11e5-9b38-a922bd180b81.png)

**Comment by snowtimeglass** [comment]
> if the learn ahead limit is zero then we use the same behavior as v2.4.4

If the learn ahead limit is, say, 10, and there still learn cards to be scheduled in 30 minutes, what would happen?

**Comment by timrae** [comment]
It should be fixed in the next beta version, it will take you to the old "study options" screen when there are cards in the queue but not ready to study.

**Comment by snowtimeglass** [comment]
Thank you for the fix.
Though I'm afraid that the "study options" screen might be a bit redundant now,
I'm looking forward to the next beta version, anyway.
