### ISSUE TITLE
'Answer button size' often too small initially

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#3766]
I'm using the 2.5beta2 version on a Nexus 6 with Marshmallow. I set the Settings->Reviewing->Answer button size to 170% (the maximum) and generally it works. Sometimes, though, when I initially go to the reviewer, the button which says 'Show answer' is small (probably the default size), and either gets bigger without user interaction (but it is noticeable) or the answer buttons that replace it on click are bigger, and from that point on all is well.

**Comment by hssm** [comment]
https://github.com/ankidroid/Anki-Android/issues/3621
