### ISSUE TITLE
Anki not handling DST?

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#3770]
I live in Germany, and we have just had a DST time change the night before - at 3:00 25.10.2015 the clock was reset to 2:00 again.
I have my 'Start of next day' set to 0:00 and it normally works. Except for today... Currently, my time is 23:28 in the current time zone (GMT+01:00 Central European Standard Time), but with DST applied it would be 0:28 (GMT+02:00 Central European Summer Time). Apparently, Anki got confused about the hour and thinks it is after midnight.
I started using Anki while we had DST applied, so I guess all its timestamps are saved relative to that or something, and it doesn't store the TZ anywhere. Or whatever, I have no idea about the internals. I guess a similar issue would manifest itself if I created my collection now, and waited until the first night after DST applies again - the 'next day' would start one hour after my setting.
Will it 'fix itself' on somehow, like when the times are saved again, this time with the new TZ?
The desktop version has the same issue, so I guess this is not an Anki Droid thing, but who knows. Are you aware of the issue? Should I just file an issue upstream?

**Comment by eginhard** [comment]
Yes, this is a known bug to conform with the current behaviour of Anki Desktop and fixing it unilaterally would cause sync issues.

It's probably best to change "start of next day" to a later time, so that a one-hour shift won't make a difference.

**Comment by lapo-luchini** [comment]
DST is easily worked around by using a later "night hour", but when traveling to a distant place, that night time easily moves into the next (or previous) day, due to timezone change. :(

**Comment by mikehardy** [comment]
The prior comment about not really being able to fix it is unfortunately still valid, so I suppose the official position of the AnkiDroid team is to not travel too far ;-). Even though the app might be useful to learn the language of faraway places, we just can't recommend it as it will mess up your studies. (yes I'm kidding, I understand it's frustrating, we just can't fix it)

**Comment by wujek-srujek** [comment]
I learned enough about Anki database that I can 'fix' days with missing reviews due to TZ changes so all is good now :)
