### ISSUE TITLE
Show a snackbar with option to check media when 0 byte files are detected

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#3782]
@hssm 
Would triggering a media check help to deal with this? There's one user that's getting this a lot

java.lang.RuntimeException: java.lang.RuntimeException: SyncError:Can't add 0 byte file.
at com.ichi2.libanki.sync.MediaSyncer.sync(MediaSyncer.java:227)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:393)

**Comment by hssm** [comment]
Yes a media check will remove any 0-byte files. I suppose we could detect this specific error and force a media check on the next sync. I would prefer to just let the user click the media check button though.

It doesn't really solve the problem of those files ending up there in the first place though. I have no idea what is up with that.

**Comment by timrae** [comment]
Currently do they see an error dialog? Maybe a snackbar with something like "Error syncing media" | (CHECK MEDIA) button could be useful

**Comment by hssm** [comment]
They should see the top line of the stack trace in the error dialog.

I like your idea. If I remember we are already checking for specific sync errors like timeouts, so adding an additional rule (or rules) for specific media errors is probably not too difficult.
