### ISSUE TITLE
URL encoding is buggy for # / %23, possibly others as well.

### ISSUE THREAD

**Issue by Tomalak** [ankidroid/Anki-Android#3785]
I currently have a card template with this link on it:

    <a href="http://jisho.org/search/{{Back}}%20%23kanji">{{Back}}</a>

Now, for example for 字 what it *should* do is go to http://jisho.org/search/%E5%AD%97%20%23kanji.

What it *actually* does is go to http://jisho.org/search/%E5%AD%97%20#kanji, thus breaking the link. Compare the search fields of both pages to see what I mean.

In other words, some part of the card HTML generation process seems to think it's all-right to translate `%23` to `#` unconditionally.

This kind of thing is actually never all-right. The URL must be preserved exactly as entered, no assumptions about what the user could have meant must be made. The type of error suggests that other characters might be affected as well.

**Comment by Tomalak** [comment]
Oh, this is the AnkiDroid repo. Never mind, I'll open this against Anki itself.

**Comment by timrae** [comment]
Does it work as expected in anki desktop?

**Comment by Tomalak** [comment]
I filed my post under "Anki Desktop", so no, it doesn't.

I'm wondering, shouldn't we discuss this in the thread instead of by mail?

**Comment by Tomalak** [comment]
@timrae Now I'm completely confused. %)

I closed this issue here exactly because I meant Anki Desktop from the start. This here was a mis-post.

**Comment by timrae** [comment]
Sorry I didn't see your second post due to bad wifi connection on my phone. The Anki Desktop support site is here: https://anki.tenderapp.com/

**Comment by Tomalak** [comment]
Yes, I've opened a thread there already, same text. :)

You're still way too quick for me, I was confused for a moment where your
response belonged to. It's still early morning in Germany. 😴
