### ISSUE TITLE
Can't sync data if the network is behind proxy

### ISSUE THREAD

**Issue by nobitavn89** [ankidroid/Anki-Android#3787]
Hi
In previous version of Anki (2.4), I can synchronize my data if my network is behind a proxy setting. (I connect to the Internet at my University via a proxy server). However, It is impossible in the Anki 2.5

Please consider,
Thanks

**Comment by hssm** [comment]
Can you please post your [debug info as shown on this page](https://github.com/ankidroid/Anki-Android/blob/develop/CONTRIBUTING.asc)?

What happens when you try to sync? Does it crash? Does it show an error? Does it time out?

We have a few error reports regarding proxies so we should look into this but we might need more information and someone to test it.

**Comment by nobitavn89** [comment]
Hi
 I have just tested again and timeout occured. I followed the guide to copy the debug log, but it just shown
AnkiDroid Version = 2.5beta2
Android Version = 4.4.2
ACRA UUID = 13a704b4-eeb9-4036-b28d-09fd124e793c

Then, I took the log of my device. The cause may come from IOException when trying to connect. I attached this log.
Please check the attached files for more details

Thanks.
![2015-11-03 01 38 12](https://cloud.githubusercontent.com/assets/7108516/10899537/0c12fa0a-8219-11e5-9649-832df8fd2e4f.png)
![log_device](https://cloud.githubusercontent.com/assets/7108516/10899538/0c14bd36-8219-11e5-9c88-93f7e67da94c.png)

**Comment by timrae** [comment]
If you uninstall and go back to v2.4.4 does the sync work?

**Comment by nobitavn89** [comment]
Hi Timrae
I works on previous version.

**Comment by timrae** [comment]
Can you please uninstall, go back to the [previous version](https://github.com/ankidroid/Anki-Android/releases/latest), and double check? We can't rule out the possibility that something in your network coincidentally happened around the same time that you updated

**Comment by nobitavn89** [comment]
Ok, please wait. I will re-install an Anki version on Google Play Store and test again

**Comment by timrae** [comment]
It's easier to do it from the link that I provided in my last post

**Comment by timrae** [comment]
If it DOES work with 2.4.4, then please also try [alpha 60](https://github.com/ankidroid/Anki-Android/releases/tag/v2.5alpha60) and [alpha 61](https://github.com/ankidroid/Anki-Android/releases/tag/v2.5alpha61) to help us pinpoint the problem

**Comment by nobitavn89** [comment]
Hi 
I tested on v2.4, alpha 60, alpha 61. The problem occured on alpha 61. It works on 2.4 and alpha60.
![v2 4_2](https://cloud.githubusercontent.com/assets/7108516/10900205/71f7a382-8220-11e5-9f21-107c13bc3908.png)
![alpha60](https://cloud.githubusercontent.com/assets/7108516/10900206/74983cc8-8220-11e5-9e89-45be793ca0db.png)

**Comment by timrae** [comment]
Thank you for testing, it seems that our new HTTP library is the culprit

**Comment by nobitavn89** [comment]
Yes, maybe this problem relates to HTTPS connection lib. 
Nice to help you. If you need to test or clarify anything more, please tell me.
Thanks for your awesome app.

**Comment by timrae** [comment]
Thanks for the report, it should be fixed in beta9
