### ISSUE TITLE
'Undo' button isn't displayed when 'Again' is tapped with learn ahead limit set to 0

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3799]
When 'Easy' is tapped on the last card,
![image](https://cloud.githubusercontent.com/assets/10436072/10869188/6c2a85e6-80ea-11e5-9136-3d5a46684ff9.png)

'Undo' button is displayed.
![image](https://cloud.githubusercontent.com/assets/10436072/10869196/a6856206-80ea-11e5-9f26-a2609e913bfd.png)

However, when 'Again' or 'Good' is tapped on the last card,
![image](https://cloud.githubusercontent.com/assets/10436072/10869203/c0105136-80ea-11e5-8177-5067928bb312.png)

'Undo' button isn't displayed. It is very inconvenient.
![image](https://cloud.githubusercontent.com/assets/10436072/10869208/f803aca0-80ea-11e5-92b5-23448db0b582.png)

**Comment by timrae** [comment]
I can't reproduce it, it must be some specific property of the options group you're using that's causing the bug

**Comment by snowtimeglass** [comment]
Oh, can't it be reproduced on your device? 

Then, would you test with this?
https://drive.google.com/open?id=0BzcRTIITO8NoelZlN01jd3RtdWc

Though the options group of the deck has been default-initialized on Anki Desktop, 
![image](https://cloud.githubusercontent.com/assets/10436072/10869376/86edc6fc-80f1-11e5-8a87-24b4ba42b783.png)
the issue is reproduced on my phone.

**Comment by timrae** [comment]
I just tried and couldn't reproduce it... What are the exact steps you took? Pressing again just keeps repeatedly showing the card again as expected. Pressing good shows the "congratulations! you have finished for now" message with the undo button visible.

**Comment by snowtimeglass** [comment]
>Pressing again just keeps repeatedly showing the card again as expected. 

Ah, please set 'Learn ahead limit' value to zero.

>Pressing good shows the "congratulations! you have finished for now" message with the undo button visible.

Pressing 'Good (10 min)' shows the message of  "congratulations"...?
Are you saying about the reaction after pressing '**Easy**'?

**Comment by timrae** [comment]
> Ah, please set 'Learn ahead limit' value to zero.

That was it

**Comment by snowtimeglass** [comment]
Yeah, thank you.

**Comment by timrae** [comment]
Should be fixed in beta8
