### ISSUE TITLE
Add more information in deck overview screen

### ISSUE THREAD

**Issue by kazuoteramoto** [ankidroid/Anki-Android#3808]
When a deck is finished the deck overview show very little information about the deck. I like how the Anki desktop plugin [More Overview Stats 2](https://ankiweb.net/shared/info/531984586) works in this aspect. If a deck has due cards its show:
![overview_due](https://cloud.githubusercontent.com/assets/291287/10916135/29884f18-8241-11e5-996b-dfd1193280fe.png)
And if the deck is finished its show:
![overview_finished](https://cloud.githubusercontent.com/assets/291287/10916166/3feafdaa-8241-11e5-8180-9fdf5f0b42e7.png)

I find this information very usefull and is a nice _overview_ of the deck.

**Comment by timrae** [comment]
We have essentially removed the overview screen in v2.5; you may like to try the beta version

**Comment by kazuoteramoto** [comment]
Ok, I'm confused I'm using 2.5beta7 and I still have a overview:
On the right side, that is not an overview?:
![screenshot_2015-11-03-20-00-22](https://cloud.githubusercontent.com/assets/291287/10923072/0111b8c4-8266-11e5-8948-e85142d16af8.png)

I think that the empty space on the right can be filled with the information of the OP.

**Comment by timrae** [comment]
Ah yeah we still have it on tablets

**Comment by timrae** [comment]
In general we don't add features that aren't in anki desktop, but that screen is a bit bare bones

**Comment by david-allison-1** [comment]
I'd like to take this on if it's still viable, but I'd like to change the naming (Learning -> Seen):

And young currently contains "Learning/Relearn", which seems incorrect.

* Mature (Review Queue >= 21D)
* Young (Review Queue < 21D)
----
* Seen (Anything not in new (except Suspended/Buried))
* Unseen (Anything not in Seen/Suspended) - should be the same as "Total New Cards"
* Suspended (Suspended/Buried)

**Comment by mikehardy** [comment]
Sure and I think as it's not an ecosystem compatibility issue, you can put what you feel makes the most sense. Only tradeoff is that since it is not ecosystem compatibility, the least code possible is the least maintenance cost possible or course

**Comment by david-allison-1** [comment]
I've had a shot at it, but I don't like it; I can't put my finger on why (maybe it'll confuse new users with too much data). 
I'll shelve it for now unless there's still a desire in the community to get it over the finish line.

![image](https://user-images.githubusercontent.com/62114487/77836449-1f9d1f00-714e-11ea-9417-4a27b450147c.png)

I'll leave a branch on https://github.com/david-allison-1/Anki-Android with it (under 3808) if anyone wants to add the finishing touches.

**Comment by david-allison-1** [comment]
It's a heavily used addon in the desktop. I think I'll come back to this when it next gets flagged. I dislike the screenshot a little less than I did first time.
