### ISSUE TITLE
Allow downgrading AnkiDroid without uninstall it

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3818]
I sometimes downgrade AnkiDroid to compare the new version with the old one.

To do so, I have to uninstall AnkiDroid in advance.
Moreover, after downgrade it or upgrading to the latest version again, I have to log in to the AnkiWeb again, and have to reset 'Gesture' preference again.
I find it troublesome.

Is it possible to allow the system to downgrade AnkiDroid without uninstall it?

**Comment by timrae** [comment]
> Is it possible to allow the system to downgrade AnkiDroid without uninstall it?

No, sorry.

**Comment by timrae** [comment]
there might be some third party apps that let you do it, but I've never tried to use one so can't help

**Comment by snowtimeglass** [comment]
I understand.
I'm sorry to hear that, but thanks anyway for the info.

**Comment by kazuoteramoto** [comment]
One way to downgrade without uninstall is to use

``` pm install -r -d /path/to/ankidroid.apk```

```
-r: replace existing application
-d: allow version code downgrade
```

on a terminal in the device, but you need root to do this.

**Comment by snowtimeglass** [comment]
Sorry, It's a bit troublesome for me at present.
Anyway, thank you for the information. I'm glad to know that there is a way.
