### ISSUE TITLE
There aren't some texts for Google Play on GitHub

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3821]
Can't they be retranslated on Crowdin?
![image](https://cloud.githubusercontent.com/assets/10436072/11019130/7f513eb0-862d-11e5-9981-34fdf201263f.png)

**Comment by timrae** [comment]
The title is already in crowdin, it just hasn't been updated in a while (doing it for every language is a lot of work). We should definitely add the "short description" text that you highlight at the bottom

**Comment by snowtimeglass** [comment]
@timrae, @eginhard 
Has the title string in Crowdin really been reflected in Github (and App) normally?
I suspect that this case is similar to #3761.

**Comment by snowtimeglass** [comment]
@timrae 
>The title is already in crowdin, it just hasn't been updated in a while (doing it for every language is a lot of work). 

Maybe most of the other language versions don't need to be updated, but the present Japanese title is obsolete and it lacks uniformity with "AnkiMobile Flashcards". I'd like to rename it "AnkiDroid Flashcards" as the original title. 

Is it difficult to update the title only for Japanese, for the present? (I suggested the new title on Crowdin about 2 years ago and have been waiting for the change on Google Play so long...)

![image](https://cloud.githubusercontent.com/assets/10436072/26231696/ed58900a-3c8b-11e7-9f67-2a7a634933ed.png)
![image](https://cloud.githubusercontent.com/assets/10436072/26231792/74a62040-3c8c-11e7-80c9-7518f28a5f92.png)

**Comment by timrae** [comment]
@snowtimeglass 
As far as I remember, we gave you access to Google Play, so you can just change the Japanese title yourself ;)

**Comment by snowtimeglass** [comment]
Thank you for the advice! I'll try it :-)

**Comment by snowtimeglass** [comment]
Thanks, I've done it!
