### ISSUE TITLE
Random order applied to all decks

### ISSUE THREAD

**Issue by martinjos** [ankidroid/Anki-Android#3826]
Setting one deck to random order appears to set all decks to random order, and vice-versa. Just go into one deck and change the order, then go and look at another deck - its order has changed too. Unfortunately, by this point it has already done irreversible damage - even if you (for example) switch a deck accidentally changed to random back to deck order, some of the random cards have already been queued up and will appear in your study schedule. This is very frustrating if the new cards are highly dependent on knowledge of previous cards in the deck. Meanwhile, I have other decks where the deck order is arbitrary and studying in deck order would be boring. What I need now is not only a fix for this bug, but also a way to return cards that have already appeared in my study schedule permanently to their correct order in the deck. Suspending the cards is not a desirable solution - the deck is very large and it would require me to work out exactly when to unsuspended the cards in question.

**Comment by martinjos** [comment]
Oops... I've just realised what my problem was, and it isn't this. I was selecting the entire deck instead of just the sub-deck I'd used before.

**Comment by timrae** [comment]
@martinjos 
Sorry for the trouble. As I wrote on Google Play today, it's not really a "bug", it's a "feature" from the Anki system called "option groups" that we can't do much about. You'll need to create a separate option group for the decks that you want to be randomized. Please check the [FAQ for more info](https://github.com/ankidroid/Anki-Android/wiki/FAQ#changing-the-study-options-of-a-deck-changes-the-options-of-my-other-decks).

As for reverting the cards back to the previous order, the easiest way is probably to restore from one of the automatic backups. Unfortunately this would mean that you lose anything you did between now and changing the card order. I'd recommend posting a message to the [main Anki Desktop support site](https://anki.tenderapp.com/), as they may have some better advice for restoring the old card order.

**Comment by martinjos** [comment]
Actually though, the random setting thing is still an issue.

**Comment by martinjos** [comment]
Okay, I've solved that now by creating a new options group.

However, another problem I've had is that if I finish studying one sub-deck for the day and then move to studying another sub-deck of the same overarching deck, which has the same options group (I set all sub-decks in the deck to have the same group), it says that I've finished studying for the day, even though I haven't studied that sub-deck yet. It's not clear to me whether this is because they're in the same "parent" deck, or because they share the same options group, or what. (I haven't studied the parent deck, as I want to keep my studying of the sub-decks separate.) It seems a bit like a bug.

**Comment by hssm** [comment]
>whether this is because they're in the same "parent" deck

Yes, that's how it works. There is a [note in the manual](http://ankisrs.net/docs/manual.html#new-cards) (new cards/day) about new card limits, but the same applies for review limits as well.

**Comment by flerda** [comment]
I believe this might also because of the way option groups work: if you
have a limit of 100 reviews in the option group it applies across all the
decks that use the same option group.

It you want to have a limit in the number of reviews to apply to each deck
individually, you would have to create multiple option groups. You can
check whether you do have a limit under "Deck options" -> "Reviews" ->
"Maximum reviews/day".

**Comment by hssm** [comment]
@flerda The limits aren't shared for every deck, but parent decks apply their limits to all sub-decks.

**Comment by flerda** [comment]
You are right (of course!). Thanks for point this out.

The way I usually handle this is by having a parent deck with a very large limit (e.g., 9999) and a different options group for the subdecks, with the limit I actually want to apply (e.g., 100). As long as I do not have more than 99 subdecks, things work as expected: each deck gets its independent set of 100 reviews per day.
