### ISSUE TITLE
Change the directory of the comlection to SD Card

### ISSUE THREAD

**Issue by gbriel-almeida-santos** [ankidroid/Anki-Android#3829]
Hello, I'm having trouble in change the directory of the media collection. Everytime I try to change an error occurs "this path was not valid". My android's version is 5 (lolipop) and in my old smartphone with jellybean I can chance the directory normally.

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#my-ankidroid-files-are-stored-on-a-sd-card-how-can-i-point-ankidroid-to-them
