### ISSUE TITLE
Actionbar in Android version >= 5.0 is not conform design guide lines and contains App Icon

### ISSUE THREAD

**Issue by pblomsma** [ankidroid/Anki-Android#3831]
![device-2015-11-10-202612](https://cloud.githubusercontent.com/assets/5375984/11073180/a6cbc592-87e9-11e5-84b1-336df0253965.png)

**Comment by ospalh** [comment]
That is the big change for the upcoming version 2.5. Some previews are, for example here: #3789.
You can wait for version 2.5 to be published or [try the beta version](https://play.google.com/apps/testing/com.ichi2.anki), See also the Google Groups [thread](https://groups.google.com/forum/#!topic/anki-android/DrMPHn9NQtk).

**Comment by pblomsma** [comment]
Hi Ospalh, thanks for your reply.. the new design looks really nice! Can't wait :)
