### ISSUE TITLE
indicators how many (new, repeat, mature) cards left disappeared on phone

### ISSUE THREAD

**Issue by peervalhoegen** [ankidroid/Anki-Android#3835]
version 2.5beta11 phone ~~(no problem on tablet!)~~ now on my tablet as well. weird...

click on deck
'learning mode' opens
light blue panel where the numbers should be is empty.
![screenshot_2015-11-11-23-14-31](https://cloud.githubusercontent.com/assets/1398557/11104633/39255f1c-88ca-11e5-9a8a-9bfd6574706d.png)

I tried to tag this with milestone 2.5, but I don't know how. Sorry about that!

**Comment by hssm** [comment]
There is a setting to configure the visibility of the card counts: `Settings -> Reviewing -> Show remaining`

Check to see if you have disabled this.

**Comment by peervalhoegen** [comment]
Oh, cool!
I do not remember unchecking that box. But it was unchecked...
So, checking the box brought the numbers back, thanks!
