### ISSUE TITLE
Draw cards with whiteboard

### ISSUE THREAD

**Issue by dcampezano** [ankidroid/Anki-Android#3836]
Is it possible to create cards simple drawing in a new card? Like in "Squid" or "Papyrus" app. Sorry for my poor English.
denis@campezano.com.br

**Comment by hssm** [comment]
It is not possible at the moment, but we would like to add something like this in the future.

Closing as dupe of https://github.com/ankidroid/Anki-Android/issues/1633.

**Comment by dcampezano** [comment]
Thank you!
Em 13/11/2015 06:40, "Houssam Salem" <notifications@github.com> escreveu:
