### ISSUE TITLE
Don't use immersive mode

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#3850]
@hssm
The immersive API is not designed to be used together with an action bar, and touching it (the action bar) leads to the status bar appearing on top of it. This is only slightly annoying when tapping a button, but when it's the overflow menu the status bar ends up getting in the way and it feels really buggy.

How about removing the immersive mode flag in v2.5 (i.e. revert to v2.4 behavior) until we can come up with a better way to workaround the limitations of the API?

Alternatively, I do have one idea for a workaround to implement real full screen mode if you are highly motivated to spin out a quick solution for v2.5:

Show a permanent notification when the "full screen mode" preference is enabled, which includes a button to toggle full screen on and off. When the reviewer starts in full screen mode, sticky immersive is enabled and the action bar is hidden. Swiping the status bar down and pressing the button in the notification disables immersive mode and shows the action bar, status bar, and navigation buttons.

**Comment by hssm** [comment]
>when it's the overflow menu the status bar ends up getting in the way

What do you mean it gets in the way? For me it's just visible but doesn't hinder interaction with the menu.

I don't think we have to go so far as to remove the feature. I imagine people who turn on full-screen mode want to buy as much space as possible and would prefer the minor aesthetic issue over not having the extra screen space at all.

As for a proper solution, the docs tell you to [use an action bar with overlay mode](https://developer.android.com/training/system-ui/status.html#action-bar) and show/hide it along with the system bar. This solves the problem from before where we left the action bar inaccessible and we also get the maximum space.

I tried to implement this the last time we went over it but I couldn't figure it out. There is something weird about the way we are using the action bar that was making it behave unpredictably and I got frustrated and gave up. I might take a look at it again soon.

**Comment by timrae** [comment]
I think we should be hiding the action bar together with the status bar as in my recent PR, but use immersive mode *without* sticky enabled. We can then use a handler to re-enable full screen mode after say 3 seconds. This is the approach advocated by Google for "reader" apps:

https://youtu.be/cBi8fjv90E4

**Comment by timrae** [comment]
> There is something weird about the way we are using the action bar that was making it behave unpredictably and I got frustrated and gave up.

I had a go at getting the above to work and probably ran into the same issue you mentioned. Disabling the MaterialDrawer fixed the issue, so I've asked the library maintainer about it.
