### ISSUE TITLE
The number of remaining cards for review suddenly decreases after I pressed Undo button

### ISSUE THREAD

**Issue by madnik7** [ankidroid/Anki-Android#3851]
I see there are 200 cards ready due today, after I study about 25~30 cards the remaining card would be around 170. At this time if I press undo button for a card I found out that the remaining card suddenly drop to 125!

This happens every time and I am wondering where the real problem stemmed from.
Note: I always monitor the remaining the remaining cards at the top left corner of the screen.

**Comment by eginhard** [comment]
Do you have "Bury related reviews" enabled in the deck options? This will decrease the remaining card count.

**Comment by madnik7** [comment]
Yes, there is and I do have many related cards. If that's the issue, why burring cards happens after I press undo button and why it is not calculated at the first step? It confuses users.

**Comment by eginhard** [comment]
I see how it could be confusing, but it's the same behaviour as in Anki Desktop and therefore won't be changed on our side.

**Comment by timrae** [comment]
@madnik7 I'd encourage you to convey your usage case to the Anki Desktop team:
https://anki.tenderapp.com/
