### ISSUE TITLE
cannot press button to edit text style because covered

### ISSUE THREAD

**Issue by waldens** [ankidroid/Anki-Android#3858]
check this video (I dunno how to record gif on phone, sorry) :
https://www.youtube.com/watch?v=d-j6yTBHyes

see? Once select some text, cannot press button to edit text style, for it's covered by the bar of android itself, even when close the keyboard temporarily.
both reproduced on 2.5beta16 and 2.5beta2
android4.4.2, huawei 3c 4g

plz fix it if possible. thx so much.

**Comment by timrae** [comment]
Hi that's not a style button, sorry for the confusion. there's no GUI for styling yet. The only actions currently available on that screen are the lookup buttons at the bottom.

**Comment by timrae** [comment]
P.s. for styling you should use standard html syntax like <b>, <i>, <u>

**Comment by waldens** [comment]
@timrae oh, thanks!
