### ISSUE TITLE
Show SVGs of LaTeX instead of PNGs

### ISSUE THREAD

**Issue by sigkell** [ankidroid/Anki-Android#3864]
The PNGs that both Anki and AnkiDroid generate don't mix well with high DPI devices. I opened a PR at dae/anki#112 for the desktop version, but it's mostly bugging me on mobile.

**Comment by timrae** [comment]
Closing as AnkiDroid doesn't generate any LaTeX images

**Comment by sigkell** [comment]
@timrae I'm having a weird issue then. In the issue referenced, it renders fine on desktop, but on AnkiDroid it looks like this: https://i.imgur.com/K5mDGkl.png - any ideas?

**Comment by timrae** [comment]
are you talking about the pixellation? it probably just means that the resolution of your Android device is higher than your computer monitor so that you don't notice.

**Comment by sigkell** [comment]
The resolution doesn't matter. The LaTeX was generated as an SVG on desktop, and looked fine however big I had the window. On AnkiDroid, it doesn't seem to be showing an SVG.

When I manually attached an SVG to a card, it looks perfectly sharp both on Anki Desktop and on AnkiDroid, which led me to believe that AnkiDroid was looking for `latex`/`$` tags to render as PNGs, and Anki Desktop wasn't syncing the SVG. If this isn't the case, why does Anki Desktop show the SVG fine, but on AnkiDroid it appears extremely pixellated?

**Comment by timrae** [comment]
Ah OK I'm not sure why that's happening. Currently neither Anki desktop nor AnkiDroid support svg in LaTeX, so you're kind of on your own sorry. Please open a PR if you figure out a simple solution

**Comment by sigkell** [comment]
Had a look, AnkiDroid explicitly appends '.png' to the filename, that's the issue. To fix this I'd have to do a check to see if either 'x.png' or 'x.svg' exist and choose the correct one to use in the `<img class=latex` tag. I've just modified AnkiDroid to do this and it displays the SVG perfectly.

Would you consider a PR for this, even though it's not something the desktop version of Anki does? Else I can just keep pulling from here and fixing it manually for myself.

**Comment by timrae** [comment]
How is it done in desktop?

**Comment by timrae** [comment]
The png file extension thing I mean

**Comment by sigkell** [comment]
Both desktop and AnkiDroid do it the same by default. I had to modify AnkiDroid similarly to how I modified desktop in dae/anki#112

**Comment by timrae** [comment]
Hmmm I can see the importance of readable math, but it feels a bit hacky. How much does the file size really increase per equation if you increase the resolution on the pngs?

**Comment by sigkell** [comment]
It is pretty hacky. I haven't yet checked, however I just noticed a limitation of using higher-res PNGs over SVGs. [Here's an example from my patched Anki/AnkiDroid](https://i.imgur.com/z1BNnsq.png). There's no way of accurately scaling the high-res image down using CSS since it's in an `<img ...>` tag, but using a vector, the browser handles scaling properly since the intended dimensions are in the SVG.
