### ISSUE TITLE
Immersive mode hides new/learning/due counts and timer

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3866]
The new immersive mode/true full screen hides the bar that displays whether the card is new, learning, or due, and hides the remaining number of cards in each of those categories. It also hides the timer. 

AnkiMobile for iOS deals with this by putting the new/learning/due counts in the Show Answer part of the screen. If AnkiDroid could display the information there, along with the timer, it would improve Immersive Mode.

Otherwise, would it be possible to have two options for full screen? One that preserves the old full screen behavior, by displaying only the upper menu bar, and one that has the new Immersive behavior?

Since I really want to see my timer and card counts, I'm turning off the fullscreen setting, which is a step backwards for me.

**Comment by kabutar111** [comment]
Another issue with same problem is, there is no way to see the button pressed. 

I really do like new immersive mode but I want see timer, card counter and buttons pressed indicator implemented into it. 

Thank you

**Comment by lizzgilmore** [comment]
Good point! I'd like to see the button pressed indicator as well.

**Comment by kabutar111** [comment]
To add to it, 
Every time I perform undo gesture, top bar comes and goes, which makes it very disturbing. 
Also without timer showing, auto show answer and next card pressure that keeps you concentrated, losses is whole point.

**Comment by hssm** [comment]
I'm in agreement about this. I've also ended up turning off full screen mode in this release to get those values back. It turns out I rely on them quite a bit!

We should be able to put it back in.

**Comment by timrae** [comment]
Yeah it's definitely possible, just a bit ugly. How about we can change the fullscreen preference from a checkbox to a list selector with something like the following 3 options?

"off" (default)
"hide system bars" (only hide action bar and navigation bar)
"true fullscreen" (hide system bars, action bar, top bar, and answer buttons; only available when gestures are enabled)

**Comment by kabutar111** [comment]
I suggest it should be revert back to previous release before this until just the light blue bar (showing due and new and timer and button pressed indicator, sorry not sure how is called ) is only visible in immersive mode.

Or  as timrae suggested 
-off 
-fullscreen mode =hide just android status bar  (that shows time and network, sorry Not sure of terminology again )
-immersive mode = current behavior

**Comment by timrae** [comment]
@kabutar111

The options that you gave are completely different from the ones I suggested. Personally I don't think there's a strong use case to hide only the android status bar without hiding the action bar and navigation bars.

**Comment by kabutar111** [comment]
When I  meant staus bar I meant, also soft keys at the bottom which was the behavior in fullscreen mode atleast for me before the last beta

**Comment by lizzgilmore** [comment]
The list selector idea is great! Can we include this option as well?:

Ideally, I'd like to keep the answer buttons as well as the bar with the
timer and new/learn/due counts and the icons that indicate what answer
choice was just selected, but hide everything else. I need the answer
buttons so I can see the interval associated with each answer (i.e. so I
can see good = 10 minutes rather than 3 days). If you moved that
information to the top of the screen or gave us an option for smaller
buttons, that would work great for me - I use gestures, so the answer
buttons are strictly there to give me interval information.
