### ISSUE TITLE
Temporarily displaying the menu bar in landscape mode with fullscreen enabled hides the rightmost menu button and the timer under the Android control buttons

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3867]
On 2.5beta17, with fullscreen enabled, you can temporarily unhide the menu bar by swiping down from the top of the screen. If you're in landscape mode when you do this, you'll find that the three-vertical-dot menu icon is hidden beneath the Android controls (back, home, running apps). The timer is also hidden. See here:

![screenshot_2015-11-22-13-59-32](https://cloud.githubusercontent.com/assets/13272950/11325677/a8cc668a-9121-11e5-8740-67d46aedcfc3.png)

With fullscreen disabled in Settings, landscape mode displays the menu bar icons and timer correctly, like this:

![screenshot_2015-11-22-14-00-20](https://cloud.githubusercontent.com/assets/13272950/11325679/b359ea6e-9121-11e5-91b8-32ff9d6093d0.png)

I like to review in landscape mode, and this issue makes it clumsy for me to edit my cards as I review them.

**Comment by timrae** [comment]
It looks like this is another issue with the library we're using for the drawer... I think we're going to have to get rid of that library
