### ISSUE TITLE
"Increase today's new card limit" works for the highlighted deck, not the specified one

### ISSUE THREAD

**Issue by tsudoko** [ankidroid/Anki-Android#3874]
Long-pressing a deck, selecting "custom study" → "increase today's new card limit", specifying the amount and pressing "OK" will increase new card count for the currently highlighted deck (the one with a slightly darker background tint on the list), not the one that has been long-pressed.

```
AnkiDroid Version = 2.5beta22
Android Version = 5.0.1
ACRA UUID = b3887115-17b7-4ba4-ba9c-84544d3f152b
```

**Comment by timrae** [comment]
Thanks a lot for the nice bug report, I'm not sure how that one slipped through the cracks for so long

**Comment by tsudoko** [comment]
Thanks for the quick fix, the custom study dialog still displays the amount of cards from the highlighted deck, though.

**Comment by timrae** [comment]
Thanks, fixed in RC4
