### ISSUE TITLE
"Hide the system bars and answer buttons" doesn't hide the answer buttons

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3877]
Is this a bug?
![image](https://cloud.githubusercontent.com/assets/10436072/11421359/90906068-9477-11e5-9082-b9ed9ff10e9d.png)
![image](https://cloud.githubusercontent.com/assets/10436072/11421477/90fa3546-9478-11e5-9ad1-5bdd7521abaf.png)

"Hide the system bars and answer buttons" has been selected.
![image](https://cloud.githubusercontent.com/assets/10436072/11421350/7da67c80-9477-11e5-8487-8979e1c9587e.png)

"Enable gestures" has been checked.
![image](https://cloud.githubusercontent.com/assets/10436072/11421354/872b8cc8-9477-11e5-99b5-30b2db55a760.png)

**Comment by timrae** [comment]
What version of Android?

**Comment by snowtimeglass** [comment]
The version is 2.5beta23.

**Comment by hssm** [comment]
I couldn't reproduce this on two devices (6.0 and 5.1.1). Tried a fresh install as well with no issue. Perhaps there was a problem with the preference upgrade?

What happens if you set it to the 2nd option? What happens when you go back again to the 3rd option after that?

**Comment by timrae** [comment]
It's probably a pre 4.4 device, the answer button is hidden in compat now
so I probably need to patch it

**Comment by hssm** [comment]
Yeah that's what it is. Tried it on a 4.0.2 emulator, same problem.

I should probably do a round of testing starting from a 2.3 emulator to catch things like this.

**Comment by snowtimeglass** [comment]
Thank you for handling this problem.
Android version of my device is 4.3.

**Comment by hssm** [comment]
On that same emulator, the answer buttons are now hidden but the action bar and the one below it are still visible. Can they be hidden as well?

![tp1](https://cloud.githubusercontent.com/assets/789082/11434004/a40a7ed8-9519-11e5-932c-e3af46544540.png)

**Comment by timrae** [comment]
No this is only going to be enabled on Android 4.4+

**Comment by timrae** [comment]
Sorry I misread who the author was

**Comment by timrae** [comment]
Below Android 4.4, if we hide the action bar then there's no way to show it again, so I don't think it's a good idea

**Comment by snowtimeglass** [comment]
Thank you.
Now, it works properly.
