### ISSUE TITLE
Hard answer choice indicator dots are invisible in Night Mode

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3881]
On 2.5beta24, when you have Night Mode enabled and you rate a card Hard, the two indicator dots that pop up above the card are impossible to see against the gray background of that bar. If I watch reeeally closely, I can just barely make them out. Having them be so faintly contrasted against this bar makes me wonder "Did I perform the gesture right and trigger the Hard rating? Or did I perform the wrong gesture, triggering Good or Again, and just miss seeing the indicator dots?"

A cleaner solution would be to change the color of those dots to black, or change the gray background of that bar to black. Since the default card background in Night Mode is black anyway, changing the background to black would get my vote here.

**Comment by timrae** [comment]
Black doesn't look good, but I think this darker grey makes it a lot more readable... What do you think?

![dark800](https://cloud.githubusercontent.com/assets/2818274/11448667/3ba8f234-95a0-11e5-9b98-88e731dc170a.jpg)

**Comment by lizzgilmore** [comment]
I think it's marvelous. Thank you!

**Comment by timrae** [comment]
For reference, this is what it looked like before
![dark700](https://cloud.githubusercontent.com/assets/2818274/11448685/a13f6b00-95a0-11e5-99fc-cc510b57b9eb.jpg)
