### ISSUE TITLE
'Undo' button isn't displayed after returning from deck overview screen

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3884]
To be more precise, 'Undo' button is displayed in an instant and then it disappears.

AnkiDroid:2.5beta26
Android:4.3

**Comment by timrae** [comment]
What are the steps to reproduce?

**Comment by snowtimeglass** [comment]
Make a new note.
Tap the deck which includes the note.
![image](https://cloud.githubusercontent.com/assets/10436072/11449627/29cbe812-95c0-11e5-8920-b53dbed6ac70.png)
![image](https://cloud.githubusercontent.com/assets/10436072/11449637/7607ccdc-95c0-11e5-82b8-ab287334109e.png)

Tap "good".
![image](https://cloud.githubusercontent.com/assets/10436072/11449642/a10aba52-95c0-11e5-82f5-65548c4add21.png)

Deck list screen is displayed automatically.
There still is the 'Undo' button.
![image](https://cloud.githubusercontent.com/assets/10436072/11449650/ea1ccbea-95c0-11e5-8995-be948d2e7d0d.png)

Tap the deck again, then deck overview screen is displayed.
![image](https://cloud.githubusercontent.com/assets/10436072/11449655/19534614-95c1-11e5-9fbe-9cdd067373ef.png)

Tap the back button of the device, then deck list screen is displayed again.
'Undo' button is displayed in an instant and then it disappears.
![image](https://cloud.githubusercontent.com/assets/10436072/11449681/16d6ef52-95c2-11e5-9c17-b0fb775ac99b.png)

**Comment by timrae** [comment]
Thanks

**Comment by snowtimeglass** [comment]
Than you, too.

**Comment by snowtimeglass** [comment]
Regrettably, this problem is still reproduced on 2.5beta27.

**Comment by timrae** [comment]
Yes but now if you tap on the deck again undo will be available from there. Undoing the last review from deck list is only supported immediately after the congratulations snackbar is shown. Navigating away from the deck list and coming back to it will hide the button.

Preventing the brief appearance of the button should be possible, however.

**Comment by snowtimeglass** [comment]
> if you tap on the deck again undo will be available from there.

Oh, so I see. Thank you.

>Undoing the last review from deck list is only supported immediately after the congratulations snackbar is shown. Navigating away from the deck list and coming back to it will hide the button.

What was it be designed for?

**Comment by timrae** [comment]
> What was it designed for?

The functionality of the button is to undo the **last review** due to entering an incorrect answer during the final review in a session. After navigating away from the deck list, that action no longer makes sense. Especially after adding / editing a card, it would be unclear exactly what is actually getting undone.

**Comment by snowtimeglass** [comment]
I understand. Thank you for the explanation.

>Preventing the brief appearance of the button should be possible, however.

I'm looking forward to the refinement.

**Comment by timrae** [comment]
In #3899 I've moved the undo feature to the overflow menu. This solves the problem you mentioned, and also allows the undoing of other actions like suspend and edit note (add note is not currently supported).
