### ISSUE TITLE
Allow snackbar of deck overview screen on tablet layout to have 2 or more lines 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3886]
I would appreciate it if you would allow snackbar of deck overview screen on tablet layout to have 2 or more lines, like that of smartphone layout.

![image](https://cloud.githubusercontent.com/assets/10436072/11449774/0ac83fa0-95c6-11e5-950e-1e36b624a972.png)

**Comment by snowtimeglass** [comment]
Thank you. This problem has been fixed.

**Comment by timrae** [comment]
Please try your best to fit the text within 1 line when possible.

**Comment by snowtimeglass** [comment]
I'll take it to heart.
