### ISSUE TITLE
Can you add a function to change the default theme?

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#3893]
The current default theme is light blue.But it cannot fit me custom background perfectly.If the theme can be change like this app,my anki will be more beautiful.
![22](https://cloud.githubusercontent.com/assets/10048069/11451621/6b536732-9607-11e5-8853-83ea162f98ae.jpg)
BTW,I like your  newest  full-screen mode.And thanks a lot for your working.

**Comment by timrae** [comment]
Please see #3757
