### ISSUE TITLE
The name of check mark, "Add", on "Edit Note" is unnatural

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3894]
(On the other hand, the name is natural on "Add Note ".)

I feel that it is unnatural as the note already exists.

Moreover, it is confusing as there is "Add note" on the menu.
![image](https://cloud.githubusercontent.com/assets/10436072/11451819/5b575910-9616-11e5-8ff0-29449754f533.png)

I think it is more natural that the name of the check mark on "Add Note " should be renamed to "Save".

**Comment by snowtimeglass** [comment]
johndem, thank you for the change!

**Comment by snowtimeglass** [comment]
Just now, I tried to check the change for the first time.
However, the 'Edit note' check mark text is not 'Save' but 'Add'.

Does the change have yet to be done?


AnkiDroid version: 2.6alpha5

**Comment by eginhard** [comment]
Thanks, now fixed in 2.6alpha6

**Comment by snowtimeglass** [comment]
@johndem, @eginhard,
thank you for the fix!
I've made sure of it.

However, I can't find the string in Crowdin. 
Does it exist there?

**Comment by timrae** [comment]
I just updated crowdin

**Comment by snowtimeglass** [comment]
I still can't find the string, "Save", in Crowdin.

**Comment by eginhard** [comment]
It's in 02-strings: https://crowdin.com/translate/ankidroid/all/en-ja#q=save

**Comment by timrae** [comment]
Thanks it looks like I accidentally synced with the wrong branch, I just fixed it a minute ago

**Comment by snowtimeglass** [comment]
Thank you. I've confirmed it.
