### ISSUE TITLE
When editin a card, search/add tag only searches and does not add tag

### ISSUE THREAD

**Issue by kmthinkingrock** [ankidroid/Anki-Android#3895]
Text appears left over from when search/add tag were a single function

**Comment by timrae** [comment]
Hi, I don't understand, can you please post a screenshot please? If you're taking about unused tags, you can clear them by running check collection from the main menu

**Comment by eginhard** [comment]
What I assume you mean is that when opening the tag dialog and clicking on the search icon, the hint text says "Add/filter tags". Entering something will filter the tag list, but you can actually still select "Add tag" from the overflow menu to create a new tag with that name, so the text is indeed correct.
