### ISSUE TITLE
Keyboard shortcut for Undo: z

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#3898]
Is there a keyboard shortcut for Undo? If so, what is it? 

If not, can it be mapped to z or u or some other single-character shortcut? In Windows at least, the typical shortcut is Ctrl+z, but I'm using a gamepad that doesn't support multiple simultaneous keypresses so Ctrl+anything is impossible. Even on a normal keyboard it's more sensible to require as few modifier keys as possible, for speed's sake.

**Comment by timrae** [comment]
OK
