### ISSUE TITLE
Please add "marked cards" for custom study deck

### ISSUE THREAD

**Issue by Pepe-Jose** [ankidroid/Anki-Android#3903]
How to start learning only favorites cards from one deck?

I've got one deck and noticed some cards by star (favs). Now I want to start repeat only which I marked.

**Comment by timrae** [comment]
Hi, when you mark a note, it simply adds a tag called "marked", therefore you can use [custom study](https://ankidroid.org/docs/manual.html#filtered) by tag to achieve what you want to do.
