### ISSUE TITLE
Night mode is breaking text to speech

### ISSUE THREAD

**Issue by nicolas-raoul** [ankidroid/Anki-Android#3904]
"night mode is breaking text to speech in latest beta"
https://twitter.com/onmubloger1/status/659363335582814208

I have no TTS so I did not test though.

**Comment by timrae** [comment]
unlikely

**Comment by eginhard** [comment]
Works fine for me with default Google TTS and Android 5.1.1

**Comment by nicolas-raoul** [comment]
He said it does not happen anymore: https://twitter.com/onmubloger1/status/671532757651034113
