### ISSUE TITLE
Auto capitalization should be off for "type answer" fields

### ISSUE THREAD

**Issue by madnik7** [ankidroid/Anki-Android#3910]
I think I hadn't had such problem before verstion 4.5.

In version 4.5, I need to press the shift key each time when going to write in text box or ofcourse turn the auto captilisation off globally. I've tested it with Samsung keyboard and Google keyboard. 

I think it would better to turn off auto capitalisation off for this app.

**Comment by hssm** [comment]
It *is* turned off but the feature doesn't work on older versions of the `Android System WebView` component. Make sure you haven't disabled updates to that app, or turned off system updates in general, or disabled the Play Store from your device.

**Comment by madnik7** [comment]
my device is samsung note 4 and its android system web view is 4.3 (46.0.2490).

I think its up to date and I didn't have such problem before.

**Comment by timrae** [comment]
What keyboard are you using? Can you try the Google keyboard? The previous
version of ankidroid did not display the input box inside the webview which
was inconsistent with anki desktop

**Comment by madnik7** [comment]
I tried both Samsung keyboard and Google keyboard. After your comment, I tried Google keyboard again. 
The auto capitalisation didn't turn off. I mean the problem still exists.

**Comment by hssm** [comment]
Is there anything complex in your card template that might alter the typing element on the card (i.e., is there something overwriting the behaviour in your template)?

I'm really not sure what else could be causing this other than some global override somewhere. That exact WebView version with the Google keyboard works correctly on my devices and emulators.

**Comment by madnik7** [comment]
yes i have. i will check it with a simple card and let you know the result.

**Comment by madnik7** [comment]
I checked it with the a default simple card and the problem is still exists.

But have you looked at this: 
http://stackoverflow.com/questions/5171764/how-do-you-turn-off-auto-capitalisation-in-html-form-fields-in-ios
Use autocapitalize="none" instead of autocapitalize="off" because "off" is deprecated for autocapitalize

**Comment by hssm** [comment]
Sorry I got myself confused with another keyboard problem (auto-complete). We *don't* turn off the auto-capitalization, but it was something we discussed in https://github.com/ankidroid/Anki-Android/issues/3754.

I think we're still not too sure what the best thing to do here is.

**Comment by hssm** [comment]
Okay, so, given that lots of people are complaining about it, I think we should turn off the auto-capitalize. That will make it behave like the previous implementation and with that one nobody really complained about the lack of auto-capitalization.

**Comment by eginhard** [comment]
Obviously changes will cause more complaints, but I agree.

**Comment by madnik7** [comment]
Why don't you create an option for it on deck if it is controversial?

**Comment by timrae** [comment]
This is indirectly fixed in 2.5.2beta1 by making the new input box an option
