### ISSUE TITLE
Can't open or repair collection after upgrade to latest version

### ISSUE THREAD

**Issue by Remco32** [ankidroid/Anki-Android#3914]
I can't get you a debug log since the program won't even open.

I just updated the app and when I ran it it gave me a "Collection not opened" error. When attempting to repair it will repair the collection but to no avail. Doing a full sync from the server does download the collection, but then I get back to the same error. Deleting the collection will let me open the program, but without my decks of course, rendering it useless.

Any suggestions?

**Comment by eginhard** [comment]
Did you upgrade to 2.5.1 already and does this issue still occur there? This sounds similar to #3905.

**Comment by Remco32** [comment]
No, I'm at 2.5. Where can I find this update?

**Comment by lizzgilmore** [comment]
2.5.1 should be available through the Play store (i.e. where you normally
download apps for Android):
https://play.google.com/store/apps/details?id=com.ichi2.anki&hl=en

**Comment by Remco32** [comment]
Following your link it would show me an update. Works like a charm now.
Cheers to the team for the quick fix.
Op 2 dec. 2015 01:06 schreef "lizzgilmore" <notifications@github.com>:
