### ISSUE TITLE
Unbury

### ISSUE THREAD

**Issue by ekimd** [ankidroid/Anki-Android#3916]
Under the "Custom Study" menu, it would be nice to bring back the "unbury" feature.

Thanks for such a wonderful app!

**Comment by timrae** [comment]
It's already be there... It displays at the bottom of the menu when there actually cards to unbury

**Comment by timrae** [comment]
By "custom study" menu, I assume you meant the long-click menu. If that's not what you meant, please access it from the long click menu.
