### ISSUE TITLE
Image search does not return any results

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3917]
This was reported on the forum but I can reproduce it easily. The multimedia editor's image search button comes back with nothing every time I try it.

**Comment by timrae** [comment]
It doesn't use an official API (I'm not sure if one actually exists or not), so I guess it's bound to periodically break. In hindsight we probably shouldn't have merged this as nobody wants to maintain it.

**Comment by hssm** [comment]
I feel that way about it sometimes...

> {"responseData": null, "responseDetails": "This API is no longer available.", "responseStatus": 403}

Apparently it was [deprecated](https://developers.google.com/image-search/?hl=en) in **May 2011**!

**Comment by timrae** [comment]
I see, the replacement API they suggest probably won't work for us, as it's designed for searching a custom range of sites, and I think it will return back a full website rather than structured JSON data.
