### ISSUE TITLE
Please add "add card" button to study screen 

### ISSUE THREAD

**Issue by cgogolin** [ankidroid/Anki-Android#3918]
Quite often when I study my Spanish vocabulary I remember that I wanted to look up and add some word pair or, thinking about the words/phrases I study, I think of some sentence that I would like to be able to say and hence want to add it to my deck.

Unfortunately, currently this is unnecessarily cumbersome as I either first have to leave the study session and then add the new card, or fire up the card browser and then add the card. 

Please add an "add card" button to the tool bar of the study screen. There is more than enough space. 

Thanks!

**Comment by timrae** [comment]
See #3154
