### ISSUE TITLE
Empty cards feature for Ankidroid

### ISSUE THREAD

**Issue by kieranclancy** [ankidroid/Anki-Android#3919]
Currently when a card is empty on Ankidroid, you get a message "Empty card. Run “Tools>Empty Cards...” on the desktop client."

This most often happens when I edit a note on Ankidroid to turn off one of its conditionally generated cards. Sometimes I will do this for quite a few cards but it can be inconvenient if I'm not near my computer to then vacuum them.

How difficult would it be to implement a deck overview function for "Remove empty cards" along with the already-existing "Check database" and "Check media" functions?

**Comment by hssm** [comment]
Shouldn't be too difficult. It makes sense to add this now that we can edit the templates on AnkiDroid.
