### ISSUE TITLE
A keyboard issue with input box ({{type:}})

### ISSUE THREAD

**Issue by madnik7** [ankidroid/Anki-Android#3922]
There is some irritating issue in version 2.5.1 when I study a card with Input Box and gesture.

A) Issue 1: need additional tap
The step to reproduce the problem:
1) I tap the text box to enter the text, then the phone keyboard appeared
2) I enter the text
3) I press the back button on my phone to hide the phone keyboard in order to review the card (Note: I don't press the go button).
4) Now there is no "SHOW ANSWER" button at the bottom of the card. I should tab to just see the "SHOW ANSER" button which not required.

B) Issue 2: Miss comparison with Gesture
The step to reproduce the problem:
1) I tap the text box to enter the text, then the phone keyboard appeared
2) I enter the text
3) I have defined Swip Left to "Answer Recommended (green)". If in this state (the state that is keyboard is still visible without passing go button), I apply the gesture of "Swiping left" then I wouldn't see comparison result.

C) Issue 3: the default input box size is too short and near to "SHOW ANSWER" and sometimes i press "Answer" button by mistake instead of a text box. By the way, I can solve the last issue by changing its size with css.

I have test with Google Keyboard, Samsung Galaxy Note 4 (Latest of all updates).

**Comment by timrae** [comment]
Please see #3912
