### ISSUE TITLE
version 2.5.1 black screen in session with day mode when using my phone

### ISSUE THREAD

**Issue by Musashi1986** [ankidroid/Anki-Android#3924]
When I use ankidroid in my phone in day mode to study a kanji deck I have, for some reason the background of the card appears black, and the kanjis and part of the answer, being black, cannot be seen. I need to enable night mode so that they will be white and I will be able to read them. However, this does not happen when I study the same deck in my tablet (also v2.5.1). All my other decks work perfectly. I didn´t have this issue when I used v2.4.4

**Comment by timrae** [comment]
Does it only happen on that deck? It's possible that you have some styling applied to that deck on your phone which hasn't been synced to your tablet yet.

**Comment by Musashi1986** [comment]
It only happens on that deck. I sync both devices every day, and it did not happen before the update. In any case, night mode works well so I don´t care much about it. Since it only happens in my phone it might be something related to it. In any case, I would say that unless somebody else has the same problem there is no need to worry about it.

**Comment by hssm** [comment]
I want to close this issue but I'm curious about what is going on. Could you post the `Styling` section of the template for that card type? Or just export the deck and send it to me?

**Comment by Musashi1986** [comment]
The styling section of the card is


div.front, div.back {
	text-align: center;
	font-family: myfont;
	font-size: 16px; /* line height is based on this size in Anki for some reason, so start with the smallest size used */
}
span.tiny {font-size: 16px;}
span.small {font-size: 24px;}
span.medium {font-size: 32px;}
span.large {font-size: 72px;}
span.italic {font-style: italic;}

.win .japanese {font-family: myfont;}
.linux .japanese {font-family: myfont;}
.mobile .japanese {font-family: myfont;}
<span class="large japanese">{{kanji}}</span>

@font-face { font-family: myfont; src: url('_kochi-mincho-subst.ttf'); }



The card is not mine. It's from a deck I downloaded. I only tried to modify it a bit to use a different font from the default one (although I was not very succesful, so I just change the font in the options whenever I want to use this deck).

As I said before, the issue must be my phone, since it is the only device in which it happens. In fact, I got so used to use it in night mode that I had forgotten about this issue.

**Comment by hssm** [comment]
Thanks, I just wanted to make sure I understood what was going on. The obvious thing is that your template doesn't specify a background color or text color. My guess is that your device has some vendor-specific theme overrides where a black background is the default when none is specified.

The original Anki template has some default colors. You should probably add them back in:

```
.card {
 color: black;
 background-color: white;
}
```
