### ISSUE TITLE
Auto-sync keep trying to sync after user cancel request (when back on home screen)

### ISSUE THREAD

**Issue by simgunz** [ankidroid/Anki-Android#3925]
Steps:
- Open AnkiDroid
- Autosync begins
- User cancels autosync
- Start studying something
- Go back to home screen

Results:
- Autosync starts again every time the user goes back to the home screen

Expected results:
- No sync should start until the user exits from the app

**Comment by hssm** [comment]
I think we only need to update the last checked time even on cancel.
