### ISSUE TITLE
In 2.5 it takes more time to show answer compared to 2.4

### ISSUE THREAD

**Issue by vi** [ankidroid/Anki-Android#3926]
It used to show it instantly, now it takes about 300 ms.

The card contains image (map).

**Comment by timrae** [comment]
Hi could you please try the following?

https://groups.google.com/forum/#!topic/anki-android/7BNVCRXYhDw/discussion

**Comment by hssm** [comment]
Also, as I mentioned on that forum page, if it's possible for you to export your collection and email it to me so I can investigate that would be really helpful as well.

**Comment by vi** [comment]
It is this deck: https://ankiweb.net/shared/info/1226689493

**Comment by hssm** [comment]
Thanks, I will have a look when I get the time.

>I don't expect problems in one deck to "spill over" to other ones.

It's unlikely, yes, but they do all share the same database, so it's not completely out of the question.

**Comment by vi** [comment]
I have also seen that a picture appears gradually, block by block.

**Comment by hssm** [comment]
I couldn't reproduce it with that deck, so I'm not sure what is going on. Would you be able to downgrade to the [previous release](https://github.com/ankidroid/Anki-Android/releases/tag/v2.4.4) to make sure that the problem completely goes away on that version?

**Comment by vi** [comment]
Re-checked v2.4.3 and v2.4.4 - the same delay.

Maybe seeing the new design I got in "bug hunting" mode and noticed the delay that I was previously ignoring.

**Comment by hssm** [comment]
If the device isn't very powerful then resizing large images is going to be slow like that. There isn't much we can do about it.

**Comment by vi** [comment]
The device is Huawei Honor 6 which I expect to be powerful enough.

**Comment by julienbaley** [comment]
It definitely feels slower (and I see this "charging" icon regularly) than before. On a OnePlus One, not using images, only Cloze.

**Comment by hssm** [comment]
Please see https://github.com/ankidroid/Anki-Android/issues/3979 about the performance issues.
