### ISSUE TITLE
2.5 has animations that I can't turn off

### ISSUE THREAD

**Issue by vi** [ankidroid/Anki-Android#3927]
2.5 seems to bring new look and feel. Visually it looks nicer than (although less convenient - more clicks to access "review forgotten cards" and "edit"), but animations (e.g. sliding between screens) add "bells and whistles" feeling I'd like to avoid.

There should be an option to disable animations.

**Comment by timrae** [comment]
I think it's your imagination; sliding animations between screens have always existed. 

> more clicks to access "review forgotten cards"

The number of clicks is the same, actually. It was 3 clicks on the old version, and a long-click followed by 2 clicks in the new version.
