### ISSUE TITLE
IntentHandler briefly appears on startup

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#3931]
From here: https://groups.google.com/d/msg/anki-android/DrMPHn9NQtk/A0iiZifNAgAJ

Since the default background is white, in night mode, it looks like a brief white flash when the application starts. Surely there's a way to hide the activity completely.

**Comment by timrae** [comment]
I'll take a look at this

**Comment by hssm** [comment]
I'll mention that the IntentHandler part was just a guess, but I'm almost certain that's what it is.

**Comment by timrae** [comment]
`android:theme="@android:style/Theme.Translucent.NoTitleBar"` seems to look a bit better
