### ISSUE TITLE
2.5 has animations that I can't turn off

### ISSUE THREAD

**Issue by vi** [ankidroid/Anki-Android#3940]
It creates "bells and whistles" feeling I'd like to avoid.

There shall be an option to turn them off.

**Comment by hssm** [comment]
Every modern Android application has animations. It's part of the platform and we should be good Android citizens by reusing the components that the operating system provides us. We will not add a setting to deliberately subvert the design intentions of the platform we are on.

If you are sufficiently bothered by animations you can turn them off globally by enabling [developer options](http://www.syncios.com/blog/enable-developer-optionsusb-debugging-mode-on-devices-with-android-4-2-jelly-bean/) and setting these three settings to "off": 
- Window animation scale
- Transition animation scale
- Animator duration scale

Hint: there is a reason settings like this are hidden behind a hard-to-access developer menu.

**Comment by vi** [comment]
OK, disabling those settings works, unnecessary movement on screen is gone.

P.S. Sorry for double-posting, in mobile Github version it wasn't obvious that there is a closed issue.
