### ISSUE TITLE
TTS doesn't work anymore

### ISSUE THREAD

**Issue by giletvin** [ankidroid/Anki-Android#3945]
Hi

Until I upgraded in 2.5.1, Google TTS worked just fine with my japanese/chinese decks. Since 2.5.1, it doesn't work anymore. When I press "Play sound again" (Rejouer le son in french), nothing happens. I reset the languages settings and started again, but nothing more happened.
AnkiDroid version : 2.5.51
Android version : 6.0 (Nexus 5)

Thanks for help

**Comment by timrae** [comment]
Try uninstalling and reinstalling. We didn't do anything that could have broken it as far as I'm aware.

**Comment by giletvin** [comment]
Ok. It seems to work again. Thanks.


2015-12-03 21:19 GMT+01:00 Tim Rae <notifications@github.com>:
