### ISSUE TITLE
Add padding in Study Options screen

### ISSUE THREAD

**Issue by tsudoko** [ankidroid/Anki-Android#3946]
The text could have more padding:
![image](http://u.flande.re/fvpgbu.png)
Highlighted area is not circular:
![image](http://u.flande.re/tuotkq.png)

**Comment by eginhard** [comment]
The highlighted area should indeed not be circular because it's part of the list item, just like the deck name. Additionally, the higher the counts are, the wider is this button, so you couldn't fit a circle anyway.

**Comment by ospalh** [comment]
I am not so sure about the padding to the left and right in the first images, but that is a matter of taste.

But the active area for the deck overview should go further to the left, and there should be a bit more space between the text and the (custom) study button.

**Comment by tsudoko** [comment]
> The highlighted area should indeed not be circular because it's part of the list item, just like the deck name.

It's inconsistent with the way expand/collapse arrows are highlighted, though.

![image](http://u.flande.re/beucdo.png)

Couldn't the highlighted area at least get more space on the left?

**Comment by timrae** [comment]
> It's inconsistent with the way expand/collapse arrows are highlighted, though.

Those are ImageButtons, whereas the deck name and counts are layouts, and they have different behavior.

> Couldn't the highlighted area for card counts at least get more space on the left?

Yeah I've fixed that in #3949 and also added a bit of padding around the congratulations message
