### ISSUE TITLE
Make Study Screen an Option

### ISSUE THREAD

**Issue by julienbaley** [ankidroid/Anki-Android#3947]
Hello Ankidroid team,

thanks a lot for the amazing new interface, a real pleasure to use.
One thing I really like (although I had never realised I needed it) is getting rid of the study screen. It's only unfortunate that 2.5.2 re-introduces it.
I don't really mind either way, but the current solution of having it "if you type on the numbers" is problematic:
Using the phone one-handed means that the thumb naturally hits on the right side (for right handed people), making "study-screen / not" a pretty random behaviour (you're always very close to the in/out boundary). That, and the fact that the numbers have different length depending on the amount of cards..

Could we please have a setting to either enable/disable the study screen? The current functionality is less convenient than either 2.4 or 2.5.

**Comment by timrae** [comment]
I agree that having the clickable areas different lengths depending on the number of cards is pretty confusing, and may prevent a muscle memory from being formed. For now I'll set a minimum length of 70dp for those layouts to make the lengths more uniform. If a lot of people complain about the current configuration then we can consider taking further steps.

**Comment by timrae** [comment]
#3946

**Comment by julienbaley** [comment]
Also really annoying is that going back from a card review to the deck list now takes either 1 or 2 back buttons, depending on how you arrived there. There's hardly a way to train muscle memory for that and it's breaking my previous habit (double tapping it) without letting me create a new one (single tapping).

(thankfully all the apks are still available!)

**Comment by eginhard** [comment]
Yes, that's confusing. I think we should always go to the deck picker
afterwards.
