### ISSUE TITLE
Cancelling Sync Doesn't Pause

### ISSUE THREAD

**Issue by julienbaley** [ankidroid/Anki-Android#3948]
Hello Ankidroid team,

I've discovered that a press on the back key made a pop-up appear asking if I'd like to cancel the sync. Unfortunately, the sync still continues while this pop-up is there, meaning that unless I reply very fast, the sync will happen, regardless of my choice.

Cheers

**Comment by timrae** [comment]
It's way too much work to fix this issue unfortunately, but maybe after we rework the http code in the future it will become possible

**Comment by timrae** [comment]
By the way, it does still cancel the sync, yup just have to wait for the current phase to complete

**Comment by julienbaley** [comment]
For the current phase? I don't understand.

**Comment by timrae** [comment]
Sync protocol has multiple phases

**Comment by julienbaley** [comment]
Perhaps I didn't explain well (or I misunderstood your answer). Here's what happens:
- click sync button
- click `back` button (even very quickly after sync, on a long sync)
- wait (don't select any option in the pop-up)
- sync has finished (it doesn't just pause between phases) <== that's the problem
- select "ok"
- sync has happened and is not cancelled

**Comment by timrae** [comment]
> wait (don't select any option in the pop-up)

Umm, obviously you have to press the OK button on the popup dialog if you want to cancel the sync...

**Comment by timrae** [comment]
At the beginning of each phase, it checks to see if you pressed the OK button, and aborts the sync if you have. Otherwise it continues to the next phase in the sync.

**Comment by julienbaley** [comment]
That considerably reduces the chance someone has to actually cancel a sync, then. You need to press 2 buttons located in different places on the screen, and fast.
Having it wait before the next step when the dialogue is open would make the feature more practical.

**Comment by timrae** [comment]
That's not how dialogs work on Android. With a bit of work I guess we could skip the confirmation dialog during the first phase of the sync though.

**Comment by julienbaley** [comment]
Hmm, ok, that's a valid point.

(I guess I'll keep on using long press on the back button to kill the app instead :) )

**Comment by timrae** [comment]
That's a *really* bad idea, you might end up corrupting your collection. You just need to wait a few seconds for the phase to complete. Another option that I highly recommend is to use the Tasker intent instead of the auto-sync feature. I have mine setup to sync everytime I plug my phone into the charger.

**Comment by timrae** [comment]
Try out 2.5.3beta1. If you press the back button during the first 2 seconds you won't be asked for a confirmation message, which should save you a bit of time.

**Comment by eginhard** [comment]
There should at least be a toast or something to indicate that the sync is being cancelled during those 2 seconds because it will take another few seconds until the sync dialog disappears.
