### ISSUE TITLE
Night mode invert color for background inside iframe but not for the fonts

### ISSUE THREAD

**Issue by jsalatiel** [ankidroid/Anki-Android#3950]
The night mode is a very nice feature, but unfortunately , if you have an html inside an iframe, the background color for the iframe is set to black, but the fonts are still black. So black fonts on black background ... =)

**Comment by hssm** [comment]
The colour inversion we do is quite basic and we can't cover all the edge cases like this one. However, you do have the option to override the styling yourself by giving the iframe custom colours yourself when in night mode. See [this wiki page](https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#customize-night-mode-colors).
