### ISSUE TITLE
Back custom study

### ISSUE THREAD

**Issue by Pepe-Jose** [ankidroid/Anki-Android#3952]
Please add option to make reverse board. It's not cosy to make it always using pc version. Need fast creation as custom deck.

**Comment by timrae** [comment]
https://ankidroid.org/docs/manual.html#reverseCards

**Comment by timrae** [comment]
v2.5 includes a fully featured card template editor, so pc version is actually not necessary any more.

**Comment by Pepe-Jose** [comment]
You don't understand. I ask for another feature.
Just imagine i've got deck with 10k cards. I forgot 100 and want to learn. I make custom deck from forgotten cards. I study. After that i want to study reversed cards from that 100. 

I offered to click on that deck and after Create Custom -> Reversed. I will get reversed cards of my deck. It's simple.


Now you offered me very strange and hard method.

**Comment by timrae** [comment]
Hi in general we only offer the same features as Anki desktop, and the feature that you're requesting can be achieved using by adding a reverse card template (as I previously linked to), together with [filtered decks](http://ankisrs.net/docs/manual.html#creating-manually).

**Comment by Pepe-Jose** [comment]
So can you add request feature to further releases? Now it's not easy.

**Comment by timrae** [comment]
You can submit a feature request to Anki Desktop [here](https://anki.tenderapp.com/), we (AnkiDroid) are not involved with it.
