### ISSUE TITLE
Reverse study not comfortable now.

### ISSUE THREAD

**Issue by Pepe-Jose** [ankidroid/Anki-Android#3955]
You don't understand. I ask for another feature.
Look, i've created topic but you closed it very fast https://github.com/ankidroid/Anki-Android/issues/3952

Sorry if i violated any rules, but read my comment.

Just imagine i've got deck with 10k cards. I forgot 100 and want to learn. I make custom deck from forgotten cards. I study. After that i want to study reversed cards from that 100. 

I offered to click on that deck and after Create Custom -> Reversed. I will get reversed cards of my deck. It's simple.

Now you offered me very strange and hard method.

**Comment by timrae** [comment]
Hi please see #3952, it's not necessary to create a new issue. Thanks for your understanding.
