### ISSUE TITLE
Suggestion: advanced "Deck Counts", which shows latent due cards on deck list screen

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3956]
One of the weakest points of Anki/AnkiDroid is users can't know whether there is any "latent due card" * of the day on main screen (deck list screen).
 
--------------
   *　"latent due card" means a due card (of the day) which isn't be counted in "deck counts" for reasons as follows.

 - Limit of review of the day has already been reached.

 - Limit of new card of the day has already been reached.

 - Due time of the learning phase card of the day hasn't come yet.

 - The card has been buried.

--------------

Such a system seems to demotivate users. Restoring "deck overview screen" can't solve this inconvenience.

I hope the following type of count feature will be added on the deck list screen.

![anki indicator edit trim](https://cloud.githubusercontent.com/assets/10436072/11607334/7307c2a6-9b85-11e5-9a32-4ba680c43cfd.png)

@timrae 
If I remember correctly, in an issue (I try to find it out again, but I can't for now), I read that you said you don't use "bury" feature very much, and re-emphasizing "unbury" button on deck overview screen didn't appeal to you. 
However, just like the poster who posted the issue, I also use "bury" & "unbury" frequently not to postpone a card till the next day but to read it on a more bigger display (a tablet or PC). I would appreciate it if you would consider such a learning style.

**Comment by timrae** [comment]
If I understand correctly, your proposal is really two separate ideas:

1) Having a marker to show when there are latent cards from the deck screen
2) Introducing a way to quickly view how many latent cards there are from the deck screen

For idea 1: Having a marker when there are latent cards seems like a good idea, but I think you'll need to get it accepted into Anki Desktop by @dae before we'd consider implementing it in AnkiDroid.

For idea 2: Since AnkiDroid 2.5.2, tapping on the counts opens the deck overview screen. Most of the information you want to view is already implemented there, so personally I don't feel the change you are proposing is appropriate.

**Comment by dae** [comment]
The congrats screen already tells user if there are cards held back due to the daily limits. The reason it behaves this way was to try and address the big issue of people getting demotivated when they returned after an absence to find 1000s of cards waiting.

**Comment by timrae** [comment]
@dae

How about the first idea of having a marker in the deck list to show decks that have buried cards? If he's burying some cards on a mobile device, then comes back to anki desktop to study them there, it would be a pain to find them without a marker if he has a large number of decks

**Comment by snowtimeglass** [comment]
@timrae

>For idea 1: Having a marker when there are latent cards seems like a good idea,

Thank you!

> For idea 2: Since AnkiDroid 2.5.2, tapping on the counts opens the deck overview screen. Most of the information you want to view is already implemented there, 

The information about latent review cards and buried cards isn't implemented there. It is insufficient.

>, and available with a single click,

Moreover, even if it is implemented, the information itself is buried away under the main screen (deck list screen). 
On the other hand, the advanced deck counts can remain on the main screen and can keep on motivating users by the colored numbers.
I hope the count feature will replace the deck overview screen.


@dae

> The congrats screen already tells user if there are cards held back due to the daily limits. The reason it behaves this way was to try and address the big issue of people getting demotivated 

Compared with the big issue, I feel the notification is too inconspicuous. Once users leave the congrat screen, it is veiled under the grey "0 0 0" or "0    0".

**Comment by dae** [comment]
For now, to avoid losing track of buried cards, you could unbury them after you finish studying each deck, so they're ready and waiting when you return to study on another device.

I appreciate what you're saying about it being easy to miss on the congrats screen, and we've seen people tend to miss text on that screen. That said, I'm a bit worried that some sort of indicator on the deck list would encourage people to investigate the extent of their backlog, leading to the same issues of people feeling overwhelmed.

**Comment by timrae** [comment]
@snowtimeglass 
> The information about latent review cards and buried cards isn't implemented there.

According to Damien, this is an important design decision of the Anki system, in which case we should keep AnkiDroid consistent with the other clients. I agree with Damien that asking you to unbury each deck as soon as you finish studying it is a reasonable way to support your usage case until a better solution is eventually implemented in a future version of Anki.

Please direct future ideas / feature requests in relation to this to the Anki Desktop forum, and if they are implemented there we will most likely also implement them in AnkiDroid.

**Comment by timrae** [comment]
Of course, if you really want to see the number of review cards, you can search in the browser for `is:due`. You can even save this search for this quick access. You could also build a custom version of Anki / AnkiDroid setup exactly how you want it.

**Comment by snowtimeglass** [comment]
@timrae 
>According to Damien, this is an important design decision of the Anki system, in which case we should keep AnkiDroid consistent with the other clients. 

>Please direct future ideas / feature requests in relation to this to the Anki Desktop forum, 

Certainly. I admit that your opinion is reasonable. I'll create a new discussion on the Anki Desktop forum after I reconsider this feature and if I think again that it should be appropriate.

Please excuse me for keeping on replying here briefly to the some points above.

@dae 
>For now, to avoid losing track of buried cards, you could unbury them after you finish studying each deck, so they're ready and waiting when you return to study on another device.

@timrae 
>I agree with Damien that asking you to unbury each deck as soon as you finish studying it is a reasonable way to support your usage case until a better solution is eventually implemented in a future version of Anki.

I also agree to the opinions. Thank you. It's a nice idea.

@dae 
>I'm a bit worried that some sort of indicator on the deck list would encourage people to investigate the extent of their backlog, leading to the same issues of people feeling overwhelmed.

I suppose that handy check and early detection and early cure would prevent people from being overwhelmed. 
Moreover, I suppose that the color of the indicator would be light gray, which wouldn't be pushy for the users who prefer stability of learning pace. (It might be more appropriate to make the indicator itself as an option (on/off) ).

Graded indicator (ex. +/++/+++ , +/+!/+!!) might also help people to notice the situation before it grows  an overwhelming one. 

-----
Anyway, thank you for your sincere comments.
