### ISSUE TITLE
Easy interval 2 days despite deck options set otherwise.

### ISSUE THREAD

**Issue by AgarwalPragy** [ankidroid/Anki-Android#3957]
I see 2 days on the easy interval , even though the deck options have graduating interval , easy interval, maximum interval  set to 1 day.

![image](https://cloud.githubusercontent.com/assets/7423639/11608894/db2b782a-9b9c-11e5-8db8-33119199a66e.png)

![image](https://cloud.githubusercontent.com/assets/7423639/11608900/f14aab30-9b9c-11e5-9164-97b5b45c8464.png)

![image](https://cloud.githubusercontent.com/assets/7423639/11608901/f938525c-9b9c-11e5-9bff-58c150940fa3.png)

**Comment by hssm** [comment]
What does the desktop client do in this case?

If it is different or you don't have the desktop client please export the deck and email it to me so I can have a look.

**Comment by hssm** [comment]
Closing as no followup.
