### ISSUE TITLE
Unable to zoom an image to original size by double tapping on it, while reviewing.

### ISSUE THREAD

**Issue by AgarwalPragy** [ankidroid/Anki-Android#3959]
This used to work earlier, but it doesn't work after the recent updates.

Steps to reproduce:

- Add a large 4k*4k pixels (any sufficiently high resolution) image to your card.
- Review this card.
- Double tap on the image.

Result: Nothing happens:

Expected/Older behavior: The whole card zooms in, and the image is shown in its original size.

Why is this important? Lack of this feature has suddenly made reviewing cards with big images impossible if you're using just one hand to both hold the mobile device and tap the screen icons. (you can't zoom in with a single hand)

**Comment by hssm** [comment]
I honestly don't remember it ever working that way.

I can see this behaviour changing with an *Android* update but I can't think of anything in the latest AnkiDroid that changes this compared to the previous version. Did you update your device or OS recently?

Would you be able to downgrade to a 2.4 AnkiDroid release to compare the behaviour again?

**Comment by timrae** [comment]
I have a vague recollection that it did work like this once upon a time,
but I think Houssam is right and it's probably an Android update (or more
specifically an Android System Webview update) that has caused the change
in behavior. AnkiDroid is designed to show you cards in exactly the same
way that Google Chrome on Android would do, and I just checked that you
can't zoom images with one finger in Chrome on my current device.
