### ISSUE TITLE
font size setting no longer resizes font on my cards

### ISSUE THREAD

**Issue by mdpatrick** [ankidroid/Anki-Android#3960]
I updated to the latest anki on android and have found that I can no longer scale the font down in size on any of my cards. They just stay at the same font size regardless of the settings. 

```
AnkiDroid Version = 2.5.2

Android Version = 5.0.1

ACRA UUID = f0025763-4888-4390-93b9-e64707338906
```

**Comment by eginhard** [comment]
The settings to change the font size is Settings -> Reviewing -> Card Zoom. Does changing its value do anything? Do you use any custom styling in your card templates?

**Comment by mdpatrick** [comment]
Card Zoom is what I needed, thanks. I think this should be a more prominent setting than "default font size", since default font size, whatever its intended for, is probably not what people are looking for. I do not style my cards, but I do use html.

**Comment by eginhard** [comment]
There is no "Default font size" setting, so I'm not sure what you mean. There is "Card browser font scaling", although this clearly indicates that it applies only to the card browser.

**Comment by mdpatrick** [comment]
You're right, that's the one I'm talking about.
