### ISSUE TITLE
Add shuffle-button for Deck

### ISSUE THREAD

**Issue by Nexen23** [ankidroid/Anki-Android#3963]
Before learning I read all cards using bury. If cards count is greater than 100, it's hard enough to read all by one day, so I shuffle cards on next day and read-by-bury unread cards (mixing with read ones).
I do it via `Desk options`->`New cards`->`Order` option. It do the work by setting it to `ordered by date` and again setting it to `random`.

Does anyone except me use this? Maybe `shuffle-button` will be useful then

**Comment by eginhard** [comment]
We could consider implementing it if it was available in Anki Desktop (which it isn't) and I'm also not sure if other people need this. You could make your own fork with such a button added if you need this a lot, it shouldn't be very hard to do.

**Comment by gavenkoa** [comment]
Actually I have a reason for shuffling of desk.

I automatically generate .apkg from electronic dictionary and unless I shuffle notes before insertion they appear in alphabetical order which is boring.

As original Anki store review settings in external to deck structure it is not desired for AnkiDroid also ))

**Comment by eginhard** [comment]
@gavenkoa If you just want new cards to be shuffled, you can do it this way: Long-press on deck -> Deck Options -> New Cards -> Order -> New cards in random order.

**Comment by gavenkoa** [comment]
Thanks!

Unfortunately official docs missed keywords "order"/"shuffle"/"random" so I iterate over all option/menus till found solution myself.

As said desktop Anki docs: http://ankisrs.net/docs/manual.html#newopts I should use this option each time after adding new cards:

*One caveat with random order mode: if you review many of your new cards and then add more new cards, the newly added material is statistically more likely to appear than the previously remaining cards. To correct this, you can change the order to ordered mode and back again to force a re-sort.*
