### ISSUE TITLE
unicode characters misaligned

### ISSUE THREAD

**Issue by HairyPhil** [ankidroid/Anki-Android#3966]
In attached screenshot, field "example sentence", the first character (accent before the E) is cropped.

This example isn't so bad, but there will be others in other character sets where the first character is completely hidden.

AnkiDroid v2.5.2 on Android 6.0 on Nexus 5.

![example](https://cloud.githubusercontent.com/assets/15921262/11626403/1b31f530-9ceb-11e5-83bc-463f45b9d45a.png)

**Comment by eginhard** [comment]
Could you paste the text of that field here? Are there any other characters where this happens?

**Comment by HairyPhil** [comment]
example sentence:
Έχω σχεδόν γλίστρησε.

Cropped characters: Έ Ί Ϊ Ϊ́ Ό Ή Ύ
Not cropped: Ά Ώ

Ύ is completely cropped so you'd think it was a regular Υ.

I realise this is a very specific low-priority problem.

**Comment by eginhard** [comment]
Thanks, but this is unfortunately out of our control and an Android issue occurring in all text fields.
