### ISSUE TITLE
Edit card: changes lost after using back button

### ISSUE THREAD

**Issue by martinjos** [ankidroid/Anki-Android#3968]
Basically, I have found that after editing a card and then going back to look at a card before the one I edited, the changes are lost. In fact, there is clearly something strange happening because when I press back to pass through the edited card, I see the edited card twice: first in the post-editing form, then in the pre-editing form. Once I have reached this point, the edits are gone forever. Clearly I don't want my edits to be lost just because I go back to look at or edit something else.

**Comment by timrae** [comment]
Sorry I don't understand what you mean... could you please record a video and put it on youtube or something?

**Comment by martinjos** [comment]
1. Start revising a deck.
2. Edit one of the cards that you are revising.
3. Go to the next card.
4. Press the back button once, and reveal the card. The edited card will be visible, with your edits.
5. Press the back button for a second time, and reveal the card. You will see the same card again (the one you edited), but your changes will be gone.
6. Search for the card in the card browser. Your changes will be missing from there too.

I hope that makes it clearer. Thanks!

**Comment by timrae** [comment]
I think you mean the undo button when you say "back button". Back button is the button at the very bottom left built into the OS

**Comment by timrae** [comment]
This a known issue, see #3374

**Comment by martinjos** [comment]
This seems like a bug to me. Undoing an edit is a fundamentally different kind of operation from undoing a card view. I can't imagine anyone actually wants the present behaviour. Couldn't it be fixed? I think it would make more sense to have a separate undo button that only appears on the edit screen, for undoing edits. Then, if you want to go back to a card and undo an edit, you have to go back into the edit screen, so at least you know what you're doing.

**Comment by timrae** [comment]
Hi Martin, as discussed in #3374, yes it's a known issue that needs to be fixed. Fixing it is quite a lot of work and it's not at the top of our priority list, but it should be fixed eventually.
