### ISSUE TITLE
File name case ignored

### ISSUE THREAD

**Issue by flimzy** [ankidroid/Anki-Android#3973]
I have observed this behavior both in AnkiDroid 2.4 and 2.5.

I have a French vocabulary card for the word 'terre', and two definitions and two images.  The images are named 'terre.jpg' and 'Terre.jpg', respectively, as the second definition refers to the proper name of the planet on which we live.

But AnkiDroid doesn't recognize that 'terre.jpg' and 'Terre.jpg' are distinct images, and shows the same image twice (which image it shows seems to be indeterminate, as I've at times seen 'terre.jpg' and at times 'Terre.jpg').

![terre](https://cloud.githubusercontent.com/assets/8555063/11653593/86d20e1a-9d9f-11e5-8999-d9275da6ea40.png)

**Comment by timrae** [comment]
In order to be compatible across multiple different filesystems (e.g. NTFS and FAT) we don't support media files that only differ in the case. Please use unique filenames.

**Comment by flimzy** [comment]
Is this a limitation imposed by the desktop client, then?

**Comment by timrae** [comment]
I'm not sure exactly where it's enforced, but it's definitely not supported. One can also run non-case-sensitive file systems on Android.

**Comment by flimzy** [comment]
Alright, thanks.

**Comment by flerda** [comment]
It is not desktop only and the behavior depends on the file system used by your phone.

Many phones use VFAT or FAT32 for the SD card storage, which is case-preserving but not case-sensitive. This means that there cannot be two files on such file systems named terre.jpg and Terre.jpg, but if you choose one of the two capitalization, it will stick, and both names will refer to the same underlying file. Looking at your results, it seems this is the case that applies to you.

If you use a phone that uses another file system (e.g., ext4) and do not sync your deck (AnkiWeb might do something like storing only one of the two files) it might actually work, but, as Tim said, it is not supported as it would not work on all Android+Desktop possible cases. Basically AnkiDroid does not do anything to try to stop you from doing so, but the results may vary depending on the particular file system your device uses and we will not do extra work to try and support it on those cases where it can be.

Hope this helps explain.

**Comment by flimzy** [comment]
Yes, thanks @flerda, that makes perfect sense.
