### ISSUE TITLE
<i>tag</i> seems not working

### ISSUE THREAD

**Issue by mrwashu** [ankidroid/Anki-Android#3975]
AnkiDroid Version = 2.5.2
Android Version = 4.2.2
ACRA UUID = 02e45f47-c254-432e-9c1d-01fabf1a26de

I am using Arial from MS. Before renewing the app italic worked well.

**Comment by eginhard** [comment]
Does it work fine for you when using the default system font? Then you need to make sure to exactly follow the instructions for using custom fonts in the manual: https://ankidroid.org/docs/manual.html#customFonts
