### ISSUE TITLE
Unseen cards pop up again

### ISSUE THREAD

**Issue by bogdanteleaga** [ankidroid/Anki-Android#3977]
This is most likely an Anki bug, but I couldn't find a place to file the bug in the repo so I'll leave it here for now.

So I'm using the Human Japanese deck(it's on the shared deck page). It has tags for every chapter so I've always been pulling cards away in separate chapter decks, studying them with rescheduling and then letting them go back to the main deck and continuing there.

It all worked good until yesterday when I thought I was done(finished all cards in the latest chapter + some more that were still unseen because I buried them earlier) and I'd have only reviews to do, only to wake up and see about 500 total new unseen cards, some of them in my main deck, and some of them in the custom decks(which I didn't delete, because I was lazy).

Having them pop up in the custom made decks seems really weird since from what I understand they should be completely moved back to the main deck once they go in review mode and the deck should be 'empty'.

I also seem to be getting some funky reviews(there's a bit more than I expected) and some of them have odd dates.

I tried running a check database and a check media and they were good. Anybody has ideas?

**Comment by hssm** [comment]
The correct place for Anki support questions is [here](https://anki.tenderapp.com/discussions/ankidesktop).

Unless you are convinced this is an issue specific to AnkiDroid we won't look into this any further.

**Comment by bogdanteleaga** [comment]
Actually, I think it might be a AnkiDroid bug. I remember I changed the app yesterday. I used to have the version I built when I submitted a patch, but I uninstalled it and installed the new one from Play Store. I did not change the AnkiDroid directory in the home folder at all.

**Comment by eginhard** [comment]
There is a setting in the deck options that limits how many new cards you
see per day. You might have just seen more new cards the following day
because you had reached that limit.

**Comment by bogdanteleaga** [comment]
As I said I complete the deck one chapter at a time, using tags(so custom decks). Custom decks do not have a limit, all the cards appear directly. I know siblings get buried, but I got new and unseen cards in a deck I created about a month ago and all the cards in it have been transferred back for a while now.(That means I haven't had new cards there for at least a couple of weeks).

**Comment by bogdanteleaga** [comment]
Still have a backup from before, but when I import it shows up the same and if I try to restore to an older backup it says invalid apkg file

**Comment by hssm** [comment]
To be honest I don't understand the problem from your description. When you say "unseen cards", do you mean new cards? Why is it that new/unseen cards are not expected? I'm a bit fuzzy on the details of new cards in filtered decks. I'm pretty sure they don't move back to their parent deck until all the steps are completed.

Also, cards that are ahead of schedule in filtered decks appear as new cards which usually confuses people. Are you reviewing ahead?

**Comment by bogdanteleaga** [comment]
Ok, I think I have an easier example.

This also happened with the kanji radicals deck.

I finished that one about 2-3 weeks ago(by finished I mean, I only had review cards left, no new/unseen cards). Now since then I've been having like 5-20 reviews/day.

And yesterday I had 65 new cards and 100+ reviews to do. Now, to be honest I *do* think I've not been getting enough reviews for those 2-3 weeks and I *do* think that I didn't see the back of some cards, but I don't understand while Anki decided to shove them all unto me yesterday.
