### ISSUE TITLE
Problem with Persian alphabet flashcards

### ISSUE THREAD

**Issue by uu5hwkxx** [ankidroid/Anki-Android#3981]
Hi
When I have a flashcard showing dots '.' or underscores '_' followed by some Persian characters (that is dots on the right, as you read right to left), the dots or underscores will be shown after the characters (that is dots on the left).
![ankidroid-bug](https://cloud.githubusercontent.com/assets/16221521/11681499/91462a5a-9e5f-11e5-81b3-2ab920646e10.png)

**Comment by hssm** [comment]
See [this](http://ankisrs.net/docs/manual.html#rtl-%28right-to-left%29-text).

**Comment by uu5hwkxx** [comment]
Alright thank you, it works well as a workaround :-)
