### ISSUE TITLE
Odd highlighting behavior when deleting lines and then adding a space

### ISSUE THREAD

**Issue by jkhooker** [ankidroid/Anki-Android#3983]
Imagine I have the following text in a text box when adding a flashcard:

"Hello in English is a word used to

greet someone"

If my cursor is just before the word "greet", and I hit [delete] twice, I will have "togreet someone" at the end of the sentence. Then, when I hit [space], I then have "to greet someone" at the end of the sentence. The problem is that then Anki bizarrely highlights part of the text and I can't get rid of that text.

I am running version 2.0.33

**Comment by eginhard** [comment]
This is the project for AnkiDroid, Anki's Android app which has a separate development team. Please post any issues with Anki in its forum: https://anki.tenderapp.com/discussions
