### ISSUE TITLE
Play media icon has been shrunk (height is too small) after turning phone into landscape mode

### ISSUE THREAD

**Issue by kelciour** [ankidroid/Anki-Android#3985]
If you rotate you phone into landscape mode then icon don't look good. Here it is:
![bug](https://cloud.githubusercontent.com/assets/16260735/11756037/f5a8a57c-a067-11e5-9a74-364395a0ced1.png)
But if you close your activity with home button and then reopen it -> icon's size will be good

I uploaded screen recorded video with bug example and custom apkg file for testing -> 
https://drive.google.com/file/d/0B85sBfBcfeSWM3FRc0xBT21zNTQ

AnkiDroid Version = 2.5.3beta5
Android Version = 4.4.2
Phone = Fly IQ436i

**Comment by hssm** [comment]
I reproduced it on a 320x480 screen. Not sure why it happens since the height and width are both set to 32 pixels. Don't really know how to solve it either since it's a WebView thing I think.

**Comment by kelciour** [comment]
I found solution in the official manual: http://ankisrs.net/docs/manual.html#card-styling
> One other thing to note is that Anki shrinks images to fit the screen by default. You can change this by adding the following to the bottom of your styling section:
`img { max-width: none; max-height: none; }`

I tried it and it worked!
