### ISSUE TITLE
Startup: no splash screen, green action bar on black background

### ISSUE THREAD

**Issue by kelciour** [ankidroid/Anki-Android#3986]
In new version with material design there is no nice startup activity screen when app starts the first time. And for 1 sec black activity with green status bar was seen.

This url contains two different recording video of start up an app - one for 2.5.3. and one for 2.4.3 version
https://drive.google.com/file/d/0B85sBfBcfeSWRkY1eUVnR19qQms/view?usp=sharing

AnkiDroid Version = 2.5.3beta5
Android Version = 4.4.2
Phone = Fly IQ436i

**Comment by eginhard** [comment]
Yes, we intentionally removed the splash screen because it's not really necessary. Usually the app loads fast enough and it's cleaner to show the progress circle directly in the main activity. I'm not sure where that green status bar comes from...

**Comment by timrae** [comment]
I just had a bit of a play around. It would be relatively simple to get something like this working if people like it...?

![splash](https://cloud.githubusercontent.com/assets/2818274/11760662/468f8ef0-a0e6-11e5-85b6-fdc0bc6f0671.png)

**Comment by timrae** [comment]
![splash2](https://cloud.githubusercontent.com/assets/2818274/11760760/cf95d5d4-a0ea-11e5-824d-0fe726c85baa.png)

**Comment by timrae** [comment]
![splash3](https://cloud.githubusercontent.com/assets/2818274/11760803/fdfc9082-a0ec-11e5-8656-6b0b35af607d.png)

**Comment by timrae** [comment]
@kelciour the loading time on your device is really really slow. Has it always been that way?!

**Comment by kelciour** [comment]
@timrae thank you very much. I noticed it but did'n try to fix it or understand where is the problem. I just used "Check database" and now it opens in 3 seconds instead of 10 seconds. 
I think it because I watched 2 season of Friends (in total 5000 cards) when every series contains about 100 cards. But after watching one series I delete 90% of watched cards and keep only 0-15 cards for every series.
