### ISSUE TITLE
The best Ankidroid Version is 2.3.2 because ...

### ISSUE THREAD

**Issue by M-M-Rezaee** [ankidroid/Anki-Android#3988]
Dear Ankidroid developers,

My Ankidroid Version is 2.3.2, and I do not want to up to date it, due to I checked new version and in spite of its artistic appearance, it does not have my favorite icon which I have denoted it in the attached image. My friends and I apply this Icon frequently. I was wounding if you could add this icon on the new version.

I look forward to hearing from you.

Bests, 
M.M-Rezaee

![suggestion](https://cloud.githubusercontent.com/assets/16259978/11760507/b9114988-a0b3-11e5-9958-ab438058d357.jpg)

**Comment by timrae** [comment]
The preview function can be accessed by long-clicking on an item in the browser and choosing "preview"
