### ISSUE TITLE
AnkiDroid crashes when displaying answer

### ISSUE THREAD

**Issue by m0ndra** [ankidroid/Anki-Android#3991]
AnkiDroid Version 2.5.2
Phone: Jolla with Android sandbox

The app crashes everytime I hit the "show answer" button in one of my decks. The answer card should load a special font to show how a specific character is written. 
I guess this might be the cause of  the crashes because all my other decks which don't use that font work perfectly fine. I didn't have any problems with Version 2.4.4

**Comment by timrae** [comment]
Hi could you please provide us with your "debug info"?
https://ankidroid.org/docs/help.html

**Comment by m0ndra** [comment]
AnkiDroid Version = 2.5.2
Android Version = 4.1.2
ACRA UUID = f82edc45-96b3-4a7d-9fea-0e14b4611694

**Comment by timrae** [comment]
Thank you, also before I look further into the issue, could you please try running "check database" from the main deck list, and see if that fixes your issue?

**Comment by m0ndra** [comment]
Okay so I get a "Datenbank überprüft" (database checked) message, the screen reloads..
When I now try to get the answer card for the first time after I run "check database" it works --> the answer card is shown without any mistakes. 
But the next card causes a crash. After restarting AnkiDroid, it's the same:

First try --> the answer card is presented correctly
Next card --> crash

**Comment by timrae** [comment]
I can't find any crash reports submitted by you in our system with the UUID that you pasted above. Could you please check that you haven't set "Error reporting mode" (in the main AnkiDroid settings) to "Never report"?

**Comment by timrae** [comment]
Also, would you be able to export the deck that is causing the crash, and email it to me so that I can try and reproduce? perceptualchaos2 at gmail

**Comment by m0ndra** [comment]
Well, I don't get a chance to send a crash report since I don't use an original Android device. My phone just emulates Android Apps in a virtual machine and the whole VM crashes and then restarts itself showing me the start screen of AnkiDroid App. 
I guess it can't be helped without the crash report...but I will send the deck to you. 
If the app won't crash on an Android device I guess its a phone(VM)-related problem.

**Comment by m0ndra** [comment]
I dont know if it's important but does AnkiDroid use any Google Play services? My phone doesn't have the play store installed (like cyanogenMod) and so this might be an issue if ankidroid uses any of the google play services...

**Comment by timrae** [comment]
I tried the deck that you sent on my device and it doesn't crash. If you can upload a log file I'll take a look at the crash signature to see if anything comes to mind, but we can't support non-official Android devices. Thanks for your understanding.

**Comment by timrae** [comment]
No we don't use Google Play services.
