### ISSUE TITLE
Bug: the color of the overflow menu of the deck list screen is odd

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#3996]
as if it were on night mode.
![image](https://cloud.githubusercontent.com/assets/10436072/11779392/257a0196-a29e-11e5-8da5-56fcb8f50fcd.png)

AnkiDroid: v2.5.3 & v2.5.3beta9
Android: 4.3

**Comment by timrae** [comment]
Thank you
