### ISSUE TITLE
LaTeX images too large and pixelated

### ISSUE THREAD

**Issue by BertrandsBallot** [ankidroid/Anki-Android#3998]
On AnkiDroid (v2.5.4) there appears to be a problem with images generated from LaTeX displaying as the correct size which leads to some extremely oversized image files being displayed. Below are two images showcasing the issue. The first image is one taken of AnkiDroid and the second is from Anki on Windows 10.

![screenshot_2015-12-14-07-44-43](https://cloud.githubusercontent.com/assets/6732283/11785816/4da30e12-a238-11e5-97e1-4744781c5b87.png)
![anki](https://cloud.githubusercontent.com/assets/6732283/11785818/4f6cecd6-a238-11e5-88f2-676380bd6dd6.PNG)

**Comment by eginhard** [comment]
See the discussion in #3864
