### ISSUE TITLE
Unable to login: Invalid email address or password

### ISSUE THREAD

**Issue by Gregyski** [ankidroid/Anki-Android#4000]
When I tried to sync with my Ankiweb account today, AnkiDroid indicated I was not logged in.  I've been successfully syncing without issue for about two years now, and this is the first time it has happened. Nothing has changed as far as my email-address or password in all that time.

After reentering my credentials, I am given the error message "Invalid email address or password" after about 1 second.  I verified their correctness through repeated typed-in attempts and by copying and pasting from a text editor to ensure both were exactly correct.  I ensured that the android keyboard was not appending a space.  I'm definitely using my email address and not my username (although I tried the latter anyways)

I tested my credentials both directly on Ankiweb and the Windows Anki application, and it worked fine in both locations.

As for the email address itself, the only thing possibly unusual about it is it has an underscore in the name (e.g. foo_bar@foobar.com).  The password is purely alphanumeric and is 11 characters in length.  As I mentioned, these have worked in AnkiDroid without issue for a long time.

**Comment by timrae** [comment]
Does it think about it for a while (i.e. try to connect to the internet first), or just immediately show that error?

**Comment by Gregyski** [comment]
The "Logging in..." swirl lasts just under 1 second, but definitely not immediate.

**Comment by timrae** [comment]
That's really weird. It's working fine for me, with underscores and all. If you see the "Logging in..." message, 1 second of swirling, and then "Invalid email address or password" you must have been sent a 403 code by AnkiWeb.

What happens if you make a dummy account with a different email address (use mailinator if you like)?

**Comment by hssm** [comment]
Yep, looking at the code, the only way to get that error is if AnkiWeb rejects your credentials.

Are you using the default keyboard? Maybe your keyboard is automatically capitalizing the text, or maybe the ```_``` or ```@``` isn't the standard kind. For example a Japanese keyboard would input ```＠``` instead of ```@```, which are not the same.

**Comment by Gregyski** [comment]
Those are good suggestions, thank you both.  I'll try creating an alternate Ankiweb account tomorrow and see how that goes.  I do use Swiftkey but I believe pasting as I did would bypass that being a problem.  Nevertheless, I'll switch to default android keyboard as well and try that again as well.

**Comment by Gregyski** [comment]
I switched to the default android keyboard and reentered my original credentials, and I got the same error.  I also typed those same credentials into a text editor to visually verify them and copied and pasted those into Ankidroid, but I got the same result.

I then created a new Ankiweb account and entered those credentials, and it worked fine.  (Well, I got a sync conflict error, but I assume that means I was successfully logged in.)  For the test credentials, I did use an email address on the same domain without an underscore but with a password with only 8 characters instead of 11.

**Comment by timrae** [comment]
@dae any ideas? It's kind of difficult to see how this could be an AnkiDroid problem

**Comment by dae** [comment]
Please create a private ticket on our support site and post the IP address you're trying to log in with and your AnkiWeb ID, and I'll see if the logs reveal anything. The fact that it works on AnkiWeb and the computer program but not AnkiDroid makes me think something may have gone wrong when AnkiDroid changed from sending the login details in the query string to a POST instead - perhaps the characters are being escaped in the wrong way.

**Comment by timrae** [comment]
@dae
That change you mentioned was during the registration process. We now simply do registration with the browser. The login code is unchanged.

**Comment by dae** [comment]
Ah, you're right of course - sorry for the noise.

**Comment by Gregyski** [comment]
Sorry, but which support site is that?  I see AnkiDroid on github and the AnkiDroid Google Groups forum.  Or do you mean the Anki non-android support site at https://anki.tenderapp.com/?

**Comment by timrae** [comment]
Yeah he means tenderapp

**Comment by Gregyski** [comment]
I created the ticket.  Thank you.  I know I could just move my decks over to a new account, but I figured if I could help diagnose a possible problem it was worthwhile.

**Comment by timrae** [comment]
Yes, thanks a lot, it's much appreciated.

**Comment by Gregyski** [comment]
I'm exceedingly embarrassed. A lack of serif got me. It was the old l vs I vs 1 situation, which I should know well enough to recognize. But I kept double checking myself and still overlooking it. I typed it dozens of times across all three locations and still only failed on Android.

Then, when thinking I put in the right thing and getting that error message, I thought it was indicating the email or password were malformed as opposed to erroneous. Nevertheless, it was my fault.

I'm sorry for wasting your and your team's time. If there is something I can do to test or something to try to make it up, let me know.

**Comment by timrae** [comment]
Haha ok these things happen. As per the [contributing wiki](https://github.com/ankidroid/Anki-Android/wiki/Contributing), answering questions on the forum when you know the answer is always a big help. Becoming a [beta tester](https://ankidroid.org/docs/manual.html#betaTesting) and reporting any issues is also helpful.
