### ISSUE TITLE
Selected gallery image is not showing in review/preview even though the html is of selected image.

### ISSUE THREAD

**Issue by ambioct** [ankidroid/Anki-Android#4004]
Some cards are not showing up the image selected from gallery but instead getting replaced by one of the images added to previous cards of the deck. This occurs even when previous images are deleted from the gallery.

**Comment by ambioct** [comment]
I found that the html of some of the downloaded gallery images (in current session of preparing cards) are similar to the html of previously downloaded images to my gallery but which were deleted from device folder after preparing cards in previous session. eg:<img src='download (4)'/> present in a previous card is being shown rather than the current selected image with the same html.

And I didnt find any option to change the image name in my Google photos settings.

**Comment by timrae** [comment]
Try renaming them with a file manager:

https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid
