### ISSUE TITLE
Generate a single card with all the cloze type note's clozes to be reviewed that day

### ISSUE THREAD

**Issue by ambioct** [ankidroid/Anki-Android#4005]
New feature that makes a **single card**, with _all the note's clozes to be reviewed that day_, from one cloze type note instead of as many cards as the number of clozes in the note. 

Reviews are done with **auto scrolling** down the single card. _Note's clozes to be reviewed that day_, while are being answered successively from top to bottom of the card, simultaneously, the screen view keeps moving down the card.

This is useful for learning a _whole lengthy essay_ by eliminating the problem of **"dissociation from context"** that occurs from apparent randomness arising in reviews of the many cards made out of one cloze type note. 

One gets to go through and learn the _whole essay_ **"in the order"** it exists and needs to be learnt.

**Comment by ambioct** [comment]
Sorry for repetition of paragraph, by mistake got jumbled up in the short text box.

**Comment by hssm** [comment]
This is a very specific use case that is better off implemented as an add-on on the desktop client. You can implement the scrolling with Javascript.

In general we won't implement any type of card-generation that doesn't exist on the desktop client. You can pitch your idea over at their support site but honestly you will just be told to make an add-on.
