### ISSUE TITLE
Cards not showing answer field

### ISSUE THREAD

**Issue by RamsesDeNorre** [ankidroid/Anki-Android#4007]
Since a couple of versions ago, a lot of the cards in my decks don't show the answer field anymore.
It are always cards with an optional third field that's shown alongside the answer in either direction.
These used to work perfectly but suddenly the answer started looking like the screenshot below, only showing that third field and not the actual translation.

I am using the latest beta release, but this bug has been present for a couple of weeks already. I'd be happy to provide you with any additional information to troubleshoot the issue.

![screenshot_2015-12-15-00-15-39](https://cloud.githubusercontent.com/assets/141248/11906874/05a11d20-a5d0-11e5-8935-78a1c03e9e0d.png)
![screenshot_2015-12-15-00-15-46](https://cloud.githubusercontent.com/assets/141248/11906873/059b5dfe-a5d0-11e5-90ae-b33e6758c15d.png)

**Comment by hssm** [comment]
In your second screenshot we can see that there are *three* card types (*Card 1, Card 2, Card 3*) associated with this note type. Basic (and reversed card) normally only has *two*, so I think you have accidentally added a third card when playing around with the card type editor and this is what one of those cards looks like.

**Comment by RamsesDeNorre** [comment]
I didn't notice that, you're completely right.
Closing this issue.
