### ISSUE TITLE
I want to reverse it and listen to the pronunciation of the question part only. Is this possible?

### ISSUE THREAD

**Issue by tesoke** [ankidroid/Anki-Android#4009]
Hi, I use ankidroid on my cellphone. My problem is that the software pronounce the answer part (below in a card) but not the question part (top in a card.) I want to reverse it and listen to the pronunciation of the question part only. Is this possible? Thanks a lot.

**Comment by tesoke** [comment]
no idea? Please help.

**Comment by flerda** [comment]
I am not sure if I understand what you want to do.

If what you want to do is reverse the front and back of your cards (not just what is read out loud), you can follow these instructions.
https://ankidroid.org/docs/manual.html#reverseCards

If you want to select what is read out loud without changing what is shown as question and answers, you might be able to do so by altering your template, but I have not done so myself, so I cannot give you detailed instructions. You might want to have a look at https://groups.google.com/forum/#!forum/anki-android for related topics.

**Comment by timrae** [comment]
@tesoke 
If I understand correctly you are using TTS and the question is not read aloud? If so, you can try going to  settings -> advanced -> Reset languages. Then next time it should ask you to choose the language for question and answer again.

**Comment by tesoke** [comment]
Thank you. Flerda! I have asked this question in https://github.com/ankidroid/Anki-Android/issues but I could not any proper answer.

Timrae! Yes, I use TTS and it only read the answer. I went to Setting but there is not any Advanced option! maybe it is because my cellphone is different: LG-E405, android version 2.3.6

So, what should I do? Thank you very much.

**Comment by eginhard** [comment]
It's in the settings within AnkiDroid.

**Comment by tesoke** [comment]
Thank you, I got it. And after open again a deck, when Ankidroid showed the question part of a card, it did not asked me to choose the language! So, I touched the Show Answer and after showing answer, Ankidroid wanted me to opt language. I did it and Ankidroid only read the answer part again and not the question part :( I want to have the pronunciation of question part not answer part.

**Comment by timrae** [comment]
Try uninstalling and reinstalling. If that doesn't work then it's probably an issue with your device; not much we can do sorry.
