### ISSUE TITLE
I would like to buy a custom version

### ISSUE THREAD

**Issue by ManuelAcas** [ankidroid/Anki-Android#4010]
I would like to buy a custom version, and sync to my web. It is posible? some developer could it?
Thanks

**Comment by timrae** [comment]
Sure, it depends on the requirements and the amount of money but I am always open to bounties

**Comment by timrae** [comment]
Please specify exactly what your requirements are. Feel free to email me if you want to talk in private: perceptualchaos2 at gmail

**Comment by ManuelAcas** [comment]
The basic is a website for database uploading and syncs. 

Then a custom ankidroid. 

It will be to use for make examens

I will check box for chapter 1, chapter 2... and I will read questións for chapter 1, chapter 2... The questión will be ranked according to successes and failures
Statistics should be shown, % fail of charter 1, ...

I think it is basic, then could gradually implementing improvements

I do not know very good github but I think could to be made a private project here.

**Comment by timrae** [comment]
This isn't within the scope of the AnkiDroid project so let's discuss offline
