### ISSUE TITLE
options group - changing requires two attempts

### ISSUE THREAD

**Issue by HairyPhil** [ankidroid/Anki-Android#4011]
Reproducable: I have two option groups, Default and MyGroup. I open the settings for a Default deck, change the option group to MyGroup, the dialogue closes, but the group is still Default. I immediately repeat the process and this time MyGroup is selected correctly.

AnkiDroid 2.5.4 on Android 6.0.1 on Nexus 5.

**Comment by timrae** [comment]
@HairyPhil I can't reproduce this. Can you try running "check database" from the overflow menu in the deck list?

**Comment by HairyPhil** [comment]
Well that was easy. Check database fixed it, working as normal now. Should have done that first, sorry.

**Comment by timrae** [comment]
No problem  :)
