### ISSUE TITLE
Braces/curly brackets not displaying correctly

### ISSUE THREAD

**Issue by lukeaus** [ankidroid/Anki-Android#4013]
The format for a Django template variable looks like this

{{ some_value }}

In Anki on OSX the formatting is fine
{{ some_value }}

on AnkiDroid however the formatting is:
{ unknown field  some_value }

**Comment by timrae** [comment]
I think you're mistaken, it doesn't work on Anki Desktop either.

![unknown](https://cloud.githubusercontent.com/assets/2818274/11963287/30ccfb2a-a929-11e5-8849-4f0b2dd22ae1.png)

**Comment by lukeaus** [comment]
Apologies - you are correct. I have never reviewed cards on Anki desktop. The text shows up fine in the editing window (which I was referring to) and in the card Browser , but neither AnkiDroid nor Anki desktop display them correctly.

Ill put this in as a feature/bug request over at Anki desktop.

Thanks

**Comment by timrae** [comment]
AFAIK it's working as intended. I'm pretty sure there's something in the manual about this, and there's a way to change from curly braces to another character.

**Comment by lukeaus** [comment]
Ill check it out - thanks

**Comment by lukeaus** [comment]
Hi @timrae I spent a while looking through the docs and playing around with settings and card templates but I have been unable to find anything in the manual about this.

I found these:
http://markmail.org/message/w3ogckvkid4oeluh#query:+page:1+mid:w3ogckvkid4oeluh+state:results
https://www.reddit.com/r/Anki/comments/3iuoao/anki_double_curly_braces_question/
however the advice is to go from
{{ some text }}
to
{ { some text }}
or 
{*{ some text }}
which is not quite ideal

I can also edit the html and do
{<span></span>{ some_text }}
which is a little nice but still a little bit of work.

Any ideas where on anki I can change curly braces to another character?

**Comment by hssm** [comment]
http://ankisrs.net/docs/manual.html#latex-conflicts

**Comment by lukeaus** [comment]
@hssm I am a bit confused.

For clarity: I am not currently using LaTex, nor do I have LaTex installed.

Is there a way to change the default field characters that Anki uses {{ }} ?

Or are you suggesting that I have to install LaTex then convert all existing notes over to LaTex templates?

**Comment by hssm** [comment]
Please try to actually read the link. It's a very short bit of text.

>While this most commonly occurs with LaTeX, the solution presented here will work in any situation where you need to include {{ }} on cards, regardless of whether LaTeX is used or not.

As the example shows you, if you put `{{=<% %>=}}` in your template, you can use `<% %>` instead of `{{ }}`.

**Comment by lukeaus** [comment]
@hssm I did read it, but it wasn't clear to me:
1. Because I don't have latex installed and it refers to a latex field
2. I thought the docs were suggesting substituting <%  %> in this  {{=<% %>=}} for <%latex field%> 
3. general confusion as to what was meant to go onto the card and what was meant to go on the template
> While this most commonly occurs with LaTeX, the solution presented here will work in any situation where you need to include {{ }} on cards, regardless of whether LaTeX is used or not.
where I was trying to put: {{=<% %>=}} on the card, which was doing nothing obviously.


Your short explanation made much more sense!
Thanks!
