### ISSUE TITLE
Show tags down bottom of each card

### ISSUE THREAD

**Issue by lukeaus** [ankidroid/Anki-Android#4014]
It would be great if you could have the tags for each card showing in a list down the bottom of each card.

A good use case for this is if you have a Deck called 'Programming Languages'

your question could be the same:
how do you declare a variable?

But your answer will be different depending on what the language is.

I tag the cards with a language tag on Anki (OSX version) but I am unable to see the tag on AnkiDroid without editing the card.

It would be great if down the bottom of each card you could show the list of tags.

This might be good to have as a per Deck setting.

Thanks

**Comment by timrae** [comment]
Just add `{{Tags}}` to the card template

**Comment by lukeaus** [comment]
Excellent - I did not realise that was a feature - thanks @timrae

**Comment by andrewsanchez** [comment]
Is there a way to only display tags up to, but not including the last tag?  For example, if my card is tagged "HIV AIDS micro" I only want it to display HIV AIDS and not genevo?  Is there some sort of index slicing that is possible?  It would also be nice if the tags could be displayed separated by commas.  That would be awesome.

**Comment by timrae** [comment]
You can probably access the tags with javascript as you can with ordinary
fields. Search around on the forum as Flavio recently posted some nice
instructions for doing that (with fields).

**Comment by jgscherber** [comment]
In case someone is looking to split their tags up with commas, here's a small script I wrote to do it

1. Wrap your tags in a span with ID "tags"
```html
<span id="tags">{{Tags}}</span>
```
2. Add the below script
```javascript
<script>
var elem = document.getElementById("tags");
var content = elem.innerHTML;
var tags = content.split(" ");
var newContent = tags.join(", ");
elem.innerHTML = newContent;
</script>
