### ISSUE TITLE
Cards randomly marked as Suspended, Marked or Leech

### ISSUE THREAD

**Issue by lukeaus** [ankidroid/Anki-Android#4015]
I have noticed that randomly cards will be marked as Suspended, Marked or Leech using AnkiDroid by simply answering the card.

e.g. on occasion clicking on '1d GOOD' will mark the card as Suspended/Marked/Leech.

It appears to happen randomly. The occurrence rate is approximately once per 1000 cards.

I have not noticed any pattern as to when this happens.

I am currently using a Samsung Galaxy S5 and using AnkiDroid 2.5.4 - however I believe this problem has been going on for at least 6 months, perhaps even longer.

**Comment by timrae** [comment]
Do you observe the same behavior with Anki Desktop? Also, are you familiar with what is [supposed to happen (according to the manual)](http://ankisrs.net/docs/manual.html#leeches)?

**Comment by lukeaus** [comment]
Ohh ok...thats a feature!
