### ISSUE TITLE
Where is repository of apps using Ankidroid API?

### ISSUE THREAD

**Issue by vi** [ankidroid/Anki-Android#4016]
There is [doc](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API) describing how to add cards programatically, also [a sample](https://github.com/ankidroid/apisample).

Where can I find apps that use this API? Is there some repository like with shared decks?

I want an app that imports cards from CSV file to AnkiDroid and before trying to implement it I want to ensure that there isn't already such app.

**Comment by eginhard** [comment]
I'm not aware of an app for that use case. We should definitely add apps using the API to that wiki page.

**Comment by vi** [comment]
OK. I'm going to try implementing an importer from the same semicolon-separated files as in desktop Anki.

**Comment by timrae** [comment]
> I want an app that imports cards from CSV file to AnkiDroid and before trying to implement it I want to ensure that there isn't already such app.

In general we are in favor of eventually supporting all of the same functionality as Anki Dekstop, so would happily accept a patch that adds this ability to AnkiDroid (no need to use the API). See also #3517

Currently the only app that I'm aware of that uses the card addition API is Aedict, but I started a list on that [wiki page](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API#list-of-apps-that-support-the-instant-add-api).
