### ISSUE TITLE
"No text-to-speech language available"

### ISSUE THREAD

**Issue by tesoke** [ankidroid/Anki-Android#4017]
I run again Ankidroid on my cellphone, but I read a deck, it show this error: "No text-to-speech language available". What is this and what should do? Thanks.

**Comment by eginhard** [comment]
It means you don't have TTS enabled on your device or there's no TTS for the language you selected or something similar.

**Comment by tesoke** [comment]
Thank you. I think I have selected another language instead of English. How can I change it into English?

**Comment by timrae** [comment]
You have to do reset languages again from advanced settings, or reinstall
if that doesn't work.

Please stop asking us for support on this feature; it's an advanced feature
that we provide for advanced users. We already explained to you how to use
it, and don't have time to provide further support, especially for Android
2.3.

**Comment by tesoke** [comment]
Ok, thank you. I will try to navigate for another forum to get help. Thanks
anyway.

**Comment by timrae** [comment]
It's not an issue of which forum you're using, it's an issue with the way you are asking the question.

You previously asked two questions on user forum about the same feature:
* [first question](https://groups.google.com/d/topic/anki-android/xkKaQopo7Sk/discussion)
* [second question](https://groups.google.com/d/topic/anki-android/j2XgP8JSfBM/discussion)

Even after we answered your question, you keep asking us the same question, without showing any effort to try things on your own, or do some research on your own using Google.

We don't have time to answer any more of your questions on this feature either here on github, nor on the user forum. Thank you for your understanding.

**Comment by tesoke** [comment]
Thank you.

**Comment by hotfair** [comment]
Hello, I'm a Chinese user of Anki android version, I have a problem with TTS,  I use Anki to memorize English  vocabulary, I have installed google TTS for making it can pronounce the word when I memorize the words. After I set the Google TTS as the main TTS engine It works, but it not works very well.  When I start to use Anki again, there is a message shows in the Anki, "No text-to-speech language available", all I have to do is that I set Google TTS as the main TTS engine  again, and after that the problem will come back again after several minus, so I have to do the setting again and again. is there anyone has the same problem as mine? what should I do to solve the problem? many thanks

**Comment by mikehardy** [comment]
@hotfair this issue is closed and has been for more than 2 years. Please open a new issue and follow the bug template provided such that we know versions of Android and AnkiDroid, and exact steps to reproduce. If we can reproduce it in a new issue then we will keep it open and look for a solution. Additionally, it may be useful to try the user support forum first to see if anyone else is experiencing it, before even opening a new report - more instructions are here https://docs.ankidroid.org/help.html
