### ISSUE TITLE
Newly installed AnkiDroid crashes

### ISSUE THREAD

**Issue by WildAngel365** [ankidroid/Anki-Android#4019]
Hi,

I just got a new phone (Doogee X5 running android 5.1) and downloaded AnkiDroid 2.5.4 onto it from the Play store. 

When I first opened the app, it let me log on and seemed to be synching, but when I went back later it crashed on opening and has crashed on opening ever since. I have uninstalled it and reinstalled it several times, even deleting all anki related data from my phone. This has not worked.

On opening the app, a small grey box appears saying "AnkiDroid has encountered a problem; a report is being sent to the developers..." Then the main app opens with a big white error box saying "collection not opened". I have tried all the options given: 'Retry opening' just brings up the same error message, 'restore from backup' doesn't do anything as there is no backup on the phone to restore from, 'Full sync from server' brings up the same little grey box and crashes out of the app altogether, 'delete collection and create new one' just seems to make the app hang with the little spinning circle timer thing going round and round.

Anki on my desktop still works fine and I have been able to sync it with no problems, so it must be a problem with AnkiDroid and not my decks.

Here is what the debug info says:

AnkiDroid Version = 2.5.4

Android Version = 5.1

ACRA UUID = 72f41c2f-55b8-4a29-a067-7c1a755979bd

Please let me know if there's a way to fix this

Edit -

Have just tried an APK install of version 2.5beta16

Has the same problems, although I did notice something flash up briefly about not being able to connect to the database, I can't seem to get that message up again though

ACRA UUID = 93cfda89-bbc9-4948-b2c0-20c25ec1ce6f

Maybe someone who knows how to use this site could see if this one was investigated before for the beta version, I couldn't find a way to search for these UUIDs

**Comment by timrae** [comment]
Hi thanks for the nice error report! I had a look at the crash report logs, and it appears that there is some kind of permission problem... AnkiDroid can't write to the AnkiDroid directory for some reason. Can you try deleting the AnkiDroid directory and restarting AnkiDroid?

```
com.ichi2.anki.exception.StorageAccessException: Failed to create .nomedia file
at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:184)
at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:188)
```

**Comment by WildAngel365** [comment]
Aha! It was a problem with the sd card. It wasn't readable. I took it out and put it back in then deleted the AnkiDroid folder like you said. AnkiDroid now working fine. If I have any further problems I'll know what to look at. Thanks very much for your help :-)

**Comment by timrae** [comment]
Thanks for the follow-up. We strongly recommend using the internal memory where possible as SD cards can be quite unreliable.
