### ISSUE TITLE
Allow users to add an image to a new note via "share" intent from 3rd party app

### ISSUE THREAD

**Issue by Agireso** [ankidroid/Anki-Android#4021]
Hello. first of all . thank you for anki, is one of most awesome apps that I have had. 
second can you add anki to this menu

http://i.imgur.com/8iX2WWW.png

is the menu after click sharing an image ... then the image could be add to anverso of a main deck.

another feacture that you could do that will help me a lot is paste image from clipboard... I can just paste text from anverso o reverso.

http://i.imgur.com/jgpSB3b.png

If I would have an image an a clipboard just hold the finger and paste,for now I will have to search the image from my galery and that i'ts so slow because the image may no appear quickly and I have to search for a long time

Thanks a lot .

**Comment by david-allison-1** [comment]
I'd like to take this on at an undefined point in the future.

**Comment by cristianvasquez** [comment]
Hello, 

To add images and screenshots is an important feature. 
There is a system of bounties to add functionality to Anki?

**Comment by mikehardy** [comment]
https://github.com/ankidroid/Anki-Android/wiki/Contributing indicates how to tie bounties to specific issues, also we have an OpenCollective now (https://opencollective.com/ankidroid) - if you coordinated with a developer / developers here on amounts and made the contribution with an agreement I could facilitate the payment (I am able to approve / pay open collective ankidroid payments)

**Comment by Akshay0701** [comment]
I would like to work on this issue ,
I will refer this site to implement receiving data from different app  
https://developer.android.com/training/sharing/receive

**Comment by mrudultora** [comment]
@Akshay0701 You are working on another issue so would you mind if I take this up ?

**Comment by Akshay0701** [comment]
Sure ,no issue

**Comment by david-allison-1** [comment]
I'd like to see this, it should be a lot easier to implement now we handle image copy/paste
