### ISSUE TITLE
Takes extremely long time to sync now

### ISSUE THREAD

**Issue by homerdough** [ankidroid/Anki-Android#4023]
I've been using this app for over a year now and it used to only sync all the cards on the very first startup of the app. But now, whenever I sync, it will not sync just the recently answered cards, it will go through literally every card and try to upload them all, which takes a very long time since most of them are media files. This makes the app downright unusable now and I don't know why this happened

**Comment by hssm** [comment]
It sounds like you're using the desktop client, because
>it used to only sync all the cards on the very first startup of the app

...is actually a new feature in AnkiDroid, and you have to explicitly enable it. If that's the case, you should ask on the [desktop support site](https://anki.tenderapp.com) and not here.

**Comment by homerdough** [comment]
It seems like unchecking the "fetch media on sync" option fixed it, but I
still don't know why it considers that I have "missing media" every single
time I sync it.

**Comment by timrae** [comment]
Try running "check media database"
