### ISSUE TITLE
Reset text-to-speech settings by deck (Bug / Request)

### ISSUE THREAD

**Issue by arooooon** [ankidroid/Anki-Android#4029]
Go to preferences>>Advanced>> Reset languages:
"Reset language assignments (for text to speech and dictionaries) for all decks. *Reset specific deck assignments on deck picker*"

I cannot find anywhere a button for resetting a specific deck!

Overall I think TTS could be better managed than it is now. It seems like AnkiDroid will ask what TTS voice I want each time a different cardside, deck and notetype comes up. Often this language selection screen comes up just when you have forgotten about it and you accidentally press French. Either you live with it or you reset ALL the tts settings and pray that you will not press French again when a new deck, front-card, back-card, reversed-note type, other note type comes up.

EDIT:

My suggestion would be to add another entry in the reviewer settings menu (Hide/ Delete, Enable whiteboard, Deck option, SELECT TTS) that would ofc only be visible if TTS was on.
This would let you choose both front and back settings for the current card's notetype and deck combination.

If you think this is a good idea I would happily implement this myself, but I would need some guidance since I am new to big projects.

**Comment by eginhard** [comment]
We could show an option on long-pressing on a deck in the deck list when TTS is enabled to reset the languages for that deck.

**Comment by arooooon** [comment]
Yes that would be good, but I think it would be great to be able reset specific card-notetypes as well.

Can I do this these changes? Will my pull request be considered? :)

**Comment by timrae** [comment]
Yes that sounds like a reasonable solution, please submit a PR

**Comment by timrae** [comment]
As far as I remember, TTS is set on a per deck basis; it's not related note type. Adding a menu entry somewhere to reset the TTS language for a specific deck is a good idea, but any other changes would need to be discussed separately

**Comment by arooooon** [comment]
Hmm it seems you are right about note types. I just started poking around in the source code and testing TTS.

```java
    /**
     * Associates a language to a deck, model, and card model for a given type.
     * 
     * @param qa the part of the card for which to store the association, {@link #LANGUAGES_QA_QUESTION},
     *            {@link #LANGUAGES_QA_ANSWER}, or {@link #LANGUAGES_QA_UNDEFINED}
     * @param language the language to associate, as a two-characters, lowercase string
     */
    public static void storeLanguage(Context context, long did, int ord, int qa, String language) {
        openDBIfClosed(context);
        try {
            mMetaDb.execSQL("INSERT INTO languages (did, ord, qa, language) " + " VALUES (?, ?, ?, ?);", new Object[] {
                    did, ord, qa, language });
```




There is indeed an unused method for resetting a specific deck in MetaDB:
mMetaDb.execSQL("DELETE FROM languages WHERE did = " + did + ";");

**Comment by timrae** [comment]
Yeah, I recommend using what we already have as a starting point and submitting a PR, then if you later find that to be too limiting for a given workflow we can discuss other possibilities.

**Comment by eginhard** [comment]
Now available in 2.6alpha6

**Comment by kabutar111** [comment]
It's not there, same behavior as play store version. 
Urgent help needed

**Comment by kabutar111** [comment]
Nevermind I found it, however showing the option on long pressing on deck view is more logical and natural
