### ISSUE TITLE
Crashes at 31384kb when downloading collection, and subsequently crashes whenever opening

### ISSUE THREAD

**Issue by carlseverson** [ankidroid/Anki-Android#4031]
Hi, 

Moto X
Android version: 5.1
Ankidroid version: 2.5.4

After installing ankdrioid it works perfectly. However, when I login and begin syncing my collection from ankiweb, the app crashes. It always crashes at 31384kb moments after the sync dialogue displays "checking downloaded file" (or something similar to that effect). After that crash, the app crashes as soon as it opens. This happens even after a fresh install. 

I have ran the "check database" and "check media" tools via the desktop app and synced them to ankiweb. 

I am unable to copy the debug info from the app (when getting it via settings -> advanced -> about) because the app crashes. 

I am not sure if it is an issue with my collection, or with the app. Any help would be appreciated. \

Thank you,
Carl

**Comment by timrae** [comment]
Does Anki desktop sync OK? 

> I am unable to copy the debug info from the app (when getting it via settings -> advanced -> about) because the app crashes.

Do you mean you're reporting two unrelated crashes? At what point does it crash when trying to get the debug info?

**Comment by carlseverson** [comment]
Anki desktop syncs with no issues. 

No, I am not reporting two unrelated crashes... it is late, and I didn't write clearly. What I was trying to say is that the app first crashes when downloading the collection (when it gets to 31384kb downloaded), after that, the app crashes when opening it. Because the app crashes when opening, I am unable to get at the debug info, and can't include the debug info here. 

Carl

**Comment by timrae** [comment]
Does it literally crash or does it so you an error dialog with restore options?

**Comment by timrae** [comment]
If it literally crashes then please try the [latest 2.6 alpha](https://github.com/ankidroid/Anki-Android/releases). If not, you should be able to restore from backup or delete the old collection file which will let you open the app and give us the debug info.

**Comment by carlseverson** [comment]
Thanks timrae, 

Here are some screenshots of what it gives me. I am calling these crashes. 
![screenshot_2016-01-03-02-12-14](https://cloud.githubusercontent.com/assets/822270/12078081/dd6557f2-b1c0-11e5-82d7-566fa844fc4f.png)
![screenshot_2016-01-03-02-11-17](https://cloud.githubusercontent.com/assets/822270/12078082/dee665bc-b1c0-11e5-837c-cf0eb4fa8adf.png)

Unfortunately I have similar issues with the 2.6 alpha. With v2.6 it doesn't crash when opening the app after the first sync and crash... instead it gives me the error dialog. However, I have tried all of the options and nothing seems to help.  

Here is the debug info. 

AnkiDroid Version = 2.5.4
Android Version = 5.1
ACRA UUID = 2f1742e7-af2c-4b35-ab40-0a71918b640a

AnkiDroid Version = 2.6alpha3
Android Version = 5.1
ACRA UUID = dfd49a12-332f-4326-a132-713a486d9dde

**Comment by timrae** [comment]
Have you tried the create new collection (i.e. delete old collection) option?

**Comment by carlseverson** [comment]
Yes. After deleting the old collection the app functions properly. However, if I go to sync my collection from anki web I run into the same issue. 

Right now I am trying to manually load the collection from my computer to ankidroid to see if that works. 

Carl

**Comment by timrae** [comment]
Can you create a new profile on Anki desktop, and sync it with AnkiWeb please? Does that work fine with Anki Desktop? Can you export the collection as an apkg file and email it to me? perceptualchaos2 at gmail

**Comment by carlseverson** [comment]
Sure... do you want me to try and sync my existing collection with the new profile, or do you want to me start with a blank collection?

**Comment by timrae** [comment]
Create a new empty profile with a blank collection, then sync with AnkiWeb. It will automatically do a full sync to your profile and give me a copy of exactly what is on AnkiWeb so that I can try to reproduce the problem.

**Comment by carlseverson** [comment]
With a new profile and blank collection I am having no issues. ... do you want me to email you the .apkg of the new profile??

**Comment by timrae** [comment]
Huh, blank collection? Didn't you sync with AnkiWeb?

**Comment by carlseverson** [comment]
Yes. ... I think there was a bit of a communication breakdown. You told me to "Create a new empty profile with a blank collection, then sync with AnkiWeb." 

I am assuming you want me to sync my old collection with the new profile, correct?

**Comment by timrae** [comment]
I want you to press the sync button in Anki Desktop after creating a new profile. 

There are several different versions of your collection on PC, Android, and Web so it doesn't make sense to talk about your "old collection" as I have no idea what you're referring to.

**Comment by carlseverson** [comment]
By old collection I mean the collection associated with old profile. 

I created a new profile (in which there are no cards and only the default deck). Synced it to ankiweb from the desktop client. 

Done, and done. 

What do you want next?

**Comment by timrae** [comment]
Thanks, now if that's working without issue please export to apkg and email it to me

**Comment by timrae** [comment]
> By old collection I mean the collection associated with old profile.

The collection in your old profile (on Anki desktop) will in general not be the same as the collection on AnkiWeb unless they are 100% in sync, so the answer to that question is no. I just want the version of the collection that's on AnkiWeb, which is what you'll be emailing to me.

**Comment by timrae** [comment]
I finally tracked the issue down to being due to an [undocumented 2MB limit](http://stackoverflow.com/questions/21432556/android-java-lang-illegalstateexception-couldnt-read-row-0-col-0-from-cursorw﻿) on the size of a database cursor in Android. Your models take up more than 1MB of space and thus cause AnkiDroid to crash.

Please update to version 2.6alpha4, and follow the instructions there (to delete your unused note types with Anki desktop), which will fix the issue for you.
