### ISSUE TITLE
The manual page doesn't open within AnkiDroid

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4032]
When "Help" on the navigation drawer is tapped,
the manual page doesn't open within AnkiDroid, but it opens by the default browser of Android (ex. Chrome, Firefox) like old versions.
The same goes for the support page.

Is it intentional?

**Comment by timrae** [comment]
> Is it intentional?

Yes

**Comment by snowtimeglass** [comment]
I feel the system in which the pages open within AnkiDroid was very cool.
Why is it abolished?

**Comment by timrae** [comment]
Which version of AnkiDroid are you talking about?

**Comment by snowtimeglass** [comment]
The version is, for example, v2.5.4.

**Comment by timrae** [comment]
No I mean which version are you saying it worked differently from how it works now?

**Comment by snowtimeglass** [comment]
2.5.4 worked differently from the newest version  (2.6alpha3).
On 2.5.4, the manual page opens within AnkiDroid.

The next version (2.6alpha1) worked like the newest version (2.6alpha3).

**Comment by timrae** [comment]
Ah I see, this was actually unintended, there was a merge problem. Technically it doesn't open inside AnkiDroid, it just uses a new library API called [chrome custom tabs](https://developer.chrome.com/multidevice/android/customtabs). I'll fix it in the next version

**Comment by timrae** [comment]
By the way, in the future, it's a lot easier to understand if you provide side by side screenshots of the two different versions when you think there has been a regression. Thanks for reporting though.

**Comment by snowtimeglass** [comment]
Certainly. Haste makes waste. 
Thank you for the fix.
