### ISSUE TITLE
Hang-Problem in NavigationDrawerActivity

### ISSUE THREAD

**Issue by brok85** [ankidroid/Anki-Android#4038]
Dear AnkiDroid Developers,
I am implementing a hang-bug detection tool and I am analyzing AnkiDroid with it. I found that the main thread of AnkiDroid, frequently calls

android.graphics.BitmapFactory.decodeStream

after the opening of a deck. In particular, the above API is called as consequence of executing 

com.ichi2.anki.NavigationDrawerActivity.initNavigationDrawer(NavigationDrawerActivity.java:111)

that calls

com.mikepenz.materialdrawer.holder.ImageHolder.applyTo(ImageHolder.java:106)

then

android.support.v7.widget.AppCompatImageView.setImageResource 

and 

android.graphics.BitmapFactory.decodeStream

at the very end. The Android documentation states, the decode* functions should not be executed on the UI thread. As a result, moving the execution of the BitmapFactory.decodeStream(...); off the main thread leads to higher responsiveness of the app.

Do you think that moving the decodeStream call off the main thread (for example by moving initNavigationDrawer in an AsyncTask) would be a valuable solution for improving AnkiDroid responsiveness?

Thanks for any information,
I hope I can help improve AnkiDroid.

**Comment by timrae** [comment]
Hi, in the current 2.6 alpha version we no longer use this 3rd party
library; does the problem still occur?

**Comment by brok85** [comment]
I analyzed the master version downloaded from github today. It should be
the latest one no?

**Comment by timrae** [comment]
The master branch contains the code in the latest released version of the
app. The develop branch contains the latest development code. See the
development wiki for more info on the branching model

**Comment by brok85** [comment]
Hi,
so I have downloaded and analyzed the development version

android:versionCode="20600104"
android:versionName="2.6alpha4"

but the problem seems to persist. Indeed, the call to 

android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:609)

on the main thread is done by 

com.ichi2.anki.AbstractFlashcardViewer.onCreate(AbstractFlashcardViewer.java:844)

in your code. 

Where you aware of also this call to that heavy API in your main thread?
Are you planning to fix also this one to further improve the responsiveness of your app?

Thanks a lot for the feedback. I hope I can help improving AnkiDroid.

**Comment by timrae** [comment]
Line 844 in AbstractFlashcardViewer is just `setContentView(R.layout.flashcard)` which draws the main layout. This isn't something we could or would want to call on a background thread...

**Comment by brok85** [comment]
yes that is true, you can not move setContentView in a background thread. The strange thing however is that this API is very common in apps, but usually it does not take more than few milliseconds to execute. In my tests, I saw that whenever that API is called in AnkiDroid the app becomes unresponsive for about 0.5 seconds, which is much longer than usual. Do you have any idea about the reason behind this undesired behavior?

**Comment by timrae** [comment]
> In my tests, I saw that whenever that API is called in AnkiDroid the app becomes unresponsive for about 0.5 seconds

Are you talking about in the reviewer (which uses a Webview) or in every activity?

**Comment by brok85** [comment]
well so far I saw that behavior when setContentView is called in DeckPicker (line 376) and in the AbstractFlashcardViewer as mentioned before.

**Comment by timrae** [comment]
How about NoteEditor and CardBrowser? I guess the header image in the navigation drawer could be the slowest to draw, so you could start by removing that and seeing what happens.

**Comment by brok85** [comment]
No, NoteEditor and CardBrowser do not show such problem. However I agree that it is probably related to the rendering of some image. Maybe changing them would solve the problem.

**Comment by timrae** [comment]
CardBrowser has the same navigation drawer image as DeckPicker, so that's probably not the issue. Probably DeckPicker is getting slowed down when opening the collection, and Reviewer is getting slowed down when rendering the WebView and its content. 

There isn't really anything we can do about either of these.
