### ISSUE TITLE
Full screen mode leaves large unused space below Answer buttons

### ISSUE THREAD

**Issue by lizzgilmore** [ankidroid/Anki-Android#4042]
On v2.6alpha4:

![screenshot_20160105-073333](https://cloud.githubusercontent.com/assets/13272950/12115293/f8e60462-b37e-11e5-9d1a-09a4c14c8a95.png)
^ Notice the white space below Show Answer. Notice the bar at the top of the screen (blue) is also not hidden.
![screenshot_20160105-073403](https://cloud.githubusercontent.com/assets/13272950/12115298/fef05db2-b37e-11e5-8388-d13549fbfb36.png)
![screenshot_20160104-205754](https://cloud.githubusercontent.com/assets/13272950/12115304/08a9651a-b37f-11e5-8fca-81de9359444c.png)

Debug info:
AnkiDroid Version = 2.6alpha4

Android Version = 6.0.1

ACRA UUID = 958af048-4c94-4a95-845f-b6ff5ba2150c

**Comment by timrae** [comment]
Yes as written in the release notes I'm waiting to see if a patch from Google will come before trying to fix this

**Comment by lizzgilmore** [comment]
Ahhh, sorry - I see now that was mentioned on the github releases page for
2.6alpha1. Clearly I was taking an Anki break over winter holidays and
missed testing a couple versions. Thanks, sorry again!

**Comment by timrae** [comment]
No problem, thanks a lot for all of your help on the message board!
