### ISSUE TITLE
Learn across multiple decks

### ISSUE THREAD

**Issue by jjh42** [ankidroid/Anki-Android#4044]
Hi,

I'm using AnkiDroid (which is fantastic btw) to learn from several different unrelated decks. But right now I have to consciously decide which deck to learn from and switch between them.

I would be really nice if there was a mode where you could say "I'd like to learn across all of these 3 decks" and it would sample between them. I don't think you can just merge the decks since they might have different settings in each deck (e.g. are the cards double side etc).

Maybe this feature already exists and I just missed it?

**Comment by hssm** [comment]
You need to create a [filtered deck](http://ankisrs.net/docs/manual.html#creating-manually) and make use of the `deck:"my deck"` [search syntax](http://ankisrs.net/docs/manual.html#searching) to refer to the decks you want to pull cards from.
