### ISSUE TITLE
Text Background in Context Menu too dark in Day Mode

### ISSUE THREAD

**Issue by aphirst** [ankidroid/Anki-Android#4046]
AnkiDroid version 2.5.4 from F-Droid
Android version 5.1.1, CyanogenMod 12.1 20160106

tl;dr:
![Day mode is broken](http://a.pomf.cat/wxvywl.jpg) ![Night mode works](http://a.pomf.cat/guorpb.jpg)

Basically the text background is too dark in the Day Mode, making the text almost unreadable (especially on low brightness).

I'll provide this, even though there was no associated crash.
ACRA UUID = 37786533-5959-4a55-9af7-f0b9368b8bbf

If there's any additional information I should submit, let me know.

**Comment by hssm** [comment]
Release 2.5.4 had a fix for this issue. Are you 100% sure that the version you are running is 2.5.4? Check in Settings -> Advanced -> About. I can see that F-Droid has this release but are you sure you updated it?

**Comment by timrae** [comment]
Yeah that's exactly the symptoms of v2.5.3. Maybe try reinstalling from here:
https://github.com/ankidroid/Anki-Android/releases/tag/v2.5.4

If that doesn't work it's probably an issue with your ROM as nobody else has reported an issue with 2.5.4, so please try on a stock device.

**Comment by aphirst** [comment]
@hssm AnkiDroid insists that it's 2.5.4, and F-Droid insists that I have that version installed.

@timrae I'll try that a bit later, but at first glance it seems that that APK is the same size as the 2.5.4 one from F-Droid.

In the meantime, I'll get in touch with some other F-Droid users, and some other users of the ROM I'm on, and see whether anyone else can reproduce.

**Comment by timrae** [comment]
You'd be surprised the number of times an uninstall > reboot > reinstall has fixed a mystery issue like this

**Comment by aphirst** [comment]
@timrae Well I uninstalled the F-Droid build and sideloaded the build from the Github releases page, and that one worked! Seems as if there's something fishy about the F-Droid build. I'll let them know that as well, while I see if anyone in their IRC channel is able to test.

**Comment by timrae** [comment]
I'd recommend trying to uninstall and reinstall in F-Droid to check that before reporting an issue

**Comment by aphirst** [comment]
I was in the middle of checking that just then after I read what you suggested...

And I can confirm that with-or-without a reboot inbetween, an uninstall-then-reinstall of the F-Droid build still exhibits the issue.

**Comment by timrae** [comment]
Curiouser and curiouser...
Thanks for the follow up

**Comment by timrae** [comment]
I just checked and the build number on github/play is 20504301... It's possible (I don't recall very well) that I messed up the build of 20504300 such that it still exhibits the issue, and that's the one they're using.

Actually I have no idea how the F-Droid build gets there... @nicolas-raoul do you manually put it up there?

**Comment by nicolas-raoul** [comment]
F-Droid builds automatically using a "recipe"

**Comment by mvdan** [comment]
We built the `v2.5.4` tag with gradle.

**Comment by krt16s** [comment]
A clean checkout of v2.5.4 tag and building with plain gradle (no fdroid stuff involved) results in this issue. Building from 4f467f30b486a0191ffb12b9661fa1e1235196eb seems to be good. Most likely 1926fcc7d86d85cbc068234bc565b9f607b8e45f is good, as well, so it looks like a mis-tagged release.

**Comment by krt16s** [comment]
Indeed, 1926fcc is the correct commit. I'd recommend removing the current v2.5.4 tag and re-tag the correct commit.

**Comment by timrae** [comment]
Done, thanks

https://github.com/ankidroid/Anki-Android/releases/tag/v2.5.4
