### ISSUE TITLE
Font not displaying some Latin characters with diacritics

### ISSUE THREAD

**Issue by Yendis9** [ankidroid/Anki-Android#4048]
I am trying to set up AnkiDroid for studying Persian. On my Anki PC version I am using arial fonts.

When transliterating Persian characters, some characters have diacritical marks. For example:
ظـ = ż 
The Persian character za is represented by z with a dot over it.
This works well in the PC anki.

In  AnkiDroid, the z with a dot over it (ż) does not display at all on the card. It does display in the editor. 

However other characters with diacritics do not display correctly in the editor or on the card. One example is the letter  ǫ (which represents the character غ). This is not a regular Q but rather character unicode 01EB (small letter O with Ogonek). The display for this character is distorted.

Changing fonts in the settings from system default to OpenSans-Regular results in a tofu box displaying (little empty square). With the system default, it displays blank.

So far, it appears to show the Persian characters correctly, but I have not really used it yet. Still trying to get it set up.

I hope this is not a big problem.

Android version 4.4.2
AnkiDroid 2.5.4

**Comment by hssm** [comment]
Please try another font. We recommend the [Google Noto fonts](https://www.google.com/get/noto/#/) since they are guaranteed to be supported by the Android browser engine.
