### ISSUE TITLE
random order not being respected?

### ISSUE THREAD

**Issue by zecoder** [ankidroid/Anki-Android#4053]
Today, I have seen cards in exactly the order added even though it was set to random in the deck's option. And, I have noticed in the past that I seem to study new cards in an order very similar, if not identical, to the order I added the notes. 

As a possible work around, I go into deck options, check that "random order" is selected (which it is), then I toggle by selecting "order added", let it reorder, then select "random order", let it reorder, and then go back to studying.

I am not 100% sure about this though, it just *seems* that way. I could be wrong.

**Comment by hssm** [comment]
We will need a reproducible test case.

**Comment by zecoder** [comment]
I will create one in the coming days, adding card pairs such as 

front back
1      one
2      two
... etc

then study in random while observing if the order is preserved after shuffling

**Comment by zecoder** [comment]
Ugh, shoulda tested beforehand. Sorry for wasting your time.
