### ISSUE TITLE
Sync with file

### ISSUE THREAD

**Issue by MarcoSchicke** [ankidroid/Anki-Android#4054]
Sometimes my web connection is slow and instabile. And also (seldon) the Anki Webserver is down.
A option to sync the Anki Database with a file would be nice.
I also read on the google forum that a few people want to sync their Collection without saving it on the Anki server. They want to use a local Server, or just any cloud.
An other Open Source Programm makes it this way: http://keepass.info/ https://keepass2android.codeplex.com/
I don't know if its easy to realize and if you want to include such future.
But for me as a non developer I don't see any difficulties since all Entries have Date / Time Stamps. 
I guess on the exported collections now only the Information for deleted files is missing for a bidirectional syncing feature.
I think that it would be a big improvement for the Anki System.

**Comment by hssm** [comment]
You can already transfer your collection between the desktop client and AnkiDroid by exporting the collection and importing it on the other device. See [the manual](https://ankidroid.org/docs/manual.html#_exporting_collection_package).

Syncing directly to a running instance of Anki would require the desktop client to support that feature first, and there is little incentive to do so when the above technique already works.

**Comment by timrae** [comment]
By the way, setting a custom url for a personal sync server in AnkiDroid is
already supported in the latest alpha versions. The user dsnopes on github
has such a sync server working I believe
