### ISSUE TITLE
Ankidroid crashed after first start

### ISSUE THREAD

**Issue by Astronach** [ankidroid/Anki-Android#4057]
After install and start Ankidroid the first time. Anki crashed immediately.
A new clear install by delete App-Data and cache does not help 

Anki Version: 2.5.4
Android Version: 5.1.1

**Comment by hssm** [comment]
Can you tell us the device model you are using and the time that the crash happens so we can find it in our crash reports?

**Comment by Astronach** [comment]
The device model is "Samsung Galaxy S II GT-I9100".
Maybe the reason is the custom rom CyanogenMod 12.1 I use ?
I send a crash report right now : 20.01.2016 14:20

**Comment by hssm** [comment]
Sorry for the delay on this. I located the error report and it seems that there is no write access at the location where the AnkiDroid directory would get created. Do any of your other apps fail?

It's probably something to do with SD cards but I can't really say from the limited information.

(For reference, the ID is:  a795dc74-73de-4ba0-91d5-c13603cd7f03)

**Comment by Astronach** [comment]
Yes the no write access was the reason. No other apps fail because of this, but I format the internal sd to ext4 and reflash the rom and now it works. Thanks!
