### ISSUE TITLE
Question/Feature request

### ISSUE THREAD

**Issue by bogdanteleaga** [ankidroid/Anki-Android#4063]
Hello,

So I've been thinking about creating some apps/scripts that would use information from Anki(e.g. I'd want to make a wallpaper to display the new kanji's that I'm learning every day). I've seen there's an API for putting cards into Anki, but I didn't seem to be able to find anything to get information from Anki. Does something like this exist? If not, would it be hard to build?

Cheers,
Bogdan

**Comment by timrae** [comment]
Hi Bogdan,

Kind of, there are methods in the content provider for this but they're not documented yet. See the ankidroid wear app for an example on how to use them!

I hope one day someone creates some more high level methods and documentation, and adds them to the API, but it's probably not so attractive for developers to work on this kind of thing.
