### ISSUE TITLE
Double tap gesture set to mark doesn't work properly

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#4064]
Debug info:
AnkiDroid Version = 2.5.4
Android Version = 6.0.1
ACRA UUID = d0c1f412-96af-42b6-8f05-ee8257676e16

Steps to reproduce:

* Turn on gestures, disable all of them (set to 'None')
* Set 'Double touch' to 'Mark note'

When seeing a card, double tap.

Actual behavior: the 'marked' star doesn't change. However, when moved to another card and going back, the star does show the correct 'marked' status. There seems to be some minor issue with refreshing the 'star' when marking is triggered by double tap.

Expected behavior: the 'marked' start is updated to reflect the 'marked' status of the card.

**Comment by hssm** [comment]
https://github.com/ankidroid/Anki-Android/issues/4020
