### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by Inconditus** [ankidroid/Anki-Android#4066]
I have LaTeX image files in my deck, generated from the desktop Anki. They show correctly in AnkiWeb and in /sdcard/AnkiDroid/collection.media/. An example image filename: `latex-0dde2ac1b1b76eabeaacca1279a57fc4533c6d3a.png`.

Things I've tried to fix:
- Uninstall and reinstall app
- Force resync from server
- Change folder location
- Force stop and remove files, then resync

This may be because my phone is rooted, I was using an older version of AnkiDroid when I was not rooted and the images were working.

Phone: Nexus 6
Android: 6.0.1 (rooted)
AnkiDroid: tried 2.6alpha6, and 2.5.4.

**Comment by timrae** [comment]
I have a rooted Nexus 5x running 6.0.1, and latex image display fine. What happens if you try including the image directly using `<img>` tags? If that works, you might need to attach the debugger and step through the code to figure out where the problem is.

**Comment by gj12** [comment]
same problem here, images working on old rooted phone with AnkiDroid 2.4.3. Images not working on new tablet with AnkiDroid 2.6beta6. Same problem with csv & <img> tag. The decks where created with python version of anki(PC).

**Comment by timrae** [comment]
Not enough information for us to help you
