### ISSUE TITLE
how can i add new word to ankidroid from tasker?

### ISSUE THREAD

**Issue by seniorivn** [ankidroid/Anki-Android#4068]
What i want: i am using goldendict to translate words while i'm reading, so i want to add the history of goldendict translations to the anki. Am i need to create a normal app to use api, or i can use somehow public intent to add new word to ankidroid?

**Comment by timrae** [comment]
You should be able to just share the word directly from goldendic... Why do you want to use tasker?

**Comment by seniorivn** [comment]
@timrae i am just a beginner, so there are a lot words i need to train, i don't want to add them all by myself, i want to automate this case, every time i save history in goldendict, tasker will add all new words to the anki, and when i open anki i can just train words.

**Comment by timrae** [comment]
I see. This is not possible sorry, and it's not really feasible to implement in AnkiDroid. When using an intent you have to confirm adding each note. If you want to add cards to AnkiDroid without confirmation you need to use the API requires support to be added to the app.

You can either request the developer of your dictionary to add API support, create your own intermediary app, or switch to a different dictionary that supports the API (currently aedict3 is the only app that I'm personally aware of that supports it)

**Comment by seniorivn** [comment]
@timrae ok, thanks, maybe i'll create app for this.
