### ISSUE TITLE
Hang problem querying whiteboard status in the MetaDB from Reviewer

### ISSUE THREAD

**Issue by brok85** [ankidroid/Anki-Android#4082]
Hi,
I am analyzing ankiDroid version 2.6alpha4 with a hang-bug detection tool. I have found that the main thread executes database operations when calling 

com.ichi2.anki.MetaDB.upgradeDB(MetaDB.java:99)

thus leading to visible hang problems. Do you think that moving this function in a background thread could improve the responsiveness of AnkiDroid? Where you aware of this problem?

Hope to help improving AnkiDroid,
Thanks for any answer.

**Comment by timrae** [comment]
I believe that this is only executed while the splashscreen is shown (i.e. when the Collection is getting opened)...? If so, this is completely on purpose, you should be able to easily find more about it in the git log history for DeckPicker.java. If the "hang" occurs while the main UI is visible, could you please provide the full stack trace?

**Comment by brok85** [comment]
android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method),
android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:732),
android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:754),
 android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:64),
 android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1676),
 android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1605),
 com.ichi2.anki.MetaDB.upgradeDB(MetaDB.java:99),
 com.ichi2.anki.MetaDB.openDB(MetaDB.java:60),
 com.ichi2.anki.MetaDB.openDBIfClosed(MetaDB.java:112),
 com.ichi2.anki.MetaDB.getWhiteboardState(MetaDB.java:260),
 com.ichi2.anki.Reviewer.onCollectionLoaded(Reviewer.java:82),
 com.ichi2.anki.AnkiActivity.onLoadFinished(AnkiActivity.java:288),
 com.ichi2.anki.AnkiActivity.onLoadFinished(AnkiActivity.java:44), android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476),
android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
 android.support.v4.content.Loader.deliverResult(Loader.java:126),
 com.ichi2.async.CollectionLoader.deliverResult(CollectionLoader.java:43),
 com.ichi2.async.CollectionLoader.deliverResult(CollectionLoader.java:13),
android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:249)android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:77), 
 android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:466), 
 android.support.v4.content.ModernAsyncTask.access$400(ModernAsyncTask.java:48), 
android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:483), 
 android.os.Handler.dispatchMessage(Handler.java:102), android.os.Looper.loop(Looper.java:148), 
 android.app.ActivityThread.main(ActivityThread.java:5417), java.lang.reflect.Method.invoke(Native Method), 
 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726), 
 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by timrae** [comment]
Oh right, the whiteboard MetaDB! It's a very small database so the query should be quite fast, but yes I think this could probably be moved to a background thread. Do you want to submit a PR?

**Comment by brok85** [comment]
What is a PR?

**Comment by timrae** [comment]
Pull request

**Comment by brok85** [comment]
well my job is to test apps to find hang-bugs...I leave the fixing of the problem to you :)

**Comment by hssm** [comment]
I'm sorry but this is not good enough. I don't know anything about your home-grown debug tool and I'm not really keen on alpha-testing it for you. Please don't open any more issues on this project for things you find with it.


>thus leading to visible hang problems

Are you able to demonstrate this problem? Any benchmarks? A video? A reproducible test case?

The specific line of code you reference is executed only once, and only when the database in question has been modified between releases. In practice, this translates to a few milliseconds of work every two years or so. It doesn't warrant the kind of attention you've given it.

>well my job is to test apps to find hang-bugs

The onus is on you to demonstrate an actual problem, not to supply developers with machine-based conjecture. It is too easy to sink time into endless micro-optimizations that have no real-world impact. If you are not going to put any effort into demonstrating a problem or providing patches for the problems you find, then I suggest you rethink your approach because you are effectively just spamming projects at this point.

**Comment by brok85** [comment]
sorry to hear that. I am not sure why you got mad, I was just trying to
help. If you thought that the possible problem I reported was not a big
deal just tell me and that's it...no need of accusing me of spamming you.
Again, my intention was just to help improving your app. Sorry it turned
this way.

**Comment by timrae** [comment]
I agree with @hssm. I'm sure you were just trying to help, but in the end you just wasted our time reading through the stack trace and checking through the code, only to find that there wasn't even any significant problem. 

At this point in time, we are only really interested in receiving reports from actual users that are experiencing frustration with the app, or developers that are interested in submitting patches.
