### ISSUE TITLE
student looking to contribute

### ISSUE THREAD

**Issue by gwildor28** [ankidroid/Anki-Android#4084]
Hi guys

I'm a university student doing an open source project which necessitates contributing to an existing project. Really Like the stuff you guys have done with Ankidroid. I need some simple tasks to do, like putting some comments in or renaming some functions, basically tasks which don't involve having to go through and understand extensive amounts of the codebase in order to resolve an issue. If someone could point me in the right direction with this that would be much appreciated

**Comment by timrae** [comment]
How about #3795?

**Comment by gwildor28** [comment]
OK thanks will take a look

**Comment by gwildor28** [comment]
Hi timrae, I looked into the issue. I had multiple problems getting the layout in design view to render properly in Android Studio and thus I couldn't resolve the issue. I had problems with Android Support Design Widget Coordinator Layout, Navigation View Coordinator Layout and missing styles, etc. Are there any other issues within the context I outlined in my initial post that you think would be suitable for me? Ill try to find something in the meantime

**Comment by timrae** [comment]
Were you able to get the code to compile?

**Comment by gwildor28** [comment]
Yes, I just couldn't preview the layouts because of rendering problems

**Comment by timrae** [comment]
OK, but why do need to preview the layouts?

**Comment by timrae** [comment]
If this is too much for you, you might like to consider contributing to the documentation repository instead:

https://github.com/ankidroid/ankidroiddocs

**Comment by gwildor28** [comment]
Hi, its difficult to see what different buttons, etc, are for without being able to see visually what they are and connect that with different parts of the application. Has anyone else had this problem?

OK thanks I'll take a look at contributing documentation

**Comment by hssm** [comment]
We don't use the designer at all. Most of our UI is built dynamically at run-time, so the designer won't show anything useful.
