### ISSUE TITLE
media volume goes up a notch for every sound that is played

### ISSUE THREAD

**Issue by domingos86** [ankidroid/Anki-Android#4086]
Sometimes it happens that whenever I'm studying a deck, the media volume goes up by a bit for every sound that the cards play, so after some 10 sounds my volume is at the max unless I keep lowering it, which in any case is really annoying.

From what I could gather, every time this happens, it's right after using a podcast app (AntennaPod), also open source, and it happens in about 4 out of 5 times after using such app (sometimes, mysteriously, everything works fine). The only sure way I found to avoid it is to open the Play Music app and start playing something (although I believe any other music app would have a similar effect) in between using AntennaPod and Ankidroid.
This is actually a further indication that the problem is most likely with the podcast app, but at the same time it's intriguing that a single app, on a system that strives to keep everything running independently, would be able to unintentionally interfere with the behavior of another.

I'm using a Nexus 5, unrooted. This issue was present in both Lollipop and Marshmallow versions.

I'm willing to dig into this issue myself, inspecting the code for both apps, but any helpful insights would be greatly appreciated.

**Comment by eginhard** [comment]
Looks like this is a known issue of that app, so please provide further information there: https://github.com/AntennaPod/AntennaPod/issues/996

**Comment by domingos86** [comment]
Thanks for doing the research. I had never noticed that exact behavior on that app, but hopefully solving that would most likely make this not an issue on Ankidroid anymore.
