### ISSUE TITLE
Class cast exception in MyAccount

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4100]
From [acralyzer](https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/reports-browser/ankidroid/bug/1c796d46056bc74526047a3f7e55a8df)

java.lang.ClassCastException: java.lang.Object[] cannot be cast to java.lang.String[]
at com.ichi2.anki.MyAccount$10.onPostExecute(MyAccount.java:426)
at com.ichi2.async.Connection.onPostExecute(Connection.java:154)
at com.ichi2.async.Connection.onPostExecute(Connection.java:73)

**Comment by mikehardy** [comment]
I also haven't seen this, but I checked the code and I can't think how it would happen. I can't really search in acralyzer (or export it) to see if it's still happening either - at least in bulk, first 1000 entries on 2.8.4 don't have it
