### ISSUE TITLE
Failed to resolve: com.afollestad.material-dialogs:core:0.8.5.1

### ISSUE THREAD

**Issue by HentaiIsPower** [ankidroid/Anki-Android#4101]
I'm trying to build with android studio, but I get gradle this error:

`Failed to resolve: com.afollestad.material-dialogs:core:0.8.5.1`

I pulled from development branch this morning. Am I missing something?

**Comment by timrae** [comment]
I just checked and it's building OK for me. Can you try again? It's possible that the jitpack repository that hosts material dialogs was temporarily unavailable. Otherwise it could possibly be a firewall issue or something...

**Comment by HentaiIsPower** [comment]
What worked for me was using Gradle 2.11 in Project Settings. Thanks.
