### ISSUE TITLE
Request for a new 'play media' button

### ISSUE THREAD

**Issue by Glutanimate** [ankidroid/Anki-Android#4104]
I don't know if this has been discussed before (couldn't find anything here on GitHub), but I think the current play button looks somewhat out of place now that AnkiDroid has moved to material design:

![screenshot_2016-02-29-16-35-41_resized](https://cloud.githubusercontent.com/assets/5459332/13399292/d9e327f2-df02-11e5-8d51-46703b505cbd.png)

It would be great if we could switch to an updated icon that's more in-line with the current app design.

**Edit**: How about one of these  from Google's very own material design iconset:

https://github.com/google/material-design-icons/blob/master/av/svg/design/ic_play_circle_outline_48px.svg
https://github.com/google/material-design-icons/blob/master/av/svg/design/ic_play_circle_filled_48px.svg
https://github.com/google/material-design-icons/blob/master/av/svg/design/ic_play_arrow_48px.svg

They are all CC-BY 4.0-licensed.

**Comment by hssm** [comment]
Feel free to send a PR with something you feel is more suitable.

I think we need to maintain the white background in the button though (instead of transparent) since it becomes difficult to see on dark backgrounds, and adding in multiple light/dark versions complicates things too much.
