### ISSUE TITLE
The left menu icon doesn't work on the study screen when the 'gesture' is enabled

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4108]
(Moreover, there are some cards in which the menu icon doesn't work on the study screen even if the 'gesture' is disabled.)

**Comment by timrae** [comment]
I also noticed this, it's super annoying. I imagine it might be a bug in the Android support library which we recently upgraded to.

**Comment by snowtimeglass** [comment]
Oh, I understand. 
Thank you for the information.

**Comment by hssm** [comment]
https://code.google.com/p/android/issues/detail?id=203290

**Comment by snowtimeglass** [comment]
@hssm, thank you for the fix!
