### ISSUE TITLE
Refactoring In computing statistics

### ISSUE THREAD

**Issue by musilto7** [ankidroid/Anki-Android#4113]
I've read the code of computing statistics. There is int variable called mType which can have only three values. I decided to create enum called AxisType  and replace  type of mType.
There is method calculateDone in Stats.java. Second method variable is boolean. The function of boolean is not described in javadoc. I decided replace boolean by Chartype and make the method private. Then two public methods will be created: calculateReviewCount and calculateReviewTime. This two new methods will use method calculateDone.
I've already implemented changes.
[https://github.com/ankidroid/Anki-Android/pull/4114](url)

**Comment by timrae** [comment]
Hi, there's no need to create a new issue, the pull request is enough. I'll move the description here into the pull request.
