### ISSUE TITLE
Update F-Droid button

### ISSUE THREAD

**Issue by PanderMusubi** [ankidroid/Anki-Android#4120]
Please upgrade your F-Droid button to the latest version. A PNG file can be found at https://commons.wikimedia.org/wiki/File:Get_it_on_F-Droid.svg

**Comment by hssm** [comment]
Done.

**Comment by PanderMusubi** [comment]
Thanks. Your website https://ankidroid.org/docs/manual.html could also include it? Also I noticed that https://ankidroid.org and https://www.ankidroid.org are rather "boring". ;)
