### ISSUE TITLE
Disable GIF animations (for eink displays)?

### ISSUE THREAD

**Issue by llakssz** [ankidroid/Anki-Android#4121]
Hi, on my eink device I would love to stop animated GIFs, without having to recreate the deck with new non-animated media.
Could we have a setting to disable GIF animations? AnkiDroid uses Chrome to display the web stuff in the cards, correct? I'm not sure how simple it is.

I remember years ago there was an eink setting I think, but I can't see it now. Has this been made redundant and not needed?
I think it may still be useful, maybe a fullscreen refresh every X cards displayed, etc.

Thanks

**Comment by hssm** [comment]
There doesn't appear to be a way to do this so it's not really in our control.
