### ISSUE TITLE
Ability to reverse upper bar and show answer bar location 

### ISSUE THREAD

**Issue by kabutar111** [ankidroid/Anki-Android#4128]
I do most my ankidroid study while liein  or sitting on tablet and in both case my hand is holding the tablet at top and all buttons will be far more accessible at top than bottom making it usable by one hand when tablet on your leg or chest/belly. 

I would really like to see this feature or version of it. 
Please do share your thoughts and thank you for great continue support :)

**Comment by hssm** [comment]
Dupe: https://github.com/ankidroid/Anki-Android/issues/2695
