### ISSUE TITLE
Review count bouncing around? bug or burying?

### ISSUE THREAD

**Issue by doingitgood** [ankidroid/Anki-Android#4130]
Trying to understand if this is a bug or not. 

So, on the left is a screenshot pre-studying (i.e., zero cards studied today). On the right is a screenshot after about 20 mins of studying. What's caught my attention is it says "25 cards studied ...". But if you look at the original numbers, shouldn't that number be around 45? 
![A](https://cloud.githubusercontent.com/assets/15900066/13725292/5bd037ca-e852-11e5-955c-1333b9b8c1c6.png)

Now another picture

On the left I am studying and the review due count is 159. I hit the back button and the review due count drops down to 155. 
![b](https://cloud.githubusercontent.com/assets/15900066/13725316/e647b928-e852-11e5-89fe-9abb72ff8996.png)

So are there cards being buried, or is something else happening? It's very confusing having things like mismatched due numbers and "cards studied", or due counts that drop 4 cards in the span of 1 second. 

Please explain (thank you)

**Comment by eginhard** [comment]
Yes, sibling cards are buried intentionally, but only once they come up in the queue or when leaving the review screen, that's why counts can jump. You can read more about it in the [manual](http://ankisrs.net/docs/manual.html#siblings-and-burying) and disable it if you don't like it.

**Comment by doingitgood** [comment]
I'm seeing a studying-card, and at that moment, the burying kicks in? (Up to this point, I had assumed that burying was taken care of prior to studying)

**Comment by eginhard** [comment]
Assuming you have a note with two cards and one of them already came up during reviews, the second card will be buried when it comes up for study or when you leave the reviewer.

It can't be done in advance because Anki can't know if and how you'll study the cards that are scheduled for the day.
