### ISSUE TITLE
Card counter inconsistencies in subdeck

### ISSUE THREAD

**Issue by Steph1444** [ankidroid/Anki-Android#4131]
Thanks for looking into this matter, I use Anki on daily basis for almost 3 years now and I'm grateful to work with this great multi platform app.
AnkiDroid Version = 2.5.4
Android Version = 5.0.2
ACRA UUID = 2118b490-e0ca-4db3-a9dd-affefcb469a3
This issue occurs on Android, as well as on Windows
I commented the issue in the attached pictures 
![screenshot_2016-03-13-09-55-15](https://cloud.githubusercontent.com/assets/16114986/13728148/d228b7b4-e90e-11e5-83c4-100fff6a1b30.png)
![screenshot_2016-03-13-09-55-26](https://cloud.githubusercontent.com/assets/16114986/13728147/d2273786-e90e-11e5-9c0e-45b9f6578d68.png)
I guess the inconsistecy began after having performed a study session "review ahead" two weeks ago, but it persists

**Comment by eginhard** [comment]
I'm not sure why this happens, but because the behaviour is the same in Anki Desktop as you say, this is not an issue with AnkiDroid, so please report it in the main Anki forum: https://anki.tenderapp.com/discussions
