### ISSUE TITLE
Review cards disappearing without review

### ISSUE THREAD

**Issue by Kaskazaraku** [ankidroid/Anki-Android#4133]
Hello,

As I'm reviewing my cards and learning some new ones for the first time,

the "due review card" counter suddenly goes from 36 to 0. 

And numbers alike. 

What causes this bug? I end up not revising the cards I'm supposed to...

Thank you for your help.

**Comment by eginhard** [comment]
This is because sibling cards are buried (they'll be shown again the next day), it's not a bug. You can read more about it in the [manual](http://ankisrs.net/docs/manual.html#siblings-and-burying) and disable it if you don't like it.
