### ISSUE TITLE
My collection is corrupted, right after I installed ankidroid.

### ISSUE THREAD

**Issue by AradorasXeon** [ankidroid/Anki-Android#4153]
I tried to reinstal it many times, but it always says "An error occured while accessing your collection. It may have been caused by a harmless bug, or there may be a problem with it." I tried every options, but none of them is working.

**Comment by timrae** [comment]
Hi can you please install the latest alpha version and see if that fixes it?

**Comment by AradorasXeon** [comment]
Hi I tried it and now it says: "There is no available storage" but I have like 700 MB+ free space on my phone (on the default storage, I don't use SD card atm).

**Comment by timrae** [comment]
Did you solve this issue? What version of Android are you using? If Android 6, please ensure you granted the storage permission

**Comment by AradorasXeon** [comment]
No, I was not able to solve it :( I am using Android 4.0.4 (Icecream sandwhich). I am hoping you guys can solve it somehow, it would be great to use anki on my phone. I have a ZTE Blade III phone, if this helps.

**Comment by timrae** [comment]
It sounds like an issue with your specific device, so I don't think there's much we can do unfortunately. Your best bet is probably to try a different (newer) Android device. Or you could try changing the ROM and see if that helps.
