### ISSUE TITLE
AnkiDroid sets itself as default viewer for different file types on ChromeOS

### ISSUE THREAD

**Issue by ivant** [ankidroid/Anki-Android#4161]
AnkiDroid, when installed as a Chrome App on ChromeOS, sets itself as a default viewer of various filetypes, most notably `zip` files, which is extremely annoying (instead of mounting zip file contents as a virtual folder, Anki is started). There seems to be no explicit way to turn that association off in ChromeOS after the app has been installed.

**Comment by timrae** [comment]
Should be fixed in the alpha version

https://github.com/ankidroid/Anki-Android/releases
