### ISSUE TITLE
The position of "play media" icon

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4162]
@Glutanimate, @hssm, @ospalh,
thank you for the refinement on the new "play media" icon. (#4104, #4106, #4152)
I also like it.

However, the position of the triangle seems to be a bit too high when it is next to strings whose size is standard (20px).  
![image](https://cloud.githubusercontent.com/assets/10436072/13920641/6ed4994e-efb7-11e5-8526-f76ce041ce02.png)

(On Anki Desktop, the "play media" icons are on proper positions, relatively. )
![image](https://cloud.githubusercontent.com/assets/10436072/13920981/160ab170-efb9-11e5-8629-6eff18934421.png)

On that point, the icon has yet to be refined, I think.
What do you think about it?

**Comment by snowtimeglass** [comment]
I don't feel that the touch feedback is beautiful, either.
 ![image](https://cloud.githubusercontent.com/assets/10436072/13921821/23ce0416-efbd-11e5-899c-b2ac6aeda2bb.png)
Would this be repaired?

**Comment by ospalh** [comment]
Can you perhaps publish  (or e-mail) your test card/model?
That would make testing a bit easier for me.

P.S.:
Maybe you want to take a look at the [SVG version](https://github.com/ospalh/anki-addons/blob/develop/svg_play_button.py) of the desktop replay button add-on? (When you have both `play_button.py` and `svg_play_button.py` installed at the same time, you’ll get two replay buttons per file, so maybe you want to delete the old play_button.py.)

**Comment by snowtimeglass** [comment]
@ospalh, thank you for the reply.
I've attatched the apkg file of the sample card here.
[Sample (play media icons).zip](https://github.com/ankidroid/Anki-Android/files/184121/Sample.play.media.icons.zip)

My device is Galaxy Note II.
The Android version is 4.3.

>P.S.

Thank you for the information.
How can I install the SVG version of the desktop replay button add-on?

**Comment by ospalh** [comment]
Thanks for the deck.

It actually looks slightly better, at least to my eye, when you *do* use a background that sets this up from the card background.
(
```
.card .replaybutton svg {
    background-color: #ddd;

}
```
)

Anyway, some thoughts:
* For AnkiDroid, these is a fixed size to these buttons, so they are always big enough to touch them, even when the font is tiny.
* The actual triangle is smaller than the image area, so when the image is bigger than the line, the transparent area at the bottom makes the position of the triangle look odd.
* Also, the bottom of the arrow  image is aligned with the baseline of the text, not with the descenders
* All in all, i guess this can be somewhat improved, but it will be some random tweaking, and the whole thing is at least partially a matter of taste.

**Comment by snowtimeglass** [comment]
I've been writing a reply to the yesterday comment of yours. 
Fortunately it is not necessary any more.
 
Thank you very much for the fix (#4168)! 
It's very nice!
