### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by tartsi** [ankidroid/Anki-Android#4180]
On the question / hint part of the card (top part) some of the thai letters are not shown properly. However the letters are show properly at the answer (bottom part).

I think thai letters were shown properly when I first time used this app about half a year ago.

This issue was with android 6.0.1

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#instead-of-the-correct-character-to-display-a-square-is-shown-why-is-that
