### ISSUE TITLE
New Ankidroid doesn't show you total number of new cards in deck anymore

### ISSUE THREAD

**Issue by gotofritz** [ankidroid/Anki-Android#4183]
Before the revamp Ankidroid would show, for each deck, how many new cards the deck had in total. That information was very useful, it told me when new cards were running low and I needed to prepare new ones. Now that information is gone. Please bring it back. Thanks.

**Comment by timrae** [comment]
You can view this information under statistics -> card types

If you prefer the Anki 2.4 way, you can also [do this](https://ankidroid.org/docs/manual.html#_clickable_areas_on_the_decks) but we may remove that possibility in the future as it's inconsistent with Anki Desktop.
