### ISSUE TITLE
Android: Small displaying bug in horizontal mode

### ISSUE THREAD

**Issue by IlianP** [ankidroid/Anki-Android#4187]
AnkiDroid Version = 2.5.4
Android Version = 5.0.2
ACRA UUID = 7f4b08a8-87db-4ab0-8d88-a480b560d2e1

Screenshot:
https://www.dropbox.com/s/b9ssg9h84pbh11a/QuickMemo%2B_2016-03-31-18-24-41.png?dl=0

Might be just the German interface. However, there's not enough space for the entire headline to fit.

**Comment by hssm** [comment]
Seems to happen on Android 5.0 specifically, and only when we rotate from portrait (i.e., starting from landscape works fine).
