### ISSUE TITLE
Bug: long-tapping on a line of the card browser won't show a menu at first

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4191]
*Steps*

1. Open AnkiDroid
2. Tap "Card browser" on the navigation drawer
3. Select a deck which has many cards (ex. your "All decks")
4. Exit AnkiDroid
5. Open AnkiDroid again
6. Tap "Card browser" on the navigation drawer again
7. Long-tap on a line (a card) of the list

AnkiDroid: 2.6alpha19
Android: 4.3

**Comment by timrae** [comment]
That's weird, I reproduced on my Nexus 6. Would you be able to tell us the version where this first started to occur?

**Comment by snowtimeglass** [comment]
Sorry. I can't remember the version.

**Comment by timrae** [comment]
Hmm... going back through the versions might be the only way to figure this strange bug out... Could it have happened going from alpha3 to alpha4? or maybe from alpha16 to alpha17? 

I don't have time to test it out at the moment.

**Comment by snowtimeglass** [comment]
I checked [AnkiDroid-2.5beta16.parallel.C.apk](https://github.com/ankidroid/Anki-Android/releases/download/v2.5beta16/AnkiDroid-2.5beta16.parallel.C.apk) just now.
This bug happens on it, too.

**Comment by snowtimeglass** [comment]
The bug seems to have happened from v2.4alpha20.

So far I haven't reproduced the bug on v2.3.2 and v2.4alpha11 ~ v2.4alpha17.
v2.4alpha18 is _v2.4alpha4_ for some reason.
I reproduced the bug on v2.4alpha20.

**Comment by timrae** [comment]
> I reproduced the bug on v2.4alpha20

Are you sure? I can't reproduce it on 2.4alpha20 or 2.4.4

**Comment by snowtimeglass** [comment]
Sure. I checked it again just now.
I can reproduce the bug repeatedly on 2.4alpha20, on Android 4.1.2 & 4.3, 
while I haven't reproduced it so far on 2.4alpha17, on the both Android version. 

_Steps_
1. Open AnkiDroid
2. Tap "Card browser" on the navigation drawer
3. ("All decks" has already been selected)
4. Long-tap on a line (a card) of the lis

**Comment by timrae** [comment]
Would you be able to show a video if it's not too much trouble?

**Comment by snowtimeglass** [comment]
Sure, but I rather hesitate to show my decks to the public.
Would you tell me your e-mail address?
I made a video just now.

**Comment by timrae** [comment]
perceptualchaos2 at gmail

**Comment by snowtimeglass** [comment]
Thank you. I send a mail just now.

**Comment by timrae** [comment]
Thanks, the video clarified the observed behavior, however I was unable to reproduce on those versions. For me the problem version is 2.6beta4, specifically the changes that introduce the question to the first column instead of the sort field.

If you wait some time for all the background tasks to finish before you attempt the long-press then the issue will not occur.

**Comment by snowtimeglass** [comment]
The bug doesn't always happen even on my device.

I suspect the time of loading the data of cards relates to this bug.
Whenever I long-tap a row 5 seconds after the "Filtering cards… Press back button to cancel" message disappears, the bug doesn't seem to happen  (in other words, the menu seems to be displayed properly) on  2.4alpha20.

When I long-tap a row immediately after the above message disappears, the menu is displayed properly on 2.4alpha17, while it isn't on 2.4alpha20.

**Comment by snowtimeglass** [comment]
>If you wait some time for all the background tasks to finish before you attempt the long-press then the issue will not occur.

Yes, I see..., but I don't need to wait any time on 2.4alpha17.
Isn't there any change which relates to the browser, between 2.4alpha17 and 2.4alpha20?

**Comment by snowtimeglass** [comment]
Thank you for the fix on v2.6alpha20, but I'm sorry to say that I can't help turning it down...
On v2.6alpha20, it takes as many as about 27 seconds to load the list, in contrast to about 3~4 seconds on v2.6alpha19...

I'll send a mail with the videos.

**Comment by snowtimeglass** [comment]
I sent it.

**Comment by snowtimeglass** [comment]
The v2.4alpha17 can load the list as fast as v2.6alpha19, and it can preview cards after loading the list as fast as v2.6alpha20.

**Comment by timrae** [comment]
> On v2.6alpha20, it takes as many as about 27 seconds to load the list, in contrast to about 3~4 seconds on v2.6alpha19...

You're right, it was too slow... Please check alpha21.

> The v2.4alpha17 can load the list as fast as v2.6alpha19, and it can preview cards after loading the list as fast as v2.6alpha20.

v2.4alpha17 only shows the sort field and the card type; it doesn't require rendering the html for the question and answer, so it's much faster. I believe 2.6alpha21 should be less than a second slower than 2.4alpha17.

**Comment by snowtimeglass** [comment]
Thank you for the work. 2.6alpha21 is pretty good.

>I believe 2.6alpha21 should be less than a second slower than 2.4alpha17.

Yes, it appears so. It is fast, but appears to be a bit slower than 2.4alpha17.
I'll send a mail with the videos again.

**Comment by snowtimeglass** [comment]
I sent it just now.

**Comment by timrae** [comment]
Yes, it will be a bit slower as I mentioned.

**Comment by snowtimeglass** [comment]
I see. Thank you for minimizing the damage.
