### ISSUE TITLE
Playback audio with note tag

### ISSUE THREAD

**Issue by ourlaw** [ankidroid/Anki-Android#4192]
The button is too small and when I press the button, the audio plays incompletely and then display the other side automatically.
And I should press the button again to hear the audio.

AnkiDroid Version = 2.5.4

Android Version = 5.0.2

ACRA UUID = 69e96336-7700-45c9-ada6-431af75974ec

**Comment by timrae** [comment]
> when I press the button, the audio plays incompletely and then display the other side automatically.

Do you have a tap gesture enabled?

**Comment by ourlaw** [comment]
Yes and when this feature is disabled, it works correctly but does tapping on the audio button considered as a tap on screen?
If it does, then it is a bad conflict.

**Comment by timrae** [comment]
Yeah it's a technical limitation. 

You can use the replay audio option in the overflow menu instead if you prefer.
