### ISSUE TITLE
Error message for missing sdcard

### ISSUE THREAD

**Issue by stefaneidelloth** [ankidroid/Anki-Android#4196]
If no sdcard is available, AnkiDroid shows a database error and suggest to:
-do a full sync
-delete the data and create a new database
...

But there is no hint that AnkiDroid requires an sd card and is not able to store decks directly on the phone.
=> Add a hint "Please ensure that an sd card is available"

**Comment by timrae** [comment]
How about in the latest alpha version?
https://github.com/ankidroid/Anki-Android/releases

**Comment by stefaneidelloth** [comment]
The latest alpha version resolves this issue. An error message is shown if I try to start Anki without sd card. Thank you.
