### ISSUE TITLE
Bug: Setting of "Choose display order" of the card browser isn't maintained when "All decks" is selected

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4199]
_Steps_
1. Open AnkiDroid
2. Tap "Card browser" on the drawer
3. Select "**All decks**"
4. Select "Change display order" on the menu
5. Select an order (ex. "By ease")
6. Exit AnkiDroid (Tap the back button twice)
7. Swipe and delete the item of AnkiDroid on the App. history list.
8. Open AnkiDroid again
9. Tap "Card browser" again 

Then, the cards are ordered by another order (ex. "By edited time (▲)").

AnkiDroid: 2.6alpha21
Android: 4.3 & 4.1.2

**Comment by bexsadirov** [comment]
Here are my observations when I tried to find the bug:
1. If you just select another deck from drop down spinner, the order type stays saved;
2. If you change the deck to another existing one, return back to "All Decks", and then select order type, it will be saved.

**Comment by tapish2000** [comment]
Hey, I want to try this issue out if I can get some help if needed.

**Comment by david-allison-1** [comment]
Sounds good to me, thanks!

**Comment by tapish2000** [comment]
https://github.com/ankidroid/Anki-Android/blob/3cca3b1f6e4c8edf05386a4652fb5e34566ddf26/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L192

This maybe an issue because these are currently hidden. Is this true?

**Comment by david-allison-1** [comment]
unlikely to be that

**Comment by tapish2000** [comment]
In the following lines of code in [CardBrowser.java](https://github.com/ankidroid/Anki-Android/blob/ec5d9e535c391a150e3489ceb515426a3946c305/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L245) in the function named `changeCardOrder()`:

```java
protected void changeCardOrder(int which) {
        if (which != mOrder) {
            mOrder = which;
            mOrderAsc = false;
            if (mOrder == 0) {
                // if the sort value in the card browser was changed, then perform a new search
                getCol().getConf().put("sortType", fSortTypes[1]);
                AnkiDroidApp.getSharedPrefs(getBaseContext()).edit()
                        .putBoolean("cardBrowserNoSorting", true)
                        .commit();
            } else {
                getCol().getConf().put("sortType", fSortTypes[mOrder]);
                AnkiDroidApp.getSharedPrefs(getBaseContext()).edit()
                        .putBoolean("cardBrowserNoSorting", false)
                        .commit();
            }
            getCol().getConf().put("sortBackwards", mOrderAsc);
            searchCards();
        } else if (which != CARD_ORDER_NONE) {
            // if the same element is selected again, reverse the order
            mOrderAsc = !mOrderAsc;
            getCol().getConf().put("sortBackwards", mOrderAsc);
            mCards.reverse();
            updateList();
        }
    }
```
`mOrder` is the variable which stores the index of the sorting type the user has selected according to the following array:
```java
private static final String[] fSortTypes = new String[] {
        "",
        "noteFld",
        "noteCrt",
        "noteMod",
        "cardMod",
        "cardDue",
        "cardIvl",
        "cardEase",
        "cardReps",
        "cardLapses"};
```
When the user has selected `No sorting (faster)` option, i.e., `mOrder = 0`, then we write `getCol().getConf().put("sortType", fSortTypes[1]);` , i.e., `fSortTypes[1] = "noteFld"` by default. 
Is this a wise thing to do? If the user wants to keep `No sorting`, then why are we forcing it to have sort `by sort field`?

**Comment by david-allison-1** [comment]
Looks strangely implemented, but fine to me:

https://github.com/ankidroid/Anki-Android/blob/db9260c03143d3770ede4b39db9e15727a69b4cf/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L562-L571

**Comment by tapish2000** [comment]
> Looks strangely implemented, but fine to me:
> 
> https://github.com/ankidroid/Anki-Android/blob/db9260c03143d3770ede4b39db9e15727a69b4cf/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L562-L571

Line number 562 runs initially when we open `Card Browser` for the first time in the app. When I am checking, this variable `colOrder` comes out to be `noteFld` i.e., `By Sort Field` always. But it should capture the previous value of sorting type that the user selected before closing the app. For this to be done, I think we should store the current `colOrder` in `SharedPreferences` everytime it is changed. If you approve this. Because I think `getCol().getConf().putString("sortType", fSortType[mOrder])` is getting changed whenever we close (removing from Android history too) and open the app again.

**Comment by tapish2000** [comment]
`getCol().getConf().getString("sortType");` -> Does this line mean that a field named `"sortType"` in database is accessed?

**Comment by david-allison-1** [comment]
> `getCol().getConf().getString("sortType");` -> Does this line mean that a field named `"sortType"` in database is accessed?

Technically it's an in-memory cache, but the value is equivalent to what's in the database. The database is a text column containing JSON

**Comment by tapish2000** [comment]
This in-memory cache must get erased when we close the app and remove it from the android history I think.
Am I right?

**Comment by david-allison-1** [comment]
> This in-memory cache must get erased when we close the app and remove it from the android history I think.
> Am I right?

It should be equivalent with the database (and treated as a bug if otherwise), the cache is a technical detail.

**Comment by tapish2000** [comment]
Yeah, I tried it out. The initial `sortType` is loaded from this in-memory cache which always comes out to be `noteFld`, not changing. When I saved it in this in-memory cache and reopened the app, it was again initialised to `noteFld`. 
What are my alternatives here, should I use `sharedPreferences` to save this information?

**Comment by david-allison-1** [comment]
`getCol().flush()`
