### ISSUE TITLE
The current title of non-default night theme is out-of-date 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4204]
Now, non-default night theme is dark grey.
The current title, "Black", should be replaced with "Dark grey", shouldn't it?
![image](https://cloud.githubusercontent.com/assets/10436072/14410461/581218c6-ff6b-11e5-9943-6a429e1fd3a5.png)

**Comment by timrae** [comment]
I just pushed the updated files

**Comment by snowtimeglass** [comment]
Thank you for the prompt response.
