### ISSUE TITLE
There aren't four texts for translation on Crowdin

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4205]
The "themes", "day theme", "night theme", and "fonts" don't seem to exist on Crowdin.
![image](https://cloud.githubusercontent.com/assets/10436072/14410533/1f750dc8-ff6d-11e5-8ed2-57be6098dbb2.png)

**Comment by timrae** [comment]
I just pushed the updated files

**Comment by snowtimeglass** [comment]
There still aren't, in contrast to #4204.
Is this all right?

**Comment by timrae** [comment]
@hssm it looks like you forgot to add the String resources, these are currently hardcoded

**Comment by snowtimeglass** [comment]
...? There still aren't this time, either.

**Comment by timrae** [comment]
They're there now

**Comment by snowtimeglass** [comment]
Thank you.
