### ISSUE TITLE
Provide an alternative for profiles

### ISSUE THREAD

**Issue by michalpravda** [ankidroid/Anki-Android#4209]
Note: this is already solved - https://github.com/ankidroid/Anki-Android/wiki/FAQ#how-to-use-different-anki-profiles
Just needed a "clean" issue to use for https://www.bountysource.com

**Comment by timrae** [comment]
This isn't really how a bounty is supposed to work; you should only create a bounty for existing open issues, and the bounty is awarded when the task is completed.

**Comment by michalpravda** [comment]
I use your work. It has solved my problem. I am happy. I don't care, that you did it before I personally asked for it. Also, I am doing this (the bounty) the first time so I'm running in the wild a bit. You can solve this and claim the bounty - that's why I have created it. https://www.bountysource.com/issues/32816047-provide-an-alternative-for-profiles

5$ won't pay your bills, but it may make your day better. That's all.

**Comment by timrae** [comment]
OK thanks, I appreciate the gesture :)
