### ISSUE TITLE
On the Black theme, some colors of "Settings" are odd

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4212]
![image](https://cloud.githubusercontent.com/assets/10436072/14458194/843c5f8a-00ea-11e6-86b4-340e54cd2cde.png)
![image](https://cloud.githubusercontent.com/assets/10436072/14458205/92c78db8-00ea-11e6-86c6-64e4bf6af938.png)

**Comment by IlianP** [comment]
Fits into this thread as well:
![screenshot_20160418-084725](https://cloud.githubusercontent.com/assets/13310932/14598084/ee96f16e-0550-11e6-877b-e7cbab145220.png)

**Comment by hssm** [comment]
The first problem is covered by #4090 and it's something I know about. The second problem should be fixed in recent builds. If you grab an alpha build from the releases page I think you'll find it's no longer a problem.

**Comment by snowtimeglass** [comment]
>If you grab an alpha build from the releases page I think you'll find it's no longer a problem.

Has the first problem already been fixed?
I've been using 2.6alpha22 for a while, and the screenshots which I posted are taken on it.

**Comment by hssm** [comment]
No, that we only referring to the second issue.

**Comment by snowtimeglass** [comment]
"The second problem" is ambiguous for me.
Is it the problem shown by my second screenshot, or the problem which IlianP posted?

**Comment by hssm** [comment]
The one from @IlianP's post. I considered "broken themes in settings" as one issue.

**Comment by snowtimeglass** [comment]
I see. Thank you.
