### ISSUE TITLE
card layout not honoured

### ISSUE THREAD

**Issue by muellert** [ankidroid/Anki-Android#4220]
I have a deck with customized card layouts. When I try to study this deck with AnkiDroid, the layout is different, messing up the study process. The problem is that fields are shown in the question which I only want to be shown in the answer. I found no way to customize the card layout in AnkiDroid, but if I would, it should not be copied to the desktop version.

**Comment by timrae** [comment]
Are you saying that cards are being rendered differently on AnkiDroid and anki desktop? If so please attach a small sample apkg demonstrating the problem (for example via Google drive or drop box link)

**Comment by muellert** [comment]
I thought so, but it turned out that I was just confused (ie. PEBKAC).  :(
