### ISSUE TITLE
Performance Issue of AsyncTask.execute

### ISSUE THREAD

**Issue by frankFic** [ankidroid/Anki-Android#4224]
Hello, developers of AnkiDroid,

I have just found out `AsyncTask.execute` is used in many places like 5 times in LoadPronounciationActivity, 4 times in AnkiStatsTaskHandler, etc.
However, this API is slower on devices with version higher than Android 3.0. As tasks started by this API are executed serially on a single background thread on those devices (stated in [API guide](http://developer.android.com/intl/zh-cn/reference/android/os/AsyncTask.html#execute(Params...))).

Using method  `executeOnExecutor` to achieve real multi-thread may improve the performance.

Thanks a lot.

**Comment by timrae** [comment]
Thanks for the info, we were aware of this and chose to execute the AsyncTasks serially.
