### ISSUE TITLE
Hitting the "back" button while studying cards causes the number of due cards change

### ISSUE THREAD

**Issue by Hapoofesgeli** [ankidroid/Anki-Android#4225]
If I get back to the main decks view while I'm in the middle of studying a deck (having again/review/new cards...), number of due cards suddenly change and get reduced. Most likely getting rescheduled rather than refreshed.
This can cause many scheduling issues if you have lots of due cards...

**Comment by eginhard** [comment]
This is the correct expected behaviour when sibling burying is enabled and won't cause scheduling issues. You can read more about it in the [manual](http://ankisrs.net/docs/manual.html#siblings-and-burying) and disable it if you don't need it.
