### ISSUE TITLE
Unification of terminology: "Action bar" and "Tool bar"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4230]
How about unifying the terms into either?

![image](https://cloud.githubusercontent.com/assets/10436072/14764996/7980a53e-0a08-11e6-8535-e447bb740d9d.png)

![image](https://cloud.githubusercontent.com/assets/10436072/14764982/790d678c-0a07-11e6-8fa2-1b4ccdff82d7.png)

**Comment by timrae** [comment]
Good idea

**Comment by timrae** [comment]
Actually "App bar" is now the official term used in the [material design docs](http://developer.android.com/training/appbar/index.html) so let's change them both to that. Toolbar has a less specific meaning that could potentially be ambiguous.

**Comment by timrae** [comment]
> The app bar, formerly known as the action bar in Android, is a special kind of toolbar that’s used for branding, navigation, search, and actions.

**Comment by snowtimeglass** [comment]
I see, thank you.

**Comment by timrae** [comment]
Could you please make an issue in ankidroiddocs about updating the manual to use "app bar"?
