### ISSUE TITLE
Use pale gray color characters when the item is disabled 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4233]
as it was.
![image](https://cloud.githubusercontent.com/assets/10436072/14765463/81a81bba-0a1d-11e6-8c4c-829cd4ff5fec.png)

**Comment by timrae** [comment]
The new way is the standard material design behavior. See the gmail app for example.

**Comment by snowtimeglass** [comment]
Where is the sample?
![image](https://cloud.githubusercontent.com/assets/10436072/14765539/50598b08-0a21-11e6-8831-4d3d52c8b2bf.png)

**Comment by timrae** [comment]
I don't understand your question

**Comment by snowtimeglass** [comment]
>See the gmail app for example.

What example behavior can I find out by seeing the "Gmail" app?

**Comment by timrae** [comment]
The unchecked boxes in gmail look exactly the same as in AnkiDroid

**Comment by timrae** [comment]
Oh sorry I misunderstood your request, you're talking about the disabled items background color, right?

**Comment by snowtimeglass** [comment]
Background color...? Are you talking about colors of checkboxes?
I'm talking about the color of the characters of the items (for example, "Swipe sensitivity") which are automatically disabled by disabling their "parent", more fundamental item, "Enable gestures".

![image](https://cloud.githubusercontent.com/assets/10436072/14765691/a30d334e-0a27-11e6-9d15-5f59cd9ec9d0.png)

**Comment by snowtimeglass** [comment]
The same goes for the following items.
![image](https://cloud.githubusercontent.com/assets/10436072/14784625/7b78c0a4-0b31-11e6-8d35-bdbdcc6bb666.png)

**Comment by snowtimeglass** [comment]
and subordinate items to "Automatic display answer" , "Notify when" (in case of "Never notify")

**Comment by snowtimeglass** [comment]
I think that the same goes for the following items.

![image](https://cloud.githubusercontent.com/assets/10436072/15799378/a6f97754-2a95-11e6-9ecd-e5004ad0bc3c.png)
