### ISSUE TITLE
Greyed out OK button in numerical input

### ISSUE THREAD

**Issue by arooooon** [ankidroid/Anki-Android#4238]
> Use Increase today's new card limit
> Press backspace to erase (OK greys out)
> Write a number

You can't press OK because it's still greyed out.

**Comment by hssm** [comment]
What version of AnkiDroid are you on? I couldn't reproduce it, but it *does* crash if you tap OK with no value written. We should probably fix that.

**Comment by arooooon** [comment]
No crash here. It's just not possible to click it. Both latest master and
develop.
Den 25 apr 2016 04:37 skrev "Houssam Salem" <notifications@github.com>:

**Comment by hssm** [comment]
Where are you accessing the dialog from? What version of Android are you on?

**Comment by timrae** [comment]
A video might be useful

**Comment by arooooon** [comment]
Please skip to 25 seconds. https://vid.me/UVCB

Notice how the OK button isn't clickable in the second example when I use numerical input. I have to use backspace to enable it.

Galaxy S4, Android 5.0.1. As well as a Galaxy Tab S. Maybe it's related to Samsung customization?I have not rooted the devices.

**Comment by hssm** [comment]
That is odd. I wonder if the keyboard is responsible. Any chance you can try another keyboard?

On the stock keyboard you can tap the submit button when there is no text and that turns off the OK button, but it behaves normally once you type something in.

**Comment by arooooon** [comment]
So installed SwiftKey on my Tab S and nope the problem isn't there anymore. However there is some other odd behavior: Erase everything and the ok button is still available and clickable (crash), erase once more and the button is greyed out.

**Comment by arooooon** [comment]
Genymotion :
with PC hardware keyboard:
Nexus 10  5.1 - NORMAL
Galaxy S4 4.4.4 - NORMAL

Without hardware keyboard:
Galaxy S4 4.4.4 Android AOSP keyboard - OK button is never greyed out. Crash.
Nexus 10  5.1 AOSP - OK button is never greyed out. Crash.
