### ISSUE TITLE
AnkiDroid crashes when badlydrawnrob/anki notetype is present

### ISSUE THREAD

**Issue by leezu** [ankidroid/Anki-Android#4241]
Dear all,

first of all thanks for developing this great piece of software.

Recently I found out about the https://github.com/badlydrawnrob/anki note type and added it to my desktop anki. Now AnkiDroid crashes as soon as I try to sync and as soon as I start AnkiDroid again it crashes again.

Only resetting AnkiDroid, deleting the collection, removing the note type on my desktop version and then syncing the collection without beforementioned notetype to AnkiDroid makes it work again.

Thanks

**Comment by timrae** [comment]
What's your "debug info"?
https://ankidroid.org/docs/help.html

**Comment by leezu** [comment]
Dear tlmrae, thanks for your comment and sorry for not including the debug info in the first place. However I'm afraid that I don't know how to get the debug info as I cannot start AnkiDroid anymore, when the abovementioned issue occurs.

Is it fine to gather the debug info before making the application crash?
Does the debug info change, after resetting AnkiDroid and deleting all files on the internal storage (or is it deterministically created from the device information)?

**Comment by timrae** [comment]
> Does the debug info change, after resetting AnkiDroid and deleting all files on the internal storage (or is it deterministically created from the device information)?

Yeah the debug info is reset when you uninstall the app, it's just a hash generated when you first run AnkiDroid and is stored in the app data. Are you able to start the app properly with the latest alpha version?

https://github.com/ankidroid/Anki-Android/releases

**Comment by leezu** [comment]
Thanks.

I reset Anki, deleted all files and then captured the following debug information:

> AnkiDroid Version = 2.5.4
> Android Version = 6.0.1
> ACRA UUID = 0a26dab9-005e-4c81-95af-28cdbd36db89

Afterwards I reproduced the crash by importing the https://github.com/badlydrawnrob/anki note type on my desktop and synchronizing with AnkiDroid. I hope that the debug report was successfully submitted to your internal crash report database.

**Comment by timrae** [comment]
Thanks, did you try the alpha version?

**Comment by leezu** [comment]
I tried it now. The issue persist. It gives however a more useful error:

> **Collection not opened**
> The Android size limit for a String in a database has been exceeded. Delete any unused note types using Anki desktop, then do a full sync.

I think if AnkiDroid can not fix this issue due to the Android size limit it would still be desirable that – if feasible – AnkiDroid does not crash so that one can perform the mentioned full sync without deleting the collection manually from the internal storage.

**Comment by timrae** [comment]
Ah, thanks. It's no longer "crashing", it's just discovered an erroneous state and gives you options and instructions on how to fix it.

> AnkiDroid does not crash so that one can perform the mentioned full sync without deleting the collection manually from the internal storage.

Doing the full sync should work fine in the alpha version after you delete excess note types.
