### ISSUE TITLE
Empty Cards confirmation takes too much time on UI thread

### ISSUE THREAD

**Issue by marcardar** [ankidroid/Anki-Android#4247]
When clicking OK on Empty Cards dialog for 2000 cards, the UI hangs for about 12 seconds on a Nexus 6P. The user does not see the button pressed state, so this is confusing.

These timings are for 2.5.4

**Comment by david-allison-1** [comment]
Let's keep this one, I remember seeing this myself.

**Comment by akp660** [comment]
I can work and solve issues by making UI simple and lag-free.

**Comment by dae** [comment]
Fixed in the backend switchover.
