### ISSUE TITLE
Feature request: Opening media file with third party's app by long-tapping a media icon

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4248]
I sometimes wish I could easily change speed of audio files with which I study on AnkiDroid.
If long-tapping a media icon would open another app, I could do so by Audipo.

Audipo
https://play.google.com/store/apps/details?id=jp.ne.sakura.ccice.audipo&hl=en
![image](https://cloud.githubusercontent.com/assets/10436072/14849861/57842b4a-0cb0-11e6-913a-5dbd37b16783.png)

The feature would also meet the demand, Pause/Rewind video on Ankidroid #3876.
Moreover, users could also listen audio files auto-repeatedly, even in partialy.

**Comment by timrae** [comment]
Cards in Anki are just html, you can make them do whatever you want. We're definitely not going to add individual specific features for specific use cases like this, but I imagine it's possible to acheive something similar to what you described by creating an appropriate [intent to open the app you want](https://developer.chrome.com/multidevice/android/intents). Maybe some javascript might be necessary as well, though I'm not too sure.

**Comment by snowtimeglass** [comment]
It is not an individual specific feature for specific use but a feature for many foreign language learners who hope to improve their listening ability.

**Comment by MarekHappy** [comment]
Yeah, I do actually not understand, why these features (Media customisation) get so little attention around Anki tech community.

It would be such a godlike feature to be able to study much more effectively trough the media (both audio and video). 

*I wish* someone found the solution... or is there already?
Thx for any input.
