### ISSUE TITLE
feature request: Option to control via volume buttons.

### ISSUE THREAD

**Issue by HairyPhil** [ankidroid/Anki-Android#4249]
User scenario: I use anki to learn foreign languages. I can attach audio to each card's question and answer. I want to use this while out walking, when I cannot look at the screen. I would like to use the button 'volume up' for 'show answer' and 'answered correctly', and 'volume down' for 'replay question' and 'answered incorrectly', then I could review a deck with my phone in my pocket without looking at it. For any exceptions, I could just momentarily use Anki normally.

I think this is a simple change requiring:
* Add a new toggle switch on the options page.
* Map two physical button inputs to four existing virtual buttons (depending on whether the question or answer is currently displayed).
* Allow Anki to run in background while screen is locked.

One problem: Since I am using audio, I may want to actually change the volume sometimes. Perhaps an alternative on-screen volume adjuster or control toggle would need to be displayed. (A workaround would be to switch to the phone's home screen, adjust the volume using the volume buttons, then switch back to Anki.)

I realise my suggestion limits answers to only two responses, good/bad, and not difficult/easy. It may be possible to add additional responses via for example double-press or long-press, but I thought it would be better to start simple.

I realise this may not be in demand at the moment, but it is a chicken-and-egg problem: people would use more full-audio decks if this feature was implemented. I hope that once people realised it was possible to use Anki via audio only, it would become a unique feature that could contribute to making Anki even more popular.

**Comment by timrae** [comment]
Hi this is already possible using a third party app to map the volume buttons to keyboard shortcuts.
https://github.com/ankidroid/Anki-Android/issues?utf8=%E2%9C%93&q=is%3Aissue+volume+buttons+control+
