### ISSUE TITLE
Does the header of navigation drawer keep pace with the new icon and the splash screen?

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4255]
The header of navigation drawer reminds me of the old icon of AnkiDroid.
Does it keep pace with the new icon and the splash screen?

**Comment by timrae** [comment]
Personally I like it and think they work well together. As always though, you or anyone else are welcome to submit an alternative design. 

Closing as not a bug report or enhancement request. General discussions like this are better suited to the forum.

**Comment by snowtimeglass** [comment]
I understand. Thank you.
