### ISSUE TITLE
Change the current whiteboard-undo icon to more intuitive and visual one

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4257]
"Add undo last stroke feature to whiteboard" #4245  will please many users.
However, its icon seems to leave room for improvement. 
![image](https://cloud.githubusercontent.com/assets/10436072/14939548/b7238df6-0f86-11e6-9dcf-b0aec2b949b6.png)

How about changing the current undo icon to more intuitive and visual one?
For example, how about this?
![image](https://cloud.githubusercontent.com/assets/10436072/14939554/dc75fa6c-0f86-11e6-8c60-21c25584bbcd.png)
https://materialdesignicons.com/icon/eraser-variant

It can be interpreted as erasing a single line.

**Comment by timrae** [comment]
I'd need to see what it looks like in the actual AnkiDroid toolbar. I'm busy with another project, but if you fork the source code and just replace the "-1" icon with the icon you want in all the `.../res/drawable-xxxx` subfolders (i.e. using the same name), and then compile and run on the emulator (or device) you should be able to create a screenshot pretty easily.

See here for more info on compiling etc:
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide

**Comment by snowtimeglass** [comment]
>fork the source code and just replace the "-1" icon with the icon you want in all the .../res/drawable-xxxx subfolders (i.e. keeping the same filename as the old icon)

Probably, I've done it.

![image](https://cloud.githubusercontent.com/assets/10436072/15090250/c4b76872-145c-11e6-9819-cbe453dd08b2.png)

>and then compile

Unfortunately I can't understand how to compile it, though I've read the instruction...

![image](https://cloud.githubusercontent.com/assets/10436072/15090258/61ef8eb2-145d-11e6-91ee-a043249b1555.png)

Would you please teach me what to do next more specifically?

**Comment by timrae** [comment]
You can just open the project in Android studio and hit the play button.

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#running-ankidroid-from-within-android-studio

**Comment by timrae** [comment]
If you prefer to just get the APK and install on your device without using Android studio you can use command line as well

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#compiling-from-the-command-line

**Comment by snowtimeglass** [comment]
Thank you for the information, but I'm at a standstill.

>You can just open the project in Android studio and hit the play button

Does "the project" mean this "AnkiDroid"?

![image](https://cloud.githubusercontent.com/assets/10436072/15090763/5a324f50-146e-11e6-8e14-113063de0269.png)!

![image](https://cloud.githubusercontent.com/assets/10436072/15090738/61c8f832-146d-11e6-9931-4a9e5c88b3d8.png)


![image](https://cloud.githubusercontent.com/assets/10436072/15090790/1ce89676-146f-11e6-842f-f74e2859d14f.png)

What should I do?

**Comment by timrae** [comment]
Yes, it looks correct. I never saw that message before but I guess click Yes to reload the project and press the play button again. I think you can ignore the message about git.

**Comment by snowtimeglass** [comment]
After clicking Yes, this message is displayed.
![image](https://cloud.githubusercontent.com/assets/10436072/15090917/17d51cbe-1473-11e6-8a0f-a0f000682b0d.png)

Do I need to register something?

**Comment by timrae** [comment]
VCS stands for version control system. You can just ignore it for now.

**Comment by snowtimeglass** [comment]
> press the play button again

After pressing a play button, this error message is displayed.

![image](https://cloud.githubusercontent.com/assets/10436072/15090968/2e31fe40-1474-11e6-8665-bc66b724fb85.png)

**Comment by timrae** [comment]
If you can't get the emulator to work you can always connect your actual device

**Comment by timrae** [comment]
Did you try running "create new emulator"? It should run better if you enable virtualization (VT-x) in the bios

**Comment by snowtimeglass** [comment]
Though I probably enabled virtualization (VT-X), and create new emulator, 
the error message about virtualization is continually displayed...

![image](https://cloud.githubusercontent.com/assets/10436072/15091292/a529b758-147f-11e6-956a-93d3e8e3a58e.png)

![image](https://cloud.githubusercontent.com/assets/10436072/15091283/5f86d4c4-147f-11e6-8b1e-e6d7e1c84468.png)

![image](https://cloud.githubusercontent.com/assets/10436072/15091297/b0dbf7a0-147f-11e6-82fd-9db764a7a2e3.png)

**Comment by timrae** [comment]
Did you press F10 to save and exit after setting VT-x?

**Comment by snowtimeglass** [comment]
Of course.

**Comment by timrae** [comment]
Please open the SDK manager and check that HAXM is installed:

https://software.intel.com/en-us/android/articles/installation-instructions-for-intel-hardware-accelerated-execution-manager-windows

**Comment by timrae** [comment]
If that doesn't work I'd recommend you just plug in a physical device to your computer instead of using the Android emulator.

**Comment by timrae** [comment]
Or when you create the emulator, under system image you can choose "Other images" and one of the entries with `armeabi-v7a` listed in the ABI column. These run very slow but don't require HAXM.

![armeabi](https://cloud.githubusercontent.com/assets/2818274/15091344/da4dbe32-1481-11e6-9e0d-641a77c43b45.png)

**Comment by snowtimeglass** [comment]
>Please open the SDK manager 

I can't understand how to open it....
Where is the "SDK manager"?
![image](https://cloud.githubusercontent.com/assets/10436072/15091532/a36bd48a-1486-11e6-905d-5a32b54274a4.png)

![image](https://cloud.githubusercontent.com/assets/10436072/15091515/36bc68f4-1486-11e6-8ed3-e84b4d33fe3a.png)


Anyway, thanks to your another advice, I can play an emulator with armeabi-v7a.
![image](https://cloud.githubusercontent.com/assets/10436072/15091547/19187846-1487-11e6-92d3-40269407f808.png)

However, I can't find AnkiDroid in it...
![image](https://cloud.githubusercontent.com/assets/10436072/15091552/4af9fb32-1487-11e6-9965-2f635443d846.png)

How should I do?

**Comment by timrae** [comment]
Press the play button in android studio

**Comment by snowtimeglass** [comment]
Pressing the play button and OK button only opens the Android home screen. 
![image](https://cloud.githubusercontent.com/assets/10436072/15091741/0501e29c-148d-11e6-840c-21f9be4da38b.png)
![image](https://cloud.githubusercontent.com/assets/10436072/15091752/42053162-148d-11e6-8c02-f4a3484072b3.png)

**Comment by timrae** [comment]
Presumably there were some errors then... Did you install the SDK properly?

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#setting-up-the-sdk

**Comment by snowtimeglass** [comment]
I installed this. 
![image](https://cloud.githubusercontent.com/assets/10436072/15091797/faf58810-148e-11e6-8914-dee3470844a6.png)

I don't know whether I installed "SDK"...

**Comment by timrae** [comment]
Please read the wiki. I don't have time to hold your hand through the whole process sorry.

**Comment by snowtimeglass** [comment]
> I don't have time to hold your hand through the whole process sorry.

You are quite right in saying so. I've already been impressed with your patience.
I'm the one who should apologize.

 (On the other hand, I think the wiki doesn't seem to write more information about how to install the android SDK, though...)
![image](https://cloud.githubusercontent.com/assets/10436072/15091867/492b59ee-1492-11e6-8a52-b0858fea557f.png)

Anyway, I seem to have installed the Android SDK by intalling this Android Studio file.
![image](https://cloud.githubusercontent.com/assets/10436072/15091870/7d8fa94c-1492-11e6-9c94-0753d944354d.png)
![image](https://cloud.githubusercontent.com/assets/10436072/15091885/ea3a14f6-1492-11e6-8f2b-60aee4aeb59a.png)



 
Before Android home screen was opened, this error message was displayed.
![image](https://cloud.githubusercontent.com/assets/10436072/15091808/80cc9118-148f-11e6-9322-4d562cb1522f.png)

**Comment by timrae** [comment]
Please compile from the command line as described on the wiki and see if it's successful

**Comment by snowtimeglass** [comment]
Is this "the command line"?
![](https://cloud.githubusercontent.com/assets/10436072/15091808/80cc9118-148f-11e6-9322-4d562cb1522f.png)

**Comment by snowtimeglass** [comment]
>If that doesn't work I'd recommend you just plug in a physical device to your computer instead of using the Android emulator.

Thanks to your patient and wide-ranging advice, I managed to create a screenshot by opening the project on my physical device.

![image](https://cloud.githubusercontent.com/assets/10436072/15092267/ed812278-149f-11e6-99c0-5c36348587da.png)

**Comment by timrae** [comment]
Congratulations. How about night mode?

**Comment by snowtimeglass** [comment]
Night mode
![image](https://cloud.githubusercontent.com/assets/10436072/15092335/9b7cd2c2-14a1-11e6-955e-3fe3a77565cd.png)

(As you may notice, the color of the icon isn't pure white but faint gray)

**Comment by timrae** [comment]
Is the icon open source? Is there an svg file? If so we should be able to change it to white easily with inkscape

**Comment by snowtimeglass** [comment]
I assume it is open source as it seems to be made by Google, but I don't know for certain.
There seems to be SVG file as shown in these images.
![image](https://cloud.githubusercontent.com/assets/10436072/15092395/9190f46c-14a3-11e6-87f9-278f94048858.png)
![image](https://cloud.githubusercontent.com/assets/10436072/15092423/459e7e84-14a4-11e6-8236-68d89ef4a19a.png)
https://materialdesignicons.com/icon/eraser-variant

**Comment by timrae** [comment]
If you download the "Icon Package", inside the drawable-xxxx folders there are files with the name `ic_eraser_variant_white_24dp.png` which are pure white. Can you please take the screenshots with these?

**Comment by timrae** [comment]
The grey color gives the appearance that the icon is not in the enabled state which is bad.

**Comment by snowtimeglass** [comment]
>The grey color gives the appearance that the icon is not in the enabled state which is bad.

Of course I agree. It's just a clumsy sample.

**Comment by timrae** [comment]
This time, instead of changing the filenames, you should edit the file `Reviewer.java` (i.e. `AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java`), search for `R.drawable.ic_exposure_neg_1_white_24dp` and replace it with `R.drawable.ic_eraser_variant_white_24dp.png`

**Comment by snowtimeglass** [comment]
![image](https://cloud.githubusercontent.com/assets/10436072/15092595/67884f34-14a9-11e6-9eb9-079d43d59904.png)
![image](https://cloud.githubusercontent.com/assets/10436072/15092597/723cf1d2-14a9-11e6-81ea-1f34d1359e0d.png)
![image](https://cloud.githubusercontent.com/assets/10436072/15092618/f68570c2-14a9-11e6-9d19-0fa534eb195f.png)

(I had made screenshots before I read your last comment, so I didn't use the filename,  `R.drawable.ic_eraser_variant_white_24dp.png`.)

**Comment by timrae** [comment]
It looks pretty good.

**Comment by snowtimeglass** [comment]
Thank you for your help!
