### ISSUE TITLE
Full screen issues

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#4259]
I came across these two issues today:

1. If the whiteboard is enabled and in landscape mode, the answer buttons cannot be interacted with:
![screenshot_20160501-192630](https://cloud.githubusercontent.com/assets/789082/14941096/358d7368-0fd3-11e6-96d6-79f57502467d.png)

2. In full screen mode, if you turn off the screen and turn it back on again, the system bars appear over the content. Showing and dismissing the system bars will fix it, so it's not a major problem. Doesn't have to be in landscape but it's a lot more evident there:
![screenshot_20160501-192905](https://cloud.githubusercontent.com/assets/789082/14941100/681330d4-0fd3-11e6-9f6e-0b19081bb3fe.png)

**Comment by timrae** [comment]
Reproduced the first issue but not the second. Will fix soon.

**Comment by timrae** [comment]
Another minor issue:

In landscape mode, with swipe left gesture on, the gesture is triggered when swiping to left to show the navigation controls. All these features really don't play nicely with each other; it's turned into a bit of a nightmare, and I'm not too sure what the best way to solve everything is.

**Comment by hssm** [comment]
Would it help if we reduce the bounds of the gesture detector when in full screen so it doesn't work at the edges?

**Comment by hssm** [comment]
For the second issue I mentioned above, it seems to be an Android behavior of sorts.

I reproduced it on the emulator and narrowed it down to a lack of a lock screen when the screen is turned off (mine's set to a minute after). If I turn it back on in more than 5 seconds, it resumes correctly already in full-screen mode. If I wait any less, it resumes like the image above.

And the reason is because it doesn't call the `OnSystemUiVisibilityChangeListener` when you tap the screen when it should. If you drag from the top as if you were bringing up the status bar, the listener gets called *three times*. So something weird is going on there, but I can't be bothered looking into it any more :dizzy_face:.
