### ISSUE TITLE
After inserting SD card, anki loses collection of Decks

### ISSUE THREAD

**Issue by doonst** [ankidroid/Anki-Android#4264]
I have Android 5.1 phone with internal 16 Gb of storage. I installed Anki, downloaded a deck, started to study. All is OK. But one day I inserted an SD card. Now my decks are gone.
In Settings->Advanced, i found "Collection path", which is set to '/sdcard/AnkiDroid'
But my collection is on internal phone storage, not SD card. I don't know path to internal storage, what should I do?

**Comment by timrae** [comment]
That's weird, what device is it? Did you make any modifications to it?
I guess you'll need to browse the file system using a [file explorer](https://github.com/ankidroid/Anki-Android/wiki/FAQ#which-file-manager-should-i-use) and figure out what path it's called.

FYI: On my device the local storage is referenced by `/storage/emulated/0`

**Comment by doonst** [comment]
Device is Oukitel k4000.
I've managed to fix this problem. 
Interesting thing is, that after inserting SD card, internal storage has path /storage/sdcard1, while SD card itself has path /storage/sdcard0
So I fixed path in Anki's settings to '/storage/sdcard1/AnkiDroid' and everything works now.
Sorry for bothering you.

**Comment by timrae** [comment]
Thanks for the follow-up. That sounds like an error on the part of your device manufacturer.
