### ISSUE TITLE
Bug: Snack bar sometimes isn't displayed after a study session of a deck finishes

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4274]
This bug happens in both case "Congratulations! You have finished for now." and case "No cards are due yet".

**Comment by timrae** [comment]
You'll need to give more specific steps to reproduce

**Comment by snowtimeglass** [comment]
Unfortunately, I don't know how to reproduce it for now.
I posted this issue tentatively as it might be the case that one of developers think of the cause with little information.

**Comment by hssm** [comment]
I probably messed up something when I moved the methods around. I'll have a look at it.

**Comment by hssm** [comment]
It seems that the problem only happens on a dual-panel (tablet) layout, right? Did it used to work recently?

**Comment by snowtimeglass** [comment]
Thank you for your interest.

>It seems that the problem only happens on a dual-panel (tablet) layout, right?

No, the problem happens on my smartphone. Its layout isn't a dual-panel one .

>Did it used to work recently?

Sorry, I don't remember about it for certain, but  I feel that it began recently.

**Comment by hssm** [comment]
Would you be able to test it in 2.6alpha32 just to be certain? I've identified a problem where this issue occurs, but it's only on the dual-panel layout and the problem should have been there for a long time, so they seem to be different issues.

**Comment by snowtimeglass** [comment]
Sure, I'll test it, though it may not be a long time as I'd like to test the upcoming beta version too...

**Comment by snowtimeglass** [comment]
@hssm, this issue haven't been reproduced on 2.6alpha32 till now.
I'll use and check 2.6beta5 from now on if you don't mind.

**Comment by snowtimeglass** [comment]
This problem sometimes still happens on 2.8alpha1 with my smartphone (Android4.3).
It seems to be appropriate to reopen this issue.

Unfortunately, I don't know how to reproduce it yet.

Incidentally, when this issue happens, tapping "Undo last review" and finishing the deck again make the snack bar be displayed normally.
