### ISSUE TITLE
Replace the current tentative icon on Google Play with the new adopted icon

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4278]
![image](https://cloud.githubusercontent.com/assets/10436072/15112415/109eaa20-1629-11e6-817e-0bf00b22172e.png)

↓
     new icon
![image](https://cloud.githubusercontent.com/assets/10436072/15112687/c639abf4-162a-11e6-8f22-071124b9cef1.png)

**Comment by timrae** [comment]
I kind of like having both the one and two star versions

**Comment by snowtimeglass** [comment]
I sympathize you as I strongly supported the two star icon, but far more users supported the one star icon on [the poll](https://groups.google.com/forum/#!topicsearchin/anki-android/poll$20AND$20icon/anki-android/GUJZqmH2yWs). 


![image](https://cloud.githubusercontent.com/assets/10436072/15113464/6981c950-162f-11e6-8ab7-e187c4fcc85e.png)

The new one star icon on Google Play will attract more people than current one does.
It also has consistency with the app icon of AnkiDroid.
So, at least on Google Play, the new one star icon should be used, shouldn't it?

You can use the two star icon on other places, e.g. Wiki, Help page.

**Comment by hssm** [comment]
I agree with you about consistency. 

Also [the docs](https://support.google.com/googleplay/android-developer/answer/1078870) seem to suggest using the same image as your icon, but a higher quality one:

>High-res icon
To publish your store listing, a high-res icon is required. The high-res icon does not replace your app's launcher icon, but should be a **higher-fidelity, higher-resolution version** that follows the same design guidelines.

**Comment by hssm** [comment]
I uploaded a new version.

There are two other graphic assets that could use an update. @snowtimeglass if you are interested in creating something for these (following the guidelines from the link in my earlier post) then feel free to have a go at it. You can use the files in [`/Anki-Android/docs/graphics/src/`](https://github.com/ankidroid/Anki-Android/tree/develop/docs/graphics/src).

![play_store_graphics](https://cloud.githubusercontent.com/assets/789082/15259240/64185e68-1993-11e6-8eda-8e776258434e.png)

**Comment by snowtimeglass** [comment]
Thank you!
