### ISSUE TITLE
2.6beta1 crashes on Android 2.3.7 when changing deck options

### ISSUE THREAD

**Issue by bigsmile01** [ankidroid/Anki-Android#4279]
2.6beta1 crashes on Android 2.3.7 when changing deck options.
The change will be applied, but the app crashes. 

P.s. I hope this is the right place for beta bugs. I searched around and it seems to be, but sorry if it is not!

**Comment by hssm** [comment]
I couldn't reproduce it. Can you please provide the exact steps taken?

**Comment by bigsmile01** [comment]
On AnkiDroid main screen

1. Tap and hold on a deck name to display the menu
2. Select Deck options
3. Tap on the "options group" menu
4. Select a new option in the "Options group" menu
5. The app will now crash.

**Comment by hssm** [comment]
I still cannot reproduce it. Would you be able to send me a copy of your collection? There might be something specific that is triggering it.

Two more things:
1 - Have you tried doing this on another device or Android version?
2 - Is this a new problem that only happens in the beta? What was the last version where you know this didn't happen?

**Comment by bigsmile01** [comment]
Thanks for replying. 

How do I send you my collection?

1 - I only have access to Android 2.3.7
2 - The previous version (before 2.6beta1) worked perfectly.

**Comment by timrae** [comment]
> The previous version (before 2.6beta1) worked perfectly

I assume you're talking about v2.5.4 which was released on 2015-12-14 rather than 2.6alpha37 which was released a few days ago?

**Comment by bigsmile01** [comment]
I am on the beta channel (as I had a problem ages ago and someone suggested I used the beta, so I could report any bugs that occur on Android 2.3.7, as apparently they aren't a lot of people testing on that version of Android).

So I think it would be 2.6alpha37. Is there a way to re-install it double check?

**Comment by timrae** [comment]
The alpha channel and beta channel are separate, so it's probably 2.5.4.

I am on the beta channel (as I had a problem ages ago and someone suggested
I used the beta, so I could report any bugs that occur on Android 2.3.7, as
apparently they aren't a lot of people testing on that version of Android).

So I think it would be 2.6alpha37. Is there a way to re-install it double
check?

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/4279#issuecomment-219025451>

**Comment by hssm** [comment]
If you want to sent it privately you can click on my name and you'll find my email on the account page.

**Comment by bigsmile01** [comment]
@hssm In Anki, do I just export my decks as apk files? I've got 25+ decks, so will that be too many to send?

@timrae I didn't install 2.6beta1 by myself, it updated automatically. Does that mean I am on the beta channel.

**Comment by timrae** [comment]
@bigsmile01

You can just do "export collection" from the app bar menu on the right in the decks screen to export everything in one go. You don't need to include the media but you should include scheduling.

>  I didn't install 2.6beta1 by myself, it updated automatically. Does that mean I am on the beta channel.

Yes.

**Comment by bigsmile01** [comment]
@hssm Sorry for the delay. I have emailed you my collection. 

The new beta updated to day by itself (2.6beta2), but the issue remains.

**Comment by hssm** [comment]
Thanks for sending me your collection. I have reproduced the issue and put in a fix for it.
