### ISSUE TITLE
Bugic in statistic screen 

### ISSUE THREAD

**Issue by cladsam** [ankidroid/Anki-Android#4280]
After I completed the review of a deck, I used to unbury aller cards that were and review them. Since, the "type of card " statistic circle appears all black color. Even for old cards.  No more green coloris.

**Comment by timrae** [comment]
Please try the 2.6 beta version
https://ankidroid.org/docs/manual.html#betaTesting

**Comment by aphirst** [comment]
I'm experiencing the same issue, currently running 2.8.2 from the Play Store on Android 6 (CyanogenMod).

![photo_2017-07-12_17-53-02](https://user-images.githubusercontent.com/1735556/28129374-fbabb2d0-672a-11e7-9004-3801fdc0dca1.jpg)

Feel free to let me know if there's any additional info you need.
