### ISSUE TITLE
Running database check unburies cards

### ISSUE THREAD

**Issue by kuklinistvan** [ankidroid/Anki-Android#4290]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Add a note to be asked in both directions
2. Practice the note

###### Expected Result

Anki asks all the cards related to that note - in both languages if it is a word, for example.

###### Actual Result

Anki forgots one of the cards and skips it. If I ask it to check the database it realizes that there is still one card left. It also happens if I don't check the database just launch it after a couple of hours.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.5.4

Android Version = 4.2.2

ACRA UUID = 5f49a838-5588-44f7-9ae7-cf50a00e2378

**Comment by timrae** [comment]
Hi you refer to "Anki" rather than "AnkiDroid" so I assume the same behavior happens in Anki Desktop...? In this case it's not "a bug or enhancement request specific to AnkiDroid" and you should post to the Anki desktop support site.

However, it sounds like you might just be confused about the [sibling burying feature](http://ankisrs.net/docs/manual.html#siblings-and-burying)?

**Comment by kuklinistvan** [comment]
I'm sorry, it is related to AnkiDroid and please excuse me my lack of knowledge, although I have spent time for looking for this function in the manual. In this case, should it come over when I let the the database checked?

**Comment by kuklinistvan** [comment]
According to the manual it should be unburied on the next day, however, for me it happens after a couple of hours.

**Comment by timrae** [comment]
What behavior do you observe with Anki Desktop?

**Comment by kuklinistvan** [comment]
I've just tested: in the desktop version my card got buried as expected and checking the database doesn't make my buried card overcome.
I have also noticed that on the mobile version the counter near the top of the screen skips a couple of steps when AnkiDroid skips the card I'm talking about.

**Comment by timrae** [comment]
Thanks for checking, I changed the title of the bug report.

**Comment by kuklinistvan** [comment]
Thank you for your help!

**Comment by kuklinistvan** [comment]
This bug seems gone for me in AnkiDroid version 2.6
