### ISSUE TITLE
Some kanji won't display correctly

### ISSUE THREAD

**Issue by lucnbernier** [ankidroid/Anki-Android#4294]
1. When I study those kanjis (誤直径), it will display correctly on my PC but not on my phone.
2. I tried this : https://github.com/ankidroid/Anki-Android/issues/3023 but it is not working, I still get the same issue.
3. Phone is a Zenfone2 from Asus. 

Thanks

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#how-can-i-use-custom-fonts
