### ISSUE TITLE
Bug: "Undo bury card" doesn't return the screen to the review screen, while "Undo last review" does

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4312]
###### Research

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. Choose "Bury card" on the **last** card on a deck. (Then, The deck list screen is displayed.)
2. Choose "Undo bury card". 
###### Expected Result
- ~~The left, blue number "0" would be changed to "1" immediately.~~
- The study screen with the card is displayed again, just as it is done when the last card is answered and then you chose  "Undo bury card".
###### Actual Result
- Nothing happens on the screen.
  (The left, blue number "0" won't be changed unless another screen (ex. the deck overview screen, the home screen of Android) is displayed and then the deck list screen is displayed again.)
###### Debug info
- AnkiDroid Version = 2.6beta5
- Android Version = 4.3
- ACRA UUID = fd8403ae-e917-4e3e-bc95-317d23a27ca3

**Comment by snowtimeglass** [comment]
@dwcheng #4322
>The bug report said that the card counter should be updated, but I thought it would be more consistent if it behaved the same way as undoing a review.

I agree with you, so I changed the title of this issue.

**Comment by david-allison-1** [comment]
Reproduced in 2.11alpha12

**Comment by farjadilyas** [comment]
@david-allison-1 Can I work on this as a first issue?

**Comment by david-allison-1** [comment]
Sure! Make sure it's still reproducible

**Comment by Arthur-Milchior** [comment]
It works on tablet. It fails on small screen, when "undo" is in the deck picker. However, when "undo" is in overview it works. There is probably something that can be taken from the overview and be used in deck picker.

Note that the same problem appear with the "suspend" action

**Comment by dae** [comment]
@snowtimeglass does this issue still exist?

**Comment by snowtimeglass** [comment]
@dae thank you for your interest. I think this issue doesn't exist on the new backend and the v3 scheduler.

Tapping "Undo Bury" changes a number of the counts from "0" to "1" immediately, as well as when I tap "Undo Answer Card". The "Undo Bury" operation doesn't bring the user back to the review screen, but the result is consistent with the case of "Undo Answer Card".

###### Debug info
```
AnkiDroid Version = 2.16.4 (67fd45a351c44c46c844aa35a402b98a2a487f68)

Android Version = 11

ProductFlavor = full

Manufacturer = OPPO

Model = CPH2013

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; CPH2013 Build/RKQ1.200903.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/115.0.5790.166 Mobile Safari/537.36

ACRA UUID = b5511134-4c2d-42a7-a741-74a98eb5e60a

New schema = true

Scheduler = std3

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```
