### ISSUE TITLE
Delete the description of donation on "About AnkiDroid"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4313]
How about deleting the description, as long as there is no description of donation on the support page of Anki Desktop?

![image](https://cloud.githubusercontent.com/assets/10436072/15799421/0b5f8f20-2a97-11e6-993f-00ddbda04417.png)

**Comment by snowtimeglass** [comment]
The description of donation still exists on 2.6.1beta1

**Comment by hssm** [comment]
It's part of the string so the translations need to be updated.

**Comment by snowtimeglass** [comment]
I expected that the following current string, which include the description of donation, would be discacrded and a replacement would appear, but the former string still exists on Crowdin as follows.
![image](https://cloud.githubusercontent.com/assets/10436072/16545617/4e9613aa-416b-11e6-9081-688cef25cb8f.png)

Should I translate the current string, disregarding the description of donation?

**Comment by hssm** [comment]
I guess we haven't pushed the latest strings to crowdin yet. You can make that change if you want, there's no harm in doing it, but I don't think it's such an important thing to worry about anyway.

**Comment by timrae** [comment]
That's strange, I did a sync to crowdin yesterday... perhaps I was on the wrong branch :-/
I just did the sync again and now the strings are updated as expected

**Comment by snowtimeglass** [comment]
Thank you. These are indeed what I want.
