### ISSUE TITLE
Replace the out-of-date "Feature Graphic" on Google Play with new one with the new icon

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4315]
The combination of the following icons is odd.
Would you please update it?

![image](https://cloud.githubusercontent.com/assets/10436072/15799612/2aaabd7c-2a9d-11e6-97b5-fdbcedcabb4e.png)

**Comment by snowtimeglass** [comment]
@hssm 

> @snowtimeglass if you are interested in creating something for these (following the guidelines from the link in my earlier post) then feel free to have a go at it. You can use the files in /Anki-Android/docs/graphics/src/. (#4278)

Would you please tell me where the following Hi-res icon is? I can't find it in  [`/Anki-Android/docs/graphics/src/`](https://github.com/ankidroid/Anki-Android/tree/develop/docs/graphics/src)

![image](https://cloud.githubusercontent.com/assets/10436072/16543471/9508dfe8-4111-11e6-8f3b-7f37cfd78f67.png)

**Comment by hssm** [comment]
That image is generated from `anki.svg`. We don't store the exported .pngs anywhere.

Also there is [this thing](http://www.norio.be/android-feature-graphic-generator/).

**Comment by snowtimeglass** [comment]
Thank you. I understand.

a trial
![ankidroid -feature-graphic 2](https://cloud.githubusercontent.com/assets/10436072/16562158/6109369e-4237-11e6-83b3-643c28a02b17.png)

**Comment by timrae** [comment]
That looks nice

**Comment by hssm** [comment]
Yeah it's really crisp, I like it. Did you intend to improve it some more? I'm fine with using it as it is, if you'd like.

**Comment by timrae** [comment]
I just changed it on Google Play, let's see how it looks

**Comment by timrae** [comment]
![screenshot 5 jul 2016 13-46-54](https://cloud.githubusercontent.com/assets/2818274/16574191/2713f2be-42b7-11e6-876b-0623387e0378.png)

**Comment by eginhard** [comment]
Looks great :)

**Comment by snowtimeglass** [comment]
Thank you developers for the positive comments :)
I'm so glad.

>Did you intend to improve it some more?

Yes, at first, I made it just to inform you that I understood the basic of the tool,
but, to tell the truth, I also like it now.

I also feel it looks good on Google Play.
I think it'll do at least for the time being.

However, for now, there is one thing which bothers me a little. 
The "Play video" button on Google Play covers the last letter "d" on my devices.
![image](https://cloud.githubusercontent.com/assets/10436072/16587379/584f2a9e-4305-11e6-9efd-6d115bf55137.png)

@timrae 
Please try the following image instead of the current one.
![image](https://cloud.githubusercontent.com/assets/10436072/16587542/13aff43a-4306-11e6-82a5-fed8f87299c0.png)

![image](https://cloud.githubusercontent.com/assets/10436072/16587323/145f1a6a-4305-11e6-8274-2bafc708452a.png)

**Comment by timrae** [comment]
OK I just updated it, it'll take a few hours to be processed though.

**Comment by snowtimeglass** [comment]
Thank you. It has been improved, I think.
![image](https://cloud.githubusercontent.com/assets/10436072/16590220/a08a4c42-4311-11e6-95e8-b910573cd889.png)

I'm sorry to trouble you, but I would like to check the following version, which shift to left one more step. 
![image](https://cloud.githubusercontent.com/assets/10436072/16590306/fda6fa38-4311-11e6-95f5-b2f72644d0b0.png)
_AnkiDroid-feature-graphic 4_

**Comment by timrae** [comment]
Done

**Comment by snowtimeglass** [comment]
Thank you.
On my devices, the position of the last version is the best.
 ![image](https://cloud.githubusercontent.com/assets/10436072/16616790/92203992-43ba-11e6-8cbc-fad645dab7c4.png)

I would like to select this graphic, if it's OK with you participants.

**Comment by timrae** [comment]
:+1:

**Comment by timrae** [comment]
Do you have an svg file for the new graphic?

**Comment by snowtimeglass** [comment]
No, I don't know how to make an svg file...

um...I've just tried it with [this on-line converter](https://convertio.co/ja/png-svg/). 

Unfortunately, maybe I failed.
[AnkiDroid-feature-graphic-4.svg (zipped)](https://github.com/ankidroid/Anki-Android/files/349768/AnkiDroid-feature-graphic-4.zip)

**Comment by snowtimeglass** [comment]
By the way, The settings of the background of the new graphic are [**here**](http://www.norio.be/android-feature-graphic-generator/?config=%7B%22background%22%3A%7B%22color%22%3A%22%2386c2ff%22%2C%22gradient%22%3A%7B%22type%22%3A%22radial%22%2C%22radius%22%3A%22890%22%2C%22angle%22%3A%22vertical%22%2C%22color%22%3A%22%230062c4%22%7D%7D%2C%22title%22%3A%7B%22text%22%3A%22AnkiDroid%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%2C%22position%22%3A100%2C%22color%22%3A%22%23ffffff%22%2C%22size%22%3A192%2C%22font%22%3A%7B%22family%22%3A%22sans-serif%22%2C%22effect%22%3A%22bold%22%7D%7D%2C%22subtitle%22%3A%7B%22text%22%3A%22Flashcards%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%22%2C%22color%22%3A%22%23ffffff%22%2C%22size%22%3A126%2C%22offset%22%3A0%2C%22font%22%3A%7B%22family%22%3A%22sans-serif%22%2C%22effect%22%3A%22normal%22%7D%7D%2C%22image%22%3A%7B%22position%22%3A%220%22%2C%22file%22%3A%7B%7D%7D%2C%22size%22%3A%22feature-graphic%22%7D), for your information.
![image](https://cloud.githubusercontent.com/assets/10436072/16618906/b29de3fc-43c6-11e6-8497-a2a5e232e6a5.png)

Then, I selected [`anki.svg`](https://github.com/ankidroid/Anki-Android/blob/develop/docs/graphics/src/anki.svg) on "Image", as you know.

![image](https://cloud.githubusercontent.com/assets/10436072/16619073/86b8c29c-43c7-11e6-9cae-020611509c79.png)

![image](https://cloud.githubusercontent.com/assets/10436072/16619315/9618ee78-43c8-11e6-9ac7-8777939d9543.png)
