### ISSUE TITLE
Add Japanese subtitles to the tutorial video

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4316]
Shall I translate the English subtitles?

 ![image](https://cloud.githubusercontent.com/assets/10436072/15803294/63d49374-2b11-11e6-829d-b6023d6b734e.png)

**Comment by hssm** [comment]
If you're up for it, sure.

**Comment by snowtimeglass** [comment]
Certainly, I'll be up for it.

Could I get a text file of the English subtitles?

**Comment by hssm** [comment]
I'm pretty sure they are automatically generated by YouTube. I'm not sure if there is a way to download them. You'll have to have search around.

**Comment by snowtimeglass** [comment]
There are subtitles which are automatically generated by YouTube, 
![image](https://cloud.githubusercontent.com/assets/10436072/15804083/6205512a-2b37-11e6-9e19-5d6529235aab.png)
![image](https://cloud.githubusercontent.com/assets/10436072/15804063/97bf0e10-2b36-11e6-8da8-324e05c6ad7b.png)

but the subtitles we are talking about now aren't automatic one.
![image](https://cloud.githubusercontent.com/assets/10436072/15804078/15e36660-2b37-11e6-9ccc-ca94adaa4ede.png)

Of course, I can translate it without the text file, but writing Japanese texts next to English ones would be a bit more helpful for a video editor, I think.

**Comment by timrae** [comment]
Oh doesn't youtube let you download the transcript? Here it is.
[transcript.txt](https://github.com/ankidroid/Anki-Android/files/299241/transcript.txt)

**Comment by snowtimeglass** [comment]
@timrae thank you for the file, but is it really normal condition?
I imagined each subtitle being listed in order...

![image](https://cloud.githubusercontent.com/assets/10436072/15804320/02224b84-2b3f-11e6-93de-26e6488fcfba.png)

**Comment by timrae** [comment]
Maybe try opening with notepad++

**Comment by snowtimeglass** [comment]
Thank you! 
I can open it properly with WordPad.
![image](https://cloud.githubusercontent.com/assets/10436072/15804341/cbd1e96c-2b3f-11e6-8b9d-4659c51556e1.png)

**Comment by snowtimeglass** [comment]
Does the narrator say "so that we can review both directions" on [3:02](https://youtu.be/F2K1gOSdIZA?t=180)?

There is no subtitle in this point.
Is it intentional?

**Comment by timrae** [comment]
Probably unintentional

**Comment by snowtimeglass** [comment]
Is it easy for you to fix it if you have enough time? 
I know you are probably too busy to fix such a trivial mistake, so I have no intention to say that you should fix it, though.

**Comment by snowtimeglass** [comment]
Will it be better for me to skip that point on my translation?

**Comment by snowtimeglass** [comment]
I've translated the subtitles.
Please feel free to use the following file.

[Translation of ankidroid_turorial_video.xlsx](https://github.com/ankidroid/Anki-Android/files/344541/Translation.of.ankidroid_turorial_video.xlsx)

**Comment by timrae** [comment]
I think you can add them yourself....? I thought I made it public

**Comment by snowtimeglass** [comment]
Sure. I'll try it, though this may take a while.

**Comment by snowtimeglass** [comment]
I've added the translation with the tool of YouTube, and just sent it to the YouTube community, which check it.

**Comment by snowtimeglass** [comment]
@timrae 
Could you approve and publish my submission?
The review progress by YouTube community members takes far more time than I'd expected...

![image](https://cloud.githubusercontent.com/assets/10436072/23577151/4abfbbf0-00fb-11e7-8854-3ddfa25054fd.png)
https://support.google.com/youtube/answer/6052538?hl=en

**Comment by timrae** [comment]
done

**Comment by snowtimeglass** [comment]
Thank you!
