### ISSUE TITLE
Bug: The title and numbers of the scale disappear on "HOURLY BREAKDOWN"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4317]
![image](https://cloud.githubusercontent.com/assets/10436072/15803551/85c1902e-2b1e-11e6-8f59-56ba2221c144.png)

The same goes for "WEEKLY BREAKDOWN".

**Comment by jvanprehn** [comment]
Sorry for breaking this... I just noticed that I also broke something in advancedstatistics in my last commit :(...
