### ISSUE TITLE
Do not play translation sound in the answer (only in two devices) 

### ISSUE THREAD

**Issue by fbrubbo** [ankidroid/Anki-Android#4320]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Do not play the recorded translation sound anymore 
2 . it works on desktop and my tablet. But not on my smartphone anymore 

Even when the sound is recorded in the front of the card it does not play 

###### Expected Result

Play the sound whenever the back of the card is shown. 

###### Actual Result

No sound is played. 
It started to happen recently after a sync error saying it was not possible to unzip. Or something like that. Thus error happens whenever sync takes place. But cards and stats sync as expected. 

###### Debug info

AnkiDroid Version = 2.5.4

Android Version = N

ACRA UUID = c6aad136-c341-40e1-9b5e-fcb5ee69045e

**Comment by fbrubbo** [comment]
The zip error is. 

ZipException : no such file or directory. 

A report is being sent to developers. 

__
Probably you have the full stack trace in your console.

**Comment by hssm** [comment]
https://github.com/ankidroid/Anki-Android/issues/4197

**Comment by fbrubbo** [comment]
Looks like the ZipException is the Android N problem, once I am running it on my  Nexus 6P. However, the not playing sound  is also happening on my Moto X Play. Nevertheless, it is working just fine in my old and good Nexus 7. 

Hope these info help you guys track down the issue. Let me know if you need anything else. 

Thanks for building anki
