### ISSUE TITLE
Sync held up by "Finding changed media"

### ISSUE THREAD

**Issue by glutanimate** [ankidroid/Anki-Android#4323]
###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. Make sure you have a note collection with lots of media files
2. Sync multiple times while adding or modifying notes on your desktop in between. Don't add or remove any media files while doing so.
###### Expected Result

Quick sync within less than 3 seconds each time.
###### Actual Result

Sync getting stuck on "Finding changed media" after a few syncs, despite no apparent changes to the media directory. When this happens the sync can take up to several minutes.
###### Debug info

Tested and reproduced on all beta versions of AnkiDroid 2.6 so far, but I'm pretty sure I was also running into this on 2.5.x every now and then. I've also made sure to check this on multiple different internet connections to rule out connectivity issues as the root cause.

Might be related to #3120.

**Comment by hssm** [comment]
Can you email me the file named `collection.log` from your AnkiDroid directory? It should provide clues about what is going on. The file has your email address so you probably don't want to post it publicly.

**Comment by Glutanimate** [comment]
Thanks for taking a look at this, @hssm. I just sent you a mail with the logfile and a description of the corresponding actions I performed.

**Comment by david-allison-1** [comment]
This still occurs. Rather serious

**Comment by theWalkingMedico** [comment]
I'm having a similar problem 
It gets stuck in Finding Changed Media 
And the sync button still shows a red dot after multiple syncs

**Comment by dae** [comment]
Should be fixed in the backend switchover.
