### ISSUE TITLE
phonetic symbol？（ankidroid ）

### ISSUE THREAD

**Issue by 140619** [ankidroid/Anki-Android#4324]
compensate	<B><FONT size=4>compensate</FONT></B><BR><FONT color=#797979 face="Kingsoft Phonetic Plain, Tahoma">/5kCmpEnseit/</FONT>

like this?
How to modify ？*.ttf

**Comment by hssm** [comment]
I have no idea what this means. The issue tracker is not for support queries. Provide more details about your problem on the [forums](https://groups.google.com/forum/#!forum/anki-android) and you might have better luck.
