### ISSUE TITLE
Clear entire whiteboard with one click

### ISSUE THREAD

**Issue by kohanyirobert** [ankidroid/Anki-Android#4327]
AnkiDroid 2.6 modified the behavior of the clear whiteboard button. Previously it cleared the entire whiteboard (what I'd like to have back), now it removes the last stroke.

I'm studying Kanji with the whiteboard and  for me it doesn't make sense to clear the last stroke. It's easier to write the whole thing again. That would happen when writing with a pen anyway.

Make it configurable in the settings please. Thank you. Maybe make long press clear the whole board or something.

**Comment by timrae** [comment]
https://groups.google.com/forum/m/#!topic/anki-android/XHmBt_0OAos

**Comment by kohanyirobert** [comment]
Thanks!

**Comment by kcroker** [comment]
This is good stuff.  Please consider putting things like this in the CHANGELOG/README next time?  I apologize if I have overlooked!
