### ISSUE TITLE
Deck statistics to Excel

### ISSUE THREAD

**Issue by dcampezano** [ankidroid/Anki-Android#4328]
* First, Sorry for my poor English.
I need to use a lot of subdecks for a exam and reutilize for others exams that I do.
So I want to export statistics of all my decks to excel , and there do my organization.

![capturar](https://cloud.githubusercontent.com/assets/12243856/16082227/04c16d7a-32e7-11e6-923e-ed549fc177ce.PNG)

Is it possible with any addon's?

**Comment by eginhard** [comment]
This project is only for issues related to AnkiDroid, which is developed independently from the other Anki versions. Please refer to the main Anki forum: https://anki.tenderapp.com/discussions
(There is no way to export these statistics in AnkiDroid)

**Comment by dcampezano** [comment]
I apologise for this. Thank you.
