### ISSUE TITLE
Feature Request: Dual Window compatibility

### ISSUE THREAD

**Issue by AlexioXela** [ankidroid/Anki-Android#4329]
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Feature Request

It would be nice if Dual Window mode could work with AnkiDroid. I know nothing about programming, but I've seen people say online that it's typically a pretty easy implementation. 

I'm thinking about using dual mode primarily so I can type out answers (for if the answer is too long for the built-in "Checking Your Answer" feature to work well) or draw the answer (for when scrolling through long cards with the whiteboard feature can be annoying) in a different application and manually compare my answer to the correct answer .

**Comment by mikehardy** [comment]
I just checked and current stable (2.8.4 at the moment) supports split screen
