### ISSUE TITLE
Android 2.3.x crash :: android.os.BadParcelableException: ClassNotFoundException when unmarshalling

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4330]
```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker}: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: android.support.v7.widget.RecyclerView$SavedState
```

https://ankidroid.org/couchdb/acralyzer/_design/acralyzer/index.html#/reports-browser/ankidroid/bug/cb546ddd860763218e06dfac9ccff066

It appears to have been [fixed with v24 of the support library](https://code.google.com/p/android/issues/detail?id=196430) :-/

**Comment by hssm** [comment]
I don't know what to do with these support libraries anymore. I'm tempted to just go with the latest one and reintroduce the FAB issue. It should be fairly limited in scope anyway from what I gather.
