### ISSUE TITLE
all fields turned red

### ISSUE THREAD

**Issue by sibilek** [ankidroid/Anki-Android#4333]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. I was entering new words to a deck with my note type. I enter "convince" and it's meaning
2. After entering some other words with same note type to the same deck, accidentally I enter "convince" again. By the way first field's bottom line turned red but I was kinda making it quickly so I didn't realize it and I hit OK button located up right.
3. Anki added "convince" again and then all fields bottom lines turned red.

###### Expected Result
To act normally
Note: I think for a situation like this the matching first field which was turning completely pink/red was better like in the early versions. Like in my situation bottom line which is turning to red sometimes can't be noticed because it's so little to realize and when in the first field entering an existing word in the deck bottom line turns to gray which is covering  the red line like in picture.

###### Actual Result
When I was entering new words to a deck, I accidentally add same word twice. And then alI fields turned to red.
![screenshot_2016-06-16-13-38-56](https://cloud.githubusercontent.com/assets/11895544/16192388/aca56696-36f1-11e6-828c-787083485b31.jpg)
![screenshot_2016-06-16-13-39-07](https://cloud.githubusercontent.com/assets/11895544/16192395/b6754b50-36f1-11e6-9ffb-a690cb1a4aaf.jpg)
![screenshot_2016-06-16-13-38-25](https://cloud.githubusercontent.com/assets/11895544/16192407/c8637012-36f1-11e6-8644-0edc3a37f7d3.jpg)

![screenshot_2016-06-20-14-22-24](https://cloud.githubusercontent.com/assets/11895544/16192537/8fd2821e-36f2-11e6-837c-44497af38a85.jpg)

###### Debug info
AnkiDroid Version = 2.6

Android Version = 5.0

ACRA UUID = bff7e18d-3056-4ce7-b037-e3fa06fb7462

**Comment by hssm** [comment]
I couldn't reproduce this problem. If you can make it happen every time then please send me your collection so I can try it myself.

**Comment by sibilek** [comment]
It happens every time. You can see in YouTube video also
https://youtu.be/s8NJW0Z9T2I

and here is the link for this deck

https://drive.google.com/file/d/0B1UpSK4YWhHJSDNBbmlrb2VmWHM/view?usp=drivesdk

I couldn't reproduce this problem. If you can make it happen every time
then please send me your collection so I can try it myself.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/4333#issuecomment-227229965>,
or mute the thread
<https://github.com/notifications/unsubscribe/ALWC-I2rEtZ4lcGQwddGuFhzNzetfRmTks5qNt2pgaJpZM4I5muH>
.
