### ISSUE TITLE
Initial Picture tutorial enhancement for new users

### ISSUE THREAD

**Issue by sibilek** [ankidroid/Anki-Android#4334]
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

I have recommended Anki to many of my friends. Most of those people are not familiar with Anki and common reply I get from them "Okay! this is empty". So I thought it would be good if a initial tutorial, which will walk through new user in the app, appear for one time when installed for the first time. So I made some preparations with pictures. I really know these pics are so amateur. I hope you like it.
I really want to contribute to AnkiDroid development.  I am so curious about helping but I have lack of developing ability. right now it's a bit higher than my ability. but I will take a look to online courses. I hope I can learn.
1. Most of new users don't know about SRS. So I thought it will be good to give quick info.
2. Most of new users don't know about sync option.

BTW I made these pics with PicsArt https://play.google.com/store/apps/details?id=com.picsart.studio

![anki tutorial01](https://cloud.githubusercontent.com/assets/11895544/16204429/62bf291e-3727-11e6-92a9-384c5fdc1f9d.jpg)
![anki tutorial02](https://cloud.githubusercontent.com/assets/11895544/16204438/700c15f0-3727-11e6-959b-62069adbe308.jpg)
![anki tutorial03](https://cloud.githubusercontent.com/assets/11895544/16204443/7ed2fc34-3727-11e6-9e48-d2bc7fd802aa.jpg)
![anki tutorial04](https://cloud.githubusercontent.com/assets/11895544/16204457/8f0aa836-3727-11e6-989c-44d4bd229a81.jpg)
![anki tutorial05](https://cloud.githubusercontent.com/assets/11895544/16204463/9837d96a-3727-11e6-8b0f-89fe046a51ae.jpg)
![anki tutorial06](https://cloud.githubusercontent.com/assets/11895544/16204491/be4dc72c-3727-11e6-9393-8342f0dfe143.jpg)
![anki tutorial 07 01](https://cloud.githubusercontent.com/assets/11895544/16204503/d24501aa-3727-11e6-9711-8de9f8bc356b.jpg)

**Comment by JaysonH91** [comment]
I think this would be very handy. I m new to anki & Android dev, but think this would be interesting to take up

**Comment by hssm** [comment]
If you are interested in working on it, have a look at something like [AppIntro](https://github.com/PaoloRotolo/AppIntro). There is a large list of applications that make use of the library that you can use for inspiration. I would encourage you to look at what other apps do and try to copy them.

**Comment by sibilek** [comment]
Thank you Jayson and Houssam. These pictures are my first thoughts. Like
sketches. I hope and sure you will come up with more brilliant ideas. And I
am looking forward to join coding and development process.

Have a nice day

Sinan Bilek
20 Haz 2016 23:24 tarihinde "Houssam Salem" <notifications@github.com>
yazdı:

**Comment by timrae** [comment]
:+1:

**Comment by Kartikkman** [comment]
@mikehardy @timrae 

This issue seems very much interesting to me , Can I take this up please ( if it is not completed yet  or anyone else is not working on this ) ?? 
Please put some of your views for this , How should I begin with this issue ?? 

Thank You 
@mikehardy @timrae

**Comment by Kartikkman** [comment]
@mikehardy , Any suggestions on this ??

**Comment by timrae** [comment]
Sure, please feel free to take it up! Following on from what has already been done here, and following up on hssm's recommendation mentioned in this thread would be a good way to get started

https://github.com/ankidroid/Anki-Android/issues/4334#issuecomment-227258427

**Comment by Kartikkman** [comment]
Thanks @timrae @mikehardy  !!! 
I am now starting to work upon this , Will be posting updates & queries for this thing !! 

-I am beginning with the Library  ( will make another small app to test this on  or what do you say ? )
- start looking on the other apps implementation  ( ones which I have in my mind as of now is nRF Connect  , others you please suggest !!! )

**Comment by Kartikkman** [comment]
Just wanted to ask , does Anki-Ankroid supports Android X ??

**Comment by Kartikkman** [comment]
Hii @mikehardy , 

I am sorry for mis-understanding , By the above I meant this : 

Written on AppIntro Github Page : 

[https://github.com/AppIntro/AppIntro](https://github.com/AppIntro/AppIntro)

Add the dependency
Please note that AppIntro supports Android X. If you haven't migrated yet, you probably want to use a previous version of the library that uses the old Support Library packages (or try Jetifier Reverse mode).

By AndroidX , I meant : 

StackOverflow : 

AndroidX is a redesigned library to make package names more clear. So from now on android hierarchy will be for only android default classes, which comes with android operating system and other library/dependencies will be part of androidx (makes more sense). So from now on all the new development will be updated in androidx.

Again , So sorry for miscommunication !!

**Comment by Kartikkman** [comment]
@mikehardy 

![AppIntro_Ankidroid](https://user-images.githubusercontent.com/28975022/63883302-8d833b80-c9f1-11e9-8ab7-ba0174616b0b.png)

I just tried , setting up library & using its minimalist features ( it works like a charm !! ) 

- I still need to use fragments with this ( first need to learn fragments though  !!!!! :/ ) 
- Decide on What content to put on these App Intro Screens 
- Need to Decide on Best Colors to fit for these 
- Apply Shared Preferences for above ( so that it only runs when user logs into app first time  and 
we can ( if you wish ) add Tutorial option on Navigation Drawer so user can watch tutorial an time  ?? 

Well lots to decide on !! . Will be proceeding with first step  , whats your say on this ?? 
@mikehardy 

Thanks 
Kartikkman

**Comment by Kartikkman** [comment]
Hey @mikehardy , Here is what I could do ( I believe that we can a wayyy lot better than this , but I just came with this as of now ) . 


[Video Link ](https://drive.google.com/open?id=1tG_EzqhqCMqvYQnlr0UwCQhnegEmWaGt)

I would be happy to rework on this . Please put your suggestions . 

Thank You @mikehardy

**Comment by mikehardy** [comment]
I requested access for it because it's not public on google drive - could you make it completely public or maybe push it up to youtube? (just in case, so everyone can see it?) :+1:

**Comment by Kartikkman** [comment]
Hey @mikehardy , Just Gave Access , anyone with link can view . 

Sorry for issue !!

**Comment by mikehardy** [comment]
I think it's a good start - I would love to see the ankiweb registration / search for deck / download deck / import deck part if you can take some screenshots of that and show them. Helping people get lots of free content immediately would answer most of the first-time questions we get where people have no idea where to start, then if you also showed them using it to sync, it would fix the other major category of questions we get: I lost my cards :-)

**Comment by Kartikkman** [comment]
Hi @mikehardy , 
Here is Video on search for deck / download deck / ankiweb registration / Sync Changes

[Download Deck ](https://drive.google.com/file/d/1NY_mTfs3zbO1mn-SvoJcrD9ezdyQuop5/view?usp=sharing)

[Syncing Changes ](https://drive.google.com/file/d/1-G3Qj9FzkFZLT3zfQswr0sqa2EDQXwfH/view?usp=sharing)

[Login AnkiWeb ](https://drive.google.com/file/d/1bgETWrSVIZlUM9Piyff144gbcu21uzqP/view?usp=sharing)

[SignUp](https://drive.google.com/file/d/1U8YN8KgN28X84xKd35S0FDuyUmgwDPpc/view?usp=sharing)

**Comment by mikehardy** [comment]
Well definitely only use fresh test accounts for posting videos of login and signup - for security reasons. I edited your comment to remove the link to the login video because that shows your gmail account and people can watch the password etc.

I like the videos but distributing video with the app will increase it's size.

If we were able to post these on youtube (like the introduction video we use for the Play Store listing) then use a webview in the tutorial with an iframe that embedded the youtube links [like this example](https://www.viralandroid.com/2015/09/how-to-embed-youtube-video-in-android-webview.html), then you could have a set of tutorial screens that had headers describing the main points "add a card", "download a shared deck", "create AnkiWeb account", "synchronize" and each could embed the related video?

You have an example app right now with tutorial screens I think? Could you see if you can put the webview with embedded youtube link in it (maybe just trying the [video from the play store](https://www.youtube.com/watch?v=F2K1gOSdIZA) to start) and see if they all connect?

**Comment by Kartikkman** [comment]
Hey @mikehardy , Here is Progress Uptill Now : 
I played with WebView & iframe Tag to Play YouTube Video . 

- It is easy to play Youtube Video in WebView  ( User needs to click on play button ) 
- Not that Easy to Play Youtube Video on  Auto Mode  although  We can do it , I tested that & its working 
-  we can only play video on Auto Mode with No sound 
- To Play Video on Auto Mode ( with Sound ) , there are methods available on internet : Some Suggested Emulated Touch , Some using JavaScript to Play Video . 

So my ques is : 
- Should I stick to playing only " Youtube " Video on WebView or look for something else ( like playing from Google Drive)  ? 
- Following those unofficial methods , though these give some issues  ( which I need to figure out ) 

Suggestions ? @mikehardy

**Comment by mikehardy** [comment]
I actually strongly prefer that videos do not autoplay, so having the user click to play is perfectly fine by me. Very cool if this will work.

I swear - if we could reduce the number of confused users that open the app and see no cards, or then try to download a shared deck and get lost, or lose their collections because they don't sync...oh man, so many users so much happier!

**Comment by Kartikkman** [comment]
Ok @mikehardy 

Then I am finalizing with the Video on WebView ( no Auto Mode ) . 
Although I was now just reading the YouTube API for Android ( so Leaving that for Now !! ) 

I will be then updating you with the results of ( Playing Youtbe Video on WebView ) inside Fragments ( although Read just Now that  Iframe Tag inside Fragments is not so good ) . 

So I do that & post results ! 
& Regarding Videos , Well I will try to improve them & include Video on above content suggested by you .

**Comment by mikehardy** [comment]
here is Anki's introductory video, for inspiration https://www.youtube.com/watch?v=QS2G-k2hQyg - shows how to grab a shared deck and import it (though for AnkiDroid it is a little different of course)

**Comment by timrae** [comment]
I'm a bit confused, I thought this issue was for making an in-app tutorial, but now you are talking about playing YouTube videos from a webview?

**Comment by Kartikkman** [comment]
Well @timrae , We can have Static Picture Tutorial , I thought that didn't gave too much explanation  . So I thought maybe we should  go for Videos . 

If there needs to be Static Images then No issues I will go fro them . You please finalize 

@mikehardy @timrae

**Comment by timrae** [comment]
I think static images would work best for an in-app tutorial. But I agree with you that video can provide more information, so we can just put a URL at the end of the tutorial to a YouTube video and the user manual, for those that want more information (and have internet access).

**Comment by Kartikkman** [comment]
Hey @timrae @mikehardy 
I have started creating Static Images as Decided . Here is one , Please share your views : 

[Create Decks ](https://user-images.githubusercontent.com/28975022/64474012-87c4ed00-d18b-11e9-8856-24dd738fc0df.jpg)

**Comment by Kartikkman** [comment]
@mikehardy @timraeWaiting for Feedback

**Comment by Arnold2381** [comment]
@david-allison-1 does this need work?

**Comment by mikehardy** [comment]
This is in progress as a GSoC project with all sorts of related activity.
