### ISSUE TITLE
Answer cards blurry, or not appearing correctly.

### ISSUE THREAD

**Issue by otvenharom** [ankidroid/Anki-Android#4336]
###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Flip card
2. Answer either doesn't show, or is blurry.
3. Happens about 20% of the time.

###### Expected Result
Answer side appears correctly.

###### Actual Result
No answer side, or blurry card, like below.
![screenshot_2016-06-22-02-34-46-01](https://cloud.githubusercontent.com/assets/5750392/16250980/5666c46e-3822-11e6-90bb-fa7c25b95f54.jpeg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.6

Android Version = 5.1.1

ACRA UUID = 82c754fe-0604-43cd-bee0-7ed48c903158

**Comment by timrae** [comment]
What does your card template look like?

**Comment by timrae** [comment]
Does same issue occur if you view the cards on anki web?

**Comment by otvenharom** [comment]
Does not happen on ankiweb. Card templates are very simple, the only edits made are font size, and specifying a meiryo font. See below:
![capture](https://cloud.githubusercontent.com/assets/5750392/16251362/ac183930-3825-11e6-8e46-d1c06cf0c689.PNG)


 The strangest part is that it happens randomly. After undoing a review and having the same card reappear, it's almost always appears correctly.

**Comment by timrae** [comment]
It sounds like it could be a device specific problem. What model are you using? Do you have any other android devices to test on? You could also try swapping the font for Google Noto and see if that helps...

**Comment by otvenharom** [comment]
Sony Z1 compact, rooted, official CE ROM. No other devices unfortunately. If it helps, I've been testing it, and rarely the blurriness is only for a split second, as if the program were taking a longer tie loading the card, however this seems to be unrelated to the length of the sentences and words. Other times only half of it is blurry, and once even the question side was like that. Is there any other diagnostic information I can provide that could be useful?

**Comment by timrae** [comment]
The display of the flashcard content (html) is handled by the android system; we don't have direct control of it, so there isn't really anything we can do about this.

As already mentioned, you can try a different font or a different device and see if the situation improves.

**Comment by hssm** [comment]
Your template is invalid. In both your front and back templates, on the last line, you start by defining a `<span>` tag but you never finish it with `</span>`.

**Comment by hssm** [comment]
Actually, you do that in more than one place.
