### ISSUE TITLE
Bug: Ankidroid defaults to system language despite language option

### ISSUE THREAD

**Issue by iiLaurens** [ankidroid/Anki-Android#4341]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1.  Have a different system language 
2.  Turn on automatic screen rotation and start in portrait mode
3.  Open any deck and review a card
4.  Rotate device into landscape mode
5.  Press the android return button to return to the to the main menu of Ankidroid

###### Expected Result
I would expect the interface of Ankidroid to be the language as set in my Ankidroid settings (English).

###### Actual Result
The interface of Ankidroid changed to Dutch (my Android system language) and effectively overrides the ankidroid setting, which I set to English.

This is on my Huawei Honor 7 Phone with Android 6.0

###### Debug info
Coming soon...

**Comment by iiLaurens** [comment]
Debug info

AnkiDroid Version = 2.6

Android Version = 6.0

ACRA UUID = 1821171c-961f-4fc0-a531-7728e600e761

**Comment by timrae** [comment]
Has your language been translated? Try a different language like Japanese that is known to have a complete translation.

**Comment by iiLaurens** [comment]
The system language of my android is set to Dutch (Nederlands). There is a Dutch translation in Ankidroid,  however I am used to the English interface of Anki and thus choose in the settings menu of Anki to use a English interface. But the issue is that, given the steps described earlier, that Ankidroid shows the Dutch translation irrespective of my preference for English as set in the settings menu.

**Comment by jarofclay** [comment]
Same issue here still.  Default language is not English in the system, but if I try to change the language to English it has no effect.  It keeps the system language.
