### ISSUE TITLE
A suggestion for how to show picture in card

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#4343]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
1.When the image's width less-than the screen's,the picture has its real width like this

![](http://o8aucf9ny.bkt.clouddn.com/2016-06-24-21-40-24.png) 

I hope to keep this feature

2.When the image's width greater-than the screen's,the picture will be compressed to 80% of screen like this

![33](https://cloud.githubusercontent.com/assets/10048069/16354354/b492e614-3ac3-11e6-8eac-455a0105a23c.png)

I think this behavior waste a lot of space to show the content for a large picture.I hope it will be compressed to 99% of the screen width(leave small space is enough like the left margin).

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by hssm** [comment]
Okay, let's try it out then. We originally used 90% because that's what the desktop client does, but it obviously makes more sense to try to maximize space on mobile.
