### ISSUE TITLE
Move filtered deck creation to the FAB

### ISSUE THREAD

**Issue by Ooglogput** [ankidroid/Anki-Android#4351]
###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

This might be the most nitpicky feature request ever, but the way it is now is horribly unintuitive. I know it's kind of in line with the desktop client, but honestly you've been ahead of them for a while now.

**Comment by hssm** [comment]
I'm inclined to agree with this.

Does anyone have a reason for why we shouldn't move it to the FAB?

**Comment by timrae** [comment]
FAB is supposed to be for commonly used actions only. Manually creating filtered decks (I.e. outside of "custom study") should be considered an uncommon action for "power users" in my opinion. 

From my experience on the support forum it's clear that adding more choices to this menu will confuse users,  so I'm not really in favor of the change.

**Comment by Ooglogput** [comment]
How common is it actually for users to add cards on mobile, though? It's already a hassle on desktop, and I can't really see anyone doing it on mobile. Downloading shared decks is easy, sure, but how often do you actually add new decks in the first place? I agree that filtered decks are more of a power user thing, but the way I see it you're more likely to do that on mobile than any of the other actions, aside from maybe adding a single card every now and then. This is just from my own experience though, I might be dead wrong. 
To be clear, I'm not advocating removing any actions from the FAB to make room, although I do think shared decks (or filtered decks, really) could possibly be integrated into normal deck creation.

**Comment by timrae** [comment]
Adding new cards is a very frequent action for a significant percentage of users.... I have some actual data to back this up actually:

https://docs.google.com/forms/d/1LkA0jw4zb-ye889gzcz8gRBWJqGPfbUpu-QUppbPgHM/viewanalytics

**Comment by Ooglogput** [comment]
Interesting, I'd never have thought. I still believe there could be room for it, though.
