### ISSUE TITLE
Please display underline in search results

### ISSUE THREAD

**Issue by carlos-hoyos** [ankidroid/Anki-Android#4361]
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. Add a note with a word
2. surround word with underscore tags < u>word< /u>
3. search for word
###### Expected Result

In the results, the word appears with a line beneath it
###### Actual Result

tags are ignored in the results. I have to edit note to know which word I underlined as it is not displayed
###### Debug info

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by david-allison-1** [comment]
I'd like to keep this around for a bit - presumably the TextView accepts a `Spannable`, and we can obtain this from the HTML.

**Comment by david-allison-1** [comment]
Would be a nice QoL for 2.14
