### ISSUE TITLE
Recording bug. Unable to preview

### ISSUE THREAD

**Issue by akiratee** [ankidroid/Anki-Android#4362]
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

Ever since new update on June 14th, whenever I record audio, playing the play button does nothing. When editing each card and trying to play the audio, it will fail. However, the audio can be heard when studying the card. This makes it very inconvenient for users to know if the recording succeeded

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by hssm** [comment]
This has been fixed and will be available in the next point release by the end of the week. If you need to have it right now you can [become a beta tester](https://ankidroid.org/docs/manual.html#betaTesting) and perhaps also help us with testing in the future.
