### ISSUE TITLE
Make subdecks more intuitive

### ISSUE THREAD

**Issue by sibilek** [ankidroid/Anki-Android#4363]
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

I have been using AnkiDroid more then 4 years now. and it took me 2 years to find out and understand subdeck issues after I started to use Anki. I know it's a bit my inexperience and foolishness. There is nothing about Subdeck in the AnkiDroid app.  It's kind of secret option. One should search the manual to find out about Subdeck. 

this enhencment will make Anki More User-Friendly and easy to find out Sub-Deck. In the picture below I just thought adding 2 items is enough which both not to make menu so crowded and basic things about sub-deck. 

First one is for adding a sub-deck to a main deck.
Second one is for converting a sub-deck to a main deck or converting a main deck to sub-deck in an other main deck

I know It's not that important. My purpose is just to make Anki more easy to use and more user-friendly. 
Cheers. :)
###### Production Steps
1. Long press a Deck on main screen.
2. Main menu of the Deck appears
3. Sub-Deck options will appear in menu.

P.S.: I generated this picture with PicsArt app.

![anki sub deck menu sketch](https://cloud.githubusercontent.com/assets/11895544/16644536/5f609418-4426-11e6-8fad-142c8155bf3c.jpg)

**Comment by timrae** [comment]
I'm not really in favor of adding new menu items, but perhaps something else could be done to make subdecks more intuitive.

**Comment by hssm** [comment]
Eventually we need to replace the dialog context menu with a Contextual Action Bar and then make the decks drag-and-droppable. Kinda like [this](https://www.youtube.com/watch?v=S7cSwMArjUQ) at the beginning. The code in libanki to handle deck renaming to allow this is already in place but it's untested.

**Comment by sibilek** [comment]
Today I saw @hssm's post and youtube video which is way better then I thougt. But yesterday after I saw @timrae's post I made some pictures via PicsArt with a new idea. I will post them anyway maybe you like the idea. :) These are all amateur pictures. I beg your patience and understanding.

1. a new "Add/Manage Subdeck" button under flowing + button like in picture. I made up icon :) I know there would be better icons. 
![subdeck new 01](https://cloud.githubusercontent.com/assets/11895544/16688258/ecfbc14e-4525-11e6-9d56-18e4698404a0.jpg)

2. When user click "Add/Manage Subdeck" button, a window like a Create deck will be appear. this window has 2 tabs. First one is "Add" subdeck. ![subdeck new 02 00](https://cloud.githubusercontent.com/assets/11895544/16688509/0c966814-4527-11e6-9efe-856219869837.jpg) 
and the result will be like...
![subdeck new 02 01](https://cloud.githubusercontent.com/assets/11895544/16688523/1af11f1c-4527-11e6-91f5-5d10f84f9e2a.jpg)

3. In this picture user will choose 2nd tab on right side which is "Manage" subdecks. Just below left side there is a dropdown menu which can be Main or Sub. It can be also changed by clickin arrows in the middle. This screen show to change a Main deck to a Sub deck. User will choose a parent deck and a Main deck which will be subdeck of choosen parent deck.
![subdeck new 03 00](https://cloud.githubusercontent.com/assets/11895544/16688573/4efdfc30-4527-11e6-96c8-4fa132e69f17.jpg)and the result will be like...
![subdeck new 03 01](https://cloud.githubusercontent.com/assets/11895544/16688669/bf58d9c8-4527-11e6-82cf-aa144d49fd59.jpg)
4. to reach this screen user will change "Main" to "Sub" by dropdown menu or clicking the arrow in the middle. And it will be "Sub" to "Main". 

![subdeck new 04 00](https://cloud.githubusercontent.com/assets/11895544/16688753/2b83d558-4528-11e6-8a17-b7a5d7ab082a.jpg)

and the result will be like...
![subdeck new 04 01](https://cloud.githubusercontent.com/assets/11895544/16688761/3bcdc982-4528-11e6-8887-b727d60fa0dd.png)

**Comment by david-allison-1** [comment]
Would like to keep this open for another round. Would have this on my priority list if I had time

**Comment by david-allison-1** [comment]
Improved in #6282, only with DeckPicker menu item
