### ISSUE TITLE
Adding <Prev, Next> buttons to Card Browser's Editing Screen to edit faster

### ISSUE THREAD

**Issue by sibilek** [ankidroid/Anki-Android#4364]
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

I have added 1200 words in English to a main deck and it's subdecks in AnkiDroid. During adding process to make it faster I skipped adding auido files to cards. Now I am using a free open-source app called [Sound4Ankidroid](https://play.google.com/store/apps/details?id=com.learnerstechlab.soundcapture4ankidroid&hl=en) to add audio files to cards, here is [youtube demonstration](https://www.youtube.com/watch?v=7oONrsqduuk) for Sound4Ankidroid, here is [Github Page](https://github.com/cojcoj/android-soundcapture4ankidroid) for Sound4Ankidroid. 

It would be faster to edit a card or add audio file to a card if "Prev" & "Next" buttons added to Card Browser's Editing Screen as in the picture below. After editing finish when user press one of the "Prev" & "Next" buttons AnkiDroid will save changes just as in AnkiDesktop browser. with this way user can easily move between cards just like in Preview screen and as in AnkiDesktop browser. 

![picsart_07-07-11 02 33](https://cloud.githubusercontent.com/assets/11895544/16646985/b342c7fe-4435-11e6-8124-6722753a1aea.jpg)
###### Production Steps
1. To edit each card I have to go card browser 
2. click card to edit
3. copy word
4. drag drop down main screen to open Sound4Ankidroid
5. click to play&(audio will be downloaded to collection.media folder)&copy file as [sound:xxxx.mp3]
6. click to hide button of Sound4Ankidroid
7. paste filename into audio field.
8. hit OK button up right
9. find next word to add audio file

![screenshot_2016-07-07-13-37-06](https://cloud.githubusercontent.com/assets/11895544/16650688/272fbd72-4448-11e6-9814-7791100a4190.png)
![screenshot_2016-07-07-10-51-24](https://cloud.githubusercontent.com/assets/11895544/16646998/c576eb94-4435-11e6-8ecb-c211a871d011.jpg)
![screenshot_2016-07-07-10-52-14](https://cloud.githubusercontent.com/assets/11895544/16647025/e0ebc732-4435-11e6-8150-83d23376ff7e.jpg)
![screenshot_2016-07-07-10-52-26](https://cloud.githubusercontent.com/assets/11895544/16647045/f08cc812-4435-11e6-8681-b41865551e83.jpg)
![screenshot_2016-07-07-10-52-48](https://cloud.githubusercontent.com/assets/11895544/16647044/f08a27d8-4435-11e6-9ee2-a91f59b93781.jpg)
![screenshot_2016-07-07-10-53-02](https://cloud.githubusercontent.com/assets/11895544/16647043/f074ecba-4435-11e6-8116-4a29fed3d52f.jpg)
![screenshot_2016-07-07-10-53-19](https://cloud.githubusercontent.com/assets/11895544/16647042/f0722912-4435-11e6-9fbf-72e460dbb02b.jpg)
![screenshot_2016-07-07-13-40-44](https://cloud.githubusercontent.com/assets/11895544/16650754/8644faf2-4448-11e6-91f7-e44f3fb7e98f.png)
![screenshot_2016-07-07-13-37-12](https://cloud.githubusercontent.com/assets/11895544/16650707/4eb0be6e-4448-11e6-8a9b-a56bd0496f94.png)

**Comment by david-allison-1** [comment]
Added edit button to the preview, but not buttons on the note editor

**Comment by david-allison-1** [comment]
I'll get to this after other big ticket items are completed, it's nowhere near as high priority now, but will help with UX

**Comment by prateek-singh-3212** [comment]
I would like to work on this issue.

**Comment by david-allison-1** [comment]
> I would like to work on this issue.

Okay, could you sketch out a rough design for how you'll go about this before you begin, and define the edge cases, and how you'll handle this.

It would be ideal if the solution contains unit tests, as the logic may be a little hairy, and you'll want to explain to future developers what your intention is here.

In my mind, the main issue is that the card browser shows cards, and the note editor shows notes. You'll need to define what do to, if, for example, you're trying to view:

* n1, n1, n2, n2 - do you show the same note again?
* n1, n2, n1, n2 - how do you handle duplicates? Ignore them?

**Comment by prateek-singh-3212** [comment]
@david-allison-1 I have analyzed the situations and came out with 2 possible solutions.
1. Showing the note editor to the user 1 time only i.e Ignoring the note editor for the rest of the card associated with it.
2. Showing the note editor Fields according to the Fields used in a particular card.
 Let me explain it to you through example.
 I have created the decks of name **7 wonders of the world** and I created custom type name 'Monuments' in which Fields are the **Country in which they are located**(Let's say 'India'), **the location of a monument in a country**(Let's say 'Agra'), **the Image of a monument**(Image of Taj Mahal), **Name of a Monument**(Let's Taj Mahal).
I have created 4 custom cards as Follow's:

Card 1: Front :Country in which {{Name of a Monument}} Located?
             Back: {{Country Name}}

Card 2: Front: {{Image of Monument}}
             Back: {{Name of Monument}}

Card 3: Front: Location of the {{Name of Monument}} in {{Country}}
             Back: {{the location of a monument in a country}}

Card 4(Reverse of card 1): Front: Name of Monument located in {{Name of Country}}
                                           Back: {{Monument Name}}

So, what I want to say from all of this thing that when the user is browsing the cards and wants to edit card 2 then the user will see fields associated with that card only i.e **Image of Monument** and **Name of Monument**

another one will be to display all the fields associated with all four cards and edit at one place and Ignore the rest of the 3 cards Note Editor.

Anki Desktop is showing all the Feilds in the note editor irrespective of that field is used in that particular card or not.

**Comment by prateek-singh-3212** [comment]
I will use buttons that we are using in preview while browsing through the note editor.
![WhatsApp Image 2021-04-07 at 19 01 34](https://user-images.githubusercontent.com/76490368/113875102-0d7ba500-97d4-11eb-9080-d99d910d9a5f.jpeg)

**Comment by david-allison-1** [comment]
@Arthur-Milchior @infinyte7 @mikehardy

Thoughts on [the above](https://github.com/ankidroid/Anki-Android/issues/4364#issuecomment-814915837)? 

Personally, the idea of matching a card to its fields is very interesting. I think we could leverage the "collapse field" functionality, and get something really useful and novel here.

I'm not sure it would work in the general case: `basic (and reversed)`, or `cloze` wouldn't work well, and we'd need a selection strategy: (per card: `distinct by fields used`, or similar).

I'm not sure about the UX, but I would like to consider the idea further.

**Comment by mikehardy** [comment]
If I were in the note editor I would expect a carousel to take me around whole notes? 🤔

**Comment by prateek-singh-3212** [comment]
![aa](https://user-images.githubusercontent.com/76490368/113978267-634a5e80-9861-11eb-9830-2ff8a0a748a1.png)

We can use the above layout and when the user swipes to the next layout then we can hide the irrelevant fields.

We may provide settings to the user that I case he/she gets confused with UI so they can turn it off and we just show Editor once for all cards as mention in [this](https://github.com/ankidroid/Anki-Android/issues/4364#issuecomment-814915837) 

>     1. Showing the note editor to the user 1 time only i.e Ignoring the note editor for the rest of the card associated with it.

**Comment by mikehardy** [comment]
Before we get too fancy with the next/prev idea, we need the card template editor to structurally match desktop more I think

If the next/prev idea conflates scrolling through notes and scrolling through cards in notes I am -1 on that, I think it will be non-intuitive / people will become lost

**Comment by david-allison-1** [comment]
I feel we should stick with `.distinct()` on the note IDs and navigating through that collection. @mikehardy Does this work?

**Comment by mikehardy** [comment]
I believe that means it will be going next/prev on entire notes (not cards inside notes or fields in cards) which I think makes sense in context of note editor, so yes

**Comment by Arthur-Milchior** [comment]
I agree with mike.
It may lead to strange result. E.g. if you sort cards by due date, then the cards of a single note may be a little bit everywhere in the list of cards. When all cards are not together, deciding which cards to select to show may be non trivial. 
* If you show the first card in the list of card and you click on the second card, then the card you click on can not even be seen
* if you show the first card in the list of card, starting where you clicked, then the behaviour will be different before and after the card you clicked on

I can see plenty of edge cases. But I'm really in favour of it.

I'd like to note that we have an open PR to display a single card by note. Both features seems heavily related. (It's a feature that is currently being added to upstream. Last time I checked they had not decided entirely what they want to do in all details)


I believe the idea of displaying only the fields that are shown is great when you edit a note opened in the reviewer. This way, you can concentrate on data actually shown and need to click to open the other fields that are probably not relevant right now. However, I don't like this idea from the card browser at all, since most of the time, I don't even know which card I click on, I'd find it confusing.
