### ISSUE TITLE
Previewer doesn't appear correctly when fullscreen enabled

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4365]
###### Reproduction Steps
1. Enable fullscreen immersive mode
2. Open previewer
3. Tap somewhere on the screen
4. The device enters immersive fullscreen mode
5. The position of the new buttons are not aligned with the bottom of the screen

It's probably easiest to simply not enter fullscreen mode at all here, since the navigation drawer is disabled here, and the navigation drawer is required to disable fullscreen mode. Also, fullscreen mode = 2 (hide answer buttons) doesn't make sense in the previewer.

**Comment by david-allison-1** [comment]
Reproduced with "Hide the system bars"
