### ISSUE TITLE
Writing feature undo should remove all writing

### ISSUE THREAD

**Issue by SpacePhoton** [ankidroid/Anki-Android#4367]
On screen writing in droid is best used as scratch paper, to review Chinese symbols for example. The recent change made the undo button remove one stroke at a time, which is impractical of you want to to scribble many things.

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
The 'clear whiteboard' button is still available from the overflow menu. If
you only need that, you can bring it into the app bar by going to Settings
-> Reviewing -> App bar buttons and configuring the button placements as
necessary (this feature was also just introduced).

**Comment by SpacePhoton** [comment]
Thanks!!!
