### ISSUE TITLE
Do not play sound on Moto x play 

### ISSUE THREAD

**Issue by scd4j** [ankidroid/Anki-Android#4372]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1.open a card 
2. Click in play button 
3. Nothing happens 

###### Expected Result

Play the sound 

###### Actual Result

No sound on Moto x play. It works fine on Nexus 7 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.6.1

Android Version = 6.0.1

ACRA UUID = 481d7122-2a85-4968-b202-75f4bf129bca

**Comment by hssm** [comment]
Please see [this section](https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid) of the wiki.
