### ISSUE TITLE
unable to use marks

### ISSUE THREAD

**Issue by lahootian313** [ankidroid/Anki-Android#4373]
Hi
In Persian language while I'm adding new card or ... I can't use these marks such as ( ) ] [   
If I use them they will show in another places of the text and make it difficult to understand

The same problem is when I wanna share my own deck and wanna put a description of my deck into the field 
In this case I can't use any word from english language because text won't be readable anymore
I have to not use any word of english

Thanks

**Comment by hssm** [comment]
Please see [this section](http://ankisrs.net/docs/manual.html#rtl-(right-to-left)-text) of the manual. You can use the same ```<div dir=rtl>...</div>``` technique inside the deck description since that supports basic HTML as well.

**Comment by lahootian313** [comment]
Hi
Sir I'm not familiar with developer activities and really don't know those  elaborate codes 
Just when I translate your app into Persian on crowdin I think why I don't have these problems there 

If u solve these problems like crowdin we don't have to learn those codes 
Thanks
