### ISSUE TITLE
New cards counter det to zero unexpectedly 

### ISSUE THREAD

**Issue by ivostoykov** [ankidroid/Anki-Android#4374]
###### Research
*Enter an [x] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Few learned cards are sent back for learning (button 1 hit)
2. After last of them had been shown and marked as learned the new cards counter is set to zero. (in my case from 29)
3. 

###### Expected Result
New cards counter to change only when all new cards had been drilled. Otherwise counter should be unchanged. 

###### Actual Result
New cards counter is set to zero even before any of these carfs had been shown. All of them seemed lost.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info

AnkiDroid Version = 2.6.1

Android Version = 5.1.1

ACRA UUID = 26fd4def-5666-427e-a2e2-1e8b0d819496

**Comment by hssm** [comment]
I'm pretty sure this is the standard sibling burying behavior, as noted in the **bury related** part of the [deck options](http://ankisrs.net/docs/manual.html#new-cards) section in the manual.

Unless you can show the desktop client behaving differently for this case then I can't consider this a bug.
