### ISSUE TITLE
Duplicate card error when adding new cards

### ISSUE THREAD

**Issue by rgamici** [ankidroid/Anki-Android#4375]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Add a duplicate card.
2. Add a non duplicate card.

###### Expected Result
When adding a non duplicate card, the border should be black.

###### Actual Result
After adding a duplicate card (the bar became red), the bar doesn't go back to black.
Regardless of what is input on next card, the bar doesn't go back to black. (I tried to add some random extra characters to be sure that the new card is not a duplicate)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
Ankidroid version 2.6
Android version 5.0
Acra UUID = 9156b069-add2-4763-b330-ef5b23f53ff8

**Comment by hssm** [comment]
I can't reproduce this. Could you perhaps export your collection (without media) and post it here so I can try to reproduce it?

**Comment by rgamici** [comment]
My collection is too big.
I tried to create a simple deck to reproduce it, but at first it was working correctly. However, after some testing, I noticed that if I added a new card and then a duplicate, it doesn't happen (it behave as expected). But if I return to the main menu and then try to add the same note again, the error happens.
Can you try it again? If you can't reproduce it, I'll upload my collection.

**Comment by hssm** [comment]
Oops I glossed over the important details. This  issue should have been fixed in the **2.6.1** release which is available in the Play Store at the moment. Can you upgrade and try it again?

**Comment by rgamici** [comment]
This doesn't happen in the newer version.
