### ISSUE TITLE
Feature Request: Automatically play video

### ISSUE THREAD

**Issue by sevenkel** [ankidroid/Anki-Android#4377]
hey there, I think It's annoying that videos are being played automatically when new card appears(If added to the Front), there must be an option to disable that.(separate from audio auto play).
Regards.

**Comment by hssm** [comment]
Anki currently considers all media under the same setting, so disabling the `Automatically play audio` setting will also disable video playback.

The media playback setting is part of the *deck options* which are part of the Anki system (and reside inside your collection), which means we can't add a separate one for video unless the desktop client does so first.
