### ISSUE TITLE
Anki collection, study settings dialog does not open

### ISSUE THREAD

**Issue by jo91** [ankidroid/Anki-Android#4378]
[######] Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  X] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

[collection.zip](https://github.com/ankidroid/Anki-Android/files/369822/collection.zip)

1. open my deck
2. open the study options dialog
3. ankidroid crashes

###### Expected Result

I created this collection with Anki on ios. Later I synchronized with ankidroid.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by hssm** [comment]
You left out the debug info section which is the most important for us to look into this issue.

**Comment by jo91** [comment]
AnkiDroid Version = 2.6.1

Android Version = 6.0.1

ACRA UUID = 4b43fae7-70ee-4fa6-b33b-1e4ad3211ad1

**Comment by hssm** [comment]
Any chance you could export your collection and send it to me?

**Comment by jo91** [comment]
[collectionexport.zip](https://github.com/ankidroid/Anki-Android/files/371300/collectionexport.zip)

**Comment by hssm** [comment]
Thanks. Expect a fix in the 2.6.2 release.
