### ISSUE TITLE
Card browser, quick feature request

### ISSUE THREAD

**Issue by shard2001** [ankidroid/Anki-Android#4382]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

On Android it would be very useful if in the card browser you could temporarily mask the answer side. You could do this with an option under the answer dropdown for 'mask answers', you would then see the answer by clicking on the space where the answer would be. 

This would mean that you could quickly scan through the questions looking for any areas you need to quickly go over for a test, or because you are going to a restaurant in the language you are learning, etc.

You could do this with a lot more effort by setting by sub groups but this would be fast, painless and effective

**Comment by hssm** [comment]
This would be a lot of work for a very particular use-case. I don't think we should be adding something like this.

You can achieve something similar by changing the column to something else and then changing it back to Answer to reveal the answer side. Not as efficient but it achieves a similar result.

**Comment by shard2001** [comment]
Thanks for that, obvious in hindsight
