### ISSUE TITLE
Android Gradle Plugin Update Recommended

### ISSUE THREAD

**Issue by madhead** [ankidroid/Anki-Android#4384]
###### Research
*Enter an [ x ] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

- [x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open the AnkiDroid source code in Android Studio 2.1.2 (latest stable version)

###### Expected Result

No major warnings.
"Instant Run" works on latest Androids.

###### Actual Result

Warning appears:

> ###### Android Gradle Plugin Update Recommended

>The project is using an old version of the Android Gradle plugin. 

>To take advantage of all the latest features, such as [Instant Run](http://tools.android.com/tech-docs/instant-run), we strongly recommend that you update the Android Gradle plugin to version 2.1.2. 

>You can learn more about this version of the plugin from the [release notes](https://developer.android.com/studio/releases/gradle-plugin.html).

###### Debug info

No debug info: it's a codebase issue.

**Comment by hssm** [comment]
Thanks for the reminder, I've been a  bit lazy with this lately.

I actually got frustrated with Instant Run and turned it off. I'm sure it's a lot more reliable now. One interesting thing about it is that it changes the application version number to `INSTANT-RUN`, and AnkiWeb refuses to sync with it because it thinks the version is too old.

**Comment by madhead** [comment]
Oh, ok. I wouldn't have thought of this.
