### ISSUE TITLE
Enhancement for "text-align: left"

### ISSUE THREAD

**Issue by leoliu1313** [ankidroid/Anki-Android#4388]
I am new to Anki, and I just figure out how to align left for all the cards.

Open desktop version, click on a card in browse, and click "cards", it will open a window that will have some styling code. In the styling box, change "text-align: center" to "text-align: left".

I am wondering if we could do the same thing on AnkiDroid app. Something like vertically align center. Add a new option for the alignment where users can set it center or left. It would be nice to have this enhancement.

**Comment by hssm** [comment]
Vertical alignment is vastly more complex and we provided it as a setting to ease the transition between template rendering methods: in the past, we used to render them much differently than the desktop client, and centering was one of the things we did differently.

Text alignment is simple, part of the default template, and is explained in the manual.

**Comment by leoliu1313** [comment]
Simple? How can we change it on the app?

**Comment by hssm** [comment]
You can edit a note and click on the "Cards" button that appears in the editor. That lets you edit templates.

**Comment by leoliu1313** [comment]
Amazing! Didn't know the app editor has the same button as desktop version. Thanks a lot!

I think you refer the following as "explained in the manual".

> Custom Card Layout

> The layout of flashcards is completely customizable, although this is an advanced topic with a fairly steep learning curve, and you will probably find it a lot more convenient to do the customization with Anki Desktop.
> 
> The card templates section of the Anki Desktop manual has detailed instructions on how to edit note types, and most of the actions discussed there are also available from AnkiDroid by tapping "cards" at the bottom of the note editor, or choosing the "manage note types" option in the deck picker. Since detailed information on customizing card layouts is available in the Anki desktop manual, it will not be repeated here.
> 
> There is an advanced formatting page on the AnkiDroid wiki with various hints on how you can get the most out of your card formatting, and we encourage you to read it, and edit it freely if you have any tips that you’d like to share with the community.

Maybe we can append the following line to make it easy for people to search?

> For example, set up text-align: left to make the content to horizontally align left.

So, when searching for "align", we get

> Center align
> 
> By default AnkiDroid tries to show cards exactly as they are shown on Anki Desktop, however if you prefer your cards to be center aligned vertically in AnkiDroid then you can enable this feature.

and that line.

**Comment by eginhard** [comment]
That's standard CSS code for which you'll find many references online, so
there's no need to include that in the AnkiDroid manual.

**Comment by leoliu1313** [comment]
lol so nice.
