### ISSUE TITLE
Ankidroid does not show learning phase cards in random order in some circumstances

### ISSUE THREAD

**Issue by wareya** [ankidroid/Anki-Android#4390]
I have a deck with two card types where every note has exactly two cards. "Bury related new cards until tomorrow" is unchecked. Learning steps are default. The deck is newly added from scheduling-less apkg and hasn't been used before.

Anki Desktop behavior:

Do 30 new cards in under 10 minutes on fresh deck. Start getting shown previously new cards that are now in the learning phase, on their 10 minute step, before their scheduled moment in time has passed. They're shown in a seemingly random order.

Ankidroid behavior:

Do the same thing. They're shown in the same order I originally saw them in.

Behavior difference is the same after waiting more than 10 minutes to make the cards all be due instead of ahead schedule.

**Comment by hssm** [comment]
Can you please attach this deck so I can use it for testing?

**Comment by wareya** [comment]
[Just Kana.apkg.zip](https://github.com/ankidroid/Anki-Android/files/391729/Just.Kana.apkg.zip)

**Comment by hssm** [comment]
Thanks for providing this bug report. You've saved me a lot of time by verifying the behavior of the desktop client and providing the sample deck. It's very much appreciated.

I've put in a fix for this which should be included in the next minor release.

**Comment by wareya** [comment]
Thank you.
