### ISSUE TITLE
Cards now have very long repeat times

### ISSUE THREAD

**Issue by AngledLuffa** [ankidroid/Anki-Android#4393]
I took a few weeks of break from using AnkiDroid.  When I started using it again, all of my cards now have a very long respawn time.

Even new cards will come up for review the next day and then have a new interval of almost a month after their first review.

I don't know if this is directly related to the break I took.  I believe the app was also updated during that time.

There are no specific steps to reproduce, but I'm happy to share my library if that helps.

This is occurring on 1.6.1 on a Blackberry Priv.
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. 
2. 
3. 
###### Debug info

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by hssm** [comment]
Anki [gives a bonus to cards that overdue](http://ankisrs.net/docs/manual.html#what-algorithm):
>Answering cards later than scheduled will be factored into the next interval calculation, so you receive a boost to cards that you were late in answering but still remembered.

New cards shouldn't be affected. Maybe you've modified one of the [deck options](http://ankisrs.net/docs/manual.html#new-cards). Compares yours with the defaults.

**Comment by AngledLuffa** [comment]
Thanks for the explanation.  The quote about factoring in the delay didn't
make it clear that the next interval would be longer, not shorter.  The
delay was long enough that some of the next intervals are 6-8 months
instead of about two months, as they would ordinarily have been.

**Comment by hssm** [comment]
In that case it does sound like you've modified some of your deck options that impact scheduling.

>This is occurring on 1.6.1

I don't remember if we even had a version with that number. The 1.x series is *so* old that the algorithms are different and is completely unsupported.

**Comment by timrae** [comment]
1.x stopped at 1.3 so I assume he means 2.6.1

**Comment by AngledLuffa** [comment]
My mistake, it was 2.6.1.

I don't recall setting any options that would affect the delay between
cards.  It was several weeks that I wasn't able to use the flashcards,
though, so that may have an effect.  I will see what happens when I
eventually finish the backlog,

Thanks!
