### ISSUE TITLE
Missed action on False media references when checking media 

### ISSUE THREAD

**Issue by p0ooo0ya** [ankidroid/Anki-Android#4396]
###### Reproduction Steps

1. check media

###### Expected Result

check database feature should provides a way to deal with media references on cards that don't exist in collection.media folder

###### Actual Result
only reporting how many false media references exits

![ankidroid checkdatable report](https://cloud.githubusercontent.com/assets/20789910/17322675/daf5214c-58b3-11e6-8604-b5321a7368e9.jpg)
alose these false references prevents Anki from importing Decks and Collection with false references after exporting

**Comment by hssm** [comment]
The desktop client does not offer an action, so neither does AnkiDroid. However, the desktop client gives you a list of cards while we do not. The default dialog implementation doesn't work well for large lists, so we omit it, but there is a TODO in code about implementing such a dialog (which can be reused for other reports).

The media exporting is a [known issue](https://github.com/ankidroid/Anki-Android/issues/3636). It's a high priority for me for the next major release.
