### ISSUE TITLE
Unable to import .apkg files: unable to find applications that support this file type

### ISSUE THREAD

**Issue by Gloria-Li** [ankidroid/Anki-Android#4399]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. creat a new set on the pc
2. export it and mail it to my phone
3. open it

###### Expected Result
The system recognizes anki and import the apkg file to anki

###### Actual Result
System unable to find applications that support the file type today, while nothing went wrong yesterday as I did exactly the same thing.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by timrae** [comment]
What mail application? Try using a different one like gmail and it should work

**Comment by hssm** [comment]
What do you think could have changed overnight on your device to make it stop working?

**Comment by Gloria-Li** [comment]
What's mail application?

I can think of nothing that has changed. I deleted the shortcut on my desktop this morning, after I found out this problem I pulled it back, but the problem didn't get fixed. I also tried to delete the app on my computer and installed it again, and the problem still exists.

**Comment by Gloria-Li** [comment]
Hi there!
I've solved the problem!
It turns out that I named my deck as "8.4.apkg", and the android system cannot recognize two dots in the file name.
Thank you so much for your help! Thank you all!:)
