### ISSUE TITLE
Settings option is labeled incorrectly

### ISSUE THREAD

**Issue by SimonLammer** [ankidroid/Anki-Android#4402]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1.  Open App Settings
2.  Choose the 2nd entry (it's called 'Lernen' in german)
3.  Scroll down to 'Show ETA'

###### What's wrong?

The heading for ```Show remaining time``` should not be ```Show ETA```(**E**stimated **T**ime of **A**rrival)

I'm not sure about the correct abbreviation. Maybe  ```Show ETC``` (**E**stimated **T**ime of **C**ompletion)?

**Comment by hssm** [comment]
The meaning is easily understood by ETA.

Not a good source but Wikipedia has this excerpt which is good enough for me.

>ETA is also used metaphorically in situations where nothing actually moves physically, as in describing the time estimated for a certain task to complete (e.g. work undertaken by an individual; a computation undertaken by a computer program; or a process undertaken by an organization).

**Comment by SimonLammer** [comment]
thanks for the reply anyway
