### ISSUE TITLE
Traceback (most recent call last):   File "aqt/main.pyc", line 740, in onNoteTypes   File "aqt/models.pyc", line 24, in __init__   File "aqt/models.pyc", line 52, in setupModels   File "aqt/models.pyc", line 71, in updateModelsList   File "anki/models.pyc", line 207, in useCount   File "anki/db.pyc", line 76, in scalar   File "anki/db.pyc", line 43, in execute pysqlite2.dbapi2.DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by chrisar15** [ankidroid/Anki-Android#4403]
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
This page is only for AnkiDroid, which is developed independently from other Anki versions. Please use the main forum for problems with Anki Desktop: https://anki.tenderapp.com/discussions
