### ISSUE TITLE
Clicking GOOD button in `Review ahead`-desk doesn't reschedule card, it only postpone in for GOOD-interval

### ISSUE THREAD

**Issue by Nexen23** [ankidroid/Anki-Android#4404]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Long press on any desk
2. Click `Custom Study`
3. Click `Review ahead` within 1 day
4. Study any card clicking GOOD button
5. Repeat steps 1-4

###### Expected Result
After card was studied with GOOD button, card must be rescheduled for GOOD-interval and GOOD-interval must be increased. But it doesn't increased at all. Card only is postponed for GOOD-interval and that's all.
I ensured myself that `Reschedule` option in `Desk options` is enabled.

###### Actual Result
Reviewing date of card doesn't changed. After repeats steps 1-4 you will get studied card again with the same GOOD button interval specified.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

Problem isn't related to crashes.

**Comment by eginhard** [comment]
Is the behaviour different in Anki Desktop?

**Comment by Nexen23** [comment]
Seems like it has same problem. Pretty sad about it. Closed.
