### ISSUE TITLE
Can't change deck fonts individually 

### ISSUE THREAD

**Issue by moshpirit** [ankidroid/Anki-Android#4405]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum → I block everything from Google, so I can't read this.

###### Reproduction Steps

1. Open AnkiDroid
2. Open different decks with different fonts
3. search in every setting if there's a way to change their fonts but individually.

###### Expected Result

Finding an option that allows me to easily change the font

###### Actual Result

I found none

###### Debug info

Using AnkiDroid 2.6.1 (F-Droid) on Android 6.0.1

**Comment by hssm** [comment]
Fonts are handled by the card templates. It is usually easier to change them using the desktop client. See the [manual](http://ankisrs.net/docs/manual.html#installingfonts).

**Comment by moshpirit** [comment]
Then I think I'll change the issue for a Feature request where we can change it directly on the app ASAP (when I could use the laptop).  

Thanks anyway 😊

**Comment by eginhard** [comment]
You can modify the card templates in the app as well, by clicking on the
Cards button at the bottom while editing a card. But as hssm said, it's
just much more convenient to do so on Desktop.

**Comment by moshpirit** [comment]
Wouldn't it be much easier establishing a system font size (not just the type) for every card?
