### ISSUE TITLE
Cleaning Apps Deleting Data from Ankidroid

### ISSUE THREAD

**Issue by Kutubuddin** [ankidroid/Anki-Android#4406]
I have a Motorola X2 and I was using Ankidriod on it. I uploaded a lot of data for my studies. Later I used the Android cleaning software "Clean Master" to clear the junk from my phone. Once I ran Clean Master and checked with my Ankidroid, my entire data was gone. Just to confirm I uploaded some data again and ran Clean Master and the same thing happened again . It is happening with all the cleaning apps. The apps are treating the data saved in Ankidroid as Junk or something I believe. I can not uncheck Ankidroid every time I use a cleaning app, it's gonna bug me out. Please help.

**Comment by eginhard** [comment]
There probably isn't anything that can be done on AnkiDroid's side, but
this shows that you should be careful about using such cleaning apps. They
are generally bloat ware and don't help improve your phone's performance.

**Comment by Kutubuddin** [comment]
Thank you so much. I appreciate it.

On 8/18/16, Enno Hermann <notifications@github.com> wrote:
> There probably isn't anything that can be done on AnkiDroid's side, but
> this shows that you should be careful about using such cleaning apps. They
> are generally bloat ware and don't help improve your phone's performance.
>
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ankidroid/Anki-Android/issues/4406#issuecomment-240762775


-- 
Regards,
Kutubuddin Molla
Communication Skill Trainer
Hopes & Dreamz
08145420287
