### ISSUE TITLE
[feature request] add "send to Anki" function

### ISSUE THREAD

**Issue by DonCN** [ankidroid/Anki-Android#4407]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. When I search words in a dictinary or edit a note in smart phone, I want to save the word or note to Anki for repeating in the future.
2. In some software there are "share" function in its menu, I think may be Anki could be the target of this kind of "share" function.
3. When I chose "share" and select Anki, I can select which deck to save the "word" or "note".

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
You can already share text to AnkiDroid, which will bring you to the note
editor.

**Comment by DonCN** [comment]
Thank you for your reply. I just find that. It is really awesome!



donliucn@gmail.com
 
From: Enno Hermann
Date: 2016-08-23 22:55
To: ankidroid/Anki-Android
CC: Don Liu; Author
Subject: Re: [ankidroid/Anki-Android] [feature request] add "send to Anki" function (#4407)
You can already share text to AnkiDroid, which will bring you to the note
editor.
