### ISSUE TITLE
Show name of sub-deck  on top of each card

### ISSUE THREAD

**Issue by bluesleex** [ankidroid/Anki-Android#4413]
Just add {{Deck}} to the card template is to displaly name of deck on the each card. how to just display name of sub-deck?

It would be great if you could have the name of sub-deck  for each card showing in a list on the top of each card.

Thanks

**Comment by timrae** [comment]
You should be able to do this with javascript. Sorry we can't help you with this, but if you get stuck you could try asking on the forum.
