### ISSUE TITLE
Unable to remove shared decks

### ISSUE THREAD

**Issue by lahootian313** [ankidroid/Anki-Android#4414]
Hi
Another issue that I am facing right now is I shared two decks a few months ago and I don't know what happened but I know that I couldn't access my shared decks 
Although I had 3 email address and tried all of them but it said :u didn't shared anything while they are now on your server even I deleted all of my accounts but still they are there

What should I do to remove them???
I edited them and added some new audio and don't want to be downloaded by others or even searched 
What can I do? 

Thanks

**Comment by flerda** [comment]
This site is specifically for the Android app, which does not itself handle sharing decks.

Please reach out to the AnkiWeb support site at: https://anki.tenderapp.com. You can ask there about the problem you are facing. Probably providing some information about the decks you shared might be helpful in finding them. You can find your sharded deck at: https://ankiweb.net/shared/decks/ and provide them with the address for the deck in question.

**Comment by lahootian313** [comment]
Hi
@flerda

U mean my issue  #4410 is the same as this issue and shouldn't I have told here
Am I right??

Thanks

**Comment by flerda** [comment]
Issue #4410 appears to be related to the Android app, so this is the right place to report it.
