### ISSUE TITLE
Steps duration

### ISSUE THREAD

**Issue by Mornon** [ankidroid/Anki-Android#4416]
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. Change steps duration (I think I changed it in 10 1440 4320 10080)
2. Pass a new card to 10 minutes and then the next day
3. Change again steps duration (like 10 1440 4320)

I'm not sure if this will reproduce the issue, since I tried to uninstall Anki and reinstall it to have a clean version, but the behaviour didn't revert to normal so I wasn't able to do more tests. I'm sure I was tinkering with steps duration, I'm not sure what I did.
###### Expected Result

I guess Again and Good should be different and follow the same pattern despite how many steps I use, so if 10 30 1440 4320 10080 gives 10 minutes for Again and 30 minutes for Good, the same should be true with 10 30 1440 4320.
###### Actual Result

If as steps I use 10 30, both Again and Good are 10 minutes; the same is true with steps like 10 30 1440 and 10 30 1440 4320, but if I use 10 30 1440 4320 10080 the steps are now 10 minutes for Again and 30 minutes for Good. They goes both to 10 minutes if I delete a step, like 10 30 4320 10080.

If I use the standard 1 10 steps, both Again and Good are 1 minute.
###### Debug info

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.6.1

Android Version = 5.1.1

ACRA UUID = b7fa306f-1d13-4960-a557-7472b0b61413

**Comment by eginhard** [comment]
Is the behaviour different on Anki Desktop?

**Comment by Mornon** [comment]
Yes and no: yes on my desktop, where I imported the same deck: with 1 10 
as steps, both Again and Good are 1 min.

No on another PC, where I didn't import that deck: on that PC, with 1 10 
as steps Again is 1 minute, while Good is ten minutes.

**Comment by Mornon** [comment]
I tried to create another group with a new deck in it, and the behavior 
is different, with the same settings: with 10 20 50 120 as steps, the 
old deck gives me 10 min both as Again and Good, while the new one gives 
me 10 min for Again and 20 min for Good.

Moving the old deck in the new group doesn't solve the issue.
