### ISSUE TITLE
Missing string

### ISSUE THREAD

**Issue by lahootian313** [ankidroid/Anki-Android#4417]
Hi
There is a missed string in crowdin
It's
Please see the shared deck page for more info

Thanks

**Comment by timrae** [comment]
Can you please post a screenshot?

**Comment by lahootian313** [comment]
Here u are
![screenshot_20160913-062046](https://cloud.githubusercontent.com/assets/14838633/18458892/7cc029d6-797a-11e6-9a69-d48411752795.png)

**Comment by lahootian313** [comment]
Actually I didn't understand what do u want from screen shot
In crowdin when I searched I wasn't able to find this string to translate
U could check it 
I'm confused

**Comment by timrae** [comment]
This is the shared deck description; the shared deck author can write whatever they want there, so there's no way to reliably translate it unfortunately.

**Comment by lahootian313** [comment]
@timrae

I didn't expect u such answer

Look
I mean that string
PLEASE  SEE THE SHARED DECKS PAGE FOR MORE INFO 
,not author's description

Did u ever pay close attention to my first post????

I don't think so

And notice everything that u write in deck description in ankidroid not ankiWeb , will be replaced with something that u write in deck description on ankiWeb

**Comment by eginhard** [comment]
@lahootian313 Tim's answer is indeed correct. The string you're talking about ("Please see the shared deck page for more info.") is the deck description. You can change it yourself via Deck Options -> Deck Description in the app, but that string is not set by AnkiDroid (you won't find it in the source here) and therefore cannot be translated, we just don't have any control over it. It's automatically set for any shared deck that you download via any Anki version.
