### ISSUE TITLE
Right to left language 

### ISSUE THREAD

**Issue by lahootian313** [ankidroid/Anki-Android#4419]
Hi
Sir u mentioned in #4373 that deck description support right to left language but I tried in lots of method but it doesn't work
Please specify which code or style or ... I should use to correct the writing???

Thanks

**Comment by mikehardy** [comment]
I noticed at least one "Gravity.LEFT" usage in the code vs "GravityCompat.START" so this could use an RTL audit

**Comment by david-allison-1** [comment]
This is going to be more important now we support more RTL languages.

**Comment by mikehardy** [comment]
re-opening this one - we would love any help here, I think all the core developers and even casual contributors at the moment are Left-to-right language users so we haven't been able to help much

**Comment by eginhard** [comment]
This specific issue of RTL text in the deck description seems to be solved. I opened #8259 instead as a general tracker for RTL support. As far as I can tell, the following text is shown as expected without adding any further markup:
> <div dir=rtl style="text-align: right;"> يولد جميع الناس أحراراً متساوين في الكرامة والحقوق، وقد وهبوا عقلاً وضميراً وعليهم أن يعامل بعضهم بعضاً بروح الإخاء.</div>
> All human beings are born free and equal in dignity and rights. They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood.

![ankidroid](https://user-images.githubusercontent.com/5216613/111510263-e807f800-874d-11eb-9379-b1fb3ae1a10a.png)


For Anki Desktop it needs to be wrapped like this:
```
<div style="direction: rtl; text-align: right;">
 يولد جميع الناس أحراراً متساوين في الكرامة والحقوق، وقد وهبوا عقلاً وضميراً وعليهم أن يعامل بعضهم بعضاً بروح الإخاء.
All human beings are born free and equal in dignity and rights. They are endowed with reason and conscience and should act towards one another in a spirit of brotherhood.
</div>
```

![anki](https://user-images.githubusercontent.com/5216613/111510287-ed654280-874d-11eb-9e34-2647a372387b.png)

@lahootian313 If you're still around, does this work for you as expected? Or are there any other issues?
