### ISSUE TITLE
"Start of next day" is reset on next sync after syncing Anki Desktop

### ISSUE THREAD

**Issue by jasonmbechtel** [ankidroid/Anki-Android#4420]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

0.  Windows laptop and Android device are both in same timezone (in my case, US-Pacific / which is currently on daylight savings time: PDT (UTC -7)).
1.  set "Start of next day" to *4* hours past midnight (should be default) in both AnkiDroid and Anki Desktop.
2.  sync AnkiDroid.
3.  note setting in AnkiDroid is still 4 hours past midnight.
4.  sync Anki Desktop.
5.  sync AnkiDroid.

###### Expected Result

setting in AnkiDroid and Anki Desktop should both still be *4* hours past midnight.

###### Actual Result

setting in AnkiDroid is now *13* hours past midnight; setting in Anki Desktop is still *4* hours past midnight.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.6.1

Android Version = 6.0.1

ACRA UUID = e8d9f0cf-4a11-4486-9491-bd6d7864b694

**Comment by timrae** [comment]
Weird...

**Comment by jasonmbechtel** [comment]
Of course, after doing this for weeks, right after I finally took the time to open this bug/issue report, it stopped happening.  Now I can sync freely between the two and the setting stays.  *sigh*
