### ISSUE TITLE
"Preview new cards" show 0 cards with 99999 days but all with 9999

### ISSUE THREAD

**Issue by Nexen23** [ankidroid/Anki-Android#4421]
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. Long click on any desk
2. Tap `Custom study`
3. Tap `Preview new cards`
4. Type 99999
###### Expected Result

All new cards in desk should be in `Custom study session` desk now
###### Actual Result

`Custom study session` have 0 cards. If in step 4 you type 9999 then everything if okay. `0 cards` really confused me for a minute to the extent of writing a report.
###### Debug info

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.6.1
Android Version = 4.4.2
ACRA UUID = f356631b-222e-40ff-9a97-893bc3c5baaf

**Comment by KhaledTo** [comment]
I'll add to this that if you enter too many digits  then the app crashes in my case (try with 12 digits for instance : 111111111111). I'm fairly new to Java and Android but it will be my pleasure to contribute to Ankidroid by solving this one if nobody is working on this issue.
