### ISSUE TITLE
Use pale gray color characters for "Vibrate" and "Blink light" when "Never notify" is selected on "Notify when"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4423]
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
- In General settings, select "Never notify" on "Notify when".  
###### Expected Result

The color of the characters of the items, "Vibrate" and "Blink light", change from black to pale gray.

![image](https://cloud.githubusercontent.com/assets/10436072/18349138/9c6b38ac-760a-11e6-980d-88e1f88b86e8.png)
###### Actual Result

The color won't change.

This seem to be an undone task on #4233.

**Comment by mikehardy** [comment]
Should be taken into account with #4944 - cross-linking so it is considered
