### ISSUE TITLE
Transfering (Chinese) Card Decks from PC to Samsung Galaxy On5

### ISSUE THREAD

**Issue by tbeachglobal** [ankidroid/Anki-Android#4424]
A few seconds after clicking "export" on my laptop, and I get a confirmation message that tells me the number of cards that have successfully exported.  However, they don't appear in my Samsung on5 device.  A Previous answer to a similar problem on the old Google instructs as follows:
export the file to apkg from Anki Desktop, then copy the apkg file to your AnkiDroid folder on your device, and choose import cards from the main menu
However, I don't  see a "main menu" and when I go to the downloads file, all I see are prepackaged decks.  So how can I (complete the) transfer of my custom made Chinese cards from my laptop to my Android (Samsung on5 device?

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by timrae** [comment]
https://ankidroid.org/docs/manual.html#AnkiDesktop
