### ISSUE TITLE
Anki crashes immediately

### ISSUE THREAD

**Issue by jazzeps** [ankidroid/Anki-Android#4425]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. I select the Ankidroid app
2. It crashes
3. 

###### Expected Result
App should start

###### Actual Result
The following error message immediately appears: "Anki has encountered a problem, a report is being sent to the developers" and then the app crashes and returns to my phone's home screen

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
I can't get the debug info because the app never opens. As soon as I select the app, it gives me that error message and then crashes

This started about a week and a half ago (around Sep 1). Please let me know what other info I can supply.

Thanks in advance for the help.

**Comment by timrae** [comment]
Could you please tell us the version of Android, your device model, and the exact time in GMT that AnkiDroid sent the report.

**Comment by jazzeps** [comment]
Android version: 4.4.2Phone: Samsung Galaxy S3
I've sent numerous reports over the last week and a half, and I just sent three in rapid succession (Sep 13, 2016 1:25 am GMT / Sep 13, 2016 2:25 am London time). Hopefully you'll be able to see the device id and recognize the three reports in rapid succession.
Thanks again for your help.

**Comment by timrae** [comment]
Our crash report system seems to be playing up a bit at the moment. You're not doing anything unsupported like using a removable SD card or anything are you?

**Comment by jazzeps** [comment]
No. Nothing changed on my device from the time Ankidroid was working to the time when it stopped. I literally just woke up one day and Ankidroid started crashing..

**Comment by timrae** [comment]
Is your device a Verizon SCH-I535? Did the problem start happening 8 days ago? If so, your debug ID is 9a9daece-00b3-441b-b9df-d2b03136453d and it looks like somehow your models have become malformed. Can you mail your collection.anki2 file to me? 	

perceptualchaos2+anki@gmail.com

**Comment by timrae** [comment]
`Caused by: org.json.JSONException: Expected ':' after rtl:33, at character 45 of {"1350615140368":{"flds":[{"ord":0,"rtl:33,"rtl":false,"sticky":false`

**Comment by timrae** [comment]
If you edit the database and remove the erroneous  `"rtl:33` it should start magically working

**Comment by jazzeps** [comment]
Unfortunately, my collection.anki2 file is 36.7 MB, so yahoo mail won't allow me to email a file that big. Can I attach it here in github? Happy to do so, but I'll wait for your confirmation first.

Also, I'm happy to try to remove the erroneous "rtl:33" but I can't find it anywhere. I've opened both the collection.anki2 file and in the collection.media.ad.db2 file in Notepad and Sublime. In Notepad I find fragments of the string you reference above, but not the actual "rtl:33" string. In Sublime I just see a bunch of hexadecimal code. I'm not a very experienced programmer but if you tell me which file I should be looking in and what application I should use to view and edit it, I'm happy to try myself. Thanks for your help

**Comment by timrae** [comment]
You can use sqlitebrowser. There should be a field called models; copy the
content of it into a text editor and search for rtl:33.

If you can't figure it out you can upload to Google drive and email me the
link

**Comment by jazzeps** [comment]
Just sent you the Google drive link via email. Thank you.

**Comment by BarbaraKaterina** [comment]
I have exactly the same problem as jazzeps. The latest error report should be from 8:18 GMT 7th October. I have Samsung Galaxy S3 mini (GT-I8190N), android version 4.1.2. The problem has been going on for a long time, I just didn't get around to reporting it here until now.

**Comment by hssm** [comment]
Your crash: `Caused by: org.json.JSONException: Expected ':' after 1392644437314 at character 3313 ...`

One of your note types (which has the id of 1392644437314) has some malformed JSON in its configuration. Perhaps you can recognize it:
```
1392644437314"bqfmt":"",
"qfmt":"{{Zpět}}",
"ord":0,
"bafmt":"",
"did":null,
"afmt":"{{FrontSide}}\n\n<hr id=answer>\n\n{{Front}} \n<p>\n<div style='font-family: Arial; font-size: 20px;'>{{hint:latinka}}</div>\n\n<br>",
"name":"Card 1"
},
{
"bqfmt":"",
"qfmt":"{{Front}}\n<div style='font-family: Arial; font-size: 20px;'>{{hint:latinka}}</div>\n\n <p>\n<br>",
"ord":1,
"bafmt":"",
"did":null,
"afmt":"{{FrontSide}}\n\n<hr id=answer>\n\n{{Zpět}}",
"name":"Card 2"
}
],
"id":1350495317095,
"latexPre":"\\documentclass[12pt]{article}\n\\special{papersize=3in,5in}\n\\usepackage{amssymb,amsmath}\n\\pagestyle{empty}\n\\setlength{\\parindent}{0in}\n\\begin{document}\n",
"name":"Základní",
"vers":[

],
"latexPost":"\\end{document}",
"req":[
[
0,
"all",
[
  2
]
],
[
1,
"any",
[
  0,
  1
]
]
],
"css":".card {\n font-family: arial;\n font-size: 20px;\n text-align: center;\n color: black;\n background-color: white;\n}\n",
"usn":0
},
```

It seems to be missing a chunk in the beginning, too. Any ideas how it might have ended up that way? Does the collection open in the desktop client?

**Comment by BarbaraKaterina** [comment]
No idea. Everything seems to work fine in both desktop client and the
online version. When I tried to search for the ID of the card type in the
collection browser, I didn't find anything, so I tried deleting all the
types that seemed to fit the specs above, but it didn't help. I also tried
looking for the id in the "collection.anki2" file, and I deleted the one
deck it was associated in. That didn't help either...

2016-10-07 10:43 GMT+02:00 Houssam Salem <notifications@github.com>:

**Comment by hssm** [comment]
Send me the collection and I'll see if I can fix it.

**Comment by BarbaraKaterina** [comment]
Thank you so much!
http://expirebox.com/download/932a2f1f87220aaf80ae9bf9eeff567b.html

**Comment by hssm** [comment]
It doesn't crash for me. Config looks fine.

Since you are using the desktop client, I think you can just delete your AnkiDroid directory and sync it back.

**Comment by BarbaraKaterina** [comment]
Thanks so much, it works fine now. Should have thought of that myself,
really...
