### ISSUE TITLE
Can't download any Shared Decks

### ISSUE THREAD

**Issue by NyhteAngel13** [ankidroid/Anki-Android#4426]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. chose subject, Japanese
2. chose deck
3. download, and poof nothing

###### Expected Result

shared deck to be downloaded so I could import it into Ankidroid

###### Actual Result

starts download sometimes and then just says it can not download the file, I have tried with many different decks. I just downloaded some like 2 days ago no problem too.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by timrae** [comment]
Are you using Google Chrome? Is it the latest version? If not, have you tried updating it? Have you tried a different browser? This is a problem with your browser and/or device rather than a problem with AnkiDroid.
