### ISSUE TITLE
Text to be ignored by Text To Speech

### ISSUE THREAD

**Issue by MrDjango1976** [ankidroid/Anki-Android#4427]
Hi,
First of all - Anki & Ankidroid is great!

I'm just struggling with one thing. I would like to add comments on my cards giving a hint on the answer. Is it possible to define text that will be excluded by the Text to Speech engine?
If so, how to define that in my import file from Excel?

Simple example: 
Front: What is the capital of France? (Eiffel tower town...)
Back: Paris 

The text in brackets should be ignored by Text to Speech.

Any ideas are appreciated!

Thanks
Michael

**Comment by timrae** [comment]
Hi Michael, there's no built-in way to do this, but you might have some luck [using ssml](https://github.com/ankidroid/Anki-Android/issues/1463#issuecomment-153290180)
