### ISSUE TITLE
How to stop my cards showing both front and back information on the front card?

### ISSUE THREAD

**Issue by Grngo550** [ankidroid/Anki-Android#4428]
Some of my cards show both the front card information (question) as well as the back card info (answer) on the front card.

Why is this happening and what can I do to get it to show me simply front card information on the front and back card information on the back?

It seems that it is the production cards that are causing the problem (I think). If I deleted them I think I delete them for the whole deck and I don't know if that's a good idea.

Any help greatly appreciated.  It's driving me crazy.

----------------------------------------------------------------------------------------

[ x ] I have read the support page and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the manual and the FAQ and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by Grngo550** [comment]
It seems that it is the production cards that are causing the problem (I think).  If I deleted them I think I delete them for the whole deck and I don't know if that's a good idea.

**Comment by timrae** [comment]
You'll want to edit the template with Anki Desktop
http://ankisrs.net/docs/manual.html#cards-and-templates
