### ISSUE TITLE
Cards with cloze fields with same ID number give error 

### ISSUE THREAD

**Issue by rsuhada** [ankidroid/Anki-Android#4429]
Cards with cloze fields with same ID number give error in the App version of Anki while working correctly on the desktop version.

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
1. Create a cloze card with fields:

 {{c1::Cats}} and  {{c1::dogs}} are cute. 

###### Expected Result
Card displaying correctly with multiple cloze fields (e.g. like in the desktop version):

[...] and [...] are cute.

###### Actual Result
Error message that the card is broken.

Thank you very much!

**Comment by hssm** [comment]
What version of AnkiDroid are you on.

**Comment by hssm** [comment]
Going to assume you're on a really old version of AnkiDroid.
