### ISSUE TITLE
Force sync dl & restore backup messing up IDs

### ISSUE THREAD

**Issue by t0suj4** [ankidroid/Anki-Android#4430]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Create new AnkiWeb account
2. Force sync download with active decks on your device
3. Do restore from backup

###### Expected Result
Flawlessly restored backup

###### Actual Result
Messed up IDs, everything was assigned to the Default deck, looks like something was not executed in the correct order. Had to do manual recovery, I was luckily using only single deck.

**Comment by hssm** [comment]
Should be fixed in the next release.
