### ISSUE TITLE
[Feature Request] Material Design Best Practice - Swipe to Refresh gesture on deck overview activity

### ISSUE THREAD

**Issue by chap126** [ankidroid/Anki-Android#4432]
I always find myself swiping down on the deck page to synchronize with the anki servers. Is this a gesture that could be implemented on ankidroid?

**Comment by eginhard** [comment]
It has actually been implemented very recently. It's already available in the current alpha version, which you can find here if you don't want to wait for the beta or general release of the next version: https://github.com/ankidroid/Anki-Android/releases
