### ISSUE TITLE
Ankidroid not playing audio from videos.

### ISSUE THREAD

**Issue by RaphaBarros** [ankidroid/Anki-Android#4434]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open Ankidroid (my device is a Redmi 2).
2. Open a deck with videos.
3. Play the cards / answer of them. 
4. The video plays, but no audio plays.

###### Expected Result

The audio from the video should play. I've already tried these videos from my media collection on another player and everything plays fine.

###### Actual Result

No audio plays.

###### Debug info
AnkiDroid Version = 2.6.1

Android Version = 4.4.4

ACRA UUID = 17fb4df8-46de-4b8d-8715-146cc35bb33e

**Comment by timrae** [comment]
Hi, we just play the videos with the android system facilities... If they don't play then there isn't really anything we can do unfortunately. Some video apps have special codecs for playing more formats than those supported by the system, and I suspect this may apply in your case.

Do you know what container format and codec your videos are using? Also, what app did you use to play them?

**Comment by RaphaBarros** [comment]
They're MP4 and I played them using MX Player. Should I try converting the video format to see if they work? Is there any way for me to make ankidroid open the video on another player?

**Comment by projectthobunny** [comment]
Bumping this issue. I have never been able to get videos to play with audio on my Pixel. Surely there is something that can be done here.

Specifically, I created my videos using subs2srs with the "iPhone support" box checked. The videos are MP4.

**Comment by timrae** [comment]
MP4 is just a container file... you need to check what codec is used internally. Anyway, all the information that we can provide is on the FAQ in the media section, for example see this one and the subsequent sections about codecs.

https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

We cannot provide support on this issue further than what's written there. There is a test deck for video here that you can also use to check that AnkiDroid is playing video correctly. 

https://github.com/ankidroid/Anki-Android/blob/master/tools/test-decks/video.apkg?raw=true

As a side note, I can tell you that I have personally used subs2srs, and was able to get audio and video files generated from it playing on AnkiDroid. This was about 6 years ago though.
