### ISSUE TITLE
Error while syncing media

### ISSUE THREAD

**Issue by lahootian313** [ankidroid/Anki-Android#4435]
Hi
What is this???

**Comment by lahootian313** [comment]
![screenshot_20160921-101956](https://cloud.githubusercontent.com/assets/14838633/18700949/e2675940-7fe6-11e6-963a-ba2f2ea50ff1.png)

**Comment by lahootian313** [comment]
By the way would u please allow me to be a proofreader for this app on crowdin 
I am already a proofreader of tapatalk app and I have sent a request for that no crowdin 

Thanks

**Comment by hssm** [comment]
There is an error when trying to sync the media collection. Your normal collection is syncing normally, so there is no issue with that, but you will have some media file missing (or maybe just 1 file).

I could never figure out what was causing it, but I'm guessing there is a media file with a tricky filename that is causing issues. I had another user report this problem with a Russian locale. So now I'm wondering, if you switch your device language to US English and then sync, does the problem go away?


(I don't have admin right on crowdin so someone else will need to look into that.)

**Comment by lahootian313** [comment]
Sure when I checked my media it says 3 media aren't in the collection folder.
I changed my phone's language into Persian but the same result
That screenshot was captured when phone's language was English

As far as I remember it doesn't happen every time but because it wasn't very important to me I didn't care 

Anyway u mean I should tell another person to allow me to be a proofreader or do I need to do something else??

Thanks

**Comment by lahootian313** [comment]
@eginhard

Hi
A few days ago I upgraded my OS so everything must be wiped out . And when I downloaded all my decks from server this message isn't displayed anymore and when check my media it says 7 media are lost in media folder while it was already 3 

I thought may it helps
