### ISSUE TITLE
Error syncing

### ISSUE THREAD

**Issue by jiboiafc** [ankidroid/Anki-Android#4437]
![anki](https://cloud.githubusercontent.com/assets/22458589/18851704/8a5e354e-8413-11e6-984d-258c0bdc3bf4.png)

**Comment by jiboiafc** [comment]
What steps will reproduce the problem?
1. Click the sync button

What is the expected output? What do you see instead?
-For it to say that syncing was successful, instead i get an error (com.ichi2.anki.exception....) where it takes me to the error report screen.

Does it happen again every time you repeat the steps above? Or did it
happen only one time?
-It just started to happen this week, after I recently made a factory reset on my phone and reinstalled Anki.

What version of AnkiDroid are you using? (Decks list > menu > About > Look
at the title) On what version of Android? (Home screen > menu > About phone > Android
version)
AnkiDroid Version = 2.6.1
Android Version = 6.0.1
ACRA UUID = 14bf9678-1344-41e4-af47-1a0b12933559

Desktop version: 2.0.32

**Comment by hssm** [comment]
This is coming from the media sync portion of the sync. The error does say it's an internal server error so either the media sync server has a temporary problem or we are sending it some bad data.

Does it still happen?

**Comment by hssm** [comment]
Please see [this announcement](https://anki.tenderapp.com/discussions/ankiweb/1755-media-syncing-issues-and-possible-data-loss).
