### ISSUE TITLE
"Type in the answer" and autocomplete

### ISSUE THREAD

**Issue by steph643** [ankidroid/Anki-Android#4444]
###### Reproduction Steps

Suppose you are French and want to learn English. 
Because you are French, your device is configured with French as your default language. 

1. Enable the "type in the answer feature" (both in the options and in the cards)
2. Create a card [front="Deux", back="Two"] and run it.
3. In the input field, enter "Two" and hit Go

###### Expected Result

Anki displays a success message.

###### Actual Result

Anki displays an error message: expected answer was "Two" but you entered "Rio" instead.

Explanation: before closing the input field, Android autocomplete feature converts "Two" into "Rio" (closest match in its French dictionary).

Wrong idea: set your device to use English as a default language (instead of French). But in that case, the autocomplete feature gives you hints on the spelling of words!

I think there should be a way to turn the autocomplete feature off. This might even be the default behavior, as learning foreign languages is probably usage #1 of a flashcard app.

**Comment by eginhard** [comment]
What keyboard are you using and which version of Android are you on? Does the behaviour change when you enable/disable "Settings -> Advanced -> Type answer into card"?

With the Google and AOSP keyboards I can't reproduce autocorrections after submitting the card.

**Comment by steph643** [comment]
I'm using Fire OS version 7.5.1_user_5174320, which is the latest firmware for the Kindle Fire HD 7. I believe it is based on Android 4.4.4.

I'm using the native/default keyboard.

**When I disable "Settings -> Advanced -> Type answer into card", the problem is solved**: the autocomplete feature doesn't change the input text after submitting the card.

**Comment by steph643** [comment]
For those landing here: checking `Settings / Advanced / Type answer into card` is *not* required to enable typing answers in cards. This checkbox only changes the *look* of the input field.

**Comment by eginhard** [comment]
What's the default keyboard on Fire OS? You should be able to see it in Settings -> Language & Input on your phone. I guess it's a custom keyboard and an issue on their side. Do you see this behaviour in any other apps?

**Comment by steph643** [comment]
There is no keyboard name/model/id. And no way of changing the keyboard (all you can do is selecting the language).

I'm not sure this issue is keyboard-related, as it doesn't occur when `Settings / Advanced / Type answer into card` is unchecked (same keyboard in both cases).

Anyway, I am satisfied with the workaround and the Kindle Fire is not worth the effort. Thanks a lot for your time.

**Comment by ospalh** [comment]
AnkiDroid is trying to tell the keyboard that i should not generate auto completion texts. This has to be done slightly differently for the two differnt input boxes, the one in the card (☑Type answer into card) and the one between card and buttons  (☐Type answer into card), and different software keyboards may understand it the one way and not the other. In the end, there is not much more we can do about this.
