### ISSUE TITLE
Screen flashes white in night mode

### ISSUE THREAD

**Issue by zaz** [ankidroid/Anki-Android#4445]
Using 2.6.1, the screen flashes white for about 0.1s every time I press <kbd>SHOW ANSWER</kbd> or rate the difficulty of a card.  This is generally only noticeable in night mode.

Thanks.

###### Research

☑ I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid.

☑ I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue.

☑ I have searched for similar existing issues here and on the user forum:

  -  #2801 (closed) may be related, but is about lag as opposed to whiteness.
  -  #3077 (closed) may be related, but describes the problem as only affecting day mode.

**Comment by hssm** [comment]
Is there a chance the card template is performing lengthy work when a card is first rendered? Is there any javascript or complex css in your template? Large images? Is it a slow device?

**Comment by zaz** [comment]
I'm using an HTC Incredible S (1GHz Qualcomm 8255).  My decks are pretty standard, with very simple CSS and no images, and the problem affects all my decks.

**Comment by timrae** [comment]
I fixed this issue some time ago... It's working fine on my device (Nexus 5x), the emulator, and for many other users. Do you have any other devices that you can test on? I would assert that it's either an issue with your specific device, or an issue with your card template.

**Comment by CNG** [comment]
I have this issue, too, on the Mac client. I have not tried night mode, but my cards all have dark backgrounds. It started after I switched to an external stylesheet, which uses a couple of fonts, and some cards have simple JavaScript.

**Comment by timrae** [comment]
This issue tracker is only for AnkiDroid, the Android client. Anki desktop is not developed by us.

**Comment by CNG** [comment]
I understand that, and was simply contributing additional information on possible causes.
