### ISSUE TITLE
Feature request: case insensitivity when checking typed answer

### ISSUE THREAD

**Issue by steph643** [ankidroid/Anki-Android#4446]
_Not sure this should be posted here. I have the same request for Anki desktop, but don't understand yet how the two projects relate._
###### Reproduction Steps
1. Create a card [front="Deux", back="**T**wo"] with `{{type:Back}}`
2. Run it.
3. In the input field, enter "**t**wo" (notice the lowercase) and hit Go
###### Actual Result

Wrong answer, because of the lowercase **t**.
###### Expected Result

I would love a "case insensitivity" feature, so that the answer is considered right.

**Comment by steph643** [comment]
It seems this used to be solved in Anki desktop using an add-on. See [here](https://anki.tenderapp.com/discussions/add-ons/1071-re-surrect-case-insensitive-add-on-for-anki-2x).

**Comment by steph643** [comment]
This request is for case insensitivity when comparing the expected answer to the typed input. It is *not* about case sensitivity/mutation when editing a card (as discussed in https://github.com/ankidroid/Anki-Android/issues/3758 and https://github.com/ankidroid/Anki-Android/issues/3754).

**Comment by eginhard** [comment]
For Anki Desktop you can use this add-on: https://ankiweb.net/shared/info/1616934891

There is no add-on infrastructure for AnkiDroid at the moment and we wouldn't add an extra setting for this, which is just a minor cosmetic issue because in the end it's still you who has to judge whether you answered the card correctly.

**Comment by steph643** [comment]
I agree it is not worth the effort. But keeping a list of feature requests is good :-)

> in the end it's still you who has to judge whether you answered the card correctly

No, it's my young child. Which makes your point debatable.

**Comment by Juanjbb** [comment]
I would also love this feature. It does matter. Anyway, thank you for the good work!

**Comment by zoulja** [comment]
Can it be reopened?

**Comment by mikehardy** [comment]
We can always reopen things, are you planning on working on this issue to help solve it?

**Comment by zoulja** [comment]
This looks like classic `string1.toLower()==string2.toLower()` approach to me, so I think I will give it a try

**Comment by DerDemystifier** [comment]
Check https://github.com/DerDemystifier/AnkiIgnoreCase It's a simple script that re-evaleuates the typed answer without case sensitivity.
It's not an Add-on, so it works both on Anki Desktop and AnkiDroid.
