### ISSUE TITLE
Omit furigana when copying to clipboard

### ISSUE THREAD

**Issue by gkirilov** [ankidroid/Anki-Android#4447]
###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open in Study mode a card with a `furigana:` field
2. Long-press on the field to select some text
3. Tap 'select all' from the bar at the top
4. Tap 'copy' from the same bar
5. Paste the text in another app

###### Expected Result
The pasted text contains no furigana.

###### Actual Result
The furigana is shown as regular text after its kanji.
(The same thing happens if I 'share', instead of copy and paste)

I occasionally enter a wrong kanji when creating cards and, later, when studying, I have doubts about it.
I'd like to be able to quickly check with a dictionary app whether the word/phrase is actually a valid one.
Being able to copy/share it straight from the Study screen would be very handy for that, but since currently the furigana is mixed with the kanji, it has to be cleaned up first.
My current work-around for that is to open the Edit Note screen, select all in the field, and copy it.
A Tasker task is listening for clipboard changes, and when a new text that matches the `\[\p{Hira}+\]` regex is copied, the task strips all spaces and furigana annotations. Then I paste it in a dictionary.
I can't do such thing straight from Study screen, as furigana is not marked as such, it looks exactly like regular kana that might be part of the word/phrase.
It would be nice if furigana is omitted when copying text from Study screen.

**Comment by gkirilov** [comment]
I forgot to add, I did check desktop Anki - it doesn't omit furigana either.
Actually it's worse - it puts newlines, pastes the same kana twice... I couldn't find any logic in what was happening.

**Comment by timrae** [comment]
The copy and pasting is done by the Android system, so I don't think there is really much we can do unfortunately. I agree that it's annoying though, I have the same issue.

**Comment by gkirilov** [comment]
@timrae, it might be possible to use `user-select: none` CSS property to at least make the ruby text unselectable. Not sure, though.

**Comment by hssm** [comment]
It was a good idea, but unfortunately it still copies the unselectable parts even if they aren't selected. [Here's a demo](http://codepen.io/hssm/pen/ozEGgB).

**Comment by gkirilov** [comment]
I guess we'll have to wait until ruby text support is improved upstream.
Thanks for giving it a try, @hssm!

**Comment by timrae** [comment]
That demo actually works great on my device (Chrome on Nougat)

**Comment by hssm** [comment]
Hmm....Is your Chrome/WebView newer? Mine's on 53.0.2785.124

**Comment by timrae** [comment]
I have the same version of Chrome. Webview is *disabled*, apparently the [Chrome apk handles Webview rendering on Android 7](http://www.androidpolice.com/2016/07/20/google-explains-chrome-will-become-webview-android-7-0/)

**Comment by timrae** [comment]
![screenshot_20161007-185121](https://cloud.githubusercontent.com/assets/2818274/19186049/51726200-8cbf-11e6-85ea-11b20d194ca3.png)

**Comment by timrae** [comment]
Ah actually it is still copying the furigana, even though it isn't selecting it... lol

**Comment by hssm** [comment]
[Known issue](https://bugs.chromium.org/p/chromium/issues/detail?id=147490). Recently assigned too so maybe we'll even see a fix soon.

**Comment by Solarlark** [comment]
I've been thinking about asking about this for a while, and finally got around to checking today and see it's already been mentioned here, so that's good... maybe. :) Anyway, my situation is pretty much the same as Two-finger's. Is there any other work-around anyone's found?
