### ISSUE TITLE
"Interval Modifier" (and other percentage based) has precision issue: type 90 -> got 89%

### ISSUE THREAD

**Issue by Nexen23** [ankidroid/Anki-Android#4448]
###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. Long click on any desk
2. Tap `Desk options`
3. Tap `Reviews`
4. Tap `Interval modifier`
5. Type `90`
6. Tap `OK`
###### Expected Result

Interval modifier
90%
###### Actual Result

Interval modifier
89%

The same bug in any other percentage based desk prefs, like `Desk options` -> `Lapses` -> `New interval`. 
###### Debug info

AnkiDroid Version = 2.6.1
Android Version = 4.4.2
ACRA UUID = f356631b-222e-40ff-9a97-893bc3c5baaf

**Comment by hssm** [comment]
I've [been aware](https://github.com/ankidroid/Anki-Android/issues/2577) of this for some time but I don't think there is much we can do about it without a major change of some sort (like replacing the JSON library we use).
