### ISSUE TITLE
Anki tags (which I have put in card template) show in Anki Desktop but not in AnkiDroid

### ISSUE THREAD

**Issue by mx3214** [ankidroid/Anki-Android#4449]
[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

Put {{Tags}} in the front cards template via anki desktop

###### Expected Result
If cards are tagged, when reviewing a tagged card, the tags should show up on the front card.

###### Actual Result
If I use anki desktop any tagged cards have their tags listed on the front template. If I use ankidroid, tagged cards do not have their tags listed.

Attached is a photo showing how the tags show with anki desktop
![anki problem](https://cloud.githubusercontent.com/assets/14053275/19215092/60b68c32-8d8c-11e6-9446-6c3a26304b19.png)

**Comment by timrae** [comment]
This works fine on AnkiDroid, I have had it setup my own templates for years.... I suspect you haven't synced properly.

**Comment by mx3214** [comment]
@timrae 
Yes you are correct. Mystified as to why it hadnt synced properly, but I just synced again after reading your comment and the problem is resolved. Thank you.
