### ISSUE TITLE
Crash on Nougat in full screen mode with answer buttons hidden

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4451]
AnkiDroid Version = 2.7beta1

Android Version = 7.0

ACRA UUID = 005d2c15-788a-4a61-90e8-5da77e4f8693

**Comment by timrae** [comment]
```
java.lang.ClassCastException: android.support.design.widget.CoordinatorLayout$LayoutParams cannot be cast to android.widget.RelativeLayout$LayoutParams
at com.ichi2.anki.AbstractFlashcardViewer.initLayout(AbstractFlashcardViewer.java:1439)
at com.ichi2.anki.AbstractFlashcardViewer.onCollectionLoaded(AbstractFlashcardViewer.java:889)
at com.ichi2.anki.Reviewer.onCollectionLoaded(Reviewer.java:98)
at com.ichi2.anki.AnkiActivity.onLoadFinished(AnkiActivity.java:286)
at com.ichi2.anki.AnkiActivity.onLoadFinished(AnkiActivity.java:42)
```

**Comment by pipixiawomen** [comment]
I have the same issue , it happened only 8.0 system

android.widget.RelativeLayout$LayoutParams cannot be cast to android.support.design.widget.CoordinatorLayout$LayoutParams

android.support.design.widget.CoordinatorLayout.onChildViewsChanged(CoordinatorLayout.java:1221)
--
2 android.support.design.widget.CoordinatorLayout$OnPreDrawListener.onPreDraw(CoordinatorLayout.java:1814)
3 android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
4 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2516)
5 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1515)
6 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7266)
7 android.view.Choreographer$CallbackRecord.run(Choreographer.java:981)
8 android.view.Choreographer.doCallbacks(Choreographer.java:790)
9 android.view.Choreographer.doFrame(Choreographer.java:721)
10 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:967)
11 android.os.Handler.handleCallback(Handler.java:808)
12 android.os.Handler.dispatchMessage(Handler.java:101)
13 android.os.Looper.loop(Looper.java:166)
14 android.app.ActivityThread.main(ActivityThread.java:7425)
15 java.lang.reflect.Method.invoke(Native Method)
16 com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
17 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by mikehardy** [comment]
Interesting @229106948 - can you include what version of AnkiDroid you are on?

**Comment by mikehardy** [comment]
Unable to reproduce on Android 8 / API26
