### ISSUE TITLE
Standardizing all Card 1 Templates & All Card 2 Templates in the Same Deck;  Consolidating Separate Chinese Decks

### ISSUE THREAD

**Issue by tbeachglobal** [ankidroid/Anki-Android#4455]
I see now from what I've read that I really should fix some more fundamental problems before I sinc my laptop and my Android.

I.  Card 1 and Card 2 Templates: is there a way to name a template so that I can find it and select it when I want to use it and expect that it's going to function with new card they way it does with the old cards?  How do I replicate the fields in the cards that are working well.  If I need to delete every thing else, that may be OK since I don't have that many useful Chinese characters at this point.

2. After I standardize my templates, the next thing I need to do is consolidate all of my Chinese cards into one deck.  But I don't see how to rename the deck so that I can start creating sub-decks. 

Thanks for your help.

**Comment by hssm** [comment]
You will need to use the desktop client to do these things. It lets you rename note types and card types (templates) and you can use the browser to convert a large number of notes from one type to another in one operation using the "*change note type*" menu item.

Sub-decks are made by adding "::" to the name. Please see [the manual](http://ankisrs.net/docs/manual.html#decks).

**Comment by tbeachglobal** [comment]
Yes, I understand that part.  The question is:  how to fix a poorly
organized multi-deck system - all for the same language - once it's been
created.  One cannot simply drag and drop, right?

Also, I'm having a problem getting my 4  word forms  - English, Pinyin,
Chinese Character, and Part of Speech - to automatically appear in their
proper fields without me having to type each one in between the brackets in
their respective fields.  Can you direct me to exact section of the lengthy
manual that would help me fix these 2  problems, or would it be faster to
start from scratch?

Thanks again.

Timothy Beach

**Comment by hssm** [comment]
You will have better luck asking on the [Anki support forum](https://anki.tenderapp.com/home). This place is only for AnkiDroid bugs.

**Comment by tbeachglobal** [comment]
Thanks.

Timothy Beach
11714 Wallaby Ct
Stafford, TX 77477
www.LifeEnglishCoach.com

*And he gave some as apostles, others as prophets, others as evangelists,
others as pastors and teachers, **to equip the holy ones for the work of
ministry**,*
*for building up the body of Christ…*(Ephesians 4:11-12; New American
Bible)
