### ISSUE TITLE
Feature request: Study suspended cards

### ISSUE THREAD

**Issue by Mornon** [ankidroid/Anki-Android#4456]
Hoping this is the right place to do a feature request, sorry if it isn't.

I'm using AnkiDroid to study vocabulary, and to thin the deck when there is a term I know well I supend the note; I'd love to have a way to check from time to time all the suspended notes, to put back in the deck the ones I don't remember anymore. It there isn't a way to do something like these (I didn't find it), would it be possible to add it?

**Comment by eginhard** [comment]
You can display all suspended cards by searching for "is:suspended" in the card browser and then unsuspend them as you wish.

**Comment by Mornon** [comment]
Sure, but I was hoping to be able to have a way to study them like the normal study session (see the front, answer, see the answer, choose keep supended/unsuspend), instead of just skimming them in the list after filtering, to check if I still remember them. Not sure if this would be too much work, though.

Thanks for your reply.

**Comment by eginhard** [comment]
You can long-press on one of them, select preview and then cycle through the cards. There is no way to directly unsuspend them from there though (not in the Desktop version either), but potentially that could be added there (?)

**Comment by Mornon** [comment]
If you can cycle just through suspended cards (I don't have access to Anki now, I'll try later) that could work.

**Comment by timrae** [comment]
Yeah, there's a filter suspended option in the menu for the browser.
