### ISSUE TITLE
Fastlane to simplify our release procedure?

### ISSUE THREAD

**Issue by nicolas-raoul** [ankidroid/Anki-Android#4458]
https://github.com/fastlane/fastlane

Our release procedure is quite complex, so this tool might help?

**Comment by jaller94** [comment]
`fastlane supply init` is an automated way to download the data from the Google Play Store into the fastlane folder structure.

https://docs.fastlane.tools/getting-started/android/setup/

**Comment by mikehardy** [comment]
Hmm - I think this is interesting. As a release engineer in a previous life I always tried to make my deployments into fully automated single commands (that did the necessary verifications and fail-stops as part of the thing), so I like this. The real win here would be if we could automate supply across *all* the various markets that had AnkiDroid though.

@jaller94 - you mention f-droid but I didn't see a plugin for that, is it possible for instance to have a single command that would do a clean build, make sure tests passed, do the packaging and signing and push that signed package out to all the markets AnkiDroid is published on?

**Comment by jaller94** [comment]
As far as I know F-Droid contributers setup a build process and F-Droid builds the apk from source.

You don't need to export to F-Droid. It looks for the files itself. To trigger a build you need to create a Release on GitHub.

The automated builds for various stores are the idea of fastbuild, yes. AnkiDroid seems to support a lot of stores. Is there a full list available?

**Comment by nicolas-raoul** [comment]
Here is the release procedure, it only lists Play Store unfortunately: https://github.com/ankidroid/Anki-Android/wiki/Release-procedure
I used to post AnkiDroid to Amazon and Lenovo (China only) too, but I haven't done it for years, as it was taking a lot of time.
If fastlane could do it, that would be great :-)

**Comment by mikehardy** [comment]
Here is the list of places it has been posted previously: https://github.com/ankidroid/Anki-Android/wiki/Contributing#markets

I can see after reading a bit more that f-droid just consumes the data structures you put in place here after you make a github release - seems sensible

Sounds like fastlane would be a good idea - the more places deployed in a fully automated fashion, the better in my opinion. I left some comments as review on the pull request. Right now it looks like we use Triple T to do the Play store stuff, if fastlane could do that so we only have one set of stuff to maintain, that seems interesting to me but I don't know enough about the pain points for release to have an opinion that counts - just an academic interest

**Comment by mikehardy** [comment]
I have been doing releases now for a while, and I'm not against fastlane - I actually use it for iOS deployments in another project, I just don't see value. Anyone that wants to do this would have to drive it start to finish, asking for permissions they needed along the way.
