### ISSUE TITLE
Notification Issue

### ISSUE THREAD

**Issue by oleg-savoskin** [ankidroid/Anki-Android#4462]
The app doesn't show notifications on Samsung Galaxy S7 (Android 6.0.1) if the 'show notifications of cards in queue' (amount < 10) option is selected and widget is enabled.

**Comment by eginhard** [comment]
There is no option for showing notifications when less than 10 cards are due. The "Pending messages available" option will only show notifications for certain events, e.g. when a sync has finished or failed, but not when any cards are due.

**Comment by oleg-savoskin** [comment]
Yep, it's true. I had changed the language of UI from Russian to English and saw that was a translation error. But I think somebody should fix it because the meaning of that option is completely different.

**Comment by eginhard** [comment]
I removed the incorrect translation (it will become effective in the next release). There was one older Russian translation for this string (Доступные сообщения в очереди), can you confirm whether this has the correct meaning or add a better translation here: https://crowdin.com/translate/ankidroid/all/en-ru#q=pending+messages

**Comment by oleg-savoskin** [comment]
I've proposed a new one
