### ISSUE TITLE
FEN should show black's perspective when it is black's turn

### ISSUE THREAD

**Issue by jytou** [ankidroid/Anki-Android#4464]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Use a FEN in which it is black's turn, for instance: rnbqkbnr/pp1ppppp/8/2p5/4P3/2N5/PPPP1PPP/R1BQKBNR b KQkq -

###### Expected Result

The board should be showing black's perspective since it is black's turn.

###### Actual Result

The board is showing white's perspective.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
I'm not entirely sure what you mean by perspective. Correct me if I'm wrong, but chess boards always have black at the top, white at the bottom so that you know in which direction they need to move. You can include "Black to move" on the front side of your card to indicate whose turn it is. If you mean something different, an illustration of the intended result would be helpful.

**Comment by hssm** [comment]
Post screenshots of the problem and attach a sample deck.

**Comment by jytou** [comment]
I was definitely saying that it should be the reverse board (eg view from the black side's player - black at bottom, white at top) that should be shown when it is black's turn. It certainly doesn't prevent having a "black to move" or "white to move" text around, but if you want to learn openings it is definitely best to see the current player's perspective rather than the opponent's. Another way around this would be to be able to specify some switch of some kind on the [fen] marker to show the flipped board since I do agree that traditionally boards are shown with white at the bottom.

**Comment by eginhard** [comment]
Can you show me any popular chess applications that do this? I don't think this is usually done because board positions would be ambiguous then later in the game. Anyway, we would not add any options to customise the chess functionality because it's used by very few people.
