### ISSUE TITLE
FEN board should not be reversed in night mode

### ISSUE THREAD

**Issue by jytou** [ankidroid/Anki-Android#4465]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Switch to night mode. Look at a board generated from FEN.

###### Expected Result

The switch to night mode shouldn't change the board at all.

###### Actual Result

The whole board is reversed:
-board pieces' colors are reversed (blacks are whites and whites are blacks),
-board squares' colors are reversed as well.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
See #4468 for an improved night mode proposal and post there if you have any further suggestions.

**Comment by jytou** [comment]
Thanks, that seems to solve it, looks good!

**Comment by eginhard** [comment]
It will be included in the next release. To use it earlier, you can sign up for [beta testing](https://ankidroid.org/docs/manual.html#betaTesting). Or sign up for alpha testing at the same link to get it now already.

**Comment by abers** [comment]
How can I check within the app that I am running the beta version? I am supposedly a beta tester according to Google Play Beta Page but my FEN still shows the old style in night mode. Within Google Play on my phone AnkiDroid also shows up in the beta list under "My apps & Games". I have left the beta programme and rejoined to see if that fixes it if my phone was not downloading the beta version for some reason.
Also does AnkiDroid currently not display additional information about the position as the Anki desktop FEN plugin does? For example, in the starting position the desktop FEN plugin displays under the board: "White’s move. ♔♕♚♛, ep: -, ½: 0, M: 1".

**Comment by timrae** [comment]
A beta for version 2.8 has not been released yet, so you'll need to additionally opt-in for the [alpha program](https://ankidroid.org/docs/manual.html#betaTesting) to get this particular patch.
