### ISSUE TITLE
Dollar sign dropped from media file names in imported deck

### ISSUE THREAD

**Issue by snoyes** [ankidroid/Anki-Android#4466]
###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Create a media file containing a dollar sign, e.g. Test$Me.mp3
2. In the desktop Anki, create a deck and a note which contains [sound:Test$Me.mp3]
3. Export the deck, and import the resulting .apkg into AnkiDroid

###### Expected Result

The deck should be imported and the media should play.

###### Actual Result

The deck is imported and the card created with the media play button, but there is no sound heard.
Editing the note shows that the '$' character is not present in the media file name. Adding the '$' again corrects the issue and the media then plays correctly (meaning the media file itself is correctly copied with the '$' in the name; only the note content is altered).

The same behavior does not occur when importing into the desktop program.
The same behavior does not occur when the deck is created via syncing through an ankiweb account, only when using the Import procedure.

###### Debug info
AnkiDroid Version = 2.7
Android Version = 6.0.1
ACRA UUID = a8390c7d-d645-4f09-a620-baa733732bb4

**Comment by snoyes** [comment]
Example zipped .apkg attached.

[TestDollarSign.zip](https://github.com/ankidroid/Anki-Android/files/545859/TestDollarSign.zip)

**Comment by Icntaann** [comment]
Example zipped .apkg attached.
I think wie have 

[Icntaann_TestDollarSign.zip](https://github.com/ankidroid/Anki-Android/files/545874/Icntaann_TestDollarSign.zip)

**Comment by snoyes** [comment]
With Icntaann's file, the import fails - I get just a popup window with no text, and the deck is not created.

**Comment by hssm** [comment]
Thanks for reporting the bug and for providing the test case. This will be fixed in the next release.
