### ISSUE TITLE
HTML5 Video on anki templates?

### ISSUE THREAD

**Issue by gajewsk2** [ankidroid/Anki-Android#4471]
I remember seeing a PR before to allow for this but can't find it now or any documentation. What's the syntax to get something like `<video>{{Video}}</video>` working?

**Comment by hssm** [comment]
Something like this I think (I didn't test it):
```
<video autoplay>
  <source src="{{Video}}" type="video/mp4">
</video>
```

The "official" way is to follow the same syntax as sound files and let Anki determine if it's a video and play it in the external video player. So you would still do `[sound:myvideo.mp4]` inside your field (not template).

**Comment by gajewsk2** [comment]
Right,  this is not working for me with an avi src file. It autoplays the video but the html is just a dead video that cant be played. 

<video width="320" height="240" controls>
  <source src="{{Video}} " type="video/avi">
Your browser does not support the video tag.
</video>

**Comment by hssm** [comment]
It's only supported on Android 4.4+. Are you on an older version?

**Comment by gajewsk2** [comment]
Couldn't edit the snippet i posted above. : `<video width="320" height="240" controls>
  <source src="{{Video}} " type="video/avi">
Your browser does not support the video tag.
</video>`

I'm on 5.0.1 lollipop with newest official anki version.

**Comment by gajewsk2** [comment]
Still can't  edit,  but i removed the space after `{{Video}}`. No change though.

**Comment by hssm** [comment]
I don't think `video/avi` is valid. I believe only a limited set of containers and/or codecs work in the <video> tag.  If you replace `{{Video}}` with `http://www.w3schools.com/html/mov_bbb.mp4`, does it then work?

**Comment by MarekHappy** [comment]
Hello there, I got referred here to find answers about how to open Anki videos in different player than the standart one (to get accces of advanced options - like in VLC).

I have tested to change the default Video program in my Android (version 4.4.4), but Anki is like a bully and opens the video still the same way.

Has anyone found a solution how to setup the phone/anki to get into advanced options during video review time?

Right now I use this syntax: [sound:Name_of_the_video.mp4]

Thanks for any help,
Marek

**Comment by timrae** [comment]
The sound: method will always open it in the default player.
You might be able to use html5 in your card template to open it in a different player. You can start by reading this thread from the beginning.

**Comment by MarekHappy** [comment]
My programing skills are low... does anyone find a syntax how to open the videos trough html5?
- in a way, they are customized for faster video review speed

Thx big time for any input.

**Comment by timrae** [comment]
It would probably not be that difficult for us to support using custom video players. I'd welcome someone to submit a pull request for such a change. There are advanced means like html5 and `intent://` type URLs that might work but I haven never tried so can't provide any assistance with this sorry.

**Comment by seltzy** [comment]
@timrae I'd like to see using VLC instead since that's well supported on android, but I don't have time to implement it.
