### ISSUE TITLE
Add "Reschedule" option in card browser (like Anki Desktop)

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#4472]
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps

 Card browser ->Long press your card.Then you will see this UI

<img src="http://o8aucf9ny.bkt.clouddn.com/2016-10-24-15-50-53.png" height="400">
###### Expected Result

I hope this place add a option **Reschedule** like desk version(In desk version,the option is in your Card browser.you can see it in Edit->Reschedule.).It will help us to re-study that don't familar card.
###### Actual Result

(By the way,I hate this question template,I think the user of Anki should not be a step-by-step people.)
###### Debug info

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by Juddd** [comment]
@eginhard Glad to know this suggestion be mark as <kbd>accepted</kbd>.Thanks a lot.These day I try to think about this need.I think it's very necessary.And same to the **Preview** interface.

![](http://o8aucf9ny.bkt.clouddn.com/2016-10-27-18-18-45.png) 

I think here can add a button for "Edit" and "Reschedule".This can help us to find,edit and study these not very famliar card when we preview our card.

**Comment by david-allison-1** [comment]
Already completed
