### ISSUE TITLE
Make "Automatic display answer" wait for card audio to finish playing

### ISSUE THREAD

**Issue by ian-kelling** [ankidroid/Anki-Android#4473]
I'm going to work on implementing this feature. I'm new to the codebase. Any tips are appreciated.

**Comment by hssm** [comment]
The `Sound` class that's used to play audio has an inner class named `PlayAllCompletionListener` that's used to signal when all sounds have finished playing. You should probably start from there.

I think it's only used internally to the `Sound` class so you might have to expose it somehow. It's a pretty messy code path to be honest.

**Comment by ian-kelling** [comment]
Thanks

**Comment by ian-kelling** [comment]
I've got the code working how I want. I will send a pull request in the next day or so.
