### ISSUE TITLE
AnkiWeb "a network error has occured" message when syncing for first time on LG Nexus 5X with stock Android Nougat 7.1.1

### ISSUE THREAD

**Issue by Twoearle** [ankidroid/Anki-Android#4474]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Run a **fresh install (meaning no collections or previous user data** of Ankidroid on Android Nougat 7.1.1 Build Number 'NPF10C' 
2. Go to preferences ->settings -> AnkiWeb account
3. Enter your Ankiweb account login credentials (email address and password)

###### Expected Result
Successful login, first time synchronization including media (pictures and audio) and subsequent sync with other devices like desktop anki app. Basically what's expected of AnkiWeb all in all. 

###### Actual Result
When attempting to login, only the "a network error has occurred" message appears.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
**Debug Info**
AnkiDroid Version = 2.7

Android Version = 7.1.1

ACRA UUID = 0fde3b97-2902-4db6-bd1f-04f15d8165de

![screenshot_20161024-201044](https://cloud.githubusercontent.com/assets/12878675/19669718/f8f3a09a-9a37-11e6-8f84-c12506ecc410.png)

**Comment by hssm** [comment]
It works fine on an emulator running 7.1.1, so I don't think it's a problem with the Android version. Are you able to visit `https://ankiweb.net/` on your phone's browser?

**Comment by Twoearle** [comment]
Yes, i am. It only seems to be a problema when trying to login through the AnkiDroid app.

**Comment by Twoearle** [comment]
The problem was fixed by uninstalling and reinstalling. It might have been a problem when upgrading from Android 6 to 7 but I'll never know for sure. Thanks for the support regardless.
