### ISSUE TITLE
Ankidroid crashes on startup (Android 2.3) [Update: And will no longer open]

### ISSUE THREAD

**Issue by bigsmile01** [ankidroid/Anki-Android#4478]
###### Research

_Enter an [ x ] character to confirm the points below:_

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. Start AnkidDroid
2. It crashes
3. 

Note: It only effects Android 2.3. I have tested on later Android and it is fine. 
###### Expected Result

Start without crashing
###### Actual Result

Crashes on start up
###### Debug info

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.7

Android Version = 2.3.7

ACRA UUID = 867ef473-1e39-46b2-8619-473fec22e9ee

**Update: As of version 2.8alpha6, Ankidroid will no longer open after crashing, rendering the App unusable**

**Comment by nicolas-raoul** [comment]
Would you mind getting a "logcat"?
You might need to install the Android SDK.
Thanks for your patience and detailed feedback!

**Comment by bigsmile01** [comment]
Hi 

Whats the easiest way to get a logcat using Mac OSX? I have searched on Google, but a lot of the advice is either for Windows or doesn't work on Android 2.3.7 (i.e. it's written for Jelly bean and later).

It would be ideal if there was some app I could download to generate the logical.

**Comment by timrae** [comment]
The app "catlog" should work on android 2.3

**Comment by bigsmile01** [comment]
@nicolas-raoul 
@timrae 
Here is the catlog.
[logcat_and_device_info.zip](https://github.com/ankidroid/Anki-Android/files/684988/logcat_and_device_info.zip)

**Comment by hssm** [comment]
Seems to be a case of [this bug](https://code.google.com/p/android/issues/detail?id=225647). We need to update our support libs to the latest ones.
