### ISSUE TITLE
Sharing decks

### ISSUE THREAD

**Issue by lahootian313** [ankidroid/Anki-Android#4479]
Hi
Now we can share a deck and send it's link to others and put it on other websites  that's great
But there is a problem! 
Imagine I share a deck that is English to Persian and I want to put it on ankiWeb Persian to English as well
So what should I do?
Just to change the templates

Till now there is no problem
So please consider if after a year I want to edit one of them and add or delete some cards and add pictures or sounds and ...

I just edit English to Persian deck and by changing its templates  I can make a new deck Persian to English and share them again

So the problem begins here
 I will lose the links that I had put in other places 
So I wanna say please make a link permanent for a shared deck so we don't have to send new links to other places

**Comment by eginhard** [comment]
It is possible to update your shared decks: http://ankisrs.net/docs/manual.html#sharing-decks-publicly

(Also note that AnkiDroid is a project independent from Anki Desktop and the AnkiWeb service. Please use the [main Anki forum](https://anki.tenderapp.com/discussions) for anything related to Anki Desktop and AnkiWeb.)
