### ISSUE TITLE
parentNode.removeChild not working on Mobile, but on Desktop

### ISSUE THREAD

**Issue by amalekh** [ankidroid/Anki-Android#4480]
###### Research

_Enter an [ x ] character to confirm the points below:_

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum
###### Reproduction Steps
1. use parentNode.removeChild in Ankidroid
2. 
3. 
###### Expected Result

The node will be deleted as in the desktop version.
###### Actual Result

It will not be executed on Ankidroid, but it is executed on Anki desktop.
###### Debug info

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by hssm** [comment]
The desktop client uses a really old browser engine. I would always consider AnkiDroid's behaviour to be the correct one.

Anyway, this isn't the place to post template issues.
