### ISSUE TITLE
Images Broken on AnkiDroid - have tried every fix I can find!

### ISSUE THREAD

**Issue by chante77** [ankidroid/Anki-Android#4485]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

I added images to cards by dragging from google images. They show up on Anki Desktop.

###### Expected Result

The images sync to mobile and Ankiweb.

###### Actual Result

The images are broken on AnkiDroid (where I need it) and AnkiWeb (I don't use this, but the manual recommended checking whether the images showed here and they don't). See screenshots. (This is happening on ALL cards I've made myself (I've only starting making my own decks with images within the past week. Previously, I've never had trouble with images in decks I downloaded.)

I have also (based on reading manual, FAQ, etc.) done the following:
- uninstalled and reinstalled AnkiDroid
- assured that "fetch media" was enabled in ANkiDroid, and re-synced
- checked that the file name in Anki matched exactly the file names on my computer including case
- checked whether my files were impacted by an Anki error in Sept. (they weren't)
- checked that my file system is not vfat, fat32 (it's NTFS)
- tried both jpg and png images
-tried dragging directly from google to Anki AND saving to my hard drive first

Also, I'm receiving a sync error, which I've attached. I don't know enough to know whether it is related to the image issue or not. 

**I would really appreciate any help you could give. I'm not very computer savvy/don't know HTML, but I really want to use Anki successfully for language learning! THANK YOU!!!**

###### Debug info
AnkiDroid Version = 2.7

Android Version = 6.0

ACRA UUID = b893e6f9-2e80-4d10-a15d-38ebac11c6b7

I'm attaching any screenshots that might be helpful.

From Desktop Anki:

Card Format: ![card](https://cloud.githubusercontent.com/assets/23282417/20032894/2a715d84-a351-11e6-9f1f-95c52c5f19d1.PNG)

Image HTML: ![htmleditor](https://cloud.githubusercontent.com/assets/23282417/20032895/2f1cd070-a351-11e6-8a17-7c36c1a7330c.PNG)

Browser: ![browse](https://cloud.githubusercontent.com/assets/23282417/20032896/3406fac0-a351-11e6-9d48-3d7cadeda878.PNG)

Sync Error: ![syncerror](https://cloud.githubusercontent.com/assets/23282417/20032897/3c12fc0a-a351-11e6-9098-3da2246ab419.PNG)

From AnkiDroid:
THE BROKEN IMAGE ERROR 
[screenshot_20161103-060459](https://cloud.githubusercontent.com/assets/23282417/20032989/47f152ae-a353-11e6-902c-543c49abda59.png)

Editing mode in AnkiDroid:
![image](https://cloud.githubusercontent.com/assets/23282417/20032986/3541a9ba-a353-11e6-9a84-1ccb4e33593f.png)

**Comment by chante77** [comment]
![screenshot_20161103-060459](https://cloud.githubusercontent.com/assets/23282417/20033034/7aae03ee-a354-11e6-96e8-17e2b895acf0.png)

**Comment by hssm** [comment]
Your images are not being synced in the first place due to an error. On the desktop client, try using the `Tools -> Check media...` option and removing any unused media. Then try to sync again. If you keep getting the sync error, ask for help on the [Anki support site](https://anki.tenderapp.com/) since the problem is unrelated to AnkiDroid.

The error message tells you the file that is causing problems. Maybe the filename is too long. You can try removing/renaming that specific file if there aren't any others like it.
