### ISSUE TITLE
transfer decks from Samsung to Iphone

### ISSUE THREAD

**Issue by william301** [ankidroid/Anki-Android#4486]
Hello I have AnkiDroid on my SamsungA8 phone and I want to transfer 5 decks with 200flashcards to my new Iphone7.

How can I do this? Thanks in advance. 

And another issue. I noticed that Samsung uses Android and the app is called 'AnkiDroid' and is free to download.

But now with my Iphone I have to pay about 25 bucks for the app I already have. And the name is different, is called AnkiFlashcards or something but the logo is still the same.

Please let me know if I will have any problem and if is the same app. Thanks.
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
AnkiDroid is an app developed independently from other versions of Anki. However, you can [synchronise your decks via AnkiWeb](https://ankidroid.org/docs/manual.html#AnkiDesktop) and then study on your computer or iPhone as well.
[AnkiMobile Flashcards](https://itunes.apple.com/us/app/ankimobile-flashcards/id373493387?mt=8&ign-mpt=uo%3D4) is indeed the official iOS version of Anki. See [here](https://anki.tenderapp.com/kb/anki-ecosystem/why-does-ankimobile-cost-more-than-a-typical-mobile-app) for more information on the price.
