### ISSUE TITLE
Can't add picture to a note where the filename already exists in collection.media

### ISSUE THREAD

**Issue by duyang0627** [ankidroid/Anki-Android#4489]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. add a picture named "download.jpg" to a note A in desktop anki
2. sync on ankidroid
3. add another picture also named "download.jpg"(but content is different) to a different note B in ankidroid

###### Expected Result

note B should show the new picture from the phone. 

###### Actual Result

note B shows the picture from desktop. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.7

Android Version = 6.0

ACRA UUID = a02634b5-7c2e-4d97-b6f7-7e5cf80da90e

**Comment by eginhard** [comment]
Reproduced. When `x.jpg` exists in the media folder and another image with that name is added via *Add Image*, the latter is renamed to `x (1).jpg` while copying it to collection.media, which is why the former is shown on the card.

Thanks for the report!

**Comment by mikehardy** [comment]
Fantastic! A really really old bug bites the dust
