### ISSUE TITLE
Missing Characters copied from PDF

### ISSUE THREAD

**Issue by TheShadowKnows55** [ankidroid/Anki-Android#4490]
Issue:

I copied Chinese phrases out of a pdf file into Anki (Desktop) and synced with my Ankidroid. In the Ankidroid version, sometimes there are characters missing in the phrase - the whole phrase shows up in the Editing mode for my card, but not in the preview card, in the preview card there is only a space - If I copy that space to somewhere else, it shows me the character...

naturally I thought it has something to do with the fonts - I changed fonts and card type - but it did not help - The Desktop Version can handle it normally... but not the Ankidroid Version.

###### Reproduction Steps

1. Download this PDF File

[1. Text_Teil1_Masterübersetzung.pdf](https://github.com/ankidroid/Anki-Android/files/587468/1.Text_Teil1_Masterubersetzung.pdf)

2. Copy the first Sentence in Anki, Sync with Ankidroid
3. Check the Preview and the Editing Mode

Expected Result: The Preview should exactly show the Sentence I copied
Actual Result: A Few Characters are indeed missing.

**Comment by eginhard** [comment]
Try Google Noto, that's generally the most reliable font: https://ankidroid.org/docs/manual.html#customFonts

**Comment by TheShadowKnows55** [comment]
Hi,
thank you for the list - I did not find a nice Chinese font anywhere close to the "Kaiti" font sadly.

In any case - This does not seem to be a font issue, I changed fonts in the card-type, but the characters were missing anyway. In addition the font I had can easily process things like 革 or 干 - but It can't process them when I copy it directly out of this pdf file, nor can other fonts process those particular copied signs.

I can also reproduce this with the way described above - It's strange because changing the font to let's say the system font I have the exact issue.

**Comment by eginhard** [comment]
Could you attach a deck with one card where the characters work for you and one where they don't? For me everything works fine, so it does sound rather like a font issue. In addition to specifying a font in the card template, you also need to make sure it's actually added to your device as described in the Anki manual: http://ankisrs.net/docs/manual.html#installingfonts

**Comment by TheShadowKnows55** [comment]
Okay, file attached (had to package it since github doesn't allow filetype)
[_Fachvokabeln.apkg.zip](https://github.com/ankidroid/Anki-Android/files/587999/_Fachvokabeln.apkg.zip)

In the Vocabulary list there is an entry named 全面深化改革. (the rest is all working)

My Card Type wants this phrase to use a certain "KaiTi.ttf" It doesn't work with this, nor without it (standard Font)
I'm still using the somewhat older method for Ankidroid and have a "fonts" folder created...I'm not sure if that's the problem, since it works with all other cards in my other decks. I used Anki extensively since years and never came across this.

Thanks for the help btw.

**Comment by eginhard** [comment]
The character on the card (copied from the PDF) and the one in your previous post are different: https://unicodelookup.com/#⾰革/1

It might not be supported by that font, so I'd recommend using Google Noto as described above.
