### ISSUE TITLE
Example field for note by default 

### ISSUE THREAD

**Issue by nodje** [ankidroid/Anki-Android#4491]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

To my understanding there is a possibility to add any custom field on a note when using Anki desktop. I understand that this isn't possible in the droid version. 
Looking at the rich adding media possibilities though, I don't understand why it isn't possible to add a text field as attachment. 

My experience with language cards is that with any non trivial vocabulary, an example is compulsory for a thorough comprehension. 

So I'd like to suggest to add an example field by default, or a text field as media attachment. 

It feels like such a feature must have been asked in the past but I couldn't find a corresponding issue.

**Comment by eginhard** [comment]
This is also possible in AnkiDroid, via "Manage note types" in the overflow menu (3 dots on the top right) on the main screen. See the manual for more details: https://ankidroid.org/docs/manual.html#customizingCardLayout

**Comment by nodje** [comment]
Great, I couldn't find it, thanks

**Comment by nodje** [comment]
I've been able to add a new note type, with an example field. I've populated all my notes but there's a problem: I can't display that additional field when studying.
Is it possible to customise what is being displayed when showing the answer?
