### ISSUE TITLE
"Ooukw" issue

### ISSUE THREAD

**Issue by Balti92** [ankidroid/Anki-Android#4493]
I have this issue when my cards are displayed, that always appears these letters "ooukw" at the ending of the front side, and on the starting of the back side this "Rr". I searched the forum but didn't found any solutions. 
Additional Info: I have almost 500 cards in my storage and used html to adjust some cards textes to the leftside. 

[URL=http://www.pic-upload.de/view-32121313/IMG_20161115_113707.png.html][IMG]http://www2.pic-upload.de/thumb/32121313/IMG_20161115_113707.png[/IMG][/URL]
[URL=http://www.pic-upload.de/view-32121314/IMG_20161115_113634.png.html][IMG]http://www2.pic-upload.de/thumb/32121314/IMG_20161115_113634.png[/IMG][/URL]

**Comment by Balti92** [comment]
Sorey the pics aren't displayed

http://www.pic-upload.de/view-32121313/IMG_20161115_113707.png

http://www2.pic-upload.de/thumb/32121313/IMG_20161115_113707.png

http://www.pic-upload.de/view-32121314/IMG_20161115_113634.png

http://www2.pic-upload.de/thumb/32121314/IMG_20161115_113634.png

**Comment by flerda** [comment]
My guess is that you probably accidentally added these to your card templates.
You should just go ahead and edit those.

https://ankidroid.org/docs/manual.html#customizingCardLayout
http://ankisrs.net/docs/manual.html#cards-and-templates

**Comment by Balti92** [comment]
Okay you were right. That was the problem... Thank you so much for your quick response!
