### ISSUE TITLE
Feature Request: add "search card browser" on text selection

### ISSUE THREAD

**Issue by lostasock** [ankidroid/Anki-Android#4496]
Hi, I'd love to see "search card browser" added as an option when I select text on a card. The cards I use (Japanese sentences), they each build on each other, with only the new word or bit of grammar explained. Sometimes I forget words that have been explained before and need to look up the card where it was explained originally. Current workflow is to select, copy, go to card browser, paste. This process feels cumbersome and could be cut down a few steps.

**Comment by timrae** [comment]
Nice idea... This would be quite possible for Android 6+

**Comment by Profpatsch** [comment]
I’d like to see such a feature, too.

> This would be quite possible for Android 6+

I skimmed the code, it seems like the display of card text is handled by a [`WebView`](https://developer.android.com/reference/android/webkit/WebView.html). I couldn’t find an obvious way to hook into the copy & paste menu. I suspect using the long press event is not the way to go? What do you suggest instead?

**Comment by mikehardy** [comment]
This is actually implemented, but caused a different problem #5016 where you were then *stuck* in the card browser, but I have a PR for that in a second, so should be all good here

**Comment by timrae** [comment]
This is a hotfix candidate
