### ISSUE TITLE
Bug: A message about cloze deletion hasn't been translated

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4497]
###### Reproduction Steps

1. [Settings]>[AnkiDroid]>[Language]>Select a language other than English 
2. Add a new note using "Cloze" notetype, without any cloze deletions (`{{c1::example}}`) on the note.
![image](https://cloud.githubusercontent.com/assets/10436072/20453050/cb0ca800-ae5c-11e6-9d41-4a4115445542.png)

3. See the card on the study screen or on the preview of the card browser.

###### Expected Result
A translated alert message is displayed, as it is on Anki Desktop (as follows)
![image](https://cloud.githubusercontent.com/assets/10436072/20453033/3a04e476-ae5c-11e6-9548-26306339a217.png)

###### Actual Result
The untranslated alert message, `"Please edit this note and add some cloze deletions. (help)"`, is displayed.
![image](https://cloud.githubusercontent.com/assets/10436072/20453108/7a863070-ae5e-11e6-9854-99a12a18992b.png)

**Comment by mikehardy** [comment]
translations are in crowdin.com - if you don't have access Tim is the man

**Comment by timrae** [comment]
@snowtimeglass is a regular translator on crowdin, he's trying to say that the string is not on crowdin, it seems to be hardcoded into `Collection.java`

**Comment by mikehardy** [comment]
Ah - I see. I've certainly seen his contributions, I guess with the detail on some I was surprised it wasn't a link tot he code line - apologies @snowtimeglass 

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1053

Doing my best to triage some of the stale issues in the tracker but I'm all too human...

**Comment by snowtimeglass** [comment]
Thank you always, @timrae  @mikehardy 
Take your time!

**Comment by mikehardy** [comment]
I wish they were all that easy...
