### ISSUE TITLE
Wrong coloring of card type statistics pie cart when there are no unseen but some buried cards

### ISSUE THREAD

**Issue by Satans-Kruemelmonster** [ankidroid/Anki-Android#4499]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Have a deck with no unseen cards but with buried cards
2. Go to stats and scroll all the way right to the card-types-tab
3. Look at the pie cart for the deck mentioned above

###### Expected Result

The pie chart should look something like this (without the black slice for the unseen cards - I took this screenshot before learning today)

![with-unseen](https://cloud.githubusercontent.com/assets/387547/20529863/f466841a-b0d1-11e6-9e0d-600c1d8c1631.png)

###### Actual Result

The mature and young+learn slices are both colored black (which usually corresponds to unseen cards)

![without-unseen](https://cloud.githubusercontent.com/assets/387547/20529898/0d480076-b0d2-11e6-93ed-fc1ec60546e3.png)

###### Debug info

AnkiDroid Version = 2.7

Android Version = 6.0.1

ACRA UUID = 85905c5e-d225-446b-92e9-251e80c7b56e

**Comment by ashleypt** [comment]
Hi I am learning android development (I already know the Java language) and I've been looking for apps to contribute to. I love Anki so this would be a great one for me. I would like to take on this issue as I continue to learn though it may take some time as I'm still learning the basics of android development. If someone would is available to mentor me on this issue, I would be extremely grateful!

**Comment by hssm** [comment]
This was fixed in https://github.com/ankidroid/Anki-Android/pull/4463
