### ISSUE TITLE
audio file not found by AnkiDroid, but Anki finds it and it is existant. 

### ISSUE THREAD

**Issue by conrad-heimbold** [ankidroid/Anki-Android#4501]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Download the attached file and extract it. 
2. Import the included database in Anki (on Desktop), go to the answer of the only card and try to play the attached audio. 
3. Import the included database in AnkiDroid (on Android), go to the answer of the only card and try to play the attached audio. 

###### Expected Result
Both with Anki on Desktop and Ankidroid on Android, Anki* should be able to find the audio file and play it. 

###### Actual Result
Anki on Desktop finds the file and plays it, AnkiDroid does not play it / does not find it. 

If I use [sound:{{dateiname_fuer_audio}}] instead, AnkiDroid works; but that's not the perfect solution, since I would like to use a separate field for the audio file name. 

###### Debug info
AnkiDroid version: 2.7
Operating System: CyanogenMod 13.0 (based on Android 6.0.1)

[test.apkg.zip](https://github.com/ankidroid/Anki-Android/files/615133/test.apkg.zip)

**Comment by timrae** [comment]
Sorry, using fields to store file names [isn't officially supported by the Anki system](http://ankisrs.net/docs/manual.html#importing-media), so you're on your own with this one.

**Comment by timrae** [comment]
See also the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ#but-still-ankidroid-does-not-play-my-media)

**Comment by conrad-heimbold** [comment]
Let's say, the field {{audio_file_name}} contains [sound:test-file.ogg] instead of test-file.ogg. Where can I put that field in the HTML card template, so that a play button is rendered? 

If I put it inside an <span> element, it does not work. Will it work with a <div> element?

**Comment by timrae** [comment]
I'm not really sure sorry, feel free to ask on the forum, as this is the bug tracker.
