### ISSUE TITLE
Glosbe translations broken

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4502]
###### Reproduction Steps

1. Enter any word into the advanced editor
2. Press TRANSLATE

###### Expected Result
Translation successful

###### Actual Result
Translation failed

I guess they changed their API or something... :-/  

As [reported here](https://groups.google.com/forum/#!topic/anki-android/Cng2KGFxZTE)

**Comment by ashleypt** [comment]
@timrae Hi, I'd like to work on this one instead as I like working with APIs and the other issue wasn't marked as HelpWanted (didn't know that was a label here!)

I'm new to android dev though I'm familiar with the Java language syntax and have programmed in other languages before. writing smaller scripts. I've decided to become a contributor to AnkiDroid to practice my skills as I continue to learn android development. Any resources you can give would be much appreciated :)

**Comment by timrae** [comment]
@ghost
Sorry, it looks like I missed this... Udacity have some [free training](https://www.udacity.com/course/new-android-fundamentals--ud851) classes from Google which you might find helpful. Other than that, just picking a simple task and going through the source code trying to figure out how to do it yourself is  a great way to learn.
