### ISSUE TITLE
Character size & Saving UN & PW

### ISSUE THREAD

**Issue by tbeachglobal** [ankidroid/Anki-Android#4503]
I just got my Anki Android app up and running after getting my laptop version card working better.

2 simple questions:
1. How do I save my User Name and Password on my Android device?
1. How can I make the size of the Chinese characters appear larger so that I can 
a) see them without wearing glasses, and
b) keep the SOON, GOOD, EASY button at the bottom simultaneously in view without having to scroll to the bottom of the screen?
Thanks.
Timothy Beach

**Comment by timrae** [comment]
1) Do you mean save you AnkiWeb un/pw? Just press the sync button, and the first time you sync it will ask you to login, and remember them.

2) There's a "card zoom" setting in preferences
