### ISSUE TITLE
AnkiDroid 2.7 crashes on startup

### ISSUE THREAD

**Issue by kdmaas** [ankidroid/Anki-Android#4505]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. tap AnikDroid icon to start application
2. crashes
3. 

###### Expected Result
AnkiDroid opens and presents the available decks

###### Actual Result
Message:
AnkiDroid has encountered a problem; a bug report ...

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
Cannot provide debug info as described here (https://ankidroid.org/docs/help.htm), because AnkiDroid won't load.

Was using AnkiDroid successfully for the last time on 2016-12-09.
Having startup crashes since 2016-12-12.

AnkiDroid version 2.7
Android version 4.4.4/010 01

None of the following steps helped:
- Moving AnkiDroid from SDcard to Main Memory
- Clearing cache
- Uninstall and reinstall with Google Play
- Uninstall and reinstall 2.7 from FDroid
- Uninstall and reinstall of previous versions 2.6.1 and 2.6 from FDroid did not help either (same crash message)
I did reboot the phone between installations.

Any ideas?

**Comment by timrae** [comment]
Are you able to share your collection file? You can send it privately by email if required.

**Comment by kdmaas** [comment]
Dear Tim,

how do I do that?

Best regards,

Klaus

DigiScout Klaus Maas
tel:      +32 473 930 951
mail: klaus.maas@digiscout.net <mailto:klaus.maas@digiscout.net>
web: www.digiscout.net <http://www.digiscout.net>
------------------------------------------------------------------------

**Comment by timrae** [comment]
Go to the AnkiDroid folder on your phone with a file manager, and copy the
anki2 file to your pc or email it yourself or something

**Comment by kdmaas** [comment]
Completely forgot about the AnkiDroid data folder.
Thank you for the reminder.
My problem is solved.
Something in the data folder must have gotten screwed up which prevented AnkiDroid from loading properly.

Uninstalled AnikDroid.
Removed the AnikDroid data folder.
Rebooted
Installed AnkiDroid
Started AnkiDroid.
Worked like a charm again.

Logged in to the Anki server to sync my collections
Everything is back at normal now.

Thank you for your help / helping me to help myself.
