### ISSUE TITLE
Bug report about media sync.

### ISSUE THREAD

**Issue by mmjang** [ankidroid/Anki-Android#4507]
In this file ([MediaSyncer.java](https://github.com/ankidroid/Anki-Android/blob/develop/AnkiDroid/src/main/java/com/ichi2/libanki/sync/MediaSyncer.java)), starting from line 153, is the code for sync media files that is marked as deleted on server:

                            if (ldirty != 0) {
                            mCol.log("delete local");
                            mCol.getMedia().syncDelete(fname);
                        } else {
                            // conflict: local add overrides remote delete
                            mCol.log("conflict; will send");
                        }
                    } else {
                        // deleted both sides
                        mCol.log("both sides deleted");
                        mCol.getMedia().markClean(Collections.singletonList(fname));
                    }

And I have found the counterpart from anki pc client ([sync.py](https://github.com/dae/anki/blob/1dce3eaaff649e2c1dbfd53bfe289cf42971045e/anki/sync.py) line 775):

                    if not ldirty:
                        self.col.log("delete local")
                        self.col.media.syncDelete(fname)
                    else:
                        # conflict; local add overrides remote delete
                        self.col.log("conflict; will send")
                else:
                    # deleted both sides
                    self.col.log("both sides deleted")
                    ldirty and self.col.media.markClean([fname])

AFAIK, `if(ldirty != 0)` seems to be just the opposite of `if not dirty`. This makes it is *nearly* impossible to sync a file deletion to ankidroid (not a big problem, though). Hope you can fix this on next release. Thanks :)

**Comment by hssm** [comment]
Well spotted. Thanks for this, I'll put in a fix really soon.
