### ISSUE TITLE
Feature request: Speeding up the video's during review time (1.25, 1.5, 2x)

### ISSUE THREAD

**Issue by MarekHappy** [ankidroid/Anki-Android#4510]
###### Reproduction Steps
1. x
2. x
3. x

###### Expected Result
To be able to speed up the videos during review time. 

###### Actual state
Limited to really short videos.

Is there a way how to do it actually? Or are we limited by the Anki desktop structure. Thanks for answer.

**Comment by eginhard** [comment]
Videos are played via external players, so you'd have to change the speed there, if possible.

You could also try and [play videos via HTML5](https://github.com/ankidroid/Anki-Android/issues/4471) and then adjust the speed through Javascript: http://stackoverflow.com/questions/3027707/how-to-change-the-playing-speed-of-videos-in-html5

**Comment by MarekHappy** [comment]
I have tested to change the default Video program in my Android (version 4.4.4), but Anki is like a bully and opens the video still the same way.

Right now I use this syntax: [sound:Name_of_the_video.mp4]

Am i doing something wrong? Has anyone found a solution how to setup the phone/anki to get into advanced options during the video review time?

Thanks for any help,
Marek

**Comment by eginhard** [comment]
I don't think it's possible to specify a specific app for playing videos, AnkiDroid just uses generic video playing capabilities of your device as far as I know.

But as I wrote above you should be able to play videos directly on the card at custom speeds with HTML5.

**Comment by MarekHappy** [comment]
Thx for quick respond eginhard,

Sadly, I have hard time to test the HTML5 (total beginner in code).
Could you please write a short step by step instructions, how to set the card up to get the HTML5 code alligned with card?
