### ISSUE TITLE
statistics: cumulative answer lines start at 0,0 instead of the first interval

### ISSUE THREAD

**Issue by kimsuarez** [ankidroid/Anki-Android#4511]
###### Expected Result

cumulative answer lines start at the first interval

###### Actual Result

cumulative answer lines start at 0,0
looks super ugly
![screenshot_2016-12-23-09-30-35-01](https://cloud.githubusercontent.com/assets/15037586/21450224/0bf69e04-c8f5-11e6-816d-6de027acf596.jpeg)

**Comment by david-allison-1** [comment]
Don't know if this is a good first issue, but let's keep it open for a bit, it'd be nice to fix.
