### ISSUE TITLE
AnkiDroid calling /sync/finish when it shouldn't

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#4512]
Following up on #4366, which seems to have been closed for some reason.

I'm seeing quite a few instances of AnkiDroid 2.7 connecting to /sync/meta and then immediately calling /sync/finish, without ever calling /sync/start or other sync commands. This results in a bumped usn, and if AD is saving the returned value it would likely result in sanity errors.

I've changed the server to return a HTTP 409 in such cases, but the users are probably receiving an error now, so it still needs fixing on the AD side.

**Comment by dae** [comment]
Ok, it looks like Tim broke this in bebaf8ec. /sync/finish should only be called on a successful sync - currently if a sync is interrupted the only option is to wait a few minutes for the server side to be reverted.

**Comment by timrae** [comment]
Can you add a sync/abort feature to the protocol?

**Comment by dae** [comment]
Done - it requires the same args as finish and shouldn't be called if the sanity check failed or finish has already been called.

Happy Christmas by the way :-)

**Comment by timrae** [comment]
Thanks, does the media server have it as well??
Merry Christmas!!

**Comment by dae** [comment]
Media syncing doesn't need it, since it doesn't have to wait around until the final command to commit the changes.

**Comment by timrae** [comment]
Ok but we do need finish() right? Will abort return an error if received by
media sync server?

**Comment by dae** [comment]
There is no finish command in a media sync - calling either finish or abort will throw an error.

**Comment by timrae** [comment]
Ahhh ok I see, the class does have a finish() method but since it just
comes from the base class it doesn't do anything.
Thanks for the clarification!

**Comment by dae** [comment]
Thanks Tim :-)
