### ISSUE TITLE
Review time shows negative numbers

### ISSUE THREAD

**Issue by alvmunoz** [ankidroid/Anki-Android#4516]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x ] I have searched for similar existing issues here and on the user forum

This is a well-known issue reported in your forum:
https://anki.tenderapp.com/kb/problems/stats-screen-shows-negative-review-time 

However I cannot find the issue in github (the link is broken) and I would like to know its status.

Thanks

**Comment by hssm** [comment]
AnkiDroid had a higher incidence of this problem from of a bug which we fixed years ago. It's still not specific to AnkiDroid, though. Every Anki client is still susceptible to the problem if the clock goes back during review (e.g., DST).

It needs to be fixed as part of the Anki algorithm which is out of our control. You can use the add-on on the page you linked to repair your collection.

**Comment by alvmunoz** [comment]
@hssm , I am using the addon, but didn't fix my problem
