### ISSUE TITLE
Bug in adding screen - inconsistent field behaviour

### ISSUE THREAD

**Issue by Alphalpha007** [ankidroid/Anki-Android#4519]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Choose Basic(optional reversed card) as note type
2. Fill all three fields
3. Submit

###### Expected Result
"Front" field should have remained same and "Back" and "Add Reverse" fields should have gone blank.
This was the behavior until yesterday

###### Actual Result
"Front" and "Back" fields go blank and "Add Reverse" fields stays the same.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.7

Android Version = 6.0.1

ACRA UUID = 383c809a-d66b-4b86-a1c7-38710f1207eb

**Comment by timrae** [comment]
Are you using "sticky fields"?

**Comment by Alphalpha007** [comment]
Yes I am, in my computer.

**Comment by timrae** [comment]
They should get synced over to ankidroid... Have you tried syncing again?

**Comment by Alphalpha007** [comment]
Here's how the problem started:
1. Made the field "Add reverse" a sticky one in computer
2. sync anki in computer
3. sync ankidroid
4. now "Add reverse" is a sticky one in ankidroid

Does this look possible?
Is there any way to unsticky it without using my computer? I don't have access to it.

**Comment by timrae** [comment]
> Does this look possible?

Yes that's almost certainly what happened.

> Is there any way to unsticky it without using my computer? I don't have access to it.

There's no way from within AnkiDroid, sorry. It's kind of an "advanced" feature.
The only way you can fix it without A computer (it doesn't have to be YOUR computer), is to edit the raw collection.anki2 database on your phone using a third party sqlite viewer. Be sure to backup your collection properly, and it's all at your own risk, and we can't provide any support for this matter, blah blah. :-p

**Comment by Alphalpha007** [comment]
I had a hunch that this was what happened but never in my life thought that sticky fields got carried over to ankidroid - especially since there was no option for sticky field in it.

Thanks a bunch!
