### ISSUE TITLE
Collection import fails: This isn't a valid apkg file.

### ISSUE THREAD

**Issue by nolala** [ankidroid/Anki-Android#4520]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
YES - and issue #4401 fits my case. Unfortunately, it's a closed thread and the solution hasn't been posted.

###### Reproduction Steps

1. Exported collection and sent to myself before reinstalling my phone.
2. Followed manual instructions to import collection to newly installed Anki on my phone by placing the old collection into the right folder.
3. Selected correct collection file when prompted by import dialogue, error pops up: "This isn't a valid apkg file."

###### Expected Result
Successful collection import.

###### Actual Result
No import possible, not even of the first deck as mentioned in issue #4401. Please help.... thank you!!

**Comment by timrae** [comment]
Does the file import in anki desktop?

**Comment by nolala** [comment]
Hadn't reinstalled that yet, but I'll try right now!

**Comment by nolala** [comment]
(... I didn't, though, it was exported from AnkiDroid)

**Comment by timrae** [comment]
Thanks for the follow up!

If you are able to reproduce exporting an apkg from AnkiDroid that is not importable, then please share your collection (you can email privately if you prefer) together with the steps to reproduce in a new issue.

**Comment by timrae** [comment]
Actually you can post it here if you like haha.

**Comment by nolala** [comment]
I would - it's not accepting my zip-file though... what do I do?

**Comment by nolala** [comment]
(I have to admit I'm not sure how to email you the file... I'm new to github :) Thanks!!

**Comment by timrae** [comment]
perceptualchaos2 <-- gmail

**Comment by timrae** [comment]
Closed as I don't believe I ever received the collection (please correct me if I'm wrong)
