### ISSUE TITLE
Scrolling with whiteboard enabled and fullscreen disabled

### ISSUE THREAD

**Issue by LeopoldKellers** [ankidroid/Anki-Android#4522]
Hello,

I don't know whether it is a bug or a whishlist feature (in case the current implementation of the whiteboard makes it nontrivial to fix this). Please label accordingly!

When I have the whiteboard enabled in Ankidroid to scribble on a card that takes more space than can be displayed on my phone's screen, it is possible to scroll up and down by moving my finger on the right end of the screen when one of the two fullscreen modes is enabled in the setings. When I turn off fullscreen mode, the whiteboard draws on the area that was previously being used for scrolling when fullscreen was on.
Since I appreciate all of the information displayed when fullscreen is off but also have thousands of cards that are both large and require the whiteboard to be on, I would be very pleased if scrolling was made possible without having fullscreen turned on. My current workflow of enabling and disabling the whiteboard every time cries for improvement

Thanks for all your previous and future work on this invaluable piece of software!

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
**-> this might also help** #4443 

###### Reproduction Steps

1.  see above
2. 
3. 

###### Expected Result

see above

###### Actual Result

see above

###### Debug info

Version 2.7 from FDroid
Android 5.1.1 (CyanogenMod 12.1)

**Comment by timrae** [comment]
The right area of the whiteboard is disabled in fullscreen mode for a completely different reason actually: when the device is in landscape, it's necessary to use that area of the screen for swiping to exit immersive fullscreen mode. I was planning on eventually making the full whiteboard available again when in landscape, but have never gotten around to doing it.

It would be relatively easy to implement what you're requesting, and at first I felt it was a good idea as it adds consistency between the different modes. However, I'm a bit worried that users with small devices will complain that they now have less area available for drawing... 

The usual workflow is to use the toolbar button to hide the whiteboard when you need to scroll, but I guess that's not as convenient as what you're currently doing... Why don't you want to just leave fullscreen enabled? I have it on by default.

**Comment by longpu** [comment]
Wow, that was fast!

> The right area of the whiteboard is disabled in fullscreen mode for a completely different reason actually: when the device is in landscape, it's necessary to use that area of the screen for swiping to exit immersive fullscreen mode. I was planning on eventually making the full whiteboard available again when in landscape, but have never gotten around to doing it.

Ok, actually I had suspected something like this from reading your replies on some related requests.

> Why don't you want to just leave fullscreen enabled?

I guess it is simply a matter of preference. I like to have the bars there at a glance without having to pull them down. The extra space freed by going fullscreen would not be sufficent to prevent the need for scrolling anyway. But I guess I will keep it enabled as a workaround until you decide to revert to the old behaviour.
To be honest, I had already started to write a feature request asking for adding a scrolling feature to the whiteboard when I more or less accidentally discovered that it actually is already possible at the moment in fullscreen mode.

> However, I'm a bit worried that users with small devices will complain that they now have less area available for drawing...

You have a point there. How do you like the idea of having two finger scrolling added to the whiteboard? That way we could have both, usability on small screens and a more ergonomic user interface.

Hm, now that I think of it, implementing this would be a good opportunity to also add long/double tap to the whiteboard. Those clicks could be forwarded to audio replay buttons or hint fields below the whiteboard. That would make it even more usable as people would no longer need to separate whiteboard cards out into separate decks if they don't want to hit the enable/disable button frequently. E.g. maybe #4504 could be solved then while just keeping the whiteboard enabled all the time.

**Comment by longpu** [comment]
Did my proposal go a bit too far? Should it maybe be discussed on the forum first, since it probably would affect quite a few other users?

**Comment by timrae** [comment]
Are you proposing to implement it yourself? Or just requesting a feature? I don't really have time to work on new features these days, so unless you're going to do it yourself there isn't much more to discuss here IMO. Your idea sounds fine but I guess it would be s substantial amount of work

**Comment by longpu** [comment]
Kind of both... Thanks for your feedback! My Android programming skills are somewhat lacking, but I'll have a go at it and will try to do it myself (in a few months, after handing in & defending my thesis).

**Comment by timrae** [comment]
Ok nice, once you've played with the code and have a concrete implementation idea, please comment here for some feedback.

Good luck with the thesis!

**Comment by dotancohen** [comment]
How about enabling two-finger scrolling on devices that support multiple touch detection.

I study Ankidroid on two devices: a Samsung Note3 that suports multiple touch and a rooted Nook (e-ink device) that does not. It would be nice if the Note3 would scroll when using two-fingers yet draw when using one, even if that feature would not be available on the Nook.

**Comment by LeopoldKellers** [comment]
Ok, recently I had some spare time and spent two afternoons to read into Android programming and thinking about a way to implement the ideas expressed above.

I have already written some code that makes everything work. I have created a [pull request](https://github.com/ankidroid/Anki-Android/pull/4728), which is primarily intended for a discussion to improve my approach (hence you can find a description of the implementation details there). Ultimately I would be happy to have it upstreamed in the next release or so.
I have tested it on my own phone and everything seems to work well (at least with my workload). But since this is my first experience with Android programming, I am not in a position to be aware of special caveats there might be with regard to some fancy devices on which users might run Ankidroid somewhere out there.

I have implemented the following:
When drawing on the whiteboard, a second finger can be used to either scroll the card behind the whiteboard up and down or to tap on elements such as media play buttons or hint fields. As @dotancohen pointed out, only on multitouch-capable devices only of course.
The event of the second finger touching the screen always cancels/undoes the currently drawn stroke. The first finger must remain on the screen meanwhile.

If there are users who have a further use cases (I don't, so I haven't implemented any of the following) which require horizontal scrolling or zooming in/out on the card, it should be straightforward to adapt my approach for that purpose.
