### ISSUE TITLE
Keyboard should automatically expand for cards with a typing field

### ISSUE THREAD

**Issue by ChristianKleineidam** [ankidroid/Anki-Android#4523]
By using the MessagEase keyboard I fell in principle fast enough to type on my phone to answer cards that need typing. 

Unfortunately the keyboard doesn't automatically popup when I open a new card with a typing speed. Always having to click on the text field needs time that's unecessary. 

I would prefer if the text field would get automatically focused and the keyboard would expand.

**Comment by eginhard** [comment]
Duplicate of #3912
