### ISSUE TITLE
cards to review disappeared

### ISSUE THREAD

**Issue by asierrayk** [ankidroid/Anki-Android#4524]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
This bug keeps happening to me since I use anki from my mobile (ankiDroid), it doesn't happen on the pc version.

To replicate the bug you need to have more than one deck grouped in a folder (to get that you only have to put a common prefix and ::, for example language::English and language::Spanish)

When you review today's new cards of one of the deck then sometimes all the new cards of the other deck have disappeared in the process of reviewing the first deck. Obviously this have no sense. Did someone ever experience the same?

I hope, I had explained it clear. Thank you

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
Already answered in the group: https://groups.google.com/d/topic/anki-android/wDsbI1baQQs/discussion
