### ISSUE TITLE
Broken strings

### ISSUE THREAD

**Issue by hssm** [ankidroid/Anki-Android#4527]
Could somebody who has access to the Crowdin project remove these two translations:

https://crowdin.com/translate/ankidroid/8171/en-vi#2604631
https://crowdin.com/translate/ankidroid/7303/en-zhcn#6533382

They will crash in their respective language when encountered. I don't seem to be able to "delete" a translation, and if I set it to blank it won't save. I don't want to copy the original English in case it counts it as translated so translators skip over it.

**Comment by timrae** [comment]
Deleted, and added you as a manager
