### ISSUE TITLE
Replace the old-style main widget with new one

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4529]
like the "Add note" widget.
 ![image](https://cloud.githubusercontent.com/assets/10436072/21678136/c87d52a8-d380-11e6-9a5c-a2f7aa01a905.png)

**Comment by eginhard** [comment]
A user [suggested](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/anki-android/EAo7ybxIwBA/JgNTp04wAQAJ) to change the widget's color based on what types of cards are due.

**Comment by Anthropos888** [comment]
Two more requests:
1) please reduce the font size of the due number and time. The time often (not always) gets cut for numbers 99+

![Screenshot_20190417-094740~(1)](https://user-images.githubusercontent.com/45192213/56267497-f09ec080-6129-11e9-936e-df3208ca2c11.jpg)

On my phone the numbers are huge, at least 2x bigger than normal android notification numbers. So it could be easily read even with 50% size.

2) please split the due numbers in new/relearn/review (blue/red/green) im accordance to the way the numbers are shown during reviews. That would be consistent throughout the app.
With smaller font size it should be no problem to show all three numbers plus the time.

**Comment by adamwolf** [comment]
Do you have any details about your phone or launcher if you use an unusual
one?

**Comment by mikehardy** [comment]
I have noticed this myself in Nova Launcher. I think it may be in the standard one as well, unsure.

**Comment by Anthropos888** [comment]
My phone is Nokia 6 with Android 9 and stock launcher. 
One more thing is that the review counter only updates after opening Ankidroid. So it doesn't show the correct number of due reviews if I haven't used Ankidroid immediately before. That means, the widget can't be used as notification for due reviews. Is that the normal behavior? (battery optimization is turned off for Ankidroid)

**Comment by mikehardy** [comment]
Interesting - that is not the expected behavior. AnkiDroid receives the boot notification (or is supposed to) and starts up the widget updater (or is supposed to)

**Comment by Anthropos888** [comment]
Ok, then I guess it's an issue with the extremely strict power management of the Nokia software. Never mind. I care more about the font size of the widget (and the additional information for new/relearn/review cards).
