### ISSUE TITLE
'Marked' status of a card not up to date when done by changing the 'marked' tag in note edit mode

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#4531]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Start a review session and go to the first not-marked (no star) card to be displayed.
2. Click the 3-dot menu button in the upper-right corner, choose 'Edit note'.
3. Under tags, choose 'marked' (in Anki, cards are marked by simply adding the 'marked' tag).
4. Click the 'tick' button to apply your changes.

###### Expected Result
When returning to the review, the card should be displayed as marked, i.e. have the 'full' star icon.

###### Actual Result
The card is not up to date as far as the 'marked' status is concerned - it has the 'empty' star icon.

Similarly, when a card is already marked, editing it and removing the 'marked' tag doesn't update the icon to 'empty' star upon going back to the review.

###### Debug info
Version: 2.8beta3, but I have experienced the same behavior for a long time, so it's not a new regression.

**Comment by david-allison-1** [comment]
Can't reproduce. Appears fixed.
