### ISSUE TITLE
syncing with no Internet

### ISSUE THREAD

**Issue by dimm0k** [ankidroid/Anki-Android#4537]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Wi-Fi on, but no connection. Data on, but searching for signal.
2. Open AnkiDroid (set to sync on open)
3. 

###### Expected Result
AnkiDroid opens up directly in Decks

###### Actual Result
AnkiDroid attempts to sync forcing user to either wait or cancel the sync

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8beta3
Android Version = 7.0
ACRA UUID = 0f5d7e80-8eb1-4be1-9e8e-295ba460fdb4

not sure if it's because of Android Version 7.0 (Nougat) or something changed in AnkiDroid...

**Comment by eginhard** [comment]
Maybe the sync timeout can be set to something lower for the auto-sync on opening?

**Comment by dimm0k** [comment]
is it possible to have the old way? where it would check the internet connection before trying to sync and if there is none, go directly to Decks? I've noticed that in airplane mode this is exactly what happens, however when there's no cell/wi-fi reception then Anki gets stuck either waiting for a connection or it times out all the while still allowing the option to press back to cancel the sync. regardless, I think these options still take too long to get to Decks and start studying...

**Comment by timrae** [comment]
Afaik we never changed anything here, so you do have "the old way" already.
Personally, I disabled auto sync and prefer to use tree tasker intent to
sync when I plug my phone into the charger at night.

**Comment by dimm0k** [comment]
hrmm, do you have more details on this tree Tasker intent? I wouldn't mind doing it this way as well

**Comment by timrae** [comment]
Sorry it was just auto correct, "tree" > "the". Check the api documentation
on the wiki for info

**Comment by dimm0k** [comment]
thanks for the mention on using Tasker for the intent... I was hoping to use that to sync if there is a connection and then open AnkiDroid after the sync is complete, unfortunately it doesn't look like you can open AnkiDroid while the intent is in effect?

**Comment by timrae** [comment]
No you can't but you could call the ordinary AnkiDroid open intent afterwards I guess

**Comment by dimm0k** [comment]
is there a list of intents for AnkiDroid somewhere else? this is all I found https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API and it doesn't mention an open intent...

**Comment by timrae** [comment]
In Tasker I think you just go "open app" or something, then choose
AnkiDroid... You don't have to explicitly specify the intent as tasker will
do it for you. I haven't played with tasker for a long time though so I
might be wrong.

**Comment by mikehardy** [comment]
I just looked at this in my deprecation pass #5025 and we are using this API, I can't see how we can do better:

https://developer.android.com/reference/android/net/NetworkInfo.html#isConnected()

Previously it was a boolean OR with isConnected or isAvailable, and if you check API docs for isAvailable it says "always returns true as of Lollipop".

Which sort of justifies all the time I spent de-deprecating, this check would have been busted frequently up until a couple days ago...

**Comment by timrae** [comment]
So that's a bug fix right? Do you wanna port it to 2.8 hotfix?

**Comment by mikehardy** [comment]
Hmm - it was part of the massive deprecation blob so not cherry-pickable, but it is a very very local fix. I'll do a PR for that, sure.

**Comment by mikehardy** [comment]
Worth noting at least that those most affected (Lollipop and higher) won't be stuck on 2.8 as we can push updates to those APIs after Google Play Store closes the window on app updates for the old APIs
