### ISSUE TITLE
[IMG] not full 

### ISSUE THREAD

**Issue by loveAnkisomuch** [ankidroid/Anki-Android#4538]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
![screenshot_20170116-174307 - ss](https://cloud.githubusercontent.com/assets/23467449/21981332/779c1bd4-dc19-11e6-98c9-76e02b158408.png)

3. 

###### Expected Result
![screenshot_20170116-174307 - like](https://cloud.githubusercontent.com/assets/23467449/21981342/8251af80-dc19-11e6-804a-35f6614b28a1.png)

###### Actual Result
![2017-01-16_18-00-44](https://cloud.githubusercontent.com/assets/23467449/21981350/8fa65ed8-dc19-11e6-9c6f-3383f6264000.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
I don't know why the width is not big enough for this picture to show.

????? Thanks for your help!

**Comment by eginhard** [comment]
Please use the main Anki forum for anything related to Anki Desktop: https://anki.tenderapp.com/discussions

This page is only for the AnkiDroid project, which is developed independently from the other Anki versions.
