### ISSUE TITLE
Bug: After my tapping a notification of an reminder, an odd screen with the type answer box is sometimes displayed

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4540]
###### Reproduction Steps

I can't reproduce it freely for now, but I saw the bug at least 3 times, and I've never seen it in other situations. 
I hope this report will be a clue to fix this bug.

1. Tap an notification of a deck reminder.  

###### Expected Result
A standard study screen is displayed. 
- Its answer button is displayed under the front-side sceen area since I don't change the position setting.
- "Type answer box" won't be displayed since the deck doesn't have any cards which need typing.

###### Actual Result
An odd study screen as follows is displayed.
- An type answer box is displayed on the app bar.
- The answer button is above the front-side screen area, in disregard of the position setting.
- Its frond-side screen area (the area under the answer button) is empty.
- The answer button size is initialized.
- After I tap the answer button, the back-side screen won't displayed, the error message, `AnkiDroid has encountered a problem; a report is being sent to the developers…`, is displayed, and AnkiDroid is closed.

![image](https://cloud.githubusercontent.com/assets/10436072/22098524/12553c26-de6a-11e6-8906-0b7e0119f6a5.png)

@madhead, do you have any idea about this, in relation to #4450?

###### Debug info

- AnkiDroid Version = 2.8 
- Android Version = 4.3
- ACRA UUID = 37569256-61f7-43a1-9020-8f15fa254b16

**Comment by timrae** [comment]
I doubt this is directly related to #4450... It's probably a deeper problem with how the app reloads and redraws itself after receiving an `intent` to open the app.
