### ISSUE TITLE
audio volume changes when device gets a notification

### ISSUE THREAD

**Issue by dimm0k** [ankidroid/Anki-Android#4542]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. set volume to x and use Anki
2. silent notification occurs (email, text, Hangouts, etc)
3. 

###### Expected Result

volume remains at x until changed manually

###### Actual Result

volume remains at x, but once a notification occurs the volume is raised to max. really weird as almost all my notifications are set to silent so they show in the notification and status bar, but don't make a sound. this does not seem to affect YouTube or my music player (GMMP), as they both remain at the same volume even after receiving a notification

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8beta3
Android Version = 7.0
ACRA UUID = 0f5d7e80-8eb1-4be1-9e8e-295ba460fdb4

**Comment by mikehardy** [comment]
#5022 - should look at this when looking at media API refactor
