### ISSUE TITLE
syncMessage is ignored on successful sync

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#4545]
onPostExecute() appears to only show syncMessage when a sync fails, which means AnkiWeb has no way to send a message to the user without preventing them from syncing. The behaviour of the other clients when the message is non-empty is to show the message separately, regardless of the sync status. This enables us to give users a warning before an upcoming change (in this case, https://anki.tenderapp.com/kb/anki-ecosystem/email-verification), instead of immediately locking them out until they take action. AnkiDroid used to handle this correctly - it looks like it was broken in 82f5a58552ef0245694f68edaa2a2868c2d5e24c

**Comment by timrae** [comment]
OK I'll try fix this over the weekend

**Comment by dae** [comment]
thanks
