### ISSUE TITLE
Bug: Checking "Enable reminder notification for this deck" makes its notification on the status bar on the spot, unexpectedly

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4546]
###### Reproduction Steps

1. Create a new deck.
2. Add a card in the deck.
3. [Deck options]>[Reminders]

4. Check "Enable reminder notification for this deck"

###### Expected Result
The reminder won't be displayed on the status bar until you specify its time and tap "OK" and the specified time comes.

###### Actual Result
the reminder is displayed on the status bar promptly.
![image](https://cloud.githubusercontent.com/assets/10436072/22362330/325305c6-e4a5-11e6-877d-b491589c737d.png)

###### Video
[[Bug] Checking Enable reminder notification for this deck makes its notification on the status bar on the spot, unexpectedly.zip](https://github.com/ankidroid/Anki-Android/files/734537/Bug.Checking.Enable.reminder.notification.for.this.deck.makes.its.notification.on.the.status.bar.on.the.spot.unexpectedly.zip)

###### Debug info
Android 4.4
AnkiDroid 2.8

**Comment by mikehardy** [comment]
Similar to the notifications not firing at the same time I am unable to reproduce this one too. I'm downloading / installing an Android 4.4 emulator to see if that helps me see these.

**Comment by mikehardy** [comment]
I can no longer reproduce this in the alphas - to test them even I have to set a reminder close to now but in the future, then wait...
