### ISSUE TITLE
Updated sync domain

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#4549]
Hi guys,

When you have a chance, could you please have future AnkiDroid releases use sync.ankiweb.net? This can shave a few seconds off the sync in some cases by avoiding an extra SSL handshake. The previous endpoints will continue to work for the foreseeable future so we don't break older versions.

https://github.com/dae/anki/commit/04bc1a77668a358404d16377706b573f0cd09349

**Comment by dae** [comment]
I would need to set up an Android development environment to be able to test that syncing still works after the change is made, so this two line change would take me a lot longer than it would take you. Do you ask users who report a typo to send pull requests too? :-)

**Comment by timrae** [comment]
> I would need to set up an Android development environment to be able to test that syncing still works after the change

Well yeah, but you probably could have done that in the time you spent reporting the issue... Also next time you have a problem you wouldn't have to repeat that. Also, you wouldn't have to wait for one of us.

> This two line change would take me a lot longer than it would take you.

As you already mentioned, it's more about the testing time than the actual changes themselves. This is the same for both us.

> Do you ask users who report a typo to send pull requests too? :-)

If we knew for sure that the user was competent enough to do it, then yes, probably.

**Comment by dae** [comment]
Hi Tim,

This is a change that presents a (small) benefit to AD users, so I thought it was something the AD developers might want to implement. 

If you'd prefer I don't report things here unless I have an accompanying pull request, that's your prerogative and I'll respect your wishes.

**Comment by timrae** [comment]
> If you'd prefer I don't report things here unless I have an accompanying pull request

There's no such rule or expectation, but of course it's always nice to get a PR instead of yet another open issue. I do appreciate you sharing the information with us and I wasn't suggesting that you stop, I just feel that if the change were coming from my side, for sure I would have submitted a PR rather than an issue, so was curious... Anyway, I'll implement the change when I get a chance.

**Comment by dae** [comment]
Thanks for elaborating, and for accepting the report. I will try to prepare a pull request for cases like this in the future. It's been years since I've done any Java, so in cases where non-trivial code changes are required I may still need to defer to you guys :-)

**Comment by timrae** [comment]
Thanks, highly appreciated! 🙂
And yes of course, no problem.
