### ISSUE TITLE
File Names Containing a Circumflex Character Fail to Play

### ISSUE THREAD

**Issue by ochsner** [ankidroid/Anki-Android#4552]
###### Research
When I imported a French Pronunciation trainer deck from fluentforever.com, I noticed some of the MP3 recordings wouldn't play on my Kindle running AnkiDroid; however, they play fine on the Mac running Anki.

The recording that did not play had a file name containing a circumflex character. If I renamed the file and did not use a circumflex character, the recording played fine.

###### Reproduction Steps

1. Create a flashcard with a a recording referencing an MP3 file name containing a circumflex character, e.g., 66-âme-B2.mp3
2. View the flashcard
3. The recording is not played

**Comment by timrae** [comment]
Can you try installing three latest version from github please?

**Comment by ochsner** [comment]
Same glitch exists in AnkiDroid 2.8 installed via apkg.

**Comment by mikehardy** [comment]
Could maybe be tested as #5022 is examined

**Comment by david-allison-1** [comment]
Can't reproduce this.

@ochsner, Is this still a problem?
