### ISSUE TITLE
problem with playback of mp4 video formats in cards after updating to android 6

### ISSUE THREAD

**Issue by afshar62** [ankidroid/Anki-Android#4553]
recently I flashed my phone to android 6 and reinstalled ankidroid. the problem accord with cards containing video mp4 formats that I didn't have problem before. there is no problem with mp3 and images, but only mp4. 
I'm so frustrated and tired because it's one week that I'm searching but I can't find any soloution on this issue. please help me I have 2000 cards and it has taken me too much time.
phone model: sony m4 aqua
the media is playing correctly on Anki Desktop but not on AnkiDroid and the media files exist in my AnkiDroid/collection.media and I see the triangle mark in my card.
I test it with another phone with android 6.0 and there was no problem but in my phone with android 6.0.1 the problem exists.
 do I need to download codecs or something like that?
do I need to downgrade to android 5?
help please

**Comment by timrae** [comment]
I already replied to your thread on the forum, please don't double post:

https://groups.google.com/forum/#!topic/anki-android/Lk7x4Pc06Wc
