### ISSUE TITLE
Bug: apkg file isn't generated by "Export deck" 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4557]
###### Reproduction Steps

1. Export a deck 

  ![image](https://cloud.githubusercontent.com/assets/10436072/22614979/6b8cc866-eace-11e6-883f-56607e55836d.png)
Tap [OK]

![image](https://cloud.githubusercontent.com/assets/10436072/22614975/542f7a74-eace-11e6-81a7-331294d65ae1.png)
Tap [Cancel]

2. Search for the exported apkg file in `export` in AnkiDroid directory (default:`/sdcard/AnkiDroid`).

###### Expected Result
The apkg file exists, as it does in v2.8 as follows.
![image](https://cloud.githubusercontent.com/assets/10436072/22614959/02e9cec6-eace-11e6-9d12-3dc1e52d8d0d.png)

After it is tapped, the following popup is displayed.
![image](https://cloud.githubusercontent.com/assets/10436072/22615024/3d6c9960-eacf-11e6-9ad2-75e72e7963ad.png)

###### Actual Result
A folder named the deck's name exists, but the apkg file of the deck doesn't exist. 
![image](https://cloud.githubusercontent.com/assets/10436072/22615056/fc100de8-eacf-11e6-97b8-02f9c55e76c4.png)

After it is tapped, its content (empty) is displayed.
![image](https://cloud.githubusercontent.com/assets/10436072/22615090/7ad6057e-ead0-11e6-813c-ea34020c1341.png)

###### Debug info
AnkiDroid 2,8.1beta1 & 2.8.1beta2
Android 4.3

**Comment by timrae** [comment]
Thanks I'll try fix it tomorrow

**Comment by timrae** [comment]
@snowtimeglass 
This should be fixed in 2.8.1 beta3. You will probably need to delete the previous `ExportSample.apkg` folder, otherwise it will fail.

**Comment by snowtimeglass** [comment]
Thank you, it has been fixed. 
As you say, the `ExportSample.apkg` folder needed to be deleted beforehand.

>otherwise it will fail.

There seems to be a little bug in the error message. I'll report it later.
