### ISSUE TITLE
Bug: Unnecessary error message is displayed when sending an exported file with another app is merely cancelled

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4558]
###### Reproduction Steps

1. [Export deck] with a deck

2. Tap [OK]
 ![image](https://cloud.githubusercontent.com/assets/10436072/22614979/6b8cc866-eace-11e6-883f-56607e55836d.png)

3. Tap [Cancel]
![image](https://cloud.githubusercontent.com/assets/10436072/22614975/542f7a74-eace-11e6-81a7-331294d65ae1.png)

###### Expected Result
Sending the exported file with anotherr app is cancelled silently, as on v2.8 or before.

###### Actual Result
An error message, `Error sharing apkg file`, is displayed.

###### Debug info
AnkiDroid 2.8.1beta2
Android 4.3

**Comment by timrae** [comment]
This is actually the same as #4557
