### ISSUE TITLE
Bug: export_successful message lacks information of where the file exists

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4559]
On v2.8 or before, a full path is displayed as a filename. 
![image](https://cloud.githubusercontent.com/assets/10436072/22623265/baafcda2-eb97-11e6-9f5d-d689c64bd6ea.png)

On v.2.8.1beta1 and v2.8.1beta2, just a filename is displayed, but the message lacks information of where the file exists.
![image](https://cloud.githubusercontent.com/assets/10436072/22614975/542f7a74-eace-11e6-81a7-331294d65ae1.png)

It's incorrect as a filename on v2.8, while it seems insufficient on v2.8beta1.
  
How about adding something like `In "(AnkiDroid directory)/export",` to the beginning of the message?

**Comment by timrae** [comment]
If you choose to share it with another app, the file will not be accessible to you, so there's no meaning to show the path to users. The path will only be shown if you choose *not* to share the file with another app, at which point the file is moved to a location accessible to the user.

**Comment by snowtimeglass** [comment]
>If you choose to share it with another app, the file will not be accessible to you,

Is that so? 
I suspect that the message is ambiguous and misleading and the result is uneasy and inconvenience (Um, sorry), though I like the simplicity of the new `export_successful` message. 
How about saving the exported file in AnkiDroid directory even when it gets shared with another app, as v2.8 or before?

**Comment by timrae** [comment]
To do that we'd need to keep two copies of the exported file... One in the main ankidroid directory and another in the internal system ankidroid data directory. Since this is wasteful I feel most users would not like it.

**Comment by snowtimeglass** [comment]
>To do that we'd need to keep two copies of the exported file...

Have two copies been needed on v2.8 or before as well?

>and another in the internal system ankidroid data directory

Is it needed to send it with another app?
If so, can't it be deleted after sending the exported file?

**Comment by timrae** [comment]
> Is it needed to send it with another app?

We have to specify a permanent location from which to share the apkg with other apps. Since the user can change the AnkiDroid directory, it's not a feasible choice. Initially I went with an internal system folder, but after your message I realized a better solution is probably to just always use the default `sdcard/AnkiDroid/export` even if the user has specified a different location for the AnkiDroid folder in advanced settings.

Please try 2.8.1 beta4.

**Comment by snowtimeglass** [comment]
Good idea!
Thank you, I'll try it!

**Comment by snowtimeglass** [comment]
Thank you. It works expectedly.

However, I feel the full path is inappropriate as a name of "File", as I mentioned before. 
![image](https://cloud.githubusercontent.com/assets/10436072/22626035/502d78d0-ebe7-11e6-8d2f-1973f9b2df54.png)

How about something like `"In "(default directory)/export", File "(filename)" was exported. Do you want to send it with another app?"`?
 
(Of course, in this issue, there is no rush for v2.8.1.)

**Comment by timrae** [comment]
"(default directory)" is confusing IMO... But, what we can do is show the relative path `AnkiDroid/export/filename.apkg` when the user is using the default AnkiDroid directory location, and only show the full absolute path `/storage/emulated/0/AnkiDroid/export/filename.apkg` when they are using a non-default path.

**Comment by snowtimeglass** [comment]
>"(default directory)" is confusing IMO... 

I mean, what is really shown to users is `/storage/emulated/0/AnkiDroid/` or anything at that position.
I didn't have confidence in the path since `sdcard/AnkiDroid/` was displayed in the message on v2.8, as the first image above... 

>what we can do is show the relative path `AnkiDroid/export/filename.apkg` when the user is using the default AnkiDroid directory location,

I can't understand the reason why the relative path is shown when the user is using the default AnkiDroid directory location... The full absolute path will be helpful to inexperienced user who are using the default AnkiDroid directory and are searching for the exported file.  
![image](https://cloud.githubusercontent.com/assets/10436072/22627250/a9edd02a-ec02-11e6-91b3-16572786845e.png)
![image](https://cloud.githubusercontent.com/assets/10436072/22627269/1825f112-ec03-11e6-868b-92e0d80d7ab2.png)
(Incidentally, my AnkiDroid directory is `/sdcard/AnkiDroid`, maybe from the beginning. Is it regarded as non-default path?)

**Comment by timrae** [comment]
@snowtimeglass 

> I feel the full path is inappropriate as a name of "File"

> The full absolute path will be helpful to inexperienced user

You are contradicting yourself, and now I can't understand what you want...

> Is it regarded as non-default path?

No, on most modern devices, `/sdcard/` is a symlink to `/storage/emulated/0/`

**Comment by snowtimeglass** [comment]
>You are contradicting yourself, and now I can't understand what you want...

Sorry for the contradiction. I meant to say, in the second sentence you quote, the information of the full absolute path of the `export` folder (i.e. `/storage/emulated/0/AnkiDroid/export`) would be helpful.
ex.
 `"In "/storage/emulated/0/AnkiDroid/export", File "(filename)" was exported. Do you want to send it with another app?"`


>Most (the native Android 6 file manager included), completely omit the /storage/emulated/0/ part of the path and just show you the relative path from there, which is why I think it's more appropriate.

Oh, Is that so? I didn't know it. Thank you.
Sorry, I don't have time now. I'll comment again later today.
(I don't mean to say there is restraint on the release of v2.8.1.)

**Comment by snowtimeglass** [comment]
Thank you, I've maybe understood about the relative path. 
I feel that using the relative paths of the parent directory of the exported file is good.

ex.
 `"In "AnkiDroid/export", File "SampleDeck.apkg" was exported. Do you want to send it with another app?`

However, I feel that something like the following message is odd, all the same. 
`File "AnkiDroid/export/filename" was exported. Do you want to send it with another app?`


If you  are reluctant to divide the (relative or absolute) path of the exported file into two parts (the path of the parent directory and the file itself), how about something like the following one?
```
File was exported.
(AnkiDroid/export/SampleDeck.apkg)
Do you want to send it with another app?
```

**Comment by timrae** [comment]
> how about something like the following one?

Looks good to me, can you please create a new issue for it?

**Comment by snowtimeglass** [comment]
Sure :-) 
One moment, please.
