### ISSUE TITLE
Period '.' displays at wrong end of the line in RTL notes.

### ISSUE THREAD

**Issue by stu40** [ankidroid/Anki-Android#4565]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

Dear Ankidroid support team,

Let me start by saying this app is my favourite way to learn a language, and it's thanks to the volunteers like yourself that keep it functioning well. Great job.

I'm learning Farsi, a right-to-left (RTL) language, and I notice Ankidroid renders the period '.' symbol at the wrong end of the line, whereas in the desktop version it renders fine. Ankidroid renders correctly every other symbol (eg. ? and brackets) - only the period symbol.

1. Screenshot below of how it correctly looks in Anki for desktop.  Notice the period is at the far left of the Farsi script.

![anki screenshot with correct rendering](https://cloud.githubusercontent.com/assets/25576046/22636682/169722d8-ec91-11e6-90df-5c9377e19978.png)

2. Screenshot below of how it looks in Ankidroid. Notice the period is at the far right on the first line. 

![ankidroid screenshot cropped](https://cloud.githubusercontent.com/assets/25576046/22636831/1810b452-ec92-11e6-8d0a-eb77214ec95b.png)

3. Screenshot below of the note editor for that note. Though the sentence in question is enclosed in DIV tags, I've tried having the sentence without any tags, and the period still renders at the wrong end of the line.

![edit screenshot cropped](https://cloud.githubusercontent.com/assets/25576046/22636840/268e4b8e-ec92-11e6-93b1-2fc89f140a8f.png)

Thanks for your assistance,
Stu40

**Comment by timrae** [comment]
Which version of Android is this on?

**Comment by stu40** [comment]
Android 4.1.2. My phone is rooted with WanamLite Rom as well.

**Comment by timrae** [comment]
For sure it's a problem with the webview on your phone... If you upgrade to
4.4 it will be fixed. If this isn't feasible there might be a setting for
fixing Arabic somewhere.

We hide the setting on 4.4 and above I believe

**Comment by stu40** [comment]
I vaguely remember that setting for Arabic, but I just checked and I can't see it in Ankidroid. I was only worried that my shared Farsi deck will render incorrect on other people's phones, but if you say it renders ok on Android 4.4, then it's fine. Thanks for your assistance Tim.

**Comment by stu40** [comment]
Tim, I knew this wasn't an issue with Android, because I noticed the incorrect rendering in Ankiweb for my Farsi deck as well. I found the solution to my problem though. As per the Anki manual [https://apps.ankiweb.net/docs/manual.html#rtl-(right-to-left)-text](url) you need to add `<div dir=rtl>{{FieldThatHasRTLTextInIt}}</div>` to the Card Type which will display your right to left language. Having done this the period now renders at the end of the line correctly.
