### ISSUE TITLE
Bug: export_successful message describes path as filename

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4566]
On v2.8.1beta6 (and v2.7, v2.8, and so on), a path is described as a filename.
![image](https://cloud.githubusercontent.com/assets/10436072/22648224/fb142c90-ecb8-11e6-8e4f-78baabd7a414.png)
It's incorrect as a the name of "file".

It seems to be more appropriate to use a message like the following one. 
```
File was exported.
(AnkiDroid/export/SampleDeck.apkg)
Do you want to send it with another app?
```
[This issue is a response to #4559]

**Comment by milyukhin** [comment]
I think this can be closed, as I've just checked and got this working as expected:
<img width="318" alt="Screen Shot 2019-06-29 at 21 00 22" src="https://user-images.githubusercontent.com/6668375/60382026-23adea80-9ab1-11e9-9d7e-3769959307a4.png">

**Comment by mikehardy** [comment]
I half remember changing that :-) I will close but of course please comment if it is reproducible
