### ISSUE TITLE
SSL error when syncing - (v. 2.0.41)

### ISSUE THREAD

**Issue by dktch1** [ankidroid/Anki-Android#4567]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Run anki
2. Open profile / deck
3. When trying to sync states: Syncing failed:
'[Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib'

###### Expected Result
Sync

###### Actual Result
Syncing failed:
'[Errno 185090050] _ssl.c:340: error:0B084002:x509 certificate routines:X509_load_cert_crl_file:system lib'

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

Anki
Version 2.0.41
Qt 4.8.4 PyQt 4.10

**Comment by timrae** [comment]
Please file your report to the folks at Anki desktop.

*[I] am reporting a bug or enhancement request specific to AnkiDroid*
