### ISSUE TITLE
Bug: Garbled filename related to Google Drive

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4569]
###### Reproduction Steps

1. Export a deck
2. Send the exported file to Google Drive
3. Open it on Google Drive
4. Select AnkiDroid as the app for the file

###### Actual Result
The name of the exported file is garbled.

English version
![image](https://cloud.githubusercontent.com/assets/10436072/22693268/e2c0c748-ed85-11e6-8fa2-381fb93a1bf5.png)

Japanese version
![image](https://cloud.githubusercontent.com/assets/10436072/22693407/7df6096c-ed86-11e6-927c-5812fe03c06c.png)

###### Debug info
AnkiDroid 2.8.1
Android 4.3

**Comment by timrae** [comment]
That's the actual filename... If you use spaces or any non alphanumeric characters then it will happen. If we don't do that then we risk problems importing the files later

**Comment by snowtimeglass** [comment]
>That's the actual filename...

Can't it revert to natural filename, at least on the popup?

**Comment by timrae** [comment]
Reverting it just on the pop-up wouldn't make sense as it would be incorrect. @hssm do you think file name normalisation is required here? I forgot exactly what issue we are trying to prevent

**Comment by hssm** [comment]
Where exactly is the filename being escaped? I don't think we gain anything from doing it since the path is on the filesystem anyway (i.e., we're not transmitting it over a limited character set).

**Comment by david-allison-1** [comment]
Fixed in 80d40bdf1aff50e85724687b9067a8b019d9e520 (#6139)
