### ISSUE TITLE
Change the button of "again" from red to other colors

### ISSUE THREAD

**Issue by filipeon** [ankidroid/Anki-Android#4570]
From the paper "color and psychological functioning" it turns out that seeing red is not suitable for learning

**Comment by filipeon** [comment]
Red markedly reduces the score

**Comment by eginhard** [comment]
Thanks. When the front side of a card is shown to the user, the red "again" button is not visible. The user then tries to think of the correct answer and flips the card, revealing the actual answer and the answer buttons, but this doesn't change the answer that the user thought of, so the red colour shouldn't matter there whereas in the experiments described in the paper something red is shown before learning tasks.

It would be interesting though to find out whether the red button has a detrimental effect on remembering the following card, but I don't think that can be inferred from these experiments (e.g. AnkiDroid shows a number of other colours at the same time). We'd certainly be supportive of any such experiments using AnkiDroid, it would be easy to set up.

**Comment by filipeon** [comment]
I think that it is related to motivation and concentration, not a memory.  There are other studies that red makes people passive.  Certainly the proportion of red in anki is low, but if there is no reason to dare use red, it will be better to eliminate that element than not, so that we make the most of Anki.

**Comment by mikehardy** [comment]
No proposal or PR here - please reopen if there's a concrete idea
