### ISSUE TITLE
Overlapping messages about syncing conflict

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4572]
The other day, after "Synchronization" tapped, the following message, which I had rarely seen, was displayed on v2.8.1.
```
Sync error
After syncing, the collection was in an inconsistent state. 
To fix this problem, AnkiDroid will force a full sync. 
Choose which side you would like to keep.

[REMOTE]    [CANCEL] [LOCAL]
```
After tapping [CANCEL] in it, I tapped "Synchronization" again, then the following familiar message was displayed.
```
Syncing conflict
You must either upload this collection or download it from Ankiweb, as they can’t be merged. 
The collection on one side will be overwritten.

[CANCEL]    [DOWNLOAD] [UPLOAD]

```
![image](https://cloud.githubusercontent.com/assets/10436072/22852829/4118bb2a-f088-11e6-9e16-56612f81cbd9.png)

I suspect the role of the first message above and the second one overlap, and the first one might be a vestige or something.
Is there any necessity to display the first message in particular situations? 

###### Debug info
AnkiDroid 2.8.1
Android 4.3

**Comment by mikehardy** [comment]
The code performs a pretty in-depth sanity check where failures will throw up the first dialog. You can grep for "sanityCheckError" to see it. The second one is the result of canceling in response to the first - now they are just in conflict and one has to go
