### ISSUE TITLE
Why the card in my ankidroid on phone always lost in several days?

### ISSUE THREAD

**Issue by luofeiyu** [ankidroid/Anki-Android#4580]
It is tested that my card  in my ankidroid on phone always lost in several days,what result in the effect?
How to fix it?
The card in my anki  on pc platform does not lost.

**Comment by timrae** [comment]
Could you please post some screenshots to demonstrate what exactly is happening, as it's not clear from your description what "lost" means.

**Comment by eginhard** [comment]
Are cards actually lost, i.e. you can't find them in the card browser? Because of the spaced repetition, you won't see each card every day, see https://apps.ankiweb.net/docs/manual.html#introduction

**Comment by luofeiyu** [comment]
Many thinks ,cards are not lost actually ,cards are lost virtually,in some way it can be activate,i am not familiar this tool--ankidroid.

**Comment by eginhard** [comment]
Please read the manual about spaced repetition, this behaviour is expected: https://apps.ankiweb.net/docs/manual.html#spaced-repetition
