### ISSUE TITLE
DeckPicker NullPointerException (corrupt collection?)

### ISSUE THREAD

**Issue by bjornmartensson** [ankidroid/Anki-Android#4581]
Separating this from [issue 3576](https://github.com/ankidroid/Anki-Android/issues/3576).

I seem to have a reproducible corruption problem. My repro steps:

1. Modify my collection on my PC in a way that requires a full upload.
1. Sync PC -> AnkiWeb.
1. Sync AnkiWeb -> AnkiDroid

Result:
AnkiDroid has a problem and sends a report somewhere. I don't think it said anywhere that the collection is corrupted, but it seems to me that it is corrupted because I have well over 150 "old" questions scheduled every day, and after this crash, I had zero "old" questions scheduled. Only some brand new questions showed up.

This happened two days (2017-02-12) and yesterday (2017-02-13) and I seem to be able to reproduce this any day now. Before Feb 12, this never happened to me.

Stack trace (thanks @timrae!):
`java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
at com.ichi2.anki.DeckPicker.showSyncLogMessage(DeckPicker.java:1097)
at com.ichi2.anki.DeckPicker.access$1000(DeckPicker.java:110)
at com.ichi2.anki.DeckPicker$18.onPostExecute(DeckPicker.java:1555)
at com.ichi2.async.Connection.onPostExecute(Connection.java:143)
at com.ichi2.async.Connection.onPostExecute(Connection.java:50)`

**Comment by timrae** [comment]
I'm pretty sure this has nothing to do with corrupt collections, it looks like a bug introduced by #4548

**Comment by timrae** [comment]
Please try the new beta version

**Comment by bjornmartensson** [comment]
This worked, thanks!!
