### ISSUE TITLE
Samsung Chromebook Plus - can't syncrhonize media

### ISSUE THREAD

**Issue by music-ismath** [ankidroid/Anki-Android#4584]
###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Install AnkiDroid from Google Play Store on Samsung Chromebook Plus
2. Sign-in and attempt to synchronize

###### Expected Result

Full deck synchronization including media

###### Actual Result

Card text appears to synchronize, but media does not (broken images). Receive error java.io.IOException: open failed: ENAMETOOLONG (File name too long). I do not receive this error when synchronizing on my Moto G4.

###### Debug info

AnkiDroid Version = 2.8.1
Android Version = 6.0.1
ACRA UUID = af55cf08-2e9f-4276-8404-df0c3f3e0d17

**Comment by music-ismath** [comment]
Is there any additional information/troubleshooting I can provide?

**Comment by eginhard** [comment]
We can't provide much support for chromebooks at the moment unfortunately (none of the developers use one).

Do you have any media file names longer than 143 characters and can shorten them? https://bugs.chromium.org/p/chromium/issues/detail?id=402794

**Comment by music-ismath** [comment]
Well, good news - on your suggestion I removed media files with long filenames; I had a few that were extremely long. Although I haven't used it intensively, it appears to be working now. Thanks for your help!
