### ISSUE TITLE
Crash on add picture from camera on Android 7

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4586]
Seems like a similar permissions issue to the crash when emailing apkgs that I recently fixed

```
android.os.FileUriExposedException: file:///storage/emulated/0/Pictures/img_201702162214361518016482.jpg exposed beyond app through ClipData.Item.getUri()
```

**Comment by dinorastoder** [comment]
I have same issue with both versions v2.8.2 and v2.9alpha4.

Steps to reproduce
1. Press on + and choose Add card
2. Press on attach and choose Add image
3. Select Camera

Here is my debug info:
AnkiDroid Version = 2.9alpha4

Android Version = 7.0

ACRA UUID = 7b59c410-9be8-4f99-8be1-0b634cca407f
