### ISSUE TITLE
"Empty Cards" deck option crashes AnkiDroid

### ISSUE THREAD

**Issue by DinnerBuffet** [ankidroid/Anki-Android#4587]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

This issue started recently (within the last month). It does not happen on the PC version.

###### Reproduction Steps

1. Delete content related to a card (in my case, I'm deleting a reference to a TTS sound file) and save the note.
2. Select "Empty Cards"

###### Expected Result
empty card is now deleted

###### Actual Result
crash

###### Debug info
AnkiDroid Version = 2.8.1

Android Version = 6.0.1

ACRA UUID = a78dc287-9736-4b0d-a3e1-10d98f3928e9

**Comment by daniel-light** [comment]
I'm getting this as well. AnkiDroid version is `2.8.1`, android version is `7.1.1`. ACRA UUID is `708f3a70-0475-4ad4-aca0-3d8654ba0362`.

**Comment by timrae** [comment]
Please check the latest beta version for a fix

**Comment by daniel-light** [comment]
@timrae thanks for the fix! and more generally, for all the work on the app :)

**Comment by DinnerBuffet** [comment]
Confirmed fixed. Thanks!
