### ISSUE TITLE
Bug: Popup window won't be displayed on the "Edit fields" screen without detaching your finger from the screen

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4592]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. [Manage note type]
2. Tap a note type
3. Long-tap a field

###### Expected Result

A popup window is displayed automatically without detaching your finger from the field, as it is done on other screens of this app.

###### Actual Result

Nothing happens as long as you keep touching the field.

###### Debug info

Android: 4.3
AnkiDroid 2.8.2beta3 & AnkiDroid.C 2.5beta16

**Comment by eginhard** [comment]
Opening the pop-up menu is the only possible action for the fields and is therefore triggered by a simple "tap".

**Comment by snowtimeglass** [comment]
Oops, sorry! I had a misunderstanding. I blush for it.
