### ISSUE TITLE
Crash on delete note type

### ISSUE THREAD

**Issue by st603** [ankidroid/Anki-Android#4593]
:(

**Comment by Ana06** [comment]
I also get the same error. 

AnkiDroid version: 2.8.1

Android version: 7.1.1

**Comment by Ana06** [comment]
It also fails when adding a new field in a note and try to save it :confused:

**Comment by eginhard** [comment]
Duplicate of #4594

**Comment by Ana06** [comment]
@eginhard

> Duplicate of #459

Not really, #459 is about editing a note type and this is about editing/deleting a note template. So, I think they are unrelated and we should merge this two issues

**Comment by eginhard** [comment]
I had updated that issue to reflect that. Anyway, it was the same underlying issue in both cases and should now be fixed in the latest beta: https://ankidroid.org/docs/manual.html#betaTesting
