### ISSUE TITLE
Crash on change/delete note type

### ISSUE THREAD

**Issue by Ana06** [ankidroid/Anki-Android#4594]
###### Reproduction Steps

1. Edit the type of a existing note from `basic` to `basic (and reversed)`
2. Click the ok button

###### Expected Result

It changes the note type and create an extra card.

###### Actual Result

It fails, shows an error Toast and doesn't update the note type neither create the extra card. :sob:

###### Debug info

AnkiDroid version: 2.8.1

Android version: 7.1.1

**Note:** this only fail if you change the type of the card, updating any field works perfectly. :wink:

**Comment by eginhard** [comment]
Fixed in the latest beta: https://ankidroid.org/docs/manual.html#betaTesting
