### ISSUE TITLE
AnkiDroid not in "Open with" list after downloading shared deck

### ISSUE THREAD

**Issue by nicolas-raoul** [ankidroid/Anki-Android#4596]
###### Reproduction Steps

1. Download shared deck
2. Once downloaded, click on the notification bar item
3. The "Open with" dialog opens:

![screenshot_20170227-155904](https://cloud.githubusercontent.com/assets/99590/23351720/27fd404a-fd06-11e6-8f9c-99af0d1f29a3.png)

###### Expected Result

I expect AnkiDroid to be one of the options.

###### Actual Result

Not AnkiDroid in the list, despite being installed, obviously.

###### Workaround

Install Amaze (or presumably another file manager) and open it from there. This time, AnkiDroid is in the list.

###### Details

Reproduced two times with different shared decks.

The browser which gets opened to select and download the shared deck is Firefox 51.1.0 from F-Droid.
Android 6.0.1 cyanogenmod
AnkiDroid 2.8.2beta4

**Comment by timrae** [comment]
Can you use intent intercept app to see the details of the intent they're
firing off?

**Comment by nicolas-raoul** [comment]
Strangely,
https://play.google.com/store/apps/details?id=uk.co.ashtonbrsc.android.intentintercept
does not intercept the event when I press "OPEN" in Firefox.
But it intercepted correctly in another test.
Maybe this "Open with" widget is actually part of the Firefox app?

**Comment by mikehardy** [comment]
We are doing everything we can in the manifest to register our accpetance, I don't think this is in our control?
