### ISSUE TITLE
Display latex code as fallback if image not exists

### ISSUE THREAD

**Issue by dreamflasher** [ankidroid/Anki-Android#4597]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open a card that has not been rendered with anki desktop before

###### Expected Result
Show latex formula as plaintext code

###### Actual Result
Broken image, no text

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by Arthur-Milchior** [comment]
This idea seems great. I had the same problem and don't know why I never thought about this simple fix. Here is it https://github.com/ankidroid/Anki-Android/pull/6247
