### ISSUE TITLE
Interacting with apps opened "within" AnkiDroid disables Android's back button

### ISSUE THREAD

**Issue by rathsky** [ankidroid/Anki-Android#4600]
Noticed with the Wiktionary app, probably also affects others. Steps:

1. Open the Wiktionary app from "within" AnkiDroid – that is, click on a Wiktionary HTML link on a card, which should start the app in overlaid mode (so that its content is shown in the open app list as AnkiDroid's entry).
2. Click on any link within the open Wiktionary app.

This completely disables the back button (the left triangle in the bottom navigation bar), effectively locking you into the overlaid Wiktionary app. The only way to get back to AnkiDroid is to close its entry in the open app list and restart it.

Dunno ofc if this is an AnkiDroid or Android issue. Anyway, I'm using latest nightly of Lineage OS 14.1.

**Comment by timrae** [comment]
Can you attach a sample deck file? You can share a link to Google drive or
if you change the extension from apkg to zip you can upload here directly.

**Comment by rathsky** [comment]
You can try with [this one](https://ankiweb.net/shared/info/1332710792). Click on the Hebrew on the back cards, Wiktionary needs to be installed ofc.

Btw, I know this is off-topic, but why is even <br> stripped from {{Type::}} on the back cards? I like to use newlines to better organize information, but all ways to express them are just removed without replacement by Anki and Ankidroid.

**Comment by timrae** [comment]
>  Click on the Hebrew on the back cards, Wiktionary needs to be installed ofc.

In the case of this deck, the links are simply to `http://en.wiktionary.com`. When the app is not installed, the links are opened by the default browser. After installing the app you then get the choice of opening in browser or app.

For me (on Nexus 5x, Android 7.1.1), in both cases (browser/app), pressing the back button after opening the link takes me back to the AnkiDroid app and I can keep using it as normal. So I expect there is some problem with your device.

What device do you have? Does it work as expected with the browser?

**Comment by rathsky** [comment]
Actually the links aren't simply to http://en.wiktionary.com but to its search page with the query being the Hebrew term (linking to the pages directly won't work – the diacritics and inflections will have it fail – and if there's single search result, it automatically relinks). Weird.

The issue with the back button arises if you have clicked on yet another link in the Wiktionary app. Eg, a related word/entry if one is suggested. If you stay on the page as opened (which I think you did) there's no problem yet.

Anyway, it happens with my two devices, a Nexus 7 and Moto G.

**Comment by rathsky** [comment]
Well possible. TBH, I uninstalled the Wiktionary app soon since it  was abandoned for ages already (now it's entirely removed from the Play Store) and did nothing but open a webview. That made these  interactions open in Chrome directly, which has always worked properly.

Guess I'll close this issue.
