### ISSUE TITLE
Option to invert images in night mode

### ISSUE THREAD

**Issue by antigonos44** [ankidroid/Anki-Android#4602]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

Option to invert the colour of images in cards when in night mode

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#invert-color-of-images-in-night-mode

**Comment by scuen** [comment]
Is there any way to invert colors in Night Mode in Android 4.1.2?
