### ISSUE TITLE
Junk in cards 

### ISSUE THREAD

**Issue by polyglot0027** [ankidroid/Anki-Android#4604]
Hi, guys! First of all thanks a lot for such a marvelous app! About my problem, in a word I can't figure out what's actually wrong but it seems like there is a bug in database. I've attached a couple of files. So when I add a new card, for example I type a word 'Pizza' in the first line and when I open up that card I see in the same line 'Pizza шлю'. This junk 'шлю' also appeared in many cards that have been in database for long time and I changed nothing in the ones, but now they all have the same stuff. How do you think what the cause may be in this case? I've tried to look up the data from db2 but some files are encrypted. Anyway thanks in advance! My phone is Meizu MX4 PRO, FLYME 6.0.2.0 OS, Android version 5.1.1 

![s70312-143146](https://cloud.githubusercontent.com/assets/18975138/23831445/4741adf2-0732-11e7-963c-ed8ef38e1da3.jpg)
![s70312-143202](https://cloud.githubusercontent.com/assets/18975138/23831447/4f64606a-0732-11e7-918e-cc2dbf396168.jpg)
![s70312-142808](https://cloud.githubusercontent.com/assets/18975138/23831449/58156646-0732-11e7-8c30-a832401c01de.jpg)

**Comment by timrae** [comment]
You'll need to edit the card template and remove the extra text from there.

**Comment by polyglot0027** [comment]
Oh gosh "facepalm", sorry for my question. Thanks for help!
