### ISSUE TITLE
Size limit for a String exceeded

### ISSUE THREAD

**Issue by aPaci95** [ankidroid/Anki-Android#4605]
Ankidroid says that I exceeded the size limit for a String in the database, and doesn't let me use it. I read about this error in FAQ, but I can't understand how to fix this problem. Can anybody help me?

**Comment by timrae** [comment]
Are you using Anki desktop?

**Comment by aPaci95** [comment]
Yes, but on anki desktop it works fine

**Comment by timrae** [comment]
As written in the FAQ, Android has a smaller limit than PC. You'll need to
do "manage note types" on desktop and delete some of the note types which
you're not using.

**Comment by aPaci95** [comment]
I already done this and the only note types left are basic and cloze deletion... I also uninstalled some plugins, but I still can't use anki on android. I have a collection of 28'000 cards, but I read online that someone have 100k-200k cards and they works fine, so I think this isn't the problem. Do you have any advice?

**Comment by timrae** [comment]
> I already done this and the only note types left are basic and cloze deletion

After deleting the note types, you need to sync from AnkiDesktop.
After syncing from Anki Desktop you need to do "full sync from server" in AnkiDroid.

> I also uninstalled some plugins
> I read online that someone have 100k-200k cards and they works fine

Anki Desktop plugins and the number of cards in your collection are not related to this issue in any way.

**Comment by aPaci95** [comment]
I already done this and it still doesn't work..

**Comment by timrae** [comment]
Can you post a video or screenshots of each step you took? The most likely possibility is that you made a mistake somewhere.

**Comment by timrae** [comment]
Also, how many decks do you have? Do any of them have a very long deck description? I think you can see / edit the deck description in deck options on Anki Desktop.

**Comment by hssm** [comment]
With the inclusion of the `sqlite-android` library, the string limit issue is no longer valid. Most likely, a different error is occurring but is being captured by the exception handler for that issue. I.e., the error message is wrong and misleading us.

Post a copy of your `collection.anki2` file here so I can take a look at it.

**Comment by timrae** [comment]
> With the inclusion of the sqlite-android library, the string limit issue is no longer valid.

Oh, have you been able to confirm this? IIRC before you were saying it "might" be fixed? Do you know what the new size limit is? 2GB? I forgot that we were just [swallowing](https://github.com/ankidroid/Anki-Android/blob/develop/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L124) the `IllegalStateException` to test for this issue.

**Comment by timrae** [comment]
The [stackoverflow thread](http://stackoverflow.com/questions/21432556/android-java-lang-illegalstateexception-couldnt-read-row-0-col-0-from-cursorw) that I originally found when researching this issue blamed it on the cursor window size, but [skimming the source code](https://github.com/android/platform_frameworks_base/blob/nougat-release/core/java/android/database/CursorWindow.java#L104) it would seem we'd get a `CursorWindowAllocationException` rather than an `IllegalStateException` in this case.

However if the above were to somehow be the culprit, we might get the same error [even with the new library](https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/java/io/requery/android/database/CursorWindow.java#L84)  due to their Android API wrapper.

**Comment by hssm** [comment]
I remember testing it on an apkg file that failed to import because of this issue (where the check is bypassed). It was working with the new library. I don't seem to have that file anymore though.

**Comment by timrae** [comment]
I emailed you the original apkg from #4031. For me it won't import, saying invalid apkg... I don't have time to check it right now though.

**Comment by hssm** [comment]
Welp, looks like I'm completely wrong about this. Not sure how I had myself convinced it was fixed. Sorry for wasting your time.

**Comment by timrae** [comment]
Was it the same problem preventing from opening it though...?

**Comment by hssm** [comment]
Yes, since we need to open it to import it, it's exactly the same. It's just that the check is done in DeckPicker while the importer doesn't go through that route.

**Comment by timrae** [comment]
I see, well good to know at least...
Do you think it's worth us using a custom jar with larger cursor size?

**Comment by hssm** [comment]
Possibly. I will check first with the library author about increasing the value or having it configurable.

**Comment by aPaci95** [comment]
@timrae I have a lot of decks (I use sub-deck organization), but I don't use deck descriptions at all. I'm going to take some screen of each step, but this afternoon I have to take a plane and I won't be able to answer here for at least 4 days 

@hssm  https://mega.nz/#!n4VigKhL!a0vFZcJB4frhpOIkQD_5x2OFDdQTjQfv5xp2eEgJWcc this is my collection.anki2

**Comment by aPaci95** [comment]
<img width="1080" alt="2" src="https://cloud.githubusercontent.com/assets/25055620/23897585/04eb5c82-08ae-11e7-8222-cc3cffe74105.png">
<img width="1080" alt="3" src="https://cloud.githubusercontent.com/assets/25055620/23897587/08116cd0-08ae-11e7-8a85-59c59e5385e5.png">
![screenshot_2017-03-14-12-00-42](https://cloud.githubusercontent.com/assets/25055620/23897602/141f7d28-08ae-11e7-95b2-c5076d3df779.png)
![screenshot_2017-03-14-12-00-47](https://cloud.githubusercontent.com/assets/25055620/23897611/1a5b5d38-08ae-11e7-9c67-5ccdf7d96750.png)
![screenshot_2017-03-14-12-00-52](https://cloud.githubusercontent.com/assets/25055620/23897617/1e24aabe-08ae-11e7-8788-d75c5fc1b0e0.png)
![screenshot_2017-03-14-12-00-56](https://cloud.githubusercontent.com/assets/25055620/23897622/21205f92-08ae-11e7-9021-9352ed82d615.png)
![screenshot_2017-03-14-12-01-11](https://cloud.githubusercontent.com/assets/25055620/23897625/234bd990-08ae-11e7-9c11-5c5d341a8009.png)
![screenshot_2017-03-14-12-01-16](https://cloud.githubusercontent.com/assets/25055620/23897629/266bbe24-08ae-11e7-8ceb-8bcccd8fb8b2.png)

**Comment by aPaci95** [comment]
Any advice?

**Comment by timrae** [comment]
It looks like the collection on ankiweb might be corrupt somehow irrespective of the string oversize issue. In the Anki desktop manual there's a procedure written for dealing with corrupt collections... Can you try it?

**Comment by timrae** [comment]
If that doesn't work one of us will have to see if we can reproduce the issue
