### ISSUE TITLE
Audio not played automatically when preceded by another, missing audio file

### ISSUE THREAD

**Issue by richardKafati** [ankidroid/Anki-Android#4609]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
[sound:silence.mp3]
{{Audio}}

from deck: https://ankiweb.net/shared/info/867291675

###### Expected Result
{{Audio}} to play automatically

###### Actual Result
{{Audio}} does not automatically play when audio file precedes it but does when audio file is removed.

Please resolve.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

Does the silence.mp3 file exist in the collection.media folder on your phone (you might need an underscore prefix, see https://apps.ankiweb.net/docs/manual.html#media-&-latex-references)? Does it work on Anki Desktop?

Also, please don't open multiple threads for the same issue.

**Comment by richardKafati** [comment]
It appears to be working on desktop but I do not see the file in collection.media or anywhere on desktop or mobile.

**Comment by richardKafati** [comment]
@eginhard

**Comment by eginhard** [comment]
It seems like the silence.mp3 file isn't included with that deck. You could make the author aware of it. If you remove silence.mp3 or replace it with an existing audio file it will work fine.

**Comment by eginhard** [comment]
Reopening because the underlying issue remains. Anki Desktop plays audio following a missing file correctly.

**Comment by pavreh** [comment]
I cannot reproduce in AnkiDroid 2.16.1. An error message "Failed to load 'silence.mp3'" appears but the second audio file plays automatically. Tested with old and new backend. It seems the issue can be closed.

**Comment by dae** [comment]
Thanks @pavreh.
