### ISSUE TITLE
Dear all,   I have tried logging into ANKI, but whenever I try, the message ‘A network error has occurred’.    I cannot log in. and transfer my ANKI deck from my computer to my smartphone.   I am based in China, I have tried using VPN, a gmail account.  I have also tried a Chinese ‘163’ email account and still cannot log on.   Does anyone have any advice?   Please help me!

### ISSUE THREAD

**Issue by Andrewkp1** [ankidroid/Anki-Android#4616]
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by Andrewkp1** [comment]
Dear all,
 
I have tried logging into ANKI, but whenever I try, the message ‘A network error has occurred’. 
 
I cannot log in. and transfer my ANKI deck from my computer to my smartphone.
 
I am based in China, I have tried using VPN, a gmail account.  I have also tried a Chinese ‘163’ email account and still cannot log on.
 
Does anyone have any advice?
 
Please help me!

**Comment by eginhard** [comment]
See the reply to your previous email: https://groups.google.com/forum/?utm_source=digest&utm_medium=email#!topic/anki-android/-ujCTWzgE00
