### ISSUE TITLE
Store TTS language by note type instead of deck

### ISSUE THREAD

**Issue by rlpowell** [ankidroid/Anki-Android#4618]
###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Have a note with two cards: one that is language X -> language Y and the other than is Y -> X
2. Have a note with 4 cards, in this order: X -> Y form 1, X -> Y form 2, Y 1 -> X, Y 2 -> X
3. Turn on TTS auto-reading, set languages for all cards.  Run through them again.

###### Expected Result

The correct TTS languages are spoken.

###### Actual Result

Cards of the second type, for both notes, will always be wrong for one note or the other.

As far as I can tell, languages are stored as "card 1 is language X on the front, language Y on the back; card 2 is language Y on the front, language X on the back", and so on, as opposed to "card 1 for note type 1 is ...; card 2 for note type 2 is ...".  Since note type 1 has card 2 being Y -> X, and note type 2 has card 2 being X -> Y, one of them will always be wrong.

This is "easily" fixable by making the card types always alternate (unless you have a situation in which one note type is *only* X -> Y1 ; X -> Y2, or something similarly wonky, in which case you're screwed), but since as far as I can tell there's no way to re-order card types in either ankidroid or anki desktop, doing so means re-creating all the cards for at least some note types.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.2

Android Version = 7.1.1

ACRA UUID = aeb64ba1-b45a-4334-a413-d6f69afc76f7

**Comment by rlpowell** [comment]
Note that I do, in fact, have a card type that makes it so that I can't work around this issue.

For adjectives, it's English -> all 4 Spanish forms for card 1, and then the other 4 cards are each form to English, i.e.:

1.  English -> Spanish MS (Masculine Singular), Spanish MP, Spanish FS, Spanish FP
2. Spanish MS -> English
3.  Spanish MP -> English
4. Spanish FS -> English
5.  Spanish FP -> English

Nouns, on the other hard, are:

1.  English -> Spanish
2.  Spanish -> English
3.  What gender is this? [english] -> Spanish answer

There is no way to order these such that every card number has the same language ordering.

**Comment by rlpowell** [comment]
Based on another TTS-related ticket, I've tried SSML; I tried a variety of versions, here's one:

```
&lt;?xml version="1.0"?&gt;
&lt;speak version="1.0"
```

This "works" in the sense that it plays just the words I want it to play, but it plays them in Spanish, so, not so much.  This is with the Google TTS engine.  I could use Ivona, but I use Google TTS for everything else, and for everything else I do not want to use Ivona, and ankidroid doesn't allow selection of TTS engine, so...

**Comment by rlpowell** [comment]
I'll note that the best solution here, as indicated in other issues, is to have an anki-specific tag that wraps the bits that should be TTS-ed, and can optionally indicate language.

**Comment by rlpowell** [comment]
OH OH!  For others with this issue: it *is* possible to re-order the cards!

In the desktop interface, in card management, there's a "More ->" button at the bottom; use Reposition.

**Comment by timrae** [comment]
It shouldn't be too hard for someone to fix, but I don't have time right now

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/MetaDB.java#L201
