### ISSUE TITLE
AnkiDroid API Permission Request Description has some unnecessary words 

### ISSUE THREAD

**Issue by wlky** [ankidroid/Anki-Android#4619]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Request permission for com.ichi2.anki.permission.READ_WRITE_DATABASE

###### Expected Result
Correct request text

###### Actual Result
"Allow AnkiWear to allow the application to ...."
![screenshot_20170416-095833](https://cloud.githubusercontent.com/assets/10642029/25069947/ab034080-228f-11e7-9df7-836d428f3aa8.png)
![screenshot_20170416-100145](https://cloud.githubusercontent.com/assets/10642029/25069948/ab206c78-228f-11e7-92d2-05602f15b26b.png)

I have tested it on an Android M and N devices in German and English with the same result.

**Comment by timrae** [comment]
I wonder if the format of that message changes on different Android versions?

**Comment by wlky** [comment]
So far the same message has appeared on all devices I have tested:
Aquaris X5 Plus - Android 7.1.1
Nexus 5x - Android 7.1.2
Find 7 - Android 6.0.1
Acer Iconia Tab- Android 6.0

Permission requests have only been available since Android 6, so I haven't tested anything below.
@timrae do you know of a specific Android version / device where the current description is displayed correctly?

**Comment by timrae** [comment]
Thanks for the extra information :-)
Would you be able to submit a PR? I'm super busy with a work deadline right
now.

**Comment by wlky** [comment]
@timrae not exactly sure how translations are handled in ankidroid.
I could create a pull request for german and english string values

**Comment by timrae** [comment]
Just English is enough for the pull request; translations are done on our
crowdin page and pulled into the project on a periodic basis.

**Comment by wlky** [comment]
@timrae I created the pull request as requested #4621
