### ISSUE TITLE
Webview update leads to scrolling issues

### ISSUE THREAD

**Issue by bgx90** [ankidroid/Anki-Android#4624]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

AnkiDroid has suddenly stopped automatically scrolling to place the dividing line on the back of a card at the top of the card display area after the SHOW ANSWER button is tapped when the back of the card is too long for the display area.  The previous behavior when viewing the same deck in landscape mode was to automatically scroll so that the dividing line was placed at the top of the card display area after tapping SHOW ANSWER.  The last time AnkiDroid was updated was 7 weeks ago.  No changes have been made to the deck or its card templates, and no changes have been made to AnkiDroid's settings.  It seems that AnkiDroid is suddenly ignoring the `<hr id=answer>` element in the card template.  The automatic scrolling was working yesterday, but today the automatic scrolling is not happening.  Forcibly stopping and restarting the application had no effect on the problem.  Powering the phone off and restarting it also had no effect.

###### Reproduction Steps

1. Start AnkiDroid
2. Open a deck
3. Turn phone to switch to landscape
4. Tap SHOW ANSWER button

###### Expected Result
The back of the card is displayed and AnkiDroid automatically scrolls so that the dividing line on the back of the card (`<hr id=answer>`) is positioned at the top of the card display area.

###### Actual Result
The back of the card is displayed, but there is no automatic scrolling to place the dividing line at the top of the card display area.

###### Debug info
AnkiDroid Version = 2.8.2

Android Version = 6.0.1

ACRA UUID = c95662f8-2084-444a-91b0-454e5dbe2cc9

**Comment by glo-fi** [comment]
I'm also having this issue. Makes using certain decks very awkward.

AnkiDroid Version = 2.8.2

Android Version = 6.0.1

ACRA UUID = bc05d872-afd1-4055-b505-83cbf0d04122

**Comment by mcallisterjp** [comment]
I have this too, a regression from yesterday. It's not just landscape mode for me, and the client also doesn't scroll up to the top of the next card after you select Again/Hard/OK/Easy.

AnkiDroid Version = 2.8.2

Android Version = 5.1.1

ACRA UUID = 18867845-9310-4edd-a30c-20f23fab58c8

**Comment by timrae** [comment]
Might be an update in the Google chrome webview to blame? As you mentioned we haven't updated AnkiDroid for a while, and certainly not the code that handles that.

**Comment by docmarionum1** [comment]
Seeing the same issue in portrait mode.

Not sure if the Chrome WebView updates along with the browser, but Chrome updated on my phone 12 hours ago and scrolling was working yesterday.  

AnkiDroid Version = 2.8.2
Android Version = 7.0
ACRA UUID = 22f123e6-1f7a-4e9b-a208-71645f58a0a7

**Comment by timrae** [comment]
> Not sure if the Chrome WebView updates along with the browser, but Chrome updated on my phone 12 hours ago and scrolling was working yesterday.

Yes, on newer versions of Android / Chrome I believe they update together.

I don't really have time to look into this right now, sorry...

@dae @hssm
Any ideas?

**Comment by hssm** [comment]
If you change `<hr id=answer>` to `<hr id="answer">`, does it fix the problem?

**Comment by bgx90** [comment]
Changing `<hr id=answer>` to `<hr id="answer">` does not fix the problem for me.

**Comment by Muhd** [comment]
Also have this issue. Was working yesterday.

Android 6.0.1
Chrome 58.0.3029.83
AnkiDroid 2.8.2

**Comment by JLRishe** [comment]
This issue seems to have appeared for me (in both portrait and landscape mode) around the time I did a system update in the last 24 hours.

Currently:
Android 7.1.2
Chrome 58.0.3029.83
Ankidroid 2.8.2

**Comment by castlereagh** [comment]
Identical story for me. Both portrait and landscape following system update. 

Android 7.1.2
Chrome 58.0.3029.83
Ankidroid 2.8.2

**Comment by timrae** [comment]
Presumably the javascript is the culprit...?

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/assets/scripts/card.js#L91

**Comment by ferrouswheel** [comment]
And me.

AnkiDroid Version = 2.8.2
Android Version = 7.1.2
Chrome 58.0.3029.83

**Comment by castlereagh** [comment]
That JavaScript fix doesn't work for me either unfortunately.

**Comment by timrae** [comment]
What JavaScript fix?

**Comment by timrae** [comment]
I meant that the internal AnkiDroid JavaScript that I linked to is probably not working as intended. Nobody has posted any fix for it yet...

**Comment by castlereagh** [comment]
Apologies. I meant changing <hr id=answer> to <hr id="answer"> didn't help me either.

**Comment by live22morrow** [comment]
A recent update to Android Webview seems to have changed this. Now, the answer side scrolls to wherever the last card was. Eg. if the last card was scrolled down 500px when you hit the good button, when next press answer the back of the next card will also be scrolled down 500px. This is somewhat more convenient, though it still seems to be unintended behavior.

**Comment by bgx90** [comment]
I am also seeing the behavior live22morrow describes.

**Comment by ferrouswheel** [comment]
With Chrome 59.0.3071.125, I seem to have the original behaviour again.

Hurray! Now I can catch up on my backlog of due cards ;-)

**Comment by Sicaduj** [comment]
Reverting to a previous version of Android System WebView (specifically version 57.0.2987.132) fixed this issue for me. You can find the apk on apkmirror or any other reliable/trustworthy website.

**Comment by timrae** [comment]
It seems we're getting conflicting information about this issue. All of the initial bug reports were for Chrome 58, however:

@ferrouswheel mentions the problem is solved with Chrome 59
while @snowtimeglass mentions (in #4663) that the problem persists in Chrome 59

@Sicaduj and @snowtimeglass have both mentioned that the problem is resolved by reverting to Chrome 57.

Is this correct? Can anyone else provide information on whether or not the issue is fixed in Chrome 57 and Chrome 59? I haven't been able to find a matching bug report for this on the Chrome website, so I'm not sure whether it's a bug or feature in the new Chrome.

**Comment by timrae** [comment]
Maybe someone could check on the simulator in Android Studio whether the problem occurs on Chrome 57, 58, and 59. You should be able to install from [here](http://www.apkmirror.com/apk/google-inc/chrome/). Without a way to reproduce the issue, we can't really do anything else to help.

**Comment by ferrouswheel** [comment]
@timrae I'm unsure if things are fixed in Chrome 59.

For the majority of my cards they all autoscroll to where I expect, but I am not easily able to determine if that's just chrome/AnkiDroid somehow remembering the scroll location. However I have thousands of cards, so would Chrome really be somehow remembering my scroll location from thousands of cards since when I started using Ankidroid years ago?

Some don't autoscroll to where I expect, but for me AnkiDroid is usable again, and that could be something to do with the cards themselves.

I may be able to investigate installing Android Studio and android development at the end of August, but I'm very unfamiliar with the Android dev ecosystem so it'll take me a fair bit of effort to set things up.

**Comment by bgx90** [comment]
I have Chrome 59.0.3071.125 installed, and the behavior that I see in AnkiDroid right now is what @live22morrow described on July 5, 2017:

> Now, the answer side scrolls to wherever the last card was. Eg. if the last card was scrolled down 500px when you hit the good button, when next press answer the back of the next card will also be scrolled down 500px. This is somewhat more convenient, though it still seems to be unintended behavior.

When I first reported this bug, no automatic scrolling occurred at all.  Some change in Chrome 59 seems to have resulted in the behavior I currently see in AnkiDroid.

**Comment by timrae** [comment]
Can one of you guys please try to reproduce it with the Android simulator? I tried to reproduce on my device but I couldn't. Once we have a way to reproduce it we can start to work out whether behavior needs to be changed on the AnkiDroid side or Chrome side.

**Comment by snowtimeglass** [comment]
@timrae 
>@Sicaduj and @snowtimeglass have both mentioned that the problem is resolved by reverting to Chrome 57.
>Is this correct? 

It might not be correct, I think.

I mentioned that the auto-scrolling problem got (almost) resolved by 


-   reverting to Android System WebView 57.0.2987.132, as @Sicaduj said.
or
-   just uninstalling (all the updates of) Android System Webview on Google Play.

Chrome on my device hasn't reverted to any previous versions. 
i.e. I am using Chrome 59.0.3071.125, and the problem has already (almost) been resolved.

**Comment by glutanimate** [comment]
I can confirm this issue on Android 6.0 running Android System Webview version 60.0.3112.107. I guess this might be obvious, but I can't help pointing out that downgrading your webview might be a bad idea. Just like with any other web browser, new versions come with important security patches. As long as you're aware of these risks it's fine, of course.

**Comment by magonreal** [comment]
I have the also the same problem here.
Android 7.0
Anki Droid 2.8.2
Chrome 61.0.3163.98

Is there already a way to fix this, without downgrading?

**Comment by timrae** [comment]
Guys please try the latest alpha version and comment here with feedback

**Comment by JLRishe** [comment]
Rats, after reviewing some cards today, it looks like this partially fixes the issue, but not completely. It works until the user manually scrolls the card at all, at which point it seems the card becomes unable to scroll itself and the scroll position is preserved even across cards. Returning to the deck screen and tapping the deck gets it to start working again until the next time the user manually scrolls.

I will keep plugging at this when I have some time.

**Comment by magonreal** [comment]
Yes, using 2.9 alpha 14, the behavior didn't change.

**Comment by timrae** [comment]
Didn't change at all?

**Comment by magonreal** [comment]
Not at all.
When I scroll down on the first answer in my deck, all of the subsequent answers I open up all start at the same scroll position as the previous card. When the answer of the first card is pretty short and I scroll until the end of it, the next card doesn't start at the end but it looks like from the exact same scroll distance as the previous one.

**Comment by JLRishe** [comment]
I've already noted that any manual scrolling on the part of the user causes the scroll position to get "stuck" where they left it.

What _has_ changed (at least for me), and what this issue was originally about, is that if you reveal the answer on a card with a long question, the full answer will scroll into view (or at least the first page of it). As I've said, that too stops working as soon as the user manually scrolls. Can anyone test to see if at least that much is working?

**Comment by magonreal** [comment]
I can try tonight. I don't have any cards with long questions in my decks now.

What I wanted to add was, that when you zoom in into any card and go to the next or to the previous, the zooming also stays the same.

**Comment by JLRishe** [comment]
Yeah, I noticed that too. In some ways that could be seen as desirable, but I guess having the zoom revert after each transition would be the right way to go.

**Comment by magonreal** [comment]
I can confirm that, when the answer on a card with a long question is revealed, the top of the screen on the answer side aligns with " <hr id=answer> ". The automatic scrolling works as intended but only when no scrolling happened on the question side. When I scroll down on the long answer the scrolling gets stuck at that point.

**Comment by LeopoldKellers** [comment]
After updating my phone from CyanogenMod 12.1 (Android 5) to LineageOS 14.1 (Android 7) I do now also experience the "pleasure" of the very behavior, which @magonreal describes.

What I'd like to contribute to the discussion is, that calling the functions exposed by the WebView, which allow for programmatically scrolling the card as I did in [a recent pr](https://github.com/ankidroid/Anki-Android/pull/4728), results in the exact same behaviour as just dragging the finger on the screen to scroll the card.

Hence the naive idea (which immediately came to my mind), of catching the touch events and processing them manually (e.g. in AbstractFlashCardViewer) to control the card's scrolling behavior does not seem to pose a viable workaround for the issue.

**Comment by timrae** [comment]
So can I revert #4728 for now, or has there been an improvement in the behavior?

**Comment by JLRishe** [comment]
edd43f6 successfully fixed the problem that this issue was originally about and @magonreal has confirmed this. The problem that @magonreal is describing is a separate, similar glitch that began occurring about 5 months ago (as evidenced by @live22morrow's comment).

**Comment by owczyped** [comment]
Not sure, but maybe it's related. Besides not working scrolling, my custom javascript on cards also stopped working some time ago. Uninstalling updates from Android System WebView fixes both scrolling and my js, but as somebody pointed out, that's not the best fix.

**Comment by snowtimeglass** [comment]
Fortunately, the problem seems to disappear completely on my device with the latest version of Android System Webview. The automatic scrolling always works properly. 

Android 5.0
AnkiDroid 2.9alpha18
Chrome 64.0.3282.137
Android System WebView 64.0.3282.137


@glutanimate 
Sorry for not getting back sooner but thank you for pointing out security risks. I didn't and don't know much about them, so the advice is helpful for me.

**Comment by timrae** [comment]
@snowtimeglass

Would you be able to confirmed that the issue is also fixed with 2.8.3? If that's the case we could revert #4734

**Comment by timrae** [comment]
Also can others please confirm that using the latest webview fixes there issues?

**Comment by magonreal** [comment]
Yes. It is working perfectly for me too now.

**Comment by snowtimeglass** [comment]
@timrae
Sorry, I read your question just now.

Yes, I've confirmed that the issue has fixed with 2.8.3, too.


2018年4月19日(木) 10:04 Tim Rae <notifications@github.com>:

**Comment by JLRishe** [comment]
@timrae I have noticed this issue happening again since yesterday. I'm suspecting another Chrome update broke the scrolling again (my phone's Chrome was updated a week ago). Is anyone else seeing this? @bgx90  @snowtimeglass

**Comment by mikehardy** [comment]
@JLRishe can you post your exact version information, this will likely need some sort of bisect on version number combinations to find the change and design an appropriate fix that stabilizes this behavior so it's not so fragile... Thanks!

**Comment by JLRishe** [comment]
@mikehardy This issue seems to have gone away again, though the only change I made was installing an update to the Google search app. Sorry for the false alarm.

**Comment by mikehardy** [comment]
@JLRishe glad to hear it's back to working, but I fear this area of the code - seems so fragile!
