### ISSUE TITLE
Night Mode image inversion for Android 4.1.2

### ISSUE THREAD

**Issue by scuen** [ankidroid/Anki-Android#4625]
Hi everyone,

I have the following question, is it possible to invert the colors of an image (specifically a gif) when Night Mode is activated in an Android 4.1.2? 

I've seen the [Advanced Formatting](https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting) but it clearly states that works for versions 4.4+...is there a workaround for my version?

Thank you all in advance and best regards.

Saul Cuen

**Comment by eginhard** [comment]
The CSS filter that does the inversion is only supported in the Android browser from Android version 4.4 upwards. I don't know if there's a way to do this in Javascript if you really need it? But you'd be on your own there. Closing this because it's outside the scope of AnkiDroid.
