### ISSUE TITLE
Feature Request: Toggle to add gridlines to whiteboard background

### ISSUE THREAD

**Issue by chap126** [ankidroid/Anki-Android#4627]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

Feature request
It would be useful to add a Toggle in whiteboard settings to add gridlines to the whiteboard for practicing kanji and neater handwritten input in general

**Comment by david-allison-1** [comment]
This is in AnkiMobile - let's keep it open a bit longer
