### ISSUE TITLE
synch with AnkiWeb excluding media

### ISSUE THREAD

**Issue by omega3** [ankidroid/Anki-Android#4628]
This was invalid notification so I edited it. But I have one remark:

I see there is an option: "Fetch media on sync" - By default, AnkiDroid will sync sounds and images as well as your cards and review history. If you disable this option, sounds and images will not be synced by AnkiDroid.

I didn't understand what fatch exactly mean. But now I think that you can consider add information to Ankidroid manual that it affect both download and upload. And you can also mention that there is an option for that in Anki desktop
https://anki.tenderapp.com/discussions/ankiweb/2289-synch-with-ankiweb-excluding-media?unresolve=true

This might help other users to better understand manual than I did.

**Comment by timrae** [comment]
Done
