### ISSUE TITLE
Double clicking a deck quickly launches two

### ISSUE THREAD

**Issue by gajewsk2** [ankidroid/Anki-Android#4630]
###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Double click a deck quickly
2. Two activities launch

###### Expected Result
After a deck has been clicked you all deck clicks should be disabled.

###### Actual Result
Two activities can launch causing chaos with reveiws that auto-advance

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by timrae** [comment]
What kind of device do you have? I can't reproduce this

**Comment by gajewsk2** [comment]
Galaxy note 4, marshmallow

**Comment by gajewsk2** [comment]
Happens on galaxy s4 as well

**Comment by timrae** [comment]
Do you have any non-Samsung devices to try on?

**Comment by gajewsk2** [comment]
Sorry, i do not. I'm having trouble reproducing it atm. Though i've seen it plenty of times over the last year which spurred me when i saw it recently  to make this issue.
