### ISSUE TITLE
Crash when changing card layout

### ISSUE THREAD

**Issue by dejj** [ankidroid/Anki-Android#4633]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Create card with "Basic" layout & save
2. Reopen card for editing
3. Change layout to "Custom" & commit

###### Expected Result

Anki should not crash

###### Actual Result

Anki reports an error and prompts with the crash reporting screen. The card layout is changed correctly though and editing can continue afterwards. The behaviour is mostly a nuisance because waiting for Anki to crash and restart takes time.

There has been one instance where the crash created 2 additional lists with word fragments from the updated card, however I cannot remember the steps to reproduce.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.2
Android Version = 5.0.2
ACRA UUID = fe545f23-aa02-4d73-9ad4-df44fbeb0f71

**Comment by dejj** [comment]
Crash also occurs when moving a card to another deck. If the card has multiple views/pages, then each of the pages have to be moved separately, crashing each time.

**Comment by mikehardy** [comment]
I was still able to locate this crash a year later! It crashed because search terms were null and it tried to operate on them. We're null checking that already in current code, this should no longer happen. You crashed 643 times in the same way with this error, that must be a record :-). Hope you're having better luck now
