### ISSUE TITLE
wiki/Database-Structure lists revlog.id as measured in seconds, but it's actually in ms

### ISSUE THREAD

**Issue by david-gpu** [ankidroid/Anki-Android#4634]
The wiki page for [Database-Structure](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure) documents that column 'id' from table 'revlog' is "epoch-seconds timestamp of when you did the review".

Based on my own tinkering and browsing the database with sqlitebrowser it's pretty clear that revlog.id is measured in epoch-milliseconds instead.

**Comment by timrae** [comment]
Thanks, as that's a wiki page please just edit it to correct any errors you find.
