### ISSUE TITLE
Bug Report: Crashing while reviewing cards. Also unable to open 'Advanced' settings. 

### ISSUE THREAD

**Issue by Kelsey1B** [ankidroid/Anki-Android#4635]
Hello,

I am coming across random crash when going through my main deck. Everything seems to be find on both Web and desktop version but not on AnkiDroid. I have a feeling that one or more of my cards maybe causing the problem but I'm unsure which one(s). I am also unable to access the 'Advanced' section in the setting thus crashing and sending an error message. This also means that I unable to obtain debugging report.  I've tryed reinstalling and problem still persistent. 

Specs:
- AnkiDroid - Latest version (as of 26th May '17)
- Android: 7.0
- Device: Asus ZenPad 10 Z300M 
- Model: P00C

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by timrae** [comment]
Please let us know if you can figure out steps to reproduce the problem... Without a reliable test case and/or a stack trace from the crash, there isn't really anything we can do unfortunately.

**Comment by Kelsey1B** [comment]
That was my thought. Just thought someone might of had a similar problem. Thanks for getting back to me anyways!

**Comment by Zekeriyya** [comment]
Aynı sıkıntıyı bende tasamaktayim Şöyle ki 1 yıla yakındır Ankidroid i kullanıyorum lakin son bir hafta icerisinde KARTLARI TEKRAR GOZDEN GEÇİR meyi denemek istediğim esnada hep hata aliyorum daha sonra ise DESTE yi BOS GÖSTERİYOR fakat içinde bir çok kartim var
