### ISSUE TITLE
Feature request: Display on top of lockscreen

### ISSUE THREAD

**Issue by ByteHamster** [ankidroid/Anki-Android#4636]
###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

- [x] I have searched for similar existing issues here and on the user forum

## Scenario

I am often learning cards that require some minutes of thinking. When I am done thinking about a card, the phone is usually already locked because of the screen timeout. Of course this can be avoided by increasing the timeout or using the Anki function to never turn off the screen. I have used this option for some time now but I noticed that keeping the screen on reduces battery life while learning quite a lot. 

## Feature request

It would be great if there was an option to display Anki on top of the lockscreen - so I can turn off the display while thinking on a card and do not need to enter my password again for the next card.

**Comment by eginhard** [comment]
You can set the timeouts for turning off the display and for locking the device after turning off the display separately. See also #3111
