### ISSUE TITLE
updates were ignored because note type has changed 

### ISSUE THREAD

**Issue by mado0705** [ankidroid/Anki-Android#4637]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  X] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Add a card-1 into Deck  "TOEIC word" and Type "TOEIC"
fields for Type "TOEIC"   : "Front" and "Back"
( add a card at PC Version 2.0.44 )

2. Export Deck "TOEIC word" ，and import it into AnkiDroid (Android)

3.  Add card-2 into Deck  "TOEIC word" and Type "TOEIC"
I add new field for Type "TOEIC" because I want to add new information.
than fields for Type "TOEIC"   : "Front" and "Back" and "new information"

4.  revise card-1's mistake

5. Export Deck "TOEIC word" ，and import it into AnkiDroid (Android)
it show following sentence: 
" Updated 0 of 1 existing notes. 
Some updates were ignored because note type has changed 
Cards Imported : 1"

###### Expected Result
in the AnkiDroid (Android)

1. card-1's card type become
Type "TOEIC"   : "Front" and "Back" and "new information"
2. card-1's mistake has been revised

###### Actual Result
in the AnkiDroid (Android)

1. card-1's card type not change
Type "TOEIC"   : "Front" and "Back"

2. card-1's mistake not be revised

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.8.2

Android Version = 5.0

ACRA UUID = 79a34867-6dca-4315-b97f-c7ba3f6e9277

**Comment by mado0705** [comment]
I have 1000 word in the deck.
Then I add new 40 word to the deck ( include card type change which is add new information, like above had said ) and some mistake revision.

Then 40 card is fine.
But mistake revision didn't work.
Those Incorrect card on AnkiDroid (Android) didn't be revised.
It was upset because I already study the deck for a month.
And revise on the AnkiDroid (Android) is not easier than revise on PC.

**Comment by eginhard** [comment]
I'd suggest to ask about this in the Anki Desktop forum to get better help on dealing with this issue: https://anki.tenderapp.com/discussions
It might work if you just make the same changes to the note type in AnkiDroid before syncing.

(AnkiDroid just implements the same synchronization code as Anki Desktop, so you'd see the same behaviour the other way around)

**Comment by mado0705** [comment]
I'm sorry. I can't follow your reason.
Because this issue, on desktop is no problem.
Note type is one type :  Type "TOEIC" : "Front" and "Back" and "new information"

And in the AnkiDroid  it became two type : 
1. Type "TOEIC" : "Front" and "Back" 
2. Type "TOEIC" : "Front" and "Back" and "new information"

I expected result is one type in the AnkiDroid after I import the .apkg file.

But actual result is two type in the AnkiDroid after I import the .apkg file.
And it make my modify mistakes didn't work.


I'm sorry my English is so bad.
Thanks for your kindly help.
I will ask  this in the Anki Desktop too.

**Comment by timrae** [comment]
Please make sure you sync on both Android and PC before comparing the
behavior

**Comment by mado0705** [comment]
I add new card and modify card on PC, But don't study on PC. 
So PC didn't have progression.
I always study on Android.

Now I try to sync on both Android and PC.
I export my Deck from Android and import the Deck  into PC.
It didn't work. 
Just like I export my Deck from PC and import the Deck  into Android.
It shows " updates were ignored because note type has changed ".

I can't sync on both Android and PC.

**Comment by timrae** [comment]
Please use anki web for syncing... Manual export and import isn't designed
for synchronization between devices.

After a change in note type, a full sync is usually required. Anki will
normally notify you of this if you are using web based synchronization, but
it can't do that if you are exporting and importing.

For now you'll need to choose the collection on one of your devices as the
master and then upload it to ankiweb using the sync function.

Please take backups of both sides before attempting this.

**Comment by mado0705** [comment]
OK, now I understand.
I will try it.
Thanks for your help.
