### ISSUE TITLE
[Feature Request] Check Media Details

### ISSUE THREAD

**Issue by ghost** [ankidroid/Anki-Android#4638]
###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Feature Request

Isn't it possible to include the details of the discrepancies of unused cards or files on the Android version the same way it is done on the Windows PC version? It is actually what forces me to use the PC version regularly but I would rather not.

BTW: There are 2 similar Issues (#4412 and #4396) but Closed even not implement yet.

**Comment by aus-wanderer** [comment]
I understand. It's a pity as I have usually only a handful of discrepancies but not that important to do it myself or hire someone.

**Comment by dae** [comment]
Closed by #14171
