### ISSUE TITLE
Copy note: Default to original note type

### ISSUE THREAD

**Issue by aus-wanderer** [ankidroid/Anki-Android#4639]
###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Feature Request

When I use the Copy card function the Type and Deck are NOT (pre)taken/chosen/set from the original card but rather from the last used one which is not really my expectation of a Copy function and therefore resulting in cards misplaced in wrong decks and/or with wrong types occasionally. I would rather have them copied from the original card as well as the tags and everything else so it is ALWAYS red at the beginning and you are forced to change something to dissolve the conflict.

----

_edited by @david-allison-1_

- [x] Rename Copy Card to Copy Note
- [x] Maintain deck from previous note
- [ ] Maintain type from previous note
- [x] Maintain tags from previous note

**Comment by mrbryce** [comment]
do you mean that you expected to get the copy of a note, rather than the copy of a card ?

**Comment by aus-wanderer** [comment]
Hmm. I am actually confused about Cards, Notes and Types. I have a Type for each Deck, which contains only (simple) Cards.

Probably you mean that Type and Deck are not part of a Card so it can not be copied? Then I do not understand, why it is shown with each Card but not taken over with Copy card?

**Comment by eginhard** [comment]
This is a misnomer, the button copies a note and should be named accordingly. And yes, it should default to the original deck and note type.

**Comment by SimonHeimberg** [comment]
Related issues:
* #5553 use term "copy notes" (has pr)
* #5165 also copy tags

Only mentioned here:
* default to the original deck
* default to the original note type

**Comment by david-allison-1** [comment]
`Note Type` still needs to be persisted. Have completed the rest
