### ISSUE TITLE
Problem with using Ankidroid in conjunction with Talkback

### ISSUE THREAD

**Issue by laosamayor2010** [ankidroid/Anki-Android#4640]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Turn On Talkback
2. Open a deck and start studing card.
3. 

###### Expected Result
Read only the question and the answer without add the prhase "Ankidroid Flascard"

###### Actual Result
When the anverse of a card is displayed, Ankidroid says the question, and then adds the phrase "Ankidroid Flashcard".		
Likewise, when the reverse is displayed, Ankidroid says the answer, and then adds the phrase "Ankidroid Flashcard".
It is not necessary that after every question and answer remind us that an ankidroid card appeared.		
This sentence has no practical use. All it does is create a lot of background noise, that does not allow studying.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
Android 4.4.2 Samsung Galaxy 4 Mini, Ankidroid V 2.8.1 Spanish
ACRA UID: d6ece592-2ae7-4a69-aa04-b19079259450
Link to video that show the problem.
https://youtu.be/pxe3Ddr0q4Y

**Comment by timrae** [comment]
I've never used talkback before, but have you tried using the text to speech feature instead?

**Comment by eginhard** [comment]
TTS is enabled in the video - Talkbalk will not in fact read the actual card content. 

I'm trying to look into where exactly that string is coming from, but I get a different behaviour: On entering a deck from the main screen, Talkback reads "AnkiDroid". TTS reads the front (except for the first card where Talkback reads "AnkiDroid"). On revealing the back, Talkback reads "splitter", but TTS does not read the back (it does with Talkback disabled).

Android 6.0.1, Oneplus One, AnkiDroid 2.8alpha6 in English

**Comment by eginhard** [comment]
I've submitted a fix for this and another related issue, which will be
available soon in the next alpha version and a bit later​ in the public
release.

Thanks a lot for reporting this and including the video. If you have any
other suggestions about improving TalkBack support in AnkiDroid, please let
us know! I'm happy to test and improve things, but I don't use it myself
and as in this case there are some differences between Android versions, so
I mainly need to rely on feedback from others.
