### ISSUE TITLE
Feature request: share android screenshot to ankidroid and get a new card

### ISSUE THREAD

**Issue by mrbryce** [ankidroid/Anki-Android#4641]
###### production Steps

1.  take a screenshot on the device
2.  share to ankidroid

###### Expected Result

ankidroid opens up the "add a card" interface with the image loaded on front card

**Comment by mikehardy** [comment]
This is related to #5023 - as we move to the new clipboard API we should accept images - I'm surprised how many dupes we have of this in the system and how popular it is, actually. I'll make a note of that on #5023
