### ISSUE TITLE
suggestion interface

### ISSUE THREAD

**Issue by andisheh01** [ankidroid/Anki-Android#4642]
hi
i have a suggestion about the interface of the new version of ankidroid
in old versions before version 2.5 for example version 2.4.4 after clicking on a deck and before starting the study of a deck an interface appeared which tells us about the total number of flash cards in  the deck and also the total new cards(remaiminig new flash cards) . it was very informative
can you put this interface in the new versions

thanks

**Comment by timrae** [comment]
You can see this by pressing the numbers on the right of the deck title in the main deck list
