### ISSUE TITLE
Audio cuts off in Japanese deck

### ISSUE THREAD

**Issue by malshiyyy** [ankidroid/Anki-Android#4643]
###### Actual Result
If the audio is longer than 1 second, it gets cut off in a Japanese deck I use. It doesn't happen in other decks. I've reinstalled the app, and imported the deck again, but it didn't help.
The issue doesn't appear on my laptop, so the problem is not the deck itself.

The closest issue I've found here is this one:
https://github.com/ankidroid/Anki-Android/issues/4541

But it doesn't have an actual answer/help. 
Please help me to continue study Japanese...

###### Debug info
AnkiDroid Version = 2.8.2

Android Version = 6.0.1

ACRA UUID = baa0bcff-0592-4341-8bbc-e30a000e82b0

**Comment by timrae** [comment]
What do you mean when you say it gets cut off? Can you post a video?

**Comment by malshiyyy** [comment]
[WhatsApp Video 2017-06-18 at 19.39.25.zip](https://github.com/ankidroid/Anki-Android/files/1085537/WhatsApp.Video.2017-06-18.at.19.39.25.zip)

I attached a zip file with a video.
What I mean is that the audio doesn't play til the end.
In the video I attached, as an example, it doesn't play the last 2 syllables; instead of saying "shiteimasu" it gets cut off and says "shiteim".
Hope it explains it...

**Comment by timrae** [comment]
Are you able to play that file in its entirety via the file manager?

**Comment by malshiyyy** [comment]
Yes, I have no problem with that.

**Comment by timrae** [comment]
Do you have any other Android devices where you can try to reproduce the
problem in AnkiDroid? If not you can post an apkg file for the deck here
including media and I'll try to check on my device.

**Comment by malshiyyy** [comment]
I tried it on other android device, but it worked just fine there.
I attached the deck package file, hope it includes the media as well (not sure about it).


[Japanese_Core_2000_Step_01_Listening_Sentence_Vocab__Images.zip](https://github.com/ankidroid/Anki-Android/files/1092472/Japanese_Core_2000_Step_01_Listening_Sentence_Vocab__Images.zip)

**Comment by timrae** [comment]
Sounds like it might be a problem with the web view on your device... have
you updated it to the latest version?

**Comment by malshiyyy** [comment]
I have version 2.8.2
I don't know what a web view is :/

**Comment by JohnMurray** [comment]
I know this is an older issue, but I'd like to mention that this is also happening for a Japanese deck I downloaded in the Mac app. When I replay the sound-clip, it plays just fine. Only when I first show the answer is the sound trimmed. I am running version `2.0.48`

**Comment by poyeya** [comment]
Same problem herencia on 2.8.3 Android  7.1 webview updated

**Comment by timor** [comment]
I can confirm the same behavior.

Android 6.0.1
AnkiDroid 2.8.4

Tried with stock Web View version and current Web View version, makes no difference.

However, I noticed that when playing the files with VLC they work, while playing them with some other music player they also get cut off.  Maybe there is a problem with the mp3 files themselves.

**Comment by mikehardy** [comment]
I'm going to close this in preference to #4457
