### ISSUE TITLE
ankidroid size limit exceeded error..!

### ISSUE THREAD

**Issue by MastanYuvi** [ankidroid/Anki-Android#4645]
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

Hello Ankidroid Developers
                             I have been facing an error regarding anki-droid size limit exceeded and it shows pop-up to delete unused note types. this makes me to delete my entire deck collection i have around 30 decks and 30 note types and after deleting my collection is empty and this makes me to re-import all the 30 decks again I think it's time waste, is there any alternative way to restore my collection with out deleting my decks due to this error. please help me with this issue quick resolving of this issue is appreciatable.
                                                                                   Thanks in Advance...!

**Comment by eginhard** [comment]
You don't need to re-import your collection. To delete unused note types in AnkiDroid, select "Manage note types" from the overflow menu (3 dots in top right) in the deck list. Then long-press on note types that say "0 Notes" and delete those types. Please synchronise your collection before doing that because afterwards you'll be required to overwrite your collection on the AnkiWeb server.

**Comment by MastanYuvi** [comment]
TQ and i want to ask u about why this error persists and BTW my ankidroid
collection has Huge amount of javascript,json and jQuery code inside my
notetypes code section and i use jquery CDN too to make my code work  will
this also result in persistance of size limit error pls help me with this
issue and if possible provide me your contact support mobile number so that
i can clarify my doubts...! :)

**Comment by eginhard** [comment]
See this link for more info: https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-do-i-get-an-error-message-about-the-size-limit-for-a-string-in-a-database

It's a limitation of Android and how note types are implemented in Anki, there is nothing we can change about it in AnkiDroid. Yes, a lot of formatting in your note types causes this issue, so you should try to reduce both the number of note types and the formatting code.

AnkiDroid is developed by volunteers only, there is no phone support.

**Comment by MastanYuvi** [comment]
Oh got it TQ if I have around 10,000-1,00,000 cards in a single note type will this effect the android size limit and fire size liit error ?

Sent from Mail for Windows 10

**Comment by eginhard** [comment]
The number of cards don't matter for this issue, only the number and content of note types.

**Comment by timrae** [comment]
This issue probably can't be fixed without introducing a  breaking database
change, which would likely disrupt a large number of users. Maybe in
AnkiDroid 3.x, but that could be years away.

**Comment by MastanYuvi** [comment]
Haha LoL ThanQ for Your kind info..! and btw if this issue is resolved then
ankidroid can make a tremendous change in flashcard industry.
