### ISSUE TITLE
SYnc error Your clock's off by ... timezone possibly wrong

### ISSUE THREAD

**Issue by enrico200165** [ankidroid/Anki-Android#4646]
###### Research
*Enter an [ x ] character to confirm the points below:*
[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Synck ankidroid with clock, timezone and DST correctly set (several tests)
2. 
3. 

###### Expected Result
Synchs

###### Actual Result
I get the message
"Sync error Your clock's off by 3598 seconds ... timezone possibly wrong ..."
On PC (windows 10) Anki synch correctly with the same clot and timezone settigs

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.2

Android Version = 6.0

ACRA UUID = 094464f4-0743-429b-847a-b1b291d775fb

**Comment by enrico200165** [comment]
Setting the clock manually one hour back makes synch work.

**Comment by eginhard** [comment]
What timezone are you in?

**Comment by enrico200165** [comment]
Rome, GMT+1, DST

**Comment by enrico200165** [comment]
Just moved from automatic time gotten from network to setting time manually. I saw not option for DST, so set timezone Madrid, (GMT+2, no DST I think as I found no option for it), Ankidroid synchs with this setting (that results in the same time as automatic network time GMT+1 DST)

**Comment by eginhard** [comment]
Your timezone definitions might be out of date, Rome/Madrid would be the same time anyway: https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-do-i-get-an-error-about-the-timezone-when-i-try-to-sync

**Comment by enrico200165** [comment]
ok, must be a timezone configuration problem, probably due to DST given that the same time without DST works.
