### ISSUE TITLE
[Feature Request] transfering individual notes via bluetooth

### ISSUE THREAD

**Issue by mrbryce** [ankidroid/Anki-Android#4649]
###### Research

[x] I am reporting an enhancement request specific to AnkiDroid

[x] I have searched for similar existing issues here and on the user forum

###### Production Steps

1.  while reviewing the card in ankidroid, select "edit note" from the menu
2.  select the new option "share via bluetooth"
3.  the app packages the current note under the current deck name, and submits it to the android bluetooth filesharing process

###### Expected Result

The package can be added to ankidroid as usual, on the receiving device

###### Actual Result

i can get my friend's card easily from his phone, updating my current deck if it bears the same name, creating a new deck if i don't have it.

i dont have to search and select from the browser, i don't have to interrupt his review, i dont have to sort through his collection to get that specific note.

###### Cheers :D

![image](https://user-images.githubusercontent.com/3010322/27012536-a2dd4a2c-4ed1-11e7-9d8c-eac81c570f10.png)

**Comment by timrae** [comment]
This would be *really* complex to implement in a satisfactory way, and you can already achieve almost the same thing by simply exporting the deck as an apkg and sending the apkg by email/bluetooth.
