### ISSUE TITLE
Warn user that cloning a note type will require a full sync

### ISSUE THREAD

**Issue by eginhard** [ankidroid/Anki-Android#4650]
###### Reproduction Steps

1. Manage note type -> Add -> Clone an existing note type
2. Synchronise

###### Expected Result

a) Either the sync proceeds normally or
b) the user is warned before adding the cloned type that a full sync will be required.

###### Actual Result

When synchronising, AnkiDroid notifies that the collection is in an inconsistent state and requires a full sync (just adding a basic note type instead of cloning works fine and doesn't require a full sync).

**Comment by timrae** [comment]
In principle I don't think a full-sync should be necessary... How about in Anki Desktop?

**Comment by mikehardy** [comment]
@eginhard - I've appreciated your return and help bug-busting in the other note editing issue, do you have the requested feedback on this one?

**Comment by eginhard** [comment]
I just checked: In Anki Desktop I can clone a note type without requiring a full sync and in AnkiDroid the behavior is still as described above.

**Comment by mikehardy** [comment]
Thank you! I think I've confirmed or closed all the stale waiting for feedback issues now, with just a couple that are actually still fresh and waiting. 

For this particular issue I'll have to dig into it later but it lives on

**Comment by david-allison-1** [comment]
Related: #6422

**Comment by sudomain** [comment]
I don't know when it changed, but cloning an existing note type no longer requires a full sync. I think that means that item 'a' of this issue's expected result is fulfilled.
