### ISSUE TITLE
Balance optimal card spacing with target % retention by a certain date.

### ISSUE THREAD

**Issue by anrew123** [ankidroid/Anki-Android#4652]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

###### Suggestion
I understand this is complex but it could be done and it would be VERY useful.

Under a "Study targets dashboard" you could create the following study target.

Name "Organic Chemistry Exam"  Target Date "1/1/18"  Days left "x"  Current predicted % "34%"

"I want to have [70%] of my cards to be "mature" by [1/1/18] when my exam is.  I can devote a maximum of [1.5 hours] per day to revise.  My study material consists of [399] [pages] (/modules/chapters).  To date I have created cards for [4] pages."  "The decks that this applies to is [Organic Chemistry] and all sub-decks"

The data contained within this paragraph would let Anki predict how many cards will be created by the end of the study material ((Number of cards to date/4)*399).
Using the built in probabilistic prediction algorithm and the % target requirements you could back fit the latest date by which all the study material needs to be converted into cards and so the minimum amount of study material that needs to be converted into cards per day.
By using the amount of revision time available per day, user data to date and the prediction algorithm it would allow Anki to limit the number of cards that could be studied per day (for optimal recall you cannot have spikes that would require hours worth of study that is not available, this happens alot to me at the moment).  This would mean the cards available to be learned would need to be staggered.  You could also warn if 1.5 hours is not sufficient and recommend a new value.

This would be useful and make Anki less demoralising and optimised (avoid sub-optimal card spikes  where the time simply isn't available to optimally learn the cards).

**Comment by timrae** [comment]
Unless this feature were to make its way into the main Anki desktop application, it's pretty unlikely that we would accept it into our codebase, so you'd need to start by suggesting it on [their forum](https://anki.tenderapp.com/). I'd suggest that you start by simply making an add-on for Anki Desktop, as I'm having trouble imagining Damien accepting it into the main app.
