### ISSUE TITLE
Chrome Webstore - Download behaving suspiciously

### ISSUE THREAD

**Issue by lingua0815** [ankidroid/Anki-Android#4654]
The Chrome Web app suddenly stopped working on my Chromebook about a week ago. In an attempt to fix it, I uninstalled the app and tried to reinstall it from the Chrome webstore. 

The info page on the Chrome Webstore states that the file size is 3.58MB, and I remember that previous installations were rather small. Now, however, the download appears to be over 100MB. 
As this seems weird behaviour, I cancelled the download at that point because I don't want to accidentally install something that may harm my machine. (My Chromebook does not support android apps, which is why the Chrome app was so useful for me).

Please check that the webstore package is working correctly and malware free. 

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Go to [https://chrome.google.com/webstore/detail/ankidroid-flashcards/ckmbkodkbmkmdjdimeiddeljndcneifo?utm_source=chrome-app-launcher](https://chrome.google.com/webstore/detail/ankidroid-flashcards/ckmbkodkbmkmdjdimeiddeljndcneifo?utm_source=chrome-app-launcher)
2. Hit Add to Chrome button
3. Watch the download creep past 100MB

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by timrae** [comment]
@agrueneberg

**Comment by timrae** [comment]
@lingua0815
When I click on that webstore link, it says:

> Additional Information
Version: 2.6.1
Updated: July 18, 2016
Size: 3.58MiB

It's probably worth updating the store to the latest version though anyway... Are you able to install the apk that you can download directly from github?

**Comment by lingua0815** [comment]
Thanks for your prompt response!
Sure, the Chrome webstore says "Size: 3.58MiB" but when I attempt a download, it goes way beyond that: 
![weirdanki](https://user-images.githubusercontent.com/29518417/27260720-42a338a6-542b-11e7-9e3c-479b661fd41b.png)

Just to reiterate, I am talking about the Chrome app, not the Android app, and my Chromebook does not support Android apk files (I have tried!).

**Comment by agrueneberg** [comment]
It's 3.58 MB + 100 MB or more for the Android App Runtime for Chrome (ARC) that needs to be installed in addition.

The app needs to be updated, but with all the uncertainty around the future of the Chrome Web Store (Google stopped updating the apk_to_crx conversion script that we used to customize the package that goes to the Chrome Web Store) and whether or not the Play Store is finally rolling out to more than just a few devices, I kind of lost interest. Once the Play Store roll-out is complete, people should receive updates without any additional work from our side.

**Comment by MathWhiz** [comment]
@agrueneberg Is there a way to install the new version for ourselves while the roll-out is happening?
