### ISSUE TITLE
The AnkiDroid image exceeds the redesigned frame of Twitter's profile icon

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4656]
Twitter has been redesigned. Its profile icons are now round instead of square.

![image](https://user-images.githubusercontent.com/10436072/27432558-ac35fed0-578b-11e7-8029-0eed5a1359d2.png)

It seems appropriate that AnkiDroid's icon be also adjusted to the new design, and be updated.   
![image](https://user-images.githubusercontent.com/10436072/27431106-382e35fc-5786-11e7-9d15-8341b7911db4.png)
Would you like me to do this work?

**Comment by timrae** [comment]
Maybe we can use PR #4659  for this

**Comment by snowtimeglass** [comment]
That looks good :-)

**Comment by nicolas-raoul** [comment]
Uploaded, thanks!
But now it does not look that great in Twitter feeds haha:
![screenshot from 2017-08-04 15-25-25](https://user-images.githubusercontent.com/99590/28956683-39d9431e-7929-11e7-844d-ed2dacdf617a.png)

**Comment by timrae** [comment]
I think that's what it looked like before and it just hadn't updated yet. It looks right when I just searched

**Comment by nicolas-raoul** [comment]
Oh right, it's nice now :-)

**Comment by snowtimeglass** [comment]
Thank you! It's nice!
