### ISSUE TITLE
Ankidroid browser freezes on attempt to display cards in a deck with .mp4 files

### ISSUE THREAD

**Issue by Olivasayana** [ankidroid/Anki-Android#4660]
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
yes
[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
yes
[  ] I have searched for similar existing issues here and on the user forum
yes

###### Reproduction Steps

1. 
2. 
3. 

###### Actual Result
When I browse my deck, which I have remade several times to try to fix this, the little "wait" circle comes on and freezes.  This doesn't happen on Anki on my windows desktop.  When this happens, the cards won't open from the Ankidroid browser for exidint.

I can successfully test myself with the deck and all the mp4 videos display correctly.  It's just the browsing function that doesn't work, and it's only broken on this one deck that has short mp4 videos in it.

I've reinstalled Ankidroid a couple of times, but no success.  

My debug info is attached below.

Thanks!

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.2

Android Version = 4.4.2

ACRA UUID = 9ae01b60-a0f2-40e5-bc2e-a3b2d071ae0c

**Comment by david-allison-1** [comment]
Fixed in #4660
