### ISSUE TITLE
Ankidroid crashes on specific card

### ISSUE THREAD

**Issue by dotancohen** [ankidroid/Anki-Android#4661]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Enter the following as a card:
Front: Print the first and ninth columns from 'ls -l', with a tab between them.
Back: $ ls -l | awk '{print $1, "\t", $9}'

2. Review the card in AnkiDroid 2.8.2 or AnkiDroid 2.9 Alpha 3.

3. Click 'show answer'

###### Expected Result

The answer (back side of the card) and the difficulty buttons should be displayed.

###### Actual Result

AnkiDroid 'closes enexpectedly'.

###### Debug info

AnkiDroid Version = 2.9alpha3
Android Version = 5.0
ACRA UUID = dd43a3ed-7e48-4731-8d3d-c524f51a21af

**Comment by dotancohen** [comment]
It seems when I remove the $9 that the crash no longer occurs. Alas, this is an important part of the text and should remain.

**Comment by chickendude** [comment]
I can't reproduce this with the latest code from the repo. What do your templates/styling look like?
