### ISSUE TITLE
Automatic Night Mode based on sunrise/sundown times

### ISSUE THREAD

**Issue by aphirst** [ankidroid/Anki-Android#4662]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Time passes
2. 
3. 

###### Expected Result

Day mode during day, night mode during night

###### Actual Result

Day/night status only changes as result of manually pressing toggle switch

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by Ivysauro** [comment]
I want this, too~

**Comment by agentydragon** [comment]
I have filed https://github.com/ankidroid/Anki-Android/issues/5685 for following system-level dark mode, which you can set to automatically turn on/off based on time (including sunrise/sundown) in modern Android versions. If we get a patch fixing https://github.com/ankidroid/Anki-Android/issues/5685, it might also enable a way to get this setup.

**Comment by aphirst** [comment]
The functionality remains desirable and unimplemented.

**Comment by mikehardy** [comment]
@aphirst PRs happily accepted

**Comment by adamwolf** [comment]
From my reading, if we hook up night mode to Android's system level
setting, this scheduling comes for free and isn't something we do anything
for.  Is this actually a different issue then?

**Comment by mikehardy** [comment]
A reasonable point #5686 is tracking that
