### ISSUE TITLE
Ability to cancel sync or ask permission on auto-sync

### ISSUE THREAD

**Issue by nbeaver** [ankidroid/Anki-Android#4665]
###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

- [x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Run synchronization.
2. Wait for synchronization to finish.

###### Expected Result

Ability to cancel synchronization.

###### Actual Result

Must wait for synchronization to abort or timeout, which may take a long time. Here's an example:

https://goo.gl/photos/wGg2aB4asaJXHs1J6

The only alternative I know is to close AnkiDroid entirely.

###### Debug info

AnkiDroid Version = 2.8.2

Android Version = 7.1.2

ACRA UUID = 0d583ee2-64d2-4f3c-bd0c-9ac6066ab1a6

**Comment by timrae** [comment]
You can cancel the sync already by pressing the back button, but it only
works in-between sync phases. In your case it seems to be getting stuck
inside the very first system call to open the TCP connection, so there's
not much we can do other than wait for the system call to timeout I'm
afraid. A better solution is for you to figure out what in your network is
causing the TCP connection to timeout; I presume it's a firewall issue of
some kind.

**Comment by mikehardy** [comment]
Some discussion on the mailing list about this again / recently. Hitting back apparently still works. But it still does some sync work and requires some mop-up if the user wanted no sync.

There is some mention that the auto-sync is happening on new app version installs + first new startup and that could be unwanted as someone is switching profiles or similar (after a long review pause, or when testing, or any other reason) so there was a request to have first-new-version/first-install/re-install auto-sync ask for user permission first. That may or may not be sensible or easy but I can see the motivation at minimum.	

References:

> From Z1839
>
> My issue with the alpha is that it seems to be “locked in” to one of my anki web profiles. No matter if I uninstall and delete the ankidroid folder from my directory, as soon as I reinstall it and open it it starts syncing to the same profile automatically.

> From Axel Merboldt
>
> Ah indeed, when pressing the back button Ankidroid asks me if I want to cancel the sync. Good!
> But here the issue was about the first sync after a new installation. In this case Ankidroid just starts syncing without asking beforehand. Even if auto sync is disabled. That is not a good behavior. It also means that Ankidroid will try to sync at *every* app start in case I cancelled the sync last time and still have an empty collection (which is normal for parallel builds). Users might want to change the storage path and other settings first before they want Ankidroid to perform a sync. So it would be good if Ankidroid asks beforehand "do you want to sync now?" after the very first start / when having a empty collection.

From Z1839
> Here’s my experience: the back button does ask to cancel, but there is a delay. That is, it only asks if I want to cancel about 15-20 seconds into syncing. It still works, but it’s kind of tedious because some data will still be synced over, so it adds extra time to the workflow because then you have to delete whatever was downloaded.

**Comment by timrae** [comment]
I guess as a work around we could put a 200ms or so spin loop at the start of the sync waiting for the user to cancel before it enters the networking stuff.

Getting cancel to be more responsive would probably be a lot of work, and might require migrating to a different networking API (we need to this eventually anyway).

Either way, those are both new issues, I think this should stay closed
