### ISSUE TITLE
Synchronization stuck on "Preparing syncing"

### ISSUE THREAD

**Issue by nbeaver** [ankidroid/Anki-Android#4666]
###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

- [x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Press "Sync" button.

###### Expected Result

Successful synchronization.

###### Actual Result

Synchronization gets stuck on "Preparing syncing..." and never completes. After more than two minutes, it fails with this error:

> **Sync error.**
> Connection timed out. Either your internet connection is experiencing problems, or you have a very large file in your media folder.

There are no large files in the media folder (all my cards are text-only), and the internet connection is fine:

- Status: connected
- Signal strength: Excellent
- Link speed: 300 Mbps
- Frequency: 5 GHz
- Security: 802.1x EAP

Full screen recording here:

https://goo.gl/photos/LT1SCKdgPEhsWJWx9

###### Debug info

AnkiDroid Version = 2.8.2

Android Version = 7.1.2

ACRA UUID = 0d583ee2-64d2-4f3c-bd0c-9ac6066ab1a6

**Comment by timrae** [comment]
Have you tried a different connection? For example your 3G

**Comment by nbeaver** [comment]
Yes, 3G works fine. In the other thread you mentioned it might be a firewall problem, which seems reasonable. In the meantime, I am closing this.
