### ISSUE TITLE
Advanced Statistics review count for "All decks" is wrong with subdecks

### ISSUE THREAD

**Issue by ineol** [ankidroid/Anki-Android#4667]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1.  Create deck A and subdecks A::X, A::Y
2.  Do reviews with both
3.  Look at the Review Count for "All decks"

###### Expected Result
It should be reviews(A::X) + reviews(A::Y) = reviews(A)

###### Actual Result
It is reviews(A::X) + reviews(A::Y) + reviews(A) = 2 * (reviews(A::X) + reviews(A::Y))

###### Debug info
AnkiDroid Version = 2.8.2
Android Version = 7.0
ACRA UUID = 3b1df827-2cd8-426d-98df-fe8aa4df5885

**Comment by timrae** [comment]
See also #4702

**Comment by shoshber** [comment]
I can reproduce this only when the advanced statistics feature is on. Propose changing the name of this issue to make it easier to find.

**Comment by rgamici** [comment]
I noticed that the problem is deeper than this and what is reported on #4702.
Even if the limit for new cards is 0, the advanced statistics algorithm is including them as due today.

**Comment by mikehardy** [comment]
Does Anki Desktop have advanced statistics like this? Curious if it is a whole-ecosystem thing, or something special to AnkiDroid

**Comment by rgamici** [comment]
It's something specific from Ankidroid.
If it is present on the desktop version, it depends on a plugin or some not
easily accessible configuration.

**Comment by mikehardy** [comment]
Thanks for confirming that @rgamici - that means this should be easy to fix then as we don't need to fear ecosystem compatibility. Or at least, contained to fix.

If anyone wants to chase through and see how the stats are constructed I believe they are all in here? https://github.com/ankidroid/Anki-Android/tree/master/AnkiDroid/src/main/java/com/ichi2/anki/stats

Specifically I think something around here or the method just below it https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java#L212

And note that you can run queries against your collection pretty easily with some sqlite apps - I personally use sqliteprime which is not on the play store anymore for some reason? https://apkpure.com/sqliteprime-sqlite-database-manager/com.lastempirestudio.sqliteprime but I'm not picky. sqlite is an open source database so lots of apps for it

This appears to be the non-advanced stats query location? https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/stats/AnkiStatsTaskHandler.java#L195 (for comparison)

Someone would need to dig in here to find the problem and propose a query that worked. If they had the math and the SQL correct but did not have the development environment to alter the Java someone (maybe me) might be able to get a PR in shape to fix it. But I'm not motivated to do the math+SQL work ;-)

**Comment by AXiSource** [comment]
This is still a problem.
And not just for "All Decks".
It's a problem for any deck with unseen cards.

- When there are unseen cards the advanced statistics graph doesn't respect "new cards = 0"
- Note that the "Due tomorrow" value is Correct


It would be good to be able to forecast accurately future workload.

Do I have to know java to help solve this ?

Thanks for your work everybody !

![20200506_Ankidroid_issue#4667_deck_settings](https://user-images.githubusercontent.com/32098707/81225980-1eb2a500-8fb8-11ea-8828-e438b2aecf51.jpg)
![20200506_Ankidroid_issue#4667_Advanced_stats_Overview](https://user-images.githubusercontent.com/32098707/81225986-207c6880-8fb8-11ea-9270-64dcba090dfe.jpg)
![20200506_Ankidroid_issue#4667_Advanced_stats_graph](https://user-images.githubusercontent.com/32098707/81225995-22462c00-8fb8-11ea-8ee2-437c26064b72.jpg)

**Comment by david-allison-1** [comment]
Hi @AXiSource,

Just to clarify, I've skimmed this and presume it only applies to advanced statistics.

It's a mix of Java and SQL, Neither are too hard to pick up, the specific code may be a little intimidating due to the length, but it seems fairly well abstracted: https://github.com/ankidroid/Anki-Android/blob/06fba842013a64fd29a64a09ca4127060306d738/AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java.

I'm not familiar with the file, but if you give it some effort and feel you're getting stuck with concepts, or feel you're getting nowhere, feel free to give me a ping and I'll be more than happy to help.

Thank you so much for taking an interest!

David

**Comment by AXiSource** [comment]
At the moment I can't really help because I never read Java before.

newCard has the attribute prob = 1 can this be a possible cause of the problem ?

Thank you too for your time @david-allison-1 

AXiSource

<details>
<summary>CLICK HERE to see snippet</summary>

https://github.com/ankidroid/Anki-Android/blob/06fba842013a64fd29a64a09ca4127060306d738/AnkiDroid/src/main/java/com/ichi2/libanki/hooks/AdvancedStatistics.java#L1625-L1641

**Comment by david-allison-1** [comment]
Thanks @AXiSource,

I'm on it.

**Comment by AXiSource** [comment]
In case somebody is lurking around and wanna help there is a diagram inside the source code : 
<details>
<summary>CLICK HERE to see diagram</summary>
![AdvancedStatistics java](https://user-images.githubusercontent.com/32098707/81312536-be257580-9054-11ea-9b7b-e0806178185f.png)
<\details>
