### ISSUE TITLE
Exclude text for TTS

### ISSUE THREAD

**Issue by vsdmub** [ankidroid/Anki-Android#4672]
###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. I would like that TTS can exclude a text enclosed between [...] I am interested in hearing the pronunciation of some English words but not the explanation notes.
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by eginhard** [comment]
See the proposed solution in #1463
