### ISSUE TITLE
Problem introduced in 2.9alpha4

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#4673]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. I have updated the Anki into 2.9alpha4 yesterday.Now,when I review the image whose width is broader than the screen,I should drag the screen to show it.I have to say this is a degeneration for me.Please fix.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by Juddd** [comment]
@timrae I'm sorry,this problem re-produce in 2.9alpha5

**Comment by timrae** [comment]
Does the problem exist in 2.9alpha3?

**Comment by Juddd** [comment]
It don't happen on 2.9alpha3

**Comment by timrae** [comment]
Thank you for the detailed information about the version where it happened. Thanks to this I could find the bug in 5 minutes. It was introduced here:

e86d66a4efae9301e3d2152ffa57225e0d198e5a
