### ISSUE TITLE
Integer overflow resulting in negative times. 

### ISSUE THREAD

**Issue by yankl** [ankidroid/Anki-Android#4674]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Try to review card with very large due times (seems to be anything longer than 2^31 seconds ≈ 68 years.) 

###### Expected Result

Correct due times appear. (In the attached image you can see that computer version of Anki behaves correctly.)
![image](https://user-images.githubusercontent.com/425828/28693475-dd028a2e-72f2-11e7-99b5-053d7e18c0e5.png)

###### Actual Result

Negative times appear (see attached screenshot of Ankidroid -- the interface is in Hungarian and év means year). The times I'm seeing are the correct times minus 2^32 seconds.

![screenshot_20170727-173846](https://user-images.githubusercontent.com/425828/28693678-fac3d08a-72f3-11e7-8d3e-af19b2978a96.png)

###### Debug info
AnkiDroid Version = 2.8.2

Android Version = 6.0.1

ACRA UUID = 1964f9b2-d451-41a3-bfb8-d7818a1ecd87

**Comment by mikehardy** [comment]
@timrae this should be closed now I think (I was reading recent commits and saw a recent merge touched this)
