### ISSUE TITLE
Feature Request: Set Default TTS Language for Cards

### ISSUE THREAD

**Issue by jameskraus** [ankidroid/Anki-Android#4675]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Feature Request

Let's allow the user to set a default TTS language for all cards.

Example: I like TTS. Currently all my cards are in English, and I really really really wish I could just knock them out without having to select a tts language every time I have a new card. They're all the same, and even if I had a few ones in a different language mixed in, I'd be happy to switch their tts language.

Willing to submit a PR if that's what it takes.

**Comment by RenWenshan** [comment]
According to https://docs.ankidroid.org/manual.html

> Text to Speech
> Enable this option to have Android read out all the text on your flashcards using the default text to speech engine. Google’s built-in TTS engine should work; 3rd party TTS engines may or may not. AnkiDroid will ask you to select the language for the front and back of your cards once for each deck on the first time you review a card in that deck. To change the language or disable TTS for a given deck after making your initial choice, you’ll need to use the "reset languages" option described below and reconfigure for each deck.

**Comment by ildar** [comment]
actually this is only half of the truth.
You actually can set the BACK side language but not the FRONT. So this doesn't work fully. Please fix!!

**Comment by mikehardy** [comment]
@ildar we are always open to PRs https://github.com/ankidroid/Anki-Android/wiki/Contributing
