### ISSUE TITLE
Request: progress bar

### ISSUE THREAD

**Issue by egoals** [ankidroid/Anki-Android#4679]
Hello, first of all thank you all for the amazing work you have done so far. 

I just want to request a feature for you to consider: progress bars while reviewing. I don't really like to know how many cards exactly are left because it feels more like a burden (gosh 78 cards on french verbs again...), but I do want a sense were I am at. Also, when a progress bar is done there is a rewarding feeling of completude and achievement, which helps to keep the motivation to return everyday for reviews.

I picture the progress bar as a thin colored line. It could offer basic color options and some colors that match with the night mode...

Thank you very much.

**Comment by mikehardy** [comment]
the request matches material design pretty well (thin line) but no PRs are evident yet...
