### ISSUE TITLE
Crash On Saving (cards, settings, etc.)

### ISSUE THREAD

**Issue by tuedan** [ankidroid/Anki-Android#4680]
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open existing card while reviewing
2. Edit any field
3. Save with check button

###### Expected Result
Back to reviewing, changes saved.

###### Actual Result
Anki crashes, auto send bug report, restarts.

###### Debug info

AnkiDroid Version = 2.8.2

Android Version = 4.4.2

ACRA UUID = eac1428c-94f5-42b5-9b42-d17aff80ed61

**Comment by timrae** [comment]
Have you tried doing "check database" from the main menu in the deck list?

**Comment by tuedan** [comment]
Yes, the data base check runs successfully. If I edit cards through the
card browser, it saves without a crash.

-Daniel

**Comment by timrae** [comment]
Can you try doing "empty cards" as well?

**Comment by tuedan** [comment]
Yes, it returns "no empty cards"

-Daniel

**Comment by timrae** [comment]
Sorry we've been having a lot of issues with the crash report system recently...

```
      "Caused by: java.lang.NullPointerException",
      "com.ichi2.async.DeckTask.doInBackgroundUpdateNote(DeckTask.java:400)",
      "com.ichi2.async.DeckTask.doInBackground(DeckTask.java:247)",
      "com.ichi2.async.DeckTask.doInBackground(DeckTask.java:66)",
```

**Comment by timrae** [comment]
The crash is happening [here](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java#L400) indicating that your card doesn't have any note associated with it. It seems clear that there is something wrong with your collection... What happens if you try to reproduce the issue using Anki Desktop?

**Comment by tuedan** [comment]
The issue does not happen on anki desktop.

-Daniel

**Comment by timrae** [comment]
Weird... Could you please upload your collection or ideally a small test deck from which I can reproduce the issue? You can use post a Google Drive link here or email me directly if you prefer.

**Comment by tuedan** [comment]
Here is a link to the collection.

https://drive.google.com/file/d/0B0_Go7rPg2WDajNsakQzYUZ6ZFk/view?usp=sharing

-Daniel

**Comment by timrae** [comment]
Thanks, how should I reproduce the issue? Does it happen for any card or only some?

**Comment by tuedan** [comment]
Anytime I try to save an edit of an existing card during a review,
AnkiDroid crashes. If I save the card without making any changes, its fine.
If I edit the card from the card browser, it's fine.

-Daniel

**Comment by timrae** [comment]
There appears to be a problem with that file, I can't open it with Anki Desktop. Can you try again and check that you can open the resulting file yourself?

**Comment by tuedan** [comment]
I uploaded the file again. It opens on my AnkiDesktop.

https://drive.google.com/a/temple.edu/file/d/0B0_Go7rPg2WDY1VHUzBYcmpXREU/view?usp=sharing

**Comment by timrae** [comment]
I can't reproduce the issue... Here's what I did (for a few different cards):

* Click on 03 NihongoShark.com
* The card shows とても
* Choose Edit note from the menu
* Change Expression field to とてもおお
* Save

**Comment by tuedan** [comment]
Those same actions crash my AnkDroid. But the problem doesn't happen on
AnkiDesktop.

-Daniel

**Comment by timrae** [comment]
Can you try this:

* Go to advanced settings
* Change the collection path from `.../AnkiDroid` to `.../AnkiDroid2`
* Locate the file you sent me and rename it to `collection.apkg`
* Open the file and import it
* Try to reproduce the steps above again
