### ISSUE TITLE
[Feature Request] Conditional Replacement for tags

### ISSUE THREAD

**Issue by SirShadowwolf** [ankidroid/Anki-Android#4682]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Feature Request

Adding text replacement based on whether a card uses a tag or not, like it already is possible with fields. Such an Add-On already exists for the PC version (1523985889). Also, if it's not too much of a hassle, just like this Add-On provides, support for hierarchical tags (Add-On 1089921461), as they themselves are already working just fine with AnkiDroid as is.

Thanks for all your efforts and keep up the great work!

**Comment by eginhard** [comment]
We generally only add features that are included in Anki Desktop itself, i.e. not via any addons.
