### ISSUE TITLE
[Feature Request] See front of card again

### ISSUE THREAD

**Issue by VeloSteve** [ankidroid/Anki-Android#4683]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Study any card with an image on the front and text on the back.
2. Click Show Answer.
3. After seeing the back, decide that you need to review the image.
4. There's no way to get there.

###### Expected Result
Be able to see the image (front of card) in order to look for details I missed.

###### Actual Result
Can't find a way to see the image.

###### Debug info
N/A  I don't think this is a bug, just a missing feature.

**Comment by damccull** [comment]
As a workaround, you can edit your card definition to add {{front}} to the back of the card in order to see the front side on the back. I usually display the front on the front card, then on the back I display the front, a heading rule, then the back, like this:

Front
{{front}}

Back
{{front}}
<hr />
{{back}}


While I agree it'd be a nice feature to be able to flip back and forth, the main anki program doesn't do that either. I think it's designed not to on purpose.

**Comment by timrae** [comment]
If you manage to get this accepted into Anki Desktop then we will likely add it to AnkiDroid as well:
https://anki.tenderapp.com/

But if you use the default card layouts, they contain the [special field](https://apps.ankiweb.net/docs/manual.html#special-fields) `{{FrontSide}}` so there isn't really a need for such a feature IMO (i.e. your card template is simply defective)

**Comment by VeloSteve** [comment]
Thanks for both responses.  

I don't really want to see the picture on both sides most of the time, but {{FrontSide}} does work.  I'll try it as a workaround.  I'll also see if there's already a feature request for this on Anki.

**Comment by eginhard** [comment]
You could probably also use Javascript to only display the front side when you click on a button in your card template.

**Comment by timrae** [comment]
Or you can use `{{hint:FrontSide}}` if you want it hidden by default

**Comment by VeloSteve** [comment]
That's what I needed!  {{hint:FrontSide}} does the job.  Obviously I don't know all the options very well.  I'll study them more before making more templates.

I found that in Anki desktop there's an edit button which shows both sides of the card.  That would have also worked for me, but the AnkiDroid version is a little different.
