### ISSUE TITLE
Hata error yardım

### ISSUE THREAD

**Issue by Zekeriyya** [ankidroid/Anki-Android#4687]
Selamlar

Kisisel çalışma

Rastgele Seçilmiş Kartlara Çalış

Bu esnada program hata veriyor ve çıkış yapmam gerekiyor

Deste dolu olduğu halde boş gösteriyor

Destelerimi kullanamıyorum

Gün içerisinde fazla tekar yapamıyorum

 AnkiDroid Version = 2.8.2

Android Version = 5.0

ACRA UUID = 539aeb93-787b-4c11-a90b-f1848b5c3c1d

**Comment by nicolas-raoul** [comment]
Google translation:

> Error error help
> 
> Greetings
> 
> Personal work
> 
> Work on Random Selected Cards
> 
> At this time the program is failing and I need to log out
> 
> The deck is empty when it is full
> 
> I can not use my hardware
> 
> I can not make a lot of repairs during the day
