### ISSUE TITLE
How can i show the badge  in AnkiDroid App, that will display the number of cards which will be schedule to study today.

### ISSUE THREAD

**Issue by John0079** [ankidroid/Anki-Android#4688]
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by nicolas-raoul** [comment]
What do you mean by "badge"?
Could you please post an example of a badge in another app?
Thanks!

**Comment by John0079** [comment]
like this app [http://anki.oss-cn-hangzhou.aliyuncs.com/temp/QQ%E5%9B%BE%E7%89%8720170906102220.jpg](url) you can see the red dot and number in this dot;
i want to ankidroid can show how many card is waiting review like this style.

**Comment by nicolas-raoul** [comment]
This can be achieved by using the AnkiDroid 1x1 widget.
Could you please try?

**Comment by John0079** [comment]
how to use it ? is there the help document to guide me to do it?

**Comment by nicolas-raoul** [comment]
Just long-press on your Android home screen then choose "Widget" then
"AnkiDroid".

**Comment by John0079** [comment]
yes , I found it, Thanks very much! it is great!
