### ISSUE TITLE
Cards don't show answers

### ISSUE THREAD

**Issue by victorsjo** [ankidroid/Anki-Android#4690]
Hi everyone. After a while - more or less a month - I didn't use Anki, all of cards suddenly stopped showing answers on the back. I tried to upgrade and reinstall the app and the desktop software (the problem is the the same both on the smartphone and on the computer), but it seems it didn't fix any bugs. I noticed in the Card Browser the answers field loading and showing anything at all (first attachment): could anyone help me?
![screenshot_20170829-012250](https://user-images.githubusercontent.com/31423154/29797674-eb5d03ea-8c58-11e7-9701-b8d4ab5c9bf4.png)
![screenshot_20170829-012639](https://user-images.githubusercontent.com/31423154/29797733-2e815ec8-8c59-11e7-9e82-31d181ef949f.png)
![screenshot_20170829-012648](https://user-images.githubusercontent.com/31423154/29797740-362365fe-8c59-11e7-85bc-3dbf9a2aab72.png)

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-do-my-cards-display-incorrectly
