### ISSUE TITLE
Update Russian locale

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#4693]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
Use AnkiDroid in Russian

###### Actual Result
The translation contains a lot of mistakes and is not consistent with AnkiDesktop as suggested by the [contribution guide](https://github.com/ankidroid/Anki-Android/wiki/Contributing#translate-ankidroid).

Major errors have been corrected at Crowdin.

**Comment by nicolas-raoul** [comment]
Thanks for your report!

Could you please fix the problems at http://crowdin.net/project/ankidroid ?

Thanks a lot!

**Comment by homocomputeris** [comment]
I have fixed major ones, please pull the changes to the master (or whatever).

**Comment by timrae** [comment]
The changes you made on crowdin [in May](https://crowdin.com/project/ankidroid/ru/activity) should be in the latest alpha.

**Comment by homocomputeris** [comment]
Done.
Hope to see fixes in the next build soon.

**Comment by homocomputeris** [comment]
@timrae Could you pull Crowdin changes into the next alpha? Latest translated strings do not appear in alpha 75.

**Comment by timrae** [comment]
Done!
