### ISSUE TITLE
Hebrew with arabic shadda doesn't show

### ISSUE THREAD

**Issue by cjer** [ankidroid/Anki-Android#4696]
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Create note in Hebrew with arabic shadda ّ.
2. When reviewing note, it will show as a square דّ
3. When editing nore it will show correctly.

###### Expected Result

Show characters correctly

###### Actual Result

Shows squares

###### Debug info
AnkiDroid Version = 2.8.2

Android Version = 7.1.2

ACRA UUID = 90f324f6-2ae1-4e8d-b131-7aef21902200

**Comment by nicolas-raoul** [comment]
Did you try using a custom font? https://docs.ankidroid.org/manual.html#customFonts

**Comment by cjer** [comment]
Works! Thanks!
