### ISSUE TITLE
"Type in the answer" auto focus for answer field

### ISSUE THREAD

**Issue by readych** [ankidroid/Anki-Android#4699]
Is there a way to have an auto focus of the answer field like the desktop version Anki does?
This would improve the handling of answering this kind of cards a lot.
At the moment, I have to touch on every card first the answer field before I can type in the answer. This is a bit annoying if I have to solve 100 cards.

**Comment by david-allison-1** [comment]
I'd like to get this done at some point in the future.

**Comment by jportoles** [comment]
What seems to be the hold up? Shouldn't this be merged mainstream by now?

**Comment by mikehardy** [comment]
I'm sorry @jportoles I didn't see the pull request where you proposed the fix for the feature? Let me know when it's ready and I'll review

**Comment by jportoles** [comment]
Ah nevermind, I thought https://github.com/ankidroid/Anki-Android/pull/4818 was good to go, hence the question.

**Comment by mikehardy** [comment]
@jpertoles that one was closed stale / no attention, if you wanted to take the work up and get it through, we are definitely receptive. I feel like things that went stale are fair game to take and move forward by other people no problem, just with some friendly attribution

**Comment by jportoles** [comment]
@mikehardy okay, thanks, will take a look.

**Comment by Arthur-Milchior** [comment]
Someone contacted me to work on it. I assume @jportoles that you're not working on it anymore.

**Comment by jportoles** [comment]
@Arthur-Milchior no, did not have time unfortunately, feel free to go ahead.

**Comment by 4D17Y4** [comment]
I'd like to work on this one if no one is working on it.

**Comment by david-allison-1** [comment]
@Arthur-Milchior, is the person you mentioned working on this?

**Comment by prince-09** [comment]
@david-allison-1 can I work on this?

**Comment by Arthur-Milchior** [comment]
> @Arthur-Milchior, is the person you mentioned working on this?

no. 

@4D17Y4 if you don't work on anything else, please take it. Please also note what you're working on on https://docs.google.com/spreadsheets/d/1desofSHMBVWEhQUnDeFxcEefoBVT9fStfC6H_slUl0o/edit#gid=0

**Comment by 4D17Y4** [comment]
I just finished on the other issue, will take this up, thanks.
Should I be adding this one to assigned ?

**Comment by Arthur-Milchior** [comment]
Yes please
