### ISSUE TITLE
AnkiDroid sets itself as background wallpaper on Android 6.0

### ISSUE THREAD

**Issue by charlesoblack** [ankidroid/Anki-Android#4701]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
Uncertain on these. This does not make it happen every time, only once in a while.
1. Have AnkiDroid running.
2. No password/passcode/lock code set.
3. Launch AnkiDroid from the "quick bar" on the lock screen

###### Expected Result

AnkiDroid opens normally.

###### Actual Result

AnkiDroid opens, but sets its own image as the phone home screen background. This does not get updated when AnkiDroid is on a different screen, for example.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.2

Android Version = 6.0

ACRA UUID = e7b8fd0a-ae52-4444-9980-7fa8f7816db4

**Comment by timrae** [comment]
I've seen this happen before when using the sync intent... No idea how to reproduce or fix though.

**Comment by mikehardy** [comment]
Closing this for now, if we can reproduce please open it with details
