### ISSUE TITLE
Import enhancement: a new checkbox on import form "Mark updated cards".

### ISSUE THREAD

**Issue by rafenciugo** [ankidroid/Anki-Android#4710]
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

First of all, thank you guys for the great job you do. I am a devoted Anki user and would like to come up with an enhancement. I imagine useful for many Anki users.

A Problem:
I use an external file to create a content (cards) and from time to time, I import it into Anki using its import functionality (menu File / Import). New cards are created automatically and some cards with the first field matched get updated. 

Unfortunately, there is no option to automatically reschedule interval or set as Marked cards that have been updated by the import process. It means that if you have learned something incorrectly specified on the card, although the card has been just updated, you will not be aware of that. You will not be able to review the updated cards before the day they are scheduled for. 

The Solution: New checkbox on import form "Mark updated cards"

Import functionality, in particular, the import form where you specify field mapping, note type, and other information, should have an additional checkbox, called  "Mark updated cards". When selected, all the updated cards would be set as Marked. Thanks to that, a user using a "card browser" could manually review updated cards and verify if the update significantly changes what he has already learned. If necessary the user could change the interval of the card manually to repeat learning process or simply, leave it as it is, and Unmark the card,  

If necessary I am ready to specify more details. I could also engage as a tester.

I'm looking forward to seeing what you think about that enhancement.

**Comment by rafenciugo** [comment]
Hello AnkiDroid Comunity

I have just noticed that that the enhancement described above is supposed to be assigned to the Anki desktop edition, and not to the AnkiDroid which is the mobile app.  As I am new here, I would appreciate it if someone could confirm that and help me reassign this issue. 

Kind regards, R.

**Comment by david-allison-1** [comment]
Hi @rafenciugo 

Blast from the past! 

You're best to ask: https://anki.tenderapp.com/discussions/ankidesktop/, or put an addon request on the subreddit.
