### ISSUE TITLE
'added cards' statistic does not reflect the number of added cards.

### ISSUE THREAD

**Issue by evanherk** [ankidroid/Anki-Android#4722]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open ankidroid
2. go to a stack, choose statistics and scroll down to see 'added cards'
3. note the number
4. Add some cards to the stack
5. look at statistics/ added cards again - no change
6 synchronize the stack
7 look at statistics/ added cards again - no change
sometimes the number fluctuates somewhat, but is is never correct. currently it reports 1112 cards as added in android in the last month, and my PC version gives 1846 cards added in the last month.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by david-allison-1** [comment]
Need to confirm that this is still occurring, but it looks like a bug

**Comment by david-allison-1** [comment]
Trivially reproducible under SchedV1:

I have a deck: `Default::aa`

Add a card to the deck. Statistics still show 0 cards added.

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/fdadd0f6ef21863c7d8318e089b3d92320cc84d6/AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java#L63-L64

https://github.com/ankidroid/Anki-Android/blob/c27f3907a6da9f6bf3dbe545a91a732ed5215352/AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java#L303-L304

Timespan:
```
ordinal = 0
name = "TYPE_MONTH"
days = 30
```

`oStats.allDay = 30`

`query = SELECT COUNT(*) FROM(
            SELECT distinct cid
            FROM revlog 
WHERE id > 1.5938316E12 AND cid IN (SELECT id FROM cards WHERE did IN (1596065982942)) EXCEPT SELECT distinct cid FROM revlog WHERE id <= 1.5938316E12 AND cid IN (SELECT id FROM cards WHERE did IN (1596065982942)))`


----

Anki 2.0.52 used:

https://github.com/ankitects/anki/blob/5410321c0e8e623a528deb2541055fef4d2b3bc8/anki/stats.py#L430-L449 to obtain the data

and 

https://github.com/ankitects/anki/blob/5410321c0e8e623a528deb2541055fef4d2b3bc8/anki/stats.py#L271-L299

**Comment by david-allison-1** [comment]
One issue:

https://github.com/ankidroid/Anki-Android/blob/c27f3907a6da9f6bf3dbe545a91a732ed5215352/AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java#L197

SECONDS_PER_DAY is a double, converting the result to a double, but it's inconclusive, as we're using the incorrect query
