### ISSUE TITLE
TTS lines get joined with no spaces

### ISSUE THREAD

**Issue by rlpowell** [ankidroid/Anki-Android#4723]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1.  Have automatic TTS turned on
2. Have a card with text like:
tan
eye
3.  Have a card with text like
tan 
eye
(note there is an extra space character after "tan")

###### Expected Result

Both are pronounced the same.

###### Actual Result

The first is pronounced as "taneye" (TAIN-eye)

Apparently, when lines are joined for TTS, they are joined with no spaces or anything; this is pretty terrible.

Ideally, TTS would not join lines at all, but if you must, join with " ", or, better, join with ". ", so there's a pause.

**Comment by GithubDG** [comment]
I also noticed such behavior.
My theory is that TTS engine is using strict HTML-tag filter which just removes these tags, not replaces them with anything.

As a workaround - I am preparing my cards with additional "space" character at all line breaks. Not ideal, but at least lets TTS work.

**Comment by timrae** [comment]
You might wanna try the new advanced TTS support:

https://github.com/ankidroid/ankidroiddocs/blob/v2.9-preview/manual.asc#advanced

**Comment by rlpowell** [comment]
I don't know how to try pre-release versions of AnkiDroid; I'll certainly try when that's release.

I don't see how it would help, though; whether or not a particular language can be defined for an utterance doesn't seem to me to have much to do with how tags are stripped during TTS.

**Comment by timrae** [comment]
Well you can read aloud specific fields, instead of just reading the whole text aloud. I thought the extra control might allow you to solve the issue, but yeah maybe not.

**Comment by Xyde** [comment]
I tried 2.9beta and the issue is still there. Kind of drives me insane when combined with the other TTS issue.
