### ISSUE TITLE
No file name conflict resolution

### ISSUE THREAD

**Issue by CowboyEnvy** [ankidroid/Anki-Android#4725]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. download images to android device (image.jpg image(2).jpg image(3).jpg)
2. replace images from exiisting cards with image(...).jpg files
3. delete image(...).jpg files from download folders
4. download additional image(...).jpg files
5. replace image inside note with file of the same name of an image already in database.

###### Expected Result

Anki should check to see if image(x).jpg inside the database and image(x).jpg outside the database are the same file (generating a hash key stored inside the database and checking new image file against that)
assuming files are the same use the prexisting file
assuming files are not the same (hash comparison issue) promt with the following options
1) replace existing image inside the database 
2) rename file (possible random generation/ image(x+1).jpg
3) cancel 

at minimum a prompt should warn about conflicting file names and display the image in the database along side the 'selected image' 

###### Actual Result

Ankidroid shows the 'new selected image' as what will appear in the card in the future but after commiting the changes  to the deck  the image already in the database is used

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid = 2.8.2

Android Version = 6.0.1

ACRA UUID = 7803e464-ce8a-4e19-92e0-b469125b42

**Comment by n1snt** [comment]
Looks like it has been open for a long time.
Is anyone working on this? If not I would love to have a try at this.

**Comment by david-allison** [comment]
Ensure it works with the new backend. We'll be removing the Kotlin backend imminently and it's not worthwhile developing for

**Comment by dae** [comment]
Should be fixed by the new backend.
