### ISSUE TITLE
Phone reboots randomly when I have many Anki cards

### ISSUE THREAD

**Issue by cristi101** [ankidroid/Anki-Android#4726]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. get a samsung galaxy note 4
2. install anki from play store
3. configure anki for storage on sdcard
4. add several large dictionaries: english, french, german (around 70000 files on sdcard in one directory)
5. try to find the amount of storage used (from settings/system/storage) or try to install new updates for existing apps

###### Expected Result
Everything works as expected without delays.
The amount of storage used is shown quickly.

###### Actual Result
The amount of storage used is not shown.
The phone reboots randomly.
When installing updates, the progress is not shown and it take a long time and several reboots to install all updates.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by timrae** [comment]
> configure anki for storage on sdcard

https://github.com/ankidroid/Anki-Android/wiki/FAQ#my-ankidroid-files-are-stored-on-a-sd-card-how-can-i-point-ankidroid-to-them

**Comment by cristi101** [comment]
I've already read that link about how to configure Anki for sdcard.
That is how I got it working with the sdcard.

I understand that you do not have official support for sdcard yet but you
should.

1) the internal memory of phone is very limited. It fill fast with app code.

2) Anki is working when pointed to sdcard.

The only problem is with the large number of files in one directory, I
think.

I have not tested it with internal memory because I don't have enough space
left.
On sdcard I have plenty.

**Comment by timrae** [comment]
It's almost certainly a problem with either your device or the OS / driver. We only use standard APIs to access the file system, and there's no way that would cause the issues you are describing.

**Comment by timrae** [comment]
You might like to try [formatting your SD card as ExFAT](https://github.com/ankidroid/Anki-Android/wiki/FAQ#i-have-too-many-media-files-and-cant-copy-them-all-to-my-device), it's worth a shot, but you'll need root.

**Comment by cristi101** [comment]
The card was formatted as exFAT by the phone. The large number of files
seems to be the problem. After I delete them everything is OK. After I copy
them back, the phone act as described (random reboots)

On 7 Nov 2017 10:23, "Tim Rae" <notifications@github.com> wrote:

You might like to try formatting your SD card as ExFAT
<https://github.com/ankidroid/Anki-Android/wiki/FAQ#i-have-too-many-media-files-and-cant-copy-them-all-to-my-device>,
it's worth a shot, but you'll need root.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/4726#issuecomment-342408775>,
or mute the thread
