### ISSUE TITLE
Media files are re downloaded with every single sync

### ISSUE THREAD

**Issue by mo7amed0metwally** [ankidroid/Anki-Android#4727]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. All media files are redownloaded each time I try to sync
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.2

Android Version = 7.0

ACRA UUID = b9828943-e86e-41b8-add1-f8a580c4b085

**Comment by mo7amed0metwally** [comment]
The latest version till date is syncing properly on my Android tablet (android version 5.0), the issue is on my phone

**Comment by mikehardy** [comment]
That must be very irritating!

Unfortunately, I can't reproduce this personally. The only thing I can think of is related to [this post](https://www.reddit.com/r/Anki/comments/53t0bv/media_constantly_redownloading_even_when_not_used/) where some one else had re-downloads over and over again.

The solution for that poster was essentially to delete AnkiDroid from the offending device (your phone, I guess?) making sure to get rid of all the backups anywhere - absolutely everything AnkiDroid related including prefs and things in /sdcard, then re-install it, and attempt to re-sync. Might work?
