### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#4732]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Have, on ankiweb, strings which are too long. 
2. Sync ankidroid

###### Expected Result
An error message as soon as the error can be detected, before the full download

I.e. since you know that there may be an error when there are too many note type, download this first. While the remaining is downloading, check whether the string is too long. If it is the case, abort the downloading. 
I imagine that this would probably not help a lot of people.  Let me explain how it would help me.
Since there is no way to know, in advance, whether the string's size problem will occur or note, I need to try to sync to see whether I successfully solved. the problem Each sync cost 50mb of bandwidth each time. This is costly, and takes time. 

At least in my case, it would be really helpful, because each time I try to download again, I have to download 50MB, before I finally see that the sync led to something I can't use.

###### Actual Result
The database is fully downloaded before the error message is shown.

###### Debug info

I can't access Debug Info while having this error message.

**Comment by timrae** [comment]
There isn't really any way to achieve what you are asking for unfortunately... Once the db exceeds the limit, we can't open it anymore. Also, it's essentially always the same string (models JSON), so I don't think this feature would be very useful. In any case, it should be obvious which string it is from opening the db in sqlitebrowser. In your case, since you're saying it wasn't obvious, I suspect it might be some other issue.
