### ISSUE TITLE
Bug Report: Cannot slide the right bar normally

### ISSUE THREAD

**Issue by standarm** [ankidroid/Anki-Android#4735]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

After I choses the **Card browser** to arrive the [*All deck* list](https://i.stack.imgur.com/aUc4e.png). Because I have so many decks. So I try to slide the right bar. But I always cannot arrive that desk position that I want to be. I record a gif to specify [the question I have meet](https://imgur.com/a/mdqYM). Note the [right bar](https://i.stack.imgur.com/FjzZw.png) closely. It will back to original position after you finish the slide.

Actually this bug persisting through many version, include your latest **2.9alpha14**. Please fix.

**Comment by standarm** [comment]
@timrae Please pay attention to this bug.

**Comment by timrae** [comment]
Your gif doesn't play for me... Post an actual video please. It sounds like it's a problem with your device anyway, as AnkiDroid doesn't have any code at that kind of framework layer.

I recommend that you try to reproduce it on another Android device, or with the simulator in Android studio. If you can reproduce it we can try updating the support library version or report a bug to Google.
