### ISSUE TITLE
Missing Play Button in tts-mode

### ISSUE THREAD

**Issue by grossy-grossy** [ankidroid/Anki-Android#4738]
Hi,
There ist no Play Button when I use tts dir cards. If ist audio in a card, then there is a Play Button. So, I have time open the menu to replay the tts. Ist ist possible to place a replay Button in the Card?

**Comment by timrae** [comment]
> [Is it] possible to place a replay Button in the Card?

I don't think so, but you can enable a play button on the toolbar with "customize app bar" in review settings.
