### ISSUE TITLE
Cannot change cloze color in Night Mode

### ISSUE THREAD

**Issue by froman753** [ankidroid/Anki-Android#4742]
I do not see an option for changing the color of cloze text when Night Mode is enabled. It appears there is some default color of blue that overrules whatever the cloze color the card CSS says. If this overrulling color could be removed or if there could be an option for changing the color, that would be appreciate.

**Comment by d0ct0rtrev0r** [comment]
Have you figured this out yet? I'm still searching.

**Comment by froman753** [comment]
I posted the solution that ended up working for me here:
https://www.reddit.com/r/Anki/comments/7fr6pu/changing_the_cloze_color_of_night_mode_on/

**Comment by d0ct0rtrev0r** [comment]
Just added the code, and it works great. Thanks for your help.
