### ISSUE TITLE
Tags in cards

### ISSUE THREAD

**Issue by Mornon** [ankidroid/Anki-Android#4743]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

Would it be possible to have tags (all, or specific ones) show somehow in cards? Mainly, I'd love Anki to tell me when the card I'm studying is a leech, so to be able to maybe be a more conservative with those cards.

(I know I can select to see just leech cards, but I'd like to be able to have some highlight on that regard also during normal study.)

**Comment by evolverine** [comment]
If your leech is tagged as such, you can apply a bit of javascript to make any visual changes for them. See this discussion for details: https://anki.tenderapp.com/discussions/ankimobile/5468-conditional-render-based-on-tag

**Comment by Mornon** [comment]
Thanks, unfortunately I have no idea about how to implement it, I don't know anything about JavaScript; I'll try to take a look when I have time.

**Comment by evolverine** [comment]
Ok, I've made a slightly more customised version of that script for your needs. (I'm not sure if the default leech tag is "leech" - can you confirm?). Just copy and paste it at the end of the card template. It is ugly, just writes a sentence (which, of course, you can change), but it should do the trick. If you learn a bit more JS + HTML + CSS, you can maybe set a style on a warning, or make visible an icon, etc. It's not that difficult, I think; if you have some time, you'll probably enjoy tinkering with it. Good luck!

`<script type="application/javascript">
var desiredTag = "leech";
if ("{{Tags}}".split(" ").indexOf(desiredTag) >= 0) {
    document.write("This is a leech");
}
</script>`

**Comment by Mornon** [comment]
Yes, the tag is "leech"; thanks for the code, I'll look for the template and try to use this code, thanks again!

**Comment by Mornon** [comment]
I can't find where in AnkiDroid I should put that code.

**Comment by evolverine** [comment]
If you use the desktop app, I find it easier to do it there first and then sync, but it's also possible in AnkiDroid: select the top-right menu button, tap on "Manage note types", long-tap on the type that your flash cards are*, tap on "Edit cards", then paste the javascript code under {{Front}}, or whatever the front template is.

Good luck!

* if you don't know what type your notes are, then when you review them simply tap on the top-right menu button, then tap on "Edit note". On the top of the screen you'll be able to see the note's type. Remember that name, that's what you'll have to long-tap to edit its template.

**Comment by Mornon** [comment]
I was able to, thanks again; I was wondering if it's possible to have something like "If it's leech write the card in red"? I'm trying to come up with a code for that, but with little luck at the moment.

**Comment by timrae** [comment]
You can show a list of tags by adding `{{Tags}}` to your template
