### ISSUE TITLE
New cards should be given at midnight, rather than at noon

### ISSUE THREAD

**Issue by CalebBiddulph** [ankidroid/Anki-Android#4745]
###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

It seems that AnkiDroid gives me new cards and reviews for the next day at noon, which doesn't seem to make as much sense as midnight, since I can't start reviewing more cards in the morning. Either that, or an option to choose the time of day to cycle cards would be nice.

**Comment by guillaumebrunerie** [comment]
You can choose the time of day in Settings -> Reviewing -> Start of next day.
