### ISSUE TITLE
Fresh build from source crashes on first run with permission failure

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4748]
I have followed all recommended research steps, and simply elided them for a more concise report

Reproduction:
1. git fork / clone / build / run on emulator that has never run ankidroid before (master/HEAD as of time of this bug report)
2. AnkiDroid crashes on startup

Useful(?) portion of stack trace:

E/CollectionHelper: Could not initialize AnkiDroid directory
                    com.ichi2.anki.exception.StorageAccessException: No write access to AnkiDroid directory
                        at com.ichi2.anki.CollectionHelper.initializeAnkiDroidDirectory(CollectionHelper.java:175)
                        at com.ichi2.anki.CollectionHelper.getCol(CollectionHelper.java:91)
                        at com.ichi2.anki.services.BootService.scheduleDeckReminder(BootService.java:47)
                        at com.ichi2.anki.services.BootService.onHandleIntent(BootService.java:39)
                        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)

Workaround:
If you manually go into Android settings for the app and grant permissions, it works

Thoughts:
On first inspection I was unable to see where AnkiDroid *asks* for permission in the code. Either way, on first startup it seems it should attempt to ask the user if it may have the permissions it needs, and if it doesn't have them it should give a nice error message prior to closing rather than a crash.

You can reproduce this easily on a device that has AnkiDroid already by doing the parallel build process (but it appears with a clean local build as well!)

Please tell me if I'm just missing something obvious, otherwise, I could also accept nudges towards how to implement a permission-request-on-first-run plus a graceful-message-then-close thing

**Comment by timrae** [comment]
Sorry just saw this, I noticed it today as well and fixed it in my latest PR

**Comment by mikehardy** [comment]
I fetch/merged this and it does look fixed to me now
