### ISSUE TITLE
[enhancement] Sort menu items by usage frequency

### ISSUE THREAD

**Issue by rillig** [ankidroid/Anki-Android#4757]
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. In the main menu, long-press on a deck.

###### Expected Result

The menu shows the most relevant items first. For me, that would be:

* User-defined learning
* Recall postponed
* More...
** Rename deck
** Deck options
** Export deck
** Delete deck

Seldomly needed menu items should be hidden in a submenu.

###### Actual Result

The menu items are arranged in a seemingly arbitrary order.

**Comment by timrae** [comment]
I don't think there's an obvious priority level for each menu item, but we could sort them alphabetically (in English), and that would put "custom study" at the top, which is what you are referring to I guess.
