### ISSUE TITLE
[enhancement] When creating filtered decks, allow filtering based on tags and cards

### ISSUE THREAD

**Issue by rillig** [ankidroid/Anki-Android#4758]
###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. On the main screen, press on "Create filtered deck"
2. Try to create a deck consisting of all cards tagged "unit_14" having ord=0

###### Expected Result

The above step 2 is possible.

###### Actual Result

* There is no UI element where I can select one or more tags.
* There is no UI element where I can select the card type(s).

**Comment by timrae** [comment]
There are no UI elements to add anything for a filtered deck, because it's intended to give low-level access for advanced users to the search query. If you need a graphical frontend, then use Custom study -> Limit to particular tags.
