### ISSUE TITLE
[enhancement] Collapse popup menus for learning cards

### ISSUE THREAD

**Issue by rillig** [ankidroid/Anki-Android#4760]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open the learning activity for a note with two cards
2. Open the menu

<div align=center><kbd><img src="https://user-images.githubusercontent.com/3233724/34085093-5f70c8f0-e38b-11e7-9334-6dae19f78b00.png"></kbd></div>

###### Expected Result

There are two menu items:
* Postpone card
* Postpone note

Having a submenu for just two entries feels too much.

Use case: I'm currently learning a deck with about 3000 vocabulary cards and want to quickly sort the known ones away. To do this, I selected 200 cards, and now I either mark each card as "simple" or I postpone it. The latter case is more complicated than necessary.

###### Actual Result

* There is a submenu "Postpone" with two entries
** Postpone card
** Postpone note

**Comment by timrae** [comment]
This was a conscious decision that we made sometime ago in order to reduce clutter in the menu. If you go to `settings -> reviewing -> app bar buttons` you can force a button for the submenu to appear in the toolbar, which will slightly ease the pain (two clicks instead of three)
