### ISSUE TITLE
Incluiding a option of change the order of deck

### ISSUE THREAD

**Issue by Towerfree** [ankidroid/Anki-Android#4762]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x  ] I have searched for similar existing issues here and on the user forum

I have a suggestion for app.

Including a function for change the order of decks. For exemplo, I am studying English > portuguese, so I could press or select one option for change the order of decks to portuguese > English.

Thanks.

**Comment by timrae** [comment]
https://docs.ankidroid.org/manual.html#reverseCards
