### ISSUE TITLE
Saved searches are deleted during synchronization

### ISSUE THREAD

**Issue by Aleks-Ya** [ankidroid/Anki-Android#4764]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

----
Hi,
I use Anki computer version + Anki Android + cloud sync.
Some monthes ago I found a bug related to saved searches. Unfortunatelly, It's still here.

This bug on Anki PC: [link](https://anki.tenderapp.com/discussions/ankidesktop/26296-saved-searches-are-deleted-during-synchronization)
Anki PC developer's comment:

> Anki is marking the collection data as modified when the filter is saved, so the only reason it would disappear is if when syncing AnkiDroid, the collection is marked as more recently modified in AnkiDroid. If AnkiDroid was in sync prior to syncing the computer and you made no changes on AnkiDroid it sounds like a bug in AnkiDroid - please report the issue to the developers.

###### Reproduction Steps

1.    In Anki PC
        1. Open browser, do any search
        1. Click heart icon and enter search name
        1. (Can see the saved search in browser)
        1. Synchronize with the cloud
        1. (Still can see the saved search in browser)
1.    In Anki Android:
        1. Synchronize
1.    In Anki PC
        1. Synchronize
        1. The saved search is absent. Expect to see the saved search in browser.

###### Expected Result
The saved search is absent in Anki PC.

###### Actual Result
The saved search is present in Anki PC.

###### Debug info
AnkiDroid Version = 2.8.3
Android Version = 7.1.1
ACRA UUID = 4f1a71fd-0b4e-40c9-9dfa-afb7cd3e5803

Anki computer version:
Version 2.0.32 (Linux)
Qt 4.8.7 PyQt 4.11.4

**Comment by Compusomnia** [comment]
I have the same problem, albeit on computer version 2.0.51 under Windows 10.

**Comment by mikehardy** [comment]
Strange. I checked and we are definitely using/accessing the same chunk of JSON in the Deck config as Anki desktop uses ("col.conf.savedFilters").

I didn't inspect JSON formats internal to that JSON area to see if they've diverged and are causing this.

Might be related to #4420 where a different item from col.conf is having synchronization issues with AnkiDesktop.

**Comment by pavreh** [comment]
Tested with Anki version ⁨2.1.53 Qt 6 (Windows) and AnkiDroid version 2.16alpha67. I cannot reproduce this bug. The saved search is still present in Anki PC after sync. Someone should test it in Linux.

**Comment by pavreh** [comment]
@mikehardy It's my pleasure to help with this awesome app. Pavel

**Comment by wujek-srujek** [comment]
I can reproduce this issue 100%. Here are the steps:

1. Open Anki Desktop (I'm on a mac).
2. Open the browser, create a search (a typical use case of mine, and the one I've observed this with is `-flag:0`).
3. Save it (Saved searches -> Save current search).
4. Close the browser.
5. Sync using the desktop version.
6. Open the browser again - the saved search is still there.
7. Close the browser.
8. Sync using AnkiDroid.
9. Sync using the desktop version.
10. Open the browser again - the saved search is gone.

**Comment by david-allison** [comment]
@wujek-srujek Could you post debug information (Settings - About - Copy Debug Info)?

**Comment by wujek-srujek** [comment]
Sure.

AnkiDroid Version = 2.16.5 (953b9bd879269910ee962b520da9705336d8bc2d)

Android Version = 14

ProductFlavor = play

Manufacturer = Google

Model = Pixel 7 Pro

Hardware = cheetah

Webview User Agent = Mozilla/5.0 (Linux; Android 14; Pixel 7 Pro Build/UQ1A.231205.015; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/120.0.6099.43 Mobile Safari/537.36

ACRA UUID = 1a81993f-e029-414a-bf93-61365f783895

New schema = false

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
