### ISSUE TITLE
the notification is not working

### ISSUE THREAD

**Issue by st603** [ankidroid/Anki-Android#4766]
android 7.0

**Comment by mikehardy** [comment]
Interesting - which notification, what version of AnkiDroid, and what version of android?

**Comment by mikehardy** [comment]
If using current builds from source, this now has a workaround in place, and notifications should be functional.

**Comment by timrae** [comment]
So the easiest way to fix this is by upgrading to the latest 2.9 alpha version I guess.
Alternatively, if you're still on v2.8.x then a workaround is to just add the AnkiDroid widget to your homescreen.
