### ISSUE TITLE
Card browser second column is missing interval

### ISSUE THREAD

**Issue by dequis** [ankidroid/Anki-Android#4767]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open card browser
2. Tap the header of the second column
3. See offered options

###### Expected Result

Options including "interval". And, possibly, the other hidden options too:

    {"changed", "created", "due", "ease", "edited", "interval"}

###### Actual Result

The available options are

    {"answer", "card", "deck", "note", "question", "tags", "lapses", "reviews"}

###### Other

This feature was originally added for issue #2212 with only four columns. https://github.com/ankidroid/Anki-Android/issues/2212#issuecomment-125513483 says:

>However, unfortunately I have only made the following columns available:
>Answer / Deck / Question / Tags
>
>It's quite a bit of extra work to include the others, and lower priority than the "answer"
>side of the card, so I will skip it for now and make a separate issue.

This corresponds to git commit 8864b996e0bd2a9b6bbc5183e5079167523a0fe0

Shortly afterwards, four more columns (Card, Lapses, Note, Reviews) were added in 062d0e474d42feda7de4714cba20f5870c241f89

###### Implementation stuff

A comment above `COLUMN2_KEYS` in `CardBrowser.java` points that they are hidden:

https://github.com/ankidroid/Anki-Android/blob/e6eb737a400a34ce8e9d2268e0b1566d7a2119d9/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L134-L150

The hiding is done through the language files, apparently:

https://github.com/ankidroid/Anki-Android/blob/e6eb737a400a34ce8e9d2268e0b1566d7a2119d9/AnkiDroid/src/main/res/values/02-strings.xml#L60-L77

It's a string array, and uncommenting that means the rest of the language files complain about length mismatch, which probably means that a localized version won't have those additional entries until they are translated or the english strings are copied to all the other languages.

I don't know what's the right thing to do here, never dealt with android localization and the translations editor of the IDE doesn't show string arrays at all.

The implementation for these appears to belong here:

https://github.com/ankidroid/Anki-Android/blob/e6eb737a400a34ce8e9d2268e0b1566d7a2119d9/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L965-L978

Getting a simple bare integer seems easy:

    item.put("interval", Integer.toString(c.getIvl()));

Turning it into a localized "%s days" string seems to involve calling `Utils.timeSpan` which requires a context (`c.getCol().getContext()`?).

Not sure it's okay to get the context like that from this particular static function, `updateSearchItemQA`.

FWIW I also implemented ease, but it shows 0% instead of `(new)` (because translations are hard)

    item.put("ease", Integer.toString(c.getFactor() / 10) + "%");

**Comment by timrae** [comment]
Feel free to open a PR, most likely I just copied that code over from python without attempting to compile or test it. It most likely requires a little bit of extra work to get it displaying the same as in Anki Desktop.

> Turning it into a localized "%s days" string seems to involve calling Utils.timeSpan which requires a context

Sorry I'm skim-reading your post, but you should just be able to pass in the result of `getContext()` from the `Activity`

**Comment by mikehardy** [comment]
I believe this was just closed with #5592 and should be available in not-yet-released 2.10alpha50

**Comment by dequis** [comment]
Hm, interesting, the diff shows interval as already there. The `context` problem I had when I tried to implement this issue is already passed to this version of the function, too. Neat.
