### ISSUE TITLE
Search over all decks, not just the selected

### ISSUE THREAD

**Issue by guettli** [ankidroid/Anki-Android#4768]
###### Research

[X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. I have created several decks: For example: Diary, TODO, Remember ...
2. I want to update a card which I created a week ago.
3. I would like to search over all decks for a word. For example "Italy"

###### Expected Result

The overview page in ankidroid which shows all available decks has menu item where I can search over all decks.

###### Actual Result

I can't find a "search over all decks" menu item

###### Next?

Solution Variant1: I was blind, this feature already exists: Then I am very sorry

Solution Variant2: This is a feature request and you would accept a pull request

Solution Variant3: This is a feature request and you won't accept a pull request.

If V2: I can't provide a Pull-Request. Are there developers which could do this? I am willing to pay money for this.

**Comment by federvieh** [comment]
- Open the navigation menu by sliding it in from the right or pressing the
"hamburger" icon in the upper right corner
- select "Card browser"
- in the tool bar you can select the deck you'd like to browse/search or
you can select "All decks"

Is this what you are looking for?

Thomas Güttler <notifications@github.com> schrieb am So., 7. Jan. 2018,
09:47:
