### ISSUE TITLE
Wrong fallback font for Japanese?

### ISSUE THREAD

**Issue by ju-w** [ankidroid/Anki-Android#4775]
### Issue
When having Japanese characters on a card and no Japanese font explicitly associated to it in the CSS, Anki uses a font that displays the characters incorrectly. It falls back to a font, which is not the system font.

###  Example

Create a card with a kanji that is written differently in Chinese
Here: 泡, other examples are 直, 刃, 器, 褐, ...

![screenshot_20180124-201844](https://user-images.githubusercontent.com/22564375/35353303-11e08b3c-0147-11e8-98a5-1a0d1ddc9f4c.png)

Here the correct font is used.

![screenshot_20180124-201852](https://user-images.githubusercontent.com/22564375/35353354-370eec1e-0147-11e8-861f-f3a2b5cab08f.png)

Also here.

![screenshot_20180124-201904](https://user-images.githubusercontent.com/22564375/35353378-4a5cd272-0147-11e8-88c2-b8fe16a2b02f.png)

No CSS associated, so the default system font should be used.

![screenshot_20180124-201931](https://user-images.githubusercontent.com/22564375/35353396-599027f8-0147-11e8-883c-6016421fde44.png)

Displayed wrong due to different font.

### Expected
The default system font should be used everywhere.

**Comment by mikehardy** [comment]
Interesting - this is the second font issue in a couple days (see also #4774) - could you specify exactly what font is your system font (the expected result) and what font you are seeing instead (if you know it)? I can see the difference visually I think but I want to be sure. Alternatively attaching a test deck with a card that has the problem and one with a font css specified  that shows it correctly could help.

**Comment by ju-w** [comment]
The font that displays the Kanji correctly is the default android system font. It is used everywhere, but I don't know the name. Also I have no idea how the font fallback works internally.
The font that displays the Kanji incorrectly, I don't know, but apparently it's also some other default font.
I'm sorry I don't know the names, so I can't create CSS for it.
However I attached the deck I used to create the screenshots.

[fonttest-jp.zip](https://github.com/ankidroid/Anki-Android/files/1661614/fonttest-jp.zip)

**Comment by mikehardy** [comment]
Thanks - I also dug around a little bit and it looks like "Roboto" is the default android font but it doesn't cover Japanese or Chinese symbols correctly, the "Noto" font is needed then but other people also see the behavior you describe - for example this comment and then the following one with a possible solution https://github.com/podlove/podlove-subscribe-button/issues/110#issuecomment-291902836

Not sure how we solve this here exactly but the problem description seems well done and we have a fair bit of accompanying information in the link above (and the links in that thread)

**Comment by mikehardy** [comment]
A bit more information with some possible workarounds for you - this is apparently called the "Han Unification Problem" and it's been logged for AnkiDroid before, but long ago.

If you are Android 7+, it appears you can Japanese to your language list and it will work correctly, if you are Android 6 or lower, you can root and install "KanjiFix", or failing either of those you can change your system default to Japanese and it will work also I think. And of course you can install the font in your Anki media and reference it in the cards as a 4th fallback.

I'm not sure there is much else AnkiDroid the application can do but others handled this before when bug reporting was on a different platform https://groups.google.com/forum/#!topic/anki-android/bgV7eVhPZUA

**Comment by ju-w** [comment]
The issue is that it appears to be working **everywhere**, _except_ Anki WebView. Same effect here: #4774 Correct in the EditView - wrong in the WebView.

The links you mention are heavily outdated and don't represent the state of Android anymore.

Actually there are 2 possibilities:

1.  Android.WebView is bugged and doesn't use the correct fallback font.
This could be tested by creating a simple WebView app that does nothing but display the Characters in in question. If it fails here, it is an Android bug and we can't fix it, only find a workaround.

2.  AnkiDroid is somewhere adding a custom CSS or forcing a different fallback font.
If 1. proofs to be working correctly, this **has** be the logical consequence.
I was looking through the code and found this line:
`content = SmpToHtmlEntity(content);`
Maybe this might be an issue? I will try some testing when I find the time for it.

**Comment by ju-w** [comment]
Ok, so I verified it and it is indeed an issue with WebView and not with Anki itself.


## Here is what I did.

I created an [app](https://github.com/ju-w/WebVeiwMin/) that fetches this html https://www.w3.org/People/D%C3%BCrst/SFC/2004/0418Hagino.html and displays it in a WebView.

### The browser uses the correct font

![screenshot_20180126-002058](https://user-images.githubusercontent.com/22564375/35417990-2fe07ce8-0230-11e8-96b9-be387a017e3c.png)


### But the WebView does not

![screenshot_20180126-002013](https://user-images.githubusercontent.com/22564375/35418001-394f70e0-0230-11e8-8d2d-92395071c883.png)


## Setting Phone to Japanese

However, when I set the phone to Japanese, the WebView will also use the desired font:
![screenshot_20180126-002535](https://user-images.githubusercontent.com/22564375/35418080-8d592d48-0230-11e8-92bd-fbdf3ef25309.png)
![screenshot_20180126-002607](https://user-images.githubusercontent.com/22564375/35418081-8f5d018c-0230-11e8-9fc3-57e7336ee350.png)


This is an annoying issue, but apparently nothing we can do against it.

WebVeiw also ignores `lang="jp"` in the html

Tested from Android 7.1.2

**Comment by mikehardy** [comment]
Shame there is no easy fix, but fantastic troubleshooting

**Comment by ju-w** [comment]
Actually, WebView does respect the `lang="ja"` Tag (not ~~"jp"~~).

When I load this html into WebView:

```
<html>
<style>
</style>
<body>This is my <b>Html</b> öäü.
<div lang="en"> Some japanese 泡浅い褐 lang="en"<div />
<div lang="ja"> Some japanese 泡浅い褐 lang="ja"<div />
<div lang="zh-Hans"> Some japanese 泡浅い褐 lang="zh-Hans"<div />
</body>
</html>
```

It dispays it correctly:

![screenshot_20180126-173056](https://user-images.githubusercontent.com/22564375/35450255-bb7bd0ec-02bf-11e8-8b3d-30a8d632c73c.png)



However, Anki does not respect it.

![screenshot_20180126-173144](https://user-images.githubusercontent.com/22564375/35450287-d5289e9e-02bf-11e8-8eb3-9e5ad8beb715.png)
![screenshot_20180126-173205](https://user-images.githubusercontent.com/22564375/35450290-d876e178-02bf-11e8-8038-e9bf6d41bdbc.png)


This is a bug in Anki itself that should be fixed.

**Comment by ju-w** [comment]
Ok, I don't know what I did wrong 2 days ago, but wrapping everything with a `<span lang="ja">...</span>` actually does works flawlessly.
All good here now.

**Comment by Anthropos888** [comment]
I just would like to suggest that the described workaround with the lang="ja" tag should be added to the manual. Since Ankidroid uses Googles default font (which still shows Chinese instead of Japanese characters) all users who learn Kanji on Ankidroid will see wrong characters! (As for me, I'm glad that I just found this entry here, which solved this problem)

**Comment by mikehardy** [comment]
@Anthropos888 you are correct, also this may help people that are using web fonts for Japanese (possibly because of this?) and experiencing slow performance #4856 

It appears you can quickly generate an edit to 'manual.asc' (the file that renders to the manual) and request a review+merge of your changes using the pencil / edit button here: https://github.com/ankidroid/ankidroiddocs/blob/master/manual.asc

**Comment by Anthropos888** [comment]
In case users have a complex note template, this JavaScript would effect the whole card, not just a single div or span:

document.getElementsByTagName('html')[0].setAttribute('lang', 'ja');

The appearance of English text will not be influenced by this, so I think it's safe to use it for the whole card. 
When I have time I can send a suggestion for the manual via your link

**Comment by nakari123** [comment]
Please also check if you've installed the system language Japanese.
This works. System languages:
---
1. English
2. Japanese
---
This will causes error:
1. English
2. Chinese
3. Japanese
--
The order of system languages matter.
