### ISSUE TITLE
Enhancement - Android Auto support

### ISSUE THREAD

**Issue by baparham** [ankidroid/Anki-Android#4779]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X ] I have searched for similar existing issues here and on the user forum

Have any of the contributors looked into what it would take to get android auto support into this app? It seems like there would be a solid use case for people who want to use this in the car during their commute, though I am not sure if there would be a good, reliable way to use it without being distracted or it being cumbersome.

Could it be possible to only allow audio focused flashcards without text, and you could use the next track and previous track buttons usually on the steering wheel to indicate "good" or "bad"?

Is there a vetting process that Google has to deem an app supported on Android Auto? Given the small list of apps that are in that supported list, this may be a hard sell to google, since I'm sure they want safety and distraction free driving to be the priority.

Just throwing this out there to see if anyone has given this some thought or looked into it in any more detail.

Thanks!

**Comment by baparham** [comment]
I just read up on the quality guidelines here: https://developer.android.com/develop/quality-guidelines/auto-app-quality.html and it seems that this violates many of the "don't display video or images" rules that the app must follow to be approved for use in auto.

Looks like there is a vetting process and you must submit your app to google for android auto approval (makes sense).

Perhaps this is a non-starter then. :-(

**Comment by paulokow** [comment]
After dealing a bit with Android Auto I had a similar idea for use of AnkiDroid.

Use case that would work and does not seem to violate any of the Google's rules:
- only audio-oriented decks (either with audio elements or with text-to-speech activated)
- steering with Previous/Next track or with speech control (not sure if it can work however)

Anywan +1 for this idea.
