### ISSUE TITLE
Cards scheduled to the past after review

### ISSUE THREAD

**Issue by jmaatta** [ankidroid/Anki-Android#4780]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

May be related to cards with missing history, possibly created by an import plugin.

###### Expected Result

After reviewing a card, its next review is scheduled to be in the future, not in the past.

###### Actual Result

I just noticed that some of my old cards were getting next review timestamps that were in the past. Now, some of these cards have been imported (with some scheduling and difficulty data) to Anki from an old SuperMemo deck and they lack review history. Still, I have never noticed this behavior in the Anki desktop app which I have used extensively for years (also for reviewing these old items with long, multi-year intervals). The buggy cards started appearing only after I decided to give AnkiDroid a try.

What seems to have happened is:
1. An old card with no review history in Anki gets a rep in AnkiDroid. (The card may have been many months overdue.)
2. I give it a good grade and expect to see the card again after a decade or so.
3. The card reappears within the same day as I'm working through my couple of hundred of overdue reviews.
4. I get a funny feeling of déjà-vu, _or_ I finally realize something is wrong.

###### Debug info

I do not provide debug info because when I realized that this was happening, I immediately deleted AnkiDroid to prevent further corruption to my deck. I was using the version from Google Play store and I have auto-updates turned on.

However, I have attached an exported deck which contains two sample cards from my deck. One I reviewed once today and then saw it reappear, with my today's review included in its history and its due date in 2015. Another is due and has no history and I'm pretty sure would show the same behavior (but I didn't try).

[samples.zip](https://github.com/ankidroid/Anki-Android/files/1692210/samples.zip)

**Comment by jmaatta** [comment]
Looks like issue #4716 describes somewhat related behavior.

**Comment by timrae** [comment]
So no reproduction steps?

**Comment by jmaatta** [comment]
I now attempted to reproduce using the sample deck I provided, but (to my surprise) I didn't succeed.

I will consider using AnkiDroid for a couple of days in the near future, taking a backup of my collection beforehand and paying close attention to when the bug occurs so that the specific conditions could be pinpointed. But this would be a bit of a deviation from my usual workflow, so no promises yet.

**Comment by smallid** [comment]
I'm also experiencing this issue and unfortunately don't have much concrete to add as reproducing it has proven elusive. I've seen this behavior 2-3 times in the past month while reviewing the Spanish 5000 vocab deck ([link](https://ankiweb.net/shared/info/241428882)). Each time I saw a few cards which I had marked as 'GOOD' come back during the same review session, behaving as if I had selected 'AGAIN'.

**Comment by timrae** [comment]
This is how I'd approach the problem:

1) At the start of each study session, make a backup of your `collection.anki2` file
1) Start recording a video of your study session
1) Work through your study session until the problem occurs
1) Stop the video, make another copy of your `collection.anki2`
1) Go through the video and confirm that the problem really was reproduced (in particular please confirm that it was really was the same card and not just a sibling, and that you really did mark it as "good")
1) Send us the video as well as the before and after `collection.anki2` files

Honestly, I feel like I have seen this problem before as well, but have also never been able to reproduce or even be sure that I wasn't just confused over a sibling card.
