### ISSUE TITLE
[Update support request] CSS grid layout compatibility

### ISSUE THREAD

**Issue by macvalino** [ankidroid/Anki-Android#4784]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Made personal CSS stylesheet using CSS grid layout to enhance card layout.
2. The layout is working fine on common android browsers(Firefox, Chrome, Opera)
3. It's not working on Ankidroid. :(

###### Expected Result

Layout flashcards with CSS grid function.

###### Actual Result

Didn't make any changes on the display layout at all, like there is no display value.(should be in columns like on browser)
![screenshot_20180206-065504](https://user-images.githubusercontent.com/36174896/35833116-c5eedf26-0b0a-11e8-987d-312f9f7d34d1.png)
![screenshot_20180206-064433](https://user-images.githubusercontent.com/36174896/35832799-827256d4-0b09-11e8-8cd8-60c9de50a04c.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.3
Android Version = 6.0.1
ACRA UUID = 0d9ba0f0-e304-4c82-aeb5-9d9883e49722

**Comment by macvalino** [comment]
UPDATED: I somehow managed customizing my deck to the design I intended  using mostly CSS flex instead. That being said, I still can't make 'grid' work. You may have this closed, and consider adding it on future updates.

![screenshot_20180206-123305](https://user-images.githubusercontent.com/36174896/35842029-aff33b10-0b3a-11e8-99b7-d78016c8eeb4.png)

**Comment by Wiileewaller** [comment]
I tried to align my 'boxes' with
#blabla{
display: flex}

but it doesn't seem to work, do you have the same issue?

**Comment by boydkelly** [comment]
Would love to see css grid support.

**Comment by mikehardy** [comment]
Find the plugins issue in our tracker and follow the link to a 3rd party reviewer project. Might be what you want

**Comment by mikehardy** [comment]
If you do a local build of AnkiDroid, development builds have a feature now where every time they display the card, they output the exact HTML that is fed to the WebView. They also enable remote WebView debugging so if you are (for example) running the development build in an emulator on a desktop (the most typical way to develop I believe), you can use your desktop chrome to connect to the webview on Android and see the running component hierarchy on the device - documented here: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection
