### ISSUE TITLE
[Improvement] Do not close keyboard on saving a note

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#4788]
###### Research
*Enter an [ x ] character to confirm the points below:*
[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[ x ] I have searched for similar existing issues here and on the user forum

Adding notes consequently is not very convenient: the keyboard closes after each one, and you have to tap the input field twice to evoke the keyboard back
###### Reproduction Steps

1. Open add note
2. Type something
3. Hit the checmark in the upper right corner

###### Expected Result
Leave the keyboard on screen

###### Actual Result
Keyboard closes

**Comment by david-allison-1** [comment]
Good first issue. Will need to ensure that it's still reproducible

**Comment by homocomputeris** [comment]
The keyboard still closes in
AnkiDroid Version = 2.11alpha5

Android Version = 9

ACRA UUID = 00241c4a-0bec-48ae-ad7b-3b256d478e8f

**Comment by david-allison-1** [comment]
Thanks!!
