### ISSUE TITLE
Apply changes for several cards at the same time

### ISSUE THREAD

**Issue by AymaneHrouch** [ankidroid/Anki-Android#4791]
Hello, i really love this app, it's the most useful app in my phone, thanks to everyone that participate in code it.. I just hope that someone can develop one thing : selecting. Sometimes I register many cards in the wrong deck, so when I recognize the mistake and want to move it to the right deck i have to do it manually, for each one separately, that's very fatiguing. adding the ability of select many cards and apply something on them at the same time (moving, changing the tag, removing) will be really great.

Thanks.

**Comment by mikehardy** [comment]
Sorry for the late response! There is some excellent work in this direction from @vrublack that may finish up soon, in the form of #4839 

it already works for me when I test it, it seems to be at the stage of passing code reviews before it can be merged into the app for the next release

**Comment by mikehardy** [comment]
This is merged and available in the alphas now, will be in 2.9 shortly
