### ISSUE TITLE
Corrupt collection that the official restoring method failed to work

### ISSUE THREAD

**Issue by MLRmarvin** [ankidroid/Anki-Android#4796]
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

I'm sorry, this is not a problem specific to AnkiDroid but I had no other solution after two days' futile efforts. If it's against forum rules please just delete this thread. 
The corrupt collection file can be downloaded here: https://drive.google.com/open?id=17z0LhiTiH0_D2aicCv-sFzxc28JazIUI

###### Reproduction Steps

1. Computer crashed while Anki was open;
2. On starting Anki, it reported corrupt collection;
3. Followed the official method for repairing with sqlite3 but dumped txt file had only 3 lines in it.

###### Expected Result
Dumped txt file of a size similar to the collection file.

###### Actual Result
Dumped txt file extremely small and with only 3 lines in it.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
![anki error message](https://user-images.githubusercontent.com/36896472/36745855-bbdc62d0-1be8-11e8-8b46-13af5fe72f05.PNG)

**Comment by timrae** [comment]
Hi, sorry for the late reply.
As this is not related to AnkiDroid, please direct your enquiry to the [main Anki support site](https://anki.tenderapp.com/) if you haven't already solved it.
