### ISSUE TITLE
Two issues with whiteboard - can't click "hints"/"summary" drop downs, and studying from top-level decks doesn't remember sub-deck settings

### ISSUE THREAD

**Issue by mimi-min** [ankidroid/Anki-Android#4800]
Whoops, hit enter and it submitted it, one sec...

I love that the whiteboard feature is a thing, though it took me a while to figure out how to use. I guess I have a few enhancements that would make using it feel more intuitive.

First, I have cards that use hints and drop-down information in the form of "summary" tags that I can't use unless I disable whiteboard, which is a bit of an annoyance, especially when I have full screen enabled so that I can scroll on whiteboard enabled cards; swiping down and disabling whiteboard just so I can click one thing then repeating it to enable it is a bit cumbersome. I know someone mentioned it before; it would be really useful to be able to use two fingers to scroll when not in full screen mode, but that's a separate issue. It would be nice if there were some way to get it to ignore whiteboard when tapping "links" or other things that are interactive (summary tags, audio buttons, etc.). Maybe having the whiteboard display "behind" text, or just links/summary tags/audio buttons?

The other thing is that I really only want the whiteboard to function on a certain card type; the deck(s) I'm using are in this type of hierarchy:

Top Level
--- Non-Writing Cards
--------- Sub-deck 1 
--------- Sub-deck 2
--- Writing Cards

I have the "Writing" deck with whiteboard enabled, and the "Non-Writing" deck with it disabled, in hopes that I could get around the lack of scrolling/unhiding issue, but if I just study from "Top Level" it ignores the setting of the sub-decks. Maybe if the whiteboard was a part of the deck options menu and there was an option to "use settings of sub-deck" along with enabled/disabled?

What would be really cool and would help with all of these issues is if there were a specific thing we could put in the cards themselves that acts as a mini-whiteboard, like a {{whiteboard}} tag. Even cooler would be the ability to use something as a background (e.g. {{whiteboard:Stroke Order Diagram}}). I'm sure this stuff is a lot of work, but it's the squeaky wheel that gets the oil, so I figured I should speak up a bit. Thank you for all of your work on Anki and Ankidroid thus far ♡

**Comment by LeopoldKellers** [comment]
Hi,

regarding the first part of your question: I have already implemented that functionality (keep one finger touching the whiteboard, while using the other finger to scroll and click around on your card) some time ago, and it is included in version 2.9alpha15 and higher. However, I don't know how soon the 2.9 release is going to happen, but if you want the feature urgently: i have been using said alpha version daily for many weeks now without any issues (on my decks at least...) : -)

**Comment by david-allison-1** [comment]
Related: #6205. Let's keep this around, not sure I'll have time to get around to it to do it properly, but it'll be useful and I'd like to see it fixed.
