### ISSUE TITLE
Bug: "%" are duplicated in "Deck options"

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#4801]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1.  Long-tap a deck title
2.  Tap "Deck options"
3.  Tap "Reviews" (or "New cards" or "Lapses")

###### Expected Result
(2.9alpha17)
![image](https://user-images.githubusercontent.com/10436072/36941357-6ea1e0aa-1f9c-11e8-9a9b-0c4a23ddf233.png)
###### Actual Result
"%" are duplicated on 2.9alpha18
![image](https://user-images.githubusercontent.com/10436072/36941381-219b0844-1f9d-11e8-81ce-5f56fd1f37c7.png)

###### Debug info
Android: 5.0
AnkiDroid: 2.9alpha18

------------------------------------------------
@mikehardy 
Isn't this issue related to [this change](https://github.com/ankidroid/Anki-Android/commit/4217076d81805834043206db27fefeb9be8cf865)?

**Comment by mikehardy** [comment]
Interesting! Very well could be. Night time here but I'll definitely look at it and see what I can do. Thanks for pointing it out

**Comment by snowtimeglass** [comment]
Thank you, too! Take your time :-)

**Comment by mikehardy** [comment]
I looked at the commit, and that one should be safe - it's downloading the status page into a temp file and then just extracting information from the temp file before deleting it, in other words it shouldn't have anything to do with the actual translations. This is probably in the python script somewhere, and I'll still take a look later unless there is a python master around...

**Comment by timrae** [comment]
Looking at the commit history, it must be caused by 3e786971111e62e75afa7b34db1233d6d77752c7
To take a guess, I'd say it's most likely a framework bug in `AppCompatPreferenceActivity`

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/DeckOptions.java#L77

Now that we've bumped the min sdk to Jellybean, we probably don't actually need to use that class anymore. It's been a while since I looked at that DeckOptions code, but it's been due for a re-write for a long time now.

**Comment by mikehardy** [comment]
I reverted that commit piece by piece, first the libraries and compileSdk down to 25.x and the behavior didn't revert until the buildTools was reverted - this line alone https://github.com/ankidroid/Anki-Android/commit/3e786971111e62e75afa7b34db1233d6d77752c7#diff-354f30a63fb0907d4ad57269548329e3L12

Something about the XML parsing in buildTools 25 -> 26 is actually at fault.

**Comment by mikehardy** [comment]
I have this isolated to *just* the gradle plugin update from 2.3.3 to 3.0.1. Even taking gradle itself all the way to 4.7-all doesn't matter. But that one line triggers the %-escaping problem. Still investigating.
