### ISSUE TITLE
review by tag doesn't add new cards with same tag

### ISSUE THREAD

**Issue by Ana06** [ankidroid/Anki-Android#4802]
When creating a deck from an existing one, selecting the _by tag_ option, it would be nice if when adding a new card with this tag, it was also added to the deck. If I am not wrong, currently the number of cards in this deck is never increased.

I think it is not possible to configure this at the moment, if not please let me know how. :wink:

**Comment by timrae** [comment]
I don't really understand... Can you please create a new issue following the template? (steps to reproduce, expected behavior vs actual behavior, etc)
