### ISSUE TITLE
Update Polish translation

### ISSUE THREAD

**Issue by pkubowicz** [ankidroid/Anki-Android#4803]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Open the main screen of AnkiDroid
2. Polish translations for `studied_cards_today` and `deckpicker_title` are obviously wrong (the author did not understand that the second format string is about minutes left)

###### Expected Result

I have submitted a few better translations to [Crowdin](https://crowdin.com/translate/ankidroid/7290/en-pl)

###### Actual Result
[src/main/res/values-pl/01-core.xml](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/res/values-pl/01-core.xml) is 8 months old and does not include translation fixes.

###### Debug info
AnkiDroid 2.8.3

**Comment by mikehardy** [comment]
@timrae I see these updated translations in the Polish file, and I can also help with Spanish as well as perhaps English (though for English it's probably just making sure there are no omissions etc). 
I read the [translation help page](https://github.com/ankidroid/Anki-Android/wiki/Contributing#translate-ankidroid) but I don't see anything on the release page that describes how to pull translations into the app source code other than update-localizations.py and I don't know how to push new files that should be translated (i.e. after the changes related to moving to API >= 15 out to crowdin). If that stuff was documented (or you gave some barebones bullet points I could flesh out as new docs for approval) I could work on pushing the new files out, translating on crowdin where possible and pulling them back in...

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#handling-translations
