### ISSUE TITLE
[enhancement] Allowing to sort reviews by card

### ISSUE THREAD

**Issue by Ekleog** [ankidroid/Anki-Android#4805]
I have a deck of Japanese with cards Kanji → Meaning, Kanji → Reading, Meaning → Reading and Meaning → Kanji. I've noticed I reviewed new cards (not in random order) much much faster than I do review cards.

I think one of the reasons is that new cards are (by the burying mechanism) almost always sorted by card type: first the Meaning → Reading cards, then the Kanji → Reading cards, etc. This causes less “context switches”, and the brain concentrates more on the vocabulary and less on “on what language is it? what was the answer I am expected to give?”

So I was thinking it may be a good idea to be able to sort review cards based on card type, grouping cards of the same type in the reviews.

What do you think about it?

(I'll open the same issue on anki-desktop's repo based on the outcome of this discussion, as I'm mostly using ankidroid for reviews)

**Comment by timrae** [comment]
Hi, sorry for the delay, in principle this change would only be requested if it were accepted upstream in Anki Desktop. Please reopen the issue if it does get implemented there.

**Comment by Ekleog** [comment]
OK thanks, will do!
