### ISSUE TITLE
Mixed foreign and English interface

### ISSUE THREAD

**Issue by tskzooms** [ankidroid/Anki-Android#4810]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Ankidroid language changed from default to English
2. Phone language switched to Mandarin Chinese (simplified characters)
3. Restarted phone

###### Expected Result

App interface completely in English

###### Actual Result

Some terms in English, some in Chinese.
For example, card feedback buttons are "again" in red, "困难“ in gray, "一般“ in green, and "easy" in blue.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.8.3

Android Version = 7.1.1

ACRA UUID = abfea427-552e-4ba8-8fd3-8489d26bcda4

**Comment by mikehardy** [comment]
Hi there! I have seen this also, it really does make a mess of trying to use a non-system language within AnkiDroid. I think this is already being tracked in Issue #4729 

I think everything you mentioned here is already noted - if you agree, this should be closed as a duplicate so we can keep track of everything related to the issue in one spot

**Comment by tskzooms** [comment]
Thanks, you're right.

**Comment by mikehardy** [comment]
Except for the part where it isn't working (!), great ;-)
