### ISSUE TITLE
Takoboto cannot send lists to Ankidroid

### ISSUE THREAD

**Issue by Kookosmile** [ankidroid/Anki-Android#4824]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Enable API on Ankidroid
2. Open a custom list in Takoboto (Japanese dictionary app)
3. Choose the "send to AnkiDroid" in the three-dots-menu. 

###### Expected Result
The custom list is automatically added to Ankidroid.

###### Actual Result
Error "Permission Denied"
The custom list is not added to AnkiDroid

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.9alpha19

Android Version = 8.1.0

ACRA UUID = d2a7bdc4-55eb-4a2a-a337-624f6f7c1be3

**Comment by tobia** [comment]
Solved it by reinstalling Takoboto *after* AnkiDroid, so that it can request the permission at install time.

![screenshot_20180805-153317__01_606x1280](https://user-images.githubusercontent.com/48756/43683415-28b570e0-98c6-11e8-8bba-51786fddbca5.jpg)

**Comment by timrae** [comment]
That's not supposed to be necessary... on stock Android 6+ permissions are
requested at run time not install time

**Comment by tobia** [comment]
I'm on Android 8.1.0 (OnePlus OxygenOS 5.1.9) and it was needed.

At run time I would get no permission request at all. If I tried to manually assign the permission in the system settings, the slider would turn back to gray as soon as I left they page.

**Comment by mikehardy** [comment]
Hi there - not saying this isn't an issue, but it's an issue outside our control. I looked for reference documentation and there's nothing else we can do other than declare the permissions available from our app. It is good that this is documented in our tracker though so we can refer others to it if needed, and hopefully the takoboto folks can document it there as well
