### ISSUE TITLE
Crash upon completing sync

### ISSUE THREAD

**Issue by Schmoulax** [ankidroid/Anki-Android#4826]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Launch Ankidroid
2. Automatic sync starts
3. Anki crashes upon completing sync

###### Expected Result
Anki launches as expected

###### Actual Result
Anki crashes after completing sync. Sync is still complete even if the app crashes. Can relaunch and use Anki as expected after the sync crash. Trying to sync again if changes were made crashes the app again upon completing sync.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.3

Android Version = 7.1.1

ACRA UUID = 63277d0d-52a7-4184-acc9-eab86b83de28

**Comment by mikehardy** [comment]
Hi there! A couple of recent crash bugs have been resolved with current code, have you tried the most recent alphas? If you can still reproduce this crash with the most recent alpha I'll need @timrae 's help to view the crash dump and see where the code failed.

Normally I'd hesitate to recommend an alpha build over a stable one but I've personally used all the most recent alphas daily for months and they've fixed issues without creating new ones - hopefully it's the same for you - https://github.com/ankidroid/Anki-Android/releases

Please give it a try and I'm curious to hear the result

**Comment by Schmoulax** [comment]
Thank you for your prompt answer. I have just tried the latest alpha build and it works!
I only used Anki for 5 minutes so I don't know if this build will bring new issues, but the crash after sync problem is solved. 

Thanks again and have a nice day!
