### ISSUE TITLE
UX: Hard to replay audio cards with one hand

### ISSUE THREAD

**Issue by shiftee** [ankidroid/Anki-Android#4830]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

Hi,

I use flash cards with audio where the user speaks in French and I may need to replay the audio multiple times in order to understand what was said.

The button to replay the audio is at the top of the screen which is awkward to reach with my thumb, unlike the "Show Answer" and difficulty rating buttons.

Is it possible to move it down to the middle or ideally the bottom of the screen?

Thanks

**Comment by timrae** [comment]
We offer two options for audio playback: from the action bar in line with
Android design guidelines, or embedded in the card itself. In the later
case you can position the audio field wherever you like it.

**Comment by snowtimeglass** [comment]
How about assigning the gesture of "Touch bottom" to the action of "Play media"? :-)

**Comment by shiftee** [comment]
I assigned it to "Double Touch". I'm new to Anki and didn't realise you could do this, thanks a lot.
