### ISSUE TITLE
Support for Adaptive Icon

### ISSUE THREAD

**Issue by lokesh-krishna** [ankidroid/Anki-Android#4831]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

API 26 introduced adaptive launcher icons. Would be really nice to see AnkiDroid support it.

**Comment by timrae** [comment]
See #4797 and #4798

**Comment by lokesh-krishna** [comment]
Is there anything stalling the merging of either one of those?  

They seem to have been around for a while.

**Comment by timrae** [comment]
Mainly just testing and user feedback... You could help out by trying them both out and commenting, posting screenshots, etc

**Comment by timrae** [comment]
@cydia2020 @lokesh-krishna 
I posted some screenshots on those two PRs. I think we can do better tbh.
If someone wants to try, then please go ahead and post a screenshot here.

**Comment by mikehardy** [comment]
We have 3 that "should work" and the simple one at minimum is essentially just adding technical adaptive support to the current icon. Let's get this done for 2.9 with at least a merge of the simple one if we can't reach consensus on an aesthetic change. I say that to motivate because this should be almost trivial as a technical thing

**Comment by mikehardy** [comment]
Posting this link from the duplicate #4989 - it has the technical information for integrating in the manifest etc https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive

**Comment by adamwolf** [comment]
Should be fixed as of https://github.com/ankidroid/Anki-Android/pull/5441, and should be in betas soon.
