### ISSUE TITLE
[Improvement] Iterate over cards with latex errors

### ISSUE THREAD

**Issue by Rubenmp** [ankidroid/Anki-Android#4836]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

When I write latex fast sometimes I have mistakes, currently I magage it using the 'Preview' of all cards 'Added today'. It could be awesome to search for latex errors inside a given deck without seeing the preview of all its cards.

Once latex errors are identified (#4597) there could be a way to look for them on the Browser.

###### Reproduction Steps
1. Browse cards
2. Search for 'deck:current latex:error' (or any deck)

If there is another expression which is more elegant is welcome.

###### Expected Result
Show cards in current deck with latex errors

###### Actual Result
Nothing

**Comment by mikehardy** [comment]
If any proposed PR to #4597 is written as a method that takes a card and returns whether it is a latex error or not, then a proposed solution here could re-use that as a virtual / searchable tag on card browser I suppose
