### ISSUE TITLE
Heavy check mark and Downarrow

### ISSUE THREAD

**Issue by Alyxvance** [ankidroid/Anki-Android#4841]
Can you make the check mark and arrow configurable?
https://github.com/ankidroid/Anki-Android/blob/2b0ef9ccf032eca1413d3ea958e6d8c5192bfd34/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L767
like 
`                sb.append("<span class=\"checkmark\">\u2714</span>"); // Heavy check mark`

and this 
https://github.com/ankidroid/Anki-Android/blob/2b0ef9ccf032eca1413d3ea958e6d8c5192bfd34/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L775
like 
`                sb.append("<br><span class=\"darr\">&darr;<br></span>");`

greetings

Edit 
Maybe the same vor the desktop to? https://github.com/dae/anki/blob/478d244a4f4bdd68dd25f29b4600ca7ae6bbb313/aqt/reviewer.py#L433

**Comment by mikehardy** [comment]
I'm not sure but it looks like since they have CSS classes you could probably modify that with CSS in the card template editor. Have you tried styling there to see if you get the results you desire? If upstream doesn't do it, AnkiDroid usually won't do it, unfortunately so that is the only customization option at the moment

**Comment by Alyxvance** [comment]
hm okay i ask again how should i style this without any class tags around the chekmark an darrow? 
sorry if its late caus i have used my solong my own compiled version but now i have a new issue and locked around the new version an i cant style it

**Comment by mikehardy** [comment]
This is a great question for the mailing list - there are some very heavy customizers there that frequently offer advice on how to tweak templates to do exactly what you want

**Comment by Alyxvance** [comment]
i have seen in the ankidesktp thats is implementet in the actual beta 
so i have it adaptet to the actual 2.9alfa54 on my own
in line 
`733         sb.append("<span id=\"typecheckmark\">\u2714</span>");`
`741         sb.append("<br><span id=\"typearrow\">&darr;</span><br>");` 
so its 741 in ankidesktop 2.1.24 beta 2 Version 2.1.24 (b1a8107a)

so the next question is why this? you could make one line or not ;)
`723        sb.append("<div");`
`724        sb.append("><code id=typeans>");`

**Comment by mikehardy** [comment]
Propose a pull request if you would like to see a change, then we can consider it
