### ISSUE TITLE
New russian translation file breaks build (03-dialogs.xml::import_media_count has bad format string)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4848]
The most recent crowdin translation download breaks the build I think? (I think, because I'm playing with buildTools 25 vs 26 for Issue #4801 and this showed up when I went down to buildTools 25)

Specifically this translation didn't include the format string correctly:

https://crowdin.com/translate/ankidroid/7303/en-ru#6533382

Using the crowdin tools (suggesting a new translation, and sending a notification to the approver) I have suggested a fix.

I have verified via text inspection that this format string was unique - in that no one else translated it that way, and only this file did:

```

<Ibiza>~/work/AnkiDroid/Anki-Android/AnkiDroid/src/main/res % grep -r '$d%' *|grep -v '$d%%'
values-ru/03-dialogs.xml:  <string name="import_media_count">Импортируются медиафайлы %1$d%&#8230;</string>
<Ibiza>~/work/AnkiDroid/Anki-Android/AnkiDroid/src/main/res % 

```

**Comment by timrae** [comment]
Approved the translation, gave you proof reader rights so you don't have to wait for me in the future, and pulled the new translations.

**Comment by mikehardy** [comment]
Great - thank you. Just FYI my mind can't help connecting this "one percent sign worked for buildtools >= 26 / two percent signs are needed for buildtools == 25" in combination with "two percent signs are showing up in the UI with buildtools >= 26" and I'm currently investigating this for Issue #4801 - may be that we need to remove double percent signs from everything (and revert this change) though I hope not
