### ISSUE TITLE
[sugestion] stop vibrating to notify pending cards while the app is still opened

### ISSUE THREAD

**Issue by 365714** [ankidroid/Anki-Android#4852]
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by david-allison-1** [comment]
I had a look at this, and it's not easily possible on newer versions of Android.

> After you create a notification channel, you cannot change the notification behaviors—the user has complete control at that point. Though you can still change a channel's name and description.

https://developer.android.com/training/notify-user/channels

We could theoretically add in an "in-app" channel and use this
