### ISSUE TITLE
aldonu Esperanton

### ISSUE THREAD

**Issue by verdulo** [ankidroid/Anki-Android#4853]
[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[ x ] I have searched for similar existing issues here and on the user forum

Bonvolu aldonu lingvon Esperanto al Crowdin, do mi povu esperantigi fasadon de la ap(likaĵ)o. Mi antaŭe sendis petojn al Houssam Salem kaj al uzanto "AnkiDroid", sed ne ricevis respondojn.

**Comment by timrae** [comment]
If the language isn't on crowdin then it probably means it's not supported by the crowdin platform. As far as I know, we don't have any control over that.

**Comment by timrae** [comment]
Ah right, I took a look around Crowdin settings and figured out how to add new languages. It should be there now. Please open a new issue here on github on completion of translation to request us to include the translation in the main app.

**Comment by verdulo** [comment]
I translated 2 most important resources ("core" and "strings"), I will soon slowly translate the rest. Please add it to alpha version of the application, so I could test how it looks.

**Comment by timrae** [comment]
I've added your translations, but haven't been able to test due to #4888

**Comment by verdulo** [comment]
It is not electable, maybe you also should add "eo" to the file https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/utils/LanguageUtil.java

**Comment by timrae** [comment]
I can add it there but that feature is broken anyway (see #4729). The only way to test is to change the system language in Android to Esperanto.

**Comment by verdulo** [comment]
I know it's buggy feature, but I have Android 6 and it should (partially work). When I installed the program [Preferences Manager](https://f-droid.org/en/packages/fr.simon.marquis.preferencesmanager) and changed the value "language" to "eo", the parts of application which I translated seems to be displayed correctly, excluding the language option which shows "XXX".
