### ISSUE TITLE
Outdated API at jcenter.bintray.com have issues detecting duplicates. Please update with current version

### ISSUE THREAD

**Issue by xelloss1012** [ankidroid/Anki-Android#4857]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

Hello!,

I'm new on Android development. I'm trying to use the AnkiDroid API in a personal project based on the sample provided at:

https://github.com/ankidroid/apisample

The API is working fine except for the findDuplicateNotes function. I'm trying to detect all duplicates I have stored in a file but it is not detecting all the duplicates. In a list of 2000 cards, it finds approximately 1100 duplicates (the remaining 900 are not detected even if they are already in the deck).

I have been trying to debug my project (based on the sample) and debugging also the Anki-Android APP, and as far as I have been able to understand, the problem seems related to a hashcode calculation that was already solved in this commit:

https://github.com/ankidroid/Anki-Android/commit/269fd178e09e9c43a8f2066c63d65802c6f6c156

In fact, I have seen the source code of the latest version of the API that I'm referencing: 

https://jcenter.bintray.com/com/ichi2/anki/api/1.1.0alpha5/

And I see that the affected files are not updated... 

I think that publishing the current version of the API should solve the problem

¿Can you please update the published API? 

In case it is not possible, ¿Could you suggest any workaround to use the latest version of the API in my project or how to point to the git version in the gradle file? (I have been trying to build the current version of the API to a JAR in my machine and then reference it in my project, but by the moment I was unable to make it work... I think I need to understand better the dependencies and build system in order to do this.. :))

###### Expected Result

When searching a duplicated card the key "熊, くま" (for example) it should find 1 result in my deck (since I have already added this card)

###### Actual Result

The card is not detected as duplicated and I can add it over and over again

###### Debug info

AnkiDroid Version = Any (the problem is with the API)
AnkiDroid API Version = 1.1.0alpha5
Android Version = 7.0.0

- Key searched for duplicates: "熊, くま"
- Wrong hashcode obtained by the published 1.1.0alpha5 version of the API: 4081968894
- Right hashcode obtained by the latest version of the AP in github: 255123055 (which seems it should work)

**Comment by mikehardy** [comment]
Interesting - this is a great bug report.

In a local branch, I have updated the API area of the source code to compile cleanly with modern tools (currently unmerged pull request )

I have generated an <b>UNSUPPORTED</b> test release of the same which you [may find here](https://github.com/mikehardy/Anki-Android/releases/tag/v1.0.1alpha6) (and yes, I got the tag wrong - should have been 1.1.0alpha6 - it's a test, forgive me)

You can download and use that local library during builds in place of the upstream one by updating your gradle dependency to 1.1.0alpha6 after installing the test release in your local repository (whose location was shown to me when I attempted a "./gradlew build" on the command line from the API sample project root directory)

My local install, which allowed the api sample to build, looked like this (pardon the bad formatting):

<code>
<Ibiza>~/Users/mike % cd /Users/mike/Library/Android/sdk/extras/
<Ibiza>~/Library/Android/sdk/extras % mkdir m2repository
<Ibiza>~/Library/Android/sdk/extras % cd m2repository/
<Ibiza>~/Library/Android/sdk/extras/m2repository % unzip /Users/mike/Desktop/release-1.1.0alpha6.zip 
</code>


Hope this helps?

@timrae I think this would have been just a standard publish of a new API alpha except for the new Java8 javadoc lint stuff

**Comment by xelloss1012** [comment]
Hello!,

Thanks to your comment I managed to understand where to unzip your release zip by using the "gradlew build" command as you suggested. 

I had to disable also the `signingConfig signingConfigs.release` option in the build.gradle, but since it's a personal project I don't care too much :)

It seems this solves my problem :D

Thank you very much!

**Comment by timrae** [comment]
Updated on bintray, sorry for the delay
