### ISSUE TITLE
Make logging work in unit tests (Timber upgrade)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4863]
This is an enhancement request I would implement myself

I'm logging an issue with the idea debate over the idea can happen here and if implemented creating release notes will be easier I think?

The general problem is I'd like to implement unit tests as I work on issues, but logging doesn't work during unit tests with our version of Timber (because android.jar in unit tests is either no-ops or exceptions)

Current Timber versions handle this (I've tested it) but you must subclass Timber differently and it may perturb the log formats

So - 

1- would a Timber upgrade/re-implementation PR be acceptable? 
2- If so, how important are the exact formats of the current logs? Can I start fresh with the general ideas in our current implementation or should I go as far as String comparison between old and new to support some unknown data-mining tooling etc?

**Comment by timrae** [comment]
Yes timber has been in need of upgrading for sometime, please go ahead. Changing log formats is no problem for this project as we don't have any tools that are going through logs with formatting assumptions
