### ISSUE TITLE
Allow TTS language to be set for subdecks

### ISSUE THREAD

**Issue by jhennig3** [ankidroid/Anki-Android#4869]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. I open a card with TTS extension enabled
2. The card is from a deck I have not seen with TTS on yet
3. I have to select the language for the card front and back

###### Expected Result
I expected that I would be able to set that language for all subdecks or not.

###### Actual Result
No option to set for all subdecks.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by ildar** [comment]
Would you please raise the priority for fixing this? That "Choose language" popup blocks using TTS.

Is there a known workaround in the wild?

**Comment by ildar** [comment]
yeah, found it:
https://github.com/ankidroid/Anki-Android/issues/4675#issuecomment-322621916
BTW, this is dup of https://github.com/ankidroid/Anki-Android/issues/4675

**Comment by obennon** [comment]
Has anyone found a workaround? It's particularly excruciating for those like me that use Ankidroid while driving. Gestures are amazing and allow to keep the eyes glued to the road,  but the language selection breaks the "routine"

**Comment by david-allison-1** [comment]
Keeping this open due to user interest.

**Comment by dae** [comment]
Any thoughts on whether the AnkiDroid-specific `<tts>` tags should be kept around long term, or deprecated & eventually removed?

**Comment by david-allison** [comment]
To be removed in https://github.com/ankidroid/Anki-Android/issues/15475

Replaced with `{{tts}}` which would handle this on a per-note-type basis
