### ISSUE TITLE
Improve developer support with project code style conventions shared by default

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4872]
It may be possible (or it may already be partially/mostly implemented) to have code style conventions shared from the project into Android Studio by default

I will look into the current code style settings and how they are shared, and make sure this is operating correctly

Discussion from browser multiselect PR #4839 here: https://github.com/ankidroid/Anki-Android/commit/e3d9d6339af091f0c8c05fb5e0a143a2b8fa5e92#commitcomment-29350498

**Comment by mikehardy** [comment]
@timrae I think this is closable - even if this merge proves to be crappy over time and is reverted, we've tried to be more one step more aggressive and also shown that installing IDEA-Checkstyle + importing the config in docs works which is the current solution, works well, and what we'd revert to

**Comment by timrae** [comment]
I think you can just close it yourself, since you opened it?

**Comment by mikehardy** [comment]
Of course!
