### ISSUE TITLE
can I get all cards throughout mutiple decks?

### ISSUE THREAD

**Issue by KnIfER** [ankidroid/Anki-Android#4878]
I dont know how to customize the search_term in :  
```
DeckTask.launchDeckTask(DeckTask.TASK_TYPE_SEARCH_CARDS, mSearchCardsHandler, new DeckTask.TaskData(
                new Object[] { new HashMap<>(), search_term , ((true)),  0}));
		
```
where  new HashMap<>() seems to be unnecessary?  
I tryed "deck:"name1" deck:"name2"" and "deck:("n1" "n2")" but they seems to be invalid.

**Comment by mikehardy** [comment]
Hi there!

I think you want the browser: https://docs.ankidroid.org/manual.html#browser <https://docs.ankidroid.org/manual.html#browser>

Then info on how to search: https://docs.ankidroid.org/manual.html#_searching <https://docs.ankidroid.org/manual.html#_searching>

note that to change many at once you’ll have to use the desktop for now

Hope this helps, if not respond with a list of all steps and I’ll try again

-Mike

**Comment by KnIfER** [comment]
I am implementing my own card browser.That is,copy codes from ankidroid and manipulate them at my will.
instead of utilizing a drawer and a toolbar, I simply add a ps-like side bar.you can long press on a tool's icon to show more correlative tools.    
currently I can select multiple cards and delete them,or move them to another deck.  
delete :  
![image](https://github.com/KnIfER/tuChuang/raw/master/selectANDdelete.gif)    
move:  
![image](https://github.com/KnIfER/tuChuang/raw/master/selectANDmove.gif)    

I am using Collection...remCards(int[]) to delete cards,and mCard.setDid(did);mCard.flush(); to move cards.

**Comment by mikehardy** [comment]
Fascinating! If you implement this on top of the API you can interact with the main deck synchronization code and not have to worry about that, but make sure to look at the most recent api-sample code (only in github at the moment) to see examples of protecting against the API provider calls failing.

Besides that I think the search terms come from the second Anki manual link above - was that useful?

**Comment by KnIfER** [comment]
Thanks!  I haven't read all of them so far.

**Comment by timrae** [comment]
Just use an empty search query ""

Please use the support forum instead of the issue tracker for questions
