### ISSUE TITLE
I can´t use my sd card as a default media storage

### ISSUE THREAD

**Issue by dilersik** [ankidroid/Anki-Android#4882]
###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Check the full path of any media stored at Sd Card (Samsung S7 Edge); 
2. Create the path at Sd Card;
3. Copy the path to Anki (Advanced Settings);

###### Expected Result
Ok with Anki working at Sd Card;

###### Actual Result
I've tried so hard use my Sd Card as a default media storage for Anki, but I couldn't. (With every possible path, I think)
What I'm doing wrong?
I would use the same Sd Card at my Sony Xperia ZQ, but after change my phone...: "The path specified wasn'n a valid directory!"

Can you help me please?

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by mikehardy** [comment]
You indicated you have read the FAQ, but this is covered there, as well as in the linked issue with instructions. Not officially supported but there are consistent reports of success with the workaround in the issue

https://github.com/ankidroid/Anki-Android/wiki/FAQ#my-ankidroid-files-are-stored-on-a-sd-card-how-can-i-point-ankidroid-to-them

**Comment by dilersik** [comment]
Yes, like I said.. I used to in my old Xperia, but I've had a little hope that anyone could solve in another way. 
Thanks! Sorry bothered you.

**Comment by mikehardy** [comment]
Ah sorry - missed that you had used it before. I'm unaware of anything but the workaround in the linked issue as of yet. It isn't supported but I do hope it works for you

**Comment by timrae** [comment]
Feel free to post on the user forum, GitHub is only for bugs and feature requests. I hope sometime within the next few years we'll support removable storage again, once we have a version with KitKat as the minimum
