### ISSUE TITLE
Basic (and reversed card) not working anymore

### ISSUE THREAD

**Issue by tbop** [ankidroid/Anki-Android#4886]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
The purpose is to create a typical deck in order to learn the vocabulary of a language, for instance German. The recommended card type in the documentation is "Basic (and reversed card)" which should supposedly create 2 cards per vocabulary pair, e.g. English <--> German / German <--> English

1. Create a new deck
2. Add a vocabulary pair with the card type "Basic (and reversed card)"
3. Repeat step 2 several times
4. Test the deck

###### Expected Result
If n entries were added Ankidroid should show the user 2n flash cards.

###### Actual Result
Although it seems that the number of flash cards created in the deck is correct only the "Side A" of a card will be shown, e.g. if the pairs were always inserted with Front: German / Back: English, the user will only be presented with the Front-First version of the card.

I can provide my custom set if needed for debugging.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.8.3

Android Version = 7.0

ACRA UUID = c1817822-44de-4df1-99ee-375cdc140722

**Comment by timrae** [comment]
Hi, card templates are customisable... If your template is broken somehow you can just edit it yourself to fix it. There are videos on how to do this in the introduction section of the Anki desktop manual. It's not a bug in the app.

**Comment by tbop** [comment]
Hi @timrae I am not using any customizable template. I am just using the basic template "Basic (and reversed card)" template that is coming with the app afaik.

**Comment by federvieh** [comment]
Since you said, that the correct number of cards has been created, please check if the reversed cards aren't buried automatically. See here fore details:
https://apps.ankiweb.net/docs/manual.html#siblings

**Comment by timrae** [comment]
Every card template is customisable including the ones that come with the app. Since you didn't give us any screenshots or detailed explanation of what "test the deck" means, we can only guess. Anyway this is not a support forum, and I'm 100% sure the information you need is in the Anki desktop manual.

**Comment by tbop** [comment]
Hi there

@timrae  So I've now logged onto Ankiweb and made my deck [public](https://ankiweb.net/shared/info/10281538). I will also investigate with the webend, perhaps I'll finally find what's corrupted in this deck.

@mikehardy  I do not think that this is a sibling problem as until recently my desk was getting out of new cards and clearly 95% of them seem to have no sibling, I've been adding them very carefully since I discovered this potential bug and always made sure that Basic (and reversed) was selecting when I insert new cards.

**Comment by PolymorphismPrince** [comment]
@tbop Did you close this issue because you solved it? I'm having the same problem even though my templates are fine?

**Comment by tbop** [comment]
@PolymorphismPrince no actually I'm pretty sure there gotta be a bug somewhere. I have this behavior repeatedly but I could not identify the pattern, it's quite erratic.

**Comment by fogbank** [comment]
I can confirm I've got the same bug on an empty deck and a newly-cloned "Basic (and reversed card)" card type. 
Yes, if I add a card, there are two cards in the deck. 
Yes, when I study it, two identical cards are shown.
