### ISSUE TITLE
App crashes on sync

### ISSUE THREAD

**Issue by sortega** [ankidroid/Anki-Android#4890]
###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Try to sync
2. See how it starts downloading changes
3. The app crashes

I was able to sync normally this morning but this evening the app is crashing again and again.

###### Expected Result

The app doesn't crash

###### Actual Result

The app crashes
![00ebf035-8a32-48a0-968b-69c238257f71](https://user-images.githubusercontent.com/259587/42126981-131f29fc-7c91-11e8-9859-217b895d39c6.jpg)

###### Debug info
AnkiDroid Version = 2.8.3
Android Version = 7.1.1
ACRA UUID = c386e42a-bbce-40dd-b347-f33abf790081

**Comment by sortega** [comment]
I think I've found out the cause. I'm experimenting with incremental reading using [this plugin](https://github.com/luoliyan/incremental-reading) and I created a note with a very big chunk of html.
After deleting that note it is syncing again without crashing.

Anyway, looks like a bug to me. In the case of having a note so big that it can't be synced an explanatory error message is preferable to a crash.

**Comment by mikehardy** [comment]
try the alpha releases? may be related to a bug we fixed with db chunk size

**Comment by mikehardy** [comment]
I should mention for completeness - I'd love to know if you try the alpha and it *still* crashes. Crashing is never okay and we'll dig in and find out why if the database chunking fix I mentioned doesn't already handle it. Thanks!

**Comment by sortega** [comment]
@mikehardy, joined the beta program and I confirm it happens in 2.8.4.

Regarding testing an alpha version, I've joined this [google group](https://groups.google.com/forum/#!forum/ankidroidalphatesters) but it's not clear to me what's the next step.

**Comment by timrae** [comment]
You should just start to see alpha versions installed by Google Play like regular updates after joining that group. It might take a day or two for play to update.

**Comment by sortega** [comment]
Sorry for taking so long but I can confirm that it is fixed in the latest alpha.

**Comment by mikehardy** [comment]
Fantastic news, thanks for taking the time to report back
