### ISSUE TITLE
Alert the user that in order to have notifications he needs to add the widget to home screen

### ISSUE THREAD

**Issue by noamraph** [ankidroid/Anki-Android#4898]
I have enabled the "notify me when more than 10 cards are due" option, and haven't received alerts unless I manually opened AnkiDroid. Now, thanks to a google search, I found out that for this to work I have to install the widget. There's no way I could have guessed it, and I don't think you can expect the user to read the entire manual before using the app. I suggest that after the user chose this option, a message box will be displayed saying that in order for this to work it's required to add the widget to the home screen.

Thanks,
Noam

###### Research

*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by mikehardy** [comment]
Hi there - its my experience that the notifications work without the widget, and I know there are some versions where we have notification issues but in most cases they work.

There are some fields in the issue report template that you haven't included, like debug info. Also if you could include your AnkiDroid version and Android version that would help

Thanks!

**Comment by timrae** [comment]
Widget is still required for v2.8.x on the Google Play version. From v2.9 onwards it will no longer be necessary.

**Comment by mikehardy** [comment]
Ahh @timrae  sorry - did not know that. I've been 2.9.x almost exclusively. Could be an enhancement request for a toast as described on 2.8.x IFF (if and only if) it will stay long-lived for API<15
