### ISSUE TITLE
Upgrade sqlite/requery dependency

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4899]
This is an enhancement request, to track some work I was intending to implement it myself as I was auditing all the dependencies and making them current

I got stuck on this one though as it is not possible to move past version 3.16 of requery as they removed the NO_LOCALIZED_COLLATORS database open flag, and we rely on it.

I asked upstream, and they requested I log an official issue, so I did so, and I'm cross-linking here so it's visible to others

https://github.com/requery/sqlite-android/issues/71

**Comment by mikehardy** [comment]
I have an upgrade to 3.23.1 (current until a month ago) working and committed, but 3.24.0 is current now and I have an open question to the requery maintainers on why it doesn't build. Hopefully I can get it working

**Comment by timrae** [comment]
So they've added back the flag that we need?

**Comment by mikehardy** [comment]
I think it's more they assert the don't-localize flag was always a NOP, so their removing it won't affect semantics though obviously it affects type-checkers / compilers

Secondarily, they indicated we were doing the bit logic wrong on the flags and proposed a correction which appeared reasonable. Including that, things built fine, tests pass and it seems fine installed though it was light usage.

In case my interpretation is incorrect, this is the link to the first of the 2 comments from the maintainer: 
https://github.com/requery/sqlite-android/issues/71#issuecomment-413110908

**Comment by mikehardy** [comment]
I'm not sure how to test this to tell you the truth, so I did some more research. If this is too uncomfortable a change and we want to ensure everything works, we should unwrap SQLiteDatabase to just use the platform one, and continue using our flag as is.

Here's the other research I did:

NO_LOCALIZED_COLLATORS has existed since API 1 and used since initial AnkiDroid import into git 9 years ago, there is no code history I could find prior to that so it's likely it's been used since project inception. I can find a few articles on the net from back then that indicate you should always use that flag to open a database so I'm guessing Nicholas just cribbed those notes and went from there.

I can't find anything in the requery source history that indicates it ever depended at build time on anything other than the ndk (not the icu, as the maintainer asserts would be necessary) so if the flag was a NOP without the icu library, then it's a nop, but I don't know either way.

Here's the commit where AnkiDroid went from android-platform SQLite to requery-wrapped SQLite:
https://github.com/mikehardy/Anki-Android/commit/f3ead441a29470cd860df8c812038e0b1309d114

That was while SQLIte was on 3.15.
