### ISSUE TITLE
Adding cards using API is slow

### ISSUE THREAD

**Issue by vi** [ankidroid/Anki-Android#4901]
[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

Import many (e.g. 100) cards using API by [my custom app](https://github.com/vi/AnkiImporter)

###### Expected Result

Cards are imported fast, constant part dominates number-of-cards-dependent part of the time.

###### Actual Result

The import is slow and is slower the more cards being imported.

Maybe it synchronoizes the database (default behaviour of sqlite) after every card added by `addNewNote`?

----

Is it a problem in AnkiDroid or in my program? Does AnkiDroid support opening and committing transactions using the API to speed up the process?

**Comment by timrae** [comment]
There's a separate function for adding multiple notes which is much faster

**Comment by timrae** [comment]
I think it's called `addNewNotes()` or something like that, check again
