### ISSUE TITLE
New SD Card => Not able to find Anki card databases

### ISSUE THREAD

**Issue by modene1** [ankidroid/Anki-Android#4906]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

**I change my SD Card to a larger one and even though the directory is stated correctly as /sdcard/AnkiDroid/ Anki cannot find it**

Phone Huwai Androind P9 - Been working fine for over 5 years (love it) including phone changes. Also was working smoothly until the SD Card was changed.

###### Reproduction Steps

1. New install
2. Crashes on install and reports "Sending report to developers"
3. Manually reopen
4. Only available page (which it jumps to immediately) is preferences. 

###### Expected Result
1. To open as normal so I can review my cards.

###### Actual Result
1. As mentioned above. Crashes.
2. Trying to amend directory
- "AnkiDroid directory is unavailable" message appears.
Returns to Preferences page.

###### Debug info
AnkiDroid Version = 2.8.3

Android Version = 7.0

ACRA UUID = 2f118ebc-4c5e-48b8-979d-349894aa8070

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#my-ankidroid-files-are-stored-on-a-sd-card-how-can-i-point-ankidroid-to-them

**Comment by modene1** [comment]
Awesome. Thanks!

<http://www.efinah.com>
