### ISSUE TITLE
Adding tags to deck/multiple notes

### ISSUE THREAD

**Issue by jalexvig** [ankidroid/Anki-Android#4911]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

Being able to add tags to an entire deck and/or multiple notes simultaneously would be a time saver. I see that @vrublack [is working on multiple note selection](https://github.com/ankidroid/Anki-Android/pull/4839) but I didn't notice anything on adding tags.

**Comment by timrae** [comment]
How do you propose this might be implemented in terms of the GUI?

**Comment by vrublack** [comment]
I think it'd be simple to do this, just add a "add tag" item to the multi-select menu and create a corresponding logic in DeckTask.

**Comment by timrae** [comment]
What about removing tags? I think you'd want to use the tag editor

**Comment by jalexvig** [comment]
@timrae Maybe in the deck options screen?

<img src="https://user-images.githubusercontent.com/12684689/43993660-1e998216-9d5f-11e8-9ec8-e68cf7c51cfb.png" width="40%">

**Comment by timrae** [comment]
Definitely not in the deck options screen, I think it would need to use the tag editor like we do when adding / removing tags in the editor.

**Comment by mrbryce** [comment]
I've been missing a way to tag/untag and export the cards currently filtered in the browser view.
It would look as simple as "tag/untag all" and "export all", since the browser already has search&filtering abilities

**Comment by sudomain** [comment]
My vote is to call the tag editor like @timrae said, but from the drop down menu that appears when long pressing a note in the browser. Maybe right below "Select all"?


![Screenshot_2019-07-31-15-10-32](https://user-images.githubusercontent.com/30786326/62240635-60694c00-b3a5-11e9-91ef-f4877b3e9993.png)

**Comment by sudomain** [comment]
If the project maintainers approve, I'd like to try implementing this in the card browser context menu as shown in my screenshot above.

My initial research shows that this menu is defined in CardBrowserContextMenu.java. In the betas there's already functionality to toggle the 'marked' tag, so maybe I'll reuse code from there and create an instance of the TagsDialog. I'm struggling to find com.ichi2.anki.R which is used by CardBrowserContextMenu.java to toggle the marked tag. Shouldn't it be located in the com/ichi2/anki directory?

**Comment by mikehardy** [comment]
The 'R' symbol is actually dynamically generated at build time, and stands for "Resources", the contents are built from src/main/res XML files

Doing these 'Task' type features is a little involved because it is asynchronous while in my previous additions I've still tried to preserve undo while being aware of memory pressure jus tin case. But there are plenty of patterns to follow, yes - like you see with the DeckTask/MARK_NOTE_MULTI items. They are all pretty much the same so hopefully not too terrible to hack on

@sudomain you're approach in general (call tag editor, from card list menu in multi-select mode) seems like it should work

**Comment by david-allison-1** [comment]
This is requested fairly often, and I'd like to get around to it

**Comment by sudomain** [comment]
There is an [old method in AnkiDroid'snport of libanki that would theoretically handle bulk adding of tags, though it's currently broken.](https://github.com/ankidroid/Anki-Android/blob/81c6e2ef67bd669b1a29f190eeed99307ed086f3/AnkiDroid/src/main/java/com/ichi2/libanki/Tags.java#L193) For reference, the [corresponding  function in desktop Anki calls a function in the rust backend](https://github.com/ankitects/anki/blob/63201d450d8709ada771e14d52b35f40a6879734/pylib/anki/tags.py#L90). If someone were to make an attempt at this feature, should the approach be to port the rust code to java as discussed in #5805 ?

**Comment by bsudhanva** [comment]
+1

**Comment by TarekkMA** [comment]
I would like to work on this one, if it's still a wanted feature.

I will make a change to the tags dialog, will add another state that will be visible, if multiple notes are selected.
* Checked: if all notes have that tag
* Unchecked: if all notes don't have that tag
* Intermediate: if some notes, have this tag and other don't
    *    clicking on it will change it to checked/unchecked, setting the same tag for all cards
    
![Screen Shot 2021-03-17 at 5 08 22 PM](https://user-images.githubusercontent.com/6633545/111490731-ef2a0880-8743-11eb-9036-d9386082aadf.png)
    
In desktop, they don't have this issue, as there is only 2 options from the card browser, add tags, or remove tags

**Comment by mikehardy** [comment]
That sounds good @TarekkMA - as long as nothing is actually persisted to the database until the change is confirmed with an explicit save and there is the option to cancel this works for me.

As an implementation detail, this will need to be done as an AsyncTask with a progress listener because it's touching storage (slow) and the UI will become unresponsive unless it's off in another task, but the UI does need to block (thus the progress listener and a progress dialog) as the CardBrowser will not have a valid state until the oepration is done, at which point it will need to reload itself to show the result of the current search with new tags

**Comment by TarekkMA** [comment]
@mikehardy  no problems, will make that.

**Comment by TarekkMA** [comment]
There is a library  https://github.com/sevar83/indeterminate-checkbox  that does have tri-state checkbox with animation transition. But not maintained. We could fork it, or make our own with no animations, I don't know anything about vector animation in android.

**Comment by mikehardy** [comment]
We will not adopt external dependencies unless they are maintained, and we are busy enough now, fork+maintain is not a good option.

I don't think animation has any value here (in fact, if we animate anything we also have to support disabling the animation since we are used on e-ink readers!)

**Comment by mikehardy** [comment]
The next alpha build will have a tags editor that works on multiple things at once
