### ISSUE TITLE
Enhancement: Integrate Codacy for static analysis / coverage 

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4914]
Lots of issues in the tracker about lint, static analysis, etc. We can close them all and have a process that makes the information actionable if there was analysis from CI that integrated with the PR process in github

I have looked at all the static analysis providers in an attempt to find one that did these things:
1- was free for open source (so lots are out)
2- handled static analysis and coverage for Java (so codebeat, coveralls etc are out)
3- was able to analyze PRs as well (so codecov is out)
4- integrated really well with github and Travis

I believe Codacy fits the bill.

I have it working well enough on my fork that I'd like to integrate it with the main project, and this issue will include some screenshots showing how.

When it's set up, it will look like this on codacy:
https://app.codacy.com/project/mikehardy/Anki-Android/dashboard?branchId=8429314

And [PRs will be decorated](https://github.com/mikehardy/Anki-Android/pull/11) as well.

1) First thing to do is sign up on codacy.com with the ankidroid github user, and tell it to watch the Anki-Android repository.

2) After that you'll want to turn off they non-Java/CSS/JS analysis so it doesn't complain about our Python and Shell (image to follow)

3) You'll want to get the API token and set it into the ankidroid Travis settings (images to follow)

4) Then I'll make a PR for [my coverage branch which produces unified jacoco reports](https://github.com/mikehardy/Anki-Android/commits/coverage-reports) for unit and integration tests, and then via travis [uploads them to codacy](https://app.codacy.com/app/mikehardy/Anki-Android/files?bid=8429314) using the API token from item 3 above

**Comment by mikehardy** [comment]
Forgot that I also chose to ignore lots of files - I don't care if AndroidStudio files, our language files, etc have issues. That's not really actionable I don't think. Here's the files I exclude:

![codacy_ignore_files](https://user-images.githubusercontent.com/782704/44288330-93b6d780-a235-11e8-98e1-98faf97ba569.png)

**Comment by mikehardy** [comment]
Forgot that I also chose to ignore lots of files - I don't care if AndroidStudio files, our language files, etc have issues. And we don't run tests on the api module near as I can tell. So none of that is really actionable I don't think. Here's the files I exclude:

![codacy_ignore_files](https://user-images.githubusercontent.com/782704/44288633-a251be80-a236-11e8-834c-243c49b8a168.png)

**Comment by timrae** [comment]
OK I've one everything except for adding the project API as I don't get that option underneath "Post-Commit Hook"

**Comment by mikehardy** [comment]
Ah cool. That one only shows up when you expand the project settings but maybe you mean you don't see anything at all under hooks? If so then I have no idea how to do the token and then send them coverage. Hmmm

**Comment by timrae** [comment]
Yeah I only see two green circles

**Comment by mikehardy** [comment]
Dang. Sorry to pester but could you post a screen grab? I can ask for support

**Comment by mikehardy** [comment]
@timrae got it! You have to add the "Project API" integration by using the "Add Integration" button on that page, *then* it generates the token. https://support.codacy.com/hc/en-us/articles/207279819-Coverage

**Comment by timrae** [comment]
OK I emailed it to you. Please use encryption rather than committing in plain text to the repository

**Comment by timrae** [comment]
Done
