### ISSUE TITLE
sync error, sd card is considered to be full, while it isn't

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#4916]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

It's not clear to me how you could reproduce my trouble. 
I have a LOT of images in anki My collection.media folder contains 53537 elements. 18 000 of them are new, generated by a script. Most of the other elements are latex images. This folder weigths 1,3Go.

###### Expected Result

A synchronization, with my thousands of new cards, and their media.

###### Actual Result

There are four error messages which occurs.
When I do open anki, it tells me my SD card is full. Which is false, there are still 80 GO free on it.
However, my phone became full during the synchronization. Which is kind of strange, because anki's app is saved on my sd card, and the data are also on the sd card.

Sometime, instead, I see
«Collection not opened.
An error occurred while accessing your collection. It...»

I tried to check the database, but it did not solve anything. I closed and opened again, still the same trouble. Restarting my phone didn't solve this either. 

Sometime, anki close itself just after I opened it, I don't even have time to press the «option» button.

Finally, when I can try to sync,  I have had a message beginning by 
«ankidroid syncin eror type -1 message cannot rollback no transaction is active»  (I had not time to copy it fully)
and 
«Ankidroid
collection synchronized
Error syncing media data

database or disk is full (code 13)
###############################
Error code: 13 (SQLITE_FULL)
Caused by: No avilable space in disk. (database or disk is full (Code 13))
############################

###### Debug info
AnkiDroid Version = 2.9alpha27

Android Version = 7.0

ACRA UUID = 4bb1e4f9-d52b-4248-92ec-8666a48ee7f0

**Comment by Arthur-Milchior** [comment]
Solution: Deleting the new notes.
That's clearly not perfect, but at least I can use ankidroid again. 

More precisely, I've kept a hundred of the new notes generated by my script, and «checked media» to delete every images which are not currently used by this hundred of notes. This will allow me to wait a few weeks before I need to do anything.

**Comment by mikehardy** [comment]
Interesting - thanks for the details and trying to solve it including using the most recent code. Can I ask what your filesystem is for the /sdcard mount? There are kniwn issues with fat32 for big anki collections but I'm I aware of lrobkems with ext4 or ntfs. Could be the problem is fs type interacting with ankidroids flat storage

**Comment by Arthur-Milchior** [comment]
Ok, I've finally understood. 
My ankidroid collection was not at all on sd card. I still find that it's pretty confusing that «sdcard directory»'s value can lie. That there is no warning message, or anything. 
Now that I've understood that the correct value is /storage/3435-3863/Android/data/com.ichi2.anki/AnkiDroid and that I should move the folder myself, it seems to works fine. And I finally have space on my phone's main storage

I currently have no wifi access, so I won't try right now to synchronize again with my ten of thousands of new images and thousands of new notes. I'll let you know later whether I still have the same kind of problem I wrote about above, or whether it's finally solved

**Comment by timrae** [comment]
SD card is not supported in the first place, but glad you got it working
