### ISSUE TITLE
Network Error on Login

### ISSUE THREAD

**Issue by kpleines** [ankidroid/Anki-Android#4918]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Got to "Einstellungen->AnkiDroid->AnkiWeb-Konto (Account)
2. Enter valid EMail and Password
3. Press "Einloggen"

###### Expected Result
Login succesfull

###### Actual Result
Error Message "Ein Netzwerkfehler ist aufgetreten" (An network error occured)

###### Debug info
AnkiDroid Version = 2.8.3

Android Version = 6.0.1

ACRA UUID = e617c65d-e4e2-4c75-9f7f-c06ce8108b88

**Comment by mikehardy** [comment]
Hello! I am only able to reproduce this when my internet connection is fully utilized by other devices, resulting in the login request timing out. I used the same AnkiDroid/Android versions and had the language set to German and when my internet connection was fully utilized for other reasons, I received the error. When I tried again, I was able to login (and synchronize) fine. We haven't received reports of login errors from any other users so I suspect this is a local network problem.

It didn't generate a crash so there is nothing to reference with that ACRA UUID. I'm unsure what handset (mobile phone) you are using but perhaps there is a problem with the mobile network on that device.

Does it still occur on this AnkiDroid version?

**Comment by kpleines** [comment]
Ok, I did it.
I installed the AnkiDroid App on another Android Phone. There I can login succesfully.
After the first login on the second Android Phone, I could also login with my primary phone.

I know my analyse doesn't helps you. But you know, its still working now. 

Thaks for help.

**Comment by mikehardy** [comment]
That is really bizarre! I'm happy it is working for you now, though
