### ISSUE TITLE
Feature suggestion: support MC questions

### ISSUE THREAD

**Issue by tumcode** [ankidroid/Anki-Android#4923]
This would be very useful!

**Comment by mikehardy** [comment]
This is not supported in Anki mainline https://apps.ankiweb.net/docs/manual.html#can-i-do-multiple-choice-questions

There are add-ons for Anki Desktop and card templates using javascript where it may be possible but only if this duplicate issue is resolved https://github.com/ankidroid/Anki-Android/issues/4828

@timrae this should be closed as duplicate

**Comment by mikehardy** [comment]
https://github.com/qwiglydee/anki-interactive
