### ISSUE TITLE
Use text from browser search bar as first field when adding a new note

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4925]
###### Reproduction Steps

1. Search for something in the browser
2. Choose "add note" from overflow menu when no results found

###### Expected Result
The term we searched for should be automatically populated into first field of note editor

###### Actual Result
We have to type it again

**Comment by david-allison-1** [comment]
This is something simple I'll want to get to for AnkiDroid 2.14 if nobody else takes it on

**Comment by IAmJaishree** [comment]
Hi @david-allison-1, I would like to work on it, can I take this issue?

**Comment by Arnold2381** [comment]
Hey @david-allison-1, can I work on this?

**Comment by david-allison-1** [comment]
@IAmJaishree, sorry, I missed the message, are you still interested?

Otherwise, sure!

**Comment by prince-09** [comment]
@david-allison-1 can I work on this issue?

**Comment by david-allison-1** [comment]
@IAmJaishree @Arnold2381

I'll go by order requested above - if you're still interested, please let me know below

**Comment by Arnold2381** [comment]
@david-allison-1  I am interested.

**Comment by david-allison-1** [comment]
Great! Thanks, sorry for the delay

**Comment by Arnold2381** [comment]
No problem!!

**Comment by Arnold2381** [comment]
@david-allison-1  waiting for your reviews!!

**Comment by Prashant830** [comment]
I want to solve this issue ,can I take this issue?

**Comment by david-allison-1** [comment]
Thanks for the enthusiasm @Prashant830!

This issue already has a Pull Request in: https://github.com/ankidroid/Anki-Android/pull/8345, it'd be best to work on another issue.

**Comment by Prashant830** [comment]
@david-allison-1 Ok never mind, I will try to solve some other issue.

**Comment by Arthur-Milchior** [comment]
It's not clear to me why this would generally be a good idea. A request could be such as 
"deck:foo is:new bar" to indicate that you want to search a new card from deck foo containing "bar". At most, only "bar" should be added in the first field.

I guess only part that are not predicate should be added. And even that rules is not easy since we have all boolean combination possible here

**Comment by david-allison-1** [comment]
We've already got a "clear field" button inside the note editor, this has been asked for for some time and would be useful to me. 

I'm personally happy with this as it is (a dumb copy from the search to the field), and if we need to iterate, then we'll take it as it comes.

**Comment by mikehardy** [comment]
Closed via #8345
