### ISSUE TITLE
[improvement] User-programmed keyboard switching

### ISSUE THREAD

**Issue by ElDonad** [ankidroid/Anki-Android#4927]
Hi there ! 
Japanese learner since a few month, I noticed how painful it is to switch between my French keyboard (when answering a "signification" question) and my Japanese keyboard (when answering "reading" questions) when I have to practice both of them. 

So my suggestion would be that the user, during the design of the card, could specify (with something like a special property on the type field, or an additional selection menu, I'm not Android programmer unfortunately so I can't help for that...) the keyboard he would like to use when answering. 

Maybe this selection could even be done by analysing the localisation of the expected answer ? I don't know, this is a simple suggestion... 

Thanks for reading, and sorry for the approximative English :(

**Comment by timrae** [comment]
Hi it's not possible for us to change the keyboard programmatically on Android
