### ISSUE TITLE
[improvement] copy existing flashcard to another deck

### ISSUE THREAD

**Issue by thodorisbais** [ankidroid/Anki-Android#4930]
I think this is pretty straight-forward.

It would be really nice for the users if they had the ability to easily copy a flash card over different decks.

What do you think of it?

**Comment by Konotori** [comment]
Yon can move a card from one deck to another (from the edit note menu). Why would you want to copy a card over several decks?

**Comment by thodorisbais** [comment]
Example: I am reading a technical book. That books is divided into different chapters. For each chapter I keep a deck. But then, I would also like to have a generic deck containing the "hottest" topics of each chapter, so each time I come across something really important I would like to have the option the copy it from the "chapter-deck" to the "generic-deck".

**Comment by mikehardy** [comment]
Add a tag and make a filtered deck for that tag?

**Comment by mikehardy** [comment]
@thodorisbais - I sincerely believe that a tag and filtered deck is still the best solution for your use case but I have seen an indication that you should be careful moving cards in "learning" state into or out of filtered decks as they may have an unexpected interaction with their learning status: https://eshapard.github.io/anki/anki-and-the-hidden-dangers-of-filtered-decks.html

I am curious if this has worked for you though.

**Comment by thodorisbais** [comment]
That specific study material of mine is not the top priority, for now, so, I would suggest we close this issue.
