### ISSUE TITLE
Play store showing Multiple APKs available?

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4931]
I'm looking into publishing a new Chrome Store version, and I notice that 2.8.3 is what is pushed out for my personal device, plus the Play Store itself says "current version" "varies by device", which indicates the Multiple APK feature is enabled, and maybe 2.8.4 isn't pushed out completely?

https://stackoverflow.com/a/31402038/9910298

I can imagine enabling that feature for 2.8.5+ in order to maintain support for Android API <15, but I'm not sure if this is intended at the moment so logging this to check.

**Comment by timrae** [comment]
Well spotted, I took a look and it seems Google has made it pretty easy to retain old APKs.

**Comment by timrae** [comment]
It seems I had also actually not released 2.8.4 properly due to unfamiliarity with the new console 😢 
So now I've just released 2.8.4 properly, and it gave me the option to retain release 2.7, which was enabled by default and I kept enabled.

**Comment by timrae** [comment]
Oh just noticed that you mentioned the 2.8.3 thing in the issue body lol

**Comment by mikehardy** [comment]
2.8.4 cut crashes by a third and generated around 35,000 new installs - probably helped a lot of people 
![screenshot from 2018-09-14 09-58-04](https://user-images.githubusercontent.com/782704/45558245-10bd7880-b805-11e8-8126-206494ea63c0.png) good work on #4744
