### ISSUE TITLE
Enhancement: Use standard file picker for package import/export on API>=19

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4932]
As mentioned by Tim on #3906:
```
It's always been the intention to use ACTION_OPEN_DOCUMENT to import apkgs
on API 19+, just nobody has ever gotten around to it.
```

Feel free to disagree with any of this, but I think the general idea is that if the API level supports it, AnkiDroid should completely bypass the current file selector and instead use [Intent.ACTION_OPEN_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT) to do collection imports.

Bonus points for using [Intent.ACTION_CREATE_DOCUMENT](https://developer.android.com/reference/android/content/Intent#ACTION_CREATE_DOCUMENT) when exporting an apkg

Some reasonable example code that show how to set the Intent options and open the resulting content:// URI stream:
http://www.zoftino.com/how-to-create-browse-files-option-in-android

**Comment by mikehardy** [comment]
Worth noting that this, in combination [with CSV/TSV import](https://github.com/vi/AnkiImporter) would allow for people to create large decks using e.g. Google Sheets / Google Docs / Google Drive, without needing AnkiDesktop

**Comment by timrae** [comment]
Shall we just bump the min SDK to Android 4.4 now that we have multiple APK support by default? Android 4.1 - 4.3 Jelly Bean only represents 2.5% of our user base, and Android 4.3 is already 6 years old now.

**Comment by timrae** [comment]
Do you want to show the confirmation dialog before or after you fire off the intent?

**Comment by mikehardy** [comment]
Definitely want the old flow, I thought it was sane. Intent fires (either view file from an open apkg action result from open document request) and then we display dialogs to confirm (or in future warn about space or OOM possibilities from my OOM branch).

I'd prefer to not peel off dead end APKs personally unless it was really hard to support until we see what hot fixing them is like. Or until we have some sort of daily active users by api metric but we have no analytics right?

**Comment by timrae** [comment]
Yeah, in the case of another 2.8.x hotfix I guess we'd have to port these API changes across which would take a little bit of effort. Anyway it's up to you whether or not you want to do it now, but I'm in favor of bumping the min SDK to 19 at the next opportunity where it makes something easier whenever that might be. And yeah we don't do any of that kind of analytics.

**Comment by mikehardy** [comment]
```
Yeah, in the case of another 2.8.x hotfix I guess we'd have to port these API changes across which would take a little bit of effort. 
```

...or cherry-pick and fix them up, but yeah without seeing either who's actually using what or how that hotfix will work (haven't experienced it yet?) I'd rather incur a little technical debt.

On the analytics side, I infer (please correct if wrong) that we want to function without a Google Play Services dependency? That means firebase is out but we could use google analytics without a Play Service dependency:

https://developers.google.com/analytics/devguides/collection/android/v4/ - 
```
Note: Google Analytics can be used and will work on devices that do not have Google Play Services. In this case you still download and use the Google Play Services SDK and Google Analytics will automatically fall back to local dispatching. Learn how to update your project's manifest file to enable background dispatching on non-Google Play devices.
```

Google analytics in this format is free up to millions of hits and you can do a sampling strategy after that if required. There are good examples of opt-out etc. I'd be willing to implement this as a personal learning project if you were okay with it and I had access to whatever dashboard lets me see results (so I know I'm hooked up - similar to acra server visibility)

**Comment by mikehardy** [comment]
@timrae very curious for thoughts on analytics. I'd love to see actual usage stats, ACRA is useful but ignores the mass of the userbase where things are working, and gives no insight into feature usage. I would throw a pop-up whenever it was released explaining it and having the opt-in box checked, but obviously allow opt-out and make it easy to find in prefs for opt-out. I'm a privacy person myself but for open source apps that promise not to monetize, even I usually allow it. Thoughts?

**Comment by timrae** [comment]
Sure, it's zero priority for me, but if you can implement it cleanly without any GPL incompatible libraries, and it's a completely opt-in process then I don't see any reason why not.

**Comment by mikehardy** [comment]
Getting back to the actual issue - I still am stuck on not knowing why the dialog doesn't work correctly on this line of code:

https://github.com/mikehardy/Anki-Android/commit/3021c185e8359ac9731232b3f18a67a51f67d1c1#diff-1dc12d88567262637de9f7d58f429f28R132

You asked if I wanted it the dialog before or after the intent - I responded I want the old flow - Intent fires (either view file from an open apkg action or result from open document request) and then we display dialogs to confirm (or in future warn about space or OOM possibilities from my OOM branch).

**Comment by timrae** [comment]
It might take me a bit of time to get to this tbh but it's on my list :/
