### ISSUE TITLE
Convert FloatingActionMenu to supported library

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4936]
The current FloatingActionMenu library is abandoned.

We should either convert to an actively developed replacement such as this one (the best I saw): https://github.com/leinardi/FloatingActionButtonSpeedDial

Or since our menu is fairly simple, implement it using framework SDKs such as this example: https://github.com/ajaydewari/FloatingActionButtonMenu (from https://stackoverflow.com/questions/30699302/android-design-support-library-expandable-floating-action-buttonfab-menu)

**Comment by mikehardy** [comment]
saw this in passing - another alternative https://github.com/robertlevonyan/customFloatingActionButton

**Comment by mikehardy** [comment]
@JordanCleeve found this https://github.com/leinardi/FloatingActionButtonSpeedDial and has an implementation cooking as part of #5134 - may be able to close this shortly

**Comment by mikehardy** [comment]
This one is still needed and has an implementation that is working (but needs an update by anyone with time) in #5134

**Comment by Akshay0701** [comment]
do you want to change floating action button completely from deckpecker activity ? , i would love to do that with `FloatingActionButtonSpeedDial` Android library,can i take this issue to work on ?

**Comment by Akshay0701** [comment]
i liked `FloatingActionButtonSpeedDial` because it gives option to add floating button items from java code as well , so we don't required xml file with name `floating_add_button.xml`, let me know what your thoughts in this library : )

**Comment by david-allison-1** [comment]
Could you link to the library so we can evaluate it?

If you're referring to https://github.com/leinardi/FloatingActionButtonSpeedDial, then it doesn't seem maintained (no commits since 2019, with 31 open issues)

**Comment by Akshay0701** [comment]
Thanks for addressing that , could you please suggest some stable library for `floatingActionMenu `

**Comment by mikehardy** [comment]
Let's not use a library, I think they are all abandoned because people are just using the apis in the standard libraries

**Comment by Akshay0701** [comment]
then what would be solution for this according to you @mikehardy ?

**Comment by mikehardy** [comment]
I linked an issue here a couple days ago: please see the discussion there, and yes the idea is to not use a library. #8223 - it may be that someone is already contemplating working on that, per discussion on that issue

I definitely do not want to adopt an abandoned library, and I do not think our use case is so fancy that we can't just use the android APIs directly based on what I have seen

**Comment by Akshay0701** [comment]
okay i understood we shouldn't use abandoned library ,i think inbuilt google.Material FABs will be good option 
(https://material.io/components/buttons-floating-action-button) ,this don't require any external library, it is supported by android sdk.

**Comment by mikehardy** [comment]
I agree - unless someone tries it and it is not possible to implement using the built in FAB APIs, we should use them

**Comment by Akshay0701** [comment]
could you give me some more info/guidance on how i can move further to this ?

**Comment by mikehardy** [comment]
1) document all the features of our current floating action menu
2) implement those features without using an external dependency

**Comment by Akshay0701** [comment]
@mikehardy i implemented FloatingActionMenu with FABS ,
There is still many imporvement need in ui as well as code ,
I will raise PR ones i clean all code
<img src="https://user-images.githubusercontent.com/52353967/111864743-c5adee80-8988-11eb-9419-4fe4cf643e08.gif" width="200" height="400" />

**Comment by tanmayChakrawarty** [comment]
We can further improve the UI by blurry effect or fade the background when FAB is clicked.
I have tried this  https://github.com/tanmayChakrawarty/FabMenu
![Screenrecording](https://user-images.githubusercontent.com/75254780/112109212-49f5b100-8bd7-11eb-9df8-da1f8d73dbe6.gif)
