### ISSUE TITLE
Cards unable to be redrawn after screen off

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4938]
Uh.oh.

**Comment by timrae** [comment]
Android 8.0.0, alpha 30
I believe it's gonna be easy to reproduce

**Comment by mikehardy** [comment]
Sure - I'm just now rebasing and branching out after you merged the last PR, I'll see what I can see

**Comment by mikehardy** [comment]
if you publish those to any distribution channels you should stop it though! no need to get a flood of reports for even one bug when we know a big chunk landed...

**Comment by timrae** [comment]
They're automatically published to the alpha channel, I don't see a way to
unpublish the APK without reverting the change and putting out a new
release, but there are only 64 alpha testers subscribed to that channel, so
as long as we can fix it promptly it's not the end of the world

On 11 Sep. 2018 12:24 am, "Mike Hardy" <notifications@github.com> wrote:

if you publish those to any distribution channels you should stop it
though! no need to get a flood of reports for even one bug when we know a
big chunk landed...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/4938#issuecomment-419953084>,
or mute the thread

**Comment by mikehardy** [comment]
got it. just firing up the environment on that code right now and if I/we can't find it in the next couple hours we can revert

**Comment by timrae** [comment]
It's still working ok on orientation change at least, but if there's no
quick fix we might have to store the card id and reload it from the
scheduler, which may not be a small change. :/

I've been dreading the day that this comes for a while now tbh lol. The
confirmation dialog class is built on a shoddy assumption that might be
broken as well.

**Comment by timrae** [comment]
I'm off to bed but will put out a release in the morning either way

**Comment by mikehardy** [comment]
Ok - I just bisected and it's the (otherwise clean) commit that does just the library upgrade and associated required-only refactor. We'll see but I may not be able to isolate it quickly

**Comment by timrae** [comment]
Thanks for the quick response, confirmed that the problem is resolved in the new alpha.

**Comment by mikehardy** [comment]
Developer comments on the 27.0->27.1 changes: https://medium.com/androiddevelopers/loaders-in-support-library-27-1-0-b1a1f0fee638

I think this issue should remain open and have a "Support Library 27.1.x - " prefix (those issue summaries are how I'm looking at forward-porting issues, or maybe we need an issue tag for "forward-porting" or similar)

**Comment by mikehardy** [comment]
I found the exact library hook at this point.

The 27.0.2 and 27.1.1 sequence for initial card load is:

1.  UI thread deck picker -> select deck
2. UI thread deck is loaded and picks first card
3. UI thread Reviewer.onResume() (plus whole object hierarchy) is called and finishes
4. Async thread CollectionLoader.deliverResult() is called
5. UI thread AnkiActivity.onLoadFinished() / LoaderCallback called
6. UI thread Reviewer.onCollectionLoaded() called the super() chain goes up
7. UI thread AbstractFlashcardViewer.onCollectionLoaded() does lots of stuff
8. UI thread Reviewer.onCollectionLoaded() does lots of stuff

For 27.0.2 screen power cycle it looks like:

1. All the onPause() stuff happens as screen goes down
2. Step 3 from the initial card load above happens as screen comes up
3. Step 4 above happens, but Step 5 on the UI thread never happens. No call.
4. The WebView show up

For 27.1.1 screen power cycle:

1. same as 27.0.2
2. same as 27.0.2
3. Steps 5-8 from the initial card load happen! UI thread .onCollectionLoaded is called
9. The WebView is blanked out :-( 

What I don't understand is why the WebView doesn't just show up again. It seems to me that the 27.0.2 flow was actually wrong - the 27.1.1 flow should be fine as it is idempotent really, but for some reason the work done by item 5-8 of the initial load works once, but not a second time on the same screen. Maybe during onPause() we need to do some more WebView teardown for 27.1.1 to make it ready for all the re-init it does?

I'm still investigating, but that's where my current understanding is.
