### ISSUE TITLE
Height of decks in deck list increased from alpha29 to alpha30?

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#4942]
I guess because of the divider change?

**Comment by mikehardy** [comment]
Probably - it altered the height of the searches in the my searches dialog so they aren't beautiful at the moment as well.

I think using Framework SDKs where possible is generally good, so I'd like to find a way to get the rendering right with it, but if not and we could resurrect the old divider

**Comment by timrae** [comment]
Agreed, and I don't think it'll be very difficult to fix

**Comment by timrae** [comment]
It seems that the material guidelines recommend not to use a divider lol

https://material.io/design/components/dividers.html#types-figure-caption-3
