### ISSUE TITLE
Night mode theme changing not functioning completely dark to night to dark

### ISSUE THREAD

**Issue by CowboyEnvy** [ankidroid/Anki-Android#4943]
###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Change into night mode
2. Change theme to black
3. Change theme back to dark

###### Expected Result
Theme should return back to dark mode completely 

###### Actual Result
Flashcard theme remains black instead of dark ther rest of the app seems to revert to dark.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.8.4

Android Version = 8.0.0

ACRA UUID = 368a5950-6224-4efa-b3b7-cc74586083cc

**Comment by timrae** [comment]
I can't reproduce on the latest alpha version, and we haven't changed anything that would break that AFAIK. Does it work as expected if you restart the app?

**Comment by timrae** [comment]
Oh I see you're talking about the flashcards themselves... This is the intended behavior actually, as you can change the color of the flashcards as you like from the card template:

https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#customize-night-mode-colors

**Comment by CowboyEnvy** [comment]
No it does not, it's still black, the only thing I haven't tried is
reinstalling it.

**Comment by timrae** [comment]
See the link I posted
