### ISSUE TITLE
Pink dots and text input placement suggestion with text-to-speech enabled

### ISSUE THREAD

**Issue by kryacer** [ankidroid/Anki-Android#4946]
![s80911-193024](https://user-images.githubusercontent.com/35563053/45363576-af758980-b5f9-11e8-9479-e665020094e0.jpg)
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps
If i remove {{type:Front}} then dots disappear
My Front Template looks like this:
{{AudioMary}}
{{AudioHunt}}

{{^AudioHunt}}
{{^AudioMary}}
div>{{Front}}</div
{{/AudioMary}}
{{/AudioHunt}}

{{type:Front}}
###### Expected Result
Clean display without pink dots

###### Actual Result
at least 6 dots

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

**Comment by mikehardy** [comment]
Please edit your report to fill in all requested information so we can help

**Comment by mikehardy** [comment]
I need to know what version of AnkiDroid you have installed, and what version of Android you are running.

**Comment by kryacer** [comment]
Anki is latest version. Android 5.1. Also tested it for 8th android. Same issue

**Comment by mikehardy** [comment]
Thank you! Sorry, hopefully last question - can you tell me the note type? when you are editing the card (but not the card template) there should be an indication of note type, something like "Basic (and reversed card)" or "Cloze" or similar? or even better if you could export the deck and save it to this issue I could import it and debug it. Thanks for the feedback

**Comment by mikehardy** [comment]
Wait! I just saw a different user with a question on text input, and I think it solves the puzzle. This is a text input prompt - the {{type:Front}} part is the key. Please read here, and if you would like different formatting you'll have to update your template to not have text input, or you'll have to turn text input off in AnkiDroid or similar: https://docs.ankidroid.org/#typeInAnswer

I'll leave this open for a little bit to make sure, but I'm nearly certain this is the issue.

**Comment by mikehardy** [comment]
Ah ha! If you have text input turned on, then that's okay. The pink dots are exactly the thing that tells you have text input on. They are not a bug, they are an indicator.

**Comment by kryacer** [comment]
Only now i understood what you meant about turning off/on text input. I thought you meant remove {{type:front}} from template. But if i turn on input then field for typing move into center of screen, which inconvenient on big screen devices.

**Comment by mikehardy** [comment]
Hmm - there may be an interaction on tablet layout devices. Could you post a screenshot of what you're seeing now, vs what you would expect?

**Comment by kryacer** [comment]
![s80923-140511](https://user-images.githubusercontent.com/35563053/45925565-bbd2de00-bf39-11e8-9dcd-1d171dd0abc7.jpg)
![s80923-140453](https://user-images.githubusercontent.com/35563053/45925566-c8573680-bf39-11e8-9799-e0a2514928fb.jpg)

**Comment by kryacer** [comment]
Input field near with "show answer" is the best

**Comment by mikehardy** [comment]
Okay - thanks for your persistence :-), I think we understand each other now? If I am correct, this issue could be described as such "Text entry box placement is inconvenient", and your suggestion is that the text entry box always be near the show answer button? Please correct me if I didn't get that right - just trying to make this clear

**Comment by kryacer** [comment]
absolutely.
You can just swap these situations when user pick "on" to text input then place field near show answer and vise versa.  But it would look weird as textbox with borders near show answer, and "type answer" near play buttons. Hard to imagine. So easy solution is to turn off indicator which shows as pink dots, or make it in new line and justify by center.

**Comment by mikehardy** [comment]
Okay - thanks again for your persistence / patience getting to an understanding here. I'll think on it a bit and update the title + think about what the change would mean in a bit, but I'm clearly not waiting on feedback at this point. Despite pink dots everywhere, hope AnkiDroid helps you learn what you need to learn...

**Comment by mikehardy** [comment]
Saw this in another location, and wanted to paste it in here. The text box has a CSS class defined in the card and you can specify arbitrary CSS to put in the card template to style the appearance. Using this ability is most likely the solution here. Here is an example of what is possible (this simply hides the box):

https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#hide-the-input-box-on-cards-using-the-type-in-the-answer-feature

```
.mobile input#typeans{
display: none;
}
```

**Comment by kryacer** [comment]
Cool! That works. Thanks
.mobile #typeans{
display: none;
}

**Comment by mikehardy** [comment]
Glad you've got a solution for now - I'll keep this open pending a decision on moving the text input close to the show answer button by default - it would likely be an easy change but I want review on the idea

**Comment by kryacer** [comment]
After "display none" with dots also disappear word correction. So anki dont show did you correct or not. So i placed {{type:Front}} into div tag and applied css like: 
.mobile #typeans{color: white;}

**Comment by mikehardy** [comment]
No one has mentioned anything against it, I think moving the text box down by default would be an acceptable change if someone wants to have at it.

**Comment by jportoles** [comment]
In case anyone else comes accross this, `.typePrompt { display: none; }` removes the pink dots without side effects.
