### ISSUE TITLE
Throttle crash reports from same trace

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4949]
I understand there is some bespoke logic in AnkiDroidApp to do this already

ACRA (since 5.0.0) includes a limiter with the same features we want, and it would make the crash database much more useful - right now the database is quickly spammed with identical reports and it's difficult to sift through

Documentation here:
https://www.acra.ch/javadoc/latest/org/acra/annotation/AcraLimiter.html

I propose this config (this is all items, with default and proposed value):

- exceptionClassLimitlimit for reports with the same exception class
  - default 10, proposed value 1000 (intention is to not impose a limit, stack traces will catch most of the duplication but we use the same exception class all over, so...)
- failedReportLimitlimit for unsent reports
  - 5 (leave as default so we don't clutter up filesystems)
- overallLimitgeneral limit of reports
  - 25 (leave as default, unlikely more than 25 reports from a device is useful)
- periodReports which have been collected before this will not be considered for any limits except failedReportLimit()
  - 7L (leave as default, after a week we can roll reports off?)
- periodUnitUnit of period()
  - DAY (leave as default)
- resIgnoredCrashToasttoast shown when a report was not collected or sent because a limit was exceeded
  - 0 (do not display a toast if we are limiting a report)
- stacktraceLimit
  - 3 default, proposed 1 (I only want to see the same exception once, personally)

I would port this to the 2.8 series (I think it would be pretty easy since I did the ACRA changes) so we could maybe fix crash bugs for older APIs, as it is now I can't pick much out of acralyzer

**Comment by mikehardy** [comment]
Alternatively I guess if I could get admin access to acralyzer so I could pull it and do some database-level crunching...

**Comment by timrae** [comment]
Sure those options sound good to me!

**Comment by mikehardy** [comment]
When I tried that earlier I could not label but maybe I wasn't owner and that was it. I'll label my own if I can

**Comment by mikehardy** [comment]
I am definitely not able to add labels, even if I am the issue owner. You'd have to add me to the project in some official way I guess - 
https://help.github.com/articles/applying-labels-to-issues-and-pull-requests/

```
In repositories where you have write access, you can assign labels to issues and pull requests to help organize your projects.
```

I think I could be a useful addition if you're into it as I do spend a fair bit of time on the issues list. If so I solemnly swear to never merge a thing individually as everything I code needs review on so many levels from "is it even a good idea", to "is it the best way then" to "don't forget about this case" before it even gets to "that line of code sucks" etc

**Comment by timrae** [comment]
Yeah I know you need access, I've been planning to give it to you for a while just haven't gotten around to writing the email lol

**Comment by mikehardy** [comment]
I want this out in all releases ASAP - I have a question out to ACRA to ask the best way since I couldn't find a clean API to finalize it. Should know within a day
