### ISSUE TITLE
Deck Picker sync / top-right menu don't show if storage permissions dialog shows

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4951]
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Reproduction Steps

1. Fresh install of AnkiDroid with no prior permissions granted on API>M 
2. open AnkiDroid, grant permissions for storage
3. Examine DeckPicker screen

###### Expected Result

Empty Deck Picker screen (Just the "Default" deck) and the sync icon and 3-dot menu icon should be at top right

###### Actual Result

The sync icon and 3-dot menu icon are not at the top right. If you stop and restart the app (with permissions already granted for all but the first start), the icons are there.

This is with the currently alpha - 2.9alpha31 at the moment

**Comment by timrae** [comment]
Oh yeah this has been around for a while AFAIK
