### ISSUE TITLE
Feature request: Reset progress button

### ISSUE THREAD

**Issue by Mornon** [ankidroid/Anki-Android#4956]
In AnkiDroid it's possible to add several buttons for when the card is being studied:

![photo_2018-09-13_15-30-27](https://user-images.githubusercontent.com/21358808/45491721-afe16200-b76a-11e8-87d7-8bbc02952388.jpg)

Would it be possible to have a Reset progress button? Sometimes I need to reset the progress on one card while studying, and since Again with my settings doesn't reset (being set at 75% percent of the interval) such a button would be handy.

Edit: Resized the image, which was too big.

**Comment by mikehardy** [comment]
Interesting - I see that in the Card Browser you can reset progress on an individual card, so the feature exists even though it only exists as a plugin for Anki Desktop but no, it does not exist as a button you may add on the review bar. @timrae what's your guidance on what to do with feature requests that definitely aren't in Anki Desktop? The closest Anki Desktop gets to this is allowing you to "reschedule to end of new cards queue" via the card browser. This one is more subtle in particular because we do have "reset progress" in the card browser already...

**Comment by timrae** [comment]
> The closest Anki Desktop gets to this is allowing you to "reschedule to end of new cards queue" via the card browser. 

The names have diverged over time, but reset progress hooks into libanki [`forgetCards()`](https://github.com/dae/anki/blob/master/anki/sched.py#L1338) which is the same as that desktop option to reschedule to end of new cards queue.

> what's your guidance on what to do with feature requests that definitely aren't in Anki Desktop? 

Well the general guidance is to close such issues as won't fix unless there's a really compelling reason not to. If someone were to submit a PR or were asking on whether or not it would be merged then that's a different story and would evaluate case by case. In this case it's a pretty simple change, which could be implemented such that the menu item was completely hidden by default unless explicitly enabled, so I wouldn't be against merging if there were a clean implementation.

**Comment by mikehardy** [comment]
@Mornon - if you can find me a nice icon to use I can maybe do this

Examples are here in the "drawables" directories. I can code but graphics is not my thing. It is likely there are resources online which can take one good icon and generate all the necessary size variants so this is not as hard as it may seem

**Comment by timrae** [comment]
FYI: The icon must be open source with vector version, most of ours come from the main Google repository which is a good place to start

**Comment by Mornon** [comment]
Thanks! In the Google Repository I found some that could work; if these aren't fit let me know and I'll search for more.

https://material.io/tools/icons/?icon=fast_rewind&style=baseline
which I like because it already mean "Bring to the start" in music and the like, so a concept similar to reset.

https://material.io/tools/icons/?icon=cancel_presentation&style=baseline
which I like because it's a card with an X, the idea of "The card is being reset"; which I don't like beucase it could mean "Delete the card".

https://material.io/tools/icons/?icon=highlight_off&style=baseline
which I like for similar reasons to the previous one, without the backdrop of being like a deleted card.

I'm trying to understand if Repository has all the necessary size variants; if not I can try to generate them, just not sure which they are.

**Comment by mikehardy** [comment]
I like fast rewind, can't help on sizes I would have to compare file by file with an existing button - haven't done one before

**Comment by Mornon** [comment]
Ok, I'll look about fast rewind; Google Repository has the vectorial version. Now I'll try to understand if that's enough, since it's scalable, or which size(s) I need to do.

**Comment by timrae** [comment]
I'm not sure what the current state of vector graphics is on Android (i.e. whether or not we still need pngs on Jellybean), but traditionally Google provides all the resolutions and we put them all in down to mdp, you can see the existing icons in the source tree

**Comment by Mornon** [comment]
I'll check about the resolutions, not sure what are mdp and source tree (sorry, not really used to GitHub).

**Comment by mikehardy** [comment]
`not sure what are mdp and source tree (sorry, not really used to GitHub).` - you are right where I was last December :-). If you keep trying I'm sure you'll get it, I'll try to help if I can

**Comment by Mornon** [comment]
Still not sure about mdp, but thanks to a friend of mine I found the icon repository; I checked the icons there and they are either 72x72 or 96x96, so I took those sizes from Google Repository, here they are (I'm unable to uploade them in drawable):

![ic_reset_96](https://user-images.githubusercontent.com/21358808/45819229-22f75500-bce4-11e8-8dc6-87095e4dac53.png)
![ic_reset_72](https://user-images.githubusercontent.com/21358808/45819230-22f75500-bce4-11e8-8970-268370980af0.png)

Is this enough?

**Comment by mikehardy** [comment]
@Mornon  - thanks for these, I'll check. @timrae I'm still learning UI stuff but I'm fine sort of blundering through it on the way to a PR as part of the learning process so don't worry about this one until you see the PR come through

**Comment by JordanCleeve** [comment]
@timrae Could you please close this issue?

**Comment by WiliTest** [comment]
Please add the "reset progress" option (of a specific card) to the app bar. We currently need to quit the desk and find the card in the card browser to do it which takes time.

**Comment by WiliTest** [comment]
Since I forgot again where the "reset progress" was in the App Bar Buttons, I'm writing it here: it's hidden with the reschedule button.  **It would be easier to find if this button was renamed "Reschedule or Reset"** (in my view these 2 features mean completely different things, I don't understand why they are together).

**Comment by mikehardy** [comment]
They are together because they all mess directly / override scheduling directly on cards, outside of automatic scheduler control.
From our perspective, you either let the scheduler do its thing and get on with your life, or you are "rescheduling", to either reposition, reset progress, or reset schedule or maybe 4 or 10 other ways people want to mess with scheduler data in the future
