### ISSUE TITLE
[Feature Request] In-App adjustment of volume of media files ("volume boost")

### ISSUE THREAD

**Issue by Hype-Toriyama** [ankidroid/Anki-Android#4957]
###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

[Feature Request:] In-App option to increase the volume of media files
In cases, when the max volume of the phone is too low.

On my Xiaomi Mi A 2 Lite the volume of audiofiles is average, even if I put the master volume of my phone regarding media output to max.
I have seen other apps with inbuilt "volume boosts" (ex: "Podcast Go", "https://play.google.com/store/apps/details?id=sanity.podcast.freak"), which give you access to higher volumes, whenever your phones max master volume is not sufficient. 

For me at least it would be handy to have a feature like this.
Thanks.

**Comment by mikehardy** [comment]
This is something the desktop doesn't do so is unlikely. In cases like this I have used a system wide equalizer to boost. I personally use one literally called "Music Equalizer" and solves this use case. Can you try that and report back?

**Comment by Hype-Toriyama** [comment]
I tried the one called "Music Equalizer" and some others poping up along with it. Also I tried one called "Volume enhancer". It works fine with my Music (played with googles "Play Music" App), but none did affect the volume of my Anki cards.

The volume of sounds on my phone can be adjusted seperately. The categories are "alarm", "ringtone" and "media". Although adjustments of the "media" volume both affects music and ankidroid volume, the other equalizers only affected music. 
(I'm new to android... maybe thats another issue here...)

Thanks for the hints though. Appreciate it.

**Comment by mikehardy** [comment]
I dug into how android handles equalizers and honestly, as a developer and experienced android user I'm not sure how I can make sure Android respects equalizer settings but this appears to be a common problem with Android and a variety of applications. I believe we're setting all the right flags for our type of audio output, and it may just be that it's not possible for apps that play short clips to have them equalized. I'll leave this open for a bit in case someone else sees something. For reference our playback is configured here: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java#L352

**Comment by mikehardy** [comment]
I've noticed we are using some deprecated music interfaces from the android operating system and I'm working on moving to the new APIs. It may have no effect, but when 2.9 comes out in beta you may notice a difference. In the meantime I'm going to close this because it's not actionable unfortunately - my investigation turned up nothing obvious

**Comment by Hype-Toriyama** [comment]
Alright. Thank you a lot. Gonna wait and report back
