### ISSUE TITLE
2.9 Release coordination

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4961]
This issue is just to coordinate the release.

We've got a milestone to track items: https://github.com/ankidroid/Anki-Android/milestone/11

I have marked a few items speculatively for inclusion where my intention is to estimate time required and potentially drop them from the release, so the list may change in the next couple days as I drop things that aren't workable

**Comment by mikehardy** [comment]
I just focused my goals for the 2.9 release somewhat. Things I really want:
- advanced notifications to not be "weird" (and per deck group is "weird" to me)
- audio clip from file (it seems so close?)
- gui language settings (I had this partially working at one point)
- tag important analytics things (I'll do a round in a few days)

I'm likely going to ignore the rest.

**Comment by mikehardy** [comment]
@timrae If you pull up the 2.9 milestone page now, I've got it roughly ordered (you can drag issues up and down).

The ordering I'm imposing is this:
1. any PR (or issue related to a PR) that has is ready for review and can be closed if the review passes and the PR merges is above this 2.9 coordination issue
1. this issue
1. any issue that has no pending PR ready for review but would create strings that need localization (thus blocking betas I think?)
1. any issue that has no pending PR ready for review but does not affect localization

At the moment we've got 3 PRs for v2.9 that I can no longer find problems in but I'd like review on, and one of those depends on a 4th PR (sqlite framework APIs). There are a couple other little PRs that look good to go but aren't 2.9 specific.

What are your thoughts on me merging these in to continue the 2.9 beta push? I've got a little of my confidence back since the upgrade-version issue, built on more textual review passes but I don't want to be pushy and I certainly don't mean to irritate you. I just know you're busy and based on earlier conversations I suspect that will stay the same for a while?

**Comment by timrae** [comment]
> What are your thoughts on me merging these in to continue the 2.9 beta push? I've got a little of my confidence back since the upgrade-version issue, built on more textual review passes but I don't want to be pushy and I certainly don't mean to irritate you.

Let me check these PRs when I have time. I think you're still a little way off merging your own PRs but maybe soon.

**Comment by mikehardy** [comment]
>  I think you're still a little way off merging your own PRs but maybe soon.

I do not disagree :-)

Just knowing your preference is good, I'll hold tight.

**Comment by mikehardy** [comment]
I’ve got all my PRs in shape for merge I think.

I wish I had more time for notifications changes, GUI language etc but it’s been a long time, and we can always release again…

**Comment by mikehardy** [comment]
Hey Mr @timrae! I'm headed from vacation now. Anything you need from me to finish shaping up 2.9? I don't *think* I'm on the hook for PRs right now with CardTemplateEditor + Database Versioning on deck for a re-try in 2.10 but I thought I'd check in just in case. I'd be happy to help in general if there's administrivia to finish out as well, I think I have a docs PR for 2.9 staged somewhere etc, maybe translations or a QA pass or whatever. Would love to see 2.9 out so let me know if I can help. Cheers

**Comment by timrae** [comment]
I think we're pretty much good to go, the main blocking task now is the release notes I think.

**Comment by mikehardy** [comment]
starting point here with changes cataloged up to the point of PR submission https://github.com/ankidroid/ankidroiddocs/pull/39

No opinion on what should or should not be included, was just adding about anything I saw in the commit log at the time

**Comment by adamwolf** [comment]
What's left now?  Updating mikehardy's release notes?

**Comment by mikehardy** [comment]
yeah - sorry I haven't gotten to it! feel free to run with it if you want. Just needs a commit scan on the release-2.9 branch from whenever I originally started that PR up to now. There were some nifty features if I recall.

Maybe also adding some sections to the manual for Mathjax, multi-select, card re-scheduling...and I think that's all the features?

**Comment by adamwolf** [comment]
We definitely need a section on Mathjax. I'm a little bogged down this
week, but if it's still around next week I'll take a stab at it!

**Comment by timrae** [comment]
OK the release notes are done now.
Aiming to do the final release within a week from now.
@adamwolf do you have time to do the mathjax documentation in the user manual.

**Comment by adamwolf** [comment]
Yup.  Will carve out some time tomorrow.

**Comment by adamwolf** [comment]
PR for Mathjax docs here: https://github.com/ankidroid/ankidroiddocs/pull/44

**Comment by timokau** [comment]
2.9 has just landed on f-droid, so I think this can be closed. Thank you all for your good work!

**Comment by mikehardy** [comment]
Yeah, agreed there. Need to open one for 2.10 really

**Comment by timrae** [comment]
2.9.2 commit log with dependency updates stripped out:
c71c2fe04 Correct edition of card in filtered deck
4f268342e fix negative due dates in filtered decks
ca42304ff Clears undo before changing schedulers
c8a20afbc New card with same due are shown according to their ord
bcc13aaf3 some html regexps should be case insensitive
43ff6f7b6 fix crash on app startup with uninitialized collection
ece0b5d33 escape backslash in find&replace
c4865da41 Cloze menu (#5536)
037219dc8 Fix Mathjax Cloze duplication issue.
aa94e209f Don't run gitflow-integrate script unless we're on correct branch
21c1838bb Adding missing Throw
0c1847276 Fix sched v2 overflow bug (#5574)
f609f4248 Adding method Parent from Anki
dbf3c09d5 Decks#checkIntegrity
d402073fa Switch to okhttp for http connections, use TLS1.2 on API<=21 (#5658)
c8e69040a intNow to intTime
