### ISSUE TITLE
Investigate native crashes in Chrome WebView

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4967]
The vast majority of our crashes as reported in the google console are in native Chrome/WebView code where ACRA doesn't even get a chance to report the crash.

There is a lot of discussion easily available for each report via google searches, but it looks like it might be some sort of memory interaction (using too much memory) inside the WebView. Sometimes (allegedly) because of javascript implementation errors, sometimes not.

I'm not sure if this is fixable pre-2.9 but I would like to at least do a formal investigation by trying to create some cards that stress the WebView, dump the HTML and profile it since it represents such a large portion of our crashes

A good place to start might be with the Kanji fonts or Base64 images or similar as there are reports of the fonts being slow

**Comment by mikehardy** [comment]
Other crashes took the time I had for this one - postponing for now since it's exploratory

**Comment by tobia** [comment]
I can confirm that the Kanji font that I'm using makes the cards load *very* slowly (half a second on a Snapdragon 845 phone) and makes WebView crash every few hundreds cards, during the half-second lag. I'll send you a sample deck by email, because I can't post the font publicly.

**Comment by timrae** [comment]
Please see #5213 for the slow loading issue and note that we will not support your font. If you can reproduce the issue with Google Noto font then we will try to look into it

**Comment by tobia** [comment]
The slow loading is exactly the same with Noto as with my font. As for the crashes, I'll use Noto exclusively for a few days to see if they subside.

**Comment by mikehardy** [comment]
In an unrelated deep-dive into WebView crashes for another app/module, I've learned that there are WebView hooks we can use to at least instrument AnkiDroid and maybe gracefully handle crashes.

Specifically onLowMemory and isRenderProcessGone may be hooked, one to perhaps allow us to message to the user that whatever they are doing is stressing the WebView and they might want to alter cards to avoid it (onLowMemory) and the other (isRenderProcessGone) to gracefully handle a crash and perhaps send a bug report or analytics hit to track frequency plus message to the user the current card crashed, then give them the option to retry the card or suspend it / give it a special tag and move on or similar.

**Comment by mikehardy** [comment]
Tagging that this is actionable now per the comment above - there are a couple things a motivated person that wanted to try their hands at Java mobile development could do (at least overriding the methods and logging things) if someone was interested.

**Comment by david-allison-1** [comment]
Note: #5820 implements `onRenderProcessGone`, we do not yet handle `onLowMemory`.

**Comment by mikehardy** [comment]
Do you mean this? https://developer.android.com/reference/android/content/ComponentCallbacks2#onTrimMemory(int) (the recommended system callback for API>=14)

The question is, is it actionable? What would we actually do?

**Comment by david-allison-1** [comment]
I was quoting the API mentioned in https://github.com/ankidroid/Anki-Android/issues/4967#issuecomment-559098034. I haven't looked into the APIs yet.

IIRC, Anki Desktop resets the webview after a certain number of reviews.

We can do that, but we can probably do better: if we get a low memory signal, reset the WebView during the load of the next card, removing the need for handling the crashed process and showing the toast to the user.

**Comment by mikehardy** [comment]
Pre-emptive 🤔  I could see that I'm just not sure if it's an improvement. Same work/delay I think, but provably before you definitely need it, vs exactly every time you need it. There was some noise on stackoverflow that it wasn't even called frequently (there are no guarantees apparently?) prior to OOMs so it seems like it would add code for no real gain? Always possible I'm missing something important though and not thinking of it correctly

**Comment by david-allison-1** [comment]
I was going to answer, but I've talked myself into suggesting another PR to improve the fix further. Kicking myself for not doing it originally.

We currently display the question on a render failure, to ensure that we're in a good state.

If we change it to rendering the currently displayed side, possibly with some additional logic to fix the state, that'll make the crashing experience even better for the user.

**Comment by mikehardy** [comment]
I'm going to close this as I think they've been pretty thoroughly investigated (and mitigated!) now - will be released in 2.9.6
