### ISSUE TITLE
Refactor ACRALimiter data deletes with ACRA5.3

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4968]
The ACRA maintainer ingested my request for Limiter data clearing with a full implementation that handles clearing on app version change by default and allows an API clear as well.

We can delete code in our codebase by refactoring to that when 5.3.0 is released (whenever that is)

Set to low priority because there are no errors associated and I don't know their release schedule.

https://github.com/ACRA/acra/pull/696

**Comment by mikehardy** [comment]
Just to note that ACRA 5.3.x was released, so this refactor may proceed. It's should be pretty easy and I think I left a note in a comment in the code which should be in AnkiDroidApp.java if I remember correctly, this really is a good first issue

**Comment by david-allison-1** [comment]
Let's give this one more cycle. Good place to get started and has significant wins in terms of bug tracking

**Comment by mikehardy** [comment]
Here was the implementation sketch from the upstream work with ACRA maintainer

> Wow, that's the full capture / implementation of the idea - I'll use the API you mention in case a user toggles their reporting state (something that indicates they're purposefully wanting to log errors usually), but the deleteReportsOnAppUpdate and resetLimitsOnAppUpdate are also perfect and the true default is also the right direction I think. Chapeau, the next version will allow me to delete code in my codebase, my favorite thing.

The idea being that if a user specifically toggles crash reporting on it is usually because we asked for a report, and if they do an off/on cycle we should then send the next report even if we thought we already sent it - i.e., we should reset any limit in that case even if we are on the same app version

**Comment by mikehardy** [comment]
Here's the code link for an implementor, I think this would be a great first issue

https://github.com/ankidroid/Anki-Android/blob/81c6e2ef67bd669b1a29f190eeed99307ed086f3/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L343-L351
