### ISSUE TITLE
onSaveInstanceState() / lifecycle crashes

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4981]
I need to nail down the exact reproduction, but ACRA has a lot of these that go a little like this:

###### Reproduction Steps

1. Review cards
2. use System Picker to open an .apkg
3. ImportDialog tries to show 

###### Expected Result

ImportDialog shows fine and import happens

###### Actual Result

IllegalStateException because onSaveInstanceState was already called
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/c19d73c3-5d80-4122-b6b6-509f1b08df80

Also (a bit different but same lifecycle problem): https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/9e87f298-b1ca-4657-9732-d4dfa4573f8f

###### Research

Note that simply targeting P (API28) may fix this as it changes lifecycle in the support libraries for onSaveInstanceState to be after onStop so that Fragment transactions like this may proceed
https://developer.android.com/reference/android/app/Activity.html#onSaveInstanceState(android.os.Bundle)
```
If called, this method will occur after onStop() for applications targeting 
platforms starting with Build.VERSION_CODES.P. For applications targeting earlier 
platform versions this method will occur before onStop() and there are no 
guarantees about whether it will occur before or after onPause().
```

**Comment by mikehardy** [comment]
Other reading, for a pre-P solution:
https://www.androiddesignpatterns.com/2013/08/fragment-transaction-commit-state-loss.html

**Comment by mikehardy** [comment]
looked into this just a little today and I still am not sure how to reproduce but I have a rough (unchecked) sketch:
- review a bunch
- leave the app so screens go onPause() but maybe not onStop()
- open an apkg externally so ImportDialog tries to show

But really, this one is probably best left for after an analytics roll-out and API28 release so it's easy to pinpoint if it just goes away (as it might with the P changes)

**Comment by david-allison-1** [comment]
@mikehardy Not sure if we want this open. Useful to kill crash bugs, but the ACRA links have died, this could be a dupe of #5075

**Comment by mikehardy** [comment]
Yeah, as current AnkiDroid acralyzer (but after I first investigated) I now know that you have to purge reports periodically, so I know that the link is good but pasting the trace in is vital. Too late now. I think we have others that are tracking lifecycle issues, I'm going to close this
