### ISSUE TITLE
Burying and Suspending cards from the API

### ISSUE THREAD

**Issue by lucwastiaux** [ankidroid/Anki-Android#4986]
Doesn't look like this is currently supported, I wanted to confirm that's the case before digging into the code. Also before implementing code, is this a sort of enhancement which is likely to be accepted ?

###### Reproduction Steps

1. Noticed that the current ContentProvider API doesn't allow Burying or Suspending a card
2. 
3. 

###### Expected Result

Being able to bury or suspend a card from an external app.

###### Actual Result

Unable to do so

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by lucwastiaux** [comment]
I'm thinking of doing this way:

Going to add  **BURIED** and **SUSPENDED** fields on the **ReviewInfo** / **SCHEDULE** API endpoint here:
https://github.com/ankidroid/Anki-Android/blob/master/api/src/main/java/com/ichi2/anki/FlashCardsContract.java#L900

Those will be write-only fields. Then in the update code here https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/provider/CardContentProvider.java#L615

If either BURIED or SUSPENDED are set to 1, we won't go into the **answerCard** path, but instead go into **buryCard** or **suspendCard** (new functions) which will in turn call **Sched.buryCards** or **Sched.suspendCards**

**Comment by mikehardy** [comment]
Tim (who wrote the api) said he'd be out until Wednesday but this at least seems well thought out. Even if the feedback is to move the logic or repackage it I'm guessing it won't be traumatic if you wanted to get the calls working as proposed
