### ISSUE TITLE
[Feature Request] Adaptive Icon

### ISSUE THREAD

**Issue by rodrigoswz** [ankidroid/Anki-Android#4989]
Please, add an adaptive icon. Just it! :smile:

Thanks

More info: https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive
Adaptive icons | Android Developers

**Comment by mikehardy** [comment]
Pull requests with possible implementations #4798 and #4797 and #4854 

I want to get it done too, should be possible but aesthetics are hard in an open source / non-dictator environment

Duplicate of #4854
