### ISSUE TITLE
Anki2.1 - support javascript hooks

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4991]
I've been logging enhancements just to track Anki2.1 new features as I assume they'll be of interest to AnkiDroid users as well

This is to track the support for the new Javascript Hooks available for HTML modification in the 6 card display contexts (question and answer both for each of review, card layout, and preview)

https://apps.ankiweb.net/docs/addons.html#javascript-in-the-question-and-answer

Looks like it's something we could do pretty well since it's javascript so it won't have type-safety issues for AnkiDroid or language translation issues (Python to Javascript) like other plugin support items.

Not sure where the 6 javascript chunks would be stored, but if an add on that put them in to col.conf used the hooks it could actually be a cross-platform add-on

**Comment by mikehardy** [comment]
After working in this code more, I believe people could put the javascript files in the media folder so access would be cross-platform. I don't see any reason not to implement this, in other words, though it's not a high priority.

If anyone else wants to have a go, you're looking at "card.js" and "card_template.html" here: https://github.com/ankidroid/Anki-Android/tree/master/AnkiDroid/src/main/assets

And if you need to work in the Java code that prepares card_template.html you'll want the abstract viewer here https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java

**Comment by runiq** [comment]
So if I place e.g. `_reviewQuestionHook.js` into `collection.media`, the JS in that file would be executed:

- in the reviewer context only
- as soon as the question is visible
- for all card types

Is that about correct?

If so, this would still require explicit support from Anki (or a simple addon) and AnkiMobile to work across all platforms, right?

**Comment by david-allison-1** [comment]
Let's keep this open for another cycle, still on my long-term roadmap for what I'll want to implement.

**Comment by mikehardy** [comment]
@infinyte7 this might be right up your alley but went stale - it would be a cross-platform compatible way to modify card contents during display etc and now would have access to our javascript API (not cross-platform but maybe could become so...)

I think the natural next evolution of the whole javascript idea is to decide exactly where to put "reusable / applies all the time javascript code" so it is synced between devices but is well-defined in order to have good documentation on it

**Comment by infinyte7** [comment]
Yes, I am developing a deck that use all AnkiDroid JS api and also it compatible to Anki Desktop and AnkiMobile. I have user agent to hide all JS api on Desktop iOS.

For AnkiDesktop, I only find pycmd('ans') for mapping show answer.

**Comment by infinyte7** [comment]
For anyone curious about developing custom card design using AnkiDroid JS API.  
- https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API
- https://github.com/infinyte7/Anki-Custom-Card-Layout
