### ISSUE TITLE
Anki ecosystem: limit size of collections and media to same as desktop climit

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#4992]
Anki limits compressed collection uploads to 100MB and uncompressed to 250MB, with media in total unlimited but individual files less than 100MB each
https://anki.tenderapp.com/kb/anki-ecosystem/are-there-limits-on-file-sizes-on-ankiweb

https://github.com/dae/anki/blob/master/anki/sync.py#L545

Near as I can tell we apply no limits on our side, and probably should in the sync code

Should be investigated at the same time as the HTTP client change #3626 and Anki dynamic URL stuff #4921 along with connection reuse #4568 

I'm looking at this a little bit now because to do analytics for #4948 I'm using a library with OkHTTP (apparently the current best HttpClient for Java/Android) and could push OkHTTP out into the rest of the codebase at the same time maybe

@dae - I'm tagging you here not because I need feedback, rather just that these are your servers we hit and if I'm doing anything about changing our interaction with them I think it's better if you're aware - I'd like to avoid causing you any trouble

**Comment by dae** [comment]
cheers

**Comment by timrae** [comment]
> OkHTTP (apparently the current best HttpClient for Java/Android)

OkHTTP is an internal dependency of Android system... `HttpURLConnection` uses it internally. I think it's better to use the Android wrapper classes rather than OkHTTP directly unless there is a usage case addressed there which is not supported by the Android wrapper classes.

**Comment by mikehardy** [comment]
```OkHTTP is an internal dependency of Android system... HttpURLConnection uses it internally```

This is true, but OkHTTP wants to unhitch, leaving HttpURLConnection in the same place HttpClient based on the Apache beta code thing from Android 1.0 went - AOSP will end up with a forked version, and will eventually go unsupported:

http://square.github.io/okhttp/3.x/okhttp-urlconnection/deprecated-list.html

There may be the same risk of orphaning with a 3rd party library vs native, but with the Apache client supported across part of our version skew and unsupported on others, and then the same thing likely to happen in the future with HttpURLConnection, my thinking was similar to the requery/sqlite-android reasoning: at least with OkHttp we'll know we have one API across all APIs and we get to know it well vs per-API support reasoning

On the plus side, the OkHttp API is easy to work with and in my performance testing on [my clean analytics implementation from the PR](https://github.com/brsanthu/google-analytics-java/blob/1a5098823250ddf8be1b262b7e31f695fb4774cd/src/main/java/com/brsanthu/googleanalytics/httpclient/OkHttpClientImpl.java) it's default under-the-covers pool would mean we get connection reuse out of the box for syncing if the Syncer infrastructure is ported to it.

**Comment by dae** [comment]
Closed by #14171.
