### ISSUE TITLE
can't remove unused media

### ISSUE THREAD

**Issue by colorsakura** [ankidroid/Anki-Android#5005]
AnkiDroid Version = 2.9alpha37

Android Version = 6.0

ACRA UUID = 18a3cf26-80cc-447b-aed9-590bfd3a72e6

**Comment by mikehardy** [comment]
I am unable to reproduce this. 

I used the same tag and emulator API, I started the process of adding a note, and I took a couple pictures with the camera plus recorded some audio, then hit the back button to discard the new note. That orphans those photos and recordings, and I verified there were 3 media files there, but no notes in the database.

I then run check media, it tells me it saw the 3 unused files, and when I choose to delete them, they are successfully deleted from the device filesystem and no longer show up in the check media dialog

?

You can try deleting them manually from /sdcard/AnkiDroid/collection.media (though be careful), you can try syncing to Anki Web, deleting the app and /sdcard/AnkiDroid completely (take a good backup first!) and re-syncing, or if you want you could set up a development environment and follow the logcat output in AndroidStudio (or via adb) to see exactly what's happening. Everything looks good on this end

**Comment by bewuwy** [comment]
For me, after changing ankiweb account on ankidroid, the media from the old account tries to sync to ankiweb. Even after clearing the app's data.
