### ISSUE TITLE
Selecting "Card Browser" from Android system long-press-on-text-input context menu leaves you stuck in Card Browser

### ISSUE THREAD

**Issue by ps-goog** [ankidroid/Anki-Android#5016]
###### Reproduction Steps

1.  case
- select [Card browser] from main menu
- click any notes
- select any text in edited notes
- you should see local menu connected with selected text (copy, paste ...) and choose from this menu menuitem [Card browser]
- and you won't be able to back

2. The same problem is then you choose option [Card browser] from other application
- select any text inside any application
- you should see local menu connected with selected text (copy, paste ...) and choose from this menu menuitem [Card browser]
- and you won't be able to back

It's mean that maybe problem is in 'extension' [Card browser]

###### Expected Result
Closing card browser window

###### Actual Result
Infinite loop

###### Debug info
AnkiDroid Version = 2.9alpha40
Android Version = 8.0.0
ACRA UUID = dd27ecef-281f-411a-b121-c44b1ca1bdb7
I'm using Samsung galaxy Tab 3

###### Research
*Enter an [ x ] character to confirm the points below:*

[ X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
Hi, sorry those instructions don't make any sense to me from 1.4 onwards. Can you please make a video?

**Comment by ps-goog** [comment]
I use AnkiDroid everyday and I think it's rather error inside Anki because I've checked and I have this error on tablet and phone and there was no system update. There was a few updates within 2 last weeks and one of them spoilt it.

**Comment by mikehardy** [comment]
That's useful information, can you remember the last ankidro version this didn't happen? Even if it was just vague like, the stable version last month might help. We have changed user interface support library versions recently and knowing when it broke might pinpoint it

**Comment by ps-goog** [comment]
I'm beta tester so I install beta version very quickly.
I noticed error 4 October, so I think the error showed between beta 37 and beta 40

**Comment by ps-goog** [comment]
I've found some new code in beta 37, maybe there
 AnkiDroid/src/androidTest/java/com/ichi2/anki/uitests/CardBrowserPreviewUI.java
@@ -88,6 +96,40 @@ public void cardBrowserPreview3UI() throws Exception {

**Comment by mikehardy** [comment]
That's just part of my automated testing harness where I once I fix a bug the test then makes sure that it never happens again - it was in relation to a crash when accessing preview functionality from card browser. Your previous comments about dates could help me bisect more quickly though - I'm sure we'll get it. Thanks

**Comment by mikehardy** [comment]
And thanks (possibly again) by the way, for participating in the alpha program. I don't think we have many active users in there and it is a huge help to make sure we don't cause lots of people problems when we go from 2.8 -> 2.9

**Comment by mikehardy** [comment]
A workaround for this to escape the "card browser jail" is to drag the navigation out with a swipe from the left. From there you can go to other areas (like the deck picker) then resume reviewing. The behavior is still clearly in error, but this allows you to continue without killing ankidroid and restarting it

**Comment by ps-goog** [comment]
This is no workaround because you still return to the card browser, but I found workaround:
- first yours idea: to drag the navigation out with a swipe from the left
- From there you can go to SETTINGS
- back: returns to card browser
-another back: return to point when you invoked card browser

**Comment by mikehardy** [comment]
@ps-goog - thanks again for testing. I think this went out in the alpha that was literally just released, so you should get an update and this should be gone

**Comment by ps-goog** [comment]
There is another unnecessary step... - when I enter to card browser to search word from local menu it show searching result and BACK show all cards instead of closing card browser (to show all cards I can clear Search box and make search again)

**Comment by mikehardy** [comment]
This is true - we're out of the jail/infinite-loop now but I could look more closely at it so we pop the CardBrowser activity off the stack. The previous behavior was unexpected enough I wanted to get a focused fix out but I'll reopen this for further work

**Comment by david-allison-1** [comment]
I'd like to see this fixed, but it'll be hard to pin down when to say "let's not make back close the screen"
