### ISSUE TITLE
Deprecation - use new shouldOverrideUrlLoading() API in WebViewClient

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5017]
de-linting the codebase, AbstractFlashCardViewer installs a WebViewClient so we have to override parent methods, but we should convert to the new API here:
https://developer.android.com/reference/android/webkit/WebViewClient#shouldOverrideUrlLoading(android.webkit.WebView,%20android.webkit.WebResourceRequest)

**Comment by jgscherber** [comment]
The parameter for the new API, [WebResourceRequest](https://developer.android.com/reference/android/webkit/WebResourceRequest) was added in API level 21, but isn't our minimum version 15? Is that correct that it won't work?

Sorry if the question is silly. I have Java programming experience, but not much in Android.

**Comment by timrae** [comment]
@jgscherber

Sorry, I totally missed your question!
