### ISSUE TITLE
Deprecation - convert from ProgressDialog to ProgressBar

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5020]
De-linting the codebase and it looks like Material Design has concluded ProgressDialogs (modal) aren't acceptable at all, and recommends always having non-modal ProgressBars.

Possible workaround is to do an AlertDialog with progress inside it, or an alternative is to do a ProgressBar and disable touch while it is working, if it's truly modal (maybe ours is?) but I assume the old APIs will go away eventually, so we need to move.

**Comment by timrae** [comment]
Where do we still have use that? In most places we are using material dialogue library with a built in progress bar.

**Comment by mikehardy** [comment]
I tagged the depreciation suppression with the github issue ids so it's searchable

**Comment by mikehardy** [comment]
Tim mentions that for most places we use MaterialDialogs dialogs, so any of the progress dialog usage here could probably be converted to those

**Comment by mikehardy** [comment]
I think this is still open waiting on one more usage
