### ISSUE TITLE
Deprecation - refactor media API usage

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5022]
The media APIs have moved a little bit - so it's not a mechanical change. This one doesn't look too difficult but enough I'm not contemplating it in my main deprecation sweep

**Comment by ashwanikr7499** [comment]
@mikehardy  can you elaborate on this issue a little bit?

**Comment by ashwanikr7499** [comment]
Hi @mikehardy, can you elaborate on the (existing) issue a little bit?

**Comment by mikehardy** [comment]
Hi @ashwanikr7499 !
I have not thought too deeply about it. I noted it twice in code when sweeping for deprecation a while back

https://github.com/ankidroid/Anki-Android/blob/d1f7d09792e06c4b0548f600b14cc24dc7a953ba/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java#L290

and 

https://github.com/ankidroid/Anki-Android/blob/d1f7d09792e06c4b0548f600b14cc24dc7a953ba/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java#L455

My comment from long long ago makes me think that a quick look at the APIs we are using, vs the ones that are recommended, and a proposal that shows which APIs currently in use (with links to docs) would map to which new APIs (with docs) might be good enough

The harder part will be if the new API has a bunch of really great functionality that we could expose, then...should we? If so, how? I'm not familiar with the MediaPlayer APIs, so I would just look and see what you think, and maybe we expand AnkiDroid's media player power in a future PR if it makes sense

Also, if the new APIs are only available in an API higher than 21, we still have to support API21, at which point you'll need to add something to the CompatV21.java object and Compat interface in the compat tree that is a baseline implementation with an API that all Android versions can use, and in the first Android version where the new APIs are available, (for example just for discussion, if it is API26) you would add the new non-deprecated implementation to CompatV26.java, then in the code you use CompatHelper to get the right Compat object for the feature, and call your API.

Does that make sense?
