### ISSUE TITLE
Android lint task hiding real problems - needs audit

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5026]
build.gradle:lintOptions:abortOnError is set to false right now, which I don't always disagree with but right now it appears to be hiding some legitimate issues, this is just an example:

```
Error: Incorrect formatting string delete_card_message; missing conversion character in '% s' ? [StringFormatInvalid]
    <string name="delete_card_message">Hapus semua kartu dari catatan ini? \ n Bidang pencarian: % s</string>
```

Not ready to work through lint issues at the moment but I don't want to forget about them...

**Comment by david-allison-1** [comment]
This needs to be looked into in further detail. I occasionally get linting errors, and these are likely to reflect crash bugs in other locales.

**Comment by david-allison-1** [comment]
We can significantly improve this now # and # are in.

I'd like to add: `StringFormatInvalid` and `StringFormatCount`

**Comment by david-allison-1** [comment]
@mikehardy Anything more you feel that we need on this issue?

**Comment by mikehardy** [comment]
No - we have made an impressive amount of progress in this area since I logged this issue almost 2 years ago :sweat_smile: - with all sorts of machinery in place to allow lint to be a real thing now, I don't see the need for this specific issue. There will always be the background task of "take the lintDebug file and slowly feed it into lintRelease" but that's not really actionable. So -> close
