### ISSUE TITLE
Path to media files

### ISSUE THREAD

**Issue by ps-goog** [ankidroid/Anki-Android#5028]
###### Reproduction Steps
New issue, add path to the media files
I have a lot of media files 5GB and often change phone and tablet and use phone and tables simultaneously and of course I have only one collection and synchronise data.
I put all media files in sdcard but name of card is different in every devise so I have media only in one device it run because
In settings I have directory set to: /sdcard/AnkiDroid
And in cards for example:
[sound:../../../../../storage/3B47-3E41/Anki/dir1/sound.mp3]
3B47-3E41 is name of SD card different in every device

###### Expected Result
Add setting path to media, in my example
/storage/3B47-3E41/Anki
And in card there will be
[sound:/dir1//sound.mp3]

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hmm possible enhancement though - why not use symlinks? If you already syncing at the filesystem level (outside of Anki) it seems like you could put symlinks in there to present a consistent path to anki? Or does AnkiDroid not respect symbolic links? https://android.stackexchange.com/questions/4044/is-possible-to-make-symbolic-links-in-the-android-filesystem-and-how

**Comment by ps-goog** [comment]
I'm using AnkiDroid synchronisation but without synchronisation media files. 
When it was changed (different name of sd card in OS, Android 6?) i tried to find solution and didn't.
All my cards are generated so I rebuilt decks with new path when I change phone and make full synchronisation without media because I also put old SD card to new phone.
The only problem is I can listen to media only on one device.
I have no rooted device. For me it's easy to enter valid path in AnkiDroid than poke in OS.

**Comment by mikehardy** [comment]
symlinks don't require root, they are easy to do
every feature we add to AnkiDroid is a burden on future maintenance and user expectations (with nearly 1 million users...) so if we can avoid adding features that not many people use, we usually do.
Please try creating a symbolic link - I think you will be surprised how easy it is

**Comment by ps-goog** [comment]
I haven't tried yet. I have got everything already organised in my Anki so I don't need to test it and because my cards are generating the is no problem to put new media's path.
It would easy for me to test new features in Ankidroid if you attach description about changes in new version.

**Comment by mikehardy** [comment]
I'm going to close this as it's an enhancement with multiple workarounds it seems - but we can point people here if they are interested and if it gets a lot of interest we can always re-open and accept pull requests
