### ISSUE TITLE
Tag desired events in analytics

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5041]
I'll wait to implement these until we have a good list, but here's the place to put  your "I wish I knew xxx about usage..." requests.

Starting out:

- how many people have X feature enabled? (any specific features? TTS? dictionary lookup? API being used? non-system-language?)
- how long do syncs take?
- how long is the average reviewing session?
- how many acra crash reports do we get vs google crashes?

I'll collect more, please add your own in comments below

**Comment by mikehardy** [comment]
I'd love to compare package names and see who is using parallel builds

**Comment by mikehardy** [comment]
API usage - would be great to know if / when people are using it

**Comment by mikehardy** [comment]
ACRA crash handler is coming through as an "event" instead of a crash or exception, for some reason?

**Comment by mikehardy** [comment]
The user-agent override is important and we can use it to tag device info, right now it's all coming from "desktop" but if we do it right we can know tablet vs mobile, and screen dimensions etc

**Comment by mikehardy** [comment]
Would be great to know collection sizes, and the size of the unbounded data where that's possible (e.g., how many people actually stuffing huge JS bundles into the Anki system? how big are they?)

**Comment by mikehardy** [comment]
It is apparently possible to crash a WebView if you feed it source data that is huge, and force it to resize, and the crash probability varies based on decoders etc. Would be interesting to tag who is using custom CSS (as this would change our view of whether our own CSS was a statistically reliable predictor of how things rendered), and how big individual images were

**Comment by david-allison-1** [comment]
I'll edit this post as I think of more. I love metrics.

**Code**
* Lint Errors
* Test Coverage

**Speed**
* Initial load/Collection Size
* Time to show a card (mean & max)
* Time to sync
* Time to display first string in card browser
* Deck Import time/Deck Size

**Count**
* Crashes
* ANRs
* Decks Imported
* Cards Added
* Cards Reviewed in one session
* Decks
* Models
* App opens per day
* Max Media/Fonts per card
* Number of Words in card


**Size**
* Collection
* #Media Files
* Sync Size

**Features**
* Whiteboard
* Sync
* Gestures
* Game Controller usage
* \LaTeX
* Dark Mode
* Chess
* Lookup
* Stats
* Filtered Decks
* Cloze
* Advanced Editor (recording, camera)
* Notification Service Usage
* Advanced Advanced Editor (Pronunciation Etc..)

**User Awareness**
* Have they read the manual/help
* Do they know we're open source etc..
* If international, did they know they can help translate?
* AnkiDroid isn't run by the same people as the rest of the ecosystem
* Anki exists
* User's own evaluation of their knowledge about AnkiDroid's features
* Beta Program

**Comment by mikehardy** [comment]
Removing from milestones as I don't think this is really actionable it is more of an umbrella I imagine a lot of PRs will link to.

I just added some fresh information #6492  so you can see the pattern on how to add dimensions to every hit. 

Adding some timing hit infrastructure and then doing some timing hits as mentioned above would be interesting, especially in combination with a custom dimension on collection size

Analytics has some support for "ecommerce hits", like purchase of certain items, it could be interesting to consider the use of any feature, awareness of anything or participation in anything (like the list above) to be an "item purchase" and log it like so as an async hit on startup.

**Comment by david-allison-1** [comment]
I normally write my timing tests in `Closable`s, as it abstracts away dealing with the timing aspect (which makes it pretty much 0-cost and bug-free)

I'm not sure if this is possible in Android (try with resources works, but I previously got an API warning if trying to implement closable), I'll need to look into this later
