### ISSUE TITLE
Discussion: anki plugin apps / enhanced reviewer integration

### ISSUE THREAD

**Issue by lucwastiaux** [ankidroid/Anki-Android#5046]
I wanted to continue the discussions from #4833 and  #4832. The app i'm working on is an enhanced reviewer which makes use of a lot of animations and improved TextView-based (not WebView) layout. You can see a demo of it here: https://imgur.com/2o2BhA5 . I hope to share a working version soon, but before that I need to work on a style/layout editor for cards. 

@timrae has generously offered to provide the app special visibility inside AnkiDroid by having a sort of plugin system which points to other apps in the play store, and I can help with code there.

@mikehardy also pointed out we could have a "review deck" intent which allows the user to select a different anki reviewer, that also sounds like a good idea and I can also work on some code changes in AnkiDroid when my app is ready for that.

The first step will be releasing the app standalone (and for that I need to wait for the API changes in #4986 to go live). The changes above can go in after that.

That being said, the naming of the app is something that may stick, so I wanted to get it right. The working name I have is "AnkiReview". and I thought the long title on the play store could have the ".. for AnkiDroid" suffix. I'm thinking of the following alternative names:

- "Enhanced Reviewer for AnkiDroid"
- "Cards for AnkiDroid"
- "AnkiSwipe"
Any other suggestions ?

I'm not good at finding names >_<

Also, can I use an icon which is clearly reminiscent of AnkiDroid ?

**Comment by mikehardy** [comment]
I don't see anything wrong with short-and-sweet "AnkiReview" personally. I don't feel like I've been working in the project long enough to carry any weight w.r.t. branding but just as a possible user, if the logo didn't have the blue star with white outline I'd wonder why not. And tenure or not on the other side - as a developer the more it's like a family of open source apps the more I like it. Would be nice to have an ecosystem around the primary syncing / scheduling / system-of-record functionality AnkiDroid can provide

**Comment by lucwastiaux** [comment]
I've released a beta of the app: https://play.google.com/store/apps/details?id=com.luc.ankireview

**Comment by mikehardy** [comment]
Cool - will be interesting to see how people like it

**Comment by lucwastiaux** [comment]
Here's an article with screenshots on the built-in style editor: https://medium.com/@lucw/learn-chinese-with-ankireview-e748bed4b196

**Comment by lucwastiaux** [comment]
As of the latest version, AnkiReview now supports Anki HTML/CSS templates: https://medium.com/@lucw/ankireview-now-supports-anki-templates-b146c88f4ac3
