### ISSUE TITLE
Cards isn't save when other is save in card browser

### ISSUE THREAD

**Issue by ps-goog** [ankidroid/Anki-Android#5058]
###### Reproduction Steps
Tablet sg tab3
1. Select any deck
2. Choose learn now (when you start Anki you have to kick deck twice to see this button, is v the second mistake)
3. Edit showed card X and change any text inside card
4. Select any text
5. From local menu choose card browser
6. Select any card in card browser and edit if
7. Change during and save card
8. Back to card X and save it
Card X isn't saved

###### Expected Result
Each save command save card

###### Actual Result
Not save if was save in other place -

###### Debug info
AnkiDroid Version = 2.9alpha46
Android Version = 8.0.0
ACRA UUID = dd27ecef-281f-411a-b121-c44b1ca1bdb7

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I haven't tried to reproduce, but I bet the edit was actually saved to the database and if you restart the application you will see the edit. If that hunch is correct, it's actually a "card browser did not reload" problem, and really it's that the card browser should be unique on the device - there are ways to tell the system to only ever run one of a given activity, and maybe that's not done, or not working in this case

**Comment by ps-goog** [comment]
I've tested it again and it happens not each time.
Close Anki and play my scenerio again.
I've checked and changes in card X aren't saved after restarting Anki.
Make sure that there are too different  modified cards X edit from deck and the second edit from card browser which is called fun X

**Comment by mikehardy** [comment]
@ps-goog sorry for the delay on the issues you've found so far. I'm nearly done with the new functionality for the 2.9 release and will have time to triage through them soon I hope. I really appreciate the testing you've done so far though, thank you!

**Comment by david-allison-1** [comment]
Let's keep this one open for another cycle. Still needs reproduction

**Comment by david-allison-1** [comment]
I think this may be caused by the fact that only the card refreshed, rather than the note after editing.

I have an inkling that this was fixed by @Arthur-Milchior a couple months back, but should be easy to reproduce

**Comment by Arthur-Milchior** [comment]
No idea when i’d have corrected it. Maybe the editor had a static member for the card, and it assumed a single editor was opened, which would be the probblem’s cause. It rings a bell
