### ISSUE TITLE
can't switch language in android 8.1 :(

### ISSUE THREAD

**Issue by st603** [ankidroid/Anki-Android#5059]
###### Reproduction Steps

1. >Sittings
2. >General settings > Language 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
This is a known issue as the Android APIs moved underneath us in the current APIs. Hoping to resolve for 2.9 in the meantime only workaround is to change your system language to change AnkiDroid interface language #4729
