### ISSUE TITLE
Expand Stats / StatsProvider with more information

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5062]
This is an enhancement request for greater stats access now that we have a stats provider:

There was discussion on the mailing list about the data itself:

https://groups.google.com/d/msgid/anki-android/e4d6b2d7-f2c7-4e73-a2f7-3b1b321da0a8%40googlegroups.com

And there was a separate request related here:
#4773

**Comment by adamwolf** [comment]
Maybe also https://github.com/ankidroid/Anki-Android/issues/5266

**Comment by david-allison-1** [comment]
Still useful - let's keep it open

**Comment by mikehardy** [comment]
StatsProvider also has some related work unmerged for the "sample app" - would be nice to open stats to external users in general, and or WebView javascript. Probably best to focus on the plumbing (access to the most general stats possible, in some way that's available to others - that is API and Javascript) so others can do anything and we can just close all the issues
