### ISSUE TITLE
Allow user to configure response for "automatically display next question" feature

### ISSUE THREAD

**Issue by marcoslcosta** [ankidroid/Anki-Android#5066]
Today, the automatic answer is always the red button.
I'd like to suggest this feature if it haven't exist yet. 

When the user set the automatic answer to display after x seconds, and, after that, folowing to next question after other x seconds, in that step, the anki always select the "red button" and it don't have how to set to another button, like "green button" as I'd like to.

**Comment by mikehardy** [comment]
Turns out this is a duplicate of #2609
