### ISSUE TITLE
Graves table almost never cleared, leads to database bloat

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5070]
###### Reproduction Steps

1. Import a very large collection on an emulator that is not associated with ankiweb
2. Delete the collection so there are no cards and check database / check media
3. Check the size of the database

###### Expected Result

Database is tiny, a few kilobytes

###### Actual Result

Database is still large (from my test, 20MB, exhausting the space on my emulator with backups and such...)

What's happening is that we are vacuuming correctly, but the only place the "graves" table is cleared that I can see is in "Collection.beforeUpload()" (called from FullSyncer on full upload)

I checked the anki python code and it appears that on normal sync, the graves table is synchronized but never deleted from? So I'm not sure there's any mechanism to ever clear this table.

Is that intended?

Seems that if there is no synchronization we could at least offer a mechanism to clear graves. Its possible this would be okay by default but we would need to take care on the interaction with an imported collection that was then modified with card deletes and then attached to an account and synchronized.

**Comment by timrae** [comment]
> Is that intended?

Sounds like a question for @dae

**Comment by dae** [comment]
Discarding graves without a full sync could result in a client that has not been synced in a while bringing back cards that the user had deliberately deleted when it is next synced.
