### ISSUE TITLE
Feature request: ePaper friendly settings

### ISSUE THREAD

**Issue by dpurge** [ankidroid/Anki-Android#5077]
I have installed AnkiDroid on ePaper device BoYue Likebook Mars. From a quick try, it seems to be working well, but does not look good because of missing colors on ePaper display.

You may consider adding a settings option that would make AnkiDroid more friendly for ePaper devices:

- skip animations
- use only greyscale colors in the interface (preferably just black and white)

Thank you for the application :)

**Comment by mikehardy** [comment]
Have you looked in the preferences? This should exist already

**Comment by dpurge** [comment]
Hi Mike, after your comment I changed to the plain theme on the phone and on the book. Indeed it is the option I  have asked for. I think the plain theme is more readable on the phone than on the eReader (white letters on the grey background ) and since it is more responsive phone is more convenient; I think I'll continue to use phone for Anki, and use use it on the eReader only as backup. 
Thank you for responding, I should have checked settings better before submitting this request.

**Comment by mikehardy** [comment]
That's good to hear - I'm relatively new to the project so I'm never 100% sure I understand the features that aren't used as commonly. Responsiveness for review speed is my main determinant as well so I wouldn't use e-ink devices normally, but yeah - good backup. Not many people use e-ink devices and even fewer are familiar with github to log issues, but we do intend to support them so if you run into other issues (like an animation showing up on e-ink - something we attempt to turn off everywhere), please let us know
