### ISSUE TITLE
Travis CI - only attempt coverage report upload if not a PR

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5080]
###### Reproduction Steps

1. Submit a PR
2. Watch the build on travis
3. Examine [the coverage report upload to codacy step](https://travis-ci.org/ankidroid/Anki-Android/jobs/446799661#L2561)

###### Expected Result

For PRs there is no API token (it is not secure for Travis to load secure tokens) so coverage upload to codacy should be skipped entirely - no resource wget fetch, etc

###### Actual Result

Coverage upload is attempted and fails due to the missing token

**Comment by mikehardy** [comment]
Marking this as a good first issue because anyone that does this will gain a lot of familiarity with Travis after this. Note that you can (and should, if you want to develop on AnkiDroid a lot) set up your own Travis to check your work prior to even making a pull request, like so: https://travis-ci.com/mikehardy/Anki-Android/branches

You can do the same with Codacy: https://app.codacy.com/project/mikehardy/Anki-Android/dashboard

The combination of the 3 items (your personal AnkiDroid fork on github, a Travis hooked to your fork, and a Codacy hooked to your fork) does a fair job of ensuring you don't even submit a PR until the code is at the level where you'll have real discussions on the logic instead of about nitpicky issues

**Comment by timrae** [comment]
I thought Travis only gets triggered on PRs... What's a non-PR and what is
the purpose of the coverage report upload?

**Comment by mikehardy** [comment]
Travis is triggered on any commit to the main repository (master and all other branches), and on any incoming pull request. It's a security problem to expose credentials in pull requests since people could request a pull of arbitrary code, thus all credentials are reserved for builds from the main repo. Similarly, codacy is triggered on any PR and on any commit to master - it can do other branches but does only the "default branch" by default.

The purpose of the coverage report is the same as the code style checks in general - the coverage report shows whether there's any automated scaffolding exercising code you're curious about, line by line (and in aggregate at method, object, package, and codebase level) and (most usefully for me personally) if you're doing maintenance / refactoring gives you a sense of whether there's any net under you while you're making cross-cutting changes (like a requery update, or the API27 thing etc)

**Comment by mikehardy** [comment]
Also worth noting that the codacy integration with Travis for coverage specifically is non-blocking - I didn't want two 3rd party services tied together and multiplying any unreliability - so though I think coverage is useful, in our process it's just a "best effort" integration - nothing in our builds depend on it to succeed.
