### ISSUE TITLE
TTS Enhancements - TTS-disable tag, speed/pitch setting abilities

### ISSUE THREAD

**Issue by tico-tico** [ankidroid/Anki-Android#5085]
(Forum thread https://groups.google.com/forum/#!topic/anki-android/4GH9yLRrsLk)

Hi. 

Since we have support for the tts tag in AnkiDroid 2.9+ i'm looking for a proper way to disable TTS language selection prompt (and TTS engine init!) to complete the picture.
Maybe we need something like `<tts service=android voice=disabled />`? Or we need more tts options, smth like ”Disable tts”, "Enable tts only for the tts tag", "Enable tts for everything, show prompts if no tts tag specified"? For me the tag-way is preferred because it doesn't required any app config changes (think about shared decks).

I doubt I will be able to implement any solution myself since I know almost nothing about java.

**Comment by tico-tico** [comment]
Suggestions from the forum user **axel.m...@gmail.com**:

> I don't use version 2.9 yet but as a natural behaviour I would expect that: 
> 1) TTS is always playing when I'm using the tts tag, no need for the user to turn it on in the settings 
> 2) a "disable TTS" setting let's users disable TTS, in case they are using a shared deck with tts tags and don't want to change the note template 
> 3) the language selection prompt does NOT show up when I'm using a tts tag (all needed information about language and voice is already there) 
> 4) the language selection prompt only shows up when I'm not using tts tags but a setting for "use TTS to read aloud all card contents" is turned on

**Comment by mikehardy** [comment]
Hey @p4nix - I didn't realize we had a gap in features here between desktop and android, if that's the case can you open a specific issue that is just for the feature gap, ideally with an example card text etc? Then I can mark it as an ecosystem compatibility thing and it won't get mixed up with separate enhancements - I prioritize compatibility much more highly than non-ecosystem features
