### ISSUE TITLE
Icon visual identification for alpha and beta releases

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5102]
###### Reproduction Steps

1. Sign up for the alpha or beta builds
2. Examine the icon for the app and for the widget
3. 

###### Expected Result

For regular builds I think the star is supposed to be blue?
For beta builds I think the icons are expected to be some other color?
For alpha builds I think the icons are expected to be red?

Basically there should be some obvious indicator if it is beta or alpha

###### Actual Result

Right now I have a red widget as an alpha install, but a blue star for the app icon, and I'm not sure what all the colors are supposed to be

Fairly certain this used to work and is a regression during the #5033 adaptive icon PR. I'll fix it as a low priority if someone could add the desired colors here for my information. 

Alternatively (and I like this better actually) we could do a little 'alpha' and 'beta' app sash like this: https://github.com/HazAT/badge (that's the official badger for fastlane, which is the current favored way to automate deployments for app developers according to the internets). I especially like putting the version on alpha or beta so people can see it moving - maybe keep the motivation up for the folks who have already got demonstrated some testing motivation

Also I think they use to be svgs but now they are pngs. Could maybe some some APK weight if they were svgs, I think?

**Comment by timrae** [comment]
It's something we did on a whim once after someone made a red icon. It's not really necessary or important, and some people didn't even like it. I don't think it's ever been working for the AnkiDroid 2.5+ main icon, and I'm fine with that, but you should be able to find the old red icon at least in the docs/graphics folder

**Comment by mikehardy** [comment]
It's definitely still there in the widget! :-). Okay, super low priority then. I'm working up Fastlane deployment on a separate project, and I'll badge my icons there. Some months from me that means I may be competent enough to trivially badge them with little "beta" and "alpha" banners here as a test - which should avoid the "you're using red / you're not using red" discussion that I saw related to it here...
