### ISSUE TITLE
Button text label is smaller than other elements and justified to top

### ISSUE THREAD

**Issue by ps-goog** [ankidroid/Anki-Android#5105]
###### Reproduction Steps
As in image and subject
![smartselect_20181107-070131_ankidroid](https://user-images.githubusercontent.com/43900825/48113530-8d942e00-e25b-11e8-8c03-d86b8de837a9.jpg)

###### Expected Result
Text should be centred horizontal and vertical and text shots be bigger

###### Actual Result
As in image and subject

###### Debug info
AnkiDroid Version = 2.9alpha50
Android Version = 8.0.0
ACRA UUID = dd27ecef-281f-411a-b121-c44b1ca1bdb7

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Yes! I just fixed this with #5104 and Tim logged it this morning as #5099. It's really obvious on a big screen...Do try to check the new issues before you log things but I continue to appreciate your testing and I'd rather have duplicates than no reports of real issues - I haven't fixed all the bugs you've logged yet and I'm sure you'll find more. Thanks

**Comment by ps-goog** [comment]
I'm sorry, I don't have time to analyse if my issue is a duplicate. I have got the same problem with my system and decided to merge duplicated issues myself because it's more important to get feedbacks instead not.

**Comment by mikehardy** [comment]
I'm okay with that - I feel the same way about more feedback than not, especially since you are testing our freshest code
