### ISSUE TITLE
Switch from 'collection.apkg' to new '*.colpkg'

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#5107]
###### Reproduction Steps

1. Export a collection  --> default name is "collection.apkg"
2. Choose save to file option
3. Choose a non-default name for the file
4. Import it

###### Expected Result
AnkiDroid recognizes it as a collection rather than a deck

###### Actual Result
AnkiDroid follows anki desktop behavior of expecting it to be called exactly "collection.apkg" in order to be recognized as a collection.

###### Possible solutions
We could change the UI to use `ACTION_OPEN_DOCUMENT_TREE` for collections to get a directory to save the file instead of allowing the user to specify the directory and filename, but then we have to show an overwrite confirmation dialog as well, and not let them store multiple collection backups in a single directory.

Rather than perpetuating this unintuitive design, I'd prefer for us to implement an idea I previously suggested to @dae quite sometime ago where we introduce a new file extension / mime type to the anki ecosystem for collections (e.g. call it `*.apkgc` or `*.acol`) instead of requiring those files to be called "collection.apkg", and we solve a bunch of UX problems.

@dae would you be willing to proceed with adding support for this to the non-AnkiDroid clients within a timeframe of say 1 - 2 months?

**Comment by dae** [comment]
It's been available for over a year: https://github.com/dae/anki/commit/0c80b5454fe8d163d2b6c86127cd8dac8cc7ecf5

**Comment by timrae** [comment]
Thanks! It's a much bigger diff than I expected, are there any other behavioral changes to be aware of there?

**Comment by dae** [comment]
The code is not fresh in my memory, but I can't recall anything in particular that you need to be careful about.
