### ISSUE TITLE
Audio Not Playing from Particular Deck

### ISSUE THREAD

**Issue by richardKafati** [ankidroid/Anki-Android#5109]
###### Reproduction Steps
I can provided .apkg file if request.

###### Expected Result
Audio to play from this deck.

###### Actual Result
Audio is not playing from a particular deck.

Audio files exist in Collection.media and I am able to play them with a different media player.

Audio plays from a new manually recorded card I created in a new deck.

I tried activating TTS and when I clicked on the deck Anki crashed, whereas another deck with audio (setup with a hook to different app for the audio file) didn't crash and just said TTS unavailable since there's already audio which played without a problem.

Audio plays in the web version of Anki.

I tried deleting the Ankidroid folder, uninstalling and resyncing from the cloud, still doesn't work.

**Comment by mikehardy** [comment]
Hmm - it looks like you've worked pretty hard to get around this, and you included most of the information we need. Could you attach the collection, ideally with information on how to search for the card that has the problem? Also, what AnkiDroid version and Android version do you have? Thanks in advance - hopefully we can figure it out

**Comment by mikehardy** [comment]
Oh, github will not take .apkg files, even though they are really just zip formatted files. You'll have to rename it to something .zip to upload it here but we'll be able to handle the renaming etc

**Comment by richardKafati** [comment]
> Hmm - it looks like you've worked pretty hard to get around this, and you included most of the information we need. Could you attach the collection, ideally with information on how to search for the card that has the problem? Also, what AnkiDroid version and Android version do you have? Thanks in advance - hopefully we can figure it out

In order to create the collection file do I download the desktop version, sync it to the server and then export it?

**Comment by richardKafati** [comment]
> Hmm - it looks like you've worked pretty hard to get around this, and you included most of the information we need. Could you attach the collection, ideally with information on how to search for the card that has the problem? Also, what AnkiDroid version and Android version do you have? Thanks in advance - hopefully we can figure it out

Collection: https://drive.google.com/file/d/1nhgIYCVBs5-KV051KWF_5kNCrVu7JfPj/view?usp=drivesdk.    (Not sure how to upload it here; 170MB)
Problem Deck: SpoonFedChinese
Android: 8.1
Anki I guess is 2.8 (says the help manual), it's the latest downloaded from the playstore, I also tried the latest alpha from a couple days ago and had the same problem.
Blah deck is manually recorded card deck

**Comment by mikehardy** [comment]
Wow that is a huge deck :-), but I can pull it down. Latest from playstore is either 2.8.4 or 2.8.5-beta1 but they are very similar, and knowing you tried the alpha let's me know that this will probably be possible to reproduce

I just want to be sure - you indicate `Blah deck is the manually recorded deck`

- is the blah deck the one that works? that you recorded in AnkiDroid and plays?
- do you have some search I can type into Card Browser while searching on All Decks that will bring up a card that definitely plays on Anki Desktop but does not play in AnkiDroid?

That last one is the most important - it will likely show the problem...

Thanks again for taking the time to work through this, if it's just your deck at least we can fix your problem, and if it's a problem in the software we may be able to fix something for everyone. Cheers

**Comment by mikehardy** [comment]
Thanks for the extra information - it takes me a couple days to reproduce things sometimes so please have patience but I will give it a try next chance I get

**Comment by richardKafati** [comment]
> Thanks for the extra information - it takes me a couple days to reproduce things sometimes so please have patience but I will give it a try next chance I get

Thanks Mike, I'd appreciate it.

**Comment by richardKafati** [comment]
@mikehardy Hey Mike, is there any status on this? Thanks.

**Comment by mikehardy** [comment]
Sorry it has been so long - believe it or not it is near the top of my list but my startup had a competition yesterday (we won, for what it's worth) so I haven't been able to prioritize it. You have provided all the information that I need though - I'm just sorry I haven't had time yet

**Comment by richardKafati** [comment]
@mikehardy Hey Mike, is there a timeline by when by when this might get looked at? Thank you.

**Comment by mikehardy** [comment]
@richardKafati unfortunately no, I'm sorry about that. My startup won a contract after winning the competition which means we actually have to have an app that works (what a surprise, right? haha) so I've been pouring all my time into it. This is still tagged as needs-triage which means it's in the short list of things to look at, but I can't make a promise on timing - sorry
