### ISSUE TITLE
Improved adaptive icon proposal

### ISSUE THREAD

**Issue by martindisch** [ankidroid/Anki-Android#5110]
I haven't been too happy with the way the Icon looks right now, compared to other apps.

![1 anki-old_small](https://user-images.githubusercontent.com/5547518/48252328-c7546880-e404-11e8-95be-f584ed1326c3.png)

Part of the problem is that the shape that's supposed to represent a flashcard requires an additional background, which is a neutral white right now.
So I took the previous SVG, cleaned it up (SVGs generated by Illustrator are quite the mess) and turned it into a square version without the shape, but maintaining all other elements exactly the way they were.

![anki svg](https://user-images.githubusercontent.com/5547518/48252504-392cb200-e405-11e8-90a6-7f3dd83f22c7.png)

As an adaptive icon, it looks like this.

![2 anki-new_small](https://user-images.githubusercontent.com/5547518/48252523-4cd81880-e405-11e8-9275-581f92c53914.png)

Because I thought some people would dislike the cut-off star, I reduced the star size and moved it a bit.

![3 anki-star_small](https://user-images.githubusercontent.com/5547518/48252583-74c77c00-e405-11e8-81e1-1bf6593ef941.png)

That's fine, but unfortunately the square version, which would still be visible in many launchers and possibly Google Play, doesn't look as attractive anymore in my opinion, because the star seems too small now.

![anki_star svg](https://user-images.githubusercontent.com/5547518/48252706-b2c4a000-e405-11e8-9ff9-55807589ebf3.png)

The people I've asked so far actually seemed to prefer the first (unmodified) version with the cut-off star, because it makes the whole thing a bit more visually interesting and dynamic.

What do you think, does something like this have a chance of getting merged?

**Comment by mikehardy** [comment]
The current one is a pretty weak effort, and I say that as the one that did it ;-)

@cydia2020 proposed a few and they looked like your proposal already, they were not accepted (yet) but if you search the issues and PRs here for "adaptive" you'll see the previous effort.

Everyone has an opinion on looks but I prefer my current (admittedly weak) effort over this just for the reason that I feel like the idea of a question and answer (a "flash card") is lost without either the shape drawing your eye to the two colors of "text lines" or maybe making those stand out more and be a very defined front and back. That said, the star is there which is the signal of Anki ecosystem identity.

Once you've read the other PRs and issues related to Adaptive icons chime in here again with how you think you'd evolve this - we are *definitely* open to suggestion

**Comment by martindisch** [comment]
I probably should have mentioned that I'm aware of the other efforts, but they seem pretty much stalled to me (also I'm personally not a fan of the two-tone background).
I was hoping this would gain more approval since it's about as faithful to the original as possible (at least the first one, with no modifications apart from losing the shape and turning it into a full background).

Anyway, thanks for your input. I'll leave this open for a few days to see if there's some more opinions and close it if there's no interest.

**Comment by cydia2020** [comment]
(Icon of ANZ)
![image](https://user-images.githubusercontent.com/12470297/48266417-69b33100-e483-11e8-92d1-bfe01d81c4a5.png)

I was aiming for something like this, but I am no icon designer nor illustrator user.

**Comment by mikehardy** [comment]
Maybe killing the gradient on the background and making the text lines pop more would maintain the question/answer identity while letting the monolith diffuse into just a general background? Flashcards aren't about gradients as an identity anyway. Note the other two icons distill the whole idea of the app into the icon - a place marker, an idea lightbulb. The star for Anki marks ecosystem identity but we are a flashcard app, so it really needs to have the idea of flashcards in my opinion. But the problem may just be that none of us are really designers, unless you are :-), then only one of us...

**Comment by martindisch** [comment]
Unfortunately I'm nowhere near being a designer either :sweat_smile: 
Simplifying the original in a text editor is about the extent of my abilities in that regard. Although I could probably manage what you proposed. I'll give it a try when I get home.
Do you have any opinions on the placement of the star? I love the original icon, so I don't really want to move it unless people dislike it being cut off in the round version.

**Comment by mikehardy** [comment]
I personally don't like it cut-off, and when I converted it to Adaptive I moved it just a little, as you did in one of your versions, so it wouldn't get chopped.

**Comment by martindisch** [comment]
Well, here it is—the version without gradient and more opaque text lines.

![complete_anki_star_new](https://user-images.githubusercontent.com/5547518/48277622-79af1e80-e44b-11e8-9116-f35d1c046cfc.png)

Since it seems a bit harsh to my eyes, another version with the same opacity of the text, but with the gradient still in the background, softening everything a bit.

![complete_ank_star_subtle](https://user-images.githubusercontent.com/5547518/48277666-9cd9ce00-e44b-11e8-84f9-493e1689cb14.png)

I'm really fine with both, though I prefer the one that still has the gradient. Keeps a bit more of the familiarity with the original icon.

**Comment by mikehardy** [comment]
You know...that one that you softened looks pretty good to me - the last example. I'm going to tag the only other people that have weighed in at all @timrae  @cydia2020 - you guys have thoughts? This is really close to @cydia2020 's work, that I also thought was really close to being good. 

I only did my weak adaptation to have *something* and I think of it like a placeholder, I personally would be fine with this second one here replacing mine.

**Comment by martindisch** [comment]
Well in these examples I made it easy for myself by just using a color as the background, while everything else (text, gradient, star) is in the SVG for the foreground.
But you're right, having two SVGs, one containing the background (color, gradient, text) and one with just the star and its shadow for the foreground is definitely the way to go. I'll look into it.

**Comment by martindisch** [comment]
Update: it works like a charm, and the parallax effect is pretty nice. See video [here](https://drive.google.com/open?id=1dHKXILftdP18GsRWW4lcfnsFT1eRWyKI).

The only problem is when the launcher has pretty intense parallax not only for the foreground, but also the background. Since the background doesn't go on forever like a color, you can end up seeing the edges of the background when there is a lot of movement, as demonstrated in the final part of the video. I have no easy solution for that, because we can't just make the background bigger and scale it down s.t. normally only the small center part is visible, as we'd run into problems with the gradient, which also covers all of the background. Plus it would be a pain to maintain background and foreground in different sizes.

But in the end I don't think that's too much of an issue. The launchers used by most people don't have parallax effects at all, and I'm not sure if any of those that do actually move the background enough to cause the problem.

**Comment by mikehardy** [comment]
I had to really pay attention to see the parallax issue you mention - it is visible but that is some serious jiggling going on - all of the icons are pretty crazy with that much motion.

I think this is approximately 10x better than my icon now for reasons of looks, much more interesting parallax, and it's SVG, I dig it. We'll see what others say, hopefully they chime in.

**Comment by timrae** [comment]
I don't mind that last one, but as I think I wrote in the other thread, I'd like to see more variations, particularly one with a somehow more defined monolith shape

**Comment by martindisch** [comment]
I'm all for more options, but I think it's really hard to make something with a prominent foreground shape (like the monolith) work well as an adaptive icon. Since the icon outline can change shape depending on the launcher, you're confined to a limited safe area inside the icon and when you need additional space for your own shape inside of that, everything you put in there quickly becomes pretty small.

Even Google seems to have had more success turning those logos into adaptive icons that don't feature a particular shape of their own, but work on a sort of background layer that can be cut to whatever shape the launcher requires. The other icons are still stuck in the halfway limbo of retaining the shape, but not quite fitting in with all the other apps that fully embrace adaptive icons.

![complete_google](https://user-images.githubusercontent.com/5547518/48299268-1bc21b80-e4cb-11e8-84ad-663c4e716c24.png)

Since the current proposal seems to be at least somewhat of an improvement, how about doing it the same way it's been done with the current icon, by going with it until an even better option emerges?

On a sidenote: I think it's a bit of a travesty that about half of Google's Android apps still use the halfway icons with white backgrounds. Considering that they presumably have some pretty decent designers on staff, I think Mike is entitled to take some pride in the current icon :wink:

**Comment by mikehardy** [comment]
Yeah as I mentioned in the other one the solid background requirement is the restriction. Without a clear idea of what to do with it an icon like this is what comes out or it's the old icon-ish like mine. If they had allowed transparency we'd have options but we don't have that capability.

**Comment by timrae** [comment]
The current adaptive icon in the development version was pretty non-controversial because it looks the same as the current round icon in 2.8.x. The last time we changed the icon we got 4 options made and took it to a vote. Hence ideally I'd like to get more submissions and do a similar thing this time.

**Comment by martindisch** [comment]
I wouldn't mind that either, it's just that I don't have more ideas for other designs solving the problem and at the moment I don't see anybody else who does. Although I do remember @cydia2020 mentioning something about maybe having time after the exams. Is this still a thing?

**Comment by martindisch** [comment]
In that case it looks like we're either stuck with the current icon or this. I'd appreciate it if everybody could quickly say if they'd rather keep the current one or go with my last suggestion for a while until somebody comes up with a better solution. Just so we can close this issue and get on with it.

Regardless of how it turns out, I pushed my updated SVG to a branch in my fork at martindisch/Anki-Android@52be9aee5f5695db0afed6ac3498af7e6af118e0, so if somebody wants to base their future efforts on the simplification of the original SVG I did for this, they can.

**Comment by mikehardy** [comment]
@martindisch - thanks for making sure it's available for the future, just in case. @timrae what's the right way to do a vote? Seems like @cydia2020 actually had a couple different looking designs, there's my no-change adaptation, and there's this one? Maybe that's enough to gather the vote to gain approval? I'd drive this I don't know what you want, and I don't want to do what turns out after the fact to be a half-measure

**Comment by nickdvlpr** [comment]
@martindisch @mikehardy 
If you would like another design added to the mix, I created a simplified version of the current icon.

![ic_launcher_dark_resized_small](https://user-images.githubusercontent.com/6563631/50664046-64e59780-0f71-11e9-88b0-2eaa1fac1f10.png)

**Comment by mikehardy** [comment]
Nice and yes I think we are just waiting for enough submissions to do a competition

**Comment by timrae** [comment]
That looks really nice, can you show how it looks on a launcher home screen?

**Comment by martindisch** [comment]
Thank you so much Nick! I was just recently thinking about closing this because I didn't think there would be any progress, but now we can move forward. This is great!

**Comment by nickdvlpr** [comment]
Glad you guys like it!

@timrae Here it is on a home screen with round and square icons.
![square](https://user-images.githubusercontent.com/6563631/50719987-752d6d80-106a-11e9-9b2b-bdd2ddb43f9b.png)
![round](https://user-images.githubusercontent.com/6563631/50719990-78c0f480-106a-11e9-80b9-7236e620a1d7.jpg)

**Comment by timrae** [comment]
That's two contenders we have now in my books. I'd like to see at least one more new concept, and/or a few variations on the existing concepts before making an official poll.

**Comment by martindisch** [comment]
Since you're looking for one more, I asked my friend Kaminaji who is a bit more talented in the graphics department to give it a shot and he came up with this.

![complete_kaminaji](https://user-images.githubusercontent.com/5547518/50783692-dee88a00-12ab-11e9-8609-b0f2df217151.png)

While he didn't find a way either to retain the monolith, he managed to emphasize the duality of the flashcard with the two-tone background, which is nice.

By the way, shouldn't we also consider @cydia2020's proposals from the [old issue](5031)  for the vote? With that we would already have at least 4 options to choose from.

**Comment by mikehardy** [comment]
Interesting. I like how both the last two give me this feeling that you do the cards and you get the star (i.e., a good grade etc) - like the star is leaping off. I agree @cydia2020 should definitely be included, and just in general now I want to delete my boring icon after seeing the development here, so hopefully we can have a vote and do that before too long. Thanks everyone - and of course if there are any more ideas, the more the merrier

**Comment by timrae** [comment]
I'd love to include one of @cydia2020's  concepts, since I think he was the one that started this whole thing, but I think a bit more work is required before they are ready for final conclusion.

While I don't have any intention of deciding the final logo myself, I want to make it clear that all core members of the team have "veto power", and certainly only proposals that I personally like will be included in the final poll.

**Comment by timrae** [comment]
Sorry I accidentally pushed the close button.

**Comment by timrae** [comment]
> While he didn't find a way either to retain the monolith, he managed to emphasize the duality of the flashcard with the two-tone background, which is nice.

The two-tone background is nice, but I really like how the star is emphasized in your one due to it being physically bigger. The star is the most recognizable part of the Anki logo, so my preference is that it continues to take up at least 50% of the available area. Perhaps you could try incorporating his background into your original concept?

**Comment by timrae** [comment]
I'm also curious how it would look having the star in the bottom rather than the top, like in the current logo. As I previously wrote, I'm also curious to see a logo that's almost entirely composed of just the star and some shadows.

**Comment by martindisch** [comment]
Kaminaji's background with my concept is actually a pretty good idea, here's how it looks.

![complete_two_tone](https://user-images.githubusercontent.com/5547518/50823664-c5d7eb80-1334-11e9-86d1-dd73d1e6b96c.png)

That was easy enough to accomplish by editing the source, but I'm not proficient enough with the "real" editing tools to produce the other ones.

**Comment by martindisch** [comment]
And Kaminaji just made a version with a bigger star at the bottom.

![complete_kaminaji_large_bottom](https://user-images.githubusercontent.com/5547518/50825445-53b5d580-1339-11e9-82f1-d9f306cea5b4.png)

**Comment by martindisch** [comment]
Here's just the star with shadows.

![complete_kaminaji_shadow](https://user-images.githubusercontent.com/5547518/50826442-f2dbcc80-133b-11e9-9e2c-f6d799fc3f15.png)

He's pumping these out faster than I can generate the previews :smile:

**Comment by timrae** [comment]
Maybe a bit smaller star and a bit more shadow, like in the keep icon next to it?

**Comment by martindisch** [comment]
He's been very productive. Here's the star, a bit smaller:

![complete_kaminaji_shadow3](https://user-images.githubusercontent.com/5547518/50839490-b8d0f180-1360-11e9-810a-21da4ba520a2.png)

And this is the smaller star with an even more pronounced shadow:

![complete_kaminaji_shadow2](https://user-images.githubusercontent.com/5547518/50839519-c4bcb380-1360-11e9-9923-ab10ddecf087.png)

A new concept:

![complete_kaminaji_card](https://user-images.githubusercontent.com/5547518/50839550-d605c000-1360-11e9-8ced-4bbe69344847.png)

And another one, symbolizing the choices you get when doing your cards:

![complete_kaminaji_choice](https://user-images.githubusercontent.com/5547518/50839601-f2a1f800-1360-11e9-840f-2ba555023daf.png)

**Comment by nickdvlpr** [comment]
![ic_launcher_3_small](https://user-images.githubusercontent.com/6563631/51343593-5eb8e600-1a5c-11e9-879a-9e146113b860.png)

Here's another version I had made similar to the previous one that I figured we could throw in the mix.

**Comment by timrae** [comment]
That's cool! Again could you please show how it looks on a launcher? It's pretty hard to visualise how it looks on a round background.

I'll try to get the ball rolling with this as soon as I'm out of job interview hell. In the meantime, the more ideas the better!

**Comment by martindisch** [comment]
Checking in to see how it's going, since I'd like to get this moving again. If you don't have enough time, I'd be happy to put together a small poll with the candidates you want, which you can give to people to vote on this.

**Comment by timrae** [comment]
Yeah sorry I forgot about this and don't have too much time to put into this. The main thing is to generate a screenshot on the simulator with all the icons side by side. Would you be able to do that?

For example see the previous poll

https://docs.google.com/forms/d/18_IJ83I5hfaLeFek9D9qg_JKyn7vtGrU2kk13C5fUug/edit

**Comment by martindisch** [comment]
I might be able to get it done this weekend, although I can't make any promises. What I need is the exact list of which icons should be part of the poll. Since we've had lots of them in this thread and some are variants of each other, the best way to make sure we don't get them confused is probably if you paste the links to the images as they've been posted here, so I get the right ones.

I have the sources for all the icons I've posted, but not the ones from Nick. If you want them I need to get these as well.

**Comment by timrae** [comment]
@nickdvlpr

Could you please post the source?

**Comment by oakkitten** [comment]
a bit of opinion here

somehow in all screenshots the default slightly rotated star ([like this one](https://user-images.githubusercontent.com/5547518/50839519-c4bcb380-1360-11e9-9923-ab10ddecf087.png) or [this one](https://user-images.githubusercontent.com/6563631/50719990-78c0f480-106a-11e9-80b9-7236e620a1d7.jpg)) it looks a bit off center, to the right. not enough to the right to seem deliberate, feels like a bad placement

vertical bars like [these](https://user-images.githubusercontent.com/5547518/50839550-d605c000-1360-11e9-8ced-4bbe69344847.png) or [these](https://user-images.githubusercontent.com/5547518/50825445-53b5d580-1339-11e9-82f1-d9f306cea5b4.png) look like menus and not like something related to anki

the higher contrast lines [like here](https://user-images.githubusercontent.com/5547518/48277666-9cd9ce00-e44b-11e8-84f9-493e1689cb14.png) stand out too much; bright lines look brigter then the black lines look darker. also the distance between rows could be made more consistent, and that one black line that touches the star could not touch it

of all images posted in this thread i like [the first suggestion](https://user-images.githubusercontent.com/5547518/48252523-4cd81880-e405-11e8-9275-581f92c53914.png) best of all

**Comment by timrae** [comment]
I think we need to advertise that we're looking for a new icon design more
widely by notifying all the beta testers and asking more people to submit
designs. Then we can ask everyone to vote in the 2.9 release, and include
the winner in 2.10.

**Comment by martindisch** [comment]
I was really hoping we could finally finish this, almost 5 months after it started. In the beginning you said that the last time, you got 4 options made for the vote, and reasonably asked for more variations. Thanks to the efforts of my friend and Nick, we now have around 8 relatively unique designs. If you wanted even more options, asking the beta testers for their proposals earlier in the process could have saved some time.

But this is your show, and as long as we get a nicer icon out of it, I don't mind too much how long it takes. In that case I won't bother to produce the screenshot with the options just yet.

**Comment by timrae** [comment]
>  If you wanted even more options, asking the beta testers for their proposals earlier in the process could have saved some time.

We haven't released a beta version in the last 5 months, so there was no way to speed it up unfortunately. Besides I was busy with job hunting.

**Comment by timrae** [comment]
> As long as we get a nicer icon out of it, I don't mind too much how long it takes. In that case I won't bother to produce the screenshot with the options just yet.

Maybe we can roll out a poll on Google Docs with all the current entries, and instructions on how to submit a new icon proposal, and then start advertising that in the alpha channel? Then we can use that same poll in the beta channel when the beta finally gets released.

**Comment by martindisch** [comment]
Sure, whatever it takes. Just tell me what you need and I'll try to get to it on the weekend. 

Maybe we don't even have to create a new screenshot for the icons, since at least the ones I proposed are all on the same background using the same crop. The only difference between the screenshots is the Ankidroid icon, so they're directly comparable to each other without external bias.
Doing that would save some time, although if there's a good reason, I'll gladly create new screenshots.

**Comment by nickdvlpr** [comment]
Sorry for not replying sooner, but here are the source files for my two icon designs. I use GIMP (free photoshop alternative) so the file type is .xcf unfortunately.

[anki_icon_gray.zip](https://github.com/ankidroid/Anki-Android/files/3099645/anki_icon_gray.zip)
This zip file contains the ic_launcher_background and ic_launcher_foreground source, along with an example PNG of what they will look like combined (the same icon I posted earlier).

[anki_icon_blue.zip](https://github.com/ankidroid/Anki-Android/files/3099650/anki_icon_blue.zip)
This zip file contains the source for the blue variant I posted.

**Comment by martindisch** [comment]
> Sorry for not replying sooner, but here are the source files for my two icon designs. I use GIMP (free photoshop alternative) so the file type is .xcf unfortunately.

Thanks a lot, we can definitely work with that.

> Upon rotating the star, however, I noticed that it does not have perfect horizontal symmetry (if the top point of the star is centered, the bottom middle crevice of the star is slightly offcenter).

Interesting, I haven't noticed because I never rotated it. In fact I didn't make any changes to the star, it's the same as in the original. Maybe we could redraw it from scratch (with its original geometry of course, minus the asymmetry) and fix that for the final version of the icon that gets chosen.

**Comment by timrae** [comment]
@nickdvlpr 

Thanks for getting back to us with the source.

@martindisch 

> Just tell me what you need and I'll try to get to it on the weekend.

Hmm I'm not really sure, we just need to advertise a central place to discuss designs and submit new ones. It could be here, the forum, a google doc, or some combination. What are your thoughts?

**Comment by mikehardy** [comment]
Our wiki, link advertised everywhere?. Then for next competition there will be an easy to find template...

**Comment by martindisch** [comment]
The wiki definitely is a central place, although I'm not sure how well it lends itself to an ongoing discussion like you usually have it when people propose different ideas. It would probably need an accompanying issue for discussion, and at that point why even have a page on the wiki?

But maybe I don't fully understand what you imagined. For accepting new proposals I would have just continued in here, then put all candidates in a Google Forms poll for the final decision.

**Comment by mikehardy** [comment]
Fair point - I can see your sketch working fine, go for it? I'd still like maybe a summary of the process on the wiki later as this issue has been a little start/stoppy and part of that was process-oriented. But that's more like mop-up after whatever decision is made on the icon itself

**Comment by martindisch** [comment]
Absolutely, documenting the process for future iterations seems like a very good idea. As for the next concrete steps, since it's just about letting people know they can still submit their ideas before the decision, I'm not sure what I can do to support you at this stage. But like I said, I'm happy to help put together a poll once we have a list of all candidates.

**Comment by svenper** [comment]
This one looks promising, I'd love to see it in context and perhaps a bit more cropped with more distinct bottom "text" (reverse gradient? gray background?):

<img src="https://user-images.githubusercontent.com/6563631/51343593-5eb8e600-1a5c-11e9-879a-9e146113b860.png" width="80" />

Regarding the cut off in the first one, I think either none, or enough to make the blue be cut off as well. 

<img src="https://user-images.githubusercontent.com/5547518/48252523-4cd81880-e405-11e8-9275-581f92c53914.png" width="300" />

**Comment by martindisch** [comment]
Thanks for reviving this, I almost forgot about it. Since it seems that there are a lot of beta releases being tested currently, maybe now's the time to get a poll up for this?

**Comment by mikehardy** [comment]
That would be ideal I think - we might be able to sneak it in just before 2.9 🙏 - do you have time to run the poll? (mostly it's creating the screenshots and doing the google-magic to make a poll I guess? according to the comment above)

**Comment by martindisch** [comment]
Sure. I just realized I already said what I need to say previously, so let me quote myself here:
> What I need is the exact list of which icons should be part of the poll. Since we've had lots of them in this thread and some are variants of each other, the best way to make sure we don't get them confused is probably if you paste the links to the images as they've been posted here, so I get the right ones.

Since Tim made the point that maintainers can veto proposals, it would save me a lot of time if the two of you could list your candidates so I only have to create screenshots for the intersection of your choices.

**Comment by mikehardy** [comment]
I abdicate any veto I'd have, I'm happy to let @timrae cull the list without complication/interference just so we don't have a Boaty McBoatface moment

**Comment by martindisch** [comment]
Very well, I'll whip something up once I get his selection.

**Comment by timrae** [comment]
https://user-images.githubusercontent.com/5547518/48277666-9cd9ce00-e44b-11e8-84f9-493e1689cb14.png

https://user-images.githubusercontent.com/6563631/50719990-78c0f480-106a-11e9-80b9-7236e620a1d7.jpg


https://user-images.githubusercontent.com/5547518/50839490-b8d0f180-1360-11e9-810a-21da4ba520a2.png

https://user-images.githubusercontent.com/6563631/51343593-5eb8e600-1a5c-11e9-879a-9e146113b860.png

**Comment by martindisch** [comment]
Ok, here's v1 of the poll: https://forms.gle/4UJCMTSrN9cjFokG8
Please don't submit anything until it's been decided that it's ready.

It shuffles the order of entries between attempts to prevent any bias that could be introduced by that. Once it's closed, I can post the CSV with the responses here. Or I could add a maintainer as a collaborator on the poll, to verify I didn't manipulate the results :wink:

**Comment by mikehardy** [comment]
Nice touch with the randomization :-), also to put them all nicely on the same background using the same icon mask. I'm not worried about manipulation, just really curious to hear the results. Poll looks good to me

**Comment by martindisch** [comment]
By the way, it's also possible to require people to submit their email address (guess that's for cases where you want to control who gets to vote) or even make them sign in (to prevent submitting multiple times). In case you think that may be necessary.

**Comment by mikehardy** [comment]
that's a good point - I wasn't worried about manipulation by us, but I could see someone stuffing the ballot box so to speak. I'm not anti-sign in though some may not want a google account for personal reasons it might be a reasonable trade-off. Not sure how Tim ran it last time w.r.g. protecting the vote integrity

**Comment by timrae** [comment]
Great, thank you for keeping this moving despite my terrible responsiveness! I guess we should include the current icon in there as well to accommodate the people who don't want to change.

I'd also like to include some text to explain the background and encourage people to engage in discussion and submit any alternative ideas or variations they have in mind. I guess we can keep using this thread as the central place for that discussion unless someone has a better idea?

**Comment by martindisch** [comment]
Added some text explaining the rationale behind the change, a link to this discussion, as well as the current icon as a fifth option. Let me know if you have anything you want to change about the text.

**Comment by timrae** [comment]
That's perfect, thank you so much!

**Comment by timrae** [comment]
@martindisch 
I've created a PR that prompts the beta users to complete the poll in #5425, so should be live for them over the next few days. Could you please update the explanation text to note that we will make a new additional poll if more icons are proposed?

**Comment by martindisch** [comment]
Thanks, I'm excited to see how it goes! I've updated the text. Just FYI, the poll already received 3 responses since I last updated it, even though I said to wait until it was done. But since these respondents saw the same poll we have now (the current icon was already added as an option then) I guess these are valid results too. But if you'd rather start with a clean slate, I can remove them.

**Comment by timrae** [comment]
Great, thank you for taking care of that! Looking at the wording again objectively, it seems quite verbose, but since this initial poll is aimed at beta testers who tend to be a bit more invested in the app, I think that's probably fine! What do you guys think?

By the way, are you able to give me owner access to the form, just in case something urgent comes up for you that prevents you from responding? perceptualchaos2 gmail.

**Comment by timrae** [comment]
Oh and I think it's fine to keep those initial votes there! It wasn't me ;)

**Comment by martindisch** [comment]
Done. Feel free to change the wording however you like.

**Comment by Magneticdud** [comment]
Beta user here, i love one of the new icons, voted my preference 😀

**Comment by timrae** [comment]
@nickdvlpr 
Would you be able to make a version of [this](https://github.com/ankidroid/Anki-Android/issues/5110#issuecomment-455302930) with a grey background?

**Comment by timrae** [comment]
I made a super rough version just to see for myself what it would look like. I guess it didn't turn out as good as I had hoped.

![Screen Shot 2019-09-07 at 13 38 56](https://user-images.githubusercontent.com/2818274/64469883-f8acda80-d174-11e9-807f-a40bf587e097.png)

**Comment by timrae** [comment]
@martindisch 
Shall we close the poll now and publish the results?

**Comment by martindisch** [comment]
Sure, seems like a good time. I'm very happy with the number of people who participated. We got 769 responses, which is much more than I'd hoped for.
GitHub won't let me upload the CSV directly, so [here it is in a ZIP](https://github.com/ankidroid/Anki-Android/files/3615015/AnkiDroid.Icon.Poll.csv.zip).

Since people could give every entry 0 to 5 points, I just summed up the total every one got, but the same could be achieved by taking averages. Here are the results in my book:

**1. Alpha with 2638 points**
![Alpha](https://user-images.githubusercontent.com/5547518/64938887-96806380-d85f-11e9-8932-1b54b6fd6f21.png)

**2. Charlie with 2546 points**
![Charlie](https://user-images.githubusercontent.com/5547518/64938927-b31c9b80-d85f-11e9-9828-c9e52d3bb4ce.png)

**3. Bravo with 2511 points**
![Bravo](https://user-images.githubusercontent.com/5547518/64938939-bdd73080-d85f-11e9-9b52-6125539e533c.png)

**4. Delta with 2256 points**
![Delta](https://user-images.githubusercontent.com/5547518/64938946-c92a5c00-d85f-11e9-985c-cf47e367e16a.png)

**5. Echo with 1654 points**
![Echo](https://user-images.githubusercontent.com/5547518/64938952-d3e4f100-d85f-11e9-9253-5304aafe8688.png)

I hope I didn't make any mistakes, but that's why I uploaded the results, so somebody else can verify that.

**Comment by timrae** [comment]
Yeah, it's pretty clear to me that no matter how you tally the results, `Alpha` was the winner. So could you make a pull request to make Alpha the new AnkiDroid icon? Of course anybody is still encouraged to submit an alternative icon at any time. I don't think `Alpha` is perfect, but it's clearly a big improvement on `Echo`.

**Comment by martindisch** [comment]
Will do. I'm a bit busy and can't say for sure if I'll get it done by tomorrow, but it shouldn't take longer than 3 days. I hope we're still in the beta window by then.

**Comment by timrae** [comment]
No problem at all, we'll most likely be in beta for another few weeks.

**Comment by martindisch** [comment]
I had a couple of minutes and was able to do it already. Now I just hope it'll hold up and there's no weird device/launcher where it looks bad for some reason.

**Comment by mikehardy** [comment]
Happy to see "echo" (my get-'er-done) icon die, and alpha was my favorite too :-). My takeaway is people like the color scheme at minimum, and they like something that references the idea of the cards. I'm excited to see the new icon show up on my launcher

**Comment by martindisch** [comment]
Right, the color scheme really is very attractive and unique, I'm glad we get to keep it.

Since this will probably be closed soon, I'd like to thank everybody who gave their opinion or submitted proposals on their own, and especially the maintainers for putting up with it. This has been a long one, but I really think it'll be worth it.

**Comment by ByteHamster** [comment]
I guess I'm too late (now that the PR is already done) but I will post this anyway. The only thing that I don't like about design Alpha is that the lines are cut off by the shape of the circle. Do you think we could move them slightly, so they have a little bit of padding to the boundaries of the circle?

If you agree, I can experiment with that a little bit within the next 4-5 hours.

**Comment by timrae** [comment]
Yeah I agree, please do!

**Comment by martindisch** [comment]
Might turn out well, I'm looking forward to it!

**Comment by ByteHamster** [comment]
I just plotted the csv you uploaded using R. I am getting the same vote sum as @martindisch, that's a good sign. Interesting enough, when looking at the number of 3+ votes, Charlie and Bravo are swapped (see plot below). Alpha is still the winner.

![image](https://user-images.githubusercontent.com/5811634/64980513-45518d80-d8ba-11e9-9a12-fb69a334ed82.png)

**Comment by martindisch** [comment]
Very nice, thanks for taking a good hard look at the numbers.

**Comment by ByteHamster** [comment]
As promised, I wanted to play around with the position and size of the lines. I added an overlay of some common adaptive icon shapes to show what parts of the image would be stripped off.

Old / New:

<img width="300" src="https://user-images.githubusercontent.com/5811634/64982366-53091200-d8be-11e9-9f5d-60195ef532ab.png" /> <img width="300" src="https://user-images.githubusercontent.com/5811634/64983708-72ee0500-d8c1-11e9-9dd3-f0b60f323d79.png" />

My changes:
- Moved lines closer together
- Reduced length of first dark line on the right
- Reduced all line lengths on the left
- Moved everything a tiny bit to the right

If you agree with those changes (especially @martindisch), I can create a PR.

**Comment by mikehardy** [comment]
not sure about the rest, but I think those changes can almost be considered bugfixes vs the various adaptive icon masks, still clearly in the spirit of the previous icon

**Comment by martindisch** [comment]
Agreed, I'm pretty sure all the people who voted for mine would like this one too. I'd say go ahead with the PR and we'll see what @timrae thinks tomorrow.

**Comment by timrae** [comment]
Yes, absolutely, great job!
