### ISSUE TITLE
CI support for JDK10 and 11

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5115]
We had errors when Java 10 was introduced and since then I think there were 2 regressions. CI should do at least one API for each of the various JDKs we expect to work (which I think would be Java 8 through Java-current at this point, for both Oracle JDK and OpenJDK?)

https://docs.travis-ci.com/user/languages/java/#using-java-10-and-later

This would be a great first issue for anyone that wanted to familiarize themselves with how we use Travis, as it would involve a change to our build matrix, but ideally without a full matrix expansion (i.e., we don't need every API for every JDK, we should pick one JDK - like oracle JDK8 which we use currently - for full Android API expansion, then pick one API (i.e. our most popular one supported by Travis which is probably API24) and only do the JDK expansion there. Recommended to set up your own Travis instance (they are free) for the implementation attempt so you don't have to open a PR and push every time you want to check a change to the .travis.yml

I would also assert that as long as the "primary JDK" (which should be oracle jdk8 since it is our current CI JDK) is working, the others should be acceptable failures since they don't block development or releases

**Comment by andersan** [comment]
Hey Mike! Made a major move this month to Colombia so I've been MIA. 

This looks like an issue I'd be happy to learn about - I've built CI pipelines with AWS tools but have wanted to learn Travis or CircleCI for a while. Will let you know if I run into any snags.

**Comment by mikehardy** [comment]
Hey, welcome to Latin America! We're neighbors - I moved to Ecuador a couple years back and hope you like it as much as I do. For this task, we're 100% Travis so you'll only learn one but they work similarly so you can pick up Circle for other projects pretty easily. I'd just pick whatever the most up-to-date emulator that works on Travis is (I think it's API24? it'll be in .travis.yml though) and I would make it optional since I'm just about sure that we're broken for jacocoUnitTestReport on JDK>8 right now (#5088) - it will be good to have it though as at some point I expect a dependency update will just magically fix it...

**Comment by andersan** [comment]
Wow, that's awesome! Its been great so far but still adapting a lot to the culture of the small town I'm living in.

It looks like API 22 is the newest version running the tests if I understand the travis.yml file.

In order to test with OpenJDK 11, for example, I'd switch to OpenJDK 11 in a script and then test by running 
` - ./gradlew jacocoTestReport` (taken from the existing code travis code)
Does that sound right? I'll set this up and test it out later tonight.

**Comment by mikehardy** [comment]
> It looks like API 22 is the newest version running the tests if I understand the travis.yml file.

Indeed - that's kind of sad but it seems like API22 is the most modern emulator that works on Travis reliably

> In order to test with OpenJDK 11, for example, I'd switch to OpenJDK 11 in a script and then test by running
> ` - ./gradlew jacocoTestReport` (taken from the existing code travis code)
> Does that sound right? I'll set this up and test it out later tonight.

That is also right - but I will say I expect failure immediately. There is something about Robolectric + OkHttp right now that is blowing up with empty passwords on the key store. My thought was to try to depend on + import the Conscrypt library in place of the stock platform SSL implementation but I didn't chase that to conclusion

**Comment by mikehardy** [comment]
The problem is the re-running unfortunately. Those APIs all work sometimes. They all work for me locally (in fact I can get API15 through API28 + Chromebook - our full API skew) to run locally every time, but for some reason on Travis each of those would sometimes fail. About the 10th time I found myself hitting the "re-run build" button for a given API I'd knock it out for flakiness.

As you roll forward so you have all the current commits you might see the same thing, or maybe with a recent dependency update things got better, or ?. I did just make a PR to switch to ANDROIDX_TEST_ORCHESTRATOR to run instrumented tests, maybe that will help as well.

More than anything, I wish Travis would enable nested virtualization so we could use x86 emulators for speed reasons and so we could use the newer APIs...

**Comment by andersan** [comment]
It appears that the x86 support will not come any time soon:
https://github.com/travis-ci/travis-ci/issues/1419

The ARM versions of the recent Android APIs still aren't available and
there's no official news on that from what I see.

I enabled the other API versions just to see what happens - the tests are
painfully slow. I'm testing from a mobile device and don't know how to
merge changes from upstream without a terminal+git repo, so I'll merge
changes later and run another test.

**Comment by mikehardy** [comment]
Seems about where things were status-wise last time I looked. So for me I just focus on CI being very very stable so that it never false-negatives, and then as an individual contributor I have the whole fleet of emulators named with a convention that works with this script: https://github.com/ankidroid/Anki-Android/blob/master/tools/quality-check/start_all_emulators.sh

In combination with a lot of RAM (32GB) I just start the whole fleet at once with no delay, run the jacocoTestReport, then stop them all and it only takes a couple minutes. That requires a pretty fast machine but even doing every other API, or just API15 and API28 by themselves is pretty good to make sure nothing odd slipped in that CI couldn't catch.

That's why I was more focused on JDK switching than APIs - just to have a fuzz check for the modern JDKs since they seemed problematic but fixable
