### ISSUE TITLE
"Cards due" notification not updating after reviewing 

### ISSUE THREAD

**Issue by noamraph** [ankidroid/Anki-Android#5133]
###### Reproduction Steps

1. Enable cards due notification 
2. Wait until there are cards due
3. Review the cards

###### Expected Result

Notification should be updated as less cards are due, and disappear when no cards are due

###### Actual Result

Notification remains, showing the same number as it showed before review 

###### Debug info
AnkiDroid Version = 2.9alpha52

Android Version = 7.1.1

ACRA UUID = e9cce31c-f922-461c-8cb7-d72cd8e89e0f

###### Research
*Enter an [ x ] character to confirm the points below:*

[  x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Indeed I see this (and it irritates me!) as well. Cross-linking with #4944 where I'm collecting information to fix all these in a go before 2.9. Notifications is next after I fix a difficult crash in the template editor

Thanks @noamraph

**Comment by federvieh** [comment]
Just to clarify: The behaviour is the same on AnkiDroid Version 2.8.4 (and before as far as I remeber). So it is not somthing that has been introduced during the development of 2.9.

**Comment by noamraph** [comment]
Actually I do remember the notification getting updated, or at least going
away, after review. Perhaps in an earlier 9.5 version, I don't remember.

On Nov 26, 2018 06:30, "Frank Oltmanns" <notifications@github.com> wrote:

Just to clarify: The behaviour is the same on AnkiDroid Version 2.8.4 (and
before as far as I remeber). So it is not somthing that has been introduced
during the development of 2.9.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/ankidroid/Anki-Android/issues/5133#issuecomment-441516031>,
or mute the thread

**Comment by federvieh** [comment]
Yes, the notifications do get updated in 2.8.4. I think the update happens when leaving the deck list. Sorry for the confusion. I didn't realize that the behaviour changed in 2.9alpha.
