### ISSUE TITLE
Media sync doesn't manage special chars ("&" becomes "&amp;"...)

### ISSUE THREAD

**Issue by guiljo** [ankidroid/Anki-Android#5137]
###### Reproduction Steps

1. Create a new card on Anki PC
2. Attach a video (or other media) with a special char in its filename (eg. "Bibi & Bubu")
3. Synchronize on PC and on AnkiDroid
4. Try to study the card on AnkiDroid

###### Expected Result
The video should play

###### Actual Result
* The video won't play
* When you browse the deck on Ankidroid, you can see the "&" has turned into an "&amp;" (but not on AnkiPC nor AnkiWeb)
* HOWEVER, on AnkiPC, Tools/Check media shows the following warnings :
    - In media folder but used by no card: Bibi & Bubu
    - Used by cards but missing in media folder Bibi &amp; Bubu
(but the video still plays when you study the card)

This bug may not be entirely AnkiDroid's fault (maybe AnkiPC could manage special chars better); however, I believe AnkiDroid could also take into account these kinds of characters.

###### Debug info
AnkiDroid Version = 2.8.4
Android Version = 8.0.0
ACRA UUID = f080fa5d-e049-4845-b17e-3f51c5674004

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
can you export a small test collection and export it with media so we have a reproduction scenario here all ready to go? (just note you have to change the filename of the export to .zip to attach it here). Also, could you raise this on anki.tenderapp.com (AnkiDesktop support site) to see what they think. Your extra detail is fantastic but when AnkiDesktop is able to play it while giving you warnings it makes me think that the issue of how to handle it is not fully resolved there, and before we make a change here we would want to know whether this is something we should handle or not. Thanks!
