### ISSUE TITLE
Android Architecture Rewrite

### ISSUE THREAD

**Issue by surajsau** [ankidroid/Anki-Android#5140]
Sorry for the direct question but, are there any plans of having a rewrite with a defined architecture (MVP, MVVM etc) for the app? The app code though understandable still appears to be a big challenge for future contributors to dive straight in. Maintaining the code will also get tougher if features & fixes keep coming up?

**Comment by mikehardy** [comment]
I haven't personally thought about it, but it might be useful yes. Incrementalism is usually a feature when collaborating with volunteers, do you have any concrete proposal for one of the simpler use cases, for example the model browser?

My main thrust over the last year has been to just get all the dependencies up to date and add testing. As I add the last few items to 2.9 I'm growing a set of tests that will make it more achievable to do something like this without accidentally creating regressions

**Comment by mikehardy** [comment]
Closing this as it is not actionable - make a modification to a small area in the style you are thinking and propose it for discussion as a PR and we can go from there
