### ISSUE TITLE
[card browser] from local menu search only last deck

### ISSUE THREAD

**Issue by ps-goog** [ankidroid/Anki-Android#5144]
###### Reproduction Steps

1. Exit ankidroid
2. Run browser
3. Select any text and click and show local menu and choose [card browser]

###### Expected Result
...
4. Ankidroid searches all deck
I think that Ankidroid should search always all deck even I run [card browser] from local menu

###### Actual Result
...
4. Ankidroid searches any (last?) deck

###### Debug info
AnkiDroid Version = 2.9alpha54
Android Version = 8.0.0
ACRA UUID = dd27ecef-281f-411a-b121-c44b1ca1bdb7

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Fixed in #6250
