### ISSUE TITLE
Crash on double-tap of undo in reviewer

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5152]
###### Reproduction Steps

1. Start app clean (kill and restart if needed - must clean undo stack)
1. Review a single card
1. tap "undo" twice as fast as possible

###### Expected Result

Card review is undone

###### Actual Result

Both taps somehow make it into the undo code, and the app crashes trying to perform the second undo since the ArrayList is underrun

Probably just needs double-tap protection. Much of the UI could probably use that.

Appears in current alphas

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/ac15f57f-40c6-45b5-8bed-580a55e814cc
```
10-23 16:58:04.448 I/AnkiDroid(25335): Reviewer:: Undo button pressed
--
2 | 10-23 16:58:04.561 I/AnkiDroid(25335): AbstractFlashcardViewer:: Question successfully shown for card id 1539854283598
3 | 10-23 16:58:04.579 I/AnkiDroid(25335): Reviewer:: Undo button pressed
4 | 10-23 16:58:04.708 I/AnkiDroid(25335): AbstractFlashcardViewer:: Question successfully shown for card id 1539854277316
5 | 10-23 16:58:04.730 I/AnkiDroid(25335): Reviewer:: Undo button pressed
6 | 10-23 16:58:04.852 I/AnkiDroid(25335): AbstractFlashcardViewer:: Question successfully shown for card id 1539854274185
7 | 10-23 16:58:04.872 I/AnkiDroid(25335): Reviewer:: Undo button pressed
8 | 10-23 16:58:04.879 I/AnkiDroid(25335): Reviewer:: Undo button pressed
9 | 10-23 16:58:04.951 E/AnkiDroid(25335): DeckTask/ doInBackgroundUndo - RuntimeException on undoing
10 | 10-23 16:58:04.951 E/AnkiDroid(25335): java.util.NoSuchElementException
11 | 10-23 16:58:04.951 E/AnkiDroid(25335): at java.util.LinkedList.removeLast(LinkedList.java:283)
12 | 10-23 16:58:04.951 E/AnkiDroid(25335): at com.ichi2.libanki.Collection.undo(Collection.java:1232)
13 | 10-23 16:58:04.951 E/AnkiDroid(25335): at com.ichi2.async.DeckTask.doInBackgroundUndo(DeckTask.java:780)

```

**Comment by timrae** [comment]
@mikehardy 
FYI: I've made a new label "Reproduced" which should be used instead of "Accepted" for bugs

**Comment by david-allison-1** [comment]
Can't access the ACRA report, but I don't think this is a crash bug. It's raised by the following:

https://github.com/ankidroid/Anki-Android/blob/547e1c64092acafc197e0d7a6bfe8e3cc0d62aef/AnkiDroid/src/main/java/com/ichi2/async/DeckTask.java#L850-L854

Recent report:

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/418d7efe-4d82-4fe7-86ef-47fa2ff9af96

**Comment by mikehardy** [comment]
🤔  might be interesting to instrument this a bit more, upgrade from .d to .i and/or add more in the method: https://github.com/ankidroid/Anki-Android/blob/547e1c64092acafc197e0d7a6bfe8e3cc0d62aef/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1354

But my analysis that it was a double-tap was because the very first thing that happens is the undo list is dequeued but it must have been empty https://github.com/ankidroid/Anki-Android/blob/547e1c64092acafc197e0d7a6bfe8e3cc0d62aef/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1353

How else can that happen?

**Comment by mikehardy** [comment]
I am unable to reproduce this on my phone which likely processes it too quickly, or perhaps it has been fixed already? This may be reproducible on emulators or things that process more slowly.

**Comment by mikehardy** [comment]
I'm going to allow it to go stale (since I can't reproduce)

**Comment by Arthur-Milchior** [comment]
Buttons are disabled dueing long tasks such as undoing. I’m not surprised therefore that it becames hard to reproduce. Using gesture may help
