### ISSUE TITLE
Special fields and review information

### ISSUE THREAD

**Issue by adlew44** [ankidroid/Anki-Android#5154]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Just saw this was a duplicate - @adlew44 could you go over to #4676 and subscribe / give it a thumbs up so we register interest there?

**Comment by adlew44** [comment]
Yes indeed – similar if not identical. I’ve given it the thumbs up and left a short note in support. Thanks.
