### ISSUE TITLE
Show progress during database checks (esp on startup)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5155]
###### Reproduction Steps

1. Upgrade to a version of the app that does a database check on startup
2. start the app
3. 

###### Expected Result

The app either starts promptly or indicates that it is doing something

###### Actual Result

The app appears to hang (possibly for a very long time on large collections, slow devices) which is worrisome for users

Reported by @anthropos888 on the mailing list

**Comment by mikehardy** [comment]
I just finished working on database versions with #5172 and took the time while in the area to try to reproduce this and create a test case. I was unable to reproduce it - if I put in a forced check, and I alter the check to take a long time (both changes so that I can guarantee the check happens and I have time to see it) - I see the database check dialog? Granted it isn't dynamic or anything, but it does indicate what's going on.

:thinking: 

![screenshot from 2018-12-19 17-00-51](https://user-images.githubusercontent.com/782704/50250728-aee64f00-03af-11e9-8fd9-242c773f12d9.png)

**Comment by Anthropos888** [comment]
Yes, the checking database dialog is there, but there is no progress shown or anything. So if the check lasts two minutes and the dialog window doesn't change at all, this might cause users to think that the app crashed. 
So some dynamic information as in the sync dialog or just a spinning wheel or something would solve that.

**Comment by mikehardy** [comment]
Ah okay - that's a reasonable point. So then it isn't that I cannot reproduce, I just didn't understand fully. I can see how seeing it stuck there is a little disconcerting - maybe we can expose what's happening during the integrity check, or at least make it an animated spinner with a note that it could take a long time depending on collection size.

**Comment by mikehardy** [comment]
Will be fixed as soon as #5177 is in shape to merge.
