### ISSUE TITLE
Notification bar disappears in note / card editor

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5156]
###### Reproduction Steps

1. Open the note editor or card editor
2. observe the notification bar
3. 

###### Expected Result

Notification bar is still there? But maybe this is intentional and @timrae  knows something from the past that I do not?

###### Actual Result

Just a white bar is shown where the notification bar was

this is with current alphas at least, reported on the mailing list by @anthropos888

**Comment by snowtimeglass** [comment]
I'm glad to hear that!
