### ISSUE TITLE
Allow selection of fields to use in browser in note editor

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5158]
Apparently in Anki Desktop it is possible to select what note fields to use in the browser view?

In AnkiDroid this seemingly should be a feature in the Note Editor, where users may select which fields will be used by Card Browser for the note?

Reported on the mailing list by @anthropos888

**Comment by timrae** [comment]
I guess you're talking about the browser card templates for front and back? These are used in our libanki but we don't provide any way to change them, that's desktop only atm.

**Comment by mikehardy** [comment]
I just had another user ask for essentially this, and it looks like you can select which field you want to use in the Card Browser, you just need to use Deck Picker -> (options menu) Manage Note Types -> long-tap a field and select it to use for sorting.

@timrae this area is new for me, but if I'm understanding this correctly this is not a bug then? And @Anthropos888 you would have the functionality you're looking for...

**Comment by david-allison-1** [comment]
I'd like to take this on. Ref: https://docs.ankiweb.net/#/templates/styling?id=browser-appearance

This only needs a UI and editing, the Card Browser already handles the override if set in AnkiDesktop.

**Design:**

* Add an additional button to the card template editor: "Browser Appearance"
* New Activity: `TemplateBrowserAppearanceActivity`
  * Input:
    * Either: CardOrdinal & ModelId
    * Or: Nothing (new model)
    * Or: serialised representation of current data ❗️ 
  * 4 fields: front, back, font, and font size.
  * Accept/Cancel button
    
  * Output
    * Accept: serialised representation of the 4 fields ❗️ 
    * Cancel: N/A

Questions:

* Will this mesh well with the in-memory template editor?
* I'd ideally like to save the new value in-memory and have the caller apply it. What's the best way to pass a structure back from an activity? Temp file in cache?

**Comment by Anthropos888** [comment]
Just as a side note: the "browser appearance" feature as been requested multiple times through the mail list recently.

**Comment by mikehardy** [comment]
yeah, we fixed a bug on image/sound tag parsing which meant the card browser reliably shows the file names, which is good because we're parsing them correctly but bad because people don't like it. This one is unfortunately stacked up behind some other stuff (#5151 as well as a little work slowdown as I prep to cut the 2.10 release branch off from master)

**Comment by Anthropos888** [comment]
I just saw that the browser appearance feature is already implemented. Haha, you guys are too fast, I can't keep up with all the recent changes :-) Thanks for your great work!

**Comment by david-allison-1** [comment]
@Anthropos888 More than happy to help! Thank you 😀
