### ISSUE TITLE
Alter CardBrowser search from context-menu intent to search in all decks

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5159]
###### Reproduction Steps

1. Right click any text on the device
2. Select the "Card Browser" option to search for the text in AnkiDroid

###### Expected Result

All decks are searched and result is shown

###### Actual Result

Only the "current selected deck" is shown

Happening on the alphas from around 2018/11/28 at least, reported on mailing list by @anthropos888

**Comment by timrae** [comment]
Yeah this is a bit of a bummer... The larger problem from a  UX perspective is that we hide the deck spinner when the search bar is open, and we lose the query when we close it. Maybe we wanna explicitly show the "deck:xyz" part of the query in the search query? Or somehow continue to show the deck spinner?

**Comment by mikehardy** [comment]
I like the idea of exposing the deck in some way, and I lean towards the query language. I don't think most people will edit that so it shouldn't "hurt" despite being pretty techy, but for those that are power users (as Anki seems to attract) it serves as a hint/reminder to the power available in that search box - which I forget is there myself pretty frequently. Other alternative would be to stack a second bar or something? 

Maybe the whole thing turns into a search bar and the spinner becomes a dropdown of available "deck:xyz" menu entries plus (enhancement...) some LIFO history of previous searches

**Comment by voidplayer** [comment]
On top of not searching all decks, filtered decks search only on filtered decks, instead of the original deck... :(
