### ISSUE TITLE
Clicking back in sub-settings leads to homepage instead of settings.

### ISSUE THREAD

**Issue by 1nsp1r3rnzt** [ankidroid/Anki-Android#5161]
###### Reproduction Steps

1. Click Settings
2.  Click Reviewing 
3. Click back

###### Expected Result
When a user clicks back button on a sub-setting page such as reviewing, It should take user back to the  `all settings activity` which is one step back. 

###### Actual Result
It leads user to the home page. 

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Indeed it does in 2.8.4 but this is fixed in 2.9 alohas, if you join the alpha program you will see this work https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases
