### ISSUE TITLE
Copy card should include original tags

### ISSUE THREAD

**Issue by adlew44** [ankidroid/Anki-Android#5165]
###### Reproduction Steps

1. Click on any tagged note in card browers
2. Click on copy card
3. View tags field: it will be empty

###### Expected Result
Tags field in copy note should contain all the tags for the original note

###### Actual Result
Tags field in copy note is blank

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! AnkiDroid's definition of "should" in these cases is governed by Anki Desktop behavior. What does Anki Desktop do in this case?

**Comment by adlew44** [comment]
I am using Anki so far exclusively for language learning (mainly vocabulary) and specifically Hebrew. Typical fields would include: English word; Hebrew word; pronunciation of Hebrew word; and comments.

 

Tags would include part of speech (noun, verb, etc.), and what the word is about (e.g. grammatical, number, alphabet, home, office, aviation, biblical, business, military, political, family, etc. etc.). These tags allow me to test myself on sets of words related to specific topics, which can reinforce the memorisation.

 

Now, as my studies proceed I frequently discover that there are two or more Hebrew words for a single English word, or vice versa. Or I might learn that a particular noun has an irregular plural or feminine form. These discoveries prompt me to create a new note. Naturally it is more convenient to use Copy card, because many of the field data for the copy will be identical to those in the original. Likewise, I would like the tags to be copied over as well, because most of them are likely to be the same as the original.

 

Another use of Copy card is where I have entered a whole sentence to be translated both ways, and I decide I would like to create separate notes for each word in the sentence (or most words). Copy card saves me having to remember each word: I can simply delete the other words. This is not necessarily a situation where field data and tags will need to be copied across, but it’s certainly something a use of Copy card I have found helpful many times – and it’s easier to delete data or uncheck tags than to re-enter them.

 

I hope this helps.

 

David Lewis

**Comment by timrae** [comment]
Thanks for detailing the usage case, that all makes sense, and would be happy to accept a change bringing the tags across if someone were to implement that

**Comment by adlew44** [comment]
Copy card has been changed to Copy note, but this function does not copy the old tags to the new note. So it is still a live issue.

**Comment by adlew44** [comment]
Does "closed" mean I've pulled the request? That was not my intention.

**Comment by david-allison-1** [comment]
@adlew44 This is an issue, a pull request is a selection of code which will fix the issue.

I've reopened it for you

**Comment by david-allison-1** [comment]
@adlew44 I've just coded this up, should be in AnkiDroid 2.12. Thanks for your response and your patience.

**Comment by adlew44** [comment]
> @adlew44 I've just coded this up, should be in AnkiDroid 2.12. Thanks for your response and your patience.

Great - thanks. Look forward to using it in 2.12.

**Comment by adlew44** [comment]
> @adlew44 This is an issue, a pull request is a selection of code which will fix the issue.
> 
> I've reopened it for you.

Thank you!

**Comment by choralbari** [comment]
I was just about to file the same issue, and was happy to see recent activity here. Will this be fixed in the next release? Thanks!

**Comment by david-allison-1** [comment]
> I was just about to file the same issue, and was happy to see recent activity here. Will this be fixed in the next release? Thanks!

To be fixed in 2.12, the deck picker in the dropdown will also be copied to the cloned note.
