### ISSUE TITLE
Missing field for due time / interval

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5168]
###### Reproduction Steps

1. Open card browser
2a. Long click on card to see more options OR
2b. Tap on the column name to see the field choice

###### Expected Result

There is a "show interval" or "show due time" option in the menu
OR
There is a way to choose "interval" or "due time" as field to show in the browser

Both fields can be seen in Anki desktop's card browser

###### Actual Result

I can't see the interval or due time of a card.
Interesting: 
1) in the card browser options you already have the possibility to sort by interval/due time
2) in the card options (long tap) you already have the possibility to reschedule, but without showing the actual interval ("blind" rescheduling?)

So why don't you show the interval/due time when you already have this information?

###### Debug info
AnkiDroid Version = 2.9alpha54

Android Version = 8.1.0

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
> So why don't you show the interval/due time when you already have this information?

Same reason any thing isn't done I'm guessing - ruthless prioritization of available development resources. Althku sometimes it's that the android platform does not (or did not) support it, or that desktop doesn't so we don't.

I'm guessing resources here... Maybe you can try your hand at Android programming, I am not being sarcastic, I actually find it quite fun.

Either way this feature seems possible, thanks for opening it

**Comment by timrae** [comment]
If it were to go somewhere it would be the column 2 selector, not the long
click menu. I think Anki desktop has it, we just never got around to
exposing it.

**Comment by mikehardy** [comment]
added enhancement label and needs-triage label to take a look at it for rough implementation effort

**Comment by timrae** [comment]
@Arthur-Milchior implemented interval, due time and the other fields from Anki still need to be implemented

**Comment by mikehardy** [comment]
#5549 just cross-linking the PR so people can see what is involved, the final set of changes is not so big if anyone wants to take a crack at it

**Comment by Anthropos888** [comment]
Brilliant, the new interval field in card browser is great!
Still missing from Anki desktop card browser:
- Due
- Ease
- Created
- Edited
- Changed

**Comment by Anthropos888** [comment]
All missing fields are now implemented as of 2.10alpha50. Thanks @Arthur-Milchior
