### ISSUE TITLE
Next card's question does not display if current answer has'nt finished loading

### ISSUE THREAD

**Issue by mrbryce** [ankidroid/Anki-Android#5173]
###### Reproduction Steps

1. Use a budget Android phone
2. study deck with heavy JavaScript on notes
2. Press "show answer" button and quickly press any ease button
3. Ankidroid is still loading the back card of the note but at the bottom there is a "show answer" for that next card that is not displayed
4. Press "show answer" and ankidroid skips the front card and displays directly the back card of next note

###### Expected Result
Ankidroid should skip displaying back card and start displaying next note's front card, even when JavaScript is still processing

Ankidroid should check wether front card has been loaded correctly before displaying back card

###### Actual Result
Answer buttons are out of sync with current card, forcing the user to go back to deck list and start reviewing again

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research

I'd recommend testing with the following deck:
https://ankiweb.net/shared/info/940243165

*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Very interesting! Sounds like a fun race condition somewhere. Do you have version info on Android, AnkiDroid and Chrome WebView? Also, if you have a collection you can attach that would help (maybe copy the templates and an example card into a separate deck, then export that and change the extension to .zip so you can attach here).
