### ISSUE TITLE
Force full sync option in preferences should show dialog with "cancel" as option at some point

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5176]
###### Reproduction Steps

1. Go to Settings > Advanced 
2. Tap "force full sync"
3. Sync your collection

###### Expected Result

Full sync can be cancelled. 

###### Actual Result

Full sync can't be cancelled! It will force full sync no matter what I'm doing!
I accidentally tapped on the above setting and it just showed "ok". But I thought it's a menu where I can choose an option. This behaviour is definitely NOT OK, so it's kind of sarcastic to see the "ok" dialog. My collection is huge and on Android it needs forever to do a full sync, so I strongly recommend to add a way to cancel the full sync. The setting should be:
"Always force full sync" > "on/off".

###### Debug info
AnkiDroid Version = 2.9alpha54

Android Version = 8.1.0

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by Anthropos888** [comment]
Yes, that's what I mean. An extra dialog that tells me "if you press OK the next sync will fully sync your collection in one direction". Users should have the possibility to click cancel at this point. Then everything is fine.

**Comment by mikehardy** [comment]
Got it, dialog boxes / control flows are usually trivial changes, this should be okay. I can certainly understand - my collection is about 20 minutes for a full sync as well. Not the end of the world, but not fun either.

**Comment by mikehardy** [comment]
You're not the only one that thinks this way, found this in the code: 

```
                    // TODO: Could be useful to show the full confirmation dialog
```

https://github.com/mikehardy/Anki-Android/blob/7855dd0216828320fe46081b4407910661d58202/AnkiDroid/src/main/java/com/ichi2/anki/Preferences.java#L318

**Comment by mikehardy** [comment]
@Anthropos888 this and the database check progress just went live with the new alpha please give them a test and reopen if they're not working. Thanks for the continued help

**Comment by Anthropos888** [comment]
Works perfectly, thanks for the fast implementation!
