### ISSUE TITLE
Introduce "Ask Later" Button

### ISSUE THREAD

**Issue by LechnerMartin** [ankidroid/Anki-Android#5183]
I love Ankidroid, but I really miss this kind of functionality. 

My use case:
I want to go through the easy cards first (on the go) and skip harder cards for a few minutes. (Kind of sleep functionality) until the easy ones are finished and I can fokus on the hard ones.

Bury is not working as I can only do it for a day - but I want only to skip a card for a few minutes or move it to the end of.todays schedule.

Any chance to get it implemented?

Br,
Martin

**Comment by mikehardy** [comment]
If it isn't in Anki Desktop, in general, it likely won't be implemented. And this is not in Desktop that I know of? So I will close this but if I'm wrong, do reopen it pointing to the manual on the feature

That said, the alphas have "reposition", and "reschedule" in the option menu for a card (or you can add it to the action bar as a button with a little dropdown.

one of those may work acceptably? Though it will need one last pull request merged before it works well (right now you do it but a new card isn't displayed, sort of defeating the purpose) so it won't be until 2.9alpha55 (or whichever alpha post-merge is released):
https://github.com/ankidroid/Anki-Android/pull/5180

https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases

Alternatively, there is some pretty advanced querying that you can do in the card browser, and it might be possible to create (and then save) a query for things you rated "hard" and reviewed in the last day, so you can review without any scheduler fiddling, and then later give a close look at tough ones? The query syntax is documented in the desktop manual and you'd just play with it in the card browser to see if it was workable

Hope this helps?

**Comment by LechnerMartin** [comment]
Thanks for the quick answer.
I will look into reposition/reschedule maybe it does what I need.

The filter will not work as I don't want to mark the card as hard - which would mean I have to answer it. I just want to skip it for a few minutes or move it to the end of today. 

If nothing works, I will try to get this feature into the desktop version first;)

Br,
Martin
ML

**Comment by eginhard** [comment]
The workflow for this would be to bury these cards and then unbury all cards in the deck when you want to get back to them at the end of the day. In AnkiDroid you can do this by long-pressing on the deck and selecting "Unbury".

**Comment by LechnerMartin** [comment]
Hello Enno,

Unfortunately this solution is not working (tried it already) as Anki also buries related cards (siblings) which i dont want to unbury (I have many multicard notes).

But you are right - something similar would solve the problem - if the siblings would stay buried.

Br,
Martin
