### ISSUE TITLE
Newlines ignored in deck description

### ISSUE THREAD

**Issue by rathsky** [ankidroid/Anki-Android#5188]
Unlike Anki desktop, AnkiDroid ignores newlines in deck descriptions which aren't BR tags, instead pushing it all into a single line.

You can easily check it by adding such a description on desktop, syncing it, and then viewing the result in AnkiDroid.

**Comment by andersan** [comment]
@rathsky Where in the app is this behavior occurring? I don't see it but very well might be missing it.

I added this deck description using anki desktop for linux, not sure if that has any impact on the test results. 

![50927175_339047243370252_2292155532556894208_n](https://user-images.githubusercontent.com/12814577/52017345-1a463500-24b5-11e9-89bc-c08d410f5e0b.jpg)

**Comment by rathsky** [comment]
When clicking on the remaining on the deck's due cards count in AnkiDroid's main menu. Which only opens the dialog if there are actually any left for the day.

**Comment by mikehardy** [comment]
The fix didn't cherry-pick cleanly to 2.9.x because intermediate changes were missing, and it's not vital so moving to 2.10 release target
