### ISSUE TITLE
NOT a issue，new feature requirement

### ISSUE THREAD

**Issue by alexwyl** [ankidroid/Anki-Android#5189]
Dear All:
Is it possible to adjust the font size while leaning cards? it's quite small on my e-ink reading device.
Thanks a lot.
Wu

**Comment by mikehardy** [comment]
Have you tried the appearance area in the settings?

**Comment by p3l4h0** [comment]
Which e-ink device do you use ?

otherwise you can change the size of the font in the settings.
The 3 dashes at the top left in ankidroid - general - appearance - change the last punk to for example 150%.
i use it in german, so the names are a little bit different ;)

**Comment by alexwyl** [comment]
> 
> 
> Have you tried the appearance area in the settings?

@mikehardy Thank you for your kind replay. 
I have tried all the settings, but can not find a solution. This really frustrate me, because I'm a IT guy...

**Comment by alexwyl** [comment]
> 
> 
> Which e-ink device do you use ?
> 
> otherwise you can change the size of the font in the settings.
> The 3 dashes at the top left in ankidroid - general - appearance - change the last punk to for example 150%.
> i use it in german, so the names are a little bit different ;)


@p3l4h0 Thank you for your kind replay. I have tried all the appearance settings, including the last option [Card browser font scaling], this option affect only THE Card Browser function but not the card learning function. 
BTW: The version of my e-like device is android 4.0, firstly I think this may be the problem. but I try ankidroid on my cell-phone, the same "problem".

**Comment by alexwyl** [comment]
AND I can zoom in the card learning UI by the two fingers gesture, but I have to do it on every card while learning, and each card twice, one for the card, the other for the answer. this is far not a effective way for leaning.
Thanks.

**Comment by mikehardy** [comment]
You may need to edit the card templates and use some CSS to achieve the results you want
