### ISSUE TITLE
Feature Request "Making "parallel" builds"

### ISSUE THREAD

**Issue by p3l4h0** [ankidroid/Anki-Android#5190]
No Real issue
*The issue is my device is too slow for a linux emulation in windows.
the memory is too small for a 2 installation with linux.
And the budget is too small for a new computer :)*

so, is it possible to make the script also available for windows. for example in a .bat file or similar ? 

i searched several times through android studio and the github files to get a new build (ankidroid.A). Unfortunately the APK can not be installed. So I definitely make a mistake somewhere :D

I hoped to be able to eliminate the error with a simple click and ready solution.

Many thanks and happy new year

**Comment by mikehardy** [comment]
Hi there, parallel builds are android only. The desktop client supports multiple profiles built in

**Comment by p3l4h0** [comment]
Thanks for answering, but i was in trouble with my windows machine to create a Android apk.

When I am trying to edit everything correct in the AndroidStudio software and compiling the apk. I can't install the APK on my phone.
i think i made some mistakes while editing, so i hoped for a script (windows .bat) that runs under windows. which does the work for me without any mistakes.

**Comment by timrae** [comment]
@p3l4h0

If you have a recent version of Windows 10 you can install the windows subsystem for linux, which will give you a bash shell without using a virtual machine. This is what I do on my windows machine, it works very well.

**Comment by p3l4h0** [comment]
Thanks you both for this fast and easy, and the subsystem solution
