### ISSUE TITLE
Syncing with syncthing

### ISSUE THREAD

**Issue by qazip** [ankidroid/Anki-Android#5191]
Hello,

I want to sync my anki database/decks/folder with syncthing. I have syncthing configured but I can't find out how to change the folder where ankidroid stores the decks and whatnot.

The idea was to sync ankidroid with my ankidesktop. How would I go about doing that? I don't use to use the ankiweb for privacy reasons.

**Comment by mikehardy** [comment]
If you want a non-default location, it won't be supported, yet it is possible:
https://github.com/ankidroid/Anki-Android/wiki/FAQ#my-ankidroid-files-are-stored-on-a-sd-card-how-can-i-point-ankidroid-to-them

If you want a private sync server, you may try:
https://github.com/tsudoko/anki-sync-server for Anki2.0

...or:
https://github.com/tsudoko/anki-sync-server for Anki2.1

(as mentioned here: http://genedan.com/no-127-ankisyncd-a-custom-sync-server-for-anki-2-1/ )

Either way - this is not really an issue - this would be a good discussion for the mailing list...

**Comment by qazip** [comment]
Thank you for the prompt reply @mikehardy. That seems to require a bit more work than what I plan to do right now. Do you know of any public anki-sync-server (based on tdudoko's code)?

**Comment by mikehardy** [comment]
Nope, AnkiWeb doesn't share your decks unless you specifically share them so there's no point in anyone starting a public Anki sync server that isn't AnkiWeb.

The choices are really "use AnkiWeb", or invest the time and do it yourself

**Comment by qazip** [comment]
Well, the point is using an open-source solution. As far as I understand, ankiweb is not open-source, is it?

**Comment by mikehardy** [comment]
AnkiWeb is not open source. However, even if a public server says it is using open source, you can't know that since it isn't your infrastructure. So the 2 choices are still the same in the end.

**Comment by qazip** [comment]
Well, I disagree with your conclusion but fair enough. Thank you.
