### ISSUE TITLE
Allow to rename images before copying into collection

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5192]
###### Reproduction Steps

1. Open card editor
2. Click on edit symbol next to an image field
3. Click on "gallery" and choose an image

###### Expected Result

Long press on the image shows several options as in the standard file browser. Especially "rename" should be possible.

###### Actual Result

No long press, no functions at all. I can't rename the picture. I need to leave AnkiDroid and open the standard file browser in order to rename the image. 

Also: it can cause synching problems if the filename of the image (let's say "download.jpg") already exists. So the rename function should be essential here. Also it is highly unlikely that users want to keep the default name of downloaded images (these names are often ridiculous long) so renaming them before copying to the collection makes sense.

###### Debug info
AnkiDroid Version = 2.9alpha55

Android Version = 8.1.0

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
How does Anki Desktop handle this?

**Comment by Anthropos888** [comment]
Well, in Anki desktop you can just drag and drop any picture (local or from a website) into the image field. That would be the ultimate solution, but I think it's highly unlikely to realize this on Android.

Abiut renaming on Anki desktop: that's not an issue since you can rename the picture at any place and then just drag and drop it into the image field. For example, you could have opened chrome, anki and your desktop next to each other, then drag an image from chrome to the desktop, press F2 to rename it and then drag it into Anki's image field. Just a matter of seconds.
On Android things are way more time consuming so a rename function would save a lot of time since you don't need to switch forth and back from Anki to the file browser etc.

**Comment by mikehardy** [comment]
I get that renaming is a big pain on Android (where task switching is terrible) vs the desktop, what I was hoping for was how Anki Desktop handles it when you attempt to import a new media file that has the same name as the old media file. Sorry if I wasn't clear!

As for drag-n-drop, the most useful analog for Android will be if the clipboard issue is resolved with support for images #5023 (which supercedes #3426)

**Comment by Anthropos888** [comment]
Anki desktop has an "add image/audio/video" button (or press F3) in the card browser/card editor. That button opens a small file browser where you can navigate to your picture. The context menu there allows "rename", "delete" and "new folder" which are all very useful in my eyes.

Would be great if AnkiDroid could copy that.

**Comment by mikehardy** [comment]
Okay, I see what you're saying and I don't disagree, but I have a very specific question about collisions:

> how Anki Desktop handles it when you attempt to import a new media file that has the same name as the old media file.

Assume you do no rename. Your collection has "foo.jpg" already (used in card 1). You attempt to import another media file "foo.jpg" on a new card (or while editing card 2). What happens to foo.jpg-original, foo.jpg-new, card 1 and card 2?

**Comment by Anthropos888** [comment]
Did you read my edit? The old picture remains untouched. The new picture will be renamed to "foo (1).jpg" automatically before copying it to the collection.

**Comment by mikehardy** [comment]
Just read the edit now, sorry :-). Interesting. I think they must be using the operating system copy, and at a low-level operating system copies on desktop operating systems handle name collisions like that. Hmmm

**Comment by mikehardy** [comment]
Would you agree in principle that this is two separate issues? One is a bug where we don't handle name collisions like desktop. The other is an enhancement requests to support all the import media features (rename) etc. I say that because handling collisions should be relatively easy and something we should do quickly, whereas enhancement requests always take longer. If you agree, I'd keep this one for the enhancement request, and a new issue with a laser focus on "handle media import filename collisions like Anki Desktop" would be good

**Comment by Anthropos888** [comment]
Ok, sounds good!

**Comment by david-allison-1** [comment]
This needs a fair bit of refactoring work before it goes in. There's a lot of unnecessary state usage in the current class, and I'd rather not add to the complexity

**Comment by prateek-singh-3212** [comment]
@mikehardy @david-allison-1 is this issue is valid now?

**Comment by mikehardy** [comment]
Maybe, I just reread it and I'm not sure what the exact spec for the feature should be as it is entangled here between collision and rename on import. Without a clean / complete specification it's not a good issue to implement. If you want to check out how desktop does optional rename on import and try to specify the feature first that is the first step, then we can think about it again
