### ISSUE TITLE
Incorrect information about new cards in deck if > 1000 in 'Custom study/increase today's...'

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#5197]
###### Reproduction Steps

1. Make sure there are > 1000 new cards in a deck.
2. Long-press the deck, choose 'Custom study', then 'Increase today's new card limit'

###### Expected Result
The dialog shows the correct amount of new cards (3250 in my case) or (just like Anki Desktop 2.1.7, Mac Os) '1000+'.

###### Actual Result
The dialog says: 'New cards in deck: 1000', which is simply not true (made me go re-check if my import worked correctly).

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
@wujek-srujek pay attention in the next alpha after today, this may be resolved for you

**Comment by malnvenshorn** [comment]
@mikehardy if it's just a display issue the limit should not be in scheduler bur rather when setting the text view, e.g. `min(count, 99999)`. Setting the limit in the scheduler means that the return values might be wrong.

**Comment by mikehardy** [comment]
While true, we keep the scheduler etc as close the the desktop code as possible, if this would break compatibility - even in ways of display - we'll typically do the same thing unless we consider it carefully like in the case of even displaying more than 1000. That said, I would assume desktop does show correct return values or that our changes will do the same. If it does not, open an issue

**Comment by malnvenshorn** [comment]
If you're already deviating by changing the value to `99999` why not setting it to `-1`? This shouldn't limit the results. The view can then be set by `max(count, 1000)` or `count > 1000 ? "1000+" : count` (don't now how it is displayed in the desktop version).

I'm not proposing this without an ulterior motive :wink: For my implementation of the progress bar I need the correct values. Workaround for now writing own methods without the limit (duplicated code)

**Comment by mikehardy** [comment]
Oh yeah - I was going to propose that you make a PR, but you are working on one ;-). You are likely closer to the code than I am, if it is something your PR changes, have an opinion on it (in an engineering sense that is: take a defensible stance with your code) and propose it as part of your changes?

**Comment by david-allison-1** [comment]
Fixed
