### ISSUE TITLE
Allow adding bulleted lists

### ISSUE THREAD

**Issue by EGecius** [ankidroid/Anki-Android#5198]
Can we please have bulleted lists in cards?

Like this one here in Github:
![image](https://user-images.githubusercontent.com/3499732/50886090-6f77b500-13e7-11e9-8283-e801411b27db.png)

**Comment by Alphyn-gunner** [comment]
I believe, you can just use html tags in your fields to achieve this.

**Comment by EGecius** [comment]
thanks for your reply. Possibly so but I think you would agree that this would be practically unusable on a phone screen.

I can't imagine myself or almost anyone else coding on a phone screen :)

**Comment by mikehardy** [comment]
Haha that's quitters talk. But seriously yes, the wysiwyg html editing enhanceme request is popular for good reason.. Would you consid this a duolixate of that one? Seems to me yes, and a thumbs up there might be the most useful thing

**Comment by EGecius** [comment]
yes, I don't mind if your prefer bullets and lists to be a part of 
'wysiwyg html' issue. Up to you :)

**Comment by EGecius** [comment]
if so, I am happy for this issue to be closed :)

**Comment by david-allison-1** [comment]
To be fixed in #1377
