### ISSUE TITLE
Learning cards disappear after deleting a custom deck

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5199]
###### Reproduction Steps

1. You have a deck with new cards (blue), learning/wrong cards (red) and due cards (green)
2. Long press -> custom -> tags -> only due cards
3. The learning cards (red) appear as new cards (blue) in the custom deck
4. Delete the custom deck without doing reviews: now the blue cards (former red cards) will not be send back into its original deck

###### Expected Result

1) if a deck has red cards, these red cards should also be red in the custom deck, not blue! Why should red cards (learning or wrong) be treated as new??

2) when deleting a custom deck, all remaining cards should be send back to its original deck as if nothing happened. But that's not the case. The former red cards don't show up as red cards anymore. In fact, I couldn't see them at all, not as green and not as blue cards (the number of new and due cards are heavily limited in my deck options, so maybe that's why other cards have priority).

###### Actual Result

1) red cards turn into blue cards
2) blue cards disappear after deleting the custom deck

###### Debug info
AnkiDroid Version = 2.9alpha56

Android Version = 8.1.0

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

**Comment by mikehardy** [comment]
Interesting - this looks subtle. Have you seen if the same thing happens with Anki Desktop? I know you are in the power user category for both - for scheduling we did a pretty straight port from the Python so this may happen there as well (meaning we should open an issue with Anki upstream), or it may have been fixed upstream and we have not ingested the fix...

**Comment by Anthropos888** [comment]
I will try to reproduce it on desktop tomorrow.

**Comment by mikehardy** [comment]
Thanks @Anthropos888 - I appreciate the help

**Comment by Anthropos888** [comment]
Ok, I just tried it and it's exactly the same problem on Anki desktop: red learning cards will be converted to new blue cards, when you create a custom study deck with the tag "only due cards". So now the custom deck doesn't have any learning cards, and the original deck only remains with new blue cards (the default number for new cards per day for that deck.

After deleting the custom deck, the blue cards will be send back to the original deck. There they will mix with the other new cards.

That leads to the result that your previous learning cards (priority cards) will not be shown in the next review session since they have no more priority and got mixed with the other new cards.

Hopefully Anki desktop will fix this. Can you forward it to them?

**Comment by mikehardy** [comment]
I will open an issue in their tracker - thanks for checking this, it was subtle enough with the direct port I had a strong suspicion it was everywhere in the ecosystem...

**Comment by mikehardy** [comment]
I have opened a discussion upstream, linked here, and will cross-link here: https://anki.tenderapp.com/discussions/ankidesktop/32038-unexpected-scheduling-behavior-when-custom-study-cards-return-to-original-deck

**Comment by mikehardy** [comment]
Per Damien upstream, [this is a known issue](https://anki.tenderapp.com/discussions/ankidesktop/32038-unexpected-scheduling-behavior-when-custom-study-cards-return-to-original-deck#comment_46810434) and is fixed in the v2 scheduler which AnkiDroid doesn't support yet #4905  (though the raw port of the scheduler code has been made #5164)

So this isn't a viable stand-alone issue but those cross-links should help future folks

**Comment by Anthropos888** [comment]
For your interest, I just could locate my cards that got "lost" through the scheduling bug: they are still there, but they are now "new" cards with a very high number as due time (It seems Anki just gives them the highest number in the queue (+1). So if users don't encounter that bug, they will never see the card again until the very last new card in their deck. 

That's quite a problem. I understand that it's not easy to rewrite the whole scheduler v2 for AnkiDroid, but is it possible to just change the part where a new due time is set for those cards? The new due time should be a real date or at least the first number in the queue, not the last.

**Comment by mikehardy** [comment]
That is a possibility, and may (or may not, I have not looked) be a quick fix that at the same time is a bit different than upstream but not in a bad way. I'll reopen this at least for the triage on whether it's easy or not

**Comment by Anthropos888** [comment]
Thanks! To clarify what integer exactly should be set as "due" value: the cards that are affected by this bug are "learning" cards, so previously they had an integer timestamp already as due value. If you can just somehow access this timestamp, then use it again when the filtered deck is created and when the filtered deck cards return to their home deck.

Otherwise use an integer that is smaller than the queue's first card's "due" value (>= 0). The card was a learning card before, so if it turns into a new card again, it should have priority before all other new cards.

**Comment by Anthropos888** [comment]
BTW, is it safe to use the newest Anki desktop version with scheduler v2 or will it cause any problems during sync? I'm still using Anki 2.0 (not for reviews) because I'm not sure if 2.1 will mess up any scheduling information during sync.

**Comment by mikehardy** [comment]
You may use the newest Anki desktop version, but the schedulers do not interoperate. Which scheduler you use is stored in the global collection conf object and the Desktop version can switch a collection between the two, but if a collection has moved to scheduler v2 I do not believe it will sync and work correctly with AnkiDroid

**Comment by Anthropos888** [comment]
Fixed with scheduler v2. I'm going to close this.
