### ISSUE TITLE
Do not reset zoom when revealing answer

### ISSUE THREAD

**Issue by qsantos** [ankidroid/Anki-Android#5201]
I have found no information about such a feature, online, or in the project's issues. This might not be important, but I wanted to share the idea.

Some of my cards require me to locate a map in a map of France. Because the map is too complex, I usually have to zoom in to see the different rivers. AnkiDroid's zoom works great. However, when revealing the answer, the zoom is reset, which is slightly annoying. Of course, I should fix the maps so that I do not have to zoom, but I thought it might be a UX improvement for AnkiDroid. [Some people might not like this change](https://xkcd.com/1172/), so it may require an additional setting.

**Comment by Anthropos888** [comment]
Question and Answer are like two seperate html files, and showing the answer will load the answer.html (just an example) and overwrite the question.html. But you can read and save information about the zoom level (css "zoom") via javascript into "window.name". This will set the window name for the reviewer window, which doesn't have any effects on your reviews, but on Anki and AnkiDroid this information is saved until you leave the reviewer.

That means, you could read and save the zoom level in the question template, and reset it in the answer template. That would work on Chrome desktop but I have no idea if it can influence your Android zoom level. 

I would do the following: add a separate "show answer" button into the question html. On click, this button will show the previously hidden (css) answer. That doesn't require any page reload so your zoom will remain as it is.

After that you'd still need to press Ankidroid's show answer button to choose the difficulty.
