### ISSUE TITLE
[2.8.5-beta1] Exporting a filtered deck makes it "locked" and impossible to review

### ISSUE THREAD

**Issue by yoshi314** [ankidroid/Anki-Android#5202]
###### Reproduction Steps

1. create a filtered deck with e.g. "added:1" as a filter
2. export that filtered deck to file
3. try reviewing that filtered deck

###### Expected Result
It works

###### Actual Result
"Deck cannot be opened" error message suggestion to check the database. Check database does not help, restarting the app does not help. 

Deleting the filtered deck completely and creating it again helps. Rebuilding the deck does not help.

I did not try to change the search query, though.

All other decks work fine when this one is locked, including the parent deck.

###### Debug info
AnkiDroid Version = 2.8.5beta1
Android Version = 7.0

ACRA UUID = 7367d681-e5e5-4003-92b4-d272902208ab

###### Research
[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
We believe 2.10alpha52 (released yesterday) has a fix for this
