### ISSUE TITLE
Browser preview: navigation buttons missing

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5220]
###### Reproduction Steps

1. Open card browser
2. Long tap on a card > preview 

###### Expected Result

Navigation buttons are showing

###### Actual Result

No navigation buttons. I can't navigate through the cards. It worked in alpha <58 but since 2.9alpha58 it's broken

###### Debug info

AnkiDroid Version = 2.9alpha60

Android Version = 8.1.0

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
Now we have multi-select, so it's setup to preview through only the cards that you selected. I just checked Anki Desktop and what we've done is a bit different from how it's done there, so we'd better fix it. Actually IIRC @mikehardy originally implemented it the same way it was done in Anki Desktop and I asked him to change it... doh.

**Comment by Anthropos888** [comment]
I see, indeed it works when more than one card is selected. But this seems not to be obvious. Also, many first time users in the forum ask about "how can I see all my cards" and the answer usually is "open the card browser, long tap the first card, choose preview and use the buttons to navigate".

This won't work anymore in the new alpha

**Comment by timrae** [comment]
I've submitted a fix, it should be released sometime over the next few days
