### ISSUE TITLE
Using the ContentProvider API, is it possible to list subdecks as a tree ?

### ISSUE THREAD

**Issue by lucwastiaux** [ankidroid/Anki-Android#5224]
###### Reproduction Steps

Listing all decks using `FlashCardsContract.Deck.CONTENT_ALL_URI` lists all decks in the tree hierarchy without distinction.

###### Expected Result

I expect to see something like "parentDeckId" in the results in order to be able to rebuild the tree the same way ankidroid does it.

###### Actual Result

Decks are returned as a flat list.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
I don't think this is currently supported, but feel free to submit a PR!

**Comment by lucwastiaux** [comment]
Thank you, I will get around to it eventually. Closing the issue for now.
