### ISSUE TITLE
Black screen since updating to Android 8.1

### ISSUE THREAD

**Issue by DJSorg** [ankidroid/Anki-Android#5226]
###### Reproduction Steps

1. Since I updated to Android 8.1, I can't normally use Ankidroid. Every 5 minutes durint my work, my screen become black so I can't use the apps anymore. I need to restart my tab (Lenovo Tab 4 8 plus) to solve it, but the same occur after 5 min when I reload the app.
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
We have more than a hundred thousand users on Android 8.1 and this does not occur. I personally used Android 8.1 to review with AnkiDroid for around a year without issue. I think something is wrong with the device or the configuration of the device but is specific to your device. You might try an uninstall / reinstall of AnkiDroid, or a factory reset or similar - but of course be careful with your data by taking backups etc

**Comment by timrae** [comment]
Yeah definitely at least try a: Uninstall -> Reboot -> Reinstall

**Comment by DJSorg** [comment]
Hi,

Thanks for your advices. I tried to Uninstall and Reinstall, I'll see if the problem occurs again.
I'll let you know :)

Kind regards,

Nico
