### ISSUE TITLE
incorrect review counts

### ISSUE THREAD

**Issue by slesniak** [ankidroid/Anki-Android#5235]
###### Reproduction Steps

Make a deck with a child deck and grandchild deck.  If the grandchild deck has review cards, the grandparent or great grandparent decks will show review count as 0 on the main screen (deck view)

This bug did not exist for me on the Play store version of the app, only on the alpha branch.  I'm using the V2 scheduler.

###### Expected Result

accurate count (41 new, 9 relearning, 262 pending reviews according to Anki desktop)

###### Actual Result

0 count for reviews in deck 'all' in screenshot below
Screenshot: ![screenshot_20190212-170332 ankidroid](https://user-images.githubusercontent.com/1088320/52679242-516f0a00-2ee9-11e9-92e6-766f7bc1e84d.png)

(Anki desktop 2.1.8 reports 41/9/262, Anki shows 41/9/0)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x, sort of ] I have searched for similar existing issues here and on the user forum

What user forum? The Anki tenderapp (https://anki.tenderapp.com/discussions/ankidroid) just directs Ankidroid people here: https://docs.ankidroid.org/help.html

**Comment by mikehardy** [comment]
@hssm hopefully tagging you on these is appropriate - I figure you know the v2 stuff cold at this point...

**Comment by timrae** [comment]
He previously said that he's only getting notifications on that one specific issue #4905

**Comment by hssm** [comment]
Any chance you could send me a copy of that collection for me to look into?

**Comment by slesniak** [comment]
@hssm  my current collection is >25,000 notes and >32,000 notes, so I created a minimal test case here: [testcollection5235.apkg.zip](https://github.com/ankidroid/Anki-Android/files/2861330/testcollection5235.apkg.zip)

Here's how that appears on desktop:

![screen shot 2019-02-13 at 8 59 23 am](https://user-images.githubusercontent.com/1088320/52729298-bec47e80-2f6d-11e9-9843-22fd0c856938.png)

And on Ankidroid
![screenshot_20190213-090110](https://user-images.githubusercontent.com/1088320/52729475-1bc03480-2f6e-11e9-9869-206bea2d693c.png)

The review count on the grandparent and test deck-grandparent decks is 0 on Ankidroid and 1 on Anki desktop in that view.

**Comment by slesniak** [comment]
resolved in  AnkiDroid-2.9alpha64.apk
