### ISSUE TITLE
BUG Caused by different quotationsmarks surrounding a filepath when adding it on Wndows 10 vs Android

### ISSUE THREAD

**Issue by Brewstr78** [ankidroid/Anki-Android#5237]
###### Reproduction Steps

1. Add this code snippet to a card that have a field named "Image" on Ankidroid.

<div id="myImg"></div>

<script>
var image = "{{Image}}";

document.getElementById("myImg").innerHTML = image;

</script>

2. Load an image into the cards field named Image and display the card. It will work. Everything will be fine, however.

3. Export the deck with the code from ankidroid to Windows and load a new image, the card will not display, throwing the following error:

SyntaxError: Unexpected identifier

The reason is that when a imagefile is loaded on windows it is given double quotation marks around it path.

In JavaScript you can't have double quotation marks inside double quotation marks. You need to have single or vice versa.

On windows changing the JavaScript code line:

var image = "{{Image}}";

Into using single quotation marks:

var image = '{{Image}}';

Will make it work on windows.

However, now if you export your deck back to Ankidroid your cards will break if you load images into them or make new cards with images on your Android device.

I suspect this inconsistency might be behind other problems people might have.

Solution: The Ankidroid should use same kind of quotation double marks around a file when it loads it.

The reason for using a javascript to place images was that I wanted to have random images displayed on my cards. Such as this:

https://www.reddit.com/r/Anki/comments/6pjuwu/showing_a_random_image_from_a_set_of_images/

###### Expected Result

Display the image

###### Actual Result

Card do not display instead Anki or Ankidroid throws the following message:

SyntaxError: Unexpected identifier

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I'm not exactly sure, but it seems to me that field replacement happens here https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java

I can't find a spot in there where it's pattern-matching in a way that would discriminate between single or double quote though.

You might try the alphas (https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases) and the new ability to view the rendered HTML of a card, or even to attach a Chrome debugger to the WebView - https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by Brewstr78** [comment]
I appreciate you look at this.

I'm not a coder unfortunately, but I will see if I can send you an image.

And see if I can try the alpha.

**Comment by mikehardy** [comment]
> I'm not a coder unfortunately, 

Setting yourself up for the alphas and looking at the rendered card HTML should be possible without coding skills - give it a shot and I think it'll be possible

> but I will see if I can send you an image.

I don't believe that will help, but feel free to attach one here if you like

**Comment by Brewstr78** [comment]
When I open a card with an image exported from Anki on Wndows the pathname to the image looks like this in the entry field:

<img src="image.jpg">

If I add a file on Ankidroid on Android v9.

The filepath will look like this:

<img src='image.jpg'/>

The anikdroid filename breaks the JavaScript if the script use single quotation marks to load the field into a variable.

**Comment by Brewstr78** [comment]
It appears I needed to enclose the names in html tags...

Windows field filename:

img src="img.jpg"

Ankidroid field filename:

img src='img.jpg'/

Hope this works.

**Comment by mikehardy** [comment]
released in 2.9.6beta4
