### ISSUE TITLE
Widget cards due message does not support pluralization

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5240]
###### Reproduction Steps

1. Use crowdin to translate the `"%d AnkiDroid cards due` message in 08-widget - https://crowdin.com/translate/ankidroid/8171/en-lt#2604631
2. Try to select for plurals
3. 

###### Expected Result

You can translate strings for different quantity groupings

###### Actual Result

Only one translation is possible

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I just made a PR for this, but unfortunately even after that there is a CrowdIn sync that needs to happen. I have all the credentials to do that but I've never done it before which makes me very, very cautious. If anyone with experience can do it after this is resolved in master that would speed this up

**Comment by timrae** [comment]
I just did the crowdin sync

**Comment by eginhard** [comment]
Thank you both, looks good!
