### ISSUE TITLE
Feature request: Ability to change the thickness of the whiteboard / drawboard pen

### ISSUE THREAD

**Issue by Xyde** [ankidroid/Anki-Android#5243]
I'm using Anki to learn some drawing principles by having an image backdrop then drawing the assignment over it. However, the default line thickness is a bit too much since it covers way too much of the backdrop and hides important visual cues. The problem is exacerbated on my tablet (1024 x 768) might be because of the low resolution. An option in the settings would be nice.

**Comment by timrae** [comment]
Stroke width setting has existed for years
