### ISSUE TITLE
Fullscreen mode not showing properly

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#5245]
Probably related to #5156. Probably caused by an appcompat update at some point along the way.

![screen shot 2019-02-17 at 13 22 53](https://user-images.githubusercontent.com/2818274/52908353-98794880-32b7-11e9-95a7-f995c1e16434.png)

**Comment by timrae** [comment]
Woah, the weird thing is that when I turn the screen off and back on again, it magically starts working lol. Thanks again Google.

**Comment by mikehardy** [comment]
I'm sure you it's something we're doings wrong that's buried in 20000 pages of documents. We are probab also messing this top area up on notched phones now that I think about it...

**Comment by timrae** [comment]
Actually it's not necessary to turn the screen off... The very first time you exit immersive mode it will display incorrectly like above, but from the second time onwards it displays correctly. I had a quick play around with it and it doesn't seem to be related to the status bar opacity setting (i.e. the issue persists even when the status bar is set to be transparent), so it may not be related to #5156, which I have a fix for.

**Comment by timrae** [comment]
After spending a few hours looking into this, I found that the culprit is the `SYSTEM_UI_FLAG_LAYOUT_HIDE_NAVIGATION` flag. Our code is pretty much just exactly what's shown in the [fullscreen tutorial page](https://developer.android.com/training/system-ui/immersive#EnableFullscreen), so I believe this must be a bug in the support library, although it's hard to know what those guys are thinking sometimes.

Removing this flag has very little effect on the reviewing experience, though I do personally prefer keeping it set.
