### ISSUE TITLE
Bug in Anki's database schema? `sfld` an integer?

### ISSUE THREAD

**Issue by jasonsparc** [ankidroid/Anki-Android#5252]
Hi! It seems that AnkiDroid has the same bug as I reported for Anki Desktop. See,
https://anki.tenderapp.com/discussions/ankidesktop/32752

---

https://github.com/ankidroid/Anki-Android/blob/ee463c2a3e20c0a8eea3c467a37b5f1b08f73f15/AnkiDroid/src/main/java/com/ichi2/libanki/Storage.java#L301

Now, I'm actually curious about whether this was intentional.

**Comment by jasonsparc** [comment]
Although, this wiki doc would be contradicting otherwise:
https://github.com/ankidroid/Anki-Android/wiki/Database-Structure

^ In that page, it said that `sfld` is a `text` and not an `integer`:
```
sfld            text not null,
      -- sort field: used for quick sorting and duplicate check
```

**Comment by david-allison-1** [comment]
sfld is an integer column. Storing text. I've updated the wiki page
