### ISSUE TITLE
Deck option group changes after deck export

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5253]
###### Reproduction Steps

1. Have a deck with an own option group (other than default)
2. Choose "export" from menu, untick the checkboxes and export
3. In the following dialogue choose "save file" and save to any folder

###### Expected Result

The export won't change anything on my collection

###### Actual Result

The export causes the option group of the exported deck to change to "default". That means, all cards will eventually be re-sorted, all deck settings will change and AnkiDroid will most likely require a full sync (so in my case).

The original deck option group is still there, users have to switch manually back to this group and cards will (eventually) be re-sorted. 

This sorting and syncing forth and back costs a lot of time and in addition it's not sure if the original sort order or anything else might be screwed up now (Anki desktop is needed to check this since there's no way to view the due time on Ankidroid).

###### Debug info

AnkiDroid Version = 2.9alpha66

Android Version = 9

ACRA UUID = f2d13677-d957-460e-9f8e-33ca6f832c17

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Cause:

https://github.com/ankidroid/Anki-Android/blob/f1ac587bc8737624a2ff540787d420db5454b9db/AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java#L195-L198

**Comment by Anthropos888** [comment]
Great! Thanks @david-allison-1  I assume that this one is easy to fix?

**Comment by david-allison-1** [comment]
@Anthropos888 I came across this when searching for another mystery. You saved me a ton of effort. Thanks for the report!

**Comment by Anthropos888** [comment]
Haha, no problem. There's another export-related issue, that should be easy to fix since the code already exists upstream: https://github.com/ankidroid/Anki-Android/issues/5643

Maybe both fixes can make it in one of the next releases so that AnkiDroid finally has an export feature which is actually working ;-) (so far I'm always using desktop for exports)

**Comment by david-allison-1** [comment]
@Anthropos888 No promises, but I'll aim to get through it by the end of the week.

Anything else that's bugging you?

**Comment by Anthropos888** [comment]
@david-allison-1  Actually yes, this one:
https://github.com/ankidroid/Anki-Android/issues/5741
It makes reviewing in fullscreen quite bothersome. And it's not obvious to me how the behavior could be fixed. The perfect issue for Sherlock Holmes ;-)

**Comment by Anthropos888** [comment]
This one works as of alpha53. Thanks @david-allison-1

**Comment by david-allison-1** [comment]
Awesome, thanks for the feedback @Anthropos888 :D
