### ISSUE TITLE
V2 Scheduler Support in PR or Fork?

### ISSUE THREAD

**Issue by dwalton0** [ankidroid/Anki-Android#5254]
Hi,

Beginning level programmer here. I've been reading through previous issues and trying to assess whether the PR now includes support for Anki 2.1 v2 Scheduling, or whether there is a semi-stable fork/source code I can compile and install as part of testing a partly finished feature. 

Kindly let me know if the PR is functioning for V2 scheduling, or where I can obtain a partially-stable version that includes this feature. Happy to provide feedback and aid in development however I can. Thank you!

**Comment by timrae** [comment]
It's already merged into master, and semi-stable. You can use by subscribing to the alpha channel or downloading directly from github.
