### ISSUE TITLE
Change deck options review/new card total updates all decks.

### ISSUE THREAD

**Issue by wenn** [ankidroid/Anki-Android#5255]
###### Reproduction Steps

1. Add two decks.
2. Select deck options from deck list view
3. Change new cards total for one deck

###### Expected Result
New card total changed without changing other decks new cards total.

###### Actual Result
See other deck new cards total changed as well

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#changing-the-study-options-of-a-deck-changes-the-options-of-my-other-decks
