### ISSUE TITLE
Allow adding complex notes through Note Editor activity

### ISSUE THREAD

**Issue by t0suj4** [ankidroid/Anki-Android#5256]
I was looking for a solution that would allow me to export an entry from a dictionary directly into Anki's Note Editor, using one of the two CREATE_FLASHCARD and SEND actions to only fill up only two fields was not sufficient.

I have created an application in AutoMate that accepts "Share...", reformats the text and launches Note Editor Activity with EXTRA_CALLER set to CALLER_CARDBROWSER_ADD and properly formatted EXTRA_CONTENT and fills the note fields. This way works *almost* perfectly.

The most annoying issue my implementation has to deal with is that the editor is not closed when I confirm the addition. So after adding like 60 notes I noticed that the back button was scrolling through the previously unclosed Activities still there.

There should be an official way to add structured note data to the Note Editor Activity. The structure should ideally specifiy note type and keys matching note fields, displaying error on mismatch.

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
There is an official way:

https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API

**Comment by t0suj4** [comment]
I'm sorry, maybe I was not clear enough... The only way to add structured note data in Note Editor is through abusing internals: sending `fied1 \x1f field2 \x1f field3` and pretending to be a caller from inside of the app.

I **absolutely** need to land in the Note Editor. The only thing I need is to have the Intent API extended.

**Comment by timrae** [comment]
Why can't you use the API?

**Comment by mikehardy** [comment]
Here's a great Kotlin example for instance, and the sample app distributed with the API similarly has a good Java example https://github.com/jkennethcarino/ankieditor/blob/master/app/src/main/java/com/jkcarino/ankieditor/util/AnkiDroidHelper.kt

**Comment by t0suj4** [comment]
Because I'm using [AutoMate](https://llamalab.com/automate/) that allows me to use only Android API.

**Comment by t0suj4** [comment]
Their dictionary is just an associative array.

**Comment by timrae** [comment]
> Because I'm using AutoMate that allows me to use only Android API.

I see. In that case, you'll need to write a simple app that receives your serialized data via intents, then unpacks the data and invokes the AnkiDroid API.

**Comment by bosbyj** [comment]
> I have created an application in AutoMate that accepts "Share...", reformats the text and launches Note Editor Activity with EXTRA_CALLER set to CALLER_CARDBROWSER_ADD and properly formatted EXTRA_CONTENT and fills the note fields. This way works _almost_ perfectly.

Hi t0suj4, I am doing a same approach here. Could you please share how you managed to pass EXTRA_CALLER to the intent? I am using "am start -n" from termux. Turned out that if NoteEditor is called from outside, it will fire "finishWithoutAnimation();"

I tried this
```
am start -n com.ichi2.anki/.NoteEditor --es "EXTRA_CALLER" "CALLER_CARDBROWSER_ADD"
```
but it didn't work. NoteEditor flashes up and shuts down immediately.

Thank you.
