### ISSUE TITLE
Persistent Long Sync times

### ISSUE THREAD

**Issue by Z1839** [ankidroid/Anki-Android#5261]
I've been having trouble getting anki droid to work on my new android device. This is my first android device, so i'm new to the game. I'm having this issue on both the latest alpha release and the latest stable release.

My app seems to be syncing forever. Moreover, once it's finally done (couple of hours), I can press sync again and it will take the same time (hours) to sync.

**Comment by mikehardy** [comment]
Please try the suggestions mentioned in dontkillmyapp.com - if they work it is a vendor + device issue out of our control. If not then yes, we have a possible problem...

**Comment by Z1839** [comment]
I really appreciate your input. I did the steps and it seems to still be doing this. Moreover, some other members have been having similar issues on the Anki subreddit.

**Comment by mikehardy** [comment]
I'm seeing low throughput now as well. Same sync code thiugh. Maybe it's a server issue? Anyone see the same from desktop or ios?

**Comment by Z1839** [comment]
I'm not exactly sure what you mean, but my syncing on my macbook and my iphone are fine.

**Comment by mikehardy** [comment]
@Z1839 thanks - that is what I meant. I was curious if other clients were experiencing it. I had a very long sync yesterday of a 70MB deck to a fresh android device, but subsequent syncs are still very very fast for me. So I'm not sure exactly what's going on here.

**Comment by Z1839** [comment]
It appears to happen when downloading the media

**Comment by mikehardy** [comment]
Strange - I have decks with lots of media, after a normal/expected amount of time downloading any real media changes, subsequent syncs are super fast, as I would expect. Do you have any storage management programs running on your phone that might touch files and make them appear new?

**Comment by Z1839** [comment]
I am not entirely sure my friend. This is my first android device and so I’m still learning the ropes. I do have the ES fileexplorer app, but I’m not sure what else. 

Also, just to provide further context for the issue: now it isn’t syncing “all day” or for several hours as mentioned. It starts quick, and then takes a while (10-20 minutes) at the downloading / checking media part- the final part of the sync.

**Comment by Z1839** [comment]
Hey man,

So I changed my deck to the V1 scheduler, exported the deck without media to my android, downloaded the stable ankidroid release. I appear to still have the same issue: the downloading media phase of the sync takes consistently long.

**Comment by david-allison-1** [comment]
Had a few user reports about this. Specifically with media.

One user is getting roughly 500MB/day (50kB/s) with ~8GB of media, whereas Anki would be able to handle the transfer in minutes. No reports in ACRA from media: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/8d7dd155-a88e-4d08-a856-ede3c4679dfe

I'll take a look, but I'm not at all familiar with the sync code and am likely to miss something big. I'm fairly low on phone storage right now, which will probably hinder testing.

**Comment by mikehardy** [comment]
I just tested a full sync on an emulator of my test collection and I pulled down 18MB in about one minute, from a cold install. Synchronization afterwards was instantaneous (as expected). What we've seen in the past is that the AnkiWeb server sometimes has things going on and if you make a fresh account it's fast in the new account, making me think there is some sort of fragmentation or something going on over there. I can't reproduce though, it's fast for me.

**Comment by david-allison-1** [comment]
I'm getting about 500MB/hour from Anki Desktop. Just building up some profiling data before I suggest improvements.

I'm pretty sure this is caused by #4568 (I've got a hack lined up on my local branch to confirm), but I'd rather get some definitive data before delving into complex code that I'm not familiar with

**Comment by mikehardy** [comment]
you might be in the best position to test ;-). Full sync with media grabs the media in batches for instance, which (if we are not reusing connections) causes a new SSL handshake each time.

Unfortunately the code links I pasted in the old issue weren't permalinks (not sure github even had that 2 years ago?) so the code has moved and we use OkHTTP now vs Apache HTTPClient so the whole landscape shifted a bit, but the fundamental question "are we re-using connections or not?" still stands

**Comment by david-allison-1** [comment]
> you might be in the best position to test ;-).

That's what scares me 🤣

We're not reusing connections AFAIK, but we batch media into zips of 25 items, I don't think it'll be the main cause of our issues.

https://github.com/ankidroid/Anki-Android/blob/06fba842013a64fd29a64a09ca4127060306d738/AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java#L204-L208

We're not threading or logging well in the code either, but I'd guess at around a 1.3x performance gain from it, I'm still looking for the smoking gun. 

Will get around to proper performance tests in about an hour.

**Comment by david-allison-1** [comment]
I'm in the process of getting a `collection.log` from an affected user.

I've tried about 4 fixes and all seem inconclusive on my end (not that I had a problem in the first place). 

I wouldn't be confident in putting these changes into a stable release until we've determined the exact cause (even if it's AnkiWeb).

@mikehardy Would you mind if I proposed "experimental" changes relating to this to put into the alphas?

**Comment by mikehardy** [comment]
Every PR is an experiment, just some have more data than others ;-)
I had a thought w.r.t. testing this stuff - it's "not too hard" (famous last words) to bring up an SSL server in Java, perhaps it would be possible to actually have a test that brought one up, recorded handshakes, but otherwise just did a known-valid replay against the sync code (or some subset of it) to validate connection re-use

**Comment by david-allison-1** [comment]
I'm going to start off with #4921, then move on to #4568. 

There's hopefully some Linux magic to get what I need out of adb for handshake detection. Haven't looked into it yet.

**Comment by david-allison-1** [comment]
Anki Desktop performs the media sync in the background. 

After looking into our implementation, and coming up relatively blank (I'd guesstimate I can get 2x perf with massive effort), I think this is going to be the best way to solve it. Not blocking user input will significantly reduce the impact, speed up the process (as they can do it during reviews, or without thinking overnight). We'll have a good answer for "why isn't my media appearing" and can likely take action to ensure that we download images before they're scheduled in the viewer.

**Comment by mikehardy** [comment]
Android does have good support for persistent notifications related to long term background downloads, as a platform feature. I've never used them but they're pushing devs that way since a year or two I think so I'd assume they're pretty well developed

**Comment by mikehardy** [comment]
Definitely would want some sort of "media sync is in progress" marker somewhere though and persistent efforts to resume...but then we'd have to maybe ask the user if it's okay since they may have moved to an expensive network and at least where I live (Ecuador) if you burn peoples data megabytes without them expecting it they will literally find you and tell you off!

**Comment by vgf89** [comment]
I still have this problem. Faster/parallel or background media downloads would be hihgly appreciated. Only getting like 1MB a minute right now.

**Comment by harshalmittal4** [comment]
I don't have any media stored on any deck yet it shows <xxx> media files downloaded while syncing and keeps syncing forever. If someone faced this before can someone please help.
