### ISSUE TITLE
Changelog is outdated

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [ankidroid/Anki-Android#5264]
[src/main/assets/changelog.html](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/assets/changelog.html) only contains the version history up to 2.6 (last updated 2016).

For comparison, these is more up-to-date changelog at https://docs.ankidroid.org/changelog.html .

To avoid confusion, consider removing the former, or replacing it with a reference to the latter.

**Comment by mikehardy** [comment]
Interesting. It gets updated, but only on the release branches: https://github.com/ankidroid/Anki-Android/blob/hotfix-2.8.5/AnkiDroid/src/main/assets/changelog.html#L457

So really we should be keeping up with it on master as we make significant changes I suppose. I have some of that work started here, when 2.9 is ready we should at least update master and branch I suppose 

https://github.com/ankidroid/ankidroiddocs/pull/39

**Comment by mikehardy** [comment]
I suppose on master if we don't intend to keep up with changelogs and on the branches it's rendered from the docs project, on master we should just put a placeholder with explanation in there, what do you think @timrae

**Comment by timrae** [comment]
Sure, why not

**Comment by mikehardy** [comment]
@Vlad-Shcherbina if you want to make a PR for your suggestion on master, maybe just with a link to the github site or whatever seems fine, seems like it'd work. I think you can edit text files like that directly in the github web interface...
