### ISSUE TITLE
Confusion in statistics as new cards get counted twice

### ISSUE THREAD

**Issue by beccare** [ankidroid/Anki-Android#5265]
###### Reproduction Steps

1. (I did) set the number of new cards for a custom deck group other than the default of 20
2. check statistics for current deck repeatedly during review
3. observe the number of new cards / total learned

###### Expected Result
The total number for the day after learning should add up to
- the new cards (blue) 
- plus the cards to review (green) at the beginning
The statistics for new cards should only increase once for a new card, and not a second time after reviewing it as a current card (red)

###### Actual Result
The total number for the day after learning adds up to
- *twice* the number of new cards (blue) at the beginning
- plus the cards to review (green) at the beginning
The statistics augments the number of new cards when viewing new blue cards as it should, but also when they reappear as red cards in the same session.

The time estimate seems thus to be skewed to give new cards double weight, while underestimating the actual time per card.

Maybe unrelated: The time estimate per card seems to be the same across all decks (which doesn't make sense, since I find Georgian scripture much more difficult to read than Romanian :)

![Screenshot_20190327-070438_AnkiDroid](https://user-images.githubusercontent.com/9350397/55056417-5ab1d180-5066-11e9-85e1-599071d0dc0f.jpg)
![Screenshot_20190327-075717_AnkiDroid](https://user-images.githubusercontent.com/9350397/55056445-6c937480-5066-11e9-87a5-739c37b82b2c.jpg)

###### Debug info
AnkiDroid Version = 2.8.4

Android Version = 8.0.0

ACRA UUID = 55af7169-b84d-402f-8804-380fe066a8b5

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the userv forum

**Comment by Anthropos888** [comment]
The "Learn" count is the sum of new cards and learning cards. 

https://apps.ankiweb.net/docs/manual.html#types-of-cards

If you just want to see the number of new cards, you could check for example "rated:1 prop:reps<=3 prop:ivl<=7" in the card browser according to your deck options.

But I agree, the Ankidroid statistics are lacking essential information from Anki desktop. However, that should be easy to add since all the data is available in the Anki source code already.
