### ISSUE TITLE
Request to add jianguoyun synchronization 

### ISSUE THREAD

**Issue by Molers** [ankidroid/Anki-Android#5267]
jianguoyun support webdav .
Can you add this feature to ankidroid?

**Comment by mikehardy** [comment]
AnkiDroid synchronization is done by comparing database internals at the row level - there is no way this would work reliably with the generic sync services like jianguoyun or dropbox or similar.

Attempting multi-device synchronization using the files themselves will lead to corruption for the same reason - they are database files. https://www.reddit.com/r/Anki/comments/7du2ay/optimal_cloud_backup_for_anki/

There is some discussion on how to use a 3rd party file-synchronizer (dropbox in this case but it should apply to jianguoyun) if you want to use some external script https://www.reddit.com/r/Anki/comments/7du2ay/optimal_cloud_backup_for_anki/

With the availability of a free cloud sync service in ankiweb, or the ability to run your own personal sync server https://github.com/tsudoko/anki-sync-server there are sufficient built-in options
