### ISSUE TITLE
additional control [deck selection with all deecks] in card browser menu 

### ISSUE THREAD

**Issue by ps-goog** [ankidroid/Anki-Android#5268]
###### Reproduction Steps
Extending [card browser] from local menu search only last deck #5144 issue

1. Go to deck X
2. Start to learn
3. Edit card
4. Select any text T, local menu [card browser]
5. Android looks for T in deck X, but I want to look in all deck
6. Back, back, select all deck
7. Search box is empty, I have to input T manually

###### Expected Result
5. Show additional control [deck selection with all deecks] in card browser menu 

###### Actual Result
6. There is no deck selection

![Screenshot_20190327-072123_AnkiDroid](https://user-images.githubusercontent.com/43900825/55054713-0ce69a80-5061-11e9-8cf2-4714a495c720.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.9alpha66
Android Version = 8.0.0
ACRA UUID = dd27ecef-281f-411a-b121-c44b1ca1bdb7

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by Anthropos888** [comment]
Similar to issue https://github.com/ankidroid/Anki-Android/issues/5159

**Comment by Anthropos888** [comment]
Recently the "search all decks" button was added when no results are found. In my opinion it would make sense to *always* show this button, since it make sense that users want to search all decks, even though results were found in the current deck.

**Comment by david-allison-1** [comment]
@Anthropos888 Second person to ask that. A new issue should be created soon.

If it's not done within a few hours, could you do it and post on https://github.com/ankidroid/Anki-Android/issues/5234#issuecomment-638067180 so we don't get a duplicate.

Thanks!

Hope to get this into the 2.11 beta

**Comment by david-allison-1** [comment]
Closed along with #6344 in #6347

**Comment by Anthropos888** [comment]
Thanks @david-allison-1 The "search all decks" button is now shown after every search which is very intuitive
