### ISSUE TITLE
<code> is incorrectly rendered as a block element

### ISSUE THREAD

**Issue by tszynalski** [ankidroid/Anki-Android#5272]
When you add a card that has the &lt;code&gt; element in the HTML source (for example, a programming question), AnkiDroid incorrectly renders it as a block element. It should be an inline element, as per the HTML5 spec.

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Ankidroid is, as far as I know, rendering with a Chrome WebView directly, so it is the Chromium rendering engine.

You provided no version numbers so I can't guess what happened.

I encourage you to install the alphas so you have a version of AnkiDroid that exposes the WebView for debugging: https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases

And use the Chrome DevTools to troubleshoot: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

If you can determine that the HTML rendered is different than the card template HTML, please follow the bug report guidelines you indicated you had followed when you checked the box above https://docs.ankidroid.org/help.html - and provide the info required along with minimal steps to reproduce (ideally a collection with the problem)

**Comment by tszynalski** [comment]
Thank you for your response.
I didn't add a list of steps, because I thought the steps to reproduce would be obvious from the question. Add a &lt;code&gt; element to the source of any field of any card (I used Anki for Windows to edit the source) and view in AnkiDroid. It renders fine on Windows.
My AnkiDroid version is 2.8.4 and my Android version is 7.1.2.

If the problem is with WebView, then perhaps AnkiDroid could apply a stylesheet that fixes it? Or use Chrome rather than WebView (apparently this is possible in Android 7)?

**Comment by mikehardy** [comment]
On Android 7 and higher, WebView *is* Chrome if I remember correctly. Applying a stylesheet in AnkiDroid different then desktop would result in style skew across the ecosystem so it's only a valid thing to do for us if our local display is already non-compliant (which it appears to be for you in this case...)

Thanks for the reproduction steps - nothing is obvious in bug reports, everything must be spelled out to make sure we reproduce the actual problem and can try to fix.

**Comment by snoyes** [comment]
`This <code>code</code> is shown <code>inline</code>.` renders for me as:
![inline_code](https://user-images.githubusercontent.com/4838517/67606280-696c7e00-f746-11e9-96eb-d94e5ce070eb.jpg)

which seems to be inline. Am I missing the point?

**Comment by tszynalski** [comment]
@snoyes Your post just made me realize the block styling was due to my own stylesheet. I totally forgot about it. There is no bug. I apologize for the misinformation.
