### ISSUE TITLE
Support for "Low-Key Anki"

### ISSUE THREAD

**Issue by malnvenshorn** [ankidroid/Anki-Android#5276]
I'm planning to add an option for the "Low-Key Anki" approach to this app and I want to ask if you would accept a pull request with this feature beforehand.

Basically it does two things:
- Reduces the button choice to only "again" and "good"
- Removes the penalty to the ease factor when hitting "again"

If you are interested there is an in-depth [article](https://massimmersionapproach.com/table-of-contents/anki/low-key-anki/intro/) which explains the ideas behind this approach.

**Comment by mikehardy** [comment]
In general, if it is not in upstream Anki, we do not do it. We have a struggle with available developer resources keeping up with both Anki upstream and Android API motion and have no effort to spare unfortunately

This is not in upstream Anki as far as I know, so take it up with them then circle back.

**Comment by malnvenshorn** [comment]
No it's not supported by the desktop version of Anki and I doubt this gets implemented, because "Low-Key Anki" is quite different in contrast how Anki works. Because the Android app doesn't support plugins I will maintain my own fork with this feature.

**Comment by mikehardy** [comment]
Wish we could help but without more horsepower actually developing the mainline source upstream and here a fork is likely best. Good luck!
