### ISSUE TITLE
Making recording function much easier to.use

### ISSUE THREAD

**Issue by lyannn** [ankidroid/Anki-Android#5283]
There is a recording function on ios, it can easily help us improve our listening and speaking ability . it looks like this.

1.Open anki - upper right corner gear - Review - Quickbar - Feel free to choose a Button - Record Voice 
2. enter the deck. 
3.According to the characteristics of the card, after you enters the card, you can listen and then flip through the text. 

4.Then select Record at the top and pop up the option. 

5.Record Voice is the recording, Replay Voice is the playback. After reading it, listen to it again, then listen to the card again. Listening and speaking progress is fast.

###### Actual Result
Ankidroid also have a recording voice function,but it isn't as convenient as this function on ios, you have to edit note, then tap a button, then you can record your voice

**Comment by david-allison-1** [comment]
Fixed in #5774
