### ISSUE TITLE
Inconsistent audio ducking for TTS and field audio

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5284]
###### Reproduction Steps

1. Review a card with TTS on the front and audio from an audio field on the back
2. Have your music app some music playing in the background
3. Listen to the difference between audio output on the front and back card

###### Expected Result

TTS and audio from an audio field ([sound:...]) is played in the same way. Both will not lower the music volume in the background (OR if audio ducking is turned on, BOTH will lower the music volume in the background)

###### Actual Result

TTS doesn't lower the volume of the background music. But the audio from the audio field does lower the volume.

Please add an option to enable or disable audio ducking so that both TTS and normal audio show the same behavior.

As for me, I'd prefer to generally disable audio ducking since I can control the desired volume of my background music in my music app. But other users might prefer a generally enabled audio ducking, so an option for that would be the best solution.

###### Debug info
AnkiDroid Version = 2.9alpha67

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
just for reference this is in the AudioManager flags sent in to the audio subsystem in libanki/Sound.java

And I personally don't like ducking either so I'd vote to take it out, or at least put a toggle in reviewing preferences to let people turn it off. Inconsistent sound volume drives me nuts too

**Comment by Anthropos888** [comment]
I'd vote to keep this issue open if there's a way to enable/disable audio ducking.

**Comment by mikehardy** [comment]
There is, but it's not a vote to keep it open anymore, it went fully stale.
If no one cares enough to actually implement it it's going to stale out and close
