### ISSUE TITLE
Unable to install the AnkiDroid app since updating to Android 9

### ISSUE THREAD

**Issue by Zinedine-Socrates** [ankidroid/Anki-Android#5288]
I recently updated my Samsung S8 to Android 9 and have been unable to download and install AnkiDroid on my phone since then. AnkiDroid had already been installed on my phone but the app was deleted when I updated the phone's software. Any ideas why this might be? (I have gone through the troubleshooting steps suggested by the app store)

**Comment by adamwolf** [comment]
Is this still an issue?

**Comment by mikehardy** [comment]
It can't be, I'm on 9 and have been forever, I've tested it a bit on Q/10 as well
