### ISSUE TITLE
Forecast doesn't account for suspended cards

### ISSUE THREAD

**Issue by L61** [ankidroid/Anki-Android#5289]
What it says at the top. The forecaster does not account for cards being suspended and sets them as due today (if they are old). As a result, the prediction for the rest of the days of the week can be wildly inaccurate.

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by guyemerson** [comment]
I have also noticed this bug.  This only happens when Advanced Statistics are enabled.

**Comment by draeklae** [comment]
I can confirm this is still an issue in the latest (stable) version (2.9.4)
