### ISSUE TITLE
[critical] sudden systematic and reproducible corruption on multiple devices, making the app unusable

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ankidroid/Anki-Android#5291]
(I didn't know the procedure to ask for help so here's a copy of the public mail)
Hi,

I am two weeks from my exams and have been sweating a lot trying to figure out what's going on. 

I'm using anki on my laptop (linux, version below) but like to do a few cards here and there on my phone, a galaxy S5  (version below). I also have an android tablet (version below) for this purpose.

Everything was going fine until today. I synced my db from my laptop to ankiweb, then opened ankidroid, synced and did a few cards. However, when syncing back to ankiweb from my phone (before going back to my laptop) I got the "corrupt database" message.

I now get this mesage everytime I do a card, and even sometimes without doing any reviews, making the app absolutely unusable.

Here's what I tried :

- checking the database
- removing the ankidroid folder and redownloading the folder from ankiweb (starts fine, does one card or wait a minute and then syncing tells me that the database is corrupted when trying to sync)
- doing the procedure indicated in the anki manual using sqlite3
- exporting then deleting the last deck I added, in case it was only a few buggy cards
- moving the ankidroid folder from my internal memory to the sd card
- trying all of the above on my tablet, got the exact same results
- uninstalling AnkiDroid, checking all permissions, rebooting phone
- combination of all of the above
- checking reddit, github etc
- probably a few other things

I noticed something strange though this morning before those issues. I manually added about 200 cards on a new deck (so 0 cards to review), then set "new cards" limite to 50 and started learning a few. I noticed that the number at the bottom (new in blue, learning in red and review in green) indicated strange figures like 31 + 37 + 0   It seems impossible to have (in this example) 68 cards when I just started a deck with only 50 new set for the day. I don't know if any of this is related but I prefered to write it.

Any help is really appreciated as I'm quite desperate <3

=====================

linux version : 
Version 2.1.9 (ae67c976)
Qt 5.12.1 PyQt 5.11.3

ankidroid phone log :
AnkiDroid Version = 2.8.4
Android Version = 7.1.2
ACRA UUID = a4438c19-39b5-40b5-9d5d-18a5438d93f7

ankidroid on my tablet :
AnkiDroid Version = 2.8.4
Android Version = 7.1.2
ACRA UUID = f17ec804-2da2-4c50-9465-ea1b3a53bcf4

###### Research
[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[X] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
Did you try restoring from the last backup before corruption occurred?

**Comment by thiswillbeyourgithub** [comment]
Thanks for the quick reply. 

Well it actually happened after I added a few hundred cards that I can't afford to lose so I did not. Try that. Is there an alternative to losing my cards? Like using exporting and importing?
Thanks

**Comment by timrae** [comment]
If the methods that you tried didn't work, you'll probably need some SQL
skills to recover the cards. We can't provide support with that I'm sorry.

**Comment by thiswillbeyourgithub** [comment]
Hi, thanks for the answer.

Do you think it would be helpful to export my collection, delete it, sync the now empty account, reimport the decks, resync?

Also, is there a way to see logs from AnkiDroid to understand what's causing the error? If anki on my laptom has no issue dealing with my decks I think I could help

**Comment by thiswillbeyourgithub** [comment]
I exported my whole database, created a new ankiweb account, imported the db in the new account, synced it on my phone and everything seems to be working fine. I intend to update this thread in case something new emerges, but I will probably use this new account from now on
