### ISSUE TITLE
Restore from backup

### ISSUE THREAD

**Issue by dotancohen** [ankidroid/Anki-Android#5294]
Ankidroid should have an option to restore from its own internal backups.

###### Reproduction Steps

1. Set minimum backups to some positive integer.
2. Accidentally overwrite your local collection.
3. Try to restore from the backups that you know you have.

###### Expected Result

I expect to find a button "Restore from backup" which demands confirmation then allows the user to select from one of the stored backups. The state of the collection should then return to the state of the collection which is found in the backup file.

###### Actual Result

The "Restore from backup" button is not found.

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
You asserted in the issue template that you read the manual

This exists, I verified it just now. "Restore from backup" option in deck picker list, sweet list of available backups.

https://docs.ankidroid.org/manual.html#backups

**Comment by dotancohen** [comment]
@mikehardy 
You got me! To be fair, I've read the manual quite (more than once) some time ago and thought "I'm not an idiot, I wouldn't miss that option".

Perhaps this is a sign that the UI could be improved, though? There are currently three "menus" to be had from the Decks screen (Hamburger, Stoplight, Plus sign).

In any case, thank you for showing me the way. Have a great week!

**Comment by mikehardy** [comment]
I have both never met a UI that could not be improved nor met a UI improvement project in open source that "finished" 😆 , but of course - #5126

**Comment by dotancohen** [comment]
@mikehardy You should give VIM a try!
Thank you, I will peruse the Material Design issue and if I have any wisdom to add, I'll do so.

**Comment by mikehardy** [comment]
apostasy, ed is the standard text editor
