### ISSUE TITLE
[Feature Request]  Disable alarm when reviewing cards (so as not to fall asleep)

### ISSUE THREAD

**Issue by german-jablo** [ankidroid/Anki-Android#5296]
There are many applications in which trivial actions must be performed to disable an alarm and thus not fall asleep. It would be great to apply that idea to a useful and productive activity such as reviewing flashcards. It could be done by linking a third party alarm application with anki, but I think the best solution would be to incorporate an alarm in anki.

I found this proposal in some forums and blogs with very good reactions in the comments, such as: [The Anki Snooze Button](https://japaneselevelup.com/anki-snooze-button/)

There is also an application that allows flashcards to disable the alarm, but only with a fixed deck of countries and capitals and without repetition spaced: [I Can't Wake Up!](https://play.google.com/store/apps/details?id=com.kog.alarmclock&hl=es_AR)

I hope you like the idea and implement it :) I think Anki would be much more downloaded and used in this way.

Thank you.

**Comment by mikehardy** [comment]
As answered on the forums:


This is non-core functionality that Anki Desktop does not support, which is generally our standard for features in AnkiDroid


You are welcome to use the API if possible to implement similar functionality, but a feature like this will not be incorporated into the main app
