### ISSUE TITLE
Sudden database corruption.

### ISSUE THREAD

**Issue by vi** [ankidroid/Anki-Android#5299]
```
E/ACRA    ( 7780): ACRA caught a SQLiteBlobTooBigException for com.ichi2.anki
E/ACRA    ( 7780): android.database.sqlite.SQLiteBlobTooBigException: string or blob too big (code 18)
```

Suddently message about corrupted database popped up and it refused to do anything relevant. Checking database also hit the same corruption.

Backups were too old or already contained bugged database.

`sqlite3 collection.anki2 "VACUUM; REINDEX;"` also failed with `Error: string or blob too big`.

Recovery using dumping the database to sql text, replacing `ROLLBACK;` at the end with `COMMIT;`, then importing it back worked and now AnkiDroid seemingly works without issues.

###### Debug info

AnkiDroid Version = 2.8.4

Android Version = 4.4.2

ACRA UUID = 84bc9788-a425-425c-8976-700bbb4bb58b

**Comment by mikehardy** [comment]
I'm going to close this unless it is reproducible on the latest alphas https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases

We have upgraded the underlying SQL library so bug reports against 2.8.4 are unfortunately not relevant

Very resourceful to do the database work yourself though, that is impressive and I'm happy you were able to get working again
