### ISSUE TITLE
Input box is not cleared if a note is deleted

### ISSUE THREAD

**Issue by Minoru** [ankidroid/Anki-Android#5300]
###### Reproduction Steps

1. Start studying a deck where all cards have input boxes ({{type:}}).
2. Type something into a box, but submit it—don't press Enter and don't press "Show answer".
3. Go to the top right menu and delete the card.

###### Expected Result

The next card appears, its input box is empty.

###### Actual Result

The next card appears, its input box contains what I typed on step 2.

###### Debug info

AnkiDroid Version = 2.8.4

Android Version = 9

ACRA UUID = 6e9d3f8d-22ab-462a-826c-bdd4cc82224b

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Is this still occurring? Couldn't reproduce it. @Minoru

**Comment by Minoru** [comment]
I can't reproduce it with 2.9.5 either (on the same Android version with the same ACRA UUID). Closing.
