### ISSUE TITLE
Unable to custom study on suspended cards

### ISSUE THREAD

**Issue by arbitrary-dev** [ankidroid/Anki-Android#5303]
###### Reproduction Steps

1. Suspend some cards in a deck
2. Create a custom study deck using `Limit to particular tags` with `leech`
3. Observe the resulting `deck:"original-deck" (tag:'leech')` deck

###### Expected Result

Deck is not empty and contains suspended cards.

###### Actual Result

Deck is empty `0 0 0`.

On the contrary, when using tags other than `leech` everything works as expected.

###### Debug info

AnkiDroid Version = 2.8.4

Android Version = 6.0.1

ACRA UUID = 39aeaf3d-c728-4cb1-8a3c-901dcf35c4e6

###### Research

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
This is by design.
