### ISSUE TITLE
SVGs are not viewable in the preview window

### ISSUE THREAD

**Issue by ohare93** [ankidroid/Anki-Android#5306]
###### Reproduction Steps

1. Edit a card which has an svg as in image in one of the fields (e.g. `<img src="flag.svg" />`)
2. Click the attachment button to the right of the field
3. You will now be in the "Editing Field" screen since there is an image in the field

###### Expected Result
A preview of the svg image is shown, just like there is if you open a png this way.

###### Actual Result
A white square is shown instead.

###### Debug info
AnkiDroid Version = 2.8.4

Android Version = 9

ACRA UUID = 01229334-5848-488f-afe4-5826790c1bed

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

These are not svgs from the Image Occlusion plugin.

**Comment by mikehardy** [comment]
Interesting - Are they viewable during review? Does it work in AnkiDesktop?

**Comment by ohare93** [comment]
Yes, and yes.

**Comment by mikehardy** [comment]
:thinking:  - thanks

**Comment by Anthropos888** [comment]
Happens in the latest alpha as well. No preview for svgs (blank white screen) in the "editing field" window. JPG and others work fine.

**Comment by mikehardy** [comment]
I recognize this is asking for something that is probably really easy but it would save time triaging if someone could attach an exported deck with an example card that shows the problem. Can just be one note, and to attach ".apkg" files here you just have to rename them with extension ".zip" (which is coincidentally all an .apkg is...)

**Comment by Anthropos888** [comment]
[svgTest.zip](https://github.com/ankidroid/Anki-Android/files/3180398/svgTest.zip)

1) I realize that might be just a result of Android photo apps (I'm using F-stop amd Google photos) not being able to load svgs.

2) I wonder why AnkiDroid export the test deck with one card and a 20kb svg in a huge size of 9MB??

**Comment by timrae** [comment]
Probably it has bundled a font or some other kind of static media

**Comment by ohare93** [comment]
[BrokenSVGDeckExport.zip](https://github.com/ankidroid/Anki-Android/files/3182131/BrokenSVGDeckExport.zip)

Here's mine. If it turns out the SVGs are just broken but because of some other program, then that's fine.

**Comment by valentin-nemcev** [comment]
> Interesting - Are they viewable during review? Does it work in AnkiDesktop?

I have the same problem, except its white screen during review too. AnkiDesktop and AnkiWeb works as expected

AnkiDroid Version = 2.8.4

Android Version = 9

This is an example of SVG
```
<svg height="743" width="1078" xmlns="http://www.w3.org/2000/svg">
 <!-- Created with Image Occlusion Enhanced -->
 <g>
  <title>Masks</title>
  <rect class="qshape" fill="#FF7E7E" height="86.79245" id="79f6399673b94d1988fedd58f891d425-oa-11" stroke="#2D2D2D" stroke-dasharray="null" stroke-linecap="null" stroke-linejoin="null" width="188.67924" x="108.79239" y="387.18865"/>
  
 </g>
</svg>
```

**Comment by timrae** [comment]
How about ankiweb using chrome on the same Android device that you have
AnkiDroid?

**Comment by mikehardy** [comment]
#5332 possibly related
