### ISSUE TITLE
Deleted tags still showing up under "Card Browser > Filter by tag > Select tags"

### ISSUE THREAD

**Issue by xmatic** [ankidroid/Anki-Android#5310]
###### Reproduction Steps

1. I manage my tags only on Desktop Anki. I deleted a tag there. Synced from Desktop Anki to Ankiweb.net, then opened up AndkiDroid and synced with Ankiweb.net. 

2. On **AnkiDroid**:
-- the tag disappeared (**as expected**) from "Decks > 'Long Press on {Deck Name}' > Custom Study > Limit to Particular Tags > Select tags". 
-- **However** the tag persists at "Card Browser > Filter by tag > Select tags".

###### Expected Result
Deleted tag should be gone from **from both**: 
"Decks > 'Long Press on {Deck Name}' > Custom Study > Limit to Particular Tags > Select tags" 
**AND** 
"Card Browser > Filter by tag > Select tags".

###### Actual Result
Deleted tag is **gone from** : 
"Decks > 'Long Press on {Deck Name}' > Custom Study > Limit to Particular Tags > Select tags" 
**BUT** not from:
"Card Browser > Filter by tag > Select tags".

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Check under "check database" - it has the side effect you are looking for - https://docs.ankidroid.org/manual.html#_advanced_actions

Not that intuitive, no, but it does work! Or it should at least, if not I'll happily reopen

**Comment by xmatic** [comment]
Works! Thanks!
