### ISSUE TITLE
Trying to build AnkiDroid on Android Studio

### ISSUE THREAD

**Issue by MaddoGokan** [ankidroid/Anki-Android#5311]
###### Reproduction Steps

1.  download the last stable release ver. source code (https://github.com/ankidroid/Anki-Android/releases/tag/v2.8.4) to open it and build it with android studio
2. 
3. 

###### Expected Result

AnkiDroid working in order to work on it

###### Actual Result
error during sync :  

> ERROR: Could not find method leftShift() for arguments [build_9wnj1gzeqpnqe4pgtuivqinr4$_run_closure8@33efe397] on task ':api:generateRelease' of type org.gradle.api.DefaultTask.

this is the code of generateRelease: 
`task generateRelease << {
    println "Release ${version} can be found at ${localReleaseDest}/"
    println "Release ${version} zipped can be found ${buildDir}/release-${version}.zip"
}`

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there, and welcome! We work on master, which is working towards a 2.9 release and is plenty stable as a target even as a base for a personal fork to modify it for personal use

There will be no further releases on the 2.8 branch, so I won't spend time working on it, sorry

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide
