### ISSUE TITLE
Card suspended when selecting red button "again"

### ISSUE THREAD

**Issue by joanbru** [ankidroid/Anki-Android#5312]
Hello, here is the issue.

1. Studying a set
2. Selecting red button "again" for one card (to play it again in the session)
3. Sometimes, not for all same cases, message : the card is suspended (indeed it is highlighted in yellow in the table of cards). So I need to remove the suspension manually for each.

This issue accures with a Huawei P9 Lite, not with a Samsung S7.

Thank you

**Comment by mikehardy** [comment]
https://apps.ankiweb.net/docs/manual.html#leeches
