### ISSUE TITLE
Wrong intervals on "good" and "easy" answer buttons for "study ahead" custom decks

### ISSUE THREAD

**Issue by rathsky** [ankidroid/Anki-Android#5313]
Custom decks created via the "study ahead" option show for me with unsorted / incoherent times for the next review on the answer buttons:

![card](https://user-images.githubusercontent.com/887320/58385284-2d45bd80-7fee-11e9-8f65-c066320eb496.png)

This occurring with like 95% of all cards in such custom decks, but never (so far) in ordinarily scheduled reviews.

This with the v2 scheduler on AnkiDroid 2.9a68. Times for the same cards differ on Anki desktop (2.1.13): only the "hard" answer seems the same, the intervals on "good" and "easy" are considerably longer.

**Comment by david-allison-1** [comment]
Fixed in #6086
