### ISSUE TITLE
Slow rampup of new cards in deck

### ISSUE THREAD

**Issue by EmmanuelMess** [ankidroid/Anki-Android#5320]
###### Description

Provide the option for dynamic 'new cards' number, or the option to choose a function to provide a slow ramp up to 20 cards per day.

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! This is an interesting idea, but as a general rule if it is not in upstream, we don't implement it. We have a hard enough time keeping up with upstream features that adding extras here is not possible. Sorry - but do feel free to propose it with Anki support - if they implement it in the main code line, we will eventually follow
