### ISSUE TITLE
Show number of due reviews even when more than 1000 are due

### ISSUE THREAD

**Issue by Ekleog** [ankidroid/Anki-Android#5322]
_This is in a way a duplicate of https://github.com/ankidroid/Anki-Android/issues/2226, which was supposed to have been fixed._

#### Problem

The number of due cards, shown on both the deck list screen and the review screen, is bounded by 1000.

This is depressing when having more than 1000 cards to review, as the 1000 number at the top of the screen will go down, until at some point using the “back” button causes a full recompute and brings it back to 1000.

#### Impact

While it is a minor annoyance when doing regular reviews (it's always possible to bound the number of daily reviews to 1000 and do custom studies to get over the 1000 without depressing), with filtered decks it's a much bigger problem, as it is not possible to just limit the number of due reviews per day to 1000 without also moving all the cards back to their original deck.

Which means catching up on a large backlog is harder than it needs to be, with no visual progress indicator to help motivation.

#### (Bad) workaround

For filtered decks, accessing the deck details page (by clicking the number of due cards on the deck list page) shows the total number of cards in the deck, which in turn is a pretty good indicator of the number of due reviews in said deck.

However, accessing it requires a relatively long excursion out of the review page, which means it doesn't really help for seeing a number always going down in a corner of the screen, which would be a nice boost to motivation (“still XXX cards to get down one more thousand reviews!”)

#### Context

I currently have ~41k cards in my backlog, following about a year of slowly falling behind on reviews. I have noticed that splitting cards in different kinds of filtered decks (that all use the relative overdueness order to decrease time spent on easy-to-remember cards) makes me much faster at reviewing them, not only because it allows me to sort the cards by the kind of thing they ask (related: https://github.com/ankidroid/Anki-Android/issues/4805, [not implemented upstream for architecture reasons](https://anki.tenderapp.com/discussions/ankidesktop/27927-enhancement-allow-sorting-reviews-by-card)), but also because when I notice my due review count falls below 1000 I start seeing actual progress, and it motivates me to get it down to 0, though I know there are still tens of thousands of other cards to go.

In this context, I'm thinking that having a way to show the ~3k due reviews per deck I'm currently left with would help me get motivation to get them down thousand by thousand, in a way much easier than making blind progress, getting demotivated, going to see the deck details page, and seeing that I've only done 20 cards since the last time I checked. It'd allow me to set myself goals and actually hold myself to them.

Anyway, here it is for the bug report / feature request depending on how one sees it.

Thank you for ankidroid! it's already great, just hope it could be even just a bit better :)

**Comment by mikehardy** [comment]
I actually side with you on at least publishing precise counts. We've discussed it before, as an intentional break with our normal "conform to Desktop behavior" stance:

https://github.com/ankidroid/Anki-Android/issues/2226
https://github.com/ankidroid/Anki-Android/issues/5092
https://github.com/ankidroid/Anki-Android/issues/5197

And this is an area we might go the for precision over conformity

If someone made a PR that put in the actual numbers, I'd probably be +1 personally and if all maintainers agreed it might be good for merge

**Comment by Ekleog** [comment]
@mikehardy Just sent an attempt at such a PR in https://github.com/ankidroid/Anki-Android/pull/5326, though I have never worked on an android app and not done java for years :)
