### ISSUE TITLE
mathjax formula  nested in cloze aren't rendered

### ISSUE THREAD

**Issue by L-M-Sherlock** [ankidroid/Anki-Android#5323]
###### Reproduction Steps

1. edit cloze card
2. input \(1 \div 2 =\){{c1::\(\frac{1}{2}\)}}
3. save card

###### Expected Result

when showing the answer, all formula will be rendered. And the formula in cloze is blue.

###### Actual Result

Only the formula in the outside of cloze are rendered. The formula in cloze show the source code in blue.

###### Debug info

AnkiDroid Version = 2.9alpha70

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by adamwolf** [comment]
Thanks for the bug report!

I'll take this!

**Comment by adamwolf** [comment]
Confirmed.

**Comment by L-M-Sherlock** [comment]
> Confirmed assuming you mean \(1 \div 2 =\){{c1::\(\frac{1}{2}\)}}

Yes, thank you!

**Comment by mikehardy** [comment]
@timrae I think this is closed with the merged change above, if you could kick out an alpha to so it could see testing? pleeeease :-)

**Comment by timrae** [comment]
We're starting to run out of alphas, we can only go up to 99 😅

**Comment by mikehardy** [comment]
Nothing like a deadline to get the release done ;-). We're close though - I still feel. Definitely before 99!

**Comment by adamwolf** [comment]
Not to be too off topic, but are there issues or things that need to be
addressed before the next release?  I can't throw a huge amount of time at
this but I can take a look at a few things...

**Comment by mikehardy** [comment]
I need to finish #5151 - a CardTemplateEditor internals change, and make sure notifications is ready to go #4944 (but likely scaled down pretty minimal vs the original vision there). It isn't that much really, but the CardTemplateEditor internals are just very complicated and I haven't addressed all review yet. I think that's about it really - the 2.9 codebase is otherwise in pretty good shape, with pretty good testing guardrails around it to keep it that way

**Comment by adamwolf** [comment]
Is there a better place for us to discuss meta things like this?  Is there
anything else left from Anki 2.1 now that MathJax is in?

**Comment by mikehardy** [comment]
Oh yeah - #4961 is our coordination issue. There's not anything else that is a must-have I don't think, just nice to haves, only speaking for myself

And for what it's worth the notification thing, or a basic implementation of it might be relatively easy. I have some WIP on a branch off my fork but it's nothing special. I think for most people they would just like to have notifications of any cards due without needing to install the widget, and we're already past that. So collaborating on something there to get it done could work, and I finish CardTemplateEditor and we're done?
