### ISSUE TITLE
[Feature Request] Success/Fail sound (like Anki fanfare addon)

### ISSUE THREAD

**Issue by bkahlau** [ankidroid/Anki-Android#5325]
# @I was never more engaged or looking forward to my anki reviews since installing the anki fanfare add-on - it briefly shows a check mark or red "X" and plays either a encouriging "pling" or a error sound after clicking the "Hard/Good/Easy" or "Again" button.
I think it makes the review sessions more engaging, this feature could be turned on/off in the settings, maybe there could be a small selection of pictures/sounds to choose from and a file browser to add custom sounds/pictures.

https://ankiweb.net/shared/info/2073603704
The add on plays the sound every time since it's considered feedback - rewards would be ideally given out at a variable quota, but I think it makes sense to make the feedback fixed

**Comment by mikehardy** [comment]
@lucwastiaux would you be interested in this for AnkiReview? Seems like a very interesting feature, and your app is where review-related things can easily break desktop conformity

**Comment by lucwastiaux** [comment]
@bkahkau AnkiReview has that exact same feature right now, do you want to give it a try?
https://play.google.com/store/apps/details?id=com.luc.ankireview

**Comment by bkahlau** [comment]
That sounds really great! Thank you! :)
But the app doesn't seem to show cloze deletions properly (it shows "{{c1::clozetext}}"
Why are the answer buttons all collected in the check mark button? Am I missing gestures, that make answering easier/more modern?
How do I get the app to play a specific sound, depending on whether I got the answer right or wrong?

**Comment by lucwastiaux** [comment]
Are you using the AnkiReview style or Anki HTML/CSS deck display mode ? you can change those using the menu while reviewing, choose "Deck Display Mode". Gestures are: swipe up to reveal answer, swipe left for bad, swipe right for good. For more specific answers, you need the floating button. Sound and icons are hardcoded for now, I was waiting to get more interest before making those customizable.

**Comment by bkahlau** [comment]
I've used both display modes, but neither of them seemed to give the intended results
I'll check the app again on the next update and once I have a new deck to learn
