### ISSUE TITLE
ankidroid type answer into the card with Bluetooth keyboard Skip back cards

### ISSUE THREAD

**Issue by superpawko** [ankidroid/Anki-Android#5333]
###### Reproduction Steps

1. Connect to Bluetooth keyboard
2. In AnkiDroid settings > Advanced > ankidroid type answer into the card (ON)
3. After typing in the answer field and pressing Enter it skips to next card without showing result

###### Expected Result

Show back side of card.

###### Actual Result

Next card view.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

I have tried many versions of Anki.

AnkiDroid Version = 2.9alpha71

Android Version = 8.1.0

ACRA UUID = 42aef225-f6f8-402e-818b-e3be9b67a5fa

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by sudomain** [comment]
While proper native keyboard shortcuts would be a great feature in the future, it is currently possible to create custom keyboard shortcuts for many apps using an app called Automate. In that app, a flow is made up of blocks that can detect events and perform actions.There are two block types in particular that should be able to do what you want:
1) The key pressed block which detects key presses or releases
2) The interact block which interacts with an on-screen UI element (including buttons like 'show  answer', sync, preview, etc)).

I've personally used these blocks together to make shortcuts to preview a template using ctrl + P and go back from the preview to the template editor using ctrl +B.

**Comment by david-allison** [comment]
@sudomain Still a problem?

**Comment by sudomain** [comment]
I can't reproduce it
