### ISSUE TITLE
app does not display "$" after typing in (cosmetic issue)

### ISSUE THREAD

**Issue by zenogantner** [ankidroid/Anki-Android#5334]
###### Reproduction Steps

1. Review a card that expects a typed-in answer, e.g. "!$" like in the attached screenshot.
2. Enter the correct response.

###### Expected Result

Positive feedback, display full response -- as in the desktop program.

###### Actual Result

Positive feedback, displays full response w/o the "$".

###### Debug info

AnkiDroid Version = 2.8.4
Android Version = 9
ACRA UUID = 1beab31f-eae9-4bb9-95fe-645ccfe7f5fd

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

![ankidroid-bug](https://user-images.githubusercontent.com/83638/59850609-f489d180-936a-11e9-928c-0e6f7c2f93b1.jpeg)

**Comment by mikehardy** [comment]
Interesting! Thanks for reporting this. We must be treating that as a special character or something

**Comment by adamwolf** [comment]
This should be fixed in https://github.com/ankidroid/Anki-Android/releases/tag/v2.9alpha80 and newer.  Could someone confirm?

**Comment by zenogantner** [comment]
Thank you for the fix, @adamwolf.

I cannot install this .apk (despite giving the necessary rights), after installing it tells me "not installed" ...
Should I report this somewhere?

**Comment by mikehardy** [comment]
@zenogantner install problems on android are out of scope for ankidroid, but if you use the Google Play Store mechanisms to sign up for the alpha program you can have alpha80 delivered via normal mechanisms and it should work https://github.com/ankidroid/Anki-Android/wiki/Installation#beta--alpha-releases

**Comment by zenogantner** [comment]
OK, so far was just in the beta program, I now signed up for alpha as well.

**Comment by mikehardy** [comment]
I'm going to mark this as closed - but! - that's making the assumption it really was fixed. If you still see the problem after making sure you have the 2.9beta's do reopen it

Cheers
