### ISSUE TITLE
Multi-Select in Card Browser

### ISSUE THREAD

**Issue by OTRawrior** [ankidroid/Anki-Android#5335]
I know this is already a feature, but I'm either an idiot (very possible) or it doesn't work on my new phone. This previously worked fine on my LG G5, but is not working on my Oneplus 7 Pro. Could be there's a setting I can't find that fixes it. Tried on both the normal play store release and the play store beta.

###### Reproduction Steps

1. Go to Card Browser
2. Hold click on any note

###### Expected Result

Multi-select enabled, can then select multiple notes and make bulk changes such as unsuspend etc.

###### Actual Result

Menu is opened. Displays card 'Rank' field (or nothing if no rank in the note) and options to 'Mark Note', 'Suspend Card', 'Delete Note' or 'Preview',

###### Debug info
AnkiDroid Version = 2.8.5beta1

Android Version = 9

ACRA UUID = 66534b95-1a6e-4c10-ae5d-8f2cba888411

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
You need to install the 2.9 alpha, or wait a few weeks for the beta to come out
