### ISSUE TITLE
Reviewer: Bury / Suspend submenu arrow not showing

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#5345]
Most likely this is a bug in the support library :-/

###### Reproduction Steps

1. Review a card in the reviewer which has siblings

###### Expected Result
Arrow shows, indicating that has a submenu

###### Actual Result
Arrow does not show, until you actually click once on the submenu, and then cancel. At which point, next time you open the menu the arrow is shown correctly

**Comment by mikehardy** [comment]
for grins if you are already there you can try a local git revert of the hash where I moved androidx.appcompat just yesterday - if you’re already there, and with the code so close to the pre-revert state it may serve as a very fast check on the assertion

**Comment by timrae** [comment]
That doesn't fix the issue. Probably the bug has been around for quite a while. The best way to get a solution would most likely be to submit a bug report with a simplified example project to AOSP bug tracker. A video might also be fine though.
