### ISSUE TITLE
Opening preference window can force-set some preferences

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#5346]
Most likely there are other preferences where this same issue occurs

###### Reproduction Steps

1. Open reviewer, note that reschedule icon is not shown in toolbar
2. Open preferences -> Reviewing -> App bar buttons
3. Close preferences window without changing anything
4. Go back to the reviewer and observe toolbar buttons 

###### Expected Result
The reschedule button is still not shown, as we didn't intentionally change the preference

###### Actual Result
The reschedule button is shown

**Comment by mikehardy** [comment]
This was noted also in #5328 - fix analytics opt-in - it was a divergence between default behavior / never-selected-anything behavior and the default that populates the prefs

Fixed that one as it was an easily merged PR (also high priority - I did implement analytics but privacy is really important obviously), didn’t think to check others. Might be similarly easily fixed though
