### ISSUE TITLE
images from image occlusion with apostrophe in filename do not display on AnkiDroid

### ISSUE THREAD

**Issue by zoliaaz** [ankidroid/Anki-Android#5347]
Hello, I recently had a problem with some cards created with image occlusion they were appear blank in ankidroid. 
So i did some search on internet but i didn't find anything, then i posted on occlusion github, https://github.com/glutanimate/image-occlusion-enhanced/issues/102 . 

Today i found the problem, all the cards that appeared blank had an apostrophe in their title.

I don't know if you can fix it, but maybe it can help someone that got the same problem.
 
###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Very interesting. I wonder if that is a general problem with any image that has an apostrophe in the title. Did image occlusion create the filename dynamically, such that you had no control over it, or was that a name you chose? Do you have a small collection you could maybe export and attach here (just rename .apkg to .zip so github will let you attach)?

**Comment by zoliaaz** [comment]
First, i chose the image title, so the problem is not from image occlusion.

Secondly, I think it's a general problem with any image with an apostrophe in their title because i did replace the image of cards that worked with an image with apostrophe in its title, then those cards didn't work anymore.

In the post i made on occlusion github, i had posted an [card that didn't work](https://github.com/glutanimate/image-occlusion-enhanced/files/3134367/Exemple.of.card.that.dont.work.on.ankidroid.image.occlusion.zip). Or you prefer more card, but i don't think it will help.

**Comment by mikehardy** [comment]
Excellent - this is great information. I'm going to change the title since I would bet this is a general problem, but either way there's enough information to find it I think. Thanks a bunch @zoliaaz

**Comment by mikehardy** [comment]
for anyone that tackles this (if someone wants to try) - first step is to try putting any image in the media collection and referencing it from a card. It should fail, while the same media with no apostrophes should work. Then I would trace through the code to see if there is anything we can do about it - making sure the Android platform supports those filenames in general etc.

**Comment by zoliaaz** [comment]
Well i just tried an image with an apostrophe in title in a normal note, and it work (image appear). So it seem it's only with card created with image occlusion. I don't know how image occlusion work, i won't help anymore.

**Comment by mikehardy** [comment]
edited the title to reflect that then - I suppose it'll be something between the desktop plugin and how we operate on mobile :man_shrugging:

**Comment by torebre** [comment]
It looks like it is the regular expression specified by imgPattern in Utils that does not match the image name string when it contains a ' . A fix may be to replace the pattern with one that is more like what is used in Anki.

Replacing it with "(?i)<img[^>]* src=(?<str>[\\\"'])([^>]+?)(\\k<str>)[^>]*>" (and using imgMatcher.replaceAll(" $2 ") is Utils.stripHTMLMedia) makes the card posted in the thread show up as expected. I haven't done further testing to check whether this expression works properly yet.

**Comment by snoyes** [comment]
Seems it affects AnkiMobile too.
https://www.reddit.com/r/Anki/comments/doy7hg/problem_with_some_cards_being_completely_blank_on/

**Comment by david-allison-1** [comment]
I'll self-assign if this isn't dealt with in 2 months. Should be a quick fix with `JSoup`

**Comment by SanjaySargam** [comment]
Is this still open?

**Comment by GautamCoder4019k** [comment]
@david-allison is the issue still open?

**Comment by david-allison** [comment]
@GautamCoder4019k it's been a while, it's open in that we need to be sure it's reproducible

**Comment by david-allison** [comment]
We've done a lot of work in the area, almost certainly fixed.

If not, will be simple to resolve
