### ISSUE TITLE
App crashes when a basic note type imports styling that contains the .cloze{} class selector

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#5351]
Continuing from [the discussion on the forum](https://groups.google.com/forum/#!topic/anki-android/Xykv32bgCg0), if a basic note type (or any non-cloze based note type) imports a css file containing the .cloze{} class selector, AnkiDroid crashes and won't reopen even after a device reboot. This was tested on 2.9alpha75 with the following files (note that .zip was added to the file name to allow uploading, to view the files, remove .zip):
[_css_cloze.css.zip](https://github.com/ankidroid/Anki-Android/files/3341370/_css_cloze.css.zip)
[_css_MAIN.css.zip](https://github.com/ankidroid/Anki-Android/files/3341371/_css_MAIN.css.zip)

The MAIN styling file just contains CSS that handles appearance of nightmode on desktop and ankidroid. The cloze styling file is the default styling for the cloze note type and is only 7 lines of CSS (without comments). Both work fine on their own, but if you try to copy the contents of the cloze file to the MAIN file, then sync, the app crashes at the next opening. In the styling section of the cards, importing is being done with this syntax:
`@import url("_css_MAIN.css");`

###### Reproduction Steps

1.  Import a CSS file in the styling section of any non-cloze based note type
2. Add the default cloze class selector (.cloze{}) to the file
3. Perform a media sync so the changes get pushed to AnkiDroid
4. Close AnkiDroid
5. Open AnkiDroid and crash

###### Expected Result
A basic note type (or any non-cloze based) should ignore the .cloze{} selector since it's only used on cloze note type

###### Actual Result
A crash

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.9alpha75

Android Version = 7.0

ACRA UUID = dfeef969-fa5d-43f8-8f41-00761d1ba055

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by sudomain** [comment]
huh. Now I can't reproduce the crash but I don't think I have my desired effect of having one CSS file. I have to try again in the morning

**Comment by mikehardy** [comment]
@sudomain I think you may have been bitten by something unrelated that went out in alpha75 #5354  - I specifically see your comment inside the crash report about cloze so I was able to put this together and relate it to you. I’m not saying there isn’t a cloze problem, but I know that one of your crashes at least was #5354

**Comment by mikehardy** [comment]
@sudomain alpha76 will be out as soon as google finishes processing it, and it contains the fix #5355 for the crash in #5354 - I can’t be certain because I haven’t tried to reproduce your cloze issue, but maybe it was just collateral and with alpha76 things work?

**Comment by david-allison-1** [comment]
@sudomain I can't reproduce this. Could you confirm whether this still occurs when you have a moment

Cheers

**Comment by sudomain** [comment]
Can't reproduce
