### ISSUE TITLE
Feature request: toggle remember last input on the "Edit Fields" screen

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#5353]
AnkiDroid has facilities for renaming, adding, removing, and repositioning fields. It also honors Anki Desktop's "Remember last input" setting when it is enabled on desktop and cards are added in AnkiDroid. It would be great if we could toggle the "stickyness" of a field on the menu that pops up when you long press a field. I'm not sure if there is a formal name for this menu, but it looks like  this:

![Screenshot_2019-07-25-14-28-51](https://user-images.githubusercontent.com/30786326/61899240-079f3c80-aee9-11e9-8b40-d35cc34b017c.png)

AnkiDroid Version = 2.9beta3

Android Version = 7.0

ACRA UUID = dfeef969-fa5d-43f8-8f41-00761d1ba055

**Comment by sudomain** [comment]
It seems this UI and helper methods are defined in ModelFieldEditor.java, including:

- addFieldDialog()
- deleteFieldDialog()
- renameFieldDialog()
- repositionFieldDialog()
- sortByField()

I might be wrong about this, but I think this might be the appropriate location for a new function:

toggleStickyField()

A few questions for project maintainers:
1. Since this feature just toggles a boolean in the database, maybe a "dialog" isn't needed for this function? Just  a context menu item that displays the current status and tapping it causes it to change values? iirc, a full sync isn't needed when toggling the stickyness
2. Once I have the function written, I would like to have two places to toggle the stickyness; the context menu I showed in my original post and in the menu that displays when tapping the paperclick icon when adding cards:

![Screenshot_2019-10-05-10-06-30](https://user-images.githubusercontent.com/30786326/66256050-1c554780-e758-11e9-89fb-86752b8b76a1.png)

I know this is more in the vein of the "Frozen Fields" add-on for desktop Anki, but I think being able to toggle this in the add cards activity would be helpful. Would this kind of deviation from desktop Anki be allowed?

**Comment by mikehardy** [comment]
Interesting - I haven't used this feature, but I just read through this issue and if I understand correctly the data storage for this feature, and the ability to handle the two states are already implemented? What's missing is just exposing the ability to change it? If I got that right I don't see anything wrong with adding it to the context menu that pops up while editing a field

I'll offer a warning for the paperclip menu - that area is hard to work with, so I'm iffier on it. I'd start with the context menu and see how that goes?

**Comment by sudomain** [comment]
Thank you for answer my question about the paperclip menu. Unless the toggleSticky() function is defined somewhere else, I don't think it is defined yet. In my limited experience with this codebase, it seems like the logical place to have it would be ModelFieldEditor.java since that is where add, delete, and rename field functionality is located. If I work on this "toggle sticky" function, is this where I would implement it?

**Comment by mikehardy** [comment]
That does sound logical, that's where I'd put it

**Comment by sudomain** [comment]
@mikehardy I'm giving this a shot now and in Android Studio I've edited a couple files (ModelEditorContextMenu.java and 17-model-manager.xml). I'm running into a problem where git status shows that .idea/codeStyles/Project.xml has also been modified, though I didn't modify this myself. Is there something wrong with my Android Studio config? is this expected behavior?

**Comment by mikehardy** [comment]
@sudomain interesting - that is the exact thing I would expect if you were either not on master fully up to date with #5459 or not using AndroidStudio 3.5.x

If you are up to date and have AndroidStudio 3.5+, a completely possible but unexpected result is that there is something else auto-edited in the style settings, or that I don't understand how it works.

Can you confirm your current on code and editor? And if so then maybe paste in the diff you see (between triple-backticks so it's formatted as code)?

And I can try to reproduce. In the meantime you can ignore the file - just don't add it to commits

**Comment by sudomain** [comment]
My "toggle-sticky-fields" branch is based on the following commit, which is timestamped 11/5/19:
4267b06acb00e75c9541b7796f43cee1e53dadfe

This is my Android Studio info from Help -> About:
Android Studio 3.5.1
Build #AI-191.8026.42.35.5900203, built on September 25, 2019
JRE: 1.8.0_202-release-1483-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by sudomain** [comment]
```

user@DESKTOP-FG6AA1U MINGW64 ~/git-repos/Anki-Android (toggle-sticky-fields)
$ git diff
diff --git a/.idea/codeStyles/Project.xml b/.idea/codeStyles/Project.xml
index f3b0fd25f..36e2aa8a7 100644
--- a/.idea/codeStyles/Project.xml
+++ b/.idea/codeStyles/Project.xml
@@ -24,6 +24,9 @@
         <package name="" withSubpackages="true" static="true" />
       </value>
     </option>
+    <AndroidXmlCodeStyleSettings>
+      <option name="ARRANGEMENT_SETTINGS_MIGRATED_TO_191" value="true" />
+    </AndroidXmlCodeStyleSettings>
     <JavaCodeStyleSettings>
       <option name="BLANK_LINES_AROUND_INITIALIZER" value="2" />
       <option name="IMPORT_LAYOUT_TABLE">
@@ -74,7 +77,8 @@
               <match>
                 <AND>
                   <NAME>xmlns:android</NAME>
-                  <XML_NAMESPACE>Namespace:</XML_NAMESPACE>
+                  <XML_ATTRIBUTE />
+                  <XML_NAMESPACE>^$</XML_NAMESPACE>
                 </AND>
               </match>
:...skipping...
diff --git a/.idea/codeStyles/Project.xml b/.idea/codeStyles/Project.xml
index f3b0fd25f..36e2aa8a7 100644
--- a/.idea/codeStyles/Project.xml
+++ b/.idea/codeStyles/Project.xml
@@ -24,6 +24,9 @@
         <package name="" withSubpackages="true" static="true" />
       </value>
     </option>
+    <AndroidXmlCodeStyleSettings>
+      <option name="ARRANGEMENT_SETTINGS_MIGRATED_TO_191" value="true" />
+    </AndroidXmlCodeStyleSettings>
     <JavaCodeStyleSettings>
       <option name="BLANK_LINES_AROUND_INITIALIZER" value="2" />
       <option name="IMPORT_LAYOUT_TABLE">
@@ -74,7 +77,8 @@
               <match>
                 <AND>
                   <NAME>xmlns:android</NAME>
-                  <XML_NAMESPACE>Namespace:</XML_NAMESPACE>
+                  <XML_ATTRIBUTE />
+                  <XML_NAMESPACE>^$</XML_NAMESPACE>
                 </AND>
               </match>
             </rule>
@@ -84,7 +88,8 @@
               <match>
                 <AND>
                   <NAME>xmlns:.*</NAME>
-                  <XML_NAMESPACE>Namespace:</XML_NAMESPACE>
+                  <XML_ATTRIBUTE />
+                  <XML_NAMESPACE>^$</XML_NAMESPACE>
                 </AND>
               </match>
               <order>BY_NAME</order>
@@ -95,6 +100,7 @@
               <match>
                 <AND>
                   <NAME>.*:id</NAME>
+                  <XML_ATTRIBUTE />
                   <XML_NAMESPACE>http://schemas.android.com/apk/res/android</XML_NAMESPACE>
                 </AND>
               </match>
@@ -105,6 +111,7 @@
               <match>
                 <AND>
                   <NAME>.*:name</NAME>
+                  <XML_ATTRIBUTE />
                   <XML_NAMESPACE>http://schemas.android.com/apk/res/android</XML_NAMESPACE>
                 </AND>
               </match>
@@ -115,6 +122,7 @@
               <match>
                 <AND>
                   <NAME>name</NAME>
+                  <XML_ATTRIBUTE />
                   <XML_NAMESPACE>^$</XML_NAMESPACE>
                 </AND>
               </match>
@@ -125,6 +133,7 @@
               <match>
                 <AND>
                   <NAME>style</NAME>
+                  <XML_ATTRIBUTE />
                   <XML_NAMESPACE>^$</XML_NAMESPACE>
                 </AND>
               </match>
@@ -135,74 +144,23 @@
               <match>
                 <AND>
                   <NAME>.*</NAME>
+                  <XML_ATTRIBUTE />
                   <XML_NAMESPACE>^$</XML_NAMESPACE>
                 </AND>
               </match>
               <order>BY_NAME</order>
             </rule>
           </section>
-          <section>
-            <rule>
-              <match>
-                <AND>
-                  <NAME>.*:layout_width</NAME>
-                  <XML_NAMESPACE>http://schemas.android.com/apk/res/android</XML_NAMESPACE>
-                </AND>
-              </match>
-            </rule>
-          </section>
-          <section>
-            <rule>
-              <match>
-                <AND>
-                  <NAME>.*:layout_height</NAME>
-                  <XML_NAMESPACE>http://schemas.android.com/apk/res/android</XML_NAMESPACE>
-                </AND>
-                </AND>
-              </match>
-            </rule>
-          </section>
-          <section>
-            <rule>
-              <match>
-                <AND>
-                  <NAME>.*:layout_.*</NAME>
-                  <XML_NAMESPACE>http://schemas.android.com/apk/res/android</XML_NAMESPACE>
-                </AND>
-              </match>
-              <order>BY_NAME</order>
-            </rule>
-          </section>
-          <section>
-            <rule>
-              <match>
-                <AND>
-                  <NAME>.*:width</NAME>
-                  <XML_NAMESPACE>http://schemas.android.com/apk/res/android</XML_NAMESPACE>
-                </AND>
-              </match>
-              <order>BY_NAME</order>
-            </rule>
-          </section>
-          <section>
-            <rule>
-              <match>
-                <AND>
-                  <NAME>.*:height</NAME>
-                  <XML_NAMESPACE>http://schemas.android.com/apk/res/android</XML_NAMESPACE>
-                </AND>
-              </match>
-              <order>BY_NAME</order>
-            </rule>
-          </section>
           <section>
             <rule>
               <match>
                 <AND>
                   <NAME>.*</NAME>
+                  <XML_ATTRIBUTE />
                   <XML_NAMESPACE>http://schemas.android.com/apk/res/android</XML_NAMESPACE>
                 </AND>
               </match>
-              <order>BY_NAME</order>
+              <order>ANDROID_ATTRIBUTE_ORDER</order>
             </rule>
           </section>
           <section>
@@ -210,6 +168,7 @@
               <match>
                 <AND>
                   <NAME>.*</NAME>
+                  <XML_ATTRIBUTE />
                   <XML_NAMESPACE>.*</XML_NAMESPACE>
                 </AND>
               </match>


```

**Comment by mikehardy** [comment]
Nothing weird about the versions. This shouldn't be happening. I'll have to look a little more deeply but I'm out of time for the day, it might be a while. Safe + recommended to just ignore it in diffs and commits for now. Also if you delete it after you already opened Android Studio it'll stay gone until you re-open Android Studio I think, and maybe permanently
