### ISSUE TITLE
crash: NullPointerException in new versioning startup code

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5354]
###### Reproduction Steps

1. Apparently you can do a few things. But, do a background sync
2. Switch back to app after the sync is done
3. crash?

###### Expected Result

That it works.
Or that it least generates valid stack traces (no idea what is going on there)

Since the stack traces aren’t great I can’t just snipe it, and I haven’t reproduced it yet, but it is prevalent

I am tracking this as a high priority since it was my code and it appears to crash across OS versions and devices for folks on alpha75

###### Actual Result

```
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.DeckPicker}: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3268)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3407)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7343)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference
at com.ichi2.anki.DeckPicker.showStartupScreensAndDialogs(DeckPicker.java:9)
at com.ichi2.anki.DeckPicker.onCreate(DeckPicker.java:37)
at android.app.Activity.performCreate(Activity.java:7802)
at android.app.Activity.performCreate(Activity.java:7791)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3243)
```

###### Debug info

https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/69c2044a-79fb-4202-99fd-ffc3ed818b5b

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by telotortium** [comment]
This is happening for me too - same Ankidroid version.

**Comment by mikehardy** [comment]
I will hopefully have a fix same day, it’s seemingly happening quite frequently so if I can’t reproduce I will be surprised

@telotortium can you tell me if it ever works correctly? or once it starts crashing this way are you stuck with crashes every time?

**Comment by telotortium** [comment]
The app is stuck crashing. It looks like the code might be obfuscated? Perhaps if you can send me a non-obfuscated build I can get the exact crashing line.

**Comment by mikehardy** [comment]
Nope, we don’t obfuscate, no reason it’s open source :-). Also I’m fully set up to build and reproduce it locally, I *wrote* the lines that are crashing (unfortunately). So I’m gearing up locally, just wondering what the impact was for users from someone currently experiencing it. Okay - Android Studio time…

**Comment by mikehardy** [comment]
(I will look at the stack thing separately, probably something about the transition from proguard to D8 even though we don’t obfuscate - the toolchain did change w.r.t dexing and all that since I’ve had a look at our stacks, maybe for release something is default on now and we are obfuscating unintentionally)

**Comment by mikehardy** [comment]
So far I have no luck reproducing this. 

I tried:
1- A fresh 2.8.4 install on API28 emulator, fresh AnkiWeb account, fresh shared deck import, sync, then install of 2.9alpha75. DB upgraded, sync worked afterwards.

2- A 2.9alpha75 install on same API28 emulator, syncing down a collection I’m pretty sure was before any of this stuff. Database checked, no problem.

3- my actual phone, also API28, it received the alpha from Play Store, did the database check on a huge collection, and is still syncing and working fine

I see crash traces from ACRA for API28 devices, so I’m just not tickling it somehow.

I’m stepping through the code now looking to see everywhere we might access that API to make it more defensive but I’d like to have a reproduction more than just armor.

If anyone can add exact steps they took (including prior versions used with the collection being synced, autosync settings, or anything else) I’d appreciate it.

**Comment by mikehardy** [comment]
Nevermind - found it. Adding test, fix coming shortly.

This happens if the application version recorded in preferences is stable (no upgrade) but the app ingests a full collection that has no AnkiDroid version (which we just started adding).

There are oddities with how the conf object in the database syncs and I suppose one of the edge cases got us there for many. Also if you do a full download without having synced after the upgrade that will do it.

**Comment by mikehardy** [comment]
Forgot the “Fixes” prefix for the bug number again on related PR
