### ISSUE TITLE
Edge cases are not handled correctly with new db version parameter

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#5364]
###### Reproduction Steps

1. Update AnkiDroid
2. Do a full sync from server
3. Restart AnkiDroid

###### Expected Result
AnkiDroid starts normally

###### Actual Result
AnkiDroid shows message "updated to version xyz"

###### Additional information
This also happens every time you start the app with an empty collection.

The incorrect "updated" message happens because of [this line](https://github.com/ankidroid/Anki-Android/blob/8837383ff1bcc2632d2b888fd51f984131fa53db/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L910), I presume.

The DB check is also going to be triggered in many cases, which is arguably intended behavior, but I would argue that it's too strict. It's getting triggered at [this line](https://github.com/ankidroid/Anki-Android/blob/8837383ff1bcc2632d2b888fd51f984131fa53db/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L941).

**Comment by timrae** [comment]
@mikehardy 
I'm thinking to revert these changes and disable the DB integrity for 2.9. The startup code is and has always been a huge spiderweb / clusterfuck. Every time I've tried to clean it up in the past, I've shot myself in the foot, so it's a huge risk, and if we're not going to include the template editor fixes, then there's not much point in doing the DB check in 2.9.

**Comment by timrae** [comment]
It's partially my fault for leaving it so late to merge, so sorry for that... I hesitated because I was scared that this kind of would happen, but in hindsight it would have been much better to merge early and test more.

**Comment by mikehardy** [comment]
Agreed on all points, this is a strong argument against release constipation in general I think, but we are here now. What I like about being here now is that there is real test coverage built, and easy infrastructure to make more. I can't fix this now as I'm traveling but I'm certain that any given issue is just a quick / easy to understand unit test away from being tickled and then fixed. Template editor testing isn't quite as exoressive but it's close. These areas will be clean eventually...
