### ISSUE TITLE
Ankidroid Can't Import a Deck

### ISSUE THREAD

**Issue by aghanki** [ankidroid/Anki-Android#5368]
1. I am using 2.8.5 beta 1 version . I made a single card into a deck .

2. I exported the card.

3. I sent the card to someone else to import
 4.
![Screenshot_2019-07-05-22-13-15-428_com ichi2 ankj](https://user-images.githubusercontent.com/50052329/60738638-4b4ef800-9f74-11e9-8c97-ba2332738db3.png)
after putting akpg file to right directory , and import the card , the empty message shown like the picture . but the deck had not imprted to the app.

debug info
AnkiDroid Version = 2.8.5beta1

Android Version = 9

ACRA UUID = 6feb8fc7-7496-4cdf-9297-da995e4571e5

**Comment by timrae** [comment]
Can you please upload the apkg here? We may also need you to provide a copy of your collection.

**Comment by aghanki** [comment]
i uploaded the deck that i have problem with it , named by Temp_Anki.apkg here.
and i made a tiny collection .
i upoaded both of them .
thank u

[Anki.zip](https://github.com/ankidroid/Anki-Android/files/3409698/Anki.zip)
