### ISSUE TITLE
Ankidroid Delete used Sounds and Pictures from database Bug report

### ISSUE THREAD

**Issue by aghanki** [ankidroid/Anki-Android#5369]
1. i used menu  , check media , when media was checked , the message showed that there is some files in media folder but not used by any cards.

2. i tapped on DELETE UNUSED .

3. after reviewing my cards , i realized some sound and image files has been deleted so i can't hear or see this .

4. if i copy the media files to collection.media folder again and repeat check media , the app will delete this files again !

debug info
AnkiDroid Version = 2.8.5beta1

Android Version = 9

ACRA UUID = 6feb8fc7-7496-4cdf-9297-da995e4571e5

![Screenshot_2019-07-05-22-38-12-483_com ichi2 anki](https://user-images.githubusercontent.com/50052329/60739137-0035e480-9f76-11e9-85d4-a0925bbcd0f4.png)

**Comment by aghanki** [comment]
i don't know what is the problem . but i am pro in using ankidroid .
this deck that i am talking about it , i built it by import from csv .
and you know what is strange ? it  is weird that one of the cards that i made ,  have an image which i import the image by myself not using csv and when i checked and deleted media , this image didn't delete but the others did. 
and you know what is more weird that i made 6 other decks like this but 2 of this decks have this probelm and the other 5 doesn't . 
i export the deck into apkg from anki desktop and i import to ankidroid to another smartphone ( 2.8.5 beta1 )  and i import it . but this problem didn't happened . 
and i don't know what is the problem . 
and this problem is not related to a specific deck , it happend to random media files from my big collection.

**Comment by aghanki** [comment]
I CHECKED media from pc . it happened again . you can see this bug from screenshots below. 
a media file is used to a card naemd :  Friends-S01E06 (1).JPG  , but both anki pc and android version says that this media file doesn't used in any cards . so this is a Bug. 
![media](https://user-images.githubusercontent.com/50052329/61522144-007ab900-aa27-11e9-9ece-946e5663faf0.JPG)

![Capture](https://user-images.githubusercontent.com/50052329/61522150-053f6d00-aa27-11e9-9bbe-575778809693.JPG)

this is just an example.

please do something

**Comment by snoyes** [comment]
I notice a difference in letter case - JPG vs jpg. If you make them match, does the problem continue or cease?

**Comment by aghanki** [comment]
i am here . the problem is not solved yet

**Comment by aghanki** [comment]
hi . guys . 
i updated my anki.
It's Version 2.1.26 (70784154).
but the problem still exists.
just look at the picture:
![image](https://user-images.githubusercontent.com/50052329/85316531-27acf680-b4d2-11ea-92e5-dcd3ad834549.png)

**Comment by aghanki** [comment]
> I notice a difference in letter case - JPG vs jpg. If you make them match, does the problem continue or cease?

It doesn't make any difference , i tried but it doesn't work.

**Comment by david-allison-1** [comment]
Hi @aghanki, this is for Anki Desktop, not AnkiDroid. Could you put in a bug report at: https://forums.ankiweb.net/

**Comment by aghanki** [comment]
> Hi @aghanki, this is an issues site for AnkiDroid, not Anki Desktop. Could you put in a bug report at: https://forums.ankiweb.net/ for Anki Desktop problems.
> 
> Thanks,
> 
> David

As i said before , it happens for Anki Desktop and Ankidroid , both, not only Anki desktop .

**Comment by aghanki** [comment]
all problems solved by doing this :
1- Rename Exactly what i use UPPER case or Lower case for both file names and extensions equal to cards and media.
2- some cases I did one space key before file name for example : [sound: kitten.mp3] , I mean before Kitten.mp3 and after : i used space key , so i deleted the space and problem solved.

I also believe the upper case and lower case issues is a bug in anki .and why? watch this:
I put cat.mp3 on my collection.media
and build cards include a sound file with this codes :
[sound:CAT.mp3]
[sound:Cat.mp3]
[sound:cat.mp3]
[sound:CAt.mp3]
so if i study this card . the card replay cat.mp3 four times.
so if i check media anki tells me :
The following files are referenced by cards, but were not found in the media folder:
Missing: ⁨CAT.mp3⁩
Missing: ⁨CAt.mp3⁩
Missing: ⁨Cat.mp3⁩
so , what is difference with them ? when i use many cards . i can’t remember what type name i used ? did i use file name with upper case ? did i use file name with lower case ?
it’s important for me to know ,because anki after check media says me that they are missing !

**Comment by dae** [comment]
Assuming this is an issue with some filesystems being case sensitive and others not. Feel free to reply if it's still an issue.
