### ISSUE TITLE
Feature: Sync with Ankiweb (if account available) at Startup

### ISSUE THREAD

**Issue by sw1tchbl4d3r** [ankidroid/Anki-Android#5373]
Hello,
I would like to see a feature like this in Ankidroid.
I learn through anki on my pc and my phone and the PC-Version automatically syncs at startup & at shutdown. I know that sync at shutdown could be difficult but sync at startup would be perfect!
Thanks

**Comment by timrae** [comment]
We already have an auto-sync feature, and there are various open issues for improvements
