### ISSUE TITLE
MathJax flickering

### ISSUE THREAD

**Issue by cazizen** [ankidroid/Anki-Android#5377]
###### Reproduction Steps
I am testing the MathJax support requested in #4915 and added in #5285:
1. Install the latest alpha.
2. Create a card with a MathJax expression, such as `\(\sin x\)`, using the standard `Basic` or `Cloze` template with no modifications.
3. Open on mobile.
4. Notice how the card renders.

###### Expected Result
No flickering.

###### Actual Result
The card flickers, momentarily displaying the raw markup before rendering. This happens both on showing the card and revealing the answer, and does not go away when the card is reviewed again.

###### Debug info
```
AnkiDroid Version = 2.9alpha80
Android Version = 9
```

###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by adamwolf** [comment]
IIRC, there's a render delay that I didn't bring over from Anki Desktop per
either Mike or Tim, because people are very picky about cards showing fast
(or something, I don't recall the details 100%).  I can take a look, and
make a branch with it, if we want to see which one folks prefer.

**Comment by adamwolf** [comment]
I confirmed--there is some code in
https://github.com/dae/anki/blob/b06b70f7214fb1f2ce33ba06d2b095384b81f874/web/reviewer.js
that
I can pull in and try to reduce this problem.

**Comment by mikehardy** [comment]
Huh - people are very picky about fast rendering, but I could see why a render delay in this case might make sense - rendering fast is great but rendering correctly first time is likely better. I think that was my counsel originally and I might be wrong here

**Comment by timrae** [comment]
Sounds good, let's try it

**Comment by adamwolf** [comment]
Sorry if the original message of mine sounded blamey, I didn't mean
anything negative by it at all!  My main computer is being repaired for a
few more days, but I should be able to get to this this week.  We will see
how it looks!

**Comment by mikehardy** [comment]
No worries at all! I just read it as correct attribution - I'm wrong all the time and even admit it occasionally ;-)

**Comment by adamwolf** [comment]
Ah, this was a "my bad".  I have a preliminary PR I'm setting up, but there's some room for improvement still.  I'll move discussion to that PR.

**Comment by adamwolf** [comment]
I think this is now solved.  Mathjax won't reflow after rendering as it will delay showing the content to the user until Mathjax has finished rendering--but that whole conditional only happens if there is Mathjax on the card. If there isn't, it shoots right past it and doesn't add any render flicker or delay.

**Comment by timrae** [comment]
Good job, thank you!
