### ISSUE TITLE
Adding {{front}} suspend/crush/etc app

### ISSUE THREAD

**Issue by ps-goog** [ankidroid/Anki-Android#5379]
###### Reproduction Steps

1. Start learning process
2. When you see card, edit it
3. Add {{front}}
4.ok/save
Applications is starting behave strange, nothing is refreshing until suspend  or crush

###### Debug info
AnkiDroid Version = 2.9alpha80
Android Version = 8.0.0
ACRA UUID = dd27ecef-281f-411a-b121-c44b1ca1bdb7

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
No longer relevant as Anki Desktop has disabled this functionality
