### ISSUE TITLE
Setting 'beginning next day' isn't synchronise

### ISSUE THREAD

**Issue by ps-goog** [ankidroid/Anki-Android#5380]
###### Reproduction Steps

1. Set 'beginning next day' on number different then is in Windows version
2. Synchronise

###### Expected Result
I should see the same time in anki for Windows

###### Actual Result
Nothing change in anki for Windows
And I synchronise from Windows this settings in ankidroid is overwrite with value from Windows

###### Debug info
AnkiDroid Version = 2.9alpha80
Android Version = 8.0.0
ACRA UUID = dd27ecef-281f-411a-b121-c44b1ca1bdb7

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
hey @ps-goog ! good to see you again - I'm not marking this as a duplicate but I *think* this is related at least to a few other open issues, the basic problem (I think!) is that there is one chunk of JSON in the collection that is sort of the master configuration for the whole collection, and I believe it has sync problems that affect all of the items in it

specifically table col, object 'conf' https://github.com/ankidroid/Anki-Android/wiki/Database-Structure
