### ISSUE TITLE
[Feature Request]  Hide Answer Buttons Only (Full Screen Mode)

### ISSUE THREAD

**Issue by tjbrn** [ankidroid/Anki-Android#5389]
Currently, the "Full Screen Mode" give **three** options: Off, Hide System Bar and Hide System Bar/Answer Buttons

I use gestures to answer my cards, so I want to hide the Answer Buttons, but maintain the System Bar. 

The System Bar still usefull with gestures because of the answer feedback (the small green/red dots on top of the screen), so I want do hide *just* the Answer Buttons.

(Expected with the new option) The "Full Screen Mode" give **four** options: Off, Hide System Bar, Hide System Bar/Answer Buttons **and Hide Answer Buttons Only.**

Current:
![image](https://user-images.githubusercontent.com/10359351/61592991-4911ae00-abb0-11e9-849f-41217af02849.png)

Expected with the new option *(Hide Answer Buttons Only)*
![90fa3546-9478-11e5-9ad1-5bdd7521abaf22222222](https://user-images.githubusercontent.com/10359351/61593027-bae9f780-abb0-11e9-8fe6-78106c27d407.png)

**Comment by danZ4C** [comment]
I would really like this too, or actually just to have an option to hide the answer buttons (and keep the top anki and system bars).

**Comment by Arthur-Milchior** [comment]
I really love the idea. Probably would be simple to implement since it is going to be similar to already existing option

**Comment by mikehardy** [comment]
@tjbrn this was implemented and released just now (in 2.16alpha46) by @smasher816! Cheers
