### ISSUE TITLE
Audio continues playing after card was deleted

### ISSUE THREAD

**Issue by pishutin84** [ankidroid/Anki-Android#5391]
###### Reproduction Steps

1. Open a card with an audio long enough to have time to delete the card
2. Right Top Corner - Tap 3 vertical dots (Menu) - Delete Note - Confirm

###### Expected Result
Next card shown. The audio from the deleted card should stop playing.

###### Actual Result
Next cars is shown. But the audio from the deleted card continues playing until its done.

###### Debug info
AnkiDroid Version = 2.8.4
Android Version = 7.0
ACRA UUID = 36b6a9aa-97cd-40e5-bda3-c56ee108fc3d

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by pablode** [comment]
This should be fixed as of PR #5434.

**Comment by mikehardy** [comment]
Oh didn't see the linked issue, thanks again @pablode
