### ISSUE TITLE
Feature request: UI to allow changing of the "Deck override" setting

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#5396]
AnkiDroid seems to honor the Deck override setting when it is set on Anki desktop. It would be a great enhancement if we could change this setting from the Card types screen in AnkiDroid. iirc, desktop uses a typing/autocomplete UI to change this setting, but a drop down menu of the available decks may be better for AnkiDroid

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
This is only available on non-cloze types.

https://github.com/ankitects/anki/blob/bbff62bf32df7b785534fedc999c56bceeafd27b/qt/aqt/clayout.py#L637-L643

Need to determine whether we can set this to a dynamic deck. I presume this can't happen.

**Comment by david-allison-1** [comment]
UI mockup

![image](https://user-images.githubusercontent.com/62114487/88612444-2481c900-d083-11ea-811d-1d6f906e556f.png)
