### ISSUE TITLE
Create automated test for "mathjax-needs-to-render" class in rendered card output

### ISSUE THREAD

**Issue by adamwolf** [ankidroid/Anki-Android#5397]
###### Reproduction Steps

1. Run the automated tests.

###### Expected Result

I expect to see an automated test that makes sure that "mathjax-needs-to-render" is in the card class list when the card question or answer contains MathJax.

###### Actual Result

No automated tests yet :(

This is a backlog-y ticket for me to refactor the cards a little bit so we can get the rendered output better.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Bot was hasty - sorry for the spam!
