### ISSUE TITLE
Feature request: Review Heatmap

### ISSUE THREAD

**Issue by o1516876** [ankidroid/Anki-Android#5399]
Are there any plans to add a review heatmap like that one from the great addon [Review Heatmap](https://github.com/glutanimate/review-heatmap)?

![review-heatmap](https://user-images.githubusercontent.com/45573416/62223503-53545900-b3b5-11e9-9343-721fcf002320.png)

**Comment by mikehardy** [comment]
Nope - if it's not in mainline Anki we don't support it. You can ask for that to be included in mainline though, on their support site
