### ISSUE TITLE
Cannot load ES2015 module because of CORS error

### ISSUE THREAD

**Issue by runiq** [ankidroid/Anki-Android#5400]
###### Reproduction Steps

Review [the card in this package (zipped)](https://github.com/ankidroid/Anki-Android/files/3456403/test.zip)

###### Expected Result

The div with ID `answerDiv` should be populated with the text "yay es2015 modules".

###### Actual Result

The message is not shown. The Chrome debugger shows a CORS error.

Steps:

1. Add above package
2. Enable AnkiDroid debugging
3. Visit chrome://inspect, select device
4. Load card and see the following CORS error:

```
Access to script at 'file:///sdcard/AnkiDroid/collection.media/_moduletest.mjs' from origin 'null' has been blocked by CORS policy: The response is invalid.
__viewer__.html:18 GET file:///sdcard/AnkiDroid/collection.media/_moduletest.mjs net::ERR_FAILED
```

###### Debug info

AnkiDroid Version = 2.9alpha66

Android Version = 9

ACRA UUID = dc263c15-851a-4700-8025-5a0f0748b419

###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by runiq** [comment]
When I look at the Chrome debugger, the page source is listed as `data:text/html;charset=utf-8;base64,`. I'm not sure if that'd debugger specific or actual helpful information, I just thought I'd mention it.

**Comment by runiq** [comment]
Added `.apkg` to reproduce issue.

**Comment by runiq** [comment]
This is probably the reason: https://stackoverflow.com/a/46992592

So, ES2015 modules are subject to CORS, which means the request to load them requires CORS headers, which cannot be set for local files.

I can't be the first person to run into this issue, can I…?

**Comment by runiq** [comment]
A workaround would probably be to:

1. run the internal chromium with [`--allow-file-access-from-files`](https://peter.sh/experiments/chromium-command-line-switches/#allow-file-access-from-files), which disables SOP between `file://` resources, and then…
2. open the HTML file as a `file://` document as well (and not as `data:…` as it's currently done).

**Comment by mikehardy** [comment]
Hi! Sorry for the delay, summer vacation time etc

You are the first person to run into this issue

Feel free to propose a PR if possible, but you might have more luck using your favorite javascript bundler to render into a single JS bundle. Then you've got access to more advanced things, standard languages, and typescript etc if you like 

An example: https://github.com/pigoz/anki-canvas

**Comment by runiq** [comment]
No worries, thanks for replying! :)

Yeah, I've kept looking into this stuff and am using webpack now: https://git.sr.ht/~runiq/anki

**Comment by mikehardy** [comment]
Great - and much better with typescript ;-). Cheers
