### ISSUE TITLE
The application still has NullPointerException

### ISSUE THREAD

**Issue by AssassinRain** [ankidroid/Anki-Android#5401]
Hello. I noticed some crashes in logs.  The corresponding commit version of code is  22ab79f, and application version is 2.8.4. 
## 1.com.ichi2.anki.IntentHandler
The exception trace is: 
*FATAL   EXCEPTION: main     java.lang.RuntimeException: Unable to start activity   ComponentInfo{com.ichi2.anki/com.ichi2.anki.IntentHandler}:   java.lang.NullPointerException: Attempt to invoke virtual method 'boolean   java.lang.String.equals(java.lang.Object)' on a null object reference     	at   android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)     	at   android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)     	at android.app.ActivityThread.-wrap11(Unknown Source:0)     	at   android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)     	at android.os.Handler.dispatchMessage(Handler.java:105)     	at android.os.Looper.loop(Looper.java:164)     	at android.app.ActivityThread.main(ActivityThread.java:6944)     	at java.lang.reflect.Method.invoke(Native Method)     	at   com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method   'boolean java.lang.String.equals(java.lang.Object)' on a null object   reference     	at com.ichi2.anki.IntentHandler.onCreate(IntentHandler.java:69)     	at android.app.Activity.performCreate(Activity.java:7183)     	at   android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)     	at   android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
### The command to trigger it is: adb shell am start -n com.ichi2.anki/com.ichi2.anki.IntentHandler -a android.intent.action.VIEW -d content://null
adb shell am start 
## 2.com.ichi2.anki.NoteEditor
The exception trace is: 
*FATAL   EXCEPTION: main     java.lang.NullPointerException: Attempt to invoke virtual method   'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null   object reference     	at com.ichi2.anki.NoteEditor.fetchIntentInformation(NoteEditor.java:563)     	at com.ichi2.anki.NoteEditor.onCollectionLoaded(NoteEditor.java:407)     	at com.ichi2.anki.AnkiActivity.onLoadFinished(AnkiActivity.java:286)     	at com.ichi2.anki.AnkiActivity.onLoadFinished(AnkiActivity.java:42)     	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)     	at   android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)     	at android.support.v4.content.Loader.deliverResult(Loader.java:126)     	at   com.ichi2.async.CollectionLoader.deliverResult(CollectionLoader.java:42)     	at   com.ichi2.async.CollectionLoader.deliverResult(CollectionLoader.java:12)     	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:252)     	at   android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)     	at   android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:485)     	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:502)     	at android.os.Handler.dispatchMessage(Handler.java:105)     	at android.os.Looper.loop(Looper.java:164)     	at android.app.ActivityThread.main(ActivityThread.java:6944)     	at java.lang.reflect.Method.invoke(Native Method)     	at   com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)*
## 3.com.ichi2.anki.Reviewer
The exception trace is: 
*FATAL   EXCEPTION: main     java.lang.RuntimeException: Unable to start activity   ComponentInfo{com.ichi2.anki/com.ichi2.anki.Reviewer}:   java.lang.NullPointerException: Attempt to invoke virtual method 'long   android.os.BaseBundle.getLong(java.lang.String, long)' on a null object   reference     	at   android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2957)     	at   android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3032)     	at android.app.ActivityThread.-wrap11(Unknown Source:0)     	at   android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)     	at android.os.Handler.dispatchMessage(Handler.java:105)     	at android.os.Looper.loop(Looper.java:164)     	at android.app.ActivityThread.main(ActivityThread.java:6944)     	at java.lang.reflect.Method.invoke(Native Method)     	at   com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)     	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method   'long android.os.BaseBundle.getLong(java.lang.String, long)' on a null object   reference     	at com.ichi2.anki.Reviewer.selectDeckFromExtra(Reviewer.java:81)     	at com.ichi2.anki.Reviewer.onCreate(Reviewer.java:73)     	at android.app.Activity.performCreate(Activity.java:7183)     	at   android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)     	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2910)*
### The command to trigger it is: adb shell am start -n com.ichi2.anki/com.ichi2.anki.Reviewer -a android.intent.action.VIEW

Because all these activities are exported ones, i.e., be exposed to outside, they may receive unfriendly commands and then lead to app crash.  After investigation, we found that the missing of null checkers causes those crashes. 
Please help to confirm whether they are true bugs. We believe that fixing these bugs will further improve the robustness of this app.

**Comment by mikehardy** [comment]
Crash testing should only be done on master, if you can reproduce this there we can reopen and hunt them down

**Comment by AssassinRain** [comment]
Hello, we perform the test on the master branch and found out some bugs still exist. The corresponding commit version of code is 95087f5.
And there is our test result.
## 1.com.ichi2.anki.IntentHandler
The exception trace is:
*08-06 00:56:43.999 20568 20568 E AndroidRuntime: FATAL EXCEPTION: main
08-06 00:56:43.999 20568 20568 E AndroidRuntime: Process: com.ichi2.anki, PID: 20568
08-06 00:56:43.999 20568 20568 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.ichi2.anki/com.ichi2.anki.IntentHandler}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at android.app.ActivityThread.-wrap11(ActivityThread.java)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at com.ichi2.utils.ImportUtils.handleFileImport(ImportUtils.java:62)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at com.ichi2.anki.IntentHandler.onCreate(IntentHandler.java:35)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6251)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
08-06 00:56:43.999 20568 20568 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)*
### The command to trigger it is: adb shell am start -n com.ichi2.anki/com.ichi2.anki.IntentHandler -a android.intent.action.VIEW -d content://null
### 2.com.ichi2.anki.NoteEditor
The exception trace is:
*08-06 00:01:22.527 14120 14120 E AndroidRuntime: FATAL EXCEPTION: main
08-06 00:01:22.527 14120 14120 E AndroidRuntime: Process: com.ichi2.anki, PID: 14120
08-06 00:01:22.527 14120 14120 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at com.ichi2.anki.NoteEditor.onSaveInstanceState(NoteEditor.java:317)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at android.app.Activity.performSaveInstanceState(Activity.java:1302)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnSaveInstanceState(Instrumentation.java:1289)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at android.app.ActivityThread.callCallActivityOnSaveInstanceState(ActivityThread.java:4088)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3490)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3550)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at android.app.ActivityThread.-wrap20(ActivityThread.java)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1373)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
08-06 00:01:22.527 14120 14120 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)*
### The command to trigger it is: adb shell am start -n com.ichi2.anki/com.ichi2.anki.NoteEditor -a android.intent.action.SEND

**Comment by mikehardy** [comment]
Thanks so much for retesting! I'll look into these although if you propose PRs to fix them that would be awesome

**Comment by AssassinRain** [comment]
OK, we have submited a PR with commit version 852eb1c.

**Comment by AssassinRain** [comment]
OK, I opened my pull request, thanks.

**Comment by adamwolf** [comment]
Have we confirmed this is fixed now that the PR is merged in?

**Comment by mikehardy** [comment]
I'm going to assume yes for issue list hygiene, we can always reopen if not

(normally I work in repos with the stale bot, so these things are auto-swept unless they have some specific label to stay open...)
