### ISSUE TITLE
Widget Not Updating / Non Responsive

### ISSUE THREAD

**Issue by SvenskNavi** [ankidroid/Anki-Android#5402]
###### Reproduction Steps

1. Have widget added to homescreen
2. Have leftover cards due from one day to the next
3. Observe widget/try to open app from widget

###### Expected Result

Widget updates cards due as needed and allowed tapping to open app.

###### Actual Result
The widget only updates stats after opening the app manually, and won't even display them if it's been a few days. Also won't open by tapping if it's been a few days (seems like the disappearance and non-responsiveness occur simultaneously). I believe this started after updating to Android 9.

###### Debug info
AnkiDroid Version = 2.8.4

Android Version = 9

ACRA UUID = 6fc63696-d6a9-4c53-b846-2ca4021d617a

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Try the workarounds at dontkillmyapp.com and report back this smells like aggressive power saving to me

**Comment by SvenskNavi** [comment]
I turned off battery optimizing per recommendation on that site, and it seems to have worked, haven't had an issue in 3 days.

**Comment by mikehardy** [comment]
that's great to hear!
