### ISSUE TITLE
Misuse of AsyncTask

### ISSUE THREAD

**Issue by cuixiaoyiyi** [ankidroid/Anki-Android#5404]
###### Reproduction Steps
In com.ichi2.anki.stats. AnkiStatsTaskHandler
The problems is:
1. It holds strong reference to the GUI element of View or Activity, which can lead to memory leak when the Activity is destroyed and the AsyncTask did not finish.
```
private class CreateChartTask extends AsyncTask<View, Void, PlotSheet>
private ChartView mImageView;
//....
private class CreateStatisticsOverview extends AsyncTask<View, Void, String>
private WebView mWebView;
```
###### Expected Result
```
private class CreateChartTask extends AsyncTask<View, Void, PlotSheet>
private WeakReference<ChartView> mImageView;
//....
private class CreateStatisticsOverview extends AsyncTask<View, Void, String>
private WeakReference<WebView > mWebView;
```

**Comment by mikehardy** [comment]
Interesting find - are you discovering this by manual code inspection or are you using an auditing tool (and if so, which one?). PRs are welcome, seems like a simple change

**Comment by cuixiaoyiyi** [comment]
Thank u for yr comment. I use an automated test tool developed by ourselves with tech of static analysis. And I confirm this by manual code inspection according to the results of detection. This tool is planned to be open source afterward. If u r interested in this tool, more discussions  are welcome.  I will try to submit the PRs.

**Comment by farjadilyas** [comment]
Can I work on this?

**Comment by david-allison-1** [comment]
Sure, thanks!
