### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by lstwn** [ankidroid/Anki-Android#5408]
###### Reproduction Steps

1. Clone the repo `git clone git@github.com:ankidroid/Anki-Android.git ankitest`
2. Open Android Studio
3. Run AnkiDroid (Shift+F10)

###### Expected Result

Should build and run the apk on my device/emulator.

###### Actual Result

When running the gradle tasks, one of them fails. Output:
`org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':AnkiDroid:transformClassesWithInstantRunForDebug'`
However, I cannot find the related task because I have little knowledge about Android dev and so on.

###### Debug info
Running it on Linux with Fedora 30.

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
Are you using the latest version of Android studio?  Has gradle installed
of the AnkiDroid dependencies? Have you tried deleting the Android studio
project and re-creating it?

**Comment by mikehardy** [comment]
You can also try the command line, in ankitest `./gradlew jacocoUnitTestReport` should work for a full build and then run a bunch of tests

In general though, it does build and work so this is confusing - must be some reason. I use Ubuntu which I know is different from Fedora but signals that linux at least should be just fine for AnkiDroid development

**Comment by lstwn** [comment]
Hi guys, thanks for the quick replies!

I investigated this a little further and stumbled upon this: [https://medium.com/@ma.labbao/solving-d9890bb9111c]

Apparently, this is a weird issue with the `instant run` feature. All you have to do is deactivate this in the Android Studio settings. The task that failed (`:AnkiDroid:transformClassesWithInstantRunForDebug`) was also not present in the gradle task explorer on the right pane but gets injected automatically if using this feature.

However, afterwards I had some issues because of me using the PlayStore release build at the same time on my device - for studying of course ;)

I found a way, how to install a debug version next to the release version by using an `applicationIdSuffix` and some changes in the manifest. But it suprised me somewhat that this was not possible yet. So it might have been like this for a reason? Or should I create a pull request with the needed changes?

**Comment by mikehardy** [comment]
I use my dev version for studying :-)

But you can also use the parallel releases - I keep them pretty up to date here https://github.com/mikehardy/Anki-Android/releases

Glad you got your build working - please feel free to edit the development page on the wiki to mention instant run should be disabled - seems like that's a requirement?

**Comment by adamwolf** [comment]
I had to disable instant run as well, when I set up my environment, folks.

**Comment by adamwolf** [comment]
I added instructions to the wiki.  If that seems good to someone else, I think we can close this.

**Comment by mikehardy** [comment]
What @adamwolf ? You are so out of date. Instant Run is dead, long live Apply Changes https://developer.android.com/studio/run#apply-changes (as of Android Studio 3.5)

Which may or may not be broken, I'm not sure

**Comment by adamwolf** [comment]
Every time I open Android Studio I have a few gigs to download for "updates", looks like one does something new now! :)

**Comment by mikehardy** [comment]
I'm mostly react-native now, which gives me the added joy of also needing to open Visual Studio code, get new node packages, open Xcode (even porkier than Android Studio) and deal with iOS and mac updates. I'm pretty sure 50% of my total available bandwidth capacity is taken up by updates at this point.

Progress

**Comment by adamwolf** [comment]
This can be closed.  Instant run has been replaced by Apply Changes, which works.

**Comment by mikehardy** [comment]
Huzzah
