### ISSUE TITLE
"Notify when" setting not functioning on 2.9beta6

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#5413]
###### Reproduction Steps

1.  Have cards due ( ~200 for me)
2.  Turn on the Notify when setting under general settings and set it to when "more than 10 cards are due"

###### Expected Result

A notification saying cards are due. I remember it working in a previous version

###### Actual Result

No notification despite due cards. I tried syncing, closing the app, adding a new note, and rebooting the device

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.9beta6

Android Version = 7.0

ACRA UUID = dfeef969-fa5d-43f8-8f41-00761d1ba055

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by SimonHeimberg** [comment]
Now summarized in #5535
