### ISSUE TITLE
Unreleased resources when finished playing audio (Bluetooth connection)?

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#5414]
###### Reproduction Steps

1. Create a note with sound.
2. Connect the phone to a Bluetooth device, like a headset.
3. Start playing music so that it is audible in the headset.
4. Open AnkiDroid and go to a card made from the note creates in step 1 and play the sound.

###### Expected Result

The music volume is decreased, the sound from the note is audible, and after it is finished playing, music volume is increased to its original level.

###### Actual Result

The music volume is decreased, the sound from the note is audible, but after it is finished playing, music volume is kept at the decreased level. Only after a note is changed to the next/previous one doesn the music get back to its original volume level.

It acts as if once AnkiDroid starts playing audio, when it is done, it doesn't 'release' whatever resources it needed to acquire to start playing.

###### Debug info

AnkiDroid used: 2.8.4.

###### Research

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi @wujek-srujek - we are very close to releasing 2.9 stable and the underlying libraries have been updated by several major versions - can you try 2.9? https://docs.ankidroid.org/manual.html#betaTesting

**Comment by wujek-srujek** [comment]
Hi @mikehardy , I've just retested with 2.9beta7 and the problem still persists.

**Comment by david-allison-1** [comment]
`playSound` accepts an `OnCompletionHandler` to allow a callback, but we do not hook our own callback to release audio.

https://github.com/ankidroid/Anki-Android/blob/de5b06c0b148c604f9fc3c00277554ee0e2ea2e7/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java#L267-L269

`playSounds` plays all sounds and we hook our own callback here.

Related: #5022 (general audio refactoring).

**Comment by mikehardy** [comment]
This is merged and should be available in the next alpha (not released yet, but soon)

**Comment by mikehardy** [comment]
2.10alpha47 is published with this and will be available when google is done processing it 🚀
