### ISSUE TITLE
No sound while studying sync'd deck. Preview feature in Browse plays audio. 

### ISSUE THREAD

**Issue by AndrewMcSwain** [ankidroid/Anki-Android#5418]
###### Reproduction Steps

1. Download shared deck on ankidroid
2. Study reguarly and everything works fine
2. Sync to AnkiWeb 
3. Sync Anki Windows from Ankiweb
4. Study Deck
5. No sound
6. Browse Deck. Sound works. 
7. Check Media returns 

'In media folder but not used by any cards:
collection (1).apkg
Thumbs.db'

8. Do a quick search for .apkg files, thinking to rename the collection from 'collection (1).apkg'
to 'collection.apkg' 
9. there are 4 files in 4 different locations with the same name

Might this be the issue? Which of these files do I rename?
 
p.s.: ankiweb study plays sound, but replay upon flipping the card is not always available? 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Hi @AndrewMcSwain,

Do you have a sample that will reproduce this issue?
