### ISSUE TITLE
Cloze detection broken for multi-line cloze inside html tag

### ISSUE THREAD

**Issue by leezu** [ankidroid/Anki-Android#5421]
###### Reproduction Steps

1. Create a cloze containing the following html on Anki Desktop:

```
<p>Cloze in html tag with {{c1::multi-line
string}}</p>
```
Note the difference to
```
<p>Cloze in html tag with {{c1::string}}</p>
```
or 
```
Cloze with {{c1::multi-line
string}}
```

2. Sync to AnkiDroid
3. Review notes

###### Expected Result
All 3 notes should show up as `Cloze with [...]`.

###### Actual Result
The `<p>Cloze in html tag with {{c1::multi-line
string}}</p>` note does not show up correctly.
Instead `Edit this note and add some cloze deletions. (help)` is displayed.

After clicking "Edit note" on AnkiDroid without making any changes to the note, the note is displayed correctly.
Checking on Anki Desktop, it turns out that clicking Edit note on AnkiDroid changed the html of the note to:
```
<p>Cloze in html tag with {{c1::multi-line<br>string}}</p>
```

###### Debug info
AnkiDroid Version = 2.9beta7

Android Version = 10

ACRA UUID = b8969252-15d5-4075-92a1-81871187ab4b

###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
interesting! great report
The perturbation of the note (saving it back as something different without editing) is tracked elsewhere #3304 which can be summed as "if you edit but make no changes, no changes should be made" (a reasonable stance)

This issue should be focused on "the close identification regexp seems to be different on AnkiDroid than Anki Desktop"

The python code they're using in Anki Desktop should be examined and whatever part makes it work multiline should be brought in to here

This should be a great first issue since Anki Desktop (code available here https://github.com/dae/anki/) is so easy to inspect

**Comment by mikehardy** [comment]
thanks by the way for confirming this in the beta so we know it is a current issue - that would have been one of my first requests :-)

**Comment by adamwolf** [comment]
Leonard, if you are interested in digging into this, it's a good first
issue.  If you aren't, let me know--I was just in this code and I can
probably hammer this out in a few minutes since you have a great test case.

**Comment by leezu** [comment]
@mikehardy Both the AnkiDroid and Anki regexes seem the same and explicitly enable matching new-lines via the `(?s)` inline flag.

https://github.com/dae/anki/blob/8a2a4d827f1afcab746585ede2ac08833d679757/anki/template/template.py#L7

https://github.com/ankidroid/Anki-Android/blob/95087f50410ff58fe5a8e914ca6462b53b74fe53/AnkiDroid/src/main/java/com/ichi2/libanki/template/Template.java#L48

The buggy behaviour only occurs when wrapping the cloze in `<p></p>` tags.

@adamwolf I don't have an Android dev setup ready to verify any changes, so it would be appreciated if you could go ahead ;) Thanks for taking care of it!

**Comment by adamwolf** [comment]
I'm out this weekend for a US holiday but I will be back at it early next
week.

**Comment by adamwolf** [comment]
(I'm a few minutes into this, adding some tests, and... we have at least a few bugs here, folks!)

Thanks @leezu.  Good catch!

**Comment by mikehardy** [comment]
Nothing like good user reports (yes, thank you @leezu ) + automated testing + a developer ready to go (thank you @adamwolf ) :-)

**Comment by adamwolf** [comment]
Can someone confirm this is fixed in the latest betas?

**Comment by leezu** [comment]
It's fixed, thank you!
