### ISSUE TITLE
Irritating count on stack overview for subdeck

### ISSUE THREAD

**Issue by SimonHeimberg** [ankidroid/Anki-Android#5422]
Maybe not a bug, but irritating

##### Reproduction Steps

1. Have a deck with several subdecks. (No cards are directly in the deck.)
2. At least one subdeck has more new cards than the limit for new cards.
3. Optional increase the limit for new cards on a subdeck.

##### Expected Result

The sum matches somehow. Or at least the number of new cards for the parent deck is at the limit.

###### limit of new cards is 5
Some subdecks have more than 5 new cards.

T      **4** 1 0  _why 4 (=limit - 1)_
T::A 2 1 0
...

![20190901_144945](https://user-images.githubusercontent.com/16302148/64073421-23f47d00-ccd0-11e9-9fc7-6ed598482f7e.png)

###### limit of new cards is 15
no subdeck has 15 new cards.

T      **14** 1 0  _why 14 (=limit - 1)_
T::A 2 1 0
...

![20190901_145223](https://user-images.githubusercontent.com/16302148/64073130-3967a800-cccc-11e9-84ea-60105cd8c522.png)

###### case limit increased

After increasing limit for new cards by 2 on subdeck A (after limit was reached).

X      2 1 0
X::A 2 1 0
X::B *2* 0 0    _why 2 here?_
X::C 0 0 0

##### Debug info
AnkiDroid Version = 2.9beta7

Android Version = 5.0.1

ACRA UUID = 0c4a528c-8ca2-4cfe-b399-004b7d2d2698

Experimental statistics = enabled

V2 scheduler = enabled

##### Research

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Interesting - how does Anki Desktop behave? This may be an upstream bug that we've ingested, and should properly be logged there then we transpose the fix to Java. Or it could be a fresh AnkiDroid-specific thing...

**Comment by SimonHeimberg** [comment]
It is less irritating than it looked like first.
The total of new cards is limit-1 because I have learnt 1 card on deck b. (At least likely, todays test showed this.) I did not see before that the maximum for all decks below the parent deck is reduced in this case.
So the 1st two cases are clear now.

The 3rd case may be a bug, but it is not so simple to reproduce.

I have no computer nearby, so I can not try with Anki.

**Comment by SimonHeimberg** [comment]
It is less irritating than it looked like first.
The total of new cards is limit-1 because I have learnt 1 card on deck b. (At least likely, todays test showed this.) I did not see before that the maximum for all decks below the parent deck is reduced in this case.
So the 1st two cases are clear now.

The 3rd case may be a bug, but it is not so simple to reproduce.

I have no computer nearby, so I can not try with Anki.
