### ISSUE TITLE
Custom sync server self-signed certificate authority network error

### ISSUE THREAD

**Issue by ARR8** [ankidroid/Anki-Android#5423]
Hi,  
I have set up an instance of tsudoko/anki-sync-server behind a reverse proxy with an HTTPS certificate signed by a custom certificate authority. After importing the CA into the Android user CA store, whenever I tried to log in, I would get a message saying "A network error has occurred."

I know you do not support this kind of setup, but I resolved the issue after moving the user certificate to the system certificate store. I create this issue partly in case someone has a similar problem and partly because I suspect the problem is related to [this](https://android-developers.googleblog.com/2016/07/changes-to-trusted-certificate.html). I think it would make sense for the app to be configured to trust user-added CAs to complement the custom server support, if it is not too difficult. Thanks.

Also, the opacity of the error was a bit frustrating while I was trying to figure out the cause; any way to show a more detailed exception?

###### Debug info
AnkiDroid Version = 2.8.4

Android Version = 9

ACRA UUID = 09a29163-4cbe-45e0-b221-c37bcbdc06aa

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! You are right that we don't really support it, and it is a very niche case - a vanishingly small percent of the userbase uses it.

If you want to propose a PR that makes error messages more clear or alters connection behavior you'd have to test it and make the PR

I think it'll be something around here https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/sync/HttpSyncer.java#L195

Please note that there is a related issue about moving the library completely as our current HTTP library needs to be swapped, so any work in the area should either be really "light" (not too large an investment in anyone's time reviewing or risking impacts) or should be in the direction of doing the swap or done in way compatible with the swap needed https://github.com/ankidroid/Anki-Android/issues/3626#issuecomment-427583694

**Comment by adamwolf** [comment]
I have a few other error messages I'd like to add re custom servers, for
instance, it is not clear that one of the urls have supplemental strings
added to it, and one does not...

**Comment by mikehardy** [comment]
Mmm - I had not considered the local network case much. That's an interesting point. 
There is an RFC for internal only IP space that defines all the ranges 

https://datatracker.ietf.org/doc/html/rfc1918#section-3

```
     10.0.0.0        -   10.255.255.255  (10/8 prefix)
     172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
     192.168.0.0     -   192.168.255.255 (192.168/16 prefix)
```

I suppose we could add an exception for non-SSL connections to those somehow? I have not investigated this, it may not be feasible but regardless of further investigation the first question is - @anadi - would allowing non-SSL connections to custom sync servers in those network ranges satisfy your use case?

**Comment by anadi** [comment]
Thanks for your reply Mike!

I think just allowing non-SSL connection to custom sync servers would be very helpful to people learning / studying with anki. The benefits far outweigh the lack of privacy.

I do understand the concern about passwords & request data being visible, to that I say:
1. To a hacker, but these are closed networks. No NAT path to server from public network interface of router.
2. There isn't much of value here to steal. Students learning and personalization of memory data.
3. Any SSL we may ask people to use, must come with instructions to dockerize and NAT the server to wifi interface of linux (Raspberian or Ubuntu)
4. You probably guessed: most of these tutors would like to run the server on Raspberry Pi (100 USD, A monitor, A network router is what they primarily use)
5. Internet & Power availability is still very patchy. Cheap android phones and a small UPS to run Raspberry PI just streches the investment far beyond what we can imagine.

**Comment by mikehardy** [comment]
Can you please answer my question directly?

> would allowing non-SSL connections to custom sync servers in those network ranges satisfy your use case?

**Comment by anadi** [comment]
Yes, it will. Thanks

**Comment by mikehardy** [comment]
@anadi in the end this is not possible, we cannot specify IP ranges and we cannot allow cleartext by default.
Luckily it is very easy to get SSL certificates, it is just a necessary thing these days - the Let's Encrypt project is the best way to handle it I think https://letsencrypt.org/

https://github.com/ankidroid/Anki-Android/pull/9149#discussion_r658927703
