### ISSUE TITLE
Default Audio Recording Format is .3gp

### ISSUE THREAD

**Issue by johnlawrenceaspden** [ankidroid/Anki-Android#5426]
Recording audio with my mobile phone creates .3gp files by default, which neither ankiweb nor, apparently, Apple devices like. 

However it's possible to record over existing .mp3 files, and they stay as .mp3. 

Would it be possible to change the default type to .mp3 for compatibility with the rest of the system? 

If not, perhaps even better would be an option to set the default sound recording type.

###### Reproduction Steps

1. Record a bit of audio

###### Expected Result

produces mp3 file

###### Actual Result

produces 3gp file

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x I have searched for similar existing issues here and on the user forum

**Comment by johnlawrenceaspden** [comment]
AAnkiDroid Version = 2.8.4

**Comment by mikehardy** [comment]
Very interesting. Makes perfect sense of course. Thanks for logging some interesting ones (I see the others too)

**Comment by johnlawrenceaspden** [comment]
I've been doing lots of little snatches of audio recording with
AnkiDroid recently and so I've run into a few minor problems. I
thought you might appreciate bug reports.

I would like to say that I think AnkiDroid is the most marvellous
thing. I wouldn't bother moaning about bugs in something that I didn't
love. Thank you so much!

**Comment by Kartikkman** [comment]
Hey @mikehardy , Can you assign this issue to me as well .

Please put your inputs , I will start working on this today . 

Please also Check Initial Picture Tutorial , I have created 4 static images ,

Thank You for all the support .

**Comment by mikehardy** [comment]
@Kartikkman - you can just grab anyone you want I think - in the 'Assignees' area of the github web ui to the top right, just click 'assign yourself' and go for it. I don't really have any more input on this one - and I saw that you made progress on the tutorial but I haven't had time to review sorry - lots of Real Job work this week as everyone just got back from vacation...

**Comment by Kartikkman** [comment]
Hey @timrae 

Can you provide me input on How to solve this one ??

**Comment by mikehardy** [comment]
You'll have to do research I think - look at the APIs we use to create 3gp files and see how to make it produce mp3s instead.

**Comment by Kartikkman** [comment]
Hey @mikehardy  . I got some insight on the Issue . Here are takeaways : 

- AudioView.java ( File where we are doing recording related stuff  & setting format of recording to 3GP ) 

- To Save the Recording into MP3 isn't just about calling the API to set it to MP3 , reason is that 
   Android doesn't support **ENCODING** of MP3 . 

Here are the Reference Links : 

`https://developer.android.com/guide/topics/media/media-formats`
`https://stackoverflow.com/questions/4886365/androidhow-to-get-media-recorder-output-in-mp3-format`

- In Order to save the File as mp3 , one needs to use Encoding Library for mp3 

Thanks 
@mikehardy

**Comment by mikehardy** [comment]
If the goal is to be cross-platform, I think the best bet is AAC LC in an .mp4 container.

I believe that would work on AnkiMobile, AnkiWeb, the desktop and AnkiDroid. But it would need to be tested

**Comment by johnlawrenceaspden** [comment]
Hang on, if the audio file is already .mp3, it has no problem
recording over it, and the new file is also .mp3 It's only new ones
that are .3gp

**Comment by mikehardy** [comment]
@johnlawrenceaspden  !?! That is most unexpected. https://developer.android.com/guide/topics/media/media-formats says there is no default mp3 encoder! Perhaps it is "corrupting" the file be recording .3gp format *into* the file but keeping the file name, and the decoder is just able to ignore the file name and go off the file header (first bytes) indicating 3gp format.

I'd triple-check a specific example like this, and if we are doing this (scribbling non-mp3 audio into an .mp3-extension filename) then that's kind of a separate bug

**Comment by Kartikkman** [comment]
Hey @mikehardy I have made tiny tweaks in Code , saving Audio in mp4 format . Tested it out on 
AnkiDesktop , AnkiWeb , Ankidroid . 

But before deleting a section of Code ,I should consult from you : 

Below is the Code ( which uses the Codec **AMR_NB**  IF   **AAC** codec is not supported on the Device , Now problem that arises with using in **AMR_NB** is that we can't put it in a mp4 file because that is not supported . 


```
if (!highSampling) {
                            // if we are here, either the codec didn't work or output file was invalid
                            // fall back on default
                            try {
                                mRecorder = initMediaRecorder();
                                mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);

                                mRecorder.prepare();
                                mRecorder.start();

                            } catch (Exception e) {
                                // either output file failed or codec didn't work, in any case fail out
                                Timber.e("RecordButton.onClick() :: error recording to " + mAudioPath + "\n" +e.getMessage());
                                showToast(gtxt(R.string.multimedia_editor_audio_view_recording_failed));
                                mStatus = Status.STOPPED;
                                break;
                            }

                        }

```

What needs to be done in this case @mikehardy ? 
Thank You for all the Support ( I am indebted )

**Comment by Kartikkman** [comment]
Hey @mikehardy , Have made Code Changes . Please Check !! 
I know it's been daunting for you to guide me , I thank you a Lot for this . I will be trying to Learn Things . 

Thank You
