### ISSUE TITLE
Rerecording audio tends to bugger up the field

### ISSUE THREAD

**Issue by johnlawrenceaspden** [ankidroid/Anki-Android#5427]
If a note has an audio file, e.g. [sound:noise.mp3], then recording over it in ankidroid often corrupts the field, often duplicating the original e.g. [sound:noise.mp3][sound:noise.mp3]. It's easily fixed by deleting the spare text, but it's frequent and annoying.

###### Reproduction Steps

1. find a note with an audio file
2. record over it using ankidroid

###### Expected Result

existing file is replaced with new recording, field unmodified

###### Actual Result

something like half the time the contents of the field will get duplicated, leading to the new recording being played twice in the card. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

**Comment by johnlawrenceaspden** [comment]
AAnkiDroid Version = 2.8.4

**Comment by timrae** [comment]
It's done this way on purpose to allow multiple media files in a field I think... The file name should be different everytime you record, does it really "corrupt" it?

**Comment by johnlawrenceaspden** [comment]
It's not so much that it corrupts it as that strange things happen. 

Say, you start out with a field which contains only [sound:aa.mp3], and there's an associated aa.mp3, and everything is working fine.

And then you go to that field and try to record a different sound

Then you'll either end up with:

[sound:aa.mp3][sound:aa.mp3], and the new sound will play twice
[sound:aa.mp3][sound:ankidroid89798798789.3gp] and you'll get the old sound and the new sound
or, occasionally
[sou[sound:aa.mp3]nd:aa.mp3] and it will be broken, but you can repair it by hand and then you'll get the new sound.

It doesn't look like a device dependent bug to me, so you should be able to reproduce it easily, but if you can't let me know and I'll try to characterize what's going on more exactly!

**Comment by johnlawrenceaspden** [comment]
For what I'm doing, I've always got one sound in an audio field, and what I want to happen is that that sound gets replaced, i.e. the field stays the same and the sound file changes but keeps the same name. 

At the moment, I'm usually getting the file name duplicated, and so every time I re-record something I have to delete the duplicate entry, which is irritating. 

But I see that some times you might want a field with two sound files in it eg hello [sound:hello.mp3] world [sound:world.mp3], and you might want to add a third. 

In which case maybe what happens should depend on where the cursor is? It looks as though it might be trying to do something like that, but the current behaviour is unpredictable and counter-intuitive.

**Comment by Anthropos888** [comment]
Do you use the paper clip icon next to the audio field to record audio? New contents are added right after the curser position when you click on the paper clip icon, that's also the same behavior for image fields.

So before I click on the paper clip icon, I always mark the existing contents of the audio/image field. Only that way the contents will be overwritten by the new file.

I have done that hundreds of times and I agree that this procedure is quite time consuming.

So my suggestion would be to let Ankidroid auto-select the whole filed contents when clicking the paper clip icon (while the cursor is NOT in that field) --> this way the whole field would be overwritten by the new contents.

If the cursor IS in that field, then new contents would just be added after the cursor position, as it is now.

Not sure though if that is the behavior you would like to see?

**Comment by johnlawrenceaspden** [comment]
I do use the paper-clip!

I think that using the recorder should never destroy the things that
are already in the field, and I think that mostly what one wants to do
is either to create a new sound file where there was none before, or
to re-record the file that's already mentioned in the field, not
create a new one with a different name.

However, of course we want to make it possible for people to add new
files, re-record specific files, etc.

I think that the following three cases cover what the field might look like:

some text possibly empty
[sound:aaa.mp3]
[sound:aaa.mp3] some text [sound:bbb.mp3]

So how about:

when the paper clip is pressed:
    if the cursor is not in the field:
       if there are links in the field:
           the program will re-record the first sound link, aaa.mp3,
and not modify the field.
       else (no existing links):
           the program will generate a new name, record a new file of
that name, and add a link to it at the end of the field.
    else (the cursor is in the field):
       if the cursor is in a link:
           the program will re-record the link that the cursor is in.
       else (the cursor is not in a link):
           the program will generate a new name, record a new file of
that name, and add a link at the current cursor position.



Thats seems to cover all the possible use cases, whilst making the
most common operations (adding a sound to an empty field, changing an
existing field with precisely one sound in it) as easy as possible.

I can't say I've thought this through in sufficient detail, but that
sounds like it would be good, and maybe it will give you ideas? I'd be
happy to beta-test!


-----------------------------------------------------

As an extra nice to have, and completely separate from the above, I
think it should be possible to back out of the edit, sometimes you
find that you just can't improve on the existing file.

So perhaps if a file is getting re-recorded, it could be stashed
somewhere, so that if you cancel the edit rather than confirming it,
the note goes back to the previous state and the new recording can be
discarded and the old one restored.

**Comment by johnlawrenceaspden** [comment]
As an extra nice to have, and completely separate from the above, I
think it should be possible to back out of the edit, sometimes you
find that you just can't improve on the existing file.

So perhaps if a file is getting re-recorded, it could be stashed
somewhere, so that if you cancel the edit rather than confirming it,
the note goes back to the previous state and the new recording can be
discarded and the old one restored.

**Comment by dae** [comment]
Please let us know if this is still an issue in the latest release.
