### ISSUE TITLE
Can't see the card when recording audio

### ISSUE THREAD

**Issue by johnlawrenceaspden** [ankidroid/Anki-Android#5428]
An enhancement request rather than a bug, quite often you just want to read out what's on the card, but you can't see the card while recording audio!

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by johnlawrenceaspden** [comment]
AAnkiDroid Version = 2.8.4

**Comment by david-allison-1** [comment]
I'd like to take this one on

**Comment by david-allison-1** [comment]
I feel we could do this with a "save" button in the "Check Pronunciation" box, but this isn't a priority for me
