### ISSUE TITLE
Recording audio tends to break the audio.

### ISSUE THREAD

**Issue by johnlawrenceaspden** [ankidroid/Anki-Android#5429]
Quite often, re-recording multiple audio files seems to disable audio playback on my phone. The only cure is to restart the app.

###### Reproduction Steps

1. Take a deck with a few audio files
2. Re-record several of them (about twenty usually does the trick)

###### Expected Result
 
Audio files still play

###### Actual Result

Audio playback stops working. No audio from that point on.

###### Debug info

AAnkiDroid Version = 2.8.4

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by dae** [comment]
Please let us know if this is still an issue.
