### ISSUE TITLE
2.11 Release (tracking)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5430]
With 2.9 in beta and nearly released #4961 - I wanted to start thinking of 2.10 [edit: 2.10 will focus on internal refactors + stabilization - 2.11 will have new features]

There is already a 2.11 milestone with things bumped from 2.9: https://github.com/ankidroid/Anki-Android/milestone/12

As for new ideas, I can think of these things:

- #5301 - cropping
- #5426 - switching from .3gp as default audio format (should be easy?)
- Moving minSdkVersion to Android 4.4 / API 19 (it appears to be our breakpoint for installs at the moment, evidence attached)
- stretch goal: WYSIWYG editor #1377 
- maybe new user tutorials? #4334 

More than anything I'd like to mop up 2.9 items (once 2.9 is stable and released), keep it focused, and get a faster public release cadence going.

Philosophically, maybe it's just one feature per release even, keeping it very small so features go out more quickly, and whatever pain points are involved in a faster release cycle are examined and targeted for improvement so it's really easy? That's my preference anyway, small frequent change.

Open to any thoughts of course

Here's our installs by API for the older APIs:

![Screenshot from 2019-09-04 15-09-06](https://user-images.githubusercontent.com/782704/64288166-053bf380-cf27-11e9-882b-9aaa56032a38.png)

For reference, in our Compat infrastructure, there are 25 APIs total, and moving from minSdkVersion 15 to 19 would allow 10 to be removed at a cost of 10,000 users total. API20 was for Android Watches only, API21 / Android 5.0 as a minimum would allow a further 6 Compat APIs to be removed, At the cost of 25,000 users.

**Comment by timrae** [comment]
Sounds good

**Comment by YuiTatsumi** [comment]
When will the final version of v2.9 release in Google Play store? the last update date is September 8, 2018

**Comment by mikehardy** [comment]
Just a note that with the PR backlog representing a sufficient amount of instability, 2.10 will be a "fast-follows" on 2.9 focused almost exclusively on getting refactor PRs merged and stabilized (almost done here) and releasing in order to zero the translation straddle again before we strand any users with minimum SDK changes

So I'm changing this to 2.11 as that will be where I open a merge window for new features

**Comment by david-allison-1** [comment]
Personal goals for 2.11 (assuming the number of bugs drops due to 2.9.6 and we're virtually crashless):

* #5635 - Optional feature: Fully randomise the scheduler
* #5192 - General Image Renaming
* Image Occlusion (no Issue Number)
* #5158 - Browser Appearance Edit Screen
* #1377 - WYSIWYG/Markdown (Probably 2.12 given the amount of work, but I'm down to tackle the beast. Let's add it in).
* Let the user define key mappings (kinda #3021), and loads of other related issues

**Comment by mikehardy** [comment]
as volunteers we mostly continue working on what we want, so it's useful to express personal priorities (and encouraged!) but mostly this is happening on Discord right now on the anki server in the ankdroid dev channel. Feel free to hang out there or if that isn't comfortable you can always comment here or open an issue and propose something you want to work on
