### ISSUE TITLE
Dropdown list for Type/Deck in Add/Edit Note jumps back while scrolling

### ISSUE THREAD

**Issue by Heineken** [ankidroid/Anki-Android#5439]
###### Reproduction Steps

1. Add more decks/notes than fit on your screen
2. Tap +, then Add to add new note or edit a note
3. scroll through drop.down list by tapping and holding your finger down

###### Expected Result
while moving one list item moves with my finger

###### Actual Result
the list jumps back 2 or so items while scrolling so that I end up with a different item under my finger that I tapped on, which makes it somehow impossible to scroll to the desired item unless I scroll by swiping + inertia (workaround)
Happens on two different phones with AnkiDroid 2.8.4

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
I think this is a bug in the Android support library which manifests on newer versions of Android. I recommend you to install the latest AnkiDroid 2.9 beta version, it's almost ready for release and the bug should be fixed. Can you please confirm?

**Comment by Heineken** [comment]
Wow, that was a quick reaction.
Yes, I confirm. With the 2.9 scrolling is smooth.
Hopefully the other issue I was going to submit (the GUI language switching randomly) is solved as well.

**Comment by timrae** [comment]
Thank you for the follow up!

**Comment by Heineken** [comment]
Wow, that was a quick reaction.
Yes, I confirm. With the 2.9 scrolling is smooth.
Hopefully the other issue I was going to submit (the GUI language switching randomly) is solved as well.

**Comment by mikehardy** [comment]
GUI language doesn't switch randomly, it mostly doesn't switch as far as I know - unfixed unfortunately - #4729

**Comment by Heineken** [comment]
Ah, I don't need to bother then. Thanks a lot!
