### ISSUE TITLE
Picture display failed

### ISSUE THREAD

**Issue by george-peng** [ankidroid/Anki-Android#5442]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by george-peng** [comment]
I don't know which directory the image is stored in, so I don't know if the download failed or the display failed.

**Comment by mikehardy** [comment]
This isn't specific enough for a bug report, sorry - our best troubleshooting advice for media not working is here: https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid
