### ISSUE TITLE
Figure out why we have to disable Instant Run

### ISSUE THREAD

**Issue by adamwolf** [ankidroid/Anki-Android#5443]
###### Reproduction Steps

1. Try to build with Instant Run turned on

###### Expected Result

A successful build.

###### Actual Result

An error during build!

When we dig into this and get it figured out, we need to remove the instructions on the developer guide of the wiki.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Now "Apply Changes" (which may actually work I haven't tried it?) https://developer.android.com/studio/run#apply-changes

**Comment by adamwolf** [comment]
This can be closed.  Instant Run has been replaced by Apply Changes, which works fine.
