### ISSUE TITLE
Flag cards feature request

### ISSUE THREAD

**Issue by boydkelly** [ankidroid/Anki-Android#5444]
Would be awesome if Ankidroid supports at some point the Flag Cards by colour option found on the desktop version.  Very practical!!!

**Comment by xx299x** [comment]
Yeah,Anki-Android not support the searching of flag.

I also hope to add this feature.

**Comment by mikehardy** [comment]
Actually this is in progress - it is just not connected. @Arthur-Milchior you are about to have some fans when the flag card stuff is all merged :-)

related:
- #5480 data support
- #5494 export support for data
- #5571 user interface for flags

**Comment by Arthur-Milchior** [comment]
Thank you @xx299x for speaking of "searching". Searching in browser/filtered deck through card is something I think I forgot to implement.
Note that I don't even know why the other flag related code are not yet merged in current alpha, while it seems to work

**Comment by Arthur-Milchior** [comment]
https://github.com/ankidroid/Anki-Android/pull/5624
I just pushed a change to allow searching for fla. Now, it remains to hope that those flags related change gets accepted and merged.

**Comment by mikehardy** [comment]
@Arthur-Milchior please, please have patience - this project for the longest time had what appears to be about 0 people interested, and just Tim keeping it alive. But one person with other priorities is not a lot of bandwidth to squeeze through, so it takes time. But everything does happen over time

**Comment by Arthur-Milchior** [comment]
Sorry, I didn't want to seem impatient. I do understand it's a lot of works. I was mostly trying to state that I did what I can to satisfy this precise request, and can't do no more.

**Comment by mikehardy** [comment]
I would have understood impatience even ;-). But yes - you have done some fantastic work that is still sidelined and there is not more that you can do I don't think - to your credit. Sounds like Tim is traveling the next couple weeks (relocation from one country to another) so patience will definitely be a virtue. Out of our control 🤷‍♂
