### ISSUE TITLE
Unable to import: This isn't a valid apkg file

### ISSUE THREAD

**Issue by PeterPecker** [ankidroid/Anki-Android#5445]
###### Reproduction Steps

1. Deck works fine on my laptop, deck is 2.3GB
2. Get the same error despite installing and reinstalling app
3. 

###### Expected Result
It works

###### Actual Result
It doesn't work

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
2.3GB is too big for an import like that I believe. You would need to use AnkiWeb to sync, but with a deck that big I'm sure it will take a while unless you set up a local sync server

**Comment by mikehardy** [comment]
would be nice to know your versions etc as well, just in case, plus the filename, might be that with desktop you exported a '.colpkg' file (the whole collection) and AnkiDroid doesn't support that yet - you'd need to rename as .apkg. You might also try exporting and importing deck by deck to keep the size down - mobile devices have limitations compared to desktop unfortunately

**Comment by PeterPecker** [comment]
Ty, I split up the deck to reduce the overall size and got it to work
