### ISSUE TITLE
Center Background image

### ISSUE THREAD

**Issue by TowelSniffer** [ankidroid/Anki-Android#5446]
1. I have a deck with a note type called Image containing different image for every card. On the desktop I have the image set as a background with the following code:

---------------------
card
---------------------
```
<div id="img">{{Image}}</div>
<script>
var a = document.getElementById('img');
var imgsrc = a.innerHTML.replace(/.*<img src\=./, "").replace(/.>.*/, "");
a.innerHTML = '<style>.card { background-image: url("' + imgsrc + '")}</style>';
</script>
```

---------------------
styling
---------------------
```
.card {
  background-repeat: no-repeat;
  background-attachment: fixed;
  background-position: center;
}
```

on the desktop, the image is displayed in the center of the card however on ankidroid, it is displayed at the top with half of the image missing. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Someone else might have more info, but have you tried direct inspection of card results? It's our best way to unblock users that are actively doing HTML/CSS/Javascript https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by TowelSniffer** [comment]
Thanks for the tip, with this I was able to find a semi solution by specifying pixel values, however, this is not ideal as the images sizes vary per card. for whatever reason, the vertical center does not seem to work on ankidroid for background images. background-position: center center; and background-position: 50%; also don't work

**Comment by mikehardy** [comment]
that is odd - you can get the whole card.html output (and you'll have the styles yourself) - I'd be shocked if there was a difference in render between working on that as a typical webpage vs how it renders in AnkiDroid since we're using the Chrome WebView under the cover, but maybe there is a Chrome version difference or something else going on?

**Comment by snoyes** [comment]
This appears to be a [ten year old bug](https://issuetracker.google.com/issues/36908439).

A workaround is to add this to your Styling:
```
html {
  min-height: 100%;
}
```

**Comment by TowelSniffer** [comment]
Hi,

Thanks, snoyes That solves the issue.
