### ISSUE TITLE
Card browser searching only in the last active deck

### ISSUE THREAD

**Issue by mtrevix** [ankidroid/Anki-Android#5452]
###### Reproduction Steps

1. open AnkiDroid, tap on any deck, and then get back to the main deck list
2. tap on the three lines (top left), and select the Card browser

###### Expected Result

Since we are not inside an active deck but on the list of decks, I would expect the Card browser to browse within all decks (and only search within the selected decks when I have opened such a deck). This was the behaviour in previous versions and I think it was the right thing.

###### Actual Result

In the version 2.9beta12 the Card browser by default searched only within the last visited deck, and to search all the decks additional taps are needed to select the list (top centre), move to "All decks", select it, and then search. This is especially cumbersome if a user has many decks and tends to browse often between decks, as this action might be needed every time.

###### Debug info

AnkiDroid Version = 2.9beta12
Android Version = 5.1.1
ACRA UUID = 0b80c544-4876-410f-b509-0fd760941370

###### Research

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
This was the source of quite some discussion 

https://github.com/ankidroid/Anki-Android/pull/5094

**Comment by timrae** [comment]
There appears to be a bug here... The last deck used in the browser is supposed to be remembered. It seems that it's remembering it if you press the back key when exiting the browser, but not if you choose "decks" from the navigation drawer.
