### ISSUE TITLE
Suggestion to reinclude former dark night theme (perhaps calling it "Slate", or similar)

### ISSUE THREAD

**Issue by mtrevix** [ankidroid/Anki-Android#5453]
This is not actually a bug, but a suggestion to add a third night theme that is equivalent to what was previously the dark night theme, and that would lie in between the current dark night theme and the current black night theme (in version 2.9beta12). It could be called "slate" or something similar (shaded, intermediate, dark grey, ash), and shows a better contrast than the current dark theme (useful in many situations) without going completely black and without needing to use the battery-demanding day themes.

This suggestion is not about recommending to replace the current dark night theme with the former one, but about including both.

###### Reproduction Steps

1. Open AnkiDroid and tap on the three lines (top right)
2. Select the night mode
3. Make sure the dark version of the night mode is on (Preferences > Appearance > Night mode > Dark)

###### Expected Result

A dark night theme that is not as dark as the black theme, but still shows good contrast, which is useful for situations such as when we are in a situation where there is a lot of light (i.e. the dark theme in previous versions), while being less battery-demanding than the day theme.

[Dark night theme in AnkiDroid 2.8.5beta1](https://user-images.githubusercontent.com/5268991/66311487-827fcd00-e906-11e9-87e1-ce388940ce09.png)

###### Actual Result

A dark night theme which shows a lighter grey scale, making it difficult to read in environments with lots of light. While this can be ideal for certain users, the previous dark night theme configuration was optimal for some situations.

[Dark night theme in AnkiDroid 2.9beta12](https://user-images.githubusercontent.com/5268991/66311562-a93e0380-e906-11e9-9f6c-e9b0d95a8e41.png) (Please, don't mind font size or other configurations, just the colour difference)

###### Debug info

AnkiDroid Version = 2.9beta12
Android Version = 5.1.1
ACRA UUID = 0b80c544-4876-410f-b509-0fd760941370

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
To even consider it I'd need to know what exact elements (maybe a marked up screenshot) you'd want different, and I'd need to confirm you couldn't change them with CSS (some stuff is CSS-overridable, some isn't). The previous dark mode is only different from current in that I made the webview conform, but I left in that it may be overridden by user CSS, so it may be you have the power to change this now...

**Comment by mikehardy** [comment]
https://github.com/ankidroid/Anki-Android/pull/5128

**Comment by david-allison-1** [comment]
Bot was a bit too soon to auto-close
