### ISSUE TITLE
When generating new cards, their due value is not the same as the one of sibling cards

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5456]
###### Reproduction Steps

1. create a note `N` of type "Basic (and reversed card)", by filling only the back. It'll thus create card two only. 
2. Create plenty of other note. We don't care about them. There cards must all be in the same deck.
3. Edit `N` by adding a value in the front field. 
4. Review the deck. 

###### Expected Result
I expect the result to be the same than in anki. 

In anki, you'll see card 1 of note `N`.

Technically, I expect that both cards have the same due value. This is ensured in anki's code by https://github.com/dae/anki/blob/master/anki/collection.py#L378 and also lines 391 and 406.

###### Actual Result
I'll see card 2 of note `N`. Then I'll see all of the other notes. And only after that, we'll see card 1 of note `N`. Technically, the due value of card 1 of note `N` will be greater than all due value of the collection. 

This breaks the assumptions that anki manual states (*), that all of the cards of a note are seen in the order of their template. Worse, it's still broken when synchronizing back with anki. Indeed, the due values remains the same. In order to correct it, I've got to manually reset the due value (or to state that the decks are in random order, and then put it back in normal order)

(*) I'm referring to "The cards of a given note are shown in the order their card types appear in, so that siblings are introduced consistently"

##### Why it is a problem for me.
The remaining tries to explain why this is actually a huge problem for me. It does not add any more informations related to the bug itself.

There are things I can practice on tablet and not on computer. (Piano scales. I can have the tablet on the piano, not the computer). I've got a field called «practice hands separately»; when it is filled, it creates card for left hands and for right hands.  Furthermore, cards 1 and 2 corresponds to left and right hands respectivly. While cards 3 corresponds to both hands. (I'm simplifying my real note type)
By default, it's not filled, and I only fill it if I realize that it's too hard right now for me to directly practice both hands separately. For example, I don't fill it for C Major. But the first time Anki will show me the scale of G flat major, I'm pretty sure I'll set this field to true. 
When I created this card type, I expected that I'll see card 1 first, i.e. left hand; then right hand, then both hands. 
Instead, ankidroid still show me both hands first, which totally defeat the purpose of this note type. 

###### Debug info
AnkiDroid Version = 2.9beta12

Android Version = 9

ACRA UUID = 532d0d37-31de-4857-8976-63bca5b10ed8

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
@mikehardy Could we add this to a release? It's in master as-of https://github.com/ankidroid/Anki-Android/pull/5540, but not in 2.9.6

**Comment by Arthur-Milchior** [comment]
@david-allison-1 thanks for checking this. I never realized that some code merged long ago where not in any release

**Comment by mikehardy** [comment]
Yeah - I was picking crash fixes only as much as possible after the 2.9-release branch was cut so this did not get picked


I still think we can get 2.10 out stable pretty quickly, like maybe just a couple weeks and I'd prefer to focus on that with the time I've got available vs doing a new 2.9 release cycle

If I thought it was going to more than 1-2 weeks I'd pick it and do 2.9.7 but I think 2.10.0 will be quick enough it's okay. I'll revisit that and do a 2.9.7 if 2.10 gets hung up on anything

**Comment by mikehardy** [comment]
Fixed by #5540
