### ISSUE TITLE
Missing option to select all cards if none is selected

### ISSUE THREAD

**Issue by rgamici** [ankidroid/Anki-Android#5464]
After you select a card in the Card Browser, the option to select all is available, but it is not if a card is not selected.

I've checked the discussion about the multiselect issue (https://github.com/ankidroid/Anki-Android/issues/2339), but there was not mention about it.
It should be an easy fix and more intuitive for the users.

I'm using the 2.9Beta12 version.

**Comment by mikehardy** [comment]
interesting - yeah, I can see what you mean from a UI/UX perspective. To be 100% clear - the options menu simply doesn't have select all as an option until you have long-pressed (and thus switched it to multi-select mode) in the card browser?

**Comment by rgamici** [comment]
>  the options menu simply doesn't have select all as an option until you have long-pressed (and thus switched it to multi-select mode) in the card browser?

Yes.

**Comment by david-allison-1** [comment]
Current State:

**Nothing Selected**

* No Options :x:

**0 Selected (only possible via select none)**

* Select All ✔️ 

**1 Selected**

* Select All (should also have select none)  :heavy_exclamation_mark: 

**All Selected (automatic)**

* Select None ✔️ 

**All Selected (manual)**

* Select None ✔️

**Comment by david-allison-1** [comment]
I'd like to take this on, but I have a question:

We currently have a state: MultiSelect with 0 selected. This seems to be a bug, you can only achieve it via "Select None", and I don't think it should occur, as none of the menu items work.

Am I OK to make this an invalid state in the browser (going back to "not in multiselect mode")?

**Comment by mikehardy** [comment]
Hmm. it's either that or a bunch of checks for selections and "You must select one or more cards to continue" error dialogs. The existing behavior of long-pressing one to get to multi-selection mode (with one selected) then de-selecting that one popping you back to single-selection mode has sort of made the decision though I think. "select none" should go back to single-selection mode - works for me
