### ISSUE TITLE
Editing notes on mobile adds lots of empty lines.

### ISSUE THREAD

**Issue by byteFurnace** [ankidroid/Anki-Android#5466]
###### Reproduction Steps

1. Create s field that contains a html table
2. Edit something in the note (which field doesn't matter) on the mobile app (In my case android)

###### Expected Result
Only what was edited changes. Tables stays the same.

###### Actual Result
Before the html table a bunch of <br> tags got inserted. These tags can only be removed on with the desktop Version.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi @byteFurnace - would you say this issue captures your problem? https://github.com/ankidroid/Anki-Android/issues/3304

**Comment by byteFurnace** [comment]
Yes @mikehardy, seems to be the same.

**Comment by mikehardy** [comment]
Okay - please head over there and subscribe, I'm going to close this is as a duplicate. There are a few people working on the codebase now vs just 1 or 2 for the last couple years so hopefully it will get some attention with the added horsepower
