### ISSUE TITLE
TTS output failed without error message (fix described inside)

### ISSUE THREAD

**Issue by stephankn** [ankidroid/Anki-Android#5468]
**POSSIBLE WORKAROUNDS**:

- delete the offline TTS files and re-install them
- delete the updates to the google TTS engine

--

###### Reproduction Steps

1. have cards with TTS synthesis configured

###### Expected Result

expected to hear TTS output of note

###### Actual Result

nothing happes, just silence without error message

###### Debug info

System is Android 9, Security Patch level August 2019.
I connected ADB and got the following output on logcat while the problem happened:

```
10-14 20:57:38.252 31066 13975 W TTS.Dispatcher: No network voice found, will fall back to local immediately
10-14 20:57:38.252 31066 13975 I TTS.ControllerWrapper: Initializing de-de-x-nfh-lstm-embedded from disk
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper: Unable to open project file.
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper: java.io.FileNotFoundException: /data/user_de/0/com.google.android.tts/files/superpacks/de-de/de-de-x-nfh-r9/pipeline (No such file or directory)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.open0(Native Method)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.open(FileInputStream.java:231)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.<init>(FileInputStream.java:165)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.<init>(FileInputStream.java:112)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at bxs.a(PG:162)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at bxs.b(PG:174)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at bxs.a(PG:200)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at bxt.b(PG:151)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at bxt.a(PG:7)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at com.google.android.tts.service.GoogleTTSService.onLoadVoice(PG:351)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$LoadVoiceItem.playImpl(TextToSpeechService.java:1250)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$SpeechItem.play(TextToSpeechService.java:819)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$SynthHandler$1.run(TextToSpeechService.java:583)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.os.Handler.handleCallback(Handler.java:873)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.os.Looper.loop(Looper.java:192)
10-14 20:57:38.253 31066 13975 E TTS.ControllerWrapper:         at android.os.HandlerThread.run(HandlerThread.java:65)
10-14 20:57:38.253 31066 13975 E TTS.LocalSynthesizer: Failed initializing controller with voice de-de-x-nfh-lstm-embedded
10-14 20:57:38.254 14684 18841 D PackageManagerServiceUtilsZTE: ZSW isallow3rdAppSendProtectdBroadcast packageName com.google.android.tts
10-14 20:57:38.279 31066 13975 I TTS.GoogleTTSServiceImp: Synthesis request for locale deu-DEU and name de-DE-language
10-14 20:57:38.280 31066 13975 I TTS.GoogleTTSServiceImp: TTS dispatch: de-de-x-nfh-lstm-embedded
10-14 20:57:38.280 31066 13975 I TTS.ControllerWrapper: Initializing de-de-x-nfh-lstm-embedded from disk
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper: Unable to open project file.
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper: java.io.FileNotFoundException: /data/user_de/0/com.google.android.tts/files/superpacks/de-de/de-de-x-nfh-r9/pipeline (No such file or directory)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.open0(Native Method)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.open(FileInputStream.java:231)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.<init>(FileInputStream.java:165)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at java.io.FileInputStream.<init>(FileInputStream.java:112)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at bxs.a(PG:162)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at bxs.b(PG:174)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at bxs.a(PG:200)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at bxt.b(PG:151)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at bxt.a(PG:10)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at com.google.android.tts.service.GoogleTTSService.onSynthesizeText(PG:212)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$SynthesisSpeechItem.playImpl(TextToSpeechService.java:1033)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$SpeechItem.play(TextToSpeechService.java:819)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.speech.tts.TextToSpeechService$SynthHandler$1.run(TextToSpeechService.java:583)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.os.Handler.handleCallback(Handler.java:873)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.os.Handler.dispatchMessage(Handler.java:99)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.os.Looper.loop(Looper.java:192)
10-14 20:57:38.281 31066 13975 E TTS.ControllerWrapper:         at android.os.HandlerThread.run(HandlerThread.java:65)
10-14 20:57:38.281 31066 13975 E TTS.LocalSynthesizer: Failed initializing controller with voice de-de-x-nfh-lstm-embedded
10-14 20:57:38.281 31066 13975 E TTS.LocalSynthesizer: Synthesizer failed to initialize: de-de-x-nfh-lstm-embedded
10-14 20:57:38.282 31066 13975 E TTS.GoogleTTSServiceImp: Synthesis failure with error status code: -4
10-14 20:57:38.282 31066 13975 W PlaybackSynthesisRequest: done() was called before start() call
```

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

I also found that on `Settings / System / Languages & Input / text-to-speech output / options / Install voice data` the playback for the installed language fails. This problem happened on different phones.
**Deleting the offline speech and re-installing fixed the issue.**

This problem report is here to document the problem in case others are facing it again. It would also have helped if Anki could have produced some error message telling me to check for a problem inside Android. Would the error code -4 mentioned in the log have been available to Anki?

I am fine if the developers close this without further action, as the purpose of documenting the problem is not related to Anki is now documented including a fix. I unfortunately only noticed it with Anki as I don't use TTS elsewhere, 

You could as well treat it as a request to add more error handling around the TTS engine code.

**Comment by mikehardy** [comment]
This may strike other people, so yes, good information especially the logcat with the actual stack trace. Unfortunately I don't see any Ankidroid frames in that trace, it looks like it's on some separate thread so I'm not sure if we'd ever get a chance in the code to act differently. I suppose there should be some recognition if the TTS engine is ready though, and perhaps we're not inspecting that and/or messaging to the user

**Comment by stephankn** [comment]
I had also noticed. This was quickly leading to the action of checking the Android setup.

As it was broken on the phone with nearly daily Anki usage and also on another phone when I checked there something was probably updated the last few days.

In the init call seems to be some error handling. I didn't see any Toast at this point. So probably no error returned there.

https://github.com/ankidroid/Anki-Android/blob/3d91bc0a1117c853e5904ab888150db9995743ec/AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java#L268

My best guess is that playback is triggered here. What is the expected error handling at this point?

https://github.com/ankidroid/Anki-Android/blob/3d91bc0a1117c853e5904ab888150db9995743ec/AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java#L65

**Comment by mikehardy** [comment]
Interesting - I share your take on line 268 being likely fine. It seemed like the error handling and "do we have an available location" handling were adequate there? Could be wrong, but it seemed fine.

Chasing line 65 into our compatibility infrastructure, there was a related change here recently as we moved to handle the TTS APIs moving in the Android system so that we could work on the old APIs or the new ones.


You are on API28 (Android 9) and the APIs were introduced in API21, so you were getting this implementation:

https://github.com/ankidroid/Anki-Android/blob/3d91bc0a11/AnkiDroid/src/main/java/com/ichi2/compat/CompatV21.java#L71

The related work was here https://github.com/ankidroid/Anki-Android/pull/5372

I wonder if something in that PR didn't work, though I reviewed it originally, and on re-review now still nothing jumps out at me :thinking:

**Comment by stephankn** [comment]
I was on 2.9Beta5, as 2.9 was not yet released. I don't think that the compat layer change is related.

Documentation recommends to set a listener for errors:
https://developer.android.com/reference/android/speech/tts/TextToSpeech.html#speak(java.lang.CharSequence,%20int,%20android.os.Bundle,%20java.lang.String)

The code here sets this listener, but does ignore all errors:
https://github.com/ankidroid/Anki-Android/blob/90977bc9e27d760db6fd88aa5f60dbd211dbc3df/AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java#L296

I assume this was the location which got called once TTS failed for met, but Anki ignored the error.

**Comment by timrae** [comment]
Pull request is welcome ;)

**Comment by stephankn** [comment]
What kind of error handling would be considered appropriate? Simply a Toast with the error message? Or a full pop-up dialog with an OK button?

**Comment by timrae** [comment]
A toast would be best I think

**Comment by mikehardy** [comment]
Good find - it will be interesting to see if it actually gets called - this is catching out a lot of users (we're getting maybe 2 a day complaining? which hints at many more that just give up) so some sort of UI feedback will be great

**Comment by mikehardy** [comment]
whatever feedback we give it should be searchable in our FAQ / issues list / manual so users can self-help with one hop I hope

**Comment by stephankn** [comment]
I can confirm that the `onError()` is called.

I can print there logging:

    Timber.v("Andoid TTS failed with error");

Unfortunately I am missing to get a valid context inside this listener. What would be a valid application context? `context` or `mReviewer.get()` is not.

I am also a bit uncertain how to handle the API change on 21. onError(String) is called and not onError(String, int). The later one would have probably given a hint regarding the error, I did not see any member/method of mTts to get the error code.

**Comment by timrae** [comment]
Probably `mReviewer.get().getApplicationContext()`, or `AnkiDroidApp.getInstance().getApplicationContext()`
