### ISSUE TITLE
A more customizable full screen mode, add better support for devices with notch or no hardware buttons

### ISSUE THREAD

**Issue by Xyde** [ankidroid/Anki-Android#5469]
The current full screen mode hides everything but the viewport. Including the system status bar and the software navigation buttons. It was not an issue on my old phone (OPO) since it had hardware buttons and no notch. But ever since switching to a more recent generation phone with a notch and lack of physical buttons. Ankidroid became kind of cumbersome to use.

Furthermore, the current full screen mode doesn't even really full screen properly the status bar area but leave a blank area. Better just give that space its initial purpose again not like there's less screen estate.

Suggestion: have 4 different full screen modes

1. Viewport only (what we currently have)

2. Viewport with visible system status bar (important for devices with notches)

3. Viewport with constant software buttons (for those who don't use gestures and hardware buttons)

4. Combination of 2 and 3.

**Comment by mikehardy** [comment]
...and to think the biggest complaint we get on the Play Store reviews is that the options are ridiculous, too numerous, and too hard to configure :-)

I'm not saying you're wrong, but the UI/UX impact of 4 different full screens is a lot to contemplate.

**Comment by tjbrn** [comment]
Related #5389
