### ISSUE TITLE
cannot add images to the cards from the ankidroid logo change

### ISSUE THREAD

**Issue by isa79es** [ankidroid/Anki-Android#5500]
###### Reproduction Steps
since the ankidroid logo was updated, images cannot be added to the cards. It shows an error as a failed edition.

###### Debug info
AnkiDroid Version = 2.9

Android Version = 9

ACRA UUID = 27b0180e-1ecf-4d46-88fe-639027f52aee

**Comment by mikehardy** [comment]
Hi there! Sorry you're having trouble, but thanks for providing all the info from the getting help steps - usually that UUID helps us index into our crash reporting system and find a stack trace that illuminates things, but unfortunately this doesn't look like a full crash so there was no information there.

Could you list out the exact steps you take that reproduce the error, starting with opening the app? Then we can try to reproduce and see what's causing the issue

Thanks!

**Comment by isa79es** [comment]
Hello! Thank you very much for your speed.
The steps are:

1. I open the application from Android.
 2. I go to the card explorer and create a new card.
 3. In the back section, when trying to attach an image, the blank screen
is displayed and says "edición fallida" ( spanish version).

This error also occurs when I try to edit an existing card (from the
browser or from the deck) and add a new image.

Thank you very much for your help.

Isabel

**Comment by timrae** [comment]
Try uninstall > reboot > reinstall AnkiDroid

**Comment by mikehardy** [comment]
The 2.9.x series has many many changes / fixes related to adding media to cards, I believe this should be closed but I will be happy to reopen if this still happens, just let us know
