### ISSUE TITLE
Anki 2.9 feature from changelog: "  Add API to open Reviewer on specific decks from other apps" what is this ?

### ISSUE THREAD

**Issue by lucwastiaux** [ankidroid/Anki-Android#5520]
Congrats on getting the 2.9 release out the door! I was very curious about this:
"Add API to open Reviewer on specific decks from other apps" (appears in the 2.9 changelog: https://docs.ankidroid.org/changelog.html)
I tried to look for a corresponding code change but couldn't find one. Can someone point me in the right direction ?
Thank you.

**Comment by timrae** [comment]
https://github.com/ankidroid/Anki-Android/pull/4438

**Comment by timrae** [comment]
If you could document the intent in the API wiki that would be appreciated

**Comment by darkzbaron** [comment]
Hi there, still interested in the documentation for using this
