### ISSUE TITLE
Latest update plays audio file twice

### ISSUE THREAD

**Issue by jlitven** [ankidroid/Anki-Android#5530]
After updating to the latest version my question plays twice on the question side and once on the answer side.

###### Reproduction Steps

1. Create a two-sided card with audio on both sides
2.  Play front
3.  Play back

###### Expected Result
One playback of the recording

###### Actual Result
Repeated playback on question side and single playback on answer side.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Interesting - thanks for the report! We have a few 2.9 crash bugs in the audio attach area so I will cross-link them as this should be easy to test while in the area anyway #5509 #5521
