### ISSUE TITLE
Cloze deletion menu item does not appear in landscape

### ISSUE THREAD

**Issue by snoyes** [ankidroid/Anki-Android#5533]
###### Reproduction Steps
Orient device in landscape. Long press on a text field to bring up the selection/insertion menu.

###### Expected Result
In portrait orientation, the "Cloze deletion" option appears in the menu.
![Screenshot_20191016-094558_AnkiDroid](https://user-images.githubusercontent.com/4838517/66930746-a6c06580-effa-11e9-85ff-d4b42455edad.jpg)

###### Actual Result
In landscape orientation (which switches to the "field at a time" style entry - don't know what that's called), the "Cloze deletion" option does not appear.
![Screenshot_20191016-094616_AnkiDroid](https://user-images.githubusercontent.com/4838517/66930761-af18a080-effa-11e9-985c-0490b7d959ce.jpg)

###### Debug info
AnkiDroid Version = 2.9

Android Version = 9

ACRA UUID = daf4537c-75a7-43e4-b2f3-1109612cc03d

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by snoyes** [comment]
This seems to be keyboard dependent. Gboard, Samsung Keyboard, and Samsung voice input all fail to include Cloze deletion, but Google Handwriting Input and Google voice typing show it.
![Screenshot_20191016-104857_AnkiDroid](https://user-images.githubusercontent.com/4838517/66936250-002c9280-f003-11e9-905f-db46550d8f2b.jpg)

**Comment by snoyes** [comment]
I _think_ that what's missing here is calling https://github.com/ankidroid/Anki-Android/blob/c71c2fe04dabaff09346202ce8aaeadd745785f4/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1716 in AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicTextFieldController.java

But I don't have a build environment for this, so I'm not prepared to fix it myself.

**Comment by mikehardy** [comment]
Fair enough, and your pinpoint notes here should be enough to patch it up - we have a pile of crash bugs affecting a lot of users on 2.9 right now so this may sit for a bit but packaged up as it is, hopefully it gets done sooner rather than later. Thanks!

**Comment by david-allison-1** [comment]
Cause: We use an `ActionListener` on each field to display the menu.

This is implemented via `setNote` -> `populateEditFields` which is called `onCollectionLoaded`

But, the `TextView` that appears on rotation is an **Extracted Text UI** defined by the IME.

It looks like we can modify it via: https://stackoverflow.com/questions/50997709/how-to-modify-the-extractededittext-for-a-custom-keyboard-in-android.

**Comment by david-allison-1** [comment]
For the moment, would a setting in the advanced preferences to disable the "Extracted Text UI" be acceptable (assuming it's named well).

**Comment by david-allison-1** [comment]
`outAttrs.imeOptions |= EditorInfo.IME_FLAG_NO_EXTRACT_UI;` doesn't work for me in GBoard. I'll leave it in a branch and see if anyone else has any ideas.

**Comment by mikehardy** [comment]
This is released as 2.10alpha66 as soon as google is done processing it
