### ISSUE TITLE
A little cosmetic problem 

### ISSUE THREAD

**Issue by Daam10** [ankidroid/Anki-Android#5539]
if I hold my finger on the ellipsis and slide my finger down, the form of functions pops up. where my finger is, an area stands out, but not completely, as it should be.
This is an extremely minor cosmetic bug. but it’s my business to inform.
![Screenshot_2019-10-18-20-13-43-550_com ichi2 anki](https://user-images.githubusercontent.com/50209149/67107005-109c6300-f1e5-11e9-8f45-3cdac6fbf295.png)

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Interesting this looks like some sort of incomplete theming on our part.

May I ask for some more information?

What version are you on? (ex 2.9.1)
What theme are you set to? (looks to me like "Night mode" / normal - not "dark" which is like night mode but not black - your theme looks like the fully black theme)

Thanks!
