### ISSUE TITLE
Feature request: display interval in card browser

### ISSUE THREAD

**Issue by thoral** [ankidroid/Anki-Android#5542]
Displaying the interval of cards in the browser would be very useful in conjunction with the new function 'ability to reposition cards'.

**Comment by mikehardy** [comment]
Interesting - I don't think there is any sorting ability in the browser, or any ability to display anything else there and it's very tight space on that screen.

**Comment by timrae** [comment]
I think this feature already exists; from the menu go to "change display
order" and choose interval.

**Comment by timrae** [comment]
True that the interval is not displayed though. It might not be difficult to add it if someone wants to make a pull request.

**Comment by thoral** [comment]
Of course I meant 'displaying' the interval instead of 'sorting'. Thanks for changiging the subject.

Displaying the front of the card is enough because it would be the same method as displaying e. g. the amount of reviews. Mobile device screens are small, and of course this would be sufficient.

Offering the ability to reposition cards makes IMO only sense if I am able to lookup the current interval value. For now I can only estimate the current value when the card is repeated ('Good' value : 2).

**Comment by Anthropos888** [comment]
Good to see that I'm not the only one who really would like to see the interval in the card browser ;-)
https://github.com/ankidroid/Anki-Android/issues/5168

**Comment by timrae** [comment]
Released in latest 2.10 Alpha

**Comment by thoral** [comment]
Thanks for adding it in the next release. 

I hope that you don't mind if I have still an additional request in the same context and use this thread: When using the function "reposition cards' during repetition (or throughout the browser)  it would be handy to display the current display interval in the input dialogue, too. 
E.g.: current interval: xy, new interval: ab.
![Screenshot_20191101-131218_AnkiDroid](https://user-images.githubusercontent.com/8202866/68035368-c2e32880-fcc3-11e9-94ed-4fbf91e7a120.jpg)

**Comment by mikehardy** [comment]
@thoral if you don't have that as a feature request separately already, I'd definitely ask for that separately. Doesn't seem unreasonable on the face of it, but it will be lost here I think. Have you tested the alphas to see if interval is working? It should be up and working now

**Comment by thoral** [comment]
Ok, I'll copy it in an new thread, I knew already... ;-)
Concerning alpha testing: no, I did not test anything. I am just using stable releases.
