### ISSUE TITLE
Scaling bug in card browser (110%)

### ISSUE THREAD

**Issue by thoral** [ankidroid/Anki-Android#5544]
I noticed since years that it is not possible to enhance the font scaling in the card browser just a little bit above 100%. 

Steps to reproduce: Scale card browser to 110% (instead of default 100%). 
Result: The font size is much to large.
Ankidroid versions: 2.9.1 and before

Workaround: use a much smaller scaling, e. g. 30 or 40% to be able to scale in minor steps and to achieve the desired font scaling. Of course this workaround is not obvious to new users who will try 110% first.

BTW On my mobile phone 100% font scaling seems to correspond to a scaling of 35% (which cannot be set).

Examples:
100%: 
![100percent](https://user-images.githubusercontent.com/8202866/67141944-e4272c00-f262-11e9-95b1-33087949c0d2.jpg)

110%: 
![110percent](https://user-images.githubusercontent.com/8202866/67141950-ebe6d080-f262-11e9-8544-fa46e06227f2.jpg)

**Comment by AdrienLemaire** [comment]
Thanks @thoral for the report and @jgscherber for the fix. Spent a while going over my style sheet rules and couldn't find out why it was so overly scaled.

**Comment by thoral** [comment]
Than you for fixing this bug in AnkiDroid 2.10!
