### ISSUE TITLE
Chromebook Anki app, enter key does not work in card template editor (V 2.9.1)

### ISSUE THREAD

**Issue by EwNeptune** [ankidroid/Anki-Android#5546]
###### Reproduction Steps

1. Open Anki chromebook app
2. Go to card template editor
3. Press enter on keyboard (works on virtual keyboard if on touchscreen mode)

###### Expected Result

A row empties out so you can type in more information

###### Actual Result

No row empties out

![Screenshot 2019-10-19 at 8 45 24  #AM](https://user-images.githubusercontent.com/26100314/67147769-d5357f00-f24c-11e9-952e-2dc504e46672.png)

**Comment by mikehardy** [comment]
@EwNeptune this actually reminds me, now that AnkiDroid 2.9.x is released, I need to do a new release for the Chrome store - #3420 #4924 #4546 #5233 may all be resolved

Can you confirm how you installed the app? If you are running 2.9.1 are you using the regular Play Store to install it? I am unsure what the state of using Android native apps on Chromebooks is these days - if I need to publish new releases on the Chrome store, or if everyone will just use the Play Store now

**Comment by EwNeptune** [comment]
> @EwNeptune this actually reminds me, now that AnkiDroid 2.9.x is released, I need to do a new release for the Chrome store - #3420 #4924 #4546 #5233 may all be resolved
> 
> Can you confirm how you installed the app? If you are running 2.9.1 are you using the regular Play Store to install it? I am unsure what the state of using Android native apps on Chromebooks is these days - if I need to publish new releases on the Chrome store, or if everyone will just use the Play Store now

Hello! I used the Play Store to install Ankidroid. I checked the Chrome store and I did not install Ankidroid on it. I am not so sure about the latter however. Thank you for the reply.

**Comment by david-allison-1** [comment]
Bot was hasty - let's keep this open - bug to fix

**Comment by dae** [comment]
Please let us know if it's still an issue.
