### ISSUE TITLE
Feature request: copy card function in browser view

### ISSUE THREAD

**Issue by thoral** [ankidroid/Anki-Android#5547]
This is just  a request to achieve a little more convenience when duplicating cards.

I often have to duplicate cards because in foreign languages exist a lot of synonyms. Normally I am learning a new vocable, and some times later I discover that that same meaning could be expressed by another vocable. In this case I enter the editor of the first card, choose the duplicate function, modify a little bit the card front of the new card (e. g. with an appropriate hint) and enter the second vocable on the back. Then I have to close the editor of the duplicate, and afterwards the editor of the first vocable which was not modified at all. 

My proposal is to offer a duplicate function directly in the card browser. In this way it would not be necessary to enter the editor first. Using this function should directly open the editor with the new duplicate.

**Comment by mikehardy** [comment]
Is this something Anki desktop does?

**Comment by snoyes** [comment]
> Is this something Anki desktop does?

The desktop version doesn't have a copy card option at all.

**Comment by mikehardy** [comment]
Our default policy is to track upstream as best we can, and with limited developer time we struggle with that as the feature set is already pretty large, so I'm going to close this since Anki Desktop doesn't do it
