### ISSUE TITLE
BUG, when editing a single card, the reschedule option does not show up.

### ISSUE THREAD

**Issue by jarmanso7** [ankidroid/Anki-Android#5551]
###### Reproduction Steps

1. Open any single card for editing
2. Click on the three vertical dots at the top right corner
3. They show up the options "Add note" and "Copy card", but **unlike before**, there is no option to reschedule the card.

###### Expected Result

In the step 3, a "Reschedule card" option shows up in the menu.

###### Actual Result

**unlike before**, there is no option to reschedule the card.

###### Debug info

N/A

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
It was removed from the note editor because it's available from both the reviewer and the card browser now.
