### ISSUE TITLE
built-in MathJax causes repeated text on (complicated) Cloze cards

### ISSUE THREAD

**Issue by karlorg** [ankidroid/Anki-Android#5552]
###### Reproduction Steps

1. create a Cloze card with the following content (preferably in a deck with no scheduled cards so you can open this card quickly):
`the \((\){{c1::\(x\)}}\()\) is {{c2::\(y\)}} but not {{c1::\(z\)}} or {{c2::\(\lambda\)}}`
2. open the card for learning (for me the issue shows on card 1)

note: combining the first cloze deletion into a single MathJax segment with the surrounding parens, like this: `\(({{c1::x}})\)` still produces this issue; without the surrounding parens it goes away though, and similarly the repeated appearances of clozes c1 and c2 seem necessary for this to happen

###### Expected Result

Card rendered like

the ([...]) is y but not [...] or {lambda}

###### Actual Result

after end of expected text (lambda), previous text repeats starting from "is y"

![Screenshot_20191021-134333](https://user-images.githubusercontent.com/3965887/67209638-9e5b9680-f40f-11e9-8c56-dfc4ed31829f.png)

after viewing answer:

![Screenshot_20191021-134340](https://user-images.githubusercontent.com/3965887/67209660-a9162b80-f40f-11e9-87df-bdbe5adfb33f.png)

###### Debug info
AnkiDroid Version = 2.9.1

Android Version = 7.1.1

ACRA UUID = 952a7898-badf-4a78-a959-a786b80319ba

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
Can you please try with the latest Alpha version?

**Comment by karlorg** [comment]
same issue on [](https://github.com/ankidroid/Anki-Android/releases/tag/v2.9.1)

is that the latest?

**Comment by timrae** [comment]
Ah that's too bad

**Comment by mikehardy** [comment]
@karlorg thanks for logging this here from my mailing list request. My hope is @adamwolf can snipe it, he's been fixing related mathjax things pretty quickly but with open source, availability is never a sure thing. Cheers!

**Comment by karlorg** [comment]
Oh sorry, I just found v2.10alpha4. Same result there I'm afraid.

**Comment by adamwolf** [comment]
Thanks for tagging me in.  I probably cannot take a look today, but I
should be able to take a look this week!  Between the great reproduction
instructions, the difference between what happens and what you expect, and
the previous work that the team has done with the Webkit debugging stuff,
I'm pretty sure we can get this one quickly.

**Comment by adamwolf** [comment]
Has anyone tried this on Anki Desktop?

**Comment by adamwolf** [comment]
(I just tried it on Anki Desktop, works fine.)

**Comment by adamwolf** [comment]
I somehow squeaked a few minutes to look at this today, there is at least one issue inside of removeFormattingFromMathjax.  Will resume later.

**Comment by timrae** [comment]
@karlorg
Should be fixed in 2.9.2beta2, please test

**Comment by karlorg** [comment]
Installing the beta failed for some reason (Android said the package was "damaged"), but installed the latest alpha from this afternoon and that's fixed it.

Thanks a lot for this, that was much faster than I expected, which is really helpful for a daily activity like flashcards :)

**Comment by adamwolf** [comment]
Nedankinde!
