### ISSUE TITLE
Incorrect v2 scheduler intervals - possible errors found, can somebody confirm?

### ISSUE THREAD

**Issue by danosl** [ankidroid/Anki-Android#5558]
###### Reproduction Steps

1. Current settings: 
- New cards: Graduating interval - 1 day, Easy interval - 2 days, Starting ease 200%
- Reviews: Easy bonus - 120%, Interval modifier - 150%

2. Doing regular daily repetitions.

###### Expected Result

**New**: Again: 2 min; Hard: 6 min; Good: 1 d; Easy: 2 d

**Learning**: Again: 10 min; Hard: 15 min; Good: 5 d; Easy: 6 d
**Learning**: Again: 10 min; Hard: 15 min; Good: 6 d; Easy: 8 d

**Reviews**: Again: 10 min; Hard: 3 d; Good: 5 d, Easy: 6 d
**Reviews**: Again: 10 min; Hard: 1.1 mo; Good: 1.7 mo, Easy: 2 mo

###### Actual Result

**New**: Again: 2 min; Hard: 6 min; Good: 10 min; Easy 2 d

**Learning**: Again: 10 min; Hard: 15 min; Good: 5 d; Easy: 5 d
**Learning**: Again: 10 min; Hard: 15 min; Good: 6 d; Easy: 6 d

**Reviews**: Again: 10 min; Hard: 3 d; Good: 3.7 mo, Easy: 8.7 mo
**Reviews**: Again: 10 min; Hard: 1.1 mo; Good: 4.9 mo, Easy: 10.1 mo

(but then _sometimes_: Learning: Again: 10 min; Hard: 15 min; Good: 1 d; Easy 2 d)

###### Debug info

AnkiDroid Version = 2.10alpha5 (same issues on 2.9.2beta2)
Android Version = 9
ACRA UUID = 487213d0-406b-466f-9e94-12da9cf75cf0

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
Can you provide a sample deck for reproduction?

**Comment by danosl** [comment]
> Can you provide a sample deck for reproduction?

Sure, how do I do it? I'm new here.

**Comment by timrae** [comment]
If you don't mind sharing publicly you can post a Google drive link here.

**Comment by danosl** [comment]
> If you don't mind sharing publicly you can post a Google drive link here.

Here you go: [AnkiDroid collection.colpkg](https://drive.google.com/open?id=10Ww9i0_7EzS7zS82F5kr9ppZzml2Eswy)

**Comment by Mornon** [comment]
Not sure if it's related: https://github.com/ankidroid/Anki-Android/issues/5449

**Comment by danosl** [comment]
> Not sure if it's related: #5449

Thanks for your feedback! I doubt these are related. IMHO, they seem like two separate issues.

**Comment by danosl** [comment]
I think I may have found the problem in [SchedV2.java](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java) where the intervals seem to be calculated.

IMHO, `86400` at the following three locations should be replaced by `86400L`
https://github.com/ankidroid/Anki-Android/blob/00b67f5b67519de705d9de480b2973f9c42bcbe6/AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java#L2181
https://github.com/ankidroid/Anki-Android/blob/00b67f5b67519de705d9de480b2973f9c42bcbe6/AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java#L2183
https://github.com/ankidroid/Anki-Android/blob/00b67f5b67519de705d9de480b2973f9c42bcbe6/AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java#L2205

Just as it is at these two locations:
https://github.com/ankidroid/Anki-Android/blob/00b67f5b67519de705d9de480b2973f9c42bcbe6/AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java#L2176
https://github.com/ankidroid/Anki-Android/blob/00b67f5b67519de705d9de480b2973f9c42bcbe6/AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java#L2210

Could somebody confirm that please? Thanks!

**Comment by mikehardy** [comment]
Tagging in @Arthur-Milchior (currently doing a pile of anki -> ankidroid porting) and @hssm (implemented v2 scheduler here)

**Comment by danosl** [comment]
Thanks! There's quite probably another spot that needs correction:
https://github.com/ankidroid/Anki-Android/blob/00b67f5b67519de705d9de480b2973f9c42bcbe6/AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java#L1995

**Comment by danosl** [comment]
FYI:
Pull request created: https://github.com/ankidroid/Anki-Android/pull/5574

**Comment by Mornon** [comment]
Thanks! At the moment I don't think i'm using the v2 scheduler (I wanted to check about the differences and if it supports time zones without changing the starting time of the day, then I kinda forgot about it), the relevant checkbox is unchecked.
