### ISSUE TITLE
Use local instead of language in preference

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5565]
###### Reproduction Steps

1. In the preference, switch language to one which is not your local language. e.g. english, for me (I'm French)

###### Expected Result
Interface in English

###### Actual Result
Interface still in French

###### Debug info
AnkiDroid Version = 2.10alpha6

Android Version = 9

ACRA UUID = 9d79c8df-964a-4eee-9188-01ff7dc1c464

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
duplicate - this one is nasty owing to at least 3 API changes in the platform in the area over the years: #4729  (and #5336 #4888 #5059)

**Comment by mikehardy** [comment]
the solution of course is to downgrade Android 5 or 6 I think :rofl: but seriously I wanted to fix that one and have a branch with a partial fix but have not completed it yet https://github.com/mikehardy/Anki-Android/tree/app-language-preference - was just playing with it in spare time which is a bit scarce at the moment vs crash bugs here
