### ISSUE TITLE
Can't display ȳ

### ISSUE THREAD

**Issue by johnlawrenceaspden** [ankidroid/Anki-Android#5570]
Obviously a font problem, no big deal, ȳ is a rare character even in macronned Latin, reporting for completeness.

###### Reproduction Steps

Make a card in desktop anki with e.g. the name Lȳdia in it
Sync to ankidroid
Preview card

###### Expected Result

Display Lȳdia

###### Actual Result

Display L dia in Preview, something a bit odd in the card browser.

###### Debug info
AnkiDroid v 2.9.1

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

**Comment by snoyes** [comment]
![Screenshot_20191023-133520_AnkiDroid](https://user-images.githubusercontent.com/4838517/67423619-34232d00-f59a-11e9-881b-f019104b7477.jpg)

Seems to work for me. Under Settings -> Appearance, what values do you have under Font?

**Comment by johnlawrenceaspden** [comment]
"System default", probably it's just the fonts on my old phone! Sorry
to bother you!

**Comment by mikehardy** [comment]
:-)
