### ISSUE TITLE
"Accessing collection" error in 2.10alpha9

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5576]
Suddenly I was kicked out of reviews today when I tried to save a change to a card. 

![Screenshot_20191027-182438](https://user-images.githubusercontent.com/45192213/67641616-77b3c900-f903-11e9-9dac-39beb0bb7d9a.png)

The message says that an error occurred while accessing the database. Same error on every deck. Before the 2.10alpha9 update I could edit cards without problem.

Things I tried, without resolving the issue:
- Check DB
- Check Media
- phone restart 
- restore from backup
- checking app permissions, memory and Battery optimization
- re-installing AnkiDroid 2.10alpha9
- full sync from Anki (where the collection is perfectly working) down to AnkiDroid
- rebuilding the database as described here: https://apps.ankiweb.net/docs/manual.html#_corrupt_collections
- copying the working collection from Anki Desktop via USB to the AnkiDroid folder

Nothing helped, still the same error. 

The solution was:

Installing AnkiDroid 2.9.1

No more error when editing cards etc.

Debug info (now on 2.9.1):

AnkiDroid Version = 2.9.1

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [ x ] character to confirm the points below:*

[x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Seems to be an issue with whatever the difference was between 2.10alpha9 and something else prior. Indications (from the mailing list) are that it was actually working while on 2.10alpha9 for a little while - reviewing and editing cards - then it stopped while still on the same version, but moving to 2.9.1 allowed use in the app

**Comment by Anthropos888** [comment]
This bug doesn't happen anymore since 2.9alpha12, so I'm gonna close this. Thanks a lot @Arthur-Milchior

**Comment by Arthur-Milchior** [comment]
2.10 you mean I guess ?
Anayway, you're welcome. I did create the bug, that's the least thing I can do to correct it.
