### ISSUE TITLE
Suggestion: Display the field-names as HTML instead of simple text

### ISSUE THREAD

**Issue by tomkahn** [ankidroid/Anki-Android#5585]
Hi! I noticed that AnkiDroid displays field names as simple text. In contrast the Desktop-versions of Anki interpet field names as HTML (not sure about AnkiMobile).

![Screenshot_20191030-231430](https://user-images.githubusercontent.com/38276038/67903338-94523a00-fb6b-11e9-867a-47e87d285857.jpg)

The option to use HTML is especially useful in complex note types. For example you can add hints to your fields that explain how this note type may be used and if there are any things to watch out for specifically.

When these field names are displayed in AnkiMobile's browser, however, the HTML source code is shown which makes the fields very long and looks ugly.

It would be great if we could get the same behavior on all platforms. Would it be possible for AnkiDroid to adapt this or was it a principled decision to do it differently?

**Comment by dae** [comment]
I did not intend for field names to include HTML, and I'm afraid it's more likely that future updates to the computer version will treat them as plain text instead.
