### ISSUE TITLE
Feature request: add card state and properties to card.html

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5587]
There is currently no information about the card state (i.e. "is:new", "is:learning") and card properties (i.e. "prop:lapses", "prop:reps") within the card.html. That means, users are not able to retrieve this information during reviews in order to dynamically change the card template.

This information could be used in several ways, for example:
- show or hide different fields on new cards and learning cards (most other SRS I know show additional information and mnemonics for new cards, but only the basic question-answer fields for review cards)
- change the background color or other styling elements for new cards, so that users in fullscreen (who don't see the numbers in the top left) can distinguish the card state
- change the appearance of hard cards (low ease) or easy cards in order to give visual hints
- change the appearance of cards that were failed recently 
- etc. etc.

Suggestion:

In the card.html there's a section where you load all the external JS. Within this script section you could add a function with an array or an object containing the card information. Ex.:
```
...
var card-state = {due:"1", new:"0", learn:"0", review:"1"};
var card-prop = {ivl:"10", reps:"3", lapses:"0", ease:"2.5"};
...
```

Users could then easily retrieve this information using JS in the card template.

###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Cause:

https://github.com/ankidroid/Anki-Android/blob/b3d6cb38f3412905462ca49c74ba8baaf66282b6/AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java#L195-L198

**Comment by david-allison-1** [comment]
@Anthropos888 This is implemented in our API: https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

Is there anything that's missing?

**Comment by Anthropos888** [comment]
@david-allison-1 
Wow, the JS API is awesome! And the documentation is very useful as well. Great work!

The only properties that seem to be missing are card's "ease" and the card's creation/modified date and time.
Especially ease could be very useful, I'm thinking about things like a red background color etc. for cards with ease < 2 or such.

**Comment by mikehardy** [comment]
will be in 2.13alpha10 when I release it (likely later today)
