### ISSUE TITLE
ContentProviderTest.testAnswerCard flaky in Travis CI

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5588]
###### Reproduction Steps

1. Watch Travis periodically
2. Look for failed builds
3. Examine the failure

###### Expected Result

Some "real" failure (in quotes because this might be real, or it could be a problem in the test itself

###### Actual Result

ContentProviderTest.testAnswerCard fails every once in a while (maybe 1 in 50 times? 1 in 100?). API17 is particularly frequent. 

```
01:55:06 V/InstrumentationResultParser: There was 1 failure:
01:55:06 V/InstrumentationResultParser: 1) testAnswerCard(com.ichi2.anki.tests.ContentProviderTest)
01:55:06 V/InstrumentationResultParser: java.lang.AssertionError: Next scheduled card has not changed
01:55:06 V/InstrumentationResultParser: at org.junit.Assert.fail(Assert.java:88)
01:55:06 V/InstrumentationResultParser: at com.ichi2.anki.tests.ContentProviderTest.testAnswerCard(ContentProviderTest.java:822)
```

###### Debug info

You can test it locally with `./gradlew jacocoTestReport` while you have a device plugged in or with an emulator running (so it runs the instrumented / on-device tests). I have never been able to reproduce it locally. Maybe I could with an API17 ARM emulator (really slow, but that's what Travis uses currently)

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java#L792

I tried to add a wait in there, thinking it might be a race condition, but that hypothesis is either wrong or it's not a big enough wait. https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ContentProviderTest.java#L817

The only thing I can think of now is to add logging everywhere in the code but I'm not sure how to retrieve the logcat from the device after the test in CI, I have never tried it.

It is also possible this simply never shows up again in CI (whether it is a real issue or not) after #5327 

###### Research

I examine the test class a bit but couldn't see where the error could come from, so I must be missing something.

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by Arthur-Milchior** [comment]
Does it occur at a specific hour ? If it happens at a moment where the day chane, it lay explain the scheduler bug

**Comment by mikehardy** [comment]
Hmm - that is possible, and the one that failed just now was around midnight my time, but Travis is running GMT and the timestamps in the logs appear to be from around 5AM. Plus, it happens more often on API17 which hints to me something performance-related is happening. Maybe I just need to target an API17 emulator in my testing (or anyone else attempting to reproduce it should similar target API17 ARM emulator heavily - even though I recognize that's a pretty miserable experience - the ARM emulators are awful when attempted interactively)

**Comment by david-allison-1** [comment]
@mikehardy have you seen this recently?

**Comment by mikehardy** [comment]
Nope 🤷
