### ISSUE TITLE
Feature request: display current interval in rescheduling dialogue

### ISSUE THREAD

**Issue by thoral** [ankidroid/Anki-Android#5595]
When using the function "reschedule cards' during repetition (or throughout the browser) it would be (very) handy to display the current interval in the input dialogue, too.
E.g.: current interval: xy
new interval: ab

![Screenshot_20191101-131218_AnkiDroid](https://user-images.githubusercontent.com/8202866/68036671-6cc3b480-fcc6-11e9-8335-eb734f16793f.jpg)

**Comment by david-allison-1** [comment]
I'd like to take this on, but only for cards in the "Review" state. Mostly because there's more complexity in getting the data for the step-based lapse/learn. 

Would this lazy fix be acceptable?

**Comment by mikehardy** [comment]
@david-allison-1 that would work for me

**Comment by Anthropos888** [comment]
That's very helpful, thanks again @david-allison-1

**Comment by david-allison-1** [comment]
@Anthropos888 No worries! Thank you for the thank you.

**Comment by thoral** [comment]
Thanks for adding this improvement in v2.10!

**Comment by david-allison-1** [comment]
@thoral No worries! Really useful for me as well
