### ISSUE TITLE
Can't open previewer on large note

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5600]
###### Reproduction Steps

Find a card/note with a lot of data (fields/card type. I don't know which one matter)

1. Open the reviewer on one of this card and then Open edit 
or
1'. or open the card browser and find one of those card.
then
2. open note type editor
3. click on preview

###### Expected Result
Previewing the card

###### Actual Result
Previewing during less than a second. Then it crash and goes back to reviewer/card browser

>E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 5246
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1326124 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7075)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: android.os.TransactionTooLargeException: data parcel size 1326124 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1143)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3890)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7075) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965) 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by Arthur-Milchior** [comment]
[erMsg.txt](https://github.com/ankidroid/Anki-Android/files/3801474/erMsg.txt)
Here is the whole message I get when I click on the preview icon (the eye)

**Comment by mikehardy** [comment]
This has an epic PR associated that will resume work when 2.9 settles a bit so I can get to it #5151 - it's the card template that can be unlimited, and the PR switches to passing templates to previewer via filesystem (only essentially unlimited data passing channel)

**Comment by Arthur-Milchior** [comment]
Can you show me where the card template is passed ? I can't figure out where it's added. It does not seems to be in the intent used in the Template Editor to open the Previewer, as this intent contains only pointers, an array with a long, and another number

**Comment by mikehardy** [comment]
I think this is what's actually getting you, note it is the activityStopped area that you are in

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java#L161

As long as the templates are handled in instance memory vs using disk as backing store, this is possible. PR #5151 will correct that https://github.com/ankidroid/Anki-Android/pull/5151/files#diff-6a23472685a7fa574a4746d52794c861R118

**Comment by Arthur-Milchior** [comment]
I just realized that this bug add the temporary card to the collection, in default deck.

**Comment by mikehardy** [comment]
The CardTemplateEditor was a tangle of related issues yes. In a nutshell, in order to preview your changes the editor was actually persisting *unsaved maybe unwanted / temporary* changes into the collection then asking the Previewer to display them (while simultaneously storing them in onSaveInstanceState etc, which can crash), then if you did want to save them it would try to reverse the work in the collection. Which it did not do perfectly even if it did not crash.

The PR revises a few chunks of infrastructure/libanki so that cards may be created with unsaved models that you pass in as JSON instead of via a collection model id, switches the CardTemplateEditor to save models temporarily to cache directory (vs collection), and opens the Previewer on the cached / temporary model. Much better, and corrects all of this but is difficult to get right and touches lots of places.

You can try it though, I just updated #5151  last night and I believe it's currently working without issue, just some structural changes to make the new functionality more maintainable before acceptance

**Comment by Anthropos888** [comment]
Is that somehow related to this bug?
https://github.com/ankidroid/Anki-Android/issues/5138

(Which is still happening in 2.9 and 2.10alpha)

**Comment by mikehardy** [comment]
@Anthropos888 I don't think it is - #5138 looked like it was going to be different to me. This issue (and #5151) all start with editing a model ('CardTemplateEditor') - everything goes wrong following model edits, not just a regular preview of card contents

**Comment by mikehardy** [comment]
This will close with the linked PR

**Comment by Arthur-Milchior** [comment]
I had entirely forgotten this bug report to be honest. Thank you
