### ISSUE TITLE
Imperfect HTML tag handling

### ISSUE THREAD

**Issue by snoyes** [ankidroid/Anki-Android#5604]
https://github.com/ankidroid/Anki-Android/blob/cd055782cc0725f700250570eb56f29e51c40e31/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L1345-L1347

HTML tags may contain an arbitrary amount of whitespace after the tag name. Tags could also contain attributes.

Should these be changed to `replaceAll("<br[^>]*?>", " ")` and the same for div?
What about the closing `</div>`?

**Comment by mikehardy** [comment]
that's a good point. I'm not sure about the input to that function either, is it already lower case or does the replace need to ignore case as well (as HTML is case-insensitive, yes?). Case aside, if the point is to remove hard breaks and divs it seems like it should actually be done correctly

**Comment by snoyes** [comment]
> the replace need to ignore case as well

Yes indeed. So, `replaceAll("(?i)<br[^>]*?>", " ")`

**Comment by mikehardy** [comment]
sounds reasonable

**Comment by david-allison-1** [comment]
We should ideally use `JSoup` to solve this.

**Comment by JalinWang** [comment]
This problem occurs in https://github.com/ankidroid/Anki-Android/blob/c7376f63b692b584d5bd9f864619c84cda4049b7/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt#L80-L86
as well.

Howerer, is `Jsoup` too heavy (latest: 428Kb) for solving such a  minor bug?

![image](https://user-images.githubusercontent.com/20621784/197331092-2b74f7f8-1eb2-43ac-93b5-1a8df88cc36b.png)

**Comment by JalinWang** [comment]
> We should ideally use `JSoup` to solve this.

This problem occurs in https://github.com/ankidroid/Anki-Android/blob/c7376f63b692b584d5bd9f864619c84cda4049b7/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.kt#L80-L86
as well.

Howerer, is `Jsoup` too heavy (latest: 428Kb) for solving such a  minor bug?

![image](https://user-images.githubusercontent.com/20621784/197331092-2b74f7f8-1eb2-43ac-93b5-1a8df88cc36b.png)

**Comment by mikehardy** [comment]
The only way to know for sure if something is "too heavy" is to build a release APK with it and without it and see what the size difference is

**Comment by dae** [comment]
This code will move into the backend when #11889 is addressed. It doesn't handle extra whitespace either, but I don't think that's a big issue in practice - it just means there won't be a space in the column where there otherwise might be.
