### ISSUE TITLE
using the new suspend and bury under new API: requires a new library release ?

### ISSUE THREAD

**Issue by lucwastiaux** [ankidroid/Anki-Android#5606]
I'd like to be able to use the new "suspend" and "bury" API functionality from this PR: https://github.com/ankidroid/Anki-Android/pull/4993
does this require deployment of a new Ankidroid API library ? I see the latest is still from april 2018: https://mvnrepository.com/artifact/api.com.ichi2.anki
thank you.

**Comment by mikehardy** [comment]
Hey @lucwastiaux! hmm when I was working on the possibility of demonstrating the stats provider in the apisample https://github.com/ankidroid/apisample/pull/9 I was using a local maven repository publish and had local defined as the first repo to check for dependencies. Made for a really fast dev cycle and the assembled .apk doesn't need any external publish, so you don't have to rely on anyone publishing or not publishing anything for it to work? Have you considered that?

If not or if that doesn't work for you then yes it would need a publish I suppose

**Comment by lucwastiaux** [comment]
Yes that works for me, let me do that, thank you.
