### ISSUE TITLE
Inaccurate document comments

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#5609]
https://github.com/ankidroid/Anki-Android/blob/4c108969a363bcce5c219b8f52a172d26290ea88/AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java#L169

Lines 169 and 222 are comments for addFieldDialog() and deleteFieldDialog(), but it appears the comment is for renameFieldDialog(). Perhaps a copy/paste job gone wrong? I would fix it, but I don't know about the processing time of these two methods.

**Comment by mikehardy** [comment]
I think the running time bit can be left alone, they look accurate based on which ones get a separate async DeckTask and which don't, and you could just alter the comments specifying what happens in your current PR

**Comment by sudomain** [comment]
Handled in #5608
