### ISSUE TITLE
Re-factor Application init to avoid ContentProvider issues

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5613]
###### Reproduction Steps

1. Use AnkiDroid API via ContentProvider without AnkiDroid running
2. Observe behavior, maybe crash?
3. 

###### Expected Result

AnkiDroid should be correctly initialized whether it was started itself or via the ContentProvider

###### Actual Result

The ContentProvider is started before the Application, so it's possible the ContentProvider users receive AnkiDroid API services in an undefined state prior the application starting up completely

Discovered in #5465 and discussed with a simple "good for now" fix in #5557 

###### Research

Most relevant documentation from https://github.com/ankidroid/Anki-Android/pull/5557#issuecomment-547739308

> When an Android app process is first started, there is well-defined order of operations:
>
> 1. Each ContentProvider declared in the manifest is created, in priority order.
> 2. The Application class (or custom subclass) is created.
> 3. If another component that was invoked via some Intent, that is created.

Suggested sketch of a solution from https://github.com/ankidroid/Anki-Android/pull/5557#issuecomment-548019443 and https://github.com/ankidroid/Anki-Android/pull/5557#issuecomment-548145195:

> it seems like there should be one object doing all the init things and exported an init method very publicly documented to synchronize so anyone calling in to it would init or wait, then return only when init was valid or attempted-but-impossible (inaccessible database or whatever). That would go a long ways towards making the Application class less of a behemoth as well

and 

> For readability purpose we could (and probably should) have a singleton that inits the application state and is called in both the application class and the content provider, but the former would basically be a no-op.

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison** [comment]
I feel this is no longer a problem
