### ISSUE TITLE
Mirror Anki's "Decrease Today's New Card Limit" functionality

### ISSUE THREAD

**Issue by boolbag** [ankidroid/Anki-Android#5615]
###### Reproduction Steps

Since the March 2019 release of [Anki for PC 2.1.10](https://apps.ankiweb.net/docs/changes.html#changes-in-2.1.10), users have been able to **decrease** a deck's new card limit for the day. This is extremely helpful whenever you mistakenly _increase_ the number of new cards for the day by a large number.

In Anki for PC, to decrease the day's new card limit, you

- go to Custom Study
- check _Increase Today's New Card Limit_
- enter a *negative* number instead positive

As of Ankidroid 2.9.1, this feature is unavailable in Ankidroid (cannot enter a negative number of new cards).

###### Expected Result

Mirror the feature from Anki for PC (allow user to enter a negative number of new cards while increasing deck's new card limits for the day).

###### Actual Result

Absent functionality.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by aplaice** [comment]
#5388 asks for the same feature, though only in the context of custom study.

**Comment by boolbag** [comment]
> 
> 
> #5388 asks for the same feature, though only in the context of custom study.

This issue actually **_is_** in the context of custom study. (Please refer to the first bullet of the top post.) That's how it works on Anki for Desktop.

**Comment by aplaice** [comment]
> This issue actually is in the context of custom study. (Please refer to the first bullet of the top post.) That's how it works on Anki for Desktop.

Yes, of course, you're right. It doesn't really make sense outside custom study...

(I'm not sure why I had consistently read (and written...) "custom study" in the context of the other issue (but only in that context), as "filtered deck", though I do know that the two are obviously completely different things... Sorry!)

**Comment by boolbag** [comment]
No need to apologize, for me it's impossible to keep everything I'd like to know about Anki in my mind at a given moment. If only someone invented a memorization program so I could remember it all. Have a great week. :-)

**Comment by aplaice** [comment]
> Have a great week. :-)

Thank you! You also have a great week!
