### ISSUE TITLE
The content of a cloze card is repeated three times.

### ISSUE THREAD

**Issue by armanshahrisa** [ankidroid/Anki-Android#5616]
###### Reproduction Steps

1. Create a cloze card with the following input:

`<div style="text-align: justify;">[<b><font color="#007f70"><u>03</u></font>.</b><b style="font-weight: bold; "><font></font></b><b style="color: rgb(85, 170, 0); "><font color="#aa0000"><u>04</u></font></b><b>.</b><b>|<font color="#55aa00"><u>081</u></font>|</b><b>.</b><b><font color="#e69900">03</font>.</b><b style="color: rgb(0, 91, 170); ">02</b>] {{c1::<b><font color="#666600">[sound:Strachan-03.04.081.03.02-Q_0001.mp3]</font></b>::Audio}} Thus, the overall variance of the phenotype \(V_\mathrm{P}\) is the {{c1::sum of the variances due to the individual causes of variation}}—the {{c1::environmental variance \(V_\mathrm{E}\)}} and {{c1::the genetic variance \(V_\mathrm{G}\)}}:</div><div style="text-align: justify;"><br></div><div>{{c1::<b><font color="#666600">[sound:Strachan-03.04.081.03.02-Q_0002.mp3]</font></b>::Audio}} {{c1::\(V_\mathrm{P} = V_\mathrm{G} + V_\mathrm{E}\)::formula}}<br></div><div style="text-align: justify;"><br></div><div style="text-align: justify;">{{c1::<b><font color="#666600">[sound:Strachan-03.04.081.03.02-Q_0003.mp3]</font></b>::Audio}} \(V_\mathrm{G}\) can in turn be broken down to a variance {{c1::\(V_\mathrm{A}\)::variance}}, which is due to {{c1::simply additive genetic effects}}, and two extra terms. {{c1::\(V_\mathrm{D}\)::Variance}} accounts for {{c1::dominance effects}}: because of {{c1::dominance}}, the effect of a certain combination of alleles at a locus may not be simply the sum of their individual effects. {{c1::\(V_\mathrm{I}\)}} is an {{c1::interaction variance}}: the {{c1::overall effect of genes at several loci}} may not be simply the sum of the effects that each would have if present alone:<br></div><div style="text-align: justify;"><br></div><div>{{c1::<b><font color="#666600">[sound:Strachan-03.04.081.03.02-Q_0004.mp3]</font></b>::Audio}} {{c1::\(V_\mathrm{G} = V_\mathrm{A} + V_\mathrm{D} + V_\mathrm{I}\)::formula}}<br></div><div style="text-align: justify;"><br></div><div style="text-align: justify;">{{c1::<b><font color="#666600">[sound:Strachan-03.04.081.03.02-Qe_0005.mp3]</font></b>::Audio}} Therefore:</div><div style="text-align: justify;"><br></div><div>{{c1::<b><font color="#666600">[sound:Strachan-03.04.081.03.02-Q_0006.mp3]</font></b>::Audio}} {{c1::\(V_\mathrm{P} = V_\mathrm{A} + V_\mathrm{D} + V_\mathrm{I} + V_\mathrm{E}\)::Audio}}<br></div>`

2. It is shown normally in Anki but repeated three times in Ankidroid. I took a look at the HTML code and there was nothing unexpected.

###### Expected Result
The card content is shown once.

###### Actual Result
The card content is repeated three times.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by snoyes** [comment]
I could not repeat with the latest code.

Can you reduce the note to the simplest one that you can which still repeats the behavior (first try taking out all the text that is not inside a {{c1:...}}, then try reducing the number of {{c1::...}, and continue until removing anything more causes the problem to disappear); then update the bug with that new text and attach a screenshot which illustrates the problem?

**Comment by armanshahrisa** [comment]
I forgot to mention that I'm using the latest stable version for Google Play. I have shorted the code. I also attach a screenshot. Hopefully, it helps.

`<div style="text-align: justify;">and {{c1::the genetic variance \(V_\mathrm{G}\)}}:</div><div style="text-align: justify;"><br></div><div>{{c1::<b><font color="#666600">[sound:Strachan-03.04.081.03.02-Q_0002.mp3]</font></b>::Audio}} {{c1::\(V_\mathrm{P} = V_\mathrm{G} + V_\mathrm{E}\)::formula}}<br></div><div style="text-align: justify;"><br></div><div style="text-align: justify;"><br></div><div>{{c1::<b><font color="#666600">[sound:Strachan-03.04.081.03.02-Q_0004.mp3]</font></b>::Audio}} {{c1::\(V_\mathrm{G} = V_\mathrm{A} + V_\mathrm{D} + V_\mathrm{I}\)::formula}}<br></div><div style="text-align: justify;"><br></div><div style="text-align: justify;">{{c1::<b><font color="#666600">[sound:Strachan-03.04.081.03.02-Qe_0005.mp3]</font></b>::Audio}} Therefore:</div><div style="text-align: justify;"><br></div><div>{{c1::<b><font color="#666600">[sound:Strachan-03.04.081.03.02-Q_0006.mp3]</font></b>::Audio}} {{c1::\(V_\mathrm{P} = V_\mathrm{A} + V_\mathrm{D} + V_\mathrm{I} + V_\mathrm{E}\)::Audio}}<br></div>`

[](https://imgur.com/wdfL0cd)

**Comment by mikehardy** [comment]
There have been many cloze changes that are not released quite yet, can you attempt to reproduce using latest alpha version, you join the beta group then the alpha mailing list like so: https://docs.ankidroid.org/#betaTesting

**Comment by armanshahrisa** [comment]
I can confirm that the issue is resolved in the latest stable release. Nice job.

**Comment by mikehardy** [comment]
Fantastic! @adamwolf  and @snoyes earning all the internet points on this one :-)
