### ISSUE TITLE
V2 scheduler: number for "due today" is in fact "due now"

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5617]
###### Reproduction Steps

1. enable v2 scheduler in the options
2. do some reviews
3. answer one card with "again" and observe the numbers in the top left and in the deck overview screen under "due today"

###### Expected Result

- the numbers in the top left of the reviewer show the cards "due today" as in V1 scheduler
- the numbers in the "deck overview screen" (click on the numbers in the deck list) show the cards "due today" (since it is labeled "due today")

###### Actual Result

- the numbers in the top left of the reviewer show the cards "due now" 
- the numbers in the "deck overview screen" show the cards "due now" (although it is labeled "due today")

Before marking the card "again":
![before](https://user-images.githubusercontent.com/45192213/68510908-02d27e80-0275-11ea-8276-8722a9e83dea.jpg)

After:
![after](https://user-images.githubusercontent.com/45192213/68510920-0b2ab980-0275-11ea-88b7-9e1c333c3a8d.jpg)

There should be a red "1" as in V1 scheduler. Same in the deck overview screen.

###### Debug info
AnkiDroid Version = 2.10alpha17

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [ x ] character to confirm the points below:*

[  x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by Anthropos888** [comment]
@hssm 

In Anki, the number for due reviews changes to the "due now" number when activating V2:
![image](https://user-images.githubusercontent.com/45192213/73077210-082c8600-3ec0-11ea-9019-5172182ce0f3.png)

With V1 scheduler, the numbers are the "due today" numbers:
![image](https://user-images.githubusercontent.com/45192213/73077327-432eb980-3ec0-11ea-9fc8-432f5d4d6f51.png)

Since Anki doesn't use the terms "now" or "today" it's no problem. But AnkiDroid says "due today", and that's incorrect for V2. Maybe you should change it to "due now" or just "due" when users enable V2.

**Comment by david-allison-1** [comment]
Bad bot...

**Comment by dae** [comment]
Closed by #14171.
