### ISSUE TITLE
Cannot change AnkiDroid Directory to sdcard

### ISSUE THREAD

**Issue by meokey** [ankidroid/Anki-Android#5622]
###### Reproduction Steps

1. Click settings, Andanced, AnkiDroid Directory
2. Change the path to my sdcard /storage/F442-FDB0/Documents/AnkiDroid, which I created by moving the same folder from /sdcard/AnkiDroid
3. Hit OK

###### Expected Result
The AnkiDroid Directory path should changed to what I desired

###### Actual Result
But it still be the default /sdcard/AnkiDroid

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.9.1
Android Version = 9
ACRA UUID = 19041193-d063-41f1-9eb4-6c9b5f0dc349

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by Alyxvance** [comment]
you have to configure the phone thats the SD card is standard Path for apps
![issue3](https://user-images.githubusercontent.com/1220916/77700748-1fb5e700-6fb5-11ea-965e-43adb41f489c.jpg)
