### ISSUE TITLE
abbr tag not working

### ISSUE THREAD

**Issue by warfarincoumadin** [ankidroid/Anki-Android#5631]
Abbreviations do not work correctly during reviews

`<abbr title="Cascading Style Sheets">CSS</abbr>`

results, as expected, in underlined text, however the text is unclickable and no tooltip is shown.

Haven't tested this, but perhaps the problem extends to other tags as well.

**Comment by david-allison-1** [comment]
bot was a little too hasty.

@warfarincoumadin, is this still an issue?
