### ISSUE TITLE
mixing back answers

### ISSUE THREAD

**Issue by beebeep85** [ankidroid/Anki-Android#5632]
###### Reproduction Steps

1. Anki mixes back answers of 2 different cards. Good front question and wrong back answer
2. 1 error card on every 10 on average
3. No visible errors until card reviewing. Card made on PC,but errors visible both on PC and mobile Android version.

###### Expected Result
Normal card with front text question and text+audio back answer.

###### Actual Result
Front text question mixed with text +audio back answer of the different card.

###### Debug info
AnkiDroid Version = 2.9.1

Android Version = 8.0.0

ACRA UUID = 2d11bd4e-0770-4fc9-bde1-d87acfff6b60

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi @beebeep85 ! Sorry you're having trouble - there have been a lot of changes with regard to the internal anki library ported from upstream. Can I ask a couple questions?

1- are you using the v1 or v2 scheduler?
2- would you be willing to confirm this still happens with the current alpha version? https://docs.ankidroid.org/manual.html#betaTesting (or direct install - https://github.com/ankidroid/Anki-Android/wiki/Installation#apk) - note you can revert to the previous version any time

**Comment by beebeep85** [comment]
Hi mikehardy,

My version is 2.1.15 (442df9d6) so, yes, I am using V2 scheduler. No so tech-savvy, I downloaded latest version from https://apps.ankiweb.net/ about a month ago:


Do you still advise that I follow your 2. step and make a little testing?
"would you be willing to confirm this still happens with the current alpha version? https://docs.ankidroid.org/manual.html#betaTesting (or direct install - https://github.com/ankidroid/Anki-Android/wiki/Installation#apk) - note you can revert to the previous version any time"

Thanks!

**Comment by mikehardy** [comment]
This sounds like an Anki Desktop issue, not AnkiDroid, based on the version you mention (2.1.15) and where you downloaded it (apps.ankiweb.net) - you'll want to get help from them, as this repo is just for the android project

http://anki.tenderapp.com/
