### ISSUE TITLE
don't sync automatically after crash

### ISSUE THREAD

**Issue by HairyPhil** [ankidroid/Anki-Android#5639]
Enhancement request.

AnkiDroid should not sync automatically if the app failed to close properly last time.

For example, I just discovered a bug (reported separately) that corrupted my database and then crashed, and upon reopening AnkiDroid after the crash, the corrupt database was synced automatically overwriting the good database on the server.

It would be better if I had an opportunity to investigate whether the database was corrupt before syncing it.

###### Debug info

AnkiDroid version 2.9.1.

###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Sensible - not sure if we have the necessary information to do this but it should be possible. 

ACRA (our crash system) would need a mechanism to report whether it had a crash on the last run, and we could use that during startup tasks like automatic sync to modify behavior accordingly

Not sure ACRA makes that possible or not but it definitely write to storage on crashes and reads from storage on startup so even if it isn't doing it already it might be possible to extend it with a plugin directly or just do the actions on crash/startup next to the ACRA usages.

**Comment by david-allison-1** [comment]
stalebot was a little too hasty. I'd like to see this, seems like a good first issue.
