### ISSUE TITLE
pictures not showing up on Ankidroid app but works on computer. says error syncing media 

### ISSUE THREAD

**Issue by ukachi13** [ankidroid/Anki-Android#5641]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Hi @ukachi13,

Is this still occurring? Could you provide any more information?
