### ISSUE TITLE
Bug: Export "with media" includes unused media

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5643]
###### Reproduction Steps

1. Have a deck with at least one small media/external file
2. Long-press the deck, choose "Export deck"
3. Tick "Include Media" and export and save the file
4. Export the same deck without media and compare the file size of both exported files

###### Expected Result

Only the used media files are exported with the deck. The file size of the deck with media is higher just by the file size of the used media.

###### Actual Result

Unused media in the collection.anki folder is included in the export! I exported a test deck of 4Kb with a js file of 1Kb and Ankidroid created a 9MB (!) file and included some fonts from the collection.media folder which are NOT used in the deck.

The export without media is just 4Kb as expected.

I experienced this bug already a year ago in the 2.9alpha versions and it's still in 2.9 and 2.10alpha

###### Debug info
AnkiDroid Version = 2.10alpha17

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Is check media able to correctly determine that the file is unused, and delete it?
Is this a media file with a '_' in front of it, indicating it should be synchronized, and may be used in cards, but in user card code?

**Comment by Anthropos888** [comment]
Hey Mike, yes, the files start with "_" but they are not used in that deck.
Check Media is able to delete unused files, but since the fonts are used in other decks, I don't want to delete them (also I think that Check Media ignores files with "_" which is good).

**Comment by Anthropos888** [comment]
I just created another test deck which doesn't use any media. When choosing "include media" the export will contain just all files from the collection starting with an underscore.

I don't think there is any reason for that?

**Comment by mikehardy** [comment]
The reason might simply be that it's hard. Javascript is Turing-complete and can dynamically construct names, the exporter isn't going to evaluate all the cards in a full browser context then walk the DOM and find all references - in fact the interface you build in cards could even need user interaction in order to generate references dynamically and show them. I'm not sure it's a tractable problem. If it's specified that `_` preserves a file even when the system doesn't know how you are using it, I think export/import has to similarly just transfer it.

My guess is Desktop behaves the same, but I haven't checked

**Comment by Anthropos888** [comment]
Hey Mike, Anki Desktop doesn't include any unused media files in the export and works as expected. That's also my only workaround until now - sync the collection and export the file via Anki desktop.

So maybe this issue should get the Anki ecosystem label?

**Comment by mikehardy** [comment]
Yeah - and fascinating, I'll have to see how they do that

**Comment by Anthropos888** [comment]
The export on Anki Desktop indeed takes several seconds when you check "include media", even if the cards don't use any media and thus no media will be exported. Without checking "include media" the export finishes instantly. Seems that Anki Desktop's search for media references is quite thorough.

**Comment by timrae** [comment]
I think that might have even been me that added it to Anki desktop. https://github.com/dae/anki/pull/114

**Comment by david-allison-1** [comment]
We already have the code written

https://github.com/ankidroid/Anki-Android/blob/fbb115f372867c0867d9dd81b2bd1bd2f55528f9/AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java#L270-L289

Issue cause: 

    2020-03-20 01:25:54.045 31364-31505/com.ichi2.anki W/AnkiExporter: _modelHasMedia given null model

**Comment by david-allison-1** [comment]
Further investigation:

https://github.com/ankidroid/Anki-Android/blob/fbb115f372867c0867d9dd81b2bd1bd2f55528f9/AnkiDroid/src/main/java/com/ichi2/libanki/AnkiPackageExporter.java#L234-L242

https://github.com/ankitects/anki/blob/862e2b48f06dadf414d171d2cfdc4ac3ad79e7da/pylib/anki/exporting.py#L270-L276

We provide the index of the model instead of the model, therefore we fail.

**Comment by Anthropos888** [comment]
Unused media is not included anymore as of alpha53. Thanks @david-allison-1  Still there's one problem:
If media is included via an external ccs file (`@import url("_css_main.css");`), it will not be exported.

I include all my fonts in an external css like this:
```
@font-face {
    font-family: F10;
    src: url('_ackaisyo.ttf');
    font-display: block;
}
```

Those fonts will not be included in the export. But since this is the same behavior as in Anki desktop (I just tested it), I guess there's nothing we can do here unless someone is going to change it upstream.

**Comment by david-allison-1** [comment]
> Unused media is not included anymore as of alpha53. Thanks @david-allison-1 Still there's one problem:
> If media is included via an external ccs file (`@import url("_css_main.css");`), it will not be exported.
> 
> I include all my fonts in an external css like this:
> 
> ```
> @font-face {
>     font-family: F10;
>     src: url('_ackaisyo.ttf');
>     font-display: block;
> }
> ```
> 
> Those fonts will not be included in the export. But since this is the same behavior as in Anki desktop (I just tested it), I guess there's nothing we can do here unless someone is going to change it upstream.

Great to hear!

Could you report it upstream? Give me a ping when it's in and I'll add it to my todo queue

**Comment by Anthropos888** [comment]
@david-allison-1  Here the answer of Damien about scanning external files for media references:

> I'm afraid I don't think it's worth complicating the code to support reading external files.

I guess the same is true for AnkiDroid? Then it's fine for me, I'm not going to open it as a new issue.

**Comment by david-allison-1** [comment]
> @david-allison-1 Here the answer of Damien about scanning external files for media references:
> 
> > I'm afraid I don't think it's worth complicating the code to support reading external files.
> 
> I guess the same is true for AnkiDroid? Then it's fine for me, I'm not going to open it as a new issue.

Up to @mikehardy regarding ecosystem compatibility. CSS would be easy to do and would provide a decent benefit for little tech debt. I wouldn't mind getting on with this after a few releases once we've got some big-ticket items out the way.

**Comment by mikehardy** [comment]
If someone wants to do it, this isn't the sort of "incompatibility" that pains me. It should be flagged really clearly in the exporter (which is libanki I believe) where we slice in the extra bit if it's done for future people trying to keep desktop and ankidroid glued together
