### ISSUE TITLE
Preview not available in note editor

### ISSUE THREAD

**Issue by Akshittuli** [ankidroid/Anki-Android#5644]
###### Reproduction Steps

1. Open card browser and click on the newly made flashcard
2. Edit the flashcard as required
3. Click top right corner to open the drop down menu

###### Expected Result

There should be an option to preview the flashcard

###### Actual Result

There is no such option. Instead you have to go back to the list of flashcards, then select the flashcard, then click on top right corner to get the drop down menu to select preview flashcard.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I confirm this on master just now - there's no preview available during note edit, I don't think this is intentionally not there so labelling it as bug for now unless there's issue / pull request history pointing to intentional removal for some reason

**Comment by wadejnu** [comment]
Try it add to big preview button on the bottom.

**Comment by Anthropos888** [comment]
The preview button can be reached from the "edit note" screen by pressing the name of the card template (i.e. "card 1") and then pressing the big eye in the top right corner.

**Comment by mikehardy** [comment]
Hmm non-intuitive at very least, I couldn't find it when expected. @Anthropos888 I'll follow your steps to repro how to do it, then think if there's something to do or not

**Comment by Akshittuli** [comment]
It would be much helpful though, if the "eye" for preview was there right at the edit note screen

**Comment by mikehardy** [comment]
If anyone is still watching this issue, this is available in 2.12alpha10 which is processing in google play store now and should release momentarily, or you can try directly in parallel / next to your main install with this package https://github.com/ankidroid/Anki-Android/releases/download/v2.12alpha10/AnkiDroid-2.12alpha10.parallel.A.apk

**Comment by david-allison-1** [comment]
Already had a number of positive responses regarding the alpha (aside from the general slowness associated with importing/unzipping 2GB)
