### ISSUE TITLE
Travis builds error with ".../emulator-headless: No such file or directory"

### ISSUE THREAD

**Issue by barbeau** [ankidroid/Anki-Android#5649]
It looks like the Android SDK team made changes that break the Travis config.  See https://travis-ci.org/CUTR-at-USF/Anki-Android/jobs/614265625#L553, which says:

~~~
$ EMU_PARAMS="-verbose -no-snapshot -no-window -camera-back none -camera-front none -selinux permissive -qemu -m 2048"
  EMU_COMMAND="emulator"
  if [[ $ABI =~ "x86" ]]; then
    if [ $API != "15" ]; then
      # API15 is using the canary channel right now, and emulator-headless is command not found?
      # this may break in the future when the current canaries are promoted but until now it works
      # for all but API15 on the canary channel
      EMU_COMMAND="emulator-headless"
    fi
  fi
  # This double "sudo" monstrosity is used to have Travis execute the
  # emulator with its new group permissions and help preserve the rule
  # of least privilege.
  sudo -E sudo -u $USER -E bash -c "${ANDROID_HOME}/emulator/${EMU_COMMAND} -avd test ${AUDIO} ${EMU_PARAMS} &"
  
bash: /home/travis/android-sdk/emulator/emulator-headless: No such file or directory
~~~

So it looks like the canaries have been promoted, according to the comment? Hence `/home/travis/android-sdk/emulator/emulator-headless: No such file or directory`.

###### Reproduction Steps

Here's what I did:
1. Fork project
2. Enable Travis on fork
3. Push new commit to fork to trigger Travis build

Alternately, I'm assuming just restarting one of the Travis builds for this project master branch will result in the same.

###### Expected Result

Travis build should start emulator

###### Actual Result

Emulator startup hangs due to `bash: /home/travis/android-sdk/emulator/emulator-headless: No such file or directory`, resulting build erroring out on Travis

###### Debug info
N/A

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Yeah, I have a branch going with a fix for it that temporarily pins the emulator back a version, and I'm tracking the upstream bugs. It's a couple things at once

Here's a link to the Travis community discussion where I collaborate with another person on this, and there is a link to the upstream bug if you want to track https://travis-ci.community/t/add-kvm-support/1406/16

Not working quite yet but just because I'm traveling this week - I'll have it fixed so it's not blocking anything within another day or so I think: https://github.com/mikehardy/Anki-Android/commits/CI-pin-emulator

**Comment by mikehardy** [comment]
If you are already in the area (and it sounds like you are) it is a nearly trivial fix temporarily, I just need to adapt the change my collaborator was using so it is actually the way our .travis.yml works vs the "copy + splat" I did as a first cut at it. It's not very involved, just takes time while you wait for Travis to validate

**Comment by barbeau** [comment]
@mikehardy Ok, thanks for the quick reply. I probably won't have time to look at this until mid next week at the earliest. Thanks for your work on this - I know it's a pain to debug on Travis due to the waiting.

**Comment by mikehardy** [comment]
Some information about underlying Android emulator bugs, the current version of the emulator has more problems I think than just 'emulator-headless' not being found, but:

`For now, you can work around this issue via adding "-gpu swiftshader_indirect" to the command line.`

and: ` I can put out another version this week.`

...both from https://issuetracker.google.com/issues/145622251

Not sure if this is a multi-bug with emulator-headless and that mixed in but it is possible.

Either way I haven't had time to dig in on this yet but it is close to the top of the stack so I can 1) make sure we don't block PRs and 2) I can do TLS1.2 for Android 4.x prior to deadline #5623 

I will comment here before starting work, for the avoidance of doubt, so if anyone picks this up prior they can know there is no duplication of effort. Please feel free :-)

**Comment by barbeau** [comment]
@mikehardy Thanks for the update! I'm trying the `-gpu swiftshader_indirect` workaround for the android-maps-utils project here, hopefully it works :crossed_fingers::
https://github.com/googlemaps/android-maps-utils/pull/590

**Comment by mikehardy** [comment]
29.3.0 is out and we're building clean again using 'emulator -no-window', I'm about to land the PR that fixes us here

**Comment by barbeau** [comment]
Thanks @mikehardy!
