### ISSUE TITLE
Allow disabling the cloze deletion action

### ISSUE THREAD

**Issue by marmistrz** [ankidroid/Anki-Android#5650]
I'm not using cloze deletion for my cards and the presence of cloze deletion forces an extra tap to reach the copy action. It'd be nice to be able to disable/change the position of the cloze deletion action.
###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
If you search through recently merged/closed PRs (not the open ones - big stack there at the moment) I think you'll see one related to moving it around in the menu so it was not present unless you were editing a cloze card, and was after copy even there. Could you check that and see if it meets your needs? If so, then following the "beta testing" instructions on the FAQ will show how to get the alpha version where I believe it exists

Provisionally closing because everything I asserted above is true - but I could easily be wrong if so come back and we'll reopen

Thanks!

**Comment by marmistrz** [comment]
I'm not using Play Services on my device, so the "beta testing" instructions are not applicable. I'll probably try building the apk from source in the following days and see (AFAIK I can't change the package name without rebuilding). 

Thanks!

**Comment by mikehardy** [comment]
check our releases page, we put *all* our APKs up there for download by anyone if they like, and I manage the parallel releases on my fork in case you need those for testing. I've got the most current stable build up there but not the alphas yet I don't think. I can generate a batch from current alpha if that's useful. Cheers

**Comment by marmistrz** [comment]
Can those APKs from releases be installed in parallel with the stable version? (i.e. do they have a different package id than the stable version?)

**Comment by mikehardy** [comment]
they do not. Perhaps install the existing stable versions from my parallel set, get it working, then install alpha over the main. Just as safe, but uses things that exist now, as I'm busy - so it avoids effort 

https://github.com/mikehardy/Anki-Android/releases/tag/v2.9.1

**Comment by marmistrz** [comment]
I guess building it on my own & patching build.gradle will be less effort :D

**Comment by mikehardy** [comment]
Highly doubtful. You'll need release java keystores set up and everything. At the end you will have exactly what I gave you. But whatever you want.

You might like https://github.com/ankidroid/Anki-Android/blob/master/tools/parallel-package-release.sh

**Comment by marmistrz** [comment]
Well, there's no need for any keystores. `installDebug` works like charm. But `parallel-package-name.sh` was highly useful for renaming the app id.

**Comment by mikehardy** [comment]
oh interesting - I did not realize that F-Droid resigns. That is a difference, yes - I'll keep it in mind.

**Comment by marmistrz** [comment]
They don't resign, they just build from scratch and necessarily need to sign with their own keys.
