### ISSUE TITLE
Cloze reference counter resets when adding cloze references to multiple fields

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#5652]
###### Reproduction Steps

1. create a cloze note type that has at least two cloze text fields in the template as suggested in the [manual to handle "overlapping text"](https://apps.ankiweb.net/docs/manual.html#cloze-deletion). 
e.g. 
`{{cloze:text 1}}
{{cloze:text 2}}`
2. Add a card of this note type. When adding cloze references like {{c1::}}, {{c2::}}, from the AnkiDroid context menu, the number correctly increments within a single field. When you switch to the other cloze field and start adding more references, the number resets to 1. This is undesired because if two different {{cloze:}} fields have the same cloze reference e.g. {{c1::}}, then both fields will be shown on the card.

For example suppose {{cloze:text1}} contains {{c1::}} {{c2::}} {{c3::}}. If we switch to {{cloze:text2}} and use the context menu to add more references, it will start adding references at {{c1::}}. This will show both fields on the actual card and looks bad.

###### Expected Result
A similar behavior as Anki desktop when adding cloze references via `CTRL + SHIFT + C` or the [...] button. Anki desktop will look in _all_ fields for a valid cloze reference with the highest number and add 1 when creating the next reference.

To contrast with the previous example:  suppose {{cloze:text1}} still contains {{c1::}} {{c2::}} {{c3::}}. If we switch to {{cloze:text2}} and start adding references using `CTRL + SHIFT + C`, then the next created reference will be {{c4::}}. The counter doesn't reset and only one of the {{cloze:text}} fields is shown per card.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.10alpha9

Android Version = 7.0

ACRA UUID = 8143cf86-e917-4ef5-ae64-10dc9d0a9999

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum

**Comment by sudomain** [comment]
I think I can take a crack at this, but I would appreciate a little instruction from you @mikehardy :

The relevant AnkiDroid code is at the end of [NoteEditor.java](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1691) and the relevant Anki code is in [aqt/editory.py](https://github.com/ankitects/anki/blob/master/qt/aqt/editor.py#L636). Two questions about this:

1. Since this code isn't in the libanki directory, do I have to worry about having my java code match the upstream python code? Is it sufficient to have the code differ as long as the behavior is similar?

2. There are functions in NoteEditor.java that iterate though the fields of a note using this:

`for (FieldEditText f : mEditFields) {`

My PR will also do this, but the variable name "f" (or "e" in some cases) is not very descriptive. Should I stick with the "f" variable name for my PR or can I use something like "fieldText"?

**Comment by mikehardy** [comment]
Hey @sudomain! Good to see you. I can feel you leaning in a certain way on both questions and I'd lean the same. 

If it is not in libanki there is no need to adhere to upstream Python code, except it should work the same

I prefer descriptive variable names personally, so go for it

**Comment by sudomain** [comment]
Mike thanks for the quick reply and guidance. I didn't know if I should change other instances of
`for (FieldEditText f : mEditFields) {` to have more descriptive variable names, so I left it as is

**Comment by mikehardy** [comment]
Nah - no need to spread out and refactor everything, just when generating new code descriptive names are more useful in my opinion, and this one is already merged and will be out in the next alpha, so all done here. Thank you for the fixes here and over time - much appreciated
