### ISSUE TITLE
Couldn't mkdirs

### ISSUE THREAD

**Issue by anlalalu** [ankidroid/Anki-Android#5654]
###### Reproduction Steps

1. Tap 'more options'
2. Tap 'restore from backup'
3. Tap 'continue'
4. select a backup

###### Expected Result
succeed with no error

###### Actual Result
AnkiDroid does not crash, but an error arises
E/SQLiteDatabase: Couldn't mkdirs /sdcard/AnkiDroid/tmpzip/collection.media.ad.db2

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.9alpha25

Android Version = 4.4.4

ACRA UUID = aafe0f30-e91d-4478-9f8e-310ab576ea9b

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Possibly this https://github.com/ankidroid/Anki-Android/wiki/FAQ#i-have-too-many-media-files-and-cant-copy-them-all-to-my-device

Possibly disk full

Hard to say - with android devices in the 4.x range the filesystem in use was quite old and leads to the FAQ above

**Comment by dae** [comment]
If it's still an issue, please let us know.
