### ISSUE TITLE
Text from lower field copied to upper field when switching to multitask mode.

### ISSUE THREAD

**Issue by moralesg** [ankidroid/Anki-Android#5660]
###### Reproduction Steps

1. Create a new card
2. Type something in the upper field.
3. Type something in the lower field (translation, result)
4. Use the android's multitask mode, which allows having 2 apps active simultaneously (not sure if it has something to do: the focus was on the lower field).

###### Expected Result
Nothing, the typed texts should remain untouched.

###### Actual Result
The text from the lower field gets copied to the upper field (and the focus goes to that field too)
![Capture+_2019-12-12-23-49-02](https://user-images.githubusercontent.com/14352147/70766706-584eef00-1d3d-11ea-8797-be499141f298.png)
![Capture+_2019-12-12-23-49-57](https://user-images.githubusercontent.com/14352147/70766717-60a72a00-1d3d-11ea-8ea5-d51f8bc4a7b7.png)

###### Debug info
AnkiDroid Version = 2.9.1

Android Version = 8.0.0

ACRA UUID = 67f96b92-d18b-4f84-a214-895e69d241fd

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum
(but it's not easy using a mobile browser)

**Comment by mikehardy** [comment]
can you maybe simplify the report by removing the multitask variable: try it single task to see if you can reproduce?

**Comment by moralesg** [comment]
Hi,
 the thing is, that the problem happens exactly as a consequence of starting the multitask mode.
to be clearer, doing a long press in the square button, at the bottom right.

as the long press starts the multitask mode, i see the phone screen get divided in two, anki taking the upper half, and another app the lower half.
as part of the action, i see how the text of the lower textfield gets copied to the upper one.the focus moves also to the upper field.
hope this helps, thanksGerman

 
  Le ven., déc. 13 2019 à 14:11, Mike Hardy<notifications@github.com> a écrit :   
can you maybe simplify the report by removing the multitask variable: try it single task to see if you can reproduce?

**Comment by snoyes** [comment]
I am able to duplicate this behavior. It does not matter which field has focus at the time. It also happens when 
* you come out of split screen mode
* you pick split screen, but then exit immediately without choosing the other app
* you open AnkiDroid in pop-up view
