### ISSUE TITLE
Custom sync server no longer working

### ISSUE THREAD

**Issue by bobberb** [ankidroid/Anki-Android#5661]
###### Reproduction Steps

1. Set custom sync server endpoint
2. Attempt log-in
3. Fail

I recently decided to wipe Anki and move my DB to my sdcard to hold all my large media collections. 

I decided on deleting everything and started from an empty app. Upon trying to sync, I am unfortunately greeted with an instant network failure. I have not changed anything on the sync-server end, Windows and Linux still sync without issue. I have no issue hitting the sync-server from Firefox, greeted with the HTML "Anki Sync Server" page (http and https OK)

###### Expected Result
Log in

###### Actual Result
"A network error has occurred" (instant) 

###### Debug info
AnkiDroid Version 2.9beta10 (and latest release as well, downgraded to last working version)
Android Version = 9

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by adamwolf** [comment]
I am using a custom sync server on the latest AnkiDroid and it works for
me.  I haven't moved my collection or anything, so this is just a datapoint
for debugging to say "they're not broken in all cases" :)

**Comment by adamwolf** [comment]
What happens if you move your DB back off the SD card, if that was the
change that broke it?

**Comment by bobberb** [comment]
Too many steps to tell which exactly since I uninstalled it as well. Moving
back to internal does not help sync.

**Comment by mikehardy** [comment]
I'm tentatively closing this, as it cannot be reproduced
