### ISSUE TITLE
Youglish embed

### ISSUE THREAD

**Issue by skyemans** [ankidroid/Anki-Android#5662]
Feature request: Youglish embed

Youglish [embed widget](https://youglish.com/developer) works well on Ankiweb and desktop but on Ankidroid gives the error message "Please upgrade browser".
This would be a big advantage for adding video content.

**Comment by mikehardy** [comment]
What versions are you on (phone operating system, chrome, android system webview, ankidroid)

"Please upgrade browser" makes me think...you need to upgrade your browser, which implies making sure you have more recent version of android, and chrome + the android system webview (if in use) are fully up to date. Chrome is on 79 right now for instance. Might work if it's on that version?

**Comment by mikehardy** [comment]
Either way, attaching a collection here that is as small as possible but contains an example of what a youglish card looks like would be useful

**Comment by skyemans** [comment]
> What versions are you on (phone operating system, chrome, android system webview, ankidroid)
> 
> "Please upgrade browser" makes me think...you need to upgrade your browser, which implies making sure you have more recent version of android, and chrome + the android system webview (if in use) are fully up to date. Chrome is on 79 right now for instance. Might work if it's on that version?

Hi, Mike.

I have tried a couple of phones (Android 6.0) with latest Chrome and

 Android system webview updated (with latest Ankidroid install). I have checked again and I see Ankiweb doesn't work either on the default browser but fine on Chrome. So it is clearly the browser and no fault of your fantastic App.  I guess I will need to get a newer version of Android...? 

Example card: https://ankiweb.net/shared/info/1621959943

Thanks for your assistance. Sorry if I'm asking silly questions. 🙄

**Comment by mikehardy** [comment]
Strange - I tried it and see what you see even with a fully up to date emulator, chrome version 78, that's a pretty up to date browser.

Youglish must just not like being in a webview for some reason. You can use this to try different styles perhaps - you can both get the rendered card contents for testing in full browsers, plus inspect the card while it is displaying on your device or in a simulator so you can try different things: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

I don't think there is anything in particular we can do in AnkiDroid though, it's a card content problem, so I'm going to close this, but if you find something remarkable or need help getting the debugging setup I may have time later to respond

**Comment by skyemans** [comment]
> Strange - I tried it and see what you see even with a fully up to date emulator, chrome version 78, that's a pretty up to date browser.
> 
> Youglish must just not like being in a webview for some reason. You can use this to try different styles perhaps - you can both get the rendered card contents for testing in full browsers, plus inspect the card while it is displaying on your device or in a simulator so you can try different things: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection
> 
> I don't think there is anything in particular we can do in AnkiDroid though, it's a card content problem, so I'm going to close this, but if you find something remarkable or need help getting the debugging setup I may have time later to respond

I am not very computer savvy, so I can't do any tests myself. However, just to let you know that the Youglish owner got back to me and said to try setting the Webview User-Agent to the latest Chrome or Firefox.  Thanks again for taking the time to reply.
