### ISSUE TITLE
Collection deemed to be inconsistent when current deck has more than a thousand review

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5672]
###### Reproduction Steps

1. Have a collection with a deck D with more than a thousand review due
2. Select D.
3. Sync

###### Expected Result
Being able to synchronize

###### Actual Result
See an error message stating that your collection is inconsistent.

At step 2, if you select another deck, with a small number of due review, then everything is allright.

###### Debug info
I'll update later when I've got my phone with me. I'm using the latest beta from the store.

###### Research
Asking the computer to check the collection and then doing a full sync from computer to ankidroid does not solve the problem.

According to Damien Elmes, https://anki.tenderapp.com/discussions/ankiweb/4273-collection-keeps-being-found-as-inconsistent the sync fails because «sanityCheck endpoint returns the differing counts in the JSON reply. The review due counts appear to differ.» 
This seems extremely consistent with the fact that numbers in anki are limited to 1000, while ankidroid shows arbitrarily great numbers. 

I'd try to fix it myself, but there is already a lot of PR I created which are still pending, so I guess I'll wait to see what happens with code I already submitted before writting more.

*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

Seems similar to https://github.com/ankidroid/Anki-Android/issues/5666

**Comment by mikehardy** [comment]
2.10alpha55 is out with the fix, as soon as Google is done processing it and starts delivery...

**Comment by mikehardy** [comment]
released in 2.9.6beta4
