### ISSUE TITLE
Dark themes use bad color for cloze templates

### ISSUE THREAD

**Issue by Erim24** [ankidroid/Anki-Android#5674]
###### Reproduction Steps

1. insert a note using cloze deletions
2. switch to night mode (same result for dark and black theme

###### Expected Result
cloze deletion with a well readable text

###### Actual Result
dark blue color used for the cloze deletion is hard to read and sometimes barely visible.

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
@Erim24, could I confirm whether this has been fixed for you?

This is what I see on 2.11alpha11:

![image](https://user-images.githubusercontent.com/62114487/83573254-f9677700-a522-11ea-9f28-c75940d7181d.png)
