### ISSUE TITLE
Anki 2.1 won't play audio file if there is a blank in the title

### ISSUE THREAD

**Issue by PandaPowerPaw** [ankidroid/Anki-Android#5676]
###### Reproduction Steps

1. Add audio file to card
2. 

###### Expected Result

Play audio in cards.

###### Actual Result

Audio file won't play.

The file is transferred to the card. It will be played once in card creating mode. After that, it won't be played again. Using "tools-check media" the audio file won't be recognized as used in a card and therefore it will be deleted.
Audio files (with spaces) which were added in version 2.0 and before are still played perfectly fine. It only affects newly added audio files with spaces in the title after switching to Anki Droid 2.1.

###### Debug info

Audio files: *.mp3

AnkiDroid
Version 2.1.15 (442df9d6)
Qt 5.12.1 PyQt 5.11.3

Installed add-ons:
Deck Stats
Deck name in title 21
ImageResizer
Mini Format Pack
Night Mode
Progress Bar
Progress Graphs and Stats for Learned and Matured Cards
Replay buttons on card
True Retention

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
The audio files are played perfectly fine, if the title of the file has no space in it. If there is a blank spot in the title, the audio file won't be played and after "check media" it will be deleted. Problem started with switching to AD version 2.1.

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! Unfortunately this is just the repository for the Android app, AnkiDroid. For the desktop app, you'll want to head over to https://anki.tenderapp.com/
