### ISSUE TITLE
Card browser: a difference with anki

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5680]
###### Reproduction Steps

1. In anki "add card" window. Click on "Cards...", 
2. Edit the basic type (card> options> browser appearance). Set "Override front template" to "{{Back}}"
3. Create a card c with front "Front", and empty back.
4. Synchronize with ankidroid
5. Open ankidroid's card browser,  and show "question"

###### Expected Result
In the question column and card c line, I expect the same thing as in anki's desktop: something empty

###### Actual Result
I see "Front"

##### Analysis
Anki's check whether there is a browser override value, and always respect it.
Ankidroid tries to respect it, unless the result is an empty string, in which case it uses the standard question. 

The reason why I'm bringing this problem which honestly is really not important is that I don't know whether you want to preserve it. I was trying to simplify browser's code, and I had a problem there. Because if I keep this feature, i'd do a small change to libanki, (since the part which computes the question/answer is in anki). Otherwise, I just would follow anki's code, that would be quite simpler, but this would make a (really small) change in ankidroid feature.
So I'd like to know whether I should follow anki (I believe that's what I should do) or if I should keep ankidroid's feature, which makes a slightly more complex code.

Note that the difference occurs in the case, which I believe to be rare, where the user used override a template, and that the overridden template show nothing while the normal template show something. This would be surprising actually; as in my example, where "overridden front template" was set to show the "back", while the real front template shows the "front"

**Comment by mikehardy** [comment]
I'd follow anki behavior as well, but I'm mainly stating that as a "taste check" to see if @timrae agrees and my maintainer taste is tuned

**Comment by mikehardy** [comment]
@Arthur-Milchior not sure if this is still an issue or not?

**Comment by Arthur-Milchior** [comment]
I believe it was closed when we stopped using `""` to mean "not computed" and used `null` instead. I won't try to reproduce as I expect it to be almost impossible to have this error except if you tries to create it
