### ISSUE TITLE
Answering with a remote bluetooth gamepad always shows "good" button highlight

### ISSUE THREAD

**Issue by cburroughs** [ankidroid/Anki-Android#5683]
###### Reproduction Steps

1. Use AnkiDroid with a bluetooth gamepad 
2. Press the `Y` button (aka `EASE_1` aka "again"), or any other answer button.
3. The color of the green "good" button is highlighted as if that button was  pushed, instead of "again" (the actual button pushed).

I have verified that the gamepad is actually sending the "Y" code with another app.  AnkiDroid appears to treat the answer correctly (adjusting when the card is due) despite the visual indication.  The colored dots across the top also appear correct.

###### Expected Result

When using my fingers and touchscreen, pressing one of the ease buttons results in the button I pressed turning it a different shade of the same color (highlighting which one was pressed).  I expect the same thing when using a gamepad.

###### Actual Result

The green "again" button is highlighted, regardless of which button is pressed.

###### Debug info

 * AnkiDroid Version = 2.10alpha24
 * Android Version = 9
 * ACRA UUID = 1d4a1744-66ec-42bc-b01f-fdec9ccd8f3a

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Very interesting - kudos especially for verifying the actual code and trying the alpha, plus determining that the results were fine though the visuals are off. Should help narrow it down during investigation

**Comment by david-allison-1** [comment]
Lets keep this for a while - would be a good first issue.

**Comment by cburroughs** [comment]
Hello bot. I have confirmed that the issue is still present in the v2.13alpha9

**Comment by david-allison-1** [comment]
I'm fairly sure that this isn't the wrong button being pressed, it's the focused button losing focus - the green of a non-focused button is lighter, which makes it appear that it's being pressed.

**Comment by david-allison-1** [comment]
Proposal: Move "focus the default answer" to an accessibility option in advanced settings. Default to off
