### ISSUE TITLE
Follow Android system-level dark mode settings

### ISSUE THREAD

**Issue by agentydragon** [ankidroid/Anki-Android#5685]
Hi. AnkiDroid has an app-specific dark mode that does not follow the system-level configuration present in newer versions of Android. Would you accept a up-to-standard pull request implementing automatically switching night mode on when Android system gets switched to night mode, and automatically switching night mode off when Android system night mode gets switched off?
If nobody has the bandwidth to fix this soonish, I might do it myself or maybe place a bounty on it.

###### Reproduction Steps

1. Start out with AnkiDroid in light mode, system in light mode
2. Turn on Android dark mode (e.g., using the quick settings bar in the notification bar)

###### Expected Result

AnkiDroid should follow the system-level dark mode settings and switch to dark mode.

###### Actual Result

AnkiDroid remains in light mode unless you manually switch it.

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by agentydragon** [comment]
According to https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#configuration_changes if an activity listens to the uiMode configuration change, it will get notified on night mode changes.

**Comment by timrae** [comment]
So how would we handle synchronisation between local and system level?
Would we hide the night mode switch when it's supported at the system
level?

**Comment by agentydragon** [comment]
I think that, long-term, the right solution would be to hide the night mode switch when on Android version that has system-level night mode. That's how I've seen so far most apps that support night mode handle it: just follow the system, not include their own custom switch.

For now, I propose the following change:

* Add a configuration check-box, "follow system night mode", disabled by default.
* Effect 1: If system night mode gets set to dark mode *and* AnkiDroid was in light mode before the change, flip AnkiDroid to dark mode.
* Effect 2: If system night mode gets set to light mode *and* AnkiDroid was in dark mode before the change, flip AnkiDroid to light mode.
* Effect 3: On app start, set AnkiDroid to the system theme option.
* Effect 4: Hide theme switch in AnkiDroid's navigation pane.

At this point I would be personally happy, because I could set the option on.

If someone wants to continue sometimes using AnkiDroid in mode not matching their system mode, they can keep doing that by keeping the option disabled and switching manually, as they would currently do.

One use-case to consider is if someone want to follow system setting changes (i.e., "if AnkiDroid is light and system is light and I switch system to dark, AnkiDroid should go dark"), but to also be able to sometimes flip just AnkiDroid to a mode not matching system settings (i.e., "after dark mode automatically changes, it should allow me to manually go back").
My proposal does not address this use-case. Users who use AnkiDroid like this will not be made worse off by my proposed change, since they can always just fall back to manually switching the mode, as they need to do now. But they won't reap the benefits of automatic mode switching.

If this setting proves useful, I would then propose enabling it by default for new installations.

Regarding onboarding existing users who don't happen to find the new option in settings, there can be a discussion later regarding whether we should, e.g., flip the logic from opt-in to opt-out, or even remove the app-level switch altogether for users of up-to-date Android.

**Comment by agentydragon** [comment]
(first sketch of having AnkiDroid's preference follow system setting in draft PR https://github.com/ankidroid/Anki-Android/pull/5686)

**Comment by timrae** [comment]
OK sounds good to me, let me know when the PR is ready to review

**Comment by mikehardy** [comment]
Keeping this one non-stale - it has an available PR in draft mode

**Comment by david-allison-1** [comment]
I'd like to suggest an alternate design from the proposed PR:

I'd like to take this on for 2.15 regardless of design decision taken.

----

* "Follow System Night Mode" will be disabled (and a toast will occur if attempted to be enabled) if the night mode status of the system can't be determined.

* Add a setting under "Appearance": `Follow System Night Mode`
   * Enable this by default
   * When this setting is enabled, gray out the night mode toggle and set it to the appropriate value from the system
   * When the night mode toggle is tapped when grayed out, inform the user that system night mode is followed and they should long press the toggle to change to manual mode
   * When system night mode changes, handle the config change
* Long pressing the night mode toggle when it is not grayed out will enable "Follow System Night Mode"

**Comment by mikehardy** [comment]
Mmm I like that. allows for discovery and easy override when people want it, defaults to follow. sounds good to me

**Comment by mikehardy** [comment]
Only slightly different from what David proposes, but with no long-pressing needed, and kicks it from the navigation drawer for Android 10+ where it is supported - from https://github.com/ankidroid/Anki-Android/issues/8150

> I think for Android APIs that support system dark mode the main "Night Mode" toggle should be removed from the navigation drawer, and we should extend DayNight theme. The settings should have a new "follow system" toggle, with our 4 themes unavailable if "follow system" is enabled, and the 4 themes available if "follow system" is disabled.
> 
> I think this would get rid of the MIUI issue and resolve all our dark mode issues at once.

**Comment by david-allison-1** [comment]
> Only slightly different from what David proposes, but with no long-pressing needed, and kicks it from the navigation drawer for Android 10+ where it is supported - from #8150
> 
> > I think for Android APIs that support system dark mode the main "Night Mode" toggle should be removed from the navigation drawer, and we should extend DayNight theme. The settings should have a new "follow system" toggle, with our 4 themes unavailable if "follow system" is enabled, and the 4 themes available if "follow system" is disabled.
> > I think this would get rid of the MIUI issue and resolve all our dark mode issues at once.

Does "follow system" on a stock Android actually change the UI automatically, or is this a MIUI specific feature?

On reflection (and now I have understanding with a recent phone with night mode toggles), I'd be happy with removing the toggle if the user has set "follow system". Possibly with a preference to re-enable it (manual mode).

Assuming that the auto UI change is MIUI specific (I think it is), then we still get value in selecting the theme style (dark/black) if "follow system" is enabled.

**Comment by mikehardy** [comment]
Good point re: selecting a "sub-theme" within dark mode (or light mode). So, theme selection (which is our list of subthemes, really) should be available at all times

It is almost as if with "follow system" you want to be able to specify the sub-themes independently, "dark theme to use if system is in dark mode:" etc

It's complicated to offer all the flexibility !

**Comment by bhatushar** [comment]
I would propose the following implementation:

1. Inside Navigation Drawer, replace "Night mode toggle" with a "Theme selector". When the theme selector is clicked, open an alert dialog prompting the user to pick a theme (system default, day mode, night mode).
2. If system default theme is selected, use the previously set sub-theme. Light or Plain for Day theme and Black or Dark for Night theme.

I think this is an efficient way to do this as it let the users quickly switch between themes. If you think it's practical, can I be assigned to this issue?

**Comment by AnuragGorkar** [comment]
> I would propose the following implementation:
> 
> 1. Inside Navigation Drawer, replace "Night mode toggle" with a "Theme selector". When the theme selector is clicked, open an alert dialog prompting the user to pick a theme (system default, day mode, night mode).
> 2. If system default theme is selected, use the previously set sub-theme. Light or Plain for Day theme and Black or Dark for Night theme.
> 
> I think this is an efficient way to do this as it let the users quickly switch between themes. If you think it's practical, can I be assigned to this issue?

This is a practical solution. I think instead of giving that option in the navigation bar and clogging it one could simply add it to the top of the prefrences menu as once applied the user is not likely to change the theme again

**Comment by bhatushar** [comment]
@AnuragGorkar I think it'll be better to keep it in navigation drawer so that the layout is consistent and doesn't confuse long term users.

**Comment by haran2248** [comment]
I have started working on this issue,Is it possible to assign me? @david-allison-1 @mikehardy

**Comment by haran2248** [comment]
I had a conversation regarding this with david few days back in discord i guess,He asked me to make a few changes in the PR that he made

**Comment by david-allison-1** [comment]
To remove ambiguity: I wrote a PR a while back which may be extended if the code is useful and it seems useful

My thoughts:

> On reflection (and now I have understanding with a recent phone with night mode toggles), I'd be happy with removing the toggle if the user has set "follow system". Possibly with a preference to re-enable it (manual mode).

* If a user's phone supports automatic night mode (>= Android 10):
* Select the theme based on the system night mode value
* Remove the "Night Mode" toggle
* Ensure that we handle config changes while inside the app
   
Rationale: If the user's phone supports auto-night-mode, then they can use the system-level toggle instead of the navigation drawer toggle. I believe in this case we can get away without a preference.

@mikehardy - confirming this design seems OK to you? I'm aware/concerned that we're not back-porting the feature to earlier versions of Android which may have vendor-specific dark mode.

**Comment by mikehardy** [comment]
I think that is close but still like the idea of a manual override in preferences (not on the navigation drawer). We manipulate colors in the app with a card color inverter in night mode and I think it's useful for users to be able to explicitly night mode within the app just in case.

Also, we have 4 themes not 2, so we need to allow the user to resolve them (OLED users want the "black" theme for instance but that is very high contrast so most users want dark, but you can't please both crowds with one setting).


So for phones that support automatic night mode
- remove the navigation drawer toggle
- add a new toggle in preferences to follow system night mode
  - add preference for dark theme to use when following system
  - add preference for light theme to use when following system
- previous theme preference becomes "manual theme selection" and they pick as they did before
- if they already have a theme preference set, observe that preference as "follow system" toggle is off and manual theme selection is on, with their existing preference?

It's a lot of choice to present but it's the only way I can think of to map the existing 4 themes (which are all important to some subset) into the new "system dark mode" world.

**Comment by david-allison-1** [comment]
@mikehardy 

> if they already have a theme preference set, observe that preference as "follow system" toggle is off and manual theme selection is on, with their existing preference?

Definitely - I was unclear

----

I don't see the use case where a user would often switch between "manual" and "auto", so I don't see the need for doubling up the "following system" theme and the "manual" theme. I'd presume that these would be the same values, and it saves adding two preferences.

----

Could we get analytics on the manual/auto selection preference? I'm of the opinion that we won't need it unless we're causing problems (as the manual toggle is replaced with a manual "night mode" OS toggle).

I hope that most of our users falling back to manual mode will stem from:

* Bugs in handling the night mode transition
* Bad power cables causing "battery saver mode" causing screen flickering

**Comment by mikehardy** [comment]
Let's copy someone elses multi-theme / system-follows UI/UX since they actually have UI/UX researchers :-)

I just saw this on GitHub as it is new, and they have the same problem - they have multiple themes people used to select manually, and now people want a "follow system" mode but they also want to specify exactly how.

They have a "Theme Selection" interface with a drop-down that has "Single Theme" or "Sync with System" as options.

With Single Theme selected, they have a display of all available themes with radio buttons and you pick one.

![ThemeSelect-manual-mode](https://user-images.githubusercontent.com/782704/117035127-9568a800-acc9-11eb-94b8-c1d3949c3485.png)


With Sync with System selected, they switch to showing two displays one for "Day Theme" and one for "Night Theme", and the active one gets badging saying it is currently active. Both of them have a little palette that lets you select which theme you want for Day or Night from all available themes.

![ThemeSelect-follows-mode](https://user-images.githubusercontent.com/782704/117035145-9ac5f280-acc9-11eb-9347-79bce7243881.png)


You can play with it here https://github.com/settings/appearance

Let's copy that and be done, it seems the most configurable (really important for our user base) and shows everything really well to me.

I consider our primary light and dark themes (not plain, not black) to be our default selections

We should *default* to follows system, with those 2 themes selected.

For any user that has a preference set to any theme, we should consider them to want "Single Theme" with their current theme.

**Comment by bhatushar** [comment]
@mikehardy that's kind of what I suggested as well in [my comment](https://github.com/ankidroid/Anki-Android/issues/5685#issuecomment-803809131).

**Comment by mikehardy** [comment]
Fantastic @bhatushar sorry if I didn't see that and note it, I was just struck by the GH design this morning when I was in github settings for a different reason and posted up the screen grabs without reading the most recent bits of the thread 🙈

**Comment by VishnuSanal** [comment]
@haran2248 Can you please confirm whether you're still working on this issue? If not, I'd like to work on this.

**Comment by VishnuSanal** [comment]
> @haran2248 Can you please confirm whether you're still working on this issue? If not, I'd like to work on this.

@david-allison-1 @mikehardy Letting this to your concern, shall I work on this issue?

**Comment by mikehardy** [comment]
Go for it!
