### ISSUE TITLE
Escaped HTML in deck options

### ISSUE THREAD

**Issue by alexanderadam** [ankidroid/Anki-Android#5687]
I hope it is a valid bug even [if I'm not able to reproduce it on Anki Desktop](https://github.com/ankidroid/Anki-Android/issues/5678#issuecomment-570063732). :wink: 

###### Reproduction Steps

1. Go to Deck options and look at the bottom

###### Expected Result

No escaped HTML

###### Actual Result

Escaped HTML

![Screenshot_20200103-133949_AnkiDroid](https://user-images.githubusercontent.com/372620/71723883-95833a00-2e2e-11ea-9bd1-1fe9bd34f403.jpg)

###### Debug info

AnkiDroid Version: `2.9.1`
Android Version: `9`
ACRA UUID: `79b69820-6975-4051-abdd-e6f15900be29`

###### Research

* [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
* [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
* [x] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
It's not really a bug, it's just that we do not support display of html in the deck options view of the deck description. If you want to see the rendered html, you need to go to the deck page (by tapping on the three numbers on the right-hand-side of the deck in the main deck list)
