### ISSUE TITLE
Clarity of blurry images improves not with zooming but with screen rotation

### ISSUE THREAD

**Issue by ronved** [ankidroid/Anki-Android#5691]
I have a deck with some screenshots of text/tables and they appear blurry which doesn't improve with zooming in but with screen rotation i.e. phone is horizontal. when both zooming in and screen rotation enlarge everything, why there is difference in clarity? I am sorry i don't know if this is something to be accepted or to be fixed.

###### Reproduction Steps

1. blurry image/picture media [when screen rotate is off i.e. phone is vertical]
2. tried zooming in when phone vertical but still blurry
3. when screen rotated i.e. phone is horizontal, same image no longer blurry

###### Expected Result
image not? blurry when zooming in

###### Actual Result
image blurry even after zooming in when phone is vertical i.e. screen rotation is off

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
How very strange! I'd expect zoom to produce more detail w/clarity any time, assuming the basic image has available pixels to show
