### ISSUE TITLE
Card browser loading eternally

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5694]
###### Reproduction Steps

1. Create decks A and B.
2. In deck A, put a single note of type basic.
3. In deck B, put 20 basic notes, containing using musics. 
4. Sync with ankidroid
5. Open the browser on deck A
6. Then on deck B.

###### Expected Result
When it ends loading, in deck A, the "loading" symbol should disappear.
In deck B, I would like the "loading" symbol to stop moving at some point. And potentially to see the file of the sound's name to appear.

###### Actual Result
In deck A, the symbol remains, 
![2020-01-04-124001_622x1151_scrot](https://user-images.githubusercontent.com/357361/71771425-64b70980-2eef-11ea-873c-5014bc81cb2a.png)ç

In deck B, the loading symbol turns 
![2020-01-04-124011_622x1151_scrot](https://user-images.githubusercontent.com/357361/71771426-67196380-2eef-11ea-82c3-1543154d1d51.png)
(I know that you can't see on the image that it turns)
And the question/answers are blank, which means that we don't have any informations about the card.

###### Debug info
I'm testing on master: d2fe7282a31be595d39eff171dfe4d05f6b21117
I had this problem for some time, but didn't really understand it until I read the card's browser code. 
The problem for deck B is that ankidroid assumes that if there is an empty answer string, it didn't yet load the values. While actually an empty string is an acceptable value, even in normal use of anki.
So I assume that, when the empty string is computed as answer, a white space " " should be used as the value of "answer" in the card, so that ankidroid knows that the computation did occur and is not loading anymore. That would be a solution which does not change a lot of the code.

Concerning files of music, I believe that adopting a solution similar to the solution used for images would be better than just removing the whole "[music:filename]" string.

Concerning the problem A, I don't yet know what causes it.

###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I have seen this happen, I actually have a deck that reproduces it but haven't had time to find the specific card that hangs up the rendering in the card browser - looks like you've solved most of the reproduction issue thought, which was the part I was stuck on

**Comment by timrae** [comment]
This would be relatively easy to solve automatically via the browser refactoring PR if you keep around both the `ArrayList<Long>` for the card IDs and the `ArrayList<Card>` for the actual cards. Then you can just check for null in the cards list instead of checking for empty strings, and pass an array of card IDs to the `DeckTask`. You could probably refactor all of this into a nice thread-safe data structure for maximum internet points.

**Comment by Arthur-Milchior** [comment]
Well, this bug is indeed related to #5684. That's how I finally understood what was going on.
It seems having a PR satisfying the requirement may takes some time. The solution I gave above would be really quick to implement (and actually not be hard to merge into #5684. So I was mostly thinking about doing an independant PR just to solve this.

**Comment by mikehardy** [comment]
I can no longer reproduce this, despite having a test deck that used to reproduce it in both ways the related PRs fixed (images, and empty answers). Thanks for fixing this @Arthur-Milchior - it's picked to 2.9.x and out as 2.9.6beta5 now where it just passed testing on my test collection and my main collection

**Comment by Arthur-Milchior** [comment]
I don't know enough about threads to know what should ideally have been done. However, I tried to follow the main idea here and create a data structure which keeps the id and the card itself together, and do only the loading required in https://github.com/ankidroid/Anki-Android/pull/6372
