### ISSUE TITLE
NullPointerException at ModelFieldEditor

### ISSUE THREAD

**Issue by anlalalu** [ankidroid/Anki-Android#5697]
###### Reproduction Steps

This crash is triggered by an automatic testing tool with this shell instruction:

adb shell am start -n com.ichi2.anki/com.ichi2.anki.ModelFieldEditor

###### Stack Trace

E/AndroidRuntime(21360): FATAL EXCEPTION: main
E/AndroidRuntime(21360): Process: com.ichi2.anki, PID: 21360
E/AndroidRuntime(21360): java.lang.NullPointerException
E/AndroidRuntime(21360): 	at com.ichi2.anki.ModelFieldEditor.setupLabels(ModelFieldEditor.java:161)
E/AndroidRuntime(21360): 	at com.ichi2.anki.ModelFieldEditor.onCollectionLoaded(ModelFieldEditor.java:124)
E/AndroidRuntime(21360): 	at com.ichi2.anki.AnkiActivity.onLoadFinished(AnkiActivity.java:286)
E/AndroidRuntime(21360): 	at com.ichi2.anki.AnkiActivity.onLoadFinished(AnkiActivity.java:42)
E/AndroidRuntime(21360): 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:476)
E/AndroidRuntime(21360): 	at android.support.v4.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:444)
E/AndroidRuntime(21360): 	at android.support.v4.content.Loader.deliverResult(Loader.java:126)
E/AndroidRuntime(21360): 	at com.ichi2.async.CollectionLoader.deliverResult(CollectionLoader.java:42)
E/AndroidRuntime(21360): 	at com.ichi2.async.CollectionLoader.deliverResult(CollectionLoader.java:12)
E/AndroidRuntime(21360): 	at android.support.v4.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:255)
E/AndroidRuntime(21360): 	at android.support.v4.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:80)
E/AndroidRuntime(21360): 	at android.support.v4.content.ModernAsyncTask.finish(ModernAsyncTask.java:487)
E/AndroidRuntime(21360): 	at android.support.v4.content.ModernAsyncTask$InternalHandler.handleMessage(ModernAsyncTask.java:504)
E/AndroidRuntime(21360): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(21360): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(21360): 	at android.app.ActivityThread.main(ActivityThread.java:5001)
E/AndroidRuntime(21360): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(21360): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(21360): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
E/AndroidRuntime(21360): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
E/AndroidRuntime(21360): 	at dalvik.system.NativeStart.main(Native Method)

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Crashes created by direct misuse of the app cause no damage and aren't possible in normal use, so are of academic interest only. I won't prioritize this personally but if you propose a PR we could merge it

**Comment by anlalalu** [comment]
Thank you for the reply, this issue is actually impossible in normal use.
