### ISSUE TITLE
A string on crowdin hasn't been reflected recently

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#5704]
The part hasn't been translated recently. 

![Screenshot_2020-01-08-21-15-21 resize trim](https://user-images.githubusercontent.com/10436072/71978537-ef389980-325e-11ea-9b91-cf63959a8e86.png)

![studied](https://user-images.githubusercontent.com/10436072/71979827-02993400-3262-11ea-9727-591c0da9446c.png)

I suspect that the association between the translation on Crowdin and the app was broken for some reason.
###### Debug info
AnkiDroid = 2.10alpha30 
Android = 5.0

**Comment by david-allison-1** [comment]
Fixed as of 2.11alpha11

**Comment by snowtimeglass** [comment]
@david-allison-1 Thank you for your support.
