### ISSUE TITLE
Text can't be vertically centered in container

### ISSUE THREAD

**Issue by ogassav** [ankidroid/Anki-Android#5706]
###### Reproduction Steps

The code shows text on the color background. The text is expected to be **vertically centered** vs. its background, like this:

**###### Expected Result**

![image](https://user-images.githubusercontent.com/59234350/72103773-33dd3700-332a-11ea-9b53-07d2ae32386d.png)

As you can see it works perfectly in Anki Desktop.

**###### Actual Result**

But not in AnkiDroid! Same deck opened:

![image](https://user-images.githubusercontent.com/59234350/72103843-5bcc9a80-332a-11ea-8fc8-cb284013908c.png)
Text is shifted to the _top_ of its container.

**###### Useful details**

**Top** line is `<span>` (green-bordered) inside `<div>` (red-bordered).
**Middle** line is a _standalone_ `<div>` with background kept.
**Bottom** line is a _standalone_ `<div>` **without** background.  

3 variants were tracked to ensure the problem doesn't come from any particular text property (e.g. background) or code element (e.g. `<span>`).

Please find attached (in ZIP):

**1)** TEST.html - automatically generated card, when Debug Mode was switched ON. Being opened in any browser shows **correct** styling.

**2)** TEST.apkg - sample deck with the above mentioned 3 variants of code.

[TEST.zip](https://github.com/ankidroid/Anki-Android/files/4042465/TEST.zip)

###### Debug info
AnkiDroid Version = 2.9.1
Android Version = 8.1.0
ACRA UUID = e1249345-0bd6-4585-a7b1-203183348585

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by ogassav** [comment]
Guys, can someone please check the attached sample deck and **confirm** you have the same problem? Thank you!

**Comment by mikehardy** [comment]
sorry @ogassav there's not that many active maintainers, like literally just 3 I think? And at least for me I'm very careful with the time I allocate to AnkiDroid because I'm in a startup and it's crazy 🤷‍♂ - haven't had time to check and may not

**Comment by moqi-Git** [comment]
@ogassav I have same problem with your deck. I will try this tonight.

**Comment by mikehardy** [comment]
@moqi-Git -> :trophy:  :smile:

**Comment by moqi-Git** [comment]
@ogassav @mikehardy 
I think this is NOT a bug. 
```
.variant_with_span>span {
    font-size: calc(0.25em + 1.5vw);
}
```
Viewport Width (vw) is based on the width of the viewport. If you change Chrome's window to same size as Android device, you will see this:

![image](https://user-images.githubusercontent.com/36124184/72501037-d9376400-3870-11ea-81bc-d3b7357d9c75.png)

**Comment by ogassav** [comment]
@moqi-Git @mikehardy 

On your screenshot the inscription is clearly moved to the bottom, i.e. is _not centered_ too.
I've played with "no-viewport" code and here's what i got with font stated in fixed **EM** value:

![image](https://user-images.githubusercontent.com/59234350/72505356-11727e80-3840-11ea-81b0-ceaffd6c5dc0.png)

Items are moved closer to the top.

Here's the result of fixed **PX** value:

![image](https://user-images.githubusercontent.com/59234350/72505420-30711080-3840-11ea-987c-5c2aa8f5b69c.png)

Items are close to what may be called "vertically centered".

So looks like the problem follows **fixed** values too... Finally, VW is a _width_ parameter and if Anki viewport's width is smaller (e.g. 780px) than the width of Android device (e.g. 800px), this should **not** be a problem, as CALC function will just calculate font size (in my case) based on VW = 780px and that's all. Why deformation of the result instead?

**Comment by moqi-Git** [comment]
@ogassav I don't know too much about css, maybe you can try "flexbox"(not sure)

**Comment by ogassav** [comment]
@moqi-Git it's not about CSS at all. The code itself is correct and all the software displays it correctly (see my initial screenshots), **except** Anki, which means smth is wrong on Anki side.
Though i'm not a programmer myself i'd check the webview functionality. If Anki uses the system one (Chrome by default) - is there discrepancy in "webview <-> Anki" **data exchange**? Are there any peculiarities of webview's **vertical** data processing (_the core of the problem in my this case_) vs. **horizontal** one? This is where i'd have started from.
FYI: `background` is element's **own** property, so aligning it with parent element is like aligning roof of the house with the building itself - they must be aligned by default. `Flexbox` and other alternatives are used to align _independent elements_ (i.e. "houses") among themselves.

**Comment by ogassav** [comment]
Guys, how can i help (being a non-programmer) = what can i do to investigate this above-mentioned problem so that together we can solve it?

**Comment by david-allison-1** [comment]
@ogassav 

Sorry, wasn't contributing to AnkiDroid when this first came about. You can compare the two via Chrome Developer tools:

**AnkiDroid**
* `Settings - Advanced - Enable HTML/Javascript debugging`
* Connect your phone via USB
* Browse to chrome://inspect/#devices

**Anki**
https://ankiweb.net/shared/info/31746032

**Comment by ogassav** [comment]
@david-allison-1 

Thank you for the feeedback. As the problem relates to AnkiDroid **only** (the sample deck attached to my first message of the thread looks fine in Anki Desktop) i followed the first part of your instructions (related to AnkiDroid), but i have Opera (not Chrome Mobile). So when i enter the string `chrome://inspect/#devices` it automatically changes to `opera://inspect/#devices` with a resulting error 404. Am i doing smth wrong?

**Comment by david-allison-1** [comment]
@ogassav  The URL I provided is Chrome-only, I don't think it works in Opera. You'll need to Google for an alternate solution (if one exists) for Opera. 

Alternately, let me know if you want me to take a quick look.

**Comment by ogassav** [comment]
@david-allison-1 

Installed Chrome Android, turned on "Allow USB-debugging" in phone settings and "Allow JavaScript debugging" in AnkiDroid. No result. The Chrome #devices page won't open. :-( Damn.
I'm sorry to disturb you, but maybe if you have time one day you could kindly have a look on your device?
The sample deck, which highlights the problem in AnkiDroid, is attached to the first message of the thread.

Alternatively i can use your advice #2, but its for AnkiDesktop, where there's no bug of this kind.

**Comment by david-allison-1** [comment]
@ogassav Sure!

My phone took a few tried to get "USB Debugging" to stick, I also needed to run it while locked, which is a partial security risk.

**Comment by david-allison-1** [comment]
Hi @ogassav, I'm not sure what the problem is:

Here is a screenshot from Chrome on my Desktop, and the first textbox is not vertically centered.

![image](https://user-images.githubusercontent.com/62114487/80832353-69ad7080-8be4-11ea-8784-c788da96f6a7.png)

Here's a screenshot from Anki 2.1.24: 
![image](https://user-images.githubusercontent.com/62114487/80832524-babd6480-8be4-11ea-9623-0307849eb577.png)

**Comment by ogassav** [comment]
Hi @david-allison-1 ,

have a look at those screenshots please...

**Opera Desktop browser** - text in every textbox **is** vertically aligned:

![1 - Opera](https://user-images.githubusercontent.com/59234350/80836150-6d48f380-8bf4-11ea-820f-3fd064725fe0.jpg)


**Anki Desktop v.2.1.15 (442df9d6)** - text in every textbox **is** vertically aligned:

![2 - AnkiDesktop](https://user-images.githubusercontent.com/59234350/80836272-aed99e80-8bf4-11ea-9aaf-31ae1e99ee4a.jpg)


**Opera Mobile browser** - text in every textbox **is** vertically aligned:

![3 - Opera Mobile](https://user-images.githubusercontent.com/59234350/80836316-c4e75f00-8bf4-11ea-868a-b0251f6aff0d.jpg)


**AnkiDroid v.2.9.6** - text in **EVERY** textbox **is NOT** vertically aligned:

![4 - AnkiDroid](https://user-images.githubusercontent.com/59234350/80836762-bbaac200-8bf5-11ea-8e21-a4757f6211e0.jpg)


The CSS itself is simplified to its maximum, so i can hardly imagine this is the problem of the lousy code. Even more so - the problem exists in AnkiDroid only, which is very suspicious. 

Just in case - I have a _default_ (Chrome) webview in my phone developer's settings. Didn't switch it to Canary or whatever else.

What so you think? ;-)

**Comment by david-allison-1** [comment]
@ogassav I really appreciate the time you've taken. Thank you.

I've just downloaded Opera and zoomed into the page, the field is bottom aligned. Is this the case for you?

![image](https://user-images.githubusercontent.com/62114487/80837920-b0549800-8bef-11ea-8dd3-fa0089bdf955.png)

But... this is bugging me, I think the issue is going to be with relative font size calculation in AnkiDroid, let me delve deeper

**Comment by david-allison-1** [comment]
It seems to be due to window size in Anki Desktop, the issue also occurs when I make the Anki Desktop window close to as small as possible.

**Comment by ogassav** [comment]
@david-allison-1 

Hi! Looks like I've solved the problem and I feel myself like an idiot frankly saying, as possibly it was my mistake somewhere - i will investigate where exactly of course. Please refer to [this](https://jsfiddle.net/u6dq9g8p/) JSFiddle for examples and find attached the updated deck (which is the copy of mentioned JSFiddle).

**SAMPLE-1** (see JSFiddle) construction is the most "complicated" in terms of number of parameters involved. In order to find the source of the problem, I started to remove parameters one by one, so **SAMPLE-2** is a bit more simple than **SAMPLE-1**, etc., etc.

Now (with the new code written today from scratch) _every_ (!) sample **is** vertically centered in both AnkiDesktop and AnkiDroid:

![1](https://user-images.githubusercontent.com/59234350/80860268-d9643f80-8c66-11ea-9388-afa3482b8ef1.jpg)

![2](https://user-images.githubusercontent.com/59234350/80860272-dec18a00-8c66-11ea-8df4-4716fd0b5b5b.jpg)

I'm really VERY sorry i took your invaluable Friday evening time yesterday. :-((((

[TEST.zip](https://github.com/ankidroid/Anki-Android/files/4567396/TEST.zip)

**Comment by mikehardy** [comment]
Glad you arrived at a solution! This comes up periodically and is useful in the sense that I believe we can authoritatively say at this point AnkiDroid does not mess with your formatting in this way. We can refer here for people to look and self-help before maintainer time is spent again
