### ISSUE TITLE
Feature: Randomize background color or font

### ISSUE THREAD

**Issue by elgalu** [ankidroid/Anki-Android#5710]
### Feature Request: Randomize visual clues

It would be useful if the app could randomize certain presentation attributes before showing a flash card.

#### Why
Because if the app always present the Q&A visually the same way the user starts memorizing the card visually though what we need is to memorize text/concepts.

The app could randomize, for instance:
- background/foreground colors
- font type and size
- text location

**Comment by adamwolf** [comment]
I think I have seen people do this in Javascript, actually.  I wonder if
there's a good tutorial for that!

**Comment by mikehardy** [comment]
yeah, easy in javascript in your card template? https://stackoverflow.com/a/1484514/9910298

**Comment by mikehardy** [comment]
Definitely would like more functionality done in javascript de-coupled from core development if possible
