### ISSUE TITLE
Using attributes in <img> tag causes field to be detected as having no content

### ISSUE THREAD

**Issue by syphoxy** [ankidroid/Anki-Android#5711]
###### Reproduction Steps

1. Create note with a field containing `<img class='custom-class' src='path/to/image.jpg'>`
2. Use `{{#Field}}<div id='field'>{{Field}}</div>{{/Field}}` in card template.

###### Expected Result

to be rendered in card's output HTML:

```
<div id='field'><img class='custom-class' src='path/to/image.jpg'></div>
```

###### Actual Result

`Field` seems to be detected to have no content and therefore is entirely excluded from the card's output HTML.

After some experimentation, I have discovered that if there is any displayable HTML surrounding the HTML tags, the field is rendered.

example: `<img ...>a` would display as expected.
example: `<img ...>&nbsp;` does not.

the reason why I know this is because I enabled the "HTML / Javascript Debugging" setting and I am inspecting the `AnkiDroid/card.html` file directly after rendering.

###### Debug info

```
AnkiDroid Version = 2.9.1

Android Version = 10

ACRA UUID = c989d65a-83be-4bb9-b5e3-659d99f87985
```

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

check.

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

can't seem to find anything pertaining to img tags here.

[x] I have searched for similar existing issues here and on the user forum

I have tried Googling for the issue, I have checked the GitHub issues and I have also checked the Google Groups for AnkiDroid as listed on the support page but I couldn't find anything relevent. I apologize if the issue has been reported already.

**Comment by mikehardy** [comment]
I think was fixed just recently and should be present if you sign up for alpha versions of the app following this https://docs.ankidroid.org/manual.html#betaTesting

possible duplicate issue #5166
I think the fix #5647

Closing provisionally but if you get the latest alpha, and verify you have it checking the version at the bottom of advanced preferences, and you still reproduce it, then obviously we'll re-open and re-examine

Cheers

**Comment by syphoxy** [comment]
thanks for the response!

I was successfully able to get the Beta release but I wasn't able to get the Alpha release despite joining the Alpha group after joining the Beta program.

after reading the diffs, my only issue with #5647 is that it only bandaids the the issue by improving the <img>-only regex. for example, this would completely filter out <svg> or anything constructed with only <div> (two things I have tried to use lately.)

**Comment by mikehardy** [comment]
🤔 after signing up for the alpha group, if you go back in the play store app to the beta tab and update there, you should see an update available, and it should be the alpha verifiable as mentioned in advanced preferences

If you've got a better approach for the bug PRs are most welcome :-) 🙏

**Comment by syphoxy** [comment]
apologies if that came across the wrong way. I just wanted to start a dialogue regarding potential knowledge and decisions that led to the current implementation. I'll try to wrap my head around the code and open a PR if I can think of anything reasonable.

RE: alpha channel: I was able to get the alpha update now and the original issue is definitely solved in that release. thanks!

**Comment by mikehardy** [comment]
no apologies needed :-), but PRs are gold. Glad you're on the alpha and your problem as it stands is solved, that's valuable feedback
