### ISSUE TITLE
Wrong ETA time for due cards with Scheduler V 2

### ISSUE THREAD

**Issue by hikerito** [ankidroid/Anki-Android#5713]
###### Reproduction Steps

I've been using Ankidroid for about a month daily, and after syncing to the desktop version it consistently reports my average time per card is about 25 seconds (based on about 5K reviews I've done so far). During all that time the ETA estimate was about right: if I had 50 cards to study, it predicted about 25 min. It was all with the default scheduler. Then a few days ago I switched to Scheduler 2.

It seems that after enabling Scheduler 2, the ETA time is calculated very strangely. At the moment, I have 5 cards to study and it says it'll take me 11 minutes. It's not a big deal but still, somewhat inconvenient. At first I thought it based the calculation on the "maximum time to study a card" setting but checked and the current due cards are from the decks where the setting is on 60 sec.
(I do have some decks that are set to 120 sec but there are no due cards in them at the moment). so I'm confused.

I must say I'm not very experienced with Ankidroid so maybe I don't understand something. I also don't feel comfortable switching the scheduler back and forth to experiment: It says it'll reset my learning cards if I switch tback to v.1  and almost all of them are in learning so no way do I want to start them all over again. 

My version of Ankidroid is 2.9, special version "A" (to co-exist with the regular one - which is also installed on my phone but I'm not using it at the moment).

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! Can you attempt to reproduce this on the 2.10alpha versions? You may sign up for pre-releases in the Play app and then specifically for the alpha group with these instructions: https://docs.ankidroid.org/manual.html#betaTesting

I know there has been some v2 scheduler work recently, thus the suggestion - might be fixed already if you look at recently closed PRs in the github repo

**Comment by hikerito** [comment]
Alright so I've installed the 2.10alpha30 and the issue is there.

**Comment by mikehardy** [comment]
Thank you very much for trying that, sorry the bug still persists

**Comment by mikehardy** [comment]
@hssm not sure if you have time to look at this, but there appears to be some difference between time estimation on v1 and v2 scheduler?

**Comment by hssm** [comment]
The ETA function is identical in both versions so you won't find a difference if you switch schedulers. 

The function [looks at the last 7 days](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/SchedV2.java#L2635) in the revlog history and uses an average of rep time for certain reps. It's possible you have an outlier or two dragging the average up and skewing the estimate. It should clear up in a week on its own if long reps aren't a regular thing for you.

If you are keen, you can use the [Advanced Browser add-on](https://ankiweb.net/shared/info/874215009) on the desktop and add the `Previous Duration` column to find the slowest rep.

**Comment by hikerito** [comment]
@hssm Thank you for your explanation. I've installed the Advanced Browser and there are indeed some cards of 2min in Previous Duration. It's perfectly possible of course that something else coincided with my switching to V2. I had a problem with some cards returning to the 'new' status after I deleted a filtered deck - apparently a well known issue but I wasn't aware of that so learned about it the hard way. Then I switched to V2.  Then I noticed the problem with the ETA. 

On the other hand, all my "end of the day" stats at the bottom of the screen are very consistent (and I do pay attention to them): I do about 200 reviews daily and they take about 80..100 min. Sure some cards take 2 min but then others take 2 seconds. How come that the daily average is about 25..30 sec - EVERY DAY and yet the average of the last 7 days used for ETA is 4 times that? The inflated ETA is shown on any number of cards: 200, 100, 50, 2... no matter how many due cards are there, I've got the ETA figure that's roughly twice the number of cards, while it should be about a half. Right now I've got 41 cards due and ETA says it'll take me 102 min. And at the bottom of the screen it says that I did 199 cards today in 100 min. 

In my deck I've got 295 card with Previous Time below 10 sec ; 365 cards between 10 and 30 sec;
160 between 30 sec and 1 min; 100 between 1m and 1m30s; zero cards between 1m31s and 2m32s; 33 cards between 2m32s and 2m59s; and finally 2 (two) cards between 3m30 and 3min54s. I'm not sure what it all means but it just doesn't look like something that should produce an ETA of 102min for 40 cards.

Anyway I'll be monitoring the stats and ETA and will let you know what I see.

**Comment by slesniak** [comment]
This looks like the same issue as #5619

**Comment by hssm** [comment]
Looks like it's wildly inaccurate on mine too. To be honest, I've never really paid attention to this number. Looking closer at the code I'm not even sure how it's even supposed to work, and I can see at least one error in it.

Anyway, I think I'll come up with something better.
