### ISSUE TITLE
In deck description, ignore what is in style and script tag

### ISSUE THREAD

**Issue by BlueGreenMagick** [ankidroid/Anki-Android#5715]
###### Reproduction Steps

1. Set deck description to `<script>a=1</script>`
2. View deck description

###### Expected Result

Deck description should be blank, instead of `a=1`

###### Actual Result
Deck description is shown as `a=1`. Only `<script>` and `</script>` gets removed

###### Debug info
AnkiDroid Version = 2.9.2beta4

Android Version = 4.4.2

ACRA UUID = 34141f01-867f-4ea4-9f19-6625973b167e

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
@david-allison-1 wins the internet points here 🏆  :-), should be in the next alpha in a day or three. Cheers!

**Comment by mikehardy** [comment]
2.10alpha47 is published with this and will be available when google is done processing it 🚀
