### ISSUE TITLE
svg, png images not shown in css grid

### ISSUE THREAD

**Issue by fjuzs** [ankidroid/Anki-Android#5716]
###### Reproduction Steps

1. Edit 'Basic' note type and add
```
.dummy_name_grid {
    display: grid;
    grid-template-columns: 1fr;
}
```
to the styling section.

2. Minimal example card:
Front:
```
<div class="dummy_name_grid"><div> AA</div><div> B[$]=[/$]B</div><div> AA</div></div>
```
Back:
```
<div>AA<br></div><div>B[$]=[/$]B</div><div>AA</div>
```

###### Expected Result

svg or png image be shown between BB on Front card.

###### Actual Result

AnkiDroid:
Nothing inbetween BB, but if the image file is missing a missing file icon is shown.
![Screenshot_20200116-111438_AnkiDroid](https://user-images.githubusercontent.com/56027570/72518397-8b613280-3855-11ea-9000-d594afdc2a98.png)

Anki:
Shown as expected.
![Screenshot_20200116_111838](https://user-images.githubusercontent.com/56027570/72518403-8f8d5000-3855-11ea-8ff2-9aa45ea26c0b.png)

##### Furthermore:
Tested it for svg and png images. It is not latex related, since it also does not work for random svg or png images.
card.html created by enabling HTML/Javascript debugging:
```
<!doctype html><html class="mobile android linux js">    <head>        <title>AnkiDroid Flashcard</title>        <meta charset="utf-8">        <link rel="stylesheet" type="text/css" href="file:///android_asset/flashcard.css">        <link rel="stylesheet" type="text/css" href="file:///android_asset/chess.css">        <link rel="stylesheet" type="text/css" href="file:///android_asset/mathjax/mathjax.css">        <style>        @font-face {font-family: "OpenSans"; font-weight: bolder; font-style: normal; src: url("file:///android_asset/fonts/OpenSans-Bold.ttf");}
@font-face {font-family: "OpenSans"; font-weight: lighter; font-style: italic; src: url("file:///android_asset/fonts/OpenSans-LightItalic.ttf");}
@font-face {font-family: "OpenSans"; font-weight: lighter; font-style: normal; src: url("file:///android_asset/fonts/OpenSans-Light.ttf");}
@font-face {font-family: "OpenSans"; font-weight: normal; font-style: italic; src: url("file:///android_asset/fonts/OpenSans-Italic.ttf");}
@font-face {font-family: "OpenSans-Regular"; font-weight: normal; font-style: normal; src: url("file:///android_asset/fonts/OpenSans-Regular.ttf");}
@font-face {font-family: "OpenSans"; font-weight: bolder; font-style: italic; src: url("file:///android_asset/fonts/OpenSans-BoldItalic.ttf");}
@font-face {font-family: "OpenSans"; font-weight: bolder; font-style: normal; font-stretch: condensed; src: url("file:///android_asset/fonts/OpenSans-CondensedBold.ttf");}
BODY {font-family: 'OpenSans';font-weight: normal;font-style: normal;font-stretch: normal;}
        </style>        <script src="file:///android_asset/mathjax/conf.js"> </script>        <script src="file:///android_asset/mathjax/MathJax.js"> </script>        <script src="file:///android_asset/scripts/card.js" type="text/javascript"> </script>    </head>    <body class="card card1 ankidroid_plain_mode">        <div id="content">        <div class="question" id="qa"><style>.card {
 font-family: arial;
 font-size: 20px;
 text-align: center;
 color: black;
 background-color: white;
}

.dummy_name_grid {
    display: grid;
    grid-template-columns: 1fr;
}</style><div class="dummy_name_grid"><div> AA</div><div> B<img class=latex src="latex-d5eb8726a34932d28103ce7ce17456421222603f.svg">B</div><div> AA</div></div></div>        </div>    </body></html>
```
Opening this card on desktop or Android with Firefox, with the image file in the same folder, yields the expected result, without the image file in the folder it shows a missing file icon.

###### Debug info
```
AnkiDroid Version = 2.9.2beta4

Android Version = 9

ACRA UUID = 04ca01a2-bca7-4509-a70e-bd7a891211b4
```

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Can you try the HTML debugging methods here to see why? https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by fjuzs** [comment]
Thanks, I somehow missed the step using Chrome developer tools. The image had 0 × 0 px size. Setting `max-width` to `none` solved the problem.

I. e. adding 
```
.chrome img {
    max-height: none;
}
```
to the styling section.
