### ISSUE TITLE
Corrupt Database

### ISSUE THREAD

**Issue by ezzick** [ankidroid/Anki-Android#5719]
###### Reproduction Steps

1. It's a good version on AnkiWeb, and I can study with it.
2. When I reload and rewrite base on AnkiDroid, it is OK.
3. I study 1 card (from any decks) and try to synchronization. But I have message "Database is corrupted"
4. I checked database, and I removed AnkiDriod from phone and set it again. But it doesn't help me.

###### Expected Result
I want to do synchronization, because it is wonderful program. And I have used it about 1 year. I love it! It's very helpful.

###### Debug info
AnkiDroid Version = 2.9.1
Android Version = 9
ACRA UUID = 42a00c21-a0cd-40dd-9b97-a0b461cb491a

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Strange - can I you try the alpha versions? A few things have been fixed and 2.10alpha is actually nearing release and all the developers use it daily for study - it should be stable https://docs.ankidroid.org/manual.html#betaTesting

If you can reproduce it there we might be able to fix it

Unfortunately the ACRA UUID doesn't show any crash reports so I don't have any info to go on there

**Comment by ezzick** [comment]
Thank you so much! I tried alpha version, and synchronization is done.

**Comment by mikehardy** [comment]
fantastic! thanks for following up
