### ISSUE TITLE
Error syncing media data

### ISSUE THREAD

**Issue by canedio** [ankidroid/Anki-Android#5720]
###### Reproduction Steps

After I updated to Anki 2.1 I get the following error after syncing on AnkiDroid:
----
AnkiDroid
Collection synchronized

Error syncing media data

no such table: meta (code 1): ,
while compiling: select dirMod from meta
----

Tried checking database/media, tried re-installing aswell

###### Actual Result
While it does sync, I do not know if there's  a deeper problem in there. Hard to know practically as I have tens of thousands of cards.

###### Debug info
MacOS 2.1.15
Ankidroid 2.9.1

###### Research

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X] I have searched for similar existing issues here and on the user forum

Thanks!

**Comment by mikehardy** [comment]
Hi there @canedio ! Can you try the solutions provided in last couple comments here? https://github.com/ankidroid/Anki-Android/issues/3125

One of them speculates an underlying cause but the media database delete will be a likely fix either way

**Comment by canedio** [comment]
very late but it works,if anybody will ever look for this. delete - collection.media.db.old
- collection.media.ad.db2 and resync. thanks @mikehardy
