### ISSUE TITLE
SVG not attainable in Javascript through XMLHTTPRequest

### ISSUE THREAD

**Issue by Kamadake** [ankidroid/Anki-Android#5722]
###### Reproduction Steps

1. Use XMLHTTPRequest() in JS to obtain "svg" data and inject into HTML DOM

###### Expected Result
To receive the data of SVG file hosted in collection.media in javascript

###### Actual Result
CORS error since file requests are made through the file protocol.

###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

--------------------------

Probably it's a pretty redundant question but I wanted to ask you all here perhaps you have a better idea or you'll just tell me it's not possible.

I wanted to try having a go at what Kanji Colorizer as an add-on but instead as Javascript code inside the card and I got that to work inside the desktop variant but I can't get it to work in the mobile variant because of how their web views work differently. Desktop is a locally hosted website and Mobile uses the file protocol. And since I'm working with XMLHTTPRequest to get the SVG element from an SVG file, I get the CORS error.

The reason I want to inject the SVG element into my actual DOM is so that I can manipulate the `<path>` elements to colour them in and also to animate them. I tried using `<svg><use>` and `<object>` but I still couldn't access the elements inside the SVG.

Thanks for your time!

**Comment by mikehardy** [comment]
I just did something similar in #5795 and I was able to do inline SVG with CSS coloring ?

**Comment by Kamadake** [comment]
hey @mikehardy ! for me the issue isn't the rendering of an SVG, but more the retrieval of an SVG. Initially I was making an XMLHTTPRequest to retrieve the SVG and then place the element in the DOM but on Android a web page is opened using the file protocol so the XMLHTTPRequest gets blocked.

Instead what I've done is work by grabbing the SVG element and storing the element in Base64 within the flash card which then lets me decode it in Javascript and do what I please with it. I just need to make it as an add-on to Anki by grabbing what Kanji Colorizer did but with the methodology I wish to use (https://github.com/Kamadake/kanji-base64izer)
