### ISSUE TITLE
Cannot combine right-to-left and left-to-right language on the same note

### ISSUE THREAD

**Issue by yairmishnayot** [ankidroid/Anki-Android#5723]
###### Reproduction Steps

1. Start to write a note in Hebrew,
2. Switch to English and start to write
3. Switch back to Hebrew and keep writing

###### Expected Result
See the note exactly as I wrote it

###### Actual Result
The note is mixed up

Original:
![Screenshot_2020-01-18-23-57-49-916_com ichi2 anki](https://user-images.githubusercontent.com/13747679/72671232-d8105d80-3a4f-11ea-8e3f-86e87767f80a.jpg)

Result:
![Screenshot_2020-01-18-23-57-54-121_com ichi2 anki](https://user-images.githubusercontent.com/13747679/72671239-ff672a80-3a4f-11ea-9e93-a46a2991da11.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Closing this in favor of #8259 - a huge amount of work was done recently, this may already be fixed, and if not we are using that to track remaining items

**Comment by eginhard** [comment]
See also the manual, it sounds like this should already work correctly: https://docs.ankidroid.org/#RTL
Maybe the fields just have not been set correctly as RTL.
