### ISSUE TITLE
When I change font, Bold doesn't apply

### ISSUE THREAD

**Issue by Cho-jin** [ankidroid/Anki-Android#5726]
###### Reproduction Steps

**Setting -> Appearance ->  change system default -> open sans regular (etc...)**

Can't apply bold...

###### Expected Result

Font : system default

![default](https://user-images.githubusercontent.com/59984527/72849888-2d1bd000-3ceb-11ea-97ec-3f3738da9e84.png)

###### Actual Result

Font : open sans regular (etc...)

![noto sans](https://user-images.githubusercontent.com/59984527/72849893-2f7e2a00-3ceb-11ea-9b7e-e4469ff59c8e.png)

###### Debug info

Ankidroid 2.9.2 beta4

android version = 4.4.4

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by moqi-Git** [comment]
@Cho-jin 
I changed the font to OpenSans-Regular and preview one desk. Here is the result. 
![image](https://user-images.githubusercontent.com/36124184/72892264-1019e800-3d51-11ea-819e-3690b4d478ca.png)

Can you provide more info about the deck and your device？Thanks.

**Comment by Cho-jin** [comment]
> @Cho-jin
> I changed the font to OpenSans-Regular and preview one desk. Here is the result.
> ![image](https://user-images.githubusercontent.com/36124184/72892264-1019e800-3d51-11ea-819e-3690b4d478ca.png)
> 
> Can you provide more info about the deck and your device？Thanks.

I found solution.

I use css @font face.

Thanks!
