### ISSUE TITLE
If there are multiple audio files in question, question audio files are played when answer is shown even when replay question option is unticked. 

### ISSUE THREAD

**Issue by PraveenMuthu22** [ankidroid/Anki-Android#5730]
###### Reproduction Steps

1. Create a card with 2 or more audio files in the question. (front).
2. Have a single audio file in the answer. (back). [screenshot](https://imgur.com/a1PL2G4)
3. Untick the deck option "Replay Question" [screenshot](https://imgur.com/3Uff6MO)
4. Review the card with Ankidroid.

###### Expected Result
Before the answer is revealed, the audio files in the question are played.
When the answer is revealed, only the audio files in the answer are played.

###### Actual Result
When the answer is revealed the audio files in the question except for the last file is played prior to the audio file in the answer is played.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi @PraveenMuthu22 ! I think we have a fix for this but it is not merged yet - https://github.com/ankidroid/Anki-Android/pull/5584 - I just tagged it for review priority to see if we can get it in soon

**Comment by mikehardy** [comment]
This should be fixed in 2.9.4 releasing now. After the you get the update re-check and we can re-open if it's not fixed
