### ISSUE TITLE
Collection crashes in version 2.9.2 when using triple colon (":::") in deck name

### ISSUE THREAD

**Issue by mtrevix** [ankidroid/Anki-Android#5734]
This is a known issue in the beta testers group (see #5603). However, it seems the bug fix didn't reach the final 2.9.2 version. This is aggravated by the fact that in some devices (such as using Android 4.4.2) previous versions don't sync anymore with Anki server (is that due to the new encryption method?).

###### Reproduction Steps

1. select a subdeck, for example "anydeck::subdeck" (appears as "anydeck > subdeck" in the collection)
2. rename it as "anydeck:::subdeck" (notice the three colons instead of two)

behaviour in previous versions (AnkiDroid), and 2.1.15 (Anki Desktop, using Ubuntu, Windows and Mac) and previous: new deck appears as "anydeck > :subdeck"

behaviour in versions 2.9.2: whole collection crashes and error message appears.

###### Personal note

Personally I have renamed the decks having triple colon to be able to keep working, but this should be fixed soon, especially because there are collections working in Anki Desktop that might stop working in AnkiDroid.

###### Research

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by timrae** [comment]
As you said, it's been fixed in 2.10 alpha series... It's unlikely we'll release a 2.9.3 sorry.

**Comment by mtrevix** [comment]
Ok, I thought it was important to let you know, because now the bug is exposed to a huge number of users. However, what intrigues me is that you say you will not release a 2.9.3, why is that? What is going to be the next version then?

**Comment by timrae** [comment]
Oh is this a bug in 2.9.2 that's not present in 2.9.1?

**Comment by timrae** [comment]
I think we're almost ready for 2.10 to go to beta

**Comment by mtrevix** [comment]
Yes, that's what I was saying. The bug started in 2.9.2beta4, see #5603.

And the worst is that the collections do work in Anki Desktop. The only AnkiDroid version they crash is 2.9.2 (apart from beta and alpha versions). The fix is really simple, and has been done already.

**Comment by timrae** [comment]
Ok thanks for the heads-up.

**Comment by mikehardy** [comment]
if @nicolas-raoul is interested in me test-driving a release, perhaps this is the perfect opportunity to hand-hold me through the process for a 2.9.3? one focused change on an already stable release, that fixes a crash. silver platter setup

**Comment by timrae** [comment]
Cherry-picked into new `hotfix-2.9.3` branch
