### ISSUE TITLE
[AnkiWeb] Review does not update the remaining number of questions correctly

### ISSUE THREAD

**Issue by lukaszcr** [ankidroid/Anki-Android#5739]
###### Reproduction Steps

1. At the beginning of the day open an Anki deck in Chrome.
2. Go through the reviews
3. The number of outstanding questions does not get updated correctly

###### Expected Result

The number of outstanding questions should reduce with every correct answer.

###### Actual Result

The blue number does not change.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
AnkiWeb is a separate team. This is an Anki-compatible but separate app, Android only. For support from them you want https://anki.tenderapp.com/
