### ISSUE TITLE
Display a dialog explaining why permission is necessary before requesting external storage

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5740]
###### Reproduction Steps

1. Initial app install
2. Start app
3. 

###### Expected Result

A dialog explaining why external storage permissions are needed

###### Actual Result

Just a raw dialog asking for external storage

This is coming up more frequently in play store reviews these days as people are finally paying more attention to privacy

Ideally this should re-use our existing dialog class infrastructure - nothing really special needed, with just an "ok" button after the explanation (they can deny the permission if they like but there's no real action to take on a simple information dialog). String should be internationalized of course.

The logic would go in the AnkiDroidApp class I believe, in the show startup dialogs etc method

Somewhat related to #5304 where we could perhaps get rid of external storage permission entirely

**Comment by atmask** [comment]
@mikehardy if this enhancement is still open I'd like to take a look into it.

**Comment by mikehardy** [comment]
@atmask yes please and thank you! :pray:

**Comment by mikehardy** [comment]
@atmask are you looking into this? If not - @david-allison-1 this could be a really quick win, it's a complaint growing in frequency as people become more privacy minded, on the way to an actual fix along the lines of #5304

**Comment by david-allison-1** [comment]
@mikehardy Happy to, as a short term fix before the introduction tutorial as long as I'm not stepping on any of @atmask's work.

Has any brainstorming been done on the reasons/wording we can use?

IMO, we don't really need the permission straight away. 

Big collections really won't sell to new users, and we don't want to scare them with "we'll use loads of space".

Explain what we do with it, backups, media, recordings.

I guess promises that we're open source, used and trusted by millions, developed by many volunteers and promise not to take your data would work better.

**Comment by mikehardy** [comment]
We do need it straight away - the collection *always* lives on the sdcard and an empty one is created and initialized at first startup. That fact should change with whatever work resolves #5304 but for now it's just fact

No brainstorming whatsoever has taken place, but yes - it is used to store the entire collection including media, as well as automated backups. No attempt to access files outside of the configured storage directory is made, and since it's open source you may verify this claim at any time or similar

**Comment by david-allison-1** [comment]
@mikehardy Sorry for the ambiguity, was referring to #5304. We shouldn't need it for new users, we currently do.

Will get a PR in tomorrow if there's no reply.

**Comment by atmask** [comment]
@david-allison-1  Feel free to take this issue. I unfortunately haven't been able to look into it.

**Comment by david-allison-1** [comment]
@atmask Cheers for the blessing. Will get to it

**Comment by mikehardy** [comment]
2.10alpha54 released just now has this whenever google delivers it to you
