### ISSUE TITLE
Fullscreen mode: swiping down to show the menu interferes with "swipe down" gesture 

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5741]
###### Reproduction Steps

1. Set Setting > reviewing > fullscreen mode to: hide system bars and answer buttons
2. Set Settings > gestures > swipe down to: answer button 2 or anything else
3. Review a card in fullscreen, try to show the menu by swiping down from the edge of your phone

###### Expected Result

The menu is shown

###### Actual Result

The menu is shown for a millisecond, then the defined swipe gesture is activated (in my case: mark the card with button 2 and go to the next card)

Possible solution: swipe gestures should not be activated when swiping from the edge of the screen.

This issue is the result of pull request https://github.com/ankidroid/Anki-Android/pull/5628 which solved an issue that I created myself (https://github.com/ankidroid/Anki-Android/issues/5415) :man_facepalming: 

Obviously the reason for the margins in fullscreen was to prevent the swipe down gesture to interfere with the show menu gesture. But since those margins lead to a misalignment of card contents and touch area, it is good that the margins got removed with pull request 5628.

So there should be another way to prevent the "show menu gesture" with the user defined swipe down gesture.

###### Debug info
AnkiDroid Version = 2.10alpha33

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mjuzikfrik** [comment]
Confirm to have the same issue.

**Comment by david-allison-1** [comment]
Looking for comments on the following design. This model is specific to fullscreen: "hide system bars and answer buttons"

**Terms:**

* Navigation Deck - The bar at the top of the UI displaying the deck name and settings.
* [System] Status Bar - The bar at the top of the phone displaying 
* [System] Navigation Buttons - The (optional) soft navigation buttons on a phone.
* Anki UI - Show Answer, Navigation Deck, System Status Bar, and Navigation Buttons
* The top - the pixels where the status bar would normally be.
  * What about a notch?
* The bottom defines the bottom pixels where the Navigation Buttons would be
  * OR, a set limit, in case there is no answer buttons

**Design:**

* When no UIs are showing
  * An initial swipe from the top should display the Anki UI
  * A second swipe from the top should display the status bar
  * An initial swipe from the bottom should display the Anki UI
  * This is the only mode where taps register
* When the Anki UI is showing
  * Horizontal swipes and taps inside the WebView should close the status bar and perform the action
  * Vertical Swipes ~10 pixels inside the WebView will register should close the status bar and perform the action 
  * A tap on the WebView should close the Anki UI without taking an action  ❗️ -this differs from the logic when the Status Bar is shown.
  * Answer buttons and options work
* When the Status Bar is showing
  * No Gestures will be processed

**Questions:**

* Do we want to hide the system status bar if the user is using a phone with a notch? Related: #5206 #5469

**Comment by Anthropos888** [comment]
Current behavior:
Swipe from the top shows the Navigation Deck, the System Status Bar and the Anki UI answer buttons (don't know about the phone's Soft Navigation Buttons since my phone still has hard buttons).

Swipe from the bottom up doesn't show any UI.

![Screenshot_20200320-085322](https://user-images.githubusercontent.com/45192213/77145414-c87db700-6a88-11ea-9ac5-bc558a3cc0f8.png)

As for me, that's OK and no need to change anything here. It's important that users just need to swipe down once to see *all three*: the Anki buttons (in order to answer), the status bar (in order to get to the phone's quick settings with another swipe down) and the Navigation deck (in oder to flag/mark the card etc.).

Actually the only thing that needs to be fixed here is that the swipe down gesture from the top doesn't interfere with the user defined swipe down action. These swipe actions should only be triggered within a ~10px margin of the webview (without creating a misalignment of the card elements as in https://github.com/ankidroid/Anki-Android/issues/5415)

Additionally, the implementation of your point 
- An initial swipe from the bottom should display the Anki UI 
Would be a very nice feature in order to provide one handed use / thumb control. User's wouldn't need to swipe down from the top with the other hand in order to answer cards.

**Comment by david-allison-1** [comment]
@Anthropos888 Thanks for the input! I have soft buttons and it's frustrating at the moment because I expect to be able to swipe up to get the navigation bar.

The new Android versions define gestures from the left/right, so I'll need to rethink a few things

Could you took a few more looks over the next few days, I'm looking for heavy criticism in the design, and it's much better to do it now than discuss whether it's "good enough" after it's coded

Thanks again,

**Comment by Anthropos888** [comment]
> When the Status Bar is showing
> * No Gestures will be processed

@david-allison-1  If it's possible to block (vertical) gestures when the status bar (or Anki UI) is showing, then that would be a way to fix the problem.

As for now, when swiping down from the top, the Navigation Deck, the Status Bar and the Anki UI appear first and *after that* the user defined action for "swipe down" is executed. So if we could just (temporarily) stop/intervene all gesture actions after the Navigation deck / Anki UI / Status bar fully loaded, then the problem would be solved.

**Comment by david-allison-1** [comment]
@Anthropos888 I'll try to get to this sometime later this week. 

I'll want to refactor and test the gesture system so we fix this one and for all, and will want to pre define the design and implementation of this to make sure I'm not wasting time. It's definitely possible to get this right.

**Comment by david-allison-1** [comment]
Hi @Anthropos888,

I've got a review in to fix this: #5871, but would like your input.

I'm unsure about what to do with the whiteboard when reviewing in full screen mode: If the user draws from the top of the screen, should a line start to be drawn (as it may trigger the Anki UI to appear)?

It's a hard thing to reason about:

We start drawing as soon as the user touches the whiteboard. We know the start coordinates of the drawing, but at that time, we don't know whether it's a swipe that would trigger the Anki UI.

I've currently got the functionality to start drawing, and continue as the Anki UI is shown. But it would be equally as easy to define a margin, and block the user from drawing when a swipe starts inside the margin.

What behaviour would you expect?

**Comment by Anthropos888** [comment]
@david-allison-1 Hey, good to hear you got a fix already. As for the whiteboard: I would always expect the Anki UI to appear when I swipe down from the top. Nothing else.
The whiteboard can be triggered within a margin of 10px or 20px from the top. I think 99.99% of whiteboard users don't need to start painting exactly from the very top of the screen.
 
The problem with the whiteboard in fullscreen is that it can only be activated/deactivated from the menu - thus users need to swipe down first in order to show the menu. So this gesture should not do anything else than showing the Anki UI.

As for the recognition of gestures and whiteboard inputs WHILE the Anki UI is shown: I'd expect the Anki UI to disappear as soon as I use gestures/taps/whiteboard. But I'd have no problem if the UI stays active and would be closed only by a single tap on the screen. Just choose the easiest way to implement that.

**Comment by Anthropos888** [comment]
Thanks @david-allison-1 ! Works great as of 2.11alpha11
This bug was so annoying for me during reviews, thanks a lot for fixing it!

**Comment by david-allison-1** [comment]
@Anthropos888 Thanks for the feedback! Sorry it took so long.
