### ISSUE TITLE
Does anyone here speak German?

### ISSUE THREAD

**Issue by MuhamHS** [ankidroid/Anki-Android#5742]
Hello everyone,

I made a post about my anki problem a month ago (https://github.com/ankidroid/Anki-Android/issues/5708). 
Unfortunately my problem has not solved until today. I still can't use Anki properly and trying to find a solution online I come across mostly English websites, (though there is a german version, but it doesn't fit my problem - The custom study deck). 
I would like to explain my problem in german, maybe I can make it more understable and also, I can understand the explanation better. 

Anki is such an amazing tool! My English and my Japanese Studies slowed down a lot this last month of not studying properly with it. It makes such a difference if one studies without it. I hope I can use Anki again. 

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
unsure if anyone speaks German here. I would try the public mailing list, there is probably someone.

I don't want a separate issue cluttering the repo so I'm going to close this one
