### ISSUE TITLE
Show link to last inserted note in the Add note screen

### ISSUE THREAD

**Issue by leoh79** [ankidroid/Anki-Android#5746]
###### Reproduction Steps

1. Click Plus sign
2. Add
3. Type in your note
4. Check Mark (save)

At this point, I would like to be able to see a link to the last inserted note to be able do re-edit it again without having to navigate through the search tool.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Exactly what would that look like? Link how, where?

**Comment by leoh79** [comment]
In the desktop, when we add a new card there is a button called _History_ which allows me to jump directly to the Browse to edit the previous inserted card. This is very handy. I was just figuring out how to create this same feature in the Android App. Just after inserting a new card I wish I could be able to easily locate and re-edit it again (could be link to the last inserted card, a history button as in the desktop version) without having to get out of the Add Card screen to perform a search on the database.

**Comment by mikehardy** [comment]
interesting - I was not aware of that desktop feature, thanks for the extra detail

**Comment by redwarp** [comment]
Currently, the app displays a toast tat displays "1 card added". How about displaying a snackbar instead, with an edit button? The snackbar would disappear after a while, or can be dismissed, but would provide a quick way to go to the card if the author of the card is second guessing themselves??

**Comment by david-allison-1** [comment]
This would be useful for me. @mikehardy mind if I self-assign?

**Comment by david-allison-1** [comment]
Unassigning for now - more complex than I'd expected as the activity has 3 purposes: adding, editing, and changing note type

**Comment by BrayanDSO** [comment]
Closed in favor of #11213 (which the desktop editor would do as well)
