### ISSUE TITLE
Make sure template editor does not add cards to dynamic decks

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5765]
From #5757 - 

Investigate the template editor adding cards to dynamic decks 

1. Create a dynamic deck
1. Make sure that deck is selected in the deck list
1. use the floating action button plus sign to add a note
1. in the add note screen hit the template editors list of cards to open template editor
1. in template editor hit the eyeball icon to preview (should work)
1. back out of preview, and add a new card in the template editor
1. save the new card and go back out to add note screen
1. save the note
1. examine the note in the browser and see what deck is assigned to each card for the note

Expected result is that the dynamic deck should not have any of the new cards in it

**Comment by timrae** [comment]
This isn't the issue I was suggesting to look into it. This is not really related to the crash video on Google Play. I was assuming that [this](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java#L500) is the code path that the crash was coming from.
