### ISSUE TITLE
Integrate plugin "Image Occlusion Enhanced" into Ankidroid

### ISSUE THREAD

**Issue by luo-chuan** [ankidroid/Anki-Android#5766]
User just can make image cloze card on PC. If the Ankidroid integrate the plugin "image occlusion enhanced", user can also make image cloze card on smart phone.  
The website of "image occlusion enhanced": https://ankiweb.net/shared/info/1374772155  
DEMO:  
![image occlusion enhanced](https://raw.githubusercontent.com/glutanimate/image-occlusion-enhanced/master/screenshots/ankiweb.png)

**Comment by mikehardy** [comment]
Can't happen for technical reasons read the FAQ sorry

**Comment by infinyte7** [comment]
I have implemented this.
https://infinyte7.github.io/image-occlusion-in-browser/
View this for usage
https://github.com/infinyte7/image-occlusion-in-browser

**Comment by mikehardy** [comment]
:exploding_head:
