### ISSUE TITLE
Sync: download media for selected notes only

### ISSUE THREAD

**Issue by fizzybiz** [ankidroid/Anki-Android#5767]
I have limited storage space on my Android, so I've got AnkiDroid set to not sync media.

But some cards depend on an image to answer the question.  Is it possible (or could it be a new feature) to only sync media for some selected cards, from the browser say?

*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I am sorry I don't think this is possible. It is possible to see in the FAQ how to put the collection on external storage
