### ISSUE TITLE
Deleting a note in AnkiDroid does not delete from AnkiWeb

### ISSUE THREAD

**Issue by hg2581** [ankidroid/Anki-Android#5769]
###### Reproduction Steps
1. Check number of cards in a deck.
2. Delete a note in AnkiDroid.
3. Check for the note being deleted on AnkiWeb after syncing as well as the number of cards in the deck which should now be less.

###### Expected Result
Note deleted.

###### Actual Result
Note not deleted in AnkiWeb.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by hg2581** [comment]
It seems I have misspoken, I tried it again and it seems to sync correctly between devices with AnkiWeb as the backend.

**Comment by mikehardy** [comment]
Good to hear, I was not looking forward to troubleshooting something as integral as this and finding a problem 😅

**Comment by hg2581** [comment]
On February 22, 2020 6:17:58 AM EST, Mike Hardy <notifications@github.com> wrote:
>Good to hear, I was not looking forward to troubleshooting something as
>integral as this and finding a problem 😅>
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/ankidroid/Anki-Android/issues/5769#issuecomment-589946424

Yes, I am not sure why it did not seem to work for me initially. If I find any problems I will ask to have it reopened, however, I have decided that my workflow will suspend the note rather than delete it.
