### ISSUE TITLE
Typo in French Translation

### ISSUE THREAD

**Issue by PierreQc** [ankidroid/Anki-Android#5771]
[######](url) Reproduction Steps

1. There is a small typo in French Translation of the Stats interface.
2. The Word "apprentissage" is miswritten with "apprantissage"
3. Thanks.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Translations are done like so: https://github.com/ankidroid/Anki-Android/wiki/Contributing#translate-ankidroid

And they are synced "periodically" - they have not been in a little while and it's on the list of things to do for the last 2.9 release at least, before 2.10

**Comment by PierreQc** [comment]
Thanks.

 

De : Mike Hardy <notifications@github.com> 
Envoyé : 22 février 2020 14:56
À : ankidroid/Anki-Android <Anki-Android@noreply.github.com>
Cc : PierreQc <pierre.l.bergeron@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [ankidroid/Anki-Android] Typo in French Translation (#5771)

 

Translations are done like so: https://github.com/ankidroid/Anki-Android/wiki/Contributing#translate-ankidroid

And they are synced "periodically" - they have not been in a little while and it's on the list of things to do for the last 2.9 release at least, before 2.10
