### ISSUE TITLE
Mathjax cloze problem..

### ISSUE THREAD

**Issue by Cho-jin** [ankidroid/Anki-Android#5775]
###### Reproduction Steps

`\(M=1\)`
`{{c1::problem}}`
`\( \dfrac{x}{{{c1::y}}}\)`

###### Expected Result
![2](https://user-images.githubusercontent.com/59984527/75413797-e9f7f100-5969-11ea-94be-6d1a91312877.png)

###### Actual Result
![3](https://user-images.githubusercontent.com/59984527/75413800-ecf2e180-5969-11ea-943d-afa2627a4443.png)

###### Debug info

PC Anki OK, but ankidroid2.9.4 X.

###### Research
*Enter an [ x ] character to confirm the points below:*

[x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
@adamwolf are you able to see anything obvious here? @Cho-jin I see an image for the first example, but nothing for the second example, so I believe there might be a problem - cloze + mathjax is very difficult to get right - but I'm not 100% of the different.

Separately, can you follow the instructions here and make sure (by checking in advanced preferences at the bottom) that you are on the alpha versions? https://docs.ankidroid.org/manual.html#betaTesting

Any fixes we incorporate will be in the alphas first, that way you will be set up to test them and confirm we fixed the issue

Thanks!

**Comment by adamwolf** [comment]
Thanks for tagging me in! It really helps me not have to watch every
Ankidroid issue :)

Has anyone tried this on desktop Anki?  If not, that would be an essential
thing to know before diving into this.

**Comment by Cho-jin** [comment]
> @adamwolf are you able to see anything obvious here? @Cho-jin I see an image for the first example, but nothing for the second example, so I believe there might be a problem - cloze + mathjax is very difficult to get right - but I'm not 100% of the different.
> 
> Separately, can you follow the instructions here and make sure (by checking in advanced preferences at the bottom) that you are on the alpha versions? https://docs.ankidroid.org/manual.html#betaTesting
> 
> Any fixes we incorporate will be in the alphas first, that way you will be set up to test them and confirm we fixed the issue
> 
> Thanks!

**Comment by Cho-jin** [comment]
My mistake, closed...ㅜㅜ
