### ISSUE TITLE
mathjax cloze problem........

### ISSUE THREAD

**Issue by Cho-jin** [ankidroid/Anki-Android#5776]
###### Reproduction Steps

`\(M=1\)`
{{c1::problem}}
` \( \dfrac{x}{{{c1::y}}}\) `

###### Expected Result

![2](https://user-images.githubusercontent.com/59984527/75413991-730f2800-596a-11ea-8ce7-909ae2f51636.png)

###### Actual Result

![3](https://user-images.githubusercontent.com/59984527/75413994-760a1880-596a-11ea-9fb8-8eafb2048c0a.png)

###### Debug info
PC Anki is OK,
but ankidroid 2.9.4 is not OK

###### Research
*Enter an [ x ] character to confirm the points below:*

[x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

**Comment by adamwolf** [comment]
OK.  It is not obvious to me, but my basic steps are to create this as a test case, and then open the debugger and step through it.  I won't be able to tackle this for a few days--tackling a tough deadline in a few weeks.
