### ISSUE TITLE
Error: SD-Card full

### ISSUE THREAD

**Issue by wsigel** [ankidroid/Anki-Android#5777]
###### Reproduction Steps

1. Open AnkiDroid
2. Error message appears (see screenshot)
3.

###### Expected Result
no error message when opening up the application

###### Actual Result
the error message that pops up says the sdcard is full but I only have an internal card with 4.5 GB and 3 GB are unused, If I click the error message away the app works without any problems. I've
uninstalled several times, deleted all files, reinstalled, synced with my ankiweb account but always get the same error message. Unfortunately I don't know any more which version of AnkiDroid I had been using before..
![Screenshot_2020-02-26-23-05-34](https://user-images.githubusercontent.com/10357745/75587019-dc2f9200-5a75-11ea-81f6-481dc1968072.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.9.4
Android Version = 4.1.2
ACRA UUID = f98c070c-9503-42e0-ac56-57945c4315e10997300010811492417371100237

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there, this sounds suspiciously like the FAQ entry about old androids and filesystem limitations

**Comment by wsigel** [comment]
The only FAQ entry I found about filesystem limitations on old androids is this one:

> Unfortunately there is a limitation on the number of files which can be stored in one folder on the FAT filesystem used by default on older Android devices and many removable storage cards. You may notice this if you have many thousand media files in your collection.

Not sure whether you're talking about this one. However my AnkiDroid folder only uses up 2,17 MB and contains only 11 files and 1 folder. That folder containing the media collection only has 4 jpg files and a total size of  130 KB - so I don't think that this is causing the problem.

**Comment by mikehardy** [comment]
strange I'm not able to find anything that seems right - the UUID is too long but if I trim it to be the right length nothing comes up, and there are no matching looking reports for the combo of android 4.1.2 and ankidroid 2.9.4 around the time of this report

Can you do one more uninstall / reinstall to reset the ACRA UUID, send it here, make sure you have turned on error reporting, and try it one more time?

Also, are you storing things on external storage? If so, that might be the problem in some subtle way - it's one of the reasons we don't officially support it (we'd like to, but it is very device-specific and was too much of a support load)

**Comment by wsigel** [comment]
so Android Version = 4.1.2
ACRA UUID = f37faae2-2a4e-40f9-b2a7-bcbb828785fd

as I said previously I do NOT use external storage. I've reinstalled now for the 5th time - still the same error. Also I noticed that after the install the entry for the installation path says:
/sdcard/AnkiDroid

However that path doesn't exist. On my phone the only one existing - and where the app actually installs - is:
/storage/sdcard0/AnkiDroid

Besides the mentioned error everything else is working fine.

**Comment by mikehardy** [comment]
Thanks for the extra information @wsigel - unfortunately I still don't have a crash report, but with the extra information it might be enough to reason through the issues here. I'm glad at least it appears to be working

**Comment by mikehardy** [comment]
Hi @wsigel we just merged #5830 and I'm about to release it in 2.9.6beta2 - if you get set up to receive beta builds now this might be fixed for you once 2.9.6beta2 is delivered to you? https://docs.ankidroid.org/manual.html#betaTesting

It was already released for our earlier testers as 2.10alpha51 and appears to be working fine

**Comment by wsigel** [comment]
I've installed the beta release but the error is not fixed - still the same error message as mentioned above.

**Comment by mikehardy** [comment]
Sorry - I have not released 2.9.6beta2 yet - still in local testing, please confirm the version number at bottom of advanced prefs after the update to see

**Comment by wsigel** [comment]
You're right - only got the beta1. So I'll wait until further notice from you. Thanks

**Comment by david-allison-1** [comment]
I'm getting this on my API16 emulator, might be worth looking into

**Comment by mikehardy** [comment]
the emulators fill up super quickly, they come with very tiny storage. I used them on purpose to test the error pathways of the syncing code last time I went through it, as it is so easy to fill them and put them in an error state
