### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by denghailong123** [ankidroid/Anki-Android#5781]
希望能优化一下UI，正如您所看到的，这款软件的UI的确不怎么漂亮

**Comment by mikehardy** [comment]
I am sorry, but we collaborate in English on github, is it possible for you to translate this and post your issue in English?

**Comment by mikehardy** [comment]
(to be clear: I am not asking for perfect English, an automated translation is probably fine!)

**Comment by MuhamHS** [comment]
I believe she/he doesnt like the user interface of anki and asks for options how to make it nicer. But since I used online dictionary my information is not accurate.

@denghailong123 

你必须用英语问. 不一定是完美的. Google translate 你可以用

**Comment by MuhamHS** [comment]
I believe she/he doesnt like the user interface of anki and asks for options how to make it nicer. 
But since I used online dictionary my information is not accurate.

@denghailong123 

他们不懂中文. 你必须用英语问. 不一定是完美的. Google translate 你可以用 :)

**Comment by mikehardy** [comment]
If that's the case, this is duplicate #5126 and it's the sort of thing that needs work, not requests, so I'll provisionally close it
