### ISSUE TITLE
Hidden (suspended) card state is not stored

### ISSUE THREAD

**Issue by l-g** [ankidroid/Anki-Android#5787]
Note that I use Ankidroid in another language than English. The literal translation of the menu option is "hide" but I'm pretty sure that it correlates to "suspend".

###### Reproduction Steps

1. Suspend a card in Ankidroid
2. Sync both the phone and the desktop
3. Search for is:suspended on desktop (I also tried this in Ankidroid, with the same result, but I am not sure if Ankidroid supports this type of searches?).

###### Expected Result
A list of the cards that was suspended in Ankidroid

###### Actual Result
No cards are suspended.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
This may in fact be a translation issue. There is also a "bury" which might correlate more to what you think of as "hide". You might try "is:buried". AnkiDroid supports this search, it should work. If it doesn't work on desktop then it's a usage error of some sort, likely related to the translation. On desktop you should be able to search for one of the particular cards and check out all of the details about it to see what state it is in

**Comment by l-g** [comment]
Weird, my action bar doesn't look like the description here https://docs.ankidroid.org/manual.html#_action_bar_3

I only have star and undo button (and an "open menu button", where there is only one option "hide", which is "bury" - suspend is missing).

**Comment by mikehardy** [comment]
settings -> reviewing -> app bar buttons is where this is customized

It is varies per device because the app bar will show as many buttons as it can depending on screen size then either "overflow" or just not show what does not fit. But it is all user customizable

**Comment by Anthropos888** [comment]
In order to prevent translation issues, the phone's system language could be temporarily set to English. Also, there's a menu item "filter suspended" in the card browser which shows all suspended cards, no search term needed.

**Comment by mikehardy** [comment]
Also if I'm wrong we can reopen but I believe this is resolved now?
