### ISSUE TITLE
Feature request: Compatibility with Anki 2.1.20 TTS field feature

### ISSUE THREAD

**Issue by p4nix** [ankidroid/Anki-Android#5793]
Hello,

this is my feature request to add compatibility to the new Anki 2.1.20 TTS support. Please note that it was done in a rush since I have a deadline approaching.

https://apps.ankiweb.net/docs/manual.html#text-to-speech
https://github.com/ankitects/anki/search?q=tts&unscoped_q=tts

Please note that my card does not make use of the tts voice/speed settings, which would ideally be included as well.

###### Reproduction Steps

1. Use [Test.apkg.zip](https://github.com/ankidroid/Anki-Android/files/4297041/Test.apkg.zip)
 - test card employing the use of a {{tts en_GB:Front}} to on-the-fly generate a TTS with the contents of the front field

###### Expected Result
According to https://apps.ankiweb.net/docs/manual.html#text-to-speech, there should be a play audio button, the text in the {{tts en_GB:Field}} will not be shown and the audio is automatically played when reviewing.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/7038116/76061573-1f14cc80-5f84-11ea-93c9-73e46b3d1b5e.png">

###### Actual Result
- it doesn't generate an audio button
- it doesn't automatically play the TTS
- it shows the content of the field, which it isn't supposed to do

###### Research
[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Thanks @p4nix I appreciate your taking the time to log this

**Comment by DaltonThompson** [comment]
One could convert the new 2.1.20 TTS syntax into the old syntax. Essentially, `{{Front}}{{tts de_DE:Front}}` becomes `{{Front}}<tts service="android" voice="de_DE">Front</tts>`.

As I understand it, one could grab a string surrounded by `{{tts ` and ending in `}}`, interpret the first characters (ending before a colon`:` or a space ` `) as the old syntax "voice". Characters after the colon `:` would be the field name, which must be passed as a string e.g. `Front`, NOT `{{Front}}`. All other characters (if included, e.g. `voices=Apple_Otoya,Microsoft_Haruka`) would be ignored, as they have information pertaining to MacOS or Windows.

**Comment by p4nix** [comment]
Thanks for looking into this issue!
I myself have downloaded the AnkiDroid sourcecode to look into this, but I am afraid my limited knowledge of coding and limited amount of time I could spend for it didn't allow me to find a solution. Please note that your solution would only be a "dirty fix" (no offense, it would help me out personally with that issue) - but ideally, it should generate the standard voice button by saving the audio temporarily, as I understand it works on Anki desktop. Otherwise it wouldn't really be ecosystem compatibility :)

**Comment by david-allison-1** [comment]
Spec: https://github.com/ankitects/anki/blob/0ecc189a9bbac8c62f0b9a5145e52074d05e515f/qt/aqt/tts.py#L1

Some Impl: 
https://github.com/ankitects/anki/blob/1524e7dcacead2a552197c7ae8e8dd1ad14bfd36/rslib/src/template_filters.rs#L189-L193

https://github.com/ankitects/anki/blob/898801ebdae716bba997da9e4902ed4e4fa4094d/rslib/src/text.rs#L66-L74

**Comment by david-allison-1** [comment]
Basic flow:

* Parse `{{tts en_US voices=Bob,Jane:Field}}` from template and convert to `[anki:tts][en_US voices=Bob,Jane]text[/anki:tts]`: [tts_filter](https://github.com/ankitects/anki/blob/1524e7dcacead2a552197c7ae8e8dd1ad14bfd36/rslib/src/template_filters.rs#L78-L84)
* Convert from `[anki:tts]` into `[anki:play:q:0]`: [extract_av_tags](https://github.com/ankitects/anki/blob/898801ebdae716bba997da9e4902ed4e4fa4094d/rslib/src/text.rs#L120-L139)
  * This is also been done for `[sound:]` tags
  * This converts it into a list of `AVTag`, and the textual representation references the index of this list.
  * Two lists are made, one for the question, one for the answer.
* The list of `AVTag` is stored in the card: [render_card_from_context](https://github.com/ankitects/anki/blob/6ecf2ffa2c46f2501ddbc3fd778035e715399a98/pylib/anki/template.py#L166-L187), [render_card](https://github.com/ankitects/anki/blob/6ecf2ffa2c46f2501ddbc3fd778035e715399a98/pylib/anki/template.py#L109-L129), [question_av_tags](https://github.com/ankitects/anki/blob/351d8a309f7d3c0cae7f818313b1a0e7aac4408a/pylib/anki/cards.py#L117-L121)
* A card is responsible for its template rendering: [render_output](https://github.com/ankitects/anki/blob/351d8a309f7d3c0cae7f818313b1a0e7aac4408a/pylib/anki/cards.py#L126-L134)
* The reviewer passes the AVTag in the card to `sounds.av_player`: [replay_audio](https://github.com/ankitects/anki/blob/eec3fcf87a88da3dbe2bad83a17ec87e3fa9106c/qt/aqt/reviewer.py#L33-L40)
* `aqt.sounds.av_player` is an abstraction over a list of players. These are set up to accept an `AVTag`,  and rank it [setup_audio](https://github.com/ankitects/anki/blob/bfb1d5c5f55eacdf9b71397ebc7fd71671ad3d03/qt/aqt/sound.py#L631-L639) [_best_player_for_tag](https://github.com/ankitects/anki/blob/bfb1d5c5f55eacdf9b71397ebc7fd71671ad3d03/qt/aqt/sound.py#L158-L170)
* Ranking logic: [voice_for_tag](https://github.com/ankitects/anki/blob/0ecc189a9bbac8c62f0b9a5145e52074d05e515f/qt/aqt/tts.py#L67-L84)
* `.play` is invoked on the player, 
----

* Add `{{tts-voices}}` field: [on_tts_voices](https://github.com/ankitects/anki/blob/0ecc189a9bbac8c62f0b9a5145e52074d05e515f/qt/aqt/tts.py#L126-L141)

----

**Notes**

A worrying method is [temp_file_for_tag_and_voice](https://github.com/ankitects/anki/blob/0ecc189a9bbac8c62f0b9a5145e52074d05e515f/qt/aqt/tts.py#L88-L94), but this appears unused. It seems easiest to ignore this in our implementation and let our TTS engine handle caching.

**Comment by BossBitch84** [comment]
How do I unsuspend my greendot card i found

**Comment by EmilRehnberg** [comment]
@david-allison-1 
Would that also yield a play button similar to how the Anki 2.1.20 does?
I find it useful being able to break up the sound playback, instead of always getting the audio for the full text. Hence the question and request :)

**Comment by david-allison-1** [comment]
@EmilRehnberg Haven't looked into the implementation, but the initial change will almost certainly mirror how Anki Desktop does it.

**Comment by lucwastiaux** [comment]
I'm planning on supporting the Anki 2.1.20 TTS {{tts}} functionality within AwesomeTTS (as opposed to the previously used <tts> tag). This would allow on-the-fly TTS to support a fallback mechanism on AnkiMobile (iOS). Ideally AnkiDroid would also support this syntax, so that the fallback works on AnkiDroid as well.

**Comment by david-allison-1** [comment]
I'm getting the initial stages of the Rust conversion into AnkiDroid 2.14, after then we'll be able to use the Anki Desktop TTS code.

**Comment by lucwastiaux** [comment]
That sounds like a good idea, will you be able to share a large proportion of code with Anki at that point ? I did notice the code which parses the {{tts}} tag is in rust (.rs file - I know nothing about rust).

**Comment by david-allison-1** [comment]
> That sounds like a good idea, will you be able to share a large proportion of code with Anki at that point ? I did notice the code which parses the {{tts}} tag is in rust (.rs file - I know nothing about rust).

We'll be compiling the rust as a native library for Android, none of the Python sadly

**Comment by lucwastiaux** [comment]
@david-allison-1 do we believe cross-compiling the rust code is still the best way to achieve compatibility with the Anki 2.1.20 TTS tag ? Or should we consider an ad-hoc implementation within AnkiDroid ?

**Comment by mikehardy** [comment]
I think he's got the rust lib published on maven as of just a day or two ago, so there is steady forward progress here. It's nearly unbelievably hard but the payoff should be worth it. I'm still +1 on rust lib port, and it seems close

**Comment by lucwastiaux** [comment]
If it works, then I 100% agree it's a superior solution to re-implementing all of this processing in java. It would allow ankidroid to react faster to anki changes in the future.

**Comment by david-allison-1** [comment]
Oh wow! That's a lot of thumbs up. Started working on this

This requires further design WRT interaction with "automatic display answer"

Automatic display answer both flips the card, and has the ability to bury/answer the card after a user-supplied timeout.

### Current behaviour

* TTS needs to explicitly be enabled in the advanced settings (preference: `tts`)
  * If this is enabled, it searches for `<tts>` tags in the card html
    * If they're found, the locale is used, and the section of the card is read
    * if they're not found, the entire card is read (`locale = ""`)
    * When reading, if the `localeCode` is "", then ask the user and save the preference in MetaDB
    * Or allow selection of a locale if the provided locale isn't mapped
 * TTS currently does not allow a user to select a voice, BUT they are supported natively in Android
 * A user can install TTS engines

AnkiDroid plays either Sound or TTS, with Sound taking priority.

If sound:

* If the question is showing: Add the sound duration of question + answer to "automatic display answer"
   * This gives time for the user to think the answer before moving on
* If answer is showing: Add the duration of the answer to "automatic display answer"

If TTS:
* Add a completion listener, and trigger it when all sounds are played, which sets off the "automatic display answer" functionality timer

### Next Steps

* Investigate into how Anki Desktop handles a combination of TTS and Sound (probably playing both)
* Discuss how we want user interaction (replaying audio) to modify the "automatic display answer"
* Unify "sound" into one component, rather than two, so we have a concept of "all sound being done"
  * Hook up the completion events of the individual components, so TTS can cause Sound to play, and Sound can cause TTS to play
  * Verify error behaviour (if TTS or sound fails, we presumably want to continue to the next sound)
  * Verify "not found" behaviour - a much more common case, we want to ensure that a snackbar is shown, especially if more than 2 invalid sounds are played in a row
  * Verify "TTS not selected" behaviour - we likely will need to do this in combination with playing sounds (ugh). 
    * Anki Desktop sounds should all have a locale, BUT we can show the selection if the locale is not supported by the current user's phone
  * Discuss deprecation of the `<tts>` mechanism
* Additional issue to discuss design of voice selection/changing speed - out of scope for now due to complexity of above

**Comment by working-name** [comment]
@david-allison Just in case you enjoy getting nudged by random people on random github issues... 😆 You're welcome.

**Comment by david-allison** [comment]
> @david-allison Just in case you enjoy getting nudged by random people on random github issues... 😆 You're welcome.

Hello, my good Random person! Could you schedule a reminder for another nudge in 3 weeks. I don't have a laptop with me currently. I would like to complete this random issue 😁

**Comment by gsingh93** [comment]
@david-allison a different random person here, it's been about 3 weeks 😄

**Comment by giselaortt** [comment]
I would like to work on this. I am junior so that could take a while.

**Comment by luc-languagetools** [comment]
Hi, this request has been open for 3 years, Anki 2.1.20 came out on 2020/02/14, introducing this new tag format. Does the AnkiDroid team not see it as a priority to support the new Anki standard ? Annoyingly, users have to do all kinds of tricks with CSS to get Anki 2.1.20 TTS tags to behave on AnkiDroid, and still don't get the benefit of TTS.

**Comment by dae** [comment]
Tracked on #14358; might be worth re-posting the bounty there.
