### ISSUE TITLE
Swipe registers twice - goes to next card instead of just reveal, or answers and reveals next card immediately

### ISSUE THREAD

**Issue by vladz0r** [ankidroid/Anki-Android#5796]
###### Reproduction Steps

1. Turn Anki swipe to answer (green)
2. Go to a card
3. Swipe (left or right, whichever you picked)
It will sometimes swipe twice, basically, so instead of just revealing the answer, it'll go directly to the next card.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by Anthropos888** [comment]
Which phone and Ankidroid version are you using? I did around 130k reviews using swipe gestures and this never happened. Sometimes the phone reacts too slow so I'm swiping two times and then the next card is shown. But that's obviously because I was too impatient.

**Comment by VladamirC** [comment]
I'm using a Galaxy S9. I reviewed fine in Ankidroid for months until the
recent version seems to have messed it up. Could be Android 10 which my
phone also updated to recently.

**Comment by mikehardy** [comment]
Nothing has changed in the swipe / gesture area in a long time, I'd suspect Android 10. Do you have any Android 9 devices you could look at? I don't use gestures personally so I don't have a lot of experience with it
