### ISSUE TITLE
Sync requires exclusive database access / other users should wait

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5801]
###### Reproduction Steps

1. Turn on auto-sync on startup
2. Turn on reminders
3. Start the app

###### Expected Result

Everything is fine

###### Actual Result

#5797 #5748

###### Research

I've already dug in to why sync has to reset the database when it is done, I believe it is justified. The reasoning is that the sync might have a failure for any reason meaning that you might roll back a transaction etc. One more look might be worth it though - https://github.com/ankidroid/Anki-Android/blob/014e6951988d37b7166bc63edca8c4e91ed34771/AnkiDroid/src/main/java/com/ichi2/async/Connection.java#L469 is where it's being reset

@timrae perhaps this is easier than I'm thinking and I should just be spinning (or wait/notifying) on CollectionHelper.isCollectionLocked()? That one is locked/unlocked during sync 🤔

**Comment by timrae** [comment]
Spin lock could be ok, short of some major architectural change, it's hard to see what else we could do... Where would you put it? Maybe in the singleton that retrieves the collection?

**Comment by mikehardy** [comment]
I'm still ruminating on it, I think these things at the moment:

1 make a wait-able collection locked method that notified on unlock in CollectionHelper
2 have the end of sync trigger notification rebuild (seems like this is separate and should be done anyway, after I thought about it)
3 either have reminder rebuild check for collection locked as it builds and just bail out if it detects it (a second-class reader, basically)
4 or have reminder rebuild actually lock the collection in combo with the wait/notify in 1 such that reminder build would play nice with anything else locking it and they would take turns (first-class exclusive reader)

I think 2 needs to happen no what
I think since a sync should rebuild notifications after, 3 is better than the combo of 1 + 4, and is conveniently easy to implement and understand
