### ISSUE TITLE
Wrong symbol for ascending/descending sorting in card browser

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5802]
###### Reproduction Steps

1. Open card browser
2. Menu > change display order
3. Look at the symbol after the current selection

###### Expected Result

Ascending symbol for ascending sorting 

###### Actual Result

Ascending symbol for descending sorting. See screenshot: the sort field is sorted Z to A (descending) but the triangle looks upwards/ascending.

![Screenshot_20200310-094008~(1)](https://user-images.githubusercontent.com/45192213/76295405-d6774f00-62b4-11ea-8973-44a874b7698c.jpg)

###### Debug info
AnkiDroid Version = 2.10alpha45

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [ x ] character to confirm the points below:*

[X  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hey @Anthropos888 do you know if this is changed behavior, as in you use this and it was working before but now is not, or is this something you just noticed now? Only asking because I just merged https://github.com/ankidroid/Anki-Android/pull/5586 yesterday and alpha45 was the first time it went out

**Comment by Anthropos888** [comment]
Hey Mike, I recognized the wrong symbol since long ago but I found the issue too minor to report. So it has nothing to do with recent changes.

**Comment by Anthropos888** [comment]
@mikehardy The waiting for feedback label can be removed ;-)

**Comment by RSBat** [comment]
Hi! I tried looking into this issue, but I need some help: in what order should it be sorted if "sortBackwards" is true? Description in [Database structure](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure#configuration-jsonobjects) is not clear, and right now it is treated like `sortBackwards == orderAscending` by CardBrowser, but descending by Finder.

**Comment by mikehardy** [comment]
Hi there @RSBat !
Seems they should be the same everywhere :-), sounds like that's just a bug.
if sortBackwards == false the largest value should be the first item, smallest last
if sortBackwards == true the smallest value should be first item, largest last

Seems right based on the comment

here is related upstream code 

https://github.com/ankitects/anki/blob/6046bbc77978d35f70915d6d1bfdc81ec14ca268/qt/aqt/browser.py#L924-L963

**Comment by david-allison-1** [comment]
As an aside, I had a look at this when I started out on the project and found that there were differences in opinion on what the arrows mean in the first place: https://stackoverflow.com/questions/338166/which-direction-should-the-arrows-point-in-a-sorted-table

I'd offer as a suggestion (pending discussion) that we move to the Android vector icon for sort, as is feels less ambiguous and more standardised (Available under: Add - Vector Image).
![image](https://user-images.githubusercontent.com/62114487/80835212-38d03a00-8bea-11ea-8b10-f57ce10f88e5.png)

Downside to this approach is that we'd need to flip the vector ourselves, which is a little more work, as there's only a sort descending in the default icon set.

**Comment by mikehardy** [comment]
agreed on the sort icon, I like that. 
vector icons are easily available
https://oblador.github.io/react-native-vector-icons/ is a good search
enter "sort" for search. I personally like these two from FontAwesome5 (https://fontawesome.com/icons?d=gallery&q=sort&m=free - license is fine https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt

https://fontawesome.com/icons/sort-amount-down-alt?style=solid
https://fontawesome.com/icons/sort-amount-up-alt?style=solid

the combo of the arrow and the directional stack says it all to anyone used to either style I think.

**Comment by Anthropos888** [comment]
@mikehardy Just my personal opinion, but the arrow-with-list combo icon looks a bit confusing to me. I wouldn't know if it stands for smallest first or largest first.

I like this explanation from the stackoverflow discussion and would prefer a simple triangle:

> I don't think of them as arrows, but as a visual mnemonic of the current state. So, showing a triangle pointing down shows descending order. It is visually in line with the icon with the largest item (base of the triangle) at the top of the list and the smallest (point of the triangle) at the bottom.

**Comment by mikehardy** [comment]
Works for me :-), I enjoy too much information packaged in too small a space normally which I understand most people don't like. My comment is still potentially useful for finding vector icons in general but feel free to disregard any aesthetic suggestion I ever make (and I mean that haha)

**Comment by Anthropos888** [comment]
@mikehardy Maybe you just see things that normal people don't see: https://youtu.be/fBDifUjNzbQ

**Comment by mikehardy** [comment]
![IMG_20200501_151823__01](https://user-images.githubusercontent.com/782704/80838789-6c499f00-8bbf-11ea-864c-75bfb9ed01d1.jpg)

Hmmm entirely possible 🤓 😅

**Comment by RSBat** [comment]
So I checked how desktop anki works (first [here](https://github.com/ankitects/anki/blob/6046bbc77978d35f70915d6d1bfdc81ec14ca268/qt/aqt/browser.py#L956-L959), then actually launched it) and it is
`sortBackwards == true <=> descending order <=> largest is first item, smallest - last`

Also when you first select column for sorting it show arrow up on desktop, but down on Android. But the result is the same. Except on android with sorting "by sort field" _sometimes_ you can get same result and same arrow direction. And found a related bug that reentering cards browser can reverse order if "by sort field" is used :confused: 

Simple fixes I've tried reverse sorting for people who use not "by sort field". Feels like fixing ordering on the first launch after update is the only solution, but I'll think abut it a little more

PS it turned out to be an interesting "Good first issue" :smile:

**Comment by RSBat** [comment]
btw I like the idea of a different icon but
1) dialog supports only text items and current arrows are unicode symbols
2) https://fontawesome.com/icons/sort-alpha-down?style=solid feels more intuitive, but doesnt fit every sorting type

**Comment by mikehardy** [comment]
@RSBat no intention of sounding patronizing - it honestly sounds like you are hot on the trail of it, and I will trust your judgement, sounds like all your investigations + reasoning are sound. Thanks for picking this up, it does sound like it got a little tricky quickly :-)

**Comment by coma123** [comment]
fixed #6326

**Comment by david-allison-1** [comment]
@coma123 Just to note: Having "Fixes #XXX" in the pull request will auto-link this issue.

**Comment by david-allison-1** [comment]
@Anthropos888 Could you confirm this is fixed when 2.12alpha2 is released? Thanks!!

**Comment by Anthropos888** [comment]
@david-allison-1 I just updated to 2.12alpha2 but the icon is the same as before. Probably not merged yet?

**Comment by david-allison-1** [comment]
@Anthropos888, the change should be in there.

https://github.com/ankidroid/Anki-Android/compare/v2.12alpha1...v2.12alpha2

@coma123, pinging for informational purposes if you'd be interested in giving this another shot.

**Comment by Anthropos888** [comment]
Here how it looks in 2.12alpha2: The order is descending, but the arrow is ascending:

![ankidroid](https://user-images.githubusercontent.com/45192213/83939459-85a4c300-a7dd-11ea-9d3c-796696b131da.png)

**Comment by mikehardy** [comment]
Between the two pull requests (one closed, one merged) on this issue, I think the first one got the arrow direction correct :-) while the second one looked correct in code review. Stealing the direction bit from the first one for a follow-on might get it...
