### ISSUE TITLE
[enhancement] create custom study deck from selected cards in card browser

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#5803]
###### Reproduction Steps

1. Open card browser
2. select some cards
3. Open card browser menu

###### Expected Result

There's an option "create custom study deck from selected cards" so that users can start a custom study section with exactly the cards they want.

###### Actual Result

As for now, a custom study deck can only be created from cards with certain tags. If the cards aren't tagged/marked, there's no way to create a custom study deck with them.

###### Research

AnkiDroid Version = 2.10alpha45

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Notes to implementers: Performing this on the card IDs isn't recommended by the manual.

> Object IDs will not work in the mobile clients, and are not intended to be used in filtered decks at the moment.

https://docs.ankiweb.net/#/searching?id=object-ids

----

There doesn't seem to be a max length on the search in Anki Desktop.

* [UI (permalink)](https://github.com/ankitects/anki/blob/8007113d7c08a10a3f0440be77c63caedc7c15dd/qt/designer/dyndconf.ui#L61)
* [Impl (permalink)](https://github.com/ankitects/anki/blob/8007113d7c08a10a3f0440be77c63caedc7c15dd/qt/aqt/dyndeckconf.py#L104)

----

We could add a "Tag Cards" option in the Card Browser, and the user could create a filtered deck based on that. 

However, doing it automatically would risk cluttering the "tags" column with metadata, and potentially affecting user workflows (if they use `{{Tags}}`).

**Comment by mikehardy** [comment]
Perhaps a flag-multiple-cards-at-once, then you could search on the flag and make a deck on that? (not sure it works, but we're busy making flags a first class feature in other areas, so it might). Then users could reserve a flag (or three) for this when needed

**Comment by mikehardy** [comment]
(or both - in general now that we have multi-select I'm positive on making as many actions applicable to "all selected cards" as possible)

**Comment by mikehardy** [comment]
If we can't use the object ids I think this is intractable.
