### ISSUE TITLE
Move flag/star render to review mini-bar, swap flag for star in app bar

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5806]
From https://github.com/ankidroid/Anki-Android/pull/5701#issuecomment-597663745

The idea here is the (hopefully) final evolution of stars and flags for 2.10

- try to move the flag/star rendering to the minibar where the counts are (suggest to put them on the left of the review timer, with the intention they have gravity towards the right side of the screen)
- switch mark to "overflow" or "menu only" or whatever the default is where it doesn't show, but users can change it
- switch flag card to always show (where mark card is now)

**Comment by mikehardy** [comment]
@david-allison-1 just tagging you as from my perspective this is really the only "must have but no one is looking at it yet" change required for 2.10. The flags/stars-in-webview feature is the only thing we already have in 2.10 that needs a bit of refinement before release. It may represent the only true 2.10 feature actually. Everything else is internal refactor / optional

**Comment by david-allison-1** [comment]
@mikehardy Happy to take this on. Could you assign and provide a soft and hard deadlines? Cheers.

**Comment by mikehardy** [comment]
I won't do deadlines in open source, seems cruel ;-). I do have hopes of a 2.10 beta in "a week or two" and stable "in a month or so". And I'm more than happy to take a stab at this if that's what I need to do to meet my own hope. Or not if life happens. I think that's the definition of an open source deadline haha

**Comment by david-allison-1** [comment]
Just nice to know expectations. Those won't be an issue/stressful ;)

**Comment by david-allison-1** [comment]
@mikehardy Would you be happy with the star to the left of the answer dots, and the flag to the right?

**Comment by mikehardy** [comment]
Anything that seems reasonable works for me, the key idea was to move them out of the WebView where they perturb people's card (negative feedback on that) and the minibar seemed like good real estate to use. People will complain about where ever they are but if it seems sensible it's defensible and we can do it + move on :-)

**Comment by lervag** [comment]
If I understand correctly, when this reaches beta/release, it will be possible to flag a single card (starring/marking affects a note, which may imply several cards). Is that right? If so, then I'm really looking forward to seeing this. Your effort is _very_ much appreciated!

**Comment by mikehardy** [comment]
@lervag - you should sign up for the alpha mailing list so you can try it out now, flagging and starring already completely function, the only remaining work is this PR which is just moving where we display that things are flagged or starred. But you can test (or just enjoy) the functionality already in current alpha releases. It will be in beta in a week or three though I think

**Comment by lervag** [comment]
@mikehardy Thanks for the quick response! I would not mind signing up for the alphas. If possible, I would also not mind contributing, although I've no experience with Android dev.

**Comment by mikehardy** [comment]
@lervag cool! Here's the instructions for telling Google Play to deliver testing versions, and further the mailing list to sign up for which flags you in Google Play for alpha builds on top of the beta https://docs.ankidroid.org/manual.html#betaTesting

Best way to get started contributing is to help with translations - there are lots of new strings to translate for 2.10 and this interface makes it pretty easy to work through: https://github.com/ankidroid/Anki-Android/wiki/Contributing#translate-ankidroid

**Comment by lervag** [comment]
Thanks @mikehardy ! I'll refrain from further off-topic comments here now, except to mention that I've responded by email to you to follow up.

**Comment by mikehardy** [comment]
released as 2.10alpha71 as soon as google finishes processing it

**Comment by lervag** [comment]
I like this change quite a lot! I'm curious, though, is it possible to change the color of the star? For me, it is rendering white on a gray background, which makes it difficult to see.

I'm probably late to all discussions here, but I was also wondering if it is possible to get "shortcut buttons" (on the top bar) to both stars and flagging, instead of flagging only?

I very much like that flagging is much more available now, though! When working with note types with several cards per note, it is much easier to flag a particular card that it requires a change/update or whatever.

Thanks for your hard work, it is very much appreciated!

**Comment by david-allison-1** [comment]
@lervag Is that the 'plain' theme? That's far less than ideal. I'll get it fixed. Thanks for the feedback!

**Comment by mikehardy** [comment]
Yeah, when I updated I was much happier with the reviewer bar placement. This is working really well now. I agree on the star though, that was my first though. I like a gold star personally :), the white star was hard to see. Then of course I immediately reconfigured my app bar buttons as well (I'm a mark person, not a flag person - personal choice) so of course then it stopped showing up in the reviewer bar which is also nice - no duplication.

**Comment by lervag** [comment]
> I'm a mark person, not a flag person - personal choice

So am I, except I have a lot of notes (e.g. geography) with multiple cards. With flags, I can "mark" the exact card that might have a problem. Starring it does not work as well, because I tend to forget which part of the note I had a problem with... :p
