### ISSUE TITLE
I want to implement hanziwriter.js in Ankidroid.

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#5807]
I have already implemented write Chinese characters like skritter in JavaScript using hanziwriter.js 
https://hanziwriter.org/docs.html

When characters and word shown then it will loop through characters in a words and count for mistake to draw stroke by user. 
If mistake == 0 (easy)
mistake == 1 (good)
mistake == 2 (hard)
mistake >= 3 (again)
  
I have already checked the 
http://abananablog.com/2016/12/31/anki-trace/
But it is not working like hanziwriter.js also it only for single character. 
I also checked 
https://github.com/jcklie/anki-maobi
But it is only implemented in anki.
For multiple characters what will be the option?

So my question is where should I start so that I can use JavaScript hanziwriter.js for multiple characters in Ankidroid.

I have already made it in JavaScript just want Ankidroid SRS feature.

**Comment by mikehardy** [comment]
I have not looked deeply at this a bit but there was one other person that did some pretty involved javascript integration (including storage usage, to handle the card front/back flip which otherwise destroys card state) and you might be able to learn something from it? https://github.com/pigoz/anki-canvas

**Comment by infinyte7** [comment]
It seems good. I will check it.

**Comment by infinyte7** [comment]
I implemented it.
It is working on Anki Desktop but for Ankidroid It seems there is some error related character encoding.
When I get length of word, then I get 2 in Anki Desktop and Ankidroid gives 7 for same word.
Ex:- ‘比如’
in Anki Desktop I get 2 ,
in AnkiDroid  I get 7.

If I pass string as hard coded then It is working. But When I use document.getElementById().innerHTML, then It is not working in AnkiDroid.

I think there may some error in webview of AnkiDroid. I am not sure but maybe.

https://github.com/infinyte7/Anki-maobi
There is HSK1 apkg as sample. It working fine on AnkiDesktop

**Comment by infinyte7** [comment]
I implemented it.
It is working on Anki Desktop but for Ankidroid It seems there is some error related character encoding.
When I get length of word, then I get 2 in Anki Desktop and Ankidroid gives 7 for same word.
Ex:- ‘比如’
in Anki Desktop I get 2 ,
in AnkiDroid  I get 7.

If I pass string as hard coded then It is working. But When I use document.getElementById().innerHTML, then It is not working in AnkiDroid.

I think there may some error in webview of AnkiDroid. I am not sure but maybe.

https://github.com/infinyte7/Anki-maobi
There is HSK1 apkg as sample. It working fine on AnkiDesktop

**Comment by mikehardy** [comment]
This will not be something supported directly. "the webview" is literally google chrome - so there should be plenty of documentation on stackoverflow etc about how to handle similar things? And if you can make it work in Google Chrome directly, it should work on AnkiDroid

**Comment by infinyte7** [comment]
I have figured out. The problem is in template of card. If I use Basic Card template from Ankidroid then It is working. 
Finally it is working on Ankidroid also.
https://github.com/infinyte7/Anki-maobi/blob/master/README.md

**Comment by mikehardy** [comment]
Excellent! While we don't support the fancy stuff *directly* I like to make sure that it is at least possible, if that makes sense. So I'm glad to hear it is possible. Cheers
