### ISSUE TITLE
Timezone move results in double-day

### ISSUE THREAD

**Issue by jalexstark** [ankidroid/Anki-Android#5809]
###### Reproduction Steps

0. Original timezone, normal timezone for use are both US West coast.
1. Travel to East coast time, set time of day to 02:00
2. Move phone to West coast, that is 3 hours behind.
3. Ankidroid shifts time of day to 23:00
4. Move time of day to 05:00.

###### Expected Result

I haven't lost or added a day, and I studied on time across my travel. I should only see one day.

###### Actual Result

Ankidroid presents 2 days of work, as if I skipped yesterday.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! Curious what scheduler (v1 or v2) you are using? Might be related to -> #5805

**Comment by jalexstark** [comment]
V1.

**Comment by mikehardy** [comment]
Thanks! Not related then. Hmm - we have a few other issues logged about dates / timezones but this has fantastic detail (super useful, thank you) so without even attempting to search for dupes this is worth keeping open

**Comment by mikehardy** [comment]
This one is unfortunately not likely to be fixed immediately because the desktop version of Anki is doing a port of it's internals from Python to Rust programming language and fixed this in the process. We are planning on using the same implementation (the Rust libanki) wrapped here, so this will be fixed magically when that happens, but depends on that conversion. More important to put effort in to that vs fixing the corner cases in timezone handling in libanki

**Comment by jalexstark** [comment]
SG. Reasonable.

Do write up a 2-page summary of the conversion experience. It would be
valuable. A clean case study of Python conversion would be so, because a
lot of conversions are from, say, C++.

(OK, I have an interest of my own as a bystander to the Rust project.)

**Comment by mikehardy** [comment]
Any experience on the Python -> Rust conversion would be from the Desktop side of things which is actually completely separate from us, but you may feel free to ask on https://anki.tenderapp.com
