### ISSUE TITLE
Beolingus pronunciation search is case insensitive

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5810]
###### Reproduction Steps

1. Go to "Add New Note" screen
2. Click the attach icon next to a field and select "Advanced Editor"
3. Enter `hello` into the text box.
4. Press "Pronunciation"
5. Press Load (with English Selected)

###### Expected Result

The English pronunciation for "Hello" is previewed.

###### Actual Result

Fails with "The word was not found".  
NB: Typing `Hello` returns the correct result.

###### Debug info
```
AnkiDroid Version = 2.10alpha45

Android Version = 9

ACRA UUID = 5a0ff95e-d1bb-46d6-9a61-d425ab3ab53d
```

###### Research
[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

###### Related

* #5376 Pronunciation sometimes shows "The word was not found" (caused by " {noun}" suffix)
* #5749 Fix for the above (use `.contains()`).

**Comment by david-allison-1** [comment]
I'm happy to take this issue on if there's design sign-off, the issue is: https://github.com/ankidroid/Anki-Android/blob/7f8272b4519319fa88c081b36cf4809b22d08757/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/beolingus/parsing/BeolingusParser.java#L44 but I have a few design questions that I'd like to confirm maintainers are happy with. Mostly the string method to use.

Note: Only English, German, Spanish and Portuguese pronunciations are supported. 

----

**Which culture should be used for string comparison?**

I presume the culture of the requested language, otherwise the [Turkish I](https://en.wikipedia.org/wiki/Dotted_and_dotless_I) would fail some lowercases: "HILL" should match "Hıll" instead of "Hill". 

Practical issues may occur with the German Eszett (ß/ẞ and ss/SS).

----

**Which string method to use for culture-sensitive, case insensitive comparison?**

[java.text.Collator](https://docs.oracle.com/javase/7/docs/api/java/text/Collator.html) supports locales.

Uses strengths:

* PRIMARY:   "a" vs "b"
* SECONDARY: "a" vs "ä"
* TERTIARY:  "a" vs "A"
* IDENTICAL: "a" vs "a"

Algorithm: Loop first with `IDENTICAL`, if that fails, use `TERTIARY`. Return the first match

Unicode normalisation modes also exist, I'll use "FULL_DECOMPOSITION".

**Issues:**

Only supports `compareTo()` and not `contains()`
----
**Regex**

Use `Pattern.compile(Pattern.quote(s2), Pattern.CASE_INSENSITIVE | Pattern.UNICODE_CASE).matcher(s1).find();`. Seems simple, and worth testing.

**Issues**

* Not locale sensitive.  
* Requires escaping

----

**ICU4j**

Looks nice, probably the best option. MIT Licensed

Usage: https://stackoverflow.com/a/23892141

**Issues:** 

* Untested
* Don't know how maintainers feel about a dependency. 

NB: I'm unfamiliar with Java, this seems harder than it should be, so maybe I'm missing a trick or a common dependency. 

----

**Defects**

We currently select the first pronunciation, I'll continue with this, but this increases the chance of ambiguities due to homophones:  

"read" -> "read" (present tense), but does not suggest "read" (past tense).

New issue with lowercasing:  
"READING" -> "Reading" (Town in England, pronounced "redding") or "reading".

I'd like to mark this as a defect in code for now and add an issue to improve it.

**Comment by mikehardy** [comment]
Ironically Beolingus was broken until just now (I fixed it very recently) and no one said anything, so this isn't a feature used that much. As such I would push towards the easiest to maintain (complexity + dependency) solution.

Careful to look at the android API not the Oracle one so you make sure anything proposed works with API15 (our minSdkVersion) and up - e.g. https://developer.android.com/reference/java/text/Collator (which is safe, added in API1 so no problem)

'contains' vs 'compare' is vital, as Beolingus adds some sauce to some words but not others - I forget what exactly but that was something I discovered while testing

Given it's just the language pairs beolingus supports I wonder if simply doing a tolower is sufficient and we're done?

**Comment by david-allison-1** [comment]
I initially assumed it was just broken since "hello" didn't work. Probably put a few users off using it.

> 'contains' vs 'compare' is vital, as Beolingus adds some sauce to some words but not others - I forget what exactly but that was something I discovered while testing

Found it: #5376

I'm happy to take on the simple solution for now. Fixes the issue and none of the alternatives seemed great.

PS: Thanks for the catch regarding APIs, will keep it in mind.

**Comment by mikehardy** [comment]
I shower valuable internet points on anyone that submits PRs, get yours today! :rofl: :medal_sports:

**Comment by mikehardy** [comment]
2.10alpha47 is published with this and will be available when google is done processing it 🚀
