### ISSUE TITLE
Ankidoid stops responding to keyboard when hint link is clicked.

### ISSUE THREAD

**Issue by origamigirl** [ankidroid/Anki-Android#5811]
Ankidoid stops responding to keyboard when hint link is clicked.

###### Reproduction Steps

1. Create card with HINT link on QUESTION side of card.
2. Click on HINT link with mouse. Hint text appears.
3. Click ENTER.

###### Expected Result

Advance to ANSWER side of card.

###### Actual Result

Nothing. (NOTE: can still advance to ANSWER side by clicking SHOW ANSWER bar with mouse.)
Once you reach the ANSWER side of card, keyboard starts working again.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.9.4

Android Version = 9

ACRA UUID = 6318c480-95cf-4c88-8300-8f0a05e48948

Running as android app on Samsung XE501C13 chromebook.

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I don't understand, I don't recall there being a hint link as a feature of AnkiDroid? I can believe mouse + keyboard input isn't great though as not many people use it on chromebooks so those input methods don't see a lot of testing + attention unfortunately

**Comment by david-allison-1** [comment]
Confirmed on Android (2.10beta45). Requires both keyboard and mouse input, it's a pain to debug.

* Create a note type containing a hint: `{{hint:Front}}`
* Create a note
* Click the hint on the card
* Press Enter
* [AbstractFlashCardViewer.onKeyUp](https://github.com/ankidroid/Anki-Android/blob/7f8272b4519319fa88c081b36cf4809b22d08757/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L970-L980) does not fire as expected.

Hints are defined in [HintFilter.java](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/hooks/HintFilter.java)

Sample HTML for a hint:

```html
<a class=hint href="#" onclick="this.style.display='none';document.getElementById('hint69609650').style.display='block';return false;">Show Front</a><div id="hint69609650" class=hint style="display: none">Hello</div>```

**Comment by mikehardy** [comment]
Fascinating! And there is a hint :-), this software has so many features I still learn new things frequently. Thanks for reproducing. The HTML/JS inspection (in combination with a card.html rendered and loaded into a regular Chrome instance) might be interesting? Or might not.. https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by david-allison-1** [comment]
Notified downstream of issue: https://anki.tenderapp.com/discussions/ankidesktop/39763-bug-report-filtered-deck-corruption?unresolve=true

I'd rather not fix this first and get libAnki out of sync with downstream.

**Comment by mikehardy** [comment]
I think  you mean to have this on #5823  :-) @david-allison-1
