### ISSUE TITLE
I have created showAnwser() function to be called from ankidroid webview AbstractFlashcardViewer, want to know security implications?

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#5816]
##### Automatic showAnswer()

1.  I added following to webview in AbstractFlashcardViewer.java
```
webView.addJavascriptInterface(new JavaScriptFunction(), "AnkidroidJS");
```
2.  Then added following class in same java file  AbstractFlashcardViewer.java
```
public class JavaScriptFunction {
        @JavascriptInterface
        public void showAnswer() {
            runOnUiThread(new Runnable() {
                public void run() {
                    if (!sDisplayAnswer) {
                        displayCardAnswer();
                    }
                }
            });
            Timber.i("JavaScriptFunction:: Show answer function called");
        }

```

3. After that I called the showAnswer function from front side of deck in Ankidroid
```
{{Front}}
<input type="button" value="Show Answer" onclick="AnkidroidJS.showAnswer();"/>
``` 

##### Benefits of using this, Show Answer called automatically after completion of answer typed or drawed after validation.
For ex:- I have implemeted existing hanzi writer js in in Ankidroid. In that after completion of drawing stroke of charactes, user have to manually type Show Answer button.
But if it get added to Ankidroid then It will be more useful. 

##### After reading stackoverflow and other website, I found that there are some security implications for this.
https://stackoverflow.com/questions/6415882/android-javascriptinterface-security
So I want to know that It is calling only displayAnswer() in Ankidroid. How may It cause security related problems?

##### I have added it my forked github repo.

**Comment by david-allison-1** [comment]
Hi, we're already got an implementation of handling JS calls (likely already with security related problems).

You can see a sample implementation: https://github.com/ankidroid/Anki-Android/pull/5815/files . Add another if into `filterUrl()`.

I can't imagine there's any security implications as you're not accepting user input here.

Cheers!

NB: I'm new to to the project, don't take my word as gospel.

**Comment by infinyte7** [comment]
I got it. I want to know how can I call displayAnswer() of AbstractFlashcardViewer.java in Front template of anki deck review.

**Comment by david-allison-1** [comment]
Hi, I'm not quite sure I totally understand. Please let me know if I've misinterpreted.

Add a function to `card.js` using a different string

https://github.com/ankidroid/Anki-Android/blob/de5b06c0b148c604f9fc3c00277554ee0e2ea2e7/AnkiDroid/src/main/assets/scripts/card.js#L61-L65

Call the function from JavaScript

Hook into `filterUrl()`, handle the string and perform appropriate logic.

https://github.com/ankidroid/Anki-Android/blob/de5b06c0b148c604f9fc3c00277554ee0e2ea2e7/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1472-L1477

Call `displayCardAnswer()`

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L2027

Hope this helps 😃

**Comment by infinyte7** [comment]
I got it. 
Please check this github repo [Anki-maobi](https://github.com/infinyte7/Anki-maobi). 
I have implemented existing HanziWriter.js in Ankidroid deck / front template.
After completion of drawing stroke user have to manually click show answer button.

For Anki Desktop there is command to show answer automatically.
```
pycmd('ans');
```
I wanted that feature in Ankidroid, to show answer automatically.

But If it get added to AnkiDroid then auto show answer like that one will be helpful.

If that can be done by using your provided codes and steps then I will use that one.

**Comment by infinyte7** [comment]
I have added following in card.j
```
function showAnswer() {
    window.location.href = "signal:show_answer";
}
```
In  ``` filterUrl()``` of AbstractFlashcardViewer.java, added
```
if("signal:show_answer".equals(url)){
                    if (!sDisplayAnswer) {
                        displayCardAnswer();
                    }
                    return true;
                }
```

But how can I call it in javascript in front side of card?
I mean using 
```{{Front}}
<input type="button" value="Show Answer" onclick=" "/>
```

**Comment by david-allison-1** [comment]
@infinyte7  `onclick="showAnswer();return false;"`

**Comment by infinyte7** [comment]
I got it. Thank you. It is more simple than my earlier implemetions.
