### ISSUE TITLE
when external input, it chage darkmode background color from black to gray to black to gray

### ISSUE THREAD

**Issue by boloing22** [ankidroid/Anki-Android#5819]
###### Reproduction Steps
1. dark mode
2. external input
3.

###### Expected Result
i thought that darkmode backgroud color is black for good.

###### Actual Result
when external input, it chage darkmode background color from black to gray to black to gray and repeatdly so on.
i am used to dark mode on bed often with bluetooth remote controller before sleep.
skimming in non light room, as it were flickering flash. it is too sensitive for eye and annoying.
i though that it relevlant highlight focus. so it is easy reproduct that.

https://youtu.be/xqcmOTuq39g

###### Debug info
galaxy s8+ anki v2.9.4
chromebook plus anki v2.9.4

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
That is bizarre! Thanks for posting the video, your description was accurate but there is nothing like seeing it. For anyone looking to triage this it definitely did not happen when using touch, it only happened when you used external input to select an answer and the incorrect color was present on the display of the next card

As a workaround, I wonder what would happen if you selected the "light dark" mode (gray everywhere) as your main mode?

**Comment by boloing22** [comment]
1st video's night theme is black.
https://youtu.be/xqcmOTuq39g

2st video's night theme is dark.
https://youtu.be/wBhwgvp6mFU

i use anki in chromebook, because video recording needs phone. but also it reprodces in android phone. 

i suppose that external input needs kinda focus. and it generate that of highlight focusing.

**Comment by mikehardy** [comment]
There might be relief here in #5811 or at least some relation. The videos are great, many thanks again. Seems to be explicitly related to keypresses vs touch. Software is always capable of surprising in the ways it can fail!

**Comment by mikehardy** [comment]
You might want to get on the alpha distribution channel so that you can check (and take advantage of) any bugfixes in the area - they appear there first, and just in case there are problems 2.9 and 2.10alpha are forwards and backwards compatible - no problem in case you need to go back to stable right now - https://docs.ankidroid.org/#betaTesting

**Comment by david-allison-1** [comment]
Related to #5811, but not fixed by it. Still occurring in my dev branch.

AFAIK, this is default Android behaviour (showing the user where the text input is focused). 

I'll look into seeing whether we can disable the functionality via a setting when I have some time.

**Comment by mikehardy** [comment]
For me I'd prioritize this much lower than the 2.9.x milestone issues, if we're adding a setting it'd be 2.10 or 2.11 earliest before I shipped it whereas we're making fantastic progress on stability and I want to finish that up - https://github.com/ankidroid/Anki-Android/milestone/15

<img width="711" alt="Screen Region 2020-03-14 at 12 11 44" src="https://user-images.githubusercontent.com/782704/76686883-01331180-65ed-11ea-97e2-111b8b88fd1d.png">

**Comment by mikehardy** [comment]
Keeping this alive for at least one more stale cycle, could be a good first issue
