### ISSUE TITLE
User Onboarding - Add Show Password icon to AnkiWeb logon

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5825]
###### New Feature Story

As an existing user of Anki Desktop with a long password who has never used AnkiDroid, I want to see a "show password" icon inside the password field on the logon screen so I can visually confirm that my password is correct, and correct any changes before logging on.

----

AnkiDroid offers a save password feature via Android OS, but this isn't useful before the password is entered for the first time.

###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Yeah, that would be nice, I'd merge it
