### ISSUE TITLE
window.location.reload() opening chrome.

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#5826]
###### Reproduction Steps

 In front side of card adding adding function to button to call 
```
window.location.reload();
```
Or other similar functions to reload webview is opening chrome.

I have to use this in my Anki deck. When user select option then it should refresh in current card.
Not on next card.
Change is get reflected from next card.
I have 

![GIF-200317_123959](https://user-images.githubusercontent.com/12841290/76839887-532d9e80-685c-11ea-8bd1-681c084b56a3.gif)

###### Expected Result
Should refresh current webview when reload () function called from front side of card.

###### Research
*Enter an [ x ] character to confirm the points below:*

I have use the following code in AbstractFlashcardViewer
```
webView.loadUrl("javascript:window.location.reload( true )" );
```
It still open in chrome.

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

###### Question
Is there any security related concerns about this?
Or better approach for this, are available in Ankidroid?

**Comment by mikehardy** [comment]
Hey @infinyte7 I just want to say that I'm open to maybe a new signal being handled in abstract web viewer, but this isn't a bug to me. It's well outside normal usage, so if you want it supported you'll need to generate the PR yourself. I'm going to close this so it doesn't clutter up the issue list but I would accept a new signal passed from Javascript to the Java signal processor if you could find one that worked

**Comment by infinyte7** [comment]
Okay, thank you
