### ISSUE TITLE
Next Day Starts At changes to incorrect time after sync

### ISSUE THREAD

**Issue by Rahey94** [ankidroid/Anki-Android#5831]
###### Reproduction Steps

1. Moved to a new timezone. Original time zone was GMT-5, now is GMT+9.
2. Time zone of my PC and Android properly update.
3. "Next Day Starts at" stays at 4 am on my computer as it should, but changed to 6 pm on Ankidroid.
4. If I manually change "next day starts at" on AnkiDroid to 4 am, everything returns to normal
5. However, whenever I sync Ankidroid returns to 6 pm.

###### Expected Result

Next day starts at should be consistently at 4 am on both Ankidroid and Windows.

###### Actual Result

After syncing, next day starts at 6 pm on Ankidroid, and 4 am on Windows. This happens even after setting next day starts at to 4 am on Ankidroid. 

###### Debug info

AnkiDroid Version = 2.9.5

Android Version = 10

ACRA UUID = 22093a8d-3099-421d-b128-30c8204cad98

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
This is indeed a problem - there is at least one issue open already that you should follow for updates #5380 - sorry it is affecting you

**Comment by Rahey94** [comment]
Thank you for your response.
