### ISSUE TITLE
Restore From Backup - Pressing Device "Back" Button should return to Deck Browser

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5833]
###### Reproduction Steps

1. Open Deck Browser
2. Select "Restore From Backup"
3. Accept the confirmation
4. Press the physical "Back" button on the device.

###### Expected Result

The user returns to the deck browser

###### Actual Result

The user is re-shown the confirmation to restore from backup.

This works correctly when using the "Back" button on the dialog.

###### Debug info
AnkiDroid Version = 2.10alpha50

Android Version = 9

ACRA UUID = 5a0ff95e-d1bb-46d6-9a61-d425ab3ab53d

###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[x] I have searched for similar existing issues here and on the user forum

----

Simple issue for someone to get familiar with the project

**Comment by mikehardy** [comment]
Are we certain this was not due to #5599 ? Might double check result of just-committed revert released as 2.10alpha53

**Comment by david-allison-1** [comment]
Certain it wasn't, apologies for not nothing it at the time
