### ISSUE TITLE
In-app wallpapers

### ISSUE THREAD

**Issue by illialoo99** [ankidroid/Anki-Android#5835]
Please, add wallpaper support for AnkiDroid. It may improve UI of app and would give more freedom for customizing.

###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi - sorry this is not a customization we will make. You can edit your card templates to set whatever background you like though, with a little HTML/CSS work - https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection
