### ISSUE TITLE
Consolidation of AnkiDroid Documentation

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#5838]
To my knowledge, there are two repos containing AnkiDroid related documentation:
1. The wiki for this project
2.The [ankidroiddocs repo](https://github.com/ankidroid/ankidroiddocs)

Seeing as how GH wikis are git repos in their own right and the similar purpose of the two projects, could we merge the two?

If so, an important question is if we want to keep a separate GH issues for the Anki-Android project (issues for code) and the newly merged documentation repo (issues for documentation). Perhaps we could get away with a single issues page with a label specifically for documentation?
###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
They have separate purposes

The ankidroiddocs repo is for the manual and has a high quality standard

The wiki is for the FAQ and contributor guides really - things that aren't in the manual and we are okay with it being wiki so it can move more quickly, it has a lower quality bar

I could see ankidroiddocs moving into a "docs" directory here in the main repo so it isn't separate, but I'm not sure if that really improves things at the same time that I'm not sure if it would affect any infrastructure related to docs.ankidroid.org

**Comment by sudomain** [comment]
Understood. I prefer the docs to be in a separate repo, but then again I don't make many contributions to the project. Two questions about the wiki:
1. if someone sees an inaccuracy would it be appropriate to just make an edit or should an issue be opened first?
2. What's the policy on linking to a Anki-related personal project in the wiki? I'm putting the finishing touches on a script that allows running desktop Anki on an Android device. May I link to it once I'm finished?

**Comment by mikehardy** [comment]
For the wiki, if there's anything wrong or that could be improved just edit (please edit! :-) )
Linking to other projects, sure! As long as they are anki-related and free I definitely don't have a problem. If they're not free and I want to keep them corralled somehow, but the point is more people learning more stuff, if the link or info you add helps that, we are winning
