### ISSUE TITLE
Feature: Forgotten AnkiWeb Email Instructions

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5844]
## Story

As a
 
* New AnkiDroid user 
* With an existing AnkiWeb account from Anki Desktop
* Who has forgotten my email

I would like to be able to access instructions on how to retrieve my email from the logon screen so I can retrieve my data from AnkiWeb.

----

Ref: https://groups.google.com/forum/#!topic/anki-android/I92p5ta892o

**Comment by mikehardy** [comment]
Keeping this one open for at least another stale cycle as it could be a good first issue

**Comment by Paras-Saini** [comment]
I want to work on this issue to fix it..

**Comment by david-allison-1** [comment]
@Paras-Saini fantastic! Thanks so much.

**Comment by Paras-Saini** [comment]
Thanks  so much sir, to assigned it to me..

**Comment by Paras-Saini** [comment]
@david-allison-1 where i found the resources related to this issue to fix it??
I need your help..?

**Comment by david-allison-1** [comment]
The first part of the issue will be figuring out:

* What AnkiDroid provides for this issue (if anything)
* What Anki Desktop provides for this issue (screenshot listed in the thread in the OP)
* What AnkiWeb provides for this issue (do they have a FAQ that we can link to about a forgotten email?)
* Anything the user can do? Checking their gmail for a specific heading?

Finally:

* What we can do about it (probably adding a section to the FAQ on the wiki, with an in-app link), the implementation is up to you, but do post a design for us to discuss if you're unsure

**Comment by Paras-Saini** [comment]
Ok,  sir thanks for ur help..

**Comment by Paras-Saini** [comment]
Yeah, @david-allison-1 on AnkiWeb there is nothing if any user forgot their mail id only they can reset their password.
So, now  i am going with to prepare a good design for it.

**Comment by Paras-Saini** [comment]
FAQ for forgotten AnkiWeb Email Instructions-

1) I forgot my AnkieWeb email.
Ans- yes, You can click on the signup button again to sign in with new email id, if you don't want to access your AnkiWEb data.

(ii) But if you want to access your data from AnkiWeb and you forgot your email, you can do it, simply by answering a security question which you use when you sign up.

(iii)If you forgot your AnkiWeb email, you can check your email box and search for the email which you have gotten from AnkiWeb to verify your account when you first sign up.

(iv) And the final possibility is we can ask user to add a recovery email or mobile number at the time of their sign up, so that they can use it to recover their account at the time of their information lost.

@david-allison-1  here is my work for that, please let me know if it is workable. And if not i'll be thankful to you for your suggestion.

**Comment by david-allison-1** [comment]
Sorry, I don't understand, where did you find this information?

**Comment by Paras-Saini** [comment]
@david-allison-1 , i have wrote it by myself, according to possibility what we can do for to recover the forgotten email.
These are the steps.

**Comment by david-allison-1** [comment]
We don't control AnkiWeb, we can only advise the users

**Comment by Paras-Saini** [comment]
@david-allison-1 srry to say that i am not getting or not clearify with the question, please define it again and plz tell me what i have to do..

**Comment by david-allison-1** [comment]
AnkiDroid doesn't control AnkiWeb, but we have users that have problems with AnkiWeb, and we need to provide them with a good experience and solve their .

* If a user has forgotten their email for AnkiWeb, then they can't login.

* The task is to fix this.

----

We need to know "how" a user should go about finding their email address that they used: list the answers here.

Then, we should work on "how do we display this to the user in-app"

**Comment by Paras-Saini** [comment]
Yeah, thanks @mikehardy now it's clear to me.
I'll provide a good solution for it.

**Comment by Paras-Saini** [comment]
@david-allison-1 , i have come up with the solution, i.e, if a user has forgotten their email for anki web then they can go to the AnkiDroid app and click on left of the AnkiDroid app then an optional sidebar opened and then they can click on the setting and then click-->AnkiDroid(general settings) and after these steps they find their AnkiWeb account..

**Comment by david-allison-1** [comment]
> @david-allison-1 , i have come up with the solution, i.e, if a user has forgotten their email for anki web then they can go to the AnkiDroid app and click on left of the AnkiDroid app then an optional sidebar opened and then they can click on the setting and then click-->AnkiDroid(general settings) and after these steps they find their AnkiWeb account..

The problem statement in the main post states a "new user", so they will not be logged in.

----

I'll go through and find the answers to my questions so we can continue:

> * What AnkiDroid provides for this issue (if anything)

Nothing - user is new

> * What Anki Desktop provides for this issue (screenshot listed in the thread in the OP shows that you can get the email there if you're logged in)

If you are logged in, your email is listed under `Tools - Preferences - Network`

![image](https://user-images.githubusercontent.com/62114487/114580065-70f35000-9c76-11eb-9829-ce9bbf519b4c.png)

> * What AnkiWeb provides for this issue (do they have a FAQ that we can link to about a forgotten email?)

I can't find anything here

> * Anything the user can do? Checking their mail for a specific heading?

Query listed:

![image](https://user-images.githubusercontent.com/62114487/114580350-ae57dd80-9c76-11eb-93f3-e246b7700388.png)

----

Of these options, checking Anki Desktop is the easiest and most likely to succeed.

Now, we need a design for a page to link to, and how we're going to link to this in-app

**Comment by Paras-Saini** [comment]
Ok,, @david-allison-1, i'll prepare a good  FAQ design for this page.

**Comment by david-allison-1** [comment]
> Ok,, @david-allison-1, i'll prepare a good FAQ design for this page.

Your best bet would be to look to the [FAQ on our wiki](https://github.com/ankidroid/Anki-Android/wiki/FAQ), and consider adding a section

**Comment by Paras-Saini** [comment]
@david-allison-1 thanks, now i'm clear with my approach thanks very much for your help.

**Comment by gourish3** [comment]
If Paras wont be able to do..Please assign it to me.

**Comment by Paras-Saini** [comment]
I'm able to do it. I'm working on it..

**Comment by gourish3** [comment]
Okay..Great

**Comment by Paras-Saini** [comment]
@david-allison-1 
Forgotten AnkiWeb Email Instructions
Step-1 Go, on Anki if you logged in, then your email is listed under Tools->Preferences->Network.

Step-2 Or, you can go to your gmail account and search for the ankiweb and you find an email which you have received while you logged in for the first time to verify your email.

I have added these two points on wiki under FAQ section you can check and if any feedback and suggestion required then plz suggest me.

**Comment by Paras-Saini** [comment]
Srry, @david-allison-1 can you plz elaborate.??

**Comment by Paras-Saini** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#forgotten-ankiweb-email-instructions
This is the link of my changes @david-allison-1

**Comment by david-allison-1** [comment]
> https://github.com/ankidroid/Anki-Android/wiki/FAQ#forgotten-ankiweb-email-instructions
> This is the link of my changes @david-allison-1

The "diff" is a link from the history. In this case: https://github.com/ankidroid/Anki-Android/wiki/FAQ/820315e5323916bbfef42cd86aad4f25a20bb886

**Comment by infinyte7** [comment]
* User may not have only created account using gmail account.

**Comment by Paras-Saini** [comment]
> > https://github.com/ankidroid/Anki-Android/wiki/FAQ#forgotten-ankiweb-email-instructions
> > This is the link of my changes @david-allison-1
> 
> The "diff" is a link from the history. In this case: https://github.com/ankidroid/Anki-Android/wiki/FAQ/_compare/5fcb0754294e1dc577f0004827d100ab0e9f85b6...820315e5323916bbfef42cd86aad4f25a20bb886

Ok, @david-allison-1

**Comment by Paras-Saini** [comment]
Now, what next @david-allison-1 any suggestion plz??

**Comment by Paras-Saini** [comment]
> Now, what next @david-allison-1 any suggestion plz??

About my work??

**Comment by david-allison-1** [comment]
* Needs to be moved to a relevant part of the document
* You need to explain in what circumstances to take each step, it's not "step 1", or "step 2". When would you take the first step, and when would you take the second: likely as sub-section headings.
* You need to explain "what" to do in terms of finding the email, not for for a specific provider.

**Comment by Paras-Saini** [comment]
> * Needs to be moved to a relevant part of the document
> * You need to explain in what circumstances to take each step, it's not "step 1", or "step 2". When would you take the first step, and when would you take the second: likely as sub-section headings.
> * You need to explain "what" to do in terms of finding the email, not for for a specific provider.

Yeah, @david-allison-1 i got it. I do that.

**Comment by Paras-Saini** [comment]
@david-allison-1  https://github.com/ankidroid/Anki-Android/wiki/_compare/6ca8f8ce214668f6b0557d3881dd7c42c0dd4397#diff-c7bd425fd98aad1f9fef20099637bcbdcfadeb566ba1f83bb40ce484f195b8cf
Please have a look..??

**Comment by Paras-Saini** [comment]
@david-allison-1 https://github.com/ankidroid/Anki-Android/wiki/_compare/6ca8f8ce214668f6b0557d3881dd7c42c0dd4397#diff-c7bd425fd98aad1f9fef20099637bcbdcfadeb566ba1f83bb40ce484f195b8cf
Please have a look..??

**Comment by david-allison-1** [comment]
Are you sure that's the right link?

**Comment by Paras-Saini** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#forgotten-ankiweb-email-instructions

> Are you sure that's the right link?

No, srry @david-allison-1

**Comment by Paras-Saini** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#forgotten-ankiweb-email-instructions
This one is the correct link.

**Comment by david-allison-1** [comment]
I've fixed it up. Now we can add a link in the app to it.

**Comment by Paras-Saini** [comment]
Yeah, thanks @david-allison-1 .

**Comment by Paras-Saini** [comment]
> I've fixed it up. Now we can add a link in the app to it.

Where we have to add it in the app @david-allison-1

**Comment by david-allison-1** [comment]
> Where we have to add it in the app @david-allison-1

From the issue description:
> I would like to be able to access instructions on how to retrieve my email from the logon screen

**Comment by david-allison-1** [comment]
This is still a good first issue.

It requires adding a link/button to the login screen

**Comment by Emsloan** [comment]
I'd like to work on adding the link/button to the login screen.

**Comment by mikehardy** [comment]
Sounds great, have at it @Emsloan ! :-)

**Comment by sethbuchinger** [comment]
I see that this issue has not been resolved yet and has gone stale.  Can I take this on?

**Comment by david-allison-1** [comment]
Sure!

**Comment by sethbuchinger** [comment]
Just for clarification, it looks like you want to link to the instructions on the login screen, but will the instructions be in-app on a separate page, or should they link out to the browser?

**Comment by david-allison-1** [comment]
> Just for clarification, it looks like you want to link to the instructions on the login screen, but will the instructions be in-app on a separate page, or should they link out to the browser?

I'd be happy with a link to the FAQ, in-app help would be great, and feel free to do it, but I feel it's going above and beyond as this feature hopefully wouldn't often be used.

**Comment by sethbuchinger** [comment]
I noticed that if I add a text string in the 04-network.xml file to display the text to the user that there are quite a few languages supported.  Do I need to hand-translate the text string for each language, or is this done through a script of some sort?

**Comment by david-allison-1** [comment]
> I noticed that if I add a text string in the 04-network.xml file to display the text to the user that there are quite a few languages supported. Do I need to hand-translate the text string for each language, or is this done through a script of some sort?

Add to the root `04-network` with no translations, we upload to CrowdIn, which will deal with translation and adding the additional files

More info: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#adding-translations

**Comment by sethbuchinger** [comment]
Ah, thank you so much!  Sorry, I've should've seen that in the development guide

**Comment by Ankita562** [comment]
Hello @david-allison  i became a new user on Ankidroid and forgot  my email ,and thought if i could add a dialog box explaining the instructions before redirecting to github which would be easily understandable by non tech-savvy people who don't understand github.

**Comment by lukstbit** [comment]
@Ankita562 There's no need for that, the instructions are pretty clear about what someone can do to remember his email address.
