### ISSUE TITLE
Count of next day cards

### ISSUE THREAD

**Issue by Mornon** [ankidroid/Anki-Android#5846]
I'm confused about how Anki counts "Due tomorrow"'s cards: yesterday, statistics said I had 359 cards due today; today, I had 19 new cards, 42 lapses and 344 review; total, 405 cards.

I'm guessing Anki doesn't count buried cards in the next day's total, like if I have both the front and the back of a card one of those is buried and shown on the next day, but this doesn't account for almost 50 cards.

Are new cards counted in the next day total? If so, the gap is 27 cards, which I'm not sure is accounted by the buried ones, but maybe yes.

###### Reproduction Steps

1. Do cards one day
2. Check next day's due cards in Statistics
3. Check actual due cards

###### Expected Result

Statistics count and actual count should match

###### Actual Result

Statistics count and actual count don't seem to match

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi @Mornon ! This one might be best on the support mailing list for answers, can you post your question there for discussion? We can leave this open to capture whatever wisdom we arrive at there (and/or describe the actual defect if/when one is discovered)

**Comment by Mornon** [comment]
Sure; should I send it to public-forum@ankidroid.org?

**Comment by mikehardy** [comment]
Yep - I'm certain there are at least a couple people on there that watch their stats very closely and should be able to add some wisdom

**Comment by mikehardy** [comment]
Hey @Mornon I saw you got some responses, any wisdom you could summarize here?

**Comment by Mornon** [comment]
No really at the moment, just some hypothesis yet to be confirmed.

**Comment by Mornon** [comment]
I'm still trying to understand what's happening, but I'm not sure; as far as I understood, some cards aren't counted, like if one gets buried it doesn't show in next day's cards count.

**Comment by mikehardy** [comment]
#6331 perhaps?

**Comment by Mornon** [comment]
Could be, I'm not sure if that's all there is.
