### ISSUE TITLE
Startup: Permissions dialog "Deny" may not open App Permissions

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5847]
I tried to get this fixed along with #5740, but couldn't get it working. Minor as it requires "Don't Keep Activities"

###### Reproduction Steps

1. Turn on "Don't Keep Activities"
2. Revoke Storage Permissions
3. Open Anki - permissions dialog opens
4. Open the app drawer
5. Open Anki - permissions dialog still there
6. Deny

###### Expected Result

7. Taken to Application Permissions

###### Actual Result

7. Stuck on Anki Screen

###### Debug info
AnkiDroid Version = 2.10alpha52

Android Version = 9

ACRA UUID = 5a0ff95e-d1bb-46d6-9a61-d425ab3ab53d

###### Notes

`sendBroadcast(new Intent(Intent.ACTION_CLOSE_SYSTEM_DIALOGS));` doesn't seem to work.

`onRequestPermissionsResult` is called with blanks if re-called when a past dialog is up.  
`onRequestPermissionsResult` is not called from the past dialog

###### Research

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
@david-allison-1 marking this as a good first issue, you've already left good direction I think. Any other pointers (like: the startup sequence is in AnkiDroidApp - you can find the check for permissions in there, usually problems that only show up with "keep activities" off are related to onPause/onResume not storing their state correctly in the passed Bundle) you can think of then hopefully someone will have time.

**Comment by david-allison-1** [comment]
@mikehardy Knowing a little more, it probably just requires a `dismissAllDialogFragments()` call. Seems like a good first issue.
