### ISSUE TITLE
Tapping "Cards:" while creating a note discards it

### ISSUE THREAD

**Issue by Ammarking** [ankidroid/Anki-Android#5850]
###### Reproduction Steps

1. Create a new note
2. Type something into "Front" and "Back"
3. Tap "Cards: Card 1"
4. Press the back button, or tap on the tick

###### Expected Result
Peacefully returns to the menu where you were creating a note and continue creating it

###### Actual Result
Note gets discarded without being saved - everything written in it is gone

This happens for too often than I'd like to admit when I'm creating notes, I intend to tap Tags and tap Cards by mistake, and then there's no going back afterwards, I have to recreate the note from scratch.

###### Debug info
AnkiDroid Version = 2.9.4

Android Version = 9

ACRA UUID = 3b60fc4b-667d-482e-8f6d-0432ead63fd7

###### Research
*Enter an [ x ] character to confirm the points below:*

[y] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
**Kidding, x.**
[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x] I have searched for similar existing issues here and on the user forum
(I just searched the term "card" and found nothing related to it)

**Comment by mikehardy** [comment]
Interesting - that doesn't sound like a good experience - thanks for reporting this. I'm going to cross-link it with #5151 as the card template editor (where you go when you tap cards) and it's interaction with the card you are editing is already under edit for the 2.10 release and the fix would naturally go in those changes (or be built on top of #5151 when it's done)

**Comment by Ammarking** [comment]
Alright, great, looking forward to it :)
Thanks for replying.

**Comment by Anthropos888** [comment]
I can confirm that this also happens in the latest alpha when adding a card through the floating plus button on the deck list. Tapping the card name in the "add note" screen will open the template editor and pressing the phone's back button (or the back arrow in the template editor) doesn't go back to the "add note" screen but straight to the deck list.

**Comment by mikehardy** [comment]
This one is linked with 5151 (which is now in) but not closed yet I don't think.

**Comment by Abanoub-Asaad** [comment]
I think this issue needs to be closed because everything works well.
