### ISSUE TITLE
Random crashes when using specific font

### ISSUE THREAD

**Issue by Chrisstar56** [ankidroid/Anki-Android#5851]
###### Reproduction Steps

1. Use this font: https://sites.google.com/site/nihilistorguk/
2. Make your reviews (with Japanese characters)
3. Crash (which resets some of your progress, when you have to do another 20 reviews or more it can be quite tiring)

###### Expected Result
The app doesn't crash. It seems to happen a lot when using this font, if randomly happens after a number of reviews, and isn't tied to a specific card. It also can happen if I switch to the system font Midway, although it happens less often. The crash appears as a restart of the app, with lost progress.

###### Debug info
AnkiDroid Version = 2.9.5

Android Version = 10

ACRA UUID = 11048a61-bcd1-499a-af06-1afd2d2caa83

###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Hi @Chrisstar56,

Thank you so much for the bug report, and sorry for the inconvenience. We use Chrome to draw your flash cards, and large fonts can cause it to run out of memory and crash. 

We can't fix this directly, but I've put in a fix to AnkiDroid last week to improve the user experience (#5780). You can get this now by [joining our beta program and downloading 2.9.6beta1](https://docs.ankidroid.org/manual.html#betaTesting).

If you find any other issues, please let us know (either via the report crash dialog, and on here). We're on a bug quashing spree, and any help in tracking issues is invaluable.

Thanks for using AnkiDroid,
David

**Comment by mikehardy** [comment]
Indeed, this was a nasty side effect (review count being reset) of something we can't control per se but have mitigated. Since it's already out in beta I'm going to close this

related #5820 #4967

**Comment by mikehardy** [comment]
You may also be interested in #4856 as there was a discussion of Japanese fonts there and there are things you can do (fonts you can use) that are "lighter" on Chrome that might help for speed plus crash avoidance
