### ISSUE TITLE
Make sure database check is robust

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5852]
2.9.6 has a database check set for the userbase as part of #5823 

The first rule should be to do no harm so a database check should not result in a crash on a collection that was otherwise allowing reviews

Nevertheless I have seen two crashes via acralyzer during the database check for 2.9.6beta3 and now is an opportunity to make the fixIntegrity routine more robust as the majority of the beta testers have not updated to beta3 yet (meaning beta4 could see changes and better results)

Please note the line numbers within AnkiDroid are off because there is some unfixed between ACRA + D8/R8 that is not preserving the line numbers correctly, but it should be possible to puzzle out what's happening

```

03-22 05:56:08.859 I/AnkiDroid(25716): executing VACUUM statement
--
3 | 03-22 05:57:21.262 E/SQLiteLog(25716): (1034) os_unix.c:36228: (4) full_fsync(/sdcard/AnkiDroid/collection.anki2-journal) -
4 | 03-22 05:57:21.404 E/SQLiteLog(25716): (1034) statement aborts at 1: [VACUUM] disk I/O error
5 | 03-22 05:57:21.458 E/AnkiDroid(25716): DeckTask/ previously running task failed with exception: 14


java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:309)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: android.database.sqlite.SQLiteDiskIOException: disk I/O error (code 1034)
at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:7)
at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:3)
at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:4)
at io.requery.android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:3)
at io.requery.android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1)
at com.ichi2.libanki.DB.execute(DB.java:6)
at com.ichi2.libanki.DB.execute(DB.java:1)
at com.ichi2.libanki.Collection.optimize(Collection.java:3)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:118)
at com.ichi2.async.DeckTask.doInBackgroundCheckDatabase(DeckTask.java:5)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:45)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

```

03-22 09:03:53.157 I/AnkiDroid(18910): showStartupScreensAndDialogs() running integrityCheck()
--
2 | 03-22 09:03:53.237 I/AnkiDroid(18910): flush - Saving information to DB...
3 | 03-22 09:04:18.264 E/AnkiDroid(18910): Collection/ doInBackgroundCheckDatabase - RuntimeException on marking card


java.lang.IllegalStateException: Couldn't read row
at io.requery.android.database.CursorWindow.nativeGetString(Native Method)
at io.requery.android.database.CursorWindow.getString(CursorWindow.java:1)
at io.requery.android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:2)
at com.ichi2.libanki.Collection.fixIntegrity(Collection.java:36)
at com.ichi2.async.DeckTask.doInBackgroundCheckDatabase(DeckTask.java:5)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:45)
at com.ichi2.async.DeckTask.doInBackground(DeckTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
```

Ideally the work in fixIntegrity:
-  should be compartmentalized as much as possible,
-  if there is any possible way to recover we should
-  if there is any information at all we can show the user we should

All this may already be the case but with 2 problems out of 418 installs so far I don't like our odds as that could potentially scale to 7,177 problems out of our 1.5million users

**Comment by david-allison-1** [comment]
Proposal: 

1. Check for remaining storage space, and show a confirmation dialog, strongly advising users that they should free up some space before checking the database.

I think most errors will be due to disk space, if we avoid these conditions, we avoid the crashes.

2. Back up (I think we already do this)

3. Convert each check into a method (allows us to hone in on the errors).

4. Add a driver function, take a `Supplier<Either<List<String>, Exception>>`, run it in a try..catch block, call the method and return any problems

I'm unsure about what we do when we get an error. We previously only use "problems" to log. We'll scare the user. Continuing as normal, and logging, as long as we don't corrupt the database seems like the best option to me.

**Comment by mikehardy** [comment]
Yeah - this looks like about exactly what I was thinking except #4 of course because I'm a Java luddite ;-). By which I mean I just don't code that way, not that it is bad.

Backup is done at startup but the space issue is paramount

In fact, much of the syncing problems, possibly backup, and database recovery could all be improved by checking for available free space. It is my understanding from a different project I maintain that obtaining disk capacity values may be subtle in Android (cf. https://github.com/react-native-community/react-native-device-info/issues/346 ) but hopefully since we have a definite storage directory the system will return reliable information. As such I would do a disk space check right at startup and assume we might need 1x the database file size extra for vacuum to execute during fixIntegrity, plus obviously we would need 1x the database file size extra for a backup. 

I'm worried about changing behavior like #5 - what if there is no backup? what if restore fails? seems like it will blow up in our face. Is fixIntegrity running in a transaction (should be)? Simply shutting down without committing means that on next open the transaction is thrown away I think, and we should be consistent?

**Comment by mikehardy** [comment]
I still have a learning curve to handle with crowdin prior to 2.9.6 and other tasks will take my time Mon/Tue so if you want to run with it @david-allison-1 - that would be great. I can keep triggering the database check in future betas (and alphas) in order to exercise it. It looks like our update curve on betas and alphas has about a full week lag to mostly-full adoption (despite my release cadence being 1-2 days for alpha and 3-4 days for beta) if that's useful

**Comment by david-allison-1** [comment]
Looks like we probably can't use a transaction for all of it.

> It is important to note that the VACCUM command requires storage to hold the original file and also the copy. Also, the VACUUM command requires exclusive access to the database file. In other words, the VACUUM command will not run successfully if the database has a pending SQL statement or an open transaction.

https://www.sqlitetutorial.net/sqlite-vacuum/

---

I'll take a look later today, will try and have the PR in by Tuesday night, easiest thing will be to extract the methods. 

I recall having issues in the past with VACUUM/ANALYZE taking up more than 1x space, I'll do some digging later on.

**Comment by mikehardy** [comment]
Ah, but "optimize" can certainly be done after a transaction commit of any other fixups. In fact I think each fix is really atomic and idempotent so this may not be so difficult to handle from a corruption standpoint. Finally, while media can take a lot of space it's my understanding that the databases of even real power users is usually relatively small. I think only if you regularly do embedded images or something would it be large. That can happen but should be rare and in that case failing a vacuum with a note about space, but then opening the collection seems like a fine way to proceed

**Comment by mikehardy** [comment]
And thanks of course for the offer to work on it - all the help here is really appreciated, I'm starting to feel pretty optimistic about the future state of the project - getting close to effectively crash free is a massive achievement and is a solid foundation for new features again

**Comment by david-allison-1** [comment]
No worries at all. I'm confident we'll get there. We're not introducing more issues right now, so it's only a matter of time. We've got great velocity, and it's always great to say "already fixed that" when confronted with issues.

As a data point, my desktop collection is ~50MB (1.19 GB for the profile). I'm a long-term, but not power user. No embedded media and nothing crazy in terms of templates.

**Comment by david-allison-1** [comment]
@mikehardy I'm planning on breaking out the integrity checks from libAnki `Collection` to `CollectionIntegrity`. Would you have a problem with this?

**Comment by mikehardy** [comment]
I prefer to have libanki as close to upstream as possible but I suppose if each check gets extracted they'll at least leave a very clear / well-named placeholder in the same spot, and we have a few concerns desktop doesn't have that are repetitive (progress reporting, async, space concerns etc) so that's a natural next step. why not...

**Comment by david-allison-1** [comment]
Done some extracting. I'm not getting on with Java lambda syntax, but it's abstracted and we can do transactions now. I'll stick in a draft PR to see if the concept is acceptable.

**Comment by david-allison-1** [comment]
The first exception is simple to understand (VACUUM takes too much space). 

I'm not sure about how we got into a state where the second happened.

It's got to be in the following code, but it looks good to me.

https://github.com/ankidroid/Anki-Android/blob/a2f8c09475c240d98e9373076ffdacc9683d05bd/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1646-L1675

**Comment by mikehardy** [comment]
Hmm, traced it to this: https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/jni/sqlite/android_database_CursorWindow.cpp#L164

That can throw in this way https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/jni/sqlite/android_database_CursorWindow.cpp#L41 but the error message would have 'column' in it even if the native interpolation failed

It can also throw this way https://github.com/requery/sqlite-android/blob/master/sqlite-android/src/main/jni/sqlite/android_database_CursorWindow.cpp#L47 but that one is clearly different, has 'UNKNOWN' in it.

Not quite a dead end - concrete results:

So I look at git blame and see that it's just because I haven't merged that dependency update for requery into 2.9.x and that file was changed, it is throwing right there from our version:

https://github.com/ankidroid/Anki-Android/blob/hotfix-2.9.6/AnkiDroid/build.gradle#L174 (requery 3.28.0)

https://github.com/requery/sqlite-android/blob/3.27.1/sqlite-android/src/main/jni/sqlite/android_database_CursorWindow.cpp#L42

https://github.com/requery/sqlite-android/blob/3.27.1/sqlite-android/src/main/jni/sqlite/android_database_CursorWindow.cpp#L167

So window->getFieldSlot is null somehow: https://github.com/requery/sqlite-android/blob/3.27.1/sqlite-android/src/main/jni/sqlite/CursorWindow.cpp#L185

Maybe we could try to handle it gracefully but log a lot more information like cursor.getCount and the count of columns to make sure we aren't trying to read outside the result matrix somehow. Could be an OOM - I'm frequently surprised by what people stuff into their collections, so perhaps we could also keep a count of rows processed, and if there was a problem we could log how many were processed (a non-zero count indicating it was a row-specific problem).

Finally, the canonical way to KNOW we avoid it if it was an OOM (and fields is I think user-specified and could grow unbounded) is to convert it like this - our previous example of blowing up in exactly this way: https://github.com/ankidroid/Anki-Android/pull/4744/files

**Comment by david-allison-1** [comment]
Given the failing devices had multiple gigabytes of memory, I'll need to actively verify that we can OOM there, it seems unlikely.

I'll see if I can get a unit test to replicate this later on.

----

I'm torn on the implementation, we currently wrap all the `fixIntegrity` work in one large transaction, and commit/fail based on whether all the checks pass. 

It makes more sense to me to wrap each task in a transaction, so we can perform as many checks as we can, and log any of the intermediate exceptions, it'll fix the issues (and any others that we miss) but it's a divergence in functionality.

I can't see how any individual task failing could corrupt the database, or any dependencies between the tasks, but it's something that needs to be known for certain.

----

Also a question: is there internal rate-limiting in ACRA, or is running `AnkiDroidApp.sendExceptionReport` inside a loop going to spam our servers?

**Comment by david-allison-1** [comment]
Couldn't reproduce with Roboelectric.

Had a shot at running under AndroidTest, but got 

```
Process finished with exit code 1
Class not found: "com.ichi2.anki.tests.libanki.CollectionTest"
```

Messy code:

```java
    @Test
    public void largeFieldDoesNotTriggerOutOfMemory() throws JSONException {
        Collection col = CollectionHelper.getInstance().getCol(InstrumentationRegistry.getInstrumentation().getTargetContext());

        JSONObject model = col.getModels().get(col.getModels().ids()[0]);
        Note n = col.newNote(model);
        ArrayList<String> fieldNames = col.getModels().fieldNames(model);
        for (int i = 0; i < fieldNames.size(); i++) {
            n.setField(i, fieldNames.get(i));
        }
        StringBuilder stringBuilder = new StringBuilder(4 * 1024 * 1024);
        for (int i = 0; i < 4 * 1024 * 1024; i++) {
            stringBuilder.append("a");
        }
        n.setField(0, stringBuilder.toString());
        col.addNote(n);
        col.save();
        col.deleteNotesWithWrongFieldCounts(() -> {}, model);
    }
```

**Comment by mikehardy** [comment]
> It makes more sense to me to wrap each task in a transaction, so we can perform as many checks as we can, and log any of the intermediate exceptions, it'll fix the issues (and any others that we miss) but it's a divergence in functionality.

I agree with this.

> I can't see how any individual task failing could corrupt the database, or any dependencies between the tasks, but it's something that needs to be known for certain.

Every one of the is not just individual, but idempotent as well. All they do is converge things currently. Even if that were not the case in the future, the individual work units can be given a contract that says "you are in an individual transaction, if you need to do things that happen in one transaction, do them in one work unit" and go with it.


> Also a question: is there internal rate-limiting in ACRA, or is running `AnkiDroidApp.sendExceptionReport` inside a loop going to spam our servers?

Yep - that was one of the first things I did to make acralyzer usable as it used to be spammed horrifically: #4954 - if the exception is effectively similar it will be rate limited to 1 stack per device per AnkiDroid version (we clear the list of already-seen stacks on version upgrade)

**Comment by mikehardy** [comment]
> Couldn't reproduce with Roboelectric.
> 
> Had a shot at running under AndroidTest, but got
> 
> ```
> Process finished with exit code 1
> Class not found: "com.ichi2.anki.tests.libanki.CollectionTest"
> ```

I've seen this. You run androidTests (or one of the android tests) and it runs fine once. You make an edit and try again and nothing works, and it fails in a way that makes no sense, not even finding the test classes. This is an AndroidStudio / gradle artifact running emulator-based tests. I'm not sure what exactly the cause is but killing / restarting emulator + Android Studio + gradle daemon at least flushes it out. Actual solution is likely more focused and ideally it gets fixed, but that was one of the prime reasons to go with robolectric long again vs emulator-based and espresso - I just couldn't get them to be reliable enough that it increased my productivity vs nuking it


> 
> Messy code:
> 
> ```java
>     @Test
>     public void largeFieldDoesNotTriggerOutOfMemory() throws JSONException {
>         Collection col = CollectionHelper.getInstance().getCol(InstrumentationRegistry.getInstrumentation().getTargetContext());
> 
>         JSONObject model = col.getModels().get(col.getModels().ids()[0]);
>         Note n = col.newNote(model);
>         ArrayList<String> fieldNames = col.getModels().fieldNames(model);
>         for (int i = 0; i < fieldNames.size(); i++) {
>             n.setField(i, fieldNames.get(i));
>         }
>         StringBuilder stringBuilder = new StringBuilder(4 * 1024 * 1024);
>         for (int i = 0; i < 4 * 1024 * 1024; i++) {
>             stringBuilder.append("a");
>         }
>         n.setField(0, stringBuilder.toString());
>         col.addNote(n);
>         col.save();
>         col.deleteNotesWithWrongFieldCounts(() -> {}, model);
>     }
> ```

**Comment by david-allison-1** [comment]
Sounds good to me, will get the finishing changes in

**Comment by mikehardy** [comment]
2.10alpha55 is out with the fix, as soon as Google is done processing it and starts delivery...
