### ISSUE TITLE
Camera doesn't work when "Don't Keep Activities" is set 

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5863]
###### Reproduction Steps

1. Enable "Don't Keep Activities"
2. Take a Picture
3. Press the Checkmark

###### Expected Result

4. A preview should appear

###### Actual Result

4. Returned to the note edit screen with no image

###### Debug info
AnkiDroid Version = 2.10alpha56

Android Version = 9

ACRA UUID = de834bb3-3eb1-4646-bd8f-616dc9dacda3

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

###### Related

#3654

**Comment by mikehardy** [comment]
Luckily don't keep activities is a dev only setting, but it does serve as a canary in the coal mine for activity save/restore failures. Lower priority since it will affect so few then, but a problem nonetheless

**Comment by farjadilyas** [comment]
Has this been fixed? I can't reproduce it on Android 10, SAMSUNG SM-A805F (Physical Device)

**Comment by david-allison-1** [comment]
Works on my Google Pixel (Android 11), I'll try my Honor tomorrow and see if it's fixed
