### ISSUE TITLE
Front template has a problem: Found '{{=<% %>=}}', but there is no field called '=<% %>='

### ISSUE THREAD

**Issue by ZBWXYL** [ankidroid/Anki-Android#5865]
###### Reproduction Steps
Front template has a problem:
Found '{{=<% %>=}}', but there is no field called '=<% %>='
1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Hi @ZBWXYL,

I'm happy to look into this further. Could you fill out the remainder of the template so I can reproduce this on my device?

Thanks,
David

**Comment by ZBWXYL** [comment]
the template is:


Front:

<div class="h2 x-left" id='div0' style="display:block;"><%问题%></div>

<div class="h2 x-left" id='div1' style="display:none;"><%问题%></div>







{{=<% %>=}}

<script type="text/javascript">




[].forEach.call(document.querySelectorAll('.h1'),

function(V0) {

V0.innerHTML = V0.innerHTML.replace(/\marked/g,"★");

});













var arr = new Array,arr1 = new Array,arr2 = new Array;




/////////

[].forEach.call(document.querySelectorAll('#div0'),

function(V0) {

V0.innerHTML = V0.innerHTML.replace(/\{\{[c]\d+\:\:([^\{|\}]+?)\}\}/g,

function(cloze) {

var div30='<span id="div3" onclick="toggle(this)" class="cloze" cloze="@CLOZE@" cloze1="@CLOZE@1" cloze2="@CLOZE@2" wor="wor2">@......@</span>';

var dd1=cloze.indexOf("::"),dd2=cloze.lastIndexOf("::"),dd3=cloze.length,cc=0,cc1=0,cc2=0;

var word = cloze.substring(dd1+2, dd3-2);

var word1,word2;

switch(dd2-dd1){

case 0: word1=word;word2="<uu>　　</uu>"; break;

case 1: word1=word;word2="<uu>　　</uu>"; break;

case 2: word1=word;word2="<uu>　　</uu>"; break;

default:

if(dd3-dd2==4){word1=word;word2="<uu>&emsp;&emsp;</uu>";}

else{word1=cloze.substring(dd1+2, dd2);word2="<uu>&nbsp;&nbsp;"+cloze.substring(dd2+2, dd3-2)+"&nbsp;&nbsp;</uu>";}}

cc=arr.push(word)-1; cc1=arr1.push(word1)-1;cc2=arr2.push(word2)-1;

return div30.replace( '@CLOZE@',cc).replace( '@CLOZE@1',cc1).replace( '@CLOZE@2',cc2).replace( '@......@', word2);

}); });

/////////




/////////

[].forEach.call(document.querySelectorAll('#div1'),

function(V2) {

V2.innerHTML = V2.innerHTML.replace(/(\{\{[c]\d+\:\:[^\{|\}]+?)\:\:[^\{|\}]*?\}\}/g,"$1}}").replace(/\{\{[c]\d+\:\:([^\{|\}]+?)\}\}/g,'<span class="cloze">'+"$1"+'</span>');

});

//////////




//////////

function toggle(id) {




if (id.getAttribute('wor')=="wor2") {

id.innerHTML = arr1[id.getAttribute('cloze1')];

id.setAttribute('wor',"wor1");




return;}

if (id.getAttribute('wor')=="wor1"){




id.innerHTML = arr2[id.getAttribute('cloze2')];

id.setAttribute('wor',"wor2");




return;}}

/////////







//////////

function showAndHidden(){

var div0=document.getElementById("div0");

var div1=document.getElementById("div1");

if(div0.style.display=='block') {div0.style.display='none';}

else {div0.style.display='block';}

if(div1.style.display=='none') {div1.style.display='block';}

else {div1.style.display='none';}

if(div2.style.display=='none') {div2.style.display='block';}

else {div2.style.display='none';}

}

/////////




/////////

/////////




</script>




<div style="display:none">{{cloze:问题}}</div>





thank you very much!
















At 2020-03-25 21:04:52, "david-allison-1" <notifications@github.com> wrote:

Hi @ZBWXYL,

I'm happy to look into this further. Could you fill out the remainder of the template so I can reproduce this on my device?

Thanks,
David

**Comment by david-allison-1** [comment]
Hi @ZBWXYL,

What is the expected behaviour? Doesn't `{{=<% %>=}}` refer to a field named `=<% %>=`? I can't see this special-cased in the manual: https://docs.ankiweb.net/#/templates/fields

**Comment by dae** [comment]
I think this user is reporting an issue with either the computer version or AnkiMobile.

@ZBWXYL: the solution is to move {{=<% %>=}} to the very top of the template.

**Comment by ZBWXYL** [comment]
> I think this user is reporting an issue with either the computer version or AnkiMobile.
> 
> @ZBWXYL: the solution is to move {{=<% %>=}} to the very top of the template.

yes, it works! thank you very much!

**Comment by ZBWXYL** [comment]
@dae yes, it works! thank you very much!
