### ISSUE TITLE
[Android R] Deprecation - AsyncTask

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5872]
https://developer.android.com/reference/android/os/AsyncTask.

It's going to be a lot of work to get this recoded. 

Feels like it'd be an easy win (in combating crashes) to ensure that the collection/database isn't null in the next implementation.

Tangentially Related: #5519, #5404, #5524, #5518

**Comment by mikehardy** [comment]
That's a sleeping dog to let lie for a little while I think, I don't even want to contemplate doing that right now. If they deprecate it in the currently unreleased platform, that means there is at least a year after the release before the platform releases it, then there is the lag between new platform release and play store minimum target version before it's mandatory, my guess is at least 2 years total before it becomes a requirement at minimum, likely more like 3 years. Thankfully

**Comment by david-allison-1** [comment]
Replaced by #7108

**Comment by mikehardy** [comment]
dangit I looked too! missed this, didn't mean to duplicate
