### ISSUE TITLE
WebView crash fix string issue

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5876]
###### Reproduction Steps

1. Build the app after merge of #5820 (and especially after merge of (#5875 where every language flags it, vs just english where it was hiding)
2. ./gradlew clean jacocoTestReport
3. Check result of resources merge warnings in console

###### Expected Result

clean output from resource merge

###### Actual Result

One of these for each localized language:

```
/Users/mike/work/AnkiDroid/Anki-Android/AnkiDroid/build/intermediates/incremental/mergeDebugResources/merged.dir/values/values.xml:2329: warn: multiple substitutions specified in non-positional format; did you mean to add the formatted="false" attribute?.
```

This is the offending line in the merged file:

```
  2329      <string name="webview_crash_loop_dialog_content">System WebView failed to render card \'%s\'.\n %s</string>
```

Should be easy enough to find in the resources file, not sure what the proper solution is - I'm focused elsewhere and just logging it for now... @david-allison-1 do you have time to take a look?

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
@mikehardy On it, will get it in today.

**Comment by mikehardy** [comment]
all in good time - thanks!

**Comment by david-allison-1** [comment]
Anything else that I need to run? No changes in my inspection settings and my global gradle config is empty

```
PS C:\GitHub\Anki-Mike\Anki-Android> ./gradlew clean jacocoTestReport

> Configure project :AnkiDroid
WARNING: The following project options are deprecated and have been removed:
android.enableUnitTestBinaryResources
The raw resource for unit test functionality is removed.


Signing not ready for Gradle Play Publisher. Be sure to specify a signingConfig for variant 'release'.

> Configure project :api
WARNING: The following project options are deprecated and have been removed:
android.enableUnitTestBinaryResources
The raw resource for unit test functionality is removed.



> Task :AnkiDroid:stripDebugDebugSymbols FROM-CACHE
WARNING: Compatible side by side NDK version was not found for android.ndkVersion '21.0.6113669'
Compatible side by side NDK version was not found for android.ndkVersion '21.0.6113669'

> Task :AnkiDroid:connectedDebugAndroidTest
Starting 40 tests on LLD-L31 - 9

> Task :AnkiDroid:jacocoTestReport
[ant:jacocoReport] Classes in bundle 'AnkiDroid' do no match with execution data. For report generation the same class files must be used as at runtime.
[ant:jacocoReport] Execution data for class com/wildplot/android/rendering/graphics/wrapper/ColorWrap does not match.

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.2.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 4m 2s
79 actionable tasks: 17 executed, 62 from cache
PS C:\GitHub\Anki-Mike\Anki-Android> ./gradlew clean jacocoTestReport
```

**Comment by mikehardy** [comment]
I only see this as a warning spam once I did the l10n sync in #5822 and it propagated to all the localels - it was lurking there since the WebView but as only one line it didn't pop out whereas with dozens it did. I'd suppose it should be a lint rule or something, and we have that enabled in CI already (https://github.com/ankidroid/Anki-Android/pull/5744/commits/1115600dc311a645fdbc4ef5f900eb9fadec92eb) so - not sure if it's possible - but if lint could be set up to fail these then it won't happen again and we'll have proof of fixes, otherwise visual verification is the ticket

**Comment by david-allison-1** [comment]
I get errors with `./gradlew lint`, but no lint errors on my regular build

**Comment by mikehardy** [comment]
Indeed - gradle lint is a mined field no one has ventured into yet... #5026

**Comment by mikehardy** [comment]
out now in 2.10alpha58 as soon as google is finished processing it
