### ISSUE TITLE
err_CLEARTEXT_NOT_PERMITTED, getting error when loading files from localhost

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#5884]
###### Reproduction Steps

1.  Run localhost on android using termux and python
2.  edit url in card template to access data from localhost instead of web url

###### Expected Result
It should fetch data from localhost and show it in card template.

###### Actual Result
It is giving following error.
err_CLEARTEXT_NOT_PERMITTED
![(2)](https://user-images.githubusercontent.com/12841290/78065942-a78d5e00-73c6-11ea-8bf2-7feaff62b06c.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
This is standard for Android now. Maybe what you want is something like this in an debug AndroidManifest.xml - https://github.com/facebook/react-native/blob/master/template/android/app/src/debug/AndroidManifest.xml

Is this just for local development with debug builds? That's the only way I could see permitting plaintext now - so I'd take a PR that did it almost exactly like the link above, but I won't loosen android encryption requirements more than I already have with self-signed certificates in #5435

**Comment by infinyte7** [comment]
Okay, I will look into it.

**Comment by infinyte7** [comment]
I have added following in ```network-security-config.xml``` then it working. 
It is loading data from localhost if ``Access-Control-Allow-Origin``` is set up in localhost configuration file.
```
    <domain-config cleartextTrafficPermitted="true">
        <domain includeSubdomains="true">localhost</domain>
        <domain includeSubdomains="true">127.0.0.1</domain>
    </domain-config>
```

Should I create PR?
