### ISSUE TITLE
Updates to database structure

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#5886]
This isn't an issue with the app, so please let me know if this was the wrong channel to report this on. [This commit](https://github.com/ankitects/anki/commit/35c03af520740a7bc98d6a7e6da501b785482975) indicates that Anki will have a change to it's database schema: The deck config will get split into a separate table while the collection is open and reverted when closed for compatibility with old clients. Full details are in the commit I linked to. The code will eventually have to be updated as the commit hints that the reverting after collection close will stop in a future version of Anki. Our [database structure document](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure) will also have to be updated. I haven't looked too far into the code of the commit, but I'm guessing this just means the dconf field of the col table will now point to a new dconf table?

**Comment by mikehardy** [comment]
@sudomain thanks for flagging this - @dae just for a really rough idea on a typical Anki deprecation cycle, how long do you leave things deprecated for before removing backwards compatibility?

Some combination of knowing that and thinking about how long our old clients persist (specifically if we cut off access to updates like when we bump minSdkVersion as proposed in #5665 to move to API16) will inform the priority of working through this on our side

**Comment by dae** [comment]
No action is required at the moment - these changes are undone before closing the collection. Even if that changes in the future, Anki will likely continue to undo the changes when exporting/doing a full sync to preserve compatibility.

**Comment by david-allison-1** [comment]
No action required at the current moment. Marking this as WONTFIX until these changes are requested, or likely to be required in the future.
