### ISSUE TITLE
Rarely statistics page uses wrong font

### ISSUE THREAD

**Issue by agentydragon** [ankidroid/Anki-Android#5889]
Note: this is low-severity and low-frequency. I don't actually expect anyone to have the time to work on this anytime soon if ever :)

###### Reproduction Steps

I'm not sure how to reproduce this. It happens to me randomly, in <5% of the times that I open the Statistics page.

###### Expected Result

Statistics page should have its usual sans-serif font

###### Actual Result

Font in statistics page sometimes switches to monospace:
![image](https://user-images.githubusercontent.com/714892/78101238-25616180-73e7-11ea-91ec-ba5362a7ea70.png)

Interestingly the headings are still styled in the correct font.

Issue #3882 sounds like it might be related.

###### Research
[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Hi @agentydragon,

Thanks for the report! I'll see if I can get to this this week.

Could I get:

* A screenshot of your "Appearance" settings page?
* Your current system font

It'd also be useful to get your ACRA ID if you've turned on crash reporting. You can find this in Settings -> Advanced -> About AnkiDroid -> Copy Debug Information.

Thanks for using AnkiDroid,
David

**Comment by agentydragon** [comment]
Hi @david-allison-1,

Appearance settings:
![image](https://user-images.githubusercontent.com/714892/78116490-a7ac4e80-7404-11ea-8115-1f5320385ea2.png)

System font: default on Pixel 3 XL. I'm not sure which one it is and couldn't immediately find it in my system settings, but it's a sans-serif font, I'd expect probably Roboto or Noto.

AnkiDroid Version = 2.9.6beta5
Android Version = 10
ACRA UUID = c3eceb0b-5174-4c5c-b784-6cfedc33393f

**Comment by david-allison-1** [comment]
Thanks!

Has this just started occurring?

What language/culture is your Android in (& could you list them all if you change them often)?

----

Likely relevant code: https://github.com/ankidroid/Anki-Android/blob/0b53caca937e05319c009d4bd4342c19c6e6193f/AnkiDroid/src/main/java/com/ichi2/anki/stats/OverviewStatsBuilder.java#L174 We use a WebView to display the overview and this class contains the logic to build the HTML.

**Comment by agentydragon** [comment]
I think I've noticed this maybe like 5 times in the last 3 months. I haven't figured out a way to trigger it...

My Android's system language is "English (Switzerland)". I have only this language/culture on my phone and don't switch.
