### ISSUE TITLE
Problem with time change

### ISSUE THREAD

**Issue by Simontawan** [ankidroid/Anki-Android#5912]
Since last day, the current time zone in my country is the Central European Summer Time (CEST/UTC+2) instead of the normal Central European Time (CET/UTC+1).

The default setting is that a new day starts 4 hours after midnight and therefore at 4 am. But Anki still adheres to the winter time and did not recognize the chance of the time zone, so a new day starts currently at 5 am although “4 hours after midnight” is still set.

It would be nice if Anki could recognize changing time zones.

**Comment by mikehardy** [comment]
Timezone + multi-device sync is riddled with little corner cases right now
I hate to spam with cross links but you may find something useful in one of these as a workaround:
#5809  #5207  #5805 #5082  #5831 #5637  

If you try some things (even if it's just moving the start of day and syncing) and it works for you across all your devices I'd love to know
