### ISSUE TITLE
Reading JSON from database is extremely slow

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#5921]
I've just tested. Reading my JSON configuration for note type from the database is extremely slow. It takes a minute on my phone (I've some huge note type). I just tried, and if the chunks size is changed from 256kb to 1MB, it still works (that's the limit of cursor) and becomes quite quicker. Is there a reason why such a low number was chosen ?

**Comment by mikehardy** [comment]
I don't believe it was chosen with intention, I don't recall any benchmarks
If 1MB is the limit of the cursor that works for me, we could try that
@david-allison-1 something to keep in mind if you chunk-load that other field we were having issues with

**Comment by mikehardy** [comment]
Fixed by #5925
