### ISSUE TITLE
[ACRA 2.9.6] - Deck Corruption on changing deck in Card Browser to Filtered Deck

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5932]
https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/cf94bd80-4108-4796-bd23-d01499107272

```
java.lang.RuntimeException: org.json.JSONException: No value for maxTaken
at com.ichi2.libanki.Card.timeLimit(Card.java:3)
at com.ichi2.anki.AbstractFlashcardViewer.initTimer(AbstractFlashcardViewer.java:12)
at com.ichi2.anki.Reviewer.displayCardQuestion(Reviewer.java:1)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.displayNext(AbstractFlashcardViewer.java:11)
at com.ichi2.anki.AbstractFlashcardViewer$NextCardHandler.onProgressUpdate(AbstractFlashcardViewer.java:1)
at com.ichi2.async.DeckTask$TaskListener.onProgressUpdate(DeckTask.java:1)
at com.ichi2.async.DeckTask.onProgressUpdate(DeckTask.java:3)
at com.ichi2.async.DeckTask.onProgressUpdate(DeckTask.java:1)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:775)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loop(Looper.java:213)
at android.app.ActivityThread.main(ActivityThread.java:8147)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
Caused by: org.json.JSONException: No value for maxTaken
at org.json.JSONObject.get(JSONObject.java:399)
at org.json.JSONObject.getInt(JSONObject.java:488)
at com.ichi2.libanki.Card.timeLimit(Card.java:2)
... 14 more
```

**Comment by david-allison-1** [comment]
###### Reproduction Steps

1. Create card in "Deck"
2. Move to "Filtered Deck 1"
3. Move to "Filtered Deck 2"
4. Review
5. Crash

**Cause:**

Card with a `did` of "Filtered Deck 2", and no `odid`

**Expected:((
`did` of "Filtered Deck 2" and odid of "Deck"

**Comment by david-allison-1** [comment]
We're missing: https://github.com/ankitects/anki/blob/3b619c4ca5dbb12236fddfb9f96ae34c8554d3af/qt/aqt/browser.py#L1649-L1651

"Cards can't be manually moved into a filtered deck."

**Comment by david-allison-1** [comment]
We might annoy a few users by fixing this. 

AFAIK, you /can/ review cards in the "wrong" filtered deck without issue (e.g. doing an interval search is a temporal query, and some items would be invalid for the query if reviewing on the next day). moving them there just isn't supported in Anki Desktop.

We allow people to do so, albeit with this bug of not setting `odid`. Fixing this would block deck transfers to a filtered deck, which IMO is a useful feature.

**Comment by mikehardy** [comment]
@dae should it be possible to move a card from one filtered deck to another? (I believe that's the crux of it here)

@david-allison-1 from my perspective the most important part we play in the Anki system (apart from SRS of course) is working together seemlessly, so if it's not in AnkiDesktop I will easily choose to annoy the users and follow Anki Desktop unless there is some Android-specific reason not to do so

If Desktop starts allowing it (via a patch we propose or Damien saying "sure" and doing it himself) then we can do it and fix the "how we do it" here, otherwise we need to block it also

**Comment by dae** [comment]
This is not something Anki tries to support at the moment - cards can only be added to a filtered deck by (re)building it, which invokes moveToDyn, which assumes the cards are in a regular deck.

**Comment by mikehardy** [comment]
Thanks @dae ! Okay then for us @david-allison-1 that means we block now to match, pending any accepted patch upstream on Desktop

**Comment by david-allison-1** [comment]
Cheers! Will see if I can get in two PRs (one for the fix, one for the integrity check) later on today.

**Comment by david-allison-1** [comment]
@mikehardy For the integrity check, we won't know where to return the cards to.

I would like to make a new deck, called "_Recovered" (in the user's local language), and tag them as "AnkiDroid_recovered".

I worry that localising the tags and deck name will make this feature harder to provide support for, do you have any suggestions for a better design?

**Comment by mikehardy** [comment]
Hmm. Maybe put them in the default deck (which always exists), and just add a tag instead? We probably have some localized words we can repurpose for the tag? If this case is found you can pop a dialog explaining the situation and maybe link to a FAQ on what happened and how to do the search - we can point everyone there? I'm guessing this is exceedingly rare so I wouldn't invest too much time in it so long as it works and we can describe it

**Comment by david-allison-1** [comment]
FAQ sounds great. I'm not sure about the default deck, I assume many users still use it (or rename it to re-purpose it). We can technically create a deck without issue, but we might be breaking the principle of least surprise by adding a deck.

I'm leaning towards having the tag be English-only so we can provide the exact tag search in the FAQ (Emoji? 🐞 😉)

I don't really know on this one. Might not matter too much

**Comment by mikehardy** [comment]
The default deck is always deck id 1 if I'm not mistaken 
I'm fine with an english-only tag so we can be extremely precise about the FAQ
I could be wrong but I assert this will be a vanishingly small occurrence in general use. Might be just this one person even

**Comment by david-allison-1** [comment]
Yes, but AFAIK `did 1` can be renamed and used as a regular deck.

I hope you're not wrong. Suppose the support volume will tell.

**Comment by mikehardy** [comment]
It absolutely can be renamed and is frequently used I think (it should be really), just saying it's guaranteed to exist - it's a useful home for orphans

**Comment by david-allison-1** [comment]
Slipped my mind: tags are a per-note basis. Shouldn't cause an issue though
