### ISSUE TITLE
keyboard input and selected text modification is so laggy when selecting words

### ISSUE THREAD

**Issue by AliEmn95** [ankidroid/Anki-Android#5938]
###### Reproduction Steps

1.sometimes when you type sth in the field
2. and then select a word or some words to add a cloze deletion
3. when you try to modify what you already have selected with dragging the two dots around the selection

###### Actual Result
the dragged dot gets glitchy and unresponsive and laggy and the same as well for the keyboard input buttons.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x  ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Hi @AliEmn95,

Thanks for the report!

How many cards do you have in your collection? It seems we perform a duplicate check on each modification of the text field (I believe on the UI thread), which is likely the cause of your lag.

Ref:

https://github.com/ankidroid/Anki-Android/blob/8a79dd14b6d7e1b865a466d4dc561914ba312f59/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1270-L1276

**Comment by david-allison-1** [comment]
`duplicateCheck()` was 4ms, which is bad, but didn't seem like it affected the UI.

I've added in #5939 as an educated guess. It feels smoother, but I wasn't able to produce the massive amount of lag mentioned.  

Would you be happy testing whether things improve when this hits the latest alpha build? @AliEmn95

**Comment by mikehardy** [comment]
Instructions for joining testing program in Google Play, along with the mailing list to join that signals you should get alpha builds: https://docs.ankidroid.org/#betaTesting

**Comment by AliEmn95** [comment]
I have about 35 thousand cards in my collection right now. 99 percent of them added via my phone (because of finger pains I have had).

I have not really tried to select or modify any kind of words in the extra field cause there is no need to add cloze deletions there. It has only happened to me when editing in the first field so far (as this has made me notice).
