### ISSUE TITLE
AnkiDroid fails to run with JDK1.14

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#5955]
###### Reproduction Steps

1. Use your favorite package manager to install JDK1.14 (we use jabba in CI)
2. Start an emulator
3. Run `./gradlew clean jacocoTestReport` from master as of Apr 8 2020 (at least)

###### Expected Result

Everything runs fine

###### Actual Result

There is a deprecation warning, but for historic reasons we consider deprecation warnings as errors in builds so that we are forced to at least consider them and file issues, like now

The deprecation warning should be understand and handled so we work with the current version of the LTS JDK

This was exposed by #5953

**Comment by david-allison-1** [comment]
For future googlers:

```
warning: [options] source value 7 is obsolete and will be removed in a future release
warning: [options] target value 7 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
[options] source value 7 is obsolete and will be removed in a future release

[options] target value 7 is obsolete and will be removed in a future release

[options] To suppress warnings about obsolete options, use -Xlint:-options.

error: warnings found and -Werror specified
warnings found and -Werror specified
```

The fix is to add:

```gradle

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```

to `build.gradle`. 

----

This doesn't fix all of the errors.
