### ISSUE TITLE
[2.9.6] Can I change cloze symbol?

### ISSUE THREAD

**Issue by Cho-jin** [ankidroid/Anki-Android#5968]
cloze symbol is [...].

Can I change [...] to something.

For example : [...]   ->  ___

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
No, that is not customizable
