### ISSUE TITLE
Rethink Check Database on Update - Forces Full Sync if problems found and user can lose data

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#5976]
If we find problems in `fixIntegrity()`, we force a full sync. That's likely because we don't set `mod` or `usn` in the fixes.

But, we haven't provided the user with an option to sync beforehand, so this is likely to either erase their unsynced progress from AnkiWeb, or reverse the fixes and remove their AnkiDroid unsynced progress.

Anki does the same, but also has a `syncable problems` collection.

https://github.com/ankitects/anki/blob/0c5f22f4ae7be0b1e5ffcb1d5a8dddd9f73930f0/pylib/anki/collection.py#L1002-L1003

----

Reported by v4mp1r3 on Discord.

> motivation:  in the latest AnkiDroid update, it wanted to run a database recheck... so I did, and it "shrunk" the database by 1kb (some metadata issue?)... anyway, when attempting to then sync (computers and AnkiWeb were synced previously), it then said that my phone was unable to merge due to conflict, so I then had to repull from web...

**Comment by mikehardy** [comment]
🤔

**Comment by Arthur-Milchior** [comment]
I know DAE told me at some point that fix integrity would be moved to back-end. I don't know whether it occured yet. I don't know either whether it's worth porting changes to java in this case. It would be possible to just use an exception the same way we do when note type are modified, and allow user to stop or process.

**Comment by dae** [comment]
I don't see this being called on update anymore - if I'm wrong, please let me know.
