### ISSUE TITLE
Night Mode shows blank copy/paste pop-up

### ISSUE THREAD

**Issue by C354R-4** [ankidroid/Anki-Android#5977]
![IMG_20200411_162813](https://user-images.githubusercontent.com/63366546/79053185-ac95ad00-7c11-11ea-89b9-9a7a0d246dca.jpg)

**It only occurs on Ankidroid and just on Night Mode**
Device: Redmi 6A
Ankidroid 2.9.6

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
What operating system version do you have, and do you have night mode engaged at the system level as well?

**Comment by C354R-4** [comment]
Its MIUI Global 11.0.7.0 | Stable
android 9 PPR1.180610.011
No, I don't.

**Comment by mikehardy** [comment]
Thanks! I'll see if we can reproduce that here

**Comment by C354R-4** [comment]
Thank you very much :)
