### ISSUE TITLE
[Feature Request]: User Onboarding - Add in Default Note Type: "Type Answer"

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5979]
I'm happy to take this on myself if the Feature Request is accepted.

It's currently a frustrating process for a new user to add in a "Type The Answer" note type.

It's a fairly common occurrence, and would be useful as a default for a new user to use when they start the program for the first time.

I'd like to add a template with the following Front Template: `{{Front}}{{type:Back}}`.

This feature is not downstream in Anki, I can't think of any compatibility issues (other than: collections made in Anki won't have this type).

This will make the "Add Note Type" dialog (Add/Clone Note Type Dropdown specifically) slightly more complex, as it will add in "Add: Type Answer" and "Clone: Type Answer" to this screen.

**Comment by mikehardy** [comment]
I like it and bet a PR upstream in Desktop would be accepted. I'd merge it here either way though

**Comment by david-allison-1** [comment]
This already exists (and has done for years 🤦), sorry about wasting your time. 

Learned something new today.
