### ISSUE TITLE
File names now show up in the browse list

### ISSUE THREAD

**Issue by Sharkara98** [ankidroid/Anki-Android#5987]
![Screenshot_20200413-030344](https://user-images.githubusercontent.com/63555375/79075325-7e10f280-7d35-11ea-9000-fea7a2f15efe.png)

The added file names make it difficult to efficiently browse through as they're in the way. On the main forum for AnkiDroid, I saw another person reporting the same issue but they weren't given any solutions for the issue. This has only been an issue since the latest update. I apologise if this has already been reported on here.

**Comment by Sharkara98** [comment]
Are you going to respond to the issue now?

**Comment by mikehardy** [comment]
Quick note: this might be a language thing but your comment sounds demanding. We're volunteers. I may respond. Someone else may respond. No one may respond. You could propose a code fix for it yourself. But remember it's open source (also known as "fix it yourself") and we're volunteers. So go easy, please

That said, #5158 has the current discussion on the topic including a comment I just made - you can follow along there as it will likely track the bulk of the work, then close this incidentally.
