### ISSUE TITLE
Advanced Editor uses original field values rather than current values

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#5992]
This is more problematic with the Visual Editor, but I want to get confirmation that I can get a fix in, and it won't interfere with plans for fixing #5011. 

If so, it's planned for tomorrow.

###### Reproduction Steps

1. Open Note Editor For Existing Note with text in "Front" field.
2. Type in Text in "Front"
3. Open Advanced Editor

###### Expected Result

4. You see the changed text in the advanced editor

###### Actual Result

4. You see the original text in the advanced editor

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum.

###### Relevant Code

https://github.com/ankidroid/Anki-Android/blob/1a1a041e9d18326233c24f3a1017cf58b7c42bac/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1147-L1152

**Comment by mikehardy** [comment]
#5011 is almost complete in CardTemplateEditor, if this is in NoteEditor, or if there is something not being passed correctly to the field editor I don't think they would collide. Either way I could take the collision, I have #5011 totally up to date with master now and am just one unit test and SQL change from having it done, so it shouldn't be too hard to merge in whatever
