### ISSUE TITLE
Home screen widgets stopped showing review counts

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#5995]
###### Reproduction Steps

1. Add the widget to the home screen.
2. Wait until the next day with non-zero reviews.

###### Expected Result
As previously, the widget should show the review and time count.

###### Actual Result
The widget doesn't show the numbers until Anki is opened and the user goes back to the home screen. This happens every day.

I have the feeling this has been happening for the last week or maybe two, I think I got an update back then, I'm not sure. It used to work not so long ago.

###### Debug info
AnkiDroid Version = 2.9.6
Android Version = 10
ACRA UUID = 40867cd2-e39d-48b4-a992-512b39c2f7bb

###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Hi @wujek-srujek,

Thanks for the report! 🙏 2.9.6 started rollout after April 3

Could you edit the debug information to include your ACRA ID?
 
All the best,
David

**Comment by wujek-srujek** [comment]
It might actually be an issue with my phone. Today, I needed to restart my phone, so I took a look at the widget, still no counts, restarted the phone, and then the counts were there.
Let me observe it for the next couple of days, I'll be back.

**Comment by mikehardy** [comment]
I use the widget, and I see the counts, for what it's worth.
I'm on the alpha series so that's with 2.10alpha69 at the moment but it's never really stopped working

**Comment by wujek-srujek** [comment]
The widget works for me now, after phone restart. I'll close the ticket.

I seem to have an issue with my phone, I need to restart it now and then, otherwise no push notification are shown, and the widget got healthy as well.

Sorry for the noise.
