### ISSUE TITLE
Trim and no initial upper case when creating new cards

### ISSUE THREAD

**Issue by l-g** [ankidroid/Anki-Android#6005]
When creating new cards using Swiftkey as keyboard the initial letter becomes upper case and if one uses Swiftkey's autocomplete to finish the (last) word, a space is added at the end, preventing/worsen (?) the duplicate search.

When learning a new language I want to save initial uppercase letter for words that should be spelled with an initial upper case letter, the rest (≈99 %) should have an initial lower case letter.

It would be nice if this initial uppercase and trailing space somehow could be prevented, that is by introducing a couple of settings for this behaviour.

###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I used to use Swiftkey and have switched for this reason. I just re-checked the message boards and they haven't listened to users for 3 years I don't think they will now.

I don't want to start adding text transformations here so I'm going to say no - I recognize keyboard choice is personal but at least there are lots of options, I'd find another one

**Comment by l-g** [comment]
Most keyboards automatically inserts capital letters in the beginning and space at the end. This is not Swiftkey specific.

**Comment by mikehardy** [comment]
if I understand correctly gboard, the default android keyboard does not do the auto-space thing? Not sure about initial caps. I dunno, if it's that prevalent and you can propose a preferences toggle to turn on input text transformation and implement a solid PR for it, I could consider it. But this seems like a keyboard issue, not an AnkiDroid issue
