### ISSUE TITLE
Add option to disable JaCoCo on local debug builds

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6009]
JaCoCo is unstable for me (often hanging) and I don't use it. I'd like to add some functionality to our gradle script allow me to set a machine variable to disable it.

If this is accepted, I'm happy to do it, although a hint in the right direction for implementation would be much appreciated.

----

I haven't delved into the area yet, so this might be a simple fix. It's not an area of expertise for me

**Comment by mikehardy** [comment]
Interesting, I've never seen a stability issue. I think it's just memory intensive maybe?

If you haven't tried using it you might actually dive into the little HTML tree it generates every time you run the unit or connected tests, it's pretty good in my opinion

That said if you're not intending to use it on even some runs it would be nice to have it be optional. I think it is already though, have you tried `./gradlew :AnkiDroid:testDebugUnitTest` ?

Or even something like `./gradlew :AnkiDroid:testDebugUnitTest --tests *PieChart*`

**Comment by mikehardy** [comment]
(`./gradlew tasks` is somewhat illuminating as are the performance scans etc - I spent some time optimizing that a while back but performance is subject to entropy more than any other thing so I imagine it's all rusty again)
