### ISSUE TITLE
Feature request: Allow per deck zoom setting

### ISSUE THREAD

**Issue by jgarvin** [ankidroid/Anki-Android#6011]
Most of the time, 100% zoom is fine for reviewing. However for foreign languages with symbols I'm not as used to seeing, like Chinese or Hebrew, I always go into settings and temporarily crank the zoom up to 160%. I would leave it there but then cards in my math decks stop fitting on the phone screen. If we could customize this by deck it would be great.

**Comment by DeltraEcho** [comment]
```
<script>
if("{{Deck}}" == "DECKNAME") {
    var fontsizemultiplier = 1.5;  var x = document.querySelectorAll(alldivs); var i = 0;
    for (i = 0; i < x.length; i++) { x[i].style.fontSize = (getComputedStyle(x[i], null).getPropertyValue('font-size').replace("px", "") * fontsizemultiplier) + "px"; }
}
</script>
```

**Comment by jgarvin** [comment]
@DeltraEcho workaround probably works, but it's not as user friendly a real GUI option.

**Comment by jgarvin** [comment]
still searching for solutions
