### ISSUE TITLE
Feature request: cloze deletion button and/or keybinding in NoteEditor.java

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#6014]
Two closely related features I'd like to see and submit a PR for, pending approval from the maintainers:

1. A `CTRL + SHIFT + C` keybind to add a cloze deletion in noteeditor.java
2. A `[...]` button in the regular noteeditor for adding a cloze deletion. I know there was discussion about this for the WYSIWYG editor #1377 , but I'd like for this to also be in the default noteeditor. Currently it is difficult to add a cloze reference ({{c1::}}) to a field for users on API 22 or lower ([5% of users](https://github.com/ankidroid/Anki-Android/issues/1377#issuecomment-611190305)). My preference would be to have this button appear at the top of the screen next to checkmark button in the add/edit notes screens.

Since screen real estate is valuable, I can have this button appear only for models that are based on the Cloze model (i.e. if type == 1 in the [models jsonobject](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure#models-jsonobjects))

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Just commenting. Will leave the approval to Mike, but looks good to me!

This won't clash with the Visual Editor. I don't see the HTML note editor going anywhere 

----
A few points to consider for the design:

* Do you have an appropriate icon for Cloze deletions? I don't think we have one already. I'm using `settings_ethernet` for the visual editor (you can access it via Add - Vector Assets). 

![image](https://user-images.githubusercontent.com/62114487/79368740-cdc70800-7f47-11ea-8798-bc005e8170c4.png)

* Do you plan to warn the user, or block the action if Ctrl+Shift+C is pressed.
  * Anki Desktop warns
  * Personal Preference: Warning user via snackbar with a button to change to the Cloze type.

**Comment by sudomain** [comment]
> Do you have an appropriate icon for Cloze deletions? 

I don't, I was thinking [...] as that's what desktop uses

> Do you plan to warn the user, or block the action if Ctrl+Shift+C is pressed on a non-cloze type. 

I'd forgotten about that desktop warning. Good catch. My PR will warn using a snackbar

**Comment by mikehardy** [comment]
Sounds fine yeah, and David's points are good. It's not too hard to kick out an SVG icon and those are valid across our whole API version skew, so I'd say use '[...]' and just make an actually good icon for it

**Comment by david-allison-1** [comment]
@sudomain still interested I presume?

**Comment by sudomain** [comment]
Yup. I hope to get to it soon

**Comment by david-allison-1** [comment]
A button was added in #6497
