### ISSUE TITLE
When editing card type of a Cloze-based note type, the user  is allowed to add more cards types. This is invalid for cloze models

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#6015]
###### Reproduction Steps
tap:
1. Manage note types
2. Long press on a cloze based model
3. Edit card types
4. Hamburger button in top right
5. Add

User will be prompted about a full sync, then the can add many card types to a cloze model.

###### Expected Result
The card type editor should check if the model is based on the cloze model (i.e. if type ==1 in the [models json object](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure#models-jsonobjects)) and it should not show the add/delete menu items

###### Actual Result

![Screenshot_2020-04-15-13-26-31](https://user-images.githubusercontent.com/30786326/79368865-15389e80-7f1e-11ea-97e8-0f40b66ebb0b.png)
Cards 2-4 are invalid here as cloze models can only have 1 card type

I haven't checked to see what happens after syncing, but I imagine desktop would report a corrupt database.
###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Fascinating - hadn't thought about that. I'm about to land a fix for CardTemplateEditor - I will stack this up for immediately after that - cross-linking here #5151 

@sudomain can you 100% confirm that on desktop if it is a cloze menu type and you go to edit the template, add/delete are disabled?

**Comment by sudomain** [comment]
> can you 100% confirm that on desktop if it is a cloze menu type and you go to edit the template, add/delete are disabled?

It is confirmed and the only card type related setting that can be changed for cloze models is the "Browser appearance" setting. Per the [cloze templates section of the anki manual](https://docs.ankiweb.net/#/templates/generation?id=cloze-templates):
> The cloze note type functions differently from regular note types. Instead of a customizable number of card types, it has a single type which is shared by all cloze deletions on a note.

**Comment by mikehardy** [comment]
Thank you - as soon as #5151 lands I can fix this immediately, it'll be a quick fix
