### ISSUE TITLE
Files names are being displayed in the browse list

### ISSUE THREAD

**Issue by Sharkara98** [ankidroid/Anki-Android#6051]
![Screenshot_20200420-003401](https://user-images.githubusercontent.com/63555375/79690746-612d6f80-829f-11ea-80bc-82dc009513e8.png)

###### Reproduction Steps

1. Open a deck with audio files

###### Expected Result
Only the question in the browse list displayed

###### Actual Result
Audio file names are displayed in the browse list

###### Debug info
AnkiDroid Version = 2.9.6

Android Version = 9

ACRA UUID = 255f475e-2863-4db2-a65b-d1f085f3c4ca

###### Research
*Enter an [ x ] character to confirm the points below:*

[X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[X] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
duplicate #5987

**Comment by Sharkara98** [comment]
Nobody answered this issue so I opened it again and you immediately closed both without offering a solution.

**Comment by mikehardy** [comment]
I don't recall you offering a solution. PRs welcome.
