### ISSUE TITLE
[Feature Request] Keymap/Customizable Keyboard Shortcuts for Reviewer Actions

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6052]
I intend to work on this if accepted. Mentioned in #5430, but I'd like to formalise and confirm plans.

----

Encompassed: #3021, #1683, #4160, #3600

* Add a settings screen under Reviewer: Keymap
  * Allow the user to view and remove current keymappings
  * Allow the user to press a button, view the key(s) pressed, and assign it to an action (same as gestures)
  * Include common modifier keys (Ctrl+Alt+Shift)
  * Specify whether an action occurs on the front and/or the back of the card
  * Block duplicate key assignments.
  * Specify whether an action occurs only on the input device used, or on all devices.
  * Specify whether an action is triggered on long/short press (or both if not defined).
  * Add in actions to navigate left/right around the 4 answers of a card.
  * Add in action to explicitly play the front/back of the card (to allow hands-free reviewing and checking of state).
  * Permit handling media events when reviewing cards
  * Stored in a SharedPreferences setting as JSON to allow future schema extensions (is this OK, if so, remove from ACRA logging due to size)?
  * Allow user to specify long press threshold in ms
* Convert Reviewer to accept commands
* Listen to KeyUp events, pass them into a KeyEventProcesser, and process the commands obtained.

**Comment by mikehardy** [comment]
Your standard video game key assignment screen, yeah? Seems like exactly how everyone else solves it which means either we're all crazy, or we've come to a generic solution and most users are familiar with the style. Tally ho

**Comment by david-allison-1** [comment]
Pending on me getting a few UI diagrams productionised for review.

Settings screen is going to be complex, but I'm not yet happy with how it should look pre-design review.

**Comment by mikehardy** [comment]
I think this may have some progress here actually #8078
