### ISSUE TITLE
Reviewer toolbar defaults incorrect

### ISSUE THREAD

**Issue by timrae** [ankidroid/Anki-Android#6054]
###### Reproduction Steps

1.  Clear AnkiDroid app data in Android settings
2.  Open AnkiDroid and start reviewing

###### Expected Result
Same items in toolbar as 2.9.x

###### Actual Result
Reschedule is set to "Always show"

It looks like the issue crept in [here](https://github.com/ankidroid/Anki-Android/commit/7855dd0216828320fe46081b4407910661d58202)

**Comment by timrae** [comment]
There may be other items which are incorrect. It would be nice if we had the defaults all in one place instead of duplicated with slight differences across [here](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/res/menu/reviewer.xml), [here](https://github.com/ankidroid/Anki-Android/blob/b427ded0ffa4697317587e67e318bee4cc0fa2da/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1676), and [here](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml)

**Comment by mikehardy** [comment]
I just noticed this today when I was playing with the new flag/mark feature! That happen to you too @timrae ? The reschedule feature is nice and all but not as a default always show. Agreed in general, flagging for 2.10 release planning
