### ISSUE TITLE
Sharing the collection.anki2 database with other Anki applications on device

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#6057]
Some of you may be familiar with the instructions I posted for [installing Anki desktop on an android device](https://github.com/termux/x11-packages/issues/142#issuecomment-559839216). I've released a project that [installs desktop Anki in Termux](https://github.com/sudomain/AnkiTermuxArch). I want AnkiDroid and Anki desktop to share the collection database (collection.anki2) and associated directories so that users don't have to have two copies of their collection and collection media on device. I've been able to do this by changing my AnkiDroid directory from `/storage/emulated/0/AnkiDroid` to `/storage/emulated/0/AnkiRootDir/User 1` like so:

![Screenshot_2020-04-20-15-53-42](https://user-images.githubusercontent.com/30786326/79793786-2703b280-831f-11ea-8cce-750eaeea0c05.png)

There are a couple issues to work out relating to file locations:
Instead of requiring users to change this setting, I think AnkiDroid should by default store the `AnkiDroid/` directory in an empty directory such as `/storage/emulated/0/Anki2/AnkiDroid`. This will allow the two projects to share a collection without users moving directories and changing settings. Not only that, but when AnkiDroid adds support for multiple profiles (#2545), AnkiDroid should probably use the same folder structure as [desktop](https://docs.ankiweb.net/#/files?id=file-locations):

`Anki2/` contains
prefs21.db
addons21/
User 1/
and other files.

Possible relevant code if I get approval to change the default Ankidroid dir: https://github.com/ankidroid/Anki-Android/blob/c832e1d9cb9d2653f15c21b558457d5b346244a7/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L168

The other issue is that if the collection is currently open in Anki then the user opens the same collection AnkiDroid (or vice-versa), the user will be told that there is a corrupt database when there isn't one (checking the database doesn't give any errors). I think this is an issue with how AnkiDroid checks for a database lock (in CollectionHelper.java?). I think this is an AnkiDroid specific issue because it's possible to run two different versions of Anki on a computer without having database issues. For instance I have Anki 2.1 and 2.0 installed on a windows machine. If my collection is open in 2.1 and I try to open the same collection in 2.0, the collection will not open. The same is true if I have it open in 2.0 and attempt to open 2.1.

Edit: added link to my project

**Comment by mikehardy** [comment]
I think this is cool that it works together but we *just* finished stabilizing AnkiDroid from crashing, and I'm in the middle of trying to cut a 2.10 release branch before I contemplate a number of complicated performance changes for 2.11.

So even the idea of changing the default directory right now frankly scares the 💩 out of me, based on previous experiences.

We have some deep thinking to do in this area (i.e. #2545 as you mention, but also and maybe more important #5304 which would try to get rid of storage permission entirely).

By linking both here we can contemplate this at the same time but I need to be honest - I'm not going to have time to get to this for probably months. If anyone else can present a coherent solution that:

1. handles multiple profiles
1. does not require storage permission
1. is still customizable by users (just in case)
1. and also can interoperate with AnkiDesktop running on Android

...then I can contemplate it

However you should be aware that libanki is actually being ported to Rust right now and unless you've successfully gotten master of Anki Desktop (with rust libanki parts) to run on Android then you might be headed into a dead end as future Anki Desktop won't work.

**Comment by sudomain** [comment]
A lot to respond to, forgive me if I missed something:

> However you should be aware that libanki is actually being ported to Rust right now and unless you've successfully gotten master of Anki Desktop (with rust libanki parts) to run on Android then you might be headed into a dead end as future Anki Desktop won't work.

This I'm not terribly worried about. [My project ](https://github.com/sudomain/AnkiTermuxArch)installs an instance of Arch Linux ARM(a port of Arch for ARM devices) in a chroot environment (technically it's a PRoot) and uses that project's packaged version of Anki (2.1.15). iirc Arch Linux Arm gets its Anki package from the Arch community repo and the community-testing repo currently has [2.1.23](https://www.archlinux.org/packages/community-testing/x86_64/anki/). Plus rust 1.42 is available as a package, though I haven't tested it.

> We have some deep thinking to do in this area (i.e. #2545 as you mention, but also and maybe more important #5304 which would try to get rid of storage permission entirely).

I hadn't seen #5304 before and my knowledge of Android storage is limited so please correct me if I'm wrong. I've learned a bit from [this doc](https://developer.android.com/training/data-storage). According to that doc, using getFilesDir() or getExternalFilesDir() (as suggested in #5304) means that the Anki collection would be considered an "App-specific file" to AnkiDroid? According to the same doc, I believe would those files would be removed if AnkiDroid is uninstalled? If this is the case, it would really hinder the ability of a program (like mine) to use the same collection database.

Regarding the two issues I brought up in my OP:
AnkiTermuxArch can adapt to the directory issue (I'm thinking an optional script that moves the collection and prompts the user to change the AnkiDroid directory setting). Today I'm having trouble reproducing the other issue of a reported database corruption when  the two apps try to open the same collection. They still can't be used at the same time, but it's better than getting a message that collection is corrupt.

**Comment by sudomain** [comment]
regarding the profile issue, AnkiDroid should probably do what Anki does. I don't know everything about how Anki does profiles, but iirc there's some profile information in prefs21.db and a separate directory for each profile in the ANKI_BASE directory

**Comment by sudomain** [comment]
It seems like the "database corrupt" error is sporadic when AnkiTermuxArch and AnkiDroid share a collection. A fix  would likely involve changing code in [CollectionHelper.java](https://github.com/ankidroid/Anki-Android/blob/c832e1d9cb9d2653f15c21b558457d5b346244a7/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L42) as that handles loading the collection. Currently it only checks for AnkiDroid's internal idea of a database lock; the `mCollectionLocked` variable rather than checking the sqlite database.

**Comment by sudomain** [comment]
My original reasons for opening this issue are resolved. I think the DB lock issue was fixed with PR #6100 (thanks for that). Additionally I can work around the default directory issue with an opt-in script for [AnkiTermuxArch](https://github.com/sudomain/AnkiTermuxArch) that moves the collection and prompts the user to change the AnkiDroid Directory setting.


I'll leave it up to the project maintainers if they want to close this issue or leave it open for discussion of handling profiles.

**Comment by mikehardy** [comment]
I value the directory discussion here and am happy that is cross linked to the tracking issue for that now but have no shortage of work so if its the same otherwise / doesn't have an urgent separate need I'll close this
