### ISSUE TITLE
add a cross in the field where you add the card, and then for a long time select everything and delete

### ISSUE THREAD

**Issue by vosirandr** [ankidroid/Anki-Android#6074]

**Comment by david-allison-1** [comment]
Can't you long press the field - select all - backspace?

**Comment by vosirandr** [comment]
Long when you do a lot

чт, 23 апр. 2020 г. в 13:31, david-allison-1 <notifications@github.com>:

**Comment by david-allison-1** [comment]
@vosirandr Sorry, I don't understand

**Comment by vosirandr** [comment]
or at least to delete everything

ср, 3 июня 2020 г., 15:57 david-allison-1 <notifications@github.com>:
