### ISSUE TITLE
[Feature Request] Verify backup creation

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6078]
I'm not testing this area of the code, or intentionally trying to break things, but over the past 2 months, I've had 2 backups which are corrupt. I don't regularly test my backups, so this presumably happens a lot more often than I'm finding.

This implies a corruption bug somewhere (possibly just killing the Task via killing the program).

It would be ideal to verify that backups work and are valid for restoration after they've been created.

**Comment by mikehardy** [comment]
Agreed, and a dialog (but with a disable checkbox) if there was not enough space. Corruption should get a dialog as well. Data loss is too serious to mess with

**Comment by david-allison-1** [comment]
Closing - #7073 is the likely culprit here.
