### ISSUE TITLE
Import using USB

### ISSUE THREAD

**Issue by ronved** [ankidroid/Anki-Android#6081]
Ankidroid manual says: Click the 'Export…​' button. Make sure to leave "all decks" selected, as it’s not possible to import individual decks into AnkiDroid. "Include scheduling information" must also remain checked. Anki will automatically create a collection.apkg on your desktop. If the file is named something else, please see the previous step again.

But Anki collection package export formats are:   collection-2020-04-26@14-23-47.colpkg or "All Decks.apkg" or .txt

After dragging any of these files into ankidroid file(mine is in sdcard) and trying to import i get the error message "Invalid file" and/or not enough storage space.

so i tried to change the name to collection.apkg but i get message saying the file will become unstable.

what should i do to move the whole collection to ankidroid using USB? 
(i am not able to use sync because of some internet connection problems)

**Comment by mikehardy** [comment]
Hi there!

> Ankidroid manual says: Click the 'Export…​' button. Make sure to leave "all decks" selected, as it’s not possible to import individual decks into AnkiDroid. "Include scheduling information" must also remain checked. Anki will automatically create a collection.apkg on your desktop. If the file is named something else, please see the previous step again.


I cannot find this in the manual https://docs.ankidroid.org/#importing (or exporting below it)

You can export or import a deck or a full collection, no problem.

> But Anki collection package export formats are: [collection-2020-04-26@14-23-47.colpkg](mailto:collection-2020-04-26@14-23-47.colpkg) or "All Decks.apkg" or .txt

Modern Anki exports full collections as .colpkg files, and modern ankidroid (2.9+) recognizes them.

> After dragging any of these files into ankidroid file(mine is in sdcard) and trying to import i get the error message "Invalid file" and/or not enough storage space.

We don't support external storage officially for a variety of reasons, accurately determining available free space is one of them. It may be that we are checking space vs /sdcard/AnkiDroid as that's what we support. I'm not sure

> so i tried to change the name to collection.apkg but i get message saying the file will become unstable.

That's no message from AnkiDroid, I don't know what it means. I'd assume the warning can be ignored, changing the extension of a file doesn't really *do* anything to the file, how it could it make a file unstable? What does it even mean for a file to be unstable?

That said, if it doesn't import one way in AnkiDroid, it's probably not going to import the other way either. Same code paths in AnkiDroid really.

> what should i do to move the whole collection to ankidroid using USB?
> (i am not able to use sync because of some internet connection problems)

I'm sorry, but for large collections, syncing it down via AnkiWeb is it, AnkiDroid does not handle import of large files well, and there may be issues with non-standard storage paths

**Comment by ronved** [comment]
> I cannot find this in the manual https://docs.ankidroid.org/#importing (or exporting below it)
its above importing section: 
https://docs.ankidroid.org/#_copy_all_decks_from_anki_desktop_to_ankidroid_via_us

**Comment by ronved** [comment]
> Modern Anki exports full collections as .colpkg files, and modern ankidroid (2.9+) recognizes them.

my ankidroid version is 2.9.6

**Comment by ronved** [comment]
> You can export or import a deck or a full collection, no problem unless they are large decks or collections
i have a large collection. i think the problem is my desktop app is not uploading. i don't know why. but my ankidroid app has no problems downloading from ankiweb.

**Comment by ronved** [comment]
> We don't support external storage officially for a variety of reasons, accurately determining available free space is one of them. It may be that we are checking space vs /sdcard/AnkiDroid as that's what we support. I'm not sure

because i am not able to import whole collection or all files, i tried chunking it deck-wise and importing each separately. i could import all most all decks except for a few but they are not large files and there is 22GB space on my sdcard. the sizes of these files range from 20- 80MB and they give the the pop up messages: e.g. 
"java.io.IOException:Bilateral_pneumothorax_pneumomediastinum.jpg:open failed: ENOSPC (No space left on device)"

**Comment by mikehardy** [comment]
could be too many files in the same directory depending on the device and the filesystem. Check the FAQ for this - sometimes if you use a different (non-FAT, in particular) filesystem it can work but you might just have too many media files in one spot

**Comment by ronved** [comment]
still searching for solutions

**Comment by david-allison-1** [comment]
@ronved Could you go to `Settings - About AnkiDroid - Copy Debug Information` and paste it here.

Could you then go to `Settings - AnkiDroid - Crash Reporting` and turn it on

Could you then try to import the file again.

Thanks,

David
