### ISSUE TITLE
Feature Request: working combination of auto-advance and text to speech

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6087]
###### Reproduction Steps

1. Enable auto-answer cards
2. Enable TTS
3. Review a selection of cards

###### Expected Result

The review should auto-advance with TTS working correctly and the auto-advance happening according to the "time for TTS to speak" plus the configured auto-advance time

###### Actual Result

According to user feedback TTS and auto-advance do not work together, and it appears that the related code is indeed not connected.

A viable solution would be to plumb a TTS UtteranceProgressListener through from AbstractFlashcardViewer so that auto-advance could function, and when the listener onDone was called and the TTS queue was empty AbstractFlashcardViewer could apply auto-advance logic

https://github.com/ankidroid/Anki-Android/blob/8c90adb685b5970356173325d2febcf05ada0cae/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L2135-L2145

and connected here somehow

https://github.com/ankidroid/Anki-Android/blob/8c90adb685b5970356173325d2febcf05ada0cae/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1876-L1883

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by SergeyLeonov999** [comment]
Спасибо огромное за решение проблемы с TTS =продвижением., Остался ещё один маленький шаг и оно будет идеальным. 
У меня есть карточки в которых заполнено только поле question, карточка Answer- пустая->. в поле ANSWER нет ни одного слова, TTS не запускается , отсчет задержки после TTS, не включается, так как  карточка ANSWER пустая. Карточка и колода останавливается. NO WORD IN ANSWER CARD (NO TTS) <-> (NO TTS ) no delay time after ANSWER CARD.

Надо ли куда то ещё написать , или описания проблемы на этом ресурсе?

**Comment by SergeyLeonov999** [comment]
У меня есть карточки в которых заполнено только поле question, карточка Answer- пустая->. в поле ANSWER нет ни одного слова, TTS не запускается , отсчет задержки послеTTS, не включается. Карточка и колода останавливается. NO WORD IN ANSWER CARD (NO TTS) <-> (NO TTS ) no delay time after ANSWER CARD.

**Comment by SergeyLeonov999** [comment]
Спасибо огромное за решение проблемы с TTS =продвижением., Остался ещё один маленький шаг и оно будет идеальным. 
У меня есть карточки в которых заполнено только поле question, карточка Answer- пустая->. в поле ANSWER нет ни одного слова, TTS не запускается , отсчет задержки после TTS, не включается, так как  карточка ANSWER пустая. Карточка и колода останавливается. NO WORD IN ANSWER CARD (NO TTS) <-> (NO TTS ) no delay time after ANSWER CARD.

Надо ли куда то ещё написать , или описания проблемы на этом ресурсе?

**Comment by SergeyLeonov999** [comment]
Спасибо огромное за решение проблемы с TTS =продвижением., Остался ещё один маленький шаг и оно будет идеальным

**Comment by SergeyLeonov999** [comment]
Спасибо огромное за решение проблемы с TTS =продвижением., Остался ещё один маленький шаг и оно будет идеальным. 
У меня есть карточки в которых заполнено только поле question, карточка Answer- пустая->. в поле ANSWER нет ни одного слова, TTS не запускается , отсчет задержки после TTS, не включается, так как  карточка ANSWER пустая. Карточка и колода останавливается. NO WORD IN ANSWER CARD (NO TTS) <-> (NO TTS ) no delay time after ANSWER CARD.

Надо ли куда то ещё написать , или описания проблемы на этом ресурсе?
