### ISSUE TITLE
Night Mode: comma-separating of pseudo-classes doesn't work

### ISSUE THREAD

**Issue by ogassav** [ankidroid/Anki-Android#6095]
###### Reproduction Steps

1. Multiple pseudo classes, comma-separated construction like `.class::before,.class::after` works perfectly in Day-mode.
2. **Night**-mode version of this construction - `.night_mode .class::before,.class::after` - won't work. You have to split it into _standalone_ `.night_mode .class::before` and `.night_mode .class::after`
3. Space after comma **", "** doesn't change anything too. Bug?

###### Debug info
AnkiDroid Version = 2.9.6
Android Version = 8.1.0
ACRA UUID = e1249345-0bd6-4585-a7b1-203183348585

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Hi @ogassav,

Thanks for the report. Could you give a full card template and field values which will display this issue?

You can surround them in triple backticks: ` ``` ` to format them as code blocks.

All the best,

David

**Comment by ogassav** [comment]
Hi @david-allison-1 

Please find attached the deck (TEST.zip) which shows the highlighted problem.
Here's the screenshot:

![image](https://user-images.githubusercontent.com/59234350/80805635-e32f6980-8bb8-11ea-8c62-26f3f467ad97.png)

I've highlighted that when the night-mode code in its `.night_mode .class::before,.class::after` version, the overall code is ruined and the lower bar becomes light-blue instead of orange (same as upper bar).

Changing the night mode class to the  `.night_mode .class::before` and `.night_mode .class::after` version solves this problem.

As for the CSS reference, i couldn't find the official document, but in the day-mode part of the code i'm using `.class::before,.class::after` construction and it works perfectly all right. Besides, I've found the Stackoverflow [comment](https://stackoverflow.com/a/41116475) which confirms this method as a working one, and an [article](https://stuffandnonsense.co.uk/blog/using-multiple-not-selectors) which explains this method **can't** be used with `:not` selector - others are ok (scroll to **Bad Magic** header of the article).

[TEST.zip](https://github.com/ankidroid/Anki-Android/files/4564140/TEST.zip)

**Comment by david-allison-1** [comment]
Thanks for the details!

I'm happy to to be wrong (I'm not a web dev, and haven't done it for years), but I believe this is working as expected.

I'll consider this to be a bug if you can show that a similar non-night mode property works as you would expect (using the same syntax), or you can replicate/show the behaviour that you're expecting in Google Chrome. You might want to head to stackoverflow to ask this to an expert in the matter.

My reasoning is below:

----

I don't believe the stackoverflow comment applies, as that doesn't use the "descendant selector" (a space).

```css
.class::before,.class::after {}
```

The above reads to me as: `class::before`, OR `class::after`, so it should work correctly.

```css
.night_mode .class::before,.class::after
```

The above means: `.night_mode .class::before` OR `class::after`. so it'll be problematic

```css
.night_mode .class::before, .night_mode .class::after
```

The above means: `.night_mode .class::before` OR `.night_mode .class::after`

Please get back to me if there's a counterexample that you can find. I've been through the rendering/appearance code for the Reviewer fairly recently and can't see how we'd cause a bug, but it's nowhere near impossible that I missed something.

All the best,

David

**Comment by mikehardy** [comment]
This may be useful, as you can get a rendered card.html on your phone filesystem and pull it off to play with it in a browser: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection (or if you are fancy you can plug your phone in with adb / Android Development features enabled and open the Chrome WebView directly for runtime inspection)

**Comment by ogassav** [comment]
Guys, i've just checked and the following format **does** work in the Night Mode:

`.night_mode .class::before, .night_mode .class::after`

I'm totally fine with that. So possibly it was **my** misunderstanding that `.night_mode` should be written only _once_, while it should be mentioned before _every_ pseudo-class listed.

If it's ok for you, i can close the issue as solved. OK?

**Comment by david-allison-1** [comment]
@ogassav Fine with me, glad you got it sorted!
