### ISSUE TITLE
"Type In Answer" displays image src as expected input

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6096]
###### Reproduction Steps

1. Card template with front and back. `{{type:Back}}`
2. Back contains `ya[sound:36_ya.mp3]<div><img src="paste-efbfdfbff329f818e3b5568e578234d0d0054067.png" /><br /></div>`

###### Expected Result

3. When card is flipped, expected value is `ya` (Anki 2.0.52/2.1.24)

###### Actual Result

3. When card is flipped, expected value is 

```
ya
paste-efbfdfbff329f818e3b5568e578234d0d0054067.png
```

###### Research
[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
[x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
[x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
looks like a job for the html parsing library we include already and I always forget about, including it's name this moment :rofl:

**Comment by david-allison-1** [comment]
Jsoup. Ideally I'd like to fully emulate Anki's parsing code to ensure full compatibility: 

https://github.com/ankitects/anki/blob/351d8a309f7d3c0cae7f818313b1a0e7aac4408a/qt/aqt/reviewer.py#L403-L435
