### ISSUE TITLE
Feature request: Left align answers

### ISSUE THREAD

**Issue by haroldeous** [ankidroid/Anki-Android#6098]
###### Reproduction Steps

1. Go to a deck
2. Study it
3. Answers are presented centre-aligned

###### Preferred Result
3. An option for answers to be presented left-aligned

**Comment by david-allison-1** [comment]
@haroldeous, the answer templates are already fully customisable.

* Edit a card 
* Click "Cards: "
* You can then enter HTML into the "Back Template" to left-align your answers.

Please let me know if your query has been answered satisfactorily, if not, a screenshot to describe what you're after would be useful

Hope this helps, 

David

**Comment by haroldeous** [comment]
@david-allison-1 , thanks a lot. That is a really powerful feature.

**Comment by danielmanesku** [comment]
This is great, however, very well hidden. 

If issue search brought you here and you don't know upfront what to put in the Back Template, here is an example:

```
<div align=left style='font-family: Liberation Mono; font-size: 20px;'>{{FrontSide}}</div>

<hr id=answer>

<div align=left style='font-family: Liberation Mono; font-size: 20px;'>{{Back}}</div>
```

**Comment by david-allison-1** [comment]
@danielmanesku Thanks so much for the elaboration!

![](https://media.giphy.com/media/g9582DNuQppxC/giphy-downsized.gif)
