### ISSUE TITLE
Sync time-out because CPU too slow

### ISSUE THREAD

**Issue by zatsuna** [ankidroid/Anki-Android#6099]
I haven't synced ankidroid on my android e-ink reader for several months now but when I tried to do it today I got sync error. I suspect that server time out window has been shortened as I was able to sync the device without any problems about 6 months ago and no changes have been made to my collection. My other android devices sync without error. 

###### Reproduction Steps

1. Try to sync a collection of about 15k flashcards on an old android e-ink reader. 
2. Device starts preparing to sync but gets sync error connection timed out before it can start. 

###### Expected Result

Synchronization to server.

###### Actual Result

Sync error connection timed out

###### Debug info
AnkiDroid Version = 2.9.7

Android Version = 4.0.4

ACRA UUID = 065d45c7-3fca-4cb3-a0c7-45b4214c78d8

###### Research
*Enter an [ x ] character to confirm the points below:*

[x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[x] I have searched for similar existing issues here and on the user forum

**Comment by zatsuna** [comment]
Solved with https://github.com/tsudoko/anki-sync-server.

**Comment by mikehardy** [comment]
No, your android operating system is too low. API15 does not support TLS1.2, so it may no longer communicate with AnkiWeb

#5623
