### ISSUE TITLE
SVG images are not displayed

### ISSUE THREAD

**Issue by nnbveh** [ankidroid/Anki-Android#6101]
###### Reproduction Steps

1. Open a Russian road signs deck
2. Standard icon instead of road signs images
3. 

###### Expected Result
Images 

###### Actual Result
Standard icon

###### Debug info
AnkiDroid Version = 2.9.7

Android Version = 9

ACRA UUID = 77ed64b7-b2c0-41c9-9838-b65a36dbb842
##### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  x] I have searched for similar existing issues here and on the user forum
 There's a similar one bit it says no images displayed at all(any file format) and in that case there's a sync problem reported, my decks are synced without an issue

**Comment by david-allison-1** [comment]
Hi @nnbveh,

Could you elaborate on the deck that you're using, either by providing a link to the shared deck, or a minimal example displaying the problem?

Initial Debugging can be done via the Chrome Inspector: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection  

Thanks,

David

**Comment by nnbveh** [comment]
![ANKI SVG](https://user-images.githubusercontent.com/39271290/80931070-2d4b6180-8dea-11ea-8245-c6fee15f86b9.jpg)

https://ankiweb.net/shared/info/1378120198

Same deck renders fine on my macbook

**Comment by david-allison-1** [comment]
Not an SVG error, these aren't SVGs, it's a URL loading error. 

My presumption: In AnkiDroid, `//` refers to the root of the filesystem, rather than a selection between HTTP or HTTPS

Chrome error:

```
75px-6.1_Russian_road_sign.svg.png:1 Failed to load resource: net::ERR_INVALID_URL
```

Card source:
```html
<img alt="6.1 Russian road sign.svg" data-file-height="2250" data-file-width="1500" decoding="async" height="75" src="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/6.1_Russian_road_sign.svg/50px-6.1_Russian_road_sign.svg.png" srcset="//upload.wikimedia.org/wikipedia/commons/thumb/5/50/6.1_Russian_road_sign.svg/75px-6.1_Russian_road_sign.svg.png 1.5x, //upload.wikimedia.org/wikipedia/commons/thumb/5/50/6.1_Russian_road_sign.svg/100px-6.1_Russian_road_sign.svg.png 2x" width="50"/>
```

Card works if the sources are changed from `//` to `https://`.

**Comment by nnbveh** [comment]
I see. Is there a way to fix this quickly for all the cards? The deck was not created by me, i can see i can edit every card one by one but 350 cards is quite a lot...Thanks anyways!

**Comment by david-allison-1** [comment]
The deck's broken in Anki 2.0 as well. It's proably best to message the deck author. Ideally they should be storing the images inside the deck so they don't overload Wikimedia, and to ensure that the files stay valid.

There might be an addon for Anki Desktop to allow find/replace, if so, replace: `//upload` with `https://upload`.

**Comment by nnbveh** [comment]
Works as intended on 2.1.25 (898801eb), maybe 2.0 is different? I'll check for the addons, thanks!

**Comment by nnbveh** [comment]
Actually there was no need for addon, Ankidroid has search&replace built-in, so i've fixed the deck now. Will try to modify it later so the images stored inside the deck. Thanks again!

**Comment by david-allison-1** [comment]
Awesome! I didn't know that... thanks!

I'll open a separate issue to get the underlying issue fixed.

Thanks again,

David

**Comment by mikehardy** [comment]
There is also a plugin to download remote referenced media into your collection if I recall correctly :-)
