### ISSUE TITLE
Ankidroid2.10beta2  fails to play more than 2 audio files in a single card.

### ISSUE THREAD

**Issue by Drrrrr519** [ankidroid/Anki-Android#6111]
###### Reproduction Steps

1. I often put more than 2 audio files in a card.  It played them consecutively, but after I updated anki to the newest version, I found it can only play two files in a row.  Can you fix that?  Thanks a lot. 
2. 
![Screenshot_20200506_000136](https://user-images.githubusercontent.com/64855701/81089568-1c583880-8f2f-11ea-90ef-bdbb1257a657.jpg)

3. 

###### Expected Result
I hope it will play all the audio files in one card. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Fascinating! Thanks for testing out the betas and reporting this. Shouldn't be too bad to fix, we'll have it before 2.10 goes out of beta but it is hard to say how long it will take. If this is affecting your studies I recommend either installing one of the parallel releases (AnkiDroid.A maybe) from the 2.9.6 release so you can review in the last stable version while checking future betas for a fix, or temporarily leaving the beta program so you get back on 2.9.x 

side-by-side parallel releases here https://github.com/ankidroid/Anki-Android/releases/tag/v2.9.6

**Comment by david-allison-1** [comment]
Thanks so much for the report! Looking into it.

**Comment by Drrrrr519** [comment]
Anki is getting better and better.  Thank y'all.

**Comment by david-allison-1** [comment]
Issue: https://github.com/ankidroid/Anki-Android/blob/0904169051eae3969402ba3f67dba9629748b515/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java#L384-L391 (my fault).

Will increase regression cover and get this fixed today/tomorrow.

**Comment by mikehardy** [comment]
Got a fix already - there will be a 2.10beta3 some time within next 12 hours if that affects whether you want to mess with what version you have installed or just wait @Drrrrr519

**Comment by mikehardy** [comment]
2.10beta3 is available now, hopefully it fixes this up

**Comment by C-Y-Liu** [comment]
> 2.10beta3 is available now, hopefully it fixes this up

Yes, it works! Thanks!
