### ISSUE TITLE
Problem with the eraser tab

### ISSUE THREAD

**Issue by Akshittuli** [ankidroid/Anki-Android#6119]
###### Reproduction Steps

1. Click on whiteboard tab while reviewing flashcards and use the feature to write/draw anything
2. Click on the erase tab till you have undone the drawing and the erase tab grays out
3. Redraw anything by clicking on the whiteboard icon

###### Expected Result
Upon redrawing, the eraser tab should revert its color from gray to white

###### Actual Result
On redrawing, the eraser tab still remains grayed out.

###### Debug info
Refer to the [support page]AnkiDroid Version = 2.10beta3

Android Version = 10

ACRA UUID = bbdbcff5-0c68-4fd5-8b77-95df0b7fc4b3

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum
![Screenshot_20200507-194002_AnkiDroid](https://user-images.githubusercontent.com/58380148/81304386-9fe26880-909a-11ea-9a4a-d87e37e709ef.jpg)

**Comment by david-allison-1** [comment]
Hi @Akshittuli,

Thanks for the report! Reproduced in 2.10alpha73

Works on 2.9.7

Will look into it today.

**Comment by mikehardy** [comment]
This has got to be due to the disable-icons-while-async-task-is-running PR a couple weeks back. I had a pending item to put a slight delay on disabling the icons as well since they'll flicker now in the normal use case, but it's still useful to have double-click protection and disable them visually for long-running operations (or slow devices in combo with big collections) so the async task doesn't go off on a different card than expected.

**Comment by david-allison-1** [comment]
Looks like it was my ActionItem change for the flags. 7c9911b6 works fine.

**Comment by david-allison-1** [comment]
Cause: https://github.com/ankidroid/Anki-Android/commit/029afff75fbcf85fa0e324fdca925d3212c34ce2#diff-15d704f4d834521dda5e28231ddbd727

**Comment by mikehardy** [comment]
That was the one I was thinking of - I was a bit iffy on it when it went in but it seemed like it would redraw and if enabled was the default... a revert is clean enough though and it can go in the 2.10beta4 pile for release - can you PR a revert on that one 🙏 ?
