### ISSUE TITLE
AnkiDroid renders a modified cloze note type incorrectly

### ISSUE THREAD

**Issue by andrewsanchez** [ankidroid/Anki-Android#6121]
###### Reproduction Steps

Import this [test.apkg.zip](https://github.com/ankidroid/Anki-Android/files/4593902/test.apkg.zip) with example note types **or**... 

- Clone the cloze note type
- Modify it so that one card is always generated from the contents of a field _without cloze deletions_
  - Do this by ensuring that the front template always references a populated field, e.g.

```
{{cloze:Text}}
<br><br>
{{MoreText}}
```

The same result can be achieved with some JavaScript:

```html
<div id="quote">{{quote}}</div>
<div id="cloze">{{cloze:quote}}</div>

<script>

let cloze = document.getElementById("cloze");
let quote = document.getElementById("quote");

function isEmpty(cloze) {
    return (!cloze || 0 === cloze.length);
}

if (isEmpty(cloze.textContent)) {
    cloze.parentNode.removeChild(cloze);
} else {
    quote.parentNode.removeChild(quote);
}

</script>
```

- Sync to AnkiDroid
- Observe the difference between how Anki Desktop and AnkiDroid renders such templates

###### Expected Result

AnkiDroid should render the template the same way Anki Desktop does:  _If_ `{{MoreText}}` is populated, or if `{{quote}}` is populated in the JavaScript example, then At least one card should always be generated from these note types

###### Actual Result

AnkiDroid generates cards from these templates with empty front sides, displaying the message

>Edit this note and add some cloze deletions

###### Research

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

There has been discussion of similar issues in the past:
- https://github.com/ankidroid/Anki-Android/issues/3440
- https://github.com/ankidroid/Anki-Android/issues?q=is%3Aissue+conditional+
- Code ref suggested by David: https://github.com/ankidroid/Anki-Android/blob/a836689480d8fe2a571319b75eebe5ae731bd73a/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1060-L1065

##### More Context

I'm trying to implement a system with several stages, based on Getting Things Done.  The first two steps are 1) Capture and 2) Process.  The first stage is to simply capture important or interesting text snippets directly into Anki while reading, before I even create any sort of active recall flashcard via cloze deletions.  I want these captured items to enter in my review schedule, allowing me to passively review the information on a SR schedule until I decide to make some cloze deletions.  After making a cloze deletion, the passive review card should not appear in my review schedule anymore; I only want to study the cloze cards from that point forward.  So essentially, I need a cloze note type that always generates at least 1 card that simply displays the un-clozed text on the front and back.

**Comment by mikehardy** [comment]
Hi there! Can you still reproduce this with 2.10beta3? https://docs.ankidroid.org/#betaTesting - we are about to do full release for that one and there has been work on field and cloze parsing that may have fixed it (or may not have) but before doing triage here I'd like to know if you still see the problem with the coming version

**Comment by andrewsanchez** [comment]
Hi, @mikehardy!  Thanks for the quick response. 😄   The behavior appears to be the same in 2.10beta3.

<img src=https://user-images.githubusercontent.com/11708906/81320546-38023280-9046-11ea-9fcb-44869558b243.png width="40%" height="40%">

<img src=https://user-images.githubusercontent.com/11708906/81320565-3fc1d700-9046-11ea-98a0-27294edd5469.png width="40%" height="40%">

<img src=https://user-images.githubusercontent.com/11708906/81320578-45b7b800-9046-11ea-9acb-087e977489da.png width="40%" height="40%">

<img src=https://user-images.githubusercontent.com/11708906/81320591-49e3d580-9046-11ea-9f84-4411f8d10ec8.png width="40%" height="40%">

**Comment by mikehardy** [comment]
Interesting - I admit I don't use cloze personally so I wouldn't have noticed this, and we should follow Anki Desktop behavior, so thanks for the super detailed report. I'm not sure this is a regression from 2.9.x (based on you just testing 2.10beta3 now I'm guessing you were on 2.9.x before?) so if that assumption holds it won't block a 2.10 release but we should fix it.

An implication of that assumption (as someone who wants everyone to be able to Get Things Done) is to suggest you look for a modified workflow for now, perhaps a card type that is specifically a pre-cloze type but named specifically so it was easy to search for in card browser, then as part of the step change in your flow from just looking at the text to cloze you'd switch the card type also. Or similar? Just thinking out loud in an effort to see that you aren't blocked as our attention may be elsewhere for a while in this project

**Comment by Arthur-Milchior** [comment]
As I explained on discord, this is related to a change in anki. I just tried 2.1.15, and this template did display "Please edit this note and add some cloze deletions. (help)" after the content of MoreText.
The commit you want to port is https://github.com/ankitects/anki/commit/2a0b480103a37fea7e33737f9916351d31b6477b
