### ISSUE TITLE
Cards with multiple cloze deletions only show cloze 1, other clozes remain buried, not for the next day, but forever, basically I'm missing all the cards other than those with cloze 1

### ISSUE THREAD

**Issue by matador94** [ankidroid/Anki-Android#6122]
###### Reproduction Steps

1. Bury new related cards checked
2. Bury review related cards checked
3. eg: I study cloze 1 on may 5ty

###### Expected Result
Cloze 2 shown may 6th or 7th

###### Actual Result
Cloze 2 remain buried forever, until I manually unburry them

###### Debug info
AnkiDroid Version = 2.9.6

Android Version = 9

ACRA UUID = bf48d50d-aab5-4b28-944e-679a711f1d6a

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
You did not paste your debug info so I don't know your version
Please try to reproduce with 2.10beta3 as there has been work in the area and we need to know how the current code handles it before doing triage here https://docs.ankidroid.org/#betaTesting

**Comment by matador94** [comment]
> You did not paste your debug info so I don't know your version
> Please try to reproduce with 2.10beta3 as there has been work in the area and we need to know how the current code handles it before doing triage here https://docs.ankidroid.org/#betaTesting

Just posted my debug info

**Comment by david-allison-1** [comment]
I believe this may have been fixed in 504d96a99d31f35cfb48d94af1e7b282603b9bb6, but any notes which were created before the fix would have been placed at the end of the new queue.

**Comment by mikehardy** [comment]
What I mean by the beta thing is follow that link, sign up for the betas (2.10beta3 now) and re-test. If you can reproduce it in the beta for the upcoming 2.10 release then we have a bug. We think it's fixed though and you won't be able to reproduce, so then we can close this issue and you'll be working (which is the hope / goal)

**Comment by matador94** [comment]
> I believe this may have been fixed in [504d96a](https://github.com/ankidroid/Anki-Android/commit/504d96a99d31f35cfb48d94af1e7b282603b9bb6) (#5456/#5540), but any cards which were created before the fix would have been placed at the end of the new queue.

So how can I enter that code in my Ankidroid?

**Comment by matador94** [comment]
> What I mean by the beta thing is follow that link, sign up for the betas (2.10beta3 now) and re-test. If you can reproduce it in the beta for the upcoming 2.10 release then we have a bug. We think it's fixed though and you won't be able to reproduce, so then we can close this issue and you'll be working (which is the hope / goal)

I just signed up for the betas, and downloaded that version, so now I should continue using Anki and you will see the the problem/bug that I'm having ,right? It's been 2 months with this weird problem and I tried every possible solution I've found on the internet, and I reallllly hope this will work

**Comment by mikehardy** [comment]
Yeah, if there's a bug in the code there's nothing you can do. If you check advanced preferences and your version is 2.10beta3 then *if* that link above to a bug + PR was the fix, you'll be all set. If not we'll have to dig in again and see what's going on with a fresh reproduction

**Comment by matador94** [comment]
> Yeah, if there's a bug in the code there's nothing you can do. If you check advanced preferences and your version is 2.10beta3 then _if_ that link above to a bug + PR was the fix, you'll be all set. If not we'll have to dig in again and see what's going on with a fresh reproduction

I did download the 2.10beta3 version, anything I should do now so you'll be able to see this problem?

**Comment by mikehardy** [comment]
Create a new note with multiple cloze deletions and attempt to reproduce the issue. Check the scheduling on the created cards (you can see when the next review is *I think* by changing the second column in the browser

You filed the bug, you'll have to tell us if you can reproduce it now.

**Comment by matador94** [comment]
> Create a new note with multiple cloze deletions and attempt to reproduce the issue. Check the scheduling on the created cards (you can see when the next review is _I think_ by changing the second column in the browser
> 
> You filed the bug, you'll have to tell us if you can reproduce it now.

Ok so I created a new deck, made a new note with 4 cloze deletions, did C1, then chaned the date of my phone to tomorrow reviewed c1 with no new cards, moved the date of my phone to the Day after tomorrow, no new cards appeared
Ps: my learning steps are : 20 1440 8640
My debug info:
AnkiDroid Version = 2.10beta3

Android Version = 9

ACRA UUID = bf48d50d-aab5-4b28-944e-679a711f1d6a

**Comment by mikehardy** [comment]
Thank you! Sorry it's happening of course, but that should be enough to reproduce / confirm it and hopefully get a fix

**Comment by matador94** [comment]
> Thank you! Sorry it's happening of course, but that should be enough to reproduce / confirm it and hopefully get a fix

Thank you for your help, I think I should wait for the next ankidroid version to hopefully fix the bug, right?

**Comment by mikehardy** [comment]
I'm not sure how long it will take really, it's all volunteer so deadlines are meaningless. I would suggest if there is anything you can do with regards to your own workflow to avoid it (maybe only one cloze per card? I don't know...) then I would do that, that way you aren't relying on a fix. I will note for completeness that Anki Desktop provides import and export of .csv files so you can do massive operations on massive amounts of cards all at once as .csv files then import again if you need to transform them somehow. I am not saying any of that is ideal, just saying a promise on timing for a fix from a volunteer is not worth anything, so we don't make them

**Comment by matador94** [comment]
> Thank you! Sorry it's happening of course, but that should be enough to reproduce / confirm it and hopefully get a fix

Someone who was helping me with this asked my to paste the following script:

import time  
pp(time.time())  
pp(self.col.crt)  
pp(time.time() - self.col.crt)  
pp(int((time.time() - self.col.crt) // 86400))


Do you need this too?

**Comment by matador94** [comment]
> I'm not sure how long it will take really, it's all volunteer so deadlines are meaningless. I would suggest if there is anything you can do with regards to your own workflow to avoid it (maybe only one cloze per card? I don't know...) then I would do that, that way you aren't relying on a fix. I will note for completeness that Anki Desktop provides import and export of .csv files so you can do massive operations on massive amounts of cards all at once as .csv files then import again if you need to transform them somehow. I am not saying any of that is ideal, just saying a promise on timing for a fix from a volunteer is not worth anything, so we don't make them

The problem is I'm using pre-made decks and there are up to 6 cloze deletion per note, I guess everyday I'll have to manually unburry cloze2,3,4 cards until some magic fix appears, thanks again man, appreciate it!

**Comment by matador94** [comment]
> I believe this may have been fixed in [504d96a](https://github.com/ankidroid/Anki-Android/commit/504d96a99d31f35cfb48d94af1e7b282603b9bb6) (#5456/#5540), but any cards which were created before the fix would have been placed at the end of the new queue

Would you mind take a look at my comments please?
