### ISSUE TITLE
Multiple cloze deletions weird problem

### ISSUE THREAD

**Issue by matador94** [ankidroid/Anki-Android#6124]
###### Reproduction Steps

1. Example card: I study medicine
2. C1 is { I }, C2 is {study}, C3 is {medicine}
3. 

###### Expected Result
The first day {I} shows up, the next day or the day after {study} shows up, the next day {medicine}shows up

###### Actual Result
Only { I } card shows up, others get buried or get (new) due date, what's going on here?!!!

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.9.7

Android Version = 9

ACRA UUID = bf48d50d-aab5-4b28-944e-679a711f1d6a

###### Research
*Enter an [ x ] character to confirm the points below:*

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[  ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Could you please re-test with 2.10beta3? You may have to create new cards to test it as there was a scheduler issue in the area that saw attention if I recall correctly https://docs.ankidroid.org/#betaTesting

**Comment by matador94** [comment]
> Could you please re-test with 2.10beta3? You may have to create new cards to test it as there was a scheduler issue in the area that saw attention if I recall correctly https://docs.ankidroid.org/#betaTesting

I will, but what about the 30000 cards I have this problem with? It's frustrating!

**Comment by mikehardy** [comment]
1) correctly diagnose problem
2) fit solution to problem

we're still at 1 - if the beta works then it's the bug we think it is, then 2 might be a targetted SQL query for you or similar, I dunno. Step 1 first

**Comment by Arthur-Milchior** [comment]
Is it a new problem ? Do you have the same problem on computer ?

It seems to me to be the nomal way anki(droid) behaves. You can not see more than one card of the same note by day unless you choose to allow it in the deck's option. Those cards are called siblings, and since they are very similar, anki believes it's useles to see them the same day, and tries to show you other card instead.

**Comment by matador94** [comment]
> Is it a new problem ? Do you have the same problem on computer ?
> 
> It seems to me to be the nomal way anki(droid) behaves. You can not see more than one card of the same note by day unless you choose to allow it in the deck's option. Those cards are called siblings, and since they are very similar, anki believes it's useles to see them the same day, and tries to show you other card instead.

Sadly it's a new problem ( has been happening for 2 months now).
I know very well about siblings and how anki works, it's not the case here

**Comment by Arthur-Milchior** [comment]
Are the three cards in the same deck ? 
If you use anki desktop, can you give us the "due" value of the the card "study" before and after you review it, so that we can see how this value change ?

Normally, all cards of a note have the same due value, except if you did anything special with them
