### ISSUE TITLE
Add more control over the 'flags' feature

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#6127]
This is not really a bug, but rather a usability issue for myself and quite a few people I know who use AnkiDroid.

We now have flags, I believe introduced in 2.9 for the no-beta community. I have no issue with that in general, it's just that it doesn't integrate into my way of using AnkiDroid (pretty much the only version I do reviews with).

They are very prominent in the reviewer UI, for me too much so for a feature that I never use (I do acknowledge others might use them, I'm just expressing my own feelings about them). They moved my beloved star to be a second class citizen ;) Now, I never use flags, my workflow was to mark any card needing attention using a star ('marked' tag). I did this because I was able to use a gesture (double tap in my case) for this. There is also a ready-made 'marked' filter on Anki Desktop sidebar, which is the Anki version I mostly use for editing, just a click away. There was also a ready-made filter for 'marked' cards in AnkiDroid. All of this worked really nice and was quick.

I understand that I have been misusing the star for what should really be a flag. I couldn't care less whether the symbol is a star, a flag, or a turtle, I cared about the gesture and filters. Here are some thought on how to make it better:

1. Allow disabling the flags in settings. If I disable flags, the icon goes to the previous spot. This will make AnkiDroid the way it used to be (for me). Shouldn't be too much hassle to place the icons differently based on a boolean flag? (Just guessing.)
2. Allow defining gestures for flags (like list all the different flag colors in the list, and let me assign double tap to red, orange and other colors). Also add pre-made filters in the browser for them. This will also make AnkiDroid the way it used to be for me, although with a different icon, which I couldn't care less about. This option doesn't make Anki Desktop the way it used to be, so I guess I will head over there to have a sidebar filter added.

**Comment by C-Y-Liu** [comment]
You can go to `settings->reviewing->app bar buttons` to  control functions displayed in review mode. 
And the way to filter flags is the same as in the desktop, searching `flag:1` in browser to filter red flags, 2,3,4 refer to other colors.
I hope this could help you.

**Comment by wujek-srujek** [comment]
Thanks! I was looking for the setting but missed it somehow!
As for the filter - I know I can write queries, but I would need to type them. Alternatively, I need to perform a couple of clicks. Both is a step backwards from a dedicated menu (Android) / sidebar (desktop).

But I guess this can be closed. Or maybe transformed into a ticket to allow flagging with a gesture?

**Comment by mikehardy** [comment]
Yeah - edit to state what is missing based on the new information about app bar buttons. We intend to move people towards flags by making flags what is more prominent now, but no previous use case should have changed except for the improvement that if you don't have stars or flags on your app bar buttons (for whatever reason) now - in a tidy space efficient way - they will show in the reviewer mini bar. So even for star-only people that's kind of nice. But gesture support - sure, just that yes it would be a new feature

**Comment by wujek-srujek** [comment]
I will create a new ticket after all, I hope you don't mind. I just think the comments would confuse people.

**Comment by david-allison-1** [comment]
@wujek-srujek Thanks for taking the time to care!
