### ISSUE TITLE
SVG support?

### ISSUE THREAD

**Issue by Geremia** [ankidroid/Anki-Android#6129]
Unlike Anki Desktop, AnkDroid doesn't support SVG images.

**Comment by david-allison-1** [comment]
@Geremia Could you give an example and provide your Anki version information? As far as I know, SVGs work fine.

**Comment by Geremia** [comment]
@david-allison-1 No, #6101 isn't about loading SVGs but incorrectly loading PNGs (which happened to be rasterized SVGs).

I just tried [this test deck containing an SVG](https://ankiweb.net/shared/info/519289211) with AnkiDroid 2.9.6, and it displays the SVG. I wonder why it wasn't working in previous versions.
