### ISSUE TITLE
Allow to configure gestured to set / unset flags

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#6131]
Setting / unsetting flags is not yet available as a gesture, it would be nice to add this as AnkiDroid is aiming at making flags more prominent.

**Comment by david-allison-1** [comment]
Agreed.

**Comment by david-allison-1** [comment]
@wujek-srujek Would you be happy with a "Remove Flag" gesture as well?

My plans:

* Flag 1...4 - toggle
* Unset Flag

**Comment by wujek-srujek** [comment]
Yes, this is actually the way I'm using stars / 'marked' tag right now: double tap to toggle. If I could configure double tap to set a flag, and then again to unset it, this would be exactly what I need.

**Comment by david-allison-1** [comment]
@wujek-srujek Already implemented, works fine on my phone, got about half an hour of computer-based testing, followed by a manual code review, and it'll be ready to go in an alpha in the next few days.

**Comment by wujek-srujek** [comment]
Thanks!
