### ISSUE TITLE
Autoplay preview

### ISSUE THREAD

**Issue by Dudeusz** [ankidroid/Anki-Android#6133]
I wonder if it is possible to add new functionalities in the preview window (Android version)? The point is to be able to enable continuous playback of flashcards while driving, for example. Currently, it is only possible to manually move subsequent flashcards. Additional buttons are needed: preview all, shuffle, loop (i.e. play the selected deck in a loop) and the option to turn the voice on or off in the question or answer. Thanks to this, you will be able to listen to and repeat flashcards when you cannot manipulate and learn. And we don't waste time)

###### Actual Result

![Anki_Preview_03](https://user-images.githubusercontent.com/65052142/81461207-6bf66880-91aa-11ea-9a0d-b1d09f8bf564.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [ x ] character to confirm the points below:*
![Anki_Preview_01](https://user-images.githubusercontent.com/65052142/81461197-5a14c580-91aa-11ea-8644-a5fe9a7986de.jpg)

[  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[  ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Hi there! I thought this feature request was already recorded but perhaps it was just an interaction in the Play Store reviews and had not been written out. I do remember it though - at any rate, it's an interesting idea and I like the idea of an autoplay-without-consequences. Right now if you do it you get reviews recorded which made it seem to me like it was not necessarily useful, so I like this idea.

It's a volunteer project of course so no promises on if it will ever get implemented, but an interesting idea either way

**Comment by mikehardy** [comment]
Keeping this open - there's work towards a PR for it even
