### ISSUE TITLE
AnkiDroid can't load all installed system fonts

### ISSUE THREAD

**Issue by Arthus** [ankidroid/Anki-Android#6144]
###### Reproduction Steps

1. Have a rooted Android device and check the fonts available in /system/fonts.
E.g. Comic_Sans.ttf and Exotwo.ttf
2. Check the available fonts in AnkiDroid's settings
3. Try to use the fonts in /system/fonts for cards,
- "font-family: Exotwo;" 
- "font-family: Comic_Sans;"
- "font-family: Comic Sans;"
- "font-family: "Comic Sans";"
- "font-family: ComicSans;"
4. Copy the font files from /system/fonts to /sdcard/AnkiDroid/fonts
5. Try to use the fonts again
- "font-family: Exotwo;" 
- "font-family: Comic_Sans;"
- "font-family: Comic Sans;"
- "font-family: "Comic Sans";"
- "font-family: ComicSans;"
6. Delete fonts from /sdcard/AnkiDroid/fonts again
7. Rename Comic_Sans.ttf to ComicSans.ttf in /system/fonts
8. Try loading/using Comic Sans font for cards

###### Expected Result
2.) AnkiDroid lists all fonts that are available on the system

3.) I can somehow convince AnkiDroid to load the "Comic Sans" font

5.) Should behave more or less the same as 3)

8.) No expectation

###### Actual Result
2.) Only OpenSans and "System default" are shown in settings dialog.

3.) Exotwo font is loaded without problem. No combination makes Comic Sans load.

5.) Exotwo still loads. Using "font-family: ComicSans;" or "font-family: Comic_Sans;" loads Comic Sans as font.

8.) Now "font-family: ComicSans;" makes AnkiDroid load & use the Comic Sans font from the system folder (Maybe _ or - breaks parsing the font file?)

###### Debug info
AnkiDroid Version 2.10beta1

Android Version = 10 (Redmi Note 3 with Custom Rom)

ACRA UUID = 521087f7-500c-4737-9177-e052dde31e0e

###### Research
[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Just to set expectations, I'm not sure what the differences could be with font loading on rooted devices and custom ROMs but they might be substantial. I'd like to focus this on any deficiency with regard to custom font-loading as we support it via these instructions: https://docs.ankidroid.org/manual.html#customFonts

Can you edit this issue to focus it down to just following those instructions and any deviations from expectations based on those?

**Comment by Arthus** [comment]
In contrast I would like to let the issue stay like this at least for some time, as I want to dig into the issue myself. I think, just because AnkiDroid can load custom fonts, the compatability with system fonts shouldn't be neglected. But I understand when this is a low priority issue/feature request.

As every app needs to request root privileges and I'm sure, that AnkiDroid doesn't run with those, the rooting itself shouldn't have any influence.
Something that might influence it, is the use of a custom rom that could have non-standard access permissions for the /system/fonts folder. In my device those are set to 755, so everyone on the system can read and execute the folder's contents.

From some early research, it should generally be possible to read that folder's contents from any app to create an "installed font list", but I'm going to confirm this and then I will check, why some files get loaded (Exotwo.ttf is oviously loaded from /system/fonts) and some don't.

Sidenote: There an additional problem with the current custom font solution, that I want to check and will possibly create an issue for later (Custom Fonts are identified by their file name and not be the name they are installed with e.g. on Windows systems, breaking the CSS formating and creating an incompatability between Anki and AnkiDroid.)

**Comment by Arthus** [comment]
I think this can be closed for now.

I had a look into this issue and Android's handling of fonts is a mess. System installed fonts get their font names hardcoded. And while Android is obviously able to load otf/ttf files, it doesn't expose a call or variable to check the embedded font name from the file. It is incomprehensible to me, how they can not implement such a feature. The name, that Windows, Linux, macOS show for a font is directly in it's header, but Android apps have no way to read it from there without using a seperate TTF/OTF library or directly implementing a parser for it itself... Crazy

And I don't think it is worth adding another library to AnkiDroid for such a small feature. If anyone else disagrees, please reopen it.
