### ISSUE TITLE
Two previews can be created when in the card type editor

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#6148]
Sorry for creating so many issues when I haven't PR'ed recently.

###### Reproduction Steps

1. Have a note type with a large number of card types (27 card types in my case)
2. Go to the card type editor
3. Quickly double tap the preview button. I'm only able to do this quickly enough on my note type that has 27 card types
4. A preview will be shown. if the back button is pressed the user will be brought to another instance of the preview of that card type. 
5. Pressing back again brings the user to the editor

###### Expected Result
One preview generated regardless of number of taps

###### Actual Result
Two previews will be generated. Curiously I can't get 3 or more previews generated. Maybe this is handled by the recent changes in the card template editor?

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.10beta3

Android Version = 7.0

ACRA UUID = fd9d9e7c-9e17-4df3-810e-43af4dc764e2

###### Research
*Enter an [ x ] character to confirm the points below:*

[ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ X ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Thanks for the report! It's better to know about issues than to leave them lurking. 

Linking: #5151, as it'll probably be included in there.

**Comment by mikehardy** [comment]
Yeah - we already have some double-click protection in 5151 thanks to @david-allison-1 pointing out it is/was necessary. There's still one pending item on that PR before I can merge it but yes, it should go in there and this will serve as reminder to test

**Comment by freemedom** [comment]
looks great
