### ISSUE TITLE
Too high forecast for first week for specific deck.

### ISSUE THREAD

**Issue by Self-Perfection** [ankidroid/Anki-Android#6152]
On one of my decks weekly forecast for the next upcoming week is always too high. For instance:
![Screenshot_20200509-234118_result](https://user-images.githubusercontent.com/3757038/81609468-a0ec0080-93e0-11ea-82b4-b48ca13a64f3.png)![Screenshot_20200509-234106_result](https://user-images.githubusercontent.com/3757038/81609467-a0536a00-93e0-11ea-97bd-01601f816c1d.png)

According to daily forecast
week_1 = 21+24+20+17+12+19+16 =129
week_2 = 17+16+13+15+11+14+18 =104

On the second screeshot second week is forecasted correctly, but forecast for first week is exagerrated by ~50 cards. Desktop Anki shows weekly forecast according to my calculation from daily forecast and bar for first week forecast in desktop Anki forecast is way lower.

Strangely this miscalculation seems to be happening only for my biggest deck. Others are not affected.

###### Debug info
AnkiDroid Version = 2.9.6

Android Version = 9

ACRA UUID = 290aef3f-0be2-4f0d-bfd7-758f4121c30b

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
There was a change recently related to this but I'm not 100% sure. I wonder if the weekly is able to take into account siblings better? You'd have to investigate the statistics calculation code.

Some initial thoughts:
- in order to reproduce anything we'd need a collection and exact statistics settings (advanced or not, iteration count if so etc etc)
- you'd need to determine which one was correct - you imply that the weekly count is exaggerated, but what if it is correct and the daily counts are incorrect?

This part of the code hasn't been looked at in a long time that I'm aware of - and while I like it and it motivates me as a user as a developer or a maintainer I'd need someone else to take it up and address the concerns above by verifying correctness etc and proposing changes

Pull requests that do that very happily accepted

**Comment by jianersswlq** [comment]
Is that a feature of advanced statistics ?

**Comment by Self-Perfection** [comment]
Sorry for not responding for a long time.

With AnkiDroid 2.11.2 the issue is still present.

Advanced statistics is disabled.

I'm quite sure that it is weekly forecast that is incorrect:
* AnkiDroid calculates daily forecast exactly the same way as desktop Anki, but with with weekly forecast there is discrepancy in weekly forecast for the first week. AnkiDroid shows much higher forecast for the first week then desktop Anki. Other weeks are identical.
* I have checked that daily forecast is correct. When there is no buried cards on the next day number of due cards increases by exactly the same amount as was forecasted the day before.

The deck is hand-made and contains verious personal data, so I can't attach it here. But I probably can remove most of the personal data by removing fields that does not affect card number and due dates and send it to developers. Where should I send such example deck?

**Comment by mikehardy** [comment]
If you export the deck and then change it's extension to .zip you can just attach it here

**Comment by Self-Perfection** [comment]
@mikehardy I've sent sample deck to the e-mail you have specified in your github profile.

Even after cleanup this sample deck contains too much of personal data, I am reluctant to post it publicly for the whole web.

**Comment by mikehardy** [comment]
@Self-Perfection  I have received it, thanks! I'm working on the 2.12 release (still has one outstanding issue at least and I just landed a feature for it which may have follow-on work) so please be patient but I'll try to reproduce when I get a chance

**Comment by Self-Perfection** [comment]
I have re-checked with AnkiDroid release 2.12.1. The issue is still present.

**Comment by Self-Perfection** [comment]
AnkiDroid 2.13.5 still misforecasts first week.

**Comment by Self-Perfection** [comment]
AnkiDroid v2.14.2 still shows wrong forecast for upcoming week.
