### ISSUE TITLE
[2.10] Card Browser broken - Text too small

### ISSUE THREAD

**Issue by goodwins** [ankidroid/Anki-Android#6161]
With the new release of today (2.10), the text in the card browser is now so small it's impossible to read and select. See attached screeshot.

![Screenshot_20200513-124547](https://user-images.githubusercontent.com/29762760/81809031-f0394a80-9520-11ea-96d8-db96b6faebd4.png)

###### Debug info

AnkiDroid Version = 2.10
Android Version = 7.0
ACRA UUID = 74ec5238-8afa-4d5d-85f5-282d3c11fb89

###### Research
*Enter an [ x ] character to confirm the points below:*

[ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

[ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

[ x ] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Hi @goodwins, thanks for the report!

* Did you uninstall the app? 
* Could you tell me the value of: `Settings - Appearance - Card browser font scaling` 

You then should be able to change the value of the preference to fix your issue.

**Comment by goodwins** [comment]
To answer your questions:
1) I didn't uninstall the app. The app was downloaded & updated automatically because there was a new version available.
2) Default font = System default, this setting is remaining unchanged sine months (or even years).

**Comment by david-allison-1** [comment]
> 2. Default font = System default, this setting is remaining unchanged since months (or even years).

Thanks, what about the value of `Card browser font scaling`?

----

I'm stumped right now, I'll keep on looking. The code looks solid and unchanged. 

This could potentially be that rolling over from version 9 to 10 caused a version refresh, but the version numbers look good.

**Comment by goodwins** [comment]
You are right, it was Card browser font scaling. I changed it from 30% to 100%.
Looking back to previous issues in 2.9, it looks like it's related to issue #5512 being fixed in 2.10.
I guess this issue can be closed.
Thanks!

**Comment by david-allison-1** [comment]
Fantastic! Thanks
