### ISSUE TITLE
[2.10] - "Typed Answer" model in translated languages does not work

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6167]
###### Reproduction Steps

1. Change Language to Russian
2. Make a card as "Basic (typed)": Базовый (ввод ответа)
3. Flip the Card

###### Expected Result

4. Answer is displayed

###### Actual Result

4. `{unknown field Front}`

###### Debug info

Anki 2.10

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
I'll get the fix in for the bug tonight.

TODO:

* Discussion on how to fix this
* Discussion on regression tests to avoid this and similar problems

**Comment by david-allison-1** [comment]
This also doesn't work in English. Ref: #5493

Front:
```
{{Front}}
```

Back:
```
{{Front}}

<hr id=answer>

{{type:Back}}
```

Front should be:

```
{{Front}}

{{type:Back}}
```

**Comment by mikehardy** [comment]
So if I understand correctly the PR will stop new users from generating bad data, but any existing users will potentially have bad data in their created-from-scratch collections and there needs to be a fixIntegrity mopup that harmonizes the fields, I think? As on Discord - just thinking that out loud

**Comment by david-allison-1** [comment]
> will potentially have bad data in their created-from-scratch collections and there needs to be a fixIntegrity mopup that harmonizes the fields, I think? As on Discord - just thinking that out loud

Yep, the complexity is with defining "what is a bad template". 

Equality on {`Name`, `afmt`, `qfmt`} with a known bad (blacklist) seems like the best option.
 
Another complexity is that this `fixIntegrity` doesn't require a full sync on success, so we'll need to emulate Anki's recent change to allow checks which don't trigger the schema change.

Does this seem reasonable?

**Comment by mikehardy** [comment]
That does sound reasonable yes
