### ISSUE TITLE
Language change bug v 2.10

### ISSUE THREAD

**Issue by LordGSama** [ankidroid/Anki-Android#6171]
###### Reproduction Steps

1. Change system language in settings to any non English language
2. 
3. 

###### Expected Result
In the previous version, pretty much all instances of English were replaced with the selected language and I expected that to occur in the update.

###### Actual Result
Many items that were previously translated are still shown in English. Here are specific instances of untranslated text:

Deck menu:
   > Number of cards remaining
    > Options
Flashcard window:
     > Same as above as well as the 4choices after you reveal the back of the card.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
The only additional info that might be relevant is that i am using a Samsung device running Android 6.0.1.

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Many strings changed, this is on contributors to fix, I sync the languages regularly and it is trivial to fix them - please go translate your language :pray: https://github.com/ankidroid/Anki-Android/wiki/Contributing#translate-ankidroid
