### ISSUE TITLE
Feature: more visible flags

### ISSUE THREAD

**Issue by Mornon** [ankidroid/Anki-Android#6173]
I just noticed in the last version it's possible to add flag directly from the card we are studying, but I to me they are kinda unnoticeable: with the card in mid-screen, I did some test and it's not unlikely (on the contrary) that I miss that the card is flagged. Would it be possible (and make sense) to have an option for a more visible flag, like an opt-in option that puts a flag next to the shown word (or content in general)?

**Comment by david-allison-1** [comment]
Hi @Mornon,

Could you send a screenshot please? 

Afterwards, you can move the flag icon to the action bar by going to: `Settings - Reviewing - App Bar Buttons`

You can also use `{{UserFlag}}` in your card template, and use JavaScript to customise the appearance based on that value.

Please let me know if this helps, or if you still need a change in the AnkiDroid code

All the best,

David

**Comment by Mornon** [comment]
I already have the button in the action bar, and when I tried to use `{{UserFlag}}` I got an error:

> Found '{{UserFlag}}', but there is no field called 'UserFlag'

This is what I see at the moment:

![photo_2020-05-14_11-01-22](https://user-images.githubusercontent.com/21358808/81926675-98631800-95e2-11ea-9e16-87f841bb272b.jpg)

But with the flag in the upper screen it's likely I won't notice if the card is flagged, unless I purposely check every time, since I'm concentrating on the middle screen, where the card is. So it'd be great to be able to have something like this:

![002](https://user-images.githubusercontent.com/21358808/81926758-c8aab680-95e2-11ea-9e54-61e51bb8632f.jpg)

with the flag appearing also near the card (just as a icon, also without being able to interact with it), or some other visual clue.

Using the template to add formatting, like we can do with tags, would be an option, giving it'd overlap with formatting from tag, but if it's possible I don't know how to do it (since `{{UserFlag}}` gives error).

**Comment by david-allison-1** [comment]
@Mornon Sorry... try `{{CardFlag}}`

**Comment by Mornon** [comment]
That works, thanks!

**Comment by david-allison-1** [comment]
Cheers!
