### ISSUE TITLE
Links to external font no more working in card style

### ISSUE THREAD

**Issue by Cliohist** [ankidroid/Anki-Android#6178]
###### Reproduction Steps

I have links to specific personal fonts for somme languages in my card styles.
The goal is the same as integrating the font to the deck. But external link is usefull when the font is to be regularly udated and modified.

1 - In card styles create a : 
`
@font-face {
font-family: 'hiero_h';
src: url('http://www.hierotext.com/fonts/Fonte perso/dico_hiero_h.ttf');}
@font-face {
font-family: 'hiero_s';
src: url('http://www.hierotext.com/fonts/dico_hiero_s.ttf');}
`

2 - Adding some CSS format
`
.hiero{ align:center;}
.hs{ font-family: hiero_s; font-size: 32px; border:0px}
.hh{ font-family: hiero_h; font-size: 32px;}
`

3- In recto card model
`<div class=hiero>{{Front}}</div>`

4- In {{Front}} field html content
`<table><tbody><tr><td rowspan="2"><span class="hs"></span></td><td rowspan="2"><span class="hh"></span></td><td rowspan="2"><span class="hh"></span></td><td rowspan="2" valign="bottom"><span style="font-family: hiero_h"><font size="5">&nbsp;&nbsp; </font></span><font size="5"><font size="2"></font></font></td></tr></tbody></table><br>`

--> this content should work if there is not problemen of conversion in the database.

Problem is the same with more simple font.

###### Expected Result

The cards should show use of the external font.
It worked this morning (14/05/2020). Then I had a notification for a kind of update asking to verify the database. I did so and after that the fonts would not display any more (14/05/2020 > 14h00). 
Still working correctly under the PC Anki.

###### Actual Result

External fonts are not used. Probably using a default font instead.
I verified my server where the font is hosted was not down.

###### Debug info

AnkiDroid Version = 2.10
Android Version = 9
ACRA UUID = 6ada0961-8f8f-461e-bfa6-1cbfc57d9217

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Confirmed: works on 2.9.0. Fails on latest alpha. 

Error in Chrome Console: `Failed to load resource: net::ERR_CLEARTEXT_NOT_PERMITTED`

Cause:

https://github.com/ankidroid/Anki-Android/blob/b8e3dd8da0abae3de86026a7aa2412aa50574781/AnkiDroid/src/main/AndroidManifest.xml#L91

Added in c58a38a80410cdd9aa4071e49a8bfe2b4f24e9dc (#5435/#5423)

**Comment by david-allison-1** [comment]
This can be fixed by modifying `<base-config>` to: `    <base-config cleartextTrafficPermitted="true">`

I don't fully understand the security implications. @mikehardy ?

**Comment by mikehardy** [comment]
The world is moving to HTTPS. We can make this change but the reporter should move to HTTPS, we're fighting a losing battle here as google complains when we submit insecure builds like this, and they'll just lock it down some other way with the next update

There's a change already that allows user installed certificates so they may secure themselves for free

I'm going to close / won't fix -> upgrade to secure channels

**Comment by Cliohist** [comment]
Ok
Thank you very much. I moved the fonts to an HTTPS server and everything works fine.
Would never have thought of that.

I don't know if other people will be surprise to find their font not working any more. Or how could people be informed.
Il looked down in the Anki manual, but they don't talk about the option of external links.
I don't know how I found this.

Anyway thanks for the information
And thanks for all the work. Ankidroid has become really important to me ;-)

Paul Wheeler

**Comment by mikehardy** [comment]
Yeah, we strongly recommend keeping things in your collection. Offline capability is a huge selling point of the Anki system. It is cool that this is possible but I'd never recommend it so I'm not surprised it's not in the docs, and this should be a niche case
