### ISSUE TITLE
chesspgn is not working in 2.10

### ISSUE THREAD

**Issue by khoramshahi** [ankidroid/Anki-Android#6181]
Thank you so much for this great application!!!

###### Reproduction Steps

1. Download the "PGN Chess Fashcards" from https://ankiweb.net/shared/info/340753088
2. Study the Deck (which has one card)

###### Expected Result
In V2.9, Anki shows the chessboard and the user can make the move that is expected in the PGN

###### Actual Result
inV2.10, The chessboard is not displayed.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @khoramshahi,

Could you confirm whether this is reproducible under AnkiDroid 2.10.2: https://github.com/ankidroid/Anki-Android/releases

All the best,

David

**Comment by khoramshahi** [comment]
Hi David,

I have the same issue on 2.10.2.
I updated my Anki using Google Play store.

My log file (if it is of any use) shows:
[1589992332] Collection.java:<init>(): /storage/emulated/0/AnkiDroid/collection.anki2,  2.10.2
[1589992332] Sched.java:_updateCutoff(): 869,  1589997600
[1589992334] Sched.java:_updateCutoff(): 869,  1589997600
[1589992334] SchedV2.java:getCard(): 'mData': ,  'mDid': 1583945841156,  'mDue': 800,  'mElapsedTime': 0.0,  'mFactor': 2500,  'mFlags': 0,  'mId': 1526829043313,  'mIvl': 0,  'mLapses': 0,  'mLastIvl': 0,  'mLeft': 1002,  'mMod': 1583961077,  'mNid': 1526828844572,  'mODid': 0,  'mODue': 0,  'mOrd': 0,  'mQueue': 3,  'mReps': 2,  'mType': 1,  'mUsn': 158,  'mWasNew': false

**Comment by david-allison-1** [comment]
@khoramshahi Thanks!

I'll get to this in a day or two, please feel free to follow up if you don't hear back within that time frame.

**Comment by david-allison-1** [comment]
@khoramshahi 

Sorry, wasn't the issue that I expected.

Please: 

* Contact the deck author and request that they use HTTPS
* Edit the card, Click "Cards", change all links to HTTPS on the Front and Back of the card

Hope this helps. Please feel free to reopen the issue if this doesn't solve your problem

**Comment by khoramshahi** [comment]
@david-allison-1 

It works! Thank you so much for your help on this!
