### ISSUE TITLE
Sync initialization absent when screen is too big

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#6182]
###### Reproduction Steps

1. Install AnkiDroid on a chromebook
2. Try to sync
3. Resize the window and try again

###### Expected Result
See the message stating that we need to connect to an extern server to sync, and do it at next step.  In french it's "Se connecter à AnkiWeb.
Vous devez vous connecter à un service tiers pour utiliser le service de synchronisation. Vous pouvez créer un compte à l'étape suivante".

Then seeing a button to go to next step.

###### Actual Result
Except for very specific size, there is no button. So no way to add an account.

I don't have an easy way to know the size of the application. What I can tell you is my full screen size is 2560x1440. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.9.7

Android Version = 9

ACRA UUID = e3a99550-00d1-40ab-9d7d-33dd16b760c8

Same problem with 
AnkiDroid Version = 2.10.1

Android Version = 9

ACRA UUID = e3a99550-00d1-40ab-9d7d-33dd16b760c8

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

I found a solution. Trying until I get a size at which the button appear. That's not a satisfying solution.

- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Interesting - I check on the chromebook sometimes (there is an emulator available for it, I don't actually have a chromebook in case anyone else wants to try it...) but it's been a while

**Comment by Arthur-Milchior** [comment]
I would expect that the problem is mostly related to the size and not to the device itself. I might be wrong, but given that the problem appear on not depending on the size, and that this is a unusual size for an android, I expect this to be the main trouble

**Comment by dae** [comment]
A lot of time has passed; let's assume it's fixed until we hear otherwise.
