### ISSUE TITLE
Anki displaying both back and front card on the front ?

### ISSUE THREAD

**Issue by SimonePols** [ankidroid/Anki-Android#6185]
See below the screenshots.

1) I create a flashcard

2) I play and I already see the back part of the flashcard in front, next to the front part

3) I click "show back" and I see now the back part as well

Any idea?

I am running the latest version of the app on a huawei P20 Lite. The problem occurs even if I create the flashcards on my laptop and play with it on the laptop itself (both when I create a flashcard on the desktop program and on the online version, I tried with a dell running W10 and with an old acer running Vista)

![Screenshot_20200515_142112_com ichi2 anki](https://user-images.githubusercontent.com/65402058/82049977-9a4adb00-96b7-11ea-8788-1005cc38f640.jpg)
![Screenshot_20200515_142057_com ichi2 anki](https://user-images.githubusercontent.com/65402058/82049980-9b7c0800-96b7-11ea-938c-54b04f041d46.jpg)
![Screenshot_20200515_142108_com ichi2 anki](https://user-images.githubusercontent.com/65402058/82049981-9c149e80-96b7-11ea-9b1e-1467024cf378.jpg)

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by david-allison-1** [comment]
Hi @SimonePols,

Thanks for the report!

That's a templating problem:

* Edit a bad card
* Click "Cards..." at the bottom of the screen
* A template editor will appear. You'll see `{{Back}}` in the question template
* Remove it

Let me know if this helps,

Thanks for using AnkiDroid

David

**Comment by SimonePols** [comment]
Thanks David ! You are the best!

Fixed already, I can come back to my Russian (-:

Thanks again
Simone

**Comment by david-allison-1** [comment]
Awesome, happy to help!
