### ISSUE TITLE
Please update the Changelog

### ISSUE THREAD

**Issue by jondo** [ankidroid/Anki-Android#6197]
###### Reproduction Steps

1. Note that the [changelog](https://docs.ankidroid.org/changelog.html) is at version 2.9.2, while the latest [releases](https://github.com/ankidroid/Anki-Android/releases) are 2.9.7 and 2.10.2.

###### Expected Result
All (but the alpha and beta) releases should be listed in the changelog.

**Comment by mikehardy** [comment]
Indeed! Sorry about that - it's up to date now
https://github.com/ankidroid/ankidroiddocs/pull/49
https://docs.ankidroid.org/changelog.html

**Comment by mikehardy** [comment]
When #6199 merges the script we use to release new public versions will enforce that these are up to date so lazy and/or forgetful maintainers (me :rofl:) won't be able to subvert the process and have the public site go stale anymore. Thanks for reporting it
