### ISSUE TITLE
"Unbury" doesn't work

### ISSUE THREAD

**Issue by Mymaa** [ankidroid/Anki-Android#6200]
1. Long tapping on any deck in the deck list
2. Tapping "unbury"
3. That operation doesn't work at all or cancel the wrong number of bury cards

Also;

1. Tapping on "custom study session"
2. Tapping on ... menu on the top of the screen and then tap on "option" (in Japanese オプション)
3. In the "search conditions of filter" (in Japanese フィルターの抽出条件)
4. Putting "is:buried" in the box
5. That operation doesn't work at all

But;

1. Tapping on "card browser" in the drawer menu
2. Tapping on the magnifier icon on the top of the screen
3. Putting "is:buried" in the box
4. That operation seems to work properly

Also, buried cards turn into unbried automatically tomorrow. (normal function)

All the operation above worked properly before version 2.9.7.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.10.2

Android Version = 9

ACRA UUID = 1c3742fa-517d-4191-a140-6c1031b0a391

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
1. What do you mean by "cancel the wrong number of buried cards"?

* Are you using the experimental V2 Scheduler, or the regular scheduler?

----

2. Buried Cards can't be reviewed until the next day

**Comment by Mymaa** [comment]
Sorry. "That operation doesn't work at all or cancel the wrong number of bury cards" is not accurate.
Correctly, 
  (1) That operation seems to work most of the cases, specifically before finishing all the tasks of the day. But I don't confirm it in every time.
  (2) Once the task is completed, that operation doesn't work most of the cases. But it has worked properly once or twice in 2 decks after updating into 2.10.x

- I use the regular scheduler.
- I don't use parent / child (sub) deck function. I think both 2 decks are parent.
- All the buried cards are manually buried not sibling cards of reviewed or new.

I hope you could find it reproduced and define / fix the issue.
Thank you very much for your cooperation.

**Comment by david-allison-1** [comment]
@Mymaa 

Replicated! Thanks for the help

**Comment by david-allison-1** [comment]
Before this is fixed, please select the deck that you would like to bury before pressing "Unbury". Apologies about the inconvenience

**Comment by Mymaa** [comment]
I'm happy you could find / define the issue and said it will be fixed!
I look forward to the day.

> select the deck that you would like to unbury before pressing "Unbury"
Noted. It's not so inconvenient for me. Thank you for giving me a workaround.

**Comment by david-allison-1** [comment]
Great!

It's fixed in the beta now, and will be in the next release (I'd hope within the next two weeks).

Thanks for your understanding

Thanks for the report, and thanks for using AnkiDroid,

David
