### ISSUE TITLE
Card overview barely readable since 2.10

### ISSUE THREAD

**Issue by januario-hh** [ankidroid/Anki-Android#6204]
###### Reproduction Steps

1. Kitkat 4.4.2/Anki 2.10.2
2. open card overview
3. the usual overview appears

###### Expected Result
readable entries, as usual since the beginning until some weeks ago

###### Actual Result
font now far too small. Can barely read the entries, even when I use my reading glasses.

###### Debug info
AnkiDroid Version = 2.10.2

Android Version = 4.4.2

ACRA UUID = d4aa20fc-010f-432e-a43d-6f490778581b

###### Research
*Enter an [x] character to confirm the points below:*

- [ ×] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [× ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [× ] I have searched for similar existing issues here and on the user forum
- [× ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! There is a scaling factor for the card browser in the preferences, try manipulating that. We have had a couple reports of this from 2.9 to 2.10 upgrade as we changed the underlying library that implements it and fixed a related bug - all users have reported success by using that preference, so I'm going to close this pre-emptively but obviously we can reopen if that doesn't help

**Comment by david-allison-1** [comment]
`Settings - Appearance - Card Browser font scaling (bottom option) - Set to 100%`
