### ISSUE TITLE
[Feature - Dev] - Expose "Interesting" configuration variables in analytics

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6207]
> is it possible on app startup, for people with analytics enabled, to send a quick summary of "interesting configuration elements" - which I interpret as just config items we're curious if people are using or not. If it is (it should be?) then it would be interesting to tag this (as well as e.g. custom language, notifications, v2 scheduler, maybe others?) just to see what's getting used and what isn't. That could help justify future maintenance if it becomes a burden (shouldn't but you never know)

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/6205#issuecomment-629877792_

----

Probably best to start a list (happy to see this edited directly/suggestions welcome):
 
- [ ] SchedV2
- [ ] Block Tap Gesture
- [ ] Gestures
- [ ] Auto Play Audio
- [ ] Dictionary Lookup in Reviewer (I think this is broken)
- [ ] Advanced Statistics
- [ ] Widget
- [ ] Notifications
- [ ] Chess
- [ ] Custom Fonts (& sizing)

**Comment by Arthus** [comment]
I already like, that SchedV2 is listed twice. 👍 I would guess, that this will be supported as long as Anki supports it, right? So "Scheduler Version" might be the better term. SchedV2 is imho more powerful and enables better managment/learning practices. If a scheduler were to be dropped, I hope it is SchedV1.

Maybe you could add "Custom Fonts" to the list?

**Comment by mikehardy** [comment]
even better maybe the size of the custom font! Yeah schedv2 is the future, no worries there

**Comment by david-allison-1** [comment]
Good catch! Fixed

We'll have problems convincing some users to switch to SchedV2 using Anki's method of conversion (removing cards with current steps) -  some settings have learning steps of 90+ days, and asking them to give up all step based learning is a massive ask.
