### ISSUE TITLE
Anki displays multiple times in App Drawer if launched from Google Drive

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6218]
###### Reproduction Steps

1. Move an apkg to Google Drive
2. Move Anki to Card Browser
3. Select File in Google Drive

###### Expected Result

4. Anki should display the import screen

###### Actual Result

4. Anki displays the import screen, but two instances appear in the app drawer.

###### Debug info

AnkiDroid Version = 2.9.7

Android Version = 9

ACRA UUID = cf8c9575-7901-4dc1-b0cf-09c6e3db3613

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
read up on singleTop, singleInstance etc Intent styles. I don't think this is necessarily a problem.

**Comment by david-allison-1** [comment]
It doesn't seem like an ideal from a UX perspective, but I'm not massively fussed as it's a niche issue. 

Fine to close as WONTFIX?

**Comment by mikehardy** [comment]
Yeah - I think this will happen with any app that uses activities from other apps to do imports or file selection or similar. I've seen it with the "majors" as well (whatsapp, google apps etc) if you try to use dropbox from them, or are in say dropbox and sharing to them.
