### ISSUE TITLE
Feature request: Add option to disable context menu entry "card browser".

### ISSUE THREAD

**Issue by RedSoul001** [ankidroid/Anki-Android#6226]
###### Feature request

1. Add an option in AnkiDroid's settings to disable the "card browser" context menu entry.

###### Expected Result
"Card Browser" will no longer appear in the context menu when highlighting text in other apps. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there!
Not sure this is possible. I believe it's added automatically by the system because we list the CardBrowser as being able to process text: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/AndroidManifest.xml#L213

There does not appear to be any way to implement the feature at all without having it show up for text selections in the system permanentely

**Comment by david-allison-1** [comment]
Potentially: https://stackoverflow.com/a/14142215

It's something that I'd like to look into in a week or so. I have 3 AnkiDroid instances on my phone, and having 3 context menu items is annoying.

**Comment by mikehardy** [comment]
Ah - I read in that area but it didn't click. Make an alias activity that exports that intent-filter, then on toggle in preferences disable the component? Is that persistent for the duration of the application install? It's liable to come back every update but we have a boot receiver and I think could do an install event receiver so we could hopefully keep it disabled if it re-enabled counter to preference post update.

**Comment by david-allison-1** [comment]
I'll need to do some testing. But seems like a good plan of action if Android lets us do it.
