### ISSUE TITLE
Anki custom study session changes original card state

### ISSUE THREAD

**Issue by vibeeshcv** [ankidroid/Anki-Android#6228]
###### Reproduction Steps

1. I started custom study session on Synonyms and antonyms 
![Screenshot_20200520-161426~2](https://user-images.githubusercontent.com/64941506/82439096-bc799a00-9ab7-11ea-9cc0-d3e9042ccc00.png)

2. Reschedule turned off 
![Screenshot_20200520-161526](https://user-images.githubusercontent.com/64941506/82439268-fc408180-9ab7-11ea-8d74-4fc1890b3e03.png)

3. [Apkg file of the session](https://drive.google.com/file/d/1e4s_lQewsdVVjzqYu1jzUZxKI5hBafY6/view?usp=drivesdk) 

###### Actual Result

The original card session state changed 
![Screenshot_20200520-161611~2](https://user-images.githubusercontent.com/64941506/82439419-41fd4a00-9ab8-11ea-8d50-10d00ce4c21f.png)

###### Debug info

AnkiDroid Version = 2.10.2

Android Version = 9

ACRA UUID = 6e2a8e53-f25c-4cc6-a183-7dab54dad6a0

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by vibeeshcv** [comment]
Anki desktop has no issue working fine

**Comment by david-allison-1** [comment]
Got it, SchedV1 should not be pulling learn cards into filtered decks: https://github.com/ankitects/anki/commit/13c54e02d8fd2b35f6c2f4b796fc44dec65043b8
