### ISSUE TITLE
Night mode don't show scalable LaTeX

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#6245]
###### Reproduction Steps

1. Have a computer with LaTeX compiler installed
1. Open the note type manager
1. Choose a note type, e.g. basic, and click on "Options"
1. select "create scalable images with dvisvgm"
1. Create a note with some latex. E.g. `[$]2[/$]`
1. Sync on ankidroid
1. Move to nightmode
1. Review this note

###### Expected Result
Seing "2"

###### Actual Result
Seeing an entirely black screen.

###### Debug info
Master, plus all of my PR merged.

###### Research
This recent feature of anki allow to compile to SVG with transparent background, instead of png with white background. Anki uses the fact that it's a SVG to inverse the colors while in night mode. AnkiDroid just display the image.

I do not know why this color change occur only in LaTeX and not all svgs.

This is done in the file "qt/ts/scss/reviewer.scss", thanks to 
```
.nightMode {
    .latex {
        filter: invert(100%);
    }
}
```
LaTeX being a class applied to images obtained using LaTeX

**Comment by mikehardy** [comment]
releated #6206  / not sure if we emit the '.latex' CSS id correctly on our latex images but this is all of a piece, HTML/JS debugging wiki page shows how to connect to running ankidroid webview (or to get card.html for local work)

**Comment by david-allison-1** [comment]
> releated #6206 / not sure if we emit the '.latex' CSS id correctly on our latex images but this is all of a piece, HTML/JS debugging wiki page shows how to connect to running ankidroid webview (or to get card.html for local work)

`class="latex"` is applied

**Comment by Arthur-Milchior** [comment]
FYI the html is generated in AnkiDroid/src/main/java/com/ichi2/libanki/LaTeX.java
