### ISSUE TITLE
Missing Language Name for "yu"

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6254]
###### Reproduction Steps

1. Open Anki at provided commit
2. Scroll Down in the Language Picker

###### Expected Result

3. `yu` is displayed at the bottom

###### Actual Result

3. A name is given to the language.

Note: We might also need to ensure that each of the languages is picking up the correct value if there's a mismatch

###### Debug info
Run from commit 6d7e2deac75ecc5548bfb919b2cf752c498506a7

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Interesting - may not be anything I can do about that, it appears that crowdin has a superset of Android languages? I haven't done the comparison but that's my guess and seems silly in retrospect to think that the sets of available languages would be 1-to-1 between the two. Unsure how to handle if that hypothesis bears out. I guess we'd need to have the language name itself be one of the strings in our translation string set

**Comment by mikehardy** [comment]
This appears to be the canonical list of languages and langauge subtag 'yu' is not present, though there are lots of yuX' languages (for many Xs). Still investigating. crowdin may have a non-conformant sub-tag that we need to translate to fit IANA which is likely what Android uses (though that also needs confirmation)

**Comment by mikehardy** [comment]
Okay - I think 'yu' (which is a custom language in crowdin instead of Cantonese standard codes unfortunately) will be fixed in the next export as 'zh-yue'

Working on filipino (perhaps 'fil-rPH' is correct?) and I think I can do it with a language mapping in crowdin.

End of work effort for the moment

**Comment by david-allison-1** [comment]
Just to note:

> This is because `forLanguageTags` accepts [IETF Language Tags](https://en.wikipedia.org/wiki/IETF_language_tag)..

https://github.com/ankidroid/Anki-Android/pull/6138#pullrequestreview-411378801

**Comment by mikehardy** [comment]
Thanks for those pointers! I'm far from an expert in the area but taking the opportunity to learn :-). Amazing rabbit-hole, this locale stuff...

**Comment by mikehardy** [comment]
If I'm reading that right and followed the links correctly, flipino should be 'fil' and Yu/Yue/Cantonese should be yue

I'll experiment with those to make sure they map correctly - most of the work here will be in the testing I'm sure, same as ever

**Comment by mikehardy** [comment]
Indeed - crowdin calls 'yu' 'Cantonese', which IANA designates as 'yue' so we're on the path here. 

'yue' works in the app if I can map the export of the existing custom 'yu' language on crowdin to it, we're set. ('fil' and 'got' also work after I fixed the import script to not have a 2-character language code expectation)
