### ISSUE TITLE
[Suggestion] - Be more permissive on file imports

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6259]
###### Reproduction Steps

1. Export a file and have a name conflict with a file which already exists
2. File is named "collection.colpkg (1)" due to the SAF: https://stackoverflow.com/q/32849387. Ref: https://github.com/ankidroid/Anki-Android/blob/ac91fd6a51d6aa61c0eaa298aa9fcbf4aa9b30a4/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L1897-L1909
3. Import "collection.colpkg (1)"

###### Expected Result

4. Collection is imported

###### Actual Result

4. This isn't a valid Anki package file\n Filename "collection.colpkg (1)" doesn't have .apkg or .colpkg extension.

###### Debug info
AnkiDroid Version = 2.11alpha6

Android Version = 9

ACRA UUID = 0292ff8f-1cba-4ded-bf2b-b48989e552de

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Oh very interesting. I'd be fine with a String.startsWith on the extension for either one we expect. Should we be even tighter with it or does it matter? A user can literally try to import anything by renaming it correctly so we can't ever trust input anyway, might as well be as permissive as possible?

**Comment by dae** [comment]
Those files won't import into the computer version, so I worry this may just be punting the confusion down the line. Why not add a datetime stamp to the filename like the computer version does instead, so that the extension doesn't get modified?

**Comment by david-allison-1** [comment]
We wouldn't be able to import `collection.apkg` as a deck package in that format currently. 

https://github.com/ankitects/anki/blob/7384df8f19216bd26aa3a3e1998a62773a7d7551/qt/aqt/importing.py#L452-L454

Is adding in another case (collection-yyyyMMddHHmmss.apkg) here feasible?

----

@mikehardy, would you prefer a revert, or move forward with a fix? Only the last two commits in the PR need to go.

**Comment by mikehardy** [comment]
@david-allison-1 move forward with a fix I think

I still don't mind accepting more liberally though personally based on the thought that the import code needs to be robust against untrusted input anyway, what do I really care what the package extension is? It's just a convention for launchers, which is fine, but if someone is in my app already and directly asking me to import something, why not?
