### ISSUE TITLE
[Suggestion] Tasker API

### ISSUE THREAD

**Issue by JulyMorning** [ankidroid/Anki-Android#6281]
Please, integrate the Tasker API into the app. I've [explained the thing in the another thread](https://github.com/ankidroid/Anki-Android/issues/4709#issuecomment-633482562) , but it deserves to have a separate one.

**Comment by mikehardy** [comment]
The Tasker API is already handled as mentioned in the other thread, but only for things that are core to AnkiDroid, like, syncing:

https://github.com/ankidroid/Anki-Android/blob/5b5afadaf3be5fc7456ae50c89ff2e0921e0db3d/AnkiDroid/src/main/AndroidManifest.xml#L174-L178

We will likely not merge things that are supported by the API, also as mentioned in that thread, with a pointer to the sample app we maintain to help people work with it
