### ISSUE TITLE
Is there an AnkiDroid developer Slack/Discord/IRC?

### ISSUE THREAD

**Issue by jgscherber** [ankidroid/Anki-Android#6283]
Question is the title -- Is there an AnkiDroid developer Slack/Discord/IRC?

I have a question around setting up a test Note (i.e. one that will be marked as "leech" on next review)

**Comment by genedan** [comment]
https://discord.gg/jPxDCK

**Comment by jgscherber** [comment]
To close out the issue - I was able to get a card trigger to leech by setting leech amount in Deck options to `1` and then updating a new card in the SQLite DB
```sql
update [cards]
set
	[usn]=-1, -- changes made
	[type]=2, -- review
	[queue]=2, -- review
	[due]=0, -- days from deck creation
	[factor]=2500, -- 2.5x more days
	[reps]=20
where [id]=<note id>
```
