### ISSUE TITLE
Card Browser: Can't browse certain decks containing brackets and stars

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6288]
###### Regression Test

Please use `*Yr1::Med2::CAS4::F4: Renal::BRS (zanki)::HY` as input. Works in Anki Desktop

###### Reproduction Steps

1. Name a deck `*Hello (zanki)`
2. Add a card
3. Card Browser

Note: `Hello (zanki)` and `*Hello` both work fine
###### Expected Result

4. Card is shown

###### Actual Result

4. Card is not shown

###### Debug info
Latest alpha

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Cause:

The wildcard in the deck name triggers a regex search, and the brackets then fail the regex

https://github.com/ankidroid/Anki-Android/blob/36e385520c1b23c157b2d0a4e03b6f6146b45049/AnkiDroid/src/main/java/com/ichi2/libanki/Finder.java#L630-L648

**Comment by jianersswlq** [comment]
Hello. What is the meaning of "use *Yr1::Med2::CAS4::F4: Renal::BRS (zanki)::HY as input"? Could you give some tips to understand this? Thanks a lot.

**Comment by david-allison-1** [comment]
> Hello. What is the meaning of "use *Yr1::Med2::CAS4::F4: Renal::BRS (zanki)::HY as input"? Could you give some tips to understand this? Thanks a lot.

Use `*Yr1::Med2::CAS4::F4: Renal::BRS (zanki)::HY` as a deck name if writing a regression test, as this was the input which caused problems originally.

**Comment by jianersswlq** [comment]
Why execute _val = val.replace("*", ".*");_  when searching input contains _*_ ?

**Comment by david-allison-1** [comment]
> Why execute _val = val.replace("_ * _", "_ .* _");_ when searching input contains _*_ ?

Because we assume that if a user types in a star, it means "match anything".

In regex terms, the star is the [Kleene Star](https://en.wikipedia.org/wiki/Kleene_star) operator, which needs to be applied to something `.*` represents "match anything".

Ideally, the fix for this problem would be to do a `Decks.byName` and return the deck if we have an exact match, then perform the regex search if a star is contained in the input.

**Comment by jianersswlq** [comment]
Actually, I find that problem in card browser. When the deck name contains wildcard and brackets, the cards in this deck will not display in the card browser. When the context contains wildcard and brackets which is as the input of card searching, the result of cards don't display too. Do you think these could be two issues?

**Comment by david-allison-1** [comment]
Apologies, typo on my description. Fixed. This is the Card Browser.

**Comment by mikehardy** [comment]
Just a note: I'm curious how AnkiDesktop handles this. Is this just us? Might be they restrict those from deck names somehow (then we should also restrict) or that they have the same bug (then they'd love to know I'm sure)

**Comment by david-allison-1** [comment]
> Just a note: I'm curious how AnkiDesktop handles this. Is this just us? Might be they restrict those from deck names somehow (then we should also restrict) or that they have the same bug (then they'd love to know I'm sure)

Works in Anki Desktop (mentioned in the OP, first paragraph). Haven't had the time to look into how it's implemented.

**Comment by mikehardy** [comment]
Aw dang - I scanned to see but missed that it was already stated. Sorry

**Comment by anadi198** [comment]
> Ideally, the fix for this problem would be to do a `Decks.byName` and return the deck if we have an exact match, then perform the regex search if a star is contained in the input.

Hi, I would like to try and solve this issue

**Comment by mikehardy** [comment]
@anadi198 with our blessing! Good luck and feel free to ask here if you have questions

**Comment by anadi198** [comment]
@mikehardy I just realised there's PR for this, so should I consider that as closed for good?

**Comment by mikehardy** [comment]
@anadi198 the PR was closed for simple lack of response, it may be correct. Best course of action is to pull the branch from the PR to see where it is, test it, and if it looks good submit a new PR with it

**Comment by anadi198** [comment]
Ok, I will do that.

**Comment by anadi198** [comment]
@mikehardy I tried the code in that PR and it seems to have fixed the issue(for `Hello (zanki)`). I'll open the PR.

**Comment by mikehardy** [comment]
Thanks! It seems like a small thing, but the simple act of testing it etc takes time and no one else had it. Very much appreciated it!
