### ISSUE TITLE
Custom Steps (in minutes) recommends phone number entry

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6291]
###### Reproduction Steps

1. Open Filtered Deck - Options - Custom steps (in minutes)
2. Clear the field

###### Expected Result

3. Nothing is suggested

###### Actual Result

3. A Phone number is suggested

###### Debug info
2.11alpha7

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
The implementation needs further testing for internationalisation. 
Just seen 0 formatted as `٠` (arabic-indic digit zero).

https://en.wikipedia.org/wiki/Hindu%E2%80%93Arabic_numeral_system#Glyph_comparison

**Comment by mikehardy** [comment]
fiendish it is

**Comment by Arthur-Milchior** [comment]
I don't get it. Why would you expect a phone number to be suggested ?

**Comment by david-allison-1** [comment]
Ugh, transposed the two fields. Fixed.

**Comment by Arthur-Milchior** [comment]
Makes far more sens. Thanks

**Comment by david-allison-1** [comment]
Had to revert the change - all solutions seem worse than leaving it as it is. WONTFIX for now
