### ISSUE TITLE
Cloze deletions not treated consistently with desktop when included as non-cloze placeholder

### ISSUE THREAD

**Issue by colin-p-hill** [ankidroid/Anki-Android#6295]
###### Reproduction Steps

1. Define a card which contains a standard placeholder, as `{{Text}}`
2. Create a note of that type with a cloze deletion in the value for that field, as `All {{c1::men}} are mortal.`
3. Study the card

###### Expected Result
I expect the field to display on the card the same way Anki for desktop does it, with the cloze deletion unprocessed, as `All {{c1::men}} are mortal.`

###### Actual Result
All cloze deletions are dropped from the card with no indication anything was elided, as `All  are mortal.`

###### Debug info
AnkiDroid Version = 2.10.2

Android Version = 10

ACRA UUID = 0c27e711-8469-4257-8884-62f1a7fd4cb1

###### Debug info (desktop version, for comparison)
    
    Anki 2.1.26 (70784154) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
    Platform: Windows 10
    Flags: frz=True ao=False sv=2
    Add-ons, last update check: 2020-05-28 10:19:00
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    
    
    ===IDs of active AnkiWeb add-ons===
    
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Notes
I recognize that people will not usually do this on purpose. However, the inconsistency can still cause problems, or at least lead to confusion. On the occasion that someone does do this on purpose (as I did), simply eliding of all clozed content is probably not ever going to be the intended result, and it is in any case a result not reproducible on desktop.

**Comment by colin-p-hill** [comment]
I understand that this is a niche problem and likely low priority. If I managed to figure out how to fix it myself, would y'all accept a pull request?

**Comment by mikehardy** [comment]
@colin-p-hill Sure! What's the proposed fix? Is this a non-cloze-type card with a cloze deletion in it? It does seem that if it is not a cloze type card we should not attempt to strip out cloze's maybe someone is trying to memorize cloze syntax!

**Comment by colin-p-hill** [comment]
@mikehardy Technically it is a cloze type card, but a custom one which sometimes uses fields without cloze processing. I haven't actually tested whether this happens with a standard card that happens to contain cloze markup.

I don't have a proposed fix just now. I don't know the codebase (or, for that matter, Android development), but the change is probably more important to me than to most users, so I may try to find time to figure it out in the future.

**Comment by colin-p-hill** [comment]
Tested with a Basic card, it does indeed do the same thing. Anki Desktop displays the unprocessed deletion tag, while Ankidroid elides them.

Looks like the issue is in the `while` loop in Template.render_tags. It causes the templates to get processed recursively -- if `{{Front}}` gets replaced with `{{foo}} {{bar}} {{baz}}`, each of those three will also be treated as placeholders, until no more placeholders are found. Testing on Anki Desktop, it doesn't exhibit this same behavior -- replacements seem to occur in a single pass.

As far as I can tell, this looping behavior is not consistent with Anki Desktop in any circumstance.

![Annotation 2020-07-18 152932](https://user-images.githubusercontent.com/66083075/87860458-9f244900-c90b-11ea-88c6-15fe86c5654c.png)
![Annotation 2020-07-18 152824](https://user-images.githubusercontent.com/66083075/87860457-9e8bb280-c90b-11ea-925b-36889291e278.png)

@mikehardy Looks like you did this on purpose with #6180. Don't suppose you remember what led to that? Looks like it related to fixing #6176. My proposed fix would be to remove the loop and replace in one pass, but I don't want to cause a regression on an issue I don't know the full background of.

**Comment by mikehardy** [comment]
Template rendering is in general a difficult area - @Arthur-Milchior spent the most time in the area, I think the PR you mention from is tangential at best, I wouldn't say I truly understand stuff. I think mostly we're working (quietly, in the background, and actually just @david-allison-1  ;-) ) on making it so we can use the newly-ported-to-Rust libanki from upstream as a library here and just call in to it, and use the "official" template rendering that way, so we're just limping along until then. I'm not sure what the best way forward is, just that in my experience in this area there will probably be a regression no matter what you do

**Comment by Arthur-Milchior** [comment]
Thank you for mentioning me.
This is the kind of error I warned about in https://github.com/ankidroid/Anki-Android/issues/6215
I'm kind of happy to see that it is not purely theoretic and that some user which are not me see the bug too. I'm a user making a lot of strange thing, I'm a contributor, I should not be taken into account...

The question here is simple: what should we do if a tag appear in a field ? I admit that I did not consider the particular case where the tag was a cloze while the note type is not close deletion, I don't think that this particular case should be taken into consideration.

The trouble is that it seems that we have users who expects to different behaviours; some user expect current anki behaviour (i.e. just show the field name and don't replace them by the field's value) and some user expect previous anki behaviour (replace the field name by the field's value). Of course, we could add a preference to allow user to decide which one to use. We could also make a third behaviour: replace a `{{fieldName}}` by its value only if "fieldName" is the name of a field.

This is not a code problem, this is only a question of knowing how we want AnkiDroid to behave in this case. The code will be simple to implement; but as far as I can tell, you raised the only question where I really disagree with the mainteneurs' choice.

**Comment by colin-p-hill** [comment]
@Arthur-Milchior I fully acknowledge that my use case is a strange one, or at least not an expected one. I have a cloze type that has a Text field and a Citation field, formatted differently in the template. Occasionally, I want to test myself on where a piece of information comes from, so I have cloze deletions in both fields. The default behavior is built with the assumption that the _only_ reason to have multiple cloze fields is to put overlapping deletions into a single note, so (in most circumstances) only one cloze field will display on a given card. I get around this by just putting both `{{Text}}` and `{{cloze:Text}}` on the card and using JS trickery to pick which one to display, replacing deletion tags with their contents if the former is displayed. In all, a tremendous hack, and certainly not something I'd expect to be supported.

So I agree, it's not a code problem. There is a problem here imo, but it's just that the implementations differ - a single note should work more or less the same way on both platforms. I don't know how y'all usually reach consensus with the maintainers of the other implementations on that sort of thing. My 2c on what implementation to favor: recursive processing makes sense, but replacing undefined tags with the empty string does not.

Which I guess brings me to another proposed fix: keep the recursion, but if no replacement is found, don't process it. A little more involved maybe - the `while` loop will need a more complex condition - but it should preserve the use cases you have in mind without ever simply throwing away data. The difference from the desktop version may still cause issues for other oddball note types than mine, though.

**Comment by Arthur-Milchior** [comment]
The usual rule is: Anki decided everything and we copy

**Comment by colin-p-hill** [comment]
That being the case, maybe the best way forward is to conform to Anki Desktop's implementation and file an upstream issue requesting this recursive behavior?

**Comment by mikehardy** [comment]
This took a while to get to - my fault - because I know this affects users negatively no matter the direction we choose and I was struggling with that. Upstream consistency will have to be the goal though, so the change (carried across a couple PRs...) was just merged and it will be in the next 2.13 alpha - thanks for pointing this out and providing the solution @colin-p-hill
