### ISSUE TITLE
Flag icon flickers during review

### ISSUE THREAD

**Issue by aampere** [ankidroid/Anki-Android#6301]
###### Reproduction Steps

1. Start review session.
2. Reveal answer to a card.
3. When you grade yourself and the next card appears, the flag icon flickers.

###### Debug info
AnkiDroid Version = 2.10.2

Android Version = 9

ACRA UUID = 39ce3acd-caf3-431f-b058-41137e3fcdae

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @aampere,

Thanks so much for the report!

This should be fixed in our latest alpha: https://docs.ankidroid.org/manual.html#betaTesting (ref: #6227).

Please feel free to reopen this if there's anything still unresolved.

Thanks for using AnkiDroid,

David
