### ISSUE TITLE
Is there better way to get values from Deck to WebView?

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#6306]
###### Reproduction Steps

I have added following codes to AnkiDroid.

[card.js](https://github.com/infinyte7/Anki-Android/blob/master/AnkiDroid/src/main/assets/scripts/card.js#L78)
<br>``` view.loadUrl ```
[AbstractFlashcardViewer.java](https://github.com/infinyte7/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L3159)

Added custom card layout using css and js to deck template.
[Anki-Custom-Card-Layout](https://github.com/infinyte7/Anki-Custom-Card-Layout)

![demo](https://github.com/infinyte7/Anki-Custom-Card-Layout/blob/master/images/demo.gif?raw=true)

###### Expected Result
Is there a better way to following values without using ```setTimeout ```.
```
Deck Title,
ETA,
New, Learn, Review Card Counts
Mark,
four button or three button is there 
```
I get values ( cards count, title, mark, eta ) but by using ```setTimeout ``` function of ```javascript```.

###### Actual Result
WebView should get values without using ``` setTimeout ```.

###### Reason
It will help in card creation with custom layout.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by infinyte7** [comment]
This is my idea. Make available all details about current card to WebView and then using css and js card can be redesigned with many possibilities. 
```card.js``` have following functions
```
showAnswer()
buttonEaseAnser1()
buttonEaseAnser2()
buttonEaseAnser3()
buttonEaseAnser4()
markCard()
CardCount()    //  have count number of new card, learn card, review card  
DeckName()   // have deck name value 
getETA()        // have value of remaining time to review the current deck
```

**Comment by infinyte7** [comment]
I have found answer using this.
https://github.com/SimonLammer/anki-persistence

Get all values to persistence value. And then use it for next. 
Following value need not to be made available using ```setTimeout```
```
ankiDeckName
total card count at from first card
total = ankiNewCard + ankiLrnCard + ankiRevCard
```

**Comment by mikehardy** [comment]
Fascinating, that's a great project! I want to tag @SimonLammer directly to say that the AnkiDroid project is thinking through what the best is to have an "officially sanctioned" card template or distribution method or similar that would bundle a few things that *any* use of advanced web technologies in the WebView would want. Persistence is such an obvious one - it's the first thing to solve.

I personally would love the wisdom of the community already working in the area
