### ISSUE TITLE
Material Design

### ISSUE THREAD

**Issue by zyIsPig** [ankidroid/Anki-Android#6320]
I think the function of anki is very helpful to me. But I think his UI design can be done better, and the functions can be more convenient. So I made my own material design, not only changed the style, but also introduced cardview to bring more traversal function. At the same time, resolve the conflict between marked and flag in cardbroswer. I want to share my own modified anki recently, I just want to give you some design inspiration, not to force everyone to like.

**Comment by zyIsPig** [comment]
<img width="400" alt="截屏2020-05-31 下午11 36 24" src="https://user-images.githubusercontent.com/48407926/83356258-8c73a600-a397-11ea-933e-5827d1445d39.png">

**Comment by zyIsPig** [comment]
<img width="333" alt="截屏2020-05-31 下午11 37 05" src="https://user-images.githubusercontent.com/48407926/83356269-a44b2a00-a397-11ea-8f75-eeb3376dbbe1.png">

**Comment by zyIsPig** [comment]
<img width="328" alt="截屏2020-05-31 下午11 37 41" src="https://user-images.githubusercontent.com/48407926/83356279-b9c05400-a397-11ea-9826-5844e94fe0b9.png">

**Comment by zyIsPig** [comment]
<img width="323" alt="截屏2020-05-31 下午11 38 33" src="https://user-images.githubusercontent.com/48407926/83356298-d9577c80-a397-11ea-88da-6ba82691bb4f.png">

**Comment by zyIsPig** [comment]
<img width="336" alt="截屏2020-05-31 下午11 39 07" src="https://user-images.githubusercontent.com/48407926/83356306-ed02e300-a397-11ea-99f1-8a990138a9ab.png">

**Comment by Michael55555** [comment]
I've been thinking about this too for a while. And I hope we'll see changes in the UI design soon.
But what do you think about lowering shadow opacity and removing cards from list view?
