### ISSUE TITLE
[Proposal] Popout "Anki Card" Share Dialog

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6323]
Google Keep has a "Share" dialog which pops over the content of the screen when clicked. This is a much nicer experience than opening the note editor to add an Anki Note.

I'd like to see the same in Anki, to reduce the friction of adding a card.

![image](https://user-images.githubusercontent.com/62114487/83363996-b62bcd80-a395-11ea-9ad0-0a6d9dbcace4.png)

We could then add an (off by default) option for "Anki Card" on the text selection menu, like "Card Browser" is currently.

**Comment by david-allison-1** [comment]
@mikehardy - Is this reasonable as a long-term proposal?

**Comment by mikehardy** [comment]
Sure, and check #5023 - in general handling any kind of clipboard data to make a new card with a nice UX would be great
