### ISSUE TITLE
Examine if Tls12SocketFactory may be removed

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6329]
It appears based on okhttp maintainer comment that the functionality in the Tls12SocketFactory to enable TLS v1.2 might be unnecessary as it is likely fully contained in okhttp

Just needs a test I believe?

https://github.com/square/okhttp/issues/4481#issuecomment-637032983

I could have sworn it did not work earlier when I was developing it but a maintainer's word is never to be taken lightly.

**Comment by mikehardy** [comment]
Relevant code link in our repo: https://github.com/ankidroid/Anki-Android/commit/47feecb9ac2e215bc56f387d043ccf9b271c032d#diff-36861f300e525ff4bc27048485a2ae3dR211

Valid test would be that it works on API16 and up

**Comment by david-allison-1** [comment]
@mikehardy OK if I take this on, or did you have plans to investigate?

**Comment by mikehardy** [comment]
No plans personally, I woke this morning with a fresh commitment to not attempt individual contributions for a little bit, to preserve bandwidth for PR review / release cycle. In my mind there are like 5 of me worth of capacity but in reality there is only .5 🤣 

This would be a quick win though if possible, I just swear I tested it and it only worked with my PR, the problem is my PR was a tangle and I'm not sure I tested "switch to okhttp without Tls12 workaround" vs "switch to okhttp with Tls12 workaround" since I snagged all that code off the internets IIRC.

**Comment by david-allison-1** [comment]
I attempted removing 

```

                ConnectionSpec cs = new ConnectionSpec.Builder(ConnectionSpec.MODERN_TLS)
                        .tlsVersions(TlsVersion.TLS_1_2)
                        .build();

                List<ConnectionSpec> specs = new ArrayList<>();
                specs.add(cs);
                specs.add(ConnectionSpec.COMPATIBLE_TLS);
                specs.add(ConnectionSpec.CLEARTEXT);

                client.connectionSpecs(specs);
```

and API 16 partially failed to sync.

**Comment by mikehardy** [comment]
Alas, the maintainer's word is worth heeding but perhaps subtle. Thank you very much for checking
I'm happy with everything going on in OkHTTP/sync land then except the download count being bogus at this point. Hasn't been a priority for me but just socializing that figuring out why my shim isn't properly clocking download amounts in the non-media phase of the sync is the only imperfection I'm aware of
