### ISSUE TITLE
Buried cards not counted as "due tomorrow" in advanced stats (inconsistent with Desktop)

### ISSUE THREAD

**Issue by boolbag** [ankidroid/Anki-Android#6331]
###### Expected Result
On Anki Desktop, the buried cards are part of the "due tomorrow" count. This makes sense because buried cards are due tomorrow.
Expecting the same in Ankidroid's Advanced statistics.

Also, I would expect Advanced Stats to compute a rolling average of the daily number of buried cards and to add that to the graph.

###### Actual Result
On Ankidroid, in the advanced stats graph, the next day's stats don't include the buried cards, so someone who buries 1-10 cards a day can't predict how many cards they'll see the next day.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Got a few advanced statistics things stacked up, with no takers at the moment, would be good to have a scrub in there, @boolbag - any interest in attempting this change, or any of the other advanced stats changes to see if you can fix them? A lot of times it's just a tiny query change or java math formula change to aggregate some extra bit of information into a sum or filter a query or similar... https://github.com/ankidroid/Anki-Android/issues?q=is%3Aissue+is%3Aopen+advanced+statistics

**Comment by boolbag** [comment]
Note to self: the stats source code seems to be [here](https://github.com/ankidroid/Anki-Android/tree/master/AnkiDroid/src/main/java/com/ichi2/anki/stats).

**Comment by david-allison-1** [comment]
@boolbag Advanced Stats is: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/libanki/stats/AdvancedStatistics.java

**Comment by boolbag** [comment]
Sorry to disappoint for now, at the moment my spare Anki time is being absorbed by tweaking my [ultimate Italian conjugation deck](http://www.asiteaboutnothing.net/w_italian-conjugation-flashcards.html) and its manual and studying a possible port to Spanish.

Regarding _buried_ status, this is probably known already, but in the Ankidroid browser the `is:buried` filter returns zero notes, when the same filter returns several notes in Anki desktop. Haven't switched to alpha yet though, maybe all that "buried" weirdness has been addressed already.

**Comment by david-allison-1** [comment]
@boolbag It hasn't been reported, but that's an easy issue to solve. Thanks! Added as #6408
