### ISSUE TITLE
Improve Cloze Deletion TTS output

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6336]
> [TTS] doesn't read anything out [on a Cloze]. So if I write:
> 
> A few lizards are venomous, eg {{c1::gila monster}}. They have {{c2::grooved teeth}} and {{c2::sublingual venom glands}}.

> On card one it will read out "A few lizards are venomous, eg. They have grooved teeth and sublingual venom glands."

> It doesn't say "blank" "deletion" or even pause for 5 seconds, so it's hard to tell where the deletion was because the sentence just doesn't make sense to listen to. I guess because it's just reading what is visible? Can you change the (...) to read out as "blank" or similar?

User reported on reddit: https://www.reddit.com/r/Anki/comments/gv67qy/option_to_have_anki_read_aloud_the_text_on_my/fsn2v3p/ . Needs verification.

**Comment by mikehardy** [comment]
Not sure how you could force TTS to pause, is something like a comma considered a "always pause for a moment" for TTS? If so just putting like `,,,` into the TTS stream might be perfect. I used to do this when coding to telephony APIs that needed pauses, might apply

**Comment by david-allison-1** [comment]
I've replaced with "blank" for now.

**Comment by mikehardy** [comment]
that is more overt, sounds good

(wait, I think that's a pun)

**Comment by david-allison-1** [comment]
To be honest, I think this one might stay in design for a little longer than I'd anticipated - not sure if we want to do something special with localisation here.

**Comment by mikehardy** [comment]
couldn't resist reading the PR, LGTM already, confirm cloze deletion already has coverage outside of TTS context (so we know it still works)? I'm 99.9% that already has coverage but your hated jacoco would tell you :) (or just knowledge of the tests of course)

**Comment by mikehardy** [comment]
up to you on timing of course

**Comment by david-allison-1** [comment]
It has human coverage

> couldn't resist reading the ~PR~branch, LGTM already, confirm cloze deletion already has coverage outside of TTS context (so we know it still works)? I'm 99.9% that already has coverage but your hated jacoco would tell you :) (or just knowledge of the tests of course)

This doesn't touch the templating engine, the code is in the HTML Template -> TTS Input synthesis stage, which was previously untested.

**Comment by mikehardy** [comment]
Human coverage on the non-touched case and auto coverage on the new case is still clearly an incremental improvement, fine by me

**Comment by KendallPark** [comment]
Hello all. When using the `<tts>` tag to only read a small selection of text, cloze `[...]` are not read as "blank."

Perhaps the `.text().replace(TemplateFilters.CLOZE_DELETION_REPLACEMENT, clozeReplacement!!))` should be applied outside of the `if` statement below?

```java
object TtsParser {
    /**
     * Returns the list of text snippets contained in the given HTML fragment that should be read
     * using the Android text-to-speech engine, together with the languages they are in.
     *
     *
     * Each returned LocalisedText object contains the text extracted from a &lt;tts&gt; element
     * whose 'service' attribute is set to 'android', and the localeCode taken from the 'voice'
     * attribute of that element. This holds unless the HTML fragment contains no such &lt;tts&gt;
     * elements; in that case the function returns a single LocalisedText object containing the
     * text extracted from the whole HTML fragment, with the localeCode set to an empty string.
     */
    @JvmStatic
    fun getTextsToRead(html: String, clozeReplacement: String?): List<TTSTag> {
        val textsToRead: MutableList<TTSTag> = ArrayList()
        val elem = Jsoup.parseBodyFragment(html).body()
        parseTtsElements(elem, textsToRead)
        if (textsToRead.isEmpty()) {
            // No <tts service="android"> elements found: return the text of the whole HTML fragment
            textsToRead.add(readWholeCard(elem.text().replace(TemplateFilters.CLOZE_DELETION_REPLACEMENT, clozeReplacement!!)))
        }
        return textsToRead
    }
```
