### ISSUE TITLE
Post-2.11 stable release F-Droid / Amazon store actions

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6339]
Referenced elsewhere but untracked, 

Now that #6268 is in and hooks are gone and we are no longer doing Dex loading and scanning, the F-Droid release build script for AnkiDroid can have an exception removed from it

This *may* (untested hypothesis) also help with Amazon publishing, once 2.11 is out and stable #5051 

Depends on 2.11 beta series and stable release

**Comment by mikehardy** [comment]
F-Droid has removed their scanner exception.
Just need to try posting this to the Amazon store now. Need response from @nicolas-raoul  on that - Nicholas! I need the amazon credentials again :pray: - not sure what happened to them but I'm not sure how to log on to the amazon store to try to upload a build anymore, none of my credentials work

**Comment by nicolas-raoul** [comment]
I just sent you an invitation :-)

**Comment by mikehardy** [comment]
I have the power! Thanks @nicolas-raoul 

```
App Submission Successful

    Your app submission is estimated to go live before 05:30 PM PDT, 16 Jun 2020.
```

We'll see how it goes :-) - that's for the 2.11.2 APK from our github releases page.

**Comment by mikehardy** [comment]
Amazon accepted the build! I'll update the release procedure docs to note that it appears possible to submit new builds to them
