### ISSUE TITLE
Improve: "AnkiDroid directory is inaccessible" error recovery

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6345]
> Haven't been on AnkiDroid for a while and decided to download it again but as soon as I get on the app I'm greeted by a screen called preferences with an alert at the bottom saying 'AnkiDroid directory is inaccessible'. I look at the current AnkiDroid directory (which I'm able to change) and it's set to /storage/26BA-0100/AnkiDroid
>
> I looked through my folders on my phone by can't find those folders. I tried creating those folders manually but that didn't work either. Does anyone know what's going on?
>
> Also as soon as I click the back button on the preferences screen the app just closes.
>
> Edit: I figured out the problem, when I used to have anki my default storage location was to my SD card so that must have been the directory it was looking for. For some reason my phone reverted back to local storage and so after changing it back to SD it started working fine

From a user report: https://www.reddit.com/r/Anki/comments/gv6n5b/ankidroid_directory_is_inaccessible/fsqdqfj/

We could handle this case better, but it's good that the user was technical and could solve the issue.

**Comment by tbop** [comment]
Hi all

I'm having the same issue here but couldn't solve it on my own like OP.
I've switched from a Samsung with an SD card to a Google Pixel that does NOT have any SD card.
The path currently set for AnkiDroit Active Directory seems to be still referring to the SD card path.

What is the default path that I should use instead so that I can be able to sync the app with my Anki account again?

Thanks!

**Comment by david-allison-1** [comment]
@tbop `/storage/emulated/0/AnkiDroid`

**Comment by tbop** [comment]
@david-allison-1 Thanks! Unfortunately I've got this path but it keeps telling me the path specified is not a valid directory. I am quite sure that the app has access to storage. I've also tried clearing the data of the app and start from scratch but same issue.

I'm on a Google Pixel XL with Android 10 https://www.gsmarena.com/google_pixel_xl-8345.php

**Comment by tbop** [comment]
Should I try to just create this folder somewhere manually from the Windows Explorer?
