### ISSUE TITLE
[low priority] Investigate: Potential data corruption on sync

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6361]
We're setting the USN of some models/decks during the syncing process to 0, but we need to determine (and comment) the behaviour that will happen on failure.

Ref: https://github.com/ankidroid/Anki-Android/blob/4276b2cdd045c68dc1cb4e59a532efe6fbf997e3/AnkiDroid/src/main/java/com/ichi2/libanki/Utils.java#L1021-L1034

> This is not handled in the code, as the code is the same as in upstream. It was not handled in upstream either. I do not know whether rust takes care of it or not, rust is too hard for me to read.

> I assume you could take a full copy of the arrays as they are before uploading them, and if the sync fails, restore the copy. However, maybe the upload suceeded and we just never received the confirmation, so the arrays are correct and reverting to previous version would actually be the bug.
I've no clue whether it ever was a problem for anyone (statistically, I assume it has been), but I've no reason to believe that it was actually an important problem

_Originally posted by @Arthur-Milchior in https://github.com/ankidroid/Anki-Android/pull/6048_

**Comment by Arthur-Milchior** [comment]
This really lack context to be understood by itself. Nothing indicates what "This" refers to.
Do you want me to explain more here ? There is little more I can state that what I added in the comment.
Anyway, I don't even see how you could force the bug to occur. You would need to be able to cut the connection at the right time to ensure that decks/note types as marked as uploaded while actually the upload did not occur.

**Comment by david-allison-1** [comment]
Got me before I added in the code context. If it can be improved further - feel free to edit the topic

**Comment by dae** [comment]
If AnkiDroid is doing the same thing as the computer version, it should not be a problem - beforeUpload() is only called in the full sync case, and if a full sync is aborted then the next sync is also a full sync.

**Comment by david-allison-1** [comment]
Thanks!
