### ISSUE TITLE
[Suggestion] GibHub - More Granular Labels

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6368]
Dealing with the stale-bot has brought up a lot of duplicates. I feel it'd be useful to add a few more tags to help find/deduplicate these. Feel free to edit this with suggestions

I also don't want us to get to the point where tagging an issue is a chore, so happy to see this rejected

https://github.com/ankidroid/Anki-Android/labels

* ~~Card Browser~~
* Home Screen (effectively the UI around the Deck Picker)
* Previewer
* ~~Multimedia Insertion~~
* Reviewer
  * Whiteboard
  * Gestures
* Maybe Rename CardAddition to `Note Editor`?
* Card Template Editor
* ~~Sync/AnkiWeb~~
* ~~Development/CI/CD (maybe keep all of these under one tag)~~
  * Travis
  * Codacy
  * Lint

----

* Preferences

**Comment by mikehardy** [comment]
Just a little more concise but not too different, if the list below (based off copy of yours then quick edit) works -> LGTM

    Card Browser
    Home Screen (effectively the UI around the Deck Picker)
    Previewer
    Multimedia
    Reviewer
    Rename CardAddition to Note Editor?
    Card Template Editor
    Sync
   Dev

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/issues/labels - done
