### ISSUE TITLE
Can't load custom fonts if data directory is on SD card

### ISSUE THREAD

**Issue by Woute** [ankidroid/Anki-Android#6373]
###### Reproduction Steps

1. Install AnkiDroid on the phone, then change the data directory location to the SD card
2. Put a ttf font file inside the collection.media directory
3. Edit notes accordingly to use the font

###### Expected Result

Desired font is used when specified in the style and template

###### Actual Result

Default font is used instead

###### Debug info

Just to make sure, I changed the location back to the internal storage (re-downloading 25k cards in the process) and without any further change, the font was properly displayed.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @Woute,

Are you using the "custom font" option in the settings? If so, the font needs to be moved up one level to be visible.

----

Otherwise, if you've supplied the font in the CSS, could you enable Javascript debugging and list the error that occurs: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

Could you also provide the card template which causes the issue. Primarily the CSS

All the best,

David

**Comment by Woute** [comment]
Hello David.

I'm using the recommended settings, as in "System default" for Default font and only apply it when no other font is specified on the card.
The CSS template is pretty standard, I've put : 

`@font-face {
  font-family: myfont;
  src: url('_kso.ttf');
}`

inside the styling part and then : 

`<span style="font-family: myfont; font-size: 60px; color: #030100;">{{expression}}</span>`

inside the template.

As I said earlier, without touching anything in the template or CSS, without changing the _kso.ttf file location either, when I moved from the SD card to the internal storage, everything worked fine instantly.

To do further testing I'm gonna need to move everything back to the SD card I guess, for now it's back to internal storage where it actually works.

But like, I don't really see how the error could come from anything but the fact storage was on the SD card. It's the only difference between behaviors.

Cheers,
Woute

**Comment by david-allison-1** [comment]
Cheers, I don't have an SD card to test, but the error is likely going to be visible in the Web Inspector: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

Once that info is available, I can do more digging.

**Comment by Woute** [comment]
I'll try to do that, for now I'm facing issues with trying to move AnkiDroid data back to the SD card. (too much data for copy I guess, and he won't try to sync even if I tell him the new location)
I'll come back when that's fixed and I have more info.

**Comment by david-allison-1** [comment]
Thanks!

**Comment by Woute** [comment]
I might give up. I have no idea what's happening anymore.
The data on my phone is all messed up.
My AnkiDroid works fine, only "issue" is that I have no idea where it's getting its data from.
I moved the AnkiDroid folder to /storage/emulated/0/AnkiDroid.back.
I told him to use the older located at /sdcard/Android/data/com.ichi2.anki/AnkiDroid.

The current state on the phone is : 
/storage/emulated/0/AnkiDroid = contains only a "backup" folder with nothing inside
/storage/emulated/0/AnkiDroid.back = contains all the data, but AnkiDroid shouldn't be able to use it since I renamed the folder, right ?
/sdcard/Android/data/com.ichi2.anki/AnkiDroid = contains all except the collection data (since I couldn't copy it, too big), it is the location specified in the AnkiDroid parameters as well, but it contains no actual data

And somehow, everything still works. Only explanation for me is it's somehow able to tell AnkiDroid.back is the folder to use. (even though I told it not to use it)

What a mess... -_-'

**Comment by david-allison-1** [comment]
Where is `/sdcard/` symlinked to on your phone? 

It's likely that `/sdcard/` actually refers to the internal storage (`/storage/emulated/0/`), would that clear up things?

**Comment by Woute** [comment]
Sadly /sdcard is the actual sdcard, I explored the path using a terminal and the files were properly on the SD card when I used USB from a Windows computer.
I'm attempting a clean install right now, deleting absolutely everything Anki related before synchronizing freshly, hopefully on the SD card...
(phone is stuck on deletion though)

**Comment by Woute** [comment]
Okay, it appears you were correct, /sdcard is the internal storage.
I have no idea how some files populated in the actual SD card when I checked it through Windows, but that's an other issue.
I'll close the ticket, the font couldn't be found since I placed it on the actual SD card.
Thanks for the help and sorry for the trouble, David.

**Comment by david-allison-1** [comment]
No worries @Woute, glad I could help
