### ISSUE TITLE
mathjax problem: \vec with a single letter inside don't work 

### ISSUE THREAD

**Issue by BlueGreenMagick** [ankidroid/Anki-Android#6374]
###### Reproduction Steps

1. Create a note with \\(\\vec{a}\\)
2. Review the card

###### Expected Result

There is an arrow above a

###### Actual Result

There is no arrow above a.

If what is inside \\vec has more than a single character however, the arrow appears.
\\vec{a} works fine on desktop Anki.
Not sure if it is an AnkiDroid problem, Android problem or a Mathjax problem.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.10.4
Android Version = 4.4.2 
ACRA UUID = 34141f01-867f-4ea4-9f19-6625973b167e

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
Sorry for the absence of answer.

We use mathjax as is. It’s in q regular web renderer. There is nothing we can do.
Did you try the same mathjax in browser on the same phone go see if it works ?
