### ISSUE TITLE
Flags don't export

### ISSUE THREAD

**Issue by beefeater7** [ankidroid/Anki-Android#6382]
###### Reproduction Steps

1. Flag some cards
2. Export the deck and delete it
3. Import it again and search -flag:0

###### Expected Result

All flagged cards show up in browser

###### Actual Result

All flags were stripped on export. 

This is verified by importing to Anki Desktop; which exports and imports flags fine, given that the cards in question are treated as new. 

Importing from AnkiDroid package yields no flags.

###### Debug info

```
AnkiDroid Version = 2.10.4

Android Version = 7.0

ACRA UUID = b3020860-b5ac-4f32-9437-a4b6fe6e6fb1
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @beefeater7, thanks for the report!

Could you provide a sample export which exhibits this problem.

You can rename the `.apkg/colpkg` to `zip` to allow it to be uploaded to GitHub.

**Comment by david-allison-1** [comment]
Relevant source. Looks like the issue is that cards don't import.

https://github.com/ankidroid/Anki-Android/blob/dbdded4ad1616ee993010ef38ca07ed74d0de1b1/AnkiDroid/src/main/java/com/ichi2/libanki/importer/Anki2Importer.java#L427-L563

**Comment by mikehardy** [comment]
cards don't import, or flags don't import? @Arthur-Milchior - you did the bulk of the flag port, do you remember doing export / import of the flag data?

**Comment by Arthur-Milchior** [comment]
I ported the same code than upstream. For some reason, anki remove flags in https://github.com/ankitects/anki/blob/master/pylib/anki/exporting.py#L198 so I believe I did the same.

**Comment by beefeater7** [comment]
@Arthur-Milchior I did some messing around with flags in the Desktop client. Updating cards' flags is not supported, so that may be what the code does? Just a wild guess. Importing to a blank slate works fine. In other words...

1. Flag card in Anki Desktop
2. Export deck to apkg and delete it
3. Import apkg back to Desktop: **Flag remains.** Delete it again
3. Import to AnkiDroid: **Flag remains.**
4. Export from Droid and delete
5. Import to Droid: **Flag is gone**
5. Import to Desktop: **Flag is gone**

Both clients will import this apkg fine. 
[Flag bug.zip](https://github.com/ankidroid/Anki-Android/files/4741227/Flag.bug.zip)

**Comment by Arthur-Milchior** [comment]
What do you mean when you say that updating card flag is not supported on desktop ? Flags are supported on desktop, and you can change them there

**Comment by mikehardy** [comment]
@Arthur-Milchior from the steps provided if you:

1. Have a flag set on Anki Desktop
1. Export the card with the flag
1. *change the flag in Anki Desktop - by say deleting it, after the export*
1. Now import it again, the flag does not get updated.

So if the flag changes post-export / pre-re-import, the import does not update the flag.

But export / import in general of flags (if you don't change them) is supported, and that seems to be the ecosystem compatibility feature gap

**Comment by Arthur-Milchior** [comment]
I even tried with older version of anki, and flags are exported. Actually, I can't even figure out whether the line I linked above is executed at any time or not. I'm lost here

**Comment by beefeater7** [comment]
Sorry about the confusion. 'Update' here means importing a flagged card into a client with other-flagged version of the card. Import to Desktop does not recognize the change of flag. I figured it may be relevant. Anyway, thanks for the fix!
