### ISSUE TITLE
In which java files & functions that replaces the value of {{Deck}}, {{Front}}, {{Type}}, {{Tags}}

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#6394]
###### Reproduction Steps
I am implemting this #4676 using this #6393. 
To get that values the ```AnkiDroidJS.``` followed by function name called. But it will be useful if that values can be accessed using
```
{{card_info:Reviews}}
{{card_info:Interval}}
{{card_info:Due}}
{{card_info:Queue}}
{{card_info:Lapses}}
```

The following info is alread available 
```
{{Deck}}
{{Type}}
{{Tags}}
{{Subdeck}}
{{Card}}
```
So, I am curious know where those have been implemented. 
 
###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Sorry! I must have forgotten to press submit, for anyone in the future: https://github.com/ankidroid/Anki-Android/blob/a493557fb56ae5c7f7285758463fae96a99c8565/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1030
