### ISSUE TITLE
Should prevent creation of {{Deck}}, {{Tags}}, {{Card}} field?

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#6395]
###### Reproduction Steps

1.  Add following fields to card template
```
Deck
Tags
Card
Type
```
2.  Add values to those fields using Note Editor
3.  Now in HTML of card
```
{{Deck}}
{{Tags}}
{{Card}}
{{Type}}
```

###### Expected Result
Should return the values in field of respective fields.

###### Actual Result
Return default values of respetive fields.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
What does Anki Desktop do here?

**Comment by infinyte7** [comment]
It doing similar things.

**Comment by david-allison-1** [comment]
Let's keep compatibility with Anki Desktop.
