### ISSUE TITLE
Remove chess css/mathjax when not needed

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6410]
We could speed up rendering by conditionally loading chess and mathjax. They're currently loaded unconditionally: 

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/assets/card_template.html

**Comment by mikehardy** [comment]
Agreed - for anyone wanting to take this on there should be some before/after numbers substantiating performance before and after any change, for each type of card (normal, chess, mathjax) to make sure it actually has an effect vs just (for example) complicating the code while the WebView has cached things somehow making it unimportant anyway
