### ISSUE TITLE
Automatically remove non-existent fields from card templates when set through content provider

### ISSUE THREAD

**Issue by hanpingchinese** [ankidroid/Anki-Android#6414]
In AnkiDroid, when a field is removed from a note type, all the references to that field are automatically removed from the card templates (e.g. {{MYFIELD}} is removed).

However, if I use the [contentprovider to set the card templates](https://ankidroid.org/apidoc/index.html?com/ichi2/anki/FlashCardsContract.CardTemplate.html), no such check is made, resulting in card templates containing potential invalid fields (and so no longer working on ankiweb following their recent stricter standards on templates).

It would be good if the contentprovider checks for fields referenced in the templates and removes those fields not in the note type.

**Comment by david-allison-1** [comment]
@hanpingchinese Do you consider this to be a high-priority issue to get fixed?

**Comment by hanpingchinese** [comment]
Hi David - it would be nice to have this, since such templates are guaranteed to break the review system on ankiweb (and presumably AnkiDroid at a later date when the strictness is applied?). Of course, I could also apply a fix at my end (and will) but this won't help users who don't (or won't want to) update their app.

**Comment by hanpingchinese** [comment]
Out of interest what is the regex for finding such fields? At the moment I have:

`\{\{[#/]?(?:text\:)?MYFIELD\}\}`

**Comment by david-allison-1** [comment]
Wasn't aware of the downstream impact. Thanks for the clarification @hanpingchinese . Will get on it.

Just a friendly pre-warning that the code's under GPL/AGPL, you'll probably want to check with dae that he's fine with the usage. We're using the following:

hxxps://github.com/ankitects/anki/commit/643ec35449f3cb85667d409ccf90a0bad22e0940

For clarity: It needs to handle multiple opening, closing, and conditionals on the same line.

**Comment by david-allison-1** [comment]
Downstream doesn't appear to have this functionality as-of 2.1.26. 

There's going to be issues with removing invalid templates on existing notes - (for example, hooks on the Desktop can specify new fields).

Adding a new template allows us more leeway, will need to give this more thought

**Comment by hanpingchinese** [comment]
Thanks for your kind words Mike. I agree with everything you say there. But then again I don't understand the implication of desktop hooks (mentioned by David), so there is that to consider too perhaps.

Yes, that's my app using the api (and also I have a [Cantonese variant](https://play.google.com/store/apps/details?id=com.embermitre.hanping.cantodict.app.pro) using the same code). My contribution was primarily with [building version 2 of the API](https://github.com/marcardar/Anki-Android/commit/7d110c5367cabbb93538a95395da099b8eab2689#diff-2965cfa9f7eaed767d9dbbf838848567) back in 2016. However, in my apps I don't actually use (and never did!) the client code I wrote, but rather access the ContentProvider directly.
