### ISSUE TITLE
Improve translation unit tests regarding PREVIOUS_LANGUAGES

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6420]
I intend to take this on myself, just moving to an issue so it's not forgotten

Note to self: This should have required PREVIOUS_LANGUAGES to change as well.

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/6413_

**Comment by mrudultora** [comment]
If you are not working on it, would explain me some more details ? I would try to solve this.

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/069e37d37d0d14aec944f5106aaf251e5f701528/AnkiDroid/src/test/java/com/ichi2/utils/LanguageUtilsTest.java

```java
    @Test
    public void testCurrentLanguagesHaveNotChanged() {
        List<String> actual = asList(LanguageUtil.APP_LANGUAGES);
        assertThat("Languages have been updated, please modify test variables: " +
                "PREVIOUS_LANGUAGES and CURRENT_LANGUAGES", actual, contains(CURRENT_LANGUAGES));
    }
```

In the linked PR, only `CURRENT_LANGUAGES` was changed, we need a mechanism to ensure that if `CURRENT_LANGUAGES` is changed, then `PREVIOUS_LANGUAGES` is changed.

I think this would just do with better commenting, rather than a test - thought over a few designs now, and I don't like any of them

**Comment by mrudultora** [comment]
A comment like this.... ?
```
/* If the changes are done in CURRENT_LANGUAGES the same changes should also be done in PREVIOUS_LANGUAGES*/
```
I will follow here, either comment or test. Test seems a good option to me.

**Comment by david-allison-1** [comment]
If you can come up with  sensible test design, then it'd be great. If not, comment and call it a day. 

It's bulletproofing our translations when a new language is added, will be useful on a failure, but not the most likely thing to occur.

**Comment by mrudultora** [comment]
Currently, there is difference in the length of arrays of `PREVIOUS_LANGUAGES` and `CURRENT_LANGUAGES` but as you told above, I think they must be of same lengths. Am I heading in right direction ?
Is the unit test written below correct ? 
```
    @Test
    public void currentLanguagesEqualsPreviousLanguages() {
        List<String> previousLanguages = Arrays.asList(PREVIOUS_LANGUAGES);
        List<String> currentLanguages = Arrays.asList(CURRENT_LANGUAGES);
        for (int i = 0; i < currentLanguages.size(); i++) {
            assertThat(currentLanguages.get(i), is(previousLanguages.get(i)));
        }
    }
```

**Comment by david-allison-1** [comment]
* `CURRENT_LANGUAGES` exists to inform the user that the tests need to be manually looked at if a language is added to the app
* `PREVIOUS_LANGUAGES` is the previous value of `CURRENT_LANGUAGES` and exists to ensure that languages are not accidentally removed from the app without good reason.

**Comment by david-allison-1** [comment]
I've added comments, and will remove the tests if they continue to cause more noise than signal
