### ISSUE TITLE
Cloning a model then syncing results in a model that only exists on the AnkiDroid device

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#6422]
###### Reproduction Steps

1. Manage note types
2. Add note type 
3. clone an existing note type (adding one of the default models is not affected by this)
4. sync

###### Expected Result
Newly cloned model will uploaded to ankiweb on sync

###### Actual Result
New model exists only on the Android device it was created on. Syncing another device will not 'pull' the model. Forcing a full sync and selecting download on the creation device results in loss of the new model.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.12alpha3

Android Version = 7.0

ACRA UUID = 0f431910-fac3-4b52-ba37-64f328e5d239

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
It's caused by a `usn` difference (usn is cloned, rather than reset). Haven't tracked down how it worked in the Anki Desktop source code.

**Comment by dae** [comment]
Please let us know if the issue still exists after updating to 2.17 (alpha may become available in a few weeks)
