### ISSUE TITLE
Duplicate entry is added without warning when adding a new note

### ISSUE THREAD

**Issue by Konstantin-Glukhov** [ankidroid/Anki-Android#6424]
###### Reproduction Steps

1. Tap on "Add a note"
2. Fill in information
3. Tap "Save" mark
A new note is added
4. Tap "Save" mark again
The same note is added

###### Expected Result

After tapping "Save" mark
"Add a note" screen should close
or
After tapping "Save" mark twice a warning should pop-up that the card is already in the deck.

###### Actual Result

Duplicate notes are added

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Anthropos888** [comment]
I can't reproduce it. After filling in front and back in the "add note" screen, a tap on the save icon in the top right saves the note and empties the fields. Pressing the tick save again brings up the message "error saving note" because the fields are empty. Filling in the same contents for the front as before will mark the field red, because Ankidroid recognizes it as duplicate. You can save it anyway without warning, but that's the same behavior as in Anki desktop.

**Comment by david-allison-1** [comment]
Hi @Konstantin-Glukhov, could you fill in the debug information section of the report, I'm primarily interested in the version of AnkiDroid that you're using.

Thanks,

David

**Comment by Konstantin-Glukhov** [comment]
My problem is that tapping the "save" mark does not clear fields. It does highlight main entry in red, but for people who do not know what it means, or forget what it means, or just don't pay attention to the color change, this behavior is meaningless. There should be a pop-up warning about the duplicate!

One enhancement is definitely due: prevent duplicates in the same deck. Decks should not allow duplicates.

Here is my debug Info from the device:

AnkiDroid Version = 2.11.1
Android Version = 8.1.0
ACRA UUID = 9d20dd21-7d72-4214-8ed9-e39144c3ea95

**Comment by sudomain** [comment]
This sounds like two distinct issues:
> My problem is that tapping the "save" mark does not clear fields.
It does for fields that don't have the "remember last input" setting enabled. This can be toggled by going to manage note types -> selecting a field -> tapping 'remember last input when adding'

> There should be a pop-up warning about the duplicate!
Personally I'm not opposed, but this proposed behavior would differ from desktop, which allows adding of duplicates with only the red field warning.

> prevent duplicates in the same deck. Decks should not allow duplicates.
Currently duplicate checking happens at the note type level for both Anki and AnkiDroid. Imo this shoild not change

**Comment by Konstantin-Glukhov** [comment]
Android interface already differs from PC one. The pop-up duplicate warning could be optional and configurable via settings. Highlighting duplicate entry as a warning is not intuitive even for technical people. It took me a while to figure out that I kept adding duplicate entries by hitting "save" icon.

**Comment by Konstantin-Glukhov** [comment]
The warning message should be added to the interface. This feature should be optional and configurable via settings.
