### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#6428]
###### Reproduction Steps

1. checkout master and pull from this repo latest version
2. Run ./gradlew clean jacocoTestReport

###### Expected Result
tests validated

###### Actual Result
As show in attached file

With -v I get

>  -----------------------------------------------------------
> Gradle 6.4.1
> ------------------------------------------------------------
> 
> Build time:   2020-05-15 19:43:40 UTC
> Revision:     1a04183c502614b5c80e33d603074e0b4a2777c5
> 
> Kotlin:       1.3.71
> Groovy:       2.5.10
> Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
> JVM:          13.0.3 (Private Build 13.0.3+3-Ubuntu-1ubuntu2)
> OS:           Linux 5.4.0-33-generic amd64
[gradlew.txt](https://github.com/ankidroid/Anki-Android/files/4760891/gradlew.txt)

**Comment by mikehardy** [comment]
I'll look into that again, I've not tried JDK14 in a long time and we don't actually run the unit tests against them, we only run the connected tests. Perhaps the unit tests still have a problem?

It's a very flexible system though as you can see. If you search stackoverflow for setting the JDK used by gradle it might be illuminating, most likely there's something wrong with your JAVA_HOME or PATH settings in your linux shell init

**Comment by dae** [comment]
@Arthur-Milchior are you doing the following? https://github.com/ankidroid/Anki-Android/pull/5888#issuecomment-607155653

**Comment by Arthur-Milchior** [comment]
I just tried when you put the link. I don't have folder "/Applications/Android\ Studio.app/Contents/jre/jdk/Contents/Home"
In the Android folder, I don't see any Contents folder.

**Comment by dae** [comment]
That is for a Mac. Presumably the Linux version bundles a JRE somewhere as well?

**Comment by mikehardy** [comment]
If you're running Unix I have to make some assumptions about your experience in setting environment variables and installing software - there's a billion ways to do it for unix but if you're using unix you must have some ways you use. 

I have a pile of JVMs for instance (installed manually and via apt) and I have a variety of ways I initialize my environment. But an example directory structure and an example of ways to switch jDKs is like so

```
mike@isabela:~/work/Kullki/ksocialscore (rebranding *) % a|grep jdk
alias jdk11='export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64 && export PATH=$JAVA_HOME/bin:$PATH'
alias jdk7='export JAVA_HOME=/usr/lib/jvm/jdk1.7.0_80 && export PATH=$JAVA_HOME/bin:$PATH'
alias jdk8='export JAVA_HOME=/usr/lib/jvm/java-8-oracle && export PATH=$JAVA_HOME/bin:$PATH'
mike@isabela:~/work/Kullki/ksocialscore (rebranding *) % ls -lat /usr/lib/jvm/
total 48
drwxr-xr-x 163 root root    12288 May 28 14:14 ../
drwxr-xr-x   7 root root     4096 Apr 26 08:10 ./
drwxr-xr-x   9 root root     4096 Apr 26 08:10 java-11-openjdk-amd64/
drwxr-xr-x   2 root root     4096 Apr 26 08:10 openjdk-11/
drwxr-xr-x   7 root root     4096 Apr 26 08:10 java-8-openjdk-amd64/
-rw-r--r--   1 root root     2044 Apr 16 07:54 .java-1.11.0-openjdk-amd64.jinfo
-rw-r--r--   1 root root     2712 Apr 16 03:47 .java-1.8.0-openjdk-amd64.jinfo
lrwxrwxrwx   1 root root       20 Apr 17  2019 default-java -> java-8-openjdk-amd64/
-rw-r--r--   1 root root     2643 Jan 17  2019 .java-8-oracle.jinfo
drwxr-xr-x   7 root root     4096 Jan 17  2019 java-8-oracle/
lrwxrwxrwx   1 root root       20 Apr 26  2018 java-1.8.0-openjdk-amd64 -> java-8-openjdk-amd64/
lrwxrwxrwx   1 root root       21 Apr 21  2018 java-1.11.0-openjdk-amd64 -> java-11-openjdk-amd64/
drwxr-xr-x   8 uucp tcpdump  4096 Apr 10  2015 jdk1.7.0_80/
```

So, install JDK8

```
mike@isabela:~/work/Kullki/ksocialscore (rebranding *) % apt list | grep installed | grep jdk

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

openjdk-11-jdk-headless/focal,now 11.0.7+10-3ubuntu1 amd64 [installed,automatic]
openjdk-11-jdk/focal,now 11.0.7+10-3ubuntu1 amd64 [installed]
openjdk-11-jre-headless/focal,now 11.0.7+10-3ubuntu1 amd64 [installed,automatic]
openjdk-11-jre/focal,now 11.0.7+10-3ubuntu1 amd64 [installed,automatic]
openjdk-8-jdk-headless/focal,now 8u252-b09-1ubuntu1 amd64 [installed,automatic]
openjdk-8-jdk/focal,now 8u252-b09-1ubuntu1 amd64 [installed]
openjdk-8-jre-headless/focal,now 8u252-b09-1ubuntu1 amd64 [installed,automatic]
openjdk-8-jre/focal,now 8u252-b09-1ubuntu1 amd64 [installed,automatic]
```

...find where it is installed, and set your JAVA_HOME to it

**Comment by mikehardy** [comment]
@dae you may like this, I have a script I call "doctor.sh" that I use to converge the development environments of my UI colleagues so I don't get support requests, here's the JDK chunk for mac, it also takes care of Xcode+rvm+ruby+brew so that brew exists...


```bash
# Check java install status
JDK_VERSION="8"
echo "Verifying installed Java Development Kit is openjdk$JDK_VERSION"
JAVA_VERSION=`java -fullversion 2>&1`
if [ "$?" != "0" ] || [[ "$JAVA_VERSION" != *"openjdk full version \"1.8.0"* ]]; then
  echo "Java package should be adoptopenjdk$JDK_VERSION but java version was $JAVA_VERSION"

  if [ "$(uname)" == "Darwin" ]; then
    echo "Installing openjdk$JDK_VERSION via brew on macOS"
    brew untap adoptopenjdk/openjdk
    brew cleanup
    brew tap AdoptOpenJDK/openjdk
    brew cask install adoptopenjdk$JDK_VERSION
    echo "# --- Add JAVA_HOME items" >> $HOME/.bash_profile
    echo "JAVA_HOME=/Library/Java/JavaVirtualMachines/adoptopenjdk-$JDK_VERSION.jdk/Contents/Home
" >> $HOME/.bash_profile
    echo "export JAVA_HOME" >> $HOME/.bash_profile
    echo "PATH=\$JAVA_HOME/bin:\$PATH" >> $HOME/.bash_profile
    echo "export PATH" >> $HOME/.bash_profile
    echo "# --- End add JAVA_HOME items" >> $HOME/.bash_profile
    echo "!!! You will need to start a new Terminal session for $JDK_VERSION to be in effect."
  else
    echo "You appear to not have openjdk full version 1.8.0 installed, but it is required. Cannot
 proceed"
    exit 1
  fi
fi
```

[doctor.sh.txt](https://github.com/ankidroid/Anki-Android/files/4761912/doctor.sh.txt)
