### ISSUE TITLE
Syncing error, type: 404, message:

### ISSUE THREAD

**Issue by kalehmann** [ankidroid/Anki-Android#6436]
###### Reproduction Steps

1.  I use [ankicommunity/anki-sync-server][ankisyncserver]
2.  I set the urls of my sync server in the app under **Settings** -> **Advanced** -> **Custom sync server** 
3.  I tap the sync button on the main activity

###### Expected Result

Synchronization success

###### Actual Result

I get the message _"Syncing error, type: 404, message:"_

###### Debug info

My media sync url has a slash (`/`) at the end. Therefore a POST request to `https://my.sync.server/msync//begin` is made. That request fails because of the duplicated slash (`/`).

Relevant log entry of the sync server:

> [2020-06-11 19:57:22,347]:INFO:ankisyncd.http:172.24.0.1 "POST /msync//begin HTTP/1.0" 404 52 

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))
    - I have confirmed, that the issue does occur with the current master

I will provide a merge request by myself soon.

  [ankisyncserver]: https://github.com/ankicommunity/anki-sync-server

**Comment by mikehardy** [comment]
Have you tried it without the trailing slash?

**Comment by kalehmann** [comment]
Yes and it works without the trailings slash.

However this should not be a problem. Therefore I filled [a pull request](https://github.com/ankidroid/Anki-Android/pull/6437)

**Comment by mikehardy** [comment]
Okay, but as mentioned in that PR, it's a valid URL, so I disagree and think the server should handle it, per RFC for URIs

**Comment by kalehmann** [comment]
I disagree with you. Take [this answer on stackoverflow][so-answer] as reference which explains the dangers of a double slash.

  [so-answer]: https://stackoverflow.com/a/20524044/9926383
