### ISSUE TITLE
Improve messages before and while checking database

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [ankidroid/Anki-Android#6442]
Using Anki 2.11.1.

When starting "Datenbank überprüfen" (check database) Anki gives me some creepy messages.

1. 
"It can take a while." -> It does not! Maybe because my deck is only 16 MB. Please check the factores influencing the duration of a database check. e.g. if it is the deck size. Check the deck size first -> if it is to big, give the users the warning message. If not. Don't bother the user with a message which is useless for her/him.

2.
Next message is about required free space. It should be 2,1 MB (not GB!) free space for a database check. Nice! Check the size yourself. If there is not enough free space give a message. It makes no sense before.

3.
The current free space is displayed in that message. This is good! But it is displayed in Bytes (B). Make it human readable please.

**Comment by david-allison-1** [comment]
Relevant code:

https://github.com/ankidroid/Anki-Android/blob/955de44f996a2eac1d0610f51a51336486c3a786/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L250

https://github.com/ankidroid/Anki-Android/blob/10c2be16778230a8850d0af065a0fd532987fd2a/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L1386-L1403

I've had a look through and it looks correct visually. I'll do another scan later on

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
What I see is

> Aktuell sind - 1659551744,00 B frei.

Android Storage Settings tells me that there is "2,45 GB" free space.
There is no SD-card in the device - only in-build-memory.

**Comment by david-allison-1** [comment]
@Codeberg-AsGithubAlternative-buhtz What region/locale is your phone using (Settings - System - Language & Input - Language & Region), and have you specified any custom formatters?

Relevant code is: 

https://github.com/ankidroid/Anki-Android/blob/955de44f996a2eac1d0610f51a51336486c3a786/AnkiDroid/src/main/java/com/ichi2/anki/CollectionHelper.java#L336-L340

It would be useful to have a screenshot of the message(s) so we can investigate further.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
In the AndroidSettings...
Language ("Sprache"): "Deutsch (Deutschland)"
No custom formatters - do not know how to do this.

The device:
Old Samsung Galaxy (S2 or S3 I think): "GT-I18190"
Android-Version: "4.1.2"
Kernel: "3.031-1332988 se.infra@SEP-110 #2 SMP PREEMPT Sun Jul 28 14:54:47 KST 2013"
Buildnumber: "JZO54K.I8190XXAMG4"

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
![shot_2020-06-15_13-35-10](https://user-images.githubusercontent.com/11861496/84653245-5a248580-af0d-11ea-928a-08a215530863.png)

**Comment by david-allison-1** [comment]
@Codeberg-AsGithubAlternative-buhtz That's really helpful, thank you. I've coded up a fix, and it should hopefully be in our next alpha build.

It was caused by your phone using a different method of reporting free space compared to newer phones.

My fix should also resolve your other issue: #6441

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Can confirm this is fixed in 2.11.2 from today. Thanks a lot!
Have not checked the current alpha because it seams fixed in the current stable also.
