### ISSUE TITLE
Add count of selected notes / warning when deleting multiple notes

### ISSUE THREAD

**Issue by dymky** [ankidroid/Anki-Android#6444]
Sorry, I am not sure whether this is the right place to post a request.

Please add a warning when multiple cards are deleted in the multi-select regime.

###### Reproduction Steps

1. Have several cards.
2. Go to the browser, select several notes and choose "delete".

###### Expected Result

I'd like to see a warning of deleting several cards.

###### Actual Result

No warning.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I could see that, yes. Just a quick note to you before you get too far along - you can restore from backup quite easily if you've lost a bunch of data. Deck picker options has the restore from backup option and their are date-stamped, usually one auto-backup a day is taken so you might have luck there depending on your own personal tradeoffs w.r.t. what changes you've made and what the backup will have in it. You can take a backup before you try, as well

**Comment by dymky** [comment]
Thank you!

That did not happen to me yet, but every time I delete a card I feel uncomfortable as there may be something selected by accident somewhere down in the list…

By the way (sorry for abusing the format, but this is really a tiny addition to the original request), <b>could you display a counter of the currently selected entries in the multi-selection regime?</b> That would be another way to address the same inconvenience.

**Comment by david-allison-1** [comment]
The count of selected cards is already in the action bar at the top of the screen. 

It would be sensible to change the snackbar (dialog) to **N notes deleted** rather than **Notes deleted**

**Comment by dymky** [comment]
You are right, the counter is there, sorry! It could be that I got used to the interface before it was added, or just missed it somehow!

Then the only thing I can say here is that deleting many notes at once still feels "too easy". This may be just ignored, or you might change the confirmation to something like "N notes have been deleted".

**By the way²**.
If memory serves, at some point there was a discrepancy between "notes" and "views" (I hope I adhere to your terminology here): say, if just one browser entry corresponding to a node with two ways of displaying (thus appearing twice in the browser) was selected and deleted, then the reversed card was still somehow present in the system (or something along those lines, I am not sure). Now everything works as expected: deleting just one "view" produced by a node deletes the whole node. I think, this might be worth an additional warning: namely, that **as a result of the requested delete action some views that are not being selected will be removed**.

**Comment by david-allison-1** [comment]
We use whatever terminology Anki uses for the most part.

A note is what you edit.

A note with the cloze note type generates 1 to many cards.

Cards are what you review, and what you see in the browser. 

I'll have a think. I think that's a good enough reason to add a warning. It's hard to explain, and unintuitive.

**Comment by david-allison-1** [comment]
Fixed: Added a dialog stating the number of cards deleted in #7329

A user can undo the operation if this number is not what is expected.
