### ISSUE TITLE
Is there a way to mark a card good/bad via JavaScript?

### ISSUE THREAD

**Issue by danZ4C** [ankidroid/Anki-Android#6445]
I am creating a custom quiz interface with multiple answer buttons.

Is there any way to mark a card good/bad via Javascript on ankidroid?

So if I click a correct html <button> it will automatically mark the current card and then displays the next one? Or if I press an incorrect button, it will mark the card wrong.

Thank you!

**Comment by david-allison-1** [comment]
Hi @danZ4C 👋  

Pretty sure we've just talked on Discord. 

https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/assets/scripts/card.js contains our functionality. Grep for `showAnswer`

https://github.com/ankidroid/Anki-Android/pulls/infinyte7 will also be interesting for you.

Feel free to reopen if you need anything else

All the best,

David
