### ISSUE TITLE
Anki Forums

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#6449]
Hi all,

It's looking highly likely at this point that Anki will be moving away from TenderApp in favour of a new forum system at https://forums.ankiweb.net/. The new site has a nicer interface, and allows the active community members to contribute more: https://blog.discourse.org/2018/06/understanding-discourse-trust-levels/

AnkiDroid is welcome to join the forum as well if you're interested. Discourse allows you to watch particular categories, so it should be possible to monitor AnkiDroid-related posts while ignoring the rest of the forum should you desire. Like GitHub, it is possible to reference people by @name, so it would make it easier for developers to ping each other in the case of cross-platform issues. And I can grant Mike and David moderator status so you can manage the AnkiDroid side of things autonomously. 

Would you like me to create an AnkiDroid category to start with? If someone is monitoring it, then you could run it in parallel for now on a trial basis, and make a decision at a later date as to whether you wanted to continue with Google Groups or not.

**Comment by david-allison-1** [comment]
I'm doing support on reddit right now. Personally happy to take on the support for the subforum as well, but best to confirm with @mikehardy that he's happy with the arrangement. Account: https://forums.ankiweb.net/u/david/summary

The main advantage for the Google Group right now is that it's our developer contact at the Play Store and allows people to put in support requests and have them answered by volunteers with pretty much 0 friction. 

Mike deals with the spam right now (I assume there's a lot). I assume for it to be viable to move, there'd need to be a way for e-mail based submission and reply without signup. and an ability to gate posts from new/unverified e-mails for approval before they're visible.

**Comment by dae** [comment]
The forum supports email replies to threads, but is not configured for starting new topics via email. I guess Google require an email address and don't support a HTTPS link as a contact address?

**Comment by mikehardy** [comment]
I'm a little concerned on community fragmentation. One of the best ways to kill a community is to move it, most of them never recover. We already have a google group, discord, and github and reddit. I want to keep all real work in github. I want a zero-friction (anonymous ok) entry point for users (that's google group for us), and beyond that I don't care about platform. So I think it's possible (and probably a positive thing) to have an AnkiDroid forum in there but I personally would steer people as much as possible to github - it would be more of a "stub" for me so that people don't get lost in handoff but I wouldn't direct people there if that makes sense?

**Comment by timrae** [comment]
I have always tried to encourage bug reports and feature requests to be
submitted to GitHub, but questions and discussions to go on Google groups.
If you had every single zero research "How come my picture isn't showing
up?" coming into GitHub, it starts to wear developers down and makes it
much harder to find actual issues.

I don't really have an opinion on Google groups vs Anki forum, they both
seem to have advantages and disadvantages, I agree that you'd need to add
support for email thread creation though, as Google Play does require an
actual email address not just a URL. That could just be implemented as a
bot that emailed back a link to the user to start a new thread and get them
to copy paste the text in, but yeah that does add friction.

**Comment by dae** [comment]
Ok, let's forget about replacing anything for now.

TenderApp had a AnkiDroid section that was not open to posting, with a description directing people to the Google Groups forum. It was fairly common for AnkiDroid users to post in the AnkiMobile section instead (often without even stating that they were using AnkiDroid), and that meant I had to reply to them pointing them to the correct site, and they had to repost their question there.

If I set up an AnkiDroid section on the new forum and someone is monitoring it, it will mean those users don't have to repost their questions, and I won't need to spend time redirecting people. It needn't be the official place - you could pin a topic asking people to post elsewhere if you wanted, though some users will invariably ignore it and post anyway.

Please let me know what you'd like me to do - I don't want to create a category if it's not what AD wants.

**Comment by mikehardy** [comment]
I do like the idea of having the category at least, and we can watch it, at minimum to prevent a bad user experience as you mention. Continuing to point them to the google groups / email is probably a good first step with bonus points if there was a link to the FAQ and AnkiDroid manual, and a link to the FAQ and then a FAQ link.

**Comment by dae** [comment]
Ok, I've added https://forums.ankiweb.net/t/about-the-ankidroid-category/177/2 to start. @david-allison-1 , your login should now have the ability to edit posts, move them, etc, so please feel free to adjust that post as required. If you want I can change the owner too - it will appear as being posted by you instead if that's done.

**Comment by mikehardy** [comment]
Thanks @dae - I'm also tracking that forum now as @MikeHardy / anki@mikehardy.net - cheers

**Comment by dae** [comment]
Updated your account too
