### ISSUE TITLE
sync_up_down_size uses incorrect units

### ISSUE THREAD

**Issue by gaul** [ankidroid/Anki-Android#6456]
AnkiDroid displays kB, not KB.  The former is 1000 while the latter is 1024.  `DeckPicker.onProgressUpdate` divides by 1024.  You can fix this via:

```
find -name 04-network.xml | xargs sed -i -e 's/\<kB\>/KB/g' -e 's/\<kb\>/KB/g'
```

###### Reproduction Steps

1. Synchronize deck
2. 
3. 

###### Expected Result

Display in binary Kilobytes (1024)

###### Actual Result

Displays in SI kilobytes (1000)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Propose the PR and capture the internet points :1st_place_medal:   :rofl:

**Comment by gaul** [comment]
Unfortunately my employer requires hoop-jumping to contribute to an AGPL licensed project.

**Comment by adamwolf** [comment]
Thanks for taking it as far as you did!

**Comment by mikehardy** [comment]
Haha totally understand. In my capacity as someone on the internet I hereby grant you all the associated internet points for this solution anyway. Thanks!
