### ISSUE TITLE
[Suggestion] CI/GitHub action to reject merge commits

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6459]
A simple regex-based checker such as https://github.com/marketplace/actions/gs-commit-message-checker might be all we need to catch 99% of cases.

**Comment by mikehardy** [comment]
Yes, and also to make sure first line isn't too long, but what happens on a reject? The commit is already in there? Then we have some hand-holding to do? Not sure what this does to novice contribution experience and I am willing to squash merge while people learn

**Comment by david-allison-1** [comment]
> Yes, and also to make sure first line isn't too long, but what happens on a reject? The commit is already in there? Then we have some hand-holding to do? Not sure what this does to novice contribution experience and I am willing to squash merge while people learn

I'd envision it to be a check - similar to how Travis/Codacy works.
