### ISSUE TITLE
CardTemplatePreviewer, Previewer, Reviewer handle newlines differently

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6460]
###### Reproduction Steps

1. Open a note (with newlines I suspect) in NoteEditor
2. Hit the Preview button (opens CardTemplatePreviewer)
3. Compare with result of reviewing the same card

###### Expected Result

Newlines handled the same

###### Actual Result

Newlines handled differently?

This is reported from https://github.com/ankidroid/Anki-Android/pull/6063#issuecomment-643788306

Needs investigation

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Related: #3304
