### ISSUE TITLE
Faulty playback of short audio files

### ISSUE THREAD

**Issue by d3rped** [ankidroid/Anki-Android#6461]
###### Reproduction Steps

1. Create a note including a (?short?) sound element/audio file 
2. Open that card.

###### Expected Result
Audio should be played back properly.

###### Actual Result
Audio starts with a plopping sound.
This mostly happens with short audio files (mostly one syllable words (originally generated through TTS)).
I've attached an example file (and a recording of how it sounds when I play it from AnkiDroid).
[audio.zip](https://github.com/ankidroid/Anki-Android/files/4777203/audio.zip)

###### Debug info
AnkiDroid Version = 2.11.3beta1

Android Version = 5.1

ACRA UUID = 62564edb-654f-4e55-b509-775d1da465ec

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Just as a note about possible inability to solve: all the audio reproduction issues we've had in the past were down to the specific device / android combination and were not able to be fixed. If you can maybe confirm this on some other device (ideally a newer one like Android 8 or up to be representative of our user base) that would help us
