### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by dristi11** [ankidroid/Anki-Android#6465]
AnkiDroid Version = 2.11.2

Android Version = 10

ACRA UUID = 75398f73-f20a-4b02-9049-87942123381d

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I see no reports with that ACRA UUID
There is no description at all of the issue, steps to reproduce, examples of data etc.
Without any information to go on, we can't help, sorry
