### ISSUE TITLE
App becoming brighter than darker when studying with a physical keyboard

### ISSUE THREAD

**Issue by DavidsonTwo** [ankidroid/Anki-Android#6479]
###### Reproduction Steps

1. Connect a physical keyboard on my phone
2. Start studying with it

###### Expected Result
Work normally

###### Actual Result
The screen become brighter then darker every time I hit the spacebar

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @DavidsonTwo, thanks for the report.

This caused by Android displaying the currently selected element when using a keyboard (so you know what space/enter will press).

What behaviour would you like to see instead?

**Comment by mikehardy** [comment]
#5819 duplicate I think

**Comment by david-allison-1** [comment]
Assumed it got closed off by the stale bot. Closing as duplicate.
