### ISSUE TITLE
Cloze "type answer" training doesn't give possibility to type answer for all cards on AndkiDroid

### ISSUE THREAD

**Issue by k-slava** [ankidroid/Anki-Android#6482]
It's my first experience in creating Cloze Type of Anki Cards, so I might create some bad route of using it. I double-checked everything and didn't find mistakes in my setup, but maybe I did something wrong, sorry if so.

The idea is to have several sentences in one card and learn some places from these sentences. I set up everything on Windows Client. On Windows Client, it works, but on Android Client, it doesn't give me the possibility to type an answer for some cards (couldn't find the pattern when it happens).

I have checked issues with the "cloze" word in it but didn't find the same issue. For example, I can have only one cloze field in the card: `This is an {{c1:: example}} for my issue`. And my problem appears in this example. Nobody reported it (or I didn't find such issue).

###### Reproduction Steps
**1. Change Cloze card type in Anki Windows**
**Font template:**
```
<div class="cardtag"><em>{{Tags}}<br><br></em></div>
{{cloze:Text}}
<br><br>
<div class="clozetype">{{type:cloze:Text}}</div>
<br>
<div class="clozeextra">{{Extra}}</div>
```
**Styling:**
```
.card {
 font-family: arial;
 font-size: 13px;
 text-align: left;
 color: black;
 background-color: white;
}

.cloze {
 font-size: 18px; 
 font-weight: bold;
 color: blue;
}
.nightMode .cloze {
 color: #00ff00;
}

.cardtag {font-size: 10px; color: #00ff00; text-align: center}
.clozetype {font-size: 18px; font-weight: bold; color:black; text-align: center}
.clozeextra {font-size: 10px; color: lightblue; text-align: center}
```
**Back template:**
```
<div class="cardtag"><em>{{Tags}}<br><br></em></div>
{{cloze:Text}}
<br><br>
<div class="clozetype">{{type:cloze:Text}}</div>
<br>
<div class="clozeextra">{{Extra}}</div>
```

**2. Create Cloze card in Anki Windows**
`{{c1::There is an example}} of strange behaviour {{c2::of AnkiDroid}} {{c3::with cloze cards}} type. `

**3. Check Cloze card in Anki Windows**
You have three cards (c1, c2, c3), and in each card, you can type your answer.

**4. Check Cloze card in AnkiDroid**
You have three cards (c1, c2, c3), and **only in "c1"** card, you can type your answer. Other cards have the only button "See answer," without typing field.

###### Expected Result
AnkiDroid works as AnkiWindows on step three above.

###### Actual Result
It seems to me that AnkiDroid, for some reason, doesn't work with the cloze field if you want to type an answer.

###### Debug info
AnkiDroid Version = 2.11.2
Android Version = 9
ACRA UUID = 83557596-3d11-4b9d-bd2c-0e763b1e7a25

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by k-slava** [comment]
UPD: Now, I met a card, not at the beginning of the sentence, and it worked properly. Now I don't know the pattern, sorry. Just many cards don't give me a field to type answers.

**Comment by mikehardy** [comment]
well, we are listening :-), sounds a bit frustrating but if you can come up with something reproducible we'll certainly have a look

**Comment by k-slava** [comment]
> well, we are listening :-), sounds a bit frustrating but if you can come up with something reproducible we'll certainly have a look

Maybe I can save a deck with those cards, and you have a glance? I can't recognize the pattern.

**Comment by mikehardy** [comment]
That would be ideal once we had a set of reproduction steps but we have pretty limited time and need to rely on you for the scenario or we could spend lots of time and have no results with all the other work on the app halted for the different focus

**Comment by k-slava** [comment]
> That would be ideal once we had a set of reproduction steps but we have pretty limited time and need to rely on you for the scenario or we could spend lots of time and have no results with all the other work on the app halted for the different focus

But it would be speedy. Download my Deck - start to use it; the first or second card will show you a problem. I was wrong about the cards that work well. But about cards that don't work, I wasn't wrong. Some of them I can type, some of them don't give me the possibility to type answers. Sorry to disturb you. Of course, I see how many open issues you have, sorry for adding another one.

I don't know, what can I do else to help in solving this problem. If I can help somehow, just say me, I will be happy to help.

In case you decide to have a glance at this problem I added deck where you can find the problem and some screenshots to illustrate it.

### Card where I can type the answer
![image](https://user-images.githubusercontent.com/32261191/85173820-c3ddc000-b27c-11ea-91e0-3b5e1746477a.png)

### Card where I can't type the answer
![image](https://user-images.githubusercontent.com/32261191/85173845-d22bdc00-b27c-11ea-8b4d-f36d1b32d050.png)

### Deck for testing
[issue_6482.zip](https://github.com/ankidroid/Anki-Android/files/4806419/issue_6482.zip)

If anything I could do, don't hesitate to ask me, I will be glad to help.

**Comment by k-slava** [comment]
I can close this issue with a recommendation not to create more than one "cloze" field per card. If necessary, it's better to clone the card. This setup works on any platform.
