### ISSUE TITLE
Manually added audio files to collections.media don't get synced

### ISSUE THREAD

**Issue by Rapptz** [ankidroid/Anki-Android#6485]
###### Reproduction Steps

1. Save a file to the AnkiDroid collections.media folder
2. Sync on mobile
3. Observe that media changes are not found
4. Sync on desktop

###### Expected Result

Media files are synced when you go to desktop.

###### Actual Result

Media files are not synced.

###### Debug info

AnkiDroid Version = 2.11.2

Android Version = 8.0.0

ACRA UUID = f6428dac-543c-4882-8903-f7504679743c

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Info

I have an app that generates card using the ContentProvider API. This API works well for me except for the fact that I can't manually add audio. An issue was posted a while ago that got closed to provide for this functionality (https://github.com/ankidroid/Anki-Android/issues/5139). To work around this issue I started adding audio to the `collections.media` folder. On the desktop version of Anki when you manually add cards to the collections.media folder and sync, the new files are synced to AnkiWeb. I figured that the same would happen with AnkiDroid.

I suspect the bug here is that new changes in the filesystem aren't actually being seen. This was hinted in a comment in the previous issue [here](https://github.com/ankidroid/Anki-Android/issues/5139#issuecomment-443972208). 

Note that the audio does play within AnkiDroid so I don't think it's a problem with the actual audio files.

**Comment by KieranBrannigan** [comment]
I have been working on something like this so I will link my pull request here. #6641

**Comment by Rapptz** [comment]
This issue still persists.

**Comment by mikehardy** [comment]
Indeed - the PR that provides a real API for it is nearly ready #6641 - in the meantime the workaround is to run a media check after adding files, they should sync after that

**Comment by Rapptz** [comment]
I've noticed that the Instant add-on API hasn't had a version bump in gradle in 3 years or so. Would it be possible to bump it? Certain URIs are inaccessible without it, for example the newly merged `FlashCardsContract.AnkiMedia`. It could be hardcoded but I think bumping the version might have better developer QoL. I wasn't sure if I should open a new issue for this since it's kind of a follow up to this one.

**Comment by mikehardy** [comment]
Mmm :thinking:  "a version bump", what exactly do you mean? There are quite a few versions in there, and I bump them all the time https://github.com/ankidroid/Anki-Android/blob/master/api/build.gradle plus a "bump in gradle" means (to me) the android gradle plugin used and/or gradle distribution used, which are both current stable last I checked

**Comment by Rapptz** [comment]
> Mmm thinking "a version bump", what exactly do you mean?

The version for that has been [1.1.0alpha6 for at least ~2 years](https://github.com/ankidroid/Anki-Android/commit/ef4993232da138b014a4f21e5cd8f6c026ae95a4) so I can't seem to get a more updated version of the package using gradle. It could also be possible that I'm missing something though, android development is more of a side thing for me.

**Comment by mikehardy** [comment]
Ah! I see what you mean. That's kind of comical actually.
Honestly, it shouldn't be alpha, it should just be 1.1.0, if you want to PR that I'll happily merge

I'm not even sure if it's release-able in it's current state, by which I mean specifically the build.gradle / maven release machinery, I'm not sure that all works still as it clearly hasn't been used in forever. Probably rusted up pretty good but only one way to find out, and that would be to actually bump version and release it

**Comment by dae** [comment]
Should be handled by the new backend (if you can even add the files manually anymore, due to scoped storage issues)
