### ISSUE TITLE
Cloze deletion popup does not seem to work on Xiaomi

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6494]
###### Reproduction Steps

1. Use a Xiaomi device
2. Highlight text in the edit note screen on cloze type note
3. Look for the cloze deletion entry on the text popup

###### Expected Result

Cloze deletion option exists in the popup

###### Actual Result

No ability to add a cloze deletion

###### Debug info

User reports (lots of them!) on google play store. It appears we have finally narrowed it to Xiaomi (at least Redmi Note 8) devices.

###### Research

Perhaps the absolutely awful Xiaomi API support and broken power management features are to blame https://dontkillmyapp.com/xiaomi - I asked a user to try mitigation but they did not report conclusive results - I don't have a Xiaomi to try because who would be a broken Android implementation?

Perhaps the ability to do cloze deletion could be duplicated in the paperclip menu so it doesn't rely on system APIs that Xiaomi cripples?

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
https://stackoverflow.com/questions/46339084/actionmodecallback-does-not-work

https://stackoverflow.com/questions/45165150/devices-with-android-miui-and-setcustomselectionactionmodecallback

**Comment by mikehardy** [comment]
I hate Xiaomi. They are a big ol' pain in my other projects too. And totally unresponsive about it. :shrug:  I'll look at this later today I've been communicating with users about it, should be able to "extra-cloze-deletion-code-that-exists" and have it available via paperclip without too much pain? hopefully not famous last words
