### ISSUE TITLE
"Copy note" destination is parent deck, not sub-deck

### ISSUE THREAD

**Issue by RadioStudy** [ankidroid/Anki-Android#6507]
###### Reproduction Steps

1. Open Ankidroid (on Google Pixel 2), opens in "Decks" view.
2. Select desired sub-deck.
3. Go to "Card Browser" - sub-deck name and number of cards shown is displayed, as well as cards.
4. Find desired card, quick tap to enter "Edit note" (should be "Edit card"?) mode.
5. Tap "three dots on right", and select "Copy note" (should be "Copy card"?).
6. Edit note (card?) content, tap the "tick mark" to save.  This returns to "Card Browser", where the sub-deck name and the number of cards shown in 3. above is still shown, not that number plus one.

###### Expected Result
New note (card?) is placed in same sub-deck from which its source note (card?) resides in.

###### Actual Result
New note (card?) is placed in the parent deck of the sub-deck from which its source note (card?) resides in.  Now have to select parent deck in Card browser, and look through 450+ cards to find new card, long tap that card, select "three dots", tap "Change deck", and this moves the note (card) to the desired deck.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @RadioStudy,

Thanks for the report, I've proposed a fix, should hopefully be able to get this into 2.12.0.

All the best,

David
