### ISSUE TITLE
Switch of terminology in the card browser for clarity

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#6519]
Resposting from the Discord aince I should've made a GH issue to begin with:

> Would a small PR get accepted if it only changed the names of two columns of the cardbrowser? Currently users can have the right column show `Changed` and `Edited` times. I was able to find that `Changed` refers to a card modification time and `Edited` is note modification time. This would differ from desktop, but would increase clarity. I'm thinking `Card Modified` and `Note Modified` instead

I also brought up this recommendation for desktop Anki and I'm waiting to hear back.

**Comment by Arthur-Milchior** [comment]
Can you share the link to your recommendation upstram please ? I see no PR related to this idea.

As I told on discord, I'm highly in favor of it

**Comment by sudomain** [comment]
I did a PM on the Anki tenderapp forums. I didn't know if it was appropriate to submit a PR without prior discussion with the maintainer.

**Comment by Arthur-Milchior** [comment]
Sorry, I asked my request badly. I wanted the link to the forum thread. Anything that would help me see DAE's answer. I didn't know it was a PM, I imagined it would be a public message.

I have usually directly send PR, unless they  are big complex change. I have never seen anyone staying it's impolite. At worse, I was told I lost my time

**Comment by sudomain** [comment]
[PR I made for desktop](https://github.com/ankitects/anki/pull/674)
