### ISSUE TITLE
Reminder performance issue on app start

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#6524]
###### Reproduction Steps

1. install current master
2. open ankidroid
3. have a reminder set for a deck (preferably with a lot of subdecks), at any time

###### Expected Result
Being able to use ankidroid.

###### Actual Result
Ankidroid suddenly becomes extremely slow. The profiler state that the ReminderService.onReceive is always getting called in main. There is litterally no time where it is not called. The worse part is that it does not uses background process to compute the number of crads, so it just keeps using all of the UI process and every other actions takes seconds to react.

However, I keep getting, every minute, a message telling me I should review my deck (but only when ankidroid is open, which defeats the purpose)

###### Debug info
I tried on v2.11.3 and there is no such problem.

This commit is not an ancestor of current commit, so I can't just bisect. I'll try to figure out more latter if required. Currently, I'll just leave you the message, hoping anyone of you know what changed recently which could have created this error.

As a side note, I can deactivating the reminder does not solve the problem. The Reminder service keeps running on main.

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

No, sorry, I've not read it again

- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

Neither

- [ ] I have searched for similar existing issues here and on the user forum

Only on bug report list. 

- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

I tested master instead of alpha

**Comment by bsudhanva** [comment]
+1

**Comment by mikehardy** [comment]
@bsudhanva please just add a reaction to the issue, the +1 generates notifications + emails etc, but yes this is an issue, affects me too

**Comment by david-allison-1** [comment]
This only seems to occur for me if I have the widget on my home screen. Is this the case for you @Arthur-Milchior?

**Comment by mikehardy** [comment]
I have the widget enabled. It does not happen on my device (I thought it did as I noted above, but I have a different reminder problem, not an infinite loop, and I don't see excessive battery drain), so we may need a collection to reproduce.

**Comment by david-allison-1** [comment]
My experience: Maybe I haven't reproduced this. But for me, this isn't an infinite loop, but this is extremely inefficient code executed on the UI thread.

* Deck Reminders are specified per options group.
* Each deck in this options group has a separate reminder scheduled
* Each reminder needs to rebuild the deck tree, which is a slow operation

https://github.com/ankidroid/Anki-Android/blob/cbfcf359b4162f4591e32df47326fcb3947984b6/AnkiDroid/src/main/java/com/ichi2/anki/services/BootService.java#L91


https://github.com/ankidroid/Anki-Android/blob/c6c92a0585e5c0ba567424cb112e81e7a98302e5/AnkiDroid/src/main/java/com/ichi2/anki/services/ReminderService.java#L115

The basic test to see if this is infinite is to add the following lines to `ReminderService::onReceive` and see if the same ID is printed twice.

```java
        Timber.d("onReceive: %d", intent.getLongExtra("EXTRA_DECK_ID", -1));
        if (intent.hasExtra("EXTRA_DECK_ID")) {
            return;
        }
```

**Comment by Arthur-Milchior** [comment]
You can get my collection on https://milchior.fr/anki/Milchior.apkg

**Comment by Arthur-Milchior** [comment]
I am totally willing to admit that I was wrong and that it is not infinite. I saw multiple call. Did not realize it was one call by deck (of this specific type)

**Comment by david-allison-1** [comment]
Okay, now we're halfway, I feel we should brainstorm a strategic fix for 2.12. I suppose we have three avenues for optimisation:

* Perform reminders per deck options group rather than per-deck
* Perform a pre-cache operation on the `deckDueList()` on startup
* Move to a background thread (painful with `BroadcastReceiver` - seems to be a 10 second timeout).

My vote would be to investigate [WorkManager](https://developer.android.com/topic/libraries/architecture/workmanager) and see if we can move our alarms based system to this.

**Comment by Arthur-Milchior** [comment]
What I don't understand is why this runs when ankidroid starts. I would expect the reminder to makes sens only when ankidroid is closed. Furthermore, on start-up, we already have the tree computed in the deck picker, so we don't even need to pre-cache it on startup, the values are already here
I guess that "per deck option" would clearly makes things easier. In particular because it would necessarily reduce the number of call. 
I doubt 10 seconds would be enough when there are a lot of decks

**Comment by mikehardy** [comment]
Seems like the boot receiver should actually just inspect the preferences and deck conf to see if any notifications are enabled, and if they are then schedule a wakeup via AlarmManager for the times requested, deferring actual calculation

Then when processing AlarmManager intents, it could use WorkManager to enqueue the calculation and notification post

I believe WorkManager is the future, I think it is all but required if you are to have a receiver that does long-running work, though I think long-running is 30s, calculating deck due is still potentially unbounded mathematically

Right now I think the service/receiver code is re-used sometimes in the UI context and not just solely as an Intent receiver, as I believe it's called from the app startup path

There's a request somewhere for the notifications to update (resulting in a kind of countdown on cards due) while people are reviewing, but perhaps a better way to keep app state / notification state in sync without being bothersome is to have the app clean all notifications when it starts or foregrounds (using lifecycle listener), and then have an option to re-post the notification(s) quietly (no sound, no vibration) if the app stops or backgrounds (using lifecycle listener, and a fresh call to the WorkManager job that creates the notifications)

That's a big re-shape of the notifications area but should be in discrete re-usable chunks at least

Not sure why I hadn't thought of it before but that is actually the solution (if we want to implement it) to "sync on close", at least in the form of "sync when the app goes in the background", where in response to app lifecycle (a different API) listener being called telling us we are no longer foreground we can enqueue a WorkManager job to sync

**Comment by david-allison-1** [comment]
> What I don't understand is why this runs when ankidroid starts. I would expect the reminder to makes sens only when ankidroid is closed. Furthermore, on start-up, we already have the tree computed in the deck picker, so we don't even need to pre-cache it on startup, the values are already here

AnkiDroid normally starts the boot service when Android boots up. 

Installing is a special case which triggers this path. We hit it very often because we're devs.

The "reminder time" is set for "current day + hours set in the reminder". By default this is 00:00, so we've passed the time for a reminder, and perform a check.

Now, we could schedule the first check as T+1 if the time has passed, so the reminder won't be triggered on boot/startup by default, but we want to ask ourselves what the intended functionality should be. 

If my phone was off, and missed a reminder, it should probably be shown. Doing this is possible, but more complex than expected due to the international date line, clock drift, etc..

**Comment by Arthur-Milchior** [comment]
Makes perfect sens. Of course, if there is a bug related to installation only, reinstalling plenty of time won't solve it... 
At this point, I'll just remove reminders, which will allow me to update to master on my phone

**Comment by mikehardy** [comment]
I believe this is resolved enough for 2.12, notifications can obviously use a bunch more iterations but good enough for now

**Comment by Arthur-Milchior** [comment]
That's right for me. Seems it makes the first start slower by half a minute, but only dev' doit often, so I guess that's okay

**Comment by david-allison-1** [comment]
Half a minute is excessive - let's fix it once we've abstracted out the counting

**Comment by Arthur-Milchior** [comment]
I don't get your point. In order to know whether reminder should be sent or not, we actually need the counting. Without counting, we can't check whether there are cards to review.
What can be removed that would help is:
* don't load models, as they are not required here (mostly a problem for me since I've big models)
* using rust code

Or simply not even sending those reminders if ankidroid is already opened, because anyway, ankidroid is running on the screen so the user probably already reviewing

**Comment by david-allison-1** [comment]
> I don't get your point. In order to know whether reminder should be sent or not, we actually need the counting. Without counting, we can't check whether there are cards to review.
> What can be removed that would help is:
> 
> * don't load models, as they are not required here (mostly a problem for me since I've big models)
> * using rust code
> 
> Or simply not even sending those reminders if ankidroid is already opened, because anyway, ankidroid is running on the screen so the user probably already reviewing

* `deckDueList` is ridiculously inefficient, turn `_newForDeck` and the like into a `group by`-> cache and it'll soar.
* Wouldn't recommend, but even more computations could be offloaded via event sourcing.

**Comment by Arthur-Milchior** [comment]
I assume that you are referring to the method `deckDueList` and not the new class. If so, I totally agree with you, and this method was entirely rewritten in rust. This is why I mentioned rust.
I could port it to java, that would not be extremely hard, but probably useless. 
Clearly, computing the real tree, then propagating limit from parent to child and propagating number of cards from child to parent will be quite simpler, especially if all numbers are obtained through a single query instead of a lot of small queries.

I didn't know "event sourcing"; in this case, a quick search on the web does not really help me understand how it would help. In particular since normally this reminder runs while AnkiDroid is closed, so there should be no event recently
