### ISSUE TITLE
CI: Use Travis workspaces to speed up build

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6532]
Travis has a beta feature: workspaces which act as a per-job cache: https://docs.travis-ci.com/user/using-workspaces

This is really useful, as it means we only need to build the APK once, before for the instrumentation stage. This will shave off a significant amount of time for the build (probably around 30 minutes total time, 6 minutes real time). 

I'd started this: `https://github.com/ankidroid/Anki-Android/compare/master...david-allison-1:improve-travis#files_bucket` (Pardon my commit names, and hacky changes)

the problem with the above is the lines:

```
  - adb shell mkdir -p /data/local/tmp/
  - adb push ${APK_CACHE_FILE} /data/local/tmp/com.ichi2.anki.apk
  - adb shell pm install -r "/data/local/tmp/com.ichi2.anki.apk"

  - adb push ${APK_TEST_CACHE_FILE} /data/local/tmp/com.ichi2.anki.tests.apk
  - adb shell pm install -r "/data/local/tmp/com.ichi2.anki.tests.apk"
  # This was previously defined in build.gradle - FIXME: Parse that file. TODO: Use correct runner - couldn't get it working.
  - adb shell am instrument -w com.ichi2.anki.tests/androidx.test.runner.MultiDexJUnitRunner
```

Currently, this:
* Does not handle the test results
* Does not use the correct test runner
* Does not relay test failures back to Travis.
* Does not work on API 28 (each API has different folders which you can push an APK from).

Instead of this code, we should hook into gradle, and provide a task which will use the existing infrastructure to push an APK to the device and instrument it, without it needing to go through the initial build stages.

This has sat on my TODO list for a while, and I haven't investigated yet. I don't expect that it will be too hard.

**Comment by mikehardy** [comment]
Naively it seems that AnkiDroid/build/outputs/apk/ could be the workspace path - does it work for a directory tree? - and then a gradle task can just have it's dependsOn list clipped off so it's just the installation and test-with-coverage run

If it can't take a directory tree, then a tar-gz could be done, workspace-put/workspace-get, expand

Same could be done .gradle/caches perhaps and then you wouldn't need to change gradle build machinery at all, just do the "warm" step (assembleDebug and assembleAndroidTestDebug I think?) and put those in to the workspace.

**Comment by david-allison-1** [comment]
That all sounds reasonable. I still need to get more familiar with gradle internals so I can't say definitively

**Comment by david-allison-1** [comment]
And, more familiar I am:

`gradlew AnkiDroid:jacocoAndroidTestReport -x packageDebugAndroidTest -x packageDebug` works as long as the `apk`s are in the

**Comment by david-allison-1** [comment]
For anyone googling, `output-metadata.json` (or `output.json` for older version of gradle) is also required in the output directory or this error occurs.

```
gradlew AnkiDroid:jacocoAndroidTestReport -x packageDebugAndroidTest -x packageDebug

 > : No compatible devices connected.[TestRunner] FAILED 
Found 1 connected device(s), 0 of which were compatible.
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':AnkiDroid:connectedDebugAndroidTest'.
> There were failing tests. See the report at: file:///home/travis/build/david-allison-1/Anki-Android/AnkiDroid/build/reports/androidTests/connected/index.html
* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
* Get more help at https://help.gradle.org
```
