### ISSUE TITLE
Alter diff-match-patch dependency to supported one (minSdk >= 24)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6537]
Our current diff utility (for type answer feature) hasn't received any attention and I think the community moved on:

https://github.com/ankidroid/Anki-Android/blob/5d81aee0bd1f388fc16a59820946addc074a8b81/AnkiDroid/build.gradle#L227

The current locus of development appears to be:

https://github.com/java-diff-utils/java-diff-utils

Might be as easy as just swapping the dependency and it works

**Comment by mikehardy** [comment]
Here's the previous related PR where I swapped a copied implementation we had for an external dep: #5129 if it's useful reference

**Comment by mikehardy** [comment]
Unfortunately that library requires API24 as it uses some java language features we can't make work on older APIs, so reopening this until our minSdkVersion matches because I ahd to revert the PR.

**Comment by pree-T** [comment]
May i work on this?

**Comment by mikehardy** [comment]
No - our minSdkVersion is still 21 - you can see in `AnkiDroid/build.gradle` - this is just a placeholder for the time when we move up to 24 and can use a better dependency. It will have to wait until then, might be a year or two...

**Comment by dae** [comment]
Perhaps relevant: https://github.com/ankitects/anki/issues/1068

**Comment by dae** [comment]
Fixed by the switch to the new backend.
