### ISSUE TITLE
Missing scheduling information in deck overview with scheduler V2

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#6562]
###### Reproduction Steps

1. enable V2 scheduler
2. review a deck with new cards and finish the deck down to 0
3. go to deck overview by pressing the three numbers right to the deck name

###### Expected Result

I can see useful information about the learning cards that will be due later today, as in V1 scheduler:

![Screenshot_20200626-233600](https://user-images.githubusercontent.com/45192213/85903693-42030f00-b807-11ea-9853-f2d0cd440eb1.png)

###### Actual Result

I only see useless information that doesn't help me to figure out how many cards are still due later today:

![Screenshot_20200626-233723](https://user-images.githubusercontent.com/45192213/85903749-6c54cc80-b807-11ea-915a-fa41aa2c7276.png)

Unfortunately Anki Desktop removed the useful information from V1 scheduler in V2, too. But at least I can see when and how many cards are still to come:

![anki](https://user-images.githubusercontent.com/45192213/85903919-c81f5580-b807-11ea-8641-daaa0f337c0c.png)

At least this should be shown in Ankidroid as well.

###### Debug info
AnkiDroid Version = 2.12alpha17

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Worth noting that this screen is very rarely accessed on phones, it shows up in the split screen view that is available by default in landscape on tablets though. The tap on the numbers in deck list is the only way to see this on phones and I'd be surprised if more than a handful of people even knew it existed...

**Comment by Anthropos888** [comment]
I still think that it's a valuable piece of information in Anki desktop and should be copied to the deck overview in Ankidroid.

**Comment by david-allison-1** [comment]
This is fairly trivial, but I'll block this on the Rust conversion to save duplicated effort.

`CongratsInfo` in rust: https://github.com/ankitects/anki/commit/e5685254c67da2e5bd1822437992706d2d01eb7f#diff-ad0dcffdf701a0711096c6d383ad6cd5R98

**Comment by mikehardy** [comment]
Note for future people: AnkiDroid is migrating statistics and  libanki (which includes the scheduler) to a new style of use where instead of porting the original Python to Java, we are wrapping the Rust library that AnkiDesktop uses now. Resolution of this issue will require understanding the upstream issue in their Rust code (for scheduler/libanki) or upstream code in svelte/CSS, and fixing it there. PRs to AnkiDroid's java implementation of libanki or stats are not the desired fix at the moment unless they are extremely well-understood and targeted at fixing a small specific issue while the transition happens

**Comment by dae** [comment]
Closed by switch to new backend.
