### ISSUE TITLE
Add "send exception report right now" button on getting help screen

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6565]
In the getting help screen we should have a "send exception report right now" button that clears any ACRALimiter clamping and does a broader logcat sweep. If users encounter random problems in the app and we have Timber categorizing correctly, we'll get traces which would help a lot for recoverable errors

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/6543#issuecomment-650782199_

**Comment by david-allison-1** [comment]
We may want a basic text entry (probably numeric) to ensure that bots don't clog up our logs.

**Comment by mikehardy** [comment]
great point - or just disable it if it's a bot similar to test crash disable #6488

**Comment by mikehardy** [comment]
just enough of a bump to keep you open for a little bit, I want to do this but not time yet

**Comment by david-allison-1** [comment]
I'll be doing this as part of the Help Section revamp in 2.14

**Comment by ritvij14** [comment]
I would like to work on this. I see a PR already merged for this though, so we need to make more additions?

**Comment by david-allison-1** [comment]
@ritvij14 I'd added the help screen, but not the button/functionality in this PR

Relevant code to add this to the UI would be: 

https://github.com/ankidroid/Anki-Android/blob/1ef55b00b426e263637baafbb6ec9f3743391e00/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java#L52-L77

This can be seen by pressing "Help" in the app.

Please also consider the following comment: https://github.com/ankidroid/Anki-Android/issues/6565#issuecomment-650797003  and consider that UI automation/bots may be accessing this functionality, and how to ensure that they don't submit massive volumes of requests.

An additional useful task would be to add some unique data to the exception report which states that it was manually created, and by which version. If we do get a spam problem on a specific version of AnkiDroid, this would allow us to filter out the reports before they hit our ACRA database.

**Comment by ritvij14** [comment]
@david-allison-1 alright got it. Also, thanks for sending the code. I will get started on this and any doubts I will ask them directly on discord.

**Comment by david-allison-1** [comment]
Just to note: ACRA is set up in `AnkiDroidApp` (the entry point to the app):

https://github.com/ankidroid/Anki-Android/blob/24443a327ed060dc31f4c16c88a3553d50d7ad05/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L127

**Comment by mikehardy** [comment]
How to test ACRA-related things: https://github.com/ankidroid/Anki-Android/wiki/Crash-Reports#developing--testing-acra-functionality
