### ISSUE TITLE
Flag on new Anki card corrupts database in Ankidroid

### ISSUE THREAD

**Issue by DavidSum47** [ankidroid/Anki-Android#6588]
###### Reproduction Steps

1. Create a new card in desktop Anki
2. Open browser and add a flag to the new card
3. Sync the database to Ankiweb
4. Sync the database from Ankiweb to AnkiDroid

###### Expected Result
The new card should appear in the AnkiDroid browser, and should be accounted for in the number of new cards shown next to the relevant deck name in the main deck list.

###### Actual Result
The new card does not appear at all in AnkiDroid.  Furthermore, either on the initial sync, or on the next sync, AnkiDroid reports a corrupted database.

###### Debug info
AnkiDroid Version = 2.11.3

Android Version = 9

ACRA UUID = 9f12830e-740b-4b23-b550-a43a0a6666b8

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @DavidSum47 

There are no crash reports under that UUID. Could you ensure that crash reporting is enabled (Settings - AnkiDroid - Send Error Reports).

Could you then send us a corrupt Anki collection so we can figure out the issue:

* Create a card with a flag in Anki Desktop (which should cause an issue in AnkiDroid if you sync)
* Close Anki Desktop
* Send the `collection.anki2` file to us ([File Locations](https://docs.ankiweb.net/#/files?id=file-locations)). 
  * Either via here (change the filename to `collection.zip` and upload it), 
  * Or to me privately (gmail: davidallisongithub) if you don't want to post your Anki data (cards, review history) publicly online.

All the best,

David

**Comment by DavidSum47** [comment]
My AnkiDroid is already set to send crash reports.  However, this issue does not produce a crash: it triggers a warning that the database is corrupt.  This sometimes happens on first syncing the deck with AnkiDroid, as I previously reported.  However, on other occasions Ankidroid has accepted the database, but does not show any new card that was flagged in Anki.  On the next attempted sync, it then reports that the database is corrupt.

If the new cards have already been reviewed even once in Anki Desktop, then AnkiDroid will happily accept the database and show the flagged cards.

As my collection is extremely large, I tested this with a brand new collection, which contained only 2 cards, both new, and 1 of them flagged.  The syncing worked normally in this case, and AnkiDroid showed both new cards.

I cannot upload my existing collection.anki2 file, because it is well over the 10MB limit.  To try to get around this problem, I backed it up and then made a copy of it.  I then removed all of the decks but one and all of the cards except for 2 new ones (one of them flagged).  But the size of the resulting file was still enormous, and too large to upload.

I have no Anki Desktop addons.

David

**Comment by david-allison-1** [comment]
> If the new cards have already been reviewed even once in Anki Desktop, then AnkiDroid will happily accept the database and show the flagged cards.
> 
> As my collection is extremely large, I tested this with a brand new collection, which contained only 2 cards, both new, and 1 of them flagged. The syncing worked normally in this case, and AnkiDroid showed both new cards.

Hi David, feel free to send your entire collection to the email I provided.

I'd like to get to the bottom of this if it's a corruption bug, even if triggered by Anki Desktop. Deck corruption should prompt to send an error report

**Comment by DavidSum47** [comment]
Hi David

I doubted that my file would send, although it got a good way along before it failed.  It is rather more than 50Mb in size.

When I deleted all but one of the folders and all but 2 cards, it was still 49.9Mb.  Clearly the "rebuild database" option in Anki Desktop does not remove much obsolete data.

David

**Comment by david-allison-1** [comment]
Hi David... 50MB for `collection.anki2` is astounding, are you sure you're not exporting and including media.

We don't need a media export to diagnose this.

But... regardless of the size, feel free to upload your whole collection (without media) to a free cloud storage provider (mega/google drive) and send me a link either here or via my gmail: davidallisongithub

**Comment by DavidSum47** [comment]
Sorry - I'm not trying to be unhelpful!  The file I tried to upload was collection.anki2 (renamed).  The media (of which there are a lot) are in collection.media/ .  Are they also stored in the database?  I don't know.

Sorry I hadn't thought of using cloud storage - pretty stupid of me!  The file is here:
https://drive.google.com/drive/folders/10LWrGf0ZHwVOj8W4JTwat2HAXnXwPL2E?usp=sharing

David

**Comment by david-allison-1** [comment]
Cheers! Requested access. Legitimately the biggest `collection.anki2` I've ever heard of! Thanks

**Comment by david-allison-1** [comment]
@DavidSum47 - does that collection include a corrupt flag? I could use it with no problem on AnkiDroid

**Comment by DavidSum47** [comment]
Yes, it does.  It should show 2 new cards in the "Active" deck.  My Anki only shows one, and in the browser the flagged one does not show up.

**Comment by david-allison-1** [comment]
@DavidSum47 - let me do more testing, both of those appear in my AnkiDroid with no problem

**Comment by david-allison-1** [comment]
@DavidSum47 I can't reproduce this at all. I'm at a loss. Sorry.

Are you technically inclined? It'd be useful to get a logcat from Anki: https://developer.android.com/studio/command-line/logcat

This tool is also built into Android Studio, and the UI is much more usable - just turn developer mode & USB Debugging on your phone and you csn copy out the relevant logs.

**Comment by mikehardy** [comment]
Note the problem report is vs AnkiDroid 2.11.3, perhaps it is already fixed, should use latest alpha for testing: https://github.com/ankidroid/Anki-Android/releases

Also Anki desktop version is not specified and they are moving fast, could be sensitive to that version as well

**Comment by david-allison-1** [comment]
I've been testing on AnkiDroid 2.11.3, so Anki Desktop version changes, or phone-specific issues are the only thing that come to mind.

**Comment by DavidSum47** [comment]
After downloading AndroidStudio and a lot of messing about (!!) I managed to get a logcat from AnkiDroid.  On this occasion I had added 2 notes (type: Basic), to one of which I then added a flag.  When I tried to sync this to AnkiDroid (via AnkiWeb), it would not accept it, saying that the database was corrupt.  The logcat (verbose) is here:

2020-07-01 11:09:17.662 12764-12764/? I/AnkiDroid: DeckPicker:: Sync button pressed
2020-07-01 11:09:17.713 12764-23295/? I/AnkiDroid: Begin openCollection: /sdcard/AnkiDroid/collection.anki2
2020-07-01 11:09:17.750 12764-23295/? I/AnkiDroid: End openCollection: /sdcard/AnkiDroid/collection.anki2
2020-07-01 11:09:17.751 12764-23295/? I/AnkiDroid: Sync - starting sync
2020-07-01 11:09:17.955 12764-23295/? I/AnkiDroid: Sync: getting meta data from server
2020-07-01 11:09:17.958 12764-23295/? I/AnkiDroid: Sync: building local meta data
2020-07-01 11:09:18.815 12764-23295/? I/AnkiDroid: Sync: collection removed data
2020-07-01 11:09:18.816 12764-23295/? I/AnkiDroid: Sync: sending and receiving removed data
2020-07-01 11:09:18.924 12764-23295/? I/AnkiDroid: Sync: applying removed data
2020-07-01 11:09:18.933 12764-23295/? I/AnkiDroid: Sync: collection small changes
2020-07-01 11:09:18.934 12764-23295/? I/AnkiDroid: Sync: sending and receiving small changes
2020-07-01 11:09:19.033 12764-23295/? I/AnkiDroid: Sync: merging small changes
2020-07-01 11:09:19.034 12764-23295/? I/AnkiDroid: Sync: downloading chunked data
2020-07-01 11:09:19.133 12764-23295/? I/AnkiDroid: Sync: applying chunked data
2020-07-01 11:09:19.150 12764-23295/? I/AnkiDroid: Sync: collecting chunked data
2020-07-01 11:09:19.156 12764-23295/? I/AnkiDroid: Sync: sending chunked data
2020-07-01 11:09:19.359 12764-23295/? E/AnkiDroid: Syncer/ Sync - SanityCheck: there are notes without cards
2020-07-01 11:09:19.507 12764-23295/? I/AnkiDroid: flush - Saving information to DB...
2020-07-01 11:09:19.514 12764-23295/? I/AnkiDroid: flush - Saving information to DB...
2020-07-01 11:09:19.526 12764-23295/? I/AnkiDroid: Sync Finished - Closing Collection
2020-07-01 11:09:19.529 12764-23295/? I/AnkiDroid: Collection closed

David

**Comment by david-allison-1** [comment]
Hi @DavidSum47, thanks so much!

Could you perform "Deck Picker - Check Database" on your AnkiDroid collection and see if that fixes things.

If it doesn't, could you also upload the `collection.anki2` from your phone.

All the best,

David

**Comment by DavidSum47** [comment]
I have now put 2 copies of collection.anki2 in the same Google Drive location as before.  The Desktop version contains 2 new cards in the Active deck, one with and one without a flag.  The AnkiDroid version is the result of syncing the file from the Desktop via AnkiWeb.  The sync produces an error message about a corrupted database, with a similar logcat output as before - notably "E/AnkiDroid: Syncer/ Sync - SanityCheck: there are notes without cards".  

'diff' reports a difference between the 2 database versions.

Running 'Check Database' in AnkiDroid results in a usable database, but it contains neither of the new cards!

David
