### ISSUE TITLE
unable to hide whiteboard whiteboard pen color picker

### ISSUE THREAD

**Issue by cburroughs** [ankidroid/Anki-Android#6601]
#6550 & #2731 recently added a color picker for the whiteboad pen color.  This appears to cause an additional app bar button (the paint pallet) to be displayed.  This means the whiteboard takes up twice as much app bar space as before (2 buttons instead of 1) and eats into the deck name.  (The deck name is sometimes important for context, in one narrow example, an 8 character deck name is now rendered as just the first two characters.)

I know #2731 has some slightly more general discussion.  As a narrow request based on the picker as implemented, I would like to be able to control it under `Settings-->Reviewing-->App bar buttons` (that is to set it to "menu only" and/or disable it).

###### Debug info
```
AnkiDroid Version = 2.12alpha20
Android Version = 10
ACRA UUID = 1d4a1744-66ec-42bc-b01f-fdec9ccd8f3a
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Thanks!! Should be fixed in the next release or two
