### ISSUE TITLE
Certain import does not progress past 0%

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6606]
Can't reproduce this yet. User-reported.

The file: https://ankiweb.net/shared/info/722819818 does not import past 0%. This is a file which is very heavy in terms of media

```
AnkiDroid Version = 2.11.3

Android Version = 9

ACRA UUID = 73fc609d-df15-4581-a744-c687db68e48a
```

ACRA reports are available for the UUID, but none display the relevant issue.

**Comment by david-allison-1** [comment]
Can't seem to get the specific device in Samsung's Test Lab. Have sent off a query to their support.

At a guess: could be file descriptor leaking in `Anki2Importer/Media`. I've coded up a potential fix, and will self-review, then PR tomorrow.

**Comment by Arthur-Milchior** [comment]
Do we have any way to contact user ? Whether it is a problem that did occur with older version ?

**Comment by david-allison-1** [comment]
I'm in contact with the user will ask them to reply here - AFAIK our last changes to the import code were in 2.11.3. 

The test under 2.11.2 should rule that change out.

Restarting the device didn't work.

**Comment by Tien0209** [comment]
There are 55862 filed in the collection.media folder. It's in my phone's storage

**Comment by david-allison-1** [comment]
> There are 55862 filed in the collection.media folder. It's in my phone's storage

There's 10208 files in the zip that you're trying to import.

55862 + 10208  > 65,536 (2^16)

@Tien0209  Could you check whether you can have a folder on your phone with 66,000 or more files in it?

**Comment by Tien0209** [comment]
I can't clone the content... by copyin it it always creates 1024 files and it doesn't even appear to be copied in the folder

**Comment by Tien0209** [comment]
Oh it actually does appear in the folder

**Comment by Tien0209** [comment]
It can have more than 66000 files

**Comment by Tien0209** [comment]
I cloned the contents and there are now more than 66000 files in the new folder

**Comment by Tien0209** [comment]
It's possible to have more than 66000 files in a folder

**Comment by Tien0209** [comment]
It's possible to have more than 66000 files in a folder

david-allison-1 <notifications@github.com> schrieb am So., 5. Juli 2020,
12:37:

**Comment by mikehardy** [comment]
@Tien0209 we get a message every single time you reply. Why have you replied 6 times?

**Comment by Tien0209** [comment]
The message didn't appear on my screen

**Comment by david-allison-1** [comment]
@Tien0209 We've released a possible fix in 2.12beta4, does this resolve the issue?

**Comment by Tien0209** [comment]
How do I access the new version?

**Comment by david-allison-1** [comment]
@Tien0209 https://docs.ankidroid.org/manual.html#betaTesting

**Comment by Tien0209** [comment]
Still doesn't work

**Comment by david-allison-1** [comment]
@Tien0209 We'll need to get Logcat working.

There aren't good instructions for doing this online

Could you:

* Enable USB Debugging on your phone: https://developer.android.com/studio/debug/dev-options

Either download Android Studio, or the Android SDK Platform Tools

----
**Android Studio**

* Download Android Studio: https://developer.android.com/studio
* Plug in your phone via USB
* Open the "Logcat" window and see if input appears.
* If it does, filter it to `com.ichi2.anki`
* Attempt an import in AnkiDroid, and post the logs.

https://developer.android.com/studio/debug/am-logcat

----
**SDK Platform Tools**

* Download the Android SDK Platform Tools: https://developer.android.com/studio/releases/platform-tools
* Shift+Right click in the folder and click "Open Command Window here"
* type in `adb devices` to run `adb`, it should list your device connected by USB
* Get `adb` working for your device if it doesn't


Run: `adb shell "logcat --pid=$(pidof -s com.ichi2.anki)"` and use Anki with your phone connected. Ensure that output occurs. Press Ctrl+C to stop;

* Close AnkiDroid
Run: `adb shell "am start -n com.ichi2.anki/com.ichi2.anki.IntentHandler; logcat --pid=$(pidof -s com.ichi2.anki)" > logcat.txt`
* Perform the import
* Ctrl+C when you feel the app has hung during the import
* Open logcat.txt and ensure that the input seems reasonable.
* Upload it here

**Comment by mikehardy** [comment]
This would be fantastic as a wiki page because yes, how you get access to logcat is very difficult. Also maybe #6565 where I user could provably send a report right then with a logcat attached might be the most useful over time

**Comment by david-allison-1** [comment]
> This would be fantastic as a wiki page because yes, how you get access to logcat is very difficult. Also maybe #6565 where I user could provably send a report right then with a logcat attached might be the most useful over time

Definitely better to get #6565 out, even with the steps above, I'll need a debug build to access `Timber.d`

**Comment by Tien0209** [comment]
Nvm, it works now. Thanks

**Comment by david-allison-1** [comment]
Great to hear it!
