### ISSUE TITLE
MIUI: Night Mode Copy Paste Menu Issue

### ISSUE THREAD

**Issue by Kayx23** [ankidroid/Anki-Android#6614]
<img src="https://user-images.githubusercontent.com/39619599/86519749-ef7bb100-be0b-11ea-8d3d-7e46cbe3f4ac.jpg" width="350">

The menu is all blank. Usually there are copy, paste, select all etc. 
###### Debug info
**AnkiDroid version 2.11.3**  - I'm not sure if this is an issue for this version specifically since I just started using night mode

**Comment by david-allison-1** [comment]
@Kayx23 Are you using a Xiaomi phone?

**Comment by Kayx23** [comment]
@david-allison-1 Yup! (how do you know)

**Comment by mikehardy** [comment]
Because Xioami phones have terrible behavior with regard to some Android APIs - as a manufacturer they implement the Android OS incorrectly and seemingly don't care unfortunately. As a developer I warn users off from the brand if possible but I understand they are popular. 

We just implemented a Xioami workaround for the popup menu recently here #6497 but I didn't realize we need one for the night mode as well

@david-allison-1 perhaps if brand == xioami we just kill the popup menu thing completely?

**Comment by mikehardy** [comment]
Thanks for reporting this by the way @Kayx23 - that was me asking for the report on the app store review, I appreciate it, as we can probably get this fixed now :-)

**Comment by david-allison-1** [comment]
@mikehardy I don't think that'll fix it - I /think/ we're overriding the text color, but not the background color for their custom `ActionMode` implementation on TextBoxes - I think this is the default menu showing, but I'm happy to be mistaken.

**Comment by mikehardy** [comment]
I'm just saying that if for Xioami we stop doing anything text menu at all, I'd be shocked if what is then their default menu fails on night mode. That's almost unthinkable even for Xioami

**Comment by david-allison-1** [comment]
My bets are that it's a theming issue on our end. We can stop the below on Xiaomi, but I can't see how that'd cause this bug

https://github.com/ankidroid/Anki-Android/blob/cf720e0c56ff05a63590a5f86697444c01f02515/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1245-L1250

https://github.com/ankidroid/Anki-Android/blob/cf720e0c56ff05a63590a5f86697444c01f02515/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1799-L1826

**Comment by david-allison-1** [comment]
We need someone with a Xiaomi phone to debug and determine if we can change the styling. Unlikely to happen sadly.

**Comment by Kayx23** [comment]
Let me know if there's anything I can help on my end - otherwise I can live with the night mode menu.

**Comment by Kayx23** [comment]
still searching for solutions

**Comment by mikehardy** [comment]
I think this is a general case of #8150 
I think this will "fix" it (work around it, really)

> Turn off dark mode for AnkiDroid by going to Display -> DarkMode -> Individual Apps. This issue had been seen in many apps on MIUI.

if so, this should be closed as duplicate of #8150 

Likely solution is to disable force dark mode? https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#force-dark - but that would need someone to test (perhaps @Abanoub-Asaad - as they have a Xioami handset I believe...)

**Comment by Abanoub-Asaad** [comment]
Sure!
I haven't changed anything in the settings
**PS** : I'm using Xiaomi - Android 7.

Regarding: `Cut - Copy - Paste` 
<div align="center">
<pre>
   
<img alt="" width="30%" src="https://user-images.githubusercontent.com/48657780/118372001-7f06fa00-b5af-11eb-91c3-e72d5586ee36.jpeg">   <img alt="" width="30%" src="https://user-images.githubusercontent.com/48657780/118372002-80382700-b5af-11eb-97dc-fd4823d0141c.jpeg">    
     
</pre>
</div>

Regarding: `the flag color` 
<div align="center">
<pre>
   
<img alt="" width="30%" src="https://user-images.githubusercontent.com/48657780/118372067-eb81f900-b5af-11eb-9ecf-c306723284c2.jpeg">   <img alt="" width="30%" src="https://user-images.githubusercontent.com/48657780/118372073-f2a90700-b5af-11eb-94e0-3e479f835739.jpeg">    
     
</pre>
</div>

**Comment by Kayx23** [comment]
> I think this is a general case of #8150
> I think this will "fix" it (work around it, really)
> 
> > Turn off dark mode for AnkiDroid by going to Display -> DarkMode -> Individual Apps. This issue had been seen in many apps on MIUI.
> 
> if so, this should be closed as duplicate of #8150
> 
> Likely solution is to disable force dark mode? https://developer.android.com/guide/topics/ui/look-and-feel/darktheme#force-dark - but that would need someone to test (perhaps @Abanoub-Asaad - as they have a Xioami handset I believe...)

My "Display -> DarkMode" is off for all apps. Still experiencing the same issue on AnkiDroid version 2.15.5. My phone is on MIUI Global 11.0.6 Stable. 

I already developed muscle memory of where the buttons are lol, no worries

**Comment by Kayx23** [comment]
Hi @david-allison-1, I happened to notice the same issue today when I was long pressing to get the menu to paste something in the YouTube app. So I suppose the problem isn't localized to Anki mobile anymore. Feel free to close the issue if need to.

**Comment by mikehardy** [comment]
Turns out it appears possible via an xml change to disallow force dark mode entirely, this could solve a lot of MIUI problems, with the caveat that then the user would have to select it manually again until #9408 lands https://stackoverflow.com/a/65616633/9910298
