### ISSUE TITLE
Adding an image to a card overwrites the file name

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#6622]
###### Reproduction Steps

1. Review a card with an image > Menu > Edit note
2. Tap on the paper clip next to the image field
3. Tap on "Gallery" button, select an image "test.jpg" from your gallery and save the changes

###### Expected Result

The image "test.jpg" will be copied to the collection folder

###### Actual Result

Instead, the image will be renamed to some horrible construct like img_202007050926164513682973119384157.jpg 

Some of my decks rely on the image file name that I choose myself, so by renaming them automatically the deck doesn't work anymore :-(

Also I didn't realize this automatic change before because there's no such message. Therefore I would recommend to show a message that the image was renamed OR show the file name below the (recently added display of the) image size (which would be a useful information anyway).

###### Debug info
AnkiDroid Version = 2.12.0beta3

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Result of #6543. @mikehardy

**Comment by mikehardy** [comment]
Yeah, there is an opposite case where if we don't rename the image there can be collisions.

The "horrible" construct is otherwise known as a "unique name" ;-)

So I want to say that as Anki ingests media there can be no guarantee of filenames that result, I think that is a correct statement, and I think stating otherwise is technically wrong. The following is based on that.

From a user experience perspective, what would work for you?

User messaging with the ability to copy to clipboard the message we will use internally?
A "speculative" (we can try it, might work, might not) image rename?

I'm not sure the best way to handle it, all I know for sure is that if we don't create guaranteed unique names there are other problems.

**Comment by Anthropos888** [comment]
Haha, sorry for the "horrible", it's just my user experience and a file name that exceeds my phone's screen is really unpleasant.

Question: why do we need to rename the images? Anki desktop saves them as they are. And beforehand it checks for name conflicts and renames the image to "test (1).jpg" if "test.jpg" already exists.

**Comment by mikehardy** [comment]
Ah, I should explicitly recognize that any choice that proposes a limited number of options is the "fallacy of false choice"

So Desktop is handling the collision, but they're generating unique names that users like. Our current "unique name" algorithm is provably unique but sucks for users (I'll grant that!)

So a proposed solution would be:
- attempt to copy the image in by it's original name, use that if unique
- only if not unique rename to "original name (N).extension" where 'N' is the number required to be unique, incrementing past whatever number was there previously? I suppose we would need to message that to the user somehow, perhaps a quick 'we did this" with only "OK" dialog is sufficient?

...and to again recognize the false choice, anything is possible (within reason) if you have a cleaner idea?

**Comment by Anthropos888** [comment]
> attempt to copy the image in by it's original name, use that if unique

Perfect!

> only if not unique rename to "original name (N).extension" where 'N' is the number required to be unique, incrementing past whatever number was there previously?

Perfect!

> I suppose we would need to message that to the user somehow, perhaps a quick 'we did this" with only "OK" dialog is sufficient?

Anki desktop doesn't do this. But yes, a message that "xyz.jp" already exists and thus was renamed to "xyz (n).jpg" would be a hell of a clean approach.

**Comment by mikehardy** [comment]
Great, I'll see what I can do - it shouldn't be too much of a change vs the current state after the crop PR landed
As ever, I appreciate that you test the betas and take the time to work with us on improvements. It makes a real difference, thanks @Anthropos888

**Comment by david-allison-1** [comment]
Another Proposal:

* Copy to the cache with the unique name
* Store original name
* When saving to the collection, if no conflict occurs, then save using the original name
* Otherwise, warn and provide the user with the options:
  * Replace
  * Rename - Text box with reasonable default name
  * Cancel

**Comment by mikehardy** [comment]
Yeah - the implementation could follow that path - the cache step (before moving to collection) is independent

**Comment by Anthropos888** [comment]
Or if it is easier to implement, then here's another idea:
- leave everything as it is
- but show the file name below or above the file size (which would be useful anyway)
- add a button "Rename" that allows users to input their own file name (give a warning if file name already exists)

This would also solve one of my other issues: https://github.com/ankidroid/Anki-Android/issues/5192  :-D

**Comment by mikehardy** [comment]
That could also work. I'll consider both when I set up tools in the area and start work

**Comment by dae** [comment]
FWIW, recent Anki versions will append a hash of the content to the filename on a conflict. Some workflows always used the same filename (eg "image.jpg"), and as the numbers increment and are predictable, (1), (2) and so on could lead to conflicts with different files added on another device prior to syncing.

**Comment by mikehardy** [comment]
Very interesting @dae ! thanks for that tidbit. @Anthropos888 this is unfortunately a strike against the idea of keeping the "make name unique" method producing really nice names if we have direct experience it has failure modes. I'll have to think on this but based on the new experience shared by Damien I'm thinking that any proposed fix would still have a nasty-looking name as a main component (possibly with editing power, but defaulting to a big ugly name).
