### ISSUE TITLE
AnkiDroidJS.ankiGetNextTime4() still returns a value even when it should be empty after failing a card

### ISSUE THREAD

**Issue by danZ4C** [ankidroid/Anki-Android#6623]
Hi, I think i got access to beta or something as AnkiDroidJS.ankiGetNextTime4() started working even though I haven't noticed an official release.

For example I have a mature card with 4 buttons available (Again/Hard/Good/Easy) and AnkiDroidJS.ankiGetNextTime4() will return "2.9 mo". I fail that card, and the next time the card is shown, it will have only 3 buttons available (Again/Good/Easy), but AnkiDroidJS.ankiGetNextTime4() will still return "2.9 mo". I believe it should be empty right? It normally is if a card wasn't mature and had only 3 buttons.

I use my custom interface and this code to always press just the "Good" option, it works fine it i don't fail a card, if i do it stops working.

   if (AnkiDroidJS.ankiGetNextTime4() == "") {
         answerButtonEase2();
     } else {
          answerButtonEase3();
     }

**Comment by david-allison-1** [comment]
Thanks for the report.

2.12 beta is out. Added in 589216460ed0a1d509890d55f1b1a1279d56566a (#6388)
