### ISSUE TITLE
Decks.isValidDeckName is named poorly and does not fully validate

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6639]
isValidDeckName is definitely *intended* to be a deck name check prior to creating a deck, but I think in our new naming we should call it "isValidDeckNameComponent" (since it's for the UI version of a deck, which is actually just a part of a potential deck hierarchy where the whole name is encoded with the :: separators yes)

But I certainly don't know all the validation rules, all I know is that they were not validated *at all* before, so I put a first take in place where I at least don't allow completely empty names. Any expansion is welcome but is also not necessarily a priority - we lived without any validation this long after all...

From Arthur:

> Nowaday, valid deck name should not contains "::::", and no part of the name should starts or end with spaces. However, I don't know whether you want to send error message for spaces as we can easily trim them. That should occur in a different PR I assume
>
> Deck names which are not normalized UTF-8 are not valid either, and I don't know if it's possible for a user to actually enter that except if they are really trying to do it

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/6638#issuecomment-654003798_

**Comment by Sofrosyn** [comment]
I could check it out, I'm New to the open source community and I use anki a lot

**Comment by david-allison-1** [comment]
@Sofrosyn Thanks! Feel free to post here if you need any guidance.
