### ISSUE TITLE
Feature request: App action to trigger synchronization

### ISSUE THREAD

**Issue by lleaff** [ankidroid/Anki-Android#6646]
Android has [App Actions](https://developers.google.com/assistant/app/overview), essentially [deep links](https://developer.android.com/training/app-links/deep-linking) to some activity in the app, documented in an XML file.

The linked doc talks about Google Assistant, but any third-party launcher can trigger these in response to various events, link them from home screen shortcuts, etc.

Since I often have to open AnkiDroid simply to trigger the synchronization, having an app action for this would turn a frequent three-step process (launch App, wait for it to load, tap on sync button) into a single step.
There could also be actions to jump directly to a review of the default deck for instance.

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
Sounds interesting - we could consider such a feature if you posted a PR for it
Alternatively you might like Tasker, we implement a Tasker intent that triggers a sync, and Tasker is a general purpose system for automating Android actions, it may transitively support all the things you want already, and turn them into an AnkiDroid sync.

**Comment by lleaff** [comment]
Perfect thanks, didn't know about this feature but it allows for exactly what I wanted to achieve ([doc](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API#sync-intent)). The app actions way would be a little bit cleaner, I will try having a go at it eventually.

**Comment by sudomain** [comment]
> Since I often have to open AnkiDroid simply to trigger the synchronization, having an app action for this would turn a frequent three-step process (launch App, wait for it to load, tap on sync button) into a single step.


Not sure if you know about it, but the autosync setting should help reduce the steps
