### ISSUE TITLE
"Collection not opened" bug message is misleading

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#6649]
###### Reproduction Steps

1. Try to review a card

###### Actual Result

![Screenshot_20200707-222006~(1)](https://user-images.githubusercontent.com/45192213/86838217-31248a00-c0a0-11ea-96d7-6e56bd1303fa.jpg)

I had this bug several times after updating Ankidroid. According to the mailing list, several users had the same issue after an update.

The problem: the message suggests to restore the collection from backup, which 
1) doesn't solve the problem
2) can cause loss of cards and scheduling information if the backup is quite old

I'd suggest to remove the part about restoring from backup in the message.
Instead, you could add something like:
"This bug may be caused by a recent Ankidroid update. You could try to install a previous version of Ankidroid: https://github.com/ankidroid/Anki-Android/releases"

Downgrading to a previous version solved this issue in most cases I'm aware of.

###### Debug info
AnkiDroid Version = 2.13alpha1

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Thanks for the report. Duplicate of #6645

**Comment by Anthropos888** [comment]
@david-allison-1 Thanks. I updated the description, could you open it again?

**Comment by Arthur-Milchior** [comment]
Makes a lot of sens actually. At least on alpha/beta. Is there a way to test whether it's alpha/beta or main code ? If the only difference is the error message, I hope it would not be a security risk
