### ISSUE TITLE
Can't open collection - no card with id 0

### ISSUE THREAD

**Issue by lucaslcode** [ankidroid/Anki-Android#6655]
###### Reproduction Steps
Version 2.13alpha1
1. Try to open deck for review
[bug.apkg.zip](https://github.com/ankidroid/Anki-Android/files/4893429/bug.apkg.zip)

###### Expected Result
Deck opens

It works on version 2.11.3

###### Actual Result
Can't open deck. Running a check and doing a full sync doesn't help.

Truncated logcat:
```
07-08 22:44:44.933 30864  4121 E AnkiDroid: com.ichi2.libanki.WrongId:  No card with id 0
07-08 22:44:44.933 30864  4121 E AnkiDroid:     at com.ichi2.libanki.Card.load(Card.java:24)
07-08 22:44:44.933 30864  4121 E AnkiDroid:     at com.ichi2.libanki.Card.<init>(Card.java:8)
...
```

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
You should definitely update to 2.13alpha2 - https://github.com/ankidroid/Anki-Android/releases/tag/v2.13alpha2

I think this may be fixed, the truncated logcat needs more stack frames to be useful unfortunately, starting at the first AnkiDroid stack frame if possible

**Comment by lucaslcode** [comment]
Works!

**Comment by mikehardy** [comment]
Really glad to hear it, sorry for the bother
