### ISSUE TITLE
Issue on AnkiDroid: Wrong time calculation

### ISSUE THREAD

**Issue by sergiocues** [ankidroid/Anki-Android#6657]
###### Reproduction Steps
I always study on the mobile, and I have verified that the study time is not calculated properly. I think it only takes into account the time the screen is turned on.
Maybe an easy option to solve this would be count the time from click to click. I mean, from the first click, when you choose the deck to start studying, to the last time you click on any button to evaluate your progress: 'again, good, easy, etc.'

1. Open AnkiDroid
2. Start Studying
3. Turn off the screen
4. Check the time

###### Expected Result

All the time since you start studying to the moment you exit the deck.

###### Actual Result

All the time the screen is turned on.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Kubo2** [comment]
@sergiocues Are you sure this is not because of the default maximum time limit after which spending any more time on a card is ignored? Anki's default value for this option is about 60 seconds I believe, and it is configurable in the Deck Options.

**Comment by sergiocues** [comment]
I don't think so, I have this time set to 900 seconds.

**Comment by mikehardy** [comment]
I believe it is true that when the screen turns off we stop counting. The idea being, how could you be actively reviewing without the screen on?

**Comment by david-allison-1** [comment]
Yep, done intentionally: https://github.com/ankidroid/Anki-Android/blob/c59f5d10c24832fbfe3af9c55d206f54418af1a9/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L915-L924

**Comment by sergiocues** [comment]
Because I'm using Anki to memorize long texts in a literal way. In fact, I've to memorize 31 texts, about 3300 words long each.
To do so, I've divided each text on a deck, and each deck on 60 cards, so each card has about 55 words.
When a card is shown, I read it several times. Then I turn off the screen and try to remember (just to avoid the waste of battery). That's the reason why I turn off the screen so often.
If this is done intentionality, as David said, this could be easily overridden just by adding a checkbox to the options, so anyone could prevent it from happening.
