### ISSUE TITLE
New phone and my progress didn't save 

### ISSUE THREAD

**Issue by sareli92** [ankidroid/Anki-Android#6660]
So I just got a new phone yesterday and when I signed in and refreshed the page it saved my recognition remembering the kanji deck but it started all the way at the beginning again where in like 300 kanji in...how can I get my progress onto my new phone?? All my progress is going to waste...
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi,

Did you press "Sync" on your old phone?
