### ISSUE TITLE
Feature request: Manually rearrange cards

### ISSUE THREAD

**Issue by sergiocues** [ankidroid/Anki-Android#6661]
I've noticed that when you have a large amount of cards to be reviewed the same day, they don't appear in order. I assume they appear ordered by time. In some cases, it would be really useful if there is a checkbox in the options to force the cards to appear in the same order that they appear in the deck.
Why? Maybe someone like me is using Anki to memorize large texts literally, and having the cards shown in its order will help memorize them, as they can be used as clue for next cards.

Another option would be the hability to rearrange cards in the card explorer. I think this could be better done on the PC, if the time is also shown. At this moment only appears the date, and it's not editable. Making that schedule editable would allow to rearrange the cards in any order you want. Even to be scheduled to be shown in a different day. That would be really useful when planning hollidays where you won't be able to study, just to avoid a large of cards being shown after the hollidays, forcing some of them to appear before that lapse in advance.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by yashrajverma** [comment]
I would like to add such feature in the app to appear card's and arrange automatically in time wise arrangement.
