### ISSUE TITLE
2.13alpha2: menu and review crashes 

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#6667]
###### Reproduction Steps

1. Try to review a deck
2. Or try to open menu > advanced > about Ankidroid

###### Expected Result

No crash

###### Actual Result

Crash. Report is being sent. 

###### Debug info
2.13alpha2, but I can't open the debug info

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Likely #6658 - Should be fixed in alpha3.

**Comment by Anthropos888** [comment]
> Should be fixed in alpha3.

@david-allison-1  Hopefully ;-) Uninstalling AnkiDroid alpha after a crash in order to install the beta/stable is a bit inconvenient because some gestures are not saved.
Is there a way to install an older beta on top of an alpha so that I don't need to uninstall the alpha first?

**Comment by david-allison-1** [comment]
@Anthropos888 We now provide parallel releases of both our stable releases and betas, so you could install `parallel.A` as stable, and `parallel.B` as beta (for example).

Sadly, these won't auto-update via Google, but it should let you keep a "known good" collection if the alphas are unstable for any reason.

We're aiming to get more automated testing in the problematic areas over the next couple of weeks. Sorry for the inconvenience, and as always, thanks so much for the testing, it's invaluable!

**Comment by david-allison-1** [comment]
@Anthropos888 This should be fixed in alpha3. Please let us know if it still occurs.

**Comment by Anthropos888** [comment]
2.13alpha3 solves the problem. As always, thanks for the quick fix!
