### ISSUE TITLE
MathJax slows the card loading

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#6668]
###### Reproduction Steps

1. Have a bunch of card with mathjax
2. review them

###### Expected Result
Each time a card load, the contents gets directly displayed. As for any kind of cards. I.e. the text change from one card to another one

###### Actual Result
The screen is empty during a fraction of seconds. In night mode, it means there is all black, and then white again. It's really unpleasant

###### Debug info
Running "merge", but the problem was the same on master last time I checked.

I do not know enough to be able to guess what the solution ought to be. I assume that loading mathjax is expensive and so it should not delay showing content. I would imagine that we could first display the card as is, and then execute its mathjax, a lot of website does it and its less painful. We could also look whether a field contains `\(` or `\[`, and if so pre-load mathjax in the web browser before changing the card content. Or maybe even loading the card in the webobject in advance, and only displaying it later (assuming we have a way to pre-compute the next card... if you see what I mean)

**Comment by Arthur-Milchior** [comment]
> Please remember we are all volunteers here

Ok

> the fastest way to get resolution on an issue is to propose a change directly, 

I'll eventually look at it then

**Comment by david-allison-1** [comment]
Related: #6410

**Comment by dae** [comment]
Closing in favor of #14302
