### ISSUE TITLE
Crash when review ends

### ISSUE THREAD

**Issue by idkw** [ankidroid/Anki-Android#6674]
###### Reproduction Steps

I'm currently using 2.13alpha2 and most of the time (~4 out of 5) the app crash when finishing reviewing a deck. Then if I open the app again the review seems to have been entirely forgotten.

I have tried uninstalling, reinstalling, clearing cache, clearing data but the issue remains.

I have sent the error reporting crash report every time it occured but I don't if you receive it or if if I can do anything to help you investigate.

###### Expected Result

The app doesn't crash and saves the review result.

###### Actual Result

The app crashes and doesn't save the review result.

###### Debug info

AnkiDroid Version = 2.13alpha2

Android Version = 10

ACRA UUID = f8db4366-6f05-4d91-baf0-21511c8d83c0

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
We have been watching the reports closely and I think they are all identified at the moment, with one fix already made that is unreleased - should be released today as 2.13alpha3
In the meantime you may want to install 2.12beta5.A (the parallel 'A' build) on your device so you have a stable reviewing experience https://github.com/ankidroid/Anki-Android/releases/v2.12.0beta5

**Comment by idkw** [comment]
Thanks, I was able to review my decks using the parralel A version 2.12beta5

**Comment by mikehardy** [comment]
Great! We are obviously working on fixing the underlying issues - but especially for people on our alpha track we really value your testing and don't want you to have to hop off alpha and maybe never get back on. Good to have an interim solution while waiting for the next release :-)

**Comment by david-allison-1** [comment]
@idkw This should be fixed in alpha3, please let us know if it still occurs.

Thanks so much for testing!

**Comment by idkw** [comment]
Just tried reviewing my decks with 2.13alpha3 and the issue appears fixex, no more crash when finishing a review
