### ISSUE TITLE
Autopublish to Huawei app gallery

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6677]
It appears we can do releases to the Huawei AppGallery automatically using this: https://github.com/cianru/huawei-publish-gradle-plugin

So it would not be too different from the recent auto-publish addition of Amazon Kindle Store: https://github.com/ankidroid/Anki-Android/commit/598e16e53810a57157646a543f7e10ae6cbcc5de#diff-01a43ecae7f3cbc652f4ae54b0232b5e

Would require a project owner to create our project with Huawei and store secured credentials with release managers here

**Comment by david-allison-1** [comment]
Turns out GitHub's blocked in the mainland, +1 here.

**Comment by mikehardy** [comment]
Even if github is available, it's not going to be nearly as accessible as simply using the default app store on the phone, and per google they can't do it (https://support.google.com/android/thread/29434011?hl=en) so this is by far the best way to reach Chinese users.

I did just check (for grins) and analytics tagging does work, we have analytics on chinese users (likely because of the way we do it, directly posting to the servers vs loading JS libraries etc or using phone pre-installed Google Play GMS libraries, thanks open source licensing requirements for forcing that...)

**Comment by mikehardy** [comment]
verification of my personal details to create a developer account (which will host the app) in process
status will be here https://developer.huawei.com/consumer/en/console#/userSetting/profile

**Comment by mikehardy** [comment]
```
Dear developer,

  Your application to join HUAWEI Developer was reviewed.


  Review result: passed

  Your membership starts from 2020-08-11.
```

So I'm unblocked, this will go back in the actionable task hopper...

**Comment by mikehardy** [comment]
How exciting, android package `com.ichi2.anki` is already taken. I've submitted a ticket with accompanying documentation to claim the app for the account I'm currently working in so I can upload a build

https://developer.huawei.com/consumer/en/support/feedback/#/ticketDetail?id=65302&time=2020-08-10%2018:17:42&ticketeCheckState=0

**Comment by mikehardy** [comment]
That took a while but this popped in my mailbox overnight, meaning I should be unblocked to try again:

```
The issue has been resolved, please try upload your app again.

Should you need help with anything else, please feel free to reach out back to us.

```

**Comment by mikehardy** [comment]
Our first Huawei AppGallery release is available:

> Dear developer,
> 
> Your application submitted at 07:04:16,August 23,2020 for releasing AnkiDroid Flashcards 2.12.1 was approved. AnkiDroid Flashcards 2.12.1 is now available for download on HUAWEI AppGallery.
Review comment: Your App has been approved. 

https://appgallery.huawei.com/#/app/C102711481

All blocks that were out of my control are removed and I will now pursue automated auto-publish implementation via our release script similar to Amazon autopublish https://github.com/ankidroid/Anki-Android/commit/598e16e53810a57157646a543f7e10ae6cbcc5de#diff-b91eeb35e4e3920b1a96d2d03212320a

@infinyte7 out of curiosity, any interest in adding the AppGallery badge to the README? :-) :pray: They have a button pack here: https://huaweimobileservices.com/appgallery-badge.zip - I also noticed the F-Droid one is clipped just a little in text-to-right-edge spacing, but that's minor

**Comment by infinyte7** [comment]
I will update all store badge with recent updates.

**Comment by mikehardy** [comment]
champion :trophy:  :rofl: - thanks man

**Comment by PANG-hans** [comment]
@mikehardy I find some thing may out of your control happend, the [released APP](https://f-droid.org/packages/com.ichi2.anki/) in `F-Droid` now can not supported in HUAWEI APPgallery in **Chinese mainland**, insteaded with another [APP](https://appgallery.huawei.com/#/app/C103098439).
If i click the [link](https://appgallery5.huawei.com/#/app/C102711481) in home page and try to download it, follwing reply means `service not support in current location` got:
![image](https://user-images.githubusercontent.com/49405752/115977698-eaf7d300-a5ac-11eb-9993-88ff51865176.png)
 

Maybe you need to contact with HUAWEI for get the license(sounds like you need to get the permition, i don't no how to do)? Hope that my reply can help you.

**Comment by mikehardy** [comment]
We are already present in the Huawei AppGallery with up to date versions even
It just doesn't *auto*publish there. I want to automate it, but it's no big deal - will happen eventually

**Comment by PANG-hans** [comment]
I mean that the up-to-date version is NOT visible now in Chinese mainland, oversea may still can work. A [version](https://appgallery.huawei.com/#/app/C103098439) made by local company was showed when searching `Anki`:
`Anki探索版` is diff of your version, total different. I don't know wether this company get the permission to do this from your developers.
![Screenshot_20210425_110730_com huawei appmarket](https://user-images.githubusercontent.com/49405752/115979187-1aabd880-a5b7-11eb-8067-666ccb737b6a.jpg)

And details of  this App
![Screenshot_20210425_110824_com huawei appmarket](https://user-images.githubusercontent.com/49405752/115979220-3dd68800-a5b7-11eb-82ee-641ece0dcc3f.jpg)


The users may not get update auto when you upload new version if they downlad the past version(May be before March. 20, i find in comment, for after your version is not supported in chinese mainland), they need to manually download and update or use the version developed base on your relesed.

####I didnot find the related issues to post these info but find this relates, so just post them here, or i need to report it in **google groups**? The [same case happend in MI store](https://groups.google.com/g/anki-android/c/_2x5bBZ57dI/m/ocQ7k3heAQAJ), posted by@**Sarah Ding**  when i search in the group.

**Comment by mikehardy** [comment]
https://appgallery.huawei.com/#/app/C102711481

@PANG-hans what *exactly* is your goal collaborating in this repo? I don't have much more time for back and forth with you without something substantial that represents real forward progress.

**Comment by PANG-hans** [comment]
Maybe i didn't explained clearly.

What i want to report:

What you want to get in your [issuecomment](https://github.com/ankidroid/Anki-Android/issues/6677#issuecomment-668681624) exactly _not_ works. People can NOT get AnkiAndroid from default app store and you could not receive feedback either! That's what i want to report.

Maybe you can find another local chinese mainland people to test that...



Reseason:

Yes you push up-to-date version to HUAWEI gallery. But people in chinese mainland can _NOT_ find it(wrong feedback when searching, no download, no update, also no give comments). Info in this [picture](https://github.com/ankidroid/Anki-Android/issues/6677#issuecomment-826207220) shows that you can not give serives in chinese mainland.

For you in overseas may can download it in HUAWEI gallery, but most people in Chinese Mainland can not download, or even can not reach the link. They can just find [this](https://appgallery.huawei.com/#/app/C103098439).



> Even if github is available, it's not going to be nearly as accessible as simply using the default app store on the phone, and per google they can't do it (https://support.google.com/android/thread/29434011?hl=en) so this is by far the best way to reach Chinese users.
> 
> I did just check (for grins) and analytics tagging does work, we have analytics on chinese users (likely because of the way we do it, directly posting to the servers vs loading JS libraries etc or using phone pre-installed Google Play GMS libraries, thanks open source licensing requirements for forcing that...)

**Comment by mikehardy** [comment]
Thanks, I'll investigate.

**Comment by mikehardy** [comment]
Sadly, China has really decided to be a controlled autocracy, and their policies are increasingly difficult to work with as a non-mainland developer. I think the only sane path for us here is to respect that.

With recent policy decisions to only allow app uploads from registered mainland citizens I've chosen to remove our app from the Huawei AppGallery and I will no longer pursue any Chinese app store release channel work.

Our APKs are *always* freely available on the wider internet, as is our source code. They will also be available in user-friendly formats for those with non-filtered internet via google play store or f-droid
