### ISSUE TITLE
Unable to copy files directly from PC into collection.media folder

### ISSUE THREAD

**Issue by Thermospore** [ankidroid/Anki-Android#6680]
###### Reproduction Steps

1.  Connect a Galaxy S10 to a Windows PC via USB
2.  Try to copy any number of files from the Windows PC to the AnkiDroid collection.media folder

###### Expected Result
File(s) are copied to folder

###### Actual Result
Windows file transfer UI hangs and file(s) are not transferred

###### Debug info
Unable to get debug info as there are too many files to sync from Ankiweb in a reasonable amount of time, which is why I'm trying to copy them manually. I'm using the latest public release. There will be about 90,000 files in my media folder once everything is copied over (I think currently it should be at about 70,000). The files are all quite small; there is only about 4GB of media total. 

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

- Files transfer without issue to other folders on the Android device; issue is limited to the Ankidroid directory
- Files are syncing / downloading from AnkiWeb without issue, but there are just so many that it would be faster to manually copy them from a PC
- Issue occurs even when AnkiDroid is not running
- Issue occurs on all Windows machines I've tried
- Issue did not occur in the past. Last time I did this was roughly a month ago, and there were no issues. Though, I think there were only about 20,000 files in the folder at the time

**Comment by david-allison-1** [comment]
Hi, thanks for the report.

This seems like an Android/Windows issue, rather than an AnkiDroid issue.

* Is this to an SD card, or internal storage?
* Have you tried copying the files to a folder on the root of the device, then copying them into `collection.media`?
* Have you ever had a folder with over 65k files? That can cause issues on some storage types.

**Comment by Thermospore** [comment]
Thanks for the response!

- This is to internal storage
- It seems going anywhere near the AnkiDroid folder all but crashes Windows Explorer. However, I can copy files to a different folder and then move them to collection.media through the file explorer UI on the Android device itself. Unfortunately after reaching about a thousand files copied Windows starts chugging and it slows to a crawl. Zipping the files first solved that issue. However, the Android file explorer is too inefficient to move that many files from one folder to another. It ends up being even slower than simply syncing the files from AnkiWeb
- To be honest I'm only familiar with the very basics of this topic

**Comment by Thermospore** [comment]
I have a suggestion that could work around the issue though (forgive me if this is already a thing). Maybe there could be an option to only sync media from specified decks. 95% of my media is from a bank of TV shows I have. I only move a handful of cards from it per day into my actual review deck (I do this on Anki desktop). There isn't really need to sync all of that media over to AnkiDroid. Refer to this messy diagram:

![image](https://user-images.githubusercontent.com/35350819/87617089-203ccf80-c6c3-11ea-8026-10c10036282e.png)
