### ISSUE TITLE
Media tries to download via sync even though the media already exists

### ISSUE THREAD

**Issue by nsmarkop** [ankidroid/Anki-Android#6681]
###### Reproduction Steps

1. Have cards with a lot of media associated and sync them from the desktop client (Anki 2.1.22) to AnkiWeb
2. Copy the contents of .../AppData/Roaming/Anki2/User 1/collection.media on my computer to AnkiDroid/collection.media on my phone via SFTP
3. Verify that the file count is the same on both sides (84,578 files), the size is the same, and the names / timestamps all match
4. Open up AnkiDroid

In FileZilla (left is my desktop, right is my phone):
![verified_all_files_synced](https://user-images.githubusercontent.com/4577561/87634759-c3590d80-c6f2-11ea-9730-e4f35cb43e95.png)

I checked the file count and size directly on my phone as well with Solid Explorer.

###### Expected Result

Opening up AnkiDroid syncs any regular changes but then does not try to download any media since it was manually synced to the media folder and already exists.

###### Actual Result

Opening up AnkiDroid syncs my regular changes and then starts downloading media files. This goes on for a long time, as if it's trying to sync every media file I added.

###### Debug info
AnkiDroid Version = 2.11.3

Android Version = 9

ACRA UUID = 18ca6cd2-19ab-46a3-a92c-030ef928bf84

I was able to grab this by pressing the app overview button, swiping AnkiDroid away to kill it, and opening it back up at which point it skipped syncing. Syncing manually again or reopening it repeated the undesired media download process though.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by nsmarkop** [comment]
Using the technique I mentioned when grabbing the debug info, I went into the card browser and scrolled through to various random cards to preview them. The images / audio I synced manually that did not exist on the phone before work as expected even though the app's media sync still thinks it needs to download media.

Not sure if that helps diagnose the problem at all, but it at least means I can work around this for now by disabling media sync in the AnkiDroid settings after force cancelling an application start sync once to get into the settings and then relying purely on the manual sync from what I can tell.

**Comment by mikehardy** [comment]
I wonder if you just ran "check database" after manually copying things it would work?
The thing is that AnkiDroid does maintain a media database separate from the card collection and if you mess with the filesystem things are obviously out of sync as AnkiDroid didn't get a chance to keep the media collection maintained.

media check (similar to check database, top right menu of deck picker) throws the database away and rebuilds it directly if I recall correctly

**Comment by nsmarkop** [comment]
Ah, that makes sense if it's going off of its own cache of what's there.

Trying "check database" didn't work for me, but "check media" actually seems to have resolved it. It was a little odd in that it attempted to download 1 media file and got stuck for a while (the upload data amount increased by 1 every minute or so but stuck in the single digits and the download data amount didn't change) then suddenly it finished and has been working fine since with media syncing turned back on again.

**Comment by mikehardy** [comment]
Excellent! I was hoping that would work.

At minimum this is a documentation problem then, and it happens to quite a few people

Our FAQ is a wiki and you can just hit the edit button and add whatever you want in there. As a user you may be the best suited to write a FAQ that for this, taking into account the user perspective better than a maintainer could. Care to give it a shot? https://github.com/ankidroid/Anki-Android/wiki/FAQ - just add it to the end with a short-ish `##` title (since it helps keep the link short) and everyone can edit until it is polished up

**Comment by nsmarkop** [comment]
Sure thing, I added a section here:

https://github.com/ankidroid/Anki-Android/wiki/FAQ#i-have-many-media-files-and-syncing-them-to-my-device-takes-too-long

I titled the section based on the situation I encountered this in, but if you think it'd be better just labeled "manually syncing media files" or something I can update it.
