### ISSUE TITLE
v2.12.0, When I click the "preview" button, Anki shows nothing but "front + back " ONLY."

### ISSUE THREAD

**Issue by Drrrrr519** [ankidroid/Anki-Android#6700]
![IMG_20200719_160350](https://user-images.githubusercontent.com/64855701/87870435-9189c480-c9da-11ea-9ba1-55b4764fb2cb.jpg)
![IMG_20200719_160415](https://user-images.githubusercontent.com/64855701/87870442-a6feee80-c9da-11ea-999b-458cc8437a1e.jpg)
![IMG_20200719_160423](https://user-images.githubusercontent.com/64855701/87870444-ac5c3900-c9da-11ea-8d39-d96f2213a0da.jpg)

**Comment by david-allison-1** [comment]
@mikehardy 

https://github.com/ankidroid/Anki-Android/pull/6692 and https://github.com/ankidroid/Anki-Android/pull/6691 don't seem to be cherry picked to 2.12.0

**Comment by freemedom** [comment]
这个似乎它就是想这样弄的（=´∇｀=） @Drrrrr519

**Comment by freemedom** [comment]
其实这个功能感觉没什么作用，你可以用那个预览
它这个是看的模板的预览

**Comment by Drrrrr519** [comment]
> 其实这个功能感觉没什么作用，你可以用那个卡片浏览器里的右上角预览
> 它这个是看的模板的预览(just note types 's preview,seems don t have specific content）

这个对我来说很有用。之前没升级前就很好用，我编辑笔记的时候可以立刻看到效果，不用往回点

**Comment by mikehardy** [comment]
@david-allison-1 you're right - that is odd, I'm not sure what happened with the cherry-picking to the release branch, I'll investigate. At any time I have 4-6 logical machines working on things and I must have driven things incorrectly (picked on one, released from another) - but I'll find out for sure. Either way, a 2.12.1 coming. @freemedom thank you for the report, we appreciate it

**Comment by david-allison-1** [comment]
Fixed in 2.12.1
