### ISSUE TITLE
AnkiDroid is breaking javascript

### ISSUE THREAD

**Issue by Radorion** [ankidroid/Anki-Android#6705]
###### Reproduction Steps

1.  This card works perfectly in Anki for PC, IOS and Web, it randomizes the answers in the front side.
2.  The correct answer must be in bold, it will make the highlight on the back of the card appear.
3. 

###### Expected Result

Works in the AnkiDroid app as it works in all other plataforms

###### Actual Result

The problem is that the bold highlight is not shown in the Anki app for Android (Ankidroid). Instead the front of the card randomizes, but the back put question in the "right" order and don't highlight the correct answer in bold.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

[Selected Notes.zip](https://github.com/ankidroid/Anki-Android/files/4949087/Selected.Notes.zip)

**Comment by david-allison-1** [comment]
Hi, thanks for the report.

Could you use https://github.com/SimonLammer/anki-persistence to persist the values between the front and the back of the card.

Please let me know if the above isn't a valid solution. Thanks!

Note: Duplicates #2868

**Comment by Radorion** [comment]
Don't have the techinical competence to try this, because I didn't write
the JS

Em seg, 20 de jul de 2020 14:24, david-allison-1 <notifications@github.com>
escreveu:

**Comment by david-allison-1** [comment]
Could you inform the author of the problem?

**Comment by Radorion** [comment]
Ok

Em sex, 25 de set de 2020 17:36, github-actions[bot] <
notifications@github.com> escreveu:
