### ISSUE TITLE
ankidroid.org uses the nginx standard welcome page

### ISSUE THREAD

**Issue by Arthus** [ankidroid/Anki-Android#6711]
###### Reproduction Steps

1. Open https://ankidroid.org/ in a browser

###### Expected Result
A nice frontpage
We could directly forward to the Google Play Store or have a small welcome page with a summary, what Ankidroid is and does, a link to the Play Store and a link to the documentation.

###### Actual Result
The nginx default Welcome page, actually saying "Further configuration is required."

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Good catch @Arthus 
I don't want to forward to areas outside of our control, and we are basically a product, we are the AnkiDroid app, so the most important thing we can show (which then links out to other things) is our manual

That was already present under docs.ankidroid.org or ankidroid.org/docs, so I just made the default nginx root `/` do a 301 redirect to docs
