### ISSUE TITLE
Menu order

### ISSUE THREAD

**Issue by JhonnySalles** [ankidroid/Anki-Android#6713]
In several updates the order of the menu is changed, which in addition to disturbing those who are already used to the established order, we have to learn to use the new order, which makes opening the wrong menu after updates.  please create a method of organizing the menu or add new features below what already exists.

![Screenshot_20200722-083611_AnkiDroid](https://user-images.githubusercontent.com/43912638/88171953-9aef7880-cbf6-11ea-9c73-751feef43bf2.jpg)

![Screenshot_2020-07-22-08-48-04](https://user-images.githubusercontent.com/43912638/88173175-857b4e00-cbf8-11ea-8d55-0d351ba74ac0.png)

###### Expected Result
maintain the order of the menus already launched, or create a way to organize the menu.

###### Actual Result
every time a new field is added, the order is changed and when opening a certain menu quickly, another is opened because it is not in the same position.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi,

`Settings - Reviewer - App Bar Buttons` should allow you to hide the new menu items that you don't want to see. Is this insufficient with the new additions?

**Comment by freemedom** [comment]
can disabled @JhonnySalles

**Comment by JhonnySalles** [comment]
I didn't know this configuration, I'll be using it.
Thank you very much.
