### ISSUE TITLE
Reviewer App Bar: Unable to disable many app bar items

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6717]
###### Reproduction Steps

1. Settings - App Bar Buttons
2. Disable Everything

###### Expected Result

3. All icons can be disabled

###### Actual Result

3. Edit Tags and Enable Whiteboard remain
4. When editing whiteboard, pen color and save remain

###### Debug info
2.12 and 2.13alpha

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by freemedom** [comment]
disable “Edit Tags" ， a bug，(´･_･`)

**Comment by david-allison-1** [comment]
Edit tags is due to a typo: ActionButtonStatus defines 

https://github.com/ankidroid/Anki-Android/blob/9b1cf82c7d140cd185f9b57f7dc3000f69982621/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java#L51

whereas the preference defines 

https://github.com/ankidroid/Anki-Android/blob/9ed9f425febcc4de5fe8120598277fb5803a332d/AnkiDroid/src/main/res/xml/preferences_custom_buttons.xml#L58

**Comment by david-allison-1** [comment]
Save Whiteboard and Pen Color are handled:

https://github.com/david-allison-1/Anki-Android/blob/fdadd0f6ef21863c7d8318e089b3d92320cc84d6/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java#L549-L550

**Comment by david-allison-1** [comment]
Enable Whiteboard does not have a preference in custom_buttons

@mikehardy I'd like to add this preference (Enable Whiteboard to `always|ifRoom|never|disabled`), but will keep the ability to disable whiteboard unconditionally.

**Comment by david-allison-1** [comment]
I'll add in the following unit tests, does anything else need to be added:

* App Bar Buttons keys match the preferences
* If all preferences are set to "never", then no menu items are visible.
  * If the whiteboard is visible, then only disable whiteboard is visible,
