### ISSUE TITLE
Wrong color display of card text

### ISSUE THREAD

**Issue by sjdhome** [ankidroid/Anki-Android#6720]
###### Reproduction Steps

1. set color for card text on Anki Windows

![1](https://user-images.githubusercontent.com/11871061/88249297-a1552180-ccd6-11ea-9827-9f7aa54520b6.png)

2. sync and open it on AnkiDroid

###### Expected Result

![批注 2020-07-23 112155](https://user-images.githubusercontent.com/11871061/88249331-c184e080-ccd6-11ea-86f7-458e9f963ff3.png)

###### Actual Result

![Screenshot_2020-07-23-11-17-36-318_com ichi2 anki](https://user-images.githubusercontent.com/11871061/88249337-c5186780-ccd6-11ea-8679-5f08e3097f62.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, thanks for the report.

This issue is linked in the manual:

> AnkiDroid contains a very basic color inverter that e.g. changes white to black and black to white when night mode is enabled. If you prefer to disable the inverter and setup your own colors, you should include a .night_mode class in your styling. For example, the following will use a dark grey background instead of black when night mode is enabled. Note that contrary to the other examples on this page there should not be a space between the .card and .night_mode classes:

https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#customize-night-mode-colors

How can we better document this so you can find it next time? What words did you use to search?

**Comment by sjdhome** [comment]
Well, that's my fault, but I think it should be consistent with the Windows version by default. Some people may not think it is related to night mode.
