### ISSUE TITLE
Make AnkiDroid resizable

### ISSUE THREAD

**Issue by alexanderadam** [ankidroid/Anki-Android#6726]
###### Reproduction Steps

1. Open AnkiDroid
2. Try to resize the window

###### Expected Result

It is resizing.

###### Actual Result

It is not.

###### Debug info

**AnkiDroid Version:** `2.11.3`
**Android Version:** `10`
**ACRA UUID:** `188bad92-bf7f-47f6-9171-0988a58670a3`

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### More details

I'm using [Samsung DeX](https://www.samsung.com/us/explore/dex/), which gives a desktop like experience and makes use of Android windowing support.

[Samsung has documentation on how to enable window resizing](https://developer.samsung.com/samsung-dex/modify-optimizing.html):

```xml
<application
    android:resizeableActivity="true">
</application>
```

This documentation also has more tweaks and information on how to improve the desktop experience in case you're interested.
They also have [an app testing guide](https://developer.samsung.com/samsung-dex/testing.html) (although some apps are fine with this guide but won't work on "real" DeX sometimes).

At the moment the resizing button is greyed out and AnkiDroid is always nearly squarish:

![Screenshot of AnkiDroid on Samsung DeX](https://user-images.githubusercontent.com/372620/88275585-e4ff5980-ccdd-11ea-8777-9390c808aa9f.jpg)

**PS:** I know that it is possible to _force_ all apps to be resizable via `Samsung Labs` > `Force Resize` but it would obviously better to make the application natively resizable to create less friction.

**Comment by Arthur-Milchior** [comment]
I tried AnkiDroid on a chromebook and was able to resize. But I did not use the button, only grabbed the size.
If you already know what change should be made, would you mind creating a Pull Request yourself please ?

**Comment by alexanderadam** [comment]
> I tried AnkiDroid on a chromebook and was able to resize. But I did not use the button, only grabbed the size.

I tried to do this as well and it works for nearly all proprietary apps but I don't work for AnkiDroid in my case.

> If you already know what change should be made, would you mind creating a Pull Request yourself please ?

I just searched for the documentation on that topic but I don't have an Android build chain on my machine. Therefore I will happily add this but I can't _test_ it.
Otherwise I would test your apk if you can make one with this change included.

What do you think?

**Comment by david-allison-1** [comment]
@alexanderadam I'd like to see this in, but it makes me hesitate.

There's a risk that there are going to be UI issues or bugs with this feature (adding resize functionality for software that wasn't originally designed for it typically does - it touches every screen). 

UI bugs are understandable, easy to spot, and can almost certainly be ironed out quickly, but issues such as operations being retried/cancelled during size changes seem more likely on the Android platform due to the app lifecycle.

I doubt there's going to be much coverage on this feature from either our alpha or beta testers. Combined with the fact that it's a fairly risky change, this leaves a fair risk of introducing UI bugs into production, which isn't ideal.

Could you think of any methods of ensuring that this change doesn't introduce issues? If nothing springs to mind, would you be willing to perform extensive testing of this feature to ensure that it's of suitable quality to release to production?

**Comment by alexanderadam** [comment]
> I doubt there's going to be much coverage on this feature from either our alpha or beta testers. Combined with the fact that it's a fairly risky change, this leaves a fair risk of introducing bugs into production, which isn't ideal.

Absolutely, I agree. If you want I will test it. Can you provide me an APK with that patch?

> Could you think of any methods of ensuring that this change doesn't introduce issues?

I'm not an Android developer, so I'm afraid that I can't answer that question.

Apps like [VLC](https://code.videolan.org/videolan/vlc-android) seem to resize fine and [it seems that they also have `android:resizeableActivity="true"`](https://code.videolan.org/videolan/vlc-android/-/blob/master/application/vlc-android/AndroidManifest.xml#L509) explicitly included. But obviously I can't tell whether this line alone is the reason why it is working or not.

Maybe @GeoffreyMetais (please forgive me for mentioning :pray:) knows more about this, because [he seem to have this introduced in VLC](https://code.videolan.org/videolan/vlc-android/-/commit/326474f62ded587469a6884043333fa2e56cf799#a83d0039595da3ead6f7172a7aab74d8fc3eba85_474_473)?

**Comment by mikehardy** [comment]
The point is that when you resize an Android app, it actually does the equivalent of killing the current screen activity and then restarting it. This process asks the activity to save it's state as it's killed, then restore it when re-vivified. That's the "app lifecycle" David mentions - though it's more precisely specified as "the android activity lifecycle". A comparison with VLC is then not that useful as this is not just app-specific but specific to each activity in the app, was it coded correctly for the app lifecycle?

The problem with AnkiDroid is that some of the Activities are not coded correctly for the app lifecycle, like #3654 

This is something we'd love to fix but it's a lot of testing effort and not something users generally care about, so as a volunteer app, it hasn't happened yet. It would be great if it did though, so this could be a big positive change for the app if someone took the list of activities from the AndroidManifest.xml file, and with that as a roadmap, used each one and tried it through the activity lifecycle to see if it met expectations

**Comment by alexanderadam** [comment]
So I tested Anki with the `Force Resize` mode and every time I resize it a message appears that says:

`To change the size of this app, it needs to be restarted. Make sure you've saved your data before restarting. If this app doesn't support landscape mode, it won't maximise correctly.`

![Screenshot of resizing AnkiDroid on Samsung DeX](https://user-images.githubusercontent.com/372620/88375819-9238a700-cd9c-11ea-92e1-0145d07ff29c.jpg)

And this message is localized depending what language I've set within Anki. So I guess this message comes from Anki itself.

This way I can't resize Anki by touching the corners and borders _but_ I can resize it via Maximize/Minimize button. Which is obviously better than before.
So everything would be fine if this XML setting has the same effect, right?

**Comment by GeoffreyMetais** [comment]
> > I doubt there's going to be much coverage on this feature from either our alpha or beta testers. Combined with the fact that it's a fairly risky change, this leaves a fair risk of introducing bugs into production, which isn't ideal.
> 
> Absolutely, I agree. If you want I will test it. Can you provide me an APK with that patch?
> 
> > Could you think of any methods of ensuring that this change doesn't introduce issues?
> 
> I'm not an Android developer, so I'm afraid that I can't answer that question.
> 
> Apps like [VLC](https://code.videolan.org/videolan/vlc-android) seem to resize fine and [it seems that they also have `android:resizeableActivity="true"`](https://code.videolan.org/videolan/vlc-android/-/blob/master/application/vlc-android/AndroidManifest.xml#L509) explicitly included. But obviously I can't tell whether this line alone is the reason why it is working or not.
> 
> Maybe @GeoffreyMetais (please forgive me for mentioning 🙏) knows more about this, because [he seem to have this introduced in VLC](https://code.videolan.org/videolan/vlc-android/-/commit/326474f62ded587469a6884043333fa2e56cf799#a83d0039595da3ead6f7172a7aab74d8fc3eba85_474_473) for the Picture-In-Picture mode for Android TV devices?

Hi

This is it, resizeable activity, but it defaults to true. You shouldn't have anything to do:
https://developer.android.com/guide/topics/ui/multi-window#configuring

So any activity is resizeable in VLC.

**Comment by alexanderadam** [comment]
> This is it, resizeable activity, but it defaults to true. You shouldn't have anything to do

This might be true in theory but it seems that it isn't for the configuration that Samsung DeX uses. Especially many FOSS applications that I tested doesn't seem to be resizable.
Applications like VLC, Firefox or Chrome are resizable whereas other applications aren't.

Or could it be that the apps are using API level 24 or lower? Because I'm experiencing the behaviour that's [written in the blue box](https://developer.android.com/guide/topics/ui/multi-window.html#:~:text=The%20system%20does%20not%20resize%20fixed-orientation%20apps;%20if%20the%20user%20attempts%20to%20open%20a%20fixed-orientation%20app%20under%20multi-window%20mode,%20the%20app%20takes%20over%20the%20whole%20screen.):

> The system does _not_ resize fixed-orientation apps; if the user attempts to open a fixed-orientation app under multi-window mode, the app takes over the whole screen.

**Comment by Arthur-Milchior** [comment]
I just installed AnkiDroid on a chrome OS. I can confirm that it is resizable, and that if you are on the answer side and resize, it goes back to question side.
I believe that, as long as resizing occurs rarely, that's better to be able to resize, even with a cost, than not to resize at all.

I do not know why Samsung DeX and chrome OS differ. However, it means that's going to be really hard to test for me, since I can't just install a version on my computer to check whether it works or not.

**Comment by alexanderadam** [comment]
> However, it means that's going to be really hard to test for me, since I can't just install a version on my computer to check whether it works or not.

In _theory_ Samsung has a test lab. But IMHO the only devices that allow to switch to DeX mode _without_ attaching an external screen, are the tablets. And somehow Samsung only provides a single DeX compatible tablet in their test lab and that is [the Galaxy Tab S4](https://developer.samsung.com/remotetestlab/rtlDeviceList.action#:~:text=Galaxy%20Tab%20S4). They're also describing [how to activate the DeX environment](https://www.samsung.com/sg/support/mobile-devices/how-to-use-samsung-dex-with-galaxy-tab-s4/) but it seems to be _deactivated_ for the devices of the test lab if I remember correctly.

However, I am happy to test anything if you tell me what I should try, click or use.

**Comment by mikehardy** [comment]
Seems like consensus is to manually set the variable in AndroidManifest.xml then, even though it should not be necessary, to allow AnkiDroid resize on mildly-non-compliant Android/ChromeOS implementations?

That's fine by me. There may be issues across Activity restarts, but that's a general problem we should slowly work to fix anyway

If someone PRd this I'd merge

**Comment by alexanderadam** [comment]
_still searching for solutions_
