### ISSUE TITLE
Decka not appearing in alphabetical order 

### ISSUE THREAD

**Issue by multilingualmarissa** [ankidroid/Anki-Android#6732]
###### Reproduction Steps

1. My decks are sorted by language, and I maybe have 3-5 decks per language  (ex: "German phrases", "German vocabulary", "French words from class" etc)
2. Naturally the language decks all cluster together alphabetically 
3. With the new update German is lodged in the middle of my French decks
4. Changing the deck names doesn't help, although with the update some decks had their names spontaneously changes. The space marks disappeared. (ex "German Phrases" became "GermanPhrases")

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
Would you mind sharing a screenshot ?
Are those examples literally how you wrote them ?

Spaces are supposed to be stripped at begin and end of deck, but not in the middle of the name. It's really not normal that you had the problem "GermanPhrases"

Could you please follow the instruction and give us the "debug info" ? If you use anki desktop, the version you use may be nice too

**Comment by david-allison-1** [comment]
Hi @multilingualmarissa, thanks for the report! 👍 

It'd be very useful to have a copy of your Anki data to diagnose this issue.

This is contained in the `/AnkiDroid/` folder on your phone.

Could you provide us with the oldest backup in the `backups` folder.

If you don't mind sharing your Anki collection publicly, the file can be uploaded here

*  Rename the file to .zip, or convert it to a zip file and upload it to a comment here.

If you have sensitive data in your Anki collection, you can email this to me:
* gmail: davidallisongithub

Thanks again,

David

**Comment by david-allison-1** [comment]
@multilingualmarissa any updates?
