### ISSUE TITLE
Sync via ADB: Ambiguous error: "Server busy. Try again later."

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6733]
Unsure it's intentional.

`adb shell am start -a com.ichi2.anki.DO_SYNC` was hard to get working, it brings up AnkiDroid, but produced a notification: "Offline/Server Busy". This implies a server problem, but was a local error

This is due to the following code

Maybe mention that it's an AnkiDroid rate limit, rather than implying that the server is busy.

https://github.com/ankidroid/Anki-Android/blob/bf1d5c3baa4a3bd76b5ead9851779c9c5ffd51f5/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DialogHandler.java#L123-L133

**Comment by mikehardy** [comment]
agreed - misleading error messages are a huge troubleshooting timewaster, +1 new string
