### ISSUE TITLE
DO_SYNC intent from CLI not syncing

### ISSUE THREAD

**Issue by dotancohen** [ankidroid/Anki-Android#6737]
###### Reproduction Steps

1. Connect and properly configure Android device for ADB.
2. `adb shell`
3. `am start -a com.ichi2.anki.DO_SYNC`

###### Expected Result

I expect the AnkiDroid sync dialogue to appear, and the associated syncing process to be performed.

###### Actual Result

The device changes to the homescreen, no matter if it was open to AnkiDroid or any other application. No notifications or toasts appear. This is the shell output:
```
$ adb shell
a50:/ $ am start -a com.ichi2.anki.DO_SYNC
Starting: Intent { act=com.ichi2.anki.DO_SYNC }
```

###### Debug info

```
AnkiDroid Version = 2.12.1
Android Version = 10
ACRA UUID = f31860c4-5af3-424a-845c-c44b28f571f2
```

###### Research

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum

###### Other

The device from which the Debug Info was taken is a [Samsung A50](https://www.gsmarena.com/samsung_galaxy_a50-9554.php) running AnkiDroid 2.12.1. I also tried with a [Barnes and Noble Nook 3 Plus](https://www.barnesandnoble.com/w/refurbished-nook-glow-light-3-barnes-noble/1127329365?ean=9780594777137) running AnkiDroid 2.11.2 and got the same results.

See related [Reddit thread](https://www.reddit.com/r/Anki/comments/hwz8ee/initiate_ankidroid_sync_via_adb/).

**Comment by david-allison-1** [comment]
Logcat output would be the most valuable at this point. The command worked on both my phone and an emulator

**Comment by dotancohen** [comment]
Interesting. Quoting the action results in Anki giving the notification "Server busy, try again later". This happens invariably, though during the time of testing I could press the Sync button in the Anki interface and it would work fine.

Logcat with the `com.ichi2.anki` tag did not seem to have anything relevant. The output below was printed *before* running the sync. Both sync in the app (successful) and sync from the CLI (unsuccessful) resulted in no further output.

```
$ adb --version
Android Debug Bridge version 1.0.39
Version 1:8.1.0+r23-5ubuntu2
Installed as /usr/lib/android-sdk/platform-tools/adb

$ adb logcat -s com.ichi2.anki
--------- beginning of crash
--------- beginning of main
--------- beginning of system
07-26 14:27:09.283  3460  3474 I com.ichi2.anki: Background concurrent copying GC freed 101028(3597KB) AllocSpace objects, 8(160KB) LOS objects, 49% free, 9497KB/18MB, paused 282us total 133.241ms
07-26 14:27:09.283  3460  3474 W com.ichi2.anki: Reducing the number of considered missed Gc histogram windows from 171 to 100
```

I'll upload the full, untagged logcat output, in case it has something tagged differently.

**Comment by mikehardy** [comment]
That sounds like the confusing error message @david-allison-1 just fixed here #6733 and that I'm about to build out in fresh release on the 2.13alpha series

**Comment by david-allison-1** [comment]
@dotancohen I've fixed the "Server Busy" error in https://github.com/ankidroid/Anki-Android/pull/6735, it should be improved in our next alpha.

It looks like syncing is working, and is just hitting an internal rate limit (one sync every 2 minutes).

**Comment by dotancohen** [comment]
Here is the full, untagged logcat output: https://termbin.com/jfuqu

**Comment by dotancohen** [comment]
Thank you, I'll test with the next Alpha.
Despite that, I did not sync for some time (much longer than the allotted two minutes) and then ran the quoted intention from the CLI. Same results as before, i.e. no sync but I get a notification "Sync cancelled" immediately.

**Comment by david-allison-1** [comment]
@dotancohen 

The logcat before a sync cancelled would be very useful - there's presumably something killing the task.

The instructions under https://dontkillmyapp.com/ may be helpful for you.

The two places that it can occur are:

https://github.com/ankidroid/Anki-Android/blob/a1d1fecc3ab2376d43c54ddd5fa44701a56125e2/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L1541-L1551

https://github.com/ankidroid/Anki-Android/blob/653b1f8681fbefc4945bf233407e61c69a4f2760/AnkiDroid/src/main/java/com/ichi2/libanki/sync/Syncer.java#L909-L919

**Comment by dotancohen** [comment]
I've retested this issue with AnkiDroid 2.13.3 on a Samsung A50.

In one terminal:
```
$ adb logcat -s com.ichi2.anki
--------- beginning of crash
--------- beginning of system
--------- beginning of main
```

In another terminal:
```
$ adb shell
a50:/ $ am start -a "com.ichi2.anki.DO_SYNC"
Starting: Intent { act=com.ichi2.anki.DO_SYNC }
a50:/ $
```

The device changes to the homescreen, no matter if it was open to AnkiDroid or any other application. Immediately the following notification appears

> "Sync error | Connetion timed out. Either your internet connection is experiencing problems, or you have a very large file in your media folder | java.net.ConnectException.Failed to connect to sync3.ankiweb.net/88.198.11.78:443"

The terminal with logcat show no further output.

Do note that the "Sync error" notification appears immediately. Furthermore, I can sync regularly with the sync button, so in fact there is no issue with the connection to the internet. I've tried with the device connected to wifi, and also to the cellular network data.

**Comment by dotancohen** [comment]
*In Ankidroid 2.14.1 on the Samsung A50 with AnkiDroid open:* `am start -a "com.ichi2.anki.DO_SYNC"` properly syncs!
*In Ankidroid 2.14.1 on the Samsung A50 with AnkiDroid closed and the lockscreen activated:* `am start -a "com.ichi2.anki.DO_SYNC"` properly syncs!

*In Ankidroid 2.14.2 on the B&N Nook Glowlight 3 with AnkiDroid open:* `am start -a "com.ichi2.anki.DO_SYNC"` does sync, then anki crashes and the device returns to the homescreen. There is no feedback that the sync is occurring, I only know that it synced because I see the changes when syncing another device.

**Comment by dotancohen** [comment]
There was nothing in logcat:
```
$ adb logcat -s com.ichi2.anki
--------- beginning of /dev/log/system
--------- beginning of /dev/log/main
```

**Comment by mikehardy** [comment]
Interesting. No knowledge of Nooks but it smells like the same area as https://dontkillmyapp.com - I wonder if there is some power management going on
