### ISSUE TITLE
Whiteboard: Pen color should hide the pen color icons if pressed again or if whiteboard disabled

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6744]
###### Reproduction Steps

1. Open Whiteboard
2. Whiteboard pen color
3. Whiteboard pen color

----

1. Open Whiteboard
2. Whiteboard pen color
3. Disable whiteboard

###### Expected Result

4. Pen color window disappears

###### Actual Result

4. Pen color window is still visible

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by infinyte7** [comment]
I will update it.
