### ISSUE TITLE
{unknown field invalid template} error on mobile Backcard

### ISSUE THREAD

**Issue by deadfriendly** [ankidroid/Anki-Android#6748]
###### Reproduction Steps

Im using this code on Win10 Desktop(works fine in Preview)
Front:
Satz. Cauch Schwarz Ungleichung mit Beweis
Back:
[latex]$\forall v,w\epsilon V$  gilt:
\begin{description}
\item[(i)] $|<v,w>|^2\leq <v,v>\cdot <w,w>$ 
\item[(ii)] $|<v,w>|^2=<v,v>\cdot <w,w> \Leftrightarrow$ v,w sind linar unabhängig
\end{description}
Beweis:(i):\\
$w\neq 0 \lambda:=\frac{<v,w>}{<w,w>} \Rightarrow 0\leq <v-\lambda w,v-\lambda w>$\\
$=<v,v>-\lambda<w,v>-\bar{\lambda}<v,w>+\lambda \bar{\lambda}<w,w>$\\
$=<v,v>-\frac{<v,w>\cdot \overline{<v,w>}}{<w,w>}-\frac{\overline{<v,w>}{<v,w>}}{<w,w>}+ \frac{{<v,w>}\overline{<v,w>}}{<w,w>}$\\
=$<v,v>-\frac{|<v,w>|^2}{<w,w>}$\\
(ii):\\
$"\Rightarrow"$ Nach (i) $v=\lambda w$ (positive definitheit)\\
$"\Leftarrow"$ Sei $v=\lambda w \Rightarrow |<v,w>|^2=|<\lambda w,w>|^2$\\
$=|\lambda|^2<w,w><w,w>=<\lambda w,\lambda w><w,w>=<v,v><w,w>$
[/latex]

###### Expected Result
Show this card on my Mobile App

###### Actual Result
Only shows the front and on the Back{unknown field invalid template} appears

###### Debug info
AnkiDroid 2.11.3
Android 8.0.0

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by freemedom** [comment]
Maybe it don't support this kind of code?

**Comment by deadfriendly** [comment]
other Latex code works fine
