### ISSUE TITLE
Progress: Anki Desktop Test conversion

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#6751]
Started in https://github.com/ankidroid/Anki-Android/pull/6708

Progress for each of the files, 

- [x] CardTest
  * 4/4 tests completed
- [x] ClozeTest
  * 0 tests completed
- [ ] CollectionTest
   * 3/6 tests completed
  - [ ] test_create_open
  - [ ] test_fieldChecksum
  - [ ] test_furigana
- [ ] DecksTest
   * 3/5 tests completed
  - [ ] test_rename
  - [ ] test_renameForDragAndDrop
- [ ] ExportingTest
  * 0/6 tests completed
  - [ ] test_export_anki
  - [ ] test_export_ankipkg
  - [ ] test_export_anki_due
  - [ ] test_export_textcard
  - [ ] test_export_textnote
  - [ ] test_exporters
- [ ] FinderTest
   * 2/3 tests completed
   - [ ] test_findCards (has TODO)
- [x] FlagTest
   * 1/1 tests completed
- [ ] ImportingTest
   * 0/11 tests completed
   - [ ] test_anki2_mediadupes
   - [ ] test_apkg
   - [ ] test_anki2_diffmodel_templates
   - [ ] test_anki2_updates
   - [ ] test_csv
   - [ ] test_csv2
   - [ ] test_tsv_tag_modified
   - [ ] test_tsv_tag_multiple_tags
   - [ ] test_csv_tag_only_if_modified
   - [ ] test_supermemo_xml_01_unicode
   - [ ] test_mnemo
- [x] MathJaxClozeTest
   * 0/0 tests completed
- [ ] MediaTest
   * 1/3 tests completed
   - [ ] test_add
   - [ ] test_deckIntegration
- [ ] ModelTest
   * 10/12 completed
   - [ ] test_chained_mods
   - [ ] test_req - has a TODO
- [x] NoteTest
   * 0/0 tests completed
- [ ] SchedTest
   * 22/28 tests completed
   - [ ] test_new_v1
   - [ ] test_newLimits_V1 (TODO: newCount getter)
   - [ ] test_overdue_lapseV1
   - [ ] test_cram (todo: which sort)
   - [ ] test_timingV1
   - [ ] test_reorderV1 (todo: sortcard)
- [ ] SchedV2Test
    * 28/37 tests completed
   - [ ] test_new_v2
   - [ ] test_newLimits_V2
   - [ ] test_reviewsV2 - todo hook
   - [ ] test_overdue_lapseV2
   - [ ] test_nextIvlV2 ⚠️ upstream is 10.8, try to understand the difference
   - [ ] test_filt_reviewing_early_normal - Investigate this difference, todo sort. #6932 (excl sort)
   - [ ] test_newLimits_V2
   - [ ] test_reorder -todo start 
   - [ ] test_initial_repeat
- [ ] StatsTest
   * 0/3 tests completed
   - [ ] test_stats
   - [ ] test_graphs_empty
   - [ ] test_graphs
- [x] TemplateTest
   * 1/1 tests completed
- [ ] UndoTest
   * 1/2 tests completed
   - [ ] test_op
- [x] UtilsTest
   * 0/0 tests completed

**Comment by Arthur-Milchior** [comment]
I don't understand what this means here. The checked values are the one you read yourself ? Those are the tests not entirely running without comment nor ignore?

**Comment by david-allison-1** [comment]
The unchecked tests are tests that require work, there's little point in listing all the tests which are already working

**Comment by Arthur-Milchior** [comment]
I believe there is one point, tracking the progress that we already made. That would be good for motivation :)

**Comment by mikehardy** [comment]
I'm here looking, but I'm not sure what action you want me to take - I have been hands off on this one but I'm okay with that, my position is that if you're okay with it David, please merge it. I trust you with it, and am excited to have the coverage increase, even if it's not perfect now

**Comment by david-allison-1** [comment]
@mikehardy I'm happy minus a few nits, but it's best to track the "remaining" portion of the tests - an issue seemed like the best place for it

**Comment by dae** [comment]
@david-allison is this still relevant?

**Comment by david-allison** [comment]
https://github.com/ankidroid/Anki-Android/labels/Won%27t-fix
