### ISSUE TITLE
Adding multiple images in a note simultaneously

### ISSUE THREAD

**Issue by abdrau26** [ankidroid/Anki-Android#6752]
I want to add multiple images in the back of a card simultaneously.
For example I want to add 10 images and I repeat the process 10 times. It is difficult, any possible solution please.

**Comment by freemedom** [comment]
> I want to add multiple images in the back of a card simultaneously.
> For example I want to add 10 images and I repeat the process 10 times. It is difficult, any possible solution please.

I sometimes need this feature, too

**Comment by mikehardy** [comment]
Someone is going to have to code this up. PRs happily accepted.

**Comment by david-allison-1** [comment]
I'd like this - not on my plate right now, but enough to keep backlogged

**Comment by david-allison-1** [comment]
Fields now support copy/paste (#7566) - I expect that fits this use case.
