### ISSUE TITLE
Cloze overlapper cards shown each day

### ISSUE THREAD

**Issue by fosslinux** [ankidroid/Anki-Android#6760]
###### Reproduction Steps

1. Install the Cloze Overlapper addon in desktop Anki.
2. Create a cloze overlapper card.
3. Review on desktop. Note that multiple cloze overlapper cards are shown on the one day.
4. Sync to mobile.
5. Review on mobile. Note that *only one* cloze overlapper card is shown per day, as with cloze cards.

###### Expected Result

The behaviour matches.

###### Actual Result

Anki desktop shows multiple cloze overlapper cards each day, while anki mobile only shows one cloze overlapper card each day.

###### Debug info
N/A, there is no crash.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) - I do not believe this is the case, because i can find no issues or commits about it.

**Comment by david-allison-1** [comment]
Hi @fosslinux, what version of AnkiDroid are you using?

**Comment by fosslinux** [comment]
> What version of AnkiDroid are you using?

2.10.4

>  Which Scheduler are you using?

V2, but the same behavior was exhibited in V1.

>  Does Anki Desktop exhibit the same behaviour if the addon is disabled?

Yes, precisely the same behavior as I observed in the original comment occurs.

> Could you upload a sample collection?

https://ttm.sh/QJm.txt (is actually a .colpkg)

**Comment by dae** [comment]
I believe that add-on overrides burying behaviour. You will need to adjust your deck options if you want it to work on the mobile clients.

**Comment by fosslinux** [comment]
Interesting, I wonder why it is then that when I disable the addon the same thing still seems to occur? Maybe this information is stored in the Note Type? 

> You will need to adjust your deck options if you want it to work on the mobile clients.

Is there any way to adjust the burying options per-card?

**Comment by dae** [comment]
https://github.com/ankitects/anki/pull/707

**Comment by fosslinux** [comment]
Nice
