### ISSUE TITLE
Increasing new card limit sporadically (rarely) fails.

### ISSUE THREAD

**Issue by vi** [ankidroid/Anki-Android#6769]
###### Reproduction Steps

(sporadically reproducible)

1. Start AnkiDroid 2.12.1.
2. Select a deck which has new cards to study, but configured to give 0 new cards per day.
3. Observe "Daily study limit reached [study more]" message below
4. Click at "[study more]"
5. Click at "Increase today's new card limit"
6. Observe a window like "New cards in deck: 33; Increase today's new card limit by: 8; [Cancel] [Ok]"
7. Tap "[OK]"

###### Expected Result

It goes into study mode, showing the first of the new cards.

###### Actual Result

It shows some message at the bottom instead. Maybe the repetition of "Daily study ... [study more]" message, maybe something else. I tried to reproduce it to see clearly, but failed to catch it this time.

The new card limit is not increased. I need to repeat inputting the number and it works from the second attempt.

###### Debug info

It seems to be happening since the last update or so. It was working well before.

 

###### Research

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @vi, that's strange, thanks for the report!

Could the message potentially be: "Congratulations! You have finished for now"?

If that's the case, there could be a negative number of new cards (as the limit can be both decreased and increased manually); the positive number which was added might not bring the limit above 0, therefore showing this message.

Does the above sound reasonable?

**Comment by vi** [comment]
I tried decreasing the limit while trying to reproduce the bug (actually found out that negative numbers now work - it was failing some years ago), but one of the time I remember just accepting a pre-entered positive number (such as 4 or 8) with OK button.

> Could the message potentially be: "Congratulations! You have finished for now"?

Maybe. I'll comment if I reproduce that again.

**Comment by david-allison-1** [comment]
@vi Thanks for the reminder! I've just improved the discoverability of reducing the study limit: #6771

I'm still confused by this, I can cause a problem if it's a large negative number, but I presume this isn't the case through normal usage of the app. Any further repro steps would be greatly appreciated.

**Comment by vi** [comment]
Meanwhile reproduced two more more times (the message is indeed "Congratulations! You have finished for now"). It may be related to clicking away from the number entry dialog (and returning back).

**Comment by vi** [comment]
Or maybe it's another issue: if I try to reduce the limit by too large number (i.e. entering `-5` there are only 4 new cards scheduled for study) then next time I try to increase the limit by 4 it ends up as "3" instead of "4" (remembering that "I need to study -1 new card"). I'd expect it to be capped at 0.

But as far as I remember, original bug didn't involve any negative numbers (unless I somehow misclicked and not noticed it).

**Comment by david-allison-1** [comment]
@vi Are you trying to increase the study limit of a subdeck? 

I can replicate this behaviour/issue in Desktop Anki (where the parent deck has the limit increased before the subdeck sees any changes), but not all the time.

**Comment by vi** [comment]
What is a subdeck? A non-toplevel deck in hierarchy with `::` path separators in the name? Or something like a "Custom Study Session"?

It is a regular-esque deck named "s::b::mury".

**Comment by david-allison-1** [comment]
> What is a subdeck? A non-toplevel deck in hierarchy with `::` path separators in the name? Or something like a "Custom Study Session"?
> 
> It is a regular-esque deck named `s::b::mury`.

A non-toplevel deck. Thanks!

**Comment by vi** [comment]
> A interesting side effect - you can go negative with number of cards to
review. For example if you have 1 new card to review you can decrease
this number by 5. It will display as if you had 0 cards to review, but
to get back to 1 you need to increase number of cards by 5 instead of 1.
Anki desktop behaves same way so I am leaving it as is.

Looks more like a bug rather than a feature.

**Comment by david-allison-1** [comment]
Possibly - but Anki Desktop appears to have the same behaviour, so it doesn't seem likely that it's causing this issue.

**Comment by Arthur-Milchior** [comment]
Which scheduler are you using please ?

Can you please let us know whether you did review any new cards in s, s::b, or in a subdeck of s::b::mury ? That would help reproducing the error to know whether anything was done to an ancestor or descendant of the deck you consider.

Would probably be nice to make a bug report to anki's forum if there is a bug upstream. I won't do it as I've not yet been able to test it myself.

**Comment by vi** [comment]
> Which scheduler are you using please?

Are there multiple ones? Probably the one that's default.

> ... whether you did review any new cards in ...

For such desks, I typically manually increase new card limit by the number I consider appropriate, then study them, then increase new card limit again, then study, etc. until the deck is done. I don't remember if the bug was on the first or non-first iteration.

On that day no other decks were reviewed as far as I remember. At least not the new cards.

> make a bug report to anki's forum if there is a bug upstream

Do you mean in Anki Desktop? I don't use Anki Desktop at all, so I don't know.

**Comment by Arthur-Milchior** [comment]
There is two schedulers. You can switch them in advanced options. I believe the scheduler by default is still number one. 

My question was: do you increase number of cards in the top level deck (the one without "::") or in the specific subdeck that you want to review ?

I did mean anki desktop yes. If you don't use it, I?ll look at it myself later

**Comment by vi** [comment]
I created the deck with AnkiDroid API (from a third-party app that imports from csv). By default all decks are configured to allow 0 new cards per day, so when I clicked on it it showed "Daily study limit reached" with a helpful button to reach the limit increaser, which I used.

I don't remember ever using hierarchical nature of decks for algorithmical reasons. I only use those `::`-containing names for have collapsible folders in main deck list (there are too many decks to reasonalby scroll though all of them). For me AnkiDroid decks are logically like a separate AnkiDroid app instances which are not supposed to interact.

---

Maybe [this](https://github.com/ankidroid/Anki-Android/issues/6769#issuecomment-665990162) needs to be resolved first (at least just in AnkiDroid, maybe in upstream as well)? If the problem persists after getting rid of negative limits then the issue can be reopened. Shall I create a separate issue for tracking fixing the negative new card limit?

**Comment by vi** [comment]
Found a stable way to reproduce:

1. Configure Anki to have 0 new cards per day by default;
2. Create new deck with cards, using AnkiDroid API or just manually (add a new deck, then add some cards into it). I use nested names like `x::y::z` for almost all decks;
3. Click at the newly created deck in main deck list.
4. "Daily study limit reached [study more]"
5. Tap "study more"
6. "Increated today's new card limit"
7. For example, "4" new cards. "[OK]"

Expected:

It begins studying those 4 new cards.

Actual:

Very briefly empty studying view (or something like that) blinks though. Then "Congratulations! You have finished for now".

Deleting and reimporting the deck makes it reproducible again.

**Comment by mikehardy** [comment]
@vi nice! Thanks for that reproduction case, those are critical

**Comment by Arthur-Milchior** [comment]
"newly created deck"

I assume you mean x::y::z ?

**Comment by Arthur-Milchior** [comment]
1. Configure Anki to have 0 new cards per day by default;
1. Create deck x::y::z
1.Add 5 cards in it
1. Click at x::y::z
1. "Daily study limit reached [study more]"
1.Tap "study more"
1."Increated today's new card limit" by 1
1. "[OK]"

It opens the reviewer and I start reviewing.

It works on my emulator, with 2.12.1.
It also works if I click on x instead of x::y::z
It works in both sched

Can you maybe send us your collection just before and just after you increase the number of card today. Maybe it'll be easier to understand why it is different on your phone and on mine if I can see more details.
