### ISSUE TITLE
SchedV1: Undo does not reset new count

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6770]
###### Reproduction Steps

1. 3 cards available
2. Study a new card, flip and answer good
3. 2 cards available
4. Undo

###### Expected Result

5. 3 cards are in "new"

###### Actual Result

5. 2 cards are in "new"

###### Debug info
2.13alpha7

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
I can't reproduce on master. I tried creating 3 cards, checking I'm in sched V1, reviewing one, undoing. The number of new cards is 2

**Comment by Arthur-Milchior** [comment]
I installed alpha 7 back and still can't reproduce.

I don't really know what to say. Seems hard to debug without being able to reproduce. I would like to ask you to double check. In particular, was it a new collection or a collection already containing a lot of data ? Can you find some conditions that ensures that it works on one collection that does not work on a new collection with only three cards ?

**Comment by david-allison-1** [comment]
Ah! You're right!. This could be due to the fact that the 'new' study limit was increased from 0 to 6

Attached file:
[6770.zip](https://github.com/ankidroid/Anki-Android/files/5012162/6770.zip)

* new collection
* Close Anki
* unzip
* rename to collection.anki2
* replace collection.anki
* Open Anki
* 6 cards are left
* Select Default
* Flip + Good
* Undo 
* 5 cards are left

**Comment by Arthur-Milchior** [comment]
In the collection you sent me, the deck option of "Default::aa" indicates that there is a limit of 0 new card by day. So it's not normal at all that there are 6 new cards shows to be due today. It seems that at some point we break the application of the limit of new card by day. I probably did it. 
I now understand why I could not reproduce your error, it is actually just a side effect of the real current problem !

Another question I have is: why does it show 6 new cards due while they are 7 new cards.  This seems related to your remark 
>the 'new' study limit was increased from 0 to 6

But I don't know where you did this increase, I can't find any 6 anywhere in the code

**Comment by Arthur-Milchior** [comment]
Okay, I now understood that you increases "today limit" of the default deck.

**Comment by david-allison-1** [comment]
@mikehardy Could we also add this to 2.12.X? Or are we planning a fairly fast 2.13?

**Comment by mikehardy** [comment]
@david-allison-1 master is of course a bit nutty right now, so probably a 2.12.2 vs a 2.13 if needed but I wasn't aware this affected 2.12? Even if so with all the master change I'm not sure it will be pickable

Anyway first important question: Does this actually affect release-2.12 or not? I'll check the rest based on knowledge there, and if not pickable then we can focus on stability for a day or three on master and go for a release branch cut. Plenty in it now

**Comment by david-allison-1** [comment]
Oh lord, sorry, completely misread the issue. Ignore me
