### ISSUE TITLE
Adding "pause" audio to AnkiDroid

### ISSUE THREAD

**Issue by mnhende2** [ankidroid/Anki-Android#6774]
I'd love to see the pausing of audio added to AnkiDroid.  It is now included in both the Desktop version of Anki and in AnkiMobile.  It had previously been accepted and given medium-priority as issue 1328 (https://github.com/ankidroid/Anki-Android/issues/1328), but because of inactivity was closed.

**Comment by mnhende2** [comment]
Just keeping this active (so that it doesn't auto close).

Wishing I had programming skills to help, but just hoping that someone else who does will consider adding in this feature to make it compatible with the desktop and AnkiMobile versions.

**Comment by mnhende2** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    Still hoping that someone with the skills
        will be able to develop this feature to make AnkiDroid to have
        the same feature as the desktop and AnkiMobile versions.
    
    [

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/ankidroid/Anki-Android/issues/6774#issuecomment-767528604",

"url": "https://github.com/ankidroid/Anki-Android/issues/6774#issuecomment-767528604",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by Wizek** [comment]
I'm also curious for this. Especially for when someone is learning long sentences instead of short words.

**Comment by mrudultora** [comment]
Would a play/pause button in Reviewer is Ok ? If yes, I would like to work on it.

**Comment by david-allison-1** [comment]
How does Anki Desktop do this?

**Comment by mrudultora** [comment]
In Anki Desktop, the audio can be paused from going to **More->Pause Audio** or with **number 5** from keyboard.

![img](https://user-images.githubusercontent.com/65870389/112453816-143efc80-8d7e-11eb-8abe-383b92a2a38a.png)

**Comment by mnhende2** [comment]
I think that AnkiMobile (the iPhone version) just has a pause/play button.  So, I think that same solution would work in AnkiDroid.

**Comment by mikehardy** [comment]
@Abanoub-Asaad take note of #8346 - it was an attempt to do this but had some difficulty with multiple audio files, otherwise was working? Not sure what final resolution should or would be but that is the current state of the art

**Comment by Abanoub-Asaad** [comment]
I will work on it. 

But that's great, I thought that there's no pause button on Anki Desktop. And now I've found the opposite here.

**Comment by Abanoub-Asaad** [comment]
Where's the XML file that has the "replay" icon? 
I've tried a lot to find it, but I haven't reached this file yet.

**Comment by mrudultora** [comment]
There's no XML for that. It's placed through HTML code. Have a look at closed PR. You can find the relevant code in `Sound.java`.

**Comment by snowtimeglass** [comment]
This issue was closed once as completed in #8781, but the situation has been changed by #14296. So, this issue has reemerged.

@david-allison How about reopening this issue as you mentioned in the 'Fixes' section of the PR #14296.

> ## Purpose / Description
> This was changed in #8781 to add 'pause' functionality But, this was not the default, the default was 'replay'
> 
> ## Fixes
> * Reopens [Adding "pause" audio to AnkiDroid #6774](https://github.com/ankidroid/Anki-Android/issues/6774)
> * Fixes [[BUG] Clicking the audio play button results in a pause, rather than a replay #14221](https://github.com/ankidroid/Anki-Android/issues/14221)
