### ISSUE TITLE
Detecting Network Interface (WiFi/Mobile Data) from JS API

### ISSUE THREAD

**Issue by shnurks** [ankidroid/Anki-Android#6783]
Suggestion:
I think it would be great to make the network interface accessible via the JS API

Use case:
It would make loading smaller images or preventing the download of videos from the internet (like YouTube) to save data on metered connections much easier.

**Comment by mikehardy** [comment]
The next alpha of 2.13 (should be 2.13alpha10) will have this - note that it does not detect the interface type, the real question here is whether a network is metered, and it will detect and report that, thanks to @david-allison-1
