### ISSUE TITLE
Show line breaks instead of <br> tag 

### ISSUE THREAD

**Issue by user655362020** [ankidroid/Anki-Android#6795]
This might not be a bug but a feature request.

###### Reproduction Steps

1. Turn on frozen field in anki desktop.
2. 
![Screenshot_20200802-145046](https://user-images.githubusercontent.com/66375825/89120117-4c34bf00-d4d1-11ea-97e7-d78fecea890e.jpg)
3. Save

###### Expected Result
![Screenshot_20200802-145046](https://user-images.githubusercontent.com/66375825/89120140-7edeb780-d4d1-11ea-81b1-2b784ee1d4be.jpg)

###### Actual Result
![Screenshot_20200802-145112](https://user-images.githubusercontent.com/66375825/89120126-5fe02580-d4d1-11ea-9537-06eb2f2014a2.jpg)

###### Debug info
AnkiDroid Version = 2.12.1

Android Version = 7.1.1

ACRA UUID = ebad227a-b6fd-4ea6-a461-ac0a85cc6441

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, thanks for the report! I think we're already tracking this as #3304

**Comment by freemedom** [comment]
> > Hi, thanks for the report! I think we're already tracking this as #3304
> 
> That issue is about ankidroid adding new `<br>`. This one is about ankidroid not rendering line break and instead showing `<br>` tags in add card fields when frozen field is used.
> 
> Line breaks are rendered (no `<br>` tags) when I edit the same card in the card editor. But when I save card in add card window then line breaks are not rendered and `<br>` tags are shown instead with frozen fields.

I don't have that problem here
<br> tags are rendered.

**Comment by user655362020** [comment]
Notice after I save.
![20200804_133153883](https://user-images.githubusercontent.com/66375825/89270350-d8bdb980-d658-11ea-8f9d-e0e18eb9f4aa.gif)

But in the card edit screen (Card browser -> Click the card) line breaks are rendered.
![Screenshot_20200804_124822](https://user-images.githubusercontent.com/66375825/89270461-ff7bf000-d658-11ea-910a-79bfa69522f6.jpg)

**Comment by freemedom** [comment]
> Notice after I save. (Frozen fields enabled in desktop)
> ![20200804_133153883](https://user-images.githubusercontent.com/66375825/89270350-d8bdb980-d658-11ea-8f9d-e0e18eb9f4aa.gif)
> 
> But in the card edit screen (Card browser -> Click the card) line breaks are rendered.
> ![Screenshot_20200804_124822](https://user-images.githubusercontent.com/66375825/89270461-ff7bf000-d658-11ea-910a-79bfa69522f6.jpg)

It seems strange that I don't have this kind of situation here,

In my ankidroid, after "1 card added", the input words are gone (front and back)

**Comment by david-allison-1** [comment]
I've put a fix in. It's in review currently and should be in 2.13alpha 11 or 12

You need to:
* Manage Note Types - Select Note Type - Long touch field - Remember Last Input When Editing

**Comment by freemedom** [comment]
> * Manage Note Types - Select Note Type - Long touch field - Remember Last Input When Editing
I've never used this featureo(*￣▽￣*)o
