### ISSUE TITLE
[Feature Request] Remember last used tags after exiting from add card screen

### ISSUE THREAD

**Issue by user655362020** [ankidroid/Anki-Android#6796]
###### Reproduction Steps

1. Enter add card screen
2. Select some tags
3. Go back to decks screen
4. Go to add card screen again

The previously selected tags are not selected anymore. An option to remember previously selected tag (just like the editor remembers previously used card type). Also a button to clear all currently selected tags

###### Debug info
AnkiDroid Version = 2.12.1

Android Version = 7.1.1

ACRA UUID = ebad227a-b6fd-4ea6-a461-ac0a85cc6441

**Comment by mikehardy** [comment]
Does Anki Desktop do this? (can you check?)

I recognize it would be nice to have but especially as a criteria for adding new features we try to mirror Anki Desktop

**Comment by user655362020** [comment]
No. It does not. But does desktop version really need it ? On desktop version, when adding cards, when I need to check if a similar card exists, I can just open the card browser without closing the add card window (So I retain the list of tags). But on ankidroid when I move away from add cards screen to card browser and return back I lose the tags.

**Comment by mikehardy** [comment]
Thanks for the context @user655362020 - you make a valid point, while we try to stay as close to Anki Desktop as possible, unavoidable platform differences (like the difference between having a multi-document interface like desktop apps vs single screen like mobile) are valid reasons to depart from desktop and include something.

Any napkin sketches of UI? For instance, should there be a preference to disable it? if there is a preference should this be the default?

This is actually non-trivial to add now that I think about it - remembering things across different activities in an android app means you have to store them somewhere, so this is actually asking to create new storage (clearing it under what conditions? never? based on preference? time? across app restart?) to provide the previous state

**Comment by freemedom** [comment]
Perhaps across App Restart would be appropriate.

Many times I find that editing cards notes  on desktop may be a good choice .
i find many features are not available and not convenient on Android and development is time-consuming(After all, it's free. I can't expect too much）

**Comment by mikehardy** [comment]
There's ample developer time going into AnkiDroid right now free or not, but mobile devices just aren't desktop. For heavy editing desktop is always going to win

**Comment by freemedom** [comment]
> There's ample developer time going into AnkiDroid right now free or not, but mobile devices just aren't desktop. For heavy editing desktop is always going to win

Yes, but computers are not easy to carry sometimes, so sometimes it‘s a trouble.

In addition , can you see if this feature suggestions is easy to develop if you have free time?（Anki Desktop don't have this,but that's because desktop anki can see the content of the image directly, and Ankidroid can't see the image directly in "Edit note"）

**Comment by user655362020** [comment]
> Any napkin sketches of UI? For instance, should there be a preference to disable it? if there is a preference should this be the default?

Yes, A preference to disable it. And disabled by default. 

> This is actually non-trivial to add now that I think about it - remembering things across different activities in an android app means you have to store them somewhere, so this is actually asking to create new storage (clearing it under what conditions? never? based on preference? time? across app restart?) to provide the previous state

The prefrerence to enable/disable "Remembering the tags" could have multiple options and only one can be selected. Something like this : 
![20200804_140119](https://user-images.githubusercontent.com/66375825/89271980-1cb1be00-d65b-11ea-85d3-c6b3cafb17a9.jpg)

The selectable options could be : 
* Disabled
* Clear tags on exit
* Remember forever (Persist across restart)

A "clear tags" button (Basically an "uncheck all" button like the already existing "select all" button) in the tag selection screen for those who use many tags to quickly clear remembered tags.It May not be revelant if using few tags. Maybe we can just press the "Select all" button twice to clear everything.  

And it would be nice if the "Remembering tags" behaviour is similar to "Card Type" field. It remembers card type per deck (Different card type remembered for different decks).

**An example use case :**
I use tags for chapter/topic names so that I can create filtered deck. 

I have multiple decks for each subjects/courses so if tags are remembered I do not need to enter tags as long as I am reading the same chapter/topic. Further if tags are remembered per deck I do not need to change the tag (the chapter/topic name) when switching between decks (different subjects/courses).

**Comment by mikehardy** [comment]
It does not seem like an easy feature to develop, but volunteers are motivated by whatever motivates them and perhaps you or someone else will implement it. PRs are usually happily accepted. We'll see if it generates interest

**Comment by user655362020** [comment]
still searching for solutions
