### ISSUE TITLE
Feature: View console log in previewer

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#6810]
###### Reproduction Steps
It will be useful to have option to view console log. It will  help in debugging without chrome desktop. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Design ideas/thoughts:

Could we use a debug flag in the Javascript API - any later errors for the card would notify the user in a snackbar with a "View Details" button?

Is there a use case where you'd want to retain the errors from a previous card, or should they be cleared when an answer is made?

We need to buffer/limit the logs, or the WebView can OOM the application. 

Whatever we do, consider a `StringBuilder` to speed up the process.

@infinyte7 What are you thoughts, where do you see problems with the above, and what would you prefer?

**Comment by infinyte7** [comment]
I like the idea. It should be in JavaScript API. But showing snackbar will be not be useful for non technical person. The log mainly used for debugging. 
My idea:
Pop up console log when a button element in HTML call the javascript api ```consoleLog``` function.

For limiting the buffer/limit logs what would be ideas?

**Comment by david-allison-1** [comment]
If we had a `enableDebugMode()` call, or passed a debug flag into `init()` then we'd be fine to show a "card developer mode enabled" toast, and a snackbar on error without impacting normal users. 

Console log could also work - which would be easier for you?

----

A circular buffer of the last X lines (50?) is generally the way to go. It seems we don't have access to one in standard Android (and it doesn't seem we have a library, but they're trivial to write if you don't care about thread safety).

**Comment by infinyte7** [comment]
I have implemented following:-
when calling ```ankiJsConsoleLog()``` boolean parameter passed. If ```true``` then show snackbar with message ```debug mode enabled``` and action ```view```. 
When ```view``` clicked then show ```alert dialog``` with console log of current cards. 
When next card load then console log reset.

But knowing number of errors in advance will help in showing log to alert dialog.

**Comment by david-allison-1** [comment]
All sounds good! Thanks for the discussion, let's move this back to the PR
