### ISSUE TITLE
[Feature Reaquest] "Add card" from android quick access

### ISSUE THREAD

**Issue by x41lakazam** [ankidroid/Anki-Android#6817]
Hi, it happens a lot that I'm reading a text in another language and find a word that I don't know. To add it to AnkiDroid I need to copy it, open ankidroid, go to Add Card and paste it. It would be great if there was a shortcut in the dropdown menu (the one that is displayed when a word is selected) to directly add a card.

There is already a shortcut for "Card browser", which is a good shortcut to the application, but having a real shortcut to the Add Card feature would be really great.

Bonus: it can use translation api to automatically add a translation for the world in the "answer" field.

Thanks a lot.

**Comment by freemedom** [comment]
https://coolapk.com/apk/com.mmjang.ankihelper 
look this，maybe could solve

**Comment by david-allison-1** [comment]
Hi @x41lakazam, Thanks for the report!

You can currently do this via Share -> Anki Card.

I considered adding this, but had feedback a couple of days ago that this wouldn't add any benefit over the above method (it's two clicks either way).

Do you feel it'd be better as a context menu item?

All the best,

David

**Comment by x41lakazam** [comment]
@freemedom looks great, thanks

**Comment by x41lakazam** [comment]
@david-allison-1 hey, thanks ! Didn't know about this way, very useful.
I still feel that this feature worth a context menu (to create a card even quicker), but less a priority now, this Share button is also doing the job.

Thanks a lot.
