### ISSUE TITLE
Preview: Newlines not converted to line breaks

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6834]
###### Reproduction Steps

1. Add Note
2. Enter "aa\naa" (where \n is a literal linebreak)
3. Preview

###### Expected Result

4. aa(newline)aa

###### Actual Result

4. aa aa

###### Debug info
2.12, also in latest alpha

**Comment by mikehardy** [comment]
Related #6460

**Comment by david-allison-1** [comment]
I'd close this as a duplicate, but already referenced it in a change
