### ISSUE TITLE
New screenshots of AnkiDroid for play store.

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#6844]
I have created Screenshots of AnkiDroid for play store.

It can be downloaded from:
https://github.com/infinyte7/AnkiDroid-Screenshots

<div style="display:flex;" >
<img  src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/create.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/add_note.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/learn.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/review_note.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/statistics-1.png?raw=true" width="19%" >
</div>

<div style="display:flex;" >
<img  src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/edit.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/flag_notes.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/night_mode.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/custom_design.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/premade_decks.png?raw=true" width="19%" >
</div>

<div style="display:flex;" >
<img  src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/whiteboard.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/statistics-2.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/edit.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/card_browser.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/change_background.png?raw=true" width="19%" >
</div>

**Comment by mikehardy** [comment]
Clean + beautiful! I'll get these up as soon as I can, thanks so much @infinyte7

**Comment by david-allison-1** [comment]
Thought I commented previously, tab must have closed.

These look great!

* We could show a subdeck in one of the screenshots
* "Edit" appears twice - maybe "Check Pronunciation" in the reviewer if we want to replace it.
* Might want to use "Browser Appearance" (Under the Card Template Editor) to make the Card Browser screenshot look nicer less busy

**Comment by mikehardy** [comment]
Only 8 screenshots are allowed, FYI - if you wanted to pick your favorites

https://support.google.com/googleplay/android-developer/answer/1078870?hl=en

**Comment by infinyte7** [comment]
I will update add note and card browser.

**Comment by infinyte7** [comment]
> Only 8 screenshots are allowed, FYI - if you wanted to pick your favorites
> 
> https://support.google.com/googleplay/android-developer/answer/1078870?hl=en

- Create
- Learn
- Review
- Statistics  (Graph)
- Whiteboard
- Flag Note
- Night Mode
- Premade Decks

**Comment by infinyte7** [comment]
Three new updated 

<div style="display:flex;" >
<img  src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/learn.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/create.png?raw=true" width="19%" >

<img style="margin-left:10px;" src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/card_browser.png?raw=true" width="19%" >

</div>

**Comment by infinyte7** [comment]
Also this one should be included.

<div style="display:flex;" >
<img  src="https://github.com/infinyte7/AnkiDroid-Screenshots/blob/master/Mockups-Background/decks.png?raw=true" width="19%" >
</div>

But it becomes 9th images.

**Comment by mikehardy** [comment]
Okay - I put that one up in place of 'Learn' had some overlap with review, and we're limited to 8

It will take a while before their servers are in sync with the changes but I've made them and hit the save button for the listing, so it should work and show up in the next hour or three? :crossed_fingers: 

https://play.google.com/store/apps/details?id=com.ichi2.anki

Thanks!
