### ISSUE TITLE
Lost my cards because "the collection isn't open"

### ISSUE THREAD

**Issue by asphoden** [ankidroid/Anki-Android#6845]
###### Reproduction Steps

1. Check data basis
2. Reset from a saving
3. full synchronization from the server version

![Screenshot_2020-08-07-13-47-33-424_com ichi2 anki](https://user-images.githubusercontent.com/69350129/89642708-942e5a00-d8b4-11ea-8375-1c544efa78fd.jpg)

###### Expected Result

Remove this message.

###### Actual Result

Nothing.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.12.1

Android Version = 10

ACRA UUID = efed454d-5d7a-4308-87f9-703079623808

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @asphoden, did you resolve this?

**Comment by asphoden** [comment]
Hi, I didn't resolve this issue. Thanks.

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., août 7, 2020 à 14:39, David Allison<notifications@github.com> a écrit :   


Hi @asphoden, did you resolve this?

**Comment by david-allison-1** [comment]
@asphoden Just to note for future: closing an issue implies that it's been resolved.

First, could you go into the `AnkiDroid` folder on your phone and take a copy of the folder. This contains backups, which will be vital if we can't correct the problem with your collection.

Second, could you click "Options" and try the "Check Database" option

If that doesn't work, could you let me know and we'll do some more investigation

Thanks,

David

**Comment by asphoden** [comment]
I'm sorry, I don't understand properly english and GitHub so I made a mistake.
I already check database and it didn't work actually.
How can I copy it ? There is only this screen (sorry this is in French)




Envoyé depuis Yahoo Mail pour Android 
 
  Le ven., août 7, 2020 à 15:29, David Allison<notifications@github.com> a écrit :   


@asphoden Just to note for future: closing an issue implies that it's been resolved.

First, could you go into the AnkiDroid folder on your phone and take a copy of the folder. This contains backups, which will be vital if we can't correct the problem with your collection.

Second, could you click "Options" and try the "Check Database" option

If that doesn't work, could you let me know and we'll do some more investigation

Thanks,

David

**Comment by david-allison-1** [comment]
Use your phone's file picker, or connect to your computer and copy the AnkiDroid folder.

After that, inside the AnkiDroid folder, you will find `collection.anki2`.

This file contains all of your Anki Data.

Could you either convert this into a `.zip` and upload it here: https://github.com/ankidroid/Anki-Android/issues/6845

Or email it to me: `[gmail: davidallisongithub]`. 

Please let me know if you don't understand.

**Comment by Arthur-Milchior** [comment]
I'm French, so if at some time it's too complex, mention me so that I can try to help in my mother tongue.
Si l'anglais est pas compréhensible, mentionnez moi que je prenne la suite. Le français étant ma langue maternelle, ça peut être plus simple. Quoi que j'ai pas trop l'habitude de gérer la récupération des cartes
