### ISSUE TITLE
Red dot on sync button appears after every review session

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#6856]
###### Reproduction Steps

1. Press the sync button to sync your collection
2. Review some cards for around 10 minutes

###### Expected Result

The red dot on top of the sync button doesn't appear since I just synced some minutes ago.

###### Actual Result

The red dot on top of the sync button appears again. 

For me that's really an issue cause red dots in any of my apps are kind of distracting and/or alarming and I immediately feel the need to interact with it in order to stop it. But since I don't want to sync after every review session I'd appreciate if there was an option to set a time limit for the dot to appear (i.e. choose from 1 to N days) or to turn it off completely.

###### Debug info
AnkiDroid Version = 2.13alpha12

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
That starts to stray into the intractable "auto-sync / when to auto-sync" territory and has no good solution.
Right now it is is very direct indicator that you have local change and are at risk of data loss, no more, no less.
How you handle that information (which is good to have) is up to you

It is possible that the color could be less alarming, but making the indicator "fuzzy" (maybe there's local change but a timer ticking? how is that actionable?) is not what I would do 

I'll leave this open to see if anyone else chimes in, but for me a reliable "risk of potential data loss" indicator is a positive step and I have positive user feedback counter to yours already from live users in my household :)

**Comment by Anthropos888** [comment]
I'm sure that some users find it very useful, but for me it's really annoying to see that red dot every time I open the app. And since I'm on limited data for the next days, I'm not gonna press that button to sync my media. And other users might have hundreds of other reasons why they don't want to sync and are being annoyed by that unrequested notification. Potential loss of data is out of question because Ankidroid stores several backups by default.

One solution could be to add the sync button to the "app bar buttons" setting so that users can choose if they want to see that button. But I personally would prefer an option that gives the user a choice "show sync reminder (y/n)"

**Comment by mikehardy** [comment]
@david-allison-1 first request for the disable-the-sync-notice pref ;-)

**Comment by david-allison-1** [comment]
Called it 😉. Where's best in Settings? AnkiDroid would be good for me, but it's already fairly crowded

**Comment by mikehardy** [comment]
Feature coherency tells me it should be in the same place you configure syncing (custom sync server etc) all that

**Comment by mikehardy** [comment]
"There's no coherency", a 5-part play starting AnkiDroid preferences 😅 

I vote for the AnkiDroid one, not the Advanced one. This will be a common request, not an advanced one.

**Comment by Anthropos888** [comment]
Yes, the "AnkiDroid" setting has a sub setting "sync" and that would be a good place.

**Comment by Anthropos888** [comment]
Thanks @david-allison-1 The new setting works perfectly fine
