### ISSUE TITLE
Card Browser doesn’t remember scroll position after editing card

### ISSUE THREAD

**Issue by saarl** [ankidroid/Anki-Android#6857]
###### Reproduction Steps

1. Open the Card Browser.
2. Scroll down and tap on a card low on the list.
3. Edit the card and tap the “Save” (check mark) button.

###### Expected Result

The card list should appear in the same scroll position from which I tapped on the card, with the edited note visible. This is how it used to work before.

###### Actual Result

The top of the note list is shown, such that, if I want to edit multiple notes in a row, I'm made to scroll down every time.

###### Debug info

AnkiDroid Version = 2.12.1

Android Version = 9

ACRA UUID = 869df53d-5443-4c1e-86cf-3fa599383fc6

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Would be a nice quality of life improvement

Does not seem to be too difficult: https://stackoverflow.com/a/36569778/9910298

**Comment by david-allison-1** [comment]
@saarl  Thanks for the report! 

Was this broken recently?

**Comment by saarl** [comment]
I first ran into this today, but it's been three weeks or more since I've edited a note from the card browser in my phone, so I don't really know. I'm pretty sure it worked as intended until about a month ago or so, though.

**Comment by mikehardy** [comment]
Mmmmm as Chief Dependency Officer (tm) there's a slight possibility the material library or appcompat library updates caused it. Material was recent and might have had significant changes, unknown? appcompat last had ...material (ahem) changes a while back though

**Comment by freemedom** [comment]
I tested 2.10.4. it without this bug.
