### ISSUE TITLE
Wrong due time displayed when more than 1h29min due time left

### ISSUE THREAD

**Issue by mileix** [ankidroid/Anki-Android#6894]
###### Reproduction Steps
Have (at least) 1h30min due time left.

###### Expected Result
1h30min displayed

###### Actual Result
2h30min displayed

###### Debug info
AnkiDroid Version = 2.12.1
Android version = 10

###### Research
- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))
It seems to systematically happen when there is (really) more than 1h29min due time left.
![Screenshot_1_AnkiDroid_2_12_1](https://user-images.githubusercontent.com/69716157/90310803-628d4280-def5-11ea-8899-9694a66b6b32.jpg)
![Screenshot_2_AnkiDroid_2_12_1](https://user-images.githubusercontent.com/69716157/90310805-691bba00-def5-11ea-8c68-fbda4d8fc2c3.jpg)

**Comment by david-allison-1** [comment]
Thanks for the report! Will get this fixed in the next alpha
