### ISSUE TITLE
Porting upstream "empty cards"

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#6896]
I want to discuss whether we follow upstream change of "Update cards".

There have been three differences. 

A checkbox allows to keep notes with no valid card. In practice, it seems that the first card will be generated, so that the note is accessible from the browser even if the card can't be reviewed. This allows to avoid loosing data. I believe it's an extremely important change. Do we port it ? I don't know what is the correct way to do it. A check box ? To buttons to ask user how they want to delete the note.

The fields of the cards to be deleted are not shown anymore. Instead, there is the note id, which is a link which open the browser to show the note. I believe we can't really port it, as we would not want to deal with multiple activities (I hate this. There are too many empty cards in my collection and needing to click on each link takes too much time.) This does not concern us too much since we just display a number of cards.

Upstream now shows the name of the card type that will be deleted for each note. Which is nice because it gets easier to understand what's wrong. In particular if all cards of type Foo are empty, it probably means I should check the template foo. I'd love to implement that, however, it would mean that we should display a list of deleted cards, and I don't know how to easily make such a big list in the current activity

**Comment by Arthur-Milchior** [comment]
We still do not follow upstream. I've some work in progress in order to make empty card quicker, the PR are still waiting for action on them. I believe those PR are a prerequisite to actually porting feature

**Comment by mikehardy** [comment]
I think this actually is done now can reopen if I'm wrong of course

**Comment by Arthur-Milchior** [comment]
Only one part of it is done. We now don't delete a note if there is no more card, we follow upstream here.
The part that is not done, and that is hard to do, is showing to the user what card will be deleted before asking them whether they want to confirm to delete them

**Comment by dae** [comment]
Fixed in new backend.
