### ISSUE TITLE
Add performance timers to certain critical places

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6897]
> > How do you track perf ?
> > I can tell I see an increase for cards with a lot of field in my collection, but that's not really scientific
> 
> `UsageAnalytics: sAnalytics.timing()` I'd guess. @mikehardy likely knows the library better.

I wrapped Analytics up pretty tightly with regards to Java accessibility because I understand this is a very privacy-minded app, so there is no way to reach in directly and do any sort of analytics except for the methods published, and none of them have to do with timing hits (where you could log the time taken for something and thus infer performance of some action in varying conditions)

To track it at all then UsageAnalytics would need an extension where sendAnalyticsTiming was implemented as a new method, and it worked similar to the "Event" hit (where we log screens shown), but let the caller define a name for the timer, and the time taken and any other details I guess?

The items available are here and the API is "fluent" so it would be used like 

```java
sUsageAnalytics.timing()
    .userTimingCategory(catParam)
    .userTimingLabel(labelParam)
    .userTimingVariableName(variableNameParam)
    .userTimingTime(timeTakenParam)
    .sendAsync();
```
https://www.javadoc.io/doc/net.mikehardy/google-analytics-java/latest/com/brsanthu/googleanalytics/request/TimingHit.html

which are really just mapping to these - the Java API ends up being an HTTP POST to this API:

https://developers.google.com/analytics/devguides/collection/protocol/v1/parameters#timing

But you are correct, there is no prior measurement to compare to, so we have no idea whether it represents an improvement or not.

That said, the best time to measure performance is when you created the program, the second best time is now. So if this was added and we started measuring some basic things (from app first line of our code executed - attachBaseContext I would think) to full init, and to deck list displaying, and to deck list displaying with numbers, that would be good. Time from card answer or card flip to card displayed again, also good

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/6850#issuecomment-674451805_

**Comment by mikehardy** [comment]
Here's a thought, if this was done in a way that was cherry-pickable to 2.12, then we would actually have implemented timers **back in time** and would actually have a comparison for this when it goes out

Just a thought

**Comment by david-allison-1** [comment]
I've attempted this (without the label parameter - marked as optional in the docs) and no timing events were appearing in our dev analytics.

`/batch` was returning a HTTP 200

Sent parameters:

```
"aid" -> "com.ichi2.anki"
"aip" -> "true"
"an" -> "AnkiDroid"
"av" -> "21400113"
"cd1" -> "9"
"cd2" -> "HONOR"
"cd3" -> "LLD-L31"
"cd4" -> "LLD-L31A"
"cid" -> "5310c967-0223-46c0-a7f3-eb74bb5dd62f"
"de" -> "UTF-8"
"sr" -> "720x1354"
"t" -> "timing"
"tid" -> "UA-125800786-2"
"ua" -> "Mozilla/5.0 (Linux; Android 9; LLD-L31 Build/HONORLLD-L31; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/85.0.4183.127 Mobile Safari/537.36"
"ul" -> "en-GB"
"utc" -> "Task"
"utt" -> "1054"
"utv" -> "ANSWER_CARD"
"v" -> "1"
`

**Comment by david-allison-1** [comment]
Analytics were just delayed, previous comment was inaccurate.
