### ISSUE TITLE
Messed up intervals on filtered decks

### ISSUE THREAD

**Issue by rappa619** [ankidroid/Anki-Android#6899]
The interval on filtered decks is messed up on ankidroid using the V2 scheduler. I'm attaching a link with images to check it out along with my settings on the desktop app. I have V2 also selected on the ankidroid app. It only occurs with filtered decks, not with normal decks. 

https://imgur.com/a/SJswyWL

**Comment by Arthur-Milchior** [comment]
Hello,

When you started to report a bug, some informations were asked to you. Can you please give them ? Without it, we can't investigate. In particular, nothing can be done without knowing your version number.
"messed up" I assume that what you means is that the number given in the good/easy buttons differs between anki and ankidroid. Or is there other problems ?

**Comment by david-allison-1** [comment]
@rappa619 Thanks for the report! Should be fixed in the next alpha. Please let us know if it continues to be a problem.
