### ISSUE TITLE
Crop image using edit note

### ISSUE THREAD

**Issue by abdrau26** [ankidroid/Anki-Android#6904]
I have a card containing images. I want to crop/edit images one by one. Is it possible in edit note?
This is my card after edit note:
![Screenshot_2020-08-16_225818](https://user-images.githubusercontent.com/59373108/90340799-1ab10d00-e014-11ea-9bb6-eddc6f2cc2c9.jpg)
I want to crop both image in "back" of the card and replace them with cropped images.

Thanks

**Comment by mikehardy** [comment]
It is not possible, sorry. If you clear out the images, then add new ones you can crop while adding the new ones. If there is only one image (traditionally there is supposed to be just one image per field - and you add more fields to add more images...) then it will work. But multiple images in the same field will not work for crop I don't think
