### ISSUE TITLE
Buttons with different dates (Wish)

### ISSUE THREAD

**Issue by klwemu** [ankidroid/Anki-Android#6914]
It is not very useful to have the same offset interval on 3 answer buttons.

<15m   9mo   9mo   9mo
Again   Hard  Good  Easy

At least the "Hard" Button should offer a much smaller range like 7 or 21 days or a percentage of Good.

**Comment by mikehardy** [comment]
Hi @klwemu - can you reproduce this on the same collection in Anki Desktop? What I'm curious about is whether this occurs just in AnkiDroid or in AnkiDesktop as well.

Further, there is not much information to go on, typically version information of AnkiDroid (and AnkiDesktop) would be the minimum info we need to reproduce a problem. Additionally if it's scheduler related we need to know which version of the scheduler you are using (v1 or v2, v1 is the default if you have not altered it) and any review options you have set (to me it appears you may have altered the scheduler review intervals etc)

**Comment by klwemu** [comment]
Desktop is same! 
(latest and all older Versions)

**Comment by mikehardy** [comment]
I'm going to have to close this then, the only scheduler bugs we accept here are where we deviate from Desktop - we must at all times behave exactly as Desktop from a scheduler perspective as a core part of the mission basically. You might check their support though - https://forums.ankiweb.net/ - by the same token if they make changes we will follow them
