### ISSUE TITLE
Enhancement : reminder appears after wake up alarm or at specific time of day

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ankidroid/Anki-Android#6915]
I feel like this would be useful.

If you never remove the notification until you do it it helps me do the jump of openning the app.

Of course : for specific time of day it could be done with a calendar app.

**Comment by david-allison-1** [comment]
You can set the reminder time in the deck options, how do you envision the functionality would look, and how does it differ from what we already offer?

**Comment by thiswillbeyourgithub** [comment]
Ah yes I forgot about deck options.

I think it would be great to see a notification urging you to do your reviews after the alarm clock of the morning. You need the discipline to not swipe it away but after that : eventually after seeing the notification you will muster the energy to click on it and start your reviews.

Of course it's only possible if android provides a way to know when an alarm clock has been set.

**Comment by mikehardy** [comment]
@thiswillbeyourgithub android does not really provide a way to inspect all the pending intents in the system, that would be an information leak across unrelated apps

**Comment by thiswillbeyourgithub** [comment]
Okay well that settles it. Sorry for the useless idea :)

I'll let you close this.

**Comment by david-allison-1** [comment]
@thiswillbeyourgithub Regardless, thanks for the suggestion! We'll get around to improving notifications and reminders at some time in the future - you might want to watch (or suggest ideas) over at #4944
