### ISSUE TITLE
V2 scheduler handles undo incorrectly in preview mode

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#6916]
A heads up about a bug that causes users to lose a review entry when they undo:

https://github.com/ankitects/anki/commit/d266f9a80a289012e46051af023008e8ab9dc7bb

**Comment by mikehardy** [comment]
@Arthur-Milchior is this an area you know well?

**Comment by Arthur-Milchior** [comment]
The entry is lost from the revlog only, right ? Seems easy to port, even if I don't understand how removing a revlog is a bug.
However I never use the preview mode, so I don't really have any insight here

**Comment by Arthur-Milchior** [comment]
https://github.com/ankidroid/Anki-Android/pull/6918

**Comment by dae** [comment]
Thanks for that Arthur. The issue is that previewing does not create revlog entries, so the previous review was getting deleted instead.

**Comment by mikehardy** [comment]
Thanks for looking out for us - I appreciate it
