### ISSUE TITLE
text to speech doesn't remember language across cards 2.13alpha17

### ISSUE THREAD

**Issue by idkw** [ankidroid/Anki-Android#6919]
###### Reproduction Steps
Starting from version 2.13alpha17 the app doesn't remember the TTS language for both card sides. Before that version, I only had to chose the languages once for each side but now it ask it again and again for all cards and all sides.

1. Review a deck with TTS enabled
2.it asks the language for both side
3. It asks it again for every subsequent card without remembering like it did before

###### Expected Result

It should remember my two languages choice for my deck

###### Actual Result

It asks the language for every side of every card

###### Debug info
AnkiDroid Version = 2.13alpha17

Android Version = 10

ACRA UUID = f8db4366-6f05-4d91-baf0-21511c8d83c0

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
@idkw that's unexpected! Thanks for reporting that

**Comment by Arthur-Milchior** [comment]
Correction sent. Sorry for my mistake and thanks for this quick notification !

**Comment by mikehardy** [comment]
I'll do a new alpha19 with the fix @Arthur-Milchior just coded up sometime in the next day or two
I recognize this might be a really irritating review experience, but you may like to continue helping us by maintaining yourself on the alpha track - you can use this "parallel" build from alpha15 before the issue came up to review until the next alpha comes out: https://github.com/ankidroid/Anki-Android/releases/download/v2.13alpha15/AnkiDroid-2.13alpha15.parallel.A.apk

**Comment by idkw** [comment]
Thank you for the quick fix
No problem, I'm continue using the alpha version
I've installed the 2.13alpha15 too in the meantime

**Comment by mikehardy** [comment]
> No problem, I'm continue using the alpha version

Fantastic - the alpha testing and your bug report are valuable contributions, thanks for sticking with it!
