### ISSUE TITLE
CSS Color Bug: R and G values are inverted for 255, 0, 128

### ISSUE THREAD

**Issue by boolbag** [ankidroid/Anki-Android#6921]
Ankidroid normally handles CSS colors perfectly but I encountered an edge case where it shows the wrong color: the R and G values are switched. 

- `color: rgb(255, 0, 128);` should be pink but displays as bright green: `rgb(0, 255, 128);`
- same with the equivalent hex values: `color: #ff0080;`
- workaround: `color: rgb(100%, 0%, 50%);` correctly displays the pink

Taking a wild guess, could be an off-by-one modulo error.

**This is as of 2.13alpha17**

###### Reproduction Steps
1. Create a note with
```
<span class='pink_rgb'>rgb(255, 0, 128); should be pink, why am I green?</span><br>
<span class='pink_hex'>color: #ff0080; should be pink, why am I green?</span><br>
<span class='pink_percent'>#ff0080;rgb(100%, 0%, 50%); should be pink and is pink, right?</span><br>
```
2. 
Add this CSS to the card:
```
.pink_rgb { color: rgb(255, 0, 128); }
.pink_hex { color: #ff0080; }
.pink_percent { color: rgb(100%, 0%, 50%); }
```
###### Expected Result
Pink, pink, pink

###### Actual Result
Green, green, pink

###### Debug info
AnkiDroid Version = 2.13alpha17

Android Version = 9

ACRA UUID = 552f8cdb-415d-47f1-92b8-9f3ab1a94ddf

Scheduler = std2

###### Research
- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Is this with the night mode color inverter?

https://github.com/ankidroid/Anki-Android/blob/eabd3b8eff2df7a51e9a44fd8919092781080f31/AnkiDroid/src/main/java/com/ichi2/themes/HtmlColors.java#L30-L81

If so it is avoidable: https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#customize-night-mode-colors

**Comment by david-allison-1** [comment]
This is likely our automated night mode colour inversion code.

See: CardAppearance.java - can't link early as I'm on my phone.

Add `.night_mode {}` to your CSS to fix this.

I'll want to add a snackbar warning for this in the note editor in 2.14 (unless someone wants to do it before then). 

It's a large quantity of our support requests and it's not intuitive.

**Comment by boolbag** [comment]
@mikehardy @david-allison-1
Yes. Totally missed that. Sorry for wasting your time!
