### ISSUE TITLE
Wrong French translation in the settings

### ISSUE THREAD

**Issue by idkw** [ankidroid/Anki-Android#6929]
Not at all a big issue, I have noticed a small typo in the French translation in the menu Settings > Review > Display

It says "aromatique" it should be "automatique"

![Screenshot_20200820-203342](https://user-images.githubusercontent.com/7012331/90811443-ea73b200-e324-11ea-83ea-cf0beb821e3f.jpg)

AnkiDroid Version = 2.13alpha15

Android Version = 10

ACRA UUID = 96d9d9ce-ca24-4b35-81ac-d39ccc275f44

Scheduler = std

**Comment by mikehardy** [comment]
These are user contributed: https://github.com/ankidroid/Anki-Android/wiki/Contributing#translate-ankidroid

Go forth and conquer the French translation :-) https://crowdin.com/translate/ankidroid/8173/en-fr#q=screen

**Comment by idkw** [comment]
Didn't know that, thanks !
