### ISSUE TITLE
Missing option: "Show learning cards with larger steps before reviews"

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#6936]
###### Reproduction Steps

1. Review a deck, answer some cards with "again"
2. On the next day (or whenever those lapses are due again) review the same deck again

###### Expected Result

The lapses should be reviewed before the due (green) cards

###### Actual Result

The lapses are ignored until the all green cards are reviewed. Problem: if you don't review all due/green cards you'll not see the lapses and they'll stack day by day.

Therefore Anki desktop has the option "Show learning cards with larger steps before reviews" in püreferences.

![learningcards](https://user-images.githubusercontent.com/45192213/90959496-c7b7d980-e49b-11ea-9b1a-32784d3e9cdb.png)

This option should be added to Ankidroid as well.

###### Debug info

AnkiDroid Version = 2.13alpha19

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

Scheduler = std2

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by freemedom** [comment]
Is it possible that the red card has not expired yet?

(I also don't understand the order how Anki sorts due cards)（Anki Manual seems not mention it）

**Comment by Anthropos888** [comment]
@freemedom The lapses are already due. Also, in scheduler V2 lapses are not shown in the red counter until they are due. So if there's a red number, you always know that those lapses are due.

Problem is that I'm stacking lapses every day and the red number is getting higher and higher without the chance to reduce it.

**Comment by freMea** [comment]
> Actually not. In sched V2, lapses from previous days are seen after reviews. That is the expected behavior unless you checked "**Show learning cards with larger steps before reviews**" in anki desktop (we have nothing similar to this checkbox on ankidroid. We should probably add it by the way)

Thanks for this clarification because I would never guess what this option is for just by reading the label.

**Comment by Arthur-Milchior** [comment]
Please, if you have some time, think about making a report on anki's forum to let them know it's not clear. We follow upstream, so there is little we can do by ourselves here

**Comment by freMea** [comment]
I will 👍

**Comment by dae** [comment]
Closed by #14171.
