### ISSUE TITLE
Add lint rule to respect new time-handling convention

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6951]
###### Reproduction Steps

1. Use time incorrectly (exactly how? We should specify)
2. Attempt to build / run tests
3. 

###### Expected Result

If you use time in a way that is not according to our new convention, the build breaks immediately with a helpful message

Reference #6942 / some discussion in Discord about adding a regex check with prohibited APIs now?

###### Actual Result

I believe it will just continue along...

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
The `Utils` class does not contains time method anymore. So there is little risk those are used. Actually, I removed them because I really would not want a dev to find a public static util method they should not use

**Comment by mikehardy** [comment]
@Arthur-Milchior can you propose that as a concrete review? Good catch

**Comment by mikehardy** [comment]
(on the linked PR)

**Comment by Arthur-Milchior** [comment]
I don't get what you want me to propose ?
The PR does not deal with those function that are not existing anymore. The PR has no problem, so there is nothing I could propose.

On the contrary, my point was that the PR is valid even if it does not follow David's description because in this case, David's remark is not up to date.
