### ISSUE TITLE
Card Template Editor/Browser Appearance: "Insert Field" Context Menu

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#6964]
I would like to have a "Insert Field" context menu in the Card Template Editor and Browser Appearance Editor. 

This would speed up the process of creating templates for me, as typing `{{}}` is slow, and it requires me to remember the exact field name. Anki has a similar feature for the Card Template Editor

![image](https://user-images.githubusercontent.com/62114487/91162852-9110d780-e6c4-11ea-84f7-fcd8dd75fe51.png)
![image](https://user-images.githubusercontent.com/62114487/91162870-979f4f00-e6c4-11ea-83a0-e32e57c4fcb6.png)

**Comment by Akshay0701** [comment]
Nice, I will work on this,
So our flow of design goes like this 

- Field add, remove, reposition and rename functionality dialog in note editor.
- Dialog in card template editor to Insert fields.

is there anything I missed?

**Comment by david-allison-1** [comment]
> Nice, I will work on this,
> So our flow of design goes like this 
> 
> - Field add, remove, reposition and rename functionality dialog in note editor.
> - Dialog in card-template-editor/browser to Insert fields.
> 
> is there anything I missed? 

Just the "insert field" in the card template editor. You can reposition and rename already in the "fields" screen from "manage note types"

**Comment by Akshay0701** [comment]
Okay Done!
<img src="https://user-images.githubusercontent.com/52353967/116902314-9a414380-ac58-11eb-9236-dbd87aeaa111.gif" width="250" height="500" />

**Comment by david-allison-1** [comment]
Fantastic!!

It'd be great to also add this on the context menu

See: `ActionModeCallback` on `NoteEditor.java`

**Comment by Akshay0701** [comment]
pardon me, but I am not sure what I have to do, is this context menu your talking and do I have to add "insert field" in this menu?
<img src="https://user-images.githubusercontent.com/52353967/116979831-1a13f000-ace3-11eb-9cc4-31cd857c924a.jpg" width="250" height="500" />

**Comment by david-allison-1** [comment]
> pardon me, but I am not sure what I have to do, is this context menu your talking and do I have to add "insert field" in this menu?
> <img src="https://user-images.githubusercontent.com/52353967/116979831-1a13f000-ace3-11eb-9cc4-31cd857c924a.jpg" width="250" height="500" />
> 

Sorry for the lack of clarity: Add it to the menu when you long press the field. This lets someone insert the field at the point where their cursor is

I believe Android calls this an "action mode"

**Comment by Akshay0701** [comment]
> This lets someone insert the field at the point where their cursor is

If we want users to insert a field at a specific position, do we actually need action mode?
because I implemented insert at cursor without action mode.

<img src="https://user-images.githubusercontent.com/52353967/117002935-d5e41800-ad01-11eb-9e67-25faaf0af83d.gif" width="250" height="500" />

**Comment by david-allison-1** [comment]
> > This lets someone insert the field at the point where their cursor is
> 
> If we want users to insert a field at a specific position, do we actually need action mode?
> because I implemented insert at cursor without action mode.
> 
> <img alt="" width="250" height="500" src="https://user-images.githubusercontent.com/52353967/117002935-d5e41800-ad01-11eb-9e67-25faaf0af83d.gif">

We can and should do both, but I feel an action mode is better optional UX
