### ISSUE TITLE
Importing a note that already exists overwrites old tags.

### ISSUE THREAD

**Issue by tjthejuggler** [ankidroid/Anki-Android#6968]
###### Reproduction Steps

1. Import a deck with a note that has fields A, B and tag X
2. Import another deck with a note that has the same fields A, B and tag Y

###### Expected Result

The note should have tags X,Y

###### Actual Result

The note has only tag Y

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by tjthejuggler** [comment]
I've written up an example of the issue on the subreddit:

https://www.reddit.com/r/Anki/comments/igh27v/importing_updated_notes_deleting_old_tags/

**Comment by mikehardy** [comment]
@tjthejuggler thank you!
