### ISSUE TITLE
Image Occlusion in AnkiDroid!

### ISSUE THREAD

**Issue by FelipeDrytven** [ankidroid/Anki-Android#6980]
Hey, bros!

I was seeing the line code of Anki Doodle. It's a great tool of Image Occlusion! Is it possible to add that code to AnkiDroid? Unfortunately, the Anki Doodle needs more features, like a "Group Elements" or "Toggle Masks". It will be better, if we could create a card with two or more linked clozes! 

https://github.com/mmjang/Ankillusion

Thanks a lot for ur work!

**Comment by mikehardy** [comment]
No, add-ons don't work in AnkiDroid. It's a platform limitation, we are not able to load 3rd party code on mobile platforms for security reasons.

**Comment by FelipeDrytven** [comment]
Hi, Mike! 😀 
Is it possible to add an Image Occlusion as a native tool in AnkiDroid? Not like an addon.

**Comment by mikehardy** [comment]
No - the amount of complexity in the app is already mind-boggling, we have a hard criteria of only including what "upstream" (Anki Desktop) includes so as not to overburden the volunteer crew here even more than it is already. The only exceptions we make are for obvious platform differences between desktop and mobile, as they have slightly different user interaction patterns and smaller screens of course

But whole features, no.

We are working towards an extensible Javascript API that can completely replace the reviewer (or just parts of it) if desired though and if someone can code Javascript. It could be implemented in that most likely https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

An example of complicated front-end work that already works with AnkiDroid https://github.com/pigoz/anki-canvas

If a general drawing program can be built inside the reviewer, I'm sure an image occlusion could be, in combination with the Javascript API allowing answers to be registered

**Comment by infinyte7** [comment]
I have implemented this.
https://infinyte7.github.io/image-occlusion-in-browser/
View this for usage
https://github.com/infinyte7/image-occlusion-in-browser

**Comment by krmanik** [comment]
I guess we should reopen this issue because the IO is natively supported in Anki, AnkiMobile and should be implemented for AnkiDroid.
Anyone who wants to implement can view this PR for implementation idea. https://github.com/ankidroid/Anki-Android/pull/12105 https://github.com/ankidroid/Anki-Android/pull/12172
