### ISSUE TITLE
Hard to determine colors on dark mode

### ISSUE THREAD

**Issue by kryacer** [ankidroid/Anki-Android#6981]
###### Reproduction Steps

1. Turn on dark mode
2. Open statistics
3. Hourly and weekly breakdown tab.

###### Expected Result
Different colors as on other tabs.

###### Actual Result
Hard to determine which colors are correspond to correct and all answers.
![Screenshot_2020-08-28-15-15-25-739_com ichi2 anki](https://user-images.githubusercontent.com/35563053/91546370-25d53880-e944-11ea-996f-3bd945447f65.png)
![Uploading Screenshot_2020-08-28-15-15-30-372_com.ichi2.anki.png…]()

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [  ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTe

**Comment by david-allison-1** [comment]
@kryacer Do you have any suggestions for better colors?
