### ISSUE TITLE
Create simple instrumented test that launches each Activity once

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#6991]
Seems about every 6 months a simple Activity launch would have caught something, cost benefit tilts towards benefit, and I had it working at one point so I have some code laying around (or more specifically - included then purged from git master but I know where it is...)

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/6984#issuecomment-683071688_

Here's a link to sort of how you do it - you can actually generate these in AndroidStudio by recording the test. The trick (in my opinion) is not to be fancy with *what* you do at all (clicking etc) or the test ends up being very flaky with timing dependencies everywhere (that's why we moved to robolectric). But to just launch the activities? should work.

https://github.com/ankidroid/Anki-Android/blob/49950bfc94154520c8bd96db6c94c76638c59d55/AnkiDroid/src/androidTest/java/com/ichi2/anki/uitests/ActivityTestUI.java

**Comment by david-allison-1** [comment]
#6994 is a fix for the issue which was raised, but I feel there's more value in exercising each screen through the entire `onCreate()` -> `onStart()` process. 

#6330 (monkey) would also catch this without the flakiness, but I'd rather avoid adding stochastic testing into the main PR build path, both from a speed and a flakiness/reproducibility point of view.

**Comment by mikehardy** [comment]
I definitely agree. Thinking a bit more practically about it, I think it does need to be espresso tests in androidTest because we specifically want device quirks and to hit all the APIs (or all the ones we currently can given whatever emulator flakiness is going on).

Creating espresso tests that simply bring up an Activity should be possible without the tests themselves flaking out (that starts to happen as you start trying to interact with the activity and do things - then you get timing issues etc)
