### ISSUE TITLE
Add ability to launch directly into reviews

### ISSUE THREAD

**Issue by z1lc** [ankidroid/Anki-Android#6995]
I would like to be able for Anki to launch me directly into reviews when I open the app, so that I don't have to click on a specific deck. Ideally, this feature would allow me to specify what deck it auto-starts the reviews on. When using the "back" button, it would just take me to the list of all decks, as it works now when reviewing.

I'm envisioning something like this in the settings:
[ ] Immediately start reviews on launch (checkbox)
Default deck used for immediate reviews: < deck name > (select input with all decks you have in collection)

I've posted a bounty for this on https://www.bountysource.com/issues/92534801-add-ability-to-launch-directly-into-reviews

**Comment by z1lc** [comment]
Would prefer this to not get auto-closed due to the bounty attached to it.

**Comment by Arthur-Milchior** [comment]
Partial answer in https://github.com/ankidroid/Anki-Android/pull/7585#issuecomment-719919957 
where you can select a deck and create an icon on android and this icon will directly lead to this deck

**Comment by z1lc** [comment]
@Arthur-Milchior amazing, that's exactly what I'd like! Awaiting anxiously to see that PR merged, thank you 🥇
