### ISSUE TITLE
Improve "Can't find image" workflow

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7009]
###### Reproduction Steps

1. Download an image heavy deck (example: AnKing with media) on Desktop
2. Sync to AnkiDroid, cancel sync before media sync completes
3. View Deck
4. A "cannot find image" symbol is displayed

###### Expected Result

* A snackbar of some sort to prompt the user with suggestions to fix the problem

###### Actual Result

* Nothing

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Very very frequent source of user frustration, yes. There's a FAQ to link to, perhaps that could serve

**Comment by david-allison-1** [comment]
I've had a shot - it's annoying, so I'll only show it twice per session
