### ISSUE TITLE
Cannot disable night mode styles via `.night_mode{ }` in 'style' element on a card's Front field

### ISSUE THREAD

**Issue by sheodox** [ankidroid/Anki-Android#7018]
I built a website ([Context.Reviews](https://context.reviews/)) that generates Japanese vocab Anki cards (mostly automatically, sourced from context sentences you looked up on a popular Japanese dictionary site) and gives you a `.txt` file that follows the [Anki manual's importing format](https://docs.ankiweb.net/#/importing?id=text-files). Since I don't believe there's a way to import things more cleanly than that 'officially' and you can't mess with the card templates in those plain text files I just have a bunch of escaped HTML and CSS in the front/back fields. (It also lets me update the way cards generate without anyone ever having to configure their card templates and can just use a standard Basic template, so in a way it's more convenient)

The cards use a dark color scheme so I wanted to disable the night mode inversion and saw you should be able to add `.night_mode { }` to your CSS but that doesn't seem to disable the inversion. I've found I can only disable it if I add it to the _card template_ but it seems having it in a `<style>` element on the card's Front field itself doesn't cut it, which is what I'm trying to do. I would like to be able to make use of that night mode inversion without requiring a card template change.

![image](https://user-images.githubusercontent.com/3468630/92070595-1013a900-ed72-11ea-8db2-2955b030cd4c.png)

![image](https://user-images.githubusercontent.com/3468630/92070584-0a1dc800-ed72-11ea-87e3-9da829d7dde7.png)

###### Reproduction Steps

1. Download this file
[context-reviews-anki-export-2020-9-2(12).txt](https://github.com/ankidroid/Anki-Android/files/5165993/context-reviews-anki-export-2020-9-2.12.txt)
2. Create a new deck on the Anki desktop app
3. Select the deck, File → Import, find the file above
4. Template should be an unchanged "Basic" template, Fields separated by Semicolon, Allow HTML in fields enabled.
5. Sync
6. View the card on AnkiDroid with night mode enabled

###### Expected Result
Cards should look like this (screenshot from desktop Anki) when including `.night_mode { }` in a `<style>` element in a card field.
![image](https://user-images.githubusercontent.com/3468630/92068969-df317500-ed6d-11ea-86f6-943701019e15.png)
More examples of what I expect the cards to look like can be found on the interactive demo on the landing page of the website ([Context.Reviews](https://context.reviews/))

###### Actual Result

![image](https://user-images.githubusercontent.com/3468630/92069007-f2dcdb80-ed6d-11ea-8212-0dc07e4fc278.png)
On the normal day mode the cards look perfectly fine. It also looks as expected on desktop Anki in both day/night modes.

###### Debug info
```
AnkiDroid Version = 2.12.1

Android Version = 10

ACRA UUID = 60cedbef-6591-4641-a092-ccc4e02dc79b
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Have you tried examining it using our integrated JS/HTML debugging facility? https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

If you can determine a clean way to change this you could propose a PR and we could check it out?

**Comment by sheodox** [comment]
Oh I didn't know that was available, handy! What do you think I should be looking for?

I found the check is fairly rudimentary.
https://github.com/ankidroid/Anki-Android/blob/185dbbba65b62423f01395b8090ceb4cb9c97529/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.java#L53-L56

Could the check be expanded to check the question/answer sides individually? They both include `css()` so if I'm reading it right it would encapsulate the current check.
https://github.com/ankidroid/Anki-Android/blob/d98f676d094d5af8c89ad7d7f84916c4bbaf10e6/AnkiDroid/src/main/java/com/ichi2/libanki/Card.java#L257-L264

Is there a worry that expanding the check to the front/back of the card is more likely to have false positives? Maybe changing the check to be a regular expression along the lines of `\.night_?[mM]ode\b` would be a bit better? (Forgive me, I'm not much of a Java programmer so I don't know if the format is different than JS). [Bit of a demo showing what I'm expecting that to match](https://regex101.com/r/p5p8bd/1)

**Comment by mikehardy** [comment]
> Could the check be expanded to check the question/answer sides individually? They both include css() so if I'm reading it right it would encapsulate the current check.

That has potential, on a first think through of it, it seems like it should work and just be a natural extension of the general "users can disable night mode" idea, with a likely modest performance hit since card sides are normally not that large.

**Comment by david-allison-1** [comment]
> Is there a worry that expanding the check to the front/back of the card is more likely to have false positives? Maybe changing the check to be a regular expression along the lines of `\.night_?[mM]ode\b` would be a bit better? (Forgive me, I'm not much of a Java programmer so I don't know if the format is different than JS). [Bit of a demo showing what I'm expecting that to match](https://regex101.com/r/p5p8bd/1)

I don't think there's much point in checking the front and the back, just checking the front should do (this also cuts down on the rendering time).

I think searching for something along the lines of : `<!--ANKIDROID:DISABLE-COLOR-INVERSION-->` would be better to avoid false positives, and it's much more explicit.

Overall, the fact that HTML is being used in the fields, rather than in a template is a little worrying from a database size perspective. It'd definitely be more ideal to use an existing library to generate an apkg (if possible). 

https://github.com/NdYAG/anki-apkg

**Comment by mikehardy** [comment]
I like the idea of a very very explicit string as well actually.
@sheodox how is this then: search front, search for explicit string -> should be good?

**Comment by sheodox** [comment]
I'd agree not much point checking the back, and I also like the idea of an explicit string.
@mikehardy That sounds great to me!

I'll check out the apkg libraries, looks like there are a few. Thanks :)

**Comment by sheodox** [comment]
Still looking for this one! I'm planning on looking into the better packaging stuff mentioned but this would still be nice.

**Comment by sheodox** [comment]
Hello, I hope this finds you all well in the new year!

I'd still like this if you find time someday! Showing my interest to protect against the stale label!
