### ISSUE TITLE
Delete unused media should give progress indication

### ISSUE THREAD

**Issue by tbm** [ankidroid/Anki-Android#7036]
###### Reproduction Steps

1. Click `Check media`
2. `Media checked` pop-up says there are unused media files
3. Click `delete unused`: files are being deleted, but there is no progress indication

###### Expected Result

Show some progress indication,either a progress bar or a rotating clock or something.

###### Actual Result

It's unclear whether anything is happening.

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

![delete-unused](https://user-images.githubusercontent.com/1556037/92341267-c4edf300-f0ef-11ea-9a67-3646a98efb48.jpg)

**Comment by mikehardy** [comment]
hah - you are not wrong, I agree with you

There is a way to do background tasks similar to our database check where it is possible to post progress back and display it, we could do that

I'm not sure if anyone will be interested to take this on - but that's the pattern to follow, and it's not too bad an area of our code I don't think
