### ISSUE TITLE
Group cards from same notes together in card browser

### ISSUE THREAD

**Issue by tbm** [ankidroid/Anki-Android#7049]
###### Reproduction Steps

1. Go to `Card browser`
2. Choose `Card Modified` as sort key
3. Cards are sorted by modification times
4. However, cards from the same note are not displayed together

###### Expected Result

If you have many notes with the same  modification date, it's not clear how the cards (`Questions`) are sorted. It looks pretty random to me.

It would be nice if cards from the same note would be grouped together.  This would be useful since I sometimes use the card browser to lookup things that I'm unsure about, and so having a word and its translation (for vocabulary notes) next to each other would be useful.

###### Actual Result

Questions are not sorted in any obvious way.

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by tbm** [comment]
Oh, so it seems the modification date is not the date the note was modified but the last time the card was seen or something (?) in which case this would be tricky to do.

Ok, I see there's also `Note modified`, but that also doesn't group cards from the same note.

**Comment by tbm** [comment]
This request still applies. Can you please re-open.

**Comment by mikehardy** [comment]
spared from stale death, at least temporarily ;-)

**Comment by tbm** [comment]
Yes, this is still there and I actually ran into it again earlier today when I accidentally removed the wrong note.

To expand on my use case: I import my deck.  Sometimes I make minor edits to my notes, and when I import the new deck I have both the old and the new note.  I want to remove the old note.  To do this, I have to select both cards... but sometimes it's difficult to choose the right ones.  (Actually, maybe selecting one card is enough to remove the whole note. Because earlier today I selected a wrong card and accidentally deleted the old and the new note).

**Comment by mikehardy** [comment]
How does Anki Desktop handle this? I'm curious, as in general we try to follow them

**Comment by tbm** [comment]
Good question, I never checked that.  As far as I can tell, Anki desktop has the same behaviour.

One difference is that the desktop version always shows the first field of the note for both back and front whereas on Android you show the first field of the particular card (which is much more useful).  Desktop calls it "Sort field" whereas you call it "Question" (again, I prefer Android's choice).  But none of these are relevant to this particular issue.

Sorry, I was looking at the wrong thing.

First I need to sort by "last modified".  This actually isn't obvious in the desktop version (you have to right click).

Ok, I think that was actually a bug in genanki (Python module to create Anki decks) which didn't set the proper modification time for notes.

Now that I look at it again, most cards are next to each other (both on desktop and Android).

I think this can be closed.  Sorry for the noise.

**Comment by mikehardy** [comment]
No worries :-), happy studying
