### ISSUE TITLE
"Show Top Bar" should work when in full screen

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7058]
If the "Show Top Bar" setting is enabled, then the top bar should be visible in the Reviewer when the reviewer is in full screen mode.

**Comment by david-allison-1** [comment]
This was a nightmare - if you attach the topbar to the menu which is shown/hidden, then it doesn't goes back to the top of the page.

**Comment by eu2021** [comment]
Please, consider tackling this nightmare, again. As I explained in #10319, I would like to have the Ankdroid Top bar without the answer buttons.

Thanks,
