### ISSUE TITLE
Add "cloze-only:Text" template filter

### ISSUE THREAD

**Issue by anki-o-meter** [ankidroid/Anki-Android#7063]
Hi, is there any plan to add "cloze-only:Text" template filter that was added in Anki 2.1.29, so Ankidroid TTS can read only the clozed part in the back of the card? It would help a lot with reviews.

**Comment by mikehardy** [comment]
No one is working on it, PRs happily accepted 🙏

**Comment by lucwastiaux** [comment]
This should be done together with the anki {{tts}} tag support, #5793

**Comment by dae** [comment]
Closed by #14171.
