### ISSUE TITLE
Tagged cards not appearing on filtering

### ISSUE THREAD

**Issue by berserkerezio** [ankidroid/Anki-Android#7070]
###### Reproduction Steps

1. Open card browser.
2. Choose the option "filter by tag".
3. Choose any tag.

###### Expected Result
Cards with specified tags should have appeared.

###### Actual Result
No cards appear.

###### Debug info
AnkiDroid Version = 2.12.1

Android Version = 9

ACRA UUID = 8203f6ea-11a2-493a-ab0d-d4999512b3ed

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I think this boils down to the filter by tag being additive with a previous deck selection, resulting in correct but not-useful search results. I was just able to replicate that - I went to card browser (note: it had my currently selected deck in there...) I said filter by tag and chose a tag I know is in use, no results. If I changed the original card browser setting to all decks and filtered by tag, I got results.

This is not a great user experience, so in 2.11 we added a "search all" toast, did you see it?

#6250
#6347

I saw it, and when I hit search all, I saw the results I expected, so I can't reproduce this

**Comment by berserkerezio** [comment]
> I think this boils down to the filter by tag being additive with a previous deck selection, resulting in correct but not-useful search results. I was just able to replicate that - I went to card browser (note: it had my currently selected deck in there...) I said filter by tag and chose a tag I know is in use, no results. If I changed the original card browser setting to all decks and filtered by tag, I got results.
> 
> This is not a great user experience, so in 2.11 we added a "search all" toast, did you see it?
> 
> #6250
> #6347
> 
> I saw it, and when I hit search all, I saw the results I expected, so I can't reproduce this

I am not getting any results in either a specific deck search,or all deck search.

**Comment by david-allison-1** [comment]
@berserkerezio Thanks for the report! Could you provide a tag which this fails for?

**Comment by mikehardy** [comment]
...and perhaps an accompanying collection export, as it seems to work for me :thinking:

**Comment by berserkerezio** [comment]
> ...and perhaps an accompanying collection export, as it seems to work for me :thinking: 

Collection export size is 2 gb,not feasible for me. I can quote the decks and there tags though,give me a while.

**Comment by david-allison-1** [comment]
> > ...and perhaps an accompanying collection export, as it seems to work for me 🤔
> 
> Collection export size is 2 gb,not feasible for me. I can quote the decks and there tags though,give me a while.

You don't need to export media

**Comment by berserkerezio** [comment]
> @berserkerezio Thanks for the report! Could you provide a tag which this fails for?

In the deck "pepper micro" that I downloaded from https://drive.google.com/file/d/1vTHQFSxPLBqfbGcovW95ZfeAJFWrS1WX/view?usp=drivesdk ,the tag (tag:#SketchyMicro::Parasites::(3)-Protozoa_of_Blood::3.3-Plasmodium_spp ) is not showing any cards related to it.

On a related note,a similar deck "pepper pharmacology" has the same issue. 

Since tags in above decks are not showing,I cannot be sure about any other decks I have as well,though one or two searches in them have shown that teir tags may be working fine. Some tags though,do not yield any cards in any deck,and are not being removed by "check database" option which should remove useless tags. Hence not sure if the tags are defective or the useless tags are not being removed.

**The tags mentioned about "pepper micro" deck are NOT useless,they ARE present in multiple cards,but do not turn up any cards upon filtering.**

**Comment by mikehardy** [comment]
That is a very very complicated tag. I wouldn't be surprised if we have some sort of issue related to it - thanks for providing the extra detail!

**Comment by mikehardy** [comment]
@david-allison-1 is on a roll today fixing all.the.bugs
I should have a 2.13.0beta3 out later today with a fix included
sign up for the beta program to get it https://docs.ankidroid.org/#betaTesting
2.13.0 proper will likely be mid-week
