### ISSUE TITLE
Report a retrograde

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#7076]
###### Reproduction Steps

**I'm in version 2.14alpha1 now**

This is my deck structure in the following, note there are 3 sub-deck in "html" deck, and I have a card due to review in sub-deck "css3" now. Then I touch the the "html" deck into the review model.
![image](https://user-images.githubusercontent.com/10048069/93013592-65568280-f5dc-11ea-8275-c5308140977c.png)

But note the title of the card show "html", actually the card in the sub-deck "css3"...
![image](https://user-images.githubusercontent.com/10048069/93014292-87eb9a00-f5e2-11ea-8ec2-d6ceb2fa41af.png)

###### Expected Result

I expected it to show "css3", which is the real title of the card. And I remember the old anki-Android have no this bug, please fix it..

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
I confirm it did not occur on 2.9
In anki upstream there is no such difference

**Comment by Juddd** [comment]
@Arthur-Milchior I suffer this problem after I upgrade the app, so I'm very sure Anki-android had that right title in certain old version...

**Comment by david-allison-1** [comment]
@Juddd Thanks so much for the report!

**Comment by david-allison-1** [comment]
Reproduced - issue is between 2.13alpha28 and 2.14alpha2

**Comment by mikehardy** [comment]
We should have a new release of 2.14alpha3 and 2.13.0beta4 at some point today (once all the work is collected and passes regression tests and google processes and releases it etc), and they will contain a fix for this. Thanks for the report!
