### ISSUE TITLE
[Suggestion/Discussion] Import: Improve user experience

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7077]
The new Anking decks are big (~2.7GB) and users are getting (understandably) bored.

```
If possible, reduce the import time
Fir example I downloaded a 2.7 GB file
And it's taking like 1-2 hours and still not completed

One more thing, say can you add that if I'm importing a file, a big one and say I got bored then started playing YouTube for about half an hour or so then the import keep working in background
It could also help a lot
Coz I got bored today and played YouTube for like half an hour or so but then AnkiDroid restarted and all the progress was reset and I had to restart the import
```

We should warn the user:

* Changing apps may stop progress
* https://dontkillmyapp.com/
* They may want to stop the phone from sleeping and keep it plugged in overnight.

We may want to take out a `WAKE_LOCK`, or move the process to a background job.

**Comment by mikehardy** [comment]
Those are *stupendously* large decks, but at the same time it is (in my opinion) the perfect use of technology. We should be supporting great audio/visual experiences during review etc. I like the idea of the wake lock

Any other messaging around large decks (don't forget to appeal to emotion and ask for solidarity, i.e. "We are working hard to improve support for import of very large decks. At this point it as at least possible, but it is likely to be slow. ...Suggestion, suggestion, suggestion...

**Comment by david-allison-1** [comment]
Had a user inquire about a 5.2GB deck today... might need to update my expectations in the PR

**Comment by david-allison-1** [comment]
Would be great to see https://github.com/ankidroid/Anki-Android/pull/7078 get over the finish line

**Comment by infinyte7** [comment]
I have tested on 5000 notes Anki deck (HSK word list) with audio.
1. Importing of the deck **without media files** complete in around **14 seconds**, then I copied media file manually 
2. Importing of the deck **with media files** complete in around **8 minutes**
These times may be change depending on decks and note type.

So, here may be if large deck there then exporting deck without media and importing will reduce the import time. But it needs to manually copy media files.

**Comment by david-allison-1** [comment]
What about the time to check media?

**Comment by infinyte7** [comment]
xiehanz_hsk5 anki decks 1300 notes
Unzip time for 1300 + additional 10 files: around 16 seconds
Copy files to AnkiDroid: around 18 seconds

Extract directly to AnkiDroid collection.media folder: 16 seconds

**Comment by infinyte7** [comment]
Check media time after manually copying files: 6 seconds

Creating zip file extracting it not ideal because file name get replaced with garbage character when extracting in phone. So, I copied from pc to phone.

**Comment by infinyte7** [comment]
Above test are not standard. Each test may need to used fresh install of app. I have created a list for testing. Testing manually will take time. 

Time comparison for:- 

**Import deck**
1. With media and scheduling info
2. Without media and with scheduling info
3. With media and without scheduling info
4. Without media and without scheduling info

**Export deck**
1. With media and scheduling info
2. Without media and with scheduling info
3. With media and without scheduling info
4. Without media and without scheduling info

**Database and media**
_Check database_ after manually copy media files
_Check media_ when media files are not in collection.media
_Check media_ after manually copy of media files into collection.media
