### ISSUE TITLE
Interleaving suggestion

### ISSUE THREAD

**Issue by sfhrdfg** [ankidroid/Anki-Android#7081]
Hi, Interleaving is one of the better  methods of learning.

###### Reproduction Steps

1. I was adjusting the options for new cards of my option group that is applied to the highest level card stack (German Stapel) of a group with a couple sub stacks to have new cards be shown at random, not by order of creation
2. I was clicking on the top level stack 
3. 

###### Expected Result

Different new Cards from different sub stacks would be shown at random, varying (therefore interleaving) from stack to stack

###### Actual Result

It stuck with one stack, not Interleaving.

###### Sugestion
I'm suggesting to make stack mixing, when practising over a top stack for a top stack the default, as it improves Interleaving, therefore learning, or adding an option for an option group to add this behaviour volubtarily.

**Comment by mikehardy** [comment]
Are you using the v2 scheduler? If not you should try it, I believe this (how it handles scheduling cards from deck families) is one of the things that it improved on. I believe it's in Advanced options

**Comment by sfhrdfg** [comment]
Thanks. I just switch it on and clicked the top deck, still by sub deck

Mike Hardy <notifications@github.com> schrieb am So., 13. Sept. 2020, 22:16:

**Comment by david-allison-1** [comment]
@sfhrdfg SchedulerV2 (in the advanced options) will allow you to review your review cards in a random order.

Please note that the initial change to SchedV2 will move all cards from the learn/relearn queue into either "new" or "review".

**Comment by sfhrdfg** [comment]
Well I turned the scheduler v2 on in the advanced settings. And it does not
show them in the random order I want. I want random order, shuffling
between subdecks, it does: random order, but until you finish all cards of
one subdeck it will only give you cards from that, same subdeck.

David Allison <notifications@github.com> schrieb am So., 13. Sept. 2020,
23:22:

**Comment by sfhrdfg** [comment]
You are right. It's better. I just had an eight card streak of the same
deck for random reasons😄

Christoph Eckinger <christopheckinger@gmail.com> schrieb am Mo., 14. Sept.
2020, 11:52:

**Comment by sfhrdfg** [comment]
And I see why: I just had eighteen new cards of the same subdeck and no
from other decks, although it does shuffle decks for the not new cards.
I'd recommend enabling deck shuffling as default or as option for new cards

Christoph Eckinger <christopheckinger@gmail.com> schrieb am Mo., 14. Sept.
2020, 13:19:

**Comment by sfhrdfg** [comment]
I do appreciate the new scheduler though👍

Christoph Eckinger <christopheckinger@gmail.com> schrieb am Mo., 14. Sept.
2020, 13:30:

**Comment by mikehardy** [comment]
We follow the Anki Desktop defaults as far as I know, and that is a stated goal of the project. I don't think there's anything actionable here so I'm going to close this, but if we defer in default behavior or scheduler behavior from Anki Desktop we can reopen and tag it as an ecosystem compatibility issue
