### ISSUE TITLE
Restore backup on initial install leaves app in unexpected state

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#7083]
###### Reproduction Steps

1. remove `/sdcard/AnkiDroid` on device (note! This is obviously dangerous, this is a testing device right?)
2. install fresh AnkiDroid (seen in firebase auto-testing lab on 2.14alpha3 release
3. accept storage permission, note empty collection screen, choose "restore from backup" from menu
4. restore from the only backup available
5. hit the '+' button the FAB and add a note, save the note

###### Expected Result

The note should save correctly and become the only note in the collection

###### Actual Result

The database is closed. I'm not sure if the backed up "collection" (from the initial install) is/was invalid and so the collection isn't open, or there is an open failure or something, but the note save won't work

```
09-14 08:32:02.626  7393  7641 E SQLiteLog: (1032) statement aborts at 43: [insert or replace into notes values (?,?,?,?,?,?,?,?,?,?,?)] attempt to write a readonly database
09-14 08:32:02.626  7393  7641 E CollectionTask: doInBackgroundAddNote - RuntimeException on adding note
09-14 08:32:02.626  7393  7641 E CollectionTask: android.database.sqlite.SQLiteReadOnlyDatabaseException: attempt to write a readonly database (code 1032)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteConnection.nativeExecuteForChangedRowCount(Native Method)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteConnection.executeForChangedRowCount(SQLiteConnection.java:778)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteSession.executeForChangedRowCount(SQLiteSession.java:764)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteStatement.executeUpdateDelete(SQLiteStatement.java:71)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteDatabase.executeSql(SQLiteDatabase.java:1919)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at io.requery.android.database.sqlite.SQLiteDatabase.execSQL(SQLiteDatabase.java:1911)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.utils.DatabaseChangeDecorator.execSQL(DatabaseChangeDecorator.java:211)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.libanki.DB.execute(DB.java:330)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.libanki.Note.flush(Note.java:142)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.libanki.Note.flush(Note.java:123)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.libanki.Note.flush(Note.java:119)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.libanki.Collection.addNote(Collection.java:651)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.async.CollectionTask.doInBackgroundAddNote(CollectionTask.java:516)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:361)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:309)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:90)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at android.os.AsyncTask$3.call(AsyncTask.java:378)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-14 08:32:02.626  7393  7641 E CollectionTask: 	at java.lang.Thread.run(Thread.java:919)

```

As a side note, the robo-tester in the video I watched got hung up trying to add an AnkiWeb account, so for some reason it is breaking out of the "monkey cage" and getting to that. This occurred because the monkey clicked the sync button

I did see the toast saying "robot detected if you are a human and you see this contact support" so I know the monkey cage was in place, it just has an area where the bars are too wide apart and the animals take over the zoo :-)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
If you close the app and reopen it, it works, on the same restored "collection".
This indicates there may be a more general problem with restore leaving the app in a bad state

In fact yes, if you export the collection (save to file in downloads) then import the exact same collection, the collection is also not opened, but after closing the app and re-opening it, it works again.

So I think the general statement that is the title of this issue is correct: import of a collection leaves the collection closed and the app must be reopened to operate correctly again

**Comment by david-allison-1** [comment]
Likely a regression from 796e2e7c6367bc1dc0cc3af2927f965705f9f30e (#7073 #7074)

**Comment by mikehardy** [comment]
I suspected as much but wanted to start by simply logging the robo result with some local probing while doing my morning email process (still full of happy users from VN haha), before guessing at cause
