### ISSUE TITLE
[Request] Option to disable answer button strings

### ISSUE THREAD

**Issue by nwwt** [ankidroid/Anki-Android#7087]
It's already possible to omit the next review "button" time, but not the static strings (Show Answer / Again - Hard - Good - Easy).

It's be neat to have an option that disables those (ie., leave the buttons and button time). They serve no information (you know what the buttons do within a minute of using Anki, as will everybody looking for the option anyway) and are instead a distraction, minor as it may be.

**Comment by nwwt** [comment]
still searching for solutions…

**Comment by david-allison-1** [comment]
bad bot
