### ISSUE TITLE
[Request] Option to disable pressed button indicator

### ISSUE THREAD

**Issue by nwwt** [ankidroid/Anki-Android#7088]
It's be neat to have an option to disable the "pressed answer button" indicator dots that briefly appear on the top of the next review's front card. I know what I've pressed anyway and have no use for them whatsoever.

I actually used AnkiDroid for half a decade hardly noticing them or even wanting to know what they stood for, but now that I've finally got an OLED screen, their blinking has actually become rather annoyingly distracting, particularly at night with otherwise near entirely (apart from card content ofc) black background/screen.

**Comment by david-allison-1** [comment]
You should be able to disable them by turning on E-Reader mode in the advanced settings.
