### ISSUE TITLE
[Request] Have review GUI dynamically take on background of reviewed card

### ISSUE THREAD

**Issue by nwwt** [ankidroid/Anki-Android#7089]
It would aid immersion (particularly with bezel-less phones and hiding system bars) if there was an option that made the reviewer dynamically take on the currently reviewed card's background color.

Assuming there's an easy way to get color info from the webview, it would probably involve two checks for the effective `background-color` of:
1. an html element with a fixed ID (say, `background`)
2. otherwise, the first element with the `.card` class

The extra 1. is necessary as the only solution to dynamically change background color based on field content involves adding such extra element (that one way or another occupies the background) in the template.

**Comment by david-allison-1** [comment]
Could you provide an image of the issue, I'm not sure I understand

**Comment by nwwt** [comment]
Eg., <a href="https://user-images.githubusercontent.com/887320/93130420-c791af00-f6d2-11ea-9a0c-27c16381f497.jpg">this</a> would become something like <a href="https://user-images.githubusercontent.com/887320/93130729-3e2eac80-f6d3-11ea-8325-a9f16b7acb6a.jpg">this</a> (though maybe with added text-shadow so the text remains better visible).

**Comment by nwwt** [comment]
still searching for solutions

**Comment by nwwt** [comment]
If the bot just ignores it anyway, maybe remove its _"Just comment"_ part.

**Comment by david-allison-1** [comment]
It's on us to remove the label - yours slipped past my notification queue. Sorry

**Comment by mikehardy** [comment]
In general though "searching for solutions" is interesting, but if no one is actually searching for solutions or doing any work on it, that is the literal definition of stale. Not trying to be combative or anything, just that lack of actual progress is a sign
