### ISSUE TITLE
robo-tester can break out of monkey-jail

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#7090]
###### Reproduction Steps

The robo-tester in the video I watched for bug #7083  got hung up trying to add an AnkiWeb account

This occurred because the monkey clicked the sync button

I did see the toast saying "robot detected if you are a human and you see this contact support" so I know the monkey cage was in place, it just has an area where the bars are too wide apart and the animals take over the zoo :-)

###### Expected Result

monkey-cage should not allow sync

###### Actual Result

monkey-cage allows sync

**Comment by david-allison-1** [comment]
Also: Translate
