### ISSUE TITLE
Automatic display answer interaction with cards with no audio

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7096]
On behalf of `Xcom#9917` on Discord

----

###### Reproduction Steps

1. Automatic display answer enabled 
2. Time to show next question 0s
3. Review cards with audio

###### Expected Result
Cards not to show next question

###### Actual Result
Cards with audio show next question, while cards with no audio don't show next question

###### Debug info
ACRA UUID = 123840d6-1f24-400b-96e1-cb8fb64b473d

###### Research
- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by ChrisPalko** [comment]
Hi Xcom here.

So I put show next question to 0s in hopes of not showing the next question. Because I have cards that are just paragraphs and I like to read them fully. And it worked exactly like that for cards that have audio on them. But a card that had audio on it instantly after the audio finished show the question of the next card

**Comment by david-allison-1** [comment]
@ChrisPalko Can't you untick "Automatically display answer", or do you want it for a given purpose?

**Comment by ChrisPalko** [comment]
I can. IT's just it helps me work faster. Because what would happen is that I can't think of the answer to the question so I think and I think, and when I get sick I see the answer and mark it as falied. Automatically showing the answer prevents me from thinking too much
