### ISSUE TITLE
BasicImageFieldController - unique suffix is too long

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7102]
Adding this issue to confirm this is considered to be a bug before I fix it.

https://github.com/ankidroid/Anki-Android/blob/8a93294a8c1397ee93568ee80f9fffc8432879ff/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java#L264-L268

We append a `timeStamp`, but pass it to `createTempFile`, which appends `Math.randomLongInternal();` to the file.

**Comment by mikehardy** [comment]
Oh interesting, one or the other is probably sufficient? The timestamp is millis in unix epoch yes? I thought that was sufficient to not collide actually, as file I/O shouldn't get into the nanos. I wasn't aware there was more sauce appended, that's not really necessary no
