### ISSUE TITLE
Update targetSdk to 29

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#7107]
The Play store has a hard requirement of targetSdk 29 for app update acceptance beginning November 2020 (which in my experience means Nov 1, not Nov anything else)

I believe we're compatible but we need to do it and check

**Comment by david-allison-1** [comment]
I believe we need to enable legacy storage capabilities (and this marks 1 year until Scoped Storage).

**Comment by mikehardy** [comment]
I believe you are correct, I'm chewing through it now, I already had part of it from my dependencies branch (robolectric 4.4 mandates sdk 29, and sdk29 on robolectric mandates java9+ ugh - just peeling the SDK stuff out now and I'll clamp robolectric to 28 for the moment)

There's a pile of stuff though, most notably AsyncTask is deprecated :scream:  which we knew but still, seeing it :scream:

**Comment by david-allison-1** [comment]
#7343 performs this, but doesn't perform the upgrade to `compileSdkVersion 30`

**Comment by mikehardy** [comment]
moving to 30 will be separate, I guess I should log that one :-) but I suppose we have a year for it now

**Comment by mikehardy** [comment]
This was effectively done in #7343
