### ISSUE TITLE
AsyncTask is deprecated

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#7108]
###### Reproduction Steps

1. bump targetSdk above 28 (I'm attempting 30 right now)
2. compile
3. 

###### Expected Result

Clean compile

###### Actual Result

Piles of deprecation warnings of course - because AsyncTask is deprecated and it's the entire way we do non-UI thread processing.

Replacing this is going to be a big deal.

**Comment by mrudultora** [comment]
@mikehardy Using HandlerThreads would be a good option. If you allow there use I would like to work on this issue.

**Comment by sharmaaadish** [comment]
can i work on it?

**Comment by Jatin887** [comment]
can i work on it?

**Comment by dae** [comment]
I think AnkiDroid's code could be considerably simplified if it migrated the existing tasks to Kotlin coroutines.

**Comment by david-allison** [comment]
@divyansh-dxn is doing this for Google Summer of Code

**Comment by BrayanDSO** [comment]
I'm elevating the priority since this may help in some crashes related to collection access and should help migrating to the new backend completely in 2.17
