### ISSUE TITLE
CI: Speed up F-Droid Publish

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7113]
F-Droid typically take a couple of weeks to pull from our repo and get a new version of AnkiDroid out.

We should see if there's an API that we can use to inform them that we've had a release, or provide them with an appropriate release.

EDIT: We've also had a request to see if we can package the betas, will need to confirm that release channels are supported, but I foresee that we'll get really good quality testers from F-Droid if this is possible

**Comment by mikehardy** [comment]
https://f-droid.org/en/docs/FAQ_-_App_Developers/#do-i-need-to-tell-you-when-i-update

**Comment by mikehardy** [comment]
As near as I can tell their automated checkupdates process finds and releases new versions with a lag time of hours. I don't think this is actionable as I don't believe there is any gain to be had from pressing them faster than their current system:

https://gitlab.com/fdroid/fdroiddata/-/commit/9c59a6f2f33a0b72ac21ab3f67ce7b068afb3735

**Comment by voidplayer** [comment]
> Some app developers submit merge requests to us with all the relevant build data when they release. You don’t need to do this, but it can speed things up

I would not want to waste anybodys time and bother somebody having to do this manually, but if it could be automated, why not

Considering 3 days later it hasnt yet reached fdroid, any speed up would be appreciated :)

PS: Yes i noticed its in fdroid yet, it hasnt build it, which the faq states cant be speed up

Also, can we push the betas too, please :)

Many programs in fdroid use them, including f-droid itself. They have suggested versions which are the ones suggested by fdroid, but you can upgrade to any other listed version

**Comment by mikehardy** [comment]
We can do anything and I'm happy to take PRs that support beta for f-droid (I :heart: fdroid) but I have other higher priority release automation tasks in my own queue so it won't be on my personal list.

**Comment by voidplayer** [comment]
Great! can we get this reopen then?

And of course there is no rush or pressure! This is wishlist material

Opening a new Bug #7159 since seems somewhat different to this

**Comment by mikehardy** [comment]
No, there is no action here. The other bug can hold it, but if no one takes it on it will stale out
