### ISSUE TITLE
Browser: Enable Filtering on Flags

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7118]
Users don't know that they can type: `flag:1` etc... this needs a visual item in the Card Browser Action bar - similar to the item in the Reviewer

**Comment by Volfee** [comment]
Hi David, if this is still an open issue, I'd be happy to work on this.

**Comment by david-allison-1** [comment]
> Hi David, if this is still an open issue, I'd be happy to work on this.

That'd be great!

Sorry the description was bare:

Syntax for a search:

https://github.com/ankidroid/Anki-Android/blob/0b23ca26293d5834775f39ede7dbd55c627fc3f6/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L1018-L1023

The menu where items can be added:

https://github.com/ankidroid/Anki-Android/blob/8a79dd14b6d7e1b865a466d4dc561914ba312f59/AnkiDroid/src/main/res/menu/card_browser.xml

It'd be best to use a nested menu (as those can display icons):

https://github.com/ankidroid/Anki-Android/blob/937d3027a35f3af8c478b2066c8f35d1627710ee/AnkiDroid/src/main/res/menu/reviewer.xml#L28-L55
