### ISSUE TITLE
Disable animations and transitions globally

### ISSUE THREAD

**Issue by balta2ar** [ankidroid/Anki-Android#7119]
Hi. I've just upgraded Anki to the latest available version on the Google Play and feels like a lot of animations have been added. Specifically:

* main sidebar on the left
* transitions between screens in the settings
* Answer buttons selection animations (when they are held and released)

I'm sorry but such animations literary make me dizzy and nauseated. Is it possible to have a setting that disables them all? Maybe some of them were there all along, but I'd totally appreciate if I could disable them anyway.

![S00916-20115957](https://user-images.githubusercontent.com/340676/93376493-f9814d80-f859-11ea-96e4-cd6c267af3fc.jpg)

Almost all animation settings are disabled in the developer settings and I can't disable the last one because if I do, app switcher on my phone becomes absolutely difficult to use.

**Comment by david-allison-1** [comment]
Hi

Settings - Advanced - Safe Display Mode will remove many of the animations. We're working on the remainder in: #7114. 

UI is not an area of the code that I'm at all familiar with, so help would be much appreciated.

**Comment by balta2ar** [comment]
Thank you for the prompt response! I checked the settings and it was enabled, so I guess I'll be waiting patiently for the new releases where that setting will have effect on more of the animations in the app. Feel free to close if this is a full duplicate, I'll subscribe to the other issue.

**Comment by mikehardy** [comment]
@balta2ar for you, to work around any health issues while waiting for animation disable, you might like to install the previous release in parallel form? It will use the same collection, and allow you to receive Google Play updates on the main install (to take advantage of animation disable when it comes out...) but be okay in the meantime: https://github.com/ankidroid/Anki-Android/releases/download/v2.12.1/AnkiDroid-2.12.1.parallel.A.apk (or any of the APKs with letter codes from https://github.com/ankidroid/Anki-Android/releases/tag/v2.12.1 )

**Comment by david-allison-1** [comment]
@balta2ar I'm able to disable the navigation drawer animation (after a lot of effort). This will be in 2.13.1 or 2.14

The button animations are disabled by the system animation settings. It's likely far beyond my skillset to allow our animation settings to influence them

**Comment by balta2ar** [comment]
Thank you both, I appreciate the effort you put into developing this app, love it! :heart:
