### ISSUE TITLE
Daily "Studied X cards in ..." no longer properly padded - regression in 2.13.0

### ISSUE THREAD

**Issue by szpak** [ankidroid/Anki-Android#7121]
###### Reproduction Steps

1. Create number of decks to make the deck list scrollable (putting a phone horizontally makes it even easier)
2. Scroll the main list of decks up and down

###### Expected Result

`Studied X cards in ...` daily summary is properly padded (it doesn't interfere with deck names)

###### Actual Result

`Studied X cards in ...` occasionally is not readable due to interfering with deck names.

![image](https://user-images.githubusercontent.com/148013/93390674-5c7cdf80-f86e-11ea-8cd4-69a3c3eedb61.png)

###### Debug info
Doesn't seem to be needed.

AnkiDroid 2.13.0 on Pixel 3a with Android 11. That problem was visible also in earliest beta versions of 2.13.0. It worked fine with 2.12.0.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Thanks for the report! I don't recall any relevant changes on this screen, but I'll investigate. 

Thanks again!

PS: We're actively seeking beta feedback, so if there's anything more, please let us know so we can quash it before the general release.

**Comment by mikehardy** [comment]
@david-allison-1 It's already in general release ;-)

**Comment by szpak** [comment]
> PS: We're actively seeking beta feedback, so if there's anything more, please let us know so we can quash it before the general release.

That's why I use the beta versions :-). This time, I've just been postponing the bug report too long and I was late to the stable party ;-).
