### ISSUE TITLE
Disable button animation

### ISSUE THREAD

**Issue by tilusnet** [ankidroid/Anki-Android#7128]
Feature request

In Ankidroid 2.13 the buttons animate which slows down the flow. I prefer the practice session to be snappy and the animations are a distraction. I'd like this feature to be switched off. 

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
@unusualstranger Is there a good way to go about this (disabling the ripple effect)? My UI knowledge is limited.

Potential thoughts: 

* Might be a way to simulate changing the animation duration per app
* Custom button View class
* Disable the animation programatically in the `Viewer`

**Comment by david-allison-1** [comment]
@tilusnet 

For now, you can disable this animation temporarily in the Android Developer Settings - Tap the build button 7 times and it's under "Display".

You could also install a parallel 2.12.1 APK alongside 2.13.0 while we get this resolved: https://github.com/ankidroid/Anki-Android/releases/download/v2.12.1/AnkiDroid-2.12.1.parallel.A.apk

Thanks,

David

You could also download AnkiDroid 2.12.1 temporarily

**Comment by unusualstranger** [comment]
> @unusualstranger Is there a good way to go about this (disabling the ripple effect)? My UI knowledge is limited.
> 
> Potential thoughts:
> 
> * Might be a way to simulate changing the animation duration developer option per app
> * Custom button View class
> * Disable the animation programatically in the `Viewer`

Sorry for late response, I'm fairly sure there should be a way to get resources from custom SDK folder though my Android UI knowledge is more limited than yours. Another way would be changing names for old background resources and new ripple background resources to be able to change them pro grammatically. Fade animation can be disabled in code. I can get onto this issue

**Comment by unusualstranger** [comment]
@david-allison-1 should I use the existing Safe Display option or make a new one?

**Comment by david-allison-1** [comment]
@unusualstranger Use 'Safe Display' (`AnkiActivity.animationEnabled`). Thanks so much for the help on this one

**Comment by unusualstranger** [comment]
I've went through all project files with Find tool and I don't see any mention of `eInkDisplay` preference key elsewhere, may that be a bug or it gets set outside of AnkiDroid? So I think I'm going with safeDisplay for now

**Comment by tilusnet** [comment]
Thanks guys for looking into this.

Also I may say something utterly obvious, but the previous version worked just fine for me.

**Comment by david-allison-1** [comment]
> I've went through all project files with Find tool and I don't see any mention of `eInkDisplay` preference key elsewhere, may that be a bug or it gets set outside of AnkiDroid? So I think I'm going with safeDisplay for now

I've fixed that in the latest version of `master`, `animationEnabled()` now uses `safeDisplay`

**Comment by unusualstranger** [comment]
> I've fixed that in the latest version of `master`, `animationEnabled()` now uses `safeDisplay`. Ref: #7092

I must have not pulled changes from upstream properly, sorry! Looks like telling Android Studio to pull from upstream wasn't enough…

**Comment by tilusnet** [comment]
Good job, thanks for the prompt update in 2.13.1! :ok_hand:
