### ISSUE TITLE
ankidroid 2.13.0  cleartext failure

### ISSUE THREAD

**Issue by liu-hz** [ankidroid/Anki-Android#7130]
when i use the ankidroid 2.13.0 on my anki-sync-server . it tell a error is java.net.UnknowServiceException:CLEARTEXT.communication to IP not permitted by net work security policy. i need help to fix this problem . if you know how to fix it .pleace tell me thank you so much

**Comment by david-allison-1** [comment]
@liu-hz Thanks for the report.

Did this work on AnkiDroid 2.12.1?

**Comment by liu-hz** [comment]
> @liu-hz Thanks for the report!
> 
> Did this work on AnkiDroid 2.12.1?

yes i test ankiDroid 2.12.1  also has this problem

**Comment by david-allison-1** [comment]
@liu-hz You'll need to use HTTPS on your sync server.

**Comment by liu-hz** [comment]
> @liu-hz You'll need to use HTTPS to connect to your sync server.

do you know how to step the sync server ?can fix this problem ?thank you so much

**Comment by david-allison-1** [comment]
@liu-hz I don't. You'd be best to ask someone associated with the Sync Server for support.

**Comment by mikehardy** [comment]
AnkiDroid requires TLS1.2. It's a hard requirement. If you run your own server you are responsible for implementing TLS.
Support for that is outside of scope here, but it is definitely possible and we specifically support self-signed certificates
I recommend https://letsencrypt.org/

**Comment by minijackson** [comment]
Hello and first of all thank you for this amazing app.

Can I ask you to reconsider allowing non TLS connection to a custom sync server?

In my usecase, I would like to use a custom sync server, but not expose it to the internet, so I would like to access the sync server through a VPN connection. Having to expose the service to be able to have a Let's Encrypt certificate makes it more discoverable and (depending on your VPN implementation) arguably less secure for people having a similar usecase.

Maybe having a "I know what I'm doing" checkbox to disable the TLS requirement would be a good compromise?

Thanks again!

**Comment by mikehardy** [comment]
We specifically add the ability to accept self-signed certificates installed in the android user trust store, you don't need a public / valid cert, just any cert
