### ISSUE TITLE
"Cloze Anything" cause "Collection not Opened"

### ISSUE THREAD

**Issue by rleitzell** [ankidroid/Anki-Android#7132]
###### Reproduction Steps

1.  Cards made on Anki for Mac using Cloze Deletions with "Cloze Anything"
2. Sync to Ankiweb
3. Upon opening AnkiDroid and attempting to sync, I get the "Collection not opened" warning, and no combination of force sync or delete library allows me to proceed until the "Cloze Anything" cards and deck are removed.

###### Expected Result
Successful sync and study

###### Actual Result
Unsuccessful sync

###### Debug info
AnkiDroid Version = 2.13.0

Android Version = 10

ACRA UUID = 36f1b591-db81-4e3c-aac5-a398978cfcdf

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @rleitzell 

Could you provide us with the `AnkiDroid/collection.anki2` file (this is all your Anki data aside from media).

If it doesn't have private data, could you copy it, change its name to collection.zip and upload it here.

It it does have private data, could you email it to my gmail: davidallisongithub

Thanks for using AnkiDroid, I'll get this looked at ASAP

David

**Comment by rleitzell** [comment]
It's unfortunately too large to upload here, it's 230mb.  I have a copy of the deck that was causing issues, however?
[Botany.apkg.zip](https://github.com/ankidroid/Anki-Android/files/5240203/Botany.apkg.zip)

**Comment by david-allison-1** [comment]
> 
> It's unfortunately too large to upload here, it's 230mb.  I have a copy of the deck that was causing issues, however?
> [Botany.apkg.zip](https://github.com/ankidroid/Anki-Android/files/5240203/Botany.apkg.zip)
> 
> 

collection.anki2 should be around 50MB max, are you sure you selected the correct file?
