### ISSUE TITLE
Cards are automatically answered in 2.13

### ISSUE THREAD

**Issue by julienbaley** [ankidroid/Anki-Android#7136]
Hello,

This happens for perhaps one card in six for me, at the moment. I have noticed the problem happening all day since the 2.13 update. It feels as if Ankidroid was mis-detecting the taps and when I lift my finger, it registered a new tap or something. (I have been using Ankidroid every day for nearly a decade, so I think my finger is not the problem)

###### Reproduction Steps

1. Go to study deck
2. press "Show Answer"

###### Expected Result

The answer is shown.

###### Actual Result

The card is automatically answered and the next card is presented.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @julienbaley, could you provide the debug information from Settings - Advanced - About AnkiDroid, it'll help us diagnose the problem

**Comment by julienbaley** [comment]
Of course, here it is:
AnkiDroid Version = 2.13.0
Android Version = 9
ACRA UUID = 5a15499c-8686-431f-afe7-bb85d64c77fa
Scheduler = std

**Comment by david-allison-1** [comment]
Hi @julienbaley,

This is being discussed in #7138, and should be fixed shortly. I'm going to close this as a duplicate. 

Please subscribe to updates in the linked thread if you want to track development progress.

All the best,

David

**Comment by julienbaley** [comment]
Thanks! Glad to see I'm not alone having the problem.
