### ISSUE TITLE
Anki droid skips cards on google pixel 2

### ISSUE THREAD

**Issue by kr1419** [ankidroid/Anki-Android#7138]
###### Reproduction Steps
AnkiDroid Version = 2.13.0

Android Version = 10

ACRA UUID = 521c40af-fd41-48c5-8674-c1ef19a9b3ee

Scheduler = std

1.  Answer a card
2.  For the next card, press show answer immediately after
3.  The card does not show the answer. Instead, it skips the card.

I believe this has to do with the new touch animation. This was never a problem before.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @kr1419, thanks for the report!

Could you download and install the 2.13.1 parallel release, enable `Settings - Advanced - Safe Display Mode` and see if this resolves the problem

https://github.com/ankidroid/Anki-Android/releases/download/v2.13.1/AnkiDroid-2.13.1.parallel.A.apk

Thanks,

David

**Comment by kr1419** [comment]
Hi, I downloaded and tried the safe display mode. It fixes the card from skipping, but when I am trying to go through cards quickly, it is stuck on the answer screen while I am pressing 'again <10'. This lasts for a couple seconds. I am able to see the touch animation with safe display mode.

**Comment by kr1419** [comment]
It seems like I am having another issue. I don't know if I should make a new post. I am going through a deck. It is not assigning me any review cards or new cards, and I have gone through 1544 cards. Maybe a safe display mode issue?

**Comment by david-allison-1** [comment]
@Arthur-Milchior @unusualstranger any ideas on the above? Things seem to be working fine on my device.

**Comment by kr1419** [comment]
AnkiDroid Version = 2.13.1
 
Android Version = 10
 
ACRA UUID = f140fd0b-69b7-459a-9301-bc024696abb4
 
Scheduler = std

**Comment by Arthur-Milchior** [comment]
> The card does not show the answer. Instead, it skips the card.

I assume it means that it shows yet another card, right ?

I've no idea what this touch animation is, so I don't have any insight here

Anyway, I can't reproduce, I can ask for the answer as long as the next card is asked and it works perfectly.
I also tried with the safe display mode activated.

>  It is not assigning me any review cards or new cards

I don't understand. Did you see 1544 cards in learning (red cards) ? That seems a quite unusual amount of cards in learning. So I guess you probably had either new or review cards

**Comment by unusualstranger** [comment]
I've reproduced the issue. Seems like answer buttons need to be disabled before transitioning, though Show Answer button appears above them.

**Comment by kr1419** [comment]
> I assume it means that it shows yet another card, right ?
 It shows the next card, but a card is still skipped.
> I've no idea what this touch animation is, so I don't have any insight here
You press the screen and a gray circle appears around your finger, like what touching the home screen button on android does. It came with the latest update.
> Anyway, I can't reproduce, I can ask for the answer as long as the next card is asked and it works perfectly.
I don't know, it is a new issue after the update for me.
> I don't understand. Did you see 1544 cards in learning (red cards) ? That seems a quite unusual amount of cards in learning. So I guess you probably had either new or review cards
It says studied 1544 cards, only assigning the red cards. I studied a lot the day before, and I was only getting red cards. But on desktop is works fine.

Here is a gif of anki skipping cards: https://gfycat.com/charmingimpressionableegret

**Comment by unusualstranger** [comment]
I will work on this issue today after I come home from work. I think I
already have some plan in mind

**Comment by mikehardy** [comment]
@kr1419 can you install the new parallel release with the fix for this to verify it works? https://github.com/ankidroid/Anki-Android/releases/download/v2.14alpha8/AnkiDroid-2.14alpha8.parallel.A.apk

If you confirm that it works for you with the fix in that release then I can cherry-pick the change back to the release-2.13 code tree and get release 2.13.3 out for everyone

Thanks!
