### ISSUE TITLE
Failed to open deck error

### ISSUE THREAD

**Issue by MikeDacre** [ankidroid/Anki-Android#7149]
###### Reproduction Steps

Try to open a deck on AnkiDroid only following latest update.

###### Expected Result

Opens.

###### Actual Result

Error message "Failed to open deck' followed by a number.

Failure occurs with every deck even after restarting. However, it did not happen this morning following the update, only this afternoon.

###### Debug info

AnkiDroid Version = 2.13.1

Android Version = 10

ACRA UUID = 0b7bd722-7774-4334-832e-4bd0692d9512

Scheduler = std2

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by MikeDacre** [comment]
Spoke too soon. Rebuilt the database in the app and that fixed the error. So, this has never happened before in the many years I have used AnkiDroid, so I'm going to leave this open in case it is a new but, but feel free to close if needed. I don't need any further support.

**Comment by david-allison-1** [comment]
Thanks for the report

Cause: #7131

https://github.com/ankidroid/Anki-Android/blob/890ef6c5835e1acde92edc6af8a36a64dcc90601/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L265-L268

Maybe checking for the collection being open is too hasty - I'll remove it and leave it as an exception handler
