### ISSUE TITLE
push betas to fdroid

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#7159]
Related #7113

Currently getting de .apk is a little cumbersome because user must know the architecture of their phones

Fdroid allows for beta releases

**Comment by mikehardy** [comment]
Here's the relevant code where we push to non-play store locations

Note that "public" is not beta, so the if would be different for f-droid, but it's after the "main" release process so this is where it should go

https://github.com/ankidroid/Anki-Android/blob/e44b6bfd683e1cbf0bae2c33384f9aa3e74d4fdf/tools/release.sh#L154-L168

**Comment by voidplayer** [comment]
In the past I tried to directly install every .apk on the beta page on github and all of them failed. Probably something wrong with my phone

I have no idea how to do this, but ill take a look!

**Comment by david-allison-1** [comment]
> In the past I tried to directly install every .apk on the beta page on github and all of them failed. Probably something wrong with my phone
> 
> I have no idea how to do this, but ill take a look!

Installs don't give error codes in the Android UI, my most common error is running out of disk space.

Also try with the "universal/Parallel.A/B" APKs, as those remove a class of errors (with the downside being a larger file)

**Comment by voidplayer** [comment]
Well, my phone is always running out of space, so that might have been it. I tried all the apks :/

I checked and i dont think is currently possible to autodetect betas

I created an [issue](https://gitlab.com/fdroid/fdroiddata/-/issues/2166)

Right now, the only way is to create a PR, which incidentally would also help to speed up the building. But I would have to learn the anki building process to do that. I checked it a little and that is a little outside of what i can comfortably do right now

**Comment by sudomain** [comment]
I'm interested in getting betas on Fdroid as well. Are we talking about betas or alphas though? From my quick browsing of the releases it seems [v2.13.0beta4](https://github.com/ankidroid/Anki-Android/releases/tag/v2.13.0beta4) was the last beta, which means the newest beta is actually older than the current stable (2.13.5).

Also, unless I've misunderstood the F-Droid build process, wouldn't we just need a tweak to the `AutoUpdateMode` and `UpdateCheckMode` of [AnkiDroid's yaml file that's part of the fdroiddata repo?](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.ichi2.anki.yml#L642)

**Comment by mikehardy** [comment]
I'm open to anyone doing anything here to make it work :-). I would not publish alphas to f-droid personally, seems like nearly an abuse of their build infrastructure (we "abuse" github and google in this way for alpha build+release but they have a revenue model...). But even there, seriously, whatever people consuming AnkiDroid via F-Droid want. Just let me/us know if you need anything, otherwise go forth and do your best :-)

**Comment by sudomain** [comment]
I'm willing to look into it more and make the appropriate PR(s). I agree
with what you said about the effect of publishing alphas on their build
infrastructure, though I'll double check with them because maybe they'll
welcome it.

If they don't want every alpha, is there a release policy for the Play
store beta program that I can reference?

**Comment by mikehardy** [comment]
I think you can just follow tags on the repo via regex, I believe that's how they do it? Our release tags are automated so their format does not vary. It is always possible that the latest production / stable release has a version number that is greater (by semantic versioning rules) than the most recent beta. This is because we do not have a policy that all production releases beta first and then release unchanged from beta, so it's possible that we simply issue a semantic-version patch release with no beta whatsoever

**Comment by voidplayer** [comment]
You **cant** auto detect version AND separate stable releases using autodetect

I stepped up to add this functionality but quoting fdroid developer, ["[autoupdate]...is a crazy bag of kludges and hacks"](https://gitlab.com/fdroid/fdroidserver/-/issues/161). I spent a day and i think i could had fixed it using 1-2 more days. Its not as easy as i thought it was going to be, but its in the back of my head...

I agree that only betas should be pushed. Mainly because i think betas are more interesting for fdroid users than alphas. Although i wouldnt be too worried about abusing it. Fdroid developers keep at least 10 versions. Ankidroid only keeps 3. Also, building is triggered manually by a fdroid developer when he feels like it, usually once a week. There might be 10 alphas in that week, and only one would get built

Meaning, I would take their own app as a meassure of what means abusing it, but dont quote me on this :)

The only way to do it automatically currently is making an account for ankidroid in gitlab of fdroid and have a PR with every beta

The other way is to fix the bug aforementioned bug of fdroid. Which i dont think is too hard and would benefit every fdroid project out there :)

**Comment by federvieh** [comment]
Hi,

please consider that at least one F-Droid user (me) would like to only use stable versions. I guess there are others, that feel the same. I'm not sure if your proposal breaks anything for my use case. Could you please elaborate?

Thank you all for your continued efforts to make and maintain AnkiDroid! You are awesome!

BR
  Frank

**Comment by sudomain** [comment]
I don't think anyone is arguing for the idea of forcing unstable software on unsuspecting FDroid users. It would be nice to have the option of getting the Betas through their infrastructure.


Also, FDroid has an option under `Settings -> Other -> Expert Mode -> Unstable updates` which is off by default.

**Comment by PanderMusubi** [comment]
@izzysoft do you think building an alpha for AnkiDroid is feasible fro F-Droid?

**Comment by IzzySoft** [comment]
Who will maintain that? As alphas/betas should not be the "suggested version", they must be added manually every time, via merge request, which someone must open and someone must process.

**Comment by PanderMusubi** [comment]
Since the alpha releases have apk files, I think it is not worth it. Better that AnkiDroid more often makes normal releases. The latest stable is almost a year old.

**Comment by mikehardy** [comment]
Yes @PanderMusubi - we are certainly trying. It's half a year though, exaggerations are demotivating as criticism ;-) - follow here #5304 and hopefully it's out soon.
Typically when we are not blocked from releasing I try to release ever 1-2 months.
