### ISSUE TITLE
Deck Life statistics reporting period now counts every card in the deck as Added, giving wrong average cards per day figure

### ISSUE THREAD

**Issue by quarridors** [ankidroid/Anki-Android#7161]
###### Reproduction Steps

1. Have active decks in AnkiDroid
2. Switch to 'Statistics'
3. Choose a deck with less than a year of total deck life
4. Switch reporting period between '1 year' and 'deck life'
5. Observe the figures under 'Added', both 'Total' and 'Average' in the 'Overview' tab

###### Expected Result

See #7160 - this may be a replated bug.

Before the situation described in issue #7160, the 'deck life' statistics Overview tab gave figures under an 'ADDED' heading that gave a total of the number of cards that had been newly learned during the deck's life, and an average cards per day that divided that total figure by the number of days in the period.

If the deck's life was less than 12 months then the '1 year' report would give the same total for new cards added as the 'deck life' version of the report.

###### Actual Result

Extra to what's reported in issue #7160, I've found that, while the year and month reports are giving the number of cards added from scratch (not unsuspended and learned cards) as the reported total, the 'Deck Life' report is giving the number of cards total in the entire deck, even when the deck's life is shorter than 1 year so should match the year report.

So the year report says 14 cards added and the deck life report says 3238 cards added, in a period shorter than 1 year.

Worse still, the average cards added per day figures on the Deck Life reports don't seem correct. One of my decks is 251 days old, claims 3238 cards were added but gives the average as 1.7 cards per day. I make 3238 cards divided by 251 days to work out as 12.9 cards per day.

On my 'Spoonfed Chinese' deck, where I've never added cards, all reports say 0 added cards except 'deck life' reporting period which gives 16034 cards, 8.5 cards per day over a 252 day period. That many cards divided by that many says should be 63.6 per day.

Same goes for the All Decks report, ther 1 month period shows 14 cards added, 0.5 per day, the 1 year period shows 14 cards added, 0 per day. Meanwhile, the deck life report instead gives 31922 cards, 16.9 cards per day for a 284 day long reported period. I make 31922 cards divided by 284 days to work out as 112.4 cards per day.

I'm also not sure where it's getting the 284 days from, my oldest decks are 252 and 251 days old.

This seems to be a clear bug.

###### Debug info
AnkiDroid Version = 2.13.1

Android Version = 9

ACRA UUID = 9cae9198-9773-489b-b08d-940acf072fb2

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by quarridors** [comment]
I've been asked on the other issue to confirm that reporting figures differ from the Desktop client's. Having downloaded the new Mac version, I've found the following of the desktop report:

There is an 'Added' report right at the very bottom, this gives all the cards I've manually added myself.

That seems to have a different but related bug. The 'All' option under Added, which is presumably the equivalent of Deck Life, says that 3,238 cards were added for the 251 day old deck and that it works out as 34 cards per day, which is wrong in a different way. The chart however goes back to day -1,860 and shows no cards actually being added anywhere in the chart except in the last 39 to 20 days, when a total of 14 were added.

The 1 month figure on Mac version seems to use a 31 day period rather than AnkiDroid's 30 days. It says 14 cards were added in that total but gives the average per day as 0 cards, when AnkiDroid gave 0.5 per day.

So that's the desktop version clearly differing from AnkiDroid ...but both seem to have related bugs that are breaking their 'deck life' or 'all' reporting period, albeit in different ways, which suggests that the bug is probably located in some backend code that both share?

Should I report this somewhere else? Any idea what the correct behaviour of the 'Added' report is meant to be? What AnkiDroid was previously doing, or what it does now (deck life counting bug aside)?

**Comment by david-allison-1** [comment]
We don't share code with Anki Desktop, but we aim to emulate its behavior. We'll start sharing code imminently.

https://forums.ankiweb.net/ would be the best place to report issues with Anki Desktop.

If you can provide an exported deck with statistics discrepancies between us and Anki Desktop, I'll get those fixed.
