### ISSUE TITLE
Scheduling Bug: Undo resets new cards to 30

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7162]
###### Reproduction Steps

1. Download: https://drive.google.com/file/d/1XYAlY4YYi6SbM3OIzlrAWrmaByXne4m_/view?usp=sharing
2. Study 4 new cards
3. Suspend all in deck
4. Unsuspend all in deck (26 cards left)
5. Review "Good"
6. Undo

###### Expected Result

7. 26 0 0

###### Actual Result

7. 30 0 0

###### Debug info
AnkiDroid Version = 2.14alpha6

Android Version = 9

ACRA UUID = 6c9f2dcc-a56f-4256-8dcd-8af4ff321a70

Scheduler = std

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
There's also a difference between the main deck picker (30) and inside the reviewer (29).

**Comment by Arthur-Milchior** [comment]
Please, can you indicates whether you mean : 
Study with pressing 1, 2 or 3? Again, good or easy.
Are you in sched V1 or V2 ?

**Comment by david-allison-1** [comment]
> Please, can you indicates whether you mean :
> Study with pressing 1, 2 or 3? Again, good or easy.
> Are you in sched V1 or V2 ?

Good (2d). schedv1 (as in the debug info)

**Comment by Arthur-Milchior** [comment]
I can't reproduce on master in an emulator

**Comment by Arthur-Milchior** [comment]
In more detail:
1. Download: https://drive.google.com/file/d/1XYAlY4YYi6SbM3OIzlrAWrmaByXne4m_/view?usp=sharing
1. Open the deck. 
1. Study 4 new cards with "good"
1. Open deck browser
1. Select the 4 unsuspended cards
1. Suspend them
1. Select all cards through the menu
1. Suspend all in deck
1. go back to deck picker (I see 26 cards left)
1. Open the deck (I see 26 new cards in deck)
1. Answer "good"
1. Undo 

I see indeed 30 cards.

**Comment by Arthur-Milchior** [comment]
I can't reproduce it anymore. Seems not to always occur, which makes it hard to consider...
