### ISSUE TITLE
{{Hint:}} stopped working

### ISSUE THREAD

**Issue by vikmaar** [ankidroid/Anki-Android#7172]
###### Reproduction Steps

{{Hint:}} hasn't been working since 2.1.31 (l'm not sure that it was 2.1.31, but l noticed it on 14.09.2020) both on Windows 10 and Android. Before that {{Hint:}} was working fine several years. Now {{Hint:}} doesn't turn into the "Show hint" link, it just stays {{Hint:}} and tapping on it doesn't open the hint.

###### Expected Result
 {{Hint:}} should turn into the active link "Show hint". Tapping / clicking on "Show hint" should open the hint.

###### Actual Result
{{Hint:}} doesn't turn into the active link "Show hint". Tapping / clicking on "Show hint" doesn't open the hint.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
This was an Anki Desktop change that we made to maintain compatibility with Anki Desktop, please contact Anki Desktop support: https://forums.ankiweb.net/

`{{Hint}}` now works only in the Card Template, and not in the fields.

Ref: #6295 and #6855

If Anki Desktop changes this, we'll match their behavior
