### ISSUE TITLE
Request: Option to disable missing media error message.

### ISSUE THREAD

**Issue by vintotal** [ankidroid/Anki-Android#7174]
In version 2.13.0: « Fix Improved messaging when collection is missing media ».

###### Reproduction Steps

1. Add a picture by drap and drop to a card on Anki desktop.
2. Sync only cards, not media on both desktop and Ankidroid.
3. Study on Ankidroid.

###### Expected Result

Like previous versions (2.12.1 and under), when "fetch media" is not active while syncing, avoid showing an error and simply do not show the media that are missing.

###### Actual Result

Show an error message for every card. This message cannot be disabled.

###### Research
*Enter an [x] character to confirm the points below:*

- [X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))
![Screenshot_20200920-102226](https://user-images.githubusercontent.com/1743914/93713662-451e4a80-fb2b-11ea-9bcf-49a09915c46f.jpg)

**Comment by david-allison-1** [comment]
Hi, thanks for the report.

We should only show this message twice per study session: https://github.com/ankidroid/Anki-Android/blob/f5479302a3f3964dad0e6d31c4f974a7dd612002/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/MissingImageHandler.java#L32

We find that people disabling "fetch media" without knowing that it will cause this issue is one of the main problems that people report, and I added this snackbar to cut down on our support issues. 

@mikehardy 

I'd rather avoid adding another preference for this. Would checking for `<!--ANKIDROID:DISABLE-MISSING-IMAGE-WARNING-->` in the card template be acceptable?

**Comment by mikehardy** [comment]
This was a large support request source, so I like the message, it should not go away.

It should only be showing twice though, and I'm not sure what the use case is for having truly missing media, but we're all adults so I'll assume it's valid :-). Probably disk space I'm guessing? Or similar, but that as a hypothetical is enough to grant it as valid, sure

I want to understand more how this shows every time, that seems contrary to the "2 times per study session" rule.

I don't like the idea of toggles implemented in hidden ways. If we make a way to disable it, it should be a real pref IMHO

**Comment by david-allison-1** [comment]
@vintotal Can you confirm that this appears more than twice per review session?

**Comment by vintotal** [comment]
If a session is delimited by the time you spend on reviewing cards without going back to the deck list, it shows only twice. I should have written it shows on every card _that has missing media_. I am sorry it was interpretated as showing every time. Even though in my case the message is not required, it is a minor issue and I think we can live with it. :-) 

If I study for exemple a few card the message shows an error twice. Then, if I go back to the deck list then start reviewing again, the message will show again twice.

**Comment by mikehardy** [comment]
Interesting. Could perhaps be once per review session without being deck specific as an easy back-off on frequency with no other changes

**Comment by david-allison-1** [comment]
I'd be fine to use a global static if that'd be appropriate?

**Comment by mikehardy** [comment]
Seems like an easy way to get 'er done @david-allison-1 -> works for me

**Comment by balta2ar** [comment]
> and I'm not sure what the use case is for having truly missing media,

Just to give you an example, my use case is that some of my cards are automatically generated based on the history of word lookup in the dictionary. The automatically extracted content contains links to media (images) but I don't really care, only text is important to me. I guess proper solution would be for me to adjust the parser/extractor that generates such notes, but of course it's best if I don't have to touch it :)

**Comment by david-allison-1** [comment]
@balta2ar This should be resolved in AnkiDroid 2.13.3 (2 instances of the snackbar per app run). Many thanks for the polite report
