### ISSUE TITLE
Image in cloud can not be loaded correctly in ankidroid.  (html)

### ISSUE THREAD

**Issue by B1INGO** [ankidroid/Anki-Android#7231]
The same image in cloud can not be loaded correctly in ankidroid,but can be loaded correctly in the desktop version.
It makes creazy ;(
- html code: \<img src="http://qiniuimage.*****.top/blog/20190108/a0znKL2coKU3.png">
![html code](https://user-images.githubusercontent.com/20365172/93917862-1f1cc400-fd3e-11ea-9a46-8635e1725a9b.jpg)
- can not be loaded in phone.
![phone](https://user-images.githubusercontent.com/20365172/93917759-f85e8d80-fd3d-11ea-9762-9098b7f06c25.jpg)
- PC version shows good
![Pc](https://user-images.githubusercontent.com/20365172/93917841-162bf280-fd3e-11ea-8b84-a066924a6247.jpg)

**Comment by david-allison-1** [comment]
Hi @B1INGO, you need to use `https`
