### ISSUE TITLE
Android 11: Crop is not supported

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7232]
###### Reproduction Steps

1. Take a picutre
2. Say 'OK' to Crop

###### Expected Result

Crop works

###### Actual Result

![image](https://user-images.githubusercontent.com/62114487/93922095-63da3800-fd09-11ea-9b9b-37966f36c096.png)

###### Debug info
2.14alpha

API 30

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Likely as Android doesn't support a crop intent? 

We should be able to handle this fairly easily if so - need to test on earlier emulators to see if this is a problem.

**Comment by mikehardy** [comment]
If only someone would refactor the image field controller thing so it wasn't such a mess and this would be easier to fix! ;-)

**Comment by david-allison-1** [comment]
Likely a casualty of Scoped Storage in Android 11. Will need to dig into the Android Source Code to see if this is still viable.

Previously, we'd provide a file reference, and the crop intent would use this file as the target to save to.

```java
        intent.putExtra(MediaStore.EXTRA_OUTPUT, imageUri);
```

Now, the user is prompted to save the cropped image by the inbuilt Android editor.

There doesn't seem to be any indication of where this image was saved in the resulting intent

After the crop is completed, the file referenced by `imageUri` is 0 bytes.

**Comment by david-allison-1** [comment]
If you have it working on Android 11, a PR would be much appreciated.

On my emulator, using the default file picker, even after cropping via a `content` URI, the resulting image wasn't saved to the provided URI and instead went to the result of a file picker inside the crop dialog (result was that the crop succeeded, but the image on screen wasn't updated)

I'd love to hear that I missed something. It's fairly likely.

**Comment by mikehardy** [comment]
On the off chance this is related, react-native-share also fiddles with intents and setting flags and such and needed repair for android 11 https://github.com/react-native-share/react-native-share/pull/968

**Comment by mikehardy** [comment]
I have not found any satisfactory solution that relies on other applications via intent for Android 11, and I poked around at it a lot, with the advance knowledge of being the person that got the current implementation working through Android 10.

I'm going to go with either 
1- a very simple library that was medium popular then abandoned and now has an active fork: https://github.com/yaroslav-v/android-crop
2- the most popular library that is abandoned but will surely fork and live somewhere: https://github.com/Yalantis/uCrop

Option 2 has way more features, so I'm going to try that first.

**Comment by mikehardy** [comment]
CALL FOR TESTERS (@arvifox ?)

I believe I have this fixed. Please install a parallel build from this test release and report back:

https://github.com/ankidroid/Anki-Android/releases/tag/v2.14.3-issue7232

It works for me in all cases I could find and actually fixes crop of existing images to boot

That release is build from release-2.14 branch as of now (with android 11 crop fix already cherry-picked in - I'm pretty confident it will work)
