### ISSUE TITLE
Desktop shows review cards due having the number of reviews of subdecks into account

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#7275]
This behaviour changed in desktop at some point. it used to behave like ankidroid

### How to reproduce

![2020-09-24_11-56](https://user-images.githubusercontent.com/4019910/94130584-25ee2880-fe5d-11ea-8845-84cbf2fcc002.png)

#### parent deck
* review limit: 10
* number of cards due: 0

#### sub deck
* review limit: 1
* number of cards due: 10

### Desktop

Parent will show only 1 card due

### ankidroid

Parent will show 10 cards due

PS: sorry captures are from desktop. They are easier to do. I just use them to illustrate what stats im refering to :)

**Comment by voidplayer** [comment]
This still happens

**Comment by voidplayer** [comment]
This still happens

**Comment by voidplayer** [comment]
Could you reopen this too @david-allison-1 ?

I also updated the bug to make it easier to reproduce whats different behaviour from desktop and ankidroid

Thanks!

**Comment by david-allison-1** [comment]
My bad. Thanks!!

**Comment by voidplayer** [comment]
Actually, i have no idea if this still happens. I now use filtered decks for everything and i have no due cards today. I will check it tomorrow

**Comment by voidplayer** [comment]
It now shows the same in desktop and in ankidroid
