### ISSUE TITLE
General stats doesnt show learning cards

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#7279]
desktop shows all due cards (new + learning + review)
![2020-09-24_17-13](https://user-images.githubusercontent.com/4019910/94164574-8004e300-fe89-11ea-9cab-d8bc4749ccc5.png)
![2020-09-24_17-11](https://user-images.githubusercontent.com/4019910/94164590-84310080-fe89-11ea-8c25-90d390945608.png)

Ankidroid  shows only review cards in the general stats: 7 in this example

Desktop behaviour is preferred because it shows 0 in decks with cards in learning :)

PS: sorry captures are from desktop. They are easier to do. I just use them to illustrate what stats im refering to :)

**Comment by david-allison-1** [comment]
Click the stats on the right side of the deck picker and it will show the stats breakdown.

**Comment by voidplayer** [comment]
Yup, im aware!

Thanks

**Comment by david-allison-1** [comment]
I'm really sorry, I'm not sure I understand then. Could you screenshot AnkiDroid to compare?

**Comment by voidplayer** [comment]
Desktop general overview
![2020-09-24_18-55](https://user-images.githubusercontent.com/4019910/94175837-869a5700-fe97-11ea-91e8-f0c3c321b6f3.png)
Android general overview
![Screenshot_20200924-184843_AnkiDroid](https://user-images.githubusercontent.com/4019910/94175871-9154ec00-fe97-11ea-8fcd-2b18f0d823d7.png)
Details:
![Screenshot_20200924-184828_AnkiDroid](https://user-images.githubusercontent.com/4019910/94175880-931eaf80-fe97-11ea-85e0-78eaa4ab7038.png)

**Comment by voidplayer** [comment]
By the way, desktop used to have this same problem. But they fixed it a couple of releases ago

**Comment by voidplayer** [comment]
This still happens

**Comment by voidplayer** [comment]
This still happens

**Comment by mikehardy** [comment]
Note for future people: AnkiDroid is migrating statistics and  libanki (which includes the scheduler) to a new style of use where instead of porting the original Python to Java, we are wrapping the Rust library that AnkiDesktop uses now. Resolution of this issue will require understanding the upstream issue in their Rust code (for scheduler/libanki) or upstream code in svelte/CSS, and fixing it there. PRs to AnkiDroid's java implementation of libanki or stats are not the desired fix at the moment unless they are extremely well-understood and targeted at fixing a small specific issue while the transition happens

**Comment by voidplayer** [comment]
still searching for solutions

This is really annoying because sometimes you have cards pending in learning and the stats shows empty cards pending. And so, you are not able to tell they are left there. Then the next day comes and those cards are learned in the next day... (Even tho i failed the day before)

If i understood your bit correctly, this will be fixed without touching anything once the transition to wrapping the rust library happens

Cool I guess, that means everything will be easier and less bugs. No idea what to do with this bug then :)

Is there an estimation time for this the new change? No rushing or anything, just curious :)

Thanks for working on this!

**Comment by voidplayer** [comment]
This still happens, but i guess this will be fixed automatically in 2.17 or 18?

**Comment by david-allison-1** [comment]
> This still happens, but i guess this will be fixed automatically in 2.17 or 18?

Needs some manual work, but it's on the list to be fixed

**Comment by voidplayer** [comment]
This still happens, but i guess this will be fixed automatically in 2.17 or 18?

**Comment by david-allison-1** [comment]
Should be, but will keep it open

**Comment by dae** [comment]
Should be closed by #14171 - if not fixed in the first 2.17 alpha when it comes out, please let us know.
