### ISSUE TITLE
bug report about preview

### ISSUE THREAD

**Issue by Juddd** [ankidroid/Anki-Android#7286]
I'm in latest verion [2.13.3](https://github.com/ankidroid/Anki-Android/releases/tag/v2.13.3)

###### Reproduction Steps

Enter into Card browser→Change display order→By created time(▼)

Then you select some card to Preview, actually you will preveiw the card by the "By created time(▲)" still. It is a crazy bug.

to preview:

![1](https://user-images.githubusercontent.com/10048069/94356383-79ac7c00-00c0-11eb-8f9a-95c0f3bdf372.jpg)

result of preview:
![2](https://user-images.githubusercontent.com/10048069/94356387-89c45b80-00c0-11eb-89ff-dc396966f649.jpg)

fix it please..

**Comment by david-allison-1** [comment]
Cause: the array is reversed, but `mPosition` is not updated:

https://github.com/ankidroid/Anki-Android/blob/42b92180120040299e590634f5b03d6f352c0a4f/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L254
