### ISSUE TITLE
Anki not working normally on Google Pixel 2

### ISSUE THREAD

**Issue by kr1419** [ankidroid/Anki-Android#7305]
###### Reproduction Steps

1.  Anki is very slow. I go through cards quickly.
2.  I go through 200 cards, anki glitches.

###### Expected Result
Anki is the speed I am used to as in 2.12.1. It is now 75% slower.

###### Actual Result
In this release anki is 75% slower compared to 2.12.1.
After anki glitches, it will not assign any blue or green cards and the cards studied and time studied is frozen.

###### Debug info
AnkiDroid Version = 2.13.3

Android Version = 11

ACRA UUID = 3edb05c7-7ab6-4128-ace6-879c3c806652

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @kr1419, thanks for the report

Could you provide a sample video of both the glitching and AnkiDroid going slowly, I haven't heard any reports of this nature, and both issues are really worrying.

Thanks,

David

**Comment by Arthur-Milchior** [comment]
My main question would be: did you make any change to your collection recently ?

If you accept to spend time working with us on this bug, it would also be interesting to know whether you could reinstall 2.12.1 and see whether anki become as quick as it used to be. ( I don't know how to easily install older version without android studio, so I'll need Mike or David to give you an explanation of how to do it )
Anki became slower when I started to use a lot of deck and subdeck, so it may potentially be related.

Did you try to use "check database" ? It might potentially help too.

**Comment by mikehardy** [comment]
Older versions available as parallel installs for pretty easy testing:

v2.12 stable https://github.com/ankidroid/Anki-Android/releases/download/v2.12.1/AnkiDroid-2.12.1.parallel.A.apk 
v2.11 stable https://github.com/ankidroid/Anki-Android/releases/download/v2.11.2/AnkiDroid-2.11.2.parallel.A.apk
v2 10 stable https://github.com/ankidroid/Anki-Android/releases/download/v2.10.4/AnkiDroid-2.10.4.parallel.A.apk

**Comment by kr1419** [comment]
> 
> 
> My main question would be: did you make any change to your collection recently ?

No, but I did delete a lot of decks that caused slowing.  I have a few add-ons like quizlet importer.

> If you accept to spend time working with us on this bug, it would also be interesting to know whether you could reinstall 2.12.1 and see whether anki become as quick as it used to be. ( I don't know how to easily install older version without android studio, so I'll need Mike or David to give you an explanation of how to do it )

I downloaded 2.12.1 on google play. It works normally. I don't know if the parallel releases are preferred for testing.

> Did you try to use "check database" ? It might potentially help too.

I did this 1-2 weeks ago after I removed a lot of decks that caused slowing, removing 30,000 cards. Still an issue.

**Comment by kr1419** [comment]
@david-allison-1 To get the file, should I connect a usb to my phone then zip it onto my computer? I use different decks, so do you want the one I am mostly using? For the videos, should I make the one of the glitching and the slowed cards separately?

**Comment by david-allison-1** [comment]
> @david-allison-1 To get the file, should I connect a usb to my phone then zip it onto my computer? I use different decks, so do you want the one I am mostly using? For the videos, should I make the one of the glitching and the slowed cards separately?

`collection.anki2` contains all decks, which is ideal for testing.

I mostly use Google Drive to transfer files between desktop and my phone, but USB will work just as well.

**Comment by Arthur-Milchior** [comment]
> > My main question would be: did you make any change to your collection recently ?
> 
> No, but I did delete a lot of decks that caused slowing. I have a few add-ons like quizlet importer.

May I ask which part was/is slow ?

Normally, speed was greatly improved in those past two or three versions, so your report is really unexpected.

> 
> > If you accept to spend time working with us on this bug, it would also be interesting to know whether you could reinstall 2.12.1 and see whether anki become as quick as it used to be. ( I don't know how to easily install older version without android studio, so I'll need Mike or David to give you an explanation of how to do it )
> 
> I downloaded 2.12.1 on google play. It works normally. I don't know if the parallel releases are preferred for testing.

Thanks for the information, I didn't even know you could download previous version directly on the play store 

> 
> > Did you try to use "check database" ? It might potentially help too.
> 
> I did this 1-2 weeks ago after I removed a lot of decks that caused slowing, removing 30,000 cards. Still an issue.

May I ask you to try again on whatever slow collection you have ? I don't really expect it'll make a global solution, but it may help if it's a database problem.

**Comment by kr1419** [comment]
> 
> 
> > > My main question would be: did you make any change to your collection recently ?
> > 
> > 
> > No, but I did delete a lot of decks that caused slowing. I have a few add-ons like quizlet importer.
> 
> May I ask which part was/is slow ?
> 
> Normally, speed was greatly improved in those past two or three versions, so your report is really unexpected.

It is when studying any deck. The answer buttons sometimes don't work, and it won't let me see the next card until I pressed 'again' three times. I can upload a gif of it later.

> 
> > > If you accept to spend time working with us on this bug, it would also be interesting to know whether you could reinstall 2.12.1 and see whether anki become as quick as it used to be. ( I don't know how to easily install older version without android studio, so I'll need Mike or David to give you an explanation of how to do it )
> > 
> > 
> > I downloaded 2.12.1 on google play. It works normally. I don't know if the parallel releases are preferred for testing.
> 
> Thanks for the information, I didn't even know you could download previous version directly on the play store

There is a github link for previous versions on it. I think under the changelog.

> 
> > > Did you try to use "check database" ? It might potentially help too.
> > 
> > 
> > I did this 1-2 weeks ago after I removed a lot of decks that caused slowing, removing 30,000 cards. Still an issue.
> 

> May I ask you to try again on whatever slow collection you have ? I don't really expect it'll make a global solution, but it may help if it's a database problem.

I just tried again. Same issues.

**Comment by kr1419** [comment]
@david-allison-1 

github won't let me upload the anki2 file. This is a google drive link to it.
https://drive.google.com/file/d/1KmVcRtqDcygB0yYficsDLeSdOEGArte6/view?usp=sharing

Here is the video of anki being slow. Seems that there is a problem with pictures displaying too: 
https://gfycat.com/meagerjealousdonkey

**Comment by david-allison-1** [comment]
@kr1419 Could you try: `Settings - Advanced - Safe Display Mode` and see if that reduces the delay?

**Comment by kr1419** [comment]
It doesn't 
https://gfycat.com/conventionalzestyaphid

**Comment by david-allison-1** [comment]
This is going to be a good reason to get #6897 (timing analytics) in.

**Comment by david-allison-1** [comment]
It seems that we may have a problem. I could only get analytics working locally, not for the server.

https://github.com/david-allison-1/Anki-Android/tree/v214-analytics
https://github.com/david-allison-1/Anki-Android/tree/v212-analytics

```
2.12 = pressing Easy through AnKing (3 = ANSWER_CARD)

category/variableName/timeTaken/label: Task/3/295ms/null
category/variableName/timeTaken/label: Task/2/19ms/null
category/variableName/timeTaken/label: Task/3/84ms/null
category/variableName/timeTaken/label: Task/3/76ms/null
category/variableName/timeTaken/label: Task/3/66ms/null
category/variableName/timeTaken/label: Task/3/76ms/null
category/variableName/timeTaken/label: Task/3/67ms/null
category/variableName/timeTaken/label: Task/3/63ms/null
category/variableName/timeTaken/label: Task/3/63ms/null
category/variableName/timeTaken/label: Task/3/73ms/null
category/variableName/timeTaken/label: Task/3/63ms/null
category/variableName/timeTaken/label: Task/3/74ms/null
category/variableName/timeTaken/label: Task/3/51ms/null
category/variableName/timeTaken/label: Task/3/71ms/null
category/variableName/timeTaken/label: Task/3/56ms/null
category/variableName/timeTaken/label: Task/3/63ms/null
category/variableName/timeTaken/label: Task/3/51ms/null
category/variableName/timeTaken/label: Task/3/74ms/null
category/variableName/timeTaken/label: Task/3/51ms/null

2.14

category/variableName/timeTaken/label: Task/ANSWER_CARD/91ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/95ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/71ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/78ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/194ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/392ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/461ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/508ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/550ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/591ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/455ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/465ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/532ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/522ms/null
category/variableName/timeTaken/label: Task/ANSWER_CARD/596ms/null
```

**Comment by david-allison-1** [comment]
Getting errors in the console from (I had been previously, but it seems that this is more of a big deal now):

https://github.com/ankidroid/Anki-Android/blob/252b91bab8d38904918a90342129f3c7a005d1cd/AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java#L1409-L1419

Commenting out the retry brought the execution time down to < 100ms

**Comment by david-allison-1** [comment]
Now, this can easily be fixed by using `intTimeMS()`

But, Anki Desktop uses `intTime() * 1000`: https://github.com/ankitects/anki/blob/70a73b7c6018c3ce3c071a7c5c38d9f57919a778/pylib/anki/schedv2.py#L753

**Comment by dae** [comment]
I think you may have misread the code you linked to David?

**Comment by david-allison-1** [comment]
🤦‍♂️ I did. That makes things easy. Thanks for the correction

```
python
> pp(int(time.time() * 1000))
1601433576963

java
getTime().intTime() * 1000
1601433633000

getTime.intTimeMS()
1601433658574
```

**Comment by kr1419** [comment]
Why do I have a deck called 'default'? I didn't add that. Did someone access my account?

**Comment by david-allison-1** [comment]
> Why do I have a deck called 'default'? I didn't add that. Did someone access my account?

No account details were shared. 

Default is conditionally shown depending on whether it contains a card. It's a deck that can't be deleted, but will be invisible if it's empty.

**Comment by kr1419** [comment]
Thank you

**Comment by mikehardy** [comment]
The fix for this (thank you so much for reporting and working with us, by the way!) is queued for the 2.13.*5* release. 2.13.4 is already out the door and while you haven't received it yet (unless you are in our beta program?) it will not contain the fix. 2.13.5 or the next alpha will contain it, FYI.

I expect 2.13.5 will probably show up on Friday or so

**Comment by kr1419** [comment]
Thanks. I'm glad this can be fixed. I will report if I find anything when 2.13.5 comes out.
