### ISSUE TITLE
How to determine the location of the "Good" button with Javascript API?

### ISSUE THREAD

**Issue by danZ4C** [ankidroid/Anki-Android#7307]
Hey guys, im using the JavaScriptAPI calls to rate the card "Good", but Good button's position varies it can be in the 2nd or the 3rd position (Again/Good/Easy or Again/Hard/Good/Easy) so I will use either buttonAnswerEase2(); or buttonAnswerEase3();

What is the best way to determine where the Good button is?

So far my code check if the time value of the 4th button is empty:

if (AnkiDroidJS.ankiGetNextTime4() == "" ) {
	// 3 buttons present (Again/Good/Easy)
	buttonAnswerEase2();
} else {
	// 4 buttons present (Again/Hard/Good/Easy)
	buttonAnswerEase3();
	
But this solution has stopped working for me twice (shortly just after the JsAPI was released the AnkiDroidJS.ankiGetNextTime4() wasn't returning an empty value even if there were only 3 buttons present. And now it stopped working again with the new glitch of having 4 answer buttons when there should be only 3. https://github.com/ankidroid/Anki-Android/issues/7294
 

Is it possible to use the card type to determine which card should have 3 buttons and which should have 4?

AnkiDroidJS.ankiGetCardType()
0 = new
1 = learning 
2 = review 
3 = relearning

"New" cards have only 3 buttons, I know that much. "Relearning" means failed cards? - i think those have only 3 buttons, right? 
What about "learning" and "review" cards, what are learning cards?

**Comment by david-allison-1** [comment]
Depends on the scheduler version:

https://github.com/ankidroid/Anki-Android/blob/4935ac517deb2d784bba0a9f7793fd2e65f99712/AnkiDroid/src/main/java/com/ichi2/libanki/sched/Sched.java#L160-L177

https://github.com/ankidroid/Anki-Android/blob/252b91bab8d38904918a90342129f3c7a005d1cd/AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java#L364-L372

**Comment by infinyte7** [comment]
May be better implementation for this. Check for all available buttons, if all available then call third button, else call second button.
```
<script>
    if (AnkiDroidJS.ankiGetNextTime1() && AnkiDroidJS.ankiGetNextTime2() && AnkiDroidJS.ankiGetNextTime3() && AnkiDroidJS.ankiGetNextTime4()) {
        // Again / Hard / Good / Easy

        buttonAnswerEase3();
    
    } else if (AnkiDroidJS.ankiGetNextTime1() && AnkiDroidJS.ankiGetNextTime2() && AnkiDroidJS.ankiGetNextTime3() && !AnkiDroidJS.ankiGetNextTime4()) {
        // Again / Good / Easy                                                                                       ^^^^ Note: not
    
        buttonAnswerEase2();
    
    } else if (AnkiDroidJS.ankiGetNextTime1() && AnkiDroidJS.ankiGetNextTime2() && !AnkiDroidJS.ankiGetNextTime3() && !AnkiDroidJS.ankiGetNextTime4()) {
        // Again / Hard                                                           ^^^^^                               ^^^^ Note: not

        buttonAnswerEase2();

    }

</script>
```

**Comment by mikehardy** [comment]
Related: the button instability was fixed also #7308 - the buttons really should be stable and only appear when they are supposed to of course :-)

**Comment by david-allison-1** [comment]
We'd be better to just add an endpoint into the JavaScript API for this

`getRecommendedButtonIndex`?

**Comment by danZ4C** [comment]
> I think we'd be better to add an endpoint into the JavaScript API for this
> 
> `getRecommendedButtonIndex`?

Yes please, it would make life so easier!

Although not sure what is the "recommended button", the "good" one? Yes it would be good to have:

buttonAnswerAgain();
buttonAnswerHard();
buttonAnswerGood();
buttonAnswerEasy();

or use a GET method to get the index of those!

**Comment by Andrej-Adamenko** [comment]
> May be better implementation for this. Check for all available buttons, if all available then call third button, else call second button.
> 
> ```
> <script>
>     function goodButton() {
>         if (AnkiDroidJS.ankiGetNextTime1() && AnkiDroidJS.ankiGetNextTime2() && AnkiDroidJS.ankiGetNextTime3() && AnkiDroidJS.ankiGetNextTime4()) {
>             // Again / Hard / Good / Easy
> 
>             buttonAnswerEase3();
> 
>         } else if (AnkiDroidJS.ankiGetNextTime1() && AnkiDroidJS.ankiGetNextTime2() && AnkiDroidJS.ankiGetNextTime3() && !AnkiDroidJS.ankiGetNextTime4()) {
>             // Again / Good / Easy                                                                                       ^^^^ Note: not
> 
>             buttonAnswerEase2();
> 
>         } else if (AnkiDroidJS.ankiGetNextTime1() && AnkiDroidJS.ankiGetNextTime2() && !AnkiDroidJS.ankiGetNextTime3() && !AnkiDroidJS.ankiGetNextTime4()) {
>             // Again / Hard                                                           ^^^^^                               ^^^^ Note: not
> 
>             buttonAnswerEase2();
> 
>         }
>     }
> </script>
> ```
> 
> Check it may be helpful. I have use this to hide custom designed button to show and hide. https://github.com/infinyte7/Anki-Custom-Card-Layout/blob/master/Example%204/front.html#L223-L247

Thank you for the code. The code worked fine, but it stopped working in AnkiDroid 2.17.0. I wonder if it can be updated, so it works in 2.17.0 and works in the previous versions.

**Comment by krmanik** [comment]
The api is breaking changes in 2.17. I will update the docs and examples later, please use this for now.

```html
<script>
   // A debug console is strongly recommended: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection
   var jsApiContract = { version: "0.0.2", developer: /* your email here */ };
   var api = new AnkiDroidJS(jsApiContract);

   api.ankiGetNextTime1()
   api.ankiGetNextTime2()
   api.ankiGetNextTime3()
   api.ankiGetNextTime4()
</script>
```

https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#get-next-time-for-review-in-webview
