### ISSUE TITLE
Database Error: Don't show "Full Sync From Server" if user does not have AnkiWeb Account

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#7326]

**Comment by Volfee** [comment]
Hey David, happy to try fixing his.

**Comment by mahisharma-cs** [comment]
Hello david, as this issue has no description, but what I understand according to the phrase, "Don't show Full Sync From Server if user does not have AnkiWeb Account", is to hide the icon of Sync from Action bar if the user is not registered on AnkiWeb Account.

I want to work on this issue. As mentioned here, Database Error. So, I would like to work upon that, if you provide any description for that and once look at my pull request #8425 .

I change this from line 778 of DeckPicker.java #8425 

``` case FULL_SYNC:
    if (syncStatus == SyncStatus.NO_ACCOUNT) {
        syncMenu.setVisible(false);
        // syncMenu.setTitle(R.string.sync_menu_title_no_account);
    }

**Comment by david-allison-1** [comment]
Hi @mahisharma-cs, that wasn't what I was intending (but thanks for working on the issue!!!). I'll clarify further on the PR, but the intention is for this line to be changed:

https://github.com/ankidroid/Anki-Android/blob/e034b3851f1b7de0f5864d3c7f830e19de4e5d87/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java#L141-L142

**Comment by gourish3** [comment]
> Hi @mahisharma-cs, that wasn't what I was intending (but thanks for working on the issue!!!). I'll clarify further on the PR, but the intention is for this line to be changed:
> 
> https://github.com/ankidroid/Anki-Android/blob/e034b3851f1b7de0f5864d3c7f830e19de4e5d87/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/DatabaseErrorDialog.java#L141-L142

Can I change it?

**Comment by david-allison-1** [comment]
@mahisharma-cs Are you still working on this issue?

@gourish3 Give them 24 hours to respond, if they don't: give me a ping and you'll be free to work on it

**Comment by gourish3** [comment]
Okay Sir!

**Comment by david-allison-1** [comment]
> Okay Sir!

Great! (and no need to call anyone here Sir! 🙂)

**Comment by mahisharma-cs** [comment]
> @mahisharma-cs Are you still working on this issue?
> 
> @gourish3 Give them 24 hours to respond, if they don't: give me a ping and you'll be free to work on it

Yes! within 18-24 hrs. I'll make the pull request on this. I am stuck in data handling but now it is send the "Full Sync From Server" is working.

**Comment by gourish3** [comment]
Okay Take your time .If you cannot do it please tell me. Ill work on it then.

**Comment by gourish3** [comment]
> > Okay Sir!
> 
> Great! (and no need to call anyone here Sir! 🙂)

Okay!🙂
