### ISSUE TITLE
Card text appears with a delay when connected to internet 

### ISSUE THREAD

**Issue by indexxd** [ankidroid/Anki-Android#7328]
###### Reproduction Steps

1. Import this deck here into ankidroid: https://filebin.net/tpl9lj6u611e9n1j
2. Turn on internet connection (wifi or data)
3. Start reviewing the deck

###### Expected Result
The card text (front or back) should appear instantly.

###### Actual Result
The text takes about 15-30 seconds to appear on the screen for every card. This doesn't happen on the desktop version. I tested it on two different devices and two different accounts and the results were always the same.

###### Debug info
AnkiDroid Version = 2.13.3
 
Android Version = 10
 
ACRA UUID = 04fdd41e-7702-4ac4-ac83-bf87f0dafe29
 
Scheduler = std
 
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @indexxd, thanks for the report

Does this delay occur on AnkiDroid 2.12.1: https://github.com/ankidroid/Anki-Android/releases/download/v2.12.1/AnkiDroid-2.12.1.parallel.A.apk

**Comment by indexxd** [comment]
Yes it does. Also I just tried version 2.9 and the delay is there too. (the issue has been going on for a while now, I think it started happening around the beginning of the year?)

**Comment by david-allison-1** [comment]
@indexxd Oh dear, it'd be useful if you could find the version where it was working as expected so we can pinpoint the issue. 

This could potentially be a WebView update on your phone, in which case it may be a struggle to work around it.

**Comment by david-allison-1** [comment]
@indexxd 

Just had a look at the file. This is a card template issue.

The CSS contains a reference to `Helvetica Neue` which is stored on a website which is now down.

Could you please find the font, then follow the instructions below to use it in your collection (or just remove the reference to the font)

https://docs.ankiweb.net/#/templates/styling?id=installing-fonts

In AnkiDroid, you can edit a card template by editing a note, and clicking the "Cards" button under tags. Please back up the CSS to a text file/note somewhere before you perform the change.

**Comment by indexxd** [comment]
Oh man, thank you so much! Removed the font and it works great. Thank you for your time.
Have a good day.

**Comment by david-allison-1** [comment]
No worries, glad it was something simple! Don't forget to send over a rating if you got us from an App Store
