### ISSUE TITLE
Changelog confusing to some users

### ISSUE THREAD

**Issue by tbm** [ankidroid/Anki-Android#7333]
I installed AnkiDroid on my friend's phone a few weeks. I asked today how things were going and she said she stopped using it because something appeared on the screen and she didn't know what to do.

She showed me and it was the changelog pop-up.  There was a lot of text and scrolling down took forever.

It even took me a bit to see the "Continue" button at the bottom.

My suggestion:

1) Maybe make that "Continue" button slightly larger or something; or make it more obvious that the changelog window is a "popup" window that can be closed.

2) When the changelog is displayed and the user exits AnkiDroid (e.g. by pressing back), remove the changelog window so it won't be shown next time.

(Another question is whether the changelog should be shown by default at all.  I'm not sure I pay attention to it much and I'm a technical user who cares about that kind of stuff... but not when I'm trying to study vocabulary ;)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, thanks for the report. What version was this for?

2) should already be implemented in #7142 (2.13.2)

**Comment by mikehardy** [comment]
Could also put the continue button at the top perhaps, I understand most might just tap through quickly, that's fine. David already put in a change so the back button works (odd it did not before!) so it won't be endless though, what a terrible way to lose a user!

I do like that it shows by default for a couple reasons, one is that we frequently interact with people and tell them to watch for the next version, then to me the changelog closes the loop for those users and we do get success (or continued failure reports) referencing the entries where their issue was mentioned. The other is that I've started putting our github closed issue milestone link in them and that link has bubbled up a few times in our referrer list as one of our most popular ingress points. Coincidentally it is associated with new first contributions from developers and that is quite literally the lifeblood of the project, so it appears to be effective as developer recruitment publicity

Definitely should be able to blitz through it though, no argument there

**Comment by david-allison-1** [comment]
The back button worked, but the toolbar didn't have the typical "Back" icon.

We've recently added a "Rate App" button to the screen, and it'd be a shame to not try that out.

**Comment by tbm** [comment]
> Hi, thanks for the report. What version was this for?

She was on 2.13.4.

Thanks for your fast response!

She received 2.13.5 in the meantime.  She know knows what to do but it's still not very intuitive.  Unfortunately I don't have further suggestions on how to improve it.

She thought it was some legal agreement that she had to accept and didn't know what to do, so she ignored it.
