### ISSUE TITLE
Displaying tags not working.

### ISSUE THREAD

**Issue by Acelya-9028** [ankidroid/Anki-Android#7336]
###### Reproduction Steps

1. create a card with {{Tags}}
2. see it

###### Expected Result

Display my tags.

###### Actual Result

Display {{Tags}}.

![Screenshot_20201003-152106_AnkiDroid](https://user-images.githubusercontent.com/45818681/94992875-3ef98680-058d-11eb-95ea-b87199bba9a9.jpg)
![Screenshot_20201003-152046_AnkiDroid](https://user-images.githubusercontent.com/45818681/94992878-46b92b00-058d-11eb-9e3e-c46dc7efbb76.jpg)

###### Debug info

AnkiDroid Version = 2.13.2
Android Version = 10
ACRA UUID = 5c8fb2f3-f637-4a3d-8512-52d4122b6ca4
Scheduler = std

###### Research

*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

- [x ] I have searched for similar existing issues here and on the user forum

- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
{{Tags}} now needs to go on the card template, please either use a new note type, or edit the card template of an existing note type.

Rationale: #6295

**Comment by Acelya-9028** [comment]
Thank you for the help :D!

**Comment by david-allison-1** [comment]
No worries, don't forget to rate the app!
