### ISSUE TITLE
Suggestion: Allowing Hacktoberfest contributions

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7337]
We can join the [hacktoberfest](https://github.com/topics/hacktoberfest) topic to encourage new users to contribute. 

I'd be happy to put time into doing a writeup of what we're after, and helping new contributors with issues.

**Comment by mikehardy** [comment]
Sure! If you want to drive it, drive on :-). In my experience working with fresh developers, preparation is everything. Precise task description, precise / objective acceptance criteria are critical. It frequently takes more time to do that well than it would to do the task itself but that's not necessarily a deal breaker, when viewed as an educational outcome it can be quite rewarding and there is a lottery ticket chance of a new long term contributor which would be a huge payoff.

**Comment by david-allison-1** [comment]
I won't have the time - happy to mark contributions as accepted, but won't be able to mentor people through the PR process.

**Comment by mikehardy** [comment]
Just as an anecdotal data point I got a blast of high quality contributions from this on react-native-device-info repo with no advertising whatsoever :-) - I can see how quality might be variable but if it works even some of the time, I'm positive on it as an idea at least.
