### ISSUE TITLE
Possible Lint Check: Members which do not meet naming conventions

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7338]
This may be possible to handle from the `android-studio` auto-lint tool. Investigate that before writing the check.

Example: `MetaDB.mMetaDb` should be `MetaDB.sMetaDb`

**Comment by Arthur-Milchior** [comment]
I think I saw some warnings about wrong variable names. I have already quite a few PR open, so was waiting for them to go down before going after more lints
