### ISSUE TITLE
.APK files are opened in AnkiDroid

### ISSUE THREAD

**Issue by kotx** [ankidroid/Anki-Android#7339]
###### Reproduction Steps

1. Download a .apk file (I used Firefox Nightly for this)
2. Try to open the .apk from the browser

###### Expected Result
The package installer gets opened and the user can install an APK.

###### Actual Result
AnkiDroid gets opened with the message "This isn't a valid Anki package file. Filename xxxx doesn't have .apkg or .colpkg extension"

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
```
AnkiDroid Version = 2.12.1

Android Version = 10

ACRA UUID = 2db7dcf6-3c52-4ba3-b8c0-dbd7af878fb8
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @kotx

Does it work for you on Firefox stable? Can't reproduce on 81.1.1

Are you sure the file was an `apk`, and not an `apkg`?

Relevant code

https://github.com/ankidroid/Anki-Android/blob/28276da066f3a2842f3ec5dc9fee861358a19e5f/AnkiDroid/src/main/AndroidManifest.xml#L83-L150

**Comment by david-allison-1** [comment]
Also note that we're up to AnkiDroid 2.13.4.

2.12.1 is an older version, but I don't recall any changes to this aspect of the code.

**Comment by kotx** [comment]
> Does it work for you on Firefox stable? Can't reproduce on 81.1.1
I'm on Firefox Stable 81.1.2 and the bug is still there. Edge 45.08.4.5074 seems to work properly though.

**Comment by kotx** [comment]
> 
> 
> Also note that we're up to AnkiDroid 2.13.4.
> 
> 2.12.1 is an older version, but I don't recall any changes to this aspect of the code.

On 2.13.4 and the issue still exists. The app is installed from F-Droid, if that's relevant.

**Comment by david-allison-1** [comment]
Would you consider submitting this to Mozilla's Bugzilla - it seems to be a Firefox issue rather than an issue in Android's package loading (given that it works in Edge). 

If there is a bug in the above code, it doesn't appear apparent to me, but I'm more than happy to be mistaken. My guess is that an apk is a zip file, and we're acting as a zip reader on the system.

Which device are you using?

**Comment by kotx** [comment]
> Which device are you using?

moto g power XT2041-4 with Android 10 & stock rom.

**Comment by kotx** [comment]
I opened an issue in Firefox's repo- if this isn't a bug with Firefox I'll reopen this issue.

**Comment by david-allison-1** [comment]
> I opened an issue in Firefox's repo- if this isn't a bug with Firefox I'll reopen this issue.

Thanks, do you have a link?

**Comment by Arthur-Milchior** [comment]
I had the problem that ankidroid tried to open anything that is a valid zip file.  I only had this problem on emulator, so it never was a real problem. 
APK being valid zip file, it may explain the problem.
No idea how to correct it however

**Comment by ninadpchaudhari** [comment]
+1 face the same problem when opening an APK from Chrome. 

If we go to File / File Browser and open the APK then the same works fine.
