### ISSUE TITLE
Click on "Hint" makes the answer appear automatically after 1 second

### ISSUE THREAD

**Issue by Bortex19** [ankidroid/Anki-Android#7340]
###### Reproduction Steps

1. Create a hint
2. When studying, click on it before clicking on "show answer" or touching the screen anywhere.
3. The answer will show up automatically after 1 second (more or less), making hint function useless.

###### Expected Result
Answer won't show up until you touch the option or slide on the screen.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.13.4

Android Version = 10

ACRA UUID = 6a0fb5a8-c396-47cb-b90b-f266e3122125

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [ X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @Bortex19, thanks so much! When did this start happening?

**Comment by david-allison-1** [comment]
Appears I was testing with gestures enabled.

@Bortex19 Can you Enable: `Settings - Gestures - Ignore Touch Gestures on Links`

**Comment by Bortex19** [comment]
It has worked!!
Thank you very much, David.

Was it my fault or should the Hints not function the way they were? I thought maybe I was accidentally tapping the screen while grabbing the phone so I put it on the desk and just tapped the hint, but it showed the answer anyway after a 'blink'.

**Comment by david-allison-1** [comment]
It's an arguable thing: some people wanted link clicks to go through gestures, but that was a change in behaviour from how we used to do things

It seemed easier to add a preference rather than annoy one group of people.

But, maybe it's time to get rid of the preference and set it as a default.

Anyway, glad to have helped. Don't forget to rate the app. Stay safe and enjoy your weekend.
