### ISSUE TITLE
Side menu does not correctly close

### ISSUE THREAD

**Issue by julienbaley** [ankidroid/Anki-Android#7344]
###### Reproduction Steps

1. click on the very left edge of the deck menu (i.e. slightly left of the '>' for folded decks)
2. try to click anywhere on the screen

###### Expected Result

One should be able to click anywhere and e.g. access decks.

###### Actual Result

After 1. the side menu pops up a little bit (roughly up to the '>' icons). In 2., the menu retracts, but the screen is unresponsive until you actually slide the side menu completely open and then close it back.

###### Debug info

As far as I know, it was there in a recent update (already present prior to the 20-09-29 one)

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @julienbaley, thanks for the report.

Could you provide debug information: `Settings - Advanced - About AnkiDroid - Copy Debug Info`

Could you download: https://github.com/ankidroid/Anki-Android/releases/download/v2.12.1/AnkiDroid-2.12.1.parallel.A.apk and see if the problem occur then.

Could you provide a short screen recording of the issue - I can't reproduce this on my phone

**Comment by julienbaley** [comment]
It seems to be gone with the alpha. For the sake of the report, here's what I had before the alpha:

AnkiDroid Version = 2.13.4

Android Version = 9

ACRA UUID = 5a15499c-8686-431f-afe7-bb85d64c77fa

Scheduler = std

And a screen recording of it
https://photos.app.goo.gl/56q1ANjP12DaL98Q7

**Comment by david-allison-1** [comment]
Thanks! What's the version of the alpha that solved it.

**Comment by julienbaley** [comment]
I've used the link you've posted in your previous comment. (I realise it may not be an alpha)

**Comment by david-allison-1** [comment]
@julienbaley Which device are you using?

**Comment by julienbaley** [comment]
OnePlus 3 on Oxygen OS 9.0.6 (Android 9)

**Comment by david-allison-1** [comment]
@julienbaley 

Could you test on:

https://github.com/ankidroid/Anki-Android/releases/tag/v2.14alpha4 - I expect this to work
https://github.com/ankidroid/Anki-Android/releases/tag/v2.14alpha5 - I expect this to fail

Thanks

**Comment by julienbaley** [comment]
Both "work" (the side-menu doesn't pop up when clicking near the border of the screen, and therefore the rest of the bug doesn't happen).

**Comment by david-allison-1** [comment]
That's unexpected

https://github.com/ankidroid/Anki-Android/releases/download/v2.14alpha9/AnkiDroid-2.14alpha9.parallel.A.apk - I expect this to work
https://github.com/ankidroid/Anki-Android/releases/download/v2.14alpha10/AnkiDroid-2.14alpha10.parallel.A.apk - I expect this bug to appear

**Comment by david-allison-1** [comment]
I can only trigger this if "Safe Display Mode" is enabled. 

@julienbaley Could you try disabling this setting and seeing if this problem goes away?

**Comment by julienbaley** [comment]
It does indeed go away!
Is it possible to fix it, still? Of the two (this bug and the animations), the animations are far more annoying for me :)

**Comment by david-allison-1** [comment]
Absolutely possible now I've tracked it down - I probably won't have the bandwidth to look at it this week, but please tag me if I haven't managed to resolve this in the next fortnight

Thanks for the fast response!

**Comment by julienbaley** [comment]
Superb :)
It's not too urgent, but happy to ping if that helps.

**Comment by julienbaley** [comment]
@david-allison-1 here is your "bump" :)

**Comment by david-allison-1** [comment]
I needed that, thanks! I'm out tonight so won't be able to look at it today, but I plan to get it done tomorrow. 

Please bump again in 24 hours if it's not assigned
