### ISSUE TITLE
Upgrade to API30 targetSdkVersion

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#7348]
If Google follows precedent, the deadline for apps to use this before they are blocked from sending updates to the Play store will be on or around the last day of October 2021

**Comment by mikehardy** [comment]
Way too important to close :-)

**Comment by 4D17Y4** [comment]
Hey @mikehardy I want to take this up,
As far as I understood we just have to update sdkVersions to the 30 in build.gradle ?

**Comment by david-allison-1** [comment]
This is going to be a large change  as we can no longer use legacy storage in API 30:

https://github.com/ankidroid/Anki-Android/blob/4030ac3d4b29569ff35a35adcc251f9026c59e92/AnkiDroid/src/main/AndroidManifest.xml#L68

See: #5304

I'll mark this as 'blocked by dependency', as most of the work will be in the above issue.
