### ISSUE TITLE
Show Hint Key Shortcut for ankidroid

### ISSUE THREAD

**Issue by sajith855** [ankidroid/Anki-Android#7354]
I have a request to add a key shortcut for Show hint during review because it will help to do reviews with Controller and many of my cards have Hint. Please add Key H for show hint

**Comment by david-allison-1** [comment]
Hi @sajith855, sounds like a good idea. Would you be interested in implementing this?

Would you want all hints to be revealed, or one at a time?

**Comment by sajith855** [comment]
> Hi @sajith855, sounds like a good idea. Would you be interested in implementing this?
> 
> Would you want all hints to be revealed, or one at a time?

I prefer one hint at a time please include in next update waiting for this😺

**Comment by Arthur-Milchior** [comment]
I see no PR linking to this, so I assume this feature request is still relevant. Keeping it open, as it makes perfect sens.

@sajith855 Do you think hints should be opened in the text order, or should a more complex order be used ? Do you know whether there is anything used by add-ons or upstream anki to decide the order ?

**Comment by Abanoub-Asaad** [comment]
Could you please provide a detailed description of the issue?

**Comment by IAmJaishree** [comment]
@david-allison-1 @Arthur-Milchior  I am interested in working on it, can I start on it?

**Comment by pree-T** [comment]
I am interested to work on it.May I start?

**Comment by pree-T** [comment]
I am interested. May I start working on this?

**Comment by Arthur-Milchior** [comment]
> Could you please provide a detailed description of the issue?

Do you have any specific question. Because I fear I have no idea what more to add. 


> @david-allison-1 @Arthur-Milchior I am interested in working on it, can I start on it?

Sorry for the delay, it's hard to read everything. I recall you were given another harder task recently, so if it's okay, I'll go with @pree-T

**Comment by david-allison-1** [comment]
I need a better system for going through my notifications. Sorry I missed this.

* Anki has a `{{hint:}}` field feature:

https://docs.ankiweb.net/#/templates/fields?id=hint-fields

The requester would like to be able to trigger each hint field in order.


* Add the functionality
* Add a Command: https://github.com/ankidroid/Anki-Android/blob/ec5d9e535c391a150e3489ceb515426a3946c305/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.java#L66-L65
* Add a keyboard shortcut: https://github.com/ankidroid/Anki-Android/blob/d74d72624c604d9e3f63e7c6a3d55a5b0bb11345/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java#L120-L119

Off-topic: We'll be making keyboard shortcuts variable in a later version of AnkiDroid

**Comment by tapish2000** [comment]
Is anyone working on this?

**Comment by Arthur-Milchior** [comment]
It seems that nobody work on it. we got no confirmation from @pree-T and no news for a week from @IAmJaishree , so go for it @tapish2000

**Comment by prince-09** [comment]
Anybody working on it? Can I continue this?

**Comment by tapish2000** [comment]
I was working on this initially but now, I have 2 other issues to work on, you can take it @prince-09

**Comment by cdhiraj40** [comment]
hey, @david-allison-1 @Arthur-Milchior I would like to know more about this and will sure like to work too. Thanks.

**Comment by david-allison-1** [comment]
@prince-09 Do you still have the time to work on this?

**Comment by cdhiraj40** [comment]
@david-allison-1 as it's been so much time and no response from @prince-09 I would like to work on this but before that can you provide me some more info? I'm new here. Thanks!

**Comment by david-allison-1** [comment]
> @david-allison-1 as it's been so much time and no response from @prince-09 I would like to work on this but before that can you provide me some more info? I'm new here. Thanks!

I've given a brief explanation in https://github.com/ankidroid/Anki-Android/issues/7354#issuecomment-803271657 . The code has moved around a little, but you can Ctrl+Shift+F for the constants to find the new locations.

https://docs.ankiweb.net/templates/fields.html?highlight=hint#hint-fields will be useful.

Please let me know what information you'd like.

**Comment by cdhiraj40** [comment]
> > @david-allison-1 as it's been so much time and no response from @prince-09 I would like to work on this but before that can you provide me some more info? I'm new here. Thanks!
> 
> I've given a brief explanation in [#7354 (comment)](https://github.com/ankidroid/Anki-Android/issues/7354#issuecomment-803271657) . The code has moved around a little, but you can Ctrl+Shift+F for the constants to find the new locations.
> 
> https://docs.ankiweb.net/templates/fields.html?highlight=hint#hint-fields will be useful.
> 
> Please let me know what information you'd like.

sure I will give it a read, thanks :)

**Comment by david-allison-1** [comment]
A key shortcut is defined in the "Controls" section of the preferences.

This allows you to map a keyboard/gamepad button to an action in the reviewer.

https://github.com/ankidroid/Anki-Android/blob/e93a3251ef14bb285b09473ee1b13681398e8a85/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.java#L39-L38

**Comment by cdhiraj40** [comment]
> A key shortcut is defined in the "Controls" section of the preferences.
> 
> This allows you to map a keyboard/gamepad button to an action in the reviewer.
> 
> https://github.com/ankidroid/Anki-Android/blob/e93a3251ef14bb285b09473ee1b13681398e8a85/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.java#L39-L38

Hey @david-allison-1 , I can't find this file in the master branch, can you tell me how to access it?
and also how to test the code which I'm gonna write as it's for desktop(that's what I currently have in my mind) and the repo is for the android app.

**Comment by david-allison-1** [comment]
It should exist in master. Use Ctrl+T to search for it

**Comment by cdhiraj40** [comment]
> It should exist in master. Use Ctrl+T to search for it

oh sorry not that one , this one  https://github.com/ankidroid/Anki-Android/blob/d74d72624c604d9e3f63e7c6a3d55a5b0bb11345/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/PeripheralCommand.java#L120-L119

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/e93a3251ef14bb285b09473ee1b13681398e8a85/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/ViewerCommand.java#L149-L206

**Comment by cdhiraj40** [comment]
hey @david-allison-1 I'm having a problem in adding hints in the card, I know how to add in Anki but I guess the same method doesn't work in anki-android. (I have written code and wanna test). Thanks

**Comment by david-allison-1** [comment]
> hey @david-allison-1 I'm having a problem in adding hints in the card, I know how to add in Anki but I guess the same method doesn't work in anki-android. (I have written code and wanna test). Thanks :)

What have you tried? What goes wrong?

**Comment by cdhiraj40** [comment]
> > hey @david-allison-1 I'm having a problem in adding hints in the card, I know how to add in Anki but I guess the same method doesn't work in anki-android. (I have written code and wanna test). Thanks :)
> 
> What have you tried? What goes wrong?

I have tried this ```{{#Hint}}{{hint:Hint}}{{/Hint}}```
```Hint Field 1:{{ hint:Field 1}}

**Comment by david-allison-1** [comment]
Why not just use `{{hint:Hint}}`? You shouldn't need conditional replacements for the feature.

Keyboard shortcuts are listed [above](https://github.com/ankidroid/Anki-Android/issues/7354#issuecomment-927043197)

**Comment by cdhiraj40** [comment]
Hey @david-allison-1, Sorry for the late I had academic exams, I will make PR can you check as I'm still having a problem with where to add functionality that works after clicking the "H" key, hope you can help. Thanks :)

**Comment by david-allison-1** [comment]
Viewercommand::getDefaultValue

**Comment by cdhiraj40** [comment]
> Viewercommand::getDefaultValue
I did add this code there but I didn't get the hint shown
 ``` case COMMAND_SHOW_HINT:
                return from(keyCode(KeyEvent.KEYCODE_H, CardSide.QUESTION));```
