### ISSUE TITLE
Type-in-the-answer cards don't update their answers immediately if you edit them during a study session

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7363]
Reported from a Google Play Review. Needs investigation.

**Comment by 152334H** [comment]
Hi, here's an example.

Starting off with this card:
![](https://raw.githubusercontent.com/152334H/middleofnowhere/master/anki_inserted_answer.png)

Which originally has these options:
![](https://raw.githubusercontent.com/152334H/middleofnowhere/master/anki_original_answer.png)

Edited to have a different answer:
![](https://raw.githubusercontent.com/152334H/middleofnowhere/master/anki_new_answer.png)

Has the original answer after submission: 
![](https://raw.githubusercontent.com/152334H/middleofnowhere/master/anki_wrong_answer.png)

**Comment by david-allison-1** [comment]
I'll get to this tomorrow

This happens on both the front and the back of the card.

`updateTypeAnswerInfo` is not called

`data.hasExtra("reloadRequired")` - false

----

Cause:

https://github.com/ankidroid/Anki-Android/blob/a7a4aa033fd78902f9da97be35990426f365eec9/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L557-L572

The type answer is only changed if the card is updated. Either we need a new handler for when the card is updated from a note edit, or we need to make updating the type answer unconditional.
