### ISSUE TITLE
All cards reversed 

### ISSUE THREAD

**Issue by dms545** [ankidroid/Anki-Android#7364]
###### Reproduction Steps

1. Opened ankidroid on my phone after updating the platform on my computer
2. All of my cards on my phone are reverse, aka, showing the answer not the question
3. I mostly have basic cards and few basic and reversed. 
I tried resyncing and uninstalling and reinstalling the app 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
Hi,

Would you accept to share with us a card with the bug (you can export a single note from the computer app)
and/or
a screenshot from the template of the card, of the note content, and of the question side of your card

**Comment by dms545** [comment]
Hi,I've attached 2 photos, I hope that's what you're looking for. -------- Original Message --------Subject: Re: [ankidroid/Anki-Android] All cards reversed  (#7364)From: Arthur Milchior To: ankidroid/Anki-Android CC: dms545 ,Author 
Hi,
Would you accept to share with us a card with the bug (you can export a single note from the computer app)
and/or
a screenshot from the template of the card, of the note content, and of the question side of your card

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/ankidroid/Anki-Android/issues/7364#issuecomment-705275061",
"url": "https://github.com/ankidroid/Anki-Android/issues/7364#issuecomment-705275061",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by Arthur-Milchior** [comment]
Thank you very much. However, it seems you answerd by mail, and joint files are not preserved. You'll need to post them directly on https://github.com/ankidroid/Anki-Android/issues/7364, sorry

**Comment by dms545** [comment]
Added to previous comment. Thanks!

**Comment by david-allison-1** [comment]
Hi @dms545,

This is caused by using the "Flip" functionality in Anki Desktop. This flips all of the "Basic" cards, not just the selected one.

To fix this, either edit the card template in Anki Desktop and "Flip" it back

Or:

* Edit a Card
* Select Cards (under tags)
* You'll see a Front Template containing {{Back}} and a back template containing {{Front}}
* Move {{Front}} to the Front, and {{Back}} to the back

Thanks for the report, and thanks for using AnkiDroid

David

**Comment by dms545** [comment]
It took a lot of searching but I found what you were referring to. Thank you so much! No idea how that happened
