### ISSUE TITLE
Feature Request: Happy sound on success

### ISSUE THREAD

**Issue by samjones3** [ankidroid/Anki-Android#7365]
I use anki and duolingo for language learning.

I have found that I am a bit addicted to the "happy sound" duolingo gives when I get something right. (Those dopamine engineers... the dang stuff works!)

I would like Anki to have a similar option.

Is this configurable?
(And if not , how do I make a feature request?)

Thanks!

**Comment by mikehardy** [comment]
Hi there! We get requests for UI changes (including animation and sound) frequently and in my experience any changes in this area make everyone unhappy, and we end up having to make it a preference so whatever it is can be disabled, with the end result that we support 2 or more of everything and it's a maintenance burden that's difficult to bear with a small volunteer crew

So we've gone a different direction. You can now do anything you like in the review experience, without waiting or asking for it to be accepted as a feature

We export a Javascript API that lets you do anything you like in the review experience, you can replace the button bar with your own buttons, and when tapped they may produce sound

https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

**Comment by rwmpelstilzchen** [comment]
Nevertheless, I think having a way to customize card appearance across note-types would be great.
