### ISSUE TITLE
v2.14alpha17 - widget not working

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#7366]
###### Reproduction Steps

1. Place the 1x1 widget on the homescreen

###### Expected Result

It shows the number of due reviews and ETA

###### Actual Result

![Screenshot_20201008-112046~(1)](https://user-images.githubusercontent.com/45192213/95440282-0c6ad780-0959-11eb-8799-a86044a414a1.jpg)

It shows an error message and doesn't open Ankidroid on tap.

###### Debug info
AnkiDroid Version = 2.14alpha17

Android Version = 9

ACRA UUID = 1f29f610-893a-403f-83d5-25a26ba97fe0

Scheduler = std2

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
No crash reports. Reproduced on my phone

**Comment by david-allison-1** [comment]
`2020-10-08 12:24:24.864 3383-3383/? W/AppWidgetHostView: Error inflating RemoteViews : android.view.InflateException: Binary XML file line #30: Binary XML file line #30: Error inflating class com.ichi2.ui.FixedTextView`

/sigh

Cause: https://github.com/ankidroid/Anki-Android/pull/7352

**Comment by david-allison-1** [comment]
`2020-10-08 12:24:24.864 3383-3383/? W/AppWidgetHostView: Error inflating RemoteViews : android.view.InflateException: Binary XML file line #30: Binary XML file line #30: Error inflating class com.ichi2.ui.FixedTextView`

/sigh

Cause: https://github.com/ankidroid/Anki-Android/pull/7352

**Comment by david-allison-1** [comment]
@Anthropos888 Great catch! Thanks
