### ISSUE TITLE
Android 11: Swipe-down gesture in fullscreen mode no longer working

### ISSUE THREAD

**Issue by nwwt** [ankidroid/Anki-Android#7375]
Dunno if this issue is actually due to AnkiDroid (2.1.4a18), but on Android 11 (today's OxygenOS 11 stable) with fullscreen mode enabled, the gesture to bring the reviewer's top bar into view is not working. Instead it yields (cropped):

<img src="https://i.imgur.com/3vWewVt.png">

(Repeated gesture then brings the system's quick settings, as usual.)

**Comment by nwwt** [comment]
Seems [quite a few games](https://support.google.com/pixelphone/thread/71645505?hl=en) have been affected by this as well. Some random comment there claims it's fixed with this month's patch for Android 11 (dunno yet, I'm on November).

**Comment by nwwt** [comment]
Got the January Android patch now, the issue is **not** fixed by it.

**Comment by mikehardy** [comment]
Should have stayed open, hopefully someone takes interest in fixing it :pray:

**Comment by nwwt** [comment]
I think I at least found a condition now:

It only occurs if both _"Navigation Gestures"_ (replacing the virtual fixed navigation bar) and _"Hide the Bottom Bar"_ (that white line then shown) are enabled.

(Both in system _"Settings"_ → _"Buttons & Gestures"_ → _"Navigation Bar & Gestures"_.)

The bottom bar is also hidden by AnkiDroid's _"Hide the system bars"_ (if selected) and only comes into view when swiping down.

Also, AnkiDroid's reviewer "jumps up" regardless of what the system's _"Hide the Bottom Bar"_ is set to. That is, while the WebView usually starts just below the hole-punch camera of my phone's screen, while the swipe-down gesture is triggered, it will instead move to start at 0 / from the very top (for no reason, and that extra area is obscured below the system's status bar anyway).

**Comment by mikehardy** [comment]
This one may or may not have been fixed - is it still reproducible on latest alphas?

**Comment by nwwt** [comment]
It's still present, as is said "jump".

Though the workaround of deactivating Android's/OnePlus's _"Hide the Bottom Bar"_ also still works.

**Comment by nwwt** [comment]
As late follow-up, in case another hits this behavior: I'm sure it's a broken OEM change (by OnePlus) given now that I've installed the Magisk module [Fullscreen/Immersive Gesture Tweeks](https://github.com/Magisk-Modules-Repo/HideNavBar), the bar is hidden and AnkiDroid  & co. still just work fine.

**Comment by michalpatryk** [comment]
This problem has resurfaced for me in s20fe with Android 13.

**Comment by twwn** [comment]
Similar for me it's bugged again as well: The swipe-down gesture causes both Anki's top bar & the Android 13's quick settings menu to come into view. By the time I've managed to close the latter, the top bar has timed out & vanished again.

**Comment by michalpatryk** [comment]
Yeah, it would be great if gestures had "toggle fullscreen" option, it would fix it easily.
