### ISSUE TITLE
Add ability to move all cards for a selected note to different deck

### ISSUE THREAD

**Issue by evilVR6** [ankidroid/Anki-Android#7376]
Can you make it possible to move entire notes between decks? I have an old Japanese deck and a new one. Sometimes I review the old deck and find some old goodies and wish to put them in my main Japanese (new) deck. When I find and select the card, it's either the production or recognition, but the other side of the note usually has a different interval so it doesn't appear nearby.
When I search for the card to move it, I cannot find the other card of the pair because it hasn't been touched, it's buried, and I'm sorting the list by last modified. 
Can there be a box to check-off that says "Do you want to move the matching card of the production/recognition pair too?" Or something like that?

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by sudomain** [comment]
> When I search for the card to move it, I cannot find the other card of the pair because it hasn't been touched, it's buried, and I'm sorting the list by last modified.

What if you sorted by note modification time or the sort field?

**Comment by david-allison-1** [comment]
This is possible in AnkiDroid 2.14:

* Select a Card in the Card Browser/Reviewer
* Card Info
* Select the Note ID
* search for `nid:[note id]` in All Decks
* Move cards

I've just added a pull request to make this functionality easier (making the NoteId Copy/Pasteable).

Thanks

David

**Comment by evilVR6** [comment]
I don't see a place to select card info.

At any rate this doesn't work for me because I don't want to do this card
by card, I want to search for the card(s) by modification time so that the
cards that I just studied come up first. Then I want to be able to switch
them from an old deck to a new deck. The problem is that I can only take
the production side or recognition side, whatever I just studied, it won't
take the entire note. No method of sorting has been able to find me both. I
just studied 10 things from an old review deck, I want the notes in my new
deck. No matter what I do I only have 10 new reviews. It should be 20.

Am I missing something completely simple?

**Comment by sudomain** [comment]
What about tags? Tags apply to all cards of a note (recognition and production in your case). While reviewing, you can use the `Edit tags` or `Mark note` to add a tag. Marking the note will toggle the `marked` tag, while `Edit tags` will give you a list of your existing tags and allow you to create new ones (`todo:add_to_my_new_japanese_deck` perhaps?). Marking probably takes fewer taps/scrolling depending on your number of tags.

In the card browser you can then `Filter marked` or `Filter by tag`.

**Comment by evilVR6** [comment]
I'll try this, thanks.

**Comment by evilVR6** [comment]
Unfortunately marking or tagging the cards only makes the card searchable a
different way and eventually I end up with the same 10 cards displayed in
my search box. But the accompanying cards (other side of the note which
hasn't been reviewed) is still buried somewhere and there's no way to get
Ankidroid to bring this other card to the new destination deck. Half the
note is in the old deck half is in the new, I should have 20 reviews in the
new deck but only have 10.

I feel like this is recent, I never used to have problems with this before

**Comment by sudomain** [comment]
That shouldn't be possible. A few questions:
1. You have a note type (e.g. `Basic`, `Cloze`, etc.) for your study of Japanese right? How many card types are shown the screen when you go do `Manage note types -> longpress your note type -> edit cards`
2. All of cards we're talking about are all in the same deck right (what you referred to as your old Japanese deck)?

**Comment by evilVR6** [comment]
Hi,

1. I have several note types, but all my Japanese are mainly in two.
2. Yes they are

**Comment by evilVR6** [comment]
In Anki desktop, once I have selected the card I just moved I can go into
Edit and hit the option 'select note', which then shows the card and it's
(Recognition or Production) partner by NID number.

I'd like to put in a feature request: that when you select a card the
"select note" option be added. Then it can switch the view and show the
selected card and it's opposite side, the pair, and also give you the NID
number.

Otherwise anytime you try to move things between decks you're only taking
half a note with you.

**Comment by sudomain** [comment]
An implementation note for the dev that picks this up: The `Card Browser -> Edit -> Select Notes` feature on desktop works when a single or multiple cards are selected and results in a browser search query of the form `nid:FIRSTID,SECONDID,THIRDID ...` and so on for every note of the selected cards.

I personally don't use this feature on desktop. I still believe that a suitable replacement workflow is:

    1. Marking/tagging a note
    2a. Filtering by marked or filtering by tag in the browser
    OR
    2b. Using a saved search term such as `tag:marked deck:*` to make sure AnkiDroid is searching in all decks
    3. Select all
    4. Change deck

I am biased though since that is my workflow when I need to change the deck for many cards and their sibling cards.
Something that might be worthy of further investigation: All of @evilVR6's marked/tagged notes should show up when filtering by marked/tagged, since [they confirmed that all of the problem cards are in the same deck](https://github.com/ankidroid/Anki-Android/issues/7376#issuecomment-719153685). It's a possible bug that I can't reproduce using the current stable, 2.13.5, and I use the filter by marked/tagged features quite regularly.

**Comment by evilVR6** [comment]
Hello,

I just tried the mark ("star") option while studying and it worked.  When
cards aren't marked or tagged in advance though it's still not possible to
get the whole note easily in the browser, but since most of my workflow
involves identifying these cards whilst studying I can live with
remembering to star the cards as i go. The tagging option wouldn't have
worked as stopping to open and edit notes and add tags is too laborious
mid-study.
I like that the starring is one-touch from the screen.

Thanks to all.

**Comment by sudomain** [comment]
Glad I could help you find the "least amount of taps" solution :) .
> When cards aren't marked or tagged in advance though it's still not possible to get the whole note easily in the browser, 

FWIW The `marked` tag can be added in the card browser when one or many cards are selected:
![Screenshot_2020-11-10-09-10-39](https://user-images.githubusercontent.com/30786326/98685449-61718300-2335-11eb-84b3-9001f5de4de3.png)

The feature of adding tags other than `marked` is being tracked in #4911
