### ISSUE TITLE
Consistently error appearing while syncing

### ISSUE THREAD

**Issue by berserkerezio** [ankidroid/Anki-Android#7380]
I updated a particularly large deck on my anki pc. I uploaded it to ankiweb and tried syncing between ankidroid and ankiweb. Ankidroid asked me if I wanted to upload or download,i selected download but the file is ~5 gb in size so I couldn't download it all in one go. So I terminated sync after the cards and few media files were downloaded. But no matter how many times I do this,every time an error message pops up that says the collection could not be opened.

![Screenshot_2020-10-13-12-22-39-365_com.ichi2.anki.jpg](https://user-images.githubusercontent.com/71184226/95825480-8979c080-0d4e-11eb-9666-73dba81ede56.jpg)

Prompts in popup are-
Close
Options

![Screenshot_2020-10-13-12-22-42-992_com.ichi2.anki.jpg](https://user-images.githubusercontent.com/71184226/95825526-9d252700-0d4e-11eb-8c64-2d1f1122bc12.jpg)
Upon opening options,I have-
Check database
Restore from backup
Full sync from server
Delete current collection and create a new one

Checking database solves the prblem temporarily,as I can again access the cards that I just downloaded from ankiweb with intact scheduling(no media though except the little I downoaded. Next time I hit sync,same thing happens,asking to download or upload and same error popup.

Everything works fine on anki pc. Please help!

**Comment by david-allison-1** [comment]
@berserkerezio Could you provide your ACRA ID: 

`Settings - Advanced - About AnkiDroid - Copy Debug Information` 

If your collection doesn't contain anything sensitive, could you zip and upload the file located at: `AnkiDroid/collection.anki2` to a comment.

Thanks

**Comment by berserkerezio** [comment]
Here's the debug info-

AnkiDroid Version = 2.13.5

Android Version = 9

ACRA UUID = 47aab9e5-5473-47c3-9c1e-7ce5d70e3b62

Scheduler = std


Collection file-
https://drive.google.com/file/d/16qNdf3TGAvx_ImJT6LjPu9Bv1dgMfgrv/view?usp=drivesdk

**Comment by berserkerezio** [comment]
It is set to ask me.

In case the last link doesn't work, here's another-

https://drive.google.com/file/d/16qNdf3TGAvx_ImJT6LjPu9Bv1dgMfgrv/view?usp=drivesdk

**Comment by berserkerezio** [comment]
Maybe its because the collection package you have is from before being synced,because the sync is not succeeding. After every sync,I get these pop ups and have to check database,which smooths out the errors I guess(hence why you have no trouble wih it),but its not allowing me to sync without forcing full sync in one direction.

Here's the collection package of my deck from anki pc-

https://drive.google.com/file/d/177beanxBqpi-O0ecshtp6TbH-KaO9uyy/view?usp=drivesdk

Maybe this one is somehow not compatible with ankidroid? I did run check database on anki pc too,so it should not be corrupted.

**Comment by david-allison-1** [comment]
Once you Check Database, it forces a sync in one direction. If you download, then you'll get the corrupted file again.

If checking the database fixes the problem, then upload.

**Comment by berserkerezio** [comment]
Ok,will try that.

**Comment by david-allison-1** [comment]
Hi @berserkerezio, did you reopen this issue accidentally, or is there more to resolve?

**Comment by berserkerezio** [comment]
Nothing to resolve,sorry.
