### ISSUE TITLE
Ankidroid doesn't remember the last deck and card type

### ISSUE THREAD

**Issue by dumbdreamed** [ankidroid/Anki-Android#7395]
###### Reproduction Steps

1. Hi my friend. Really appropriate your work on this.
I have a problem when selecting a word from another app and hit anki card option, in the previous builds it remembered my last choice for deck and card type but now it doesn't. Any idea how to solve this?
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Sorry for the trouble, but thanks for taking the time to report it. May I ask for some more information?

"in previous builds" -> which version?
what version are you on currently?

There instructions on getting version info here: https://docs.ankidroid.org/help.html (specifically hunt for "copy debug info")

Once you know the previous version that worked and the version you are on, you can try a version halfway between them to see when if the bug appears already or not, then for each range where the bug shows up, you can try a version halfway between the last version that worked and the one you tested, and usually within just 2-3 tests - maybe 10-15 minutes of effort? - you find where it started. From that we can usually make a fix immediately :-) - all the builds are here: https://github.com/ankidroid/Anki-Android/releases
