### ISSUE TITLE
內容出現亂碼

### ISSUE THREAD

**Issue by yule0619** [ankidroid/Anki-Android#7408]
###### Reproduction Steps

1. 
![Screenshot_20201019-001750406](https://user-images.githubusercontent.com/72739592/96373687-b855c380-11a0-11eb-89c3-b89f051ed204.jpg)

2. 
![Screenshot_20201019-001803406](https://user-images.githubusercontent.com/72739592/96373692-be4ba480-11a0-11eb-834a-b700c2467cac.jpg)

3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, click `卡片 2` and you'll open a template editor - there's likely something wrong with the template. 

If you can't determine the problem, you could ask on our mailing list:

https://groups.google.com/forum/#!forum/anki-android

**Comment by yule0619** [comment]
![Screenshot_20201019-113256600](https://user-images.githubusercontent.com/72739592/96398725-1dd89d00-11ff-11eb-9956-ce8274e7ec20.jpg)
請問有人知道怎麼修改嗎？
上一個版本沒這個問題
PC版也都正常

**Comment by david-allison-1** [comment]
> 請問有人知道怎麼修改嗎？
> 上一個版本沒這個問題
> PC版也都正常

Could you export the deck on your PC, rename it to `.zip` and upload it here.
