### ISSUE TITLE
Bug in Card Browser section / Add new note window / Deck

### ISSUE THREAD

**Issue by leotheforth** [ankidroid/Anki-Android#7420]
###### Reproduction Steps

Please watch the video

https://youtu.be/mKHVGFPvZG0

###### Expected Result

Once in the Card Browser  -> "particular Deck" section the default Deck in the "Add new note" window has to be "the particular Deck"

Should I want to manually change it to another Deck it should be possible for the duration of this particual window (entry mask) opened e.g. if in Card browser I chose Greek then per default when I want to add a new note to the deck the default deck should be Greek;

###### Actual Result

If in the Add new note window I previously had let's say Japanese as Deck it will stay there even if in the Card Browser I currently have another Deck.

**Comment by david-allison-1** [comment]
Hi @leotheforth, thanks for the report! 

Would you be interested in submitting a pull request to fix this, or should we add this issue to the backlog?

**Comment by leotheforth** [comment]
Add it to the backlog

**Comment by david-allison-1** [comment]
@leotheforth Should be in the next alpha or two: https://docs.ankidroid.org/manual.html#betaTesting

**Comment by leotheforth** [comment]
@david-allison-1 

Alright.
