### ISSUE TITLE
Feature request: Unique settings in "Options" for each deck

### ISSUE THREAD

**Issue by leotheforth** [ankidroid/Anki-Android#7424]
As the result each deck will have unique settings in the "Options" for each deck: 

Different reviewing time 
Different amount of cards 
+ to be learned 
+ to be reviewed
etc

Spanish is easier to learn for English-speakers than Chinese, Japanese, Thai or Korean and Turkish is easier than Arabic or Farsi, hence one can memorize (learn and review) various amount of cards in each language 
e.g. 100 new cards to learn and 150 new cards to review for Spanish deck
and
only 20 new cards to learn and 50 new cards to review for Japanese deck

**Comment by mikehardy** [comment]
deck options groups exist and are more flexible. Can do 1 to 1 with decks if you want, meeting your request, or 1 to many which is even more flexible

**Comment by leotheforth** [comment]
Thanks @mikehardy 

I close the ticket

**Comment by leotheforth** [comment]
Hi @mikehardy, @david-allison-1 and all other creators of amazing Anki platform, 

Having taken some time to think about it, I'd like to re-open this request. 
Having unique set of options for each deck (additionally to having option group settings) would make it more user friendly as it would allow to change options for different decks "on the fly" i.e. without a need of creating another group, if a user wants to change something for just one deck and in the default group are also several decks assigned already. 

Leo

P.S. I understand that it is not a bug, however what Anki lacks somewhat (from my point of view) is, the easy-ness of use and a better usability and having the feature implemented would contribute towards better usability of Anki (again from my personal point of view).

**Comment by mikehardy** [comment]
This will only happen if it happens upstream - I think you'll want to lobby for the change upstream then we'll follow here for ecosystem compatibility. We can't have a config system different than the general Anki ecosystem though https://forums.ankiweb.net/

**Comment by leotheforth** [comment]
> This will only happen if it happens upstream - I think you'll want to lobby for the change upstream then we'll follow here for ecosystem compatibility. We can't have a config system different than the general Anki ecosystem though https://forums.ankiweb.net/

Mike, who I can pitch the open feature requests there to?

**Comment by mikehardy** [comment]
If you just open as a feature request Damien Elmes should see it, he *is* Anki (AnkiDesktop, AnkiWeb, AnkiMobile) - AnkiDroid (here) is a port from the original GPL-licensed / open source Python version of AnkiDesktop more than a decade ago, and since then we collaborate to maintain compatibility and feature parity etc. But he still runs all the rest

**Comment by leotheforth** [comment]
Thank you very much @mikehardy
