### ISSUE TITLE
After install, hitting back from change log goes back to Play Store instead of home

### ISSUE THREAD

**Issue by jgscherber** [ankidroid/Anki-Android#7438]
After installation, hitting the back button from the Changelog page returns the user to the Google Play store page, instead of going to the AnkiDroid home page (see video)

https://gfycat.com/acceptablereadyarcticduck

AnkiDroid Version = 2.13.5

Android Version = 10

ACRA UUID = 03434583-cd6c-4869-8ed2-d8e7712382df

Scheduler = std

**Comment by david-allison-1** [comment]
@jgscherber Thanks for the report! Is the app usable when opening again?

**Comment by jgscherber** [comment]
Yeah, relaunching the app brings me to the AnkiDroid home page. Just reporting it as a weird behavior

**Comment by david-allison-1** [comment]
> Yeah, relaunching the app brings me to the AnkiDroid home page. Just reporting it as a weird behavior

Cheers - already got a fix in, will be sorted for the next release
