### ISSUE TITLE
Syncing problems "Collection not opened" no matter what

### ISSUE THREAD

**Issue by SergyOrloff** [ankidroid/Anki-Android#7459]
###### Reproduction Steps

1.Running check database 
It results in "Database checked", and after clicking "ok" I have red stress mark at the upper right button for syncing and "Syncing conflict" when I am trying to sync. 
It offers to upload or download from Ankiweb. I am choosing 
2."Download" and "Overwrite"
It results in "Collection not opened" message. I go to "Options" and try 
3."Restore from backup"
It does it, then I am trying to sync and I get "Syncing conflict" again. Trying to download from Ankiweb, failing, getting "Error handling" message. Pressing 
4."Full sync from server"
Agreeing to "Overwrite". Getting message "Collection not opened" again. Trying "Delete collection and create new one" from "Options".
5."Delete collection and create new one"
Clicking "Create", seeing "Collection is empty" on the screen. Red stress mark on the syncing button at the upper right. Trying to sync and "Downloading", "Synchronization" and back to "Collection not opened". 
6.Tried to delete and install AnkiDroid couple times
No difference.
7.Delete the card I was creating on Anki Version 2.1.35 (on Windows).
No difference, was just a wild guess that it could help. It didn't.
https://groups.google.com/g/anki-android/c/L70NpmkhxMA/m/qqVvc2ENCQAJ

###### Expected Result

Syncing is expected

###### Actual Result

Syncing not happening

###### Debug info
AnkiDroid Version = 2.13.5

Android Version = 7.0

ACRA UUID = 58b7af15-37ae-4f32-9324-e49ef9b509e6

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

I am not sure if all my [x] are honest but I am just to tired to deal with this issue more. Even adding this thing (what am I adding? issue?) is hard. No idea if I am doing it right.

[collection.zip](https://github.com/ankidroid/Anki-Android/files/5430692/collection.zip)

**Comment by mikehardy** [comment]
Hi there! So, you are running database check to fix the database, then immediately overwriting it with a full download (of a maybe corrupt database from the server?) each time? That will result in the things you see.

Once you have run database check and it's working, push the changes up to the server. If you download again, you've wiped out the results of the database check

**Comment by SergyOrloff** [comment]
> Once you have run database check and it's working, push the changes up to the server. If you download again, you've wiped out the results of the database check

Hi, thank you for answering! Not sure I understand... Should I chose "UPLOAD" in the attached screenshot? I am afraid that it would upload what I have in AnkiDroid and destroy all that I did on my laptop for a month already... No?
![Capture+_2020-10-23-20-26-09](https://user-images.githubusercontent.com/20322335/97034888-3f72b500-156e-11eb-92b5-03e4433314e5.png)

**Comment by mikehardy** [comment]
It might destroy state. Upload will overwrite the collection on AnkiWeb.

This is a multi-device syncing infrastructure. If you have allowed your state to skew amongst your devices (with some reviews done on desktop and some on mobile device, and not syncing regularly in between them so they are up to date), there is no technical way to handle that, no syncing service can untangle that.

Prior to uploading changes as an overwrite to AnkiWeb you will want to choose carefully what your "source of truth" is (desktop? mobile?) then do a database check on that source of truth, and upload to AnkiWeb, then download to the other clients.

**Comment by SergyOrloff** [comment]
Ok, but what if my "source of truth" is the desktop? I am ok with overwriting the collection on AnkiWeb entirely. Actually, that's exactly what I am trying to do. I chose carefully, and my choice is the desktop. Still, when I am trying to overwrite, I can't. "Collection not opened". 

I just checked the database on the desktop, synced. Opened mobile, got error message "Collection not opened", went to "Error handling", chose "Full sync from server", ... "Synchronization", downloading... and again "Collection not opened". 

I was syncing regularly until this issue appeared. I am ok with overwriting anything on the mobile with what I have on the desktop. I am checking the database on the desktop, and I still can't download it to AnkiDroid. 

That is the problem - that I can't download from the desktop. I am totally fine with burning everything on the mobile to the ground.

**Comment by SergyOrloff** [comment]
> then immediately overwriting it with a full download (of a maybe corrupt database from the server?) 

I don't think that the database is corrupt on the server, because it works just fine on the desktop. I just want to download everything from the desktop to the mobile and I can't do that.

**Comment by mikehardy** [comment]
I'm not sure what exactly is going on with desktop vs mobile, but we have had several problems recently where desktop was corrupting the collection and we had to work around it.

Have you tried running check database on AnkiDroid *after* forcing a full sync down from AnkiWeb (which should be in sync with Anki Desktop, your source of truth)? Then is it able to work? If so, then if you upload back to AnkiWeb and then download on to AnkiDesktop you may have a consistent system again, based on the Anki Desktop collection

**Comment by SergyOrloff** [comment]
> Have you tried running check database on AnkiDroid after forcing a full sync down from AnkiWeb (which should be in sync with Anki Desktop, your source of truth)? Then is it able to work? If so, then if you upload back to AnkiWeb and then download on to AnkiDesktop you may have a consistent system again, based on the Anki Desktop collection

Thank you, Mike, that worked! Uff, I spend so much time just mindlessly trying to make it work somehow just doing more or less the same, instead of trying some logic. 

Still weird why it wasn't able to just overwrite the collection on AnkiDroid, but currently I am ok with it just working. Thank you very much, again!

**Comment by mikehardy** [comment]
Most of the time syncing is a very small differential merge so that it's fast even if you have (like some of our users) collections that run into the gigabytes (!!) with a database that's multiple megabytes even. Better to just transfer a few kilobytes. You have to be pretty specific (or do a few specific actions) with the Anki syncer to tell it you really really do want a full synchronization, and then it's somewhat dangerous because it can overwrite changes. Anyway, very glad it worked! Happy reviewing
