### ISSUE TITLE
Deck Options NumberRangePreference displays wrong value due to rounding issue

### ISSUE THREAD

**Issue by Volfee** [ankidroid/Anki-Android#7466]
When you modify some of the deck options like Reviews/Easy Bonus or Reviews/Interval wrong value is displayed. 

For example if you modify Easy Bonus to 130 the actual value that is shown in the UI is 129%. This only happens for some values and must be related to some rounding issue (nothing major). 

I can write a PR that will fix it.

**Comment by mikehardy** [comment]
That would be great @Volfee !

**Comment by david-allison-1** [comment]
I had a search when this was posted - I'm certain it's been mentioned before, but I can't find a reference, getting it fixed would be grea.t
