### ISSUE TITLE
Feature request: keyboard shortcut 'Y' to sync

### ISSUE THREAD

**Issue by senorsmile** [ankidroid/Anki-Android#7471]
###### Reproduction Steps

1. open anki
2. hit 'y' on the keyboard

###### Expected Result
Sync with ankiweb happens

###### Actual Result
Nothing

###### Debug info
AnkiDroid Version = 2.13.5

Android Version = 9

ACRA UUID = 57588002-3428-4942-9b5d-5c640b68c06d

Scheduler = std2

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Additional Details
In the desktop version of Anki, there's a keyboard shortcut 'Y' to start a sync.  On both my chromebook and android device with a keyboard, this keyboard shortcut is not present.

**Comment by david-allison-1** [comment]
Fixed in 1d77f57ddbf74fc418efa4bcb3c7f11b49aec4af (#7106 and #5233).

Available in AnkiDroid 2.14: https://github.com/ankidroid/Anki-Android/releases 

https://docs.ankidroid.org/manual.html#betaTesting

Thanks!

**Comment by david-allison-1** [comment]
@senorsmile Also note that we have a sync intent if you use Tasker, or similar software: https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-API#sync-intent
