### ISSUE TITLE
[Feature Request] An option to hide the new font errors

### ISSUE THREAD

**Issue by leopard20** [ankidroid/Anki-Android#7483]
Is it possible to make the new font errors optional? Because despite the errors, I see the text just fine as it is. In fact, I tried installing the fonts it was missing and not only did it slow down loading notes but also it looked worse than the default font my system uses.
So I simply don't want AnkiDroid to show me any errors, just like the previous versions. (with an option to ignore missing fonts)

**Alternatively, when the option "default font applicability" is set on "always", you can hide the errors even if the default font is "system default". (which currently still shows the error btw)**

Edit: I don't make these cards so I can't fix it myself. They are imported from a dictionary app.

**Comment by david-allison-1** [comment]
> I don't make these cards so I can't fix it myself. 

It's on the card template, you can edit the card template (tap "Cards" when editing a note) and remove the reference to the invalid font.

**Comment by mikehardy** [comment]
You need to contact the author of the template then, if they are producing a broken template they should know
I believe we already tuned it so it only shows a couple times then stops

Bottom line: you have a broken personal collection, install the font, or delete it from the template
