### ISSUE TITLE
[FEATURE REQUEST] Add new card button while studying

### ISSUE THREAD

**Issue by tpondant** [ankidroid/Anki-Android#7509]
###### Reproduction Steps

1. Click on deck to start studying it
2. Searching for a + button to add new card while studying/reviewing a deck

###### Expected Result
Expected a + button like on the home screen of the app to quickly add a new card while studying. 

###### Actual Result
No button to add a new card. Have to leave study session to find the add button again.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, thanks for the feature request!

This should already be available at: `Settings - Reviewing - App Bar Buttons - Add Card`

Please let me know if this doesn't resolve your issue

Thanks,

David
