### ISSUE TITLE
Restoring default deck override setting results in corrupted collection

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#7512]
###### Reproduction Steps

1. manage note types, edit cards, deck override for any card type
2. "restore default"
3. Sync changes and pull to desktop*

*irl after this step: spend way too much time read JSON in a SQL browser :)
###### Expected Result
the restore default button should go into the `tmpls`JSON of `col.models` and for the modified template and change `"did":SOMEID` to `"did": null`

###### Actual Result
instead, it removes `"did":SOMEID` entirely. AnkiDroid is entirely fine opening a collection in this state (which is a separate issue), but it causes desktop v2.1.35 to panic with an error such as `missing field 'did' line 1`.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.13.5

Android Version = 7.0

ACRA UUID = 0417c1bf-8871-4e84-9233-cfea8e42b734

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
`.put("", null)` doesn't set the key to null, it removes it.

We'll need a lint check in future for this. 

https://github.com/ankidroid/Anki-Android/blob/ada67bc3d304193eab15d42badaafe9863d340cf/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java#L239-L244
