### ISSUE TITLE
LINT: Don't use `getString()` in Material Dialogs

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7518]
We should add a lint check here - maybe even to the original repository?

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/7489#issuecomment-716222133_

**Comment by Arthur-Milchior** [comment]
What is the "original" repository ?

**Comment by david-allison-1** [comment]
https://github.com/afollestad/material-dialogs

**Comment by mikehardy** [comment]
I will do no work for material dialogs, they appear to be developer-belligerent. I intend to replace that library.
