### ISSUE TITLE
I ask you, add the ability to add tags to several cards at the same time - I'm tired of changing one card at a time

### ISSUE THREAD

**Issue by vosirandr** [ankidroid/Anki-Android#7520]

**Comment by david-allison-1** [comment]
hi @vosirandr, thanks for the feature request!

Definitely! Would you like to contribute a Pull Request for this?

This is a duplicate of #4911, so I'll close it (feel free to +1 the lined issue).

Contributions are more than welcome, 

Thanks for taking the time to ask,

David
