### ISSUE TITLE
Add a cross so that you can delete the entire field at once

### ISSUE THREAD

**Issue by vosirandr** [ankidroid/Anki-Android#7522]

**Comment by david-allison-1** [comment]
Thanks for the request!

What's your use-case where you have to do this often? 

Are you using `Long Press Field Text - Select All - Delete`, which should speed this up?

**Comment by vosirandr** [comment]
![Polish_20201027_082717031.png](https://user-images.githubusercontent.com/61714173/97260819-9e665180-182e-11eb-8877-fdfd4f70f5e2.png)

**Comment by david-allison-1** [comment]
When you type into the Google Search bar, sometimes the results aren't what you expected and you'll want to try something different. There's no "search" functionality in the Note Editor

For now, I'm of the opinion of this StackOverflow answer:

> It depends from the context. If the user knows the value to enter and it’s less likely that he will change it later Than the ‘clear’ button is not needed.

https://ux.stackexchange.com/a/115015

But, if there's a use case, let's implement it.

**Comment by vosirandr** [comment]
when I wrote degrees, that is, 3³, it was easier for me to delete the
entire field than to erase this 3 <sup> 3 </sup>

вт, 27 окт. 2020 г., 16:22 David Allison <notifications@github.com>:

**Comment by david-allison-1** [comment]
Okay, will add it to the "attach media" button for now, will make it more prominent if there's user demand.
