### ISSUE TITLE
Note Editor: Add Icons to Multimedia Menu

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7526]
Good first issue - need to replace icons with XML drawables (Via Add - Vector Icon), then set a style/tint on the XML icons.

https://github.com/ankidroid/Anki-Android/blob/71fdd0445f020ec7f798e29bc08dc13d658d9234/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1405-L1406

Menu currently looks like:

![image](https://user-images.githubusercontent.com/62114487/97322794-0d13d100-1868-11eb-9c45-7ffce158a750.png)

**Comment by mrudultora** [comment]
@david-allison-1 Please reopen this issue.

**Comment by arpitnema07** [comment]
hey, I would like to work on this issue, can someone help me on how to get started.

**Comment by mrudultora** [comment]
Hi, @arpitnema07 sorry but I have started working on it. Would you mind to take another issue?

**Comment by arpitnema07** [comment]
Ok, @mrudultora but if you're not done than I have resolved the issue, btw Thanks.

**Comment by mrudultora** [comment]
@david-allison-1 Android Studio does not have all the required icons. Could you suggest me a preferred website for searching? ( I have already looked on icons8, freepik, etc.)

**Comment by david-allison-1** [comment]
Right now, I don't know, sorry.

From memory, there should be appropriate icons in the pack provided by Android Studio

**Comment by infinyte7** [comment]
@mrudultora 
View 
https://romannurik.github.io/AndroidAssetStudio/icons-launcher.html
https://material.io/resources/icons/
And use vector icon instead of png

**Comment by mrudultora** [comment]
@infinyte7 Thanks for the info. I had found vectors for all except last one. For, **clear field** can I use the png icon of erase already present in app ( or this vector [icon ](https://material.io/resources/icons/?icon=clear&style=baseline))

**Comment by infinyte7** [comment]
[clear](https://material.io/resources/icons/?icon=clear&style=baseline) icon look good to me.
