### ISSUE TITLE
Review Gestures: Consider 9-touch model

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7537]
AnkiMobile has 9 touch points for gestures (each corner & centre).

This has been requested as a feature for tablets

> On a personal note, I prefer AnkiDroid to iOS Anki on every single aspect (you have honestly done such a phenomenal job with this app) but one - the 9 touch areas iOS offers for gesture support during reviews (top/mid/bottom each for left/mid/right of interface) is superior and much more comfortable on a tablet to the 4-sided touches (top/bottom/left/right) AnkiDroid offers. For me this is the difference-maker causing me to review on my iPad rather than my Android devices, but should also be relatively easy to implement to vastly improve the gesture experience. I could be in the minority on this, but it's something worth looking into in my opinion.

**Comment by mikehardy** [comment]
🤔  would be a bit of a breaking change for gesture people but they can set it up compatibly

One thing to keep in mind is that Android system itself has a gesture mask now I think? I have no personal experience it's just flagged in my mind as something to research if I ever touch gesture things

**Comment by david-allison-1** [comment]
Added it as an option, it can't be perfectly compatible with 4-sided gestures, and users might want either.
