### ISSUE TITLE
[2.14alpha] Note Editor: Fix Tab Ordering

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7539]
Tab ordering was broken by Restore/Collapse field: 5205c62a4266a2c90a266d4a76301d36e77490b7

I have a fix on my machine for API 26.

\< API 25 will take some time, as it requires fixing modifying IDs, which appear to mess with the ConstraintLayout

**Comment by mikehardy** [comment]
constraintlayout itself just bumped a patch release but with no release notes, FYI, it's in my dependabot integration tree, unpulled as of yet but I'll PR it just in case that affects you

**Comment by mikehardy** [comment]
there's the PR on the off-chance it affects you please feel free to merge if I haven't circled back to it yet after awaiting CI
