### ISSUE TITLE
Functionality request

### ISSUE THREAD

**Issue by leotheforth** [ankidroid/Anki-Android#7556]
Ability to:

- duplicate decks and subdecks [create a copy of a / (some) deck(s) with all it's content]
- merge decks and subdecks
- copy notes to other deck(s) and subdeck(s)

in Ankidroid

**Comment by Arthur-Milchior** [comment]
Hi,

Can you please state what would be a duplicated deck ? Do you want to also duplicate the content ? I can't imagine the point

We usually follow upstream feature, so it won't occur unless you convice Anki to do it. There exists an add-on for merging deck if it helps.

You can already copy individual note, open it in the editor and there is a copy option. You can also move this note in any deck

**Comment by leotheforth** [comment]
Hi Arthur, 

>> Can you please state what would be a duplicated deck ? Do you want to also duplicate the content ? I can't imagine the point

Yes, a copy of the to be duplicated (sub)deck with all it's content.

Let me tell what I did before I submitted the request:

Let's say I have a deck named Greek
I exported the deck with all it's content into a file
Renamed the deck into Greek2 
Imported the export file 
A new Greek deck was not created.  

>> We usually follow upstream feature, so it won't occur unless you convice Anki to do it. There exists an add-on for merging deck if it helps.

I understand that. I really would love to speak with the creators and outline my thoughts to them. I really love Ankidroid and I think that it is a great tool, however in terms of usability it is not the most user friendly one and to major parts of it it is also not drag and drop capable.  

>> You can already copy individual note, open it in the editor and there is a copy option. You can also move this note in any deck

I know that, Arthur. Just imagine one has to duplicate a couple of thousands of entries... one by one... do you get the picture?

I outline what I think would be beneficial for Ankidroid, whether it will be acted upon or not and whether it will be implemented is up to the Ankidroid developers. 

Best wishes and kind regards
Leo 

P.S. I really would love to meet the Ankidroid core developers team in body and flesh i.e. face to face, whenever soon it would be possible. I even eventually would fly in on my own costs, when this whole madness with the highly political virus would end. Alternatively we can have a Zoom meet-up with a whiteboard functionality so I could share my ideas with you guys and gals in a prejudice free environment.

**Comment by leotheforth** [comment]
P.P.S. I'm talking about Android version of Ankidroid

**Comment by Arthur-Milchior** [comment]
> Hi Arthur,
> 
> > > Can you please state what would be a duplicated deck ? Do you want to also duplicate the content ? I can't imagine the point
> 
> Yes, a copy of the to be duplicated (sub)deck with all it's content.
> 
> Let me tell what I did before I submitted the request:
> 
> Let's say I have a deck named Greek
> I exported the deck with all it's content into a file
> Renamed the deck into Greek2
> Imported the export file
> A new Greek deck was not created.

Indeed, each card has a unique id, and it detects that those cards are duplicate. There are add-ons in computer version to copy card. It may help you more.

> 
> > > We usually follow upstream feature, so it won't occur unless you convice Anki to do it. There exists an add-on for merging deck if it helps.
> 
> I understand that. I really would love to speak with the creators and outline my thoughts to them. I really love Ankidroid and I think that it is a great tool, however in terms of usability it is not the most user friendly one and to major parts of it it is also not drag and drop capable.

You can contact anki's author on https://forums.ankiweb.net/ 
We are all volunteers, so even a good suggestion is not guaranteed to be implemented, but all contributions to the code are considered.

> 
> > > You can already copy individual note, open it in the editor and there is a copy option. You can also move this note in any deck
> 
> I know that, Arthur. Just imagine one has to duplicate a couple of thousands of entries... one by one... do you get the picture?

I understand. And in this case I'd use the computer and just use the copy add-on


> P.P.S. I'm talking about Android version of Ankidroid

The versions for computer, ios, web are not called ankidroid. That's why there is "droid" in the name

**Comment by leotheforth** [comment]
@dae

**Comment by mikehardy** [comment]
@leotheforth I think what you want is to go here directly: https://forums.ankiweb.net/

**Comment by leotheforth** [comment]
@mikehardy Added another feature request there as well. 

Thanks Mike.
