### ISSUE TITLE
Backside scroll poition-quality of life

### ISSUE THREAD

**Issue by TowelSniffer** [ankidroid/Anki-Android#7581]
When flipping a card Ankidroid resets the scroll position to the top. this is different from Anki desktop behaviour which maintains the same position. As in if you have rolled down on the front side, Anki desktop remains scrolled on the backside as well.

**Comment by mikehardy** [comment]
I am not saying this is not an issue, I just think it is actually a duplicate: #5182

**Comment by TowelSniffer** [comment]
Thank you, and you are correct. The linked issue seems to describe my problem. Sorry I missed it.
