### ISSUE TITLE
Cards I relearned yesterday which should have appeared 15 days later appeared today.

### ISSUE THREAD

**Issue by TwistedChimera** [ankidroid/Anki-Android#7593]
###### Reproduction Steps

**Platform:**

AnkiDroid 2.13.3

**Settings:**

New cards:
- Steps: 25 1440 4320 8640
- Order: New cards in order added
- New cards/day: 40
- Graduating interval: 15 day(s)
- Easy interval: 20 day(s)
- Starting ease: 250%
- Bury related new cards: unchecked

Reviews:
- Maximum reviews/day: 9999
- Easy bonus: 130%
- Interval modifier: 100%
- Maximum interval: 180 day(s)
- Bury related reviews: unchecked
- Use general settings: checked

Lapses:
- Steps (in minutes): 30 1440 4320 8640
- New interval: 15%
- Minimum interval: 15 days (I changed this to 20 a few days ago) 
- Leech threshold: 99 lapse(s)
- Leech action: Tag only

Advanced:
- Experimental V2 scheduler: off

Reviews:
- I review cards and change settings exclusively on AnkiDroid  2.13.3
- I rarely use laptop for reviewing. Mainly for editing html. I don't make my own cards.
- Snapshots were done on laptop because it's easier (anki 2.1.34 (8af8f565) windows 10)

Changes made recently (within 7 days):
- Changed minimum interval from 15 days to 20 days (I didn't like that my relearned cards showed "Good (15 days) Easy (15 days)")

Changes made 30+ days ago:
-  Changed minimum interval from 1 day to 15 days (I noticed lapsed cards after last step (8640) goes to 1 day after so I changed it to 15 days)
- Some cards that were showing (good 1day) were manually rescheduled to 15 days using the "reschedule for review in x days" button in ankidroid during review.

When did problem begin:
- Most likely after the time minimum interval was changed. I didn't notice until 10/31/2020. But I did suspect some cards having unusually high good intervals (good 1.1mo) on some cards the day before even though I reviewed them 1 day prior.

Cards affected:
- Exclusively lapsed cards
- Possibly lapsed cards with previous setting (minimum interval: 15 days) being affected by new setting (minimum interval: 20 days)
- The lapsed cards affected are on the last step, 8640, (30 1440 4320 8640) meaning pressing good would be (good 15days)
- I do not know if lapsed cards on previous steps are also affected because I haven't noticed it while reviewing.

###### Expected Result

Cards I pressed Good(15 days) on October 30, 2020 appear 15 days later.

###### Actual Result

Some cards I pressed Good(15 days) on October 30, 2020 appeared October 31, 2020 with good(1.1mo)

Same thing is happening to some of the cards I need to review today November 1, 2020 (reviews made on ankidroid 10/31/2020, snapshots done on anki 2.1.34 (8af8f565) windows 10): https://imgur.com/a/6gAFGEk

[backup-2020-10-31-09.07.19.zip](https://github.com/ankidroid/Anki-Android/files/5470156/backup-2020-10-31-09.07.19.zip)

Snapshots I made from a backup on October 31, 2020 (on anki 2.1.34 (8af8f565) windows 10): https://imgur.com/a/7IAU5Yp

Extensions used:
https://ankiweb.net/shared/info/1008566916 (checking info during review)
https://ankiweb.net/shared/info/1052724801 (finding date reviewed and date due)
###### Debug info
AnkiDroid Version = 2.13.3

Android Version = 5.1.1

ACRA UUID = 869c575a-3a0b-4b7b-809d-e917856f7d04

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
Hi,

Link to reddit post https://www.reddit.com/r/Anki/comments/jl9w17/cards_i_relearned_yesterday_which_should_have/
There are also plenty of image. I didn't thought about asking for card info before, and that's a shame. The log of review is quite useful !

Thanks a lot again for such a detailled description of the bug. That's really appreciated.
Can you please export a card where the problem occurs (select it on desktop, in the card browser, then select export in a menu.), put it in a zip file and post it here. I'd like to see your card in details to try to reproduce.

Did you do anything on the computer before syncing your collection on the computer ? 
I'd be interesting in knowing whether the problem still exists if you don't sync your collection on your computer (I would not ask you to stop syncing online, that would be too dangerous if the phone get lost.)

The most interesting information would be to know whether the card had the correct due date and then it was changed to an error, or whether as soon as it left the scheduler, the date was erroneous.



Note for @mikehardy and @david-allison-1 : I've not touched the scheduling part of the code. Only the fetching part. So I highly doubt I can help more than anybody else. https://github.com/Arthur-Milchior/anki/blob/commented/documentation/computing_intervals.md tried to explain how the next date is computed, but it does not seems to be relevant.

**Comment by david-allison-1** [comment]
@TwistedChimera Which version of Anki Desktop are you using?

**Comment by TwistedChimera** [comment]
Version 2.1.34 (8af8f565)
Python 3.8.0 Qt 5.15.1 PyQt 5.15.1

**Comment by TwistedChimera** [comment]
@Arthur-Milchior I haven't touched anki today so I was easily able to get a version of the cards before I reviewed them and after.

[5 notes.zip](https://github.com/ankidroid/Anki-Android/files/5470307/5.notes.zip)

Cards are based on this album https://imgur.com/a/6gAFGEk

**Comment by david-allison-1** [comment]
Can't say I'm familiar with this part of the sched (I normally keep the "New Interval" at the default of 0%, but this seems intentional:

https://github.com/ankitects/anki/blob/6b0b3fcd6a9f9fe467e9caa90c0d0f8d1bbabbdb/pylib/anki/sched.py#L284-L292

**Comment by Arthur-Milchior** [comment]
It seems you're entirely right @david-allison-1. That's really what the code does. And that does seems not consistent with https://docs.ankiweb.net/#/deck-options?id=lapses and anyway, we should not display "15 days" if we reschedule one day after

@dae could we get your advice here. TL/DR, it seems that when you press good on the last step of a lapse card, it's always rescheduled the next day in sched V1, and actually ignore the minimum interval setting. (it sets the minimum interval setting of the card, but it won't be taken into account before next review). Is it expected ? Can this be disambiguated in the manual, because that seems confusing. Or did both David and myself miss something here ?

**Comment by dae** [comment]
The V1 scheduler updates the new review interval when the card is first failed, not on the last step.
