### ISSUE TITLE
Travis CI: Pricing changes - Migrated to limited "Free" plan - Seek Alternatives

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7604]
As per: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing . Will need to consider alternatives.

> ### Building on a public repositories only
> We love our OSS teams who choose to build using TravisCI and we fully want to support that community. However, recently we have encountered significant abuse of the intention of this offering. Abusers have been tying up our build queues and causing performance reductions for everyone. In order to bring the rules back to fair playing grounds, we are implementing some changes for our public build repositories.
> 
> For those of you who have been building on public repositories (on travis-ci.com, with no paid subscription), we will upgrade you to our trial (free) plan with a 10K credit allotment (which allows around 1000 minutes in a Linux environment).
You will not need to change your build definitions when you are pointed to the new plan
When your credit allotment runs out - we’d love for you to consider which of our plans will meet your needs.
We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
Your account name and VCS provider (like travis-ci.com/github/[your account name] )
How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more)
Usage will be tracked under your account information so that you can better understand how many credits/minutes are being used

...

> ### Building on the macOS environment
>  macOS builds need special care and attention. We want to make sure that builders on Mac have the highest quality experience at the fastest possible speeds. Therefore, we are separating out macOS usage from other build usage and offering a distinct add-on plan that will correlate directly to your macOS usage. Purchase only the credits you need and use them until you run out.

> $15 will buy you 25 000 credits (1 minute of mac build time costs 50 credits)
Use your credits for macOS builds only when you need to run these
Replenish your credits as you need them
More special build environments that fall into this category will be available soon

...

> ### How will the new pricing changes be released?
> Beginning on Monday the 2nd of November 2020, customers impacted by pricing changes listed above will be gradually upgraded to the new pricing scheme upon their plan expiration date.
>
> To check the specific date for transferring your subscription to a new plan, please go to the subscription page in your account settings and review your renewal date.

**Comment by mikehardy** [comment]
As chatted about on discord, seems asking for an allotment of minutes should work if they really were doing this to prevent miner abuse and we are a legit project. Otherwise it's a migration to github actions really, on macOS runners they have android emulators with acceleration

**Comment by david-allison-1** [comment]
Got a reply. Response inline below

<details><summary>Reply</summary>

----

Hi,

We've been using Travis as an Open Source project since 2012. 

This is in relation to the changes mentioned in https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing and ensuring that we can continue to use Travis given the changes regarding open source projects.

> Thanks for contacting Travis-CI Support! We would love to help.
> 
> We offer an Open Source Subscription for free to non-commercial open-source projects. To qualify for an Open Source subscription, the project must meet the following requirements:
> 
> * You are a project lead or regular committer (latest commit in the last month)

✔️ I am a regular committer (https://github.com/david-allison-1)
> * Project must be at least 3 months old and is in active development (with regular commits and activity)

✔️ Project is over 10 years old with regular commits 
> * Project meets the OSD specification

✔️ The Project meets OSD (GPLv3) 
> * Project must not be sponsored by a commercial company or organization (monetary or with employees paid to work on the project)

✔️  The project is not sponsored by a commercial company
> * Project can not provide commercial services or distribute paid versions of the software

✔️ The project provides no commercial services and is free to download from GitHub, and various app stores.
> 
> Does this sound like you and your project? We'd be very happy to support you!
> 
> However, if your project does not match these requirements or you have further questions, please feel free to ask!
> 
> We look forward to your response if you meet these requirements to proceed with the next steps.
> 
> Thank you

</details>

**Comment by mikehardy** [comment]
Moved to github actions
