### ISSUE TITLE
Full screen mode not working on pixel 5

### ISSUE THREAD

**Issue by mariano54** [ankidroid/Anki-Android#7608]
###### Reproduction Steps

1. Buy a pixel 5
2. Enable full screen mode with no answer buttons

###### Expected Result
Should not see answer buttons and top bar 

###### Actual Result
See answer buttons and top bar

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mariano54** [comment]
I realized that if I pull down from my notification bar and pull it back up, it succeeds in putting me in full screen.

But then I have no way to exit full screen! The swipe up to go home (pixel 5 gesture) is not working, it's overridden by the ankidroid gestures.

Anyway, I love the app, thank you so much for developing it, it's my favorite app.

**Comment by mikehardy** [comment]
Very strange! Thanks for the report - can you try using the latest alpha? You did not mention your version so I'm not sure what version you are on, but the gestures have seen a lot of work since 2.13.x
