### ISSUE TITLE
I'm able to review cards from a subdeck by clicking on its parent even though the "maximum reviews/day" was achieved in the subdeck but not on the parent deck 

### ISSUE THREAD

**Issue by MarcelloNastri** [ankidroid/Anki-Android#7625]
###### Reproduction Steps

1. Get an old deck from ~2011 that was backlogged.
2. Set the "maximum reviews/day" to 1. 
3. Create a new deck.
4. Set the"maximum reviews/day" to 9999.
5. Put the old deck as a subdeck of the new deck.
6. Review the one card on the old deck by clicking on the old deck.
7. Click the new deck.

###### Expected Result

When clicking the parent deck (new deck) I should receive the message "daily study limit reached" and not be able to review the due cards for the subdeck (old deck), which has reached it's number for the "maximum reviews/day" already.

###### Actual Result

Ankidroid shows the due cards (my backlog) to be reviewed (500+ cards).

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.13.5

Android Version = 9

ACRA UUID = 90aec22d-47ad-446f-9e35-ab7665569feb

Scheduler = std2

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Notes
I tried rescheduling all the cards for a different day but the cards still appeared to review.

**Comment by mikehardy** [comment]
Hi there - can you try with the latest alpha to see if you still reproduce this? https://github.com/ankidroid/Anki-Android/releases

**Comment by MarcelloNastri** [comment]
Tried with the AnkiDroid 2.14alpha27 release and the issue remains.

I also realized that even if I change the number of reviews for its direct parent deck, any other parent above that one is able to see the due cards.

Thank you for your help.

**Comment by dae** [comment]
I'm not sure I'm following your report - are you saying that only the limit of the deck you click on is being applied? If so, that's expected behaviour for the V2 scheduler.

**Comment by MarcelloNastri** [comment]
Below is a representation of the decks and their maximum reviews/day:
**A 9999
---- B 1**

The behaviour I get is:
I can review only 1 card when I click on the deck B directly.
I can review more than 1 card when I click on the deck A (or any upper deck) directly.

Let me know if that is the expected behaviour.

**Comment by dae** [comment]
Yes, it is covered on https://faqs.ankiweb.net/the-anki-2.1-scheduler.html

**Comment by MarcelloNastri** [comment]
The "issue" is a feature, you can close this. Sorry for not answering.

**Comment by awesome-rdash** [comment]
Hi, it appears that the behavior differ from Anki.

I have here 225 reviews to do while on mobile it's 2000+ (I have restrictions on subdecks).
![image](https://user-images.githubusercontent.com/2684614/107129219-234c1700-68c4-11eb-9e3f-afe88df63924.png)
I use Anki Version 2.1.35 (84dcaa86)

I prefer this behavior. Would it be possible to have an option, maybe for each deck?

Thanks
