### ISSUE TITLE
Feature Request: add 'abort learning & sync' to gestures 

### ISSUE THREAD

**Issue by littlefoodt** [ankidroid/Anki-Android#7633]
(I'm sorry I'm not experienced with github etiquette, I don't think I can add tags myself?  Sorry in advance etc.)

###### Explanation
This will mostly be useful for people who use both ankidroid (gestures), and Anki desktop. 

When reviewing cards on the go, gestures are great to quickly close (full screen) cards and go back to using other apps or putting the phone away. But this also means that if you did a couple cards while waiting for the start of a meeting/elevator/call/etc, it's really easy to forget to sync your progress so far.  If you then return to studying through anki desktop and forget about your phone, you can end up doing your cards twice. 

###### Suggestion
I would like to have a gesture added that syncs your progress. Either sync in combination with the 'abort learning' gesture, or create a different gesture for syncing, whatever works best. 

My best idea so far though, would be that you could keep the abort learning gesture and add a second gesture that does the same but also syncs. So 'Abort learning & Sync', that way people can pick their preferred method.  (But maybe you guys have a better idea.)

###### Explanation of my settings/gestures and how I run into this issue:
I go full screen, and use swipe left,right for my answers (again/good). Volume up for closing full screen, volume down to undo a review. For me that makes reviewing really fast and keeps distractions as low as possible. However, then something happens and I want to stop reviewing. So I press volume up, close the app with a swipe gesture, go on with what I have to do, and I forgot to sync. 

(Many thanks for all your hard work!  You have made my anki-time so much better!)

**Comment by david-allison-1** [comment]
Hi @littlefoodt 

Just want to say a quick thank you! The request was very well formatted. 

I've put in a Pull Request to implement this - assuming all goes well with the review, it'll be in an [alpha build](https://github.com/ankidroid/Anki-Android/releases). You can install these in parallel with AnkiDroid to try them out (select `Parallel.A.apk`).

Maintainers are responsible for tagging (it stops people from adding "Priority: Critical" to their requests.

I expect it'll be in 2.14alpha29, and I'll endeavour to ping you when this happens.

PS: Thanks for the thank you! 😁

**Comment by david-allison-1** [comment]
@littlefoodt Could you try it out and let us know if you encounter any problems: https://github.com/ankidroid/Anki-Android/releases/download/v2.14alpha29/AnkiDroid-2.14alpha29.parallel.A.apk

**Comment by littlefoodt** [comment]
Works like a charm! I went through half my cards while regularly syncing and double checking with Anki (desktop) and it works great. I'll keep going for a few days and if I notice anything odd I'll report back. Thanks a lot! :D

**Comment by karolzlot** [comment]
Hey, just wanted to point out that I think this is no longer possible to configure in newest version. I see that gestures settings now lack "abort learning & sync". 
Some more recent discussion is here: https://github.com/ankidroid/Anki-Android/issues/17084
