### ISSUE TITLE
Cards are hidden behind the toolbar and become hard to read (fail to adjust the card location when users toggle the full screen)

### ISSUE THREAD

**Issue by tingsu** [ankidroid/Anki-Android#7643]
###### Reproduction Steps

1. fresh install and create some cards in some deck
2. enable "Preferences" -> "Gestures" -> "Enable gestures"
3. chose "Preferences" -> "Reviewing" -> "Fullscreen mode" -> "Hide the system bars and answer buttons"
4. open the deck and review the cards 
5. scroll down to show the toolbar and answer buttons (now the cards are hidden behind the toolbar)
6. click the answer buttons (do not return back to the full screen), the cards are still hidden behind the toolbar (difficult for users
to read the cards)

###### Expected Result

Under the above full screen mode, (1) if the user scrolls down to show the toolbar and answer buttons when reviewing cards,
anki should *automatically* adjust the location of cards (e.g., showing the cards under the toolbar), and keep this location until the user returns back to the full screen mode; (2) when the user explicitly returns back to the full screen mode, anki should adjust the location of cards back again (e.g., showing the cards at the location of the original toolbar).

###### Actual Result

Under the above full screen mode, anki fails to adjust the location of cards. As a result, the user cannot easily review cards.

###### Debug info

This issue is reproducible on the latest release version (2.13.5) and the latest develop version (2.14alpha29), and is reproducible on Android emulator (Android 7.1) and Huawei nova 5 (Android 9.0).

The reproducing video:

![found_issue_in_v2 14alpha14_v2 14alpha16](https://user-images.githubusercontent.com/3156978/98621605-a05a0580-2342-11eb-9807-4590641c0f15.gif)

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [X] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by sjl872964789** [comment]
I also encountered this issue, any plan to fix this? Thanks.

**Comment by david-allison-1** [comment]
What's the use-case? 

When the app is full screen, I'd assume you're only temporarily using the app bar for an action, and it will be hidden again when the action is complete

**Comment by tingsu** [comment]
Thanks for the reply @david-allison-1 .

I encounter this issue when I try to open the notification or just try to open the app bar. But when the app bar is shown, the answer bar (again, good, easy) is also shown. Then I, as a user, may use the answer bar in this use-case, and easily note this GUI glitch issue. I think one easier way to avoid this issue is only show the app bar and do not show the answer bar together. When the answer bar shows, it is easier for users to use that and note this a bit unfriendly issue.  Hope my comments help.

**Comment by tingsu** [comment]
Thanks @david-allison-1 !

This issue could be a regression bug.  It works perfect on v2.5 (see the video below) but fail to work (behave like what I described in this issue report) since v2.6.  

![ankidroid_issue_7643](https://user-images.githubusercontent.com/3156978/99143264-69466580-265c-11eb-80c7-73816d2361e1.gif)

**Comment by david-allison-1** [comment]
Aiming to have this in for 2.15 once I get through with the Rust conversion. 

It's become personally frustrating now I'm using full screen.
