### ISSUE TITLE
Add the ability to sort alphabetically, I want to create a dictionary from Anki

### ISSUE THREAD

**Issue by vosirandr** [ankidroid/Anki-Android#7648]

**Comment by david-allison-1** [comment]
What's wrong with `Card Browser - `Change Display Order - By Sort Field`?

**Comment by vosirandr** [comment]
how to fix?

ср, 11 нояб. 2020 г., 1:49 David Allison <notifications@github.com>:

**Comment by vosirandr** [comment]
the sorting field contains a link to a picture, not a word

ср, 11 нояб. 2020 г., 8:29 Андрей Борисов <vosirandr@gmail.com>:

**Comment by sudomain** [comment]
This might be a silly question, but do you need to sort by these links to pictures often? You're probably better off changing the sort field to whatever the field is that you want to sort alphabetically via `manage note types > select note type > select field > sort by this field`. This is the purpose of the sort field according to Anki desktop's manual afterall.
