### ISSUE TITLE
Browser - Reposition: does not update cards or add undo 

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7674]
###### Reproduction Steps

1. Select a card
2. Reposition: 1

###### Expected

3. Undo reposition is visible
4. Card has the "due" updated

###### Actual

3. "Undo reposition" is not visible
4. Card has the same "due"

**Comment by david-allison-1** [comment]
Reschedule, Reset and Undo are also affected

Undo cause: 23f9d804f22cb87af322c279db7804b943f8d503

**Comment by Arthur-Milchior** [comment]
I just tested with v2.13.5, start of october, which does not have 23f9D80 and I can reproduce the problem.
Did you test on https://github.com/ankidroid/Anki-Android/pull/7677 to see whether you can reproduce it ? I would assume that you can.
