### ISSUE TITLE
Reviewer: "Lookup Dictionary" menu item is unused

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7679]
Functionality is hooked up, but not usable as the control is never made visible.

We should add this to "App Bar Buttons" so the user can move this around on the menu.

https://github.com/ankidroid/Anki-Android/blob/46075e2ccc93a40e3b64c39333263184f43fbe07/AnkiDroid/src/main/res/menu/reviewer.xml#L118-L121

**Comment by Abanoub-Asaad** [comment]
`I'm working on it`

Could you please provide a detailed description? 
Should I make this item appear? What's the funtionality of it and ... ?

**Comment by david-allison-1** [comment]
AnkiDroid has a lookup dictionary which is rarely used. It involves looking up selected text in one of a few externally defined dictionaries.

It can be enabled in the settings.

The current flow is: 

* Highlight a word, 
* Copy it
* A clickable "lookup" icon should appear, 

It would be helpful to also allow a menu item to replicate the functionality without copy/pasting the word:

* Highlight the word
* Select "Lookup" from the App Bar

The Menu Item is already defined in the linked code snippet, but the functionality was never implemented so the item is never shown.

This change would involve:

* Show the menu item if the "Lookup Dictionary" preference is enabled
* Disable the menu item when "Lookup Dictionary" preference is disabled
* Define the menu item https://github.com/ankidroid/Anki-Android/blob/5128cc2c756ce1434367eb58807650581f26c661/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java#L47
* Add a `ViewerCommand` for the functionality to lookup a word
* Implement the ViewerCommand in `AbstractFlashcardViewer`: do nothing/show a toast if no word is highlighted, otherwise perform a lookup search
* (Optional) Add a gesture for the functionality (see past PRs for how this is done - maybe add some documentation).

**Comment by mohaned-hassan** [comment]
can I work on this?

**Comment by david-allison-1** [comment]
Let's give it 48 hours. @Abanoub-Asaad are you still working on this?

**Comment by david-allison-1** [comment]
@mohaned-hassan All yours

**Comment by mohaned-hassan** [comment]
Thanks, on it.

**Comment by mohaned-hassan** [comment]
@david-allison-1 

Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/reviewer/ActionButtonStatus.java
`setupButton(preferences, R.id.action_search_dictionary, "customButtonSearchDictionary", SHOW_AS_ACTION_IF_ROOM);`

Can you please point out why the preference of the search_dictionary button has no value (always returns the default value)?
