### ISSUE TITLE
The "Rename note type" string is used when renaming a field

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#7695]
###### Reproduction Steps

1. Rename field
2. dialog pops up saying "rename note type"
3. 

###### Expected Result
The dialog should read "Rename field"

###### Actual Result
"Rename note type" appears instead. The actual renaming of the field works fine, just a wrong string

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.13.5

Android Version = 7.0

ACRA UUID = 0417c1bf-8871-4e84-9233-cfea8e42b734

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [ X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by sudomain** [comment]
I'm away from my dev machine, but I think [this is it](https://github.com/ankidroid/Anki-Android/blob/13eda5cd0b19256043250708e31086938f4d819d/AnkiDroid/src/main/java/com/ichi2/anki/ModelFieldEditor.java#L274)

**Comment by david-allison-1** [comment]
Yep, cheers!

**Comment by sudomain** [comment]
Beat me by a few seconds lol
