### ISSUE TITLE
Mac unit test fails

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#7702]
A lot of tests are failing on mac, with the message 
> An error occurred while generating the build script.

David found this link: https://travis-ci.community/t/osx-builds-on-travis-ci-com-start-to-fail-with-an-error-occurred-while-generating-the-build-script/10592

While it fails, I suggest we allow the mac build to fail, so that the remaining tests still goes on and we can get green light.

I am not stating it's impossible to get tests that really fail on mac only, but I've never seen it and believe that currently, mac tests are creating more trouble than protection

**Comment by mikehardy** [comment]
I use mac about half the time (Linux the other half), it should work, but macOS-land is in upheaval at the moment with the introduction of Big Sur. It's important to me to have macOS working as a development environment though, I'll take a peek and hopefully can get it working. If not I'll temporarily allow failure as you suggest though

**Comment by Arthur-Milchior** [comment]
When I state that it should be allowed to fail, I only meant in Travis. Of course, if you can't run the tests on your computer, that's a huge problem.

**Comment by mikehardy** [comment]
No longer relevant, we are moving to github actions. It does work locally :-)
