### ISSUE TITLE
[Feature request] Rebuild all filtered decks at once.

### ISSUE THREAD

**Issue by igorkudrin** [ankidroid/Anki-Android#7708]
I have several filtered decks in my setup to help conducting my learnings. It would be great if it is possible to update all them with just one command. For Anki Desktop there is a plugin which adds the "Rebuild All" button, which is very helpful, and I would like to have something similar in AnkiDtoid.

**Comment by mikehardy** [comment]
Hi there! This does sound useful - we try to implement only features that are in Anki Desktop though, not in plugins, as the scope of features is already so large with that restriction that we have a hard time keeping up. This seems like it could be a reasonable feature request for upstream though, have you tried asking there if it can go in as a 1st party (not add on) feature? If it did then we could follow suit here

https://forums.ankiweb.net/

**Comment by igorkudrin** [comment]
Hi Mike,

Thanks for the quick response! I've created a suggestion topic there, https://forums.ankiweb.net/t/add-rebuild-all-and-empty-all-commands-into-anki-desktop/5202. Let's see how it goes.

**Comment by mikehardy** [comment]
Great! Thanks for doing that. If I could beg for one more thing :-), if you could carry the resolution (whatever it was) back to this issue here that would help us keep the conversation intact. I'm interested to see how it goes
