### ISSUE TITLE
Get stuck or even frozen occasionally

### ISSUE THREAD

**Issue by dfliaoyue** [ankidroid/Anki-Android#7709]
###### Reproduction Steps
Don't know. Seems to appear occasionally over time.
1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.13.5

Android Version = 11

ACRA UUID = 2b2c1683-153d-46c7-8771-8b4e782cb56c

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! If I'm not mistaken I just interacted with you on the Play Store in a review, welcome to our github home.

Hopefully we can figure out what is going on, but the key will be figuring out exactly how to reproduce it - we can only fix things we can see. If there was any way you could share your collection, and a series of actions that showed the slowness, then we could nail it. I understand some people have personal information in their collections though, so sometimes that is not possible.

If you can share your collection - it's just an export (from the top right menu on the deck picker), without media, and if you change the extension to .zip you can upload it here. Then we would just need some usage scenario that shows the slowness

**Comment by dfliaoyue** [comment]
[collection-20201118120259.colpkg.zip](https://github.com/ankidroid/Anki-Android/files/5557682/collection-20201118120259.colpkg.zip)

I always use the larger deck first, when the bug appeared. Sometimes it's smooth, but sometimes laggy.

**Comment by dfliaoyue** [comment]
Sorry but I don't see any necessary to record screen, for it is just frozen.
Exactly, after opening a deck and going through some cards, it is irresponsible. A few minutes' wait may fix it, but if force-closing the app and reopening it, the number of remaining cards is reset (but the number of finished cards remains).
Seemingly the app increasingly slows down till it's frozen during a task. And if it goes well at the outset, it will be fine all along.

**Comment by qsantos** [comment]
I have encountered this behavior numerous times. This happens whenever the database is updated ; for instance, when judging a review, or when synchronizing the database. I have > 1 M reviews and tens of thousands of cards, so it might be related to that.

Clicking on “Check the database” in the menu in the upper-right corner of the home screen seems to fix the issue.
