### ISSUE TITLE
Night mode still enabled in a certain deck after switching to light mode

### ISSUE THREAD

**Issue by kuri7** [ankidroid/Anki-Android#7715]
###### Reproduction Steps

1. Use night mode.
2. Disable it.
3. Review a card.

###### Expected Result

The card should be in light mode as expected.

###### Actual Result

Since night mode was disabled, the cards should be in light mode. Instead, the cards are still in dark mode (black). This happens for two decks out of three. The deck where this doesn't happen is a user-created deck directly in Ankidroid.

###### Debug info

AnkiDroid version = 2.13.5

Android version = 8.0.0

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
It'd be useful if you provided an export of the decks in question.

This is possibly a content issue, and not an AnkiDroid issue, since the issue does not appear on all decks. Have you looked at the card template (edit a card and click "cards") to see if there is CSS/JavaScript causing this.
