### ISSUE TITLE
[Accessibility] Touch Target is not respected.

### ISSUE THREAD

**Issue by andreacantone** [ankidroid/Anki-Android#7716]
###### Reproduction Steps

1. Activate the app [Accessibility Scanner](https://play.google.com/store/apps/details?id=com.google.android.apps.accessibility.auditor&hl=it&gl=US)
2. Open the app Anki-Android.
3. Activate the registration from the Accessibility Scanner and use the Anki-Android app.
4. After using the app, stop the recording.

###### Expected Result

The size of the elements should be at least 48dp*48dp.

###### Actual Result

Some elements don't respect the size of the touch target.

![IMG_20201118_175515](https://user-images.githubusercontent.com/25429624/99562366-4b646200-29c8-11eb-827d-0b9af4cad9b4.png)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! I have tried Accessibility Scanner against AnkiDroid myself and the results were...voluminous. There are a *lot* of issues. Logging them each independently is counter-productive I think, there are just too many. What we really need here are PRs that fix issues found. Are you open to fixing these?

**Comment by andreacantone** [comment]
@mikehardy Unfortunately, I can't fix the bugs because I'm working on a research study on accessibility in Android but I can't solve the bugs because of lack of time, but I can provide information about the accessibility errors found, if someone else can fix the bugs.

**Comment by mikehardy** [comment]
@andreacantone given that the Accessibility Scanner already provides the information, and it would be how testing is performed after changes to verify the fix, I don't think that is really actionable either. The action is really just "run the Accessibility Scanner and follow it's guidance" (in general). Duplicating that info here seems like wasted effort. The problem I see is that without some "taste" (experience / wisdom) in the area it is hard for me to say where to start even - what the important priorities are.

If you have experience in the area or guidance about the most important things to fix first, or some literature you could point us to on that, it would move this forward as it starts to be more actionable

**Comment by Arthur-Milchior** [comment]
@mikehardy I'm conflicted here. I do find useful to have multiple bug reports. Mostly because we may want to have separate discussion for each accessibilities issues. If we want to go this way (which is probably a good idea), we'll need to decide what to do. 
For example, in this case, I would admit that trying to respect accessibilities norm by having our buttons respecting the standard's minimal size for usability seems an excellent and simple idea. Except that doubling the line's size mean that we'll have twice less decks on the screen, and that is a change I really would not like. This probably mean allowing user to change the line's size, and if we go this way, that's something we need to discuss before implementing it.

**Comment by mikehardy** [comment]
Maybe an accessible toggle that goes to a low vision mode. I don't know. I want one umbrella to start that talks about the approach really. I do not want 100 accessible issues
