### ISSUE TITLE
Ungently need python 3.9 support for anki

### ISSUE THREAD

**Issue by dima4p** [ankidroid/Anki-Android#7720]
I am very sorry for disturbing you. I did not find how to report this issue directly to anki team. I hope, someone of your team has a contact with them.

My distro have upgraded python 3.8 to 3.9 and I cannot run anki on my machine.

Thanks in advance for help.

**Comment by david-allison-1** [comment]
Hi @dima4p 

https://forums.ankiweb.net/ would be your best bet.

I'm closing this as it's not actionable from the AnkiDroid side, but please do reply if we can help more

David
