### ISSUE TITLE
SyncError with TLS 1.3-only servers

### ISSUE THREAD

**Issue by kitambi** [ankidroid/Anki-Android#7725]
###### Reproduction Steps

1. Set up a TLS 1.3-only sync server (Apache directive: SSLProtocol -all +TLSv1.3)
2. Set up AnkiDroid to sync to this TLS 1.3-only server

###### Expected Result
Successful sync with ankisyncd server, as it would with TLS 1.2 enabled.

###### Actual Result
This misleading error message:
Sync error
Connection timed out. Either your internet connection is experiencing problems, or you have a very large file in your media folder.

SSLException while building HttpClient

###### Logcat
[anki-ssl-handshake-error.log](https://github.com/ankidroid/Anki-Android/files/5567243/anki-ssl-handshake-error.log)

###### Debug info
AnkiDroid Version = 2.14.0
Android Version = 9
ACRA UUID = 6d584fe8-b805-480e-821b-6b0dd8f4a92a
Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I'm going to trust OkHTTP on this one, until proven otherwise you have a setup error on your sync server

```

11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at java.lang.Thread.run(Thread.java:764)
11-19 14:32:47.181  3597  4555 E AnkiDroid: Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:286)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:11)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:9)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:15)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:37)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:1)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:6)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:5)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:22)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:22)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at okhttp3.RealCall.execute(RealCall.java:9)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at com.ichi2.libanki.sync.HttpSyncer.req(HttpSyncer.java:39)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	... 14 more
11-19 14:32:47.181  3597  4555 E AnkiDroid: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7d0d1e4c88: Failure in SSL library, usually a protocol error
11-19 14:32:47.181  3597  4555 E AnkiDroid: error:1000042e:SSL routines:OPENSSL_internal:TLSV1_ALERT_PROTOCOL_VERSION (external/boringssl/src/ssl/tls_record.cc:592 0x7d0d07d348:0x00000001)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
11-19 14:32:47.181  3597  4555 E AnkiDroid: 	... 34 more
11-19 14:32:47.181  3597  4555 E AnkiDroid: 

```

**Comment by david-allison-1** [comment]
TLS1.3 is not supported natively by Android 9 (it requires Android 10 or later).

> Protocol | Supported (API Levels) | Enabled by default (API Levels)
> -- | -- | --
> TLSv1.3 | 29+ | 29+

https://developer.android.com/reference/javax/net/ssl/SSLSocket


It seems we could solve this via a dependency: https://stackoverflow.com/questions/55539513/how-to-enable-tlsv1-3-for-okhttp-3-12-x-on-android-8-9

**Comment by mikehardy** [comment]
I built this with conscrypt once as a test to workaround the 1.2 restriction and get Android 4.x working, it adds a great deal to the APK size (by vague memory, like 1-2MB) for not-strictly-required functionality, plus is security surface area, so I do not want to do that. We will rely on platform encryption libraries.

Thanks to Project Treble if your phone has Android 9, Android 10 should be possible (if not now then soon) as vendor upgrades are much easier, perhaps that is an option? Or, just use 1.2 for now? 1.3 is just starting to roll out everywhere not having the new-new working when dealing with operating systems is not cause for alarm, for me
