### ISSUE TITLE
Suspended Cards in Filtered Decks losing Suspend State when Rebuilding or Emptying

### ISSUE THREAD

**Issue by uoQg1lZlYz** [ankidroid/Anki-Android#7730]
###### Reproduction Steps

1. Enable **V2 Scheduler**
2. Create a **Filtered Deck** with Search `deck:"All" is:due or is:new`
3. Create a Random Card(s)
4. **Rebuild** the **Filtered Deck**
5. **Suspend** any Card(s) while in **Filtered Deck**
6. **Browse** `is:suspended` [cards are properly suspended]
7. **Empty** or **Rebuild** Filtered Deck
8. **Browse** `is:suspended` again [cards magically disappear from being suspended and go right back into the Filtered Deck (if **Rebuild**) and Normal Deck (if **Emptied**)]

###### Expected Result

- Cards should still be `is:suspended` even after **Empty** or **Rebuild**.

###### Actual Result

- Cards are un-toggling Suspend State after **Empty** or **Rebuild**.

###### Debug info

AnkiDroid Version = 2.14.0

Android Version = 9

ACRA UUID = a3b00b3e-08b5-40b5-b253-aa6f9995181f

Scheduler = std2

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

---

### Temporary Hack Solution

For those that are facing this problem and want a temporary hack solution try:-

1. Add `-flag:1` to your Main **Filtered Deck**'s Search e.g. `(deck:"All" is:due or is:new) -flag:1` 
_Note:_ Remember to surround your original Search settings with Brackets as shown in the example above ⬆️ 
2. While studying in your Main Filtered Deck and you encounter a Card you want to Suspend. **Flag** it **Red** instead!
3. After your done studying your Main Filtered Deck. **Rebuild** or **Empty** it. [All your **Flag Red** Cards should be **kicked** out of your Filtered Deck now]
4. Go to **Card Browser** and search for all the **Flag Red** Cards
5. **Select All** Cards and **remove** the **Flag Red** (by applying a **No Flag**)
6. Now with all Cards still selected. **Suspend** them! [Suspending Cards outside the Filtered Deck works so don't worry!]
7. Profit?

_Alternatively:_ If you use **Flag Red** for other things then you can substitute `flag:1` with `tag:marked, flag:2, tag:<Your_Made_Up_Tag>, etc.`

#### Extra Info

- `flag:1` = Flag Red
- `flag:2` = Flag Orange
- `flag:3` = Flag Green
- `flag:4` = Flag Blue
- `tag:marked` = Starred Card
- `tag:<Your_Made_Up_Tag>` = A Tag that you made

**Comment by david-allison-1** [comment]
Hi @uoQg1lZlYz, thanks for the report! Will look into it now.

**Comment by uoQg1lZlYz** [comment]
Thank you for the speedy reply!

Is it ok if I edit the Original Post and add a **Temp Hack Solution** at the end of the Post to help those who are facing this problem?

Or should I just do it as a new reply?

**Comment by david-allison-1** [comment]
Of course! Edit away

**Comment by david-allison-1** [comment]
Related: https://github.com/ankitects/anki/commit/fe493e31c4d73ae2bbd0c4d8c6b835974c0e290c

https://anki.tenderapp.com/discussions/ankidesktop/38247-bug-suspended-cards-automatically-included-in-the-filtered-decks

**Comment by david-allison-1** [comment]
@uoQg1lZlYz I just want to stop back and say thank you so much for the detailed reproduction steps, this made the fix super-easy 💯 💯💯

**Comment by uoQg1lZlYz** [comment]
@david-allison-1 Anything to make it easier for the Dev's! ❤️ ❤️ ❤️ 

I'm happy I could help!

**Comment by mikehardy** [comment]
Yeah, this might be the bug report of the year because of all the details. Nice!

**Comment by uoQg1lZlYz** [comment]
@mikehardy Bug report of the year, nice! Thank you for that. I'm flattered!

And Thank you all for all the hard work on creating and maintaining such an amazing app! I'm truly grateful! ❤️
