### ISSUE TITLE
Numeric Keypad doesn't work on version 2.14.0

### ISSUE THREAD

**Issue by CrypticToilet** [ankidroid/Anki-Android#7736]
After upgrading  AnkiDroid 2.14.0, it couldn't react my numeric keypad (However, only enter key seems to work normally)

I tried turning on and off The NumLock key , but it didn't seem to make sense.

I don't know what version I used before because my Google Play App automatically updated my AnkiDroid.

so I downgraded to version 2.13.5 using the apk file and my numeric keypad is working normally. I think it's a version problem.

hope this will be helpful in the development.

**Comment by david-allison-1** [comment]
Hi, thanks for the report. Which screen are you trying to use the numeric keypad with?

**Comment by CrypticToilet** [comment]
oh, I forgot writing my environment.
when answering cards, my numeric keypad didn't react. [again], [hard] and [easy] can't be pressed. but enter key only works and Good button is okay.

tablet: Kindle Fire HD(Fire OS)
numeric keypad: USB

thank you for replying!

**Comment by david-allison-1** [comment]
Hi @CrypticToilet, would you consider yourself to be technically capable? 

It'd be really useful to get the data on the details of the  buttons being pressed - I'd have hoped there would be a good app on the play store for this, but I've come up blank

**Comment by Nabokov86** [comment]
I confirm this problem. In 2.13.5 these buttons acted like this:
"NUMPAD_1" - Again
"NUMPAD_2" - Hard
"NUMPAD_3" - Good
"NUMPAD_4" - Easy 

Too bad, I also used numpad for quick answers.

**Comment by david-allison-1** [comment]
Could you test to see if things work between these two versions:

https://github.com/ankidroid/Anki-Android/releases/download/v2.14alpha12/AnkiDroid-2.14alpha12.parallel.A.apk - should work
https://github.com/ankidroid/Anki-Android/releases/download/v2.14alpha13/AnkiDroid-2.14alpha13.parallel.A.apk - should fail

**Comment by Nabokov86** [comment]
@david-allison-1 That's correct.

Version alpha12 works, but alpha13 doesn't.

**Comment by david-allison-1** [comment]
@Nabokov86 Do you need to press any other keys to get a "1" to appear on your keyboard? Holding down function/shift for example?

**Comment by Nabokov86** [comment]
No, I just press on this button KEYCODE_NUMPAD_1 = 145, or this KEYCODE_1 = 8. Standard keyboard with standard android keycode.
