### ISSUE TITLE
Please swap search and sync buttons

### ISSUE THREAD

**Issue by julienbaley** [ankidroid/Anki-Android#7737]
###### Reproduction Steps

1. use Ankidroid for years
2. update to newest version
3. click on the sync button

###### Expected Result

It syncs.

###### Actual Result

It opens a search! Everyone has probably built a muscle memory regarding sync, and the sync button has just been moved to make way for a search button that's used (I believe) far less frequently. Is it still possible to fix this? Please~ :)

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi. I was originally concerned that menu items may be hidden if there are too many - sync is most important, so it should be at the "top" of the priority list, which moves it to the left.

But, as we're using "always show", this shouldn't be a problem

Thanks for caring!

https://github.com/ankidroid/Anki-Android/blob/1be10dcaa8afe80c474435b9e568b6df24a0c593/AnkiDroid/src/main/res/menu/deck_picker.xml#L3-L13

**Comment by julienbaley** [comment]
I couldn't tell if your message meant you would want to fix this or not, until I saw the "accepted" label :)

Thanks for this! I haven't hit the sync button a single time since the update :-(

**Comment by david-allison-1** [comment]
@julienbaley Just to let you know, we have "auto sync every 10 minutes" in the AnkiDroid preferences. 

I added a "close and sync" gesture to 2.14.0

We also have a "pull down to sync" function on the deck list.

**Comment by julienbaley** [comment]
> Just to let you know, we have "auto sync every 10 minutes" in the AnkiDroid preferences.

Oooh, I'm activating this right now, that's awesome :)
Anki on desktop has recently (in the last few months) made the sync lightning fast, is this something that will happen to Ankidroid too?

> We also have a "pull down to sync" function on the deck list.

I do use it sometimes, but it only works if you're already "scrolled up", and my deck list is rather long (28 decks at the moment).

**Comment by david-allison-1** [comment]
> > Just to let you know, we have "auto sync every 10 minutes" in the AnkiDroid preferences.
> 
> Oooh, I'm activating this right now, that's awesome :)
> Anki on desktop has recently (in the last few months) made the sync lightning fast, is this something that will happen to Ankidroid too?
> 
> > We also have a "pull down to sync" function on the deck list.
> 
> I do use it sometimes, but it only works if you're already "scrolled up", and my deck list is rather long (28 decks at the moment).

I've got a change which is just about to go into testing to start this work. It'll take quite some time for us to get around to improving syncing, but it will happen.

**Comment by julienbaley** [comment]
Looking forward to it, thanks for the awesome work :)

**Comment by julienbaley** [comment]
> we have "auto sync every 10 minutes" in the AnkiDroid preferences.

I've had it since yesterday, and wanted to give feedback on the feature. I think it's extremely useful, but would really reach its full potential if "open" was the criterion instead of "start": most of the time, I switch between apps and never really "exit" (and therefore neither "start") Ankidroid, so when I switch back to it, it doesn't seem to be considered a start and therefore doesn't auto-sync. I don't know how easy a change it would be, but that's what would make the feature useful for me. :)

**Comment by mikehardy** [comment]
interesting idea. There was a push to organize and expand auto-sync capabilities before, and "app state" (foreground or background) is actually one of the reliably detectable things in Android (tech note: using the "lifecycle" architecture components, they let you set listeners for pause/resume app state which equates to foreground/background.

**Comment by mikehardy** [comment]
Separately (because I saw it separately - I'm processing the notifications as an email queue, sorry 😅 ) thanks for the note on the lighting fast desktop sync. I wasn't aware there was more speed to be gained there but maybe there is? Maybe it's part of the bit-by-bit conversion of desktop to Rust language from Python and Rust is just faster 🤔

**Comment by david-allison-1** [comment]
And the media sync (which takes the majority of the time) is moved to the background. There's a pending issue for this somewhere in the backlog
