### ISSUE TITLE
Warn on use of HTTP image

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7741]
See: #7231

HTTP images are no longer supported. 

https://github.com/ankidroid/Anki-Android/blob/83afaf6176d3e97068630733131e5e0b213bf13c/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L3198-L3225

Maybe link to: https://github.com/ankidroid/Anki-Android/wiki/FAQ#external-content

**Comment by TKGZ** [comment]
I'll try this one next! 👍

**Comment by TKGZ** [comment]
@david-allison-1  Are there other situations where you would put a similar warning that you have in mind for this one? (for example a warning of invalid image) - just so I can have a feel for how these are usually styled.

**Comment by Arthur-Milchior** [comment]
@TKGZ You can try to create a card with a missing image. E.g. opening a card with a image and changing the name of the image to an invalid one. You should get a similar warning

**Comment by TKGZ** [comment]
> @TKGZ You can try to create a card with a missing image. E.g. opening a card with a image and changing the name of the image to an invalid one. You should get a similar warning

Thanks!

**Comment by TarekkMA** [comment]
Hi, I would love to take a go at this issue. How should we warn the user about the use of a http resource in the card?

Will a simple toast do the trick or we need to maybe inject some html elements in place of the image.

right now I have made it so a toast will pop up when an http uri is intercepted
<img src="https://user-images.githubusercontent.com/6633545/110652629-386add00-81c5-11eb-96ca-a9845a0801d9.png" width="35%">

**Comment by david-allison-1** [comment]
A Snackbar would be best, as it allows a "help" link.

See: 

https://github.com/ankidroid/Anki-Android/blob/83afaf6176d3e97068630733131e5e0b213bf13c/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L3572-L3575

**Comment by TarekkMA** [comment]
Okay will do a PR tomorrow with that implemented
