### ISSUE TITLE
Vivo Y20 - Create Shortcut does not work

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7743]
Reported on discord

> Example of change in the new version: if you long click on a deck, you can add it on your android screen. You'll get a button opening directly this deck without going through the list of deck.
>
> Bug: i cant add Deck to my Home screen on Android 10 device Vivo Y20
>
> I click on Create Shortcut.. nothing happens

Related: #6995

This seems to be a Vivo-specific issue.

**Comment by david-allison-1** [comment]
This can be fixed via: https://www.youtube.com/watch?v=zl3CFjPUKeo

**Comment by Arthur-Milchior** [comment]
Probably a twitter follower given what they quoted

**Comment by david-allison-1** [comment]
Phone data: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/reports-browser/user/ae733d56-a5ac-46eb-ba84-1b655fb818d0

I'll use manufacturer == "vivo"

**Comment by david-allison-1** [comment]
Please do not close this until I've done an acceptance test with the affected user.

**Comment by david-allison-1** [comment]
This was not resolved in 2.14.1 - presumably Vivo returns `true` even if this is not handled

**Comment by david-allison-1** [comment]
Resolved 
![image](https://user-images.githubusercontent.com/62114487/100536286-7c8a3100-3217-11eb-922f-5774ef01be9b.png)

**Comment by mikehardy** [comment]
if ("shaven".equals(yak.hairStatus()) {
  ✨ 
} else {
  yak.shave();
}
