### ISSUE TITLE
Duplicate warning no longer working

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7746]
Play Store Review 

> However the latest update has introduced an issue. If you are trying to add a card with the same word the app doesn't warn you anymore. I hope to see it fixed soon.

**Comment by mikehardy** [comment]
We need to verify that this is against the same card type. The warning is only for the same type as you might have different languages in learning, with valid duplicates. Upstream docs mentioned this

**Comment by david-allison-1** [comment]
It's broken within the same note type for me, seems to be on note types with more than 2 fields

I presume 95af4ee94952982fd40ce37765ca76c9e190acbb

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/b592d2c33cc0c8b43bca5b5938e8e87b8e10ba1f/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java#L284-L294 is badly broken, which will slow down the testing

**Comment by david-allison-1** [comment]
Copy/paste error on https://github.com/ankidroid/Anki-Android/blob/38a8fb474e4221b277b76802770b4d76d22ed82f/AnkiDroid/src/main/java/com/ichi2/libanki/Note.java#L301

If the sort field is changed, then the feature is broken
