### ISSUE TITLE
Add lint check to stop using onPrepareOptionsMenu

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#7757]
We should add a lint check to stop using onPrepareOptionsMenu 

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/7756#issuecomment-731749243_

----

Until we're past Android 8.0.0

**Comment by TarekkMA** [comment]
If this rule added what should we do with this code? move it to `onCreateOptionsMenu`?

https://github.com/ankidroid/Anki-Android/blob/a1ebaa00664bdb54a439da83dc6207194228e9d4/AnkiDroid/src/main/java/com/ichi2/anki/DeckPicker.java#L665-L672

**Comment by mikehardy** [comment]
this is good to keep in stock for first issues

**Comment by BrayanDSO** [comment]
Since the issue is just `menu.findItem` returning null at `onPrepareOptionsMenu`, save the item reference at `onCreateOptionsMenu` and use it back at `onPrepareOptionsMenu`
