### ISSUE TITLE
The string, "Card info" hasn't been translated on the card-browser-selected menu, though it has properly been done on the title of the card-info scteen 

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#7758]
###### Reproduction Steps

1. Change [Language] from English to Japanese. 
2. Go to [Card browser]
3. Long tap a row
4. Tap [More options]

###### Expected Result
[Card info], one of the items of the menu, has been translated into Japanese.

- I translated the string on Crowdin on November 5, and the string has properly been reflected on the title of the card-info screen.
- The tagged screenshots on the page below shows the string should be reflected on both the title of the card-info screen and the card-browser-selected menu.
https://crowdin.com/translate/ankidroid/all/en-ja?filter=basic&value=0#q=Card%20info

###### Actual Result

The strings, "Card info", hasn't been translated.

###### Debug info
2.14.0
and
2.15alpha5

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
@snowtimeglass  Thanks for the report!

Fix will be in the next version.

I'll see if I can add a lint check to ensure we don't fall afoul of this in future.

**Comment by snowtimeglass** [comment]
@david-allison-1 Thank you for the fix!
