### ISSUE TITLE
Using `import()` in WebView

### ISSUE THREAD

**Issue by hgiesel** [ankidroid/Anki-Android#7760]
###### Reproduction Steps
1. Use dynamic module import via `import()` in WebView of reviewer

###### Expected Result
You get a promise with a resolved module.

###### Actual Result
```
Access to script at 'file:///storage/emulated/0/AnkiDroid/collection.media/__closet.js' from origin 'null' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, https.
```

###### Debug info
AnkiDroid Version = 2.15alpha6
Android Version = 11
ACRA UUID = a59979cb-3332-4b9d-b7de-d3abc56057c5
Scheduler = std2

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

This fails on AnkiDroid, because collection.media is accessed through a `file` scheme, whereas on AnkiMobile and AnkiDesktop, it is accessed through an `http` scheme. I wonder if there could be a way to make it on AnkiDroid as well. Same is true for using `fetch` in the WebView.

I'm the developer of [Closet](https://ankiweb.net/shared/info/272311064), probably the most elaborate JavaScript add-on so far in the Anki sphere, and looking for a way to reliably load it from within the reviewer WebView across platforms.

**Comment by mikehardy** [comment]
Thanks for reporting this! I want our javascript capabilities to be both useful and compatible with Anki ecosystem so we need to fix this some how. We're still stabilizing the release-2.14 code branch but should have some time to look at this shortly.
