### ISSUE TITLE
[Suggestion] Omit seconds of the study dates on Card Info screen

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#7762]
Card Info screen is very useful. Thank you very much.

However, the study date on the screen seems a bit too detailed. Isn't it enough to display time in hours and minutes? How about omitting the figures of seconds (as Anki Desktop does)?

The omission will make the screen more neat, and it'll even reduce the possibility of line-break in a record.

**Comment by david-allison-1** [comment]
Thanks for the feedback!

I wrote the Card Info screen in a few hours when I wanted a break from another much more complex project.

We'll be replacing the Card Info screen with the one used in Anki Desktop in the coming months. 

I suspect this won't be worked on in that time period, but we'll be consistent with Anki Desktop's display eventually.

**Comment by snowtimeglass** [comment]
Thank you for the comment. 
I'm looking forward to the change leisurely :-)
