### ISSUE TITLE
Note Editor Toolbar: Add Color Picker

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#7766]
Hello guys. I am totally new to open source development. I am a ux designer, and an active user of Anki, and I would like to somehow help to improve Anki's user experience. I have created an interactive prototype to deliver some inspiration about how color picking could work seaminglessly. It is not fully functional, but can showcase the concept. [It is available from here.](https://x3auwf.axshare.com/#id=aiez77&p=page_1&sc=2
)
Please let me know guys what do you think.

_Originally posted by @jakabbalint in https://github.com/ankidroid/Anki-Android/issues/1377#issuecomment-731224578_

----

I love this design and feel we can use the same "edit" mechanism for the custom buttons - it's much more intuitive than long-pressing to delete.

**Comment by sakshi-1604** [comment]
I would like to work on this

**Comment by david-allison-1** [comment]
Thanks! Do check out the design. It's lovely: https://x3auwf.axshare.com/#id=aiez77&p=page_1&sc=2

**Comment by mrudultora** [comment]
@sakshi-1604 Are you still working on it ?

**Comment by sakshi-1604** [comment]
I was working on it . But as my college exams are going on I am going to submit pr after 1,2 weeks

**Comment by sakshi-1604** [comment]
Yes

**Comment by tapish2000** [comment]
@sakshi-1604 I just want to ensure if you are still working on this? If you face any issues or unable to complete it, feel free to write here.

**Comment by mrudultora** [comment]
@david-allison-1 I was thinking that in the proposed PR the library used is not maintained (as Mike suggested). So, rather than giving support for many colors, why not we give support for 3-4 important colors (as suggested in design). And if **sakshi-1604** is not taking this up, I would like to work on it.

**Comment by mikehardy** [comment]
The PR already has a batch of specific colors, I think it has those *and* the color picker. Just having the specific colors part seems adequate

**Comment by david-allison-1** [comment]
> @david-allison-1 I was thinking that in the proposed PR the library used is not maintained (as Mike suggested). So, rather than giving support for many colors, why not we give support for 3-4 important colors (as suggested in design). And if **sakshi-1604** is not taking this up, I would like to work on it.

@sakshi-1604 
Would you be happy with this? @mrudultora feel free to take this on in 48 hours if there's no response

**Comment by sakshi-1604** [comment]
Okay ,so I will add specific color only , instead of adding many colors.

**Comment by david-allison-1** [comment]
@sakshi-1604 are you working on this, or would you like it unassigned?

**Comment by david-allison** [comment]
I liked this in 2020, and I still like this
