### ISSUE TITLE
Note Editor: Preview of mixed RTL Text mismatches EditText

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#7767]
Reported in the mailing list:

https://groups.google.com/g/anki-android/c/M6TI4ZOqNNQ/m/YnYGfD6qAQAJ

Text: `אני אוהבת {{c1::chocolate ופיצה}}`

Pasting this into AnkiDroid displays this correctly: 

![image](https://user-images.githubusercontent.com/62114487/100061466-04da9180-2e26-11eb-8496-5a8e30dc3417.png)

But displays as:

![image](https://user-images.githubusercontent.com/62114487/100061508-12901700-2e26-11eb-9120-737d3a06436e.png)

**Comment by david-allison-1** [comment]
We can wrap the content in `<span dir="rtl"></span>` when we encounter it (check if the EditText is RTL), but this means that the EditText no longer appears as RTL

We can prefix this value with a RTL mark (copy from: http://www.unicode-symbol.com/u/200F.html)

```
אני אוהבת {{c1::chocolate ופיצה}}

<span dir="rtl">אני אוהבת {{c1::chocolate ופיצה}}</span>

‏<span dir="rtl">אני אוהבת {{c1::chocolate ופיצה}}</span>
```

![image](https://user-images.githubusercontent.com/62114487/100065600-e11a4a00-2e2b-11eb-9b36-5ab49a63d30a.png)

----

![image](https://user-images.githubusercontent.com/62114487/100065565-d5c71e80-2e2b-11eb-95ae-c1d9e29d7ee7.png)

-----

**Comment by david-allison-1** [comment]
After some thought, handling RTL via appending data to the fields will likely end up being nasty, and it might be better handled by the user in the card template than in the editor (possibly along with some UX hints to detect RTL text and suggest this to the user).

@dotancohen Do you have any thoughts on this? What do you do in this situation with your cards? 
I'm currently well out of my depth with what a good RTL language experience is.

**Comment by dotancohen** [comment]
In Anki desktop, fields can be marked as LTR or RTL. I have two cloze Note Types: one for LTR cloze notes, and one for RTL cloze note. I just tested creating RTL cloze notes in Ankidroid and it works perfectly, for the RTL cloze note type.

In all cases, RTL should be handled by the framework, not the app! Apps never get all the cases correct (and there are many many corner cases in regards to cloze in RTL), and frameworks have proper support and testing.

I do see that the AnkiDroid feature for managing note types does not have facility to mark a field as LTR or RTL. So in order for this user to create an RTL cloze note type, either he needs to do so in Anki desktop, or this feature needs to be added to AnkiDroid.

I can also send to this user an empty deck containing an RTL cloze note type that they can use.

**Comment by david-allison-1** [comment]
Thanks so much for the guidance, I'll need to look more into this. It's an aspect of the software that I haven't had any experience with.

Adding the RTL option seems like the most sensible option. 

Is this all that you'd recommend for the moment, or is there more that we can/should do to improve the experience?

**Comment by dotancohen** [comment]
> Is this all that you'd recommend for the moment, or is there more that we can/should do to improve the experience?

From a technical perspective, really, that is all that should be done. But users do need to know that the option is there and how to use it. I'll review the docs and add a section for RTL users.

Are the files for [the official docs](https://docs.ankidroid.org/manual.html) not in the git repo, or am I just not finding them?

**Comment by mikehardy** [comment]
@dotancohen your wisdom here has been fantastic, thanks for helping - the docs are in a separate for...reasons(?) https://github.com/ankidroid/ankidroiddocs/

**Comment by dotancohen** [comment]
> @dotancohen your wisdom here has been fantastic, thanks for helping - the docs are in a separate repo for...reasons(?) https://github.com/ankidroid/ankidroiddocs/

Thanks, PR here:
https://github.com/ankidroid/ankidroiddocs/pull/82

**Comment by dae** [comment]
@david-allison suggest closing in favor of an "integrate desktop editor" issue

**Comment by mikehardy** [comment]
100% on integrate desktop editor yes - maintaining a mediocre editor here is a terrible idea
