### ISSUE TITLE
Crop after taking image does not work

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7768]
* Take Image
* Crop dialog appears - select crop
* Crop Image
* Image is not cropped

Pressing "Crop Image" works

**Comment by mikehardy** [comment]
There was another review that mentioned this yesterday but without repro steps - I saw the response you made to the new one today and cross-linked the other review.

What happened though? I think this worked in the original crop implementation I brought in from the old PR - you helped QA the heck out of that one too! Possible regression from one of either the FileUpload libanki API changes or the refactor in there recently

**Comment by david-allison-1** [comment]
Likely cause: https://github.com/ankidroid/Anki-Android/pull/7435

**Comment by david-allison-1** [comment]
Apparently it's been broken since 2.13.5

This may be the cause of the fix for https://github.com/ankidroid/Anki-Android/issues/7232 not working
