### ISSUE TITLE
[Bug] Strings for copied images are always pasted at the end of the field irrespective of the cursor position.

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#7770]
###### Reproduction Steps

1. Copy an image on Chrome
    (Long-tap and select "Copy image")
2. Open Note Editor of AnkiDroid
3. Input some strings in a field
    (or select in your mind a field in which some strings have already input) 
4. Tap a position other than the end of the field
   (Then, the cursor blinks at the position)
5. Tap the position again
   (Then, the context menu is displayed) 
6. Select "Paste"

###### Expected Result

The string to show the image, e.g. `<image src="1234567812345678.png">`, is inserted in the position, as copied strings are generally done, and as copied images are done on Anki Desktop.

###### Actual Result

The string to show the image is pasted at the end of the field.

###### Debug info
ver 2.15alpha7

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Nice @snowtimeglass thanks as ever helping us with great reports

**Comment by snowtimeglass** [comment]
Thank you, too. 
@mikehardy @david-allison-1 
Thanks for the fix and the comment. I'm so glad.
This function is also very useful.
