### ISSUE TITLE
Ctrl+C opens the preview mode in 2.14.1

### ISSUE THREAD

**Issue by Nabokov86** [ankidroid/Anki-Android#7771]
I used to like to press Ctrl+C in the editor. But now something has changed, and I don't like it anymore.

Version 2.13.5 this keyboard shortcut only copies. In version 2.14.1 (possibly also 2.14), it opens the preview mode.

**Comment by david-allison-1** [comment]
@Nabokov86 Thanks for the report! Will be fixed in 2.14.2
