### ISSUE TITLE
Method in source code to bulk add notes?

### ISSUE THREAD

**Issue by dallonasnes** [ankidroid/Anki-Android#7779]
I'm toying with a custom feature and wondering if there is a good way to bulk add notes to my deck? I haven't come across a "bulk add notes" method in the source code. All I've seen is a way to add a single note to a deck.

Below is what I've put in thus far, although it has its problems -- primarily, it's really slow, and says "saving note" dozens of times (depending on the batch size). Wondering if anyone here can point me to a batch method, if it exists, or provide some guidance. I also wonder, if I'm adding notes in batch, if the launchCollectionTask still needs to run on the main thread?

For reference, the below block lives in `NoteEditor.java` on my branch.
```
          for (String s : notes){
                Note currentNote = mEditorNote.clone(); //unsure if I really need to clone this
                String newValue = convertToHtmlNewline(s);
                currentNote.values()[0] = newValue;
                // Save deck to model
                currentNote.model().put("did", getCol().getModels().current().getLong("did"));
                // Save tags to model
                currentNote.setTagsFromStr(tagsAsString(mSelectedTags));
                JSONArray tags = new JSONArray();
                for (String t : mSelectedTags) {
                    tags.put(t);
                }
                getCol().getModels().current().put("tags", tags);
                getCol().getModels().setChanged();
                mReloadRequired = true;
                CollectionTask.launchCollectionTask(ADD_NOTE, saveNoteHandler(), new TaskData(currentStringNote));
            }
```

**Comment by dallonasnes** [comment]
nevermind, I found a method shortly after opening this issue -- a `BulkInsert` in `CardContentProvider`

**Comment by mikehardy** [comment]
Yep, although worth noting that if you wanted to help the entire AnkiDroid community, you could take the existing CSV import work #6772 and move it forward, then you could just ask AnkiDroid to ingest your .csv...

**Comment by dallonasnes** [comment]
i'll have a look at that issue, thanks for pointing it out!
