### ISSUE TITLE
Improvements: Update 2.15: Check Pronunciation shortcut

### ISSUE THREAD

**Issue by MarkusJLechner** [ankidroid/Anki-Android#7780]
### Reproduction Steps: **Record not always works**
1. Press "Shift + V"
2. Release "Shift" before "V" triggers the play action

###### Expected Result
Recording is triggered, as intended to do so

###### Actual Result
Plays the recorded audio

(Maybe the listener sits on keyup?)

---

### Reproduction Steps: **Recording > Play / Play > Recording**
1] Press "Shift + V" (must release "shift" before "v", see previous issue reproduction)
2] While recording press "V"
  or
1] Press " V"
2] While playing press "Shift + V"

###### Expected Result
Current state is stopped and the desired state is triggered.

###### Actual Result
The previous state has to be stopped with the same keyboard shortcut before an different state can be activated.
eg. i have to press "Shift + V" again while recording to stop it, then its possible to press "V" for playing

---
### Improvement: **Keyboard layout**
**Description:** Because the phone is limited in display space it should have an different keyboard layout as the desktop version.

**Current situations:**
* Pressing an recording shortcut reduce screen content
* Record and Play should be easily accessible on the phone
* An shortcut for "Stop" as its not possible to start an recording from the start

**UX Solutions:**
* "V" show record buttons (+ resets current playing recorded audio) + start the recording
* "Shift + V" stops current playing and hiddes the buttons
* "B" plays/pause the recording
* "Shift + B" stops the playing

###### Reference
#7732 
#7733 
https://docs.ankiweb.net/#/studying?id=editing-and-more
Point **Record Own Voice**

Anki source code, record own voice
https://github.com/ankitects/anki/blob/98a4a1927a8e781a1c0b4a297caa8e86134ac027/qt/aqt/reviewer.py#L743-L744

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
I want to see this fixed before 2.15
