### ISSUE TITLE
Do not run CI for documentation-only changes

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#7787]
Hi @Ayusch, what are you trying to accomplish with these pull requests? They're expending our CI server resources, and seemingly for no benefit if you're just going to close the PR.

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/7786#issuecomment-735051016_

**Comment by darvesh** [comment]
I hope this will be helpful for the person working on this 

https://github.com/RReverser/react/blob/233af7e2dff4c79619f5cda6943388ff9e21581b/.travis.yml#L10

**Comment by mikehardy** [comment]
moved to github actions since Travis isn't allocating open source build minutes anymore in practice, CI is not running on doc changes anymore via path inclusion filters on the github action
