### ISSUE TITLE
[Bug] In languages other than English, the latter half of the gesture-triggered action menu causes malfunction

### ISSUE THREAD

**Issue by snowtimeglass** [ankidroid/Anki-Android#7793]
###### Reproduction Steps

1. In `Settings - AnkiDroid - Language`, select a language other than English, e.g. German, French, Japanese, Chinese simplified.

  Then, in the language, 

2. Select `Settings - Gestures - Enable gestures`.
3. Tap `Swipe up`.
4. Tap `Bury note` in the menu.

   * Strictly speaking, to make sure, tap the item whose string should correspond to `Bury note`.

       e.g. 
                Tap `Notiz aufschieben`
                Tap `Enterre la note`
                Tap `ノートを延期`
                Tap `隐藏笔记`

5. Swipe up on the study screen.

###### Expected Result

- The next card is displayed.

- Then, if you select `English` in `Language`, and re-open the `Swipe up` action menu, you see `Bury note` selected, of course.

###### Actual Result

- The learning is aborted, and the home screen (the Decks screen) is displayed.

- Then, if you select `English` in `Language`, and re-open the `Swipe up` action menu, you see `Abort learning` selected.

![image](https://user-images.githubusercontent.com/10436072/100534256-2f768100-3250-11eb-904e-bb05c41a3cb3.png)

###### Debug info

- Ver.2.14.0

- The upper 10 items in the menu (the items above the blue line in the following image) work properly.

![image](https://user-images.githubusercontent.com/10436072/100534168-36e95a80-324f-11eb-9bb2-c99a12faba78.png)

- In languages other than English and Japanese, the string which should correspond to `Card info` doesn't exist. 

    (In Japanese, it didn't either, but I added it on November 8. The Japanese string which should correspond to `Lookup expression` has gone missing instead.) 

- Instead of the string which should correspond to `Card info`, the string which should do to `Tag note` actually correspond to `Card info`. In other words, the translated string for `Tag note` has slid up to the position of `Card info`.

- This "sliding up by one step" continues until the item whose string should correspond to `Page Down`, i.e. until the third item from the bottom (the item on the green line in the image). 

- The second item from the bottom, whose string also correspond to  `Page Down`, works properly, or the item hasn't been translated (e.g. in German).

- This discordance has originally occurred on Crowdin for some reason.  

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Thanks for the report!

This is going to be a pain to solve. I'm happy to put in the manual work to solve this (if necessary), but would like to figure out the best course of action (and how to stop this happening going forwards)

----

Previously, adding an item into the list would remove the translations of all below it: https://github.com/ankidroid/Anki-Android/commit/fa47849bb4f7fa52c86d052cf75249c9382bd96e#diff-49528be50fa00f0ce3b79dff371ae6dc96ae75c363bb3c078998f131269f7091R53

This behaviour was changed in https://github.com/ankidroid/Anki-Android/pull/6979 , now adding a string to the middle of a `string-array` does not delete the strings which previously existed.


* "Card Info" was added at the middle of the list (I felt it made more sense here than appending it to the end of the list - the array handles both visual position and translation): 21a5e8530b57fb1d164fe54b34e7a519f779fdef
* When a translation sync occurred, if the strings matched, then Card Info was added in the correct place: https://github.com/ankidroid/Anki-Android/commit/3e379a151470d4bfb4f8425e7ba6669314602ab1#diff-cd9f44c092fcbab3a2acd71bcb4e97e5f81a9ff18af13b5bd3c4ddbaf1754fb0R53 ✔️ 
* If the Strings were already translated, then "Page Down" was duplicated and added to the end of the list, this ended up as an off-by-one error: https://github.com/ankidroid/Anki-Android/commit/3e379a151470d4bfb4f8425e7ba6669314602ab1#diff-49528be50fa00f0ce3b79dff371ae6dc96ae75c363bb3c078998f131269f7091R70 ⛔

Going forwards, I propose:

**Solving the issue**
* Determine affected languages ✔️ 
    * [ ] ar
    * [ ] be
    * [ ] cs
    * [ ] de 
    * [ ] eo
    * [ ] es-AR
    * [ ] es-ES
    * [ ] fa
    * [ ] fr 
    * [ ] hu
    * [ ] ind
    * [ ] it
    * [ ] ja
    * [ ] nl
    * [ ] pl
    * [ ] pt-BR
    * [ ] ru
    * [ ] sat
    * [ ] uk
    * [ ] zh-CN
    * [ ] zh-TW
* Determine how screenshots are affected ✔️ 
   * Screenshots are no longer associated with the correct strings ⚠️
* Determine strategy to fix languages ❓
   * Manually on CrowdIn?

**Future Proofing**
* Deprecate `11-arrays.xml`
   * Instead, use `@string` references: https://stackoverflow.com/a/4161645
   * Enforce via lint check

**Comment by david-allison-1** [comment]
Files used: #7796

Steps:

* Edit a translation file (11-arrays.xml)
* File - Upload Translations 
* Delete "Card Info" translation

I'll update my above post as files are handled.

Note: Czech was already fixed by our translator.

**Comment by david-allison-1** [comment]
Russian needs more work as many of the translations are approved

**Comment by david-allison-1** [comment]
Fixed Screenshots

**Comment by david-allison-1** [comment]
I've approved all my changes to Russian ✔️

**Comment by david-allison-1** [comment]
I believe this task is completed now. @mikehardy are we fine to run a translation sync?

**Comment by mikehardy** [comment]
If the state of `values/*xml` is good (it will go up and clobber existing values plus maybe cause changes to other languages if keys are added/removed) and crowdin values that will not have changes dependent on `values/*.xml` then yes

That's a very wishy-washy sounding answer, but I think you've done the needful for both?

And we've always got source control :-)

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/actions/runs/390222911

https://github.com/ankidroid/Anki-Android/compare/i18n_sync

Mistake with `eo`, but good aside from that

**Comment by snowtimeglass** [comment]
Thanks a lot for the arduous fixes!
