### ISSUE TITLE
Remove 11-arrays.xml string-array elements

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#7794]
Arrays are better used in `constants.xml` and referenced via `@string` to allow for changes in the order of the array

----

* Deprecate `11-arrays.xml`
   * Instead, use `@string` references: https://stackoverflow.com/a/4161645
       * How do we do this without trashing the existing translations? Doesn't seem easy in Android Studio
   * Enforce via lint check

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/7793#issuecomment-735378061_

-----

Follow up steps from #7800 :

* [x] Language sync
* [x] Copy from string-array to string for each language file

<details><summary>progress</summary>

**no action**

* [x] af
* [x] am
* [x] bn
* [x] ckb
* [x] da
* [x] fy
* [x] ga
* [x] got
* [x] gu
* [x] hr
* [x] hy
* [x] is
* [x] jv
* [x] ka
* [x] kk
* [x] km
* [x] ky
* [x] lv
* [x] mn
* [x] mr
* [x] my
* [x] nn (nnno)
* [x] pa (pain)
* [x] ro
* [x] sq
* [x] ss
* [x] sw
* [x] tg
* [x] tgl (tagalog: tl)
* [x] th
* [x] ti
* [x] tn
* [x] ts
* [x] tt (ttru)
* [x] ur (urpk)
* [x] uz
* [x] ve
* [x] wo
* [x] xh
* [x] yue (yu)
* [x] zu

**Action Needed**

* [x] ar
* [x] az
* [x] be
* [x] bg
* [x] ca
* [x] cs
* [x] de
* [x] el
* [x] eo
* [x] es-rAR
* [x] es-rES
* [x] et
* [x] eu
* [x] fa
* [x] fi
* [x] fil
* [x] fr
* [x] gl
* [x] heb
* [x] hi
* [x] hu
* [x] ind
* [x] it
* [x] ja
* [x] ko
* [x] ku
* [x] lt
* [x] mk
* [x] ms
* [x] nl
* [x] no
* [x] pl
* [x] pt-rBR
* [x] pt-rPT
* [x] ru
* [x] sat
* [x] sk
* [x] sl
* [x] sr
* [x] sv
* [x] ta
* [x] te
* [x] tr
* [x] uk
* [x] vi
* [x] zh-rCN
* [x] zh-rTW

</details>

* [x] Move gestures_labels to constants.xml

**Comment by david-allison-1** [comment]
Specifically for `gestures_labels`: the items which can't currently use `@string` (as there are no non-array strings defined) are:

```
        <item>No action</item>
        <item>Answer button 1</item>
        <item>Answer button 2</item>
        <item>Answer button 3</item>
        <item>Answer button 4</item>
        <item>Answer recommended (green)</item>
        <item>Answer better than recommended</item>
        <item>Tag note</item>
        <item>Lookup expression</item>
        <item>Play media</item>
        <item>Abort learning</item>
        <item>Toggle Red Flag</item>
        <item>Toggle Orange Flag</item>
        <item>Toggle Green Flag</item>
        <item>Toggle Blue Flag</item>
        <item>Remove Flag</item>
        <item>Page Up</item>
        <item>Page Down</item>
        <item>Abort Learning and Sync</item>
```

**Comment by david-allison-1** [comment]
Currently Copying Strings

Searches:
* "No"
* "Answer"
* "Tag"
* "Look"
* "Play"
* "Abort"
* "Flag" (flags)
* "Page"

**Comment by david-allison-1** [comment]
gestures_labels was the main issue and this has been resolved. Leaving the rest as low priority.

**Comment by TarekkMA** [comment]
So what is required to solve this issues is to extract all items from the 11 remaining arrays as strings in the same file `11-array.xml` and copy the array decleration to `constants.xml` making them refrence the string found in `11-array.xml` file. 

Is that right ?
