### ISSUE TITLE
Card Template Editor usability: Move editing of different sections to their own screens

### ISSUE THREAD

**Issue by javiercl2020** [ankidroid/Anki-Android#7798]
###### Reproduction Steps

1. Create new note 
2. Open editing section
3. Type in any section

###### Expected Result
Could be like the desktop version a separate window for the Styling, one for the front template and one for the back. 
See pictures below
![Screenshot 2020-11-03 160949](https://user-images.githubusercontent.com/73913963/100573229-f1ec1500-329c-11eb-8356-037e0256a0e7.jpg)
![Screenshot 2020-11-03 161009](https://user-images.githubusercontent.com/73913963/100573230-f284ab80-329c-11eb-8ac7-68623e2c7119.jpg)
![Screenshot 2020-11-03 160927](https://user-images.githubusercontent.com/73913963/100573231-f31d4200-329c-11eb-97bf-340c0d60fef9.jpg)

###### Actual Result
Styling Front and back templates are in same screen

###### Debug info
Ankidroid version 2.14.1
Android: 10
###### Research
*Enter an [x] character to confirm the points below:*

- 

> [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid

- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
This is a great place to track the general idea that the Note Editor screen has a serious usability issue in that the screen real estate for the edits is very very constrained. 

The front, styling, and back could all be separated I think. 

It is not a small project, but this is a heavily used screen and is probably worth the investment. It may take a while for anyone get to but we are not tracking it elsewhere, I will pin this one

**Comment by mikehardy** [comment]
@Akshay0701 fixed this in #8730! closing
