### ISSUE TITLE
Editing cards in preview mode modifies previewed cards

### ISSUE THREAD

**Issue by JSN7777777** [ankidroid/Anki-Android#7801]
###### Reproduction Steps

1. Seleccionar 2 o más tarjetas en el explorador de mazos.
2. Seleccionar vista previa.
3. Editar uno o más campos en la tarjeta seleccionada desde la vista previa.
4. Confirmar edición (✓).

###### Expected Result

Los cambios se guardan y la tarjeta editada debería aparecer con los cambios recien efectuados en vista previa.

###### Actual Result

Los cambios se guardan pero la aplicación reaparece en una tarjeta diferente o en el listado de exploración, y es necesario repetir el proceso para editar la siguiente tarjeta.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Mil gracias @JSN7777777 !

Tal vez sera chistoso para Ud pero por lo mejor, uso AnkiDroid como aprender español :-) entonces puedo usar este asunto para practicar para los otros mantenedores

Reproduction Steps
  
    Select 2 or more cards in the card browser
    Select preview
    Edit one or more fields in the selected card from preview
    Confirm the edit (hit the checkmark)

Expected Result

The changes should be saved and the edited card should appear in preview mode with the recent changes in effect

Actual Result

The changes are saved but the application shows a different card or the card browser list, and it's necessary to repeat the process to edit the next card


----

Note: this came in from a google play review, I believe @JSN7777777 is the same user and graciously took the time to log the issue

Cheers

**Comment by david-allison-1** [comment]
I've had a try at replicating this on 2.15alpha9 and wasn't able to.

This could theoretically be due to not refreshing handling two cards from the same note.

Would it be possible to have a video of the reproduction?

**Comment by JSN7777777** [comment]
Perdón, descubrí que sucede al entrar al explorador de mazos y cambiar
desde ahí el mazo a revisar antes del proceso.

Por ejemplo, estoy estudiando el mazo 1 y entro a explorar tarjetas, luego
desde ahí, cambio en la flecha superior, al mazo 2.

Y lego selecciono las tarjetas para editar desde la vista previa como
expliqué en la publicación...

Saludos

**Comment by david-allison-1** [comment]
Reproduced, will get on this in the next couple of days

**Comment by david-allison-1** [comment]
Reproducible in 2.13. Related: #7026

**Comment by david-allison-1** [comment]
Cause:

In the base class, we update the note

https://github.com/ankidroid/Anki-Android/blob/f50a1d001a7adeb7df3724ee283ea5a82cf69abd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1124-L1134

After handling this, we perform additional scheduler-related tasks, which are not relevant to the previewer

https://github.com/ankidroid/Anki-Android/blob/f50a1d001a7adeb7df3724ee283ea5a82cf69abd/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L528-L537

The card shown is from the scheduler, but moving forwards and back shows the correct card.

We can solve this by passing in `fromReviewer: false`: 

https://github.com/ankidroid/Anki-Android/blob/dbaf6549ec268333b20d160a0c40962d3135ba0d/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java#L571-L584
