### ISSUE TITLE
Update to ACRA 5.8.0 (new init style)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#7805]
Note this is required before updating to Android Gradle Plugin 5 - cf https://github.com/ACRA/acra/issues/810 where all the details on the "why" are laid out

https://github.com/ACRA/acra/releases/tag/acra-5.8.0-alpha1

The change should be a matter of bending the current ACRA init (done with annotations) to a Builder style

**Comment by mikehardy** [comment]
also very important to note that 5.8.0 is in *alpha* right now. This is tracking future necessary work, not urgent work that must be done immediately

**Comment by mikehardy** [comment]
ACRA 5.8.0 is in beta now, and it has the ability to access LimiterData to rate limit the help dialog send exception report feature.

Code snip from upstream to give us an idea how to do it:

https://github.com/ACRA/acra/issues/843#issuecomment-820784697


```java
long mostRecentTimestamp = LimiterData.load(this).getReportMetadata().stream()
    .filter(report -> report.getExceptionClass().equals(UserSubmittedException.class.getName()))
    .mapToLong(report -> report.getTimestamp().getTimeInMillis())
    .max().orElse(-1);
```


The reflective code and unchecked cast etc from #8629 should be removed during this upgrade

**Comment by jimrod942** [comment]
Hi @mikehardy, I'd like to work on this issue. I am new to Anki and open source contribution in general. Could you perhaps point me to any resources for this issue that may help? For example, I see where the ACRA init is done with annotations in AnkiDroidApp.java, but I am unsure what it means when you suggest to migrate the initialization to a "Builder style."

**Comment by mikehardy** [comment]
Hi 👋 😊
It means all if the config elemens we send in with those annotations will become I stead chained configuration method calls on the ACRA configuration builder. Do a quick search on fluent APIs and builders and that will explain the style. Look at the ACRA API now and the release notes for the version after ours and it should be clear I hope. Cheers

**Comment by mikehardy** [comment]
This one has a PR open and is just waiting on ACRA 5.9.x to be published, after my PR there to open up the custom dialog implementation was just merged
