### ISSUE TITLE
Images are not saved for future revisions 

### ISSUE THREAD

**Issue by yulo820324** [ankidroid/Anki-Android#7808]
###### Reproduction Steps

1. Hello everyone, I have the following problem, I created my own cards with images. 

2. at a certain time I go back to review my images they disappear (I synchronize) I save them on the server they are well re-used space. 

3.  I wanted to know how to get the images to stay  on the server and once you check that card, don't fear that you will be adding it again, it is very hard to do all that process again !!!  grateful from now on

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by yulo820324** [comment]
1. Hello everyone, I have the following problem, I created my own cards with images. 

2. at a certain time I go back to review my images they disappear (I synchronize) I save them on the server they are well re-used space. 

3.  I wanted to know how to get the images to stay  on the server and once you check that card, don't fear that you will be adding it again, it is very hard to do all that process again !!!  grateful from now on

**Comment by david-allison-1** [comment]
@yulo820324 Could you be a little more specific with the steps to reproduce the problem (ideally showing how a single image gets deleted)?

**Comment by yulo820324** [comment]
Very simple, I keep the images synchronized with the server until there, everything is ok, then in the next revision of the card, the image appears as if it is absent, it is only seen that there was once an image and if I am going to edit this source code of the same , but the image does not appear (now I don't have to print them all like that again), a small icone type box appears as if recognizing that there was ever an image there. Enviado do Email para Windows 10 De: David AllisonEnviado:terça-feira, 1 de dezembro de 2020 02:57Para: ankidroid/Anki-AndroidCc:yulo820324; MentionAssunto: Re: [ankidroid/Anki-Android] Images are not saved for future revisions (#7808) @yulo820324 Could you be a little more specific with the steps to reproduce the problem (ideally showing how a single image gets deleted)?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yulo820324** [comment]
Very simple, I keep the images synchronized with the server until there, everything is ok, then in the next revision of the card, the image appears as if it is absent, it is only seen that there was once an image and if I am going to edit this source code of the same , but the image does not appear (now I don't have to print them all like that again), a small icone type box appears as if recognizing that there was ever an image there.  Enviado do Email para Windows 10 De: David AllisonEnviado:terça-feira, 1 de dezembro de 2020 02:57Para: ankidroid/Anki-AndroidCc:yulo820324; MentionAssunto: Re: [ankidroid/Anki-Android] Images are not saved for future revisions (#7808) @yulo820324 Could you be a little more specific with the steps to reproduce the problem (ideally showing how a single image gets deleted)?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by yulo820324** [comment]
This is a last estable version 2.14.1 (see print atached)
And the other atached image shows the problem.

Em ter, 1 de dez de 2020 21:39, @YULO@ <yulo820324@gmail.com> escreveu:

**Comment by david-allison-1** [comment]
Hi yulo, I've tried:

* Adding an image
* Syncing
* Editing the note with the image
* Editing the image, then cancelling, then saving the note
* Syncing again

None of these have removed the image. Could you provide a series of steps which will cause the image to be removed?
