### ISSUE TITLE
When creating cards from highlighted text the text should default to the back field.

### ISSUE THREAD

**Issue by McSpooder** [ankidroid/Anki-Android#7809]
The functionality of creating a card from a highlight on Android is awesome. But I found that pasting the highlight into the front field is usually the undesired action. Most of the times I want to remember the text that is being highlighted and so I would usually make a card with a question prompting the for the highlighted text. Of course the question part goes in the front field. So what ends up happening is I then just cut the auto placed text from the front and paste it into the back field.

This is less of an issue but more of a suggestion. Does anyone else think this is a more intuitive way of doing this?

**Comment by voussoir** [comment]
Sounds like this depends on the field of study. For my foreign-language cards, I use this feature to take words out of books and I do want them to go to the primary field. This feature quickly became one of my favorite AnkiDroid updates.

I think the main challenge is that Anki cards are only required to have one field, and the rest are optional. Cloze cards for example can be made from notes with only the primary text field. The fields do not strictly correspond to front-back as you can design your cards however you like. So if AnkiDroid gained this option to "move highlighted text to second note field" it would have to fall back to the primary field when the note only has one field.

But I imagine the number of people using two-field front/back cards is high enough that this feature would be valuable. Just adding my perspective.
