### ISSUE TITLE
All local data has been lost since the last update

### ISSUE THREAD

**Issue by kunichik** [ankidroid/Anki-Android#7810]
###### Reproduction Steps

1. Open the app after update.
2. Close changelog dialog.

###### Expected Result
Open the last desc (local, not synced)

###### Actual Result
The desc browser was empty.

###### Debug info
AnkiDroid Version = 2.14.1

Android Version = 10

ACRA UUID = d242f514-0edb-4007-b034-2f1ddaaeddaa

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @kunichik,

I haven't heard of this happening (aside from SD Card issues - do you use one?). There are no bug reports in ACRA. 

We store all user data in the "AnkiDroid" folder of your phone, which contains 8 backups by default. We also store a full copy of your database on AnkiWeb if you use the sync functionality.

The following instructions should help you restore your collection: https://github.com/ankidroid/Anki-Android/wiki/FAQ#help-my-collection-is-corrupted

Please let me know if the above works, ensuring that the `AnkiDroid` folder is backed up before taking any action.

All the best,

David

**Comment by kunichik** [comment]
Hi David!
Thanks for reply!
I'm afraid that all the data have been lost since the last update.
There are only three commits that have been made after update:
![IMG_20201203_203911](https://user-images.githubusercontent.com/39728460/101073293-e3a53e00-35a7-11eb-9490-8e468b1b3bb3.jpg)

**Comment by kunichik** [comment]
> aside from SD Card issues - do you use on
No, I don't

**Comment by kunichik** [comment]
I've answered to all the questions and wait for next steps not using Anki all this time.
Please let me know if it is still possible to restore my local data if there are no archives in the backup folder as mentioned above ?

**Comment by mikehardy** [comment]
No, there is no magic. They are files on computers. If there are no files on the computer, and you have not done some backup somewhere (perhaps using syncopoli, or AnkiWeb) then I don't understand what we can do?

**Comment by kunichik** [comment]
> then I don't understand what we can do?
Sadly!
All the data have been lost after an update.
It would be nice if you ask the user before the update
and make some backups, logs etc.
Let me know if I can help you with it.

**Comment by mikehardy** [comment]
We take automatic backups **ever day**
We offer a free cloud sync service in AnkiWeb.
I really don't know what more we can do

**Comment by kunichik** [comment]
>We take automatic backups every day

What do you think,
why there was no backup 
after updating in the backup folder ?

In your opinion, this is normal
for the update process
erase all data?

**Comment by mikehardy** [comment]
I won't discuss this further, I'm sorry you lost your data but we have nearly 2MM devices now and the update process *in no way deletes data*

It is not normal. I do not know why you had no backups. Perhaps you had no space. Perhaps your device hardware failed.

Use syncopoli for local backups. Use AnkiWeb for cloud backup.

**Comment by kunichik** [comment]
>I won't discuss this further

me too.

>I'm sorry you lost your data 

thanks, have a nice eve.
