### ISSUE TITLE
Intermittent image flash in reviews?

### ISSUE THREAD

**Issue by adamwolf** [ankidroid/Anki-Android#7825]
Hi friends!

I got a new Pixel 4A, and noticed something.  I do not know if this is *actually* related to the new phone, or if it's always been there, or if it's new.

I can definitely work on debugging it myself, but I'd appreciate any pointers and I'd like to run it past you all in case it's obvious.

Today, during my review, I noticed that some of my cards had a weird flash during the render.  The flash was a larger version of the image on the card, offset, and it automatically rerendered really quickly.

After noticing it, I went back and tried the card again, and it was intermittent, happening maybe 20% of the time.  It may be time-related or cache related or something...

The cards I noticed it on were all generated via an image occlusion plugin on desktop, but these are the only cards where I have large images.

Have we seen anything like this before?  What's the next step for me? Turn on debug mode, hook up with Chromium on my machine, and see if I can reproduce it then?

###### Reproduction Steps

1. Go through a review

###### Expected Result

Each time Q or A loads, the images load at the appropriate size.

###### Actual Result

Sometimes, there's an extremely quick flash of the image, larger, and offset, before rendering to the appropriate size.

###### Debug info
AnkiDroid Version = 2.14.1

Android Version = 11

ACRA UUID = a85fdb0c-2dec-4556-a3c0-b31daabe7604

Scheduler = std2

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
I would debug via webview debugging yeah, this sounds like a reflow from an image where initial image display size isn't computed or something so raw image dimensions are used then later the view is constrained causing the reflow. And racy apparently! should be fun ;-)

**Comment by david-allison-1** [comment]
Possibly the `resizeImages` call

https://github.com/ankidroid/Anki-Android/blob/f50a1d001a7adeb7df3724ee283ea5a82cf69abd/AnkiDroid/src/main/assets/scripts/card.js#L171-L182

**Comment by adamwolf** [comment]
I should look at the card and make sure there isn't any funny Javascript in
it, too, I guess I didn't think about that!

**Comment by mikehardy** [comment]
Oh yeah! That was some code I think could be retired even. card.js has some dino-bits in it

**Comment by adamwolf** [comment]
it's still there.  i haven't yet been able to dig into it.

**Comment by adamwolf** [comment]
Hmm, I would have thought my comment would have made it not get closed?

**Comment by mikehardy** [comment]
That is strange, perhaps there was a race condition, and of course robots win those ;-)
More seriously - reopening

**Comment by david-allison-1** [comment]
@adamwolf Could you provide a deck export for a repro case?

**Comment by GitGondola** [comment]
I'm having the same issue.
I recorded it, made it into a gif and slowed it down to highlight what happens. (see attached pic)
In reality the image is the wrong size for 1 or 2 frames
It still happens with all the javascript stripped from my card templates.
![98842073](https://user-images.githubusercontent.com/68796479/116402846-3988c400-a870-11eb-8bab-826f3de57ea3.gif)

**Comment by mikehardy** [comment]
@GitGondola - are you able to build the app and load it on the phone to test changes? If so - if you removed that code from card.js above, I wonder if it would work correctly for you? Or perhaps it would be worse! But that's our hunch right now, to remove that code
