### ISSUE TITLE
Feature request: Text style bar support for night mode

### ISSUE THREAD

**Issue by Fullchee** [ankidroid/Anki-Android#7832]
![Screenshot_20201205-124328](https://user-images.githubusercontent.com/11246258/101259765-e82d3c00-36f8-11eb-81da-696ad1c05004.jpg)

###### Reproduction Steps

1. Turn on Night mode
2. Add a new card

###### Expected Result
The bar should turn dark

###### Actual Result
The bar is the same color as before (light grey)

###### Debug info
AnkiDroid Version = 2.14.2

Android Version = 8.0.0

ACRA UUID = f265de49-8f0f-4a43-8483-2270e10738cf

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

I'm not sure what the user forum is. Is it the subreddit?

**Comment by Fullchee** [comment]
I found the user forum and a similar issue

https://groups.google.com/g/anki-android/c/IGZ4wJn4pTY/m/T3rBFHb5AwAJ

Is it preferable to post in the Google Group forum or create GitHub issues?

**Comment by mikehardy** [comment]
Hi @Fullchee ! Thanks for reporting this. I think of the mailing list / forum as a place for user support and initial discussions, it is not a bad place to discuss things like this but when it comes to real bugs or tracking actual development effort? It is 100% here in github, so this is perfect, and I'm glad we have this in the tracker now

**Comment by Akshay0701** [comment]
I will to work on this issue .

**Comment by david-allison-1** [comment]
Just to note: `lily_123#0506` on Discord requested this issue, and Akshay was Ok with this. Assume it's assigned for a reasonable period of time

**Comment by prateek-singh-3212** [comment]
I would like to work on this issue.

**Comment by prateek-singh-3212** [comment]
Here is the screenshot of Light and dark mode respectively. Should I change the icons to white in dark mode?
![WhatsApp Image 2021-03-27 at 12 42 11](https://user-images.githubusercontent.com/76490368/112714609-082f7800-8f01-11eb-9c91-52f0b1a5db9b.jpeg)
![WhatsApp Image 2021-03-27 at 13 24 15(2)](https://user-images.githubusercontent.com/76490368/112714612-0960a500-8f01-11eb-9609-6e7729fb5e25.jpeg)

**Comment by david-allison-1** [comment]
I've messaged `lily_123#0506` about this, if I don't get a response within 48 hours, it's yours

**Comment by prateek-singh-3212** [comment]
Okay, no issues.

**Comment by david-allison-1** [comment]
All good to go, thanks for your patience

**Comment by prateek-singh-3212** [comment]
Here is the screenshot of light and black mode

![WhatsApp Image 2021-03-27 at 12 42 11](https://user-images.githubusercontent.com/76490368/112890305-58baf700-90f4-11eb-8469-c1a1e9dbaa77.jpeg)
![WhatsApp Image 2021-03-30 at 00 33 47](https://user-images.githubusercontent.com/76490368/112890276-4e98f880-90f4-11eb-96ca-319ec22d2a24.jpeg)

**Comment by david-allison-1** [comment]
@prateek-singh-3212 Sorry for the ambiguity, could you edit the main post of the PR and put them there.

Could you also show the plan/dark themes

* I think the white may be a little too bright, but best to wait to see what others think

**Comment by mikehardy** [comment]
Fix merged, will be released in the next 2.15alpha
