### ISSUE TITLE
[Feature Request] - Add setting option to choose "Default Whiteboard Pen Color"

### ISSUE THREAD

**Issue by hugomarins** [ankidroid/Anki-Android#7834]
Because of the background of my note types, I usually use the red pen color in the whiteboard. But every single time I start reviewing a deck, I have to choose the whiteboard pen color again, as the default blue has a bad contrast in my note types.

I think it would be very cool if a setting option was added to "Settings > Reviewing  > Whiteboard" section, so that another default pen color could be chosen. 

Another good solution would be the last chosen color be saved (& remembered) for the specific deck, just as enabling whiteboard currently is.

Thanks!

**Comment by david-allison-1** [comment]
Last color sounds good! Thanks for the suggestion!

**Comment by david-allison-1** [comment]
Related: #6550

**Comment by mikehardy** [comment]
won't be in a stable release for a few weeks but I'm merging the feature now and it will be in an alpha later today accessible with instructions here: https://docs.ankidroid.org/#betaTesting

**Comment by hugomarins** [comment]
Thanks @mikehardy, it is working perfectly!

**Comment by mikehardy** [comment]
@david-allison-1 --> 🏆
