### ISSUE TITLE
Feature request: render HTML character entities (such as &lt for < ) in the card browser

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#7838]
I thought I remembered seeing a GH issue a long time ago about rendering html in the card browser, but I can't find it now.
###### Reproduction Steps

1. Create notes with a field that contain the `<` character then the `>` character
2. replace those characters with `&lt` and `&gt` when you realize webview is trying to render contents of what it believes is an HTML element
3. Look at cards in card browser and see that &lt and &gt aren't rendered

###### Expected Result
&lt and &gt should be changed to < and >

###### Actual Result
&lt and &gt

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.14.1

Android Version = 7.0

ACRA UUID = 0417c1bf-8871-4e84-9233-cfea8e42b734

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
@sudomain I am 99.99% sure you know this and tried it with the `;`, but it is `&lt;` right, not `&lt` ?

**Comment by sudomain** [comment]
Lol that's embarassing. Sorry. 

Interestingly my incorrect `&lt` does render to < in the card previewer/reviewer.

**Comment by mikehardy** [comment]
That actually seems like a separate but maybe totally valid bug! 🤔
