### ISSUE TITLE
Passwords containing extended ascii characters may not work

### ISSUE THREAD

**Issue by thunderblood101** [ankidroid/Anki-Android#7839]
###### Reproduction Steps

1. Press the button in the top right corner for sync
2. Press login
3. Attempt to login with an account with a password containing extended ASCII characters, such as à, ø, ¶, etc. 

###### Expected Result

Normal login

###### Actual Result

Popup at the bottom, "invalid email address or password" 

###### Debug info
AnkiDroid Version = 2.14.1

Android Version = 10

ACRA UUID = 7eb55f5d-f09a-4bbf-9d66-e8147c7be127

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Interesting. Can you confirm these work if you just use Chrome directly to log in to AnkiWeb?

**Comment by JavaZauber** [comment]
I have experienced similar issues with `invalid email address or password`.

(Notice: all mentioned passwords are OLD passwords and are no longer related to my account)

My first password was `ú<gÄÜÃä]<uâD;®Ó+Ë>û{æmÆR`]¤;ÀT<¨Xö±ÖÏBGEîqXÉ§r¥ÍJpÈ6¹â7pÜyÆÁ`. AnkiWeb worked fine in the Browser. **AnkiDroid did not work.**  
Then I tried `Snc5o1qGCmSeR9ZphmvDbuDfrXEx7T3hDNQJm3pa`. **AnkiDroid did not work.**  
Then I tried `SfZWXWtGifDNFOuQqjDH`. **AnkiDroid did not work.**

I don't understand why AnkiDroid always displays `invalid email address or password`.
Please support unicode passwords in length of at least 64 chars or upwards

#### [NIST.SP.800-63b](https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf), Authenticator and Verifier Requirements

> Verifiers SHALL require subscriber-chosen memorized secrets to be at least 8 characters in length. Verifiers SHOULD permit subscriber-chosen memorized secrets at least 64 characters in length. All printing ASCII [RFC 20] characters as well as the space character SHOULD be acceptable in memorized secrets. Unicode [ISO/ISC 10646] characters SHOULD be accepted as well. [...]
> 
> Verifiers SHOULD NOT impose other composition rules (e.g., requiring mixtures of different character types or prohibiting consecutively repeated characters) for memorized secrets. Verifiers SHOULD NOT require memorized secrets to be changed arbitrarily (e.g., periodically). However, verifiers SHALL force a change if there is evidence of compromise of the authenticator.

**Comment by prateek-singh-3212** [comment]
@JavaZauber I am unable to reproduce the issue. I have tried all the passwords which you have mentioned above and all of them worked for me. I am not getting any errors.

**Comment by JavaZauber** [comment]
Thanks, @prateek-singh-3212. Okay then perhaps it's something else?
Does this feature require Google Play Services?

I am running Lineage OS Version `lineage_mata_userdebug 9 PQ3A.190801.002 6764d04004` without Google Play Services

**Comment by JavaZauber** [comment]
related: #8811

**Comment by mikehardy** [comment]
WIthout being able to reproduce we may only guess, which is inefficient unfortunately
It may simply be the most current version vs the current-released version - 2.15.0beta1 just came out and perhaps it is fixed there if you join the beta program and try? https://docs.ankidroid.org/manual.html#betaTesting

It should have nothing to do with Lineage or lack of play services.
