### ISSUE TITLE
Unit Test: Ensure that Deck Picker works without permissions

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7849]
Also needs a follow-up issue to get a unit test in, or a drive to get the instrumented tests working on a clean/safe collection

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/7846#issuecomment-741636510_

**Comment by shobhi1310** [comment]
Can I take this issue?

**Comment by david-allison-1** [comment]
Sure. Just to note: you've asked for a few, do ensure that you're going to get through them

**Comment by shobhi1310** [comment]
@david-allison-1 

I went through an earlier referenced issue #7846 which said that AnkiDroid could not be opened without permissions, and it got a PR on it #7847 which seems to resolve the crashing issue, but on my system when I am testing it without granting permissions, it is again reverting back to asking me for the permissions. This kindof makes it mandatory to grant permissions to files and folders on phone.

**Comment by david-allison-1** [comment]
Storage permissions are mandatory for the app to function at the moment.

The point of this issue is to ensure via automated testing that developers can't accidentally make changes which cause AnkiDroid to crash if it doesn't have storage permission.

**Comment by shobhi1310** [comment]
@david-allison-1 
I had one idea of writing a unit test for it. In the `DeckPickerTest.java` file, we can launch the DeckPicker class and assert if the value `REQUEST_STORAGE_PERMISSION` has been put to 1.

Is it correct?

**Comment by david-allison-1** [comment]
It sounds reasonable: the best way to test would be to break startup as it was done in the linked PR, write a test which fails, then fix the bug that you introduced and ensure that the test passes

**Comment by shobhi1310** [comment]
@david-allison-1 

I reverted back the PR #7847 and as expected the app would crash on startup. So the main issue is that the menu is getting initialized but it has no context of connection to DB because of no permissions. So the PR shifted 
```java
// Remove the filter - not necessary and search has other implications for new users.
menu.findItem(R.id.deck_picker_action_filter).setVisible(getCol().getDecks().count() >= 10);
```
this line inside the `colIsOpen()` scope which ensures that there is a connection to the DB. So, I will also put up a testing which ensures the same.

**Comment by shobhi1310** [comment]
@david-allison-1 

I tried to run unit tests `DeckPickerTest` as I wanted to put my custom test, but none of the previous tests are also running. What could be the reason?

I also tried it on other unit test case classes, and similarly none of the test cases passed.

![image](https://user-images.githubusercontent.com/42507632/113518371-8ea02580-95a3-11eb-9046-4026e90f0daf.png)

**Comment by david-allison-1** [comment]
* Could you ensure that you're on the latest version of master?
* If so, could you raise an issue

Please copy and paste, don't send screenshots of errors

**Comment by shobhi1310** [comment]
@david-allison-1 

Android Studio has support of JDK 8 as of now and that means it only has support till SDK 28. (SDK 29 and above require JDK 9)
Whereas the recent release of Roboelectric needs to run test using SDK 29 so that is what has caused the issue which has been mentioned in the reproducible error as shown below:

```
"D:\Android\Android Studio\jre\bin\java.exe" -ea -Didea.test.cyclic.buffer.size=1048576 "-javaagent:D:\Android\Android Studio\lib\idea_rt.jar=59850:D:\Android\Android Studio\bin" -Dfile.encoding=UTF-8 -classpath C:\Users\visha\AppData\Local\Temp\classpath1807349207.jar com.intellij.rt.junit.JUnitStarter -ideVersion5 -junit4 com.ichi2.anki.DeckPickerTest
[Robolectric] WARN: Android SDK 29 requires Java 9 (have Java 8). Tests won't be run on SDK 29 unless explicitly requested.
[Robolectric] WARN: Android SDK 30 requires Java 9 (have Java 8). Tests won't be run on SDK 30 unless explicitly requested.
Called loadFromPath(/system/framework/framework-res.apk, true); mode=binary sdk=28
```

One of the proposed solution which I got in [StackOverflow](https://stackoverflow.com/questions/58516687/how-to-add-java-9-to-android-studio) is:
```
@RunWith(AndroidJUnit4::class)
@Config(maxSdk = Build.VERSION_CODES.P, minSdk = Build.VERSION_CODES.P) // Value of Build.VERSION_CODES.P is 28
class TestClass {
...
}
```

**Comment by david-allison-1** [comment]
This shouldn't cause a problem:

https://github.com/ankidroid/Anki-Android/blob/8748835f1ee5f606bb86a962e1fa477d38858a24/AnkiDroid/src/test/resources/robolectric.properties#L3

**Comment by shobhi1310** [comment]
> Storage permissions are mandatory for the app to function at the moment.
> 
> The point of this issue is to ensure via automated testing that developers can't accidentally make changes which cause AnkiDroid to crash if it doesn't have storage permission.

@david-allison-1 

commit 732eb1a86096a9220a86a88f2bcec25bcaa76a63 seems to solve this issue as I have tested it now. Can you verify it once?

**Comment by david-allison-1** [comment]
Another test handling the specific regression would still be needed

**Comment by david-allison-1** [comment]
> I also tried it on other unit test case classes, and similarly none of the test cases passed.
> 
> [image](https://user-images.githubusercontent.com/42507632/113518371-8ea02580-95a3-11eb-9046-4026e90f0daf.png)

You need to install GCC for now

**Comment by shobhi1310** [comment]
> Another test handling the specific regression would still be needed

So, basically the test should be such that it tries to open the app without permissions to file storage and if check if the app crashes.

I also went through the PR #7847 and reverted back the changes made to check the issue of the app crashing and startup. So the test written should be able to fail it.

Just confirming from your side and for your comments
@david-allison-1

**Comment by david-allison-1** [comment]
> > Another test handling the specific regression would still be needed
> 
> So, basically the test should be such that it tries to open the app without permissions to file storage and if check if the app crashes (Deckpicker activity is the starting point).
> 
> I also went through the PR #7847 and reverted back the changes made to check the issue of the app crashing and startup. So the test written should be able to fail it.
> 
> Just confirming from your side and for your comments
> @david-allison-1

Yes, that's correct

**Comment by mikehardy** [comment]
This will no longer be needed in future versions because we're migrating to scoped storage
