### ISSUE TITLE
Alter Toolbar::getClozeIcon now that minSdkVersion is >=21

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#7851]
Yep - let's add a low priority issue for it,

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/7845#discussion_r539323952_

**Comment by abhinav700** [comment]
Hey is someone still working on this issue? I am new to open source and would like to start with this one

**Comment by david-allison-1** [comment]
sounds good to me
