### ISSUE TITLE
AnkiDroid preview for "basic and reverse" cards never shows the reverse version in preview mode, even when that's the version of the card you clicked on.

### ISSUE THREAD

**Issue by WraithGlade** [ankidroid/Anki-Android#7857]
###### Reproduction Steps

1. Open up a "basic and reverse" card list on AnkiDroid in the note browser. [Here's the deck I tested this on](https://ankiweb.net/shared/info/205388282), just in case the issue is more narrow than I realize, but I suspect it is a broadly applicable problem.
2. Find a pair of Front -> Back and Back -> Front cards in the list.
3. Click on each variant and in each case click the "preview" button on the top right of each card.
4. Notice how the Back -> Front case will never appear in preview, not even when you clicked on that version of the note.
5. Notice (in contrast), that the Desktop version of Anki never has this problem. The Desktop version always shows the different sided versions of the cards correctly in preview, unlike AnkiDroid.

###### Expected Result

When preview is used on card pairs, the Back -> Front version should appear different than Front -> Back in preview mode.

###### Actual Result

Both Back -> Front and Front -> Back versions of notes appear exactly the same when previewed on AnkiDroid. They both look like the Front -> Back version.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dnym** [comment]
My problem seems related: AnkiDroid seems uninterested in non-primary card types, in actual **review** mode. I made a copy of the basic front-and-back type, added 3 notes ("A / 1", "B / 2", "C / 3"), then added a secondary card template (Back -> Front). AnkiDroid only shows card type 1 in review. If I reposition the templates, then _only_ Back -> Front is shown.

**Comment by mikehardy** [comment]
I wonder if the cards are somehow assigned to different decks?

**Comment by Arthur-Milchior** [comment]
I can reproduce. I’ll take a look. Thanks for the report

**Comment by Arthur-Milchior** [comment]
I just made a pull request fixing it. Hopefully, it'll get corrected, but you'll need to be on alpha branch or to wait for next release I fear.

**Comment by mikehardy** [comment]
That was my bug from a while ago I think! Oof - thanks for fixing it @Arthur-Milchior 
I'll do another alpha tomorrow or next day - this is the only fix in it at the moment and I'd like to collect one or two more before a release, but not more than another day

Cheers

**Comment by david-allison-1** [comment]
Fixed in #7940
