### ISSUE TITLE
Updating to MathJax 3

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#7865]
Anki moved to MathJax 3, see https://changes.ankiweb.net/#/  ( thanks @andrewcrook  for the information)

I believe we should move to. They start to be faster, which will be a HUGE benefits, some card take more than a second to load on my phone due to mathjax. They also support the package physics, which was one of the things that forced me to still used LaTeX sometime.

I've not yet tried on anki, but I suspect that it means there are some formulas that will render on anki and not on ankidroid. 

The sad part is that, according to http://docs.mathjax.org/en/latest/upgrading/v2.html , the update is not trivial. I've not even find where is the mathjax file in our repo, so I've not tried yet. However, I suspect that we have a very basic usage, which ensure that it won't be that hard to update.

As a side note, if we can display mathjax only after rendering, that would be wonderful. That would probably ensure that the main card content could start loading first, without blocking for mathjax to be rendered

**Comment by mikehardy** [comment]
I believe that you will really appreciate the work here then 😁 #7782 from @hgiesel
