### ISSUE TITLE
Cards not showing options in quiz cards in macbook . https://ankiweb.net/shared/info/1888315035.The cards are not showing options

### ISSUE THREAD

**Issue by jyant99** [ankidroid/Anki-Android#7884]
https://ankiweb.net/shared/info/1888315035

The quiz card with options is not showing any options when using on macbook

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, is this for AnkiDroid or Anki Desktop?

These issues are for AnkiDroid only. 

You can find support for Anki Desktop here: https://forums.ankiweb.net/

All the best,

David
