### ISSUE TITLE
Ankidroid syncing far more media files than I actuially have

### ISSUE THREAD

**Issue by KublaiKhan64** [ankidroid/Anki-Android#7903]
On my amazon fire when I attempt to sync it keeps downloading media files when I only have 1800 cards with max a single image and audio file on the card. My last attempt to sync I stopped the sync at 33k media files downloaded (when my tablet informed me I had run out of available space) when I would assume the max I could possibly have is 3-4k media files.

###### Debug info
AnkiDroid Version = 2.14.2

Android Version = 5.1.1

ACRA UUID = a1bef49d-9a11-46de-aa7f-711a3c56ada7

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
FYI: answered here, check to see if this is resolved there

https://www.reddit.com/r/Anki/comments/kdp9v7/comment/gfxvngy

**Comment by KublaiKhan64** [comment]
> FYI: answered here, check to see if this is resolved there
> 
> https://www.reddit.com/r/Anki/comments/kdp9v7/comment/gfxvngy

Trying that now, that was actually my first idea after posting this issue, it's taking a while but I'll try again when it's done and get back to you
