### ISSUE TITLE
Speed Very Slow on MI 10 Android 11

### ISSUE THREAD

**Issue by AbdullahUQ** [ankidroid/Anki-Android#7905]
###### Reproduction Steps

1. Use cards normally, very slow pulling next card 
2.  Extrmely slow to update remaining reviews on main screen
3. Worst speed undoing last review

###### Expected Result

Very poor performance since last update

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @AbdullahUQ 

Thanks for the report. Could you upload a deck containing at least 10 cards which is slow?

This can be performed by long pressing a deck and selecting "export".

GitHub accepts `.zip| files, so zip or rename the `apkg`

Thanks

David

**Comment by AbdullahUQ** [comment]
Hello David,

Thank you for your email. So, I'm using the AnKing Step 1 deck, and I would
export it, but it's with every deck and it's specific to my android device.
On my laptop, iPhone, there's absolutely no issue.
This started specifically in the past 1 week after the Anki Update on
Google play and/or with my Android 11 update. I created a whole new deck
and imported one, and it was lagging in it as well.
It is unnaturally slow to go to the next card. Like the lag is 2-3 seconds,
which really is affecting the speed at which I'm doing my anki reviews.
Could you please help me out with this?
I'll be eternally grateful.

Thank you,
Abdullah

**Comment by david-allison-1** [comment]
Hi @AbdullahUQ,

Could you please provide a zipped sample so we can diagnose this?

Could you also download 2.13.5 from here and state if app speeds up? https://github.com/ankidroid/Anki-Android/releases/download/v2.13.5/AnkiDroid-2.13.5.parallel.A.apk

All the best,

David

**Comment by donglu** [comment]
The same problem.

**Comment by mikehardy** [comment]
@donglu please see the information and questions above, we have not received a response / information yet that allows us to fix it. Unfortunately "The same problem" does not advance the process of fixing it

**Comment by AbdullahUQ** [comment]
Hello,

It's not allowing me to export as a .zip but it did export it as a .apkg,
which I have attached to this email.

Regards,

Abdullah

**Comment by mikehardy** [comment]
Yes - it only exports .apkg, but those files are actually just '.zip' format files. The problem is that github won't accept .apkg files but it will accept .zip, so if you just change the extension to .zip then you can attach it. I don't think attachments will work over email? I think you need to use the github web UI to attach the .zip file. Thanks for helping!

**Comment by AbdullahUQ** [comment]
[Brosencephalon's Pre-Clinical Collection (v.1.5).zip](https://github.com/ankidroid/Anki-Android/files/5719788/Brosencephalon.s.Pre-Clinical.Collection.v.1.5.zip)

Okay perfect. I've uploaded it here on github. Just to add this is with every deck on my phone, this one was the fastest that could be exported so that's why I attached it.

**Comment by mikehardy** [comment]
Thank you! It *may* be that for the performance problem to show up we need the full collection and not just a single deck, but this gives us something to start with.

**Comment by Arthur-Milchior** [comment]
@AbdullahUQ and @donglu, can you please both give us the debug info, as explained in https://docs.ankidroid.org/help.html?

**Comment by Arthur-Milchior** [comment]
Are all of your card actually new ?
Because, the fact that some card may be in learning, or due later may affect the speed at which the next card is computed.


Are all cards slow, or only some of them ? If only some, can you also give us an example of a slow card

**Comment by Arthur-Milchior** [comment]
You didn't send any media in this zip file. Can you maybe send them?
It would be possible that big images make the collection slower, and we won't be able to reproduce without them

**Comment by bmcneil81** [comment]
I've been seeing the same issue on approximately the same timeline as other reports.  My debug info is below and my collection is attached.

AnkiDroid Version = 2.14.3

Android Version = 11

ACRA UUID = 6a261082-acf0-4a44-842e-4a6b7714406b

Scheduler = std

Crash Reports Enabled = true

Attachments area


[collection-20210116102244.zip](https://github.com/ankidroid/Anki-Android/files/5824881/collection-20210116102244.zip)

**Comment by david-allison-1** [comment]
@bmcneil81 

Thanks for the follow-up.

Could you try an earlier version of AnkiDroid (2.12.1 for example): https://github.com/ankidroid/Anki-Android/releases/tag/v2.12.1 and see if you can pinpoint the version where the slowdown occurred?

I have a feeling that this may be due to a WebView upgrade, but if using an earlier version shows an improvement, we can get it fixed.

**Comment by bmcneil81** [comment]
Hi David - thanks for the suggestion.  I will try to reproduce the bug with
earlier versions and see if I can identify where it begins.

**Comment by mikehardy** [comment]
This would still be good to investigate but we haven't had time yet, sorry - if you can report speed differences between your current AnkiDroid and a parallel install (from our releases page here) of a prior version that would help, otherwise it may sit
