### ISSUE TITLE
  Pronunciation problems in using ankidroid

### ISSUE THREAD

**Issue by liu-hz** [ankidroid/Anki-Android#7909]
###### Reproduction Steps
When using the pronunciation function of ankidroid deck, use a link in the label sound. When you click pronunciation, it will show that ankidroid failed to play. The link is as follows: what's the problem

[sound:http://dict.youdao.com/dictvoice?audio=slip&type=2]

**Comment by mikehardy** [comment]
Hi there!
We only support https for external resources (sounds or images). http will not work.
https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid
