### ISSUE TITLE
Card Browser: Drag to select many

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7910]
This enhancement was suggested in beta feedback. I really like the idea and feel it warrants further discussion

**Comment by mikehardy** [comment]
Has potential, problem is it mixes gesture idiom in the browser by adding time as an axis to the interaction? Drag is supposed to move the list, now it will ... select many if the user holds it? I'm not sure how that works.

I'm not a fan of the difficult discover of long-press to enter multi-select, maybe more than "select all" there could be a "show (or hide) select checkboxes" but the same gesture doing multiple things 🤔

**Comment by mikehardy** [comment]
I do see the review comment now - I guess if the default android file selection widget lets you do it, we could follow their lead to take advantage of their "user training"...

**Comment by david-allison-1** [comment]
My Android's file browser supports it by long pressing a checkbox and dragging down. 

This seems sensible, but scrolling does not occur if dragging to the bottom of the screen, which we might want to do. I'm not going to personally prioritise, but good first issue for someone looking to improve UX

**Comment by oakkitten** [comment]
another popular way is: while in selection mode (after long-pressing one item, with checkboxes visible), long press another item to select all items between the last selected item and the current one

my image app and file browser app implement both of these ways and it works pretty well i think

**Comment by mrudultora** [comment]
@david-allison-1 I want to work on it. What is the preferred choice here ? The one asked in beta feedback or the one suggested by oakkitten.

**Comment by david-allison-1** [comment]
Interestingly, GMail doesn't have this feature, which makes me pause and ask 'why', but both solutions seem good to me on the surface.

To be honest, whatever you feel would be more effective. I don't have a strong opinion. 

If oakkitten says that both work well in their apps, then I'd be happy with both. If you just want to pick one for now, and leave another for another issue, that'll also work.

**Comment by mrudultora** [comment]
@david-allison-1 Why we are still using listview ? I think moving to recyclerView has a potential to be opened as a new issue.

**Comment by david-allison-1** [comment]
> @david-allison-1 Why we are still using listview ? I think moving to recyclerView has a potential to be opened as a new issue.

Sure!
