### ISSUE TITLE
Correcting "The front of this card is blank."

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#7911]
###### Reproduction Steps

Create a card template 
```
{{^front}}
{{back}}
{{/front}}
```
and a card with "front" unfilled and "back" filled.
Preview it.

###### Expected Result
As in anki, this should shows the content of back.

###### Actual Result
The front of this card is blank.

###### Research

This was changed in 2.1.28 and we never ported it. It's complex to do a full "empty card" efficient, but that's still quite easy to implement this rule for a single note, even if this note have plenty of card. 
[example_reverse.apkg.zip](https://github.com/ankidroid/Anki-Android/files/5721453/example_reverse.apkg.zip)

**Comment by sakshi-1604** [comment]
working on it

**Comment by Arthur-Milchior** [comment]
@sakshi-1604 were you able to reproduce this bug?

I believe I already solved it and probably forgot to close the pull request. Really sorry about that.
If you can reproduce it, don't hesitate to ask for information, the process is not strainghtforward

**Comment by manasimallu** [comment]
can I take this issue?

**Comment by Arthur-Milchior** [comment]
@manasimallu Thanks for your interest.
Did you read the last post ?

I was asking @sakshi-1604 whether they could reproduce the bug. So first thing to do is to let us know if you can reproduce it or not. If you can reproduce it, then go for it. Otherwise, please let us know and close the bug

**Comment by sakshi-1604** [comment]
No I am not able to reproduce the bug.  This issue is already solved.

**Comment by Arthur-Milchior** [comment]
Thanks a lot for the report @sakshi-1604
