### ISSUE TITLE
MathJax advanced features no longer work after switch to SVG

### ISSUE THREAD

**Issue by hgiesel** [ankidroid/Anki-Android#7915]
After switching to MathJax SVG output, several advanced features don't work anymore:

```
\( \color{blue}{test} \)
```

This should trigger an automatic import of the MathJax "color" library, which then is applied to the "test". This worked before switching to SVG, it works on Anki itself, but now it doesn't work anymore in Android.

On every rendering, MathJax spits out a new error to the WebView console,  cannot find `xArrow` on undefined within the `mchem` library (weirdly enough):

> mhchem.js:1 Uncaught TypeError: Cannot read property 'xArrow' of undefined
    at Object.<anonymous> (mhchem.js:1)
    at a (mhchem.js:1)
    at Module.<anonymous> (mhchem.js:1)
    at a (mhchem.js:1)
    at mhchem.js:1
    at mhchem.js:1

###### Reproduction Steps

1. Put in `\( \color{blue}{test} \)` into a card
2. Try rendering the card
3. Inspect the WebView console through Chrome inspector

###### Expected Result

<img width="100" alt="Screenshot 2020-12-20 at 02 15 55" src="https://user-images.githubusercontent.com/7188844/102702973-4ca7d980-4269-11eb-93e1-d20d7b75227d.png">

###### Actual Result

<img width="135" alt="Screenshot 2020-12-20 at 02 39 29" src="https://user-images.githubusercontent.com/7188844/102703234-9b0aa780-426c-11eb-8bb2-412c94e35a24.png">

###### Debug info
AnkiDroid Version = 2.15alpha16
Android Version = 11
ACRA UUID = 220a752a-acec-4b5e-b025-5c6b30202ae6
Scheduler = std2
Crash Reports Enabled = false

**Comment by mikehardy** [comment]
Interesting - so we have the first hiccup in the attempted switch

this smells like a simple failure to include all the necessary libraries but internet search turned up no promising hits

this will be the problem with not sticking to the same bundle of mathjax that upstream (ankidesktop) uses as now we're responsible for sussing out our own correct (and ecosystem compatible) mathjax packaging

if we can't do that quickly, we'll need to revert 

Related info:

http://docs.mathjax.org/en/latest/input/tex/extensions/color.html

> This extension is loaded automatically when the autoload extension is used
> Alternatively, use \require{color} 

@hgiesel have you tried explicitly loading it? that might suss out whether it is included or not, or whether autoload is off or not as 2 likely candidates for the issue

**Comment by hgiesel** [comment]
I just tried an explicit `\require{color}` before using the color library, but it didn't change the error. Just to be clear, the `mchem` exception is thrown every time you use MathJax, regardless of using libraries or not. I guess I could have turned this into two to issues, however the issues seem very much related.

**Comment by mikehardy** [comment]
This seems like the perfect time to fire up WebView debugging - it will let you inspect the object in the DOM of the live WebView running on the emulator, it's kind of fantastic for this work, as once you locate the undefined object being dereferenced it should be easy to see what library chunk is missing, I hope

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#via-chrome-development-tools

**Comment by Arthur-Milchior** [comment]
> if we can't do that quickly, we'll need to revert

Do you mean to revert to 2 (which upstream does not use anymore), or to a non-svg Mathjax 3 version?

**Comment by mikehardy** [comment]
mathjax 3 is here to say, I mean revert the CHTML -> SVG switch. In my mind, that is speculative, we are attempting it but it shouldn't throw errors in javascript console immediately, and it must be anki ecosystem compatible with it's supported modules / features.

**Comment by mikehardy** [comment]
@infinyte7 here is the issue where the xArrow undefined error was mentioned by @hgiesel - I think it is unrelated to the CHTML/SVG switch we tentatively implemented so it might pay to peel it off to a separate issue for independent triage/fix

**Comment by infinyte7** [comment]
Thanks, I was debugging webview and getting those errors.

**Comment by mikehardy** [comment]
So, what's the consensus here? I haven't seen any progress and we have a regression so I'm thinking we need to revert the switch to SVG, that is we need to render CHTML again and accept whatever rendering errors we have with that for now

**Comment by mikehardy** [comment]
To be specific, that's #7906 and I would do a git revert of those 2 commits

**Comment by hgiesel** [comment]
I'm inclined to agree here. I did have a look into this, but in the end, I'm not sure it's worth the effort, also considering that it'll mean diverging from upstream Anki.

**Comment by mikehardy** [comment]
Great, that's at least 2 of us out of 3 ;-), I'll make a PR with the reverts and see how it goes. Thanks for the thought-review @hgiesel
