### ISSUE TITLE
Ankidroid word wrapping issue

### ISSUE THREAD

**Issue by hea7en2** [ankidroid/Anki-Android#7919]
###### Reproduction Steps

     Enter all English letters in the question or answer box, a long string of letters
     When using this card to display, the letters will not automatically wrap when they are too long, and they will always be displayed in a straight line beyond the border, unless you manually add spaces or wrap the lines
     The overall style of the page will also be affected by this
     If it is all entered in Chinese, the system will automatically wrap when it is too long. I hope that it will wrap automatically when entering English.

###### Expected Result

When all English letters are entered, they should be super long and will automatically wrap after reaching the frame position. Hope to fix it!

###### Actual Result

After entering all English letters, they will not automatically wrap after they are too long, and they will be displayed beyond the border.

###### Debug info

AnkiDroid Version = 2.15alpha4

Android Version = 10

ACRA UUID = cfa90515-e628-4e81-b5a1-cff6c2301bb4

Scheduler = std
 @![123](https://user-images.githubusercontent.com/46583161/102705630-9bcf2800-42c4-11eb-9647-6e1bc8db1ba6.jpg)

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hello!

With apologies, we collaborate in English. We are interested in collaborating with anyone and of course we provide translations for lots of languages but development is in English. I have used google translate to translate your issue, but I ask that you do so in the future for issues and comments

For your issue, can you verify this happens with the most recent alpha? We are on 2.15alpha16 now https://github.com/ankidroid/Anki-Android/releases

Can you change the screenshot to show the full card?

Also, this may be related: https://github.com/ankidroid/Anki-Android/pull/7455

**Comment by hea7en2** [comment]
I tested it on the latest version 2.15Alpha18, and I still have this problem. At present, I have added "overflow-wrap:break-word;" to the card style css to solve this problem, but I still hope to be able to use the AnkiDroid app This problem is handled internally! Thank you!
![aaa](https://user-images.githubusercontent.com/46583161/102856597-be4a7800-4461-11eb-9d50-db3317225571.jpg)

**Comment by hea7en2** [comment]
> 我在最新版本 2.15Alpha18 上对其进行了测试，但仍然存在此问题。 目前，我添加了 “overflow-wrap：break-word;”。 卡片样式的 CSS 来解决此问题，但我仍然希望能够使用 AnkiDroid 应用程序。此问题在内部处理！ 谢谢！
> ![aa](https://user-images.githubusercontent.com/46583161/102856597-be4a7800-4461-11eb-9d50-db3317225571.jpg)

**Comment by hea7en2** [comment]
> 你好！
> 
> 抱歉，我们使用英语进行合作。 我们有兴趣与任何人合作，我们当然会提供多种语言的翻译，但是开发是用英语进行的。 我已经使用 google translation 来翻译您的问题，但请您日后这样做以获取问题和评论
> 
> 对于您的问题，您可以验证最新的 Alpha 版是否会发生这种情况吗？ 我们现在在 2.15alpha16 上 [ https://github.com/ankidroid/Anki-Android/releases](https://github.com/ankidroid/Anki-Android/releases)
> 
> 您可以更改屏幕快照以显示完整卡吗？
> 
> 另外，这可能与以下问题有关：[＃7455](https://github.com/ankidroid/Anki-Android/pull/7455)

我在最新版本 2.15Alpha18 上对其进行了测试，但仍然存在此问题。 目前，我添加了 “overflow-wrap：break-word;”。 卡片样式的 CSS 来解决此问题，但我仍然希望能够使用 AnkiDroid 应用程序。此问题在内部处理！ 谢谢！

**Comment by mikehardy** [comment]
Ah ha! Then it looks like we have a potential solution as well (adding overflow-wrap:break-word to the css)

I'll mark this as a great fix for someone getting started in the project to pick up

Thanks for your research and testing here, I appreciate it!
