### ISSUE TITLE
AnkiDroid does not bundle JQuery, while AnkiWeb/AnkiMobile do

### ISSUE THREAD

**Issue by hea7en2** [ankidroid/Anki-Android#7920]
###### Reproduction Steps

1. Ankidroid未自带JQuery.js，PC端Anki中有自带JQuery.js
2. Ankidroid中无法手动引入外部js文件，使用如下语法无效： <script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
3. Ankidroid只能使用最最原生的js语法，想实现想要的页面效果或功能非常麻烦，希望能手动引入外部js文件实现

###### Expected Result
1.希望Ankidroid中能自带JQuery.js语法
2.希望 Ankidroid中可以实现手动引入外部js文件，能使用更多的语法实现更多的功能

###### Actual Result

Ankidroid中无法手动引入外部js文件，使用如下语法无效： <script type="text/javascript" src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>

###### Debug info

AnkiDroid Version = 2.15alpha4

Android Version = 10

ACRA UUID = cfa90515-e628-4e81-b5a1-cff6c2301bb4

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
We will not bundle third party libraries that are not also bundled in Anki Desktop.
If you want jQuery, you will have to put it in your own collection and reference it, or reference it from the internet but via https (not http)

Possibly related #7764 - experimental import support for JS files, which should merge and release as a new alpha today

**Comment by david-allison-1** [comment]
Hi, AnkiDroid doesn't support `http` due to Android platform restrictions. Please use `https`. 

Thanks!

**Comment by hgiesel** [comment]
> We will not bundle third party libraries that are not also bundled in Anki Desktop.

I actually intended to ask you this, but Anki **does** provide jQuery, and so does AnkiMobile on iOS, as well as AnkiWeb. On Anki, it is currently in version 1.12.4, on AnkiMobile, it is on 2.2.2, on AnkiWeb it is on 3.5.1 (newest version, non-slim version). Gotta love the version spread :)

AnkiDroid is the only platform that does not provide jQuery.

**Comment by mikehardy** [comment]
@hgiesel shows how much I know about the current javascript packages in Anki :facepalm: 

The converse of my statement is also true, and relevant here: we should bundle all javascript libraries that AnkiMobile/AnkiWeb bundle, usable in an identical way (if at all possible)

So @hea7en2 this is worth reopening, to track any future addition of jquery

**Comment by hea7en2** [comment]
谢谢回复！我会持续关注的，辛苦了！
