### ISSUE TITLE
After switch the language in general setting, the words are not fully translated until the app is reopened

### ISSUE THREAD

**Issue by Sunt-ing** [ankidroid/Anki-Android#7921]
###### Reproduction Steps

1. Install the app.
2. Switch the language to Chinese in the general setting.
3. Click "检查数据"("Check database"), find that the language used in the checkbox is English.
4. Kill the app, reopen it, and click "检查数据"("Check database") again, find that the words are all in Chinese now.

###### Expected Result
After switching the language to Chinese, all words should be in Chinese if they have a Chinese version.

###### Actual Result
Only part of the words is in Chinese until the app is killed and reopened.

###### Debug Info
AnkiDroid Version = 2.14alpha18
Android Version = 9
![ankidroid_inconsistency](https://user-images.githubusercontent.com/43040147/102708306-012f1300-42dd-11eb-8a7c-9a241345c48a.gif)

https://user-images.githubusercontent.com/43040147/102706017-ff5b5480-42c8-11eb-8e02-b94899bdbc4f.mp4

**Comment by mikehardy** [comment]
Hi there! This is a pretty difficult area

I wonder if the String resource manager is stale from the ApplicationContext for those strings, while the ActivityContext works, and we could either change which context we use or we could also update the ApplicationContext?

https://github.com/zeugma-solutions/locale-helper-android/issues/1
