### ISSUE TITLE
Highlight default selection in pickers

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#7931]
In note editor, there is a selector to change the card's deck. I believe the current deck should be highlighted, so that if you changed the deck by accident you can easily come back to it without loosing all other change you made to the card. The same thing should be good for the card type

The same change should probably also occur on other list selector, but I've not found other example where it would be so useful.

**Comment by Abanoub-Asaad** [comment]
I'm working on it.

**Comment by Ekagra** [comment]
I'm working on it

**Comment by bishalbar77** [comment]
Can I work on it?

**Comment by david-allison-1** [comment]
@bishalbar77, there's already a pull request in to fix this: #8174, it'd be better to find an issue that isn't being worked on
