### ISSUE TITLE
"Manage note type" is uselessly slow

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#7937]
**Is your feature request related to a problem? Please describe.**
"Manage note type" is extremely slow. That should not be the case given that it only show a list of note type.

**Describe the solution you'd like**
That it loads immediately, even if with less data (e.g. loading without the number of note of each type is still useful)

(I'd expect to give it as a task for someone to show how background process work)

**Comment by mikehardy** [comment]
Not disagreeing, but I will say that this screen is used almost never according to analytics. It is *vital* when it is used, just that it's use is very very infrequent.

**Comment by ritvij14** [comment]
@Arthur-Milchior is there some way to reproduce this? Because on my device it doesn't slow down at all. :thinking:

**Comment by Arthur-Milchior** [comment]
@ritvij14 If you download my collection http://milchior.fr/anki/ then it should be slow. It really requires a huge collection with plenty of note type and plenty of cards

Warning: depending on culture, it may contains cards that may be considered as NSFW

**Comment by bhatushar** [comment]
@Arthur-Milchior I imported your collection but "Manage note types" is still loading at normal speed. I tested it on an emulated device (Android 10, API 29). Is this issue fixed?

**Comment by Arthur-Milchior** [comment]
I can't reproduce either and honestly I don't know why. I assume something else was changed but I don't know what. I guess it's worth closing it now.
Still be curious to reproduce with december version to check if I can reproduce.
