### ISSUE TITLE
Card browser: Add Option to limit to one card per note

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#7939]
When you are looking for a specific note to correct, or to get information, seeing all cards is totally useless. This get worse because the screen is small, and some note may be repeated once by cloze or once by card, and there may be a lot of siblings.

So, I really would appreciate a way to limit one card by note in the browser.

I believe it may be a good first issue, because findNotes already exists in the database.  This means that this require to add an option and to change findCard to find note. There is no need to an actual find card window, the find note is totally sufficient.

**Comment by david-allison-1** [comment]
I remember a discussion on Discord/Reddit a couple days ago asking about why cards weren't being suspended, and it turned out that it was due to an addon with this functionality. I think there's likely a lot of hidden gotchas with this when implemented with the batch editing functionality.

**Comment by Arthur-Milchior** [comment]
I assume you're referring to my add-on is https://ankiweb.net/shared/info/797076357
The problem was considered in august, and I added an option so that in note mode, all actions such as suspend are done on all cards of the note and not only on the shown card. I don't recall getting any complaints since, but it seems too rare that the people having an add-on trouble actually report the problem to a place where I can be notified

There is at least one easy solution for ankidroid: we can just deactivate all functionality related to cards when in note mode. I assume it will remains deletion, copy and marked, but it should be checked once this feature gets implemented

**Comment by kartikeysaran** [comment]
Can i work on this issue if this is open !

**Comment by Arthur-Milchior** [comment]
@kartikeysaran : I'd love too :D

**Comment by IAmJaishree** [comment]
@kartikeysaran are you working on this?

**Comment by kartikeysaran** [comment]
> @kartikeysaran are you working on this?

Yes I am

**Comment by david-allison-1** [comment]
How does Anki Desktop implement this functionality?

**Comment by kartikeysaran** [comment]
> How does Anki Desktop implement this functionality?

I think this would be very easy to implement in Anki-Desktop as well , when finished with this will love to work on that too

**Comment by david-allison-1** [comment]
What's the plan for keeping this feature in 2.16 when we remove most of `libAnki`? `Distinct by nid` on the client side?

**Comment by Arthur-Milchior** [comment]
Anki have a very different browser. On my screen, I can see 50 lines at once, or 20 lines with fields. It also allows to show the card name AND the card sort field AND plenty of other information. So, as I argued in the first message, our UI need to be more efficient than upstream UI. When space is a premium, it becomes less acceptable to duplicate informations if user don't want it.

It should be done correctly indeed, so that there is no doubt about what is being done. E.g. you don't want user to think they are suspending a whole note while they are suspending a single card, nor the inverse.

This feature is available in https://ankiweb.net/shared/info/797076357 since august. It used to be available in Advanced Browser, but we decided to split both features due to change in the browser code. Sadly, the port to rust made it inefficient and I opened today https://github.com/ankitects/anki/pull/1098 to try to make it efficient again. I admit I didn't thought about the question of porting to rust, but if DAE accept it, it would solve this last issue.

**Comment by david-allison-1** [comment]
I'm asking from an implementation perspective, how are we going to model this feature with the new search syntax which won't allow us to modify `libanki`: https://github.com/ankitects/anki/blob/5160d0c418fd39b3a74dfd9d32aa3258913bf067/rslib/backend.proto#L843-L907

\* Technically, we'll be using the following for 2.16, but same result:

https://github.com/david-allison-1/Anki-Android-Backend/blob/3625800da95a75d62320cee6d25a64cf7d2e1bb6/tools/protoc-gen/test/backend.proto#L89

**Comment by Arthur-Milchior** [comment]
I just gave you the link to a PR I made in Anki that would allow to do a search with one card by note. I'll wait to see dae's answer

**Comment by Arthur-Milchior** [comment]
Actually, my PR seems to be rejected. Because someone already added the feature, even adding a UI button for it. See https://github.com/ankitects/anki/pull/1100 and https://github.com/ankitects/anki/pull/1033 (Note that the PR is marked as rejected. Actually, the code is merged, but for a reason I don't really understand DAE don't use GithHub to add come to main branch )

**Comment by Arthur-Milchior** [comment]
If you run anki from source, you'll have this option available. It's not yet available from mainstream, I suppose it's not 100 stable yet.

**Comment by Arthur-Milchior** [comment]
> Can be implemented via col.newBackend.backend.browserRowForId()

Ping @viciousAegis
