### ISSUE TITLE
[Bug] Scheduler v2: Daily Card refresh does not line up with "Start of next day"

### ISSUE THREAD

**Issue by FrostKiwi** [ankidroid/Anki-Android#7945]
AnkiDroid's environment:
I recently switched to the scheduler V2 and my "Start of next day" is set to the default 4 AM. Lastly, I changed my Phone's language to not line up with my locale. Local time is CET, but the language of the Phone is set to Japanese, which corresponds to JST. The following issue is possibly caused by Scheduler v2 defaulting to UTC, because it is confused by the mishmash of locales and timezones.

I was lazy and did not do my daily cards until one hour before 4 AM. 
Unusually, I was presented with both the reviews and new cards of the next day at 3AM, instead of the normal 4AM. The exact minute the clock hit 3AM, I was hit with the reviews for the next day. I have 20 new cards and ~140 reviews a day. But suddenly at 3AM it jumped to 40 new cards and ~250 reviews.
I did exactly half of what I was given. This is shown in the stats, as me doing twice as many new cards in one day, as compared to other days and the following day doing almost no new cards at all.
And lastly, since mistakes / again reviews come last, There are no mistakes on that day and twice as many on the next one.
Theory: Scheduler V2 accidently updated based on UTC, instead of local time. It just so happens, that 4AM local time is 3AM UTC. Maybe AnkiDroid's Scheduler V2 accidently get's confused by locale and defaults to UTC?
![JArhJtk](https://user-images.githubusercontent.com/60887273/102885664-082c6180-4454-11eb-8981-4af3a7a657c3.png)

###### Reproduction Steps

Not quite sure what's the cause, but in my case: Wait until one hour before "Start of next day" and observe cards getting added.

###### Expected Result

Card refresh should line up with the "Start of next day" time

###### Debug info
AnkiDroid Version = 2.14.2

Android Version = 10

ACRA UUID = 6c373a16-d4cb-47de-895b-78f7a019a8e2

Scheduler = std2

Crash Reports Enabled = true

###### Research
- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there, if I'm not mistaken this is a dupe of #6203 - which unfortunately means you've walked in to a huge but quiet project we are working on to port AnkiDroid over to the new Rust-language implementation of libanki from upstream Anki Desktop #5805 which is close to landing but might be a little while (thus the unfortunate part - this will only close when that is done as we intend to rely on the new Rust libanki to handle timezone / start of next day etc)

Does that linked issue seem like the same thing?

**Comment by FrostKiwi** [comment]
@mikehardy 
https://github.com/ankidroid/Anki-Android/issues/6203 seems to be similar. Though it is surprising, how in my case it is by default already wrong, updating at 3AM. Tonight I changed system language to English again and checked at 3AM, same reviews update happening an hour early.
Either way the gist is the same: Scheduler v2 not honoring Start of the day, so I'll close this to avoid dupes.
