### ISSUE TITLE
[Bug] The number of reviews is different inside and outside the deck

### ISSUE THREAD

**Issue by tobia** [ankidroid/Anki-Android#7946]
###### Reproduction Steps

1. Load or inspect [this export file](https://mega.nz/file/SQNBwS5B#XxN5ogXs0z_OmJXy2vFVj65JvGOJd0z2EFwz4FOlUgU) (I hope that's enough to reproduce the issue)

###### Expected Result

The number of wrong cards (red number) should be the same in the main screen and during reviews. In this case the correct number is 3.

###### Actual Result

The main screen shows 3, but if you open the deck it says 42. 

![Screenshot_20201221-101540__01](https://user-images.githubusercontent.com/48756/102890219-5e050780-445c-11eb-8838-e77056d8ecd8.jpg)

![Screenshot_20201221-101546__01](https://user-images.githubusercontent.com/48756/102890234-63625200-445c-11eb-8dfb-8b8cd639e828.jpg)

###### Debug info

AnkiDroid Version = 2.14.2

Android Version = 10

ACRA UUID = 89032829-485f-4afd-a966-61ad635fd68c

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
Hi,

Thanks for reporting this bug.
This is not actually a bug, but a really bad user interface. Those two numbers are reporting different but related things. 
In the main screen, it states that there are three cards that you can review now. In the reviewer, the second screen, this mean that there is 42 repetition of cards in learning you'll have to do today. It also counts the cards that are due in ten minutes, or in an hour.
This is one place where I believe we should not follow upstream, as it's confusing. Sadly, that's not my decision to take.

**Comment by tobia** [comment]
Oh, wow. I would have never guessed.

I would certainly prefer either a default or an option to see the actual number of remaining cards, like the other 2 numbers seem to show.

**Comment by mikehardy** [comment]
If you want to pursue it upstream https://forums.ankiweb.net/ we may be able to get this fixed ecosystem wide

**Comment by Arthur-Milchior** [comment]
It's almost impossible to guess unless you spent far too much time reading the details of the way those numbers are computed. It's only because you're not the first to report it that I could answer quickly.

I won't pursue it upstream personally. I expect users request to bear more weight than contributors remark, and I'm no longer an average user I think

**Comment by tobia** [comment]
> *It's almost impossible to guess unless you spent far too much time reading the details of the way those numbers are computed.*

Based on this, I would ask for it to be fixed here, independently of upstream. Current behavior makes no sense, is obscure, and serves no purpose.

The numbers that I, as a user, would like to have on top during a study session are:

1. 🔵 the number of cards in the current deck that are scheduled for *learning* in the current session
2. 🔴 the number of **cards** in the current deck (not repetitions) that are scheduled for *re-learning* in the current session
3. 🟢 the number of cards in the current deck that are scheduled for *review* in the current session.

**Comment by mikehardy** [comment]
We will not deviate from upstream
