### ISSUE TITLE
Deck Picker: Add "Add Cards" item to "This deck is empty" snackbar

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7948]
Debatable design decision, but I'm for it. I feel it warrants a small design discussion before implementation.

**Is your feature request related to a problem? Please describe.**
When an empty deck is selected, a snackbar is displayed. The "Help" link links to https://docs.ankidroid.org/manual.html#gettingStarted, which is questionably useful, most users will want to be guided to the "Add" action

![image](https://user-images.githubusercontent.com/62114487/102929942-6a588700-4493-11eb-971e-2864245afb2c.png)

**Describe the solution you'd like**
Convert this to a dialog box stating this, and offering the user a chance to "add (cards/notes)" as the primary action.

**Describe alternatives you've considered**
Adding a second action to the snackbar is questionable by google guidelines

> A snackbar can contain a single action. "Dismiss" or "cancel" actions are optional.

https://material.io/components/snackbars

**Comment by Arthur-Milchior** [comment]
I agree that a button "Add a card" opening add card with this deck selected would be better

**Comment by mikehardy** [comment]
I would just switch "Help" to "Add Card" personally
