### ISSUE TITLE
[Bug] List of saved search fail to synchronize from AnkiDroid to Anki

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#7949]
Hi,

This bug is crossposted between AnkiDroid and [anki's forum](https://forums.ankiweb.net/t/configuration-is-not-properly-synced/5989). It occurs with 2.1.35 anki and current master (15.alpha?) of ankidroid.

Reproduction steps:
1. In ankidroid's card browser, search for "A" and save this search as "A"
2. Sync ankidroid, then anki
3. In anki, open the browser. Remark that "A" is not listed as a search. Create a search "B" and save it as "B".
4. Sync anki then ankidroid
5. Open ankidroid card browser and look at the list of saved search. It contains B and not A.

Ideally, in step 3, A would have appeared in the card browser since it's added in the configuration's "savedFilter". In any case, it should not have disappeared from Ankidroid at step 5.

The sync occurs in rust, I don't understand it, so I've no idea exactly what occurs. I suspect at least that anki ignores the change in config and don't believe it's expected. If anki does not solve it, we should think about either:
* using a different config, so that anki does not erase ankidroid values
* manually ensure that data are not erased when syncing

**Comment by LinearMomentum** [comment]
May I work on this?

**Comment by mikehardy** [comment]
This may be quite difficult, but that is a vague warning. I think there may be syncing issues related to the general collection configuration object in general. What I mean is that it may not be specific to saved searches at all, there may be a general problem with syncing the config object in a collection between AnkiWeb and AnkiDroid.

So the first thing to do I think is to read the development guide's database / data structure area to determine exactly where saved searches are being stored. I assume it is in the collection configuration object but could be wrong

The second thing is to check the code for syncing that looks at exactly when the config object containing saved searches is determined to "need sync" and sent across from one to the other. Is it only in the "ConfirmModSchema" control flow for full syncs? Is there a way to sync just the config section that includes saved searches? I'm not sure

Then the third thing is to make a change to saved searches and verify all the knowledge from 1 and 2 above, and fix it?

**Comment by LinearMomentum** [comment]
> This may be quite difficult, but that is a vague warning. I think there may be syncing issues related to the general collection configuration object in general. What I mean is that it may not be specific to saved searches at all, there may be a general problem with syncing the config object in a collection between AnkiWeb and AnkiDroid.
> 
> So the first thing to do I think is to read the development guide's database / data structure area to determine exactly where saved searches are being stored. I assume it is in the collection configuration object but could be wrong
> 
> The second thing is to check the code for syncing that looks at exactly when the config object containing saved searches is determined to "need sync" and sent across from one to the other. Is it only in the "ConfirmModSchema" control flow for full syncs? Is there a way to sync just the config section that includes saved searches? I'm not sure
> 
> Then the third thing is to make a change to saved searches and verify all the knowledge from 1 and 2 above, and fix it?

I think I have realized this function. I just save the searches before sync and add the deleted ones after sync but I don't know whether that's true.

**Comment by mikehardy** [comment]
So you propose to implement a partial sync (hold saved searches to the side, merge them later) on the side of the main sync? How do you propose to manage naming conflicts or deletes of searches of the same name?

I believe you will quickly have re-implemented the existing sync algorithm, but just for deck configuration, with fresh untested code, in an AnkiDroid-specific (vs ecosystem-wide) implementation.

What would be better is to determine why the deck configuration is not already syncing as expected across the ecosystem with the existing sync logic, and fix that.

I do not want a special-sync-of-deck-conf-on-the-side-of-sync solution

**Comment by Arthur-Milchior** [comment]
I'd add an even stronger warning. This part of the sync is done in Rust upstream. So you may need to read some Rust code to try to figure out what's going on exactly. If you feel like you can do it, then you're very welcome to figure out what's going on. 
I believe that until you can explain why it is broken, it's too soon to consider code to correct it.
Actually, I suspect it might be required to do the correction in rust itself; DAE usually accepts code correcting bugs, but that need to be explained

**Comment by Arthur-Milchior** [comment]
So @LinearMomentum plase feel free to take this task if you believe you can do what we are asking. Otherwise, please let us know that you quit it, and it's perfectly fine too

**Comment by mikehardy** [comment]
Yeah, honestly I don't even want to go near this one hahaha, but it is important! It would be great if someone just said "you know what, I can't explain why, but I'm going to become the collection configuration sync expert" and fixed it all through the system.

**Comment by Arthur-Milchior** [comment]
The synchronization center is ankiweb. Which means only DAE can know the entire system.

But I used to know this part before rust. I taught myself rust since I wrote this bug report. So I can always take a look at it

**Comment by dae** [comment]
Can you reproduce the issue with the latest desktop code? Which direction the config syncs depends on whichever side was marked as modified more recently, and for a while there Anki had a bug that would mark the collection as modified when it shouldn't IIRC.

**Comment by Arthur-Milchior** [comment]
Do you get notification even when I don't use the "@" before your name?

I'll try to reproduce and let you know soon, thanks for your feedback

**Comment by Arthur-Milchior** [comment]
I can't reproduce anymore. Thank you @dae.

**Comment by dae** [comment]
No notification without the @

Glad to hear the issue's gone away!
