### ISSUE TITLE
When importing external html file into AnkiDroid page, an error is reported: Failed to load "XX.html"

### ISSUE THREAD

**Issue by hea7en2** [ankidroid/Anki-Android#7950]
###### Reproduction Steps

1. Create a new html file in the collection.media folder: _lunbo.html, and add content
2. The jQuery.js file was successfully introduced into the page
3. Call the $("#lunBo").load("_lunBo.html"); method when the page loads, the page reports an error: "_lunBo.html" failed to load
4. The same method is used to import files into Anki on the PC side successfully, and no error is reported. Why can't we import external html files in AnkiDroid? If it can be introduced by what method?

###### Expected Result

Hope that the external html file can be successfully imported through the $("#lunBo").load("_lunBo.html"); method

###### Actual Result

Use $("#lunBo").load("_lunBo.html"); failed to import external files, error: failed to load "_lunBo.html" file
![001](https://user-images.githubusercontent.com/46583161/102965655-3fb90d80-4529-11eb-9020-b818357e50be.jpg)
![002](https://user-images.githubusercontent.com/46583161/102965658-421b6780-4529-11eb-97e6-7b49111408b6.png)

###### Debug info
AnkiDroid Version = 2.18alpha4

Android Version = 10

ACRA UUID = cfa90515-e628-4e81-b5a1-cff6c2301bb4

Scheduler = std

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I don't understand the versioning ("2.18alpha4" does not exist) but I think this may be what you want? #7764

**Comment by hea7en2** [comment]
> 我不了解版本控制（“2.18alpha4” 不存在），但我认为这可能是您想要的吗？[＃7764](https://github.com/ankidroid/Anki-Android/pull/7764)

Sorry, the input was wrong, it should be 2.15alpha18, I deliberately used the latest version to test, but this problem does exist, I hope to be able to track down
