### ISSUE TITLE
Card Template Editor UI text entry areas unusably small

### ISSUE THREAD

**Issue by hea7en2** [ankidroid/Anki-Android#7951]
**Is your feature request related to a problem? Please describe.**
The windows of the three editing pages (front, style, and back) are too small. When there is a lot of content, it takes a long time to slide down to find the corresponding code. It is very troublesome. It is very inconvenient to adjust the page!
**Describe the solution you'd like**
I hope to be able to add pop-up buttons separately, click to open a separate editing window, and edit the page code in full screen mode to facilitate viewing the corresponding code
**Describe alternatives you've considered**
Add a pop-up button next to the small box, click to open a separate editing window, and edit the page code in full-screen mode
![321](https://user-images.githubusercontent.com/46583161/102966817-9fb0b380-452b-11eb-91e8-f3f8b408557c.jpg)

**Additional context**

**Comment by mikehardy** [comment]
Hi there! I agree with this, it is one of our current most popular issues debated but has not been logged anywhere

Upstream Anki Desktop I believe lets you edit each of the 3 sections on separate screens.

A successful solution to this would have a separate sub-screen for each of the three areas yes, perhaps in a ViewPager like the CardTemplateEditor, but definitely with more screen real estate for each area

Thanks for logging this

**Comment by sudomain** [comment]
At the time of this writing, Anki desktop (2.1.38) has a drop down menu to switch between card types and radio buttons to switch between the front template, back template, and styling section:

<img width="953" alt="anki 2 1 38 card editor" src="https://user-images.githubusercontent.com/30786326/103507024-2880f680-4e2c-11eb-9ab5-76c2202a1d08.PNG">

I'm not well-versed in Android-dev vocabulary, but I think AD's [template editor](https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplateEditor.java) uses a TabLayout to switch between card types and shows all template/styling in 3 textboxes on the same screen. My personal preference would be to have the card types in a dropdown menu (a "spinner" in android lingo?) at the top similar to desktop, and have a TabLayout beneath the spinner for the Front, Back, and Styling sections. This would give each section more room for editing. This might be bad UI though.

**Comment by mikehardy** [comment]
I think that is headed in the correct direction (spinner / drop-down for types, tab layout for template sections) and could work. Bad UI would be two tab layouts stacked on each other ;-)

**Comment by mikehardy** [comment]
This is a serious usability issue and does not track with desktop (where they have a separate sub-screen for each). Pinning

**Comment by Akshay0701** [comment]
Currently, after reading the above discussion,i understand the problem is with small view of Card Template Editor ,
So solution I think would be changing current UI matching with AnkiDesktop ,Like this 

![Capture](https://user-images.githubusercontent.com/52353967/116511688-72628080-a8e4-11eb-89d9-041455575420.PNG)

It might look little compact design , so to make this design more clean we can shift below editor options at bottom of screen 
![Capture](https://user-images.githubusercontent.com/52353967/116511939-ddac5280-a8e4-11eb-9202-a9cd50078a89.PNG)

so our UI may look like this : -
![Capture](https://user-images.githubusercontent.com/52353967/116512050-0c2a2d80-a8e5-11eb-9e3b-b74fd991f3c4.PNG)

**Comment by mikehardy** [comment]
That looks pretty good. We even have two viewpager2 examples in code base now with stats and inside card template editor already I think

**Comment by infinyte7** [comment]
We may take some ideas from AnkiMobile. In your PR radio button is good. 
But will it better to have like this?


<img src="https://user-images.githubusercontent.com/12841290/116713405-586d8e80-aa07-11eb-9969-359b50820dbf.PNG" height=500></img><img src="https://user-images.githubusercontent.com/12841290/116713419-5c99ac00-aa07-11eb-87cf-41f5449dd4a3.PNG" height=500></img><img src="https://user-images.githubusercontent.com/12841290/116713441-5efc0600-aa07-11eb-9827-8c84dee4114b.PNG" height=500></img>

**Comment by Akshay0701** [comment]
Thanks, it looks much better if we use bottom navigation bar rather than 3 radio button, I would love to implement in this way, @mikehardy  and @david-allison-1 what do you think, should we keep radio button or bottom navigation is good?
