### ISSUE TITLE
[Feature Request] Make a button with which you can repeat an almost forgotten word twice, after which it returns to its original place.

### ISSUE THREAD

**Issue by HannekeM** [ankidroid/Anki-Android#7956]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HannekeM** [comment]
Still waiting for a solution.

**Comment by mikehardy** [comment]
I don't believe this is present in Anki Desktop. Please note that unless it is something specific to the mobile form factor we only implement things that are in Anki Desktop

I'm going to provisionally close this but if you can point to the manual on desktop or post a screenshot of the feature you want here, implemented there, we can reopen
