### ISSUE TITLE
[Feature Request] Make the numbers new/learning/review clickable, so that you can choose and vary what you want to practice.

### ISSUE THREAD

**Issue by HannekeM** [ankidroid/Anki-Android#7957]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HannekeM** [comment]
Still waiting for a solution.

**Comment by mikehardy** [comment]
I don't believe this is present in Anki Desktop. Please note that unless it is something specific to the mobile form factor we only implement things that are in Anki Desktop

I'm going to provisionally close this but if you can point to the manual on desktop or post a screenshot of the feature you want here, implemented there, we can reopen
