### ISSUE TITLE
Delay showing flagged or marked state, until the answer is shown, to avoid hints

### ISSUE THREAD

**Issue by Andrej-Adamenko** [ankidroid/Anki-Android#7975]
The problem is that when I review a card I previously marked or flagged, the flag gives me a hint about the answer. I believe it is better not to show that state until the answer is shown. 

![Screenshot_20201228-091626_AnkiDroid.jpg](https://user-images.githubusercontent.com/70955223/103196769-75754200-48ed-11eb-956a-90e71ec60336.jpg)

**Comment by Arthur-Milchior** [comment]
That would be easy to create as an option, if we want to add it. I have no opinion on it, but I think some people here prefer to avoid increasing the number of options to much

**Comment by mikehardy** [comment]
Hi there - No, this would deviate from upstream. If the flags are part of your hinting system, configure the Action Bar to hide that button on to the menu so you don't see it

Alternatively, this is the sort of thing you can do with the javascript API, code up a bit of javascript that gets the flag for the card and displays it in your card on a delay. Niche options like this are why we have the JS API, so you can cover your needs without upstream deviation or options proliferation https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API
