### ISSUE TITLE
TTS fails with large text body [Bug]

### ISSUE THREAD

**Issue by hssnnkim** [ankidroid/Anki-Android#7982]
###### Reproduction Steps

1. put in large text body - e.g. "sample of too long.txt" text file attached
[sample of too long.txt](https://github.com/ankidroid/Anki-Android/files/5754998/sample.of.too.long.txt)

2. activate text to speech in settings
3. use this card template

{{FrontSide}}

\<hr id=answer>

\<tts service="android" voice="en_US">

{{Back}}

\</tts>

###### Expected Result

audio text to speech output like all of my other cards

###### Actual Result

No audio TTS output
and error message:
"No text-to-speech language available."

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.14.2

Android Version = 10

ACRA UUID = 86800501-5a5f-4080-b8a1-f965ea11344e

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting)) - can't figure out where changelog is for alpha version releases.

**Comment by mikehardy** [comment]
My initial take on this is that there may be nothing we can really do - there is probably some underlying limitation on TTS posted into the Android TTS engine

My second take is that it might be possible to break the text into chunks that the Android TTS engine can digest successfully, with a loop sending a chunk in, waiting for completion, sending another etc until all chunks sent.

If anyone wants to triage this to verify and (if my hypothesis is correct) post a PR, we could accept it

**Comment by hssnnkim** [comment]
Thanks for the reply. 

For now, I've taken the cards that are too long and creating separate audio files that I clipped onto the card. 

However, I also have Automatic Display Answer enabled, and for all cards that have an audio file attached, it doesn't move on to the next card automatically once the audio file finishes playing. Any tips on this?

**Comment by mikehardy** [comment]
no, sorry

**Comment by hssnnkim** [comment]
Bump :(

**Comment by mikehardy** [comment]
@hssnnkim sorry, that's not the way open source works, it's not squeaky wheels that get grease, it's people that do work to fix things that see their things fixed. I don't use TTS personally so while I have some solution ideas above, I have no time personally to work on them

**Comment by hssnnkim** [comment]
Oh sorry, I didn't mean for you specifically to fix it, was just trying to get someone else to "triage" it?

**Comment by hssnnkim** [comment]
Still searching for solutions :$

**Comment by dae** [comment]
Please comment if it's still a problem.
