### ISSUE TITLE
[Bug] Remaining time wrongly displayed as "0s" when falling under "1min"

### ISSUE THREAD

**Issue by julienbaley** [ankidroid/Anki-Android#7983]
###### Reproduction Steps

1. Review your cards until remaining time is 1 minute
2. Review a few more cards

###### Expected Result

It should either show "0 minute" or "55 seconds" (or whatever estimate is accurate given seconds/card)

###### Actual Result

It shows "0s". It suggests that Anki chooses the appropriate unite based on the remaining time (it does show "1h 5min" if over 59min), despite computing the remaining time in minutes. The smallest unit of display should match the estimation unit.
Admittedly, this is a minor bug, but perhaps it's trivial to fix :)

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by julienbaley** [comment]
This issue still exists :)

**Comment by david-allison-1** [comment]
Let's clamp the value at 1m

**Comment by AyaanJaved** [comment]
Can I work on this?
