### ISSUE TITLE
Font Scaling Does Not Work

### ISSUE THREAD

**Issue by jaykay-git** [ankidroid/Anki-Android#7985]
No matter what zoom scaling level is chosen using the slider in settings, the font on the cards stays the same exact size as before.  Restarting the app does not help either.

**Comment by mikehardy** [comment]
This is *usually* due to some styling in the card template that is causing the font size to be fixed
suggest editing an affected card, selecting one of the templates at the bottom of the card editor, which should open the card *template* editor, and checking the style section

**Comment by zoulja** [comment]
I second this.
Seems there is no simple way to zoom cards.
"Font size" setting affect only card edit menu, but not card display
