### ISSUE TITLE
[Bug] Fullscreen mode doesn't unhide bottom navigation when deeplinking into other apps (Pleco)

### ISSUE THREAD

**Issue by murphm8** [ankidroid/Anki-Android#7989]
The other links in the text selection context menu seem to work and show bottom navigation. That would be "Card Browser", "Anki Card", "Web Search", so I'm not sure in Android apps if the app being opened is supposed to defensively ensure the navigation bar shows,or if the app that is being deeplinked from should re-show the navigation bar. If this is a problem with Pleco please let me know and I can follow up with a bug report to them.

###### Reproduction Steps

1. Use fullscreen mode
2. On a card deeplink into another app (I use Pleco as a dictionary and can select text then use the context menu to open that in Pleco)
3. The bottom navigation bar does not show and I have to swipe up to get to the back button

###### Expected Result

I expect when a deeplink action occurs that AnkiDroid would show the navigation bar so I can return to AnkiDroid.

###### Actual Result

Bottom navigation bar continues to not show, making it tedious to return after checking another app.

###### Debug info

AnkiDroid Version = 2.14.3

Android Version = 11

ACRA UUID = 17718a15-abcc-4eaa-9189-efe4916107f2

Scheduler = std2

Crash Reports Enabled = true

.

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by murphm8** [comment]
Also posted on Pleco forums: https://www.plecoforums.com/threads/bug-navigation-bar-does-not-show-when-deeplinking-into-pleco-from-anki-when-in-fullscreen-mode.6651/

**Comment by david-allison-1** [comment]
@murphm8 Thanks for the report! Do you have a sample card which will exhibit this behaviour?

**Comment by murphm8** [comment]
This issue is with the "Pleco" item in Android's text selection context menu. I've updated the info above. I found that the bottom bar works correctly the first time I navigate to Pleco from Anki, but subsequent navigations the bar is hidden.

So:

1. Navigate to Pleco using the text selection context menu
2. Hit the back button
3. Navigate to Pleco using the text selection context menu
4. Now you should see that the back button is missing from the bottom of the screen
