### ISSUE TITLE
[Bug] Card Browser: suspend does not update UI

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#7992]
###### Reproduction Steps

1. Select a deck
2. Select All
3. Suspend

###### Expected Result

* Cards are marked in yellow

###### Actual Result

* Progress bar, card colour does not change when progress bar completes

###### Debug info
AnkiDroid Version = 2.15alpha20

Android Version = 9

ACRA UUID = 7e03f9c9-c191-4da0-a1f9-d76e8429bc60

Scheduler = std

Crash Reports Enabled = false

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
There was a related issue recently with regards to marking cards when coming back from note editor I think, a special flag was set / needed to be set to tell the card browser to refresh itself. Very vague but: I expect there is just some missing connection between the suspension and the card browser, no refresh request is being called on the card browser

**Comment by sumadithya** [comment]
I tried to replicate this.
It only gives expected results.

**Comment by sumadithya** [comment]
I want to work on this issue

**Comment by david-allison-1** [comment]
Sounds good to me, thanks!

**Comment by sumadithya** [comment]
I tested it further.
Turns out it only gives this problem when there are duplicate cards.

**Comment by david-allison-1** [comment]
Sounds good! Thanks for the update

**Comment by sumadithya** [comment]
I'm quite certain https://github.com/ankidroid/Anki-Android/pull/8642 must have fixed this issue. I will test it and report.

**Comment by sumadithya** [comment]
Sorry for the delay.
This is fixed by https://github.com/ankidroid/Anki-Android/pull/8642
I have tested it.

**Comment by david-allison-1** [comment]
@sumadithya Thanks!
