### ISSUE TITLE
[Privacy] WebView

### ISSUE THREAD

**Issue by duggalsu** [ankidroid/Anki-Android#7993]
Opt out of sending metrics to Google when using WebView. Add the following to the manifest -
```
<meta-data android:name="android.webkit.WebView.MetricsOptOut" android:value="true" />
```
https://developer.android.com/guide/webapps/webview-privacy

**Comment by mikehardy** [comment]
Nice! I like this idea. Philosophically we *do* use analytics and crash tracing but they are all *opt-in* and off by default. That's important to us. We want hermetic privacy by default if possible. If you proposed a PR for this I'd happily merge it.

**Comment by mikehardy** [comment]
It is worth noting that users are still in control of this setting: https://support.google.com/accounts/answer/6078260
So if a user has opted out at the device level, this will be off for them in our application as well.
I am still positive on the idea of just opting out for our app as well though.

**Comment by david-allison-1** [comment]
Thanks so much for the suggestion! 

Completely agreed. Let's get rid of it
