### ISSUE TITLE
Problem importing large deck on Ankidroid. Every time I try to import the deck the app crashes

### ISSUE THREAD

**Issue by Derweag** [ankidroid/Anki-Android#7995]
What the title says. When I click on [this deck](https://www.reddit.com/r/medicalschoolanki/comments/iri0yg/anking_overhaul_v8v3_release_physeo_tags_skin_of/) (about 3.2 gbs) to import it my phone freezes for couple of seconds and then the app crashes/closes to main screen.

I tried importing relatively smaller decks 1.6gbs and 900 mbs and same thing happened. Smaller decks than those worked fine.

I've plenty of storage space on my phone. My phone is Honor 8X with Android 10 and using Ankidroid's latest version available on Play Store.

AnkiDroid Version = 2.14.2

Android Version = 10

ACRA UUID = 9497ef74-a9d9-449c-9a07-89a4fd9be0d5

Scheduler = std

Crash Reports Enabled = true

**Comment by mikehardy** [comment]
For very large decks (and make no mistake - from a mobile perspective, these are very large) we recommend import on Anki Desktop, sync to AnkiWeb then sync down to AnkiDroid. We know that path works.

We do have some success with large decks but it's not guaranteed (as you can see)

Hopefully that gets you moving with the deck you need to import?
