### ISSUE TITLE
[Bug] TTS working for the whole card but not for the `<tts>` marks.

### ISSUE THREAD

**Issue by nbrr** [ankidroid/Anki-Android#7996]
###### Reproduction Steps

Card includes `<tts service="android" voice="ja">{{Expression}}</tts>` and other stuff.
Note that I have tried a bunch of other values for `voice`: ja, jp, Japanese, jpa, jpn, en_GB.
Either have AnkiDroid's Settings -> Advanced -> TTS enabled or disabled.

###### Expected Result

TTS for {{Expression}} **only** is played.

###### Actual Result

Nothing is played when TTS is disabled.
The **whole card** is read when TTS is enabled, so TTS somehow works.

###### Debug info

AnkiDroid Version = 2.14.2

Android Version = 8.0.0

ACRA UUID = d92aee43-a5d0-4d7c-893e-70fe6312faaa

Scheduler = std

Crash Reports Enabled = true

###### Research

I note several TTS-related issues reported here, as well as mentions of it in the manual of FAQ, but none seem to address the specific case where TTS works for the whole card, but not for the `tts` mark. I have tried downgrading Google TTS's app.

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by srghma** [comment]
I have switched from google tts to samsung and it worked

**Comment by srghma** [comment]
Actually have this issue too

**Comment by bitozoid** [comment]
It looks to me that once enabled, AnkiDroid will TTS the whole card unless it finds the right HTML tag. That looks as a bug to me. 

* AnkiDroid Version = 2.14.6
* Android Version = 10
* ACRA UUID = 65952fbc-9f5b-4fc9-a37b-b311606de719
* Scheduler = std2
* Crash Reports Enabled = true

Meanwhile, this may be a workaround (derived from https://github.com/ankidroid/Anki-Android/wiki/FAQ#tts--text-to-speech-is-not-speaking):

```html
<div id="anki_tts">{{tts en_US voices=AwesomeTTS:Front}}<tts service="android"/></div>

<p><div id="ankidroid_tts" style="display:none;">
    <tts id="tts_tag" service="android" voice="en_US">{{Front}}</tts>
</div></p>

<script>
 if (document.documentElement.classList.contains("android")) {
       document.getElementById("anki_tts").innerHTML = "";
 } else {
       document.getElementById("ankidroid_tts").innerHTML = "";
 }
</script>
```
