### ISSUE TITLE
Any way to use qFade and aFade in ankidroid?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ankidroid/Anki-Android#7997]
**Is your feature request related to a problem? Please describe.**
I use [my own template of cloze](https://github.com/thiswillbeyourgithub/Clozolkor), basically sometimes it loads the answer side directly when reviewing and my code then hides by itself the answer. My problem is that on ankidroid fading with aFade and qFade son't seem to exist and without fading, I can catch a glimpse of the answer before it hides.  [here's the code in anki](https://github.com/ankitects/anki/blob/13994973cb866dd1a3a8db9a547268e2ef1b6e94/qt/aqt/data/web/js/reviewer.ts). I believe this is also interesting to have when using image occlusion as some slower device can show the answer before the rectangles are added on top.

**Describe the solution you'd like**
Ability to set aFade and qFade in my js template to make the question and answer load gradually.

**Describe alternatives you've considered**
Frankly just looking away.

**Additional context**
I'm using 1.14.2 I hope it's okay for me to ask this here, I searched the wiki and the codebase for any related code but no luck.

**Comment by Arthur-Milchior** [comment]
It seems it would require to rewrite a big part of the javascript. Thanks for giving a link to current anki code, it looks like it changed a lot since it was ported on ankidroid. It may occur one day, especially since @infinyte7 seems to touch a lot the javascript part, but I don't know when

**Comment by infinyte7** [comment]
Anki use single webview for displaying all questions and answers to same webview by removing previous displayed questions and answers. But in AnkiDroid every time ```__viewer__.html``` created and new card content loaded to AnkiDroid webview. To get facility of qFade and aFade, there should be changing to webview part but this will leads to change to major portion of AnkiDroid codebase.

But setTimeout in javascript can be used to wrap the questions or answer. The ```text2``` will dislpayed after 1 sec but here fisrt text1 displayed. It can be useful.
e.g.
```
<div id="text1">Some text</div>
<div id="text2" style="display: none;">Display after some time</div>
<script>
setTimeout(function() { 
     document.getElementById('text2').style.display = "block";      // inline-block, inline, flex...
}, 1000);   // display after one second
</script>
```

**Comment by thiswillbeyourgithub** [comment]
Thank you very much, I will try to implement your script into my template when I have more time.

Thank you so much.
