### ISSUE TITLE
I want to be able to insert my new card to the front of the new cards queue

### ISSUE THREAD

**Issue by jparta** [ankidroid/Anki-Android#7998]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when I have to create a card, and then search for it to reposition it to the front of the queue. My new cards are introduced I  the order created. Sometimes I create a card that I want to learn sooner than later.

**Describe the solution you'd like**
I want to have an option on the creation page for repositioning the card.

**Describe alternatives you've considered**
One way to do it is to order cards by created time and filter to new cards. But this isn't much different than just searching for the card, in terms of effort.

**Comment by mikehardy** [comment]
Hi there! Does Anki Desktop let you do this? If not, this will likely not happen here, if it does we can mark it for ecosystem compatibility and put it in the queue. Thanks!

**Comment by jparta** [comment]
It does not. Should I suggest the feature to be added on desktop?

**Comment by mikehardy** [comment]
Yes! That's the normal path for features that aren't a direct result of something that is purely caused by being mobile vs being desktop (like, the huge difference in screen size...). Then we do our best to keep up with the desktop features as they come

**Comment by jparta** [comment]
Understood. Thanks!

**Comment by WiliTest** [comment]
The feature request must be asked here: https://forums.ankiweb.net/
