### ISSUE TITLE
Screenshots for F-Droid 

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [ankidroid/Anki-Android#7999]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by mondlicht-und-sterne** [comment]
it doesn't matter if and when this is done. this is just information that it is still possible.
the screenshots would then have to be entered into fastlane.

**Comment by shuvashish76** [comment]
PR submitted.
As per the F-Droid doc, it has to be in root directory.
