### ISSUE TITLE
[Bug] Tag "marked" not synced

### ISSUE THREAD

**Issue by lervag** [ankidroid/Anki-Android#8000]
Recently I've experienced that the tag `marked` applied while reviewing is not synced properly. If I mark a note on AnkiDroid, then sync to my computer, the note is not marked on my computer. It seems synchronization otherwise works as expected.

I don't know exactly when, but I think this issue is recent and started to occur within the last month or two.

**Comment by lervag** [comment]
Huh. I did a "check database" and now the tags were properly synchronized. I don't know why/what happened. Sorry for the noise...

**Comment by mikehardy** [comment]
Very strange! If it recurs please do come back and let us know. Also congratulations on being item 8000 here :-)

**Comment by lervag** [comment]
> Very strange! If it recurs please do come back and let us know.

Will do. If I do, do you have any up front tips on what kind of input may be of help for debugging/inspecting?

> Also congratulations on being item 8000 here :-)

Thanks! Well timed and planned, of course :p

**Comment by mikehardy** [comment]
If at all possible an export of an affected deck (even if just with one card) along with exact steps to reproduce and the "debug info" copied from advanced settings all the way at the bottom (if you tap the version number you get a screen that has version details that help us reproduce on the same version you're using etc)

**Comment by Arthur-Milchior** [comment]
Where did you mark the card ? Reviewer ? Browser ?

It may be possible the note is not marked as changed, even if it seems unlikely. Anki onnly sync changed elements 
Did you make any change on the marked note on your computer ? Editing a note on two devices then syncing both device will discard the change from one of those devices

**Comment by lervag** [comment]
> Where did you mark the card ? Reviewer ? Browser ?

While reviewing.

> It may be possible the note is not marked as changed, even if it seems unlikely. Anki onnly sync changed elements
> Did you make any change on the marked note on your computer ? Editing a note on two devices then syncing both device will discard the change from one of those devices

Thanks, that's useful to know. I don't know exactly if this explains the issue, but it will be good to keep in mind.
