### ISSUE TITLE
[Bug] AnkiDroid not usable on Google Pixel 1 XL due to invalid directory path

### ISSUE THREAD

**Issue by tbop** [ankidroid/Anki-Android#8002]
###### Reproduction Steps

1. Install AnkiDroid on a Pixel 1 XL (Android 10)
2. Open AnkiDroid

###### Expected Result
The application should show the dashboard and sync with your account.

###### Actual Result
Application directly shows "Advanced Settings" and mentions that an invalid directory is set.
When trying to return to the main screen the app will terminate. The application cannot be used on this device.

Similar issues were lately reported [here](https://github.com/ankidroid/Anki-Android/issues/6345#issuecomment-753307405) and [here](https://github.com/ankidroid/Anki-Android/issues/5097)

###### Debug info
AnkiDroid Version = 2.14.2

Android Version = 10

ACRA UUID = 63a662f7-ae81-476f-9ff2-2a2e60bd71bd

Scheduler = Not found

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
How'd the troubleshooting steps work out for you? https://github.com/ankidroid/Anki-Android/wiki/FAQ

**Comment by tbop** [comment]
@mikehardy I could bet I had previously tried this but.... it seems that reinstalling the app solved my issue. Thank you so much!

https://www.youtube.com/watch?v=3YmMNpbFjp0

**Comment by IlluvatarEru** [comment]
Getting the same error 3 years later. Updated Anki to latest version triggered the error (Samsung no external storage).
Re installing the apps hold *not* be the default troubleshooting step. Especially as this means losing your decks.
