### ISSUE TITLE
Syncing causing full re-download of decks

### ISSUE THREAD

**Issue by ryanp97** [ankidroid/Anki-Android#8004]
AnkiDroid Version = 2.14.2

Android Version = 11

ACRA UUID = 1036d894-ee07-403c-8504-17d79239b82a

Scheduler = std

Crash Reports Enabled = true

Every time I sync, it attempts to re-download all files. It seems to initiate the re-download after the differential is sync'd. Repros everytime on my pixel 5.

**Comment by david-allison-1** [comment]
Hi @ryanp97,

Sorry for the late response. 

If your collection does not contain sensitive information, could you zip it/rename it to `.zip` and post it here?

The file to upload is located in `/AnkiDroid/collection.anki2`

If it contains sensitive information that you wouldn't want to be public, could you send it to my gmail: davidallisongithub

All the best,

David
