### ISSUE TITLE
Improve UX when user regularly hits the time limit for answering

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8005]
**Is your feature request related to a problem? Please describe.**

Some users take longer than 60 seconds per card regularly, and by default Anki and AnkiDroid cap the "time" in the revlog at 60 seconds. This means that both statistics, and the estimates for deck completion time are significantly less than they should be, frustrating users.

**Describe the solution you'd like**
I would like a warning, either in the Reviewer, or in deck statistics that the "maxTaken" is often (~25% of the time?) being hit, and this will impact both estimates, and stats.

**Describe alternatives you've considered**
This suggestion is open-ended and the threshold is arbitrary. Mostly posting this for discussion and to log a user frustration.

**Comment by ElnuDev** [comment]
+1

**Comment by voidplayer** [comment]
just an idea, maybe show the time by default? This will make people aware of this setting and when it stops counting

I personally reduced it. 30-40 seconds is enough for me. If it takes longer, i just fail it

**Comment by david-allison-1** [comment]
@ElnuDev did you have the timer display for cards enabled or disabled?

**Comment by david-allison-1** [comment]
> just an idea, maybe show the time by default? This will make people aware of this setting and when it stops counting
> 
> I personally reduced it. 30-40 seconds is enough for me. If it takes longer, i just fail it

I'd been thinking about this - I don't recall what the Anki defaults are, but I'll check.

Thanks!

**Comment by ElnuDev** [comment]
> @ElnuDev did you have the timer display for cards enabled or disabled?

I believe it was disabled.

**Comment by haran2248** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> Some users take longer than 60 seconds per card regularly, and by default Anki and AnkiDroid cap the "time" in the revlog at 60 seconds. This means that both statistics, and the estimates for deck completion time are significantly less than they should be, frustrating users.
> 
> **Describe the solution you'd like**
> I would like a warning, either in the Reviewer, or in deck statistics that the "maxTaken" is often (~25% of the time?) being hit, and this will impact both estimates, and stats.
> 
> **Describe alternatives you've considered**
> This suggestion is open-ended and the threshold is arbitrary. Mostly posting this for discussion and to log a user frustration.

Are you suggesting that the maximum time limit is increased from 60s to more than that?Do you have any maximum cap in mind?

**Comment by ElnuDev** [comment]
No, rather that there should be "a warning, either in the Reviewer, or in deck statistics that the "maxTaken" is often (~25% of the time?) being hit, and this will impact both estimates, and stats," as @david-allison-1 said. I think for most people/decks, 60 seconds is perfectly adequate, but in case it isn't, it would be good to have some sort of warning to let people know that there's an option to change the maximum time to prevent their statistics from being completely messed up as mine was.

**Comment by david-allison-1** [comment]
Up for discussion - I don't think we've got a good design yet.

I'd be tempted to say "display the timer (in red) if the max time is hit", but having opinions from other maintainers would be useful here

**Comment by voidplayer** [comment]
Major problem wast that op wasnt aware of this setting. I personally discovered it myself and turned it in after a few years of use

Ideas:
- Show it in by default. This will likely make you aware of the cards being time sensitive and look for a setting
- Dont show it by default. Show a tool tip after hitting it the 100th time

**Comment by ElnuDev** [comment]
I feel like there should be a "no stale" label or something...
