### ISSUE TITLE
[Feature] Swivel screen access on the LG Wing

### ISSUE THREAD

**Issue by mcamtat** [ankidroid/Anki-Android#8007]
I know its sort of obscure but the LG Wing is a phone that has a smaller screen when swiveled out and some apps are compatible with it. Ankidroid unfortunately is not. It would be extremely cool if you guys were to make it to where LG Wing users can use Ankidroid on the smaller screen.

**Comment by mikehardy** [comment]
Well that's a novel design ;-)


> 6.8" FHD+ P-OLED, 2460x1080 resolution, 60Hz - 3.9" half FHD+ OLED, 1240x1080 resolution, 60Hz
