### ISSUE TITLE
[Bug] Extra bar in statistics graph

### ISSUE THREAD

**Issue by dummifiedme** [ankidroid/Anki-Android#8008]
###### Reproduction Steps

1. Open ANKIDroid
2. Go to Statistics
3. Go to 

###### Expected Result
The marked in the actual reesult shouldn't be there.

###### Actual Result
![image](https://user-images.githubusercontent.com/68785729/104117706-5e047300-5349-11eb-9150-010548c465f4.png)

###### Debug info
AnkiDroid Version = 2.14.2

Android Version = 10

ACRA UUID = 6741e8ea-fe6c-4c57-9f40-47b4f7e61073

Scheduler = std2

Crash Reports Enabled = true

###### Research
- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))
- ALso, I tried to look through various options (month, year, deck life), restrating the phone and clearing the cache. Nothing seems to fix it.

**Comment by mikehardy** [comment]
Very interesting! If you could export a collection or deck that reproduces this we would be most grateful. You may attach them here by changing the extension to just .zip or you can email it to me if it is more sensitive at github at mikehardy.net. That one should be easy to fix

**Comment by dummifiedme** [comment]
I forgot to mention. I checked for all the decks individually as well. The error only shows when "All Decks" are selected.
There are quite a few decks if you really need, which one should I provide, if at all? :p

**Comment by mikehardy** [comment]
I need a reproduction case, so whatever will reproduce it when imported

**Comment by dummifiedme** [comment]
I don't exactly know which deck might be creating problem, since I have checked them all individually.
I will share one of my major deck.

https://drive.google.com/file/d/1CbSqv4_Oy7hyIo_P7l9Ht2Rio2y3vJ27/view?usp=sharing

**Comment by dae** [comment]
Recent Anki versions add an entry in the revlog with ease=0 when manually rescheduling cards in the browse screen, so the graphs will need to be updated to exclude that value.

**Comment by dummifiedme** [comment]
I am glad (or proud) to have found it then 😄. Contribution++

**Comment by mikehardy** [comment]
Yeah, that helps as the deck here did not reproduce it when imported, thanks @dae

**Comment by mikehardy** [comment]
Here's the commit to port https://github.com/ankitects/anki/commit/ce49ca940167c4da181f124bf2cd0104559c2642

**Comment by mikehardy** [comment]
I chucked up a PR that will/should ignore ease == 0 in stats queries but does not copy the manual revlog entry, I think we'll get that from rustlib as we adopt that, the rust scheduler is the only spot the 0's are inserted

I like that the stats is in typescript now, as we adopt anki's rust lib we should be able to just bolt the various typescript parts together into a webview as well and not maintain that either (which would be great as the AnkiDroid stats stuff is pretty out there, code-wise...)
