### ISSUE TITLE
[Bug] Not a valid path. Registration not possible.

### ISSUE THREAD

**Issue by SoerenHH** [ankidroid/Anki-Android#8013]
###### Reproduction Steps

![image](https://user-images.githubusercontent.com/77383644/104431047-bf198a00-5587-11eb-89ce-894b7e377f94.png)

Everything works fine on my old cell phone. The above error occurs on the new Google Pixel 4a. Registration is not possible. When I started the app for the first time, I also allowed the phone to be shared.

Thanks for your help!

// Auf meinem alten Handy funktioniert alles. Auf dem neuen Google Pixel 4a kommt der o.g. Fehler. Eine Anmeldung ist nicht möglich. Beim erstmaligen Start der App habe ich auch die Freigabe auf den Handyspeicher zugelassen.

Danke für eure Hilfen!

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Can you double-check that you have granted storage permissions for the app?
What happens if you try `/sdcard/AnkiDroid`?
What happens if you *completely* delete and reinstall the app?

**Comment by SoerenHH** [comment]
Hallo. Ich bin immer nur in das angezeigte Menü gekommen (siehe oben) und hatte zuvor die Speicherfreigabe erteilt.
Hatte auch mehrfach die App deinstalliert und wieder installiert.

--> Mein Handy hat keine Speicherkarte. Ich habe dennoch Ihren Vorschlag  /sdcard/AnkiDroid probiert und es funktioniert 
jetzt tatsächlich!

Vielen Dank!!!

**Comment by mikehardy** [comment]
Fantastic! I wonder if this was an artifact of preferences auto-backup/restore on to a new phone 🤔  - @david-allison-1 I think it was your PR that put the real machine filesystem path in there a while back, I wonder if there is a failure to open that maybe an /sdcard/AnkiDroid could be attempted before giving up?

**Comment by david-allison-1** [comment]
I think a "reset to default" button would make sense here 

Would that work for you? @mikehardy

**Comment by mikehardy** [comment]
I like that - overt / obvious / should work

**Comment by kartikeysaran** [comment]
Can i work on this ?

**Comment by david-allison-1** [comment]
Sure!
