### ISSUE TITLE
Proposed improved UI

### ISSUE THREAD

**Issue by quentinjs** [ankidroid/Anki-Android#8019]
Hi,

I apologize for a draft proposal but I'm looking for feedback and suggestions.  I have struggled with the UI now for a few days and from my experience if its not intuitive for me then its going to be a headache for others.  

I have attached a very rough draft of part of the process flow (with concept images).  Please provide constructive suggestions and I will update the story board PDF accordingly.

I have just noticed that the screen image names are not part of the PDF.  I will update with first round of feedback

[Flash Cards.pdf](https://github.com/ankidroid/Anki-Android/files/5816992/Flash.Cards.pdf)

**Comment by david-allison-1** [comment]
Hi @quentinjs, thanks for the suggestions.

We aim to have functional compatibility with Anki Desktop, which means that we typically avoid adding features unless they're in Anki Desktop, or very relevant to reviewing on a phone, and won't affect users syncing to the desktop version (for example: gestures). 

A lot of the suggestions in the PDF seem to be geared around adding new functionality, and this is unlikely to occur.

----

That being said, we're definitely interested in improving the UX of the app. If you were to pick a few "high impact" suggestions which wouldn't involve adding functionality, where would you start?

**Comment by quentinjs** [comment]
I'm glad I sent the draft.  :-)  

It might look like it was focused on new functionality, but its mostly a change in layout/flow with what you have as existing functionality.  

**Approach**
Workflow is probably the most important, so everything but the play screens need to be considered. Although on the play pages I think adding a "audio" button next to each displayed phrase is much clearer way to replay and change the audio than the current way in the setting menu that is very clunky.

The story boards are meant to foster discussions, and I don't know all the use cases as I am focused on learning a language not say social studies or Calculus or others.  So feedback is very appreciated.

II will focus on a UI workflow on my story board, and pull the new features out.  The new features I will return to once we nail down some flow changes on the SmartPhone. .  And possibly Desktop if you feel a story board for the desktop would help. 

**Features**
 I don't use the desktop app, but the suggested new features I touched on should also be do-able in the desktop app as well (slightly different layout) and of course mouse and keyboard focused vs smartphone.  I will install the desktop app and provide a more comprehensive  examples when UI is nailed down.  Also as above, prioritization and importance by others is important to guide my designs.

**Comment by quentinjs** [comment]
I can't fix but I provide business experience on good UX design If you
don't want it then I can waste my time more enjoyable ways.

**Comment by mikehardy** [comment]
@quentinjs no need to get testy ;-).
You should understand of course that we are all volunteers, so you're just talking to a group of people that do this *when they have time*
You should also know that we are participating in the Google Summer of Code this year, which provides a mentoring opportunity to (at current count) more than 150? Maybe 200 by now young programmers who are looking at the app and sending us a firehose of ideas and proposed code changes.

Isn't that amazing? I think it's pretty cool.

So just some patience :-)

**Comment by quentinjs** [comment]
I am not trying to be impatient but if the request has to hit multiple apps
then so be it.  And great there is that many helping hands.  I am just
trying to help in the way that I can.
