### ISSUE TITLE
"Review All" option

### ISSUE THREAD

**Issue by lotard** [ankidroid/Anki-Android#8020]
I currently have ten active decks, each of which will have a couple cards to review each day. Instead of clicking on each deck separately, I'd like to click 'review all' and get it over with.

It could be an option in upper-right corner menu (where "Create filtered deck" etc are).

**Comment by mikehardy** [comment]
Hi there! Does Anki Desktop do this? We try to follow their functionality so we are unlikely to add this if they do not, however this seems like a cool feature. I know I would use it. Can you check and if not, pursue it here: https://forums.ankiweb.net/

**Comment by iCarlosCode** [comment]
Yeah, man! That would be awesome. For now, you can use [subdecks](https://docs.ankiweb.net/#/getting-started?id=decks). I think it can solve your problem a little bit.
For example, you can create a deck for Calculus and create subdecks for Limits and Derivatives. When you review your Calculus’ deck, you will review all of your subdecks **at once**.
Organize your decks to find decks that you could convert into subdecks for a given field. Maybe you have a deck for grammar and a deck of slang that could be subdecks of only one English Language deck.

**Comment by lotard** [comment]
Thanks for the workaround @iCarlosCode!

I'll take it up with Anki Forums (:

**Comment by mikehardy** [comment]
For reference, I have a big "parent deck" where I put "Learned" and I re-parent my decks when they are finished and just in long-term review under that one. You do that by changing the name of the deck you learned and want to have just in the big "Learned" area with a prefix 'Learned::', as the parent-child relationship is managed entirely by the deck name, with path components separated by double colon '::'
