### ISSUE TITLE
Frequency Scaling for adaptive learning

### ISSUE THREAD

**Issue by quentinjs** [ankidroid/Anki-Android#8021]
I think the frequency / scaling of learning frequency can be simplified and thus the UI as well.

**Goal**
Remove the need for a user to think about card difficulty, they have 2 choices (on smart phone) swipe left or right.

**Assumptions**

- User applies an initial "feel" of difficulty, similar to Story Points. 
- Fixed scale for all users
- Frequency Scaled based on Fibonacci scale.  May days is 34.  (1min, 1 day, 2D, 3D, 5D 8D 13D 21D and 34D)
- User can force the play of completed cards
- Must score 3 learns to move up. Must fail once to move down.
- Variant:  only 20 cards will be played at a the same time, as cards are marked as successful and are moved up in progression for that day add additional cards.

**Difficulty Initial State**
Able to set a starting point based on users feeling of difficulty. Very familiar with topic, somewhat familiar and none at all. (Easy, average, and Difficult) with the deck of cards being created.

**Process**

1. Based on Feel, choose starting point as 1min, 1d or 2d.
2. For cards at 1Min.  If a user plays the deck long enough in the first day, the user can move the card to 1D.  
3. Determine progression up.  
- **Case A** If User is on 1Min.  If the user takes less than 1 day to move a card forward.  then progress to 1D.
- **Case B** If User is on 1Min.  The user takes 5 days to move a card forward.  Say user plays on day 1, and then on day 3 and day 5, then the card is moved to 8D.
-**Case C** Is user is on day 34D and completes 3 wins then the card is marked as learnt and removed from play.
4. Determining Progression Down. If the user fails at a card, then the card is immediately moved to the next lower stage.  E.G. from 8D to 5D

**Feedback please?**

**Comment by mikehardy** [comment]
This is something you should discuss upstream on https://forums.ankiweb.net/ first

We copy Anki Desktop behavior in general / as a guiding principle for our functionality. We're not going to deviate from that

**Comment by quentinjs** [comment]
Move the story to where ever it needs to be.
