### ISSUE TITLE
Old images are repeating when I add new ones. PLEASE HELP

### ISSUE THREAD

**Issue by kinteryder** [ankidroid/Anki-Android#8022]
Hi, I have been using anki for now about 5 or 6 days but ever since i started adding images on my cards, it just keep repeating old images i have added before. If I create a new card in ankidroid and then it shows to a attachment icon right, when I click it, It says “Add images, Add audio clip etc…” . And when I click on add images and add one from my gallery of my phone and crop it I click on the tick button. and then I View it **its not the picture I added or uploaded. It’s showing a old picture I added.**

PLEASE HELP

**Comment by iCarlosCode** [comment]
Hi. Could you please record your screen? Have you tried to use other gallery app?

**Comment by kinteryder** [comment]
no its not like that of a problem, the problem is that when i use gallery
or camera to add a picture to a card and after i save it and open it, its
showing a previous image that i have uploaded earlier. Please help

**Comment by iCarlosCode** [comment]
Ok. But if you record a short video showing the bug happening, it would be a lot better to understand it. Best regards

**Comment by kinteryder** [comment]
Ok, I will do that.

**Comment by iCarlosCode** [comment]
Ok, Looking forward to it. 😁

**Comment by zestily** [comment]
Hi! I also have this problem! I recorded my screen. As you can see, everything works fine until I look at the card. Then the attached image is from a different one. It also doesn't matter if I use Anki's camera function, or if I crop the image or not.
Any idea on how to fix this? 

https://user-images.githubusercontent.com/81319012/112344834-ca461000-8cc4-11eb-87d8-2fb81150b7e6.mp4

@iCarlosCode

**Comment by iCarlosCode** [comment]
Thanks for recording, I am going to try it.

**Comment by zestily** [comment]
Thank you so much!

**Comment by iCarlosCode** [comment]
I tried. But I wasn't able to replicate this bug. I will record my screen showing how everything just works as intended. Maybe it varies from cellphone to cellphone. I am using a Samsung Galaxy A11. Android 10.

**Comment by zestily** [comment]
Thanks a lot! I actually found that this is only a tablet bug, not a phone bug for me (at least it hasn't shown up on my phone so far). Odd, huh? It's a workaround, not a solution, but meanwhile I'm happy I can still use it in all its functionality as intended :)

**Comment by mikehardy** [comment]
This definitely comes up in play store reviews, it may be hard to reproduce - I've certainly never seen it! - but I'm sure there's a problem somewhere...

**Comment by zestily** [comment]
still searching for solutions

**Comment by mikehardy** [comment]
Yes I believe this was just noticed by a reviewer on play store as well. I still have not seen it but I'm sure it's happening

**Comment by iCarlosCode** [comment]
The problem is just to know why and how this is happening...
