### ISSUE TITLE
[Bug] Build environment requirements?

### ISSUE THREAD

**Issue by zoulja** [ankidroid/Anki-Android#8023]
Hi
I'm checking whether I can contribute something good to AnkiDroid.
So I installed AndroidStudio 4.1, cloned repo, opened project and got the following:
```
class jdk.internal.loader.ClassLoaders$PlatformClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$PlatformClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
class jdk.internal.loader.ClassLoaders$PlatformClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$PlatformClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')

Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)

Re-download dependencies and sync project (requires network)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.

Stop Gradle build processes (requires restart)
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.
```

Where I can get detailed information about build environment requirements? 
https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#Android-Studio has some very general description and not much helpful.
My environment:
Kubuntu 20.10
AndroidStudio 4.1
```
% java -version                                                                                                                                                                                          
openjdk version "1.8.0_275"
OpenJDK Runtime Environment (build 1.8.0_275-8u275-b01-0ubuntu1~20.10-b01)
OpenJDK 64-Bit Server VM (build 25.275-b01, mixed mode)
```

**Comment by mikehardy** [comment]
Hi there!
That wiki page is not general, it is actually specific enough, it does appear the error message is fairly prescriptive.
I develop using Ubuntu 18 currently which should be similar, and it works, along with openjdk 1.8

There's really not much else to it, and you can see from the output of the github action runs here (for the unit tests at least) that it's using all the same tooling

No idea what went wrong but your local environment does seem corrupt somehow

**Comment by david-allison-1** [comment]
@zoulja What version of Java does `JAVA_HOME` point to?

**Comment by zoulja** [comment]
@david-allison-1 thanks a lot for looking into this
JAVA_HOME is not set at all as I see.
Per Google recommendation I've tried to set it to **android_studio_installation_path/jre** but result is the same

**Comment by mikehardy** [comment]
I don't know what path `java -version` is pulling java from (`which java` ?) but that's what JAVA_HOME should be.

With apologies, our development setup is perhaps the most basic Android app java set up possible at the moment. It is completely standard. The ability to set it up correctly is just a pre-requisite for developing Android apps and since we're not doing anything special, any given information you find online or stackoverflow should serve.

**Comment by zoulja** [comment]
Sorry for bothering you good sir, but a few years ago I had AndroidStudio related case(even I'm not Android/Java developer) - and it's not that simple, and there is no 'standard'
There are always some dependencies and missing details and there is no any guarantee the code will be built in different environment.
So I'm almost sure volunteers work in some good old environment and you don't have time resources to test ankidroid build with all AndroidStudio versions/OS versions.
I don't blame anyone, I just want to understand how to deal with this issue. 
I already checked SO before posting, so now I'm running out of ideas

**Comment by mikehardy** [comment]
There is a standard, "download Android Studio, check out the repository, open it in Android Studio", that's literally it! I'm not exaggerating. Some years ago perhaps it was more involved.

If you want to get nitty-gritty, you may install openjdk itself manually (use package manager of choice, configure JAVA_HOME in shell), install the android command line tools (configure PATH to include them), check out the repository and go.

There is not anything else to it. It is confounding that with two requirements to fulfill: a working java, a working set of command line tools (both which you can get from Android Studio full install) it does not work for you.
