### ISSUE TITLE
Plus (+) and minus (-) buttons for increasing "new cards"

### ISSUE THREAD

**Issue by srghma** [ankidroid/Anki-Android#8024]
I'm always frustrated when I want to increase number of new cards for today, but to edit current number have to remove it first

**Describe the solution you'd like**

Add these buttons that call modal

![Screenshot_20210118-191546_AnkiDroid](https://user-images.githubusercontent.com/7573215/104946329-88e26d00-59c2-11eb-8e82-b8d90d297e2d.jpg)

![Screenshot_20210118-193357_AnkiDroid](https://user-images.githubusercontent.com/7573215/104947293-386c0f00-59c4-11eb-9ae6-c2f92dcf686d.jpg)

**Comment by david-allison-1** [comment]
@srghma It's better to temporarily increase the number of new cards via the `custom study` option, but the change looks good to me, thanks!

**Comment by Blargian** [comment]
Hi, I'm a frequent user of Ankidroid and would like to get involved in contributing to open-source. Could I take a stab at this for my first issue?

**Comment by mikehardy** [comment]
Hi @Blargian - sure! The rough sketch above seems like it would acceptable for merge to me, and David said the same. I believe the general idea is that you tap on the setting you want to change, then if it's an integer-type preference (like this new cards per day setting) you will add the ability to "listen" for volume up / volume down events and use those to alter the setting? Could work and could be a nice "first change" in the code base, yes.

If you haven't already, check out the development guide in the wiki as it takes you through getting all set up with existing code correctly passing unit / emulator automated testing and has a limited bit of guidance on where code is located, but as a first change the thing to do (if it were me) would be to then open the app on the emulator while watching `adb logcat` (easy to view and filter in Android Studio - it can be noisy!) and open up the feature you are looking to modify. Hopefully there are already some log messages printed out that help locate the feature in the code, if not I would add some to make sure I *knew* I was modifying what I thought I was modifying...and then you can start trying to modify things and we can check the PR when it seems like it's working

Feel free to ask here for more info on anything, it's always fun to work with new contributors, each one of us that is here now received help from someone else when starting so don't be shy. Cheers

**Comment by Blargian** [comment]
Hi @mikehardy  thanks for the pointers. I'll give this a shot and reach out for help if I get stuck

**Comment by mrudultora** [comment]
@Blargian Are you still on it ?

**Comment by Blargian** [comment]
@mrudultora I didn't have any luck with this - I need to learn quite a bit more about android first. Please feel free to take over if you would like.

**Comment by danishjamal104** [comment]
Whats the status of this issue?Anyone still working on this?

**Comment by mrudultora** [comment]
@danishjamal104 I would take this up. But still waiting as some points are not clear.

**Comment by Arthur-Milchior** [comment]
It seems Blargian answered that they are not working on it anymore. So @mrudultora feel free to work on it

**Comment by ayush1729cpp** [comment]
is anyone working on this issue , or shall i work

**Comment by bhatushar** [comment]
@mrudultora @ayush1729cpp Are you working on this issue? If not, please let me know as I'd like to work on it.

**Comment by mrudultora** [comment]
@bhatushar @ayush1729cpp I am currently working on another issue. I guess, you can mutually decide and anyone can take this up. I am not on it as of now.

**Comment by mrudultora** [comment]
> Hi @Blargian - sure! The rough sketch above seems like it would acceptable for merge to me, and David said the same. I believe the general idea is that you tap on the setting you want to change, then if it's an integer-type preference (like this new cards per day setting) you will add the ability to "listen" for volume up / volume down events and use those to alter the setting? Could work and could be a nice "first change" in the code base, yes.
> 
> If you haven't already, check out the development guide in the wiki as it takes you through getting all set up with existing code correctly passing unit / emulator automated testing and has a limited bit of guidance on where code is located, but as a first change the thing to do (if it were me) would be to then open the app on the emulator while watching `adb logcat` (easy to view and filter in Android Studio - it can be noisy!) and open up the feature you are looking to modify. Hopefully there are already some log messages printed out that help locate the feature in the code, if not I would add some to make sure I _knew_ I was modifying what I thought I was modifying...and then you can start trying to modify things and we can check the PR when it seems like it's working
> 
> Feel free to ask here for more info on anything, it's always fun to work with new contributors, each one of us that is here now received help from someone else when starting so don't be shy. Cheers

@bhatushar @ayush1729cpp This had to be implemented.

**Comment by ChaxuGarg** [comment]
Can I give this issue a try? @mrudultora

**Comment by ayush1729cpp** [comment]
@mrudultora thanks for telling ,  i am working on another issue so @ChaxuGarg you can ask @bhatushar if he is working on it or not

**Comment by bhatushar** [comment]
I've submitted a PR for this issue. If it gets accepted, close this thread.

**Comment by mikehardy** [comment]
@srghma next alpha will have this courtesy of @bhatushar :smile:
