### ISSUE TITLE
Learn "learning" queue only after others, don't mix it with other two queues, only populate "learning" queue"

### ISSUE THREAD

**Issue by srghma** [ankidroid/Anki-Android#8025]
**Is your feature request related to a problem? Please describe.**

I believe it improves speed

Todo write tree of how old options interact with this checkbox

There are 3 queues: new blue, learning red, review green

**Describe the solution you'd like**

![Screenshot_20210118-212435_AnkiDroid](https://user-images.githubusercontent.com/7573215/104956189-46c22700-59d4-11eb-9ee0-b1686838a014.jpg)

**Comment by srghma** [comment]
In my particular case I want to review, learning, new, learning

**Comment by mikehardy** [comment]
Hi there! How does Anki Desktop handle this? In general - but especially with scheduler options - we follow Desktop as closely as possible. If this is not Anki Desktop the right place to start is with them, then we will do our best to incorporate it here - https://forums.ankiweb.net/

**Comment by david-allison-1** [comment]
We'll need this in Anki Desktop before we work on it

**Comment by srghma** [comment]
added the feature request to the anki forum 

https://forums.ankiweb.net/t/order-of-queues-new-setting/8520

**Comment by david-allison-1** [comment]
Thanks! Please let us know if it gets included
