### ISSUE TITLE
[Bug] "Media checked" notification reversed

### ISSUE THREAD

**Issue by tbm** [ankidroid/Anki-Android#8031]
The sync notification looks good:

![notification-sync](https://user-images.githubusercontent.com/1556037/105276380-38465c00-5bdc-11eb-8ef0-356722a435fa.jpg)

Now compare the "media checked" notification:

![notification-media](https://user-images.githubusercontent.com/1556037/105276406-472d0e80-5bdc-11eb-8a7e-a4b6b8c652e9.jpg)

The text is reversed.

It should be:

```
**AnkiDroid**
Media checked
```

instead of

```
**Media checked**
AnkiDroid
```
###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Nice! Not sure I've ever actually seen that notification but the reversal is pretty obvious!
