### ISSUE TITLE
Reset progress of cards

### ISSUE THREAD

**Issue by noseyposey17** [ankidroid/Anki-Android#8033]
I used AnkiDroid last night, and this morning when I synced my progress, all of my reviews for the day were reset to learning cards.  Not sure what happened, but I had to open a backup on my desktop to fix. Just wanted to make sure you all were aware.

**Comment by david-allison-1** [comment]
Hi @noseyposey17, thanks for the report.

Was this a 'full sync' (download/upload), or the regular two-way sync?

**Comment by noseyposey17** [comment]
I believe it was a regular two-way sync. I haven't been able to recreate it, and it only affected the one subdeck I was working on at the time. I've synced again since this morning, with no problems.
