### ISSUE TITLE
Ankidroid is a day behind Ankiweb[Bug]

### ISSUE THREAD

**Issue by EJBlake409** [ankidroid/Anki-Android#8035]
###### Reproduction Steps

1. Sync Ankiweb
2. Sync Ankidroid
3. 

###### Expected Result
Ankidroid has the same number of cards due today as shown on Ankiweb

###### Actual Result
Ankidroid has 0 cards due today; the cards due today on Ankiweb are due TOMORROW on Ankidroid. For example, on Ankiweb there are 200 cards due today; Ankidroid shows that there are 0 cards due today and that these 200 cards are due tomorrow instead. If I proceed to do all 200 cards due today on the desktop version, Ankidroid will then say that there are 0 cards due tomorrow.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.14.3

Android Version = 9

ACRA UUID = 305461c2-8d06-4063-a716-7327790234a3

Scheduler = std2

Crash Reports Enabled = true
###### Research
*Enter an [x] character to confirm the points below:*

- [X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X ] I have searched for similar existing issues here and on the user forum
- [X ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @EJBlake409 

The latest alpha (https://github.com/ankidroid/Anki-Android/releases/download/v2.15alpha26/AnkiDroid-2.15alpha26-universal.apk) allows you to enable "New Timezone Code" in Anki Desktop and sync. Does this fix the issue?

**Comment by EJBlake409** [comment]
@david-allison-1 
I thought I was a part of the alpha program, but I am trying the link that you included in your message, and it won't seem to work on my phone. I am able to download the link when tapping on it and open up the package installer. However, when I tap "install", I get a message saying "App not installed." 
I do think that the "New Timezone Code" would fix the issue, (if I can get it to work on Ankidroid), because when I turn it on in Anki Desktop, the schedules between the two align. 
Thank you so much for your help

**Comment by david-allison-1** [comment]
Is your device low on space? That's the normal issue 

(Android's error messages aren't helpful at all)

**Comment by EJBlake409** [comment]
I have over 17 GB of available space. Even after deleting some apps, I tried the link again and am still getting the "App not installed" message :(

**Comment by mikehardy** [comment]
There are a few other reasons this can happen unfortunately I know of no other way to diagnose them then to turn on developer mode on the device (google it - it's a bunch of taps on the build number in the device info screen), allow adb usb debug connections in the new developer mode menu, then plug it in to a computer and using `adb logcat` (from the Android Studio command line tools) to watch the device log and see whatever exception stack trace is thrown during the install

As a developer I think this process is not ...so bad as far as setting up troubleshooting environment go but if it's your first time doing anything like that it might sound daunting. So I can't say "you should do that" without knowing your experience level + motivation, but that's the path forward if you want to continue down the path

**Comment by EJBlake409** [comment]
I will have to give this a try, thanks. In the meantime, is there any estimate as to when the "New Timezone Code" will be compatible with Ankidroid in beta or public versions?

**Comment by mikehardy** [comment]
I try to do a "feature release" on the main release trains (beta -> public) about every 2 months, and it has been about a month already, so, hopefully soon. The underlying thing releasing this time (incorporating the upstream Rust library) is a really deep change though so - even though it appears to be working great right now - it might be delayed. Sorry, that's the best ETA I can give

**Comment by mikehardy** [comment]
I *think* this is a duplicate of #6203 and I'm closing it to consolidate.
