### ISSUE TITLE
Accents

### ISSUE THREAD

**Issue by Bat-Ori** [ankidroid/Anki-Android#8038]
I'm using Anki for language learning, and I'm mightily impressed. Only difficulty is, my Surface tablet is rubbish at inserting accents. It strikes me that there's a lot of free space. I wonder if you could put some buttons there for éèêôûàâîëïç and so on? I imagine I'm not the only person who has this problem...

**Comment by david-allison-1** [comment]
Hi @Bat-Ori.

Just confirming: this query is for AnkiDroid, and not Anki Desktop.

That's what the editor toolbar can be used for. Click the "+" and you can add a button which will add in an accented letter.

Long press a custom icon to remove it.

----

But, you're probably better downloading a keyboard in your target language for your sSrface, then long pressing a key on a virtual keyboard (or using Alt+Gr/similar on a physical keyboard) to learn how to type the accents as a native would.

I'm going to close this as answered, but please feel free to respond or ask to have the question reopened if you've still got questions

Thanks for using AnkiDroid!

David
