### ISSUE TITLE
Filter raise error messages

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8043]
When trying the latest ankidroid alpha my template started to not work, giving me a warning that `{{info-Factor:}}` fields don't exist or something like that. Those "info" fields are used because of the addon [additional card fields](https://ankiweb.net/shared/info/744725736) that is only supposed to affect anki desktop and should be ignored on ankidroid.

I dont' know if it's just because it's an alpha or if it's a regression but figured it might be useful to notify you!

Sorry again for the double mail. Thanks a lot!

_Originally posted by @thiswillbeyourgithub in https://github.com/ankidroid/Anki-Android/issues/8030#issuecomment-766065941_

**Comment by Arthur-Milchior** [comment]
@thiswillbeyourgithub can you please copy both the card template you use and the exact error message.

**Comment by Arthur-Milchior** [comment]
Can you also try the card type with anki without add-on and let us know how it works. We are trying to reproduce anki without add-on, so it may not be a bug technicaly speaking. It may still be something we want to change

**Comment by thiswillbeyourgithub** [comment]
Hello again, thank you for the quick reply as always.

1. Apparently it is a bug because running anki-desktop without addons returns no error code whatsoever.

2. The error code I get on the latest ankidroid build is 
```
Front template has a problem:Found '{{info-New?}}', but there is no field called 'info-New?'.
More information
```

3. As for posting my template, I'm afraid it might cause more trouble than it's worth because my particular template is very custom, with js and external css files etc. But I reproduced with a more minimal template as follows :
front : 
```
        <span class=notOnMobile>
                <span class=red>
                    <u>{{info-New?:}}</u>
                </span>
                <u>{{info-Review?:}}{{info-Learning?:}}</u>
                {{info-Factor:}}
        </span>

{{cloze:Text}}
```

styling : 
```
.notOnMobile { color:grey; font-weight:bold; }
    .mobile .notOnMobile { display : none ;}
```

I confirm this template cause no issue in ankidroid 2.1.14, no issue in anki 2.1.35 without addons, and the aforementionned error code in the latest ankidroid build.

Btw, thanks a buch to whoever had to idea of parallel builds, it's really helps a tremendous amount to be able to quickly test versions without screwing up having to uninstall and reconfigure etc.

**Comment by Arthur-Milchior** [comment]
Could you maybe share a crad with your minimal example. That would help. For example, right now, I don't know which fields you have in your card, which is important to test

**Comment by mikehardy** [comment]
Parallel builds idea and initial script were @timrae I believe, and yes, thanks to him for that, I still use them regularly as a profile support workaround

**Comment by Arthur-Milchior** [comment]
@mikehardy While I certainly appreciate Tim Rae work, I don't understand why you are mentionning this here and suspect that you posted in the wrong thread

**Comment by dae** [comment]
The OP mentioned parallel builds above.

Re this functionality, please see the header of https://github.com/ankitects/anki-addons/blob/master/demos/field_filter/__init__.py

**Comment by Arthur-Milchior** [comment]
I've seen it and I'm working on correcting it

**Comment by thiswillbeyourgithub** [comment]
> Could you maybe share a crad with your minimal example. That would help. For example, right now, I don't know which fields you have in your card, which is important to test. For example, do you have a field `info-Review?`

There you go : Note that this is an apkg file, I just removed the extension and put "zip" to allow exchanging over github.

[Selected Notes.zip](https://github.com/ankidroid/Anki-Android/files/5865905/Selected.Notes.zip)

**Comment by Arthur-Milchior** [comment]
I think I corrected it. Can you please test 2.15 alpha 23 and check whether the problem correctly disappeared

**Comment by thiswillbeyourgithub** [comment]
I confirm all my earthly problems went away. Thanks!
