### ISSUE TITLE
[Bug] Card was registered as "pass" when changed deck on review

### ISSUE THREAD

**Issue by i-zanis** [ankidroid/Anki-Android#8047]
###### Reproduction Steps
1. While reviewing click editor
2. Change a card to another deck with different steps.
3. The card registers as correct twice, first with the interval shown in the first deck then on the new one.

First Card
![image](https://user-images.githubusercontent.com/55964867/105620977-9e102f00-5dfa-11eb-81ff-ded373f29c4c.png)
Second Card
![image](https://user-images.githubusercontent.com/55964867/105622634-f4856980-5e0a-11eb-905a-7e87e6bb2874.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi @i-zanis, is this bug report for AnkiDroid, or Anki Desktop?

If it's for AnkiDroid, could you fill out the "Debug info" section in the original post.

Thanks
