### ISSUE TITLE
Bottom Nav Bar instead of Side Drawer

### ISSUE THREAD

**Issue by nxcco** [ankidroid/Anki-Android#8053]
To provide Anki Droid with a more modern UI, I suggest changing from a side drawer to a bottom navigation bar, as it also would fit all necessary items. In addition, the advantage would be a better navigation experience on large screens. What do you think?

**Comment by mikehardy** [comment]
It would take up real estate constantly as opposed to the drawer going away, wouldn't it?

Our users are fantastically jealous of both the screen real estate (if you consume any of it without some way to make your new style go away completely, they will complain) and their attention (if you add anything to the UI that cannot be disabled, they will complain)

From my experience with those two specific complaints, I don't think a bottom navigation bar fits with AnkiDroid's core reviewing experience?

**Comment by nxcco** [comment]
I understand, as I also considered this behavior. Maybe some time in the future :D

**Comment by mikehardy** [comment]
could happen :-), not sure if it ever will be more modern given installed userbase preferences but who knows?
