### ISSUE TITLE
[Bug] UnknownHostException when syncing media

### ISSUE THREAD

**Issue by nylonee** [ankidroid/Anki-Android#8062]
###### Reproduction Steps

1. Have Anki decks in the cloud which include images and other media content
2. Attempt to sync decks to Anki-Android
3. Push Notification appears with error

###### Expected Result
Anki-Android should correctly sync all media

###### Actual Result
Notification error occurs, see image:
![photo6095798322905329200](https://user-images.githubusercontent.com/4732553/106208808-ded1c480-61bb-11eb-9595-df87ed5bc7f5.jpg)
Attempting to open the deck shows that the media has not synced. See image:
![photo6095798322905329199](https://user-images.githubusercontent.com/4732553/106208868-f7da7580-61bb-11eb-9278-b58a190bbcf1.jpg)

###### Debug info
AnkiDroid Version = 2.14.3

Android Version = 11

ACRA UUID = 176fbb42-e3df-45a9-8f37-efe53613e788

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Temporary issue with your internet connection. 

If you look at the `AnkiDroid/collection.media` folder, after each media sync, there should be more files.

Continue syncing until it completes.

----

We could potentially improve this error message for users. It's one of the more common issues. 

I've added a fix for the login screen, but we could do better with the media sync (as it's likely to be the longest sync)

**Comment by nylonee** [comment]
Oh interesting, that makes a bit more sense now.
It doesn't look like retries are implemented, this seems like a good place to implement some retries (and make the error message a bit more user friendly)

**Comment by david-allison-1** [comment]
Definitely!

A reimplementation of the sync mechanism is on the cards for 2021 (personal estimate: mid/late Q2)
