### ISSUE TITLE
Enhance the drawer experience

### ISSUE THREAD

**Issue by HuixingWong** [ankidroid/Anki-Android#8070]
The conflict between the drawer and system gestures makes it not very convenient to use

**Comment by mikehardy** [comment]
Hi there! Please be very very specific about exactly you mean. Which gesture? At which point on the screen? Which version of Android?

Further please take pity on us, note that Android just added system gestures at the operating system level. How exactly to interoperate / cooperate with them? It's a tough problem.

So very specific suggestions for working together with system gestures would also be appreciated

**Comment by HuixingWong** [comment]
> Hi there! Please be very very specific about exactly you mean. Which gesture? At which point on the screen? Which version of Android?
> 
> Further please take pity on us, note that Android just added system gestures at the operating system level. How exactly to interoperate / cooperate with them? It's a tough problem.
> 
> So very specific suggestions for working together with system gestures would also be appreciated



> Hi there! Please be very very specific about exactly you mean. Which gesture? At which point on the screen? Which version of Android?
> 
> Further please take pity on us, note that Android just added system gestures at the operating system level. How exactly to interoperate / cooperate with them? It's a tough problem.
> 
> So very specific suggestions for working together with system gestures would also be appreciated

Most newer Android devices have full-screen gestures that cause the drawer to fail to slide out from the side
