### ISSUE TITLE
[Maybe fixed?] Problem with sync in ankidroid / "No value in models"

### ISSUE THREAD

**Issue by Devamitta** [ankidroid/Anki-Android#8079]
When I try to sync on ankidroid, it is failed and write a error "syncing error, type: -1, message: org.json.JSONExeption: No value in models.

**Comment by acheng-ubc** [comment]
I just got this exacr same issue as well right now. I'm not sure how to provide more debug or error information, but I have tried using Check database and Check media but nothing has worked. I have no custom study decks.

AnkiDroid Version = 2.14.3

Android Version = 10

**Comment by mumeme** [comment]
I just got the same issue too

**Comment by diertian** [comment]
me too.

AnkiDroid Version = 2.14.2

Android Version = 9

**Comment by Devamitta** [comment]
Now everything again working well. 
Thanks!

**Comment by diertian** [comment]
I tried 4 or 5 times. And it's OK now.

**Comment by mikehardy** [comment]
Sounds like something must have happened on the ankiweb server? Strange.

**Comment by mikehardy** [comment]
This was resolved upstream, no longer happening
