### ISSUE TITLE
[Error Decoding Response Body]

### ISSUE THREAD

**Issue by roysnyderts** [ankidroid/Anki-Android#8080]
![image](https://user-images.githubusercontent.com/78456682/106686661-af92cd00-6598-11eb-9ff9-bbff29032d1b.png)

Unable to sync on my computer. Tried 'check database' to no avail.

My phone won't sync either and receives a "json.decoder.JSONDecodeError: Expecting value: line 1 column 1" error. 

Any help be appreciated!

**Comment by mikehardy** [comment]
Others reported the same thing (#8079) but are also reporting that it is working now? Note that AnkiWeb is not in our control, we are compatible with it, but it is a different group - https://forums.ankiweb.net/ is their support site
