### ISSUE TITLE
Make timebox limit warning into a confirm popup

### ISSUE THREAD

**Issue by fletchermoore** [ankidroid/Anki-Android#8081]
The current timebox implementation is as a notice that appears in the same was a card being automatically suspended, and is fairly subtle. On desktop the timebox stops you and makes you confirm to continue. I would like this feature on droid as well, since I sometimes miss the timebox event on droid.

**Comment by kuroni** [comment]
Hi, I would like to work on this!

**Comment by david-allison-1** [comment]
Awesome, thank you!!
