### ISSUE TITLE
Pas d'accès à l'application 

### ISSUE THREAD

**Issue by CloThpb** [ankidroid/Anki-Android#8083]
Bonjour,
Quand j'ouvre l'application, je suis directement dans les paramètres et il y a un message d'erreur qui s'affiche en indicant que le chemin vers le stockage des donnés n'existe pas. J'ai tenté de desinstaller et réinstaller l'appli sans succès, j'ai aussi redémarrer mon téléphone. 
J'ai + de 1000 cartes sur mon compte et j'aimerai vraiment pouvoir y accéder. Quelqu'un aurait il une solution à mon problème ?
Merci d'avance

**Comment by CloThpb** [comment]
Voilà un screenshot de la page où je suis bloquée: https://zupimages.net/viewer.php?id=21/05/pe7e.jpg

**Comment by mikehardy** [comment]
Hello - I believe I responded on Google Play reviews, but try '/sdcard/AnkiDroid' in the database path
