### ISSUE TITLE
CSS grid on ankidroid vs desktop

### ISSUE THREAD

**Issue by boydkelly** [ankidroid/Anki-Android#8087]
Hi,

I am trying to style my .card with display: grid.   My cards are perfect on desktop even with small window size.   But on Ankidroid it seems the grid is not respected.   I am not asking for specific help here.   Just wondering is there any way to 'inspect' the html in ankidroid to see what is happening?  It  there a known issue where this will not work or is totally not supported?   Thanks for any pointers!  bk

**Comment by mikehardy** [comment]
Hi there!
Indeed there is, you can use the full chrome devtools: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

Also maybe of interest https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting
