### ISSUE TITLE
Have the option to use subdeck card limit when reviewing from a parent deck

### ISSUE THREAD

**Issue by awesome-rdash** [ankidroid/Anki-Android#8091]
**Is your feature request related to a problem? Please describe.**

On AnkiDroid, when I review a parent deck containing multiple sub-decks, the limits of each sub-deck are not used and are replaced by the parent deck limit.
It's very frustrating as on desktop it's working the opposite, and also I have precise limits for my sub-decks according to the course importance, exam date, exam passed..., and I want to review all my courses at once, with each individual limitations.

**Describe the solution you'd like**
I would like to have an option for each deck that could be as simple as a checkbox "Use sub-decks parameters".
Also, the behavior should be the same between desktop and android.

**Describe alternatives you've considered**
I can't think of another option, what I'd really like is to have is a big bucket with all my cards, but with different settings inside that bucket.

**Additional context**
I searched for this and understood it was supposed to work that way here and there:
https://github.com/ankidroid/Anki-Android/issues/7625
https://forums.ankiweb.net/t/2-1-scheduler-does-not-respect-subdeck-max-review-limit-when-reviewing-a-parent-deck-with-a-higher-limit/2577
https://faqs.ankiweb.net/the-anki-2.1-scheduler.html

**Comment by awesome-rdash** [comment]
Actually on Anki desktop, it looks like there is an issue where the number or review is calculated according to the old scheduler (0 review left), but when I start review, the 2.1 behavior is correctly used. The issue is only on the display side.
![image](https://user-images.githubusercontent.com/2684614/107131365-d8d39600-68d5-11eb-8e26-99edeaaed568.png)

**Comment by BLannoo** [comment]
I have the same issue, can this issue be re-opened.

**Comment by mikehardy** [comment]
@BLannoo please use the most recent alpha, in a specific way, and you should get same scheduling as on Anki Desktop:

- install from https://github.com/ankidroid/Anki-Android/releases
- settings --> advanced --> enable new schema
- settings --> advanced --> enable v3 scheduler
