### ISSUE TITLE
The informations of the app are disapearing during the play

### ISSUE THREAD

**Issue by Kayminet** [ankidroid/Anki-Android#8093]
AnkiDroid Version = 2.14.3

Android Version = 8.0.0

ACRA UUID = 9690f7f0-abde-4de9-8b24-6e1957131ce8

Scheduler = std

Crash Reports Enabled = true

**Comment by mikehardy** [comment]
Hello!
Unfortunately this includes no specific information about the actual problem you encountered vs the expected behavior, or precise steps to reproduce

You may like https://github.com/ankidroid/Anki-Android/wiki/FAQ#lost-my-cards
