### ISSUE TITLE
Answer button size (I want to get smaller)

### ISSUE THREAD

**Issue by Cho-jin** [ankidroid/Anki-Android#8096]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

1. Answer button size (I want to get smaller)
   Answer button size is 100% at least..... How can I get small answer button.

**Comment by mikehardy** [comment]
I recommend turning on gestures, and hiding buttons entirely. Making the button size customizable is not something we're currently contemplating but lots of people are fans of the gesture system. Have you tried it?

**Comment by iCarlosCode** [comment]
Yeah, @mikehardy's  suggestion will make the button size equal 0%. You will never have to worry about it again. Give gestures a try. :)

**Comment by sheharyaar** [comment]
@Cho-jin If it is resolved, please close the issue.

**Comment by Cho-jin** [comment]
Thanks. I try gestures.
