### ISSUE TITLE
[Bug] text-to-speech tag

### ISSUE THREAD

**Issue by smb1987** [ankidroid/Anki-Android#8097]
There is a problem in android version. As you know, recently PC version of Anki added a text-to-speech feature that isn't possible in android version as easy as it is in Windows, Mac etc.
If someone uses _{{tts en_US Front}}_, he should type again _{{Front}}_ to see the text of this field. Since the android version can not run _{{tts en_US Front}}_, it shows the text of this field and therefore the user (which uses both PC and Android versions) sees the text of the field twice on the phone (once for _{{tts en_US Front}}_ and once for _{{Front}}_) and the correct format is heard and shown just on PC. It seems easy to change the code of AnkiDroid and make it able to ignore _{{tts ...}}_ completely, until this version be able to perform this tag.

**Comment by iCarlosCode** [comment]
Hi, @smb1987. I have already opened an issue about it, please check #8010.
Thanks for opening it too.

**Comment by mikehardy** [comment]
Yes - resolving this as a duplicate in favor of #8010 as that one has more information
