### ISSUE TITLE
js api -> ability to open card browser (the card search) from js api with `ankiSearch("deck:foo myField:bar")`

### ISSUE THREAD

**Issue by srghma** [ankidroid/Anki-Android#8109]
**Describe alternatives you've considered**

related to:
- https://faqs.ankiweb.net/linking-cards-together.html
- https://ankiweb.net/shared/info/1423933177

the current solution to make links from card to card is to:
- render all cards as html files
- place them in collection.media folder on mobile or pc
- add Iframes `<iframe src="_card${cid}.html" width="${0.9*window.innerWidth}" height="${0.9*window.innerHeight}" ></iframe> `

but you cannot edit the related card this way

**Is your feature request related to a problem? Please describe.**

But for me the ability to issue the search request / open card browser would be sufficient

**Describe the solution you'd like**

in back of my card I would have sentence

```
<div onclick="ankiSearch("deck:\"My Deck\" kanji:kanji1")">kanji1</div>
```

and on press it would open card browser (without closing the card!!!, I can still return to it by pressing back button)

and fill it with search query

the search query parser would extract the:
1. "deck:..." - if no deck is in query THEN use "All Decks"
2. (maybe) [`is:suspended`](https://github.com/ankidroid/Anki-Android/blob/c2f6c1080a099800faaf83e2690abd7e343d7d1b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L1072)
3. (maybe) `tag:marked`
4. [...all other fields are considered as query to `setQuery`](https://github.com/ankidroid/Anki-Android/blob/c2f6c1080a099800faaf83e2690abd7e343d7d1b/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L1073)

**Additional context**

![photo5280945011405468666](https://user-images.githubusercontent.com/7573215/107871300-e924db80-6ea8-11eb-87a6-4d2f4f3786f8.jpg)

**Comment by infinyte7** [comment]
@srghma I don't think it will be supported because the linking part is done by addons in Anki. Also it needs to checked the behavior of card created using that addons in AnkiDroid. The searching and opening deck browser using JS API may be implemented in AnkiDroid.

**Comment by srghma** [comment]
> I don't think it will be supported because the linking part is done by addons in Anki

yes, I don't this, it's just related

> The searching and opening deck browser using JS API may be implemented in AnkiDroid

good, that's all I need

**Comment by srghma** [comment]
I still think it's useful feature to have (to open search tab with js)
