### ISSUE TITLE
[Bug] Matrices are not rendering when using Mathjax

### ISSUE THREAD

**Issue by twisp007** [ankidroid/Anki-Android#8110]
###### Reproduction Steps

Using Mathjax write a matrix.

```
\[\begin{bmatrix}
1 & -2 & 1 \\
0 & 2 & -8\\
-4 & 5 & 9 \\
\end{bmatrix}\]
```

###### Expected Result
![In Desktop Anki it works fine.](https://user-images.githubusercontent.com/28303082/107880710-a85baf80-6f06-11eb-9492-bd5caa18bf88.png)

###### Actual Result
![In AnkiDriod it doesn't.](https://user-images.githubusercontent.com/28303082/107880741-cfb27c80-6f06-11eb-8f9f-3f06677ed7d8.png)

###### Research

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Does this still happen with the alphas? Some heavy work has been done on mathjax between 2.14 and the 2.15alpha series - https://github.com/ankidroid/Anki-Android/releases

**Comment by twisp007** [comment]
Both Google Play Version and the latest alpha version have this problem.

The issue seems to be that some HTML creeps into the Mathjax code. But only AndiDroid has an issue with this. The desktop version of Anki displays the matrices with no problem.

**One way to avoid HTML creeping into Mathjax code is to drop into the "HTML Editor View (ctrl+shift+x)" and type in the Mathjax code.**

Since deviant behavior from the desktop version is considered a bug in AnkiDroid am I leaving the issue open.

**Comment by mikehardy** [comment]
Very interesting - yes this should be addressed, and that's good info re: html creeping in / workaround - thank you
