### ISSUE TITLE
[Bug] Negative time reported in review time statistics

### ISSUE THREAD

**Issue by bjornmartensson** [ankidroid/Anki-Android#8111]
###### Reproduction Steps

1. Go to Statistics for my deck.
2. Set the time interval to "deck life"

Note: Advanced Statistics is disabled.

###### Expected Result
Review time shows meaningful numbers.

###### Actual Result
Review time shows negative number of minutes that are completely out of whack, e.g. average for days studied: -6032.3 minutes/day. Even if this number was positive, it would be wildly incorrect.

See screen shot:
![ankidroid-negative-statistics](https://user-images.githubusercontent.com/8526080/107965978-8405de80-6fab-11eb-9b22-70de463a353b.png)

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Peyman-hme** [comment]
Hi, I would like to working on it.

**Comment by david-allison-1** [comment]
> Hi, I would like to working on it.

Sounds good!

**Comment by david-allison-1** [comment]
Do you have a plan for how to work on this one?

**Comment by Dian-Jiao1031** [comment]
I wanted to try to fix the bug, but I found that I couldn't reproduce the bug. Maybe I should think about the conditions under which the bug appeared first……

**Comment by Dian-Jiao1031** [comment]
@david-allison-1 
It can find that although the data in the review time is negative, the calculation process is correct (e.g. -22741816 / -6032.3 = 3770.0074). I just looked at stats.java, but I didn't seem to find the specific methods to calculate the four data (sorry, maybe my code understanding is not good enough). Could you give me a brief hint, thanks a lot.

**Comment by david-allison-1** [comment]
I have absolutely no clue what's gone on here, sorry.

It's likely not DST related. Could possibly be someone changing their time settings. 

Doesn't seem to be under or overflow, possibly a date initialised to 1970?

**Comment by Dian-Jiao1031** [comment]
> I have absolutely no clue what's gone on here, sorry.
> 
> It's likely not DST related. Could possibly be someone changing their time settings.
> 
> Doesn't seem to be under or overflow, possibly a date initialised to 1970?

Well, I don't think it's below the overflow either, I'll try and fix it and then pull request

**Comment by Dian-Jiao1031** [comment]
> I have absolutely no clue what's gone on here, sorry.
> 
> It's likely not DST related. Could possibly be someone changing their time settings.
> 
> Doesn't seem to be under or overflow, possibly a date initialised to 1970?

Well, I agree with u. I'll see if I can fix it and then pull request

**Comment by bjornmartensson** [comment]
Strangely, when I look now, the number are positive and realistic. The bug must have gotten fixed. The only thing that is slightly weird is that longest interval shows as -35.5 years, but that I don't care much about.

I think we can close this issue? Thanks for the help with it!
