### ISSUE TITLE
[Bug] Corrupt collection 

### ISSUE THREAD

**Issue by Rafania** [ankidroid/Anki-Android#8112]
About a month ago when I opened AnkiDriod it generated a report which I sent. I kept using the app normally until 
2 weeks ago when I tried to sync it gave me the error "your collection has been corrupted" . Checking the database also gives me the same error. It suggests that I use an old back up but my latest one is too old and I will lose alot of work. Can you please help me fix it without restoring from an old back up

**Comment by Arthur-Milchior** [comment]
Hi,

Normally, when you created the bug report, you saw a text https://docs.ankidroid.org/help.html indicating you how to get debugging information. Can you please share them with us, so that we can maybe find your report. 

Ankidroid does backup itself automatically, so normally, you have regular backup. I assume you get the message when you open the app, and that it suggest to use a backup. Normally, if you click on it, it should show you backups.

If I understand correctly, you don't sync regularly, and getting backup from server would give you very outdated collection, right?

In android, if you know how to navigate the memory, you have a folder called AnkiDroid, you might want to make a copy of it before doing anything, so that the current state of the collection is copied and can't be lost anymore.

**Comment by Rafania** [comment]
AnkiDroid Version = 2.14.3

Android Version = 10

ACRA UUID = 71b38b82-73fe-4f47-9502-58ae4b9c1f4e

Scheduler = std

Crash Reports Enabled = true

**Comment by Rafania** [comment]
![Screenshot_20210216_005527_com ichi2 anki](https://user-images.githubusercontent.com/79109907/108069831-7e240200-706c-11eb-836b-70961564d5f1.jpg)
![Uploading Screenshot_20210216_005531_com.ichi2.anki.jpg…]()

**Comment by Rafania** [comment]
Hi! Thanks for replying so quickly.
I pasted the debugging information and the error I receive when I use the app. 

Yes my current collection is outdated and sadly all of the back ups on my phone are already versions of the corrupted collection since it synced automatically. I have month old back ups on my pc however those are really outdated but they are still safe.

**Comment by Rafania** [comment]
Hi
I have tried exporting my collection and importing it on the PC in order to fix the problem but it didnt work. It gave me the following errors 
Anki was unable to open your collection file. If problems persist after restarting your computer, please use the Open Backup button in the profile manager.

Debug info:
Traceback (most recent call last):
  File "aqt\main.py", line 477, in loadCollection
  File "aqt\main.py", line 512, in _loadCollection
  File "anki\collection.py", line 54, in _init_
  File "anki\collection.py", line 266, in reopen
  File "anki\rsbackend_gen.py", line 464, in open_collection
  File "anki\rsbackend.py", line 256, in _run_command
anki.rsbackend.DBError: DBError { info: "SqliteFailure(Error { code: DatabaseCorrupt, extended_code: 11 }, Some(\"database disk image is malformed\"))", kind: Other }

I have also tried deleting the collection media.db2 files since i read somewhere that this fixed the same problem for other people but that didnt work either.
I also tried uninstalling anki and re-installing to no avail. 
currently at a dead end would really appreciate some help. Thanks!

**Comment by mikehardy** [comment]
If your database file is truly corrupt, our best info is here: https://github.com/ankidroid/Anki-Android/wiki/Unopenable-collections

**Comment by Rafania** [comment]
I followed the steps and it still didn't work.
https://drive.google.com/file/d/1bNoXrNjGNV7j54iORJP1QQAMlRFNXlEI/view?usp=drivesdk

This is the link to my collection as the steps said to post it here.

**Comment by mikehardy** [comment]
Unfortunately that relies on volunteer time (us downloading / opening / repairing) and at least personally I'm sorry I don't have a lot of free time right now. Perhaps someone else will have time. I can outline really quickly what I would do though: on desktop I would find a sqlite database program and attempt to open it, most of them are able to "repair" (possibly with data loss!! warning!!) sqlite files that have mild corruption. The .anki/.anki2 collection files are in fact sqlite data files. 

This might work https://sqlitebrowser.org/dl/

**Comment by Rafania** [comment]
I have been trying to use it but I amnot sure how it works. I followed a video and opened the collection.anki2 
as database and run integrity check to find 4 errors (posted a pic below)
![Uploading IMG_20210224_172340.jpg…]()
. I then exported the database as sql file and tried to import it but it gave me the following error: 
Error importing data: error in statement 7#: object name reserved for internal use: sqlite_stat4. Aborting execution and rolling back

Can you please tell me how to proceed? And if I'm using sqlite wrong?

**Comment by mikehardy** [comment]
Your image is not actually uploaded, but text of error messages is strongly preferred.
I cannot tell you how to proceed unfortunately, ever corrupt database is corrupt it in it's own unique way unfortunately.
I can say that if you are having trouble running a sql statement (which is what an import of a sql file is doing) then the easiest way to hack your way forward is to remove the offending statement

**Comment by Rafania** [comment]
The 4 errors are:
*** in database main ***
Page 10446: btreeInitPage() returns error code 11
Page 10648: btreeInitPage() returns error code 11
Page 10399: btreeInitPage() returns error code 11
Page 10317: btreeInitPage() returns error code 11

How do I remove the offending statement? By deleting the whole sqlite_stat4 table?

If yes i tried that and I successfully imported the rest. I then saved the new database and didn't know what to do after. So I tried copying it into the AnkiDriod folder and restarting the app but nothing happened.
Was I supposed to do something differently?

**Comment by mikehardy** [comment]
> The 4 errors are:
> *** in database main ***
> Page 10446: btreeInitPage() returns error code 11
> Page 10648: btreeInitPage() returns error code 11
> Page 10399: btreeInitPage() returns error code 11
> Page 10317: btreeInitPage() returns error code 11

That sounds serious but is so low level I have no idea sorry

> How do I remove the offending statement? By deleting the whole sqlite_stat4 table?
> 
> If yes i tried that and I successfully imported the rest. 

Yes, and that sounds like progress

> I then saved the new database and didn't know what to do after. So I tried copying it into the AnkiDriod folder and restarting the app but nothing happened.
> Was I supposed to do something differently?

That is about what I would try, and ideally it would have resulted in things working.
Corrupt databases are just that though: corrupt. I have no idea the extent of data corruption, data loss etc. While you have the database open in a sqlite editor you should be able to see what appears to be reasonable data in there - all as documented here https://github.com/ankidroid/Anki-Android/wiki/Database-Structure
