### ISSUE TITLE
Search card ignore case

### ISSUE THREAD

**Issue by idkw** [ankidroid/Anki-Android#8116]
**Is your feature request related to a problem? Please describe.**
Not a bug but a feature currently not very practical

**Describe the solution you'd like**
When searching for cards, I'd like to be able to ignore the case (all the time via a toggle in the advanced settings). Currently the search performs an exact contains match so if I have a uppercase letter in my word and searching with a lowercase I won't find my cards. This is annoying because I have to type all my search in multiple ways to make sure I have not that card already with a slightly different case (usually the first letter of the first word).

You might say I should write all my cards in lowercase but I already have a huge list of cards and I don't really feel like editing them one by one. Furthermore when downloading other user's collections the problem remains.

**Describe alternatives you've considered**
The workaround is currently to do multiple search with different case which is not very practical and I still can miss some cards and end up creating duplicates, very similar cards

**Additional context**

Searching for "воздух" ("air" in russian) with lowercase return nothing because I have created the card with a leading uppercase В

![Screenshot_20210216-201111](https://user-images.githubusercontent.com/7012331/108110276-5300d900-7093-11eb-931c-afe4d752fe48.jpg)

Searching with a leading uppercase allow to find it
![Screenshot_20210216-201100](https://user-images.githubusercontent.com/7012331/108110333-6449e580-7093-11eb-93ea-6963facf4540.jpg)

**Comment by moqi-Git** [comment]
SQLite only understands upper/lower case for ASCII characters by default. (only support English)

The ICU extension to SQLite includes an enhanced version of the LIKE operator that does case folding across all unicode characters. But Android system only support origin SQLite.

**Comment by idkw** [comment]
Ok couldn't we have a secondary column to store the same date in lowercase just for indexing and search ?

**Comment by mikehardy** [comment]
We will not modify the database in any way that is not already in upstream Anki Desktop, so in general no unless they support it.

It is possible for us to support sqlite extensions - or it was - but with the conversion to a different back-end with pre-packaged Rust I'm not sure that is even an option 

Additionally this is something that others with inflected or accented languages want as well - they want "fully normalized" text searches where they can search without the accents and umlauts etc.

The main point is that this is something to approach Anki Desktop for first https://forums.ankiweb.net/

**Comment by idkw** [comment]
@mikehardy Ok thank you
Is there some ongoing work to at least make the search consistent between anki desktop and android, because currently it is not.

Exemple : 

Searching for "Certificat" (with first letter uppercase) on anki desktop returns lowercase results.

![image](https://user-images.githubusercontent.com/7012331/108888208-74217680-760b-11eb-9af3-c4c6ed2fd15e.png)


But on anki android it doesn't return any results. It only return the results if I search for exactly "certificat" without first letter uppercase.



I'm not sure if its a bug on anki android or if this is something that should be first implemented in anki desktop. In any case I don't have any experience in the project so to me it seems to be issue that will be stuck forever if an experienced maintainer doesn't step in and take on the feature and required bug fix/changes in anki desktop and android from start to finish. On my side I'm hapy to assist with testing but don't know what to do more as a simple user.

**Comment by mikehardy** [comment]
Very interested in that result, I'll reopen this. My previous statement of course implies that if anki desktop does it we do want to conform

**Comment by idkw** [comment]
@mikehardy Sorry I think I was fooling myself

With my example the search is consistent when searching for the french term "Certificat" or "certificat", it returns the cards on anki android and anki desktop in both cases.

However when searching for the russian term "Расписка" or "расписка" it only returns the cards for an exact match (in lowercase here) on both desktop and android.

So the issue might be actually with what @moqi-Git was saying above ? https://github.com/ankidroid/Anki-Android/issues/8116#issuecomment-784071549

In any case my issue remains and even though the behavior is consistent between anki droid and desktop regarding non-latin characters, it seems to be a consistent bug ^^

**Comment by abdnh** [comment]
> With my example the search is consistent when searching for the french term "Certificat" or "certificat", it returns the cards on anki android and anki desktop in both cases.
> 
> However when searching for the russian term "Расписка" or "расписка" it only returns the cards for an exact match (in lowercase here) on both desktop and android.

@idkw 

This is actually the intended behavior. It's documented in the desktop manual:
> Standard searches are case insensitive for Latin characters - a-z will match A-Z, and vice versa. Other characters such as Cyrillic > are case sensitive in a standard search, but can be made case insensitive by searching on a word boundary or regular expression (w:, re:).

See https://docs.ankiweb.net/#/searching?id=simple-searches
