### ISSUE TITLE
Images can't display[Bug]

### ISSUE THREAD

**Issue by hoangvuminhthu** [ankidroid/Anki-Android#8118]
**Is your feature request related to a problem? Please describe.**
I ooen my ankidroid and lots of images can't display. That's really bad
**Describe the solution you'd like**
pls help me

**Describe alternatives you've considered**

**Additional context**
![Screenshot_20210218_232619](https://user-images.githubusercontent.com/79295116/108452167-a1cc8f80-729a-11eb-8baa-84ed689d0f3e.png)

**Comment by mikehardy** [comment]
Hi there! Probably this: https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

We can reopen if that doesn't clear it up - but card content will be specific to your cards, they are your content, so something about the card content will need to change it is not going to be an AnkiDroid problem normally
