### ISSUE TITLE
 "cloze-only:Text" not working

### ISSUE THREAD

**Issue by ionx711** [ankidroid/Anki-Android#8123]
The "cloze-only:Text" filter on a cloze note type is not working

**Comment by mikehardy** [comment]
Hi there!
You skipped all the information we ask for, that makes it difficult to help.
We need your version information (https://docs.ankidroid.org/help.html)

Could you provide the exact steps from app start that show the problem?

**Comment by ionx711** [comment]
AnkiDroid Version = 2.14.3

Android Version = 10

ACRA UUID = 794f3d42-3015-47d8-87bd-624d3dbb7b98

Scheduler = std2

Crash Reports Enabled = true

**Comment by ionx711** [comment]
I don't know how to properly say it. But it's an app function I usually use with TTS in cloze notes, when I click show answer it will read only the cloze word/s. It works on the anki pc version, but on ankidroid it reads the whole note.

**Comment by ionx711** [comment]
I quoted from https://docs.ankiweb.net/#/templates/fields

"On a cloze note type, you can make Anki read only the elided sections using the cloze-only filter, like so:
{{tts en_US:cloze-only:Text}}
The cloze-only filter is supported in Anki 2.1.29+ and AnkiMobile 2.0.65+."

**Comment by rye761** [comment]
This is not implemented in AnkiDroid yet. See #7063

**Comment by Arthur-Milchior** [comment]
Closing this one as duplicate of the other
