### ISSUE TITLE
[Bug]Silent uninstall ist not silent, it ask a Data-Backup Question

### ISSUE THREAD

**Issue by zimttat** [ankidroid/Anki-Android#8127]
###### Reproduction Steps

1. try to uninstall anki 
2. question about databackup block uninstall process
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
This is not a feature of the app, this would be a feature of the mobile operating system.

Apps do not get any notification whatsoever from the operating system during uninstall, and no app code has the ability to run even if it wanted to
