### ISSUE TITLE
Prioritizing translations

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8131]
I believe we should improve the way to deal with strings, so that translators know which of the 1242 they should proritize. Probably create a user story, check which are the strings shown to the user in this story, and allow the translators to check all strings belonging to this story that remains to translate. 

### Example of a story 
In my opinion, such a story would contain:
* Creating an account
* initial syncing
* importing a downloaded a deck
* opening the deck
* Reviewing
* clicking on all buttons present by default (no long click, so no alt text. Not editing)
* Ending the daily reviews
* Syncing again

We could state that we have a minimal viable product in language LANG if all of those strings are translated. A user could indeed use it, even if they would not have access to all features and debugging would be harder.

### Eample
To give a more concrete example: "Correct answers on mature cards: %1$d/%2$d (%3$. 1f%%)" is probably less used, more complex to understand without a good knowledge of the app, and less blocking to the user than "Hard". The translators should be able to quickly figure out this difference, so that they can start on things that really matters.

# How to do it

If you agree, let's now discuss how to do it, because that's not trivial.

## Tag

The easiest solution for developers would be to tag strings in crowdin. Then we can tell translators to seach for this tag. That's really not easy. There is no way to easily see how many strings remains in the first story in each file. Filtering by tag is marked as an advanced options. So that probably won't help much

## Files

We could stop using those 18 files. I don't know about you, but I've never found them really useful. If I'm looking for a string, I use android studio search feature, I never look for the very file content. And ids are used as R.string.foo, so it will not matter if file change. Except for `git blame` purpose, which I know is quite important for David at least.
Instead, I'd find more useful to have a file 01-Very-Important.xml which contains the minimal set of strings for the user story. A file 02-Important.xml which contains strings which are usually used, etc...

I perfectly now that this is not something that is normally done. A usual translation sync will totally break here. However, that's only a limitation of our sync tool and not a crowdin limitation at all. We can totally upload translations in all languages simultaneously, so that we keep track of existing translations. 
Here is a suggestion about how to do that:
* We create files with the ids of the very important strings, the important strings, etc.. for example in json, so that's easy to parse
* We create a file which create 01-VERY-important in all languages and put in it the xml related to each strings in the json file
* We sync from crowdin
* We apply the script
* we sync to crowdin in all languages

I'll first need to run the test https://github.com/ankidroid/Anki-Android/pull/8130
and maybe another one.

Please let me know your thoughts. More specifically, I want to know:
* whether you believe this notion of stories is worth pursuing
* whether you find that the solution I give would be acceptable.

Mainly because it really matters if the first answer is yes and the second is no that we find another solution and that we don't just stop the project because the solution is not the good one

**Comment by mikehardy** [comment]
The rule used to be that files 01 and 02 were the highest priority 
Translate those and you cover like 95% of use cases and have a fairly valid translation, it used to be the standard for including a language

It is supposed to be really easy like that? I am not in favor of highly organized structures as maintaining high states of organization requires effort (definition of organization style, like this, training people on it when they make changes or you prepare them to be able to review things etc).

If it is no longer the case that the 01/02 files are really only the most necessary strings, we should organize the 01 and 02 files (or maybe just 01, so it's even easier to communicate to translators) that 01 must be translated. The rest can be organized however, in my opinion, "story" importance, functionality area etc

Here's a thought: what does moving strings around between files (regardless of how we do it) do to existing translations?

**Comment by Arthur-Milchior** [comment]
Great, I believe we mostly agree about the big picture.

Concerning your question, we'll know as soon as you merge https://github.com/ankidroid/Anki-Android/pull/8130
I should note that this only touch the "don't translate" file whose only purpose is to allow us to do such test.

I can't do the test myself for two reasons. First:
* I don't have the API key
* I would not want to send API request without a second person looking at the code
