### ISSUE TITLE
Sound doesn't work after synchronization

### ISSUE THREAD

**Issue by MelnikovAleksey** [ankidroid/Anki-Android#8133]
AnkiDroid Version = 2.14.3

Android Version = 9

ACRA UUID = 6b4571cd-5809-456f-9f76-50dec95f57ce

Scheduler = std

Crash Reports Enabled = true

**Comment by mikehardy** [comment]
Hi there!
Our issue template includes this:

>  I have checked the manual and the FAQ and could not find a solution to my issue

The FAQ includes this https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid

It should help?

**Comment by 2tanayk** [comment]
@MelnikovAleksey is this still an issue,it would be if you provide more details so that me or any other developers here can help 😄
