### ISSUE TITLE
AnkiDroid 2.14.3 handles MathJax differently than Anki 2.1.41 [Bug]

### ISSUE THREAD

**Issue by cpettitt** [ankidroid/Anki-Android#8146]
###### Reproduction Steps

1. Create a card with ket notation (comes with MathJax 3 baket extension) in Anki 2.1.41:

```\(\ket{0}\)```

2. Sync with Anki web
3. Observe incorrect ket notation rendering (MathJax 3 braket extension seems to not be loaded)

###### Expected Result

Card should look like this (works on desktop):

|0>

###### Actual Result

\ket0

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by cpettitt** [comment]
I joined the beta program but do not seem to have gotten a new version. It still says version 2.14.3.

**Comment by mikehardy** [comment]
There are currently not new betas, but there are quite a few alphas - if you also sign up for the google group for alpha delivery, the play store will start delivering alphas https://docs.ankidroid.org/manual.html#betaTesting

**Comment by NicoWeio** [comment]
> I joined the beta program but do not seem to have gotten a new version. It still says version 2.14.3.

In case you didn't see it: You can also download the latest alpha APK from the [releases page](https://github.com/ankidroid/Anki-Android/releases) on GitHub.

**Comment by dorrin-sot** [comment]
What api version are you running?
I can't seem to be able to reproduce it with my emulator
