### ISSUE TITLE
[Bug] Colors not displaying properly

### ISSUE THREAD

**Issue by ElnuDev** [ankidroid/Anki-Android#8149]
###### Reproduction Steps

1. Create a deck with the following on the front of the card:

```HTML
{{Front}}

<strong>
<p><span style="color: red">red (keyword)</span>, <span style="color: #ff0000">red (hex)</span></p>
<p><span style="color: lime">lime (keyword)</span>, <span style="color: #00ff00">lime (hex)</span></p>
<p><span style="color: blue">blue (keyword)</span>, <span style="color: #0000ff">blue (hex)</span></p>
</strong>
```

And the following on the back of the card:

```HTML
{{Front}}

<strong>
<p><span style="color: red">red (keyword)</span>, <span style="color: #ff0000">red (hex)</span></p>
<p><span style="color: lime">lime (keyword)</span>, <span style="color: #00ff00">lime (hex)</span></p>
<p><span style="color: blue">blue (keyword)</span>, <span style="color: #0000ff">blue (hex)</span></p>
</strong>

<hr id="answer">

{{Back}}
```
2. Open the deck in Anki. The colors should all display properly. (see Expected Result section)
3. Sync.
4. Open the deck in AnkiDroid. The colors should not display properly. (see Actual Result section)

###### Expected Result

![Screenshot from 2021-03-07 11-31-54](https://user-images.githubusercontent.com/9874955/110252157-ed3c9a00-7f38-11eb-9020-763eecc0a162.png)

###### Actual Result

![image](https://user-images.githubusercontent.com/9874955/110252506-ac458500-7f3a-11eb-9f13-ecc4395eea02.png)

###### Debug info

AnkiDroid Version = 2.14.3

Android Version = 8.0.0

ACRA UUID = 95885102-0d8a-45a5-9bd6-f0e93cef28c7

Scheduler = std

Crash Reports Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! This is in the FAQ, at the end, as a link to advanced formatting

We auto-invert colors in night mode. It's a feature for most, that is a bug for some. If it is a bug for you, it is under your control to alter: https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#customize-night-mode-colors

**Comment by ElnuDev** [comment]
Thank you! Sorry I missed that. Adding
```CSS
.card.night_mode { }
```
to the card fixed the issue. Though, I think it would be nice to have an option in the settings to disable the inverter instead of having to go into the CSS.

**Comment by mikehardy** [comment]
That could be a nice feature, if you'd like to propose a PR for it as a preference in advanced settings we could merge it
