### ISSUE TITLE
[Bug] Empty white space above HTML Tables in Ankidroid

### ISSUE THREAD

**Issue by peterj71** [ankidroid/Anki-Android#8152]
###### Reproduction Steps

1. Create HTML table in a field (use my table.html sample if you like)
2. View it perfectly in Anki desktop
2a. Double check that table displays perfectly in Chrome as well
2b. Triple check HTML in the w3 validator (note there are some warnings for using old HTML in my example but nothing significant and it displays perfectly in Anki desktop and Chrome)
3. View it and cry in Ankidroid on tablet and mobile

###### Expected Result

Should appear identically in both Anki desktop and Ankidroid

###### Actual Result

Empty white space appears above the tables in Ankidroid, sometimes so much white space that the table is forced down and off the visible screen area, requiring scrolling to find it

![Screenshot_Chrome](https://user-images.githubusercontent.com/15965443/110422916-4997e900-80f4-11eb-8138-a975ff045034.png)
![Screenshot_Desktop](https://user-images.githubusercontent.com/15965443/110422920-4ac91600-80f4-11eb-9764-ee7e16c5de3e.png)
![Screenshot_Mobile](https://user-images.githubusercontent.com/15965443/110422922-4b61ac80-80f4-11eb-939e-075e3ef26ab0.png)
![Screenshot_Tablet](https://user-images.githubusercontent.com/15965443/110422926-4bfa4300-80f4-11eb-96e5-c71cd06416f4.jpg)
[table.html.txt](https://github.com/ankidroid/Anki-Android/files/6106047/table.html.txt)

###### Debug info

Debug info from Android 10 mobile below, but issue is identical on my Android 9 tablet, so it's definitely Ankidroid specific

AnkiDroid Version = 2.14.3
Android Version = 10
ACRA UUID = b0a45792-702b-4092-ac2b-7f13a774c8de
Scheduler = std
Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum --- similar reported on Google forum and it was waved off as user error by Axel Merboldt, however I can reproduce it consistently, see attached screenshots
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Interesting, I wonder if some CSS rule is being applied? https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting

You can inspect the HTML WebView if you plug your device into your computer, enable debugging for the device and use Chrome webtools I think: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by peterj71** [comment]
Hi Mike, thanks for the suggestions. I setup debugging and at the same time upgraded to last night's 2.14.6 release from the Play store, and hey presto the whitespace above my tables is already gone?!?! 8-) 

There's a little redundant whitespace under the tables but that doesn't affect me, so for the moment I'll close this ticket if I can - if I can't then please close/hold it on my behalf, thanks!
