### ISSUE TITLE
AnkiDroid Directory is inaccessible

### ISSUE THREAD

**Issue by asbaran** [ankidroid/Anki-Android#8156]
Anki doesn't work on my newer Samsung Note 10 plus all of a sudden and displays an error Ankidroid Directory is inaccessible when I didn't even make any changes. Meanwhile my older Asus Zenfone Max has no issues accessing anki.

**Comment by david-allison-1** [comment]
Hi, this is likely an issue with the `Advanced - AnkiDroid Directory` setting being restored from a device backup from another device.

Could you set this to: `/storage/emulated/0/AnkiDroid` and see if this fixes the issue?

**Comment by asbaran** [comment]
Hi David,

It worked for me. Thanks so much for your help.

Kind regards,
Vlad
