### ISSUE TITLE
Blocker: Disable hardware rendering in WebView Activities for Android 8/8.1

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8160]
###### Reproduction Steps

Refer to: #7369 - Reviewer and Changelog (both WebViews) have flicker / render issues *only* on Android 8/8.1 real devices (not emulators)

Refer to: #8154 - where *all* Reviewer-related Views are switched to software render using layout overrides

###### Expected Result

That layout files are not duplicated, but Android 8/8.1 have software render for WebView Views such that they render correctly

###### Actual Result

We have the layouts duplicated 3 times, once from minSdkVersion to API25, once for API26+API27, and once for API28 and higher

Also, the Changelog is not software render yet.

###### Proposed Solution:

You can disable hardware in these ways:

- at the view level in layout files (leads to duplication of layouts, this issue)
- at the activity level in AndroidManifest.xml (this is application-wide and cannot be tuned per-API
- at the view level programmatically

The goal here is:
- determine the full set of views that need to be set to software render
- programmatically set them to software render inside a test for API26/API27
- add a preference (as noted would be useful in #8165) to use hardware render anyway

Open questions:
- does changing this programmatically work? (it should, but needs testing)
- can the set of Views set to software render be smaller than the set I changed in #8154 (maybe, would need testing)

###### Debug info

This is not really debuggable as none of the core contributors have real devices that show the probem though @jbuschtoens was instrumental in the hotfix I put in release-2.14 as a responsive tester that reproduces it every time, with reliable first reports on failure and success that were invariably reproduced by others.

**Comment by mikehardy** [comment]
Noting this is a blocker for v2.15 release. If we release v2.15 without doing either this, or cherry-picking #8154 to main dev branch, Android 8/8.1 will have render issues during review again, breaking review for many users.

**Comment by danishjamal104** [comment]
Hey @mikehardy , so what is actual cause of this flicker /  render issue ?

**Comment by infinyte7** [comment]
@mikehardy The buttons and card count not appearing due to webview. So, I have created JS Addon for adding button and card count using JS API.
It is not good solution but if user use hardware rendering with the JS Addon will be helpful or not?

https://github.com/infinyte7/Anki-Custom-Card-Layout/tree/master/JS%20addon#2-button-and-card-count-addon

**Comment by mikehardy** [comment]
@infinyte7 that could help, but we need to solve the underlying problem first I think

@danishjamal104 no idea, I don't have an Android 8/8.1 hardware device to test with, and could never reproduce it myself - when it shows up, it does not matter what version of AnkiDroid is in use back to really old ones (2.10.x at least) so it is some sort of operating system or WebView change :shrug:
