### ISSUE TITLE
Going back to deleted card [Bug]

### ISSUE THREAD

**Issue by Heineken** [ankidroid/Anki-Android#8161]
###### Reproduction Steps

1. practice until a reverse card is displayed
2. edit note
3. change note type from 2-way to 1-way type, thus deleting the reverse card
4. save -> deleted card is still displayed (1. minor bug)
5. answer and flip to next card 
6. Go back -> Error is displayed
7. Trying to restart the affected pile triggers the error again and offers DB check, which resolves the problem eventually

###### Expected Result
The deleted card should not be shown, then I couldn't go back to it either.

###### Actual Result

Caught error.

###### Debug info
AnkiDroid Version = 2.9.4

Android Version = 7.1.1

ACRA UUID = 500618ce-5823-40ba-b36c-feac66c74651

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by kartikeysaran** [comment]
Can i work on this issue ?

**Comment by david-allison-1** [comment]
@kartikeysaran Sure!

**Comment by kartikeysaran** [comment]
Hey @Heineken can you please attach a video file for a clear understanding of the issue :)

**Comment by kartikeysaran** [comment]
> Hey @Heineken can you please attach a video file for a clear understanding of the issue :)

Performing the Bug reproduction steps

**Comment by Heineken** [comment]
Hey kartikeysaran,
Great that you are motivated to tackle this issues.
Sorry, I'd rather not bother recording and uploading a MB sized video of a problem that can be described in a few bytes. Which I did.
Is there anything unclear?
Have you tried to reproduce the problem?

**Comment by mrudultora** [comment]
@Heineken Unable to reproduce (card is getting deleted).

**Comment by kartikeysaran** [comment]
> @Heineken Unable to reproduce (card is getting deleted).

Same in my case the card were deleted successfully

**Comment by david-allison-1** [comment]
Also can't repro. @Heineken , could you fill out the `Debug info` section of the issue to ensure we're testing against the correct version. Thanks

**Comment by Heineken** [comment]
Hey guys, thanks for your effort and sorry for not having posted the debug info right away. I did it just now.

To be clear, the problem is not that the card wasn't deleted, it was. Otherwise there wouldn't be that error, which, to my understanding, occurs when the app tries to access the deleted card.

**Comment by mrudultora** [comment]
@Heineken In the issue you mentioned that deleted card is still displayed. So, I meant that when I deleted the card, it wasn't displaying. Just followed the steps you told, but still unable to reproduce.

**Comment by david-allison-1** [comment]
@Heineken You're on a version of AnkiDroid from well over a year ago. I've spent most of 2020 fixing bugs.

Would you consider upgrading to 2.14.6?

**Comment by Heineken** [comment]
Hey David,
Thanks for the info. I avoid Google Stuff and rely on FDroid to keep my apps up to date. I know it lags behind, I didn't think a whole year.

I don't verify the version numbers manually. I should have before filing her, though. Sorry guys!

Anyway, I'm impressed by the response!

**Comment by david-allison-1** [comment]
Very welcome! 

@Heineken 

Do check out our changelog, just to ensure you don't miss anything: https://docs.ankidroid.org/changelog.html

F-Droid should have an auto-update function somewhere, other users definitely do use it. releases lag behind Google Play by a few weeks worst case (down to their infra), but it's definitely not years

**Comment by Heineken** [comment]
My FDroid does check for updates automatically and I install all of them every one in a while. It claims to have updated AnkiDroid 3 days ago. I don't remember, anyway, the only version that is offered is 2.9.4.

I'll update manually via browser download.

**Comment by Heineken** [comment]
I couldn't update without uninstalling first, because of a conflict with an packet installed under the same name. So, for FDroid it's a different app. 

Once had the same issue when QuickDic was forked. Looks like I missed something big here.

**Comment by david-allison-1** [comment]
If you have the time, could you raise an issue/support query on F-Droid's side and keep us in the loop in case there's anything that we need to do - we're definitely on 2.14.6 (latest) on the main F-Droid page: https://f-droid.org/en/packages/com.ichi2.anki/

https://gitlab.com/fdroid - unsure about where to submit an issue. I don't believe we were forked/changed signing keys (@mikehardy should be able to confirm)

Android 7.1 is well within the versions that we support

**Comment by Heineken** [comment]
Hey David,

I do have the time, but I hesitate, because I got the update error when trying to install the apk independently from the FDroid app. I downloaded it from fdroid.com, though.

I don't really know how this signing works. Is the apk on FDroid the same as on Google Play or is is signed for/by FDroid?
AFAIK, an app installed via Google Play is recognized and can be updated by FDroid. Not vice versa, though.

**Comment by mikehardy** [comment]
Fdroid builds from source and signs it themselves. I don't think there is any cross compatability between installs as the certificates used to sign the apk must match. I also maintain an apk updating library for react-native (https://github.com/mikehardy/react-native-update-apk/) so I'm pretty sure on these points as I've tested all scenarios (and failed plenty, while learning) 

However if you uninstall and then install fresh it won't matter

I didn't delve into whatever this problem is, those are just apk updating and signing facts as I understand them

**Comment by Heineken** [comment]
Soooo, I filed the bug [here](https://gitlab.com/fdroid/fdroidclient/-/issues/2175).

I realized the issue may have been caused by TitaniumBackup, which I use to migrate between phones (, which I have to do way too often, clumsy me).
