### ISSUE TITLE
Remove "experimental" from v2 scheduler setting, default to v2 for new / empty installs

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8162]
###### Reproduction Steps

1. Use AnkiDesktop 2.1.42 or higher
2. Attempt to sync with AnkiDroid from a default install

###### Expected Result

Sync works as expected

###### Actual Result

Error message about new scheduler?

(this came from a play store review comment)

Apparently 2.1.42 (at least, maybe earlier?) of Anki Desktop turns on V2 scheduler by default, whereas AnkiDroid is still using V1 as default.

- I think the V2 scheduler should definitely have the "EXPERIMENTAL" tag removed, it is not experimental anymore?
- I think new users should get V2 by default

What I'm not sure about, how to handle existing V1 users.

- Perhaps on startup / version upgrade we can show a dialog saying they are on the V1 scheduler and should update to V2 as it is now the default. Link to a WIKI page, plus outline the steps (make sure one side of sync has all data up to date, toggle V2 scheduler, full sync to AnkiDroid from up to date side, verify all other clients are set to V2, sync all other clients) ?

**Comment by dae** [comment]
Assuming the new timezone code will be available as well, defaulting to v2 with the new timezone code enabled would be good. For existing users, you may want to defer to the upgrade prompt in the computer version for now, as 2.1.41 introduced new code for switching from v1→v2. The current code inside AnkiDroid is based on older logic that resets all learning cards and empties all filtered decks, so if doing the upgrade on the device you'd need to port the new update logic to avoid resetting people's progress.

**Comment by kartikeysaran** [comment]
Can i work on this ?

**Comment by mikehardy** [comment]
@kartikeysaran no, this is not available for work by anyone but core contributors / maintainers at the moment. It requires careful thought, investigation, and planning across the ecosystem to make sure we get it right.

**Comment by puelp** [comment]
That's reassuring to hear.

Please take all the time you need to make AnkiDroid 2.15 work seamlessly with Anki 2.1.41/2.1.42's new default scheduler!

**Comment by mikehardy** [comment]
Going to focus this one and get some of it done for 2.15 in order for the widest swath to get timezone syncing fixed etc:

- remove the experimental tag from the v2 scheduler label in advanced settings - I think this will actually require a *new* string (retiring the old one) so that translators know to re-translate
- make v2 the default **for new installations** - no intention to auto-convert or even ask existing users at this point, but it seems safe on first install to make v2 the default? The only hangup I can think of is for people that are AnkiDroid-only but sync to AnkiWeb, that just install on a new device and sync a schedv1 collection down. How will this affect them? needs testing

Seem reasonable?

**Comment by dae** [comment]
Sounds good, just a reminder that we'll want to make sure the initial setup also enables the new timezone code, and not just the new scheduler. Should not affect scheduling, as a full sync is required when moving to a new device in any case.
