### ISSUE TITLE
[Bug] Type answer into card

### ISSUE THREAD

**Issue by SubhamJena** [ankidroid/Anki-Android#8163]
Hacker's keyboard app defaults to all UPPERCASE (with autocapitalisation on) while typing even after repeatedly turning off the uppercase toggle in 'Type answer into card field'.
Wasn't an issue with previous Ankidroid releases.
No issue with Samsung keyboard.

Hacker's keyboard v1.40.7
AnkiDroid 2.14.6

**Comment by mikehardy** [comment]
That is strange, I don't recall anything in the area changing recently.
Can you double-check a previous release you knew it worked on? You can install parallel builds from the releases page side-by-side with your current install for quick testing, for example parallel A from here: https://github.com/ankidroid/Anki-Android/releases/tag/v2.14.3

**Comment by SubhamJena** [comment]
I am afraid:
• Tried installing the previous versions of Ankidroid. But the problem persisted.
• Can't blame Hacker's keyboard because neither did I mess with it nor updated it.
• What I did was updated few days back to Anki 2.1.40 and updated AnkiDroid twice upon its two recent releases.

*****
The problems looks specific to some devices:
Freshly installed the apps (both Hacker's keyboard & AnkiDroid) on two other devices:
1. Galaxy A20 :- No issues
2. Infinix hot 8 :- Same problem as mine.

In my device tried clean install,
> once importing that specific deck exclusively.
> once more by just syncing from ankiweb account. But no luck.

Certain clarifications:
There doesn't seem to be any issue with native Basic(type in answer)
The problem lies with a custom Cloze card type from https://github.com/qwiglydee/anki-interactive.

**Comment by SubhamJena** [comment]
I even see the WebView renderer crashes while reviewing these cards. I have reviewed these cards earlier but it was fine then. May be in some way My UPPERCASE issue be related to the issue raised by you <a href=https://github.com/ankidroid/Anki-Android/issues/8160#issue-827760815>here</a>

**Comment by mikehardy** [comment]
I can't see how this is an AnkiDroid problem, but I could be wrong. I would investigate Hacker's keyboard perhaps, their release notes etc
