### ISSUE TITLE
Adding dark mode in custom tabs

### ISSUE THREAD

**Issue by mrudultora** [ankidroid/Anki-Android#8164]
**Is your feature request related to a problem? Please describe.**
This is not a problem as such. But, the custom tab appears bright even in dark mode. I am using the app in dark mode and suddenly much increase in brightness doesn't seems good.

**Describe the solution you'd like**
As, custom tabs support dark mode in toolbar, navigation bar and also some reduced brightness (complete dark mode is not supported in custom tabs), we can use that feature.

**Comment by mrudultora** [comment]
If it's a valid change, I would like to work on this.

**Comment by mrudultora** [comment]
@Arthur-Milchior @mikehardy Can I work on this.... ?

**Comment by Arthur-Milchior** [comment]
Hi,

I beg your pardon, but I've no idea what is "custom tab", so I don't even understand the request. Can you maybe share a screenshot of current version and what you'd like to obtain.

I don't expect anybody else to be considering this, at least I've not heard about it, so if this change make sens and do not break other people use of the app, it would be great to have you work on a topic you care about.
Is it GSoC related?

**Comment by mrudultora** [comment]
Attaching a screenshot of chrome custom tabs..
![Screenshot_2021-03-11-13-50-58-121_com.android.chrome.jpg](https://user-images.githubusercontent.com/65870389/110757973-fd72b300-8271-11eb-988b-7f65c700e7bb.jpg)

Here, the app is in dark mode but you can see that toolbar, navigation bar and the content is bright. So, as a user and developer I was asking that can I add dark mode here. Chrome custom tabs support dark mode for toolbar, navigation bar. The content will not be dark but will have a reduced brightness.

@Arthur-Milchior No, it's not a GSOC related topic. I hope you understand the above points ;-)

**Comment by mrudultora** [comment]
@Arthur-Milchior I would also suggest one more change. If you open changelog in dark mode the webview renders it in bright mode, but at the same time if you open About Ankidroid it follows both dark mode and bright mode. So, I think we should do this change for changelogs also. Should this be opened as a separate issue ?

**Comment by david-allison-1** [comment]
Sounds good to me, as long as it'll be compatible with API levels that don't support system-level night mode.

**Comment by mikehardy** [comment]
Next alpha will have it fixed! Thanks @mrudultora !
