### ISSUE TITLE
[Bug] 2.14.6 performance

### ISSUE THREAD

**Issue by Arx724** [ankidroid/Anki-Android#8165]
Hey, I've been using ankidroid for a good year now and just ran into an issue. Today's update update seems to have killed in-card performance for me. Everything is smooth in menus etc, but while reviewing it's much less responsive (particularly noticeable when scrolling).
I'm using ankidroid v2.14.6 on a Moto G5 running Android 8.1.0, which I realize is pretty old but it ran fine until today. I'm not sure if I'm missing a new menu option or something that I should be turning on/off, but performance remains terrible even after restarting my phone.

Thanks in advance for any help!

**Comment by mikehardy** [comment]
You must upgrade your Android operating system, or use 2.15-alphas unfortunately.

You would not believe the trouble we had isolating a render issue on Android 8 / 8.1 only, where if you use the default render pathway (hardware render) the reviewer is completely broken for a large percentage of Android 8/8.1 users. #7369

So we had to disable hardware render for Android 8. #8154 

If that *did not* affect you, please feel free to use a parallel version of 2.14.3 (prior to these changes), or you can hop on the 2.15.x alpha track where I have not yet implemented the software-render workaround.

For 2.15.x I am exploring a different workaround to the problem which will be programmatic #8160. I am going to resolve this issue but I will note on that one that the proposed solution should have a preference marked as "potentially dangerous" for Android 8/8.1 users to use hardware rendering anyway, and if they have problems, it's on them

**Comment by mikehardy** [comment]
(how to get on beta - and then enable alpha build delivery - track from play store: https://docs.ankidroid.org/manual.html#betaTesting)
