### ISSUE TITLE
Change in the icon colors in Help dialog box

### ISSUE THREAD

**Issue by haran2248** [ankidroid/Anki-Android#8166]
**Is your feature request related to a problem? Please describe.**

The Help dialog box icons has a monotonous color of white and grey.Which makes the app dull and lifeless

**Describe the solution you'd like**

The colour of the icon adjacent to the item header can be made blue.So as it adds a little bit of joy and color to the UI 

**Describe alternatives you've considered**

All the adjacent icons in the dialog box near to the item header can be shifted to the theme color of the app which is blue and white

**Additional context**

![WhatsApp Image 2021-03-11 at 01 48 44 (2)](https://user-images.githubusercontent.com/56928954/110692831-cc13cc00-820c-11eb-96f5-4435f5ce1c26.jpeg)
![WhatsApp Image 2021-03-11 at 01 48 44 (1)](https://user-images.githubusercontent.com/56928954/110692837-cd44f900-820c-11eb-82b2-c4bf7098dbb6.jpeg)
![WhatsApp Image 2021-03-11 at 01 48 44](https://user-images.githubusercontent.com/56928954/110692844-ce762600-820c-11eb-9cb4-0d5ebf0034fa.jpeg)

By changing the icon colors the UI of the app becomes more user friendly

** Edit by Arthur**
Removed the description of the sections

**Comment by haran2248** [comment]
@Arthur-Milchior @mikehardy Can I work on this issue?

**Comment by Arthur-Milchior** [comment]
I've mostly no opinion about it. As a suer I want those menus not to get in the way, I do what I've to do and am fine with them being lifeless... but on the other hand I use text interface everyday and love when I can avoid UI altogether, so probably not a good idea to think about what I want.

I've mostly no opinion about it, would be interested to see what it would be like to have the icons in blue, and if neither @david-allison-1 nor @mikehardy object, that's fine with me

**Comment by danishjamal104** [comment]
Hey @haran2248 , do checkout the margin/padding of the items too, as it is not following the material guidelines, to be specific the options are too much left oriented and their is a false margin in bottom, what do you suggest @Arthur-Milchior ?

**Comment by Arthur-Milchior** [comment]
I'll be honest, I've no notion of UX so I'll defer my trust to:
* guidelines
* automated best practice tools, in particular for accessibilities.

I clearly would be interested in a link to the specific rules we do not follow, so that I can also educate myself here. 
I'd note that this should probably be in a separate request, as I assume that color and position can be changed independtly

**Comment by haran2248** [comment]
> Hey @haran2248 , do checkout the margin/padding of the items too, as it is not following the material guidelines, to be specific the options are too much left oriented and their is a false margin in bottom, what do you suggest @Arthur-Milchior ?

Ohh makes sense I will cover that in another isssue

**Comment by haran2248** [comment]
> I'll be honest, I've no notion of UX so I'll defer my trust to:
> 
> * guidelines
> * automated best practice tools, in particular for accessibilities.
> 
> I clearly would be interested in a link to the specific rules we do not follow, so that I can also educate myself here.
> I'd note that this should probably be in a separate request, as I assume that color and position can be changed independtly

How about I make a PR for this issue and you let me know if it makes sense?With respect to The User Interface and color coding,Since the theme has a mix of blue,white and black I thought it would be smart to bring that color coding uniformly
