### ISSUE TITLE
[Bug]Activity losses its state whenever we change theme(Night Mode to Light Mode)

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#8170]
###### Reproduction Steps

1. Go to Study
2. Clicked on show answer
3. Change theme from hamburger menu (switch on/off night mode)

###### Expected Result
Activity Should Keep Showing Answer .

###### Actual Result
Activity losses its state and answer layout gets invisible again.

###### Debug info
AnkiDroid Version = 2.14.3

Android Version = 10

Scheduler = std2

Crash Reports Enabled = true

**Comment by Bbiswabasu** [comment]
I would like to work on this

**Comment by Akshay0701** [comment]
what if we navigate activity to deck page after changing theme, will that resolve null data issue?

**Comment by mikehardy** [comment]
Duplicate #4035
Please search issues list (open and closed) prior to logging issues
