### ISSUE TITLE
Make randomizing new card order faster

### ISSUE THREAD

**Issue by jdpopkin** [ankidroid/Anki-Android#8172]
**Is your feature request related to a problem? Please describe.**
Switching my main deck from "show cards in random order" to "show cards in order added" and back again takes a long time on my phone. I've never rigorously timed it, but it seems like each of those operations takes about ten seconds. I do this every once in a while, so it's pretty annoying; if it were faster I'd probably do it every day. (More details re why at the bottom of this post.)

_Why is it slow?_
Changing the deck-order fires off a couple of queries for every card in your deck, not just every _new_ card in your deck. For my main deck, which has like 17k total cards, this is slow. This is frustrating for me because I typically have less than 200 _new_ cards.

**Describe the solution you'd like**
I would like this to go faster. I think it's doable.

The code that gets called when you choose to show cards in {non,}random order looks like it avoids actually _updating_ any cards that aren't new. If that's true, maybe we just have to update the queries in `SchedV2.randomizeCards` and `SchedV2.orderCards` to do that filtering up front instead.

I have a commit where I do this (I'll make a pull request soon), and it seems faster than the status quo. It seems to work all right with my deck in my emulator. That said, Anki has a ton of features and I absolutely would not notice if my change had broken something.

**Describe alternatives you've considered**
I could split my main deck into smaller decks, I could manually rearrange the new-card-ordering, or I could be more patient.

**Additional context**
Two parts - possible reasons for skepticism that what I'm proposing will work, and more explanation re why I want to do this regularly.

**Reasons for skepticism**
_"New" card definition might be subtler than I think_
`SchedV2.sortCards` checks `type = Consts.CARD_TYPE_NEW` and `queue = Consts.QUEUE_TYPE_NEW` separately. If those actually aren't equivalent, I'm less confident my change is safe. Maybe we could query for all cards where (type = new or queue = new) and pass those in instead?

_Inconsistent with desktop_
I don't know any Rust, but as far as I can tell Anki's doing roughly the same thing on desktop - it [passes a list of card-IDs to sort without any up-front filtering by new-ness](https://github.com/ankitects/anki/blob/a0c47243b648a42f0f1a4a2c10c8b8495a0cfee6/rslib/src/scheduler/new.rs#L165). So we might not want to mess with this behavior.

_Broken test_
`SchedV2Test.test_filt_keep_lrn_state` is failing on my branch when I run tests locally. It also fails for me on `master`, so maybe it's just an environmental issue. But maybe I'm not cleaning/rebuilding properly.

_Too weird a use-case_
I'm not sure how many other people care about this problem, and maybe it's not worth fixing. I'll spend the rest of this post explaining why I do this.

**Why I care about this**
_Why I prefer random order_
I add cards in large blocks of related material - maybe I'll spend a couple hours on Duolingo one day, maybe I'll import a bunch of trivia questions from some CSV another day. But that isn't how I want to actually learn them. I'd prefer a roughly even distribution of language-cards and trivia-cards each day, but it isn't convenient to alternate between the two when adding cards. I know I can also manually rearrange the order of my new cards to get the mix right, but that's pretty fussy. I'd rather just randomize and add more language cards whenever there are too many trivia cards in the mix (or vice versa).

_Why I re-randomize instead of just leaving the deck in random order_
I haven't seriously looked into the code for this, but it seems like when you randomize the order of new cards, each new card gets assigned a random number, and Anki shows new cards in order based on that number. (Based on `Collection._dueForDid` I think this is roughly right, and that the number-range is from 1 to 1000?) So if you never empty your queue of new cards, a card that's unlucky enough to get assigned 990 will basically never be shown - it will only be shown if /every/ new card left in the deck has been assigned 990 or higher. In practice, that means that random order favors new cards - your old cards end up being disproportionately "unlucky" by natural selection.

I don't think there's any simple way to avoid that. The random-ordering in Anki works well enough - it just means I have to re-shuffle every once in a while. Which is fine - I just wish it were a little faster 😃

**Comment by dae** [comment]
I can't think of any reason off the top of my head why this would cause problems - the fact that non-new cards were being fetched before was likely just an oversight.

**Comment by Arthur-Milchior** [comment]
Thanks a lot @dae for confirming. Seems a really nice analysis, thank you for explaining so much.
Don't hesitate to come discuss on discord with us, so you can bounce ideas with us and check whether we see any reason why it would not work, it may have saved you time as it seems you had to really look carefully at everything. Or maybe on anki official forum.

If there is the similar problem in Rust, you may want to correct it in rust too maybe. Otherwise, I'd suggest to create this as an issue on anki site.

I'd note that, if you use anki desktop, you may want to consider using an add-on that automatically randomize your card everyday, or something like that, so that you don't have to do it manually. Such an add-on would be quite simple to do if it do not already exists
