### ISSUE TITLE
Adding an option to select all cards in the "study a random selection of cards" in custom study

### ISSUE THREAD

**Issue by VamsiKrishnaCommits** [ankidroid/Anki-Android#8176]
**Is your feature request related to a problem? Please describe.**
I often use the feature study a random selection of cards  in custom study and I have to go to the card browser to find the total number of cards(Some times)  . I was thinking why don't we add a feature to just select all the cards.
**Describe the solution you'd like**
So , in the dialogue box ,  we can just add a check box below the edit text to select all the cards in the deck. On selecting the checkbox we run a function to get the total number of cards in the deck and fill the edit text with it
![Screenshot_20210312-181609_AnkiDroid](https://user-images.githubusercontent.com/59550525/110958078-50339400-8372-11eb-9a13-073339995446.jpg)

**Comment by avirajrsingh** [comment]
@VamsiKrishnaCommits I too like your suggestion. Also we can display the total number of cards on the dialog itself so if a user needs to enter a number less than total number of cards he gets to know the number. Also instead of prefiling the EditText with 100 we can prefill it with the total number of cards present in the deck.

**Comment by mikehardy** [comment]
An interesting idea...how does Anki Desktop implement this? They may have already handled it, or they may like the feature as well (can propose things here https://forums.ankiweb.net/) - I think easiest is just to have a line below the edit text that just says the current deck count, and it's done

**Comment by david-allison-1** [comment]
I might not be understanding this issue, please let me know if I'm mistaken.

It doesn't seem appropriate to use the "randomly select cards" as a means to study all the cards, and I don't think we want to encourage this.

Filtered decks are primarily based on a search. 

Create a filtered deck for the search `deck:<name>` instead and that'll handle a filtered deck displaying all the cards.

**Comment by mikehardy** [comment]
That's a good point. I imagine if we compare with Anki Desktop they do not allow this, and if so I think your intuition here David is right and we should follow Anki Desktop, which specifically means just closing this

**Comment by VamsiKrishnaCommits** [comment]
I mean it's not like the most sought out feature , at times I felt like just having this feature would save me the hassle of knowing the deck size to go through the entire deck in custom study . It would just improve the UX.

**Comment by Arthur-Milchior** [comment]
Wouldn't just entering 9999 work ? If you select a number too big, it do not break, and you don't have to look at actual number

**Comment by VamsiKrishnaCommits** [comment]
There are decks having sizes more than 100000 , do we have a threshold on deck size? If there is ,it's news to me.

**Comment by VamsiKrishnaCommits** [comment]
Which happens rarely though, I think you are right@Arthur-Milchior

**Comment by Arthur-Milchior** [comment]
Put whatever number you want. I don't know how you can review more than 9999 cards in a day, so having a random selection of 9999 cards do not intuitively seems to be a problem, but that's you call.

Does it solve your problem? can we close?

**Comment by VamsiKrishnaCommits** [comment]
Yeah you can close it , it makes more sense now
