### ISSUE TITLE
answer button position top hides card content in reviewer

### ISSUE THREAD

**Issue by fletchermoore** [ankidroid/Anki-Android#8177]
With a recent update cards were showing blank on review. I toggled the setting answer button on top back to the default bottom in order to get it to show cards again, but I don't prefer this position because I fat finger bottom buttons. I'm mainly using gestures.

**Comment by david-allison-1** [comment]
@fletchermoore Thanks for the report! 

Which version was this problem exhibited on? We fixed a bug where the card content wasn't appearing in V2.14.6

Can you confirm that you still can't see card content if the position is "Top".

If this is the case, could you go to `Settings - Advanced - About AnkiDroid - Copy Debug Information` and paste the data here so we can look into it further.

Thanks

**Comment by fletchermoore** [comment]
Ah looks like I didn't yet have 16. It works now. Thank you
