### ISSUE TITLE
Restructure ReadText and TextToSpeech usage

### ISSUE THREAD

**Issue by JG916** [ankidroid/Anki-Android#8179]
## Problem
ReadText and its usage of TextToSpeech is prone to bugs.
The internal structure of ReadText is a mix of static and non-static fields and functionality, which leads to a large amount of trouble with state.
The connections between ReadText, TTS and AbstractFlashcardView are also complicated.

## Solution
Without getting too deep into possible solutions (way too much to take in before I feel confident about stating one), one concern brought up so far is about whether to lean towards static vs non-static usage.
After checking out the documentation for TTS more, it might not be a good idea (or not even possible) to consolidate all of it into a singleton - because of initialization listeners, possible leaks, or other hardcoded Activity <-> TTS communication.

## Misc Info
See #8155 and #8084 for precursory discussions that lead to this issue.

P.S. @mikehardy When I mentioned "shared throughout all applications", it looks like I spoke too soon. Some of the functionality is device-wide, but not to the point where a singleton makes perfect sense :-(

P.P.S It didn't look like either the bug or feature templates were appropriate for this. LMK if I should change the format.

**Comment by shobhi1310** [comment]
Can I pick up this issue and work on it?

**Comment by david-allison-1** [comment]
@shobhi1310 This probably wouldn't be a great first issue, but do let me know if you'd like it anyway.

Coming up with a design that we can discuss here would be the first stage

**Comment by shobhi1310** [comment]
Ya actually I was going to ask this since this is a conceptual design. I would be happy to have comments from you on this and work accordingly.

**Comment by david-allison-1** [comment]
Let's give it a shot. I can't guarantee that we'll get through this one quickly.

**Comment by david-allison-1** [comment]
Do note: it should be compatible with a design in: https://github.com/ankidroid/Anki-Android/issues/5793#issuecomment-624558490

I don't think this change will be high level enough to affect it

**Comment by mikehardy** [comment]
This is still a thing and at some point we'll want to support the new TTS features from upstream

**Comment by BrayanDSO** [comment]
A lot of our code should be restructured to have a decent enough architecture, and we are well aware of it, so I'm closing this to get the focus of GH issues into bugs and feature requests
