### ISSUE TITLE
Digits not very visible in the night mode[Bug]

### ISSUE THREAD

**Issue by 2tanayk** [ankidroid/Anki-Android#8183]
###### Reproduction Steps

1. Go to the navigation drawer
2. switch to night mode
3. Check the last 2 digits (when 0) on the right side of a deck
![ankil](https://user-images.githubusercontent.com/60653277/111029351-4f5a3b00-8422-11eb-955a-f6f51827bc56.jpeg)
![ankid](https://user-images.githubusercontent.com/60653277/111029373-69941900-8422-11eb-8960-2eb9fdc68a2b.jpeg)

(This is more of an enhancement than a bug)
###### Expected Result
A lighter color which is more visible and suitable for night mode

###### Actual Result
The digits are not very visible in a dark theme

###### Debug info
AnkiDroid Version- latest version (from the master branch)
Android version-10

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by 2tanayk** [comment]
I would also like to work on this issue if accepted :)

**Comment by Arthur-Milchior** [comment]
This is indeed a real isuse. Clearly, either it should be displayed and can be read, or not displayed at all. In any case, I know the accessibility test app stated it was not accessible. I'm happy you'd work on it, I think I had no time.

I want that the result pass accessibility test, please. You can take a look at the app on https://developer.android.com/guide/topics/ui/accessibility
I'd also like to have a clear difference between 0 and other numbers, so that a quick look show which decks have card to review.
Usually, I ask for the dev to explain what they want to do before they start. However, since it's "only" a change of color, I guess that doing the change and taking screenshot of result is easier than trying to explain in a mock document.

**Comment by Arthur-Milchior** [comment]
And in case it's not clear, once the feature request is accepted as relevant, you don't need our permission to work on it. So you can work on it already

**Comment by 2tanayk** [comment]
> This is indeed a real isuse. Clearly, either it should be displayed and can be read, or not displayed at all. In any case, I know the accessibility test app stated it was not accessible. I'm happy you'd work on it, I think I had no time.
> 
> I want that the result pass accessibility test, please. You can take a look at the app on https://developer.android.com/guide/topics/ui/accessibility
> I'd also like to have a clear difference between 0 and other numbers, so that a quick look show which decks have card to review.
> Usually, I ask for the dev to explain what they want to do before they start. However, since it's "only" a change of color, I guess that doing the change and taking screenshot of result is easier than trying to explain in a mock document.

Yes I do know about the accessibility test thing and I think it fails even without having to test it

**Comment by 2tanayk** [comment]
I'll start working on it as soon as it is possible!

**Comment by Arthur-Milchior** [comment]
You don't have to test, I can confirm it is failing too. It's obviously failing here. 
This was not a test required until recently to be honest, and we have a lot of correction to do

**Comment by Akshay0701** [comment]
@2tanayk  are you still working on this ?

**Comment by 2tanayk** [comment]
> @2tanayk  are you still working on this ? 

Yes I am

**Comment by 2tanayk** [comment]
Please let me know if the above is enough
