### ISSUE TITLE
[Bug] Answer column displays something unclear

### ISSUE THREAD

**Issue by zoulja** [ankidroid/Anki-Android#8186]
###### Reproduction Steps
I'm preparing multiplication table cards for my kid
1. Create basic card with Answer input
![image](https://user-images.githubusercontent.com/10187203/111042309-dd97e680-844d-11eb-8d35-1997690a114a.png)
2. Check it in cards table

###### Expected Result
Answer column shows actual answer - 9
###### Actual Result
I'm not sure where data for this column comes from and why it's not simply what anyone could expect to see here
![image](https://user-images.githubusercontent.com/10187203/111042322-ebe60280-844d-11eb-9dfc-a05ee118bebe.png)

Sad true that I'm too old and tired to remember multiplication table, but I can't review what I've done all at once - I must click all cards one by one to find an error, this is really frustrating

###### Debug info
AnkiDroid Version = 2.14.6

Android Version = 10

ACRA UUID = 5ff72660-fb1e-445c-9a4a-cd46e651b63a

Scheduler = std2

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi,

This can be fixed via the card template "Browser Appearance" functionality: 

https://www.youtube.com/watch?v=JbxNP4pSIBA

Enter `{{оборот}}` in the "Answer Appearance".

Best,

David

**Comment by zoulja** [comment]
Thank you good sir, you are my saviour 🙏
Is there some article/documentation to understand the logic behind current implementation (which doesn't look reasonable to me, but maybe I'm just missing something)?

**Comment by mikehardy** [comment]
Interesting - I would have similar expectations to @zoulja - if I set card browser to the name of a field and that field has something in it, why wouldn't that show up :thinking:

**Comment by david-allison-1** [comment]
> Interesting - I would have similar expectations to @zoulja - if I set card browser to the name of a field and that field has something in it, why wouldn't that show up 🤔

My understanding is that this depends on the card template: If the answer template contains, but doesn't start with `{{FrontSide}}`, then it won't be stripped.

https://github.com/ankidroid/Anki-Android/blob/ba6051f93e29a4ed3ebb58fe591ddcaef532d2db/AnkiDroid/src/main/java/com/ichi2/anki/CardBrowser.java#L2633-L2653

We should check with Anki Desktop to see what its behaviour is here. Possibly there is a bug in our implementation

**Comment by Arthur-Milchior** [comment]
I'd like to add that you can but the `<h1>` tag in the template, so that you don't have to repeat it everywhere.

I don't know what the second column titile OTBET mean (I know I'm not actually using the correct letter, sorry for that), so it's hard to know exactly what's going on in details.  Sharing the card would also help as it would show what is your two templates

**Comment by zoulja** [comment]
Hello, @Arthur-Milchior, thanks for looking into this!
Ответ literally means Answer
