### ISSUE TITLE
Add 'View cards' to deck's context menu

### ISSUE THREAD

**Issue by zoulja** [ankidroid/Anki-Android#8187]
**Is your feature request related to a problem? Please describe.**
Current implemenation, when you need to click dedicated menu item in left pane(to see the cards you have) is not user friendly
Looks like some legacy implemenation that could be improved

**Describe the solution you'd like**
Need to add 'View cards' menu in deck's context menu
Actual layout:
![Screenshot_20210314_213512](https://user-images.githubusercontent.com/10187203/111080166-421a7a80-850e-11eb-9e4a-e1b52dddc997.jpg)

Expected layout:
![Screenshot_20210314_213512-01](https://user-images.githubusercontent.com/10187203/111080096-e0f2a700-850d-11eb-8c75-e062654db10b.jpeg)

**Describe alternatives you've considered**
This is the UX standard, obvious and user friendly way, no alternatives

**Additional context**
none

**Comment by mikehardy** [comment]
PRs happily accepted :-) - for any user interface work, please post screenshots before and after with the proposed change so we may see how it looks without pulling + building a developer branch

**Comment by zoulja** [comment]
Thank you @mikehardy, I've updated description.
Can't promise anything abt PR, last time when I tried to contribute I wasn't even able to setup development environment ¯\_(ツ)_/¯

**Comment by mikehardy** [comment]
:-), we are participating in the google summer of code this year and have a HUGE pile of motivated participants at the moment so there is some hope for it, cheers

**Comment by ChaxuGarg** [comment]
Can I work on this issue, @mikehardy @david-allison-1 ? (Also I am a complete beginner to open source and big codebases, so any leads are highly appreciated)

**Comment by david-allison-1** [comment]
Sounds good to me, as long as @zoulja hasn't already started work. Thanks!!

**Comment by ChaxuGarg** [comment]
Created a PR for this issue. Please check and give feedback. Thanks a lot!!

**Comment by ChaxuGarg** [comment]
I guess should be fine now, review once and close the issue if PR looks okay!!

**Comment by musiqualGeek** [comment]
I think just adding the text "View Card List" is not enough. It should be in alignment with the rest of the text. Make it more readable.
- Add top and bottom margin for View Card List
- Change the color of the text View Card list to blue or any other color that can be easily differentiated with the card name text color.
- the Start margin also needs to be fixed as it is not alligned with rest of the text.

**Comment by mikehardy** [comment]
@musiqualGeek if that is a review of the PR, please make review comments *on* the PR #8216

**Comment by pravesh00** [comment]
Is anyone working on this?

**Comment by david-allison-1** [comment]
> Is anyone working on this?

Active PR, but hasn't been looked at in a few days. let's give the author a little more time. 

@ChaxuGarg, are you around?

**Comment by ChaxuGarg** [comment]
> > Is anyone working on this?
> 
> [Active PR](https://github.com/ankidroid/Anki-Android/pull/8216), but hasn't been looked at in a few days. let's give the author a little more time.
> 
> @ChaxuGarg, are you around?

Yeah, i am here. Really sorry for being inactive @mikehardy, took a little digital detox, will fix the issue very soon now.

**Comment by ShridharGoel** [comment]
Opened a pull request for this since there was no update from the assigned person whose pull request was inactive (already commented there to check the status).
