### ISSUE TITLE
ProgressDialog extra space due to empty title [Bug]

### ISSUE THREAD

**Issue by imaryandokania** [ankidroid/Anki-Android#8192]
###### Reproduction Steps

1. The path to error is com/ichi2/anki/MyAccount.java
2. Progress dialog initialisation inside  onPreExecute() 

###### Expected Result(after correction)
<img width="292" alt="Screenshot 2021-03-14 at 9 08 33 AM" src="https://user-images.githubusercontent.com/61244704/111056182-38106180-84a5-11eb-94f8-202611f6d20d.png">

###### Actual Result 
<img width="292" alt="Screenshot 2021-03-14 at 9 09 53 AM" src="https://user-images.githubusercontent.com/61244704/111056189-42326000-84a5-11eb-9c26-e9a16d8923f2.png">

###### Debug info
<img width="692" alt="Screenshot 2021-03-14 at 9 11 59 AM" src="https://user-images.githubusercontent.com/61244704/111056208-5e360180-84a5-11eb-9e5e-0c36cd1db0a0.png">

here the code should be:

the error is with keeping title as "" , I have fixed this issue , I will create pr if you want

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Looks good to me! Let's get this fixed.

**Comment by imaryandokania** [comment]
> Looks good to me! Let's get this fixed.

I have committed and also create PR . Hope it gets merged
