### ISSUE TITLE
Marathi language xml files is not well translated.

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#8203]
## Problem 
Ankidroid do support for marathi language but when we select locale language as marathi it keep shows all english words

## Solution
I viewed full codebase there is problem with marathi translated string files in values folder (it is in english translation not marathi) ,
So to solve this issue i have to translate english word to marathi word. 

## Additional context
The reason i am taking this issue because, my native language is marathi ,so i can translate english word to marathi easily.

**Comment by Akshay0701** [comment]
i am working on this issue.

**Comment by infinyte7** [comment]
@Akshay0701 View this to get started
https://github.com/ankidroid/Anki-Android/wiki/Translating-AnkiDroid

**Comment by Akshay0701** [comment]
Thanks alot ,it will make this transition part more easier

**Comment by Akshay0701** [comment]
Hey @infinyte7 now i understood , why marathi translation was so bad ,crowdin have very few word in marathi language, thats why its result bad translated file. again thanks :)

**Comment by david-allison-1** [comment]
Thanks! Very happy to see work on this, but let's move any related discussion to CrowdIn, as that's the platform we use for language related issues: https://crowdin.com/project/ankidroid/mr#

**Comment by Akshay0701** [comment]
Yes but crowdin platform don't have enough words to translate  English to Marathi language ,that's why I raised issue .

**Comment by Akshay0701** [comment]
I am already completed half translation , only few files is remaining to translate to Marathi language 

This is translation of crowdin for marathi language(it keeps showing English words)

![Screenshot_20210314-155809.jpg](https://user-images.githubusercontent.com/52353967/111078863-8e20eb80-851d-11eb-87d1-5855c2f6c1bb.jpg)

I converted to Marathi ,here is the screen shot
![Screenshot_20210314-155751.jpg](https://user-images.githubusercontent.com/52353967/111078932-ccb6a600-851d-11eb-95c0-8ce74f442249.jpg) 

I am already completed half translation ,Can you open this issue ?

**Comment by david-allison-1** [comment]
> Yes but crowdin platform don't have enough words to translate English to Marathi language ,that's why I raised issue .

I'm sorry, I don't quite understand this. Could you explain?

----

If it's the fact that the app hasn't been translated, then there's little point in keeping an open issue for it. CrowdIn will handle organisation around the issue much better than GitHub. There's little point in drawing people's attention to it as 99% of contributors won't be able to help, and those that can will be using CrowdIn to fix it.

We have ~90 languages and individually there's little to no incentive to keep open issues for them here.

If it's something else (such as a problem with the translation process), then let's reopen the issue.

**Comment by Akshay0701** [comment]
No actually Arthur and mrudultora discussing ,about this issue with other possible approach , mrudultora also created issue to track all discussions related to this topic ,we will see how we can improve this language part of app.

**Comment by eginhard** [comment]
> I am already completed half translation , only few files is remaining to translate to Marathi language

@Akshay0701 Just for completeness because you mentioned you have already translated half of the files to Marathi and I don't see that on the CrowdIn platform. You should enter all your translations directly here: https://crowdin.com/project/ankidroid/mr

You should not edit the values-mr/*.xml files yourself, these are updated automatically. The updated strings will then appear in the app in a future update. See the link mentioned above for more details: https://github.com/ankidroid/Anki-Android/wiki/Translating-AnkiDroid

**Comment by Akshay0701** [comment]
@eginhard thanks a lot , i will add my translation to above link you given,i have more than half translated files in my locale machine , i will add them as soon as possible  :)

**Comment by mikehardy** [comment]
Excellent @Akshay0701 ! And nice to see you in the comments @eginhard :-) - we certainly appreciate the help right now, the more people that know AnkiDroid helping out the better for sure!

**Comment by Akshay0701** [comment]
@eginhard finally updated almost 100% of string to marathi ,hope this will help all Indian/Maharashtrian users.

**Comment by mikehardy** [comment]
@Akshay0701 

https://github.com/ankidroid/Anki-Android/pull/8685/checks?check_run_id=2428378696#step:8:40

```
/home/runner/work/Anki-Android/Anki-Android/AnkiDroid/src/main/res/values-mr/06-statistics.xml:74:201: Resource and asset merger: The entity name must immediately follow the '&' in the entity reference.
    org.xml.sax.SAXParseException; lineNumber: 74; columnNumber: 201; The entity name must immediately follow the '&' in the entity reference.
```

**Comment by mikehardy** [comment]
Fixed up on crowdin after testing fixes locally, it was a problem with HTML entities:

```
mike@isabela:~/work/AnkiDroid/Anki-Android (i18n_sync *) % git diff
diff --git a/AnkiDroid/src/main/res/values-mr/06-statistics.xml b/AnkiDroid/src/main/res/values-mr/06-statistics.xml
index 112d49dbd..9d31090af 100644
--- a/AnkiDroid/src/main/res/values-mr/06-statistics.xml
+++ b/AnkiDroid/src/main/res/values-mr/06-statistics.xml
@@ -71,7 +71,7 @@
     <string name="stats_answer_type">उत्तर प्रकार</string>
     <string name="stats_today_again_count">पुन्हा मोजा: &lt;b&gt;%d&lt;/b&gt;</string>
     <string name="stats_today_correct_count">(&lt;b&gt;%.1f%%&lt;/b&gt; बरोबर)</string>
-    <string name="stats_today_type_breakdown">जाणून घ्या: &lt;b&gt;%1$d&lt;/b&gt;, पुनरावलोकन करा:  &lt;b&gt;%2$d&lt;/b&gt;,  पुन्हा करा: &lt;b&gt;%3$d&lt;/b&gt;, फिल्टर &lt;b&gt;%4$d&lt;/b&gt; / बी & जीटी;</string>
+    <string name="stats_today_type_breakdown">जाणून घ्या: &lt;b&gt;%1$d&lt;/b&gt;, पुनरावलोकन करा:  &lt;b&gt;%2$d&lt;/b&gt;,  पुन्हा करा: &lt;b&gt;%3$d&lt;/b&gt;, फिल्टर &lt;b&gt;%4$d&lt;/b&gt; / बी &amp; जीटी;</string>
     <string name="stats_today_mature_cards">प्रौढ कार्डावर अचूक उत्तरेः %1$d/%2$d (%3$.1f%%)</string>
     <string name="stats_today_no_mature_cards">आज कोणतीही परिपक्व कार्डे अभ्यासली गेली नाहीत</string>
     <string name="stats_overview_forecast_total">एकूण: &lt;b&gt;%1$d&lt;/b&gt; पुनरावलोकने</string>
diff --git a/AnkiDroid/src/main/res/values-mr/10-preferences.xml b/AnkiDroid/src/main/res/values-mr/10-preferences.xml
index 89588964e..e01018f1e 100644
--- a/AnkiDroid/src/main/res/values-mr/10-preferences.xml
+++ b/AnkiDroid/src/main/res/values-mr/10-preferences.xml
@@ -291,7 +291,7 @@
     <string name="analytics_title" maxLength="41">वैशिष्ट्याचा वापर सामायिक करा</string>
     <string name="analytics_summ">विकासकाला लोक कोणती वैशिष्ट्ये वापरतात हे पाहण्यात मदत करून आपण अंकीड्रोइडमध्ये योगदान देऊ शकता</string>
     <string name="note_editor_replace_newlines" maxLength="41">एचटीएमएलसह नवीनलाइन पुनर्स्थित करा</string>
-    <string name="note_editor_replace_newlines_summ">टीप संपादकात, & lt; br & gt ची कोणतीही घटना रूपांतरित करा. कार्ड संपादित करताना नवीन रेषांवर.</string>
+    <string name="note_editor_replace_newlines_summ">टीप संपादकात, &lt; br &gt; ची कोणतीही घटना रूपांतरित करा. कार्ड संपादित करताना नवीन रेषांवर.</string>
     <string name="no_code_formatting" maxLength="41">साधे टाइप केलेले उत्तर स्वरूपन</string>
     <string name="no_code_formatting_summ">टाइप केलेल्या उत्तर निकालांमध्ये निराकरण ‘‘ ’</string>
     <string name="type_in_answer_focus" maxLength="41">लक्ष द्या ‘उत्तर टाइप करा’</string>

```

**Comment by Akshay0701** [comment]
Sorry for mis formatting ,is this resolved now ?

**Comment by mikehardy** [comment]
Yeah - I resolved it, it was really subtle! The one in 10-preferences was an error that you could have gotten I think but the one in 6-statistics *should* have worked, except for a very rare combination of it needing to be HTML entities in that string *and* not being able to use the `&amp;` entity specifically. I'm not sure who else could have gotten that one except someone familiar with the python script for localizations fetch...

**Comment by Akshay0701** [comment]
Thanks Mike!
