### ISSUE TITLE
Adding more translations to app

### ISSUE THREAD

**Issue by mrudultora** [ankidroid/Anki-Android#8205]
**Is your feature request related to a problem? Please describe.**
Currently, the app supports translations. But according to one of the members, currently only 9% text is translated. That's very low. 

**Describe the solution you'd like**
Crowdin supports automated translations with the help of variety of engines (it have it's own TM and MT service). For ex, Microsoft Translator, Google Translate, Google AutoML Translation, Yandex.Translate, Amazon Translate and much more for automation. They have some requirements of API keys.

**Describe alternatives you've considered**
The alternative is only if real users come and help for translations.

**Additional context**
More information can be found out [here](https://crowdin.com/resources#machine-translation).

**Comment by Akshay0701** [comment]
Thanks for raising this issue , I also talking about same thing,it is need to address.

**Comment by david-allison-1** [comment]
Mirroring what I said on Discord: (Opinions open for discussion)

I'd only be happy if machine translation is used by fluent speakers to supplement their translation efforts. Adding partially or badly translated text means that our translators would lost their measure of progress, and a bad result would likely frustrate users more than using English if we're using inconsistent terms throughout the app. 

Even with modern translation services, I sometimes have my words translated into the exact opposite of their meaning, and that worries me, we're not at the stage where we can trust the system.

----
@Akshay0701 
In terms of translations: we need more, but it's a maintenance task that we're very unlikely to ever fully resolve. To me, this doesn't feel appropriate for GitHub issues (as the criteria for completion is a moving target), given that CrowdIn will handle progress reporting and collaboration much better than GitHub.

**Comment by mikehardy** [comment]
Agreed that machine translations are not the proper solution for this. Up to now, if users are interested they translate, and if they are not, there is no translation, and that's life (and open source): you get out of it what you put into it :shrug:

**Comment by mrudultora** [comment]
@mikehardy I agree. But, is there a way to motivate users to translate. I guess, most of them never looks from that perspective.

**Comment by david-allison-1** [comment]
> @mikehardy I agree. But, is there a way to motivate users to translate. I guess, most of them never looks from that perspective.

We've recently added a "Contribute/Translate" in our new "Help" menu - I haven't added metrics to this (I'll raise an issue), but I don't feel it will be well-used.

It's worth discussing whether we want to (or how to) make this more prominent, especially if we know a user is using a language which we don't support well yet

**Comment by mrudultora** [comment]
@david-allison-1 Can we put **Support AnkiDroid** directly in nav drawer ? (we can just experiment with different things and then only we can know the most productive way in this matter).

**Comment by david-allison-1** [comment]
> @david-allison-1 Can we put Support AnkiDroid directly in nav drawer ? (we can just experiment with different things and then only we could know the most productive way in this matter).

Could you raise another issue as an enhancement to consolidate discussion? Personally I've been considering it and would like to see it, but it'd be interesting to get other maintainer's opinions on it.

**Comment by Arthur-Milchior** [comment]
> It's worth discussing whether we want to (or how to) make this more prominent, especially if we know a user is using a language which we don't support well yet

Added https://github.com/ankidroid/Anki-Android/issues/8242 which seems a related improvement
