### ISSUE TITLE
[Bug] Error reporting mode changes back to Never report on restarting the app.

### ISSUE THREAD

**Issue by ritvij14** [ankidroid/Anki-Android#8207]
###### Reproduction Steps
`In Debug mode:`
1. Open the app and go to Settings > General Settings > Error Reporting Mode
2. By default it will be set on `Never Report`. Change it to Always Report / Ask me, and close the app.
3. On reopening the app and going back to settings, the setting is back to Never Report.

###### Expected Result
On reopening the new setting should be retained.

###### Actual Result
On reopening it is set back to Never report.

###### Debug info
AnkiDroid Version = 2.15alpha28

Android Version = 10

ACRA UUID = 7486fcf0-c78d-41fc-bd23-057d06c89acc

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Sorry for the bad info. Debug-only feature

> every time you want to successfully send a crash report you must allow the app to do so, for debug builds we assume crash reports are worthless so you have to manually toggle it on in settings first from "never" to one of the report send options that will actually send

https://github.com/ankidroid/Anki-Android/pull/8193#discussion_r593960483

**Comment by 2tanayk** [comment]
I too was about open an issue for this,glad I looked it up :)
