### ISSUE TITLE
Create a Contributions file and move content from the wiki

### ISSUE THREAD

**Issue by aflah02** [ankidroid/Anki-Android#8208]
**Is your feature request related to a problem? Please describe.**
Currently for aspiring contributors there is no obvious way to see how to get going. Also traditionally the wiki tag has more of an association with a description rather than the process to set up (in reference to other repos which I've seen).
I would suggest creating a Contributions File which lists the process of setting up the repository as a whole.

**Describe the solution you'd like**
Some references can be - https://github.com/facebook/react/blob/master/CONTRIBUTING.md
Although this links further but this is generally the file used in most repositories to explain the contribution process.

**Describe alternatives you've considered**

**Additional context**

**Comment by mikehardy** [comment]
I see no value in a contributing file vs the wiki, that is a sideways motion, no actual benefit, in fact it makes it more difficult for people to edit I think, so I do not like it

If you have content you would like to add to the wiki, you may just edit it

putting a contributing file in that points to the wiki is fine by me though - just propose a PR for that if you like

**Comment by aflah02** [comment]
Hmm alright will do thanks @mikehardy
