### ISSUE TITLE
Add metrics to "Help" section items

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8210]
A new Help menu was added in https://github.com/ankidroid/Anki-Android/pull/7358

We currently don't send any analytics for clicks on this screen. It would be useful to confirm that this dialog is being used, and how changes to this screen affect user interactions.

It would also be useful to measure the bounce rate from this screen if it is closed without the user selecting an item.

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8205#issuecomment-798986603_

**Comment by mrudultora** [comment]
@david-allison-1 Would you please give some more info. Like, how to track and send analytics?

**Comment by david-allison-1** [comment]
@mrudultora Mike Hardy would be the one to ask if you'll need further ideas/thoughts on adding additional analytics methods. We're not logging much right now. This may need expanding for the given task.

For now, we have `UsageAnalytics.java`

Sample method:

https://github.com/ankidroid/Anki-Android/blob/24443a327ed060dc31f4c16c88a3553d50d7ad05/AnkiDroid/src/main/java/com/ichi2/anki/analytics/UsageAnalytics.java#L230-L252

**Comment by mrudultora** [comment]
@david-allison-1 Okay, I will wait.

**Comment by david-allison-1** [comment]
@mikehardy Opinions on this one?

**Comment by mikehardy** [comment]
#7300 is a good example
I think sendAnalyticsEvent is sufficient but the Categories need to be constrained as there are only so many you may have and typos would be a terrible way to burn a category slot.

I propose `UsageAnalytics.Category.LINK_CLICKED` with a simple / unique string value for each help link the user may click, used like so https://github.com/ankidroid/Anki-Android/pull/7300/files#diff-b9f2f2c8f664870d38eaa028e9f1a2a3f830e13e0c2591cafaabf8826f7951c2R272

Any other links in the app might be interesting as well, e.g. in the changelog we might be able to intercept a link click just enough to log it but I'm not sure. I would consider that a separate thing though and stay focused on just instrumenting the help menu here

**Comment by mrudultora** [comment]
@david-allison-1 This `execute` method is called on clicking the item in **Help** and it has only one parameter. I thought of adding a second parameter but it was not making sense. I need the title of the item selected from **Help** dialog box. This is the only place where I can add analytics, but I am unable to get title of that item. Please throw some light in this context.
https://github.com/ankidroid/Anki-Android/blob/7921fc264abca3332328d3e0bc75cde718b4bf28/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java#L89-L99

**Comment by david-allison-1** [comment]
> @david-allison-1 This `execute` method is called on clicking the item in **Help** and it has only one parameter. I thought of adding a second parameter but it was not making sense. I need the title of the item selected from **Help** dialog box. This is the only place where I can add analytics, but I am unable to get title of that item. Please throw some light in this context.
> https://github.com/ankidroid/Anki-Android/blob/7921fc264abca3332328d3e0bc75cde718b4bf28/AnkiDroid/src/main/java/com/ichi2/anki/dialogs/HelpDialog.java#L89-L99

The problem with using the name is that it'll be variable depending on the language. I'd use a different ID: a hardcoded string 

----

Note sure if you appreciate me throwing out a design here, if you'd rather work through it yourself, please let me know. Autonomy when making fixes is fantastic :)

* Edit `Item.java`
* Add an abstract method: String getAnalyticsId()
  * Implement it for the derived classes - accept a resource Id from `constants.xml` in the constructor. I don't think we want a hardcoded string here, even for `RateApp` as we'd want to distinguish between two buttons with the same functionality
* Make `execute()` protected and rename it - also do this for derived classes
* Make a new `public final execute` method which:
  * calls what was previously called `execute()`
  * sends the click analytic via getAnalyticsId() - Implementer's choice, but I'd do this before the call
