### ISSUE TITLE
Add Lint check to ensure all .java files have Copyright Headers

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8211]
With more new contributors, we should automate ensuring that each new file has a copyright header, rather than leaving this to code review.

We can do this via a lint check. For example: https://github.com/ankidroid/Anki-Android/blob/db82ab008a90ff89e77c5c5637b2e33be17ab04a/lint-rules/src/main/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsage.java

It would be ideal if the lint check guided users to the correct setting screen in Android Studio to set up the copyright:

This can be done via an explanation: https://github.com/ankidroid/Anki-Android/blob/db82ab008a90ff89e77c5c5637b2e33be17ab04a/lint-rules/src/main/java/com/ichi2/anki/lint/rules/InconsistentAnnotationUsage.java#L37-L39

![image](https://user-images.githubusercontent.com/62114487/111086339-82c8c280-8513-11eb-8e7e-bf10bd85a6cc.png)

It may also be useful to provide users with a template:

```
 Copyright (c) $today.year Your Name Here <example@example.com>

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU General Public License as published by the Free Software
 Foundation; either version 3 of the License, or (at your option) any later
 version.

 This program is distributed in the hope that it will be useful, but WITHOUT ANY
 WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 PARTICULAR PURPOSE. See the GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along with
 this program.  If not, see <http://www.gnu.org/licenses/>.
```

**Comment by david-allison-1** [comment]
Please note that this functionality may already exist in Android Studio's suite of lint tools, and we should confirm that this isn't the case before writing our own code.

**Comment by ChaxuGarg** [comment]
Can I work on this?

**Comment by imaryandokania** [comment]
I want to work on this

**Comment by david-allison-1** [comment]
Sorry @imaryandokania, I'll go with @ChaxuGarg as he commented first.

Normally we don't have the two people going for the same issue - it's a nice problem to have

**Comment by imaryandokania** [comment]
> Sorry @imaryandokania, I'll go with @ChaxuGarg as he commented first.
> 
> 
> 
> Normally we don't have two people going for the same issue - it's a nice problem to have

No problem 😀

**Comment by almas33** [comment]
Hi @ChaxuGarg are you working on this? If not I would like to work on.

**Comment by almas33** [comment]
> Please note that this functionality may already exist in Android Studio's suite of lint tools, and we should confirm that this isn't the case before writing our own code.

There doesn't seem to exist any lint check on this , regarding copyrights there is only one lint check which suggests to convert (c) to copyright symbol

**Comment by ChaxuGarg** [comment]
> Hi @ChaxuGarg are you working on this? If not I would like to work on.

I haven't started working on it yet, so sure @almas33 go ahead

**Comment by david-allison-1** [comment]
> > Please note that this functionality may already exist in Android Studio's suite of lint tools, and we should confirm that this isn't the case before writing our own code.
> 
> There doesn't seem to exist any lint check on this , regarding copyrights there is only one lint check which suggests to convert (c) to copyright symbol

We can write our own if one doesn't exist: https://github.com/ankidroid/Anki-Android/pull/7707

**Comment by david-allison-1** [comment]
IntelliJ Template:

```
 Copyright (c) $today.year Your Name Here <example@example.com>

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU General Public License as published by the Free Software
 Foundation; either version 3 of the License, or (at your option) any later
 version.

 This program is distributed in the hope that it will be useful, but WITHOUT ANY
 WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
 PARTICULAR PURPOSE. See the GNU General Public License for more details.

 You should have received a copy of the GNU General Public License along with
 this program.  If not, see <http://www.gnu.org/licenses/>.
```
