### ISSUE TITLE
Improve the UI for the Add Decks button

### ISSUE THREAD

**Issue by iamvs-2002** [ankidroid/Anki-Android#8223]
**Is your feature request related to a problem? Please describe.**
![Screenshot (128)](https://user-images.githubusercontent.com/54304786/111108284-880f2700-857e-11eb-9d33-a683778c9d10.png)
![Screenshot (129)](https://user-images.githubusercontent.com/54304786/111108288-89d8ea80-857e-11eb-8cb4-98164eb49ebf.png)
As seen in the above screenshots, when the user clicks on the add decks button(floating action button), the text or the description for each overlaps the background text. It doesn't look good, especially for the Night Mode.

**Describe the solution you'd like**
A solution for that would be to replace the same with the hover-over text, thereby improving the UI.

**Describe alternatives you've considered**
An alternate solution for the same would be to design a layout for such texts, thereby improving the UI.

**Additional context**

**Comment by david-allison-1** [comment]
Do you have any proposed solutions to this problem?

**Comment by kartikeysaran** [comment]
@david-allison-1 We can either hide the text and the image whenever the menu is open ("+" button is clicked ) Or If the decks are empty we can rather hide the floating button and place a button at the center stating  "Create your first deck , Get Shared Decks"

**Comment by iamvs-2002** [comment]
> Thanks for the report!
> 
> Do you have any proposed solutions to this problem?

Yes, I think it can be solved by using the Extended Floating Action Button rather than using the Floating Action menu.
What I mean by that is that:
By using the Extended Floating Action Button, one can add a separate text view to every floating action button inside the extended floating action button. In that way, there can be a different layout for those text views, as per the overall UI.
Kindly allow me to work on this issue.

**Comment by david-allison-1** [comment]
> Extended Floating Action Button

Honesty: I'm not too familiar with this part of the code

Could you provide a link if it's a new dependency ? It's best to confirm that we'll be OK with adding it before delving into the implementation.

I wouldn't immediately see an issue with this - I think we've been wanting to modify the current FAB for some time.

But it will be best to hold off on this one until we're sure this is the solution that we want

**Comment by kartikeysaran** [comment]
> @david-allison-1 We can either hide the text and the image whenever the menu is open ("+" button is clicked ) Or If the decks are empty we can rather hide the floating button and place a button at the center stating "Create your first deck , Get Shared Decks"

This would not require any new dependency to be implemented this might work what say :)

**Comment by iamvs-2002** [comment]
> > Extended Floating Action Button
> 
> Honesty: I'm not too familiar with this part of the code
> 
> Could you provide a link if it's a new dependency ? It's best to confirm that we'll be OK with adding it before delving into the implementation (would mean a lot of wasted time if the dependency isn't suitable).
> 
> I wouldn't immediately see an issue with this - I think we've been wanting to modify the current FAB for some time.
> 
> But it will be best to hold off on this one until we're sure this is the solution that we want - I really don't like saying this (as I really don't feel we should stop people from working on issues)

Actually, this won't require any other dependency, just the one for material design.
It's basically like this: https://origin.geeksforgeeks.org/extended-floating-action-button-in-android-with-example/
(PS: though a little more complex in our case)

**Comment by iamvs-2002** [comment]
> > > Extended Floating Action Button
> > 
> > 
> > Honesty: I'm not too familiar with this part of the code
> > Could you provide a link if it's a new dependency ? It's best to confirm that we'll be OK with adding it before delving into the implementation (would mean a lot of wasted time if the dependency isn't suitable).
> > I wouldn't immediately see an issue with this - I think we've been wanting to modify the current FAB for some time.
> > But it will be best to hold off on this one until we're sure this is the solution that we want - I really don't like saying this (as I really don't feel we should stop people from working on issues)
> 
> Actually, this won't require any other dependency, just the one for material design.
> It's basically like this: https://origin.geeksforgeeks.org/extended-floating-action-button-in-android-with-example/
> (PS: though a little more complex in our case)

Also, an alternative solution could be to try adding a layout for the text views, else just giving them a background with higher padding. I shall try that, possibly that might improve it.

**Comment by iamvs-2002** [comment]
@david-allison-1 
I was going through the code. I found that adding the Extended Floating Action Button might cause an issue with casting it to the view because it's not entirely in one file.
I have a better solution, keeping earlier code as same.
Here it is:

The issue is basically with the UI and not with the Widget actually.
I went through the documentation of the Widget used for the Floating action menu/buttons, and there I found a bit useful solution which is to change the background color and the text color for the menu labels.
I did that, but I have one better suggestion, i.e., whenever the menu is opened/expanded, we could just **reduce** the visibility of the background layout. That would make it look better to the user.

NOTE: I mean to "REDUCE" the visibility and not to make it invisible entirely...xD

If you want, may I attach a video after implementing the same?

**Comment by leoshrey** [comment]
@iamvs-2002 yes, as you mentioned we can reduce background visibility on floating button click. This will improve the visibility and hence the more clear UI. 
Just for an example I am attaching the screenshot for the same thing implemented in skype application - which is making the background blue in color:
![skype111](https://user-images.githubusercontent.com/53581274/111186109-b02b7400-85d8-11eb-85e0-dd79e0f2d980.png)
But in our case I want to make the background blur which will make it look a lot beautiful and more focused on deck buttons, and hence making more handy and clear to the user.

What are your thoughts regarding this ?

If it is okay can I move forward solving this issue ?

**Comment by iamvs-2002** [comment]
> @iamvs-2002 yes, as you mentioned we can reduce background visibility on floating button click. This will improve the visibility and hence the more clear UI.
> Just for an example I am attaching the screenshot for the same thing implemented in skype application - which is making the background blue in color:
> ![skype111](https://user-images.githubusercontent.com/53581274/111186109-b02b7400-85d8-11eb-85e0-dd79e0f2d980.png)
> But in our case I want to make the background blur which will make it look a lot beautiful and more focused on deck buttons, and hence making more handy and clear to the user.
> 
> What are your thoughts regarding this ?
> 
> If it is okay can I move forward solving this issue ?

Well, I'd say that let's wait for the project admin. But yes, I wanted to work on the same. If possible, you may search for some other issue?

**Comment by mikehardy** [comment]
Getting rid of our current floating action menu and moving to supported APIs is much more important than the visual work

Here is the related issue: #4936

Unless we are doing something very difficult that cannot be implemented in the platform APIs I think this section from that related issue is the important part:

> Or since our menu is fairly simple, implement it using framework SDKs such as this example: https://github.com/ajaydewari/FloatingActionButtonMenu (from https://stackoverflow.com/questions/30699302/android-design-support-library-expandable-floating-action-buttonfab-menu)

For me, step 1 is: validate that we can use the built-in androi dframework SDK APIs to implement our FAB (this is just research, maybe a quick prototype
Step 2: get that PR in and merged
Step 3: investigate user interface changes like the one discussed above

A bonus step, now that we are on API21 as minSdkVersion I think SVG support is easy, and the "convert PNGs to SVGs" PR idea can be implemented easily: #5134 (note this also included an attempt to change the FAB but it was hard since we were still on minSdkVersion 15 and 16)

**Comment by iamvs-2002** [comment]
> Getting rid of our current floating action menu and moving to supported APIs is much more important than the visual work
> 
> Here is the related issue: #4936
> 
> Unless we are doing something very difficult that cannot be implemented in the platform APIs I think this section from that related issue is the important part:
> 
> > Or since our menu is fairly simple, implement it using framework SDKs such as this example: https://github.com/ajaydewari/FloatingActionButtonMenu (from https://stackoverflow.com/questions/30699302/android-design-support-library-expandable-floating-action-buttonfab-menu)
> 
> For me, step 1 is: validate that we can use the built-in androi dframework SDK APIs to implement our FAB (this is just research, maybe a quick prototype
> Step 2: get that PR in and merged
> Step 3: investigate user interface changes like the one discussed above
> 
> A bonus step, now that we are on API21 as minSdkVersion I think SVG support is easy, and the "convert PNGs to SVGs" PR idea can be implemented easily: #5134 (note this also included an attempt to change the FAB but it was hard since we were still on minSdkVersion 15 and 16)

I got it. You are right, the current FloatingActionMenu library is abandoned.
The Github link for the library you have provided, it could be used. Else, an extended floating action button could be implemented from scratch I guess?

**Comment by Akshay0701** [comment]
@mikehardy said `Getting rid of our current floating action menu and moving to supported APIs is much more important than the visual work` , i think inbuilt google.Material FABs will be good option
(https://material.io/components/buttons-floating-action-button) ,this don't require any external library and it is supported by android sdk.
let me know what mentors think on this ? and i want take this issue up to solve :D

**Comment by mikehardy** [comment]
I believe this conversation is happening in two places at once, which is dangerous as it implies duplicate work and lost thoughts. Let's keep the discussion on the FAB to #4936

**Comment by david-allison-1** [comment]
FAB has now been converted to use the support library. We're open to new designs.

**Comment by tanmayChakrawarty** [comment]
@david-allison-1 I will work on a new design.

**Comment by iamvs-2002** [comment]
> FAB has now been converted to use the support library. We're open to new designs.

The design for?

**Comment by david-allison-1** [comment]
A design for how we'd be able to improve the UI using the new FAB library.

I don't know what we have available in terms of functionality

**Comment by david-allison-1** [comment]
@tanmayChakrawarty I think it'd be best to let @iamvs-2002 work on this if they'd like, since they reported the issue

**Comment by iamvs-2002** [comment]
> A design for how we'd be able to improve the UI using the new FAB library.
> 
> I don't know what we have available in terms of functionality

Ohh okay

**Comment by iamvs-2002** [comment]
> @tanmayChakrawarty I think it'd be best to let @iamvs-2002 work on this if they'd like, since they reported the issue

I would be more than happy to work on this issue.

**Comment by iamvs-2002** [comment]
https://user-images.githubusercontent.com/54304786/113470188-45e84f80-9471-11eb-84b1-cf17d9c6eb10.mp4

I was just trying to do some changes(UI), and now the app looks like this.

**Comment by iamvs-2002** [comment]
@david-allison-1 
Kindly guide me once about what I should implement, so that I may begin working on this issue. 
Being a user of AnkiDroid, I feel that, the night mode is basically causing all the problems. Personally, it doesn't feel much comfortable to the eyes, due to high contrast, hence I made it gray from black. This way, it was pleasant to the eyes and hence improved the UI for the add decks button by adding an appropriate background for the same(matching to the logo of the app).

**Comment by david-allison-1** [comment]
It's best that if you raise an issue, you stick to solving it, and log other problems that you encounter as separate issues.

We have both a dark, and a black theme. The dark theme is easier on the eyes

As discussed above, improving/changing the background should fix the issue

**Comment by iamvs-2002** [comment]
> It's best that if you raise an issue, you stick to solving it, and log other problems that you encounter as separate issues.
> 
> We have both a dark, and a black theme. The dark theme is easier on the eyes
> 
> As discussed above, improving/changing the background should fix the issue

Yes, so I'll improve the background and make a pull request for this issue soon.
