### ISSUE TITLE
Add check on back button pressed from Launcher Activity 

### ISSUE THREAD

**Issue by riturajjain2000** [ankidroid/Anki-Android#8226]
**Is your feature request related to a problem? Please describe.**
If the back button is pressed while being on the Deckpicker Activity, the App just exits, which gets frustrating sometimes 

**Describe the solution you'd like**
Add a second check like an AlertDialog with a message like - "Do you really want to exit Ankidroid ?"

**Describe alternatives you've considered**
A Snackbar or Toast with a message "Press back again to exit the app"

**Comment by kartikeysaran** [comment]
> **Is your feature request related to a problem? Please describe.**
> If the back button is pressed while being on the Deckpicker Activity, the App just exits, which gets frustrating sometimes
> 
> **Describe the solution you'd like**
> Add a second check like an AlertDialog with a message like - "Do you really want to exit Ankidroid ?"
> 
> **Describe alternatives you've considered**
> A Snackbar or Toast with a message "Press back again to exit the app"

if a user presses back button from the home activity the app still runs in background while if we manually make the user exit the app is killed @riturajjain2000 what do you think ?

**Comment by IAmJaishree** [comment]
We can manually make it go to background, and this issue seems good, it will surely enhance the user experience.
If user presses the back button we can show the message "Press back again to exit the app" something like this, and when user presses the back button again we can make the app go in background(which is the original behavior of the back button).

**Comment by riturajjain2000** [comment]
> > **Is your feature request related to a problem? Please describe.**
> > If the back button is pressed while being on the Deckpicker Activity, the App just exits, which gets frustrating sometimes
> > **Describe the solution you'd like**
> > Add a second check like an AlertDialog with a message like - "Do you really want to exit Ankidroid ?"
> > **Describe alternatives you've considered**
> > A Snackbar or Toast with a message "Press back again to exit the app"
> 
> if a user presses back button from the home activity the app still runs in background while if we manually make the user exit the app, it is killed from background too @riturajjain2000 what do you think?

I checked , the Activty is not going to background when back button is pressed

**Comment by kartikeysaran** [comment]
> I checked , the Activty is not going to background when back button is pressed ,it is getting destroyed , so I guess this makes the issue just a UI enhancement

No , the app goes to background please can anyone else too check this :)

**Comment by riturajjain2000** [comment]
> > I checked , the Activty is not going to background when back button is pressed ,it is getting destroyed , so I guess this makes the issue just a UI enhancement
> 
> No , the app goes to background please can anyone else too check this :)

How you reached to that conclusion , plz share

**Comment by kartikeysaran** [comment]
> How you reached to that conclusion , plz share

Press the back button and the app closes -> check your background activity in your phone and Ankidroid is running in background and when we will close the app with "code" the app is killed from background too :)

**Comment by SujyotRaut** [comment]
@kartikeysaran Yes your right when back button is pressed app is running in background but DeckPicker Activity is destroyed
@riturajjain2000 I like to work on this issue

**Comment by SujyotRaut** [comment]
I submitted PR as per you feature request waiting for review if everything goes well then it will be merged

**Comment by riturajjain2000** [comment]
Mention first here that you are working on smthng , as I was working on it , now it will be just waste of my time 😅

**Comment by mikehardy** [comment]
Hello, the problem with the feature request is that none of the core contributors have even had a chance to look at it

Do we want this feature? I'm not sure, we want to think about it. I'm definitely sure we do not want to kill the app, that is not a recommended pattern in Android programming - you should let the system kill / quit apps when it wants to, but otherwise leave them running.

One thing I know is that if we make this change, the first thing a bunch of users will ask for is a preference to turn it off.

**Comment by mikehardy** [comment]
Actually - I see David did look at it and marked it as accepted, so there is that at least :-), I'll look at the PR

**Comment by SujyotRaut** [comment]
It doesn't kill the app process it just closes the `DeckPickerActivity`

**Comment by pree-T** [comment]
May I work on this?

**Comment by david-allison-1** [comment]
@pree-T There's already a PR for this

**Comment by david-allison-1** [comment]
As for a spec (requested on the PR)

* If the user presses 'Back' once on the DeckPicker, a Toast should be displayed stating `Press back again to close`
* There is no functional difference between how "back" works now, and how pressing it a second time (after this change) will work

**Comment by iamvs-2002** [comment]
> As for a spec (requested on the PR)
> 
> * If the user presses 'Back' once on the DeckPicker, a Toast should be displayed stating `Press back again to close`
> * There is no functional difference between how "back" works now, and how pressing it a second time (after this change) will work

If no one is working on this issue, kindly assign me this issue.

**Comment by david-allison-1** [comment]
> If no one is working on this issue, kindly assign me this issue.

There's a pull request in for this which requires feedback, ping me in 48 hours and I'll let you know

**Comment by iamvs-2002** [comment]
> As for a spec (requested on the PR)
> 
> * If the user presses 'Back' once on the DeckPicker, a Toast should be displayed stating `Press back again to close`
> * There is no functional difference between how "back" works now, and how pressing it a second time (after this change) will work

Kindly tell me that: the toast message is shown to close the deck menu or the app? I think it's for closing the app right?
