### ISSUE TITLE
[Bug] {{cloze:Text}} ignores repeated words and just check first of them

### ISSUE THREAD

**Issue by Koorosh-J** [ankidroid/Anki-Android#8229]
AnkiDroid ver 2.14.6
1. in card filed I use "This is {{c1::test}} which is containing {{c1::test}} word twice"
2. in Front and Back template I have "{{cloze:Field_name}}"
3. now when I Type answer like "test, test" in front and tap the answer:

I expect this: 
test, test (Check mark)

but I wee this:
test, test (first highlighted in green and second in red followed by downside arrow on next line and after that shows answer like the following line)
test (one time, so It recognize it as false answer and there is no check button)

**Comment by LittleFish33** [comment]
I think you want to create a card with two or more blanks and type answers. This can be achieved by using {type:Field_name}}.

For example, I create a cloze with two fields: `Text` and `Extra`:

1. In the `Text` field, I have "This is {{c1::test}} which is containing {{c1::test}} word twice". And in the `Extra` field, I have "test, test".
2. In the Front and Back template I have `{{cloze:Text}} {{type:Extra}}`.

The configuration is shown in the following:

<img src="https://user-images.githubusercontent.com/25958734/111198867-090c0400-85fb-11eb-81fa-f524460669aa.png" width=350> <img src="https://user-images.githubusercontent.com/25958734/111198827-fb567e80-85fa-11eb-85c1-ec7ef93f51ab.png" width=350>

And the final results are:

<img src="https://user-images.githubusercontent.com/25958734/111199274-699b4100-85fb-11eb-9005-49e1094843e2.png" width=350> <img src="https://user-images.githubusercontent.com/25958734/111199292-6dc75e80-85fb-11eb-88c7-cd74f23d5e7a.png" width=350>

**Comment by david-allison-1** [comment]
@Koorosh-J What does the latest version of Anki Desktop do? And how do we differ from this?

**Comment by Koorosh-J** [comment]
> 
> 
> I think you want to create a card with two or more blanks and type answers. This can be achieved by using {type:Field_name}}.
> 
> For example, I create a cloze with two fields: `Text` and `Extra`:
>  ...


Thank you for your suggestion, but this template work good on my desktop version my template is simple and looks like this:

Front Template:
----------------------------------------------
<div>{{cloze:Blanked_Text}}</div>
<br>
<div>{{Words_Suggest}}</div>
<br>
<div>{{type:cloze:Blanked_Text}}</div>

Back Template:
----------------------------------------------
<div>{{cloze:Blanked_Text}}</div>
 <br>
<div>{{type:cloze:Blanked_Text}}</div>

And in my card I filled fields like this:
----------------------------------------------
Blanked_Text: This is {{c1::test}} which is containing {{c1::test}} word twice
Words_Suggested: test - test1 - test2 - test

**Comment by Koorosh-J** [comment]
> 
> 
> @Koorosh-J What does the latest version of Anki Desktop do? And how do we differ from this?

Both android and desktop versions are the latest.

Desktop: 2.1.35
Android: 2.14.6

**Comment by LittleFish33** [comment]
@david-allison-1  In the original file, the project uses `set<String>` to save the correct answer to use for {{type::cloze::NN}} fields (refer to the `private String contentForCloze(String txt, int idx) ` function in AbstractFlashcardViewer.java). In this case, {{cloze:Text}} ignores repeated words because there cannot be duplicate elements in a set. Therefore, I change the type from `set<String>` to `ArrayList<String>`. I have tested it on my phone. A pull request has been made.

**Comment by david-allison-1** [comment]
> @david-allison-1 In the original file, the project uses `set<String>` to save the correct answer to use for {{type::cloze::NN}} fields (refer to the `private String contentForCloze(String txt, int idx) ` function in AbstractFlashcardViewer.java). In this case, {{cloze:Text}} ignores repeated words because there cannot be duplicate elements in a set. Therefore, I change the type from `set<String>` to `ArrayList<String>`. I have tested it on my phone. A pull request has been made.

Thanks! Would also be great to get an automated test to ensure we don't get a regression here.

**Comment by LittleFish33** [comment]
@Koorosh-J Hi, I have tried to use the template you described above, and I get the same results in both Desktop: 2.1.35 and Android: 2.14.6. Both the Desktop and Android require to type `test` only once. I am a little confused about this. Can you please check if the two clozes on your template are exactly the same？Or better, could you provide a `akpg` file of your template?

**Comment by Koorosh-J** [comment]
@LittleFish33
First let me thank you for working on this issue and then:

Wow, That is a magic sentence !! I have test it in my own desktop version and the result was what you have said (repeated "test" ignored), but if I add one more different word like "test2" the result will we true. I mean:

Blanked_Text: This is {{c1::test}} which is containing {{c1::test}} word twice {{c1::test2}}

On Desktop version: result is true (no word is ignored)
On Android version: result will ignore repeated "test" word.

**Comment by Koorosh-J** [comment]
@LittleFish33
First let me thank you for working on this issue and then:

Wow, That is a magic sentence !! I have test it in my own desktop version and the result was what you have said (repeated "test" ignored), but if I add one more different word like "test2" the result will we true. I mean:

Blanked_Text: This is {{c1::test}} which is containing {{c1::test}} word twice {{c1::test2}}

On Desktop version: result is true (no word is ignored)
On Android version: result will ignore repeated "test" word.

**Comment by LittleFish33** [comment]
> @LittleFish33
> First let me thank you for working on this issue and then:
> 
> Wow, That is a magic sentence !! I have test it in my own desktop version and the result was what you have said (repeated "test" ignored), but if I add one more different word like "test2" the result will we true. I mean:
> 
> Blanked_Text: This is {{c1::test}} which is containing {{c1::test}} word twice {{c1::test2}}
> 
> On Desktop version: result is true (no word is ignored)
> On Android version: result will ignore repeated "test" word.

@david-allison-1 
I have reviewed the corresponding code of Anki's desktop version. I think the reason behind this is because the Android version and Desktop version use different logic. This is how the Desktop handles the cloze:

```python
# https://github.com/ankitects/anki/blob/main/qt/aqt/reviewer.py
# lines 500-516
def _contentForCloze(self, txt: str, idx: int) -> str:
    matches = re.findall(r"\{\{c%s::(.+?)\}\}" % idx, txt, re.DOTALL)
    if not matches:
        return None

    def noHint(txt: str) -> str:
        if "::" in txt:
            return txt.split("::")[0]
        return txt

    matches = [noHint(txt) for txt in matches]
    uniqMatches = set(matches)
    if len(uniqMatches) == 1:
        txt = matches[0]
    else:
        txt = ", ".join(matches)
    return txt
```

It can be observed that `len(uniqMatches)` is not 1, the Desktop version will use the matches (which is not a `set`). While for the android version, `set` is always used.

This explains the two situations mentioned above:

1. For `Blanked_Text: This is {{c1::test}} which is containing {{c1::test}}.`, we have `len(uniqMatches)==1`, therefore both the Desktop and android will ignore the repeated words. 
2. For `Blanked_Text: This is {{c1::test}} which is containing {{c1::test}} word twice {{c1::test2}}`, we have `len(uniqMatches)!=1`, therefore the Desktop uses the matches (i.e., `test, test, test2`). While the android version always uses `set`, i.e., `test, test2`.

I think one possible solution is changing the android code to make it consistent with the Desktop version. What do your think about it?

**Comment by david-allison-1** [comment]
> I think one possible solution is changing the android code to make it consistent with the Desktop version. What do your think about it?

Sounds like the correct approach! Thanks so much for the investigation

Let's add a test case where AnkiDroid and Anki Desktop currently differ as well, to ensure we don't get any regressions

**Comment by Arthur-Milchior** [comment]
@dae Can you please confirm that this was indeed what you intended to do ? It seems slightly counter intuitive and before we port this feature in AnkiDroid I'd like to have confirmation that it is not a bug.

If there is a single string the user must write, but potentially write it many time (e.g. {"foo", "foo", "foo"}) then the result will contains "foo" a single time. However, if the users must write distinct string (e.g. {"foo", "bar", "foo"}) then the result will be "foo, bar, foo", with the repeated strings shown multiple time. I am surprised that it is shows to user this way

**Comment by dae** [comment]
Originally it just used a simple set, but users found that confusing when "one, two, one" become "one, two". But there are other users who take a paragraph and delete a word from it multiple times, so if we did not enforce any uniqueness, they may have to write out "one, one, one, one", which is kind of silly - so the single instance case is special-cased.
