### ISSUE TITLE
Add Changelogs in release builds

### ISSUE THREAD

**Issue by mrudultora** [ankidroid/Anki-Android#8230]
**Is your feature request related to a problem? Please describe.**
There is no option to view the changelogs in release builds (available only in debug mode).

**Describe the solution you'd like**
Adding the changelogs option in (Settings->Advanced Settings) similar to debug mode.

**Describe alternatives you've considered**
None

**Comment by mikehardy** [comment]
yes - as we discussed on Discord - thanks for logging this
