### ISSUE TITLE
Add device information (hardware manufacturer and device model number) to Debug Info copied to clipboard in app

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8234]
It occurs to me that we should probably add Vendor and Model (the device info) to the Debug Info in the app that people copy/paste here, it would be useful

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/8227#issuecomment-799634011_

Further details:
- "Debug Info" is what we instruct users to copy from the app here https://docs.ankidroid.org/help.html
- similar issue is #8142 (which has a PR I think, and shows where the code is)

**Comment by 2tanayk** [comment]
can I work on this issue?

**Comment by mikehardy** [comment]
Sure @2tanayk - but please wait for a moment before proposing a pull request - subscribe to the PR #8225 as it is work in the same area and will result in conflicts if you begin work before that is completed.

While waiting, it may help to at least exercise the crash reporting system's development features to make sure you can successfully cause a test crash and view the crash test results. 

https://github.com/ankidroid/Anki-Android/wiki/Crash-Reports#developing--testing-acra-functionality

From that point it should be relatively easy to grab `Build.` variables mentioned (with some examples here in a react-native module I maintain https://github.com/react-native-device-info/react-native-device-info/blob/master/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java - search for MANUFACTURER as an example) 

Then once #8225 is done you can make a pull request based on that work, with an example of what the report looks like as a link to the test acralyzer instance

**Comment by 2tanayk** [comment]
sure!

**Comment by david-allison-1** [comment]
@mikehardy 

I'm not sure I see the conflict: this relates to "Copy to Clipboard" rather than ACRA. We already get the device name/model in ACRA. 

This change will become less useful if "send error report" is used for bug reports, but it'll still provide value as we won't get this from all users

**Comment by 2tanayk** [comment]
sir do I need to setup an acralyzer instance or do I use the one already setup that is:
https://918f7f55-f238-436c-b34f-c8b5f1331fe5-bluemix.cloudant.com/acralyzer/_design/acralyzer/index.html#/dashboard/

**Comment by mikehardy** [comment]
Oh no! David you are right. I am sorry, this is a different area of the codebase, there is no relation to the ACRA and the exception reporting with the WebView information (though adding *that* to the copy debug info would also be nice here :-) - I apologize. You do not need to worry about acralyzer @2tanayk for this issue, sorry for the confusion that's my fault

**Comment by 2tanayk** [comment]
ok sir so,should I do this?

> It occurs to me that we should probably add Vendor and Model (the device info) to the Debug Info in the app that people copy/paste here, it would be useful

**Comment by 2tanayk** [comment]
This is what the copy debug info looks like right now:

AnkiDroid Version = 2.15alpha30

Android Version = 10

ACRA UUID = 83b2e646-bd14-47eb-be63-749b0b30210f

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment]
Yes, you may proceed and there should be no conflict with anyone else's work. Changing it to include hardware information (manufacturer, model) and (if it is possible? Also the [WebView user-agent information](https://github.com/ankidroid/Anki-Android/pull/8225/files#diff-16e6875e2e5f1fc02ccdb62ea3d1cb8c5b401a669f4931f8ebb9c403f5d1e683R143) as in the other linked issue) would be good

**Comment by 2tanayk** [comment]
sure👍
