### ISSUE TITLE
Saving coverage

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8239]
Automated test create a coverage report. That is, a folder with html document indicating exactly what is being tested currently and what is not. The report is saved in %AnkiDroidRoot%/AnkiDroid/build/reports/jacoco/jacocoUnitTestReport/html/index.html

The feature request consist in ensuring that the report of the current version of master is accessible online at a fixed URL. This would ensure that every contributor can check in a simple click what is not covered and where they can work to improve this coverage without needing to run command from terminal and open the correct file.

**Comment by mikehardy** [comment]
This exists. We get it for free with our codecov integration
https://codecov.io/gh/ankidroid/Anki-Android/tree/master/AnkiDroid/src/main/java
bookmark that link, view whatever files you like...

**Comment by Arthur-Milchior** [comment]
Thanks so much. I thought David stated that it only existed with comand line

**Comment by mikehardy** [comment]
I think it's just much faster to view it in the command line when you are actually developing locally.
But when you are reviewing things or inspecting things, I integrated codecov.io specifically for this reason: they've got the reports online (with tracking of change over time even...) so you can look at other branches, PR results etc

**Comment by Arthur-Milchior** [comment]
Feel free to disagree with https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#code-coverage if you disagree.
I really hope we can get more coverage. So that we can get more people starting on it. And probably that having an already made list will help start. That's all

**Comment by mikehardy** [comment]
That chunk of documentation looks great, thank you!
