### ISSUE TITLE
Jacoco test show coverage automatically

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8240]
Currently `./gradlew  jacocoTestReport` generates coverage in 
`%AnkiDroidRoot%/AnkiDroid/build/reports/jacoco/jacocoUnitTestReport/html/index.html`. However, this coverage is hard to find.

The feature request consists in:
* If the run is successful, adding a link to this report, with the entire path, so that the user can open it in a single click and know it exists
* Having an option to open the report automatically (If it's possible in gradle.) Whether this should be turned on or off by default should be discussed

**Comment by TarekkMA** [comment]
I have managed to do this in Gradle. If the jacoco task succeeds it will open index.html in the default browser. 

I did open the html using this function:
```groovy
def openInBrowser(path) {
    def os = org.gradle.internal.os.OperatingSystem.current()
    if (os.isWindows()) {
        exec { commandLine 'cmd', '/c', "start $path" }
    } else if (os.isMacOsX()) {
        exec { commandLine 'open', "$path" }
    }
}
```

The only thing missing is linux which I didn't find a built-in command that will open the html in the default browser. 

we can have the user input the Linux command in `local.properties` or as env variable.

**Comment by Arthur-Milchior** [comment]
I like the idea of using a local properties. I'd also like if you please to have a flag for this feature; as I don't want to see it used everytime tests are run

**Comment by david-allison-1** [comment]
@Arthur-Milchior `enable_coverage=false` in the `local.properties` should disable coverage.
