### ISSUE TITLE
[Bug] Text

### ISSUE THREAD

**Issue by asabir123** [ankidroid/Anki-Android#8241]
###### Reproduction Steps
Hi, 
I have put in a type in answer box where i can type in the answer, I have inlcuded images below. Whenever, I click the show answer button, the answer comes twice (1st with the question and 2nd below the questions in its normal space). Can you please help. 

![Screenshot 2021-03-14 at 9 23 53 PM](https://user-images.githubusercontent.com/80747952/111281382-c9faa480-8634-11eb-99e0-25c72da84a54.png)
![Screenshot 2021-03-14 at 9 23 43 PM](https://user-images.githubusercontent.com/80747952/111281384-c9faa480-8634-11eb-94b5-1a21749f3811.png)

##### Research
*Eter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ []] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi,


You want

```
{{Front}}

<hr id=answer>

{{type:Back}}
```

on the back.

Best,

David

**Comment by asabir123** [comment]
Hi,
I am having another problem when viewing images. Ever since Ive inserted an answer type in bar next to the question, none of my pictures are included in the answer. I have included 2 screenshots below:

________________________________

**Comment by david-allison-1** [comment]
Hi, @asabir123, you haven't included images

You might be better served on our mailing list, or reddit (see the in-app help section for more details).

**Comment by asabir123** [comment]
I have please check again,

________________________________

**Comment by david-allison-1** [comment]
@asabir123 Please come to the GitHub issue or use the mailing list, the pictures haven't been transferred to the GitHub issue

**Comment by asabir123** [comment]
i understand, can you please send me the link as I cant find it hence why I messaged you over email?
This would be greatly appreciated.

Thank you,
________________________________

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/issues/8241#issuecomment-812910279

**Comment by asabir123** [comment]
Hi
I am having another problem when viewing images. Ever since Ive inserted an answer type in bar next to the question, none of my pictures are included in the answer. I have included 2 screenshots below:
![Screenshot 2021-04-03 7 34 54 PM](https://user-images.githubusercontent.com/80747952/113488509-8a4a0e80-94b6-11eb-9a5f-54f87e2752b2.png)
![Screenshot 2021-04-03 7 34 44 PM](https://user-images.githubusercontent.com/80747952/113488510-8ae2a500-94b6-11eb-9c96-e0472e11ae1a.png)

**Comment by asabir123** [comment]
it just says screenshot...

**Comment by david-allison-1** [comment]
Tap "Cards", you'll have modified the card template

**Comment by asabir123** [comment]
what do i do after that?

**Comment by asabir123** [comment]
it comes to this page, could you also change the font to aerial. 
![Screenshot 2021-04-03 7 58 11 PM](https://user-images.githubusercontent.com/80747952/113488586-fcbaee80-94b6-11eb-816a-88cb01696cea.png)

**Comment by david-allison-1** [comment]
> it comes to this page, could you also change the font to aerial.
> ![Screenshot 2021-04-03 7 58 11 PM](https://user-images.githubusercontent.com/80747952/113488586-fcbaee80-94b6-11eb-816a-88cb01696cea.png)

Change `{{type:Back}}` to `{{Back}}`. Please use our mailing list in future for support queries.

**Comment by asabir123** [comment]
sure, will i still be able to type in my answer.

**Comment by asabir123** [comment]
and do i change it for both of them?

**Comment by david-allison-1** [comment]
If you want to type in your answer, use the `basic (type in answer)` note type.

If you also want a picture on the back, use a separate field to define it: https://docs.ankiweb.net/#/getting-started?id=notes-amp-fields

**Comment by asabir123** [comment]
Great thank you for your help! :)
