### ISSUE TITLE
Requesting user to translate

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8242]
The people who may be most interested and able to translate AnkiDroid are our users. 

I suggest to add a message to users, after their thousands review, asking them to contribute to the translation if the translation is not complete.
Waiting a thousand review ensure that people have actually used the app, and that we are not asking to people who just opened it for the first time.

In practice, I suggest we show the suggestion at startup, the first time there is more than a thousand reviews. So that we are not interrupting a review session.

I suspect that the most difficult part is figuring out whether a translation is entirely done or not. Ideally, if there is internet, the solution would be to query crowdin server, but I doubt we can do it. An alternative solution would be to query ankiweb website. In this case, it would require the website to be updated regularly, e.g. once a day, with the current values from crowdin. It should be simpler to do once a day update than once by user, and furthermore this can be done with crowdin private key if required. 

If this is not a practical solution, then, just we can just keep a hardcoded list of languages with missing translations, and update it when we sync translations. This means that even if someone does the entire translation in language L, every other user would see the request to translate for potentially some months. That's not ideal, but probably still better than the current situation where people don't even know they can help

**Comment by mikehardy** [comment]
I like this idea, but why not keep it simple?
English translations are not needed so, this simple rule?

- If we are starting up
- If the user interface language is not English
- If we have not shown the "help us translate" dialog yet
- If the user has more than 1000 reviews
- Note in preferences that we have shown the "help us translate" dialog and show the dialog

**Comment by Arthur-Milchior** [comment]
```
If
 we are starting up &&
 the user interface language is not English &&
 we have not shown the "help us translate" dialog yet &&
 the user has more than 1000 reviews
then:
  show the dialog;
  save in preferences that we have shown the "help us translate" dialog
```
Is it what you meant? I had trouble understanding without the then. Especially since you first note you showed the dialog and then showed it.

That's fine by me. Slighty useless to show it when translation exists. But maybe cool if people understand what free software really mean.

**Comment by mikehardy** [comment]
In every translation except maybe 2 there are missing strings, and we add strings all the time, so I think it's a lot of complexity with little benefit

And yes! That's the pseudo-code I meant. I want to save in preferences first - and know it's saved - just for the 0.00001% case where for some reason the app crashes and we get it into some terrible loop of showing the dialog every time. Saving the pref first then displaying the dialog means we are by default maybe showing the dialog too few times, but we will definitely not show it too many times

**Comment by Arthur-Milchior** [comment]
I'm fine with it. If user starts complaining, we can always change in update later. But seems to make perfect sens. Just have to wait until someone work on it. (That's so strange to think it's a realistic idea)

**Comment by dae** [comment]
It's a noble idea, but as nobody has responded in over 2 years, I wonder whether it might be better to close this and reduce the issue count?
