### ISSUE TITLE
Decoupling CardViewer and card content

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8243]
Currently, the `AbstractFlashCardViewer` is very coupled with actual card content. For example `mCardContent` contains the question/answer text to be displayed as html, `mSoundPlayer` contains all sounds which are going to be played...

This mean in particular that it is currently impossible to do any work in advance, in background, since computing the list of sound is equivalent to playing it, and there is no function to compute the html content without displaying it.

At least for the code quality, decoupling a card content from the actual activity displaying the card seems useful. Hopefully, it would also be a first step toward solving https://github.com/ankidroid/Anki-Android/issues/7902

**Comment by TarekkMA** [comment]
Seems like a good task, I would like to try tackling this issue.

**Comment by IAmJaishree** [comment]
@Arthur-Milchior  do you have any suggestions or ideas for its implementation in mind already or it's a free path to explore?
I would like to work on this issue.

**Comment by Arthur-Milchior** [comment]
If you're not already working on something else, I'll happy give you this task.

I do not have anything specific in mind. 
I assume that ideally, we should have a data structure which contains all the informations needed to display card content. That is:
* the text (css + html)
* the media player with media filled, not yet playing
* if it's an answer, the number of buttons to show
* Anything else I'd have missed that is used

and the reviewer or abstract flash card viewer can take this and display it's content without needing to access database at all.

**Comment by IAmJaishree** [comment]
@Arthur-Milchior I have other issues but and I raised a PR for them, I can work on this now if you want.

**Comment by Arthur-Milchior** [comment]
Then please go for it.

**Comment by Arthur-Milchior** [comment]
Any news @IAmJaishree ?

**Comment by BrayanDSO** [comment]
I'm currently rewriting the reviewer (#14302), which include this.
