### ISSUE TITLE
[Bug] Changing note type in note editor make fields non clickable

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#8247]
###### Reproduction Steps

1. Open deck
2. Edit note
3. Change note type
4. Click on fields, it is not clickable
5. Change type to original note type now fields are clickable.

###### Expected Result
It should make other fields clickable in note editor when note type change.

###### Actual Result
It is not making fields clickable.
<img src="https://user-images.githubusercontent.com/12841290/111357047-e85bb100-86c3-11eb-9645-21ff5823e25b.gif" height=450></img>

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.15alpha30

Android Version = 11

ACRA UUID = c36be804-6080-4d1b-a9e7-5633cd4703fe

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

Model = Samsung M30s

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
This is semi-intentional - changing note type is intended to allow a user to select "Field A goes to Field B in he new note type" - try it out with a note type with multiple fields, this doesn't work as well if the user can also edit the fields.

That being said, the UX is bad, and could do with fixing. We could patch this up by greying out the fields.

**Comment by Ekagra** [comment]
I want to work on greying out the fields if nobody's working on it, if that make sense.

**Comment by david-allison-1** [comment]
Personally, I'd be happy with it, but I think we should see what other maintainers think. 

Maybe we'll want a larger redesign of the screen rather than patching the issue.

**Comment by Ekagra** [comment]
ok sounds good

**Comment by mikehardy** [comment]
The whole screen needs a new layout. Specifically for changing note type though, can you post screenshots  or a quick screen recording of how AnkiDesktop handles it?

**Comment by infinyte7** [comment]
Anki Desktop have no option to change note type and deck.

![1](https://user-images.githubusercontent.com/12841290/111875494-0a5f7700-89d5-11eb-9078-5d997e12130e.gif)

**Comment by mikehardy** [comment]
what what :sweat_smile:  ? We appear to be diverging already then, so let's go as easy as possible, if it is possible to simply gray them out, that works for me

**Comment by mrudultora** [comment]
@infinyte7 I am unable to reproduce this. It's working completely fine in my device.

**Comment by infinyte7** [comment]
Then may be again it is problem with Samsung One UI 3.0

**Comment by infinyte7** [comment]
@mrudultora I have tested it one other phone Moto and Asus
And problem persists.

1. Install some shared deck from AnkiWeb
2. Import in AnkiDroid 
3. Select a deck and review
4. Click edit from options menu
5. Change type of note
6. Click on fields
Fields are non clickable.

In AnkiDesktop change deck and note type not available so, ```setVisibility=GONE``` can be done when edit option clicked.

**Comment by mrudultora** [comment]
@infinyte7 Yes, now I am able to reproduce. Are you working on this ?

**Comment by infinyte7** [comment]
No, I am working on other projects.

**Comment by prateek-singh-3212** [comment]
@mrudultora Are you working on this issue?

**Comment by mrudultora** [comment]
@prateek-singh-3212 No!

**Comment by tapish2000** [comment]
I will try to look into this one if no one minds.

**Comment by prateek-singh-3212** [comment]
I would like to work on this issue.

**Comment by mikehardy** [comment]
Sounds great, this looks like a great example of collaboration among everyone too, it is really great to see :-)

**Comment by prateek-singh-3212** [comment]
![Issue 8247](https://user-images.githubusercontent.com/76490368/112447458-59abfb80-8d77-11eb-8595-919b287304a0.gif)
I have greyed out the EditText Fields as demonstrated in the above video. Is it is correct?
here is the code:
![issue 8247 code snippet](https://user-images.githubusercontent.com/76490368/112448565-86144780-8d78-11eb-9699-853c229a9cdb.png)

**Comment by david-allison-1** [comment]
> ![Issue 8247](https://user-images.githubusercontent.com/76490368/112447458-59abfb80-8d77-11eb-8595-919b287304a0.gif)
> I have greyed out the EditText Fields as demonstrated in the above video. Is it is correct?
> here is the code:
> ![issue 8247 code snippet](https://user-images.githubusercontent.com/76490368/112448565-86144780-8d78-11eb-9699-853c229a9cdb.png)

Looks good! Could you put in a PR?

**Comment by prateek-singh-3212** [comment]
Yes, Sure
