### ISSUE TITLE
Document searching legacy Google Code Issues

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8249]
This should take < 1 hour to do.

----

Before GitHub, we used [Google Code](https://en.wikipedia.org/wiki/Google_Developers#Google_Code) to track issues

It is sometimes useful to look up past issues in the old issue tracking system, the issues have been migrated to GitHub, but a specific search query in GitHub will find this issue.

I would like instructions in the developer guide (near the bottom) for improving discoverability of this for new developers.

I would like this implemented as a [Google Chrome Search Engine](https://zapier.com/blog/add-search-engine-to-chrome/)

Example: I want a search for `gc 2208` to return a GitHub search listing https://github.com/ankidroid/Anki-Android/issues/3105 as the result

This doesn't need to include an explanation of how to use Google Chrome, just a link to: https://zapier.com/blog/add-search-engine-to-chrome/ or similar google tutorial, the URL string which allows the search, and possibly a suggested search keyword

**Comment by TarekkMA** [comment]
Implementing it as a custom search in Google Chrome directly, wouldn't be feasible. The old issue ID not found in the URL. so we can't know that 2208 points to 3105 right away.

- We could scrap all the migrated issues and extract the old gc id and the new gh id.
- Build a GitHub static site with the mapping of these issues, using JavaScript.
- So for example the url of the static site would be: https://ankidroid.github.io/gc/
- The url for searching for `gc 2208` would be https://ankidroid.github.io/gc/2208
- Using JS we extract the path and using the mapping file we redirect the user.

After that implementing it as a custom search will be fairly easy.

What do you think about this proposed implementation? And do you have any pointer on how we should filter these migration issues, I noticed one user named `hssm` who ported all the issues.

**Comment by TarekkMA** [comment]
This task seems interesting, if my proposal is okay, I would love to give it a try

**Comment by david-allison-1** [comment]
A search engine will work:

`https://github.com/ankidroid/Anki-Android/search?q=%22Originally+reported+on+Google+Code+with+ID+%s%22&type=issues`

https://github.com/ankidroid/Anki-Android/search?q=%22Originally+reported+on+Google+Code+with+ID+2208%22&type=issues

**Comment by TarekkMA** [comment]
Oh, I wasn't using quoted search terms, that's why my results looked unreliable.

**Comment by david-allison-1** [comment]
No worries! It wouldn't be worth doing for anything more complex - it's something that occurs rarely, and has value, but not enough to expend hours of dev effort on.

**Comment by david-allison-1** [comment]
Done: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#custom-search-engines
