### ISSUE TITLE
[BUG] Progress Dialog of NoteEditor extra space

### ISSUE THREAD

**Issue by imaryandokania** [ankidroid/Anki-Android#8252]
###### Reproduction Steps

1. Go to "add notes"
2. after adding all details try to save them 
3. The progress Dialog will appear with some issues.

###### Expected Result

![Screenshot_1615946584](https://user-images.githubusercontent.com/61244704/111403480-27eec100-86f5-11eb-8768-223f18101ec3.png)

###### Actual Result
![Screenshot_1615822428](https://user-images.githubusercontent.com/61244704/111403538-3c32be00-86f5-11eb-8f66-836d077341c7.png)

###### Debug info
Small changes of title in progress dialog

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Arthur-Milchior** [comment]
I'm sorry, but I fail to follow what's going on here. You write "add deck option", but you show "add note" screen shot. 
I tried "+" then "create deck" and that still works on my phone
I also tried to change deck option and it seems to still work. I'd really like more specific description.

**Comment by imaryandokania** [comment]
> I'm sorry, but I fail to follow what's going on here. You write "add deck option", but you show "add note" screen shot.
> I tried "+" then "create deck" and that still works on my phone
> I also tried to change deck option and it seems to still work. I'd really like more specific description.

Yes it was a typo error sorry again, this problem is similar to what was in login page , the title is filled with spaces , the new version require it to be null
