### ISSUE TITLE
UI support for right-to-left (RTL) languages

### ISSUE THREAD

**Issue by eginhard** [ankidroid/Anki-Android#8259]
This is an umbrella issue to track right-to-left (RTL) language support improvements in the AnkiDroid UI (as opposed to showing cards with RTL content).

**We would love any help taking specific items from this and implementing them!** Especially from people who can at least read a RTL language like Arabic, Farsi, Hebrew or Urdu and have experience with using apps in these languages. However, it is also possible to force a RTL layout for other languages like English in the [developer options](https://developer.android.com/studio/debug/dev-options#drawing).

To keep things organized the issue itself will be edited as things are defined and tracked. Comments will just be used for discussion not actual tracking.

In #8261, basic RTL support was added. Now it should be possible to examine different parts of the app separately and create appropriate issues if anything else is not correctly handled.

**Resources:**
- General information: https://dotancohen.com/howto/rtl_right_to_left.html
- Android documentation: https://developer.android.com/training/basics/supporting-devices/languages#SupportLayoutMirroring
- Material Design guidelines: https://material.io/design/usability/bidirectionality.html#mirroring-layout

**Related items:**
- ~~#4371: RTL layout in the deck overview screen~~
- ~~#8191: The input stepper added in this PR should have RTL support~~
- #7767: Note Editor: Preview of mixed RTL Text mismatches EditText
- ~~#8396: RTL support for activity transition animations~~
- ~~#8282: RTL lint rules~~
- ~~#8984: RTL statistics screen~~

**Comment by irshadmd** [comment]
I would like to work on this, I know Urdu and Arabic too

**Comment by TarekkMA** [comment]
Sorry, @irshadmd. I talked with @eginhard about me taking this issue on discord.

**Comment by TarekkMA** [comment]
@eginhard I have figured out why the UI wasn't reacting to being changed to an RTL locale. We needed to explicitly state that we want to support RLT.

Both issues you linked will be solved with the PR I posted. There will still be some work to do to support RTL completely as some of the xml designs is hard coding the directionally.

**Comment by eginhard** [comment]
@irshadmd @TarekkMA Thanks both of you for volunteering, previously there weren't any contributors at all with the relevant language knowledge! It's nice to see that updating the manifest is already a big improvement, but I expect there will still be other more subtle issues and I'd suggest to work together on those.

You could go through the app together with the change in #8261 and decide how to divide any issues that you spot. Just communicate clearly so that no work is duplicated. It will be especially helpful if you could review each other's PRs related to this.

**Comment by TarekkMA** [comment]
Okay no problems, we can merge #8261 then move on to fixing other issues. I will fix the issue with DeckPicker and the wrong back arrow direction in study options. and @irshadmd make sure to tag me in your PR

**Comment by irshadmd** [comment]
okay sounds great🚀

**Comment by dotancohen** [comment]
I've noticed that the Statistics screen in RTL starts with the tabs scrolled all the way to the left.

What should happen:
1. The Overview tab, which is now the rightmost tab, should be displayed.
2. The tab selector should be scrolled to the right, so that the Overview tab's tab indicator is shown.

What currently happens:
1. The Overview tab, which is now the rightmost tab, should be displayed. (this is correct)
2. The tab selector is scrolled to the left, so that the Card Types tab's tab indicator is shown. (this is wrong)

**Comment by mikehardy** [comment]
Peeled off as a work item in #8984 @dotancohen - thanks for the report!

**Comment by dotancohen** [comment]
Now that the version with proper RTL support has been rolled out to my entire family, we're all in agreement that the Again/Hard/Good/Easy button order should not have been reversed.

I don't know about other RTL locales, but for Hebrew (Israel) muscle memory functionality is never reversed. So e.g. scrollbars are reversed (not critical muscle memory) but e.g. the OK/Cancel buttons on OS dialogue boxes are not. By this pattern, the Again button should remain on the left no matter the directionality of the UI as a whole.

**Comment by dae** [comment]
If you're used to the old order I imagine adjusting will be a pain, but wouldn't RTL order be more logical for people new to the program? The computer version also shows the answer buttons from right to left in Hebrew FWIW.

**Comment by david-allison-1** [comment]
My comment from reddit:

> Could you raise this on the issues?
>
> I'm hesitant on this one - we become consistent with Anki Desktop with this change, as it reverses the buttons if Hebrew is selected
>
> https://i.ibb.co/6JBVRqN/image.png

https://www.reddit.com/r/Anki/comments/nkct2f/ankidroid_2150_changelog/gzorpvs/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by dotancohen** [comment]
> If you're used to the old order I imagine adjusting will be a pain, but wouldn't RTL order be more logical for people new to the program? The computer version also shows the answer buttons from right to left in Hebrew FWIW.

This is a further argument for not switching the directionality of critical UI components. My desktop is LTR, my phone is RTL. This is extraordinarily common here. If you would like, I could survey some neighbours to see how their desktops and phones are configured.

It would be an interesting question why desktops are typically LTR here but phones are RTL. My _guess_ would be that people just leave things in the default state.

**Comment by eginhard** [comment]
It should be fine to close this now. There's only one open issue left that is linked from here and it's also not strictly UI related.

Otherwise it doesn't seem like there have been new RTL issues recently. Anything else that comes up can be reported in a separate issue.

**Comment by mikehardy** [comment]
Very slowly moving towards "the good" - gotta get 2.16 out so all the work here and everywhere else sees the light of day...
