### ISSUE TITLE
Moving Support AnkiDroid to Navigation Drawer

### ISSUE THREAD

**Issue by mrudultora** [ankidroid/Anki-Android#8260]
**Is your feature request related to a problem? Please describe.**
As we are not having translations (may be users are not interested or they don't know about this option that they can contribute), some changes should be done.

**Describe the solution you'd like**
 I think we should move **Support AnkiDroid** to Navigation Drawer (we can just experiment with different things and then only we could know the most productive way in this matter).
I opened this issue as it was suggested here https://github.com/ankidroid/Anki-Android/issues/8205#issuecomment-799716807
Opened for discussions.

**Comment by oddlyspaced** [comment]
I would love to work on this

**Comment by mrudultora** [comment]
@oddlyspaced Hi, as of now this issue is opened to get views of all the members. So, please don't work on this now. Let's wait for there views.

**Comment by oddlyspaced** [comment]
Sure! @mrudultora

**Comment by david-allison-1** [comment]
I've been considering this for a few versions. I like it, but wait for a little more discussion

**Comment by oddlyspaced** [comment]
Instead of just moving the option, we can possibly add an alert dialog when the user launches the app presenting them the option to ask for translation and everything related to it. The alert dialog can be shown after a while when the user has used the app. Like about 10-20 launches or whatever threshold we set.

**Comment by Akshay0701** [comment]
Instead of showing alert dialog to each new user , we can check whether user spend enough time on app to request support from user ,this will not annoy user.

**Comment by mikehardy** [comment]
I'll defer to you @david-allison-1 - I like it in general as well though. There is available real estate there and especially because translations don't involve any money it is not like we are begging, we are just asking. And as my momma always said "if you don't ask, you don't get"

**Comment by Arthur-Milchior** [comment]
I'd be interested to know what you mean about "support". Because https://github.com/ankidroid/Anki-Android/wiki/Contributing is really really big. We probably can't translate all of this in all languages. I don't know what makes sens to translate. (E.g. asking for help for translation is useless, if the person don't speak english they can't translate. Asking for money make sens, but I'm not sure I'd want to always highlight this when the drawer opens)

**Comment by mrudultora** [comment]
@Arthur-Milchior It's true that all of that cannot be translated, but at least it would help in increasing the frequency of translations because there are currently 2M active users. Its ok if we don't have 100% translations. Something is better than nothing :-)

**Comment by Arthur-Milchior** [comment]
I entirely agree that we don’t need peffrection. My question was about asking for more detqils about the proposal

**Comment by david-allison-1** [comment]
Let's go ahead with this.

RE: Translations - I don't feel these will be necessary immediately 

From the "Support AnkiDroid" menu that we have: 

![image](https://user-images.githubusercontent.com/62114487/111860421-34fef080-893f-11eb-92c1-87a491299666.png)

* ✔️ Donate - Open Collective's responsibility to handle
* ✔️ Translate - no need for translation of the output, translation will be difficult without a grasp of English
* ⚠️ Develop - I think development is primarily English-only, I don't think there's value in translating the dev guide at this stage
* ✔️ Rate - No need for translation
* ⚠️ Other - https://github.com/ankidroid/Anki-Android/wiki/Contributing ❌ This page needs updating before we consider translations - "Sponsor Development"/"App Store maintenance" may want to be deleted/rewritten/moved to another page at the very least
* ❌ Send Feedback - Partially translated, we might want to move this to CrowdIn as a separate issue: https://github.com/ankidroid/Anki-Android/blob/24443a327ed060dc31f4c16c88a3553d50d7ad05/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L571-L587

**Comment by mikehardy** [comment]
@david-allison-1 good analysis - I agree on all the specific line items and your determination on each

**Comment by kartikeysaran** [comment]
Cani take up this issue !

**Comment by mrudultora** [comment]
@kartikeysaran I am already working on it.

**Comment by mrudultora** [comment]
@david-allison-1 Which all options we have to include in dialog box ? According to your previous replies in this thread I have excluded _Send feedback_.

**Comment by david-allison-1** [comment]
> @david-allison-1 Which all options we have to include in dialog box ? According to your previous replies in this thread I have excluded _Send feedback_ and _Rate_.

Sorry - missed this. Might as well be the same as is in "Support AnkiDroid" currently (just transpose the menu to the top level)
