### ISSUE TITLE
Replacement of SeekBarPreference with IncrementerNumberRangePreference

### ISSUE THREAD

**Issue by haran2248** [ankidroid/Anki-Android#8262]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Dragging the SeekbarPreference can be replaced by just typing in an editText or incrementing the values in the field

**Describe alternatives you've considered**
The Seekbar Preference can be replaced with normal EditText as well.

**Additional context**
 This issue was just an extension of #8024.There are places we can add similar features in the UI
![WhatsApp Image 2021-03-18 at 00 33 07](https://user-images.githubusercontent.com/56928954/111534735-54a2e700-878e-11eb-904d-b07b7186df9b.jpeg)
![WhatsApp Image 2021-03-18 at 00 32 22](https://user-images.githubusercontent.com/56928954/111534740-55d41400-878e-11eb-8a21-f9b8c405bb37.jpeg)

**Comment by david-allison-1** [comment]
Copied from my comment on Discord

> No need, we need to do better with that screen, but that's not the solution IMO
> Our main problem with that screen is that people don't understand that time uses modular arithmetic, so they'll be asking "how do I set 25 hours past midnight"

> 25 % 24 = 1. That's the UX problem that we need to solve

**Comment by haran2248** [comment]
> Copied from my comment on Discord
> 
> > No need, we need to do better with that screen, but that's not the solution IMO
> > Our main problem with that screen is that people don't understand that time uses modular arithmetic, so they'll be asking "how do I set 25 hours past midnight"
> 
> > 25 % 24 = 1. That's the UX problem that we need to solve

ohh ok ill try to work on that.Is there any other issue of that sort?

**Comment by david-allison-1** [comment]
There is now: https://github.com/ankidroid/Anki-Android/issues/8267. Closing this as WONTFIX
