### ISSUE TITLE
[Bug] Sync failing

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8265]
Full sync fails. Currently, I try to force upload. My main deck Everywhere has got 1550 review and 55 cards (so 1605 cards) in learning on ankidroid and 1770 green cards on ankiweb (review+learning). 

This occurs just after https://github.com/ankidroid/Anki-Android/issues/8264 and after https://forums.ankiweb.net/t/full-sync-failed/8449/2 but since it's a full sync, I don't see how it could really fails that much. Maybe I'd need @dae help here if it's related to ankiweb side.

I'm running 67f0938 sched V2

**Comment by Ekagra** [comment]
Is database the problem for this issue ?

**Comment by Arthur-Milchior** [comment]
I've no idea what the exact problem is. And since the server is closed source, I sadly can't try to check entirely.

A potential issue is that the green number in anki is not the sum of the last two columns. But I doubt that it is the entire problem because ankidroid and anki do not show me the same card to review

**Comment by david-allison-1** [comment]
Don't discount this potentially being caused by the transition to Rust-based database access if it's not reproducible in 2.14,X. 

How would we go about diagnosing this?

**Comment by Arthur-Milchior** [comment]
I did look at ankiweb, so that I can avoid an extra sync.

**Comment by Arthur-Milchior** [comment]
By the way, this is after a full sync from phone to ankiweb. During those sync, the database is closed and sent verbatim, so it seems hard for the rust library to break it

**Comment by dae** [comment]
Arthur, are you reporting a separate issue to the one you posted about on the Anki forums? If so, what is the error you are getting?

You can test the syncing protocol locally with https://github.com/ankitects/anki/blob/main/docs/syncserver.md

**Comment by Arthur-Milchior** [comment]
I have no idea whether they are related. only that they occured at the same time.

My current understanding is that it is a difference in the way of counting review cards from subdecks actually.

**Comment by dae** [comment]
What is the error you are getting?

**Comment by Arthur-Milchior** [comment]
I do not get any error message. Simply, the number of cards in the second column on ankiweb were quite bigger than the sum of the second and third column on ankidroid (card in learning and review). Which I took as an indication that sync failed. Now I understand it's probably that we are counting things differently.

**Comment by david-allison-1** [comment]
@Arthur-Milchior Is this still occurring?

**Comment by Arthur-Milchior** [comment]
Not anymore. I just checked and now numbers agree, while they did not during multiple day. No idea why. That's why I asked for tests regarding filling the queues. Guess I'll eventually do myself as it do not seems to advance.
