### ISSUE TITLE
"NOT_FOUND_DECK_ID" should be deleted.

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8266]
"NOT_FOUND_DECK_ID" is used in DeckPicker. It is potentially set as preference for browserDeckIdFromDeckPicker . However this value is never read. Which lead me to suspect that REQUEST_BROWSE_CARDS request is entirely useless. Should be investigated. 

This should wait for #8196 to be merged first so that the constant is not used

**Comment by haran2248** [comment]
Can i work on this?

**Comment by haran2248** [comment]
There seems to be no function which moves to onActivityResult with REQUEST_BROWSE_CARDS as a requestCode,So i dont think it wil be useful,Shall make a PR deleting that PR?

**Comment by haran2248** [comment]
There seems to be no function which moves to onActivityResult with REQUEST_BROWSE_CARDS as a requestCode,So i dont think it wil be useful,Shall make a PR deleting that PR?

**Comment by Arthur-Milchior** [comment]
Please do so.

> There seems to be no function which moves to onActivityResult with REQUEST_BROWSE_CARDS as a requestCode,So i dont think it wil be useful,Shall make a PR deleting that part?

If there is a difference with what I wrote, please let me know. It seems similar
