### ISSUE TITLE
Improve "Start of Next Day" UX

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8267]
> Our main problem with that screen is that people don't understand that time uses modular arithmetic, so they'll be asking "how do I set 25 hours past midnight"

> 25 % 24 = 1. That's the UX problem that we need to solve

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8262#issuecomment-801522836_

**Comment by david-allison-1** [comment]
@haran2248 - this one's yours if you'd like

**Comment by haran2248** [comment]
Yes i would like to work on this

**Comment by haran2248** [comment]
There is a seekbar which ranges from 0 to 23,Do you want me to change that?Do you want users to type the start of the next day in an editText?Can you guide with what exactly is to be done?

**Comment by david-allison-1** [comment]
I don't know what should be done right now. I know that our current UI isn't sufficient to guide the user to a correct solution.

Starting work on this issue will involve coming up with a design that makes sense and solves the above UX issue.

We should discuss designs and see what other maintainers think.

I believe that an `EditText` would make things worse, as we want the user to select a number of hours between 0 and 24.

Maybe we want a clock display with only hours?

**Comment by mikehardy** [comment]
it's a small set of numbers, and they are linear so I still like a seek here
a label change (that is: just using better text) might be sufficient?

"Please select the hour you want to use as the "start of next day", 0 represents midnight, 23 is 11pm, etc"

This is not something many users will ever do, and even those that do change it will not change it often, they are going to do it once so we can have them think a bit, and as a rarely used feature we should not spend a lot of time

fast + easy == done

**Comment by haran2248** [comment]
> it's a small set of numbers, and they are linear so I still like a seek here
> a label change (that is: just using better text) might be sufficient?
> 
> "Please select the hour you want to use as the "start of next day", 0 represents midnight, 23 is 11pm, etc"
> 
> This is not something many users will ever do, and even those that do change it will not change it often, they are going to do it once so we can have them think a bit, and as a rarely used feature we should not spend a lot of time
> 
> fast + easy == done

sure that works as well
