### ISSUE TITLE
Check media and delete deck popup have white space on top

### ISSUE THREAD

**Issue by infinyte7** [ankidroid/Anki-Android#8272]
###### Reproduction Steps

1. Check media from options menu or delete deck
2. Popup appear with white space
3. 

###### Expected Result
No white space at top of popup

###### Actual Result
<Img src="https://user-images.githubusercontent.com/12841290/111732752-42af6a00-889c-11eb-848d-94b9dda73e59.jpg" height=500></img>
<Img src="https://user-images.githubusercontent.com/12841290/111732755-4511c400-889c-11eb-9203-9ef3f23677f4.jpg" height=500></img>

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x ] I have searched for similar existing issues here and on the user forum
- [ x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Ekagra** [comment]
I am working on this

**Comment by bishalbar77** [comment]
I am working on this

**Comment by david-allison-1** [comment]
> I am working on this

@bishalbar77 - It'd be best to find something different to save duplicated effort, it won't be a large change to fix

**Comment by Ekagra** [comment]
@david-allison-1 thanks for assigning me

**Comment by bishalbar77** [comment]
Okay @david-allison-1

**Comment by Ekagra** [comment]
before making a PR, I would like to confirm only dialogues mentioned in the issue are to be fixed? there might be other ones with white spaces too.

**Comment by mikehardy** [comment]
I think for a change like this you can/could/should fix any that you see with the same problem. Best to do them all at once

**Comment by david-allison-1** [comment]
Could we replace `""` with `null` inside `StyledProgressDialog`'s methods? Would stop this from occurring in future.

**Comment by Ekagra** [comment]
@david-allison-1 that's exactly what I am doing and it's working fine
