### ISSUE TITLE
Adding a CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by adrishyantee** [ankidroid/Anki-Android#8273]
Hello, how about adding a Code of Conduct as a markdown file to this repository or to Contributing.md file so that new contributors are well aware of the rules and regulations while making any contributions to this repository.

We can add sections like:
-  Pledge
-  Standards
-  Scope
-  Enforcement
-  Attribution

I will be adapting from the Contributor Covenant, version 1.4, which is available [here]( https://www.contributor-covenant.org/version/1/4/code-of-conduct.html)

If you like this idea, you can assign it to me, and then I will work on this.
I will make a pull request so that you know what changes I am going to make.

**Comment by mikehardy** [comment]
Before doing anything like this we actually need an email address that can handle things like this and as of yet we don't have one

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [INSERT EMAIL ADDRESS]. 

We don't really have infrastructure for that unfortunately.

The document you link seems good as far it goes though. Please don't act on this but it is blocked on core maintainers implementing some sort of contact solution.

**Comment by adrishyantee** [comment]
Okay, I totally understand the difficulty in managing such a big thing. I will be waiting for all the maintainers to make necessary arrangements before taking this sort of thing into account.
