### ISSUE TITLE
[Deprecation] Move to new Crowdln API

### ISSUE THREAD

**Issue by TarekkMA** [ankidroid/Anki-Android#8274]
![Screen Shot 2021-03-19 at 9 59 55 AM](https://user-images.githubusercontent.com/6633545/111749273-375b3f00-889a-11eb-8f85-85a414ac9b83.png)

We should move to API 2.0 before the end of the year

**Comment by mikehardy** [comment]
That's unfortunate, already plenty to do but it is always something in a large project :-)
Thanks for logging this.

**Comment by tapish2000** [comment]
Can I take this issue?

**Comment by david-allison-1** [comment]
> Can I take this issue?

This may be complex - I feel it might be better if you take a different issue while you're getting used to the project

**Comment by david-allison** [comment]
Would probably need to check with CrowdIn support about getting the project verified as open source, we're very close to the 60k strings limit which pushes you to paid territory if you're not an open source app

**Comment by krmanik** [comment]
I will give it a try.

**Comment by mikehardy** [comment]
Champion :trophy: ! let me know if you need any advice or anything, this is so important to project continuity that I really want to see this get done and I will help any way I can

**Comment by krmanik** [comment]
Okay, Thanks

**Comment by krmanik** [comment]
@mikehardy @david-allison 

I have updated this shell script to find broken strings. The typescript approach is slower and may not catch the expected errors.

This is added in below script.
```
'<!--'
'%d%%'
'%s%%'
'%1$d%%'
'%1$.1f'
 '%1$.2f'
 '%2$.2f'
 '%3$.1f'
```

Will this script handle the expected errors?

```shell
#!/bin/bash
# Spot malformed string replacement patterns in Android localization files.
# Hopefully it will prevent this kind of bugs: https://code.google.com/p/ankidroid/issues/detail?id=359

# shellcheck disable=SC2016
EXIT_STATUS=0

VALUES=res/values/10-preferences.xml

pushd AnkiDroid/src/main > /dev/null || exit 1
if grep -RHn "%1$ s" $VALUES; then
  echo "Found '%1$ s'-related error"
  EXIT_STATUS=$((EXIT_STATUS + 1));
fi
if grep -RHn "%1$ d" $VALUES; then
  echo "Found '%1$ s'-related error"
  EXIT_STATUS=$((EXIT_STATUS + 1));
fi
if grep -RHn "%1" $VALUES | grep -v "%1\\$"; then
  echo "Found '%1'-related error"
  EXIT_STATUS=$((EXIT_STATUS + 1));
fi

# This is currently not working and I'm not sure why? It worked a couple days ago as of 20200516
echo "The next test will likely only run correctly on macOS. On Ubuntu it does not work well."
if grep -RHn '%' $VALUES |
 grep -v '<!--'     | # Filter comments
 grep -v '%d%%'     |
 grep -v '%s%%'     |
 grep -v '%1$d%%'   |
 grep -v 'pref_summary_percentage' |
 sed -e 's/%/\n%/g' | # Split lines that contain several expressions
 grep '%'           | # Filter out lines that do not contain expressions
 grep -v ' n% '     | # Lone % character, not a variable
 grep -v '(n%)'     | # Lone % character, not a variable
 grep -v 'n%<'      | # Same, at the end of the string
 grep -v '>n% '     | # Same, at the beginning of the string
 grep -v '%で'      | # Same, no spaces in Japanese
 grep -v '%s'       | # Single string variable
 grep -v '%d'       | # Single decimal variable
 grep -v '%[0-9][0-9]\?$s' | # Multiple string variable
 grep -v '%[0-9][0-9]\?$d' |  # Multiple decimal variable
 grep -v '%1$.1f'   | # ?
 grep -v '%1$.2f'   |
 grep -v '%2$.2f'   |
 grep -v '%3$.1f'   |
 grep -v '%.0f'     |
 grep -v '%.1f'     |
 grep -v '%\\n'     |
 grep -v 'stats_overview_card_types_'
then
 echo "Found grep errors in $VALUES"
 EXIT_STATUS=$((EXIT_STATUS + 1))
fi

if grep -RHn '％' $VALUES; then
  echo "Found errors in simple '%' grep"
  EXIT_STATUS=$((EXIT_STATUS + 1));
  fi

if grep -RHn "CDATA " $VALUES; then
  echo "Found CDATA-related errors"
  EXIT_STATUS=$((EXIT_STATUS + 1));
fi

${ANDROID_HOME}/cmdline-tools/latest/bin/lint --check StringFormatInvalid ./res
popd > /dev/null || exit 1
echo "Exiting with status $EXIT_STATUS"
exit $EXIT_STATUS
```

**Comment by krmanik** [comment]
The lint catch the errors that I am trying to implement in `check.ts` file.

The following lint check errors in localized strings also and it is faster. 

Check string format errors like `%1$ s` (space after $) and other errors in `<string>`
```
lint --check StringFormatInvalid ./res
```

Check error for `%1 $s` (space after %1)
```
lint --check StringFormatCount ./res
```

Check if localized string contains `one`, `few`, `many`, `other` for quantity strings
```
lint --check MissingQuantity ./res
```
 
>In these locales, it is usually an error to have a message which does not
include a formatting argument (such as '%d'), since it will not be clear from
the grammar what quantity the quantity string is describing. 
```
lint --check ImpliedQuantity ./res
```

I think the `lint` should be used.
http://tools.android.com/tips/lint-checks
