### ISSUE TITLE
Lint for Rtl rules

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8282]
> I would need to go through all the XML files and fix all the hard coded directions, we can add to the development guide to never use right, left in XML, and android studio by default shows warning when using them.

_Originally posted by @TarekkMA in https://github.com/ankidroid/Anki-Android/issues/8261#issuecomment-801417681_

Documentation is good, Lint is better. A lint rule that fail or warn on "left" and "right" in xml would be wonderful.

@TarekkMA, do you know whether there are exception, some case where using "left" still make sens ? If so, I'd like the PR to also indicates explicitly how to add this exception and in which case it would be acceptable

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/8ea9640cb4e7ad99a67d0e78ec75993f237d4029/lint-release.xml#L274-L277

Documented: http://tools.android.com/tips/lint-checks

**Comment by TarekkMA** [comment]
I did actually notice the linting rule that are set to ignore, but I thought they are there for a reason. 

In RTL locals, every thing is flipped around, so start and end should be used at all times.

I can't remember off the top of my head when it is ok to use hard coded directions, if the linting can be ignored for one line we can enable all the RTL linting to be errors, and if we come across such a scenario we disable for that line

And also something that is very important is `Drawable#setAutoMirror` for direction dependent images, like horizontal arrows for examples

**Comment by Arthur-Milchior** [comment]
In this case, I believe that this feature should be :

Stop ignoring those Rtl lint as soon as you can.
