### ISSUE TITLE
Document Viewing Debug Analytics Data

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8284]
> @david-allison-1 needed some help in testing out the changes. How do I access the development version of google analytics for this project?

We'll need to discuss that, for now, assume that if it logs the value, it works

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8283#issuecomment-803265860_

----

Not sure how possible this will be (might need to go off logs). Will need a discussion on how we proceed.

It'll be a more common question now we're ramping up the analytics capture and could do with being in the Development Guide

**Comment by mikehardy** [comment]
I think at this point we should just say watch adb logcat and assume that if in debug it says it is sending XYZ that you may trust it completely, then include an example

It is possible to grant people access to view analytics but I do not want to, for 2 reasons:
- to be clear, we have everything configured to collect no data that is identifying or sensitive that I am aware of except the very general location of the user (by very general I mean like "they are probably from this country", but even then **just in case** I want to keep access to the data very limited
- the actual process of access control sharing becomes a blocker if it is part of the process, and it is a separate database etc that would need granting and revoking etc

For those reasons, just document what the logs look like, and indicate that they may be trusted completely for analytics work

**Comment by david-allison-1** [comment]
Also to document: https://github.com/ankidroid/Anki-Android/pull/8261#issuecomment-803511169
