### ISSUE TITLE
Fail CI if Analytics string constants are changed

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8287]
If analytics strings/categories are changed, then we cannot compare them between versions.

The likely issue here is some usages of `.getClassName()`

Context:

If this goes in, we should add an issue to enforce this via a lint check 

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/8257#discussion_r596467326_

**Comment by mikehardy** [comment]
Yes, I suppose the uses of getClassName (which I put in originally!) should be altered to be constants themselves so they survive refactoring. In essence any use of logEvent should be considered an external API call including all values passed to it, and changing the call (including values) should be considered a "breaking change", so the code should be set up to reflect that

**Comment by ritvij14** [comment]
@david-allison-1 I wanted to try out this issue as I am curious how the CI tests for AnkiDroid work. Will this be covered in the JUnit tests that are run by `./gradlew jacocoUnitTestReport`?

**Comment by david-allison-1** [comment]
`./gradlew jacocoTestReport` for both Android and Unit Tests +
`./gradlew lintRelease` for our lint checks

**Comment by mrudultora** [comment]
@ritvij14 Are you working on 2 issues simultaneously. Just asking because on discord you asked something about Lookup dictionary......

**Comment by ritvij14** [comment]
> @ritvij14 Are you working on 2 issues simultaneously. Just asking because on discord you asked something about Lookup dictionary......

@mrudultora no I am not. I am working on an issue that adds analytics for Lookup Dictionary. The work is almost complete just needed a few clarifications. This issue just got me curious as to how the CI works, hence why I asked the question here. If the previous issue gets solved and I am able to figure out how to work on this, maybe I will take this one up next

**Comment by mrudultora** [comment]
@david-allison-1  As ritvij14 is currently assigned a different issue, I want to take this up.

**Comment by david-allison-1** [comment]
Sure

**Comment by mrudultora** [comment]
@david-allison-1 I am unable to think of a solution through lint. Would you please explain me the approach to handle this issue ?

**Comment by david-allison-1** [comment]
* Add an annotation: `@AnalyticsConstant`
* Mark all string with this annotation

* Add a list of known strings in a unit test
* Use reflection to get the values of each field marked with `@AnalyticsConstant`
* Add a unit test which will fail if a string is marked with `@AnalyticsConstant`, and isn't added to the list (added, but not set in the unit tests)
* Add a unit test which will fail if a string is in the list, and isn't in the code (removed)
