### ISSUE TITLE
[Bug] Select Many not consistent with configuration changes

### ISSUE THREAD

**Issue by mrudultora** [ankidroid/Anki-Android#8294]
###### Reproduction Steps
As stated here https://github.com/ankidroid/Anki-Android/pull/8278#discussion_r598113467 the variables are not saved and restored. Its a special case of #3654

###### Expected Result
Select many feature should work fine on changing orientation.

###### Actual Result
It's not storing the last selected position so causing inconsistencies.

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by prathamk22** [comment]
Can I work on this issue?

**Comment by mrudultora** [comment]
@prathamk22 Sorry, I have already fixed this one. I will make a PR for this soon. Would you mind taking an another issue ?
