### ISSUE TITLE
Codecov posting comments inside diffs on GitHub

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8296]
No problem - I still haven't seen the effect I am looking for but I think that may be because people branched for their PRs prior to my change, in other words it may take a moment for the tuning to actually filter in to people's PRs. We can take further action if it is not working well within a few days though on new PRs. I want my clean diffs back in the web UI as well :-)

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/8190#issuecomment-803346979_

Specifically this still seems to be happening here https://github.com/ankidroid/Anki-Android/pull/8292 even though I check the .codecov.yml files and they look they are in place, so something about them isn't configured correctly yet

**Comment by mikehardy** [comment]
@Arthur-Milchior FYI - I notice codecov is still spamming the diff after I thought I had made a change that would stop it. Tracking here

**Comment by david-allison-1** [comment]
Unsure if this is still pending, if it is:

https://docs.codecov.io/docs/github-checks-beta

```
github_checks:
    annotations: false
```

or pressing "a" on the GitHub diff to remove the annotations
