### ISSUE TITLE
An app guide will be great for new users

### ISSUE THREAD

**Issue by ojasjain24** [ankidroid/Anki-Android#8299]
when I first tried the app, I wasn't able to figure out the functionalities.

A guide will improve UX. A guide that will show all the features and functionalities to the first time users.

**Comment by Ekagra** [comment]
This is one of the project proposal for GSoC this year

**Comment by prathamk22** [comment]
@ojasjain24 Can I work on this?

**Comment by ojasjain24** [comment]
> @ojasjain24 Can I work on this?

please ask the maintainers about it.

**Comment by mikehardy** [comment]
Onboarding was one of our two accepted Google summer of code projects so this is in process already. Many thanks for the offer though! Hopefully there is something else in the list that looks interesting
