### ISSUE TITLE
[bug] letter going inside another letter on realme x2 pro custom rom AOSiP 11. looks perfectly on desktop and while writing the question. 

### ISSUE THREAD

**Issue by KanyeTheLamar** [ankidroid/Anki-Android#8300]
###### Reproduction Steps

1. Write Question in the language dhivehi in a card 
2.  Click the deck after submitting the question 
3.  It shows a letter inside another letter (abnormality is the most bold looking part) 

###### 
![Screenshot_20210321-135718_AnkiDroid](https://user-images.githubusercontent.com/81077087/111900279-6e288500-8a53-11eb-8d24-cc8b81f71fff.png)

###### 
![Screenshot_20210321-135729_AnkiDroid](https://user-images.githubusercontent.com/81077087/111900283-7680c000-8a53-11eb-9c1e-25097ce2f23a.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
@KanyeTheLamar Thanks! Could you copy/paste the text that's causing issues?
