### ISSUE TITLE
[Suggestion] CI: Automate "commit message length" check

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8313]
**To discuss with AnkiDroid community, not yet accepted for work**

There is currently a checkbox in the PR template to ensure that the commit message title is 50 chars or less

It would be useful to automate this check: 

* So it's not forgotten in reviews
* So we can add documentation on writing a good commit message and do not need to duplicate effort explaining it

----

> You have a descriptive commit message with a short title (first line, max 50 chars).

https://github.com/ankidroid/Anki-Android/blob/master/.github/pull_request_template.md

**Comment by mikehardy** [comment]
Here's a github action that can do it if someone makes a workflow to implement
https://github.com/mristin/opinionated-commit-message

**Comment by david-allison-1** [comment]
> Commit messages of the pull request are not verified unless you trigger the workflow on the push as well. GitHub does not include the content of commit messages in the context payload, so checking all the commit messages of the pull request would involve various API call and additional complexity.

> To overcome this issue, run opinionanted-commit-message both on pull_request and push. Please upvote this issue to signal the visibility and so that we could judge when this feature merits the effort.

Does this mean that we'll only get results for this after we `push` to master (or another local branch to the repo), or does GitHub show checks run on the source repo in the PR?

**Comment by mikehardy** [comment]
@david-allison-1 unsure, things like this only work with testing - I integrated a conventional-commits PR title checker and it is even more subtle for fork-based flows https://github.com/amannn/action-semantic-pull-request/#event-triggers - so hesitate to even speculate without actually trying it

**Comment by mrudultora** [comment]
I would like to work on this. But few questions, the github action Mike suggested could be installed by any of the member of AnkiDroid only. Am I right ?

**Comment by david-allison-1** [comment]
> I would like to work on this. But few questions, the github action Mike suggested could be installed by any of the member of AnkiDroid only. Am I right ?

Now, I'm not an expert here:

* You can set up actions on your own repository to test for free (as long as it's public)
* GitHub actions can be added by anyone in a pull request to a YAML file: https://github.com/ankidroid/Anki-Android/tree/master/.github/workflows
* In a pull request, the token that GitHub Actions uses is read-only
* In other circumstances (manual run by maintainer, merge to master), the token is read/write

**Comment by mrudultora** [comment]
I searched for some github actions and also looked at the one suggested by Mike. But they are getting too strict. We just want to check the commit message length. They are checking too many other things too.

**Comment by mrudultora** [comment]
These are some of the error. Do we want this much strict ?
```
Error: The message 1 is invalid:
* The line 3 of the message (line 1 of the body) exceeds the limit of 72 characters. The line contains 80 characters:
"Bumps [actions/setup-java](https://github.com/actions/setup-java) from v1 to v2.". Please reformat the body so that
 all the lines fit 72 characters.
* The line 7 of the message (line 5 of the body) exceeds the limit of 72 characters. The line contains 261 characters: 
"<li><a href=\"https://github.com/actions/setup-java/commit/8764a52df183aa0ccea74521dfd9d506ffc7a19a\"><code>
8764a52</code></a> Rename v2-preview to v2 in docs and tests (<a href=\"https://github-redirect.dependabot.com/actions/setup-java/issues/151\">#151</a>)</li>". 
Please reformat the body so that all the lines fit 72 characters.
```

**Comment by david-allison-1** [comment]
To discuss, but I feel going forwards:

* First line 50 chars
* body - 72 chars
* Exception on for URLs - but must start at position 0

**Comment by mikehardy** [comment]
That really just seems like a pain in the butt to me. I don't even *really* care about the 50 characters to be honest

**Comment by david-allison-1** [comment]
As mentioned in the header: needs discussion

My main goal is to remove the checkbox in the PR template: so as a resolution, I'd be happy with either by automation or removal of the line (or closing this issue as WONTFIX).

I feel there's benefit from a short commit header, I'm pro keeping it to 50 chars.

72 chars: I'll keep to it personally, it's a reminder to spend some time and be concise, but I'm fine to leave it be

**Comment by mrudultora** [comment]
> 72 chars: I'll keep to it personally, it's a reminder to spend some time and be concise, but I'm fine to leave it be

Is there a way we limit the works of a github action? I searched a lot for a github action that just helps us in checking the commit message length, but was unable to find. They all come with many other checks too. What's your suggestion ? How should I proceed on this one ?

**Comment by david-allison-1** [comment]
Best for us to decide on a course of action first

I'm sure there'll be an action which allows a basic regex for the fist line

**Comment by mikehardy** [comment]
if we do a check, let's limit it to the first line, 50chars check
If the action does not have a way to limit it, the actions themselves are all open source, no reason you can't PR to them to add something, e.g. https://github.com/styfle/cancel-workflow-action/pulls/mikehardy ;-)

**Comment by david-allison-1** [comment]
@mrudultora Sounds good to go!
