### ISSUE TITLE
Using DataStorePreferences Instead of SharedPreferences

### ISSUE THREAD

**Issue by kartikeysaran** [ankidroid/Anki-Android#8315]
## Using DataStore Preferences instead of Shared Preferences can be a great feature to include 
Currently we are using Shared Preferences inside our application , If we use DataStore Preferences , we might be able to prevent certain crashes

### Benefits of using DataStore Preferences instead of Shared Preferences

<img src="https://3.bp.blogspot.com/-Vk_q5hWw6DQ/X00ZfiRrB9I/AAAAAAAAPlo/u-kvBvmMfzgRnNViYLwaAim-E7wq5yxKACLcBGAsYHQ/s1600/Screen%2BShot%2B2020-08-31%2Bat%2B11.25.43%2BAM.png" width="600" height="500" />

**Comment by david-allison-1** [comment]
Preface: only had a skim of the documentation, may be missing something

I haven't seen any `SharedPreferences`-related crashes. It's a simple API, and there doesn't seem to be any upside in spending a large amount of effort rewriting stable code, with the likelihood of introducing bugs to fix issues that we don't have. 

Feels like a "new shiny" from Google that won't be worth the maintenance effort. 

I don't see any upside in rewriting (but I'm happy to be proven wrong). Going to say [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).

**Comment by kartikeysaran** [comment]
> I don't see any upside in rewriting (but I'm happy to be proven wrong). Going to say [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it)/[If it ain't broke, don't fix it](https://en.wikipedia.org/wiki/Bert_Lance#If_it_ain't_broke,_don't_fix_it).

Should i close the issue ?

**Comment by mikehardy** [comment]
What we need to do in reality is handle deprecation on existing code #5019

**Comment by oyeraghib** [comment]
@david-allison What do you think about introducing DataStore Preferences now? As now we have introduced Coroutines, I feel like it may be somewhat beneficial to introduce DataStore Preferences so we can perform these operations asynchronously in background.

**Comment by david-allison** [comment]
Intuition is that the async overhead will be slower than a memory read. 

Very happy to do a performance test and see if I'm incorrect here.

**Comment by david-allison** [comment]
Intuition is that the async overhead will be slower than a memory read. 

Very happy to do a performance test and see if I'm incorrect here.
