### ISSUE TITLE
[Bug]  Anki won't open on Google pixel 5

### ISSUE THREAD

**Issue by kr1419** [ankidroid/Anki-Android#8318]
###### Reproduction Steps

1.  tap app icon
2. 
3. 

###### Expected Result

app opens. Not an issue until today. But before that, Anki was often not responding after going through a card and I had to wait for it to work.

###### Actual Result

Nothing. Sometimes it says anki is not responding.

###### Debug info
I can't get this as the app won't open.

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
No relevant crashes in our tracker for a Pixel 5.

Could you try downloading an earlier stable version of AnkiDroid (2.13.5 for example): https://github.com/ankidroid/Anki-Android/releases/tag/v2.13.5  (Pick `Parallel.A`).

If this works, it's a problem with a new version of the app; if it doesn't, it's a problem with your collection. Let us know and we can diagnose further.

**Comment by kr1419** [comment]
It works perfectly with that version. Here is my debug:
AnkiDroid Version = 2.13.5

Android Version = 11

ACRA UUID = c75f1602-d621-4905-b10b-972e080ab97e

Scheduler = std

**Comment by kr1419** [comment]
It was working for a little bit. Now the app won't open.

**Comment by kr1419** [comment]
This seems to be an issue with the android version or phone. All of my other apps close quickly after opening them. Restarting doesn't help. But the other thing about Anki not responding because of going through one card is still an issue aside from that.

**Comment by Kartoffel0br** [comment]
My phone says Google Play Services is crashing now, what is happening???

**Comment by kr1419** [comment]
https://9to5google.com/2021/03/22/android-apps-crashing-webview/

**Comment by kr1419** [comment]
Uninstalling webview seems to have fixed this. Feel free to close the issue. I'm not sure if I should.

**Comment by david-allison-1** [comment]
Thanks! Closing - moving to https://github.com/ankidroid/Anki-Android/issues/8319 for further discussion.

Today's not gonna be fun
