### ISSUE TITLE
Ankidroid ver 2.4.16 fail to run on android 11

### ISSUE THREAD

**Issue by timbob89** [ankidroid/Anki-Android#8323]
App fails to start. Delinked collections by way of change to directory name and continued to fail to start. Removed Ankidroid files from phone but 2.4.16 continued to crash on start up. Reverted software to 2.4.13 and app starts - unable to reload prior collection so downloaded backedup library from Ankiweb. Is this a case of poor SW compatibility? For the moment I am running the old version to buy me some time but the app continues to occaisionally crash in the background causing a battery drain.

Appreciate any thoughts.

Collection.anki2 file available at below:

https://drive.google.com/file/d/1kbke4HyS82NBWqfPYUyvJrue_n0euDhq/view?usp=sharing

**Comment by david-allison-1** [comment]
Hi, Google's released a bad update for "Android System WebView". Please uninstall it until they fix it. More info: https://github.com/ankidroid/Anki-Android/issues/8319

**Comment by timbob89** [comment]
Not to worry, David! Appreciate the feedback - thanks for the hard work (y) 

I have uninstalled WebView and it seems to have corrected the issue with Ankidroid 2.4.16.
