### ISSUE TITLE
[Bug] filtered decks created on desktop show the mark of subdecks on them

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#8324]
###### Reproduction Steps

1. create filtered on desktop on ```2.1.41```
2. sync with ankidroid

![image](https://user-images.githubusercontent.com/4019910/112119583-cda2a400-8bbd-11eb-8910-a781f72dbfa2.png)

**Comment by david-allison-1** [comment]
First step in diagnosis would be to:

* Reproduce
* Obtain the JSON for the decks and see what's changed
* Post results

**Comment by voidplayer** [comment]
I cant find a way to obtain the json from desktop or ankidroid. Only export is in apkg, which contains a sqlite database. But looking at the database i found this one json field and his a diff from a filtered with colapse icon (created on desktop) and a filtered without

Both exports are done from ankidroid

```
$ diff bad.json good.json 
[...]
<         "name": "filtered::filteredbad",
---
>         "name": "filtered::filteredgood",
51,52c51,52
<         "collapsed": true,
<         "browserCollapsed": true,
---
>         "collapsed": false,
>         "browserCollapsed": false,
```

**Comment by voidplayer** [comment]
still searching for solutions

**Comment by tomorekoya** [comment]
Hi. I would like to look into this.

**Comment by david-allison-1** [comment]
Sounds good to me

**Comment by tomorekoya** [comment]
So my first question would be about step 1 in the reproduction:
1. Does <code>```2.1.41</code> refer to the desktop app's version number that I should be testing with?
2. How do I create a filtered deck?

**Comment by tomorekoya** [comment]
Actually, never mind about number 2. I just YouTubed it.

**Comment by tomorekoya** [comment]
Still looking for solutions.

**Comment by voidplayer** [comment]
I can no longer reproduce this
