### ISSUE TITLE
Unit test for review dates

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8326]
We really need to have unit tests that check that, when you press again, hard, good and easy, the next review date are computed as they should be.

It is a good first issue because essentially, it consists in creating cards, reviewing them, and checking their new state or date are correct. So it really uses a very small part of the code. However, you may need help to figure out what are the date that we expect, what are all the tests cases that should be considered, so please don't hesitate to come discuss with me if you are interested in this topic

Some tests are present in upstream, but not a lot. If you speak rust, maybe anki could benefits from the same tests.

**Comment by Ekagra** [comment]
I would like to work on this

**Comment by Arthur-Milchior** [comment]
Go for it. Don't hesitate to ask question if you have a doubt about what is the expected behavior of the scheduler. It's not always straightforward when you move the hour at which day start multiple times or if you change timezone. 
You probably want to look at Robolectric's getCol to find the date at which the unit tests are run.

**Comment by Ekagra** [comment]
Sure, I'd update if I need help.

**Comment by Ekagra** [comment]
```
    protected Collection getCol() {
        // 2020/08/07, 07:00:00. Normally not near day cutoff.
        MockTime time = new MockTime(1596783600000L, 10);
        return CollectionHelper.getInstance().getCol(getTargetContext(), time);
    }
```
starting from here, can you brief me about what this does and what needs to be done?

**Comment by Arthur-Milchior** [comment]
I can. In this case, I'd like you to please write down javadoc, so that the next people reading this get a better understanding.

You are outdated. This code is not on https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/test/java/com/ichi2/anki/RobolectricTest.java#L246 anymore. If you have a local copy of code on your computer, you may want to update it. I did recent changes in order to make it easier to read and use.


`Collection` is the type that represents the user collection, decks, notes, reviews, cards, note type, card type, etc.... So that's what you'll need to test everything in background, and to make a lot of changes to prepare user interface tests.

To ensure consistency in tests, instead of using current time, we use fixed time `MockTime`. We set the time at the 7th of august 2020. The date is totally random. Each time you query the clock, 10 miliseconds passed. This ensure time move slowly.
You can also change the clock. So for example, even if collection is theoretically created the 7th of august 2020, you can move to the 8th of august to create a card, move to the 10th to review it, then to the 12th to review it again, etc... 
You can also just create a card, put it in review mode, and put it's due value at some specific date

**Comment by Ekagra** [comment]
If I'm understanding this right,` Robolectric's getcol `returns a collection for other tests and we have to make it return the collection real time and not on a fixed time?

**Comment by Arthur-Milchior** [comment]
I feel like we need to discuss it by speech, otherwise it'll take time.

`getCol` returns a new collection for every test. Each time you start a new test you get a new collection.

We never want to test with real time. That may cause a lot of problem and is not something that should be done in unit test. On the contrary, David and I spent a lot of time to ensure that we never need to use real time and that we get time we decided to set in.

In particular, that's useful because you can make tests that take weeks in simulated time and only a second in real time,

**Comment by Arthur-Milchior** [comment]
@Ekagra any news on it?

**Comment by Ekagra** [comment]
> @Ekagra any news on it?

I'm currently not working on it, anyone interested please take up this PR

**Comment by kubaczechowski** [comment]
Hi. Can I tackle this issue?

**Comment by mikehardy** [comment]
@kubaczechowski sure! Let us know if you need any help, and if that's the case best method is probably just posting what you have as a draft PR and asking questions on that. Cheers!

**Comment by kubaczechowski** [comment]
Okay. Thank you for the support @mikehardy !

**Comment by kubaczechowski** [comment]
Hi. 
I have tried to find it on my own but then I couldn't ... 


1. Can I ask which class is responsible for handling this action event(saving note)?
![image](https://user-images.githubusercontent.com/67064580/124023197-f8d33580-d9ed-11eb-807d-21b71f2c1d42.png)

2. Can I ask which class handles action events for this four buttons?
![image](https://user-images.githubusercontent.com/67064580/124023497-49e32980-d9ee-11eb-8154-e0c636572216.png)

Thanks in advance for all the answers! PS. I'm fully aware that this is beginner question , though debugging or deduction 
I couldn't get to that.

**Comment by kubaczechowski** [comment]
I intended to look on methods for this two ^^ action events in order to get better perspective on what actions I need to invoke in 
unit tests.

**Comment by mikehardy** [comment]
That's our NoteEditor, and it should be this if you tap on it (it's different if you use keyboard etc) https://github.com/ankidroid/Anki-Android/blob/33473d9408e0fccc7ba6d6277ce691d0a53c4cc3/AnkiDroid/src/main/java/com/ichi2/anki/NoteEditor.java#L1117-L1120

Note: the best way to find these things is to run the app from AndroidStudio (install the "Play" variant, from command line it's `./gradlew installPlayDebug`) and then watch the console output (on command line it is `adb logcat`)

You would see this line pop up: "NoteEditor:: Save note button pressed" - and then you could search the codebase for that string (from command line it's `grep -r  'NoteEditor:: Save note button pressed'`) to locate where the thing is happening and then chase around from there

Hope this helps?

**Comment by kubaczechowski** [comment]
Yes, it does!! Thank you for such extensive answer, now I will know that :)

**Comment by kubaczechowski** [comment]
```
    @Test
    public void testAgainButtonStatistics(){
        Note newNote = new Note(getCol(), new Model()); // collection set in conctructor
        MockTime reviewTime = new MockTime(2020, 7, 10, 8,
                0, 0, 0, 10);
        Reviewer rev = new Reviewer();
        //now we need to update note so that it will be reviewed

    }
```
Here I have come so far. Now I want to review note (the flashcard in question) and invoke action for again button. Then I will check if its in the deck of flashcards to revise (it should always be there after button again was pressed). Can I ask for a hint how I can review Note? I guess I would need to use one of the methods in `AbstractFlashcardViewer` but I'm not sure. 

I picked again button for a start because I think its the easiest one and then when I familiarize I will be able to consider cases
for other buttons (easy / hard/ ) as well.

**Comment by mikehardy** [comment]
I believe there are test cases that touch the reviewer already, and some helper methods in some object in the test directory that let you instantiate a Reviewer with some number of cards already prepopulated

I think this might be a good example https://github.com/ankidroid/Anki-Android/blob/42911de4ad06eb4bdf4f2ffc0dbe90e0b88f8b4d/AnkiDroid/src/test/java/com/ichi2/anki/ReviewerTest.java#L105-L133

**Comment by Arthur-Milchior** [comment]
Hi @kubaczechowski, thanks for wanting to work on it.
If you do the test I was suggesting, then I fear that you are going in a wrong direction. 
The tests I'm asking for is only about background computing, not about user interaction.
That means that you can use the unit test method to create one card. Change its due date, interval, queue and type, call the scheduler with this card and a button, and check that the new date is as expected and the new interval is as expected.
