### ISSUE TITLE
Does "estimated time to complete reviews"  include time spent by "swiping" back?

### ISSUE THREAD

**Issue by DavidBakala** [ankidroid/Anki-Android#8329]
Is there a bug in the "estimated time for review" calculation for review for a particular day in Ankidroid when we use "swiping" (gestures) to a previous card feature?

I'm using "gestures" and a time limit (15s) for a card to review, untill it skips automaticly to the next one and marks the card as "Again", so maybe in 1/5 - 1/3 cases I "swipe" back (using "gestures" feature) onto the previous card if I wasnt quick enough, but I know the card and I want to review it again.

What I think is happening, is that if you review normally (without swiping to the previous card; maybe also the time limit plays its role), the time spent with each card is counted and based on the total time for the number of cards reviewed that day, the statistics is calculated, on the basis of which, the prediction for how much time you need for reviewing next time, is made...

But, what I think happens, when I swipe to the previous card, the time spent with the previous card (lets say I have it set for a 15s interval, used it fully, and then the card was marked as "Again" and skipped to the next card) and the time spent with the following card (lets say I spent 5s, before I realised that I want to repeat the previous card, because I know it and I dont want it to be marked as "Again", that I just need more time) is not counted. Therefore the statistics are distorted.

So if this happens in 1/5 - 1/3  of cases, the statistics for calculation of the estimated time for study get quite messed up...

So you lets say spend 1,5hrs by vigorous studying (including swiping back as I explained earlier), but Ankidroid thinks, that you studied only 1hr... Because it doesnt count the time spent with the revieved and next card, as I explained (in my example it can be 20s extra time which is not counted in 1/5 - 1/3 cases from the total ammount of cards for review), when you swipe back. It counts only the time you spent with a card when you press a "good", "hard" button etc. But if you "swipe" back, this time you spent (actually studying and thinking about the card), is not counted.

So next time you open Ankidroid, it tells you, that the estimated time for your study is 1hr... But in reality it can be 2hrs, because the statistics are wrong!

The result is that it messes up with my planning, and it is also frustrating at times, because you think that you must be very slow that particular day etc.

I use Ankidroid with the time interval and "Swipe" feature for a quite long time, but the Ankidroid time predictions for review are never accurate. They differ considerably almost every time.

I just infer this on the basis of my observation. I don't know if I'm right.

Thanks for help.
D.

**Comment by david-allison-1** [comment]
I believe this is the same behaviour as Anki Desktop/AnkiMobile, so not a bug, but if they change, we will. Feel free to ask: https://forums.ankiweb.net/

* We store review data in the `revlog` table: https://github.com/ankidroid/Anki-Android/wiki/Database-Structure . This includes time taken per review
* All our statistics use this table
* `undo` removes the entry, and resets the timer
* So, yes, the time taken on the original repetition isn't stored/taken into account
