### ISSUE TITLE
Init capacity set capacity instead of size

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8337]
This change sets the `initialCapacity` for `HashSet` and `HashMap`

My understanding is that these collections will expand their capacity when `capacity > intialCapcity * loadFactor` (maybe `>=`)

As `loadFactor < 1`, this means that by setting the capacity equal to the known collection size, we'll guarantee that each collection will go through a resize operation, which is what we want to avoid

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/7612#issuecomment-806495346_

**Comment by AyaanJaved** [comment]
Could I work on this? 
It's my first foray into the open-source world, would try my best to solve this issue.

**Comment by david-allison-1** [comment]
@AyaanJaved 

Thanks! AnkiDroid was my first Open Source Project. We're a welcoming bunch.

There's already a PR in for this issue: https://github.com/ankidroid/Anki-Android/pull/8339 so it's probably best to find something else that interests you.

Feel free to message me (`DavidA#0813`) on [our Discord](https://discord.gg/qjzcRTx), and/or post in `#ankidroid-gsoc` if you can't find anything, and we'll point you in the right direction.

**Comment by AyaanJaved** [comment]
Oh, my bad for not noticing that.
Thanks a lot @david-allison-1.

> Feel free to message me (`DavidA#0813`) on [our Discord](https://discord.gg/qjzcRTx), and/or post in `#ankidroid-gsoc` if you can't find anything, and we'll point you in the right direction.

Noted 👍

**Comment by Arthur-Milchior** [comment]
As far as I'm concerned if you want to do the work of adding unit test, I'd be quite happy about that. They are missing in #8339

**Comment by kartikeysaran** [comment]
> As far as I'm concerned if you want to do the work of adding unit test, I'd be quite happy about that. They are missing in #8339

Can i add unit tests for this ?

**Comment by david-allison-1** [comment]
@AyaanJaved , would you like to be assigned this? 

Otherwise, @kartikeysaran , sure!

**Comment by AyaanJaved** [comment]
Would love to work on this but i don't have any prior experience on writing unit tests.
Please assign it to @kartikeysaran :)

**Comment by david-allison-1** [comment]
> Would love to work on this but i don't have any prior experience on writing unit tests.
> Please assign it to @kartikeysaran :)

Understood, we're more than happy to help you through getting started 😄. 

Please do reach out in a week or so when you feel more comfortable with the project, it's a great skill to have

**Comment by Arthur-Milchior** [comment]
@kartikeysaran, any update on this?

**Comment by kartikeysaran** [comment]
> @kartikeysaran, any update on this?

I was busy with some others stuffs, Thankyou for pinging me, I will make sure to add unit test asap
