### ISSUE TITLE
Adding a Reminder button in study option fragment

### ISSUE THREAD

**Issue by prateek-singh-3212** [ankidroid/Anki-Android#8344]
**Is your feature request related to a problem? Please describe.**
Setting reminder is somehow a lengthy process and people use this very often. 

**Describe the solution you'd like**
we can put the button at the study option fragment which redirects the user to new page which askes user to select the priority of reminder. If priority is high means the user wants to set up alarm and if priority is low the we can just send the notification to the user(which we are doing now).

**Describe alternatives you've considered**
Or we can just put the reminder button to study option fragment and set the reminder (which we are doing now).

**Additional context**
![WhatsApp Image 2021-03-26 at 19 02 30](https://user-images.githubusercontent.com/76490368/112639987-ea153980-8e66-11eb-972b-65ad54b2fc4d.jpeg)

**Comment by david-allison-1** [comment]
I think we'd only do this if upstream did it.

Feel free to request it as a feature: https://forums.ankiweb.net/

**Comment by prateek-singh-3212** [comment]
okay, I will put this issue in the forum.

**Comment by david-allison-1** [comment]
Thanks! Closing for now. Let me know if it's in Anki Desktop
