### ISSUE TITLE
Modifying login UI of the app

### ISSUE THREAD

**Issue by Prashant830** [ankidroid/Anki-Android#8347]
**Modifying login UI of the app**
Right now, the thing that the Login UI of the AnKidroid app is certainly quite good but the UI is not like premium. So I would like to improve the Login UI of the app .

**Describe the solution you'd like**
Moving ( Email Address & password) EditText  in a rounded box & login button corners in rounded form .

**Additional context**
Demo like this -:

https://user-images.githubusercontent.com/72181295/112653217-35821480-8e74-11eb-9651-2ad744ae919a.mp4

**Comment by david-allison-1** [comment]
We've already gone through one UI change for the login page: https://github.com/ankidroid/Anki-Android/pull/8182 , and it'd be best to test this before trying a new design.

For future, we've added some guidance for UI changes: https://github.com/ankidroid/Anki-Android/wiki/User-Interface-contribution

----

But... I would support a change adding the password/email icon to the left hand side of the boxes.

**Comment by Prashant830** [comment]
@david-allison-1 Ok so i can solve this issue??

**Comment by Prashant830** [comment]
Next time I will take care of all the roles before putting any issue

**Comment by david-allison-1** [comment]
> @david-allison-1 Ok so i can solve this issue??

I'd personally accept a change adding an email/password icon to the current screen
