### ISSUE TITLE
At navigation drawer, The menu option of Report a Bug is missing .

### ISSUE THREAD

**Issue by Prashant830** [ankidroid/Anki-Android#8348]
**The menu option of Report a Bug is missing .**
 In  this application , At navigation drawer, The menu option of Report a Bug is missing .

**Describe the solution you'd like**
Creating a menu option for report a bug at navigation drawer. 
After creating the report a bug option, navigation drawer, if any user sees any issue or bug in app, then that user will click on this option and then he will come to the issue option of github repository of app so that he can create his new issue .

**Additional context**
Demo like this-:
![report a bug](https://user-images.githubusercontent.com/72181295/112662325-8ea27600-8e7d-11eb-8185-8ed795fdcdd2.jpeg)

**Comment by david-allison-1** [comment]
Thanks! For now, we've very wary of adding UI changes without solid justification (we're very time-constrained right now with GSoC, and it takes a lot of time away from known bugs/reported issues, for something subjective which ).

We've already added "report a bug" to our help menu in 2.15: https://github.com/ankidroid/Anki-Android/pull/8193

Going to close this as-per https://github.com/ankidroid/Anki-Android/wiki/User-Interface-contribution
