### ISSUE TITLE
Extracts keys (string) to constants

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8352]
Android and Anki uses a lot of dictionnary to save and load preferences and pass parameters in call to activities.

The risk with strings is that a difference, such as the case, or - and _, is hard to notice and risk to break things. It would be helpful to replace those strings by `static final String`, that is, constants, to ensure that however the code evolves, there is no duplication of strings.

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/pull/8066

**Comment by irenenserrano** [comment]
Hello, 
My partner and I would like to work on this issue.

**Comment by Arthur-Milchior** [comment]
Given that David already did a lot of work, I'd like to wait until what can be merged from #8066 is merged. Don't know how much time it will take

**Comment by Arthur-Milchior** [comment]
@irenenserrano Actually, if you want to work on it, you can. More precisely, you can work on strings used in bundles, intents and all JSONObjects (e.g. decks, model and deckoption). @david-allison-1 can you please confirm that those ones are not yet used ?

**Comment by david-allison-1** [comment]
All I did was `SharedPreferences`

**Comment by irenenserrano** [comment]
@Arthur-Milchior @david-allison-1 thank you for the update! I will begin working on the issue.

**Comment by irenenserrano** [comment]
@david-allison-1 Hello, I am very sorry for this but I am unable to work on this issue anymore. If anyone else would like to take this issue please feel free

**Comment by david-allison-1** [comment]
No worries! Life takes priority
