### ISSUE TITLE
[Bug] Login Page - Anki Icon Flickers

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8354]
###### Reproduction Steps

1. Open Login Page (vertical screen)
2. Anki Icon appears

###### Expected Result

* Anki Icon stays on screen (it's vertical, and my phone has room for the icon).

###### Actual Result

* Anki Icon then quickly disappears

###### Debug info
```
AnkiDroid Version = 2.15alpha32

Android Version = 11

ACRA UUID = 2775070f-9c41-4dc3-886f-63fc5769ad8f

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Screnshots:

<details><summary>While Screen loading</summary>

![image](https://user-images.githubusercontent.com/62114487/112692143-6105fe80-8e76-11eb-88fc-0be6e68739e4.png)


</details>


<details><summary>After screen loaded</summary>

![image](https://user-images.githubusercontent.com/62114487/112692162-6e22ed80-8e76-11eb-8058-cbead457c9ae.png)

</details>

**Comment by david-allison-1** [comment]
@Akshay0701 - follow on from #8182. I'm happy to put this up as a "Good First Issue" if you don't have time. No pressure

**Comment by bhamrickatmills** [comment]
@david-allison-1 if @Akshay0701 is busy, could I give this a shot as a first issue?

**Comment by david-allison-1** [comment]
Thanks for the interest! 

Let's give @Akshay0701 24 hours, if there's no reply, it's yours (feel free to ping me and I'll assign it after this).

**Comment by Prashant830** [comment]
@david-allison-1 I want to solve this issue ,can I take this issue?

**Comment by david-allison-1** [comment]
@Prashant830 You'd be best to find another issue since I've already replied to the two people above

**Comment by Prashant830** [comment]
Ok

**Comment by david-allison-1** [comment]
@bhamrickatmills - all yours!

**Comment by bhamrickatmills** [comment]
Thank you @david-allison-1! If I have an questions I'll ask you in discord!

**Comment by prosperian** [comment]
Hi, is this still open? can i work on this?

**Comment by david-allison-1** [comment]
Hi @prosperian, this has been assigned and is being worked on, you'd be best to find an issue which is unassigned: https://github.com/ankidroid/Anki-Android/issues?q=is%3Aopen+label%3A%22Good+First+Issue%21%22+no%3Aassignee
