### ISSUE TITLE
[Bug] Decks are not sorted by numerical order

### ISSUE THREAD

**Issue by MarioRomanDono** [ankidroid/Anki-Android#8364]
###### Reproduction Steps

1. Create a deck with a number as the first character (e.g. '1 sample')
2. Create another deck with the consecutive number as the first character (e.g. '2 sample')
3. Create another deck with the first number multiplied by 10 as the first characters (e.g. '10 sample')

###### Expected Result
Decks should be ordered as '1 sample' -> '2 sample' -> '10 sample'

###### Actual Result
Decks are ordered as '1 sample' -> '10 sample' -> '2 sample'

![Decks bad ordered](https://i.imgur.com/MyrVuhi.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.14.6

Android Version = 10

ACRA UUID = 97896022-be89-482d-85d3-10724779e477

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
They're sorted alphabetically, `01, 02, ... ,10` will be in the correct order
