### ISSUE TITLE
[Bug] Custom Tabs color inconsistent with UI

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8365]
###### Reproduction Steps

1. Open AnkiDroid
1. Click the plus
2. Select "Get shared deck"

###### Expected Result

* App bar does not change color

###### Actual Result

* App bar changes color

###### Debug info

```
AnkiDroid Version = 2.15alpha31

Android Version = 11

ACRA UUID = 2f93c96f-11ae-45bd-b314-b1236df15be0

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Requested by @MarioRomanDono

**Comment by Arnold2381** [comment]
@david-allison-1 can I try giving it a shot?

**Comment by prateek-singh-3212** [comment]
@david-allison-1 I would like to work on this issue.

**Comment by david-allison-1** [comment]
Let's give @MarioRomanDono 24 hours, feels bad to reassign this since he asked for an issue to do. 

Otherwise, @Arnold2381, it's yours. Give me a ping in 24 hours and I'll assign it

**Comment by Arnold2381** [comment]
Sure I will wait!! No problem at all.

**Comment by mrudultora** [comment]
@david-allison-1 I am unable to reproduce this on **2.15alpha33**. Also, #8164 fixed this. Could you post a screenshot ?

**Comment by david-allison-1** [comment]
The app bar is a different color 

![image](https://user-images.githubusercontent.com/62114487/112767577-664a8100-900f-11eb-9bf1-ac7fd8526d46.png)

![image](https://user-images.githubusercontent.com/62114487/112767601-93972f00-900f-11eb-97d4-2a1b7b8a7d35.png)

**Comment by LinearMomentum** [comment]
Should the appbar look like this？
![QQ图片20210424150835](https://user-images.githubusercontent.com/72519107/115950629-ff858e00-a50e-11eb-8828-32d9c88df652.png)

**Comment by mikehardy** [comment]
If by appbar you mean the top light blue-ish area, yes
If by appbar you mean the gray-ish content from AnkiWeb, that's from AnkiWeb and not in our control

**Comment by david-allison-1** [comment]
On me. Note: related to #8175
