### ISSUE TITLE
[Bug] Scrolling is extremely jumpy and barely functional

### ISSUE THREAD

**Issue by BenSandeen** [ankidroid/Anki-Android#8366]
###### Reproduction Steps

1. Open AnkiDroid
2. Start learning from a deck
3. Display the answer for a card
4. Scroll down

###### Expected Result
App scrolls smoothly and normally

###### Actual Result
App scrolling is extremely jumpy and often bounces back in the direction I'm scrolling from

###### Debug info
AnkiDroid Version = 2.14.6

Android Version = 8.1.0

ACRA UUID = bedf0991-402e-4d21-b5f3-2f751cfe6dc1

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

-  [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
We've had to make some changes to hardware acceleration due to issues with Android 8, we've improved this in the 2.15 alpha, please the following link for instructions on how to access it:

https://github.com/ankidroid/Anki-Android/issues/8165#issuecomment-795776817

**Comment by david-allison-1** [comment]
My bad - thanks for the heads up
