### ISSUE TITLE
[Bug] ACRA Crash Dialog - Can't enter additional information

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8380]
###### Reproduction Steps

1. Help - Get Help - Send Troubleshooting report
2. Tap "Enter your feedback or information"

###### Expected Result

* I can enter text

###### Actual Result

* Keyboard doesn't appear, I can only paste

###### Dev notes

https://github.com/ankidroid/Anki-Android/blob/a739a1c42edac3e058269add024a2eb8b1d6703e/AnkiDroid/src/main/res/layout/feedback.xml#L17-L23

* We should also fix the fact that this does not look like an EditText in night mode

###### Debug info
```
AnkiDroid Version = 2.15alpha34

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ2A.210305.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 2f93c96f-11ae-45bd-b314-b1236df15be0

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
@david-allison-1 can i work on this issue

**Comment by david-allison-1** [comment]
Sure
