### ISSUE TITLE
[Bug] RTL support for activity transition animations

### ISSUE THREAD

**Issue by eginhard** [ankidroid/Anki-Android#8396]
###### Reproduction Steps

1. From the deck list, go to the Card Browser or Statistics screen
2. Return to the deck list
(probably affects transitions between other activities as well)

###### Expected Result
When the UI is set to a RTL language, the new activity should appear from the left and then disappear to the left (i.e. the opposite as in LTR languages).

###### Actual Result
The new activity appears from the right, and disappears to the right like in LTR languages.

###### Debug info
2.15alpha36

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by vinishhub** [comment]
I want to work on this issue please can you elaborate more??

**Comment by vinishhub** [comment]
No I don't Know to Read the  Rtl language its just animation part so I think there is no need of language

**Comment by eginhard** [comment]
No, it's not necessary, just makes it easier to test and to understand what should be changed.

But in that case go ahead and try to reproduce it, using the instructions in the issue I mentioned to force a RTL layout for English. Make sure you're using the latest alpha version or the master branch from Github.

**Comment by vinishhub** [comment]
ok then assign me the task

**Comment by vinishhub** [comment]
https://user-images.githubusercontent.com/76252038/113134565-95930500-923e-11eb-9399-e2e7edf8d8d8.mp4

**Comment by vinishhub** [comment]
sir do check is this correct

**Comment by eginhard** [comment]
Yes, this is the wrong behaviour I mentioned in the bug description. For RTL languages, the intended behaviour would be to mirror these animations horizontally.

**Comment by vinishhub** [comment]
okk so the layout should be same only animation is to change right

**Comment by vinishhub** [comment]
ohh sorry sir
so the activity's  "In-transition" should be from right to left  and "out transition" right to left .
Right????

**Comment by eginhard** [comment]
Yes. Essentially all left->right and right->left animations should be reversed for RTL.

**Comment by vinishhub** [comment]
sir I have created a separate animation file anim-ldrtl under res And I have entered the animation file and changed the behaviour of each file (i.e In slide_left_in I have placed property of slide_right_in and viceversa).I don't Know what to do next.

**Comment by mikehardy** [comment]
I'm in this area for other reasons and noticed that we are using ActivityTransitionAnimation in our source tree for these animations (or at least, we *should* use it for all animations)

Currently we have a LEFT and RIGHT defined as constants to specify an animation.

Following Android naming practices those constants should be renamed START and END so that the "idea" of RTL languages is built in

Then in the switch statement where the constants are used, the existing right and left animations should be selected appropriately depending on RTL status

I do not believe any other layouts or anything are required, and once the constant names are changed in Java the code won't compile if anyone is doing it wrong

**Comment by vinishhub** [comment]
Sir I have renamed  LEFT AND RIGHT variables to START AND END how to implement in switch case we have to reverse the transition when switched from LTR to RTL and vice versa

**Comment by mikehardy** [comment]
in each of the indicated cases, you will need some programmatic way to determine if your locale is RTL or not, then select the correct animation. Figuring that out is the task.

**Comment by Akshay0701** [comment]
Character.getDirectionality returns the[ Bi-directional (bidi)](https://en.wikipedia.org/wiki/Bidirectional_text) character type. Left-to-right text is a predictable type L and right-to-left is also predictably type R. BUT, Arabic text returns another type, type AL.

I added a check for both type R and type AL and then manually tested every RTL language Android comes with: Hebrew (Israel), Arabic (Egypt), and Arabic (Israel).

As you can see, this leaves out other right-to-left languages, so I was concerned that as Android adds these languages, there might have a similar issue and one might not notice right away.

So I tested manually each RTL language.

Arabic (العربية) = type AL
Kurdish (کوردی) = type AL
Farsi (فارسی) = type AL
Urdu (اردو) = type AL
Hebrew (עברית) = type R
Yiddish (ייִדיש) = type R
So it looks like this should work great:

> public static boolean isRTL() {
>     return isRTL(Locale.getDefault());
> }
> 
> public static boolean isRTL(Locale locale) {
>     final int directionality = Character.getDirectionality(locale.getDisplayName().charAt(0));
>     return directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT ||
>            directionality == Character.DIRECTIONALITY_RIGHT_TO_LEFT_ARABIC;
> }

**Comment by Akshay0701** [comment]
@vinishhub this is not very complex problem ,but if still not able to solve it ,no issues ,I will do that for you :)

**Comment by vinishhub** [comment]
Thanks sir

**Comment by vinishhub** [comment]
https://user-images.githubusercontent.com/76252038/113726413-d9d84680-9711-11eb-8149-aeb0ae846a71.mp4

@eginhard I think now its ok
