### ISSUE TITLE
[Bug] Deck ordering differs from Anki Desktop

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#8397]
###### Reproduction Steps

1. Add Decks: `AA`, `ab`, `BB`

###### Expected Result

1. `AA`
2. `ab`
3. `BB`

###### Actual Result

1. `AA`
2. `BB`
3. `ab`

###### Debug info

```
AnkiDroid Version = 2.15alpha34

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ2A.210305.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 2f93c96f-11ae-45bd-b314-b1236df15be0

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
@david-allison-1 can i work on this issue

**Comment by david-allison-1** [comment]
Sure.

It would make sense to collaborate with, @AyaanJaved on the issue as they're also in the area, and may provide unit tests or advice for you to follow.

**Comment by albus-droid** [comment]
Can I work on this as my first issue.

**Comment by Prince-kushwaha** [comment]
@albus-droid i am working on this issue

**Comment by albus-droid** [comment]
Ok.
I'd happy to help if any is needed. 

Cheers.

**Comment by Prince-kushwaha** [comment]
@david-allison-1 can you tell me  sorting of string in done in  increasing or descreasing order

**Comment by Prince-kushwaha** [comment]
@david-allison-1 can tell me sorting of string is done in increasing or decreasing order

**Comment by Prince-kushwaha** [comment]
@david-allison-1  Ordering of {AA,ab,BB}  is not correct in Card Brower ordering is not in increasing or decresing order 
See below
 
![Screenshot_2021-03-31-16-02-02-999_com ichi2 anki](https://user-images.githubusercontent.com/65972015/113131497-ec96db00-923a-11eb-887a-abc99fee8718.jpg)

**Comment by Prince-kushwaha** [comment]
@david-allison-1 can i work on this above issue

**Comment by Prince-kushwaha** [comment]
@david-allison-1 another solution of this issue in pull request  #8439

**Comment by david-allison-1** [comment]
@Prince-kushwaha It'd be best if you closed one of those

Try to keep one pull request per issue. You can rebase a pull request to fix it if something goes wrong.

If you don't have the git skills, to properly rebase (don't worry - it takes time), then it's best to close the original PR and link to the new one so we can understand how it progressed

**Comment by arjun20varma** [comment]
Can i work on this issue?

**Comment by david-allison-1** [comment]
> Can i work on this issue?

Thanks for the enthusiasm! There's already an open pull request: https://github.com/ankidroid/Anki-Android/pull/8439

It'd be best if you find another open issue: https://github.com/ankidroid/Anki-Android/issues?q=is%3Aissue+is%3Aopen+label%3A%22Good+First+Issue%21%22+no%3Aassignee

Off-topic: @Prince-kushwaha, no rush, but the PR is awaiting feedback

**Comment by MathewKJ2048** [comment]
I am willing to work on this issue, if any help is needed

**Comment by CheerfulPianissimo** [comment]
Hello. I would like to be assigned to this issue as my first issue on AnkiDroid.
