### ISSUE TITLE
Unit Test for TextViewUtil

### ISSUE THREAD

**Issue by Ekagra** [ankidroid/Anki-Android#8398]
The TextViewUtil doesn't have any tests to check for example if the textview is null or if size is greater than zero, I think we need to implement these in TextViewUtil and make unit tests for the same.

**Comment by david-allison-1** [comment]
It'd be better to add a `@NotNull` annotation rather than a unit test for these edge cases

**Comment by Ekagra** [comment]
Yeah that would work but don't you think it's better to have a conditional check rather than adding an annotation?

**Comment by david-allison-1** [comment]
No, there's no benefit: you're substituting one exception with another and adding a runtime performance cost.

**Comment by Ekagra** [comment]
I see, so should I implement this?

```
    @NonNull
    public static float getTextSizeSp(@NonNull TextView first) {
        return first.getTextSize() / first.getResources().getDisplayMetrics().scaledDensity;
    }
```

**Comment by david-allison-1** [comment]
There's no point in a `@NonNull` on the return - floats aren't nullable. Other than that, seems OK

**Comment by Ekagra** [comment]
alright this looks fine ?

```
    public static float getTextSizeSp(@NonNull TextView first) {
        return first.getTextSize() / first.getResources().getDisplayMetrics().scaledDensity;
    }
```
