### ISSUE TITLE
Architecture: Convert CustomStudyDialog to use FragmentFactory

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8406]
By not allowing constructor-based injection, it makes testing with `FragmentScenario` difficult

Instead, we should define and decouple the required interfaces and inject them into the constructor

We should then use this to enable the test defined in #8338

See: #8338

**Comment by TarekkMA** [comment]
I will try to tackle this issue

**Comment by TarekkMA** [comment]
These are the required things that could be extracted as an interface

```java
interface CustomStudyDialogListener {
    showDialogFragment(d);
    dismissAllDialogFragments()
    startActivityForResultWithoutAnimation()
}
```

So we could inject `Collection` and `CustomStudyDialogListener` as constructor parameters.

**Comment by TarekkMA** [comment]
I can use [`ExtendedFragmentFactory`](https://github.com/ankidroid/Anki-Android/blob/b1743baeadc622d547944fd6d493681429c1d517/AnkiDroid/src/main/java/com/ichi2/utils/ExtendedFragmentFactory.java) (OPEN PR) and make the factory thing modular, by having a static function like this.

```java
static void attachFragmentFactory(AppCompatActivity activity) {
    final fm = activity.getSupportFragmentManager();
    // CustomStudyDialogFactory extends ExtendedFragmentFactory
    fm.setFragmentFactory(CustomStudyDialogFactory(fm.getFragmentFactory()));
}
```

**Comment by david-allison-1** [comment]
Great!

What do you think about splitting that interface into `DialogFragment` handling and `Navigation` handling?

Nav will be rewritten this year, so don't put too much thought into it.

**Comment by TarekkMA** [comment]
> Great!
> 
> What do you think about splitting that interface into `DialogFragment` handling and `Navigation` handling?
> 
> Nav will be rewritten this year, so don't put too much thought into it.

That would be for the better, will start on it tomorrow.
