### ISSUE TITLE
Hindi texts are not clear to understand

### ISSUE THREAD

**Issue by shrish-sharma-git** [ankidroid/Anki-Android#8411]
###### Reproduction Steps

1. Use Hindi as the Universal Font
2. The Hindi language used is not clear to understand.

###### Expected Result
The texts should be easy to understand, I do not know English that much

###### Actual Result
The texts/strings are too vague to understand

###### Debug info
Device: Realme 7 Pro
Android Version: 11
AnkiDroid Version: 2.14.6
Device System Language: Hindi

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by eginhard** [comment]
AnkiDroid is translated by the community. If you would like to help improve the Hindi translations, see the instructions here: https://github.com/ankidroid/Anki-Android/wiki/Translating-AnkiDroid
