### ISSUE TITLE
[Bug] Start of New Day - Preference text is truncated

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8417]
###### Reproduction Steps

1. Preferences - Reviewing

###### Expected Result

2. Preference text is not truncated

###### Actual Result

3. Preference text is truncated

![image](https://user-images.githubusercontent.com/62114487/113192374-933ca500-9256-11eb-9b64-368089316fde.png)

###### Debug info
```
AnkiDroid Version = 2.15alpha34

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ2A.210305.006; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 2f93c96f-11ae-45bd-b314-b1236df15be0

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Prince-kushwaha** [comment]
@david-allison-1 can i work on this issue

**Comment by david-allison-1** [comment]
Okay

**Comment by Prince-kushwaha** [comment]
@david-allison-1 i not know how write lint rule can you help me

**Comment by david-allison-1** [comment]
I'm sorry, I don't have the free time right now to teach everything. 

You can see examples in the `lint-rules`project, and you can view similar projects on GitHub to see how the APIs should be used.

If you have specific questions, I'll try to help.

It'd be best to formalise what you're trying to accomplish with the lint checks

**Comment by david-allison-1** [comment]
@Prince-kushwaha are you interested in working on this

@mikehardy Coming back to this, I've had a quick Google and there doesn't seem to be advice on the maximum length of a preference title.

On a small screen (2.8 inch), it seems to be the same as my pixel, but that could be Android emulators standardising: 
![image](https://user-images.githubusercontent.com/62114487/114109854-0df86680-98ce-11eb-96be-dfdb9e87e879.png)

I'm thinking 32 characters as the max (`Start of next day (0 is midnight` on the text), do you think this is leaving too much room?

As for the original preference, I don't think we can fit our intention in the title. I'd like to revert so we can try another method for 2.16. Would you support this?

**Comment by mikehardy** [comment]
Sure

**Comment by prateek-singh-3212** [comment]
I would like to work on this issue.

**Comment by david-allison-1** [comment]
> I would like to work on this issue.

Thanks! It's one of the things that I'd want to do, but wouldn't be able to find the time to do it well

**Comment by prateek-singh-3212** [comment]
Okay, I will work on the linting issue.

**Comment by prateek-singh-3212** [comment]
BTW I have an idea.
we can use the ticked seek bar instead of using the normal seek bar and at the beginning, we can put midnight and at the end, we can put 11 PM.
![ss](https://user-images.githubusercontent.com/76490368/114236820-ce9a4a80-999f-11eb-9536-a6e53a613b3d.png)

**Comment by david-allison-1** [comment]
That looks great! As long as we have some visual feedback for the user about the hour that they select

**Comment by arjun20varma** [comment]
Can I try to work on this issue?

**Comment by david-allison-1** [comment]
> Can I try to work on this issue?

Sure! @prateek-singh-3212's plan looks good to me

**Comment by Arnold2381** [comment]
@david-allison-1 can I work on this?

**Comment by david-allison-1** [comment]
@arjun20varma Are you still working on this?

@Arnold2381 give it 24 hours, then absolutely, thank you! Ping me and I'll reassign, but feel free to work on it

**Comment by Arnold2381** [comment]
@david-allison-1 I started working on it!
BTW just to be clear I have to implement this 
![image](https://user-images.githubusercontent.com/46752548/115274118-f6d33780-a15d-11eb-987d-97e1a327e93e.png)
and should I also limit the preference text?

**Comment by david-allison-1** [comment]
> @david-allison-1 I started working on it!
> BTW just to be clear I have to implement this
> ![image](https://user-images.githubusercontent.com/46752548/115274118-f6d33780-a15d-11eb-987d-97e1a327e93e.png)
> and should I also limit the preference text?

Thanks! Don't bother limiting the text, we'll do that in https://github.com/ankidroid/Anki-Android/pull/8586

**Comment by Arnold2381** [comment]
Ok!!!

**Comment by Arnold2381** [comment]
@david-allison-1 
![image](https://user-images.githubusercontent.com/46752548/115618532-756fd680-a310-11eb-8f49-462b67076efb.png)
is this okay?

**Comment by david-allison-1** [comment]
> @david-allison-1
> ![image](https://user-images.githubusercontent.com/46752548/115618532-756fd680-a310-11eb-8f49-462b67076efb.png)
> is this okay?

Fantastic! You'll save /so/ many user questions with this one.

* It needs a slightly larger margin (be consistent with the top)
* Use 11PM instead of 11
