### ISSUE TITLE
TTS audio suddenly strange (4/1)

### ISSUE THREAD

**Issue by leitz010** [ankidroid/Anki-Android#8420]
The audio quality in Japanese and Korean is truncated and strange sounding. Like the type of voice modulation you see in movies when robots are disfunctioning.

**Comment by david-allison-1** [comment]
Thanks for the report!

@leitz010 Could you go to `settings - advanced - about ankidroid - copy debug info` and paste it here

**Comment by leitz010** [comment]
Here it is ^^:

AnkiDroid Version = 2.14.6

Android Version = 11

ACRA UUID = cc3ec77b-8b96-40ad-99e3-3187c7799494

Scheduler = std

Crash Reports Enabled = true

**Comment by david-allison-1** [comment]
Thanks @leitz010 

If your Anki collection doesn't contain sensitive information, could you zip the file located at `AnkiDroid/collection.anki2` and upload it here, or post a link to it on cloud storage (for example: Google Drive)

If it does, please let me know and we'll find an alternative.

**Comment by leitz010** [comment]
Here is a link to it:

https://drive.google.com/file/d/1W4nYHtLOP0Va1AOYSunhcYiWMFOu37_Y/view?usp=drivesdk
