### ISSUE TITLE
[Bug] autofocus on type fields always on is very annoying

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#8424]
I saw that recently #4699 was fixed, and i think this is not ideal

Usually, I  only type words that i doubt the spelling of and sometimes i only review on phone with one hand and gestures, aka, not typing at all

The keyboard takes 60% of my screen real state. Having it on at all times would be very annoying. Currently it works great. just have a single tap to type those that i feel is granted to type

Its not ideal for those who type every word i guess, but depending on where you do your reviews that day, im sure not even they type in all the words every time

This is a different situation on desktop, the original justification, when having the input field in autofocus is not hidding half the card (Althought it also steal the focus on every shortcut)

I know you try not to overdo settings, but this having an optional keyboard seems one of those cases to me :)

**Comment by david-allison-1** [comment]
Thanks for the feedback!

Open for ideas: We could potentially move this to the JavaScript API

**Comment by voidplayer** [comment]
My idea is to just having a setting to enable the setting

Im sure theres people on both camps. People that always want the keyboard on, because they review on a tablet or something where space is not an issue and that type every word. And people like me, that use it only on hard words. Even people in between, that sometimes want it on at all times, and sometimes they are in the bus and want to review without typing at all

One of the reasons keyboard feels like it takes so much space is because the keyboard only steals space from the actual card, and not any of the buttons around the card (menus on top and show answer button on the botton)

Not sure if the ui is even able to handle whats hidden when the keyboard is out

**Comment by david-allison-1** [comment]
@mikehardy Any opinions on this? Would like to tackle it tomorrow

**Comment by mikehardy** [comment]
Mmm if it's a change of behavior and we know the UI gets really cramped I could see it being a toggle with the default being the no change behavior. Hard to please everyone all the time for sure
