### ISSUE TITLE
[Bug] type fields text colors not visible in dark mode

### ISSUE THREAD

**Issue by voidplayer** [ankidroid/Anki-Android#8428]
Original color

![Screenshot_20210402-120648_AnkiDroid](https://user-images.githubusercontent.com/4019910/113409450-926c5600-93b1-11eb-8094-63b69b1d2218.png)

Night mode: light grey and yellow are not very visible

![2021-04-02_12-49](https://user-images.githubusercontent.com/4019910/113409580-e0815980-93b1-11eb-9fdd-d6130a243d55.png)

**Comment by prateek-singh-3212** [comment]
Hi, @voidplayer  I would like to work on this issue and also want to know that what other maintainers think regarding this issue.

**Comment by david-allison-1** [comment]
@voidplayer Thanks for the report. Are you using custom CSS on the note type, I can't reproduce those colors

@prateek-singh-3212 The first thing would be to determine what Anki Desktop does, and see if we have a regression.

**Comment by voidplayer** [comment]
As i show in the first pic, the text is colored blu

From my limited perspective the problem comes from showing dark grey in the light theme, that turns into light grey in the night theme

Desktop seem to ignore styling completely. Which seems a reasonable thing to do regardless while showing a diff of errors

I wish i could ignore case too, but thats a matter for another thread ;)

**Comment by voidplayer** [comment]
By the way, the custom style comes in the card field like this ```<font color="#0000ff">der Putsch</font>```

**Comment by david-allison-1** [comment]
@voidplayer Thanks! Having a full card template would allow us to replicate this.

You can add `.night_mode { }` to the card template to remove the automatic night mode color inversion, and this may fix your issue.

**Comment by voidplayer** [comment]
@david-allison-1 its a shared deck, you can download it here 

https://ankiweb.net/shared/info/399999380

**Comment by voidplayer** [comment]
I added the field ```{{type:German}}``` to the card type: 2 front template

```
<div id="TitleBar">
<img style="width: 25px; height: 25px;" src="_GermanFlag.jpg">
{{#Tags}} {{Tags}} {{/Tags}}
</div>
<br/><br/>

<div id="EnglishText">
{{English}}
{{type:German}}
</div>
```

**Comment by prateek-singh-3212** [comment]
@david-allison-1 Anki desktop is working fine.
 Here is the screenshot of Anki desktop light and dark mode.  
![1anki](https://user-images.githubusercontent.com/76490368/113438647-99718380-9406-11eb-9bc9-dde94352281a.png)
![2anki](https://user-images.githubusercontent.com/76490368/113438651-9b3b4700-9406-11eb-93e3-5d39628b886e.png)

**Comment by david-allison-1** [comment]
> @david-allison-1 Anki desktop is working fine.
>  Here is the screenshot of Anki desktop light and dark mode.  
> ![1anki](https://user-images.githubusercontent.com/76490368/113438647-99718380-9406-11eb-9bc9-dde94352281a.png)
> ![2anki](https://user-images.githubusercontent.com/76490368/113438651-9b3b4700-9406-11eb-93e3-5d39628b886e.png)
> 

Is that using the "type" feature?

**Comment by prateek-singh-3212** [comment]
> Is that using the "type" feature?

Yes.

**Comment by david-allison-1** [comment]
Could you show a "type the answer" diff on the card to see how it looks?

**Comment by prateek-singh-3212** [comment]
> Could you show a "type the answer" diff on the card to see how it looks?

Are talking about Anki Desktop?

**Comment by voidplayer** [comment]
@prateek-singh-3212

Yes, hes asking how it looks like on desktop. You have to modify the template to add a field ```type:``` as i commented on https://github.com/ankidroid/Anki-Android/issues/8428#issuecomment-812591800

**Comment by prateek-singh-3212** [comment]
Thanks, @voidplayer,
Here is the screenshot of Anki.
![finall](https://user-images.githubusercontent.com/76490368/113681719-ed6ab980-96df-11eb-8a17-4d5c27635aec.png)
![finalb](https://user-images.githubusercontent.com/76490368/113681715-ec398c80-96df-11eb-8eea-bf2c11e0a230.png)

**Comment by david-allison-1** [comment]
Okay, it would seem sensible to me to disable the color inversion on the answer HTML.

https://github.com/ankidroid/Anki-Android/blob/2d344bfb26b7a97e3173c8db4461a0def36e496f/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L2249-L2251

----

@mikehardy Now Anki Desktop has native night mode, I feel we should move to emulate this functionality exactly, rather than keep with our color inversion code. Does this seem sensible?

**Comment by dae** [comment]
Related: https://github.com/ankitects/anki/issues/1078

**Comment by mikehardy** [comment]
In general agreed with doing exactly what Desktop does in the general case - in this specific case I'm not sure exactly what it does so I'm not 100% sure. This area is definitely one prone to user consternation though, and I can only imagine if there are two levels of user consternation because Desktop and AnkiDroid are both doing night mode things, but incompatibly

**Comment by voidplayer** [comment]
Withtout looking at the code, desktop seems to just ignore text coloring completely and use their own text colors just for the diff, which is an clean solution that will just work

Inverting colors would also work (probably even better), but you have to make a good selection of colors for the light theme. That is light background colors with dark text. Which i believe is the root of the problem and right now is not the case, even for desktop. Some of the desktop colors are bad for light theme too, they just dont invert colors, which is where the problem is more notizable

Theres a dark grey and a strong red background which makes a poor contrast in a light theme as it is, and it makes text even harder to read after inverting colors

If you are just going to follow desktop and dont invert colors, that is a bug for desktop i guess

What do you think @dae ? should i open a bug in desktop for this?

**Comment by prateek-singh-3212** [comment]
@david-allison-1 Should I go with Anki Desktop?

**Comment by david-allison-1** [comment]
> @david-allison-1 Should I go with Anki Desktop?

Yes, we want to be 100% compatible

**Comment by prateek-singh-3212** [comment]
@david-allison-1 Should we add an invert HTML color option in settings? because this issue contains the removal of previously written code.

**Comment by mikehardy** [comment]
Let's not over complicate
Type answer diffs on desktop ignore styling and look a certain way
Ankidroid type answer diffs don't ignore styling

For type answer diffs we should do what ankidroid does

That's the issue, that's the expected pr, in my opinion

**Comment by voidplayer** [comment]
still searching for solutions

**Comment by voidplayer** [comment]
still searching for solutions

**Comment by voidplayer** [comment]
still searching for solutions

**Comment by dae** [comment]
Please let us know if it's still an issue after a 2.17 alpha comes out.
