### ISSUE TITLE
Proposal to add a animated splash Screen 

### ISSUE THREAD

**Issue by Amitcode77** [ankidroid/Anki-Android#8447]
Every successful has a good splash screen at the launching of the app which has a great psychological effect on users mind.

I love the app functionality and uses but the User Interface of the app is a little complicated. So I want to work to improve the UI  of the app and start my work by adding a splash screen.

I want to add a short animated splash screen to the app by using the default logo and theme. If you approve me, I will start working on its design and show it to you.
Thank you!

**Comment by iamvs-2002** [comment]
I am sorry, but I don't think it is really useful because, since Anki Droid is an educational app, Splash Screen would be really annoying for the users.

**Comment by david-allison-1** [comment]
I don't think any of my apps have an animated splash screen. 

Personally, I think there's better things that we could focus on

**Comment by mikehardy** [comment]
Agreed - there are real UI issues if that's the goal. For instance breaking CardTemplateEditor into multiple screens like on the desktop instead of trying to have 3 text areas on one tiny phone, or Accessibility improvements (which typically have the effect of making the UX/UI better for everyone)
