### ISSUE TITLE
Modify the UI for the overview tab in the Statistics activity

### ISSUE THREAD

**Issue by iamvs-2002** [ankidroid/Anki-Android#8448]
**Is your feature request related to a problem? Please describe.**
Since the overview tab mostly contains text, it is important to create a nice UI.

**Describe the solution you'd like**
I will improve the UI by trying every possible modification such as adding the background for each different topic, or displaying the sub-topics in the grid, etc, and hence chose the best/most optimal out of them.

**Describe alternatives you've considered**

**Additional context**

**Comment by david-allison-1** [comment]
Hi, thanks for the report. Could you fill out the template

**Comment by mikehardy** [comment]
https://github.com/ankidroid/Anki-Android/wiki/User-Interface-contribution

**Comment by iamvs-2002** [comment]
> Hi, thanks for the report. Could you fill out the template

Yea, I'll add it soon.

**Comment by iamvs-2002** [comment]
![Screenshot_20210406-231747_AnkiDroid.jpg](https://user-images.githubusercontent.com/54304786/113755802-5c6eff00-972e-11eb-997b-d316ded92a2c.jpg)

I meant about this screen, it's UI can be improved by using different sections for each type of stat.

**Comment by david-allison-1** [comment]
Hi, can you fill out the template

**Comment by Akshay0701** [comment]
@iamvs-2002 instead of adding background and making in grid ,
can we implement calendar stats in AnkiDroid , below image is from Anki Desktop , 
![review-heatmap-1](https://user-images.githubusercontent.com/52353967/115052965-313d9a00-9efc-11eb-96fd-373f1df4227b.png)
