### ISSUE TITLE
Investigate _pre21 xml files

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#8454]
We're on API 21 now, see how/whether we can combine these files, and determine why they were called `_pre21`

`fab_label_background_black_pre21.xml`
`fab_label_background_pre21.xml`

**Comment by ritvij14** [comment]
@david-allison-1 how can I check their exact usage? I saw these files and they have the same content (which is also the same as v21/fab_label_background.xml)

**Comment by david-allison-1** [comment]
> How can I check their exact usage? I saw these files and they have the same content (which is also the same as v21/fab_label_background.xml)

"find all (Ctrl+Shift+F)", then right click an instance and perform Android Studio's "Find Usages"

We also don't need `v21`

**Comment by david-allison-1** [comment]
An example to start off:

https://github.com/ankidroid/Anki-Android/blob/c1697ad37158b47d4a44c200e7428704af61792b/AnkiDroid/src/main/res/values/theme_black.xml#L100

**Comment by Paras-Saini** [comment]
I'll want to work on this issue.

**Comment by mikehardy** [comment]
Fantastic! Thanks

**Comment by Paras-Saini** [comment]
Thanks sir.

**Comment by Paras-Saini** [comment]
@mikehardy  i have investigate the above file and below is the path of it.
AnkiDroid/src/main/res/drawable/fab_label_background_pre21.xml

**Comment by david-allison-1** [comment]
Okay, the questions are:

* Dig into the history to find why the files were named `_pre21`
* Now we're post-21, what can we do to simplify the code

**Comment by Paras-Saini** [comment]
Ok.

**Comment by Paras-Saini** [comment]
@david-allison-1 i'am suncying my project because it showing errors, so we have to upgrade my gradle, till then please i need further elaboration on this.

**Comment by Paras-Saini** [comment]
@david-allison-1 can i do it with tool target API,??
By adding-   <RootTag xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools" >

**Comment by Paras-Saini** [comment]
<RootTag xmlns:android="http://schemas.android.com/apk/res/android"
xmlns:tools="http://schemas.android.com/tools" >

**Comment by Paras-Saini** [comment]
@david-allison-1 can i do it with tool target API.?

**Comment by david-allison-1** [comment]
> @david-allison-1 can i do it with tool target API.?

The first stage of this is to look into the git history and see why these were called `pre_21` in the first place, and what the post-21 alternatives are.

**Comment by vinishhub** [comment]
what we can do is we can use [Layerlist]( https://developer.android.com/guide/topics/resources/drawable-resource) to combine these files

**Comment by vinishhub** [comment]
can i work on this issue if you don't mind??

**Comment by Paras-Saini** [comment]
If,  u're confident  then u can..

**Comment by vinishhub** [comment]
ok! after looking into the git history of `fab_label_background_black_pre21.xml`  was named `fab_label_background.xml ` the only difference is the   color earlier we were using `#151515` now we're using `@color/material_grey_700`

**Comment by vinishhub** [comment]
@david-allison-1  please assign me this issue .

**Comment by Paras-Saini** [comment]
@david-allison-1 i want more information it will be great for me.

**Comment by david-allison-1** [comment]
The point of this Issue is to investigate the history of why the file was needed. You know more then I do at this point.

**Comment by Paras-Saini** [comment]
Sure,  thank you.

**Comment by mikehardy** [comment]
Still valid and a good first issue
