### ISSUE TITLE
[Bug] 2.14.6 - Android 11 - onRenderProcessGone triggered when app is in background

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8459]
###### Reproduction Steps

1. Open AnkiDroid
2. Open a card
3. Move AnkiDroid to background
3. Do something which causes the WebView to OOM - Discord Video, open camera, etc...

###### Expected Result

* We only show the toast when the app is visible

###### Actual Result

* AnkiDroid shows a toast: the `Fatal Error: WebView renderer crashed. Cause: %s` message

###### Debug info
```
AnkiDroid Version = 2.14.6

Android Version = 11

ACRA UUID = ed31b78c-342f-42f0-92c1-0ee430a93ec6

Scheduler = std2

Crash Reports Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Note: Only a good first issue if you can reproduce this error

**Comment by niki0712** [comment]
Can I work on this issue?

**Comment by david-allison-1** [comment]
> Can I work on this issue?

Sure!

**Comment by farhazulMullick** [comment]
I am begining to continue my journey to Open Source contribution.
I am how to generate this bug please guide me

**Comment by mikehardy** [comment]
@farhazulMullick welcome! I think @niki0712 is already working on this, as the comments show above. Additionally the reproduction steps are included in the bug description, successfully learning how to reproduce and reproducing the issue is a significant part of the task I don't believe there is further guidance.

**Comment by niki0712** [comment]
@david-allison-1 I'm trying to reproduce this error currently I'm downloading and installing Android 11 on my emulator I will need some more time as I lack resources

**Comment by vinishhub** [comment]
I would Like to work on this issue If it is still open

**Comment by david-allison-1** [comment]
@vinishhub I believe @niki0712 may still be looking into this.

Give them 48 hours to respond, then it's yours
