### ISSUE TITLE
[Bug] Card Browser - Select Many Crash

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8460]
I have discovered a bug related to this feature and wanted to let you know (I can try to collaborate on this):
- Enter Card Browser, choose a deck with enough cards to scroll.
- Long-Press the top card.
- scroll down and long-press the bottom card (Any two cards that need scrolling to go from one another.)

**Expected** : Select all cards between.
**Actual**: AnkiDroid Crashes.

https://user-images.githubusercontent.com/53411854/113493598-4de3d600-94e9-11eb-986e-846fe3e6a384.mp4

This is the line where it hangs
``` CheckBox cb = childView.findViewById(R.id.card_checkbox); ```

_Originally posted by @madelesi in https://github.com/ankidroid/Anki-Android/issues/8278#issuecomment-812937391_

**Comment by david-allison-1** [comment]
@madelesi Thanks for the detailed report! You might want to subscribe to this issue (right hand toolbar) for progress updates

**Comment by madelesi** [comment]
@david-allison-1 Sure! I was posting it as a comment first because it was a new feature and I thought about making an issue later. I'll see if I can contribute alongside @mrudultora

**Comment by david-allison-1** [comment]
Closing: duplicate of #8467 (just picking one issue to consolidate discussion)
