### ISSUE TITLE
Name field in `Create Deck` dialog should get auto-focused on opening

### ISSUE THREAD

**Issue by ShridharGoel** [ankidroid/Anki-Android#8462]
**Is your feature request related to a problem? Please describe.**
Selecting the `Create Deck` option opens a dialog with a field to enter the name of the deck but does not auto-focus on the field.

**Describe the solution you'd like**
The name field should get focused by default and keyboard should get opened since typing a name is the only purpose of that dialog box.

**Comment by ShridharGoel** [comment]
@Arthur-Milchior @david-allison-1 Please let me know if this is a valid issue and if I can start working on it.

**Comment by david-allison-1** [comment]
Seems reasonable, let's do it!

**Comment by ShridharGoel** [comment]
I have noticed that options like `Rename deck` and `Create subdeck` require a functionality similar to this. Should I create separate issues for them?

**Comment by david-allison-1** [comment]
Let's audit in https://github.com/ankidroid/Anki-Android/issues/8464, no need for one issue per item

**Comment by ShridharGoel** [comment]
Okay, I also thought to have one single issue for handling other such cases.
