### ISSUE TITLE
[Enhancement] Audit and improve dialog usage

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8464]
UX enhancement related to #8462, should likely be broken up into further tasks, rather than taken on in one go.

We should:

* Audit dialogs to see if they should open up the keyboard (#8462)
    * Consider a program design to make this functionality easy to accomplish
* Audit dialogs to see if "enter" on the on-screen keyboard should perform a submit, rather than close the keyboard.
   * Example: "Create Deck" dialog, as it is single-line
   * Consider a program design to make this easy to accomplish

**Comment by ShridharGoel** [comment]
I would like to work on this.

**Comment by ShridharGoel** [comment]
I would like to work on this.

**Comment by ShridharGoel** [comment]
We can create a static utility function which can be used at the required places.
