### ISSUE TITLE
[Bug] Card colour does not get updated on selecting a flag

### ISSUE THREAD

**Issue by ShridharGoel** [ankidroid/Anki-Android#8466]
###### Reproduction Steps

1. Go to Card Browser
2. Long click on a card
3. Select any flag from the flag menu
4. Notice the card's colour.

###### Expected Result

The card colour should get updated according to the selected flag.

It's working fine in 2.14.6.

###### Actual Result

The card colour doesn't update until the Card Browser is reopened.

###### Video depicting the issue

https://user-images.githubusercontent.com/35566748/113611997-e191df80-966c-11eb-8698-55d228d6252e.mp4

###### Debug Info:

> AnkiDroid Version = 2.15alpha38
> Android Version = 9
> Manufacturer = Xiaomi
> Model = Redmi Note 8
> Hardware = qcom
> Webview User Agent = Mozilla/5.0 (Linux; Android 9; Redmi Note 8 Build/PKQ1.190616.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Mobile Safari/537.36
>ACRA UUID = 817bfdac-1e58-49a7-aa67-67c23db0bb49
> Scheduler = std
> Crash Reports Enabled = false
> DatabaseV2 Enabled = true

> `git rev-parse HEAD` shows?

`2d344bfb26b7a97e3173c8db4461a0def36e496f`

Edited by @Arthur-Milchior to add all informations in the top level post

**Comment by ShridharGoel** [comment]
If this issue is valid, then I would like to work on it.

**Comment by david-allison-1** [comment]
What version of AnkiDroid are you using?  `Settings - About AnkiDroid - Copy Debug Info`

This works for me

**Comment by ShridharGoel** [comment]
`v2.15alpha38`

I have built it from the `master` branch.

**Comment by david-allison-1** [comment]
`git rev-parse HEAD` shows?

**Comment by ShridharGoel** [comment]
> `git rev-parse HEAD` shows?

`2d344bfb26b7a97e3173c8db4461a0def36e496f`

**Comment by david-allison-1** [comment]
> What version of AnkiDroid are you using? `Settings - About AnkiDroid - Copy Debug Info`

Hmm... Could you provide all the information listed in the debug info

**Comment by ShridharGoel** [comment]
###### Debug Info:

```
AnkiDroid Version = 2.15alpha38

Android Version = 9

Manufacturer = Xiaomi

Model = Redmi Note 8

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; Redmi Note 8 Build/PKQ1.190616.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.141 Mobile Safari/537.36

ACRA UUID = 817bfdac-1e58-49a7-aa67-67c23db0bb49

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

**Comment by david-allison-1** [comment]
I can't reproduce this, could you provide a failing unit test (which you made pass) along with your fix, if possible

**Comment by david-allison-1** [comment]
Could you also confirm that this is a regression from 2.14.6

**Comment by ShridharGoel** [comment]
> Could you also confirm that this is a regression from 2.14.6

It's working fine in `2.14.6`.

**Comment by Arthur-Milchior** [comment]
If you wait longer, does the color appear ? 

I've just tested, it took a few seconds to update on my phone , which is far too slow but another problem.

**Comment by ShridharGoel** [comment]
> If you wait longer, does the color appear ?
> 
> I've just tested, it took a few seconds to update on my phone , which is far too slow but another problem.

On my device, the colour doesn't appear until the card browser is opened again. Tested by waiting for more than a minute.

**Comment by Arthur-Milchior** [comment]
Ideally, I'd love if you could do a bisection to find the commit introducing the bug. But if you need to recompile, reload on your device and test each case, that's going to be very long. 

However, I really have no idea what to do else

**Comment by ShridharGoel** [comment]
> Ideally, I'd love if you could do a bisection to find the commit introducing the bug. But if you need to recompile, reload on your device and test each case, that's going to be very long.
> 
> However, I really have no idea what to do else

I tried doing that but it was even happening on some commits which were few months old. I'll check even older commits to find the one which introduced the bug.

**Comment by Abanoub-Asaad** [comment]
Can I work on this issue?

**Comment by david-allison-1** [comment]
> Can I work on this issue?

If you can reproduce it, then sure, thanks!

**Comment by ShridharGoel** [comment]
This is the commit which has caused the bug: https://github.com/ankidroid/Anki-Android/commit/3e7983670370141b6dc2e1ab3d7a4036c0585def

**Comment by ShridharGoel** [comment]
This seems to be the commit which has caused this bug: https://github.com/ankidroid/Anki-Android/commit/3e7983670370141b6dc2e1ab3d7a4036c0585def

**Comment by david-allison-1** [comment]
> This seems to be the commit which has caused this bug: [3e79836](https://github.com/ankidroid/Anki-Android/commit/3e7983670370141b6dc2e1ab3d7a4036c0585def)

@Arthur-Milchior any idea?

**Comment by Abanoub-Asaad** [comment]
When I tried to test it, no problem appeared
https://user-images.githubusercontent.com/48657780/116272316-1a5f3900-a781-11eb-8cb5-321d025df92b.mp4

**Comment by Arthur-Milchior** [comment]
> > This seems to be the commit which has caused this bug: [3e79836](https://github.com/ankidroid/Anki-Android/commit/3e7983670370141b6dc2e1ab3d7a4036c0585def)
> 
> @Arthur-Milchior any idea?

TL/DR: #8735 

Longer: You were totally right that this commit introduced bugs. I'll shamelessly blame the fact that it is entirely due to the fact that there were no typings on Object[] and that it really was hard. But I'm sincerely sorry that you had to spend so much time on it @ShridharGoel and I'm really thankful that you bisected
