### ISSUE TITLE
NF: Add a popup to update the app when a new version is available

### ISSUE THREAD

**Issue by Ekagra** [ankidroid/Anki-Android#8469]
**Describe the solution you'd like**
I have seen there's no feature to ask the user to update the app when a new version is available, we can add a snackbar or dialogue popup for the same.

**Describe alternatives you've considered**
None

**Comment by david-allison-1** [comment]
Is this possible in a privacy-friendly manner?

How do we handle when we no longer support and Android platform?

**Comment by mikehardy** [comment]
You have to keep this up to date across multiple app stores with version information on each app store and they don't provide public APIs mostly

This is done in some apps by just assuming the install is from play store and checking that, which is something you can verify (it is possible to know where an app is installed from, programmatically) but checking the version is still the equivalent of a scrape.

The alternative is to have a server doing the job of "source of truth" (like the gitub releases page) and you integrate a library that lets you check for versions there but then you might be out of sync with published versions on an app vendor (like, Amazon App Store is currently lagging, we'd say they were available when they were not) so you would need per-store metadata.

So I think the best solution would be partial (only available for some install methods) and hacky to do the partial.

I don't think this is useful enough to do the feature, so I'm going to close this.

Appeal to authority: I maintain https://github.com/mikehardy/react-native-update-apk/ - I've done a lot of work on the in-app-updating area, and also integrated over-the-air updates etc via things like https://github.com/microsoft/react-native-code-push/ - this is a much harder area than it appears at first, and is only really a tractable problem if you constrain it to one app store, at which point it is less useful to us.

We'll let the app stores do the job

**Comment by Ekagra** [comment]
That was informative, thanks,
