### ISSUE TITLE
Possible APK size optimization effort

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8473]
2.15alpha23 https://github.com/ankidroid/Anki-Android/releases/tag/v2.15alpha23

single-architecture APKs are ~12.5MB

2.15alpha24 https://github.com/ankidroid/Anki-Android/releases/tag/v2.15alpha24

single-architecture APKs are ~19MB

20MB is acceptable these days, this is not a "bug" per se, the goal is to use the AndroidStudio APK analysis tool to *explore* the size difference and see if there are any optimizations we are missing.

I hypothesize this is from inclusion of the Rust backend which we all agreed would add size and accepted, so we may not be able to optimize it any further - the result of investigation may be "this is the minimum size for current functionality" and we just close this.

But maybe we can with some combination of more aggressive optimization settings or binary / library stripping etc.

So to be quite specific:
- build an APK for a specific architecture for each of alpha23 (pre change) and current main branch
- open each in AndroidStudio to determine where the largest size deltas are
- read tool documentation for whatever tools produce the APK components that are responsible for the change in size to see if any changes in how we use the tools are possible
- post findings here

I'm happy to take this on as it's something I've done for AnkiDroid before, but if anyone else is looking to learn more about APK size optimization and get familiar with the tools involved, it's a good introduction.

I'll leave it for a couple days in case someone chimes in with interest.

**Comment by bhamrickatmills** [comment]
@mikehardy I don't really know much about this I'd be interested in poking around! ( I don't  want sole responsibility for this, but I would like to play with the tools if that's alright.)

**Comment by mikehardy** [comment]
Sure give it a go!

**Comment by david-allison-1** [comment]
Whatever comes out of it, if we have a little more dev documentation on size analysis on the wiki, it'll be a plus for us, and future developers

**Comment by mikehardy** [comment]
Great point, and looking forward over years a section on the dev guide (or maybe a separate page linked in the dev guide) that explains it might be the most useful possible outcome over time

My first step is always to get a release APK generated for each build I'm investigating, which requires creating a java keystore that you have passwords for where the build.gradle looks for it, or altering the build.gradle temporarily to point to a keystore you control.

My second step is to open Android Studio and ask it to open the armv8 (our most used CPU architecture) .apk file in the AnkiDroid/build/outputs/etc/etc/etc folder (I always just `find . | grep '\.apk'` to find them

Then I start comparing. My guess is that size difference will be .so (native binary library files) files, and if you unzip the apk and run the `file` command on them they will include the word 'stripped' etc meaning the easy optimizations are done. But maybe not?

**Comment by atharva20-coder** [comment]
@mikehardy I searching over the internet about this and found some resources can I try for it. I have done a similar thing for our (I and my friend made it in 10th std) Android App.

**Comment by atharva20-coder** [comment]
![Anki-Android  E__clone_Anki-Android  - C__Users_hp_Downloads_AnkiDroid-2 15alpha24-arm64-v8a apk - Android Studio 10-04-2021 17_17_10_LI](https://user-images.githubusercontent.com/69634375/114268846-e8c83d00-9a20-11eb-9db3-61c6632dd3f9.jpg)

I analyzed and compared both the APK and what I found is this ☝☝

**Comment by atharva20-coder** [comment]
I have analyzed and compared both the API and this is what it shows.

![Anki-Android  E__clone_Anki-Android  - C__Users_hp_Downloads_AnkiDroid-2 15alpha24-arm64-v8a apk - Android Studio 10-04-2021 17_17_10_LI](https://user-images.githubusercontent.com/69634375/114270607-fb477400-9a2a-11eb-8072-813f6772ea18.jpg)


I have found solutions to reduce APK size
There are certain methods like 
1. Crunching the images
The aapt tool can optimize the image resources placed in res/drawable/ with lossless compression during the build process. For example, the aapt tool can convert a true-color PNG that does not require more than 256 colors to an 8-bit PNG with a color palette. Doing so results in an image of equal quality but a smaller memory footprint.
*SAMPLE CODE*

aaptOptions {
    cruncherEnabled = false
}

2. Remove unused resources.



![Screenshot 2021-04-10 181919](https://user-images.githubusercontent.com/69634375/114270548-9ee45480-9a2a-11eb-8f96-bb01018ea884.png)

android {
    // Other settings

    buildTypes {
        release {
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

**Comment by mikehardy** [comment]
Interesting - 

- cruncherEnabled looks interesting, we do have some PNGs still around until we are converted to all SVGs - I'd take a PR for that
- I am wary of shrinkResources, that can cause other problems if you are not careful, here is my past experience with that ;-) (fastsquatch is me on twitter) https://twitter.com/fastsquatch/status/1196475279688028160 - this was a real problem I had before 

Following the rule of thumb for optimization where you focus on the things that have the biggest impact, the thing to do is actually to look at the next level down in rsdroid.so

Is the construction of rsdroid.so optimal? Is there some stripping or anything that we could do there?

It is built here https://github.com/david-allison-1/Anki-Android-Backend/

I wonder, for instance, is the file including multiple architectures at once?

 https://github.com/david-allison-1/Anki-Android-Backend/blob/f7ec0c47302eeaace165e7b2dbcf86d9b2c4e367/rsdroid/build.gradle#L39

Is it being stripped correctly and optimized in the release profile of the build?

I honestly have no idea :-)

**Comment by dae** [comment]
14.5MB sounds about right for a release build - it includes things like https libraries for syncing, regex libs, unicode tables, all of the translations, etc. I forget what the config was for that Anki version, but it's probably also embedding sqlite into the rsdroid.so, so if you're not accessing sqlite outside of the backend, you may be able to remove the other sqlite lib

**Comment by dae** [comment]
There is a compiler option to optimize for size instead of performance that you could try - I don't know what the relative tradeoff would be.

**Comment by mikehardy** [comment]
Thanks for the headsup - would be curious to *see* the size/performance tradeoff if @atharva20-coder is interested in finding the flags, getting an rsdroid build environment setup and then doing a set of comparison builds. 

but I think the biggest win as you mention is to purge out our requery dependency (external sqlite build)

@david-allison-1 is this statement correct or not? "we are not touching the collection outside of the Rust code while running on android devices now" ?

As a further optimization, we are using and bundling okhttp for various things at the Java level. If size optimization is a thing (note from me: it is a thing but not *that* much of a thing at our current reasonably-acceptable size) then we could port the syncing / HTTP related bits next and purge out the okhttp dependency as well. I'd put that as a low priority item vs other things personally.

**Comment by david-allison-1** [comment]
At the time, I expected that Rust was going to fail to initialize on some devices due to dodgy Linux implementations (I'm going to guess: missing `rand` style functions). 

We currently fall back to requery if the Rust-based collection access is not available.

Testing has been /much/ more promising than expected. 

Other than that:

https://github.com/ankidroid/Anki-Android/blob/aa0c51bcae88ffbfa76224c27beed0c6d923dcd9/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L303-L317

To note: AFAIK `MetaDB` uses the Android framework SQLite implementation

**Comment by atharva20-coder** [comment]
> * cruncherEnabled looks interesting, we do have some PNGs still around until we are converted to all SVGs - I'd take a PR for that

So should I convert all the PNG's to SVG or should I compress the size for now(later on I want to convert all PNG's into SVG's)?

Feeling a bit confused please explain.😕

**Comment by dae** [comment]
I did not test performance, but compiling for size brings things down by about 1-2MB - I probably wouldn't bother with it.

**Comment by david-allison-1** [comment]
2MB is significant.

I don't feel I have the capacity to take on testing within the next few days (I'll see how things pan out after the GSoC application period is over on the 14th). 

I'd be happy for someone to take this on in the mean-time

https://github.com/johnthagen/min-sized-rust provides a very good guide.

Plan:

* modify `https://github.com/david-allison-1/Anki-Android-Backend/blob/main/.github/workflows/linux_build.yml` to publish an artifact so we can quantitatively check for size changes
* Add a unit test to https://github.com/david-allison-1/Anki-Android-Backend to ensure against regressions in `catch_unwind` and error reporting from panics
* Ensure that https://github.com/mozilla/rust-android-gradle doesn't override flags
* Send in PRs with each of the modifications and see the size increase/decrease from each suggestion
* Combine them, and ensure the result is smaller

**Comment by dae** [comment]
Looks like for the latest desktop code it's just over a MB, and 800k after the library gets compressed. Switching the setting is comparatively easy, it's testing various scenarios to make sure the performance tradeoffs are justified that's the time consuming part.

**Comment by mikehardy** [comment]
Here is some low-hanging fruit - it appears my publishing automation doesn't strip symbols from .so files, likely because the ndk isn't installed or similar: https://github.com/ankidroid/Anki-Android/runs/2359122237?check_suite_focus=true#step:10:95

**Comment by dae** [comment]
Rust release builds don't include debug symbols by default, so not sure that would help here

**Comment by mikehardy** [comment]
> Rust release builds don't include debug symbols by default, so not sure that would help here

Seems reasonable...

For anyone else following along I just want to be clear that I will not block 2.15 on this. It's a "nice to have" for me, we are no longer a super slim app but at the same time our peer average is 16.9MB for the app category on play store, we are right about average. I'm just exploring if there are obvious things we are missing.

So far it appears the answer is "not really" with a more detailed answer that involves potential to shave maybe 3MB total between, ranked from will likely do or try to "eh, probably not...":

- purge all PNGs for SVGs (should do anyway, has a PR that could land actually, will check)
- rely 100% on platform sqlite + rsdroid sqlite (has potential, might be easy, and would really simplify our dependencies, I might try it)
- size-optimized rsdroid build that may perform worse (iffy, not a huge gain and I'd prefer to build 100% same as desktop if possible - blazing a new "needs continuous performance testing" path sounds terrible)
- maybe purge okhttp and rely entirely on rsdroid for sync and platform http or rsdroid for other transfer (not for 2.15...)

I appreciate the brainstorming and investigation here, we can probably slim down to at least "peer average" vs just a tiny bit overweight vs average

**Comment by mikehardy** [comment]
PNGs to SVGs resurrected - #5134 ! Just rebased that and fixed it up and re-pushed it

**Comment by mikehardy** [comment]
using platform sqlite as in #8695 gets us this comparison

```
-rw-rw-r-- 1 mike mike 20467830 Apr 25 11:59 AnkiDroid-play-arm64-v8a-release.apk
-rw-rw-r-- 1 mike mike 21408293 Apr 25 12:02 AnkiDroid-2.15alpha45-arm64-v8a.apk
```

About 1MB there, and honestly it is probably the same performance at this point. I'll have to have @Arthur-Milchior  try it though :-)

**Comment by mikehardy** [comment]
Okay - punting any further consideration of this to 2.16, I've picked the low-hanging fruit for 2.15.
- merged SVG conversion
- posted PR for framework sqlite - it's not merged but *it* is tagged for 2.15 (to either do it or decide not to) so that's fine

**Comment by Arthur-Milchior** [comment]
I'll put it on my phone and test it. However, I've never used 
But a small slowness will be hard to notice, as a lot of things went slightly slower after rust. Not enough to be worth not doing it, nothing close to what it used to be in 2019

**Comment by mikehardy** [comment]
I keep seeing this and wasting time scanning it. Summary comment on final tasks that may (or may not be) reasonable:


- size-optimized rsdroid build that may perform worse (iffy, not a huge gain and I'd prefer to build 100% same as desktop if possible - blazing a new "needs continuous performance testing" path sounds terrible)
- maybe purge okhttp and rely entirely on rsdroid for sync and platform http or rsdroid for other transfer (not for 2.15...)

**Comment by mikunimaru** [comment]
I think language-related optimization is the most effective.
I tried to compare the size of apk by changing the value of build.gradle android defaultConfig resConfig.

original  
22,020,096

resConfigs "en"
16,252,928

resConfigs "en", "de"
16,646,144

resConfigs "af", "am", "ar", "az", "be", "bg", "bn", "ca", "ckb", "cs", "da",
            "de", "el", "en", "eo", "es", "et", "eu", "fa", "fi", "fil", "fr", "fy", "ga", "gl", "got",
            "gu", "heb", "hi", "hr", "hu", "hy", "ind", "is", "it", "ja", "jv", "ka", "kk", "km", "kn", "ko", "ku",
            "ky", "lt", "lv", "mk", "ml", "mn", "mr", "ms", "my", "nl", "nn", "no", "or", "pa", "pl", "pt",
            "ro", "ru", "sat", "sk", "sl", "sq", "sr", "ss", "sv", "sw", "ta", "te", "tg", "tgl", "th", "ti", "tn", "tr",
            "ts", "tt", "uk", "ur", "uz", "ve", "vi", "wo", "xh", "yue", "zh-rCM", "zh-rTW", "zu"
26,738,688

The size of about 400kb per language may be a treasure trove of apk size reduction factors.
Above all, it is less stressful than optimizing intricately intertwined functions.

**Comment by david-allison-1** [comment]
I'd like to prompt for adding UPX to Anki-Android-Backend's CI: https://github.com/johnthagen/min-sized-rust#compress-the-binary - it seems like the largest gain for the smallest effort

**Comment by dae** [comment]
To save a few megabytes of storage, you'd be introducing a separate decompression step on startup that requires loading the entire binary into memory, and it may cause false positives from antivirus programs - doesn't seem worth it IMHO.

**Comment by mikehardy** [comment]
I am okay with our current size and size-related trade-offs personally vs anything truly fancy. We can't delete languages because we let users switch at will, it is not dependent on the system. Doing semi-fancy compression...mmm I don't know ;-).

We are still just a little smaller than the average learning app, and nearly every other app I use daily. No, we are no longer a lean-mean 8MB app, but we (or I?) knew where we were going when Rust came in, and the previous efforts prior to 2.15 got us to "smaller than average".
