### ISSUE TITLE
[Bug] Saving Note - Freeze/Crash

### ISSUE THREAD

**Issue by MrkEstnt** [ankidroid/Anki-Android#8474]
###### Reproduction Steps

1. Add card info [Basic (and reversed card)]
2. Click Save icon

###### Expected Result
Proceed to next empty card in same deck.

###### Actual Result
Saving Note pop up remains in place. Must quit application and restart. Typically, card has been added with no data lost.

###### Debug info

AnkiDroid Version = 2.14.6

Android Version = 9

ACRA UUID = 4e7383c9-4993-4ce8-8a84-a671ede485b7

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Oh no - thanks for reporting this!

I'm marking it as a good first issue as we have lots of new contributors and perhaps one of them could see if this is still reproducible on the main development branch or on 2.14.6 - it may have already been fixed

**Comment by oaeka** [comment]
Well, i tried to reproduce it but it worked fine

**Comment by david-allison-1** [comment]
@MrkEstnt Thanks for the report! Sorry this is happening

* Did anything happen before this broke (software update/new phone)?
* How recently did this start occurring?
* Are you able to provide us with a copy of all your Anki Data (excluding images)
  * If you don't have private data: could you zip the file located at `AnkiDroid/collection.anki2` on your phone and upload it here
  * If you do have private data, could you let us know and we'll work something out

**Comment by HarshitaSingh828** [comment]
in which software we have to code

**Comment by david-allison-1** [comment]
> in which software we have to code

@HarshitaSingh828 Could you post general question on our Discord, or read our [wiki](https://github.com/ankidroid/Anki-Android/wiki/) for the answers: Java

**Comment by MrkEstnt** [comment]
This problem started recently, namely when I started using AnkiDroid on my
Chromebook.

The only other thing different is that I started using the US INTL keyboard
to type accented letters directly into cards in the French deck.

Please see the attached zip file.

**Comment by david-allison-1** [comment]
Hi @MrkEstnt, no file has been attached, could you come to GitHub and post it: https://github.com/ankidroid/Anki-Android/issues/8474

**Comment by MrkEstnt** [comment]
[collection.zip](https://github.com/ankidroid/Anki-Android/files/6273586/collection.zip)

**Comment by david-allison-1** [comment]
I don't get this freeze, but... there's a lot of things that are strange about your card types.

What do you want `Basic (and reversed)` to do?

Right now, there's a template for `Card 1` which has

```
{{Sample Question - Type Your Name}}
<br>
{{Mark ...}}
```

Ideally this should be:

front:
```
{{Front}}
```

back:
```
{{FrontSize}}

<hr id=answer>

{{Back}}

**Comment by MrkEstnt** [comment]
I think this template for Card 1 was from when I wanted to type answers in, which I no longer wish to do.

How do I access the card templates within AnkiDroid?

**Comment by MrkEstnt** [comment]
Sorry, I was able to access Card 1 via a particular card and change it to reflect the code above.

What should the back code be?

**Comment by david-allison-1** [comment]
----

```
{{Back}}
```

```
{{FrontSide}}

<hr id=answer>

{{Front}}
```

**Comment by Paras-Saini** [comment]
I'll want to work on this issue.

**Comment by Paras-Saini** [comment]
@david-allison-1, plz assign me this good first issue,.

**Comment by MrkEstnt** [comment]
Changing the Front template appears to have resolved the issue. Thanks so much for everyone´s help!
