### ISSUE TITLE
[Bug] "Modify today's  new card limit" option has been removed (2.15alpha 39)

### ISSUE THREAD

**Issue by boolbag** [ankidroid/Anki-Android#8481]
###### Reproduction Steps
Not sure if you can reproduce. For me these steps work for all the decks I've tried them on.

In a deck that has lots of new cards, I always manually add new cards via _Custom study / Modify today's new card limit_

1. Today, I went to do that and the option was missing: the first option in the _Custom study_ menu was _Modify today's review card limit_. No option to change the new card limit. That's new in alpha39 or a very recent alpha (don't recall whether the last upgrade was from alpha38)

2. Went to Anki Desktop, added two new cards for the day, synched, they were reflected in Ankidroid, and the option reappeared.

3. Just to check if I was dreaming, zapped the two new cards from the cue (entered -2 in the new card limit), synched, and tried to add them again: the _Modify today's  new card limit_ was gone again!

###### Expected Result
When pressing _Custom Study_, the _Modify today's  new card limit_ option needs to always be there, like it used to be.

###### Actual Result
When pressing _Custom Study_, the _Modify today's  new card limit_ option is absent.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
On it. Thanks for the report!
