### ISSUE TITLE
[Bug] Regression CustomStudyDialog filtering on tags will result in a crash

### ISSUE THREAD

**Issue by TarekkMA** [ankidroid/Anki-Android#8487]
I think this #8341 introduced a bug in `CustomStudyDialog`, it removed the setter for the listener (which is great, since we can't relay on it to be there after a configuration change) but it assumed the fact that `getActivity()` would return an activity that does implement the interface.

In the case of `CustomStudyDialog` the interface was implemented on the dialog, not on its hosing activity `StudyOptionsActivity`.

```
2021-04-05 21:48:15.228 22091-22091/com.ichi2.anki E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ichi2.anki, PID: 22091
    java.lang.ClassCastException: com.ichi2.anki.StudyOptionsActivity cannot be cast to com.ichi2.anki.dialogs.TagsDialog$TagsDialogListener
        at com.ichi2.anki.dialogs.TagsDialog.lambda$onCreateDialog$1$TagsDialog(TagsDialog.java:171)
        at com.ichi2.anki.dialogs.-$$Lambda$TagsDialog$TJXB9icr-xFZpv9Zstg5vm6cF3o.onClick(Unknown Source:2)
        at com.afollestad.materialdialogs.MaterialDialog.onClick(MaterialDialog.java:410)
        ......
        ......
```

###### Reproduction Steps

1. Open custom study dialog
2. select tag filtering
3. have fun in the tag dialog
4. once you click on ok, it crashes

###### Expected Result
no crash

###### Actual Result
crash

**Comment by TarekkMA** [comment]
I plan to solve this issue, but I figure that waiting on #8322, so we don't waste time on solving merge conflicts.

The same thing that will be done to #8406, I would apply here.
- Extract all decencies to be initialized and used via member fields, instead of casting or calling a static method every time the object is needed
    - initialization will be done  in `onAttach` so the hosting activity will be active to be casted
- Swap the  `onAttach` initialization with constructor initialization and introduce a `FragmentFactory`

**Comment by Swado** [comment]
Hello, I would like to contribute to this bug, I have tried to reproduce and seen the bug.

**Comment by TarekkMA** [comment]
@Swado you better wait for #8322 to be merged. I was planning to solve it myself, but if you want to take it no problems.

Here are some pointers:
You will need knowledge on `FragmentFactory` (I have some resources listed in #8369) and it's better to use the class I have recently added #8483 `ExtendedFragmentFactory`

**Comment by TarekkMA** [comment]
@Swado I assume you will not be working on this, so I just wanted to let you know that I will start working on it.
