### ISSUE TITLE
Search Option For List of Deck 

### ISSUE THREAD

**Issue by ANUJAGRAWAL2000** [ankidroid/Anki-Android#8488]
**Is your feature request related to a problem? Please describe.**
It may be that the user have a long list of decks and he created a deck some days ago but now he is having trouble in finding that particular deck due to very long list but the user know the name of the deck so if we provide the search functionality it will be helpful.
**Describe the solution you'd like**
The search view will show that list of deck which user search.
**Describe alternatives you've considered**
Open to discussion from members
**Additional context**

**Comment by ANUJAGRAWAL2000** [comment]
@david-allison-1 Please check this issue. I want to work on this issue.

**Comment by david-allison-1** [comment]
We already have this. It appears if the user has over 10(?) decks.

Have you encountered this problem yourself?

**Comment by ANUJAGRAWAL2000** [comment]
Okay. 
Can we allow this for even less decks(<10)?

**Comment by david-allison-1** [comment]
Is there a method that's compatible with the issue raised: https://github.com/ankidroid/Anki-Android/issues/7835
