### ISSUE TITLE
[Bug] Extreme lag/slowdown when returning to "main view"

### ISSUE THREAD

**Issue by charlesoblack** [ankidroid/Anki-Android#8495]
###### Reproduction Steps

1. Have some cards due.
2. Do the cards normally.
3. Return to "main deck view" either through the "back" button or through finishing the cards currently due.

###### Expected Result

The application responds normally.

###### Actual Result

The application hangs for a period of ~5 seconds, displaying the pre-reviews "due cards" count, then returns to normal, updating the "due cards" count. Sometimes the application does not return to normal.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

(working on this; the bug does not happen every time)

Google Pixel 3a
Android version 11
Ankidroid v2.14.6

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, has this started happening recently?

If you try a parallel version of an older release (`Parallel.A`), do you still have the problem?

2.13.5 for example: https://github.com/ankidroid/Anki-Android/releases/tag/v2.13.5

**Comment by charlesoblack** [comment]
It started happening a few releases ago. I haven't been very regular with
my Anki unfortunately, so I don't know exactly when. I think it might have
been in February.

Not sure how to run a parallel version, let me look into it. The bug hasn't
happened today yet so I'm starting to suspect it somehow fixed itself... as
of ~a week ago it was still happening. Was there a new release recently?

**Comment by david-allison-1** [comment]
Nothing that will have solved the issue (I believe):

Installing a parallel release:

https://github.com/ankidroid/Anki-Android/releases/tag/v2.13.5 - click "AnkiDroid-2.13.5.parallel.A.apk" and install.

If it's flaky, let us know when it next happens and we'll look into it further.

**Comment by charlesoblack** [comment]
I was just about to post saying that it had probably resolved itself, when it happened again.

Debug info:
```
AnkiDroid Version = 2.14.6

Android Version = 11

ACRA UUID = e7b8fd0a-ae52-4444-9980-7fa8f7816db4

Scheduler = std

Crash Reports Enabled = true
```

I'll try installing 2.13.5 in parallel and use that instead for the next few days (or however long my Anki streak lasts...).

**Comment by mikehardy** [comment]
@charlesoblack if you're installing parallel builds you'll have more fun with the 2.15 releases - I'm packing that up for beta release today, it's ready to go and has an astonishing amount of progress plus a new toggle to turn hardware rendering back on for you, in advanced settings https://github.com/ankidroid/Anki-Android/releases

**Comment by charlesoblack** [comment]
Sure. I was trying 2.13.5 in parallel and it seemed fine for ~700 cards. There was one moment with a slight delay but it was much shorter than the ones I've observed in 2.14.6.

I'll install 2.15 beta in parallel once you've packaged it. :)

**Comment by charlesoblack** [comment]
Looks like the bug is still in 2.13.5. Should I try one minor version further back?

Is it possible that it is related to writing progress to the internal db? I have ~36k cards, and most of them have associated media (audio and images).

**Comment by mikehardy** [comment]
I don't know, I only go forward :lotus_position:  (laughing, but serious). Use the 2.15 parallel.

**Comment by charlesoblack** [comment]
Yep, still happening on 2.15 beta.

Also having slowdowns when rendering the card. Sometimes it will freeze after doing a card and rendering the next one. Might be related?

**Comment by mikehardy** [comment]
@charlesoblack can you confirm that you went in to settings advanced and enabled hardware rendering? If so, this may be some other problem...

**Comment by charlesoblack** [comment]
I must have missed that request, sorry.

My option has "disable card hardware render", and ir's off (by default?). So I am using hardware rendering I guess.

Should I try without it and report back?

**Comment by mikehardy** [comment]
Oh I fear I have led you on tangent, apologies. That is a setting primarily aimed at Android 8/8.1 handsets and it should default to off for you on Android 11. If you use software rendering things will only be worse!

Is your collection something that you can share or does it have proprietary information you can't share? The next step for debugging this will be to get your collection (if possible) so we may attempt to reproduce it with the specific types and volumes of data you have. If you can share it you can zip and attach /sdcard/AnkiDroid/collection.anki2 here, or share the same somehow to my github email address. If that's not possible I understand - my notes are boring but not everyone's are ;-).

**Comment by charlesoblack** [comment]
It does have a few birthdays that I'm not comfortable sharing. It happens with some premade decks, though, for instance [this one](https://ankiweb.net/shared/info/685421036).

I can also send my (zipped) collection to you via email, but I would kindly ask that you do not misuse the information of course. Do you think this is necessary given that the issue occurs with a premade deck? (Is there maybe scheduling information that's relevant? or maybe it's the size of the collection?)

**Comment by mikehardy** [comment]
Happening on premade decks is sufficient if you attest they'll reproduce, and I'm more comfortable with that. Privacy is a real thing :-), and simply not handling data is best way to avoid mishandling it. Thanks for the link!

**Comment by charlesoblack** [comment]
I've been testing as I do my Anki cards and as of today, on v2.15.4 I haven't seen any slowdowns for some time now. I'm not sure what the original issue was but it seems like it's fixed now.

I'll close the issue and hopefully we won't have to reopen it. :)

**Comment by mikehardy** [comment]
Thanks for reporting back, I really appreciate it and of course I'm happy it seems to be working for you. Yes, :crossed_fingers:
