### ISSUE TITLE
in android 10 mobile anki-app , when i add a new card in a deck ,there is a label which has the number of the card referred as (Cards : card1). the bug is that number does not change every time i add a new card. 

### ISSUE THREAD

**Issue by 3mmar7amed** [ankidroid/Anki-Android#8501]
###### Reproduction Steps

1.add a new card 

###### Expected Result

cards : card(number of the card in the deck)

###### Actual Result
cards: card1 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
It's listing the card templates which may be generated when the card is added.

Do you have a proposed solution?

![image](https://user-images.githubusercontent.com/62114487/113898836-211f0f80-97c4-11eb-85ab-e6f9ca35987e.png)

![image](https://user-images.githubusercontent.com/62114487/113898891-2d0ad180-97c4-11eb-8a2a-b83c0e60cd01.png)

**Comment by 3mmar7amed** [comment]
yes, we can make it generic not fixed in the template. i have experience with web which I can have the number of the card from the backend (which will be the index of the card +1 probably in an array or list) and send it to the template

**Comment by 3mmar7amed** [comment]
it would be done like that

**Comment by 3mmar7amed** [comment]
can I go ahead that?

**Comment by david-allison-1** [comment]
No, it doesn't make sense from what we're trying to accomplish with that text.

I'm open to alternatives, but the best alternative would be to rename "Card 1" to something along the lines of "Single Sided Card".

But, we'd need to have an upstream change in Anki Desktop before we make this change, and we'd need to propose this in Anki Desktop before it's enabled

**Comment by 3mmar7amed** [comment]
sorry, i did not get you, what do you mean by "along with simple flashcard " could give me an example?
if we should propose it first on Anki desktop, does it hard to do on desktop first? or we can deal with it?
