### ISSUE TITLE
FAQ page for developers

### ISSUE THREAD

**Issue by atharva20-coder** [ankidroid/Anki-Android#8506]
While going through the Idealist for GSoC 2021. It was mentioned that Anki needs a Documentation page for developers.
A FAQ page will be a great thing to have for an organization like Anki as a FAQ page helps an organization in the following ways: 

1. Your FAQ Help You Address Your Reader’s Needs.  
2. Boost Your Search Engine Optimization.
3. FAQs enable you to deal with specific queries that your contributors have.
4. They also represent high-quality and relevant content that can improve ranking performance.

## Solution
From the above points, it is quite clear why Anki should have a FAQ page.
Therefore I started making one along with a documentation page for Anki.

Progress of my work
Link for live documentation page: https://anki-docs.netlify.app/
Link for FAQ page: https://anki-faq.netlify.app/

Currently, it contains dummy text as work is still in progress : 😊

**Comment by david-allison-1** [comment]
Hi, I'm not sure whether a GitHub issue will be the right place to plan this, but let's get cracking. 

I think the first stage would be to discuss our needs in detail

Presumably this is going to augment or replace some, or all of our wiki: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide

Regarding your points:

(2) and (4): I'm only looking for discoverability from developers looking to contribute to the project, SEO is important in that contributors could find the documentation if the internal search is insufficient, which isn't an ideal position to be in.

I don't see how to differentiate (1) and (3), they seem to be the same point.

----

Moving on to design: I'm not the most versed in UX, but I've come across this resource and it seems very pragmatic for idea generation with links to some very good tutorials: https://uxtools.co/challenges/

I think we'll want to work through these items: not purely methodically, but to get a good grasp of what we want from the design. 

I don't know how we want to approach this, but if we don't have a better option: it feels we either want a list of 'needs/workflows', and/or a list of 'personas', from which we generate 'needs'.

Going through a few personas off the top of my head, 

* Onboarding/first contributor 
* Developer (code/methodologies)
* Maintainer

I'd be interested in hearing if anyone feels this is a pragmatic way to model the issue, and I'm very open to moving it forward to generate 'needs'
