### ISSUE TITLE
Anki Desktop Settings overwriting Ankidroid's when syncing [Bug]

### ISSUE THREAD

**Issue by skinac** [ankidroid/Anki-Android#8515]
###### Reproduction Steps

1. Change App Deck Settings
2. Sync app
3. Sync desktop

###### Expected Result
desktop and ankidroid syncing

###### Actual Result

ankidroid's settings reverted to desktop's older ones.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.14.6
Android Version = 10
ACRA UUID = db26d0f7-0413-4219-b4bd-c3170dedfa0c
Scheduler = std2
Crash Reports Enabled = true

###### Research
x
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I believe this (closed, until just now) issue #3662 is actually the same as this one, and is still potentially a problem. I'm going to close this in favor of #3662 as that already contains lots of information on the general problems of syncing the settings - this does come up from time to time, I understand it can still be a problem
