### ISSUE TITLE
Improve the icons of community menu with official icons

### ISSUE THREAD

**Issue by tanmayChakrawarty** [ankidroid/Anki-Android#8517]
The icons in the community menu are not looking good replacing them with official logos will make it look good.

Before:- 
![before](https://user-images.githubusercontent.com/75254780/114027316-dcaf7480-9894-11eb-8c74-86b2320b59db.jpg)
After:-
![after](https://user-images.githubusercontent.com/75254780/114027610-2e57ff00-9895-11eb-9b12-d966c5408a79.jpg)

I have already done this so if it looks like it will be a good pull request then I will do the pull request.

**Comment by david-allison-1** [comment]
Do we have permission to use those images?

**Comment by tanmayChakrawarty** [comment]
These are vector assets so I think we can use them.
Source:- https://materialdesignicons.com/

**Comment by david-allison-1** [comment]
> @david-allison-1 These are vector assets so I think we can use them.
> Source:- https://materialdesignicons.com/

Could you link the individual icons that they're using, along with their license

**Comment by tanmayChakrawarty** [comment]
@david-allison-1 Following are the links of individual icons along with GitHub repo and LICENSE
Github Repo:- https://github.com/Templarian/MaterialDesign
LICENSE:- https://github.com/Templarian/MaterialDesign/blob/master/LICENSE
Reddit icon:- https://dev.materialdesignicons.com/icon/reddit
Discord icon:- https://dev.materialdesignicons.com/icon/discord
Facebook icon:- https://dev.materialdesignicons.com/icon/facebook
Twitter icon:- https://dev.materialdesignicons.com/icon/twitter

**Comment by david-allison-1** [comment]
Looks good

**Comment by tanmayChakrawarty** [comment]
@david-allison-1  So can I create a pull request for this ?

**Comment by david-allison-1** [comment]
Sure! Be sure to include the licenses
