### ISSUE TITLE
[Bug] Gestures for answer buttons don't work

### ISSUE THREAD

**Issue by kuroni** [ankidroid/Anki-Android#8527]
###### Reproduction Steps

1. Enable gestures
2. Set some gesture action to an answer action (e.g. answer button 1, answer button 3, answer recommended, etc.)
3. Go to any deck and perform the gesture.

###### Expected Result
The answer action should be performed after the gesture.

###### Actual Result
The answer action is not performed after the gesture.

###### Debug info
Tested on both physical device and emulator.

Physical device info:
```AnkiDroid Version = 2.15alpha39

Android Version = 10

Manufacturer = samsung

Model = SM-A307GN

Hardware = exynos7904

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-A307GN Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 330c9b2a-f22f-47aa-a891-66352d287395

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

Emulator info:
```
AnkiDroid Version = 2.15alpha39

Android Version = 9

Manufacturer = Google

Model = AOSP on IA Emulator

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 9; AOSP on IA Emulator Build/PSR1.180720.117; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/69.0.3497.100 Mobile Safari/537.36

ACRA UUID = d28ce267-ee89-4faf-a3d4-3fc904411482

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
The issue only affects the latest alpha release. I was able to pinpoint the commit that creates the issue (https://github.com/ankidroid/Anki-Android/commit/559b3f1e47c1dbdb6395007b31592d311337e003).

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Thanks!

Conflict between  559b3f1e47c1dbdb6395007b31592d311337e003

and https://github.com/ankidroid/Anki-Android/blob/5542ad6ea5f212c04ae8dd93e19626832c25b11d/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L2840

`performClick` doesn't send anything to the touch listener

**Comment by kuroni** [comment]
Hm, I dug around for a while, but I don't find a good solution simply because there is no `performTouch`.

What do you think about just copy-pasting the touch handling code instead of calling through fake-clicking like we're doing right now? Personally I have no trouble with that, but if the touch handling code changes in the future we will need to fix in two places which is not an ideal thing.

**Comment by boolbag** [comment]
Was about to report a problem and saw this bug report. Here's some additional info:
- the "swipe problem" was introduced in 2.15alpha40 (alpha39 was swiping fine)
- for me the swiping issues are left, right and up (down is fine unless the page is long and needs to scroll)

Thank you!!!

**Comment by david-allison-1** [comment]
> Hm, I dug around for a while, but I haven't found a good solution yet simply because there is no `performTouch`.
> 
> What do you think about just copy-pasting the touch handling code instead of calling through fake-clicking like we're doing right now? Personally I have no trouble with that, but if the touch handling code changes in the future we will need to fix in two places which is not an ideal thing.

I'd consider extracting out the logic from the touch handler, or extracting the touch handler variable and calling into it directly.

Would like a regression test as well for the command

Happy for someone to work on this, or I can take it on. Would like to get this sorted soon as it's frustrating for alpha users

**Comment by kuroni** [comment]
I can take on it. Just to clarify, is the regression test here referring to the gestures mapped to answer button, or the answer button logic itself?

**Comment by david-allison-1** [comment]
> I can take on it. Just to clarify, is the regression test here referring to the gestures mapped to answer button, or the answer button logic itself?

Awesome!

I'd go through `executeCommand -> assertion`. But use your judgment
