### ISSUE TITLE
Implement Downgrade & Quit [in progress in Anki-Backend repo]

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8529]
If we can "Downgrade & Quit" in 2.15, this will save us a lot of hassle with the database schema upgrade in 2.16

This will allow seamless downgrades from 2.16 to 2.15

Open to discussion for how we present this option to users

**Comment by mikehardy** [comment]
Hmmm - that's interesting.

How exactly does Desktop do it?

Seems like it will need coordination "forward in time" and backwards, specifically, 2.15 now already has the feature of detecting and messaging incompatible database versions if I recall correctly? It should forward-reference the feature perhaps and say more, e.g. "Open the collection with a compatible future version then `<insert however to downgrade and quit here`"

This feels like an advanced maneuver though, I mean we don't intend for people to *ever* need to downgrade and quit so maybe an advanced settings button...

**Comment by david-allison-1** [comment]
Anki Desktop has it on the "Switch Profile" menu.

![image](https://user-images.githubusercontent.com/62114487/114191925-d4af0d80-9944-11eb-9897-d28710aee742.png)

We're in an interesting place with the downgrade & quit: AnkiDroid 2.15 has **future** knowledge of how to downgrade from the new database schema in AnkiDroid 2.16.

My main worry is that a beta user will load AnkiDroid 2.16, which does (probably opt-in while in alpha: to discuss) a database schema upgrade, and won't be able to go back without loading a backup or syncing.

With this feature: we can handle a user who updates to 2.16, and either: 

* Automatically downgrade the schema
* Show a dialog allowing them to do so

**Comment by mikehardy** [comment]
Even more important to me is the casual tester / bugfix user / multiprofile person with parallel builds.

We will *definitely* see people that need to do this.

Hmm thinking about this then, from a user perspective, if my hunch the *normal* case will be parallel access across versions, and a very plausible but probably rarer case will be people actually going from a 2.16 version to a 2.15 version:

- add the ability to downgrade and quit in the code (of course, all built on that)
- add the ability to downgrade and quit every time as a preference (advanced setting)
- for parallel builds during alpha (determined by examining package name + version name) make downgrade and quit the default if the pref did not exist?
- add the ability to downgrade and quit one time explicitly (in same advanced setting area)

Since this is in an area of Anki Desktop that we don't mirror anyway, we're relatively free in how we do it, and honestly that screenshot is totally non-intuitive to me anyway, does it downgrade all the profiles' collections, or just one? if just one is it the open one? but I'm on a profile opening screen so which one? Not copying that might be a plus

**Comment by mikehardy** [comment]
the above would have the side effect of us being able to still casually recommend parallel builds for bugfix confirmation / testing without having to discuss this at all or fear blowing up their main play store stable install in the normal case.

**Comment by dae** [comment]
When a desktop user switches back to a previous version without using that button (which downgrades all profiles at once), they receive a message saying "This profile requires a newer version of Anki to open. Did you forget to use the Downgrade button prior to switching Anki versions?". So their data is not gone, and is still accessible in the newer version, but if they wish to downgrade, they need to switch back to the newer version and perform that step first. The upgrade/downgrade process potentially writes tens of megabytes of notetype data for large collections, builds/discards indexes and so on, so I'm not sure it's something you'd want to happen on every "quit"

If 2.16 will continue to use the Rust code it currently uses (ie, not update to the latest desktop code), then the downgrade logic will be identical, and you could just automatically downgrade in 2.15 if encountering a collection with the later schema. But if 2.16 plans to bump the Rust code as well, you'll need to make sure you don't bump it past the next schema change, or 2.15 will no longer be able to read the file.

**Comment by mikehardy** [comment]
Mmm "writes tens of megabytes of data..." - yeah that's not something to do by default every time.

Perhaps there should be a stronger gate in the alphas then indicating it's a big step prior to doing it (one of those irritating "are you sure?" dialogs with some detail - it's for alpha consumers so detail is not a bad thing - then rely on the "normal" behavior you indicate @dae 

That would actually exercise the "normal" behavior more during alpha release (with exception of a confirm dialog before forward-converting) so is a plus in that way

**Comment by david-allison-1** [comment]
I don't plan to bump the anki commit in Rust for 2.16 (sans AnkiDroid-related changes)

The main plan:

  * To get to Schema 16, we need to:
     *  update the database (`openCollection` on the Rust - one line change)
     *  Make changes to the classes which handle the schema changes (Decks, Tags, Models, DConf, Conf)
        * Some of these classes have been heavily modified, despite being in `libAnki`, which makes this a slow job of untangling functionality. I've started.  Probably a week or two of effort
     * Apply these changes to a java-compatible shim, to provide an upgrade path without forcing the update

Plan for functionality before 2.16 release:

* Dev only - completely unstable: flag in manifest 
   * Get unit tests passing, ensure that downgrade works 
* Alpha - Add an advanced preference flag, scary warning, possibly best for new testing profiles
   * Pick a couple features to entice testing: New Stats page seems like a good one
* Mid-stage alpha: suggest opt-in/auto for new collections
* Late-stage alpha/beta: Upgrade on open

**Comment by david-allison-1** [comment]
@mikehardy Need a quick "OK" on the backup strategy, I'd like to test & refactor the current backup code before continuing:

* Add a `ankidroidPre16Downgrade.colpkg` backup before performing the operation
  * This does not contain the time in the filename (questinable)
* Overwrite if one already exists
* Ignore this backup when performing the "keep 8 backups" check

Test: Ensure that the "restore from backup" shows this file

**Comment by mikehardy** [comment]
Seems sensible - backups fail to create for lack of space sometimes as well
