### ISSUE TITLE
Lag when showing the answer of a card

### ISSUE THREAD

**Issue by mtbox9x** [ankidroid/Anki-Android#8530]
Hi. I'm using HTC10 android 8.0. It is lag when showing the answer of a card, can not scroll down correctly. I tried a old version 2.13.5 parallel.A and it work well. Can you fix this in next version? Thank you

**Comment by mikehardy** [comment]
Hi @mtbox9x - this is a known issue and duplicates #8328 - you will want the latest 2.15alpha as mentioned there but our state of the art has moved a bit, once you get the 2.15alpha that fixes the issue you'll need to enable the fix and we would love to hear confirmation if it works for you, as mentioned here https://github.com/ankidroid/Anki-Android/pull/8458#issuecomment-813055838
