### ISSUE TITLE
[Bug] Card browser becomes empty on going back from Settings.

### ISSUE THREAD

**Issue by ShridharGoel** [ankidroid/Anki-Android#8533]
###### Reproduction Steps

1. Go to Card browser (should be containing some cards).
2. Go to Settings.
3. Press the back button.
4. Card browser shows as empty.

###### Expected Result

Cards should have been displayed.

###### Actual Result

Card browser is empty.

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by sumadithya** [comment]
I tried to reproduce this.
It works inconsistently, it gives expected result few times but gives actual result mostly.

**Comment by kartikeysaran** [comment]
Yes it was reproduceable would love to take this issue up !

**Comment by ShridharGoel** [comment]
@kartikeysaran I am already working on this.

**Comment by ShridharGoel** [comment]
This is not happening on the latest master build, hence closing.
