### ISSUE TITLE
Add CrowdIn and lint rules for Preference Title Length

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8534]
We should ideally add either/or:

* A lint rule to ensure that preference text in English does not exceed a limit
* Hints for CrowdIn to ensure that our translators do not hit the same issue

We may possibly allow the text to be multiline, I'd be against this, as it's a title and should be succinct.

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8417#issuecomment-811310435_

**Comment by prateek-singh-3212** [comment]
I would like to work on this issue.

**Comment by david-allison-1** [comment]
Note: Using 42 as the limit, as strings of that length existed in English without complaints
