### ISSUE TITLE
Implementing In-app updates 

### ISSUE THREAD

**Issue by kartikeysaran** [ankidroid/Anki-Android#8548]
Adding In-app updates inside Ankidroid which is a Play Core library feature that prompts active users to update your app.

**Additional context**
https://developer.android.com/guide/playcore/in-app-updates

**Comment by mikehardy** [comment]
I am very aware https://github.com/mikehardy/react-native-update-apk/issues/16

I still don't think it has value versus almost anything else, duplicates #8469
