### ISSUE TITLE
[Bug]Add Unit test to functions in KeyUtils.java

### ISSUE THREAD

**Issue by haran2248** [ankidroid/Anki-Android#8555]
UnitTest has to be added to the functions getDigit() and isDigit() in keyUtils.java

**Comment by haran2248** [comment]
Im working on this

**Comment by david-allison-1** [comment]
Hi, you don't need an issue for a unit test - 

I typically add issues as a reminder for myself or future developers where a high-value test would be useful, where this is flagged in a Code Review, but as something that isn't worth blocking the PR over.

**Comment by haran2248** [comment]
Ohh makes sense,So i can make a PR directly?

**Comment by david-allison-1** [comment]
> Ohh makes sense,So i can make a PR directly?

Sure!
