### ISSUE TITLE
com.ichi2.anki.AbstractFlashcardViewer#selectAndCopyText function not working[Bug]

### ISSUE THREAD

**Issue by Mohaned-Elfeky** [ankidroid/Anki-Android#8565]
###### Reproduction Steps

1. Enable lookup setting in advanced options
2. open a card and press lookup text (should copy the text of the card into the clipboard if clipboard is empty)
3. copy text manually and press lookup again (should lookup the text in external dictionary)

###### Expected Result

when pressing lookup text first time should copy the text automatically into the clipboard and on the second click should lookup the copied text.

###### Actual Result

when pressing lookup for the first time doesn't copy the text and the lookup doesn't work unless the user copies the text manually.

###### Debug info
AnkiDroid Version = 2.15alpha38

Android Version = 10

Manufacturer = Google

Model = Android SDK built for x86

Hardware = ranchu

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Android SDK built for x86 Build/QSR1.200715.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.185 Mobile Safari/537.36

ACRA UUID = 8721fab1-8ef3-4f81-bdd8-865355533c10

Scheduler = std

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by PANG-hans** [comment]
Sorry, I enabled loopup setting in advanced options, but can not follow step `2` and `3`. Could you please give some pictures? Or maybe it depends on the selected `lookup setting`?

**Comment by Mohaned-Elfeky** [comment]
try setting the lookup dictionary setting to the fourth option(Leo.org-web)

**Comment by alsanchez** [comment]
Likely related to  #5024

**Comment by BrayanDSO** [comment]
Lookup was removed
