### ISSUE TITLE
Cloze: After "Show Answer" in long cards, restart from the top of card page

### ISSUE THREAD

**Issue by mvonkessel** [ankidroid/Anki-Android#8567]
###### Reproduction Steps

1. When a lot of text is used in a card in cloze mode  you have to scroll down to the cloze 
2.  As soon as you press show Answer, you have to scroll down again to see the cloze answer. In the computer version the answer just reveals.

###### Expected Result

It would be great, if it works as in the computer version. When pressing show answer, the cloze just reveals without jumping back to the start of the page and then requires to scroll all the way back down.

###### Actual Result

It requires a lot of time to scroll down again to the paragraph with the cloze after show of answer, as one did it just shorty before. This makes me prefer the computer version, but I wish it would be different.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by error12368** [comment]
Can I work with this? 🤓

**Comment by david-allison-1** [comment]
Absolutely!

**Comment by error12368** [comment]
I tried adding a private variable `mScrollOnY' to `AbstractFlashCardViewer' to record the scroll amount in Y, and scroll the current card to the recorded variable. 

It ends up unstable, sometimes the card will jump back and sometimes it will scroll to the recorded place as I expected.😢

I think it may relates to the way that Anki loads the answer. Is Anki reload whole card sometimes when user taps on "show answer" button, causing the variable `mScrollOnY' to reset?
