### ISSUE TITLE
[Bug] Gestures not working since 2.15alpha40

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#8572]
###### Reproduction Steps

1. have gestures turned on
2. choose "recommended answer (green) for swipe left
3.  try to answer card with good (swipe left)

###### Expected Result

card is marked good, next card appears

###### Actual Result

nothing happens

###### Debug info
sorry, immediately uninstalled the alpha, so no debug info.  2.15alpha40 on Android 9

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
@Anthropos888 Without the debug info (at least phone information, from a current install) this report is much less useful, please provide something as we have several issues that are for instance Android version dependent, e.g. this one for Android 11 #7375 

Also could be #8527 which is a recent regression as the whole gesture system continues to handle more edge cases but hits a few bumps along the way

**Comment by Anthropos888** [comment]
Sure, here's the debug information of my currently installed version:

AnkiDroid Version = 2.14.6

Android Version = 9

ACRA UUID = 751875a7-f00b-41fe-90b1-2bcc6af0617f

Scheduler = std2

Crash Reports Enabled = true

**Comment by farjadilyas** [comment]
Can I work on this?

**Comment by david-allison-1** [comment]
> Can I work on this?

@farjadilyas 
Could you discuss with @kuroni (here pr in Discord) - would rather not duplicate the effort - LMK if there's anything I need to do to unblock
