### ISSUE TITLE
Lint: Toast.makeText -> UIUtils.showThemedToast

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8576]
This would save time on code reviews.

I'll take this on in the next couple of days if nobody wants it. Low effort, high reward with new applicants

**Comment by nicdard** [comment]
I would be happy to help here

**Comment by david-allison-1** [comment]
Great, thanks!

You should be able to find sample code:

https://github.com/ankidroid/Anki-Android/tree/89a7679839f55fa4748155ded6e73b33dc8fc545/lint-rules

The main aim would be to ensure that new users are advised that a call to `Toast.makeText` should be replaced with a call to `UIUtils.showThemedToast`

I think the file: 

https://github.com/ankidroid/Anki-Android/blob/4935ac517deb2d784bba0a9f7793fd2e65f99712/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectSystemCurrentTimeMillisUsage.java 

would be the most similar

Unit testing this is very simple, and you get visual feedback in the IDE if you rebuild the project.

Let me know here if you need more help

**Comment by sridhar-5** [comment]
Hi,
Happy and Interested to solve this issue. But one thing is, I've gone through the code in this link you've mentioned 

Link : [https://github.com/ankidroid/Anki-Android/blob/4935ac517deb2d784bba0a9f7793fd2e65f99712/lint-rules/src/main/java/com/ichi2/anki/lint/rules/DirectSystemCurrentTimeMillisUsage.java](url)

But i don't see a call to `Toast.makeText`. can i know exactly where, this is to be replaced.

Thanks in Advance.

**Comment by nicdard** [comment]
Hi sridhar-5, actually I am gonna opening a PR (hopefully) today for this.

Thank you david-allison-1for the examples and the advices, I think it is all clear and I will work on the issue as soon as I come from the office :)

**Comment by sridhar-5** [comment]
sure.

**Comment by nicdard** [comment]
> sure. Just curious about where the `Toast.makeText` actually exist.

I don't know if there are calls actually in the codebase know apert from the body of `Uiutils.showThemedToast`, but the task aims to spare code review time by suggesting people to use this helper method instead of the one from Android framework. At the end, once developed, the lint rule will signal all occourences to the one from the framework if any and I will therefore fix them within the change

**Comment by sridhar-5** [comment]
> > sure. Just curious about where the `Toast.makeText` actually exist.
> 
> I don't know if there are calls actually in the codebase now apart from the body of `Uiutils.showThemedToast`, but the task aims to spare code review time by suggesting people to use this helper method instead of the one from Android framework. At the end, once developed, the lint rule will signal all occourences to the one from the framework if any and I will therefore fix them within the change

Thanks for the reply man. Looking forward for your successful Pull request, would love to have a look at the code after the changes you've mentioned.

**Comment by prateek-singh-3212** [comment]
Hi @nicdard 
If you need any kind of help regarding this issue then feel free to PM me on discord.

**Comment by nicdard** [comment]
> Hi @nicdard
> If you need any kind of help regarding this issue then feel free to PM me on discord.

Thank you! I have just submitted the PR, the only doubt is how to link in the JavaDoc both android.widget.Toast and UIUtils classes, since when I try the IDE shows me an error like: `Symbol android.widget.Toast is not accessible from here`.

**Comment by prateek-singh-3212** [comment]
@nicdard I am encountering this issue too. It is a bug in Android Studio. 
https://youtrack.jetbrains.com/issue/IDEA-207715
