### ISSUE TITLE
[Bug] Coptic letters not rendering properly

### ISSUE THREAD

**Issue by pinnerup** [ankidroid/Anki-Android#8578]
I'm using Anki for learning Coptic vocabulary, and for some reason, AnkiDroid has problems displaying Coptic unicode text. Some cards are garbled in a way that it seems the app is rendering separate letters of a word on top of one another. 

As an example, the word "ϩⲱⲡ" is rendered in my AnkiDroid like this: 

![2021-04-11 21 26 31](https://user-images.githubusercontent.com/7774108/114319257-08d72980-9b11-11eb-8f93-e4a1d3e8836a.jpg)

Oddly enough, the AnkiDroid editor has no problem displaying the same text correctly:

![2021-04-11 21 26 38](https://user-images.githubusercontent.com/7774108/114319269-112f6480-9b11-11eb-9324-cff8ba02cf6f.jpg)

I think the problem may be confined to words that start with one of the 'special' Coptic letters, e.g. ϣ, ϥ, ϧ, ϩ, ϫ, ϭ or ϯ. Also oddly, when the text comes up again for later reviews, it sometimes displays correctly.

###### Reproduction Steps
1. Create a card containing the text "ϩⲱⲡ" on the front
2. Place the card in a deck
3. Review the card in AnkiDroid

###### Expected Result
AnkiDroid displays "ϩⲱⲡ".

###### Actual Result
AnkiDroid displays garbled letters.

###### Debug info
AnkiDroid Version = 2.14.6
Android Version = 11
ACRA UUID = df647715-8dac-4307-a05a-e639bbbc58bd
Scheduler = std2
Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dorrin-sot** [comment]
Hi can i work on this?

**Comment by mikehardy** [comment]
Sure! It would be great to have some sort of unit test that shows the failure @pinnerup is seeing prior to fixing it. Not sure if that is possible *if* it is a problem in the WebView itself. Examining it via inspecting the WebView in the debugger may be useful https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection - which also implies that the first thing we need is a note with contents that reproduce the problem

**Comment by rillian** [comment]
I think this probably is a WebView bug. I see something similar with blink-based browsers on Android. IIRC Anki uses that for card display. See also this [Brave issue](https://github.com/brave/brave-browser/issues/15238).

@pinnerup does setting a custom font for the cards work around the problem?

**Comment by rillian** [comment]
I saw the problem just entering the same word in a new card: [card-ϩⲱⲡ.zip](https://github.com/ankidroid/Anki-Android/files/6314992/card-.zip)

NB it's a little tricky to reproduce. I see overdrawn characters the first time I look at the card, but not always on subsequent views. I can usually trigger it again by changing the font size in the card template and then tapping the view icon.

**Comment by mikehardy** [comment]
We use the Android System Webview for display, which is Chromium based and updated by Google (sometimes with bugs...) looking at google issue tracker or chromium issue tracker may show something

**Comment by Dian-Jiao1031** [comment]
I find this bug interesting and wonder if it has been fixed yet. I found that the character "ϩ" didn't display in the Android emulator, and I found that many Egyptian characters didn't display. I would like to ask where this part of the related code in the project? I thought I'd try to fix it by myself. OAO

**Comment by rillian** [comment]
I've not tracked it down yet. I think the bug is in the text rendering code of the Android webview component. Probably chromium trunk is the best place to fix it. The change will likely be easy to backport to the various Android trees from there.

I suspect it's something to do with loading the fallback font metrics and the fact that Coptic characters are split between two unicode blocks. Maybe a data race since it fixes itself after first load.

**Comment by Dian-Jiao1031** [comment]
I see，thanks. (I tried adding some Coptic font libraries and found that it didn't help.TAT)

> I've not tracked it down yet. I think the bug is in the text rendering code of the Android webview component. Probably chromium trunk is the best place to fix it. The change will likely be easy to backport to the various Android trees from there.
> 
> I suspect it's something to do with loading the fallback font metrics and the fact that Coptic characters are split between two unicode blocks. Maybe a data race since it fixes itself after first load.

I see，thanks. (I tried adding some Coptic font libraries and found that it didn't help.TAT)
