### ISSUE TITLE
Remove `android:configChanges` from AndroidManifest.xml

### ISSUE THREAD

**Issue by TarekkMA** [ankidroid/Anki-Android#8589]
Using `android:configChanges` in the declaration of activities is not a recommended practice. We should let the system handle configuration change.

https://developer.android.com/guide/topics/manifest/activity-element#config
https://developer.android.com/guide/topics/resources/runtime-changes#HandlingTheChange

I think this will not be easy since most of the app has many coupled logic in the lifecycle methods of activities/fragments.

Moving logic to [`ViewModel`](https://developer.android.com/reference/androidx/lifecycle/ViewModel?hl=en) and using some of the android architecture components would be a good start.

**Comment by nicdard** [comment]
I think this can be a really good idea, I can help on this I think :)

Do you have some tips about where to start / how to split the work?

**Comment by TarekkMA** [comment]
This should be dealt with one activity at a time, so work can be split per activity. The issue is that we need to do some refactoring and take some architecture designs so the logic is separate from the lifecycle methods.

I will wait to see what is the opinion of the maintainers about this issue.

**Comment by lukstbit** [comment]
@david-allison You closed this because you don't want to implement it? IMO, dropping our custom _configChanges_ declarations from the manifest is something we should do for most of our screens.

**Comment by david-allison** [comment]
I only fixed the GitHub close reason to match the actual state of the issue (state)

I'm fine with reopening: it should be fixed, but it's a big job, and we're so under-resourced that I can't see it happening soon.

(off topic: I implemented "not planned" support for the stale action a while later)
