### ISSUE TITLE
'Set Due Date' and 'Forget' are being counted as reviews

### ISSUE THREAD

**Issue by ThoreBor** [ankidroid/Anki-Android#8592]
###### Reproduction Steps

1.  Select a card in the browser on Anki Desktop
2.  Select 'Forget', or 'Set Due Date' (today, tomorrow+reset interval, random choice of 3-7 days all produce the same bug)
3.  Sync Anki Desktop
4.  Sync Ankidroid

###### Expected Result
Ankidroid and Anki Desktop show the same number of reviews

###### Actual Result
Ankidroid and Anki Desktop have different review numbers because Ankidroid counts those rescheduled cards as reviews.

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
has PR, stay open a bit

**Comment by mikehardy** [comment]
Bad bot, no biscuit (and slow maintainers - we are doing our best, thanks for your patience)
