### ISSUE TITLE
[Bug] - TimePreference class should have "mod-like" behavior

### ISSUE THREAD

**Issue by diegonyc** [ankidroid/Anki-Android#8593]
###### Reproduction Steps

1. call [`parseHours` static method](https://github.com/ankidroid/Anki-Android/blob/164200255997ac4750493118c24cec649191b630/AnkiDroid/src/main/java/com/ichi2/preferences/TimePreference.java#L75) with `"24:00"` as argument

###### Expected Result
Should return `int 0`

###### Actual Result
`int 24`

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research

See https://github.com/ankidroid/Anki-Android/pull/8590

*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by m4r4c00ch0** [comment]
In #8590 we talk about a "mod-like" behavior for the `TimePreference` class. 

Can we define what is the expected behavior?

Some expectations (tests) in plain-english can be helpful to define the unit tests—and implement the functionality itself :)

Also, take into account that we have a `parseHours` method **and** a `parseMinutes` method.

**Comment by PANG-hans** [comment]
Sorry, is this bug still exist?
Can i work on this issue? I'm a junior student learning _Software Engineer_, required to fix some issues on github.

**Comment by mikehardy** [comment]
Hi @PANG-hans ! I think the best idea is to find an issue labeled "good first issue" though we may be at zero on those for the moment. This one appears to have some sort of requirements definition question so it's not a great issue to start on unfortunately, we apparently need to discuss it first and decide *what* we want before we figure out how to do it. That's probably not going to happen for a while

**Comment by PANG-hans** [comment]
> Hi @PANG-hans ! I think the best idea is to find an issue labeled "good first issue" though we may be at zero on those for the moment. This one appears to have some sort of requirements definition question so it's not a great issue to start on unfortunately, we apparently need to discuss it first and decide _what_ we want before we figure out how to do it. That's probably not going to happen for a while

Emmm, maybe it's a better choice. But i'm still a freshman for github and required to use git fix some issues in the course brfore tomorrow. The issue labeled with `Good First Issue` is bit hard, so i'd want to take it as my first try with git project. Thanks a lot if you can accept the request.

**Comment by m4r4c00ch0** [comment]
@PANG-hans I did not look for a `good-first-issue` issue. When I found this bug, I was looking for untested modules on the project. The code coverage is low, you can fork the project and compile it locally. Then, find modules with low coverage and test those!

You might be surprised at what you will find. And I am sure that, even though is not an explicit issue, maintainers of this project would appreciate the additional testing :)

**Comment by PANG-hans** [comment]
> @PANG-hans I did not look for a `good-first-issue` issue. When I found this bug, I was looking for untested modules on the project. The code coverage is low, you can fork the project and compile it locally. Then, find modules with low coverage and test those!
> 
> You might be surprised at what you will find. And I am sure that, even though is not an explicit issue, maintainers of this project would appreciate the additional testing :)

Thanks a lot!
