### ISSUE TITLE
[Bug] DeckPicker is restarted while returning via Navigation Drawer

### ISSUE THREAD

**Issue by farjadilyas** [ankidroid/Anki-Android#8598]
###### Reproduction Steps

1. Open DeckPicker
2. Open Card Browser/Statistics
3. Go back to DeckPicker via the Navigation Bar

###### Expected Result
DeckPicker is opened as it was left in the back stack

###### Actual Result
DeckPicker is restarted, splash screen shown

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by farjadilyas** [comment]
I want to work on this if this is accepted. We can make a one line tweak to NavigationDrawerActivity to ensure the DeckPicker in the back stack is used while maintaining the behavior of clearing the activities above it in the back stack

**Comment by david-allison-1** [comment]
Sounds good to me, thanks!
