### ISSUE TITLE
[Bug] Very unhelpful error message for updated anki

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8601]
###### Reproduction Steps

1. Update anki to latest scheduler
2. sync anki
3. sync ankidroid

###### Expected Result

Step by step explanation of how to solve the issue

###### Actual Result

A vague explanation which do not state how to open preference and which exact button to click on

![2021-04-14-100151_183x121_scrot](https://user-images.githubusercontent.com/357361/114675427-82853800-9d08-11eb-8455-c4eac701be96.png)

###### Action to solve it:

Creating a video, without any word or text (apart from the English version of the menu), that
* Open anki
* open the tools menu
* open the preference window
* click on the scheduling tag.
* check the Legacy timezone handling button

Rewrite the error message with:
* a link to this video
* a detailed step by step explanation as I did above so that the user do not have to understand anything about the issue

Even better, if @dae would accept this (may be too complex): giving us a message we can send back to ankiweb, that would trigger the legacy timezone handling back either on ankiweb or as a suggestion on anki desktop on next sync, so that the user don't even have to do anything else than resync and accept the suggestion

**Comment by mikehardy** [comment]
Except...in 2.15 (which should release soon?) this is all fixed and we handle it correctly - it is literally the start of all the Rust conversion odyssey :-)

There is definitely a gotcha in that if on anki you don't have sched v2 enabled you don't even *see* the legacy timezone handling preference. That's unexpected...

**Comment by david-allison-1** [comment]
Legacy timezone handling is V2 only. The user won't get that message if they're on V1

**Comment by Arthur-Milchior** [comment]
How, I didn't know there was a plan to release it soon. that's great.

**Comment by david-allison-1** [comment]
> How, I didn't know there was a plan to release it soon. that's great.

https://github.com/ankidroid/Anki-Android/milestone/37 - couple of glaring bugs, add Downgrade & Quit, and we should be good to go
