### ISSUE TITLE
Feature Request: No new cards if ...

### ISSUE THREAD

**Issue by Dr747** [ankidroid/Anki-Android#8608]
Hi there, 

I've been using Anki on PC and Android for some months now and I've got an idea for a new feature I would quite enjoy having, so I thought I might share it here, maybe other people would find it useful too. I've not been practicing my vocabulary (which I use Anki for) very much for the last few weeks and so now I have a lot of cards that want to be practiced. I think it would be nice to be able go into the settings and set it, so that if that number of unpracticed cards exceeds for example 100, no new cards will be added. That would make catching up easier.

I hope you'll find this useful as well and maybe add it sometime.

Thanks!

**Comment by david-allison-1** [comment]
Hi @Dr747, thanks for the feature request!

We aim to keep feature parity with Anki Desktop to maintain ecosystem compatibility, we almost always want a feature to exist in Anki Desktop before porting it across.

You can ask for features in Anki Desktop: https://forums.ankiweb.net/

I'm closing this as there's nothing for us to do until this feature is accepted for work into Anki Desktop, please post here if you get a positive reply to let us know.

All the best,

David
