### ISSUE TITLE
[Feature request] Bury after a certain number of failed attempts

### ISSUE THREAD

**Issue by aPaci95** [ankidroid/Anki-Android#8611]
It would be cool to have an option to set a certain amount of attempt to review a card (per day). After that set amount of failed reviews, ankidroid automatically bury the card. I'm using an [addon](https://ankiweb.net/shared/info/1255924302) that does exactly this for anki desktop and i can't live without this anymore ahah It would be awesome to have this in ankidroid too!

**Comment by dorrin-sot** [comment]
> It would be cool to have an option to set a certain amount of attempt to review a card (per day). After that set amount of failed reviews, ankidroid automatically bury the card. 

Does the addon ask to bury after that certain number of times or does it do it automatically?

**Comment by mikehardy** [comment]
Hi there! If it is not a core feature in Anki Desktop, we will not implement it here.
Our policy is to implement Anki Desktop features, not add-on features - it has to be *in* Anki Desktop
If you lobby it for it on their site and they implement it, then we will follow forums.ankiweb.net/
