### ISSUE TITLE
Create unit test verifying illegal characters (like '##') may not be used in field names

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8612]
#8388 is the original issue, and #8389 fixes it, but a unit test that verifies those illegal characters can't be entered would be nice to have

The strategies below could work.

You could also extend Robolectric test, get the dialog "open" (virtually) and attempt to enter an illegal field, verifying it fails.

---------

First attempt would be to extract `TaskManager.launchCollectionTask(new CollectionTask.AddField(mMod, fieldName), listener);` to a method and override it in a test.

If that's difficult, a "TODO" in a test class to write a test for this issue would be fine

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8389#issuecomment-809842496_

**Comment by dorrin-sot** [comment]
Hi can I work on this?

**Comment by david-allison-1** [comment]
Sure, thanks!

**Comment by dorrin-sot** [comment]
Nice! Can I ask what the illegal character(s) are?
