### ISSUE TITLE
[CI] CrowdIn: We can now automate a check for "missing screenshots" on strings

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#8621]
I was asked to evaluate https://support.crowdin.com/croql/ by CrowdIn: it should support our use case, and allow us to automate the check that each translation has a screenshot

**Comment by david-allison-1** [comment]
AnkiDroid's Project Id is `720`, this differs from APIv1, which requires the project identifier (`ankidroid`) 🤦‍♀️

**Comment by david-allison-1** [comment]
Needs the CrowdIn token to continue

**Comment by mikehardy** [comment]
@david-allison-1 I don't believe I have a secure transmission mechanism for you, to send it to you? I just checked `gpg --list-keys` and I don't have one on file for you - happy to send you the crowdin key via some secure mechanism

**Comment by dae** [comment]
@david-allison worth keeping open?

**Comment by david-allison** [comment]
It would be semi-useful as a report, but we have much more pressing issues
