### ISSUE TITLE
[Bug] Bury select note automatically

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8627]
On a1ebaa00664bdb54a439da83dc6207194228e9d4 in the reviewer, the bury button directly bury the note instead of asking to choose. The suspend button works as usual

**Comment by david-allison-1** [comment]
Relevant. Was a sibling suspended?

https://github.com/ankidroid/Anki-Android/blob/a5a68b0fbecc837980174ca35f9ebf364ecc54b8/AnkiDroid/src/main/java/com/ichi2/anki/Reviewer.java#L1249-L1269

**Comment by Arthur-Milchior** [comment]
No. Some of teh cards with the problem are entirely new notes, with entirely new siblings

**Comment by Eggg0771** [comment]
May I work on this one？

**Comment by david-allison-1** [comment]
> May I work on this one？

Sure! 

* First step would be to provide reproduction steps in a comment
* Then see if you can write a failing regression test
* Ideally `git bisect` to understand where the regression was introduced to the codebase
* Then, we have context for why the issue occurred: document it in a comment, fix the issue and commit the regression test to ensure it doesn't happen again

**Comment by Eggg0771** [comment]
> > May I work on this one？
> 
> Sure!
> 
> * First step would be to provide reproduction steps in a comment on this issue (should be simple)
> * Then see if you can write a failing regression test
> * Ideally `git bisect` to understand where the regression was introduced to the codebase
> * Then, we have context for why the issue occurred: document it in a comment, fix the issue and commit the regression test to ensure it doesn't happen again

Sorry that I misunderstand the issue. I have tried many times but fail to reproduce it.

**Comment by david-allison-1** [comment]
@Arthur-Milchior Do you have repro steps for this?

**Comment by mikehardy** [comment]
@Arthur-Milchior waiting on you for steps to reproduce

It's one of the last 2.15 issues without a PR so I'm watching it closely :eyes: :smile:

**Comment by Arthur-Milchior** [comment]
My repro steps were to add a note with two cards and try to bury it. Seeing that if does not ask whether i want to bury cards or not as it should

**Comment by david-allison-1** [comment]
@Arthur-Milchior Can't repro on alpha46 using Basic & Reversed. Do you have "bury siblings" enabled?

**Comment by mikehardy** [comment]
I'll punt this to 2.16 and we can cherry-pick if we can't reproduce it

**Comment by david-allison-1** [comment]
I can repro a similar issue. I'll investigate, maybe tonight or tomorrow

I'll move this to 2.15 as I'm fairly sure it's a regression, but happy to see it moved back to 2.16

**Comment by mikehardy** [comment]
no reproduction, can reopen if we can reproduce
