### ISSUE TITLE
[Test] Regression test: Statistics

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8631]
Regression test potential here

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8626#issuecomment-820819291_

**Comment by Abanoub-Asaad** [comment]
I'm working on it.

**Comment by nicdard** [comment]
I would like to help with this, however I will probably need some guidance :)

**Comment by david-allison-1** [comment]
@nicdard 

The change would be a test of `DeckPreviewStatistics`

Have `collection.getDb()` return null

Then launch the task. 

`onPostExecute` would crash because the WeakReference (`mTextView`) was never assigned

**Comment by rodrigo-sp17** [comment]
Hi guys! Sorry for not introducing myself, but I picked this issue up today as my first and tried to solve it. Hope it helps!

**Comment by david-allison-1** [comment]
> Hi guys! Sorry for not introducing myself, but I picked this issue up today as my first and tried to solve it. Hope it helps!

Welcome! Thank you so much!!!! Feel free to join us on [Discord](https://discord.gg/qjzcRTx). 

I've been on a break from the project for a couple of days, but I'll get in to the review ASAP, I know how frustrating it can be to have a review waiting

**Comment by nicdard** [comment]
Great job, thank you @rodrigo-sp17, unfortunately I have been busy at work and University so I did try to add the test but didn't have as much time as needed to complete it during the last days

**Comment by rodrigo-sp17** [comment]
No problem @nicdard, I had some time to spare so figured why not! 
It actually took me the whole day just to make AsyncTask's onPostExecute run on tests.
