### ISSUE TITLE
[Bug] Custom steps not being hidden when v2 scheduler enabled?

### ISSUE THREAD

**Issue by dae** [ankidroid/Anki-Android#8641]
From the sounds of the following report, the user has switched to the v2 scheduler, but is still being shown a custom steps in the filtered deck screen. The v2 scheduler does not support custom steps, so they should not be displayed in that screen.

https://groups.google.com/g/anki-android/c/RuOQlwLJruo

**Comment by dorrin-sot** [comment]
I would love to try to work on this though I'll probably need a little guidance on where to start

**Comment by david-allison-1** [comment]
@dorrin-sot Options are:

https://github.com/ankidroid/Anki-Android/blob/89a52a43971ed4b54cb70de3eb65bca5af8df716/AnkiDroid/src/main/res/xml/cram_deck_options.xml

https://github.com/ankidroid/Anki-Android/blob/a299058a22c327cd14091b7d95a2e7b5123cd43c/AnkiDroid/src/main/java/com/ichi2/anki/FilteredDeckOptions.java

Hide the option if `col.schedVer() >= 2`

Check Anki Desktop code if you're unusre - typically best to keep the code open as a reference to get context for when a change occurred

**Comment by mikehardy** [comment]
@dae thanks a bunch for connecting the dots on that mailing list report and the v2 scheduler and our filtered deck screen - I don't know nearly enough about the v1/v2 scheduler or custom study decks to connect them. As an actual Anki *user* I'm a simpleton, I never custom study nor change the default settings really nor use sub-decks :sweat_smile: so I'm blind here

**Comment by mikehardy** [comment]
@dorrin-sot no pressure, but just checking: are you still working on this or do you still intend to? It's one of the last 2.15 issues without a PR so I'm watching it closely :eyes: :smile:

**Comment by dorrin-sot** [comment]
Hi sorry I've been abit busy with uni so I couldn't focus on it properly😅. Can I work on it next week or is that too late?

**Comment by mikehardy** [comment]
@dorrin-sot studies take priority every time, no worries - happy to have you back here any time in the future when you've got time, otherwise good luck with uni
