### ISSUE TITLE
UX: Add more instances of com.ichi2.preferences.IncrementerNumberRangePreference

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8647]
`Deck Options - New Cards/day` is using this class, but `Deck Options - reviews/day` doesn't.

We should be consistent, and look through the app to see where else this preference would make sense.

**Comment by mk-94** [comment]
Hi, i would like to take this one. :)

**Comment by david-allison-1** [comment]
Guidelines: https://www.nngroup.com/articles/input-steppers/

Effectively, initially go through `Preferences`, `DeckOptions` and `FilteredDeckOptions` and see which ones would make more sense using a `IncrementerNumberRangePreference ` instead of a `NumberRangePreference`.

**Comment by mk-94** [comment]
Ok, will have a look.

**Comment by mk-94** [comment]
This is my proposal where IncrementerNumberRangePreference makes more sense. 
**Deckoptions**

_New Card_
Maximale answer time
Graduating interval
Easy interval

_Lapses_
Steps
Minimum interval
Leech threshold

_Reviews_
Maximum reviews/day
Easy bonus
Hard interval
Interval modifier

_General_
Maximal answer time


**Preferences**
Reviewing
Learn ahead limit
Timebox time limit


**FilteredDeckOptions**
Limit to


All these numbers could use small steps so i think it makes sense to setup the IncrementerNumberRangePreference like Deck Options - New Cards/day

**Comment by david-allison-1** [comment]
> Steps

No, this contains multiple steps separated by a space

I think the rest seem reasonable
