### ISSUE TITLE
Shortcut option without opening app 

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#8648]
## Feature
Implement ShortcutInfo for common action like opening CardBrowser,Statistics, Settings,And Note Editor 

## Desire output of feature 
<img src="https://user-images.githubusercontent.com/52353967/115278506-289acd00-a163-11eb-99be-72049040de29.jpg" width="250" height="500" />

**Comment by david-allison-1** [comment]
* Review would be my priority - if we could disable this with nothing to do, it'd be fantastic, but fine to have with a Toast of "noting to review"
* "Add Note" would be my second preference
* Browse Cards would be third

I don't think we need Statistics. Possibly "perform sync"? What do you think?

**Comment by Akshay0701** [comment]
Review cards are a good option, not sure how we disable shortcut with nothing to do, could you guide me on this?

I think instead of statistics we can make settings shortcut, your thought?

**Comment by Akshay0701** [comment]
I think for now we should keep 3 option which is required and not include other irrelevant or less important option

**Comment by david-allison-1** [comment]
> Review cards are a good option, not sure how we disable shortcut , could you guide me on this?
> 
> I think instead of statistics we can make settings shortcut, your thought?

I don't think we need either settings or stats, but I'll leave it up to you.

We'll be able to add analytics to see which gets the most use.

----

I don't know if we can disable shortcuts, we probably can, but I don't think it'll be worth the effort (unless we can use a timer/widget to check for "learn" cards becoming active, then the shortcut will be out-of-sync with the app).

On reflection, unless we can do it perfectly (which may be hard), it's best not to bother.
