### ISSUE TITLE
[Bug] New timezone handling + scheduler v2 results in incorrect time after midnight 

### ISSUE THREAD

**Issue by kuroni** [ankidroid/Anki-Android#8652]
###### Reproduction Steps

1. Enable Scheduler V2 + new timezone handling
2. Set time after midnight to 23.

###### Expected Result
Cards are readded at 23:00.

###### Actual Result
Cards are readded at a different time (in my case it's 4:00, timezone is EST).

###### Debug info
```
AnkiDroid Version = 2.15alpha40

Android Version = 10

Manufacturer = samsung

Model = SM-A307GN

Hardware = exynos7904

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-A307GN Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.66 Mobile Safari/537.36

ACRA UUID = c97b320c-d4ba-46bd-8e39-9b9176000770

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
Setting to either scheduler V1 or turning off new timezone handling (or do both) fixes the problem.

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Your timezone information is quite curious + interesting, if I understand, that's UTC-4? But it could be UTC-5 and be either a coincidence but not the problem, or the actual problem

What *exact* timezone are you since I'm not user EST maps to anything unambiguously https://www.timeanddate.com/time/map/

**Comment by kuroni** [comment]
Currently it's UTC-4, but for a period of time in the year it's UTC-5 due to daylight saving time.

**Comment by kuroni** [comment]
Update: so I think this has more to do with syncing time after midnight more than anything ...

After the issue (which I only discovered because I was studying at around 4:00), I turned off new timezone handling (still with schedule v2 on) and went to bed.

Now (this is around 16:00), I checked the deck again and noticed that it was reset to the new day again (note that I haven't learned all cards previously, so it should not reset since my setting is at 23:00 after midnight). This time, I went to Anki on PC, changed the time after midnight settings to 23:00 (it was 4:00 on PC up until now), and the cards are correctly returned to the previous day. I synced the deck, return to AnkiDroid and tried all combinations of scheduler version + new timezone handling, and it seems to be working fine now.

**Comment by mikehardy** [comment]
Thanks for reporting @kuroni - I'm going to close this as it seems to be behaving then - we're paying close attention to this though, the new timezone handling is perhaps the most important feature (both for infrastructure with our use of the Anki Rust lib and for users so that syncing works perfectly with anki desktop) of 2.15
