### ISSUE TITLE
Floating Action Menu closes only when it is tapped again

### ISSUE THREAD

**Issue by leoshrey** [ankidroid/Anki-Android#8654]
**Is your feature request related to a problem? Please describe.**

When user opens up the floating action "+" button and want to close it again if in case he do not want to perform any operation mentioned in the floating menu, then he usually has to click the floating button again to shrink the menu.

<img src="https://user-images.githubusercontent.com/53581274/115455609-cebc0500-a23f-11eb-8900-d17419384d3e.gif" width="200" height="400" />

**Describe the solution you'd like** 

More user friendly feature can be used, like if the user can tap or scroll anywhere in the deck page to close the menu.

<img src="https://user-images.githubusercontent.com/53581274/115464496-cc12dd00-a24a-11eb-9118-b4dbc7221e24.gif" width="200" height="300" />

**Describe alternatives you've considered**
I would like to implement this feature to modify the current scenario, if it is feasible.

**Additional context**
This idea can be further expanded to include one more feature, which is hiding the Floating button itself while scrolling vertically. This will make the contents on the card page more readable, hence more friendly interface.
I would be glad to hear for suggestions.

**Comment by error12368** [comment]
Can I work on this? I think tapping other places is supposed to shrink the menu as well.😝

**Comment by david-allison-1** [comment]
I believe this is fixed in #8290 (thanks to @Akshay0701 !!)
