### ISSUE TITLE
Add support for .spx audio files

### ISSUE THREAD

**Issue by marreromarco** [ankidroid/Anki-Android#8656]
Would it be possible to support .spx audio files in AnkiDroid ?

.spx audio files are already supported on the Desktop version of Anki.

_______
What is an SPX file?

Audio file compressed using Speex compression and saved in the Ogg Vorbis container format; designed as an audio compression format specifically for speech; compresses voice at 2 to 44 kbps and supports 8 kHz, 16 kHz, and 32 kHz compression in the same bitstream.

_____
Note: Some pronunciation dictionaries use .spx format. For example, the "Langenscheidt Pronunciation German Dictionary" :
http://lingvodics.com/dics/details/1928/

**Comment by vinishhub** [comment]
I want to work  on this issue

**Comment by david-allison-1** [comment]
> I want to work on this issue

I expect that this may be a complex issue to solve if the Android device doesn't support the codec. It might be better if you work on a simpler issue.

If you still continue, do you have a planned design?

**Comment by vinishhub** [comment]
ok then no issue I will work on simpler issue ✌

**Comment by mikehardy** [comment]
If desktop supports it we have to expect we may *see* them even if we don't support them. I think it's possible get the list of codecs supported on a device but it looks like Speex is not on the list of supported formats: https://developer.android.com/guide/topics/media/media-formats#audio-formats

I'm not sure there is any action we can reasonably take here to expand support beyond what comes with devices, without risking becoming a multimedia-file-playing app, which is not our core value proposition.

If you want media files to be compatible with AnkiDroid it's important to choose format for compatibility not compression I believe

**Comment by marreromarco** [comment]
Would it be possible to add an option to play sounds with an "external player" ?

In that way, we could choose VLC Android to play sound formats that AnkiDroid currently cannot play.

**Comment by dae** [comment]
Neither AnkiWeb nor AnkiMobile support spx either, and external players sound like a lot of extra complexity - I think the easiest option would be to re-encode the files as mp3.

**Comment by mikehardy** [comment]
@dae might be good to somehow make the list of supported formats for Web/AnkiMobile/AnkiDroid accessible somehow in AnkiDesktop (plus we could do same here, as one a "supported formats" help link or something, I'm loathe to maintain an updated list even as a new source of external velocity to track, but the simple link pointers might be useful?

**Comment by dae** [comment]
The desktop list is here:

https://github.com/ankitects/anki/blob/main/qt/aqt/editor.py#L55

mp3 is the most universally supported, and that is what I recommend to people. AnkiMobile's recordings are in m4a, as iOS doesn't provide an mp3 output unfortunately.

**Comment by mikehardy** [comment]
That's slightly conflating container and codec (you can have an mp3 encoded audio in an m4a container it appears) but that runs the risk of deliberately misunderstanding you to be irritating, which is not the point, I'm *pretty* sure iOS always goes for "AAC encoded audio in an M4A container" as a default? And it appears Android supports that fine since Android 3 (well inside our minSdkVersion) so on iOS that's a fine default. Being prescriptive in Anki Desktop then ("Use mp3 files or AAC audio in an m4a file for mobile-compatible files" or some such) could be good for years.
