### ISSUE TITLE
[Bug] Waiting time when a deck is finished

### ISSUE THREAD

**Issue by sangorys** [ankidroid/Anki-Android#8660]
###### Reproduction Steps

See [my YouTube video here for the reproduction](https://www.youtube.com/watch?v=3xdXHQyTsd8)
1. I study all the flash cards of a deck

###### Expected Result
1. The deck shows that there is no more card to study
2. I can study another deck

###### Actual Result
1. The refresh of the flashCard to study takes between 30s to 1 min
2. I cannot study another deck because all cards are blank. I need to wait between 30s to 1 min

=> assumption : a background task do a long treatment to update the new data with my study

###### Debug info
AnkiDroid Version = 2.14.6

Android Version = 11

ACRA UUID = 49dbd4c4-e8da-4954-b1b6-f51241ec4dfc

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by sangorys** [comment]
Hello,

I still have the issue with the version 2.15.6

**Comment by sangorys** [comment]
Nobody can help me ?

**Comment by mikehardy** [comment]
We can reopen - not sure how to reproduce

**Comment by sangorys** [comment]
How can I help ? I am living with this bug daily since several months.

Intuitively, this is a bug with a background task which takes maybe 30s on a big database when the training has been finished on a deck. I have 3500 cards. I guess you need a big database to reproduce it

**Comment by sangorys** [comment]
I am sorry for the bad news : same behavior with the last alpha release

How can I help you more ?

**Comment by sangorys** [comment]
The bug disappears after my phone update to Android 12 !!!
