### ISSUE TITLE
Investigating GSon

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8668]
As far as I remember, some of the long tasks, such as loading the collection when the application start, takes a few second - on big collection - processing JSon. If I remember correctly, one of the bottleneck was that each JSon get operation uses a try/catch, which is is an expansive operation. The only trouble is that the JSONException are checked exception and that we don't want to `throws` them everywhere in the codebase.

I think it might be interesting to check GSon, another library for JSon. I suspect we would win time some precious seconds. Indeed:
* Its exceptions are not checked
* it can convert between JSONObjects/array and java Map/List.  This would avoid the entire overhead of the JSON library

Most of the change can be automatized, but that's not entirely trivial.  Indeed, the functions do not have the same name even if it has the same signature than in current implementation. And if we want to save this second of loading time, it's not ideal to create an intermediate class just to change the function name.

It may be useless if most of the work moves from java to rust, those try/catch will disappear with it anyway

**Comment by lazy-codebear** [comment]
Can I work on this issue? Is your meaning is using GSon library to replace now library.

**Comment by Arthur-Milchior** [comment]
You can work on it.

I don't know whether gson will replace current JSON library. What I want is to make the test and see whether it will improve loading time at all, and potentially other long operations. Even creating a note, when the note type is complex, or changing a note type, can be improved when the JSON library is efficient, as accessing template is required often

You can test over http://milchior.fr/anki/ which is my real life collection and take a dozen of seconds to load. That seemed silly (at least to me), but each second saved is actually really great for the confort of use of the app.

**Comment by lazy-codebear** [comment]
I will try to do it. It is the first time I working on anki. How does it work when import a deck?

**Comment by Arthur-Milchior** [comment]
It's not a deck but an entire collection. You'll need to use the desktop version to import it. And you should create a new profile, as otherwise it would remove the current content of your collection.
But anyway, you can probably do tests first on your usual collection or on a test collection, and once you are happy with the code change you made, test on a big collection

**Comment by TarekkMA** [comment]
Jackson is supposed to be much faster than gson.

**Comment by mikehardy** [comment]
Script a set of tests that exercise both cases on the same set of easily-available test data, then post benchmarks that others can attempt to reproduce, or it's just talk ;-)

**Comment by mikehardy** [comment]
Users only care about the performance they see in the real world on their real device, right? It has to be a practical test, like of the Anking decks or I think Arthur has his decks up for testing on https://milchior.fr but I'm not sure where?

**Comment by mikehardy** [comment]
Sorry - meant to actually tag @Arthur-Milchior - Arthur - do you have your decks available somewhere for people looking to stress test Anki things? I seem to recall you did, if not sorry for the bother

**Comment by TarekkMA** [comment]
I think this is the link: http://milchior.fr/anki/.

I found this repo with some benchmarks. https://github.com/fabienrenaud/java-json-benchmark, and Jackson is among the top. Jackson provides databinding which will be super helpful to covert models and configs from json to java classes easily.

**Comment by TarekkMA** [comment]
gson was already added as a dependency, so I replaced it with Jackson and tried to my best to use jackson the same as gson so that the minifer would only remove unused stuff.

Gson (streaming) was used [here](https://github.com/ankidroid/Anki-Android/blob/dd49160e8719934f473bbc6071e6b44cf245eb68/AnkiDroid/src/main/java/com/ichi2/libanki/importer/AnkiPackageImporter.java#L127-L143) and [here](https://github.com/ankidroid/Anki-Android/blob/dd49160e8719934f473bbc6071e6b44cf245eb68/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java#L1473-L1484)
Gson (data binding) was used [here](https://github.com/ankidroid/Anki-Android/blob/dd49160e8719934f473bbc6071e6b44cf245eb68/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/activity/TranslationActivity.java#L287-L288)

#### Gson (previous version)
![Screen Shot 2021-05-10 at 6 59 18 PM](https://user-images.githubusercontent.com/6633545/117696889-1dffb080-b1c2-11eb-8386-4072e6f8bac8.png)
#### Jackson
![Screen Shot 2021-05-10 at 6 59 05 PM](https://user-images.githubusercontent.com/6633545/117696948-2f48bd00-b1c2-11eb-85eb-6b79d12c7f85.png)

#### Additional notes 
from my research jackson seems to be very large library in term of method count and in the number of modules/extensions that can be added to it

**Comment by mikehardy** [comment]
That's quite the performance increase... It looks worth it to me

**Comment by TarekkMA** [comment]
If we go with streaming only the size would be exactly the same as the previous version with gson, but will have to write everything by hand and no more one-liners

Streaming API example form my benchmark:

https://github.com/TarekkMA/android_json_benchmarks/blob/c090f901aa369e5839bf38dc85744fcd371d587b/benchmark/src/androidTest/java/com/example/benchmark/json_parse/models/N_Deck.java#L29-L99

Should we switch to streaming only?

**Comment by TarekkMA** [comment]
Another candidate is https://github.com/ngs-doo/dsl-json , will try to get some benchmarks on it

**Comment by TarekkMA** [comment]
I guess jackson is the way to go, but should we go streaming or databinding 🤔

**Comment by mikehardy** [comment]
less code I think - not having the JSON schema embedded in our parsing code like that seems like a win

**Comment by Arthur-Milchior** [comment]
Interesting. I didn't even knew we used gson. This issue was referring to reading Decks/Models from the collection. But clearly, this is interesting too. 

Note that 
```java
                default:
                    jp.skipChildren();
```
would not be acceptable. If there are properties we don't know, we should keep them. Indeed, when we recreate the string and put it in the database, we want to put all properties we didn't change as they used to be

**Comment by Arthur-Milchior** [comment]
Great.

I'd clearly be curious, if you have the courage to go into git history, can you find and explain why we used two different libraries?
I can't figure out whether the authors explained why they had distinct needs. 

Great to see that the extra properties where taken into account. Thanks.

**Comment by TarekkMA** [comment]
Gson is used from 2013, I don't know the exact reason why but maybe the authors needed to do json streaming with gson as seen in 

https://github.com/ankidroid/Anki-Android/blob/0711bcde77f417bf274abee7b16c4b5b8f2e1b0a/AnkiDroid/src/main/java/com/ichi2/async/CollectionTask.java#L1473-L1484


If I found an interesting git message I will be sure to put it here

**Comment by TarekkMA** [comment]
@Arthur-Milchior jackson has a tree model that can replace current json classes. but I think the goal is the serilize/deserilize json from/to a type safe and expressive class instead of using string keys everywhere.

#8810 I tried migrating `Model` as a demo for what will happen if we used databinding. along with tests that will hopefully clear how it's being used.

**Comment by TarekkMA** [comment]
@Arthur-Milchior 

#8817 I have just finished converting the old `JSONObject`/`JSONArray` to utilize Jackson tree model API.

And the results are very very amazing,

## Benchmarks for parsing 34MB of models

### Current Appreach with `org.json.****` (535.8 ms)
```java
            mModels = new HashMap<>();
            JSONObject modelarray = new JSONObject(modelsJson);
            JSONArray ids = modelarray.names();
            if (ids != null) {
                for (String id : ids.stringIterable()) {
                    Model o = new Model(modelarray.getJSONObject(id));
                    mModels.put(o.getLong("id"), o);
                }
            }
```
### Current Approach with the new JSON objects (249 ms)
```java
            mModels = new HashMap<>();
            TMJSONObject modelarray = new TMJSONObject(modelsJson);
            TMJSONArray ids = modelarray.names();
            if (ids != null) {
                for (String id : ids.stringIterable()) {
                    TMModel o = new TMModel(modelarray.getJSONObject(id));
                    mModels.put(o.getLong("id"), o);
                }
            }
```
### Letting Jackson deserialize directly to the map (240 ms)
```java
            mModels = objectMapper.readValue(modelsJson, new TypeReference<Map<Long, TMModel>>() {});
```

**Comment by Arthur-Milchior** [comment]
To be honest, I'm fine with the 9ms cost of keeping current approach compared to using directly a map :p 


Yeah, you're right, that's amazing. 

I'm kind of sorry for you, because there used to me changes that can save dozens of seconds, but most are gone, and now you have to deal with changes that same 300ms. I really like ensuring that the application is as fluid as possible (and I suspect it will also uses less memory for temporary variables), and it makes the app more pleasurable. But you missed last year progress, that was more spectacular: https://www.reddit.com/r/Anki/comments/iu24ph/ankidroid_one_year_of_change_in_term_of_speed/

**Comment by TarekkMA** [comment]
Wow the difference you made is incridible, I hope I will be able to make the app more pleasurable for the end-user to use and for the developer to contribute and understand/test the code.

**Comment by mikehardy** [comment]
I think you already have!
