### ISSUE TITLE
[CI] AnkiDroid Lint isn't running

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8669]
https://github.com/ankidroid/Anki-Android/runs/2375811376?check_suite_focus=true - Working

https://github.com/ankidroid/Anki-Android/runs/2387077443?check_suite_focus=true - Not working (https://github.com/ankidroid/Anki-Android/pull/8427)

We may want a lint canary branch? Run lint on it daily, and if it passes, we have a problem

**Comment by mikehardy** [comment]
The lint canary branch is both a terrible yak shave and also a great idea.
I'll check into this

**Comment by mikehardy** [comment]
Going to skip the canary for now, I don't want to build more CI machinery if possible. I switched the lint check to be sub-module-by-name so now if variants are messed with it'll be obvious as the command will outright fail
