### ISSUE TITLE
Support for  "Malayalam" Language

### ISSUE THREAD

**Issue by vinishhub** [ankidroid/Anki-Android#8676]
**Is your feature request related to a problem? Please describe.**
AnkiDroid Does not support Malayalam Language

**Describe the solution you'd like**
Creating A `value-ml` will add Malayalam language

**Comment by vinishhub** [comment]
I want confirmation, So that I can start working on this issue. I have started working on It

**Comment by david-allison-1** [comment]
Translations are handled by CrowdIn. 

I've added: https://crowdin.com/project/ankidroid/ml-IN# , please translate there and inform us when `01-core` is translated

Thanks!

**Comment by vinishhub** [comment]
I have translated the 01-core file

**Comment by mikehardy** [comment]
@vinishhub Great! I think the next thing to do is to add it to the language lists like so: https://github.com/ankidroid/Anki-Android/commit/e1cabb4372466d9f7951b0942c215efff25dde74#diff-bc7f2d221b9823e2452393c27afb78d2510511ba80f1feca59a7d224c272667a

The next few files aren't "core" but will vastly improve the translation quality if you can do them before the language-addition PR is merged and I sync strings

**Comment by vinishhub** [comment]
I have added the language to list  I have one doubt we have to copy the content from crowdin(after translation) and paste it into values-ml right??

**Comment by mikehardy** [comment]
@vinishhub definitely not on the copying thing. Please examine the diff I linked - notice they are in a scripts directory - that script pushes the english / original strings up to crowdin, translators do the work there, then another script pulls them down automatically and creates the directories. There's nothing you need to do except propose a pull request similar to the diff I linked
