### ISSUE TITLE
Visual problems while studying cards

### ISSUE THREAD

**Issue by VergilWang15** [ankidroid/Anki-Android#8678]
**Is your feature request related to a problem? Please describe.**
When learning a card, the content on the card is destroyed and refreshed again, which will cause some visual problems.  Especially in night mode, it will make me feel that the font is flickering

**Describe the solution you'd like**
Can it be modified to add the answer to the interface instead of destroying the question and then refresh the answer and question

**Describe alternatives you've considered**
↑
**Additional context**
None

**Comment by david-allison-1** [comment]
Hi, thanks for the report. Could you fill out the "bug report" template below, especially the "Debug Info"

```
---

###### Reproduction Steps

1. 
2. 
3. 


###### Expected Result



###### Actual Result



###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))
```

**Comment by VergilWang15** [comment]
I can work on it if the issue is accepted

**Comment by VergilWang15** [comment]
This problem occurs every time I learn a card, so I think this is the font refresh mechanism of the software interface, not a specific bug

**Comment by david-allison-1** [comment]
I think the main question is "What does Anki Desktop do here". If we don't follow what's happening, then we introduce incompatibilities (for example: if a user uses a JavaScript based timer).

**Comment by VergilWang15** [comment]
---

###### Reproduction Steps

1. download a shared deck in the Chinese language with the name "考研词汇5500"
2. Do the recite part


###### Expected Result
The answer showed up below the question


###### Actual Result
The question refreshed after it is destroyed while the answer showned up


###### Debug info
AnkiDroid Version = 2.14.6

Android Version = 10

ACRA UUID = 0f861976-3cac-48d1-9363-0459937d987b

Scheduler = std

Crash Reports Enabled = false

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))
