### ISSUE TITLE
add the theme followed system

### ISSUE THREAD

**Issue by Jacky486** [ankidroid/Anki-Android#8686]
add the dark theme option for following system.

**Comment by mikehardy** [comment]
Hi there! We want to do this, but given we have 4 different themes at the moment (black, dark, light, plain) and have had them forever, it is important to take those into account for existing users as we implement the feature of following the system theme.

That work is already tracked here #5685 and has some tentative work #5686 #7824 but it's not easy so those haven't landed. Follow #5685 to see progress and you'll know when we have it

Thanks!
