### ISSUE TITLE
Shorter title asked to translator

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8689]
Some titles don't fit on a line. E.g. "share feature usage" in Russian according to @oakkiten. We should have a way to let user know they should try to make it shorter, up to adding a subtitle

**Comment by Akshay0701** [comment]
the same issue with Hindi or Marathi this is the translation of the above text in Hindi is "Sāmāyika karāya phī vaiśiṣṭya vāpara"
