### ISSUE TITLE
Convert remaining PNG files to SVG where possible

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8696]
Still need to audit more, maybe more of these may be converted but this is the current list

```
mike@isabela:~/work/AnkiDroid/Anki-Android/AnkiDroid/src (convert-icons-to-vector-assets) % find . | grep 'drawable-' |grep png|cut -f5 -d'/'|sort|uniq|grep -v ic_stat_notify|grep -v logo
ankidroid_txt.png
anki.png
av_pause.png
av_play.png
av_rec.png
av_rec_stop.png
av_stop.png
drawer_shadow.9.png
ic_action_suspend_dropdown.png
ic_eraser_variant_white_24dp.png
ic_flip_to_back_white_24px_dropdown.png
spinner_triangle.png
widget_add_note.png
widget_bg_number.9.png
widget_bg_small_finish.png
widget_bg_small.png
widget_bg_time.9.png

```

Note that logos and notification assets etc I do not think may be converted easily, and any icons we use need to be licensed correctly for our use (i.e., from material.io or similar, where we know we may use them)

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/5134#issuecomment-826349309_

**Comment by vinishhub** [comment]
I would like to work on this @mikehardy

**Comment by mikehardy** [comment]
Sure go for it! Note that material.io is the best source of icons for things we can use, but I was not able to find icons for everything. 

It's possible to draw SVGs even, without too much pain - I mention that because the "dropdown" version of the SVGs is usually the regular SVG but with a new triangle path at bottom right - that path could probably be stolen from any of the SVG icons that already have it and plopped onto the non-dropdown version of whatever svg icon already exists for the same thing but in non-dropdown form

No idea about the widget ones, or the shadow etc. Basically I don't expect everything can be converted, but some of them sure.

Please do one at a time either in separate PRs or - even better if possible - as separate commits on one PR

**Comment by david-allison-1** [comment]
Anki.png -> https://github.com/ankidroid/Anki-Android/blob/master/docs/graphics/legacy/anki.svg I think

**Comment by vinishhub** [comment]
can we use online png to svg converter to convert to svg

**Comment by vinishhub** [comment]
> separate commits on one PR

how can I create seperate commits ?
