### ISSUE TITLE
UX: Improve AnkiWeb Upload/Download Screen

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8702]
Caught a portfolio piece with a great suggestion (Ctrl+F for `AnkiWeb Sync Dialogue (Before)`: https://www.hunternielsen.com/project/04096f2e/AnkiMobile

![image](https://user-images.githubusercontent.com/62114487/116012717-38635700-a624-11eb-9de8-639a7ad6aa3b.png)

Our Dialog:

![image](https://user-images.githubusercontent.com/62114487/116012817-cc352300-a624-11eb-84ad-e8ef888f853b.png)

----

@Arthur-Milchior @mikehardy I'd like to move this to the 2.15 milestone, as it should be very simple to do, and very high impact. 

Pending on whether you agree that this would be a worthwhile change and the wording change makes sense to you

Author has provided their blessing:

![image](https://user-images.githubusercontent.com/62114487/116012847-fab2fe00-a624-11eb-8579-a75f8712aae8.png)

**Comment by mikehardy** [comment]
This would be great - the terms "upload" and "download" are ambiguous these days as well, so I'd love to evict them.

**Comment by david-allison-1** [comment]
I'll get to this tomorrow

**Comment by Arthur-Milchior** [comment]
Please use the term "Collection" instead of "Deck". Deck was used for collection long long ago. Let’s be simple but correct

**Comment by david-allison-1** [comment]
> Please use the term "Collection" instead of "Deck". Deck was used for collection long long ago. Let’s be simple but correct

Do users know what a collection is?

**Comment by Arthur-Milchior** [comment]
Collection is the term used, in anki.
* "Export format: Anki Collection package"
* "import: packaged anki deck/collection"
* A free account is required to keep your collection sychnronized

in the manual:
https://docs.ankiweb.net/#/getting-started?id=collection

In ankidroid:
* New collection
* Delete collection and create new one
* Replacing collection...
* Export collection as anki package

(tHis term appear 23 times in the res/values files in strings

So, of course, not all users know the difference, that's a certainty. But up to know, there is consistency in the entire ecosystem and this is always the term presented to user to mean "all the material stored in Anki – your cards, notes, decks, note types, deck options, and so on." (as defined in https://docs.ankiweb.net/#/getting-started?id=collection )

**Comment by david-allison-1** [comment]
Sounds reasonable
