### ISSUE TITLE
Improve keyboard handling for "Type in the answer" text input

### ISSUE THREAD

**Issue by Vuenc** [ankidroid/Anki-Android#8708]
**Is your feature request related to a problem? Please describe.**

When I want to type in an answer for a card, I often notice the following problems:

1. By default, the first character I enter is upper-case. Since my vocabulary answers most often start with a lower-case character, I have to manually turn it off each time I type in a word.
2. The keyboard's auto-correct is turned on, so I get a suggestion for the answer word once I start typing it. This sometimes make it too easy to give the correct answer.
3. When I enter accented characters, say 'ó', by long-pressing a key in the top row, say 'o', the keyboard's default suggestion is a number ('9' in this case), and I often accidentally type in the number instead of the accented letter. I know this is not primarily an Anki issue, but see my suggestion below how this might still be improved.

**Describe the solution you'd like**

1. The keyboard should start in lower-case mode when entering the answer field. In my experience, in many languages, the majority of words in the vocabulary start with a lower-case letter.
2. The keyboard's auto-correct suggestions should be disabled in the answer field.
3. About the issue with numbers/accents: it seems to be possible to have the numbers in a separate row above the rest of the keyboard (at least I've seen this in other vocabulary apps). I assume that at least for typing in vocabulary answers, it's much more common to use accented letters than to use numbers, so changing the default keyboard behavior by giving the numbers an extra row might be a sensible option.

**Describe alternatives you've considered**

For the upper-case setting at the start of the word, one could also start in upper-case or lower-case mode depending on if the first character in the answer is upper- or lower-case. Disadvantage: this gives away this piece of information to the answerer (does not seem like a huge problem though).

**Additional context**

For context on the accent vs number issue: I use Anki to study Spanish, and my keyboard setting for this is a Spanish-language Gboard with a German keyboard layout. The behavior depends on the layout: e.g. on my usual German-language Gboard, the character 'ö' has priority over the number '9' when long-pressing the 'o' key, while on the Spanish-language Gboard, the number has priority over the character 'ó'. 

How the keyboard in Anki currently looks:

![2021-04-27_12-33](https://user-images.githubusercontent.com/26114194/116227881-e706b500-a754-11eb-9459-a553ada9d673.png)

How a keyboard without suggestions and with a number row might look:

![2021-04-27_12-32](https://user-images.githubusercontent.com/26114194/116228031-11f10900-a755-11eb-9cef-9ab69f6c2bf1.png)

**Comment by voidplayer** [comment]
It would be even nicer if it could ignore case all together

My problem is the opposite, German nouns are upper case, and my keyboard dont capitalize them automatically

I just learned to ignore the mistakes that dont matter 🤷‍♂️

**Comment by mikehardy** [comment]
I'm really not sure there is a universal solution here without working it out upstream in Anki Desktop.
How do they handle it?

**Comment by Vuenc** [comment]
> I'm really not sure there is a universal solution here without working it out upstream in Anki Desktop.
> How do they handle it?

You mean for the suggestion to make it case-insensitive? Yes, I assume more changes would be needed for that, and I'm also not sure if that's wanted (maybe some people like to have a case-sensitive check)
I hoped that only changing the behavior of the input box would be an easier alternative that wouldn't need upstream changes, since it concerns the Android GUI only.

However voidplayer writes that their keyboard behaves differently, so that's a bit unsettling. I'd hoped that it would only need some attribute of the textbox to be set and that the different keyboards would change their behavior accordingly. But I haven't looked into how this works on Android, maybe someone knows and can shed light on this?

**Comment by voidplayer** [comment]
@Vuenc my keyboard in the type field doesnt make dic suggestions or autocapitalize already. I use dic for 3 languages

It does when im editing a card. Maybe your android keyboard is not able to act accordingly? Im using anysoftkeyboard for more reference

**Comment by Vuenc** [comment]
Huh, weird that different keyboards behave so differently. I use Gboard, and there I get both the auto-capitalization and suggestions. I also just tried it on another phone which has Microsoft SwiftKey, and there I get suggestions, but no auto-capitalization

**Comment by mikehardy** [comment]
We have run into keyboard-specific actions before - that is one of the reasons there will likely not be a universal solution. It's the same with Launcher behavior - on Android we're spoiled for choice vs Apple, but also there are quirks...
