### ISSUE TITLE
Feature : Paste Clipboard Image As PNG 

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#8709]
### **Is your feature request related to a problem? Please describe.**
AnkiDesktop have feature of "Paste Clipboard Image As PNG " in the preference window ,
currently AnkiDroid do support to copy and paste image but not have this preference option in app.

![Capture](https://user-images.githubusercontent.com/52353967/116271252-7041da00-a79d-11eb-9324-eae83f1a6027.PNG)

**Comment by kartikeysaran** [comment]
@Akshay0701 are you working on this?

**Comment by Akshay0701** [comment]
Sure go on 👍

**Comment by kartikeysaran** [comment]
Thanks @Akshay0701 i am working on this
