### ISSUE TITLE
Make preferences easier to understand and navigate

### ISSUE THREAD

**Issue by oakkitten** [ankidroid/Anki-Android#8710]
Some of AnkiDroid preferences are very confusing and require reading the manual in order to understand what they do. I think pereferences should include enough information for the user to at least get a rough picture of what each preference does, and include a link to documentation when it's not feasible to explain everything in detail. The user must not ponder, “What does this setting do?”

Some examples of sources of confusion:

* AnkiDroid. This is the name of the topmost preference screen. This is just the name of the app. This says nothing about the category
* New card position. This implies there's some list of cards and when you create a new card this controls where it is placed. I'm guessing this is absolutely not what this setting is about
* Learn ahead limit. What is this?
* Timebox time limit. What is this?
* App bar buttons. I think AnkiDroid is the only app I've got that calls the toolbar "app bar"
* Show Top Bar. Is this the same as app bar?
* Automatic display answer. I'm not a native English speaker but this doesn't sound like proper English?
* Day theme → Plain. What does it mean to have a “plain” scheme? It's not like “light” scheme is especially flamboyant.
* "Disable Single-Field Edit Mode. Allows 'Cloze Deletion' context menu when in landscape mode". I.. just don't understand any of this
* "Performance → Max number of backups". Why backups affect performance? What does it mean to have 5 backups? What is backed up? How often are backups made? How can the user know which number to put here?

These are a few examples of many. I suggest:

* Increasing the number of primary categories. For example, synchronization settings could have a preference screen of their own. Notification settings should have its own category. About screen can be accessible from the list of preferences as well.
* Divide preferences better. Off the top of your head, can you tell whether you will find "Image zoom" in "Appearance" or "Reviewing"?
* Remove repeating/unnecessary/unhelpful information. This mostly means removing preference summaries. E.g.
  * "AnkiDroid. General settings" → "General settings"
  * "Show remaining. Show remaining card count" → "Show remaining card count"
  * "Keep screen on. Disable screen timeout" → "Keep screen on" (and make sure that it's clear that it's only done while reviewing)
  * "Center align. Center the contents of cards vertically" → "Center card content vertically"
* Use non-persistable helper preferences or explanatory preference screens. For instance, in this YouTube preference screenshot the non-clickable text on the top offers some useful information, and in this Chrome preference screenshot you can see how they used a whole screen to explain a single preference.
   <img width=300 style="float: right" src=https://user-images.githubusercontent.com/1710718/116278504-76748e00-a77e-11eb-9c8f-e0cbd263ee80.png> <img width=300 src=https://user-images.githubusercontent.com/1710718/116278505-77a5bb00-a77e-11eb-9154-249f9a4bcfe2.png>
* When needed—hopefully, very rarely—use "Learn more" links like in the above screenshot that open documentation.
* On/off (checkbox) preferences should be verb phrases. E.g. 
  * "Automatic synchronization" → "Synchronize automatically" (or better yet, "Synchronize automatically when starting or exiting app")
  * "Automatic display answer" → "Display answer automatically" (or better yet, "Display answer automatically after some time")
* Multiple choice preferences, if possible, should form simple sentences. E.g. 
  * "New card position → New card after reviews" → "Show new cards → After reviews"
  * "Default font applicability → Always; When no font specified on flashcards" → "Use default font → Always; When no font specified in the flashcard"
* Use descriptive names. E.g. "Plain" theme → "Grayscale" theme
* Use consistent capitalization. E.g. "Show Top Bar" → "Show top bar"
* Use words instead of magic numbers. E.g. "Timebox time limit → 0 min" → "Timebox → Disabled" (and a helper preference explaining what Timebox is)
* Possibly remove superficial preferences. I'm not sure why "Display synchronization status" is a preference

Some of what I suggest requires that some preference titles should be made multiline. You can find examples of google apps using multiline preference titles where longer phrases are needed, so I hope this is not an issue. This will also make translators' work easier. Some languages have longer words (e.g. German) or wider letters (Russian). When a translator is trying to cram these into limited space it can lead to very poor results.

**Comment by david-allison-1** [comment]
If you were going to break this up into workable, isolated chunks, where would you begin? 

I think we could quickly get 60% of this done in one non-controversial change, but the length of the issue will discourage people from beginning

**Comment by oakkitten** [comment]
(I've never worked on a project with such... notification density, so take this with a huge lump of salt)

VCS wise, I don't see how you could break up the bulk of change into anything useful. But work wise, perhaps it would be useful to separate the work into code change, “mechanical” data transformation and decision making. Maybe:

1. Make a big decision on how the work should proceed. Including deciding:
   * Whether or not trying for single-line titles is preferable
   * Whether or not helper preferences should have limited size
   * Whether to use "Learn more" links or a button in the toolbar or something else
   * This is not quite related, but perhaps decide if a naming scheme should be used for strings (something like `pref__screen_name__group_name__preference_title__summary`)
1. Do some mechanical transformations
   1. If using xml preferences, inline strings
   1. Reformat the xml if needed (semantic word wrapping maybe? xml entities, etc)
   1. Extract preference text into readable format (markdown?), e.g.
      > * [Screen] Account and synchronization
      >   * [Link] AnkiWeb account. {Not logged in, &lt;account name>}
      >   * [Checkbox] Automatically fetch missing media when syncing
1. Do decisions. Change the markdown file as needed. Review, rinse, and repeat. Decide which preference should be changed, moved, removed, or added. Markdow will allow for easily looking at changes, and everyone can weigh in on how this or that preference should look like.

   (I think it'd help to add some preferences. E.g. For Timebox, I would add “Enabled” checkbox and “Time limit”, that is disabled if “Enabled” is off. Or perhaps “Duration”?)
1. Write some code
   1. Add new Preference classes (`HelperPreference`?) & other infrastructure, as needed
   1. Add migrations for changed preferences
1. Put changes into the app. Another mechanical transformation
   1. Put the changes from the markdown file into xml. I'd do a single commit. At this point the “Learn more” things probably will be pointing nowhere, so keep these as comments.
   1. Extract strings

This won't allow doing this in iterations, but does allow separating workflow between people, and the final changes can be made fast enough as to not to be significantly disrupted by changes on main

**Comment by Arthur-Milchior** [comment]
I beg your pardon, but what is "notification density". It seems AnkiDroid is a strange project. Most of the contributors started open source with anki(droid). It is possible that it has a big impact on the way we deal with it, since none of the maintainer has previous experience, and the project was not very active before Mike arrived.

I ENTIRELY agree with David. It's really hard to discuss you proposal right now, too many things, it will lead to unreadable discussion if we answer to everything at once.

What do you mean by "inline strings"? And "mechanical". I have a hard time following what you intend to do in practice

In order to split into smaller chunk, for example:
> Use words instead of magic numbers. E.g. "Timebox time limit → 0 min" → "Timebox → Disabled" (and a helper preference explaining what Timebox is)

I agree with you, you're quite right, it seems a good idea. You can clearly put a small PR or feature request, as you prefer, with this very small scale change, and we can discuss it, accept it, merge it. It will clearly NOT be perfect because this will belong in one big preference menu, but at least it will be progress.

You can do the same thing for a lot of small improvement you suggest. For example, you may be right about app bar. It's the technical name https://material.io/components/app-bars-top#usage but may not be relevant to show. That can clearly be discussed in its own thread. Once we are done with them, it'll be easier to get a bigger picture of the way the preferences menu should be reorganized. 

Thanks a lot for your interest. Really sorry to ask you so much work, but it seems impossible to progress on so many things at once

**Comment by oakkitten** [comment]
> what is "notification density"

It's just that AnkiDroid generates way more GitHub notifications than any other project I'm watching, so I'd rather not make any assumptions as to how it's organized

> What do you mean by "inline strings"?

The opposite of extracting string. This is not necessary, but the resulting commits would make more sense to the reader, if history is of importance.

> And "mechanical"

Such that can be performed by or as if by a script. Something that doesn't involve much thinking.

> I agree with you, you're quite right, it seems a good idea. You can clearly put a small PR or feature request, as you prefer, with this very small scale change, and we can discuss it, accept it, merge it. It will clearly NOT be perfect because this will belong in one big preference menu, but at least it will be progress.

I think going this way would be much more work for everyone, and the end result would be poorer. I think having a single human-readable file would be a great aide. I think someone who's good at English and is already familiar with what individual settings actually do could make the first draft out of it in a few hours. I think discussing changes in such a document would easy to discuss. ¯\\\_(ツ)_/¯

**Comment by oakkitten** [comment]
I also think that AnkiDroid should include the list of used libraries in the about section, as well as the according licenses, where appropriate. It is my understanding that some licenses, including MIT and GPL, mandate that both the shipped application & the source code must include the according licenses. Apache 2 seems to be specifically not requiring this, but only if the library is only referenced by name, such as in the Gradle files. As apks don't come with externally accessible documentation files, I suppose licensing information should be included somewhere in app's UI.

Also, giving credit to library authors is just a nice thing to do.

**Comment by mikehardy** [comment]
Re: including a licenses page where we include the libraries and licenses - that's a great idea, and yes the right thing to do on all counts. Would happily merge a PR that did that, maybe similar to the Changelog could be an "Included Software" link either off help menu or in settings that opened up a WebView and we could have an HTML page there with all the info

**Comment by oakkitten** [comment]
### Streamline Fullscreen mode settings

Currently, these are the three full screen mode options:
1. Off
2. Hide system bars
3. Hide system bars and answer buttons

The top bar (the one with the card count and the timer), if on, in always visible in mode 2, but only visible in the overlay in mode 3, that is when you swipe from the edge of the screen to show system bars. I suppose both users who use buttons and users who use gestures might want to chose either behavior.

Also, you can already disable answer buttons in the Answer button position setting.

I suggest changing the settings as follows,

> * Review in fullscreen
>   * On
>   * Off
> 
> * Show top bar
>   * Always
>   * Only on fullscreen overlay
>   * Don't show
> 
> * Show answer buttons
>   * Always
>   * Only on fullscreen overlay
>   * Don't show
>
> * Position answer buttons [grey out if not showing]
>   * On top
>   * On bottom

Or, if it is ok to not show answer buttons in fullscreen overlay,

> * Review in fullscreen
>   * On
>   * Off
> 
> * Show top bar
>   * On top of reviewer
>   * On fullscreen overlay
>   * Don't show
> 
> * Show answer buttons
>   * On top of reviewer
>   * On bottom of reviewer
>   * Don't show

Also I suggest:
 * Rename top bar to info bar, or review status bar. I think “top bar” is easily confused with toolbar.
 * Do not show answer buttons above the top bar
 * Grey out “Show remaining” if not showing top bar
 * Move ETA from the toolbar to the right of top bar
 * Color top bar using the same color as the reviewer

**Comment by mrudultora** [comment]
@mikehardy 

> Re: including a licenses page where we include the libraries and licenses - that's a great idea, and yes the right thing to do on all counts. Would happily merge a PR that did that, maybe similar to the Changelog could be an "Included Software" link either off help menu or in settings that opened up a WebView and we could have an HTML page there with all the info

A preference could be added below the changelogs, that works in a similar fashion as changelogs. In the HTML page, every library can be added. Also, a brief description can be added below each library mentioning the reason of it's usage. 
I don't think that including licenses would make sense.

**Comment by mrudultora** [comment]
Oh, I didn't knew about this!

**Comment by BrayanDSO** [comment]
I'm closing this not because I don't agree with some of the related issues. My goal is to split those in into objective and actionable issues so it doesn't stand here forever
