### ISSUE TITLE
[Bug] Confusing icons in "Advanced editor" for notes

### ISSUE THREAD

**Issue by Abanoub-Asaad** [ankidroid/Anki-Android#8711]
###### Reproduction Steps

1. Click on the floating action button (+)
2. Add note
3. Click on attach button (📎) in Front or Back
4. Select Advanced editor 
5. Notice the icons in the title bar.

###### Expected Result
There are two mic icons, the first one for Audio recording and the second one for Audio Clip.
The second icon should be something different because it's so confusing.

###### Actual Result
The two icons are the same.

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Additional Information
If you approved the issue, I would like to work on it.

**Comment by david-allison-1** [comment]
Sure! Make sure the icon is available under an appropriate license.

**Comment by Abanoub-Asaad** [comment]
Okay, Thank you.

**Comment by mikehardy** [comment]
someone else just pointed out remixicons which looks good if material.io doesn't have anything

**Comment by Abanoub-Asaad** [comment]
I'll check the two websites and choose the appropriate icon.

**Comment by Abanoub-Asaad** [comment]
Sorry! I've checked the "note_editor.xml" layout, but I couldn't find the advanced editor layout.

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/26295a2efc870979ce3bd224b3e8f0c4bd37a566/AnkiDroid/src/main/res/menu/popupmenu_multimedia_options.xml
