### ISSUE TITLE
Synchronisation issues (Android 11) [Bug]

### ISSUE THREAD

**Issue by Kolwyntjie** [ankidroid/Anki-Android#8712]
###### Reproduction Steps

1. Open AnkiDroid
2. Press the 'Sync' button

###### Expected Result

The sync process will begin and will sync the changes i have made during my last session (Adding cards that I've added, taking away cards ive taken away, etc)

###### Actual Result

Full Sync begins again syncing all 12400 cards as if I have just opened the app for the first time. Then resulting in an error. 

###### Debug info

AnkiDroid Version = 2.14.6

Android Version = 11

ACRA UUID = f27de4ed-adda-4a3e-a589-5d291d5449bd

Scheduler = std2

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there!
I haven't checked 2.14.6 in a long while but at least on current alphas (https://docs.ankidroid.org/#betaTesting) and an Android 11 emulator (my normal development environment, actually) Android 11 has no problems.

I can't reproduce it

**Comment by david-allison-1** [comment]
Are you making changes which require a full sync, or obtaining an error while syncing stating that a full sync is necessary?

**Comment by Kolwyntjie** [comment]
> Are you making changes which require a full sync, or obtaining an error while syncing stating that a full sync is necessary?

No I'm simply doing things like adding a card or two to a Deck, syncing it on my computer which goes fine and just syncs thoes 2 cards, and when I hop onto my phone and sync it forces a full sync of all 12000 cards and the media on them which then takes almost a hour and does this every time no matter what it is that I add or take away or review. And it only happens on my phone, weather o add the card on my PC or phone, my phone always forces a full sync even tho the cards are on my phone, and then that sync ends in an error.

**Comment by david-allison-1** [comment]
Does it show the "full sync" dialog?

If it doesn't, then you're just downloading media which AnkiWeb tells us you're missing. You may be able to "clear media" on the desktop if you have a lot of unused media files

**Comment by Kolwyntjie** [comment]
> Does it show the "full sync" dialog?
> 
> If it doesn't, then you're just downloading media which AnkiWeb tells us you're missing. You may be able to "clear media" on the desktop if you have a lot of unused media files. You can cancel the media sync, as the download is incremental

Not quiet sure what the full sync dialog looks like. But yes that could very well be the issue, how could I fix the issue while still keeping all the media files?

**Comment by david-allison-1** [comment]
> > Does it show the "full sync" dialog?
> > 
> > If it doesn't, then you're just downloading media which AnkiWeb tells us you're missing. You may be able to "clear media" on the desktop if you have a lot of unused media files. You can cancel the media sync, as the download is incremental
> 
> Not quiet sure what the full sync dialog looks like. But yes that could very well be the issue, how could I fix the issue while still keeping all the media files? 

![Screenshot_20210426-001530.png](https://user-images.githubusercontent.com/62114487/116362618-2509e480-a7fa-11eb-83af-88c66c4f0816.png) - full sync dialog

If you have unused media in Anki desktop/AnkiWeb, then surely you want that deleted?

Otherwise, open the ankidroid folder on your phone and check the collection.media folder.

Each time you sync, you should see the number of files increase, syncing will be fast when the number of files matches Anki Desktop, as there's nothing more to sync

**Comment by Kolwyntjie** [comment]
> ![Screenshot_20210426-001530.png](https://user-images.githubusercontent.com/62114487/116362618-2509e480-a7fa-11eb-83af-88c66c4f0816.png) - full sync dialog
> 
> If you have unused media in Anki desktop/AnkiWeb, then surely you want that deleted?
> 
> Otherwise, open the ankidroid folder on your phone and check the collection.media folder.
> 
> Each time you sync, you should see the number of files increase, syncing will be fast when the number of files matches Anki Desktop, as there's nothing more to sync

![Screenshot_20210427-191036_Instagram](https://user-images.githubusercontent.com/83306444/116368805-c48a9f80-a819-11eb-80cf-d9dd1e9f01bc.png)

Ah right it doesn't show me that sync dialog, here is a picture of the error. (I've synced over 8 times at this point and it still gives me the error even after re-installing and so on. The reason I don't want to clear unused media is because I've just added a deck of about 1000 cards with media and I don't want to delete that all when I plan to begin using it..

**Comment by mikehardy** [comment]
This could be some "indigestible" character in a media file name causing a media file error perhaps.

**Comment by Kolwyntjie** [comment]
> This could be some "indigestible" character in a media file name causing a media file error perhaps.

Hmm that may be true, but I don't understand why its specifically not working since I upgraded to Android 11, since it would sync just fine on android 10

**Comment by david-allison-1** [comment]
@Kolwyntjie Could you download a AnkiDroid 2.15 alpha: https://github.com/ankidroid/Anki-Android/releases

* Sync, obtaining the error you posted in the screenshot
* Help - Get Help - Send Troubleshooting Report

**Comment by mikehardy** [comment]
Can reopen if we receive feedback + reproduction
