### ISSUE TITLE
[Bug] Deck Options new cards steps numbers are not displayed correctly

### ISSUE THREAD

**Issue by Suvendu-SM384** [ankidroid/Anki-Android#8732]
###### Reproduction Steps

1.  Open "options"
2. Open "new cards"
3. The number in "Steps (in minutes)" are not displayed correctly

See the attached gif for more information.
![2](https://user-images.githubusercontent.com/83439385/116642980-984e5a80-a9a2-11eb-84d1-1eb7837cf56a.gif)

###### Actual Result
A correct numerical integer, for example "110", instead of "1 10"

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
That's correct. One step of 1, and one step of 10.

Maybe we want to comma-separate it?

**Comment by Akshay0701** [comment]
I will solve this issue in my pr #8787 👍
