### ISSUE TITLE
[UX Proposal] Code Syntax Highlighting for Card Templates

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8739]
**Is your feature request related to a problem? Please describe.**
Users often make syntax errors in their CSS. This is frustrating for them, and also requires support effort from the community

**Describe the solution you'd like**
I would like to see HTML, and CSS code highlighting for the Card Template Editor

**Describe alternatives you've considered**
Maybe CSS Validation? Maybe also show JS if possible.

**Additional context**
Night mode needs to be considered
This shouldn't crash, and shouldn't take too long.

**Comment by ShridharGoel** [comment]
If this is accepted, then I would like to work on it.

**Comment by mikehardy** [comment]
Related #7798 - this would be nice but I'm way more interested in WYSIWYG editing for the actual notes...

**Comment by david-allison-1** [comment]
> Related #7798 - this would be nice but I'm way more interested in WYSIWYG editing for the actual notes...

Agreed: this feels like it'll be an easy win supplied by a library, but much lower impact than the editor

**Comment by Arthur-Milchior** [comment]
Editor may be blocked by gsoc. If someone want to work on this project but can’t do wisiwyg, then it’s a very fine project

**Comment by mikehardy** [comment]
Oh good point, sure then - ideally it's an easy drop-in library

**Comment by ShridharGoel** [comment]
Should I start working on this?

**Comment by david-allison-1** [comment]
> Should I start working on this?

Sure. Do you have a proposed library?

**Comment by ShridharGoel** [comment]
Yes, I have checked and tried out a few libraries.

These two libraries seem good:
1. https://github.com/Badranh/Syntax-View-Android

    It seems to have limited syntax highlighting for CSS.
    It can check for valid parentheses.
    
    Screenshot when used in AnkiDroid:
   
![AnkiDroid syntax library 1](https://user-images.githubusercontent.com/35566748/116782794-d0d85c00-aaa8-11eb-923e-8205d0fe8092.jpeg)

2. https://github.com/ahmadaghazadeh/CodeEditor

    Better syntax highlighting for CSS.
    It supports basic auto-complete.
    Does not support parentheses validation.
    It seems that this does not support proper changing of background colour.
    
    Screenshot when used in AnkiDroid:

![AnkiDroid syntax library 2](https://user-images.githubusercontent.com/35566748/116783024-1184a500-aaaa-11eb-87ca-d3b4bc255342.jpeg)

**Comment by david-allison-1** [comment]
Neither of those libraries seem actively maintained

**Comment by ShridharGoel** [comment]
I couldn't find any actively maintained library related to this functionality.

**Comment by ShridharGoel** [comment]
Found a good library which is maintained as well: https://github.com/massivemadness/Brackeys-IDE.

**Comment by david-allison-1** [comment]
This is a worrying amount of code, looks reasonable, but let's see how much it adds to the APK size.

Main worry would be that the amount of complexity would increase the chance of bugs.

Let's see how much effort it'll be, I'd be happy to give it an experiment

**Comment by mikehardy** [comment]
I'd be surprised if it added too much size TBH - *just* code (without resources, and with R8 shrinking things) is usually not a big deal, especially now that Multidex isn't a problem it's usually not a worry.

That said, turning minify on temporarily in your build.gradle and comparing the APK before and after should be instructive, if size is a concern, that's the data point we need to see
