### ISSUE TITLE
[Feature Request] "Statistics" section - Graph of Answers value vs answer per session

### ISSUE THREAD

**Issue by sankayop** [ankidroid/Anki-Android#8743]
**Is your feature request related to a problem? Please describe.**
No, not related to any malfunction :)
It is more a thought that I had while using the app.
Namely, I have the feeling that, while busy with one study session, my answers are pretty sharp and correct in the beginning and then, they get more false as the time pass. Then, at the end of the session, they are getting more correct since I feel like the end of the tunnel is approaching.
But this is just a feeling...

**Describe the solution you'd like**
I thought it would be neat to have, in the "Statistics" section, just before the "answer buttons" tab, a new tab called "Answer quality".
This tab would present a graph with in the y-ordinate 4 possible values (4, 3, 2, 1 or Easy, Good, Hard, Again) and in the x-coordinate, a question counter for the last session.
For each x (answered question), the answer quality is given in y.
To help, a cumulative bar graphic and/or a trend (curve fitting) line can be added.

Two examples are given below:
example 1:
<img src="https://user-images.githubusercontent.com/23059127/116780494-7bd32080-aa7d-11eb-8b6a-527924e2fac8.png" width=50% height=30%>

example 2:
<img src="https://user-images.githubusercontent.com/23059127/116780499-855c8880-aa7d-11eb-821a-f0fd699e181f.png" width=50% height=30%>

Personally, I prefer example 2.

**Additional context**
I understood from @david-allison-1 that the "statistic section" from Ankidroid is being fully reshaped to conform to ankidesktop (to increase compatibility) and that it is better to propose them directly. I will do so. But because I was already busy with the preparation, I thought it would be better to continue. You can of course close this feature request after reading :)

Have a nice day

ps:
if needed, the python code to produce the plots:
```
import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit

# Functions
def cumulVect(answerVal, val):
  vect = np.zeros_like(answerVal)
  counter = 0
  for id,ii in enumerate(answerVal):
    if ii == val:
      counter += 1
    vect[id] = counter
  return vect

def vectSep(answerVal, val):
  vect = np.zeros_like(answerVal)
  for id,ii in enumerate(answerVal):
    if ii == val:
      vect[id] = val
  return vect

# Main
nbAnswer = 50
ansId = np.arange(nbAnswer) + 1
np.random.seed(1729)
answerVal = np.random.randint(4, size=(nbAnswer)) + 1
# answerVal = np.array([3, 4, 3, 3, 3, 3, 4, 3, 3, 3, 2, 1, 3, 1, 1, 3, 1, 1, 3, 1, 3, 3, 4, 3, 4, 4, 3, 4, 3, 3])

# fitting curve
def func(x, a, b, c, d):
    return a*x**3 + b*x**2 + c*x + d
popt, pcov = curve_fit(func, ansId, answerVal)
fit = func(ansId, *popt)


width = 0.35
again = cumulVect(answerVal, 1) / nbAnswer * 4
hard = cumulVect(answerVal, 2) / nbAnswer * 4
good = cumulVect(answerVal, 3) / nbAnswer * 4
easy = cumulVect(answerVal, 4) / nbAnswer * 4

againSep = vectSep(answerVal, 1)
hardSep = vectSep(answerVal, 2)
goodSep = vectSep(answerVal, 3)
easySep = vectSep(answerVal, 4)

# Plots
fig = plt.figure(figsize=[10,5], dpi=100, tight_layout=True)
ax = fig.add_subplot()

# # Cumulative version
# ax.bar(ansId, again, width, color='r')
# ax.bar(ansId, hard, width,bottom=again, color='#929292')
# ax.bar(ansId, good, width,bottom=again+hard, color='g')
# ax.bar(ansId, easy, width,bottom=again+hard+good, color='b')
# ax.plot(ansId, answerVal, 'o-', color='orange', linewidth = 2, label="Correctness")
# ax.plot(ansId, fit, '--', color='red', linewidth = 5, alpha=0.5, label="Trend")

# Separate version (better)
ax.bar(ansId, againSep, width, color='r')
ax.bar(ansId, hardSep, width, color='#929292')
ax.bar(ansId, goodSep, width, color='g')
ax.bar(ansId, easySep, width, color='b')
ax.plot(ansId, fit, '--', color='red', linewidth = 5, alpha=0.5, label="Trend")

ax.legend()
ax.set_title('Answers quality for the last session ({ans} questions done)'.format(ans=nbAnswer))
ax.set_ylabel('Questions\' answer')
ax.set_xlabel('Questions\' log')
ax.set_xticks(ansId)
ax.set_yticks([1, 2, 3, 4])
ax.set_yticklabels(['AGAIN', 'HARD', 'GOOD', 'EASY'])

plt.savefig('ankidroidStatQLog.png')
plt.show()
```

ps: just for info, suggestion added to Ankidesktop: https://forums.ankiweb.net/t/statistics-section-graph-of-answers-value-vs-answer-per-session/9684

**Comment by mikehardy** [comment]
Yeah - I'll close this but it's a great suggestion and write-up. More specifically than "conform" even I think it's more accurate to say "re-use", by which I mean "in the future, we will directly use the AnkiDesktop statistics code", so if it goes in there we will simply get it automagically, which would be awesome
