### ISSUE TITLE
Add regression test for card browser changing color when card flag changes

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8744]
This is follow on work for issue #8485

It was fixed in #8735 but without a test confirming the fix and making sure it doesn't happen again

This issue tracks creation of a test that verifies the issue before the fix from #8735 and makes sure it is actually fixed

In [a comment on the related PR](https://github.com/ankidroid/Anki-Android/pull/8735#pullrequestreview-649336285):

> Okay, is it worth obtaining logs from @ShridharGoel (or adding more logs if they're insufficient) so we can better understand this in the future?
> 
> Dealing with an unknown regression worries me: there's no reason that we won't reintroduce it at a later date
> 
> We shouldn't close the issue until it's verified to be fixed by @ShridharGoel , but this looks reasonable to me

**Comment by dorrin-sot** [comment]
I would love to work on this test

**Comment by mikehardy** [comment]
Sure! I apologize I don't recall if you have worked through the Activity lifecycle using the robolectric framework before or not, but this one might not be that bad to do, it will certainly be a good way to get acquainted with robolectric if you aren't already

**Comment by dorrin-sot** [comment]
thanks I haven't worked that much on it. just opening a dialog for a test in my first pr
