### ISSUE TITLE
[Feature] Add show answer buttons toggle in settings

### ISSUE THREAD

**Issue by Z233** [ankidroid/Anki-Android#8747]
**Is your feature request related to a problem? Please describe.**
I am coding a card template that redesigns the answer button. I want to hide default answer buttons when keeping the app bar visible, but I didn't find a related option in settings.

**Describe the solution you'd like**
Add show answer buttons toggle in "Settings > Reviewing > Display".

**Comment by mikehardy** [comment]
Hi there! You will want to use the Javascript API to do this I think? You will want to combine full screen mode (to clear out the current Reviewer UI) then add Javascript to implement the UI you like:

https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

I think that should be sufficient? You can examine some samples at the bottom of the page

**Comment by Z233** [comment]
> Hi there! You will want to use the Javascript API to do this I think? You will want to combine full screen mode (to clear out the current Reviewer UI) then add Javascript to implement the UI you like:
> 
> https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API
> 
> I think that should be sufficient? You can examine some samples at the bottom of the page

Thanks for your reply! I have checked this link before. The example in the link is what inspired me to code a custom card layout. But the thing is I don't want the things fullscreen mode does that hide the system status bar and app bar when hiding the answer buttons. Because it has time, card count, undo, and a lot of useful information and actions. I want to use them directly rather than reimplement them in the card template. So I looking for a related option in settings but didn't find anything. I think offering a checkbox or option to let users toggle answer buttons visible is reasonable.

**Comment by mikehardy** [comment]
It may be reasonable but we have a *lot* of fullscreen variations at the moment. This won't be a high priority - once people are implementing card templates with reviewer elements already it's not a big step to do the full UI especially with examples already. I won't close this but I don't see it as a priority personally. It may be possible for you or someone else to implement it but I'm wary of the "full screen mode" preferences proliferation here.

**Comment by Z233** [comment]
> Hi there! You will want to use the Javascript API to do this I think? You will want to combine full screen mode (to clear out the current Reviewer UI) then add Javascript to implement the UI you like:
> 
> https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API
> 
> I think that should be sufficient? You can examine some samples at the bottom of the page

    Got it. Thanks for your patient replies.🤗

**Comment by Z233** [comment]
> It may be reasonable but we have a *lot* of fullscreen variations at the moment. This won't be a high priority - once people are implementing card templates with reviewer elements already it's not a big step to do the full UI especially with examples already. I won't close this but I don't see it as a priority personally. It may be possible for you or someone else to implement it but I'm wary of the "full screen mode" preferences proliferation here. 

Got it. Thanks for your patient replies.🤗
