### ISSUE TITLE
Add User Profile Feature

### ISSUE THREAD

**Issue by CreatorZZY** [ankidroid/Anki-Android#8748]
**Is your feature request related to a problem? Please describe.**
Add User Profile Feature Just like What the feature in Anki of IOS do.

**Describe the solution you'd like**
Emmm, It is useful for me to manage the desk.

**Describe alternatives you've considered**
Change The profile in the Left（or Right） Side drawer.

**Additional context**
Nope.

**Comment by david-allison-1** [comment]
Thanks for the feature request!

I believe this is a duplicate of https://github.com/ankidroid/Anki-Android/issues/2545
