### ISSUE TITLE
[Bug] Card browser becomes empty on switching night mode

### ISSUE THREAD

**Issue by ShridharGoel** [ankidroid/Anki-Android#8754]
###### Reproduction Steps

1. Go to card browser
2. Switch from day mode to night mode or vice-versa.

###### Expected Result

Cards should be shown.

###### Actual Result

Card browser becomes empty.

###### AnkiDroid version

`2.15alpha47`

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Akshay0701** [comment]
Duplicate #8169

**Comment by ShridharGoel** [comment]
@Akshay0701 Thanks for informing this.
