### ISSUE TITLE
Filtered Deck Options: Add "Enable second filter" option

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8761]
Screenshot from Anki Desktop 2.1.34, confirm how this looks on the latest version before implementation

![image](https://user-images.githubusercontent.com/62114487/116902320-e37e9c80-ac32-11eb-9182-45cee8a310cd.png)

**Comment by Arnold2381** [comment]
Can i work on this?

**Comment by david-allison-1** [comment]
Sure! Make sure you add in a reference to the change in the Anki desktop source

**Comment by Arnold2381** [comment]
Ok!!

**Comment by Arnold2381** [comment]
@david-allison-1 If I make changes in `Storage.java`. Will the changes be reflected? Because right now I have changed the structure of JSONArray for this feature and it isn't getting reflected.

**Comment by david-allison-1** [comment]
> @david-allison-1 If I make changes in `Storage.java`. Will the changes be reflected? Because right now I have changed the structure of JSONArray `terms` for this feature and it isn't getting reflected?

I don't think you want to be doing that, take a look at early 2.1 for Anki desktop and see how the feature is implemented.

Main thing would also be a couple of tests to ensure that the functionality isn't changed in 2.16

**Comment by Arnold2381** [comment]
Yea, I already looked at it before.
I think I figured it out. Thank you!! Will continue working.
