### ISSUE TITLE
[Bug] added tag in `TagsDialog` doesn't get sorted in the list correctly

### ISSUE THREAD

**Issue by TarekkMA** [ankidroid/Anki-Android#8764]
###### Reproduction Steps

1. Have a list of tags (preffebly big)
2. Add a new tag "zzzzz" in `TagsDialog`.

###### Expected Result

All checked tags appearing first.

###### Actual Result

All checked tags appearing first except the new "zzzzz" tag

###### Research

This issue will be apparent once #8762 is fixed, this is not a regression bug since the legacy code had this same issue.

The issue is that the new tag is added to the list (as unchecked) then the list is sorted, after that the new tag is checked. 
This will result in the new tag belonging sorted with the unchecked tags since the sorting was done before checking the tag.

**Comment by mikehardy** [comment]
As you note this isn't a regression I'm marking it for 2.16 - it won't block 2.15
