### ISSUE TITLE
[Feature] Add stop button for audio notes

### ISSUE THREAD

**Issue by Abanoub-Asaad** [ankidroid/Anki-Android#8771]
**Is your feature request related to a problem? Please describe.**
When I add audio to notes, I can't stop the audio.

**Describe the solution you'd like**
I suggest creating a stop icon for solving this.

**Additional context**
If you approved the feature, I would like to work on it.

**Comment by david-allison-1** [comment]
What does Anki Desktop do?

**Comment by Abanoub-Asaad** [comment]
Also, there's no stop button on Anki Desktop.

**Comment by Abanoub-Asaad** [comment]
On both the desktop and android app, the audio never stops unless I show the answer.

**Comment by mikehardy** [comment]
A slightly more useful comparison here is AnkiMobile - it has a play/pause button for audio - this specific item is actually duplicate of #6774 - which isn't a bad thing - taking that one up would be great
