### ISSUE TITLE
[UX] Improve Note Editor Buttons

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8779]
**Is your feature request related to a problem? Please describe.**
The note editor "Cards" button does not look like a button. Tags doesn't either, but gets much more use

![image](https://user-images.githubusercontent.com/62114487/117094044-9dbcf380-ad5a-11eb-8d15-b63127544d59.png)

**Describe the solution you'd like**
Restyle the button to add some indicator that it's a button (shadow?)

**Additional context**

I feel the `LinearLayout` -> `TextView` was a hack, and we should extract this to a separate class which performs the appropriate action and allows us more control over the visual aspects

https://github.com/ankidroid/Anki-Android/blob/c1697ad37158b47d4a44c200e7428704af61792b/AnkiDroid/src/main/res/layout/note_editor.xml#L113-L136

**Comment by prateek-singh-3212** [comment]
I would like to work on this issue.

**Comment by Akshay0701** [comment]
<LinearLayout 
           android:layout_width="fill_parent" 
           android:layout_height="wrap_content" 
           android:orientation="vertical" > 
           <LinearLayout 
               android:id="@+id/CardEditorCardsButton" 
               style="?android:attr/buttonStyleSmall" 
               android:layout_width="fill_parent" 
               android:layout_height="wrap_content" 
               android:layout_gravity="center" 
               android:gravity="center" > 

I think we should remove one linear layout if there is no strong reason to keep two layers of linear layout.

**Comment by prateek-singh-3212** [comment]
@david-allison-1 your views on this?

https://user-images.githubusercontent.com/76490368/117353355-a5e97000-aecd-11eb-8bb8-9b6cdd38a672.mp4

**Comment by david-allison-1** [comment]
> @david-allison-1 your views on this? I have used AppCompatButton and layer-filter in background.
> 
> https://user-images.githubusercontent.com/76490368/117353355-a5e97000-aecd-11eb-8bb8-9b6cdd38a672.mp4
> 
> 
> 
> 

Looks much better!

The font looks strange, but I think that's a system choice

Can you make the shadow slightly smaller, and move it to the bottom right?

**Comment by prateek-singh-3212** [comment]
> Can you make the shadow slightly smaller, and move it to the bottom right?

Yes, sure.

**Comment by prateek-singh-3212** [comment]
Here is all the screenshots of light, dark, plain and black mode.
![Screenshot_20210507-134311_AnkiDroid](https://user-images.githubusercontent.com/76490368/117423727-a8d07900-af3e-11eb-9792-5521309fbb53.jpg)
![Screenshot_20210507-141043_AnkiDroid](https://user-images.githubusercontent.com/76490368/117423752-acfc9680-af3e-11eb-93a1-cb787fe16944.jpg)
![Screenshot_20210507-141019_AnkiDroid](https://user-images.githubusercontent.com/76490368/117423757-ae2dc380-af3e-11eb-95a4-77078d9a784a.jpg)
![Screenshot_20210507-140526_AnkiDroid](https://user-images.githubusercontent.com/76490368/117423765-aec65a00-af3e-11eb-8efb-3cf0e3d5dcb2.jpg)

**Comment by david-allison-1** [comment]
Fantastic!
