### ISSUE TITLE
[UX] Card Template Editor - Preview

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#8780]
After a preview, the screen should:

* Maintain the selected tab
* Maintain the cursor position
* Maintain the scroll position of the edit text

**Comment by Akshay0701** [comment]
is this really needed?
if yes then how we could implement this?

**Comment by david-allison-1** [comment]
@Akshay0701 save the values onSaveInstanceState and restore them onRestoreInstanceState

**Comment by Akshay0701** [comment]
Thanks and I will start work on this once my university work finish 👍

**Comment by Akshay0701** [comment]
Okay, so we have a view pager and there might be many card view in there, so we need to save each fragment mEditorViewId and mEditorViewPosition, the solution I think would be is saving a list of editorViewId and editorViewPostion and then restoring it to a particular position of the card, 

your thoughts?

**Comment by david-allison-1** [comment]
> Okay, so we have a view pager and there might be many card view in there, so we need to save each fragment mEditorViewId and mEditorViewPosition, the solution I think would be is saving a list of editorViewId and editorViewPostion and then restoring it to a particular position of the card.
> 
> your thoughts?
>  

Sounds reasonable, I'm not too clued up on the implementation, but my sl aim would be to store:

* Index of the pager
* Scroll position
* Cursor position
