### ISSUE TITLE
[Bug] Cloze cards with embedded HTML in cloze fields not rendered correctly

### ISSUE THREAD

**Issue by lamvankhoat1** [ankidroid/Anki-Android#8784]
###### Reproduction Steps

1. characters like +, :: cannot be displayed in cloze. For example: {{c1::std::cout << x;}}

###### Expected Result
std::cout << x;

###### Actual Result
[cout< (in question)
std (in answer
![Screenshot_20210507100946](https://user-images.githubusercontent.com/83797527/117393798-1c628e00-af1f-11eb-88cc-9cc2a5eab68e.jpg)
![Screenshot_20210507101004](https://user-images.githubusercontent.com/83797527/117393802-1e2c5180-af1f-11eb-83be-81fa410ff9c8.jpg)

)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dorrin-sot** [comment]
Hi can I work on this

**Comment by lamvankhoat1** [comment]
> can I work on this?

Please help me with that 😄

**Comment by lamvankhoat1** [comment]
> @lamvankhoat1 I can't reproduce it. could you post your debug info from `settings -> advanced -> about ankidroid -> copy debug info`?

Actually, this is a display error so I can't copy the debug info

**Comment by dorrin-sot** [comment]
What do you mean? can you not go to settings?
