### ISSUE TITLE
Record button size is bigger than other button

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#8788]
###### Reproduction Steps

1. Open Add Note
2. Open Record Audio

###### Expected Result
All Button should have the same size 

###### Actual Result
Record Button size bigger than other two 

## OutPut
<img src="https://user-images.githubusercontent.com/52353967/117441204-a8da7400-af52-11eb-90f2-22ba0f4c42bd.jpg" width="250" height="500" />

**Comment by vinishhub** [comment]
I would like  to solve this as this mistake is from my side

**Comment by Akshay0701** [comment]
No issue, Go ahead

**Comment by mikehardy** [comment]
Nice spot @Akshay0701 !
