### ISSUE TITLE
[Feature] Web Speech API in Javascript

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#8794]
As a solution to all the functional requirements related to TTS, I would like to propose support for the Web Speech API in JavaScript.

By supporting the Web Speech API, it will be possible to realize the speech behavior of the cloze-only tag, place the speech button in the card, and speak the text multiple times at different speeds using JavaScript on the user side.

This has the advantage of keeping the application side simple by leaving the implementation of overly complex functions related to TTS to the user's JavaScript side.

Below is the sample code.

```html
<p><select id="voice"></select></p>
<p><textarea id="textarea">This is TTS test.</textarea></p>
<p><button id="button1">Speak</button>
  <button id="button2">Stop</button></p>

<script> 
// CC0 http://creativecommons.org/publicdomain/zero/1.0/
if (window.speechSynthesis) {
  let voices = [];
  function setVoices() {
    if (voices.length) return;
    voices = speechSynthesis.getVoices();
    if (!voices.length) return;
    voices
      .filter(v => v.lang.startsWith("en"))
      .forEach(v => {
        let opt = document.createElement("option");
        opt.text = v.name;
        opt.voice = v;
        voice.appendChild(opt);
      });
  }
  speechSynthesis.addEventListener("voiceschanged", setVoices);
  setVoices();
}
button1.addEventListener("click", () => {
  let opt = voice.selectedOptions;
  if (!opt.length) return;
  let u = new SpeechSynthesisUtterance(textarea.value);
  u.voice = opt[0].voice;
  u.lang  = u.voice.lang;
  u.addEventListener("boundary", e => {
    if (e.name != "word") return;
    textarea.focus();
    textarea.setSelectionRange(e.charIndex, e.charIndex + e.charLength);
  });
  u.addEventListener("end", () => textarea.setSelectionRange(0, 0));
  speechSynthesis.speak(u);
});
button2.addEventListener("click", () => {
  if (!window.speechSynthesis) return;
  speechSynthesis.cancel();
});
 </script>
```

I've also prepared a page where you can easily try out the code.
[https://codepen.io/mikunimaru/pen/poevqKq](https://codepen.io/mikunimaru/pen/poevqKq)
The above code is executable in my android browser, so I think android is capable of supporting Web Speech API.

**Comment by infinyte7** [comment]
Have you tried this one https://github.com/ankidroid/Anki-Android/wiki/FAQ#to-use-tts-on-ankidesktop-and-ankidroid
? 
It is working for cloze also.

SpeechSynthesisUtterance is not supported in android webview. So, above code will not work inside AnkiDroid reviewer. May be JAVA implementation will be done to create TTS.
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance

**Comment by mikunimaru** [comment]
> Have you tried this one https://github.com/ankidroid/Anki-Android/wiki/FAQ#to-use-tts-on-ankidesktop-and-ankidroid
> ?
> It is working for cloze also.
> 
> SpeechSynthesisUtterance is not supported in android webview. So, above code will not work inside AnkiDroid reviewer. May be JAVA implementation will be done to create TTS. Also after rust conversion the TTS will be improved in latest release of AnkiDroid.
> https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance

In the current app specification, there is no way to achieve the behavior of speaking only the opened part of the text when cloze is opened.

Is it possible to use Chrome Custum Tab instead of WebView to enable rich JavaScript?
https://developer.chrome.com/docs/android/custom-tabs/overview/

The availability of powerful JavaScript provides great extensibility to AnkiDroid, which has no add-ons.

**Comment by infinyte7** [comment]
> In the current app specification, there is no way to achieve the behavior of speaking only the opened part of the text when cloze is opened.

May be in AnkiDroid 2.15 or 2.16 the TTS will improved greatly even for cloze also.

> Is it possible to use Chrome Custum Tab instead of WebView to enable rich JavaScript?
https://developer.chrome.com/docs/android/custom-tabs/overview/

I don't this so but you can submit PR. 

> The availability of powerful JavaScript provides great extensibility to AnkiDroid, which has no add-ons.

The js addons support will be available for AnkiDroid soon.

**Comment by mikunimaru** [comment]
I've read the commentary and understood that the Web Speech API is difficult to use. 
Then what about an alternative: providing an api that can freely call AnkiDroid's TTS from javascript in the template.

This api provides a lot of custom freedom with TTS functionality.

**Comment by mikunimaru** [comment]
I tried to add TTS API for JS by a simple modification.
https://github.com/mikunimaru/Anki-Android/commit/b04f7cd4415923d8ce7b2e939d717607f738fb0d


https://user-images.githubusercontent.com/43168745/117616402-0b777e00-b1a6-11eb-9e10-6126f3b2e937.mp4

```html
<p><textarea id="textarea">This is TTS test.</textarea></p>
<p><button id="button1">Speak</button>

  <script> 
// CC0 http://creativecommons.org/publicdomain/zero/1.0/
var jsApi = {"version" : "0.0.1", "developer" : "dev@mail.com"};
var apiStatus = AnkiDroidJS.init(JSON.stringify(jsApi));

button1.addEventListener("click", () => {
 const text = document.getElementById("textarea").value
 AnkiDroidJS.speak_experimental(text);
});
 </script>
```

Calling TTS seems to work very well.
Please consider adding a JavaScript api. (Adding an api is too difficult for me because I don't have enough understanding of the code to estimate the changes)

**Comment by infinyte7** [comment]
Also this is old message in discord for this features from @mikehardy.
```
 that TTS stuff looks very interesting! If it works well and I wonder if we can "bend" the built-in / "core" TTS implemented in AnkiDroid to simply emit the necessary HTML/JS using that.
```

**Comment by david-allison-1** [comment]
@mikunimaru FYI: We're in the process of accepting Anki Desktop style TTS.

https://github.com/ankidroid/Anki-Android/blob/253706a403cae606e6db455055a8b44e3b7ed662/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.kt#L27-L37

I believe that this work is compatible with this class, but flagging it up in case we need to make changes before 2.16 goes out.
