### ISSUE TITLE
Adding color picker in Whiteboard and Add notes

### ISSUE THREAD

**Issue by mrudultora** [ankidroid/Anki-Android#8795]
**Is your feature request related to a problem? Please describe.**
There were 2 PRs in previous few days, that were based on this issue. But the PRs were rejected as the libraries used were abandoned.

**Describe the solution you'd like**
Using this [colorpicker library](https://github.com/mrudultora/Colorpicker) to add those features.

**Describe alternatives you've considered**
None

**Additional context**
Its open to views of others. And also, one of those PR is still open so, if the author of that PR (#8575) would like to add this then it would be pretty good. Otherwise, I will take this up.

**Comment by vinishhub** [comment]
I would like to work on this

**Comment by mrudultora** [comment]
@vinishhub Sorry, but I am already working on it.

**Comment by mikehardy** [comment]
Hey @mrudultora I note that #8575 is going stale as is the related issue #7766 - here you mention you are already working on integrating the color picker library, but I don't see a related PR. Are you still working on color picker related items? No emergency of course - if I understand correctly it's exams going on everywhere right?, just looking for status.

**Comment by mrudultora** [comment]
@mikehardy Yes, I am currently busy with my exams. I will try to make a PR soon.

**Comment by mikehardy** [comment]
Great - knowing you've still got an eye on it is fine, I'm a dinosaur now but I do still remember exam time stress. I have no desire to pile on that when they need all your focus. Good luck
