### ISSUE TITLE
[Bug] Custom decks don't show due cards in deck list view

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#8796]
###### Reproduction Steps

1. Create a 'custom deck':
   1. Long press a deck.
   2. Choose 'Custom study'.
   3. Choose 'Limit to particular tags'.
   4. Select a tag and finish.
   5. Go back to the deck list and rename the 'Custom study session' deck to something else so that it is preserved.
   6. Edit its options by unselecting 'Reschedule cards based on my answers in this deck.'.
2. Use it, but use the 'again' / red button for some cards.
3. After the scheduled time (default 10 minutes) open Anki Droid again and go to the deck list.

###### Expected Result

The custom deck should show the number of due cards (the ones where 'again' was chosen). This happens in Anki Desktop and Anki Web, but not in Anki Droid. When I explicitly press the custom deck to go into its details, it does show the correct number of 'again' cards.

This seems to be a regression as it used to work, but I'm not sure when it broke, I haven't used custom decks for some time.

###### Actual Result

The custom deck in deck list doesn't correctly show the 'again' due cards.

###### Debug info

AnkiDroid Version = 2.14.6
Android Version = 11
ACRA UUID = 1a81993f-e029-414a-bf93-61365f783895
Scheduler = std2
Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

![list-no-due](https://user-images.githubusercontent.com/2421362/117541451-2adea180-b014-11eb-8685-c8ecad048032.png)
![details](https://user-images.githubusercontent.com/2421362/117541456-303bec00-b014-11eb-92bf-c0d0e89dada0.png)
<img width="398" alt="desktop" src="https://user-images.githubusercontent.com/2421362/117541349-c4f21a00-b013-11eb-9051-0b7812c51440.png">
<img width="1141" alt="web" src="https://user-images.githubusercontent.com/2421362/117541373-de936180-b013-11eb-8e92-574df3807629.png">

**Comment by mikehardy** [comment]
Is this still reproducible in 2.15?

Separately:

Note for future people: AnkiDroid is migrating statistics and  libanki (which includes the scheduler) to a new style of use where instead of porting the original Python to Java, we are wrapping the Rust library that AnkiDesktop uses now. Resolution of this issue will require understanding the upstream issue in their Rust code (for scheduler/libanki) or upstream code in svelte/CSS, and fixing it there. PRs to AnkiDroid's java implementation of libanki or stats are not the desired fix at the moment unless they are extremely well-understood and targeted at fixing a small specific issue while the transition happens

**Comment by wujek-srujek** [comment]
Yes, reproducible with 2.15.4.

**Comment by wujek-srujek** [comment]
Well, still happens in 2.15.6.

**Comment by dae** [comment]
Closed by #14171.
