### ISSUE TITLE
Document in the wiki

### ISSUE THREAD

**Issue by Coder2002-MSAdithya** [ankidroid/Anki-Android#8809]
The word issues is being spelt as 'issuess'

**Comment by david-allison-1** [comment]
> The word issues is being spelt as 'issuess'

Hi, thanks for the report! Could you link the page for reference.

In future, if it's a typo on the wiki, feel free to be bold and fix it

Best

David

**Comment by Coder2002-MSAdithya** [comment]
<https://github.com/ankidroid/Anki-Android/wiki> is the link to the wiki. I do not know how to edit wikis as I am a newcomer to open source

**Comment by Coder2002-MSAdithya** [comment]
Please acquaint me with the procedure

**Comment by david-allison-1** [comment]
> Please acquaint me with the procedure

You click "Edit" on the page, and fix it. The page that you linked doesn't contain the word "issuess"

**Comment by Coder2002-MSAdithya** [comment]
Fixed typo in the page <https://github.com/ankidroid/Anki-Android/wiki/Development-Guide>

**Comment by Coder2002-MSAdithya** [comment]
Thanks for your help @david-allison-1 .This is my first open source contribution

**Comment by david-allison-1** [comment]
Fantastic, thank you!

I think this can be closed now, let me know if I'm mistaken
