### ISSUE TITLE
[Bug] Can't log in to AnkiWeb

### ISSUE THREAD

**Issue by JavaZauber** [ankidroid/Anki-Android#8811]
###### Reproduction Steps

1. Create AnkiWeb Account. I created an account with mail address ending in `.tech` and password 60 char unicode password
2. AnkiWeb Account successfully created
3. Try to log in using AnkiDroid version 2.14.6 via F-Droid

###### Expected Result

4. should let me log in & sync my decls

###### Actual Result

4. Always get responded `"Invalid email address or password"`. My user/pass was definitely correct because I copy&pasted them from my password manager

###### Debug info
> AnkiDroid Version = 2.14.6
> Android Version = 9
> ACRA UUID = 98534880-f3c4-46f7-b6f8-40ed3f28f551
> Scheduler = std
> Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Item 2 here https://github.com/ankidroid/Anki-Android/wiki/FAQ#sync-is-not-working - try regular mobile browser

**Comment by JavaZauber** [comment]
> Make sure you can log in to your AnkiWeb account directly at https://ankiweb.net/account/login

I can login fine on ankiweb.net

**Comment by JavaZauber** [comment]
I am running Lineage OS without Google Play Services (version `lineage_mata_userdebug 9 PQ3A.190801.002 6764d04004` to bespecific).

**Comment by JavaZauber** [comment]
Yeah this ticket is stale...
I'll try to find the time to compile & debug the app.

**Comment by mikehardy** [comment]
I wonder if this is related to non-ASCII chars in either username or password. I've seen that happen.
