### ISSUE TITLE
[Bug] Specific cards in my collection (using {{#field1}}{{^field2}} nested condition) show as empty in AnkiDroid, but not in Desktop

### ISSUE THREAD

**Issue by Andrej-Adamenko** [ankidroid/Anki-Android#8813]
###### Reproduction Steps

1. Try to review or preview the example card from the attached file in Anki Desktop: [test.zip](https://github.com/ankidroid/Anki-Android/files/6468701/test.zip)
2. The card looks like this: ![image](https://user-images.githubusercontent.com/70955223/118033905-049d6680-b372-11eb-8cac-1b12dfae919b.png)
3. Try to review or preview the card in AnkiDroid. The card looks like this: 
![0-02-05-0d4c1abbcdada545d67f5016591f6749d5a54cb3e02830ae083eb4197066171b_f16f35d9](https://user-images.githubusercontent.com/70955223/118034647-e3894580-b372-11eb-991b-70f0f1687591.jpg)
This screenshot is to identify the card: 
![0-02-05-b14750d6dd2a86ba3bf489b8b7d374d72f0641cb38f105aa90b43bdcb7456426_180ff40](https://user-images.githubusercontent.com/70955223/118034897-2fd48580-b373-11eb-8733-e889339c6eef.jpg)

###### Expected Result
The card in AnkiDroid should look like it does in Anki Desktop

###### Actual Result
The card in AnkiDroid is empty

###### Debug info
AnkiDroid Version = 2.14.6
Android Version = 10
ACRA UUID = 1b392f85-2b0c-4491-b153-fdb7fb7b8d34
Scheduler = std2
Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Andrej-Adamenko** [comment]
The problem was easily reproducible, but I cannot reproduce it anymore

**Comment by mikehardy** [comment]
Currently cannot reproduce - we can reopen if it pops up again
