### ISSUE TITLE
[Bug] 2.15.0Bata Inconsistency of target deck name on note creation screen

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#8825]
###### Reproduction Steps

1. Select a deck
2. Create a new note
3. Although the top deck appears to be selected on the note creation screen, the deck selected on the first deck list screen is actually selected.

###### Expected Result

Matching the notation of the target deck name on the note creation screen with the actual target deck to be created.

###### Actual Result

https://user-images.githubusercontent.com/43168745/118222268-3f121b00-b4ba-11eb-8880-69de4cd4e0db.mp4

###### Debug info
AnkiDroid Version = 2.15.0beta2

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 05b6416d-1bc6-4282-bd44-b8be120255f2

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by VergilWang15** [comment]
It seems to be a display bug, I can work on it if the issue is accepted.

**Comment by mikehardy** [comment]
@VergilWang15 that would be great! Please, and thank you :-)

**Comment by Akshay0701** [comment]
> It seems to be a display bug, I can work on it if the issue is accepted.

Note : this is happening because noteEditor spinner is not showing lastSelectedDeck, now all you have to do is just update lastSelectedDeck In spinner

**Comment by mikehardy** [comment]
2.15.0beta4 (or 2.15.0 if we go live with 2.15 with no more betas) will have this fixed. Thanks!
