### ISSUE TITLE
[Bug] 2.15.0Bata Statistics for another deck are displayed

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#8826]
###### Reproduction Steps

1. Select a deck from the deck list
2. Open the statistics screen

###### Expected Result

The deck name displayed on the statistics screen matches the deck that actually displays the statistics.

###### Actual Result
The deck name displayed on the statistics screen does not match the deck that actually displays the statistics.

https://user-images.githubusercontent.com/43168745/118224616-784c8a00-b4be-11eb-8f71-25090d0a7e67.mp4

###### Debug info
AnkiDroid Version = 2.15.0beta2

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 05b6416d-1bc6-4282-bd44-b8be120255f2

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by VergilWang15** [comment]
Cant reproduce the issue, the .mp4 video is not availble. Can you re-upload it again？

**Comment by mikunimaru** [comment]
> Cant reproduce the issue, the .mp4 video is not availble. Can you re-upload it again？

![output](https://user-images.githubusercontent.com/43168745/118248968-db024d80-b4df-11eb-8449-149e10a6c398.gif)

It may not be playable depending on the environment, so I will repost it as a gif video.

**Comment by prateek-singh-3212** [comment]
@mikunimaru Yaa, It is reproducable. I would like to take this on.

**Comment by mikehardy** [comment]
I think this may need a fix exactly like #8849

**Comment by mikehardy** [comment]
@prateek-singh-3212 you might want to coordinate with @Akshay0701 as I think this is in a batch of similar issues - @Akshay0701 I hate to tag you in on a bunch of issues but @mikunimaru has been doing some great in-depth testing on the deck selection / display parts of the app and it appears there are a few issues with regard to what deck is in use internally and what deck is showing now - can you take a look? With apologies I'm going to just paste this same comment in the ones I think are similar :sweat_smile:

**Comment by Akshay0701** [comment]
@prateek-singh-3212 I really appreciate your willingness to coordinate with me,

**Comment by mikunimaru** [comment]
As far as I confirmed, it seems that # 8826 was solved by the @Akshay0701 pull request.
