### ISSUE TITLE
Putting json in JSON File

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#8845]
I wonder whether there is an easy way to put it into a .json file, that would make this even easier to read. Ideally statically import the file content, otherwise reading it. It's rarely used anyway, so the cost is not really big and it would improve the code clarity.

_Originally posted by @Arthur-Milchior in https://github.com/ankidroid/Anki-Android/pull/8817#r632318057_

**Comment by TarekkMA** [comment]
Multiline string literals would really come in handy in this situation.

**Comment by david-allison-1** [comment]
We now have Kotlin available, which may provide more options
