### ISSUE TITLE
[Bug]2.15.0beta3 new card creation defaults to the first deck, instead of the one you have selected

### ISSUE THREAD

**Issue by makolyte** [ankidroid/Anki-Android#8847]
###### Reproduction Steps

Let's say I have two decks, A and B.

1. I select deck B 
2. I click +, then click add new note
3. It opens the new card form with deck = A
4. I switch it to deck B and add a card
5. It switches back to deck A, requiring me to switch back to B every time 

###### Expected Result
Before this latest update, it would set the deck to whatever you had selected and would stay on that deck as you are adding more cards.

Instead, it keeps switching to the first deck (appears to be selecting the first deck sorted alphabetically)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.15.0beta3

Android Version = 10

Manufacturer = samsung

Model = SM-T510

Hardware = exynos7904

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-T510 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Safari/537.36

ACRA UUID = 9392d581-19cc-4783-be8c-1fc32a1aa855

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment]
Great report - thank you for letting us know! We definitely did a lot of work for deck selection dialogs in this release, but we also do not intend to change how the "current selected deck" feature (where it is kind of sticky and should be used as you describe without reverting back to first-in-a-list) works

**Comment by mikehardy** [comment]
@Akshay0701 I am going to *guess* (If I am wrong please correct me and help find the right person :pray: ) that this is related to the work you did in this area? Never a bunch of forward-progress without at least one unintended consequence ;-) - if you have any time to take a look it would be great. Thank you!

**Comment by Akshay0701** [comment]
Your Right Its is my mistake, I am sorry for that,

@makolyte First of all Thank You for a detailed report and its just a visual problem

 I just forget to put one line in note Editor 😅

**Comment by mikehardy** [comment]
2.15.0beta4 (or 2.15.0 if we go live with 2.15 with no more betas) will have this. Thanks!
