### ISSUE TITLE
AnkiDroid crashes every time I try to open it

### ISSUE THREAD

**Issue by tuhuynhh** [ankidroid/Anki-Android#8848]
https://drive.google.com/file/d/1ghilD5m2JuF_IuJErZd9pmKP7xZfj21d/view?usp=drivesdk

**Comment by mikehardy** [comment]
Hi there @tuhuynhh ! I've requested access to that video.

Have you tried simply uninstalling and reinstalling? Frequently that fixes things: https://github.com/ankidroid/Anki-Android/wiki/FAQ#after-installing-the-latest-version-of-ankidroid-it-starts-crashing

**Comment by tuhuynhh** [comment]
@mikehardy yeah I tried reinstalling a few times, and it still didn't work.

**Comment by mikehardy** [comment]
Is this still happening? We can reopen if this is still happening with 2.15
