### ISSUE TITLE
More info checking media

### ISSUE THREAD

**Issue by javiercl2020** [ankidroid/Anki-Android#8850]
In ankidroid when you check media it only shows how many files are not being used.
But not which ones like in Anki Desktop
Anki desktop tells you exactly what file its not being used
![Screenshot_20210516-120212](https://user-images.githubusercontent.com/73913963/118405836-40b91b80-b63f-11eb-951d-5488c1cc0f52.png)

**Comment by mikehardy** [comment]
Interesting - that could quite large but I suppose we could put a scrollbox in the dialog? Not great UI but I'm not sure how others solve the "present unbounded set of lines in a dialog" issue otherwise

Do you have AnkiMobile ? I'm curious how they handle it on iOS but I don't have it...

**Comment by javiercl2020** [comment]
> Interesting - that could quite large but I suppose we could put a scrollbox in the dialog? Not great UI but I'm not sure how others solve the "present unbounded set of lines in a dialog" issue otherwise
> 
> Do you have AnkiMobile ? I'm curious how they handle it on iOS but I don't have it...

No
I have Ankidroid Android phone

**Comment by dorrin-sot** [comment]
@mikehardy it could be something like this.
![image](https://user-images.githubusercontent.com/59933477/118407049-e300ef80-b68f-11eb-8eed-34ba0005d14a.png)
(Sorry for the bad handwriting😅)

**Comment by iamvs-2002** [comment]
Maybe a horizontal swipe layout(using ViewPager) would look good.

**Comment by mikehardy** [comment]
I think just starting with a scrollbox in there with an alphabetical list would be nice, and prove the concept / get the data going back and forth. Almost no one uses this function, so it's not worth spending a lot of time on IMHO - there are much higher impact areas of the app - I try to focus on what users really use on a daily basis, or crashes

**Comment by dorrin-sot** [comment]
oh ok. If there's no rush and no one else accepts I can work on it after my finals 🥲
