### ISSUE TITLE
[Bug] In the learning history for each day of the week in the statistics screen, all are counted as learning on Sunday.

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#8853]
###### Reproduction Steps

1. Open "weekly" on the statistics screen
2. All data is aggregated on Sunday

###### Expected Result

Data is aggregated on the correct day of the week.

###### Actual Result

![output](https://user-images.githubusercontent.com/43168745/118408642-6e46a900-b6c1-11eb-9540-dd34816b01d1.gif)

###### Debug info
AnkiDroid Version = 2.16alpha00

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 53fcb5bb-27cb-45eb-86a1-052df39ff3f3

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I just checked and it's true for me even if I do it for all decks / lifetime - definitely an issue :scream:

**Comment by dorrin-sot** [comment]
@mikehardy can I work on this? I think the problem is in the sql query string in `Stats::calculateWeeklyBreakdown`

**Comment by mikehardy** [comment]
Sure!

**Comment by dorrin-sot** [comment]
@mikehardy can I ask how I can view and run queries on  the revlog database? I can't find it in the database inspector of android studio

**Comment by david-allison-1** [comment]
> @mikehardy can I ask how I can view and run queries on  the revlog database? I can't find it in the database inspector of android studio

It's under the `AnkiDroid/collection.anki2` file. I'll typically use JetBrains DataGrip to open, browse and query it. It's a SQLite file

**Comment by dorrin-sot** [comment]
@david-allison-1 thanks
