### ISSUE TITLE
[Bug] Cards in the child deck are displayed as cards in the parent deck.

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#8855]
###### Reproduction Steps

1. Select parent deck
2. Open card browser
3. Tap a card in the child deck

###### Expected Result

The deck to which the correct card belongs is displayed

###### Actual Result

It is always displayed as belonging to the parent deck

###### Debug info
AnkiDroid Version = 2.16alpha00

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 53fcb5bb-27cb-45eb-86a1-052df39ff3f3

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
@Akshay0701 I hate to tag you in on a bunch of issues but @mikunimaru has been doing some great in-depth testing on the deck selection / display parts of the app and it appears there are a few issues with regard to what deck is in use internally and what deck is showing now - can you take a look? With apologies I'm going to just paste this same comment in the ones I think are similar :sweat_smile:

**Comment by Akshay0701** [comment]
Sorry, correct me if I am wrong but @mikehardy I don't think it is related to my Spinner work.

**Comment by mikehardy** [comment]
I think you're right on this one. I'm not sure it is a regression either, it would be interesting to see how far back it goes in the releases by checking 2.14 stable and if it works there seeing where in 2.15 it broke

**Comment by mikehardy** [comment]
I think this might be related to the deck spinner actually. I can reproduce it. The spinner is set to the current selected deck now vs the sub-deck.
If I set the card browser to all decks and tap a sub-deck card it does set to the parent deck of the card so it's close but not quite right.

I'm investigating this now

**Comment by mikehardy** [comment]
Got it.
