### ISSUE TITLE
It doesn't keep the deck selection when adding notes via context.

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#8856]
###### Reproduction Steps

1. Add notes from another app via context
2. I have selected the deck where I want to save this note.
3. Add notes from another app again via context

###### Expected Result

The target deck selected earlier is retained

###### Actual Result

The deck selection will be reset so I will have to reselect every time

###### Debug info
AnkiDroid Version = 2.16alpha00

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 53fcb5bb-27cb-45eb-86a1-052df39ff3f3

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
@Akshay0701 I hate to tag you in on a bunch of issues but @mikunimaru has been doing some great in-depth testing on the deck selection / display parts of the app and it appears there are a few issues with regard to what deck is in use internally and what deck is showing now - can you take a look? With apologies I'm going to just paste this same comment in the ones I think are similar :sweat_smile:

**Comment by Akshay0701** [comment]
If I understood your issue then your saying, note-Editor should display lastSelectedDeckId, Am I Right?

In the below video, I tried to create a card via context and it displaying the lastSelectedDeck as expected.
I don't face any issue in this

<img src="https://user-images.githubusercontent.com/52353967/118856389-84887b00-b8f4-11eb-926b-0e9b06ced6b1.gif" width="250" height="500" />

**Comment by mikunimaru** [comment]
@Akshay0701 

After that, if you save the note in bbbb and reopen the context, aaaaaaaa will be the initial position for deck selection again.

I didn't add the [bug] tag to the title because I wasn't sure if this was the intended behavior.
Personally, I think that there are many cases where notes are added to the same deck repeatedly, so I think it is better to keep the deck selected when adding notes via context.

I put this in between the urgent bug reports, but it is less urgent than other reports because it is more like a functional improvement.

**Comment by mikehardy** [comment]
Interesting - going to move this to 2.16 I'm not sure it's a regression really, and requires some user interface thought

**Comment by david-allison-1** [comment]
@mikunimaru When you have time, could you try this on 2.14.6 and report what happens?

**Comment by Akshay0701** [comment]
> Interesting - going to move this to 2.16 I'm not sure it's a regression really, and requires some user interface thought

simple hack Is: allow note editor spinner to save lastSelectedDeckID(as we did in statistics and card browser)

**Comment by mikehardy** [comment]
That would fix it yes, but first it needs thought / decision on the "should we do this" theme

> I didn't add the [bug] tag to the title because I wasn't sure if this was the intended behavior.
> Personally, I think that there are many cases where notes are added to the same deck repeatedly, so I think it is better to keep the deck selected when adding notes via context.

That's the core question.

I'm curious how Desktop handles this? Or AnkiMobile (iOS)?

**Comment by Akshay0701** [comment]
in the case of Desktop: it doesn't save deckID in note editor

**Comment by mikehardy** [comment]
resolved won't fix then, ecosystem compatibility
