### ISSUE TITLE
[Bug] Advanced Statistics does not calculating new cards correctly

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#8857]
###### Reproduction Steps

1. Create a deck
2. Change deck options
3. Open Advanced Statistics

###### Expected Result

Prediction based on changed deck options

###### Actual Result

I feel that the option change is not taken into consideration.
Below is the stats for decks that have never learned cards.

![Screenshot_20210517-153337297 (2)](https://user-images.githubusercontent.com/43168745/118445077-eeecc000-b728-11eb-9d07-d7b55b598f72.jpg)
![Screenshot_20210517-153446870 (1)](https://user-images.githubusercontent.com/43168745/118444594-4cccd800-b728-11eb-9f55-cd3cbbda6f6c.jpg)

###### Guessing the cause
The app may be ignoring some deck option parameters when making predictions.
I feel that the change of Interval modifier is not reflected either.

###### Debug info
AnkiDroid Version = 2.16alpha00

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 53fcb5bb-27cb-45eb-86a1-052df39ff3f3

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
@Akshay0701 I hate to tag you in on a bunch of issues but @mikunimaru has been doing some great in-depth testing on the deck selection / display parts of the app and it appears there are a few issues with regard to what deck is in use internally and what deck is showing now - can you take a look? With apologies I'm going to just paste this same comment in the ones I think are similar :sweat_smile:

**Comment by Akshay0701** [comment]
@mikunimaru you faced this issue because of the visual problem of statistics after setting lastSelectedDeckId.
it's sorted in #8872

**Comment by mikunimaru** [comment]
This issue continues even after applying the pull request above.

Here are the steps to reproduce the bug a little easier.

1. View statistics
2. Switch to the option of 0 new learning schedules
3. View statistics again

Changes in deck options are not reflected in the stats forecast.

**Comment by mikehardy** [comment]
I do not believe this is a regression in 2.15
You must had settings -> advanced -> advanced statistics turned on to even see the new card forecast correctly
Then it is true - the new card forecast is still using what appears to be the defaults even if you restart the app

**Comment by mikehardy** [comment]
Note for future people: AnkiDroid is migrating statistics and  libanki (which includes the scheduler) to a new style of use where instead of porting the original Python to Java, we are wrapping the Rust library that AnkiDesktop uses now. Resolution of this issue will require understanding the upstream issue in their Rust code (for scheduler/libanki) or upstream code in svelte/CSS, and fixing it there. PRs to AnkiDroid's java implementation of libanki or stats are not the desired fix at the moment unless they are extremely well-understood and targeted at fixing a small specific issue while the transition happens
