### ISSUE TITLE
[Bug] When I change the type on the note creation screen, it seems that the target of the deck is also changed arbitrarily, but it is not actually changed.

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#8860]
###### Reproduction Steps

1. Open the note creation screen
2. Select another deck
3. Select another type

###### Expected Result

Only the type changes

###### Actual Result

The deck selection will be restored.
What's more, the display has just returned, but the deck selection has not been restored internally.

###### Debug info
AnkiDroid Version = 2.16alpha00

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 53fcb5bb-27cb-45eb-86a1-052df39ff3f3

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
@Akshay0701 I hate to tag you in on a bunch of issues but @mikunimaru has been doing some great in-depth testing on the deck selection / display parts of the app and it appears there are a few issues with regard to what deck is in use internally and what deck is showing now - can you take a look? With apologies I'm going to just paste this same comment in the ones I think are similar :sweat_smile:

**Comment by Akshay0701** [comment]
I see there are many visual problems in deck selection and note editor, thanks to @mikunimaru,
I am off for a month, I will be more thank full if @mikunimaru or any other contributors could take this issue and work on it, if there any doubt then feel free to ask me.

**Comment by mikunimaru** [comment]
@Akshay0701 
Thanks for the pull request.

I built it and confirmed it.
It looks like this issue has been resolved.
