### ISSUE TITLE
[Bug] When change the language, the main page not change the language.

### ISSUE THREAD

**Issue by lazy-codebear** [ankidroid/Anki-Android#8865]
###### Reproduction Steps

1. open a card
2. change the language of the app, for example change from English to Chinese
3. go back to main page

###### Expected Result
The language of the main page is Chinese.

###### Actual Result
The language of the main page is still English. After refresh the windows, the language is right.

Change the language
![1](https://user-images.githubusercontent.com/71474135/118747752-283e4080-b88d-11eb-9df0-fe2fc30e4322.jpg)

But the language of main page is English
![2](https://user-images.githubusercontent.com/71474135/118747797-42781e80-b88d-11eb-8f33-100afbdd17b4.jpg)

###### Debug info
AnkiDroid Version = 2.14.6

Android Version = 10

ACRA UUID = 8e82ade7-10a6-428e-8faf-f2137cebe615

Scheduler = std

Crash Reports Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by lazy-codebear** [comment]
I will try to solve the issue.

**Comment by mikehardy** [comment]
I'm not sure this is 100% fixable on all versions of Android. You did not include the version of your handset? That is usually the key to whether it works or not without an app restart

There was a *lot* of work in the area to get it right - see:

**Comment by lazy-codebear** [comment]
@mikehardy 
Device: HONOR 20
Android version: 10

The work your mentioned is about the system language and app language. If not choose the system language in the app, changing the language when getting in a card. Then close the card, the language do not change. I think it is a bug.

**Comment by mikehardy** [comment]
@lazy-codebear I'm not sure I understand what the bug is with exact steps to reproduce, can you list it out as numbered steps with the names of the screens you mention, or grab a little video of a reproduction, please? You could certainly be right but there was so much work in the area, I want to see if I can reproduce it exactly as you specify and then how it relates to the previous work

**Comment by lazy-codebear** [comment]
@mikehardy 
It is like this:
https://user-images.githubusercontent.com/71474135/118915334-5d1ac800-b95f-11eb-9e61-09443af88543.mp4


When go back the main page, the language is still English. After open the setting again, the language become right.

**Comment by mrudultora** [comment]
Unable to reproduce this issue on my phone, on the basis of steps mentioned above.

Device details:
Realme Narzo 30 (Android 12).

App Version: 2.15.6 (installed from Google Play Store).
