### ISSUE TITLE
[Feature]  Add ability to sort by sub-deck in card browser

### ISSUE THREAD

**Issue by PANG-hans** [ankidroid/Anki-Android#8869]
**Is your feature request related to a problem? Please describe.**
can not show cards in default sub-decks.

**Describe the solution you'd like**
Add new display order

**Describe alternatives you've considered**
add a default sector in card select if have card

**Additional context**
<img height="400" src = "https://user-images.githubusercontent.com/49405752/118805671-c73c5a00-b8d8-11eb-8fe6-a91e31025f46.jpg">

**Comment by prateek-singh-3212** [comment]
I would like to add this feature.

**Comment by mikehardy** [comment]
Looks like an ecosystem compatibility issue but not in libanki or stats, that usually means "yes!", so, yes! :-)
I personally do not use folder hierarchies much or this sort feature so I would very very carefully check exactly how desktop does it to make sure it's the same, and (to help me, the reviewer-that-wishes-he-had-more-time-but-does-not) explaining the behavior exactly in the PR so I know how to check
