### ISSUE TITLE
[Bug] Audible cards are shown as free space in Card browser

### ISSUE THREAD

**Issue by Abanoub-Asaad** [ankidroid/Anki-Android#8871]
When I open the Card browser, the audible cards are shown as free space.

Why isn't there anything else to refer that there's an audible card here instead of free space?
Also to make a visual difference between if the card is already **empty** or **audible**.

 <img alt="" height="500" src="https://user-images.githubusercontent.com/48657780/118848372-fc43af00-b8ce-11eb-9b96-6784691c50d6.jpeg">

**Comment by Georgezxh** [comment]
Hi! I guess it is because in the cardbrowser, the audible card was replaced by "". So it looks like empty in card browse. I am working on this!

**Comment by Abanoub-Asaad** [comment]
Thank you so much for your initiative
I fear because the issue doesn't get approved yet, it would be better to wait until being approved.

**Comment by david-allison-1** [comment]
WONTFIX: already exists https://github.com/ankidroid/Anki-Android/pull/8903#issuecomment-846589501
