### ISSUE TITLE
[Bug] Crash in TAGs

### ISSUE THREAD

**Issue by Abanoub-Asaad** [ankidroid/Anki-Android#8890]
A lot of functionalities related to TAGs crash.

https://user-images.githubusercontent.com/48657780/119005505-c9adbb00-b98f-11eb-9a78-6e41744bac54.mp4

**Comment by Abanoub-Asaad** [comment]
![Screenshot from 2021-05-20 17-39-57](https://user-images.githubusercontent.com/48657780/119008601-9c164100-b992-11eb-939c-8fa2c20bb45e.png)

**Comment by TarekkMA** [comment]
What is the Android version you are using version?

**Comment by Abanoub-Asaad** [comment]
7

**Comment by Abanoub-Asaad** [comment]
But I have another has Android 10, but I haven't this crash on it
I will try.

**Comment by TarekkMA** [comment]
Make sure you fetch latest master.

**Comment by Abanoub-Asaad** [comment]
Yes
Does this crash happen with you?

**Comment by TarekkMA** [comment]
I'm think you don't have the latest version

do the following in the command line
```bash
$ git checkout master
$ git fetch upstream
$ git merge upstream/master
```

The staktrace indicates that a call to `Collections.sort` is happening but I fixed it in #8808

**Comment by TarekkMA** [comment]
Also there are a tests to make sure that `Collections.sort` is never called

https://github.com/ankidroid/Anki-Android/blob/60476b8331c63f42050d0142342b5c410aaeb11d/AnkiDroid/src/test/java/com/ichi2/anki/dialogs/tags/TagsListTest.java#L254-L265

https://github.com/ankidroid/Anki-Android/blob/60476b8331c63f42050d0142342b5c410aaeb11d/AnkiDroid/src/test/java/com/ichi2/utils/UniqueArrayListTest.java#L92-L106

**Comment by Abanoub-Asaad** [comment]
> I'm think you don't have the latest version
> 
> do the following in the command line
> 
> ```shell
> $ git checkout master
> $ git fetch upstream
> $ git merge upstream/master
> ```
> 
> The staktrace indicates that a call to `Collections.sort` is happening but I fixed it in #8808

I can't make `checkout master` because I'm working on another branch that I've made
But I'll try again, thank you.

**Comment by TarekkMA** [comment]
No problems, when you do please let me know if that issue still exists

**Comment by Abanoub-Asaad** [comment]
Just downloaded the latest version from Google Play "V 2.15.0beta5" and It worked well and there are no issues
Thank you, Tarek. I will close this issue.

**Comment by mikehardy** [comment]
I have these scripts to quickly get my main lines (for repositories that use the old "master" or the new "main" for default branch) or for branches. They are really useful, I keep them in `~/bin` and that's first in my path

```
mike@isabela:~ % more bin/uob
#!/bin/bash
echo "attempting to rebase from origin"
BRANCH=`git status|head -1|cut -d' ' -f3`
echo "branch name detected as: $BRANCH"
git fetch origin
git rebase origin/$BRANCH
mike@isabela:~ % more bin/uom
#!/bin/bash
echo "attempting to rebase from origin"
BRANCH=`git branch -a|grep origin/HEAD|cut -d/ -f4`
echo "origin HEAD branch name detected as: $BRANCH"
git fetch origin
git rebase origin/$BRANCH
mike@isabela:~ % more bin/uub 
#!/bin/bash
echo "attempting to rebase branch from upstream"
BRANCH=`git status|head -1|cut -d' ' -f3`
echo "branch name detected as: $BRANCH"
git fetch upstream
git rebase upstream/$BRANCH
mike@isabela:~ % more bin/uum
#!/bin/bash
echo "attempting to rebase from upstream"
BRANCH=`git branch -a|grep origin/HEAD|cut -d/ -f4`
echo "upstream HEAD branch name detected as: $BRANCH"
git fetch upstream
git rebase upstream/$BRANCH
```

1) no merge, ever :-) - rebase!
2) "uom" is "Update from Origin Main/Master", "uum" is "Update from Upstream Main/Master"
3) "uob" is "Update from Origin Branch (same name as current)", "uum" is "Update from Upstream Branch"

So if I'm working on a branch and there's some other unrelated fix that merged to main branch upstream and I need it (like here), I just `git stash` my current work, `uum`, then `git stash pop` (and resolve conflicts in my local work if I need to, then move on

Cheers :-)

**Comment by TarekkMA** [comment]
very nice, I will use these scripts
