### ISSUE TITLE
Add option to pause a deck (+show/hide paused decks)

### ISSUE THREAD

**Issue by jpggithub** [ankidroid/Anki-Android#8892]
**Is your feature request related to a problem? Please describe.**

When you have many decks, it could be too much to work on.
Sometimes, you prefer to work on some specific decks and don't have time to work on the others during a certain period of time.
If you have many decks, it is quite annoying to look at all our decks when you want to work only on some of them.

In #3303 it is suggested to just delete the decks we have giving up during a certain time.

It can be done but it is not very convenient because:
- even if you don't work seriously on some decks, you want sometimes to look at them or just work on them a little bit or just to look at a specific card
- and you also want to add some new cards even if you don't work on them at the moment

If the decks are saved and deleted from Ankidroid, you can't be done easily.

**Describe the solution you'd like**
A simple "show/hide the deck" and "show all" options could solve these  issues.
Perhaps it could be easily implemented in Ankidroid and the desktop version?

**Comment by mikehardy** [comment]
Hi there! This is an area where we will only do what "upstream" (Anki Desktop) does, so it is better suited for there: forums.ankiweb.net/

I think another possible option is to make a folder called "suspended" and put them in there? Specifically what I mean is that I think you're looking for visually cleaner deck list so it's less guilt/anxiety-inducing, and this should help as the total counts next to suspended won't be attributable to a specific deck so it's easier to gloss over while focusing ?

**Comment by jpggithub** [comment]
Yes, good idea, a "suspended" folder could also be fine.
Is it already possible with the actual Ankidroid? I have never seen this option.

**Comment by mikehardy** [comment]
Well, it would just be via convention - you would create a folder called "Suspended" yourself, then in the decks you wanted to put in there you'd move them by either changing their name from "Whatever" to "Suspended::Whatever" (or perhaps it's possible to do it all graphically at this point - I don't use subfolders much sorry :sweat_smile: ) and that's that. Re-name / move back out when you want to take them up again

**Comment by mikehardy** [comment]
Other thought, you can actually load up one deck in card browser, long-press to enter multi-select, menu option select all, then menu option schedule -> suspend. Then you will have *actually* suspended them all vs just sort of visually hiding them
