### ISSUE TITLE
[Bug] Restoring from an automatic backup shouldn't immediately create a new backup because it causes the oldest to be deleted.

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#8897]
###### Reproduction Steps

1. Find something "not right" in your collection and decide to go through AD's automatic backups
2. Restore from backup
3. AnkiDroid will create a new "backup" as soon as it finishes restoring, and deletes the oldest one
4. Repeat 1-3 atleast 8 more times (unless you've changed the default preference "Max Number of Backups" (under Advanced)
5. Notice that all 8 of your automatic backups are now from today and the thing that was "not right" in your collection has been propogated to all of them

###### Expected Result
Restoring from a backup should not immediately create a new backup. Ideally the AD restore process should follow desktop (as of v. 2.1.43):
1. warn the user they are replacing their current collection with an older backup
2. let them choose a backup
3. confirm with them that `Automatic syncing and backups have been disabled while restoring. To enable them again, choose the profile or restart Anki[droid]`

###### Actual Result
Restoring from a backup immediately creates a new backup, thus deleting the oldest one. This means collection mistakes get spread through the older backups. 

Additionally, it seems that [the backup section of the AD manual](https://docs.ankidroid.org/manual.html#backups) is incorrect when it says "The backup is taken in the background when you first start the app. A backup will only happen if more than 5 hours has elapsed since the last time a backup was created" because I now have 8 backups from May 21, 2021. Even if this 5 hour rule were in place, I don't think restoring should result in a new backup being made: If today I restore from an artitrary backup, say 5/14/21, then AD will create a new backup for thats basically identical except with todays date.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
AnkiDroid Version = 2.15alpha49

Android Version = 7.0

Manufacturer = LGE

Model = LGL84VL

Hardware = sf317

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; LGL84VL Build/NRD90U; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.91 Mobile Safari/537.36

ACRA UUID = 80da83ce-b9bf-4913-9e68-b343866833da

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Oh! I agree with you. Conforming with upstream and no taking a backup on restore seems sensible

**Comment by sudomain** [comment]
An amusing temporary workaround is for users to only restore from the oldest backup. The names will get muddled up, but it'll prevent deletion of the oldest backup since it will become the newest.

**Comment by mikehardy** [comment]
This is a real issue
