### ISSUE TITLE
Split Information about deu card and time in banner

### ISSUE THREAD

**Issue by PANG-hans** [ankidroid/Anki-Android#8905]
**Is your feature request related to a problem? Please describe.**
As shown, the info of due cards is displayed but needed time can not display completely.
I have tested it on different language.
<img height="400" src="https://user-images.githubusercontent.com/49405752/118913574-4de64b00-b95c-11eb-9b09-d33c0f87f244.jpg">

**Describe the solution you'd like**
Enlarge the height of Split it into two lines,
first line show due card,
second line show rest time.

**Describe alternatives you've considered**

**Additional context**

**Comment by mikehardy** [comment]
I wonder if making it prefer the ellipses (`...`) over the text slightly. There will always be space pressure here, but the deck information in the list is the thing to prefer I think, I don't like the idea of growing the height of the top bar

**Comment by PANG-hans** [comment]
I can understand that change the height of top bar may create more conflicts, but i tested it on different lanuage, device and front. it can not performance well in portait. 
one more line make the info more clear and useful.
