### ISSUE TITLE
Remove or hide easy and hard buttons

### ISSUE THREAD

**Issue by javiercl2020** [ankidroid/Anki-Android#8908]
I use anki mainly for language learning.
I read an article saying that the hard button and easy button changes the algorithm.
Is it possible to hide it or remove it?
There is an add on for desktop.
https://web.archive.org/web/20210203165239if_/https://massimmersionapproach.com/table-of-contents/anki/low-key-anki/intro

**Comment by mikehardy** [comment]
Hi there!
No, we only follow core Anki Desktop functionality, sorry.
