### ISSUE TITLE
Please add Icons in options menu on reviewer

### ISSUE THREAD

**Issue by henon** [ankidroid/Anki-Android#8912]
**Problem**
The card menu consists of 11 entries, all without icons. This makes it arduous to use the menu, i.e. to replay audio. You have to read the menu. With icons you could much faster select the needed entry.

**Describe the solution you'd like**
Please add icons to the menu entries, like a play button for "Replay audio" or a pencil icon for "Edit note", etc.

**Comment by mikehardy** [comment]
Did you know, you can change the AppBar buttons in the reviewer, so that the ones you actually use frequently (like, I use replay audio a lot so I wanted that up there as a button) are up there as buttons?

Give that a shot if you can

We can potentially add icons to the menu now - in the past it wasn't so easy because of backwards compatibility with very old Android versions but we have mostly dropped those now and might be able to do this.

**Comment by henon** [comment]
Thanks, that solves my problem. In case anybody else (like me) overlooked this setting and wonders how to configure it:

App drawer > Settings > Reviewing > App bar buttons

Icons in the menu would still be nice though.

**Comment by prateek-singh-3212** [comment]
> We can potentially add icons to the menu now - in the past it wasn't so easy because of backwards compatibility with very old Android versions but we have mostly dropped those now and might be able to do this.

@mikehardy I am intrested in implemeting icons. But can you Please elobrate this? like what do you expect from me to do? Because all the icons and implentaion which we are using now looks good to me.

**Comment by mikehardy** [comment]
@prateek-singh-3212 - open AnkiDroid, select a deck and start reviewing, in the Reviewer open the options menu at top right.

Right now that is nothing but text lines in the dropdown

I believe we already have icons assigned for each of those items we just don't show them in the drop-down menu. I believe this request is to add the icons to the drop-down menu (as opposed to just when they are used in the AppBar as buttons). This may be a valid request for all of the menus, really

**Comment by prateek-singh-3212** [comment]
Okay, now it's clear to me. Good idea, I will work on it but after some time because my laptop hard disk gets corrupted.

**Comment by mikehardy** [comment]
Oh I'm sorry to hear that - that is the worst. For any PR related to hear, no pressure - 2.16 will be some time away yet

**Comment by prateek-singh-3212** [comment]
How is it looking? . Here is the screenshot of light, dark, plain, light mode.
![WhatsApp Image 2021-05-29 at 15 09 23(3)](https://user-images.githubusercontent.com/76490368/120065694-488dac80-c090-11eb-873d-8534873bd525.jpeg)![WhatsApp Image 2021-05-29 at 15 09 23(2)](https://user-images.githubusercontent.com/76490368/120065696-49bed980-c090-11eb-8410-a7092f58dc45.jpeg)
![WhatsApp Image 2021-05-29 at 15 09 23(1)](https://user-images.githubusercontent.com/76490368/120065698-4b889d00-c090-11eb-8198-116803b9e945.jpeg)![WhatsApp Image 2021-05-29 at 15 09 23](https://user-images.githubusercontent.com/76490368/120065872-34967a80-c091-11eb-9e72-bff7ee0aaec8.jpeg)

**Comment by prateek-singh-3212** [comment]
Shall i change the icon of disable white board as they are having same icon?

![WhatsApp Image 2021-05-29 at 15 21 50](https://user-images.githubusercontent.com/76490368/120065954-a4a50080-c091-11eb-82a5-b12ea21f164e.jpeg)

**Comment by david-allison-1** [comment]
> Shall i change the icon of disable white board as they are having same icon?
> 
> ![WhatsApp Image 2021-05-29 at 15 21 50](https://user-images.githubusercontent.com/76490368/120065954-a4a50080-c091-11eb-82a5-b12ea21f164e.jpeg)

Looks great!

Yeah, make them different - and Deck Options should have a "settings" icon of some description
