### ISSUE TITLE
[Bug] Reviewer much slower in AnkiDroid 2.15

### ISSUE THREAD

**Issue by Zwergkrug** [ankidroid/Anki-Android#8927]
###### Reproduction Steps
1. Open any deck in AnkiDroid for review
2. click show answer
3. choose AGAIN/HARD/GOOD or EASY

###### Expected Result

answer card is shown almost instantly,
next card is shown almost instantly

###### Actual Result

300ms - 1s delay before card is shown
Sometimes card has system font for a second, then changes to correct font.

###### Debug info

AnkiDroid Version = 2.15.0

Android Version = 6.0

Manufacturer = HUAWEI

Model = H60-L04

Hardware = hi3630

Webview User Agent = Mozilla/5.0 (Linux; Android 6.0; H60-L04 Build/HDH60-L04; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 2eaac15d-15ff-4947-a390-e7f405b37f9b

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Additional info
- I posted my problem on Reddit and was recommended to open this issue
- I installed a parallel version of 2.14.6 and it works fine
- All of my cards contain kanji. An example note is attached below
[Example_Note.zip](https://github.com/ankidroid/Anki-Android/files/6538955/Example_Note.zip)

Thank you very much for your support! I am very grateful.

**Comment by david-allison-1** [comment]
Thanks for the report! @Zwergkrug

I've tried this, and the card appears instantly for me on both AnkiDroid 2.15 and AnkiDroid 2.14.6

Can you confirm that this card exhibits the problem and I'll investigate further

All the best,

David

**Comment by Zwergkrug** [comment]
Hi David,

the card exhibits the problem.
I will investigate if the problem might be my phone in a few hours after work and revisit this thread.

**Comment by david-allison-1** [comment]
Given:

> I installed a parallel version of 2.14.6 and it works fine

There's likely something that we can do.

I don't see anything immediately. The most helpful thing that you could do would be to see which alpha of 2.15 caused the slowdown. You can do this by installing `Parallel.A/B` from our `releases` page and seeing if something is fast or slow.

My main worry is that it would be:

* https://github.com/ankidroid/Anki-Android/releases/tag/v2.15alpha24 - slow
* https://github.com/ankidroid/Anki-Android/releases/tag/v2.15alpha23 - fast

Could you check these?

**Comment by david-allison-1** [comment]
@Zwergkrug I don't think this will be the issue, but could you also check `Settings - Advanced - Disable card hardware renderer` and ensure that the checkbox is **not** checked.

**Comment by Zwergkrug** [comment]
> @Zwergkrug I don't think this will be the issue, but could you also check `Settings - Advanced - Disable card hardware renderer` and ensure that the checkbox is **not** checked.

The checkbox is not checked.

I tested v2.15alpha24 and v2.15alpha23. Both lagexactly the same as 2.15. 
2.14.6 works smoothly.
The lag changes from 300ms to sometimes 1s. I can not find a cause for those changes in lag. I'm starting to think that it is a performance problem of my phone. If that is the case I'm deeply sorry to cause you trouble. Maybe suspend my issue until someone else reports the same problem.

**Comment by david-allison-1** [comment]
I believe that this is something that we can fix. 

If you find the alpha version that causes the lag, we can work out the change that causes it, and look into it further.

**Comment by Zwergkrug** [comment]
I installed AnkiDroid-2.15alpha8.parallel.A.apk (and other previous versions) and those work as smooth as 2.14.6
The lag starts with AnkiDroid-2.15alpha9.parallel.A.apk 

I hope that makes sense.

**Comment by david-allison-1** [comment]
You're a fantastic person. Thank you!

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/compare/v2.15alpha8...v2.15alpha9 - I'll call the MathJax 3 code as the culprit

**Comment by david-allison-1** [comment]
@hgiesel Do you feel it's possible to detect MathJax usage, and only load the MathJax JS code if MathJax exists?

**Comment by hgiesel** [comment]
@david-allison-1 

> only load the MathJax JS code if MathJax exists?
I thought that was already happening on Ankidroid?

I actually suspect it's jQuery. MathJax 3 is usually faster than MathJax 2, so if anything that should make it faster.

**Comment by david-allison-1** [comment]
Nope - JS is loaded, even if there's no MathJax content.

https://github.com/ankidroid/Anki-Android/blob/df129fa012d3223529b9724ed49e19b3c4043b7f/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L2318

https://github.com/ankidroid/Anki-Android/blob/1337f3ea21cef25f549a89a81dcbaf151dde184d/AnkiDroid/src/main/assets/card_template.html#L12-L15

Was JQuery also changed in that commit? I don't see any references, but I have a limited understanding of MathJax

**Comment by hgiesel** [comment]
Yes, jQuery does not seem to be included in the diff, but it was also added around that time frame. jQuery was freshly added, while MathJax was updated to a newer version, that's why I'm a bit puzzled how MathJax could make it slower.

To dynamically exclude Mathjax from loading, `card_template.html` would have to be generated dynamically as well.

**Comment by david-allison-1** [comment]
Thanks, on it.

**Comment by Zwergkrug** [comment]
Hello,
I installed AnkiDroid-2.15.1.parallel.A.apk and it works well.

Thank you very much for the quick response!
