### ISSUE TITLE
Issue with Pleco Chinese Dictionary

### ISSUE THREAD

**Issue by Patback** [ankidroid/Anki-Android#8928]
The newest version of Anki is not accurately syncing with Pleco Chinese Dictionary. Whenever I add a new card from Pleco to Anki, it adds the card but not reports that the card is added. This causes Pleco to not mark the card as currently in the deck and leads to confusion in the user continuously adding the same card over and over again

**Comment by david-allison-1** [comment]
Thanks for the report.

Is this an issue with AnkiDroid 2.15, or with Pleco?

Sadly, the AnkiDroid API which Pleco uses only works on the stable version of AnkiDroid, so you'll need to uninstall 2.15 to test.

This wipes AnkiDroid specific settings such as gestures, but not data.

You can install 2.14.6 from: https://github.com/ankidroid/Anki-Android/releases/download/v2.14.6/AnkiDroid-2.14.6-universal.apk

**Comment by mikehardy** [comment]
Is there a contact with the Pleco developers or an issue report filed with them? If you could connect them here perhaps we could collaborate and fix it more quickly?
