### ISSUE TITLE
If current deck is pointing to an invalid deck set it to default

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8930]
> make sure current isn't null before returning it, if it is null, set deck conf current deck to default deck then return that. Sound right Damien?

It could be null/missing, or it could point to an id that doesn't exist - both cases need to be handled

_Originally posted by @dae in https://github.com/ankidroid/Anki-Android/issues/8894#issuecomment-847547351_

Note that a partial fix was already made - for the null case:

https://github.com/ankidroid/Anki-Android/commit/ef5f7badc5c8b7381f66a1ff4dd5e41f6fa539d6#diff-e576625ef3cb53556ff135a9fc296d94cbb848c62f59d4f065d1595d948310bcR1079-R1081

But it is not handling the situation where it is pointing to a deck that might be missing

**Comment by dorrin-sot** [comment]
@mikehardy I tried a couple of ways of selecting a deck and deleting it and going to a page that uses the current deck, but everytime it gets properly set to Default deck. Is there a specific way to reproduce this?

**Comment by mikehardy** [comment]
You won't be able to test this with the interface - it resets current deck if you delete current deck.
I think you need to close the app, then directly edit (read as: mess up) the database by setting the current deck pointer to something that does not exist. Then open the app and try a feature that uses current deck to make sure it handles the bad current deck pointer
