### ISSUE TITLE
[Bug] Investigate ContentResolver DISPLAY_NAME failures when pasting images

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8937]
###### Reproduction Steps

1. Start AnkiDroid on Android 11 (a version we have crash reports for on this issue)
2. Attempt to paste an image into a field (note: image source that will trigger this is unknown!)
3. Watch `adb logcat`

###### Expected Result

Successful paste with pasted image name *based on the originating filename* and no log noise.

###### Actual Result

Under some circumstances you will see a SQLiteException in the logs indicating the `_display_name` column was not present in the table queried for name?

See #7748 for stack trace and previous details.

#7754 was an initial patch for this and stopped the crash
#8933 is a second attempt, allowing paste to continue

But we still have no understanding of *why* the column is missing, it feels like we're doing something very wrong here / are missing an opportunity for a real fix.

Inspecting AOSP source code to determine what is really going on in the ContentResolver would help, or if we can reproduce it, perhaps determining what ContentResolver sources trigger this, if not all of them?

###### Debug info

Definitely occurs on Android 11. Definitely occurs with 2.15.0 release tag.

###### Research

I was unable to find anything on stackoverflow or the wider internet about this exact issue.

**Comment by david-allison-1** [comment]
@mikehardy Is this fixed by https://github.com/ankidroid/Anki-Android/pull/9025 ?

**Comment by mikehardy** [comment]
Unknown
