### ISSUE TITLE
[Bug] Crash 2.15.0 - "flds" is possibly null on Model?

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8940]
###### Reproduction Steps

1. Load some sort of corrupted collection (I imagine), where there is a note that has a card template / model with no fields
2. Attempt to get a card in the Reviewer that is associated with that note type / broken model

###### Expected Result

A dialog saying your collection is corrupt, and in the database corruption fixes we should repair note types with no fields so that they have valid defaults?

Connected with this - an investigation upstream to see if + and how they handle corrupt models

###### Actual Result

```

Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.ichi2.utils.JSONArray com.ichi2.utils.JSONObject.getJSONArray(java.lang.String)' on a null object reference
at com.ichi2.libanki.Models.fieldMap(Models.java:1)
at com.ichi2.libanki.Note.load(Note.java:14)
at com.ichi2.libanki.Note.<init>(Note.java:4)
at com.ichi2.libanki.Collection.getNote(Collection.java:1)
at com.ichi2.libanki.Card.note(Card.java:3)
at com.ichi2.libanki.Card._getQA(Card.java:4)
at com.ichi2.libanki.Card._getQA(Card.java:2)
at com.ichi2.async.CollectionTask$GetCard.task(CollectionTask.java:5)
at com.ichi2.async.CollectionTask$GetCard.task(CollectionTask.java:1)
at com.ichi2.async.CollectionTask.actualDoInBackground(CollectionTask.java:14)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:2)
at com.ichi2.async.CollectionTask.doInBackground(CollectionTask.java:1)
```

###### Debug info

Seen on ACRA from release tag v.2.15.0

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dorrin-sot** [comment]
Is there any way to reproduce this other than by messing with the database files directly? The problem seems to occur by deleting a model, deleting all its fields or setting the modelId of a note to an id that doesn't exist though none of these can happen through the ui

**Comment by mikehardy** [comment]
Probably not - we are down to the types of crashes that are so rare they are basically edge cases of bad add-ons from desktop doing weird things to the database or similar. There may not be much more to do in some of these cases then check for expected data, and if you see unexpected data pop up the "your database is corrupt, you need to run check database" dialog. But not crashing and at least offering the info that there is something awfully wrong, and here is maybe how to fix it is useful still

**Comment by dorrin-sot** [comment]
Oh, that's a relief. I was afraid I had to add fixing corruption myself😅. I'll try to add it tonight, if not tomorrow

**Comment by dorrin-sot** [comment]
@mikehardy How do I get the last activity object opened from inside the `Models` class?

**Comment by mikehardy** [comment]
I'm not sure it matters from the context of handling corrupt data? I'm not sure what you're trying to do so can't say really. If you need to post or pop a dialog there are UI utils methods that can do that statically - those probably use some other statics based off AnkiAndroidApp that do it

**Comment by dorrin-sot** [comment]
I was trying to open the dialog from `Models::fieldMaps` so I needed to use the last activity for opening the dialog and also to go back to DeckPicker and do a check database. Though I'm leaning toward launching it from each activity individually
