### ISSUE TITLE
[Bug] Review limits on nested child decks no longer behaving the same as AnkiDesktop

### ISSUE THREAD

**Issue by LordZounds** [ankidroid/Anki-Android#8942]
###### Reproduction Steps

1. Create Deck 1 with unlimited reviews.
2. Create Deck 2, limit its reviews to zero, and make it a child of Deck 1.
3. Create Deck 3 with unlimited reviews, and make it a child of Deck 2. This deck should have cards that limits aside, would otherwise be due.

###### Expected Result

On AnkiDesktop, and on AnkiDroid prior to the 2.15 update as far as I can tell, the result would be as follows:

![AnkiDesktop](https://user-images.githubusercontent.com/22622172/119542548-4ad0cd80-bd55-11eb-9653-698db3bb6c1e.png)

Setting max reviews to 0 on the "Disabled" deck results in the reviews in the child decks being suppressed, and the views are not accessible from the parent deck either.

###### Actual Result

On AnkiDroid 2.15, the result is as follows:

![AnkiDroid](https://user-images.githubusercontent.com/22622172/119543259-13aeec00-bd56-11eb-8bca-034f483bbcb2.png)

The "Disabled" deck's review limit only affects the deck itself, both its parent and child decks are unaffected.

###### Debug info

AnkiDroid Version = 2.15.0

Android Version = 11

Manufacturer = Google

Model = Pixel 2 XL

Hardware = taimen

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 2 XL Build/RP1A.201005.004.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 1a2404fe-23f8-4454-9868-214ef4873c33

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, we're about to release 2.15.1 which should hopefully fix this. Please let us know if this still occurs after 2.15.1 is out.

Ref: #8926

**Comment by ChrisMonta** [comment]
I can confirm that my update to 2.15.0 introduced this bug, review limits no longer propagates to parent decks. Looking forward to the fix in 2.15.1

**Comment by ChrisMonta** [comment]
I just forced update to 2.15.1 and every looks back in order

**Comment by mikehardy** [comment]
Really happy to hear this and kudos to David for nailing this one so incredibly quickly! Sorry about the hassle and thanks for bearing with us

**Comment by LordZounds** [comment]
Yes, I have updated 2.15.1 and the issue is fixed for me as well. Thank you!
