### ISSUE TITLE
[Bug] {{FrontSide}} is treated as a field if used on the question side of a card template

### ISSUE THREAD

**Issue by tomkahn** [ankidroid/Anki-Android#8951]
###### Reproduction Steps

Add {{FrontSide}} to the questions side of any card template like so: https://www.dropbox.com/s/pz74fr93anelrk9/2021-05-25_Ankidroid_Bug.png?dl=0

###### Expected Result

{{FrontSide}} is treated as an empty string on the question side of a card. This is how Desktop-Anki does it (see screenshot above on the right).

###### Actual Result

AnkiDroid complains that there is no field called {{FrontSide}} and doesn't show the question side at all. https://www.dropbox.com/s/9oiiwef99gyhpt3/Fehlermeldung_AnkiDroid%20%28002%29.jpg?dl=0

###### Debug info
AnkiDroid 2.15.0

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have searched for similar existing issues here and on the user forum
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, we've just put out 2.15.1, could you confirm it's still an issue there, and we'll get on it. Thanks!

**Comment by tomkahn** [comment]
Yep, just tried it. Same thing on 2.15.1.

**Comment by dae** [comment]
I wonder if this actually needs fixing? FrontSide is nonsensical on the front side of the card. Is this your own template, or did you get it from a popular shared deck?

**Comment by tomkahn** [comment]
Yeah, I thought about that as well. I think there is one valid usage: By checking if "{{FrontSide}}" is equal to an empty string you can determine in JavaScript if you are currently displaying the front side or the back of the card. I used this to make sure I don't run certain formatting scripts twice. That would otherwise happen if you use {{FrontSide}} on the back of the card.

The card is from one of my own note types which are also public and used by a few thousand people.

**Comment by mikehardy** [comment]
I was under the impression card body in the WebView would have front and back specific CSS selectors allowing fool-proof detection that way? Even in the Javascript API (https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API) there is no function to detect them - but it seems useful - which makes me think there must be an easier way (CSS selectors, my hunch)

**Comment by tomkahn** [comment]
Hi Mike, I don't know. Do these CSS selectors work on all Anki platforms and can they be accessed via JavaScript? The scripts I run heavily change the HTML-content of the card. For example they link any laws mentioned to their specific texts (i.e. § 433 I BGB => https://dejure.org/gesetze/BGB/433#Abs1 ), so it's not just a matter of styling.

I'd also be happy to look through the code myself to get it to work as before. Unless you don't want that anymore, in which case it would be great to have an alternative.

**Comment by mikehardy** [comment]
I looked for you - we rely on these - I believe they are cross platform?

https://github.com/ankidroid/Anki-Android/blob/f4dd4958d905591746f7aadd2e4511433c77ab7e/AnkiDroid/src/main/java/com/ichi2/anki/cardviewer/CardAppearance.java#L37-L41

**Comment by tomkahn** [comment]
Thank you for your efforts, Mike! But I meant looking for a fix such that AnkiDroid treats {{FrontSide}} as an empty string again (when used on the front side of a card). I did so just now and I think it could be fixed by adding one additional line:

`fields.put("FrontSide", "");`

after [line 1120](https://github.com/ankidroid/Anki-Android/blob/dff77283952367d927d61f6f61363aedca28bcc0/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1120) in Collection.java. (Reasoning: [Line 1125](https://github.com/ankidroid/Anki-Android/blob/dff77283952367d927d61f6f61363aedca28bcc0/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1125) is the corresponding code for adding {{FrontSide}} as a field on the backside of a card.)

What do you think?

**Comment by david-allison-1** [comment]
> Thank you for your efforts, Mike! But I meant looking for a fix such that AnkiDroid treats {{FrontSide}} as an empty string again (when used on the front side of a card). I did so just now and I think it could be fixed by adding one additional line:
> 
> `fields.put("FrontSide", "");`
> 
> after [line 1120](https://github.com/ankidroid/Anki-Android/blob/dff77283952367d927d61f6f61363aedca28bcc0/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1120) in Collection.java. (Reasoning: [Line 1125](https://github.com/ankidroid/Anki-Android/blob/dff77283952367d927d61f6f61363aedca28bcc0/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1125) is the corresponding code for adding {{FrontSide}} as a field on the backside of a card.)
> 
> What do you think?

Just bisecting to understand the cause of the issue - my fix is the same, I'll get it into the codebase later on today once I understand:

* What Anki Desktop does
* Which change caused this

**Comment by david-allison-1** [comment]
```
7149efeb7986e393eabd6f2db855707002fe388e is the first bad commit
commit 7149efeb7986e393eabd6f2db855707002fe388e
Author: [redacted]
Date:   Sat Dec 26 12:35:08 2020 +0100

    Porting card generation rules from 2.1.28

    The main difference is that the rule: "A card is generated if and only if a field content is shown" is actually
    respected. The rules are not encoded in "req" anymore but are actually checked

    Smaller differences:
    * It is assumed that field does not contains :, }}, and does not start with #, ^ nor /. This assumptions is ensured
      by anki's backend. If for some reason this assumption is not satisfied, the error message may differ than the one
      shown previously.
    * Similarly, if a template rule is not satisfied, (e.g. a conditional is not closed, or if it's closed but was never
      opened), the error message may differ.
    * The computation time is linear in the size of the template. It used to be a multiple of the size of the template and
      its depth (i.e. number of imbricated conditionals)

    I made two differences over rust code:
    * I memoize the result of compiling a template into a tree, so that it does not need to be done multiple time
    * I added ParserNodes as a kind of ParserNode, to factorize the part of the code looping over nodes

    Of course, as it's java and not rust, I used inheritance instead of enum for structured data.
```

https://github.com/ankidroid/Anki-Android/commit/08217dac2e11df83321ae00271d3fb03bbb3e089 https://github.com/ankidroid/Anki-Android/pull/7980

**Comment by tomkahn** [comment]
On behalf of all law students studying for their finals: Thank you very much for your fast response! I just donated $100 to your open collective page to show my appreciation.

**Comment by david-allison-1** [comment]
Thanks!!!!!!!!!! 💝💝

Just to note; you can download 2.14.6 Parallel.A from here while the fix is pending release
 https://github.com/ankidroid/Anki-Android/releases/tag/v2.14.6

Thank you again,

David
