### ISSUE TITLE
More than 6 profiles?

### ISSUE THREAD

**Issue by amandatxt** [ankidroid/Anki-Android#8954]
Until now, I'm using two devices so I can get the desired number of profile. Is there a way to quickly add more than the extra 5 profiles?

I remember there was a way to unpack and pack the apk back again with some subtle changes and I once did this but can't remember how.

**Comment by david-allison-1** [comment]
Hi, our parallel publishing scripts are commented:

* https://github.com/ankidroid/Anki-Android/blob/master/tools/parallel-package-name.sh
* https://github.com/ankidroid/Anki-Android/blob/master/tools/parallel-package-release.sh

How many profiles do you need? We can trivially increase the number for 2.15.2, which should be out soon, at least until we sort out native profile support

**Comment by amandatxt** [comment]
Thanks for replying so fast!! I need 12 profiles and I'm not sure I'm good enough to make use of these files you linked, unfortunately

**Comment by david-allison-1** [comment]
> Thanks for replying so fast!! I need 12 profiles and I'm not sure I'm good enough to make use of these files you linked, unfortunately

No worries! I've added a fix in: https://github.com/ankidroid/Anki-Android/pull/8955

There's the potential that this change won't be accepted (makes releasing the app a fair bit slower) 

If it's not, let me know and I'll see what I can do with regards to documentation

**Comment by david-allison-1** [comment]
Taking a different approach: https://github.com/ankidroid/Anki-Android/pull/8955#issuecomment-848362188

**Comment by amandatxt** [comment]
Unfortunately, I'm not really sure on how to proceed from here. 
I guess I will keep using two devices until Ankidroid comes with a profile thing built-in.
Unless you can further help me, I would like to thank you for at least hearing my "problem".
Thank you very much

**Comment by mikehardy** [comment]
Nothing to do as of yet @amandatxt but what we're hoping for is that in the future if you really need a *lot* of extra profiles, you can fork ankidroid on github (free, and just a clck near the top of the main page) then in your fork you can go to the "Actions" tab, select the "Publish" action, give it the number of profiles you want, and then when it's done they will all be there for you to download

And you'll be able to do that any time, and we'll have it documented.

That's likely a week or three away, whereas multiple profile support is something we do really want but is not on our roadmap at the moment based on what developers are telling us they want to work on, so it has no definite ETA
