### ISSUE TITLE
After recent update, NullReference occurs when using "send to AnkiDroid" feature from other app 

### ISSUE THREAD

**Issue by codywahl** [ankidroid/Anki-Android#8956]
After the recent AnkiDroid update, when sending a word into Anki via another app (in my case, Takoboto) a null reference error occurs.

![Screenshot_20210526-110402_Japanese Dictionary Takoboto](https://user-images.githubusercontent.com/6902227/119592647-d741c580-be13-11eb-9d5b-98d0ac47a7df.jpg)

**Comment by codywahl** [comment]
Resolved in 2.15.1. Closing issue.

**Comment by mikehardy** [comment]
What a relief! And another round of applause to David for nailing this one incredibly quickly along with a separate scheduler issue. The way we work with the underlying collection is completely different in 2.15 and hopefully these are the last little rough edges to smooth out as we make this transition
