### ISSUE TITLE
[Bug] 2.15: Broken cursor returned from AnkiDroid Instant Add API

### ISSUE THREAD

**Issue by hanpingchinese** [ankidroid/Anki-Android#8957]
###### Reproduction Steps

```
val NOTE_PROJECTION = arrayOf(FlashCardsContract.Note._ID, FlashCardsContract.Note.FLDS, FlashCardsContract.Note.TAGS)
resolver.query(FlashCardsContract.Note.CONTENT_URI_V2, NOTE_PROJECTION, "mid=1622000288972 and csum in (3274722590)", null, null)

```
###### Expected Result

cursor.moveToNext() returns true

###### Actual Result

cursor.moveToNext() returns false

This problem started appearing (for all my users) yesterday when they updated AnkiDroid to 2.15. I've looked into the issue, and I'm baffled. The cursor returned from the above content provider query, returns a cursor with the expected count (e.g. a value > 0, at the expected position (-1), and is not closed), but cursor.moveToNext() returns false. On closer inspection BulkCursorToCursorAdapter.onMove(-1, 0) is returning false unexpectedly.

Any ideas?

###### Debug info
AnkiDroid 2.15.0 and 2.15.1

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by hanpingchinese** [comment]
Is it something to do with this class?

https://github.com/david-allison-1/Anki-Android-Backend/blob/main/rsdroid/src/main/java/net/ankiweb/rsdroid/database/StreamingProtobufSQLiteCursor.java

**Comment by hanpingchinese** [comment]
On inspection of the cursor from within the CardContentProvider (at the point where it is returned from the query method), the moveToNext() works as expected. Also, if I read (from within the CardContentProvider) the StreamingProtobufSQLiteCursor into a MatrixCursor and return that instead, then Hanping works as expected (i.e. the cursor provided by the content resolver does not have the moveToNext() problem).

So the problem is something to do with how Android's ContentProvider framework converts the StreamingProtobufSQLiteCursor into a Cursor provided (via the ContentResolver) to 3rd party apps.

**Comment by david-allison-1** [comment]
Hi @hanpingchinese

Profuse apologies for this.

The reproduction case passes in our current `androidTest` framework

`Cursor` is a `android.content.ContentResolver$CursorWrapperInner`, I can't find a source ref for `BulkCursorToCursorAdapter`

I ca reproduce this on my device, and I'll aim to get it sorted today

**Comment by hanpingchinese** [comment]
Thanks very much for your super-fast work!  I tried out the latest code and can confirm all is working again. Any idea when the app will be updated on the Play Store?

**Comment by david-allison-1** [comment]
> Thanks very much for your super-fast work! I tried out the latest code and can confirm all is working again. Any idea when the app will be updated on the Play Store?

Google's approved the release, available now.

Typically 4 days for a full auto-rollout, but users can update manually
