### ISSUE TITLE
Deck Group due count does not match deck's

### ISSUE THREAD

**Issue by topherbuckley** [ankidroid/Anki-Android#8960]
After recently updating to 2.15.0 I noticed the green review count on my deck groups no longer matches the sum of the cards due from the decks within the group. See screenshot below. I typically study by clicking the group "Japanese" as opposed to studying from each deck individually. I noticed this error after starting to study today and noticing cards from Heisigs deck popping up when studying from the Japanese group. The deck options for Heisigs are set so no new cards nor any reviews should be scheduled. If I click on Heisigs deck then these deck options are abided by, but it seems the group Japanese is no longer respecting the options set by this sub deck. 

Is this intentioal behavior? If so, what settings should be updated to make my parent deck Japanese respect the deck options of the subdeck Heisigs? 

Also I note that these cards are not shown as due when studying from Ankiweb, so it appears to be an ankidroid issue only and not something weong with my collection. 

![Screenshot_20210526-191550](https://user-images.githubusercontent.com/15166572/119643643-f281f480-be56-11eb-9075-908af1a73cf8.jpg)

Phone specs:
Nexus 6
Android 9 
Havoc v2.9 ROM

**Comment by mikehardy** [comment]
Hi there! We think this is fixed in 2.15.1 so I'm going to close this but of course please update and *if* it is not fixed let us know
