### ISSUE TITLE
Feature request: Hide Hard/Easy buttons

### ISSUE THREAD

**Issue by bmaupin** [ankidroid/Anki-Android#8966]
This might seem like an odd request but I was wondering if there was a way to hide the Hard/Easy buttons so I would only see the Again/Good buttons, and if's not currently possible if you'd accept a PR for such an option.

I love the flexibility of this app and the ability to hide a lot of the extra information on the screen (button times, ETA, etc) but I still find when I'm studying that the answer buttons themselves feel distracting. I think the distraction is more cognitive than visual: instead of answering a yes/no question (do I know this card?) I'm presented with a multiple-choice question (to what degree do I know or not know this card based on up to four choices that may or may not have changed since the previous card?).

I know that the Hard/Easy buttons are a part of the learning algorithm but I wouldn't mind the tradeoff of seeing a card more or less often as a result of not seeing them.

Thanks!

**Comment by mikehardy** [comment]
We will not deviate from upstream functionality in our main reviewer code, so if you want this change you must get it accepted upstream forums.ankiweb.net/

If you would like to bend the Reviewer here to your will and map whatever visible buttons you show to whatever you want, then you'll want to use the Javascript API we provide for niche requests like this, in combination with full screen mode, to replace the reviewer - there are examples: https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API

**Comment by bmaupin** [comment]
> We will not deviate from upstream functionality in our main reviewer code, so if you want this change you must get it accepted upstream forums.ankiweb.net/

Ah thanks, that makes sense that you would want to have a consistent UX between the different applications. I had thought of this more like the option in the settings that allows hiding the times on the buttons (the Anki web app shows the times but has no option to hide them, whereas the desktop app doesn't seem to show them at all), but I suppose the buttons themselves are consistent and this would be a significant change in functionality, even if it is just an option in the settings. At least that's my interpretation of your response.

> If you would like to bend the Reviewer here to your will and map whatever visible buttons you show to whatever you want, then you'll want to use the Javascript API

From that page:

> This api allow deck developer to add functionality to cards that can call native functions defined in AnkiDroid.

Does that mean this functionality would have to be built into each deck? That would be a bit of a bummer if so; I would hate to force this on somebody using one of my shared decks, or vice-versa have to rebuild every deck I use to add this functionality.

I've skimmed the documentation a bit but it's not clear to me how I would actually use the API, but I'll keep digging.

Thanks!

**Comment by mikehardy** [comment]
It would need to be in the card template yes - however, we *are* working towards a way where you may have javascript addons that affect all decks, and the javascript addons themselves are manageable with checks to npmjs.com and semantic versioning etc

It's the only way to do add-ons on mobile really (Javascript, that is, in the WebView) so I'm hoping it is the future, but it has been slow going so far as some huge initiatives keep popping up (like Google Summer of Code) that knock it down in priority

Until then - has to be in the card template used by a deck

**Comment by bmaupin** [comment]
Got it. Is there a particular issue for the JavaScript API that I can follow to get an update on its status?

Thanks!
