### ISSUE TITLE
[Bug] Navigation Drawer's gesture is not strict enough

### ISSUE THREAD

**Issue by mwohlbach** [ankidroid/Anki-Android#8969]
###### Reproduction Steps

1. Press finger anywhere on screen (including the far right edge of my screen) and swipe right 
(This only started happening after I updated to the new version 2.15.0)

###### Expected Result
The navigation drawer should only open if the finger is initially touched on the far left of the screen.
(From the docs: "The navigation drawer can be opened from most places in the application by pressing the left menu icon, or alternatively swiping outwards from anywhere on the far left side of the screen.")

###### Actual Result
The Navigation Drawer is opened no matter where I swipe my finger right from on the screen.

###### Debug info
AnkiDroid Version = 2.15.0
Android Version = 9
Manufacturer = samsung
Model = SM-G950U
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-G950U Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36
ACRA UUID = 84f74cb2-f3dd-4478-9912-f9f6cb43a5c7
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! The docs should be updated, this change was on purpose, phones today are quite a bit bigger than the past but hands are the same size, and for people with smaller hands they could not access it, this allows them to access it.

However, we do not intend for it to interfere with use cases.
We have heard from some users that they were drawing on the screen in reviewer and that triggered it, however the whiteboard is specifically for that use case and does not collide with this open drawer gesture

We have heard there may be other cases where it collides with a gesture but we don't have a reproduction yet.

Can you please tell us exactly what use of the system you are trying to do where the new nav drawer opening is bothersome?

**Comment by mwohlbach** [comment]
Hey! Thanks for the clarification.
That is the same use case that I was doing. I would practice writing the word by scribbling on the screen with my finger when going through cards. And by scribbling on the screen I was now constantly opening the navigation drawer. 

I just tried using the whiteboard feature (never knew this existed) and it works fine for my use case.

**Comment by david-allison-1** [comment]
> I just tried using the whiteboard feature (never knew this existed) and it works fine for my use case.

Perfect! Are you ok if we close the issue if this is solved for you?

**Comment by mwohlbach** [comment]
Yes that is fine. Thank you!
