### ISSUE TITLE
[Bug] Card Browser "Search All Decks" not returning correct results

### ISSUE THREAD

**Issue by gebezis** [ankidroid/Anki-Android#8975]
###### Reproduction Steps

Thr bug appeared after yesterday's update.

1. I am in the card browser menu of a deck on Anki Droid.
2. I search for a word.
3. There are no matches.
4. A button appears at the bottom to search all decks.
5. I click it and it returns no results (unlike before the update) even though it should return a result. 
6. If I click the menu on top which now says "All Decks" I can see only some 170 or so cards are included in this fictional "All Decks" folder and not the total of 4000 that I have. 
7. If I choose again manually "All Decks - 4000 cards", from the dropdown now the result of the search is correctly displayed. 

###### Expected Result

Before the update the "Search all decks" would return a result. On the top under All Decks was written the corect number of the total cards. 

###### Actual Result
No result is returned unless manually switched to All Decks from the drop down menu on top. The number of cards displayed under the  All Decks on top is wrong and is a much smaller number, again unless manually switched to All Decks. 

###### Debug info

AnkiDroid Version = 2.15.2

Android Version = 11

Manufacturer = samsung

Model = SM-G998B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-G998B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 34e4a61d-0029-4993-babd-17ea0e5a2781

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, thanks for the report. Could you please fill out the 'Debug Info' and ensure you're on AnkiDroid 2.15.1

**Comment by mikehardy** [comment]
Actually - current version is 2.15.2 now :-)

**Comment by gebezis** [comment]
> Hi, thanks for the report. Could you please fill out the 'Debug Info' and ensure you're on AnkiDroid 2.15.1

Done.
