### ISSUE TITLE
Optional 2x2 grid for answer buttons

### ISSUE THREAD

**Issue by caycaycarly** [ankidroid/Anki-Android#8976]
![Screenshot_20210526-214857~2](https://user-images.githubusercontent.com/57024945/119772282-8b0e8800-bedc-11eb-80a1-6c2bd534a771.jpg)

Above is the default answer button size on ankidroid. The size of it can be increased, but that only increases the "height" of the button. Not the width.

It would be neat if there could be an option to rearrange the answer buttons in a 2x2 grid as the mock-up that follows

![Screenshot-20210526-214913-2](https://user-images.githubusercontent.com/57024945/119772431-c27d3480-bedc-11eb-8dfd-3050b6ed744b.png)

Even better if the user can rearrange the buttons and not just be forced to use a fixed arrangement of the buttons in the 2x2 grid.

This would help people who have trouble with accurately clicking the intended buttons and aren't comfortable with gestures as the solution.

**Comment by mikehardy** [comment]
Worth mentioning voice control was also mentioned as a possible solution and may work for some but is only an option and is not sufficient for the use case.

If someone would like to take this on, the general idea would be that in the Settings --> Review area there should be a toggle for "Large Answer Buttons" and it would enable the 2x2 button layout as mocked up here

**Comment by Akshay0701** [comment]
I will take this issue.

**Comment by AkinchanKushwaha** [comment]
Hi, can I work on this issue?

**Comment by Akshay0701** [comment]
Sure go ahead @AkinchanKushwaha

**Comment by AkinchanKushwaha** [comment]
@Akshay0701 can you assign me this issue?

**Comment by AkinchanKushwaha** [comment]
Do I need to create a different setting option in `Settings -> Reviewing` section for this feature?

**Comment by mikunimaru** [comment]
@caycaycarly .
@AkinchanKushwaha 
Is it possible to reverse the position of hardware again and hard?
If it has the same design as the image, I feel like pressing the hard button by mistake when trying to press the again button.

Considering the frequency of pressing the button, I think it is better for the size to be larger for again and good.

**Comment by caycaycarly** [comment]
Yes, that would be my preference as well.

But, I think that there also needs to be an option to rearrange the layout. There arises no need for it when using the default 1 x 4 layout because the buttons are placed on a "spectrum" of sorts,

**Comment by mikehardy** [comment]
If possible for the first iteration of this feature I would like to keep it to a single preference, no preference to re-order. Let's go with @mikunimaru suggestion(s) and ship it then get feedback
