### ISSUE TITLE
Option to change the order of options and hide unnecessary ones in the Toolbar

### ISSUE THREAD

**Issue by Zed0004** [ankidroid/Anki-Android#8977]
### Kindly make the toolbar customizable
I always have to scroll the toolbar to use the Cloze button in the toolbar in Card Editor.
my suggestion is that the options in toolbar should be customizable and have the following properties:

- Ability to Change the order of buttons in toolbar
- Ability to hide buttons in toolbar which aren't needed often
It would be nice if these options are added in the Settings

![image](https://user-images.githubusercontent.com/84900576/119789392-a5526100-bef0-11eb-9f87-1a6f42d58e8a.png)

**Comment by mikehardy** [comment]
Hi there, this is just a stopgap until we get #1377 - spending extra developer time in here is not likely to happen, or at least is something I would prefer did not happen as it is a mal-investment of time vs getting a real WYSIWYG editor.
