### ISSUE TITLE
[Bug] Custom delimiters break in v2.15.x of AnkiDroid

### ISSUE THREAD

**Issue by natfarleydev** [ankidroid/Anki-Android#8978]
Apologies if this is raised elsewhere, since it's all punctuation it's very difficult to search for.

Essentially my problem is about custom delimiters, I have a lot of jinja templates in my questions and answers (mostly for Ansible) so I use custom delimiters with `{{=<% %>=}}` which AnkiDroid previously handled fine but the latest update (2.15.0) breaks this behaviour. This behaviour in Anki is documented here: https://apps.ankiweb.net/docs/manual20.html#latex-conflicts

###### Reproduction Steps
1. Have a template like this for back of a card with custom delimiters:
```
{{=<% %>=}}

<%FrontSide%>

<hr id=answer>

<section>
<%Back__pk%>
</section>
```

###### Expected Result
Card displays properly 

###### Actual Result
![image](https://user-images.githubusercontent.com/1312119/119791953-344d8200-becd-11eb-88b2-770f11f1409d.png)

###### Debug info
Refer to the [support page](![image](https://user-images.githubusercontent.com/1312119/119791973-39123600-becd-11eb-8cab-32e7dbfcd9f1.png)) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](![image](https://user-images.githubusercontent.com/1312119/119791973-39123600-becd-11eb-8cab-32e7dbfcd9f1.png)) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
While AnkiDroid should be handling these, chances are you no longer need them.

https://docs.ankiweb.net/math.html#cloze-conflicts

**Comment by natfarleydev** [comment]
Thanks @dae, unfortunately my problem doesn't involve LaTeX/math mode, my problems are with cards describing Jinja templates so putting a space between `}}` doesn't work

(incidentally, putting a unicode U+200B in between them does, but changing the delimiter is much easier since it means I can copy/paste easily from the web)

**Comment by dae** [comment]
It's not specific to math tags - field content is no longer considered when the templates are rendered.

**Comment by natfarleydev** [comment]
Interesting, I'll change my templates back to use `{{` and `}}` and see if it's a problem. Thanks @dae!

**Comment by mikehardy** [comment]
Very curious to hear back - we are working on harmonizing the core code of AnkiDesktop + AnkiDroid and template parsing changes in 2.15 were a large part of that. It wasn't perfect though so we have more to fix up depending on your report. Cheers

**Comment by natfarleydev** [comment]
@mikehardy Happy to report that using `{{` and `}}` in an answer no longer causes any problems with the default template variable delimiters (`{{` `}}`)  (they are in a `<pre>` tag as part of the field, but sounds like that doesn't matter for this case)

I guess the original issue still stands (problems setting custom delimiters), but this fix works for me

**Comment by mikehardy** [comment]
Great! Glad to hear we don't have a more "emergency / my review capability completely broke" type situation.

I'll add this to the queue for remediation in 2.15.3 - maybe @Arthur-Milchior has a moment to check through how the new template code is handling these...

**Comment by Arthur-Milchior** [comment]
Resolved: https://github.com/ankidroid/Anki-Android/pull/8987
