### ISSUE TITLE
Kannada Language support to Ankidroid

### ISSUE THREAD

**Issue by vinishhub** [ankidroid/Anki-Android#8979]
**Describe the solution you'd like**
AnkiDroid does not support Kannada , Kannada is the regional Language of Karnataka, India.
Creating crowdin for kannada Language will update the language.

**Comment by david-allison-1** [comment]
Hi, please get `core`, and ideally `strings` up to 100% translated and let us know

**Comment by vinishhub** [comment]
core and strings are 100 % completed

**Comment by david-allison-1** [comment]
Kicked off a translation sync: https://github.com/ankidroid/Anki-Android/actions/runs/886333372

Once this is in, I'll put in a PR, and pull in the new translations

**Comment by david-allison-1** [comment]
@vinishhub Could you confirm things are working as expected on the latest `master`

**Comment by vinishhub** [comment]
Most of the strings are translated to kannada language .

**Comment by david-allison-1** [comment]
> Most of the strings are getting translated to kannada language .

Sorry for the lack of clarity: is Kannada now selectable as a language, and working as expected after an app restart?

**Comment by vinishhub** [comment]
yup its working
