### ISSUE TITLE
[Bug] Hierarchy of review limits is now different from desktop version

### ISSUE THREAD

**Issue by sam-jaques** [ankidroid/Anki-Android#8980]
###### Reproduction Steps
1. Collection A with subcollections A1 and A2, where A1 belongs to group G1, A2 to group G2, and A to group G. 
2. Group G1 has a review limit of 0 cards, group G2 has a review limit of 20 cards, G has a review limit of 40 cards.
3. A1 and A2 each have 10 cards to review.
4. Review collections A1 and A2 by selecting collection A for review.

###### Expected Result
No cards from collection A1 are shown, and all 10 cards from A2 are shown. That is, the card limit of the subcollection applies before the card limit of the larger collection. The desktop application acts in this way.

###### Actual Result
10 cards from A1 are shown and 10 cards from A2 are shown.

###### Debug info
AnkiDroid Version = 2.15.0

Android Version = 7.0

Manufacturer = Xiaomi

Model = Redmi Note 4

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; Redmi Note 4 Build/NRD90M; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = a95b93d0-f2a7-4ba9-ba05-f51c6bf717ce

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
- [X] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by dae** [comment]
Are you using the latest computer version?

**Comment by david-allison-1** [comment]
Hi, please upgrade to AnkiDroid 2.15.1 and this should resolve it

**Comment by sam-jaques** [comment]
2.15.1 fixes it, thanks and sorry for raising a solved issue. And thanks for fixing the issue so fast the fix was released before my phone had even downloaded the version that introduced the bug!

**Comment by david-allison-1** [comment]
> 2.15.1 fixes it, thanks and sorry for raising a solved issue. And thanks for fixing the issue so fast the fix was released before my phone had even downloaded the version that introduced the bug!

Very welcome!
