### ISSUE TITLE
Android: sync always downloads everything

### ISSUE THREAD

**Issue by sm18lr88** [ankidroid/Anki-Android#8983]
I have the current version of Anki in my Android 6T.
Anytime I sync it uploads a little data (correct upload sync) but downloads the entire database all over again.
It doesn't happen in the desktop version.

**Comment by mikehardy** [comment]
Hi there!

"Current version", which exact version is that? We do releases nearly daily, people are frequently behind. You deleted our issue template, it contained advice on how to get this information and requested it from you. You requested help from us but ignored the template, that is not in general a good idea

"Android 6T", this is not a version of Android nor a device version. I believe you mean "OnePlus 6T" (nice phone, I have one), but it doesn't mention your Android version.

To your problem: have you attempted - after making sure AnkiWeb was up to date! - Settings --> Advanced --> Force full sync, then *carefully* making sure you have a backup just in case - taking a full sync from AnkiWeb replacing your AnkiDroid collection?

That has worked to stop bizarre syncing behavior for others.

**Comment by sm18lr88** [comment]
Solved. Thank you.
