### ISSUE TITLE
Statistics screen in RTL starts with the tabs scrolled all the way to the left.

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#8984]
I've noticed that the Statistics screen in RTL starts with the tabs scrolled all the way to the left.

What should happen:
1. The Overview tab, which is now the rightmost tab, should be displayed.
2. The tab selector should be scrolled to the right, so that the Overview tab's tab indicator is shown.

What currently happens:
1. The Overview tab, which is now the rightmost tab, should be displayed. (this is correct)
2. The tab selector is scrolled to the left, so that the Card Types tab's tab indicator is shown. (this is wrong)

_Originally posted by @dotancohen in https://github.com/ankidroid/Anki-Android/issues/8259#issuecomment-849839821_

**Comment by david-allison-1** [comment]
Had a play:

```
                mSlidingTabLayout.selectTab(mSlidingTabLayout.getTabAt(1)); - scrolls to 1
                mSlidingTabLayout.selectTab(mSlidingTabLayout.getTabAt(0)); (immediately after) - scrolls to the start :/
```
