### ISSUE TITLE
[Bug] Custom MathJax macros do not display correctly

### ISSUE THREAD

**Issue by msw1age** [ankidroid/Anki-Android#8991]
This started happening in version 2.15.0.
Steps to reproduce:
1. Create MathJax macro in a card template
2. Use that MathJax macro in a card

Here is an example template for the front of a Cloze card:
```
{{cloze:Text}}
<script type="text/x-mathjax-config">
  MathJax.Ajax.config.path["Contrib"] = "//cdn.athjax.org/mathjax/contrib";
</script>

<script>  
MathJax.Hub.Config({  
  TeX: { 
	extensions: ["[Contrib]/physics/physics.js", "AMSmath.js","AMSsymbols.js", "[Contrib]/siunitx/siunitx.js"],
	Macros: {
    Z: "{\\mathbb{Z}}"
	}
},
 CommonHTML: { linebreaks: { automatic: true } },
  "HTML-CSS": { linebreaks: { automatic: true } },
         SVG: { linebreaks: { automatic: true } }
});
MathJax.Hub.Configured();  
</script>
```
Here is an example card using the above macro:
``The elements of \(\Z/n\Z\) are {{c1::representative}}s of the group, but can be treated like elements.``

Here is how this appears on my desktop:
![image](https://user-images.githubusercontent.com/52355352/119949477-c2b61800-bf4e-11eb-84c9-382cd3fa82ea.png)

And here is how it appears in Ankidroid since version 2.15.0:
![image](https://user-images.githubusercontent.com/52355352/119949624-e8dbb800-bf4e-11eb-91b2-1ef7c25f3b3f.png)

**Comment by mikehardy** [comment]
Hi there! Sorry for the delay - I just marked this up for triage. Please note we issued a couple updates aimed at regressions from the switch to 2.15 - can you verify this is still happening with 2.15.2 ? 

My guess is this will still be happening but I want to make sure

Thanks!

**Comment by ShridharGoel** [comment]
This might be a change in the updated MathJax version. It is giving the same result on trying here: https://www.mathjax.org/#demo.

You may notice the same behaviour on the latest version of Anki Desktop.

**Comment by msw1age** [comment]
I can confirm this is still happening in 2.15.2.

**Comment by david-allison-1** [comment]
From the WebView Debugger:

```
__viewer__.html:26 Uncaught TypeError: Cannot read property 'Config' of undefined
    at __viewer__.html:26
```

**Comment by david-allison-1** [comment]
Emphasis mine

> There are a number of changes in version 3 that affect how MathJax is configured. In version 2, there were several ways to provide configuration for MathJax; in MathJax 3, when you are using MathJax components, there is now only one, which is to set the MathJax global to contain the configuration information prior to loading MathJax. I**n particular, you no longer call MathJax.Hub.Config(), and this function does not exist in MathJax v3**. See the section [Configuring MathJax](http://docs.mathjax.org/en/latest/web/configuration.html#configuration) for more details on how to configure MathJax.

http://docs.mathjax.org/en/latest/upgrading/v2.html#configuration-changes

**Comment by msw1age** [comment]
Thanks for your help. It seems that the issue came from MathJax 3 breaking the old configuration, and not from any problem with Ankidroid, so I will close this issue.
