### ISSUE TITLE
Does Ankidroid work on WearOS smartwatches (without a system's built-in webview)?

### ISSUE THREAD

**Issue by U1F357** [ankidroid/Anki-Android#8992]
Hi, when I tried to install Ankidroid on my WearOS smartwatch, I found that Ankidroid does not work because WearOS does not have a built-in webview, I tried to install an additional webview (_com.google.android.webview_), but unfortunately ankidroid doesn't recognize it. Is there a workable solution to make Ankidroid work in this particular condition?

WearOS seems to be no different from Android, except that it doesn't have a built-in webview.

There is a [way](https://www.bilibili.com/read/cv4661653/) to install webview by getting ROOT access to WearOS and modifying the _framework-res.apk_, but this method is complicated and can easily lead to system failure.

I think it is convenient to do the memory practice at any time on a portable device like a smart watch.

(I know this is a strange request, but carrying a cell phone is not allowed at my school, but a smartwatch is.)
(I used translation software while writing this, sorry my English is not very good, I hope you can understand.)

Ankidroid is a great software, it has helped me a lot in my English learning, thank you for your efforts!

**Comment by david-allison-1** [comment]
Hi, does https://play.google.com/store/apps/details?id=com.yannik.wear.anki work for you?

It's unmaintained on GitHub, you might want to contact the author if you have changes that you want/need to be made. It'd be great to see it back to a good state.

PS; is there a good way of detecting wearOS on startup so we could guide future users to this answer?

Best

David

**Comment by U1F357** [comment]
> 
> 
> Hi, does https://play.google.com/store/apps/details?id=com.yannik.wear.anki work for you?
> 
> It's unmaintained on GitHub, you might want to contact the author if you have changes that you want/need to be made. It'd be great to see it back to a maintained state.
> 
> PS; is there a good way of detecting wearOS on startup so we could guide future users to this answer?
> 
> Best
> 
> David

Thanks for your reply!

Ankiwear is great, and I've used it before, but unfortunately it has to rely on an Android phone to provide card information to the watch over Bluetooth, but the whole point of a smartwatch is to be portable and work independently of a bulky phone.

My idea is to have Ankidroid detect that there is no webview built into the system and direct the user to install an additional webview and be able to use it, rather than having a popup that says Ankidroid doesn't work because there is no webview built into the system.

Or the ankiwear method, which can intercept the TEXT in the anki card and only display the TEXT instead of a real web page, so that there is no need for a webview, and it can save more power.

Also, it would be great if ankidroid could do some basic UI adaptations for the small (usually 400x400px) and round screens of smartwatches!

I'm sorry I don't have any experience in Android app development, so I can only talk about my ideas here, so I'm sorry I can't help you guys. My ideas might be ridiculous or useless, if so, please ignore my ideas and spend your time on other meaningful things!

(I used translation software while writing this, sorry my English is not very good, I hope you can understand.)

Thanks!

**Comment by mikehardy** [comment]
We rely completely on the WebView

**Comment by U1F357** [comment]
> 
> 
> We rely completely on the WebView
My idea is to have Ankidroid detect that there is no webview built into the system and direct the user to install an additional webview and be able to use it, rather than having a popup that says Ankidroid doesn't work because there is no webview built into the system.
hmmm, is that possible? (I don't know Android development)

**Comment by U1F357** [comment]
> 
> 
> Any installed WebView should work. Are you just referring to a wording change?

I tried, but unfortunately, ankidroid doesn't work with the additional webview I installed, I found some information on the web, hope it helps you guys

> In wear OS, if an app wants to use a webview through the **system api,** the system will try to find _com.android.webview_, which does not exist. When you install an additional webview (_com.google.android.webview_), it will not work properly because the app name is not the same as _com.android.webview_. 

Not only that, according to the [wear OS webview installation tutorial](https://www.bilibili.com/read/cv4672026) available on the web, you need to first change the app name of the webview you want to install additionally (_com.google.android.webview_ to _com.android.webview_), and you need to move your installed webview from _/data/app/_ to _/system/pri-app/_, which requires ROOT privileges and is likely to cause a system crash during the operation.

I don't know much about android app development, and **I don't know if the above information I found on the web is correct**.

So can ankidroid go to use the extra installed webview instead of going through the system api?

(I used a translation software while writing this, sorry my English is not proficient, I hope you can understand.)

thanks！

**Comment by david-allison-1** [comment]
Your English translation is fine.

Does your installed WebView appear in your Android Settings: `Settings - Developer Options - WebView Implementation`?

We're using the default Android implementation of a WebView: if it works for other apps, it should work for AnkiDroid.

I'm afraid that you're well into the region of "this isn't supported by us, but we'll make a best effort attempt to get it working". 

If we can make small changes to get things working/make things easier, then please let us know.

**Comment by U1F357** [comment]
> 
> 
> Your English translation is fine.
> 
> Does your installed WebView appear in your Android Settings: `Settings - Developer Options - WebView Implementation`?
> 
> We're using the default Android implementation of a WebView: if it works for other apps, it should work for AnkiDroid.
> 
> I'm afraid that you're well into the region of "this isn't supported by us, but we'll make a best effort attempt to get it working".
> 
> If we can make small changes to get things working/make things easier, then please let us know.


I have searched some information and found that it seems to be quite difficult to implement my idea, and this idea should only be beneficial to very, very few people, so I think there should be no need to try it.

Maybe I will try to implement this idea by myself after I learn Android app development later.

Thanks for your answers, you're a great team!
