### ISSUE TITLE
[Bug] Interval after the decimal point is not reflected accurately in the deck option

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#8995]
###### Reproduction Steps

1. Enter 0.1 for the deck option interval
![Screenshot_20210528-190651991_1](https://user-images.githubusercontent.com/43168745/119971905-8638f980-bfec-11eb-9053-6521aa29d196.jpg)

###### Expected Result

It is displayed as 0.1.

###### Actual Result

![Screenshot_20210528-190655061_1](https://user-images.githubusercontent.com/43168745/119971891-80431880-bfec-11eb-9d7e-28b1620f8192.jpg)

###### Debug info
AnkiDroid Version = 2.16alpha00

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Mobile Safari/537.36

ACRA UUID = 53fcb5bb-27cb-45eb-86a1-052df39ff3f3

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Looks like a classic "integer treated as floating point" issue. I believe we just added the ability to have small steps like this, and it appears the addition wasn't complete... 

Appears to need something like this https://github.com/ankidroid/Anki-Android/pull/7640/files

**Comment by Peyman-hme** [comment]
Hi, Can i work on this as my first issue? I want to fix it like that PR.

**Comment by mikehardy** [comment]
Sure @Peyman-hme ! This looks like a great first issue, please communicate here (or just post a PR with what you have) if you have any questions. Welcome :-)
