### ISSUE TITLE
[Bug] Smaller AnkiDroid icon, and magnifying glass icon after 2.15.0

### ISSUE THREAD

**Issue by viivgit** [ankidroid/Anki-Android#8997]
Maybe it's two different bugs, but since it concerns icons that became smaller after the 2.15.0 update I put them together, as I suspect they might come from the same root cause.

Bug 1: **The AnkiDroid icon** (the tilted white star with round edges) **is smaller in the notification bar than before**, even though it takes the same amount of space width-wise, thus it would be better if it went back to its previous size, taking advantage of the full space it can have, thus making it more visible. It is currently harder at a quick glance, or for people with bad eyesight, to see what that icon is that indicates that you have cards to do.

Bug 2: **The magnifying glass icon** that appears at the top right of a card, that allows you to launch a search of the selected item (in an external app for instance), that you get after copying something on a card being reviewed, and then tapping anywhere on the screen, **is smaller than before**. It is harder to select than before, so it would be better if it went back to its previous size.

###### Reproduction Steps
Bug 1:
1. Have cards due
2. The AnkiDroid icon is in the notification bar 

Bug 2:
1. Have a card open for review
2. Select any item (e.g. a character, a word) by long pressing, and then on the pop up menu selecting 'Copy'
3. Tap anywhere on the card
4. The magnifying glass icon appears at the top right of the card. (If you press it launches a search for instance in another app of what you selected)

###### Expected Result
Bug 1:
The icon is the same size as before.
Bug 2:
The icon the same size as before.

###### Actual Result
Bug 1:
The icon smaller than before.
Bug 1:
The icon smaller than before.

###### Debug info
AnkiDroid Version = 2.15.2

Android Version = 10

Manufacturer = samsung

Model = SM-G960F

Hardware = samsungexynos9810

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-G960F Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 64cf8984-4f06-4def-9281-10a05fddae3e

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
The question is: does it matter?

We did a massive conversion from PNG to SVG and this is part of the aftereffect of that I'm sure.

But, if the icons were the current size originally, they would not be different, would it be okay then? In other words, this may not be something worth taking any action on.

I'm personally not bothered and would move on, but maybe I'm missing some reason the size on these is important?

#5134 is the umbrella for all the work, there were a couple follow-ons linked through #8696 #8707 #8251

If it's really bothersome we'd love a PR to alter it

**Comment by viivgit** [comment]
> The question is: does it matter?

As mentioned:
- For the Notification bar icon, it makes it harder at a quick glance for me to see what is this tiny icon among 5-10 that are there already. I'm sure it's worse for people with bad eyesight.
- For the magnifying glass, it makes it harder to click it.

So I would say yes, it matters.

Since you mention SVG, is there a parameter that can be tuned to scale these icons? A *2 scale compared to what it is now should do it.

**Comment by david-allison-1** [comment]
Notification icon:

https://github.com/ankidroid/Anki-Android/blob/910ed30408fcfd28b38e7ef5b9bd826db58b263a/AnkiDroid/src/main/res/drawable/ic_stat_notify.xml



----

Lookup icons

https://github.com/ankidroid/Anki-Android/blob/1fbf16e693e6c8787cb00f6a8b00e88f1f76be46/AnkiDroid/src/main/res/drawable/ic_lookup.xml (unchanged for 7 years)

https://github.com/ankidroid/Anki-Android/blob/2cdbfa8caa5b24b37edaf2a1445dd96f2d8ae27a/AnkiDroid/src/main/res/drawable/ic_lookup_normal.xml

https://github.com/ankidroid/Anki-Android/blob/2cdbfa8caa5b24b37edaf2a1445dd96f2d8ae27a/AnkiDroid/src/main/res/drawable/ic_lookup_pressed.xml

**Comment by david-allison-1** [comment]
The notification icon is badly formed (too much whitespace)

The lookup icon uses

https://github.com/ankidroid/Anki-Android/blob/17214602862f4edf42e6173f0715b3d5e71f61f2/AnkiDroid/src/main/res/layout/reviewer_flashcard_fullscreen.xml#L42-L43

which has changed due to the svg
