### ISSUE TITLE
Keyboard opens and closes when clicked on a search result

### ISSUE THREAD

**Issue by ShridharGoel** [ankidroid/Anki-Android#9004]
* Search All Decks
* Select a card
* The keyboard opens and closes almost immediately

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/8998#issuecomment-850763658_

**Comment by yasin459** [comment]
hi, is it still open? can I work on this?

**Comment by david-allison-1** [comment]
Sure!

**Comment by yasin459** [comment]
what is the prefered action when you want to edit a card? should the keyboard open automatically? or it must open when the user clicks on a text filed(like "Front" or "Back")?

**Comment by david-allison-1** [comment]
Open automatically, focus on "Front". Same as 2.14.6
