### ISSUE TITLE
[Bug] Cannot view cloze note with many cards in the editing screen

### ISSUE THREAD

**Issue by hjenjeldy** [ankidroid/Anki-Android#9005]
###### Reproduction Steps

1. Click on a card
2. Click the view button 
![Screenshot_2021-05-29-17-09-09-26_a9eef3a2a561b80d5c76daebd0f9a14c](https://user-images.githubusercontent.com/85016202/120066455-b5a93e00-c0a0-11eb-836c-df57654c3778.jpg)

###### Expected Result
The card is shown

###### Actual Result
Cannot view the card and the screen reads "A card could not be generated"
![Screenshot_2021-05-29-17-02-29-48](https://user-images.githubusercontent.com/85016202/120066529-2cded200-c0a1-11eb-94b0-39db4d2c8345.jpg)

###### Debug info
AnkiDroid Version = 2.15.1

Android Version = 10

Manufacturer = Realme

Model = RMX1853

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; RMX1853 Build/QKQ1.190918.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Mobile Safari/537.36

ACRA UUID = fe9d70b1-b495-4a7d-b77f-3842fa3e875b

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
@hjenjeldy Thanks for the report!

Could you provide the text of the field which is causing a problem

Is this new to AnkiDroid 2.15.X?

**Comment by hjenjeldy** [comment]
![Screenshot_2021-05-29-17-33-28-45_a9eef3a2a561b80d5c76daebd0f9a14c](https://user-images.githubusercontent.com/85016202/120067131-34ec4100-c0a4-11eb-99e6-9f5b4095480c.jpg)
Yes this only happen after the latest update Ankidroid 2.15.2

**Comment by hjenjeldy** [comment]
![Screenshot_2021-05-29-17-42-21-54_a9eef3a2a561b80d5c76daebd0f9a14c](https://user-images.githubusercontent.com/85016202/120067369-6a455e80-c0a5-11eb-91a0-26e20a40cdeb.jpg)
![Screenshot_2021-05-29-17-42-31-46_a9eef3a2a561b80d5c76daebd0f9a14c](https://user-images.githubusercontent.com/85016202/120067371-6b768b80-c0a5-11eb-9811-1a0701c69f29.jpg)
Yes this only happens after the latest update Ankidroid 2.15.2

**Comment by ShridharGoel** [comment]
@hjenjeldy There might be some specific text which is creating this issue. Can you provide the complete text which is creating this issue?

**Comment by hjenjeldy** [comment]
Here is the complete text. 
![Screenshot_2021-05-30-00-32-34-34](https://user-images.githubusercontent.com/85016202/120079560-98936000-c0de-11eb-998e-15f558ad13a2.jpg)

**Comment by hjenjeldy** [comment]
Here is the issue.

https://user-images.githubusercontent.com/85016202/120080223-1016be80-c0e2-11eb-91cb-d9bf5f96908a.mp4

**Comment by david-allison-1** [comment]
@hjenjeldy Thanks! Could you provide the text in the image as text please?

**Comment by hjenjeldy** [comment]
Here is the text.
1.<img src="img5908446481369716702.jpg">
{{c1::<img src="img3757569282625065625.jpg">}}
2.<img src="img4200410510692470506.jpg">
{{c2::<img src="img3304177105168458565.jpg">}}
3.<img src="img7546688077963552349.jpg">
{{c3::<img src="img478568764204099534.jpg">}}
4.Năm 1945, lấy đâu làm ranh giới phân chia Bắc Nam?
{{c4::vĩ tuyến 16}}
5.Năm 1954, lấy đâu làm ranh giới phân chia Bắc Nam?
{{c5::vĩ tuyến 17}}
6.<img src="img6630015611099756650.jpg">
{{c6::<img src="img2664589457377317892.jpg">}}
7.Đảng Cộng Sản VN thành lập khi nào, do ai?
{{c7::T2/1930, Nguyễn Ái Quốc}}
8.Đảng Cộng Sản Đông Dương thành lập khi nào, do ai?
{{c8::T10/1930, Trần Phú}}
9.Đảng Lao động VN thành lập khi nào?
{{c9::T2/1951}}
8. Đảng Cộng sản VN tái thành lập khi nào?
{{c10::1976}}
11.<img src="img2630143086668408679.jpg">
{{c11::<img src="img3200592909378692486.jpg">}}
12.<img src="img585809593860096435.jpg">
{{c12::<img src="img1212123446387343097.jpg">}}
13.<img src="img7062511238075474235.jpg">
{{c13::xuất thân người lãnh đạo}}
14.<img src="img6878031261858123251.jpg">
{{c14::<img src="img2961598715805978902.jpg">}}
15.Đầu XX: khuynh hướng dân chủ tư sản thể hiện qua 2 xu hướng nào?
{{c15::
Bạo động: Phan Bội Châu - đánh đuổi Pháp, giành độc lập.
Cải cách: Phan Châu Trinh - đánh đổ phong kiến}}
16.<img src="img5234665747202894940.jpg">
{{c16::<img src="img7020474356836810522.jpg">}}
17.<img src="img4095017513801871102.jpg">
{{c17::<img src="img5086475064562052921.jpg">}}
18.<img src="img8766477699572776055.jpg">
{{c18::<img src="img9084609161873533727.jpg">}}
19.<img src="img95438173421456005.jpg">
{{c19::<img src="img6481215841148968394.jpg">}}
20.<img src="img4834450231905493997.jpg">
{{c20::<img src="img5838370543841033990.jpg">}}
21.<img src="img6721741350931288169.jpg">
{{c21::<img src="img6375856707116869134.jpg">}}
22.<img src="img1501401862613208288.jpg">
{{c22::<img src="img5671901871345171294.jpg">}}
23.<img src="img8682698792715898482.jpg">
{{c23::<img src="img6222200467606526356.jpg">}}
24.<img src="img681653813637387723.jpg">
{{c24::<img src="img7678672273218865988.jpg">}}
25.<img src="img8253464911231619063.jpg">
{{c25::<img src="img6928275708037176807.jpg">}}
26.<img src="img6797136168499969062.jpg">
{{c26::<img src="img5019482681547384599.jpg">}}
27.<img src="img7824608384480365176.jpg">
{{c27::<img src="img5338642971406640932.jpg">}}
28.<img src="img6720104345082080304.jpg">
{{c28::<img src="img4440145324647795968.jpg">}}
29.<img src="img18957533837266211.jpg">
{{c29::<img src="img2407058776234788973.jpg">}}
30.<img src="img2499208069386801305.jpg">
{{c30::<img src="img2137719235413877390.jpg">}}
31.<img src="img3619099676003450516.jpg">
{{c31::<img src="img6651400926487178256.jpg">}}

**Comment by hjenjeldy** [comment]
Here is the text.
1.<img src="img5908446481369716702.jpg">
{{c1::<img src="img3757569282625065625.jpg">}}
2.<img src="img4200410510692470506.jpg">
{{c2::<img src="img3304177105168458565.jpg">}}
3.<img src="img7546688077963552349.jpg">
{{c3::<img src="img478568764204099534.jpg">}}
4.Năm 1945, lấy đâu làm ranh giới phân chia Bắc Nam?
{{c4::vĩ tuyến 16}}
5.Năm 1954, lấy đâu làm ranh giới phân chia Bắc Nam?
{{c5::vĩ tuyến 17}}
6.<img src="img6630015611099756650.jpg">
{{c6::<img src="img2664589457377317892.jpg">}}
7.Đảng Cộng Sản VN thành lập khi nào, do ai?
{{c7::T2/1930, Nguyễn Ái Quốc}}
8.Đảng Cộng Sản Đông Dương thành lập khi nào, do ai?
{{c8::T10/1930, Trần Phú}}
9.Đảng Lao động VN thành lập khi nào?
{{c9::T2/1951}}
8. Đảng Cộng sản VN tái thành lập khi nào?
{{c10::1976}}
11.<img src="img2630143086668408679.jpg">
{{c11::<img src="img3200592909378692486.jpg">}}
12.<img src="img585809593860096435.jpg">
{{c12::<img src="img1212123446387343097.jpg">}}
13.<img src="img7062511238075474235.jpg">
{{c13::xuất thân người lãnh đạo}}
14.<img src="img6878031261858123251.jpg">
{{c14::<img src="img2961598715805978902.jpg">}}
15.Đầu XX: khuynh hướng dân chủ tư sản thể hiện qua 2 xu hướng nào?
{{c15::
Bạo động: Phan Bội Châu - đánh đuổi Pháp, giành độc lập.
Cải cách: Phan Châu Trinh - đánh đổ phong kiến}}
16.<img src="img5234665747202894940.jpg">
{{c16::<img src="img7020474356836810522.jpg">}}
17.<img src="img4095017513801871102.jpg">
{{c17::<img src="img5086475064562052921.jpg">}}
18.<img src="img8766477699572776055.jpg">
{{c18::<img src="img9084609161873533727.jpg">}}
19.<img src="img95438173421456005.jpg">
{{c19::<img src="img6481215841148968394.jpg">}}
20.<img src="img4834450231905493997.jpg">
{{c20::<img src="img5838370543841033990.jpg">}}
21.<img src="img6721741350931288169.jpg">
{{c21::<img src="img6375856707116869134.jpg">}}
22.<img src="img1501401862613208288.jpg">
{{c22::<img src="img5671901871345171294.jpg">}}
23.<img src="img8682698792715898482.jpg">
{{c23::<img src="img6222200467606526356.jpg">}}
24.<img src="img681653813637387723.jpg">
{{c24::<img src="img7678672273218865988.jpg">}}
25.<img src="img8253464911231619063.jpg">
{{c25::<img src="img6928275708037176807.jpg">}}
26.<img src="img6797136168499969062.jpg">
{{c26::<img src="img5019482681547384599.jpg">}}
27.<img src="img7824608384480365176.jpg">
{{c27::<img src="img5338642971406640932.jpg">}}
28.<img src="img6720104345082080304.jpg">
{{c28::<img src="img4440145324647795968.jpg">}}
29.<img src="img18957533837266211.jpg">
{{c29::<img src="img2407058776234788973.jpg">}}
30.<img src="img2499208069386801305.jpg">
{{c30::<img src="img2137719235413877390.jpg">}}
31.<img src="img3619099676003450516.jpg">
{{c31::<img src="img6651400926487178256.jpg">}}

**Comment by david-allison-1** [comment]
Repro steps:

* create note: `{{c1::a}} {{c2::b}}`
* card browser
* select the second card
* Edit 
* Preview
* "A card could not be generated"

**Comment by david-allison-1** [comment]
Cause:

We are using the Card Template Editor Previewer. This works on a per-model basis.

⚠️ `getDummyCard()` uses `getCol` before onCollectionLoaded

https://github.com/ankidroid/Anki-Android/blob/6a7b73c25a4689ae96227bae919fdae123057824/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java#L85-L92

`getDummyCard` 
* uses `"tmpls"` which does not work for clozes (use `col.findTemplates` typically)
* uses the default field names, so clozes wouldn't be created anyway - "Text" has no "c1"

https://github.com/ankidroid/Anki-Android/blob/6a7b73c25a4689ae96227bae919fdae123057824/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java#L279-L281

Throws on line:

https://github.com/ankidroid/Anki-Android/blob/6a7b73c25a4689ae96227bae919fdae123057824/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java#L283

I'd say the main thing to do would be to better define the Card Template Previewer logic. It was only designed to work for the template editor. It now partially works on the Note Editor, but there are a few unsolved bugs which stem from the assumption that the screen is called from the template editor (variable model, fixed card).

If our dummy card creation succeeds, we later enrich it with the correct values:

https://github.com/ankidroid/Anki-Android/blob/6a7b73c25a4689ae96227bae919fdae123057824/AnkiDroid/src/main/java/com/ichi2/anki/CardTemplatePreviewer.java#L238-L257

**Comment by hjenjeldy** [comment]
Thanks for your explanation.

**Comment by david-allison-1** [comment]
Now we've explained it, let's get it fixed

**Comment by prateek-singh-3212** [comment]
I would like to take this issue.

**Comment by david-allison-1** [comment]
Sounds good to me! Can you get the fix from my diagnostics? 

I'd expect modifying `getDummyCard` to use ordinal 0 if the model is a cloze model would work

**Comment by prateek-singh-3212** [comment]
Is this issue is of high priority?

**Comment by david-allison-1** [comment]
Yes

**Comment by prateek-singh-3212** [comment]
>Can you get the fix from my diagnostics?
 I'd expect modifying getDummyCard to use ordinal 0 if the model is a cloze model would work

Yaa, I analyzed the problem and I will implement this according to your idea.
