### ISSUE TITLE
[Bug]mp3 converts to mpeg

### ISSUE THREAD

**Issue by gijshvg** [ankidroid/Anki-Android#9008]
In ankidroid, when I attach an audioclip, mp3 files get converted to mpeg. No real problem but a) the image to which the sound is connected disappears b) playing the sound is much slower. Not what I am used to. In anki, all is well, and older mp3s just play fine. Al this after update to 2.15. I could not find another post or issue about this.

**Comment by mikehardy** [comment]
Hi there! I have not seen this behavior - is there any way you could do a screen recording (in any way, posted anywhere) that demonstrates the full path to reproduce the error?

**Comment by mikunimaru** [comment]
I have exactly the same problem.
A quick survey only differs in the file extension.
![Screenshot_20210530-143908489_1](https://user-images.githubusercontent.com/43168745/120093621-7b9a7380-c156-11eb-9211-7fa16a1bd661.jpg)
![Screenshot_20210530-143935340_1](https://user-images.githubusercontent.com/43168745/120093625-81905480-c156-11eb-8934-27f986a0a571.jpg)
![Screenshot_20210530-144514895_1](https://user-images.githubusercontent.com/43168745/120093631-8523db80-c156-11eb-90b7-f7656d4dc7c6.jpg)
![Screenshot_20210530-145212111 (1)](https://user-images.githubusercontent.com/43168745/120093654-abe21200-c156-11eb-9954-9bde13695bcd.jpg)


I uploaded an audio file for test
[testmp3.zip](https://github.com/ankidroid/Anki-Android/files/6565780/testmp3.zip)

**Comment by mikunimaru** [comment]
It seems that the cause is that the contents are mp1 and mp2.
Some smartphone audio editing software outputs this type of file.
![Screenshot_20210530-150121392 (1)](https://user-images.githubusercontent.com/43168745/120094020-dd5bdd00-c158-11eb-9aaa-5e29cc6ffd49.jpg)

**Comment by gijshvg** [comment]
@mikunimaru Possible, but before the update to 2.15 all was well. Now the .mp3 returns as part of the .mpeg filename. Looks to me like a programming regression.

**Comment by gijshvg** [comment]
And here is a screenshot of  using pronunciation_ru_вишня.mp3: 
![Screenshot_20210530_163248](https://user-images.githubusercontent.com/8613802/120108480-945e5580-c165-11eb-9d55-7719b2e5cfd2.jpg)

[Russian Word.zip](https://github.com/ankidroid/Anki-Android/files/6566368/Russian.Word.zip)

**Comment by david-allison-1** [comment]
Reproduced on my Android 11. This is not a problem on 2.14.6

**Comment by david-allison-1** [comment]
`file_example_MP3_700KB.mp3` is converted to `file_example_MP3_700KB_mp3`

Cause: 2d0056c3f0a75b99fedd81affc600570c8cd96e5

https://github.com/ankidroid/Anki-Android/blob/2d0056c3f0a75b99fedd81affc600570c8cd96e5/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java#L165-L173
