### ISSUE TITLE
The undo button requires many taps to work

### ISSUE THREAD

**Issue by opiechow** [ankidroid/Anki-Android#9014]
Hello,

After one of the recent updates I need to press the undo button a random number of times after going through some of the cards. Once it starts working, I can go back through multiple cards without interruption, but then I when I go through some other cards the problem occurs again. This is really annoying especially that I tend to use this feature a lot.

**Comment by prateek-singh-3212** [comment]
Thanks @opiechow  for reporting this issue. If you provide the debug info and a vedio that describes your issue then it will be easier for us to reproduce this issue.

For debug info please go to settings > advanced > about ankidroid > copy debug info after copying edit the issue template and paste it their.

**Comment by moonlight83340** [comment]
Hey, same problem here.
For reproduction :
- do a card
- tap to cancel the last review (nothing)
- tap again (it's work)
So basicaly we need to double tap every time to cancel a review. (It's not that annoying)
Debug info :
AnkiDroid Version = 2.15.2

Android Version = 8.0.0

Manufacturer = motorola

Model = Moto Z2 Play

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; Moto Z2 Play Build/OPSS27.76-12-25-23; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 67b4dbe8-f11a-474c-bbdd-7191400d7f23

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by ShridharGoel** [comment]
Can a video be attached? Not happening on my device.

**Comment by mikehardy** [comment]
We *think* this may have been a padding issue with regard to the undo button, that is was attempting to detect taps too precisely, and @ShridharGoel just posted a fix that I'm merging for release 2.15.3 which should go out shortly. When I merge that fix it will mark this closed but if the issue is still happening after you update to 2.15.3 please post a video of it here and we can reopen and re-investigate. Thanks!

**Comment by opiechow** [comment]
FYI after the update it the issue is resolved, thank you very much :)🍺

**Comment by moonlight83340** [comment]
Issue is resolved, thanks guys !
