### ISSUE TITLE
Increase or eliminate the upper limit of backup generation

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#9022]
**Is your feature request related to a problem? Please describe.**
With backup limits of up to 10 generations, I'm worried about preparing for upcoming delicate changes such as schema changes.

**Describe the solution you'd like**
Increase or eliminate the upper limit of backup generation

**Describe alternatives you've considered**
The classic method of manually re-backing up backup files.

**Additional context**
As the storage capacity of smartphones has increased recently, it may be more advantageous to raise the default setting value of the backup generation at the same time.
Even if the default number is set to 50 generations like the anki desktop, I think that there are few people who run out of storage capacity with current smartphones.

**Comment by david-allison-1** [comment]
I'll say that I'm going to be very cautious with the schema upgrades. But I understand your concern.

I do feel that it's excessive, but I've proposed the change

**Comment by mikehardy** [comment]
I agree with @mikunimaru - if the default is the same, the upper limit is really arbitrary in my mind. I've got 60GB of space free on my phone and AnkiDroid's database is about the most important thing I have. What do I care if there are 80 copies of it? Wouldn't bother me and if it takes up too much space it's something I did to myself

**Comment by mikunimaru** [comment]
Ideally, it is better to set by numerical input instead of bar.  People who set a large number on the desktop side will be able to apply the same value.

Initially I proposed to increase or remove the upper limit, but I think it would be better to remove the upper limit as the desktop does.

I felt that it was not necessary for the app to set the upper limit of the most important settings such as backup unless it was unavoidable due to the specifications.

**Comment by mikunimaru** [comment]
However, when I checked it now, the upper limit on the desktop side was 99 generations, so I think the change of @david-allison-1 is accurate.

Regarding the default value of the setting item, I think that it is one way to match it with the desktop.

**Comment by mikehardy** [comment]
The preference type David just implemented is a plus/minus bar that you may also just type into directly
