### ISSUE TITLE
[AnkiDroid 2.15.2] API Issues: AnkiReview

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9029]
I'm seeing some occasional errors on AnkiReview with Ankidroid 2.15.2 (Attempt to invoke interface method 'boolean android.database.Cursor.moveToFirst()' on a null object reference), is this a known issue with the API ? I can try to put together a repro but doesn't seem to happen systematically.

_Originally posted by @lucwastiaux in https://github.com/ankidroid/Anki-Android/issues/8931#issuecomment-851570757_

**Comment by lucwastiaux** [comment]
I'll try to put together a repro in the next couple of days, I downgraded to AnkiDroid 2.14 for now.

**Comment by mikehardy** [comment]
No reproduction - punting to 2.16 for now
