### ISSUE TITLE
Show multiple previews for more than one card

### ISSUE THREAD

**Issue by ShridharGoel** [ankidroid/Anki-Android#9034]
If a user selects the `Cloze` option and creates a note like this: `{{c1::Test1}} {{c2::Test2}}`, we can show previews for both the cards. Currently, only the preview for the first card is shown.

**Comment by david-allison-1** [comment]
There's already a PR and issue in for this one, I'm on my phone so can't easily find it

**Comment by ShridharGoel** [comment]
Got it: https://github.com/ankidroid/Anki-Android/issues/7941.
Thanks @david-allison-1 for letting me know.
