### ISSUE TITLE
Ankidroid update to the latest version via Google Play on older smartphones and Android versions

### ISSUE THREAD

**Issue by kodovanie** [ankidroid/Anki-Android#9037]
Dear all,

is it possible to update to the latest version of Ankidroid on Samsung Galaxy S3 mini, Android version 4.1.2? I am also signed as beta-tester on google play.

The latest version version I have is 2.14.6 (according to info directly from Ankidroid). I have always been updating the app via Google play.

Google play does not show me any updates - I know there is version 2.15.2 (27th May 2021).
In the area information (on Google Play) it even says version (2.10.4), updated (31.05.2020) - this completely confuses me because I have actually higher version that what Google play is currently telling/offering me.

The reason why I would like to update to the latest version is that I would like to have synchronization between desktop Anki and mobile Ankidroid. I read somewhere that the best thing to do is just to update to the latest version. Nowadays I cannot synchronize the devices because of this time zone handling - I know there is a tip (for older versions) to tick "Legacy timezone handling" in Anki desktop, but I am scared to be using it, because in the brackets it says "buggy", so I am not sure what it means and do not want to corrupt my collection.

**Comment by mikehardy** [comment]
No it is not, sorry. Our minimum supported android for AnkiDroid 2.15 and the future is now Android 5.x
You'll need to find a new device or find a way to get a new Android version on your existing device.
I've good luck with LineageOS in the past.

**Comment by kodovanie** [comment]
Hi. Ok thanks for letting me know.

**Comment by david-allison-1** [comment]
Just to note: don't worry about corruption from the timezone code, it's been in production for years, and was the original default in both ankidroid and Anki desktop.

**Comment by kodovanie** [comment]
Hi, thanks for the heads-up.
