### ISSUE TITLE
Inform users about availability of new update

### ISSUE THREAD

**Issue by ShridharGoel** [ankidroid/Anki-Android#9039]
Whenever a new update is released, we can display a dialog in the app to inform users about the update.

This library can be used here: https://github.com/javiersantos/AppUpdater

**Comment by ShridharGoel** [comment]
I'll add this if it is accepted.

**Comment by david-allison-1** [comment]
Personally: I'd rather not, especially if it's hard to detect when we deprecate a version, and I'd definitely not want internet access without consent from a user.

It feels this should be a function of the app store that a user uses

**Comment by mikehardy** [comment]
I agree with this one also - historically I haven't seen any issue with users updating with reasonable speed - it's an interesting idea but as a user I don't like my apps to bug me about this sort of thing unless an update to them has security implications (like my banking app, or web browser) - for flashcards, I'll get to it don't bug me ;-)
