### ISSUE TITLE
Range selection mode in the card browser

### ISSUE THREAD

**Issue by caycaycarly** [ankidroid/Anki-Android#9041]
It would be helpful to have a toggle for a "range selection" mode in the card browser where you can set the start and stop positions to select all the cards in the range.

![Screenshot_20210601-205144~3](https://user-images.githubusercontent.com/57024945/120350513-aa624680-c31c-11eb-9203-137142d2b6e9.jpg)

![Screenshot_20210601-205136~2](https://user-images.githubusercontent.com/57024945/120350528-b0582780-c31c-11eb-9edc-e157a903bffa.jpg)

**Comment by caycaycarly** [comment]
Oops. Feature already exists. Long press the ending row and the range is selected.

**Comment by david-allison-1** [comment]
Todo: add this to the manual

**Comment by mikehardy** [comment]
@caycaycarly if you want to have a go at adding it to manual you can hit the edit button on this page and put it somewhere that seems appropriate? https://github.com/ankidroid/ankidroiddocs/blob/master/manual.asc :-)
