### ISSUE TITLE
No response when tapping the answer button quickly

### ISSUE THREAD

**Issue by mikunimaru** [ankidroid/Anki-Android#9042]
###### Reproduction Steps

1. Press the answer button immediately after displaying the answer

###### Expected Result

Proceed to the next card

###### Actual Result

Button does not respond

https://user-images.githubusercontent.com/43168745/120378776-d18b3900-c359-11eb-9dd2-48b1bff4ab6c.mp4

###### Debug info
AnkiDroid Version = 2.16alpha00

Android Version = 10

Manufacturer = asus

Model = ASUS_I01WD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ASUS_I01WD Build/QP1A.190711.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Mobile Safari/537.36

ACRA UUID = 53fcb5bb-27cb-45eb-86a1-052df39ff3f3

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by prateek-singh-3212** [comment]
Thanks @mikunimaru  for reporting the issue. I am not able to reproduce this See vedio :- It is smooth for me.

https://youtube.com/shorts/z3PlfPd8f3w?feature=share

It depends on mostly on cpu usage and the how big is card to render. Mentor's Please correct me if I am wrong.

**Comment by mikunimaru** [comment]
@prateek-singh-3212 
When I played your video at 0.25x speed, I could see that the first Easy tap on the second card wasn't responding.

In other words, my issue is reproduced in your environment.

**Comment by prateek-singh-3212** [comment]
Surely, Their is but not that much because all the process in the background takes some time to complete as I said earlier their are lots of factor on which it depends. I would like to know other members thoughts on this issue.
Thanks @mikunimaru for finding this issue.

**Comment by david-allison-1** [comment]
We should be able to fix this. the first step is knowing why this occurs. 

My theory is that it could be a problem with double-tap protection on the buttons

**Comment by ShridharGoel** [comment]
To prevent accidental double taps, we have a 200 ms time interval before the second click would be registered. So isn't this expected?

**Comment by mikunimaru** [comment]
@ShridharGoel
It may be convenient to prevent erroneous taps immediately after displaying the question, but I think it is not necessary to prevent erroneous taps immediately after displaying the answer.

The user may intentionally double-tap quickly, such as when the answer is clear.
In fact, I raised this issue, recognizing that it was a bug because the intentional double tap did not respond many times.
In my case, there are many easy questions, and I often perform actions to move to the next question quickly, so I encounter this unresponsiveness many times a day.

**Comment by ShridharGoel** [comment]
@mikunimaru That makes sense.
@david-allison-1 Should we consider decreasing the time interval here?

**Comment by david-allison-1** [comment]
I think we need to confirm that we're hitting the limit.

Personally: After that. Let's try 150ms. 

@mikehardy - think this one is your call

**Comment by mikehardy** [comment]
agreed on both. There was a strong defense of the double-tap protection on discord so I don't want to scrap it. It has saved me during review as well and even on my *fastest* cards 200ms is no bother personally. In questions of taste like that I default to no change

**Comment by mikunimaru** [comment]
If there is a demand for double tap protection, it seems better not to touch this specification.  If the delay does not change with the CPU specifications of the smartphone, it is a specification rather than a bug.

This isuue seems to be the kind of issue where the number of people who encounter the issue in the first place is small, although those who do encounter it will encounter the same problem over and over again.

For most people, the benefit of double-tap protection will be greater, so closing it doesn't seem to be a problem. If it is to be opened again, it would be more appropriate to rework it as a feature request rather than a bug report.

**Comment by ShridharGoel** [comment]
A setting can be added for disabling double tap protection in the preferences.

**Comment by mikehardy** [comment]
That's a good point @ShridharGoel and exactly what I thought when @mikunimaru correctly put it in the context of a specification, I hadn't been thinking clearly about it. If it is a spec, and a matter of taste, then yes could be a preference and even a configurable delay. User wants 10ms? Okay. 0? okay. 200 (current) as default. I consider this a minor feature but only because I don't hit it often. For those that hit it over and over, it could be nice to have

**Comment by mikunimaru** [comment]
It would be great if the protection time could be set.  Then there are benefits not only to those who want to reduce protection like me, but also to those who want to increase protection.
