### ISSUE TITLE
Deck Menu (after long-pressing a deck title)

### ISSUE THREAD

**Issue by joshakaw** [ankidroid/Anki-Android#9043]
**Is your feature request related to a problem? Please describe.**

Yes, the whole Deck Menu experience could be much better. One of my main issues is that all of the buttons look homogenous and there is a mental lag of adjusting to the layout. Nothing is in a memorable placement either - if I asked you to tell me the order without looking, you probably couldn't. 
This combined with a long press adds up to a pretty extended period of time before you are ready to change a setting.

My next problem is that there are sub-menus and variable dumps (such as "Increase value by x amount") just to perform a simple task.

**Describe the solution you'd like**

![home-page.png](https://user-images.githubusercontent.com/84877484/120401373-d0ccb580-c30d-11eb-9005-fee53918db27.png)

**Long press issue:**

Currently:
1. Clicking title instantly starts studying.
2. Clicking count brings to special menu.
3. Pressing and holding brings to Deck Menu.

Suggestion - Reverse these button functions and add arrows to signify an "instant study" button:
1. Clicking title brings up the Deck Menu.
2. Clicking Count instantly starts studying.
3. Special menu no longer exists (info moved to Deck Menu).
4. Press and hold Count to custom study. May need a tutorial or a popup to inform about this. 

![new-settings-edit.png](https://user-images.githubusercontent.com/84877484/120402591-8d277b00-c310-11eb-811e-8e1650c06e62.png)

**Aforementioned Deck Menu issues:**

Suggestion - Menu with easy way to change and view deck settings/info:
1. Renaming is already a editable field.
2. You can start studying immediately after changing settings with Study button (same as previously suggested Home layout).
3. View/edit your current deck options group.
4. View/edit today's card limits.
5. Less common actions are in the ... menu (Export, Add to Home, Delete).
6. Press and hold Study button to custom study.

Edit - "Suggestion to the Suggestion"
+1. There could be multiple icons on the top besides the ... menu such as info, stats, edit/add, etc.
+2. Selected deck name in the faded background would be moved to the center (much like a phone keyboard when selecting text that the keyboard would block).
End Edit

**Describe alternatives you've considered**

As I was thinking of it, I came up with many alternatives that still annoyed me, here they are. I'm sure there's another good way but I haven't thought of it.

Fixing long press issue:
1. Deck Menu in sidebar.
2. Deck Menu after pressing Count button.
3. (...) button after every deck name that leads to the Deck Menu.

As for a new Deck Menu, it is probably not helpful to give alternatives of my own opinion on the layout because no one's decided on anything yet.
But I do think a Deck Menu with a memorable and easy layout is very desirable.

**Additional context**

Since no other studying app works like AnkiDroid, it has to be as easy to use as possible for new people. And when it's easy to use for new people (and not dumbed down) it's a lot easier for people that have used AnkiDroid for a while.

**Comment by mikehardy** [comment]
Hi there, with apologies, this is so many items at once you can see it does not appear actionable to use. Due to volume of development in progress we have extremely limited time to consider ideas, work with contributors to get a PR in shape to merge, and merge it.

I suggest you focus on extremely small things and do them one at a time, that is the most successful way to get changes made. Especially in the UI - any time we make UI changes a significant portion of our userbase complains, so we must consider them carefully and a big batch like this is unworkable.

If you take a single one of your ideas here and post a PR for it, we can consider it for merge I think
