### ISSUE TITLE
Unit Test for Cloze Card Preview

### ISSUE THREAD

**Issue by prateek-singh-3212** [ankidroid/Anki-Android#9046]
A unit test should be added for the cloze card preview. For cloze card preview ordinal is set to 0 .

Reference PR: #9040 _(Orignally posted by @david-allison-1)_
https://github.com/ankidroid/Anki-Android/pull/9040#pullrequestreview-673781254

**Comment by prateek-singh-3212** [comment]
I will add the unit test after on week as my college exams starting from 3 june and will finish on 8 june. So, I will be less active during this period.

**Comment by david-allison-1** [comment]
Good luck!!!!! Life comes first. Wishing you all the best

**Comment by prateek-singh-3212** [comment]
Thanks 😊

**Comment by david-allison-1** [comment]
@prateek-singh-3212 is this still potentially going to be completed? I can take it on if you'd like
