### ISSUE TITLE
Increase privacy policy compliance (for Huawei and everyone really)

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#9050]
I took the opportunity with 2.15.3 release to also (finally) publish 2.15.x on to the Huawei AppConnect app channel

I noticed (and they notified us) that we are not fully compliant with their privacy policy (section 7):

https://developer.huawei.com/consumer/en/doc/30202#h1-1613641610376-6

Specifically I think in the first Help page we probably need a new sub-menu for "Privacy" and in there we need to put a link to our existing privacy policy (we use https://ankiweb.net/account/terms as ours also) with some extra information about opt-in and fully anonymous nature of our analytics and our crash reporting system

Also note that this is a good opportunity to do an audit of the data we collect to make sure that it is truly anonymized and does not contain any PII (Personally Identifiable Information) so that GDPR compliance is as easy as it should be (that is: there is no way to request what information we have on you or delete it because it's completely anonymous so we could not locate you if we tried and there is therefore nothing to see or delete)

**Comment by tanmayChakrawarty** [comment]
@mikehardy I would like to work on this.

**Comment by mikehardy** [comment]
That would be great! Thanks @tanmayChakrawarty

**Comment by tanmayChakrawarty** [comment]
@mikehardy So far I have done this please give your feedback on this and let me know what else do we need to implement.

https://user-images.githubusercontent.com/75254780/121179377-51933080-c87d-11eb-977a-5b142b7a7183.mp4

**Comment by david-allison-1** [comment]
We need to have an AnkiDroid and AnkiWeb policy linked

The AnkiDroid policy is currently listed on the wiki
