### ISSUE TITLE
Regression tests: 2.15.3 crash on startup

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9056]
2.15.4 is rolling out now and is already available here @burbilog please confirm it works for you? It should - if not there is something else going on: https://github.com/ankidroid/Anki-Android/releases/tag/v2.15.4

Action plan for 2.15.5 on this one:

- There must be a test that fails on 2.15.3 (and it should fail on master as well?) via starting the study options fragment from deck picker via the review counts (to prove this can't happen again - this has been problematic in the past)
- then fix the navigation drawer preference PR on master and enable the test
- merge that fix PR
- cherry-pick the navigation drawer gesture preference back to release-2.15 and the fix PR for it as well

Sound about right @david-allison-1 ?

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/9052#issuecomment-853378139_

**Comment by ShridharGoel** [comment]
I'm working on this.

**Comment by mikehardy** [comment]
I just looked through and it appears that the regression test for this - #9073 - is in progress but the actual fix for the navigation drawer preference PR is not done yet? If anyone is aware of the status and I'm wrong, please correct me!

**Comment by ShridharGoel** [comment]
@mikehardy It was fixed in #9057.

**Comment by mikehardy** [comment]
We're still working on regression tests but I *finally* just now had time to work through the stack and get back to this. :sweat_smile: 

I pulled it and tested it locally with the new gesture preference for full screen navigation drawer both on and off, and opening the study options screen works in both modes now. I think we're stable then on master currently
