### ISSUE TITLE
Gentle restart for stalled users

### ISSUE THREAD

**Issue by Autonom** [ankidroid/Anki-Android#9068]
Anki is great, but sometimes I stop using it because real life happens and I lose the habit.  When I receive reminders, I have too many cards to catch up on and this is off-putting, acting as a psychological barrier to restarting.   I've been ignoring the daily reminders for over a month now.

Anki could do more to encourage the user back into the habit.  Does anyone else drop the habit and need a bit of encouragement to get going again?

**Describe the solution you'd like**
Reduce the number of cards to just 1 or 2, an easy win, and gradually increase build the user back up to the usual number of cards.   

**Describe alternatives you've considered**
Grit my teeth and dig deep to find the motivation to start again.

**Comment by david-allison-1** [comment]
Just confirming: you are aware that you can do this already with the settings? Long press a deck and change the number of new/review cards

AnkiDroid's a port of Anki Desktop, we try to remain in-sync feature wise, and try not to introduce new features to ensure that all clients in the ecosystem function in the same manner.

If you want to request a feature, it's best to go through Anki Desktop first, then we'll definitely add it to our issues list: https://forums.ankiweb.net/

**Comment by Autonom** [comment]
Yes, I know about the number of reviews in the settings.

Anki is smart in the way it determines the interval for the next review to optimise transfer to long term memory.  Similarly, it could be smart in optimising the workload to encourage the stalled/demotivated user.

The number of new/review cards might have an upper bound which is a function of the number of missed reviews over the last few weeks. 

I'm not familiar with the desktop client as I just use mobile and Ankiweb. Well, until I stalled ;-)

**Comment by mikehardy** [comment]
With apologies, this is an area of features where we must stay in tune with desktop, as it is not specific to the mobile form factor or android limitations. As mentioned above the forums.ankiweb.net link is where to ask.

I imagine you may like desktop, in combination with the load balancer add-on perhaps https://ankiweb.net/shared/info/208879074

This will not result in a change here unless/until Anki Desktop implements it though, so it is not something we will track
