### ISSUE TITLE
[Bug] Regression: AnkiDroid crashes (100% reproducible) when clicking an empty custom deck in deck list

### ISSUE THREAD

**Issue by wujek-srujek** [ankidroid/Anki-Android#9069]
###### Reproduction Steps

1. Create a custom deck , e.g. for a tag, and give it a name.
2. Make sure this deck is empty (e.g. do all the cards or empty it).
3. In the deck list, press the custom deck.

###### Expected Result

As it used to be, I expect to go to the deck 'summary' screen, which allows me to rebuild it and start learning.

###### Actual Result

The application crashes.

###### Debug info

AnkiDroid Version = 2.15.3
Android Version = 11
Manufacturer = Google
Model = Pixel 3 XL
Hardware = crosshatch
Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3 XL Build/RQ2A.210505.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.77 Mobile Safari/537.36
ACRA UUID = 1a81993f-e029-414a-bf93-61365f783895
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true

###### Research

Workaround: in the deck list, long press the custom deck, choose 'rebuild' - this will make sure the deck isn't empty, and now I can start learning. So, the crashes seem to happen on empty custom decks only.

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, thanks for the report. 

Fixed in 2.15.4, please upgrade. Sorry for the inconvenience.
