### ISSUE TITLE
[Bug] Text not showing 

### ISSUE THREAD

**Issue by badchute** [ankidroid/Anki-Android#9072]
here's a video of an example. 
https://user-images.githubusercontent.com/78628674/120799274-1a690a80-c571-11eb-8c25-0b015eb20234.mp4 

I found the same bug that is reported a few months ago but the solution given for them wasn't working for me. 

###### Debug AnkiDroid Version = 2.15.4

Android Version = 10

Manufacturer = realme

Model = RMX2030

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; RMX2030 Build/QKQ1.200209.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.99 Mobile Safari/537.36

ACRA UUID = 6b936a7a-ff28-4c98-bbe0-f3d534c49145

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true
 

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Thank you for opening a separate issue and filling in the debug info @badchute - I believe it will help fix this

Referenced issue is #8153 

From there https://github.com/ankidroid/Anki-Android/issues/8153#issuecomment-854777013

>  also notice that the statistics overview is blank
> 
> i tried doing it on ankiweb and it works
> 
> i also tried deleting all my files then re installing ankidroid but the problem is still there.

Statistics overview is also a WebView which is a great avenue of investigation: this will probably be a WebView issue.

I notice from User Agent diagnostics the version is unexpected:

> Webview User Agent = Mozilla/5.0 (Linux; Android 10; RMX2030 Build/QKQ1.200209.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.99 Mobile Safari/537.36

My Android System WebView is listed as version `91.0.4472.88` so I infer you have an outdated WebView on your device and my hypothesis is now that updating that will fix things.

There are lots of articles online that should nudge you towards having an up to date webview: https://duckduckgo.com/?q=how+do+I+update+android+system+webview

Can you please attempt to reproduce after you've got a webview version of 91+ to see if it still happens?

**Comment by badchute** [comment]
IT WORKS!! thank you so much for your hard work.

**Comment by mikehardy** [comment]
Oh that's great news - I was afraid we had another bizarre WebView bug (the last one is still too fresh in my mind). Make sure you keep auto-update on if you can and specifically keep the WebView and Chrome up to date on your system - those are a big part of whether your phone is secure against hacking from malicious websites or not, and of course it helps keep flashcard apps working :-). Cheers

**Comment by ChrisMoinsen** [comment]
This bug was driving me mad: on one phone with Android 9, the app was working perfectly. On a older phone with Android 8, the text on the cards was always invisible. According to the hints  above, I tried to update WebView, but it already was the latest version. 

My final solution was very simple and successful: **reboot the device!**

Anyhow: a big thanks to the developers for this great app!

**Comment by david-allison-1** [comment]
Thanks!

`Settings - Advanced - Disable card hardware render` may be useful on your Android 8, but no need to if things are working
