### ISSUE TITLE
[Bug] The default deck can't be deleted

### ISSUE THREAD

**Issue by bmaupin** [ankidroid/Anki-Android#9074]
###### Reproduction Steps

I generated a test deck using the anki python API, imported it into the desktop app, and synced. When I try to delete it from AnkiDroid, I get this message:

> The default deck can't be deleted

I do seem to be able to delete it from the Anki Desktop app, however.

I don't see anything in the AnkiDroid documentation referring to a "default" deck or why it might be handled differently from other decks; I found a similar issue but it no longer seems to be accurate since I am able to delete the deck from Anki Desktop:

> This isn't a bug; you can't delete the default deck in Anki Desktop either. Rather it
should be hidden when it's empty.

(https://github.com/ankidroid/Anki-Android/issues/2497#issuecomment-125523960)

Here's the .apkg file I generated:

[test.apkg.zip](https://github.com/ankidroid/Anki-Android/files/6600471/test.apkg.zip)

###### Expected Result

I would expect to be able to delete it, as I'm able to delete it using Anki Desktop.

###### Actual Result

Unable to delete it as described.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Thanks!

**Comment by Arthur-Milchior** [comment]
I've just tried on desktop, and when I try to delete the unique deck of the collection you shared, it delete the content of the deck, however, there remains a deck called "default" in the list of decks.

So it seems that even if you got no error message, the deck is still here.

It seems that anki evolved in the way it behaves with default deck. Maybe we should eventually copy it.
Does it creates any trouble to you that require you to need a correction quickly? Otherwise, I'd argue, wait for rust to ensure this new behavior is automatically copied in ankidroid.

**Comment by bmaupin** [comment]
I was confused as to why I wasn't seeing the same behaviour, so I deleted all of my decks from Anki Desktop, and lo and behold the Default deck was still there, albeit empty. The behaviour seems to be:

- If Default is not the only deck and *Delete* is chosen, the cards in the deck are deleted and the deck is hidden
- If Default is the only deck and *Delete* is chosen, the cards in the deck are deleted and the Default deck is still shown

This is definitely a minor inconvenience at most (I can always delete the default deck from Anki Desktop and then sync) so feel free to close it, especially if AnkiDroid will get the desktop behaviour at some point.

Thanks!
