### ISSUE TITLE
[Bug] Sync is not work

### ISSUE THREAD

**Issue by levirs565** [ankidroid/Anki-Android#9076]
###### Reproduction Steps

1.  Create deck and note
2.  Login to AnkiWeb in AnkiDroid
3.  Sync notes

###### Expected Result

When I open https://ankiweb.net/decks/ , this must show all my decks and notes.

###### Actual Result

When I open https://ankiweb.net/decks/ , this only show Defaults deck and this deck does not have any card (0 card and 0 note)

###### Debug info
AnkiDroid Version = 2.15.4

Android Version = 10

Manufacturer = OPPO

Model = CPH2185

Hardware = mt6765

Webview User Agent = Mozilla/5.0 (Linux; Android 10; CPH2185 Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = e0b3ffbd-bfcc-467e-a0e4-ce0f8b1afa5a

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! You say "sync notes" - the first time you log in to AnkiWeb typically you need to do a "full sync".
My hypothesis is that you either did not or did not sync in the correct direction.
It sounds like something did not go correctly at this point in the process.

You may go to "settings" --> "advanced" in the AnkiDroid settings and choose "force full sync" to force the issue. After tapping that then when you sync the next time it will prompt you again to overwrite the collection on one side or the other. Overwrite the AnkiWeb side with your Device collection and things should show up over there.

If not then it is possible you have somehow attempted to login to AnkiWeb using a different account.

**Comment by levirs565** [comment]
Thank you for your support. AnkiDroid sync work after Check Database.

**Comment by mikehardy** [comment]
Great to hear! Thanks for reporting back
