### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by MedicalArk** [ankidroid/Anki-Android#9079]
###### Reproduction Steps

1.  I added ~9,000 audio files on Anki Desktop and attempted to sync on AnkiDroid. They are about 4GB total size.
2.  The sync starts, but then reaches "Synchronization" and becomes slow. It downloads approximately 500Kb every minute

###### Expected Result
The synchronization downloads at normal internet speeds and occurs over several minutes or an hour

###### Actual Result
The synchronization downloads at slow speeds and has not fully synced over the last week after multiple syncs.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [X ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ X] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Not saying this is not an issue, but this is a duplicate - #8925
