### ISSUE TITLE
Card Counts not Synced & Can't find "New Timezeone Code"

### ISSUE THREAD

**Issue by Skyron27** [ankidroid/Anki-Android#9082]
My ankidroid account is synced to the same one I use in my PV. However, there is an issue with the review system where the app says 0 reviews left whilst the PC says 46. Also sometimes it says certain subdecks have reviews left but when I try to do the review from the parent deck, it doesn't show anything. I have to select the exact subdeck to do the review. I got feedback from the team saying that I should try enabling "New timezone code" but I don't see that option being available.

###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by prateek-singh-3212** [comment]
Hi @Skyron27 Thanks for reporting this issue. Please provide us the debug info
For debug info GoTo: Settings > Advanced >About AnkiDroid > Copy debug info.

PS. Please Rename the title and make it 1 line and describe the issue in template.
For editing the template go to 3 dots and select edit.

**Comment by david-allison-1** [comment]
Hi @Skyron27, could you fill out the template in the main post please.

Thanks

David
