### ISSUE TITLE
[Bug]Incomplete translations for Azerbaijani

### ISSUE THREAD

**Issue by skull591** [ankidroid/Anki-Android#9085]
###### Reproduction Steps

1. Go to the settings page and change the language to Azerbaijani
2. View the General settings page

###### Expected Result
All texts are translated to Azerbaijani

###### Actual Result
While some texts are properly translated, some of the texts remain in English

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by prateek-singh-3212** [comment]
Thanks @skull591 for reporting this issue. AnkiDroid is having just 26% of text converted to Azerbaijani from english.
Link of Crowdin Page : https://crowdin.com/project/ankidroid/az#

If you want to contribute in langauge translation then feel free to do this. I will helps the people who uses AnkiDroid in Azerbaijani.
For Contribution look: https://github.com/ankidroid/Anki-Android/wiki/Translating-AnkiDroid.

Are you intrested?

**Comment by mikehardy** [comment]
As @prateek-singh-3212 showed - this is not really an issue, we don't track them here in that way as most languages never make it to 100% and it would just clutter our issue tracker. But we would love it if you or anyone you know helps translate on crowdin.com! Thanks
