### ISSUE TITLE
Feature request: grouping decks in folders

### ISSUE THREAD

**Issue by eiluudio** [ankidroid/Anki-Android#9087]
Ankidroid should implement a "folders" feature to group types of decks together. 

For those of us who dabble in far too many languages/topics, the main screen can be unwieldy to use, especially when trying to mentally "contain" languages within specific days of the week. Being able to throw all decks of a particular type in a collapsable folder would be amazing. If the feature then also included ways to "silence" or reflect whatever stats the currently "highlighted" folder has, that would be a bonus. But the main premise in my mind is simply grouping and collapsing categories on the main screen--sort of like how decks do for subdecks, but for all decks themselves.

Thanks for your consideraton. I should add that Anki is my favorite and most used app by far. I would also be willing to donate to help towards this feature being made but I am unsure how that process works even after reading the guide, as a non-expert.

**Comment by david-allison-1** [comment]
Hi, 

Does this work: https://youtu.be/LtNbQ8185e4

Make a top level deck per-language and move the subdecks underneath it

**Comment by eiluudio** [comment]
I'm...speechless. Yes! God, I've been wanting to do that for years. 

However I will simply say this seems to come from the PC Anki school of design, where highly customisable infinite phrasings can help create the flow you want--whereas on mobile, as an ignorant and non-PC acquainted user, it never occurred to me (perhaps I didn't check!) that I could do such things. While I'm all for manual customisability, having the option to do it with a long press or in some kind of main menu where you organise with easy swipes and presses may be a pipe-dream, but I think helpful for a lot of users who have no idea this feature exists!

Thanks again.

**Comment by david-allison-1** [comment]
I added "Create Subdeck" to the long press menu for a deck a while back

Could this be better named?

**Comment by eiluudio** [comment]
Interesting--that mechanism would make sense, except here I wasn't trying to make subdecks but 'master decks', if that makes sense--so an option to create one above the current level that contains the long-pressed item would be good, rather than another sub-level that I have to then move around. 

Unless what it means by 'create subdeck' is _turn this deck into a subdeck of a larger deck_, in which case it's just confusing...lol. 

Appreciate the support!
