### ISSUE TITLE
Traduction chinoise 翻譯錯誤 [Bug]

### ISSUE THREAD

**Issue by vintotal** [ankidroid/Anki-Android#9090]
###### Reproduction Steps

1. Synchroniser en utilisant la version en chinois de Taïwan
2. Utiliser Ankiweb comme source
3. Constater que le texte dit « Ankiweb » deux fois et que le « Ankidroid » est absent.

![Screenshot_20210609-073331](https://user-images.githubusercontent.com/1743914/121348233-1719aa00-c8f6-11eb-8982-65a9d0612777.png)

###### Expected Result

Indiquer correctement le sens de synchronisation.

###### Actual Result

Le sens de synchronisation est confondant.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, our translations are handled on CrowdIn, you should be able to fix them yourself: https://crowdin.com/project/ankidroid/zh-CN#

**Comment by vintotal** [comment]
Thank you 謝謝 merci!

**Comment by david-allison-1** [comment]
> Thank you 謝謝 merci!

不客气
