### ISSUE TITLE
Expand crash report to note disk free/total reporting

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9097]
- I would send an exception report as we do now even if we are not fully crashing (because of the dialog) and I would expand our crash report to note disk free/total reporting (example code here if we don't already have some around somewhere https://github.com/react-native-device-info/react-native-device-info/blob/7a87ea18dbe4076f063e08b74dbd42bb2a9c3dac/android/src/main/java/com/learnium/RNDeviceInfo/RNDeviceModule.java#L353-L405 - in fact I think we do for collection import / unpack pre-check but this code I just referenced is probably more modern!)

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/9066#issuecomment-854814307_

**Comment by sethbuchinger** [comment]
I would like to take this one on if possible.  I was wondering if this is is just a matter of updating the ACRA report fields or if there is more to it than that?  The TOTAL_MEM_SIZE and AVAILABLE_MEM_SIZE are available in that library.

**Comment by mikehardy** [comment]
I think it's just adding report fields, but storage not mem :-)
Definitely look at the current version of that file just in case - I maintain that library and I don't think there has been any motion in that storage size area for a while but you never know

**Comment by sethbuchinger** [comment]
Ahh, good point on memory vs. storage.  I was confused by the comment "Estimation of the available device memory size based on filesystem stats", but in any event I can check it out.  I'm new to ACRA and was wondering where the crash reports are stored for AnkiDroid, so I could check them out.  Unless there is a way to output it locally?

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/wiki/Crash-Reports#developing--testing-acra-functionality may be helpful (lists a free to access DEV instance). You can use the file explorer to browse `/data` for an ACRA report, but I haven't done so myself.

https://github.com/ankidroid/Anki-Android/pull/8301 may also be useful context

**Comment by sethbuchinger** [comment]
Thanks!  I will look through that info

**Comment by mikehardy** [comment]
Note: if you're in ACRA-land already, you might take a look at #7805 / #9779 - one thing about changing the initialization style is that while the wiki page I wrote up about ACRA testing does work, and should be used for final testing, you'll see in the initialization work where you can grab hold of how ACRA does reporting and maybe for testing you can have it dump to a file or send you a mail or post to your own server (that sounds silly but it's kind of easy to set up a temporary node/express server or firebase function or whatever these days :) - so who knows). Anyway, they are *related* but not dependent, just offering that in case it makes testing actually easier, not to send you down a rabbit hole. Cheers

**Comment by sethbuchinger** [comment]
Few questions on this one.  

1) I was able to get the FREE/TOTAL storage to write to the ACRA report.  The first approach was enabling TOTAL_MEM_SIZE and AVAILABLE_MEM_SIZE parameters in the ACRA Library.  Since there was some question over whether this was memory (RAM) vs. storage, I decided to also write a new method to create CUSTOM FIELDS in the ACRA report.  As it turns out, both values matched (there is a slight error between the "FREE" reporting.  I'm haven't dug into how the ACRA library is querying the memory size vs how I implemented it).  So the assumption is that the ACRA parameters are actually storage. The simpler solution would be to just enable the parameters in the ACRA report, but wanted to get some feedback.  


<img width="662" alt="Screen Shot 2021-12-05 at 6 41 30 PM" src="https://user-images.githubusercontent.com/65492746/144768896-da0397a6-8f9a-41b1-8fe0-de12b793e093.png">

2) Do we also need to proceed for SD storage space or are users not allowed to access SD storage with the app?

Thanks for your feedback!

**Comment by mikehardy** [comment]
Oh interesting - go upstream then, less code to maintain is a fabulous thing, and the ACRA library is easy to post PRs to if there is something to the discrepancy you saw, the maintainer there is fast + professional in maintainence

**Comment by mikehardy** [comment]
Looks like current idea is to use the built-in ACRA parameters for free mem / total mem, and to investigate if there is any method for external storage as well (if not, might be best to post a PR to ACRA, as mentioned - it's a great library to work on, if you propose a sensible PR it will be merged...)

**Comment by mrudultora** [comment]
Unable to see a PR related to above discussions. @sethbuchinger are you still working on it?

**Comment by dae** [comment]
If nobody is has time to implement this in the near future, should we keep it around?

**Comment by mikehardy** [comment]
agreed - had more value in run up to storage migration but didn't get it before then, and not a ton of value besides that - android is pretty good about warning users when they run low on space and storage is managed semi-dynamically by operating system with cloud storage these days anyway so the values aren't even static over time (so even if we had the info, it may not be actionable as the operating system could purge things that have copies in the cloud in response to pressure...)
