### ISSUE TITLE
Feature Request: Support for external (in /collection.media) javascript files

### ISSUE THREAD

**Issue by brainexcerpts** [ankidroid/Anki-Android#9098]
I was trying to get automatic syntax highlighting in Ankidroid using an offline version of https://highlightjs.org saved in my /collection.media folder on my desktop app. This trick works for the Desktop version but seems to not be allowed on Ankidroid:
https://www.reddit.com/r/Anki/comments/e005jx/load_js_functions_in_external_file/

Some kind of support for Javascript files could be very powerful for all sorts of cool addons IMHO.

**Comment by kleinerpirat** [comment]
This is already possible since 2.15 with the following PR https://github.com/ankidroid/Anki-Android/pull/7764.

Because that feature was implemented by @hgiesel, the author of the add-on [Closet](https://ankiweb.net/shared/info/272311064), when the method stops working one day, it is best to take a look at the way it is handled there: closet/anki/web/[user.js](https://github.com/hgiesel/closet/blob/766b4233f641725ff018cba72aba1ed736451fd7/anki/web/user.js#L6-L32)

---
Here is a general template you could use for an asynchronous import. I included two example files (`_popper.min.js` and `_pulltorefresh.umd.min.js`) that would be located in collection.media - to better illustrate how it works:

```
function getAnkiPrefix() {
    return globalThis.ankiPlatform === "desktop" ?
        "" :
        globalThis.AnkiDroidJS ?
        "https://appassets.androidplatform.net" :
        "."
}

var files = [{
        name: "Popper",
        url: "_popper.min.js",
        init: null
    },
    {
        name: "PTR",
        url: "_pulltorefresh.umd.min.js",
        init: initPTR
    },
]

if (!globalThis.ExternalScriptsLoaded) {
    for (file of files) {
        loadScript(file)
    }
    // guard to prevent further imports on Desktop & AnkiMobile
    globalThis.ExternalScriptsLoaded = true
}

async function loadScript(file) {
    var scriptPromise = import (`${getAnkiPrefix()}/${file.url}`)
    scriptPromise
        .then(() => {
                console.log(`Loaded ${file.name}.`)
                if (file.init) file.init()
            },
            (error) => console.log(`An error occured while loading ${file.name}:`, error)
        )
        .catch((error) =>
            console.log(`An error occured while executing ${file.name}:`, error)
        );

    if (globalThis.onUpdateHook) {
        onUpdateHook.push(() => scriptPromise)
    }
}
```

**Comment by mikehardy** [comment]
Oh thank you so much @kleinerpirat - I have not had the time to respond to this yet, and your comment is :100: !

**Comment by santiyounger** [comment]
> closet/anki/web/[user.js](https://github.com/hgiesel/closet/blob/766b4233f641725ff018cba72aba1ed736451fd7/anki/web/user.js#L6-L32)

Hey thanks a lot for sharing this info. I've been looking all over to use an external .js file to work with Anki


I tried the code you provided above, but I it didn't work. I followed your advice to look for the closet addon's code in user.js

this is it:


```js
function closetUserLogic(closet, preset, chooseMemory) {
    $$editableCode;
    return output;
}

var getAnkiPrefix = () =>
    globalThis.ankiPlatform === "desktop"
        ? ""
        : globalThis.AnkiDroidJS
        ? "https://appassets.androidplatform.net"
        : ".";

var closetPromise = import(`${getAnkiPrefix()}/__closet-$$version.js`);
closetPromise
    .then(
        ({ closet }) =>
            closet.template.anki.initialize(
                closet,
                closetUserLogic,
                "$$cardType",
                "$$tagsFull",
                "$$side",
            ),
        (error) => console.log("An error occured while loading Closet:", error),
    )
    .catch((error) =>
        console.log("An error occured while executing Closet:", error),
    );

if (globalThis.onUpdateHook) {
    onUpdateHook.push(() => closetPromise);
}
```

unfortunately I'm a beginner and don't really know how to modify that code to link to my local .js file in my Anki media folder.


I'm also assuming this code goes straight into (in my case) the back template of my anki card, but correct me if I'm wrong


Really appreciate any tips 

Thanks!

**Comment by YellowOnion** [comment]
Why can't `<script src="_blah.js" />` just work like it does on desktop? 

I hate having to copy and paste this gross huck of code in to every template just to get imports to work.

What happened to DRY?

**Comment by oleg-work** [comment]
What worked for me in `Desktop Anki -> card type -> front template`:

```html
<script>
  function getAnkiPrefix() {
    return globalThis.AnkiDroidJS
      ? "https://appassets.androidplatform.net/"
      : ""
  }
  var injectScript = (src) => {
      return new Promise((resolve, reject) => {
          const script = document.createElement('script');
          script.src = src;
          script.async = true;
          script.onload = resolve;
          script.onerror = reject;
          document.head.appendChild(script);
      });
    };
  (async () => {
      if (typeof hljs === "undefined") {
          var src = `${getAnkiPrefix()}_highlight.min.js`
          await injectScript(src);
      }
      document.querySelectorAll("pre code").forEach(el => {
          hljs.highlightElement(el);
      });
  })();
</script>

{{Front}}
```

Tested on macos and ankidroid.
