### ISSUE TITLE
Negative card count values displayed.

### ISSUE THREAD

**Issue by terrywallwork** [ankidroid/Anki-Android#9100]
Negative card count displayed for green counter number. See screenshot.

Also included is deck causing the issue.
[TerryWallwork_JLPT_Words_Grammar-20210611153043.zip](https://github.com/ankidroid/Anki-Android/files/6639147/TerryWallwork_JLPT_Words_Grammar-20210611153043.zip)

Latest version I cant check as wont run but reporting anyway in case was carried to 2.15.x

AnkiDroid Version = 2.14.6

Android Version = 8.0.0

ACRA UUID = 2153dce3-3fb1-466e-802c-7fd658117dc0

Scheduler = std

Crash Reports Enabled = true

![Screenshot_20210611-152332](https://user-images.githubusercontent.com/19387982/121701990-606e2300-cac9-11eb-93c6-3c19bcb6ac72.png)

**Comment by mikehardy** [comment]
Hi there!

> AnkiDroid Version = 2.14.6

Can you verify this still happens in 2.15.4 (current stable?) You assert it won't run, that's not credible, we have more than a million users on it? If it won't run, that's a separate much more important issue we must solve first

**Comment by terrywallwork** [comment]
Im not able to consistently reproduce, as it has never happened before.  I cant test in 2.15.4 as when I hold down on a deck and select custom study, and select Modify today's New Card Limit and add  card or Modify Review Limit and add, the app closes with no error report screen displayed, even though I have always report selected. Also when cards are displayed it is display very slowly compared to 2.14.6.

**Comment by david-allison-1** [comment]
@terrywallwork Works for me. Could you add a separate issue for this? We weren't aware and we'll get it sorted.

If you're fine with sharing your data publicly, could you zip up the file: `AnkiDroid/collection.anki2` and post it along with the "Bug" template

If you want to keep your data private, publish the issue and we'll go from there.

**Comment by terrywallwork** [comment]
Im not sure what bug template is but here is the requested file.

[collection.anki2.zip](https://github.com/ankidroid/Anki-Android/files/6641764/collection.anki2.zip)

**Comment by mikehardy** [comment]
@terrywallwork the bug template is essentially asking for a paste of the debug info from the advanced settings screen in ankidroid - it gives us versions of everything and that usually helps us pin down an issue: https://docs.ankidroid.org/help.html#_support

**Comment by terrywallwork** [comment]
AnkiDroid Version = 2.14.6

Android Version = 8.0.0

ACRA UUID = 2153dce3-3fb1-466e-802c-7fd658117dc0

Scheduler = std

Crash Reports Enabled = true

**Comment by mikehardy** [comment]
Note for future people: AnkiDroid is migrating libanki (which includes the scheduler) to a new style of use where instead of porting the original Python to Java, we are wrapping the Rust library that AnkiDesktop uses now. Resolution of this issue will require understanding the upstream issue in their Rust code, and fixing it there. PRs to AnkiDroid's java implementation of libanki are not the desired fix at the moment.
