### ISSUE TITLE
Feature request: Make reviewing cards a default action/ auto review

### ISSUE THREAD

**Issue by makkaroni470** [ankidroid/Anki-Android#9102]
When learning we should make use of the laziness of humans. Usually we like to be passive, this tactic is deployed against us by tech companies e.g. by auto loading new videos in YouTube or Facebook. We should use this effect for our better. When reviewing cards it should take as little action as possible.

Currently in AnkiDroid there is the option to automatically reveal and rate the cards "again" after a set amount of seconds. This can be further improved to reduce interventions by the user:
1. Rating the card "good" is much more common than rating the cards "again". Therefore this should be changed or the user should be given the choice.
2. Not all cards take the same amount of time, and sometimes you to want to think a little longer or reread the answer. Therefore a button should be added to be able to pause the auto feature. (Next to the flag button). Without this the auto review feature is often more cumbersome to use than it should be.

I got this idea from watching a video by the AnKing: https://www.youtube.com/watch?v=gNq4Drmliac
These two suggested features are available on the desktop app via his add-on, or on the iOS App of Anki. In the video he shows both.
About the default effect: https://en.wikipedia.org/wiki/Default_effect
Another thing I've discovered is that it is less stressful to learn, if you don't skip the timer even if you know the answer before the time runs up. It helps to keep a constant pace and not burn out. It reminds me of practicing piano with a metronome.

**Comment by mikehardy** [comment]
We like this so much we've almost finished implementing it ;-) #8281 - just needs a little work and it'll be in
