### ISSUE TITLE
Allow non-SSL connections in RFC1918 reserved / local subnet space

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#9103]
Requested by @anadi in #5423 and it seems reasonable. I'm open to merging a PR for this if someone wants to take it on

---------

Mmm - I had not considered the local network case much. That's an interesting point. 
There is an RFC for internal only IP space that defines all the ranges 

https://datatracker.ietf.org/doc/html/rfc1918#section-3

```
     10.0.0.0        -   10.255.255.255  (10/8 prefix)
     172.16.0.0      -   172.31.255.255  (172.16/12 prefix)
     192.168.0.0     -   192.168.255.255 (192.168/16 prefix)
```

I suppose we could add an exception for non-SSL connections to those somehow? I have not investigated this, it may not be feasible but regardless of further investigation the first question is - @anadi - would allowing non-SSL connections to custom sync servers in those network ranges satisfy your use case?

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/5423#issuecomment-856299731_

**Comment by prateek-singh-3212** [comment]
I would like to work on this. TBH I don't know how to implement but will learn and implement this.

**Comment by mikehardy** [comment]
It's going to be in here - https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/res/xml/network_security_config.xml

**Comment by mikehardy** [comment]
https://github.com/ankidroid/Anki-Android/blob/e09629ab0d97ff171d68f83ea66842fa6c2a4eb7/AnkiDroid/src/main/AndroidManifest.xml#L66

**Comment by prateek-singh-3212** [comment]
> would allowing non-SSL connections to custom sync servers in those network ranges satisfy your use case?

@mikehardy  should I go with this ?

**Comment by mikehardy** [comment]
Sure, have at it :-)

**Comment by mikehardy** [comment]
Unfortunately not technically possible per discussion on related PR #9149 - closing as can't fix
