### ISSUE TITLE
ActivityStartupUnderBackupTest: Improve documentation

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9112]
TODO: Improve the unit test documentation.

A user should know:

To fix a test failure, add the following to the start of `onCreate`
```
        if (showedActivityFailedScreen(savedInstanceState)) {
            return;
        }
```

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/9048#discussion_r652902854_

**Comment by vinishhub** [comment]
I would like to work on this

**Comment by ppavankumar727** [comment]
Can I work on this issue?

**Comment by david-allison-1** [comment]
Sure!

**Comment by ppavankumar727** [comment]
Can I get brief info, I tried to add the lines to the onCreate method of the Anki Activity 
![2021-06-18 08_05_38-Anki-Android – AnkiActivity java  Anki-Android AnkiDroid](https://user-images.githubusercontent.com/61464862/122498075-1c6ca800-d00c-11eb-8f9e-c05e26ab969f.png)

**Comment by umang-sinha** [comment]
is this resolved? If not, I would like to take this up

**Comment by mikehardy** [comment]
It appears the currently-connected PR does not resolve the issue and is dormant for a couple weeks. I think this is ok to work on it if you have time :muscle:

**Comment by umang-sinha** [comment]
Alright! I'll start working on it then

**Comment by tomorekoya** [comment]
Hey, guys. So this looks like it's still not fixed. If no one is working on this at the moment, I'd like to try my hand at it.

**Comment by tomorekoya** [comment]
Should this documentation go into every test file, a particular test file, or the wiki?

**Comment by mikehardy** [comment]
I think improving it on the wiki is actually best if documentation is the answer

I would only alter actual code if there was some way to enforce it (like how the `@CallSuper` annotation works, or with some sort of unit test assertion or similar) - a custom lint rule could probably do it as well

**Comment by david-allison-1** [comment]
> Should this documentation go into every test file, a particular test file, or the wiki?

If a new activity is created without the code in the OP, then the following test will fail

https://github.com/ankidroid/Anki-Android/blob/9d12f5d5b06f6377b073a1530189f69f658774fd/AnkiDroid/src/test/java/com/ichi2/anki/ActivityStartupUnderBackupTest.java#L73-L93

The test partially describes the problem, but we can do better, especially explaining how to fix the issue.

**Comment by tomorekoya** [comment]
Ok. I guess the most obvious place for it would be there, then. Thanks.
