### ISSUE TITLE
Card scrolls in wrong direction

### ISSUE THREAD

**Issue by MouseAndKeyboard** [ankidroid/Anki-Android#9113]
During reviews on mobile:

I have some long cards which require me to scroll down to see their close deletions. 
My issue is that when I try to swipe up or down on one of the cards, it's as if there's another finger also swiping in the opposite direction.

I'm able to scroll down if I very slowly swipe up ("fighting against") the opposite scroll direction.

For me: swiping down should correspond to scrolling up.

This bug hasn't always existed, but it has for at least the past month.

Version: 2.15.4
Phone: Motorola g5

**Comment by mikehardy** [comment]
Hi there! I wonder if you are on Android 8? If you are, we had to disable hardware rendering on Android 8 to work around a serious problem with the reviewer that happened to some people. On the other hand, this meant that scrolling behavior for complex cards was affected for some other people.

If you are on Android 8, you might try going into settings --> advanced, and making sure hardware render is not disabled (you will have to change the setting for Android 8 as we default to disabling it for that version). Then  you can try the reviewer again to see if scroll works. If scroll works, *and* you have all the reviewer answer buttons present then you should be all set

**Comment by mikehardy** [comment]
no feedback, closing

**Comment by NicolasMICAUX** [comment]
> Hi there! I wonder if you are on Android 8? If you are, we had to disable hardware rendering on Android 8 to work around a serious problem with the reviewer that happened to some people. On the other hand, this meant that scrolling behavior for complex cards was affected for some other people.
> 
> If you are on Android 8, you might try going into settings --> advanced, and making sure hardware render is not disabled (you will have to change the setting for Android 8 as we default to disabling it for that version). Then you can try the reviewer again to see if scroll works. If scroll works, _and_ you have all the reviewer answer buttons present then you should be all set

This solve it for me, with same issue
