### ISSUE TITLE
Keep the original image file name when it's attached

### ISSUE THREAD

**Issue by BrayanDSO** [ankidroid/Anki-Android#9116]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to use the same image in multiple cards. If I know the image file name, I can just type `<img src="imageFileName.extension">`. 

The problem: When I attach an image with AnkiDroid, it changes the image file name to something like "img9843278434234908", so it's difficult to use my image again.

**Describe the solution you'd like**
AnkiDroid keeping the original file name, like the Anki Desktop version does.

**Additional context**
I believe it's somewhat related to #5192

**Comment by Akshay0701** [comment]
That's right Anki Desktop does save images with their original names, 

Anki Desktop work like this ->
image file name is not already present it simply include that image file with its original name example `sample.png`
and if file name is already present in collection then anki add unique code to original name like this `sample-1ac0415bf8b772feb31e7ce8148cdd3210056d5e.png`

**Comment by BrayanDSO** [comment]
Since there isn't any update since this issue was posted, I believe this is still a problem

**Comment by BrayanDSO** [comment]
Based on 2.1.16alpha42, this is what I got:

The method which handles selected files is [handleSelectImageIntent](https://github.com/ankidroid/Anki-Android/blob/v2.16alpha42/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java#L435). It gets the filename correctly, but changes it when running [internalizeUri](https://github.com/ankidroid/Anki-Android/blob/v2.16alpha42/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java#L451).

[internalizeUri](https://github.com/ankidroid/Anki-Android/blob/v2.16alpha42/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java#L451) changes the filename when making a cache image copy with [createNewCacheImageFile](https://github.com/ankidroid/Anki-Android/blob/v2.16alpha42/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java#L499)

To keep the filename, it would be necessary to change [createNewCacheImageFile](https://github.com/ankidroid/Anki-Android/blob/v2.16alpha42/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java#L295) to something like:

```java
private File createNewCacheImageFile(@NonNull String filename) throws IOException {
        File newImage = new File(mAnkiCacheDirectory, filename); 
        return newImage;
    }
// I'm new to Java, suggestions are welcome
```
or create a new method to be used at [internalizeUri](https://github.com/ankidroid/Anki-Android/blob/v2.16alpha42/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicImageFieldController.java#L451) (which probably is better to avoid breaking other places which uses createNewCacheImageFile). 

The only caveat with this method change would be drawings file names, which would change from the current `imgRandomNumberSequence.extension` pattern to `unixtimestamp.extension`.

My **1st doubt** is which approach should be followed to naming drawings, since they aren't on Anki Desktop.
- Keep using `imgRandomNumberSequence.extension`?
- `unixtimestamp.extension`?
- Some new pattern like `draw-RandomNumberSequence.extension`?
- Whatever?
- Something else?

---
Then, the second step would be checking if a media with that name already exists. 

Anki desktop does with this [function](https://github.com/ankitects/anki/blob/2.1.49/rslib/src/media/files.rs#L163).
If new file, just add; if has the same filename and hash, do nothing; and if filename is equal but files are different, add its hash to the filename, like `file-checksum.extension`

Ankidroid does it with [writeData](https://github.com/ankidroid/Anki-Android/blob/v2.16alpha42/AnkiDroid/src/main/java/com/ichi2/libanki/Media.java#L257). The main difference about its behavior it the filename pattern being `file (index).extension` when there are 2 or more file with the same name.

My **2nd doubt** is why the pattern difference? I guess it's just lack of updating, since that part were added 8 years ago, but let me know if is there any specific reason. It should be updated to keep up with Anki Desktop?

---
Finally, ankidroid only handles **adding** media with same names. If two names are equal, the new one will have a index correctly added to its name. But the field `<img>` tag isn't updated, keeping the old name, since `<img>` tag and media adding are 2 separated steps. I'm still working out how to fix this. If anyone has any tips, let me know

**Comment by mikehardy** [comment]
Hey @BrayanDSO solving your own issue from nearly a year ago, nice one!! :-)

**Comment by BrayanDSO** [comment]
Fixing this is what made I start contributing to AnkiDroid, since attaching images is part of my workflow. 

Back then when I created the issue, I hadn't thought it would be this easy to join a community and start pushing some bits of code. I'm happy I tried to look further into it and started contributing
