### ISSUE TITLE
Make it harder to reduce the number of reviews or new cards

### ISSUE THREAD

**Issue by AlexApps99** [ankidroid/Anki-Android#9117]
**Is your feature request related to a problem? Please describe.**
When I'm studying, sometimes I'm feeling lazy or don't have enough self control, so I will go into `Custom study` and reduce the number of new cards or review cards to save time.
Obviously, this is detrimental to my learning and as such I would like it to be *harder* to reduce the number of review or new cards.

**Describe the solution you'd like**
If the number of cards is being reduced, some kind of popup saying "Are you sure you want to do that? This will have a negative impact on your learning" or something to that effect.
It doesn't have to be so strongly worded but it might help me to stick to my targets

**Describe alternatives you've considered**
A setting to disable reduction of new/review cards, so you can only increase the number.

**Comment by mikehardy** [comment]
Hi there! This would deviate from upstream, if Anki Desktop implements a feature like this we will follow
https://forums.ankiweb.net
