### ISSUE TITLE
HTML mock-up of AnkiDroid screen for onboarding

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#9129]
This issue track a specific feature of the onboarding screens: #9092.

The goal is to create HTML (+css, no JS if possible) version of multiple important screen of the app. DeckPicker, reviewer, browser, stats, note editor. Those screens will be shown during onboarding with explanation text to illustrate what the user will be able to do with ankidroid.

Here is the reason why we have this goal. We first thought that the slides in the onboarding screen would contain screenshot of the app. The first version of the PR by @ShridharGoel used the same screenshot than the one of the app store. While reviewing the PR, we realized that this led to quite a lot of problem:
* screenshots are in English only. This is not inclusive at all and not really helpful for the important part of the user base in non-us country. On the contrary, an html page can have some template and we can reuse the already existing string ressources in it.
*  screenshot requires a lot of extra work each time we update the interface. That would be worse if we take screenshot in all languages. On the contrary, mock-up that only emphasis the important point without showing the exact interface can be kept longer (the idea here is to present the app, not to teach exactly how to do something. So it's fine if the image is not perfect copy of reality)
* screenshot are heavy. @mikehardy have done a lot of work if I remember correctly to keep the app as small as possible. This is important where internet is expansive, for old phone with little memory, etc... using bitmap images would be a huge increase in app size that is not acceptable given that each image will be seen once (or at most a very few time if they decide to replay the onboarding)

SVG would potentially be acceptable substitute. But it seems that to mock-up a UI, while allowing arbitrary string inside, and adapting to the user phone size, and potentially to night mode, html is more adapted.

The main assignee is @ShridharGoel, however other people may have relevant idea or experience in this particular topic. While @ShridharGoel is in charge of creating the library for onboarding users and showing slide, it's totally fine to share the work of creating each images if there is a CSS guru that is available and want to help

**Comment by prateek-singh-3212** [comment]
I would like to take this issue.

**Comment by Arthur-Milchior** [comment]
I'll repeat what I wrote on discord. 
You should start with a single window, select one from the screenshot of  https://github.com/ankidroid/Anki-Android/pull/9092
If you speak a non-English language, do the page in this language. Then abstract the page and replace text by a templating system. This way, if there is anything that is forgotten to be localized, I'll notice it (unless your foreign language of choice is French). 
Once we are sure we found the correct way to incorporate html in ankidroid, we can document it and create the other html page
