### ISSUE TITLE
[Bug] CSS Style empty cards

### ISSUE THREAD

**Issue by lyaricci** [ankidroid/Anki-Android#9131]
When styling cards on "CSS style", they don't appear on "Card Browser".
The solution I found is style everything on every field of a card.

###### On CSS style

![Screenshot_2021-06-22-00-18-39-580_com ichi2 anki](https://user-images.githubusercontent.com/85897445/122858436-a52b6280-d2f0-11eb-886a-9abe177523ec.jpg)

###### Result
![IMG_20210622_002216](https://user-images.githubusercontent.com/85897445/122858504-c0966d80-d2f0-11eb-9920-498887302d1b.jpg)

###### Styling on fields
![Screenshot_2021-06-22-00-20-04-801_com ichi2 anki](https://user-images.githubusercontent.com/85897445/122858645-fcc9ce00-d2f0-11eb-9ded-38b598953997.jpg)

###### Result (as it should)

![IMG_20210622_003102](https://user-images.githubusercontent.com/85897445/122858733-22ef6e00-d2f1-11eb-8172-38db33a62e33.jpg)

###### Debug info
AnkiDroid Version = 2.15.4

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi Note 7

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi Note 7 Build/QKQ1.190910.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.101 Mobile Safari/537.36

ACRA UUID = c0e7be85-6aa3-4ffb-9f3f-6d5677dacf36

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, what does Anki Desktop show here?
