### ISSUE TITLE
[Bug] \overline is not displayed correctly on Samsung Tablet - Android 11

### ISSUE THREAD

**Issue by megadix** [ankidroid/Anki-Android#9146]
UPDATE: fixed sample source code

###### Reproduction Steps

1. enter a MathJax formula using `\overline`
2. preview or study card

Sample source code:

```html
Does not render correctly on AnkiDroid ( \overline is not displayed )<br><br>
\(\overline{(A \cap B)} = \overline{A} \cup \overline{B}\)<br>
\(\overline{(A \cup B)} = \overline{A} \cap \overline{B}\)<br><br>
Fallback:<br><br>
\((A \cap B)^c = {A}^c \cup B^c\)<br>\((A \cup B)^c = A^c \cap B^c\)
```

###### Expected Result

This code renders correctly on my phone (Huawei Honor 8 - Android 7)

![AnkiDroid-phone-ok](https://user-images.githubusercontent.com/1434231/123392847-cbc1f580-d59d-11eb-8cc6-8b04c21b7ec9.png)

###### Actual Result

This is the rendering on Samsung S6 Lite (Android 11)

![AnkiDroid-Samsung-S6-KO](https://user-images.githubusercontent.com/1434231/123392973-f0b66880-d59d-11eb-8315-f79c5db02582.png)

###### Debug info

```
AnkiDroid Version = 2.15.4
Android Version = 11
Manufacturer = samsung
Model = SM-P610
Hardware = exynos9611
Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-P610 Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.101 Safari/537.36
ACRA UUID = e7eca83f-9cc1-4d4c-ad7b-8837ecfb9533
Scheduler = std2
Crash Reports Enabled = true
DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Can you search the issues list for other mathjax issues + samsung? I believe we have had this problem before and I think it might just be a subtle line width issue, like perhaps if you styled the formula to have larger text perhaps it would show up?

Either way, this may not be something we can handle other than via some config tweak. We are using Mathjax libraries to render the mathjax and that's an external project - they may have something in their issue tracker as well?

:thinking:

**Comment by david-allison-1** [comment]
Hi, thanks, likely related to #9002

Are both versions on AnkiDroid 2.15, as we changed the MathJax rendering engine in this release?

**Comment by megadix** [comment]
Hi, and thank you for the very quick response!

Yes I've searched for Samsung Issues, but I thought it was something different from #7848 and/or #9002

Since both devices (Phone with Android 7 vs Samsung Tablet with Android 11) use the same AnkiDroid version `2.15.4`, I think it might be something in the WebView on Samsung or Android 11, who knows...

I will try some workaround using CSS (or whatever) to try to uniform across Windows app and Android, I'm updating this is issue if I find some acceptable solution.

Thank you for your support,
Dimitri

**Comment by gjgress** [comment]
I am also experiencing this issue on my Samsung Galaxy Note 9. I am on the latest AnkiDroid build as well. Happy to provide more details upon request.

Here's my debug info:
```
AnkiDroid Version = 2.15.4

Android Version = 10

Manufacturer = samsung

Model = SM-N960U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; SM-N960U Build/QP1A.190711.020; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.181 Mobile Safari/537.36

ACRA UUID = 28ca630e-fbf3-48b1-89c7-68b60c11a10a

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by YuvMilo** [comment]
Hey, I'm still searching for solutions! 
This issue persists with my Pixel 6.
There seems to have a solution to a similar problem here:
https://github.com/mathjax/MathJax/issues/2701

**Comment by roscherk** [comment]
Same issue on Asus Zenfone 9.
Code: `Test&nbsp;<anki-mathjax>\overline{\text{test}}_r(a) = {{c1::\{x \in X : \rho(x, a) &lt; r\} }}</anki-mathjax>`
Output: 
![image](https://user-images.githubusercontent.com/70962699/207921931-3b2793ba-fac0-4bfb-97b3-351449f87338.png)

Debug info:
```
AnkiDroid Version = 2.15.6

Android Version = 12

Manufacturer = asus

Model = ASUS_AI2202

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 12; ASUS_AI2202 Build/SKQ1.220406.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.79 Mobile Safari/537.36

ACRA UUID = 1bed530d-9b0d-4c86-9b4c-d5902203b3fb

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by mikehardy** [comment]
Please test on the new alpha releases to see if it still happens there, mathjax support has seen quite a few changes since the last public release - https://github.com/ankidroid/Anki-Android/releases

**Comment by roscherk** [comment]
Works just fine on [2.16alpha91](https://github.com/ankidroid/Anki-Android/releases/tag/v2.16alpha91), thank you!

**Comment by fimmind** [comment]
Hi! As suggested in [this comment](https://github.com/mathjax/MathJax/issues/2701#issuecomment-859594360), an alternate way to solve the problem is by adding the following snippet to the CSS: 
```css
mjx-stretchy-h > mjx-ext { overflow: clip visible ! important; }
```

Adding the code to the note noteplate's CSS solved the problem on my tablet (Android 13, AnkiDroid 2.15.6)
