### ISSUE TITLE
Overflow issue

### ISSUE THREAD

**Issue by khanguyenwk** [ankidroid/Anki-Android#9167]
Hello everyone, thank you so much for very useful app. I use it everyday. 
Since I use a plug in to automatically add content to note (from dictionary), I meet an overflow issue: I have to scroll to see the full content, it's not optimized for phone screen

![Screenshot_20210629-211546_AnkiDroid.jpg](https://user-images.githubusercontent.com/42679589/123892780-6c8d2800-d985-11eb-8636-dc5c7b768531.jpg)

I have to scroll or zoom out to see the full content of that note

![Screenshot_20210629-211600_AnkiDroid.jpg](https://user-images.githubusercontent.com/42679589/123892826-7f076180-d985-11eb-9dd3-323e73ae0146.jpg)

I realize that while filling the field with content, the plug-in add a css code and it's the main reason that make the display doesn't fit the phone screen. 

![Screenshot_20210629-211632_AnkiDroid.jpg](https://user-images.githubusercontent.com/42679589/123892922-a8c08880-d985-11eb-8e3d-c7db18d65eef.jpg)

Is there any way that I can fix it?
Thank you so much

**Comment by david-allison-1** [comment]
Hi, this looks like an issue with your dictionary.

But, we might be able to fix this: Scroll down and select `Cards` (under `Tags`) and you can add CSS, or HTML to affect how the content is displayed. Some of this will be able to either fix the CSS, or use JavaScript/HTML to fix the scrolling.

https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection may be helpful if you're having trouble with the HTML creation.

**Comment by khanguyenwk** [comment]
> Hi, this looks like an issue with your plugin, and you should contact the author.
> 
> But, we might be able to fix this: Scroll down and select `Cards` (under `Tags`) and you can add CSS, or HTML to affect how the content is displayed. Some of this will be able to either fix the CSS, or use JavaScript/HTML to fix the scrolling.
> 
> https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection may be helpful if you're having trouble with the HTML creation.

Thank you so much fo your help David
I don't know about css or html, do you recommend any code or any way to add to the 'Card' to disable this the overflow issue?

**Comment by david-allison-1** [comment]
Sorry, I don't have the time to help right now. Please go to `Help - Community` inside the app, and someone on one of our communities should be able to help out

**Comment by mikehardy** [comment]
This definitely looks like a "your dictionary generates content that is not quite right / your dictionary needs to examine the issue" type problem though, anything you do with CSS/HTML in your AnkiDroid will fix your issue but there may be lots and lots of people suffering with the same problem from content generated by whatever dictionary that is

**Comment by mikehardy** [comment]
This will not result in a change to our code, so I'm going to close this
