### ISSUE TITLE
Paste as PNG if alpha channel exists

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9171]
I think that (auto-switch to PNG if there is an alpha channel) for a follow-up PR. I think this is an area where starting by deferring to users' choice  and implementing the upstream feature is a reasonable start

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/9080#issuecomment-871019475_

**Comment by Akshay0701** [comment]
only png and gif support alpha channel in it and we already processing it by our default checks,
So, David do we really need to check for the alpha/transparency channel in the image file?

**Comment by david-allison-1** [comment]
My understanding from the requirements (https://github.com/ankidroid/Anki-Android/pull/9080#discussion_r660166058):

* Anki Mobile will always use `.jpg`
* Unless the file has an alpha channel, in which case it will use `.png`

We currently (I believe):

* convert a transparent gif to a jpg 
  * (we need to ask what we want to do about animations here)
* Do not convert a non-transparent png to a jpg

**Comment by dae** [comment]
If AnkiMobile detects a gif on the clipboard, it keeps it as a gif, as some users want the animations.
