### ISSUE TITLE
Leech action feature request

### ISSUE THREAD

**Issue by leitz010** [ankidroid/Anki-Android#9186]
**Is your feature request related to a problem? Please describe.**
I often ignore the leech tag, and wish the leech mechanic did more than it currently does. I think it has a lot of potential to help in learning.

**Describe the solution you'd like**
An option under "leech action" to also automatically "reset progress" once the lapse threshold has been reached, and an automatic reset of the lapse count.

**Describe alternatives you've considered**
Other potential automated leech options:
* A set delay of x (editable) days before the word is seen again.
* A leech deck created with all leech cards added to it.

**Additional context**

**Comment by david-allison-1** [comment]
Hi, thanks for the request!

We aim to maintain compatibility with Anki Desktop. Does the feature exist there? We'll only be able to work on this if it'll be implemented

If it doesn't, can you request it: https://forums.ankiweb.net/ and post a link to the thread for tracking?

Best,

David

**Comment by leitz010** [comment]
[Here it is.](https://forums.ankiweb.net/t/leech-action-feature-request/11181?u=leitz010)
