### ISSUE TITLE
Feedback on undo

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#9192]
When you press undo, show a small toast indicating what was undone, confirming that the undo order was sent.

Ideally, you should wait until undo is done succesfuly to show the message.

If you want to go the extra miles, and undo takes more than half a second to succeed, you can show a message confirming that undo was registered. This could occur if a long computation is being done in parallel, such as finding the next card in a big deck

**Comment by Mohaned-Elfeky** [comment]
Can I work on this?

**Comment by Mohaned-Elfeky** [comment]
still searching for solutions
