### ISSUE TITLE
Energy - battery consumption not optimal in background mode.

### ISSUE THREAD

**Issue by sankayop** [ankidroid/Anki-Android#9194]
**Is your feature request related to a problem? Please describe.**
Since i use ankidroid, my smartphone's battery is discharging quite fast. But i never thought of looking at the battery manager. Today i did it.
The result is 23hrs of use in 3 days while practically, i've bee using the app 1hr per day. The rest of the time, the app is in backgd (or at least should have been) or shut down. According to the apps manager, ankidroid was 0 min in backgd. The latter is not normal.
<img src="https://user-images.githubusercontent.com/23059127/124347431-0f8fad00-dbe5-11eb-97bf-78b98653b089.png" width=40% height=40%>

**Describe the solution you'd like**
Enable ankidroid in background when temporarily not used, to reduce its consumption

**Describe alternatives you've considered**
The alternative is the current situation, but not optimal.

**Additional context**
Nothing else to add except the app is amazing.

**Comment by david-allison-1** [comment]
Hi, thanks so much for the report!

Presumably you were using the reviewer when this happened?

Could you go to `help - get help - send troubleshooting report`

Then could you then go to `Settings - Advanced - Copy Debug Info` and paste it here.

This may be related to #9086.

**Comment by sankayop** [comment]
AnkiDroid Version = 2.15.4

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi Note 8

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi Note 8 Build/QQ1B.200105.004; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/74.0.3729.186 Mobile Safari/537.36

ACRA UUID = 3d2112ed-282e-4fa7-ac99-cdc7e32ca2c1

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment]
Hmm - android 10 vs android11 but if you tried the latest alpha (2.16alpha3 at the moment) this may be fixed for you as it will contain the fix from #9086: https://docs.ankidroid.org/#betaTesting

Can you try it? I use it as my main install but you can also try it as a side-by-side install by installing parallel A https://github.com/ankidroid/Anki-Android/releases

**Comment by sankayop** [comment]
@mikehardy, you're right, I just found out it's been a very very long time my os hasn't updated... (reason is it was an alpha release and to update, I have to install a new version of the os... thus no update actually).
I'll first start with this before annoying you guys further.

For my part, if your background energy consumption is working with android11, this issue can be closed.
Sorry for bothering. If necessary, I will reopen the case when I'll be at Android11.

Have a nice evening,

**Comment by mikehardy** [comment]
Oh - what I meant was that you could update the version of ankidroid not your OS, I'm on Android 10 still personally for instance, it's supposed to work!

**Comment by sankayop** [comment]
Ok, my bad.
I just subscribed to the alpha group, waiting for google to provide me the update :)
I'll let you know, thanks.

**Comment by sankayop** [comment]
Ok, I'm using alpha for 4 days now and all looks fine.
Thanks for the guidance!
