### ISSUE TITLE
[Bug] “Press back again to exit”

### ISSUE THREAD

**Issue by apiote** [ankidroid/Anki-Android#9210]
###### Reproduction Steps

1. Open Ankidroid
2. Go back (press back button or do back gesture)

###### Expected Result

Exit app

###### Actual Result

A toast appears “Press back again to exit”

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

###### Explanation

In two latest versions it’s necessary to go back twice before actually exit the app. As far as I have searched, there is no option to disable this behaviour. This is really annoying. Some time ago it even was against the guidelines; I cannot find now the article in Google’s Android manual. Anyway, I cannot find a reason where this would be a good idea.
The only reason I can think of is when opening the app again would be more of a nuisance than going back twice. This is not the case when it comes to Ankidroid.
Moreover, the message “Press back (…)” discriminates against those of us who use navigation gestures—we do not _press_ back. Newer Android versions deprecate the bottom navigation bar.

I do not want You to disable this behaviour completely. You might have had some reason for implementing it which I cannot think of. But please let users disable/customise this behaviour.
At the very least, I want to give You feedback on this—it’s a surprising change (I couldn’t find it in the changelog) and an annoying one.

**Comment by mikehardy** [comment]
I'd take a PR that makes it a preference if you want to post one

The use case that argues for it is one I've experienced a bunch in my house: back button is right next to "Easy" button, and kid sloppy-taps resulting in an exit.

The change to 2-taps to exit was a real win for me.

**Comment by apiote** [comment]
I won’t say no. I get that everybody is a volunteer.
But let me understand that use case, when we’re at it. “Easy” button is shown on the review screen and back-twice is present on main screen. So the case would be: “Easy” button is visible, so we’re on the review screen with an answer visible, back button is tapped instead and takes us back to main screen. We’d have to tap back again to actually exit the app.
Is there something I miss? Are we talking about the same behaviour?

I review with full screen and usually use gestures instead of buttons so I never noticed that.

I noticed that—if it really should—it does not protect from accidental exit. You can tap back once from main screen, which will bring the toast and You‘ll stay on main screen; then You can enter a deck (go to review screen), go back to the main screen. Now when You tap back, it will not show the toast, You’ll exit the app after one tap.

**Comment by mikehardy** [comment]
It works well enough for my child. He understands the Anki interface and knows to hit the decks with reviews to do, so he stays in flow on review even after one back press takes him to deck list

Previously when it booted him out of the app completely he would actually voice his frustration.

I repeat it was a big win in my house.

I repeat I'm happy to merge a PR making it a preference if you want to post one, we're all adults and opinions may differ but I have no interest, it's a win for me, so I'm not motivated to post anything

**Comment by apiote** [comment]
I sounded rude. I’m sorry.

I don’t want to change solution which works for You no matter how it is implemented; I want to give people an option to change it on their devices. You’ve made it clear that this implementation is fine by You.

It works for You and it is You who makes decisions here. I don’t understand the use case but it’s all right, I don’t have to.
I’m not a parent, an educated pedaogue, nor do I fully know the circumstances around Your child voicing frustration, so I won’t comment on that.

I do understand Your position as a maintainer, and the fact that You make decisions which may be based on Your experiences. When I find the time, I will write a patch and post it. Till then I’m grateful that Ankidroid exists and for countless hours sacrificed by volunteers.

You can close this issue if You feel nothing more can and should be said.

**Comment by mikehardy** [comment]
No worries - I think it's fine to leave open in case others want to work on it as well (there is a large crew of volunteers) and if/when a PR comes in I'll merge it. It's a win for me, no question, but my experience with AnkiDroid is that for the same feature there are always people that both love and hate it - it's impossible to please everyone. But then everyone hates that we have all these settings, so really we can't win. I just merge patches ;-)

**Comment by mikehardy** [comment]
Just launched 2.16alph5 which has the related PR merged - https://docs.ankidroid.org/manual.html#betaTesting (explains how to get alphas as well) :rocket:
