### ISSUE TITLE
[Bug] Android 8.0: .ogg cannot be added

### ISSUE THREAD

**Issue by pavreh** [ankidroid/Anki-Android#9225]
.ogg file can be attached to a card in Anki and it plays during review in AnkiDroid but .ogg cannot be attached to a card in AnkiDroid.

###### Reproduction Steps

1. Add note
2. Add audio clip (in a field)
3. LIBRARY
4. Select an .ogg file

###### Expected Result

The line [sound:filename.ogg] is added to the field.

###### Actual Result

The .ogg file is gray and cannot be selected.

###### Debug info
AnkiDroid Version = 2.15.4

Android Version = 8.0.0

Manufacturer = samsung

Model = SM-A320FL

Hardware = samsungexynos7870

Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; SM-A320FL Build/R16NW; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Mobile Safari/537.36

ACRA UUID = 2446e1e8-e861-4aee-a725-c96294a68fa1

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue

Ogg file is supported in according to FAQ.

- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

I have tested it also in 2.16alpha3.

**Comment by david-allison-1** [comment]
Hi, thanks for the report. 

This is likely an issue with your android system not reporting the `ogg` as media.

Could you upload the file and we'll see what we can do

Ref: https://github.com/ankidroid/Anki-Android/blob/fd8fac37e7d38e0aaacc1db4c49c1b3d22803451/AnkiDroid/src/main/java/com/ichi2/anki/multimediacard/fields/BasicAudioClipFieldController.java#L61-L70

Best,

David

**Comment by pavreh** [comment]
Great, there is the file.
[flush__gb_1.zip](https://github.com/ankidroid/Anki-Android/files/6786038/flush__gb_1.zip)

**Comment by david-allison-1** [comment]
Works on my Android 11. Might take a bit of time

**Comment by david-allison-1** [comment]
Just confirming: the `ogg` is on your device, and not from a cloud provider or similar?

**Comment by david-allison-1** [comment]
Reproduced on Android 8.0

![image](https://user-images.githubusercontent.com/62114487/124973006-e925a380-e022-11eb-9672-9e31d1330851.png)

**Comment by david-allison-1** [comment]
Thanks so much for the report.

I've put in a fix for this, it's awaiting review, and I expect that it will be available for 2.16alpha4

**Comment by pavreh** [comment]
Thank you David, it was quick. 
Pavel

**Comment by mikehardy** [comment]
Just launched 2.16alph5 which has the related PR merged - https://docs.ankidroid.org/manual.html#betaTesting (explains how to get alphas as well)
