### ISSUE TITLE
[Bug] Crash when opening statistics

### ISSUE THREAD

**Issue by hydeswag** [ankidroid/Anki-Android#9230]
I have ankidroid 2.15.5beta1
My phone is a google pixel 4a 5g on android 11

I tried restarting my phone and it did nothing. Everything else seems to work fine.

edit : i don't know what happened but now it works? i just got to a new day and it's not crashing but it might happen again once i review cards?

**Comment by david-allison-1** [comment]
Hi, thanks for the report. Could add in "Settings - Advanced - About AnkiDroid - Debug Info" to your post?

**Comment by david-allison-1** [comment]
Likely: https://couchdb.ankidroid.org/acralyzer/_design/acralyzer/index.html#/report-details/cc588ffa-0511-4eba-b1f1-cab6f363fc52

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:354)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
at java.util.concurrent.FutureTask.run(FutureTask.java:271)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:764)
Caused by: java.lang.IndexOutOfBoundsException: Index: 25, Size: 24
at java.util.ArrayList.set(ArrayList.java:453)
at com.ichi2.libanki.stats.Stats.calculateBreakdown(Stats.java:22)
at com.ichi2.anki.stats.ChartBuilder.calcStats(ChartBuilder.java:6)
at com.ichi2.anki.stats.ChartBuilder.renderChart(ChartBuilder.java:1)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackgroundSafe(AnkiStatsTaskHandler.java:10)
at com.ichi2.anki.stats.AnkiStatsTaskHandler$CreateChartTask.doInBackgroundSafe(AnkiStatsTaskHandler.java:1)
at com.ichi2.anki.stats.StatsAsyncTask.doInBackground(StatsAsyncTask.java:2)
at com.ichi2.anki.stats.StatsAsyncTask.doInBackground(StatsAsyncTask.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:333)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
... 4 more
```

**Comment by david-allison-1** [comment]
Likely cause is 7cacb3396a0302898cc17be88af574387ae65636 (https://github.com/ankidroid/Anki-Android/commit/a8a8d92c96f87befc65d71684d2de7541637b1aa on 2.15)

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/blob/a8a8d92c96f87befc65d71684d2de7541637b1aa/AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java#L881-L887

An index of 25 would mean a negative value (totally possible: `-2 % 24 == -2`)

Likely caused by our new timezone code

https://github.com/ankidroid/Anki-Android/blob/00abc059f60fd18ddc9e77d2425436a3cad044ed/AnkiDroid/src/main/java/com/ichi2/libanki/sched/SchedV2.java#L2178-L2187

https://github.com/ankidroid/Anki-Android/blob/7cacb3396a0302898cc17be88af574387ae65636/AnkiDroid/src/main/java/com/ichi2/libanki/stats/Stats.java#L871-L877

**Comment by mikehardy** [comment]
Thanks for the report @hydeswag ! Sorry for the crash - unintended consequence of a different fix where I tried to normalize the hourly breakdown graph by calculating for "all hours in the day", naively thinking that those would, you know, 24 hours ;-) #9200

I'll look into this and repair it. Really appreciate the beta testing and the crash report so this doesn't affect the whole userbase

**Comment by mikehardy** [comment]
From the crash report, 

- "dayOffset" is 4

- "schedVer" is showing up in the crash report as `TRUE`  which was a little confusing. The way it is handled in the code is not as an actual version but as a boolean whether user *wants* v2 scheduler or not. That whole area bears some inspection as it is not v1 vs v2 in future state, with vNext coming, and pluggable schedulers possible in future?

Anyway, confirmed it's on v2 scheduler.

I was actually still on v1 scheduler so I switched my collection to v2 and over the course of my collection's life I have reviews at all hours of the day, so I tried to reproduce the crash and could not. I'm not sure exactly how this happens, still working on reproduction

That said, even without reproduction I think the appropriate change is to mod the hour in the array.set by 24 to make sure it falls in range? I will propose a PR that does the same but I'm not 100% sure on it. I was tempted to just kill all the day offset complication in the hourly breakdown entirely and just generate a midnight to midnight graph but I'm sure I'll make 10 errors if I do that

This is the line I'm thinking of changing by adding a mod 24
https://github.com/ankidroid/Anki-Android/commit/a8a8d92c96f87befc65d71684d2de7541637b1aa#diff-d548123ae3ff64c9f5cc9135edfebdc1032d839e10b47da7d96b77e249217106R893

**Comment by mikehardy** [comment]
@hydeswag I think 2.15.5beta2 should be out on the play store if you could give it a try? I'm reasonably certain I fixed it but I couldn't reproduce it locally, so you are actually our best test case for this one. Would love to hear how it goes. Thanks!

**Comment by hydeswag** [comment]
> @hydeswag I think 2.15.5beta2 should be out on the play store if you could give it a try? I'm reasonably certain I fixed it but I couldn't reproduce it locally, so you are actually our best test case for this one. Would love to hear how it goes. Thanks!

actually it just happened again right now
what's weird is that the statistics are fine the day but I think once it gets to midnight and after, it starts crashing? Yesterday I studied the day and I'm pretty sure my statistics were fine when I looked at them throughout the day but I'm not sure if i looked at them after midnight. I have a feeling that studying after midnight is what triggers it? i have the day set to 7 hours past midnight if that matters

**Comment by david-allison-1** [comment]
Are you sure you're on beta2? No crashes in ACRA for the release yet. 

`Settings - Advanced - About AnkiDroid - Copy Debug Info` to check

**Comment by hydeswag** [comment]
> Are you sure you're on beta2? No crashes in ACRA for the release yet.
> 
> `Settings - Advanced - About AnkiDroid - Copy Debug Info` to check

AnkiDroid Version = 2.15.5beta1

Android Version = 11

Manufacturer = Google

Model = Pixel 4a (5G)

Hardware = bramble

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 4a (5G) Build/RQ3A.210605.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/89.0.4389.105 Mobile Safari/537.36

ACRA UUID = 3d84f6ae-4043-484d-a59e-ac642a2f6454

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by hydeswag** [comment]
oh nvm my bad it's not beta 2, I'll see if it's fixed when i get the update

**Comment by david-allison-1** [comment]
No worries! We've all been there. Give me a shout if it's still an issue

**Comment by hydeswag** [comment]
I tested it on beta2 and it is fixed

**Comment by mikehardy** [comment]
Thanks so much for reporting back. I think that was our last holdup on releasing 2.15.5, it has a ton of fixes I'm looking forward to releasing to the whole userbase so this is great news
