### ISSUE TITLE
[Feature] Add new JavaScript API to bury current card and add tags to current note.

### ISSUE THREAD

**Issue by BilderLoong** [ankidroid/Anki-Android#9231]
**Is your feature request related to a problem? Please describe.**
I want to bury and add tags to cards that have overflowing content in the current mobile device, because it's frustrated to review cards that have overflow content.

**Describe the solution you'd like**
I want to use JavaScript to check whether the current card has overflowing content. If so I want to bury it and tags it, then I can review it on the desktop for a better experience.

**Describe alternatives you've considered**
Able to move notes to other decks can be an alternative for the above bury API.

I have already read the [AnkiDroid Javascript API](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API) but I can't find the API I want.

**Comment by mikehardy** [comment]
My general policy is that within the reviewer, any of the actions we allow via the Java reviewer UI (like, actions from the menu) are things I will support being exposed in the Javascript API, so this works for me as an addition if someone wants to take this up and they don't exist already

**Comment by BilderLoong** [comment]
It will help me a lot if your guys have time to implement this kind of APIs.
Also, very appreciate your guy's hard work.

**Comment by BilderLoong** [comment]
Thank you guys so much!
