### ISSUE TITLE
Use typescript instead of js for API

### ISSUE THREAD

**Issue by nicdard** [ankidroid/Anki-Android#9234]
I would like to work on this feature, but I miss a little bit of context on where to find the js API bindings for example. Also maybe we can move the js code to typescript instead of just and the definition file. Having typescript would allow us also to use openapi specification for example and get typescript types and stubs from a specification either written or generated from java code. Last but not least this would help also documenting the APIs, but it's a proposal that maybe is not even feasable

_Originally posted by @nicdard in https://github.com/ankidroid/Anki-Android/issues/9104#issuecomment-877512822_

**Comment by nicdard** [comment]
Opened by mistake!

**Comment by mikehardy** [comment]
NP - I code typescript professionally though, and strongly prefer it over javascript, if that's of any use as a perspective / way of thinking. Anything that would have us use+support typescript by default vs javascript would be fantastic IMHO.

**Comment by nicdard** [comment]
I changed the title of this and I am gonna reopen it to serve as discussion for typwscript proposal since I have seen that there is some interest. :)
