### ISSUE TITLE
[Bug] Copyright lint check not running

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9242]
https://github.com/ankidroid/Anki-Android/pull/9240#discussion_r667403068

**Comment by david-allison-1** [comment]
Theory: aae98e787f7bcbcd5235d2e273d8ae6593335ffd - if `Anki-Android`  depended on `api` for the checks, then this would have disabled them

**Comment by mikehardy** [comment]
:zap:
