### ISSUE TITLE
App crashes when editing card during review

### ISSUE THREAD

**Issue by jreppnow** [ankidroid/Anki-Android#9262]
Hi, this is occuring since the last update. 

Steps:

1 Start Review of a deck. 
2 After passing some cards, choose to edit one of the cards. 
3 In the edit dialogue, remove some text from a field. 
4 Press the confirm button (checkmark in the top bar). 

Here, the app becomes completely unresponsive and has to be forcefully restarted. 

AnkiDroid Version = 2.15.5

Android Version = 11

Manufacturer = Google

Model = Pixel 5

Hardware = redfin

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 5 Build/RQ3A.210605.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Mobile Safari/537.36

ACRA UUID = 9c23753b-7a98-4c56-979f-6caeb915ffa7

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by jreppnow** [comment]
![Screenshot_20210714-080044](https://user-images.githubusercontent.com/40561502/125571377-947fcaf0-6bb0-4255-a2d1-333f24642fdc.png)

This is the screen you get stuck in.

**Comment by david-allison-1** [comment]
Hi, thanks for the report.

I can't reproduce this (2.16alpha or 2.15.5) 

Could you go to `help - get help - send troubleshooting report`

Could you then zip and upload your collection to GitHub (located at AnkiDroid/collection.anki2)

If your collection contains personal information, please don't upload it and let us know. We'll discuss how to get it privately.

Best,

David

**Comment by david-allison-1** [comment]
While we're diagnosing this, have 2.15.4.Parallel.A, which should still work: https://github.com/ankidroid/Anki-Android/releases/tag/v2.15.4

**Comment by jreppnow** [comment]
Hi, I van upload my collection in the evening (my time, so in 8-10 hours). For the meantime, I wanted to let you knoe that the change went through after I sent the Bug report, and I have also been unable to reproduce the issue since, eben with the same deck.

**Comment by jreppnow** [comment]
I have sent the troubleshooting report referencing this issue in the description. My collection is attached to this comment:

[collection.zip](https://github.com/ankidroid/Anki-Android/files/6814528/collection.zip)
