### ISSUE TITLE
AnkiDroid not working

### ISSUE THREAD

**Issue by asabir123** [ankidroid/Anki-Android#9273]
Hi, 
Whenever I try to sync my flash cards on my Chromebook it says Sync Error: Your anki client is not compatible with the V2 Scheduler.

**Comment by david-allison-1** [comment]
> Hi,
> Whenever I try to sync my flash cards on my Chromebook it says Sync Error: Your anki client is not compatible with the V2 Scheduler.

Hi, `Settings - Advanced - About AnkiDroid - Copy Debug Info`

You're very likely using an old version of AnkiDroid and should update

**Comment by asabir123** [comment]
Hi
This is the debug info:
AnkiDroid Version = 2.8.4 Android Version = 5.0 ACRA UUID = 950c5d9e-70a4-4e03-a676-6553d54f600e

**Comment by asabir123** [comment]
What is the updated version?

**Comment by david-allison-1** [comment]
> What is the updated version?

We're at 2.15.6, which still supports your device

**Comment by asabir123** [comment]
im using a school computer, so playstore is blocked. is there any other alternative way of updating it.

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/releases

**Comment by asabir123** [comment]
ive downloaded all of them but the issue is the same. It says that we have to you use an application on the chrome web store to open the files. I dont know which application can you help me?

**Comment by david-allison-1** [comment]
> ive downloaded all of them but the issue is the same. It says that we have to you use an application on the chrome web store to open the files. I dont know which application can you help me?

You should be able to open the apk directly on the chromebook without an app.

@mikehardy Is it possible for us to update AnkiDroid on the Chrome Web Store at this point?

**Comment by asabir123** [comment]
it says this for all of them:
![image](https://user-images.githubusercontent.com/80747952/125825619-06dc1ad4-6b73-404c-ac7f-dd043a4e2860.png)

**Comment by asabir123** [comment]
have you received a reply from @mikehardy

**Comment by mikehardy** [comment]
> > ive downloaded all of them but the issue is the same. It says that we have to you use an application on the chrome web store to open the files. I dont know which application can you help me?
> 
> You should be able to open the apk directly on the chromebook without an app.
> 
> @mikehardy Is it possible for us to update AnkiDroid on the Chrome Web Store at this point?

No. Publishing apks on Chrome web store appears irretrievably broken from last investigation, none of the binaries in the tool chain work. Only remediation I think is to unpublish it somehow if possible, or update the listing to say it is no longer maintained and the current apk should be installed from play store or releases page

**Comment by asabir123** [comment]
Okay so what should i do?

If AnkiDroid from chrome web store has not been updated, then in the past (a month ago) when i would sync it, it never used to say this.

**Comment by mikehardy** [comment]
You have converted your collection to the v2 scheduler at some point, on some other device, so it is no longer compatible with the older releases.
Convert it back to the v1 scheduler and it should sync

With apologies, there is nothing we can do here, the chrome web store is extraordinarily developer unfriendly in my experience and I can no longer push updates to it. The expectation is that the play store or sideloading is the mechanism to install APKs on chromeos now. I understand this is frequently not in your control if you use managed computing resources like a school device, however it should be possible to petition the administration to either preinstall Anki (it's totally free: they have the right to do that without any license hassle, and it's small too) or to allow Play Store with a curated set of apps (so kids don't download games etc)

**Comment by asabir123** [comment]
How do i convert it?

**Comment by mikehardy** [comment]
Get a device you control, with Anki on it. Like, Anki Desktop or a cell phone. Install Anki and get your collection on it.

There should be an option to manage the scheduler version.

In AnkiDroid it is "settings --> advanced", in there you may toggle v1 or v2 scheduler.

**Comment by asabir123** [comment]
okay thank you. Which one should I do (V1 or V2)?
Also, will the setting update on the chromebook as well?

**Comment by mikehardy** [comment]
The scheduler version is embedded in your collection
Your collection is what syncs between devices
Ankidroid 2.8 does not know of, and does not work with v2 scheduler so if AnkiDroid 2.8 compatibility is important to you, you must choose v1 scheduler

After you do this you will be forced to do a full sync, it is an incompatible change and not merge-able in the collection, so whatever device you convert back to v1 on, you will then be forced to full sync up to AnkiWeb, then you can full sync down to your chromebook

**Comment by david-allison-1** [comment]
`Settings - Advanced - Scroll Down - V2 Scheduler - Disable it`

**Comment by asabir123** [comment]
Okay thank you very much

**Comment by david-allison-1** [comment]
Very welcome :)

Sadly, you'll need to treat this as "we're now unable to support your device". 

https://ankiweb.net/about may need to be used at some point in the future if support from AnkiWeb ends and you're unable to upgrade your device.

**Comment by asabir123** [comment]
Okay thank you

**Comment by asabir123** [comment]
do you still have:
Download Anki for 2016+ Linux (2.1.40)

**Comment by david-allison-1** [comment]
> do you still have:
> Download Anki for 2016+ Linux (2.1.40)

https://github.com/ankitects/anki/releases/
