### ISSUE TITLE
2.15.6: [Tablet] White space on Home screen

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9279]
##
besides, there is a little issue of layout at top-right corner, if using tablet (after v2.15.5)
best regards!

![Screenshot_01](https://user-images.githubusercontent.com/87444056/125849680-1e114b06-81a8-4e5c-ac78-689de542f03b.png)
![Screenshot_02](https://user-images.githubusercontent.com/87444056/125849690-bc0154bb-50ef-47ef-b9ec-2c0f6baa843c.png)

debug info:
AnkiDroid Version = 2.15.6

Android Version = 7.1.1

Manufacturer = htc

Model = Nexus 9

Hardware = flounder

Webview User Agent = Mozilla/5.0 (Linux; Android 7.1.1; Nexus 9 Build/N4F27P; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/53.0.2785.135 Safari/537.36

ACRA UUID = adfe1c1d-c34d-4c2e-823f-8ec742d3dc77

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

_Originally posted by @cygnetlakes in https://github.com/ankidroid/Anki-Android/issues/9267#issuecomment-880980178_

**Comment by mikehardy** [comment]
Must be more fallout from all the layout changes from making full screen navigation drawer swipe an option - @ShridharGoel was the last touch in there I think
