### ISSUE TITLE
Regression test: Preferences - Full Screen Gesture setting

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9281]
See the linked comment: a bug was introduced in a past commit, and we should ensure that we check the correct constants here via unit tests.

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/9278#r671360231_

**Comment by aryanritesh** [comment]
Hey! I am new here and I'd like to start helping. I think I can go through this issue.

**Comment by david-allison-1** [comment]
Awesome! Give me a ping if you need anything

**Comment by aryanritesh** [comment]
@david-allison-1 Okay so I just went through this , so basically all I've to do is test this on my device and upload a ss right?
Or is there anything I am missing out on?

**Comment by david-allison-1** [comment]
Add a unit test, then we don't need to retest it ever again

**Comment by aryanritesh** [comment]
![1631378652561](https://user-images.githubusercontent.com/84223159/132955142-237d91dc-f889-42dd-97ad-60eb9dda77d4.jpg)
@david-allison-1 
I tested this and I don't see any borders, it's working fine

**Comment by david-allison-1** [comment]
The full screen setting is for the reviewer, and that page isn't full screen

**Comment by aryanritesh** [comment]
Okay wait , I'm getting a bit confused over here , what exactly do I have to do?

**Comment by aryanritesh** [comment]
@david-allison-1 what are the parameters I'd need over here for testing?

**Comment by david-allison-1** [comment]
@aryanritesh I'm not sure I understand the question, what are you trying to accomplish?

The aim of this issue is to write an automated unit test which would catch the following issue:

https://github.com/ankidroid/Anki-Android/pull/9278/commits/420fb12ed7c3042ac09c9e6b47d920c92c508899
