### ISSUE TITLE
Stabilize / re-enable "open study options" instrumented test in CI

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#9282]
Ignoring it in CI now pending an issue I will peel off about stabilizing root view matching, but now it runs successfully locally and won't gum up CI runs.

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/issues/9205#issuecomment-881542544_

There is related discussion on the original PR #9205, a solution will likely involve using a specific RootMatcher in CI

**Comment by mikehardy** [comment]
This fails for me locally too, it is a *real* pain.

**Comment by mikehardy** [comment]
By pending changes I assume you mean loading/using backend study options page? If that assumption is correct, then this issue has no value and should close yes

**Comment by dae** [comment]
Sorry, that was indeed vague :-) I don't think I properly understood this issue, as I was assuming it was something custom study related, where that screen will move into Svelte in the future).  But I would vote to close in any case - flaky tests are an awful time sink, and I presume whatever issues this test was originally added to address are not frequently regressing.

**Comment by Arthur-Milchior** [comment]
There are still two tests that are disabled and whose todo is the current bug, so re-openining it
