### ISSUE TITLE
[Bug] LaTeX - `\\` doesn't work

### ISSUE THREAD

**Issue by PiotrLrc** [ankidroid/Anki-Android#9292]
Hi. After the latest patch `\\` in the latex mode stoped working. `\newline` doesn't work either.

**Comment by david-allison-1** [comment]
Hi, could you fill out the bug template, including `Settings - advanced - about ankidroid - copy debug info`.

What is the latest version that works (likely 2.14.6)

 You can find our old releases: https://github.com/ankidroid/Anki-Android/releases/

Install the Parallel.A app to revert to an older version for now.

**Comment by PiotrLrc** [comment]
Ok, I checked that in 2.14.6 `\\` was still working. 

I copied debug info: 

```
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = TCL

Model = T671H

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; T671H Build/RKQ1.201112.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.210 Mobile Safari/537.36

ACRA UUID = 5243dd98-67a4-4c29-b7f1-77e41e2ac03c

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by mikehardy** [comment]
Hi @PiotrLrc do you use AnkiDesktop at all? if so I'm curious if it works for you there? Thank you for posting the debug info!
