### ISSUE TITLE
[Bug] TestUtils.isCI() returns false on CI in emulator

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9293]
@mikehardy This is because "CI" is not set on the emulator.

**Comment by david-allison-1** [comment]
I've tried `$ANDROID_HOME/platform-tools/adb shell setprop CI true` , but this fails with 

```
Failed to set property 'CI' to 'true'.
See dmesg for error reason.
```

https://github.com/david-allison-1/Anki-Android/actions/runs/1046694065

Attempting it as root

**Comment by david-allison-1** [comment]
An alternate solution would be to set this in `BuildConfig`.

@mikehardy If root access works, which would you prefer?

**Comment by mikehardy** [comment]
Oh my that's a mess. Not sure why that did not occur to me. Adb root and then a set prop should work. Honestly anything that seems sane works for me, adb seems easier but both seem sane

**Comment by mikehardy** [comment]
Oh my that's a mess. Not sure why that did not occur to me. Adb root and then a set prop should work. Honestly anything that seems sane works for me, adb seems easier but both seem sane

**Comment by mikehardy** [comment]
TestUtils.CI you had one job. ONE JOB.

**Comment by david-allison-1** [comment]
`root` doesn't crash, but it doesn't seem to work, doing more digging

**Comment by david-allison-1** [comment]
Tried using `SystemProperties` and I can read the property, but setting it is flaky

Worked on CI on my repo, but seems flaky. I'll use buildprops

```
          $ANDROID_HOME/platform-tools/adb root
          $ANDROID_HOME/platform-tools/adb shell setprop CI true
```

```
Run $ANDROID_HOME/platform-tools/adb devices
List of devices attached
emulator-5554	device

restarting adbd as root
error: closed
Error: Process completed with exit code 1.
```

going back to `BuildConfig.CI`
