### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by visakhaav** [ankidroid/Anki-Android#9295]
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-A505F

Hardware = exynos9610

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-A505F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Mobile Safari/537.36

ACRA UUID = de202edc-9331-473d-b775-eb1606e6547c

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by david-allison-1** [comment]
Hi, there's no description of what the bug is. Could you let us know.

Thanks
