### ISSUE TITLE
Field names are no longer allowed to contain colons :

### ISSUE THREAD

**Issue by TheOneric** [ankidroid/Anki-Android#9297]
### Bug Behaviour

Version:
Present in 2.15.6; first noticed in either 2.15.2 or maybe 2.15.4 *(not sure anymore)*. Was working in 2.14.6.

Effect:
AnkiDroid claims to encounters an error with the back template (only back template!) of one of my decks, printing
```
Back template has a problem:Found '{{大辞泉}}', but there is no field called '大辞泉'.
```

Yet, despite this message, the back template does **not** contain `{{大辞泉}}`, it contains `{{Definition: 大辞泉}}` where `Definition: 大辞泉` is an actual field.
I can also confirm that it renders fine in for me in Desktop-Anki *(and old versions of AnkiDroid)*.

Here's the full text of the back template:
```
{{FrontSide}}
<div style='font-family: Meiryo; font-size: 30px;'>{{Reading}}</div>
<hr id=answer>

<div style='font-family: Meiryo; font-size: 25px;  text-align: left;'>{{Definition: 大辞泉}}</div>
<br>
<div style='font-family: Meiryo; font-size: 20px; text-align: left;'>{{Example Sentences}}</div>
```

I exported and attached a single example card: [消防.apkg.zip](https://github.com/ankidroid/Anki-Android/files/6850051/apkg.zip)

### Reproduction Steps

1. Open the card
2. Tap button to show backside

### Debug info
Anki Droid Version = 2.15.6
Android Version = 10
Manufacturer = HTC
Model = m8
Hardware = qcom
Webview User Agent = Mozilla/5.0 (Linux; Android 10; m8 Build/QQ3A.200805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.101 Mobile Safari/537.36
ACRA UUID = 9bedfb8a-8854-4b63-83c6-b309270af6b9
Scheduler = std
Crash Reports Enabled = true
DatabaseV2 Enabled = true

Source of Binary: FDroid

### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
The card template doesn't work in Anki 2.1.44 either.

**Comment by TheOneric** [comment]
> The card template doesn't work in Anki 2.1.44 either.

Hmm, with 2.1.13 my version is a bit older and it works:
![grafik](https://user-images.githubusercontent.com/1668471/126376648-42bdf295-f906-4d32-993b-3cede94e2583.png)

Based on the version number alone I would normally not expect any incompatible Template changes from 2.1.13 to 2.1.44.
Does Anki not keep the template format stable between patch-level version-cahnges? If it's supposed to, I guess I should open an Anki issue as well.

**Comment by david-allison-1** [comment]
Anki Desktop doesn't use semver. From an addon author perspective, each "patch" version is a breaking change.

We use semver with our releases

**Comment by TheOneric** [comment]
For reference: I've [posted a question](https://forums.ankiweb.net/t/what-constitutes-a-valid-field-name-old-templates-broken/11554) about what constitutes a valid fieldname to Anki's support forum, after I failed to find anything relevant to `Definition: 大辞泉` in the changelogs or docs.

**Comment by mikehardy** [comment]
Anki is just stricter about references to fields now, and will no longer ignore fields that don't exist. I believe the fix is to make sure you only reference fields that exist. You may need to edit your card template to add the field in the error message.

**Comment by TheOneric** [comment]
> I believe the fix is to make sure you only reference fields that exist.

The field **does** exist! The field is named `Definition: 大辞泉` and referecned as `{{Definition: 大辞泉}}`. But for reasons unbeknownst to me Anki(Desktop|Droid) instead try to search for the field `大辞泉`, which does in fact not exists *(but also never got referenced)*.

**Comment by mikehardy** [comment]
Oh, interesting! Sorry I did not notice that detail. I wonder if it is the spacing in the name? That seems like the likely culprit. I wish I could be more prescriptive and say "it's definitely the space", it just seems likely. I wonder if you changed the field name and the template reference to one with no space in the name if it would work

**Comment by TheOneric** [comment]
Thanks for the help!
Turns out the change in AnkiDesktop is intentional. It was not the space but the colon `:`, which now has a special meaning in templates. Closing as it's not a AnkiDroid bug after all.

**Comment by mikehardy** [comment]
Ah ha! Well, now I know more about the template system myself, thanks for driving this all the way to real understanding. Sorry your template unexpectedly blew up but I imagine you've resolved that practical issue and are moving forward now as well. Happy reviewing
