### ISSUE TITLE
Performing a normal sync results in insufficient memory error.

### ISSUE THREAD

**Issue by Michael35699** [ankidroid/Anki-Android#9304]
###### Reproduction Steps

1.  sync without forcing.

###### Expected Result

The synchronization completes, and the day continues.

###### Actual Result

As the synchronization message becomes "Finishing syncing ...", the application reports an error with the message "Operation not possible due to insufficient memory on your device". However, the synchronization does complete when forcing one-sided from AnkiWeb.

###### Debug info

AnkiDroid Version = 2.16alpha6

Android Version = 11

Manufacturer = samsung

Model = SM-N975F

Hardware = exynos9825

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-N975F Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.164 Mobile Safari/537.36

ACRA UUID = 1a814959-72ad-4bfb-ac2f-67d8a96fd638

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! This seems like it will be related strongly to the size of your collection. I understand some collections contain private information, but also - just on the off-chance it is okay - some collections are really just a bunch of general knowledge and vocabulary etc and if you could share it (export and zip and share a link or try to attach here) that would help us. Otherwise I fear we not be able to make any progress on this assuming my hunch it is collection-dependent is correct

**Comment by david-allison-1** [comment]
```
java.lang.OutOfMemoryError: Failed to allocate a 160563208 byte allocation with 25165824 free bytes and 128MB until OOM, target footprint 427317560, growth limit 536870912
at java.util.Arrays.copyOf(Arrays.java:3257)
at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
at java.lang.StringBuffer.append(StringBuffer.java:270)
at java.util.regex.Matcher.appendReplacement(Matcher.java:716)
at java.util.regex.Matcher.replaceAll(Matcher.java:843)
at java.lang.String.replaceAll(String.java:2314)
at com.ichi2.libanki.Utils.jsonToString(Utils.java:1)
at com.ichi2.libanki.Models.flush(Models.java:7)
at com.ichi2.libanki.Collection.save(Collection.java:7)
at com.ichi2.libanki.sync.Syncer.finish(Syncer.java:6)
at com.ichi2.libanki.sync.Syncer.sync(Syncer.java:98)
at com.ichi2.async.Connection.doInBackgroundSync(Connection.java:16)
at com.ichi2.async.Connection.doOneInBackground(Connection.java:2)
at com.ichi2.async.Connection.doInBackground(Connection.java:4)
at com.ichi2.async.Connection.doInBackground(Connection.java:1)
at android.os.AsyncTask$3.call(AsyncTask.java:394)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
```

Seems like an OOM due to a massive amount of data in the card types. Phone has 12GB RAM

**Comment by mikehardy** [comment]
Last time I did a big deep-dive into the syncer and collection import (which is similar to the sync) it appeared there was some inefficient string/stringbuffer usage in that handles weren't cleared so the JVM GC wasn't able to clear things, but I never proceeded beyond seeing that. And now it appears this may go Rust-internal so perhaps the issue goes away medium-term? (it's been a really long term issue, so that's actually a massive improvement with regard to "timescale of fix")

**Comment by Michael35699** [comment]
> Hi there! This seems like it will be related strongly to the size of your collection. I understand some collections contain private information, but also - just on the off-chance it is okay - some collections are really just a bunch of general knowledge and vocabulary etc and if you could share it (export and zip and share a link or try to attach here) that would help us. Otherwise I fear we not be able to make any progress on this assuming my hunch it is collection-dependent is correct

Honestly I thought that the collection I have is just too large at first, but then there's no memory insufficient error when the sync is forced one sided. Do these syncs have a different procedure? I'll try and reduce the size of my note types, and I'll reply again.

**Comment by Michael35699** [comment]
I have reduced the size of my note types, and it seems that it's working. I'll close this issue as this is a user-sided bug. However, I think it would be nice to look into the reason why normal syncing did not work with large collections when force syncing worked. Thank you!

**Comment by mikehardy** [comment]
I'm happy that worked for you, but I side with the users here, there's no reason you should have to twiddle your note types for it to work, it's a shame we have this limitation. On the other hand - I really do think it will go away as this area is converted to Rust (which is in process now) so it is "okay" to close it in the sense that it should actually go away, and not just if users carefully manage their decks.

To answer your other question - yes - a full sync is a very different procedure from a differential sync. One of them (full sync) just copies a sqlite database with no processing, and it's done. The other (differential) means a diff list is sent and lots and lots database work may be necessary (which apparently has a resource leak - or inefficient use - somewhere fundamental in the code)
