### ISSUE TITLE
[Bug] Some UI elements are not completely black.

### ISSUE THREAD

**Issue by LemmusLemmus** [ankidroid/Anki-Android#9305]
###### Description
Some UI elements are not completely black in the black night theme, contrary to my expectations. During daytime these areas are practically invisible, whereas at night they are highly visibly grey, especially in combination with AMOLED. I find this inconsistency somewhat distracting, as well as aesthetically unappealing with the slight grey on top of the otherwise perfectly black screen.

###### Reproduction Steps

1. Select Night Theme Black and enable night mode
2. Review Cards, look at the decks listed in the main activity or look at the settings.*
3. Use the screen in dark conditions and/or set the brightness of the screen sufficiently high.
4. (Optional) Use an AMOLED display**

*In the review card section, the small bar under the header is affected. The issue can also be encountered where there are menu items listed, for example in the deck list in main activity and the settings menu where the background of the decks listed are also not completely black. There might be additional UI elements with this issue that I have yet to notice.
**Using an AMOLED display makes the issue much more apparent, since there is a relatively clear contrast between the pixels that are off and the pixels that are still emitting light.

###### Expected Result
Everything is completely black.
![Expected Result](https://user-images.githubusercontent.com/63229554/126673036-e4b1ee6f-a6a0-4492-8a34-b2952638f0b0.png)
Here I am only showing images of the problem as it manifests itself in the review section. All screenshots were taken from NicoWeio's issue #8150, since they clearly demonstrate the problem and I am too lazy to actually take my own screenshots.

###### Actual Result
A grey area occupies part of the screen. Please note that the grey bar in the image below may appear invisible under certain conditions, if you cannot see the grey bar try increasing the brightness of your display or refer to [this image](https://user-images.githubusercontent.com/63229554/126674257-a19a9641-a3b9-4c4b-9b03-f8a6959aeb94.png), where I have drastically increased the brightness of the affected area to a more visible grey colour.
![Actual Result](https://user-images.githubusercontent.com/63229554/126672659-01e70254-479a-4ea1-91e0-83213c11a84d.png)

###### Debug info
AnkiDroid Version = 2.15.6 (the latest Google Play Store build of the application)

Android Version = 10

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; ONEPLUS A6003 Build/QKQ1.190716.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Mobile Safari/537.36

Screen = Optic AMOLED 6.28″ Display

###### Research
I was not able to replicate the issue in the Android emulator.
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Interesting! I have a sub-optimal work lighting environment, no way I'd see that without your  super-emphasized screen shot :-)

Happy for anyone to take a pass through Theme.Black to make things actually `#000000`
