### ISSUE TITLE
[Bug] Failed to sync media files: java.net.UnknownHostException: Unable to resolve host "sync6.ankiweb.net": No address associated with hostname

### ISSUE THREAD

**Issue by artkpv** [ankidroid/Anki-Android#9306]
###### Reproduction Steps

1. Has cards with images. Using Desktop Anki to upload to cloud. It does the sync and uploads / downloads very fast.
2. Open Ankidroid. Press Sync
3. It downloads very slowly about 20MB in around 10-30 min. Then shows message (translated from Russian):

> Collection synced.
> Error while syncing media files
> java.net.UnknownHostException: Unable to resolve host "sync6.ankiweb.net": No address associated with hostname

###### Expected Result

It synchronizes the files.

###### Actual Result

Error shown

###### Debug info

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Sony

Model = Xperia 10 II

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Xperia 10 II Build/RQ2A.210505.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/90.0.4430.82 Mobile Safari/537.36

ACRA UUID = 4387e7bd-3a02-43e0-9062-79e501f3e539

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum

**Comment by mikehardy** [comment]
This has come up before, the speed issue is already logged, but it will get all the files on retry eventually

The network error is real though. Something about your local dns services is unstable and there was a failure there. That's out of our control.

**Comment by artkpv** [comment]
@mikehardy Thanks. I use custom ROM LineageOS 18.1 for Xperia 10 II [Stock-based] ( https://forum.xda-developers.com/t/rom-unofficial-lineageos-18-1-for-xperia-10-ii-stock-based.4219081/ )

**Comment by mikehardy** [comment]
I've used lineage, it works
That's not relevant to my comment though. Your local dns services appear unreliable. Mostly working, but can fail occasionally, it seems

**Comment by artkpv** [comment]
Strange. I've tried several times for in last months. It never worked. Always did this: slowly downloaded media files then failed with the error.

**Comment by david-allison-1** [comment]
The media file download is incremental, as long as the media files in `collection.media` are increasing, it will eventually finish.

This typically means a temporary issue with your internet connectivity (which we can do better with handling retries). If you retry, the download should continue where it left off

**Comment by artkpv** [comment]
@david-allison-1 Thanks for answers! I got it synchronised by repeatedly retrying. It took about 3-6 retries and 1-3 hours.
