### ISSUE TITLE
Deck name styling with HTML

### ISSUE THREAD

**Issue by Munzu** [ankidroid/Anki-Android#9307]
I've recently come across this [post on reddit](https://www.reddit.com/r/Anki/comments/opb0yo/you_can_use_html_to_colorin_bold_the_names_of/) that shows how you can style the deck names with HTML. 

This is how it looks for me on desktop:
![image](https://user-images.githubusercontent.com/31477160/126775460-fb275acd-2a3c-4b0f-bc5d-be9034413d9d.png)

Unfortunately, it doesn't seem to work on AnkiDroid. AnkiDroid will just show the HTML code as plain text.
![image](https://user-images.githubusercontent.com/31477160/126775552-4bbf2121-d2c2-4f8f-8002-571d02a38904.png)

Is there any chance this will get implemented into AnkiDroid as well?

Thanks in advance for any reply.

Desktop: 
- Anki Version 2.1.43
- Windows 10

Mobile:
- AnkiDroid Version 2.15.6
- Android 11 (LineageOS 18.1)

**Comment by david-allison-1** [comment]
Hi, thanks for the feature request!

The last discussion we had on this was #5814 , which ended with

>> (Daemien) I'm afraid the only reason HTML tags in deck names currently render in the deck browser is due to oversight - in the future they will likely be shown as text instead.
>
> ankitects/anki#544

Unless this has changed, we won't be implementing the feature.

**Comment by Munzu** [comment]
Thanks for the quick reply!
Sorry I didn't find that issue earlier.
That's unfortunate but understandable. Thanks. I'll close the issue then.
