### ISSUE TITLE
[Bug] Closet addon nonfunctional in Android versions 9 and below

### ISSUE THREAD

**Issue by talenelat-elin** [ankidroid/Anki-Android#9311]
Preface: I'm unsure of the complete extent or cause of the problem

This concerns the the addon [Closet](https://ankiweb.net/shared/info/272311064).
Cards created using it are supposed to work in AnkiDroid from version 2.15 too, but I'm seeing that it doesn't work in certain devices.

The problem: The clozes and occlusions are not rendered at all, instead the contents of the fields are shown, including the closet notation, like so: 
![image](https://user-images.githubusercontent.com/71895835/126846447-433e77d0-0ae4-4e81-80fd-5fbe612b8714.png)
In a functioning card, the contents of the double square brackets should have been replaced by `[...]` in the front of the card.

How I test it:
1. Delete all the ankidroid files present from previous installs, if any.
2. Fresh install of ankidroid from the play store
3. Import an apkg file of closet cards that I've created (that definitely work on Anki Windows)- [LINK](https://mega.nz/file/zbAiQbLD#OWMPaRsV00eEJTMCN7RQAOzf9ymrUN6NuDnSiSRBQYQ)
4. Check the cards

So far, I've tested 6 devices:

1. Xiaomi Redmi Note 5 Pro - broken
2. Xiaomi Redmi Y2 - broken
3. Xiaomi Redmi Note 7 Pro - broken
4. Lenovo K9 - Broken
5. OnePlus 6 - Works
6. RealMe 2 - Works

I'd appreciate it if people could import the deck and check out the cards on their devices and add to the data.

[I've posted an issue in Closet's github too](https://github.com/hgiesel/closet/issues/73)

Tested in: AnkiDroid 2.15.6

**Comment by talenelat-elin** [comment]
It's possibly due to Android version differences, I'll update here as soon as I get the information of these devices.

**Comment by david-allison-1** [comment]
Does it work (without the addon) on the latest version of Anki Desktop?

**Comment by talenelat-elin** [comment]
> Does it work (without the addon) on the latest version of Anki Desktop?

@david-allison-1, Yes.
Just tested in Anki Windows 2.1.44 (64bit) and all cards work.

I'm not sure if you're familiar with closet, but the cards once made should function in all anki versions beyond 2.1.41, without requiring any addons, because the reviewer side of closet works via a javascript file that is included inside the template. (`__closet-0.5.3.js`)

The actual addon helps in creation of the closet cards.

**Comment by talenelat-elin** [comment]
I think it is related to Android versions.

Evidence:
<table><thead><tr><th>Phone</th><th>status<br></th><th>Android Version</th></tr></thead><tbody><tr><td>Xiaomi Redmi Note 5 Pro</td><td>broken<br></td><td>9 PKQ1.180904.001</td></tr><tr><td>Xiaomi Redmi Y2</td><td>broken</td><td>9 PKQ1.181203.001</td></tr><tr><td>Lenovo K9</td><td>broken</td><td>8.1.0</td></tr><tr><td>Xiaomi Poco M2<br></td><td>working</td><td>10 QP1A.190711.020</td></tr><tr><td>OnePlus 6</td><td>working</td><td>10 (OxygenOS v10.3.11)</td></tr><tr><td>Realme 2 Pro</td><td>working<br></td><td>10 (Realme UI V1.0)<br></td></tr></tbody></table>

**Comment by hgiesel** [comment]
Closet relies on dynamic imports, which was added in https://github.com/ankidroid/Anki-Android/pull/7764. It seems like this only works on Android 10+, so there's really nothing we can do.
