### ISSUE TITLE
[Bug] Review count different between AnkiDroid, AnkiWeb/AnkiDesktop (mac)

### ISSUE THREAD

**Issue by e-e** [ankidroid/Anki-Android#9314]
###### How I _think_ this happened:

1. Was on a flight traveling to a timezone three hours behind my home timezone (took off at 4pm home-time, 1pm destination time)
2. Did reviews on the plane (using both AnkiDroid and AnkiDesktop) with wifi connection, synced completed reviews multiple times. Both devices still on home timezone.
3. After landing (now in destination timezone), attempted to sync final completed reviews from AnkiDesktop so I could update AnkiDroid for the car ride. This is when I noticed first discrepancy - unfortunately I don't remember which device was showing reviews, but one was showing that I had reviews I still had to do and the other was showing that they were completed for the day.

###### Expected Result
Review counts should be consistent between devices/environments 

###### Actual Result
**AnkiDesktop (~9:30am destination TZ)**
<img width="425" alt="Screen Shot 2021-07-26 at 9 32 34 AM" src="https://user-images.githubusercontent.com/5191838/127049685-2af5886e-0248-4c21-aafe-8d19fe22ef30.png">

**AnkiWeb (~9:30am destination TZ)**
<img width="1137" alt="Screen Shot 2021-07-26 at 9 49 43 AM" src="https://user-images.githubusercontent.com/5191838/127049846-6fe06d7d-7ad2-4287-ae45-0c00848aebd6.png">

**AnkiDroid (~9:30am destination TZ)**
![218457148_415954266382232_304341217775581707_n](https://user-images.githubusercontent.com/5191838/127049931-259fb60c-6332-455c-8e08-4ccc7ff582f1.png)

Notice how in the AnkiDroid screenshot, there are no reviews available for `KanjiV2` and `Tobira`, and limited reviews available for `J4`, but also states that I've "Studied 0 cards in 0 minutes today".

###### Debug info
AnkiDroid:
```
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Google

Model = Pixel 5

Hardware = redfin

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 5 Build/RQ3A.210705.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.115 Mobile Safari/537.36

ACRA UUID = c6048392-c0bf-4e21-ab78-3fd704aa0495

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**AnkiDesktop (mac)**
```
Version ⁨2.1.44 (b2b3275f)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

I've attempted the "Sync in one direction" from both AnkiDroid and AnkiDesktop to no effect.

**Comment by david-allison-1** [comment]
Hi, thanks for the report.

Anki Desktop: `Tools - Preferences - Scheduling - Disable legacy timezone code`

**Comment by e-e** [comment]
This seems to have worked. Disabling the above + forcing a one-way sync in AnkiDroid to pull down from AnkiWeb seemed to do the trick. Thank you for the help!
