### ISSUE TITLE
Resources: Allow strings containing '&'

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9319]
We need either need

* a lint check to ensure that strings do not contain an `&amp`. A user should use `&` in a CDATA block instead
   * I'd personally be happy with this to mark the issue as fixed
* or fix the localization script
  * Needs thorough testing, I wouldn't consider this to be a good first issue as it involves CrowdIn API access and we don't have a test framework yet
  * See: https://github.com/ankidroid/Anki-Android/pull/9318#issuecomment-887631641

See a working example:

https://github.com/ankidroid/Anki-Android/blob/897f932b6f673327497246894dd2362d1917d287/AnkiDroid/src/main/res/values/02-strings.xml#L260

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/9318#issuecomment-887633139_

**Comment by inomag** [comment]
I am interested in doing this task.
