### ISSUE TITLE
[Bug] Audio files cannot be added

### ISSUE THREAD

**Issue by farjadilyas** [ankidroid/Anki-Android#9321]
###### Reproduction Steps

1. Add Note
2. Add Audio Clip
3. Click on LIBRARY
4. Select a music file

###### Expected Result
Any music file can be selected. 

###### Actual Result
(API Level 26): Music files except for .ogg files (for eg: .mp3 file) are greyed out & cannot be selected
(API Level 30): All files are greyed out including .ogg & .mp3 files

API 26 - Samsung Galaxy S7 (Physical Device):
The 3 .ogg files are selectable, but the .mp3 file isn't
![api26_greyed_out](https://user-images.githubusercontent.com/29615198/127356791-e4662afe-52ba-4381-9d34-66bda1ab9681.jpg)

API 30 - Pixel 4 XL (Emulator):
![greyed_out](https://user-images.githubusercontent.com/29615198/127351593-b47163fd-7659-4e6f-a673-56d2d94e6459.JPG)

One of these files is a .ogg file, the other is a .mp3 file

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by farjadilyas** [comment]
Can I work on this? A related previous [commit](https://github.com/ankidroid/Anki-Android/pull/9228/commits/cd37b342939b7817f6346c97d438adaa2bbc496a) linked to this [accepted answer](https://stackoverflow.com/questions/1698050/multiple-mime-types-in-android) which solves this issue & makes audio files including .ogg files selectable on both the devices mentioned in the issue @ API 26 & 30.

**Comment by mikehardy** [comment]
Hahah from my comment on the related PR "Famous last words but it doesn't look like it can break anything,"

Famous last words indeed. Programming, why are you so irritating!?!
