### ISSUE TITLE
Unable to import or export Anki collections / decks

### ISSUE THREAD

**Issue by soleera** [ankidroid/Anki-Android#9324]
###### Reproduction Steps

1. Install & open AnkiDroid
2. Allow file permissions
3. Tap Menu > Import

###### Expected Result

Opens a dialogue box or file explorer app so the user can select a *.colpkg or *.apkg file

###### Actual Result

"The system does not have an app installed that can perform this action."

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = OnePlus

Model = IN2023

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; IN2023 Build/RP1A.201005.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.115 Mobile Safari/537.36

ACRA UUID = 7b15bc06-f0a1-4d87-975a-a18149c67e99

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! That is...really strange. Is there any file manager app on the system? Have you tried opening the file manager app separately, using it to navigate to downloads and attempt to open the shared deck that way? (It should be hooked up via file extension to AnkiDroid and trigger an import)

We are just attempting to open any file picker app using the standard Android system call for opening a file chooser - this is one of the most fundamental of Android things to do, and we're doing it the standard way - I'm very surprised this isn't working

**Comment by soleera** [comment]
Got the chance to look into this properly with adb and it seems like something messed with DocumentsUI... After reinstalling via a shell everything seems to be working again!
