### ISSUE TITLE
Update to compileSdkVersion 30

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9331]
Lots of deprecations here (primarily AsyncTask), but others exist.

Warrants its own issue

Related: #7348

**Comment by david-allison-1** [comment]
Deprecations:

* WindowManager.LayoutParams.FLAG_FULLSCREEN

**Comment by mikehardy** [comment]
Looks like an extravaganza for the CompatHelper/Compat infrastructure...

**Comment by david-allison-1** [comment]
I'll just whack a `@SuppressWarnings` on there for now, surgery can wait for another day
