### ISSUE TITLE
[Bug] Floating action button change all color

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#9341]
###### Reproduction Steps

1. Install master (5efa59bf0de963a4ecc679cd022c3d8f794caacc)
2. Click on the floating action button (the plus)

###### Expected Result
Either just the menus. Or everything grayed and menu focused

###### Actual Result
Even the menu is grayed.

![Screenshot_20210731-034447_AnkiDroid.jpg](https://user-images.githubusercontent.com/357361/127725089-ef34d848-c7da-41dc-a786-6b399e18bcfc.jpg)

**Comment by mikehardy** [comment]
Arthur, it would be good to know your debug info - this doesn't happen for me on a mobile device (not tablet mode), Android 10, 2.16alpha6 and I struggle to see in the commit history what could cause it :thinking:

**Comment by ShridharGoel** [comment]
Reason: In case of mobile, the `FloatingActionButton` is separate from the `LinearLayout` having ID as `deckpicker_view`. But in case of tablet, the `FloatingActionButton` in inside `deckpicker_view` which causes the alpha value to be set on the `FloatingActionButton` and its related views as well.

**Comment by Arthur-Milchior** [comment]
AnkiDroid Version = 2.16alpha7

Android Version = 11

Manufacturer = samsung

Model = SM-T515

Hardware = exynos7904

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-T515 Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.115 Safari/537.36

ACRA UUID = 6136db88-8714-436c-adea-30ae4f10577b

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
