### ISSUE TITLE
New flags in Anki 2.1.45

### ISSUE THREAD

**Issue by eu2021** [ankidroid/Anki-Android#9347]
As you know, the new Anki 2.1.45 (already stable) offers 3 new flag colors. So, I suggest that they are included in AnkiDroid. 

Thanks,
BR,

**Comment by david-allison-1** [comment]
Pink (FF82EE) Ctrl+5
Turquoise (00D1B5) Ctrl+6
Purple (9649DD) Ctrl+7

https://github.com/ankitects/anki/blob/578b1b0552582dd04936e3c64ce2c660381a2e6d/ts/sass/_vars.scss#L24-L26

**Comment by david-allison-1** [comment]
This isn't a major issue - no crashes on 2.16 with the new flag

**Comment by david-allison-1** [comment]
Added in https://github.com/ankitects/anki/pull/1213
