### ISSUE TITLE
Add built-in canvas🎨

### ISSUE THREAD

**Issue by nxcco** [ankidroid/Anki-Android#9363]
Problem:
To add a drawing to a card, one hast to go to a sketching app. Then one has to record a screenshot or save the drawing. That's prevents from being more productive.

Solution:
Provide a built-in canvas. When you tap the little clip, you should get the option to create a drawing.

What do you think of that?

**Comment by Akshay0701** [comment]
Really great idea @nxcco, we already implemented the drawing page option in #9048 Visual editor, you will get to see this in action soon.
