### ISSUE TITLE
please remove  android:networkSecurityConfig="@xml/network_security_config" attribute

### ISSUE THREAD

**Issue by HarryRen** [ankidroid/Anki-Android#9364]
I get a `net：：ERR_CLEARTEXT_NOT_PERMITTED` in Android9.0 with a http link to ankiServerSync.

please remove android:networkSecurityConfig="@xml/network_security_config" attribute.

 **android:usesCleartextTraffic="true"** and **android:networkSecurityConfig="@xml/network_security_config"** attribute are conflicted.  

Is anyone has a lastest stable version with **android:networkSecurityConfig** removed? I need one.

**Comment by HarryRen** [comment]
I compile it by myself. Ugly.

**Comment by mikehardy** [comment]
@HarryRen why not propose a PR?

**Comment by mikehardy** [comment]
...also, if those items are conflicted, could you point to some documentation saying you must use one or the other? I work in this area (android apps from scratch, that require cleartext traffic to development servers) so I'm pretty up to date on the requirements and I thought this was correct but perhaps there is an error here. If so, I'd love to see it corrected.
