### ISSUE TITLE
[Bug] Default deck shows up in card browser even when empty.

### ISSUE THREAD

**Issue by Vortexagon** [ankidroid/Anki-Android#9372]
###### Reproduction Steps

1. Open AnkiDroid. It could be a fresh install or not. You could add your own decks at this stage, but from my testing the problem persists all the same.
2. Notice how there is no Default deck on your Home / Decks page.
2. Go to the card browser

###### Expected Result
The "Default" deck does not show up in the "Deck Search" menu in the card browser.

###### Actual Result
The "Default" deck shows up in the "Deck Search" menu in the card browser. If you haven't tapped on another deck before going here it defaults to showing this empty Default deck.

###### Debug info
```
AnkiDroid Version = 2.15.6

Android Version = 7.0

Manufacturer = HUAWEI

Model = PRA-LX1

Hardware = hi6250

Webview User Agent = Mozilla/5.0 (Linux; Android 7.0; PRA-LX1 Build/HUAWEIPRA-LX1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.131 Mobile Safari/537.36

ACRA UUID = d8707b1f-9d6b-4956-9e3b-95bc5c26bf70

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by yasin459** [comment]
what should i do to fix this?
is default deck neccessary? or it's useless and we just need to delete it from cardbrowser deck drop down?

**Comment by yasin459** [comment]
ok i am working on this

**Comment by yasin459** [comment]
@mikehardy 
umm, i have a "Deck" object which is a son with some params, I want to filter them if deck is empty ,how can i find how many cards a deck contains?

**Comment by mikehardy** [comment]
The development guide on the wiki explains the database structure and json elements I think - that might be a good place to start

Be careful that there may be sub-decks, or decks may be "dynamic", to filter them if they are empty you'll need to verify all decks in a tree rooted at the deck you are inspecting are empty

I believe if you look in the Decks are Collection APIs you should find the APIs you need. The scheduler may also be interesting, or the notification system, they all fetch deck card counts so may serve as examples
