### ISSUE TITLE
[Bug] In night mode the card menu is white text on white bg

### ISSUE THREAD

**Issue by henon** [ankidroid/Anki-Android#9379]
Screenshot
![Screenshot_20210806-084544_AnkiDroid](https://user-images.githubusercontent.com/44090/128468786-4efeb0b0-81d9-4646-af16-fb353c8c7c2e.jpg)
![Screenshot_20210806-084622_AnkiDroid](https://user-images.githubusercontent.com/44090/128468813-ef1edeb3-1931-46d1-aeb3-ac3ac2b0659f.jpg)

Android version 11

**Comment by 9004912418** [comment]
The one way to enable dark mode on the menu is by using a CSS media query for the user's preferred color scheme. This media query will hook into the system setting of the user's device and apply the theme if a dark mode is enabled.

@media (prefers-color-scheme: dark) {
  :root {
    /* dark mode variables go here */
  }
}

currently, the prefers-color-scheme media query has limited browser support, so users will not be able to benefit from having the dark mode applied using this media query in certain browsers. However, the dark mode can still be applied by using a CSS class fallback.

**Comment by prateek-singh-3212** [comment]
Thanks @henon for reporting this issue. Can you please fill the debug template. And please specify the ankidroid version. 

To copy debug info goto:- settings-> advanced -> ankidroid -> copy debug info

**Comment by henon** [comment]
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-G996B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-G996B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.131 Mobile Safari/537.36

ACRA UUID = 737fbbf8-1b81-4e6b-85d6-764716405993

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by henon** [comment]
Btw, both dark themes have that issue, Black and Dark.

**Comment by henon** [comment]
Strangely enough, now it is working. All I did is install an OS update, but of course we can not know for sure if that is the real reason. 
![Screenshot_20210808-234440_AnkiDroid](https://user-images.githubusercontent.com/44090/128646740-cbda68e6-b422-4e26-867a-a9b123652b2d.jpg)

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-G996B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-G996B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.131 Mobile Safari/537.36

ACRA UUID = 737fbbf8-1b81-4e6b-85d6-764716405993

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true



Should it occur again I will reopen this issue.

**Comment by david-allison-1** [comment]
Very likely it was the OS update, nothing's changed on our side

**Comment by henon** [comment]
Strangely enough, now it is working. All I did is install an OS update, but of course we can not know for sure if that is the real reason. 
![Screenshot_20210808-234440_AnkiDroid](https://user-images.githubusercontent.com/44090/128646740-cbda68e6-b422-4e26-867a-a9b123652b2d.jpg)

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = samsung

Model = SM-G996B

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-G996B Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.131 Mobile Safari/537.36

ACRA UUID = 737fbbf8-1b81-4e6b-85d6-764716405993

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true



Should it occur again I will reopen this issue.
