### ISSUE TITLE
FYI: Fake "Free" AnkiDroid app on iTunes App Store

### ISSUE THREAD

**Issue by agentjudy** [ankidroid/Anki-Android#9399]
Hi the AnkiDroid Team,

Don't know if you have any means to do anything about it but - https://apps.apple.com/us/app/anki-pro-flash-cards-ankidroid/id1573585542

Context: https://forums.ankiweb.net/t/ankipro-another-ripoff-anki-app/11791

Best regards,

Agent Judy

**Comment by mikehardy** [comment]
Hi there! This is probably best raised in https://forums.ankiweb.net - they are the proprietors of the Anki iOS Mobile app and are separate from us

**Comment by mikehardy** [comment]
I did leave a review for the app though, now that you brought it to my attention :-), I think that's all I can do. Theft is sad.
