### ISSUE TITLE
Disculpe poruqe solo me aparecen 20 fichas si tengo 75[Bug]

### ISSUE THREAD

**Issue by Sarahirl7** [ankidroid/Anki-Android#9402]
###### Reproduction Steps

1. Porque solo se ven 20 fichas si tengo 72 y eso es en todas tengo más pero solo dice que son 20
3. 
![p](https://user-images.githubusercontent.com/88849415/129240202-a9176466-a593-4899-ba9f-781d11277d1a.png)
![pp](https://user-images.githubusercontent.com/88849415/129240212-fda4495a-3d33-42b8-8839-de75ea421a80.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hola! Las tarjetas son en el busquedor porque si, las existen. Solo 20 (o menos!) estan lista para revisar, y es por eso que solo 20 (o menos!) van a aparecer en la lista de barajas

Todo explicado en la introduccion pienso, y si le gustaria cambiar la cantidad de tarjetas nuevas que estan listo para revisar diario, haz click largo por la baraja para abrir opciones del barajas, y cambiarlo alla

https://docs.ankiweb.net/deck-options.html#new-cardsday

**Comment by Sarahirl7** [comment]
Muchas gracias por la atención ya pude
