### ISSUE TITLE
[Bug] Name of custom card type appearing instead of a field (only on AnkiDroid, not on desktop)

### ISSUE THREAD

**Issue by mafarkas** [ankidroid/Anki-Android#9418]
###### Reproduction Steps
Custom card type ("Anatomy(point out & name)") with the following fields:
1: Name (of structure)
2: Type
3: hint
4: Pic1 - arrow
5: Pic1 - blank
6: Learning aid

And cards:

1. Point out (1st pic)
    Front:
Point out the {{Name (of structure)}}
<br/>
{{Pic1 - blank}}
<br><br>
    Back:
{{Name (of structure)}}
<hr id=answer>
{{Pic1 - arrow}}
<br><br>
{{Learning Aid}}

2. ID (1st pic)
    Front:
What {{Type}} is this?
<br/>
{{Pic1 - arrow}}
<hr id=answer>
<b>[..<i>{{hint}}</i>..]
    Back
{{Pic1 - arrow}}
<hr id=answer>
{{Name (of structure)}}
<br> <br> 
{{Learning Aid}}

Have also tried:
- originally, 1st field was just "Name." Got the same bug
- Have since tried changing "Type" to "Type (of structure)." Got the same bug.
- The issue does not occur on Anki browser. I don't use AnkiWeb, so I haven't tried it there.

###### Expected Result

See html; note type should not appear in card when studying

###### Actual Result
Note type name appears instead of {{type}}

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mafarkas** [comment]
I can provide screenshots, but am I am not sure whether it would help.

**Comment by david-allison-1** [comment]
Hi, what does Anki Desktop do here?

**Comment by mafarkas** [comment]
@david-allison-1 , on desktop it's appearing as you would expect from the html: the card's {{type}} appears properly.

**Comment by david-allison-1** [comment]
Thanks! I'll take a look

For now, you should be able to fix this by renaming the field, both in the "Fields" screen, and in the "Card Templates" screen.

**Comment by dae** [comment]
{{Type}} is a [special field](https://docs.ankiweb.net/templates/fields.html#special-fields) and should not be used as a field name.

**Comment by david-allison-1** [comment]
Good first issue: Add an `@Ignore`d unit test for renderQA. Fixing will be performed in the Rust conversion and is blocked on #8988

https://github.com/ankidroid/Anki-Android/blob/ac0bec41a811bac142d8ed4aaf935164e4415486/AnkiDroid/src/main/java/com/ichi2/libanki/Collection.java#L1087-L1088

**Comment by mafarkas** [comment]
Thank you @david-allison-1 and @dae! I changed the name of the field accordingly

**Comment by mafarkas** [comment]
And I good to close this issue, or are y'all trying to implement something with discussion tied to this thread?

**Comment by shreelakshmijoshi** [comment]
Hi @mafarkas !
I am a new open source contributor and would like to solve this issue, could you help me understand the issue better by providing some extra references ? 
Is this is issue open to contribute ?

**Comment by david-allison-1** [comment]
> And I good to close this issue, or are y'all trying to implement something with discussion tied to this thread?

Let's implement what's discussed

----

@shreelakshmijoshi 

It's open. See https://github.com/ankidroid/Anki-Android/issues/9418#issuecomment-899963747 for a spec (writing a unit test that fails, and ignoring it), please feel free follow up on anything that you're unsure of.

**Comment by dae** [comment]
Closed by #14171.
