### ISSUE TITLE
FR - "Card browser" & "Statistics" menu icons

### ISSUE THREAD

**Issue by joshakaw** [ankidroid/Anki-Android#9428]
**Is your feature request related to a problem? Please describe.**
The 'Card Browser' icon (a magnifying glass) does not necessarily represent what the menu entails.
The 'Statistics' icon is too thick as compared to every other icon

![example](https://media.discordapp.net/attachments/701922522836369498/877932775552991302/Screenshot_20210819-111111.png?width=167&height=369)

**Describe the solution you'd like**
1. Replace the current icon for the Card Browser with a deck of cards
(This does not currently exist on the material icon library, so I modified the money icon)

![cards2x](https://user-images.githubusercontent.com/84877484/130096109-a6b2d286-21bd-48c3-b044-d35c9aa26cde.png)

2. Replace the current Statistics icon with the "Bar Chart" icon from the material library.
_Currently the menu is using the equalizer icon, which is considerably more thick than the "Bar Chart" icon._

![icons](https://media.discordapp.net/attachments/701922522836369498/877932942935093278/unknown.png)

**Comment by david-allison-1** [comment]
@joshakaw  Could you provide the 'modified money' icon as a SVG?

**Comment by david-allison-1** [comment]
Would you mind if I flipped the statistics icon, having the larger bar on the left seems 'wrong' in comparison with the current icon

**Comment by joshakaw** [comment]
> Would you mind if I flipped the statistics icon, having the larger bar on the left seems 'wrong' in comparison with the current icon
Looks fine either way, I don't mind.

> Could you provide the 'modified money' icon as a SVG?

[card-browser-icon.zip](https://github.com/ankidroid/Anki-Android/files/7108250/card-browser-icon.zip)
