### ISSUE TITLE
New cards counter does not update when entering a new card

### ISSUE THREAD

**Issue by dansynek** [ankidroid/Anki-Android#9430]
When I click on edit card and then enter new card, the new card counter does not update. It updates when I leave the deck and reenter.

AnkiDroid Version = 2.15.6

Android Version = 10

Manufacturer = Xiaomi

Model = Mi 9T

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Mi 9T Build/QKQ1.190825.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Mobile Safari/537.36

ACRA UUID = d91f0a2d-61fa-4c6a-b5e3-d5e621fd90f7

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by dorrin-sot** [comment]
Hi I can't reproduce this bug. Can you provide a recording of the steps you took for this to happen?

**Comment by dansynek** [comment]
> 

Uploading 20210820_162152.mp4…

`

**Comment by dansynek** [comment]
Uploading Anki bug.mp4…

**Comment by dansynek** [comment]
It says uploading. And not uploaded. Does that mean something went wrong. I tried twice!

**Comment by dorrin-sot** [comment]
maybe it wasn't done uploading when you went to preview it or clicked the comment button 🤔

**Comment by dansynek** [comment]
https://user-images.githubusercontent.com/619992/130343703-b2ca233b-6d70-41e4-9678-cc8818d0a383.mp4

It worked when I uploaded it from PC instead of Android phone. Anyway, this is the recording of the bug

**Comment by dansynek** [comment]
Nevermind the uploading problem. I think it was becaus eI didn't notice on the phone that I had to accept the comment befofre the uploading takes place. It was clearer from a PC.

**Comment by dansynek** [comment]
Oh no, it seemed I closed the comment by mistake and I can't find how to unclose it..... I wonder if I am stupid or if the system is hard to use. Anyway, I will open the issue again unless I can find a way to unclosde it or if someone can do it for me...

**Comment by dansynek** [comment]
Ok ,managed to unopen it. Sory for all the noise. Anyway, the bug is real(though not serious)

**Comment by dorrin-sot** [comment]
oh right, thanks I was using the generic way of adding the note and checking the deckpicker numbers 😅. I'll try to fix it

**Comment by dansynek** [comment]
Thanks for fixing it and I enjoyed adding my milligram of effort to make Ankidroid even better!

**Comment by mikehardy** [comment]
All the help adds up! Thanks for posting this

**Comment by Prince-kushwaha** [comment]
@mikehardy can i work on this issue

**Comment by dansynek** [comment]
Check if it is still true. I made the initial report and if I remember
correctly it was fixed in a couple of days.

**Comment by dae** [comment]
OP says it's fixed.
