### ISSUE TITLE
[Bug] Displaced tablet layout

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#9436]
###### Reproduction Steps

1. Launch AnkiDroid on a tablet

###### Expected Result
Aligned layout on the right

###### Actual Result
Layout is misaligned on the right:
![photo_2021-08-22_17-51-31](https://user-images.githubusercontent.com/7422433/130359601-302fe9e8-dd03-455a-ad5a-fccd33b590c0.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
```
AnkiDroid Version = 2.15.6

Android Version = 9

Manufacturer = samsung

Model = SM-T713

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; SM-T713 Build/PQ3A.190801.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.152 Safari/537.36

ACRA UUID = ed468302-47be-446f-9607-efc3e39f8ef9

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by homocomputeris** [comment]
Sorry, the same as https://github.com/ankidroid/Anki-Android/issues/9279

**Comment by mikehardy** [comment]
Yeah I wish I could fix this one but I can't pick cleanly on to the release branch, sorry. Go with the alpha :-)
