### ISSUE TITLE
On API<=23 emulator the image was lager than screen viewport

### ISSUE THREAD

**Issue by Akshay0701** [ankidroid/Anki-Android#9439]
Gallery photos appear far larger in preview in devices API <= 23. 

![Capture](https://user-images.githubusercontent.com/52353967/130348358-41f8ca76-646a-4ebe-8b4e-dea30a4bb38b.PNG)

_Originally posted by @Akshay0701 in https://github.com/ankidroid/Anki-Android/issues/9394#issuecomment-903234344_

**Comment by dae** [comment]
We're up to a min API of 23 now. Still a problem?

**Comment by mikehardy** [comment]
Even if it still occurs on API23 itself (original issue lists it as `<= 23` so I assume it still affects 23...) the usage stats indicate just a few thousand devices on 23 in contrast with the nearly 3 million total device installs. So I'm going to say not worth any effort even if it reproduces
