### ISSUE TITLE
[Bug] Syncing Media not working

### ISSUE THREAD

**Issue by Kk2050** [ankidroid/Anki-Android#9456]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
AnkiDroid Version = 2.15.6  Android Version = 11  Manufacturer = realme  Model = RMX2001  Hardware = mt6785  Webview User Agent = Mozilla/5.0 (Linux; Android 11; RMX2001 Build/RP1A.200720.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Mobile Safari/537.36  ACRA UUID = 8965edb0-9d06-4c19-88a1-18735d2dab84  Scheduler = std2  Crash Reports Enabled = true  DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, what's the problem? No crash reports under that ACRA ID

**Comment by david-allison-1** [comment]
https://github.com/ankidroid/Anki-Android/wiki/FAQ#syncing should help
