### ISSUE TITLE
Regression test: no crash if sound is not found

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9461]
See stack trace for the cause: https://github.com/ankidroid/Anki-Android/issues/9401

The deliverable will be a unit test which fails before PR https://github.com/ankidroid/Anki-Android/pull/9407 goes in, and passes afterwards

----

Thanks! Could you add a regression test here for when the sound is not in the collection?

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/9407#issuecomment-898621819_

**Comment by Peyman-hme** [comment]
Hi. Can I working on it?

**Comment by mikehardy** [comment]
Sure!

**Comment by raddi1972** [comment]
Is someone still working on this? If not I would like to try.

**Comment by david-allison-1** [comment]
Sure, thanks!

**Comment by raddi1972** [comment]
> Could you add a regression test here for when the sound is not in the collection? 

Please, could you clarify which collection you are talking about? I am kind of new to Android Development and need some guidance.

**Comment by david-allison-1** [comment]
> > Could you add a regression test here for when the sound is not in the collection?
> 
> Please, could you clarify which collection you are talking about? I am kind of new to Android Development and need some guidance.

[This pull request](https://github.com/ankidroid/Anki-Android/pull/9407#issuecomment-898621819) fixed an issue.

A regression test is a unit test which is designed to ensure that an issue doesn't occur again.

* Understand the linked PR
* Check out the code at the revision before the PR landed
* Write + commit a unit test which exercises the broken code branch, and reproduces the crash
* Cherry pick the unit test to the latest master
* Ensure that the PR above fixed the test

**Comment by david-allison-1** [comment]
I was asked to elaborate on the cause of the issue. These code snippets below are from how the code was at the time:

`setDataSource` throws as the file couldn't be read (didn't exist)

https://github.com/ankidroid/Anki-Android/blob/b6ccfd9aae9721a40f121a06979bfc80ec1c49cc/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java#L375

Therefore `mAudioFocusRequest` was never set

https://github.com/ankidroid/Anki-Android/blob/b6ccfd9aae9721a40f121a06979bfc80ec1c49cc/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java#L392-L396

`releaseSounds()` is called

https://github.com/ankidroid/Anki-Android/blob/b6ccfd9aae9721a40f121a06979bfc80ec1c49cc/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java#L400

and this uses `mAudioFocusRequest`, which is null

https://github.com/ankidroid/Anki-Android/blob/b6ccfd9aae9721a40f121a06979bfc80ec1c49cc/AnkiDroid/src/main/java/com/ichi2/libanki/Sound.java#L521-L525

It would be better to exercise this code via the `Reviewer` class, as this API is much less likely to change.

**Comment by raddi1972** [comment]
To test this the plan I have come up is,
To add a invalid path in the `Sound` (in the hash map `mSoundPaths`), then calling the `playSoundInternal` method through `Reviewer` class. This would then create the same error which will occur before the pull request #9407.
Is this plan good or should I try some other approach?

**Comment by david-allison-1** [comment]
You'd be best to check out the code at the failing commit hash, then test in-app with `[[sound:not_on_file_system.mp3]]`.

If this fails (it should), duplicate this in a unit test (inside `ReviewerTest`), providing and viewing a note with the above code. Debug the test if the crash isn't reproduced, and fix the preconditions of the test to ensure we get a failure at the given commit.

When things are the same, you have a regression test.

**Comment by raddi1972** [comment]
I was able to roll back to the commit hash and was able to recreate the problem (the app crashed) and I got the similar stack trace as the one provided in the issue #9401. 
Now whenever I run a test in `ReviewerTest` then I get some linking error as- 
`java.lang.UnsatisfiedLinkError: C:\Users\dixit\AppData\Local\Temp\rsdroid7800908337259424667.dll: Can't find dependent libraries`
Looks like a linking error, did I miss something while setting up environment? 
Thank you for the help.

**Comment by david-allison-1** [comment]
@raddi1972 See: https://github.com/ankidroid/Anki-Android/issues/8482 - should have a download to fix the issue

**Comment by raddi1972** [comment]
@david-allison-1 there does not seems to be a fix for windows! I tried running `./gradlew jacocoUnitTestReport` using git bash and it worked but does not work for powershell. Is there a way to run a specific test in `ReviewerTest` from terminal so I can directly run it from git bash and test? In case there is not, then I will setup linux environment to fix it.

**Comment by david-allison-1** [comment]
> @david-allison-1 there does not seems to be a fix for windows! I tried running `./gradlew jacocoUnitTestReport` using git bash and it worked but does not work for powershell. Is there a way to run a specific test in `ReviewerTest` from terminal so I can directly run it from git bash and test? In case there is not, then I will setup linux environment to fix it.

I use Windows, it works on my machine, so it's possible to get it working. I haven't done anything specific to get it running, and the listed steps should work, or at least get closer to a diagnosis.
