### ISSUE TITLE
[Bug] Import Package: System File Picker - Searching for a file doesn't allow selection

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9467]
###### Reproduction Steps

1. Deck Picker - Import
2. Search for "apkg"
3. tap on apkg file

###### Expected Result

4. File selector closes

###### Actual Result

4. File selector stays open

###### Debug info
Not really an AnkiDroid issue

```
AnkiDroid Version = 2.16alpha12

Android Version = 11

Manufacturer = Google

Model = Pixel 3a

Hardware = sargo

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3a Build/RQ3A.210805.001.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Mobile Safari/537.36

ACRA UUID = 1775f05e-66c5-4bd4-91f9-1fdec7945c81

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true
```

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by ShridharGoel** [comment]
@david-allison-1 It is working fine on Pixel 2 API 30 emulator.

**Comment by codingtosh** [comment]
This seems to be working fine on Version 2.16alpha28, Samsung's ONEUI API 30 as well. @david-allison-1 Could you upload a recording of the steps?

**Comment by david-allison-1** [comment]
Can no longer repro... don't know what happened there. Apologies for the wasted time
