### ISSUE TITLE
[Bug] Scrolling X takes priority over Y in stats

### ISSUE THREAD

**Issue by joshakaw** [ankidroid/Anki-Android#9468]
###### Reproduction Steps

1. Open stats menu
2. Scroll up and down the Overview tab (Y direction)
3. While scrolling, slightly move your finger to the left.

###### Expected Result

Tab is locked from scrolling in X direction while I'm scrolling up and down on a stats page (Y direction).

###### Actual Result

Scrolling up and down gets locked, and it starts scrolling in the X direction, from the small finger movement to the left.

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Google

Model = Pixel 3

Hardware = blueline

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Pixel 3 Build/RQ1A.201205.003.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Mobile Safari/537.36

ACRA UUID = 0dad175e-a323-4043-b6d3-cfb5e999ad28

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true
###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x]have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
I'm not sure this is anything we can do anything about. These are system libraries (ViewPager2, with a ScrollView inside it).
If you can find somewhere that allows scrolling in both the fragment *inside* the view pager tab as well as the view pager tab itself at the same time then this is at least possible technically, however, I would disagree this is a bug.

I believe the priority of tab scrolling over intra-tab fragment scrolling is on purpose because the behavior is on average slightly more confusing if everything can move at once.

**Comment by joshakaw** [comment]
Not sure if I wrote my issue correctly. I don't think everything should move at once, but I think when you are viewing a page, like Overview, and scrolling down, I think there should be 0 potential for it to start moving left to right and start switching tabs. Scrolling in the Y should have priority over the X, instead of the current situation.

**Comment by mikehardy** [comment]
I hear your opinion.

it really has to start with this though:

>  I'm not sure this is anything we can do anything about. These are system libraries (ViewPager2, with a ScrollView inside it).
If you can find somewhere that allows scrolling in both the fragment inside the view pager tab as well as the view pager tab itself at the same time then this is at least possible technically,

Then I'd want to see some sort of UX guide that agreed with you, as it is opinion and the defaults disagree with you.

In my experience (and I just re-tested it now), I just fling the overview with my thumb and it scrolls right on the bottom, no X scroll issue.
