### ISSUE TITLE
[Bug] Inconsistent font rendering when system fonts are chosen

### ISSUE THREAD

**Issue by homocomputeris** [ankidroid/Anki-Android#9482]
###### Reproduction Steps

1. Set 'System default' font in the settings
![Screenshot_20210902-110426_AnkiDroid](https://user-images.githubusercontent.com/7422433/131907802-8f910100-b6b2-43d3-92c5-acb045e5673b.png)

2. Create a card with italic text
![Screenshot_20210902-110017_AnkiDroid](https://user-images.githubusercontent.com/7422433/131907842-d6fc82b0-4d36-43cb-b322-3bb42531e860.png)

3. Choose a system font
![Screenshot_20210902-110046_Стили_и_обои](https://user-images.githubusercontent.com/7422433/131908059-b59b899c-58f0-44da-a218-0578ad400be8.png)

###### Expected Result
System font should be used, not some thin variation.
`<i>` should be rendered as italic, not italic bold.

I would expect something like this (OpenSans Regular is chosen in the settings):
![photo_2021-09-02_23-01-41](https://user-images.githubusercontent.com/7422433/131908598-bb1aba73-99be-4543-ba30-591b6b56a02a.jpg)

###### Actual Result
1. Thin font instead of the system one
2. Italics rendered as italics bold:
![Screenshot_20210902-110009_AnkiDroid](https://user-images.githubusercontent.com/7422433/131908172-d59abd9c-8c69-462c-980b-89968f40080c.png)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
```

AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = OnePlus

Model = ONEPLUS A6003

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; ONEPLUS A6003 Build/RQ3A.210805.001.A1; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.164 Mobile Safari/537.36

ACRA UUID = f4b3e223-395b-4497-8fac-878e4acb5ac8

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by homocomputeris** [comment]
Still an issue

**Comment by homocomputeris** [comment]
Still an issue

**Comment by homocomputeris** [comment]
Still an issue

**Comment by homocomputeris** [comment]
Still an issue

**Comment by homocomputeris** [comment]
Still an issue

**Comment by pavreh** [comment]
Hi @homocomputeris, let me recap your steps: Set font in Ankidroid settings to system default. Change font in the phone settings. Start reviewing in Ankidroid. Font used in a card is not as expected. Is it correct? 

Font used in a card can be influenced by the card template. Check CSS Styling of your card template. 

![Screenshot_20220721-220758_AnkiDroidA](https://user-images.githubusercontent.com/10192661/180307046-147ce710-3e17-4380-a2c7-852523eda4c8.png)

**Comment by homocomputeris** [comment]
Correct.

Here is my CSS
```
.card {
    font-size: 30px;
    text-align: center;
}

.var {
color: navy;
font-size: 60%;
font-variant: small-caps;
}

.reg {
color: green;
font-size: 60%;
font-variant: small-caps;
}
```

**Comment by pavreh** [comment]
I deleted "font-family" from my CSS and I got exactly the same result (thin font, italics is bold). It means the issue is caused by your CSS. Add a font family to the .card section. I am not sure how to handle .var and .reg sections.

**Comment by homocomputeris** [comment]
If you confirm the issue, it means it's caused by the incorrect font rendering or wrong font substitution.
