### ISSUE TITLE
How do I get all data from certain deck via content provider?

### ISSUE THREAD

**Issue by KursX** [ankidroid/Anki-Android#9483]
I am a Smart Book application developer. https://smart-book.net
In my application, users read books in different languages and save words from books to their dictionary.
I do sync via anki-api.
The problem is that when inserting, I indicate the ID of the deck, but I cannot get all the cards/notes from a certain deck, only all cards/notes of a certain model.
Perhaps I haven't found how to do this?
Now I want to give the opportunity to fully synchronize my application with anki. For users to add / delete / search / use anki decks as an offline dictionary

**Comment by mikehardy** [comment]
I'm sorry I nor anyone else has had time to chat with you on this, apologies. I think the "apisample" app might have some clues to it? It allows you to kind of walk through a whole collection if I recall correctly https://github.com/ankidroid/apisample
