### ISSUE TITLE
App bar isn't displayed in fullscreen mode

### ISSUE THREAD

**Issue by Nanonej** [ankidroid/Anki-Android#9484]
When the "Fullscreen mode" option is toggled on, the app bar is not displayed when reviewing cards.

I don't have other phone to try on, so if it's specific to me here is some additionals info:
- Ankidroid version 2.15.6
- Phone model Xiaomi Mi 9 SE

**Comment by david-allison-1** [comment]
Drag down from the top of the screen to reveal the bar

**Comment by Nanonej** [comment]
Yeah I figured that, but is it intentional ? Shouldn't there an an option like the answers button to hide the app bar too ?
