### ISSUE TITLE
[Bug] Some sort of issue from mailing list about image changes causing problems

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#9489]
###### Reproduction Steps

Just prose, not sure it has repro steps. Reporter did not want to sign up for github

----

I'm very familiar with Anki Droid, and use it daily.  I have always done all of the check media and check database commands. This problem is nothing that I'm doing, as I haven't changed my interactions with AnkiDroid for years, and my card collection is not corrupted in any way.  I check it daily with all the error checking functions.

Once I have replaced the media file in Anki Droid and then attempt to synchronize, I get the error 400 message. When I go out to Anki desktop in Windows, it says that there is a card expecting a media file which is not there.  So there is something about a simultaneous erasure of a media file and a creation of a new one in ankicard that now suddenly confuses the sync function, or the hub, or desktop anki. I don't know what it is.

Good luck on it.  I don't know what a GitHub is, or how to create a problem report, so I hope you can take care of that end of things.

The problem that Ankidroid is now creating, every day, with different cards, after trying a lot of different things, is that I have to completely uninstall ankidroid, erase all of my material, reinstall ankidroid, and download everything from the hub. It's a big deal as I have about twelve thousand cards in 49 decks, and lots of media.  I will have to use only desktop anki until this problem gets fixed within ankiDroid.

My drastic approach fixes things until the next time that I try to change a media file. Then the new card that I have changed the media file on is the one that causes the sync not to work.

I hope this more complete description helps you! Thanks for looking at the problem.

Frederick

Sent from my T-Mobile 5G Device

-------- Original message --------
Date: 9/3/21 1:54 PM (GMT-08:00)
Subject: Re: [Ankidroid] AnkiDroid Flashcards

Hi there! Can you open an issue in our github (there's a link from the help menu in the app) with as many details + steps to reproduce + filenames (maybe the name is a problem?) as possible?

You might try deck list --> menu --> check database and check media as well to see if that helps

-Mike

> Something has changed in the most recent version that is causing error 400.
>
> What seems to be happening is that when I replace a sound file with a different sound file on a card, when I go to synchronize it with Anki, I get error 400.  And I can no longer synchronize.
>

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Could you check with the recipient if a previous version of AnkiDroid will fix the issue? It would be useful to pin down whether this is an AnkiDroid issue, or a change in AnkiWeb

**Comment by dae** [comment]
I've made a change to AnkiWeb which I suspect will fix this. The code was updated recently, and while I had tested the changes with AnkiDroid, I didn't cover the deletion case. AnkiDroid's code is based on the older desktop code, which sends an empty string instead of a null. 🤦

**Comment by mikehardy** [comment]
Okay - thanks @dae ! I reached out to the original reporter, we'll see what we hear back

**Comment by mikehardy** [comment]
@dae - ⚡ 

> It worked.  Yay!
> 
> My thanks to the responsive, accommodating and knowledgeable Anki teams!
> 
> Frederick
