### ISSUE TITLE
[Bug] Punctuation marks problem

### ISSUE THREAD

**Issue by Abanoub-Asaad** [ankidroid/Anki-Android#9498]
###### Reproduction Steps

When I write an Arabic sentence and put a punctuation mark at the end of it, the punctuation mark becomes at the start of the sentence in case of reviewing.

###### Actual Result
As we know, Arabic is written from right to left, so the punctuation mark should be at the end of the sentence in case of reviewing the notes.

### Screenshots

In the left image, we can see the **exclamation mark (!)** at the end of the Arabic sentence as expected
In the right one, the **exclamation mark (!)** became at the start of the sentence.

<div align="center">
<pre>
   
<img alt="" width="30%" src="https://user-images.githubusercontent.com/48657780/132129950-ace26ad0-6273-44d6-9f54-1a97bd7b9664.jpg">  <img alt="" width="30%" src="https://user-images.githubusercontent.com/48657780/132129953-b4cad101-815c-4998-8fe0-b74937637199.jpg">   
     
</pre>
</div>

**Comment by mikehardy** [comment]
Anything at all you can do to log + reproduce (and hopefully fix 🙏 ) RTL languages would be incredibly welcome. I feel like we made great progress but it's not a case anyone else that actually posts PRs tests

**Comment by Abanoub-Asaad** [comment]
Are you talking about this log?

![Screenshot from 2021-09-06 11-06-50](https://user-images.githubusercontent.com/48657780/132191709-b129b2b9-bade-4c7c-b635-a7cb2b7646ba.png)

**Comment by Abanoub-Asaad** [comment]
I can solve this problem, but I would like to know where I can find the HTML code in the  that's responsible for the RTL notes. I tried to find it but didn't reach it.

**Comment by Abanoub-Asaad** [comment]
I can solve this problem, but I would like to know where I can find the HTML code in the  that's responsible for the RTL notes. I tried to find it but didn't reach it.

**Comment by mikehardy** [comment]
the "assets" directory has most of the HTML that is used as scaffolding for programmatic interpolation

the AbstractFlashcardViewer file is good to step through to see how (and when) it gets the "q" and "a" parts of a card - following it shows how the code is generated for interpolation into the files in assets directory

**Comment by eginhard** [comment]
Just to make sure, did you add `dir="rtl"` somewhere in your card template to indicate that this field contains RTL text? See the manual: https://docs.ankidroid.org/#RTL
There is no special code in Anki to display RTL cards, it's based on standard HTML markup.
