### ISSUE TITLE
FR - Add Note / Add Deck icons

### ISSUE THREAD

**Issue by joshakaw** [ankidroid/Anki-Android#9499]
**Is your feature request related to a problem? Please describe.**
The icons currently used do not necessarily represent interacting with a deck of cards (folder and + icon).
<img src="https://user-images.githubusercontent.com/84877484/132254354-6f14a0b5-092a-4481-b514-cc8d992f1707.png" width=200>

**Describe the solution you'd like**
Icons that appear more like flashcards/a deck of flashcards ([Icons 2.zip](https://github.com/ankidroid/Anki-Android/files/7117608/Icons.2.zip)):

Originally posted icons (add note, add deck):
![image](https://user-images.githubusercontent.com/84877484/132254402-4786c83e-489c-493e-90e3-6cf7d85dcc66.png) ![image](https://user-images.githubusercontent.com/84877484/132254462-aeae5fe2-e461-4191-8677-1d76c3b960c3.png)

<hr>
Edit - Filled icons:

![image](https://user-images.githubusercontent.com/84877484/132960291-62032c09-dee0-40b5-81b3-b90f3c1f1fba.png) ![image](https://user-images.githubusercontent.com/84877484/132960267-e8d9613c-c842-4c73-8e6c-7d4822ed00de.png)

[Filled FAB Icons.zip](https://github.com/ankidroid/Anki-Android/files/7148426/Filled.FAB.Icons.zip)
<hr>

**Additional context**
A couple of weeks ago I submitted my icon to replace the Card Browser icon, and it was put into the 2.16 release. These icons are a modification of this original icon, I think they'll make the FAB experience better.
https://github.com/ankidroid/Anki-Android/issues/9428#event-5255561600

**Comment by pratik2315** [comment]
Hello sir, I am just starting out here, this seems like a perfect issue to start with, can I work on this issue? 
Thanks.

**Comment by mikehardy** [comment]
Hey @pratik2315 - sure! Our normal request around icons is that they are all svg now, so the result here should be a PR changing vector graphic XML files, and we need to make sure there's a copyright header in there with the right owner as a comment in the SVG - most of the rest of them should have examples you may use as patterns. Thanks!

**Comment by joshakaw** [comment]
Yeah - you can probably just go ahead and make a PR since it's a small issue. Thanks!

**Comment by joshakaw** [comment]
I already put the comment in with the files in the ZIP (license, copyright, changes, etc), you should be all set! Thanks

**Comment by david-allison-1** [comment]
Sounds good to me, let me know if you have any questions

**Comment by joshakaw** [comment]
I made some other types that might look better than the original proposed icons at such a small scale (also it would fit with the current Filled icon style of the shared deck icon)

![image](https://user-images.githubusercontent.com/84877484/132960291-62032c09-dee0-40b5-81b3-b90f3c1f1fba.png) ![image](https://user-images.githubusercontent.com/84877484/132960267-e8d9613c-c842-4c73-8e6c-7d4822ed00de.png)

[Filled FAB Icons.zip](https://github.com/ankidroid/Anki-Android/files/7148426/Filled.FAB.Icons.zip)
Header included

**Comment by pratik2315** [comment]
Thank you @joshakaw I will add your icons👍

**Comment by pratik2315** [comment]
My first ever PR merged🥳 Thanks all for being so supportive!!
