### ISSUE TITLE
Ignore gestures on links not working for <details> tag

### ISSUE THREAD

**Issue by markhavemann** [ankidroid/Anki-Android#9500]
###### Reproduction Steps

- Create a card with information inside of <details></details> tags
- the information should now be hidden with a "details" heading to display it.
- In the gestures section of the menu, set Ankidroid to ignore gestures over links. This words on Audio and {{hint::}} tags.
- set tap screen gesture to answer as suggested answer
- view a card with the details tag and the "details" link to show information

###### Expected Result

- hidden information should be displayed without moving to the next card, as happens with audio links and hint links.

###### Actual Result

- hidden information is show but the gesture is triggered and the next card is shown immediately.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Oh no - I hate to just punt things to @david-allison-1 but he always seems to fix these with a one-liner in 5 minutes 😅

**Comment by david-allison-1** [comment]
Sorry, we're constrained via Chrome's API for this once, could you turn the `details` into an `a` + click listener?

**Comment by BrayanDSO** [comment]
Closing this to join with #14303 since it's probably the only solution
