### ISSUE TITLE
Delay siblings for cards other than cloze

### ISSUE THREAD

**Issue by markhavemann** [ankidroid/Anki-Android#9501]
**Is your feature request related to a problem? Please describe.**

I often have several cards from the same note (a card for pronunciation of a Chinese character, a card for the meaning, and a card for a sentence containing the character/word, and sometimes an English>Chinese card too). They often always come up on the same day, so the first card may remind me of the others. 

It feels like a waste of time to review information that's almost the same information all together. It's useful having so many cards (the same information in slightly different forms), but frustrating to see it so close together. I find myself seeing one card and then burying the other three that day, then the next day burying two, then finally the last one. This is ok but frustrating and a waste of time, not to mention that burying by one day isn't really efficient. 

**Describe the solution you'd like**
This add on for the desktop version does it perfectly.
https://ankiweb.net/shared/info/1369579727

An option to turn this on and off for each deck would be amazing.

**Describe alternatives you've considered**
Can't really add anything else, the creator of the addon seems to have put a lot of thought into making something that works well.

**Additional context**
The comments on the addon page are probably worth having a look at.

**Debug Info**
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Xiaomi

Model = Redmi K30

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi K30 Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/92.0.4515.159 Mobile Safari/537.36

ACRA UUID = 4c3763b8-63cd-4621-ae00-8af750d8ed37

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment]
Hi there - it looks like you trimmed out the debug info part of our new issue request. I'd like to see that information, can you provide it please?

https://docs.ankidroid.org/help.html

**Comment by markhavemann** [comment]
Added debug info.

**Comment by mikehardy** [comment]
Thank you! I'll admit, I was hoping to see something besides "std2" for the scheduler, indicating we'd have something easy to try. 

I seem to recall this changed recently because it was a point of confusion for new users, perhaps by default it is off now. Can you check the related settings here? https://docs.ankiweb.net/studying.html#siblings-and-burying

Sorry this is all vague and low-percent-chance-of-fix, but it's worth a try

**Comment by markhavemann** [comment]
![a4ff5950645cf4ddf5a5cba01fbff22](https://user-images.githubusercontent.com/2283022/132448698-b7fe9e1a-e2bb-497a-9d8b-b820e732a952.jpg)

**Comment by david-allison-1** [comment]
> Thank you! I'll admit, I was hoping to see something besides "std2" for the scheduler, indicating we'd have something easy to try.
> 
> I seem to recall this changed recently because it was a point of confusion for new users, perhaps by default it is off now. Can you check the related settings here? https://docs.ankiweb.net/studying.html#siblings-and-burying
> 
> Sorry this is all vague and low-percent-chance-of-fix, but it's worth a try

From my reading, this is a feature request, and not a bug. In which case we'll need to see the functionality in Anki Desktop before we implement it (or wait for our addons PR to land).

Anki Desktop accepts feature requests: https://forums.ankiweb.net/
