### ISSUE TITLE
[Feature request] Default answer selection when using the timers

### ISSUE THREAD

**Issue by ekalz** [ankidroid/Anki-Android#9504]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
AnkiDroid thankfully provides TTS. It also provides the feature of showing the answer card and even moving onto the next card after an adjustable amount of time. For the second function - moving to the next card - the default answer selection is "bad". 
An option of selecting the default answer to "good" would enable semi-passive learning with Anki in combination with TTS in some scenarios. For example, learning with headphones while doing chores and only requiring interaction for bad answers when necessary. Good answers would automatically progress during a sessions using TTS, the fixed timers and using the default option "good". 

**Describe alternatives you've considered**
With the current "bad" default selection it's possible too but usually needs more attention. At least for reviews. 

**Additional context**
Maybe in long term advanced audio only options could be considered, like adjusting the answer selections, timers, repetition times for each card type, review type (new/learned/easy). But that's just an idea. The request above should be easy to implement with available code.

**Comment by mikehardy** [comment]
Hi there! This is a duplicate request but we have a PR that is almost ready for merge - this will be available in the future #8281
