### ISSUE TITLE
Feedback on suspend and on bury

### ISSUE THREAD

**Issue by eu2021** [ankidroid/Anki-Android#9519]
**Is your feature request related to a problem? Please describe.**
I use Ankidroid with a small Bluetooth controller, and, sometimes, I am not sure if I pressed the correct button. This is not a problem for the main answer button, because there is a feedback color that appears after each review rate. The problem happens when I press bury, or suspend, because there is no such feedback.

**Describe the solution you'd like**
I would like to have a feedback message when I press bury or suspend.

**Additional context**
This kind of feedback is already a vanilla feature in Desktop Anki.

A feedback on undo was also discussed [some time ago](https://github.com/ankidroid/Anki-Android/issues/9192).

BR,

**Comment by david-allison-1** [comment]
I started on this, and got waylaid with the fact that our "launch a task in the background" code isn't well designed (which makes a change like this slightly harder). It's a nice excuse to fix this part of the codebase, so this change will be behind a much larger change

Here's a relevant video while you wait, sorry for the delay

[![](https://img.youtube.com/vi/AbSehcT19u0/0.jpg)](https://www.youtube.com/watch?v=AbSehcT19u0)

**Comment by eu2021** [comment]
Thanks for looking into this.

The video is very funny.
