### ISSUE TITLE
Import cards from Mémorion

### ISSUE THREAD

**Issue by Lizzygg** [ankidroid/Anki-Android#9522]
Hello,

I have many cards in Mémorion (flashcard app) that I would like to export to Anki. Is there a way to do it without losing the progress?
I can export them in TSV, or XLS format. Also in the specific .mem one.

Thanks for reading

**Comment by mikehardy** [comment]
Hi there! Anki desktop allows for csv import, use anki desktop to import then sync up to ankiweb and down to ankidroid. There's no other way at the moment
