### ISSUE TITLE
[Bug] Second audio file not auto played if first one is not available

### ISSUE THREAD

**Issue by szpak** [ankidroid/Anki-Android#9523]
###### Reproduction Steps

0. Ensure auto playback for audio files is enabled.
1. Create a card template with 2 audio files on the front page, e.g. `[sound:broken.mp3] [sound:existing.mp3]`.
2. Change `existing.mp3` to any audio file available in your collection.
3. Review that card.

###### Expected Result

The second audio file is auto played (the first one is missing).

###### Actual Result

Nothing is auto played (on the front page). It is required to tap the (second) "playing triangle" to hear existing audio file.

###### Additional info

It is a minor issue and usually is caused by some problem on the user side, however, tracking down why auto playing for audio files doesn't work for the front page in my new card template, it took me a while to pinpoint the original problem (here, missing audio file). It was especially unpleasant, as Anki Desktop (2.1.15 on Linux) auto played the second file without any problem (and the first (missing) one was `silence05.mp3` which was inaudible :-) ).

Tested with AnkiDroid 2.15.6 and 2.9beta5.

###### Debug info

Not needed

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
What does Anki Desktop do here? From memory, it was the same functionality, but this could have changed

**Comment by szpak** [comment]
2.1.15 just plays the second (existing) file, ignoring error on the first one. However, it's not the newest desktop version, so it might change in the meanwhile (unfortunately, there is no RPM available with the newer version for Fedora).

**Comment by mikehardy** [comment]
go go go go :-)
