### ISSUE TITLE
string: `link_donation` is unused

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9525]
This is used incorrectly (used in code, but not displayed). It's not picked up by our lint checks as we:

* Get the string from an array
* Apply substitutions to this string via `String.format`, rather than the Android `getString()`

It should be removed, but let's handle this in a separate issue/PR

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/9400#discussion_r711767936_

**Comment by mikehardy** [comment]
Oh - is it the difference between getString vs String.format that allows it to silently fail lint checks? That informs my current misunderstanding of a part of #9400 - I'll read up on that, thanks

**Comment by pratik2315** [comment]
Hi, I would like to work on this issue if its alright? Thanks.

**Comment by david-allison-1** [comment]
Sounds good to me!

**Comment by Aman1131145** [comment]
hey @david-allison-1 can you assign this to me.

**Comment by thevar2002** [comment]
Hey @david-allison-1 I would like to work on this issue. @Aman1131145 I am looking into this issue from yesterday Midnight. Just Joined the Discord and Read up development Guide. Would mean a lot if you could let me work on this one.

**Comment by mikehardy** [comment]
Okay @thevar2002, please have at it, but in future please drop a comment so people *know* you're active on something :-), welcome to you both though! Happy to have new folks around. @Aman1131145 hopefully something else tagged up as help wanted / good first issue looks interesting. Cheers!

**Comment by Aman1131145** [comment]
Hey @thevar2002, I am a fresher to this field, and it is my first assignment and there is way too much code to even start with. Can you help me to get started with the code.
