### ISSUE TITLE
[Bug] Lag and sometimes crash after some use

### ISSUE THREAD

**Issue by burbilog** [ankidroid/Anki-Android#9530]
###### Reproduction Steps

I have two devices -- old Samsung tablet with stock 5.1.1 Android and Asus ZB602KL phone with Pixel Experience (Android 11) ROM. The problem is the same on both devices.

1. Start using Anki, enter deck 
2. Review about 20-100 times
3. Watch the lag, the next card will be delayed for several seconds. It depends on the device and the phase of the moon, but usually after 20-30 cards. The lag seems to increase with every card.

###### Expected Result

Normal behaviour.

###### Actual Result

On Samsung tablet it lags and then crashes. On Asus ZB602KL it lags until it becomes unisable. 

*Pressing back and entering deck again fixes the problem.*

###### Debug info

~~~
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = asus

Model = Zenfone Max Pro M1

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Zenfone Max Pro M1 Build/RQ3A.210905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/93.0.4577.82 Mobile Safari/537.36

ACRA UUID = 4dfdc298-daf5-40b2-b282-348c9d00c870

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
~~~

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

Interesting thing is, another deck "Core 2000" became broken, it complains that it does not do http requests anymore. But I don't use that deck anymore, it stays there inactive. Current deck did not experience any font problems so far.

**Comment by david-allison-1** [comment]
There's no relevant crash reports for the device listed. Could you post the debug info for the other device?

**Comment by burbilog** [comment]
> There's no relevant crash reports for the device listed. Could you post the debug info for the other device?

Right now I spent some time on Samsung tablet and got message that Anki program was stopped. Anki restarted and here is debug output:

~~~
AnkiDroid Version = 2.15.6

Android Version = 5.1.1

Manufacturer = samsung

Model = SM-P601

Hardware = universal5420

Webview User Agent = Mozilla/5.0 (Linux; Android 5.1.1; SM-P601 Build/LMY47X; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/93.0.4577.62 Safari/537.36

ACRA UUID = 7c19a91a-d416-4312-88ca-cb2244184480

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
~~~

> This is likely deck-specific, so an export of that would help, if it doesn't contain private information

Nothing secret (added .zip extension because github did not want to accept.apkg file):

[3way-20210921154003.apkg.zip](https://github.com/ankidroid/Anki-Android/files/7203103/3way-20210921154003.apkg.zip)

Note that this deck did not change much within few months and it worked OK until recently. I add about 10-20 words per week.

**Comment by mikehardy** [comment]
Thank you very much for all the details - I haven't checked the collection yet, but progressively bad performance followed by a crash is *usually* a webview not handling something about the card template well, and typically it has been "heavy fonts" in the past. I wonder if this will go that way? Anything like that sound familiar about your collection / this deck?

**Comment by david-allison-1** [comment]
Collection uses heavy fonts (japanese with stroke ordering).

**Comment by mikehardy** [comment]
https://docs.ankidroid.org/#customFonts

> Please note that AnkiDroid has to load the entire font into memory in order to use it, and fonts for Asian languages can be quite large. If you have an older device and notice AnkiDroid crashing frequently after installing a font, you may have exceeded your device’s memory limits. For Google Noto, it’s not recommended to use the combined CJK font, rather get the individual languages separately from here.

**Comment by burbilog** [comment]
Well, it may explain problems with Samsung tablet (but again, it worked OK with the same font months ago), but does not explain lag on ZB602KL with 4G RAM -- my RAM widget shows at least 1 gig free. I'll try to delete webview updates, may be google added something heavy to it...

**Comment by mikehardy** [comment]
Having free RAM on the system does not mean the process itself has available RAM or is using it correctly, unfortunately. In matters of performance things are very often unintuitive and normal assumptions about how things should behave frequently don't match reality. Makes related issues really "exciting" to troubleshoot ;-).

WebView updates happen all the time and frequently break things, unfortunately.

**Comment by burbilog** [comment]
Deleted webview updates on Samsung tablet and worked though the deck, ~200 cards, no problems. So, it seems to be introduced with recent webview update. BTW, there is new update from Google for webview, I'll update it on ZB602KL and check it tomorrow, with fresh amount of cards.

**Comment by mikehardy** [comment]
Happy to hear a success report! I'm sorry to say that if this is a WebView crash related to heavy fonts, it is really outside our control similar to all the previous ones that resulted in the documentation I linked. So I'm going to close this, but I do understand it's frustrating
