### ISSUE TITLE
Feature request: separate path for collection.media/ ?

### ISSUE THREAD

**Issue by sudomain** [ankidroid/Anki-Android#9532]
**Is your feature request related to a problem? Please describe.**

Spurred by [a question I recently raised in an old issue](https://github.com/ankidroid/Anki-Android/issues/3106#issuecomment-924146180) it seems over the years many people have wanted support for SD card storage due to the size of their collections. I don't think most Anki users actually have `collection.anki2` files composing several gigabytes, but rather very large `collection.media` directories. I anecdotally base this on the size of my collection:

    $ du -sh collection.anki2 collection.media
    86M     collection.anki2
    5.8G    collection.media

I think AnkiDroid is in an unique position as far as Anki clients go because of it's tendency to run on cheaper hardware with less storage (at least compared to desktop and iOS). Because of this unique position, I propose an unique solution and behavior that differs from desktop.

**Describe the solution you'd like**
A new preference under `Advanced -> AnkiDroid directory` for a collection.media directory.

**Describe alternatives you've considered**

**Additional context**
I'll someday (sooner rather than later) be in the market for a new phone. I'd rather put up a larger bounty for a SD card or other storage related feature for AnkiDroid than have to buy a more expensive phone specifically for the size of my collection.media.

**Comment by duanyang25** [comment]
I am currently working on this issue.

**Comment by sudomain** [comment]
@duanyang25 how's it going :)
