### ISSUE TITLE
Dev Process: enable linting unit tests

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9538]
Can be set via:

`lintOptions { checkTestSources true }`

https://developer.android.com/reference/tools/gradle-api/4.2/com/android/build/api/dsl/LintOptions

But, there's a long way to go, we likely want a baseline file to start with.

```
Wrote HTML report to file:///C:/GitHub/Anki-Android-Git/Anki-Android/AnkiDroid/build/reports/lint-results-amazonRelease.html
Lint found 412 errors. First failure:
C:\GitHub\Anki-Android-Git\Anki-Android\AnkiDroid\src\test\java\com\ichi2\anki\NoteEditorTest.java:269: Error: Field requires API level 23 (current min is 21): android.content.Intent#ACTION_PROCESS_TEXT [InlinedApi]
        Intent i = new Intent(Intent.ACTION_PROCESS_TEXT);
                              ~~~~~~~~~~~~~~~~~~~~~~~~~~
```

@mikehardy - this can be a good first issue if a baseline is used. 

What do you think? Baseline, or work through the issues to get a clean build

**Comment by david-allison-1** [comment]
We could add `Scope.TEST_SOURCES` if we only want to apply some of our custom rules to tests.

https://groups.google.com/g/lint-dev/c/rtjVpqHmY0Y

**Comment by mikehardy** [comment]
Tough one. Normally I'm really incremental but I never see us getting to zero if we don't just work through them - anything ignored now will likely be ignored forever, they're all vetted tests right, like this is our normal lint config right now? I think we should be able to pass that.

**Comment by david-allison-1** [comment]
Counts:

The main issue is `WrongConstant`, which is commonly used intentionally to ensure that constant values don't change

Count  | Code | Definition
-- | -- | --
1 | InlinedApi | Using inlined constants on older versions
42 | NewApi | Calling new methods on older versions
240 | WrongConstant | Incorrect constant
1 | DirectCalendarInstanceUsage | Use the collection's getTime() method instead of directly creating Calendar instances
2 | DirectSystemCurrentTimeMillisUsage | Use the collection's getTime() method instead of System.currentTimeMillis()
1 | InconsistentAnnotationUsage | Use androidx.annotation.NonNull and androidx.annotation.Nullable. See explanation for
45 | MissingCopyrightHeader | All files in AnkiDroid must contain a GPLv3-compatible copyright header
62 | NonPublicNonStaticFieldName | non-public non-static naming
1 | PrintStackTraceUsage |  Use Timber to log exceptions (typically Timber.w if non-fatal)
18 | VariableNamingDetector | Variable name should not use field prefixes.

**Comment by Arnold2381** [comment]
Hey @david-allison-1 I would like to continue this. Can you give some info on how to start with this?

**Comment by david-allison-1** [comment]
> Hey @david-allison-1 I would like to continue this. Can you give some info on how to start with this?

Set `checkTestSources true` in `lintOptions` in `lint.gradle`.

Run `./gradlew lintAmazonRelease`

And pick a subset of issues to fix. There's probably about 350 left

**Comment by Arnold2381** [comment]
@david-allison-1  for NewApi I am solving it by adding  `@RequiresApi(api = Build.VERSION_CODES.O)` before tests. Is that okay?

**Comment by david-allison-1** [comment]
Sounds good! If the tests pass, I'm happy

**Comment by mikehardy** [comment]
wait - does that imply that these tests will only run on Oreo (android 8) and higher? If so that means we'll lose coverage on code for a large percentage of devices we run on. If there are a lot of tests like this it would be better to make the code more compatible if possible

**Comment by david-allison-1** [comment]
Did we run Robolectric on older Android versions (besides via `@Config`?). 

Travis was an OS-based split, rather than an API-based split. From memory this was on a modern version of Android

**Comment by mikehardy** [comment]
I run robolectric locally against the full API skew periodically, yes.
Travis was OS and API (and JDK, actually) - it was a pretty bit matrix

**Comment by david-allison-1** [comment]
How does Robolectric handle these tests currently? 

If I'm reading right, it's exercising APIs which aren't provided by the Android version, so should crash

**Comment by mikehardy** [comment]
:thinking: good point, it definitely does not crash or I would have logged something prior. It appears to run through them fine
