### ISSUE TITLE
[Bug] SVG Images displayed with incorrect colors

### ISSUE THREAD

**Issue by bratkartoff** [ankidroid/Anki-Android#9543]
#### Description
Since today, the svg images from [this deck](https://ankiweb.net/shared/info/2109889812) (I haven't checked other decks) are displayed incorrectly. White is replaced with black, and all other colors are lighter than they should be (as if the black component was replaced with white).
##### Actual Result
How it looks:
![BugOnPhone](https://user-images.githubusercontent.com/46403888/134368306-ac20bdd5-9924-4709-94ea-73fa6ef62fc5.jpg)

##### Expected Result
How it should look (Anki Desktop), and how it looked in Anki Droid until yesterday:
![Desktop](https://user-images.githubusercontent.com/46403888/134368401-593e9ca2-30fe-4ff3-861d-bbeb33c1e460.png)

PNGs are not affected.

I suspect this issue is caused by an update to Android WebView. I updated the apps on my phone via Playstore yesterday, which included updating Android WebView to version 94.0.4606.50 (AnkiDroid was not updated).

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Xiaomi

Model = Mi 9 SE

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Mi 9 SE Build/RKQ1.200826.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.50 Mobile Safari/537.36

ACRA UUID = 02a8e8f3-abcd-4bf9-b670-826f61749e34

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Hi, likely our night-mode inversion playing up

Edit - Cards... Styling - add `.night_mode {}`

Let me know if this doesn't work.

Best,

David

**Comment by bratkartoff** [comment]
Thanks for the hint.
Editing the card's styling didn't solve the problem with any combination of "Night Mode" and "Appearance", but deactivating the dark mode for AnkiDroid in the MIUI settings does.

In the phone settings,
Display > More Dark Mode Options - uncheck AnkiDroid.

**Comment by mikehardy** [comment]
Oh how I hate hate hate MIUI forced dark mode. MIUI in general is a broken Android implementation and honestly I wish it did not exist.

**Comment by david-allison-1** [comment]
Xiaomi strikes again! 😉

https://github.com/ankidroid/Anki-Android/blob/a2eb2093ab29943b07b3452ab96eedc018234298/AnkiDroid/src/main/java/com/ichi2/utils/AdaptionUtil.java#L168-L171

Glad you got it sorted, thanks for taking the time to debug it!
