### ISSUE TITLE
ResetPassword is hidden behind the ```sign_up_description```

### ISSUE THREAD

**Issue by cdhiraj40** [ankidroid/Anki-Android#9547]
**Is your feature request related to a problem? Please describe.**
Whenever the keyboard opens the string resources always hides the reset password

**Describe the solution you'd like**
It can be stopped by adding ```windowSoftInputMode =adjust pan ```

**Describe alternatives you've considered**
None, But would love to hear the alternatives

**Additional context**

https://user-images.githubusercontent.com/75211982/134623794-4c63b2e3-c3a3-4296-97c8-5f1ce919e508.mp4

**Comment by cdhiraj40** [comment]
What are your thoughts? @mikehardy @david-allison-1

**Comment by mikehardy** [comment]
Please search for issues tagged good first issue and use those as your first contributions, it will really help
We're behind in several areas of project management (reviewing, merging, releasing etc) and contemplating a bunch of new features is not a high priority right now

**Comment by cdhiraj40** [comment]
> Please search for issues tagged good first issue and use those as your first contributions, it will help
> We're behind in several areas of project management (reviewing, merging, releasing, etc), and contemplating a bunch of new features is not a high priority right now

sorry for the inconvenience. I will sure look into that issue and try to work on them
