### ISSUE TITLE
[feature request] Select decks to sync

### ISSUE THREAD

**Issue by Lou-0** [ankidroid/Anki-Android#9548]
Hi,

I own a very basic phone, and I am so happy that the ankidroid app is so light, it's perfect for me.

However, some of my decks are a bit heavy (with MP3 files), and it fills my phone memory up pretty fast.
It would be amazing if I could choose to exclude these decks from synchronisation to save space.
I still use these decks on ankiweb and on pc.

Do you think this could be possible? People have recommended me to use different profiles but I thought it would be more convenient like this.

Good job on the app!
Have a nice day,
Lou

**Comment by mikehardy** [comment]
Hi there! Selective sync of decks is something that is just not supported in the ecosystem - if you want this feature you'll have to petition "upstream" on AnkiDesktop first at https://forums.ankiweb.net (though please search first as it may already be addressed)

In the meantime, separate profiles might be the ticket - that's something we don't support directly but we do make an effort to support indirectly via parallel releases https://github.com/ankidroid/Anki-Android/wiki/FAQ#how-to-use-different-anki-profiles
