### ISSUE TITLE
Support for Sardinian

### ISSUE THREAD

**Issue by asereze** [ankidroid/Anki-Android#9550]
I've completed the translation of AnkiDroid into Sardinian (ISO 639-1 code: "sc") on Crowdin. Could you please add it to the app?

**Comment by david-allison-1** [comment]
Wow! Already 100% on everything, that's incredible. Thank you so much!

https://crowdin.com/project/ankidroid/sc

**Comment by mikehardy** [comment]
Wow, pretty sure that is a new speed record! You'll have to sign up for the *alpha* testing group (not just beta) to see it, but the next release should have it after I merge @david-allison-1's pull request

:trophy: !

**Comment by asereze** [comment]
> Wow! Already 100% on everything, that's incredible. Thank you so much!

Thank you to you for your work!

> Wow, pretty sure that is a new speed record! 

Ahahahah nice! But I have to admit I "cheated", since I already had started working on it on Stringlate a few days ago, so I had most of the strings ready!

>You'll have to sign up for the _alpha_ testing group (not just beta) to see it, but the next release should have it after I merge @david-allison-1's pull request

Ok, thank you very much!

**Comment by david-allison-1** [comment]
Just to note, we've updated the following with additional format strings, could you check them out to confirm the `%s` are in the correct place

* https://crowdin.com/translate/ankidroid/8167/en-sc?filter=basic&value=0#q=sync_error_invalid_sync_server
* https://crowdin.com/translate/ankidroid/7291/en-sc?filter=basic&value=0#q=ankidroid_init_failed_webview

**Comment by david-allison-1** [comment]
I've updated a few strings which use `&amp;` instead of `&`:

* https://crowdin.com/translate/ankidroid/7291/en-sc?filter=basic&value=0#q=less_than_time
* https://crowdin.com/translate/ankidroid/8173/en-sc?filter=basic&value=0#q=note_editor_replace_newlines_summ

Needs fixing 🔨:
* https://crowdin.com/translate/ankidroid/7303/en-sc?filter=basic&value=0#q=about_content

@mikehardy This may be due to an `&amp;` issue: https://github.com/ankidroid/Anki-Android/issues/9319

**Comment by mikehardy** [comment]
2.16alpha16 is building now and after it finishes build + release upload + google processing (maybe an hour?) it should start showing up in the Play app on phones tied to the alpha channel :rocket:

**Comment by david-allison-1** [comment]
Done a manual test and it looks good, thanks!!

**Comment by david-allison-1** [comment]
Info.java: needs a regression test for each language - it currently crashes due to https://github.com/ankidroid/Anki-Android/issues/9550#issuecomment-926827683

**Comment by asereze** [comment]
> could you check them out to confirm the `%s` are in the correct place

Yes, they are correct.


> Needs fixing hammer:
>
>     * https://crowdin.com/translate/ankidroid/7303/en-sc?filter=basic&value=0#q=about_content

Done!
