### ISSUE TITLE
A lint failure should publish the HTML report as an artifact

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9553]
A lint failure should publish the HTML report as an artifact

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/issues/9552#issuecomment-926792874_

**Comment by mikehardy** [comment]
Actually, in practice this is more convenient, I think. The build log is already downloadable if needed, and it is more convenient than an artifact (which is delivered by zip and requires expansion etc) for what should be textual information

The new 4 lines here puts it right there where you want to see it immediately:

```groovy
android {
    lintOptions {
        textReport true
        textOutput "stdout"
        explainIssues false
        showAll true
        abortOnError = true
        warningsAsErrors true
        lintConfig file("../lint-release.xml")
        checkReleaseBuilds = true
    }
}
```

Testing locally and will PR

**Comment by david-allison-1** [comment]
Oh, if that doesn't truncate the log, it'd be perfect!

**Comment by mikehardy** [comment]
In practice it's never that many errors, and tens of thousands of log lines are acceptable per build step, with hundreds of thousand(s?) acceptable per build. Even then the full log is available via a quick click and it comes down text immediately (no zip mediation) so the happy path is much better and the failure mode is better too
