### ISSUE TITLE
Custom colors and themes/presets

### ISSUE THREAD

**Issue by Shidouuu** [ankidroid/Anki-Android#9568]
Customizable colors for individual menu items and such would be very nice over the default light/plain and dark/black.

Would like to see ability to change color of:

- Card text
- Specific elements of cards, like card title, definition, notes, etc.
- Menu bars
- Buttons
- Background
- Menu text
- Basically everything

Even if the only way to change them were a text box with a color id I'd be very happy! Also apologize if some can't be done, I'm not an expert on how Anki works.

**Comment by mikehardy** [comment]
Hi there!

I think a more maintainable path forward is probably to handle the Android 12 theming system but I'm not sure exactly what the APIs are yet https://duckduckgo.com/?t=ffab&q=android+12+theme+system

**Comment by Shidouuu** [comment]
Interesting, however many devices are not upgraded to or do not have Android 12. Also, wouldn't the colors only be changeable through the device settings, affecting the whole device rather than just AnkiDroid? And wouldn't it be more difficult to change the colors of individual elements?

**Comment by mikehardy** [comment]
The ability to do fully custom theming on a per-app basis is something very few users ask for (though yes, I hear your request), while it adds a great deal of complexity to the app, so it will likely never be a priority.

Supporting a general system way of doing it (which, ideally - though not necessary is easy) is possible.

Luckily most Android devices these days are pretty easily upgradable and vendors are actually doing it, Google put a lot of effort into that during Android 8, and we see that in our OS adoption curves here in our analytics - people are moving quickly from 9 to 10 and 11. I expect 12 will actually be adopted pretty quickly. That's a recent phenomenon, it certainly wasn't the case a few years ago - most devices were just stuck.

So given the system is solving the general idea of theming, most people actually should be able to get it by the time we will have any time to implement anything, and fully custom theming is (in my lived experience) a niche maintenance burden, I'm going to reiterate that Android 12 themes are probably the way to go here

I am happy to be proved wrong with a PR that implements fully custom themes and does not look like a maintenance headache for the future

**Comment by Shidouuu** [comment]
> I am happy to be proved wrong with a PR that implements fully custom themes and does not look like a maintenance headache for the future

Haha that seems like a challenge
