### ISSUE TITLE
[Bug] Gap above Deck Overview Screen on Boox Device

### ISSUE THREAD

**Issue by cyphar** [ankidroid/Anki-Android#9569]
###### Reproduction Steps

1. Install AnkiDroid on the Onyx Boox Nova Air 3.
2. Open it.
3. Notice that the tablet display mode is being used, but the Deck Overview screen has a white gap above the top bar.

I don't have any other tablets and couldn't find any screenshots of how this should look online, so I'm filing a bug because this seems like some sort of bug to me.

###### Expected Result

| Expected Result | Actual Result |
| -------------- | --------- |
|I don't own a tablet, so no image here. but I would expect the top bar to be continuous rather than having an offset.|![Screenshot_20210929-235242](https://user-images.githubusercontent.com/2888411/135282683-3a731a3d-34ba-4dff-ac73-52b325f85439.png)|

###### Debug info
<details>

```
AnkiDroid Version = 2.15.6

Android Version = 10

Manufacturer = ONYX

Model = NovaAir

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; NovaAir Build/2021-08-18_10-03_3.1_ff9edb7; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/88.0.4324.181 Safari/537.36

ACRA UUID = 3882a2b9-02b7-40a7-a67b-d37562e05d47

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

</details>

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Could you check the [alpha](https://github.com/ankidroid/Anki-Android/releases/download/v2.16alpha17/AnkiDroid-2.16alpha17.parallel.A.apk)? I believe this has been fixed

**Comment by cyphar** [comment]
Yes, it appears to be fixed in the alpha. Thanks. :smile_cat:
