### ISSUE TITLE
[Bug] On a card with two type inputs, AnkiDroid only lets you type into one; shows one answer on answer screen

### ISSUE THREAD

**Issue by Shidouuu** [ankidroid/Anki-Android#9572]
###### Reproduction Steps

1. Create a new card type with a 'Reading' and 'Meaning' field, and create a new deck with a note.
2. Type something into them.
3. Paste the following html into the front and back sides:
Front:
```
<span style="font-size: 60px; ">
<div class=jp> {{furigana:Reading}}</div>

{{type:Reading}}
{{type:Meaning}}
```
Back:
```
<hr id=answer>
<span style="font-size: 32px; ">
<div class=jp></div>
 {{Meaning}}<br>

<div  style="float: left; display: block; margin-left: 10%;">{{type:Meaning}} </div> 

<div style="float: right; display: block; margin-right: 10%;">{{type:Reading}} </div>
```
4. Now go back to the main menu and study the deck.
5. Enter something into the input, and observe.
###### Expected Result
On Anki desktop, on the answer screen it should show both answers and the correct one.

###### Actual Result
On AnkiDroid instead of two different answers it shows 2 of the first answer that is first in html. 

![Screenshot_2021-09-30-10-45-38-909_com.ichi2.anki.jpg](https://user-images.githubusercontent.com/36283656/135477835-4585707d-aad1-44eb-ad12-fe388869bb83.jpg)

_Edit:_ Oops, there's also supposed to be an `{{Expression}}` up there. I copied this from a modified shared deck and forgor that `{{Reading}}` is only for furigana and the answer (since the reading and furigana are the same). Now that I think about it, `{{furigana:Reading}}` should be up there too... Whatever, you get the point.

Also, it only lets you type into one input. Although you can circumvent this by checking the 'Type answer into card' box under 'Workarounds' in the advanced preferences, thereby showing two text boxes, it still only shows you the first answer on the answer screen.

![Screenshot_2021-09-30-10-34-55-211_com.ichi2.anki.jpg](https://user-images.githubusercontent.com/36283656/135477809-c178ad86-5bc1-43d8-af6e-438bb6082e6a.jpg)

###### Debug info
```
AnkiDroid Version = 2.16alpha17

Android Version = 9

Manufacturer = Xiaomi

Model = Redmi Note 5

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; Redmi Note 5 Build/PKQ1.180904.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/93.0.4577.82 Mobile Safari/537.36

ACRA UUID = 66b9de46-b3df-4508-b79b-1b07bd11507f

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

###### Research

*Didn't research much but this is a kind of niche issue so I assume it hasn't been solved already*
- [] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Oh my! Thanks for pointing this out - ecosystem compatibility is one of our fundamental goals (right next to "don't ever crash" and "don't lose data") so I tagged this up appropriately and hopefully someone has time to look at it

**Comment by david-allison-1** [comment]
Anki Desktop also does not handle this behavior correctly

**Comment by Shidouuu** [comment]
@david-allison-1 Oops, my mistake. I assumed it had worked yesterday when I was messing around yesterday. Hadn't gotten the chance to test it until I got home. Thanks for pointing it out! I'll make an issue on the Anki Desktop repo.

**Comment by Shidouuu** [comment]
Yeah turns out two types are just incorrect syntax. I would _love_ to be able to separate the readings and meanings onto different cards, but being a shared deck with thousands of cards, that might take awhile... Unless there's some magical script I can make to separate the furigana from the kanji.

**Comment by david-allison-1** [comment]
> Yeah turns out two types are just incorrect syntax. I would _love_ to be able to separate the readings and meanings onto different cards, but being a shared deck with thousands of cards, that might take awhile... Unless there's some magical script I can make to separate the furigana from the kanji.
> 
> Edit: Oh, the decks use sqlite, so it might not be that hard after all! Will have to mess around with that later today

Anki also has CSV import, which can be used to mass update cards (coming soon in AnkiDroid, probably won't make 2.16).

**Comment by mikehardy** [comment]
This is how Anki sucks you in. First you just start learning things, then you realize something is missing, then you realize that it was all built in a way that is actually kind of easily hackable, then you start developing on it and getting PRs merged ;-)

**Comment by Shidouuu** [comment]
Ehehehe, I didn't think it'd turn into a programming journey when I started using Anki, but as soon as I started customizing it...
