### ISSUE TITLE
[Bug] "is:learn is:review" not showing any cards

### ISSUE THREAD

**Issue by szalejot** [ankidroid/Anki-Android#9573]
###### Reproduction Steps

1. Open Card browser
2. Put "is:learn is:review" as a search condition.

###### Expected Result
Should filter cards that have lapsed and are awaiting relearning. That how it works on desktop Anki.

###### Actual Result
No cards are shown.

###### Debug info
AnkiDroid Version = 2.15.6

Android Version = 8.0.0

Manufacturer = asus

Model = ASUS_Z01HD

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 8.0.0; ASUS_Z01HD Build/OPR1.170623.026; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.61 Mobile Safari/537.36

ACRA UUID = ffc51eb1-d4d4-4314-a51d-a8de3cb61665

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
If someone picks this up as a first issue and attempts to triage it: You will need to get the latest Anki Desktop, the latest AnkiDroid, get a collection and do a few reviews and get it synced across a new account on AnkiWeb, and make sure that everything is set up for testing with a few cards in learning and a few in review etc. Then reproduce on both platforms, and start digging into AnkiDroid to see why the search results are unexpected...

**Comment by voidplayer** [comment]
Maybe related #8307

**Comment by prateek-singh-3212** [comment]
> Can I try this?

@Guneetconvent2002 Yes, Go ahead.
