### ISSUE TITLE
Hierarchical sidebar or page feature for ankidroid?

### ISSUE THREAD

**Issue by MmZy1** [ankidroid/Anki-Android#9580]
I suggest Maybe ankidroid can have sidebar option in browser like anki desktop that can be access by a small button and then view the same contents like tags and decks but in a "tree hierarchical style" and keep the filter by tag and flag options, so we can benefit from hierarchical tags with :: seperator like anki desktop.
Thanks for your help

**Comment by mikehardy** [comment]
tagging this for ecosystem compatibility analysis to compare our behavior with current anki desktop
It may be that this feature is too difficult to do in the constrained screen size that is a typical mobile device, but who knows...

**Comment by MmZy1** [comment]
@mikehardy 
For size issue, you can make it like the way sidebar shows in notion app in mobile:
![Screenshot_2021-10-04-08-44-22-544_notion id](https://user-images.githubusercontent.com/91826472/135800274-665f121d-e3d2-43bc-90ca-f45c2c6cbe43.png)
It's easy to use I think and size will not be problem like this
