### ISSUE TITLE
"filtered/virtual deck" -> options -> options -> "activate second filter" is missing

### ISSUE THREAD

**Issue by Golddouble** [ankidroid/Anki-Android#9593]
**Is your feature request related to a problem? Please describe.**

In Anki Desktop in the options of a "filtered deck", I can enable a second
filter. I have done this.
But in Ankidroid I have not found the function "second filter". It looks
in the GUI as if there is only one filter possible.

When I sync now my Anki desktop (with a second filter in options) with
Ankiweb and then sync Ankiweb with Ankidroid, then Ankidroid still only
shows one filter.

Question: What is right?
A) Ankidroid does only show 1 filter, but it has nevertheless both
filters active in the deep, it's just not visible for the user and also
not edible. That means although you can not see the second filter, you
have now nevertheless the same filter in Ankidroid as you have created
in Anki desktop.
B) Ankidroid does not support the second filter. So the filter you have
created in Anki desktop is converted into a "one filter". This means you
now have not the same filter in Ankidroid as you had originally created
in Anki Desktop.
C) Other 

**Describe the solution you'd like**
If A) is right, then please make both filters visible in Ankidroid.
If B) is right, then this means that Ankidroid is not compatible to Anki Desktop. Please make it compatible again by adding the function "second filter" in "filtered deck" -> options -> options

**Comment by david-allison-1** [comment]
Hi, have you tried our alpha builds? I believe we've implemented this feature
