### ISSUE TITLE
Existing clients should have their custom sync server default value removed

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#9600]
AnkiWeb has moved away from `https://msync.ankiweb.net` since 2017, but we provided this as a default value to clients in a preferences screen and should clear it

----

This default is persisted to the preferences when the screen is viewed. We should presumably remove it for current clients as well as avoiding suggesting it to new users

Either via:

* Adding a preference upgrade to `PreferenceUpgradeService.kt`

```kotlin
/**
 * msync is a legacy URL which does not use the hostnum for load balancing
 * It was the default value in the "custom sync server" preference
 */
internal class RemoveLegacyMediaSyncUrl : PreferenceUpgrade(3) {
	override fun upgrade(preferences: SharedPreferences) {
		val mediaSyncUrl = CustomSyncServer.getMediaSyncUrl(preferences) ?: return
		if (mediaSyncUrl.startsWith("https://msync.ankiweb.net")) {
			preferences.edit { remove(CustomSyncServer.PREFERENCE_CUSTOM_MEDIA_SYNC_URL) }
		}
	}
}
```

and yielding an instance of the class

https://github.com/ankidroid/Anki-Android/blob/250097f54e0bf28371770275b613bc0e5e5b3248/AnkiDroid/src/main/java/com/ichi2/anki/servicelayer/PreferenceUpgradeService.kt#L69-L72

* Or: special-case the logic in `CustomSyncServer` to return null

https://github.com/ankidroid/Anki-Android/blob/8ada79b2698092c6f53bcba66e835e696b8d8e05/AnkiDroid/src/main/java/com/ichi2/anki/web/CustomSyncServer.java#L31-L34

_Originally posted by @david-allison-1 in https://github.com/ankidroid/Anki-Android/pull/9470#pullrequestreview-742586224_

**Comment by david-allison-1** [comment]
Does need testing to see if we can get away with one value being null, I tested the area fairly heavily the last time I was here and I'm fairly sure we can, but syncing is somewhere we can't screw up
