### ISSUE TITLE
AnkiDroid compresses images while adding causing text to become unreadable

### ISSUE THREAD

**Issue by user1823** [ankidroid/Anki-Android#9605]
When I add images (e.g. diagrams) to my Anki cards using AnkiDroid, it compresses the images. This sometimes makes the resolution too poor that the text (in the images) is not readable. Kindly fix this issue.

**Comment by david-allison-1** [comment]
Hi, are you using copy/paste, or the gallery?

**Comment by user1823** [comment]
> Hi, are you using copy/paste, or the gallery when you add images?

I am using the Gallery.
Pin icon -> Add image -> Gallery
