### ISSUE TITLE
issue when Adding Cloze Note On some android phones

### ISSUE THREAD

**Issue by Kale123456** [ankidroid/Anki-Android#9616]
https://1drv.ms/v/s!Aoq6hTbE2xg2jBFWJ44iBnAmTbbD

That link contains the screen recording of how the issue took place. Also if you need logs, please tell how to do them. This issue is persistent with many other friends who use ankidroid, making us have to use the computer app in order to create cloze notes.Other stuff:

If you need any more information, just reply i will reply within the same day. For logs tell me how to do them plz. That exact thing happens on my 2 devices:
Oneplus 8, Xiaomi K20 Pro. The app version is:2.15.6

**Comment by david-allison-1** [comment]
The file has been deleted. Could you upload it again?

**Comment by Kale123456** [comment]
https://1drv.ms/v/s!Aoq6hTbE2xg2jBFWJ44iBnAmTbbD

Im sorry guthub wouldnt let me upload a 20 second screen recording

**Comment by mikehardy** [comment]
No crash reports with that UUID unfortunately.

Got this from a K20 though

```


Stack Trace | com.ichi2.utils.JSONException:  org.json.JSONException: Value null at did of type org.json.JSONObject$1  cannot be converted to long	at com.ichi2.utils.JSONObject.getLong(JSONObject.java:2)	at com.ichi2.anki.NoteEditor$SetNoteTypeListener.onItemSelected(NoteEditor.java:12)	at android.widget.AdapterView.fireOnSelected(AdapterView.java:957)	at android.widget.AdapterView.dispatchOnItemSelected(AdapterView.java:946)	at android.widget.AdapterView.access$300(AdapterView.java:55)	at android.widget.AdapterView$SelectionNotifier.run(AdapterView.java:910)	at android.os.Handler.handleCallback(Handler.java:938)	at android.os.Handler.dispatchMessage(Handler.java:99)	at android.os.Looper.loop(Looper.java:223)	at android.app.ActivityThread.main(ActivityThread.java:7665)	at java.lang.reflect.Method.invoke(Native Method)	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)Caused by: org.json.JSONException: Value null at did of type org.json.JSONObject$1 cannot be converted to long	at org.json.JSON.typeMismatch(JSON.java:101)	at org.json.JSONObject.getLong(JSONObject.java:528)	at com.ichi2.utils.JSONObject.getLong(JSONObject.java:1)	... 12 more
-- | --



```

**Comment by Kale123456** [comment]
By "getting that from a K20" what do you mean. Also please tell me something i can understand as i don't understand what the report contains. Thanks😄

**Comment by Kale123456** [comment]
AnkiDroid Version = 2.15.6

Android Version = 11

Manufacturer = Xiaomi

Model = Redmi K20 Pro

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; Redmi K20 Pro Build/RQ3A.210605.005; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.71 Mobile Safari/537.36

ACRA UUID = 1050ccb5-c136-48ba-89fd-482f3beb12cc

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

Please check this one. 

Many Thanks
