### ISSUE TITLE
Automatic Language Selection feature in the Note Editor for multilingual keyboards

### ISSUE THREAD

**Issue by gthfaria** [ankidroid/Anki-Android#9618]
According to the Anki manual "This feature allows you to define a default language to be used in your keyboard for a field in a note type."

I have tested this feature and it works very well when you are editing or adding a card. However, when you are reviewing a card that uses the "type in the answer" feature, the automatic language selection does not seem to work.

**Comment by david-allison-1** [comment]
It's a prompt to perform some refactoring on the "Type Answer" functionality - I don't like touching aspects of `AbstractFlashcardViewer` without trying to make things a little more manageable. The code's a beastie.

After that, it's a really simple extension

**Comment by david-allison-1** [comment]
Direct link to a valid release if you don't want to use Google Play:  https://github.com/ankidroid/Anki-Android/releases/download/v2.16alpha23/AnkiDroid-2.16alpha23.parallel.A.apk
