### ISSUE TITLE
type-in answer doesn't appear in card previews

### ISSUE THREAD

**Issue by Shidouuu** [ankidroid/Anki-Android#9626]
When previewing a card during editing, it doesn't show the type-in, forcing you to save your edits in order to test it.

**Comment by mikehardy** [comment]
Hmm - I don't see a benefit during preview in actually trying to compute the difference (that is: react to the results of typing) but are you saying that the type in answer box doesn't even render?

**Comment by david-allison-1** [comment]
This has been on my TODO list: it's confusing for onboarding as it implies that the "type answer" functionality isn't working

**Comment by zihanxu3** [comment]
> Hi, I'm new here but I think this issue is suitable for me. Could I work on this for a while?

Hi are you still working on this one? If not I can give it a try!

**Comment by mikehardy** [comment]
This one has a PR in progress @zihanxu3 - #9684
