### ISSUE TITLE
[Bug] Automatic Display Answer does not advance if TTS is enabled and there is no text

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9630]
###### Reproduction Steps

1. Enable Auto Display Answer
2. Enable "Advanced - Read Text"
3. View a card with no back

###### Expected Result

1. The card moves on after the delay

###### Actual Result

1. Nothing

###### Debug info
2.15.6

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

## Related

#9170

**Comment by prateek-singh-3212** [comment]
I would like to work on this issue.

**Comment by david-allison-1** [comment]
Awesome, sounds good to me

**Comment by david-allison-1** [comment]
Thanks!

Issue is

https://github.com/ankidroid/Anki-Android/blob/498be443b67d3079d57a5ea17b4bd0fa79542aa4/AnkiDroid/src/main/java/com/ichi2/anki/ReadText.java#L161-L169

Blocked temporarily on #9674
