### ISSUE TITLE
Return a list of cards programmatically instead of opening the card browser with a query.

### ISSUE THREAD

**Issue by GitGondola** [ankidroid/Anki-Android#9633]
When learning Japanese, cards may share a kanji. I want to generate a list of words from other cads that share a kanji with part of the question kanji.
I would have this as an additional function, not one that replaces "AnkiDroidJS.ankiSearchCard(query)"

**Comment by mikehardy** [comment]
It's javascript, so you can do anything you like with the results I think?

**Comment by GitGondola** [comment]
Do you have a basic example?

**Comment by infinyte7** [comment]
I think it is not implemented -> to get card contents for particular note using note id. 
There are some desktop addons which perform such action.

**Comment by infinyte7** [comment]
I have searched for existing function in AbstractFlashcardReviewer `col` and `mSched` but haven't found any function to so it needs to implement the java function first.
I want to implement this feature. Any additional information will be helpful.

**Comment by GitGondola** [comment]
why close it if it isn't fixed.

**Comment by mikehardy** [comment]
@GitGondola why leave issues open forever if no one cares enough to fix them? The issues list is for active issues, active is "it's an issue, and people care enough to work on it". Happy to reopen if you want to work on it. Otherwise, it'll be here forever for reference.

**Comment by krmanik** [comment]
It is in development.
