### ISSUE TITLE
[Bug] Opus sound files greyed out in file picker although accepted when renamed as mp3

### ISSUE THREAD

**Issue by Heineken** [ankidroid/Anki-Android#9639]
This is actually about two bugs, one preventing desired functionality, the other one providing it nonetheless via a hidden feature.

###### Reproduction Steps
1. Add/edit flash card sound 
2. Add sound from library, point to local storage directory containing an opus file -> grey, i.e. not selectable
3. Rename opus file to .MP3
4. select it in 2. -> works just fine (in spite of wrong extension)

###### Expected Result
In step 2.: that opus files be accepted (quite handy as thus WhatsApp voice messages from a native speaker can be used directly as pronunciation examples)

optionally in step 4.: That using a sound file with a wrong extension give an error or, better yet, a warning with the option to automatically correct the file extension.

###### Actual Result
opus file not selectable
opus file renamed to .mp3 is accepted and replayed

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".
Using 2.15.6

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
It appears ogg support should get it though `.opus` is also a possibility https://en.wikipedia.org/wiki/Opus_(audio_format)#Containers

That would solve the first item

The second item is a platform thing, we won't even know (at the code level) if a sound file has an unexpected name/extension. The platform plays it or it doesn't, but we get no information, so that one will be a "won't fix"

**Comment by david-allison-1** [comment]
This works on my Android 11. I believe that this would always have worked (as the mime type is `audio/ogg`).

This doesn't work on an API 26 emulator. This implies that there's additional work to do aside from #9225. I'll investigate

**Comment by david-allison-1** [comment]
Ugg... MIME is `application/octet-stream` (binary file). 

I'm open to suggestions, but we can't get a good UX here. 

The best case would likely be a "allow all files" somewhere in the advanced prefs.

This is probably a WONTFIX and a phone OS update will fix this.

@mikehardy
