### ISSUE TITLE
Lint checks don't report wrong formatting and wrong code style

### ISSUE THREAD

**Issue by ShridharGoel** [ankidroid/Anki-Android#9650]
Lint checks pass even when formatting or code style is improper.

For example, the following passes:
```
if (someCondition)
{
    // Do something
}
```

Lint should report that the opening brace should be in the same line as the `if` statement.

For more context, check this pull request: https://github.com/ankidroid/Anki-Android/pull/9647

**Comment by ShridharGoel** [comment]
@david-allison-1 It was for Java files. For Kotlin files, the pre-commit hook would format them unless it is skipped for some reason.

**Comment by david-allison-1** [comment]
I expect that this will be a fair amount of effort to write, and work would be better placed in continuing the Kotlin migration
