### ISSUE TITLE
Options to inject js code from deck options to modify scheduling information during reviewing

### ISSUE THREAD

**Issue by krmanik** [ankidroid/Anki-Android#9665]
**Is your feature request related to a problem? Please describe.**
The features is currently in beta in Anki Desktop.

<img src="https://user-images.githubusercontent.com/12841290/137773944-fb346b39-a869-4984-9044-79aae2fdaad4.png" height=400px></img>

**Describe the solution you'd like**
EditText view to insert js code with `states` provided.

**Describe alternatives you've considered**

**Additional context**
https://faqs.ankiweb.net/the-2021-scheduler.html#add-ons-and-custom-scheduling

**Comment by david-allison-1** [comment]
I can't say I've looked into the new scheduler massively, but I believe that it'll just be a call from the WebView to the Rust (via the Java). 

![](https://media.giphy.com/media/9fga0fpr00vK/giphy.gif)

**Comment by infinyte7** [comment]
To be implemented in next version of AnkiDroid.

**Comment by infinyte7** [comment]
To be implemented in next version of AnkiDroid.

**Comment by dae** [comment]
To support this, the reviewing screen will need to be refactored to store the next states, and will need to call the JS function after a card is shown. The existing API in AbstractSched will need to be changed.
