### ISSUE TITLE
[Bug]full screen mode on miui12.5 can not be hided well in the next card if i call my top-bar.

### ISSUE THREAD

**Issue by nanoTiO2** [ankidroid/Anki-Android#9694]
[######](url) Reproduction Steps

1. open the full screen mode in miui12.5 (redmi k30pro) (anki2.16 alpha23)
2. start learning, and touch the top of the screen( slide it )
3. then in the next card,  top-bar of anki is not hided .

###### Expected Result

top-bar is hided

###### Actual Result

top bar is fixed in the screen,

explain:top-bar i mean, the place(how many card i ought to learn, time i need to spent on not the notification bar)

 and only i switch the night mode or open the setting, and come back, this bar could be hindered successfully 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by AkechiShiro** [comment]
Hi, @nanoTiO2 could you precise your exact MIU12.5 information (by reading it inside your Android settings, About your device), I'm under MIUI 12.5 `Global 12.5.6.0 (RKHEUXM)` with a Xiaomi Poco F3 and I can't reproduce the bug using the latest alpha (2.16alpha34), either it's due to a different version of MIUI12.5, or maybe I've made a mistake while trying to reproduce it.

**Comment by nanoTiO2** [comment]
i have updated my software and system to the newest yesterday, and the bug still occours, the system of my Miui is12.5.7[rjkcnxm], my phone is redmi k30pro zoom editon, and the the information below i dont konw how to translate to english, so i use this here.
(内核版本 core version ):4.19.113—perf-gec90c723c482.

first i switch the fullscreen (hide answers bar and topbar)in display in review setting
sec i study with finger guestures
thi i make a motive to call the miui information bar
end i come to the next card with.this 
![9A74763B-74FD-4E97-A193-80217B1CEA8E](https://user-images.githubusercontent.com/58650184/145308784-de445daa-45c2-4e42-8c56-1f47b3d47b25.jpeg)

**Comment by AkechiShiro** [comment]
Sorry for the delayed response @nanoTiO2 , I received not long ago an update for MIUI 12.5.7 however I'm still unable to reproduce your bug, so far what I tried to reproduce it :

- 1 : Activate full screen (hide topbar and hide answer buttons)
- 2 Activate gestures.
- 3 I try to learn from a deck, swipe down on the screen, answer/move to the next card, and it seems all good to me.

Does this bug happen if you disable gestures ?
What kind of gesture do you use for it to happen ? Do you slide down ? Up ? Left, right ?

**Comment by nanoTiO2** [comment]
I slide down, look at the video please.and I can not disable my guestures when I open the full screen mode

发自我的iPad

**Comment by AkechiShiro** [comment]
I saw your video, could you maybe share me your card deck ? I can't seem to reproduce your bug but it might be related to your deck of cards maybe ? (If not it's probably very specific to your device)

Here is a video captured on my phone trying exactly the bug but failing to do so.

https://user-images.githubusercontent.com/14914796/148656505-ab32f12b-9bbe-46e4-98fd-281f651897e5.mp4

**Comment by nanoTiO2** [comment]
thank you I don't know what I did . i can use this function as you too. even I don't update my system or anki droid .maybe it is some bugs from miui .thank you
