### ISSUE TITLE
Card Template Preview: Check UX

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9696]
On an empty note we currently show "a card couldn't be generated". I feel this is better than defaulting to "Front/Back", but I'm not sure if this is the correct new user UX?

Maybe we want to use field names if all the fields are empty?

----

I'll defer the UX question to however Anki Desktop does it with a tie-break (in case they don't do anything similar) to `%s field contents here` or similar as a separate issue/PR

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/9689#pullrequestreview-786796248_

**Comment by mikehardy** [comment]
pending merge of PR #9739
