### ISSUE TITLE
[Bug] All audios are played when I click on any one of the audio buttons

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#9722]
###### Reproduction Steps

1. Have a deck with a template with multiple audios on the back template (I haven't tested on the front template) [I am using this [desk](https://ankiweb.net/shared/info/238128422) with a modified front/back template cf below]
2. Start the study of this deck and show the answer
3. If needed, wait for all the sound to finish and then click on one of the audio button

###### Expected Result
When one of the button is clicked only the audio of this button is played not the other ones. 

###### Actual Result
All the audio are played in the same order as they appear in the template

###### Other
The back template is working as expected on Anki Desktop: when one of the button is clicked only the audio of this button is played not the other ones. 

Here is the back template:
```
{{FrontSide}}
<br><br>
<div style=' font-size: 0px ;  text-align: right;'>{{Sound}}</div>
<div style='font-family: Arial; font-size: 70px;color:#FF80DD;'>{{IPA}}</div>

<div>
<div  style='font-family: Arial; font-size: 30px;color:#9CFFFA; text-align:left;'>
 {{Meaning}}<div style=' font-size: 0px ;  text-align: right;'>{{Sound_Meaning}}</div></div>

<br><br>
<div  style='font-family: Arial; font-size: 30px;color:#9CFFFA; text-align:left;'>
&nbsp;→&nbsp;{{Example}}<div style=' font-size: 0px ;  text-align: right;'>{{Sound_Example}}</div></div>
</div>

```

And here is the front template:
`<div style='font-family: Arial; font-size: 70px;color:#FF80DD;'>{{Front}}</div>
`
###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

AnkiDroid Version = 2.15.6

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.85 Mobile Safari/537.36

ACRA UUID = ba2a7ac3-aa20-4edc-8251-0b3de0ebd8be

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by MagTun** [comment]
I have tried the new alpha (2.16alpha29) and I still get the same bug. Also my friend, which has the same phone has the same bug (he had it already on the last regular release and now also on the 2.16alpha29)

**Comment by MagTun** [comment]
As a workaround/debugging, I have added to the back template a simple button which calls only the audio file via the `HTMLAudioElement`.

But I still get the sane bug: when I click this button all the audios are played, always in the same order as they are set in the HTML.  

I tried several combinaisons by changing the order of the audio in the HTML and by calling different audio in the function `audioWorkaround()`, but they all give the same result: all the audios are played in the order set by the HTML. 

Here is this new template:

```


{{FrontSide}}
<br><br>
<button onclick="audioWorkaround()">Audio workaround</button>
<div style=' font-size: 0px ;  text-align: right;'>{{Sound}}</div>
<div style='font-family: Arial; font-size: 70px;color:#FF80DD;'>{{IPA}}</div>

<div>
<div  style='font-family: Arial; font-size: 30px;color:#9CFFFA; text-align:left;'>
 {{Meaning}}<div style=' font-size: 0px ;  text-align: right;'>{{Sound_Meaning}}</div></div>

<br><br>
<div  style='font-family: Arial; font-size: 30px;color:#9CFFFA; text-align:left;'>
&nbsp;→&nbsp;{{Example}}<div style=' font-size: 0px ;  text-align: right;'>{{Sound_Example}}</div></div>
</div>

<script>
function audioWorkaround(){
var audio = new Audio('{{Sound}}');   // even though only {{Sound}} is called, {{Sound_Meaning}} and {{Sound_Example}} are played.
audio.play();
}
</script>
 
```

**Comment by WiliTest** [comment]
@MagTun I tried again AnkiDroid Version 2.16alpha33 and it's working!

**Thank you to those who fixed it!** 
(I'm very happy!)

**Comment by MagTun** [comment]
I just retried with the same deck and now it's working fine. 
I don't know what fixed this bug but to give some clues, since my last post, I have :
- uninstalled the deck 
- updated to AnkiDroid-2.16alpha32-armeabi-v7a.apk 
- uninstalled AnkiDroid to reinstall AnkiDroid-2.16alpha29-armeabi-v7a.apk  (because 2.16alpha32 was buggy)
- reinstalled the deck

(Since it seems fixed but without an obvious fix, I am not sure if I should close this issue or keep it open)
