### ISSUE TITLE
Options for new ease when rescheduling cards for review

### ISSUE THREAD

**Issue by lukexodus** [ankidroid/Anki-Android#9740]
In the latest version, when "rescheduling cards for review," it sets the new ease of the card to 250%

Please add an option to choose what ease to change to when rescheduling:

- starting ease in the deck options
(I often change my starting ease often for different decks. 250% is not always applicable for any cards, some is easier (ex. 300%), some is harder (ex. 200%))

- doesn't change the ease (use the card's current ease)

- or input the desired ease or choose from preselected ease amounts (ex. 200%, 225%, 250%, etc.)

This feature is added to Anki (desktop) in version 2.1.45. The new ease when setting new interval is the starting ease in the deck options. This feature is good enough for me if you can emulate it. But if you can add the options mentioned above, that would be better. Any alternatives is welcome.

**Comment by dae** [comment]
Closed by #14171.
