### ISSUE TITLE
Long deck name are not in deck selection menu

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#9750]
**Is your feature request related to a problem? Please describe.**
As seen on attached picture, when the name is long, it is truncated. It's a trouble because the last part of the name is actually the most relevant for me. While the earliest part allow me to sort decks

![Screenshot_20211101-035929_AnkiDroid.jpg](https://user-images.githubusercontent.com/357361/139615757-c94f44c0-fc3a-451a-aea3-33b6104a3f79.jpg)

**Describe the solution you'd like**
When the name is longer, the name is split on multiple line. Same way it is when you click on the deck and open the menu

**Describe alternatives you've considered**
I've considered changing the textView to setSingleLine(false) in getDropDownView. I've also considered using `                        android:layout_height="wrap_content"` in note_editor's Spinner. Neither work

**Comment by codingtosh** [comment]
Hi @Arthur-Milchior , I would like to take this up. I think I have a working solution, ss for reference

![Screenshot_20211102-011712_AnkiDroid.jpg](https://user-images.githubusercontent.com/81802035/139732245-3aa8125f-29c8-404e-a57c-618e0ebedebe.jpg)

**Comment by Arthur-Milchior** [comment]
Seems wonderful. I can't wait to see how you did it.
@david-allison-1 or @mikehardy would you be ok with this change in behavior. It would affect only people with long deck name

**Comment by codingtosh** [comment]
@Arthur-Milchior The approach is actually similar to yours, just the diffference that getView had to be overridden, not getDropDownView as we want to target the Spinner's view, not its dropdown/dialog view. I have included the inspection process in the PR for your reference. Please review.

**Comment by Arthur-Milchior** [comment]
After more test, on my phone, it breaks when deck names are at least than 3 lines long. At least I saw the beginning of the third line, so that's already better
