### ISSUE TITLE
Disable "html_javascript_debugging" for unit/android tests

### ISSUE THREAD

**Issue by david-allison-1** [ankidroid/Anki-Android#9751]
This code will make tests slower, as it unnecessarily introduces IO to the card rendering pipeline

https://github.com/ankidroid/Anki-Android/blob/e55051d054a10fcf8781095d874a73ec811a08ee/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L333-L335

**Comment by pree-T** [comment]
May I work on this?

**Comment by mikehardy** [comment]
@pree-T you've asked for four items - please focus on one of them first to make sure you understand how to get a PR through, but once you've decided which of the four you want to start with, by all means go for it!
