### ISSUE TITLE
UI for buttons in adding multimedia.

### ISSUE THREAD

**Issue by KasinaDheeraj** [ankidroid/Anki-Android#9763]
**Is your feature request related to a problem? Please describe.**
No, this feature isn't a problem. But the UI has been with basic buttons, So I want to enhance them to good looking outline buttons.
**Describe the solution you'd like**
I would like to change UI as shown in below screenshots basic to outline.

**Additional context**
<img src="https://user-images.githubusercontent.com/58620100/140020985-59025a26-38a0-42d7-8def-b3fa61d7cfe3.png" height="550" /><img src="https://user-images.githubusercontent.com/58620100/140021051-f13cd045-717e-4dd4-ae14-451a6cf2eebb.png" height="550" /><img src="https://user-images.githubusercontent.com/58620100/140021107-5d13c536-c141-495e-8833-73154089aeb5.png" height="550"/>

**Would you like to work on this?**
Yes, I would like to contribute to it.

**Comment by theyashgrover** [comment]
I would like to work on this issue (as well) , Once It's reviewed and accepted.

**Comment by david-allison-1** [comment]
I feel the change is preference based and conflicts with our current design (as questionable as it may be).

I'll wait for other maintainers, but it's a weak 'no' from me, especially since we have many more issues which will bring concrete improvements if resolved. 

Also for consideration: https://github.com/ankidroid/Anki-Android/wiki/User-Interface-contribution

**Comment by mikehardy** [comment]
Agreed on the week no - I'm not 100% against this, its just that it is not a priority and will in my experience immediately lead to a bunch of back and forth and then a preferences toggle to leave them alone, it's an inefficient use of developer time vs the current list of real problems + things that we must do (if not now, eventually, like handling deprecation issues)
