### ISSUE TITLE
[Deprecation] InputConnectionCompat.createWrapper API deprecated

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#9775]
###### Reproduction Steps

1. update dependencies (androidx core-ktx #9725)
2. run a build
3. see build warning failing build

###### Expected Result

clean compile without ignoring deprecation

###### Actual Result

```
/home/mike/work/AnkiDroid/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/FieldEditText.java:146: warning: [deprecation] createWrapper(InputConnection,EditorInfo,OnCommitContentListener) in InputConnectionCompat has been deprecated
        return InputConnectionCompat.createWrapper(inputConnection, editorInfo, (contentInfo, flags, opts) -> {
                                    ^
```

We stumbled on this deprecation:
https://developer.android.com/reference/androidx/core/view/inputmethod/InputConnectionCompat#createWrapper(android.view.inputmethod.InputConnection,%20android.view.inputmethod.EditorInfo,%20androidx.core.view.inputmethod.InputConnectionCompat.OnCommitContentListener)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by pree-T** [comment]
May I work on this?

**Comment by murugu-21** [comment]
I think this issue can be closed now

**Comment by murugu-21** [comment]
I think this issue can be closed now @mikehardy

**Comment by mikehardy** [comment]
@murugu-21 has the related work been done to handle this deprecation? I see no link to the related PR ?

**Comment by pree-T** [comment]
Is this issue open? I would like to work on it. Can someone help me?

**Comment by mikehardy** [comment]
You can work on it but I have no time for assistance beyond what I put in the description, sorry

**Comment by david-allison-1** [comment]
@pree-T Sounds good to me

**Comment by pree-T** [comment]
Thanks for assigning me this issue @david-allison-1 . What am I supposed to do as a fix for this issue? I tried to reproduce it but did not get any such warning.

**Comment by david-allison-1** [comment]
> Thanks for assigning me this issue @david-allison-1 . What am I supposed to do as a fix for this issue? I tried to reproduce it but did not get any such warning.

What change did you make? Did you sync gradle afterwards?

**Comment by pree-T** [comment]
> > Thanks for assigning me this issue @david-allison-1 . What am I supposed to do as a fix for this issue? I tried to reproduce it but did not get any such warning.
> 
> What change did you make? Did you sync gradle afterwards?

I updated all the dependencies and synced the gradle files.

**Comment by david-allison-1** [comment]
Okay, rereading, the issue appears to the to resolve the linked deprecation.

I believe it's ignored in 35633410ba46cdd907a973d031e183d3d157ad4d

**Comment by pree-T** [comment]
So what am I supposed to do Sir @david-allison-1 ?

**Comment by pree-T** [comment]
I am facing difficulty in figuring out the code syntax which will replace the deprecated API. Can someone help me ? @david-allison-1

**Comment by david-allison-1** [comment]
Sorry, I don't have free time for mentoring. All I'd do would be to Google for the replacement

**Comment by pree-T** [comment]
> Sorry, I don't have free time for mentoring currently. All I'd do would be to Google for the replacement

I tried googling but did not find any proper relevant answer.

**Comment by david-allison-1** [comment]
https://developer.android.com/reference/androidx/core/view/inputmethod/InputConnectionCompat#createWrapper(android.view.inputmethod.InputConnection,%20android.view.inputmethod.EditorInfo,%20androidx.core.view.inputmethod.InputConnectionCompat.OnCommitContentListener)

**Comment by pree-T** [comment]
> https://developer.android.com/reference/androidx/core/view/inputmethod/InputConnectionCompat#createWrapper(android.view.inputmethod.InputConnection,%20android.view.inputmethod.EditorInfo,%20androidx.core.view.inputmethod.InputConnectionCompat.OnCommitContentListener)

I have checked this. However, no proper syntax is mentioned in this page.

**Comment by mikehardy** [comment]
@pree-T then this is not the issue for you. You need to be able to do these tasks with the information we've already given or it is not a fit, sorry
