### ISSUE TITLE
Handle Android 11 package visibility restrictions interaction with package resolution

### ISSUE THREAD

**Issue by mikehardy** [ankidroid/Anki-Android#9825]
Handle Android 11 package visibility restrictions interaction with package resolution

Android 11 introduced restrictions on resolving external packages / activities, and we need to include an appropriate queries tag in our AndroidManifest.xml or this will always fail now

Good discussion here with link to source docs plus the following couple answers likely cover most of our use case for this:

https://stackoverflow.com/a/62856745/9910298

All callers of canOpenIntent / tryOpenIntent need to be examined inside AnkiDroid to see what kind of thing they are trying to do, then an appropriate queries element for this app needs to be constructed and added to our `AndroidManifest.xml`

_Originally posted by @mikehardy in https://github.com/ankidroid/Anki-Android/pull/9816#r744681963_

**Comment by avikkundu** [comment]
want to work on it.

**Comment by david-allison-1** [comment]
Sounds good to me!

**Comment by mikehardy** [comment]
wait - I was in this area recently and I think it was already done - check our androidmanifest, via git blame and see:

https://github.com/ankidroid/Anki-Android/blame/master/AnkiDroid/src/main/AndroidManifest.xml#L57-L62

https://github.com/ankidroid/Anki-Android/commit/0bc0563e55be418b7e639425a88284c9dcb823f1

https://github.com/ankidroid/Anki-Android/pull/9660

**Comment by mikehardy** [comment]
Ah well it is done at least for the TTS interaction, but a quick grep -r for the strings I mention above anOpenIntent / tryOpenIntent  to see if we need to specify other things is probably still useful.

One possible result of this scan is "no action needed" - I would actually gamble and say that is the likely outcome, but the only way to know is searching / inspecting

Thanks!

**Comment by mikehardy** [comment]
@avikkundu that works for me - thanks for looking! I typically post notices to follow our opencollective process only on merged PRs, but this knowledge - even in absence of needing a PR - is obviously valuable - so for January if you have spent time on this please consult https://github.com/ankidroid/Anki-Android/wiki/OpenCollective-Payment-Process - cheers!
