### ISSUE TITLE
`fa`: export_email_text_new appears to be invalid and not caught by lint

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9847]
Should have two format strings

https://github.com/ankidroid/Anki-Android/blob/9d80f5baa6b5c356756677bd22ec0c0f8d0311b9/AnkiDroid/src/main/res/values-fa/02-strings.xml#L191-L195

**Comment by david-allison-1** [comment]
The issue would be to investigate why Android Studio shows an error, but calling `gradlew lintAmazonRelease` passes

**Comment by gautom5987** [comment]
Hi @david-allison-1, I would like to work on this issue :)

**Comment by david-allison-1** [comment]
Sounds good to me!

**Comment by AayushSolanki** [comment]
Hi @david-allison-1 is @gautom5987 still working on the issue if not could you please assign it to me?

**Comment by david-allison-1** [comment]
Sounds reasonable to me, it's been a month. Thanks!

**Comment by AayushSolanki** [comment]
@david-allison-1 should these anchor tag open some links? ``<string name="export_email_text_new"><![CDATA[        سلام! 
         <br/><br/> 
         این یک دسته از فلش کارت های ankidroid هست که توسط **<a href="">**ankidroid برای شما ارسال شده است</a>. 
         برای استفاده از آن یکی از نسخه‌های در دسترس **<a href="">**anki را امتحان کنید</a> و از یادگیری کارآمد و آسان لذت ببرید. 
         ]]></string> ``****

**Comment by david-allison-1** [comment]
The issue relates to why Android Studio shows an error, but our `lint` CI build passes. (https://github.com/ankidroid/Anki-Android/issues/9847#issuecomment-964237362)

We ideally want this CI change to ensure that a string change like this would never go into a build again. This may flag other invalid strings, so we could fix all of these at once.

**Comment by AayushSolanki** [comment]
@david-allison-1 

> The issue relates to why Android Studio shows an error, but our `lint` CI build passes. ([#9847 (comment)](https://github.com/ankidroid/Anki-Android/issues/9847#issuecomment-964237362))
> 
> We ideally want this CI change to ensure that a string like this would fail the build. This may flag other invalid strings, so we could fix all of these at once.

@david-allison-1 could you please tell me how could i know about the errors lint is warning about

**Comment by david-allison-1** [comment]
> @david-allison-1
> 
> > The issue relates to why Android Studio shows an error, but our `lint` CI build passes. ([#9847 (comment)](https://github.com/ankidroid/Anki-Android/issues/9847#issuecomment-964237362))
> > We ideally want this CI change to ensure that a string like this would fail the build. This may flag other invalid strings, so we could fix all of these at once.
> 
> @david-allison-1 could you please tell me how could i know about the errors lint is warning about

You should be able to see the lint warnings/errors when the string is used in Android Studio

**Comment by pree-T** [comment]
May I work on this? Can someone help me to fix this issue as I am relatively new to open source contribution? @mikehardy @david-allison-1

**Comment by Arthur-Milchior** [comment]
@pree-T do you still want to work on it?

**Comment by pree-T** [comment]
> @pree-T do you still want to work on it?
Yes certainly if someone can help me to resolve it.

**Comment by s-deepak-kumar** [comment]
Can You Please Assign It To Me?

**Comment by david-allison** [comment]
> Yes certainly if someone can help me to resolve it.

What do you need help with? You need to actively ask if you're stuck with something.

**Comment by SanjaySargam** [comment]
If no one working on this issue then I'd love to work on this issue?

**Comment by dae** [comment]
If you're still interested, that would be appreciated.

**Comment by david-allison** [comment]
No longer reproducible. Applying the string from above, then running `gradle lintPlayRelease` fails

```
  /Users/davidallison/StudioProjects/Anki-Android/AnkiDroid/src/main/java/com/ichi2/anki/export/ActivityExportingDelegate.kt:170: Error: Format string 'export_email_text' is not a valid format string so it should not be passed to String.format [StringFormatInvalid]
                  activity.getString(
                  ^
      /Users/davidallison/StudioProjects/Anki-Android/AnkiDroid/src/main/res/values-am/02-strings.xml:190: This definition does not require arguments
  
  The full lint text report is located at:
    /Users/davidallison/StudioProjects/Anki-Android/AnkiDroid/build/intermediates/lint_intermediate_text_report/playRelease/lint-results-playRelease.txt
```
