### ISSUE TITLE
[Bug] Answer buttons not at bottom of screen

### ISSUE THREAD

**Issue by david-allison** [ankidroid/Anki-Android#9853]
###### Reproduction Steps

1. Settings - Reviewer - Fullscreen

###### Expected Result

Answer buttons at bottom of screen

###### Actual Result

![image](https://user-images.githubusercontent.com/62114487/141004809-94087947-9ad6-4e36-8a23-f63d9d082f88.png)

###### Debug info
2.15.6 and current dev build

###### Research
- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Screen is curved, and it's likely fallout from that, doubt it's MIUI specific

**Comment by mikehardy** [comment]
I have the same problem on one of my apps that doesn't get the "safe area insets" correct. Perhaps #9406  would help?

**Comment by david-allison-1** [comment]
Fixed up 9406 and it didn't resolve the issue, likely needs a lot of reading

**Comment by mikehardy** [comment]
That's great about 9406 refresh / rescue though, you should push to that branch so the results are available for review (maybe merge). Bummer it didn't fix it. This is an area of *quite* a bit of work in react-native at least, there is a module for it with all sorts of abstraction piercing if needed, starting from "try to just handle it" (fully abstract) to "okay, here's all the info we have as constants, we won't apply anything but you can slice them in anywhere you want for absolute padding values, have fun..."

https://github.com/th3rdwave/react-native-safe-area-context

It's kind of a mess. I was not aware of MIUI specific issues though and a search is an antegooglewhackblatt https://github.com/th3rdwave/react-native-safe-area-context/issues?q=MIUI

**Comment by david-allison-1** [comment]
Also reproducible on 2.15.6 on my Pixel

**Comment by s-deepak-kumar** [comment]
Can I Work On It?

**Comment by david-allison** [comment]
> Can I Work On It?

Definitely!

**Comment by mikehardy** [comment]
I think this is still a problem

**Comment by JalinWang** [comment]
I didn't reproduce this issue on my MIUI.

2.16alpha86
MIUI 12.5

Navigation Bar Mode:
![image](https://user-images.githubusercontent.com/20621784/197329593-9d8ab2c9-5948-4116-8a32-5aa8aca01623.png)

Fullscreen Guesture Mode:
![Screenshot_2022-10-22-16-29-08-788_com ichi2 anki](https://user-images.githubusercontent.com/20621784/197329600-8e9c56c5-4ffa-4648-a410-26b31b27303f.jpg)

**Comment by david-allison** [comment]
You're not in full screen mode
