### ISSUE TITLE
[Bug] Switching apps causes Ankidroid to restart

### ISSUE THREAD

**Issue by Anthropos888** [ankidroid/Anki-Android#9855]
1) Review a card
2) press your phone's home button or switch between recent apps using the toggle button
3) toggle back to Ankidroid app

Expected result:
The same card as before is shown in the reviever

Actual Result:
Ankidroid shows the app start logo and returns to the deck view OR loads a new card to the reviewer.

The behavior is quite new, maybe a few months. But I can't tell exactly when it started.

Maybe it has something to do with Chrome Canary 98 being my webview but I can't use normal Chrome as Webview because the problem with Chrome and large fonts isn't solved yet.

AnkiDroid Version = 2.16alpha29

Android Version = 9

Manufacturer = HMD Global

Model = TA-1021

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; TA-1021 Build/PKQ1.181105.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/98.0.4695.2 Mobile Safari/537.36

ACRA UUID = 751875a7-f00b-41fe-90b1-2bcc6af0617f

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by mikehardy** [comment]
Very strange - I see that you have crash reports on, and your ACRA UUID is in there but when I search for that UUID in our crash database, I don't get any hits. Zero crash reports. But this *sounds* like a crash :thinking: 

Not sure what actions I can take to move this forward. Would be interesting if you could temporarily set Firefox or something up as your WebView (is that possible even? Not sure) but I give that low chance of effect.

Would be interesting if you examined power settings on your device to see if AnkiDroid was in the "kill this app quickly in background to save power" bucket vs being given some priority, for example https://dontkillmyapp.com/

Would be interesting to know if you have enabled developer mode on your device and turned on "don't keep activities"

**Comment by david-allison-1** [comment]
Alternately, this could be a crash in native code that ACRA can't handle. If you have access to logcat, it may produce a crash trace

**Comment by Anthropos888** [comment]
I tested with Android System Webview 96 and the result is the same.

But actually it makes a difference if I press the home button or the toggle button:

Pressing home button during reviews and then opening Ankidroid from home screen will restart Ankidroid, show the app logo and then the deck view.

Switching to another app via toggle button during reviews and then coming back to Ankidroid will show the reviewer, but with a different card. Before that it seems like the webview crashed (white screen with grey top bar, see screenshot)

There is no crash message at all
![Screenshot_20211110-193559](https://user-images.githubusercontent.com/45192213/141173145-49a339cf-198f-4faf-bf7e-d173bf9468da.png)
.

**Comment by Anthropos888** [comment]
BTW, energy optimimizations and "Don't keep activities" are turned off.

**Comment by mikehardy** [comment]
I really appreciate the reports but all of the data makes me sad ;-). No hits there, no ideas at the moment, sorry. I can imagine that's frustrating, either you waste time getting back to where you were or you have a weird / disconcerting "card switch" issue at minimum

**Comment by david-allison-1** [comment]
No leads here. Sorry.

Could you try a parallel build of 2.15.6 and see if that passes? If so, then we've introduced a regression and have a chance to track it down.

**Comment by Anthropos888** [comment]
@david-allison-1 
The 2.15.6 parallel build solves one issue: pressing home button during reviews and then return to the app via app icon on home screen doesn't restart the app anymore. It returns to the reviewer and shows the same card as before. So your intention was right.

But the issue woth toggling through recent apps and then return to Ankidroid remains. The webview reloads amd shows a different card.

**Comment by s-deepak-kumar** [comment]
Anyone Work On It Or Not?

**Comment by dae** [comment]
Assuming this is fixed in latest release; please comment if not.
