### ISSUE TITLE
Anki is not displayed correctly on Samsung Galaxy Tab S7+ in horizontal view [Bug]

### ISSUE THREAD

**Issue by serjace** [ankidroid/Anki-Android#9878]
###### Reproduction Steps

1. Open or emulate AnkiDroid on [Samsung Galaxy Tab S7+](https://www.gsmarena.com/samsung_galaxy_tab_s7+-10336.php) (12.4" screen size, 1752x2800 pixels resolution, 16:10 aspect ratio (~266 ppi density)
2. Enable horizontal view.
3. You will see that those bars are not aligned - https://ibb.co/rpnMPV2.
![with gestures enabled](https://user-images.githubusercontent.com/83470612/141345851-2f822b1b-f3fd-42f3-9237-ff481a4b633d.jpg)
4. The same issues persists in vertical view as well - https://ibb.co/NT7v544, yet for the most part the tablet is used in horizontal mode (due to the screen size) so it would be amazing if horizontal view is fixed at least.
![vertical view with gestures enabled](https://user-images.githubusercontent.com/83470612/141345844-e534982c-8c7f-4dde-99bd-c237719a6216.jpg)

###### Expected Result
Both sides should be aligned, which happens when I use AnkiDroid in split screen mode - https://ibb.co/9g4YKzL or as a resized floating window.
![when in split screen mode](https://user-images.githubusercontent.com/83470612/141345848-f5f4d20a-4c83-4873-ae81-e6a7faea8542.jpg)

###### Actual Result
AnkiDroid in horizontal view with gestures enabled - https://ibb.co/rpnMPV2
![with gestures enabled](https://user-images.githubusercontent.com/83470612/141345851-2f822b1b-f3fd-42f3-9237-ff481a4b633d.jpg)
AnkiDroid in horizontal view with navigation bar enabled- https://ibb.co/c8Xg9VN
![with navigation bar enabled](https://user-images.githubusercontent.com/83470612/141345854-be75891d-2120-43b3-ac41-54cdbc88c7aa.jpg)
AnkiDroid in vertical view with gestures enabled - https://ibb.co/NT7v544
![vertical view with gestures enabled](https://user-images.githubusercontent.com/83470612/141345844-e534982c-8c7f-4dde-99bd-c237719a6216.jpg)

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! Yes, this is a known item that we've fixed but not released yet, release is going to take a while it is blocked on a very very important change to the way we handle the database in #9123 

The issue you are seeing is #9279 and was fixed in #9285 

You can get the fix now if you want, via alpha testing https://docs.ankidroid.org/manual.html#betaTesting or directly installing https://github.com/ankidroid/Anki-Android/releases

Hope this helps!
