### ISSUE TITLE
Difficulty Displaying Cloze and Type Fields

### ISSUE THREAD

**Issue by ctonnesen** [ankidroid/Anki-Android#9886]
I used Anki back in 2.0 and am recently returning to it for some brutal classes. I had it set up then where I could have multiple Cloze Deletions on the front and then type in the answers. However, upon loading up 2.1, all of my add-ons were invalid, so I began the process of trying to recreate the experience. I stumbled upon this [add-on](https://ankiweb.net/shared/info/1933645497), however it caused issues on AnkiDroid where it would just show the cloze deletion dots [...] for the front of the card. I then tried to combine the
`{{cloze:Text}} <br> <br> {{type:cloze:Text}}` on the front of the card as seen below and it worked for the computer:

![Front](https://user-images.githubusercontent.com/82608454/141520038-05399359-9351-41dc-b61e-799ec0f08bbc.png)
![Back](https://user-images.githubusercontent.com/82608454/141520066-b2b1755c-d237-4060-bec5-bc04e37199d8.png)

but not Anki Droid. All I got was the following, even with the advanced settings for the type-in turned on:

![Front](https://user-images.githubusercontent.com/82608454/141521129-8a16d2df-fd8e-4194-af60-9ba5a3d71c75.jpg)
![Back](https://user-images.githubusercontent.com/82608454/141521151-dd30a33d-c3b8-4291-a3c5-afc559048d23.jpg)

Support for either the add-on or typing in Cloze deletions would be fantastic. Here's the debug info

```
AnkiDroid Version = 2.15.6

Android Version = 12

Manufacturer = Google

Model = Pixel 4 XL

Hardware = coral

Webview User Agent = Mozilla/5.0 (Linux; Android 12; Pixel 4 XL Build/SP1A.211105.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/95.0.4638.74 Mobile Safari/537.36

ACRA UUID = 28509e27-80b1-4cc5-8111-f444007a0f1d

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

Current Add-Ons are:
![image](https://user-images.githubusercontent.com/82608454/141521537-d9fe86f2-ba04-4035-8e27-5b3fece4b094.png)

**Comment by david-allison-1** [comment]
Hi, this is fixed in #9743; it may take a while to release this feature (we've got a big change for 2.16, and this will likely land in our "Rust Backend" change for 2.17).
