### ISSUE TITLE
How to assign undo gesture to s pen

### ISSUE THREAD

**Issue by SurajJhaIn** [ankidroid/Anki-Android#9902]
I tried to assign undo to s pen button, but it doesn't seem to work. Can we make it happen please.

**Comment by david-allison-1** [comment]
Hi,

Can you try installing an alpha build and finding out if you can map an S-Pen button in `Settings - Controls`: https://github.com/ankidroid/Anki-Android/releases/download/v2.16alpha32/AnkiDroid-2.16alpha32.parallel.B.apk

Best wishes,

David

**Comment by SurajJhaIn** [comment]
I tried it many times, but s pen button doesn't work. It works fine with other apps like Infinite painter, Samsung notes. Please make it possible.

**Comment by david-allison-1** [comment]
It'll likely be a fair bit of work (and I don't have a device with an S-Pen). The fastest way for this to be implemented is if you have a chat about implementation and code it yourself. Would you have the time to do this?

Ref: https://github.com/ankidroid/Anki-Android/issues/9670#issuecomment-946706801

**Comment by SurajJhaIn** [comment]
I would love to, but unfortunately I don't that coding expertise.
