### ISSUE TITLE
[Help or Feature request] Possibility to save permanent custom settings

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#9905]
On my note template, I have several checkboxes that determine if some specific events will be fired or not.

I am looking for a way to save the last state of each checkboxes so that when a new card is loaded, they are each set in the same state as on the previous card. So basically, each time the state of a checkbox is changed, its current state should be saved somewhere. Then when a new card is loaded, the checkboxes are set according to the value saved. 

A great solution would be to be able to save custom settings in the db and then save/read/modify then via AnkiDroidJS api. 

I didn't find how to do that so I tried another less convenient solution: save/read/modify a file. But I wasn't able to that either (cf the code below). There was no error message in the developer console but I guess it's because of some security restrictions. 

I found a cumbersome workaround: setting several variables at the top of my front template which I manually set to true or false, according to my current needs. But it isn't convenient. 

It would be nice to have a way to save custom permanent settings. 

---
For example, I tried this to save the file

```
let a = document.createElement('a');
a.href = "data:application/octet-stream,"+encodeURIComponent("My DATA");
a.download = 'abc.txt';
a.click();
``` 

I also tried other scripts proposed [here](https://stackoverflow.com/questions/21012580/is-it-possible-to-write-data-to-file-using-only-javascript)

**Comment by mikehardy** [comment]
I believe you want to use the web storage API, kind of like this project does ? https://github.com/pigoz/anki-canvas/blob/master/src/storage.ts

**Comment by MagTun** [comment]
Sorry for the delay and thanks a lot for your quick reply. 

I spent some times trying to understand how this app works but I am still very confused by it.

At least, thanks to this script, I figured out that I can use `window.sessionStorage` to hold a value across a single session which is better than the current work around that I have set up. 

But it would be even better if I could hold the  values across multiples sessions (like when I finish a review and start reviewing another deck). But apparently  `window.localStorage` is not supported as when I try to save a new item, it returns this error: `Uncaught TypeError: Cannot read properties of null (reading 'setItem') at <anonymous>:1:14`.

I couldn't figure out the part about `(window as any).db`. Would this be able hold values across sessions? I have never coded in typescript before and I am willing to learn if this is the only way but I would prefer a js based solution (even with ankidroidjs api).

**Comment by mikehardy** [comment]
I see what you mean. Here's a logical progression:
- IF we hope for there to be a cross-platform javascript API used by 3rd party extensions...
- THEN we should recognize those extensions may have configuration (or state) of their own
- THEREFORE we should offer a place for javascript API to store state and config that syncs

I believe the only place to do this is in a data element in the collection config?

@dae we are still slow-walking forward on the idea of a good JS API, what do you think of the silly BE IT RESOLVED ;-) text above ? Do you have any thoughts on where best to allow a javascript API to put a "bag" of state?

**Comment by david-allison-1** [comment]
Just to note: we can enable LocalStorage, this is discussed: https://github.com/ankidroid/Anki-Android/issues/6971

**Comment by mikehardy** [comment]
in my opinion, if it is not possible to sync it across devices it is seriously diminished as a feature.

**Comment by MagTun** [comment]
@david-allison-1, thanks for letting me know!

I understand that I should add `webview.getSettings().setDomStorageEnabled(true);`  somewhere among [here](https://github.com/ankidroid/Anki-Android/blob/ab5472d710bf106aa70301b1cad9194d599ebe72/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L1560) but I have no idea how I can edit this file. I searched in Android/data/com.ichi2.anki/Ankidroid but it's not there. 

Could you please explain where I can find/edit it? Thanks a lot!

**Comment by david-allison-1** [comment]
You'll need to pull AnkiDroid from source (either via downloading a zip, or `git clone`), and edit it via Android Studio.

These steps should be useful: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#source-code

**Comment by MagTun** [comment]
I was hoping not to go this way ;-). Also it's not a long term solution as I would have to package Ankidroid each time there is a new update.

Is there a reason why `webview.getSettings().setDomStorageEnabled(true);` is not part of the core Ankidroid source code? If there are drawbacks to using it, maybe adding an advanced feature to be able to activate it, just for the users who want to still use it, could be a good compromise?

 Or is it because the way to go would be the one suggested by @mikehardy (a good JS API)?

**Comment by dae** [comment]
@mikehardy sorry, I missed your comment. The collection config is the best place to store small config data that needs to be synced, and AD could expose some JS API for it if it wished. Anki stores its own information there as well though, so to minimize possible breakages, I'd recommend you add some custom prefix like `_droid_js_` to all keys that are exposed/written, so that the JS can't accidentally/maliciously alter important variables like schedVer

**Comment by mikehardy** [comment]
Thanks @dae!
Then for key scoping seems like:
1- AnkiDroid in general should provide an API for JS add-on config storage, and AnkiDroid should handle prefixing to avoid any malicious scenarios from untrusted add-ons
2- JS Add-ons will need some sort of namespace restrictions where names are enforced as globally unique on at least the plane of "clean add on name", where "clean" means when the name is transformed to conform to whatever names are technically permitted for deck config storage, that technically permitted add-on name is still unique amongst all add-ons
3- AnkiDroid should then handle the JS add-on config element store/fetch with a prefix all storage with `_droid_js_` + `$clean_add_on_name`

Note that item 2 above is actually a somewhat difficult requirement - in an open ecosystem we will not be able to control add-on naming at the source. So it may be best to simply manage conflict by exposing the problem to the user on JS add-on install. Stated differently, item 2 may be satisfied by checking for a collision in technically-permitted add-on names between those existing in an installation and any potential new add-on. If this check fails during add-on install, expose that to the user with an error message and fail the install

**Comment by ChuckieChen945** [comment]
Hello everyone, I would like to know if this issue is still ongoing, or if this issue was just accidentally closed?

**Comment by david-allison** [comment]
`localStorage` has been enabled. 

This doesn't persist between review sessions/app restarts, but should be sufficient for this

**Comment by ChuckieChen945** [comment]
Thank you for your response! I’ve spent a few more days trying to figure out how to store permanent custom settings in AnkiDroid via JavaScript to maintain card state consistency across review sessions/app restarts, but unfortunately, I couldn’t find any other methods. This issue seems to be the only possibility.

I want to express my deep gratitude to the AnkiDroid team for your dedication and hard work. Your software has been an invaluable tool in my learning journey. The effort and expertise you put into this project do not go unnoticed and are greatly appreciated.

I’ll keep subscribing to this issue, holding onto the hope that a turning point may come in the future. Thank you once again for all that you do!
