### ISSUE TITLE
Invert colour for images on cards when Anki is in dark mode

### ISSUE THREAD

**Issue by SpacexerDragon5** [ankidroid/Anki-Android#9908]
it would be nice if there where an option when i create cars, which allows me to invert the colours of an image when dark mode is enabled or not. This becomes useful for screenshots which contain allot of text. eg:
![Screenshot_20211117-220606](https://user-images.githubusercontent.com/68651941/142284058-c6397eb6-3844-42d2-8c93-7bd530b0de04.png)
vs
![image](https://user-images.githubusercontent.com/68651941/142284062-e134902c-19f9-4b1f-a2a9-7aba0df59513.jpg)
it makes card in dark environments more readable an don't hurry my eye...

**Comment by SpacexerDragon5** [comment]
It's less important but i think it's worth mentioning it here

**Comment by david-allison-1** [comment]
You should be able to do this with the card template, and the `.night_mode` CSS selector

**Comment by mikehardy** [comment]
Indeed! It's documented: https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#invert-color-of-images-in-night-mode

**Comment by SpacexerDragon5** [comment]
great! Thank you, I didn´t saw any buttons or so to enable this...

**Comment by mikehardy** [comment]
Yep - it's not exposed in the UI. There are quite a few "dark corners" of the Anki system where basically anything is allowed, and it's the escape hatch for low-frequency user requests - this is one of them. That isn't to say these requests aren't important, just that developer time is scarce. So for a lot of things it boils down to: "well, it's actually a web page, and you can edit it with web tools like this..." to do exactly what you want :-). Good luck!
