### ISSUE TITLE
Night mode and table color.

### ISSUE THREAD

**Issue by Cho-jin** [ankidroid/Anki-Android#9916]
Black table border is not displayed in night mode.

Black character is transfered to white character.

But Black table border is not.

**Comment by david-allison-1** [comment]
Thanks for the report! What does Anki Desktop do here?

If we don't match, then we'll fix it.

If we do, we need to fix this in Anki Desktop first.

In the meantime, to fix your problem, you may need to update the card template:

https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#customize-night-mode-color

See also: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

**Comment by Cho-jin** [comment]
> Thanks for the report! What does Anki Desktop do here?
> 
> If we don't match, then we'll fix it.
> 
> If we do, we need to fix this in Anki Desktop first.
> 
> In the meantime, to fix your problem, you may need to update the card template:
> 
> https://github.com/ankidroid/Anki-Android/wiki/Advanced-formatting#customize-night-mode-colors
> 
> See also: https://github.com/ankidroid/Anki-Android/wiki/Development-Guide#html-javascript-inspection

Thanks, I solved the problem. 

.night_mode   {
 filter: invert(1); -webkit-filter:invert(1);
}
