### ISSUE TITLE
[Bug]sound  is not work

### ISSUE THREAD

**Issue by davidberg-python** [ankidroid/Anki-Android#9933]
###### Reproduction Steps

1. i click on button

###### Expected Result
hear the sound

###### Actual Result
I do not hear

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there - with apologies, you have not provided any of the information requested, so we do not have any ability to help.
I can personally attest that sound works fine for my cards in my app, so sound in general is working.
I assume either the sound is missing https://github.com/ankidroid/Anki-Android/wiki/FAQ#why-doesnt-my-sound-or-image-work-on-ankidroid
Or you have done something to your card templates that makes it not work
Or your phone has some general sound issue?

But, if you skip all the information we ask for in the template we can't help, sorry

**Comment by davidberg-python** [comment]
on my computer the sound works but on my cell phone it doesn't

**Comment by davidberg-python** [comment]
Settings - AnkiDroid - Fetch media on sync was not selected
