### ISSUE TITLE
cards disappear when reviewing

### ISSUE THREAD

**Issue by bahamut8591** [ankidroid/Anki-Android#9936]
Having an issue when i am reviewing my deck and it will say 75 card to review, and at a random point, a decent amount of them disappear.

Been doing this a few times, today i caught it when i had 31 card to review, and then it went to 1 card

**Comment by absoluteinc** [comment]
One explanation that it could be is Anki is burying related cards. Under the deck options, see if the setting for burying related cards is checked or not.
