### ISSUE TITLE
[Bug] Card browser displayes the card back as answer, for "Basic (type in)" cards

### ISSUE THREAD

**Issue by 64kramsystem** [ankidroid/Anki-Android#9943]
###### Reproduction Steps

1. Create a "Basic (type in)" card, with "front" as front text, and "back" as back text
2. Open the Card browser

###### Expected Result

The card should show "front" as Question, and "back" as Answer

###### Actual Result

The card shows "front" both as Question and Answer

###### Debug info

I've edited away some fields for privacy.

```
AnkiDroid Version = 2.15.6

Android Version = XXX

Manufacturer = Google

Model = XXX

Hardware = XXX

Webview User Agent = XXX

ACRA UUID = eaf677f9-6503-4369-a60e-35e01e33895c

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Thanks! 

What does Anki Desktop do here?

**Comment by david-allison-1** [comment]
To work around the issue:

* Deck Picker - Manage Note Types - Basic (type in answer) - Long press - Cards - Menu - Browser Override and enter `{{Back}}` in the back template.

Here's a quick video demo: https://www.youtube.com/watch?v=JbxNP4pSIBA

**Comment by 64kramsystem** [comment]
> To work around the issue:
>     * Deck Picker - Manage Note Types - Basic (type in answer) - Long press - Cards - Menu - Browser Override and enter `{{Back}}` in the back template.

Thanks for the reply!

The Desktop version is also affected. I've tried the Windows version (the Linux version doesn't work :grimacing:), and in the browser, if I add the `Answer` column (it's not present by default), it shows the front.

**Comment by david-allison-1** [comment]
Could you please report this on the [Anki Desktop forums](https://forums.ankiweb.net/), once they get the fix, we'll implement it.

I'm going to close this under the assumption:

* My previous comment with the YouTube video resolved your issue
* This is an issue which should be fixed upstream, and there's nothing for us to do until this case.

If I'm wrong, or when Anki Desktop has fixed this, please add a comment and we'll reopen it and get it fixed.

Thanks so much for submitting the issue, we really appreciate feedback 👍 

![](https://media.giphy.com/media/3o6Zt6KHxJTbXCnSvu/giphy.gif)

**Comment by 64kramsystem** [comment]
> Could you please report this on the [Anki Desktop forums](https://forums.ankiweb.net/), once they implement the fix, we'll implement it.
> 
> I'm going to close this under the assumption:
> 
>     * My previous comment with the YouTube video resolved your issue
> 
>     * This is an issue which should be fixed upstream, and there's nothing for us to do, as we're compatible with Anki Desktop here
> 
> 
> If I'm wrong, or when Anki Desktop has fixed this, please add a comment and we'll reopen it and get it fixed.
> 
> Thanks so much for submitting the issue, we really appreciate feedback +1
> 
> ![](https://camo.githubusercontent.com/73c77ac44b6924414745e183d70fc8e3fe32ddd892f1397d0f0b90bb5571eb65/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f336f365a74364b48784a546258436e5376752f67697068792e676966)

Excellent. Thank you for the prompt help :smile: And for your product! :heart_eyes:
