### ISSUE TITLE
[Bug] Order cards in custom study review by date/time created (added) doesn’t work 

### ISSUE THREAD

**Issue by camerooncameroon** [ankidroid/Anki-Android#9945]
###### Reproduction Steps

From: https://www.reddit.com/r/Anki/comments/g50jln/how_to_review_due_anki_cards_in_the_order_added

1) Go to the deck that you'd like to review old cards in order added.

2) Click "custom study"

3) Click "study by card state or tag"

4) Input the # of cards you'd like to review, and click "due cards only", then click "choose tags"

5) If you want to review all cards in this deck, just click ok. (you can review cards with selected tags, if you desire)

6) Now that you're back at the main screen for the deck, click "options"

7) Replace "order due" with "order added"

8) Ensure that you select the box that says "reschedule cards based on my answers in this deck"

9) Click rebuild.

###### Expected Result

now you'll be presented with these cards in the order they were added. When you complete the cards, they will be marked as complete in the original deck, and they will reappear in the original deck based on how you graded them while answering

###### Actual Result

it doesn't work on AnkiDroid (as well as on Anki Desktop) - the cards are shown in a random order (or sorted maybe by some other algorithm) but NOT in the order they were added (in spite of the settings)! If I reset the progress (i.e. make the cards new ones) - then the order they are shown obeys the settings (show in the order added)

###### Debug info
    
    Anki 2.1.49 (dc80804a) Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
    Platform: Windows 10
    Flags: frz=True ao=True sv=3
    Add-ons, last update check: 2021-11-25 00:59:32
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Hyperlink ['318752047', 2021-11-21T21:04, 'None', '']
    Advanced Browser ['874215009', 2021-07-23T02:14, 'None', '']
    Advanced Card Styles ['1625103157', 2021-09-23T16:51, 'None', '']
    Advanced Copy Fields ['1898445115', 2019-05-03T23:46, 'None', '']
    AnkiConnect ['2055492159', 2021-07-14T05:59, 'None', '']
    Asset Manager ['656021484', 2021-08-30T02:07, 'None', '']
    AwesomeTTS - Add speech to your flashcards ['1436550454', 2021-11-19T12:21, 'None', '']
    Batch Editing ['291119185', 2019-06-02T23:47, 'None', '']
    Batch Remove Formatting eg bold italics etc ['1734822644', 2018-09-24T20:34, 'None', '']
    BetterSearch ['1052724801', 2021-11-21T23:42, 'None', '']
    Browser TableEditor side-by-side horizontal split ['831846358', 2021-05-27T21:47, 'None', '']
    CC-CEDICT for Anki Chinese dictionary ['418828045', 2021-09-03T21:33, 'None', mod]
    CSS Injector - Change default editor styles ['181103283', 2021-10-05T03:29, 'None', '']
    Card Info During Review ['2179254157', 2021-02-05T15:22, 'None', '']
    Change Card Creation Times ['217650262', 2019-03-05T07:59, 'None', '']
    Change Order of Review Cards in Regular Decks ['3731265543', 2018-10-13T03:47, 'None', '']
    Chinese Companion - frequency sort HSK suspend heisig support and more ['2129668097', 2018-11-22T18:55, 'None', '']
    Chinese Pinyin Translator Zhuyin Bopomofo Gwoyeu Romatzyh ['1792056402', 2018-11-09T08:27, 'None', mod]
    Chinese Prestudy ['882364911', 2020-11-03T11:43, 'None', mod]
    Chinese Support Redux v0142 ['1128979221', 2021-03-29T07:19, 'None', mod]
    Chinese Vocabulary Generator ['1370756741', 2021-02-24T13:07, 'None', '']
    Chinese Words Finder ['2048169015', 2020-07-07T17:32, 'None', '']
    Clickable Tags v20 Anki 2120 support ['1739176371', 2021-10-17T04:27, 'None', '']
    Cloze Overlapper for Anki 21 ['109531687', 2021-01-12T08:12, 'None', '']
    Colorful Browser Sidebar ['929609616', 2021-09-09T23:03, 'None', mod]
    Countdown To Events and Exams ['1143540799', 2021-03-14T01:40, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2017-08-29T23:57, 'None', '']
    Custom Background Image and Gear Icon ['1210908941', 2021-08-20T06:20, 'None', mod]
    Customize Editor Stylesheet ['1215991469', 2018-09-04T20:03, 'None', '']
    Deck name in title 21 ['699175524', 2019-06-01T06:05, 'None', '']
    Duplicate and Reorder ['duplicate_and_reorder', 2020-10-16T21:56, 'None', '']
    Edit Field During Review Cloze ['385888438', 2021-07-31T10:57, '6.7', mod]
    Export in CSV format ['1478130872', 2019-01-21T23:21, 'None', '']
    Extended Card Stats During Review ['1008566916', 2017-08-29T23:59, 'None', '']
    Extended Tag AddEdit Dialog ['1135507717', 2021-05-19T05:29, 'None', '']
    Fast cards reposition ['544982740', 2021-09-19T18:51, 'None', '']
    Fastbar- with nightmode support ['46611790', 2021-08-23T01:33, 'None', '']
    Fill the blanks - Multiple typecloze support ['1933645497', 2021-08-06T00:38, 'None', '']
    Find and Replace in Card templatesNotetypesHTML ['992153575', 2021-09-17T11:34, 'None', '']
    Hierarchical Tags 2 ['594329229', 2021-03-07T07:25, 'None', '']
    Highlight Search Results in the Browser ['225180905', 2021-03-10T22:06, 'None', '']
    Image Editor ['307397307', 2021-09-10T15:41, 'None', '']
    Image Style Editor ['1593969147', 2021-10-17T07:32, 'None', mod]
    ImageResizer ['1214357311', 2021-04-10T21:15, 'None', '']
    Load Balanced Scheduler ['208879074', 2018-10-05T05:06, 'None', '']
    Maximum image height and width in card editor ['229181581', 2021-07-23T11:01, 'None', '']
    Mini Format Pack ['295889520', 2018-07-24T22:45, 'None', '']
    Minimize to tray ['85158043', 2020-02-15T20:28, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2021-01-27T14:09, 'None', '']
    More Overview Stats ['2116130837', 2021-05-29T16:24, 'None', '']
    Multiple Choice for Anki ['1566095810', 2021-03-18T22:50, 'None', '']
    Papercards - export  print flashcards to paper ['2042118948', 2021-05-14T06:58, 'None', mod]
    Quick Colour Changing ['2491935955', 2017-08-28T17:48, 'None', '']
    Rebuild All  Empty All for Anki 21 ['1810938259', 2018-07-20T09:40, 'None', '']
    Refocus Card when Reviewing 21 ['1642550423', 2018-09-19T19:14, 'None', '']
    Resize images in editor ['1103084694', 2021-07-19T11:35, 'None', mod]
    Review Heatmap ['review_heatmap', 2020-04-30T18:23, 'None', '']
    Scale Images ['1312865748', 2021-06-05T14:53, 'None', '']
    Sentence adder for any language with batch add option ['1682655437', 2021-03-24T19:52, 'None', '']
    Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-12T16:47, 'None', '']
    The KING of Button Add-ons ['374005964', 2020-04-18T03:33, 'None', '']
    Zoom 21 ['1846592880', 2020-01-12T22:26, 'None', '']
    maobi - Chinese Hanzi Writing Quizzes in Anki v0 5 2 ['931477147', 2021-02-21T22:14, 'None', mod]
    remove linebreaks  do word wrap ['2028179508', 2021-04-12T04:36, 'None', '']
    
    ===IDs of active AnkiWeb add-ons===
    1008566916 1052724801 109531687 1103084694 1128979221 1135507717 1143540799 1210908941 1214357311 1215991469 1312865748 1370756741 1436550454 1478130872 1556734708 1566095810 1593969147 1625103157 1642550423 1682655437 1734822644 1739176371 1792056402 1810938259 181103283 1846592880 1898445115 1933645497 2028179508 2042118948 2048169015 2055492159 208879074 2116130837 2129668097 217650262 2179254157 225180905 229181581 2491935955 291119185 295889520 307397307 318752047 3731265543 374005964 385888438 418828045 46611790 544982740 594329229 656021484 668156440 699175524 831846358 85158043 861263371 874215009 882364911 929609616 931477147 992153575
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    Add Cards - Web Browser ['1783260740', 2020-10-28T11:35, 'None', '']
    Advanced Review Bottom Bar ['1136455830', 2021-09-22T01:59, 'None', '']
    Anki Excel Sync ['1832015432', 2021-01-28T08:53, 'None', '']
    Bury Cousins related cards that arent siblings ['1072815885', 2021-07-20T06:23, 'None', '']
    Bury related notes ['413416269', 2020-04-03T12:55, 'None', '']
    Button Colours Good Again ['2494384865', 2021-04-06T19:57, 'None', '']
    Chinese Getter ['972150718', 2021-06-23T19:27, 'None', mod]
    Chinese-Text-Scanner ['2121493325', 2020-06-28T09:53, 'None', mod]
    Color Confirmation ['1084228676', 2020-03-14T17:13, 'None', '']
    Copy notes ['1566928056', 2021-09-18T19:00, 'None', '']
    Duplicate Selected Notes ['2126361512', 2017-08-29T23:57, 'None', '']
    Legacy Remove HTML ['1101026246', 2021-01-25T00:40, 'None', '']
    Let it Snow ['321075516', 2017-12-21T21:48, 'None', '']
    MorphMan for Anki 21 ['900801631', 2021-02-11T09:30, 'None', '']
    Multi-column note editor ['3491767031', 2021-11-02T20:18, 'None', '']
    Searching PDF Reading  Note-Taking in Add Dialog ['1781298089', 2021-09-17T15:24, 'None', mod]
    blank ['1690290745', 2021-05-04T16:04, 'None', '']

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Debug info is always applicable, we're very curious for the version you are using of desktop and ankidroid at minimum
When you say "it doesn't work on AnkiDroid (as well as on Anki Desktop)" - I can't parse that.

To be super clear:
- does this work on desktop?

**Comment by camerooncameroon** [comment]
Version info:
Version ⁨2.1.49 (dc80804a)⁩
Python 3.8.6 Qt 5.14.2 PyQt 5.14.2
AnkiDroid version 2.15.6

@mikehardy 
`does this work on desktop?`
No, it doesn't

**Comment by mikehardy** [comment]
Interesting - one thing we try to do is work exactly the same as desktop, to the point where our scheduler code is actually shared! That is, we're 100% bug-compatible as well ;-). Have you raised this on https://forums.ankiweb.net ? They might be interested there, and if the fix makes it into the scheduler there, we will pick it up here automatically...

**Comment by camerooncameroon** [comment]
Yes, I posted it on Ankiweb forums, too https://forums.ankiweb.net/t/order-cards-in-review-by-date-time-created-added-doesnt-work/15267

**Comment by camerooncameroon** [comment]
@mikehardy 
Hi, Damien said this will be implemented in the next beta of Anki Desktop: https://forums.ankiweb.net/t/order-cards-in-review-by-date-time-created-added-doesnt-work/15267/12?u=odeon

**Comment by mikehardy** [comment]
Ah cool! There really isn't further action to take here other than our standard "stay in sync with upstream rust library" tasks which are pretty involved but also will happen regardless of this issue or not. So I'm going to close this as it is not actionable really but it won't be actually fixed until we get whatever underlying code has that change. To set expectations it could be a while, we have a pretty big backlog right now of very important tasks (scoped storage migration for Android 11/12 compatibility, most importantly)
