### ISSUE TITLE
[Bug] Card Resizing not Possible on Android TV

### ISSUE THREAD

**Issue by CaerDallben** [ankidroid/Anki-Android#9947]
###### Reproduction Steps

1. Open AnkiDroid on Android TV (Sideloaded)
2. Go to menu to resize card.
3. Change value on card resizing scale.

###### Expected Result
Changed card resizing scale would save and resize cards.

###### Actual Result
It is impossible to save the card resizing value by pressing enter or any other key so it remains at 100. On a phone with a touchscreen, sliding the scale autosaves the value - this is not possible on a non-touch-screen device like a TV.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Not many people use the TV functionality. 

Should be possible with an additional key event (left/right arrow)

**Comment by CaerDallben** [comment]
Thanks for responding! Are you saying it should already be something that should be doable because I tried button-mashing every button on all my remotes to see if anything would save the new value but no such luck. 

Also, the TV functionality is GREAT. A lot better than I anticipated. The only problem was that I couldn't figure out how to move an image occluded card up or down when it was covered by the menu bar and the answer bar. I figured the logical solution would be to reduce the card size but was unable to get it to save. Even if the resize function was changed to an input instead of a scale that should fix it. Otherwise the app works perfectly for TV including remote control with gamepads.

**Comment by pree-T** [comment]
May I work on this?

**Comment by david-allison-1** [comment]
@pree-T You've asked for multiple issue. Can you select one that you'd like to work on, it doesn't seem fair to take on multiple 'good first issue's unless you're getting through them at a significant pace.

**Comment by fred042** [comment]
@david-allison-1 Can I try to fix this issue?

**Comment by david-allison-1** [comment]
@fred042 Sure!

**Comment by fred-sab** [comment]
Hi @david-allison-1 

A solution should be to save the preference on change instead of on touch stop (see PR #10039), wdyt?

PS: for an unknown reason my other new account got suspended (maybe because I already had this account). That's why I'm using this one instead 😅
