### ISSUE TITLE
I am getting error while syncing my account

### ISSUE THREAD

**Issue by SurajJhaIn** [ankidroid/Anki-Android#9950]
![Screenshot_20211127-131925_AnkiDroid](https://user-images.githubusercontent.com/45020824/143673159-6f8fb63e-b5f5-448a-83b3-cd5b686fcffd.jpg)

**Comment by david-allison-1** [comment]
Hi, please fill out the rest of the "bug" template. Hard to help with just a screenshot

**Comment by SurajJhaIn** [comment]
When I went to PC, it asked for ankiweb or anki. I chose Anki my problem got solved but my today's review got deleted.
