### ISSUE TITLE
Use catalogs for files?

### ISSUE THREAD

**Issue by exec228** [ankidroid/Anki-Android#9952]
Salut!

**Is your feature request related to a problem? Please describe.**

The problem is to back up and restore mobile phone data and configuration.

It's virtually impossible to do it easily, because sdcard/AnkiDroid/collection.media/ contains 15000 files.

I have 7 decks only.
Copying it forth and back takes a whole day or more, up to 30-50 hours.
Through LANDrive (fr.webrox.landrive, paid license, up to 50Mbit/s).
Because MTP just either crashes on this folder after copying a small grasp of files, or just ignores copying command.

**Describe the solution you'd like**

Is it possible to kind of **use** directory feature? It's invented to counter problems like I described above.

**Describe alternatives you've considered**

No alternatives. At least from End User point of view.

**Additional context**

If deck-authors cannot do it, is it possible that core programmers do it instead?
Like alphabetically sort files by means of force, to have, for example, 26+10 folders depending on the **last** char of the filename (first several letters are bad, because they are repeating several thousand times).

Thank you!

**Comment by mikehardy** [comment]
Have you tried something efficient, like rsync, for example Syncopoli? 
Also free / open source, not the best thing to configure but works great https://f-droid.org/en/packages/org.amoradi.syncopoli/

The media folder is flat and unorganized and will likely stay that way forever, I would look harder for efficient ways to handle that, in other words. Not exactly what you want to hear perhaps but sometimes hearing things that are nevertheless true can help focus attention on what's actually possible.

Failing that, any change like this would start upstream in Anki Desktop, and we'd adopt it here if your feature request succeeded there, as it would be ecosystem wide - https://forums.ankiweb.net

If something changes there we can reopen
