### ISSUE TITLE
[Bug] "Replace collection" dialog doesn't say which collection it is

### ISSUE THREAD

**Issue by Kelvets** [ankidroid/Anki-Android#9953]
###### Reproduction Steps

1. After having changes that should be synchronized, press the second of the three icons in the top bar (shaped like two rotating arrows with a red circle on the top-right)
2. You will be met with the two confirmation dialogs below

###### Expected Result

The dialogs should explicitly mention which collection/deck it is talking about, in case you did several decks that day.

###### Actual Result

![Capture+_2021-11-28-02-02-39](https://user-images.githubusercontent.com/3800465/143730546-028f8382-a8c6-4765-bb83-12803d2fe770.png)

![Capture+_2021-11-28-02-02-51](https://user-images.githubusercontent.com/3800465/143730550-077efa36-1b80-4a4e-8c00-448e2b319377.png)

As you can see it does not mention the deck's name at any point.

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [X] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
That's because it is not deck specific, it is specifically the entire collection that may not be merged.
This is not something we can solve really.
https://docs.ankiweb.net/syncing.html#merging-conflicts
