### ISSUE TITLE
Clarify the error message about missing spaces

### ISSUE THREAD

**Issue by Arthur-Milchior** [ankidroid/Anki-Android#9954]
![Screenshot_20211128-092615_AnkiDroid](https://user-images.githubusercontent.com/357361/143791168-dc77391f-ec92-49f3-9b49-33d7bd3ba73a.jpg)
> There is not enough space to unzip the package. Needed %1$d, available %2$d

This error message comes from String resource import_log_insufficient_space.
It seems clear to me that it has multiple issues, such as:
* It is too technical. There is no need to let the user know apkg files are zips that require unzipping. On the contrary, it may confuse someone trying to use it as a zip.
* It contains long numbers which are not reader friendly. Stating that we need 3.2GB and only have available 2.6 would be enough information.
* It does not state how to solve the issue. In this cases, the options could be: 
  - to free .6GB of space (and let the user know they can delete the .apkg after importing)
  - importing it on another device, e.g. a computer, and then syncing (that would work because what is costly here is unzipping. That leads to having the content in three copies. In the unziped folder, in the media folder/database, and in the zip file. If the files arrive thanks to synchronization, a single copy will be here)

I'd suggest to add a page to our documentation (if it does not already exists), explaining in more details what I just wrote above, and also adding a link to this page (but ideally, the error message should be self sufficient. Links are usually not translated, and not available without internet, so it's far from ideal).

I'm not a native English speaker, so I won't try to find the best formulation of the new sentence

**Comment by souravmunjal** [comment]
working on this issue

**Comment by souravmunjal** [comment]
![Group 1](https://user-images.githubusercontent.com/30770269/144140115-1a84c8a3-b044-4440-9b81-391a0ceb883b.png)
Hey aurthur here is a proposed design for the above let me know if it works so that i can start working on it

**Comment by mikehardy** [comment]
I question whether option 1 is actually an option? I do not think there is the ability to delete it while importing. So the text could be just

Having trouble? Sync uses less space than import. You may try to import the package on some other device (for example, using Anki Desktop) and then sync it to this device via AnkiWeb)

Otherwise, I think it looks excellent - the presentation of numbers is so much better

**Comment by souravmunjal** [comment]
yeah makes sense will remove the first point and then continue with this text either

**Comment by Arthur-Milchior** [comment]
I fear option 1 is not what I had in mind. One more proof  that my explanation needed improvement. In any case, we should not even mention "unzipping" it, because the user should not have to know that .apkg is implemented as a zip file. Worse, if they try to unzip it (which is natural for a zip file), it will create more issues.

The user should free some space. E.g. deleting music, downloaded file, app. Or sometime just using android tool to save space would be sufficient. We should just tell them to free some space, nothing more. If we try to explain how to free space, we can't do a proper job, it's totally outside of our scope to do so.

As a related suggestion, I believe once the import is entirely done, we should offer the user to delete the .apkg for them since it probably became useless.


It would be theoretically possible to loop over each file from the zip, extract it and delete it. This may potentially limit the memory used. But the cost would be to port unix zip library to Android, because Android library do not have an option to update a zip file. Even in the case where someone would want to do this complex work and come back (probably in a few months or a year) with a working library, I would not want to use it, because the risk of having it breaking and corrupting apkg file is far too high for the small benefits we would get from it

**Comment by Arthur-Milchior** [comment]
By the way, thanks for dealing with this issue.

**Comment by souravmunjal** [comment]
yeah actually it was just design not implemented yet if you have any changes in mind you can suggest before i start working

**Comment by mikehardy** [comment]
We have an issue logged and have investigated space-optimization here: https://github.com/ankidroid/Anki-Android/issues/6036 - I think ideally we would use the apkg file directly, right now we copy it, then we unpack it, then we import it. It's pretty wasteful. We already use a 3rd party zip dependency, as well, to handle >2GB files: https://github.com/ankidroid/Anki-Android/blob/83c12fbcf19b91350a70cf7b1601de0328d81565/AnkiDroid/build.gradle#L309

That's orthogonal to simply fixing the dialog to be a lot more useful though

**Comment by Arthur-Milchior** [comment]
Well, I already gave feedback.

Let me try a sentence then:

Your device to not have enough storage to import this deck. We need $1 and you only have $2 available. Here are two ways to solve it.
* Either free $1-$2 and try to import the deck again. 
* Or try to import the package on some other device (for example, using Anki Desktop with the same account) and then sync it to this device via AnkiWeb.

Let's ignore in this discussion the part about space optimization, I'm happy to know another issue already track it.

**Comment by souravmunjal** [comment]
aurthur can you share the deck with me?

**Comment by mikehardy** [comment]
That should not be necessary. You don't need anything more than the code to work on this one. Insert dummy return values during testing in order to test the dialogs.

**Comment by souravmunjal** [comment]
<img width="320" alt="image" src="https://user-images.githubusercontent.com/30770269/144504122-692c7fa6-b633-4931-889b-c5c0486ec803.png">
if this looks ok i can create a pr for this?

**Comment by souravmunjal** [comment]
i have generated a pr please check 
@Arthur-Milchior @mikehardy 
https://github.com/ankidroid/Anki-Android/pull/9965/commits
