### ISSUE TITLE
[Bug] Login does not have "try anyway" feature if user is detected as being offline

### ISSUE THREAD

**Issue by greengekota** [ankidroid/Anki-Android#9961]
###### Reproduction Steps

1. Block google from a firewall so that your android device will report that you are not connected to internet, while you still have access to the anki server.
2. Try to connect to anki.

###### Expected Result

Either attempt to connect before and then report that there is no connectivity on failure, or present the "Try anyway" button as it happens for syncronization.

###### Actual Result

AnkiDroid says "You are offline" and doesn't allow to connect to the server at all.

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there!

>  or present the "Try anyway" button as it happens for syncronization.

So it sounds like we override the check in some cases? What exactly is your set of reproduction steps? You didn't include that or the debug info...they would help

**Comment by mikehardy** [comment]
Great, so:

> So it sounds like we override the check in some cases? 

sync lets you override the check

> What exactly is your set of reproduction steps? You didn't include that or the debug info...they would help

Trying to log in on the account page does not allow an override.

happens with current stable

**Comment by SSTG** [comment]
Hey I am new to the community. Could you please give me an overview of how to go about this issue?

**Comment by SSTG** [comment]
I think I am understanding the issue now. I would like to work on it but you'll have to excuse me as I am a newbie in open source so I might ask some silly questions.

**Comment by greengekota** [comment]
There is a `isOnline()` function which asks to android if "there is 
network connection". If that function returns false then AnkiDroid will 
prevent you from attempting to connect the anki server. This was added 
more than a decade ago and as you can see it resulted in an accumulation 
of hacks. The last one

https://github.com/ankidroid/Anki-Android/commit/91d1580d70ae2b309cccb1ec87a39458ad0cc7fe

adds a button to the "Snackbar" to override the whole `isOnline` check, 
but there is another case where `showSimpleSnackbar` is being used 
instead of `showSyncLogMessage` from that commit.

What if android reports that is network connection, but the Anki server 
is down? The `isOnline` function will pass but you will get an error.
Which means you will always have to deal with the latter situation, 
making the current check not so useful.

What if android reports that there is no network connection, while you 
can actually contact the anki server? You won't be able to use 
AnkiDroid. A change in API from android side can result in pain:

https://github.com/ankidroid/Anki-Android/issues/7013
https://github.com/ankidroid/Anki-Android/pull/8331

Android being wrong about network connection is my problem.

If you remove the `inOnline` check and try to syncronize while you 
cannot reach the anki server you'll get a pop-up saying

 > Sync error
 > Connection timed out. Either your internet connection is experiencing
 > problems, or you have a very lare file in your media folder.
 > java.netUnknownHostException: unable to resolve host <host>.
 > No address associated with hostname

which is the "sync_connection_error" string. Is there any reason to 
leave the `isOnline` check?

**Comment by mikehardy** [comment]
Yes, that error message ("connection timed out..." etc) creates support load here from confused users. "I have a sync error, help...." when there is nothing we can do to help, so it is frustrating for everyone.

Simply having a "Try Anyway" similar to the login would be great

**Comment by SSTG** [comment]
Oh okay let me have a look at the function

**Comment by SSTG** [comment]
Okay so I have been looking at the code. I tried to run the app with no connection on my device but I didn't get any "try anyway" button in the snackbar though it is mentioned in the DeckPicker code, I am only getting "You are offline" . So I am thinking that the error is with the getAllowSyncOnNoConnection function.

**Comment by greengekota** [comment]
> Yes, that error message ("connection timed out..." etc) creates support load here from confused users. "I have a sync error, help...." when there is nothing we can do to help, so it is frustrating for everyone.

I'm sorry, searching for "connection timed out" in the issues doesn't yield many results, but the `isOnline` method was added more than 10 years ago so maybe I'm looking at the wrong place, or maybe users don't mention those exact words.

If the problem is that the "Connection timed out" message is too technical, then I think one solution would be to make that message more human friendly. Another solution - maybe a convoluted one - would be to keep a state of "android thinks there is not network", and when a connection attempt fails then present the message "You are offline" instead of the more verbose "Connection timed out. Either your internet connection is experiencing problems, or you have a very large file in your media folder".

The `isOnline` check requires me to keep pressing the "try anyway" button at every sync, which is not a great experience. I'll just keep a patch to remember how to remove it.

> Simply having a "Try Anyway" similar to the login would be great

It would help, thank you. And good luck with your work, SSTG.

**Comment by SSTG** [comment]
Thanks. I am working on it right now. Will let you know if I encounter any difficulty

**Comment by SSTG** [comment]
Sorry for being inactive for a while. I think I have implemented the second solution just as you said.

**Comment by pree-T** [comment]
Can I work on this?

**Comment by david-allison-1** [comment]
@pree-T There's an active PR in, doesn't feel worthwhile

**Comment by viciousAegis** [comment]
Does this issue need working on?

**Comment by david-allison** [comment]
The PR hasn't seen action for almost two months. I'd be happy if you worked on it.

**Comment by viciousAegis** [comment]
I went through the whole issue thread, and from my understanding, this is the solution to be implemented? https://github.com/ankidroid/Anki-Android/issues/9961#issuecomment-991893890

@greengekota, This was your suggestion, should I try implementing this?

**Comment by david-allison** [comment]
> I went through the whole issue thread, and from my understanding, this is the solution to be implemented? [#9961 (comment)](https://github.com/ankidroid/Anki-Android/issues/9961#issuecomment-991893890)
> 
> @greengekota, This was your suggestion, should I try implementing this?
> 
> > Simply having a "Try Anyway" similar to the login would be great
> 
> Basically should I add the `try anyway` button here as well, similar to the login popup?

Something similar to: 91d1580d70ae2b309cccb1ec87a39458ad0cc7fe.

I think the relevant code is: 

https://github.com/ankidroid/Anki-Android/blob/cfb2dd110271719e757a22a9997e11c51085cac7/AnkiDroid/src/main/java/com/ichi2/anki/MyAccount.java#L294-L304

`Connection.setAllowSyncOnNoConnection(true);` already works for logins, but the variable (`setAllowSyncOnNoConnection`) should be renamed

**Comment by viciousAegis** [comment]
Should I rename it to `setAllowLoginSyncOnNoConnection` ? That should cover everything. Other than that, I have added the `Try Anyway` button and it is working in the same way as https://github.com/ankidroid/Anki-Android/commit/91d1580d70ae2b309cccb1ec87a39458ad0cc7fe. WIll link a PR once the renaming is confirmed.

**Comment by david-allison** [comment]
Awesome! That sounds good.
