### ISSUE TITLE
[Bug] Some js file not loading on older devices

### ISSUE THREAD

**Issue by lowwor** [ankidroid/Anki-Android#9963]
I'm using closet with anki-droid. It looks like the version of webview available on older versions of android is more restrictive as to not inferring text/javascript as the type for files loaded with type="module" that have no type.
![image](https://user-images.githubusercontent.com/5444033/144440940-9cc655f7-fa1b-418a-ae01-2632af9c1ecc.png)
Solution would be similar with the following pr 
https://github.com/ionic-team/cordova-plugin-ionic-webview/pull/629/files
quote following lines in IonicWebViewEngine.java
```
                        String extension = MimeTypeMap.getFileExtensionFromUrl(path);
                        if (extension != null) {
                            if (path.endsWith(".js") || path.endsWith(".mjs")) {
                                // Make sure JS files get the proper mimetype to support ES modules
                                mimeType = "application/javascript";
                            } else if (path.endsWith(".wasm")) {
                                mimeType = "application/wasm";
                            } else {
                                mimeType = MimeTypeMap.getSingleton().getMimeTypeFromExtension(extension);
                            }
                        }
```

**Comment by mikehardy** [comment]
Interesting - can  you include the debug info requested in the information template, so we may understand versioning of the affected environments better? 

You deleted that section but it's useful: 
https://github.com/ankidroid/Anki-Android/blob/81bebb51c90c6c3813233d42d1a8f819e51cbaf7/.github/ISSUE_TEMPLATE/issue_template.md?plain=1#L25-L26

**Comment by mikehardy** [comment]
For anyone working on this, once you can reproduce it based on the versions provided, I *think* the issue will be located here:

https://github.com/ankidroid/Anki-Android/blob/81bebb51c90c6c3813233d42d1a8f819e51cbaf7/AnkiDroid/src/main/java/com/ichi2/utils/AssetHelper.kt#L52-L54

referenced from here https://github.com/ankidroid/Anki-Android/blob/81bebb51c90c6c3813233d42d1a8f819e51cbaf7/AnkiDroid/src/main/java/com/ichi2/anki/AbstractFlashcardViewer.java#L744-L749

**Comment by lowwor** [comment]
> Interesting - can you include the debug info requested in the information template, so we may understand versioning of the affected environments better?
> 
> You deleted that section but it's useful: https://github.com/ankidroid/Anki-Android/blob/81bebb51c90c6c3813233d42d1a8f819e51cbaf7/.github/ISSUE_TEMPLATE/issue_template.md?plain=1#L25-L26

Here is the debug info:
``` 
AnkiDroid Version = 2.15.6

Android Version = 9

Manufacturer = OnePlus

Model = ONEPLUS A3010

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 9; ONEPLUS A3010 Build/PKQ1.181203.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/66.0.3359.158 Mobile Safari/537.36

ACRA UUID = f5e31891-77e1-4261-bba6-c94ad4abf1f0

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true
```

**Comment by lowwor** [comment]
The js url is "https://appassets.androidplatform.net/__closet-0.5.3.js" and URLConnection.guessContentTypeFromName(path)  return null for this.

**Comment by ajinendra05** [comment]
hello @mikehardy , I'm new in community  and I'm truly interested in your idea of AnkiDroid can you please enroll me some good fixes to fix .

**Comment by mikehardy** [comment]
Hi there! Welcome! I linked the area of code above, and the issue submitter has already proposed a solution, I don't believe I have more to offer with regard to possible solutions, I think it's all there

**Comment by david-allison-1** [comment]
Adding to the unit tests would be a great place to start:

https://github.com/ankidroid/Anki-Android/blob/1152e0e0df4bad802e9cd4edbba59cc550b5b113/AnkiDroid/src/test/java/com/ichi2/utils/AssetHelperTest.java#L26-L31

**Comment by lowwor** [comment]
Opened a pr for this. #9971

**Comment by pree-T** [comment]
Is this issue still open?May I work on it?

**Comment by david-allison-1** [comment]
> Is this issue still open?May I work on it?

There's an active pull request. Please pick another issue

**Comment by mikehardy** [comment]
The next alpha will have the fix, I will generate one either today or tomorrow depending on how all the merges today go. Thanks for not just logging it but also fixing it! :trophy:
