### ISSUE TITLE
[Bug] flashcards seem to be added to the wrong deck

### ISSUE THREAD

**Issue by victorpgm** [ankidroid/Anki-Android#9964]
I have a problem when I want to add a flashcard, I create a flashcard and when I finish it is on another deck, and i've tried to see if i had made a mistake or i put in a wrong folder, but the same thing always happens. In short, my flashcards appear on others in the wrong deck

**Comment by david-allison-1** [comment]
Settings to check:

* Settings - AnkiDroid - Deck for new cards
* Deck Picker - Manage Note Types - Long Press - Cards - Card - Deck Override
