### ISSUE TITLE
[Bug]AnkiDroid Version = 2.15.6  Android Version = 11  Manufacturer = samsung  Model = SM-T970  Hardware = qcom  Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-T970 Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.45 Safari/537.36  ACRA UUID = 1ed35a15-ecf3-4d76-a2ce-d2ce7601dfa9  Scheduler = std  Crash Reports Enabled = true  DatabaseV2 Enabled = true

### ISSUE THREAD

**Issue by Bedaryosif** [ankidroid/Anki-Android#9967]
###### Reproduction Steps

1. 
2. 
3. 

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [ ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there! With apologies, this report contains no information about what you are trying to do, what you expect to happen, and what happens instead, so it is not actionable
