### ISSUE TITLE
[Bug] Tapping resources button registers as a tap to answer the card

### ISSUE THREAD

**Issue by absoluteinc** [ankidroid/Anki-Android#9974]
###### Reproduction Steps

1. Use AnkiDroid 2.16alpha34
2. Have tap gestures on. My settings are tap anywhere and it shows the answer. With answer shown, tap anywhere for "good".
3. Tap to show the card answer. Attempt to click the resources button to show more information, and it does so but also registers it as a tap to answer good, and moves onto the next card.

###### Expected Result

Should just open the resources

###### Actual Result

Opens resources and also answers good simultaneously.

###### Debug info
AnkiDroid Version = 2.16alpha34

Android Version = 11

Manufacturer = samsung

Model = SM-G973U

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; SM-G973U Build/RP1A.200720.012; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.45 Mobile Safari/537.36

ACRA UUID = 487fa2e4-17f0-4422-8e3f-dcf2a6ee4f3b

Scheduler = std2

Crash Reports Enabled = false

DatabaseV2 Enabled = true

https://user-images.githubusercontent.com/85033548/145508444-5958cdd8-14ed-45b2-8620-7d3f3af88193.mp4

^All I'm doing here is tapping once to show the answer, then I clicked on the "First Aid" button once. As you can see, it opens the corresponding First Aid image, but also clicks "Good" on the card and moves onto the next. 

###### Research
*Enter an [x] character to confirm the points below:*

- [ x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [ x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [ x] I have searched for similar existing issues here and on the user forum
- [x ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by absoluteinc** [comment]
This issue is still present even with the setting "Ignore touch gestures on links" turned on. Tested issue still present on 2.16alpha36

**Comment by absoluteinc** [comment]
Tested issue still present on 2.16alpha38

**Comment by absoluteinc** [comment]
#9500 
#7340
These are issues that are identical and have yet to be solved

**Comment by BrayanDSO** [comment]
Closing this to join with #14303 since it's probably the only solution
