### ISSUE TITLE
[Bug] Ankidroid does not run in background

### ISSUE THREAD

**Issue by shundred** [ankidroid/Anki-Android#9975]
###### Reproduction Steps

1. I have checked and granted all the permissions to Ankidroid to run in background.
2. Sometimes answering a long question takes upto 10 minutes.
3. As soon as the screen turns off or I switch to another app the ankidroid timer (which logs time taken every-time to give the answer) stops, so the correct time is not logged.
4. For this I have to keep screen on which is unnecessary wastage of battery.

###### Expected Result

Ankidroid Timer in background or when display is off

###### Actual Result

Ankidroid timer not running in background

###### Debug info
Refer to the [support page](https://ankidroid.org/docs/help.html) if you are unsure where to get the "debug info".

###### Research
*Enter an [x] character to confirm the points below:*

- [x ] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x ] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x ] I have searched for similar existing issues here and on the user forum
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by mikehardy** [comment]
Hi there!
This is a specific choice from way back when: #1340
Others have noticed, and there was a *lot* of deliberation.

In the end this is not a behavior we will adopt: #4808, in particular this comment: https://github.com/ankidroid/Anki-Android/issues/4808#issuecomment-484934768

I understand this may not fit you personally but it is unfortunately not possible to be all things to all people without complicating the app even further

**Comment by shundred** [comment]
Thanks for your early reply, I have read whole #1340 and #4808

As in #4808 there are many reasons already mentioned for background timing,
there is no use in repeating that all again.

1. As it is mentioned in #1340 that the app used to log time even in
background back than.
2. An option can be provided in settings to switch between the desired
behaviour.
3. Theoretically saying (as I do not understand codes that much) is it not
possible to log time based on conditions (weather the app was in background
or not, for users who want timer to stop in background).
