### ISSUE TITLE
[Bug] Clozes containing curly brackets are not displayed correctly

### ISSUE THREAD

**Issue by Namnodorel** [ankidroid/Anki-Android#9976]
###### Reproduction Steps

1. Create a cloze with `}}` inside, eg. due to the use of MathJax, like `{{c1::\(\frac{f^{(k)}}{k + 1} = (\frac{\partial^k F}{\partial h^k})(0, t, u)\)}}`
2. Preview or view the created cloze

###### Expected Result
The cloze should render properly when viewing the front of the card and render the math equation when viewing the back.

###### Actual Result
The cloze rendering cuts off before the actual cloze is finished.
![Screenshot_20211211-010158_AnkiDroid](https://user-images.githubusercontent.com/10784607/145655874-355ab4fc-5e7c-46a2-b6c3-f292934f6fbe.png)

###### Debug info
AnkiDroid Version = 2.15.6
Android Version = 10

Webview User Agent = Mozilla/5.0 (Linux; Android 10; G8441 Build/QQ3A.200805.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/87.0.4280.101 Mobile Safari/537.36

Scheduler = std

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum (#5776 may be related but is stale)
- [ ] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

## Educated Guess
After making a quick search through the repo with an idea of where this bug might come from, I believe I have found the problem: The file

https://github.com/ankidroid/Anki-Android/blob/8f2e0946062f62c181228848ccdec71ec3ed1b43/AnkiDroid/src/main/java/com/ichi2/libanki/template/TemplateFilters.java

uses Regular Expressions to detect clozes. Regular expressions are a provably insufficient method for detecting patterns that involve "counting" (like matching parentheses or brackets). I believe that this is exactly what causes the issue. A mechanism that can parse context free grammars would be the appropiate alternative. I don't know if there are any conventional mechanisms for that in Java, but for such a simple case, a custom implementation for the special case of cloze detection might suffice.

**Comment by david-allison-1** [comment]
What does Anki desktop do here?

**Comment by Namnodorel** [comment]
> What does Anki desktop do here?

I hadn't disvovered it there because I don't review cards on it, but it appears to have the same issue.

**Comment by Namnodorel** [comment]
For Anki Desktop, it was actually already reported, here: https://github.com/ankitects/anki/issues/1012 
There is a workaround (placing spaces between closing brackets), but I disagree with the conclusion reached there that a fix would not be worth it. It's true that it would "break" cards that have mismatched brackets, but IMO those cards always should have been broken, as they use a broken syntax. 
At the same time, the issue forces cards that are perfectly fine syntactically to use workarounds to display correctly.

**Comment by mikehardy** [comment]
Unfortunately, the conclusion there is binding. We will / must follow their parsing rules. If this is altered upstream we will get the fix eventually as we share render code. As such, I understand the possible frustration but this is not actionable here
