### ISSUE TITLE
Text Formatting and message is unclear in synchronization dialog on home page

### ISSUE THREAD

**Issue by souravmunjal** [ankidroid/Anki-Android#9977]
<img width="322" alt="image" src="https://user-images.githubusercontent.com/30770269/145736290-2adabbf5-d2af-471a-b42b-69ba8217f0d3.png">

While synchronization process we see this dialog 
Issues and Suggestions - 
1. "Up" and "Down" are bit unclear if it is speed then it should be "Upload" and "Download" or if it is anything else it should be clear.
2. If it is speed it should be kbps instead of kb
3. Formatting of numbers is not right(it should be 3.2mb,and so on)

**Comment by Akshay0701** [comment]
can I work on this issue?

**Comment by UvrajSB** [comment]
@david-allison I want to work on this, can you please assign it to me?

**Comment by UvrajSB** [comment]
@david-allison what are we supposed to display in this dialog box. The changes I can infer are
1) Converting Up -> Uploaded and Down -> Downloaded
2) Changing the unit from KB -> MB -> GB when required
Can you please tell if I got it right or not
