### ISSUE TITLE
[Bug]Disabling "automatic display answer" disable "Keep screen on"

### ISSUE THREAD

**Issue by WiliTest** [ankidroid/Anki-Android#9984]
(I have this bug on both AnkiDroid 2.16alpha29 + AnkiDroid 2.16alpha33)

###### Reproduction Steps

1. In settings/Preference/Reviewing:  check the box "keep screen on"
2. (below) check the box "automatic display answer",
3. uncheck the box "automatic display answer",

###### Expected Result

"keep screen on" should be turned on

###### Actual Result

"keep screen on" is disabled 
(If it was on, it should stay on even if we turn off the "automatic display answer")

###### Debug info
AnkiDroid Version = 2.16alpha33

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = 7d455f46-b339-4c51-b645-a07708ae9194

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by david-allison-1** [comment]
Interesting, this has been a "feature" for over 10 years:

[6a9cbdda5836ff0117525f1f3eccfe3255e61fb9](https://github.com/ankidroid/Anki-Android/commit/6a9cbdda5836ff0117525f1f3eccfe3255e61fb9#diff-ec3df6b55bc76bab2c72db0119638135477383df6b90f7024018b4af22a4a8f4R245-R246)

**Comment by WiliTest** [comment]
@david-allison-1 
I don't understand.  
1) Do you mean that I'm the only one complaining about it since it has been implemented 10 years ago? 
Or 
2) do you mean that this "bug" is actually intended? (If so I don't understand why, since they are 2 separate features: I want to keep my screen on when I use "automatic display answer" and also when I don't use it).

**Comment by david-allison-1** [comment]
It was intended, you're the first person to mention it that I know of and the developer who wrote it no longer contributes to the project.

I have no idea why it was intended. [Chesterton's fence](https://en.wiktionary.org/wiki/Chesterton%27s_fence) says we should think about this before removing it.

Right now, I'm in support of removing tp his "feature"

**Comment by WiliTest** [comment]
Chesterton's fence is interesting! (But it should take into account the principle of "cultural evolution/coevolution" which state that cultural evolution is natural thus non-intelligent, and thus wobbly and full of s.../absurdity  ;-) )

**Comment by mikehardy** [comment]
Hmm. I can see how the features are tangled. Automatic display answer (especially with auto-answer/advance card) will not behave in an expected way if the screen turns off.

I can see how people would want the screen to stay on even during non-automatic review, in case they need to consider a card deeply.

I don't like having mixed toggles / settings but if the auto feature really needs it, they must be mixed in a way.

What about this - consider leave screen on as being two separate configurations - one is for keeping the screen on in general. This is the setting that is currently dependent on auto show answer but that you want to be separate, and should be independent. The second  would be actually hidden and 100% dependent on auto show answer, always enabled for auto-answer sessions. This would remove the screen off choice for auto-answer but is what the feature actually needs I think? And then you have independent control over screen off as a general setting.

To bind the feature of auto-advance more correctly to keep screen on when it needs it, I suppose you'd need to actually only keep the screen on for the greater of auto-show-answer delay + some reasonable amount of time for the question to visible or infinite if the user has enabled auto-answer/advance as well ?

**Comment by WiliTest** [comment]
Another option: before launching the _automatic display answer_, Anki could simply check the state of the checkbox _screen ON_. If it's not checked (=OFF) it just turns it ON during the _automatic display answer_ (=while its checkbox is checked). And after it (when its checkbox isn't checked anymore),  Anki can just put back checkbox "screen ON" like it was before (it would remain ON if it was ON before, or it would turn it OFF if it was like that).

**Comment by mikehardy** [comment]
That's the same behavior in effect, but if the features / toggles remain tangled and automatic display answer is twiddling them temporarily, then if the app crashes (or is just terminated in the background as the platform reserves the right to do) then the setting could be left permanently in the state that was intended to be temporary

**Comment by WiliTest** [comment]
It still doesn't work.

**Comment by BrayanDSO** [comment]
@WiliTest Have you tried one of the latest alpha releases? I fixed this a while ago

**Comment by WiliTest** [comment]
> @WiliTest Have you tried one of the latest alpha releases?

Thanks a lot for having work on this issue and for taking the time to reply!

No, I did not try yet. I'm on 2.16alpha70, and, as usual, I'll lose my settings by trying to update (if I must come back because of a bug). But I will.
