### ISSUE TITLE
[Bug]Bug with the app colors in 2.16alpha32 (phone dark mode -not ankidroid night mode- not taken in account ?)

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#9985]
###### Reproduction Steps

1. use Anki with the phone in Dark mode (this is the phone settings, not the night mode in Anki)
2. install AnkiDroid-2.16alpha32-armeabi-v7a.apk
3. open the app (the phone should still be in Dark mode)

###### Expected Result
The app colors should be the same as in the previous version (AnkiDroid-2.16alpha29-armeabi-v7a.apk)

###### Actual Result
The app colors are different and the two options in Preferences> Appearance> Day theme and Night theme doesn't work. 
Even though the Dark mode is on, the app colors are the same as the one with the dark mode turn off in the previous version. 

Old color (when using AnkiDroid-2.16alpha29-armeabi-v7a.apk):
![Screenshot_2021-12-16-18-16-57-474_com ichi2 anki](https://user-images.githubusercontent.com/15843700/146421122-688ae58d-733f-44b2-902b-1def42511465.jpg)

New color (when using AnkiDroid-2.16alpha32-armeabi-v7a.apk):
![Screenshot_2021-12-16-18-23-35-042_com ichi2 anki](https://user-images.githubusercontent.com/15843700/146421159-37b83bab-5a08-4648-b1d5-42af69c138af.jpg)

###### Debug info
Before the 2.16alpha32 I had installed: AnkiDroid-2.16alpha29-armeabi-v7a.apk

AnkiDroid Version = 2.16alpha32

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.85 Mobile Safari/537.36

ACRA UUID = ba2a7ac3-aa20-4edc-8251-0b3de0ebd8be

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by MagTun** [comment]
I wanted to debug a bit further by activating / deactivating the dark mode on the AnkiDroid-2.16alpha29-armeabi-v7a.apk (it could be that AnkiDroid-2.16alpha32-armeabi-v7a.apk doesn't take into account which mode the phone is currently in) but I can't reinstall it to check.
After the installation process, I get a "App not installed" probably because the current version is higher ? How can I downgrade?

**Comment by mikehardy** [comment]
Do you have the non-standard vendor-specific we-can't-really-handle-it "forced dark mode" turned on in the phone settings?

**Comment by MagTun** [comment]
Yes I do! (You probably haven't see the updated subject/first post which mentions the "phone dark mode").

I didn't know that this "phone dark mode" was so difficult to handle for developers... but it worked great until at least AnkiDroid-2.16alpha29. 

So does this mean that, in the next update(s), AnkiDroid won't detect the dark background anymore and that to have a dark background on the main page,we will have to use AnkiDroid nigh mode? 

This would be a terrible option because AnkiDroid nigh mode changes all the colors (even the one that are hard coded in HTML which are keept by the phone dark mode).

**Comment by mikehardy** [comment]
Correcting ankidroid night mode is the goal. We must not (and cannot) rely on any non-standard vendor-specific modes. Honestly, MIUI as a vendor should be shunned from the community and disallowed to use AOSP as a base given what they do, and the trouble it causes us as developers. I feel pretty strongly about that.

**Comment by david-allison-1** [comment]
This is intentional, until very recently, we haven't been able to test MIUI's night mode, and it introduces a large amount of issues. 

Many people can't figure out how to insert images/audio because it breaks horribly breaks accessibility guidelines. This is a major degradation of functionality to new users.

I don't currently have the time to fix (or even list) all the compatibility issues that MIUI has introduced with this feature. I'd potentially be willing to maintain this feature once all of the issues are fixed, but let's cross that bridge when we come to it.

> This would be a terrible option because AnkiDroid nigh mode changes all the colors (even the one that are hard coded in HTML which are keept by the phone dark mode).

Night mode color inversion can be disabled by adding `.night_mode {}` to the CSS of a card template.

**Comment by MagTun** [comment]
@david-allison-1, I didn't know about the option `.night_mode {}` and it works great, thanks for that! 


@mikehardy  and @david-allison-1, Since it's possible to prevent the color inversion, I agree that a better ankidroid night mode is the way to go and that relying on vendor specific settings is a bad option. @david-allison-1, if the ankidroid night mode is good, than you should have to spend time fixing the MIUI dark mode. But for the moment ankidroid night mode isn't great because the white is too white and quite agressive: too me a greyish white (maybe like `rgb(216, 216, 216)`)  would be better.  Also the   `.night_mode {}` should be documented. Maybe, it could be a popup the first time the dark mode is activated: "To prevent color inversion in your cards, add .night_mode {} to the CSS of a card template." with a checkbox to not "do not display the next time").

**Comment by MagTun** [comment]
`.night_mode {}` works great when added to the CSS of a card template, but not when it is added to an imported css located in collection.media (using `@import url()`). 
Is there a way to make this rule work from an import CSS?

**Comment by david-allison-1** [comment]
Not currently

**Comment by ShridharGoel** [comment]
@mikehardy @david-allison-1 There's a way to disable the forced dark theme, should we try that?

**Comment by mikehardy** [comment]
Maybe? I think David looked into this and we were weary until we could test. He's got a test device now at least, but the new semi-barrier is apparently that developing for it is a terrible experience, not your standard android dev experience

**Comment by ShridharGoel** [comment]
This isn't happening when I tried on Redmi Note 8.

@MagTun What's the MIUI version of your device?

**Comment by MagTun** [comment]
MIUI Global 12.5.3

**Comment by david-allison-1** [comment]
> There's a way to disable the forced dark theme, should we try that?

That's the cause of this issue. I've disabled the forced dark theme, and this issue is due to the fact that I've removed it.

> Maybe? I think David looked into this and we were weary until we could test. He's got a test device now at least, but the new semi-barrier is apparently that developing for it is a terrible experience, not your standard android dev experience

Something changed automatically and I can now attach ADB.

**Comment by david-allison** [comment]
We now match the phone theme, I believe this is completed.
