### ISSUE TITLE
In automatic display answer/timeout answer: add a "do nothing" 

### ISSUE THREAD

**Issue by WiliTest** [ankidroid/Anki-Android#9987]
**Is your feature request related to a problem? Please describe.**
I would like to use automatic display answers to review some new and old cards but without registering the new review (nor burying the card). I just want to make some "shallow/lazy review" sessions that won't change anything. 

(I already use this for new cards when my hands aren't available and my mind half busy. But I have to reset all the progress after it.  A "do nothing" would skip the "reset progress" on the new card, and would allow me to review also others cards. Yes, it's shallow learning but I find it quite satisfying: it's better to do many shallow reviews in a day than no review at all.

**Describe the solution you'd like**
In automatic display answer/timeout answer: add a "do nothing"

**Comment by SSTG** [comment]
I would like to work on it. Can someone assign this to me?

**Comment by mikehardy** [comment]
Hmmm - this would have us differing from upstream a little bit, but I do understand the possible utility. I'm going to invoke @dae here - Damien, what do you think about automatic review having a "do nothing at all just keep on going through cards..." option for the "what to do when advancing to next" set of options? Maybe people want to just listen with headphones while sleeping ;-).

**Comment by dae** [comment]
The default behaviour in AnkiMobile is to bury cards, which approximates this use case. Doing absolutely nothing would result in cards reappearing when queues were rebuilt in the v1/v2 scheduler.

**Comment by david-allison-1** [comment]
I'd prefer not to introduce a "do nothing" if at all possible as that will add additional complexity to the scheduling.

**Comment by mikehardy** [comment]
That's two solid reasons not to, an interesting idea then but I'm going to close this as "won't fix"

**Comment by WiliTest** [comment]
I don't understand why "doing absolutely nothing" would add an "additional complexity to the scheduling". But I'm sure you know what you are talking about.

> Maybe people want to just listen with headphones while sleeping ;-).

Some people would like to study even when their hands aren't available (eg. while working with my hands, doing sport...). 

I completed my request above, to show why I believe this feature is important.
