### ISSUE TITLE
[solved] Do I have to uninstall my existing AnkiDroid version to downgrade? (How to downgrade/revert?)

### ISSUE THREAD

**Issue by WiliTest** [ankidroid/Anki-Android#9988]
**Do I have to uninstall my existing AnkiDroid version to downgrade?** 
yes
**will uninstalling wipe away my data?**
no
**Will uninstalling wipe away my settings?**
Yes sometimes (I did lose them, but somehow my friend did not). But reinstalling my most recent backup fixed it: it reinstalled the settings).

(We struggle to find this information, so with this post, it will be more visible).

**Comment by david-allison-1** [comment]
Yes. Android doesn't allow version downgrades without uninstalling.

You may want to use a Parallel Release in future: https://github.com/ankidroid/Anki-Android/releases/
