### ISSUE TITLE
[Feature request] Make it easy to call event/custom functions when performing actions (ex: adding TTS when clicking on the answer buttons or performing a gesture)

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#9993]
**Is your feature request related to a problem? Please describe.**

I use Ankidroid while running and it's not easy to see the little dots that show which answer button has been clicked. Also, I have set up several gestures like sliding left and right and sometimes I make these gestures unintentionally and I don't see the little notification like "card suspended" so I am sometimes unaware that I sent a gesture/action. 

**Describe the solution you'd like**

To fix this, I thought it would be great to have an easy way to add events function when clicking the answer buttons or performing a gesture, A simple implementation would be able to activate a TTS when an action is performed in settings. Another more complex would be to be able to add these functions via the Note template. 

**A imperfect workaround and some suggestions**

For the long story, I was able to partially do what I wanted: [add TTS when the buttons are pressed](https://github.com/MagTun/AnkiDroid-Custom-Card) (but not for the gesture) 

To do that I modified the templates written by [Infinyte7](https://github.com/infinyte7/Anki-Custom-Card-Layout) [btw @Infinyte7, thanks so much for having shared them!] but this workaround isn't convenient for several reasons:  

1) It doesn't allow me to add TTS when the gestures are performed (ex: sliding left/right) 
   - possible solution: the feature request above would solve this  
  
  
2) To add the TTS to the answer button, I had to remove the original buttons (by enabling the fullscreen mode with the button) and add them back via a JS script in a note template. The problem is that the fullscreen mode is a "general settings" (which affects all my decks) and the JS script affects only a single note template. I have more than ten decks each with one or several different templates and because of this setup, I have to edit all the templates (more than 20) just because the fullscreen mode is a general setting and not in the deck options.  
   - possible solution: possibility to override the fullscreen general settings via deck options.
   
  
3) The fullscreen mode also hides the top bar which I use a lot (for things like editing the note, card info, and rescheduling). I can still slide the top part to make it appear but it's not really convenient when I wear gloves. 
   - possible solution: add a fourth option in the fullscreen menu: hide only answer buttons and not the top bar

  
4) I was able to add the card count for the review (via the _js_addon_button_cardcount, thanks again to Infinyte7) but I couldn't find a way in the AnkidroidJS docu, to underline the count to which the current card belongs (new, learn, review) 
   - possible solution 1: possibility in full mode to hide only the answer buttons
   - possible solution 2: possibility to extract via AnkiDroidJS the "status"(?) of the card: new, learn or review. 

  
**Others comments:**
a) When a script in collection.media is updated (either on android or on the computer), the modifications are not synced to the other device, even when a full upload is done.   

b) It takes a lot of time to open the folder collection.media (like 50secs or so), so it's cumbersome to edit the scripts that are located in this folder (which need to be done because of the comment above).  Is there another location where these "general scripts" could be located? [I solved this by using a code editing app Acode with the script kept open in it, so I don't have to open the collection.media folder on my Android each time I need to edit them, but still it would be great to have a separate folder for the scripts]  

c) I add some of the fields via js with something like myDiv.innertext = `{{front}}`; but then if one of the fields in my card contains the `, the script crashed.  (Actually before using ` to enclose the field, I was using '  and " which I use a lot in my field, so but I switch to ` which I do not )

**To the AnkiDroid team:**
If you think some of these comments are relevant, I can open separate features to make it easy for you to keep track of the request. I just didn't want to overflow you with many requests.

**Comment by infinyte7** [comment]
Some if these can be implemented using already provided JS API. I may reply on it later.

**Comment by MagTun** [comment]
@infinyte7, I looked into the files mentioned in some of your pull requests concerning the JS API but I couldn't find any information about the features I have mentioned above. If you have the time to explain how they can be implemented, or if you can just point me to the files (I am not very good at JS but I may understand a bit), I would really appreciate it.

**Comment by infinyte7** [comment]
@MagTun 
>see the little dots that show which answer button has been clicked

1. Add [custom button](https://github.com/infinyte7/Anki-Custom-Card-Layout/blob/master/Example%204/front.html#L55-#L70) at bottom
2. Set [timeout ](https://www.w3schools.com/jsref/met_win_settimeout.asp)
3. Now in timeout JS code, use if_else condition to know the button pressed. Show the dots using HTML/CSS class. 
4. After timeout call the function for pressed button to move to next question.  

>TTS when clicking on the answer buttons

Similar to above but here in timeout function call TTS function, then call JS API to answer, then move to next question.

> possible solution: possibility to override the fullscreen general settings via deck options.

Addons development is in progress, it will be used to add global settings to all decks. Till then patience. 

> possible solution: add a fourth option in the fullscreen menu: hide only answer buttons and not the top bar

PR is appreciated for this. 

> to underline the count to which the current card belongs (new, learn, review)

Use [Card Type](https://github.com/ankidroid/Anki-Android/wiki/AnkiDroid-Javascript-API#card-type) to find the new, learn, review, then uderline the card counts. 

> performing a gesture

API not exposed for this.

_I may not able to provide detailed solution before mid January. (Sorry)_

**Comment by MagTun** [comment]
Thanks for your quick answer! 
Sorry I wasn't clear enough, concerning the little dots and the TTS, I was able to found a similar [solution](https://github.com/MagTun/AnkiDroid-Custom-Card/blob/main/0000_00_js_addon_button_back.js#L84-#L118)  (actually I don't display the little dots but I change the background color for a couple of seconds so it's clearly visible).  


> Addons development is in progress, it will be used to add global settings to all decks

This is such a good news! 

> add a fourth option in the fullscreen menu: hide only answer buttons and not the top bar

I am afraid my level of JS is too low for that, I will still have a look (if it's java, I don't stand a chance) 

> Card Type

Thanks for that!

> performing a custom function (like TTS) on a gesture

Would there be a way to do it by adding some settings in the general/deck settings? 

Please don't reply before mid-January, you are already amazing for answering so quick. And again thanks a lot for this, and all you do for Anki!
