### ISSUE TITLE
[Bug] App crashes when changing deck on "deck browser" and "statistics" (AnkiDroid-2.16alpha32-armeabi-v7a.apk)

### ISSUE THREAD

**Issue by MagTun** [ankidroid/Anki-Android#9994]
###### Reproduction Steps

1. open  "deck browser" or "statistics" 
2. tap on the deck name to change deck

###### Expected Result
The decks menu should open

###### Actual Result
The app crashes

###### Debug info
AnkiDroid Version = 2.16alpha32

Android Version = 10

Manufacturer = Xiaomi

Model = Redmi 7A

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 10; Redmi 7A Build/QKQ1.191014.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/94.0.4606.85 Mobile Safari/537.36

ACRA UUID = ba2a7ac3-aa20-4edc-8251-0b3de0ebd8be

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

###### Research
*Enter an [x] character to confirm the points below:*

- [x] I have read the [support page](https://ankidroid.org/docs/help.html) and am reporting a bug or enhancement request specific to AnkiDroid
- [x] I have checked the [manual](https://ankidroid.org/docs/manual.html) and the [FAQ](https://github.com/ankidroid/Anki-Android/wiki/FAQ) and could not find a solution to my issue
- [x] I have searched for similar existing issues here and on the user forum
- [x] (Optional) I have confirmed the issue is not resolved in the latest alpha release ([instructions](https://docs.ankidroid.org/manual.html#betaTesting))

**Comment by Akshay0701** [comment]
I will like to solve this issue, can anyone assign this issue to me?

**Comment by Akshay0701** [comment]
@MagTun I am not able to reproduce this issue in my device 

AnkiDroid Version = 2.16alpha29

Android Version = 11

Manufacturer = OnePlus

Model = GM1911

Hardware = qcom

Webview User Agent = Mozilla/5.0 (Linux; Android 11; GM1911 Build/RKQ1.201022.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/96.0.4664.104 Mobile Safari/537.36

ACRA UUID = cc4ed13e-3ce2-4b59-b293-0c5a29ea94f9

Scheduler = std2

Crash Reports Enabled = true

DatabaseV2 Enabled = true

**Comment by Akshay0701** [comment]
@MagTun we will try to fix this issue soon, for now you can use [AnkiDroid 2.16alpha29](https://github.com/ankidroid/Anki-Android/releases/download/v2.16alpha29/AnkiDroid-2.16alpha29-arm64-v8a.apk) version its doesn't have this issue.

**Comment by Akshay0701** [comment]
I can't able reproduce this error in the new version of AnkiDroid, seems like the error has been resolved, I am closing this issue for now, if you again faced this problem do let me know,

Thanks
