### ISSUE TITLE
Unable to add images to note

### ISSUE THREAD

**Issue by ma54ik** [ankidroid/Anki-Android#9995]
I'd like to add a image to a note, but the App doesn't give me that option at add note.
The manual says, that on the right hand side of the input box suppose to be a small paperclip, which gives you that option, but it doesn't show up.

I use android 11 and version 2.15.6 of AnkiDroid

Thanks in advance!

**Comment by david-allison-1** [comment]
You're probably using a Xiaomi phone: disable Xiaomi's "auto night mode" and enable AnkiDroid's night mode and it'll appear.

**Comment by Lokawn** [comment]
I got the same issue. Solved with @david-allison-1's advise

**Comment by ma54ik** [comment]
> You're probably using a Xiaomi phone: disable Xiaomi's "auto night mode" for AnkiDroid and enable AnkiDroid's night mode and it'll appear.

Thank you, it works now!
